### ISSUE TITLE
Issue Accessing Data / Google PageSpeed Insights

### ISSUE THREAD

**Issue by andrewkoski** [google/site-kit-wp#1]
I currently have the plugin on https://poisar.com. The issue seems that after the integration, the PageSpeed Insights API has some sort of data error. I properly enabled the PageSpeed API and only have restrictions as it pertains to utilizing poisar.com and *.poisar.com/* via the API. Please reference the following images.

![123](https://user-images.githubusercontent.com/13125986/59787537-8bc52b00-927e-11e9-8f27-508afbbbdfed.png)

![1234](https://user-images.githubusercontent.com/13125986/59787552-9384cf80-927e-11e9-93ea-7913eefd6d9e.png)

![12345](https://user-images.githubusercontent.com/13125986/59787559-98498380-927e-11e9-8ddb-ae7a959c910b.png)

**Comment by andrewkoski** [comment]
Also, I should add that I allowed for Less secure app access to run in my Google Account.. but that didn't help either. Also, the Analytics aren't properly appearing. (As shown below.)

![12345678](https://user-images.githubusercontent.com/13125986/59788346-5ae5f580-9280-11e9-8560-7c4d7b392556.png)

**Comment by jamesozzie** [comment]
Try setting the applications restrictions to "None" and then deactivate Site Kit. (Settings > Admin > Reset Site Kit). Then add Page Speeds Insights again. Once thats done add the restrictions again to your site using *poisar.com* and wait a few minutes before checking your dashboard. 

The view for your Analytics dashboard seems ok, if your website was just setup new. Did you select the correct property ID after you selected the correct account?

**Comment by andrewkoski** [comment]
So the restrictions are what caused the PageSpeed Insights from working.
As for the Analytics though, they still are not working.. even after reloading the plugin.
I did select the correct property, etc.. but still no luck. :/
![12](https://user-images.githubusercontent.com/13125986/59796335-15cabf00-9292-11e9-8ed4-41fc689abf13.png)

**Comment by jamesozzie** [comment]
@andrewkoski We will need to investigate this further. Can you let me know what version of WordPress you are using and if you are using any caching or other Analytics/reporting plugins?

**Comment by jamesozzie** [comment]
@andrewkoski I will close this ticket as your Page Speed Insights are working. I have opened one for the Analytics specifically [here](https://github.com/google/site-kit-wp/issues/11).
