### ISSUE TITLE
Technical error

### ISSUE THREAD

**Issue by nomicool** [google/site-kit-wp#10]
after uploading plugin receiving following error The site is experiencing technical difficulties.

**Comment by jamesozzie** [comment]
@nomicool Do other plugin installs work and can you install work via FTP/SFTP?

**Comment by nomicool** [comment]
Yeah other plugins are working fine i got error while activating google kit

**Comment by jamesozzie** [comment]
@nomicool Was the error when activating or installing? There could be a plugin or theme conflict but we'll need to know more. Can you activate another theme and deactivate other plugins before trying to install Site Kit again, in a new Chrome incognito window? 

Please also let me know the following (in particular any errors in Chrome dev console log):
- Errors in Chrome dev console
- URL / Site
- Theme being used
- PHP Version
- WordPress Version
- Any firewall/security plugin you are using

**Comment by jamesozzie** [comment]
@nomicool I will close this ticket as I didn't receive a response and I am unable to replicate the issue. If the problem persists feel free to reopen. If so please also let us know as much of the following as possible: 

- WordPress Version: 
- Web Host OS: 
- Site Kit Plugin version: 
- Browser: 
- Operating System: 
- PHP Version: 
- Site Kit install method (WP dashboard upload, FTP, version control etc)? 
- Any firewall/security plugin in use: 
- Chrome Dev tools error console messages: 
- Active theme: 
- Website URL:
