### ISSUE TITLE
AdSense panel - Restricted metric(s)- Convert the referenced URL to a link

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#100]
## Bug Description

There is a referenced URL for when a user adds the AdSense panel (The referenced URL appears in a blue panel, "Restricted Metric(s)"). It appears when a user does not connect AdSense to their Analytics. Rather than just referencing the URL this could be converted to a link, allowing for easier navigation to that resource. 

## Steps to reproduce

1. Add AdSense module
2. Don't connect AdSense to Analytics
3. Visit the main Site Kit dashboard (AdSense panel)

## Screenshots

![R7uZmkhoF5c](https://user-images.githubusercontent.com/41326532/60501405-e796a780-9cb3-11e9-816c-8d41180d49e7.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics API error message about "Restricted metric(s)" that can be returned when AdSense is active but not linked to the active Analytics property should be enhanced so that the URL included in the message is rendered as an actual (external) link.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by johnPhillips** [comment]
@felixarntz - @wpdarren and I have been unable to recreate this issue. It seems to be quite old as well - wondering if it is still a problem?

**Comment by wpdarren** [comment]
@johnPhillips I can have a look at trying to recreate this and come back to you.

**Comment by felixarntz** [comment]
@johnPhillips @wpdarren Oh you're right - apologies, I missed that we had already prevented this error to show up. In such a case the user now already always sees the `AdSenseLinkCTA` component output, which is good as is.
