### ISSUE TITLE
Analytics connection & authenticate not working

### ISSUE THREAD

**Issue by dionisis17** [google/site-kit-wp#1001]
Hello, I have test in two wp sites site kit plugin and in both sites I can not authenticate the account cause I get an error page (attachment) when I click in final step " I confirm". I disable the known plugins but nothing...
![sk2](https://user-images.githubusercontent.com/53856507/71532288-58cdb500-28fb-11ea-8e76-cf283b562d9a.png)
![sk1](https://user-images.githubusercontent.com/53856507/71532290-59664b80-28fb-11ea-97c2-d895e9c4d4d8.png)

Thank you very much for this excellent plugin!

**Comment by jamesozzie** [comment]
@dionisis17 Thanks for reporting. We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue.
