### ISSUE TITLE
Expose PHP-to-JS data on more script-specific and private globals

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1004]
The public JavaScript API of the plugin is going to live on the `googlesitekit` global. However, at the moment, this global is mostly used to expose server-side data on the client, via `wp_add_inline_script()`. This results in two issues:

* The public API object includes random data that should never be accessed directly (except in the future respective datastore resolver).
* One global is overused to just dump almost anything into it.

Some work in this was already kicked off as part of #981.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHP data that needs to be available in JS...
    * ...should not be exposed on `googlesitekit`
    * ...should be exposed on more specific globals, relevant to certain JS assets and tied into a relevant `before_print` callback
    * ...should be exposed on globals prefixed with `_googlesitekit`
* The `googlesitekit-admin` script should be renamed to `googlesitekit-base` because that is effectively what it is. It contains minimum functionality and dependencies and can be enqueued any time Site Kit needs to do anything.

## Implementation Brief

* Create a new `Assets\Script_Data` class as a sub-class of `Script`
    - Should **require** a new `$args['global']` key with the name of the global variable that the data will be set to
    - Should **require** a new `$args['data_callback']` key with a function to call to "lazy-load" the data only when the `Data` is to be printed
    - Should **not** accept an `$args['before_print']` key, as this will be overridden with an internal function to set the data on the `WP_Dependency` right before it is about to be printed by WP (See **Historical context** below for more info as to how this should be done and why).  
    _We could technically support both I think but that should be unnecessary_
* Migrate global data variables to named `Assets\Script_Data` instances in `Assets::get_assets()`
    - `_googlesitekitBase`
    - `_googlesitekitAPIFetchData`  
    _Ideally this could be shared by E2E tests as well but that may not work if any API utilities need to still work when the plugin is inactive_
* Update `Script` assets to define required data in their list of dependency handles
* ~~Update consuming code to source data via imports rather than touching globals directly~~
_To do in a follow-up issue or part of ongoing JSR work - See Historical context below._

<details>
<summary>Historical context</summary>

#### Migrate inline "data" scripts to named "virtual" data-only scripts
WordPress supports registering scripts as "aliases", that is you get all the benefits of the dependency system, without requiring an actual script src.

We can then add data-only `Script` instances using a convention (the class is final, otherwise we could simplify this a little with a sub-class)

```php
new Script(
    'googlesitekitdata_prop',
    array(
        'src'          => false,
        'before_print' => function ( $handle ) {
            // Allow the value to be extended.
            $data = apply_filters( 'googlesitekit_data_prop', array(
                'foo' => 'bar',
            ) );
            wp_localize_script( $handle, '_googlesitekitData_prop', $data );
        }
    )
),
```

Here we have declared the data object as its own named asset, which other scripts can declare as a dependency. WordPress will make sure it is enqueued and output automatically before any dependent scripts. The `before_print` callback allows us to lazy-load the data that we pass to WordPress which can output the `script` tag for us.

~~Since we have `before_print` we can actually use this technique for any arbitrary code using `wp_add_inline_script`, not just data objects.~~
WordPress does not support using `wp_add_inline_script` with aliases before v5.0 so in order to remain compatible with WP 4.7 we will need to use another method.

WP does support using `wp_localize_script` but this function casts all scalar values of top-level keys to strings which is both unexpected and undesired. Instead we can use the same mechanism that `wp_localize_script` uses internally which looks like this (we're already using it):

https://github.com/google/site-kit-wp/blob/dcf1bdea088846545dc699147b404b68877496ca/includes/Core/Assets/Assets.php#L349-L354

### Update `Script` assets to define the data in its list of dependency handles

Once we have each data object defined as its own virtual script, we only need to add its handle to the scripts list of `dependencies` to make sure it's available.

e.g
```php
new Script(
    'googlesitekit_admin',
    array(
        'src'          => $base_url . 'js/googlesitekit-admin.js',
        'dependencies' => [ ...$dependencies, 'googlesitekitdata_prop' ],
    )
),
```
> Here `_googlesitekitData_prop` would be enqueued and available for the `googlesitekit_admin` script.

![image](https://user-images.githubusercontent.com/1621608/72071720-1fcb1280-32f5-11ea-9085-3b8e5d7c716f.png)

### Update consuming code

_This portion has been punted as part of this issue to be done as part of ongoing JSR work due to the large size and scope of this item in particular. See below for the original details for this section._

<details>
<summary>Original details</summary>

On the React side, we shouldn't really be reaching for globals directly. While we're at it, we should update the consuming code to read from these data/configuration objects as imports. We can leverage webpack aliases to map imports to the proper global and thus have a single place to change in the future should we need to.

I would imagine this should transition well in regards to the larger JSR work. We can then mock imports per test rather than mess with globals, but we could still do that if needed.

This is probably the largest part of the work to do as global use is fairly ubiquitous across the codebase, storybook, and tests.
</details>
</details>

## Changelog entry

* Improve asset handling in PHP by introducing dedicated data-only scripts, to use as dependencies.

**Comment by aaemnnosttv** [comment]
@felixarntz what should be done with `Assets::get_inline_data` which accounts for most of the data in the `googlesitekit` global right now? Surely each one of those wouldn't be its own global?

**Comment by felixarntz** [comment]
@aaemnnosttv I think we should review all the properties on a case-by-case basis, and potentially re-group or entirely remove some of them. Parts of them may even be unused now. Note that this also ties in deeply with some of the JSR work: For example, the `googlesitekit-site` asset (see #999 and #1000) will require a couple of things from PHP, and most of those should therefore be in a global `_googlesitekitSite` that is inlined before that script specifically. We will have a few things in `_googlesitekitBase`, such as those that are even needed by the very minimum `googlesitekit-base` (`googlesitekit-admin`) script, but the goal here is to minimize the data in that one and move the data to globals that are specific to certain JS files.

I think this is more complicated than only restructuring properties on the current global to become their own global, so we may want to review this together and come up with a plan. It is not super-urgent though, I think it makes most sense in combination with the foundational JSR work.

Until we have restructured all the data, I'd like to leave the existing `googlesitekit` data (via `Assets::get_inline_data()`) completely untouched, to prevent unexpected issues. Once we have exposed everything that is still needed in the new way, we can start migrating - potentially even to using the datastore already.

**Comment by felixarntz** [comment]
IB ✅ 

I really like the idea of using script aliases! Probably the only thing that wouldn't work this way is including one of the data `after` a specific script (which we do currently in one place, but we don't actually need to). So that should be okay.

How do you want to implement this, given that we haven't defined yet how to reorganize all the data currently in `googlesitekit`?
For now, I feel like we might want to only use that implementation for `_googlesitekitBase`, and then for the current `googlesitekit` (which will mostly be beneficial to eliminate the direct accesses to the global and use imports instead). Splitting out further objects should probably be part of the respective issue that requires them (further JSR pieces).

**Comment by felixarntz** [comment]
@aaemnnosttv Let's limit the work in this one on the PHP side only for now.

* Put foundation for virtual script assets in place.
* Use it for `_googlesitekitBase` only for now.

Let's not touch the JS part, I think that's not worth the hassle at this point. We can better refactor these pieces once we have datastores for all of these.

Regarding splitting out parts from `googlesitekit`, this should happen in individual PRs for the respective datastores, using the same mechanism that the PR for here will put in place.

Can you check what the estimate for just the above would be? It's probably going to be less than 15 points. We might be able to do it in the next sprint then still.

**Comment by aaemnnosttv** [comment]
@felixarntz I've moved this back to IB for now, and updated it to reflect the updated vision here going forward.

> Let's not touch the JS part, I think that's not worth the hassle at this point. We can better refactor these pieces once we have datastores for all of these.

I agree, the JS portion was a bit ambitious and doesn't quite justify the effort right now.

> Use it for `_googlesitekitBase` only for now.

In addition to the base data, we should also use this for the APIFetchData (see IB).

---

The estimate has been updated as well so this is ready review again 👍

**Comment by felixarntz** [comment]
@aaemnnosttv 
I wonder whether we should make `Data` derive from `Asset` directly instead of `Script`: There are fields (`src`, `before_print`) which `Data` wouldn't support although its parent class `Script` does, which would be strange. We could do the following:
* We would then move `src` from the `Asset` constructor to both the `Script` and `Stylesheet` constructor, as this is actually where it is used. `Data` would not support that property.
* `before_print` would also be moved out of the `Asset` constructor, and the `before_print()` method would as well: Either to both `Script` and `Stylesheet` or (probably preferable) to a new `Asset_With_Before_Print_Trait` (there should be an interface then too).
* `fallback` should be entirely removed as we no long need it since we no longer bundle 3P assets.
* This would leave us with a clean `Asset` base that only supports `dependencies` and `version`, which is what every asset should have.

What do you think?

**Comment by aaemnnosttv** [comment]
> I wonder whether we should make `Data` derive from `Asset` directly instead of `Script`

I considered that although I chose `Script` due to its required implementation as a script in WP. It is registered and enqueued as a script, and its dependencies also (if any) can only be scripts.

> We would then move `src` from the `Asset` constructor to both the `Script` and `Stylesheet` constructor, as this is actually where it is used. `Data` would not support that property.

As a script it still needs `$args['src']` for use when registering, although it must always be `false` which could be set in the constructor.

> `before_print` would also be moved out of the `Asset` constructor, and the `before_print()` method would as well: Either to both `Script` and `Stylesheet` or (probably preferable) to a new `Asset_With_Before_Print_Trait` (there should be an interface then too).

This won't work I think because `Data` relies on the `before_print` handling to lazy-load its data using `data_callback`. It wouldn't support the `before_print` arg (although it _could_ if we wanted to). Did you perhaps mean `Script` and **`Data`** would get the trait and interface? I don't think it makes sense for `Stylesheet`.

> `fallback` should be entirely removed as we no long need it since we no longer bundle 3P assets.

👍 

> This would leave us with a clean `Asset` base that only supports `dependencies` and `version`, which is what every asset should have.

`version` isn't really relevant for `Data` since it isn't actually loaded by the browser. `Data` only supports `data_callback` (required) and `dependencies` (which can only be script handles).

---

Another alternative would be changing the hierarchy to be `Asset` -> `Data` -> `Script` instead of `Asset` -> `Script` -> `Data` as `Script` supports more things that `Data` does not.

I generally like the idea of using composition for shared code as an alternative to inheritance but we should be careful to not make things overly complex at the same time.

**Comment by felixarntz** [comment]
@aaemnnosttv Maybe for more clarity we should call the new class `Script_Data`. Let's go with the hierarchy you originally suggested `Asset` -> `Script` -> `Script_Data`, as script data is still a `Script`. Regular scripts would per WP still be able to depend on script data (and even vice-versa, although we'd probably never need that).

In other words, let's go with your original IB, just rename `Data` to `Script_Data`.

Also let's prioritize that as it would improve some other JSR work that's coming up shortly (e.g. #1000 and #1176). Would be great if you could pick implementation of this up as soon as the remaining 1.4.0 issues are through.

**Comment by felixarntz** [comment]
IB ✅ (pending `Data` renamed to `Script_Data`)

**Comment by aaemnnosttv** [comment]
> In other words, let's go with your original IB, just rename `Data` to `Script_Data`.

IB updated 👍

**Comment by cole10up** [comment]
Smoke test with latest develop, connected all services and ran a series of functional tests. All good from a manual perspective.

![image](https://user-images.githubusercontent.com/57115907/76183924-47204d80-6187-11ea-99fe-2698ab83c6ee.png)

**Comment by tofumatt** [comment]
QA ✅
