### ISSUE TITLE
Bounce rate changed from 90 to 45

### ISSUE THREAD

**Issue by bugsbunnyua** [google/site-kit-wp#1007]
## Bug Description

Good day! After installing the plugin sitekit, bounce rate on askyourfitnessquestion.com changed from 90 to 45. We are warring about getting incorrect data because of your plugin. Please, comment if sitekit can mislead data of Google Analytics.

## Additional Context

 - PHP Version: 7.3
 - Plugin Version 1.1.4

**Comment by jamesozzie** [comment]
@bugsbunnyua From your Analytics account can you confirm you have the reporting period set to 28 days?The primary tab may be displaying data from a different reporting period.  
![M1HZM2n](https://user-images.githubusercontent.com/41326532/71727696-062c5580-2e33-11ea-9a26-58a7d1709079.png)

If you've confirmed the correct reporting period can you also check whether you have any views setup and that the correct Analytics property is being used.

**Comment by bugsbunnyua** [comment]
@jamesozzie 
![photo_2020-01-04_09-32-54](https://user-images.githubusercontent.com/37905852/71763236-59a9ac80-2ee2-11ea-9161-22821caa00fc.jpg)

**Comment by jamesozzie** [comment]
@bugsbunnyua Thanks for adding the image. As we don't have access to your Analytics dashboards can you check whether your 28 day Analytics report matches with your Site Kit dashboard? If possible can you share screenshots of both.

**Comment by bugsbunnyua** [comment]
In attachment two screenshots? from GA and Dashboard of plugin. the data is the same

The issue is that the Bounce rate started to fall AFTER we installed the plugin
this can be seen from the previous screenshot

![714c7979f3a0e9271100b03cf549b80b](https://user-images.githubusercontent.com/37905852/72202824-ac4c1100-346c-11ea-89e3-fd18746b4e80.png)
![e607d41b807a5fbf95c708951843797f](https://user-images.githubusercontent.com/37905852/72202825-ac4c1100-346c-11ea-9b3d-4b22b47853b9.png)

**Comment by bugsbunnyua** [comment]
@jamesozzie sorry, can you answer the question above?

**Comment by jamesozzie** [comment]
@bugsbunnyua Apologies for the delay, we've been focusing general support over on the WordPress [support forum](https://wordpress.org/support/plugin/google-site-kit/). 

The issue you have been encountering should hopefully be addressed soon, it looks like a genuine bug which requires some work as you will see in issue #481. Thanks for your input (and screenshots), I'll add it to the existing open issue now.

**Comment by bugsbunnyua** [comment]
@jamesozzie This link #481 Our problem is not in the color of arrows

We have a lower bounce rate after installing the plugin
This is not a problem, but we want to know why the bounce rate was 90%, and after installing the plug-in it became 50-60%

That is:

When there was no plugin on the site, the bounce rate was 90%

When the plugin was installed, the bounce rate became 50-60%

What is the reason?

**Comment by jamesozzie** [comment]
@bugsbunnyua While the factors affecting bounce rates vary the plugin doesn't make alterations to the appearance or functionality of your website, key factors in bounce rates. Site Kit operates in the back end, pulling information from the various Google products and sharing with logged in users only. 

From a front end aspect Site Kit places minimal code snippets for the various Google products into your site, the same code snippets as you would insert manually if adding the various Google products. You can check those snippets by inspecting the source code of your website. With Site Kit disabled you can compare how your website looks and performs, you shouldn't face any differing user experience or performance. 

> When there was no plugin on the site, the bounce rate was 90%
> When the plugin was installed, the bounce rate became 50-60%
> What is the reason?

While there no disputing your bounce rate has changed it's difficult to pinpoint exact causes and would require digging deeper. As you are using AMP you'll need to take that into consideration also, ensuring you have your AMP analytics setup correctly.
