### ISSUE TITLE
Kadence Ascend theme portfolio

### ISSUE THREAD

**Issue by MrWonka** [google/site-kit-wp#1008]
## Bug Description

When the Kadence Ascend theme is installed, 

## Steps to reproduce

1. Activate the ascend theme
2. Create a page that uses the portfolio template, when items are added they will appear on the page
3. Enable Site kit

## Screenshots

![Untitled](https://user-images.githubusercontent.com/31148930/71773527-82569400-2f2c-11ea-89a7-c8aa19944906.png)
![Untitled2](https://user-images.githubusercontent.com/31148930/71773532-84205780-2f2c-11ea-9167-9e932b726175.png)

## Additional Context

 - PHP Version: 7.0.33
 - OS: Windows 10
 - Browser Firefox
 - Plugin Version 1.1.4
 - Device: Lenovo Laptop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@MrWonka Thanks for reporting. I am able to recreate the issue from my side, but I was able to get the portfolio pages working once I deactivate Site Kit and set again. Can you check the same from your side?

**Comment by MrWonka** [comment]
I reset, deactivated, re-activated and then did the setup again. The issue persists.

**Comment by jamesozzie** [comment]
@MrWonka Thanks for the update. I will keep you posted on this issue while we investigate further.

**Comment by jamesozzie** [comment]
@MrWonka Sorry I'm only getting back to you on this now, this issue must have escaped me, we've since moved Site Kit support over the WordPress support forums. Can you check whether the same issues persists, I just checked with the latest version of Site Kit and the Kadence theme (with Kadence Block & Virtue/Ascend/Pinnacle Toolkit).

**Comment by jamesozzie** [comment]
@MrWonka Just following up with you to check whether the issue persists? I'm unable to reproduce the same issue using the latest version of the Kadence theme with the admin toolbar enabled and Site Kit active. 

If you are still encountering the same issue please check whether you have the minification option configured within your Autoptimize plugin, with a possible conflict with the Site Kit admin toolbar. Should the same issue persist feel free to [open a WordPress support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post).
