### ISSUE TITLE
chore(tools): add release-drafter.yml inside .github

### ISSUE THREAD

**Issue by snitin315** [google/site-kit-wp#1009]
**Actual Behaviour**
Currently we don't have the `release-drafter.yml` file which is very useful to keep track of a project. As pull requests are merged, a draft release is kept up-to-date listing the changes, ready to publish when you’re ready.
Right Configuration can  categorises the changes into headings, and automatically suggests the next version number as well.

for more info visit [here](https://github.com/release-drafter/release-drafter)

**I Would like to work on the issue**

**Comment by tofumatt** [comment]
Given we don't currently follow conventional commits in this repo, I'm not sure how useful something like release-drafter would be for this project.

I'd love to have more semantically-organised commits (`fix:`/`feat:`/`chore:`/etc.), and it would make release notes easier, but then I'm not sure how many people read them anyway 😄

Unless @felixarntz thinks we should move to those sorts of commits (and a commit-linter to ensure we're doing it) I don't think this will be an issue we work on/PR we merge.

Thoughts, @felixarntz and @aaemnnosttv?

**Comment by tofumatt** [comment]
I'm going to close this issue as we don't use conventional commits in the project likely won't be useful anyway.

It's a good idea, but I don't think one we'll implement. Thanks for the suggestion though 🙂
