### ISSUE TITLE
chore(tools): Create auto_label.yml

### ISSUE THREAD

**Issue by snitin315** [google/site-kit-wp#1010]
Currently we don't have the `auto_label.yml` file inside `.github` folder . Right now we have to label PR's manually.
Adding this will lead to automatic labelling of Pull Request's based on semantic naming of title.

**Comment by aaemnnosttv** [comment]
Thanks for the suggestion @snitin315. I'm sure this works well for some projects but the suggested automation wouldn't work with our workflow. Thanks again!
