### ISSUE TITLE
User does not have sufficient permission for site, PHP notices

### ISSUE THREAD

**Issue by Camilo517** [google/site-kit-wp#1015]
## Bug Description

When debugging I found these errors

## Steps to reproduce

1. You activate the plugin
2. The property does not have permissions in google search http://prntscr.com/qkm1v2

## Screenshots

http://prntscr.com/qkm18p

## Additional Context

 - PHP Version: 7.4.1
 - OS: Windows 10
 - Browser Chrome

**Comment by jamesozzie** [comment]
@Camilo517 Thanks for reporting. We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue.
