### ISSUE TITLE
Google Cloud Support

### ISSUE THREAD

**Issue by bhubbard** [google/site-kit-wp#1025]
## Feature Description

Not sure if this plugin is the right place to request these features, but I would love to see google offer in this plugin or as a separate plugin tools to easily integrate WP with Google Cloud Services. 

Some Examples:
* Send work to Cloud Tasks
* Tools to send data to Pub/Sub or Cloud Functions.
* MemoryStore Integration for Caching, etc

For example here is a small file I made for Google Cloud Functions:
https://gist.github.com/bhubbard/b74514de39252ac91e64c8f34aaf4e85

Pub/Sub Example:
https://github.com/wp-api-libraries/wp-google-pubsub-api
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@bhubbard Thanks for the suggestion. I've marked it as a product enhancement for the team to review or reclassify. Thanks for the input.

**Comment by ernee** [comment]
adding another request from the support forums: https://wordpress.org/support/topic/google-cdn-2/

**Comment by marrrmarrr** [comment]
This is significantly more technically challenging than what the huge majority of Site Kit users would be able to benefit from.
