### ISSUE TITLE
Update Travis-CI distribution to Xenial

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1026]
Ubuntu Trusty is no longer supported as of April 30, 2019.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Travis-CI should use a maintained Ubuntu distribution.

## Implementation Brief

* Merge #1024.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
QA ✅on this one; not much to check but I verified those are the right settings according to the docs at https://docs.travis-ci.com/user/reference/xenial/#differences-from-the-trusty-images

Travis has been running fine so looks good!
