### ISSUE TITLE
Set Compose Project Name for E2E environment

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1028]
## Feature Description

By default, docker compose uses the directory name of its compose file for the name of the project which is shared by all containers. This has the potential to create conflicts should other projects borrow our configuration as a starting point for their own E2E tests. This also makes it a bit clearer when reviewing your local running containers. Instead of needing to know that `local-env_*` containers are for Site Kit, we should give them a proper name.

By defining the [`COMPOSE_PROJECT_NAME`](https://docs.docker.com/compose/reference/envvars/) environment variable, we can override the default used when running `docker-compose up`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A
## Implementation Brief

* Merge #1022 

## Changelog entry

* N/A

**Comment by cole10up** [comment]
Building, installing and general function of SK confirmed.

Passed QA
