### ISSUE TITLE
Refactor stray module settings into Settings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1030]
## Feature Description

In #859/#995 we introduced dedicated `Settings` classes for each module that has settings. A few settings that were originally implemented as one-off/standalone options should be refactored into its module's Settings for consistency.

- [x] Migrate `Search_Console::PROPERTY_OPTION` to a new `Search_Console\Settings`
- [x] Migrate `googlesitekit_analytics_adsense_linked` to `Analytics\Settings` as `adsenseLinked`  

Similar to the way we migrate legacy keys, we can use `option_` filters on the main `Settings` option to use the legacy option as a fallback if the key is not defined in the saved array value.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `Search_Console\Settings` class that for now only contains one entry for the Search Console property, `propertyID`.
* The existing `Analytics\Settings` should include `adsenseLinked`.
* Both original options `googlesitekit_search_console_property` and `googlesitekit_analytics_adsense_linked` should be migrated respectively if they exist.

## Implementation Brief

* Create `Search_Console\Settings` with a single `propertyID` key
    - In the `get_default()` method, initialize the default value for `propertyID` using the `googlesitekit_search_console_property` option
    - Update `Search_Console` to implement `Module_With_Settings`
* Add `adsenseLinked` to `Analytics\Settings::get_default`
    - Initialize value from the `googlesitekit_analytics_adsense_linked` option
* Update consuming code to use respective `Settings` instances
* Add tests to cover the migration behavior

## Changelog entry

* Migrate stray module settings into object-like option for consistency and future scalability.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**
Ran a series of tests around setup of Analytics, Search Console and Adsense. Running through settings confirming everything functions and no errors occur. 

![Site Kit by Google Settings ‹ Maximum Osprey — WordPress](https://user-images.githubusercontent.com/57115907/72958829-43fb0a80-3d5d-11ea-9e44-163d1837de7f.gif)

Passed QA ✅
