### ISSUE TITLE
Use "dependencies" for build/production node dependencies

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1032]
## Feature Description

Currently we use `devDependencies` for all of our node dependencies, but this isn't the intended way to organise dependencies in `package.json` (see: https://github.com/google/site-kit-wp/pull/1016#discussion_r365249927 for a detailed explanation).

We should move all dependencies we use to build/ship the plugin from `devDependencies` to `dependencies` in `package.json`. This would be things like `@wordpress/*`, `react`, etc. The only files to remain in `devDependencies` would be things like `babel` and `webpack` used to develop/build/work on the project, but not to run it in production builds.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* JavaScript/CSS dependencies that are actual "production" dependencies (that we bundle in our plugin code) should be moved from `devDependencies` to `dependencies` in `package.json`.

## Implementation Brief

* Review packages in `devDependencies` and move any modules imported in src/assets to `dependencies`
* Any dependencies for build, testing, VRT, Storybook, etc should remain under `devDependencies`

## Changelog entry

*

**Comment by felixarntz** [comment]
I'm not a 100% sure on whether to do this one: For us, all of these dependencies are dev dependencies. None of them are needed for the production version of the plugin because we bundle everything.

For the JS part specifically though, I see why it could help to have that separation between dependencies we use in our code vs dependencies we just use to build our code.

**Comment by tofumatt** [comment]
Strictly-speaking that's true, the benefits are mostly around developer experience… though webpack _might_ benefit from know which modules to include, mostly its tree-shaking/dead-code-elimination should handle things.

But yeah, it's mostly a handy thing for us to tell which bits of code we can consider "replaceable" from a build/tooling perspective vs code we need in the actual _runtime_ of the app.

That last bit would be the main benefit to me 😄

**Comment by aaemnnosttv** [comment]
FWIW WordPress core makes the same distinction in its [`package.json`](https://github.com/WordPress/wordpress-develop/blob/master/package.json) as well.

Another important difference that @tofumatt and I discussed recently is to better inform the severity of a detected security vulnerability. An XSS vulnerability in a dev/build dependency is a non-issue, where it is very important if it affects something we bundle for production.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

Looks like all the dependencies were properly moved over, so moving to approval.
