### ISSUE TITLE
Allow changing site URL registered on the authentication service

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1034]
## Feature Description

When changing the site URL (in WordPress code: `home_url()`) at some point, it differs from the URL that is registered on the authentication service. Common scenarios for such changes include going from HTTP to HTTPS, or fixing common problems with WordPress URLs as outlined in our troubleshooting docs. This can result in several problems:

* Issues with the redirect URI no longer matching
* A new site being registered next time instead of using the already existing one (with the different URL)

Site Kit should allow updating the URL registered on the proxy. There is already a route available for doing so on the service.

Furthermore, a common issue has been that sites where the site URL does not start with exactly the home URL can't use the proxy. We will expand the functionality of the proxy therefore to pass full URLs, instead of just `admin_root`. Let's prepare the plugin for this change here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Whenever the home URL or site URL is updated in WordPress and Site Kit already has site ID and site secret stored, Site Kit should issue a request to the authentication service to inform it about the change:
    * `POST https://sitekit.withgoogle.com/o/oauth2/site/`
    * with the following body parameters:
        * `nonce`
        * `site_id`
        * `site_secret`
        * `url`
        * `name`
        * ~~`rest_root`~~
        * `admin_root`
        * `return_uri` --> `admin_url( 'admin.php?page=googlesitekit-splash' )`
        * `action_uri` --> `admin_url( 'index.php' )`
    * these parameters should have values similarly how they're generated in `OAuth_Client::get_proxy_setup_url()`, and the two new parameters should be present in both occasions
* There should also be an update routine to fire a request to the proxy on the next (1.5.0) update, to cover all the sites that have had changes in the meantime.
* The plugin should longer pass `rest_root` anywhere at all (it's no longer used).

## Implementation Brief

* Add a new `Google_Proxy::get_site_fields()` method to return an array of the following fields
    - `url`
    - `name`
    - `admin_root`
    - `return_uri`
    - `action_uri`
* Add a new `Google_Proxy::sync_site_fields( Credentials $creds )` method to
    - Merge site fields with `nonce`, `site_id`, and `site_secret`
    - Call `wp_remote_post( self::OAUTH2_SITE_URI, $args )` with the above parameters in the `$args['body']`
* Add hooks on updates to `home` and `siteurl` options to `Authentication::register`
    - Hook on to `update_option_home`
    - Hook on to `update_option_siteurl`
    - Hook on to `update_option_googlesitekit_db_version`
    - In callback `add_action` on to `shutdown`
        - if sync flag is present, return (request has already been made)
        - if not `oauth_client->using_proxy()` return
        - set flag
        - call `$this->google_proxy->sync_site_fields( $this->credentials )`
* Add a `Migration_n_e_x_t` class to update the `googlesitekit_db_version` option and trigger the site fields to be synced
* Update `OAuth_Client::get_proxy_setup_url` to use `Google_Proxy::get_site_fields()`
* We need to be mindful that the sync request is not sent during tests, so we should add a hook on the base test case to clear the `shutdown` action after each

## Changelog entry

* Fix various plugin setup issues related to inconsistent URLs by automatically updating registered URIs on the authentication service.

**Comment by onurparlar** [comment]
https://github.com/google/site-kit-wp/issues/1114

**Comment by felixarntz** [comment]
@aaemnnosttv Let's pick this up as high priority for next release (in 2 weeks).

**Comment by felixarntz** [comment]
@aaemnnosttv Often times, the home URL and site URL options are updated within the same request, so with your current IB it would issue two requests then. And actually they may result in problems because as soon as the home URL and site URL no longer differ (more explicitly, if the site URL no longer starts with the home URL). Let's change this so that whenever one of them changes, a single request is later issued (maybe on `shutdown`?) to ensure that we only fire one request that handles changes to both.

I also have a few follow-up items:
* We should also add an update routine to fire a request to the proxy on the next (1.5.0) update, to cover all the sites that have had changes in the meantime.
* A common issue has been that sites where the site URL does not start with exactly the home URL can't use the proxy. We will expand the functionality of the proxy therefore to pass full URLs, instead of just `admin_root`. Let's prepare the plugin for this change here:
    * In addition to the other parameters that describe the site (`name`, `url`, `admin_root`, `rest_root`), also pass a `return_url` parameter, which should be `admin_url( 'admin.php?page=googlesitekit-splash' )`, and an `action_url` parameter, which should be `admin_url( 'index.php' )`.
    * No longer pass `rest_root` anywhere at all (it's no longer used).

I've added these to the IB. It may increase the estimate a little bit, which is fine. With the new scope it will result in a much more impactful outcome for addressing people's issues.

**Comment by aaemnnosttv** [comment]
> Often times, the home URL and site URL options are updated within the same request, so with your current IB it would issue two requests then. And actually they may result in problems because as soon as the home URL and site URL no longer differ (more explicitly, if the site URL no longer starts with the home URL). Let's change this so that whenever one of them changes, a single request is later issued (maybe on shutdown?) to ensure that we only fire one request that handles changes to both.

That's a good call, although hooking the request later itself would still result in two calls so I don't think that's necessary. Instead we can have the callback unhook itself from both, so that it only runs once per request, regardless of which hook triggers it.

The other changes sounds good. I'll update the IB.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> That's a good call, although hooking the request later itself would still result in two calls so I don't think that's necessary. Instead we can have the callback unhook itself from both, so that it only runs once per request, regardless of which hook triggers it.

That wouldn't really be enough I believe. We must only issue the request _after_ both URLs have been updated, and the only way to "kind of make sure" that's the case is by hooking into a very late action (like `shutdown`) as soon as one of the two gets updated. If the other than gets updated in the same request (which again is likely), then we'll have both the latest versions by the time `shutdown` is run.

**Comment by aaemnnosttv** [comment]
Yeah, that makes sense as we need to wait for both to be updated before making the call. IB updated 👍

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅(Code/approach looks good and setup still works fine.)
