### ISSUE TITLE
Ensure correct GTM container is used for printing snippet

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1036]
## Bug Description

When printing the GTM snippet on AMP vs non-AMP, we currently check for the "AMP mode" currently relevant for the overall site. This is not correct, we should simply use `amp` as usage context when printing the AMP snippet, or `web` when printing the non-AMP snippet.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When printing a GTM snippet in AMP or non-AMP context, we should rely solely on that to use usage context `amp` vs `web`.

## Implementation Brief

* The following methods should use `Tag_Manager::USAGE_CONTEXT_WEB` instead of `Tag_Manager::get_usage_context()`:
    * `Tag_Manager::print_gtm_js()`
    * `Tag_Manager::print_gtm_no_js()`
* The following methods should use `Tag_Manager::USAGE_CONTEXT_AMP` instead of `Tag_Manager::get_usage_context()`:
    * `Tag_Manager::print_amp_gtm()`
    * `Tag_Manager::amp_data_load_analytics_component()`

## Changelog entry

* Ensure that the Tag Manager snippet rendered is always compatible with the current context (AMP vs non-AMP).

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**
Setup AMP on a JN instance with Analytics.
![image](https://user-images.githubusercontent.com/57115907/73240930-59a17300-4155-11ea-9dcc-d5626be4d03b.png)

![image](https://user-images.githubusercontent.com/57115907/73240937-5efebd80-4155-11ea-9f02-f3220bc31bab.png)

Setup tag manager:
![image](https://user-images.githubusercontent.com/57115907/73240982-835a9a00-4155-11ea-933c-fa60058e627b.png)

Confirmed snippet was inserted:
![image](https://user-images.githubusercontent.com/57115907/73241004-8eadc580-4155-11ea-8683-c1ca774f9521.png)

Deactivated AMP
![image](https://user-images.githubusercontent.com/57115907/73241115-f06e2f80-4155-11ea-8495-41895c446278.png)

Reinstalled Analytics and Tag Manager without AMP - no issues.

Passed QA ✅
