### ISSUE TITLE
GA Error during setup: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#1039]
## Bug Description

While testing https://github.com/google/site-kit-wp/issues/198
During GA Setup with fresh account that doesn't have a tag added to the site, user is able to select a grayed out option here:

![image](https://user-images.githubusercontent.com/57115907/72407118-58af2100-3713-11ea-981d-46ced7b8e506.png)

Causing the error: Cannot read property 'length' of null

## Steps to reproduce

1. Create a fresh Jurassic Ninja session
2. Install 1.2.0 version of SK
3. Activate and start GA setup
4. During setup flow don't select anything for the first drop down (Account) but expand the either property or view drop downs an select 'Select an account'

Notice:

![image](https://user-images.githubusercontent.com/57115907/72407230-ae83c900-3713-11ea-852f-405e3e96a561.png)

## Acceptance criteria

* Users should not be able to select a property until a concrete account (i.e. not "Select an account" or "Setup a new account") is selected in the accounts dropdown.
* Users should not be able to select a profile until a concrete property (i.e. not "Select a property" or "Setup a new property") is selected in the properties dropdown.

## Implementation Brief

* Disable the property select box (https://github.com/google/site-kit-wp/blob/bfd0a3e22f99deb230cfb62ff8c9f14c7a04fd3e/assets/js/modules/analytics/setup.js#L945) if no account is selected.
* Disable the profile select box (https://github.com/google/site-kit-wp/blob/bfd0a3e22f99deb230cfb62ff8c9f14c7a04fd3e/assets/js/modules/analytics/setup.js#L965) if no property is selected.
* It's worth fixing https://github.com/google/site-kit-wp/blob/bfd0a3e22f99deb230cfb62ff8c9f14c7a04fd3e/assets/js/modules/analytics/setup.js#L1059 as well while here: we should be checking for `message` truthiness before we check for `.length`, so we should change that check to `if ( ! message || 0 === message.length ) {`.

## Changelog entry

* Fix bug and potential JavaScript error where user was able to select Analytics property before selecting an account.

**Comment by tofumatt** [comment]
Confirmed this happens for any account without a property selected. Seems we should be disabling input on that select until the first has a value.

![2020-01-15 11 32 19](https://user-images.githubusercontent.com/90871/72430632-cba7ae80-378a-11ea-9543-33cbbfa26e2d.gif)

I can get this to happen for a user that has accounts, but just hasn't selected ones, so this is straightforward to test:

![2020-01-15 11 34 53](https://user-images.githubusercontent.com/90871/72430754-132e3a80-378b-11ea-9168-fdb9856917f2.gif)

This is likely a release-blocking bug. The AC just needs to be "user cannot select second input unless account is selected" I think.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
QA ✅
