### ISSUE TITLE
Update Asset handle names for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1040]
## Bug Description

Currently our Asset handle names use an inconsistent naming convention. Let's update them to all be the same for consistency.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All Site Kit-owned Asset handles should start with `googlesitekit-`
* Asset handles should be kabob-cased

## Implementation Brief

* Update all handle names in `Assets::get_assets`
* Update references to handles (enqueuing, etc)

## Changelog entry

* Make JS and CSS asset names consistent.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## ✅ QA

* ✅ All Site Kit-owned Asset handles should start with `googlesitekit-`
* ✅ Asset handles should be kabob-cased

Moving to approval.
