### ISSUE TITLE
Generate a version-specific filename when building a release zip

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1041]
## Feature Description

Currently the command for building a zip file for release `npm run release-zip` generates a `google-site-kit.zip` file every time. This is not very ideal for testing when we may have multiple versions of the file around for testing/QA.

It would be great if the command generated a filename which had relevant version information in the filename. E.g. `google-site-kit.v{plugin.version}.{git.branch}@{git.shortSha}.zip`

Placeholder legend
```
plugin.version = (parse from plugin header)
git.branch     = git rev-parse --abbrev-ref HEAD
git.shortSha   = git rev-parse --short HEAD
```

> The branch name would need rewriting to make it safe as a filename to convert things like `/`.

An example generated filename might then be `google-site-kit.v1.2.0.develop@2f74fd30.zip`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The resulting zip file generated by `npm run release-zip` should contain the following information in the filename
    - Plugin version (from WordPress file header)
    - Current git SHA (abbreviated version)
    - Current branch name (if not in a detached HEAD state)
    - Date & time of current commit
* Filename must be cross-platform safe (i.e. no `\` or `/`)
* Ideally should not depend on executing `git` commands

## Implementation Brief

* Add [`git-repo-info`](https://www.npmjs.com/package/git-repo-info) to npm `devDependencies`
* Update `gulp-tasks/zip.js` to generate the zip file name dynamically
    - Use [`getRepoInfo()`](https://www.npmjs.com/package/git-repo-info#usage) to retreive all necessary git-based information without `git`
* Add [`sanitize-filename`](https://www.npmjs.com/package/sanitize-filename) to ensure cross-platform naming compatibility of the resulting filename
* Finish #1098

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Ran a test off of the enhance/1041-release-zip-followup branch to confirm this change. Looks good on my end. Zip was created properly.

![image](https://user-images.githubusercontent.com/57115907/74253482-fca0d380-4ca3-11ea-812a-17ef2de108c8.png)

**Comment by cole10up** [comment]
This is looking good. Passed QA.
