### ISSUE TITLE
SiteKit dashboard not working for other admin user

### ISSUE THREAD

**Issue by fhfournier** [google/site-kit-wp#1051]
## Bug Description

Hi,

GoogleSiteKit dashboard not working for all user. Its work for main user who configure the link with Google only.

## Steps to reproduce

Login in master admin : all work

Login with another admin : not work

## Screenshots

User admin : 
![image](https://user-images.githubusercontent.com/3278753/72535685-f5bea680-3846-11ea-9c8d-aeba3deeea24.png)

Another admin : 
![image](https://user-images.githubusercontent.com/3278753/72535737-0838e000-3847-11ea-9ef1-40c1ae2eb2f4.png)

## Additional Context

 - PHP Version:  7.4
 - OS: [e.g. iOS] : Linux Ubuntu
 - Browser : Chrome
 - Plugin Version : 1.1.4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@fhfournier Site Kit support is provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your question on there, where we would be happy to assist. 

The setup process for additional users differs [slightly](https://github.com/google/site-kit-wp/issues/881) for other users, they should not have to setup the plugin in full. If you are encountering issues with setup for other admin users can include the the error message or additional info of the problem with the support topic.
