### ISSUE TITLE
Cannot read property 'performance' of undefined

### ISSUE THREAD

**Issue by hotkeyJunkie** [google/site-kit-wp#1057]
**Cannot read property 'performance' of undefined**

TypeError: Cannot read property 'performance' of undefined
    react-dom.min.js?ver=16.9.0:103 
    at allmodules.js?ver=1.2.0:7
    at t.value (allmodules.js?ver=1.2.0:7)
    at re (react-dom.min.js?ver=16.9.0:95)
    at Vg (react-dom.min.js?ver=16.9.0:95)
    at ph (react-dom.min.js?ver=16.9.0:217)
    at lh (react-dom.min.js?ver=16.9.0:126)
    at O (react-dom.min.js?ver=16.9.0:121)
    at ze (react-dom.min.js?ver=16.9.0:118)
    at react-dom.min.js?ver=16.9.0:53
    at unstable_runWithPriority (react.min.js?ver=16.9.0:26)

## Steps to reproduce

1. Go to 'Site Kit'
2. Click on 'Dashboard'
3. See error

## Screenshots

![image](https://user-images.githubusercontent.com/13815886/72657268-38c77800-3a07-11ea-86ef-d3d1c280239b.png)

![image](https://user-images.githubusercontent.com/13815886/72657243-e5552a00-3a06-11ea-951e-41f4a516905c.png)

## Additional Context

 - PHP Version: 
 - OS: Windows 10
 - Browser Chrome
 - Plugin Version 1.2.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@hotkeyJunkie Thanks for raising this issue. You can see issue #1054 which looks related to the issue you have been encountering. Can you try try and clear your browser's cache before checking once more (or purge your CDN if applicable) before checking once more. 

If the above fails feel free to open a new [WordPress support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) and we can assist from there.
