### ISSUE TITLE
Reconnect Site Kit — Warning is still showed

### ISSUE THREAD

**Issue by andrewio** [google/site-kit-wp#1058]
## Bug Description
The warning message "We’ve made a lot of improvements to get Site Kit ready for general release! In order to use this new version, you’ll need to go through the updated setup flow to re-generate your credentials. Once you’re done, all your data will still be there." is showed all over the admin panel last several releases of plugin.

## Additional Context

 - PHP Version: 7.3
 - OS: Mac OS X
 - Browser [chrome]
 - Plugin Version [1.2.0]
 - Device: [MacBook Pro 2017]

Several times reconnected and clicked on the "Ignore" button. No result last month. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@andrewio Thanks for reporting. Site Kit support is provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your issue on there, where we would be happy to assist.
