### ISSUE TITLE
Per Post Link Integration

### ISSUE THREAD

**Issue by ashishmohta** [google/site-kit-wp#1059]
## Feature Description

I was using Jetpack Stats, and one thing it does best is adding a link to the Stats page on per post basis.

For example, if I click on the link, it will take me to a detailed page that gives me complete stats on one page.

I see Google Site kit doing the same but partially. As of now, I need to open the post in edit mode, and then hover over the GSK icon on the Wordpress admin bar. It then reveals the last 90days traffic stats in the form of a summary.

Instead, if it can add a link to Analytics which when clicked opens Analytics of the post, it will be super convenient.  For now, I need to manually copy the link, paste it into "Search for individual page or post information" text box, and then figure out details.

Ashish

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@ashishmohta Thanks for the request. It is already possible to access the single URL view for Site Kit via Site Kit's admin bar menu by clicking on the "More details" link. You can access this link when editing the post, so from what I'm understanding this is already available today, so this issue shouldn't be relevant anymore.

If you mean something different, please reopen and clarify so we can re-consider this.
