### ISSUE TITLE
Fix potential issue with unexpected PageSpeed Insights API response

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1061]
## Bug Description

Recently, the JS error `Cannot read property ‘performance’ of undefined` has been reported twice:

* https://wordpress.org/support/topic/strange-error-on-the-dashboard/
* https://wordpress.org/support/topic/dashboard-error-cannot-read-property-performance-of-undefined/

This must come from PageSpeed Insights, since this is the only place where we reference a property `performance`. I am not sure what the problem with the API response there is, since we should be catching bad responses (>=400) already elsewhere. But let's dig into this a bit, and, even if we don't find anything, at least safe-guard the checks so that we don't just assume `data.categories.performance` to be there.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no JavaScript errors being thrown because of an unexpected response from PageSpeed Insights API.

## Implementation Brief

* Use `lodash.get` to retrieve the nested value in pagespeed's `isZeroData` function    
https://github.com/google/site-kit-wp/blob/b9611e7f4584f43cd4f1c1f776faa547bb19a4c5/assets/js/modules/pagespeed-insights/dashboard/dashboard-widget-homepage-speed-column.js#L46-L48
   - Potentially use the same check when it is referenced later but it shouldn't be necessary as the above callback will be called before the component is ever rendered

## Changelog entry

* Prevent unexpected PageSpeed Insights API responses from breaking the dashboard.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

- Setting up and removing Pagespeed insights
- Ran through token expired test with Pagespeed insights
- Flipped date ranges
- Uninstalled and reinstalled SK

Unable to reproduce. This looks to be fixed.

@ernee 
Feel free to followup with the following support tickets to retry after deployment
https://wordpress.org/support/topic/strange-error-on-the-dashboard/
https://wordpress.org/support/topic/dashboard-error-cannot-read-property-performance-of-undefined/

**Comment by maverick85** [comment]
Hi guys, sorry I see this is closed already but I just updated the plugin and now, despite the dashboard not being broken, I'm getting these errors:
![Screenshot 2020-02-14 at 09 44 06](https://user-images.githubusercontent.com/10200278/74520013-ae433d00-4f0e-11ea-872c-87713592fc6c.png)

At the Site Kit Dashboad
