### ISSUE TITLE
Remove Beta_Migration class

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1062]
Before the 1.0.0 launch, we created a `Beta_Migration` and a `Migration_1_0_0` class to ensure old credentials were removed. Let's remove this class for the next release.

* It's been there long enough now, and the few potential outliers that are still on Beta (if any) are okay to ignore. They could simply reset the plugin.
* There have been some reports (e.g. https://wordpress.org/support/topic/warning-message-is-still-showed/) of this message showing again after every release. Indeed, I can see how this migration class is a bit more error-prone than the others because it does not look at a database version like we do in the newer ones. We don't really need to investigate that though, let's just remove the class.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should no longer be a `Beta_Migration` class that used to inform beta users about the stable release and remove some data.
* There should no longer be a `Migration_1_0_0` class that used to inform beta users about the stable release and remove some data.

## Implementation Brief

* Delete `Beta_Migration` and test
* Delete `Migration_1_0_0` and test
* Remove class instantiations in `Plugin`

## Changelog entry

* Remove legacy migrations that were only relevant to pre-1.0.0 users.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
This has been confirmed fixed via my tests forhttps://github.com/google/site-kit-wp/issues/1054  and user feedback here: https://wordpress.org/support/topic/warning-message-is-still-showed/

Passed QA ✅
