### ISSUE TITLE
Implement base module datastore and googlesitekit.modules.createModuleStore()

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1063]
## Feature Description

Based on the JavaScript refactoring plans, every module should eventually register its own datastore on the `googlesitekit.data` registry.

Which selectors and actions each store exposes may obviously differ between each of them, however all module stores should inherit a "base store" that provides the foundation for module-specific data that is universal. In fact, a base store itself should be a sufficient MVP for being used as a module datastore without any additions.

This issue is for the following work:
* Scaffold a `googlesitekit-modules.js` that exposes an object `window.googlesitekit.modules`.
* For now, this object should only have a single method `createModuleStore( slug )`.
* The method should return a base store object specific to the module slug given, so that a consumer of the method can either register it as-is or augment it with additional selectors and actions.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `googlesitekit-modules.js` file that is registered in WordPress as `googlesitekit-modules` and exposes a `window.googlesitekit.modules` object in JavaScript.
    * The script should have `googlesitekit-api` as dependency - potentially it will need `googlesitekit-data`, but it probably shouldn't, since it would never register a datastore itself.
* The script should expose a single method for now: `window.googlesitekit.modules.createModuleStore( slug )`
    * The method should, based on the given module slug, create a module datastore object scoped to that module slug and return it.
    * The datastore object returned should have a single selector:
        * `getNotifications()`: This should result in an API request to the `GET modules/(?P<slug>[a-z\-]+)/notifications` API endpoint, which should return an array of 0 or more notification objects.
    * The datastore object returned should have no ("public") actions.

## Implementation Brief

* Create a new file `assets/js/googlesitekit/modules/index.js` that exports a function `createModuleStore( slug )`.
    * Based on the given `slug`, create and return a new datastore object with a single selector `getNotifications()` and a corresponding resolver `*getNotifications()` which uses `@wordpress/api-fetch` to make a request `GET modules/(?P<slug>[a-z\-]+)/notifications`.
    * The API call should result in the response being set as available notifications via an "internal" `receiveNotifications()` action.
* Introduce `assets/js/googlesitekit-modules.js` and import `assets/js/googlesitekit/modules` inside it, then expose it globally as `googlesitekit.modules`. If the `googlesitekit` global isn't available, create an empty object and place data inside it as a property.
* Add Webpack external for `assets/js/googlesitekit/modules` that resolves to `googlesitekit.modules`.
* In PHP class `Assets`, rename the current `googlesitekit_modules` to `googlesitekit-allmodules`, and add an entry so that `googlesitekit-modules` is registered in WordPress. (May already be covered by #1040.)

## Changelog entry

* Introduce `googlesitekit-modules` asset with `createModuleStore` function to create a base datastore for a Site Kit module.

**Comment by tofumatt** [comment]
Oh, I like this idea!

A thought about terminology here: I think "notifications" is the wrong word and actually tripped me up a bit reading this. As I understand it, "notifications" are more like "alerts" or "notices"—persistent messages that a user needs to take action on something in the module's scope. Something like "You need to finish set up of your AdSense account." or something. It's not a notification that is transitory and expires after viewing once (eg: "We set up your AdSense account."

This might be a good opportunity to rename these things from "notifications" to "alerts" or "notices", at least starting in the client-side code. I expect notifications to expiry after consumption—or for there to be a way to mark them as "cleared". For these notifications it seems like we provide neither, and if we do want to later implement "real notifications" it'll make naming things hard.

So I'd suggest we rename `getNotifications()`/`*getNotifications()` to something like `getNotices()` or even `getAlerts()`… the first is a bit more agnostic as to severity so more flexible.

Other than that though I like this approach, so let me know what you think about naming and after that we can approve this IB 😄

**Comment by felixarntz** [comment]
@tofumatt It is actually a mix of both. There are some alerts and some notifications as part of that. "Publisher wins" for example are notifications, they can easily be dismissed and sometimes also "dismiss themselves" (only show once). Let's keep these called "notifications" for now.

**Comment by tofumatt** [comment]
Naming looks good, so I think this is good to review now 😄

**Comment by felixarntz** [comment]
@tofumatt I was actually asking you to review this one, since I wrote the original IB :)

**Comment by tofumatt** [comment]
Ahah, whoops! Clearly the week away under the weather did me no good. I was thinking I didn't really remember writing the IB. That said I reviewed it and had nothing to add and think it looks good, so IB ✅and the estimate on it looks right too! (Thanks for reminding me who wrote it! 😅)

**Comment by felixarntz** [comment]
Moving this out of the 1.5.0 release, no reason for it to unblock the process (even though it's close to done).

**Comment by tofumatt** [comment]
This is now good to merge; just assigning @felixarntz for the PR merge 🙂

**Comment by cole10up** [comment]
Ran a series of tests installing latest develop. Connecting all services, checking dashboards, uninstalling services, resetting SK and deleting SK. 

Passed QA ✅

**Comment by tofumatt** [comment]
Eng QA ✅

All tests and code around these modules work as-expected, so moving to approval.
