### ISSUE TITLE
Squirrly SEO plugin prevents data charts from loading on dashboard and other module pages 

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1068]
## Bug Description

Prompted by a [report in the forums](https://wordpress.org/support/topic/no-charts-loaded/), [Squirrly SEO plugin](https://wordpress.org/plugins/squirrly-seo/) prevents data charts from loading on the dashboard and respective module pages (loading bar persists as if attempting retrieval). There are several warning messages in the browser console. 

## Steps to reproduce

1. Install and activate [Squirrly SEO plugin](https://wordpress.org/plugins/squirrly-seo/)
2. Go to the dashboard or module pages
3. See data not displaying and attempting to load

## Screenshots

<img width="1280" alt="Squirrly SEO plugin prevents charts from loading  " src="https://user-images.githubusercontent.com/8108643/72939011-e34ddc80-3d20-11ea-8f73-0c8c688e1955.png">

## Additional Context

 - PHP Version:  7.1.33
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.2.0
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by Tobias-Conrad** [comment]
any update?

**Comment by squirrly** [comment]
Hi,

Replace line wp-content/plugins/squirrly-seo/classes/ActionController.php: 45

echo '<script type="text/javascript" src="https://www.google.com/jsapi"></script>
with 
echo '

This way you don't load the Google API from Squirrly. 
We will add an update to load Google API only in our plugin pages.

**Comment by felixarntz** [comment]
@squirrly Thanks for addressing the issue. Do you have a tentative timeline for the fix, or potentially a GitHub issue where we can follow along?

**Comment by ThierryA** [comment]
@squirrly friendly ping

**Comment by Tobias-Conrad** [comment]
@squirrly fix is working well when include in wp.org version?
Do you load other scripts not needed all the time?
SEO is about speed give it a try please, to make squirrly fast and lightweight.

**Comment by squirrly** [comment]
@Tobias-Conrad We released a new Squirrly SEO version with the fix for Google API. Best, Calin

**Comment by ernee** [comment]
[@Tobias-Conrad confirmed](https://wordpress.org/support/topic/no-charts-loaded/) charts now loading. Thanks @squirrly ! Closing.
