### ISSUE TITLE
Do not delete plugin data when deleting/uninstalling the plugin

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1069]
## Feature Description

Currently all plugin data is wiped when someone deletes the plugin. While this is not a massive problem at this point, it can be unexpected, and in the future will potentially become detrimental, if Site Kit ever starts storing data for which it is the only source.

It is already possible to reset via the UI, which results in a similar effect. So if someone wants to completely delete everything, they could just reset and then deactivate and delete the plugin.

Let's move the `uninstall.php` logic into the `Reset` class so that deleting the plugin no longer results in plugin data getting wiped.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No plugin data should be wiped when the plugin is deleted.

## Implementation Brief

* Move data deletion from `uninstall.php` to `Reset::all()`
* Delete `uninstall.php`

## Changelog entry

* No longer delete plugin data when uninstalling and instead rely on the more explicit reset functionality.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Setup my local without SK, installed, activated and confirmed functionality. Deactivated and deleted. Checked the directory, confirmed there wasn't a reset before deleting.

![image](https://user-images.githubusercontent.com/57115907/74406163-bf435f80-4de3-11ea-98a3-25d593aa0b47.png)

Passed QA ✅
