### ISSUE TITLE
Cache: Global cache keys are never removed

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#108]
## Bug Description

The `\Google\Site_Kit\Core\Storage\Cache` class stores a list of transient names related to keys that it has cached in an option of "global cache keys".

It also has a `remove_global_cache_key` method which is intended to remove an individual key from this list. This is a private method used only once within the class.

The problem is that this method assumes keys are stored as an associative array (or map/dictionary) when the keys are stored as a simple numeric array (list). It fails to remove the key from the stored list when it attempts to unset it using the given cache key as the index to remove.

## Screenshots

Method inspection at runtime as shown by xDebug
![image](https://user-images.githubusercontent.com/1621608/60581795-3a459180-9d90-11e9-8167-855fcf3959be.png)

`global_cache_keys` instance property value
![image](https://user-images.githubusercontent.com/1621608/60581803-3ca7eb80-9d90-11e9-8fad-4bbe3c8d6d50.png)

## Additional information

Also, the method is invoked as a static method `::` when it should be called as an instance method `->`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A

## Implementation Brief

* Global cache keys are stored in an indexed array, but the current code tries to remove them by using the actual cache key as array index which will never be a match.
* Look up the index of the key and the unset that instead.
* Provide tests to ensure the fix works as expected.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Added missing moderator section details.
