### ISSUE TITLE
Bad Request error

### ISSUE THREAD

**Issue by drawcard** [google/site-kit-wp#1081]
## Bug Description

I am getting a "Bad Request" error as follows
![image](https://user-images.githubusercontent.com/1435638/73221079-ea0ca180-41af-11ea-9bc2-b37a0bcf348d.png)

## Steps to reproduce

Select "Manage sites" from the top right corner of Site Kit
![image](https://user-images.githubusercontent.com/1435638/73221244-48398480-41b0-11ea-99a3-967cbf26f39e.png)
Then the error occurs.

## Additional Context

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | MySQL Community Server - GPL v8.0.17 |  
PHP Version: | 7.3.7 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 40M |  
GD Installed: | Yes |  
ZIP Installed: | Yes

![image](https://user-images.githubusercontent.com/1435638/73226213-2a275080-41bf-11ea-9f25-1ccea0d61b77.png)

![image](https://user-images.githubusercontent.com/1435638/73226239-3f9c7a80-41bf-11ea-94cc-4ef382391360.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by drawcard** [comment]
I disconnected and reconnected my Google account and it seems to be working again

**Comment by jamesozzie** [comment]
@drawcard Good to know, thanks for the update. You can follow the guides on the plugins [website](https://sitekit.withgoogle.com/documentation/fix-common-issues/) going forward for steps to take on setup issues, and submit any support topics using the plugins [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/#new-post).
