### ISSUE TITLE
Add @testing-library/react-testing-library support and use for tracking events

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1083]
## Feature Description

Right now we don't have any way to test DOM output/manipulation with Jest, only with E2E tests. Because the E2E tests are quite slow and a lot of overhead to set up, we should start doing more unit/functional tests with `@testing-library/react-testing-library`. A good example of that is the code in #1079 benefitting from DOM test code but being a bit too much for a full E2E test.

Because we don't have global state management or anything bootstrapping these tests should be straightforward, and we can also start testing components using the tests rather than E2E tests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tests can be used to verify component behaviour in Jest.
* Tests can be used to test DOM manipulation without using the E2E/Puppeteer testing framework.

## Implementation Brief

* Add `@testing-library/react` to the project's `devDependencies`
* Create a provider component used for all tests (example: https://github.com/octopusthink/nautilus/blob/master/utils/testing.js#L11-L14). This provider would be for future use—and might even be a simple `Fragment` wrapper for now, but is best to set up right away.
* The provider component can start inside our own `test-utils` file that we should include a webpack alias for, so we can `import { render } from 'test-utils';` in our tests and have it point to our own custom render method using our own provider and other wrappers.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@tofumatt this is great, just a few questions:
- Possible typo in the package name? It's `@testing-library/react`, no?
- As for the provider component, is this more for future use? We don't really use Context right now so just wondering how this would be useful.
- I assume we would want to add a `test-utils` file similar to that [described in the setup docs](https://testing-library.com/docs/react-testing-library/setup#custom-render) as well?

Also, please add an estimate!

**Comment by tofumatt** [comment]
You're right, whoops! I seemingly copied the GitHub repo name over the npm package 😣

Thinking this is XS just because of the provider setup, but that might take even less time than that. It's definitely on the lower-end of XS 👍

**Comment by tofumatt** [comment]
Oh, and to clarify: "provider" is more of a general wrapper provider, not specific to React Context. It will be where we add context, but also a `@wordpress/data` `Provider` for state during tests, etc. I use "Provider" as a generic term here 😄

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@tofumatt this should be ready for review, with the exception of the added webpack alias for `test-utils`. That part didn't want to work for some reason, so that part is not included.

**Comment by tofumatt** [comment]
(Issue approved, just needs @felixarntz to merge 🙂)

**Comment by tofumatt** [comment]
QA ✅

Tests all run and imports work 👍
