### ISSUE TITLE
Site Kit Installed and working GTM created but not linking to Site Kit

### ISSUE THREAD

**Issue by lloftus26** [google/site-kit-wp#1085]
Hi Site Kit,

I am not a coder, I am following the instructions on Site Kit Set-up for my site. The plugin installed and everything activated beautifully until I got to Google Tags Manager, I have my account created in GTM and for some reason it is not connecting to the site, even after re-fetching.
<img width="1086" alt="Screen Shot 2020-01-30 at 9 06 17 AM" src="https://user-images.githubusercontent.com/60478691/73469527-b82c4400-4343-11ea-9a41-35e9989676b0.png">
I turned off the only caching option I could find and I tried installing in incognito as well. I did not try switching my theme, as I did not want to lose all of the customization I have built. Please let me know thoughts on what to try next.

Thank you in advance,

Leigh

**Comment by jamesozzie** [comment]
@lloftus26 Thanks for reporting. We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist.
