### ISSUE TITLE
Reports started showing  blank

### ISSUE THREAD

**Issue by computerghar** [google/site-kit-wp#1109]
For website www.topyellowpage.com , site kit Dashboard started showing Blank reports.
* Reinstalled Plugin
* Tried to reinstall plugin.
* Message Reinstall / Reset
* After checking login email, it goes in same loop
* Settings not showing now.
![Capture Site kit no report](https://user-images.githubusercontent.com/4169907/74129693-3ae7b580-4c06-11ea-82e6-ba25da676834.JPG)

**Comment by jamesozzie** [comment]
@computerghar Thanks for reporting. I've responded to your query from your [WordPress support forum topic](https://wordpress.org/support/topic/site-kit-stopped-showing-reports/). Feel free to add any input there and we can assist.
