### ISSUE TITLE
Adsense Dashboard not Showing

### ISSUE THREAD

**Issue by zai17** [google/site-kit-wp#1112]
## Bug Description

Dear, Google Site Kit Plugin Team

I've been on this issue for a long time. The issue is when I try to connect my google site kit account with Google Adsense, the google adsense dashboard will not show up. And recently, it written "e.replace is not a function" as you can see on the image below.

I'm not a techie guy, but I think it's a bug. 

Please, fix this bug as soon as you have time. 

Thank you.

Regards,

Zai
![Bug site kit google while activating adsense fitur](https://user-images.githubusercontent.com/57032232/74166929-65675c00-4c62-11ea-86e4-7a79508fe2d4.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@zai17 Thanks for reporting. We have an open issue which you can keep track at #1112
