### ISSUE TITLE
GA send Event not working

### ISSUE THREAD

**Issue by gounder** [google/site-kit-wp#1120]
## Bug Description
We have connected Google Analytics and have added [event tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) on various places on our site but the same isn't showing in Google Analytics. On investigating we realized Analytics is added using the Google Tag Manager code which does event tracking differently i.e. they have to be created in Google Tag Manager itself, but as we have connected Analytics and not tag manager, we don't have a container to add the events in GTM.

## Steps to reproduce

Contact form 7 has the tutorial to track form submissions - https://contactform7.com/tracking-form-submissions-with-google-analytics/

## Additional Context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@gounder Thanks for reporting, and great to see you making use of the plugin! There's an open [feature request (#26)](https://github.com/google/site-kit-wp/issues/26) that deals with additional options using the Analytics module. 

I'll chase up for any updates on this matter and report back on that issue. In the meantime you can keep watch of that related issue or add your input there.

**Comment by gounder** [comment]
Hi @jamesozzie 

What I meant is there is no way for someone to have custom events being sent to GA if they don't use Tag Manager.

Sitekit offers both GA connection and GTM connection, but is only implementing using GTM, which leaves someone whose connected using GA without any option for event tracking, many have used event tracking on Contact form 7. 

Maybe there's a better way to handle this, if someone connects GA then a GA universal code should be and if GTM then the GTM code... 

I did see the feature request, but that's asking for events to be automatically added like it's done in the Monster Insights plugin for Downloads and Outbound Link clicks.

**Comment by jamesozzie** [comment]
@gounder fgfgf

**Comment by jamesozzie** [comment]
@gounder Correct that at present using Tag Manager is required for such event tracking. I've added this as a product enhancement for the team to discuss. Thanks for the suggestion.

**Comment by gabrielstuff** [comment]
hello, just bumping on that. Was trying to simply add some `ga` tracking based on the following doc : https://developers.google.com/analytics/devguides/collection/gajs/methods/gaJSApiBasicConfiguration

After futher reading, I understood that the GTM methods is used and so one should only follow methods described there : https://support.google.com/tagmanager/answer/6106716?hl=en&ref_topic=6333310 to build custom event?

**Comment by tommiekn** [comment]
Hi, @jamesozzie there was any update regarding this feature and a possible implementation ? agreeing with @gounder thats a bit of limitation for whom doesnt use tag manager

**Comment by marrrmarrr** [comment]
Hi @gounder and everyone else who chimed in here so far, it seems that the main limitation here is around the type of snippet -- Site Kit uses gtag.js, whereas you seem to be referring to the older analytics.js (or at least that's what's referenced in the [Contact Form 7 help article](https://contactform7.com/tracking-form-submissions-with-google-analytics/) you linked). 

Are you usuing analytics.js, and if yes is it feasible for you to [upgrade the GA implementation](https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs#measure_events) to gtag.js?

**Comment by marrrmarrr** [comment]
Hi @gounder and everyone, 
I'll be closing this for now, if you do happen to read the comments have a look at the GA docs, and let us know if you have more questions.

**Comment by tommiekn** [comment]
hi @marrrmarrr ,

I have a wordpress plugin that worked well with ga() events, it worked well as well with other analytics plugins that uses gtags after i have updated to gtag() events.
However, with sitekit i can't happen to make it work.

I'm using GA debug to figure out the calls, as well Tag Assistant, events gets fired but never arrive on gtag/analytics.

Could you please advise if i need to change the implementation somehow ? Set a default measurement id with a "send_to" command in the event?

The linked tag manager in Sitekit is an empty property, aka theres no settings.

This is the log from GA debug. Tag assistant is just empty.

Over the end theres an example of event fired.

Goal here is to have a gtag function that works with Gsite with default settings.


`js?id=UA-27656468-6:128        _                 _
  __ _| |_ __ _  __ _   (_)___
 / _` | __/ _` |/ _` |  | / __|
| (_| | || (_| | (_| |_ | \__ \
 \__, |\__\__,_|\__, (_)/ |___/
 |___/          |___/ |__/


js?id=G-W4Y829SYNH:415        _                 _
  __ _| |_ __ _  __ _   (_)___
 / _` | __/ _` |/ _` |  | / __|
| (_| | || (_| | (_| |_ | \__ \
 \__, |\__\__,_|\__, (_)/ |___/
 |___/          |___/ |__/


js?id=UA-27656468-6:128 Processing commands (7)
js?id=UA-27656468-6:128 Processing GTAG command: ["set", "linker", {domains: ["mydomain.com"]}]
js?id=UA-27656468-6:128 Processing data layer push: {event: "gtm.init_consent"}
js?id=UA-27656468-6:128 Processing data layer push: {event: "gtm.init"}
js?id=UA-27656468-6:128 Processing GTAG command: ["js", Thu Jul 08 2021 12:41:13 GMT+0200 (Central European Summer Time)]
js?id=UA-27656468-6:128 Tag fired: {function: "__rep", vtp_containerId: "UA-27656468-6", vtp_remoteConfig: ["map"], tag_id: 1}
js?id=UA-27656468-6:128 Tag fired: {function: "__zone", vtp_childContainers: ["list", ["map", "publicId", "G-W4Y829SYNH"]], tag_id: 3}
js?id=UA-27656468-6:128 Trying to install container G-W4Y829SYNH from both a snippet and from a zone tag.
js?id=UA-27656468-6:128 Processing GTAG command: ["set", "developer_id.dZTNiMT", true]
js?id=UA-27656468-6:128 Processing GTAG command: ["config", "UA-27656468-6", {anonymize_ip: true}]
js?id=UA-27656468-6:128 GTAG Command: "config", target: "UA-27656468-6", configuration: {anonymize_ip: true}
js?id=UA-27656468-6:128 Processing data layer push: {gtm.start: 1625740873856, event: "gtm.js"}
js?id=UA-27656468-6:128 Processing GTAG command: ["js", Thu Jul 08 2021 12:41:14 GMT+0200 (Central European Summer Time)]
js?id=UA-27656468-6:128 Processing GTAG command: ["config", "G-W4Y829SYNH"]
js?id=UA-27656468-6:128 GTAG Command: "config", target: "G-W4Y829SYNH", configuration: {}
js?id=UA-27656468-6:128 Processing commands (1)
js?id=UA-27656468-6:128 Processing data layer push: {event: "gtm.dom"}
js?id=G-W4Y829SYNH:415 Processing commands (8)
js?id=G-W4Y829SYNH:415 Processing GTAG command: ["set", "linker", {domains: ["mydomain.com"]}]
js?id=G-W4Y829SYNH:415 Processing data layer push: {event: "gtm.init_consent"}
js?id=G-W4Y829SYNH:415 Processing data layer push: {event: "gtm.init"}
js?id=G-W4Y829SYNH:415 Processing GTAG command: ["js", Thu Jul 08 2021 12:41:13 GMT+0200 (Central European Summer Time)]
js?id=G-W4Y829SYNH:415 Tag fired: {function: "__gct", vtp_trackingId: "G-W4Y829SYNH", vtp_sessionDuration: 0, vtp_googleSignals: ["macro", 1], vtp_foreignTld: ["macro", 2], vtp_restrictDomain: ["macro", 3], vtp_eventSettings: ["map", "purchase", ["map", "blacklisted", false, "conversion", true]], vtp_dynamicEventSettings: ["map", "edit_rules", ["list"], "synthesis_rules", ["list"]], tag_id: 7}
js?id=G-W4Y829SYNH:415 Loaded existing client id: 2066192423.1625739807
js?id=G-W4Y829SYNH:415 Event would be batched, but batching is disabled in debug mode.
js?id=G-W4Y829SYNH:415 Sending event "page_view" to undefined
js?id=G-W4Y829SYNH:415 Request parameters:
js?id=G-W4Y829SYNH:415 v: 2
js?id=G-W4Y829SYNH:415 tid: G-W4Y829SYNH
js?id=G-W4Y829SYNH:415 gtm: 2oe770
js?id=G-W4Y829SYNH:415 _p: 261767914
js?id=G-W4Y829SYNH:415 sr: 1920x1080
js?id=G-W4Y829SYNH:415 _dbg: 1
js?id=G-W4Y829SYNH:415 ul: en-us
js?id=G-W4Y829SYNH:415 cid: 2066192423.1625739807
js?id=G-W4Y829SYNH:415 Event parameters:
js?id=G-W4Y829SYNH:415 en: page_view
js?id=G-W4Y829SYNH:415 Shared parameters:
js?id=G-W4Y829SYNH:415 dl: https://mydomain.com/release/ipsiom-xyz/
js?id=G-W4Y829SYNH:415 dr: https://mydomain.com/?gtm_debug=x
js?id=G-W4Y829SYNH:415 dt: Title
js?id=G-W4Y829SYNH:415 sid: 1625739805
js?id=G-W4Y829SYNH:415 sct: 1
js?id=G-W4Y829SYNH:415 seg: 1
js?id=G-W4Y829SYNH:415 Sending request: https://www.google-analytics.com/g/collect?v=2&tid=G-W4Y829SYNH&gtm=2oe770&_p=261767914&sr=1920x1080&_dbg=1&ul=en-us&cid=2066192423.1625739807&_s=1&dl=https%3A%2F%2Fmydomain.com%2Frelease%2Fipsiom-xyz%2F&dr=https%3A%2F%2Fmydomain.com%2F%3Fgtm_debug%3Dx&dt=Ipsiom%20-%20XYZ%20-%20Kinphonic&sid=1625739805&sct=1&seg=1&en=page_view
js?id=G-W4Y829SYNH:415 Tag fired: {function: "__lcl", vtp_waitForTags: false, vtp_checkValidation: true, vtp_uniqueTriggerId: "1_15", tag_id: 40}
js?id=G-W4Y829SYNH:415 Tag fired: {function: "__lcl", vtp_waitForTags: false, vtp_checkValidation: true, vtp_uniqueTriggerId: "1_22", tag_id: 41}
js?id=G-W4Y829SYNH:415 Tag fired: {function: "__ehl", vtp_groupEvents: true, vtp_groupEventsInterval: 1000, vtp_uniqueTriggerId: "1_36", tag_id: 44}
js?id=G-W4Y829SYNH:415 Processing GTAG command: ["set", "developer_id.dZTNiMT", true]
js?id=G-W4Y829SYNH:415 Processing GTAG command: ["config", "UA-27656468-6", {anonymize_ip: true, _uei: 6}]
js?id=G-W4Y829SYNH:415 GTAG Command: "config", target: "UA-27656468-6", configuration: {anonymize_ip: true, _uei: 6}
js?id=G-W4Y829SYNH:415 Processing data layer push: {gtm.start: 1625740873856, event: "gtm.js", gtm.uniqueEventId: 7}
js?id=G-W4Y829SYNH:415 Processing GTAG command: ["js", Thu Jul 08 2021 12:41:14 GMT+0200 (Central European Summer Time)]
js?id=G-W4Y829SYNH:415 Processing GTAG command: ["config", "G-W4Y829SYNH"]
js?id=G-W4Y829SYNH:415 GTAG Command: "config", target: "G-W4Y829SYNH", configuration: {}
js?id=G-W4Y829SYNH:415 Processing data layer push: {event: "gtm.dom", gtm.uniqueEventId: 10}
js?id=G-W4Y829SYNH:415 Tag fired: {function: "__ytl", vtp_captureStart: true, vtp_captureComplete: true, vtp_captureProgress: true, vtp_progressThresholdsPercent: "10,25,50,75", vtp_triggerStartOption: "DOM_READY", vtp_uniqueTriggerId: "1_25", vtp_enableTriggerStartOption: true, tag_id: 42}
js?id=G-W4Y829SYNH:415 Processing commands (0)
analytics.js:26 
                         _                          _       _   _
                        | |                        | |     | | (_)
  __ _  ___   ___   __ _| | ___    __ _ _ __   __ _| |_   _| |_ _  ___ ___
 / _` |/ _ \ / _ \ / _` | |/ _ \  / _` | '_ \ / _` | | | | | __| |/ __/ __|
| (_| | (_) | (_) | (_| | |  __/ | (_| | | | | (_| | | |_| | |_| | (__\__ \
 \__, |\___/ \___/ \__, |_|\___|  \__,_|_| |_|\__,_|_|\__, |\__|_|\___|___/
  __/ |             __/ |                              __/ |
 |___/             |___/                              |___/

analytics.js:26 Running analytics_debug.js. This script is intended for testing and debugging only.
log @ analytics.js:26
J @ analytics.js:25
(anonymous) @ analytics.js:123
(anonymous) @ analytics.js:123
analytics.js:26 Initializing Google Analytics.
analytics.js:26 Running command: ga("create", "UA-27656468-6", {cookieDomain: "auto", allowLinker: true, name: "gtag_UA_27656468_6"})
analytics.js:26 Creating new tracker: gtag_UA_27656468_6
analytics.js:26 Auto cookieDomain found: "mydomain.com"
analytics.js:26 Running command: ga(Function)
analytics.js:26 Running command: ga(Function)
analytics.js:26 Running command: ga("gtag_UA_27656468_6.require", "linker")
analytics.js:26 Plugin "linker" intialized on tracker "gtag_UA_27656468_6".
analytics.js:26 Running command: ga("gtag_UA_27656468_6.linker:autoLink", ["mydomain.com"], false, false)
analytics.js:26 Running command: ga("gtag_UA_27656468_6.set", {anonymizeIp: true, forceSSL: true, &gtm: "2ou770"})
analytics.js:26 Running command: ga("gtag_UA_27656468_6.send", "pageview", {&did: "dZTNiMT", hitCallback: [function]})
js?id=UA-27656468-6:128 Sending "Google Analytics" hit.
js?id=UA-27656468-6:128 Target ID: "UA-27656468-6"
js?id=UA-27656468-6:128 Hit URL: "https://www.google-analytics.com/collect?v=1&_v=j91d&aip=1&a=261767914&t=pageview&_s=1&dl=https%3A%2F%2Fmydomain.com%2Frelease%2Fipsiom-xyz%2F&ul=en-us&de=UTF-8&dt=Ipsiom%20-%20XYZ%20-%20Kinphonic&sd=24-bit&sr=1920x1080&vp=1920x476&je=0&_u=wCCACUABB~&jid=&gjid=&cid=2066192423.1625739807&tid=UA-27656468-6&_gid=1708135985.1625739807&gtm=2ou770&did=dZTNiMT&z=1388580668"
js?id=UA-27656468-6:128 Hit Data:
js?id=UA-27656468-6:128 "&did": "dZTNiMT"
js?id=UA-27656468-6:128 "hitCallback": [function]
js?id=UA-27656468-6:128 "hitType": "pageview"
analytics.js:26 
Sent beacon:
v=1&_v=j91d&aip=1&a=261767914&t=pageview&_s=1&dl=https%3A%2F%2Fmydomain.com%2Frelease%2Fipsiom-xyz%2F&ul=en-us&de=UTF-8&dt=Ipsiom%20-%20XYZ%20-%20Kinphonic&sd=24-bit&sr=1920x1080&vp=1920x476&je=0&_u=wCCACUABB~&jid=&gjid=&cid=2066192423.1625739807&tid=UA-27656468-6&_gid=1708135985.1625739807&gtm=2ou770&did=dZTNiMT&z=1388580668


analytics.js:26 <unknown>        (&did)  dZTNiMT
analytics.js:26 <unknown>        (&gtm)  2ou770
analytics.js:26 _j1              (&jid)  
analytics.js:26 _j2              (&gjid) 
analytics.js:26 adSenseId        (&a)    261767914
analytics.js:26 anonymizeIp      (&aip)  1
analytics.js:26 apiVersion       (&v)    1
analytics.js:26 clientId         (&cid)  2066192423.1625739807
analytics.js:26 encoding         (&de)   UTF-8
analytics.js:26 hitType          (&t)    pageview
analytics.js:26 javaEnabled      (&je)   0
analytics.js:26 language         (&ul)   en-us
analytics.js:26 location         (&dl)   https://mydomain.com/release/ipsiom-xyz/
analytics.js:26 screenColors     (&sd)   24-bit
analytics.js:26 screenResolution (&sr)   1920x1080
analytics.js:26 title            (&dt)   Title
analytics.js:26 trackingId       (&tid)  UA-27656468-6
analytics.js:26 viewportSize     (&vp)   1920x476
analytics.js:26 Registered new plugin: ga(provide, "render", Function)
js?id=G-W4Y829SYNH&l=dataLayer&cx=c:415        _                 _
  __ _| |_ __ _  __ _   (_)___
 / _` | __/ _` |/ _` |  | / __|
| (_| | || (_| | (_| |_ | \__ \
 \__, |\__\__,_|\__, (_)/ |___/
 |___/          |___/ |__/


js?id=G-W4Y829SYNH&l=dataLayer&cx=c:415 Duplicate container installation abandoned: G-W4Y829SYNH
js?id=UA-27656468-6:128 Processing commands (1)
js?id=UA-27656468-6:128 Processing data layer push: {event: "gtm.load"}
js?id=G-W4Y829SYNH:415 Processing commands (1)
js?id=G-W4Y829SYNH:415 Processing data layer push: {event: "gtm.load", gtm.uniqueEventId: 17}
js?id=G-W4Y829SYNH:415 Tag fired: {function: "__sdl", vtp_verticalThresholdUnits: "PERCENT", vtp_verticalThresholdsPercent: "90", vtp_verticalThresholdOn: true, vtp_horizontalThresholdOn: false, vtp_triggerStartOption: "WINDOW_LOAD", vtp_uniqueTriggerId: "1_33", vtp_enableTriggerStartOption: true, tag_id: 43}
js?id=UA-27656468-6:128 Processing commands (1)
js?id=UA-27656468-6:128 Processing GTAG command: ["event", "link-service", {action: "https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle", service: "spotify"}]
analytics.js:26 Executing Google Analytics commands.
analytics.js:26 Running command: ga("create", "UA-27656468-6", {cookieDomain: "auto", allowLinker: true, name: "gtag_UA_27656468_6"})
analytics.js:26 Ignoring create request for duplicate tracking name.
log @ analytics.js:26
J @ analytics.js:25
Z.create @ analytics.js:116
Y.b.<computed> @ analytics.js:73
jf.R @ analytics.js:115
jf.H @ analytics.js:113
Z @ analytics.js:116
Gn @ js?id=UA-27656468-6:203
(anonymous) @ js?id=UA-27656468-6:207
ce @ js?id=UA-27656468-6:81
ke @ js?id=UA-27656468-6:83
Hn @ js?id=UA-27656468-6:207
bo @ js?id=UA-27656468-6:222
Sn.flush @ js?id=UA-27656468-6:226
Sn.push @ js?id=UA-27656468-6:224
Un @ js?id=UA-27656468-6:220
event @ js?id=UA-27656468-6:238
wp @ js?id=UA-27656468-6:248
a.push @ js?id=UA-27656468-6:252
a.push @ js?id=G-W4Y829SYNH:513
a.push @ gtm.js?id=GTM-5F4PKGW:196
gtag @ (index):830
(anonymous) @ 6d7ca.js:5
dispatch @ d52ed.js:2
v.handle @ d52ed.js:2
analytics.js:26 Executing Google Analytics commands.
analytics.js:26 Running command: ga(Function)
analytics.js:26 Executing Google Analytics commands.
analytics.js:26 Running command: ga(Function)
analytics.js:26 Executing Google Analytics commands.
analytics.js:26 Running command: ga("gtag_UA_27656468_6.require", "linker")
analytics.js:26 Command ignored. Plugin "linker" has already been required on tracker "gtag_UA_27656468_6".
log @ analytics.js:26
O @ analytics.js:25
x @ analytics.js:109
jf.R @ analytics.js:115
jf.H @ analytics.js:113
Z @ analytics.js:116
Nj @ js?id=UA-27656468-6:156
un @ js?id=UA-27656468-6:200
Gn @ js?id=UA-27656468-6:204
(anonymous) @ js?id=UA-27656468-6:207
ce @ js?id=UA-27656468-6:81
ke @ js?id=UA-27656468-6:83
Hn @ js?id=UA-27656468-6:207
bo @ js?id=UA-27656468-6:222
Sn.flush @ js?id=UA-27656468-6:226
Sn.push @ js?id=UA-27656468-6:224
Un @ js?id=UA-27656468-6:220
event @ js?id=UA-27656468-6:238
wp @ js?id=UA-27656468-6:248
a.push @ js?id=UA-27656468-6:252
a.push @ js?id=G-W4Y829SYNH:513
a.push @ gtm.js?id=GTM-5F4PKGW:196
gtag @ (index):830
(anonymous) @ 6d7ca.js:5
dispatch @ d52ed.js:2
v.handle @ d52ed.js:2
analytics.js:26 Executing Google Analytics commands.
analytics.js:26 Running command: ga("gtag_UA_27656468_6.linker:autoLink", ["mydomain.com"], false, false)
analytics.js:26 Executing Google Analytics commands.
analytics.js:26 Running command: ga("gtag_UA_27656468_6.set", {anonymizeIp: true, forceSSL: true, &gtm: "2ou770"})
analytics.js:26 Executing Google Analytics commands.
analytics.js:26 Running command: ga("gtag_UA_27656468_6.send", "event", {&did: "dZTNiMT", hitCallback: [function], eventCategory: "general", eventAction: "link-service"})
js?id=UA-27656468-6:128 Sending "Google Analytics" hit.
js?id=UA-27656468-6:128 Target ID: "UA-27656468-6"
js?id=UA-27656468-6:128 Hit URL: "https://www.google-analytics.com/collect?v=1&_v=j91d&aip=1&a=261767914&t=event&_s=2&dl=https%3A%2F%2Fmydomain.com%2Frelease%2Fipsiom-xyz%2F&ul=en-us&de=UTF-8&dt=Ipsiom%20-%20XYZ%20-%20Kinphonic&sd=24-bit&sr=1920x1080&vp=1920x476&je=0&ec=general&ea=link-service&_u=yCCACUABB~&jid=&gjid=&cid=2066192423.1625739807&tid=UA-27656468-6&_gid=1708135985.1625739807&gtm=2ou770&did=dZTNiMT&z=981894877"
js?id=UA-27656468-6:128 Hit Data:
js?id=UA-27656468-6:128 "&did": "dZTNiMT"
js?id=UA-27656468-6:128 "hitCallback": [function]
js?id=UA-27656468-6:128 "eventCategory": "general"
js?id=UA-27656468-6:128 "eventAction": "link-service"
js?id=UA-27656468-6:128 "hitType": "event"
analytics.js:26 
Sent beacon:
v=1&_v=j91d&aip=1&a=261767914&t=event&_s=2&dl=https%3A%2F%2Fmydomain.com%2Frelease%2Fipsiom-xyz%2F&ul=en-us&de=UTF-8&dt=Ipsiom%20-%20XYZ%20-%20Kinphonic&sd=24-bit&sr=1920x1080&vp=1920x476&je=0&ec=general&ea=link-service&_u=yCCACUABB~&jid=&gjid=&cid=2066192423.1625739807&tid=UA-27656468-6&_gid=1708135985.1625739807&gtm=2ou770&did=dZTNiMT&z=981894877


analytics.js:26 <unknown>        (&did)  dZTNiMT
analytics.js:26 <unknown>        (&gtm)  2ou770
analytics.js:26 _j1              (&jid)  
analytics.js:26 _j2              (&gjid) 
analytics.js:26 adSenseId        (&a)    261767914
analytics.js:26 anonymizeIp      (&aip)  1
analytics.js:26 apiVersion       (&v)    1
analytics.js:26 clientId         (&cid)  2066192423.1625739807
analytics.js:26 encoding         (&de)   UTF-8
analytics.js:26 eventAction      (&ea)   link-service
analytics.js:26 eventCategory    (&ec)   general
analytics.js:26 hitType          (&t)    event
analytics.js:26 javaEnabled      (&je)   0
analytics.js:26 language         (&ul)   en-us
analytics.js:26 location         (&dl)   https://mydomain.com/release/ipsiom-xyz/
analytics.js:26 screenColors     (&sd)   24-bit
analytics.js:26 screenResolution (&sr)   1920x1080
analytics.js:26 title            (&dt)   Title
analytics.js:26 trackingId       (&tid)  UA-27656468-6
analytics.js:26 viewportSize     (&vp)   1920x476
js?id=G-W4Y829SYNH:415 Loaded existing client id: 2066192423.1625739807
js?id=G-W4Y829SYNH:415 Event would be batched, but batching is disabled in debug mode.
js?id=G-W4Y829SYNH:415 Sending event "link-service" to undefined
js?id=G-W4Y829SYNH:415 Request parameters:
js?id=G-W4Y829SYNH:415 v: 2
js?id=G-W4Y829SYNH:415 tid: G-W4Y829SYNH
js?id=G-W4Y829SYNH:415 gtm: 2oe770
js?id=G-W4Y829SYNH:415 _p: 261767914
js?id=G-W4Y829SYNH:415 sr: 1920x1080
js?id=G-W4Y829SYNH:415 _dbg: 1
js?id=G-W4Y829SYNH:415 ul: en-us
js?id=G-W4Y829SYNH:415 _uei: 9
js?id=G-W4Y829SYNH:415 cid: 2066192423.1625739807
js?id=G-W4Y829SYNH:415 Event parameters:
js?id=G-W4Y829SYNH:415 en: link-service
js?id=G-W4Y829SYNH:415 _et: 8904
js?id=G-W4Y829SYNH:415 ep.action: https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle
js?id=G-W4Y829SYNH:415 ep.service: spotify
js?id=G-W4Y829SYNH:415 Shared parameters:
js?id=G-W4Y829SYNH:415 dl: https://mydomain.com/release/ipsiom-xyz/
js?id=G-W4Y829SYNH:415 dr: https://mydomain.com/?gtm_debug=x
js?id=G-W4Y829SYNH:415 dt: Title
js?id=G-W4Y829SYNH:415 sid: 1625739805
js?id=G-W4Y829SYNH:415 sct: 1
js?id=G-W4Y829SYNH:415 seg: 1
js?id=G-W4Y829SYNH:415 Sending request: https://www.google-analytics.com/g/collect?v=2&tid=G-W4Y829SYNH&gtm=2oe770&_p=261767914&sr=1920x1080&_dbg=1&ul=en-us&_uei=9&cid=2066192423.1625739807&_s=2&dl=https%3A%2F%2Fmydomain.com%2Frelease%2Fipsiom-xyz%2F&dr=https%3A%2F%2Fmydomain.com%2F%3Fgtm_debug%3Dx&dt=Ipsiom%20-%20XYZ%20-%20Kinphonic&sid=1625739805&sct=1&seg=1&en=link-service&_et=8904&ep.action=https%3A%2F%2Fopen.spotify.com%2Falbum%2F76O5oTjPviIS5vsSyPsKle&ep.service=spotify
js?id=G-W4Y829SYNH:415 Processing commands (1)
js?id=G-W4Y829SYNH:415 Processing GTAG command: ["event", "link-service", {action: "https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle", service: "spotify"}]
js?id=UA-27656468-6:128 Processing commands (1)
js?id=UA-27656468-6:128 Processing data layer push: {event: "gtm.linkClick", gtm.element: https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle, gtm.elementClasses: "", gtm.elementId: "", gtm.elementTarget: "blank", gtm.triggers: "1_15,1_22", gtm.elementUrl: "https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle", eventCallback: [function], eventTimeout: 2000}
js?id=G-W4Y829SYNH:415 Processing commands (1)
js?id=G-W4Y829SYNH:415 Processing data layer push: {event: "gtm.linkClick", gtm.element: https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle, gtm.elementClasses: "", gtm.elementId: "", gtm.elementTarget: "blank", gtm.triggers: "1_15,1_22", gtm.elementUrl: "https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle", eventCallback: [function], eventTimeout: 2000, gtm.uniqueEventId: 19}
js?id=G-W4Y829SYNH:415 Tag fired: {function: "__get", vtp_eventName: "click", vtp_settings: ["map", "streamId", "G-W4Y829SYNH", "eventParameters", ["map", "link_id", ["macro", 6], "link_classes", ["macro", 7], "link_url", ["macro", 8], "link_domain", ["macro", 9], "outbound", true]], vtp_deferrable: false, tag_id: 17}
js?id=G-W4Y829SYNH:415 Loaded existing client id: 2066192423.1625739807
js?id=G-W4Y829SYNH:415 Event would be batched, but batching is disabled in debug mode.
js?id=G-W4Y829SYNH:415 Sending event "click" to undefined
js?id=G-W4Y829SYNH:415 Request parameters:
js?id=G-W4Y829SYNH:415 v: 2
js?id=G-W4Y829SYNH:415 tid: G-W4Y829SYNH
js?id=G-W4Y829SYNH:415 gtm: 2oe770
js?id=G-W4Y829SYNH:415 _p: 261767914
js?id=G-W4Y829SYNH:415 sr: 1920x1080
js?id=G-W4Y829SYNH:415 _dbg: 1
js?id=G-W4Y829SYNH:415 ul: en-us
js?id=G-W4Y829SYNH:415 _uei: 9
js?id=G-W4Y829SYNH:415 cid: 2066192423.1625739807
js?id=G-W4Y829SYNH:415 Event parameters:
js?id=G-W4Y829SYNH:415 en: click
js?id=G-W4Y829SYNH:415 _et: 271
js?id=G-W4Y829SYNH:415 ep.link_id: 
js?id=G-W4Y829SYNH:415 ep.link_classes: 
js?id=G-W4Y829SYNH:415 ep.link_url: https://open.spotify.com/album/76O5oTjPviIS5vsSyPsKle
js?id=G-W4Y829SYNH:415 ep.link_domain: open.spotify.com
js?id=G-W4Y829SYNH:415 ep.outbound: true
js?id=G-W4Y829SYNH:415 Shared parameters:
js?id=G-W4Y829SYNH:415 dl: https://mydomain.com/release/ipsiom-xyz/
js?id=G-W4Y829SYNH:415 dr: https://mydomain.com/?gtm_debug=x
js?id=G-W4Y829SYNH:415 dt: Title
js?id=G-W4Y829SYNH:415 sid: 1625739805
js?id=G-W4Y829SYNH:415 sct: 1
js?id=G-W4Y829SYNH:415 seg: 1
js?id=G-W4Y829SYNH:415 Sending request: https://www.google-analytics.com/g/collect?v=2&tid=G-W4Y829SYNH&gtm=2oe770&_p=261767914&sr=1920x1080&_dbg=1&ul=en-us&_uei=9&cid=2066192423.1625739807&_s=3&dl=https%3A%2F%2Fmydomain.com%2Frelease%2Fipsiom-xyz%2F&dr=https%3A%2F%2Fmydomain.com%2F%3Fgtm_debug%3Dx&dt=Ipsiom%20-%20XYZ%20-%20Kinphonic&sid=1625739805&sct=1&seg=1&en=click&_et=271&ep.link_id=&ep.link_classes=&ep.link_url=https%3A%2F%2Fopen.spotify.com%2Falbum%2F76O5oTjPviIS5vsSyPsKle&ep.link_domain=open.spotify.com&ep.outbound=true`
