### ISSUE TITLE
Improve Optimize setup notice

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1121]
## Feature Description

The current Analytics module has an option to exclude logged in users from tracking. By default that option is enabled, so WP admins are not counted in metrics. 

<img width="515" alt="Screen Shot 2020-02-11 at 2 40 10 PM" src="https://user-images.githubusercontent.com/41326532/74247718-6938c400-4cde-11ea-9f67-f4b48ff9e888.png">

The Site Kit Optimize module depends on the Analytics module being enabled.  

When an account is setup from within the Optimize platform and connected via the Analytics property it can cause false diagnostics errors (from within the Optimize platform).

<img width="1341" alt="Screen Shot 2020-02-11 at 2 56 59 PM" src="https://user-images.githubusercontent.com/41326532/74247958-c92f6a80-4cde-11ea-9076-7feb9b4c07df.png">

<img width="872" alt="Screen Shot 2020-02-11 at 2 38 58 PM" src="https://user-images.githubusercontent.com/41326532/74247666-51614000-4cde-11ea-9d1c-d91c35a0aba4.png">

As users connecting the Optimize module may following this standard setup flow from the same browser (while logged into their WordPress dashboard) they may encounter this issue. 

**Should we place a notice within the Optimize module connection below to inform users to perform an Optimize diagnostics test once not logged in?** 

Without such as notice users may encounter false diagnostics errors. 

<img width="726" alt="Screen Shot 2020-02-11 at 3 01 20 PM" src="https://user-images.githubusercontent.com/41326532/74248365-64284480-4cdf-11ea-9ef9-fbb41b777d3f.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing per #6466
