### ISSUE TITLE
Check to see if E2E environment is running when running test:e2e command

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1122]
## Feature Description

The E2E test suite requires a set of Docker containers (started with `npm run env:start`). This requirement makes sense and most of the time doesn't create issues, but is a bit new-contributor-hostile and is also an easy thing to mess up after a Docker restart or system restart. If you restart your machine, update Docker, or otherwise forget to start the E2E test environment, you'll run the test the first time only to see:

```
 ● Test suite failed to run
    Error: net::ERR_CONNECTION_REFUSED at http://localhost:9002/wp-admin/plugins.php
```

This is easily avoidable by having the E2E test script first try to connect to http://localhost:9002 (via a modified script that makes a `curl` request to http://localhost:9002, and if it can't connect running `npm run env:start` first.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Running `npm run test:e2e` on a machine that has not run the E2E Docker environment (started by `npm run env:start`) does not fail with a "connection refused" error.

## Implementation Brief

* Add a script (or npm `pre` script) to `npm run test:e2e` that tries to `curl` http://localhost:9002. If there is a response, run `return 0` right away; if not, run `npm run env:start` then `return 0`.

## QA Brief

* On a new checkout of the repo, run: `composer install && npm install && npm run build`
* Run `npm run env:stop` to ensure env is stopped since it is global
* Run `npm run test:e2e`

The E2E tests should run as if the environment was running; no error should be output and the script should exit normally.

## Changelog entry

*

**Comment by tofumatt** [comment]
(I moved this one along into IB review as it is extremely straightforward to write and largely a developer quality-of-life issue. If that's a bad thing let me know and we can push it back. This is also not high-priority, but came to mind after biting me and I figured I should just file 😄)

**Comment by aaemnnosttv** [comment]
The e2e environment has a `restart: always` policy so it should restart automatically once started even after rebooting. Are you sure this isn't the case?

I agree that the experience could be better for a first-time run, where it may not be obvious that a separate command is necessary to start the environment before the test command.

**Comment by tofumatt** [comment]
Ah, I see! I was likely getting confused with my `10updocker` site re: restarting, so this might be more a first-run experience. In that case: more annoying to QA, and possibly much less of an issue—though still something to be (quickly and straightforwardly) improved.

**Comment by aaemnnosttv** [comment]
We actually already have something very similar to this which is used for backstop as it needs to start storybook and wait for it to be ready before running its tests.

The command is `start-server-and-test` (see `test:visualtest`). We should be able to use this to call `env:start http://localhost:9002 test:e2e:run`  (where test:e2e:run is the current command). Not sure if this would work with passing arguments the way we do now. Ideally the `env:start` command would be updated as well to finish early if the env was already running (currently it will do the whole install again every time).

**Comment by felixarntz** [comment]
IB ✅ 

Given that this is is rather low priority, let's only pick it up if we really have capacity left. It should be super small, but basically, if there's any unexpected complication, let's defer to later.

**Comment by cole10up** [comment]
**Tested**

Ran `npm run env:stop`
Then `npm run test:e2e`
![image](https://user-images.githubusercontent.com/57115907/80684242-3949c300-8a7a-11ea-893b-723e0f7cd44b.png)

Confirmed E2E test acknowledged the docker container wasn't found, kicked it off and continued.

Ran a positive test through and confirmed E2E passed

Passed QA ✅
