### ISSUE TITLE
Consolidate Backstop/VRT commands into one

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1124]
## Feature Description

Currently we have several different commands defined for running BackstopJS for VRT in both local environments and on Travis. These also include duplicate configuration files, the only difference being the target hostname to use for the URL for stories. This varies by platform as Docker does not have a single internal hostname for resolving the host machine's IP. We need this because Backstop runs in a Docker container, but it targets the development server run by Storybook on the host machine.

Consolidating the configuration allows us to have a single command for running VRT, regardless of the environment. There is nothing particularly special about the `travis:` variant, only that it's running from a Linux host. This is confusing for contributors who are running Linux, that they would have needed to run the `travis` command rather than the main `test:visualtest` command to run VRT.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `test:visualtest` should be the only npm script for running VRT  
_Excluding the `backstopjs` script which is used internally by `start-server-and-test` with `storybook`_

## Implementation Brief

This is slightly tricky to implement as Backstop first loads on the host and then again within the docker container so we need to differentiate between the two at runtime. This is possible by checking for the `--docker` command argument which is only passed when running from the host (see npm script). However, this flag is not present in the command that is run within Docker. It uses `--moby` instead. Any additional arguments to the `backstop test` command are passed along to the container as well.

* Detect the proper hostname to use for Storybook when loading on the host from the Backstop config file and set this as a new argument on the process dynamically to be passed along to the command run with Docker.
* Delete Travis-specific commands and configuration
* Merge #1123 

## QA Brief

* 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
(Issue approved, just needs @felixarntz to merge 🙂)

**Comment by tofumatt** [comment]
QA, runs here and on Travis! ✅
