### ISSUE TITLE
Analytics in posts list

### ISSUE THREAD

**Issue by maloherry** [google/site-kit-wp#1127]
## Feature Description

In Wordpress posts list (wp-admin/edit.php), add a column with an icon for each post. When the admin clicks on the icon, it opens a modal (or a new tab) with analytics information for this particular post.

This feature allows authors, editors and administrators to quickly answer the most asked question : "how did my paper work?"

This feature exists for instance in ExactMetrics : https://wordpress.org/plugins/google-analytics-dashboard-for-wp/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by Tom-Woef** [comment]
would be a feature that i like to see

**Comment by gmmedia** [comment]
Great idea

**Comment by felixarntz** [comment]
Thanks for the issue, this has been on our mind for a while. We're tracking this via #296, so please follow along that one for any updates.
