### ISSUE TITLE
Sparkline color does not match arrow when inverted

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1128]
## Bug Description

In #481 we fixed the `DataBlock` arrow color for metrics which have inverted scoring (increase is bad) however the color used for `Sparkline` charts is still using the same standard scoring logic for determining its color.

## Steps to reproduce

* Authenticate with a site that has an increase in bounce rate
* Navigate to the Analytics dashboard
* See green sparkline with (correct) red arrow pointing up

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/74419595-d40b0c00-4e52-11ea-95c8-fb101cb269fe.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Sparkline color should match the color of the increase/decrease arrow for `DataBlocks`

## Implementation Brief

* Add a `invertChangeColor` prop to `Sparkline`
* Set this prop accordingly for `DataBlocks` that use it  
Currently `DataBlocks` accepts the full `Sparkline` component via the `sparkline` prop. Ideally, this would be rendered internally as there are multiple shared props, such as `change` and (in this case) `invertChangeColor`. This could be done by changing the `sparkline` prop to accept an object of props to pass to the `Sparkline` component, in addition to those it shares.
* Refactor/simplification: Wrap `Sparkline` with the `withInstanceId` HOC which can be used to build a unique `id` rather than passing it in for each

## QA Brief

* 

## Changelog entry

* Fix misleading sparkline color for metrics that should use the inverted color, such as bounce rate.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## ✅ QA

Sparkline color now matches arrow in inverted (bounce rate) and normal modes

![image](https://user-images.githubusercontent.com/1621608/75337666-1c381e80-5896-11ea-807a-624503885be7.png)

Moving to approval.
