### ISSUE TITLE
Composer tweaks

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#113]
## Feature Description

This issue proposes a few minor changes to the `composer.json` file:

1. The `composer.json` file currently contains a `version` key. This is recommended to be omitted [according to the schema](https://getcomposer.org/doc/04-schema.md#version). Unless this is necessary for some reason, it's better for this to be inferred from VCS.

1. Regarding the `scripts` section, the `vendor/bin/` prefix on the commands is unnecessary and generally a good idea to omit as the location of the vendor directory is configurable.
As noted in the documentation for [writing custom commands](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands):  
> Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are easily accessible.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Remove the `vendor/bin/` prefix on the commands in `composer.json`.

## Implementation Brief

* Remove the `vendor/bin/` prefix from `lint` and `lint-fix` commands in `composer.json`

Per [@swissspidy's comment](https://github.com/google/site-kit-wp/issues/113#issuecomment-546948844)
* Set `sort-packages` config to `true` (and sort existing requires)
* Add `roave/security-advisories` to `require-dev`
* Replace `phpcompatibility/php-compatibility` with `phpcompatibility/phpcompatibility-wp`  
_`phpcompatibility/php-compatibility` will still be installed, but as a dependency of the WP variant_
* Adding required PHP extensions to `require`
  - `ext-json`
  - `ext-openssl`
  - what else?

## Changelog entry

* N/A

**Comment by swissspidy** [comment]
As for the version number, the same goes for `package.json`, especially when the package is not published on npm.

**Comment by felixarntz** [comment]
Regarding the version number in `composer.json` and `package.json`, I just removed that in https://github.com/google/site-kit-wp/commit/246842c90d7cf678e310b7b2ca79af44478923c5. That leaves us with just the second point for this one.

**Comment by swissspidy** [comment]
There are some other configuration changes that might be useful in `composer.json`:

* Adding required PHP extensions to `require`
* Adding `roave/security-advisories` as a dev dependency
* Require `phpcompatibility/phpcompatibility-wp` instead of `phpcompatibility/php-compatibility`
* Set `config.sort-packages` to `true`

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Confirmed that composer functions after installing homebrew and running `brew install php`

Verified .zip was functional and able to update builds properly.

Passed QA ✅
