### ISSUE TITLE
Plugin Activation E2E test is unstable

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1130]
## Bug Description

Since implementing the plugin activation as a React component (#991), running `npm run test:e2e -- specs/plugin-activation.test.js` locally has become much less stable—the selectors the E2E tests wait for to run their assertions no longer ensure all content is loaded, so the selectors can timeout after the `500ms` timeout. But sometimes they _don't_, leading to race condition E2E tests which are no fun!

There's an easy fix for this: wait for the proper selectors to be rendered by the React component in the test. 😄

## Steps to reproduce

1. Run `npm run test:e2e -- specs/plugin-activation.test.js` several times
2. Sometimes it will pass, sometimes it will fail with a timeout error

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `plugin-activation.test.js` E2E should pass consistently.

## Implementation Brief

* Add `await page.waitForSelector( 'h3.googlesitekit-activation__title' );` after https://github.com/google/site-kit-wp/blob/5219216fdc97a9415f4b3993f752456e23fd7df4/tests/e2e/specs/plugin-activation.test.js#L50 and https://github.com/google/site-kit-wp/blob/5219216fdc97a9415f4b3993f752456e23fd7df4/tests/e2e/specs/plugin-activation.test.js#L61

## QA Brief

* `npm run test:e2e -- specs/plugin-activation.test.js` should pass consistently

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Updated my machine to run docker here: https://www.docker.com/products/docker-desktop

ran the following `npm run env:start` `build:test` then `npm run test:e2e -- specs/plugin-activation.test.js`

![image](https://user-images.githubusercontent.com/57115907/74631753-99cf9200-5112-11ea-98da-9834b13b51bc.png)

Confirmed 5 runs, no timeouts - all passed. 16 seconds each run. 

Passed QA ✅
