### ISSUE TITLE
Have an Option to Make Code Local

### ISSUE THREAD

**Issue by ElectronEsq** [google/site-kit-wp#1132]
## Have an Option to Make Code Local

Anyone running their site through things like GTMetrix will see how GTM etc negatively affects the score. If all the required code was delivered locally via this plugin and cached, it would really help.

The plugin could always update the local code when a new version is available, so there would be no downside to doing this. It would give people more control over their sites performance.

I recently uninstalled Site Kit to do this manually myself.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by morganhvidt** [comment]
This would be really nice!

**Comment by jamesozzie** [comment]
@Invariant-Change Thanks for the suggestion. I've added as a feature request for the team to consider.

**Comment by glanglois** [comment]
It would be great to store locally Google Analytics and Tag Manager, through Site Kit, to have everything related to Google services handled in one plugin.

In the meantime, this option is offered by caching plugins such as WPRocket (https://docs.wp-rocket.me/article/1103-google-tracking-add-on)

**Comment by jamesozzie** [comment]
@glanglois Thanks for the input. The team will review this feature request going forward. Note however this isn't guaranteed to be part of future releases, with hosting the JavaScript files locally [not recommended](https://support.google.com/analytics/answer/1032389?hl=en).

**Comment by jonathansoltero** [comment]
This isn't only GTM, Google's own PageSpeed Insights. That's why I scratch my head.

**Comment by felixarntz** [comment]
As mentioned above, [self-hosting the Google service JS files is not recommended](https://support.google.com/analytics/answer/1032389). There are teams in Google which are actively working on improving performance for the scripts used by websites across the web, so hopefully this will become a less of an issue in the future.

Site Kit itself will for the above reason not self-host these assets. If you wish to do so, you can use a plugin like WP Rocket (as mentioned above) in combination with Site Kit.
