### ISSUE TITLE
Check if opcache_reset function exists

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1136]
## Bug Description

The `opcache_reset()` function may not be present on all systems which can result in fatal errors (see https://wordpress.org/support/topic/undefined-function-opcache_reset-v1-3-0/). This is a follow-up to #1066.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `function_exists` check before calling `opcache_reset`.

## Implementation Brief

* There should be a `function_exists` check before calling `opcache_reset` in `googlesitekit_opcache_reset`.

## QA Brief

* N/A

## Changelog entry

* Ensure `opcache_reset()` exists before calling it.

**Comment by aaemnnosttv** [comment]
IB ✅
