### ISSUE TITLE
WordPress caught an error with one of your plugins, Site Kit by Google.

### ISSUE THREAD

**Issue by peterhuckle** [google/site-kit-wp#1138]
Everything seems to be working fine but this is the error generated ...

Error Details
=============
An error of type E_ERROR was caused in line 102 of the file /home/pagemake/kohukohu.com/wp/wp-content/plugins/google-site-kit/google-site-kit.php. Error message: Uncaught Error: Call to undefined function opcache_reset() in /home/pagemake/kohukohu.com/wp/wp-content/plugins/google-site-kit/google-site-kit.php:102
Stack trace:
#0 /home/pagemake/kohukohu.com/wp/wp-includes/class-wp-hook.php(290): googlesitekit_opcache_reset(Object(Plugin_Upgrader))
#1 /home/pagemake/kohukohu.com/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /home/pagemake/kohukohu.com/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/pagemake/kohukohu.com/wp/wp-admin/includes/class-plugin-upgrader.php(316): do_action('upgrader_proces...', Object(Plugin_Upgrader), Array)
#4 /home/pagemake/kohukohu.com/wp/wp-admin/includes/ajax-actions.php(4421): Plugin_Upgrader->bulk_upgrade(Array)
#5 /home/pagemake/kohukohu.com/wp/wp-includes/class-wp-hook.php(288): wp_ajax_update_plugin('')
#6 /home/pagemake/kohukohu.com/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#7 /home/pagemake/kohukohu.com/wp/wp-includes/plugin.php(478): WP_Hook->do_actio

**Comment by jamesozzie** [comment]
@peterhuckle Thanks for reporting. We've moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. 

You can also try [resetting Site Kit](https://i.imgur.com/slHxBGO.png) before then deleting the plugin in full. After doing so please install and setup once more, using a Chrome browser [incognito](https://i.imgur.com/ALzgiHp.png) window.
