### ISSUE TITLE
Improve element className readability

### ISSUE THREAD

**Issue by Shavindra** [google/site-kit-wp#1139]
## Feature Description
Improve readability by using `classnames` if an element has more than one class. 
e.g 
https://github.com/Shavindra/site-kit-wp/blob/9cb4448a811ab58880b99bd47447e9fba5dec6e9/assets/js/components/page-header.js#L75-L82
```
<div className={ classnames(
    'mdc-layout-grid__cell',
    'mdc-layout-grid__cell--align-bottom',
    'mdc-layout-grid__cell--align-right-tablet',
    'mdc-layout-grid__cell--span-4-phone',
    'mdc-layout-grid__cell--span-4-tablet',
    'mdc-layout-grid__cell--span-6-desktop',
) }>
```
compared to:
```
<div className={ `
    mdc-layout-grid__cell
    mdc-layout-grid__cell--align-bottom
    mdc-layout-grid__cell--align-right-tablet
    mdc-layout-grid__cell--span-4-phone
    mdc-layout-grid__cell--span-4-tablet
    mdc-layout-grid__cell--span-6-desktop
` }>
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Hi there

Thanks for the  suggestion, we are already tracking this in #1072. I see you mention that issue already in your PR #1133, so I am closing this one here as a duplicate.

**Comment by tofumatt** [comment]
This issue focuses on improving the readability of _static_ `className` props with multiple classes but no dynamic values. This is largely a readability issue and separate from the review in #1133—so I don't think this one is a duplicate, more of a code-quality follow-up.

**Comment by aaemnnosttv** [comment]
@tofumatt would you please review this to see if it's still relevant? I believe we're already doing this in new/refactored components. Not sure it's worth a dedicated issue for older ones that will probably be removed (or refactored) at some point anyways.

**Comment by tofumatt** [comment]
I had a look through the codebase and agree that this is no longer relevant. We've updated a lot of these issues and it isn't worth the dedicated issue anymore as there are few left and refactors tend to clean up this code.

I think we can close this issue now 🙂
