### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined in `readableLargeNumber`  for integer only currencies.

### ISSUE THREAD

**Issue by torounit** [google/site-kit-wp#114]
## Bug Description

TypeError: Cannot read property 'value' of undefined in [readableLargeNumber](https://github.com/google/site-kit-wp/blob/release/v1.0.0-beta.1.0.1/assets/js/util/index.js#L138) 

This error occurs for currencies that do not use decimals.

The return value of `Intl.NumberFormat.prototype.formatToParts` does not always include `{ type: 'decimal' }`.  (ex. JPY, ISK, KRW ... )

## Steps to reproduce

1. Change currency JPY.
2. install plugin and activate adsense.
3. goto adsense setting page.

## Additional Context

 - PHP Version: 7.2
 - OS: OS X 10.14
 - Browser: Chrome 75.0
 - Plugin Version: 1.0.0-beta.1.0.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All currency values in AdSense subreport and across the plugin should be displayed correctly, regardless of whether they use a decimal point or not. 
* No JS errors should be displayed for these currency values. 

## Implementation Brief

 
Split https://github.com/google/site-kit-wp/blob/develop/assets/js/util/index.js#L138 to find decimal and check if defined before setting the value.
Replace in https://github.com/google/site-kit-wp/blob/develop/assets/js/util/index.js#L141 only if decimal is defined.

## Changelog entry

* Fix potential JavaScript error when formatting currency values.

**Comment by jamesozzie** [comment]
@torounit Can you confirm that this is the same issue as #93, relating to your AdSense dashboard?

**Comment by torounit** [comment]
@jamesozzie  This issue is different from #93 . 

This error occurs only Adsense setting page in Site Kit. (/admin.php?page=googlesitekit-module-adsense)

**Comment by lucymtc** [comment]
ready for implementation brief review

**Comment by adamsilverstein** [comment]
Hello @torounit -thanks for the bug report. I am working to QA that this has been fixed. I'm a little unsure how to complete step 1. of your instructions:

> 1. Change currency JPY.

Do you mean in my AdSense account? I am unable to do that, see https://support.google.com/adsense/answer/3415949?hl=en

So far I tested this by modifying the code to use "JPY" as the currency code, everything seemed to work as expected, there were no JS errors and the page displayed correctly. I was unable to test with Japanese currency numbers (not sure how AdSense returns those numbers)  so I'm not 100% certain this passes QA.

To fully test this I either need access to an AdSense account that is already set up with JPY  currency or we can set a test account to the correct currency (and ensure it has some data).

**Comment by adamsilverstein** [comment]
> So far I tested this by modifying the code to use "JPY" as the currency code

I confirmed that before the PR was merged, hard coding the currency unit as I did in my test was enough to cause the errors described in this issue. 

Based on this I have very high confidence 95+%  that this fixes the issue and am moving it over to the approval column for that reason. I don't think it is possible to do absolute confirmation of the fix without access to a new AdSense account.

cc: @felixarntz @aaemnnosttv

**Comment by torounit** [comment]
@adamsilverstein 

> To fully test this I either need access to an AdSense account that is already set up with JPY currency or we can set a test account to the correct currency (and ensure it has some data).

I think too. So need a new account for the locale.

[Current currency & funds code list](https://www.currency-iso.org/en/home/tables/table-a1.html)  may be helpful.

**Comment by marrrmarrr** [comment]
@torounit do you happen to have an active AdSense account with JPY set as currency?

**Comment by torounit** [comment]
@marrrmarrr I have JPY AdSense account.

When I tested version 1.0.5 on my site, the error no longer occurred.
