### ISSUE TITLE
Dashboard screen HTML is rendered twice

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1140]
## Bug Description

The HTML for rendering the Site Kit dashboard is being rendered twice on the page. This affects the `dashboard` and `dashboard-details` screens.

## Steps to reproduce

* Navigate to Site Kit dashboard
* View page source
* See two `[id="js-googlesitekit-dashboard"]`

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/74718473-f928c180-523a-11ea-93f3-f2df9f10d92c.png)

## Additional Context

This bug dates back to the initial release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `render` method for each `Screen` should only be called once

## Implementation Brief

* Remove the render function for the top-level parent menu item, and replace it with an empty string  
https://github.com/google/site-kit-wp/blob/dcf1bdea088846545dc699147b404b68877496ca/includes/Core/Admin/Screen.php#L129-L131 

## QA Brief

* 

## Changelog entry

* Fix double-rendered HTML markup on Site Kit dashboard screen.

**Comment by felixarntz** [comment]
IB ✅ 

Good catch!

**Comment by tofumatt** [comment]
QA ✅

Only one element on both pages:

<img width="359" alt="Screenshot 2020-02-24 19 48 54" src="https://user-images.githubusercontent.com/90871/75185879-bdac5c80-573e-11ea-819b-1e0126c53bb9.png">
<img width="409" alt="Screenshot 2020-02-24 19 48 43" src="https://user-images.githubusercontent.com/90871/75185884-bf762000-573e-11ea-852b-53522bb03261.png">

**Comment by aaemnnosttv** [comment]
You're better off testing with `document.querySelectorAll` or using an attribute selector as `jQuery` will only return the first element with an `#` selector 😄 

![image](https://user-images.githubusercontent.com/1621608/75193098-3838a480-575e-11ea-893d-ae9267429e76.png)

**Comment by tofumatt** [comment]
Hah, noted!

Still, QA ✅

Tested with `querySelectorAll` and it also just returned one element:

<img width="447" alt="Screenshot 2020-02-26 10 54 16" src="https://user-images.githubusercontent.com/90871/75338299-631e1800-5886-11ea-9bbc-37c6881427aa.png">
