### ISSUE TITLE
Fix AMP violations caused by AMP dev mode regression

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1142]
## Bug Description

#505 introduced support for AMP dev mode so that Site Kit scripts and stylesheets are not considered AMP violations by the plugin, since they are only loaded when the user is logged in anyway and should continue to work in these circumstances.

There was a regression recently (reported multiple times) by no longer using `wp_add_inline_script()` to print the `window.googlesitekit` object definition and instead relying on `WP_Scripts::add_data()` (because this is the only way to make it work as a standalone script). Since this script is standalone, we need to add back a mechanism to highlight it as compatible with AMP dev mode. We can use a `/*googlesitekit*/` comment for that like before (unfortunately modifying the rendered `script` tag is not possible).

Another issue is that the AMP plugin filter for that, `amp_dev_mode_element_xpaths`, fires rather early, but we only hook it in during `wp_enqueue_scripts` which is too late. It can be generally hooked in during `init`, there is nothing expensive in there anyway.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should not be any AMP violations flagged by the AMP plugin when the Site Kit admin bar menu is loaded.

## Implementation Brief

* Introduce `Assets::add_extra_script_amp_dev_mode()` to add `/*googlesitekit*/` comment to all 'data' scripts.
* Hook in `amp_dev_mode_element_xpaths` in top-level `Admin_Bar::register()`.
* Include `hoverintent-js` fix so that it is flagged with `data-ampdevmode`. This was added to the AMP plugin via https://github.com/ampproject/amp-wp/pull/3928, but only in the very recent 1.4.2, so I think it's worth doing that here, with a TODO to remove in the future.
* Merge #1143 

## QA Brief

* Activate AMP plugin and set to AMP standard mode.
* Go to a page in the frontend for which the Site Kit admin bar menu shows.
* Ensure the plugin does not report any validation errors, and that the menu opens as expected when hovering over it.

## Changelog entry

* Fix AMP violations when user is logged in and Site Kit admin bar menu is active.

**Comment by aaemnnosttv** [comment]
IB + CR ✅

**Comment by aaemnnosttv** [comment]
## ✅ QA

### Using AMP v1.4.0 and Site Kit 1.3.0

1. **Confirmed validation errors on home page**  
![image](https://user-images.githubusercontent.com/1621608/75171288-11fe0f00-5734-11ea-83cc-10f8a08849fe.png)
1. **Hover intent and Site Kit global data**  
![image](https://user-images.githubusercontent.com/1621608/75171377-33f79180-5734-11ea-8d79-d81e743aebc4.png)
1. ✅ Rechecking shows no validation errors using Site Kit 3b532c9797d1d5c5975f283bada4e6ba35c888e9  
![image](https://user-images.githubusercontent.com/1621608/75174687-b5055780-5739-11ea-8fad-5878e5d407bf.png)


### Using AMP v1.4.4 (current latest) and Site Kit **1.3.0**
1. **Confirmed validation errors on home page**  
![image](https://user-images.githubusercontent.com/1621608/75174154-c732c600-5738-11ea-8887-97cd0a8030cb.png)
1. **Site Kit global data only**  
![image](https://user-images.githubusercontent.com/1621608/75174210-df0a4a00-5738-11ea-8f5b-935545ac9e89.png)
1. ✅ Rechecking shows no validation errors using Site Kit 3b532c9797d1d5c5975f283bada4e6ba35c888e9  
![image](https://user-images.githubusercontent.com/1621608/75174594-89826d00-5739-11ea-9a84-8431ccdc94af.png)

✅  Menu opens as expected on hover
![image](https://user-images.githubusercontent.com/1621608/75174910-14636780-573a-11ea-8e64-b77cc558f5f6.png)

Moving to approval
