### ISSUE TITLE
Enhanced Ecommerce Tracking

### ISSUE THREAD

**Issue by tomeda** [google/site-kit-wp#1144]
I would love to se enhanced ecommerce tracking included into siteKit plugin.

**Comment by jamesozzie** [comment]
@tomeda There is an open product enhancement which you can find [here (#459)](https://github.com/google/site-kit-wp/issues/459) in relation to WooCommerce ecommerce tracking. 

If you want to suggest any additional features other than whats listed there can you add more details to this issue?

**Comment by jamesozzie** [comment]
Closing as we have #459 open
