### ISSUE TITLE
# Suggestion: Include Site Map feature

### ISSUE THREAD

**Issue by rvalins** [google/site-kit-wp#1145]
## Feature Description

Google Site kit has become a great tool for WordPress. However, It would be great if it allow users to make a site map, instead using another plugin

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Hi @rvalins 

If you are referring to XML sitemaps you might be pleased to hear that some folks (including contributors from Google) are working on bringing this functionality natively to WordPress core. Hopefully in WordPress 5.5.

You can read more about it here:

https://make.wordpress.org/core/2019/06/12/xml-sitemaps-feature-project-proposal/
https://make.wordpress.org/core/2020/01/27/feature-plugin-xml-sitemaps/

The feature plugin is currently available for testing on https://wordpress.org/plugins/core-sitemaps/

Given this effort it wouldn't make sense to to include this kind of functionality in Site Kit.

**Comment by felixarntz** [comment]
Adding site maps is out of scope for Site Kit given that WordPress core now includes them by default per the above comment.
