### ISSUE TITLE
WP Dashboard widget CTAs take up too much space

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1147]
## Bug Description

For users who don't have Analytics connected (maybe they don't use it for example), the dashboard widget has two CTAs on it to activate Analytics (more space is used by CTAs than stats!). Ideally, there shouldn't be more than one of these in the widget, and given that this is not a Site Kit screen, it's a bit distracting for these to not be dismissible.

Possible alternatives:
* Remove module CTAs from dashboard widget - inner components/sections will appear based on module activation
* Limit CTAs displayed to a single dismissible CTA

## Steps to reproduce

1. Set up Site Kit, without connecting Analytics
1. Go to WordPress dashboard
1. See 2 CTAs to setup Analytics

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/74848784-af2a0380-5340-11ea-9f30-5cb0d6f5f44d.png)

Error examples when search console isn't correctly setup:
From `/wp-admin/admin.php?page=googlesitekit-dashboard`:
<img width="1244" alt="115778007-d9bf8400-a36a-11eb-9df4-cc273e70cb32" src="https://user-images.githubusercontent.com/373931/116478972-cc573d80-a833-11eb-8cc1-8c712cd5ed44.png">

Another from `/wp-admin/index.php`
<img width="616" alt="115778176-1c815c00-a36b-11eb-98bf-92c8e055db96" src="https://user-images.githubusercontent.com/373931/116479052-e8f37580-a833-11eb-8442-b5aefa8a1e0d.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `WPDashboardWidgets` component should be updated to only show a single CTA (activation/setup/zero-data) component for each module
    * Only CTAs of the same type should be consolidated
    * This will need to be done manually like we do in the admin bar now since we do not use (and will not be using) the widgets API in this location which handles aggregating these cases automatically. Unlike the widgets API logic, this consolidation should happen regardless of the widgets being directly adjacent to one another.
* Jest component tests should be added for each of these cases

### Determine widget states
Determine whether each Analytics and Search Console widget in `components/wp-dashboard/WPDashboardWidgets.js` is in a special state or not.

- Query the Widgets store's `getWidgetState` selector for each Search Console and Analytics widget, passing the widget slug. Determine whether each widget is in a special state. See `AdminBarWidgets` component for an example:
https://github.com/google/site-kit-wp/blob/c9afd7833b942fae9b80c5f6cd65b22a5d2ee2d2/assets/js/components/adminbar/AdminBarWidgets.js#L64-L68
See the `SPECIAL_STATES` constant here for reference / comparisons. 
https://github.com/google/site-kit-wp/blob/098aa8b35be053032cb91c1c72944d6cac53913f/assets/js/googlesitekit/widgets/util/constants.js#L34-L38
- Repeat this process for the Analytics widgets

### Combine widgets if necessary 
Display only one special state CTA per module.

- If both Search Module components are in the same special state, show a single CTA in the location of the first widget. For example if both are in a `ReportZero` state, render only the first of the two components. If only one of the components is in a special state, render both.
- Similarly, if the Analytics widgets are in the same special state, show a single CTA in the location of the first widget in that state. 
   - Note that you will need to refactor / incorporate the existing logic around line 77 that currently deals with showing CTAs. 
- Pay attention to the logic around the CSS classes that are applied on line 66: currently the `.googlesitekit-wp-dashboard-stats--fourup` class is applied to improve the UI when a certain number of widgets will be rendered. This might need refactoring to take into account the new permutations involved with the Search Console widgets.

### Test Coverage

* Up to the discretion of the engineer who implements this. If the combining logic becomes nuanced and ends up getting pulled out into a separate utility (like `combine-widgets`) then tests might be a good idea. If the logic is straightforward and can be contained in the component then perhaps it is not so necessary.

### Visual Regression Changes

* Images will likely need updating to reflect these changes.

## QA Brief

There are two Search Console widgets ('Impressions' and 'Clicks') and three Analytics widgets (Visitors' and 'Average time on page' at the top and 'Popular pages'  at the bottom). 

We will need to test the following permutations:
| State | Should see |
| --- | --- |
| Analytics not active | Single Analytics 'Activate' ('Set up Analytics') CTA at the top |
| Analytics not connected | Single Analytics 'Complete setup' CTA at the top |
| Search Console has zero data | Single 'Zero data' notice ('Gathering Data') at the top |
| Analytics has zero data |  The 'Visitors' and 'Average time on page' widgets can be replaced by a single 'zero data' notice ('Gathering Data'). The 'Popular pages' widget will be combined if it too is in a zero data state |

### Setup
* Set up Site Kit as usual, but for now don't connect Analytics, just connect Search Console.
* You will also need the Developer Settings plugin, as we will be setting a custom URL.

### Search Console zero data state, Analytics inactive state
* Create a new site in Jurassic Ninja
* Connect / sign in with Site Kit to get access to it in Search Console
* Returning to your testing site, use the Developer Settings plugin to set your custom URL to the Jurassic Ninja site
* Return to the Wordpress dashboard.
* Clear your cache ('Application' tab in dev tools), and reload.
* In the Site Kit dashboard widget, you should see a single Search Console CTA reflecting the zero data state.
* You should also see a single Analytics 'activate module' ('Set up Analytics') CTA.

### Search Console working state
* Use the Developer Settings plugin to set your custom URL back to the correct site address (i.e. not the Jurassic Ninja site we created). 
* Return to the Wordpress dashboard.
* Clear your cache ('Application' tab in dev tools), and reload.
* The two Search Console widgets (impressions and clicks) should be rendered.

### Analytics active but not connected 
* Go to Site Kit settings and click the 'Connect more services' tab
* Click Analytics.
* When the loader has finished and you are prompted to select an account, click 'cancel'. Analytics should now be in an active, but unconnected state.
* Revisit the Wordpress dashboard.
* You should see a single 'Complete setup' CTA.

### Analytics active and connected state: with / without data
* Return to settings and complete the Analytics set up so that the module is active and connected.
* You will now need to test scenarios where there is data and where there is no data - you could use two Analytics accounts to do this, and toggle between them.
* If there is data to show, the 3 Analytics widgets ('Visitors', 'Average time on page' and 'Popular pages') should be rendered correctly.
* The widgets should be combined if more than one of them is in a zero data state such that there is only ever one CTA / notice. 
  * So if the two at the top ('Visitors', 'Average time on page') are empty but the one at the bottom ('Popular pages') isn't, you should see the notice at the top. 
  * If all three are empty, you should only see one notice at the top. 
  * If the bottom one is empty but the top two aren't, you should see a notice at the bottom.
  * If the bottom one AND a top one are empty, you should see the notice at the top along with the non-empty widget.

### Layout and CSS
* Remember to check for visual regressions throughout - breakpoints, loading states etc.

## Changelog entry

* Improve WordPress dashboard widget UX so that only one CTA per module is displayed when the module has no data or needs to be activated.

**Comment by aaemnnosttv** [comment]
@johnPhillips IB looks good to me overall but it's missing an estimate and the sections for tests are missing as well 😄  These should always be filled in even if none are needed, although maybe a test would be good to add for this. What do you think?

**Comment by johnPhillips** [comment]
Sorry @aaemnnosttv, I thought I'd done that 🤦‍♂️. 
Estimate added (7 felt slightly too small because there are some open ended elements here), and guidance on tests updated.

**Comment by aaemnnosttv** [comment]
Great, thanks @johnPhillips 👍 

One question:

> Establish whether the Search Console module is connected and active via the Modules store's  `isModuleConnected()` and `isModuleActive( 'analytics' )` selectors.

Is this necessary? We should only need to check `getWidgetState` since these will also depend on the active/connected state.

**Comment by johnPhillips** [comment]
Good point @aaemnnosttv, thank you - I have edited the IB to take this into account.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by johnPhillips** [comment]
@felixarntz I've got a couple of questions about the special states / combining behaviour here.

I noticed that in the description for this issue there are screenshots of Search Console showing doubled up errors. 
The current behaviour of the Widget API is not to combine erroring widgets, so just to clarify: is the intention that errors are combined here on the dashboard (i.e. to save space), or that we follow what the Widget API does? 

Also, it's my understanding that the 'activate module' and 'complete activation' states won't ever be shown for Search Console, because if Site Kit is set up then Search Console will always be active and connected. Is that correct? 
If so, would you still like me to cover the edge cases where SC is not active / connected anyway and show the appropriate (combined) CTA?

Hope that makes sense.
CC @aaemnnosttv

**Comment by felixarntz** [comment]
@johnPhillips It's correct that errors currently aren't being combined, so the errors in the screenshot are actually irrelevant in regards to the ACs. What should be combined though is any "Gathering Data", "Activate module", or "Complete module activation" CTAs that are similar.

Here is a more representative screenshot of what needs to be fixed:
<img width="507" alt="Screen Shot 2021-06-30 at 5 58 38 PM" src="https://user-images.githubusercontent.com/3531426/124049399-3c697780-d9cd-11eb-80c4-44b49f9654e6.png">

This should only end up displaying to "zero data" boxes, one for Analytics, one for Search Console. Same if only one of the two has data, the respective other module should only be represented in one box saying that it is "gathering data".

Since here the fix has to be manually accomplished (similar to the admin bar in `AdminBarWidgets`), we can ignore the (non-existent) case that Search Console is not active. We _do_ need to consider the following:
* Analytics not active.
* Analytics not connected.
* Search Console has zero data.
* Analytics has zero data.

It's basically similar to how `AdminBarWidgets` does it, only in a different layout of course, following the way the blocks are aligned in the WP dashboard widget.

**Comment by aaemnnosttv** [comment]
> Also, it's my understanding that the 'activate module' and 'complete activation' states won't ever be shown for Search Console, because if Site Kit is set up then Search Console will always be active and connected. Is that correct?
If so, would you still like me to cover the edge cases where SC is not active / connected anyway and show the appropriate (combined) CTA?

@johnPhillips I just took another look here and the SC widgets do not provide fallback components via `whenActive` which would be where the inactive or complete module activation widget states to aggregate would come from, so I think at least for now we don't need to be concerned with these two cases for SC. The only special state that SC would need aggregated is the zero-data state, where as all of them apply to Analytics.

**Comment by johnPhillips** [comment]
@felixarntz @aaemnnosttv That makes sense, thank you both! 🙏

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

_**Search Console zero data state, Analytics inactive state**_

- In the Site Kit dashboard widget, you  see a single Search Console CTA reflecting the zero data state. You see a single Analytics 'activate module' ('Set up Analytics') CTA.  -  [Screenshot](https://user-images.githubusercontent.com/73545194/127187216-7960d8ff-14cb-4f2a-9ca7-4a322afff5b5.png)

**_Search Console working state_**

- The two Search Console widgets (impressions and clicks) are  rendered.  - [Screenshot](https://user-images.githubusercontent.com/73545194/127187460-0a23478b-e65b-4b3e-8ea5-9544a598fdac.png)

_**Analytics active but not connected**_

-  see a single 'Complete setup' CTA - [Screenshot](https://user-images.githubusercontent.com/73545194/127187618-8b1a4f9a-b6c2-4207-bfe3-ced54211a2ac.png)

**_Analytics active and connected state: with / without data_**

- With data, the 3 Analytics widgets are rendered correctly - [Screenshot](https://user-images.githubusercontent.com/73545194/127188784-bc3e8839-2c0a-453f-89bc-00a83cbea1e1.png)
- The widgets are combined if more than one of them is in a zero data state such that there is only ever one CTA - [Screenshot](https://user-images.githubusercontent.com/73545194/127189001-e50aeb8b-646d-49f7-9c58-b4cffc0df6c3.png)  In addition tested different zero data states. 
- Checked the layout throughout the testing and also the rendering. 
- Checked the WP dashboard widget on our primary browsers, Chrome, Safari and Firefox etc. 
- Checked the Wp dashboard widget on small screen sizes.
