### ISSUE TITLE
Improve post-module activation notice suggestions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1148]
## Feature Description

Currently after activating a module, a success notice is displayed (as below) congratulating the user and displays the activation status of 4 specific modules:

![image](https://user-images.githubusercontent.com/1621608/74850076-33c95180-5342-11ea-9548-70306abcbc04.png)

Rather than always displaying the same 4 modules, it would be great if the displayed modules were a bit more dynamic so that activating other modules was a bit more seamless.

For example, activating Tag Manager from an initial setup is a bit of a poor experience.

1. Set up Site Kit
1. From Site Kit dashboard, click "Set up Analytics" from CTA or success notice
1. Once activated, you must navigate to the Settings page
1. Click on _Connect More Services_ tab
1. Click _Set up Tag Manager_

The last 3 actions could be a single click from the post-Analytics setup notice if Tag Manager were included there.

This issue isn't Tag Manager specific, it's just an example to demonstrate how the suggestions could be improved.

Per https://github.com/google/site-kit-wp/issues/1148#issuecomment-1012231198, this issue is now being reframed specifically to the `unifiedDashboard` feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the `serviceSetupV2` feature flag is enabled, don't show "Here are some more services you can connect" part of the success message. 
    * Just show success message "Congrats on completing setup for ...!" (+illustration) and "Ok, got it" button to dismiss (basically like in https://github.com/google/site-kit-wp/issues/1148#issuecomment-877032120)

## Implementation Brief

* When https://github.com/google/site-kit-wp/pull/4618 has been merged.
* Update `assets/js/components/notifications/BannerNotification.js` to support the `smaller` value for `format`.
	* Set `winImageCellProps` to have the following properties when the `format` is `smaller`:
		* `smSize: 4`
		* `mdSize: 2`
		* `lgSize: 2`
	* Update styles in `assets/sass/components/global/_googlesitekit-publisher-wins.scss` to have the SVG (`.googlesitekit-publisher-win__image-large`) to have the width set to `100%` when `format` is `smaller`.
* Using `assets/js/components/notifications/SetupSuccessBannerNotification.js`,
	* If `serviceSetupV2 ` feature flag  is enabled and we are testing for the `authentication_success` notification,
		* Update `BannerNotification` to use the `smaller` value for `format`.
		* Set `winData.description` to `''`
		* Do not render `ModulesList`.
	* If `serviceSetupV2` feature flag is not enabled, existing functionality should remain.
* Add stories for `SetupSuccessBannerNotification`

### Test Coverage
* No new tests to be added.

## QA Brief

* Enable the `serviceSetupV2` feature flag.
* Connect Site Kit and verify the notification banner displays according to the AC.
* Setup a module and verify the notification banner displays according to the AC.
  * The PageSpeed Insights and Idea Hub modules have extra text so it's worth checking these as well as one or more other modules. Enable the `ideaHubModule` feature flag in order to setup Idea Hub.
* Disable the `serviceSetupV2` and perform a regression test on the above steps.
* Verify the new Storybook stories for the `SetupSuccessBannerNotification` component, they are under `Components -> SetupSuccessBannerNotification`:
![image](https://user-images.githubusercontent.com/18395600/154298981-8c90b7aa-37ba-496d-ab47-c1a32a957405.png)
  * Storybook for `develop` branch: https://google.github.io/site-kit-wp/storybook/develop/

### Update:

When reviewing this again, please see [this comment](https://github.com/google/site-kit-wp/issues/1148#issuecomment-1050166477) below for details of the tweaks that have been made to the notifications.

## Changelog entry

* Simplify success banner notification for the unified dashboard.

**Comment by jamesozzie** [comment]
If a user connects SC, Analytics, AdSense and PageSpeed Insights in particular the below text could be improved, or alternatively display the only remaining module, Optimize:
_Here are some other services you can connect to see even more stats:_

![EjrgYopeoLX png (3304×1260)](https://user-images.githubusercontent.com/41326532/77439915-8e414c00-6ddf-11ea-97a2-706c20c6ff13.png)

**Comment by aaemnnosttv** [comment]
> If a user connects SC, Analytics, AdSense and PageSpeed Insights in particular the below text could be improved, or alternatively display the only remaining module, Optimize

Don't forget Tag Manager 😄

**Comment by marrrmarrr** [comment]
Three considerations here:
- We're revising this entire UXD flow in the new dashboard redesign;
- Users tend to treat these messages not as recommendations, but as "must do next and get all the green checkmarks";
- GTM and Optimize are for slightly more advanced users (who want to do experiments etc) and don't offer any functionality that can be accessed via the Site Kit dashboard.  

Based on all this, I think the most efficient thing we can do here is to make sure we don't show the "here are some other services you can connect..." sentence if everything else has been connected already. 

@felixarntz if the user connected GTM and SC, GA, PSI have already been connected, can we simply show a message that says "Congrats on completing the setup for Tag Manager!" and skips the bottom part?

**Comment by felixarntz** [comment]
@marrrmarrr Yes, for now let's improve this in a limited way as follows: If all of the 4 flagship modules are already active, don't show the list of modules here, as it's pointless then.

**Comment by felixarntz** [comment]
I've updated the ACs here to cover all relevant cases. Basically, if all 4 modules we usually show there are already active, there's no point to show them as modules to potentially activate. This is not only relevant potentially after GTM, it could also apply to Optimize, or any of the other modules that you activate _last_.

**Comment by danielgent** [comment]
![design-changes](https://user-images.githubusercontent.com/8496063/117285819-ba475180-ae68-11eb-85a9-108399806871.png)

Just putting this here to check everyone is ok with the whitespace :+1:

**Comment by felixarntz** [comment]
@marrrmarrr What do you think about the above? If all of the 4 primary modules are already active, we decided to not display them here, but now there's extra white-space. Should the side kick on the right be smaller instead?

**Comment by danielgent** [comment]
I put a 3 as I already tried this out while doing the IB. It's just styling changes, no test changes required

**Comment by felixarntz** [comment]
@danielgent Regarding your question in https://github.com/google/site-kit-wp/issues/1148#issuecomment-833425118, can we _for this particular situation_ (that there are no module boxes in the notification) display the creature on the right a bit smaller, so that it doesn't unnecessarily increase the height? If that works, let's do it.

**Comment by danielgent** [comment]
![smaller-image](https://user-images.githubusercontent.com/8496063/125052719-912f8100-e0a4-11eb-875e-b67068307e4b.png)

I've changed the image to be smaller when there are no module boxes in the notification

I've created a PR here, so this is ready for IBR https://github.com/google/site-kit-wp/pull/3690 but as it's outside the current sprint and not a priority I won't assign it back to Felix now

**Comment by felixarntz** [comment]
@danielgent Thanks for your work on this. I would say the IB is good to go, but I actually think it isn't really worth increasing code complexity and spending our time (even a little bit) on this, given that the "Generic Dashboard V1" epic will completely remove/overhaul these notifications.

I'll close this as `wontfix` for now, since very soon it'll be `invalid`. cc @aaemnnosttv

**Comment by felixarntz** [comment]
Reopening this after a conversation with @marrrmarrr, since the original reason for closing is no longer the case. We don't need to touch this for the current version of the dashboard, but we've decided that for the `unifiedDashboard` the section with the module boxes should be entirely removed, so that the success message is always just the main headline, text, button and sidekick graphic. The visuals can be heavily based on what was already implemented in #3690.

I'll redefine the ACs here accordingly.

**Comment by marrrmarrr** [comment]
Thanks @felixarntz! To confirm, there will still be zero-state widgets within the dashboard itself encouraging people to connect GA, right? 
Before service setup redesign is rolled out, there might still be a bunch of people who don't set up GA right away, so perhaps it might make sense to keep the boxes around until Service Setup redesign is launched and for now remove the "here are some more services" sentence + boxes for the case where everything is connected?

**Comment by asvinb** [comment]
@felixarntz Looks like we have an error in the AC. It says:
> If the `serviceSetupV2` feature flag is enabled

Shouldn't that be the `unifiedDashboard` feature flag? I've added the IB based on this assumption.

**Comment by felixarntz** [comment]
@asvinb No, this issue isn't part of the unified dashboard epic. We only want to remove these boxes for when the `serviceSetupV2` epic is rolled out, since that includes the ability to set up Analytics from the start, at which point these boxes will be even less relevant (in many cases they would only have AdSense left to activate).

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@techanvil @felixarntz I have a few observations:

- I feel the alignment of the text and graphic could be improved. Right now, the graphic looks lost and is aligned to the far right. On the current notices, it is centre aligned. I'm also wondering if the text should be more aligned with the graphic.
- On mobile the graphic is much larger. it's 361x361 pixels, compared with 200x200 pixels currently. 
- The useful information on some of the notices are no longer appearing:
For Optimize the message  `To set up experiments and see the results, go to [Optimize]`
For Analytics the message `You’ll only see Universal Analytics data for now. [Learn more]`

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/153874171-b1b15381-45f0-424e-9127-c5bf1b25317f.png)
![image](https://user-images.githubusercontent.com/73545194/153874191-32ebb15f-9979-492b-8ffe-bdde1408cbad.png)
![image](https://user-images.githubusercontent.com/73545194/153878645-407deee8-8172-444b-bf6c-72ea4b5a7b88.png)

</details>

**Comment by techanvil** [comment]
> ### QA Update: 
> @techanvil @felixarntz I have a few observations:
> 
> * I feel the alignment of the text and graphic could be improved. Right now, the graphic looks lost and is aligned to the far right. On the current notices, it is centre aligned. I'm also wondering if the text should be more aligned with the graphic.
> * On mobile the graphic is much larger. it's 361x361 pixels, compared with 200x200 pixels currently.
> * The useful information on some of the notices are no longer appearing:
>   For Optimize the message  `To set up experiments and see the results, go to [Optimize]`
>   For Analytics the message `You’ll only see Universal Analytics data for now. [Learn more]`

Hi @wpdarren, thanks for the observations.

In terms of the implementation, this is just a result of following the IB.

The AC is a little sparse so it looks like the IB has been written with a bit of artistic licence.

@felixarntz, could we get a steer on this please? The new V2 version of these notifications can be seen here - https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-setupsuccessbannernotification--site-v-2

**Comment by aaemnnosttv** [comment]
@techanvil @wpdarren there was a comment about this from a while back but looks like it didn't make it into the revised ACs: https://github.com/google/site-kit-wp/issues/1148#issuecomment-858775482

This requires limiting the graphic to a height of 69px to accomplish which looks a bit odd on desktop as it is off to the side.

![image](https://user-images.githubusercontent.com/1621608/154026527-a2e1bd5d-f6a1-4adb-bde5-5efdcf656dee.png)

It looks a bit more reasonable on mobile but also feels to be inefficient with the vertical space.

![image](https://user-images.githubusercontent.com/1621608/154026851-5c830bb1-d6aa-4a64-907f-fe401d6f1fb8.png)

> * The useful information on some of the notices are no longer appearing:
>   For Optimize the message  `To set up experiments and see the results, go to [Optimize]`
>   For Analytics the message `You’ll only see Universal Analytics data for now. [Learn more]`

My interpretation here is that this should be preserved and that the IB called for it to be cleared when it shouldn't have been.

**Let's open a follow-up PR to do the following (under the same conditions):**
* Limit the height of `.googlesitekit-publisher-win__image-smaller` to 69px
* Restore the notification's description (e.g. "You’ll only see Universal Analytics data for now")

We can then iterate on this in CR (if needed) or in a follow-up issue if there are more substantial changes to be made. cc: @felixarntz @marrrmarrr

**Comment by aaemnnosttv** [comment]
Thanks @techanvil ! @wpdarren @mohitwp this is ready for another pass 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified :

- Enabled the `serviceSetupV2` feature flag
- Connected Site Kit and verified the notification banner displays according to the AC.
- Verified notifications for all modules Analytics, PSI, Optimize, Tags, Adsense. 
- Verified all stories of Storybook.
- Verified in Safari, Chrome, Firefox and Edge latest versions.
- Verified in mobile devices iPhone, iPad, Android mobile.
- Verified when `serviceSetupV2` feature flag is not enabled.
- Verified that notification appears as per https://github.com/google/site-kit-wp/issues/1148#issuecomment-858775482
- Verified that height of `.googlesitekit-publisher-win__image-smaller` is 69px and width is set to 100% as per IB.

<screenshots>

![NewAnalytics](https://user-images.githubusercontent.com/94359491/154438839-434360c6-d4de-4126-9943-d7e9e1268ce1.png)

![IdeaHub](https://user-images.githubusercontent.com/94359491/154438161-6837bdfe-9fee-48b0-99b1-153110016a8b.png)
![I-padService](https://user-images.githubusercontent.com/94359491/154438163-637ef668-3905-418f-8661-195d3a574667.png)
![Optimize](https://user-images.githubusercontent.com/94359491/154438166-c384e606-da60-47b8-9fed-54a13c5920af.png)
![PSI](https://user-images.githubusercontent.com/94359491/154438167-fac4254b-51ea-41bb-b1fa-24f37b20b994.png)
![SerSetupMobile](https://user-images.githubusercontent.com/94359491/154438169-f4cb62e8-bc2b-4f03-9d80-a9ddf8442b12.png)
![SerSetupMobile2](https://user-images.githubusercontent.com/94359491/154438172-1e74b336-04c9-4e08-995e-a2577786fe41.png)
![TagManager](https://user-images.githubusercontent.com/94359491/154438174-ec296394-7c13-478d-8d6d-53959afe96ac.png)



</screenshots>

**Comment by felixarntz** [comment]
### Approval ⚠️ 

The implementation here satisfies the ACs all correctly, however after review with @marrrmarrr we'd like to request one additional change that should be small enough but worth it for a slightly improved experience:

* Right now there is no text content between the notification heading and the "Ok, got it" button, which looks strange, so let's add something.
* Any version of this notification that **does not already** have its custom text content there below the heading (i.e. the `winData.description`, `winData.learnMore.label` _and_ `anchor.label` are all empty, and **only with `serviceSetupV2` flag enabled**) should still show the following "fallback" text description:
    * Description: _Connect more services to see more stats._
    * Learn more label: _Go to Settings_
    * Learn more URL: `select( CORE_SITE ).getAdminURL( 'googlesitekit-settings' )`, with `#/connect-more-services` appended to it so that it links to that tab in Site Kit > Settings
    * This learn more link goes to the current site, so it shouldn't be marked as external link or open in a new window/tab. We currently don't support this in the `BannerNotification` component, however adding support for that should be simple:
        * Add an optional prop `learnMoreTarget` to the `BannerNotification` component, which by default is `external`.
        * Only add the `external` prop to the "learn more" `Link` if the `learnMoreTarget` prop is set to `external`.
        * Then use the prop by passing it to `BannerNotification` just in this one instance above, setting it to `internal` so that that link opens in the same window/tab.

I realize this is a bit of extra work here, but it should be straightforward enough to tackle it in time for Monday's release. @techanvil Does the above make sense to you? Would you be able to pick this up tomorrow? In case you have any concerns, don't hesitate pinging me so that we can sort this out sooner than later.

**Comment by techanvil** [comment]
> The implementation here satisfies the ACs all correctly, however after review with @marrrmarrr we'd like to request one additional change that should be small enough but worth it for a slightly improved experience:
> 
> :scissors: snip
> 
> I realize this is a bit of extra work here, but it should be straightforward enough to tackle it in time for Monday's release. @techanvil Does the above make sense to you? Would you be able to pick this up tomorrow? In case you have any concerns, don't hesitate pinging me so that we can sort this out sooner than later. Also feel free to assign to me for CR.

Hi @felixarntz, that's no problem at all. I've created a PR for this, #4891. The only thing I should mention is that I am OoO this afternoon, so if any changes are needed during this period someone else will need to pick them up.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Enabled the serviceSetupV2 feature flag

- Verified that the new description, learn more link and URL appear on notifications without a description, i.e. Tag Manager and Search Console. URL is `/wp-admin/admin.php?page=googlesitekit-settings#/connect-more-services`
- Verified notifications for all modules Analytics, PSI, Optimize, Tags, Adsense. appear as per the AC. 
- Verified on desktop and mobile. 

Disabled the serviceSetupV2 feature flag

- Verified that the new notification does not appear but current notifications continue to be displayed. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/155735283-8db1f059-042d-49a5-b732-0d113e24d617.png)
![image](https://user-images.githubusercontent.com/73545194/155735298-fe5c107c-fd6d-4eaf-95be-b91626b3e31c.png)
![image](https://user-images.githubusercontent.com/73545194/155735323-fe7a4402-e2bd-4b45-aa61-c2f3337c0314.png)

</details>

**Comment by felixarntz** [comment]
Excellent, thank you for the quick updates @techanvil @tofumatt @wpdarren! This is good to go now.
