### ISSUE TITLE
Dashboard error v1.3.0: Must call google.charts.load before google.charts.setOnLoadCallback

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1155]
## Bug Description

Some users are encountering the below dashboard error after Site Kit setup. This appears in their primary Site Kit dashboard, and started to occur with v.1.3.0 of the plugin. 

![image](https://user-images.githubusercontent.com/41326532/75466338-f25c2600-5981-11ea-8d8a-2423e1bca962.png)

```
Must call google.charts.load before google.charts.setOnLoadCallback

in n in div in n in m in div in div in div in div in n in div in n in Unknown in Unknown in Unknown in Unknown in WithFilters(t) in n in n in div in div in div in div in n in a
```

Console error:
```
JQMIGRATE: Migrate is installed, version 1.4.1
admin.php?notification=authentication_success&page=googlesitekit-dashboard:2121 Mixed Content: The page at ‘https://www.[hidden].com/wp-admin/admin.php?notification=authentication_success&page=googlesitekit-dashboard&#8217; was loaded over HTTPS, but requested an insecure stylesheet ‘http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/smoothness/jquery-ui.css?ver=5.3.2&#8217;. This request has been blocked; the content must be served over HTTPS.
2googlesitekit-dashboard.js?ver=1.3.1:12 Error: Must call google.charts.load before google.charts.setOnLoadCallback
at Object.google.v.w.H.lo [as setOnLoadCallback] (loader.js?ver=5.3.2:317)
at new n (googlesitekit-dashboard.js?ver=1.3.1:3)
at Io (googlesitekit-dashboard.js?ver=1.3.1:12)
at Zr (googlesitekit-dashboard.js?ver=1.3.1:12)
at Is (googlesitekit-dashboard.js?ver=1.3.1:12)
at Ac (googlesitekit-dashboard.js?ver=1.3.1:12)
at Tc (googlesitekit-dashboard.js?ver=1.3.1:12)
at kc (googlesitekit-dashboard.js?ver=1.3.1:12)
at googlesitekit-dashboard.js?ver=1.3.1:12
at t.unstable_runWithPriority (googlesitekit-dashboard.js?ver=1.3.1:12)
gs @ googlesitekit-dashboard.js?ver=1.3.1:12
admin.php?notification=authentication_success&page=googlesitekit-dashboard:1 Mixed Content: The page at ‘https://www.[hidden].com/wp-admin/admin.php?notification=authentication_success&page=googlesitekit-dashboard&#8217; was loaded over HTTPS, but requested an insecure stylesheet ‘http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/smoothness/jquery-ui.css?ver=5.3.2&#8217;. This request has been blocked; the content must be served over HTTPS.
```

Users encountering this issue:
- [https://wordpress.org/support/topic/must-call-google-charts-load-before-google-charts-setonloadcallback/](https://wordpress.org/support/topic/must-call-google-charts-load-before-google-charts-setonloadcallback/) - RESOLVED
- [https://wordpress.org/support/topic/must-call-google-charts-load-before-google-charts-setonloadcallback-error](https://wordpress.org/support/topic/must-call-google-charts-load-before-google-charts-setonloadcallback-error)
- [https://wordpress.org/support/topic/must-call-google-charts-load-before-google-charts-setonloadcallback-problem/#post-12456770](https://wordpress.org/support/topic/must-call-google-charts-load-before-google-charts-setonloadcallback-problem/#post-12456770) - RESOLVED
- [https://wordpress.org/support/topic/error-when-trying-to-load-dashboard/](https://wordpress.org/support/topic/error-when-trying-to-load-dashboard/) - RESOLVED
- [https://wordpress.org/support/topic/error-on-dashboard-only-adsense-not-effected/](https://wordpress.org/support/topic/error-on-dashboard-only-adsense-not-effected/)

Trying to replicate on new domains at present. 

## Expected Behaviour

Dashboards should display as expected. 

## Additional context

 - Plugin version: 1.3.0
- Occurs for new Site Kit users (awaiting information on whether this occurs for existing users upon upgrade)
- Started occurring since Site Kit v1.3.0
- No issues with site details (matching URLs)
- Reported sites, 2 https (with redirection), 1 http. 
- Occurs just with the Search Console module active
- Users have already tried resetting, reinstalling from browser incognito and clearing cache.
- Doesn't seem to impact other module setup, awaiting confirmation

Reported sites - from WP support topics:
- [https://internetgaminginfo.com/](https://internetgaminginfo.com/)
- [revistatecnologia360.com.br](http://revistatecnologia360.com.br/)
- [https://allinone-accounting.com/](https://allinone-accounting.com/)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No errors should be raised by the Google charting library if loaded by another plugin

## Implementation brief

The problem is that `google.charts.load` was only being called when we were loading the charting library. If it was already present, we were setting the `onLoadCallback` but not calling the load function.
* Ensure `google.charts.load` is always called regardless of whether or not `google.charts` is already loaded or if we need to load it asynchronously.
* Merge #1200

## QA testing instructions

* Disable all other plugins except Site Kit (and dev settings if needed)
* Set up Site Kit, and the Analytics module
* Ensure no errors are raised when viewing the the Site Kit dashboard and Analytics module dashboards
* Install and activate the [Google Analytics](https://wordpress.org/plugins/googleanalytics/) plugin (no configuration necessary)
* Ensure no errors are raised when viewing the the Site Kit dashboard and Analytics module dashboards

## Demo

* 

## Changelog entry

* Fix compatibility error where `google.charts.load` was not called before `google.charts.setOnLoadCallback`.

**Comment by jamesozzie** [comment]
Possible conflict with [GoogleAnalytics](https://wordpress.org/plugins/googleanalytics/) plugin as reported by some users. Requires further testing.

**Comment by jamesozzie** [comment]
To replicate install the [Google Analytics plugin](https://wordpress.org/plugins/googleanalytics/) after setting up and installing Site Kit. 

![image](https://user-images.githubusercontent.com/41326532/75467473-9d211400-5983-11ea-83fc-cc091f889ba4.png)

**Comment by aaemnnosttv** [comment]
Confirmed error is raised on Site Kit dashboard when `googleanalytics` plugin is installed and active.

![image](https://user-images.githubusercontent.com/1621608/75773358-69186b00-5d56-11ea-9119-f79aaaf9fa1b.png)

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed latest develop and setup Analytics module after disabling all plugins.
![image](https://user-images.githubusercontent.com/57115907/76283793-d184b200-6258-11ea-92e9-f2065fe32936.png)

![image](https://user-images.githubusercontent.com/57115907/76283763-bdd94b80-6258-11ea-8559-38ec68c58ee7.png)

Installed and activated Google Analytics Plugin
![image](https://user-images.githubusercontent.com/57115907/76283847-f2e59e00-6258-11ea-8b5f-9083243991c4.png)

Confirmed Dashboard is looking good. 
![image](https://user-images.githubusercontent.com/57115907/76283875-0264e700-6259-11ea-835b-b361ed5165d2.png)

Checked Analytics functionality
![image](https://user-images.githubusercontent.com/57115907/76283914-19a3d480-6259-11ea-999a-6bde2590172b.png)

Checked settings
![image](https://user-images.githubusercontent.com/57115907/76283972-3d671a80-6259-11ea-8ebe-332b6e1c2347.png)

All good on my end!

Passed QA ✅

**Comment by marrrmarrr** [comment]
LGTM

**Comment by Sandraf199889** [comment]
Muito Bem isso [Ficou](resenhaonline.com.br) explicado me ajudou
