### ISSUE TITLE
Dead code in OAuth client token callback

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1158]
## Bug Description

The following code is never executed because `$client` will never be set in the context.

https://github.com/google/site-kit-wp/blob/ddcd425db69ec84e2d888cebfdee3ab10b92fc72/includes/Core/Authentication/Clients/OAuth_Client.php#L272-L278

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `$client` instance should be made available to the set token callback

## Implementation Brief

* Add a `use ( $client )` to the closure so that the instance is always available
[Previously](https://github.com/google/site-kit-wp/commit/40e3e4e03afdf1e1d08c103edbd1320777955b88#diff-48c8b1490a8befd13ca3a60d4be2b7fcR249-R250) `$client` was `$this->google_client` which wasn't guaranteed to be set, hence the check and the source of the bug.

## QA Brief

* 

## Changelog entry

* Fix minor bug causing potentially incorrect token expiry to be recorded.

**Comment by tofumatt** [comment]
Refresh tokens are set and refreshed as expected, and the code looks good. So I think this is QA ✅
