### ISSUE TITLE
Fix outdated and slightly incorrect AMP client ID usage

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1160]
## Bug Description

There are currently two issues with how we are tracking AMP traffic with Analytics:
1. We are using an outdated mechanism (specify `useAmpClientId` option in non-AMP GA snippet and render `amp-google-client-id-api` meta tag in AMP version). This has actually been out of date since late 2018 and is superseded by using the "AMP linker" (see https://support.google.com/analytics/answer/7486764 and https://developers.google.com/gtagjs/devguide/amp).
2. We only use AMP client ID when the site is using secondary AMP (and only if the user enables the toggle). However, AMP client ID / AMP linker is just as useful to track traffic from an AMP cache to the origin AMP content, so this should be enabled in primary AMP too. There is no good reason to not use AMP linker, so we should remove the toggle entirely (also better for UX anyway, since this is hard to understand).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Remove functionality that renders `amp-google-client-id-api` meta tag in AMP content.
* Remove functionality that sets `useAmpClientId` in the GA snippet (non-AMP).
* Remove Analytics sub-setting `ampClientIDOptIn` entirely, including its option in the UI.
* If AMP is generally enabled, unconditionally include AMP linker configuration in non-AMP `gtag` snippet via `gtag('set', 'linker', {'domains': ['wp-site-domain.com']});` (see https://developers.google.com/gtagjs/devguide/linker#basic_setup).
    * Because this property has to be set via `gtag('set', ...)` instead of being provided via `gtag('config', <TRACKINGID>, ...)`, it would typically not be filterable. However, it should be filterable, and the fact that this should be provided separately is an implementation detail. Therefore, `linker` should become part of the filtered `$gtag_opt` array variable. After running the filter, if `linker` is set it should be extracted out and set via `gtag('set', ...)`. The rest would then go through config as usual.
* Unconditionally include AMP linker configuration in `amp-analytics` options for `gtag` via `"linker": { "domains": ["wp-site-domain.com"] }` (see https://developers.google.com/gtagjs/devguide/amp#link_domains).
    * Because the entire `amp-analytics` configuration is filterable, we're good here.

## Implementation Brief

* Remove `Analytics::print_amp_client_id_optin()` and its action.
* Introduce private helper `Analytics::get_home_domain()` that uses `wp_parse_url( home_url(), PHP_URL_HOST )`.
* In `Analytics::enqueue_gtag_js()`:
    * Remove the logic relevant for setting `useAmpClientId`.
    * Include a `linker` key in `$gtag_opt` with an associative array that has `domains` with an array with the single value of `Analytics::get_home_domain()`.
    * Move the first `wp_add_inline_script()` call down to right after running the `googlesitekit_gtag_opt` filter.
    * After running the `googlesitekit_gtag_opt` filter, check if `$gtag_opt['linker']` is set, and if so take it out, modify the inline script by adding `gtag('set', 'linker', <JSON_encoded_value>)` and unset `$gtag_opt['linker']`.
* In `Analytics::print_amp_gtag()`:
    * In the same associative array where right now there's `groups`, include a `linker` key with an associative array that has `domains` with an array with the single value of `Analytics::get_home_domain()`.
* In `Optimize::print_amp_optimize_experiment()` and `Optimize::amp_data_load_experiment_component()`:
    * Remove check for `amp-client-id-opt-in`.
* Remove `amp-client-id-opt-in` datapoint in `Analytics`.
* Remove `ampClientIDOptIn` sub-setting from `Analytics\Settings`.
* Remove `amp-client-id-opt-in` datapoint in `Optimize`.
* Remove `ampClientIDOptIn` from `Optimize::prepare_info_for_js()`.
* In `js/modules/analytics/setup.js`: Remove all references to `ampClientIDOptIn` completely, including the toggle and its description.
* In `js/modules/optimize/setup.js`: Remove all references to `ampClientIDOptIn` completely, and output the AMP experiment snippet only based on whether AMP is enabled or not.

## QA Brief

* 

## Changelog entry

* Replace outdated AMP client ID mechanism for tracking AMP traffic with recommended AMP linker approach, and enable it by default.

**Comment by aaemnnosttv** [comment]
This looks good for the most part, just a few questions. Do you want to add an estimate as well?

> Unconditionally include AMP linker configuration in non-AMP gtag snippet

Even if the site isn't using AMP at all?

> However, it should be filterable, and the fact that this should be provided separately is an implementation detail. Therefore, linker should become part of the filtered $gtag_opt array variable. After running the filter, if linker is set it should be extracted out and set via gtag('set', ...). The rest would then go through config as usual.

Why not give it a dedicated filter rather than pass it through via options when it isn't an option?

**Comment by felixarntz** [comment]
@aaemnnosttv 
> This looks good for the most part, just a few questions. Do you want to add an estimate as well?
> 
> > Unconditionally include AMP linker configuration in non-AMP gtag snippet
> 
> Even if the site isn't using AMP at all?

Oh yeah, I meant it that way, unconditionally if AMP :)

> > However, it should be filterable, and the fact that this should be provided separately is an implementation detail. Therefore, linker should become part of the filtered $gtag_opt array variable. After running the filter, if linker is set it should be extracted out and set via gtag('set', ...). The rest would then go through config as usual.
> 
> Why not give it a dedicated filter rather than pass it through via options when it isn't an option?

Hmm I feel like that's overly verbose. I'm not sure why this is implemented in a different way than some of the other config options, but the way I see it this is just as much a config option as the other ones.

**Comment by aaemnnosttv** [comment]
>  I'm not sure why this is implemented in a different way than some of the other config options, but the way I see it this is just as much a config option as the other ones.

I agree, but the fact that it is separate leads me to think that it should be also separate from the config for consistency. The fact that it's more verbose is more of an edge case I think as users shouldn't really need to filter this so that would be an edge case.  Either way, I don't think this detail is blocking here but I would also be interested to know why it's implemented as such and not as an option.

IB ✅ 

Would you like to add an estimate as well?

**Comment by felixarntz** [comment]
@aaemnnosttv In AMP it's also with the other information, hence I wanted to avoid introducing a separate filter just for that. Let's go with that approach for now, if there's a need for something similar, we can explore further.

Added an estimate.

**Comment by tofumatt** [comment]
The only thing to note here is that the ["Learn more" link](https://github.com/google/site-kit-wp/pull/1203/files#diff-74bda441ac699b6ba3c20413cd45f751R248) is not very accessible to a screenreader, but aside from that this works as-intended and the code looks good.

QA ✅

**Comment by westonruter** [comment]
Follow up: #2010
