### ISSUE TITLE
Remove unused "above_app" actions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1164]
## Feature Description

Each app screen currently fires a `googlesitekit_above_*_app` action above its render target element.

E.g.
https://github.com/google/site-kit-wp/blob/a5a20609d8d6491a963f13ebf232bc471d5692b6/includes/Core/Admin/Screens.php#L240-L247

These are unused and should be removed if we have no plans to use them in the future.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No PHP actions `googlesitekit_above_*_app` should be fired.

## Implementation Brief

* Remove all `googlesitekit_above_*_app` hooks in PHP.

## QA Brief

* Search for `googlesitekit_above_` in `includes/*`
* Ensure no `googlesitekit_above_*_app` do_action-s remain

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Makes sense. This is so basic that I just waved it through :)

**Comment by tofumatt** [comment]
All hooks removed, QA ✅ from me.
