### ISSUE TITLE
Site Kit Will Not Activate

### ISSUE THREAD

**Issue by tristanhemsley** [google/site-kit-wp#1165]
## Bug Description

Hi. I have just bought a site and had Site Kit installed and it was connected and working, but I needed to change the tag for my GA account ID as the plugin would not link to it and kept linking to the previous owner’s GA. I deactivated and deleted the plugin and have installed it (through Add New and also downloading and uploading it) and tried to activate it, but there is a blue line moving across the screen on a loop and nothing else happens. The Dashboard button brings up a blank screen. I have tried clearing the site cache and the browser cache and re-installing the plugin in an incognito window on Chrome and Firefox, but the same issue keeps happening. The only error message in the console ‘Failed to load resource: the server responded with a status of 403 ()’ for Chrome.

## Steps to reproduce

N/A

## Screenshots

![1](https://user-images.githubusercontent.com/48993069/75123557-65bf1880-56a0-11ea-867f-a4df7f20a89e.JPG)
![2](https://user-images.githubusercontent.com/48993069/75123558-66f04580-56a0-11ea-8e42-90028f275ef0.JPG)

## Additional Context

 - PHP Version:  
 - Browser [e.g. chrome, safari] Chrome, Firefox, Edge
 - Plugin Version [e.g. 22] 1.3.1
 - Device: [e.g. iPhone6] Laptop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@tristanhemsley I'll close this while we work on your [support topic](https://wordpress.org/support/topic/site-kit-will-not-activate/) in the WordPress support forum.

**Comment by tristanhemsley** [comment]
Okay, thanks
