### ISSUE TITLE
Redirecting issue

### ISSUE THREAD

**Issue by SupraFan** [google/site-kit-wp#117]
I have an issue with the setup... when i will do the second step, it always redirects me to the "My Profile" site and leaves the google app and never finished the second step... what can i do?

**Comment by jamesozzie** [comment]
@SupraFan Thanks for reporting this issue. To confirm, this is at the "Authenticate" stage? Would you be able to share screenshots or a video of the error? We will need some more context to be able to troubleshoot. 

Also please try resetting Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit). If you are not able to reach that section try deleting the Site Kit plugin before opening a new incognito window in your browser and starting the process of installing and activating again. Maybe also deactivate any firewall or adblocker you might have enabled, even temporarily during the setup stage.

Let us know if the same issue arises again, and if so please some additional information.

**Comment by SupraFan** [comment]
http://service-finden.de/Media/issue.mp4

**Comment by SupraFan** [comment]
here is a little clip i made about my problem with the site kit.... hope you can help me

**Comment by jamesozzie** [comment]
@SupraFan Thanks for the video clip. I see you are using the Brave browser. Can you try to setup Site Kit in an alternate browser and see if the same problem arises?

**Comment by SupraFan** [comment]
no, the same issue with a brand new install of firefox and chrome.... :(

**Comment by jamesozzie** [comment]
@SupraFan Thanks for checking. We will need to troubleshoot further, do you mind deactivating the social login plugin also (temporarily) while you start the process again, after resetting Site Kit? Please then share any console errors (Using Dev Tools with a Chrome browser). We might need to check your network logs ago but please try again. 

Also a couple of other things to check before installing:
- WordPress Address & Site Address (Settings > General): Please ensure you have the correct and same URL in both (including http://)
- Disable any Firewall or AdBlocking software while setting up

Let me know after you try again.

**Comment by andizer** [comment]
I encountered the same problem and after spending a couple of hours on debugging I found out that my theme was catching the 'code' from the url by accessing `$_GET`. In my case it was my own theme, but I guess another plugin it watching the `$_GET` and redirecting before sitekit gets the chance.

**Comment by jamesozzie** [comment]
@andizer Thanks for the input, very useful. Can you let me know what theme you are using?

**Comment by andizer** [comment]
It was a theme developed by myself and only used by me. It also contains some social features like the issuer has. Ik hope this is useful.

**Comment by cejayassoc** [comment]
I had a similar issue. I could not complete step 2. After allowing all the requested authorizations, the page would not redirect. I disabled all my plugins (except Site Kit) and tried again.  I was able to complete the authorization with all plugins disabled.

**Comment by jamesozzie** [comment]
@cejayassoc Thanks for the info. Would you be able to let me know what plugins you are using?

**Comment by hablaviajero** [comment]
> nd tried again

I made this , i have backpacker traveler theme but I deactivate it with all the plugins, and nothing happend. I used another explorer like safari or opera but anything happend, please help me

**Comment by hablaviajero** [comment]
> here is a little clip i made about my problem with the site kit.... hope you can help me

How did you solve it? Can u' help me

**Comment by jamesozzie** [comment]
@hablaviajero Can you perform the following steps and see if the same issue occurs ?
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate your other active WordPress plugins 
3. Temporarily activate an alternative theme
4. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png) as opposed to a different browser

If the above fails to resolve the issue please inform me of the following:
- Web Host Environment
- Console Errors
- PHP Errors 
- Any Firewall or security software on your web host (ie. ModSecurity)

**Comment by cejayassoc** [comment]
> @cejayassoc Thanks for the info. Would you be able to let me know what plugins you are using?

Here is the list of plugins we are using:
Divi Theme
404page by Peter Raschendorfer
Content Views by Content Views
Formidable Forms & Formidable Forms Pro by Strategy11
GoDaddy Pro Sites Worker by Godaddy
iThemes Security by iThemes
Media Library Assistant by David Lingren
PrivateDaddy by Nadav Elyada
Quotes Collection by Srini G
Smar Slider 3 by Nextend
UpdraftPlus (free version) by UpdraftPlus.com

**Comment by jamesozzie** [comment]
@cejayassoc 2. In your iThemes security plugin can you uncheck [this](https://i.imgur.com/7OyyYyI.png) option from the general settings

@SupraFan Do you also have ithemes security?

**Comment by enusdigital** [comment]
I have tried everything and nothing seemed to work, the last thing I tried was disabling mod_security and it worked like a charm.

I use Divi theme also but it was fairly easy for me to diable mod_security since  recently migrated to a cPanel based server.

**Comment by jamesozzie** [comment]
Closing with no response from original user
