### ISSUE TITLE
Introduce notification functionality to core/site store

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1174]
This is a follow-up to #999 and #1110 (also related #1000 and #1173).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/site` store should have an additional selector `getNotifications`:
    * The selector should issue an API request to `core/site/data/notifications` to get a list of notification objects.
        * See #1110 / #1170 for typical properties to expect on notifications (probably doesn't matter much for implementation of this, but fyi).
    * The selector should however also support notifications added by JS (i.e. when receiving the server response, it shouldn't override the JS-added notifications, but only the ones previously received from server).
* The `core/site` store should have actions `addNotification( notification )` and `removeNotification( id )`:
    * Both of these should only work client-side for now, i.e. simply modify the JS-based notifications array.
    * All `notification` objects must include `id`, so that they can be removed using that.

## Implementation Brief

In a new `googlesitekit/datastore/site/notifications.js`:
* Use `createNotificationsStore` from #1205 with parameters `core`, `site`, `notifications` to generate the notifications store object needed and export it.
* Export `INITIAL_STATE` from that file as well (the initial state of just the notifications part).

In `googlesitekit/datastore/site/index.js`:
* Include the results in the existing `core/site` store definition, and merge the notifications store's `INITIAL_STATE` into the actual store's `INITIAL_STATE`.

## QA Brief

* 

## Changelog entry

* Add notifications functionality to `core/site` datastore.

**Comment by tofumatt** [comment]
> Include the results in the existing `core/site` store definition, and merge the notifications store's `INITIAL_STATE` into the actual store's `INITIAL_STATE`.

I'm a bit confused by this part of the brief—what does that entail in code? `INITIAL_STATE` is the uninitialised state code used to bootstrap a store, but I don't understand why we'd merge one store's `INITIAL_STATE` into another.

From the sounds of this issue we want to add notifications to `core/site`; based on the approach in #999 I'd think that would entail a new file (similar to `assets/js/googlesitekit/datastore/site/connection.js`) that contained notification data for the store.

So my approach would be to use the code in https://github.com/google/site-kit-wp/pull/1205/files#diff-084d6f9b3b4d5a065e515e4b91e750d3 but use it as `assets/js/googlesitekit/datastore/site/notifications.js`, then include that in the main `core/site` similar to the other two files in that folder.

**Comment by felixarntz** [comment]
> > Include the results in the existing `core/site` store definition, and merge the notifications store's `INITIAL_STATE` into the actual store's `INITIAL_STATE`.
> 
> I'm a bit confused by this part of the brief—what does that entail in code? `INITIAL_STATE` is the uninitialised state code used to bootstrap a store, but I don't understand why we'd merge one store's `INITIAL_STATE` into another.

The notifications "store" wouldn't be an actual store, but it would have its own `INITIAL_STATE` like what we were talking about for #1162 earlier (merging "sub-stores" initial state into the actual store's `INITIAL_STATE`).

> So my approach would be to use the code in https://github.com/google/site-kit-wp/pull/1205/files#diff-084d6f9b3b4d5a065e515e4b91e750d3 but use it as `assets/js/googlesitekit/datastore/site/notifications.js`, then include that in the main `core/site` similar to the other two files in that folder.

Good point, that makes sense. I'll update the IB.

**Comment by tofumatt** [comment]
Ahhh, gotcha! Yeah, I feel like we need to use a name for those—I'm happy with "sub-store" 😄

In that case, creating a sub-store for notifications sounds good.

One thing to note, having looked at the PRs where notifications are handled thus far (https://github.com/google/site-kit-wp/pull/1205/files#diff-084d6f9b3b4d5a065e515e4b91e750d3R32-R35). The idea that there are server and client notifications that are handled slightly differently makes sense to me, but in terms of organisation I'd propose that we group all notifications together and simply mark each one with attributes (such as `fromServer: true` or something) rather than group `serverNotifications` and `clientNotifications`. I think it's better to tag notifications with specific attributes than separate them out into different lists: it's more extensive for the future and makes it easier to deal with all notifications as a single group when appropriate, but then filter them out based on different attributes—not just server/client.

**Comment by tofumatt** [comment]
IB ✅

I'd prefer if we grouped notifications how I mentioned when implementing this, but this approach sounds good.

**Comment by tofumatt** [comment]
Code is reviewed and approved; assigning for merge 🙂

**Comment by cole10up** [comment]
**Tested**

Installed latest develop SK and connected all modules. Confirmed functionality. Removed all modules. Disconnected SK and uninstalled SK, re-installed and confirmed setup.

No issues to note. Passed QA ✅

**Comment by tofumatt** [comment]
QA ✅from engineering as well. Moved to approval.
