### ISSUE TITLE
Scaffold googlesitekit-user package and core/user store

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1175]
## Feature Description

This is very much similar to #999, introducing a separate `googlesitekit-user` JS file and respective module that registers a `core/user` store on `googlesitekit.data`. The implementation should follow the same patterns established in #999 (even the selectors and actions are very similar in behavior).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a JS file `googlesitekit-user.js` that is registered in PHP as `googlesitekit-user`.
* The script should depend on `googlesitekit-data` and `googlesitekit-api`.
* The script should register a `core/user` store on `googlesitekit.data`.
* The store should (for this initial implementation) have the following selectors:
    * `getAuthentication()`: resolves to the `core/user/data/authentication` route and "pass-through" its response<sup>1</sup>
    * `isAuthenticated()`: Should use the respective property from the above selector
    * `getRequiredScopes()`: Should use the respective property from the above selector
    * `getGrantedScopes()`: Should use the respective property from the above selector
    * `getError()` returns `state.error` set by internal `CATCH_*` actions  
    This doesn't belong to any other internal piece so it should be defined in its own file/sub-store
* The store should (for this initial implementation) have the following actions:
    * `disconnect()`: calls `core/user/data/disconnect` route

<sup>1</sup> The `core/user/data/authentication` should be modified in PHP to just rename `isAuthenticated` to `authenticated` (consistency with naming of other such parameters in e.g. `core/site/data/connection`). Any existing references in PHP or JS code should be adjusted.

## Implementation Brief

* Create a new file in `assets/js/googlesitekit/datastore/user/index.js` that creates a new `'core/user'` store using `'googlesitekit-data'`'s `registerStore` .
* Add an asset entry in `Assets.php` to enqueue the file.
* Expose a `getAuthentication()` selector that uses data from the `core/user/data/authentication` endpoint
* Expose a `getRequiredScopes()`: Should use the respective property from the above selector
* Expose a `getGrantedScopes()`: Should use the respective property from the above selector
* Add a `disconnect()` action that calls the `core/user/data/disconnect` API endpoint for the current user
* Add appropriate Jest tests.

## QA Brief

* 

## Changelog entry

* Introduce `core/user` datastore for managing user-specific data in JS.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@tofumatt Still needs estimate

**Comment by tofumatt** [comment]
Whoops, sorry, added!

**Comment by tofumatt** [comment]
QA ✅
