### ISSUE TITLE
Modify module REST route names to better match existing schemes

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1178]
## Feature Description

Some of the module REST routes we're currently using don't fit into our `{type}/{identifier}/data/{datapoint}` scheme, so we should adjust them. Note that we should differentiate between routes that belong to the core of Site Kit (`core/modules`) vs routes that integrate with custom module functionality (`modules/(?P<slug>[a-z\-]+)`). This will later be similar in JS, we'll have a generic `core/modules` store, and then individual module stores for specific functionality (see #1063).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The REST route `modules` should become `core/modules/data/list`.
* The REST route `modules/(?P<slug>[a-z\-]+)` should become `core/modules/data/info`, with a required `slug` parameter.
* The REST route `modules/(?P<slug>[a-z\-]+)/notifications` should become `modules/(?P<slug>[a-z\-]+)/data/notifications`. While doing that, we need to ensure that that route handler takes precedence over the more generic `modules/(?P<slug>[a-z\-]+)/data/(?P<datapoint>[a-z\-]+)` (this notifications "datapoint" really just passes through the request anyway and simply ensures that the response is not "Invalid datapoint", even if the module itself didn't implement it).
* All references to these endpoints in existing JS code should be updated so that they still work.

## Implementation Brief

* Merge #1218 

## QA Brief

* 

## Changelog entry

* Standardize several REST API route names for consistency with JavaScript API.

**Comment by felixarntz** [comment]
@aaemnnosttv If everything is clear and sounds good to you here, feel free to immediately go ahead with a PR (as the IB would likely match the ACs here).

**Comment by aaemnnosttv** [comment]
> The REST route `modules/(?P<slug>[a-z\-]+)` should become `core/modules/data/info`, with a required `slug` parameter.

This is a problem because this route supports GET and POST, and our data API doesn't support passing `data` as query parameters for GET requests. `apiFetch` also fails if `data` is passed for GET requests.

Instead, I changed `core/modules/data/info` to `core/modules/data/{slug}` - let me know what you think.

Keep in mind that `data` passed via parameters in `data.set` comes through as `$request['data']`.

**Comment by tofumatt** [comment]
QA ✅

Code looks good, routes are updated, and the plugin still behaves as-expected for the modified routes.
