### ISSUE TITLE
Introduce core/modules store in googlesitekit-modules

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1179]
## Feature Description

There should be a `core/modules` store on `googlesitekit.data` that allows to retrieve information about the available modules and their activation status. Some of the store selectors and actions should be wrapped with high-level functions on `window.googlesitekit.modules`. This issue is partly dependent on #1063 and #1178.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit-modules` script (introduced in #1063) should register a `core/modules` store on `window.googlesitekit.data` (via `googlesitekit/data` module).
* The store should follow patterns established in previous stores (see #999, #1175).
* The store should have the following "public" selectors:
    * `getModules()`: Should initially resolve via REST API call to `core/modules/data/list`.
    * `getModule( slug )`: Should probably just call `getModules()` selector and find the respective slug. Alternatively call `core/modules/data/info`, but that may result in unnecessary requests.
    * `isModuleActive( slug )`: Should get that respective boolean from the respective module information (can probably use `getModule()` selector).
* The store should have the following "public" actions:
    * `activateModule( slug )`: Should (if the module isn't already active) issue a `POST` request to `core/modules/data/info` with `active=true`.
    * `deactivateModule( slug )`: Should (if the module isn't already deactivated) issue a `POST` request to `core/modules/data/info` with `active=false` (or similarly without `active` parameter).
* In addition to registering the store on `googlesitekit.data`, the `googlesitekit-modules.js` script should expose the following convenience wrapper functions on `window.googlesitekit.modules` (in addition to the existing `createModuleStore( slug )`):
    * `activateModule( slug )`: Calls `googlesitekit.data.dispatch( 'core/modules' ).activateModule( slug )`
    * `deactivateModule( slug )`: Calls `googlesitekit.data.dispatch( 'core/modules' ).deactivateModule( slug )`

## Implementation Brief

* Use the `assets/js/googlesitekit-modules.js` script to register a `core/modules` store.
* Add selectors to the store:
  * `getModules()` with a resolver that uses data from the `core/modules/data/list` API.
  * `getModule( slug )`: Use `createRegistrySelector` to call `getModules()` above and extract the specific slug's data. It should return `null` if the slug can't be found.
  * `isModuleActive( slug )`: Should get the respective boolean from the respective module information (using the `getModule()` selector above). Should return `null` if the module doesn't exist.
* Add actions to the store:
  * `activateModule( slug )`: Should (if the module isn't already active) issue a `POST` request to `core/modules/data/info` with `active=true`. Should probably skip the request if the module is already active.
  * `deactivateModule( slug )`: Should (if the module isn't already deactivated) issue a `POST` request to `core/modules/data/info` with `active=false`. Should probably skip the request if the module is not active.

Add methods to `googlesitekit.modules.`:
  * `activateModule( slug )`: Calls `googlesitekit.data.dispatch( 'core/modules' ).activateModule( slug )`
  * `deactivateModule( slug )`: Calls `googlesitekit.data.dispatch( 'core/modules' ).deactivateModule( slug )`

## QA Brief

* 

## Changelog entry

* Introduce `core/modules` datastore for managing module information and activation state.

**Comment by felixarntz** [comment]
IB ✅

**Comment by ShahAaron** [comment]
Tested

PR code
Run e2e tests - passed
Run JS Unit tests - passed
Run Visual regression tests - passed

Site still functioning correctly

Passed QA ✅
