### ISSUE TITLE
Contributing doc need to be updated

### ISSUE THREAD

**Issue by ivankristianto** [google/site-kit-wp#118]
## Bug Description

Contributing guideline need to update:
https://github.com/google/site-kit-wp/blob/develop/CONTRIBUTING.md#contributing-code

Instead of branch from `master`, it should branch from `develop`, and submit PR to `develop`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ThierryA** [comment]
Will be addressed in #121
