### ISSUE TITLE
Internal event tracking not connected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1181]
## Bug Description

In #1055 we refactored the implementation of our internal event tracking infrastructure. In doing so we moved away from using the global `gtag` function and `dataLayer` variables for safer interoperability with other scripts that may be on the page. In doing so, the dataLayer is not getting fully connected.

## Steps to reproduce
1. Install the [Tag Assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk) Chrome extension
1. Opt-in to Site Kit's anonymous usage tracking
1. Load the splash screen `/wp-admin/admin.php?page=googlesitekit-splash`
1. See the single Global site tag in Tag Assistant  
![image](https://user-images.githubusercontent.com/1621608/75365537-03dff800-58c6-11ea-8898-f4e61f77e813.png)
1. Note, Google Analytics is not detected  
![image](https://user-images.githubusercontent.com/1621608/75365710-3e499500-58c6-11ea-8376-d0a7c713b040.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tracking events should be recorded and sent to GA via `gtag` as expected.

## Implementation Brief

The problem is that the dataLayer expects elements to be instances of  [`Arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments)

* Update internal `dataLayerPush` to push the special `arguments` variable onto the data layer, not an array
* Merge https://github.com/google/site-kit-wp/pull/1182

## QA Brief

1. Install the [Tag Assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk) Chrome extension
    * Ensure no extensions are blocking Tag Manager from loading
1. Load the splash screen `/wp-admin/admin.php?page=googlesitekit-splash`
1. Ensure that both the global site tag and Google Analytics are detected
1. Click on the Analytics tag
1. See **1 Pageview Requests** (can also click into this for pageview data)  
![image](https://user-images.githubusercontent.com/1621608/75369365-fcbbe880-58cb-11ea-894e-dac1911ddce3.png)

## Changelog entry

* N/A

**Comment by cole10up** [comment]
**Tested**
Confirmed setup of Tag Manager:
![image](https://user-images.githubusercontent.com/57115907/75414836-b0c66f00-58de-11ea-82ac-55c5f17c346e.png)

Confirmed setup of Analytics:
![image](https://user-images.githubusercontent.com/57115907/75414870-c8055c80-58de-11ea-8810-d7495c55fd0f.png)

Confirmed opt in status:
![image](https://user-images.githubusercontent.com/57115907/75414894-de131d00-58de-11ea-9679-94a56f00d9c4.png)

Activated Tag Assistant:
![image](https://user-images.githubusercontent.com/57115907/75414945-fdaa4580-58de-11ea-9f90-2252be8b2f44.png)

Ensured both Analytics and Tag Manager detected:
![image](https://user-images.githubusercontent.com/57115907/75415096-6ee9f880-58df-11ea-90b1-d5c112647b24.png)

Confirmed Analytics page view requests was shown
![image](https://user-images.githubusercontent.com/57115907/75415146-9214a800-58df-11ea-88df-4430f011ba28.png)

Adjusted analytics and confirmed nothing is being blocked
![image](https://user-images.githubusercontent.com/57115907/75415184-b07aa380-58df-11ea-8d1c-97b39de39890.png)

Ensured disabling and reenabling Analytics functioned properly. 

Passed QA ✅
