### ISSUE TITLE
Decouple date range selector values from labels

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1183]
## Bug Description

Dashboard doesn't load with the Spanish language (localized) version of Site Kit.  The following WP Error is present in the browser console:

```
WP Error in data response  > Object
code: "invalid_date_range"
message: "Rango de fecha no válido."
data: null
```

Support topic reference: https://wordpress.org/support/topic/g-sitekit-dashboard-doesnt-finish-loading/

This is because of a problem previously raised in #447: Site Kit relies on translatable strings to generate date range slugs. While the scope of 447 is much larger, we should address this bug in a more timely manner. Let's find a solution that really just addresses the bug though, we should not get into any actual refactoring here.

## Steps to reproduce

1. Go to _Settings > General_ to enable Spanish as the site language  (es_ES, es_VE, es_AR, and es_MX currently have the error) 
2. Install and activate Site Kit (with translated version) 
3. Setup and enable service connections 
4. See the dashboard elements attempting to load and the error in the console. 

## Screenshots

<img width="1274" alt="WP Error- Spanish localized version" src="https://user-images.githubusercontent.com/8108643/75396888-6f1bd100-58aa-11ea-9512-fa457f47e0e8.png">

video: https://recordit.co/dZyAMQwuRg

## Additional Context

 - PHP Version: 7.3.15
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.3.1
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `select` element in the `DateRangeSelector` component should have slugs as values and the current translatable strings only as labels.
* The date range filter used should rely on slugs.
* No slug should be generated from a translatable string.

## Implementation Brief

* Change the keys used for each date range option from translated strings to regular strings. (https://github.com/google/site-kit-wp/blob/develop/assets/js/components/date-range-selector.js#L100)
* Change the values used in the `'googlesitekit.dateRange'` hook (eg https://github.com/google/site-kit-wp/blob/develop/assets/js/components/date-range-selector.js#L35 and other places that hook is referenced)
* Merge (#1197)

## QA Brief

* Change the language the plugin displays in (will require changing your WordPress site's language from English)
* Select various date ranges in the date range dropdown on the main plugin dashboard page
* The values should change and no error should be encountered.

## Changelog entry

* Ensure date range selectors functionality is decoupled from localizable strings.

**Comment by swissspidy** [comment]
I **think** this is because of #447. I remember discussing this with @felixarntz .

See how the date labels are translated here:

![Screenshot 2020-02-27 at 10 32 26](https://user-images.githubusercontent.com/841956/75431018-87442c80-594c-11ea-8482-fa11c87887a6.png)

My suggestion would be to treat #447 as a bug rather than an enhancement...

**Comment by felixarntz** [comment]
@tofumatt A couple things are missing here. See PR review. Let's proceed from there. The IB is _kinda_ complete, except maybe stating that the filter should use slugs rather than generically saying strings.

**Comment by tofumatt** [comment]
The issue with the existing code wasn't that slugs weren't sent to the API, but that they couldn't be made from translated strings. Because there aren't many tests around this behaviour I went for the least-disruptive option first: use the strings that work as the key (they'll be converted by functions into usable slugs) and make the values the translated strings.

There's a bit more to this issue when refactoring how these date slugs are handled and makes it less of a quick fix than before, but still shouldn't take too long.

**Comment by felixarntz** [comment]
Fair point. I think the changes outlined in https://github.com/google/site-kit-wp/pull/1197#pullrequestreview-369215742 would be worth including here - let me know how much work this will entail, and if it's more than 1-2 extra hours, we'll do that later.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* Tested that Site Kit in `es_ES`
* Updated local translation to include new `Last %s day` and `Last %s days`  
_These should really be `%d` and include a `translators:` comment_
* Checked that the correct date range slugs were sent in the requests for each available date range
![image](https://user-images.githubusercontent.com/1621608/76504943-4a4e5e80-6451-11ea-876e-8d2940a3c99d.png)
![image](https://user-images.githubusercontent.com/1621608/76504951-4cb0b880-6451-11ea-90fb-cef027203388.png)
![image](https://user-images.githubusercontent.com/1621608/76504956-4f131280-6451-11ea-8114-3a2304648aa1.png)

**Comment by marrrmarrr** [comment]
Tested with Spanish as well.
