### ISSUE TITLE
Include link to support forums in JS error handler

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1184]
## Feature Description

Currently when an error is raised in React it may trigger our `ErrorHandler` component (see #943) which in turn renders a `Notification` for the user (rather than a blank screen) with information about the error.

As a notification, we could also provide a `learnMoreURL` prop. If we were to include this, the most useful URL might be a GitHub issue search using the error message
```
https://github.com/google/site-kit-wp/issues?q=is%3Aissue+%22error-message-here%22
```

This should help the user to see if there is already an issue for their particular issue or not.

GitHub is the better place to send users in this case since a fatal error in any case is not likely something that will be easily fixable via support.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a JS error occurs, the error notification "Site Kit encountered an error" should include a link "Report this problem", which links to the WP support forums for the plugin.

## Implementation Brief

* Update [`ErrorHandler`](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/ErrorHandler/index.js) component:
  * Replace `description` of the rendered `Notification` component to be a link to WP support forums (https://wordpress.org/support/plugin/google-site-kit/) with `Report this problem` text.
  * Add `{ error.message }` to the child `<pre>` tag right before `{ info.componentStack }`.
  * Add `style={ { overflow: 'auto' } }` attribute to the `<pre>` tag.
  * Add onclick handler to the `<pre>` tag with the following code to automatically select tag content when a user clicks on it:
    ```js
    const element = ...; // DOM element for <pre> tag

    const range = document.createRange();
    range.selectNodeContents(element);

    const selection = window.getSelection();
    selection.removeAllRanges();
    selection.addRange(range);
    ```

## QA Brief

* Add a code that throws an exception in one of the components that is rendered on the dashboard and build assets.
* Open the dashboard page, you should see that an error has occured, its details, a button to copy details to clipboard and a link to WordPress support forum.
* Click on the link, it should open WordPress support forum in a separate tab.
* Click on the "Copy to clipboard" buttton, it should change its icon and copy error details into your clipboard wrapped with backticks.

## Changelog entry

* Add copy-to-clipboard functionality and link to WordPress support forums to generic JavaScript error handler.

**Comment by tofumatt** [comment]
Reading this over again: are we sure this is a good idea? I don't think it's a good UX to direct most users to our GitHub repository and have them check for potential errors or issues.

Unless the plugin were developer-focused (it's not) and the issue tracker was the main source of support (it's not), it's likely to:

* confuse users unfamiliar with GitHub
* confuse users who don't have ZenHub installed, as our GitHub issues lack a lot of context without it
* direct users with support requests to put them in the wrong place

I think we should close this issue and not implement this change, as I think it only serves to confuse the majority of users who would be directed to GitHub when encountering a critical error.

**Comment by aaemnnosttv** [comment]
> Reading this over again: are we sure this is a good idea? I don't think it's a good UX to direct most users to our GitHub repository and have them check for potential errors or issues.

I'm not sure that it is a good idea, but it's up for consideration 😄 

I opened this issue as an enhancement to the current error handling we have in place which gives no further direction, so in that regard I feel like it's better than nothing.

Perhaps this issue would be better named "Consider adding learn more link to error boundaries"? Linking to GitHub directly might be a bit too clever, but I think we could be more helpful in the messaging we provide for users in these scenarios.

**Comment by felixarntz** [comment]
We discussed this one a while back, and there was consent that linking to GitHub wouldn't be appropriate for this plugin, mostly for the points @tofumatt makes. It's a great idea overall to pass the exact React error in such a link so users don't have to copy-paste it, but I think we shouldn't do this right now. We thought about linking to the WP support forums, but there it wouldn't be possible to pass anything in query vars.

I think we should close this for now as `wontfix`. If we have another concrete idea, we can open a new issue and discuss.

**Comment by aaemnnosttv** [comment]
> We thought about linking to the WP support forums, but there it wouldn't be possible to pass anything in query vars

What do you mean? The support forum has a search that we could fill. E.g.
https://wordpress.org/search/loading+chunk+intext%3A%22Plugin%3A+Site+Kit+by+Google%22
It's not a query parameter like `?s=` but it's still a URL we could generate programmatically.

If that's not an option for some reason, I'm fine with closing it. The issue was merely a discussion point for how to enhance the error handling experience.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@eugene-manuilov Can you add a QA Brief for this one? Afterwards this can be moved to QA.

**Comment by eugene-manuilov** [comment]
@felixarntz QA brief is added.

**Comment by tofumatt** [comment]
QA ✅
