### ISSUE TITLE
Misplaced Tests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#119]
## Bug Description

This isn't really a bug, but there are a few test cases for PHPUnit which are misplaced according to the directory structure convention we have in place.

The tests still run as it is, so there's no risk to actual test coverage, this is just for consistency.

Affected tests are:

```
Core/Util/Google/Site_Kit/Tests/Core/Util/UninstallationTest.php
Core/Storage/Google/OptionsTest.php
```

Should be:

```
Core/Util/UninstallationTest.php
Core/Storage/OptionsTest.php
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A

## Implementation Brief

* Move files to the right locations according to their full class name (including namespace).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv For next time, even for such purely test-related issues it would be great if you could add a quick implementation brief (one sentence), and mark the other two sections as N/A.
