### ISSUE TITLE
Allow selecting metrics in Analytics, such as pageviews instead of or in addition to users and sessions

### ISSUE THREAD

**Issue by archon810** [google/site-kit-wp#1190]
## Feature Description

Right now, Site Kit only shows users and sessions in Analytics. I prefer seeing pageviews instead, for example, and I think Analytics settings should allow some more flexibility in this regard.

Is it possible to consider bringing in more data types to be shown?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This issue contains three individual enhancement requests, so I've split some of them out:

1. The primary request is to allow displaying other Analytics metrics than what Site Kit currently displays. I'll refocus the issue on just that, which we are currently exploring as part of a greater effort to allow customization of the Site Kit dashboard.
2. The second request is to have awareness of which date range the data displayed in the admin bar for. I've opened #3202 for this.
3. The third request is to be able to change the date range for which data is displayed in the admin bar, somewhat a further iteration on 2. I've opened #3203 for this.

**Comment by tofumatt** [comment]
I'm closing this one for now as customising the metrics for particular widgets isn't something we're planning on for non-Key Metric widgets, which do offer some customisation.

We can open a new issue to work on this in the future if we decide to, but given this one has been stalled for four years I'm going to close it to help us triage issues 🙂
