### ISSUE TITLE
Add link to leave a review in Site Kit in footer

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1193]
## Feature Description

Many plugins add links in the footer of their plugin-owned screens to leave a review on wordpress.org.

We already have a `Need Help?` link in the bottom right corner. We could add a link on the other side asking users to leave a review.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
as a status update -- we'll be rethinking where it would make the most sense to place these links as part of the overall visual redesign.

**Comment by felixarntz** [comment]
Closing this one since we'll potentially revisit this as part of a broader redesign, but also will implement a targeted feedback popup which includes this.
