### ISSUE TITLE
Remove vendor assets

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1198]
## Bug Description

As of #993 all vendor dependencies are installed via npm, yet we still have a few vendor library files in the codebase.

The [assets/vendor](https://github.com/google/site-kit-wp/tree/afe494712f41ce29b23deaff091f579d5e109787/assets/vendor) directory is no longer used and can be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `assets/vendor` directory and its contents should be removed

## Implementation Brief

* Merge #1199

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB / PR ✅

**Comment by cole10up** [comment]
Confirmed post develop deploy that assets/vendor no longer exists.

![image](https://user-images.githubusercontent.com/57115907/75958333-d7515080-5e70-11ea-91bd-9c0f143ee859.png)

Passed QA ✅
