### ISSUE TITLE
Analytics: enable support for automatic event tracking

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1207]
## Feature Description
**Add automatic Analytics tracking for key events.** 

Related: https://github.com/google/site-kit-wp/issues/26

> The default JavaScript tracking snippet for Google Analytics runs when a web page is first loaded and sends a pageview hit to Google Analytics. If you want to know about more than just pageviews, you have to write code to capture that information yourself.

[autotrack](https://github.com/googleanalytics/autotrack) is a JavaScript snippet that _provides default tracking for the interactions most people care about_.

In particular, adding the `autotracker` script in Site Kit would enable automatically tracking the following useful events:

* [Outbound Link Tracking](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/outbound-link-tracker.md) - track links to external sites.
* [Outbound Form Submission Tracking](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/outbound-form-tracker.md)- tracks forms submitted to different domains (eg some hosted forms).  
* [Social Widget Tracking](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/social-widget-tracker.md) - track interactions with the official Twitter (tweet/follow) and Facebook (like) button.
[URL change tracker](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/url-change-tracker.md) - tracks changes to the URL via the History API and sends pageviews. This allows single page applications to be tracked like traditional sites without any extra configuration.

We could also extend it to cover additional use cases described in https://github.com/google/site-kit-wp/issues/26.

## Technical Considerations

* Ensure [compatibility with gtag.js](https://github.com/googleanalytics/autotrack/issues/202)
* Ensure increased load is negligible, consider [lazy loading](https://github.com/googleanalytics/autotrack#code-splitting) autotracking script
* Determine best route for exposing options (enable/disable entire feature? filters?)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamsilverstein** [comment]
Note: an alternative to the 'autotrack' script is figuring out a way we can enable [Analytics Enhanced Tracking](https://support.google.com/analytics/answer/9216061?hl=en).

**Comment by felixarntz** [comment]
This is somewhat similar to #1424, however it makes sense to keep it open, to inform any future decisions on this. I'll add it to the relevant epic we have now.

**Comment by aaemnnosttv** [comment]
Closing as this library is UA specific, but we've also recently shipped support for enabling Enhanced Measurement (GA4's feature which has a lot of the same features here) via SK 🚀
