### ISSUE TITLE
Request new analytics.provision scope

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1209]
## Feature Description

* Add the new provisioning scope the the scopes requested by Analytics.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Analytics is activated (for the first time), the scopes requested should include `https://www.googleapis.com/auth/analytics.provision`. During the user's auth flow, an additional analytics provisioning scope will be requested.

## Implementation Brief

* Add `https://www.googleapis.com/auth/analytics.provision` to the array of scopes in `Analytics.php::get_scopes()`

## QA Brief

* 

## Changelog entry

* N/A

**Comment by adamsilverstein** [comment]
I went ahead and added AC & IB details here since it is straightforward, please adjust if I missed something.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Technically ready for QA, but this in the GA provisioning branch (for 1.7.0 release) and should only be QAd with the other changes - let's keep this one waiting in the QA column for a bit.

**Comment by cole10up** [comment]
Sounds good @felixarntz

**Comment by adamsilverstein** [comment]
@cole10up - I created this draft PR to create a build for QA: https://github.com/google/site-kit-wp/pull/1343

**Comment by cole10up** [comment]
**Tested**

Was able to test this one using the Site Kit tester plugin.

Flipped my branch to: 
![image](https://user-images.githubusercontent.com/57115907/78407736-5940b080-75ba-11ea-9898-4833cd07eeb1.png)

Ran a series of tests installing SK and activating Analytics for the first time.

Confirmed the scope being requested here:
![image](https://user-images.githubusercontent.com/57115907/78407929-c2c0bf00-75ba-11ea-8d9c-7715c4be6db5.png)

and the final one here:
![image](https://user-images.githubusercontent.com/57115907/78407946-cc4a2700-75ba-11ea-982d-58eaa843247e.png)

Confirmed negative tests, denying, canceling. Uninstalling and reinstalling passed.

Passed QA ✅
