### ISSUE TITLE
Add Contributor Handbook

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#121]
## Feature Description

Write first iteration of the Contributor Handbook and replace existing documentation.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- [x] Add **Home** landing page
- [x] Add first iteration of **Engineering** guidelines
- [x] Add first iteration of **Project Management** guidelines
- [x] Add first iteration of **Release** guidelines
- [x] Add first iteration of **Roles & Job Families** guidelines
- [x] Update **README.md** to reference to the Wiki
- [x] Update **CONTRIBUTING.md** to reference to the Wiki
- [x] Cleanup **/docs**

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
I opened #125 for a specific follow up. Closing this one as it's been merged.
