### ISSUE TITLE
Handle TOS response

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1213]
## Feature Description

Once the user completes (or declines to complete) the Terms of Service, they are redirected back to the site. Handle successful responses and failures.

### Details

After the user takes some action on the TOS page then they will be redirected back to the `redirectUri` specified during account ticket creation. The response from the TOS page will be included as part of the query string.

* Successful responses will return data about the newly created account, unsuccessful requests will return an error code: see [docs for details](https://developers.google.com/analytics/devguides/config/provisioning/v3/user-controlled#technical-tos).
* When accepting the redirect, the `account_ticket_id` is checked against the one stored to later validate the request. Once validated, the stored data can be removed.
~* Send an analytics event indicating the completion of the TOS flow and the results: `trackEvent( 'analytics_setup', 'provisioning_tos_complete', [success|failure]] );~
* If there is an error, return the error screen/message and stop, otherwise continue…  
* Question: do we need to make an additional request to obtain the `internalWebPropertyID` (a private ID for the web property that appears unused).
* Redirect based on the results

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a handler that listens to incoming GET requests with `?gatoscallback=1` (see [here for requirements](https://developers.google.com/analytics/devguides/config/provisioning/v3/user-controlled#technical-tos-flow-response)).
* The handler should check for an error query parameter and return that error to the user if present.
* It should compare the received account ticket ID with the one stored via #1212, and fail if it is not the same (like a nonce check). Afterwards the account ticket ID stored before should be wiped.
* The account ID, property ID, and profile ID returned should be set.
* The user should be redirected to the dashboard (where Analytics should now be active). --> This is to be potentially revisited following UXR study, but for now let's assume this, as it's also the simplest solution.

## Implementation Brief

* In `includes/modules/Analytics.php` add a new hook on `admin_init` that checks for the `gatoscallback` query variable. (Match `oauth2callback` handling in `includes/Core/Authentication/Authentication.php`)
  - Avoid handling when WP_CLI defined
  - Scan input variables from `context->input()` 

* The handler should check the received [Account Ticket](https://developers.google.com/analytics/devguides/config/provisioning/v3/reference/provisioning) `id` parameter against the id stored in the [provisioning step](https://github.com/google/site-kit-wp/issues/1212):
`get_transient( ANALYTICS_PROVISIONING_ACCOUNT_TICKET_ID + '::' + get_current_user_id() )`
* Immediately delete the stored id.
* If the ids do not match, construct and return an error which will be displayed in the front end.
* If the ids match, proceed...
* Store the returned `account`, `property` (including `internalWebProperyID`) and `view` data in the analytics settings:
`$this->get_settings()->merge( { mapped returned settings } );`. Setup is now complete.
* Redirect the user to the Dashboard on success (`wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=analytics`, or to Analytics setup URL (`wp-admin/admin.php?page=googlesitekit-module-analytics&slug=analytics&reAuth=true?error={error code}`) if there is an error, passing the error code as a query variable.

**Note: reviewing the codebase, the internalWebPropertyID field appears unused. I suggest we investigate this further and remove if this is the case.**

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@adamsilverstein IB is good to go, except one detail: We can't track an event here since this is PHP. I'm not even sure this is required, we will know that already through our authentication service. I think we should just skip that part.

**Comment by adamsilverstein** [comment]
> We can't track an event here since this is PHP. I'm not even sure this is required, we will know that already through our authentication service. I think we should just skip that part.

Good point. I can see that we might not need the tracking here any more. If we do decide we still want to have this event triggered here, we can add it on the client side, passing an additional query variable to indicate the state.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
This may be affected by https://github.com/google/site-kit-wp/issues/1357#issuecomment-610516434 - we may want to change the redirect URL to be within WP Admin.

**Comment by felixarntz** [comment]
Let's wait with QA on this until everything from #1210 is done - it will only be testable altogether.

**Comment by cole10up** [comment]
**Tested**

Tested exiting setup of SK during TOS, hit cancel on each instance of the proxy
![image](https://user-images.githubusercontent.com/57115907/81140079-f033bc00-8f1c-11ea-8aa5-ebd6f55ea495.png)

Confirmed all instances of cancel drove to the correct page.

Canceled first TOS on Adsense setup:
**Noticed the following:**
![image](https://user-images.githubusercontent.com/57115907/81140164-44d73700-8f1d-11ea-8410-49850464d1d9.png)

Was able to re-auth and complete the setup

Canceled first TOS on Analytics setup:
![image](https://user-images.githubusercontent.com/57115907/81140198-61736f00-8f1d-11ea-88ed-639ad30598f5.png)

Was able to re-auth and complete the setup

Note - these 2 instances aren't the same experience but didn't fail on my end.

Passed QA ✅
