### ISSUE TITLE
SITE KIT will not accept my URL

### ISSUE THREAD

**Issue by Netchip** [google/site-kit-wp#1214]
## Bug Description

The putty is : xn--resistnciademocrtica-xxb1q.com
The Site URL is : https://resistênciademocrática.com/

But site kit does not want either ???

what do I do NOW ?????

**Comment by jamesozzie** [comment]
@Netchip Thanks for reporting. Unfortunately at present domains with non standard characters are unsupported. We are working on extending support which will allow for you to complete setup as expected. You can find out more in the related issue, #794.

Feel free to add any input to that issue.
