### ISSUE TITLE
Add documentation for core/site and datastore

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1215]
## Feature Description

Because of the size of #999 and the amount of code to review in #1162—as well as it blocking other issues—we omitted the documentation in the review/PR. We should add JSDoc comments to all new methods in that PR.

Additionally, @felixarntz and I discussed removing the `.private.js` file approach and marking private functions with the `@private` JSDoc param, which I think we can do for files in this issue as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All functions in #999 should have valid JSDoc strings.
* Private methods should be marked with the `@private` doc marker.

## Implementation Brief

* Add JSDoc for all functions added in #999.
* Move private file contents to their "main" file.
* Mark all functions previously in `.private.js` files as `@private`.
* Merge #1216

## QA Brief

* Little QA required; this is only adding documentation. Worth checking to see if tracking events still behave as expected because their `index.private.js` file was removed (contents moved to `index.js`).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## ⚠️ QA

A few minor items to be fixed. I created a PR for these in #1243

**Comment by tofumatt** [comment]
Thanks @aaemnnosttv! The changes look good; shame JSDoc doesn't seem to flag them by default 😞

**Comment by tofumatt** [comment]
(Changes look good and PR approved; assigning @felixarntz to merge the PR.)

**Comment by aaemnnosttv** [comment]
Didn't realize there was a dedicated issue for the follow up issues (#1241) so this is a bit redundant to be in execution as well. I think it's okay to move to Approval but I'll check with @felixarntz about it.

**Comment by felixarntz** [comment]
I'll move this to approval, we can deal with the follow-up outside of the release via #1241.
