### ISSUE TITLE
A network error occurred and the request could not be completed.

### ISSUE THREAD

**Issue by scarletshow** [google/site-kit-wp#122]

**Comment by jamesozzie** [comment]
@scarletshow Thanks for reporting the issue. Would you be able to provide more context to this issue and we can troubleshoot? If you cannot do a screen grab please provide some of the following information:

At what stage does this error appear?
WordPress Version: 
Web Host Environment: 
Site Kit install method (WP dashboard upload, FTP, version control etc)?
Any firewall/security plugin in use: 
Chrome Dev tools error console messages: 

If you want to try again I would suggest checking the app in your Google Cloud Platform also, you can delete that specific project which the setup created and try the process again.

**Comment by scarletshow** [comment]
Thank you.

**Comment by jamesozzie** [comment]
@scarletshow Were you able to get Site Kit working? If so I will close this issue.

**Comment by scarletshow** [comment]
Yes. Thank you.

**Comment by thekaku** [comment]
i have same issue, cant get oauth credential

**Comment by jamesozzie** [comment]
@thekaku Please check your WordPress site settings under "Settings > General" in your WordPress dashboard. Confirm your WordPress Address (URL) and Site Address (URL) match, and ensure they have a https prefix if you are using a https website. You can then attempt to setup Site Kit again. 

If that fails can you provide more information on the error you are receiving. Please share any console errors, screenshots or additional context .

**Comment by thekaku** [comment]
i tried to reset sitekit
after upload the plugin, i go https://developers.google.com/web/site-kit?sitename=Projasaweb&siteurl=https://projasaweb.com
and click Get OAunt Credentials

then get this error "A network error occurred and the request could not be completed."

console error : http://prntscr.com/pd64zp
this is my setting http://prntscr.com/pd64g1

**Comment by thekaku** [comment]
Solved : it because adblocker
