### ISSUE TITLE
Simplify `collectionActions` to alias `collect` and add `addInitializeAction` utility function

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1225]
## Feature Description

Currently, `collectActions` adds a generic `initialize()` action which is more than just collecting 😄. @felixarntz pointed out that we may have limited cases when we want to collect actions without adding an `initialize` action. While _technically_ one could just use `collect` over `collectActions` in that case, I think it's best to be a bit more functional in our approach and restore all `collect*` functions to just use `collect` (as was the original implementation), and then add functions that extend the actions/reducers/etc. when needed.

Most of our stores will use these functions, but let's make it a bit more functional.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All `collect*` functions in https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/data/utils.js should only collect items and not extend them.
* `addInitializeAction` and `addInitializeReducer` are added to https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/data/utils.js and used in stores.

## Implementation Brief

* Create a function that adds an `initialize()` action to an object of actions named `addInitializeAction`
* Create a function that responds to an `initialize()` action to a reducer named `addInitializeReducer`
* Replace `collectionActions( …actions )` calls with `addInitializeAction(collectionActions( …actions ))`
* Replace `collectionReducers( INITIAL_STATE, …reducers )` calls with `addInitializeReducer(INITIAL_STATE, collectReducers( …reducers ))`

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
## QA ✅ 

LGTM 👍
