### ISSUE TITLE
No response 

### ISSUE THREAD

**Issue by hapesurya** [google/site-kit-wp#1229]
## Bug Description

I already installed Site Kit plugin. I already followed the steps. and when I have to verify site ownership and click proceed button, There was no response after several attempts.

I already followed all step to fix issues in https://sitekit.withgoogle.com/documentation/fix-common-issues/

## Steps to reproduce

1. Go to Site Kit plugin
2. Sign in with Google (to verify ownership)
3. Grant Site Kit access to account (click Allow)
4. Verify site ownership (click proceed)
4. No response after several time to click the "proceed" button (see screenshot below)

## Screenshots

![site kit plugin-error](https://user-images.githubusercontent.com/47084690/76136808-30370980-6068-11ea-979b-51263028e8eb.png)

## Additional Context

 - PHP Version: 7.0
 - Browser : chrome
 - Plugin Version 1.4.0
 - Device: from Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@hapesurya If you're still encountering issues with Site Kit feel free to [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on the WordPress support forums, where we provide plugin support.
