### ISSUE TITLE
Remove old analytics.js

### ISSUE THREAD

**Issue by max23468** [google/site-kit-wp#1230]
## Bug Description

I've connected Google Analytics but a report done with GTMetrix shows that I'm both using the old analytics.js qnd the new jtag. How can I use only the latter?

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@max23468 Can you share your site URL and we can take a look. It may be a case whereby you are not using Site Kit to place the Analytics [tracking snippet](https://i.imgur.com/c9Mcpf8.png).

**Comment by max23468** [comment]
Thank you! I think I used only Site kit for Analytics.

I've just disabled maintenance mode so you can take a look

**Comment by max23468** [comment]
I've tried resetting my Analytics account and the plugin, but I still get two different js

https://www.googletagmanager.com/gtag/js?id=UA-158455317-1 
https://www.google-analytics.com/analytics.js

**Comment by jamesozzie** [comment]
@max23468 Everything looks fine from your setup. I can check with the team but the Analytics and GTM script being called on your site seem fine, using the default scripts from each service. Can you share the full error as seen on GTMEtrix?

**Comment by max23468** [comment]
It's not an error, but Analytics script should only call gtag.js script from GTM, as analytics.js has been deprecated since 2018: https://developers.google.com/analytics/devguides/collection/gtagjs/migration

Using both is a waste of resources, I think, and it seems that Site Kit is implementing both tags

**Comment by jamesozzie** [comment]
@max23468 Thanks for the update Max. Allow me to check with the team before reporting back.

**Comment by max23468** [comment]
Also, the snippet from my analytics page shows only the global js tag:


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-158455317-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-158455317-1');
</script>

Probably the best solution is letting user choose to have gtag.js, analytics.js or both, even if Google advises users to add only gtag

**Comment by jamesozzie** [comment]
@max23468 I spoke with the team in relation to this and the Analytics.js script does not on the front end of your site by default, it gets requested via the gtm.js script when required, which is normal behavior. As you correctly mentioned the Analytics.js script should not be added to the markup of your site. 

If you check the "initiator" tab when checking the Analytics.js network resource you'll see how the Analytics.js is requested, via the gtm.js script.

**Comment by max23468** [comment]
Thank you for the clarification!
