### ISSUE TITLE
Two weeks worth of Google Analytics data missing

### ISSUE THREAD

**Issue by drawcard** [google/site-kit-wp#1231]
## Bug Description

I logged in to Google Analytics today to check on site stats, and discovered that my site has not been recording any Google Analytics activity for 2 weeks, despite the fact that Site Kit is reporting that GA is connected.

I checked my site code in Incognito mode, and noticed that the usual GA script is not loading at all.

Can this missing data be retrieved?

This issue has also been reported here: https://support.google.com/analytics/thread/31518161?hl=en

## Steps to reproduce

No steps to reproduce.

## Screenshots

![image](https://user-images.githubusercontent.com/1435638/76174454-39a2ac00-61f7-11ea-9502-7459cea17413.png)

![image](https://user-images.githubusercontent.com/1435638/76174495-87b7af80-61f7-11ea-961a-7eefdc1646fb.png)

![image](https://user-images.githubusercontent.com/1435638/76174550-d8c7a380-61f7-11ea-8a34-0f64c85a5e3e.png)

## Additional Context

 - PHP Version: 7
 - OS: [e.g. iOS] macOS Catalina
 - Browser [e.g. chrome, safari] Chrome
 - Plugin Version [e.g. 22] Site Kit v1.4.0
 - Device: [e.g. iPhone6] Mac

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@drawcard While the statis the Analytics module may show as "Connected" you would also need the Analytics code snippet placed on your site, via Site Kit or another method. If you want to share your site URL I can check for the snippet. Alternatively can you confirm you have the [Analytics snippet option](https://i.imgur.com/c9Mcpf8.png) enabled?

Another scenario which has occured before was where Analytics tracking code was placed via another plugin or theme option, with that snippet used as opposed to allowing Site Kit to place the snippet. In some cases the other Analytics plugin or theme feature was removed, resulting in no data being gathered.

**Comment by drawcard** [comment]
Thanks @jamesozzie, my client doesn't wish for me to share the URL of the site. But I can add that Site Kit had been working fine up to that point, and had been placing the code snippet on the site. There were no other GA related plugins installed either, and no theme changes.

**Comment by drawcard** [comment]
Just reporting that I found the option that @jamesozzie had mentioned, and have turned it on. Thanks for pointing that out! But I'm not sure why it was switched off, possibly someone else had done it.

It would be nice if the plugin reported whether or not it was placing a snippet on the site, as it wasn't very obvious that there was this preference under the Analytics panel. Just a little label somewhere near "Connected" would do the trick.
