### ISSUE TITLE
Analytics stats graph is showing wrong year and no data 1.5.0

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#1232]
## Bug Description

Removed 1.4.0 from my personal site, built and deployed 1.5.0 develop (attached) 
[google-site-kit.v1.4.0.develop@226c1df37c.zip](https://github.com/google/site-kit-wp/files/4304755/google-site-kit.v1.4.0.develop%40226c1df37c.zip)

Setup Analytics and checked /admin.php?page=googlesitekit-module-analytics

Notice:
![image](https://user-images.githubusercontent.com/57115907/76184903-e3981f00-618a-11ea-9cec-e20f4a42d22e.png)

Selecting 90 days:
![image](https://user-images.githubusercontent.com/57115907/76184942-00345700-618b-11ea-9309-29eeac0931f1.png)

Notice 7 days graph shows:
![image](https://user-images.githubusercontent.com/57115907/76184958-0c201900-618b-11ea-8cc5-d34da15ccb8f.png)

Confirmed Analytics data is present via GA.
![image](https://user-images.githubusercontent.com/57115907/76185063-65884800-618b-11ea-9471-c7890f3c672b.png)

Only one active plugin (SK)
![image](https://user-images.githubusercontent.com/57115907/76185016-42f62f00-618b-11ea-8f38-991d4990342f.png)

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this one out as stale. Seems like it may have been a problem with the build or the local environment at the time.

Thanks @cole10up !
