### ISSUE TITLE
More than one user cannot edit sitekit without glitches

### ISSUE THREAD

**Issue by ReeceHaigh** [google/site-kit-wp#1235]
## Bug Description

I set up sitekit on my login, Everything worked.
The SEO team on their login showed they needed to re authenticate with google, They did which caused my login to show I need to re authenticate, And we get stuck in this loop.
Even though they can login and have the same access to my google accounts analytics, Tag manager ect they cannot set them up.

## Steps to reproduce

On wordpress have sitekit installed.
One wordpress user setup sitekit with a main google account.
Make sure another google account has access to all properties on the main google account (Analytics, Tag manager ect.)
Another user of the same wordpress site login, It shows as sitekit not setup on this site.
Try and set it up with the other google account, When it does work it throws issues and kicks the main account off.

## Screenshots
![screenshot_2020-03-09_at_11 00 01](https://user-images.githubusercontent.com/55700746/76222025-e427c880-6211-11ea-8172-146d4f45f8c4.png)
![image_from_ios](https://user-images.githubusercontent.com/55700746/76222033-e68a2280-6211-11ea-9d7b-6b3353a0db02.png)

## Additional Context

 - PHP Version: PHP 7.4.2 @64BitOS
 - OS: [e.g. iOS] Windows 10 Ver 1909 / IOS 13.3.1
 - Browser [e.g. chrome, safari] Chrome Version 80.0.3987.132 (Official Build) (64-bit) / iOS Safari
 - Plugin Version [e.g. 22] Version 1.4.0
 - Device: [e.g. iPhone6] HP Desktop PC / iPhone XR

One person with the google analytics account should be able to set up sitekit then other users of the wordpress site should be able to see the sitekit dashboard (Especially at admin level) as currently it means even though the SEO team have access to my stuff I have to share my wordpress loin with them to show and edit sitekit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@ReeceHaigh In relation to the re-authentication issue there may be other factors impacting this notice, one being OAuth limitations (if using 25+ sites). You can find out more about the limitations [here](https://developers.google.com/analytics/devguides/config/mgmt/v3/authorization#invalid_grant), with updates on that limitation in relation to Site Kit at #520. 

Looking at the screenshots provided the Google Tag Manager notice may be as a result of another container code already being placed on your site, which could be from another plugin, theme feature or other Tag Manager implementation. 

So we can troubleshoot further can you share the following:
- How many sites do you have Site Kit connected on (using the same Google account)?
- How many other administrators are connecting to an existing Site Kit setup?

**Comment by ReeceHaigh** [comment]
@jamesozzie 
    How many sites do you have Site Kit connected on (using the same Google account)?
2 Wordpress installs, 3 sites - One is a network site with itself and a subdomain (2), The other is a standalone site (1) (So 2 wordpress installs, 3 domains / public sites.).

    How many other administrators are connecting to an existing Site Kit setup?
1, The only admins on all wordpress sites are the SEO Team and I. My Google account is the main one(Analytics, Tag manager ect) with the SEO team having their own google account with full access to all my properties.

**Comment by ReeceHaigh** [comment]
I'm not having trouble authenticating, The issue is that sitekit is not shared with other logged in wordpress admins, So i'm authenticated now but when the SEO team log in they are seeing the reauthenticate message. If they do that then when I log in, I get the message.

I'd rather authenticate with my account then anyone who logs in can see what I see, Analytics, Settings ect.

**Comment by ReeceHaigh** [comment]
As a test I created a new user with an alternate email then logged in via a different browser - You can see it acts like sitekit has not been set up on the new user, Even though on my main one it is.

![Annotation 2020-03-10 150140](https://user-images.githubusercontent.com/55700746/76326233-44853b80-62e0-11ea-8c11-a3298bafaad9.jpg)

**Comment by adamsilverstein** [comment]
@ReeceHaigh Hi, thanks for the bug report. To clarify in your original test, when the second user logs in:

* Are they a WordPress admin?
* Are they setting up Site Kit with their own Google account?

**Comment by ReeceHaigh** [comment]
@adamsilverstein Yes, Both accounts are full wordpress admins, and owners on the google tools.

Yes they used their own google account and linked up the sites shared tools.

**Comment by adamsilverstein** [comment]
@ReeceHaigh Can you still reproduce this with the current version of the plugin? I am going to try to reproduce on my end as well.

**Comment by ReeceHaigh** [comment]
> Testing on my local instance I was not able to reproduce this issue. Both users remained logged in and had access to the site data. Please confirm this is still an issue and if it is we will continue to investigate.

Yes it’s still happening.

Was this done with 2 different google accounts sharing one lot of google services?

Different Wordpress accounts can log in to the plugin with the same email but not with 2 different emails with the same google analytics property.


So my wordpress login uses my google email to access site kit, our Seo team have their own Wordpress login and their own google email (but have access to my google analytics/adwords on their account) so they don’t have to log into any of my accounts to see and manage things, but when they sign in to sitekit using all their own logins and authenticate sitekit to my website mine is logged out, when I authorise my domain property again theirs is logged out.

**Comment by adamsilverstein** [comment]
That is odd, I wasn't able to reproduce that. 

Are both users WordPress admins?

I shared access to my Analytics account with a second user, and then logged in with a separate WordPress user and authorize site kit with that account. 

Both users maintained access to the data with their respective accounts.

Once they re-authenticate, do they see the data correctly? Do you have a second personal account you can share the data with to see if you can reproduce this directly?  

Can you try resetting site kit (from settings->admin), then set everything up yourself. The seo users should log in with their account but should not need to use settings at all.  Can you confirm the seo user is also added to Search Console?

**Comment by adamsilverstein** [comment]
> I'd rather authenticate with my account then anyone who logs in can see what I see, Analytics, Settings etc..

This type of 'shared data access' is a feature we are considering, for now however each user needs to have access to the google services you set up with their own account.

**Comment by jamesozzie** [comment]
@ReeceHaigh Just following up to check whether the same issue persists with the latest version of Site Kit. I'm happy to try and recreate the same issue from my side if you'd like to share your [Site Health information](https://i.imgur.com/Rtkmsba.png).
