### ISSUE TITLE
Fix initial state uninitialized properties to use "undefined" as value

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1236]
See https://github.com/google/site-kit-wp/issues/1173#issuecomment-595498612

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Existing stores (`core/site`) should be modified to use undefined as their "uninitialized" value.
* The `INITIAL_STATE` properties that start as undefined should still be present in that object.

## Implementation Brief

* N/A

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* Checked all store initial state objects use `undefined` for unset state
    * This only affected the state for `connection`, as the only other state keys are `doing*` state which can be set initially since these are more internal flags.
