### ISSUE TITLE
Disconnecting from SK on latest develop throws 'Cannot read property 'splashURL' of undefined' error

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#1237]
**Steps to reproduce**

Have the following configuration on the latest (attached) develop:

![image](https://user-images.githubusercontent.com/57115907/76285993-4d352d80-625e-11ea-9ccd-16fd8cd90c40.png)

Disconnect user from SK

Notice the following error occurs and user's instance of SK is no longer functional. Unable to reconnect.
![image](https://user-images.githubusercontent.com/57115907/76285801-dbf57a80-625d-11ea-9cda-00f62ee1ea40.png)

![image](https://user-images.githubusercontent.com/57115907/76286175-9eddb800-625e-11ea-89b4-fd3279864e54.png)

[google-site-kit.v1.4.0.develop@3597aedbee.zip](https://github.com/google/site-kit-wp/files/4310663/google-site-kit.v1.4.0.develop%403597aedbee.zip)

**Comment by aaemnnosttv** [comment]
@cole10up Something seems to be wrong with the zip you provided.  I didn't see the same error as you, but I couldn't even load the dashboard
![image](https://user-images.githubusercontent.com/1621608/76292858-a9c53680-62b8-11ea-9a7a-496d76d22819.png)

Can you try again using the latest build here?
https://github.com/google/site-kit-wp/wiki/refs/heads/develop/google-site-kit.zip

**Comment by cole10up** [comment]
I tried just now with the build you linked as well as added you to the instance. Still seeing the same experience.

![Site Kit by Google Dashboard ‹ Hellogoodbye — WordPress](https://user-images.githubusercontent.com/57115907/76327736-978ecc80-62a7-11ea-984a-df2fdb60b8be.gif)

**Comment by aaemnnosttv** [comment]
Thanks, that helps a lot. I'll take a closer look and follow up.

**Comment by jamesozzie** [comment]
Another user encountering this same issue from a WP support topic: 
[https://wordpress.org/support/topic/cannot-read-property-splashurl-of-undefined/#post-12536451](https://wordpress.org/support/topic/cannot-read-property-splashurl-of-undefined/#post-12536451)

**Comment by aaemnnosttv** [comment]
@cole10up @wpdarren would you please take a look and see if this is still possible? From what I can see disconnecting is working as expected.

**Comment by wpdarren** [comment]
@cole10up @aaemnnosttv disconnecting works as expected for me too with the latest release.  There's a support threat included in this ticket and it looks like the issue was resolved for the users too. I think we can close this.
