### ISSUE TITLE
Register module settings REST Routes automatically

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1244]
## Feature Description

Currently Module classes that support settings implement their own datapoints for updating settings in each class. This is unnecessary and may lead to inconsistency between datapoints when they don't require any special handling.

Also, no modules currently implement a `GET` method for the settings datapoint.

Since datapoints are mostly a mechanism to make batch requests possible, and settings shouldn't be needed in batch requests, we can provide them automatically via `Modules` by registering a `modules/{slug}/data/settings` route.

In the callback, we only need to check that the module identified by the given slug implements `Module_With_Settings`.  If the module exists but does not implement this interface, return a `400`.

Callbacks should be registered for `GET` requests to return `Settings::get()` and `POST` for `Settings::merge()` to update them.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `modules/{slug}/data/settings` route is registered in `Modules::get_routes()` which supports `GET` and `POST` requests
    - `GET` handler should return `ModuleSettings::get()`
    - `POST` handler should merge the given settings via `ModuleSettings::merge( $request['data'] )` before returning `ModuleSettings::get()`
* All current `settings` datapoints and handlers are removed

## Implementation Brief

* Add a new `REST_Routes` instance in `Modules::get_routes()` for `modules/{slug}/data/settings`
    - Register _before_ `modules/(?P<slug>[a-z\-]+)/data/(?P<datapoint>[a-z\-]+)` to take precedence
* In the callback for both, ensure the module exists, or return a `WP_Error`, similar to other `modules/{slug}` routes
* In the callback for both, ensure the module implements `Module_With_Settings`, or return a `WP_Error` with `400` status
* `GET` handler: return `$module->get_settings()->get()`
* `POST` handler:
    - Load the current settings with `get`, iterate over the keys, and ensure each one is present in the new settings, or return `WP_Error` to require all keys to be passed.
    - `->merge()` the provided new settings from `$request['data']` and return `$module->get_settings()->get()`
* Remove `POST:settings` datapoint in:
    - `Analytics`
    - `Tag_Manager`
    - `Optimize`
* Should require no changes in JS as the new route should match the same as datapoint

## QA Brief

* 

## Changelog entry

* Automatically include a REST route to read and edit settings for every module that supports them.

**Comment by felixarntz** [comment]
@aaemnnosttv Overall IB ✅, with two additional remarks:
* Would it make more sense to also allow for partial settings to be passed? I'd say no for now, but wanted to add it as a consideration.
* Let's make sure there is no discrepancy in any of the existing three `POST:settings` datapoints with the intended generic behavior - if there is, we may need some backward-compatibility patches.

**Comment by cole10up** [comment]
Ran a series of tests setting up all modules, confirming functionality, removing modules and resetting site kit.

![Site Kit by Google Settings ‹ Hellogoodbye — WordPress](https://user-images.githubusercontent.com/57115907/77618537-bd48e200-6ef3-11ea-96c0-5b43560c8a60.gif)

Passed QA ✅

**Comment by tofumatt** [comment]
Eng QA ✅
