### ISSUE TITLE
Simplify module settings in module JS info

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1245]
## Feature Description

Currently, the base `Module::prepare_info_for_js` method does not add a module's settings into the module info. Instead, module sub-classes individually overload this method and add their settings to it.

Now that Module classes are settings-aware, we can add this from the base method automatically for modules that implement `Module_With_Settings`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `Module::prepare_info_for_js` should always set the `settings` key in the array
    - If the module is an instance of `Module_With_Settings`, set it as `$this->get_settings()->get()`, otherwise set it to `false` (similar to how `screenID` is set)
* Module sub-classes should no longer add their own settings in the `prepare_info_for_js` method
* The `hasSettings` key should default to `$this instanceof Module_With_Settings`
    - Special cases should be overridden by the individual module (e.g. Search Console)

## Implementation Brief

* N/A

## QA Brief

* 

## Changelog entry

* Ensure module settings are consistently passed from PHP to JavaScript, and fix some minor logic issues in the consuming JavaScript code.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Ran a series of tests installing latest develop. Connecting all services, checking dashboards, uninstalling services, resetting SK and deleting SK.

Passed QA ✅

**Comment by aaemnnosttv** [comment]
QA ✅
