### ISSUE TITLE
Add support for preloading REST requests on page load

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1246]
## Feature Description

As we move to a fully datastore-based data layer, we want to make most (if not all) data fetched by resolvers available via REST endpoints. The data that is cheap to gather and provide is currently set to a global variable on page load (similar to `wp_localize_script`). This data should also be available via REST endpoints. In these cases, the responses to these routes can (and should) be preloaded into the REST API client on page load.

WordPress currently already does this in the block editor by exposing a [`block_editor_preload_paths` filter](https://developer.wordpress.org/reference/hooks/block_editor_preload_paths/), which provides an array of REST endpoint paths (including optional query parameters) to preload. These are then passed through the [`rest_preload_api_request` function](https://developer.wordpress.org/reference/functions/rest_preload_api_request/) (which is just a named function used as a callback for `array_reduce`). The results are then JSON encoded and passed to a [preloading middleware](https://github.com/WordPress/gutenberg/blob/f3ae6da72daa7c4cd5aba56ddc7668d0224aa593/packages/api-fetch/src/middlewares/preloading.js) which is registered with the `apiFetch` instance.

Source: https://github.com/WordPress/WordPress/blob/76e375434bdab9b1bf0a36da4492d554767b5618/wp-admin/edit-form-blocks.php#L55-L87

We should be able to use the same underlying preloading and apiFetch middleware to preload responses to simple REST requests as well. We can't use the same filter though because a) it's only run on post edit screens, and b) is only used for core's `window.wp.apiFetch` (which isn't always available for the versions we support, and we use our own instance).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Script_Data` instance for `googlesitekit-apifetch-data` should expose a `googlesitekit_apifetch_preload_paths` filter, which defaults to an empty array
* The paths from this filter should be preloaded with `rest_preload_api_request`
* The result of this should be included in the script's data as `preloadedData`
* `assets/js/api-fetch-shim.js` should be updated to pass the preloaded data to `apiFetch` using the `createPreloadingMiddleware`
* Each active `Module_With_Settings` should have its `settings` REST route added to the paths to preload

## Implementation Brief

* Add the new filter to `googlesitekit-apifetch-data`, to populate data for the added `preloadedData` key
* Add a filter in `Modules::register` to add the settings route to the list of preloaded routes for each module
* Simplify apiFetch bootstrapping by using `googlesitekit-apifetch-data` instead of implementing it
* Merge #1289 

## QA Brief

* 

## Changelog entry

* Add preloading middleware for REST API data and preload module settings routes on pageload.

**Comment by felixarntz** [comment]
@aaemnnosttv I wonder whether we can somehow tie the API routes that should be preloaded to the respective script handles in PHP.

I'd say we should certainly pass a `preloadPaths` property to the client via `_googlesitekitAPIFetchData`, and that should fire a filter like `googlesitekit_apifetch_preload_paths`. So at a minimum we could use that.

The problem if we want to tie it to the individual script assets (and a potential `preload_paths` argument on them) would be that these scripts would also rely on `googlesitekit-api-fetch-data` which would therefore end up having its `data_callback` being printed before (so the filter would fire before an eventual data callback from the more specific script could hook it in).

What are your thoughts on the approach here?

**Comment by aaemnnosttv** [comment]
I may not be understanding what you mean 100%. I agree that it makes sense to add a filterable list of paths to preload to the APIFetchData, but I don't think we should couple `Script_Data` to preloaded REST Routes.

`Script_Data` are just dependencies. Even if they contain data that we want to preload via an API route, we don't need to make this class responsible for that. We still have to register a real route to handle that.

> The problem if we want to tie it to the individual script assets (and a potential preload_paths argument on them) would be that these scripts would also rely on googlesitekit-api-fetch-data which would therefore end up having its data_callback being printed before (so the filter would fire before an eventual data callback from the more specific script could hook it in).

Again, maybe I'm not understanding but `Script_Data` shouldn't have dependencies of their own I don't think. If we did want to hook onto `googlesitekit_apifetch_preload_paths` from ` Script_Data` I don't think we would have to rely on `googlesitekit-api-fetch-data` (other assets would rely on that). Again, if we did, we could add that filter in `Script_Data::register` and then check if `wp_script_is( $this->handle, 'enqueued' )` in the callback. 

It sounds like you're trying to avoid duplication of defined data. Can you elaborate on what you're thinking here?

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested** Ran a series of regression tests on page loads after installing latest develop SK, activating and connecting all modules.

No errors on my end.

Passed QA ✅

**Comment by tofumatt** [comment]
QA ✅from me too; moving to approval.
