### ISSUE TITLE
Register modules/adsense datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1247]
## Feature Description

As a prerequisite of #1014, we need a new `modules/adsense` datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new directory `assets/js/modules/adsense/datastore`.
* The datastore should be registered on `Data` (`window.googlesitekit.data`) with the name `modules/adsense`.
* The datastore should use `Modules.createModuleStore` (`window.googlesitekit.modules.createModuleStore`) and combine that "sub-store" with its own selectors/actions etc. (i.e. with its own "sub-stores").
* The existing `assets/js/modules/adsense/index.js` file should do an import of the new `assets/js/modules/adsense/datastore` so that the datastore gets registered.

#### For settings:

* `getAccountID()`
* `getClientID()`
* `getUseSnippet()`
* `getAccountStatus()`
* `getSiteStatus()`
* `getSettings()` ("private")
* `haveSettingsChanged()`

#### Others:
* `getExistingTag()` --> returns `{ accountID, clientID }` or `null`
* `getTagPermission( accountID, clientID )` --> returns true or false
* `getAccounts()` --> returns list of AdSense accounts (typically a list of 1 account)
* `getClients( accountID )` --> returns list of AdSense clients (typically 1 client per type, e.g. "AFC")
* `getAlerts( accountID )` --> returns list of account alerts if any
* `getURLChannels( accountID, clientID )`
* `getReport( options = {} )` --> this does not accept an account as this selector is actually intended for beyond the setup, and the server will automatically return an error if no account ID is stored

#### For settings:
* `setAccountID( value )`
* `setClientID( value )`
* `setUseSnippet( value )`
* `setAccountStatus( value )`
* `setSiteStatus( value )`
* `setSettings( values )` ("private")
* `saveSettings()`

#### Others:
* Internal `fetch*` and `receive*` actions for the above selectors that resolve via API requests.

## Implementation Brief

* Implement selectors and actions based on the ACs above.
* For setting-related selectors and actions, use the automated functionality from #1250 rather than manually implementing them.

## QA Brief

* 

## Changelog entry

* Introduce `modules/adsense` JavaScript datastore with core functionality for the AdSense module.

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt Related to #1224, I've put together a list of selectors and actions for this one here. Let's make sure to keep both of these issues consistent in areas where they overlap (mostly naming).

**Comment by tofumatt** [comment]
Moving this one back to execution for now while the tests/existing `modules` global code is sorted out, just so it's clear what stage it's at 😄

**Comment by tofumatt** [comment]
Code review is ✅ from me; assigned over to merge 👍

**Comment by tofumatt** [comment]
Sorry, clicked "Close and comment" by mistake 😅

**Comment by cole10up** [comment]
Testing notes added in the main ticket here: https://github.com/google/site-kit-wp/issues/1332

**Comment by tofumatt** [comment]
I don't see the `assets/js/modules/adsense/datastore` in question in `develop` and got a bit confused because the `adsense-setup-refactoring` branch that code was merged into wasn't mentioned in the IB.

Checked out `adsense-setup-refactoring` and the code and tests are there; working as-expected.

QA ✅from engineering, moving to approval.
