### ISSUE TITLE
Implement createSettingsStore helper for reusable and consistent settings stores

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1249]
## Feature Description

Most modules will require settings functionality in their store (see #1224 and #1247 for example). We've already discussed the public API for that quite a bit in these two issues. This issue is about introducing a JavaScript layer to make implementation of such stores trivial and consistent automatically.

Related issues for server-side changes: #1244, #1245

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit/data` JS module should provide an internal function `createSettingsStore( type, identifier, datapoint, subSettings )`, which accepts `type`+`identifier`+`datapoint` to indicate the API route to connect to, and a `subSettings` list with names of the sub-settings that are part of the settings object that this endpoint controls.
* This function should be incorporated into `createModuleStore`, which should be expanded to `createModuleStore( slug, options = {} )`, with the only supported option for now being `settings`: If provided, it should be the list of settings (technically sub-settings) that belong to the Site Kit module; in that case `createModuleStore` will automatically call `createSettingsStore( 'modules', slug, 'settings', settings )` and combine that with the existing notifications sub-store.

## Implementation Brief

* Implement settings store creator using naming conventions and patterns previously defined as part of #1224 and surrounding discussions
* Review, iterate on and merge #1250 :)

## QA Brief

* 

## Changelog entry

* Add support for reading and editing settings to datastores created via `googlesitekit.modules.createModuleStore`.

**Comment by tofumatt** [comment]
For what it's worth I think this (and the accompanying PR) are good to go and should be moved along, as I've proceeded with #1224 assuming the settings store extender will be available to avoid re-implementing too much code 😄

**Comment by tofumatt** [comment]
QA ✅on this one; doesn't touch production code but things still work as-expected 👍
