### ISSUE TITLE
Send `analytics_redirect_uri` during site setup.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1254]
## Feature Description

The new Google Analytics provisioning feature relies on a callback URL which is loaded after the user completes the Terms of Service. This URL is passed requesting account provisioning and only a pre-registered route is allowed. 

Store the approved callback route during site setup to check against during the provisioning request.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When setting up a new site in site kit, the setup flow information should include a redirect uri for Analytics provisioning.

## Implementation Brief

* In `Google_Proxy::get_site_fields` add a new field `analytics_redirect_uri` to the array of fields, setting it to: `{site_url}?gatoscallback=1`. 

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Regression with latest develop passed.

**Tested**

Installed and activated SK
Connected Analytics, confirmed functionality of Analytics
Disconnected Analytics
Reconnected

Passed QA on my end ✅

**Comment by adamsilverstein** [comment]
After debugging an issue with our existing oauth callback, we have decided to move the callback to the `wp-admin` url. I will create a separate follow up issue for this.
