### ISSUE TITLE
Add option to edit Analytics snippet

### ISSUE THREAD

**Issue by max23468** [google/site-kit-wp#1257]
## Feature Description

Editing the default snippet which is injected by Site Kit could be useful for people who need to disable additional features like Ads/Remarketing ones.
Otherwise an option to add additional code to existing Analytics script would be usegul.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@max23468 Thanks for the suggestion. One of the main objectives of Site Kit is to make it easy for any user to integrate the various Google products, including Analytics into their site. While being able to edit the snippet would be useful for many it could also result in misconfigured tracking code if not implemented correctly.

If you're looking to place specific GA tracking code with additional features you can always insert your own code as you would normally, directly into a theme option, plugin or your WordPress template files. Site Kit will [recognize that existing tracking](https://jumpshare.com/v/BS0XIsQSZO4ri49OVAZI) code during Analytics module setup, so you can still use the Analytics dashboard without having Site Kit place the snippet. 

I can keep this suggestion open as a feature request for the team to consider. Thanks for the input.

**Comment by felixarntz** [comment]
It is possible to customize the Analytics snippet already, by using the `googlesitekit_gtag_opt` filter (or `googlesitekit_amp_gtag_opt` for the AMP version). Other than that, we've also made a few additional enhancements, with #3161 being currently worked on.

Allowing to edit the actual snippet directly is a non-goal for Site Kit as it would be too complex for the intended audience and furthermore would pose potential security issues. However, if there are specific adjustments which are not possible to add to the Site Kit snippet, these should definitely be catered for - feel free to open issues if there is something specific in Analytics that Site Kit does not let you do right now.
