### ISSUE TITLE
http_request_failed error during setup

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1262]
## Bug Description

Some users who've attempted setup reported encountering an error as below, with setup not proceeding. 
```
“Oops! There was a problem during set up. Please try again.
Unknown Error (code: http_request_failed).”
```
No screenshots available. 

Some related WordPress topics below:
https://wordpress.org/support/topic/unknown-error-code-http_request_failed-2/
https://wordpress.org/support/topic/error-when-setup-2
https://wordpress.org/support/topic/unknown-error-code-http_request_failed/
https://wordpress.org/support/topic/problem-during-setup-site-kit-2/
https://wordpress.org/support/topic/error-http_request_failed-when-verify-domain/

Possible issues with Google services unavailable for websites mentioned. VPN's referenced in [one support topic](https://wordpress.org/support/topic/unknown-error-code-http_request_failed-2/) with additional information in Google forms submission. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by lukegood** [comment]
I think I can provide some screenshots. These are my steps before I got this error.
Clicked the button to start.
[![8DdMB6.md.png](https://s1.ax1x.com/2020/03/18/8DdMB6.md.png)](https://imgchr.com/i/8DdMB6)
Cliked the button.
[![8DdKnx.md.png](https://s1.ax1x.com/2020/03/18/8DdKnx.md.png)](https://imgchr.com/i/8DdKnx)
Chose my account. (This picture is in Chinese.)
[![8DdmcR.png](https://s1.ax1x.com/2020/03/18/8DdmcR.png)](https://imgchr.com/i/8DdmcR)
Clicked the button to allowed the Site Kit to get my account information. 
[![8DdEh4.png](https://s1.ax1x.com/2020/03/18/8DdEh4.png)](https://imgchr.com/i/8DdEh4)
Clicked _Proceed_.
[![8DBScd.md.png](https://s1.ax1x.com/2020/03/18/8DBScd.md.png)](https://imgchr.com/i/8DBScd)
And the error.
[![8Dd1AO.md.png](https://s1.ax1x.com/2020/03/18/8Dd1AO.md.png)](https://imgchr.com/i/8Dd1AO)

Hope these screenshots are usefull.

**Comment by kindect** [comment]
I'm also receiving this problem and I'm also a user in China :D
I've been through the docs and I found out that the problem should be the internet trouble

As a site manager in china , I know that Google service are blocked in china so i'm currently using lantern VPN service to connect to google and i'm using Ubuntu 18.04 with gnome (I don't think this really matters after setting up LAMP and wordpress)

Anyway it seems that google itself is using a VPN in the site kit and the host name cannot be resolved

the result is simple: editing google's plugin and insert your own VPN code , which should be found through php helping website

**Comment by Pete-Z** [comment]
I am also a user of China. I have the exact same issue. 

I checked WordPress site URLs, which are correct. It's a brand new VSP server, so I don't think it has any ModSecurity or Web Application Firewalls. All the other plugins, including iThemes, are deactivated, but the issue remains. 

Below is my site health info. 
`
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/wwwroot/www.zhaozhao.co
wordpress_size: 37.84 MB (39680783 bytes)
uploads_path: /home/wwwroot/www.zhaozhao.co/wp-content/uploads
uploads_size: 3.24 MB (3399817 bytes)
themes_path: /home/wwwroot/www.zhaozhao.co/wp-content/themes
themes_size: 3.13 MB (3284078 bytes)
plugins_path: /home/wwwroot/www.zhaozhao.co/wp-content/plugins
plugins_size: 47.27 MB (49561165 bytes)
database_size: 2.44 MB (2555904 bytes)
total_size: 93.92 MB (98481747 bytes)

### wp-active-theme ###

name: GeneratePress Child (generatepress_child)
version: 0.1
author: Tom Usborne
author_website: https://tomusborne.com
parent_theme: GeneratePress (generatepress)
theme_features: automatic-feed-links, post-thumbnails, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, responsive-embeds, custom-logo, menus, editor-style, widgets
theme_path: /home/wwwroot/www.zhaozhao.co/wp-content/themes/generatepress_child

### wp-parent-theme ###

name: GeneratePress (generatepress)
version: 2.4.2
author: Tom Usborne
author_website: https://tomusborne.com
theme_path: /home/wwwroot/www.zhaozhao.co/wp-content/themes/generatepress

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.1, author: the WordPress team (latest version: 1.2)

### wp-plugins-active (1) ###

Site Kit by Google: version: 1.6.0, author: Google

### wp-plugins-inactive (9) ###

Anti-Spam: version: 6.5.4, author: CreativeMotion
Code Snippets: version: 2.14.0, author: Code Snippets Pro
Contact Form 7: version: 5.1.7, author: Takayuki Miyoshi
Easy Theme and Plugin Upgrades: version: 2.0.1, author: Chris Jean
Elementor: version: 2.9.7, author: Elementor.com
GP Premium: version: 1.9.1, author: Tom Usborne
iThemes Security: version: 7.6.1, author: iThemes
Simple CSS: version: 1.1, author: Tom Usborne
Yoast SEO: version: 13.4, author: Team Yoast (latest version: 13.4.1)

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.18.0-147.5.1.el8_1.x86_64 x86_64
httpd_software: nginx/1.16.1
php_version: 7.3.11 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 300
memory_limit: 256M
max_input_time: 60
upload_max_size: 50M
php_post_max_size: 50M
curl_version: 7.61.1 OpenSSL/1.1.1c
suhosin: false
imagick_availability: false

### wp-database ###

extension: mysqli
server_version: 5.7.26-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/wwwroot/www.zhaozhao.co/wp-content
WP_PLUGIN_DIR: /home/wwwroot/www.zhaozhao.co/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### google-site-kit ###

version: 1.6.0
php_version: 7.3.11
wp_version: 5.3.2
reference_url: https://zhaozhao.co
amp_mode: no
site_status: not-connected
user_status: not authenticated
active_modules: site-verification, search-console
required_scopes: 
	openid: ⭕
	https://www.googleapis.com/auth/userinfo.profile: ⭕
	https://www.googleapis.com/auth/userinfo.email: ⭕
	https://www.googleapis.com/auth/siteverification: ⭕
	https://www.googleapis.com/auth/webmasters: ⭕
search_console_property: none

`
Any idea how can I fix this issue? Thanks in advance for your help.

**Comment by kindect** [comment]
Glad to see Chinese fellows (which i'am also one) working on this and provide useful info like this
So the possible solution is to set php to use the VPN service since the google sever isn't available in China.
Hope that's going to help you

**Comment by Pete-Z** [comment]
Hi Kindect. Appreciate your input on the issue. I will do some research on how to set up PHP to use VPN. Have you resolved the issue with this VPN method? Is there a way you can share more details about how you did it? (Sorry, I'm a novice at these things.)

**Comment by jamesozzie** [comment]
@adamsilverstein I investigated this further today and there have been various causes for users impacted. Some findings below with links to their WP support topics:

**Third party service** 
One user is using a third party service to setup their WordPress site. Using this service results in their site URL being a subdomain of this third party service
[WordPress support topic]( https://wordpress.org/support/topic/error-http_request_failed-during-installation/)  | [Dedicated GitHub issue (#1363)](https://github.com/google/site-kit-wp/issues/1363)

**Mismatching URLs in General settings**
Some users have differing settings within their WordPress [general settings](https://i.imgur.com/MkFLF0E.png), resulting in the same error. 
[WordPress support topic](https://wordpress.org/support/topic/problema-para-configurar-la-aplicacion/#post-12647507) - Awaiting confirmation from user

@ernee and I will try reproduce the same issue next, with mismatching URLs.

**Comment by Pete-Z** [comment]
I don't have mismatching URLs in WP general settings. Also, if change “WordPress Address (URL)” and “Site Address (URL)” from hppts to http, Google Site Kit will get stuck at "Checking Compatibility". 

See video recordings of the errors:

https://www.youtube.com/watch?v=tGJHGStNa3o&feature=youtu.be

https://www.youtube.com/watch?v=09eaF9LN6lE

**Comment by aaemnnosttv** [comment]
The plugin needs to be able to connect to `https://sitekit.withgoogle.com`.

This can be checked with wp-cli using the following command:

```
wp eval 'print_r(wp_remote_head("https://sitekit.withgoogle.com"));'
```

If you don't have wp-cli, you could also test with `curl` but it might not be exactly the same as the way WP connects:

```
curl -I https://sitekit.withgoogle.com
```

Alternatively, the [Log HTTP Requests](https://wordpress.org/plugins/log-http-requests/) plugin could be used to inspect the details of the error.

**Comment by jamesozzie** [comment]
Tested Site Kit setup using region/country specific locations. Unable to recreate the same `http_request_failed` error message but did experience timeouts in some regions. 

I was able to recreate the same error using some hosting platforms, in particular for hosting providers who are more restrictive on services permitted. 

The issue is most likely service/hosting provider related, with whitelisting `*.withgoogle.com` a possible fix.

**Comment by ernee** [comment]
related topic resolved with host intervention (firewall): https://wordpress.org/support/topic/unknown-error-code-http_request_failed-3/

**Comment by jamesozzie** [comment]
Closing as there can be various causes, including at host level or geographical restrictions to Google services. 

For those who encounter this error if looking for support please [open a WordPress support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) while including your hosting provider and [Site Health information](https://i.imgur.com/Rtkmsba.png) (within the support topic or privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/)).
