### ISSUE TITLE
Users getting stuck on splash screen without error feedback

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1266]
## Bug Description

One of the common issues still regularly reported on the support forums, even after #1034, is that users sometimes cannot seem to complete the setup flow, as in they land back on the splash screen after going through what appeared to be the successful setup.

To recap, these are the requirements for a site to be considered "set up":
* The site needs to have site ID and secret.
* The user needs to have an access token.
* The site needs to have a Search Console property.

After investigating last week, the reason for this unexpected behavior is the lack of a Search Console property being stored in the site's database. While it's problematic that this happens without error feedback, we should rather fix the underlying issue: The reason that this can happen is that the logic to determine the Search Console property or the site URL itself may be out of sync with the logic on the authentication service or out of sync with the site URL stored on the authentication service. That means that, even if the authentication service detects or creates a corresponding Search Console property, because of these inconsistencies the site itself may not pick that up, silently failing and therefore not storing any Search Console property.

This can actually be easily resolved by passing the found Search Console property from the authentication service to the site, so that the site no longer needs to do that lookup itself.

A secondary problem that should be addressed alongside these changes (it already has been on the authentication service): For domain property comparisons, any eventual "www." part should be ignored.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Users should not get stuck on the splash screen after successfully completing the setup flow on the authentication service.
* There should always be a Search Console property stored after receiving a new token (access token _and_ refresh token).
* For domain property comparisons, any "www." prefix should be ignored.

### Technical acceptance criteria

* The authentication service will soon include the correct Search Console property in the response for receiving the OAuth token after going through the user flow, in a `search_console_property` field. The plugin should take that into account if available, instead of trying to look up the property itself.

## Implementation Brief

* Make URL matching for Site Verification and Search Console (for URLs and domains) fully consistent with each other by introducing a `Google_URL_Matcher_Trait` with methods `is_url_match( $url, $compare )` and `is_domain_match( $domain, $compare )`.
* Use that trait in both the `Site_Verification` class (`GET:verification` datapoint) and `Search_Console` class (`GET:matched-sites` datapoint) instead of the currently manual and inconsistent logic.
* Use exactly the same comparison logic as in the authentication service (including ignoring "www." prefix for domain matching), and provide the same tests to ensure it (this part needs to be reviewed specifically by @adamsilverstein).
* In `OAuth_Client::authorize_user()`, rename the `$authentication_token` variable to a more applicable `$token_response` and pass it to the `googlesitekit_authorize_user` action.
* Use that `$token_response` in the hook within `Search_Console::register`, and if there is a `search_console_property` in there, store that immediately instead of the existing detection logic.
* Merge #1267.

## QA Brief

* 

## Changelog entry

* Fix issue where users would get stuck on setup screen after seemingly successful completion of the setup flow on the authentication service.

**Comment by aaemnnosttv** [comment]
IB ✅ 

Needs estimate still 😄

**Comment by felixarntz** [comment]
@cole10up You should be able to verify this by changing the site URL of the site right after (e.g. in another tab) going through the setup flow Google consent screen on the proxy - basically when you land in step 1. A change as simple as HTTP --> HTTPS or so should already be enough.

This should leave you come back to the splash screen with no explanation after seemingly successfully completing the flow in the current version, but it should actually go through properly _with_ the version that includes this PR here.

**Comment by cole10up** [comment]
Tested:

Confirmed on 1.5.1 changing the domain to HTTPS from HTTP drives user back to the splash screen.

Installed latest develop 1.6.0 tried same flow, and didn't see any odd behavior after adjusting the domain URL in another tab. 

Passed QA ✅
