### ISSUE TITLE
Proposal adding services

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#127]
Add Google reCaptcha among the plugin services with the various versions: v2, invisible etc;
Adding Google My Business among the plugin's services;

Automatic positioning for Google AdSense ads, without using third-party plugins;

Possibility to add Google Analytics snippets with anonymized IP;

Moreover there are also some proposals for Google Analytics here: https://github.com/google/site-kit-wp/issues/36

**Comment by jamesozzie** [comment]
@sviluppomania Thanks for the great suggestions, as the plugin develops we can hopefully continue to add such features where possible. In relation to anonymizing IPs see  #56 and #18 . 

To keep track of such useful feature requests can you log each issue individually as a feature request (as opposed to multiple requests in the same submission). We can then categorise and prioritise accordingly.

**Comment by sviluppomania** [comment]
> @sviluppomania Grazie per gli ottimi suggerimenti, man mano che il plugin si sviluppa, possiamo sperare di continuare ad aggiungere tali funzionalità laddove possibile. In relazione agli IP anonimizzati vedere [# 56](https://github.com/google/site-kit-wp/issues/56) e [# 18](https://github.com/google/site-kit-wp/issues/18) .
> 
> Per tenere traccia di tali utili richieste di funzionalità è possibile registrare individualmente ciascun problema come richiesta di funzionalità (diversamente da più richieste nella stessa sottomissione). Possiamo quindi categorizzare e stabilire le priorità di conseguenza.


@jamesozzie sorry James, I do not understand regarding the anonymized IP ... The snippet inserted by the plugin does not make it with anonymized IP.

**Comment by jamesozzie** [comment]
Hi @sviluppomania. Customizing parameters for the inserted snippet is not supported at present. There is an [open feature request](https://github.com/google/site-kit-wp/issues/56) for this which will be discussed.

**Comment by jamesozzie** [comment]
Closing as open feature request exists #56
