### ISSUE TITLE
Finalize AdSense module setup/settings refactoring with datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1270]
This is a tracking task, to merge the branch [`adsense-setup-refactoring`](https://github.com/google/site-kit-wp/tree/adsense-setup-refactoring) to `develop` once all related refactoring has been completed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A

## Implementation Brief

* N/A

## QA Brief

* 

## Changelog entry

* N/A

**Comment by cole10up** [comment]
This was tested in this ticket: https://github.com/google/site-kit-wp/issues/1014
