### ISSUE TITLE
Errors plugin not listed 

### ISSUE THREAD

**Issue by gdgdd** [google/site-kit-wp#1272]
I have errors that are not listed with you, look at the screenshots of the errors and the plugins that are activated
I deactivated Monster, Wp Rocket; Ad insert
I installed this plugin to better place my advertisements: do I have to remove the other adsence scripts that I placed via the site theme, the ad insert plugin, and the composer page of the site

CAPTURES : 

![capture 1  site](https://user-images.githubusercontent.com/14005450/77111494-203c0400-6a30-11ea-9617-482234fc124f.PNG)

![capture2site](https://user-images.githubusercontent.com/14005450/77111589-4661a400-6a30-11ea-9bd5-ff5f73172669.PNG)

![capture3site](https://user-images.githubusercontent.com/14005450/77111690-7315bb80-6a30-11ea-8fa5-016698e1c2ff.PNG)

![capture 4 site](https://user-images.githubusercontent.com/14005450/77111759-8c1e6c80-6a30-11ea-96a9-a0384bff9cdc.PNG)

**Comment by jamesozzie** [comment]
@gdgdd Thanks for reporting. We're currently investigating this issue, which you can find out more about at https://github.com/google/site-kit-wp/issues/1092

Feel free to keep watch there or add any additional input to that issue.
