### ISSUE TITLE
Low Google PageSpeed score with active SiteKit.

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#1274]
## Bug Description

The Plugin causes a very low score in Google PageSpeed.
Why and why is it due?

## Screenshots

![image](https://user-images.githubusercontent.com/26438200/77368830-68736300-6d5d-11ea-9d1c-f4ecb3cd6796.png)

## Additional Context

 - PHP Version: 7.4.1
 - Browser [e.g. chrome, safari] chrome
 - Plugin Version [e.g. 22] 1.5.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@sviluppomania Site Kit operates primarily in the back end of your site, therefore not impacting the performance itself when visitors access your site. 

From the front end you can check your source code and check the code snippets inserted via Site Kit. You’ll notice only minimal code is inserted, such as snippets to add Analytics tracking code or AdSense Auto ads. If you were to implement the various Google products yourself without using Site Kit the code would be similar, so there is very minimal impact on performance. 

If you have connected the AdSense module via Site Kit and ads are displaying there can be times when ads impact performance, irrespective or whether they were added via Site Kit or another implementation. You can check <a href="https://support.google.com/google-ads/answer/2404037?hl=en" rel="noopener" target="_blank">this guide</a> or considering using AMP, with AMP ads performing better than non AMP ads. 

If that doesn't answer your question you can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist from there. We've moved general support over to the WordPress support forums. Please add as much relevant information, such as your [Site Health info](https://i.imgur.com/Rtkmsba.png) to your support topic to assist with your specific issue.

**Comment by sviluppomania** [comment]
@jamesozzie I found PageSpeed both with the plugin active and with the plugin disabled, it shows a significant change in performance.
It influences. How can we solve it? Maybe it's the CSS / JS of the plugin ...
