### ISSUE TITLE
AMP Linker for Google Analytics adding _gl query param to validated URLs

### ISSUE THREAD

**Issue by westonruter** [google/site-kit-wp#1275]
## Bug Description

On a site with Site Kit v1.5.1 active, which now enables linker by default for Google Analytics, when I try validating a URL via the admin bar menu item, I am taken to a validated URL screen with a `_gl` query parameter present. For more information on the `_gl` parameter, see https://developers.google.com/gtagjs/devguide/linker

That's not good because every time the admin bar menu item is clicked, a separate validated URL post will be created. 

The `_gl` query parameter needs to be stripped from the URL that is stored for the `amp_validated_url` post type.

However, it doesn't seem right that the `_gl` parameter should specifically be part of the AMP plugin because it's a Google-specific thing. It turns out that `AMP_Validated_URL_Post_Type::normalize_url_for_storage()` is already removing the `wp_removable_query_args()` from the validated URL. 

To fix the problem, all that Site Kit needs to do is add this filter:

```php
add_filter(
	'removable_query_args',
	function ( $args ) {
		$args[] = '_gl';
		return $args;
	}
);
```

## Steps to reproduce

1. Enable AMP plugin in Standard mode.
2. Enable Google Analytics in Site Kit
3. Navigate from homepage to a post.
4. Click on the validate link in the admin bar.
5. Notice the validated URL includes the `_gl` query parameter.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/77389430-6c4cb880-6d50-11ea-9faf-c05d0529908d.png)

## Additional Context

 - Plugin Version: 1.5.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It should be ensured that a potential `_gl` query parameter is not considered essential to a URL.

## Implementation Brief

* Add the following to the main `Plugin` class (for lack of a better place - it shouldn't be in `Analytics` because it's not really specific to that module, e.g. Tag Manager may cause the same problem):
```php
add_filter(
	'removable_query_args',
	function ( $args ) {
		$args[] = '_gl';
		return $args;
	}
);
```

## QA Brief

* 

## Changelog entry

* Fix issue related to added `_gl` query parameter from AMP linker.

**Comment by claudiulodro** [comment]
As a data point, we've had at least one publisher notice this issue and ask about it.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest 1.7.1 zip. Activated Analytics module. And activated AMP plugin in standard mode.

Navigated to a post and clicked validate URL in the admin bar.

Post URL: https://hellogoodbye.today/test-page/

Notice:
![image](https://user-images.githubusercontent.com/57115907/80071094-e5c6fa80-84f8-11ea-8b62-8735cd552760.png)

Created a fresh post, and retested

Post URL:  https://hellogoodbye.today/amp-url-validation/

![image](https://user-images.githubusercontent.com/57115907/80071329-45bda100-84f9-11ea-89c9-522bf601d5f6.png)

Didn't see the _gl parameter on the URL or in the list.

Passed QA ✅

**Comment by westonruter** [comment]
cf. https://github.com/ampproject/amphtml/issues/30176
