### ISSUE TITLE
Large number rounding should match service UI.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1279]
## Bug Description

When rounding large numbers (eg thousands), Site Kit's Analytics detail page shows a different "Users" number than the Analytics product UI. The numbers user's see in Site Kit should match those that they see in Analytics as well as in Search Console and AdSense detail reports.

* First discovered while working on https://github.com/google/site-kit-wp/issues/1202.
* Note: This issue may affect all rounding, we should check other services (Search Console, AdSense) to see how their UI's work with large numbers.

## Steps to reproduce

1. Go to the Analytics page for a site with thousands of user visits.
2. Compare the data reported by the plugin for 28 days/90 days vs what the Analytics product UI shows.
3. Note that numbers over 1,000 and lower than 99,000 are rounded differently (when over half way to the next 1000).

### Example case
* On my personal site, checking the last 90 days recently I had 6,852 Users. This is the number shown in the detail page in Analytics, and the number returned to Site Kit from the Analytics API:

![image](https://user-images.githubusercontent.com/2676022/77457369-31836880-6dc2-11ea-88d9-72d55d8c117a.png)

On the Analytics Home page, this number is rounded to the nearest 100 and presented as "6.8k":

![image](https://user-images.githubusercontent.com/2676022/77457440-511a9100-6dc2-11ea-8238-2ca943b7e433.png)

In Site Kit, the same number is [rounded using `Math.round` in `readableLargeNumber`](https://github.com/google/site-kit-wp/blob/c2ec75e3327ebb06ad28dcdcc5d78e7e4294bb27/assets/js/util/index.js#L144-L149), resulting in it being rounded **up** and displayed as "6.9k":

![image](https://user-images.githubusercontent.com/2676022/77457557-7d361200-6dc2-11ea-9565-9e0c41722b92.png)
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All large number rounding should match between Site Kit and the respective product UI.

## Implementation Brief

- In `assets/js/utils::readableLargeNumber` ensure that all numbers are rounded down using `Math.floor`.
- Add additional tests in `assets/js/util/test/readableLargeNumber.js` to confirm that numbers match the expected results in various product UIs.

## QA Brief

* 

## Changelog entry

* Fix bug where certain numbers were rounded differently from how the respective Google service rounds them.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@ryanwelcher This still needs an estimate (via ZenHub extension) :)

**Comment by ryanwelcher** [comment]
Thank you @felixarntz!  I've added the estimate

**Comment by tofumatt** [comment]
Code reviewed ✅from me—passing off to merge 🙂

**Comment by ryanwelcher** [comment]
I'm going to take this back to look at the issues that @adamsilverstein ran into in the PR - https://github.com/google/site-kit-wp/pull/1327#issuecomment-607496860

**Comment by cole10up** [comment]
**Tested**

Downloaded and installed latest develop SK:
[google-site-kit.v1.6.0.develop@4b626cc5a5.zip](https://github.com/google/site-kit-wp/files/4451554/google-site-kit.v1.6.0.develop%404b626cc5a5.zip)

Connected and setup Analytics

Checked 90 days in SK versus 90 days in GA:

![image](https://user-images.githubusercontent.com/57115907/78806837-1d219d00-7978-11ea-9870-a1b097f2d493.png)

![image](https://user-images.githubusercontent.com/57115907/78806879-2a3e8c00-7978-11ea-88be-875edb737324.png)

Notice User's majorly off between GA's statistics and SK.

Sending back to CR

**Comment by felixarntz** [comment]
Moving this out of 1.7.0 because it's very late - #1309 should have priority.

cc @ryanwelcher

**Comment by felixarntz** [comment]
@cole10up This issue is only about numbers being rounded, not the day range displayed - could you re-check against this?

**Comment by cole10up** [comment]
Trying to recheck the user totals are way off between GA and SK so I can't accurately get a positive test as they don't match.

See total users here in SK:
![image](https://user-images.githubusercontent.com/57115907/78808922-fadd4e80-797a-11ea-82aa-295b8072add7.png)

See total users here in GA:
![image](https://user-images.githubusercontent.com/57115907/78808955-0c265b00-797b-11ea-8bf0-868484cedcbf.png)

Sessions, bounce rate and duration match. User total seems to be broken in SK.

**Comment by cole10up** [comment]
Retested and am not seeing any extra rounding of large numbers.

GA:
![image](https://user-images.githubusercontent.com/57115907/78867461-fefa8200-79f5-11ea-966a-5147bc26fbc4.png)

SK:
![image](https://user-images.githubusercontent.com/57115907/78867507-10dc2500-79f6-11ea-83d1-13ab3484f7a9.png)

Passed QA ✅
