### ISSUE TITLE
Low Google PageSpeed score with active SiteKit.

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#1283]
#1274 
@jamesozzie 
 I found PageSpeed both with the plugin active and with the plugin disabled, it shows a significant change in performance.
It influences. How can we solve it? Maybe it's the CSS / JS of the plugin ...

**Comment by jamesozzie** [comment]
@sviluppomania Are you able to provide a video demonstrating the PageSpeed differences using the [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) and we can investigate/communicate from there? You can use a service such as recordit, along with web.dev for measuring. 

While we've moved support over to the WordPress forums we can file a GitHub issue or reopen this issue if we're able to determine any aspect of the plugin that requires attention in relation to this.

**Comment by sviluppomania** [comment]
@jamesozzie 
These are videos from the my Website with Google Site Kit and without Google Site Kit...
[Screencast.zip](https://github.com/google/site-kit-wp/files/4395327/Screencast.zip)

**Comment by sviluppomania** [comment]
@jamesozzie
