### ISSUE TITLE
Only make API requests in resolvers when lacking data

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1286]
## Feature Description

Part of #1101, we should only make requests for data when there isn't data available already. This will drastically cut down on API mocking in test code and increase the performance of our app if we preload data from places.

A good example of this is in the analytics module, we get accounts, properties, and profiles during the first request (via the resolver for `getAccounts()`), but because the `getProfiles` and `getProperties` resolvers haven't run, they still make two more API requests despite the data already being available.

We should check for existing data before dispatching control actions.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Data stores which have received data but not resolved their selectors should not dispatch to get the same data.

## Implementation Brief

* Check for data inside any resolver before dispatching a `fetch*()` action, where appropriate.
* Merge #1290

## QA Brief

* This should have no impact on existing production code and require no/minimal QA. If the app still works: we're good 🙂

## Changelog entry

* Update datastore resolvers to only issue API requests when lacking data.

**Comment by aaemnnosttv** [comment]
IB ✅  CR ✅

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt Why is this still in CR but unassigned?

**Comment by tofumatt** [comment]
Looks like that might've been ZenHub getting confused about PRs for this being merged into both `develop` and the refactoring branch… or possibly just an oversight after the code was merged. All the related PRs here have been merged, so I think this can move to QA.

**Comment by cole10up** [comment]
Ran regression around basic functionality. Installed and setup SK, connected all modules, confirmed functionality, disconnected modules, disconnected SK, deactivated and removed SK. Reinstalled and confirmed everything remained functional after setup a 2nd time.

Passed QA ✅
