### ISSUE TITLE
Tag Manager: Layout inconsistency in settings after installing AMP

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1296]
## Bug Description

If Tag Manager is set up before AMP is installed/enabled, only a web container will be configured in the settings. After, if AMP is enabled, the empty value for the setting creates an inconsistency in the layout

## Steps to reproduce

1. Set up Site Kit with Tag Manager (no AMP)
1. Install and activate AMP in either Transitional or Reader modes (i.e. paired)
1. Go to Settings > Tag Manager
1. See AMP Container ID header out of alignment with other headers

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/77669693-d900c680-6f8d-11ea-9504-29699aaf23cc.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The layout of the Tag Manager settings panel should not look off if there is no AMP container selected while AMP is in use.

## Implementation Brief

* Create a new shared component for displaying a setting value, e.g. `DisplaySetting` (I'm open to better names for this 😄 )
* It should accept the `value` as a prop
* Internally, it should return the value if present, or `"\u00A0"` (unicode for `&nbsp;` which we can't use because React will escape it)
* Update settings views to use `DisplaySetting` for displaying each primitive value.  
I.e. those that are currently `{ value || false }`

If we decide in the future to display something else instead (e.g. "not set", etc) we only need to make the change in one place.

## QA Brief

* Follow the steps to reproduce above
* Ensure the layout is not [distorted](https://user-images.githubusercontent.com/1621608/77669693-d900c680-6f8d-11ea-9504-29699aaf23cc.png)

## Changelog entry

* Fix layout issue in Tag Manager settings panel when no container is selected.

**Comment by tofumatt** [comment]
I would prefer it explicitly say "Not set" rather than displaying an empty string. I think it makes things clearer, more consistent, and doesn't have the potential to look like a bug. But we can discuss that in the PR or later; the basis of this is IB ✅

**Comment by aaemnnosttv** [comment]
@tofumatt I agree, but that can be a discussion for another issue as you said 👍

**Comment by cole10up** [comment]
**Tested**

Installed latest 1.7.1 zip. Activated Analytics and Tag manager without an AMP account. Activate AMP in Transitional mode. Noticed:

![image](https://user-images.githubusercontent.com/57115907/80072549-40f9ec80-84fb-11ea-9d89-bab2c5665cf1.png)

Checked Reader mode: 
![image](https://user-images.githubusercontent.com/57115907/80072601-52db8f80-84fb-11ea-84b0-5aa3ee8d8408.png)

Confirmed positive test with AMP container ID populated without being misaligned
![image](https://user-images.githubusercontent.com/57115907/80072770-8f0ef000-84fb-11ea-8bdf-30a52bddac59.png)

Passed QA ✅
