### ISSUE TITLE
Punycode URL is being displayed on disconnect screen for unicode domains

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#1297]
## Bug Description

Disconnecting my user on a unicode domain (http://türkish.com) shows http://xn--trkish-3ya.com/ as the URL in the 'revoked access' message

![image](https://user-images.githubusercontent.com/57115907/77669782-8948dd80-6f42-11ea-9077-53ce922cf56c.png)

## Steps to reproduce

- Login to http://türkish.com/wp-admin/admin.php
- Setup SK
- Click Disconnect 
![image](https://user-images.githubusercontent.com/57115907/77670004-d5941d80-6f42-11ea-8ac2-dc9bef24dd4a.png)

Notice

![image](https://user-images.githubusercontent.com/57115907/77669782-8948dd80-6f42-11ea-9077-53ce922cf56c.png)

## Acceptance criteria

* For sites that use a unicode domain as their "Site Address", the message shown after disconnecting should show that unicode domain, not the punycode version of it.

## Implementation Brief

* Add the [punycode](https://github.com/bestiejs/punycode.js) library and use its `toUnicode()` function to decode punycode hostnames in `setup-proxy.js`.
* Merge #1331 🙂 

## QA Brief

* 

## Changelog entry

* Fix unicode domains being displayed in punycode version in disconnect feedback message.

**Comment by tofumatt** [comment]
That page currently uses `new URL( url ).hostname` to render the hostname, which will output punycode characters (this is expected behaviour). All we need to do is import a punycode decoder and decode the hostname here. 👍

**Comment by felixarntz** [comment]
@tofumatt Overall sounds good, but shouldn't we be using the [`toUnicode` function](https://github.com/bestiejs/punycode.js#punycodetounicodeinput)?

**Comment by felixarntz** [comment]
Also this will need an estimate :)

**Comment by tofumatt** [comment]
Argh, I could've sworn I added an estimate. Oh, and sure, we can use `toUnicode` instead! I tried it out with `decode` in my branch, but `toUnicode` is more appropriate, true 😄

IB updated!

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

This is not fixed.

Built latest develop here:
[google-site-kit.v1.6.0.develop@4b626cc5a5.zip](https://github.com/google/site-kit-wp/files/4448365/google-site-kit.v1.6.0.develop%404b626cc5a5.zip)

Logged into http://xn--trkish-3ya.com/wp-admin/admin.php

Setup SiteKit and clicked Disconnect from dashboard.

Notice:
![image](https://user-images.githubusercontent.com/57115907/78747795-23375f80-791f-11ea-897a-9657a77bd3fa.png)

**Comment by felixarntz** [comment]
@tofumatt Can you check on this?

**Comment by tofumatt** [comment]
Oddly, I authenticated on that site, disconnected, and saw this screen:

<img width="1028" alt="Screenshot 2020-04-08 18 12 00" src="https://user-images.githubusercontent.com/90871/78813115-74e5f580-79c4-11ea-9c32-531d9a6e2823.png">

I'm not sure what would've caused the original error—maybe something was just cached? It seemed to work on the site for me. 😅

**Comment by felixarntz** [comment]
It could indeed be caching, since the plugin version number had not yet changed to 1.7.0.

**Comment by tofumatt** [comment]
Ah, just a note here that @cole10up and I talked about this on Slack and he tested it and experienced the correct behaviour on two separate machines as well—including the one he originally saw the failure on.

I forgot to mention that here, but we both verified this working and he said it was good to move to Approval 😄
