### ISSUE TITLE
Implement googlesitekit-widgets asset with "core/widgets" datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1298]
## Feature Description

There should be a `js/googlesitekit/widgets` module that registers a `core/widgets` store. It should have an entrypoint file `googlesitekit-widgets`. The file should also use the handle `googlesitekit-widgets` in PHP.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Add new `js/googlesitekit/widgets/datastore` module that exports a `core/widgets` datastore and `js/googlesitekit/widgets` that for now just imports that. The module will later do more things so it needs to be there in addition to `js/googlesitekit/widgets/datastore`, although right now that's the only surface point.
* The module should have an accompanying entrypoint file `js/googlesitekit-widgets.js` with a PHP handle of the same name.
* The store should have the following actions:
    * `registerWidgetArea( slug, settings )`
    * `assignWidgetArea( slug, contextSlugs )`
    * `registerWidget( slug, settings )`
    * `assignWidget( slug, widgetAreaSlugs )`
* The store should have the following selectors:
    * `isWidgetAreaRegistered( slug )`
    * `isWidgetRegistered( slug )`
    * `getWidgetAreas( contextSlug )`
    * `getWidgets( widgetAreaSlug )`
* The datastore should fully operate on the client side. So most likely this will only need `googlesitekit-data` as the sole dependency in PHP.
* See doc for more details on requirements for these actions and selectors.

## Implementation Brief

* Create a `js/googlesitekit/widgets/datastore/index.js` that creates a module, similar to other datastores. This will likely be a simple datastore, similar to `core/site`.
* Create a `js/googlesitekit/widgets/index.js` that exposes our Widgets API.
* Create an `assets/js/googlesitekit-widgets.js` file. Import `Widgets` from `assets/js/googlesitekit/widgets` and expose it on `googlesitekit.widgets`.

### Widget actions

* `registerWidgetArea( widgetAreaSlug, settings )`: Create a widget area with the specified slug and settings. This saves the data in the `widgetAreas` section of the store. If the `slug` supplied is already in use, it should dispatch a failed action and log a `console.error` message to alert the developer/user. Registering a widget with an existing slug should not crash the app. Essentially: whoever registers a `slug` first claims it. The `settings` object takes the following attributes:
    * `priority`: numeric priority, like WordPress hook priorities (lower means higher priority, default is 10)
    * `title`: Title of the widget area, shows above
    * `subtitle`: Subtitle of the widget area, shows right below the title
    * `icon`: SVG icon for the widget area
    * `style`: defines how the widget area renders its widgets; the following values are available:
        * `boxes`: every widget renders as an individual box (this should be the default)
        * `composite`: the widget area itself renders as a box and every widget is just inside, basically as columns within that box
* `assignWidgetArea( widgetAreaSlug: String, contextSlugs: String | Array )`: Assign the Widget Area (`widgetAreaSlug`) to each Context (`contextSlugs`) provided (or to one context slug if `contextSlugs` is a string instead of an array). Repeat assignments will be ignored; assignment is idempotent.
* `registerWidget( slug, settings )`: Register/create a widget with a particular slug and settings. This requires `settings.component` (I wonder if we should make it a separate argument, before `settings`?), which will be a React component. **Because we can't store a function (eg. a React component) inside our datastore, this will require storing a reference to the component/function outside the datastore and keying it by its slug.** Something like `registry._widgetComponents[slug] = settings.component`—but likely keyed to each instance of the widget datastore (to help with testing, etc.).
* `assignWidget( slug: String, widgetAreaSlugs: String | Array )`: Assign the widget (`slug`) to each Widget Area (`widgetAreaSlugs`) provided (or to one context slug if `widgetAreaSlugs` is a string instead of an array). Repeat assignments will be ignored; assignment is idempotent.

### Widget selectors

* `isWidgetAreaRegistered( slug )`: Return `true` if a Widget Area with the given `slug` is registered. `false` if not.
* `isWidgetRegistered( slug )`: Return `true` if a Widget with the given `slug` is registered. `false` if not. Widgets are _registered_ globally, so this requires no other arguments. Widgets are only assigned with context/area scopes.
* `getWidgetAreas( contextSlug )`: Return all registered areas for a given Context (`contextSlug`). Returns `undefined` if the specified Context (`contextSlug`) is not registered.
* `getWidgets( widgetAreaSlug )`: Return all registered widgets for a given Widget Area (`widgetAreaSlug`). Returns `undefined` if the specified Widget Area (`widgetAreaSlug`) is not registered.

## QA Brief

* 

## Changelog entry

* Introduce `core/widgets` datastore for Site Kit widget registrations.

**Comment by felixarntz** [comment]
@tofumatt I removed the feature branch bit from this one too.

**Comment by tofumatt** [comment]
Whoops, I sort of misplaced where to put most of the IB, and misread this one as just scaffolding. I'll write up the implementation for these methods here 😅

**Comment by felixarntz** [comment]
IB ✅ 

@tofumatt 
I'm not sure about requiring `component` as separate parameter before `settings`. Part of me likes the idea, on the other hand we can just as well make it a requirement to pass `settings` and at least include `settings.component`. The main downside of having `component` separate would be that we may in the future add `settings.component` support to `registerWidgetArea` too, and if we had a separate argument for `registerWidget` it may become odd. I think I'd prefer to keep `settings.component` for now.

Regarding where to store the widget components, good point on doing it per store instance - which probably mean also per registry instance in this case (we'd have the store just once per registry). How about instead of `googlesitekit.widgets._widgetComponents[slug] = settings.component` we'd use `registry._widgetComponents`? For our main registry this would then mean `googlesitekit.data._widgetComponents`.

**Comment by tofumatt** [comment]
>  The main downside of having `component` separate would be that we may in the future add `settings.component` support to `registerWidgetArea` too, and if we had a separate argument for `registerWidget` it may become odd. I think I'd prefer to keep `settings.component` for now.

That sounds good. Since it was required and so fundamental I figured separating it would be good, but I like the flexibility offered by `settings`. It would even be easy to change that API after it's shipped, so sounds good to keep it in `settings` for now 👍

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

### Summary

Overall QA looks good. The entrypoint + Asset were not created per the AC but this might not matter at this point as it was added in #1301.

There are a few warnings raised in the tests that ideally should be addressed.

### ACs

* ✅ Add new `js/googlesitekit/widgets/datastore` module that exports a `core/widgets` datastore and `js/googlesitekit/widgets` that for now just imports that. The module will later do more things so it needs to be there in addition to `js/googlesitekit/widgets/datastore`, although right now that's the only surface point.
* ⚠️ The module should have an accompanying entrypoint file `js/googlesitekit-widgets.js` with a PHP handle of the same name.  
**No entrypoint added in `webpack.config` or `Script` defined in `Assets`** These appear to have been added in #1565 though so it's likely not a failure here.
* The store should have the following actions:
    * ✅ `registerWidgetArea( slug, settings )`
    * ✅ `assignWidgetArea( slug, contextSlugs )`
    * ✅ `registerWidget( slug, settings )`
    * ✅ `assignWidget( slug, widgetAreaSlugs )`
* The store should have the following selectors:
    * ✅ `isWidgetAreaRegistered( slug )`
    * ✅ `isWidgetRegistered( slug )`
    * ✅ `getWidgetAreas( contextSlug )`
    * ✅ `getWidgets( widgetAreaSlug )`

### Widget Areas

```
  core/widgets Widget areas
    actions
      assignWidgetArea
        ✓ should implicitly create a context when assigning a widget area, if one does not exist (7ms)
        ✓ should re-use a context if one is already created (2ms)
        ✓ should assign a registered widget area to a context (3ms)
      registerWidgetArea
        ✓ should register a widget area (2ms)
        ✓ requires a slug (16ms)
        ✓ requires settings (3ms)
        ✓ requires a title and subtitle in settings (6ms)
        ✓ should register multiple widget areas (2ms)
        ✓ should use priority: 10 as a default (2ms)
        ✓ should not overwrite an existing widget area (2ms)
    selectors
      getWidgetAreas
        ✓ requires a contextSlug (2ms)
        ✓ returns all registered widget areas (2ms)
        ✓ does not return unregistered widget areas (1ms)
        ✓ returns widget areas that were registered after they were assigned (1ms)
        ✓ returns the widget areas sorted by priority (2ms)
      isWidgetAreaRegistered
        ✓ returns true if the widget area is registered (4ms)
        ✓ returns false if the widget area is not registered (2ms)
```

⚠️ 2 warnings raised in Widget Areas tests:
```
  console.warn node_modules/jest-mock/build/index.js:860
    Could not register widget area with slug "header". Widget area "header" is already registered.

  console.warn node_modules/jest-mock/build/index.js:860
    Could not register widget area with slug "pageviews". Widget area "pageviews" is already registered.
```

### Widgets
```
  core/widgets Widgets
    actions
      assignWidget
        ✓ should assign widgets to a widget area (11ms)
        ✓ should allow assignment of non-registered widgets (4ms)
        ✓ should allow assignment of non-registered widget areas (11ms)
      registerWidget
        ✓ places the widget component in a variable external to the store, with a key from the store (36ms)
        ✓ uses the same WidgetsComponent section when multiple widgets are registered (8ms)
        ✓ does not overwrite an existing widget (6ms)
    selectors
      getWidgets
        ✓ requires a widgetAreaSlug (15ms)
        ✓ should return an empty array when no widgets have been registered (2ms)
        ✓ should return all widgets for a given widgetAreaSlug after they're registered (2ms)
        ✓ should return widgets in the correct priority (3ms)
        ✓ should not return widgets that have been assigned but not registered (2ms)
        ✓ should return widgets that have been assigned before they were registered, once they have been registered (2ms)
      isWidgetRegistered
        ✓ returns true if the widget is registered (2ms)
        ✓ returns false if the widget is not registered (2ms)
```

⚠️ 1 warning raised in Widgets
```
  console.warn node_modules/jest-mock/build/index.js:860
    Could not register widget with slug "widget-1". Widget "widget-1" is already registered.
```

---

@felixarntz what do you think? Should we just address the remaining details here in #1301?

**Comment by felixarntz** [comment]
@aaemnnosttv I opened #1614 to address the QA feedback here. Shouldn't affect the release though since it's only tests, and `googlesitekit.widgets` isn't used yet anyway.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

All previous QA feedback has now been addressed:
* The module should have an accompanying entrypoint file `js/googlesitekit-widgets.js` with a PHP handle of the same name.  
_Also includes missing definition in `externals`_
* All expected warnings raised in tests have been muted

Moving to Approval.
