### ISSUE TITLE
Implement base React components for Widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1300]
## Feature Description

We'll need several base components to enable rendering of widget areas and widgets, that should be part of the `googlesitekit-widgets` module. Most of these components should be internal, while a few should be public (exposed in a `window.googlesitekit.widgets.components`).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Add a `js/googlesitekit/widgets/components` folder to implement the necessary components.
* The following components should be implemented (relying on the `core/widgets` datastore)
    * `WidgetRenderer`
    * `WidgetsRenderer`
    * `WidgetAreaRenderer`
    * `WidgetContextRenderer`
    * `Widget`: This one should also be exposed on the `Widgets` object in a new `components` property, so that it becomes publicly available via `window.googlesitekit.widgets.components.Widget`.
* See the doc for more info on what these components should do and how they should behave.

### Widget Components

Create new components in `js/googlesitekit/widgets/components`.

  * Create a `<Widget>` component that can be used to provide the "default widget appearance". This is, effectively, a component that provides the default padding/styling for a widget. It doesn't take any props. Usage: `<Widget><div>Your website is FAST!</div></Widget>`. Should be available on `googlesitekit.widgets.components.Widget`.
  * Create a `<WidgetRenderer>` component that renders a widget based on a `slug`. It would be `slug` as a prop, from the parent component (`WidgetAreaRenderer`), and would select the relevant widget (from the data store) and output that. Usage: `<WidgetRenderer slug="pagespeed" />`.
  * Create a `<WidgetAreaRenderer>` component that renders a list of widgets. It would be provided the area name as prop, from the parent component (`WidgetContextRenderer`) and would select all relevant widgets registered to this area (using a `getWidgets()` selector) and output them, wrapped in `<WidgetsRenderer>`. Usage: `<WidgetAreaRenderer area="footer" />`.
  * Create a `<WidgetContextRenderer>` component that takes a single prop: `context`. It should select, from the widget datastore, all widgets that are in the `context` supplied (using a `getWidgetContext()` selector). Usage: `<WidgetContextRenderer context="dashboard" />`.

Reading through the widgets Google Doc, I don't think we need `WidgetsRenderer`; `WidgetAreaRenderer` can output all of the `<WidgetRenderer>` components and skip the extra component.

## QA Brief

* 

## Changelog entry

* Introduce base components for upcoming Site Kit Widgets API.

**Comment by felixarntz** [comment]
@tofumatt 
> Because we can't store JS objects in our data store, we'll want to store a reference to the registered component in a JS object, keyed by the `context`, `area`, and `slug` props.

When you say "JS objects" do you mean any objects, or are you referring to specifically classes, component functions etc? This should be added to the #1298 IB then since it's most relevant from there. Regarding keying values outside the datastore, we should be able to only use `slug` since that's the only thing identifying the widget. The data for the same widget in another area wouldn't differ.

> I think the request to change several pages to use this new API as part of this issue might make things a bit too large to track in this issue.

That makes sense. The integration part specifically is also why I didn't want to merge it into `develop`, as it would basically empty out all these areas. I'll reduce the scope of this one to only the basic API pieces and open a separate issue. We can discuss further whether the actual API usages should go in a feature branch or not, but I agree with your other comment in that at least the API itself should go against `develop`.

**Comment by felixarntz** [comment]
The below comments were originally made in issue description by @tofumatt:

### Refactoring

> The existing components for `dashboard` screen, the `dashboard-details` screen, and the `module` screens should be modified [...]

I think the request to change several pages to use this new API as part of this issue might make things a bit too large to track in this issue. Maybe we should start with a _single_ page, or separate out that bit from this issue.

### Widget Registration

> Modify the `core/widgets datastore` module so that it automatically registers a few core widget areas for context dashboard.

Since we won't actually have these widgets available yet, I don't think we should do this in this issue. If you're okay with keeping those pieces out-of-scope for this issue, we can file new issues for those pieces.

### Comments on the long-running branch (`feature/widgets-api`)

We've been using a long-running branch for the work on #1101, and I feel it's lead to siloing of code, a lot of duplicate PRs against `develop`, duplicate/extra effort, and a cognitive load from the feeling that the "long-running" nature of the refactor branch means it will stay open for weeks.

I'd rather not do this again, and instead keep as much of this code in `develop` as possible. We can use feature flags to disable the usage of the components themselves in the UI, ensuring they're not used in production (webpack will actually remove any unused code so it shouldn't even impact bundle size significantly). But keeping our branches small and working from `develop` should reduce the amount of blocking and PRs against multiple branches we've been doing with #1101.

I don't think much of this code—especially for this issue—requires a separate branch. The new approach can live alongside the old one, and especially since we'll be replacing each page piecemeal and not at once, we'll need this to happen at some point.

Instead of working on a long-running branch that requires more upkeep and starts to feel a bit too large, let's try keeping these changes against `develop`.

**Comment by tofumatt** [comment]
Sounds good! I think creating new issues for those pages will help keep these future JSR issues from feeling too big 😄

IB updated; mostly just to remove the reference to JS objects (I meant functions/React components, yes 🙂). I added that to the #1298 IB, so removed it here and this should be good to go 👍

**Comment by felixarntz** [comment]
@tofumatt 
> Should be available on `googlesitekit.components.Widget`.

This should be `googlesitekit.widgets.components` (or internally when writing our own code on `Widgets.components`, where `Widgets` is the object imported from `googlesitekit-widgets`).

> Create a `<WidgetRenderer>` component that renders a widget based on a context, area 
name, and slug. It would be provided `context`, `area`, and `slug` as props

So the idea is that the `WidgetRenderer` based on the prop gets the widget data (e.g. inner component) itself based on the received `slug` prop? I think that makes sense. However, I don't think it needs `context` and `area`. These are solely for determining which widgets to render for the given context/area (as mentioned before, content of a widget would never differ based on where it renders). What was your thinking for including them as props?

> Create a `<WidgetAreaRenderer>` component that renders a list of widgets. It would be provided the `context` name and `area` name as props

Same idea here - I think this should be possible by only passing `area`.

> Create a `<WidgetAreasRenderer>` component that takes a single prop: context

That sounds good, but an idea here: Maybe we should rename this to `ContextRenderer`, or more specifically `WidgetContextRenderer`. This would be more logical alongside the other two `WidgetAreaRenderer` and `WidgetRenderer`, and also with the prop that it would receive. Also you ditched `WidgetsRenderer` in the IB (which I agree with), so the name `WidgetAreasRenderer` now feels a bit odd. It's rendering everything for a widget context, which _is_ multiple widget areas, but given the other component names as well as the prop I think `ContextRenderer` makes more sense. What do you think?

**Comment by tofumatt** [comment]
> This should be `googlesitekit.widgets.components` (or internally when writing our own code on `Widgets.components`, where `Widgets` is the object imported from `googlesitekit-widgets`).

Whoops, I guess I mixed them up. Fixed!

> So the idea is that the `WidgetRenderer` based on the prop gets the widget data (e.g. inner component) itself based on the received `slug` prop? I think that makes sense. However, I don't think it needs `context` and `area`. These are solely for determining which widgets to render for the given context/area (as mentioned before, content of a widget would never differ based on where it renders). What was your thinking for including them as props?

Oh, I guess that's true. If there's no intention of having them render different at all based on those props we can remove them.

> Same idea here - I think this should be possible by only passing `area`.

For a widget's `slug`—which is unique across the entire datatstore—this makes sense. But forcing areas to be unique across contexts will lead to verbose-and-repeated area names. Let's say we have a "Dashboard" context and a "Header" area in that context: to register that we'd need to have a `dashboard` context and a `dashboardHeader` area. That seems a bit verbose and repeated to me. If the aim is to prefix all of the areas and make them unique, then maybe we just need `area` and `slug`? If we're already putting the context's name in the area as a prefix, I don't see it adding a lot of value for us, but it does introduce complexity.

> That sounds good, but an idea here: Maybe we should rename this to `ContextRenderer`, or more specifically `WidgetContextRenderer`. This would be more logical alongside the other two `WidgetAreaRenderer` and `WidgetRenderer`, and also with the prop that it would receive. Also you ditched `WidgetsRenderer` in the IB (which I agree with), so the name `WidgetAreasRenderer` now feels a bit odd. It's rendering everything for a widget context, which _is_ multiple widget areas, but given the other component names as well as the prop I think `ContextRenderer` makes more sense. What do you think?

I like it! That sounds good; I've updated the IB. 👍 I've updated other IBs that make reference to `WidgetAreas` (#1298) as well.

**Comment by felixarntz** [comment]
@tofumatt 
> For a widget's `slug`—which is unique across the entire datatstore—this makes sense. But forcing areas to be unique across contexts will lead to verbose-and-repeated area names.

I see what you mean regarding the name being repeated. The problem is if we change here that widget area slugs are not unique across all contexts (which would be a change from the original plans outlined in the doc and actually is relevant to #1298, which was already approved, more than here), we would also need to account for that when assigning widgets (e.g. assigning to `dashboardSpeed` would assign a widget to that specific area, whereas if it was just `speed`, we would need to provide the context there as well.

I think these slugs _should_ be unique across context areas so that assigning widgets is straightforward as in only requiring to know the widget area it will be added to. When registering a widget area, the decision is yours to say "I want this to be a widget area for only the dashboard" (therefore call it `dashboardSpeed` to clarify) or "I want this to be a widget area that can appear anywhere (therefore call it just `speed`).

**Comment by tofumatt** [comment]
Fair enough! IB updated to just require the area `slug`.

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
After reviewing the new Widget API, I tend to consider this ticket as not done yet. @tofumatt said that afer discussing it with @felixarntz they agreed that by default all widgets need to be wrapped with `<Widget>` component, plus there should be a way to opt-out of it and not to wrap widgets by providing an appropriate option during widgets registeration process. So, once it's done, we can consider this ticket completed.

One more minor feedback: `Widget.test.js` file tests `WidgetRenderer` component - i think we need to rename `Widget.test.js` file to `WidgetRenderer.test.js` to better match its purpose.

**Comment by felixarntz** [comment]
@eugene-manuilov @tofumatt Regarding the alternative wrapping mechanism, @tofumatt and I had decided to work on it as part of a separate issue, I just opened this issue above. Good catch on the incorrect test file name, let's fix that here.

**Comment by tofumatt** [comment]
Good catch! I've submitted a new PR with the fix, thanks for that 😄

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: - All looks good now.
