### ISSUE TITLE
Implement googlesitekit-widgets asset for public widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1301]
## Feature Description

The `js/googlesitekit/widgets` module with a public `googlesitekit-widgets` entrypoint file (and a PHP handle `googlesitekit-widgets`) should be expanded to do more than just include the `core/widgets` datastore (see #1298).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Have `js/googlesitekit/widgets` module export a `Widgets` object with some public API functions (in addition to registering the store from #1298).
* The entrypoint file should import `Widgets` and expose it on a global `window.googlesitekit.widgets`.
* The following functions should be implemented and exposed:
    * `registerWidgetArea( slug, settings )` --> `Data.dispatch( 'core/widgets' ).registerWidgetArea( slug, settings )`, but also assign the widget area if there is `settings.context` or `settings.contexts` (this is a shortcut)
    * `registerWidget( slug, settings )` --> `Data.dispatch( 'core/widgets' ).registerWidget( slug, settings )`, but also assign the widget if there is `settings.widgetArea` or `settings.widgetAreas` (this is a shortcut)
    * `assignWidgetArea( slug, contextSlugs )` --> `Data.dispatch( 'core/widgets' ).assignWidgetArea( slug, contextSlugs )`
    * `assignWidget( slug, widgetAreaSlugs )` --> `Data.dispatch( 'core/widgets' ).assignWidget( slug, widgetAreaSlugs )`
    * `isWidgetAreaRegistered( slug )` --> `Data.select( 'core/widgets' ).isWidgetAreaRegistered( slug )`
    * `isWidgetRegistered( slug )` --> `Data.select( 'core/widgets' ).isWidgetRegistered( slug )`
* See the doc for more details on these functions and how they should behave.

## Implementation Brief

Add the following methods to the `Widgets` object exported in `assets/js/googlesitekit/widgets`:

### Datastore methods

* `registerWidgetArea( slug, settings, areas )`. This would call `Data.dispatch( ‘core/widgets’ ).registerWidgetArea( slug, settings );`, then `Data.dispatch( ‘core/widgets’ ).assignWidget( slug, areas )`
* `registerWidget( slug, settings, contexts )`. This would call `Data.dispatch( ‘core/widgets’ ).registerWidget( slug, settings )`, then `Data.dispatch( ‘core/widgets’ ).assignWidgetArea( slug, contexts )`
* `assignWidgetArea( slug: String, contextSlugs: String | Array )` which will call `Data.dispatch( 'core/widgets' ).assignWidgetArea( slug, contextSlugs )`
* `assignWidget( slug: String, widgetAreaSlugs: String | Array )` which will call `Data.dispatch( 'core/widgets' ).assignWidget( slug, widgetAreaSlugs )`
* `isWidgetAreaRegistered( slug )` which will call `Data.select( 'core/widgets' ).isWidgetAreaRegistered( slug )`
* `isWidgetRegistered( slug )` which will call `Data.select( 'core/widgets' ).isWidgetRegistered( slug )`

## QA Brief

* 

## Changelog entry

* Implement Site Kit widgets API datastore wrapper on `googlesitekit.widgets`.

**Comment by tofumatt** [comment]
Most of these functions are helper functions that will map to the store directly. I realised that the registration of an _actual_ widget will require storing references to the component/function that renders the widget outside of the datastore—because it's an actual function that can't be serialised to JSON. But I think that should happen inside the store and not on the `googlesitekit.widgets` object.

I'll elaborate more on that in #1298. 🙂

**Comment by tofumatt** [comment]
As mentioned in #1300: I don't think we should be developing these features in a long-running feature branch like we did for #1101, but let's leave the discussion of that in #1300 since I brought it up there first 😄

**Comment by felixarntz** [comment]
@tofumatt 
> But I think that should happen inside the store and not on the `googlesitekit.widgets` object.

Agreed. The `googlesitekit.widgets` wrappers shouldn't do anything but call the underlying datastore actions/selectors. I agree with your other comment regarding different arguments from the datastore being confusing. So let's keep them entirely the same and not do anything differently. In other words, all the functions on `googlesitekit.widgets` should _only_ call the datastore functions, passing through the same arguments.

Regarding the (rest of the) implementation brief:
> Create a `assets/js/googlesitekit-widgets.js` file.

This would already have happened during #1298, which should be implemented first. The file just needs to be expanded as you say afterwards, to expose more than the datastore.

> Add the following methods to the `Widgets` object

You're missing two methods :)

> Note that all of these methods take an optional third argument for dependency-injection/testing: `_registry`. This defaults to our global data registry: `Data`/`global.googlesitekit.data`. But they should use a variable to allow better testing.

Let's not add this variable here. This is our public API, so I'd want to avoid clutter, and (more importantly) the API is just a wrapper (especially now as we're getting rid of the extra handling of contexts and widget areas to assign to). This shouldn't ever be tested against _any_ registry; for that we have tests with the actual datastore. I'd almost be inclined to say these functions don't even need tests since they just pass through similar function calls - but it certainly makes sense testing them, which we can easily do by ensuring they act on our main registry, which in a way is even more useful when it comes to testing these functions than having _any_ registry, since coupling to our main registry is de-facto the only thing these functions do.

**Comment by tofumatt** [comment]
I'm still in-favour of adding the DI variables for testing and flexibility, as I generally don't like us tying code too closely to globals—even though that's what this module aims to do, it's easier to test without having to mock globals, and ensuring the actual public, `global`-attached modules behave as-intended is worthwhile.

For instance, testing and ensuring that all of these modules pass through all arguments as intended and dispatch calls to the correct data store is much easier with dependency injection. Many public APIs have internally-intended variables/arguments exposed in JavaScript 😄, my personal favourite being:

<img width="427" alt="Screenshot 2020-04-21 at 02 09 27" src="https://user-images.githubusercontent.com/90871/79814031-2433ac80-8375-11ea-8eaf-05ab0a289749.png">

But I've removed them from the IB for now. We may wish to add these optional, undocumented, internal arguments for testing later, but we can do that then.

**Comment by felixarntz** [comment]
@tofumatt IB looks good to me, however let's combine the `area` and `areas`, and the `context` and `contexts` arguments into one respectively. We're doing the same for `assignWidgetArea` and `assignWidget`, allowing a string or array, so the `registerWidgetArea` and `registerWidget` functions should do that the same way and then just pass through that argument if it is provided.

**Comment by tofumatt** [comment]
Ah, good call. I've made the change. I also removed the object arguments in that case, because there aren't one-or-the-other arguments. 👍

**Comment by felixarntz** [comment]
IB ✅
