### ISSUE TITLE
Migrate PageSpeed Insights content area in dashboard to use Widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1302]
## Feature Description

This is the first out of a few Site Kit module components to migrate to use the new Widgets API. Let's use this one as a test against our own API, to see whether it works as expected. We can expect some minor changes to the Widgets API itself to become necessary as part of working on this.

Further issues to migrate the other Site Kit modules' content areas will be opened once this one has been completed. Once this issue is ready, we should be able to consider our Widgets API stable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Refactor the PageSpeed Insights module directory per the following:
* Add a `js/modules/pagespeed-insights/components` folder for any new components.
* Re-implement the existing `DashboardSpeed` component as a standalone widget fully relying on the datastore.
    * Use the necessary components from `window.googlesitekit.widgets.components` (via importing from `Widgets.components` during development). If you need anything here that is not exposed on that object, maybe it should be - let's evaluate on a case-by-case basis.
    * Rely on existing datastores for any information you may need (like `modules/pagespeed-insights` and `core/site`).
    * The most outer component that will actually be passed as `settings.component` during widget registration should for example be able to determine whether it needs to render the actual widget content or the blue "Set up PageSpeed Insights" CTA via the datastore (this logic to differentiate is currently "hard-coded" in `js/modules/pagespeed-insights/index.js`). Again, if there is a selector missing here, let's discuss adding it to a proper place.
* The existing/old components here should be deleted, and the filters in the module's `index.js` files should be replaced with a call to `Widgets.registerWidget( 'pagespeedInsightsWebVitals', settings )`, and it should be assigned to render in the widget area `dashboardSpeed` and `pageDashboardSpeed`.

## Implementation Brief

As mentioned in #1392, this work should be done against `develop` with the use of feature flags.

* To enable access to WordPress user capabilities (needed by widget, and later by several other things too):
    * Modify `Permissions` class to add a filter to `googlesitekit_user_data`, which should amend the object passed to JS with a `permissions` object, that includes all primitive Site Kit capabilities as key and the result of `current_user_can( $cap )` as value.
    * Add selector `getCapabilities()` to `core/user` store, with a resolver that populates the initial store state with permissions from `global._googlesitekitUserData.permissions` and just returns that object (or `undefined` if not yet loaded).
    * Add selector `hasCapability( capability )` to `core/user` store, which calls `getCapabilities` and then checks for the passed cap and returns `true|false` (or `undefined` if not yet loaded).
* Move `js/modules/pagespeed-insights/dashboard/dashboard-cta.js` to `js/modules/pagespeed-insights/components/DashboardPageSpeedCTA.js`, rename the component accordingly and migrate its global access to use the datastore (via `core/modules` store's `getModule( 'pagespeed-insights' )` and `core/user` store's `hasCapability( 'googlesitekit_manage_options' )`).
    * Update reference in `js/modules/pagespeed-insights/index.legacy.js`.
* Create a `js/modules/pagespeed-insights/components/DashboardPageSpeedWidget.js` file with corresponding component.
    * If PSI module is not active or not set up (via `core/modules` store's `getModule( 'pagespeed-insights' )`), return the `DashboardPageSpeedCTA`.
    * Otherwise, return the `Widget` component (accessed via `Widgets.components.Widget`, which will resolve to `global.googlesitekit.widgets.components.Widget` in production code) with the `DashboardPageSpeed` component inside.
* In `js/modules/pagespeed-insights/index.js`, register the widget via `core/widgets` store's `registerWidget`:
    * Use slug `pagespeedInsightsWebVitals`.
    * Pass the new `DashboardPageSpeedWidget` component.
    * Pass `WIDGET_WIDTHS.FULL` as width.
    * Pass `wrapWidget: false` (see #1724).
* After the register call, also assign the widget via `core/widgets` store's `assignWidget`, to widget areas `dashboardSpeed` and `pageDashboardSpeed`.

## QA Brief

* The existing PSI widget should be available unchanged.
* The development build should include the same PSI widget like the original one (in the new widget areas, above the current ones).
    * The UI for the new widget is currently broken (see https://github.com/google/site-kit-wp/pull/1766#pullrequestreview-454437619), **this is expected right now** (this will be fixed via #1678, and since this widget is not in production build, it's okay). In order to preview what it actually looks like, for now inspect the DOM element `.googlesitekit-widget.googlesitekit-widget--pagespeedInsightsWebVitals` and add two extra classes `mdc-layout-grid__cell mdc-layout-grid__cell--span-12`.

## Changelog entry

* Migrate PageSpeed Insights widget to use the new Site Kit widgets API.

**Comment by felixarntz** [comment]
@tofumatt 
> Create a `js/modules/pagespeed-insights/components` folder

I know this is in the AC, but we're currently not using this approach for Site Kit modules, maybe we should do this throughout. All modules that have already refactored components have them all in some arbitrary folders in the module root folder, alongside `datastore`. Maybe we should change this for all modules so that the root becomes only:
* `components`
* `datastore`
* `util` (if needed)
* `index.js`
* `index.legacy.js` (until ready to be removed)

All other current directories there (which contain components) would be moved into the module's `components` folder. What do you think?

> Remove [...] `assets/js/modules/pagespeed-insights/settings`

This holds already refactored components for the settings UI of PSI, so it shouldn't be removed. If we do the above, that folder should be moved to `assets/js/modules/pagespeed-insights/components/settings`.

**Comment by tofumatt** [comment]
Oh, the `components/` folder everywhere sounds good 👍  I mentioned moving items for this module into that folder in the IB.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
With #1636 moving forward as high priority, this issue should be considered blocked. We should implement the new widget using the datastore as part of #1636, so the scope here will be reduced, as it's only going to be about migrating that new widget to the actual Widgets API infrastructure.

**Comment by felixarntz** [comment]
Moving back to IB for later, since this will need more simpler IB after #1636.

**Comment by felixarntz** [comment]
@tofumatt Wrote a new IB for review. The estimate is a bit smaller than originally since the main component itself was already refactored as part of the web vitals updates.

**Comment by tofumatt** [comment]
I think we should use full selector names for `getCaps` and `hasCap`. It took me some time to figure out what they meant, and I eventually gave up and then kept reading the IB… but I think that's a bad sign for discoverability and readability 😄

Let's go with `getCapabilities()` and `hasCapability()` so it's clearer the intent of those selectors.

That said, is there any reason not to name them `permissions` rather than `capabilities`? It's easier to reason about and we already have `getPermissionScopeError()` as a selector, so how about `getPermissions()` and `hasPermission()`?

---

Otherwise this looks good, so if changing the selector names is the only change needed and you're cool with that, IB ✅ and feel free to move this right into execution. 🙂

**Comment by felixarntz** [comment]
@tofumatt I've updated the IB to use the full `getCapabilities` and `hasCapability`.

The reason to use the term "capability" is that this is what is the common term to use in WordPress. Essentially:
* "Permissions" --> Google service / API permissions
* "Capabilities" --> WordPress user permissions

**Comment by cole10up** [comment]
**Tested**

Checked npm run build version:

Remains unchanged:
![image](https://user-images.githubusercontent.com/57115907/88629892-b0382d00-d064-11ea-86ad-f4e566df6b7f.png)

Checked npm run build:
![image](https://user-images.githubusercontent.com/57115907/88755775-bb4b9580-d116-11ea-89fe-a8c0095a91aa.png)

Noticed the layout is a bit messy

Added @eugene-manuilov to https://dynamic-roadrunner.jurassic.ninja/wp-admin

Sending back for an adjustment

**Comment by cole10up** [comment]
**Tested**

Checked npm run build version:

Remains unchanged:
![image](https://user-images.githubusercontent.com/57115907/88756426-76286300-d118-11ea-9e2c-51cdbd2664a8.png)

Installed and activated build running npm run build:dev

![image](https://user-images.githubusercontent.com/57115907/88756032-4d539e00-d117-11ea-8d14-f8ffc8ca98ec.png)

Added @eugene-manuilov to https://dynamic-roadrunner.jurassic.ninja/wp-admin/

Sending back for an adjustment
