### ISSUE TITLE
Daily traffic graph in dashboard widget

### ISSUE THREAD

**Issue by DustinWStout** [google/site-kit-wp#1304]
## Feature Description

As a publisher, I need to see my traffic trends from day to day. A simple numeric value with +/- percentage is not helpful for monitoring the daily health of my businesses. It has happened multiple times where there was a sudden drop in traffic due to an issue and I was unaware of it for a couple of days because I didn't have access to a graph that would show me there was a problem.

I've taken the time to create a mockup to show what I mean:

<img width="505" alt="Screen Shot 2020-03-27 at 8 46 18 AM" src="https://user-images.githubusercontent.com/2152604/77774113-c925c880-7007-11ea-9d0a-3a53695c1f10.png">

The current dashboard widget (numbers only) would have just showed me that traffic was up by 332.4% and I would have thought, "Oh good... we're doing great!"

It wouldn't have showed me that traffic had completely stopped the last 4 days and I'd continue to lose traffic until I make time to click through to the Analytics tab inside the SiteKit admin menu OR open up Google Analytics itself. I don't typically have time to do this every day because there are just too many things on my task list. 

So a simple graph in the dashboard widget would be a **HUGE** value. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by DustinWStout** [comment]
Bumping this up again because it seems like the only enhancements/additions happening to the plugin are ones that **no publisher is asking for**.

**Comment by jamesozzie** [comment]
@DustinWStout Many thanks for the suggestion, along with supporting context. I've categorised your feature request now. Rest assured all such suggestions do get considered and discussed. We can keep you notified here with any further updates.

**Comment by gmmedia** [comment]
I would also like to see that.
