### ISSUE TITLE
Low Google PageSpeed score with active SiteKit.

### ISSUE THREAD

**Issue by ghost** [google/site-kit-wp#1307]
**#1274 <--
#1283** <--

@jamesozzie @ernee 
I found PageSpeed both with the plugin active and with the plugin disabled, it shows a significant change in performance.
It influences. How can we solve it? Maybe it's the CSS / JS of the plugin ...

I also opened a report on the support Wordpress forum: https://wordpress.org/support/topic/google-site-kit-wp-low-google-pagespeed-score-with-active-sitekit-1283/#post-12593553

In this discussion there is a zip file attached: screencast.zip, on the forum I don't know if it is possible to attach files.

These are videos from the my Website with Google Site Kit and without Google Site Kit...
**-->** 
**### [Screencast.zip](https://github.com/google/site-kit-wp/files/4397392/Screencast.zip)**

**Comment by jamesozzie** [comment]
If you'd like us to investigate your site feel free to [open a new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) in the WordPress support forums, where we provide support for such queries. 

Note also that while we are continuously making improvements where possible to Site Kit performance it's worth doing some performance checks when manually connecting the various Google products compared to using Site Kit to connect your site to the various Google services it supports. The plugin doesn't add any performance impacting code to a users site as evident by checking your sites source code before installing Site Kit and after connecting Site Kit, with just the Search Console mode active upon installation. You'll notice only a meta tag added to your sites source code, and no Site Kit specific http requests made when using your browsers developer tools as a non logged in user.
