### ISSUE TITLE
Review Tag Snippet Placements

### ISSUE THREAD

**Issue by ghost** [google/site-kit-wp#1310]
## Feature Description

The Tag Assistant [Chrome extension](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en) highlights Site Kits Analytics insertion as a "non standard implementation", as per screenshot below. 

This links to a [support center article](https://support.google.com/tagassistant/answer/3207128?ref_topic=2947092#nonstandard). 

![image](https://user-images.githubusercontent.com/41326532/78130835-ebf21b80-7411-11ea-9f49-12ecbf021907.png)

You could make the script code in the header file (Google Analytics, AdSense, etc) go to the footer.php file as low as possible, but before the `<body>` tag. By doing so, the sites save a few milliseconds or even a second.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by sviluppomania** [comment]
@jamesozzie @ernee

**Comment by jamesozzie** [comment]
@sviluppomania Thanks for the suggestion. You'll find information on the suggested placement the snippets below. Site Kit uses these suggestions as per product best practices guidelines.
- [AdSense](https://support.google.com/adsense/answer/9274516?visit_id=637211676115594559-1486183102&rd=1)
- [Analytics](https://support.google.com/analytics/answer/1008080?hl=en)

The various product snippet placements are subject to change, and we can revisit if necessary.

**Comment by sviluppomania** [comment]
@jamesozzie Will you change the positions suggested by my post?

**Comment by jamesozzie** [comment]
@sviluppomania The most appropriate snippet placement is used as per the different product guidelines at present. I can confirm with the team and report back to you here.

**Comment by sviluppomania** [comment]
@jamesozzie Reading many positioning guides of the various tags: adsense, analytics and many others (even not from Google) show a performance improvement from milleseconds if not a 1 second improvement!

**Comment by jamesozzie** [comment]
@sviluppomania Thanks for the input. I've reopened this support topic and added some details to it for the team to review. Many thanks for the suggestion.

**Comment by sviluppomania** [comment]
@jamesozzie The suggestion also concerns other snippets and not just Analytics.
Will others be moved too? Eg Google AdSense etc?

**Comment by sviluppomania** [comment]
@jamesozzie

**Comment by jamesozzie** [comment]
@sviluppomania There is no guarantee the snippets will be moved, we will however review all the snippet placements in relation to ensure best practice.

**Comment by sviluppomania** [comment]
> @sviluppomania There is no guarantee the snippets will be moved, we will however review all the snippet placements in relation to ensure best practice. 

We do know, however, that snippets cause a big slowdown.  They should be moved as low as possible, perhaps in the footer before the <body> tag, as expected by many guides around the web.  The tags that affect a lot are those of Google Analytics and Google AdSense, to follow other active minor snippets.  Moving all these we have an improvement of many milliseconds if not a whole second.

**Comment by sviluppomania** [comment]
@jamesozzie @felixarntz @aaemnnosttv

**Comment by sviluppomania** [comment]
News? 
@jamesozzie 
@felixarntz 
@aaemnnosttv

**Comment by sviluppomania** [comment]
There are news?? @jamesozzie

**Comment by jamesozzie** [comment]
@sviluppomania There are changes to the way the Tag Manager snippet is placed, which you can find out more at #1308. This is scheduled for the next release which is due this week (1.7.1)

While the snippets will not be at the foot Site Kit follows all placement best practices. While you may find conflicting suggestions on placements online the following article explains the correct placement of the tag we use for analytics:  https://developers.google.com/analytics/devguides/collection/gtagjs/

You're also free to use your own placements by manually inserting the Analytics snippets into your site, independent of Site Kit. These snippets will be recognised when setting up the analytics or other modules within Site Kit.

**Comment by sviluppomania** [comment]
@jamesozzie post # 1308 only talks about Tag Manager, while there are also Adsense and Analytics that cause a drop in performance.
