### ISSUE TITLE
Simplify tag-permission datapoint for Analytics module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1316]
The `tag-permission` datapoint for Analytics currently tries to figure out access to a property by looking through properties for all accounts that a user has, which requires issuing as many Analytics API requests as there are accounts for the user. We can instead infer the account ID from the given property ID.

Another change that should be made is that this datapoint should never return an error. Its sole purpose is to check for the permission, so if there is no permission, it should just provide false - but not an error. That error is only relevant for a very specific case, so that should be handled in JS.

Another enhancement, following #1259, is that we'll be able to get rid of supporting unnecessarily an optional `accountID` parameter for the Analytics datastore's tag permission functionality.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics `tag-permission` datapoint...
    * ...should never return an error.
    * ...should only require a `propertyID` parameter.
    * ...should always return an object with `accountID`, `propertyID`, `permission` (boolean).
    * ...should determine the account ID from the property ID (property IDs look like "UA-{accountID}-x").
* The datastore and the existing setup route should be updated for these changes.

## Implementation Brief

* Merge #1317

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz this issue seems partially related to https://github.com/google/site-kit-wp/issues/341 (at least for the existing tag case). Perhaps that issue should be updated to be specific to `matchedProperty` lookup?

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

@felixarntz this looks good, with the exception of the "should never return an error" condition. It will return an error if the `propertyID` is not provided, or is invalid. I think these are acceptable reasons to return an error for this datapoint, but it is technically a conflict with the AC. If you're okay with these exceptions, then 👍

**Comment by felixarntz** [comment]
@aaemnnosttv Right, yeah that still makes sense. I guess the ACs should have said "should not return an error to indicate lack of access"

✅
