### ISSUE TITLE
Stuck at Checking Compatibility... 

### ISSUE THREAD

**Issue by ELkoos** [google/site-kit-wp#1318]
## Bug Description

After installation and activation, the button to start integration process remains inactive, and Site Kit is stuck at Checking Compatibility. Issue persist after 30 minutes of wait.

## Steps to reproduce

Download plugin
Activate it
Tried reinstallation, etc - to no avail

 - PHP Version: 7.3
 - Shared hosting, Wordpress 5.3.2 + Woocommerce 4.0.1
 - Chrome, Firefox
 - newest plugin version from repository
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@ELkoos we're now providing support in the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Feel free to open a topic there and we'll be happy to assist.
