### ISSUE TITLE
Add support for module-specific assets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1319]
Modules should be able to enqueue their own assets. In the long term, every Site Kit module should have its own JS file for its functionality (e.g. Analytics would have `googlesitekit-modules-analytics.js`).

These modules cannot just be dependencies of other modules that need them because...
* ...they're not actually dependencies, but they modify the experience (they are "extensions")
* ...they have to work independently (to support 3P in the future)

Let's introduce a way for modules to enqueue their own assets. Everywhere where loading module assets is relevant, a new API method on `Modules` should be called to take care of that.

Let's also include a secondary small change in this PR (as previously discussed with @aaemnnosttv): `googlesitekit.data` should expose a few more functions from `wp.data`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Modules should be able to enqueue their own assets.
* `googlesitekit/data` should expose the following functions from `@wordpress/data`:
    * `useSelect`
    * `useDispatch`
    * `useRegistry`
    * `RegistryProvider`

## Implementation Brief

* Introduce a `Module_With_Assets` interface with methods:
    * `get_assets()`: Returns array of `Asset` instances.
    * `enqueue_assets()`: Enqueues `Asset` instances as necessary.
* In `Assets`, introduce a filter `googlesitekit_assets` to filter the available assets.
* In `Modules::register()`, hook into that filter to iterate over all modules which implement `Module_With_Assets` and call their `get_assets()` method to amend the filter value.
* Introduce a new public method `Modules::enqueue_assets()`:
    * This method should iterate through all modules that implement `Module_With_Assets` and call the above method `enqueue_assets()`.
* In areas where we enqueue assets, `Modules::enqueue_assets` should be called. If not yet available, the `Modules` instance should be passed to these classes in the constructor. Here are the classes to cover:
    * `Google\Site_Kit\Core\Admin\Dashboard`
    * `Google\Site_Kit\Core\Admin\Screens`
    * `Google\Site_Kit\Core\Admin_Bar\Admin_Bar`
* In `assets/js/googlesitekit/data`, add the four functions from the ACs to the import list from `@wordpress/data`, and then export them on the `Data` object.

## QA Brief

* 

## Changelog entry

* Allow modules to register and enqueue their own assets by implementing a `Module_With_Assets` interface.

**Comment by aaemnnosttv** [comment]
I think the `Module_With_Assets` interface should define a `get_assets` method (this is consistent with many of the other interfaces as well. In this case, `Modules` should also call this during its `register` method to make sure all module assets are registered.  This is important to support dependencies between assets.

For enqueuing, we may want to provide a parameter to the module for it to know whether it is active or not (perhaps `Module` should get an `is_active` method instead?), as an active module may likely require additional/alternate assets than an inactive one. As we discussed, there are cases where it makes sense for an inactive module to register things on the client.

As for `Assets $assets` being passed to the enqueue method, would we then call `$assets->enqueue_asset( $handle )` for each? This method actually seems unnecessary. Assets should enqueue and work the same regardless of how they're enqueued (either using this class, or as a dependency, etc).

Here's what I'm thinking
* Add `Module_With_Assets::get_assets(): Asset[]`
* `Modules` calls `Module::get_assets()` for each `Module_With_Assets` during its `register` (active or not) and calls `Asset::register()` for each
* Add `Module::is_active` for the module to be activation-aware
* `Modules::enqueue_assets()` is called where needed, calls `Module::enqueue_assets()` for each available `Module_With_Assets` (I don't think `Assets` is necessary to be passed here - our assets should always be registered, and they will be enqueued as dependencies if needed 😄 )

Let me know what you think.

**Comment by felixarntz** [comment]
@aaemnnosttv I like these suggestions overall.

> As for `Assets $assets` being passed to the enqueue method, would we then call `$assets->enqueue_asset( $handle )` for each? This method actually seems unnecessary. Assets should enqueue and work the same regardless of how they're enqueued (either using this class, or as a dependency, etc).

Theoretically yes, but there are some nuances. Specifically, the `before_print` callback mechanism doesn't work if an `Asset` is not actually included in `Assets::$assets`. The rest would all be okay.

I think we could have `Module_With_Assets::register_assets( Assets $assets )` and `Module_With_Assets::enqueue_assets( Assets $assets )` (we'd also need to introduce a `Assets::register_asset( Asset $asset )` method to enable registration from the outside). The reason to use that is
1. the above "requirement" to go through `Assets` to properly support our `Asset`-based assets
2. that it would even allow someone (3P) to handle this completely separately (if they don't want to bother with our interfaces, they could also use e.g. `wp_register_script` and `wp_enqueue_script` directly).

The alternative from my POV would be to force using our mechanism and have `Module_With_Assets::get_assets()` and something like `Module_With_Assets::get_asset_handles_to_enqueue()`. That would be more restrictive, but in another way more true to our APIs and it would tie in better with other similar interfaces.

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv Actually, let's do it like you've suggested: The missing piece to accomplish there was a filter in `Assets` to allow for more assets to be registered.

Let's introduce a filter `googlesitekit_assets` on that list, then hook into that in `Modules` and collect the module assets via `Module_With_Assets::get_assets()`. Then, for enqueuing, we can use `Modules::enqueue_assets()` which calls all necessary `Module_With_Assets::enqueue_assets()`.

**Comment by felixarntz** [comment]
@aaemnnosttv I've updated the IB accordingly.

Regarding whether the module is active or not, that's a good point, but let's deal with that at a later stage. We don't need that awareness now, as for now all module assets will always be enqueued. Adding a `Module::is_active()` or similar in the future would not be a problem.

**Comment by cole10up** [comment]
Ran regression around basic functionality. Installed and setup SK, connected all modules, confirmed functionality, disconnected modules, disconnected SK, deactivated and removed SK. Reinstalled and confirmed everything remained functional after setup a 2nd time. 

Passed QA ✅
