### ISSUE TITLE
Modules setup components remounting on every user action on the settings page 

### ISSUE THREAD

**Issue by lucymtc** [google/site-kit-wp#132]
## Bug Description

Setup modules components ( TagmanagerSetup, AnalyticsSetup... ) in the settings page are being re-mounted with every action ( expanding settings view, expanding form, canceling editing, saving ) when it should be only re-rendering and not re-mounting.
 
## Steps to reproduce

1. Activate and configure Analytics module. 
2. Add a `console.log( 'did mount' );` inside `componentDidMount` in `AnalyticsSetup` component  https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/setup.js#L88
3. Go to Site Kit > Settings > Connected Services
4. In the console see the console.log message 'did mount' as the component has been mounted. 
3. Click on Analytics to expand, see another message  'did mount' in the console 
4. Click on Edit in the expanded analytics settings, see another message  'did mount' in the console
5. Click on Cancel in the expanded analytics settings form, see another message  'did mount' in the console 

## Additional Context

 - PHP Version: 7.1
 - OS: mac
 - Browser: chrome (all)
 - Plugin Version: Developer beta
 - Device: macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This should no longer be relevant now that these setup components have all been refactored. Please reopen if it still causes problems.
