### ISSUE TITLE
Fix failing e2e test on WordPress 5.4

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1322]
## Bug Description

We seem to have an e2e test that is consistently failing against WordPress 5.4, which was released just a few hours ago. Now I see that the e2e tests against "WordPress latest" are failing which is likely due to a change in that version.

I've experienced this multiple times on different PRs so it's probably something we really need to look into and fix.

FYI actually using Site Kit on WordPress 5.4 has worked without any issues for me, including the admin bar, which is somehow the cause of the e2e test failures. So it looks like the problem is something test-specific that does not affect production code (phew...).

[Here is one of the jobs that have been failing.](https://travis-ci.com/github/google/site-kit-wp/jobs/310848410)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit e2e tests should not fail on WordPress 5.4.

## Implementation Brief

* Introduce utilities to safely toggle `core/edit-post` features  
_Needed to both dismiss the welcome guide (no useful selectors to use from browser) and to disable fullscreen mode which is the default as of WP 5.4_
* Merge #1324 

## QA Brief

* E2E tests all pass

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
It's due to the new default editor view which is now full screen (hence the admin bar not being visible) but also due to the overlay which is blocking the hover state.
https://make.wordpress.org/core/2020/03/03/fullscreen-mode-enabled-by-default-in-the-editor/

![image](https://user-images.githubusercontent.com/1621608/78110585-e1308a00-7403-11ea-9d0c-a297171bf8fd.png)

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Confirmed latest change on an older version of WP:

<details>
  <summary>Click to expand results on WP 4.9.13</summary>
  
`Coles-MacBook-Air:google-site-kit cole$ WP_VERSION=4.9.13 npm run env:start

> googlesitekit@ env:start /Users/cole/Local Sites/googlekitlocal10uplabscom/app/public/wp-content/plugins/google-site-kit
> ./bin/local-env/start.sh

STATUS: Stopping Docker containers...
STATUS: Downloading Docker image updates...
Pulling mysql     ... done
Pulling wordpress ... done
Pulling cli       ... done
STATUS: Starting Docker containers...
Creating network "googlesitekit-e2e_default" with the default driver
Creating googlesitekit-e2e_mysql_1 ... done
Creating googlesitekit-e2e_wordpress_1 ... done
Creating googlesitekit-e2e_cli_1       ... done
STATUS: Attempting to connect to WordPress......
STATUS: Downloading WordPress version 4.9.13...
STATUS: Installing WordPress...
STATUS: Creating additional users...
STATUS: Admin 2 created! Username: admin-2 Password: password
STATUS: Editor created! Username: editor Password: password
STATUS: Author created! Username: author Password: password
STATUS: Contributor created! Username: contributor Password: password
STATUS: Creating a few posts...
[02-Apr-2020 15:22:00 UTC] PHP Notice:  compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:00 UTC] PHP Notice:  compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:00 UTC] PHP Notice:  compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
STATUS: Created post with title "Hello Solar System!"
[02-Apr-2020 15:22:01 UTC] PHP Notice:  compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:01 UTC] PHP Notice:  compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:01 UTC] PHP Notice:  compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
STATUS: Created post with title "Hello Milky Way!"
[02-Apr-2020 15:22:02 UTC] PHP Notice:  compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:02 UTC] PHP Notice:  compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:02 UTC] PHP Notice:  compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
STATUS: Created post with title "Hello Universe!"
[02-Apr-2020 15:22:04 UTC] PHP Notice:  compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: context in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:04 UTC] PHP Notice:  compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: ID in /var/www/html/wp-includes/post.php on line 3387
[02-Apr-2020 15:22:04 UTC] PHP Notice:  compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
Notice: compact(): Undefined variable: filter in /var/www/html/wp-includes/post.php on line 3387
STATUS: Created post with title "Hello Spéçïåł čhāràćtęrß!"
STATUS: Ensuring that files can be uploaded...
STATUS: Current WordPress version: 4.9.13...
STATUS: Checking the site's url...
STATUS: Installing a dummy favicon...
STATUS: Activating Google Site Kit plugin...
STATUS: Setting permalink structure...
[02-Apr-2020 15:22:12 UTC] PHP Warning:  md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
Warning: md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
[02-Apr-2020 15:22:12 UTC] PHP Warning:  md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
Warning: md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
STATUS: Configuring site constants...
STATUS: WP_DEBUG: false...

Welcome to...

Google Site Kit

Run npm run dev to build the latest version of the Google Site Kit plugin,
then open [02-Apr-2020 15:22:18 UTC] PHP Warning:  md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
Warning: md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
http://localhost:9002 to get started!


Access the above install using the following credentials:
Default username: admin, password: password`

</details>

Confirmed all tests passed on WP 5.4 (current)

<details>
  <summary>Click to expand results on WP 5.4</summary>
  
`Coles-MacBook-Air:google-site-kit cole$ WP_VERSION=5.4 npm run env:start

> googlesitekit@ env:start /Users/cole/Local Sites/googlekitlocal10uplabscom/app/public/wp-content/plugins/google-site-kit
> ./bin/local-env/start.sh

STATUS: Stopping Docker containers...
STATUS: Downloading Docker image updates...
Pulling mysql     ... done
Pulling wordpress ... done
Pulling cli       ... done
STATUS: Starting Docker containers...
Creating network "googlesitekit-e2e_default" with the default driver
Creating googlesitekit-e2e_mysql_1 ... done
Creating googlesitekit-e2e_wordpress_1 ... done
Creating googlesitekit-e2e_cli_1       ... done
STATUS: Attempting to connect to WordPress.....
STATUS: Downloading WordPress version 5.4...
STATUS: Installing WordPress...
STATUS: Creating additional users...
STATUS: Admin 2 created! Username: admin-2 Password: password
STATUS: Editor created! Username: editor Password: password
STATUS: Author created! Username: author Password: password
STATUS: Contributor created! Username: contributor Password: password
STATUS: Creating a few posts...
STATUS: Created post with title "Hello Solar System!"
STATUS: Created post with title "Hello Milky Way!"
STATUS: Created post with title "Hello Universe!"
STATUS: Created post with title "Hello Spéçïåł čhāràćtęrß!"
STATUS: Ensuring that files can be uploaded...
STATUS: Current WordPress version: 5.4...
STATUS: Checking the site's url...
STATUS: Installing a dummy favicon...
STATUS: Activating Google Site Kit plugin...
STATUS: Setting permalink structure...
[02-Apr-2020 15:28:46 UTC] PHP Warning:  md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
Warning: md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
[02-Apr-2020 15:28:47 UTC] PHP Warning:  md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
Warning: md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
STATUS: Configuring site constants...
STATUS: WP_DEBUG: false...

Welcome to...

Google Site Kit

Run npm run dev to build the latest version of the Google Site Kit plugin,
then open [02-Apr-2020 15:28:52 UTC] PHP Warning:  md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
Warning: md5_file(/var/www/html/wp-content/plugins/google-site-kit/dist/assets/js/e2e-utilities.js): failed to open stream: No such file or directory in /var/www/html/wp-content/mu-plugins/e2e-assets.php on line 23
http://localhost:9002 to get started!


Access the above install using the following credentials:
Default username: admin, password: password`

</details>

Passed QA ✅
