### ISSUE TITLE
Connection Loop/error after clicking on proceed: Loading chunk 0 failed

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1323]
## Bug Description
After attempting to install Site Kit (version 1.6.0) for the first time on a particular site setup will not proceed, taking the user back to the setup screen. The error encountered is described below:

WordPress Support Topic:
https://wordpress.org/support/topic/connection-loop 

Additional related support topics:
- https://wordpress.org/support/topic/site-kit-verify-site-ownership-error/ (RESOLVED)
- https://wordpress.org/support/topic/site-kit-verify-site-ownership-loop/ (RESOLVED)
- https://wordpress.org/support/topic/proceed-loop-error-fixed/ (RESOLVED)
- https://wordpress.org/support/topic/verify-site-ownership-proceed-button-loops/ (RESOLVED)
- https://wordpress.org/support/topic/i-cant-connect-with-sit-kit/ (RESOLVED)
- https://wordpress.org/support/topic/loop-when-verifying-site-ownership/ (RESOLVED)

```
Loading chunk 0 failed. (error: https://theguyinthekitchen.com/wp-content/plugins/google-site-kit/dist/assets/js/chunk-googlesitekit-adminbar~chunk-googlesitekit-setup-wizard~chunk-googlesitekit-setup-wizard-proxy-7b6a86fd3073896743e0.js)

    in Unknown
    in Suspense
    in DashboardSplashApp
    in ErrorHandler
    in GoogleSitekitDashboardSplash
```

Site Health information
```
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: America/Toronto
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /path/to/theguyinthekitchen.com
wordpress_size: 37.86 MB (39701123 bytes)
uploads_path: /path/to/theguyinthekitchen.com/wp-content/uploads
uploads_size: 1.56 MB (1639164 bytes)
themes_path: /path/to/theguyinthekitchen.com/wp-content/themes
themes_size: 1.97 MB (2065890 bytes)
plugins_path: /path/to/theguyinthekitchen.com/wp-content/plugins
plugins_size: 48.65 MB (51013016 bytes)
database_size: 3.48 MB (3653632 bytes)
total_size: 93.53 MB (98072825 bytes)

### wp-active-theme ###

name: Hello Elementor (hello-elementor)
version: 2.2.2
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
parent_theme: none
theme_features: menus, post-thumbnails, automatic-feed-links, title-tag, html5, custom-logo, editor-style, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /path/to/theguyinthekitchen.com/wp-content/themes/hello-elementor

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.1, author: the WordPress team

### wp-plugins-active (9) ###

Advanced Custom Fields: version: 5.8.9, author: Elliot Condon
Classic Editor: version: 1.5, author: WordPress Contributors
Custom Post Type UI: version: 1.7.4, author: WebDevStudios
Elementor: version: 2.9.7, author: Elementor.com
Elementor Pro: version: 2.9.2, author: Elementor.com
Enable Media Replace: version: 3.3.11, author: ShortPixel
Rank Math SEO: version: 1.0.41.1, author: Rank Math
Save & Import Image from URL: version: 0.7, author: basteln3rk
Site Kit by Google: version: 1.6.0, author: Google

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.3.16 64bit
php_sapi: cgi-fcgi
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.59.0 OpenSSL/1.0.2r
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.40-84.0-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /path/to/theguyinthekitchen.com/wp-content
WP_PLUGIN_DIR: /path/to/theguyinthekitchen.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### google-site-kit ###

version: 1.6.0
php_version: 7.3.16
wp_version: 5.3.2
reference_url: https://theguyinthekitchen.com
amp_mode: no
site_status: connected-site
user_status: not authenticated
active_modules: site-verification, search-console
required_scopes: 
    openid: ⭕
    https://www.googleapis.com/auth/userinfo.profile: ⭕
    https://www.googleapis.com/auth/userinfo.email: ⭕
    https://www.googleapis.com/auth/siteverification: ⭕
    https://www.googleapis.com/auth/webmasters: ⭕
search_console_property: none
```

Additional info:
- Attempted deactivating all plugins during setup
- Attempted setting up incognito
- Additional info such as console errors & responses within support topic
- First time setup on this site (Site Kit 1.6.0)
- Other websites complete setup fine using same host

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Replicated setup with [all plugins](https://i.imgur.com/nNy80hZ.png) (other than Elementor Pro) setup and active  with default settings. Unable to replicate on personal test site. Escalating to L2

**Comment by jamesozzie** [comment]
Users are able to successfully verify with another Google account in many cases ([Example](https://wordpress.org/support/topic/loop-when-verifying-site-ownership/)). 

Awaiting feedback from users suggesting they check their [site verification](https://www.google.com/webmasters/verification/home?pli=1) with site variations and verified users. 

Updated listed of impacted users in original post, included those with "Resolved" status

**Comment by adamsilverstein** [comment]
Updated description with one additional resolved issue; followed up with two support tickets that are still open.

For this ticket: https://wordpress.org/support/topic/site-kit-verify-site-ownership-loop/ worth noting that the user's site has a forced redirect from {domain} to www.{domain}. This could break the setup flow if the Home url is  {domain}.

**Comment by felixarntz** [comment]
@ernee @jamesozzie Could you create a separate issue for the "loading chunk 0 failed" JS error specifically? The verification loop bug should be fixed shortly.

**Comment by tofumatt** [comment]
I've created several test sites, with all of these plugins installed (aside from Elementor Pro), and haven't been able to replicate this chunk error.

I made sure to use the dashboard to start setup, rather than the "start setup" button directly from the plugins page.

For what it's worth: this was happening before 1.7 so it doesn't seem like #1344 was the cause of this.

But I'm unable to reproduce the issue. If anyone finds more explicit steps, I can give it another go.

**Comment by jamesozzie** [comment]
@tofumatt For the [original support topic](https://wordpress.org/support/topic/connection-loop/) the fix Felix applied on the proxy seems to have resolved this issue. I'll create separate issue for the JS related error. 

We're awaiting confirmation from 2 other impacted users mentioned in this thread, suggesting they reattempt setup.

**Comment by jamesozzie** [comment]
Marking as resolved, with all users referenced either confirmed as resolved or non responsive.
