### ISSUE TITLE
Blank dashboard after Analytics/AdSense connection: Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1325]
## Bug Description
Using the latest version of the plugin connecting the Analytics or AdSense modules results in a blank dashboard. This dashboard error I suspect appears where the "Congrats on completing the setup for ..." appears, as the status for all modules show "connected" from the users Site Health information

WordPress Support topic:
https://wordpress.org/support/topic/blank-page-when-trying-to-activate-adsense-or-analytics-or

Additional information:
- Site Kit version 1.6.0
- All modules "Connected"
- Analytics tracking code exists on site already
- No Auto ads code exists in source code (despite module status "connected")
- Single ad unit code placed on site already (via Theme option, not Site Kit)

![image](https://user-images.githubusercontent.com/41326532/78126071-d678f380-7409-11ea-905f-b1e3fb615edb.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by cole10up** [comment]
Installed all plugins and mimicked settings of the user here: https://wordpress.org/support/topic/blank-page-when-trying-to-activate-adsense-or-analytics-or/

![image](https://user-images.githubusercontent.com/57115907/78326600-a88dcf00-752f-11ea-90eb-182802465ee4.png)

Unable to reproduce the error after installing, activating Adsense and Analytics with all plugins active, sending over to level 2.

<details>
  <summary>Site health info</summary>
  
`
### wp-core ###

version: 5.4
site_language: de_DE
user_language: de_DE
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/users/user65b78522/apps/user65b78522/public
wordpress_size: 44,75 MB (46920027 bytes)
uploads_path: /srv/users/user65b78522/apps/user65b78522/public/wp-content/uploads
uploads_size: 0,00 B (0 bytes)
themes_path: /srv/users/user65b78522/apps/user65b78522/public/wp-content/themes
themes_size: 3,79 MB (3975557 bytes)
plugins_path: /srv/users/user65b78522/apps/user65b78522/public/wp-content/plugins
plugins_size: 111,20 MB (116605122 bytes)
database_size: 2,55 MB (2670592 bytes)
total_size: 162,29 MB (170171298 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.2
author: WordPress-Team
author_website: https://de.wordpress.org/
parent_theme: none
theme_features: post-thumbnails, automatic-feed-links, custom-background, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /srv/users/user65b78522/apps/user65b78522/public/wp-content/themes/twentytwenty

### wp-themes-inactive (2) ###

Twenty Nineteen: version: 1.5, author: WordPress-Team
Twenty Seventeen: version: 2.3, author: WordPress-Team

### wp-plugins-active (44) ###

Activity Log: version: 2.5.2, author: Activity Log Team
AddQuicktag: version: 2.5.3, author: Frank Bültge
Admin Menu Editor: version: 1.9.5, author: Janis Elsts
Ads.txt Manager: version: 1.2.0, author: 10up
Advanced Ads: version: 1.17.8, author: Thomas Maier, Advanced Ads GmbH
Advanced Database Cleaner: version: 3.0.0, author: Younes JFR.
Akismet Anti-Spam: version: 4.1.4, author: Automattic
amr shortcode any widget: version: 3.7, author: anmari
Antispam Bee: version: 2.9.1, author: pluginkollektiv
Classic Editor: version: 1.5, author: WordPress Contributors
Collapse-O-Matic: version: 1.7.11, author: twinpictures, baden03
Companion Plugin: version: 1.11, author: Osk
Content Aware Sidebars: version: 3.11.1, author: Joachim Jensen - DEV Institute
Cookie Notice: version: 1.2.51, author: dFactory
Disable and Remove Google Fonts: version: 1.1.1, author: Fonts Plugin
Easy Add Thumbnail: version: 1.1.3, author: Samuel Aguilera
Elementor: version: 2.9.7, author: Elementor.com
Favicon by RealFaviconGenerator: version: 1.3.17, author: Philippe Bernard
GDPR Cookie Consent: version: 1.8.7, author: WebToffee
Google Adsense Dashboard: version: 2.3, author: Alin Marcu
GS Portfolio for Envato Lite: version: 1.3.1, author: GS Plugins
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Hummingbird: version: 2.4.2, author: WPMU DEV
Iframely: version: 0.7.1, author: Itteco Corp.
Jetpack by WordPress.com: version: 8.3, author: Automattic
LH Archived Post Status: version: 2.20, author: Peter Shaw
LoginPress - Customizing the WordPress Login: version: 1.4.3, author: WPBrigade
Login With Ajax: version: 3.1.10, author: Marcus Sykes
Native Emoji: version: 3.0.1, author: Daniel Brandenburg
Post Expirator: version: 2.4.0.1, author: Aaron Axelsen
SEOPress: version: 3.8.4, author: SEOPress
Show Current Template: version: 0.3.3, author: JOTAKI Taisuke
Site Kit by Google: version: 1.6.0, author: Google
Smart Slider 3: version: 3.3.28, author: Nextend
Smash Balloon Instagram Feed: version: 2.3, author: Smash Balloon
Smush: version: 3.6.1, author: WPMU DEV
URL Shortener by MyThemeShop: version: 1.0.16, author: MyThemeShop
User Role Editor: version: 4.53.1, author: Vladimir Garagulya
Video Embed & Thumbnail Generator: version: 4.6.25, author: Kyle Gilman
WP Comment Policy Checkbox: version: 0.3.2, author: Fco. J. Godoy
WP to Twitter: version: 3.4.4, author: Joseph C Dolson
Yet Another Related Posts Plugin: version: 5.1.2, author: YARPP
Yoast SEO: version: 13.4.1, author: Team Yoast
ZigWidgetClass: version: 0.9.2, author: ZigPress

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Nicht verfügbar
imagemagick_version: Nicht verfügbar
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.4.0-174-generic x86_64
httpd_software: Apache/2.4.41 (Unix) OpenSSL/1.0.2g
php_version: 7.3.16 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 512M
php_post_max_size: 1024M
curl_version: 7.47.0 OpenSSL/1.0.2g
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.29-0ubuntu0.16.04.1-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /srv/users/user65b78522/apps/user65b78522/public/wp-content
WP_PLUGIN_DIR: /srv/users/user65b78522/apps/user65b78522/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### jetpack ###

site_id: false
ssl_cert: No
time_diff: false
version_option: 8.3:1585848707
old_version: 8.3:1585848707
public: Private
master_user: Kein Masterbenutzer festgelegt.
current_user: #1 demo (oskosk+jurassicninja+new+site+created@gmail.com)
tokens_set: None
blog_token: Not set.
user_token: Not set.
version: 8.3
jp_plugin_dir: /srv/users/user65b78522/apps/user65b78522/public/wp-content/plugins/jetpack/
plan: free
HTTP_HOST: running-marine.jurassic.ninja
SERVER_PORT: 443
HTTPS: on
HTTP_X_FORWARDED_FOR: 68.8.26.177
REMOTE_ADDR: 68.8.26.177
protect_header: false
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/running-marine.jurassic.ninja","siteurl":"https:\/\/running-marine.jurassic.ninja","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: [{"name":"test__check_if_connected","pass":false,"message":"Jetpack ist nicht verbunden.","resolution":"connect_jetpack","action":"https:\/\/running-marine.jurassic.ninja\/wp-admin\/admin.php?page=jetpack#\/dashboard","severity":"critical","label":"Your site is not connected to Jetpack","action_label":"Reconnect your site now","description":"<p>A healthy connection ensures Jetpack essential services are provided to your WordPress site, such as Stats and Site Security.<\/p><p><span class=\"dashicons fail\"><span class=\"screen-reader-text\">Error<\/span><\/span> Your site is not connected to Jetpack.<strong> We recommend reconnecting Jetpack.<\/strong><\/p>","group":["default"],"type":"direct"}]

### google-site-kit ###

version: 1.6.0
php_version: 7.3.16
wp_version: 5.4
reference_url: https://running-marine.jurassic.ninja
amp_mode: no
site_status: connected-site
user_status: authenticated
active_modules: site-verification, search-console, adsense, analytics
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/adsense: ✅
	https://www.googleapis.com/auth/analytics: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/analytics.manage.users: ✅
	https://www.googleapis.com/auth/analytics.edit: ✅
search_console_property: https://running-marine.jurassic.ninja/
adsense_account_id: pub-900•••••••••••••
adsense_client_id: ca-pub-900•••••••••••••
adsense_account_status: account-pending-review
adsense_use_snippet: yes
analytics_account_id: 2230••••
analytics_property_id: UA-2230••••••
analytics_profile_id: 1354•••••
analytics_use_snippet: yes

`

</details>

**Comment by aaemnnosttv** [comment]
Based on the error message, it seems that this can be caused by circular dependencies. If that were the cause though, I would expect it to affect everyone.

@jamesozzie it shows the user has Hummingbird Cache installed, which could be causing a problem, depending on how it is configured. Have we asked them to try with all plugins disabled and using a core theme?

I would also be interested to know if it continues to be a problem with 1.7.

**Comment by jamesozzie** [comment]
Safe to close this one, user is now successfully setup. Thanks for the tips @aaemnnosttv
