### ISSUE TITLE
Use webpack for all asset management

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1326]
## Feature Description

We use Webpack for the majority of our asset management (JS and SCSS), but there are still several `gulp` tasks for things like `imagemin` and SVG assets.

Having both `gulp` and `webpack` is redundant, and we should centralise our asset pipeline to use only webpack.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `gulp` and related packages should be removed from the dependencies in `package.json`
* `gulp` tasks should be removed from the repo
* all asset processing should be done by `webpack`
* release task should be removed and use webpack/non-gulp tasks

## Implementation Brief

* Convert all tasks in https://github.com/google/site-kit-wp/blob/develop/gulpfile.babel.js/https://github.com/google/site-kit-wp/blob/develop/gulp-tasks/webpack.js to use webpack. This should have no/little impact on the scripts we run, but they shouldn't rely on `gulp` anymore.
* Remove all `gulp` tasks and dependencies
* The `release` task looks like the most involved one/the task without an obvious Webpack replacement (Imagemin and SVG manipulation should be straightforward): https://github.com/google/site-kit-wp/blob/bc8e51999da45896969e6a88a901f33fc4e9a478/gulp-tasks/zip.js, but converting that to a node+git library script should be straightforward.

Note that all scripts and build processes should be _cross-platform_ and should not be using shell scripts. See discussion in #1784.

It's unclear if changing from `gulp` to `webpack` will necessitate importing images/SVGs from JS files directly rather than referencing their direct URLs, but I suspect it will. So things like https://github.com/google/site-kit-wp/blob/develop/assets/js/util/svg-icon.js#L26 might need to be changed, but seemingly that's one of only a few places we reference SVGs...

## QA Brief

* This is a build/tooling-related change so we mainly need to make sure all images (not svg) continue to render correctly and everything should generally still work as before

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
I'd say while this makes sense, it should be quite low priority - there doesn't seem to be anything which this heavily affects.

**Comment by aaemnnosttv** [comment]
IB ✅ 

We should consider using [`npm-run-all`](https://www.npmjs.com/package/npm-run-all) for better composite command composition as part of this too.

**Comment by tofumatt** [comment]
In light of comments in the PR I've approved this, but someone else needs to merge it. Feel free to have a look at the PR comments and weigh in as well, but even if this doesn't migrate us to a webpack-only pipeline, it's an improvement worth taking.

**Comment by aaemnnosttv** [comment]
@tofumatt there seems to be a bit of ambiguity in the definition of this issue which has led to some confusion in the implementation. Would you please work with @eugene-manuilov to clarify any details around what is still needed here?

**Comment by tofumatt** [comment]
I've amended the IBs to state that a webpack approach is what was intended and that shell scripts/node scripts weren't the intention. Since the ACs say as much, I've updated the IB to remove mention of `node`/`npm`/shell scripts, with everything referencing a Webpack-only approach.

The aim here should be to convert all asset management to rely on the `webpack` command/Webpack pipeline. This means only one build tool, and also means that webpack can track our assets; finding assets we aren't using and refrain from packaging them in the ZIP, and alerting us to missing assets.

The aim should be to convert existing gulp stages (or `npm` stages in the proposed PR, #1784), to files processed by Webpack by modifying the `webpack.config.js` and any JS files that rely on the assets.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov just noting here that the `build:static` command should also no longer be necessary and should be able to be removed after this refactoring is done, but let me know if there's any reason why we might still need it.

**Comment by wpdarren** [comment]
### QA update: Still testing.. 

1. Activated and setup SiteKIt on WP site in develop branch  https://d.pr/i/ozKvqu
2. Connected Google account https://d.pr/i/V4tAjJ
3. Activated all services (Analytics, Adsense, etc.)  
4. Checked images on Dashboard  
5. Checked images on Search Console
6. Checked images on Adsense https://d.pr/i/JSSofL
7. Checked images on Analytics 
8. Checked images on Settings  https://d.pr/i/rlkFwc / https://d.pr/i/nicsEA / https://d.pr/i/KvjuFv

### Environment:

WP 5.5.1 
PHP: 7.3.21
SiteKit: 1.19.0 in Development branch
