### ISSUE TITLE
Implement existing tag detection in core/site datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1328]
## Feature Description

We should have a mechanism to find an existing tag within the `core/site` datastore that replaces the current `getExistingTag()` utility function.

See #1317 for some related comments.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/site` store should have a new `getExistingTag( tagMatchers, options )` selector.
    * `tagMatchers` should be an array of tag matching regexes.
    * `options` should support for now support a single `urls` property which should be an array of URLs to scrape content from to run the regexes against. If not provided or empty, this should default to the `homeURL` or if AMP mode is "secondary" the `homeURL` and a single AMP post URL (similar to how the current `getExistingTag()` works.
    * Overall the selector should behave the same way as the existing utility function, e.g. pass `tagverify` query parameter etc.
* The `core/site` store should probably have an action like `fetchHTML( url )` to fetch the HTML markup string for a certain URL. The `getExistingTag()` resolver could then use that.
* The `getExistingTag()` selectors in the `modules/analytics` and `modules/adsense` stores (plus any other ones if introduced by then) should be modified to use the new `core/site` selector passing their respective `tagMatchers`. The logic around using the old `getExistingTag()` utility function should be removed.

## Implementation Brief

I think the API for the `getExistingTag()` selector should be a bit higher-level, exist on the module stores—not "core/site", and be supported by a private, lower-level `getHTMLforURL()` selector (that gets HTML for a particular URL and saves it in the store for future use).

* Add a `getExistingTag()` selector to the relevant module stores (`modules/analytics`, `modules/adsense`, and others). These will use `Data.select('core/site').getHTMLforURL( url )` under-the-hood to request the site URL, and then run the HTML source against matcher functions. (For now these will match regexes against the HTML source.). Each module will rely on `getExistingTagURLs()` to create a list of URLs to request and a `tagMatchers` array of `RegExp` in each modules' `utils.js` folder to determine if an existing tag is present. (Internally, something like `extractExistingTag( html, tagMatchers )` can be used to check for existing tags and return them if found.)
* The `getExistingTag()` selector should continue to add the query params `{tagverify: 1, timestamp: Date.now()}` to the URLs it uses, as in the existing approach (https://github.com/google/site-kit-wp/blob/af32da2ebb1fda7d69508efae68d69b71e8b34b8/assets/js/util/index.js#L521)
* Add a `getHTMLForURL( url )` selector to `core/site` store that returns the HTML source string for a given URL. It should have a resolver that makes a request to `url`. This resolver can be invalidated when we want to refetch a page's source using the `invalidateHTMLForURL( url )` action (see below). This selector will be private for now, but might be useful to expose in the future.
* Add an `invalidateHTMLForURL( url )` action to the `core/site` store that uses `registry.stores[ STORE_NAME ].getActions().invalidateResolution( 'getHTMLforURL', [url] )` to invalidate the resolver and re-run the `fetch( url )` call.
* Update and add tests for existing `getExistingTag()` selectors in the `modules/analytics` and `modules/adsense` stores The logic around using the old `getExistingTag()` utility function should be removed.

## QA Brief

* The changes affect `adsense`, `analytics` and `tagmanager` modules, so set up test site without those modules set up. And make sure the markup for the home page already has snippets for each of those 3 modules in it (see below).

* Example snippet for analytics in the `<head>` (swap in the account's analytics ID for `${ analyticsID }` ): 
    
      
      <script async src="https://www.googletagmanager.com/gtag/js?id=${ analyticsID }"></script>
	  <script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());
	
	  gtag('config', '${ analyticsID }');
	  </script>

* Example snippet for Adsense in the `<head>` (swap in account's Adsense ID for `${ adsenseID }`):

      <script data-ad-client="${ adsenseID }" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

* Example snippets for TagManager (swap in valid container ID for `${ containerID }`):

  * In `<head>`:

         
		<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
		new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
		j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
		'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
		})(window,document,'script','dataLayer','${ containerID }');</script>
		

  * In `<body>`:

        
	    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=${ containerID }"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	     

* Then set up each of the modules and make sure you can successfully complete the setup and then edit settings.

## Changelog entry

* Simplify detection of existing tags and combine functionality in the JS store.

**Comment by tofumatt** [comment]
Note that I set this to a 19 estimate factoring in the DOMParser work, but it's probably closer to ~11-12 without it. It probably still warrants a 19 either way as they'll be a lot of testing involved, but just flagged that here 😄

**Comment by aaemnnosttv** [comment]
@tofumatt I really like the direction here - 👍 from me.

Regarding the larger design here, it seems a bit odd to me that module-specific tag details would be exposed through the `core/site` datastore. To get an existing tag for a module, we would simply `registry.select( MODULE_STORE ).getExistingTag()` which would select `getHTMLforURL` and could do the necessary parsing in its resolver.

There's of course there's different ways to do this and there's also room for abstraction around the common things that every existing tag request should do, but we should be careful to not impose too much on each. For example, some modules might not care about AMP at all and that would affect which URLs need to be fetched for different modules. Of course the datastore will help with the performance here to not be constantly fetching like we are now but just thinking how to best share things that are common while allowing for flexibility between modules.

Also, don't forget that core technically has its own tag that we use for compatibility checks during the initial setup, so any higher-order `getExistingTag` functionality should not assume a module but something more abstract like a `tagType`.

Thoughts? 😄

**Comment by tofumatt** [comment]
Actually, that's a good point. Maybe we don't want to expose that functionality via the core store at all. Having the fetch actions take place and be saved there seems fine, but I've updated the IB to state we don't need a `getExistingTag()` inside the `core/site` store.

**Comment by felixarntz** [comment]
@tofumatt 
> Add a `getExistingTag( moduleSlug, options )` selector to the relevant module stores

If we plan to deal with this only in the module stores (I like that idea!), then it should continue to be using the parameterless selector `getExistingTag()` we already have right now.

> Add a `getHTMLForURL( url )` selector that returns the HTML source string for a given URL.

That one should be in `core/site` right? I think that makes most sense because it is generic - it's just not entirely clear from the IB.

Adding on to @aaemnnosttv's suggestions, how about we introduce simple utility functions `getExistingTagURLs()`, which returns the URLs to check for existing tags (returns the home URL, plus a post URL if secondary AMP), and `extractExistingTag( html, tagMatchers )`? Then each module's `getExistingTag()` resolver could call `getExistingTagURLs()`, for each of them call `select( 'core/site' ).getHTMLForURL( url )`, then for every `html` string returned call `extractExistingTag( html, tagMatchers )` (where the `tagMatchers` argument is controlled by the module anyway). I think utility functions receiving data for these pieces make most sense, it doesn't need to be all baked into the datastores directly.

Let's not do the `DOMParser` thing for now - while that's worth considering in the future, this issue should be more about refactoring our existing API to better tie in with our datastore and be testable. Let's keep using plain HTML strings for now.

**Comment by tofumatt** [comment]
> If we plan to deal with this only in the module stores (I like that idea!), then it should continue to be using the parameterless selector getExistingTag() we already have right now.

Whoops, my bad. You're right—I forgot to remove the `moduleSlug` from the IB after I updated it to mention putting these in each module store. Updated! 😄

> That one should be in core/site right? I think that makes most sense because it is generic - it's just not entirely clear from the IB.

Yup! That's what I meant but I updated the IB to clarify.

-----

Do you mean adding `getExistingTagURLs()` as a selector? A data store should be used to store application state—which is changeable, non-constant data. In the case of the existing tag URLs, they're a known constant; we know what URLs we want to use for checks for any given module.

But if it's just a simple utility function, not related to the store: yes, that makes sense. How we handle the list of URLs to check and the matchers seems like small detail so I didn't elaborate too much in the IB (it could be a function, a constant, whatever), but I added it as a function that each module's `utils.js` could have for now.

**Comment by felixarntz** [comment]
@tofumatt 
> Do you mean adding `getExistingTagURLs()` as a selector?

I was mentioning it as a utility, I agree it shouldn't be a selector, as well as `extractExistingTag()` should be a utility function. It's similar to the AdSense `determineAccountStatus()` and `determineSiteStatus()`, which are utility functions intended to be used in components alongside datastore hooks, but don't need to be part of the datastore itself, since they only receive arguments, run logic based on them and return a result.

**Comment by felixarntz** [comment]
Regarding the IB:
Let's remove the DOMParser parts, we can see if there's a need for this later - for now it's just about refactoring the API to make it testable.

> Add a `getExistingTag( options )` selector

I don't think there's a need for `options`, this selector should be parameter-less. The module knows the URLs to check through (via `getExistingTagURLs()` utility function) as well as the `tagMatchers` regexes to match (defined internally per module). We shouldn't make our APIs overly flexible for when they don't need to be (we never check different URLs than the ones that `getExistingTagURLs()` would return). Expanding is always possible based on requirements.

> We should maintain an internal list of `tagMatchers` we use to check for tags related to a particular module.

Not fully clear how you mean that. The `tagMatchers` should definitely be defined per module, no code should ever need to pass them to `getExistingTag`. They could easily be in the respective module datastore's `constants.js` file or similar.

> Add a `getHTMLforURL( url )` selector to `core/site` store that returns the HTML source string for a given URL. It should have a resolver that makes a request to `url` with the added `{tagverify: 1, timestamp: Date.now()}` query params added

I don't think the selector itself should modify the `url`. These query parameters are existing-tag-specific details, while this selector is a generic "give me content from the given URL" selector. Instead, the `getExistingTagURLs()` utility function should directly return URLs that have these query parameters appended so they can be passed to `getHTMLForURL` as is (note it should be a capital `F` in `For` per our convention, otherwise it's no longer camel-case).

**Comment by felixarntz** [comment]
@tofumatt You haven't updated all parts of the IB based on my last response, but also didn't reply - could you clarify? My main outstanding point was that there should be no need for an `options` parameter in `getExistingTag`. It will be per module, and the module selector knows everything it needs to know (URLs and tag matchers). Providing `options` here is overkill, we'd never pass it. If we need it at some point, we can easily add it later.

**Comment by tofumatt** [comment]
Sorry about that! As mentioned earlier: I think I typed this up in my code editor and then forgot to submit the new one 😅

Should be good for another review now, will all points addressed.

**Comment by felixarntz** [comment]
@tofumatt 
> Note that, unlike in the existing approach [...] we don't add `{tagverify: 1, timestamp: Date.now()}`.

These query parameters need to remain in use, they're unrelated to us using resolvers.

* The `tagverify=1` is mandatory to ensure Site Kit does not render its own tags for these requests (we don't want to find our own tags as "existing tags"). We can include this query parameter in the URLs returned by `getExistingTagURLs`, since it must always be there for those URLs.
* The `timestamp` parameter is used to try to circumvent caching on certain setups. We always want to have the latest HTML hence add it. Potentially this could be handled within `getHTMLForURL` internally? Since it should never receive cached content, it could just add it to any URL.

Also, nit-pick, but again the name should be `getHTMLForURL`, not `getHTMLforURL` :)

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

Mostly good, but one thing which should be fixed.

* Tested setup of Analytics, Tag Manager, and AdSense using an existing tag with permission and confirmed module setup successfully with existing tag behavior.
* Tested settings view/edit with existing tags with and without permission, and all were detected properly.
  **Note: AdSense does not display the existing tag notice in the Settings view (only edit) unlike Analytics and GTM** (not a regression)
* ⚠️ I noticed that when an invalid tag is detected (e.g. `UA-XXXXX-1` for Analytics) that an `invariant` error is raised. This is a bit of a regression (although unlikely), we should handle this better to prevent these errors from breaking functionality.
