### ISSUE TITLE
Introduce stringifyObject function to use for datastores

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1333]
## Feature Description

Our datastores will often need to store values keyed by the properties that they were retrieved with (e.g. to support selectors with parameters). While we've so far only had simple cases with one or two properties where we would simply concatenate them, this will easily get more complex as we start supporting selectors that accept e.g. `options` objects of various structure. An immediate case where this is needed is the `getReport` selector of the `modules/adsense` datastore (see #1247). Since this is a general enhancement though and will likely be beneficial to other modules (including Analytics), it should be opened against `develop` and then merged back into the feature branches.

We already have a mechanism to stringify objects, which we use in `googlesitekit-api` as well as the old/current `data.js` module. Let's abstract the relevant part out into a `stringifyObject( obj )` utility function which we can reuse throughout.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `stringifyObject( obj )` utility function based on our existing `md5( JSON.stringify( sortObjectProperties( obj ) ) )`.
* All code using the above logic should be modified to use the new utility function.

## Implementation Brief

* Merge #1334.

## QA Brief

* 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅ and code-reviewed, just assigning it to you so you can merge it 😄

**Comment by aaemnnosttv** [comment]
QA ✅
