### ISSUE TITLE
window.googlesitekit.modules.createModuleStore is undefined

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1335]
## Bug Description

As soon as enqueuing one of the new module assets (e.g. from #1224 or #1247) for the first time, I noticed an error in the console that `window.googlesitekit.modules.createModuleStore` is undefined. That is because we currently (in our "old" codebase) already use `window.googlesitekit.modules` to hold module information passed from PHP. That's unfortunate, but we can easily resolve this for the time being by merging the new API object in there.

It's not great, but in the long run the whole old `window.googlesitekit` object will go away, so we'll be fine. It's most important for now to fix this.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `window.googlesitekit.modules.createModuleStore` must not be undefined when `googlesitekit-modules` is enqueued.

## Implementation Brief

* In `googlesitekit-modules.js`: If `window.googlesitekit.modules` is already defined, merge the new API object with the old PHP data object so that both are available.
* Include a TODO comment to remove this at some point.
* Ensure access to legacy module data happens via a specific function `getModulesData` instead of directly accessing the global `googlesitekit.modules`.

## QA Brief

* 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
All reviewed and good-to-merge, just assigning to you to handle the merge 🙂

**Comment by tofumatt** [comment]
All good—assigning to you for merge 😄

**Comment by tofumatt** [comment]
QA ✅

`createModuleStore` no longer fails to load/get added to the existing `googlesitekit.modules` object. 👍

No need for @cole10up to thoroughly test this one as it isn't in any production code.
