### ISSUE TITLE
Fix API.set not passing through data correctly

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1346]
## Bug Description

Our API datapoint routes for `POST` requests expect all data to be within a `data` body parameter. However our new `googlesitekit.api` layer passes all data directly in the body, making all such requests fail.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Data passed to `googlesitekit.api.set` should be sent in a single `data` parameter in the request body.

## Implementation Brief

* Merge #1345.

## QA Brief

* 

## Changelog entry

* Fix bug where `googlesitekit.api.set` would not pass through request data correctly to the API endpoints.

**Comment by tofumatt** [comment]
Covered by #1345; nothing to QA here for @cole10up as this isn't in production code yet, but the requests are being made appropriately in our refactor branches.
