### ISSUE TITLE
All versions of Google reCaptcha in one Plugin.

### ISSUE THREAD

**Issue by ghost** [google/site-kit-wp#1348]
## Feature Description

Hello,
among all the services in the Site Kit I don't see Google reCaptcha ...
It would be the case to insert it giving the possibility to apply a different version from v2 to v3 with the security level from the lowest to the highest.
Thus ensuring less use of third-party plugins and ensuring an excellent service.

Note: Also ensuring the position of the snippets as low as possible. Example: Footer, before the `<body>` tag, ensuring greater site performance and quality of service.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by sviluppomania** [comment]
@jamesozzie @felixarntz @aaemnnosttv

**Comment by jamesozzie** [comment]
@ghost The team will be going through the list of suggestions and feature requests in time. We can keep you posted here once we have any further updates.

**Comment by kaelhoel** [comment]
It would be an absolutely fantastic addition to the Google Site Kit. Please consider adding reCaptcha to the package. :)

**Comment by sviluppomania** [comment]
@jamesozzie Thank you! Please tag my new account for updates.

**Comment by sviluppomania** [comment]
@jamesozzie 

Please add to the post above.
![image](https://user-images.githubusercontent.com/63558798/79687755-cd7d8400-8249-11ea-960a-4e2b416447ae.png)

**Comment by sviluppomania** [comment]
There are news?? @jamesozzie

**Comment by jamesozzie** [comment]
@sviluppomania The team will be reviewing all new request requests in time. As soon as there are any updates you will be notified here.

**Comment by sviluppomania** [comment]
@jamesozzie Please can you insert screenshots in the first post (top). Thank you.

**Comment by jamesozzie** [comment]
@sviluppomania I'm unable to add additional images to original comment, most likely due to permissions. Having said that the full context will be reviewed by the team when considering additional features.

**Comment by sviluppomania** [comment]
Hi @kaelhoel , what do you propose to add / improve? So the request takes on more value and is enriched with suggestions.

**Comment by sviluppomania** [comment]
@jamesozzie news?

**Comment by jamesozzie** [comment]
Hi @sviluppomania. No news just yet, but the team will be reviewing all feature requests in due course.

**Comment by sviluppomania** [comment]
@jamesozzie news?

**Comment by felixarntz** [comment]
Thanks for the request. Site Kit is focused on helping site owners and content creators succeed, with a primary focus on guidance through metrics and insights. While it offers a connection to various Google services, bundling anything related to a Google service into this plugin is out of scope, such requests are reviewed on a case-by-case basis.

reCaptcha falls out of scope and is better be implemented separately from Site Kit, as its use-case and also technical functionality are very different.

**Comment by andreszs** [comment]
If they don't want to add recpatcha to site kit, at least they could create a new, official Google Recaptcha plugin. Each Google service that is applicable to wordpress should have its own official plugin after all.

The current third-party plugins are far from ideal since they flood the WP admin panel with notices, messages and warnings requesting to pay for "premium" features, which are in fact free because Google does not charge for them.
