### ISSUE TITLE
Error Setting Up Google Site Kit

### ISSUE THREAD

**Issue by wpfella** [google/site-kit-wp#1349]
## Bug Description

I installed Google Site Kit plugin by searching the plugin from the Plugins tab in my WP Dashboard. 

Once I installed it, I tried to set it up with my Google account. 

## Steps to reproduce

1. I go to Google Site Kit in the dashboard
2. Click on Start Setup
3. When I click on Start Setup in my WP Dashboard, it takes me to the Google Page which gives information on start setting up the Site Kit for the website and the next screen is where it asks me to choose one of the Google accounts that I have on my device or to sign-in to another Google account.
4. Here, I click on the account that I already have logged in there
5. The next screen it takes me to Accept to allow to share information..
6. Typically, after the above step of accepting a first accept, there are a few other accepts that should come and then it must auto-direct me to the dashboard, but however in my case it just takes me to the WP Login Page (asking me to login in my WordPress Dashboard). So after the first accept, it signs me out from WP Dashboard and takes me to the login page for WP Dashboard.

I have tried a lot of fixes from Sitekit error fixes and none of them worked.

The fixes that are tried are:

1. Change from HTTP to https
2. Try installing it in an incognito window
3. Tried from Macbook and Chromebook
4. Uninstalled a lot of plugins and at one stage, the only plugin I had was Google Site Kit and even then the same error.

I am using the latest WordPress version 5.4 on Siteground hosting with I believe 7.3 PHP version.

My website is a small one-page website built using Hello Theme and Elementor and Elementor PRO page builder. The first time I tried installing site kit, it had Facebook Customer Chat plugin installed, but as said earlier I did try to uninstall all the plugins except Google Site Kit, but still the same error.

At that point, I did not have Cache Plugin (neither third party nor Siteground Optimizer plugin). I removed them too prior to trying this setup.

Can someone suggest anything to help fix this issue?

Adding an update:

1. I delete the whole website and installed a fresh WordPress on the domain and the only thing I tried to do was install Google Site Kit Plugin and set it up (the first thing I did after the fresh WordPress install), but still didn't work.

2. I tried doing a similar thing on a different domain and I could set up the site kit within 120 seconds on that different domain (on the same Siteground hosting).

3. The domain on which I am trying to install site kit was previously added and verified to my same Google account that I am trying to connect to. Could that be an issue? I removed the property from Google Search from my Google Account, so that domain name is no longer a part of my Google Search Property. And now I am unable to connect Google Site Kit with that domain/website.

Any suggestions??

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@wpfella We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist, and possibly reopen this GitHub issue if we can determine a bug. 

Please include your url and [Site Health information](https://i.imgur.com/Rtkmsba.png) in the support topic. If you prefer to share privately you can use [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit) after creating a new support topic.
