### ISSUE TITLE
Avoid push errors in deploy-to-wiki action

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1351]
## Bug Description

Sometimes the `deploy-to-wiki` action fails ([example here](https://github.com/google/site-kit-wp/runs/565234823)) because some changes have been pushed in the meantime. I suspect this can happen when the action is run multiple times concurrently. It has been occurring fairly often, so it would be good to stabilize that part.

For example:
* Either catch an error in the push command, and if it fails pull and merge in the changes.
* Or pull again right before the push.

We could also have some kind of retry mechanism, but my first hunch is that wouldn't help much here. Either way, let's figure out a way to stabilize this action so it causes less errors in PR builds - which also affects the reliability of our QA tester plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `deploy-to-wiki` action should not fail because of a failing `git push` call.
* The action should ensure that the latest code is pulled so that `git push` can succeed.

## Implementation Brief

* Add a `git pull --no-edit --quiet` command in the `deploy-to-wiki` action in `site-kit-wp/.github/workflows/build-pr.yml` [immediately before](https://github.com/google/site-kit-wp/blob/c59ce625e095439c89c7e6da48e3868ba3502b05/.github/workflows/build-pr.yml#L80) pushing. 

## QA Brief

* 

## Changelog entry

* N/A

**Comment by adamsilverstein** [comment]
@felixarntz - Let's try pulling immediately before pushing to see if that resolves the issue. Adjusted IB accordingly.

**Comment by felixarntz** [comment]
IB ✅ 

If we do `git pull` after the commit, we'll need to ensure it gets merged automatically (as in it shouldn't open vim or something).

**Comment by felixarntz** [comment]
@adamsilverstein This still needs an estimate.

**Comment by adamsilverstein** [comment]
> If we do git pull after the commit, we'll need to ensure it gets merged automatically (as in it shouldn't open vim or something).

Good point, updated command in IB to `git pull --no-edit` which should [skip the edit step](https://git-scm.com/docs/git-pull/2.3.5#git-pull---no-edit) in the pull command 

Added an estimate.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

It seems all action runs have succeeded since merging this so seems to be doing the trick 👍 

![image](https://user-images.githubusercontent.com/1621608/78782103-2297db00-79aa-11ea-8360-e8f19b52a7ce.png)
