### ISSUE TITLE
Actions with controls do not invoke reducer

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1361]
## Bug Description

Actions dispatched on a datastore will not trigger the reducer if they have an associated control. The reducer we use has primarily been for setting "has started" state but the issue is more serious in that we've seen it cause components to render improperly as a result.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All actions that have an associated control should have a dedicated action for use in the reducer

## Implementation Brief

* Update all `FETCH_*` actions which have a case in the reducer for setting "doing" state to be generator action creators that also yield a new `{action}_STARTED` type.
* Update the actions referenced in the reducer to use the new `{action}_STARTED` action

## QA Brief

* 

## Changelog entry

* Fix JS datastore actions to never have an associated control and reducer at the same time.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz I think this one can be closed now that #1387 has been merged.
