### ISSUE TITLE
Adjust `analytics_redirect_uri` to use `wp-admin` url.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1362]
## Feature Description

Update the `analytics_redirect_uri` added in https://github.com/google/site-kit-wp/issues/1254 to use a `wp-admin` url.

See: https://github.com/google/site-kit-wp/issues/1357

Similar to the `OAuth_Client::get_redirect_uri ` , the `analytics_redirect_uri` (here - https://github.com/google/site-kit-wp/pull/1315/files#diff-bbaf5b751feff38436021e081d52271cR94) should be modified to use `admin_url( 'index.php' )` instead of `untrailingslashit( home_url() )`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Similar to the `OAuth_Client::get_redirect_uri ` , the `analytics_redirect_uri` (here - https://github.com/google/site-kit-wp/pull/1315/files#diff-bbaf5b751feff38436021e081d52271cR94) should be modified to use `admin_url( 'index.php' )` instead of `untrailingslashit( home_url() )`.

## Implementation Brief

* Modify the URL per the ACs in `Google_Proxy::get_site_fields()`.
* Modify `Analytics::get_provisioning_redirect_uri()` to instantiate a `new Google_Proxy( $this->context )`, call its `get_site_fields()` method and return the `analytics_redirect_uri` value from there. Not super elegant, but at least no more duplicate logic to generate this URL.

## QA Brief

* 

## Changelog entry

* N/A

**Comment by cole10up** [comment]
**Tested**

Installed latest develop, navigated to setup screen and checked the request below:

![image](https://user-images.githubusercontent.com/57115907/80455638-fe605780-88e0-11ea-9517-625ea4a701f7.png)

![image](https://user-images.githubusercontent.com/57115907/80455758-323b7d00-88e1-11ea-88dc-584ae75ffe78.png)

Confirmed positive test setting up functioned. Resetting SK and running through setup functions as well.

Passed QA ✅
