### ISSUE TITLE
Analytics set up with no accounts triggers re-auth notice

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1368]
## Bug Description

Currently when setting up the Analytics module using a Google account that has no Analytics accounts, the "Issue accessing data" notice is displayed when it should not.

The reason for this is that when a data request fails with an error that has a `data.reason: "insufficientPermissions"` in the response, it triggers this notice.

This exception is thrown by the Google API, which returns this response:
```json
{
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "insufficientPermissions",
        "message": "User does not have any Google Analytics account."
      }
    ],
    "code": 403,
    "message": "User does not have any Google Analytics account."
  }
}
```

## Steps to reproduce

1. Set up Site Kit using a Google user that has no Analytics accounts
1. Connect Analytics to initialize the module's set up
1. See error

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/78890682-c34fce80-7a6e-11ea-9dd7-c0427a8ff59d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GET:accounts-properties-profiles` datapoint should return a successful response with empty arrays for each if the user has no accounts
* All error handling for no-accounts cases in client code, E2E mocks, etc should be removed and be updated to use the new count-based logic.

## Implementation Brief

* Update `GET:accounts-properties-profiles` in `Analytics::create_data_request` to return a function that makes the same request in a try/catch block
    * Needs to use `$this->with_client_defer( false )` to dispatch the request immediately
* Only catch `Google_Service_Exception`s (any other will be caught by the default error handler)
* If an exception is caught in the case of no accounts, (exception message === `User does not have any Google Analytics account.` - unfortunately there is not a better identifier for this) then return a new `\Google\Site_Kit_Dependencies\Google_Service_Analytics_Accounts` with its items set to an empty array
* If any other exception is caught, re-throw it
* Update `GET:accounts-properties-profiles` in `Analytics::parse_data_request` to return early (and not request properties-profiles) if `$accounts` are empty
* Update consuming client code, E2E mocks, etc to use the new count-based logic

## QA Brief

* Set up Site Kit with a Google user that has no Analytics account
* Initialize the set up for Analytics
*  The "Issue accessing data" notice should not be displayed
E.g.
![image](https://user-images.githubusercontent.com/1621608/79979159-bdfc7600-84a9-11ea-98c8-36debec60eac.png)

## Changelog entry

* Fix Analytics incorrectly triggering re-authentication notice when the user does not have any accounts.

**Comment by felixarntz** [comment]
@aaemnnosttv Great find - let's prioritize this!

IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz this one is ready for your review.

Note there are 2 PRs, one for develop, and another for the analytics refactoring branch which includes the first and removes the error handling we had in place in the datastore for this.

**Comment by aaemnnosttv** [comment]
Ready for another pass @felixarntz 👍

**Comment by cole10up** [comment]
**Tested**

Installed 1.7.1 Zip, activated SK and Analytics with a user that doesn't have an analytics account noticed:

![image](https://user-images.githubusercontent.com/57115907/80069710-aa2b3100-84f6-11ea-846f-db232159fd08.png)

Checked edge cases, clicking cancel

![image](https://user-images.githubusercontent.com/57115907/80069723-b4e5c600-84f6-11ea-83ec-ad41d88786eb.png)

Clicking re-fetch refreshes, no error seen.

Clicking create account navigates to the proper URL https://analytics.google.com/analytics/web/provision/#/provision

Passed QA ✅
