### ISSUE TITLE
ads are not showing

### ISSUE THREAD

**Issue by brunoalbim** [google/site-kit-wp#1369]
ads are not showing. some remain just a yellow square, and others do not appear at all.

**Comment by jamesozzie** [comment]
@brunoalbim We've moved Site Kit support over to the [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit/). Please also that If the AdSense code snippet is placed on your site (via Site Kit) then then yo'll need to use the [AdSense Help Center](https://support.google.com/adsense/?hl=en#topic=3373519) for further support. 

Feel free to create a new support topic and include your site URL or further information and we would be happy to point you in the right direction.
