### ISSUE TITLE
Add webpack plugin to avoid circular dependencies

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1372]
## Feature Description

Circular dependencies in JS modules can create odd side-effects that can be difficult to identify.

Let's add the [`circular-dependency-plugin`](https://github.com/aackerman/circular-dependency-plugin) to help us avoid them going forward.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* [`circular-dependency-plugin`](https://github.com/aackerman/circular-dependency-plugin) is added to development dependencies
* Main webpack config is updated to use the plugin in a way that raises errors when a circular dependency is detected
* Any existing errors are resolved (there are a few)

## Implementation Brief

* Finish #1373 to resolve detected circular dependencies
* Merge #1373 

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Assigning this to @felixarntz for merge after the release.

**Comment by tofumatt** [comment]
Looks good; no circular dependencies found. Adding a circular dependency flags the error:

<img width="629" alt="Screenshot 2020-04-30 13 09 20" src="https://user-images.githubusercontent.com/90871/80708605-e0af1000-8ae3-11ea-83dd-a84285430c15.png">

**Comment by tofumatt** [comment]
QA ✅
