### ISSUE TITLE
Port shared data store changes and conventions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1375]
This is a catch-all issue for porting changes to shared datastore code from the Analytics component refactoring branch to develop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All actions that have controls must have dedicated actions for state mutations
* Async actions should follow the following conventions:
    - Use a single action creator generator function to yield all actions for normal/success flow
    - E.g. an action to fetch a "foo" resource would have the following actions
    - `START_FETCH_FOO` - Sets `fetchingFoo: true` in the store
    - `FETCH_FOO` - has associated **`control`** to perform async fetch
    - `FINISH_FETCH_FOO` - Sets `fetchingFoo: false` and potentially other state for a successful completion
        - `receive*` actions are still separate and don't always share the same action name
    - `CATCH_FETCH_FOO` - called by consuming code in the `catch` block surrounding the `yield actions.fetchFoo()` and should always require an `error`
        - Should accept an `error` parameter, and the action should always have `payload.error`
    - The action creator for `fetchFoo` should always return the result from the primary main action, _after_ yielding the `FINISH_FETCH_FOO` action

#### All Stores (core/site, etc)
* Add `constants` sub-module
    - Move and export `STORE_NAME` from this module to avoid circular dependencies with store sub-modules
    - Store sub-modules should only import this from `constants`
* Ensure all action creators include a `payload`, even if empty.

#### Settings Store
* Add selectors:
    - ~~`getSavedSettings`~~
    - ~~`getSaved{Setting}`~~
* Add actions:
    - `rollbackSettings` - "Restores" current settings with saved settings
* Update `actions.set{Setting}` to allow falsy values (invariant should only prevent setting `undefined`)

#### E2E
* Add Redux action logging to e2e-utilities and opt-in via `DEBUG_REDUX=1` env var

#### Webpack + Storybook
* Update main webpack config to allow bits of it to be imported for use by custom config for storybook  
This is necessary for Storybook to work - all Site Kit external assets (e.g. `googlesitekit-data`) need to be converted to aliases

#### Shared Components
* Update the Material `Switch` to use a unique ID by default
* Upgrade `@material/react-select` to latest (resolves bug where disabled state does not change when prop changes)

#### Added Shims
A few module import shims are necessary to make sure consuming code always references the same version.
Normally this would be handled by webpack, but since our entrypoints are split up and made into externals this doesn't seem to work the same way.

* Add shim for `@wordpress/hooks` - makes sure that there is only ever one instance of hooks modules by importing and re-exporting everything onto/from `googlesitekit._hooks`
* Add shim for `@wordpress/element` - makes sure that there is only ever one instance of hooks modules by importing and re-exporting everything onto/from `googlesitekit._element`  
Seems to be necessary to prevent React hooks from raising errors due to separate instances of React  

#### Test Utils
* Add `WithTestRegistry` HOC which wraps children with a fresh test registry which is configurable via its callback prop

## Implementation Brief

* Port most code directly from the `enhance/1101-analytics-datastore-components` branch where possible
* Implement other changes directly (such as action verbaige and creator changes)

## QA Brief

* 

## Changelog entry

* Add `rollbackSettings` action to settings datastores and refine overall datastore infrastructure.

**Comment by felixarntz** [comment]
@aaemnnosttv ACs look good, with one piece pending to be discussed further:

Should we name saved settings selectors `getSaved...` and current ones `get...`? Or vice-versa saved settings `get...` and current ones `getCurrent...`? This is not about the specific name, it doesn't need to be "saved" or "current" - the point is about the common case needing to be the simpler one. My initial feeling is that we'd only ever need the current settings when editing settings, which is a more specific case, and therefore I'd lean towards naming these selectors more verbosely, as in `getCurrent...` or similar.

cc @tofumatt 

Let's start work on the PR for all the other pieces, those all look good to me. We can continue discussing the above in the meantime and add to the PR once we've made a decision.

**Comment by felixarntz** [comment]
Per our conversation earlier, let's not introduce `getSavedSettings` and `getSaved{SettingSlug}` selectors.

**Comment by tofumatt** [comment]
QA, moving to approval ✅
