### ISSUE TITLE
"Let Site Kit place code on your site" working wrong way

### ISSUE THREAD

**Issue by phamquangbaoplus** [google/site-kit-wp#1377]
## Bug Description

1. 404 pages should not have AdSense code
2. 
Not needed at all:
<script>(adsbygoogle=window.adsbygoogle||[]).push({google_ad_client:"ca-pub-xxx",enable_page_level_ads:true,tag_partner:"site_kit"});</script> 

We only need:

 <script data-ad-client="ca-pub-xxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

## Steps to reproduce

1. Enable "Let Site Kit place code on your site"
2. Go to a 404 page 
3. 404 pages should not have AdSense code

## Additional Context

 - PHP Version: 7.4
 - OS: [e.g. iOS] Windows 
 - Browser [e.g. chrome, safari] Chrome
 - Plugin Version [e.g. 22] 1.7.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@phamquangbaoplus Does the theme you are using provide standard 404 templates using the same structure as are other content types? If so then the AdSense code will be placed on your site, whether ads appear or not, using the default Auto code placements. 

Are you looking to not place ads on your 404 URLs? If so the [AdSense Support Center](AdSense Support Center) should be able to assist with product specific queries.

**Comment by jamesozzie** [comment]
@phamquangbaoplus Just following up with you on this matter. Let me know if you have any additional queries on this, otherwise I'll close this issue. For AdSense specific queries the [AdSense Support Center](https://support.google.com/adsense/?hl=en#topic=3373519) should be able to assist.
