### ISSUE TITLE
Modify Analytics module setup with Tag Manager guidance

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1382]
## Feature Description

The Analytics module setup should make appropriate recommendations regarding Tag Manager usage.

**PR for this should be opened against `feature/ga-gtm-separation`.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The GA module should behave a little differently based on whether the GTM module is set up or not.

### GTM module not active

* Don't do anything (other than what's already happening).

#### GTM container has GA tag

* Handle this exactly the same way as if there was an existing tag on the page (with slightly different user-facing message):
    * If user has access to the tag, force-select it. Show informational message "You're already using Google Analytics through Google Tag Manager with the property UA-1234567-1. Site Kit will therefore not place an Analytics tag because Tag Manager already covers it."
    * If user does not have access to the tag, block them. Show error-like message: "You're already using Google Analytics through Google Tag Manager with the property UA-1234567-1, but your account doesn't seem to have access to this Analytics property. You can either modify your Tag Manager configuration to use a different property, or request access to this property from your team."
* The GA module's `useSnippet` option should be set to `false`.

#### GTM container has no GA tag

* Don't do anything (other than what's already happening).

## Implementation Brief

**Variable references for below**

* `select( core/modules ).isModuleActive( 'tagmanager' )` as `tagmanagerModuleActive`
* `select( modules/tagmanager ).getSingleAnalyticsPropertyID()` as `gtmAnalyticsPropertyID`

~~

* Extract logic for force-selecting the Analytics existing tag or GTM property to a new custom hook `useExistingTagEffect` (similar to the GTM module), except this hook should also include logic for selecting the property ID from GTM.
    - Permission for a detected GTM property ID must also be checked if present with `hasTagPermission( gtmAnalyticsPropertyID )`
    - An Analytics existing tag should take precedence over a detected property ID in GTM regarding the force-selected value(s)
    - Refactor `SetupMain` and `SettingsEdit` with new hook
    - Add tests for this hook (see GTM version for reference) but needs additional logic tested for extended logic
* Show a new `<ExistingGTMPropertyNotice>` component if `gtmAnalyticsPropertyID` is a valid propertyID and `hasTagPermission( gtmAnalyticsPropertyID )`
    - Similar to `ExistingTagNotice`, add a new component for displaying this GTM specific notice
    - Should show even if the existing tag notice is already showing, as the user should be informed if there is potential duplicate (or worse) tracking in place
* Show a new `<ExistingGTMPropertyError>` component if `gtmAnalyticsPropertyID` is a valid propertyID `&& hasTagPermission( gtmAnalyticsPropertyID ) === false`
    - Similar to `ExistingTagError`, add a new component for displaying this GTM specific error
* Extend logic for `canSubmitChanges` if `tagmanagerModuleActive`
    - Return `false` if `isValidPropertyID( gtmAnalyticsPropertyID ) && hasTagPermission( gtmAnalyticsPropertyID ) === false`
* Update Jest tests for `datastore/settings.js` to cover changes to `canSubmitChanges`
* Add Storybook stories for these cases to "Setup" and "Settings" stories
    - No existing tag, with GTM property with access
    - No existing tag, with GTM property with no access
    - No existing tag, with multiple GTM properties (different property IDs)
    - With existing tag, with GTM property (same property ID) with access
    - With existing tag with access, with GTM property with no access

### Prerequisite
1. Set up a Tag Manager container that has an Analytics tag set up with the same Analytics property ID (`UA-...`) that you're using for your Site Kit site.
2. Set up another Tag Manager container that has _any_ Analytics tag set up with a property ID that you don't have access to.
3. The site should only have the Search Console module active, no other ones.

### Test 1
1. Activate the Tag Manager module.
2. Select the above container 1. The description should now explain that an Analytics property was detected.
3. Click "Continue to Analytics setup". You should immediately be moved to the Analytics setup.
4. In the Analytics setup, you should now be informed that you're already using Analytics via Tag Manager, and the corresponding Analytics property should be force-selected in the dropdown, without you being able to change it.
5. Complete Analytics setup.
6. Check that the frontend contains the Tag Manager snippet, but not the Analytics snippet (because Tag Manager takes care of Analytics now).

### Test 2
Same as Test 1, but instead of step 3., click "Continue without Analytics", and then go to Site Kit Settings and activate Analytics manually. The rest of the experience should be the same.

### Test 3
Same as Test 1, but instead of step 2, select the above container 2. Then in the Analytics setup, you should see an error message informing that you don't have access to the Analytics tag included via Tag Manager. You should be blocked and unable to complete Analytics setup in that case.

### Test 4
1. Activate the Tag Manager module.
2. Select another container than the above (which doesn't have Analytics), and complete setup.
3. Then activate the Analytics module.
4. Nothing should be different from usually, because the Tag Manager container doesn't have Analytics.

## Changelog entry

* Provide guidance in Analytics setup flow when Tag Manager is already active and its container is configured to use Analytics.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> `select( modules/tagmanager ).getAnalyticsPropertyIDs()` as `gtmAnalyticsPropertyIDs`

Why do we need awareness of this here? While this configuration could have been changed in the meantime, I think we can limit that handling to the GTM setup flow, and in here only get the single GTM GA property (if present).

> Show a new `<ExistingGTMPropertyNotice>` component if `gtmAnalyticsPropertyIDs` is not an empty array, and `gtmAnalyticsPropertyID !== propertyID`

What does `propertyID` refer to here? If that's the property ID set in the GA module: This comparison would only apply to settings (where a property ID had already been chosen), but not setup - it's somewhat of a use-case which we right now don't cover at all in Analytics (this would just as much apply for a regular existing tag). I think introducing that here is out of scope, so let's just display the `ExistingGTMPropertyNotice` whenever there is any `gtmAnalyticsPropertyID` with permission, and then force-select it (same like we do for an existing tag).

**Comment by aaemnnosttv** [comment]
@felixarntz IB updated. Before we move this forward, what E2E coverage do you feel should be included here? Having a non-AMP and few secondary AMP cases makes sense I think, but what about primary AMP?

**Comment by felixarntz** [comment]
@aaemnnosttv IB ✅  I think we don't need AMP-related e2e tests here, since the parts relevant to AMP are implemented in #1381 right?

**Comment by aaemnnosttv** [comment]
@felixarntz as we discussed yesterday, I think both issues don't have much of a need for E2E, but instead most of the useful coverage we want to add can be provided by Jest tests for the datastore (`canSubmitChanges`) and component/hook tests (`useExistingTagEffect`). I'll update the IB to mention these but this should be good to move forward now 👍

**Comment by cole10up** [comment]
**Test 1:**
