### ISSUE TITLE
Split Tag Manager setup/settings into different components using datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1386]
## Feature Description

Similar to #1101 and #1014, this issue is about refactoring the Tag Manager setup/settings implementation to use distinct components, smaller standalone sub-components, all using the `modules/tagmanager` datastores (and other datastores as necessary).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be distinct standalone components for all three dropdowns in the GTM setup/settings.
* There should be a `SetupMain` component for the setup screen.
* There should be a `SettingsMain` component for the settings panel, displaying either a new `SettingsView` or `SettingsEdit` based on the context.
* The components should only access datastore data, never anything from globals.
* The implementation should follow patterns established as part of the issues linked above.

## Implementation Brief

**Create the following Tag Manager-specific React components:**
* `<AccountSelect>` for choosing the account
* `<WebContainerSelect>` for choosing the web container
* `<AMPContainerSelect>` for choosing the AMP container
* `<UseSnippetSwitch>` for toggling the `useSnippet` setting
* `<ExistingTagError>` for rendering a blocking error regarding an existing tag
* `<ExistingTagNotice>` for rendering a non-blocking notice regarding an existing tag
* `<ErrorNotice>` for rendering the current `error` in the module's datastore, if any
* `<AccountCreateLegacy>` for rendering the steps to take to create an account, with buttons to "Refetch accounts" or cancel
* `<SetupForm>` for rendering a `<form>` containing the `<AccountSelect>`, and relevant container select components based on the context
* `<SettingsForm>` for rendering a `<div>` containing the `<AccountSelect>`, and relevant container select components based on the context, as well as `<UseSnippetSwitch>`
* `<SetupMain>` for rendering a loading state, `<ExistingTagError>`, `<AccountCreateLegacy>`, or `<SetupForm>`
* `<SettingsEdit>` for rendering a loading state, `<ExistingTagError>`, `<AccountCreateLegacy>`, or `<SettingsForm>`
* `<SettingsView>` for rendering the static view for all settings
* `<SettingsMain>` for rendering `<SettingsEdit>` or `<SettingsView>`

Additional details
* Most of these have an equivalent component that can be used as an example in the Analytics datastore. Some may even be the same, with the only difference as the `STORE_NAME` in the data hooks.
	- Analytics components should be referenced for `useEffect` and other hooks that will need to be used for integration with larger legacy app  
	E.g. handling "Confirm changes" on save settings, and toggling disabled state of this button
* Add storybook stories for all important states in setup and settings:
	- `stories/module-tagmanager-settings.stories.js`
	- `stories/module-tagmanager-setup.stories.js`
* Add component tests for each new component

## QA Brief

* 

## Changelog entry

* Significantly improve stability and maintainability of Tag Manager module setup and settings.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@aaemnnosttv Since the work here is yet to be started, let's put all GTM-specific components into `assets/js/modules/tagmanager/components` (i.e. most subdirectories like `common`, `settings`, `setup` would go into that). See https://github.com/google/site-kit-wp/issues/1302#issuecomment-637664470.

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest develop.

Activated Analytics and Tag Manager module

![image](https://user-images.githubusercontent.com/57115907/87509775-1ebdc980-c627-11ea-9b0d-bf769bf6e615.png)

![image](https://user-images.githubusercontent.com/57115907/87509812-3432f380-c627-11ea-92e9-82f11c301ad2.png)

![image](https://user-images.githubusercontent.com/57115907/87509894-5d538400-c627-11ea-9865-cd22d98c3cac.png)

Confirmed functionality

![image](https://user-images.githubusercontent.com/57115907/87510012-9ab81180-c627-11ea-8123-0d08fa0a2b63.png)

![image](https://user-images.githubusercontent.com/57115907/87510023-a0adf280-c627-11ea-89e9-51cd7d08b691.png)

Confirmed editing container functions properly

![image](https://user-images.githubusercontent.com/57115907/87510072-b8857680-c627-11ea-85de-44c208b6840a.png)

![image](https://user-images.githubusercontent.com/57115907/87510084-c1764800-c627-11ea-977f-8636cdd107dd.png)

Confirmed disconnection of tag manager functions

![image](https://user-images.githubusercontent.com/57115907/87510130-da7ef900-c627-11ea-878a-04b57136cb9a.png)

![image](https://user-images.githubusercontent.com/57115907/87510205-fedad580-c627-11ea-8dfa-0db3ef6f205a.png)

Passed QA ✅

**Comment by aaemnnosttv** [comment]
I just noticed that it isn't possible to select "Set up a new container" now
![Kapture 2020-07-16 at 18 46 47](https://user-images.githubusercontent.com/1621608/87692938-0370cc80-c795-11ea-8286-9bee4f097255.gif)

This can be seen in Storybook as well https://google.github.io/site-kit-wp/storybook/master/?path=/story/tag-manager-module-settings--edit-with-all-settings

Moving back to execution to resolve.

**Comment by felixarntz** [comment]
Setting up a new container now works as expected ✅
