### ISSUE TITLE
Migrate plugin dashboard to use Widgets API infrastructure

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1392]
## Feature Description

After #1300, we should start using the Widgets API. Note that with the changes below we'll break all these screens by making them empty (there won't be any widgets initially).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing components for dashboard screen and the dashboard-details screen should be modified (let's not refactor these components; let's change them as little as possible, as much as needed for just this change here) to use the `WidgetAreasRenderer` to render widget areas. If possible, for now let's just add this component and not replace the existing "filtered components" currently being used to render the respective area. This will allow us to temporarily have both the old and new way available (we'll never publish any release with that state, but it'll potentially help building the new widgets and ensuring they look and behave similarly). Also keep in mind this is all happening in a branch separate from `develop`. The components should render widget areas for the given context as follows:
    * For the dashboard use context `dashboard`.
    * For the dashboard-details ("dashboard for a single URL") use context `pageDashboard`.
* Modify the `core/widgets` datastore module so that it automatically registers a few core widget areas for context `dashboard` (they should registered with prioritiy 1-5 in the order below):
    * `dashboardAllTraffic`
    * `dashboardSearchFunnel`
    * `dashboardPopularity`
    * `dashboardSpeed`
    * `dashboardEarnings`
* Modify the `core/widgets` datastore module so that it automatically registers a few core widget areas for context `dashboardDetails` (they should registered with prioritiy 1-4 in the order below):
    * `pageDashboardSearchFunnel`
    * `pageDashboardAllTraffic`
    * `pageDashboardTopQueries`
    * `pageDashboardSpeed`

## Implementation Brief

* Add feature flags and use them for this code:
  * Use [webpack-feature-flags-plugin](https://github.com/davolokh/webpack-feature-flags-plugin) to set our feature flags. This gives us tree-shaking dead code elimination (so we never ship that code to production until it's enabled), but allow us to reduce our usage of long-running feature branches.
* Add `{ featureFlags.DashboardWidgetsAPI && <WidgetAreasRenderer context="dashboard" />}` to https://github.com/google/site-kit-wp/blob/c302d8cb77374e394ba4711a93b3d7ca33e43802/assets/js/googlesitekit-dashboard.js#L54. I'd prefer to place our new components up as high-as-possible in the tree to prevent interaction with existing filters/WP JS Hooks, etc. We can create a component to house this `WidgetAreasRenderer` if desired, but I'd love to put the new components up at the top of the tree. We may need to place it lower in the tree to be able to share screen space with existing widgets, but best to try to put it as high as possible and adjust during implementation :smile:
* Add a `<WidgetAreasRenderer context="pageDashboard" />` to https://github.com/google/site-kit-wp/blob/c302d8cb77374e394ba4711a93b3d7ca33e43802/assets/js/googlesitekit-dashboard-details.js#L44. I'm going with `pageDashboard` as the context here over `dashboardDetails`, because I agree that we should have a better name for this, and I've always found "Dashboard Details" to be confusing and a bit of an unclear implementation leak.
* Register these widgets areas for the `dashboard` context:
  * `dashboardAllTraffic`
  * `dashboardSearchFunnel`
  * `dashboardPopularity`
  * `dashboardSpeed`
  * `dashboardEarnings`
* Register these widgets areas for the `pageDashboard` context:
    * `pageDashboardSearchFunnel`
    * `pageDashboardAllTraffic`
    * `pageDashboardTopQueries`
    * `pageDashboardSpeed`

These widgets won't all exist yet, but we should write the code to queue them up. Then place the code behind a development feature flag. That way we can start outputting whatever widgets we _do_ have available by excluding them from the feature flag check (or having specific flags for each feature and enabling them for production builds).

## QA Brief

* For a development build, these duplicate widget areas should be displayed (indented), in both the dashboard and the single page dashboard. They don't have any widgets yet, so it should basically just be the headings and subtitles.
* For a production build, these should not be displayed at all. There should be no visual change from a production build with and without this issue completed.

## Changelog entry

* Implement widget areas using new Site Kit widgets API.

**Comment by tofumatt** [comment]
Most of the estimate here is around feature flags, but because we're just registering things here I don't think this issue should take too long. It's closer to 4 than 7, for what it's worth. 😄

**Comment by felixarntz** [comment]
@tofumatt Note this issue _is_ also about modifying the actual dashboard to display widgets (actually no widgets because there won't be any registered yet) - so this will either go against a feature branch or require feature flags to go against `develop`. The first bullet point of the ACs is mostly about that.

**Comment by tofumatt** [comment]
That makes sense. I think the IB is pretty clear about usage of feature flags now. Let me know if that's good or if there's something else missing from here, but I think the idea that we set feature flags with something like https://github.com/davolokh/webpack-feature-flags-plugin is clear; actual usage of that will be down to checking if they're true or not in the React component.

**Comment by felixarntz** [comment]
@tofumatt IB mostly SGTM, including usage of feature flags. So for now the intention would be to have `featureFlags.DashboardWidgetsAPI` and `featureFlags.PageDetailsWidgetsAPI` (or whatever we decide for the name, see below) right?

> I'm going with `page` as the context here over `dashboardDetails`

Maybe `pageDashboard` instead of `pageDetails`? The intention is for it to be very similar to the general dashboard, just for a single page instead. I like including `page`, but I'm actually not so sure about the `details` bit either.

> I think it's worth changing the slug name from `dashboardSpeed` to `dashboardPageSpeed`; same goes for the details slug.

What's your thinking behind that? The name is based on the current heading for these areas, so I think using `Speed` makes most sense.

> Register these widgets [...]

This should say "Register these widget areas" - this is not about registering any widgets yet.

**Comment by tofumatt** [comment]
> So for now the intention would be to have featureFlags.DashboardWidgetsAPI and featureFlags.PageDetailsWidgetsAPI (or whatever we decide for the name, see below) right?

Yup! I imagine we might decide to name/namespace them in some way so I didn't specify the names here, but that's the idea 😄

> Maybe pageDashboard instead of pageDetails? [...] The name is based on the current heading for these areas, so I think using Speed makes most sense.

Works for me! IB updated.

> This should say "Register these widget areas" - this is not about registering any widgets yet. The first widgets will be part of #1302.

Argh, indeed! That's what I meant to write, must've just got confused and left it out of the text. IB updated 😄

**Comment by felixarntz** [comment]
IB ✅ 

Via #1300, `WidgetAreasRenderer` will have a different name (`WidgetContextRenderer` or similar), but that isn't really relevant for the IB itself.

**Comment by felixarntz** [comment]
With this getting merged, be aware that running a development build (`npm run build:dev`) will from now on include an unfinished and unpolished duplicate list of widget areas in both the dashboard and the single page dashboard. Due to some grid constraints and to keep things simple alongside the existing production UI, **the new widget areas are slightly further indented**. Let's keep it this way for now, it actually serves as a good visual indicator that those further indented areas are the new ones, which are hidden behind a feature flag.

See these screenshots for reference of what this should look like for a development build:
![Screenshot 2020-07-09 at 11 11 53](https://user-images.githubusercontent.com/3531426/87075981-fc1a5380-c1d5-11ea-8abc-348dcb747411.png)
_Dashboard_

![Screenshot 2020-07-09 at 11 11 39](https://user-images.githubusercontent.com/3531426/87076006-03416180-c1d6-11ea-968f-131592d3b192.png)
_Single Page Dashboard_

For production builds (`npm run build`), nothing should visually change from today, i.e. these duplicate widget areas shouldn't display there.

We will resolve the outer UI concerns, i.e. make sure the new areas are no longer extra indented, once we're closer to completely removing the old widget areas (which didn't use the API and were just hard-coded). In the long term, it will also be ensured that a widget area will not be displayed if it has no widgets in it (like what's happening now).

**Comment by cole10up** [comment]
**Tested**

Installed develop zip and activated plugin.

Notice dashboard:
![image](https://user-images.githubusercontent.com/57115907/87633111-a242ed80-c6ef-11ea-9955-5c9bf32d51f7.png)

Installed latest 1.12.0 release candidate and activated plugin

Notice dashboard:
![image](https://user-images.githubusercontent.com/57115907/87633364-1aa9ae80-c6f0-11ea-9af5-83a031ed3a46.png)

Confirmed install and uninstall of plugin

Passed QA ✅
