### ISSUE TITLE
Fatal error on line 97

### ISSUE THREAD

**Issue by alexkangelov** [google/site-kit-wp#1393]
## Bug Description

I downloaded Google site kit for wordpress but when I click activate I get this message.

Plugin could not be activated because it triggered a fatal error.

Fatal error: Can't use function return value in write context in /home/nulainfo/public_html/vitaburgas.com/wordpress/wp-content/plugins/google-site-kit/google-site-kit.php on line 97

**Comment by jamesozzie** [comment]
@alexkangelov Thanks for reporting. We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. 

Please include your [Site Health information](https://i.imgur.com/Rtkmsba.png) so we can determine your environment setup, including your PHP version.
