### ISSUE TITLE
Allow changing the site name on authentication service

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1397]
## Bug Description
Users are presently unable to modify the name listed under "Manage Sites" > 

![image](https://user-images.githubusercontent.com/41326532/79560329-53a99700-809f-11ea-9ba4-f3578d518bc5.png)

![image](https://user-images.githubusercontent.com/41326532/79560489-9b302300-809f-11ea-8199-d0ceb01d15c5.png)

The initial "Site Name" is also used after the following:
1. Revoking access (via Site Kite dashboard > Manage Sites > Remove Access > Reset Site Kit
2. Changing "Site Name" in a users WP General Settings
3. Revoking access via https://myaccount.google.com/permissions?pli=1
4. Attempting setup once more

Original support topic:
https://wordpress.org/support/topic/change-the-site-name/

[Supporting video](https://recordit.co/jAJ8Fk7Hns)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Changes to the Site Title should be synchronized to the authentication service on-the-fly

## Implementation Brief

* In `Authentication::register()`, add the same `$option_updated` callback onto `update_option_blogname`, just like the existing ones for home + site URL

## QA Brief

* 

## Changelog entry

* Update registered site name on authentication service when it is updated in WordPress.

**Comment by aaemnnosttv** [comment]
@jamesozzie this name should be updated automatically now any time their Site URLs change:

![image](https://user-images.githubusercontent.com/1621608/79565648-caec2480-80b9-11ea-90c6-7bccc3634fbb.png)

@felixarntz perhaps we should extend this functionality to include changes to the Site Title as well?

**Comment by aaemnnosttv** [comment]
Escalating to execution 👍

**Comment by felixarntz** [comment]
IB ✅

**Comment by ShahAaron** [comment]
**Tested**

Pull down develop, navigated to dashboard -> Manage sites

- Revoked access
- Settings->Admin Settings->Reset Site Kit
- Changed "Site Name" in a users WP General Settings
- Setup Site Kit again
- Revisited Manage sites and the "Site Name" had changed 

Passed QA ✅

**Comment by aaemnnosttv** [comment]
@ShahAaron the steps you took here would pass QA before this issue was worked on so this isn't quite ready for Approval yet.

Please try the following:
* Set up Site Kit
* Change "Site Title" in Settings > General
* From Site Kit dashboard, click on "Manage Sites" from the user's dropdown in the Site Kit header to navigate to the authentication service
* See new site title reflected in the list of sites on the authentication service

**Comment by ShahAaron** [comment]
@aaemnnosttv I probably didn't explain what I did very well

This time a strictly followed your steps and the new site title was shown on the list of sites for the authentication service
