### ISSUE TITLE
Errors after clearing account permissions: Unknown Error (code: Invalid parameter: 'code') 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1398]
## Bug Description

After clearing account permissions errors appear in Site Kit dashboard access, and after re-authentication. 

Possibly plugin related or non issue related to environment. Only encounters on one site at present, will try to reproduce once more. 

## Steps to reproduce

1. Clear account permissions via https://myaccount.google.com/permissions?pli=1
2. Visiting existing Site Kit dashboard, the "Sorry you cannot access this page" notice appears. 

![image](https://user-images.githubusercontent.com/41326532/79563121-1267b600-80a4-11ea-92bf-c30733b37f44.png)

3. The can be dismissed after refreshing. After doing to the following appears

![image](https://user-images.githubusercontent.com/41326532/79563509-ded95b80-80a4-11ea-9906-08d3fa3342ed.png)

4. After following the standard access screen and allowing all permissions I encounter the following:

![image](https://user-images.githubusercontent.com/41326532/79562856-97060480-80a3-11ea-9a50-3a63c9384b66.png)

5. This can also be dismissed and Site Kit works as normal, with all previous modules connected. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Closing as issue doesn't appear when using incognito or when refreshed. We can reopen or use as reference should this issue occur again.

**Comment by jamesozzie** [comment]
Occurred once more after switching a site URL from www to non www. The plugin recognised the URL change and suggested to redo plugin setup. This dashboard notice occurred as below after doing so, with no console errors on the same screen:

![image](https://user-images.githubusercontent.com/41326532/111684639-db070980-881e-11eb-980d-fddbf5cc72c2.png)

Upon page refresh the notice disappeared, with Site Kit setup and all services running as normal. All dashboards also had data (the same as before the www. change (www change was only temporarily - to recreate an users experience)

Internal task created to perform the same tests and gather additional insights

Additional notes:
- All services were connected prior to and after this notice appears
- No security or optimisation plugins active
- Testing performed on the same site used for AdSens testing (o.....ie)

**Comment by abdullah1908** [comment]
@jamesozzie this error occurred for me as well. Its fixed by resetting Site Kit settings before Redo Site Kit Setup.
