### ISSUE TITLE
Create a "combineStores" utility function to combine stores

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1400]
## Feature Description

Currently, we create "combined" stores like this: https://github.com/google/site-kit-wp/blob/507e81f4af2b52e77db6a71710777d5ea086302b/assets/js/googlesitekit/modules/create-module-store.js#L59

But that's a bit verbose and makes combining multiple stores together a bit annoying. We should create a utility that combines stores—even ones that lack certain keys.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Create a `combineStores( …args )` function that accepts a list of stores and combines their actions, reducers, etc. for multiple stores and returns a single store. It should not require that stores have all store properties (eg. `initialState`, `actions`, etc.) and should use sane defaults for any missing values.
* It should still fail if duplicate keys are found, similar to the `collectActions`, etc. functions.

## Implementation Brief

* Add a `combineStores( …args )` function that accepts full stores as arguments, each with the object shape:

```js
{
  INITIAL_STATE,
  actions,
  controls,
  reducer,
  resolvers,
  selectors,
}
```

Note that _every value should be optional_, because it's possible to have a store that doesn't have `controls`, or even `selectors`, etc. We can provide sane defaults for other things like `reducer` or `initialState` if none are provided. (Though equally, I'd be fine if `initialState` was also required.)

* This should act like an amalgamation of this type of code: https://github.com/google/site-kit-wp/blob/c302d8cb77374e394ba4711a93b3d7ca33e43802/assets/js/googlesitekit/datastore/site/index.js#L38-L85, but allow for developers to simply submit entire stores. So the above code would change to:

```js
const store = Data.combineStores(
	{
		actions: Data.commonActions,
		controls: Data.commonControls,
	},
	connection,
	info,
	reset,
	notifications,
);

Data.registerStore( STORE_NAME, store );
```

## QA Brief

* 

## Changelog entry

* Add `googlesitekit.data.combineStores` utility function to combine multiple datastore objects.

**Comment by felixarntz** [comment]
IB ✅ 

Let's have all parts of the object optional including `INITIAL_STATE`.

**Comment by ShahAaron** [comment]
Tested

PR code
Run e2e tests - passed
Run JS Unit tests - passed
Run Visual regression tests - passed

Passed QA ✅

**Comment by felixarntz** [comment]
Based on our conversation, let's remove the initialization-related bits from `combineStores` to get it ready in itself to be shipped in the release (see findings in #1476). We can then completely remove the initialization logic via #1476 or another issue.

**Comment by jqlee85** [comment]
@felixarntz  the `combineStores()` utility itself doesn't have any initialization code. `Data.commonStore` does use `addInitializeReducer()` and `addInitializeAction()`, though it's not being used used anywhere (until #1476 is merged). Should I remove the the two `addInitialize...` calls from `Data.commonStore`?

**Comment by felixarntz** [comment]
@jqlee85 Yeah exactly, sorry for being a bit unprecise in my comment above. `combineStores` should not use any initialization logic _indirectly_ either 👍 The actual problem as mentioned lies in `addInitializeAction` being called with an empty object for `commonStore`.
