### ISSUE TITLE
Auto-select Analytics profile based on property's `defaultProfileId`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1404]
When a user selects an Analytics property in the dropdown (in setup or settings), Site Kit currently auto-selects the first profile found that belongs to the selected property. It should instead look for the profile identified by `defaultProfileId` in the property object and select that one by default. Only if for some (edge-case, possibly even bug) reason no such profile is found, it should fall back to the first applicable one.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics logic for auto-selecting a profile on property selection should consider the selected property's `defaultProfileId` with highest priority, and only if there's no match found fall back to picking the first one.

## Implementation Brief

Working from the `refactor/analytics-data-store` branch if not merged yet

#### `assets/js/modules/analytics/datastore/properties.js`

* In `actions.selectProperty` before the profile is set, load the property similar to how it is done for `internalPropertyID` above
* If the property has a `defaultProfileId` set, set the `profileID` with the `property.defaultProfileId` and return early
* If there is no `defaultProfileId` set, continue to the current logic for setting the profile ID
* Update tests accordingly (likey just E2E)

## QA Brief

* 

## Changelog entry

* Rely on the default profile specified in an Analytics property for the profile to pre-select in the dropdown in Analytics setup/settings.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed latest production ready 1.8.0 SK zip. Setup SK and activated Analytics module

Confirmed selecting multiple accounts would default to the first property
![image](https://user-images.githubusercontent.com/57115907/81255572-d9579d00-8fe2-11ea-97be-20ee064c54ab.png)

![image](https://user-images.githubusercontent.com/57115907/81255598-eb394000-8fe2-11ea-991f-e26f7ff42339.png)

![image](https://user-images.githubusercontent.com/57115907/81255635-01df9700-8fe3-11ea-865f-c2c9600de384.png)

No bugs discovered, flipping between accounts, adjusting the property prior to flipping accounts and back confirmed functional.

Confirmed happy path setup and disconnect functioned properly

Passed QA ✅
