### ISSUE TITLE
Batch requests triggered multiple times when certain assets are enqueued

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1406]
## Bug Description

Currently, multiple entrypoints include the legacy `dataAPI` in their bundle. This causes its init method to be called multiple times which leads to batch requests hooked on `googlesitekit.moduleLoaded` to be executed once for each time it is hooked.

This bug is technically present in the current release but inactive since affected entrypoints (such as `googlesitekit-api`) are not used yet.

More info on the origin of this issue here: https://github.com/google/site-kit-wp/pull/1311#issuecomment-615929968

## Steps to reproduce

1. Enqueue `googlesitekit-api`
1. Go to the Site Kit dashboard
1. See duplicate batch requests made

## Screenshots

Console statements added to show behavior
![image](https://user-images.githubusercontent.com/1621608/79669316-5d2c1f80-81c3-11ea-8b4b-5f474273f83b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `dataAPI.collectModuleData` should only be executed once per page load
* `dataAPI` should not be bundled in the `googlesitekit-api` asset

## Implementation Brief

* In `data/index.js`, add a condition to only `addAction( 'googlesitekit.moduleLoaded' )` if it doesn't already have an action by the same namespace already hooked
* Reorganize a few modules/imports to prevent `components/data` from being included in `googlesitekit-api` and other irrelevant entrypoints (basically by association with `assets/js/util`)
* Merge #1407 

## QA Brief

* 

## Changelog entry

* Fix bug where similar batch request to the API could occur multiple times.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Downloaded SK 1.7.1, installed and activated all modules. Checked console, no errors on dashboard. Confirmed functionality of modules on the dashboard. Unable to reproduce.

![image](https://user-images.githubusercontent.com/57115907/80058817-29146f80-84df-11ea-9ce9-95f07efdb48c.png)

Passed QA ✅
