### ISSUE TITLE
[Analytics] Add the ability to enable reports on Demography and Interests for Remarketing and Advertising

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#1408]
## Feature Description

Currently the Analytics snippet does not allow you to enable / disable important reports such as: Demography and Interests for Remarketing and Advertising.

Useful services, usable with both anonymized and non-anonymized IP.

![image](https://user-images.githubusercontent.com/63558798/79687657-1c76e980-8249-11ea-902d-ad681fc628be.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@sviluppomania I've added that as a feature request for the team to consider for future releases. Please allow time before you receive a response. Many thanks for the suggestion.

**Comment by sviluppomania** [comment]
@felixarntz @aaemnnosttv

**Comment by sviluppomania** [comment]
@jamesozzie news?

**Comment by jamesozzie** [comment]
Hi @sviluppomania, no update yet unfortunately. We're currently working on separate features, updates and enhancements at present. You'll be notified by one of the team members on the status of this feature request.

**Comment by felixarntz** [comment]
This is now being tracked via a separate issue #3053, please follow along there for any updates. I will close this one as duplicate.
