### ISSUE TITLE
Analytics setup: Error: The response is not a valid JSON response

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1412]
## Bug Description

Some users have been encountering issues when connecting the Analytics module, with the error below appearing when clicking on the "Configure Analytics" button
`Error: The response is not a valid JSON response`

![image](https://user-images.githubusercontent.com/41326532/79869330-1748a480-83d9-11ea-8ae6-ef44093e5b24.png)

Console errors:
```
VM2496:1 POST https://www.xxxx.xxx/wp-json/google-site-kit/v1/modules/analytics/data/settings?_locale=user 403
(anonymous) @ VM2496:1
b @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
c @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
forEach.t.<computed> @ googlesitekit-vendor.js?ver=1.7.0:1
n @ googlesitekit-vendor.js?ver=1.7.0:1
_next @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
u @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
i @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
o @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
e @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
u @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
i @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
k @ googlesitekit-vendor.js?ver=1.7.0:1
set @ googlesitekit-module.js?ver=1.7.0:4
(anonymous) @ googlesitekit-module.js?ver=1.7.0:17
k @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
C.forEach.t.<computed> @ googlesitekit-vendor.js?ver=1.7.0:1
k @ googlesitekit-vendor.js?ver=1.7.0:1
e @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
i @ googlesitekit-vendor.js?ver=1.7.0:1
AsyncIterator._invoke @ googlesitekit-vendor.js?ver=1.7.0:1
C.forEach.t.<computed> @ googlesitekit-vendor.js?ver=1.7.0:1
l.async @ googlesitekit-vendor.js?ver=1.7.0:1
value @ googlesitekit-module.js?ver=1.7.0:17
m @ googlesitekit-vendor.js?ver=1.7.0:1
k @ googlesitekit-vendor.js?ver=1.7.0:1
(anonymous) @ googlesitekit-vendor.js?ver=1.7.0:1
E @ googlesitekit-vendor.js?ver=1.7.0:1
Aa @ googlesitekit-vendor.js?ver=1.7.0:1
T @ googlesitekit-vendor.js?ver=1.7.0:1
Ba @ googlesitekit-vendor.js?ver=1.7.0:1
Kd @ googlesitekit-vendor.js?ver=1.7.0:1
rt @ googlesitekit-vendor.js?ver=1.7.0:1
Qd @ googlesitekit-vendor.js?ver=1.7.0:1
Hc @ googlesitekit-vendor.js?ver=1.7.0:1
Pd @ googlesitekit-vendor.js?ver=1.7.0:1
e.unstable_runWithPriority @ googlesitekit-vendor.js?ver=1.7.0:1
Hr @ googlesitekit-vendor.js?ver=1.7.0:1
et @ googlesitekit-vendor.js?ver=1.7.0:1
Nd @ googlesitekit-vendor.js?ver=1.7.0:1
Show 30 more frames
```

Main WordPress support topic to work from:
https://wordpress.org/support/topic/error-the-response-is-not-a-valid-json-response-3/#topic-12689616-replies

**Additional information:**
- Occurs with all plugins temporarily deactivated
- Matching URLs in WP General settings
- No mixed content, all https
- Site Health information provided in submission form
- Site Kit 1.7.0
- Module status active in Site Health
- Checked from browser incognito with plugins deactivated 

_Awaiting additional information_ 

Other recent reported topics (with same JSON error in the past month):
- https://wordpress.org/support/topic/the-response-is-not-a-valid-json-response-12/ (Resolved - mismatching URLs)
- https://wordpress.org/support/topic/analytics-connection-gives-error-the-response-is-not-a-valid-json-response/ 
- https://wordpress.org/support/topic/error-the-response-is-not-a-valid-json-response-2/ (Resolved - unknown)
- https://wordpress.org/support/topic/error-the-response-is-not-a-valid-json-response-2/ (Resolved - unknown)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Possible issue with hosting Web Application Firewall as discovered by @ernee. Awaiting confirmation

**Comment by ernee** [comment]
When checking the failed request for this error (403) in the browser console, the following is given by WPMU DEV hosting that their WAF firewall is blocking it and to go to the hosting logs for details: 

<img width="500" alt="403 error" src="https://user-images.githubusercontent.com/8108643/80128780-01f38780-854b-11ea-947e-c183c2e1b5c8.png">

<img width="500" alt="403 error instructions " src="https://user-images.githubusercontent.com/8108643/80128632-cce73500-854a-11ea-9c7d-d324a76007e5.png">

The logs say the user could either whitelist their IP or disable the WAF rule to allow the request :

<img width="500" alt="WPMUDEV logs" src="https://user-images.githubusercontent.com/8108643/80128271-429ed100-854a-11ea-9ab3-a36a9c634f06.png">

Myself and recent users (including the initial topic) affected by this issue confirmed whitelisting their IPs resolved it. 

Should anything further be done on our side regarding this? **cc:** @felixarntz @marrrmarrr

**Comment by felixarntz** [comment]
@ernee Yeah that sounds like something we cannot address on our end then, so let's close this issue. Maybe worth connecting with WPMU DEV over this issue? What do you think @marrrmarrr?

**Comment by ernee** [comment]
@felixarntz @marrrmarrr quick follow up that WPMU DEV [posted in the forums](https://wordpress.org/support/topic/error-the-response-is-not-a-valid-json-response-3/#post-12790430) that they have made some adjustments to their WAF rules to prevent this.

**Comment by Pranav0180** [comment]
I use Ithemes Security plugin and I'm facing the same issue, is it possible that Ithemes may be blocking the google site kit? How may I fix this?

**Comment by abdullah1908** [comment]
Hey @pedro-mendonca ,

Thanks for reaching us out.

Please [open a new ticket](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) at Support Forum in addition to the [Site Health information](https://drive.google.com/file/d/11InT4iIKpf2zE4jwzWWWbwa_2N4yvd69/view) via [form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) privately so we can troubleshoot this issue for you.

**Comment by saharben** [comment]
I can confirm that iThemes Security Pro setting: 'Filter Long URL Strings' is causing this issue.

**Comment by jodzeee** [comment]
> I can confirm that iThemes Security Pro setting: 'Filter Long URL Strings' is causing this issue.

@saharben Thanks for mentioning this. Now wondering if this is something Site Kit will fix or do we have to go on without using that setting?

**Comment by jamesozzie** [comment]
@jodzeee @saharben This is not something we can easily address on our site. We have however been in touch with iThemes and their next major release will no longer have this configuration option, which users do sometimes run into issues with for particular services. It's not enabled by default when setting up iThemes, users should only encounter this if they choose to enable this option.

**Comment by Wesleychavesdeveloper** [comment]
I migrated ecommerce from a shared hosting to a VPS hosting but now the plug has this error. I already deactivated all the plugs I already uninstalled and installed it again, as instructed in the error message, but the error still continues ..

![screencapture-universodaspiscinas-wp-admin-admin-php-2021-04-09-23_44_32](https://user-images.githubusercontent.com/70098828/114256482-e073f180-998f-11eb-865b-ef0a15ce5f01.png)

**Comment by leqnam** [comment]
The problem, I finally discovered, was the popular iThemes Security plugin.
But to remove it was not the solution. Any ideas?

**Comment by bethanylang** [comment]
Hi @leqnam! Support for Site Kit is provided via the <a href="https://wordpress.org/support/plugin/google-site-kit/">support forums</a>. If you'd like to <a href="https://wordpress.org/support/plugin/google-site-kit/#new-topic-0">open a new topic</a> there, we'd be happy to help.

**Comment by cadentic** [comment]
hi

I need a specific IP address or port to enable from security group as I am using ec2
