### ISSUE TITLE
Additional PHP Testing | includes/Core/Storage/Encrypted_User_Options.php

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#142]
## Feature Description
PHP Tests for `includes/Core/Storage/Encrypted_User_Options.php`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Add 100% PHP Tests coverage for `includes/Core/Storage/Encrypted_User_Options.php`

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Moving this to Blocked for now. Development should be done but it's pending merge of #137

**Comment by aaemnnosttv** [comment]
Ready for review
cc @felixarntz
