### ISSUE TITLE
Implement Custom Dimensions for common WP use cases

### ISSUE THREAD

**Issue by nedberke** [google/site-kit-wp#1424]
## Feature Description

Site Kit inserts the GA tracking code; it would be helpful if it facilitated the creation of custom dimension for common use cases in Wordpress. This includes:
- Author
- Category
- Tags
- "Published on" date

Less common, but useful:
- Post type (custom post types)
- Word count (in ranges)
- Logged in
(Here's a bunch of others that might help in brainstorming sensible options): https://thenextweb.com/insider/2016/12/01/marketing-the-tnw-way-17-50-custom-dimensions-in-google-analytics/)

Being able to see these as reports in GA (performance by author, for example) is helpful to any content publisher. I understand there is still a clunky element of directing the user back to GA to create the Custom Dimensions in the GA Admin panel and match the Index #s, and also in creating the report. But these obstacles are small compared to getting custom dimensions in the tracking code - especially when the tracking code is handled by a plugin. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamsilverstein** [comment]
@marrrmarrr This one might be interesting to consider as part of onboarding flow data (which users would want to track these?). We have discussed tracking categories, tags, users before, but I couldn't find an open issue.

**Comment by nedberke** [comment]
What do you mean by "Which users would want to track these?" I imagine anyone who is publishing content would benefit from the breakdowns that this permits.

**Comment by adamsilverstein** [comment]
Possibly, assuming they use these elements. Since this requires adding custom dimensions, we need to make be thoughtful about what is best for users before adding it.

**Comment by ericjames** [comment]
Bump this!!! This is the whole reason to use any plugin with Wordpress, to implement specific settings across different page types and importantly in Wordpress land, page URLs do not necessarily indicate their categorization in Analytics (ie: posts with specific tag would not be reflected in Analytics to see the performance of specific tags)

**Comment by felixarntz** [comment]
Some overlap with #26 here.

**Comment by amitmalewar** [comment]
**Do you have any updates on this?**
Nine out of ten individuals who use plugins for Google Analytics are looking for this feature.

**Comment by jbryanbarnes** [comment]
Adding on: This is possibly the most meaningful WORDPRESS CORE data that would be helpful to have in Analytics. 

Wanted to add in additional support from our organization for this feature - it seems so obvious that this should have been implemented by now.

**Comment by aaemnnosttv** [comment]
Custom dimensions will start to be added for respective metrics that depend on them with the release of the Key Metrics feature which will be rolling out over the next few weeks 🎉
