### ISSUE TITLE
Admin bar integration and W3 Total Cache Minify conflict 

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1427]
## Bug Description

After 1.7.0, a [user in the forums](https://wordpress.org/support/topic/new-update-breaking-my-site-css-on-admin-side/) reported that Site Kit's admin bar integration and [the minify option](https://jmp.sh/KlYV5gG) in the [W3 Total Cache plugin](https://wordpress.org/plugins/w3-total-cache/) conflict causing display issues in the admin bar integration: 
<img width="500" alt="Broken admin bar with W3TC Minify" src="https://user-images.githubusercontent.com/8108643/80044573-cd83bb00-84b9-11ea-8921-6ab6f0266ee9.png">

In some themes, like [WoodMart](https://themeforest.net/item/woodmart-woocommerce-wordpress-theme/20264492), CSS display issues also appear when viewing the site while logged in:

<img width="500" alt="Woodmart- Site Kit and W3TC conflict" src="https://user-images.githubusercontent.com/8108643/80044891-c27d5a80-84ba-11ea-976d-58eec75dfbb5.png">

Disabling W3 Total Cache's minify option resolves the issue in both cases (admin bar and broken site CSS). For the theme issue, disabling Site Kit's admin bar via the following filter also restores the correct display of the site (while W3TC minify is enabled):

`add_filter( 'googlesitekit_show_admin_bar_menu', '__return_false', 1000 );
`

## Steps to reproduce

1. Setup Site Kit and W3 Total Cache with [minify option enabled](https://jmp.sh/KlYV5gG) (_Performance > General  Settings > Minify > Enable_) with defaults selected.
2. View a page of the site with stats (to show admin bar integration) while logged in
3. See broken admin bar integration 
4. Activate [WoodMart theme](https://themeforest.net/item/woodmart-woocommerce-wordpress-theme/20264492), see broken display of site additionally.

## Screenshots

Correct display with default theme (W3TC minify disabled)
<img width="500" alt="Twentyninteen- W3TC disabled" src="https://user-images.githubusercontent.com/8108643/80045467-54d22e00-84bc-11ea-9827-5a3ede7ed44e.png">

Correct display with Woodmart theme (W3TC minify disabled) 

<img width="500" alt="Woodmart- W3TC minify disabled" src="https://user-images.githubusercontent.com/8108643/80047080-4cc8bd00-84c1-11ea-81de-60f456fe0323.png">

## Additional Context

 - PHP Version: 7.3.16
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.7.0
 - Device: MacBook Air

Related support topic: https://wordpress.org/support/topic/new-update-breaking-my-site-css-on-admin-side/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Admin bar should display correctly with Woodmart theme and W3 Total Cache Minify enabled.

## Implementation Brief

* ~~Using `Admin_Bar/Admin_Bar.php`~~
* ~~Edit the `register` method and add a filter `add_filter()` with the following:~~
  * ~~filter hook name `w3tc_minify_css_enable`~~
  * ~~callback function which returns `false`~~
  * ~~priority of `10`~~
  * ~~accepted arguments of `1`~~
* ~~Add a comment to explain why this filter has been added with `@since n.e.x.t` to add the version number when it was introduced~~

* Using `assets/sass/components/adminbar/_googlesitekit-wp-adminbar.scss`,
	* Update the background image styles of the `.googlesitekit-wp-adminbar.hover .googlesitekit-wp-adminbar__icon` selector along with the other selectors having the same styles to have the SVG background image as a base64 encoded string.
	```css
	background-image: url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDMiIGhlaWdodD0iNDQiIHZpZXdCb3g9IjAgMCA0MyA0NCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+PGRlZnM+PHBhdGggZD0iTTQyLjUgMThIMjJ2OC41aDExLjhDMzIuNyAzMS45IDI4LjEgMzUgMjIgMzVjLTcuMiAwLTEzLTUuOC0xMy0xM1MxNC44IDkgMjIgOWMzLjEgMCA1LjkgMS4xIDguMSAyLjlsNi40LTYuNEMzMi42IDIuMSAyNy42IDAgMjIgMCA5LjggMCAwIDkuOCAwIDIyczkuOCAyMiAyMiAyMmMxMSAwIDIxLTggMjEtMjIgMC0xLjMtLjItMi43LS41LTR6IiBpZD0iYSIvPjwvZGVmcz48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxtYXNrIGlkPSJiIiBmaWxsPSIjZmZmIj48dXNlIHhsaW5rOmhyZWY9IiNhIi8+PC9tYXNrPjxwYXRoIGZpbGw9IiNGQkJDMDUiIG1hc2s9InVybCgjYikiIGQ9Ik0tMiAzNVY5bDE3IDEzeiIvPjxwYXRoIGZpbGw9IiMzNEE4NTMiIG1hc2s9InVybCgjYikiIGQ9Ik0tMiAzNWwzMC0yMyA3LjkgMUw0Ni0ydjQ4SC0yeiIvPjxwYXRoIGZpbGw9IiM0Mjg1RjQiIG1hc2s9InVybCgjYikiIGQ9Ik00NiA0NkwxNSAyMmwtNC0zTDQ2IDl6Ii8+PHBhdGggZmlsbD0iI0VBNDMzNSIgbWFzaz0idXJsKCNiKSIgZD0iTS0yIDlsMTcgMTMgNy02LjFMNDYgMTJWLTJILTJ6Ii8+PC9nPjwvc3ZnPg==");
	```

## QA Brief
* Setup Site Kit and W3 Total Cache with minify option enabled (Performance > General Settings > Minify > Enable) with defaults selected.
* View a page of the site with stats (to show admin bar integration) while logged in
* The admin bar should not be broken.
* Additionally, test with the WoodMart theme to see if the admin bar renders correctly.

## Changelog entry

* Fix admin bar styles conflict with W3 Total Cache Minify functionality.

**Comment by jamesozzie** [comment]
I did some more testing on this today and while I can recreate the same issues using the WoodMart theme I wasn't able to reproduce this with any other theme I tested. 

I was however able to see another conflict that occurs with 3 different sites I tested. With the minify option enabled when hovering over the Site Kit tab the notifications count is output next to the title. 

![image](https://user-images.githubusercontent.com/41326532/80088596-a3cba200-8554-11ea-9b95-a372a61801ab.png)

**Comment by jamesozzie** [comment]
Re-assigning while I check this issue still exists.

**Comment by jamesozzie** [comment]
I've been able to recreate minification related issues with the W3 Total Cache and admin toolbar with Site Kit 1.29.0 and the Woodmart theme 2.4.0. ([recording](https://recordit.co/f86hxJHexb)). 

While there doesn't appear to be any additional characters added to the Site Kit admin toolbar title there are formatting issues as seen below:

![image](https://user-images.githubusercontent.com/41326532/113735160-e352b600-96f3-11eb-8e61-1f7f17e45397.png)

- Deactivating Site Kit the formatting issues no longer occur
- Switching to another theme the issue no longer occurs - although an additional character does appear in the admin toolbar (SK tab). This is in the form of an additional span label below:
`googlesitekit-notifications-counter update-plugins count-0` 

![image](https://user-images.githubusercontent.com/41326532/113734225-134d8980-96f3-11eb-962d-4db0780cabe5.png)

So overall this issue seems to involve 2 different issues:
- Exposing a plugin update count
- Formatting issues issues specific to the Woodmart theme, Site Kit and the minify feature of W3 Total Cache

**Comment by Hazlitte** [comment]
I have observed some similar problems with a different theme and W3 Total cache.  From further testing I found that the problem is specific to minifying the CSS using W3 Total Cache.  There is a hook provided by W3 Total Cache to do disable CSS minifying so it might be best to disable it given that this problem is not specific to the WoodMart theme.

**Comment by eugene-manuilov** [comment]
Thanks, @Hazlitte. Do you know what exactly breaks styles? Can we change something in our styles to fix this issue and escape a need to add `w3tc` specific filter?

**Comment by Hazlitte** [comment]
Hi @eugene-manuilov, my testing showed that this problem is not theme specific.  I tested a couple of other Woo Commerce themes and observed the same behaviour.  When CSS minifying is enabled in W3 Total Cache some styling errors occur and a span element is injected into the DOM.  I didn't figure out if the problem can be prevented by changing styling class names.  We could target the element that is injected and hide it.  As this appears to be specific to Woo Commerce themes we could use the W3 Total cache filter only if Woo Commerce is enabled.  At the time the filter seemed the best way to solve the problem and potentially others that have not surfaced yet when the CSS minify enabled in that plugin.

**Comment by eugene-manuilov** [comment]
> At the time the filter seemed the best way to solve the problem and potentially others that have not surfaced yet when the CSS minify enabled in that plugin.

Unfortunately, we can't just add a filter from a 3rd party plugin (even from the popular one) to fix some compatibility issues by disabling some functionality (am I right, @aaemnnosttv?).

@asvinb can you also check this issue and see if you can find a way how to solve this problem without adding the `w3tc_minify_css_enable` hook to our codebase? :thinking:

**Comment by asvinb** [comment]
@Hazlitte @eugene-manuilov @aaemnnosttv After spending some hours on that, I finally managed to find out the culprit in our CSS which is not playing nicely with `minify`. It's the following line:
https://github.com/google/site-kit-wp/blob/develop/assets/sass/components/adminbar/_googlesitekit-wp-adminbar.scss#L82

So without minification, the SVG (html decoded) markup is as follows:
```html
<svg width="43" height="44" viewBox="0 0 43 44" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><path d="M42.5 18H22v8.5h11.8C32.7 31.9 28.1 35 22 35c-7.2 0-13-5.8-13-13S14.8 9 22 9c3.1 0 5.9 1.1 8.1 2.9l6.4-6.4C32.6 2.1 27.6 0 22 0 9.8 0 0 9.8 0 22s9.8 22 22 22c11 0 21-8 21-22 0-1.3-.2-2.7-.5-4z" id="a"/></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"/></mask><path fill="#FBBC05" mask="url(#b)" d="M-2 35V9l17 13z"/><path fill="#34A853" mask="url(#b)" d="M-2 35l30-23 7.9 1L46-2v48H-2z"/><path fill="#4285F4" mask="url(#b)" d="M46 46L15 22l-4-3L46 9z"/><path fill="#EA4335" mask="url(#b)" d="M-2 9l17 13 7-6.1L46 12V-2H-2z"/></g></svg>
```
but the minified version is as follows:
```html
<svg width="43" height="44" viewBox="0 0 43 44" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><path d="M42.5 18H22v8.5h11.8C32.7 31.9 28.1 35 22 35c-7.2 0-13-5.8-13-13S14.8 9 22 9c3.1 0 5.9 1.1 8.1 2.9l6.4-6.4C32.6 2.1 27.6 0 22 0 9.8 0 0 9.8 0 22s9.8 22 22 22c11 0 21-8 21-22 0-1.3-.2-2.7-.5-4z" id="a"/></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"/></mask><path fill="#FBBC05" mask="url(#")" d="M-2 35V9l17 13z"/><path fill="#34A853" mask="url(#b)" d="M-2 35l30-23 7.9 1L46-2v48H-2z"/><path fill="#4285F4" mask="url(#b)" d="M46 46L15 22l-4-3L46 9z"/><path fill="#EA4335" mask="url(#b)" d="M-2 9l17 13 7-6.1L46 12V-2H-2z"/></g></svg>
```
There is a small diff between those 2 SVGs:
Un minified:
```html
fill="#FBBC05" mask="url(#b)"
```
Minified:
```html
fill="#FBBC05" mask="url(#")"
```

Basically `minify` is replacing `#b` by `#"` and it's messing the overall CSS output. So in the IB, I've suggested we `base64` encode the SVG to prevent that. I tested it locally and it works fine.

**Comment by Hazlitte** [comment]
Wow, great find @asvinb 👍

**Comment by eugene-manuilov** [comment]
That's aweseome! Thanks, @asvinb! IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- With Site Kit and W3 Total Cache with minify option enabled. When I view a page with stats, the admin bar is not broken.
- Also tested with the WoodMart theme and the admin bar renders correctly. 

![image](https://user-images.githubusercontent.com/73545194/126667773-8893bb41-02a2-43b4-a01e-26899296efcd.png)
