### ISSUE TITLE
Dashboard search input not validated

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1434]
## Bug Description

![image](https://user-images.githubusercontent.com/1621608/80126810-262b8480-859c-11ea-9f58-81bb385216d1.png)

Currently the search input on the Site Kit dashboard does not validate the input at all.

It allows the form to be submitted, even with nothing input which raises an error in the console (with no feedback).

## Steps to reproduce

1. Go to Site Kit dashboard
1. Click on "View Data" with nothing in the input
1. See error in console with no feedback given

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The dashboard search should only be submittable with valid input

## Implementation Brief
* In the `PostSearcher` component, modify the `onClick` to ensure that `match` is defined.
* Introduce `state.canSubmit` with a default value of `false` and set the `disabled` prop to be the opposite of it's value.
* Set `state.canSubmit` to be true when both `state.selection` is set and there is a match.
* If defined, set the `document.location` normally.
* Update to use `global.location` as we use `global` for all globals instead of `window` or other implied globals like `document`

Merge: #1452

## QA Brief

* 

## Changelog entry

* Ensure dashboard search form can only be submitted with valid content.

**Comment by aaemnnosttv** [comment]
@ryanwelcher this is a good start - a few thoughts for you:

* Ideally we would also set the `disabled` state on the _View Data_ button based on the validity of the input
    - To do this, would need to have the value of the input in state (i.e. `Autocomplete` would be a "controlled" component  - which doesn't seem to be possible)
   - Let's disable the button based on the presence of `state.selection` since this is required to match with in the `onClick`
* Regarding the `onClick` - as long as there is a `selection` there should always be a `match` since all options are simply a list of posts by title - we should of course prevent the error if there is somehow not a `match` but I think adding additional messages is probably not necessary - let me know if this is not the case though.
* Please update this to use `global.location` as we use `global` for all globals instead of `window` or other implied globals like `document`

Please update your IB and I think this should be good to go 👍

**Comment by ryanwelcher** [comment]
> * Ideally we would also set the `disabled` state on the _View Data_ button based on the validity of the input
>   * To do this, would need to have the value of the input in state (i.e. `Autocomplete` would be a "controlled" component  - which doesn't seem to be possible)
>   * Let's disable the button based on the presence of `state.selection` since this is required to match within the `onClick`

This makes sense, however, `state.selection` is set to `undefined` when the input loses focus. So it the user clicks anywhere but the button, the button is disabled. This will also activate the button if there are no posts found.

If we introduce `state.buttonEnabled` we can set it to true when we have both a selection and a match.

**Comment by marrrmarrr** [comment]
@aaemnnosttv IIRC people can enter both a page title and a URL in this field; if they typed something nonsensical or something that has no matches, would we be able to notify them (e.g. with a message in the drop-down like "no matches found")? 

If that is too much hassle, the proposed UI solution as MVP SGTM.

**Comment by aaemnnosttv** [comment]
@marrrmarrr that's correct. We don't really have a good way to identify nonsensical input and I wouldn't want to disable the submit if it might potentially be correct. We know for sure that it's invalid if the input is empty though which is the main case here.

We do currently show a "No results found" when appropriate, except when the input is empty in which case it errors and the user sees no change.

Thanks for confirming, I'll move this forward I just wanted to double-check with you first.

**Comment by aaemnnosttv** [comment]
@ryanwelcher let's use a more general purpose name for the state instead of `buttonEnabled` which is a bit overly specific. In the future, it's not hard to imagine that CSS classes or other things might change based on the same logic. Something like `hasSelection`, `hasMatch`, `canSubmit` are a few ideas that come to mind that would be logically the same, but would be more versatile to use 😄 

Please update this in the IB, otherwise - IB ✅

**Comment by ryanwelcher** [comment]
@aaemnnosttv based on the logic I've implemented, the user has to have a `selection` and a `match` to be able to click the View Data button. This effectively removes the ability to enter a URI directly as it won't return any content titles and means that pages such as the home page ( unless a page is set ) or archive pages are not accessible via this search tool.

For the purposed of this issue, I have modified the input label to say `Title` instead of `Title or URL` to better reflect what can be input but we should probably address the ability to input a URL in a separate ticket unless @felixarntz feels that we should address it here.

**Comment by ryanwelcher** [comment]
As a follow up here, I just wanted to confirm that content that can resolve to a piece of content from the URL does indeed show in the results dropdown. In the case of URI's that do not have related content such as archive pages will display "No results found" and the button will not become clickable.

**Comment by aaemnnosttv** [comment]
CR ✅ - assigning to @felixarntz to handle the merge around the upcoming release.

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest develop. Navigated to dashboard.

Confirmed user isn't able to search with items outside of valid URLs
![image](https://user-images.githubusercontent.com/57115907/83998179-e4b92380-a914-11ea-9ecd-31a698a2f77e.png)

![image](https://user-images.githubusercontent.com/57115907/83998201-f39fd600-a914-11ea-8ca8-a4a44e841538.png)

![image](https://user-images.githubusercontent.com/57115907/83998191-ebe03180-a914-11ea-81a2-db31104ed77f.png)

Confirmed happy path functions:
![image](https://user-images.githubusercontent.com/57115907/83998268-0c0ff080-a915-11ea-9f81-e69686db2501.png)

Passed QA ✅
