### ISSUE TITLE
Dialog buttons appear misaligned

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1436]
## Feature Description

Currently, all dialog CTA buttons are left-aligned at the bottom. This looks a bit off visually and would be better UX as well if the two were spread apart.

#### Current Dialogs
![image](https://user-images.githubusercontent.com/1621608/80196591-4a33a800-8626-11ea-8cf2-8790c438e569.png)
![image](https://user-images.githubusercontent.com/1621608/80196690-68010d00-8626-11ea-82c8-51b2c63db42b.png)

#### Suggested Layout
![image](https://user-images.githubusercontent.com/1621608/80027315-3c7a0780-84ec-11ea-839b-df16cb912e81.png)

Justify buttons to the sides to avoid lopsided look, but also make it more difficult to accidentally click the wrong thing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Dialog CTA buttons should be justified to the sides
* Additional margin should be added between dialog body and footer

## Implementation Brief

* In `assets/sass/vendor/_mdc-dialog.scss`modify the `.mdc-dialog__actions` class to 
    * `justify-content: space-between`
    * `margin:2em 0;`
* Ensure that VRT passes.

Finish and merge: #1453

## QA Brief

* 

## Changelog entry

* Improve alignment of dialog buttons.

**Comment by aaemnnosttv** [comment]
This looks like a good start @ryanwelcher - just one request for you:

Can we set the margin using a variable for line-height so that the space is equal to 1 or 2 empty lines of text? Perhaps we can just use `em` for this.

**Comment by ryanwelcher** [comment]
@aaemnnosttv sounds good. I've updated the IB accordingly.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
Code reviewed; just assigned to @aaemnnosttv/@felixarntz to merge. 🙂

**Comment by cole10up** [comment]
**Tested**

Confirmed reset button layout:
![image](https://user-images.githubusercontent.com/57115907/80682682-d5be9600-8a77-11ea-80f0-96d99f8d90b9.png)

Checked mobile view
![image](https://user-images.githubusercontent.com/57115907/80682742-ebcc5680-8a77-11ea-946b-6b6974656bf7.png)

Confirmed disconnect button layout:
![image](https://user-images.githubusercontent.com/57115907/80682853-21713f80-8a78-11ea-85ba-ce434b908358.png)

Checked mobile view
![image](https://user-images.githubusercontent.com/57115907/80682819-11f1f680-8a78-11ea-8719-a8253d3ec1e7.png)

Confirmed buttons and cancel function properly

Passed QA ✅
