### ISSUE TITLE
Problem with AdSense

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#1441]
## Bug Description

Hi, the problem is only with Google AdSense, whether it is inserted with SiteKit or manually, without excellent results, Google PageSpeed Insights: 98 (Desktop) and 68 (Mobile).
With other services no performance problems.

How should we reduce this problem while not losing advertising?

## Additional Context

PHP: 7.4
OS: Windows 10
Browser: Chrome
Device: Windows PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@sviluppomania Any AdSense performance queries would be best served using the official AdSense channels, such as the [AdSense Help Center](https://support.google.com/adsense/?hl=en#topic=3373519). As it's not specific to the Site Kit product itself it's not something the Site Kit team can control or dedicate resources towards. 

Sorry we can't be of more assistance in this case.
