### ISSUE TITLE
Optimize local env scripts

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1443]
## Bug Description

There are a few optimizations and minor fixes we can do to our [`local-env` scripts](https://github.com/google/site-kit-wp/tree/46290f84ed6897f18c094e57949fcddeac7e7587/bin/local-env) used for E2E environment orchestration.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `status_message` calls and similar message utility functions should not be wrapped in `$()`  
The reason this is done is because the underlying `_message` functions use the `-n` argument which omits the new line at the end. It's wrapped to add the newline back which is unnecessary in most cases
* `*_message` functions should not use the `-n` argument to `echo`
    - If we need functions that don't add a new line, we should add them as `*_format` functions like the `action_format` function we already have.
* Remove the loop that waits for WP to be responding to requests  
https://github.com/google/site-kit-wp/blob/46290f84ed6897f18c094e57949fcddeac7e7587/bin/local-env/install-wordpress.sh#L20-L27  
This is unneccessary as the following are all wp-cli commands and by the end the environment will definitely be responding to requests so this saves about 5 seconds off of the start-up time.  
_If really needed, we should reduce the sleep between retries to 1s_

## Implementation Brief

* `*_message` calls to have `$()` wrapper removed
    - `echo -en $(status_message "Attempting to connect to WordPress...")` becomes `status_message "Attempting to connect to WordPress..."`
    - Affected files in `bin/local-env`
* In `bin/local-env/includes.sh` remove -n argument for all `*_message` functions
    - `echo -en ` becomes `echo -e`
* Remove the loop that waits for WP to be responding to requests  
https://github.com/google/site-kit-wp/blob/46290f84ed6897f18c094e57949fcddeac7e7587/bin/local-env/install-wordpress.sh#L20-L27 
    - Becomes `$(curl -L http://localhost:$HOST_PORT -so - 2>&1 | grep -q "WordPress")`

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
IB ✅

**Comment by ShahAaron** [comment]
For point 3 - Remove the loop that waits for WP to be responding to requests. I did not remove the loop as it caused the request to fail, so I just reduced the sleep to 1

**Comment by aaemnnosttv** [comment]
## QA ✅
