### ISSUE TITLE
Issue with Site Kit Setup - 404 error

### ISSUE THREAD

**Issue by maverick85** [google/site-kit-wp#1444]
## Bug Description

Unable to Setup Site Kit;

## Steps to reproduce

1. Install the plugin/reset setup
2. Start Site Kit Setup
3. Proceed to Sign In
4. Select Google Account
5. Allow Access to Site Kit
6. stumble on a 404 page
## Additional Context

 - PHP Version: 7.3.17
 - Browser: Safari & Firefox
 - Plugin Version: latest

WP is installed on a directory `domain.com/wp` but accessible from the domain root `domain.com`.
I have setup this plugin before never had any issues. Thanks

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@maverick85 Thanks for reporting. We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue, such as your [Site Health information](https://i.imgur.com/Rtkmsba.png). 

We can also reopen this issue should we determine a bug or area which requires further examination.
