### ISSUE TITLE
Sitekit doesn't detect App+Web Property

### ISSUE THREAD

**Issue by digitalsetups** [google/site-kit-wp#1447]
## Bug Description
While setting up Analytics via SiteKit, it detects only legacy properties and not App+Web ones. In the drop downs, you only see the legacy or old ones. Sitekit doesn't detect App+Web Property while setting up Analytics.

## Steps to reproduce for the First Time
Go to SiteKit -> Analytics -> Choose Analytics Account -> You wouldn't see App+Web Properties in the Property drop down. Only legacy or old-type properties are filtered out and displayed in the list.

## Steps to reproduce on existing setup with Legacy or UA  Property
Go to SiteKit -> Settings -> Analytics -> Edit -> Try to change the property, it's still same.

## Additional Context
We're not sure if its a bug or missing feature as Apps+Web is still in Beta but, still it is being used widely now by publishers and marketers. (We're using it for our several websites) It's really important to see this in SiteKit as several tracking properties are using App+Web type. Also, ensure that when it is available in drop down, it allows us to choose either one data stream view or ALL by default. Because in WP, we may only want to see audience of website and not of app (may be). 

 - PHP Version: 7+
 - Browser: Firefox, Chrome, Edge
 - Plugin Version: All versions until 1.7.1 (the current one)
 - Wordpress Version: All versions until 5.4 (the current one)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@digitalsetups currently Site Kit supports the _Web property_ in Analytics. As you mention, the App + Web property is still in beta/ development, so Site Kit doesn't yet support this. 

In the meantime, you can set up a Web property to configure with Site Kit.  If App + Web tracking is desired, its tag would need to be manually added (using multiple tags for Analytics is generally ok. See this document: https://support.google.com/analytics/answer/1032400?hl=en).

I've marked this issue as a feature request for us to update as development progresses. Thanks for your inquiry.

**Comment by digitalsetups** [comment]
@ernee Okay, great. 

Yet, we have already connected additional tags with it as you recommended.

**Comment by felixarntz** [comment]
We are currently working on adding GA4 support (formerly "App+Web") to Site Kit, and it is one of our main priorities right now. Please follow along the overarching epic #2220 (or any specific sub-issues) for further updates. We are currently anticipating to roll this out within the next 3 months.
