### ISSUE TITLE
AdSense - Stay on "Locating accounts…"

### ISSUE THREAD

**Issue by nakasix** [google/site-kit-wp#1448]
## Bug Description

The setup of AdSense stay on "Locating accounts…".

The setup of the following modules is correct:
- Search Console
- Analytics
- PageSpeed Insights

## Steps to reproduce

1. Subscribe to Google Adsense (Google Website).
2. Join Google Adsense to Google Analytics (Google Website).
3. Install "Site Kit by Google" on Wordpress.
4. Setup Search Console
5. Setup Analytics
6. Setup PageSpeed Insights
7. Setup AdSense -> Stay on "Locating accounts…".

## Screenshots

Screenshot of message.
![Screenshot](https://user-images.githubusercontent.com/37986982/80314507-21f8a480-87f2-11ea-98e5-ea5dea8b8c1a.PNG)

## Additional Context

Server:
 - PHP Version: 7.2
 - OS: Ubuntu 18.04.4 LTS
 - WordPress Version: 5.4
 - Plugin Version: 1.7.1

Client:
 - Browser: Mozilla Firefox 75.0 (64 bits)
 - OS: Windows 10 Pro
 - Device: PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@nakasix thanks for opening an issue. Support for the Site Kit is proved in its [WordPress plugin support forum](https://wordpress.org/support/plugin/google-site-kit/). Open [a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we'd be happy to assist you.
