### ISSUE TITLE
Additional PHP testing | includes/Core/Util/Cron.php  

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#146]
## Feature Description
PHP Tests for `includes/Core/Util/Cron.php`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Add 100% PHP Tests coverage for `includes/Core/Util/Cron.php`

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
This task is superseded by #158 and will not be done.
