### ISSUE TITLE
Expand storybook static files deployment to work for pull-requests

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1460]
## Feature Description

As a follow-up to #1459, we should expand on that work to also expose storybook static files for pull-requests on google.github.io/site-kit-wp.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Storybook builds for pull-requests should be made available via directories like `storybook/pull/{$pr_number}` in the `gh-pages` branch (so that they can be accessed on e.g. `https://google.github.io/site-kit-wp/storybook/pull/1000`).
* When a pull-request is closed, the respective folder should be deleted.

## Implementation Brief

* Expand the `build-storybook.yml` script to also run on `pull_request`.
* Instead of assuming `GITHUB_REF` to always be `refs/head/{$branch_name}`, also support the case where it's like `refs/pull/{$pr_number}/...`.
* Introduce a `remove-storybook.yml` file that on PR close checks out the `gh-pages` branch, wipes the respective folder, and then commits the change.

## QA Brief

* All PRs opened or updated/synchronized after this is merged should have a storybook build publicly available at:  
`https://google.github.io/site-kit-wp/storybook/pull/{PR#}`
* Once the PR is closed, the URL should be a 404 (storybook removed)

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz I realize we don't currently do this with `build-pr` yet but we should prevent these workflows from running on PRs from forks as they are guaranteed to fail. This in turn marks one of the checks as failed and is confusing.

We should be able to prevent this by adding a check like this to the build job:

```yml
if: ${{ ! github.event.pull_request.head.repo.fork }}
```

Otherwise, IB ✅  😄

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Storybook was built for an open PR (e.g. #1715 which adds these stories)
![image](https://user-images.githubusercontent.com/1621608/86101345-d0ef8000-bac2-11ea-971f-44eb20292d3d.png)

Storybook was removed for a closed PR (that did have a storybook built for it)
![image](https://user-images.githubusercontent.com/1621608/86101218-9ede1e00-bac2-11ea-9bf4-a121df2e62ae.png)
