### ISSUE TITLE
Update JSDoc return types to not use nullable

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1468]
Our usage of JSDoc type unions and nullable types (more info here: https://jsdoc.app/tags-type.html) isn't quite right. We sometimes document return types with type unions—a return type of several types—without parenthesis when they are supposed to be supplied.

We also use nullable types in some places when we should really be using `{(Type|undefined)}`. Let's tidy those mistakes up. 😄

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All JSDoc return types should use the "Multiple types (type union)" when the function returns multiple types, not the "Nullable type" if they return a value or `undefined` (don't use `{?number}`, use `{(number|undefined)}`.
* All "Multiple types" return types should be wrapped in parenthesis (`@return {(Object|undefined)}`)

## Implementation Brief

* Search through the codebase for nullable types (eg. `{?number}`, pretty much any instance in the code with `return {?`) and ensure they are actually a value or `null`. They are likely meant to be `{(SomeType|undefined)}` and should be adjusted accordingly. We should check on non-return values as well, but return ones are the ones that sparked this issue 😄
* Check all existing type unions to ensure they are wrapped in parenthesis (it looks like most offending instances returning `Type|undefined` without parens are in `assets/js/googlesitekit/datastore/site/connection.js` and one in `assets/js/googlesitekit/data/create-notifications-store.js`, but there could be more)

## QA Brief

* Literally _nothing_ to QA on this one: it only touches comments/documentation, so feel free to be quick QAing this 😄

## Changelog entry

* N/A

**Comment by rajatdiptabiswas** [comment]
If this is still available, is it okay if I give it a try?

The instructions seem clear and I think I might be able to solve this issue.
I have an exam coming up, but I shall try to get it done as soon as possible.

Thanks in advance.

**Comment by felixarntz** [comment]
@tofumatt IB mostly ✅ , however note that this also applies to some `param` docs, not only `return`. May be good to clarify.

**Comment by rajatdiptabiswas** [comment]
Hi @tofumatt!

I have created a PR but unfortunately, a check failed. Kindly look into it and let me know what I must do differently.

More details are listed in the PR description.

Thanks.

**Comment by tofumatt** [comment]
@felixarntz IB updated to mention non-return types, fair point.

@rajatdiptabiswas: Thanks I'll take a look at your PR—looks like the check that failed isn't related to your code and might be a bug in our GitHub Actions code? At any rate, we'll respond in the PR but if Travis and the CLA checks are passing—which they are—you should be good 😄
