### ISSUE TITLE
Optimize: support OPT prefix containers

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1471]
## Feature Description

Site Kit supports the Optimize container (script) with  the **GTM** prefix:

<img width="1074" alt="Optimize GTM" src="https://user-images.githubusercontent.com/8108643/80647103-c2351000-8a22-11ea-862d-ff5e6addc2ab.png">

Optimize now provides the container (script) with the **OPT** prefix, which Site Kit currently does not support:

<img width="1072" alt="Optimize OPT" src="https://user-images.githubusercontent.com/8108643/80647480-628b3480-8a23-11ea-8842-35c9a173560a.png">

Site Kit should support both container types. 

Related support topic: https://wordpress.org/support/topic/cant-add-optimize-wrong-id/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should be able to recognise both OPT-XXXXXXX and GTM-XXXXXXX as valid Optimize IDs. 
* In the setup UI, add "Format: GTM-XXXXXXX or OPT-XXXXXXX" as an explanatory text next to the input field. 

## Implementation Brief

* Modify `validateOptimizeID` utility function to also support a string starting in `OPT-`.
* Update displayed example value per the ACs.

## QA Brief

* 

## Changelog entry

* Add support for new Optimize container IDs starting in `OPT-`.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ShahAaron** [comment]
Tested

Went to settings and added Optimize
Went to Google settings and added Optimize
In the setup UI, add "Format: GTM-XXXXXXX or OPT-XXXXXXX" correctly displayed as an explanatory text next to the input field.
Site Kit recognised both OPT-XXXXXXX and GTM-XXXXXXX as valid Optimize IDs.
Saved

Passed QA ✅
