### ISSUE TITLE
WordPress in its own subdirectory - 404 error encountered after signing in with Google account

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1474]
## Bug Description

As initially reported in #1444 some users may encounter a 404 page when attempting Site Kit setup after placing WordPress files in a subdirectory. This is dependent on what method they used from the below guide:
https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-ii-with-url-change

WordPress support topic:
https://wordpress.org/support/topic/issue-with-site-kit-setup-404-error/#post-12758604

## Steps to reproduce

1. Create a WordPress site in a subdirectory
2. Follow the [steps as advised](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-ii-with-url-change) in method 2 of the "Giving WordPress Its Own Directory" guide
3. Follow all use Site Kit setup steps
4. 404 page appears

When performing Site Kit setup the process proceeds fine, starting with the admin URL which includes the subdirectory (_.ie. mysite.com/**wpfiles**/wp-admin_). After verifying your site and then choosing your Google account to sign in with a 404 page is encountered (listing the URL without subdirectory .ie. _mysite.com/wp-admin_)  

[Video of issue](https://recordit.co/ivEKe1cCF7)

403 error also encountered during further testing (at same stage)
![image](https://user-images.githubusercontent.com/41326532/80724097-596c9700-8af9-11ea-9fb9-f3b1fbdd7b7e.png)

## Additional Context

- [Method one](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-i-without-url-change) using the guide allows Site Kit setup to proceed as expected
- Admin URL callback during Site Kit setup reverts back to root install (without subdirectory)
- During testing I also encountered 403 errors on one install

Site Health after attempting setup:

```
### google-site-kit ###

version: 1.7.1
php_version: 7.2.15
wp_version: 5.4.1
reference_url: http://mysite.com
amp_mode: secondary
site_status: not-connected
user_status: not authenticated
active_modules: site-verification, search-console
required_scopes: 
	openid: ⭕
	https://www.googleapis.com/auth/userinfo.profile: ⭕
	https://www.googleapis.com/auth/userinfo.email: ⭕
	https://www.googleapis.com/auth/siteverification: ⭕
	https://www.googleapis.com/auth/webmasters: ⭕
search_console_property: none
```

Workaround :  
- Revert back to same URLs in site settings (before including subdirectory)
- Undo changes to index.php file by removing the subdirectory folder redirect (the file should be located in root folder)
- Move index.php file back into subdirectory folder along with other WordPress files
- Add redirect in .htaccess file in root folder as referenced in [method 1 guide](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-i-without-url-change)
- Save permalinks
- Attempt Site Kit setup once more

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by maverick85** [comment]
Hi everybody, I would like to add just a note I think this is important:

When I am authenticated on WP, if I type the url `mydomain.com/wp-admin` it does not fail, it directs me automatically to `mydomain.com/wp_folder/wp-admin`.

This, particularly, does not happen when setting up the Site Kit plugin, and as far as I've noticed is the only plugin that displays this behaviour (giving a 404 error instead of redirecting properly when calling domain/wp-admin while logged in).

**Comment by adamsilverstein** [comment]
@maverick85 & @jamesozzie - thanks for the bug report. It looks like Site Kit is redirecting back to your site to the incorrect root URL. Now when you are trying to set up the plugin, the redirect back to your site during the setup flow is failing.

Apparently you started with WP in the root, then changed to a subfolder install, and Site Kit failed to pick up on that change. Dows that sound right? 

We will look into the best solution for this. One question: did you have Site Kit set up on this site previously with an older version of the plugin?

**Comment by maverick85** [comment]
Hi Adam, thanks for your reply.
Actually your assumption is not correct, the WP site was setup from the start with the ‘domain/wp_folder/‘ and afterward the setup to serve from domain root (method 2 from WP kb) as described. It was not properly “moved” ever per say.

**Comment by maverick85** [comment]
Hi Adam @adamsilverstein, thanks for your reply.
Actually is not that, the WP site was setup from the start with the `domain/wp_folder/`and afterward the setup to serve from domain root (method 2 from WP kb) as described. It was not  “moved” ever per say. (In my case!)

**Comment by adamsilverstein** [comment]
Ah, thank you for clarifying. Still trying to determine conditions to reproduce the 'stuck' state you are in.

**Comment by maverick85** [comment]
@adamsilverstein sure mate no problem, anything just ask away!

**Comment by jamesozzie** [comment]
@adamsilverstein Issue no longer persists as per original support topic. Thanks for providing an update @maverick85 

I'll also confirm from my side with one such setup.

**Comment by cole10up** [comment]
**Tested**

Ran through a series of tests installing WP in its own subdirectory - was unable to reproduce this locally. Sending to L2.

**Comment by jamesozzie** [comment]
More possible examples of unsuccessful Site Kit setups with users placing WordPress files in a "wp" folder. Awaiting further information from users:
- https://wordpress.org/support/topic/cannot-complete-steps-running-me-in-circles/
- https://wordpress.org/support/topic/plugin-setup-stuck-in-a-loop-without-any-error-notice/

I'll test the same setup myself also, following method 2 in [this guide](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-ii-with-url-change)

**Comment by aaemnnosttv** [comment]
Unable to reproduce this myself with a fresh Bedrock install on an unverified domain. Verification works as expected, nothing out of the ordinary. Tried it again after verifying and set up worked again. As reported it works fine for them in some cases too, so it would be good to get the full Site Health info for a site where it's failing.

**Comment by jamesozzie** [comment]
Setup proceeded when testing both suggested methods (Site Kit 1.10.0), new Site Kit setup with files in a wp directory. 

Initial support topic also resolved, with user successfully connected.
