### ISSUE TITLE
Refactor existing datastores with combineStores

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1476]
This issue is a follow-up to #1400 to update our existing code to use the new utility.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All existing datastore definitions should use `Data.combineStores` for aggregating stores into the single store which is registered on `Data`

## Implementation Brief

* Update following store creations to use to use `combineStores()` utility.
  * https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/index.js
  * https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/modules/create-module-store.js
  * https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/index.js 

* Update any existing tests or files to that rely on previous exports from the updated files, including (but not limited to):
  * https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/index.test.js
  * https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/info.test.js
  * https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/notifications.test.js

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
> Update any existing tests or files to that rely on previous exports from the updated files, including

This part shouldn't be necessary as the exports from the index shouldn't change at all. This is only about refactoring how the store components are assembled _before_ exporting.

Otherwise, IB ✅

**Comment by felixarntz** [comment]
I assigned all of you @jqlee85 @aaemnnosttv @tofumatt just because it would be good to get all of your thoughts on https://github.com/google/site-kit-wp/pull/1484#discussion_r420489638.

**Comment by aaemnnosttv** [comment]
@felixarntz I think this should be good to go now. Assigning to you since you had previously requested changes, but also because it is not tagged with the release yet.

**Comment by ShahAaron** [comment]
Develop pulled 
Tests run JS & PHP Unit, e2e & Visual Regression - passed

Code checked - Data.combineStores added - passed 
A/C's - passed

QA ✅
