### ISSUE TITLE
Do not request proxy notifications if proxy is not being used

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1479]
## Bug Description

Even when the proxy is not in use the `core/site/data/notifications` endpoint tries to make a request to the proxy, which will always fail obviously because there is no client ID.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/site/data/notifications` endpoint should only issue a request to the proxy if it is actually in use.

## Implementation Brief

* Add `Authentication` instance as optional third parameter to `Notifications::__construct()`, and set it as class property. If not provided, create from `$context` (only to simplify tests, our production code must _always_ provide it).
* Pass the `Authentication` instance `$authentication` as third parameter when instantiating `Notifications` in the main `Plugin` class.
* Modify `core/site/data/notifications` route logic in `Notifications` class to check `$this->authentication->get_oauth_client()->using_proxy()`. If not, immediately return with an empty array `WP_REST_Response`.
* Nice side-effect to implement here too: Since the `Notifications` class now receives an `Authentication` instance, let's replace manual instantiation of the `Credentials` object in the `Notifications` constructor with `$this->authentication->credentials()`.

## QA Brief

* 

## Changelog entry

* Do not request remote notifications if the site is not connected to the remote.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Ran a series of tests with the production ready SK 1.8.0 zip. Installed and activated SK. Activated modules and performed a series of tests within the proxy around exiting TOS according to this ticket: https://github.com/google/site-kit-wp/issues/1213

Removed and added modules from settings page and the dashboard after initial login. Was unable to experience any issues on my end.

Passed QA ✅
