### ISSUE TITLE
404 Errors in E2E Logs

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1481]
## Bug Description

Recently, logs for E2E tests have become littered with 404 errors in the console, even though all tests are currently passing. However, this only seems to happen on Travis.

**Update**
After debugging this a bit, I found this is happening because static assets were not being included in the `build:test` build as of some recent changes.

## Steps to reproduce

1. Open [E2E test job log from a Travis run](https://travis-ci.com/github/google/site-kit-wp/jobs/325978566)
1. See lots of 404 errors logged

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/80831872-3e328200-8bf4-11ea-8958-0a8c3a910b27.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All full `build:` script variants (dev|test|production) should run:
    - `remove-dist`
    - `build:static`
    - Ending with a `webpack` command (easiest to customize with flags)
*E2E tests should log any response that returns a 400 status code or above in a way that includes the status, method, and URL
    - Suppress/ignore default message which is useless to avoid duplicates and extra noise  
    "Failed to load resource: the server responded with a status of"...

## Implementation Brief

**`package.json`**
* Update `build` to alias `build:production`
* Update `dev` to alias `build:dev`
* Update `watch` to call `build:dev -- --watch`
* Ensure `build:dev` and `build:production` both run `remove-dist` followed by `build:static`  
`build:test` uses `build:production` internally so it's covered too

**`tests/e2e/config/bootstrap.js`**
* Unconditionally add an event handler on `response`
    - Check the status code
    - If greater than 399, log it as a warning and include the method and URL
* Update `observeConsoleLogging` with a conditional to return early for messages matching the AC

Merge #1482

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
Code review 👍

So just assigning to you for the merge.

**Comment by ShahAaron** [comment]
Pulled develop
Ran all tests e2e - passed
Visually confirmed "Failed to load resource: the server responded with a status of"... message no longer output

Confirmed changes to `package.json` & `tests/e2e/config/bootstrap.js`

QA ✅
