### ISSUE TITLE
Rename Analytics Profiles to Views for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1486]
## Feature Description

Currently in Site Kit, we refer to Analytics Views as "Profiles" everywhere. However, in Analytics the product, as well as documentation these are referred to as "Views" since the introduction of the new interface.

![image](https://user-images.githubusercontent.com/1621608/80951332-6393db80-8e00-11ea-9655-69b17abc0755.png)

We should update our interfaces to be consistent with the vocabulary used by the larger Analytics ecosystem. Users who are new to Analytics who might be looking for more information in the documentation will find nothing for profiles (even the above is only available via [archive.org](https://web.archive.org/web/20140210142117/https://support.google.com/analytics/answer/3202287)).

![image](https://user-images.githubusercontent.com/1621608/80950874-67732e00-8dff-11ea-8631-5ebc2181d1ce.png)

[![](https://lh3.googleusercontent.com/tOT3pxDi8e_uAQ1YEm8_q4x8N7SquUMF6XF8P72oo82NgCxk4EkN40qomHl52fqh4KlW=w500)](https://support.google.com/analytics/answer/1009618?hl=en)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Throughout all user-facing copy (messages, labels, ...) we should refer to Analytics views instead of Analytics profiles.
* Naming of code-level things should not be modified, since e.g. APIs still refer to profiles as well.

## Implementation Brief

This appears to have been updated in most instances.

The only instance found was the setting of the name field of the Select component `assets/js/modules/analytics/common/profile-select.js`. Note that any changes to this will require the associated test to be updated as this uses the text from the field `fireEvent.click( getByText( /set up a new profile/i ) );` & `expect( listItems[ 0 ].textContent ).toMatch( /set up a new profile/i );`

## QA Brief

* 

## Changelog entry

* Rename Analytics profiles to views consistently.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Confirmed initial setup page:
![image](https://user-images.githubusercontent.com/57115907/82533208-aee40480-9af7-11ea-8d2d-6b253894bcfd.png)

Checked drop downs. **Noticed 'Setup new profile' exists on view drop down**
![image](https://user-images.githubusercontent.com/57115907/82533296-d0dd8700-9af7-11ea-8126-48ee2ef4d3e3.png)

Confirmed settings page:
![image](https://user-images.githubusercontent.com/57115907/82533408-0bdfba80-9af8-11ea-8c1a-d6a939a70015.png)

Sending back to @ryanwelcher to adjust the drop down copy

**Comment by cole10up** [comment]
False alarm! I had the GA Provisionings branch selected.

![image](https://user-images.githubusercontent.com/57115907/82534661-5a8e5400-9afa-11ea-95c6-cd33ea647a93.png)

Confirmed view in the drop down. Moving to approved.

**Comment by aaemnnosttv** [comment]
@felixarntz I just noticed that this was not renamed in the Site Health fields:
![image](https://user-images.githubusercontent.com/1621608/83395211-8ff04700-a402-11ea-8758-2648e7946064.png)

Should this not also be updated as it is technically user-facing?

**Comment by felixarntz** [comment]
@aaemnnosttv Good catch. Let's do this in a follow-up PR, not critical to be in the release though.
