### ISSUE TITLE
Adsense connection stalled by Ad blocker

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1491]
## Bug Description

When using an Ad blocker extension in the browser, Adsense gets stuck at "locating accounts" and does not complete the process. Console error shows ERR_BLOCKED_BY_CLIENT on its request. 

Disabling Ad blocker on the page allows the process to complete.  

## Steps to reproduce

1. Connect the Adsense service in a browser that has an Ad blocker extension (tested[ with this one](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom?hl=en-US))
2. On the Adsense admin screen, see the message that Adsense is "locating accounts" with progress bar loading

## Screenshots

![Adsense and Adblock](https://user-images.githubusercontent.com/8108643/80989525-e8272f80-8de9-11ea-81cf-83f53ebf6600.png)

## Additional Context

 - PHP Version: 7.3.16
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.7.1
 - Device: MacBook Air

related support topic: https://wordpress.org/support/topic/google-site-kit-adsense/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When an adblocker browser plugin is active, the AdSense setup flow should display the adblocker warning as expected.
* This should be tested with a few popular adblocker extensions (particularly, with the original point of failure extension linked above).

## Implementation Brief

* Rename our adblocker "detection" script from `ads.js` to `pagead2.ads.js` so that it is more appropriately blocked for AdSense requests (that string is blocked also by AdBlock extension), which is what matters most for Site Kit usage.

## QA Brief

* 

## Changelog entry

* Fix ad blocker detection failing for popular AdBlock browser extension.

**Comment by felixarntz** [comment]
@ernee Have you been able to replicate that?

This is an expected error, but the user shouldn't even be able to get there typically, since we would show the AdBlocker warning that is baked into the plugin. So it looks like we have a bug that the warning doesn't show here.

**Comment by ernee** [comment]
@felixarntz yes, the above is from my personal site. No Adblocker warning was displayed for me- just the stalled experience.

**Comment by jamesozzie** [comment]
Similar issue in the following support topic: [https://wordpress.org/support/topic/site-kit-adsense-activation/#post-12887100](https://wordpress.org/support/topic/site-kit-adsense-activation/#post-12887100)

**Comment by felixarntz** [comment]
The problem here is that this particular adblocker seems to not block requests to our `ads.js` detection script, that's why the warning doesn't show. We should probably change that filename to be `adsense.js` - I tested that, and _that_ name was blocked as expected. It's also generally a good idea, since we're really looking to avoid AdSense being blocked, we don't care as much about _any_ ads here.

**Comment by aaemnnosttv** [comment]
IB ✅ 

Note that only the resulting entrypoint and asset src in `Assets` needs to be renamed, not the source file.

**Comment by ShahAaron** [comment]
@aaemnnosttv @felixarntz I've renamed the file from `ads.js` to `adsense.js`
Changed the src & entrypoint in `Assets` and the webpack entry
The result is that it displays ` Ad blocker detected, you need to disable it in order to set up AdSense.` whether the adblocker is on or off

**Comment by aaemnnosttv** [comment]
@ShahAaron that means the script probably isn't being loaded, or maybe you have an adblocker active? Do you have a branch pushed up for this?

**Comment by ShahAaron** [comment]
@aaemnnosttv have just #1626 with the code in

**Comment by felixarntz** [comment]
@aaemnnosttv I think we should rename the actual source script too, it would be confusing for it to have a different name than the built version.

**Comment by cole10up** [comment]
**Tested:**

Installed latest develop and activated SK.

Installed ad blocker:
![image](https://user-images.githubusercontent.com/57115907/83997815-14b3f700-a914-11ea-8c1e-f31652c13fff.png)

Noticed:
![image](https://user-images.githubusercontent.com/57115907/83997824-1bdb0500-a914-11ea-94e2-24c9d867ed44.png)

Tried to setup:
![image](https://user-images.githubusercontent.com/57115907/83997886-49c04980-a914-11ea-8f9b-31880cfac47d.png)

Confirmed happy path functioned properly with ad blocker turned off:
![image](https://user-images.githubusercontent.com/57115907/83997930-6197cd80-a914-11ea-947e-7950743a4ad0.png)

Confirmed with uBlocker and muBlocker

Passed QA ✅

**Comment by rafapontederino** [comment]
I have the same problem. The Adsense has connected to my site and waiting for approval from google (I have the Adsense already from my youtube channel), but there is something that bothers me because it mentions in the site kit dashboard "Ad blocker detected, you need to disable it in order to set up AdSense". What should I do?
![Screenshot (31)_LI](https://user-images.githubusercontent.com/80829188/111467397-add63080-8724-11eb-84d5-bd7a88b8f01f.jpg)
![Screenshot (30)_LI](https://user-images.githubusercontent.com/80829188/111467408-b169b780-8724-11eb-9d0d-91ab57ab3cfd.jpg)

**Comment by jamesozzie** [comment]
@rafapontederino Have you tried temporarily deactivating your Ad Blocker? If you're having trouble feel free to reach out in the plugins [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit/#new-post), where we'd be happy to assist you with this.

**Comment by rafapontederino** [comment]
@jamesozzie I did, and I opened my site with my phone too, but the "Adblocker detected, you need to disable it in order to set up AdSense" is still there. I have tried several times to enter the WordPress support forum but I have a problem with login.

**Comment by jamesozzie** [comment]
@rafapontederino Sorry to hear you're unable to login to the WP Support Forums. I assume you've tried a password reset, which would get sent to your phone. Ideally we can obtain your Site Health information via [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) although you would need to reference a WordPress support forum topic which you've created. If you're unable to open a support topic feel free to share your active plugins here, any of which could be resulting in this notice.

**Comment by rafapontederino** [comment]
I still cannot access WordPress support forum. Attached is my active plugins
![Screenshot (33)](https://user-images.githubusercontent.com/80829188/111507135-9e69de00-874a-11eb-90ed-c41bac023f31.png)

**Comment by jamesozzie** [comment]
I see you have the Health Check & Troubleshooting plugin active, have you tried navigating to troubleshooting mode within this plugin, while enabling only Site Kit in troubleshooting mode? When doing to please do so from a Chrome browser incognito window, to ensure browser extensions are not interfering with displaying your data.

**Comment by rafapontederino** [comment]
@jamesozzie I did navigate to troubleshooting mode with the Health Check & Troubleshooting plugin from a Chrome browser incognito window. But the result is still the same, "Adblocker detected, you need to disable it in order to set up AdSense" is still there.
![Screenshot (34)](https://user-images.githubusercontent.com/80829188/111554768-41d8e400-8787-11eb-8324-d2ecd03214e2.png)

**Comment by rafapontederino** [comment]
Hi @jamesozzie, did you find any solution for "Adblocker detected, you need to disable it in order to set up AdSense"?

**Comment by jamesozzie** [comment]
@rafapontederino Apologies for the late response. I do see some [Ad Block related referenced](https://i.imgur.com/vnJbc7B.png) when checking your site source code although I'll need to check up on this. Strange that the Health Check & Troubleshooting plugin didn't allow you to proceed, with only Site Kit active while in troubleshooting mode. 

Do you see any [console errors](https://imgur.com/KyLAzgH.png) when trying to view your dashboard, or alternative can you share any [XHR responses](https://drive.google.com/file/d/19sl0VBsTwdGhPrEIAkt9MDjWgKLex2hG/view?usp=sharing) on that page after refreshing the dashboard screen?

**Comment by rafapontederino** [comment]
@jamesozzie Look at the pictures! but I have no idea what to do after this
![Screenshot (45)](https://user-images.githubusercontent.com/80829188/112160151-30119980-8bea-11eb-933d-ecb1ae5f52c2.png)
![Screenshot (46)](https://user-images.githubusercontent.com/80829188/112160155-3142c680-8bea-11eb-858e-5789edb5229c.png)

**Comment by jamesozzie** [comment]
@rafapontederino Many thanks for sharing, this information is great to troubleshoot. 

As you're unable to access the support forums in this case I'll create a separate GitHub issue for you. Please allow me some time and I'll comment you in on that issue, we can troubleshoot from there.

**Comment by rafapontederino** [comment]
@jamesozzie Ok, many thanks for your help
