### ISSUE TITLE
Add ESLint rules to enforce our docs standards

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1493]
## Feature Description

Essentially the same as #924, but for JavaScript.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

There should be ESLint rules to enforce the following:

### Semantical
* Every description of everything starts with a capital letter (descriptions, parameter docs, return docs, ...).
* Every description of everything ends in a dot (descriptions, parameter docs, return docs, ...).
* For functions, the first word of the description must end in an "s" (this is probably 99% reliable, but most importantly should never yield a false positive - I don't think there are any exceptions to the grammatical rule of 3P verbs ending in an "s").

### Organizational
* Every `param` and `return` tag has a type and description.
* Every function doc-block should have a `since` tag.
* The order of tags (if present, for each) should be `since` (multiple entries allowed), `deprecated`, `private`, `param` (multiple entries allowed), `return`.
* For methods and functions, tags should be grouped: `since`/`deprecated`/`private` should be grouped together, separated by a blank line from `param`/`return` which should be grouped together.
* All `param` tag types and descriptions in a single doc-block should be indented in a way that they are aligned with each other.

## Implementation Brief

* Build on the work in #722 (PR: #1847) that allows us to write custom ESLint rules
* For requiring `param` and `return` types, etc., add to `.eslintrc.json`:
```json
    "jsdoc/check-types": ["error"],
    "jsdoc/require-param": ["error"],
    "jsdoc/require-param-description": ["error"],
    "jsdoc/require-param-name": ["error"],
    "jsdoc/require-param-type": ["error"],
    "jsdoc/require-returns-check": ["error"],
    "jsdoc/require-returns-description": ["error"],
    "jsdoc/require-returns-type": ["error"],
    "jsdoc/require-returns": ["error"],
    "jsdoc/no-undefined-types": ["error"],
    "jsdoc/valid-types": ["error"],
```
* Add rules for each of the points above
* Consider using https://github.com/gajus/eslint-plugin-jsdoc for some of the above rules and as inspiration/a utility library for our own JSDoc rules.
* Parse any JSDoc comments with a JSDoc parser and ensure tags like `@since` exist and match our format

JSDoc blocks can be straightforwardly-extracted using this code in an ESLint rule:

```js
'jsdoc-rule-name': {
    create( context ) {
        const source = context.getSourceCode();
        return {
            '*': ( node ) => {
                const jsDoc = source.getJSDocComment( node );
                if ( ! jsDoc ) {
                    return;
                }

                if ( ! jsDocPassesCheck( jsDoc ) ) {
                    context.report( { node, message: `Missing something in JSDoc.`, data: { name: node.name } } );
                }
            },
        };
    },
}
```

though there is likely a more efficient selector 😄 

Afterward: be sure to fix all errors flagged by ESLint.

Because of the unknowns in managing the parsers and the amount of errors encountered when enabling even the suggested rules from `eslint-plugin-jsdoc`, this is a reasonably-larged sized issue and is best-handled by someone familiar with ESLint (eg. probably me 😆 ).

## QA Brief

* Ensure no ESLint errors are encountered, and create/modify a few JSDoc blocks with JSDoc entries that should cause the above checks to fail and ensure an error is raised when running `npm run lint:js`.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
I tried to write up a specific implementation brief for this issue, but doing so required researching the available JSDoc parsers' APIs or existing ESLint JSDoc plugins (https://github.com/gajus/eslint-plugin-jsdoc) out there that we could integrate into our own rules to build some of the more esoteric ones like ordering and rules about grammar in comment text.

Unfortunately there isn't anything plug-and-play that will handle our cases here, so we need to build a set of custom ESLint rules that also parse JSDoc blocks and check them for certain tags. I tried to provide examples but I don't want to spend too much time defining this one especially as I think some of the points are reasonably well-served by code review.

If you'd rather I provide a very explicit IB let me know, but it's a fair bit of API experimentation that might be better officially allocated in a sprint planning meeting than done as definition work.

**Comment by felixarntz** [comment]
@tofumatt IB pretty much LGTM, just a general question (since some of it is high-level, which I think is okay overall):

I would think there's existing rules we could use or configure to enforce correct indentation (e.g. all `param` docs should be aligned the same way)? Also, is there something existing we could use to say "everything should have `since`", "there should be no blank line between `param` and `return`", "there should be a blank line above `param`", these kinds of things?

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

* Tested many different doc block variations
* Found rules are generally well-enforced
* Found a few minor gaps in logic

The following is considered to be a valid block

```js
/**
 * Checks description.
 *
 *
 * @since asdfsdf something happened
 *
 * @since
 * @deprecated use at your own risk
 *
 *
 * @private
 *
 * @param {Object} buz A parameter.
 *
 *
 * @param {null}   qux Q stuff.
 *
 * @return {string} Something.
 */
```

* Allows for blank lines between tags of the same type/group (these should probably always be adjacent without blanks between)
* Does not require a value is passed to `@since` tag, and allows for a non-version-like value
* Does not enforce the same rules on the description of the `@since` or `@deprecated` tags when present

Some of these may be tricky to address perfectly, but I think we can at least:
* Disallow empty lines between adjacent grouped tags
* Disallow more than a single empty line, anywhere in the block
* Require `@since` to have and start with a version-like value e.g `/^[1-9a-z](\.[0-9a-z]+){2,}/`
* Require `@since` description to start with a capital letter and end in a full stop, **if present**
    - Require a description for all instances except the first
* Require `@deprecated` tag to have a description that starts with a capital letter and ends in a full stop

The above example block would then be required to meet these like so:
```js
/**
 * Checks description.
 *
 * @since x.x.x.x
 * @since x.x.x.y Something happened.
 * @deprecated Use at your own risk.
 * @private
 *
 * @param {Object} buz A parameter.
 * @param {null}   qux Q stuff.
 *
 * @return {string} Something.
 */
```

Maybe this is being a bit overly strict, so if it's a ton of effort to implement then it's probably not worth it, but I feel like these should all be reasonably doable.

Perhaps most of this would be better addressed in a follow-up issue, but I feel like these two in particular should be addressed here:
* Disallow empty lines between adjacent grouped tags
* Require `@since` to have and start with a version-like value e.g `/^[1-9a-z](\.[0-9a-z]+){2,}/`

cc: @tofumatt

**Comment by felixarntz** [comment]
@tofumatt @aaemnnosttv Since this is not critical for plugin usage and therefore shouldn't block the release, I suggest we create a follow-up issue to fix the above valid points and then consider this one completed.

**Comment by aaemnnosttv** [comment]
Moving this forward to approval in favor of a new issue to cover the above enhancements.

**Comment by aaemnnosttv** [comment]
@felixarntz @tofumatt the new issue is here (https://github.com/google/site-kit-wp/issues/2154) and ready for an IB 👍
