### ISSUE TITLE
Fix AdSense tag issues in AMP

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1495]
## Bug Description

It can happen that the AdSense module detects Site Kit's own tag as an existing tag, altering the UX accordingly, which obviously shouldn't happen then. This happens because the `amp-auto-ads` tag is in one place rendered even when a `tagverify` query parameter is present.

Furthermore, for sites where their theme does not support the `wp_body_open` action, the `amp-auto-ads` tag currently is only printed if the module setup is complete, which is incorrect. The snippet should be placed as soon as the client ID is available, unless it was opted out from.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's own AdSense snippet should not be detected as an existing tag.
* Site Kit's AdSense snippets should not be rendered when a `tagverify` query parameter is present.
* Site Kit's AdSense snippets should be rendered already when the module setup is not complete yet.

## Implementation Brief

* Add the following to `AdSense::amp_content_add_auto_ads()` and similarly to `AdSense::amp_data_load_auto_ads_component()`:
```php
if ( $this->context->input()->filter( INPUT_GET, 'tagverify', FILTER_VALIDATE_BOOLEAN ) ) {
	return $content;
}
```
* Remove `AdSense::is_connected()` checks from the same two methods.
* Merge #1496.

## QA Brief

* 

## Changelog entry

* Fix bug where `amp-auto-ads` snippet would not always be printed if the theme didn't support the `wp_body_open` action.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ShahAaron** [comment]
Tested

Activate AMP plugin
Set up Adsense account
On front end checked `amp-auto-ads` tag is output
Added `?tagverify=1` parameter and tag is not output

Passed QA ✅
