### ISSUE TITLE
Search Console deep links may point to incorrect URL

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1497]
## Bug Description

The Search Console deep links included in various places include a `resource_id` query parameter that identifies the Search Console property to show data for. Currently it uses the site URL, which is not really accurate and may result in incorrect URLs if the Search Console property in use slightly differs from that URL (e.g. if it is a domain property).

Also, a few Search Console deep links also have a URL structure equivalent to `authuser=1`. These URLs start with `search.google.com/u/1/`, where `/u/#/` should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Deep links to Search Console should rely on the actual Search Console property active instead of assuming it is the site's URL.
* Deep links to Search Console should not have any user ID in the path

## Implementation Brief

* Replace usage of `global.googlesitekit.admin.siteURL` with `getModulesData()[ 'search-console' ].settings.propertyID` everywhere it's used for Search Console deep links (search for `resource_id=`).
* Replace all instances of `https://search.google.com/u/*/` with `https://search.google.com/`

## QA Brief

* 

## Changelog entry

* Fix Search Console deep links to use the correct property identifier.

**Comment by aaemnnosttv** [comment]
@felixarntz in reviewing this, I noticed that 3 of these links also have the `/u/1/` prefix in the URL (i.e. `authuser=1`) which obviously shouldn't be there. I'll update the AC+IB to include this also but everything else sounds good 👍 

IB ✅

**Comment by ShahAaron** [comment]
@felixarntz could I check am I replacing usage of global.googlesitekit.admin.siteURL with getModulesData()[ 'search-console' ].settings.propertyID where `resource_id=`or `search-console?resource_id=`. There are many instances where `resource_id=` like `search-analytics?resource_id=`

**Comment by felixarntz** [comment]
@ShahAaron All of these should be adjusted since they all deal with Search Console. The problem here is that we should never assume the site URL is also the Search Console property for the site. For most cases it will be, but not all. For example if you have a Search Console domain property, it will look like `sc-domain:example.com` rather than `https://example.com`, and linking with the site URL would result in a 404 because there probably is no Search Console property for that then.

**Comment by cole10up** [comment]
**Tested**

Ran a series of tests through multiple hosts. Setting up search console, resetting SK, setting up again. Checking network, no raised issues and happy path looking good.

![image](https://user-images.githubusercontent.com/57115907/81895641-93ad4e00-9567-11ea-9b57-95b4efd77a52.png)

Passed QA ✅
