### ISSUE TITLE
Create `modules/search-console` datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1498]
Similar to #1224, #1248, #1385, Search Console should receive a `modules/search-console` datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Introduce datastore `modules/search-console` that is registered on `googlesitekit.data` and exported from `assets/js/modules/search-console/datastore`.
* Rename `assets/js/modules/search-console/index.js` to `assets/js/modules/search-console/index.legacy.js` and update relevant import references.
* Add new `assets/js/modules/search-console/index.js` that for now simply imports from `./datastore`.
* Introduce JS entrypoint asset `googlesitekit-modules-search-console.js` with similar handle in PHP. It should simply import from `./modules/search-console`.
* The datastore should for now only expose a single `getPropertyID` selector, powered by the capabilities of `createSettingsStore` (called via `getModuleStore`).

## Implementation Brief

* Create new directory `datastore` in `assets/js/modules/search-console` and create `index.js` in it.
* Add new `assets/js/modules/search-console/index.js` that for now simply imports from `./datastore`.
* Rename `assets/js/modules/search-console/index.js` to `assets/js/modules/search-console/index.legacy.js` and update relevant import references.
* Create `googlesitekit-modules-search-console.js` in `assets/js` and import `./modules/search-console` into it.
* Add a new entry point in `webpack.config.js` called `googlesitekit-modules-search-console` that uses `assets/js/googlesitekit-modules-search-console.js`.
* Set up a matching handle in `includes/Modules/Search_Console.php`  by having the `Search_Console` console class implement the `Module_With_Assets` interface and use `Module_With_Assets_Trait` and creating a `setup_assets` similar to https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L1292
* In `assets/js/modules/search-console/datastore/index.js` import `Modules` from `googlesitekit-modules` and create a new base store using `Modules.createModuleStore` with the name of `search-console`.
* expose a `getPropertyID` selector by passing `settingsSlugs: ['propertyID']` when calling `createModuleStore` - see https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/index.js for reference.

## QA Brief

* 

## Changelog entry

* Introduce `modules/search-console` datastore in JS.

**Comment by aaemnnosttv** [comment]
IB looks good @ryanwelcher - just a few details to clarify:

> Set up a matching handle in `includes/Modules/Search_Console.php` similar to Analytics

This involves implementing the `Module_With_Assets` interface and using the `Module_With_Assets_Trait`.

> expose a `getPropertyID` selector

This is done automatically by the settings store which is created internally by `createModuleStore` using the `settingsSlugs` provided to it. In this case, the only setting is `propertyID` so we only need to pass this as a string in an array when calling `createModuleStore`. This creates all of the setting-specific actions and selectors as well as general settings datastore "components", not just the one selector 👍 
E.g.
https://github.com/google/site-kit-wp/blob/f9d9806a6dc860dd64a5672ebcc802c584479374/assets/js/modules/analytics/datastore/index.js#L32-L43

**Comment by ryanwelcher** [comment]
Thanks for the clarification @aaemnnosttv. IB updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA, moving to approval ✅
