### ISSUE TITLE
Refactor Search Console settings using datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1499]
## Feature Description

Similar to #1101, #1014, and #1386 (but a lot simpler here!), let's refactor the Search Console settings (no setup involved here) to use the datastore introduced by #1498.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All changes should be made within the `assets/js/modules/search-console` directory.
* There should be a `SettingsView` component that displays the Search Console settings. It should look the same as it does today, except:
    * "Connected URL" should say "Connected Property"
    * The value displayed should not be the site URL, but the Search Console property ID (via `getPropertyID` selector)
* There should be a `SettingsMain` component for the settings panel, that for now just always displays `SettingsView`. While it is not strictly necessary, it's good for consistency with the other module components infrastructure, and it keeps it internal to the `SettingsMain` component that Search Console does not have any way to edit settings (i.e. there is no need for a `SettingsEdit` component).
* The components should only access datastore data, never anything from globals.
* There should be a Search Console/Settings section in Storybook with the settings panel in different states, similar to how it was added for the issues linked above.
* The implementation should follow patterns established as part of the issues linked above.

## Implementation Brief

This work is dependant on the datastore introduced by #1498
All changes to be in `assets/js/modules/search-console`
* Remane `assets/js/modules/search-console/settings/search-console-settings-status.js` to `assets/js/modules/search-console/settings/settings-view.js`
    * In `assets/js/modules/search-console/settings/settings-view.js` change "Connected URL" to say "Connected Property"
    * In `assets/js/modules/search-console/settings/settings-view.js` change the value displayed should not be the site URL, but the Search Console property ID (via `getPropertyID` selector)
* Create `SettingsMain` in `assets/js/modules/search-console/settings/settings-main.js` that for now just always displays `SettingsView`. See #1101 
* Move filter for adding the modules settings component from `index.legacy.js` to `index.js`. Note to insure that the new component needs to be wrapped using `RegistryProvider` before being passed to the filter. 

`<Data.RegistryProvider value={ Data }>
        .......
</Data.RegistryProvider>`

* There should be a Search Console/Settings section in Storybook ( `stories/module-search-console-settings.stories.js` ) with the settings panel in different states, similar to how it was added for the issues linked above. See https://github.com/google/site-kit-wp/blob/refactor/1014-adsense-setup-components/stories/module-analytics-settings.stories.js

## QA Brief

* 

## Changelog entry

* Display actual Search Console property used in settings, and migrate to using the datastore.

**Comment by felixarntz** [comment]
@ShahAaron IB looks good for the most part. Something to add here is that the filter for the refactored component should be moved from the `index.legacy.js` file to `index.js`. The legacy file should only have references to code that has not been refactored yet. Also keep in mind that the new component needs to be wrapped in a `RegistryProvider` for the filter.

With these few changes the IB should be good to go.

**Comment by felixarntz** [comment]
IB ✅

**Comment by ShahAaron** [comment]
@felixarntz is a test required for `settings-main.js`. I haven't added on as `SettingsMain ` just displays `SettingsView`. When I look at `Analytics` and `Adsense` they only have tests for editing

**Comment by felixarntz** [comment]
@ShahAaron Since `SettingsMain` basically just passes through to `SettingsView`, I think that doesn't need one. 👍

**Comment by cole10up** [comment]
**Tested**

Installed latest develop and activated SK
Confirmed property is listed on the settings page
![image](https://user-images.githubusercontent.com/57115907/83097780-cbcf8900-a05d-11ea-9a1d-280d1d787a36.png)

Confirmed SK can be reset and display the correct property.

Passed QA ✅
