### ISSUE TITLE
Scaffold `modules/pagespeed-insights` datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1500]
## Feature Description

Similar to #1224, #1248, #1385, #1498 (but a lot simpler here), PageSpeed Insights should receive a `modules/pagespeed-insights` datastore.

Note that (as with the other refactorings) we'll initially focus on purely setup/settings. Since there is no PSI-specific data dependency in that, we technically don't need the datastore yet. So this issue is really about scaffolding an empty datastore (we'll need it as soon as we start refactoring the dashboard).

As part of this issue, we should add one minor change to the `core/site` store to prepare for refactoring PSI settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### New store `modules/pagespeed-insights`
* Introduce datastore `modules/pagespeed-insights` that is registered on `googlesitekit.data` and exported from `assets/js/modules/pagespeed-insights/datastore`.
* Rename `assets/js/modules/pagespeed-insights/index.js` to `assets/js/modules/pagespeed-insights/index.legacy.js` and update relevant import references.
* Add new `assets/js/modules/pagespeed-insights/index.js` that for now simply imports from `./datastore`.
* Introduce JS entrypoint asset `googlesitekit-modules-pagespeed-insights.js` with similar handle in PHP. It should simply import from `./modules/pagespeed-insights`.
* The datastore should simply use `createModuleStore` but not expose any other selectors/actions.

### Existing store enhancements `core/site`
* Modify the existing `getAdminURL()` selector to become `getAdminURL( page, args )` (both parameters optional). If `page` is provided, the `adminURL` should receive a corresponding `page` query parameter. If `args` are provided, these should be added as query parameters too. If `adminURL` is `undefined` (not loaded), the entire selector should return `undefined`. This is now essentially our old `getSiteKitAdminURL( page, args )` function in a datastore way.

## Implementation Brief

* Create new directory `datastore` in `assets/js/modules/pagespeed-insights` and create `index.js` in it.
* Add new `assets/js/modules/pagespeed-insights/index.js` that for now simply imports from `./datastore`.
* Rename `assets/js/modules/search-pagespeed-insights/index.js` to `assets/js/modules/pagespeed-insights/index.legacy.js` and update relevant import references.
* Create `googlesitekit-modules-pagespeed-insights.js` in `assets/js` and import `./modules/pagespeed-insights` into it.
* Add a new entry point in `webpack.config.js` called `googlesitekit-modules-pagespeed-insights` that uses `assets/js/googlesitekit-modules-pagespeed-insights.js`.
* Set up a matching handle in `includes/Modules/PageSpeed_Insights.php`  by having the `PageSpeed_Insights` console class implement the `Module_With_Assets` interface and use `Module_With_Assets_Trait` and creating a `setup_assets` similar to https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L1292
* In `assets/js/modules/search-console/datastore/index.js` import `Modules` from `googlesitekit-modules` and create a new base store using `Modules.createModuleStore` with the name of `pagespeed-insights`.
* In the `core/site` store, modify the existing `getAdminURL()` selector to become `getAdminURL( page, args )` (both parameters optional). If page is provided, the `adminURL` should receive a corresponding `page` query parameter. If `args` are provided, these should be added as query parameters too. If `adminURL` is `undefined` (not loaded), the entire selector should return `undefined`.

## QA Brief

* 

## Changelog entry

* Introduce `modules/pagespeed-insights` datastore in JS.

**Comment by felixarntz** [comment]
IB ✅ 

Thanks for being thorough here @ryanwelcher - I think generally for engineering-based issues like this where the ACs already are some rough IB almost, it's okay to omit the similar parts and refer to the ACs in the IB. Then you can focus the IB more on specific details that are important.

**Comment by ShahAaron** [comment]
Develop pulled
Tests run JS & PHP Unit tests, e2e & Visual Regression - all passed

Code checked - passed
A/C's - passed

QA ✅
