### ISSUE TITLE
Refactor PageSpeed Insights settings using datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1501]
## Feature Description

Similar to #1101, #1014, #1386, and #1499 (but a lot simpler here!), let's refactor the PageSpeed Insights settings (no setup involved here) to use our datastore and other best practices.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All changes should be made within the `assets/js/modules/pagespeed-insights` directory.
* There should be a `SettingsView` component that displays the same text with link that PageSpeed Insights settings display today (use `getAdminURL( 'googlesitekit-dashboard' )` via #1500 to get the URL).
* There should be a `SettingsMain` component for the settings panel, that for now just always displays `SettingsView`. While it is not strictly necessary, it's good for consistency with the other module components infrastructure, and it keeps it internal to the `SettingsMain` component that PageSpeed Insights does not have any way to edit settings (i.e. there is no need for a `SettingsEdit` component).
* The components should only access datastore data, never anything from globals.
* There should be a PageSpeed Insights/Settings section in Storybook with the settings panel in different states, similar to how it was added for the issues linked above.
* The implementation should follow patterns established as part of the issues linked above.

## Implementation Brief

See https://github.com/google/site-kit-wp/issues/1499 for similar work done on Search Console settings.
All work to be done in `assets/js/modules/pagespeed-insights`.
- Create a new `SettingsView` component  `assets/js/modules/pagespeed-insights/settings/settings-view.js` this is to include what is largely in `assets/js/modules/pagespeed-insights/settings/index.js` now. It should display the same text with link that PageSpeed Insights settings displays today (use `getAdminURL( 'googlesitekit-dashboard' )` via #1500 to get the URL).
- Create a new `SettingsMain` component  `assets/js/modules/pagespeed-insights/settings/settings-main.js`. This is to displays `SettingsView` only (i.e. there is no need for a `SettingsEdit` component).
- `assets/js/modules/pagespeed-insights/settings/index.js` to be refactored to import `SettingsMain` only.
- Move filter for adding the modules settings component from `assets/js/modules/pagespeed-insights/index.legacy.js` to `assets/js/modules/pagespeed-insights/index.js`. ~~Note to ensure that the new component needs to be wrapped using RegistryProvider before being passed to the filter. `<Data.RegistryProvider value={ Data }> ....... </Data.RegistryProvider>`~~  
**This is no longer necessary due to the addition of the `<Root>` component.**
- Create `stories/module-pagespeed-insights-settings.stories.js` a new PageSpeed Insights/Settings section in Storybook with the settings panel in different states.

## QA Brief

* 

## Changelog entry

* Migrate PageSpeed Insights settings to using the datastore.

**Comment by ShahAaron** [comment]
@felixarntz does the the new component need to be wrapped using `RegistryProvider` before being passed to the filter.
`<Data.RegistryProvider value={ Data }> ....... </Data.RegistryProvider>`
Also is a test required for `SettingsMain` a it only uses `SettingsView` and not `SettingsEdit`

**Comment by felixarntz** [comment]
@ShahAaron Yes, currently all our entry components relying on datastores will need to be wrapped like this (will change once #1530 is in place).

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

PageSpeed Insights module settings continues to work as expected after activating. Toggling open, closed, edit, cancel, and module disconnection all work as expected.
