### ISSUE TITLE
Update E2E tests to use proxy authentication by default

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1503]
## Feature Description

Currently the authenticated state that is implemented in E2E tests uses the old pre-proxy GCP-based authentication. This doesn't make much difference in terms of authentication as it is mocked/fake state anyways; there's no real authentication happening. However, there is a growing amount of behavior that is dependent on whether or not the site is configured to use the proxy or not, so it doesn't make sense any more for E2E tests to run in this context primarily when non-proxy sites are by far the minority of environments.

We can keep the ability to use the GCP authentication to ensure backwards compatibility with the alternate setup flow, but we should be using proxy-based authentication for any tests that aren't specifically testing something which is specific to `usingProxy`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new E2E utility plugin for setting proxy credentials  
Essentially a proxy-version of [`gcp-credentials.php`](https://github.com/google/site-kit-wp/blob/11e70c4c2cd51861a0db446da0fe995501f1ca12/tests/e2e/plugins/gcp-credentials.php)
* There should be a new E2E utility plugin for faking proxy authentication  
Essentially a proxy-version of [`auth.php`](https://github.com/google/site-kit-wp/blob/11e70c4c2cd51861a0db446da0fe995501f1ca12/tests/e2e/plugins/auth.php)  
	- ~~The proxy auth plugin should use the current `Plugin Name: E2E Tests Auth Plugin` to be used in place of the current~~  
        **We decided to use a new name to be explicit with:** "E2E Tests Proxy Auth Plugin"
	- The GCP auth plugin should be named "E2E Tests GCP Auth Plugin" and would be referenced in tests as `e2e-tests-gcp-auth-plugin`
* Move `e2e/specs/auth-*` to a new `e2e/specs/auth/` directory and remove `auth-` prefix from file name
* Test files which are specific to GCP auth should be renamed with a `gcp-` prefix and have their descriptions (`describe(...)`) updated accordingly
* No tests should be skipped based on lack of proxy authentication (e.g. #1479)

## Implementation Brief

* Rename `auth.php` to `gcp-auth.php`
	- Rename plugin to "E2E Tests GCP Auth Plugin"
* Add a `tests/e2e/plugins/proxy-credentials.php` which sets credentials with a proxy-based client ID
* Add a `tests/e2e/plugins/proxy-auth.php` which requires `proxy-credentials.php`
	- Plugin Name: E2E Tests Auth Plugin
* Reorganize auth specs according to AC
* Update GCP-specific test filenames and descriptions:
	- `auth-flow-admin-2.test.js`
	- `auth-flow.test.js`
	- `auth-setup-search-console.test.js`
	- `auth-setup-verification.test.js`
* Update non-GCP specific tests to use proxy (mostly updating classes referenced)
	- `plugin-activation.test.js`
	- `plugin-reset.test.js`
* Update any skipped tests that require proxy authentication to no longer be skipped

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
