### ISSUE TITLE
Insert HTML comments for each module/product snippet

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1504]
## Feature Description

For the different snippets place via Site Kit it may be useful to insert a comment such as `inserted via Site Kit`.

The AdSense module already provides a useful hint in the form of the below:
`tag_partner: "site_kit"` 

While there are additional hints of Site Kit placements more obvious comments may assist in troubleshooting issues, in particular for Analytics and Tag Manager users. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All snippets which Site Kit places for Google services should be annotated with surrounding HTML comments:
    * Above: `Google xyz snippet added by Site Kit`
    * Below: `End Google xyz snippet added by Site Kit`
    * See below for the different "xyz" permutations.
* For AdSense (web and AMP): `AdSense`, `AdSense AMP`
* For Analytics (web and AMP, plus opt-out): `Analytics`, `Analytics AMP`, `Analytics opt-out`, `Analytics AMP opt-out` (all of these annotations should also be used for the respective GA4 snippets in the `analytics-4` module)
* For Tag Manager (web and AMP): `Tag Manager`, `Tag Manager AMP`
* Anywhere a snippet is rendered for (AMP) Stories, it should also use the regular `* AMP` annotation.
* The comments should always be separated from the actual snippet through a line break, i.e. they should not appear in the same line.

## Implementation Brief

As per the AC add HTML comments above and below the placement of each tag snippet.  Ensure the comments are separated from the tag snippet using line breaks.  The comments are:
* Above: `Google xyz snippet added by Site Kit`
* Below: `End Google xyz snippet added by Site Kit`

In each case replace `xyz` with the relevant text in the AC.

* For Adsense add the comments to the output of the tag snippets in the `render` methods:
  * `Modules/Adsense/Web_Tag`
  * `Modules/Adsense/AMP_Tag`
    *  Note that the comments all need to be added to the `amp_content_add_auto_ads` and `set_story_ad_slot_id` methods
* For Analytics AMP `render` methods:
  * `Modules/Analytics/AMP_Tag`
* For Tag Manager `render` methods:
  * `Modules/Tag_Manager/AMP_Tag`
  * `Modules/Tag_Manager/Web_Tag`
* For Analytics and Analytics 4 use the `script_loader_tag` filter to add the comments: 
  * `Modules/Analytics/Web_Tag`
  * `Modules/Analytics_4/Web_Tag`

## QA Brief

* As per the AC, all inserted snippets by Site Kit will have surrounding HTML comments. 
* You will need to enable all the modules to test every snippets. 
* For Opt Out snippets, you'll need to have Analytics Opt Out Enabled
* Please check for both logged in and not logged in state!
* Use View Source to inspect the source code and feel free to use "Ctrl+F / Cmd+F" to find the relevant parts of the source code. ie. 'snippet added by Site Kit'

## Changelog entry

* Add surrounding comments to all HTML tags output by Site Kit modules.

**Comment by Hazlitte** [comment]
@felixarntz @jamesozzie I have added an IB for this.  Note that `render` methods are not being used to output all tag snippets, in some cases `wp_enqueue_script` is being used. (as noted in the IB)

**Comment by eugene-manuilov** [comment]
> Note that wp_enqueue_script is used instead of render methods so the comments cannot be added for:
> Modules/Analytics/Web_tag
> Modules/Analytics_4/Web_tag

@Hazlitte there is the [`script_loader_tag`](https://developer.wordpress.org/reference/hooks/script_loader_tag/) filter that we can use to add comments to enqueued scripts.

**Comment by Hazlitte** [comment]
Thanks @eugene-manuilov, I have updated the IB 👍

**Comment by eugene-manuilov** [comment]
@Hazlitte we also need to mention the Analytics-4 module.

**Comment by Hazlitte** [comment]
👍

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by tofumatt** [comment]
Tagging this as a good first issue—the approach is straightforward though to test the output it will require setting up a site with AdSense, Analytics, Google Analytics 4, and Tag Manager.

**Comment by aaemnnosttv** [comment]
@kuasha420 would you please add a QA brief?

**Comment by kuasha420** [comment]
@aaemnnosttv Done. Should it be a QA:Eng as well?

**Comment by aaemnnosttv** [comment]
@kuasha420 thanks! I don't think it's needed but we can always add it later if we feel it is 👍

**Comment by kuasha420** [comment]
@wpdarren as per our slack discussion with @aaemnnosttv, can you process this and create a separate issue accordingly. 

Cheers.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

All snippets which Site Kit places for Google services have annotated with surrounding HTML comments:

- For AdSense (web and AMP): AdSense, AdSense AMP
- For Analytics (web and AMP, plus opt-out): Analytics, Analytics AMP, Analytics opt-out, Analytics AMP opt-out [Screenshot](https://user-images.githubusercontent.com/73545194/131852494-c1a8d396-89d1-482d-8797-de02f95aff1a.png)

- For Tag Manager (web and AMP): Tag Manager, Tag Manager AMP [Screenshot](https://user-images.githubusercontent.com/73545194/131852513-491f69ac-f4ef-45fb-9346-63d1cee81bca.png)

- Tested the HTML comments when logged in and out. 
- The comments are separated from the actual snippet through a line break, i.e. they do not appear in the same line.

![image](https://user-images.githubusercontent.com/73545194/131852469-f7f920f5-c13b-4503-b000-6972839568ca.png)
