### ISSUE TITLE
Render amp-analytics in story post type (Web Stories plugin integration)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1506]
## Feature Description

We should integrate with the Web Stories plugin to place our `amp-analytics` snippet within stories.

Responsibilities between the two plugins should be distributed the following:
* Site Kit will take care of rendering the basic `amp-analytics` snippet, with tracking ID etc. Site Kit can hook into the Web Stories `web_stories_print_analytics` action for that.
* Web Stories will take care of adding the necessary story-specific events. Web Stories can hook into the `googlesitekit_amp_gtag_opt` filter for that and add the event configuration e.g. if `is_singular( 'amp_story' )` (since that filter fires for any AMP context, not just stories).

Web Stories will need to make slight adjustments accordingly (see https://github.com/google/web-stories-wp/issues/1168): The plugin should remove the functionality where it renders the snippet itself (replicating a lot of Site Kit logic) and instead simply filter into Site Kit's `googlesitekit_amp_gtag_opt` to add story-specific events for stories.

cc @swissspidy 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should place the `amp-analytics` snippet based on the regular configuration in Web Stories posts (using `web_stories_print_analytics`).
* Secondary: Site Kit should ensure no `amp-auto-ads` tag is rendered for Web Stories.

## Implementation Brief

* In the `Analytics::register` method, hook the existing `$print_amp_gtag` closure into `web_stories_print_analytics`.
* Update the `Context::is_amp` method to also return true if `is_singular( 'web-story' )`. Since that is now decoupled from the AMP plugin, but itself is always using AMP anyway, we can reliably do that.
* Update `AdSense` class methods where there are checks for `is_singular( 'amp_story' )` to also check `is_singular( 'web-story' )` in the same way. Let's keep the `amp_story` ones for backward-compatibility.

## QA Brief

* 

## Changelog entry

* Render `amp-analytics` snippet for Web Stories.

**Comment by felixarntz** [comment]
@swissspidy Does the above sound good to you? Just double-checking, Web Stories's story post type always will have `is_amp_endpoint` return true right? Since we're currently checking that in the function - I guess no changes will be needed here on our end?

**Comment by swissspidy** [comment]
1. Uhm, unsure. Unless the AMP plugin is active, that function won‘t exist. Not sure right now what it returns for stories if it‘s active (will test tomorrow), but I think `false`. I would not rely on this function for stories and instead just check the post type if needed.
2. Correct.
3. Correct.

**Comment by felixarntz** [comment]
@swissspidy Ah that's a good point then. We can simply update our own `Context::is_amp()` method then, to return `true` if `is_singular( 'amp_story' )` too. I'll update the IB.

**Comment by swissspidy** [comment]
`is_singular( 'web-story' )` 🙂
But you'll quickly notice that when testing 😉

**Comment by felixarntz** [comment]
@swissspidy Oh that reminds me of something, we also check right now in some places for `amp_story` post type to avoid placing `amp-auto-ads` then because it's not supported in stories. Because of the limited use of regular actions and filters in Web Stories that may not be as much of a problem, but I actually think we should make sure and include `is_singular( 'web-story' )` checks in these areas too.

**Comment by swissspidy** [comment]
IB approved 👍

**Comment by ryanwelcher** [comment]
This looks to have been QA in the PR - https://github.com/google/site-kit-wp/pull/1596#pullrequestreview-420020682
