### ISSUE TITLE
Ensure activating/deactivating a module refreshes user authentication state

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1507]
## Bug Description

Activating/deactivating a module may change the scopes that the current user needs to grant access for. While #1175 introduced the `core/user` store and #1179 introduced the `core/modules` store, these now need to integrate with each other so that changing module activation state results in the user authentication data to be refetched.

This is somewhat an enhancement, but also a bug since currently this would result in a broken experience.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Changing module activation state via the `core/modules` store actions should trigger a refetch of the `core/user/data/authentication` API datapoint (via `core/user` store action). The API call to activate/deactivate the module must happen first, so that the authentication data in the following call acts upon the new module state. This should be integrated in a way that the `core/modules` action only completes once it the `core/user` API fetch call has been completed.
* It must be ensured that this re-fetch actually performs the fetch. The `core/user/data/authentication` data is preloaded via the `apiFetch` preloading middleware, but here it must be bypassed (see #1478).

## Implementation Brief

In`assets/js/googlesitekit/modules/datastore/modules.js`:
* Create a new action constant called `REFETCH_AUTHENICATION`
* Add a `yield` statement to both `activateModule` and `deactivateModule` actions before the return that yields the following object`{ payload: {}, type: REFETCH_AUTHENTICATION}`
* import the STORE_NAME from `assets/js/googlesitekit/datastore/user` as `CORE_USER_STORE_NAME`
* Add a control for `REFETCH_AUTHENTICATION` [that uses `createRegistryControl`](https://github.com/google/site-kit-wp/blob/11e70c4c2cd51861a0db446da0fe995501f1ca12/assets/js/modules/analytics/datastore/settings.js#L66) from `Data` that that accepts  `params` object parameter and calls`registry.dispatch( CORE_USER_STORE_NAME).fetchAuthentication()`

In `assets/js/googlesitekit/datastore/user/authentication.js`
* Modify the `FETCH_AUTHENTICATION` control  to call to bypass caching with`return API.get( 'core', 'user', 'authentication', null, { useCache: false } )`

Note if #1175 has not been merged, this work should branch from the associated PR.

## QA Brief

* 

## Changelog entry

* Enhance functionality of new `core/modules` store so that module activation/deactivation results in authentication data to be refreshed.

**Comment by felixarntz** [comment]
IB generally ✅ 

@ryanwelcher One detail here that is due to the enhancements from #1478 is that we need to ensure that routes with `useCache` set to `false` also bypass any eventual preloaded API responses, which is currently not the case. In https://github.com/google/site-kit-wp/issues/1478#issuecomment-624696055 I added a suggestion on how we could generally fix this, simply by adding an additional query parameter in such cases to avoid the preloaded data from being "matched" with the request. Let's try that as part of this PR.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
