### ISSUE TITLE
AdSense reports URL includes user index

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1516]
## Bug Description

The Adsense reports URL returned by `GET:reports-url` contains the authuser index hardcoded to `0`. This should be removed. Deep links for correct auth user will be handled in #1456 

https://github.com/google/site-kit-wp/blob/a454d88f0c1a24b2f7fd1418753c86ac3b8c8d42/includes/Modules/AdSense.php#L527

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No AdSense URLs should include `/u/#` (where `#` is any number) in the path

## Implementation Brief

* Update the URL above to not include the `/u/0` segment

## QA Brief

* 

## Changelog entry

* Fix AdSense report URL to not include user-specific affix.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed latest develop and confirmed existing account reports link drives to the correct URL.
![image](https://user-images.githubusercontent.com/57115907/81896330-429e5980-9569-11ea-884e-cbc40793f054.png)

Checked both links on the Adsense page:

![image](https://user-images.githubusercontent.com/57115907/81896369-55b12980-9569-11ea-83f7-6af31861c716.png)

Checked a separate host with Adsense being provisioned

![image](https://user-images.githubusercontent.com/57115907/81896405-65c90900-9569-11ea-939c-081615f102e9.png)

Checked Dashboard:

![image](https://user-images.githubusercontent.com/57115907/81896474-885b2200-9569-11ea-97b7-6fd7279c6715.png)

All good on my end

Passed QA ✅
