### ISSUE TITLE
Settings rollback prevents profile creation when creating new property

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1517]
## Bug Description

The new settings rollback that happens in the `SettingsEdit` component prevents profile creation when creating a new property.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/81289525-3d27a780-906f-11ea-8339-1cb817cd6669.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Settings rollback must only happen when transitioning from settings edit to settings view, if settings have changed

## Implementation Brief

* Move `useEffect` triggering rollback to `SettingsMain` and add `! isEditing` into condition guarding `rollbackSettings` action call
* Merge #1519 

## QA Brief

* 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
All good from code review; just assigning to you for the merge! 👍

**Comment by felixarntz** [comment]
QA ✅ 

Creating a new property and profile with new Analytics flow worked as expected.
