### ISSUE TITLE
Error Setting up with WPML

### ISSUE THREAD

**Issue by luizeof** [google/site-kit-wp#1520]
## Bug Description

When I try to install the Site Kit with WPML, in any language or using "all" language, the Google Site Kit does not allow to continue as it takes the URL with the language, /en or /pt-br for example. You should get the website address without these suffixes.

## Steps to reproduce

1. Website running WPML
2. Install Site Kit
3. Try to Configure, you will see the image bellow:

## Screenshots

![da7c611c-a0d7-423e-a7f2-051f8a651f91](https://user-images.githubusercontent.com/257004/81298350-0b9ce500-904b-11ea-84ae-13d0ba46ce34.png)

## Additional Context

 - PHP Version: 7.3
 - OS: Windows
 - Browser: Chrome
 - Plugin Version : 1.7.1 or newer
 - Device: N/A
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by luizeof** [comment]
#1449 seems to solve the problem, but I will wait for the next version.

**Comment by jamesozzie** [comment]
@luizeof Thanks for reporting. Let's close this one with #1116 already open.

**Comment by luizeof** [comment]
@jamesozzie after the recent release, I can confirm that this bug persists.


When the Site Verification returns, duplicate the site address, see the url:

´https://powertic.com/pt-br/powertic.com/wp-admin/?action=googlesitekit_proxy_setup&googlesitekit_code=sitekit-....&googlesitekit_site_code...´

**Comment by jamesozzie** [comment]
@luizeof Thanks for the update. We're still working on this issue at present, with some progress made as of #1116.

**Comment by javierlorente** [comment]
It's solved?

**Comment by jamesozzie** [comment]
@javierlorente Setup should proceed fine with WPML, with more information on #1116. If you do encounter any issues feel free to create a new WordPresss support topic, while sharing your additional context such as your [Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/), within the topic or using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/).
