### ISSUE TITLE
Analytics: Reporting periods displaying 1/1/70 start and end date for sites with low traffic

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1522]
## Bug Description

Possibly related to #1099

With the Analytics module setup on sites with low traffic the reporting periods are displaying both a start and end date of 01/01/70

Recreated on 4 different sites with low traffic. 

Site 1:
![image](https://user-images.githubusercontent.com/41326532/81309216-9943f900-907a-11ea-9690-28f991a3323b.png)

Site 2:
![image](https://user-images.githubusercontent.com/41326532/81308964-51bd6d00-907a-11ea-9e45-4d72ffb95353.png)

## Additional Context

- SK version 1.7.1
- Same issue arises with Site Kit as the only plugin installed, with core WP plugin
- Tested with and without views applied

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When there is no (or rather "empty") data returned from an Analytics API request, the graphs on the Analytics module page should still display correct start and end dates, based on the currently selected date range.

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
#1185 Also related. In some cases, the chart also doesn't have data plotted. Reported in [this support topic](https://wordpress.org/support/topic/no-data-from-analytics-to-google-site-kit-plugin/page/2/#post-12766914) as well.

**Comment by SSSV** [comment]
I'm having this issue on a site with a ton of traffic (in March they sold $80k in their online store). Apparently no traffic has been recorded since I installed Site Kit before March...

**Comment by ernee** [comment]
@SSSV thanks for sharing your case. Traffic not being recorded in Analytics in general may be something separate. I encourage opening [a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post)so we can investigate further.

**Comment by ernee** [comment]
another report with from a site with two months worth of tracking data (date displayed is  12/31/1969): https://wordpress.org/support/topic/audience-overview-date-is-1969/

**Comment by jamesozzie** [comment]
Tested again, same issue occurs on sites with low traffic. 
Site Kit 1.12.0

Occurs across all reporting periods available, not just 28 days report.

**Comment by huriprod** [comment]
Same Problem here since the last update of the plugin yesterday :/

**Comment by cole10up** [comment]
**Tested**

I was able to reproduce this on hellogoodbye.today.

![image](https://user-images.githubusercontent.com/57115907/90725390-f43ddc80-e274-11ea-849d-c67958e03d27.png)

Console isn't showing any issues

**Comment by felixarntz** [comment]
@ryanwelcher With your finding yesterday about always including all rows in Analytics API requests, can you check whether that potentially resolves this issue? I'm wondering if those "zero" dates are only displayed here because there are no rows in the response.

**Comment by aaemnnosttv** [comment]
@felixarntz the change to [include empty rows](https://github.com/google/site-kit-wp/commit/025d1f4dc28a84e092a49e9ef1d69df282b5b46f) in the response is only in develop right now.

@cole10up can you reproduce this with the latest in develop?

**Comment by cole10up** [comment]
Retested on hellogoodbye.today:
![image](https://user-images.githubusercontent.com/57115907/94051790-e8ba6580-fd8c-11ea-8f1d-e8b0ea3be19b.png)

Also checked my personal site:
![image](https://user-images.githubusercontent.com/57115907/94051827-fa9c0880-fd8c-11ea-9922-98f1c1eb9d08.png)

I also checked latest release and I'm still not able to reproduce:
![image](https://user-images.githubusercontent.com/57115907/94051936-23bc9900-fd8d-11ea-9cb8-1f9637a2be5a.png)

**Comment by aaemnnosttv** [comment]
Thanks @cole10up 👍 

@felixarntz I suggest we close this one out as unreproducible – we can always reopen it if needed.

**Comment by jamesozzie** [comment]
I've checked this on 3 sites with low traffic, including the site I used when opening this issue. The incorrect date stamps no longer occur from my side. Checking with the 3 WordPress users below before closing:

- https://wordpress.org/support/topic/no-data-from-analytics-to-google-site-kit-plugin/page/2/
- https://wordpress.org/support/topic/audience-overview-date-is-1969/
- https://wordpress.org/support/topic/audience-overview-date-is-1-1-70/

**Comment by jamesozzie** [comment]
Closing with no response from users reporting this issue.
