### ISSUE TITLE
Analytics adsenseLinked always false

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1524]
## Bug Description

The special internal Analytics option for storing the linked state with AdSense (`adsenseLinked`) is always false, even after it is saved as `true`.

## Steps to reproduce

1. Setup Analytics
1. Setup AdSense in a connected state
1. Trigger Analytics `GET:report` with AdSense metrics
1. See Analytics `adsenseLinked` option is still `false`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics setting for `adsenseLinked` should be `true` when the following criteria is met:
    - Analytics and AdSense are both active and set up
    - Analytics `GET:report` is requested with AdSense metrics

## Implementation Brief

* Sanitize `adsenseLinked` as a boolean in `Analytics\Settings::get_sanitize_callback` rather than always setting it to `false`
* Merge #1525  

## QA Brief

* 

## Changelog entry

* Fix bug where Analytics table would never include AdSense metrics even with a successful AdSense connection.

**Comment by felixarntz** [comment]
IB ✅ 

(except PR is #1525) 😄

**Comment by Alnetkhatiyan** [comment]
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1635336603446911"
     crossorigin="anonymous"></script> need to implement my code I can't do it

**Comment by Alnetkhatiyan** [comment]
Please help for code implementation 
Regard

**Comment by jamesozzie** [comment]
@Alnetkhatiyan Thanks for reaching out. We provide Site Kit initial support requests from the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Note also that for assistance with setting up the plugin on your WordPress site there is [a guide on the plugin website](https://sitekit.withgoogle.com/documentation/install/). By following the guide you'll find there is no requirement to manually insert your ad code, the plugin can do this for you.
