### ISSUE TITLE
Add dateRange to core/user store

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1529]
## Feature Description

In preparation for refactoring date range select boxes to use the datastore, we need to first add dateRange state and functionality to the `core/user` datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `assets/js/googlesitekit/datastore/user/date-range.js` datastore module which is combined into the `core/user` store in its index with the following components:
	* `selectors.getDateRange` - returns the current date range slug
	* `actions.setDateRange( slug )` sets the current date range by its `slug`
* The initial dateRange should be `last-28-days` for now although in the future this may be persisted from a previous choice
* There should be a new `assets/js/googlesitekit/datastore/user/date-range.test.js` adding test coverage to the new components
* There should be a new utility function (not in datastore) `getAvailableDateRanges()` that returns an array of objects like:
	```js
	{
		slug: 'last-28-days',
		label: sprintf( __( 'Last %d days', 'google-site-kit' ), 28 ),
	}
	```

## Implementation Brief

* Add a `getDateRange()` selector that returns the currently-selected date range slug, eg: `'last-7-days'`
* Add a `setDateRange( slug )` action that sets the active date range using a `slug` like `"last-28-days"`.
* The state's defaults should be what would be set by `setDateRange( 'last-28-days' )`
* Add a utility function (`getAvailableDateRanges()`) that returns an object where the key is the date range `slug`, and the value is an object with the date range slug and its translation (I think that's `[ 'last-7-days', 'last-14-days', 'last-28-days', 'last-90-days' ]`, but check existing code to make sure I'm not missing anything). It would have the shape: `{'last-7-days': {slug: 'last-7-days', label: _n( 'Last %s day', 'Last %s days', 28, 'google-site-kit' ) }}`

## QA Brief

* 

## Changelog entry

* Add `getDateRange()` selector and `setDateRange( slug )` action to the `core/user` store.

**Comment by tofumatt** [comment]
There's an issue with the original AC proposed here: it wants to use `__()` inside the data store, but I'm not sure that the datastore has knowledge of the current locale. I assume that it doesn't, and that an `i18n` provider is required for that? At any rate, returning localised values from the data store seems wrong to me; the data store should be returning consistent values and the frontend should be choosing how to format/display that info.

`getDateRange()` should instead return an object with the shape:

```js
 {
 	slug: 'last-28-days',
 	number: 28,
 }
```

The actual component can do the `sprintf()` bit with locales, and the `number` value.

**Comment by felixarntz** [comment]
Mostly SGTM, but a few points of feedback:
* `getActiveDateRange` should be `getDateRange`.
* I agree with @tofumatt on not returning localized values. I also think the available date ranges should not be managed by this store at all, they can be in a utility function `getAvailableDateRanges` that could include localized values, potentially even functions to transform to `startDate` and `endDate` or something like that. I think we should remove `getAllDateRanges` as a selector and instead have a decoupled utility function.
* Changing the `slug` approach to something more sophisticated should either not happen at this point, or we should take the time to think it all the way through. I'm not sure a `number` + `dateUnit` approach satisfies the needs in a future-proof way. From that POV, the `slug` is actually better because it doesn't restrict us to any convention (but clearly has other trade-offs).

**Comment by tofumatt** [comment]
Sounds good re: `slug`. I omitted any talk of handling localisations in this issue as it's out-of-scope of simply handling the data, so this should be set for another review 🙂

**Comment by felixarntz** [comment]
@tofumatt IB mostly good to go, however I think that the `getAvailableDateRanges()` utility should return a map of objects keyed by the slug, to include other data (at a minimum the localization). While you mentioned you were not going to focus on this part, the localized strings belong with this. If we don't put them here, we'll surely have to replicate the list somewhere else, so I'd prefer if the utility function could be more comprehensive. To only e.g. check for validity, the datastore could easily use `Object.keys( getAvailableDateRanges() )`.

**Comment by felixarntz** [comment]
@tofumatt 
> Add a `getDateRange()` selector that returns the currently-selected date range object with the shape: `{ slug: `last-${number}-${dateUnit}` }`

Why an object with just `slug` here? I think we could just return the string? The other details would come via `getAvailableDateRanges()`. We may want to introduce a `getAvailableDateRange( slug )` that just returns details for the one date range specified.

Regarding `getAvailableDateRanges()`, let's not use `text` as the property name, maybe something like `name` or `label`?

**Comment by tofumatt** [comment]
Ah, good call re: returning just the slug. The object was there when we were returning more info, but just returning the slug makes sense for that selector.

I've renamed "text" to "label", so I think this is good to go 😄

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz it seems the IB and AC are out of sync due to the decisions that were made since it was originally written. Would you please update it to reflect the final ACs?

**Comment by felixarntz** [comment]
@aaemnnosttv Done!

**Comment by aaemnnosttv** [comment]
## QA ⚠️

* ✅  There should be a new `assets/js/googlesitekit/datastore/user/date-range.js` datastore module which is combined into the `core/user` store in its index with the following components:
	* `selectors.getDateRange` - returns the current date range slug
	* `actions.setDateRange( slug )` sets the current date range by its `slug`
* ✅ The initial dateRange should be `last-28-days`
* ✅ There should be a new `assets/js/googlesitekit/datastore/user/date-range.test.js` adding test coverage to the new components
* ✅ There should be a new utility function (not in datastore)
* ⚠️ `getAvailableDateRanges()` that returns an array of objects like:
	```js
	{
		slug: 'last-28-days',
		label: sprintf( __( 'Last %d days', 'google-site-kit' ), 28 ),
	}
	```
`getAvailableDateRanges()` returns an object of date range objects, keyed by the date range slug, but the AC calls for an Array. This is probably okay as it was described this way in the IB which was approved so it may have been either missed or accepted and just not updated in the ACs.

Assigning to @felixarntz to decide if any further action is needed here.

**Comment by felixarntz** [comment]
Returning an object here makes sense, since it allows for quick lookup by slug. QA ✅
