### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by estereofonico** [google/site-kit-wp#1533]
Since we're using this plugin, the Tag Manager went crazy, the traffic counts double. When will you gonna add the Tag Manager method to avoid this kind of issue? 

This is the major problem of this plugin, just using Analytics when you must use the tag manager.

Thanks for the plugin, best if you work on that issue. 

## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@estereofonico Thanks for opening this issue. We are working on making improvements to the way the plugin works with Tag Manager inserted snippets, you can find out more  at #1381. I can keep you posted here with any updates.

**Comment by jamesozzie** [comment]
@estereofonico Just to keep you updated we are still working on these changes to the Tag Manager module as per #1381. I'll keep you informed here with any additional information.

**Comment by jamesozzie** [comment]
@estereofonico You can setup Tag Manager independent of Analytics within Site Kit. You'll find out more on this in #1381. 

Feel free to get in touch via the WordPress [support forums](https://wordpress.org/support/plugin/google-site-kit/#new-post) if you have encounter any trouble during setup. Thanks for your patience on this.
