### ISSUE TITLE
Google News Sitemap

### ISSUE THREAD

**Issue by itsgarryb** [google/site-kit-wp#1535]
## Feature Description

Hi all,

suggestion: would be nice if features geared toward Google News users were integrated in Site Kit.

Google News Sitemap generation along with an automation that handles update and pingback could be a good start.

Do you see it as something feasible and/or within the scope of this project?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Many thanks for the suggestion. I've added this as a feature request for the team to consider for future releases.

**Comment by marrrmarrr** [comment]
Thanks for the suggestion, @itsgarryb -- since there are already efforts to add Sitemap functionality to [WP Core](https://make.wordpress.org/core/2020/07/22/new-xml-sitemaps-functionality-in-wordpress-5-5/), adding News sitemaps specifically is not on Site Kit's radar right now.
