### ISSUE TITLE
Really Simple SSL prevents setup when changing from http to https

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1537]
## Bug Description

While investigating the issue reported[ in this topic](https://wordpress.org/support/topic/dashboard-not-working-despite-authenticating/), we've found that the [Really Simple SSL plugin](https://wordpress.org/plugins/really-simple-ssl/) can prevent updates on the proxy when changing the site from` http://` to` https://`. 

Temporarily disabling Really Simple SSL and manually updating the **WordPress Address** and **Site Address** under _Settings > General_ from the WordPress dashboard then reactivating/ configuring Really Simple SSL is a workaround. 

## Steps to reproduce

1. On a `http://` site with Site Kit configured and a SSL certificate available (Let's Encrypt is a good option), install and activate [Really Simple SSL ](https://wordpress.org/plugins/really-simple-ssl/)
2. Click [Go ahead, activate SSL](https://jmp.sh/nArPo5B) to allow the plugin to dynamically update the WordPress Settings to `https://`
3. Reset Site Kit and proceed with the setup process
4. See the setup process loops back to [the start on the dashboard](https://jmp.sh/dmBEuEu)

## Additional Context

 - PHP Version: 7.3.16
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.8.0
 - Device: MacBook Air

related support topic: https://wordpress.org/support/topic/dashboard-not-working-despite-authenticating

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
I'm also able to replicate the same issue, although with a verified http URL type property first in Search Console (verified using JetPack):
1. Removed all SC properties (clean slate)
2. Setup JetPack, default settings (free plan) and verified site ownership using JetPack (OAuth) 3. Setup Site Kit (1.8.0) - everything worked fine from setup point of view (although no additional URL type properties were created). SK used existing http URL type property - JetPack created & verified
4. Activated https for site (didn't setup auto redirection at host level)
5. Checked SK dashboard (with https site). While still awaiting dashboards to populate and site status connected (with http) I was able to connect Analytics & PageSpeed insights (all incognito)
6. Installed and activated Really Simple SSL - default settings, activated SSL at prompt
7. Reset Site Kit 
8. Clicked in "Start Setup" button at Sign in with Google to set up Site Kit screen
9. Followed all setup steps. At congratulations screen clicking on "Go to my Dashboard" directs me back to the same "Start Set" screen

When deactivating and reactivating Really Simple SSL I was able to proceed, I didn't have to reset Site Kit or manually modify site settings. 

Worth nothing that at no stage in the above is there a https URL type property created in Search Console. Site Health shows connected status at http.

**Comment by ernee** [comment]
User in the following topic had a similar issue: https://wordpress.org/support/topic/google-sitekit-http-url-error-in-google-search-console/

- The user had `https://` set up with Really Simple SSL before Site Kit
-  Site Kit kept adding the HTML verification file/ property in Search Console as `http://` (however, they were able to successfully complete the setup process  
- Workaround resolved it for them

**Comment by ernee** [comment]
This issue looks to be resolved with https://github.com/google/site-kit-wp/issues/1857. Closing.
