### ISSUE TITLE
Analytics setup: "Refetch my account" link not working

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#154]
## Bug Description

When setting up Analytics nothing happens at the Analytics setup stage when "Re-fetch my account" is clicked on.

![nqaOVvB1Rt](https://user-images.githubusercontent.com/41326532/60806108-098f9e80-a17a-11e9-81fd-0c39849b5022.gif)

## Steps to reproduce

1. Setup Analytics module
2. At the "Create Account / Refetch my account stage" nothing happens when "Re-fetch My Account" is clicked on

## Screenshots

The following error appears in dev tools:
Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
justwrong.ie/:1 Blocked script execution in 'http://justwrong.ie/?tagverify=1' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

Same issue occurs when AMP plugin deactivated, and cache cleared (Checked in cognito mode)

 - PHP Version: 7.2
 - OS: IOS
 - Browser [e.g. chrome, safari]: Chrome
 - Plugin Version: 1.0.0-beta.1  (same issue with 1.0.0-beta.1.0.1 )
 - AMP Plugin: Installed (v1.2)
 - CDN / Firewall / Security plugin in use: None

Just to confirm, there is an existing property ID within my Analytics with that domain name, and no existing Analytics tag or snippet exists on the website.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

In the Analytics setup flow, with no existing Google Analytics accounts for the current user:

* When clicking "Re-fetch Account", the plugin never gets stuck in a loading state.
* When a new account has been created in the meantime, the dropdowns are displayed and the Accounts dropdown contains that new account.
* When no account has been created in the meantime, the UI looks identical to how it was before clicking "Re-fetch Account".

## Implementation Brief

Summary: update `getAccounts` to behave the the same when called, both on component mount and when refetching accounts.

* In `AnalyticsSetup@componentDidMount`: move/merge `then` callback into the `try` block of `getAccounts`
    * the secondary/inner `try/catch` can be removed to share the existing block in `getAccounts`
    * Move `data.deleteCache( 'analytics', 'existingTag' )` to `catch` block - the rest of the catch is the same, so it can be removed
* Call `setState` within `getAccounts` in success and failure cases
    * Revisit if `this._isMounted` check is necessary
    * If necessary and not mounted, we can resolve the promise immediately without calling setState.
* Update Promise returned in both cases to resolve when `setState` is completed by passing the resolve function as the second argument to `setState`. In both cases the Promise can be resolved with the full new state of the component. A single promise can be created at the beginning of the method and resolve differently depending on the outcome.

## Changelog entry

* Fix bug where Analytics "Re-fetch Account" button was not correctly refreshing the UI.

**Comment by Jeff9511** [comment]
Hi i have the same issue with you as i can't connect my analytic account and also couldnt re-fetch any account or data. Any solution here? thanks

**Comment by jamesozzie** [comment]
@jeff I deleted the existing Analytics tracking code from my theme files which I had placed previously, which in turn removed the option to "Refetch my account data". 

Do you mind letting me know the following and we can hopefully assist:
- Do you have any other Analytics plugin installed, if so what plugins?
- Are you getting the same console error from Chrome Dev Tools?
- Prior to adding the Analytics module in Site Kit did you have the correct Analytics Property tracking code on your site (via inputting into your theme options, pasting into your theme files or via a plugin)?

Please try the following:
- Delete the Analytics module from Site Kit (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
- Temporarily deactivate any Analytics plugin or security plugin
- Activate the Analytics module again

It would be great to also get any console errors if the above doesn't work so we can troubleshoot further, but hopefully the above fixes the issue.

**Comment by Jeff9511** [comment]
- Yes i did use other analytics plugin (monster insight), but i already deactivate this plugin before i install google site kit.
- i tried to check any console error and this appeared.
![console error](https://user-images.githubusercontent.com/52736698/61042987-d5c9a880-a407-11e9-9efa-6f480f6f842d.PNG)

- Im using oceanwp theme and this theme doesn't have theme option. i copy the tracking code from google analytic and paste it in <header> in the theme editor.
- Yes, i did try to deactivate the plugin along with all other & security plugin and activate google site kit again, but end up it seems like same result as i couldn't fetch any data and connect my google analytic account.

I'm not a programming expert, just a newbie try to create an eCommerce website for small business. i might need some beginner guidance to fix this. 

thanks a lot for helping me on.

**Comment by jamesozzie** [comment]
@Jeff9511 Thanks for the update, without identifying errors like this we wouldn't be able to fix for others. That error seems relates to your theme or plugin. Do you mind changing themes, temporarily, while trying to install Site Kit again? Please try again incognito and with other plugins deactivated.

**Comment by aaemnnosttv** [comment]
This has been reproduced during E2E testing in #356 .

**Technical details**
In `handleRefetchAccount`, the promise returned from `getAccounts()` is never handled to update the component with the new state, so it is stuck in a loading state even though the response was completed.

https://github.com/google/site-kit-wp/blob/b1c57aee1f32921533b8f081f63fcfccae8cc432/assets/js/modules/analytics/setup.js#L572

This is necessary as is done in the component's initial load:
https://github.com/google/site-kit-wp/blob/b1c57aee1f32921533b8f081f63fcfccae8cc432/assets/js/modules/analytics/setup.js#L84-L87

**Comment by aaemnnosttv** [comment]
@felixarntz IB is ready for review.

**Comment by felixarntz** [comment]
IB looks awesome!

**Comment by lucymtc** [comment]
QA looks good according to the acceptance criteria.

**Comment by marrrmarrr** [comment]
LGTM

**Comment by askAnnamarie** [comment]
Cool stuff! But am I the only one who thinks this could be solved easier if we get a pro to do it? Someone on the team at nerdpilots.com, for example? They also have a shop where we can buy small services like this for same-day delivery: nerdpilots.com/store.
