### ISSUE TITLE
Dashboard menu item conflict with WP Engine hosted sites

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1541]
## Bug Description

As reported in the [WordPress support forums](https://wordpress.org/support/topic/messes-with-the-wordpress-admin-menu/) with Site Kit activated the WP Engine settings tab is placed below the dashboard tab. 

Without Site Kit active the WP Engine settings tab is placed top of the admin dashboard tabs. 

Unknown what parameters are passed with WP Engine `add_menu_page`, it's a hosted placed entry, not an installed plugin. 

## Steps to reproduce

1. Confirm tab placement of WP Engine settings tab (with WP Engine hosting)
2. Install and active Site Kit
3. Check placement of WP Engine settings tab

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/81550263-e4f6eb00-9377-11ea-97d9-69334a378ca0.png)

 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's PHP logic that currently moves the WordPress dashboard and the Site Kit menu as the top two items of the overall WordPress admin menu should be updated as follows:
    * The WP dashboard menu item should not be moved (and not be assumed to be at the first position).
    * The Site Kit menu item should always appear right after the WP dashboard menu item, wherever that is.

## Implementation Brief

* Update the hook for the `menu_order` filter in the `includes/Core/Admin/Screens.php` file to do the following:
  * Return early if either `googlesitekit-dashboard` or `index.php` doesn't exist in the list.
  * Move the `googlesitekit-dashboard` slug to be right after `index.php` in the menu order list.
  * Make sure other slug positions are not modified.
* Update tests in the `ScreensTest::test_menu_order` method to account for a case when there might be a third-party-page above the dashboard.

Use this snippet as an example:

  ```php
  function( array $menu_order ) {
      $new_order = array();
      foreach ( $menu_order as $index => $item ) {
        if ( $item !== self::PREFIX . 'dashboard' ) ) {
          $new_order[] = $item;
        }

        if ( 'index.php' === $item ) {
          $new_order[] = self::PREFIX . 'dashboard';
        }
      }

      return $new_order;
  }
  ```

## QA Brief

* Either try out using WP Engine / Bluehost account, or
* Add and activate bluehost plugin https://github.com/bluehost/bluehost-wordpress-plugin, or WP Engine mu-plugins folder.
* Ensure that the position of Bluehost / WP Engine menu item doesn't change if Site Kit plugin is enabled or disabled.
* Ensure that when Site Kit plugin is enabled, its menu item follows Dashboard in the sidebar.

<img width="346" alt="wpengine-sitekit" src="https://user-images.githubusercontent.com/373931/95949930-8a3f4080-0da8-11eb-9b68-4567c99b42e2.png">
<img width="251" alt="bluehost-sitekit" src="https://user-images.githubusercontent.com/373931/95949932-8b706d80-0da8-11eb-8d65-ecb5c3b7ad67.png">

## Changelog entry

* Fix menu positioning bug that would move menu item for WP Engine and Bluehost hosting providers.

**Comment by jamesozzie** [comment]
No change in this with Site Kit version 1.12.0. 

![image](https://user-images.githubusercontent.com/41326532/88678738-ad7e1c00-d0e6-11ea-9741-ec09bfd59d57.png)

**Comment by jamesozzie** [comment]
Similar issue occurs with Bluehost sites. With sites activated from the hosting CP there is a "Bluehost" plugin automatically installed which adds a "Bluehost" admin menu to the top of the WordPress admin menu. With Site Kit active the tab order is modified as below:

![taborder](https://user-images.githubusercontent.com/41326532/89778937-46a92b80-db06-11ea-8e52-b18cc34c3901.gif)

**Comment by cole10up** [comment]
This is confirmed on my end as well. Sending to Execution prioritization:

![image](https://user-images.githubusercontent.com/57115907/90872363-5ec44a80-e351-11ea-9d1f-2b7b7cb47d50.png)

@aaemnnosttv - Let me know if you want access to this site.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov let's define the IB in terms of how it will work logically rather than (or at least in addition to) a code snippet as it makes it a bit easier to review and implement 😄 

A few points I think we should consider
- It should only change the position of the `googlesitekit-dashboard` item, not necessarily any item that starts with the Site Kit prefix
- It shouldn't add the `googlesitekit-dashboard` if it wasn't already in the list (which is possible with the current IB)

So basically, I think we can summarize it as the following steps:
1. if `googlesitekit-dashboard` is not in the list of menu items, return the list unchanged
1. if `index.php` is not in the list of menu items, return the list unchanged
1. remove `googlesitekit-dashboard` from the list
1. slice the list from the beginning until the position of `index.php` (inclusive)
1. append `googlesitekit-dashboard`
1. append the remaining items (the second half of previous slice), if any and return the new sorted list

**Comment by eugene-manuilov** [comment]
@aaemnnosttv ok, updated IB slightly differently.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Created a new site using WP-Engine

![image](https://user-images.githubusercontent.com/57115907/96488507-f8459680-11f2-11eb-8ccc-afd35ae6642b.png)

Installed, activated latest SK
![image](https://user-images.githubusercontent.com/57115907/96489371-3b543980-11f4-11eb-9959-8058f0a0f3a6.png)

Setup SK
![image](https://user-images.githubusercontent.com/57115907/96489573-748ca980-11f4-11eb-8a55-3038453c436b.png)

Installed modules and confirmed menu item stayed in the top position for WP-Engine
![image](https://user-images.githubusercontent.com/57115907/96489759-b7e71800-11f4-11eb-929c-27a98d6d82d2.png)

Clicking into each module dashboard functions properly, clicking the WP-Engine dashboard also functions properly.

Passed QA ✅
