### ISSUE TITLE
Possible conflict with Monster Insights

### ISSUE THREAD

**Issue by martinkrcho** [google/site-kit-wp#155]
## Bug Description

The Site Kit plugin negatively affects Google Analytics functionality when using side by side with plugin [AMP for WP – Accelerated Mobile Pages](https://wordpress.org/plugins/accelerated-mobile-pages/) and [Google Analytics Dashboard Plugin for WordPress by MonsterInsights](https://wordpress.org/plugins/google-analytics-for-wordpress/).

We have 2 separate Google Analytics trackers:
- one for non-AMP traffic
- one for AMP traffic

## Steps to reproduce

1. Create 2 separate Google Analytics trackers for the same web site
2. Set up [Google Analytics Dashboard Plugin for WordPress by MonsterInsights](https://wordpress.org/plugins/google-analytics-for-wordpress/) to use one of the trackers to track non-AMP traffic.
3. Set up [AMP for WP – Accelerated Mobile Pages](https://wordpress.org/plugins/accelerated-mobile-pages/) to use the other tracker to track AMP traffic.
4. Leave the website to collect visitor stats for couple of days.
5. Set up Site Kit plugin with no Google Analytics tracking enabled.
6. Traffic captured by the GA tracker for AMP will decrease.
7. Disable Site Kit plugin.
6. Traffic captured by the GA tracker for AMP will increase.

## Screenshots

Here's a screenshot of the Google Analytics traffic that shows the decrease of Google Analytics traffic after activating Site Kit.

![AwesomeScreenshot-AwesomeScreenshot-Analytics-2019-07-09-09-07-40-2019-07-09-09-07-20](https://user-images.githubusercontent.com/1962663/60867048-313e3f80-a22a-11e9-8f20-1ee075e142e9.png)

## Additional Context

- PHP Version: 7.0.27-1~dotdeb+8.1
- OS: MacOS Mojave 10.14.5
- Browser: chrome
- Plugin Version: 1.0.0-beta.1 (upgraded to 1.0.0-beta.1.0.1 on July 8)
- Device: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

The bug might be related to [an issue I reported earlier](https://github.com/google/site-kit-wp/issues/89). Perhaps the stuck/unfinished GA setup process affected the AMP pages in some way?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@martinkrcho Thanks for reporting. I can reproduce the same issue, but regardless of whether AMP for WP is installed the same issue arises. When MonsterInsights places any Analytics tracking code on your site adding the Analytics module in Site Kit results in an "Issue Accessing Data" notice, and views are not available. 

See video below: In short, Analytics must be added via Site Kit Module first, or with MonsterInsights deactivated (so there is no existing Analytics site existing on site). 

I will test with AMP for WP Analytics code added next. Do you mind deactivating both AMP for WP and MonsterInsights temporarily and checking the Site Kit Analytics setup again? Please first remove your Analytics module from Site Kit first.

See video below:
http://recordit.co/s0uFieQgKR

Site Kit version 1.0.0-beta.1.0.1

**Comment by jamesozzie** [comment]
@martinkrcho Were you able to get MonsterInsights working use one of the wordarounds mentioned above?

**Comment by martinkrcho** [comment]
No, I was not able to get it working. I have to bring our staging server up to speed to be able to test the scenario you mentioned. I promise I will get back to this in couple of days. I have abandoned Site Kit for now, but I would really like it to get to point where I can drop the other plugins and just use Site Kit with AMP plugin from Google.

**Comment by marrrmarrr** [comment]
Thanks @martinkrcho for reporting this and @jamesozzie for debugging. The underlying cause is indeed described in issue #89, so I'll mark this as a duplicate and we'll prioritise it accordingly. 
Feel free to re-open if you see any other related issues.

**Comment by crobertwatson** [comment]
I'm getting zero traffic recorded in Google Analytics after installing Site Kit. I was running Monster Insights, and not running AMP for WP. Then I installed Site Kit and immediately removed Monster Insights after installing Site Kit. One day later my traffic dropped to zero from a consistent level of several hundred visits per day.
