### ISSUE TITLE
Refactor <p> and <h5> in settings to improve accessibility

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1557]
## Bug Description

Currently we have components that use `<p>` and `<h5>`s incorrectly. An example is here: https://github.com/google/site-kit-wp/pull/1410#discussion_r424722296, but it's not exhaustive; there are several components that take this approach to displaying data, where what is marked up as a Paragraph is really a Heading, and vice-versa.

This is problematic for accessibility and semantic reasons, and shouldn't be this way. 😄 We should refactor these components so they are marked-up accordingly. If the visual style of these components makes sense as-is, then the markup should be changed but the style largely preserved. (I'm not sure that's the case though.)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Components should use `<h*>` tags for headings and `<p>` for the content related to that heading, not the other way around.
* `<h*>` headings should *precede* the content they are describing, not come **after** the paragraph that relates to them.
* Visual appearance should be unmodified.

## Implementation Brief

* Swap `h5` and `p` tags in the following files:
    * `assets/js/modules/adsense/settings/settings-view.js`
    * `assets/js/modules/analytics/settings/settings-view.js`
    * `assets/js/modules/tagmanager/setup.js`
* In `assets/sass/components/settings/_googlesitekit-settings-module.scss` make any required CSS changes to the `.googlesitekit-settings-module__meta-item-type` class selector to ensure that there is no visual change.
* Finish and merge #1579

* Confirm that the VRT tests pass.

## QA Brief

* 

## Changelog entry

* Fix accessibility issues in Site Kit settings due to semantically incorrect tag usage.

**Comment by ahmedkrmn** [comment]
Hi Matthew, can I work on this one?

**Comment by aaemnnosttv** [comment]
IB ✅ 

@ahmedkrmn - you can start storybook with `npm run storybook` 😄 - you may want to keep an eye on this issue before starting on this as it may be done by someone on our team.

**Comment by ShahAaron** [comment]
@tofumatt I've noticed a similar issue with `assets/js/modules/search-console/settings/settings-view.js` except the tags are both `div`'s are you happy for me to convert these to `h5` and `p` tags, just to be consistent

**Comment by tofumatt** [comment]
Code review ✅ from me, just needs merging 🙂

**Comment by cole10up** [comment]
**Tested**

Built and installed latest develop SK. Activated each module.

Ran a series of regression tests around each module confirming visual appearance is unmodified.

Passed QA ✅
