### ISSUE TITLE
Cloudflare Flexible SSL (plugin) compatibility

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1558]
## Feature Description

Prompted by [a recent support topic](https://wordpress.org/support/topic/site-kit-reinstall-trouble/), Site Kit currently isn't fully compatible with certain implementations of [Cloudflare's Flexible SSL](https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options#h_4e0d1a7c-eb71-4204-9e22-9d3ef9ef7fef). 

Users may prefer to use Flexible SSL before obtaining a certificate at their host/ server as a way to provide HTTPS for their visitors using Cloudflare as the intermediary, while the traffic coming through Cloudflare to the site is unencrypted over HTTP.

There seems to a variety to ways to make this work in WordPress (without issues like redirection loops, [mixed content](https://github.com/google/site-kit-wp/issues/1391#issuecomment-628008695), etc.), a popular method is following [this guide](https://www.icontrolwp.com/blog/enabling-cloudflares-universal-flexible-ssl-wordpress-without-infinite-redirect-loops) and using the [Cloudflare Flexible SSL plugin](https://wordpress.org/plugins/cloudflare-flexible-ssl/). A few things to note about this process:

1) Changing the **WordPress Address (URL)** is discouraged. 

2) To force visitor traffic to use HTTPS, one must create a Page Rule in Cloudflare (not WordPress) to **Always Use HTTPS** 

While Site Kit's setup process can be completed with these instructions there are shortcomings for the user experience/ outcome:

1) When the **WordPress Address** and **Site Address** remain HTTP, Site Kit throws this warning:
<img width="991" alt="Caching plugin warning" src="https://user-images.githubusercontent.com/8108643/81986146-25f73580-95ec-11ea-958e-58f7a75c26a1.png">

However, the setup process can proceed and complete. 

The warning does not display when only the **Site Address**  is updated to HTTPS : 

<img width="739" alt="Site Address only updated" src="https://user-images.githubusercontent.com/8108643/81986659-162c2100-95ed-11ea-9b55-fafe886e688d.png">

2) In the settings, the Search Console property is recognized properly as HTTP and HTTPS depending on whether the **Site Address** has been changed:
<img width="1093" alt="HTTP in settings" src="https://user-images.githubusercontent.com/8108643/81986801-5ab7bc80-95ed-11ea-9869-f692d394821e.png">

<img width="1056" alt="HTTPS in settings" src="https://user-images.githubusercontent.com/8108643/81986519-c9e0e100-95ec-11ea-8419-0c28b4089dac.png">

However, _in both cases_, Site Kit _adds_ the site property to Search Console as HTTP:

<img width="306" alt="HTTP Search Console property" src="https://user-images.githubusercontent.com/8108643/81986388-93a36180-95ec-11ea-8224-2e2d31e8c08a.png">

**_Impact on other modules may need further review_ **

**Site Health:**

```
### google-site-kit ###

version: 1.8.0
php_version: 7.1.14
wp_version: 5.4.1
reference_url: https://example.com
amp_mode: no
site_status: connected-site
user_status: authenticated
active_modules: site-verification, search-console
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
search_console_property: http://example.com

```
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by pablosfc1** [comment]
I have Cloudfare with HTTPS forced. But at configure the plugin Site Kit shown me the message "encountered an error: Loading chunk 3 failed." Additionally I had to activate the Really Simple SSL plugin in Wordpress, then the Google Site Kit it's functioning ok now.

**Comment by ivankruchkoff** [comment]
As an additional datapoint, setting up sitekit over http, then enabling flexible ssl and visiting via https gives `blocked:mixed content` in the network tab and a notification `You are probably offline` on the sitekit dashboard

Screenshot attached:
<img width="1099" alt="mixed-content" src="https://user-images.githubusercontent.com/373931/114086437-77915a00-9867-11eb-810b-c480b36b759c.png">

**Comment by bethanylang** [comment]
Closing as we have not encountered this issue for some time.
