### ISSUE TITLE
Wizard shows even when the setup has completed by another admin

### ISSUE THREAD

**Issue by ngxson** [google/site-kit-wp#1568]
## Bug Description

If the site has **more than one admin accounts**, and one of them setup site kit, then **only this admin** can access site kit dashboard.

## Steps to reproduce

1. Setup site kit
2. Add another admin account on wordpress
3. Login to that account
4. Go to site kit, it shows "Sign in with Google to configure Site Kit"

## Additional Context

 - PHP Version: 7.3.17
 - Wordpress version : 5.4.1
 - OS: Windows 10
 - Browser: Chrome
 - Plugin Version: Site Kit by Google 1.8.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@ngxson Apologies for the lack of response. As we already have #852 open I'll close this issue as a duplicate. Feel free to add any additional information to that issue.
