### ISSUE TITLE
Analytics activation failure

### ISSUE THREAD

**Issue by shikshik** [google/site-kit-wp#1569]
## Bug Description

Cannot connect analytics. Getting an endless loader with the error: "Error: cURL error 2:"
Other services were successfully connected.

## Steps to reproduce

1. Install the plugin
2. Successfuly connected with my google account
3. Tried to connect analytics service
4. Got the failure message

Detailed error from network tab:
/index.php?rest_route=%2Fgoogle-site-kit%2Fv1%2Fmodules%2Fanalytics%2Fdata%2Faccounts-properties-profiles&existingPropertyID=&_locale=user

Returned with status 500
With this response:
{"code":"unknown","message":"cURL error 2: ","data":{"status":500,"reason":""}}

Also tried re-installing using incognito with same results.

## Additional Context

 - PHP Version: 7.4
 - OS: MacOs
 - Browser Chrome
 - Plugin Version latest

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@shikshik thanks for your report! Could you [open a topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) in our support forums and provide your [Site Health information](https://i.imgur.com/Rtkmsba.png) and hosting provider? 

We'll be investigating this further [in this issue](https://github.com/google/site-kit-wp/issues/1575), but that information in a support topic would be most helpful.
