### ISSUE TITLE
Setup E2E tests suite

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#157]
## Feature Description

Setup E2E tests suite

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Entails having the necessary infrastructure in place for running end-to-end tests on a fully-functioning WordPress site running Site Kit.
* The e2e test suite is containerized and thus platform agnostic.
* Allows running end-to-end tests locally.
* Allows testing against multiple WordPress versions. 
* Tests are running and passing on Travis CI.
* Bonus: Documentation in the [contributor handbook](https://github.com/google/site-kit-wp/wiki) explains how to run the e2e tests. 

## Implementation Brief

* Implementation is based on the experience from adding the same e2e infrastructure that was [recently added to WordPress core](https://make.wordpress.org/core/2019/06/27/introducing-the-wordpress-e2e-tests/) and also the [AMP plugin](https://github.com/ampproject/amp-wp/issues/2696).
* Helper scripts and commands are added for setting up and starting/stopping the containerized test environment.
* Multiple Docker Compose files exist to allow easily running the tests against different WordPress versions.

## Changelog entry

* N/A

**Comment by adamsilverstein** [comment]
This is looking really good. @swissspidy has e2e tests infrastructure running (along with some initial tests) in https://github.com/google/site-kit-wp/pull/163 which is approved for merge.  In that PR @wordpress/e2e-test-utils is being used to have some helper functions for things like activating plugins during tests and navigating to admin pages. 

One item I see remaining from the implementation brief is "_Multiple Docker Compose files exist to allow easily running the tests against different WordPress versions._" @swissspidy do you plan to work on that in a separate PR?

**Comment by swissspidy** [comment]
> One item I see remaining from the implementation brief is "Multiple Docker Compose files exist to allow easily running the tests against different WordPress versions." @swissspidy do you plan to work on that in a separate PR?

Good point. In #163 I instead opted for one single Docker Compose file, but just switch the WordPress version by using the environment variables. That makes handling easier and more consistent with the other tests.

See the Travis config here:

https://github.com/google/site-kit-wp/blob/7d29a70931313e2f02b9fb3874ed4741955c9bea/.travis.yml#L109-L117

**Comment by adamsilverstein** [comment]
Right, that is excellent! I was confused because your implementation didn't match the wording of the acceptance criteria here.  I feel like we can adjust the acceptance criteria here to reflect what you built, if @ThierryA agrees.

Quick question: when I run these tests locally, which WordPress version will the tests run against (and is it possible to change that)?. This might be an important capability if we discover a bug specific to a version of WordPress.

**Comment by swissspidy** [comment]
Yeah the wording was perhaps a bit too specific. The point is about being able to use different versions easily.

By default the tests use the latest version of WordPress (5.2.2 as of this writing). To change that, you can use something like that:

```bash
WP_VERSION=4.9.10 npm run env:start
npm run test:e2e
```

And if you want to install Gutenberg too:

```bash
WP_VERSION=4.9.10 GUTENBERG_VERSION=4.9.0 npm run env:start
npm run test:e2e
```

To more easily debug the tests you can disable headless mode like this:

```bash
HEADLESS=false npm run test:e2e
```

I'll try to document these things in the wiki this week.

**Comment by adamsilverstein** [comment]
> I'll try to document these things in the wiki this week.

Perfect, thanks! 

Do you know if we can use puppeteer's [slowMo](https://github.com/GoogleChrome/puppeteer#debugging-tips) feature?  I've found that useful building e2e tests in the past.

**Comment by swissspidy** [comment]
Yes.

`slowMo` can be added to the `launch` section in `jest-puppeteer.config.js` if wanted. There's no env variable for it, but if desired we could adjust the config file accordingly to allow for that.

**Comment by lucymtc** [comment]
QA looks good!
