### ISSUE TITLE
Include Site Kit version string in client service requests

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1571]
## Feature Description

Include a version string in client->service requests matching the user agent string used by the PHP client. Enable enforcing specific version to use setup flow & notifying old plugin version users they need to upgrade.

When first setting up the plugin, we should include the plugin name/version (`'wordpress/google-site-kit/' . GOOGLESITEKIT_VERSION;`) as a parameter to the setup endpoint the user reaches by clicking the [Start Setup] button.

Similarly when a second admin logs into the site and uses Site Kit, the [Sign in with Google] button link should include the plugin version.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Unconditionally pass an `application_name` query parameter in the proxy setup URL, and the proxy permissions URL as well. The value should be computed in the same way the `$application_name` used by our `Google_Client` instance is generated.

## Implementation Brief

* In `OAuth_Client::get_proxy_setup_url` add the `application_name` query parameter. Add after the `googlesitekit_proxy_setup_url_params` filter so the value cannot be changed with the filter.

`$query_params['application_name'] = rawurlencode( 'wordpress/google-site-kit/' . GOOGLESITEKIT_VERSION );`

## QA Brief

* 

## Changelog entry

* Provide `application_name` query parameter to authentication service.

**Comment by felixarntz** [comment]
@adamsilverstein Let's open a PR for this from and against `master`.

**Comment by felixarntz** [comment]
IB ✅ , except we should also add the parameter to the permissions URL. For the sake of speed, let's handle that via the PR though, no need to iterate on IB for this.

**Comment by adamsilverstein** [comment]
I tested https://github.com/google/site-kit-wp/pull/1572 and verified the `application_name` parameter is added for both initial setup and subsequent Admin user sign ins.
