### ISSUE TITLE
Include update routine to check affected sites

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1573]
## Feature Description

Site owners whose sites were actually affected by the security vulnerability allowing unprivileged accounts to get verified and thus gain Search Console access should be informed and presented with steps to resolve the issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On update, if there are WP user accounts that do not have the `googlesitekit_setup` capability but still have a verification token set, a request to Site Kit Service should be issued to flag them.
    * Site Kit Service will provide a notification to these sites with how they can resolve the issue.
* The plugin should support displaying more than one notification in the dashboard, in case there are multiple that the user has not dismissed (this should be the case already now, but needs to be tested specifically).

## Implementation Brief

* Introduce class `Migration_1_8_1` similar to existing migration classes in `includes/Core/Util`, with public `register()` and `migrate()` methods.
* Add private method to the class `check_unauthorized_verified_users()`:
    * If the site is not using the proxy (tiny edge-case), bail and do nothing.
    * Run a `WP_User_Query` to get all users (set reasonable limit of 20) that have a `googlesitekit_site_verification_meta` or `googlesitekit_site_verification_file` user option set, and then filter them by whether `! user_can( $user_id, Permissions::SETUP )`, to get all users that are verified despite not being authorized to do so. If there are no such users, all is fine, bail early.
    * Disconnect these users by wiping all their user meta that starts with `googlesitekit_` (similar logic as in `Authentication::disconnect()`).
    * Issue a `POST` request to the proxy's `/notifications/mark/` route with `notification_id` set to "verification_leak" and `notification_state` set to "required", as well as identifiers for these unauthorized users in an `identifiers` parameter.
* Initialize class instance from `Plugin` main class.

## QA Brief

* 

## Changelog entry

* Check for users that verified through Site Kit without being authorized to do so, and disconnect them from Site Kit.

**Comment by adamsilverstein** [comment]
Overall IB looks good. One question:

> Site Kit Service will provide a notification to these sites with how they can resolve the issue.

Do these show up on the dashboard and persist until dismissed?

**Comment by felixarntz** [comment]
@adamsilverstein 
> Do these show up on the dashboard and persist until dismissed?

Yes it would be dismissible and show until then.

**Comment by felixarntz** [comment]
QA ✅ 

Tested this against staging proxy. Unauthorized verified users' Site Kit data gets wiped as expected, and the flag request to the proxy is issued.

Also, the notification system _does_ support multiple remote notifications already, nothing needed to be changed here:
![Screenshot 2020-05-19 at 16 30 19](https://user-images.githubusercontent.com/3531426/82388474-8ae8cc00-99ee-11ea-8baf-1d9c849f24a4.png)
