### ISSUE TITLE
Phase out Cron API

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#158]
## Bug Description

The `\Google\Site_Kit\Core\Util\Cron` class is a relic of an earlier implementation of the plugin and no longer serves a useful purpose. Currently the only module which is using it is the PageSpeed Insights module. Functionally, the cron that runs is not providing any benefit since the data that is fetched in the background is not cached.

This class and its use is to be phased out and removed, per @felixarntz .

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure no fatal error occurs during basic plugin usage and particularly during setup and usage of the PSI module.

## Implementation Brief

* Delete `\Google\Site_Kit\Core\Util\Cron`
* Remove usage of filters provided from modules
    - `googlesitekit_cron_daily_requests`
    - `googlesitekit_cron_hourly_requests`
* Register actions in `Plugin` for site kit cron hooks that unschedule the event (avoids the need to check for if scheduled on every request)
    - `googlesitekit_cron_daily`
    - `googlesitekit_cron_hourly`
* Register action on `googlesitekit_deactivation` in `Plugin` to ensure cron events are unscheduled if deactivated before event runs
* Note added actions for cleanup are to be removed in a future release
* Update tests accordingly
    - No `Cron` test to delete
    - Update `PluginTest` to test added hooks

## Changelog entry

* N/A

**Comment by lilybonney** [comment]
Assigning to @aaemnnosttv to write the implementation brief. Many thanks!

**Comment by aaemnnosttv** [comment]
Ready for brief review.

**Comment by felixarntz** [comment]
@aaemnnosttv Since we are in developer beta, I'd say it's okay if we remove the class right away (although I like your BC approach in general). We could probably make the call to remove old scheduled hooks manually in the `Plugin` main class and not rely on the Cron class.

**Comment by aaemnnosttv** [comment]
Either way we have code to be removed later but I think your suggestion sounds a bit cleaner with more we can remove now and less to remove later 👍 

Updating the brief now.

**Comment by aaemnnosttv** [comment]
@felixarntz I've updated the brief, so this is ready for your review again.

**Comment by felixarntz** [comment]
@aaemnnosttv Implementation brief looks good. I just merged the Plugin tests, so those can be updated as part of this as well now.

**Comment by aaemnnosttv** [comment]
Great, I just updated the IB to note that `PluginTest` will be updated 👍

**Comment by felixarntz** [comment]
QA looking good!
