### ISSUE TITLE
Issue with OAuth/ Windows IIS: Unknown Error (cURL error 60)

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1588]
## Bug Description

Opening due to [a recent report](https://wordpress.org/support/topic/unknown-error-curl-error-60/) in the forums and [a previous report](https://wordpress.org/support/topic/unknown-error-code-curl-error-60-ssl-certificate-problem-unable-to-get-local/) of something similar to replicate. In a Windows IIS environment, the setup process fails at the OAuth step with a cURL error 60:

`Unknown Error (code: cURL error 60: SSL certificate problem: unable to get local issuer certificate). To resume setup, start here.`

In the[ previous report ](https://wordpress.org/support/topic/unknown-error-code-curl-error-60-ssl-certificate-problem-unable-to-get-local/)the user changed to a Linux environment and updated their PHP version to 7.3 to resolve. 

In the [current report](https://wordpress.org/support/topic/unknown-error-curl-error-60/), user attempted several troubleshooting steps including changed/ downgraded PHP (7.4 to 7.2)  and installing a CA SSL certificate (Let's Encrypt) over the original self-signed (Cloudflare). 

May be related to the default configuration or a misconfiguration of cURL / SSL certificate for [cURL verification](https://curl.haxx.se/docs/sslcerts.html) on the server, but will update the issue as we learn more. 

## Screenshots

Image of the last step before the failure and the error message: https://imgur.com/a/1lhnHob

## Additional Context

Related support topic: https://wordpress.org/support/topic/unknown-error-curl-error-60/

Site Health: https://wordpress.org/support/topic/unknown-error-curl-error-60/#post-12877647

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by luc122c** [comment]
Hi there, following up on this, I've put the phpinfo cURL section below. The rest can be found [here](https://lukenelson.uk/test.php). Many thanks for investigating this.


cURL support | enabled
-- | --
cURL Information | 7.68.0
Age | 5
Features
AsynchDNS | Yes
CharConv | No
Debug | No
GSS-Negotiate | No
IDN | Yes
IPv6 | Yes
krb4 | No
Largefile | Yes
libz | Yes
NTLM | Yes
NTLMWB | No
SPNEGO | Yes
SSL | Yes
SSPI | Yes
TLS-SRP | No
HTTP2 | Yes
GSSAPI | No
KERBEROS5 | Yes
UNIX_SOCKETS | Yes
PSL | No
HTTPS_PROXY | Yes
MULTI_SSL | No
BROTLI | No
Protocols | dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host | x86_64-pc-win32
SSL Version | OpenSSL/1.1.1d
ZLib Version | 1.2.11
libSSH Version | libssh2/1.9.0

**Comment by luc122c** [comment]
After some further investigation, I've managed to resolve the issue and get SiteKit installed. 

After following @ernee's advice on the [WordPress support thread](https://wordpress.org/support/topic/unknown-error-curl-error-60/), I started looking into my PHP installation to ensure cURL was configured correctly. My first stop was the [cURL Installation](https://www.php.net/manual/en/curl.installation.php) page of the PHP Manual. 

>  Also libssh2.dll must be present in your `PATH`.

This was the first thing I tried, as libssh2.dll was not in my `PATH`, however it didn't help. Then I read through the user contributed notes on the article. [One comment from Greg](https://www.php.net/manual/en/curl.installation.php#124549) says:

> For those who may be having WordPress issues relating to curl, the answer for me was that the curl.cainfo wasn't specified in the config.  This resulted in a plugin giving some non-graceful errors for which I was finally able to track it down.
`curl.cainfo =  "C:\php\extras\ssl\cacert.pem"`
You'll need a copy of the cacert.pem (doesn't come with PHP and does need to be updated every so often can be found at an official permalink of:
https://curl.haxx.se/ca/cacert.pem
They use a modified version of Mozilla's certificate store meant to work with libcurl.
I'm not an expert, this is just what fixed the errors for me.
(cacert.pem lists official root certificate providers so your computer knows which ones its safe to authenticate against is my lay interpretation.  I'm sure it's not technically accurate but close enough for us lay people.)

I'm not one for blindly downloading things so I decided to find the `curl.cainfo` option in my `php.ini`. Mine looked like this:

> [curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo =  

After some further Googling, I came across [this article](https://thisinterestsme.com/php-curl-ssl-certificate-error/) discussing using 'Using a cert with PHP’s cURL functions' and 'Adding the cert to your php.ini file'. Again, the article links to the [official cURL website](https://curl.haxx.se/docs/caextract.html) and says to download the `cacert.pem` and reference it in the `php.ini`. After following the steps,  mine now reads `curl.cainfo = "C:\Program Files\PHP\v7.4\extras\ssl\cacert.pem"`. I then restarted IIS and re-tried the setup process; it worked right away. 

@ernee was right! It was a server configuration issue. I'll mark the issue as resolved on WordPress.org and leave this info, I don't have permission to close the issue on here.Hopefully these threads help out anyone else who has the same issue. I'd be very interested if  someone more familiar with cURL or PHP or WordPress could shed some light on this issue?

**Comment by ernee** [comment]
@luc122c great troubleshooting! Really appreciate your detailed steps to resolve it as well. Closing this one out.

**Comment by ibalbale** [comment]
Spot on! I followed the steps for my v7.1 and it worked like a charm. Thanks @luc122c
