### ISSUE TITLE
Request contains an invalid argument. how to solve this error to GET OAUTH CREDENTIALS...???

### ISSUE THREAD

**Issue by vihar3vasoya** [google/site-kit-wp#159]
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

* 
#44

**Comment by jamesozzie** [comment]
@vihar3vasoya Thanks the raising this issue. In order to investigate further Do you mind following the steps below:

1. Can you please check your [Google Cloud Console](https://console.cloud.google.com/) and ensure there was no project setup? Site Kit would have created a new project during setup if the process completed. If you see such a project please [delete it](https://i.imgur.com/EoA1edo.png). 
2. Next please then reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit) 
3. Please check your [site settings](https://i.imgur.com/MkFLF0E.png) to ensure you have the correct site name and site address (including https or http). 
4. Start the Site Kit installation again, and during setup please let me know the "Project Name" and "Application Name" which should [appear](https://i.imgur.com/LDdZw8j.png) during initial setup.

**Comment by vihar3vasoya** [comment]
hello jamesozzie
there is only one project in my google cloud console...and it contains my wordpress web site mentioned above...so i can't delete that one...

**Comment by vihar3vasoya** [comment]
![Untitled](https://user-images.githubusercontent.com/50228034/60988711-ce4fc400-a361-11e9-86e0-ae1af4f89968.png)

![Untitled1](https://user-images.githubusercontent.com/50228034/60988899-49b17580-a362-11e9-93ab-5301d976a458.png)

**Comment by vihar3vasoya** [comment]
in my cloud console dashboard or we can say home page there is a project cold...ultra-water-243713...
so waht shoud i do now...???

**Comment by jamesozzie** [comment]
@vihar3vasoya Can you please delete that project from within your Google Cloud Console. 

Are you using https? If so please ensure you have your https website in your [site settings](https://i.imgur.com/MkFLF0E.png), then try to install Site Kit again.

**Comment by vihar3vasoya** [comment]
-are you sure deleting the project named .ultra-water-243713. i don't lose my web site???...
-so i have one que...??? deleting my project .ultra-water-243713. also delete  my wordpress site...because i made that site on google cloud console VM Engine...
-and the site is make on default settings...i don,t use any special https settings till now...

**Comment by jamesozzie** [comment]
@vihar3vasoya Only delete the project that was created via Site Kit (An Analyzer). If you don't see that don't delete any other project. 

Also what do you see in your [site settings](https://i.imgur.com/MkFLF0E.png)? The application name from your screenshots above display your IP address, please enter your correct URL in both fields and try the process again from below:

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate your active WordPress plugins
3. Start the Site Kit installation again

If you can perform the above in an [incognito window](https://i.imgur.com/ALzgiHp.png) we can check if the issue arises again. Please let me know after you perform all steps above.

**Comment by vihar3vasoya** [comment]
There is no any other project created on my dashboard by site kit...
Ther is only one project containing my wordpress site...

**Comment by vihar3vasoya** [comment]
I also tryed removing and reinstalling the site kit plugin...but nothing happens

**Comment by jamesozzie** [comment]
@vihar3vasoya Can you please follow the steps below to try and proceed with your Site Kit setup:  

1. Please check your WordPress site settings under "Settings > General" in your WordPress dashboard. Confirm your WordPress Address (URL) and Site Address (URL) match, and ensure they have a https prefix if you are using a https website. 
2. Restart the Site Kit setup process again
3. If the same error appears close the "Couldn't create project" window
4. In the address bar of your window paste the following in: https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
5. Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
6. Press enter, with your cursor in the address bar (as if you are visiting that URL)
7. Press the "GET OAUTH CREDENTIALS" button
8. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

If the above fails please inform me of the following:
- Web Host Environment
- Security / Firewall plugins in use
- PHP Version
- Console Errors
- PHP Errors

**Comment by jamesozzie** [comment]
@vihar3vasoya Did you have any luck with the plugin setup?

**Comment by jamesozzie** [comment]
I will close this ticket as I didn't receive a response and I am unable to replicate the issue from my side. If the problem persists feel free to reopen.
