### ISSUE TITLE
Remove PR action not consistently working as expected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1590]
## Bug Description

Our GitHub Action to remove built artifacts for PRs from the wiki is not working as expected. This is resulting in the wiki growing very large in size which is also slowing down the time to clone it in our builds substantially.

## Steps to reproduce

1. View checks of a closed PR
1. See `remove-pr` job failed  
e.g. https://github.com/google/site-kit-wp/runs/696936169?check_suite_focus=true

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/82800493-7b510380-9e84-11ea-8c98-6974765b6ed3.png)

## Additional Context

The job fails due to the push failing "error: failed to push some refs to 'https://github.com/google/site-kit-wp.wiki'" due to missing commits. This may be due to the `build-pr` job running again when the PR is merged at the same time. Looking at the commits on the wiki, there are cases where PRs are removed successfully (e.g. [1583](https://github.com/google/site-kit-wp/pull/1583/checks)), so there may be a bit of a race condition.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `remove-pr` job should always run when a PR is closed, regardless of build or other action success states

## Implementation Brief

* Set the `remove-pr` job's `if` to run `${{ always() }}`  
By default this is set to `${{ success() }}` but we want this to always run regardless if other steps failed or not as the PR is closed
* Merge #1804 

See https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

**Note: artifacts deployed to the wiki from previous jobs where `remove-pr` failed will need to be removed manually.**

<details>
<summary>Paths to clean up</summary>

```
Found files from 51 PRs that are closed and should be removed 
 [ 'refs/pull/1123',
  'refs/pull/1162',
  'refs/pull/1166',
  'refs/pull/1189',
  'refs/pull/1197',
  'refs/pull/1199',
  'refs/pull/1200',
  'refs/pull/1203',
  'refs/pull/1205',
  'refs/pull/1206',
  'refs/pull/1216',
  'refs/pull/1217',
  'refs/pull/1218',
  'refs/pull/1220',
  'refs/pull/1226',
  'refs/pull/1227',
  'refs/pull/1228',
  'refs/pull/1234',
  'refs/pull/1239',
  'refs/pull/1240',
  'refs/pull/1243',
  'refs/pull/1252',
  'refs/pull/1284',
  'refs/pull/1303',
  'refs/pull/1306',
  'refs/pull/1312',
  'refs/pull/1329',
  'refs/pull/1353',
  'refs/pull/1359',
  'refs/pull/1360',
  'refs/pull/1413',
  'refs/pull/1431',
  'refs/pull/1442',
  'refs/pull/1453',
  'refs/pull/1457',
  'refs/pull/1467',
  'refs/pull/1473',
  'refs/pull/1485',
  'refs/pull/1496',
  'refs/pull/1528',
  'refs/pull/1544',
  'refs/pull/1551',
  'refs/pull/1562',
  'refs/pull/1564',
  'refs/pull/1570',
  'refs/pull/1634',
  'refs/pull/1664',
  'refs/pull/1665',
  'refs/pull/1679',
  'refs/pull/1732',
  'refs/pull/1763' ]
Found files from 2 branches that should be removed 
 [ 'refs/heads/1436',
  'refs/heads/fix' ]
```

</details>

## QA Brief

* 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Looks good to me, and I see it's pruning the files in closed PRs: https://github.com/google/site-kit-wp/runs/894959033?check_suite_focus=true

Might be worth manually pruning all the old files if there's an easy command, but this is working as-expected so QA ✅

**Comment by aaemnnosttv** [comment]
I already removed the old ones manually 👍 

One important thing to check is that the job works when the checks previously failed. This seems to be the main reason why there were leftover artifacts because GHA don't run when previous checks fail by default.

**Comment by tofumatt** [comment]
Ah, true. So any PR with failing checks should still remove old files, yeah? I'll be on the lookout for new PRs that fail and make sure they have this in there; if I don't see any soon I'll create a test one. I'll assign this back to me just to make sure that's covered 👍

**Comment by aaemnnosttv** [comment]
[Here's an example](https://github.com/google/site-kit-wp/pull/1329/checks) from a few weeks ago - the PR was closed and the remove job seems to never have ran (maybe because the bot closed it?).

Many failed because the git checkout was out of sync with the remote (possibly due to how long the checkout was taking too). The order of `git pull` change in this PR should address that, but is technically still a possible race condition.

**Comment by tofumatt** [comment]
I think this is working as the actions are running so marking as approved ✅
