### ISSUE TITLE
Dashboard search should support URIs that don't resolve to individual posts

### ISSUE THREAD

**Issue by ryanwelcher** [google/site-kit-wp#1592]
Currently, any URIs that are entered to the input must resolve to a related piece of content, or "No results found" are displayed. In the case of directly entering valid URIs that don't resolve such as tag archive or the homepage when there is no Page assigned.

The was discovered while working on #1434 and will be more pronounced with the work done there, as now the View Data button is not enabled unless there is a matched piece of content.

We should be able to submit valid URIs directly as long as they match the site domain.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new class `Google\Site_Kit\Core\Util\REST_Entity_Search_Controller`, which has a `register` method that adds an additional REST endpoint `core/search/data/entity-search`.
    * The endpoint should essentially be a revised version of the existing `core/search/data/post-search` endpoint, with a few differences, as listed below.
    * Instead of returning an array of post objects, it should return an array of entity objects, with the following fields:
        * `id`
        * `title`
        * `url`
        * `type`
    * If a URL is passed and an entity is found, the result should always be returned, not only if it is a post.
    * If the provided value is not a URL, the behavior should be similar to today, relying on only post search, since WordPress does not have a solid search mechanism for other entities. In that case, the posts found just need to be transformed to the entity format (see `Entity_Factory::create_entity_for_post`).
* The new class should be initialized (and registered) in the `Plugin` main class.
* All code (mostly in JS) which currently relies on `core/search/data/post-search` should be switched to the new endpoint instead, including the updated response format of course.
* The then unued `core/search/data/post-search` endpoint should be removed.

## Implementation Brief

* Create a new file `includes/Core/Util/includes/Core/Util/REST_Entity_Search_Controller.php` with
a class `Google\Site_Kit\Core\Util\REST_Entity_Search_Controller`.
  * Add a `register()` function which adds a `new REST_Route` `core/search/data/entity-search` based on `core/search/data/post-search` from the following:
  https://github.com/google/site-kit-wp/blob/4713411/includes/Core/REST_API/REST_Routes.php#L171-L222

  * The returned value will be an array of entities, see the AC for the format. The entities will be fetched either via `create_entity_for_post()` or from the call to `get_reference_entity_from_url()`: 
  https://github.com/google/site-kit-wp/blob/4713411/includes/Core/Util/Entity_Factory.php#L169-L186

* Call the `register()` function of the new class in the `includes/Plugin.php` file:
  https://github.com/google/site-kit-wp/blob/4713411/includes/Plugin.php#L176-L194

* Update `js/components/PostSearcherAutoSuggest.js` to use the new endpoint.

* Remove the no longer needed REST Route:
  https://github.com/google/site-kit-wp/blob/4713411/includes/Core/REST_API/REST_Routes.php#L171-L222

### Test Coverage

* Add tests in `phpunit/integration/Core/Util/includes/Core/Util/REST_Entity_Search_ControllerTest.php`, looking at any of the `REST_*_ControllerTest` files for reference.
* Update any broken tests and/or stories.

### Visual Regression Changes

* N/A

## QA Brief

* Test Entity Search:
    * Copy a permalink of a non-post entity, such as tags or category.
    * ie: `http://sitekit.10uplabs.com/?cat=1` or `http://sitekit.10uplabs.com/category/uncategorized/`
    * Paste in in the URL Search. The Autocomplete should bring up the respective entity as a result. 
    * It should navigate to the correct Dashboard Details/Entity Dashboard page. 
    * Test in Both Old and Unified Dashboard. 
 * Existing Functionality:
     * Searching by keyword should continue to work as before. ie. only bring up post and page. 
     * Test on both Old and Unified Dashboard. 
 * QA:Eng
     * Make sure the output format of `core/search/data/entity-search` meets AC. 
     * Make sure newly added and existing tests are passing. 
     * Make sure E2E tests are passing. 

## Changelog entry

* Support pages that don't resolve to a specific post on the Dashboard Search.

**Comment by aaemnnosttv** [comment]
Related to #174, the dashboard details view already supports these kind of "virtual" entities like archive pages - we only need to update the search endpoint to support it 👍 

![image](https://user-images.githubusercontent.com/1621608/114539566-4ba61800-9c5d-11eb-85c7-087511b1fcbe.png)

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff ! The IB looks good, but we should add tests for the new endpoint via the controller class as we have for others (see `REST_*_ControllerTest`s).

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff – I think we should bump the estimate for the added tests but otherwise

IB ✅

**Comment by asvinb** [comment]
### QA: ✅ 

* Searched for a non entity URL and the correct result came up.
* Upon clicking the search result, the user is redirected to the entity dashboard.
* Works both on unified and non unified dashboard
* Keyword search works
