### ISSUE TITLE
Clear legacy caches when submitting module changes

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1593]
## Bug Description

With AdSense and Analytics setup/settings already refactored, both of these modules now invalidate the browser cache via `googlesitekit-api`, to ensure no stale data is being displayed (which could apply to e.g. different accounts). However, what is not covered currently is the cache used by the legacy API layer `assets/js/components/data`, which is at this point actually more relevant because pretty much the entire dashboard and module pages rely on that.

We should fix this for the coming release, which includes the AdSense refactoring and adds the prominent Analytics provisioning feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `submitChanges` actions of `modules/adsense` and `modules/analytics` should also invalidate caches for the legacy API layer `assets/js/components/data` (see `invalidateCacheGroup` function).
* These function calls should be annotated with TODOs to explain why they're there and that they should be removed in the future.

## Implementation Brief

* In `assets/js/modules/adsense/settings.js` and `assets/js/modules/analytics/settings.js`:
    * Import `legacyDataAPI` from `assets/js/components/data`.
    * Call `legacyDataAPI.invalidateCacheGroup( 'modules', 'adsense' )` / `legacyDataAPI.invalidateCacheGroup( 'modules', 'analytics' )` right after the existing calls to invalidate the new caches.
    * Add TODO comments to both legacy API calls.

## QA Brief

For both Analytics and AdSense modules:
* Set up the module normally
* Go to the main SK dashboard (this primes the caches)
* Refresh the page, you should not see network requests for the module data
* Edit the module settings and make a change (e.g. toggle snippet output)
* Save settings
* Navigate back to SK dashboard while observing network requests
    * Network requests should be made for the module data on the first request to the main dashboard

## Changelog entry

* Ensure all module caches are cleared when modifying Analytics settings.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ryanwelcher** [comment]
Tested locally:
* Loaded Dashboard to prime caches and then confirmed that page reload fires no network requests.
* Changed AdSense settings to not insert the snippet and confirmed that Dashboard made a network request for module data. 
* Refreshing Dashboard did not fire another request for module data.
* Change Analytics settings to not insert the snippet and confirmed that Dashboard made a network request for module data.
* Refreshing Dashboard did not fire another request for module data.

QA ✅
