### ISSUE TITLE
Create helpers to enable modules for E2E tests.

### ISSUE THREAD

**Issue by ryanwelcher** [google/site-kit-wp#1594]
When creating E2E tests, being able to call a helper utility to enable and baseline configure any module will allow our tests to be simpler and ensure consistency across tests. For example, while writing tests for #1255 we needed to enable TagManager to test AMP validation on the homepage:

```
it( 'validates homepage AMP for logged-in users', async () => {
    await expect( page ).toClick( 'button', { text: /confirm \& continue/i } );
    await page.waitForSelector( '.googlesitekit-publisher-win--win-success' );
    await expect( page ).toMatchElement( '.googlesitekit-publisher-win__title', { text: /Congrats on completing the setup for Tag Manager!/i } );
    await page.goto( createURL( '/', 'amp' ), { waitUntil: 'load' } );
    await expect( page ).toHaveValidAMPForUser();
} );
```

This could be simplified to abstract away the setup as it's not really related to the test.

```
it( 'validates homepage AMP for logged-in users', async () => {
    await setupTagManager();
    await page.goto( createURL( '/', 'amp' ), { waitUntil: 'load' } );
    await expect( page ).toHaveValidAMPForUser();
 } );
```

**Comment by aaemnnosttv** [comment]
Looks like we've already implemented a few `setup{Module}` utilities, but it would be good to have one for each module.

We'll likely add these as needed though. I wouldn't want to add utilities that we aren't using. This could improve the performance of E2E runs though by bypassing a few steps that aren't relevant to one or more tests.

**Comment by tofumatt** [comment]
Given we already have the appropriate utilities where needed and there's been no further movement on this issue, I'm closing it as fixed 🙂
