### ISSUE TITLE
Include an option to download or print a users PageSpeed Insights performance report

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1597]
## Feature Description

At present Site Kit displays performance metrics within the dashboard, with a link to the full PageSpeed Insights web interface. As the results can differ a link to a downloadable html file or print option that contains additional metrics to that specific performance report may be useful. 

While maybe harder to achieve an alternative would be to provide a link to the full PSI report, in the same way that [web.dev](https://web.dev/measure/) provide a shareable link to a report after performing a PageSpeed test 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
After reviewing with the team, we've decided that this isn't something that we're currently planning on adding support for. Neither the [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) frontend or [web.dev Measure](https://web.dev/measure/) offer downloadable of the report either and reports can always be printed via the browser like any other page. Closing this as something to potentially revisit in the future.
