### ISSUE TITLE
Use esc_url instead of esc_attr where appropriate

### ISSUE THREAD

**Issue by swissspidy** [google/site-kit-wp#16]
Let's revive #2 to fix a small issue where `esc_url()` should be used for strings that appear in a `src` attribute.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* URL attribute values are escaped using the appropriate WP API function.

## Implementation Brief

URL attribute values are fully escaped using `esc_url` in the following methods:

* `\Google\Site_Kit\Modules\TagManager::print_gtm_no_js`
* `\Google\Site_Kit\Modules\TagManager::print_amp_gtm`
* `\Google\Site_Kit\Core\Util\Tracking::print_gtag_script`

## Changelog entry

* Update URL attributes to escape the full URLs.

**Comment by aaemnnosttv** [comment]
I've updated the acceptance criteria to be more generic to URL attribute values, not specifically `src` attributes as I found this was used in the same way for `amp-analytics`:

https://github.com/google/site-kit-wp/blob/9ef4b4f74dae2ddf1d3f4131eb81d7d674f6872f/includes/Modules/TagManager.php#L217-L219

Implementation brief added and ready for review.
