### ISSUE TITLE
Update Storybook module settings stories to use createLegacySettingsWrapper

### ISSUE THREAD

**Issue by ShahAaron** [google/site-kit-wp#1602]
## Bug Description

Currently our Storybook stories for module settings each use the same `Settings` wrapper component which is used just for rendering in Storybook. This is defined in the stories file for multiple modules' settings stories, e.g.:

https://github.com/google/site-kit-wp/blob/33a649d3b20fbcf9f5d9f04d6ff53640825a8e41/stories/module-analytics-settings.stories.js#L56-L103

In #1715 we introduced the `createLegacySettingsWrapper` utility for reducing this boilerplate needed for each module's settings stories.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `Settings` wrapper components defined in `stories/module-*-settings.stories.js` files should be removed
* Stories in `stories/module-*-settings.stories.js` should be refactored to use `createLegacySettingsWrapper`

See Tag Manager for example usage:
https://github.com/google/site-kit-wp/blob/20f826af64092da7633d94ead7d23a75667762a7/stories/modules-tagmanager-settings.stories.js#L35

## Implementation Brief

* Update `stories/module-*-settings.stories.js` (except `tagmanager` as it is already done) to use the new utility instead of the inline `Settings` component definition

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by umuur** [comment]
Hello, can I take this issue?

**Comment by aaemnnosttv** [comment]
Hi @umuur, thanks for asking 🙂  - I can't assign it to you but you certainly can submit a PR for it 👍 

It's technically not ready to be worked on yet though since the implementation brief is not yet approved. You should wait to submit a PR until the you see that it has "✅  IB" but it's unlikely that much will change from what's already defined here since it's a fairly straightforward task.

**Comment by umuur** [comment]
Alright! Thanks!

**Comment by felixarntz** [comment]
IB ✅

**Comment by umuur** [comment]
I made a pull request (#1808), but 'deploy to wiki' check failed on 'Run actions/checkout@v2' stage. What could I missed?

**Comment by aaemnnosttv** [comment]
@umuur that is expected as certain actions (like deploys) will fail when triggered by PRs from a fork. Don't worry about that, the important part is that the Travis build passes 👍

**Comment by umuur** [comment]
Alright! I've commit new changes in order to pass Travis. Currently there is no issue with it. But the status for #1808 says "Merging is blocked".

**Comment by aaemnnosttv** [comment]
@umuur I've reviewed your PR, which looks good; just a few changes necessary. Let's continue the conversation over there 👍

**Comment by aaemnnosttv** [comment]
@felixarntz adding the release here to merge, although of course it doesn't really affect the release 😄

**Comment by ryanwelcher** [comment]
Confirming that all module settings stories are using `createLegacySettingsWrapper` 

QA ✅
