### ISSUE TITLE
Integrate commonStore into createModuleStore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1607]
## Feature Description

All our module datastores `modules/*` currently don't use the `commonStore`. `commonStore` should be integrated into `createModuleStore` so that this is automatically taken care of for all modules.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `createModuleStore` should return a store object that includes the `commonStore`.

## Implementation Brief

* Update `createModuleStore` to combine `Data.commonStore` into the resulting `combinedStore`  
https://github.com/google/site-kit-wp/blob/a4601c7367419bef3083cf3b5a56b714f6484ef1/assets/js/googlesitekit/modules/create-module-store.js#L78-L81
* Remove `Data.commonStore` from individual module stores  
E.g. https://github.com/google/site-kit-wp/blob/a4601c7367419bef3083cf3b5a56b714f6484ef1/assets/js/modules/pagespeed-insights/datastore/index.js#L33

## QA Brief

* 

## Changelog entry

* Simplify module datastore creation by including `commonStore` in the store returned `googlesitekit.modules.createModuleStore`.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
