### ISSUE TITLE
Require only readonly scopes for Tag Manager by default

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1608]
## Feature Description

As a follow-up to #1566, after refactoring the Tag Manager module (#1385, #1386) the module should be adjusted to only require the basic read-only scope. All other scopes should only be required for API datapoints that perform actions where these scopes are needed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Tag Manager module should only require the `https://www.googleapis.com/auth/tagmanager.readonly` scope by default.
* The Tag Manager API datapoints that require `https://www.googleapis.com/auth/tagmanager.edit.containers` or `https://www.googleapis.com/auth/tagmanager.manage.accounts` should be annotated as such, using the mechanism introduced as part of #1566.
* Users should need to go through the OAuth flow when creating a new Tag Manager container, granting the extra requested scope.

## Implementation Brief

* Update `Tag_Manager::get_scopes` to return an array of only `https://www.googleapis.com/auth/tagmanager.readonly`
* `POST:create-container` datapoint is already annotated with it's necessary scope (remove `isset` condition if still present)
* Update tests
* Update `SetupForm` component with auto-submit behavior after granting additional permissions (see `analytics/setup/setup-form.js`)
    - Should use `select( CORE_USER ).hasScope( SCOPE_CONTAINER_EDIT )` to conditionally auto-submit if necessary scope has been granted
	- Requires Tag Manager datastore includes `createSnapshotStore`

The `https://www.googleapis.com/auth/tagmanager.manage.accounts` scope is currently unused by any of our datapoints.
It may have been added previously when `tagpermission` requested [user permissions](https://developers.google.com/tag-manager/api/v2/reference/accounts/user_permissions/list) which does require this scope, and wasn't removed when we simplified this check later.

## QA Brief

* When activating Tag Manager, the only GTM scope you should see for it to grant is "View your Google Tag Manager container and its subcomponents"
![image](https://user-images.githubusercontent.com/1621608/87062776-2d1a7880-c216-11ea-91b7-3857c561cbfb.png)
* When creating a property or view for the first time, you should be prompted to grant additional scopes
    - After granting, property/view creation will be possible (until you go through oAuth again)

## Changelog entry

* Only require the `https://www.googleapis.com/auth/tagmanager.readonly` scope by default for Tag Manager, and request write scopes only as needed for a specific action.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Fixed via #1715.

**Comment by cole10up** [comment]
**Tested**

Installed latest develop, activated Analytics and setup tag manager.

Noticed during setup scopes in QA brief above:

![image](https://user-images.githubusercontent.com/57115907/87513518-b1f9fd80-c62d-11ea-8fe4-08920e982b3a.png)

Confirmed during cancelation of Tag Manager scopes user is able to redo setup

![image](https://user-images.githubusercontent.com/57115907/87513635-dfdf4200-c62d-11ea-9d5f-4996d8a24ba2.png)

![image](https://user-images.githubusercontent.com/57115907/87513679-f4bbd580-c62d-11ea-8233-76a57d90a56f.png)

Confirmed new account setup flow

![image](https://user-images.githubusercontent.com/57115907/87513809-2765ce00-c62e-11ea-8e0e-93e33d57d04a.png)

Confirmed fetch new account functions

![image](https://user-images.githubusercontent.com/57115907/87513927-5419e580-c62e-11ea-8f77-f2a763e7cd75.png)

![image](https://user-images.githubusercontent.com/57115907/87513964-609e3e00-c62e-11ea-8206-23dc4012c53f.png)

Passed QA ✅
