### ISSUE TITLE
Migrate all modules to use `Module::get_datapoint_definitions()` and deprecate `Module::get_datapoint_services()`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1609]
## Feature Description

#1566 introduced a new method `Module::get_datapoint_definitions()` that allows for more flexibility for a module to define its datapoint interface, surpassing the previous `Module::get_datapoint_services()`, which only allows a datapoint to be associated with a service, but no additional information. The new method has a base implementation that only exists for backward-compatibility though, in a perfect world it would be abstract.

As part of #1566 only the immediately necessary datapoints (some in Analytics, some in Tag Manager) were migrated to use `Module::get_datapoint_definitions()`, so this issue should migrate all other datapoints over, so that none of our modules any longer implements `Module::get_datapoint_services()`. Any code that currently calls `Module::get_datapoint_services()` should be modified to rely on `Module::get_datapoint_definitions()` (except the one call in `Module::get_datapoint_definitions()` that makes the backward-compatibility work).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All module PHP classes should implement `Module::get_datapoint_definitions()`, covering all datapoints that are currently covered in `Module::get_datapoint_services()`.
    * Note that `Module::get_datapoint_definitions()` also takes the request method into account, while `Module::get_datapoint_services()` didn't (another improvement here).
    * Since all datapoints currently covered by `Module::get_datapoint_services()` only provide the API service name they're using, the migration should be straightforward just providing the `service` key.
* `Module::get_datapoint_services()` shouldn't be implemented or used anymore anywhere, except in the `Module::get_datapoint_definitions()` base implementation.

#### For each `Module` sub-class
* Add a `protected function get_datapoint_definitions()` method (if not present)
* Add a `GET:{datapoint}` key to the returned array for all applicable entries in `get_datapoint_services`
* Add a `POST:{datapoint}` key to the returned array for all applicable entries in `get_datapoint_services`
* All added entries should be a minimum of `array( 'service' => {service} )` where `{service}` is the value defined in `get_datapoint_services`  
This key should always be set, even if empty
* Modules that already implement `get_datapoint_definitions` should be updated to no longer call the `parent::get_datapoint_definitions()`
    - Existing datapoint definitions should be updated to include the `service` key with their respective service
* The `get_datapoint_services` method should be removed
* References to `get_datapoint_services` should be updated to use `get_datapoint_definitions` and must account for different return value

#### `Module`
* Update `Module::get_datapoints` to use `get_datapoint_definitions` instead
* Update `Module::get_batch_data` to use `get_datapoint_definitions` instead
* Annotate `Module::get_datapoint_services()` with `@deprecated n.e.x.t`
* Add `_deprecated_function` call to `Module::get_datapoint_services()` indicating `static::class . '::get_datapoint_definitions()'` as the replacement to use instead

## QA Brief

* 

## Changelog entry

* Deprecate `Module::get_datapoint_services()` PHP method in favor of `Module::get_datapoint_definitions()` for more flexibility in annotating API datapoints.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* All references to `get_datapoint_services` have been updated to use `get_datapoint_definitions`
* `get_datapoint_services` is now deprecated
* All modules now implement `get_datapoint_services` for all datapoints with matching definitions for previously defined services
