### ISSUE TITLE
Errors when getting OAuth credentials

### ISSUE THREAD

**Issue by Awaisaliarain** [google/site-kit-wp#161]
![issue 2](https://user-images.githubusercontent.com/26734580/60938653-1c2ae480-a2ee-11e9-8b52-6fba68f44aeb.PNG)
![Issue one](https://user-images.githubusercontent.com/26734580/60938654-1cc37b00-a2ee-11e9-874f-48c0ecbf898d.PNG)

i am facing a erro  when getting OAuth credentials

**Comment by Awaisaliarain** [comment]
![issue 4](https://user-images.githubusercontent.com/26734580/60938897-2e595280-a2ef-11e9-9d7b-72efbe47b440.PNG)
![issue 3](https://user-images.githubusercontent.com/26734580/60938898-2e595280-a2ef-11e9-8201-f9c4ef89b1da.PNG)



Hi! i am facing 2nd  problem on my other wordpress site. when iam connecting my google account it will redirct to my siteb home page not getting all info to site kit plugin.

**Comment by jamesozzie** [comment]
@Awaisaliarain Thanks for informing us. For the issue regarding Project ID there is an existing open issue, #24.

Do you have a staging site you can check with another theme and with your plugins deactivated? Or if you are in a position to temporarily deactivate your other plugins on an existing site before trying the following we can see if that works?
- Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
- Temporarily deactivate other plugins
- Deleting the existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager?previousPage=%2Fiam-admin%2Fsettings%3Fproject%3Dampfaces-prescho-1561454403106&folder=&organizationId=&project=ampfaces-prescho-1561454403106)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
- Install Site Kit in a new incognito window.
- Check your Site Kit dashboard.

Please let me know and we can hopefully assist.

**Comment by Awaisaliarain** [comment]
what about your second problem? which is not redirect on site kit plugin
page after verify email

**Comment by jamesozzie** [comment]
Hi @Awaisaliarain 

There could be a plugin conflict causing the redirection. You in a position to temporarily deactivate other plugins before trying to activate Site Kit again? Please use an incognito window and reset Site Kit first, using an incognito window ensures a clean cache and no potential issues with any Chrome extensions.

**Comment by jamesozzie** [comment]
@Awaisaliarain Did you have any luck setting up Site Kit? For the OAuth error you can manually create your credentials using the steps below:
1. Close the "Couldn't create project" window you are/were encountering
2. In the address bar of your window paste the following in:
3. https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
4. - Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the httpss if you have a securite site
5. - Press enter, with your cursor in the address bar (as if you are visiting that URL)
6. - Press the "GET OAUTH CREDENTIALS" button
7. - The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

In relation to the redirecting error are you using iThemes security? If so can you uncheck [this](https://i.imgur.com/7OyyYyI.png) option from the general settings. If you are using an alternate security plugin there could be settings which are impacting your setup, inform me of any additionals plugins you are using if the above fails to resolve the issue.

**Comment by jamesozzie** [comment]
Closing this ticket with no response received. If you are encountering the same issue feel free to reopen.
