### ISSUE TITLE
Rename legacy `googlesitekit` object to `_googlesitekitLegacyData`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1615]
## Feature Description

The `global.googlesitekit` object that is used to pass data from PHP to JS for our legacy codebase will be removed in the long term either way. However, it is becoming increasingly problematic for it to still be around, since some new JS code actually _should_ be using `global.googlesitekit` to expose a public API:
* Any such asset, e.g. `googlesitekit-data`, can run into issues if it's enqueued too early, before the legacy `global.googlesitekit` object is printed. In this case, the new API bits would just be overridden, resulting in tons of JS errors.
* Other assets, e.g. `googlesitekit-modules` rely on a specific sub-key that is also used by the legacy data. In this case, even when enqueued late enough, the asset needs to provide logic to merge its APIs in, so that both the new APIs and the legacy data continue to work.

Another problem is that inspecting `global.googlesitekit` is rather confusing now, seeing an object that is mixed up between APIs developers _should_ use and PHP-to-JS data developers _should not_ use.

Because of these problems, `global.googlesitekit` (for legacy data, _not_ for new APIs) should be renamed to `global._googlesitekitLegacyData`. All references (production code, tests, Storybook, BackstopJS data, ...) need to be adjusted accordingly, which is probably going to be a fair amount of work. (At least, there is `getModulesData()` to make the replacement quick and simple for _that_ case.)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All PHP-to-JS legacy data currently part of `global.googlesitekit` should instead be part of a new `global._googlesitekitLegacyData` (quick to change in PHP, quite a bit to change in JS).
* `global.googlesitekit` should _only_ house the new APIs (`googlesitekit.api`, `googlesitekit.data`, `googlesitekit.modules`, `googlesitekit.widgets`).
* All references to legacy data should be correctly modified to reference the new `global._googlesitekitLegacyData`. BackstopJS data will also need to be regenerated like that.

## Implementation Brief

- In `includes/Core/Assets.php` change the name of on the global from `googlesitekit` to `_googlesitekitLegacyData` - https://github.com/google/site-kit-wp/blob/develop/includes/Core/Assets/Assets.php#L364
- Update all legacy code( ie. `assets/js/components` and `assets/js/util` ) references from `googlesitekit` to `_googlesitekitLegacyData` being sure to update the related tests, Storybook, and BackstopJS accordingly. 
- Files such as `assets/js/googlesitekit-modules.js` should not be refactored.
## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@ryanwelcher I think some things here need to be refined, maybe the description was slightly unclear.

> Edit the `get_inline_data` method to no longer add the `modules` key.

The `modules` key should still remain there, the conflict with new APIs would be resolved already by renaming the `googlesitekit` object for legacy data.

> Update all references to `_googlesitekitLegacyData` in production code, tests, Storybook, and BackstopJS. A quick search showed ~ 265 results across 99 files but that may not be exhaustive.

I may be nitpicking here, but note that this should only be adjusted when it comes to _legacy_ production code. Code referencing new APIs (e.g. `googlesitekit.data`, `googlesitekit.widgets` or so) should not be updated, these APIs should remain on `googlesitekit`. So we should be careful doing a search-and-replace here - it can probably be a search-and-replace for the majority of our codebase (e.g. pretty much all of `assets/js/components` and `assets/js/util` is legacy code), but any refactoring files like e.g. `assets/js/googlesitekit-modules.js` should not have this replaced.

**Comment by ryanwelcher** [comment]
@felixarntz I've updated the IB, please review when you can.

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
