### ISSUE TITLE
Expand visual regression tests to include refactored screens

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1616]
While our visual regression tests take quite a bit to run, they are still very useful when it comes to ensuring the integrity of our UI over time. However, now that more and more of the codebase has been getting refactored with a higher emphasis on building out Storybook stories, none of the new stories is yet part of our VRTs. This has led to oversights where Storybook would get broken by PRs because (of course) it wouldn't always be manually checked through.

We should define a list of stories to include in Storybook to get a better sense of breakage there. This can also include revisiting the existing stories covered and whether some of them are no longer necessary.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This will become more feasible as stories are being migrated to CSF (see [this doc](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit), specifically [here](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit#heading=h.qb9296pheam6)).

For now marking as _Stalled_ because it's not really applicable until then.

**Comment by aaemnnosttv** [comment]
@felixarntz moving this forward now that the new integration with Backstop is completed 👍

**Comment by felixarntz** [comment]
@aaemnnosttv Not sure we're really in a place to do this just _yet_ since a ton of stories are still using the old format. I think there will need to be a bunch of other "migrate story for widget x to CSF" issues first.

**Comment by aaemnnosttv** [comment]
Closing this as we have resumed creating new VRT scenarios for many new components since this was last updated so this is no longer relevant as a standalone issue.
