### ISSUE TITLE
Add e2e coverage for additional scopes requests

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1617]
#1566 introduced a more incremental way to request write scopes only when necessary. At the moment this is only used by Analytics, but shortly will be used by Tag Manager as well (#1608), and potentially further modules in the future.

While this has been tested and will be shipped without e2e tests in 1.9.0 (due to time constraints), we should have some e2e tests to cover these cases, since it's not something that can reasonably be covered with Jest.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be new e2e tests for the following:
    * Creating an Analytics account (via proxy & provisioning API) when not having the `https://www.googleapis.com/auth/analytics.provision` scope yet. Expected experience:
        * The user sees a notice above the button that explains they will need to grant additional permissions.
        * Upon clicking the button, they're redirected to OAuth (should be mocked).
        * When returning, their original action is automatically invoked, without requiring them to click the button again.
        * They should be redirected to the Analytics TOS ~~(can be mocked to an immediate success redirect to Site Kit (`...?gatoscallback=1...`)).~~
        * ~~They should end up on the dashboard.~~
    * Creating an Analytics property when not having the `https://www.googleapis.com/auth/analytics.edit` scope yet. Expected experience:
        * Upon clicking the button, a dialog opens informing the user that they will need to grant additional permissions.
        * Once they click _that_ button, they're redirected to OAuth (should be mocked).
        * When returning, their original action is automatically invoked, without requiring them to click the button again.
        * They should end up on the dashboard.
    * Creating an Analytics view when not having the `https://www.googleapis.com/auth/analytics.edit` scope yet. Expected experience should match the one for creating an Analytics property above.

## Implementation Brief
- Create a new `write-scope-requests.test.js` in `tests/e2e/specs/modules/analytics`
- Implement a new `describe` for `Analytics write scope requests`
- In a `beforeAll`, ensure that any oAuth requests are intercepted and successfully returned. [See this example](https://github.com/google/site-kit-wp/blob/develop/tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js#L36). Also ensure that any requests to the Analytics TOS as are also mocked and returned successfully.
- In the `beforeEach`, ensure that the Analytics module is set up by adding the following helpers:
    - `activatePlugin( 'e2e-tests-oauth-callback-plugin' )`   
    - `setSiteVerification()`
    - `setSearchConsoleProperty()`
    - `setupAnalytics()`
- Write tests fulfilling the requirements as indicated in the AC.

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz - @eugene-manuilov and I talked about the first test described for "Creating an Analytics account" and it doesn't seem useful to go past the redirection to the TOS page since we would have to intercept that request to send the user back to the `gatoscallback` URL. This would require we mock API plugin on the server to handle the `create-account` request so that the transient would be set when we land on this URL only to trigger the redirect. This handler has good coverage as it is in `AnalyticsTest::test_handle_provisioning_callback` so we feel like it should be okay to consider this test done at this point, also because we can't control the request to the `gatoscallback` since that comes from the proxy - we would end up testing our own mocks.

If you agree, would you please update the AC to reflect this change? Essentially only the last step "They should end up on the dashboard." would be removed.

**Comment by eugene-manuilov** [comment]
> Creating an Analytics property when not having the https://www.googleapis.com/auth/analytics.edit scope yet. Expected experience:
>*    ...
>*    When returning, their original action is automatically invoked, without requiring them to click the button again.
>*    They should end up on the dashboard.

@felixarntz @aaemnnosttv auto submission isn't implemented for analytics settings edit form. Thus these two last points doesn't make sense in property and profile creation tests. I have implemented tests that check that if a user doesn't have sufficien permission, they will see a permission dialog and be redirected to the OAuth when they click "Proceed" button.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov that's correct - the auto-submit is not currently possible in the settings screen context because the submit button/action is outside of the settings components. It is possible however in the module set up context. Since the AC doesn't specify the context, we should be able to test both of these in the module set up context.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv there is no way to create a new property or a new profile when we are creating a new account. The only way is in the settings screen as far as I see it. Or am I missing something?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov a new property and view are created as part of the account creation/provisioning process on the Google side. So after the account creation is completed, you will have a new property and view for the new account but it doesn't create these from the Site Kit side, if that's what you're asking?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv i meant that we can't do what you said:`Since the AC doesn't specify the context, we should be able to test both of these in the module set up context.` - we can test new property and new view creation only on the settings page.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I see what you mean now, although this is a bug introduced in #716 as it should be possible to create a new property and view during setup. Because `ProfileNameTextField` is not rendered when the option is selected, the default value is not set and so `canSubmitChanges` blocks submitting the form because the profile name is empty and thus invalid.

I'll create an issue to fix this. cc: @felixarntz

**Comment by aaemnnosttv** [comment]
Actually, since the actual code change to fix this is so small we should probably fix it here as a separate issue to fix would need tests for it anyways.

This change fixed it for me although this should be thoroughly tested:
```diff
diff --git a/assets/js/modules/analytics/setup/setup-form.js b/assets/js/modules/analytics/setup/setup-form.js
index 4e90b0cc..5ccc2291 100644
--- a/assets/js/modules/analytics/setup/setup-form.js
+++ b/assets/js/modules/analytics/setup/setup-form.js
@@ -41,6 +41,7 @@ import {
 	ExistingTagNotice,
 	ProfileSelect,
 	PropertySelect,
+	ProfileNameTextField,
 } from '../common/';
 import { trackEvent } from '../../../util';
 import { isPermissionScopeError } from '../../../googlesitekit/datastore/user/utils/is-permission-scope-error';
@@ -99,6 +100,10 @@ export default function SetupForm( { finishSetup } ) {
 				<ProfileSelect />
 			</div>
 
+			<div className="googlesitekit-setup-module__inputs googlesitekit-setup-module__inputs--multiline">
+				<ProfileNameTextField />
+			</div>
+
 			<div className="googlesitekit-setup-module__action">
 				<Button disabled={ ! canSubmitChanges }>
 					{ __( 'Configure Analytics', 'google-site-kit' ) }

```

**Comment by eugene-manuilov** [comment]
@felixarntz @aaemnnosttv here is a PR for the hotfix: https://github.com/google/site-kit-wp/pull/1753

**Comment by felixarntz** [comment]
Opened a separate issue #1754 for tracking since this will go into its own hotfix release.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv ok, #1735 is ready for review. I have reworked it a bit to match AC requirements.

**Comment by aaemnnosttv** [comment]
@felixarntz I've updated the AC for the first case (account provisioning) as mentioned above to only test up until the redirect to the TOS. This is because it would require more substantial changes to only test the `gatoscallback` handler which is already well tested in PHPUnit.

**Comment by tofumatt** [comment]
Code here looks good to me and the tests behave appropriately, so moving to approval.
