### ISSUE TITLE
Scaffold `modules/optimize` datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1620]
## Feature Description

Similar to #1224, #1248, #1385, #1498, #1500, Optimize should receive a `modules/optimize` datastore.

**This is the last module to receive this type of refactoring!** 🎉 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Introduce datastore `modules/optimize` that is registered on `googlesitekit.data` and exported from `assets/js/modules/optimize/datastore`.
* Rename `assets/js/modules/optimize/index.js` to `assets/js/modules/optimize/index.legacy.js` and update relevant import references.
* Add new `assets/js/modules/optimize/index.js` that for now simply imports from `./datastore`.
* Introduce JS entrypoint asset `googlesitekit-modules-optimize.js` with similar handle in PHP (via a new `Optimize::setup_assets()` implementation). It should simply import from `./modules/optimize`.
* The datastore should use `createModuleStore` to expose the relevant Optimize settings selectors and actions (for `optimizeID`, and `ampExperimentJSON`). Note that for `ampExperimentJSON`, a manual renaming of the selector and action needs to happen (so that it becomes `getAMPExperimentJSON` / `setAMPExperimentJSON`), similar as done for Tag Manager before (see https://github.com/google/site-kit-wp/issues/1385#issuecomment-621348685). The datastore should also expose the following action:
    * `submitChanges()`: Should submit changes from setup or settings, and behave similarly to e.g. Analytics (will be simpler though because it really only needs to use the `saveSettings()` action at this point).

## Implementation Brief

* Create new directory `datastore` in `assets/js/modules/optimize` and create `index.js` in it. 
* Rename `assets/js/modules/optimize/index.js` to `assets/js/modules/optimize/index.legacy.js` and update relevant import references.
* Add new `assets/js/modules/optimize/index.js` that for now simply imports from `./datastore`.
* Create `googlesitekit-modules-optimize.js` in `assets/js` and import `./modules/optimize` into it.
* Add a new entry point in `webpack.config.js` called `googlesitekit-modules-optimize` that uses `assets/js/googlesitekit-modules-optimize.js`.
* Set up a matching handle in `includes/Modules/Optimize.php`  by having the `Optimize` console class implement the `Module_With_Assets` interface and use `Module_With_Assets_Trait` and creating a `setup_assets` similar to https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L1292
* In `assets/js/modules/optimize/datastore/index.js` import `Modules` from `googlesitekit-modules` and create a new base store using `Modules.createModuleStore` with the name of `optimize`. 
* The datastore should expose the relevant Optimize settings selectors and actions (for optimizeID, and ampExperimentJSON). For `ampExperimentJSON`, a manual renaming of the selector and action needs to happen (so that it becomes `getAMPExperimentJSON` / `setAMPExperimentJSON`), similar as done for Tag Manager before (see https://github.com/google/site-kit-wp/issues/1385#issuecomment-621348685). 
* The datastore should also expose the following action:
    * `submitChanges()`: Should submit changes from setup or settings, and behave similarly to e.g. Analytics (will be simpler though because it really only needs to use the `saveSettings()` action at this point).

## QA Brief

* 

## Changelog entry

* Introduce `modules/optimize` JS datastore for Optimize module.

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
