### ISSUE TITLE
Refactor Optimize setup/settings components to use datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1621]
## Feature Description

Similar to #1101, #1014, #1386, #1499, #1501, the module setup and settings components for Optimize should be refactored to use the datastore.

**This is the last module to receive this type of refactoring!** 🎉

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All changes should be made within the `assets/js/modules/optimize` directory.
* The datastore from #1620 should be used. If further selectors/actions are required, it can be amended as part of this.
* There should be `SettingsView` and `SettingsEdit` components that each display the same content which these respective Optimize areas display today.
* There should be a `SettingsMain` component for the settings panel, that conditionally displays `SettingsEdit` or `SettingsView`.
* The components should only access datastore data, never anything from globals.
* There should be new Optimize/Setup and Optimize/Settings sections in Storybook with the setup UI and settings panel in different states, similar to how it was added for the issues linked above.
* The implementation should follow patterns established as part of the issues linked above.
* All functionality should remain as it originally was.

### Additional ACs as found necessary during implementation

See https://github.com/google/site-kit-wp/pull/1675#pullrequestreview-443394496

* The Optimize `ampExperimentJSON` setting should from now on store values as actual JSON strings. Existing setting values (e.g. objects or `null`) should be automatically transformed into such a string upon retrieval (e.g. the API should only ever expose the string version).

## Implementation Brief

* This ticket is blocked by #1620, which creates the new optimize datastore.
* Move `setup.js` into `assets/js/modules/optimize/setup/`. This currently contains the components that are to be split into `settings`, `setup` and `common`.
	- Create a new `assets/js/modules/optimize/setup/index.js` to import the new `setup.js`.
	- All components for `settings` and `common` to be moved from here (see below ). 
	- New `setup.js` to refactor `renderForm()` in current `setup.js`
* Create reusable common Optimize components in `assets/js/modules/optimize/common/` for:
	- `optimizeID` - currently `rederinfo()` in `setup.js`
	- `ampExperimentJSON` - currently `renderAMPSnippet()` in `setup.js`
* Create settings components in `assets/js/modules/optimize/settings/`. Currently found in `setup.js`.
	- `SettingView` ( `assets/js/modules/optimize/settings/settings-view.js` ) - to display the same content as is currently displayed.
	- `SettingEdit` ( `assets/js/modules/optimize/settings/settings-edit.js` ) - to display the same content as is currently displayed.
	- `SettingMain` ( `assets/js/modules/optimize/settings/settings-main.js` ) - to conditionally display `SettingsEdit` or `SettingsView`.
* New Optimize/Setup and Optimize/Settings sections in Storybook should be created with the setup UI and settings panel in different states. See #1501, #1499.
* The implementation should follow patterns established as part of the issues linked above.
* All functionality should remain as it originally was.

## QA Brief

* 

## Changelog entry

* Significantly improve stability and maintainability of Optimize module setup and settings, and fix bug where editing Optimize settings with AMP active could cause an error due to the `ampExperimentJSON` module setting not being stored as JSON string.

**Comment by felixarntz** [comment]
@ShahAaron IB looks mostly good, just want to emphasize that the current `setup.js` should be split like elsewhere, to have the separate components for setup and settings. It's maybe a bit high level here, we should specify further since this is a bit more complex than it was for e.g. Search Console and PageSpeed Insights (since they didn't have any editing capabilities). UI components that are used in both of them should be implemented as their own reusable `common` components (see e.g. Analytics or AdSense module), for example the Optimize ID input field and the AMP experiment JSON textarea. Would be great if you could refine the IB a bit more to cover all those cases.

**Comment by ShahAaron** [comment]
@felixarntz I've refined the IB as requested

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed latest SK release candidate. Ran through a series of regression test around optimize. Installing module, uninstalling. Confirming container setup.

![image](https://user-images.githubusercontent.com/57115907/86839684-98b5e780-c056-11ea-9cf7-252a8f61208d.png)

Passed QA ✅
