### ISSUE TITLE
Expand `googlesitekit-modules` JS API to allow registering modules

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1622]
## Feature Description

Modules are currently registered in PHP and exposed to JS via the `core/modules/data/list` API endpoint. However, we will also need to register module data in JS, e.g. components to use as settings panels. Data registered in JS should be combined with the data registered in PHP, with JS taking precedence.

While the focus of allowing pure-JS module registration (no PHP) is not important at this point, we should build it pretty much with that in mind.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a scaffolded JS component `DefaultModuleSettings`, within `assets/js/googlesitekit/modules/components`. For now it can just return `null`, implementation should be in a follow-up issue.
* A new action `registerModule( slug, settings )` should be added to the `core/modules` datastore:
    * The following `settings` arguments should be supported for now:
        * `settings.name`: Optional. Module name. Default is the `slug`.
        * `settings.description`: Optional. Module description. Default empty string.
        * `settings.icon`: Optional. Module icon. Default empty string.
        * `settings.order`: Optional. Numeric indicator for module order. Default 10.
        * `settings.homepage`: Optional. Module homepage URL. Default empty string.
        * `settings.internal`: Optional. Whether the module is considered internal. Default false.
        * `settings.settingsComponent`: Optional. React component to render the settings panel. Default is the `DefaultModuleSettings` component.
    * This data should be registered in the existing store state property `modules`, being merged into the data for the respective module there, if already exists. In other words, before actually running the code register the module, the action should fetch server-side module data via `core/modules/data/list` automatically, so that after that everything can work fully client-side.
    * When merging, the above default values for `settings` should only be applied if there is _neither_ a client-side value _nor_ a server-side value for it. Note that these defaults should also apply if no client-side registration call is ever made. This will mostly be irrelevant for our current usage, however, e.g. the `settingsComponent` will never be registered in PHP (not possible), so that data should be filled with the default even if it was purely loaded from PHP.
* The existing `getModules` selector should be modified to return modules sorted by `order` ascending. If not present, 10 should be assumed.
* Both `getModules` and `getModule` should be modified to also include `settingsComponent`, which will technically be stored outside of the datastore (see how the `googlesitekit-widgets` datastore handles components related to datastore).
* In PHP, the API endpoints `core/modules/data/list` and `core/modules/data/info` should be augmented to include each module's `order` in the response so that this data is also taken into account in PHP.
* There should be solid Jest test coverage, particularly to ensure the merging from server-side and client-side data works as expected.
* Side effect: Rename `isSettingModuleActivation` selector to `isDoingSetModuleActivation` to match our naming conventions.

In the future, the `settings` parameter for `registerModule` will be expanded to allow for more data as necessary (e.g. `setupComponent`, which is not necessary for now since that is still handled separately).

## Implementation Brief

* Add a `registerModule( slug, settings )` action to the `core/modules` datastore. All `settings` arguments are optional; `slug` is required.
    * `settings` should accept the arguments:
        * `settings.name`: Defaults to `slug` if not supplied.
        * `settings.description`: Default `null`.
        * `settings.icon`: Default `null`.
        * `settings.order`: Default `10`.
        * `settings.homepage`: Default `null`.
        * `settings.internal`: Default `false`.
        * `settings.settingsComponent`: Optional. React component to render the settings panel. Default is the `DefaultModuleSettings` component. (See #1623)
    * Module registration should be additive; any calls to `registerModule` should merge data passed to `registerModule` with data already loaded from the `core/modules/data/list` endpoint. (Default values should not overwrite existing values.)
* Modify `getModules()` selector https://github.com/google/site-kit-wp/blob/af5b679c11ba92b266f1a659f9b840823d8173b7/assets/js/googlesitekit/modules/datastore/modules.js#L324 to return modules in order similar to https://github.com/google/site-kit-wp/blob/af5b679c11ba92b266f1a659f9b840823d8173b7/assets/js/googlesitekit/widgets/datastore/widgets.js#L224. (In fact, we use that sort function in several places and should abstract it out.)
* store `settings.settingsComponent`s in the same manner as widget components (see: https://github.com/google/site-kit-wp/blob/af5b679c11ba92b266f1a659f9b840823d8173b7/assets/js/googlesitekit/widgets/datastore/widgets.js#L39). Ensure they're stored on a per-registry basis and not shared between registries. This is already done in the widgets example, so follow that 🙂
* Add `order` to the responses in the `core/modules/data/list` and `core/modules/data/info` endpoints.

## QA Brief

* 

## Changelog entry

* Introduce `registerModule` action to `core/modules` store, which allows for JS module registration and will in the future enable registration of module components.

**Comment by felixarntz** [comment]
@tofumatt I assigned this to you for IB since it's fairly similar to what you've done for widgets, with some nuances.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@tofumatt I just noticed `core/modules` has a `isSettingModuleActivation` selector - per our naming conventions that should be called `isDoingSetModuleActivation`, so I've added to the ACs to do this renaming here.

**Comment by felixarntz** [comment]
Moving this out of the release since it's not critical.

**Comment by tofumatt** [comment]
Reviewed and approved; assigning to @aaemnnosttv for merge.

**Comment by eugene-manuilov** [comment]
QA :x: 

@ryanwelcher the following requirement in the AC list is not implemented. Could you please implement it too? Everything else looks good to me.

> Side effect: Rename isSettingModuleActivation selector to isDoingSetModuleActivation to match our naming conventions.

**Comment by ryanwelcher** [comment]
@eugene-manuilov thank you for catching that! I've added a new PR to this issue ( #1839 ) to address this.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
