### ISSUE TITLE
Fix regression of module activation/deactivation always firing deactivation event

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1629]
## Bug Description

We've recently noticing a decline in `module_activate` Analytics tracking events being submitted, and it turns out that actually none of these were being sent at all.

While changing the API datapoint for module activation/deactivation in https://github.com/google/site-kit-wp/commit/c0aa178bd9d2562b12c5067d050d67649739378f, the API response format was changed so that there would never be a `responseData.active` as e.g. referenced in https://github.com/google/site-kit-wp/blob/c0aa178bd9d2562b12c5067d050d67649739378f/assets/js/util/index.js#L528. This would result in an incorrect module activation status (`undefined`) in the `googlesitekit` global (sounds worse, but is fortunately pretty much irrelevant for how we use it), but it messes up the tracking to only fire `module_deactivate` events. It appears that this has been broken since 1.5.0.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* References to the response data from `core/modules/data/activation` should be updated to the new response format.
* More precisely, the response shouldn't be used at all since it is just `true`. If the request completes and the promise resolves, we can just set the module activation status to the status it was supposed to be set to.

## Implementation Brief

The implementation requires not using `responseData.active` which no longer exists.

 * In `/assets/js/util/index.js` change the use of `responseData.active` to `status` which is passed in as a parameter by `activateOrDeactivateModule`.

## QA Brief

* 

## Changelog entry

* Fix bug with event firing when activating or deactivating a module.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest SK. Setup with tracking.

Ran a series of tests activating all modules and disconnecting all modules.

Noticed page speed insights is looking a bit off (seems unrelated), sent a slack to the team:
![image](https://user-images.githubusercontent.com/57115907/84736973-d5148d00-af5b-11ea-9794-cba47e1bbb6d.png)

![image](https://user-images.githubusercontent.com/57115907/84737018-eb224d80-af5b-11ea-95aa-872938a8ed78.png)

Confirmed all modules are able to be disconnected, site kit reset and functional.

Passed QA ✅
