### ISSUE TITLE
Ensure Site Kit tracking events are sent

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1630]
## Bug Description

In order to record tracking events with `gtag.js`, we're pushing event data onto the `dataLayer` stack as documented. However, as `gtag.js` works asynchronously, our current approach does not ensure these events are actually collected by Analytics - especially since the actual code we're writing simply adds data to an observed array.

[`gtag.js` provides a mechanism to know when an event was actually sent](https://developers.google.com/analytics/devguides/collection/gtagjs/sending-data#know_when_an_event_has_been_sent), so we should use this in the plugin. It will make the `trackEvent` function asynchronous, but that is okay. In most cases, we shouldn't even need to update the function calls - it's only really necessary in the cases where right afterwards e.g. a navigation away from the current page happens (e.g. module activation/deactivation or setup completion).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's tracking events should use the `event_callback` argument for `gtag.js` to "ensure" the event is actually sent - "ensure" in double quotes because there should still be a 1 second timeout in case there is a problem, since event tracking should not block the user or result in any user-facing error.
* If an event is not sent within the 1 second timeout, a console warning should be triggered.
* Code that calls the `trackEvent` function should do so asynchronously in every case where there is a navigation away from the page right after.

## Implementation Brief

* Return a promise in `trackEvent` that always resolves (consuming code should await, but doesn't need awareness of whether the event was sent in time or not).
* Pass `event_callback` among the arguments to `dataLayerPush`, making it resolve the promise.
* Use `setTimeout` with 1000ms to resolve the promise, triggering a console warning in this case.
* In the `event_callback` function, clear the timeout. Also add a safeguard in place to ensure the promise is only resolved once: Theoretically (probably not practically) the `event_callback` could kick in after 1 second, but in this case the promise would already been resolved by the timeout.
* Merge #1631.

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
