### ISSUE TITLE
Expose web vitals metrics in PSI widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1636]
## Feature Description

With the launch of [Web Vitals](https://web.dev/vitals/), the PageSpeed Insights API now exposes the relevant field data in API responses for all sites where it is available. [Sample API request](https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https%3A%2F%2Fweb.dev%2F&strategy=mobile)

We should expand the capabilities of the PageSpeed Insights widget to expose these metrics when available.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**This issue is only about putting the functionality in place, the exact UI will be handled in a follow-up issue. The end result of this issue should essentially be the widget displaying everything that's needed in the most basic and "ugliest" way possible.** 😄 

* Web vitals metrics should be exposed in the PageSpeed Insights widget in both the dashboard as well as single page stats, **if available in the API response for both "mobile" and "desktop"**.
* There should be two tabs in the upper left for toggling "Lab Data" and "Field Data" (exact wording TBD).
* There should be a button group on the upper right for toggling "Mobile" and "Desktop".
* If there is no field data available in the API response (currently that is the majority), the "Lab Data" tab should be the default tab. Otherwise, the "Field Data" tab should be the default tab.
* "Lab Data" tab should for now display:
    * Total blocking time
    * Largest contentful paint
    * Cumulative layout shift
* "Field Data" tab should for now display:
    * First input delay
    * Largest contentful paint
    * Cumulative layout shift
* Every one of these values should be marked with either "Good", "Needs improvement" or "Poor", based on the value.
* The widget should have the common footer that says "Source: PageSpeed Insights", with a link.

## Implementation Brief

* Modify `Google\Site_Kit\Modules\PageSpeed_Insights::parse_data_response()` to return the full `$response` from the PSI API instead of just the `lighthouseResult` property. Document this change with a new `@since` annotation since technically this is a breaking change. Since likely nobody uses our API endpoint directly, we can probably get away with it, but should at least document it.
* Implement a new `DashboardPageSpeed` functional component in `assets/js/modules/pagespeed-insights/components/DashboardPageSpeed.js`, with tabs and UI per the ACs. The component should fully rely on the datastore, except for the `permaLink` reference below that should still come for the global (migrating that should be a separate effort).
* Rely on `getReport` selector from `modules/pagespeed-insights` store to get the reports for "mobile" and "desktop".
    * If `global.googlesitekit.permaLink` (or `global._googlesitekitLegacyData.permaLink`, see #1615) is present, use that for the `url` parameter, otherwise use the site's URL (i.e. homepage URL) via `getReferenceSiteURL` on `core/site`.
* Use `core/forms` to manage the "Lab Data" vs "Field Data" tabs and the "Mobile" vs "Desktop" buttons.
    * "Mobile" should be the default.
    * If both mobile and desktop reports include `data.loadingExperience.metrics` in the response, "Field Data" should be the default; otherwise "Lab Data".
* For "Lab Data", display:
    * TBT: `data.lighthouseResult.audits[ 'total-blocking-time' ].displayValue`
    * LCP: `data.lighthouseResult.audits[ 'largest-contentful-paint' ].displayValue`
    * CLS: `data.lighthouseResult.audits[ 'cumulative-layout-shift' ].displayValue`
    * For the respective indicator, rely on the respective field's object's `score` value (between 0 and 1), with similar breakdown as currently is used for the overall PSI score. 
* For "Field Data", display:
    * FID: `data.loadingExperience.metrics.FIRST_INPUT_DELAY_MS.percentile` (should be displayed in milliseconds)
    * LCP: `data.loadingExperience.metrics.LARGEST_CONTENTFUL_PAINT_MS.percentile` (should be displayed in seconds, i.e. divided by 1000, rounded to 1 decimal)
    * CLS: `data.loadingExperience.metrics.CUMULATIVE_LAYOUT_SHIFT_SCORE.percentile` (should be displayed as value between 0 and 1, i.e. divided by 100, rounded to 2 decimals)
    * For the respective indicator, rely on the respective field's object's `category` value.
* The new component should be hooked into `googlesitekit.DashboardModule` and `googlesitekit.DashboardDetailsModule`, if the module is active in `assets/js/modules/pagespeed-insights/index.js`.
* The existing PageSpeed Insights dashboard widget components (now unused) should all be deleted. The only one remaining should be the `PageSpeedInsightsCTA` - hooking that in should also be the only thing that remains in `assets/js/modules/pagespeed-insights/index.legacy.js`
* No changes are necessary in the PHP API client since the existing API version was expanded with the data.

## QA Brief

* After setting up the plugin as usual, fake your site URL to be e.g. `https://web.dev` (which has field data available). That can be done e.g. via the developer settings plugin.
* Then activate PageSpeed Insights and check the widget in the dashboard.
* To check for a single page, create a page on your site with e.g. slug "vitals" (this is a real-world page on web.dev, so just creating an empty page with the same slug allows us to test field stats for it.

## Changelog entry

* Implement new version of PageSpeed Insights widget that focuses on core web vitals.

**Comment by felixarntz** [comment]
This issue is ready to be IB-reviewed and picked up as is. Note that there is no final mock yet, so this should only be focused on getting the widget ready to display the information and provide the functionality needed. In other words, just put some rudimentary tabs for "Lab Data" and "Field Data", a right-aligned button group "Mobile" and "Desktop", and then for each tab display the respective data in a `DataTable`.

**Comment by aaemnnosttv** [comment]
> Use two state hooks to manage the "Lab Data" vs "Field Data" tabs and the "Mobile" vs "Desktop" buttons

@felixarntz I'm not entirely sure what you mean by this but it sounds like you're referring to using `useState` to track the active tab? I think only one should be needed for that. Also, I think we could use `core/forms` for this rather than component state to keep it in the datastore without requiring added selectors, etc.

> If there is no field data available in the API response (currently that is the majority), the "Lab Data" tab should be the default tab. Otherwise, the "Field Data" tab should be the default tab

What happens if there is no Field Data? It sounds like this will be the majority of users for now. Should we disable that tab altogether or would it have a no data CTA type component like others do?

Aside from those, IB ✅

**Comment by aaemnnosttv** [comment]
Also the IB mentions `assets/js/modules/pagespeed-insights/components/DashboardPageSpeed.js` - should this not be `dashboard-pagespeed.js`?

**Comment by felixarntz** [comment]
@aaemnnosttv Good point on using `core/forms` for state of the widget, I've updated this bit.

If there's no Field Data, the tab should still be displayed, with some CTA (exact UI and wording to be defined in #1649).

**Comment by aaemnnosttv** [comment]
> Regarding the component file name, I thought we discussed yesterday to from now on move ahead with file names with the actual component names?

I recall the decision around whether or not to include in a directory but I don't remember discussing the filename. That sounds good to me though.

Thanks for the added clarification around Field Data handling 👍 

IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest SK release candidate.

Adjusted my site's URL to https://web.dev 

Activated PSI and validated creating a new page with the slug "supreme"

Confirmed PSI functioned properly

Passed QA ✅
