### ISSUE TITLE
WooCommerce compatibility: Error after attempting to send report

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1638]
## Bug Description

Originally reported in this [support topic](https://wordpress.org/support/topic/problems-with-sending-analytics-mail/), when attempting to send an email report from WooCommerce (for example from the _Analytics > Orders_  admin page), the process fails as reported in the _Status_ section of the plugin's admin. 

[CSV reports are emailed](https://docs.woocommerce.com/document/woocommerce-analytics/#download-to-csv) to the user by default after the number of data sets (orders for example) have surpassed the first page of the reporting table (25+). After pressing _Download_ there is a notification that the report will be emailed:

<img width="600" alt="WooCommerce order email download" src="https://user-images.githubusercontent.com/8108643/83819230-2d0ae400-a67e-11ea-9869-b89ca5642cd1.png">

Under _WooCommerce > Status > Logs_, the following critical error is present:

<img width="600" alt="Woocommerce error in logs" src="https://user-images.githubusercontent.com/8108643/83818871-3fd0e900-a67d-11ea-9665-39379c8ed8b3.png">

Under _WooCommerce> Status > Scheduled Actions_, the failed attempts for the hook `woocommerce_admin_report_export ` are logged with further detail as [noted in the topic](https://wordpress.org/support/topic/problems-with-sending-analytics-mail). 

While the user reported not getting the email report additionally, I have yet to receive an email with Site Kit deactivated to compare/ replicate this aspect. 

## Steps to reproduce

1. On a site with WooCommerce and 25+ orders, activate Site Kit
2. Go to (WooCommerce) _Analytics > Orders_
3. Scroll to the bottom and click _Download_
4. Go to _WooCommerce > Status> Logs_ and _Scheduled Actions_ respectively to see errors. 

## Additional Context

- PHP Version: 7.3.16
- OS: MacOS
- Browser: Chrome
- Plugin Version: 1.9.0
- Device: MacBook Air
- WooCommerce version: 4.20

#1637 experienced at the same time

Support topic for reference: 
https://wordpress.org/support/topic/problems-with-sending-analytics-mail/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@ernee This is a bug in WooCommerce - they're manually re-running the `rest_api_init` action without passing the mandatory first parameter, see https://github.com/woocommerce/woocommerce-admin/blob/v1.2.4/src/ReportCSVExporter.php#L125. I have opened an issue on their end to address this: https://github.com/woocommerce/woocommerce-admin/issues/4604

Let's keep an eye out on that issue - there's nothing we can do on our end regarding that.
