### ISSUE TITLE
Report bug on site performance with Site Kit

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#164]
Hi, let me point out that since I installed Site Kit there is a big drop in the site's performance by controlling even with Google PageSpeed, I tried disabling all the plugins and activating them one by one and Site Kit creates a performance loss.  Why?

**Comment by sviluppomania** [comment]
@jamesozzie

**Comment by jamesozzie** [comment]
@sviluppomania Sorry to hear you are encountering issues. When you mention a drop in performance I assume you mean page speed. What tool are you using to measure performance ([Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/), [web.dev](https://web.dev/) etc? There should be very minimal impact on page speed, Site Kit simply places the various module tags to your website, in the same way as tags would be placed manually. Most of the dashboard information and metrics are collected server side via the various product APIs. 

If you would like to put together some screenshots or added context of the problem you are encountering (including comparisons with and without your other plugins) we can certainly take a look into this for you.

**Comment by sviluppomania** [comment]
@jamesozzie 
Hi James, in the attachment there are 4 screenshots of Google PageSpeed Insight, for various reasons I have obscured the url of my site. 2 mobile (inactive plugin and active plugin) and same for Desktop.

**Google PageSpeed Insight with plugin disabled:**

**Desktop**: https://i.ibb.co/nMn9tHs/Desktop-inactive.png

**Mobile**: https://i.ibb.co/Px7kQ70/Mobile-inactive.png




**Google PageSpeed Insight with active plugin:**

**Desktop**: https://i.ibb.co/2tx57mf/Desktop-active.png 

**Mobile**: https://i.ibb.co/CwPwqtS/Mobile-active.png

**Comment by jamesozzie** [comment]
Thanks for the update, I will keep this open while performing some checks from my side and look at what other aspects of the plugin might be having an impact.

**Comment by jamesozzie** [comment]
@sviluppomania I have performed a few tests using PageSpeed Insights and also web.dev (which also uses the Lighthouse API) and I was unable to see any consistent or noticeable difference in performance. Do you have any security plugins with plugin rules in place, or scanned internals which might have impacted performance during your testing?

**Comment by jamesozzie** [comment]
@sviluppomania I will close this now as I am unable to gather any notificale differences when using Page Speed Insights.
