### ISSUE TITLE
"Error desconocido (código: cURL error 77: ). Para reanudar la configuración empieza aquí"

### ISSUE THREAD

**Issue by Kali-Gula** [google/site-kit-wp#1642]
## Bug Description

I have this message error after install plugin and try to configure my google acount:
"Error desconocido (código: cURL error 77: ). Para reanudar la configuración empieza aquí"
Before I was using "Google Analytics Dashboard Plugin for WordPress by MonsterInsights"
I uninstall it and try to install G Site Kit.

I make 3 steps to configure the plugin and when finishes error appears.

Can you help me please.
Thanks !

## Screenshots
![Captura de pantalla 2020-06-06 a las 9 48 52](https://user-images.githubusercontent.com/66510480/83939194-42e1eb80-a7db-11ea-9b3d-592c03da482b.jpg)

 - PHP Version: 7.3.18
 - OS: [e.g. iOS] MacOs
 - Browser [e.g. chrome, safari] Firefox
 - Plugin Version [e.g. 22]  Versión 1.9.0
 - Device: [e.g. iPhone6] Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@Kali-Gula thanks for reporting! Could you open [a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) in the [Site Kit WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/)? We can assist you further there. Thank you!
