### ISSUE TITLE
Add a shared VSCode config

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1647]
We should add a shared `.vscode/settings.json` to the project that includes things like Jest config paths and recommended extensions to improve developer productivity when using VSCode. @ryanwelcher had some snippets that would be handy as well, but for me I benefit from:

```json
"jest.autoEnable": false,
"jest.pathToConfig": "./tests/js/jest.config.js",
```

along with some other auto-format-on-eslint settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A shared, `.vscode` config is checked into the repo, allowing developers to share common settings.
* Jest tests run automatically in VSCode.

## Implementation Brief

* Create a new file `.vscode/settings.json` with the following contents:
```
{
	"editor.formatOnSave": false,
	"editor.codeActionsOnSave": {
		"source.fixAll.eslint": true
	},
	"eslint.alwaysShowStatus": true,
	"phpcs.enable": true,
	"phpcs.executablePath": "vendor/bin/phpcs",
	"jest.autoEnable": false,
	"jest.pathToConfig": "./tests/js/jest.config.js",
}
```
* Add `.vscode/launch.json` to the `.gitgnore` to prevent this file from being committed if users have their own settings.

## QA Brief

* Open the project in VSCode with the [Jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) extension installed, then use the command palette to run "Jest: Start runner" and observe the Jest tests being run in VSCode.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by Hazlitte** [comment]
QA ✅
