### ISSUE TITLE
Only include opt-in GA tracking script on Site Kit admin screens

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1648]
## Feature Description

Site Kit currently includes the GA tracking snippet on all pages where it's loaded. This has resulted in some concerns particularly when including it in the frontend for logged-in users (due to the Site Kit admin bar menu).

We don't use any specific tracking events in the admin bar menu or WP dashboard widget, so it's better to not include the snippet for those areas.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's GA tracking script should only be included on Site Kit-owned admin screens:
    * `googlesitekit-dashboard`
    * `googlesitekit-splash`
    * `googlesitekit-settings`
    * `googlesitekit-module-*`

## Implementation Brief

* In the PHP `Tracking` class:
    * Add a new property `trackingAllowed` to `_googlesitekitBaseData`.
    * Based on the current `$hook_suffix` global, set it to `true` only for the admin screens outlined in the ACs, otherwise to `false`.
* In `assets/js/util/tracking/index.js`:
    * Check for the value of `trackingAllowed`, and only make the initial `toggleTracking( isTrackingEnabled() )` call if that is the case.

## QA Brief

* 

## Changelog entry

* Only load Site Kit-specific Analytics script on Site Kit admin screens.

**Comment by aaemnnosttv** [comment]
@felixarntz what if `tracking` was its own asset that we only enqueued in `Screen::enqueue_assets`?

**Comment by felixarntz** [comment]
@aaemnnosttv That has been in the back of my head for quite a while, and we should do it at some point, but not for now. This would also bring up other issues, like e.g. the tracking should still work on the plugin activation banner. If we don't enqueue the script on the plugins screen, we'd have an issue there. If we just don't run the initial logic on pageload though, that'd be okay.

**Comment by aaemnnosttv** [comment]
> the tracking should still work on the plugin activation banner. If we don't enqueue the script on the plugins screen, we'd have an issue there.

That current AC here only mentions Site Kit owned screens 😄  
Is `plugins.php` the only exception to that rule?

**Comment by felixarntz** [comment]
Oh I think there's a misunderstanding here, we should indeed only set `trackingAllowed` to true for Site Kit screens, so that the snippet is inserted on pageload. However, my previous point was that we still need the overall tracking logic to be loaded in e.g. `plugins.php` so that, when the user opts in, the snippet is inserted. It just shouldn't be inserted on pageload.

If we move to a separate `googlesitekit-tracking` asset, we'd need to make sure it's loaded also in `plugins.php`, but we'd still need the differentiation that it shouldn't insert the script on pageload.

But either way, I think that's for a separate task in the future.

**Comment by cole10up** [comment]
**Tested**

Installed latest SK release candidate and activated Analytics module.

Checked tracking for the following pages: Dashboard, module, splash and settings.

Checked admin bar:

![image](https://user-images.githubusercontent.com/57115907/85001829-02eb0480-b109-11ea-96ac-96c5ad79525a.png)

Checked WP dashboard:

![image](https://user-images.githubusercontent.com/57115907/85001972-2e6def00-b109-11ea-8b9a-9a2718bd9dc1.png)

Passed QA ✅
