### ISSUE TITLE
After the oauth nothing happen

### ISSUE THREAD

**Issue by IshanFx** [google/site-kit-wp#165]
I completed the setup flow until the OAuth. After the oauth completed it redirect to the wordpress main page and nothing happend. the redirected page is like this "wp-admin/admin.php?page=custom-dashboard.php"

#4

**Comment by jamesozzie** [comment]
@IshanFx Thanks for reporting. There could be a number of reasons this is occuring, potentially a plugin conflict, Firewall rules or AdBlocker. Do you mind trying the following:

1. - Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. - Temporarily deactivate your other active WordPress plugins
3 - Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
4. - Install Site Kit in a new incognito window (so Chrome extensions don't interfere and caching inactive)

Let me know if the above works. Very important to check in an incognito window also, AdBlockers can also sometimes cause interference during setup.

**Comment by jamesozzie** [comment]
#117

**Comment by IshanFx** [comment]
I tried all, but no luck. The redirect URL doesn't contain the page which needs to redirect. Is it the right format?

**Comment by IshanFx** [comment]
<img width="1319" alt="Screen Shot 2019-07-11 at 3 28 23 PM" src="https://user-images.githubusercontent.com/8342587/61041791-92177480-a3f0-11e9-9c2f-6f1e605cf2d0.png">

It show this after the oauth complete

**Comment by jamesozzie** [comment]
@IshanFx Thats interesting, would you be able to share any console errors? 

And are you using https, with non https redirection in place? If so is this also reflected in your [site settings](https://i.imgur.com/MkFLF0E.png).

**Comment by IshanFx** [comment]
Thanks changing the http to https in setting solve the issue.

**Comment by jamesozzie** [comment]
Thanks for letting us know. I will close the issue now.

**Comment by fhfournier** [comment]
Having same issue and i'm using https
