### ISSUE TITLE
Adsense: links to Adsense account pages from module are blank

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1652]
## Bug Description

Initially reported in [this forum topic](https://wordpress.org/support/topic/adsense-code-and-site-kite/#post-12929520), links in the Adsense module lead to blank pages in the Adsense account: 

<img width="500" alt="Link in Adsense module" src="https://user-images.githubusercontent.com/8108643/84183174-5215a300-aa40-11ea-8018-ecbdebba987b.png">

![Adsense account blank page from Site Kit](https://user-images.githubusercontent.com/8108643/84186213-1204ef00-aa45-11ea-8143-c44da2878496.png)

Visiting the pages directly from the Adsense account in the browser renders:

![Adsense account page renders](https://user-images.githubusercontent.com/8108643/84185670-344a3d00-aa44-11ea-9e22-caec0a5670fc.png)

Note difference in the URL structure, for example:

**Visit from Site Kit**

https://www.google.com/adsense/new/u/emailaddress@gmail.com/pub-9003023971424122/sites/my-sites?source=site-kit

**Visit directly in browser**

https://www.google.com/adsense/new/u/0/pub-9003023971424122/sites/my-sites

May be related to the site in pending status (review/ approval/ non-approval) for an already approved Adsense account. 

## Steps to reproduce

1. Configure the Adsense module
2. Click on links in the module
3. Arrive on blank pages in the Adsense account

## Additional Context

 - PHP Version: 7.3.16
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.9.0
 - Device: MacBook Air
 

Support topic: https://wordpress.org/support/topic/adsense-code-and-site-kite/#post-12929520

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Links to the AdSense FE should use the `?authuser=EMAIL` query argument instead of the `/u/EMAIL` path segment.

## Implementation Brief

Merge #1789 as the steps in the AC have been added to it.

## QA Brief

1. Ensure that you're only logged into a single Google account. Before this fix, the AdSense service URLs will only work with multiple accounts logged in.
2. Configure the Adsense module
3. Click on links in the module
a. Without this fix, the URL should render pretty much a blank screen.
b. With this fix, the URL should render the expected AdSense service frontend.

## Changelog entry

* Fix bug where deep links to the AdSense service frontend could result in blank screens there for users with a single Google account logged in.

**Comment by felixarntz** [comment]
This has a similar problem like https://github.com/google/site-kit-wp/issues/1456#issuecomment-661999939: The `/u/{email}` approach only works if the user is actually logged into more than one Google account in the browser. I re-tested the same thing using `?authuser={email}`, and it worked, so let's switch to that.

**Comment by felixarntz** [comment]
Just assigned this to Sprint 29. If it involves more work than an hour (e.g. as part of #1456), let's reconsider and instead schedule for Sprint 30. @ryanwelcher Feel free to address in the #1456 PR if trivial enough - in that case, the IB here could just be to merge that PR.

**Comment by felixarntz** [comment]
IB ✅

**Comment by ernee** [comment]
Adding this other report from the forums: https://wordpress.org/support/topic/site-kit-adsense-blank-page/

Also noting that I still experience the same behavior in an incognito browser window.

**Comment by felixarntz** [comment]
@ernee It is expected right now that this fails in an incognito window. If you log into your browser with two different Google accounts though, it should work. (Obviously this is still a major bug, because most users only have a single Google account, and we're working on it.)

**Comment by felixarntz** [comment]
@cole10up You should be able to QA this as part of #1456 (please review the QA Brief here as well though).

**Comment by eugene-manuilov** [comment]
@tofumatt assigning this to you since you are QAing #1456.

**Comment by tofumatt** [comment]
QA ✅
