### ISSUE TITLE
Add support for `dashboard-details` screen to entity detection

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1653]
## Feature Description

We recently introduced selectors on `core/site` to get information about the "entity" associated with the current context. An entity is basically a URL annotated with relevant WordPress information, e.g. whether it is a post, a term, the blog archive, a date archive etc. At the moment, only entities of type `post` (a single post) and `home` (the blog archive) are supported (for context, #174 is about expanding that at some point).

One area which is not yet supported by the entity detection mechanism on the PHP side is the details view for a URL within `googlesitekit-dashboard`. This is what this issue aims to solve: If you're on a details view, the entity detection mechanism should support detecting `post` and `home` entities from that as well.

A secondary change that should be made here is that `home` should be renamed to `blog`, as that is a more appropriate representation. While WordPress calls this "home" (e.g. `is_home()` function), it may not be the actual home page.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When visiting `googlesitekit-dashboard` for a single URL (`permaLink` query parameter), `Context::get_reference_entity()` should support detecting that entity if it is a single post or the blog archive.
* Entities of type `home` should have their type changed to `blog`. Since this is not used anywhere yet, it's fine to just change.
* If the entity of type `blog` is the home page (i.e. there is no post associated with it), assume a title of `__( 'Home', 'google-site-kit' )`, similar to how WordPress labels it in e.g. its Menus UI.

## Implementation Brief

* Introduce method `Context::get_reference_entity_from_url( $url )`:
    * Replace the reference URL with the "local" `home_url()` to ensure local WP logic works with the URL (this is only relevant when the reference URL differs).
    * Use `url_to_postid` function (or WP.com equivalent where applicable).
        * If this doesn't return a result, check specifically whether the URL is for `get_option( 'page_for_posts' )`, since this particular case is not covered by `url_to_postid`.
    * If a post ID was found, return that post's entity object.
    * Otherwise, if the URL path is just empty or `/`, return the entity for type `blog` (see naming change, previously would have been `home`), via a new private `Context::create_entity_for_home_blog()`.
* In `Context::get_reference_entity()` and its `is_admin()` clause, check if we're on `page=googlesitekit-dashboard` with a `permaLink` query parameter. If so, call the new `Context::get_reference_entity_from_url( $url )` with the `permaLink` value.
    * Also modify the currently manual creation of the `blog` (formerly `home`) entity to use the new private method mentioned above.
* Update the `post-search` datapoint in `REST_Routes` to rely on `Context::get_reference_entity_from_url` since it right now pretty much has the same logic replicated. Then, make sure to check that the returned entity is actually for a post before returning it, since that endpoint should only return post objects.
    * By doing this, we're fixing a minor bug where this would currently not support the `get_option( 'page_for_posts' )` URL, due to the `url_to_postid` shortcoming mentioned above.
* Replace the reference to `global.googlesitekit.permaLink` in the PageSpeed Insights dashboard widget to use `getCurrentEntityURL` from `core/site` (see #1636).
* See #1657 for draft PR.

## QA Brief

* 

## Changelog entry

* Detect current URL and related data when on the Site Kit screen for single URL details.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
