### ISSUE TITLE
Improve error & notice readability by not splitting words

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1658]
## Bug Description

Consider modifications to the current `word-break: break-all` style applied to errors/notices in the admin dashboards, which results in split words.

![Untitled-4](https://user-images.githubusercontent.com/41326532/84195539-a9466280-aa96-11ea-8e8c-7562d27c72b2.jpg)
![img](https://user-images.githubusercontent.com/41326532/84195542-aa778f80-aa96-11ea-9423-9a9986a43bb2.gif)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This was already changed to `break-word` in #1990. See https://github.com/google/site-kit-wp/pull/1990/files#diff-f157bf19f656b132dc081eb5063ffabd0103e4a328526892e9b747fb00f70c23

Closing as already fixed 😄
