### ISSUE TITLE
Define REST routes in their own dedicated areas  

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#166]
Instead of having all REST routes in the REST_Routes class, that class should provide a filter, and the routes should be defined in more applicable areas, via that filter.

Most current routes would move to one of the following classes:
- Authentication/Authentication
- Modules/Modules

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* API routes should be moved out of `REST_Routes`:
    * `core/site/data/reset` --> `Util\Reset`
    * `core/user/data/authentication` --> `Authentication\Authentication`
    * `core/user/data/disconnect` --> `Authentication\Authentication`
    * `modules` --> `Modules\Modules`
    * `modules/(?P<slug>[a-z\-]+)` --> `Modules\Modules`
    * `modules/(?P<slug>[a-z\-]+)/data/(?P<datapoint>[a-z\-]+)` --> `Modules\Modules`
    * `modules/(?P<slug>[a-z\-]+)/notifications` --> `Modules\Modules`
* The following routes should remain in `REST_Routes`:
    * `data`
        * because it is not specific to any area and theoretically should be able to access any `{type}/{identifier}/data/{datapoint}` route to resolve a batch request
        * because we potentially will drop support for batch requests in the future
    * `core/search/data/post-search`
        * because it should doesn't fit anywhere
        * because we should at some point remove it and instead rely on core's `wp/v1/posts` with some tweaks before making the request

## Implementation Brief

* In `REST_Routes::get_routes()`:
    * Remove all `REST_Route` objects from the array, except the ones that should remain (via ACs).
    * Run them through a new filter `googlesitekit_rest_routes`.
* For every route that should be moved (via ACs):
    * Add a private/protected method to the class which is supposed to filter `googlesitekit_rest_routes`, and amend the filter value so that it includes the route.
        * Update eventual `$this->...` references to still work correctly.
        * The method should be called in a closure attached to the `googlesitekit_rest_routes` filter in the `register()` method.
    * If there is no `register()` method on the class, add one, and call it in `Plugin` or wherever applicable.
    * In the `register()` method, hook in the new filter method added to `googlesitekit_rest_routes`.

## Changelog entry

* Move REST route definitions into more applicable classes that handle the respective functionality.

**Comment by aaemnnosttv** [comment]
Looks great @felixarntz - just one question.

> For every route that should be moved... Add a method to the class which is supposed to filter `googlesitekit_rest_routes`, and amend the filter value so that it includes the route.

Do you mean the class should get a new method like `get_routes()` but the method is called from `::register()` where the `googlesitekit_rest_routes` filter is added or that each class should define all the routes in `::register()`?

**Comment by felixarntz** [comment]
@aaemnnosttv 
> Do you mean the class should get a new method like `get_routes()` but the method is called from `::register()` where the `googlesitekit_rest_routes` filter is added or that each class should define all the routes in `::register()`?

The first. There would be a `get_routes()` or similar (private/protected), and it would be called by a closure in `register()` that is attached to the `googlesitekit_rest_routes` filter.

**Comment by aaemnnosttv** [comment]
Thanks @felixarntz. That's what I thought, I just wanted to clarify.

Also, existing tests for `REST_Routes` that are moved should be moved to their respective test cases for the classes where they will now be registered.

IB ✅

**Comment by tofumatt** [comment]
QA ✅

All the code changes here look good, and the plugin still works as expected. 👍
