### ISSUE TITLE
PageSpeed Insights Link on Dashboard Not HTTPS

### ISSUE THREAD

**Issue by roadsunknown** [google/site-kit-wp#1660]
On the Site Kit Dashboard, under the Speed section, there is an external link to "PageSpeed Insights". If the site is served over HTTPS, as configured in WordPress, this link does not use the HTTPS prefaced link but rather uses an HTTP link. This results in PageSpeed Insights returning a message: "Requested URL redirected to: https://domain.com". This is an unnecessary as the link from Site Kit to PageSpeed Insights should be HTTPS if the site is configured as such.

## Steps to reproduce

1. Confirm Site Address (URL) in WordPress is prefaced with https://
2. Go to "Site Kit" > "Dashboard"
3. Scroll down to "Speed" section
4. Click "PageSpeed Insights"
5. See message "Requested URL redirected to: https://domain.com"

## Screenshots

![image](https://user-images.githubusercontent.com/371759/84230796-672b1a00-aab2-11ea-94d6-84258f61663f.png)
![image](https://user-images.githubusercontent.com/371759/84230595-f2f07680-aab1-11ea-97a9-97cf8af91279.png)
![image](https://user-images.githubusercontent.com/371759/84230946-b7a27780-aab2-11ea-9a5a-f3feb1cf379f.png)
![image](https://user-images.githubusercontent.com/371759/84230693-34812180-aab2-11ea-886b-f0802af4e5d7.png)

## Additional Context

 - PHP Version: 7.3
 - OS: Windows 10
 - Browser: Chrome 83
 - Plugin Version: 1.9.0
 - Device: Dell XPS 13 7390

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@roadsunknown Thanks for opening this GitHub issue. 

Reproducible in support with a fully https site (and both URLs in general settings including https). PageSpeed Insights module will pass the non secure URL to PageSpeed Insights web interface. 

Worth noting that even with the module passing the insecure URL as long as there is redirection in place the https site will be used for metrics. 

![Untitled-7](https://user-images.githubusercontent.com/41326532/84250445-f876ac80-ab03-11ea-8a95-a6b94510f49b.jpg)

**Comment by cole10up** [comment]
**Tested:**

Tested on https://hellogoodbye.today

Checked and was unable to reproduce this one.

![image](https://user-images.githubusercontent.com/57115907/88143096-8043e200-cbab-11ea-9b78-0ff96f538b66.png)

@jamesozzie - Can you give this a try with the latest build?

**Comment by jamesozzie** [comment]
@cole10up All looks good to me. 

![image](https://user-images.githubusercontent.com/41326532/88183610-98f2dd00-cc29-11ea-8d1f-d4ff2a0b8dc0.png)

@roadsunknown Can you check from your side?

**Comment by roadsunknown** [comment]
@jamesozzie Issue was fixed in of the last builds. All good on my side.
