### ISSUE TITLE
JetPack Slideshow Conflicts with Site Kit Admin Bar

### ISSUE THREAD

**Issue by LuckynaSan** [google/site-kit-wp#1668]
## Bug Description
Carousal slideshow in <a href="https://jetpack.com/support/jetpack-blocks/slideshow-block/" rel="noopener" target="_blank">JetPack</a>  does not display on the site when Site Kit adds its admin bar integration.  

Related topics: 
https://wordpress.org/support/topic/slide-show-disappearing/
https://wordpress.org/support/topic/site-kit-conflicts-with-jetpack-blocks/

## Steps to reproduce
1. Install and activate Jetpack and Site Kit (connect to Analytics service). 
2. Go to site page, slideshow section is blank and received a <a href="https://jmp.sh/Njqw9eq" rel="noopener" target="_blank">console error</a>.

3. Carousal slideshow displays on site when Site Kit admin integration bar is disabled. 
Appearance > Theme Editor > Theme Functions > Insert new code: 
add_filter( 'googlesitekit_show_admin_bar_menu', '__return_false', 1000 );

## Videos
When Jetpack installed alone then the <a href="https://recordit.co/S9xH5fKg46" rel="noopener" target="_blank">slideshow works</a>.

When JetPack installed and Site Kit (search console, analytics) installed/activated, <a href="https://recordit.co/I4nvHKsHTQ" rel="noopener" target="_blank">slideshow does not work</a>.

When Site Kit admin bar was disabled, then the <a href="https://recordit.co/Hc6qezy6pQ" rel="noopener" target="_blank">slideshow works</a>.

## Additional Context
- The issue only occurs while logged into WordPress.

 - PHP Version: 7.2.31 
 - OS: [e.g. iOS] MacOS
 - Browser Chrome
 - Plugin Version 1.9.0
 - Device: MacBook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Jetpack slideshow should be displayed as expected without a console error when the Site Kit admin bar menu is active. This should be tested in both the frontend and the editor.

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ryanwelcher** [comment]
@LuckynaSan I am having difficulty reproducing this with Site Kit v1.10. Can you confirm that this is still an issue?

**Comment by LuckynaSan** [comment]
@ryanwelcher I tested that the slideshow carousal behaved as expected with Jetpack and Site Kit v1.10. installed. I am going to check with the user if this version is working correctly on their end as well and will follow up on this GitHub ticket. Thanks!

**Comment by LuckynaSan** [comment]
@ryanwelcher The user confirmed this is no longer an issue. I will close this ticket. Thank you!
