### ISSUE TITLE
Add dashboard widget access permissions for all WordPress users

### ISSUE THREAD

**Issue by mikelking** [google/site-kit-wp#1669]
#### Problem: 
Currently the various GSK data widgets only appear on the dashboard of the user who connected the site to the respective Google product. 

#### Recommendation:
It would be extremely beneficial to have the ability as the site admin to allow others to see and possibly interact with these dashboard without having to setup more accounts in the actual Google product. As an operator of large WordPress installations with many freelancers user account management is kind of a full time job already. 

#### Example:
For example take a look are BeeHive Pro (formerly google analytics plus from WPMUDev). I can connect this to GA and then setup permissions in WordPress defining who can see and interact with the Analytics dashboard. Editors and Freelancers are able to see how the content they are producing is performing without having to be super analytics aware or even have GA access. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ngxson** [comment]
I reported the same issue one month ago, but they completely ignored it: https://github.com/google/site-kit-wp/issues/1568

**Comment by jamesozzie** [comment]
@mikelking Thanks for your suggestion and providing additional context. As we already have an open GitHub issue (#852) in relation to access for non administrators I'll close this as a duplicate. Feel free to add any suggestions or additions to that issue. 

@ngxson Apologies for the lack of response. I can see you've added you comments to the original issue, many thanks for your input.
