### ISSUE TITLE
Google Analytics snippet not inserted on multisite install

### ISSUE THREAD

**Issue by drawcard** [google/site-kit-wp#1673]
## Bug Description

I have a multisite with two sub-sites, and I have Google Site Kit running on them (Version 1.9.0). The plugin is not network activated, but is instead activated on each sub-site via their plugin manager.

The option to place the GA snippet is checked on the settings page on each sub-site, however the snippet is not being injected on the sub-sites source code. 

I also tested this with an incognito browser to ensure no extensions or logged-in accounts were blocking the script.

## Screenshots

Options are active
![image](https://user-images.githubusercontent.com/1435638/84611425-f7c38900-aefc-11ea-8213-d9eae80331f5.png)

Searching source code for snippet placement, with 0 results returned:
![image](https://user-images.githubusercontent.com/1435638/84611604-8506dd80-aefd-11ea-8e23-7fa70825d533.png)

![image](https://user-images.githubusercontent.com/1435638/84611621-8e904580-aefd-11ea-91cc-736191c5976c.png)

## Additional Context

Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.3.23 |  
PHP Version: | 7.1.33 |  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@drawcard thanks for reaching out! We provide support via the [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit/). Could you open[ a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there so we can troubleshoot further? Thanks so much.
