### ISSUE TITLE
Integrate WP CLI scripts into regular PHP class file structure

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1677]
## Feature Description

Currently our WP CLI commands are found in the `bin` directory, which is a bit odd (see https://github.com/google/site-kit-wp/issues/925#issuecomment-644010561). Let's move them into our regular class infrastructure within the `includes` directory.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All WP CLI commands should be found within the `includes` directory in a way that they will be autoloaded as necessary.

## Implementation Brief

* Move `bin/authentication-cli.php` to `includes/Core/CLI/Authentication_CLI_Command.php`.
* Move `bin/reset-cli.php` to `includes/Core/CLI/Reset_CLI_Command.php`.
* Adjust namespace for both files to be `Google\Site_Kit\Core\CLI`.
* Turn the reset command into a class (for auto-loading), with an `__invoke` method.
* Introduce new class `Google\Site_Kit\Core\CLI\CLI_Commands` that has a constructor that accepts a `Context` instance, as well as `register` method. The calls to `WP_CLI::add_command` that are currently right within the WP CLI command class files should be moved out of there into the new `CLI_Commands::register` method.
* Remove direct loading of the CLI files from `includes/loader.php` and instead add the `defined( 'WP_CLI' ) && WP_CLI` conditional to `Plugin::register`, and in there instantiate the new `CLI_Commands` class with the `Context` instance and call its `register` method.
* Modify both existing command classes so that they get a constructor with the `Context` instance. In `CLI_Commands::register`, these classes can simply be instantiated and then the instances can be passed to the `WP_CLI::add_command` calls (see https://make.wordpress.org/cli/handbook/guides/commands-cookbook/#required-registration-arguments).

## QA Brief

* 

## Changelog entry

* Rename `wp google-site-kit auth revoke` to `wp google-site-kit auth disconnect` and adjust internal CLI commands infrastructure.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ShahAaron** [comment]
Tested

Pulled branch and setup locally. Insured site functions as expected.

- `bin/authentication-cli.php` to `includes/Core/CLI/Authentication_CLI_Command.php` - confirmed
- `bin/reset-cli.php` to `includes/Core/CLI/Reset_CLI_Command.php` - confirmed
