### ISSUE TITLE
Add grid logic and additional styles for widgets and widget areas

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1678]
## Feature Description

While #1300 includes minimal styling for widget areas and widgets, there's quite a bit more that needs to be done, specifically to make the dynamic grid work as intended.

Every widget is registered with a width of `full`, `half` or `quarter`, and they should be organized within their widget area in a grid that accounts for this registration argument, while also optimizing for the available space as much as possible.

The other registration argument that matters for styling is each widget area's `style`.

For a better idea, this issue is about ensuring these two types of widget areas render correctly, similar to how they do today (while today all of it is hard-coded):

`composite` style widget area example (all widgets are within one box):
![Screenshot 2020-06-15 at 17 49 32](https://user-images.githubusercontent.com/3531426/84719731-f01dd780-af30-11ea-9492-e91a1110afa0.png)

`boxes` style widget area example (every widget is its own box):
![Screenshot 2020-06-15 at 17 49 54](https://user-images.githubusercontent.com/3531426/84719738-f4e28b80-af30-11ea-996a-0bb60848f878.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Overall widget area grid and styling
* The widget area should render as a grid (`mdc-layout-grid`).
* The widget area header should render as a grid cell that spans the full width (12 columns).
* If the widget area is of style `boxes`, each widget (per the `Widget` component) should receive white background and box-shadow as currently (e.g. Popularity widget area), as well as the current 24px padding (similar to `mdc-layout-grid` class). Every widget should appear as a cell within the widget area's main grid (see first bullet point).
* If the widget area is of style `composite`, the widgets wrapper element should receive white background and box-shadow as currently (e.g. Search Funnel widget area). In this case the widgets wrapper itself should render as yet another grid (`mdc-layout-grid`), giving it the same 24px padding from that, but also setting things up for inner widgets to appears as cells within that grid.

### Widget size and alignment
For context, on desktop the grid has 12 columns, on tablet it has 8 columns, on mobile it has 4 columns.

* Widget output should be inspected first: If a widget returns `null`, it should be skipped.
* Regardless of the widget area style, widgets should receive grid cell classes (via `WidgetRenderer` component) based on their registered `width` and how much space there is available):
    * For `full` width, the widget should span the full width on all viewports.
    * For `half` width, the widget should span half width on desktop and full width on tablet and smaller (since essentially the tablet is the half width).
    * For `quarter` width, the widget should span quarter width on desktop, half width on tablet, and full width on mobile.
    * By definition, this means that if the next widget is too wide for the remaining available horizontal space, it will move to the next row. This is perfectly fine, however we should add some "clever" logic as follows to reduce wasted space:
        * If there are only three `quarter` widgets in a row, they should instead each span a third on desktop.
        * If there is only one `half` and one `quarter` widget in a row (order is irrelevant), they should instead span two thirds and one third respectively on desktop.
        * In other words, content that is 3/4 wide should be stretched to cover 1/1. This should not apply to anything else though, if the content is e.g. 1/2, it shouldn't stretch because we can consider this increase in size too big for whatever the widget is displaying.

### Misc fixes

The following widget areas should actually be registered with "composite" style instead of "boxes" (as they do today in our current UI):
* `dashboardAllTraffic`
* `dashboardSearchFunnel`
* `pageDashboardSearchFunnel`
* `pageDashboardAllTraffic`

### Overall widget area grid and styling
* Make `googlesitekit-widget-area` the outer grid via `mdc-layout-grid` (done as part of #1300).
* Wrap `googlesitekit-widget-area-header` in an `mdc-layout-grid__inner` and give it `mdc-layout-grid__cell mdc-layout-grid__cell--span-12` (done as part of #1300).
* Within `googlesitekit-widget-area-widgets` include an `mdc-layout-grid__inner` (done as part of #1300).
* Add background color and box-shadow to `.googlesitekit-widget-area-composite .googlesitekit-widget-area-widgets` and `.googlesitekit-widget-area-boxes .googlesitekit-widget` (done as part of #1300).
* Add the exact style of `mdc-layout-grid` to `.googlesitekit-widget-area-boxes .googlesitekit-widget` (for composite, this style is actually applied via the inner grid itself, see below).
* If widget area style is `boxes`:
    * Render every widget as a grid cell in the outer grid (see details on span classes below).
* If widget area style is `composite`:
    * Include within `.googlesitekit-widget-area-widgets .mdc-layout-grid__inner`:
        * `mdc-layout-grid__cell mdc-layout-grid__cell--span-12`, to fill full width for inner grid below.
        * `mdc-layout-grid` to create inner grid that will automatically add the necessary padding.
        * `mdc-layout-grid__inner` to _actually_ create the inner grid in combination with its wrapping `mdc-layout-grid` element.
    * Render every widget as a grid cell in the inner grid (see details on span classes below).

### Widget size and alignment

* Add `getGridCellClasses( widgets )` utility function that receives sorted array of widgets in widget area (via `getWidgets` selector) in `assets/js/googlesitekit/widgets/util/get-grid-cell-classes.js`:
    * The function should return an array of strings that contains the class names to use. The array index is the same index of the respective widget (i.e. the length of the array is the number of widgets to render in the widget area).
    * If the `widget` returns `null`, skip the layout calculation for that widget, and assume it takes zero space.
    * Every string should include `mdc-layout-grid__cell`.
    * If widget width is `full`, the string should include `mdc-layout-grid__cell--span-12`.
    * If widget width is `half`, the string should include `mdc-layout-grid__cell--span-6-desktop mdc-layout-grid__cell--span-8-tablet`. On mobile, it will automatically not be wider than the maximum.
    * If widget width is `quarter`, the string should include `mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-4-tablet`. On mobile, it will automatically not be wider than the maximum.
    * In order to determine the grid cell classes to use for `half` and `quarter` widgets on desktop, increase a `counter` while iterating over the widgets, adding 12 if `full`, 6 if `half`, or 3 if `quarter`. If the value becomes equal to 12, set it to 0 afterwards to restart the count (next widget will be in a new row). If the value becomes greater than 12:
        * Subtract the number just added again.
        * If the number is 9, start an inner loop iterating backwards over the part of the class names array already generated (a while loop with exit condition `counter === 0`), essentially "correcting" the default desktop widths of the previous widgets:
            * If the string contains `mdc-layout-grid__cell--span-3-desktop`, replace it with `mdc-layout-grid__cell--span-4-desktop` (1/3) and subtract 3 from `counter`.
            * If the string contains `mdc-layout-grid__cell--span-6-desktop`, replace it with `mdc-layout-grid__cell--span-8-desktop` (2/3) and subtract 6 from `counter`.
            * Exit condition of the while loop will be reached after either 2 or 3 array entries.
        * Set the counter to the current widget's respective desktop width (12, 6, or 3). Essentially, this is the first widget in the next row.
        * If at the very end the final `counter` value is 9, run the same backwards loop one last time.
* In `WidgetRenderer`, call `getGridCellClasses` with the widgets obtained from the datastore. Then, iterating through the widgets, add a `div` around every widget's component with the classes string returned from the utility function for this widget (i.e. at the respective array index). (Don't wrap `null` widgets, though they won't have any classNames associated, see above.)

### Misc fixes

* Modify widget area registration arguments per the ACs.

## QA Brief

* Run a development build.
* The PageSpeed Insights widget in the **new** widget area should now display correctly, for both the dashboard and the single URL dashboard details views.
* To test the grid logic and resizing, temporarily add the code snippet in https://github.com/google/site-kit-wp/pull/1816#issuecomment-663794555 to `assets/js/modules/pagespeed-insights/index.js`, below the existing registration call for the PSI widget, then do a development build with this. (It will add some dummy widgets below the PSI widget.)
    * On mobile, all widgets should fill the entire width.
    * On tablet, "quarter" widgets should fill half the width while "half" and "full" (the PSI widget is a "full" widget) widgets should fill the full width.
    * On desktop, "quarter" widgets should fill a quarter of the width, "half" widgets should fill half the width, "full" widgets should fill the full width, **except**:
        * If a row has widgets that, in combination would only end up filling three quarters of the width (e.g. 3 "quarter" widgets, or one "half" and one "quarter" widget), each widget should be expanded so that the full row width is covered - in other words, a "half" widget would change to span two thirds, a "quarter" widget would change to span one third.
* The Search Funnel and All Traffic widget areas should display in "composite" style, i.e. they should in its entirety render as a white box. (Normally, each widget itself would be a white box, but for "composite" style it's the entire widget area.)
    * Note that widget areas right now always display even if they contain no widgets, which is currently expected. It also allows to test the above regardless of whether there are widgets.

## Changelog entry

* Implement logic and styling for managing widget areas and widgets in a dynamic grid, respective registered widget widths and aligning them properly.

**Comment by tofumatt** [comment]
Looks good. It's a bit difficult to follow the logic of what the grid code should be doing from the IB, but I think that's because it's harder to explain this sort of thing in words than code. The general approach makes sense though 👍 

I'm only confused by this part, which I suspect is a typo:

> If the string contains `mdc-layout-grid__cell--span-3-desktop`, replace it with `mdc-layout-grid__cell--span-3-desktop` (1/3) and subtract 3 from counter.

Those classes are the same, so I'm a bit confused as to what we're replacing here 🙂 

From the ACs, the aim here is to increase the size of 1/4 widgets to 1/3 widgets, and 1/2 widgets to 2/3 widgets in order to reduce the amount of "empty" space we have (mainly on desktop), correct? If that's the case I'm guessing we just need to change the above to read:

> If the string contains `mdc-layout-grid__cell--span-3-desktop`, replace it with `mdc-layout-grid__cell--span-4-desktop` (1/3) and subtract 3 from counter.

The implementation of how we actually achieve that, I think, we can be flexible on and do what makes sense in the utility function, though the approach outlined here seems good.

I think that's the only change that needs to be made, so if that sounds good then IB ✅ after that one change is made and we can move this into the backlog. (If anything else needs changing let me know and I'll have another review 🙂 )

**Comment by felixarntz** [comment]
@tofumatt Oh that was indeed just a copy paste oversight, your assumption of what it should mean is right. I've updated it accordingly, moving to execution backlog.

**Comment by felixarntz** [comment]
@tofumatt IB updates sound good ✅

**Comment by cole10up** [comment]
**Tested**

Built latest dev build, activated site kit and page speed insights.

Notice:
![image](https://user-images.githubusercontent.com/57115907/88886045-890d6700-d1ee-11ea-88be-f2a2afc94f8b.png)

Confirmed toggles:
![image](https://user-images.githubusercontent.com/57115907/88886134-af330700-d1ee-11ea-8d3f-3883902bf1de.png)
![image](https://user-images.githubusercontent.com/57115907/88886160-b78b4200-d1ee-11ea-8c3f-5f23792b401a.png)

Confirmed removal of PageSpeed insights:
![image](https://user-images.githubusercontent.com/57115907/88886199-c70a8b00-d1ee-11ea-9ca5-76246ff3dcb4.png)

Noticed clicking the jump to bottom of the page feature is still tied to the old module
![image](https://user-images.githubusercontent.com/57115907/88886249-e43f5980-d1ee-11ea-84ce-867543bf3aad.png)

Checked mobile view:
![image](https://user-images.githubusercontent.com/57115907/88886718-f372d700-d1ef-11ea-9d7d-c494a5d378cd.png)

Different size windows:
![image](https://user-images.githubusercontent.com/57115907/88886793-14d3c300-d1f0-11ea-9dc0-63014b454561.png)
![image](https://user-images.githubusercontent.com/57115907/88886826-20bf8500-d1f0-11ea-98b7-a8d8bff58be9.png)



**Confirmed latest release candidate doesn't show this layout**
![image](https://user-images.githubusercontent.com/57115907/88886305-0638dc00-d1ef-11ea-916f-61c4b854a56f.png)

Passed QA ✅
