### ISSUE TITLE
Analytics user and user percent change should match Analytics dashboard

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1681]
## Bug Description

When viewing the Analytics data in Site Kit, the number shown for user change percent should match the number shown in the Google Analytics Dashboard for all reporting periods. Currently all numbers match **except** user change percent.

Previously discussed in https://github.com/google/site-kit-wp/issues/1280

## Steps to reproduce

1. Set up Analytics in Site Kit.
2. Compare the user change percentage change data shown in Analytics to the data shown in Site Kit

### Expected result
The numbers should match.

### Actual result
The numbers are different.

## Screenshots

<img width="1464" alt="7 days" src="https://user-images.githubusercontent.com/2676022/84824350-02554f80-afdd-11ea-8a30-c2987a538618.png">

![28-days](https://user-images.githubusercontent.com/2676022/84824357-05e8d680-afdd-11ea-95af-ce68aff3399e.png)

![90days](https://user-images.githubusercontent.com/2676022/84824363-08e3c700-afdd-11ea-86a2-e9fa04fafe37.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user percentage change in Site Kit should match the user percentage change displayed in the Analytics frontend.
    * This is most likely currently wrong for the same reason #1202 was implemented (see PR #1277) - that issue only resolved the problem for the overall number, but not the percentage. We can probably use the same request from there to get the percentage, by modifying https://github.com/google/site-kit-wp/pull/1277/files#diff-a75b3a0da6c74c4dc70fbf476e42f23cR437 to include the date range comparison.
    * This should be tested for any date range other than 90 days, which has its own separate problem (#1280).
* It should calculate the percentage change from the same API response that is used for the absolute users number.
* This should be fixed for:
    * Site Kit dashboard
    * Site Kit Analytics page
    * WP dashboard widget
    * `traffic-increase` publisher win
    * Admin-bar total users

## Implementation Brief

* In `assets/js/components/publisher-wins/index.js` swap the data point used:
   * Change `overviewReportDataDefaults` to `userReportDataDefaults` for the data callback with identifier `traffic-increase`

* In `assets/js/components/publisher-wins/traffic-increase.js` change user/percent calculations. Remove use of `calculateOverviewData` and instead extract the data from the new API call:

```js
const totalUsers = get( reports, '[0].data.totals[0].values[0]' );
const previousTotalUsers = get( reports, '[0].data.totals[1].values[0]' );
const totalUsersChange = Number( changeToPercent( previousTotalUsers, totalUsers ) );
```

Note: `totalUsersChange` is converted to a number for the comparison on the following line - the notice is only shown if the increase is between 10 and 100%.

* In `assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetOverview.js` and `assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopLevel.js` add `previousTotalUsers` to state, assigning it in the `toState`` callback (in the withData setup):

`const previousTotalUsers = get( data, '[0].data.totals[1].values[0]' );`

   * Calculate totalUsersChange directly instead of using the number provided by `calculateOverviewData`:

`const totalUsersChange = changeToPercent( previousTotalUsers, directTotalUsers );`

* In `assets/js/modules/analytics/components/adminbar/AnalyticsAdminbarWidgetOverview.js:
   * Change `overviewReportDataDefaults` to `userReportDataDefaults`
   * Switch user data to use the new data point, as above. 

* For `assets/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetOverview.js`:

   * Add state setup, putting overview, directTotalUsers and previousTotalUsers in state.
   * Change withData setup, adding a new datapoint with the `userReportDataDefaults` config.
   * For each datapoint, use `toState` to extract the correct data into state:

overviewReportDataDefaults:
```js
if ( ! state.overview ) {
	return {
		overview: calculateOverviewData( data ),
	};
}
```

userReportDataDefaults:
```js
if ( ! state.directTotalUsers ) {
	const directTotalUsers = get( data, '[0].data.totals[0].values[0]' );
	const previousTotalUsers = get( data, '[0].data.totals[1].values[0]' );
	return {
		directTotalUsers,
		previousTotalUsers,
	};
}
```
   * Change display conditionals:
`{ ! data.length` -> `{ 0 === directTotalUsers` 

   * Add the boilerplace for state based data components (`componentDidUpdate` and `componentDidMount` which call `processCallbackData`)

* In `assets/js/modules/analytics/util/index.js` ensure the user report is multi date range:

```js
export const userReportDataDefaults = {
	multiDateRange: 1,
	metrics: [
```

* In `assets/js/modules/analytics/util/calculateOverviewData.js` remove the calculations for `totalUsers` and `totalUsersChange`. Verify these are no longer used anywhere in the codebase.

## QA Brief

* Check User/Visitor change percentage in the following locations:
  * Site Kit Dashboard 
  * Site Kit Analytics page
  * WP Dashboard 
  * Admin-bar dropdown
  * Traffic increase publisher win (I tested this using a code change, if you need help reproducing I can create a test build that forces this to show).

* In all cases percent change should match what is shown in Analytics. 
* When a dropdown is present to select a day range, all ranges except 90 days (7, 14, 28) should be checked and match Analytics.

## Changelog entry

* Fix bug where the displayed Analytics user count percentage change was slightly off from Analytics service frontend.

**Comment by adamsilverstein** [comment]
I have a ticket opened with the Analytics team to see if we can determine how this datapoint is calculated. I will report back here with findings and add an IB once I have more details.

**Comment by adamsilverstein** [comment]
Update: I have asked again for help on the (internal) ticket, so far there has not been a response, only that they are looking at it... so I am not able to create the IB yet.

I will keep my eyes on the ticket for now.

**Comment by felixarntz** [comment]
@adamsilverstein Any updates here? Even if this percentage is affected by the #1280 bug, that would only be for the 90 day span. Shouldn't we be able to get the percentage in a similar way to how we got the correct "Users" number before (#1277). Maybe we'd just need to alter https://github.com/google/site-kit-wp/blob/1.12.0/assets/js/modules/analytics/util/index.js#L397 so that it includes the `multiDateRange: 1` argument? This should query that number for both periods so we could get the comparison percentage change.

**Comment by adamsilverstein** [comment]
>  Even if this percentage is affected by the #1280 bug, that would only be for the 90 day span. 

Right - this number is currently off for any date range.

> Shouldn't we be able to get the percentage in a similar way to how we got the correct "Users" number before (#1277).

I will take another look... I was hoping the same thing -  unfortunately I tried that without success. I will try again to make sure and add some screenshots here to add a record of what I see. I also tried several ways to have the API aggregate the data without any luck in matching the percent change I see in the analytics dashboard.

**Comment by felixarntz** [comment]
@adamsilverstein Per our testing earlier, let's for now change our implementation to rely on the same `ga:users` query for the percentage calculation. We can add `multiDateRange: 1` to the query, and then have to adjust the calculation (the response format will be slightly different too since it will include additional values). While this value seems to still be slightly off (especially for higher numbers), it's more precise than what we currently have as it relies on the same query like the absolute number, which makes sense.

This should be used for:
* Site Kit dashboard Unique Visitors percentage (absolute number is already using it)
* Site Kit Analytics overview Users percentage (absolute number is already using it)
* WP dashboard Unique Visitors percentage _and_ absolute number (absolute number here was missed in #1277 I think)
* The `traffic-increase` publisher win percentage _and_ absolute number (that one we missed originally too)

Separately, let's keep following up with Analytics folks to see why we're still not getting the exact same results in some instances.

**Comment by adamsilverstein** [comment]
@felixarntz thanks for the discussion and feedback.

I have discovered the underlying issue with our Analytics percent change numbers being off... Turns out the past period used for comparison is always aligned on the same *days of the week* as the current period

So if the current period starts on a monday, the past period also starts on a monday

This makes some sense, especially when you look at a day by day comparison, because traffic patters will vary by day of the week, eg weekends might be busier times. By aligning on days of the week, this difference is reduced.

For 7 or 28 day reports, this works out that the previous period ends exactly before the current period - because 7 and 28 are whole peek periods (number of days is evenly divisible by 7).

When we try 90 days (or 30 in the Analytics UI), the previous period is "offset" to match the start day of the week; depending on the alignment this could mean moving the period forward, or backward by up to 3 days

I will add an IB for this change as well as the other user data changes you specified.

**Comment by felixarntz** [comment]
@adamsilverstein There might be some confusion here, the problem regarding percentages for the 90 day period is handled in #1280. While there's some overlap between these two, this one here is about fixing the percentage for "Users" specifically, which is also wrong for other date ranges.

**Comment by adamsilverstein** [comment]
Right, that last comment belongs on the other ticket, I will copy it there. I will work on the user issue here and the 90-day date issue there.

**Comment by adamsilverstein** [comment]
@felixarntz Added IB. Looking through the code, I discovered one other component that displays the User/visitor data: the adminbar dropdown. I added this to the AC and IB.

**Comment by adamsilverstein** [comment]
The Analytics team has confirmed a potential bug for the homepage _user change percentage_. In short, users are complicated and the number they show on their homepage is incorrect. The number shown in Audience overview (which matches Site Kit) is more accurate. They will work to resolve this issue.

**Comment by felixarntz** [comment]
IB ✅

**Comment by adamsilverstein** [comment]
> The Analytics team has confirmed a potential bug for the homepage user change percentage. 

Still investigating here: one additional detail is that some properties show this discrepancy while others do not. The discrepancy I see with my test account data may be an outlier, and the fixes we are making here (to always use the direct query) may fix this completely for most users.

**Comment by aaemnnosttv** [comment]
Added an estimate here retroactively mostly to cover CR and QA - @adamsilverstein feel free to increase this to account for any additional efforts on your end.

**Comment by adamsilverstein** [comment]
This is ready for additional review.

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest RC, setup SK and activated analytics

Checked user percentage:
7 Days:
![image](https://user-images.githubusercontent.com/57115907/90112672-298e7b80-dd05-11ea-842f-b3c5f7affe48.png)

GA:
![image](https://user-images.githubusercontent.com/57115907/90112817-5773c000-dd05-11ea-8002-902b210b9bc6.png)

Discrepancy is due to my initial test

28 days:
![image](https://user-images.githubusercontent.com/57115907/90112949-825e1400-dd05-11ea-9845-1ad7eb4201ba.png)

GA:
![image](https://user-images.githubusercontent.com/57115907/90113003-930e8a00-dd05-11ea-890d-3500bf32fda7.png)

Dashboard:
![image](https://user-images.githubusercontent.com/57115907/90113079-ad486800-dd05-11ea-9290-bcce5d68e35d.png)

Passed QA ✅
