### ISSUE TITLE
Plugin setup stuck in a loop (without any error notice)

### ISSUE THREAD

**Issue by brandomeniconi** [google/site-kit-wp#1682]
## Bug Description
SiteKit can't complete setup because it's continuously redirects to the splash page after the OAuth2 flow, without any error or warning (see gif). 

## Steps to reproduce

1. Go to WP-Admin > SiteKit > Dashboard
2. Click on "Start Setup"
3. Complete the OAuth2 connection flow 
4. The sitekit's website redirects to the WP site to confirm the setup, but WP redirects back to the sitekit's splash page.

## Screenshots

![sitekit_loop](https://user-images.githubusercontent.com/393114/84866021-704f5480-b079-11ea-8ec5-4120bf98c8c4.gif)

## Additional Context

 - PHP Version: 7.3
 - OS: MS Windows 10
 - Browser: Chrome
 - Plugin Version: 1.9.0
 - Device: PC
 - Server: Google App Engine  
 - Multisite: yes (occurred in single sites too)

We used sitekit on different sites and in some of them it completed the setup correctly. The all are based on the same environment. I've tried changing Google Account, Incognito Mode, Resetting the plugin but nothing has worked so far.

I suppose that there is something that fails in the connection but the plugin gives no feedback about the error and simply redirects back to the Oauth flow. An error before the redirect could help a lot.

I can't debug on the live sites because I'm running WP on AppEngine and I have no shell access.

Thanks for the support.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@brandomeniconi Thanks for reporting and providing the additional context. Initial support requests can be submitted using the plugins [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/#new-post). 

When creating a post if you can share your [Site Health information](https://i.imgur.com/Rtkmsba.png) within the post we may be able to troubleshoot or determine the cause. You can use [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) to share privately if you prefer.
