### ISSUE TITLE
Default selected view can be empty if view doesn't exist

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1691]
## Bug Description

In #1404 we updated the logic in the Analytics setup and settings components to pre-select the default profile for a property if that property has a `defaultProfileId`.

This is a bit of an edge case, but if that profile is deleted, it will still be around for 30 days or so (GA refers to this as sending it to the "Trash Can"). While the deleted profile will not be returned by the API as a profile for the property, but the property will still references the deleted profile ID as its `defaultProfileId`. This causes the profile ID to be set to an ID that isn't a valid option in the list of choices, resulting in a blank selection.

## Steps to reproduce

1. In Google Analytics, go to Admin > Property Settings and select a Default View
1. Delete the view chosen as the default
1. In Site Kit, set up Analytics (or go to settings edit)
1. Select the account and property with the default view configured previously
1. See that the View is empty

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/85038468-48521500-b18f-11ea-9b7f-cecc1f635f5f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The default view for a property should only be selected if the view exists  
This should be fine as properties and profiles are all received before this selection happens

## Implementation Brief

* Update `selectProperty` selector to check that `profiles` array contains a profile with id that equals to `property.defaultProfileId` before calling `setProfileId` with a default value.
  * If such profile doesn't exist, skip setting the default value.

## QA Brief

* Follow the steps reproduce above and confirm that the View populates with "Set up a new View"

## Changelog entry

* Only select Analytics default view for the active property automatically if it still exists.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
