### ISSUE TITLE
E2E Redux debugging no longer working as expected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1694]
## Bug Description

Due to recent changes to how assets are enqueued in E2E, the current `e2e-utilities.js` asset is being loaded too late to be loaded in time for the Redux logging to be connected. This has to be loaded before the data stores are registered.

The solution is to simply split the `e2e-utilities.js` into separate assets to be enqueued separately as it is the `api-fetch-data` dependency which is needed for `_e2eApiFetch` which is causing the script to be loaded later than it needs to be.

## Steps to reproduce

1. Run `DEBUG_REDUX=1 npm run test:e2e`
1. Note absence of Redux action logging in console output

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/85119946-358d1e00-b22b-11ea-92b8-35eea6a7a02c.png)

**Expected Output**
![image](https://user-images.githubusercontent.com/1621608/85119863-142c3200-b22b-11ea-91a9-ee453a2fcb91.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Running E2E tests with `DEBUG_REDUX=1` should result in Redux actions logged in the console

## Implementation Brief

* Split `e2e-utilities.js` into separate `e2e-api-fetch` and `e2e-redux-logger` assets
* Enqueue `e2e-redux-logger` in header to register the logger as soon as possible
* Merge #1695 

## QA Brief

1. Run `npm run build:test`
1. Run `DEBUG_REDUX=1 npm run test:e2e`
1. Ensure Redux action logging is present in console output

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Moving to Approved, worked with @aaemnnosttv to confirm console output.
