### ISSUE TITLE
Use lazy/Suspense from wp.element if available

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#170]
If not available, they should be imported from React as fallback

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `lazy` and `Suspense` should be accessed from `wp.element` if present. They should only be accessed from `React` if they aren't present on `wp.element`.
* There should be no console errors on the Site Kit dashboard or the individual module pages.

## Implementation Brief

* `lazy` and `Suspense` should be accessed from `wp.element` if present. They should only be accessed from `React` if they aren't present on `wp.element`.

## Changelog entry

* N/A

**Comment by lucymtc** [comment]
QA looks good. 
Tested by installing Gutenberg plugin which exposes lazy/Suspense in wp.element 

Confirming related functionality works as expected in both scenarios with lazy/Suspense from React and from wp.element.
