### ISSUE TITLE
Blank dashboard - Update to 1.10.0 - Uncaught TypeError: Cannot read property ‘needReauthenticate’ of undefined

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1701]
## Bug Description

After upgrading to 1.10.0 the admin dashboard is blank, with the following console error 

```
googlesitekit-activation.js?ver=1.10.0:1 Uncaught TypeError: Cannot read property 
needReauthenticate of undefined
at Object.<anonymous> (googlesitekit-activation.js?ver=1.10.0:1)
at Object.205 (googlesitekit-activation.js?ver=1.10.0:1)
at __webpack_require__ (googlesitekit-activation.js?ver=1.10.0:1)
at Module.<anonymous> (googlesitekit-activation.js?ver=1.10.0:1)
at Module.533 (googlesitekit-activation.js?ver=1.10.0:1)
at __webpack_require__ (googlesitekit-activation.js?ver=1.10.0:1)
at n (googlesitekit-activation.js?ver=1.10.0:1)
at googlesitekit-activation.js?ver=1.10.0:1
at googlesitekit-activation.js?ver=1.10.0:1
```

Site Health info:
```
version: 1.10.0
php_version: 7.4.5
wp_version: 5.4.2
reference_url: https://**hidden**
amp_mode: no
site_status: connected-site
user_status: not authenticated
active_modules: site-verification, search-console, adsense, analytics, pagespeed-insights
required_scopes: 
	openid: ⭕
	https://www.googleapis.com/auth/userinfo.profile: ⭕
	https://www.googleapis.com/auth/userinfo.email: ⭕
	https://www.googleapis.com/auth/siteverification: ⭕
	https://www.googleapis.com/auth/webmasters: ⭕
	https://www.googleapis.com/auth/adsense.readonly: ⭕
	https://www.googleapis.com/auth/analytics.readonly: ⭕
search_console_property: **hidden**
adsense_account_id: pub-192•••••••••••••
adsense_client_id: ca-pub-192•••••••••••••
adsense_account_status: approved
adsense_use_snippet: yes
analytics_account_id: 1674•••••
analytics_property_id: UA-1674•••••••
analytics_profile_id: 2191•••••
analytics_use_snippet: yes
```

WordPress support topic: 
https://wordpress.org/support/topic/blank-white-screen-23

Another similar issue reported: 
https://wordpress.org/support/topic/blank-screen-90 

## Additional Context

- Similar to #1700 which also occurred with version 1.10.0  
- Incognito window or reinstalling plugin didn't resolve issue
- No related front end console errors
- Site fully secure with redirection
- Previous versions working fine

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
New dashboard error (no longer blank screen) after revoking access and reinstalling Site Kit, see [WP support topic](https://wordpress.org/support/topic/blank-white-screen-23/) for more info:
```
Site Kit encountered an error
Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

in NotificationCounter
in ActivationApp
in RestoreSnapshots
in ErrorHandler
in Root
```

**Comment by jamesozzie** [comment]
Closing as original user was able to use Site Kit as expected after temporarily deactivating caching plugin while reinstalling Site Kit. 

For those impacted please try clearing your browsers cache and purging your CDN before checking Site Kit dashboard once more. Alternatively follow the steps as described in [original support topic.](https://wordpress.org/support/topic/blank-white-screen-23/)

**Comment by jamesozzie** [comment]
Reopening for further inspection. Similar to #1700 and #1704, which both occurred after the same version update.

**Comment by felixarntz** [comment]
This is caused by a similar problem as #1700 - let's follow progress in that issue.
