### ISSUE TITLE
1.10.0: frontent webfont configuration interferes with site font configuration

### ISSUE THREAD

**Issue by lkraav** [google/site-kit-wp#1703]
## Bug Description

Our UI library enqueues `'sans-serif' => 'Roboto:300,300i,400,400i,700,700i,900'`

This plugin adds hardcoded Roboto:500, which matches some of our upstream vendor components styling in an unintended fashion.

https://github.com/google/site-kit-wp/blob/8ffa689fd0f30d5ed83642c029cfcb89eb26ad32/includes/Core/Assets/Assets.php#L176-L179

## Steps to reproduce

:point_up: 

## Solution

I'm not sure.

a) I couldn't find any setting to disable loading Site Kit on frontend. I'm not sure if anybody is actually looking at it, perhaps I should be able to just disable loading.

b) Make font list filterable, so I could remove the interfering weight?

c) All of the above?

d) Any other ideas?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Google font families definition that Site Kit uses by default should be filterable, relying on a new `googlesitekit_font_families` filter.
* If the filter returns an empty array, the entire process of enqueuing the fonts should be short-circuited - basically in that case it should be assumed that another plugin/theme is taking care of it in their own way.

## Implementation Brief
* Using `includes/Core/Assets/Assets.php`
    * In the `register` method, add a new filter via the `add_filter` function, named `googlesitekit_font_families`.
    * The second parameter of the `add_filter` function should be an anonymous function having `$fonts` as only parameter.
        * Within the function, check if `$fonts` is not an `array` and is `null`. If that is the case, then return the existing fonts array, i.e the values of the `$font_families` variable.
        * If `$fonts` is an array and is not null, return `$fonts`.
    * In the `enqueue_fonts` method, get the values for the `$font_families` variable by applying the `googlesitekit_font_families` filter the `apply_filters` function and having `null` as second parameter.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Within the active theme's `functions.php`, insert the following snippet:
	```php
	add_filter( 'googlesitekit_font_families', function() {
		return null;
	} );
	```
* Check on the FE via Devtools to see ifno requests are made to load the `Roboto` and `Google Sans` fonts.

## Changelog entry

* Update Google fonts loaded by Site Kit to be filterable.

**Comment by tofumatt** [comment]
IB ✅

**Comment by johnPhillips** [comment]
QA ✅

- When I added the snippet to the `functions.php` of the current theme and navigated to the front end, I was not seeing `Google Sans` or `Roboto` loaded. 
- When I removed the snippet, I saw `Google Sans` or `Roboto` loaded.
