### ISSUE TITLE
Analytics does not support set up with moved properties

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1707]
## Bug Description

Google Analytics supports transferring ownership of an Analytics Property and its views to another account (see [Move a property](https://support.google.com/analytics/answer/6370521?hl=en)).

When this happens, the property is moved to the destination account but its property ID remains unchanged. In https://github.com/google/site-kit-wp/issues/1402 we simplified our internal API to derive the Analytics account ID from the property ID as it is documented in [Tracking ID and property number](https://support.google.com/analytics/answer/7372977?hl=en).

However, this is clearly not a safe assumption to make as warned in the the above document on moving properties:

> Keep in mind that the original account is still identified in the ID (e.g., `UA-<source account number>-1`), and since the ID does not change, any automated processes that you have set up for the destination property that make assumptions about the account number could be affected.

This blocks users from being able to set up the Analytics module using a moved property because the request for the property's profiles is using the account ID from the property ID (the source account ID) rather than the current (destination) account ID. See #1548 

## Steps to reproduce

1. Move a property from Analytics account A to Analytics account B
1. Attempt to set up the Analytics module using the moved property
1. See error message below

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/85406003-d6504600-b569-11ea-8b8e-fd51541ed81f.png)

## Additional Context
 - Plugin Version: 1.10

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The account ID for a given property or profile/view must be explicitly passed based on the selected account whenever possible rather than inferring from a property ID alone
* Existing tag logic cannot blindly assume an account ID based on the property ID, but the account ID in the property ID should still be checked first for the most efficient property look-up when checking tag permission

#### `datastore/properties.js`

* Update `actions.selectProperty` to source `accountID` from `selectors.getAccountID()` instead of parsing

#### `datastore/profiles.js`

Update the following functions to require an `accountID` as the first parameter before `propertyID`
* `selectors.getProfiles`
    * `resolvers.getProfiles`
* `selectors.isDoingCreateProfile`
* `selectors.isDoingGetProfiles`
* `actions.createProfile`
* `actions.fetchGetProfiles`
* `actions.fetchCreateProfile`

#### `setup/setup-main.js` and `settings/settings-edit.js` 

* Update the `useEffect` which sets the `accountID` and property in the existence of an existing tag to source the `accountID` from `getTagPermission( existingPropertyID ).accountID` rather than parsing from existing tag.

#### `util/parse-property-id.js`

* Delete

#### `GET:tag-permission` datapoint

* Parse the account ID from the property ID as we do now
* Check if the user has access to this account
	- If yes, check if the property exists/belongs in this account
		* If yes: ✅
		* If no: iterate through all other accounts the user has access to
			- If property is found: ✅
			- Otherwise: user does not have access.

In all cases, the response should return the same shape with a 200 response:
`{ accountID: string, propertyID: string, permission: bool }`

More specifically:
* The parsing of the property ID into an "assumed" account ID should now happen in the `has_access_to_property` method, its second parameter should be removed.
* The `has_access_to_property` method should now return an associative array with `accountID` and `permission`: If account with access found, use that account ID and `true`, otherwise use the assumed "parsed" account ID and `false`.
    * The `GET:tag-permission` code itself should be modified to no longer do the parsing itself, and instead just call `has_access_to_property`, then merge that method's return value into an associative array with `propertyID`, to maintain the same overall response shape as today.

#### `GET:accounts-properties-profiles` datapoint

* Update to require an `existingAccountID` when passing a `existingPropertyID`

#### `datastore/accounts.js`

* In the resolver for `getAccounts`, wait for `getTagPermission`
	- If an existing tag is present, pass the returned `accountID` from the tag permission as `existingAccountID` in addition to `existingPropertyID` when calling `fetchGetAccountsPropertiesProfiles`

## QA Brief

* 

## Changelog entry

* Require `accountID` to be passed to `getProfiles` selector in `modules/analytics` store, in order to supported moved Analytics properties.

**Comment by felixarntz** [comment]
IB ✅ 

One thing to add: Profiles should also be keyed by `${ accountID }::${ propertyID }` again in the datastore.

**Comment by felixarntz** [comment]
@aaemnnosttv I've added a small extra segment to the IB, under the "More specifically" section for `GET:tag-permission`: TLDR we should have the property detection method now also return the detected account ID, since it is no longer necessarily the parsed one. See #1709 for the same change in AdSense. This brings it more in line with the JS datastore code too, and the `GET:tag-permission` code itself then almost just calls that method and merges in `propertyID`.

**Comment by ryanwelcher** [comment]
@felixarntz in working on this, we discovered a bug in `isDoingGetAccounts` specifically around `isAwaitingAccountsPropertiesProfilesCompletion`. It seems that if the request fails, that `isDoingGetAccounts` never changes. cc @aaemnnosttv

**Comment by felixarntz** [comment]
@ryanwelcher Thanks for flagging! Did you find a solution to the bug yet, or is that something where another pair of eyes would help?

**Comment by aaemnnosttv** [comment]
@felixarntz it's a limitation of the `createFetchStore` since the `reducerCallback` is only called on success. I forget why this state was added again? 🤔  

I wonder if `isDoingGetAccounts` should simply select `getAccounts` and return `accounts === undefined` ? That way it would always be accurate without being coupled to a resolver or any state other than accounts. What do you think? It ends up having the side-effect of loading accounts, but I don't think that would be a problem as it is.

**Comment by felixarntz** [comment]
@ryanwelcher @aaemnnosttv Oh this is actually a bug in the `getAccounts` resolver. The call `dispatch( STORE_NAME ).receiveAccountsPropertiesProfilesCompletion();` needs to happen after the if clause, so regardless of whether the request was successful or not. The same fix needs to be applied to the `getProperties` resolver, where `dispatch( STORE_NAME ).receivePropertiesProfilesCompletion( accountID );` should also run after the if clause. Let's do that as part of this PR.

The reason this additional `isAwaiting*Completion` was introduced is that, due to how these are kind of "combined" API endpoints, multiple reducers need to be used, and those reducers (`receiveGetAccounts`, `receiveGetProperties`, `receiveProfiles`) are actually built like they should be if we didn't have those combined API endpoints. It's a bit odd, but works as expected apart from the above bug.

**Comment by cole10up** [comment]
**Tested**

Installed latest 1.12.0 release candidate.

Moved Elasticpress from cole10up to Key Cougar account

![image](https://user-images.githubusercontent.com/57115907/87638630-f43c4100-c6f8-11ea-9aa0-00074210f08f.png)

![image](https://user-images.githubusercontent.com/57115907/87638706-1930b400-c6f9-11ea-98e6-a2ca2125bb5a.png)

Setup Analytics:

Notice moved properly is displayed:
![image](https://user-images.githubusercontent.com/57115907/87638795-36fe1900-c6f9-11ea-82c9-14f01571bccf.png)

Successfully able to setup
![image](https://user-images.githubusercontent.com/57115907/87638835-48472580-c6f9-11ea-95d5-891170bc68b5.png)

Checking with a separate user on the same site:
![image](https://user-images.githubusercontent.com/57115907/87638863-55fcab00-c6f9-11ea-9d21-f3567144f6e6.png)

![image](https://user-images.githubusercontent.com/57115907/87638888-5dbc4f80-c6f9-11ea-8815-8e529de8b85f.png)

This is confirmed fixed.

Passed QA ✅

**Comment by felixarntz** [comment]
In terms of QA this is good, however the calls in Storybook to the changed actions have not been updated, so our Storybook components appear broken. Moving back to Execution to address.
