### ISSUE TITLE
Explore caching PSI module data server-side

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#171]
As the PageSpeed Insights API takes a considerable amount of time to load results and since that data is not confidential in any way, we should cache it on the server-side in an intelligent way.

This is a special case, so I don't think we should bring back the old cache layer. Instead, we can implement the mechanism directly in the module. It should work something like this:

Cache request results in transients.
As soon as the API key (PageSpeed Insights uses a global API key, not OAuth) is available, perform an initial request so that the data is stored and available on first page load.
Subsequently, when fetching data from the transient, check its expiration separately and perform another request in the background to refresh that data, while serving the data immediately from the cache.
The data can be cached globally in transients since it is not scoped to a user in any way.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Not crucial to do, plus there is some overlap with the upcoming work to store historic PSI data, as well as potentially storing lab data on demand.

This is a `maybelater` for now.
