### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jeremycanales01** [google/site-kit-wp#1716]
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@jeremycanales01 Please provide more information on this issue and we can hopefully assist.
