### ISSUE TITLE
Internal GA tracking not loading when opted-in

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1717]
## Bug Description

In https://github.com/google/site-kit-wp/issues/1648 we updated the logic used to restrict which screens our internal event tracking would be automatically loaded on if the user was opted-in (it would still never be loaded automatically without this). However, Analytics is no longer loaded at all due to a flaw in the the logic used on the `$hook_suffix` to qualify the screen; except when opting in as Analytics is loaded on-demand. Subsequent events after navigating are not tracked.

## Steps to reproduce

1. Opt-in to GA tracking
1. Navigate to Site Kit dashboard
1. See GA is not loaded on the page

## Additional Context

 - Plugin Version: 1.10

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**Same as #1648**
* Site Kit's GA tracking script should only be included on-load on Site Kit-owned admin screens:
    * `googlesitekit-dashboard`
    * `googlesitekit-splash`
    * `googlesitekit-settings`
    * `googlesitekit-module-*`

**Additionally**
* E2E tests are added to cover this behavior

## Implementation Brief

* Add a `public get_screen( $hook_suffix ): Screen|null` method to `Screens`
* Pass `Screens` instance to `Tracking` as a new constructor dependency.
* Replace logic for `trackingAllowed` logic to call `get_screen()` with the current `$hook_suffix` and set to `true` if the returned value is an instance of `Screen`
* Add E2E tests to check for the presence of `script[data-googlesitekit-gtag]` on Site Kit screens
	- present on initial load on above screens in AC when user is opted-in to tracking
	- not present on initial load on above screens in AC when user is opted-in to tracking
	- not present on screens outside of AC regardless of user opt-in
* Finish and merge #1718 

## QA Brief

* Install [Tag Assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk) and enable for the site

When the Site Kit GA tag is loaded, you will see this in Tag Assistant
![image](https://user-images.githubusercontent.com/1621608/86272186-d5a55880-bbd6-11ea-9a91-de0f7d433e30.png)

* Reset Site Kit if not using a fresh install but don't set up yet
* Check a few non-Site Kit pages and make sure Tag Assistant does not show the Site Kit GA tag  
E.g. WordPress dashboard, Plugins, Front end
* Set up Site Kit - **do not opt-in to anonymous tracking**
* Check the following Site Kit screens to make sure the Site Kit GA tag **is not loaded**
    - Site Kit dashboard
    - Settings
    - Splash (set up)
    - Module page (e.g. Search Console page)
* Opt-in to tracking via the splash page or admin settings
* Check the same screens as above to make sure the GA tag **is loaded**
* Check a few non-Site Kit pages and make sure Tag Assistant **does not show** the Site Kit GA tag

Note: when opting-in to tracking you should see the GA tag show up, even on non-Site Kit screens (like the plugin activation banner on the plugins page)

## Changelog entry

* Fix admin tracking regression where snippet would not be loaded on the page.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
For some reason, E2E tests are failing on `develop` now after this was merged so I'm moving this back to execution to resolve.

**Comment by cole10up** [comment]
**Tested:**

Installed and enabled Tag Assistant for my site. Installed lates SK release candidate. 

![image](https://user-images.githubusercontent.com/57115907/86838208-be41f180-c054-11ea-8547-da60100df9c1.png)

Reset SK checked non-site kit pages:

![image](https://user-images.githubusercontent.com/57115907/86838363-ecbfcc80-c054-11ea-8724-a6e21b625ddd.png)

![image](https://user-images.githubusercontent.com/57115907/86838377-f2b5ad80-c054-11ea-89ff-77739d85e9f9.png)

![image](https://user-images.githubusercontent.com/57115907/86838409-f9dcbb80-c054-11ea-883c-0b3c238ca24d.png)


Setup SK ensured **I did not opt-in to anonymous tracking**

![image](https://user-images.githubusercontent.com/57115907/86838675-4fb16380-c055-11ea-9bbc-fcac30ca095d.png)

![image](https://user-images.githubusercontent.com/57115907/86838696-563fdb00-c055-11ea-8a13-2fdcae7040ad.png)

![image](https://user-images.githubusercontent.com/57115907/86838724-60fa7000-c055-11ea-8521-efab2d7e5d05.png)

Clicked opt-in in settings

Confirmed:

![image](https://user-images.githubusercontent.com/57115907/86838787-71aae600-c055-11ea-837c-b277e3d0399c.png)

![image](https://user-images.githubusercontent.com/57115907/86838802-78395d80-c055-11ea-9fb2-7d074bbe34b0.png)

All good on my end.

Passed QA ✅
