### ISSUE TITLE
Update documentation on how to package a release build

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#172]
Initial thought is we create a release branch for a version, eg `release/1.0.1` and run the release command their, committing the built files and tag the release. We can then update the download link in master to the download zip url.

- git checkout -b release/[NAME]
- gulp release

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this in favor of #1196 and #603 which delegates release building and deployment to GitHub Actions. 

Current release building related documentation is found here:
https://github.com/google/site-kit-wp/wiki/Releases
