### ISSUE TITLE
Wrap registered widgets with `Widget` component by default

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1724]
## Feature Description

Follow-up to #1300, closely related to #1678: While the components rendering a widget should have full control about the widget rendered, the majority of components is expected to return its content wrapped in the `Widget` component that was implemented as part of #1300 and is publicly exposed. As part of the discussions on these issues it was decided to simplify this so that by default the `Widget` component would automatically wrap the actually registered component's output.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new property to wrap widget components with `Widget` automatically should be available on `settings` when registering a widget, and its default value should be `true`.
    * If `true` the component rendered should be wrapped in an instance of the `Widget` component, unless the component itself returns `null`, in which case it should not result in an empty `Widget` being rendered (related: grid logic in #1678).
    * If `false` just render the component like it is now.
* Note that this is technically a breaking change, but since we've not been publicizing this API and are not using it yet, it's acceptable at this point.

## Implementation Brief

* Add property `settings.wrapWidget` with default of `true` to the `registerWidget` action in the `core/widgets` store.
* In the `WidgetRenderer` component:
    * Render the `Component` into a variable. If `null`, just return `null` right away.
    * Also retrieve the `wrapWidget` value. If `true`, wrap the `Component` instance in a `Widget` instance and return that.

## QA Brief

* 

## Changelog entry

* Introduce new `wrapWidget` setting to `core/widgets` store's `registerWidget` selector which adds the wrapping `Widget` component by default.

**Comment by tofumatt** [comment]
> Note that this is technically a breaking change, but since we've not been publicizing this API and are not using it yet, it's acceptable at this point.

I would note that any existing Widgets should be migrated to remove their own `<Widget>` wrapper if any exist when this is implemented. But since we aren't using them yet this should be fine. 😄 

Also, I added the QA: Eng label to this issue as there won't be anything to QA yet.

IB ✅

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

* Registered a widget using the global `widgets` instance  
```js
global.googlesitekit.widgets.registerWidget( 'test-widget', {
	component: () => <h1>Test Widget</h1>,
}, [ 'dashboardAllTraffic' ] );
```
* Component was wrapped with `Widget` by default  
![image](https://user-images.githubusercontent.com/1621608/87557220-4c0a8600-c6c0-11ea-8ac4-c0547b22de39.png)
![image](https://user-images.githubusercontent.com/1621608/87557075-254c4f80-c6c0-11ea-969d-316fecb90421.png) 
* Adding `wrapWidget: false` to the widget `settings` caused the rendered widget to not be wrapped with the `Widget` component  
![image](https://user-images.githubusercontent.com/1621608/87557194-4614a500-c6c0-11ea-98d9-1b3a13898a7b.png)
![image](https://user-images.githubusercontent.com/1621608/87557187-44e37800-c6c0-11ea-9c0c-fbab92c22f16.png) 


✅  `settings.wrapWidget` documented on `registerWidget` in `datastore/widgets.js`
https://github.com/google/site-kit-wp/blob/1452dd99381b36ca2d46665ba42177cb7ca0a915/assets/js/googlesitekit/widgets/datastore/widgets.js#L84-L91

⚠️ `settings.wrapWidget` not documented on `registerWidget` in `widgets/index.js`
https://github.com/google/site-kit-wp/blob/1452dd99381b36ca2d46665ba42177cb7ca0a915/assets/js/googlesitekit/widgets/index.js#L73-L79

Functionally everything seems to be working fine, just the setting documentation missing in the main widgets API module.

I'll create a quick PR to add this as it's just a single line to be copied.

**Comment by aaemnnosttv** [comment]
QA ✅  now that #1786 is merged.
