### ISSUE TITLE
Fix datastore issues around preloaded API data and using API caching

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1725]
## Bug Description

After #1611 (PR: #1692), the datastore could that this change was implemented for needs to be updated to no longer specify `useCache: false` by default, which wasn't part of that issue - at the moment, providing this property as `false` results in the preloaded data being ignored.

Also, we are currently not yet preloading modules data from `core/modules/data/list`, which we should add now.

Another related issue is that refreshing data from these stores (currently only happening when changing module activation state in `core/modules`) is not working correctly:
* For refreshing module data, it is relied on the same logic like originally, so as soon as we remove `useCache: false` (which we should for the above reason), it would not actually refresh data but rely on the cache.
* For refreshing authentication data, the current logic refreshes the cached data, but does not actually touch the `core/user` store, so if that had requested authentication data before (which is what would practically happen all the time), it would not be updated because the resolver was already resolved.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The internal `fetch...` datastores for the following selectors should be updated to by default rely on the cache, but support bypassing the cache:
    * `createSettingsStore`'s `getSettings`
    * `core/site`'s `getConnection`
    * `core/user`'s `getAuthentication`
    * `core/modules`'s `getModules`
* The `core/modules` store should, as part of the `setModuleActivation` action, call `fetchGetModules` bypassing the cache, and it should rely on the `core/user` store's authentication infrastructure instead of just refetching a current API response.
* Module data should be preloaded on the server via the `google-site-kit/v1/core/modules/data/list` REST endpoint.

## Implementation Brief

* Modify the 4 `fetch...` stores listed in the ACs in the following way:
    * Add an `argsToParams` function that accepts a single `options` argument (default `{}`) with a `useCache` (default `true`) as sole property and returns an object like `{ options }`.
    * Update the `controlCallback` to look at `params` (first parameter) and use the `options.useCache` value from there.
* In `assets/js/googlesitekit/modules/datastore/modules.js`:
    * Pass `{ useCache: false }` argument to `fetchGetModules` call in `setModuleActivation` action (to bypass cache).
    * Change the `REFETCH_AUTHENTICATION` control to be come a registry control, which calls the `core/user` store's `fetchGetAuthentication( { useCache: false } )` (argument to bypass cache).
    * Move yielding the `REFETCH_AUTHENTICATION` into the `setModuleActivation` action right after the `fetchGetModules` call in the clause, as it is right now unnecessarily duplicated.
* In the PHP `Modules` class, add `google-site-kit/v1/core/modules/data/list` to the list of preloaded route paths.

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This generally looks good to me.

Since these fetch actions don't have any required params, I think we should give it a single `options` param as an object. That would be more clear to use (even if it is just the one option for now). e.g.
```js
yield fetchGetConnection( { useCache: false } )
// Rather than
yield fetchGetConnection( false )
```

Otherwise, IB ✅ 

I have a feeling the estimate may be a bit small, but that mostly depends on the implications these changes may have on existing tests more than the actual changes to the source. They shouldn't really change much because we don't really have dedicated tests for fetch actions, so as long as this change doesn't require more substantial changes it should be fine 👍

**Comment by felixarntz** [comment]
@aaemnnosttv That sounds good to me, updated the IB to use an `options` object as the argument. Also that's fair, I changed the estimate to 7 - I think the production code changes themselves are actually even closer to a 1 than a 3, but since this could have implications on testing, it may take quite a bit more.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz #1611 has been reverted so I'm assigning this one to you and moving it back to AC for now.

**Comment by felixarntz** [comment]
#1611 has been updated with a new approach that covers the relevant parts from here as well (this was originally just a follow-up anyway). Closing.
