### ISSUE TITLE
Enable language parameter for setup/auth flow

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1726]
## Feature Description

* Pass a language parameter to the setup and scope re-auth process to indicate the user's language.

The Site Kit service used during setup is now localized into the following languages: Japanese, German, Norwegian, Brazilian Portuguese, Russian, Latin American Spanish, Spanish and Ukrainian. 

To enable the localized version of the service, the Site Kit plugin needs to pass an `hl` language parameter.  The service uses a [language matcher](https://blog.golang.org/matchlang) to determine the closest supported language, falling back to english.  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When setting up Site Kit, the current WordPress user's language settings should be passed as the `hl` query parameter to the setup URL.
* When going though the setup flow, all strings (except names) should be translated from their english versions to the user's language, including auth screens (for supported languages, see above).
* When adding an additional scope (for example when activating a new module such as Analytics), the current WordPress user's language settings should be passed as the `hl` query parameter to the authentication URL.

## Implementation Brief

* In `includes/Core/Authentication/Clients/OAuth_Client.php::get_proxy_setup_url` add an `hl` query parameter set to the user locale:

```php
$query_params['hl'] = get_user_locale();
```

* In `includes/Core/Authentication/Clients/OAuth_Client.php::get_authentication_url` add an `hl` query parameter set to the user locale:

```php
$query_params = array(
	'hl' => get_user_locale(),
);

return add_query_arg( $query_params, $this->get_client()->createAuthUrl() );
```

## QA Brief

* To add additional languages to WordPress, go to Settings and choose the language from the dropdown, click save changes. WordPress will install the language on the fly.
* Now create a user or edit an existing user profile and choose the language to test.

## Changelog entry

* Pass `hl` query parameter to Site Kit service for setup and authentication, for a localized experience.

**Comment by adamsilverstein** [comment]
Draft PR: https://github.com/google/site-kit-wp/pull/1672 with approach described in IB (can be tested with the tester plugin against staging).

**Comment by felixarntz** [comment]
@adamsilverstein One thing that's missing here is handling the language when going to the OAuth consent screen directly (e.g. when requesting additional scopes). Can you amend the ACs and IB to include this part too?

**Comment by adamsilverstein** [comment]
Yep, will do!

**Comment by adamsilverstein** [comment]
@felixarntz Missed this one last week, I have now updated the AC and IB to include the authorization flow when adding scopes/enabling a new module.

**Comment by felixarntz** [comment]
IB ✅

**Comment by adamsilverstein** [comment]
Updated draft PR to match IB and added tests.

**Comment by cole10up** [comment]
**Tested**

Installed latest develop SK and the staging plugin.

Ran through a series of setup and auth tests:

**Spanish:**
![image](https://user-images.githubusercontent.com/57115907/88624599-1f5d5380-d05c-11ea-9532-d74d38c8eaf9.png)
![image](https://user-images.githubusercontent.com/57115907/88624632-2edc9c80-d05c-11ea-837a-e588d04b0ed6.png)
![image](https://user-images.githubusercontent.com/57115907/88624662-39973180-d05c-11ea-80a1-e45af4fbc660.png)
![image](https://user-images.githubusercontent.com/57115907/88624685-43b93000-d05c-11ea-9324-36c37195e6e7.png)

**German**
![image](https://user-images.githubusercontent.com/57115907/88624991-d063ee00-d05c-11ea-87aa-a94f2e98c6a3.png)
![image](https://user-images.githubusercontent.com/57115907/88625010-d78afc00-d05c-11ea-95bb-8d8c4ffdbe36.png)
![image](https://user-images.githubusercontent.com/57115907/88625030-df4aa080-d05c-11ea-90de-32c066ad19ea.png)
![image](https://user-images.githubusercontent.com/57115907/88625090-f5f0f780-d05c-11ea-8465-02559d69ec8a.png)

To not clutter the rest of the findings - will show the first splash screen and call out any errors
**Japanese**
![image](https://user-images.githubusercontent.com/57115907/88625346-6d268b80-d05d-11ea-9173-9209c476dff5.png)

**Norwegian**
![image](https://user-images.githubusercontent.com/57115907/88626036-c7741c00-d05e-11ea-9e17-9d0492bb58e3.png)

**Portuguese**
![image](https://user-images.githubusercontent.com/57115907/88626167-0013f580-d05f-11ea-908f-37cf87a07dcb.png)

**Russian**
![image](https://user-images.githubusercontent.com/57115907/88626277-3baebf80-d05f-11ea-8077-0e6b53d05d79.png)

**Ukrainian**
![image](https://user-images.githubusercontent.com/57115907/88626455-80d2f180-d05f-11ea-85c2-fc4b2232467c.png)

Notice the Sign in with Google button looks a bit sloppy

That is the only item to note.

Passed QA ✅
