### ISSUE TITLE
Track advanced plugin Analytics events for

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1728]
## Feature Description

For certain popular plugins, Site Kit's Analytics module should fire additional events if the respective plugin is active.

**This work should be done against a `feature/ga-advanced-tracking` branch.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics should inject additional code to fire certain events as follows:
    * For WooCommerce, event category `ecommerce` and event actions:
        * `add_to_cart` (with item name)
        * `remove_from_cart` (with item name)
        * `checkout`
        * `review_cart`
        * `cart_contents`
        * `update_cart`
        * `product_details` (with item name)
        * `place_order`
        * `proceed_to_paypal`
    * For WP Forms, Contact Form 7, Gravity Forms, Ninja Forms, Formidable Forms, event category `engagement` and event actions:
        * `form_submit`
* Tracking of these events should work in both AMP and non-AMP.
* Extra JavaScript code included for non-AMP should be in the HTML source after the Analytics tag. It should not have any dependencies and rely on patterns established by the [AMP framework](https://github.com/ampproject/amphtml/blob/feb792fcdc7d328073300d083a516c18c87c1194/extensions/amp-analytics/0.1/analytics-root.js#L433) for performance-efficient selector matching.

### 3P event registration

* 3P plugins should be able to register their own events by hooking into a new action `googlesitekit_register_gtag_events`. The action should receive an instance of a `Plugin_Tracking_Events_Registry` class, which has a `register( array $config )` method.

## Implementation Brief

* See separate protoype and spreadsheet.

## QA Brief

* N/A

## Changelog entry

* Introduce API layer for advanced Analytics event tracking configurations from other plugins.

**Comment by MiraSm** [comment]
If you release it, it will be a bomb. And will this plugin itself simply transmit events to GA, or place a datalayer in code?

**Comment by OC2PS** [comment]
This issue is closed, but evidently the plugin still doesn't do enhanced ecommerce tracking...

**Comment by jamesozzie** [comment]
Any update on this can be tracked via #3051, feel free to subscribe to that issue for further information.
