### ISSUE TITLE
Fix first admin usage and introduce concept of ownership

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1743]
While the goal of Site Kit is to treat all administrator users as equal in terms of their permissions, it is crucial to have the concept of ownership for certain parts of the plugin, e.g. to indicate that a certain administrator user originally configured it.

As part of this issue, no visual changes should be made yet, but the necessary infrastructure should be put in place to have awareness of owner users. In the future this will be surfaced like e.g.:
* Informing admins when editing module settings who originally set up the module (and therefore has access).
* Warning admins when editing key module settings set up by someone else that they will essentially take over as new module owner.
* Informing users who get Google API-related permission errors for whom they need to ask to get the necessary access.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/site` JS data store should expose a `getOwnerID` selector, which returns user ID (integer) of the first administrator that connected overall Site Kit.
    * `core/site/data/connection` should expose a new `ownerID` in API response (see below).
* The existing `googlesitekit_first_admin` option should be renamed to `googlesitekit_owner_id`, and it should be modified to always return an integer (i.e. `0` if there is none set).
    * An upgrade routine should rename the existing option in the database appropriately.
    * The logic to set the owner (currently happens on the fly when loading legacy JS data in `Authentication::inline_js_setup_data()`, which is a bad practice) should be moved to after having received an access token (`OAuth_Client::authorize_user()`), and of course it should only happen if the user can `Permissions::MANAGE_OPTIONS` and if there is no other user set yet, with the following caveat:
        * If there is already an owner set and it is a different user, check if that user still exists, and if they do, whether they can still `Permissions::MANAGE_OPTIONS`.  
        If one of these requirements is no longer satisfied, the current user should implicitly take over as the new Site Kit owner.
* Site Kit modules with editable settings which have Google API-side access implications should receive an `ownerID` (integer) sub setting:
    * `Analytics` (via account ID, property ID, profile ID)
    * `AdSense` (via account ID, client ID)
    * `TagManager` (via account ID, container ID, AMP container ID)
    * `Optimize` (via Optimize ID)
    * Whenever one of the above settings is **changed** for the respective module, the owner ID should be set to the current user ID.
    * The datastores of these modules should expose a `getOwnerID` selector.

## Implementation Brief

* Update `assets/js/googlesitekit/datastore/site/connection.js`
    - Add `selectors.getOwnerID` as a registry selector that returns `ownerID` from `getConnection`
    - Update `connection.test.js` to include a test for this selector
* Create a new `Owner_ID` class that extends `Core\Storage\Setting` for the `googlesitekit_owner_id` option
    - Should have a type of `integer`
    - Should use `intval` as its `sanitize_callback` (see `get_sanitize_callback`)
    - The `default` value should be sourced from the `googlesitekit_first_admin` option, cast to an integer
    - Needs a test case created for it
* Add a new `Module_With_Owner` interface
    - `protected function get_owner_id() : int;`
* Add a new `Module_With_Owner_Trait` which implements the method and returns `ownerID` from the module settings
* Add a new `Setting_With_Owned_Keys_Trait`
    - implement a `register_owned_keys` method which accepts an array of settings keys that, are related to the `ownerID`
    - Adds action to `add_option_{{ $option }}`  
        If the new option value has values defined for any of the owned keys, call `$this->merge( array( 'ownerID' => get_current_user_id() ) )`
    - Adds filter to `pre_update_option_{{ $option }}`
        - the filter callback receives both the new `$value` and `$old_value`
        - iterate over the list of owned keys, if the values do not match for any of the keys set `$value['ownerID'] = get_current_user_id();` before returning
* Update relevant `Module_Settings` sub-classes to `use Setting_With_Owned_Keys_Trait`, add `ownerID => 0` to their default settings, and call `register_owned_keys( array( ... ) )` in their `register` methods
    * `Analytics` - `accountID`, `propertyID`, `profileID`
    * `AdSense` - `accountID`, `clientID`
    * `TagManager` - `accountID`, `containerID`, `ampContainerID`
    * `Optimize` - `optimizeID`
    * Update tests for these `Module_Settings` sub-classes respectively
* Datastores for these modules will get a `getOwnerID` selector automatically via `createSettingsStore`
* Add `Owner_ID` as `owner_id` property to `OAuth_Client`, instantiated in the constructor, like `First_Admin`
* Update `OAuth_Client::authorize_user` to call `Owner_ID->set( get_current_user_id() )` but only if none is currently set and `current_user_can( Permissions::MANAGE_OPTIONS )`
    - If there is an existing owner ID `Owner_ID->get()` and `$current_owner_id !== get_current_user_id()` and `! user_can( $current_owner_id, Permissions::MANAGE_OPTIONS )`,  
    `Owner_ID->set( get_current_user_id() )` to change the owner to the current user
    - This should have added test coverage in `OAuth_ClientTest`
* Remove `First_Admin` class and test
    - Remove `isFirstAdmin` and references in `Authentication::inline_js_setup_data()`

#### Site Kit ownership

* Reset Site Kit
* Setup Site Kit with an admin user ("**User A**")
* Verify that the `googlesitekit_owner_id` option matches the admin user's ID  
_The value can be inspected via the special `wp-admin/options.php` page, or using wp-cli: `wp option get googlesitekit_owner_id`_
* Without resetting, connect to Site Kit using a different admin user ("**User B**")
* Verify that the `googlesitekit_owner_id` option still matches the same ID belonging to **User A**
* Update **User A**'s role to be a non-administrator
* Disconnect **User B**
* Connect **User B** again
* Verify that the `googlesitekit_owner_id` option matches the user ID of **User B**

#### Module Ownership

* `Analytics`
    - Setup Analytics with an admin **User A**
    - Verify that the `ownerID` for the module references the user ID of **User A**  
        ```js
        googlesitekit.data.select( 'modules/analytics' ).getOwnerID() // may need to run twice due to settings resolution
        ```
    - With a different admin user **User B**, change the configured view/profile
    - Verify that the `ownerID` for the module references the user ID of **User B**
* `AdSense`
    - Skip as there is no way to change the owned settings via the UI – rely on automated tests
    - Ensure the AdSense store has the `getOwnerID` selector
        ```js
        typeof googlesitekit.data.select( 'modules/adsense' ).getOwnerID === 'function' // should be `true`
        ```
* `TagManager`
    - Setup Tag Manager with an admin **User A**
    - Verify that the `ownerID` for the module references the user ID of **User A**  
        ```js
        googlesitekit.data.select( 'modules/tagmanager' ).getOwnerID() // may need to run twice due to settings resolution
        ```
    - With a different admin user **User B**, change the configured container
    - Verify that the `ownerID` for the module references the user ID of **User B**
* `Optimize`
    - Setup Optimize with with an admin **User A**
    - Verify that the `ownerID` for the module references the user ID of **User A**
        ```js
        googlesitekit.data.select( 'modules/optimize' ).getOwnerID() // may need to run twice due to settings resolution
        ```
    - With a different admin user **User B**, change the configured Optimize ID
    - Verify that the `ownerID` for the module references the user ID of **User B**

## Changelog entry

* Introduce concept of ownership for modules based on who set them up.

**Comment by aaemnnosttv** [comment]
@felixarntz this is a good start here but I have a few questions:

What should happen if the owner disconnects from Site Kit, role changes (no longer has Site Kit permissions), or is deleted? I imagine the code that loads this would need to check if the user still exists and is connected to Site Kit to still be considered a site/module owner? Is this more of a concern for subsequent code built on this or is there anything additional to consider in the foundation here?

> An upgrade routine should rename the existing option in the database appropriately

Not sure an upgrade routine is necessary for this. Could we use it to filter in the default value instead, similar to how we handle `googlesitekit_search_console_property`?

**Comment by felixarntz** [comment]
@aaemnnosttv 
> What should happen if the owner disconnects from Site Kit, role changes (no longer has Site Kit permissions), or is deleted? I imagine the code that loads this would need to check if the user still exists and is connected to Site Kit to still be considered a site/module owner? Is this more of a concern for subsequent code built on this or is there anything additional to consider in the foundation here?

Either of these special cases will become more relevant once we work on issues where this is exposed, but generally I believe we should never clear any of the options in these scenarios:
* If the user disconnects or is no longer an admin, they are still the user that most likely has access to e.g. the module's entities (since they're Google service territory).
* If the user is deleted, we can still inform other administrators that "another unknown user" (wording TBD) set up that module, so it's worth keeping that reference.
* For the main Site Kit ownership, we should ensure that, once the owner is no longer an admin or is deleted, and a new administrator connecting should take over in that case. Yet, we shouldn't delete the option, rather when somebody new connects, we should check if the current owner still satisfies these criteria and if not override them. I'll add something to the ACs to clarify this.

> > An upgrade routine should rename the existing option in the database appropriately
> 
> Not sure an upgrade routine is necessary for this. Could we use it to filter in the default value instead, similar to how we handle `googlesitekit_search_console_property`?

I think that's okay. Note that the `First_Admin` class itself should be removed (replaced with `Owner_ID` class), but we can use this approach and keep the old option around until it's naturally deleted (e.g. when resetting).

**Comment by felixarntz** [comment]
@aaemnnosttv IB ✅

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

The site's owner ID currently won't be set on the initial setup (when it should be) as the current user is seen as missing necessary capabilities due to a timing issue related to our meta capability mapping.

This is also missing a QA brief which I didn't notice during CR so I'll add that along with a follow-up PR to fix this.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

All of the other points checked out in my first pass, only the initial connection wasn't working so this is all good now!
