### ISSUE TITLE
Ensure `bin` directory is no longer included in release ZIP file

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1748]
## Bug Description

Since we removed the WP CLI commands from the `bin` directory and it is now used for internal tools, the directory should no longer be included in a release ZIP.

I fixed this manually for the 1.11.0 release, but it should be automatically handled in the future.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release ZIP builds should not include the `bin` directory.

## Implementation Brief

* Remove all `bin` globs from the `globs` array in `gulpfile.js/copy.js`
* Merge #1767 

## QA Brief

* Run `npm run release-zip`
    * Ensure zip file does not contain a `google-site-kit/bin` directory 
* Run `npm run dev-zip`
    * Ensure zip file does not contain a `google-site-kit/bin` directory 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by jqlee85** [comment]
QA ✅
