### ISSUE TITLE
Ensure awareness of snippet status prior to or during plugin deactivation or uninstall

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1750]
## Bug Description

At present a user may uninstall Site Kit after using the plugin to place the various Google services snippets. This can result in future data not being collected, which users may not be aware of. 

While there are different methods to uninstall a plugin consider some approaches that would alert users to the implications, or suggesting they manually place the activated product snippets. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamsilverstein** [comment]
@jamesozzie - Reviewing the available [Deactivation hooks in WordPress](https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/) and some posts on the topic, it is not possible to display a message to users _after they deactivate the plugin_. The reason for this is straightforward: when users disable the plugin, the admin screen refreshes and at that time the plugin code is no longer running.

Some plugins use JavaScript to insert and interstitial "uninstall confirmation" modal. While we could use a similar approach to warn users what is getting disabled, this flow creates a poor user experience where users have to click twice to disable the plugin.

![image](https://user-images.githubusercontent.com/2676022/87343668-7adefb80-c50a-11ea-99ce-a9a61dd876c5.png)

So we can't tell the user anything after they deactivate, maybe we can still inform them before they deactivate?

One idea would be to add a status line on this plugin description so they would at least see information about what is active before deactivating:

![image](https://user-images.githubusercontent.com/2676022/87344522-da89d680-c50b-11ea-8ef0-8e2c542132f1.png)

Another idea is place an icon beside the deactivate button, for example a yellow triangle exclamation point with a tooltip that contains the warning message `Deactivating Site Kit will remove the following connected services:` + a list of what is connected:

![image](https://user-images.githubusercontent.com/2676022/87345813-dc549980-c50d-11ea-9579-d48d5c9f8739.png)

cc: @marrrmarrr and @felixarntz for feedback here.

ps. your ticket title mentions both deactivation and uninstall. In both cases our code will not be running, the hooks that WordPress provides are typically used for cleanup process and are not user facing.

While not strictly enforced, it generally understood and expected from the docs for plugins that deactivating and reactivating a plugin will not change any settings (ie. non destructive) whereas uninstalling a plugin will reset the settings/remove anything the plugin may have added (eg. if a plugin adds a custom post type, it would remove this post type on **unintsall**).

**Comment by marrrmarrr** [comment]
I think the benefit of warning a minority of users will likely be obscured by the extra step / annoyance we'd create for the majority of users (generally if people want to uninstall something, they want the quickest way possible). 
I'm closing this for now, but if lots of complaints from confused users pop up, we could reconsider the benefits.
