### ISSUE TITLE
Add a setting for siteSpeedSampleRate to the Gtag snippet

### ISSUE THREAD

**Issue by superfein** [google/site-kit-wp#1751]
## Feature Description

For web performance engineers, being able to set the siteSpeedSampleRate to 100 can provide a more complete user data when measuring performance and UX bottlenecks. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@superfein Many thanks for the suggestion. I've marked this for the team to review.

**Comment by BenEfrati** [comment]
Until implement this feature, you can use this function to add siteSpeedSampleRate

```
add_filter('googlesitekit_gtag_opt', function($gtag_opt){
	$gtag_opt['siteSpeedSampleRate'] = 100;
        return $gtag_opt;
}, 10, 1);
```

**Comment by superfein** [comment]
Thanks @BenEfrati, the filter worked! Really appreciate you sharing it with me.

I'm a little confused though, I thought the GA option was "siteSpeedSampleRate:" 100. Can you confirm if it's "siteSpeedSampleRate" or "site_speed_sample_rate?"

**Comment by BenEfrati** [comment]
Hi
As you can see, I edited my comment since siteSpeedSampleRate is not working with `gtag`
I changed to site_speed_sample_rate based on:

https://support.google.com/analytics/thread/7741119?hl=en
https://support.google.com/analytics/thread/5529764?hl=en

**Comment by superfein** [comment]
Brilliant! Thanks again for confirming that @BenEfrati. I missed the edit you had made, my bad. 

Cheers!

**Comment by aaemnnosttv** [comment]
Closing this out as it is already possible to configure using the `googlesitekit_gtag_opt` filter.
