### ISSUE TITLE
Control the output of the Google scripts

### ISSUE THREAD

**Issue by dingo-d** [google/site-kit-wp#1752]
## Feature Description

It would be great if there was a way to define where we want the analytic scripts to load. The reason for this is that I have a GDPR plugin that will block or load certain parts based on the consent from the user, so if the user says: don't load tracking cookies, I wouldn't load them on the site for that user.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for the suggestion @dingo-d ! This is already possible using some filters on the PHP side, although it may not be documented yet.

For Analytics for example (assuming it is connected via the Analytics module) you can block it from being output entirely with this filter:

```php
add_filter( 'googlesitekit_analytics_tag_blocked', '__return_true' );
```

**For consent-type blocking specifically,** you can use an alternate filter which will still output the tags, but in an initially disabled state. That way, you can use client-side logic to enable them after the fact without requiring a full page reload. Unfortunately, the enabling part is not handled for you (for web tags) so this part is required to implement yourself. It is however handled for AMP tags though.

```php
add_filter( 'googlesitekit_analytics_tag_block_on_consent', '__return_true' ); // web tag
add_filter( 'googlesitekit_analytics_tag_amp_block_on_consent', '__return_true' ); // AMP tag
```

The above filters work for any core module in Site Kit that outputs tags; simply substitute the module's slug (e.g. `analytics` / `adsense`) in the filter name.

More about this [for AMP here](https://amp.dev/documentation/examples/user-consent/client_side_user_consent_flow/).
