### ISSUE TITLE
Fix view name field not displaying in Analytics setup

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1754]
## Bug Description

While the new field to enter an Analytics view name when creating a new view (#716) should appear both in Analytics setup and settings, it is currently not present in setup, blocking the setup from being completed when a user attempts to create a new view (since providing the view name is still a requirement).

See https://github.com/google/site-kit-wp/issues/1617#issuecomment-655567737 for more context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics view name field should be displayed in Analytics setup too.

## Implementation Brief

* Merge #1753.

## QA Brief

* 

## Changelog entry

* Fix bug where users attempting to create a new Analytics view during module setup would be blocked from proceeding.

**Comment by cole10up** [comment]
**Tested**

Installed latest release candidate to reproduce the issue.

Was able to see the issue below:

![Site Kit by Google Dashboard ‹ Related Pelican — WordPress](https://user-images.githubusercontent.com/57115907/86994783-216a7b80-c15c-11ea-832e-413ec58b41be.gif)

Installed 1.11.1, activated and ran through Analytics setup.

![Sign in - Google Accounts (2)](https://user-images.githubusercontent.com/57115907/86994959-a6559500-c15c-11ea-8457-e836e011d05d.gif)

Confirmed new view is able to be created.

Check setup and confirmed switching views functions.

![image](https://user-images.githubusercontent.com/57115907/86995007-bec5af80-c15c-11ea-83fe-059c5908e64c.png)

Confirmed new view setup in settings page functions properly.

![image](https://user-images.githubusercontent.com/57115907/86995036-d3a24300-c15c-11ea-9116-d19ac1a26291.png)

Confirmed removing module and setting up module happy path functions proerly.

Passed QA ✅

**Comment by aaemnnosttv** [comment]
@felixarntz Reopening this as the warning icon is still missing from the profile name field if the new name matches an existing view.

This displays correctly in the settings, it's likely just a missing style for the setup.

**Expected**

![image](https://user-images.githubusercontent.com/1621608/87005850-58767680-c1c8-11ea-875a-c83536ea44d8.png)

**Actual**
![image](https://user-images.githubusercontent.com/1621608/87005835-53192c00-c1c8-11ea-92f1-117a5eda2c36.png)

**Comment by felixarntz** [comment]
@cole10up Ready for another quick QA, see the above UI issue. We now also have Storybook stories for this state:
* Setup: https://google.github.io/site-kit-wp/storybook/master/?path=/story/analytics-module-setup--create-new-view
* Settings: https://google.github.io/site-kit-wp/storybook/master/?path=/story/analytics-module-settings--edit-open-when-creating-new-view

**Comment by cole10up** [comment]
**Retested**

Installed latest fix with the UI issue, confirmed below.

![Site Kit by Google Dashboard ‹ Related Pelican — WordPress (1)](https://user-images.githubusercontent.com/57115907/87076200-40a5ef00-c1d6-11ea-95d0-fb0cfe0c4fa6.gif)

Checked existing Analytics functionality:

![image](https://user-images.githubusercontent.com/57115907/87076288-6632f880-c1d6-11ea-80b1-0cb1521c67ce.png)

UI matches settings page.

Confirmed happy path setup and tear down functions properly

![image](https://user-images.githubusercontent.com/57115907/87076340-777c0500-c1d6-11ea-8d63-142bb3780dcc.png)

![image](https://user-images.githubusercontent.com/57115907/87076384-8793e480-c1d6-11ea-9490-c66472a3b6a0.png)

Passed QA ✅
