### ISSUE TITLE
Javascript Required Messages

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#177]
When Javascript is disabled, Site Kit pages are blank and do not load. While WordPress' functionality is severely limited if Javascript is disabled, it would be good to at least display a message in a `<noscript>` tag when loading SiteKit pages that Javascript is required to use Site Kit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When JavaScript is disabled in the browser, accessing any Site Kit admin screen (dashboard, module screens, settings), as well as the admin bar menu, should display a user-facing message: "The Site Kit by Google plugin requires JavaScript to be enabled in your browser."

## Implementation Brief

* Create a `Requires_Javascript` trait in the `Core/Util` namespace which provides a `get_noscript_html` method to return the `<noscript>` html as a string. This way we have a single source for all places we need to include the tag.
* Add the `<noscript>` tag to the Screen `render()` method 
https://github.com/google/site-kit-wp/blob/b42304c5e577eb13fa5934bd9c02f2a0cba1e44b/includes/Core/Admin/Screen.php#L204-L210
which calls `render_callback()` from each screen to ensure the tag is included for all Site Kit screens.
The tag should only be rendered if there is a `render_callback`
* Add `<noscript>` tag to the admin bar in `Admin_Bar::menu_markup() `
* Add `<noscript>` tag to the activation banner in `Activation::get_activation_notice`
* Add CSS to hide all Site Kit loading bars (and/or app render targets) if JS is not enabled using the `body.no-js` class
    - Ideally something like `body.no-js #js-googlesitekit-*`

## QA Brief

**Affected areas**
* Site Kit plugin activation notice
* Site Kit WordPress dashboard widget
* Site Kit splash (setup) pages
* Site Kit module dashboard pages
* Site Kit main dashboard page
* Site Kit settings page
* Admin Bar (post edit & post on front) for posts that have data in Search Console &/or Analytics

**Expected Notice when JS is disabled**
> The Site Kit by Google plugin requires JavaScript to be enabled in your browser.

### Steps
1. Set up Site Kit as normal with JavaScript enabled
1. Ensure each affected area **does not** display the above notice that JavaScript is required
1. [Disable JavaScript](https://developers.google.com/web/tools/chrome-devtools/javascript/disable)
1. Ensure each affected area **does** display the above notice that JavaScript is required

## Changelog entry

* Add user-facing warnings to Site Kit areas when JavaScript is disabled.

**Comment by felixarntz** [comment]
@lucymtc 
> Add `<noscript>` with message to the Screens.php admin_head existing action 

This should be in a `head` action, it needs to be where the actual content markup is generated.

Also, the implementation brief doesn't cover the admin bar menu.

**Comment by lucymtc** [comment]
@felixarntz for the admin pages it is specified to hook into `admin_head`
I have added implementation for admin bar.

**Comment by felixarntz** [comment]
@lucymtc Apologies, I originally wrote exactly the opposite of what I meant:

> This ~~should~~ **shouldn't** be in a `head` action

`<noscript>` tags with the fallback messages should be rendered with the markup exactly where they should appear, for example in the `render_callback()` methods for the screen, or the `Admin_Bar::menu_markup()` method.

**Comment by lucymtc** [comment]
Implementation brief updated

**Comment by felixarntz** [comment]
> Create helper in `includes/Core/Util/` to return the `<noscript>` tag so we have a single source for any different places we need to include the tag.

I think this should be implemented as a trait with a protected method, as it's quite specific. We don't need an own class or public function for that.

**Comment by tofumatt** [comment]
It's worth noting that Puppeteer has `page.setJavaScriptEnabled( false )` so we should be able to write a straightforward E2E test for this one to ensure the right `<noscript>` content is being loaded.

**Comment by aaemnnosttv** [comment]
@felixarntz I updated the IB to include the Activation notice/app since this hadn't changed since July. I also added a point to use CSS to hide loading bars, etc using core's `no-js` class that wp-admin provides. Everything else is the same so I don't think this warrants a full re-review, but please take a look and let us know if there's anything else needed here 👍

**Comment by cole10up** [comment]
**Tested**

Disabled Javascript:

![image](https://user-images.githubusercontent.com/57115907/76389135-d06e8600-6327-11ea-9452-f596df144abe.png)

Confirmed the message is displayed:

![image](https://user-images.githubusercontent.com/57115907/76389240-0b70b980-6328-11ea-9275-9d78bb4ba12d.png)

Passed QA ✅

**Comment by cole10up** [comment]
**Tested**

Site Kit plugin activation notice
![image](https://user-images.githubusercontent.com/57115907/76478418-dd41b700-63c5-11ea-861c-9d126650c30d.png)

Site Kit WordPress dashboard widget
![image](https://user-images.githubusercontent.com/57115907/76478567-59d49580-63c6-11ea-9cde-471010c8105e.png)

Site Kit splash (setup) pages
![image](https://user-images.githubusercontent.com/57115907/76478471-082c0b00-63c6-11ea-90fd-4f2907751d73.png)

Site Kit module dashboard pages
![image](https://user-images.githubusercontent.com/57115907/76478544-40cbe480-63c6-11ea-9513-6e62229629ee.png)

Site Kit main dashboard page - Pass Above

Site Kit settings page
![image](https://user-images.githubusercontent.com/57115907/76478599-7244b000-63c6-11ea-99da-1eaa67e7a1fe.png)

Admin Bar (post edit & post on front) for posts that have data in Search Console &/or Analytics
![image](https://user-images.githubusercontent.com/57115907/76478654-9e603100-63c6-11ea-85ed-e0287a01f27f.png)

**Comment by aaemnnosttv** [comment]
Thanks for the follow up screenshots @cole10up. I think they may be out of order or missing a few though.

To clarify a few things:

* The setup/splash page is where you land if you click _Site Kit > Dashboard_ in the admin menu but it hasn't been set up yet. This one (you labelled as "Activation notice")  
![image](https://user-images.githubusercontent.com/1621608/76499928-4c5fef80-6448-11ea-97e6-91665a251b1f.png)
    - The activation notice is what shows up immediately after activating the plugin on `plugins.php`
* > Site Kit splash (setup) pages  
![image](https://user-images.githubusercontent.com/1621608/76499993-6f8a9f00-6448-11ea-9284-ff3cce98f12e.png)  
    - This is totally out of our hands as it's an `accounts.google.com` URL.

* > Admin Bar (post edit & post on front) for posts that have data in Search Console &/or Analytics
    - Your screenshot here doesn't show that the Site Kit admin bar menu item is there. You'll need to use the developer settings plugin and match the page/post URL to one that has data on the site that you're using in the Custom Site URL. It should essentially look the same as this one from the front-end though:
![image](https://user-images.githubusercontent.com/1621608/76500344-1111f080-6449-11ea-99e9-a033eba598bf.png)
* > Site Kit WordPress dashboard widget
    - This screenshot isn't showing the WordPress dashboard 😄 (`/wp-admin/index.php`)

**Comment by marrrmarrr** [comment]
Verified this message appears on the main dashboard, single page stats, settings page.
