### ISSUE TITLE
Update @wordpress/scripts to its latest version

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1770]
## Feature Description

The `@wordpress/scripts` dependency (currently used on 3.4.0) should be updated to its latest version. The newer versions include / depend on a new `@wordpress/jest-console` package though, which requires us to change many of our Jest tests to account for this change. See https://github.com/google/site-kit-wp/pull/1763#issuecomment-657267120 for more information.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `@wordpress/scripts` should be updated to its latest version (newer than 3.4.0).
* Fix all unexpected console logging in Jest tests. Console logging in any test which is not expected should cause the test to fail.
* There should be no errors on Site Kit screens, and tests should pass (obviously).

## Implementation Brief

* Upgrade `@wordpress/scripts` to the latest version.
* Update javascript tests to explicitly call `expect( console ).toHaveErrored()`, `expect( console ).toHaveWarned()` or `expect( console ).toHaveLogged()` when a console output is expected.
* Remove `muteConsole` calls from all javascript tests.
* Remove `muteConsole` function from `tests/js/utils.js` file.

## QA Brief
* Running `npm run test:js` does not result in any errors or display any unexpected console logging (all console logs should fail tests)
* App functions normally without breakage

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅ , however we should only add the console expect statements if they are actually expected. For cases where an error is logged because e.g. we forgot to intercept a request that we should have intercepted, that should be fixed by intercepting it.

**Comment by aaemnnosttv** [comment]
@caseymorrisus would you please add a QA Brief here as well?

**Comment by tofumatt** [comment]
QA  ✅
