### ISSUE TITLE
Add `getReport` selector to `modules/search-console` store

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1774]
There should be a `getReport` selector issuing an API request to our `GET:modules/search-console/data/searchanalytics` datapoint, which relies on https://developers.google.com/webmaster-tools/search-console-api-original/v3/searchanalytics/query.

While maintaining backward-compatibility, the datapoint should be adjusted to support a range of arguments closer to the original. At the same time, this should happen in a way where similar arguments are named the same way across different report datapoints (e.g. in Analytics or AdSense).

While not yet fully in its intended a state, a good reference here is the [existing `getReport` selector of the `modules/adsense` store](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/datastore/report.js). The one here should be approached similarly.

While the PageSpeed Insights report endpoint is not time-based and generally simpler than the ones here, it's good to have a look at that respective [selector implementation](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/pagespeed-insights/datastore/report.js) too.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/search-console` JS store should expose a selector `getReport( options = {} )`.
    * Should use `createFetchStore` to issue an API request to the `GET:modules/search-console/data/searchanalytics` datapoint.
    * Supported arguments (should all be documented on the selector):
        * `startDate`: Required, unless `dateRange` is provided. Start date to query report data for  as `YYYY-mm-dd`.
        * `endDate`: Required, unless `dateRange` is provided. End date to query report data for as `YYYY-mm-dd`.
        * `dateRange`: Required, alternatively to `startDate` and `endDate`. A date range string such as 'last-28-days'.
        * `compareDateRanges`: Optional, only relevant with `dateRange`. Default `false`.
            * In the future, we will revisit date handling so that we'll do the mapping of start and end date parsing on the client and then use `startDate` and `endDate`. For now, our code should continue to use `dateRange` (and `compareDateRanges` where needed). `startDate` and `endDate` however should already work today, to allow for flexible queries regardless of Site Kit limitations.
        * `dimensions`: Optional. List of dimensions to group results by. See https://developers.google.com/webmaster-tools/search-console-api-original/v3/searchanalytics/query#dimensionFilterGroups.filters.dimension for possible values. Default empty array.
        * `url`: Optional. URL to get a report for only this URL. Default empty string.
        * `limit`: Optional. Maximum number of entries to return. Default 1000.
* The `GET:modules/search-console/data/searchanalytics` datapoint should be modified to support arguments as described above, while maintaining full backward-compatibility. For example:
    * If `startDate` and `endDate` are provided, omit `parse_date_range` logic and set them directly.
    * Support `dimensions` as either array or string (while only the array should be documented).

## Implementation Brief

* Add a the `getReport( options = {} )` selector to `assets/js/modules/search-console/datastore/report.js`.
    * Use `createFetchStore` to issue an API request to the `GET:modules/search-console/data/searchanalytics` datapoint.
    * Supported arguments (should all be documented on the selector):
        * `startDate`: Required, unless `dateRange` is provided. Start date to query report data for  as `YYYY-mm-dd`.
        * `endDate`: Required, unless `dateRange` is provided. End date to query report data for as `YYYY-mm-dd`.
        * `dateRange`: Required, alternatively to `startDate` and `endDate`. A date range string such as 'last-28-days'. These are know values and should result in the relevant startDate and and endDate being set, not sending this string to the API.
        * `compareDateRanges`: Optional, only relevant with `dateRange`. Default `false`. **I'm not sure what this does.**
        * `dimensions`: Optional. List of dimensions to group results by. See https://developers.google.com/webmaster-tools/search-console-api-original/v3/searchanalytics/query#dimensionFilterGroups.filters.dimension for possible values. Default empty array.
        * `url`: Optional. URL to get a report for only this URL. Default empty string.
        * `limit`: Optional. Maximum number of entries to return. Default 1000.
* The `GET:modules/search-console/data/searchanalytics` datapoint should be modified to support arguments as described above, while maintaining full backward-compatibility. For example:
    * If `startDate` and `endDate` are provided, omit `parse_date_range` logic and set them directly.
    * Support `dimensions` as either array or string (while only the array should be documented).

## QA Brief

* Engineering: Ensure described `getReport` selector signature from ACs is matched in the implementation.
* Functionality: Ensure Search Console data displayed does not differ after this issue's PR merged.

## Changelog entry

* Add `getReport( options )` selector to `modules/search-console` store for querying Search Console reports.

**Comment by tofumatt** [comment]
The IB here is _pretty much_ the AC, but I have a question about supporting both `startDate`+`endDate` as well as `dateRange`. If the new selector will only be used by new components and the API will support `startDate`+`endDate`, why bother adding `dateRange` support when the plan seems to be to phase it out and calculate those dates on the client (which is what I'd propose)? It's a more flexible API having generic start and end dates, and supporting both complicates the API a fair bit.

From the ACs and the existing code it's not clear to me what `compareDateRanges` does (there's no accompanying documentation for the param anywhere in the existing code), so I'm not sure how to write the IB for that, but it's (hopefully) minor.

Would you be okay just adding `startDate` and `endDate` support for the new selectors? We could even take common strings as input like `last-28-days` and convert them to send `startDate`+`endDate` in the query params?

**Comment by felixarntz** [comment]
@tofumatt I considered not supporting `dateRange` (and related legacy date args) but this is a different beast and implementing this here would drastically blow up scope of this issue. I don't think supporting both makes the implementation much more complex? It's really only if `startDate` and `endDate` are set, don't use the other, the actual functionality which is the complex part is on the server and already in place.

Regarding `compareDateRanges`, this is also legacy that we have on the server, it basically doubles the days requested. This kind of thing sounds like it's easily replaced by handling on the client and just passing custom `startDate` and `endDate`, but there are several nuances between how this should work because of different API oddities, and that's why we should just keep these legacy arguments for now, as an alternative to the proper `startDate` and `endDate` - we'll migrate towards them separately in the near future.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Removing this from the 1.13.0 release since it should get more testing (mostly because server-side API changes needing to be backward-compatible).

**Comment by felixarntz** [comment]
Removing this from the release since it should get additional time to be in use in `develop`.

**Comment by tofumatt** [comment]
The AC/IB here outlines certain arguments (`startDate` + `endDate`) as required, but it's worth noting that required selector arguments are problematic and we shouldn't have them. But the idea was that one set of arguments or the other work.

In that regard this looks good. I didn't notice a difference in Search Console output when tested, so QA ✅
