### ISSUE TITLE
Improve `getReport` selector of `modules/adsense` store

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1776]
The `getReport` selector as well as the `GET:modules/adsense/data/earnings` datapoint, which relies on https://developers.google.com/adsense/management/v1.4/reference/reports/generate, should be adjusted to support a range of arguments closer to the original. At the same time, this should happen in a way where similar arguments are named the same way across different report datapoints (e.g. in Analytics or Search Console), and the changes need to be fully backward-compatible.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/adsense` JS store selector `getReport( options = {} )` should be adjusted as follows:
    * Supported arguments (should all be documented on the selector):
        * `startDate`: Required, unless `dateRange` is provided. Start date to query report data for  as `YYYY-mm-dd`.
        * `endDate`: Required, unless `dateRange` is provided. End date to query report data for as `YYYY-mm-dd`.
        * `dateRange`: Required, alternatively to `startDate` and `endDate`. A date range string such as 'last-28-days'.
            * In the future, we will revisit date handling so that we'll do the mapping of start and end date parsing on the client and then use `startDate` and `endDate`. For now, our code should continue to use `dateRange`. `startDate` and `endDate` however should already work today, to allow for flexible queries regardless of Site Kit limitations.
        * `metrics`: Required. List of metrics to query. See https://developers.google.com/adsense/management/metrics-dimensions#metrics for possible values. At least one metric is required.
        * `dimensions`: Optional. List of dimensions to group results by. See https://developers.google.com/adsense/management/metrics-dimensions#dimensions for possible values. Default empty array.
        * `orderby`: Optional. Order definition objects containing 'fieldName' and 'sortOrder'. 'sortOrder' must be either 'ASCENDING' or 'DESCENDING'. Default null.
        * `limit`: Optional. Maximum number of entries to return. Default 1000.
* The `GET:modules/adsense/data/earnings` datapoint should be modified to support arguments as described above, while maintaining full backward-compatibility. For example:
    * If `startDate` and `endDate` are provided, omit `parse_date_range` logic and related, and set them directly.
    * Support `dimensions` as either array or string (while only the array should be documented).
    * Add `metrics` support, while for now keeping it optional with the existing default (should not be documented, and the selector in JS should fail without this).
    * Add `orderby` support and map to AdSense API `sort` argument.

## Implementation Brief

* Add a selector `getReport( options = {} )` to a new file `assets/js/modules/adsense/datastore/report.js`.
    * Supported arguments (should all be documented on the selector):
        * `startDate`: Required, unless `dateRange` is provided. Start date to query report data for  as `YYYY-mm-dd`.
        * `endDate`: Required, unless `dateRange` is provided. End date to query report data for as `YYYY-mm-dd`.
        * `dateRange`: Required, alternatively to `startDate` and `endDate`. A date range string such as 'last-28-days'.
        * `metrics`: Required. List of metrics to query. See https://developers.google.com/adsense/management/metrics-dimensions#metrics for possible values. At least one metric is required.
        * `dimensions`: Optional. List of dimensions to group results by. See https://developers.google.com/adsense/management/metrics-dimensions#dimensions for possible values. Default empty array.
        * `orderby`: Optional. Order definition objects containing 'fieldName' and 'sortOrder'. 'sortOrder' must be either 'ASCENDING' or 'DESCENDING'. Default null.
        * `limit`: Optional. Maximum number of entries to return. Default 1000.
* The `GET:modules/adsense/data/earnings` datapoint should be modified to support arguments as described above, while maintaining backward-compatibility. For example:
    * If `startDate` and `endDate` are provided, omit `parse_date_range` logic and related, and set them directly.
    * Support `dimensions` as either array or string (while only the array should be documented).
    * Add `metrics` support, while for now keeping it optional with the existing default (should not be documented, and the selector in JS should fail without this).
    * Add `orderby` support and map to AdSense API `sort` argument.

## QA Brief

* Engineering: Ensure described `getReport` selector signature from ACs is matched in the implementation.
* Functionality: Ensure AdSense data displayed does not differ after this issue's PR merged.

## Changelog entry

* Enhance `getReport( options )` selector in `modules/adsense` store to allow for flexibly querying AdSense reports.

**Comment by tofumatt** [comment]
I think the ACs here largely echo what the IB should be, but I'm proposing we simplify the arguments accepted by the new selector to only be what we want long-term and use Date objects for `startDate` and `endDate` as mentioned in #1775.

**Comment by felixarntz** [comment]
@tofumatt See #1775, let's bring back the legacy arguments to the IB for now.

**Comment by tofumatt** [comment]
Amended to use the legacy args for now 👍

**Comment by felixarntz** [comment]
@tofumatt You had `multiDateRange` in the IB here too, that's only supported by Analytics though, so it's not needed here (I just removed it).

IB ✅

**Comment by felixarntz** [comment]
Removing this from the 1.13.0 release since it should get more testing (mostly because server-side API changes needing to be backward-compatible).

**Comment by felixarntz** [comment]
Removing this from the release since it should get additional time to be in use in `develop`.

**Comment by cole10up** [comment]
**Tested**

Setup latest SK develop, activated Adsense and started adding data confirming revenue numbers matched as well as impressions.

![image](https://user-images.githubusercontent.com/57115907/90722829-69f37980-e270-11ea-9c49-9e955379f526.png)

![image](https://user-images.githubusercontent.com/57115907/90722836-6fe95a80-e270-11ea-92f0-b5a2df1fb170.png)

![image](https://user-images.githubusercontent.com/57115907/90722852-75df3b80-e270-11ea-8ddb-c0f483d009de.png)

Passed QA ✅
