### ISSUE TITLE
Remove debug bar integration

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#178]
Debug bar is currently available, as we implement Site Health we should consider removing it. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The debug bar integration should be removed, because it is useless as it is. If we want to use it, we should invest some time to explore what information it would include for a proper implementation in the future.

## Implementation Brief

* Merge #981.

## Changelog entry

* Remove very limited debug bar integration for now.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Debug bar does not contain a "Site Kit" panel
![image](https://user-images.githubusercontent.com/1621608/71967483-16b24680-320c-11ea-81d7-30926031e958.png)

`Core\Util\Debug_Bar` class has been deleted and no other references to debug bar exist in the codebase.

Moving to Approval.
