### ISSUE TITLE
Prefer sessionStorage over localStorage in googlesitekit-api

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1780]
## Bug Description

The new `googlesitekit-api` appears to choose `localStorage` over `sessionStorage` which should not be the case. I noticed that seeing the PSI API responses now appearing in `localStorage` while before they used to be in `sessionStorage` (which should be the case unless `sessionStorage` is not available).

Our legacy `dataAPI` rightfully prefers `sessionStorage` usage over `localStorage` usage. The only thing that should be stored in `localStorage` is the total notifications count, which is a special case that should bypass the API layer anyway (as it currently already is).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit-api` cache layer should preferably use `sessionStorage` over `localStorage` if available.

## Implementation Brief

* In `assets/js/googlesitekit/api/cache.js`, change the order of the two elements in `defaultOrder`, so that `sessionStorage` is attempted first.

## QA Brief

* 

## Changelog entry

* Fix new JS API layer to prefer `sessionStorage` over `localStorage` for caching.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: 

Confirm, all data is stored in the session storage now. There is only `googlesitekit::total-notifications` record in the local storage.
