### ISSUE TITLE
As we onboard asking users what their goals are to determine which modules we should recommend.

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#179]
Discussed during the initial build of Site Kit, goal is to help users understand their goals (increase traffic, more CTA conversions) and then suggest modules to they should set up as part of the set up flow instead of having them set up post Site Kit set up. 

Would be a great way to expose users to Google products they might not know about.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
This was already implemented as part of the User Input feature, so it's no longer relevant. 
But none of the "reasons for closing" labels apply in this case (cc @felixarntz to consider whether we want to add an "outdated" or "no longer relevant" closing label).
