### ISSUE TITLE
Search Console Verification Error by Google Tag Manager

### ISSUE THREAD

**Issue by immdraselkhan** [google/site-kit-wp#1790]
Here are the details of the error https://www.loom.com/share/81e32822a5fd4a9fba6970650dc36982
I'm sorry for the little bit longer video.

**Comment by immdraselkhan** [comment]
So did you reviewed it?

**Comment by jamesozzie** [comment]
@immdraselkhan Thanks for sharing and apologies for the delayed response. To clarify you're unable to verify your Tag Manager account with your Search Console property? From a brief look of the video it seems the same issue occurs when you manually place your Tag Manager code snippets into your theme.

**Comment by immdraselkhan** [comment]
First I tried but automatically doesn't work, then I tried manually and the same issue.

**Comment by jamesozzie** [comment]
@immdraselkhan I understand. As this is a Search Console issue as opposed to Site Kit specifically you can check with the product experts using the [Search Console help center](https://support.google.com/webmasters/?hl=en#topic=9128571).

I noticed also others reported the same issue [here](https://support.google.com/webmasters/thread/43572874?hl=en), which may be of use. 

If you happen to encounter any Site Kit specific queries feel free to [create a post](https://wordpress.org/support/plugin/google-site-kit/#new-post) in our WordPress support forum, where we'd be happy to assist.
