### ISSUE TITLE
Update backstopjs package to the latest version

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#1794]
## Feature Description

The backstopjs dependency should be updated to its latest version. The newest version contains different improvements and bug fixes which can improve the quality of our VRT tests. In particular it can catch the error which is ignored by the current version of backstop:

![failed_diff_google-site-kit_Dashboard_Search_Funnel_0_document_1_medium](https://user-images.githubusercontent.com/873049/87697473-cc051e80-c79a-11ea-961f-2cf6decd5b02.png)
_The reference image ([medium screen only](https://raw.githubusercontent.com/google/site-kit-wp/develop/tests/backstop/reference/google-site-kit_Dashboard_Search_Funnel_0_document_1_medium.png)) contains 2.1k unique visitors when it should be 0 (like on other screens: [large](https://raw.githubusercontent.com/google/site-kit-wp/develop/tests/backstop/reference/google-site-kit_Dashboard_Search_Funnel_0_document_2_large.png) and [small](https://raw.githubusercontent.com/google/site-kit-wp/develop/tests/backstop/reference/google-site-kit_Dashboard_Search_Funnel_0_document_0_small.png))._

Also, looks like the latest version of backstopjs uses puppeteer which renders fonts and graphs (like on the screenshot above) slighly different to the current version. It causes a lot of failures which we need either accept or figure out whether or not we can configure puppetteer/backstopjs to use the same rendering approach.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* [`backstopjs`](https://www.npmjs.com/package/backstopjs) should be upgraded to the latest stable version (currently 5.3.0)

## Implementation Brief

Approve and merge this PR https://github.com/google/site-kit-wp/pull/3212

Differences are much less than initially anticipated

(Visual diffs are on comment here https://github.com/google/site-kit-wp/issues/1794#issuecomment-824771536 )

## QA Brief

This is an infrastructure ticket that only targets testing so as long as the Pull Request passes all the tests then this ticket is done

Check the difference between the old and new backstop images (as GitHub doesn't show image diffs)

## Changelog entry

* N/A

**Comment by danielgent** [comment]
@eugene-manuilov @aaemnnosttv I had a go at upgrading backstop and I created a PR where I accepted the changes and it is passing

I might be missing something as the description alluded to there being many errors but there were only 5 (approved and on the PR, but I'm pasting the diffs here)

![checkboxes](https://user-images.githubusercontent.com/8496063/115709491-9288c180-a371-11eb-9610-0a108890f5fe.png)
![checkboxes-2](https://user-images.githubusercontent.com/8496063/115709492-93215800-a371-11eb-8578-3e91113d41f6.png)
![checkboxes-3](https://user-images.githubusercontent.com/8496063/115709493-93215800-a371-11eb-814c-b2a4d1f539c5.png)
-
![external-link-icon](https://user-images.githubusercontent.com/8496063/115709495-93215800-a371-11eb-845e-3210967c28de.png)
![select-direction](https://user-images.githubusercontent.com/8496063/115709497-93b9ee80-a371-11eb-95ff-300bff046f37.png)

**Comment by danielgent** [comment]
See the passing PR here https://github.com/google/site-kit-wp/pull/3212
Eugene mentioned there would be icon differences.   

It's odd that the select opens upwards though if the viewport changes.

I was expecting a lot more!  What do you both think @eugene-manuilov @aaemnnosttv ? Happy to upgrade like this and approve these changes?

**Comment by eugene-manuilov** [comment]
This ticket was created quite a while ago and at that time we had more VR issues. If there are just 5 at the moment, it's good for us and we can upgrade backstopjs :tada: 

> Happy to upgrade like this and approve these changes?

Yes, looks like all of these changes are caused by using a different version of the browser which is expected, so we can approve it.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@danielgent please remember to always add a QA Brief with a PR when including one as part of the IB. Once added you can simply un-assign yourself 👍

**Comment by johnPhillips** [comment]
QA ✅
- Verified the version of backstop has been updated
- Manually checked the updated images
- Ran VRT tests to double check and they all passed
