### ISSUE TITLE
Add ability to anonymise IP address for Google Analytics 

### ISSUE THREAD

**Issue by gx10** [google/site-kit-wp#18]
The default GA snippet implementation doesn't add the option to anonymise IP addresses, which is required in some countries, for example the EU. 

For all cases where Site Kit places the GA snippet on behalf of the user, we should enable this by default. (Site Kit can't update the snippet for sites where it was already placed via another plugin or other method.) 

## Steps to QA

Ensure the functionality in the AC/IB works, but it's worth additional QA on an existing site that upgrades to this functionality, because it introduces a new setting with a default.

1. Create/use an existing site with Analytics enabled before updating to a version of the plugin with this commit.
2. Ensure the HTML/analytics tag output does not include `"anonymize_ip":true`
3. Update the version of the plugin to one with this change.
4. Check the HTML source; it should _now_ include `"anonymize_ip":true`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
For cases where there is no pre-existing GA snippet detected on the site and the user decides to let Site Kit place the GA snippet on their behalf, check if the site is primary AMP. 
* If yes, no need for further action. 
* If not:
    * When placing the snippet, add the `anonymize_ip` parameter to anonymise IP addresses ([details here](https://gist.github.com/felixarntz/2800ed9abfa13aabfa6e5c8ba9ec5066)) 
    * In the Analytics settings section, add a toggle (on by default) with the text "Anonymise IP address". 
<img width="345" alt="Screenshot 2019-12-05 at 17 33 45" src="https://user-images.githubusercontent.com/13304791/70254586-9d937f80-1785-11ea-9c83-a474750887f3.png">
* If the user chooses to switch this off, remove the parameter from their GA snippet and update the toggle text to "IP address anonymization is disabled." 

## Implementation Brief

* Add a toggle (on by default) to enable "Anonymize IP" functionality in `assets/js/modules/analytics/setup.js` with the text:
```jsx
<Switch label={ __( 'Anonymize IP Address', 'google-site-kit' ) } />
<p>{ __( 'IP addresses will be anonymized.', 'google-site-kit' ) }</p>
```
* The above switch should only be available on the change/edit screens—not during setup.
* Add a setting to the `Modules/Analytics.php` code for anonymizing IP addresses. This should be enabled by default on updates to respect GDPR—existing users will have the feature on-by-default like new users would.
* If the anonymous IP setting is enabled, add to `enqueue_gtag_js` in `Modules/Analytics.php`.
```php
$anonymize_ip_address = $this->get_data( 'anonymize-ip-address' );
if ( ! is_wp_error( $anonymize_ip_address ) && $anonymize_ip_address ) {
    // See https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization.
    $gtag_opt['anonymize_ip'] = true;
}
```

## Changelog entry

* Anonymize IP addresses by default in Google Analytics snippet, and grant the user control to modify with a new setting.

**Comment by jamesozzie** [comment]
@gx10 You can use the [relevant help center](https://support.google.com/analytics/answer/2763052?hl=en) for information on Analytics specifically. Site Kit displays a dashboard with basic information from your Analytics account only.

**Comment by gx10** [comment]
Hi James, 

Thank you for your reply. 

But SiteKit did inject the Analytics code in our website ... not just display the dashboard.

And I was looking to configure the code injection so that is works as in the article you mentioned.

Thanks,

Andrei

**Comment by sviluppomania** [comment]
@jamesozzie 
Hello,
you should add the possibility to anonymize the IP address between the settings (Google Analytics) of the plugin, other plugins that integrate Analytics grant this possibility.

**Comment by jamesozzie** [comment]
I have marked this as an enhancement for further investigation

**Comment by gx10** [comment]
Thanks! Is there some code we can use for now to stop SiteKit injecting Analytics code? Because now it injects gtag/js and we want to use the Universal Analytics on the pages, but still have the Analytics Dashboard from SiteKit

**Comment by ivankristianto** [comment]
@gx10 
I believe you can remove the gtag inserted by site kit by following these steps:
1. Go to Site Kit settings
2. From Connected Services Tab, expand Google Analytics module, and click edit.
3. You can choose to remove snippet then Confirm changes.
See the screenshot below:
![Image 2019-06-21 at 21 09 37](https://user-images.githubusercontent.com/656006/59928550-30a35c00-9469-11e9-861d-c27a59b8ff63.png)

Let me know if it's fix your issue.

**Comment by gx10** [comment]
Thank you.

It didn't work because it wasn't displaying my account. Only that analytics
is connected. And the edit button wasn't working.

I disconnected it. And when I reconnected it said it detected that we
already use an analytics ID and that it will connect with that. (We
injected the code through another plugin in the mean time, so we can have
anonymous ips)

So it looks good now.

Thanks!

Andrei



În vin., 21 iun. 2019 la 17:12, Ivan Kristianto <notifications@github.com>
a scris:

**Comment by 24Degrees** [comment]
Isn't this the same issue as #33?

**Comment by gx10** [comment]
Yes, but 33 is a copy of this :)

**Comment by felixarntz** [comment]
Thanks @gx10, customizing Analytics parameters for the inserted snippet is indeed not supported currently. We've opened #55 and #56 to start a discussion on providing options there. Anonymizing IPs would be a crucial piece of that.

**Comment by gmmedia** [comment]
Yes anonymizing IPs is very important.
It should be the default setting, because the use of Analytics without anonymizing is illegal in Europe.

**Comment by tofumatt** [comment]
IB added; note that the text differs from the one in the AC. The AC doesn't provide context as to what IP anonymisation is or why it's important. I think it's useful to explain this setting to users if we're going to provide it. It should look something like:

<img width="697" alt="Screenshot 2019-12-06 11 09 06" src="https://user-images.githubusercontent.com/90871/70318928-0c6de880-1819-11ea-864f-a8259a7f5aac.png">

All that said: what's the benefit to providing this as an option to users? This setting is required under GDPR, so making it the default for users who don't have more custom needs (and would likely confuse some users). When would a user ever _want_ to collect full IP addresses?

**Comment by felixarntz** [comment]
@tofumatt 
> The AC doesn't provide context as to what IP anonymisation is or why it's important. I think it's useful to explain this setting to users if we're going to provide it.

This is on the user. We should not provide any information that goes into legal territory because we cannot guarantee that this is sufficient to satisfy GDPR requirements. Please update the IB to use the text as outlined in the ACs.

> When would a user ever _want_ to collect full IP addresses?

We thought about not exposing a toggle and just enabling it, but we need to stick to the conventions that the respective Google service has established for that. We'll use a solid default, (as mentioned below) but there may actually be people that do not want this to be enabled.

> The above switch should be available on setup and change/edit screens.

As noted in the ACs, this should only appear in settings, not setup. It should default to true though, so users are always on the "safe" side by default, even if they don't see the setting (for example when they never visit settings after going through the setup).

Also (I know this may not necessarily end up like that, but it was in your code snippet), let's use camel-case names for options (let's use `anonymizeIP` instead of `anonymize-ip-address`).

**Comment by tofumatt** [comment]
The text I proposed doesn't actually suggest that it makes the website entirely compliant, but merely outlines that anonymising IP addresses is a requirement under GDPR. I don't think that we should say that ticking that box ensures your site is 100% GDPR-compliant, but it's a very relevant detail and common question for users of analytics, and saying it's *a* requirement helps clarify the toggle's purpose without being legal advice/a guarantee.

It could be nice to at least have a link to learn more about IP anonymisation if the plugin can't provide any reason for the toggle in its own text. I guess we could use https://support.google.com/analytics/answer/2763052?hl=en&ref_topic=2919631 or https://support.google.com/analytics/answer/2905384?hl=en&ref_topic=2919631, but neither provide _reasons_ to use IP masking—simply what it is and how it works.

If the default is "on" that helps, but I think we should clarify this text or remove the option going forward. 🤷‍♂

---

I did change the text slightly in the IB from being a repeat of the label for the toggle. Replicating the label text is confusing and not good accessibility practice, so I've changed it to say `<p>{ __( 'IP addresses will be anonymized.', 'google-site-kit' ) }</p>`—it would say "IP addresses will not be anonymized." when disabled.

**Comment by felixarntz** [comment]
@tofumatt I like the new label.

IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr One thing I noticed while reviewing this is that now that Analytics is getting more settings, it would be good to revisit the styling of setting labels, section "headings", and descriptions as these are nearly identical stylistically.

![image](https://user-images.githubusercontent.com/1621608/70694357-16d02c80-1cc8-11ea-8113-41fd7f9c66cd.png)

The setting for `useSnippet` would likely be better as a switch (like the others). The radio buttons actually make it a bit more difficult to quickly understand whether or not the snippet is being output or not because it requires to you read everything. This is especially inefficient as the whole wording of the option changes depending on the saved value.

Also note the description text for the anonymize IP addresses has the exact same treatment as the section heading for the list of tracking exclusions from Analytics, which is visually confusing.

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

### Behavior ✅ 
* Tested that anonymization defaults to enabled
* Tested that setting is only displayed in module settings, not during set up
* Tested that setting value works as expected both when on and off

### Appearance ⚠️ 
* No space between setting description and _Learn More_ link (hovered to better show spacing issue)  
![image](https://user-images.githubusercontent.com/1621608/70897362-1d79df00-1ffb-11ea-8d50-c14e9349ca0f.png)  
![image](https://user-images.githubusercontent.com/1621608/70897430-469a6f80-1ffb-11ea-86fd-d5bb6c819fa9.png)

**Comment by felixarntz** [comment]
@tofumatt Can you open a follow-up PR to address the above?

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Picking up where the [first round](https://github.com/google/site-kit-wp/issues/18#issuecomment-565988820) left off, the spacing issue has been corrected. No remaining issues.

![image](https://user-images.githubusercontent.com/1621608/70929873-ad8c4880-203c-11ea-8c48-411820a97129.png)

Moving to approval.

**Comment by marrrmarrr** [comment]
👁👍
