### ISSUE TITLE
Errors in batch requests are cached when they shouldn't be

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1800]
## Bug Description

The legacy dataAPI is still used for performing batch requests using `dataAPI.combinedGet`. When the responses for each request are received we call `handleWPError` which identifies error responses and performs error-specific actions.

https://github.com/google/site-kit-wp/blob/c776b09354e40612462c88fa6128e6878c24f172/assets/js/components/data/index.js#L185-L192

Unfortunately, nothing is currently done to prevent these error responses from being cached as we do with other responses. This leads to an error message potentially lasting in the dashboard for an extended period of time until the cache expires and the request is retried.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any `WP_Error` response in a batch request should not be cached

## Implementation Brief

* Extract `WPError` from `dataAPI.handleWPError` identification logic to a new `isWPError` utility
* Update `dataAPI.combinedGet` result iteration to only call `dataAPI.handleWPError` if `isWPError`  
	- If `isWPError`, the call to `setCache` should be skipped
* `dataAPI.get` does not need to use `isWPError` since `catch` will always receive an error
* Remove "is error" logic from `dataAPI.handleWPError` as it will only be called with an error now

## QA Brief

* Set up Site Kit and navigate to the dashboard
* Configure an error to be returned in a batch request (e.g. update `GET:searchanalytics` handler to throw an exception)
* Delete keys in session storage for the modified datapoint (e.g. `googlesitekit_modules::search-console::searchanalytics::*`) or just clear your entire session storage
* Reload the page
* See the error as a warning about a WP_Error in the data response
* Inspect the cache in session storage to make sure the error was not cached (not present in the session storage)

## Changelog entry

* No longer cache API response errors within batch requests.

**Comment by felixarntz** [comment]
IB ✅

**Comment by ryanwelcher** [comment]
I am not seeing any errors in session storage. QA ✅
