### ISSUE TITLE
Upgrade dealerdirect/phpcodesniffer-composer-installer to latest version

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1802]
## Feature Description

The composer package `dealerdirect/phpcodesniffer-composer-installer` is currently installed at `0.5.*` with the latest version at `0.7.0`. This is probably a simple upgrade but was not done as part of #1356 due to the version constraint.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `dealerdirect/phpcodesniffer-composer-installer` is upgraded to the latest version possible

## Implementation Brief

* Run `composer require dealerdirect/phpcodesniffer-composer-installer` to install the latest version compatible with other dependencies

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
