### ISSUE TITLE
Husky pre-commit hooks no longer work when using an app

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1803]
## Bug Description

In #1356 we upgraded many project dependencies including Husky to the latest version. The current version of Husky is known to have a problem with git hooks not running when committing via a GUI/app.

See https://github.com/google/site-kit-wp/issues/1356#issuecomment-659528824

## Steps to reproduce

1. Make an arbitrary change to the code
1. Stage the changes
1. Commit the changes using a GUI git client (e.g. GitHub Desktop) with an invalid commit message (e.g. "asfsdfsfs")
1. Commit succeeds

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Husky commit hooks should work when committing via CLI and with most popular git client apps

## Implementation Brief

* Downgrade `husky` to v`3.x`

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

GitHub Desktop showed an error with a bad commit.
GitHub Desktop allowed a legitimate commit message 👍
