### ISSUE TITLE
Do not run ZIP and Storybook build workflows on PRs from forks

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1818]
## Bug Description

The GitHub actions for building ZIP files and building Storybook currently run on every PR, regardless of origin. This causes a problem for forks because usually those contributors do not have access to push to the wiki or to the `gh-pages` branch. Let's modify the GitHub actions so that they only run on PRs that come from the original `google/site-kit-wp` repo.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* GitHub actions to build and deploy ZIP files and build and deploy Storybook should only run on PRs from `google/site-kit-wp` branches, but not on PRs that come from forks.

## Implementation Brief

* Update job `if` conditions for the following jobs to prevent running when triggered by forks
    - `build-storybook`
    - `build-zips`
    - `remove-pr`
    - `remove-storybook`
* Include the following logic in the `if`
    - If the job already has an `if` condition, include this with `&&`  
    ```yml
    if: ( existing condition ) && github.event.pull_request.head.repo.fork == false
    ```
    - Otherwise, add the `if` to the job including the status function which is `success()` by default  
    ```yml
    if: success() && github.event.pull_request.head.repo.fork == false
    ```
* Deploy jobs depend on build jobs so they do not need added conditionals

Note: "When you use expressions in an if conditional, you may omit the expression syntax (`${{ }}`) because GitHub automatically evaluates the if conditional as an expression."

Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif

**Suggested minor enhancements**
* Combine `build-zips` and `remove-pr` into a single `google-site-kit-zips.yml` workflow, similar to how the Storybook workflow contains `build`, `deploy`, and `remove` jobs
* Rename `build-storybook.yml` to `storybook.yml`
* Update workflow `name`s to be a user-facing name, e.g. "Storybook" or "Plugin Zip Files" as currently it has the same name as a job, which can be confusing when referencing a job id whether a job or a workflow is being referred to

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅ 

The renaming/reorganizing suggestions sound good to me as well.

**Comment by tofumatt** [comment]
QA ✅

Checks were skipped for a user without write permissions:

<img width="974" alt="Screenshot 2020-07-29 at 14 46 48" src="https://user-images.githubusercontent.com/90871/88808218-7c671f80-d1aa-11ea-94ea-5e93af7a8b18.png">

https://github.com/google/site-kit-wp/pull/1844
