### ISSUE TITLE
Improve (by reducing) how much the frontend iframe to check for existing tags is loaded

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#182]
For reference: https://github.com/10up/googlesitekit/pull/689#discussion_r291471198

Currently the iframe is loaded whenever you are on the Settings page when Analytics is active. That should not be the case for performance reasons, it would be better to really only load it when it's needed, i.e. when the user actually starts editing Analytics settings. Probably we could improve this globally so that the iframe is simply always inserted via JavaScript whenever it needs to be loaded - that would be the most solid solution IMO because it wouldn't rely on making assumptions in PHP.

Ideally we inject the iframe dynamically to avoid loading it at all until we need to actually check for a tag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by lucymtc** [comment]
noting here iframe is no longer loaded, we currently check tag existence with fetch request https://github.com/google/site-kit-wp/pull/82 results are saved in sessionStorage

**Comment by aaemnnosttv** [comment]
@lucymtc is this issue no longer relevant? If so, then let's close it.

**Comment by marrrmarrr** [comment]
Felix and I discussed. Closing.
