### ISSUE TITLE
Duplicate batch requests fired, resulting in short-term quotas being exceeded

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1828]
## Bug Description

In `develop` we currently fire the same batch request twice. While this is of course clearly a bug and regression, it also can result in short-term quotas being exceeded, particularly some of the Analytics queries often return a 429 with "profileId xyz has too many concurrent connections". The additional batch request being made is the exact same in every case, so it's definitely a duplicate which should not happen.

This happens on any Site Kit page where we issue batch requests. It does however _not_ happen for the batch request for the WP dashboard, so there has to be something that causes this in our screen logic.

This has been working fine before (including the latest 1.12.0 release), so it's a high priority regression to fix before we can release 1.13.0.

Let's see which of our recent changes introduced this duplicate request.

Potentially related: #1406 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit screens should only fire a single batch request on pageload.

## Implementation Brief

The problem is due to module data being reset and loaded again by the effect we introduced in the `DateRangeSelector`.

We can clean this up significantly and fix the bug by moving this behavior to the dedicated `CollectModuleData` component.

* Merge #1832 

## QA Brief

* 

## Changelog entry

* N/A

**Comment by cole10up** [comment]
**Tested**

Was able to reproduce this issue while regressing https://github.com/google/site-kit-wp/issues/1836

Installed latest SK develop, ran the same test - confirmed short term quota issue was not present.

![image](https://user-images.githubusercontent.com/57115907/88621940-7c560b00-d056-11ea-8951-0b459cf713e6.png)

Passed QA ✅

**Comment by aaemnnosttv** [comment]
@cole10up the important thing to check for is that duplicate requests to `wp-json/google-site-kit/v1/data` are no longer made. The quota error is important but more of a symptom and may not happen every time.

You'll want to check that the page loads without making duplicate requests to this endpoint. It's not uncommon for it to be requested twice on page load (particularly if PSI is active), but with different request data (i.e. not duplicate).
