### ISSUE TITLE
Site Kit service uses https callback for non secure sites

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1833]
During Site Kit setup on a _**http**_ site when there is a security certificate available but not in use Site Kit setup fails at the final callback stage, with the callback URL referencing the https site.  

**Default site (WP), with no redirection to secure URL** 

![image](https://user-images.githubusercontent.com/41326532/88383149-db3f2a00-cda1-11ea-9dec-8ee934f13919.png)

**Default https URL (with a holding page)**

![image](https://user-images.githubusercontent.com/41326532/88383016-94e9cb00-cda1-11ea-833c-1de4bb97b984.png)

**Both General Settings URLs displaying http**
![image](https://user-images.githubusercontent.com/41326532/88383384-5274be00-cda2-11ea-8012-2c261773d3d5.png)

**Setup experience**

![http_https](https://user-images.githubusercontent.com/41326532/88382269-04f75180-cda0-11ea-83fb-7db1a8415877.gif)

While the issue may be attributed to hosting configurations/no redirection in place, if a user has http defined in their general settings the Site Kit service (and therefore callback) should utilize the http schema or perform a check other than _is https available_ to allow setup to proceed. 

This may occur in the following scenario:
1. A site has a https certificate available, but WP site is http (also defined in their general settings) 
2. There is no redirection in place, with a default placeholder for https content
3. A user logs into their non secure admin panel
4. They start the Site Kit setup process

## Additional Context

 - Support created ticket, can reproduce/provide access
 - Default document at host level for domain is index.php
 - Combined http/https directory setup at host level

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by pablosfc1** [comment]
Yes, I had this problem. Then I have Cloudfare with HTTPS forced. But at configure the plugin Site Kit shown me the message "encountered an error: Loading chunk 3 failed." Additionally I had to activate the Really Simple SSL plugin in Wordpress, then the Google Site Kit it's functioning ok now.

**Comment by adamsilverstein** [comment]
@jamesozzie Can you still re-produce this issue on the latest version after resetting? If your site is `http` we should be setting you up that way. If you change from `http` to `https` we should do a better job detecting that and helping you reset the connection to use `https`.

**Comment by jamesozzie** [comment]
Performed another test on separate  site. See below findings, happy to share a login or test on another site

1. Created a new WordPress install on a domain that had both http / http versions available (no redirection in place)
2. Setup SK on http version of admin dashboard, setup worked fine (SC only, no other modules connected)
3. Accessed secure version of admin panel, SK dashboard displayed data fine
4. Checked SH info, connected site remained as non secure version (http)
5. I then added redirection (forcing all traffic to https) at host level (no plugins usage)
6. Confirmed non secure version of website is inaccessible (front end or admin panel)
7. Site Kit remained working fine although at no stage was I asked to reconnect or at no stage was there detection of a new URL after using https

**Comment by adamsilverstein** [comment]
> I then added redirection (forcing all traffic to https) at host level (no plugins usage)

So at this point, you didn't change the URL used in WordPress, right? eg. it remained set to the the "http" version of the site?

In this case, this is the 'expected' behavior. We only detect when the apparent URL of the site changes, and the server based redirect you added does not do that.

Is there an issue we can resolve or behavior we can improve here?

**Comment by jamesozzie** [comment]
All looks good to me. In one setup today I switch from http and https and I got the notification about the new URL, suggesting I reconnect. All looks good, no further action required.
