### ISSUE TITLE
Consistent index.js file in component directories

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#1838]
## Feature Description

After refactoring in #1654, it turned out that not all directories have sufficient index.js files. We need to create or update index.js files in all component directories to make it consistent accross all directories. A sufficient index.js exports all components in the folder using named exports. The following is the list of directories that need to be updated.

#### Directories with insufficient index files:

- `adsense/components/dashboard`
- `analytics/components/settings`
- `optimize/components/settings`
- `pagespeed-insights/components/settings`
- `search-console/components/settings`
- `tagmanager/components/common`

#### Directories without index files:

- `analytics/components/adminbar`
- `analytics/components/dashboard-details`
- `analytics/components/wp-dashboard`
- `pagespeed-insights/components/common`
- `pagespeed-insights/components/dashboard`
- `search-console/components/adminbar`
- `search-console/components/dashboard-details`
- `search-console/components/dashboard`
- `search-console/components/wp-dashboard`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Every `modules/*/components` subdirectory should have an `index.js` file which exports all components in that directory.

## Implementation Brief

* Add test to ensure module index consistency (https://github.com/google/site-kit-wp/commit/323fc9703ee5b0be47608a726e0524e963a9e4a3)
* Add missing index modules and exports as identified by running `npm run test:js:watch -- --coverage=false assets/js/modules/index.test.js`
* Finish and merge #1954
	- The above PR only has the added test which will currently fail, all the index modules and exports just need to be added

## QA Brief

* `npm run test:js:watch -- --coverage=false assets/js/modules/index.test.js` should pass 😄 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

Created a folder with files that should cause a violation to be raised and both ESLint and the Jest test complained 👍🏻
