### ISSUE TITLE
When you don't have enough data, and switch to 7 days and then back to larger data it shows an error that the data isn't available

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#184]
Noticed this on my site. I don't have any data from the last 7 days so when I switch to the last 7 days it rightly shows and error. When I switch back to 14, 28 or 90 days the error still displays.

Steps to recreate:
1) View dashboard (or module page) as normal
2) Switch to 7 day view - receive gathering stats message
3) Switch to 14, 28 or 90 day view - receive gathering stats message above the graph

Currently I get:
<img width="1243" alt="5e154a77a53dc159dd71b39ea1991787" src="https://user-images.githubusercontent.com/28811945/61000790-d12bc400-a323-11e9-9799-89876f805962.png">
I expect to get:
<img width="1310" alt="5e212abcb4c5fb8e7c92dff5cbfcc85a" src="https://user-images.githubusercontent.com/28811945/61000798-d557e180-a323-11e9-9e76-0cfa79d575cc.png">

Currently I get:
<img width="1248" alt="5e239c58c61eb62b904436db7d275509" src="https://user-images.githubusercontent.com/28811945/61000831-e9034800-a323-11e9-99cc-0e2d4a87a9eb.png">

I expect
<img width="1310" alt="5e2c4a6691ce5336456560b70247c020" src="https://user-images.githubusercontent.com/28811945/61000839-edc7fc00-a323-11e9-95c2-8f6d3aa7f08c.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* "Gathering data" message should only be displayed for views where there's no data returned from the API.

## Implementation Brief

* Set `zeroData` in state any time new data is loaded.
* Merge #1876

## Changelog entry

* Fix bug where state of not having sufficient data for a Site Kit widget would sometimes incorrectly persist when switching the date range.

## QA Brief

* Test that switching between an empty view and a populated view does not display the error as pictured in https://github.com/google/site-kit-wp/issues/184#issuecomment-668780740
* This state can be hard to reproduce; if you want a copy of cached `sessionStorage` data to test it, ping me and I can send you some privately. The data I have been testing with needs to be anonymised so I don't want to post it here 😄

**Comment by felixarntz** [comment]
Related: #447 

Potentially this will already fix it.

**Comment by ThierryA** [comment]
Moving this to IB as it doesn't have an estimate

**Comment by felixarntz** [comment]
Let's check if this is still relevant after the latest changes to the date range selector. I prioritized this for the upcoming release since we should fix it if still a problem, but it could be that it already got fixed by now - in that case this should be closed.

**Comment by tofumatt** [comment]
This does still happen with the new datepicker, at least on legacy pages that are using `withData`:

![2020-08-04 20 24 03](https://user-images.githubusercontent.com/90871/89335921-93b57980-d690-11ea-88d8-b724915ca7de.gif)

**Comment by tofumatt** [comment]
Just posting here to document what I'm finding, as this wasn't very intuitive to me. It looks like this `setState` call:

https://github.com/google/site-kit-wp/blob/897c92e479c3577ceceb3355b8c58c5c7287c4e3/assets/js/components/higherorder/withdata.js#L196

Isn't properly "reset" when the date range changes, meaning the empty "Last 7 Days" request sets a `zeroData` state in the component, which isn't reset when switching back to "Last 28 Days". Resetting that when the date range changes should fix things, just need to figure out where to do that appropriately here.

**Comment by tofumatt** [comment]
This one was much tougher to track down than implement, so PR is ready and the IB is set to review. Turns out: it was still happening! 😄

**Comment by aaemnnosttv** [comment]
IB ✅ but the fix needs tweaking - will follow-up in code review.

**Comment by cole10up** [comment]
**Tested**

Installed latest SK release candidate, activated and setup.

Activated Analytics with on a site with not enough data:

![image](https://user-images.githubusercontent.com/57115907/90111622-c3edbf80-dd03-11ea-98b3-e58bb859ac6e.png)
![image](https://user-images.githubusercontent.com/57115907/90111655-cd772780-dd03-11ea-9103-690eca2fa655.png)

Dashboard:
![image](https://user-images.githubusercontent.com/57115907/90111695-de279d80-dd03-11ea-88de-74570152f855.png)
![image](https://user-images.githubusercontent.com/57115907/90111719-e41d7e80-dd03-11ea-9fa1-f3a32837b031.png)
![image](https://user-images.githubusercontent.com/57115907/90111735-eaabf600-dd03-11ea-8813-67af60853104.png)

![image](https://user-images.githubusercontent.com/57115907/90110669-6efd7980-dd02-11ea-8937-c6fc06129a2b.png)

Adjusted the duration of the data for an existing site:

![image](https://user-images.githubusercontent.com/57115907/90110760-93595600-dd02-11ea-82ab-ecf6fa6aa84d.png)
![image](https://user-images.githubusercontent.com/57115907/90110887-bb48b980-dd02-11ea-8bf6-68c72502c94c.png)
![image](https://user-images.githubusercontent.com/57115907/90110913-c3085e00-dd02-11ea-9459-a3fefe0908d7.png)
![image](https://user-images.githubusercontent.com/57115907/90110945-ce5b8980-dd02-11ea-8250-eb104c5323c3.png)

Passed QA ✅
