### ISSUE TITLE
Update issue and pull request templates

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1845]
## Feature Description

Currently the issue templates do not have any mention of tests. This could be improved by adding a section or at least a comment to the Implementation Brief section indicating any proposed test coverage additions, changes, which kind of tests, whether or not VRT changes are expected or not. This is all valuable information to include for the implementation and should result in better collaboration between engineers if the engineer executing an issue is different than the one who defined it. It's also useful for producing better-informed estimates.

The PR template should also be updated to include a checkbox to make sure that the QA Brief for the source issue is filled out and up-to-date.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The issue template should include additional sub-headings under "Implementation Brief":
    * Heading "Test Coverage"
       - For the bug report template:  
       `<!-- One or more bullet points for how to implement automated tests to verify the issue is resolved. -->`
       - For the feature template:  
       `<!-- One or more bullet points for how to implement automated tests to verify the feature works. -->`
    * Heading "Visual Regression Changes"  
    `<!-- One or more bullet points describing how the feature will affect visual regression tests, if applicable. -->`
* The pull-request template should include an additional checkbox as second-to-last entry:  
`I have added a QA Brief on the issue linked above.`

## Implementation Brief

* Add the new sections (above) for Implementation Brief to https://github.com/google/site-kit-wp/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md and https://github.com/google/site-kit-wp/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md
* Add the additional checkbox (above) to https://github.com/google/site-kit-wp/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

## QA Brief

* Create a new "bug report" issue with our template and verify the new content above appears
* Create a new "feature" issue with our template and verify the new content above appears
* Create a test PR and ensure it includes the new QA checkbox

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅ 

@tofumatt Shouldn't this really be a 1 hour estimate? I feel like if this isn't then nothing is 😆

**Comment by tofumatt** [comment]
Tested both new issue templates and a test PR. All templates updated and appeared as expected.

QA ✅
