### ISSUE TITLE
Display permissions error notification when missing Site Kit service requirements

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1848]
## Feature Description

Follow-up to #1646: When any of the errors with a `data.reconnectURL` present is returned from an API call (e.g. `missing_verification`, `missing_delegation_consent`, `missing_search_console_property`), that error should also be surfaced in a top-level notification in the dashboard since it will affect _all_ API calls by definition.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For API errors that have a `data.reconnectURL` present, the API layer should trigger a top-level notification on the Site Kit dashboard:
_Heading: Site Kit can’t access necessary data_
_Description: {error.message}_
* The notification should have CTA link `data.reconnectURL` and CTA label _Redo the plugin setup_.
* This should primarily be implemented via the legacy `assets/js/components/data` API (i.e. like the existing filters in there), via a new `AuthError` component.
    * The current `DashboardAuthError` component should be renamed to `DashboardAuthScopesError` since that is more appropriate for its usage.
* However, the above new case should also be implemented for the datastore infrastructure and the `assets/js/googlesitekit/api` error handler in `siteKitRequest`:
    * The `core/user` store should receive new actions `setAuthError( authError )` and `clearAuthError()`, and a new selector `getAuthError()`, which set/unset/get a `WP_Error`-like JS object (`code`, `message`, `data`).
    * The `assets/js/googlesitekit/api` error handler (which right now only handles `ERROR_MISSING_REQUIRED_SCOPE` errors) should receive additional logic like above, if `data.reconnectURL` is present and the `core/user` datastore is available, dispatch `setAuthError` on it.
    * The `ErrorNotification` (which right now is filtered and by default just returns `null`) should be modified to use `getAuthError` and return the new `AuthError` if applicable. The filters should be maintained as they are (as in if the legacy API adds an error via filter, it will take precedence, which is fine).

## Implementation Brief

 * Rename existing `DashboardAuthAlert` to `DashboardAuthScopesAlert`  and update all references to it.
* Create new `AuthError` component in  `assets/js/components/notifications` with displays the heading, description and CTA link/text as defined in the AC.
* In `assets/js/components/data/index.js` , update the `handleWPError` function to add a new conditional that checks for the existence of `data.reconnectURL` and is found adds the new `AuthError` component to the `googlesitekit.ErrorNotification` filter.
* Add the new selectors/actions to the `core/user` store and applicable tests.
* Update `siteKitRequest` in `assets/js/googlesitekit/api/index.js` to utilize new actions to match the filter logic.
* Update the `ErrorNotifiction` component to return the new `AuthError`  when applicable.

## QA Brief

* Set up Site Kit using the proxy as usual
* Connect a service like Analytics
* Open a new tab and navigate to the Site Kit dashboard
	- Click on your user in the header and select "Manage Sites" from the dropdown to go to the permissions management screen on the proxy
	- Click the button to "Remove access" for the site you are using
	- **Important: close the browser tab - do not click "Back" to go back to your site as this will trigger a disconnect**
* Now we need to trigger the access token to be refreshed which happens automatically on-demand when it expires (after 1hr)
	- To skip this 1hr wait time, we need to update the user meta for your user to tell Site Kit that the token should already be expired
	- Run `wp user meta set <user> wp_googlesitekit_access_token_expires_in 1` where `<user>` is your WP username, user ID or email
* Clear the session storage
* Reload the Site Kit dashboard
* See auth error notification with CTA button to "redo the plugin setup"  
![notification](https://user-images.githubusercontent.com/873049/94170219-73d45200-fe98-11ea-86da-fb1e39494fc6.png)

## Changelog entry

* Display error notification when refreshing an access token failed due to missing Site Kit authentication service requirements.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA failed ❌

After following the QA steps I got these screen:

<img width="1201" alt="Screenshot 2020-10-07 at 17 20 48" src="https://user-images.githubusercontent.com/90871/95358954-82bbfb00-08c1-11eb-9a7b-5821dc4277f1.png">

It seems to be behaving as expected, but the UI is different to what the QA brief says. If this is intentional please let me know and move this into approval. But otherwise it seems the UI doesn't match the QA Brief.

**Comment by tofumatt** [comment]
QA ✅

The issue here is fixed but there is a separate issue that prevents the fix from appearing.
