### ISSUE TITLE
Cant change analytics sign in info if there is an error (only options are to refetch or create new)

### ISSUE THREAD

**Issue by mikjits** [google/site-kit-wp#185]
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@mikjits Did you have any luck setting up Analytics after? If not please describe the error, along with posting any console errors you might see.

**Comment by mikjits** [comment]
I still haven't been able to set it up. I click complete activation

![1](https://user-images.githubusercontent.com/52760995/62707626-ee998f80-b9ae-11e9-90b4-b5b188018f0a.JPG)

It only gives me the option to refetch or create new
![2](https://user-images.githubusercontent.com/52760995/62707628-ee998f80-b9ae-11e9-9428-e96cbd669f39.JPG)

I already have analytics that works on the full dashboard so I do not want to create new, when I click refetch it just shows the loading bar continuously 

![3](https://user-images.githubusercontent.com/52760995/62707629-ee998f80-b9ae-11e9-902d-c3a62bff35d0.JPG)

I've tried removing it completely and re-adding it and it just takes me to this same cycle.

**Comment by jamesozzie** [comment]
@mikjits There are some troubleshooting steps you'll find in this duplicate issue, #386. 
Can you check the possible causes in that issue and see if any of those apply to you?

**Comment by jamesozzie** [comment]
@mikjits Did you have any luck setting up the Analytics module after the previous suggestion?

**Comment by mikjits** [comment]
no

Yours in success,
Michael Athens
303-909-1405

**Comment by jamesozzie** [comment]
@mikjits If you want to share you [Site Health info](https://i.imgur.com/Rtkmsba.png) I can take see if there is anything I notice which could be impacting your setup.

**Comment by jamesozzie** [comment]
@mikjits I will close this issue due to lack of response. Feel free to reopen if you are encountering the same issue. Include additional information such as your site health information, console errors and XHR responses.
