### ISSUE TITLE
Dashboard error after AdSense activation

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1855]
As reported in the [WordPress support forums](https://wordpress.org/support/topic/adsense-connection-error/#post-13189298) one encountered the below error during AdSense setup:

```
Failed to construct ‘URL’: Invalid URL

in SetupSiteAdd
in div
in div
in SetupMain
in InnerComponent
in WithFilters(BaseComponent)
in div
in div
in div
in section
in div
in div
in div
in div
in SetupWrapper
in Suspense
in GoogleSitekitModule
in RestoreSnapshots
in ErrorHandler
in Root
```

Awaiting additional information

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Unfortunately no further information provided on this topic. Escalating to L1 in the event it warrants further investigation.

**Comment by cole10up** [comment]
Unable to reproduce, no new items from the forums on this ticket. Setting to closed.
