### ISSUE TITLE
Improve support for sites that have changed their URL

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1857]
Our current support for sites changing their URL has slightly improved since initial launch, but is still causing quite a high number of support requests. For some context, changing the URL of a site affects the following:

* URLs registered on the Site Kit service need to be updated, otherwise any subsequent (re-)connection attempts will likely fail (for a myriad of possible reasons and edge cases, which we've been patching over numerous times).
* The Search Console property used _may_ need to be updated to reflect the new URL.

At the moment, we are only handling URL changes if they happen by updating the WordPress options, but there are several other ways this can happen, even outside of WordPress context. Furthermore, we only deal with updating the URLs on the Site Kit service, but not with e.g. updating Search Console.

High level summary of the changes required: We should support detection of URL changes through _any_ means, and in such a case prompt the administrator to reconnect, so that requirements for the new URL are checked, and the Search Console property is updated. This is only needed for _any_ user with administrator privileges, not every user connected to Site Kit (although there is no downside if multiple users go through this anyway, e.g. if they both access WP at a similar time).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**This feature is only relevant for sites that use the proxy.**
* Whenever a user receives an access token as final part of connecting (i.e. `googlesitekit_authorize_user` action), _if_ they can `googlesitekit_setup`, the current **home URL** should be stored in a `googlesitekit_connected_proxy_url` option.
* On every `admin_init`, _if_ the current user can `googlesitekit_setup` and if the site is "connected" (i.e. has site ID and secret), check whether the current home URL differs from the one stored in `googlesitekit_connected_proxy_url`. If yes:
    * Disconnect the current user.
    * Set a temporary flag (e.g. user meta) that this user was disconnected due to a URL change.
* For any user that has the above flag set (and the site is still "connected"), a general WP admin notice should be displayed (see copy below). It should include a link to reconnect, which brings them to the splash screen.
* There should be a new `admin_action_googlesitekit_proxy_connect_user` action handler which when called, qualifies the current user before redirecting them to the `OAuth_Client::get_proxy_setup_url`
* The `proxySetupURL` provided to the client should be in the form:
`{admin_url}?action=googlesitekit_proxy_connect_user&nonce={nonce}`
* When a user with the flag (and the site still "connected") visits the splash screen, modify the copy (see below).  
When the user then clicks on the button, it shouldn't immediately redirect to the proxy setup as usual, but instead:
    1. Issue a _synchronous_ request to sync the site fields.
    2. After that, redirect the user to the proxy setup URL.
* When such a user then reconnects (i.e. `googlesitekit_authorize_user` action), the temporary flag for them should be deleted.
* The current logic to sync site fields on URL option updates should be removed, as the above explicit behavior should replace it. It should only be kept for site title updates and DB version updates (which are not as critical for the functionality, but good to keep).

### Admin notice copy

_Heading: Reconnect Site Kit_
_Description: Looks like the URL of your site has changed. In order to continue using Site Kit, you'll need to reconnect, so that your plugin settings are updated with the new URL._
_Link label: Reconnect_ (leads to proxy)

### Conditionally modified splash screen copy
Should be the same as the admin notice copy above. 

_Heading: Reconnect Site Kit_
_Description: Looks like the URL of your site has changed. In order to continue using Site Kit, you'll need to reconnect, so that your plugin settings are updated with the new URL._
_Button: Reconnect_ (leads to proxy)

### Misc fixes

* The logic to set the Search Console property on `googlesitekit_authorize_user` should only run if the current user can `googlesitekit_setup`.

#### New settings

* Add a new `Core\Authentication\Connected_Proxy_URL` class, which extends `Core\Storage\Setting`
    - Represents the `googlesitekit_connected_proxy_url` option
    - Instantiate as a `connected_proxy_url` property of `Authentication` in the constructor and register the setting in `Authentication::register` with others
    - Should have an internal method for normalizing provided URLs
        - This method should be used as the `sanitize_callback`, and also with the method below
    - Should receive a public `matches_url( $url )` method, which normalizes the given URL and compares it to the saved value and returns `true` if they are equal, otherwise `false`
    - Extend the `register` method to add a new action on **`googlesitekit_authorize_user`** to simply call `$this->delete()` unconditionally
* Add a new `Core\Authentication\Disconnected_Reason` class, which extends `Core\Storage\User_Setting`
    - Represents the `googlesitekit_disconnected_reason` user option
    - Instantiate as `disconnected_reason` on `Authentication` and register the setting in `Authentication::register` with others

#### `Google_Proxy`

* Define a new `Google_Proxy::ACTION_CONNECT_USER` class constant: `googlesitekit_proxy_connect_user`
* Update `Google_Proxy::sync_site_fields` with an optional second parameter `$mode` which defaults to `async`
    - When `$mode = 'sync'`, the request should be made without `timeout` and `blocking` args so that it waits for the response
    - Update to always return the result of `wp_remote_post`

#### `Authentication`

* In `Authentication::register`, add a new action on **`googlesitekit_authorize_user`** and call a new private method `set_connected_proxy_url`  
    In the new method:
    - If `current_user_can( Permissions::SETUP )`, call `Connected_Proxy_URL->set( home_url() )`  
    _No need to check if this is different first as WP will skip the DB query if the values are the same_
* In `Authentication::register`, add a new action on **`admin_init`**, calling a new private method `check_connected_proxy_url`
    In the new method:
    - If **not** `current_user_can( Permissions::SETUP )` – return early
    - If **not** `$this->credentials()->has()` – return early
    - If **not** `$this->credentials()->using_proxy()` – return early
    - If **not** `$this->is_authenticated()` – return early
    - If **not** `$this->connected_proxy_url->has()` – return early
    - if **not** `connected_proxy_url->matches_url( home_url() )`
        - Disconnect the current user `$this->disconnect()` and then set the disconnected reason code:
        - `disconnected_reason->set( Authentication::DISCONNECTED_REASON_CONNECTED_URL_MISMATCH )` (a new constant which holds the `connected_url_mismatch` string literal)
* In `Authentication::register`, add a new action on **`'admin_action_' . Google_Proxy::ACTION_CONNECT_USER`** which calls a new private method `handle_proxy_connect_user`:
    - If **not** `current_user_can( Permissions::SETUP )`, `wp_die` with insufficient permissions message (use the same as core)
    - If **not** `credentials->using_proxy()`, `wp_die` with a generic "doing it wrong" message
    - Verify `$_GET['nonce']` with `Google_Proxy::ACTION_CONNECT_USER` as the action or `wp_die`
    - If `disconnected_reason` is equal to `connected_url_mismatch` (using `disconnected_reason` instance and reason constant)
        - Call `Google_Proxy->sync_site_fields( Credentials, 'sync' )` to synchronously update site fields before navigating to proxy setup as usual
    - Redirect to `OAuth_Client->get_proxy_setup_url( $access_code )` as it does now (see `Authentication::inline_js_base_data`)
        - This should always be the last step regardless of `disconnected_reason` presence or value
* Add a new `Authentication::get_proxy_connect_user_url` method, essentially returning:  
    ```php
    return add_query_args(
        array(
            'action' => Google_Proxy::ACTION_CONNECT_USER,
            'nonce'  => wp_create_nonce( Google_Proxy::ACTION_CONNECT_USER )
        ),
        admin_url( 'index.php' )
    );
    ```
    - Update `proxySetupURL` in `Authentication::inline_js_base_data` to use the new `get_proxy_connect_user_url` instead so that the client always sends users through the WP backend to get there (similar to `connect_url`). This is also more secure as it does not expose credentials such as site ID and site secret to the front end and only allows access to users with sufficient permissions.
* Update `Authentication::authentication_admin_notices`
    - Add a new notice to the array from a new private method `get_reconnect_after_url_mismatch_notice`
    - In new method return a new `Notice` with a slug of `reconnect_after_url_mismatch`
        - The `active_callback` should return true if:
            - the saved `disconnected_reason` is equal to `connected_url_mismatch` (using `disconnected_reason` instance and reason constant)
            - AND `credentials->has()`
        - The message should come from the ACs above
        - Build the html in PHP with the single action button/CTA linking to `Google_Proxy->get_connect_user_url()`
* Update `core/user/data/authentication` response in `Authentication::get_rest_routes` to include `disconnectedReason` set to `disconnected_reason->get()`
* In `Authentication::register`, remove actions for syncing site fields when `home` or `siteurl` options change  
    ```diff
    - add_action( 'update_option_home', $option_updated );
    - add_action( 'update_option_siteurl', $option_updated );
    ```

#### `Search_Console`

* Update `googlesitekit_authorize_user` callback in `Search_Console::register` to return early if the current user cannot `Permissions::SETUP`

#### JS
* Add a new `getDisconnectedReason` selector to `assets/js/googlesitekit/datastore/user/authentication.js` which selects `disconnectedReason` from the main `getAuthentication` selector
    * Add `DISCONNECTED_REASON_CONNECTED_URL_MISMATCH` to `datastore/site/constants`, defined with the same value as the PHP constant
* Update `assets/js/components/setup/setup-proxy.js`
    - **Refactor as functional component using `useSelect` hooks instead of `withSelect` HOC**  
    This component is basically a `render` function with a constructor as it is so this should be a fairly straightforward conversion
    - Use alternate wording when the selected `disconnectedReason` is set to `connected_url_mismatch` (using constant for comparison)

### Tests

**PHPUnit**
* Add test case for new `Connected_Proxy_URL`
* Add test case for new `Disconnected_Reason`
* Update `AuthenticationTest`
    - Added/removed hooks in `register`
    - Add test for `get_proxy_connect_user_url`
    - Add test(s) for `'admin_action_' . Google_Proxy::ACTION_CONNECT_USER` action
    - Add tests for `googlesitekit_authorize_user` actions
    - Add test for new behavior hooked on `admin_init`

**Jest (unit)**
* Update `assets/js/googlesitekit/datastore/site/connection.test.js` to include new `getDisconnectedReason` selector

**Jest (E2E)**
_No anticipated changes necessary_

**Storybook**
* Add story for `SetupUsingProxy` in the new state for a changed URL

Update any other tests as necessary.

## QA Brief

You'll need a site whose URL you can change.

* Create a WordPress site (eg. `http://original.url`) and authorise it with Site Kit, as an admin user.
* Change its URL, eg. with:
```php
define( 'WP_HOME', 'http://new.url' );
define( 'WP_SITEURL', 'http://new.url' );
```
in the `wp-config.php`.
* Navigate to any admin page and observe the admin notice.
* Click the link in the notice and you should see the text _"Looks like the URL of your site has changed. In order to continue using Site Kit, you'll need to reconnect, so that your plugin settings are updated with the new URL"_ and you should be able to click the "reconnect" button to update your settings

You can repeat the above, but change to a non-admin user after setup (eg. without `googlesitekit_setup` permissions) and you should not see the notice after changing the URL.

## Changelog entry

* Store the site URL that is connected to the Site Kit authentication service and prompt users to reconnect if the site URL has changed, allowing to update the registered configuration and fix future connection issues.

**Comment by marrrmarrr** [comment]
@felixarntz I've added a button to the splash screen, since it was in your description of the expected flow, but was missing from the notification. 
IIUC users whose URL has changed won't be able to use Site Kit until they go through this process, right?
If that's the case, why don't we redirect them straight to the splash screen, instead of relying on them to notice the message in wp-admin?

**Comment by tofumatt** [comment]
I think this IB does the trick, but I'm admittedly less familiar with the PHP in the app, so if my approach is off let me know 😅

**Comment by felixarntz** [comment]
@tofumatt
> Add a check for `if ( current_user_can( Permissions::SETUP ) )` and set the current reference URL to `googlesitekit_original_reference_url` setting in the `Search_Console` module settings here:

This setting shouldn't be related to Search Console, it's a general setting which should receive its own class extending `Google\Site_Kit\Core\Storage\Setting`. The logic to set it should be executed either in this new class via an action hook on `googlesitekit_authorize_user` or "hard-coded" in `Google\Site_Kit\Core\Authentication\Clients\OAuth_Client::authorize_user` before the action hook fires.

Otherwise, I think the IB reads a bit too close to the ACs. For the PHP part, it would be good to describe how to actually implement the changes (class names, method names etc.) - including for example where to implement the new REST API endpoint. For the (small) JavaScript part it should also be mentioned (at least on a high level) on how and where these changes should be made.

**Comment by aaemnnosttv** [comment]
@felixarntz this issue turned out to be quite a bit larger than may have been expected but I think it's all covered now. I took a slightly different approach than outlined in the AC in a few places but I think you'll like the changes.

The main difference is changing the way we send users to the proxy for setup to flow throw WP rather than navigate directly from the client. This allows us to sync the site fields before we redirect if needed rather than introduce a new REST route and is a bit more simple than the alternative since the client now has a single place to send users in either case and all of the credentials are kept in the backend without being exposed until all permission/nonce checks have passed.

Let me know what you think 👍

**Comment by felixarntz** [comment]
@aaemnnosttv The IB looks great, thanks for all the detail - it's cleaner than my original idea of a REST route and otherwise pretty much what I had in mind. There are still a few things to potentially revisit:

Overall, I think there are a few more places where we need to check whether the site is using the proxy (e.g. `Authentication::check_connected_reference_url`. Basically this entire feature is irrelevant for sites not using the proxy. We don't necessarily need to add this everywhere to the IB, but it should be noted on a high level.

> Add a new `Core\Authentication\Connected_Reference_URL` class

Revisiting this, this is actually incorrect in the ACs and probably led to this: The URL used here should not be the reference URL, but the home URL, since this is what is always sent to the proxy. The reference URL basically doesn't exist from the proxy point of view, it's a plugin-internal detail. Let's rename the class, setting and other references to "reference URL" (ha ha) accordingly, I think we should just go with `connected_url` (no need to use `connected_home_url`, the proxy query parameter is also called simply `url`. Actually, maybe we could use `connected_proxy_url`, which would nicely indicate that this is only relevant to the proxy. I'll update this in the ACs as well.

> Update `Authentication::disconnect()` to accept a new optional `$reason` parameter, which defaults to `null`
> * At the end of the method, after meta cache is deleted, call `$this->disconnected_reason->set( $reason )`

I'd prefer if we handled the flag separately and kept `disconnect()` to really only disconnect. Otherwise I think it mixes up concerns a bit too much. We could just set the reason right after disconnecting.

> If `disconnected_reason` is equal to `reference_url_mismatch` (using `disconnected_reason` instance and reason constant)

Just to clarify, I assume if that is not the case, the action will redirect to the proxy right away, correct?

> Update `core/site/data/connection` response in `Authentication::get_rest_routes` to include `disconnectedReason` set to `disconnected_reason->get()`

Since this is a user setting, it should rather be exposed in `core/user/data/authentication`. I agree the naming seems a bit odd because it refers to disconnecting, but it's still a per-user value.

> Add a new `getDisconnectedReason` selector to `assets/js/googlesitekit/datastore/site/connection.js`

See above, this should instead go into `assets/js/googlesitekit/datastore/user/authentication.js`

**Comment by aaemnnosttv** [comment]
That all sounds good to me.

> Just to clarify, I assume if that is not the case, the action will redirect to the proxy right away, correct?

Yes – it was kind of written like the code would be structured there (if url mismatch, sync fields, endif – redirect to proxy) 😄 

Will update the IB with the remaining changes shortly 👍

**Comment by felixarntz** [comment]
@aaemnnosttv IB basically LGTM , just two things:
> If **not** `credentials->using_proxy()`, redirect to splash page (should show legacy setup)

I think here we should `wp_die` instead, since this action should only be used when the proxy is in use, so I think that is more explicit error feedback. If this redirected to the splash page, you'd end up in a "loop".

The other thing, the REST API endpoint for `disconnectedReason` should be `core/site/data/authentication`, and in JS all the selectors etc around `disconnectedReason` should be part of the `core/user` store, not `core/site` store (this is probably just an oversight as there is no `core/site/data/authentication`).

After those changes, this should be ✅

**Comment by aaemnnosttv** [comment]
>> If **not** `credentials->using_proxy()`, redirect to splash page (should show legacy setup)
>
> I think here we should `wp_die` instead, since this action should only be used when the proxy is in use, so I think that is more explicit error feedback. If this redirected to the splash page, you'd end up in a "loop".

If we want to `wp_die` for that instead, that's fine; it shouldn't be possible to end up in a loop though because that action wouldn't run for a menu page and the splash page would show the legacy setup if not using proxy.

> The other thing, the REST API endpoint for `disconnectedReason` should be `core/site/data/authentication`, and in JS all the selectors etc around `disconnectedReason` should be part of the `core/user` store, not `core/site` store (this is probably just an oversight as there is no `core/site/data/authentication`.

Ah yes, that's confusing indeed. I think you meant `core/user/data/authentication` as well! 😉 

---

@felixarntz The IB is updated now and I also updated the ACs to remove the part about the added REST route, and added a few points about the changes to the `proxySetupURL`.

**Comment by felixarntz** [comment]
@aaemnnosttv Yeah, let's go with `wp_die` calls, I think it's more explicit - this shouldn't ever happen anyway. IB ✅

**Comment by tofumatt** [comment]
QA ✅

Admin user visiting an admin page after changing the URL:
<img width="1203" alt="Screenshot 2020-09-24 at 23 31 52" src="https://user-images.githubusercontent.com/90871/94206811-38e51500-febe-11ea-90a3-4c22ca48d042.png">

Tested with a non-admin user and the notice went away.

Reauthorised the site and the notice didn't appear 👍🏻

**Comment by marrrmarrr** [comment]
tested with changing the URL of the site from https to http and then back. admin notice and reconnect screens appearing as described in ACs. lgtm
