### ISSUE TITLE
Detail screen title shouldn't show slashed data  

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#186]
Original post tile:
![549c996da5e0fb1f2fbed2380254a5af](https://user-images.githubusercontent.com/28811945/61006031-feca3a80-a32e-11e9-872f-5e417bb35217.png)

in site kit detail view:
![54982fe9a66424743296f26c5fe3d424](https://user-images.githubusercontent.com/28811945/61006043-038eee80-a32f-11e9-96f6-6e8162acfcca.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Post titles should show without /
* All special characters should be properly displayed. 

## Implementation Brief
Update `decodeHtmlEntity()` to account for backslashes.
https://github.com/google/site-kit-wp/blob/develop/assets/js/util/index.js#L907

## Changelog entry

* Fix bug where some post titles display backslashes on detail page.

**Comment by felixarntz** [comment]
Implementation brief looks good!

**Comment by circlecube** [comment]
I've addressed the code review comment. Moving back to review.

**Comment by adamsilverstein** [comment]
This worked well in my testing. I created a test page with several different special characters including the original smart apostrophe. Everything displayed as expected, no slashes were visible:

![image](https://user-images.githubusercontent.com/2676022/63439132-b94b6380-c3ea-11e9-90c4-f5cf37756a32.png)

**Comment by marrrmarrr** [comment]
LGTM.
