### ISSUE TITLE
Update .nvmrc to use the current LTS version

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#1868]
## Feature Description

Node 10 is no longer the actual LTS version and based on the [LTS schedule](https://nodejs.org/en/about/releases/) will become deprecated in less than a year (04/30/2021). We need to consider changing Node.js version to the current LTS. We can do it by changing `10` on `lts/*` in the `.nvmrc` file.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this out as we recently updated it to `14` which is quite a bit more recent than `10` 😄 

I don't think we will be changing it to the dynamic `lts/*` though because we want to control when it changes.
