### ISSUE TITLE
\Google\Site_Kit\Modules\TagManager\TagManager should be Tag_Manager for consistency

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#187]
Currently: `\Google\Site_Kit\Modules\TagManager\TagManager` 

Should be updated to `Tag_Manager` for consistency

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `TagManager` PHP class should be renamed to `Tag_Manager` for consistency, before launch.

## Implementation Brief

* Rename `Google\Site_Kit\Modules\TagManager` to `Google\Site_Kit\Modules\Tag_Manager`
* Update any references and imports

_Note: There are `TagManager` classes that are present in the Google SDK (copied into vendor) that should not be renamed. That is, a project-wide search-replace is likely not safe, and care should be taken to ensure that only references to the Site Kit module are changed/updated._

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
### QA ⚠️ 

- `tests/phpunit/integration/Modules/TagManagerTest.php` should be `Tag_ManagerTest.php`  
_PR #708_
- The slug for the Tag Manager module should _maybe_ also be `tag-manager` now instead of `tagmanager`?  
However (not hyphenated):
    - `https:// tagmanager .google.com/` Homepage subdomain
    - `https://www.googleapis.com/auth/ tagmanager .manage.accounts` Auth scopes

**Comment by tofumatt** [comment]
Good catch on:

> `tests/phpunit/integration/Modules/TagManagerTest.php` should be `Tag_ManagerTest.php`

I've created #709 for that fix.

Not sure about changing the slug, but we can add it to the above PR if needed.

**Comment by felixarntz** [comment]
I think it's okay keeping `tagmanager` as the slug. There are certainly arguments for `tag-manager` (I think the scopes aren't a counter argument because they pretty much never contain hyphens), but it would also lead us to changing option names accordingly (`tagmanager` --> `tag_manager`.

**Comment by aaemnnosttv** [comment]
### QA ✅ 

No instances of `TagManager` module class remain in old form.

Moving to approval.
