### ISSUE TITLE
Dashboard error during Analytics module setup: Error: Login Required

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1872]
## Bug Description

As reported in a [WordPress support forum topic](https://wordpress.org/support/topic/site-kit-analytics-error-login-required/) a dashboard error appears during Analytics module setup
`Error: Login Required`

https://i.imgur.com/mI8nzi4.png
![image](https://user-images.githubusercontent.com/41326532/89295749-52ee3e00-d659-11ea-9eec-6a3a2d4f3a12.png)

The Analytics account drop-down may also remain loading.
No further information provided. 

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by julian4u0** [comment]
i fixed this by going to google analytics, adding the tracking code to header of my website and trying again

**Comment by jamesozzie** [comment]
@julian4u0 Many thanks for sharing, that's good to know should other users encounter this issue.

**Comment by prashantkrsahu** [comment]
I am encountering the same issue when I try to connect Google Analytics as well as Google AdSense. Search Console is connected but there is no data in the Search Console section. The same error showing inside the Search Console section.

**Comment by jamesozzie** [comment]
@prashantkrsahu Do you encounter the same "Login Required" error? If you'd like to open a [support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on the WordPress support forums we can hopefully determine the cause. With the topic please include a screenshot of the error you encounter and if possible share your [Site Health information](https://i.imgur.com/Rtkmsba.png). You can share privately if preferred using [this form](prashantkrsahu ).

**Comment by jamesozzie** [comment]
Closing with no additional reports on this issue and no response from user in support forums.

**Comment by RedactedProfile** [comment]
Definitely facing this issue at the moment

![image](https://user-images.githubusercontent.com/1039911/120741646-3ce42080-c4aa-11eb-9a49-ad3a538489ab.png)

**Comment by bethanylang** [comment]
Hi @RedactedProfile Thanks for getting in touch! Support for the Site Kit plugin is managed on the WordPress.org support forums. If you can [create a new topic there](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0), we can take a look and help you troubleshoot this issue. Thank you!
