### ISSUE TITLE
Improve `parse_date_range`: accept an array instead of positional arguments.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1877]
## Feature Description

The `parse_date_range` helper function has a growing list of [positional arguments](https://github.com/google/site-kit-wp/pull/1822/files#diff-cfaf931d253f74a615a5684c6f0207b6R566-R573). Originally suggested [here](https://github.com/google/site-kit-wp/pull/1822/files#r464883281). 

We can make calls more human-readable by passing these instead as an array of named arguments. This will also let us leave out arguments that expect their default value.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This is no longer relevant since all new components no longer rely on PHP date range parsing, and in the near future the PHP side of it will be completely removed.
