### ISSUE TITLE
Add permission_callback to all E2E REST Routes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1882]
## Bug Description

As of WP 5.5, the `permission_callback` argument is required for all registered REST routes. Public routes (such as those used by our E2E tests) only need to use a permission callback of `__return_true`. This isn't a problem for any of our main routes used in Site Kit but this argument was omitted for all routes used in E2E tests.

Example notice:
```
PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>google-site-kit/v1/e2e/auth/access-token</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.) in /var/www/html/wp-includes/functions.php on line 5225
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E tests should not raise any PHP notices related to improperly registered REST API routes belonging to the Site Kit namespace

## Implementation Brief

* Add `permission_callback` with `__return_true` for each use of `register_rest_route` in `tests/e2e`
* Merge #1929

## QA Brief

* Start the local E2E environment if you haven't already (it stays running if already started, even across reboots!)  
	```
	$ npm run env:start
	```
* cd into the `bin/local-env` directory
* Enable the debug log (`WP_DEBUG` is enabled by default, but logging is not)  
	```
	COMPOSE_PROJECT_NAME=googlesitekit-e2e docker-compose exec -u 33 cli wp config set WP_DEBUG_LOG true --raw --type=constant
	COMPOSE_PROJECT_NAME=googlesitekit-e2e docker-compose exec -u 33 cli touch wp-content/debug.log
	```
* Enable all plugins in the E2E environment  
	```
	COMPOSE_PROJECT_NAME=googlesitekit-e2e docker-compose exec -u 33 cli wp plugin activate --all
	```
* In a new terminal, live tail the debug log to watch for notices  
	```
	COMPOSE_PROJECT_NAME=googlesitekit-e2e docker-compose exec -u 33 cli tail -n 0 -f wp-content/debug.log
	```
* Log in to the E2E environment `http://localhost:9002/wp-admin/` and click around
* No `permission_callback` notices should be logged citing `google-site-kit/v1` endpoints
	- One possible exception to this (if not already addressed) is the `google-site-kit/v1/core/search/data/post-search` endpoint which will be handled in #1924

## Changelog entry

* N/A

**Comment by cole10up** [comment]
**Tested**

On **master** branch
Ran `npm run env:start`

![image](https://user-images.githubusercontent.com/57115907/90598766-85934d00-e1a8-11ea-8820-4a82c80ccf62.png)

Enabled dbug log:
![image](https://user-images.githubusercontent.com/57115907/90598874-bd01f980-e1a8-11ea-87ca-faf3d5585fc2.png)

Enabled all plugins:
![image](https://user-images.githubusercontent.com/57115907/90598924-cd19d900-e1a8-11ea-8608-1395db40920c.png)

Started tailing debug.log.

Clicked around my local end to end env and noticed the permissions error:
![image](https://user-images.githubusercontent.com/57115907/90609804-6f41bd00-e1b9-11ea-8ea1-8e59d29f4cf1.png)

Flipped to **develop** branch

Began tailing logs and noticed permissions error is gone
![image](https://user-images.githubusercontent.com/57115907/90609875-8680aa80-e1b9-11ea-9b64-41d6a6c5cf6e.png)

Passed QA ✅
