### ISSUE TITLE
Fix PHPUnit tests running on WP nightly

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1883]
## Bug Description

Currently we have one job which runs our PHPUnit tests against WordPress trunk/nightly but it also uses the nightly version of PHP which is currently PHP 8. This has resulted in that job failing consistently ever since PHP 8 became the version used in PHP nightly. While some work has been done to try to fix this (#1555), it doesn't seem like this will be working anytime soon as our dependencies (including our minimum supported version of PHP 5.6) aren't completely compatible with PHP 8 yet.

With WP 5.5 coming very soon, we've already seen at least one issue that was caught by E2E (https://github.com/google/site-kit-wp/issues/1710) - let's make sure we don't miss anything due to a broken job.

Rather than introduce yet another job in CI, let's update the current job that runs PHPUnit on the WP nightly build to use a stable version of PHP so that this job is useful again. We can create a new issue in the future for adding a PHP 8/nightly job in the future as it will likely require additional changes to support.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PHP tests job in `.travis.yml` that runs for `WP_VERSION=master` should use the latest stable version of PHP
* The job should still be allowed to fail as it is running against a pre-release version of WordPress
* The job should pass before merging the PR for this issue

## Implementation Brief

* Merge #1885

## QA Brief

* Navigate to https://travis-ci.com/github/google/site-kit-wp/pull_requests
* Travis tests for "PHP Tests (PHP 7.4, WordPress trunk)" should pass for PR 1885

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Verified fixed.

![image](https://user-images.githubusercontent.com/57115907/89979203-093ac000-dc24-11ea-861a-692df82c7514.png)

Passed QA ✅
