### ISSUE TITLE
Compatibility Check: detect invalid domain names.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1884]
## Feature Description

When users first set up Site Kit, the plugin checks that the user's setup is completely compatible with Site Kit. We can improve these checks by verifying that the user's WordPress site URL is a valid, public URL that will be accepted by the [Site Verification API](https://developers.google.com/site-verification). We should ideally tell the user why their domain won't work, and point them to the local development documentation for localhost domains.

In particular the user should be warned explicitly when their domain is a local development domain, an ip address, or lacks a TLD. We don't need to test for public accessibility, the Site Verification API will do that for us.

For example:

'localhost', '192.168.x.x', '127.0.0.1', "https://mysite" or "http://mysite:8081" are all invalid domains that should be flagged.

This will help users and also resolve the verification failures we see in the service logs where we are attempting to verify sites that are not public valid domains.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The compatibility checks that Site Kit performs when initially setting up should be extended to provide additional tests on the current hostname (`location.hostname`)
* The following conditions should also result in a `invalid_hostname` error to be raised, just as if Site Kit were configured on `localhost` as today
    * The current hostname is an IP within the following ranges, inclusive ([reference](https://en.wikipedia.org/wiki/Reserved_IP_addresses))
        * `10.0.0.0–10.255.255.255` (`10.0.0.0/8`)
        * `127.0.0.0–127.255.255.255` (`127.0.0.0/8`)
        * `172.16.0.0–172.31.255.255` (`172.16.0.0/12`)
        * `192.168.0.0–192.168.255.255` (`192.168.0.0/16`)
    * The current hostname includes a port
    * The current hostname does not include a top level domain `tld` (i.e. has no `.` in it)

## Implementation Brief

* In `assets/js/components/setup/CompatibilityChecks/checks.js`, update the `checkHostname` function:
* check if `window.location.port` is not empty.
* if `window.location.hostname` is a valid IP address, check if it's within the invalid IP address range.
    * Check for valid IP address using a regex like [this](https://stackoverflow.com/a/68104187).
    * Use the CIDR notations of the reserved IP from the AC and match `hostname` against them using helper functions. See [this](https://stackoverflow.com/questions/503052/javascript-is-ip-in-one-of-these-subnets/503238#503238) for example. 
* Otherwise, check if the hostname doesn't include a tld by checking if it doesn't contain a dot `(.)`
* throw `ERROR_INVALID_HOSTNAME` as soon as a check is true. Otherwise do nothing.

### Test Coverage

* It would be nice if we create a unit test for the `checkHostname` that includes all the aforementioned cases. 

### Visual Regression Changes

* n/a

## QA Brief

* Site Kit should flag sites with the URL that matches all the mentioned conditions from the AC in addition to previous ones. 
* Ensure the correctness of newly added `checkHostname` tests.

## Changelog entry

* Improve validation for domains used for Site Kit during setup.

**Comment by ShubhamPalriwala** [comment]
Can I try this one if it is available ?

**Comment by kuasha420** [comment]
@aaemnnosttv Couple of questions about the AC, 

* Should we also include IPv6 reserved addresses? 
* Shouldn't we use `window.location.host` instead of `window.location.hostname` to find  out non standard port? Can we get away with `window.location.port` ? 

Thank you.

**Comment by aaemnnosttv** [comment]
> Should we also include IPv6 reserved addresses?

@kuasha420 Good question, I don't think we need to go there just yet unless maybe @adamsilverstein knows of these being problematic as well?

> Shouldn't we use `window.location.host` instead of `window.location.hostname` to find  out non standard port? Can we get away with `window.location.port` ?

My understanding is that `location.port` would work fine here because `location` doesn't include standard ports for http(s), so anything on this property should be non-standard by definition.

**Comment by eugene-manuilov** [comment]
@kuasha420 the current IB just repeats AC. Could you please add more details of how exactly we need to implement additional checks?

**Comment by eugene-manuilov** [comment]
@kuasha420 for IP ranges checks, I think we can use the approach explained in this StackOverflow answer: https://stackoverflow.com/a/503238/531994. It relies on the CIDR notation and uses subnet masks. I have updated AC to list the appropriate CIDR notation for IP ranges. Let me know if you need help with it.

**Comment by adamsilverstein** [comment]
> Should we also include IPv6 reserved addresses?

I don't think we need to cover these based on my sense that these aren't in wide usage. I can check our logs to see if they show up at all, is there a typical ip6 address for local development I can look for?

**Comment by kuasha420** [comment]
@eugene-manuilov I agree CIDR is a great idea and makes things a lot more expressive in code. I have updated the IB. Feel free to have a look.

**Comment by eugene-manuilov** [comment]
Thanks, @kuasha420. IB :heavy_check_mark:
