### ISSUE TITLE
Event tracking timeout warning raised unnecessarily

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1886]
## Bug Description

Currently in the Analytics module, we default to excluding logged in users from measurement for the selected view chosen during module setup.

Originally this would simply prevent the Analytics tracking snippet from being output when users were logged-in. In #944, we revised this to use the GA opt-out script (and respective AMP configuration) to opt-out of all GA measurement instead to ensure this setting was respected, regardless of where Google Analytics tracking was implemented (such as GTM).

In https://github.com/google/site-kit-wp/issues/1630, we updated our internal event tracking to use the `event_callback` parameter to ensure these events are being sent. In the event that the callback takes longer than 1 second to be invoked, we raise a warning about it. This is currently visible using the default GA settings when hovering the Site Kit admin bar menu:

> Tracking event "page_stats_view" (category "admin_bar") took too long to fire.

This is because the event is never tracked (as expected) due to the opt-out which is in effect via the GA module setting to exclude all logged in users. This is because our `trackEvent` function pushes the event onto the data layer regardless of the opt-out, and the callback is never invoked because of the opt-out.

So everything is working as expected, but we're raising an unnecessary warning in the console that could be easily prevented.

In the future, we may be able to change the logic used for excluding logged-in users from measurement in GA to use the [property ID specific method](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out), but this wasn't an option previously as we didn't have a way to know what property ID was being used in GTM, although this is coming in #1381.

## Steps to reproduce

1. Set up Site Kit with Analytics configured using default settings
1. Be sure to opt into tracking on the Settings screen.
1. Navigate to a page on the front end that has data in Search Console or Analytics
1. Open the browser console
1. Hover the Site Kit admin bar item
1. See warning about event that took too long to fire

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/89526639-b8286780-d7f0-11ea-98c5-dc1aba5e2694.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Internal event tracking should not raise warnings for events that took too long to fire when the GA opt-out is in effect.

## Implementation Brief

* Update `trackEvent` to return early if `global._gaUserPrefs?.ioo?()`
* Update tests for `trackEvent` accordingly

## QA Brief

1. Set up Site Kit with Analytics configured using default settings
1. Be sure to opt into tracking on the Settings screen.
1. Navigate to a page on the front end that has data in Search Console or Analytics. Create the page if necessary.
1. Open the browser console
1. Hover the Site Kit admin bar item
1. Confirm that no error is thrown.

## Changelog entry

* Fix console warning about event tracking timeout being unnecessarily raised.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@ryanwelcher CR is ✅  – would you please add a QA brief? Once that's done, this is ready to move on to QA 👍

**Comment by cole10up** [comment]
**Tested**

Set up Site Kit with Analytics configured using default settings

 Opted into tracking on the Settings screen.

Navigated to a page on the front end that has data in Search Console or Analytics.

Confirmed no errors were displayed

Passed QA ✅

**Comment by aaemnnosttv** [comment]
> Navigated to a page on the front end that has data in Search Console or Analytics.
> Confirmed no errors were displayed

@cole10up just to confirm – did you hover the admin bar menu item? This is the action that triggered the warning before so this is a critical step in the QAB.

**Comment by cole10up** [comment]
@aaemnnosttv - Thanks for double checking. Yes hovered over Admin, navigated through different pages hovering over admin. No issues.

![image](https://user-images.githubusercontent.com/57115907/92770114-7722f600-f34e-11ea-851b-15969becffa9.png)

![image](https://user-images.githubusercontent.com/57115907/92770171-84d87b80-f34e-11ea-9358-0a0626283994.png)
