### ISSUE TITLE
Event Tracking for downloads, external links, email links and telephone links

### ISSUE THREAD

**Issue by scottshefler** [google/site-kit-wp#1892]
## Feature Description

A previous Google Analytics plugin we were using had the ability to enable event tracking for downloads, external links, email links and telephone links. It would be great if this plugin could accommodate that as well. It worked by using some JavaScript on the front end to match links that fit the above criteria and applied the appropriate action, category, label tags to the links and triggered an event when clicked.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@scottshefler Many thanks for your valuable feedback. As we already have #1207 open I'll close this one as a duplicate, but feel free to add any input to that feature request. 

With the [autotrack](https://github.com/googleanalytics/autotrack) feature mentioned in that issue many of the suggestions you've referenced would be covered, including external links and  tracking emails and contact related links via HTML tags.
