### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Od99977** [google/site-kit-wp#1893]
My AdSense account was diapproved on the 9th. July and that it was going to take 30 days without showing AdSense but I have finished it on the 8th of August but not yet showing AdSense. What could be the reason

**Comment by JoeyCreator** [comment]
I would like to know to, but its the samething my AdSense account was diapproved.

**Comment by jamesozzie** [comment]
@Od99977 Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. Note that we can only assist with Site Kit related queries, should this issue be at AdSense account level the product experts at the [AdSense Help Center](https://support.google.com/adsense/?hl=en#topic=3373519) should be able to assist.
