### ISSUE TITLE
Official AMP plugin version 2.0(beta 3) -> Deprecated: AMP_Theme_Support::get_support_mode

### ISSUE THREAD

**Issue by maciejmackowiak** [google/site-kit-wp#1895]
## Bug Description
Hello,
We've started testing the beta version of the official AMP WP plugin and there is a tiny issue with Site Kit by Google:
```
ErrorException

User Deprecated: AMP_Theme_Support::get_support_mode is <strong>deprecated</strong> since version 2.0.0! Use AMP_Options_Manager::get_option instead.
```

Here is the culprit:
https://github.com/google/site-kit-wp/blob/1.13.1/includes/Context.php#L356

## Steps to reproduce

Install and activate AMP WP 2.0.0 beta 3
https://github.com/ampproject/amp-wp/releases/tag/2.0.0-beta3

## Additional Context

 - PHP Version: 7.4
 - Plugin Version 1.13.1
 - AMP WP Version: 2.0.0 beta 3

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For AMP plugin version >= 2.0.0 (see https://github.com/ampproject/amp-wp/blob/develop/amp.php#L20), rely on `AMP_Options_Manager::get_option` instead of `AMP_Theme_Support::get_support_mode` to detect the AMP mode.
* Just like for the previous method, there should be checks in place to ensure the class and method exists before calling it.

## Implementation Brief

* Update `Context::get_amp_mode` method, it should depend on `AMP__VERSION` constant:
  * If `AMP__VERSION >= 2.0.0`, do the following:
    * Call `AMP_Options_Manager::get_option( 'theme_support' )` instead of `AMP_Theme_Support::get_support_mode()`.
    * Update `$exposes_support_mode` variable definition to use `method_exists( 'AMP_Options_Manager', 'get_option' )` instead of `method_exists( 'AMP_Theme_Support', 'get_support_mode' )`.
  * Otherwise (`AMP__VERSION < 2.0.0`) use existing approach to define `$exposes_support_mode` and to get support mode.

## QA Brief

* Install the latest AMP beta of version 2.0.0-beta3 (https://github.com/ampproject/amp-wp/releases/tag/2.0.0-beta3) on a WordPress site with Site Kit installed. There should be no error on the WordPress Admin dashboard, Analytics setup, or Site Kit Dashboard.
* Install a pre-2.0.0 version of AMP—it should also continue to work as before even with the new code.
* There should be no PHP notice thrown by Site Kit on e.g. the Site Kit dashboard when `WP_DEBUG` and `WP_DEBUG_DISPLAY` are enabled.

## Changelog entry

* Migrate away from using `AMP_Theme_Support::get_support_mode()` which will be deprecated in the AMP plugin version 2.0.0.

**Comment by felixarntz** [comment]
@eugene-manuilov IB pretty much ✅ , but keep in mind this should remain backward-compatible. We'll need a few conditionals in there based on whether `defined( 'AMP__VERSION' ) && AMP__VERSION >= 2.0.0`.

**Comment by eugene-manuilov** [comment]
@felixarntz I have updated IB to address your notes.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: Installed amp `2.0.0-beta3-xxxx`, don't see deprecation errors.

One thing that i have noticed is that the new version of amp has added [`CronBasedBackgroundTask::is_needed` ](https://github.com/ampproject/amp-wp/blob/183be02c259284d2d95fc2a6d017805bf93fba5a/src/BackgroundTask/CronBasedBackgroundTask.php#L41-L43) method which uses `wp_doing_cron()` function that has been added in the WordPress version 4.8.0. Not sure if we need to do something with it or not, but once the new version of amp is released, we won't be able to use it with our plugin on sites with WordPress version 4.7.0.

**Comment by felixarntz** [comment]
@eugene-manuilov That's okay though, it's on them which version of WP they require.
