### ISSUE TITLE
Migrate Search Console Impressions and Clicks dashboard widget to use Widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1897]
The current Search Console `SearchConsoleDashboardWidgetTopLevel` widget should be migrated to use the Widgets API (which is behind a feature flag), while maintaining the current version as legacy components. Those will be removed only once all widgets have been migrated so that we can do the entire switch.

Some general practices for migrating:
* The migration should happen by fully **re-implementing** the components: In other words, the existing components should keep their current functionality, they should **not** use the datastore. Those legacy components should be prefixed with `Legacy*`.
* A good starting point is probably to copy the components into new files and go from there, while renaming the old ones and leaving them untouched.
* For the refactored version, _only_ the actual widget components should be fully responsible for retrieving data from the datastore. If they rely on further `common` components for UI, these should receive such data via props.
* If there are UI parts that can be reused between the new and legacy components, those can be outsourced into `common` components, however as mentioned above **it is important that the legacy components keep using the legacy data API and are not switched to the datastore**. Only the new ones should be.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`SearchConsoleDashboardWidgetTopLevel`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetTopLevel.js) component should be migrated to a functional component using the datastore entirely, no globals and no legacy data API.
* Refactoring map:
    * `dashboard/SearchConsoleDashboardWidgetTopLevel.js` should become `dashboard/DashboardImpressionsWidget.js` (refactored widget 1), `dashboard/DashboardClicksWidget.js` (refactored widget 2) and `dashboard/LegacySearchConsoleDashboardWidgetTopLevel.js` (legacy) - i.e. this component should be split into two separate widget components for the refactoring. The refactored widget components should access the datastore for the main API data.
    * `dashboard/DashboardSearchFunnel.js` should simply be renamed to `dashboard/LegacyDashboardSearchFunnel.js`.
    * `dashboard/DashboardSearchFunnelInner.js` should simply be renamed to `dashboard/LegacyDashboardSearchFunnelInner.js`.
* The new `DashboardImpressionsWidget` and `DashboardClicksWidget` components should rely on `select( CORE_SITE ).getCurrentReferenceURL()` so that they use the site URL vs the current entity URL as applicable (the latter e.g. when used in the `pageDashboard` context).
* The new `DashboardImpressionsWidget` component should be registered as a widget with priority 1, width `Widgets.WIDGET_WIDTHS.QUARTER`, and for the two widget areas `AREA_DASHBOARD_SEARCH_FUNNEL` and `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL`.
* The new `DashboardClicksWidget` component should be registered as a widget with priority 2, width `Widgets.WIDGET_WIDTHS.QUARTER`, and for the two widget areas `AREA_DASHBOARD_SEARCH_FUNNEL` and `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL`.

#### Stage 1
* Rename the following files and components accordingly:
  * `assets/js/modules/search-console/dashboard/SearchConsoleDashboardWidgetTopLevel.js` ->
    `assets/js/modules/search-console/dashboard/LegacySearchConsoleDashboardWidgetTopLevel.js`;
  * `assets/js/modules/search-console/dashboard/DashboardSearchFunnel.js` -> 
    `assets/js/modules/search-console/dashboard/LegacyDashboardSearchFunnel.js`;
  * `assets/js/modules/search-console/dashboard/DashboardSearchFunnelInner.js` ->
    `assets/js/modules/search-console/dashboard/LegacyDashboardSearchFunnelInner.js`.
* Update:
  * `index.legacy.js` file to use:
    * `LegacySearchConsoleDashboardWidgetTopLevel` instead of `SearchConsoleDashboardWidgetTopLevel`;
    * `LegacyDashboardSearchFunnel` instead of `DashboardSearchFunnel`.
  * `stories/dashboard.stores.js` file to use:
    * `LegacySearchConsoleDashboardWidgetTopLevel` instead of `SearchConsoleDashboardWidgetTopLevel`;
    * `LegacyDashboardSearchFunnelInner` instead of `DashboardSearchFunnelInner`.

#### Stage 2
* Create `assets/js/modules/search-console/dashboard/DashboardImpressionsWidget.js` file;
* `DashboardImpressionsWidget.js` file should:
  * Define a functional component with `DashboardImpressionsWidget` name;
  * Use `useSelect` hook and the following selectors:
    * `getCurrentReferenceURL` selector from the `core/site` datastore to retrieve the current reference URL;
    * `getDateRange` selector from the `core/user` datastore to retrieve the current date range;
    * `getReport` selector from the search-console datastore (implemented in #1774) to retrieve the current search analytics.
       * Use `date` dimension, current reference URL and date range information to compose options object and pass it into the getReport selector.
  * Replicate the logic from the legacy comonent to render imporessions widget;
    https://github.com/google/site-kit-wp/blob/8edad66b753af26c933e54ebf830d618f3a9bb32/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetTopLevel.js#L115-L131

#### Stage 3
* Create `assets/js/modules/search-console/dashboard/DashboardClicksWidget.js` file;
* `DashboardClicksWidget.js` file should:
  * Define a functional component with `DashboardClicksWidget` name;
  * Use `useSelect` hook and the following selectors:
    * `getCurrentReferenceURL` selector from the `core/site` datastore to retrieve the current reference URL;
    * `getDateRange` selector from the `core/user` datastore to retrieve the current date range;
    * `getReport` selector from the search-console datastore (implemented in #1774) to retrieve the current search analytics.
       * Use `date` dimension, current reference URL and date range information to compose options object and pass it into the getReport selector.
  * Replicate the logic from the legacy comonent to render clicks widget;
    https://github.com/google/site-kit-wp/blob/8edad66b753af26c933e54ebf830d618f3a9bb32/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetTopLevel.js#L140-L156

#### Stage 4
Update `assets/js/modules/search-console/index.js` file:
  * Import `domReady` from `@wordpress/dom-ready` and `Widgets` from `googlesitekit-widgets`;
  * Call `domReady` function with a callback function that registers the following widgets using `Widgets.registerWidget` function:
    * `DashboardImpressionsWidget` widget with the following arguments:
      * A string `searchConsoleImpressions` as widget slug;
      * Settings object where:
        * `component` is `DashboardImpressionsWidget`;
        * `width` is `Widgets.WIDGET_WIDTHS.QUARTER`;
        * `priority` is `1`;
        * `wrapWidget` is `true`.
      * Areas array that includes `AREA_DASHBOARD_SEARCH_FUNNEL` and `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL` imported from `googlesitekit/widgets/default-areas`.
    * `DashboardClicksWidget` widget with the following arguments:
      * A string `searchConsoleClicks` as widget slug;
      * Settings object where:
        * `component` is `DashboardClicksWidget`;
        * `width` is `Widgets.WIDGET_WIDTHS.QUARTER`;
        * `priority` is `2`;
        * `wrapWidget` is `true`.
      * Areas array that includes `AREA_DASHBOARD_SEARCH_FUNNEL` and `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL` imported from `googlesitekit/widgets/default-areas`.

## QA Brief

* In a development build, the new Search Console Impressions and Clicks widgets should render correctly in the Site Kit dashboard and the single URL details view. They should behave the same way as the old ones.
* It should be tested that they display errors if e.g. the API request goes wrong - they shouldn't keep loading infinitely in such a case (try e.g. to block client-to-server requests to cause an error).
* The old/legacy Search Console Impressions and Clicks should continue to show up in both development and production builds and behave like before.

## Changelog entry

* Migrate Search Console Impressions and Clicks widgets to new Widget API.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@ryanwelcher Assigning this to you to take over. This is almost good to go, I assume the feedback I gave in the review is relevant for the other widget PRs in CR as well.

**Comment by cole10up** [comment]
**Tested**

In a development build setup SK and checked Impressions and Clicks.

![image](https://user-images.githubusercontent.com/57115907/92553078-f3b2b900-f216-11ea-9aa0-b40d00cdcaad.png)

Confirmed flipping date functions.
![image](https://user-images.githubusercontent.com/57115907/92553126-0e852d80-f217-11ea-8918-d0cbd74093c3.png)

Different browser widths and mobile:
![image](https://user-images.githubusercontent.com/57115907/92553148-1fce3a00-f217-11ea-8e45-1d2294bfc8f2.png)

![image](https://user-images.githubusercontent.com/57115907/92553177-2c529280-f217-11ea-856b-b482945613f6.png)

Confirmed Release build functionality:
![image](https://user-images.githubusercontent.com/57115907/92553227-43918000-f217-11ea-85d3-861979302b2a.png)

Passed QA ✅

**Comment by felixarntz** [comment]
@cole10up Did you also test that for the single URL details view ("page dashboard")? All the new widgets should be checked in both of these areas, where the behavior is _slightly_ different.

**Comment by cole10up** [comment]
@felixarntz verified single URL details:

![image](https://user-images.githubusercontent.com/57115907/92694165-83ca2e80-f2fb-11ea-9988-c71e01c9a01e.png)

Thanks for checking!
