### ISSUE TITLE
Migrate Search Console Top Keywords dashboard widget to use Widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1899]
The current Search Console `DashboardWidgetPopularKeywordsTable` and `SearchConsoleDashboardWidgetKeywordTable` widgets should be migrated to use the Widgets API (which is behind a feature flag), while maintaining the current version as legacy components. Those will be removed only once all widgets have been migrated so that we can do the entire switch.

Some general practices for migrating:
* The migration should happen by fully **re-implementing** the components: In other words, the existing components should keep their current functionality, they should **not** use the datastore. Those legacy components should be prefixed with `Legacy*`.
* A good starting point is probably to copy the components into new files and go from there, while renaming the old ones and leaving them untouched.
* For the refactored version, _only_ the actual widget components should be fully responsible for retrieving data from the datastore. If they rely on further `common` components for UI, these should receive such data via props.
* If there are UI parts that can be reused between the new and legacy components, those can be outsourced into `common` components, however as mentioned above **it is important that the legacy components keep using the legacy data API and are not switched to the datastore**. Only the new ones should be.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`DashboardWidgetPopularKeywordsTable`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/search-console/components/dashboard/DashboardWidgetPopularKeywordsTable.js) and [`SearchConsoleDashboardWidgetKeywordTable`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetKeywordTable.js) component should be migrated to functional components using the datastore entirely, no globals and no legacy data API.
* Refactoring map:
    * `dashboard/DashboardWidgetPopularKeywordsTable.js` and `dashboard/SearchConsoleDashboardWidgetKeywordTable.js` should be combined into a single `dashboard/DashboardPopularKeywordsWidget.js` (refactored), plus `dashboard/LegacyDashboardWidgetPopularKeywordsTable.js` (legacy 1) and `dashboard/LegacySearchConsoleDashboardWidgetKeywordTable.js` (legacy 1). The refactored widget component should access the datastore for the main API data.
    * `dashboard/DashboardPopularity.js` should simply be renamed to `dashboard/LegacyDashboardPopularity.js`.
    * `dashboard/DashboardPopularityInner.js` should simply be renamed to `dashboard/LegacyDashboardPopularityInner.js`.
* The new `DashboardPopularKeywordsWidget` component should rely on `select( CORE_SITE ).getCurrentReferenceURL()` so that it uses the site URL vs the current entity URL as applicable (the latter e.g. when used in the `pageDashboard` context).
* The new `DashboardPopularKeywordsWidget` component should be registered as a widget with priority 1, width `Widgets.WIDGET_WIDTHS.HALF`, and for the two widget areas `AREA_DASHBOARD_POPULARITY` and `AREA_PAGE_DASHBOARD_POPULARITY`.
    * The latter widget area is currently called `AREA_PAGE_DASHBOARD_TOP_QUERIES`. This should be changed as part of this issue, i.e. rename it to `AREA_PAGE_DASHBOARD_POPULARITY`.

#### Stage 1
* Rename the following files and components accordingly:
  * `assets/js/modules/search-console/dashboard/DashboardWidgetPopularKeywordsTable.js` ->
    `assets/js/modules/search-console/dashboard/LegacyDashboardWidgetPopularKeywordsTable.js`;
  * `assets/js/modules/search-console/dashboard/SearchConsoleDashboardWidgetKeywordTable.js` -> 
    `assets/js/modules/search-console/dashboard/LegacySearchConsoleDashboardWidgetKeywordTable.js`;
  * `assets/js/modules/search-console/dashboard/DashboardPopularity.js` ->
    `assets/js/modules/search-console/dashboard/LegacyDashboardPopularity.js`;
  * `assets/js/modules/search-console/dashboard/DashboardPopularityInner.js` ->
    `assets/js/modules/search-console/dashboard/LegacyDashboardPopularityInner.js`.
* Update:
  * `index.legacy.js` file to use:
    * `LegacyDashboardWidgetPopularKeywordsTable` instead of `DashboardWidgetPopularKeywordsTable`;
    * `LegacyDashboardPopularity` instead of `DashboardPopularity`.

#### Stage 2
* Craete `assets/js/modules/search-console/dashboard/DashboardPopularKeywordsWidget.js` file;
* `DashboardPopularKeywordsWidget.js` file should:
  * Define a new functional component with `DashboardPopularKeywordsWidget` name;
  * Use `useSelect` hook and the following selectors:
    * `getCurrentReferenceURL` selector from the `core/site` datastore to retrieve the current reference URL;
    * `getDateRange` selector from the `core/user` datastore to retrieve the current date range;
    * `getReport` selector from the search-console datastore (implemented in #1774) to retrieve the current search analytics.
       * Use `query` dimension, `10` as limit, current reference URL and date range information to compose options object and pass it into the getReport selector.
  * Replicate the logic from the legacy comonent (either `DashboardWidgetPopularKeywordsTable` or `SearchConsoleDashboardWidgetKeywordTable`) to render keywords table widget.

#### Stage 3
* Rename `AREA_PAGE_DASHBOARD_TOP_QUERIES` to be `AREA_PAGE_DASHBOARD_POPULARITY` in `assets/js/googlesitekit/widgets/default-areas.js` and `assets/js/googlesitekit/widgets/register-defaults.js` files;
* Update `domReady` callback in the `assets/js/modules/search-console/index.js` file (added in the #1897):
  * Register `DashboardPopularKeywordsWidget` widget with the following arguments:
    * A string `searchConsolePopularKeywords` as widget slug;
    * Settings object where:
      * `component` is `DashboardPopularKeywordsWidget`;
      * `width` is `Widgets.WIDGET_WIDTHS.HALF`;
      * `priority` is `1`;
      * `wrapWidget` is `true`.
    * Areas array that includes `AREA_DASHBOARD_POPULARITY` and `AREA_PAGE_DASHBOARD_POPULARITY` imported from `googlesitekit/widgets/default-areas`.

## QA Brief

* In a development build, the new Popularity widget should render correctly in the Site Kit dashboard. It should behave the same way as the old ones.
* In a development build, the new Popularity widget should render correctly in the Site Kit single URL details view. it should behave the same way as the old ones.
* Links from the single URL details view should include the page query parameter.
* It should be tested that they display errors if e.g. the API request goes wrong - they shouldn't keep loading infinitely in such a case (try e.g. to block client-to-server requests to cause an error).
* The old/legacy Popularity widget should continue to show up in both development and production builds and behave like before.

## Changelog entry

* Migrate Search Console Top Keywords widget to new Widget API.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Setup SK on a site with lots of search console data, ran a series of tests:

Dashboard:
![image](https://user-images.githubusercontent.com/57115907/93975842-e58f8d00-fd2c-11ea-9907-eda52b404d16.png)

Detailed page stats:
![image](https://user-images.githubusercontent.com/57115907/93975938-11ab0e00-fd2d-11ea-8428-c14b57b3f159.png)

Adjusting timeline:
![image](https://user-images.githubusercontent.com/57115907/93975973-1ff92a00-fd2d-11ea-8220-7965410d0685.png)

Mobile:
![image](https://user-images.githubusercontent.com/57115907/93976090-49b25100-fd2d-11ea-9678-c14f79e70119.png)

Legacy:
![image](https://user-images.githubusercontent.com/57115907/93976118-559e1300-fd2d-11ea-8f94-4406a7b6e8db.png)

Passed QA ✅
