### ISSUE TITLE
Issue Accessing Data Error

### ISSUE THREAD

**Issue by jdavini23** [google/site-kit-wp#19]
Once the plugin is installed and I go to set up the client configuration it has it tells me that it has issues accessing data and to Reauthenticate my google account as seen below - 
<img width="1440" alt="Screenshot 2019-06-20 12 28 25" src="https://user-images.githubusercontent.com/13425128/59876010-37da4500-9357-11e9-8b5c-cfa0b854a0d7.png">

Once I click that it crashes and sends me an email containing this information with error:

An error of type E_ERROR was caused in line 651 of the file /www/shesocial_856/public/wp-content/plugins/google-site-kit/vendor/google/auth/src/OAuth2.php. Error message: Uncaught InvalidArgumentException: missing the required redirect URI in /www/shesocial_856/public/wp-content/plugins/google-site-kit/vendor/google/auth/src/OAuth2.php:651
Stack trace:
#0 /www/shesocial_856/public/wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php(340): Google\Auth\OAuth2->buildFullAuthorizationUri(Array)
#1 /www/shesocial_856/public/wp-content/plugins/google-site-kit/includes/Core/Authentication/Clients/OAuth_Client.php(444): Google_Client->createAuthUrl()
#2 /www/shesocial_856/public/wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php(502): Google\Site_Kit\Core\Authentication\Clients\OAuth_Client->get_authentication_url('https://shesoci...')
#3 /www/shesocial_856/public/wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php(189): Google\Site_Kit\Core\Authentication\Authentication->handle_oauth()
#4 /www/shesocial_856/public/wp-includes/class-wp-hook.php(286): Google\Site_Kit\Core\Authentication\Authentic

**Comment by jamesozzie** [comment]
Thanks for the info and contents. There is an open #12 issue for the "Issue accessing data" notice, but can you confirm you see this notice after clicking on the "Proceed" button after pasting in your Client ID?

Can you also try opening the project from your Developers Console and deleting the Client ID before trying again in cognito mode?

**Comment by jdavini23** [comment]
Oops! My fault on that. 

Also, before nothing happened when I clicked the proceed button, when I opened the console there were some errors, but then I refreshed the page with the console open and then was able to proceed without any issues. 

I was able to get through the initial setup now fine.
