### ISSUE TITLE
Set expectations after setup of GTM module  

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#190]
For most of the modules (GA, PSI, AdSense), a new section/stats appear in the dashboard after setup is complete.
But for GTM, there is no module, we only do the provisioning via the plugin. Let's update the copy on the setup screen to make sure user expectations are set correctly.

![GTM-setup-copy](https://user-images.githubusercontent.com/28811945/61006564-44d3ce00-a330-11e9-989e-d5d0ae76836a.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by JayHoltslander** [comment]
**Aside:** The only way I knew that this was what activating the GTM module actually does, was from stumbling across this Github issue. Going back and disabling it now to prevent double placement.

**Comment by marrrmarrr** [comment]
The UI text has since been updated, this issue is no longer relevant.
