### ISSUE TITLE
Migrate Analytics Popular Pages dashboard widget to use Widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1900]
The current Analytics `AnalyticsDashboardWidgetPopularPagesTable` widget should be migrated to use the Widgets API (which is behind a feature flag), while maintaining the current version as legacy components. Those will be removed only once all widgets have been migrated so that we can do the entire switch.

Some general practices for migrating:
* The migration should happen by fully **re-implementing** the components: In other words, the existing components should keep their current functionality, they should **not** use the datastore. Those legacy components should be prefixed with `Legacy*`.
* A good starting point is probably to copy the components into new files and go from there, while renaming the old ones and leaving them untouched.
* For the refactored version, _only_ the actual widget components should be fully responsible for retrieving data from the datastore. If they rely on further `common` components for UI, these should receive such data via props.
* If there are UI parts that can be reused between the new and legacy components, those can be outsourced into `common` components, however as mentioned above **it is important that the legacy components keep using the legacy data API and are not switched to the datastore**. Only the new ones should be.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`AnalyticsDashboardWidgetPopularPagesTable`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetPopularPagesTable.js) component should be migrated to a functional component using the datastore entirely, no globals and no legacy data API.
* Refactoring map:
    * `dashboard/AnalyticsDashboardWidgetPopularPagesTable.js` should become `dashboard/DashboardPopularPagesWidget.js` (refactored), and `dashboard/LegacyAnalyticsDashboardWidgetPopularPagesTable.js` (legacy). The refactored widget component should access the datastore for the main API data.
* The new `DashboardPopularPagesWidget` should return `null` if the Analytics module is not active. _Only_ otherwise Analytics data should be requested, i.e. this probably needs to go into a separate component `DashboardPopularPages`, since hooks cannot run conditionally (we use `*Widget` as top-level entry point while the un-suffixed version is essentially the main part of it, without any extra checks for active modules etc.).
* The new `DashboardPopularPagesWidget` component should be registered as a widget with priority 2, width `Widgets.WIDGET_WIDTHS.HALF`, and for the widget area `AREA_DASHBOARD_POPULARITY`.

#### Stage 1
* Rename `assets/js/modules/analytics/dashboard/AnalyticsDashboardWidgetPopularPagesTable.js` file to be `assets/js/modules/analytics/dashboard/LegacyAnalyticsDashboardWidgetPopularPagesTable.js`;
* Rename `AnalyticsDashboardWidgetPopularPagesTable` component in the `LegacyAnalyticsDashboardWidgetPopularPagesTable.js` file to be `LegacyAnalyticsDashboardWidgetPopularPagesTable`;
* Update `index.legacy.js` file to use `LegacyAnalyticsDashboardWidgetPopularPagesTable` instead of `AnalyticsDashboardWidgetPopularPagesTable`.

#### Stage 2
* Create `assets/js/modules/analytics/dashboard/DashboardPopularPagesWidget.js` file;
* `DashboardPopularPagesWidget.js` file should:
  * Import `getTopPagesReportDataDefaults` from the `assets/js/modules/analytics/utils/index.js` file.
  * Define a new functional component with `DashboardPopularPagesWidget` name;
  * Use `useSelect` hook and the following selectors to pull data required for the widget:
    * `getDateRange` selector from the `core/user` datastore to retrieve the current date range;
    * `getReport` selector from the analytics datastore to retrieve report data.
      * Use `getTopPagesReportDataDefaults` function call results and date range information to compose options object and pass it into the `getReport` selector.
  * Return `PreviewTable` component while data is being fetched (like it is done in the legacy component);
  * Replicate the logic from the legacy comonent to render popular pages widget;
  * Wrap rendered component with the `Widget` component that has `analyticsPopularPages` slug  and `googlesitekit-widget--no-padding` class, and return it.
* Export a component enhanced with `whenActive` HOC (see Stage 2 in #1896) that uses `analytics` as module name.

#### Stage 3
* Update `domReady` callback in the `assets/js/modules/analytics/index.js` file (added in the #1896):
  * Register `DashboardPopularPagesWidget` widget with the following arguments:
    * A string `analyticsPopularPages` as widget slug;
    * Settings object where:
      * `component` is `DashboardPopularPagesWidget`;
      * `width` is `Widgets.WIDGET_WIDTHS.HALF`;
      * `priority` is `2`;
      * `wrapWidget` is `false`.
    * Areas array that includes just `AREA_DASHBOARD_POPULARITY` imported from `googlesitekit/widgets/default-areas`.

## QA Brief

* In a development build, the new Popular Pages widget should render correctly in the Site Kit dashboard. It should behave the same way as the old ones.
* It should be tested that the widget displays errors if e.g. the API request goes wrong - they shouldn't keep loading infinitely in such a case (try e.g. to block client-to-server requests to cause an error).
* The old/legacy Popular Pages widget should continue to show up in both development and production builds and behave like before.

## Changelog entry

* Migrate Analytics Popular Pages widget to new Widget API.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
CR looks good here – assigning to @felixarntz to respond to a few of my questions on the PR.

**Comment by felixarntz** [comment]
@eugene-manuilov @ryanwelcher Feedback is similar to the one on the previous widget migration PRs. Let's try to get #1898 in and then complete the remaining ones.

**Comment by cole10up** [comment]
**Tested**

Installed latest development build and confirmed popular pages widget:

![image](https://user-images.githubusercontent.com/57115907/93846008-a17e8880-fc57-11ea-9105-3622b498e48b.png)

Confirmed all links within popular pages drive to the correct detailed page stats
![image](https://user-images.githubusercontent.com/57115907/93846030-b4915880-fc57-11ea-8fac-3af040392ed0.png)

Blocking the API doesn't load the widget data:
![image](https://user-images.githubusercontent.com/57115907/93846210-4731f780-fc58-11ea-8f2f-efe27672725f.png)

Passed QA ✅
