### ISSUE TITLE
Add support for paginated content to entity detection

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1911]
Follow-up to #174: The `WP_Query_Factory` already supports detecting paginated content from URLs, parsing it into the correct `WP_Query` arguments. However, the `Entity_Factory` at the moment still ignores pagination, which means that Site Kit right now does not provide insights for URLs which are for paginated content other than page 1. This is less important to cover than the different content types in general, but should still be implemented for completeness.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a `WP_Query` is for an archive page greater than 1 (i.e. `paged` argument is present and greater than 1), Site Kit should detect this as expected.
* When a `WP_Query` is for an additional page of a single post (this is _very_ rarely used, but you can paginate a single post using a `nextpage` tag or block), Site Kit should detect this as expected.
* In both cases, the entity should then use a modified URL that links to that page, using either the pagination permastruct if pretty permalinks are enabled, or a regular `paged` / `page` query argument otherwise.
    * For building these URLs, let's look at how WordPress core builds such URLs, e.g. in its posts pagination and post pagination functions.
* Note that there are already several test cases in place in `Entity_FactoryTest` for paginated content. These all have `TODO` annotations to update their expected entity URLs. A good approach is probably to update these tests as mentioned there and only then implement the actual production code changes to make them pass.

## Implementation Brief

Run php unit tests on `tests/phpunit/integration/Core/Util/Entity_FactoryTest.php` and ensure they all pass.
$ `./vendor/bin/phpunit tests/phpunit/integration/Core/Util/Entity_FactoryTest.php`
Next update `data_from_wp_query()` and change the `11` `TODO` cases to the correct URLs.
Run php unit tests again and ensure that they are failing, when they all pass the implementation is complete.

In includes/Core/Util/Entity_Factory.php

Update the following functions to take an optional `$page` parameter
```
create_entity_for_term()
create_entity_for_author()
create_entity_for_post_type()
create_entity_for_post()
create_entity_for_posts_blog()
```

Making use of `$query->is_paged()` https://developer.wordpress.org/reference/classes/wp_query/is_paged/ and the query `paged` param to the above functions.
Update the url we pass to the call to `new Entity` to include the page number using add_query_arg https://developer.wordpress.org/reference/functions/add_query_arg/

## QA Brief

Verify that the Entity Dashboard pages are now correctly showing the paginated URL for a given page.

* Create enough posts in WordPress to enable pagination.
* Navigate to the front page, and then to **Page 2** (or, any page other than Page 1).
![image](https://user-images.githubusercontent.com/18395600/150815652-fdae8559-3ed7-4afd-a73a-8589bf566440.png)
* Make a note of the URL, in particular, the path/query string which includes the page number.
![image](https://user-images.githubusercontent.com/18395600/150816041-31014603-b79a-4a4d-8a1e-0538a1edc954.png)
* Hover over the Site Kit menu bar item and click on **More details** to navigate to the Entity Dashboard for the page.
![image](https://user-images.githubusercontent.com/18395600/150816400-5990eab3-3b51-4388-b5c0-64d81b004591.png)
* Verify the Entity URL matches the page you just came from (note, if you are using the Developer Settings plugin the domain may differ but the path/query string should match).
![image](https://user-images.githubusercontent.com/18395600/150817757-322e07d4-8535-4c93-8055-58fb8955a612.png)
* Similarly verify the pagination for:
  * Posts by author, category, and date, and for a paginated post (a post with page breaks inserted in it).
  * Different permalink settings (see `/wp-admin/options-permalink.php`) - notable with permalinks disabled (the **Plain** setting) and enabled.

## Changelog entry

* Add support for paginated content to entity detection

**Comment by tofumatt** [comment]
IB looks good to me!

IB ✅

**Comment by techanvil** [comment]
Unfortunately, the IB is lacking some detail here, and following it doesn't result in the tests passing. The expected test URLs look like `https://example.com/blog/page/3`, but adding a `page` query param as per the IB results in a corresponding URL of `https://example.com/blog/?page=1`.

That's because the expected URLs follow the permalink structure, but permalinks are not covered by the IB.

It looks like we need to copy some of the logic from WordPress in [`paginate_links`](https://github.com/WordPress/WordPress/blob/e07b5af0423ea294e5cc0987a9ffde0cb3835221/wp-includes/general-template.php#L4203), at a minimum, possibly also referring to some functionality within [`link-template.php`](https://github.com/WordPress/WordPress/blob/master/wp-includes/link-template.php). It's quite tricky trying to get a definitive picture of what the solution is here.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Entity Dashboard pages are now correctly showing the paginated URL for a given page.

- Verified pagination for Posts by author, category, and date, and for a paginated post.
- Verified the Entity URL matches the page from which we redirected, and clicking on the link navigate user to the same page.
- Verified functionality when UFD is enabled.
- Verified functionality when UFD is disabled.
- Verified with different permalink settings. 

<details>

1. When permalink - Plain setting is enabled.

https://user-images.githubusercontent.com/94359491/153162114-e2d47806-2a00-41da-a33a-1d9179fe8103.mp4

2. When Permalink - Plain setting is disabled.


https://user-images.githubusercontent.com/94359491/153162254-a5d385cd-9c1d-4ce5-bd65-e74ac553c567.mp4

</details>

cc @wpdarren
