### ISSUE TITLE
Erro para anúncios

### ISSUE THREAD

**Issue by PortalOeste** [google/site-kit-wp#1913]
Olá, ao adicionar o site no Site Kit, diz você precisa corrigir algumas coisas antes de podermos conectar o Site Kit à sua conta do AdSense. 
No ADS tem a notificação: Encontramos um problema na string de TC do IAB em um ou mais dos seus sites/apps. Esses erros podem afetar a veiculação de anúncios para usuários europeus. Há um relatório detalhado disponível na página "Consentimento dos usuários da UE".

Não consegui localizar e identificar para resolver o problema.

**Comment by jamesozzie** [comment]
@PortalOeste Sorry to hear you've had trouble setting up AdSense on your site via Site Kit. Unfortunately we can only assist with plugin related queries, with the notification and email you received not relating to the plugin or plugin configuration. 

The best resource for AdSense related queries would be the [AdSense Help Center](https://support.google.com/adsense/?hl=en#topic=3373519).
