### ISSUE TITLE
readme. 

### ISSUE THREAD

**Issue by hildaaudrey** [google/site-kit-wp#1914]
[](README.md) [README.md](README.md) [README.md](README.md) ## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@hildaaudrey For general queries we've moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue. 

If you're looking to submit a feature request or product enhancement feel free to add more context in the description and re-open this issue.
