### ISSUE TITLE
Only query Search Console data for the current website

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1917]
## Bug Description

By default, queries to Search Console API include results for all URLs that are associated with the connected Search Console property. In most cases (e.g. URL properties), all these URLs are associated with the current site by definition - however, it isn't necessarily like that for domain properties, which are always for an entire second-level domain (i.e. may include URLs from other sites such as subdomains or subdirectory sites).

## Screenshots

* I have Site Kit set up on my personal main website, using a domain property for Search Console.
* However, I also have an entirely separate website on a subdomain where I post random cocktail pictures (which apparently is more popular in Search than my main site 😄 ).
* As you can see below, Search Console in Site Kit certainly includes data for that other site, which shouldn't be the case.

![Screenshot 2020-08-14 at 13 33 33](https://user-images.githubusercontent.com/3531426/90290457-c569d580-de32-11ea-938f-111b4fec70b8.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All Search Console API queries from Site Kit should only take URLs which are part of the current reference site into account.

## Implementation Brief

* In `Search_Console::create_search_analytics_data_request`, _always_ include a dimension filter with:
    * dimension `page`
    * operator `contains`
    * expression of the current reference site URL, without trailing slash
* If `page` argument is provided (as already possible before), combine that dimension filter with the above one into a single dimension filter group where both filters have to be satisfied. This ensures `page` cannot refer to a URL outside of the site, which should be expected behavior.
* Merge #1918.

## QA Brief

This is hard to manually replicate without sufficient time investment, unless you already have that setup. Therefore, feel free to go over that together with me (@felixarntz), as I have this kind of setup.

* Setup two separate WordPress sites where one is on a subdomain of the other.
* Set up a Search Console domain property for the second-level domain (has to be done manually, Site Kit will use domain properties if they exist, but cannot set them up).
* Put some content on the subdomain site and search for it in various ways in Google search so that Search Console over time picks this up. May take a couple days.
* Set up Site Kit on the second-level domain site.
* Without this issue fixed, queries would include data for the subdomain site too. After the fix for this issue, it should only include data for the second-level domain site as expected.

Apart from this, it should also be verified this doesn't change the Search Console data shown for the more common URL properties.

## Changelog entry

* Ensure Search Console data in Site Kit only includes data for the current site even when using a domain property.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested** with @felixarntz on a call

On a domain with sub domains notice cocktail names being displayed prior to the fix below. These cocktail names exist on a subdomain but are displayed on the current site
![image](https://user-images.githubusercontent.com/57115907/91462785-6f882b00-e83f-11ea-802d-36985fa86fe4.png)

After the fix:
![image](https://user-images.githubusercontent.com/57115907/91462996-b4ac5d00-e83f-11ea-8019-bed17178a29d.png)

This is confirmed fixed. Passed QA ✅
