### ISSUE TITLE
Make site owner notifications more dynamic

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#192]
Don't show notifications that encourage module setup after user has clicked on it once or make it dynamic so the user is not asked to set up the same module after they have already set it up.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@bjackson27 could you confirm if there are module setup notifications other than this one? 

![module-setup](https://user-images.githubusercontent.com/13304791/61631012-7b430e80-ac89-11e9-8b8c-ea24cc8f10eb.png)

**Comment by marrrmarrr** [comment]
Closing this issue -- part of it is no longer relevant, and the general UI will be addressed by the visual language redesign.
