### ISSUE TITLE
Analytics opt-out for logged-in users not working for Web Stories

### ISSUE THREAD

**Issue by swissspidy** [google/site-kit-wp#1920]
## Bug Description

#1596 added analytics support for Web Stories, but we missed to account for the tracking opt-out for logged-in users.

The Analytics module does this by hooking into `wp_head`:

https://github.com/google/site-kit-wp/blob/95f876b4a6d8050a506828005b775ea580a4335e/includes/Modules/Analytics.php#L126-L134

However, that action is not run for Web Stories. For Web Stories, there's a custom `web_stories_story_head` action that has the same effect.

## Steps to reproduce

1. Update settings to exclude logged-in users from analytics
1. View a single web story
1. Notice absence of `__gaOptOutExtension`

## Additional Context

Site Kit 1.14.0
Web Stories 1.0.0 Beta 1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Opting out of tracking for logged-in users should work for stories from the Web Stories plugin.

## Implementation Brief

* Hook into `web_stories_story_head` to call `print_tracking_opt_out()` if tracking is disabled

## QA Brief

1. Install the Web Stories plugin alongside Site Kit.
2. Activate the Analytics module and ensure the snippet is being placed by Site Kit. Also ensure that logged-in users are not being tracked.
3. Create a story and open it in the frontend.
4. Ensure that the HTML source code contains the script containing `__gaOptOutExtension` which is rendered by Site Kit (there's an HTML comment above it indicating that it's from Site Kit).

## Changelog entry

* Fix opting out of Analytics for logged in users not working correctly for Web Stories.

**Comment by swissspidy** [comment]
cc @felixarntz

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed latest develop zip, setup and activated SK.

Installed and activated Web Stories:
![image](https://user-images.githubusercontent.com/57115907/91383485-1ab5c780-e7e1-11ea-855b-fe30b0182873.png)

Activated Analytics:
![image](https://user-images.githubusercontent.com/57115907/91385271-623e5280-e7e5-11ea-84bb-4b62d03e00c6.png)

![image](https://user-images.githubusercontent.com/57115907/91385308-784c1300-e7e5-11ea-9ece-6a9b3750ad16.png)

Confirmed logged in user isn't being tracked:
![image](https://user-images.githubusercontent.com/57115907/91385330-813ce480-e7e5-11ea-9dd8-d00e306b9bde.png)

Sessions and users remained the same:
![image](https://user-images.githubusercontent.com/57115907/91385347-8863f280-e7e5-11ea-8a11-ef249ede0f4f.png)

Confirmed source code:
![image](https://user-images.githubusercontent.com/57115907/91385650-3f606e00-e7e6-11ea-9844-91145ac5aa14.png)

Passed QA ✅
