### ISSUE TITLE
Update source links to point to Google service FE appropriate locations

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1923]
Many of Site Kit's widgets include a source link at the bottom. However, most of them right now don't link to specific places relevant for the widget, so they aren't very helpful. Furthermore, sometimes these source links point to the Google service frontend, while other times (e.g. on the dashboard) they point to the respective Site Kit module page.

All source links should be updated to point to the respective Google service frontend, to the respective property/view/container/client/site data and, where possible, to a view that shows the same information that the Site Kit widget shows.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All links to change (see below) should use the respective `getServiceURL` datastore selector, to e.g. inherit the correct Google account indicator.
* The source links on the "Clicks", "Impressions", and "Top search queries for your site" Site Kit dashboard widgets (including single URL details), as well as on the "Top search queries over the last x days" Search Console module page widget, should point to:
    * `https://search.google.com/search-console/performance/search-analytics?resource_id={propertyID}&num_of_days={currentDateRangeDays}`
    * On the single URL details view, the URL should include another query parameter `&page=!{searchConsoleURL}` (see below)
* The source links on the "Unique Visitors from Search" Site Kit dashboard widget and the "Bounce Rate" Site Kit single URL details widget should point to:
    * `https://analytics.google.com/analytics/web/#/report/visitors-overview/a{accountID}w{internalWebPropertyID}p{profileID}/`
    * On the single URL details view, the URL should include a suffix `_r.drilldown=analytics.pagePath:{analyticsPagePath}/` (see below)
* The source links on the "All Traffic" widget area widget on Site Kit dashboard (including single URL details), as well as on Analytics module page, should point to:
    * `https://analytics.google.com/analytics/web/#/report/trafficsources-overview/a{accountID}w{internalWebPropertyID}p{profileID}/`
    * On the single URL details view, the URL should include a suffix `_r.drilldown=analytics.pagePath:{analyticsPagePath}/` (see below)
* The source links on the "Most popular content" Site Kit dashboard widget and the "Top content over the last 28 days" Analytics module page widget should point to:
    * `https://analytics.google.com/analytics/web/#/report/content-pages/a{accountID}w{internalWebPropertyID}p{profileID}/`

`{searchConsoleURL}` is the current URL, escaped for query parameters (e.g. slashes become "%2F").
`{analyticsPagePath}` is the path segment for the current URL, with slashes replaced with "~2F".

_Note that for the Analytics links, we do not have awareness of exact dates on the client, so for now we can't provide date ranges for those links - that would be out of scope._

## Implementation Brief
Some of the components below may have _Legacy_ versions based on work being done on #1896, #1897, #1898, #1899, and #1900 and depending on when the PR for this is created. Please ensure to confirm any naming differences in the tickets listed above should there be any discrepancies.

### Dashboard
* Refactor `DashboardAcquisitionPieChart` or `LegacyDashboardAcquisitionPieChart` if work for #1896 merged to be functional components
	* Refactor the `getSiteKitAdminURL`  call to use the `getServiceURL` from the  `modules/analytics`  datastore passing the appropriate URL information as defined in the AC.
* Refactor  `SearchConsoleDashboardWidgetTopLevel` or `DashboardImpressionsWidget`, `DashboardClicksWidget` and `LegacySearchConsoleDashboardWidgetTopLevel` if work for #1897 is merged to functional components if needed.
	* Refactor the `getSiteKitAdminURL`  call to use the `getServiceURL` from the `modules/search-console` datastore passing the appropriate URL information as defined in the AC.
* Refactor `AnalyticsDashboardWidgetTopLevel`  or `DashboardUniqueVisitorsWidget`, `DashboardBounceRateWidget` and `LegacyAnalyticsDashboardWidgetTopLevel` if work for #1898 is merged to functional components if needed
	* Refactor the `getSiteKitAdminURL`  call to use the `getServiceURL` from the  `modules/analytics`  datastore passing the appropriate URL information as defined in the AC.
* Refactor `AnalyticsDashboardWidgetPopularPagesTable` and `LegacyAnalyticsDashboardWidgetPopularPagesTable` if work for #1900 is merged to be functional components if needed.
	* Refactor the `getModulesData().analytics.homepage` call to use the `getServiceURL` from the  `modules/analytics`  datastore passing the appropriate URL information as defined in the AC.

### Search Console Page
* In `SearchConsoleDashboardWidgetKeywordTable`  or `DashboardPopularKeywordsWidget` and `LegacySearchConsoleDashboardWidgetKeywordTable` is the work for #1899 is merged and update each detail URL to include `&page=!{searchConsoleURL}` as per AC.
### Analytics Page
In `AnalyticsDashboardWidgetTopPagesTable` update each detail URL to include `_r.drilldown=analytics.pagePath:{analyticsPagePath}/` as per AC

## QA Brief

* All of the Source links from both new and legacy widgets should link to the corresponding Google service front end (see ACs for exact URLs).
* Link should show the opens in new tab icon.

## Changelog entry

* Provide accurate deep links for all Search Console and Analytics widgets, pointing to the corresponding location in the Google service frontend.

**Comment by felixarntz** [comment]
@ryanwelcher IB looks good. However, we'll also need to consider the refactored versions of those widgets, if already present. This has to be kind of on demand, based on what is already implemented by the time this issue's PR gets to completion. See #1896, #1897, #1898, #1899, #1900 for relevant issues each of which "copies" (as refactored version) one of the widgets relevant for this issue. Can you add relevant pointers to the IB?

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Removing this from the upcoming release because it touches a bit too much legacy code to be merged this late.

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup develop SK. 

Activated all modules, clicked through each google service link and tested each functioned properly and opened in a new tab.

Analytics:
Audience, Acquisitions, Pages

Adsense:
Page performance, Site performance

Search Console:
Site performance

@felixarntz - Noticed one link on the dashboard for Analytics doesn't open in a new tab below:
![image](https://user-images.githubusercontent.com/57115907/96220503-b17b4680-0f3d-11eb-9c27-191047402030.png)

Source: [Analytics](url) opens in the same window. Should open in a new tab.

**Comment by aaemnnosttv** [comment]
@cole10up @felixarntz in the current release that link goes to Site Kit's Analytics dashboard in WP, not the external service so if that was an intentional change then we likely just missed adding `external` on that link where it wouldn't have had it before.

**Comment by ryanwelcher** [comment]
@aaemnnosttv @felixarntz I'll create a PR for adding the external prop. Apologies for missing it.

**Comment by cole10up** [comment]
**Retested**

Looks good, all links drive to the correct external pages in a new tab.

Passed QA ✅
