### ISSUE TITLE
Specify `permission_callback` for custom post search REST route

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1924]
## Bug Description

Since WordPress 5.5, not providing a `permission_callback` when registering a REST route will trigger a PHP warning via `register_rest_route()`. Site Kit does not currently use that function and instead relies on the `WP_Server::register_route()` call, which is just as fine - it's a bit strange that WordPress core does not trigger the same warning from there - which is why, fortunately, this is a fairly minor concern here right now, since none of our users should see a warning due to that argument being omitted.

However, we should still be fixing that. Our post search route right now is public, and even if it stayed like that, it should receive a `__return_true` callback. However, it probably makes more sense to restrict it to Site Kit users, since there is no purpose to calling it for unauthenticated users anyway, and it's better to be more restrictive than not.

Somewhat related: #1908 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit REST route `core/search/data/post-search` should receive a `permission_callback`.
* The route should be accessible for any user that can `Permissions::AUTHENTICATE`.
* Site Kit should be using the more high-level WP core function `register_rest_route` instead of `WP_REST_Server::register_route`.

## Implementation Brief

* Add a new `$can_authenticate` helper function variable in `REST_Routes::get_routes` to check `current_user_can( Permissions::AUTHENTICATE )`
* Update the `core/search/data/post-search` `REST_Route` definition in `includes/Core/REST_API/REST_Routes.php`
	- Add `permission_callback` with `$can_authenticate` after the `callback` key in its arguments (see the `data` route for an example)
* Add a new public `REST_Route::register` method for consistency with other similar classes such as `Asset` or `Setting` that "own" the definition of their registration
	- Calls `register_rest_route( REST_Routes::REST_ROOT, $this->get_uri(), $this->get_args() )`
	- Update `REST_RouteTest` with a new `test_register` method to cover this behavior
* Delete `REST_Routes::register_route`
* Update `REST_Routes::register_routes`
	- Remove `$server` from its method signature
	- Call `$route->register()` instead
* Update `REST_Routes::register`
	- Remove `$server` from the callback and from the call to `register_routes` as it is no longer used/needed

## QA Brief

* With `WP_DEBUG` and `WP_DEBUG_LOG` enabled, no PHP warnings should be logged to the PHP error log when calling the `core/search/data/post-search` REST datapoint (via searching for a post in the Site Kit dashboard search input).

## Changelog entry

* Provide `permission_callback` to `core/search/data/post-search` datapoint and rely on higher-level `register_rest_route` function from WordPress core.

**Comment by aaemnnosttv** [comment]
@felixarntz per our conversation yesterday, we should also update our route registration to use `register_rest_route` instead of the method on the server as it seems to be the intended way to do this outside of core.

**Comment by felixarntz** [comment]
@aaemnnosttv I've augmented the ACs accordingly.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Confirmed that no REST Route registration warnings are raised for the `post-search` (or any other) Site Kit endpoint.

Also confirmed that removing the added `permission_callback` for the `post-search` route does raise the warning as expected (which didn't happen before).

Changes to `REST_Routes` and `REST_Route` classes look good 👍
