### ISSUE TITLE
Move date range parsing logic and actual dates awareness to the client

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1925]
At the moment, the client fully relies on date ranges such as `last-28-days`. These are then passed to the server where they are parsed into actual start and end dates. There are cases where we need awareness of the actual dates on the client too though.

We've already updated the server-side layers to accept actual start and end dates via #1774, #1775, and #1776, so let's start moving towards that goal where we no longer require that date-parsing logic on the server and can instead just pass through dates to the respective Google API.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new selector `getDateRangeDates( options = {} )` on the `core/user` store:
    * `options.offsetDays` is an integer that is the number of days to offset (e.g. if the API does not include fresh data for the last 1 or 2 days yet). Default should be `0`.
    * `options.compare` is a boolean for whether date ranges to compare should be included. Default should be `false`.
    * `options.weekDayAlign` is a boolean for whether the compared date range should be aligned for the weekdays. Only relevant if `options.compare` is `true`. Default should be `false`. See #1280 for reference on why that exists.
    * The selector should return an object that has `startDate` and `endDate` (format `Y-m-d`). If `options.compare` is true, the object should also include `compareStartDate` and `compareEndDate`. The compare dates should always come _before_ (i.e. if `startDate` is "2020-04-05", `compareEndDate` will definitely not be greater than "2020-04-04").
    * The selector logic should fully replicate the PHP logic from `Module::parse_date_range`, except:
        * It doesn't need `$previous`, since it will always include the previous dates if `options.compare` is `true`.
        * It doesn't need `$multiplier`, since that is only to query an extra period for APIs that don't support multiple date ranges. For those cases, it should be relied upon `options.compare` and then pass `compareStartDate` and `endDate` to the respective API in order to get the full range in one query.
    * Comprehensive Jest test coverage should be added.
* The Analytics `GET:report` datapoint in PHP should support receiving `compareStartDate` and `compareEndDate` arguments. If both of them are provided, they should make up a second date range object for the query.
    * This should only apply if the recently added `startDate` and `endDate` are also present, it shouldn't affect the "legacy" logic that relies on the `dateRange` argument.
* For now, no actual queries should be updated, this can happen in follow-up issues.

## Implementation Brief

* Add a new `selectors.getDateRangeDates` to `assets/js/googlesitekit/datastore/user/date-range.js`
    - Accepts a single optional `options` parameter, which defaults to an empty object, with additional default values for its keys
        - `options.offsetDays` defaults to `0`
        - `options.compare` defaults to `false`
        - `options.weekDayAlign` defaults to `false`
    - The selector should internally select `getDateRange` and parse the returned string into start and end dates based on the range parsed from the string which will be in the format `last-{x}-days` where `{x}` is a positive integer
    - The selector should always return an object with `startDate` and `endDate` keys
        - If `options.compare`, it should also include a `compareStartDate` and `compareEndDate` which is the "previous period" – that is, the same range, but the one previous to the current
        - Additionally, if `options.weekDayAlign`, additional logic is needed to potentially shift the dates of the `compareStartDate` and `compareEndDate` so that they match the same day of the week of the `startDate` and `endDate`.
        Since both ranges are of equal length, shifting it based on start or end date will yield the same result, but `compareEndDate` should never be after `startDate`.
    - All dates should be formatted as `YYYY-MM-DD`
    - Aside from querying the current `dateRange`, the selector should delegate the parsing to a few new utility functions in `assets/js/googlesitekit/datastore/user/utils` based on the given `options`
        - `getPreviousDate( relativeDate, daysBefore )`  
        Parses the given date, and returns the previous date `daysBefore` before the `relativeDate` where `relativeDate` is a date string as `YYYY-MM-DD` and `daysBefore` is an unsigned integer
            - i.e. `endDate = getPreviousDate( today, options.offsetDays )`  
            and `startDate = getPreviousDate( endDate, dateRange )`  
        This also makes testing easier because a fixed dates can be used for the input and expected output.
        - `getPreviousWeekDate( relativeDate, daysBefore )`  
        Similar to `getPreviousDate` but shifts the resulting date so that it returns a date that falls on the same day of the week as the `relativeDate` while preserving the `daysBefore` as a minimum, but it could be up to 6 days more than `daysBefore`.  
            - i.e. `compareEndDate = getPreviousWeekDate( endDate, dateRange )`  
            `compareStartDate = getPreviousDate( compareEndDate, dateRange )`
        - Potentially add a new utility for formatting a `Date` object into a `YYYY-MM-DD` string

Chronologically, the dates should always be in the following order, from past to present:
1. `compareStartDate`
1. `compareEndDate`
1. `startDate`
1. `endDate`
1. – now –

#### Analytics Module

* Update `GET:report` in `Analytics::create_data_request`
    - In the conditional that checks `strtotime( $start_date ) && strtotime( $end_date )` conditionally add another date range to the array if `$data['compareStartDate']` and `$data['compareEndDate']` are also valid dates

#### Tests
* Robust test coverage should be added for the date parsing/calculation utilities used by the `getDateRangeDates` selector using fixed dates
* Tests should be added for the `getDateRangeDates` selector to ensure the expected result is returned given different `options`
    - The added date utility functions can be used to obtain the expected dates to make assertions on the resulting object since these will always be relative to the time the test is run

## QA Brief
Majority of code changes are covered via unit tests.

1. Verify that date ranges (Last 7 Days, Last 14 Days, Last 28 Days, Last 90 Days) within Analytics module still behave the same as before.
2. General quick smoke test to verify no errors around Analytics module.

## Changelog entry

* Introduce `getDateRangeDates()` selector to `core/user` datastore to retrieve actual date strings based on the current date range.

**Comment by felixarntz** [comment]
Flagging this as Good First Issue, mainly because the logic is already defined in PHP and mostly needs to be ported to JS.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Analytics module seems to be functioning normally and data displayed matches the current release.
