### ISSUE TITLE
Error when attempting to connect Adsense on WP.com (Business plan)

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1926]
## Bug Description

A [user in the forums](https://wordpress.org/support/topic/sitekit-rest-api-401-error-while-setting-up-adsense-at-wp-com-business-plan/) reported getting the following error in Site Kit when trying to connect Adsense on WP.com (Business plan) :

```
“Error: The response is not a valid JSON response.”

console : “{“code”:”rest_forbidden”,”message”:”Sorry, you are not allowed to do that.”,”data”:{“status”:401}}”
```

As well as the following 403 error on the request:

![403 error](https://user-images.githubusercontent.com/8108643/90441095-39071f00-e08d-11ea-8c14-270b77b220c1.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

- Related support topic: https://wordpress.org/support/topic/sitekit-rest-api-401-error-while-setting-up-adsense-at-wp-com-business-plan/
- Suspected issue with the firewall at WP.com (Jetpack)
- Potentially other users on the WP.com (business plan) impacted due to the response from support rep to user in the topic. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Another possibly impacted user. Site Health info provided ( Response number 66):
https://wordpress.org/support/topic/error-the-response-is-not-a-valid-json-response-4/#post-13286234

**Comment by masterwali** [comment]
I'm getting the same error.

**Comment by ernee** [comment]
Update that we're working with the team at WP.com to address this issue. We'll update accordingly.

**Comment by ernee** [comment]
Another report in the forums: https://wordpress.org/support/topic/ad-sense-configuration-on-google-site-kit/

**Comment by JoshuaGoode** [comment]
Thanks for the report.  @adamsilverstein reached out and we were able to get this resolved. 

To review, Site Kit responds with a 403 payload when additional permissions are required -- prompting the user to grant Site Kit permissions to create a new property.

Something like:

> {"code":"missing_required_scopes","message":"You\u2019ll need to grant Site Kit permission to create a new Analytics property on your behalf.","data":{"status":403,"scopes":["https:\/\/www.googleapis.com\/auth\/analytics.edit"]}}

Unfortunately, as soon as our side saw the 403 response, we delivered our custom 403 page instead of what Site Kit was trying to send to the user. 

We've now made adjustments to resolve this.  After multiple tests, I can confirm this is now resolved and this issue can be closed.

**Comment by ernee** [comment]
@JoshuaGoode thanks so much for looking into this! We've gotten confirmation from users that they can now connect to Adsense. I will close this topic as resolved.

**Comment by adamdunnage** [comment]
@jimgarrigan Thanks for leaving a comment here. As your issue is with WordPress.com and this isn't a Site Kit specific issue, I would recommend reaching out to the [WordPress.com support](https://wordpress.com/support/help-support-options/) team who should be able to help you further with this.

**Comment by jimgarrigan** [comment]
Hi Adam,
It appears to me t**he problem is partially caused by a custom 403 page configured within NGINX**.

For example, I changed:
**error_page 403 /403-error.html;**
to
**# error_page 403 /403-error.html;**

If someone has a better solution and/or suggestion I am receptive.

Thank you
