### ISSUE TITLE
Add Google Analytics developer ID to Site Kit-placed gtag snippets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1927]
`gtag.js` snippets placed in the frontend by Site Kit should be annotated with Site Kit's developer ID.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's non-AMP `gtag.js` snippet should include `gtag('set', 'developer_id.dZTNiMT', true)`, after the `gtag('js', new Date())` directive.
* This is not supported in AMP (yet), so it should be omitted for now.

## Implementation Brief

* Add developer ID to gtag snippets rendered by `Analytics` class as described in the ACs.
* Merge #1928.

## QA Brief

* Site Kit's Analytics snippet in the frontend (only for non-AMP) should include a segment `developer_id.dZTNiMT`.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅ 

@felixarntz please add a QA Brief as well 🙂

**Comment by aaemnnosttv** [comment]
@felixarntz the PR is merged, it just needs the QA Brief and then it's ready for QA 👍

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest develop release candidate. Activated, installed setup SK.

Activated and setup Analytics module, checked source code:
![image](https://user-images.githubusercontent.com/57115907/91386115-2c9a6900-e7e7-11ea-9f69-f0765cbcb108.png)

Passed QA ✅
