### ISSUE TITLE
Increase font size in admin bar

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#193]
Currently the text in the admin bar is very small, it'd be great to make it bigger

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Adjust font-size 
* Adjust spacing 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@bjackson27 could we get a few mocks of alternative versions with different font sizes?

**Comment by aaemnnosttv** [comment]
@marrrmarrr this is likely a symptom of #888, but it's unclear from the initial issue if this is referring to wp admin or front end. I think we can probably address the sizing as part of that issue though.

**Comment by aaemnnosttv** [comment]
@marrrmarrr this is a bit of an older one which should have been partially (if not completely) addressed by #888 (inconsistencies between themes). Can you take another look and see if this is still relevant?

**Comment by marrrmarrr** [comment]
@aaemnnosttv thanks for the reference to the other issue. Beyond the font sizes, I think the bigger issue is that we're stretching the contents of the admin bar to the width of the screen, which results in huge white spaces on laptop screens and even more on desktop screens. 
We should reconsider perhaps left-aligning the contents of the admin bar -- I think the better approach here is redesigning the entire layout. I'll close this issue and discuss with the the designer.
