### ISSUE TITLE
Consent API Feature Request

### ISSUE THREAD

**Issue by AertHulsebos** [google/site-kit-wp#1930]
## Feature Description

Comply with GDPR and other privacy laws by conforming to the Consent API.
---------------
Copy of: https://wordpress.org/support/topic/consent-api-integration/

Hi team,

To be able to use Google Site Kit in a GDPR compliant way a method would be needed to conditionally allow or disallow the scripts to run, based on user consent and/or region.

For our plugin https://wordpress.org/plugins/complianz-gdpr/ I’ve been looking into creating an integration, but there doesn’t seem to be a filter to easily add some classes or attributes to scripts, which is needed to handle this.

Even better would be to create an integration with the WP Consent API, which we expect to get merged in WordPress core 5.6/5.7. This would make this integration useful for all cookie management plugins which support the consent API, currently Cookiebot and Complianz.

The WP Consent API allows any cookie management plugin to manage consent for plugins that integrate with it.

For example, depending on the country where the website visitor is browsing the website, consent would be needed for anonymous statistics, or for statistics (not anonymous), or no consent is required at all.

https://make.wordpress.org/core/features/
https://github.com/rlankhorst/wp-consent-level-api/
https://wpconsentapi.org/

Let me know if you have any questions about this!

Rogier

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This is currently being prioritized via #462, please follow along there for updates. I'll close this one as a duplicate.
