### ISSUE TITLE
Add number of connected users to Site Health information

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1932]
Site Kit's Site Health information should include the number of connected users.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's Site Health information should contain a row "Connected user count", following "User Status".
* It should display the number of users that currently have a Site Kit access token.

## Implementation Brief

* Add `Debug_Data::get_connected_user_count_field()`:
    * Query user count that have a SIte Kit access token set.
    * Use `label` "Connected user count", and specify the user count as `value`.
        * `debug` isn't necessary since it can use the same as `value`.
* Add `connected_user_count` key after `user_status` in `Debug_Data::get_fields()` and call the new `get_connected_user_count_field()` for it.

## QA Brief

* Set up Site Kit for multiple users.
* Confirm that the Connected user count is shown in Site Health and reflects the correct number of authenticated users.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Set up Site Kit with multiple users.

Confirmed connected users count is shown in Site Health and reflects the correct number of authenticated users:
