### ISSUE TITLE
Allow combining equal elements in datastore collect utilities

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1937]
## Feature Description

Currently our datastore collection utilities for aggregating selectors, actions, reducers, etc all raise errors in the presence of duplicate elements. This is due to the way the `collect` utility is implemented which prevents passing any two items with the same name:
https://github.com/google/site-kit-wp/blob/82d6fa72656d48de04d9c9b91462471ed28c0227/assets/js/googlesitekit/data/utils.js#L51-L56

The same goes for `collectNames`
https://github.com/google/site-kit-wp/blob/82d6fa72656d48de04d9c9b91462471ed28c0227/assets/js/googlesitekit/data/utils.js#L149-L150

This causes aggregate stores to be overly-concerned with the sub-stores they're composed of making store composition unnecessarily complicated
https://github.com/google/site-kit-wp/blob/e2b60a6f7778536b94ae2d321cc9f6b860b88edd/assets/js/googlesitekit/modules/create-module-store.js#L78-L100

This prevents us from sharing common partials between stores, such as `Data.commonActions` and `Data.commonControls`. Furthermore, it obscures what a store contains because combining stores can only be additive so the only way to see what it has is to manually traverse the stack of compositions or inspect the end result in the browser/test/log/etc.

Since the intention of the validation that's present in the `collect` utilities is to prevent overwriting something unintentionally by merging two _different implementations_ that both define a selector or action by the same name, we should update this to only error if the values are in fact different. So far, these values should be the same since they're mostly coming from static exported values

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Combining duplicate same-key same-value elements in a store should not raise an error 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv I'm still leaning towards not doing this. Maybe we can refine this in a better way and centralize inclusion of the common components, but I think having the limitation of not being able to combine similarly named actions/selectors/etc. continues to be more valuable than harmful, especially as our datastores grow.

Maybe there's a way to rephrase this and improve the surface for (undesired) conflicts in another way?

**Comment by tofumatt** [comment]
Raising errors on overwriting/name collisions is a purposeful feature of our combine/`collect` utilities; it prevents bugs (eg. by preventing us from overwriting selectors/functions).

Given it has been without issue for years, I think we can safely close this one as a won't fix 🙂
