### ISSUE TITLE
Introduce (internal) registry for modules in PHP

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1939]
While we shouldn't _yet_ allow 3rd parties to register their own modules in PHP, with this being a future requirement we can start working towards that goal. We already provide the necessary foundation in PHP to implement a custom module class, however registration is a key aspect that is currently missing.

Following this enhancement, we should continue to evaluate our current class infrastructure relevant for implementing a module class, including the necessary interfaces and traits, and flag any potential complexities or oddities that can be improved.

(Note that, while Site Kit uses a single gigantic class for each module, the current architecture doesn't dictate for it to be that way. The approach of using a single class as entrypoint to everything should be maintained, however as soon as module registration actually becomes available for 3P, we should recommend to separate functionality into different classes controlled by the registered module main class.)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new class `Google\Site_Kit\Core\Modules\Module_Registry` should be introduced, with the following public methods:
    * `register( string $classname )`: Registers a module's PHP class name.
        * The method should throw an exception if the class does not extend `Google\Site_Kit\Core\Modules\Module`.
    * `get_all()`: Returns the indexed array of all registered module PHP class names.
* `Google\Site_Kit\Core\Modules\Modules` should use the registry:
    * In the `get_available_modules` method's clause which loads the modules, create an instance of the new registry class. Then, call the `register` method for each of the existing Site Kit classes, and afterwards the `get_all` method to get an array of class names like there is currently.
        * In the future, once ready to expose to 3P, this will fire an action hook like e.g. `googlesitekit_register_modules` to allow third parties to register their own on the registry instance.
* Make the following methods non-abstract as they don't really need to be implemented by child classes:
    * `Google\Site_Kit\Core\Modules\Module::setup_services`: Should return an empty array in its base implementation.
    * `Google\Site_Kit\Core\Modules\Module::create_data_request`: Should throw `Google\Site_Kit\Core\REST_API\Exception\Invalid_Datapoint_Exception` in its base implementation.
    * `Google\Site_Kit\Core\Modules\Module::parse_data_response`: Should pass through `$response` in its base implementation.
* In `Google\Site_Kit\Core\Modules\Module::validate_data_request`, populate the `'request_scopes_message'` key with a default message if it is not specified: "You’ll need to grant Site Kit permission to do this.".
* All existing module classes' `create_data_request` and `parse_data_response` implementations should be updated to call the parent method at the end of the method instead of "duplicating" the default code which now happens in the base class.

## Implementation Brief

* Merge #2305 

## QA Brief

* All modules should be present and activate normally
* Check that all modules which request data are still able to do so as before

## Changelog entry

* Simplify module class infrastructure and implement (internal) module registry.

**Comment by felixarntz** [comment]
IB ✅ 😆

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest release candidate of Site Kit.

Activated and ran tests on each module:

![image](https://user-images.githubusercontent.com/57115907/98210599-aa6ca600-1ef5-11eb-9478-0066ca583846.png)

Adsense:
![image](https://user-images.githubusercontent.com/57115907/98210655-bf493980-1ef5-11eb-88b1-8fc4d6400895.png)

![image](https://user-images.githubusercontent.com/57115907/98210672-c53f1a80-1ef5-11eb-8b5f-c63e784d854c.png)

![image](https://user-images.githubusercontent.com/57115907/98210692-cd975580-1ef5-11eb-974e-1591e6f77b51.png)

Analytics:
![image](https://user-images.githubusercontent.com/57115907/98210720-d8ea8100-1ef5-11eb-9457-ea38ca2c78b1.png)

![image](https://user-images.githubusercontent.com/57115907/98210735-dd169e80-1ef5-11eb-912f-1abecbf0e086.png)

![image](https://user-images.githubusercontent.com/57115907/98210875-1ea74980-1ef6-11eb-8925-5f40bd91b73e.png)

![image](https://user-images.githubusercontent.com/57115907/98210905-2830b180-1ef6-11eb-8723-b92abd448594.png)

Including Search Console:
![image](https://user-images.githubusercontent.com/57115907/98210957-367ecd80-1ef6-11eb-8265-b098f22f2c5c.png)

![image](https://user-images.githubusercontent.com/57115907/98210977-3f6f9f00-1ef6-11eb-8c61-8b2d41e43076.png)

Admin bar:
![image](https://user-images.githubusercontent.com/57115907/98211029-4eeee800-1ef6-11eb-8658-d7c79d84ed03.png)

Tag Manager and Optimize:
![image](https://user-images.githubusercontent.com/57115907/98211124-6c23b680-1ef6-11eb-88f0-dd90dc8fcdfe.png)

Passed QA ✅
