### ISSUE TITLE
Error when connecting Google analytics

### ISSUE THREAD

**Issue by Habibsen** [google/site-kit-wp#194]
here is a picture of it. I have an account for my Analytics so this makes no sense. - 
![image](https://user-images.githubusercontent.com/52763624/61009072-c26bfe00-a371-11e9-9d8f-d0120cf9b20a.png)

**Comment by srcek** [comment]
Same here.

**Comment by Habibsen** [comment]
I tried taking wp-rocket off, but that did not work...

**Comment by jamesozzie** [comment]
@Habibsen Can you try the below, as @srcek suggested there could be another plugin, Ad Blocker or Firewall/security feature causing this error. 

- Remove the [Analytics module](https://i.imgur.com/6ppIDwZ.png) (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
- Temporarily deactivate your other active WordPress plugins
- Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

Let me know if that fixes the issue, if not we can troubleshoot further. If the issue arises again please share any [console errors](https://i.imgur.com/f5WfLb3.png).

**Comment by jamesozzie** [comment]
@Habibsen Have you attempted connecting the Analytics module in Site Kit again? If you are encountering the same issue please let me know the following
- Any security/firewall plugins in use
- Any caching plugins in use
- If ModSecurity is enabled on your web host

**Comment by jamesozzie** [comment]
@Habibsen I will close this issue as I didn't get a response, but of you are encountering the same issue after following the steps advised above feel free to reopen.

**Comment by SaludInfusions** [comment]
> Same here.
> 
> Edit: I managed to solve the problem by disabling WP Super Cache plugin temporarily.

Thanks that worked, been a frustrating night trying to get it linked.
