### ISSUE TITLE
Update invariant use within datastore generator functions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1941]
## Bug Description

In #1801 we updated the way `createFetchStore` works internally so that invalid use raises errors as expected.

As discovered in that issue, the main problem is that errors raised in a generator function do not throw but instead result in a rejected promise which is not handled well.

We still have many instances of `invariant` used within generators in the datastore outside of the `createFetchStore` use.

E.g. https://github.com/google/site-kit-wp/blob/62c82436e2a69f7d7e4c544f07c73d7e838269a8/assets/js/googlesitekit/modules/datastore/modules.js#L181-L183

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `createValidatedAction` utility should be created for simplifying the definition of an async action that has validation
	- It should take two arguments: `validate` (a non-generator function), `actionCreator` (a function which may or may not be a generator that returns and/or yields actions)
* All instances of action creators in the data store which are generators that perform validation on parameters (i.e. `invariant`) should be updated to use the new utility

## Implementation Brief

* Finish and merge https://github.com/google/site-kit-wp/pull/3158
	- Add tests for `createValidatedAction`
	- Update remaining actions

## QA Brief

* Review the codebase to make sure there are no longer any actions defined as generator functions which call `invariant` internally

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz moving this forward to AC as there are still quite a few of these in the codebase.

**Comment by felixarntz** [comment]
@aaemnnosttv I like the approach you're suggesting, great! IB ✅

**Comment by wpdarren** [comment]
@aaemnnosttv just checking this should be a `QA:Eng` ticket since it mentions looking at the codebase?

**Comment by aaemnnosttv** [comment]
Yep, thanks @wpdarren – I've added it now 👍

**Comment by tofumatt** [comment]
QA ✅
