### ISSUE TITLE
Implement setting the admin could switch, so the plugins does not track visitors with DNT client header or GPC enabled

### ISSUE THREAD

**Issue by MikkCZ** [google/site-kit-wp#1946]
## Feature Description

Although the [Do Not Track](https://en.wikipedia.org/wiki/Do_Not_Track) header has not been widely adopted, I still consider it a good manner to honor it, when the user has it enabled. I propose to add an option to the plugin settings, to exclude users with the DNT header enabled the same way like logged-in users are excluded. By default it should be off (ignore the DNT header).

The implementation of honoring DNT can be either on backend (not include the tracking code at all) or in JS (by wrapping the tracking code into the following condition).
```js
if(!(window.doNotTrack === "1" || navigator.doNotTrack === "1" || navigator.doNotTrack === "yes" || navigator.msDoNotTrack === "1")) {
    // all tracking code goes here
}
```

But it would probably be better to utilize what's already in place for excluding logged-in users.

EDIT: There is [Global Privacy Control](https://globalprivacycontrol.org/) as well, which might get higher adoption.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Many thanks for the suggestion, which I've added categorized as a feature request for the team to review. Note that all such suggestions are periodically reviewed by our product team, however there is no ETA for it. Please feel free to add any additional comments or simply keep watch of it's progress here.

**Comment by aaemnnosttv** [comment]
I'm not sure if it makes sense for us to add an additional browser-specific method for opt-ing out of tracking as it is already opt-in by default. We only collect anonymous information from users who opt-in to this to help us improve the plugin and users can manage their preference at any time via the plugin's settings.

**Comment by MikkCZ** [comment]
Just to clarify, the act of installing the plugin is opt-in, but that's done by the site admins. But currently there is no way for the WordPress admins using this plugins to enable visitors of their page to opt-out from that tracking, if they want to honor peoples choice. Maybe the [Global Privacy Control](https://globalprivacycontrol.org/) might be better to use nowadays, instead of DNT.

**Comment by aaemnnosttv** [comment]
I see what you mean now, thanks for clarifying. I've flagged this for review with the team so stay tuned for updates 👍
