### ISSUE TITLE
Fix PHPCS regression no longer flagging several violations

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1948]
For the past few weeks, it looks like PHPCS has no longer been flagging violations when they would have been expected to be flagged. For example, in #1881 there are several occurrences of translation strings without a text domain (intentionally because they should use WP core translations) where that usage was not flagged by PHPCS (should have raised `WordPress.WP.I18n.MissingArgDomain`).

Other cases where I noticed a lack of rule enforcement was when e.g. not using strict comparisons (e.g. `==` or `in_array( $element, $arr )`).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Violations from the `WordPress-Extra` ruleset should be flagged as expected by PHPCS.
* Specifically, a missing text domain should be flagged.
* The `WordPress-Core` ruleset should be omitted from our ruleset since it is included within `WordPress-Extra` anyway.

## Implementation Brief

* Remove `WordPress-Core` rule from `phpcs.xml` and move exclusions to `WordPress-Extra`.
* Remove `WordPress-VIP-Go` rule from `phpcs.xml` and instead include individual high level sub rules (e.g. `WordPressVIPMinimum.Functions`, `WordPressVIPMinimum.Performance`, ...).
    * Add exclusions for sub rules which don't make sense in Site Kit, such as flagging usage of user meta.
* For the `text_domain` property, provide an array since that seems to be required now. Include `google-site-kit` _and_ `default`, which indicates that we use WordPress core translation strings in some places.
    * All core translation strings **must** now explicitly include `'default'` as text domain, which will result in the same core behavior as if there was none. Omitting the text domain though could still happen accidentally, so that will intentionally get flagged by PHPCS and should not happen.
* Fix all violations that now surface after fixing the above.
* Merge #1950.

## QA Brief

* Using a `==` in the codebase should get flagged by PHPCS.
* Omitting a text domain in the codebase should get flagged by PHPCS.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅, errors as expected when those violations are introduced to the code:
<img width="533" alt="Screenshot 2020-08-27 at 15 58 41" src="https://user-images.githubusercontent.com/90871/91459112-2f946880-e87e-11ea-9813-85b6a525e0ac.png">
