### ISSUE TITLE
What should non-admins see instead of CTAs

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#195]
Currently we have CTAs asking the user to set up modules when they don't have them, this makes sense for Admins. Some users (authors/editors) will get the dashboard but won't be able to set up additional modules so it doesn't make sense to display this CTA for them. We'll need to determine what these users should see instead.

We'll also need to consider how we solve this for contributors in the admin bar.

<img width="1187" alt="Screen Shot 2019-05-10 at 11 46 04 AM" src="https://user-images.githubusercontent.com/28811945/61014389-dbae8380-a34c-11e9-9121-9d20869f61e0.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
Since the ACLs for using Site Kit currently allow only admins in WP, this is no longer relevant.
