### ISSUE TITLE
Blank front end after login

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1951]
## Bug Description

As reported in the [WordPress support forums](https://wordpress.org/support/topic/white-screen-of-death-208/#post-13309678) the site is broken at the front end after login.

Currently attempting to recreate, Site Health info provided. 

## Additional Context

 - WordPress 5.5
- WooCommerce Active
- ManageWP MU plugin active (although site not hosted with GoDaddy)
- Similar issue reported in #1637 ([last comment reported today](https://github.com/google/site-kit-wp/issues/1637#issuecomment-679420632))

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by xtomyserrax** [comment]
Hey, isnt this the same issue im experiencing?

https://wordpress.org/support/topic/my-site-doesnt-work-anymore-with-the-newest-update/#post-13312525

**Comment by jamesozzie** [comment]
@xtomyserrax We're investigating this at present, trying to recreate with the same environment. I see you were able to get Site Kit working in the end. Should you encounter anymore issues be sure to get in touch.

**Comment by xtomyserrax** [comment]
Hey I never got Site Kit working. I had to downgrade to 1.13.1 for it to work fine (1.14.0 doesnt work for me)

**Comment by xtomyserrax** [comment]
Okay so this is really weird, apparently reinstalling G Site fixed the issue. I dont really know what was the cause, In the support topic I made in the forum I sent some error logs but not from the debug, sadly I couldnt get them

**Comment by jamesozzie** [comment]
@xtomyserrax Many thanks for the update, appreciate the follow up. I've been unable to recreate the same issue but from following your topic and others the issue may occur intermittently with a combination of plugins. Let us know should you encounter the issue once more.

**Comment by jamesozzie** [comment]
Tested similar setup with the following:
- Same hosting provider
- Varnish enabled at host level
- WP Fastest Cache & the same MU plugins installed
- Elementor v.3.0.0

Unable to reproduce the same issue after various tests, including minifying JS files with the admin bar enabled. Awaiting update from user.

**Comment by xtomyserrax** [comment]
Hey, as additional info, I deactivated ALL plugins and just left G Site enabled and the error still happened to me. Weird that after reinstalling it didnt happen anymore.

And I had this error shown: https://imgur.com/a/SrvUau3

If I ever experience it again Ill surely contact you guys. Im sad I didnt enable the debug log before reinstalling

**Comment by jamesozzie** [comment]
Closing as non responsive user. Issue looks to be resolved on the Elementor side as per #1637
