### ISSUE TITLE
E2E tests failing after AMP v2 release

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1959]
## Bug Description

Site Kit currently has a number of E2E tests in place to cover our AMP-specific behavior in the plugin. To accomplish this, we install the latest version of the `amp` plugin as part of our E2E environment provisioning script.

The latest release of the plugin (v2) that was [just released](https://github.com/ampproject/amp-wp/releases/tag/2.0.0) seems to have broken our tests.

E2E failures in the job below all indicate AMP tests
https://travis-ci.com/github/google/site-kit-wp/jobs/378352175

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All AMP E2E tests should pass using the latest version of the `amp` plugin

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/1962

## QA Brief

* E2E tests should pass (required for https://github.com/google/site-kit-wp/pull/1962 to be merged) so this is mostly N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅
