### ISSUE TITLE
Explore which elements of Site Health Report to integrate with Site Kit 

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#196]
Integrate Site Health report to help efficiently dealing with support requests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@marrrmarrr @felixarntz I think this one can be closed in favor of #169 which will be included in the upcoming release.
