### ISSUE TITLE
Analytics Provisioning: improve defaults for blank site names & subdirectory installs.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1960]
## Bug Description

When using a WordPress site with a blank "Site Title" (Settings->General) and creating a new Analytics account in Site Kit, the `Account` field should be pre-filled with a default value - instead, it is empty.

## Steps to reproduce

1. Enable Analytics.
2. During setup - From the Account dropdown, select "Set up a new account"
3. Note: also reproducible from the settings screen.

### Expected result: 
The account field should be pre-filled with a default value (as stated in the text).

### Actual result: 
The account field is empty. Users must enter an account name before being able to click "Create Account"

## Screenshots

![image](https://user-images.githubusercontent.com/2676022/91450884-09e57000-e83a-11ea-9a44-3e26e3c4a6c6.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When using a WordPress site with a blank "Site Title" (Settings->General) and creating a new Analytics account in Site Kit (during setup or from the settings screen), the `Account` field should be pre-filled with the site URL. 
* When using a WordPress site installed in a subdirectory, the default property name when provisioning analytics should include the subdirectory path.

## Implementation Brief

* In `assets/js/modules/analytics/components/common/AccountCreate/index.js` - in the code section that sets up the form store reading `// Only set the form if not already present in store.`

use the `hostname` for the `accountName` value if the `siteName` is blank:

`accountName: siteName || hostname,`

* Update property name to include path:
`propertyName: `${ hostname }${ pathname }`.replace( /\/$/, '' ), // Strip trailing slash`

## QA Brief

* Set the WordPress Site Title to blank/empty.
* Create a new Analytics account from Site Kit.
* Verify in Analytics new account with name `your-test-sitename.com` was created.
* Test process with WordPress installed in a subdirectory, verifying property name includes path:
	* eg wp-admin is at `testsite.com/wp/wp-admin`, in this case the property name for the property should be `testsite.com/wp`.

## Changelog entry

* Provide site URL as fallback default value when creating a new Analytics account if site title is empty.

**Comment by felixarntz** [comment]
@adamsilverstein Can you debug a bit more why this might be happening? Could it be that your site name is empty or something like that? I'm not able to replicate it on my end.

Does it happen anywhere you try to create an account, or is it different between e.g. Analytics setup/Analytics settings?

**Comment by adamsilverstein** [comment]
Turns out this was user error! I had been testing another issue caused by a blank WordPress site name (where we were showing 'UNDEFINED' during the setup flow) so I had my local testing environment set that way - hence the blank title field.

Still, it did create a confusing user experience and I feel like we can improve the experience by choosing another good default - the site URL (which cannot be blank!). This is the same fix we applied to the setup flow.

I will update the issue description and help move thru AC/IB - this should be straightforward to fix.

**Comment by aaemnnosttv** [comment]
Rather than using the `siteURL`, I think we should fallback to the `hostname` rather than the full URL, which we already use for the property name:
https://github.com/google/site-kit-wp/blob/04ffad3598e7a81582f8a211649cee2d1dbb5e6a/assets/js/modules/analytics/components/common/AccountCreate/index.js#L74-L78
E.g. `accountName: siteName || hostname, `

In light of this duplication, I think perhaps the `propertyName` should include any potential path (for accuracy with subdirectory installs). So `propertyName` would be essentially: 
```js
propertyName: `${ hostname }${ pathname }`.replace( /\/$/, '' ), // Strip trailing slash 
```

Thoughts @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv SGTM!

**Comment by adamsilverstein** [comment]
Great suggestions, thanks @aaemnnosttv. I mostly chose siteURL for consistency for how we handle blank site names in the service during setup flow, using the host instead might be a nice improvement there as well.

**Comment by adamsilverstein** [comment]
Updated IB.

**Comment by aaemnnosttv** [comment]
IB ✅ 

Regarding the QAB (this isn't needed until CR but no worries 😄 )

> eg wp-admin is at `testsite.com/wp/wp-admin`, in this case the property name for the property should be `testsite.com/wp`.

This is not entirely accurate as this can happen in a non-subdirectory install by putting WP in its own directory. A subdirectory install in this case is one where the home URL and admin URLs share a common path after the root of the domain.
E.g. home URL: `http://example.com/foo/` and admin URL `http://example.com/foo/wp-admin/`.

So here the `accountName` would be `example.com` and the `propertyName` would be `example.com/foo`.

**Comment by cole10up** [comment]
**Tested**

Created a site without a site title:
![image](https://user-images.githubusercontent.com/57115907/94177681-cc7efd00-fe4e-11ea-8a94-9cfaf902e9e4.png)

Installed, activated and setup latest SK. Created new Analytics account:
![image](https://user-images.githubusercontent.com/57115907/94177890-2c75a380-fe4f-11ea-879e-1cc137c35a3d.png)

Confirmed account and property were created properlly:
![image](https://user-images.githubusercontent.com/57115907/94178036-647ce680-fe4f-11ea-93e7-2696d274787d.png)

**Comment by cole10up** [comment]
Without spending a tremendous amount of time running through setup issues - just note at this time I'm unable to validate subdirectory installs as the env I tried is throwing an error setting up sitekit. 

Passing this to approval with this note to keep moving on the release.

**Comment by aaemnnosttv** [comment]
QA ✅ 

I tested this with a site on a multisite subdirectory install and the fields populated as they should in both cases.

<details>
<summary>Screenshots</summary>

**With site title**
![image](https://user-images.githubusercontent.com/1621608/94186405-58c10c80-feaf-11ea-9f69-32ad679057f9.png)

**Without site title**
![image](https://user-images.githubusercontent.com/1621608/94186439-637ba180-feaf-11ea-8615-fbcc04d22a06.png)

</details>
