### ISSUE TITLE
Introduce User_Transients storage class

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1964]
For the upcoming user input feature, we'll need to have "user transients" - i.e. transients which are stored in the `usermeta` database table instead of `options`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Introduce `Google\Site_Kit\Core\Storage\User_Aware_Interface` interface with methods `get_user_id` and `switch_user` (similar to the existing `User_Options`).
* Introduce `Google\Site_Kit\Core\Storage\User_Aware_Trait` which implements the two public methods, relying on a `$user_id` class property.
* Modify `Google\Site_Kit\Core\Storage\User_Options_Interface` to extend `Google\Site_Kit\Core\Storage\User_Aware_Interface`, removing the method definitions already covered in the new interface.
* Modify `Google\Site_Kit\Core\Storage\User_Options` to use the new `Google\Site_Kit\Core\Storage\User_Aware_Trait`, removing the methods and class property and instead relying on the trait. The constructor can call `switch_user` to set the initial user ID.
* Introduce `Google\Site_Kit\Core\Storage\User_Transients` class which implements `Google\Site_Kit\Core\Storage\User_Aware_Interface` (no need for a transients interface at this point):
    * Constructor should receive `Context` instance and `$user_id` (default of current user ID, similar to `User_Options`).
    * The class should have methods `get`, `set`, and `delete` with similar signatures and documentation to `Transients`. The methods should behave similar to WP core's `get_transient`, `set_transient`, and `delete_transient`, except:
        * It should use the `$wpdb->usermeta` (`*_user_meta` functions) table instead of `$wpdb->options` (`*_option` functions).
        * It should not fire any filters or actions.
        * It should also account for whether network mode is enabled - the easiest way for that is probably to internally create a `User_Options` instance and rely on that.
    * The class should furthermore have methods `get_user_id` and `switch_user` via `Google\Site_Kit\Core\Storage\User_Aware_Trait`.

## Implementation Brief

* Add a new `Core\Storage\User_Aware_Interface` interface with methods:
    - `get_user_id() : int`
    - `switch_user( int $user_id ) : Closure`
* Add a new `Core\Storage\User_Aware_Trait` which implements `User_Aware_Interface`
    - `switch_user` – The returned `Closure` takes no arguments and should restore the previous `$user_id` that was set before switching when invoked
    - The user ID is stored and retreived on/from a `private $user_id` property
* Update `Core\Storage\User_Options_Interface` to extend `User_Aware_Interface`
    - Remove `get_user_id` method to inherit from the parent
    - Remove `switch_user` method to inherit from the parent
* Update `Core\Storage\User_Options` to `use User_Aware_Trait`
    - Remove `private $user_id` property
    - Remove `get_user_id` method to inherit from the trait
    - Remove `switch_user` method to inherit from the trait

#### Transients

* Add a new `Core\Storage\User_Transients` class which implements `User_Aware_Interface`
    - The constructor should:
        - require a `Context` instance, and an optional `$user_id`
        - instantiate a `User_Options` instance instance using the provided user ID into a private `user_options` property
    - `get( $transient )`
        - if using an external object cache  
        calls and returns a private method: `get_from_cache( $transient )`
        - else  
        calls and returns a private method: `get_from_user_options( $transient )`
    - `set( $transient, $value, $expiration = 0 )`
        - if using an external object cache  
        calls and returns a private method: `set_in_cache( $transient, $value, $expiration = 0 )`
        - else  
        calls and returns a private method: `set_in_user_options( $transient, $value, $expiration = 0 )`
    - `delete( $transient )`
        - if using an external object cache  
        calls and returns a private method: `delete_from_cache( $transient )`
        - else  
        calls and returns a private method: `delete_from_user_options( $transient )`
    - `switch_user( $user_id )` proxies to the same method on `user_options`
    - `get_user_id` proxies to the same method on `user_options`
* Cache methods
    - `$transient` should be internally prefixed as `user_options->get_meta_key( user_{user_id}_{transient} )`  
        - `user_options` is used here to handle network mode-specific prefixing
        - get `user_id` from `user_options->get_user_id()`
        - hereafter the prefixed `$transient` will be referred to as `$prefixed_transient`
    - `$cache_group` varies based on `Context->is_network_mode()`
        - if `true`, use `site-transient`
        - otherwise, use `transient`
    - `get_from_cache( $transient )`  
        calls and returns `wp_cache_get( $prefixed_transient )`
    - `set_in_cache( $transient, $value, $expiration = 0 )`
        calls and returns `wp_cache_set( $prefixed_transient, $value, $cache_group, (int) $expiration )`
    - `delete_from_cache( $transient )`
        calls and returns `wp_cache_delete( $prefixed_transient, $cache_group )`
* User option methods
    - `$transient` should be internally prefixed as `googlesitekit_transient_{ $transient }`  
    hereafter referenced as `$prefixed_transient`
    - `$transient_timeout` should be internally prefixed as `googlesitekit_transient_timeout_{ $transient }`  
    hereafter referenced as `$prefixed_transient_timeout`
    - `get_from_user_options( $transient )`
        `$value = user_options->get( $prefixed_transient )`  
        `$timeout = user_options->get( $prefixed_transient_timeout )`
        - If `false !== $timeout && $timeout < time()` call `$this->delete()` and return `false`  
        otherwise return `$value`
    - `set_in_user_options( $transient, $value, $expiration = 0 )`
        calls `$result = user_options->set( $prefixed_transient, $value )`
        calls `user_options->set( $prefixed_transient_timeout, (int) $expiration )`
        returns `$result`
    - `delete_from_user_options( $transient )`
        `$result = user_options->delete( $prefixed_transient )`  
        `user_options->delete( $prefixed_transient_timeout )`    
        returns `$result`

#### Tests
* Add a trait for `Core\Storage\User_Aware_Interface_ContractTests`
* Update `User_OptionsTest` to use `User_Aware_Interface_ContractTests`
* Add a PHPUnit test case for `Core\Storage\User_Transients`, also using `User_Aware_Interface_ContractTests`

_No E2E, Jest, or Storybook changes necessary_

## QA Brief

* N/A – this is a new internal API which is not used anywhere yet. The added test coverage should be sufficient for now.

## Changelog entry

* Introduce `User_Transients` PHP class for storing user-specific transients.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> `switch_user( int $user_id ) : Closure`

+1, I like this idea. Just pointing out that this changes the signature of the existing method, but since it returns `void` currently, it shouldn't have any implications.

Regarding the transients abstraction, I think it goes a bit too far - there are several great ideas in there, but it also has some inconsistencies like for example:
* Only `Core\Storage\Transients\Cache_Backend` has a `set_prefix` method which somewhat breaks the `Core\Storage\Transients\Transients_Backend_Interface` contract.
* `Core\Storage\Transients\User_Options_Backend` is user-specific so it would probably also need to implement the user-aware interface.
* The prefix approach for `Core\Storage\Transients\Cache_Backend` works, but is somewhat confusing to - that could also be a user-aware transient backend instead, that allows switching the user (which internally would switch the prefix).

Overall I'd prefer if we kept it simple, which leaves more room for future updates and didn't add all these abstractions. How about for now only add private methods to `Core\Storage\User_Transients`:
* if using persistent object cache (these methods would need to check if network mode)
    * `get_from_cache( $transient )`
    * `set_in_cache( $transient, $value, $expiration = 0 )`
    * `delete_from_cache( $transient )`
* otherwise (these methods would use a `User_Options` instance which already has awareness of network mode)
    * `get_from_user_options( $transient )`
    * `set_in_user_options( $transient, $value, $expiration = 0 )`
    * `delete_from_user_options( $transient )`

While this results in a bigger class, it doesn't put us into a corner, and I'd argue it actually keeps the code easier to understand than with the additional backend abstractions.

**Comment by aaemnnosttv** [comment]
Thanks for your thoughts @felixarntz!

> Regarding the transients abstraction, I think it goes a bit too far - there are several great ideas in there, but it also has some inconsistencies like for example:
> * Only `Core\Storage\Transients\Cache_Backend` has a `set_prefix` method which somewhat breaks the `Core\Storage\Transients\Transients_Backend_Interface` contract.

Yeah, I agree that's not ideal. I think the problem here is combining a low-level backend like `Cache_Backend` with `User_Options_Backend` which uses the higher-level `User_Options` internally that already handles the prefixing.
For these to be more interchangable, `User_Options_Backend` would probably need to be a `User_Meta_Backend` (with no internal options/meta class) which would be a bare user storage backend as user options imply prefixing. We of course need prefixing, but that should be applied consistently by `User_Transients`. The only prefixing that `User_Meta_Backend` would apply on its own that the `Cache_Backend` wouldn't would be `googlesitekit_transient_` and `googlesitekit_transient_timeout_` which are an implementation detail of that backend.

Instead of such a low-level `Cache_Backend`, we would probably need a `User_Cache_Backend` so that both would be equally user-scoped/aware. In this way, `User_Transients` would call `switch_user` unconditionally to the backend, and `set_prefix` wouldn't really be necessary anymore, only a way of sharing `$network_mode` which informs the remaining elements of the dynamic key. That could also be done by providing `Context` to the backend instances instead.

---

While I like the idea of using polymorphism to solve this in a more composable OO design, I agree that we don't need to try to do this all in one issue and that is something we can iterate towards later if desired. I'll update the IB to use a more primitive approach for now.

**Comment by aaemnnosttv** [comment]
@felixarntz I've updated the IB as discussed. I left the estimate the same though as this feels like one of the issues that falls somewhere in the middle as 11 feels a bit tight here. Back to you!

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
(No QA needed; moving directly to approval 👍🏻)

QA ✅
