### ISSUE TITLE
VRT consistently failing with Admin Bar

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1965]
## Bug Description

The "Global / Admin Bar" visual regression tests are failing now on `develop` as well as builds for PRs. This is very odd as [the same build passed](https://travis-ci.com/github/google/site-kit-wp/builds/181695155) only 10 hours ago.

The failure is specific to the Admin Bar test which also happens to be the first story that is run by VRT.

```
compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 0.00%, threshold: 0.05% }: Global/Admin Bar google-site-kit_Global_Admin_Bar_0_document_0_small.png
```

The error seems to indicate a size difference, rather than a difference in content exceeding the threshold.

VRT runs with `travis_retry` which retries the command up to 2 times after the first failure and it still fails consistently so it is not a fluke.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Visual regression tests should pass

## Implementation Brief

* Merge #1966 

## QA Brief

* VRT passes (required for PR to be merged so no manual action needed)

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
Assigning to @aaemnnosttv to merge. 🙂
