### ISSUE TITLE
Update CTAs to hint at stats - new auth flow

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#197]
Update the CTA to set up additional modules from the solid color boxes to a box that partially displays data. The data that would be displayed is fake.

Messaging should say "Connect Analytics to see your visitors and goals" Link would take user to analytic set up flow.

![6c7763adf4f2e6804e5a95f5c1821ec7](https://user-images.githubusercontent.com/28811945/61014555-ac4c4680-a34d-11e9-926b-acc2e4c645f9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@bjackson27 the next step here would be to get some mocks, so we can scope what exactly the implementation will require before we prioritise it. 
Who would be the best person to assign this to for that step?

**Comment by marrrmarrr** [comment]
Closing this, as it's being addressed with the dashboard UX work going on right now (zero states specifically).
