### ISSUE TITLE
G Analytics Drop Down 

### ISSUE THREAD

**Issue by mrashleyball** [google/site-kit-wp#1972]
When adding new G Analytics the drop-down disappears.

Screen recording - https://a.cl.ly/12uJRq2Z

**Comment by jamesozzie** [comment]
Thanks for reaching out. Initial support requests can be submitted using the plugins WordPress support forum. 

Please open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) while providing the following:
- Your [Site Health information](https://i.imgur.com/Rtkmsba.png). You can share [privately](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) if preferred. 
- Does this occur with different browsers?
- Do you encounter any [console errors](https://imgur.com/KyLAzgH) on the same screen?

We can then try and recreate the same experience and revisit this GitHub issue if required.
