### ISSUE TITLE
cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out

### ISSUE THREAD

**Issue by tmichellemoore** [google/site-kit-wp#1973]
## Viewing the Google Site Kit dashboard in the WordPress admin view, I am receiving the following errors for each component.
**All Traffic**
Data error in Analytics - cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out
**Search Funnel**
Data error in Search Console - cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out
Data error in Analytics - cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out
**Popularity**
Data error in Search Console - cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out
Data error in Analytics - cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out (Same as above)
**Page Speed and Experience**
Error: cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out

**WordPress Dashboard**
Unknown Error (code: cURL error 7: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out). To fix this, redo the plugin setup.

Note: Settings indicate that the services are connected.

## Steps to reproduce

1. Go to the WordPress admin view
2. Click on [Google] Site Kit.
3. Click on Dashboard. (Search Console and Analytics display the same applicable error.)

## Screenshots

![WordPress-GoogleSiteKit-2020-08-30 103727](https://user-images.githubusercontent.com/7757648/91662186-b760b980-eaae-11ea-9af5-44f47e8ebe6e.jpg)

![image](https://user-images.githubusercontent.com/7757648/91662181-add75180-eaae-11ea-9ad5-cc4688e3d6f4.png)

## Additional Context

-- | --

 - PHP Version: 7.4.9
 - OS: Windows 10
 - Browser: Chrome
 - Plugin Version: 1.15.0
 - Device: PC Laptop
-WordPress Version | 5.5

This issue was occurring all morning and as I was moving through the screens to pull the screenshots and adding the information to this ticket it started to work! So at this point this isn't an issue but I would still like to know what the problem was.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reporting. Initial support requests can be submitted using the plugins WordPress support forum. 

Please open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing your [Site Health information](https://i.imgur.com/Rtkmsba.png) within the topic or [privately](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) we can try and determine the root cause in your case, while revisiting this GitHub issue if necessary. 

Within the topic please include details on whether Site Kit worked for you previously and if so whether you've made any changes.

**Comment by jcax2** [comment]
Hi! Don't know if still useful, but I have the same problem. SOLVED:

go to your hosting control panel and allow the outgoing connections with Google's IP. Mine is:  142.250.190.XX 

Hope this help.
