### ISSUE TITLE
Disable coverage collection for Jest tests by default

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1974]
## Feature Description

Our current Jest config enables code coverage reporting by default however this is not optimal for most runs as it significantly slows down the tests.

From the docs:
> Because these retrofits all executed files with coverage collection statements, it may significantly slow down your tests.

In my testing, I see ~100% increase in the time it takes the test to run when enabled, so I find myself disabling it manually with the `--coverage=false` when running tests.

Furthermore, we don't use the generated coverage data for anything right now. While this can be useful at times, it should be opt-in rather than the default.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Code coverage reporting should be disabled by default.

## Implementation Brief

* Set `collectCoverage: false` in `tests/js/jest.config.js`
* Merge #1975 

Since this isn't used in CI for reporting to a coverage tracking service, no other commands need to change.

## QA Brief

* Running `npm run test:js` does not generate a code coverage report

<details>
<summary>Example coverage report</summary>

```
=============================== Coverage summary ===============================
Statements   : 13.97% ( 1041/7453 )
Branches     : 1.94% ( 77/3968 )
Functions    : 7.01% ( 134/1911 )
Lines        : 14.58% ( 1038/7121 )
================================================================================
```
</details>

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

No coverage generated after running the tests, and they're definitely faster! 👍🏻
