### ISSUE TITLE
Google API requests fail when using HTTP Proxy that requires authentication

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1976]
## Bug Description

Site Kit currently supports using an HTTP proxy using WordPress core constants for `WP_PROXY_*` values.

For proxies that require authentication, Site Kit is configured to send the credentials through over the `Proxy-Authorization` header, which is consistent with how the WP HTTP API implements proxy authentication for streams. See [`\WP_HTTP_Proxy::authentication_header`](https://developer.wordpress.org/reference/classes/wp_http_proxy/authentication_header/)

Originally reported here: [cURL erro 56 with Proxy](https://wordpress.org/support/topic/curl-erro-56-with-proxy/)

## Steps to reproduce

1. Set up Site Kit in an environment using an HTTP proxy that requires authentication  
_This can be a bit complicated if you don't already have it set up for you_
1. Configure WordPress to use the HTTP proxy using the respective constants, configured correctly in `wp-config.php`  
	```
	define( 'WP_PROXY_HOST', 'https://your-proxy-host' );
	define( 'WP_PROXY_PORT', 'your-proxy-port' );
	define( 'WP_PROXY_USERNAME', 'your-proxy-user' );
	define( 'WP_PROXY_PASSWORD', 'your-proxy-user-password' );
	```
1. Clear all transients, and flush the cache in WP to trigger requests again
1. While logging requests at the proxy, navigate to the WP dashboard
	- See WP HTTP requests succeeding
1. Go to the Site Kit dashboard, clear the browser's session storage and reload the page
	- See Site Kit HTTP requests failing with 407 error

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/91723660-c7f35b80-eba4-11ea-8769-cbe47d869820.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit Google API requests should work when WordPress is configured to use an HTTP proxy with or without authentication required

## Implementation Brief

* Provide proxy authentication credentials in the `proxy` request option rather than as an additional header
* Merge #1977

## QA Brief

* The setup needed here is a bit complicated but it can be done using [Squid](http://www.squid-cache.org/) to set up an http proxy that requires authentication

## Changelog entry

* Fix support for WordPress configurations using an HTTP proxy with or without authentication required.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested in a working session with Evan**

Before: 
![image](https://user-images.githubusercontent.com/57115907/92497056-bebe4c00-f1ad-11ea-8a0d-051855dce772.png)

After:
![image](https://user-images.githubusercontent.com/57115907/92497089-c5e55a00-f1ad-11ea-9c1c-61098df7b830.png)

Passed QA ✅
