### ISSUE TITLE
Configure Travis builds to finish fast

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1986]
## Feature Description

Currently we have a few jobs in our Travis test matrix which are allowed to fail. One of these is an E2E test which often starts a few minutes later than the rest, which causes the entire build to take longer to finish (i.e. report success/fail) until all jobs finish. This can cause an otherwise successful build to take another several minutes before any related PRs can be merged.

From the [Travis blog](https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/):

> For a while, Travis CI has supported allowed failures in your build matrix - jobs that are allowed to fail, without affecting the status of the entire build.

> However, even if some of the items in your build matrix are allowed failures, Travis CI will still wait for them to finish before marking the build as finished. Even if all of the other jobs are done, Travis CI won’t mark the build as finished until the allowed failures are done, despite the fact that allowed failures won’t ultimately affect the status of the build.

See the docs on this here:
https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Travis build should be configured not to wait for allowed failures to finish running before reporting its status

## Implementation Brief

* Configure `jobs.fast_finish: true` in `.travis.yml`
* Merge #1987 

## QA Brief

* Once merged, the build result should be reported as soon as the main list of jobs is completed, even if not all of the jobs which are allowed fail have finished yet

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Right on.

IB ✅

Code reviewed as well, so assigning it back to you to merge 👍
