### ISSUE TITLE
Print meta generator tag on a new line

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1993]
## Feature Description

As per one WordPress support topic consider inserting the Site Kit meta tag on it's own line when printed into wp_head. 

More info below:
https://wordpress.org/support/topic/meta-in-wp_head/#post-13372948

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is such a small change, that it's not really worth its own issue. It's also rather cosmetic.

If anything, we should address this in https://github.com/google/site-kit-wp/issues/938.
