### ISSUE TITLE
Users get stuck in onboarding flow (version RC2)

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#200]
Two users today reported very similar issues independently of each other -- they upgraded to RC2 and were not able to complete the setup flow.

User 1:
Upgraded to RC2, generated and copied credentials, then got stuck at the account sign-in step: clicking "Sign in with Google" and selecting the account takes him back to the same step. Video he shared: https://www.loom.com/share/b3f5a5752801456ab98b1167a3ae2325

User 2:
Upgraded to RC2, generated and copied credentials, authenticated, then got stuck at the verification step (screenshot attached). When he clicks "continue", nothing happens.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
I can't reproduce this any more, and given that it was for version RC2, I doubt it's relevant at this point. 

@jamesozzie could you try to replicate this? The user's recording is here: 
https://www.loom.com/share/b3f5a5752801456ab98b1167a3ae2325

I'm wondering if it's related to issue #4 .

**Comment by jamesozzie** [comment]
This is probably more related to #78. In other cases the authentication fails because of Ad Blockers in use. I'm unable to recreate this issue myself with older RC versions but others have reported the same issue last week. I will keep it open while I check again
