### ISSUE TITLE
Show error on single URL details view if no entity is matched

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2001]
Before we implemented proper entity detection in Site Kit (see #174), the single URL details view worked for any URL part of the site, or even URLs not part of the site for certain services that don't incorporate permission management (such as PageSpeed Insights).

However, now the single URL details view relies on entity detection to find out more information of the "entity" based on the given URL. This means that, if a single URL details view is accessed, it can and should only provide meaningful results if an entity is detected.

This issue should modify the single URL details view accordingly so that, if no current entity is available, a corresponding message is displayed, instead of still attempting to show data (for the new widgets, doing so would fall back to showing site-wide data, which would be just as irrelevant on that screen).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the single URL details view, if there is no current entity (e.g. if the `getCurrentEntityURL` selector of the `core/site` store returns `null`), the screen should show a corresponding message instead of all the regular UI:
    * The "Detailed Page Stats" heading and the back link should be kept.
    * The date range selector should not be there.
    * The white box that would normally have the page title and URL should include the following message: _It looks like the URL %s is not part of this site, therefore there is no data available to display._ (`%s` should be the URL taken from the `permaLink` query parameter)
    * Everything below that box should not be displayed.

## Implementation Brief

* Extract the inner Entity-dependent elements from `DashboardDetailsApp` into a new `DashboardDetailsEntityView` component in `assets/js/components/dashboard-details/`
    - Starting from the `div` containing `<DateRangeSelector />`
    - Ending with `<DashboardDetailsModules />`, inclusive
* Add a new `DashboardDetailsEntityNotFoundView` component as a variant (but not copy of) of `DashboardDetailsEntityView`
    - renders with the following title/url portion https://github.com/google/site-kit-wp/blob/f244c63925cd56d0bb03a048d0b387824c335fe5/assets/js/components/dashboard-details/dashboard-details-app.js#L85-L109
        - The `h3` and `Link` components should be replaced by the message in the AC rendered as plain text (i.e. `<p>`):  
        _It looks like the URL %s is not part of this site [...]_
        - The URL in this block should be sourced from the full URL passed in the `permaLink` query parameter of `global.location.href`  
* Update `DashboardDetailsApp` to conditionally render the appropriate component based on the value of `getCurrentEntityURL`
    - This URL is provided from the server response so there is no resolver to wait for – it will be available immediately
    - If `null`, render the `DashboardDetailsEntityNotFoundView`
    - Otherwise, render the `DashboardDetailsEntityView`

### Tests

* Add storybook stories for the dashboard details view to render `DashboardDetailsApp` with stories for both
    - A found Entity
    - A not-found Entity
* No Jest, E2E changes
* No VRT changes expected

_There are no stories for this view yet, so create a `stories/dashboard-details.stories.js` module for them_

## QA Brief

* Go to the following page: `/wp-admin/admin.php?page=googlesitekit-dashboard&permaLink=%2F404-page`
* Make sure that you see everything that is listed in the AC

## Changelog entry

* Show an error message if the URL for the single URL detail view cannot be identified as part of the site.

**Comment by aaemnnosttv** [comment]
@felixarntz perhaps the message shouldn't contain the URL itself as it is linked below (assuming the message goes where the title was).

Do you think the message should be rendered as an `ErrorText`? It probably shouldn't use an `h3`. If not the error text, then perhaps just a `<p>`?

**Comment by felixarntz** [comment]
@aaemnnosttv I think we should entirely replace the `h3` and the `Link` with the error message. Using `ErrorText` sounds good to me.

**Comment by aaemnnosttv** [comment]
@felixarntz on second thought, I think the `ErrorText` may be a bit too "severe" for this case. This should be an edge case which is likely expected if details were requested for an "unresolvable" URL. This is essentially an internal 404 which reminds me of Google's 404 page which is cute 😄 

![image](https://user-images.githubusercontent.com/1621608/94943452-67777700-04e0-11eb-9e9a-a4b4f1ba1573.png)

I'm not saying we should steal this exactly, but a few ideas we could borrow:
* Not using an error appearance – it's not a big deal
* Only showing the path of the URL – keeps the message shorter by removing the bits which will always be the same (we already do this on dashboard widgets)
* Using the robot image would be awesome... 😄 

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv That's fair, let's not use error appearance. I still think we should show the full URL because someone could manually add a `permaLink` parameter for a completely unrelated website, so then the full URL matters.

For the robot image, probably no because it would require some extra whatever license hassle, so 🤷‍♂️ 😆

**Comment by aaemnnosttv** [comment]
@felixarntz IB updated 👍

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup SK. Navigated to /wp-admin/admin.php?page=googlesitekit-dashboard&permaLink=%2F404-page

Checked the AC and confirmed content and functionality.
![image](https://user-images.githubusercontent.com/57115907/95616331-7b5e3400-0a1e-11eb-9700-ac86970de122.png)

Back button functions properly, checked on mobile and other window sizes and browsers.

Passed QA ✅
