### ISSUE TITLE
Display Bounce Rate and Session Duration in Analytics graph tooltip correctly

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2008]
## Bug Description

Per @eugene-manuilov's finding, the tooltips for the Bounce Rate and Session Duration graphs on the Analytics module page do not display their values in the correct format.

**Bounce Rate**:
![bounce](https://user-images.githubusercontent.com/3531426/92817507-7e142d80-f37b-11ea-84e2-18ab0ef2cba4.png)

**Session Duration**:
![duration](https://user-images.githubusercontent.com/3531426/92817874-ea8f2c80-f37b-11ea-88f1-37936c3c1029.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tooltips for the Bounce Rate graph on the Analytics module page should display its value formatted in the same way as the total value above the graph (percentage with 2 decimals).
* Tooltips for the Session Duration graph on the Analytics module page should display its value formatted in the same way as the total value above the graph (split into minutes, seconds etc., with corresponding units).

## Implementation Brief

In the `assets/js/modules/analytics/util/index.js` file:
* Import `prepareSecondsForDisplay` from the `assets/js/util/index.js`file;
* Amend `extractAnalyticsDashboardData` function:
  * Declare a new `dataFormats` array after `dataLabels` with the following values:
    * `( x ) => parseFloat( x ).toLocaleString()` as first and second values;
    * `( x ) => parseFloat( x ).toFixed( 2 ) + '%'` as third value;
    * `prepareSecondsForDisplay` as fourth value.
  * Update the second argument for `statInfo`'s sprintf function to be `dataFormats[ selectedStats ]( row[ 1 ] )` instead of `parseFloat( row[ 1 ] ).toLocaleString()`.

## QA Brief

Go to the Analytics page and check the following in the Audience overview widget:
* When `Users` or `Sessions` metric is selected, actual values in the tooltip should be formatted based on the current locale of the browser (for instance: `12,345` for en-US).
* When the `Bounce Rate` metric is selected, the tooltip should show actual values formatted as a percentage with 2 decimals.
* When the `Session Duration` metric is selected, the tooltip should display its actual values formatted as an internal in the same way as the total value above.

## Changelog entry

* Fix tooltips for Bounce Rate and Session Duration in Analytics graph to format values correctly.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested:**

Installed latest develop, checked bounce rate:
![image](https://user-images.githubusercontent.com/57115907/93846597-59606580-fc59-11ea-838a-256ac530322e.png)

Session duration:
![image](https://user-images.githubusercontent.com/57115907/93846643-7f860580-fc59-11ea-9831-d539cf1549f5.png)

![image](https://user-images.githubusercontent.com/57115907/93846690-a3494b80-fc59-11ea-977e-28e6e4921a1d.png)

**Noticed session duration tooltip doesn't make much sense with what the Y axis is displaying**

The above 2 screenshots show session durations for the tooltip displaying minutes with the Y axis showing increments  by the hundreds.

Sending back to CR @eugene-manuilov

**Comment by aaemnnosttv** [comment]
Thanks @cole10up looks like this needs a little refinement here. Just noting that with the latest release that it uses the same units and scale on the Y axis, but the value is consistent with it, so it looks like we just need to update the labels used for the axis to match.
![image](https://user-images.githubusercontent.com/1621608/93895092-1c977b80-fcf8-11ea-853c-a878d0af895a.png)

**Comment by ryanwelcher** [comment]
I've opened a ticket for discovery into formatting the vertical axis - see #2095.

Moving to approval.
