### ISSUE TITLE
Size of the project Git repository

### ISSUE THREAD

**Issue by kasparsd** [google/site-kit-wp#2011]
## Bug Description

The size of the current Git repository during the checkout is 409.66 MiB which is around 430MB!

```
Cloning into 'site-kit-wp'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 83795 (delta 46), reused 63 (delta 24), pack-reused 83691
Receiving objects: 100% (83795/83795), 409.66 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (60766/60766), done.
```

This appears to be caused by all the storybook files in the history:

```
a94e9c83a197  4.3MiB storybook/pull/1721/main.859da0e8856db45c74fc.bundle.js
e7c892312a6a  4.3MiB storybook/pull/1830/main.ee704e29d0bf4c7f87ec.bundle.js
1c5dd7b42333  4.3MiB storybook/pull/1826/main.c6638f313027243e10cf.bundle.js
fce5ba5ce994  4.3MiB storybook/pull/1826/main.b4b4755e34c15c792ed2.bundle.js
9890069b5585  4.3MiB storybook/pull/1816/main.92e3411374033370c37d.bundle.js
00ea77d8c5de  4.3MiB storybook/pull/1823/main.f1119fda69efcb9259ca.bundle.js
000728cf75b4  4.3MiB storybook/pull/1766/main.c5fd927d6e58769a0371.bundle.js
50806129a56b  4.3MiB storybook/pull/1766/main.84346e724d4c4e29b9fe.bundle.js
f1dcb9da16bc  4.3MiB storybook/pull/1766/main.6dcd18088badffb513ec.bundle.js
9836b601a0d3  4.3MiB storybook/pull/1823/main.cc50da7849e43ded28d7.bundle.js
c63088d36863  4.3MiB storybook/pull/1823/main.58c765ecf593858990f7.bundle.js
f87867b7ee37  4.3MiB storybook/pull/1823/main.5f40c3663a6c90b8e921.bundle.js
5bee9f97ede3  4.3MiB storybook/pull/1809/main.3de5046e042e4e719330.bundle.js
2dbd4f704095  4.3MiB storybook/pull/1671/main.666b559cf23df2008323.bundle.js
68f28d90456f  4.3MiB storybook/pull/1671/main.470f066a2fe314726b23.bundle.js
a43464033d31  4.3MiB storybook/pull/1671/main.97a48e56be58fb989b60.bundle.js
ae81371b893b  4.3MiB storybook/pull/1671/main.65b51266afc6277c52fe.bundle.js
c437d570b0cc  4.3MiB storybook/pull/1671/main.b59f350742ef2907586e.bundle.js
```

## Steps to reproduce

Clone the project repository and notice the checkout size:

    git clone https://github.com/google/site-kit-wp.git

Confirm the size of the newly created directory:

    du -hs ./site-kit-wp
    434M	./site-kit-wp

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Yeah, unfortunately there are some old storybook builds in there that didn't get pruned it seems as well as builds for things like dependabot PRs which aren't really necessary. Ideally, these storybook builds would be hosted elsewhere too, but this is what we have for now.

As a workaround, it's probably best to only checkout the single branch you need (probably the default `develop` for contributions). This makes it much more manageable:

```
⚡  git clone --single-branch git@github.com:google/site-kit-wp.git                          
Cloning into 'site-kit-wp'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 65625 (delta 6), reused 10 (delta 4), pack-reused 65608
Receiving objects: 100% (65625/65625), 36.73 MiB | 10.31 MiB/s, done.
Resolving deltas: 100% (48140/48140), done.
/tmp 
⚡  cd site-kit-wp
site-kit-wp develop ✓
⚡  du -sh .                                                 
 55M	.
```

I agree that this isn't a great experience for new contributors though. The remaining bulk of the size is likely from backstopjs reference images.

**Comment by jamesozzie** [comment]
@kasparsd I'll close this with the above information provided. Feel free to reopen should you have any additional queries on this.
