### ISSUE TITLE
Inconsistent loading state in Search Console popular keyword dashboard widget components

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2013]
## Bug Description

The `DashboardWidgetPopularKeywordsTable` (legacy) and `DashboardPopularKeywordsWidget` (Widgets API) components currently have an odd loading state in the dashboard which is inconsistent with others, particularly in its size which causes the layout to shift between loading and loaded states.

This is only visible briefly on the dashboard but is consistently reproducible.

## Steps to reproduce

1. Set up Site Kit and go to the dashboard
1. Clear the browser's session storage
1. Reload the page with a focus on the first (left-most) widget under the Popularity heading
1. Notice the widget only fills a single grid column and the other widgets are horizontally displaced
1. The widget is also missing the white border and padding like the `AnalyticsDashboardWidgetPopularPagesTable` has

## Screenshots

![Kapture 2020-09-10 at 23 05 37](https://user-images.githubusercontent.com/1621608/92931617-65c01380-f44c-11ea-984d-eda26caee46a.gif)

![image](https://user-images.githubusercontent.com/1621608/92931743-96a04880-f44c-11ea-9679-62ade25de7ec.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Search Console `LegacyDashboardWidgetPopularKeywordsTable` component should render a consistent loading state with other dashboard widgets so that it fills its full area and has the same visual treatment (white background, with footer)

_New widget-based components will be handled in a new issue per https://github.com/google/site-kit-wp/issues/2022#issuecomment-702829747_

## Implementation Brief

Edit `LegacyDashboardWidgetPopularKeywordsTable.js`
* Modify rendering of `PreviewTable` so that it renders as a child of the already included `Layout` component. 

## QA Brief

* Go to the dashboard
* Clear the browser's session storage
* Reload the page with a focus on the legacy popularity widgets at the bottom
* Check that popularity widgets fill full row correctly.

## Changelog entry

* Fix inconsistent loading state in Search Console Popular Keywords widget, which previously caused content shifting.

**Comment by felixarntz** [comment]
@caseymorrisus Did you accidentally miss something here? The IB is empty :)

**Comment by caseymorrisus** [comment]
> @caseymorrisus Did you accidentally miss something here? The IB is empty :)

That's my bad, must've left it on the preview tab and missed hitting save. Should be good now!

**Comment by felixarntz** [comment]
@caseymorrisus 
> Edit `DashboardPopularPagesWidget.js` and `DashboardPopularKeywordsWidget.js`

I think this change also needs to be added to `LegacyDashboardWidgetPopularKeywordsTable.js`, which is the actual component where this currently surfaces in production. It also applies to `LegacyAnalyticsDashboardWidgetPopularPagesTable.js`, but there it's already handled correctly (as seen in the code and the above screenshare).

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest development SK. Cleared session storage, refreshed page.

![Site Kit by Google Dashboard ‹ Oi ie - Brasileiros na Irlande — WordPress (2)](https://user-images.githubusercontent.com/57115907/95250625-e2ef6600-0809-11eb-8dfe-e44e0eb333ac.gif)

Refreshed from different pages, to confirm no other functionality was broken.

Passed QA ✅
