### ISSUE TITLE
Create Stories for widgets that have additional states.

### ISSUE THREAD

**Issue by ryanwelcher** [google/site-kit-wp#2018]
Some Widgets have additional states other than `Loaded`, `Data Unavailable` and `Error` that need to be accounted for in Storybook.

* `DashboardTopEarningPagesWidget` has a state that is displayed when the AdSense and Analytics accounts are not linked - see #1902
* `DashboardGoalsWidget` has a state that is displayed when there are no Goals defined. - see #1898

This can be done in the `generateReportBasedWidgetStories` that is being used to generate all of the Stories for these widgets but if it becomes too complex, we can define these additional Stories without using that function.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `generateReportBasedWidgetStories` utility function should support additional variants other than the three default ones.

## Implementation Brief

* Merge #1963.

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
`generateReportBasedWidgetStories` now supports `additionalVariants` as described in the ACs. Example screenshots:

**AdSense Top Earning Pages widget** (see `AdSense Not Linked`)
![Screenshot 2020-09-23 at 17 01 37](https://user-images.githubusercontent.com/3531426/94086144-ea9d1c80-fdbe-11ea-830f-eae532c05460.png)

**Analytics Goals widget** (see `No Goals`)
![Screenshot 2020-09-23 at 17 02 13](https://user-images.githubusercontent.com/3531426/94086166-fc7ebf80-fdbe-11ea-8969-7e1b4a6f8fc4.png)

QA ✅
