### ISSUE TITLE
Fix Top Queries widget keyword links to Search Console not including query correctly

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2019]
## Bug Description

The links for each keyword in the Top Queries widget's table point to the Search Console frontend, including a `query` query parameter for the keyword. However, it is used incorrectly: When opening such a URL, it shows the overview of all keywords, not actually a view specific to that keyword. That is because the `query` parameter requires an exclamation point before the keyword to look for an exact match.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `query` query parameter for Search Console deep links in the Top Queries widget should be prefixed with `!`.

## Implementation Brief

* Included as part of #1942, where this was discovered.

## QA Brief

* Before this fix, click on any keyword link in the Top Queries keywords table - see how it lands on the keywords overview instead of the specific keyword.
* After this fix, clicking on such a keyword link should result in a view that actually only has that keyword. You should also be able to see that keyword ("Query") as a filter active above.

## Changelog entry

* Fix Search Console deep links for specific keywords in keywords widget to point to the correct location.

**Comment by felixarntz** [comment]
See https://github.com/google/site-kit-wp/pull/1942/commits/2d1f3948a6b3c5c41db549c642248ed8859de097 for the fix.

**Comment by cole10up** [comment]
**Tested**

Installed latest SK, activated and navigated to top queries widget on current release:
Clicking top link:
![image](https://user-images.githubusercontent.com/57115907/93976777-5edbaf80-fd2e-11ea-827b-205004dc075b.png)

Drives to:
![image](https://user-images.githubusercontent.com/57115907/93976802-656a2700-fd2e-11ea-81aa-456c16b60eb7.png)

After fix:
![image](https://user-images.githubusercontent.com/57115907/93976838-7024bc00-fd2e-11ea-8c68-d84ea0460828.png)

Passed QA ✅
