### ISSUE TITLE
Implement search box widget in Site Kit dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2023]
The last widget missing to complete the Site Kit dashboard with the new Widget API is the search box:

**Without Analytics active:**
![Screenshot 2020-09-14 at 12 42 43](https://user-images.githubusercontent.com/3531426/93130788-e3bc2e80-f687-11ea-8767-4d640302f047.png)

**With Analytics active:**
![Screenshot 2020-09-14 at 12 40 34](https://user-images.githubusercontent.com/3531426/93130808-e9b20f80-f687-11ea-81a1-918676a1eb23.png)

Since this widget is not specific to any module, it should be part of the core widgets API layer as a default.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Search for individual page or post information" widget should be re-implemented in `assets/js/googlesitekit/widgets/components/URLSearchWidget.js`. (The old widget should be left untouched and kept in place for the current/old UI.)
* The widget should match the functionality and behavior as of today. It should **not** use the legacy `Layout` component though (related #2022).
* The widget should be registered in the `registerDefaults` function into `AREA_DASHBOARD_POPULARITY`, with:
    * priority `100`
    * width `WIDGET_WIDTHS.HALF` (this is acceptable for now; it currently renders in half or full width based on other active widgets, but that shouldn't be a concern for now)
    * wrapWidget based on what makes most sense for implementation

## Implementation Brief

* Add a new `URLSearchWidget` component in `assets/js/googlesitekit/widgets/components/URLSearchWidget.js`
    - Based on the current/legacy implementation in `assets/js/components/PostSearcher.js`
        - Should not have Analytics-specific styling or logic internally
    - Should use the new wrapper component/strategy to be introduced in #2022 rather than the legacy `<Layout>` component internally
* Register the widget in `assets/js/googlesitekit/widgets/register-defaults.js`
    * Area: `AREA_DASHBOARD_POPULARITY`
    * Priority: `100`
    * Width: `WIDGET_WIDTHS.HALF`
    * Title: `Search for individual page or post information`
    * Subtitle: none
    * `wrapWidget` (dependent on results of #2022)

This issue should depend on #2022 to avoid the need for the legacy `Layout`.

#### Tests

* Add Storybook story/stories for the new widget `stories/dashboard.stories.js`
* This is mostly a wrapper component for the `PostSearcherAutoSuggest` so no additional Jest tests should be needed

## QA Brief

* Verify within Storybook that `Dashboard -> URL Search Widget` behaves similarly to `Dashboard -> Post Searcher`
* Verify within admin dashboard
  * Type "Hello world!" into the Search Box widget within the first Popularity widget area (non-legacy version)
  * Verify that autosuggest works correctly and shows a populated value while typing "Hello world!"
  * Click "View Data" CTA
  * Verify that page changes to Detailed Page Stats page for page with slug "hello-world"

## Changelog entry

* Implement post search widget using the new Widget API.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@caseymorrisus I think the QA Brief here could be improved. Checking Storybook can help, but we should focus mainly on how this works in the actual product (with a development build, in this case). Can you add some more details on this, related to comparing the new widget with the legacy version? Note also that the area is displayed slightly differently depending on whether the Analytics module is active or not. There is right now one visual disparity in that, which is expected though - see #2251 for fixing that.

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest development build of SK.

**Activated Analytics** module and ran a series of tests around the search box:

![image](https://user-images.githubusercontent.com/57115907/98206527-e6503d00-1eee-11eb-90b6-b49a8c1db2a5.png)

Checked look and feel, browser sizes, browser types and mobile:
![image](https://user-images.githubusercontent.com/57115907/98206594-05e76580-1eef-11eb-9745-926664925b83.png)

![image](https://user-images.githubusercontent.com/57115907/98206632-126bbe00-1eef-11eb-9c23-a68be243a295.png)

Noticed the fallback width needs to be adjusted via 2251

Confirmed autofill:
![image](https://user-images.githubusercontent.com/57115907/98206665-231c3400-1eef-11eb-8996-5393cb55cc85.png)

![image](https://user-images.githubusercontent.com/57115907/98206680-29aaab80-1eef-11eb-99b9-d6ca042a3a19.png)

Confirmed navigation:
![image](https://user-images.githubusercontent.com/57115907/98206715-3a5b2180-1eef-11eb-80b0-aac96d5a48d0.png)

**Without Analytics configured**

![image](https://user-images.githubusercontent.com/57115907/98206830-7bebcc80-1eef-11eb-98c0-082106e008f0.png)

Look and feel, browser sizes, browser types and mobile:
![image](https://user-images.githubusercontent.com/57115907/98206869-8e660600-1eef-11eb-9249-8891c89d3d1a.png)

![image](https://user-images.githubusercontent.com/57115907/98206887-99b93180-1eef-11eb-8d2b-b8df8e9a8129.png)

Autofill:
![image](https://user-images.githubusercontent.com/57115907/98206927-a9387a80-1eef-11eb-9d71-2b3e9d233c40.png)

![image](https://user-images.githubusercontent.com/57115907/98206939-b190b580-1eef-11eb-9553-4bba11ff5b2c.png)

Navigation:
![image](https://user-images.githubusercontent.com/57115907/98206968-bf463b00-1eef-11eb-815a-93e07bf96dc4.png)

Confirmed current search box functionality.

Passed QA ✅
