### ISSUE TITLE
Simplify client side module registration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2024]
## Feature Description

While working on #1623, some improvements were discovered as to ways that we could simplify the way modules are registered on the client side.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `actions.registerModule` should not use `getRegistryKey` or a separate object for `ModuleComponents` and can pass `settingsComponent` through to the reducer.
* `actions.registerModule` should no longer be a generator function and all asynchronous use should be converted to synchronous
* `actions.registerModule` should only pass the following keys through to its `payload.settings`:
	- `name`
	- `description`
	- `icon`
	- `order`
	- `homepage`
	- `settingsComponent` – only this key should have a default set in the action (`DefaultModuleSettings`), the rest should be `undefined` if not passed
* The modules datastore partial should have two new top-level keys in its state:
	- `clientDefinitions` – initial value of `{}`
	- `serverDefinitions` – initial value of `undefined`
* `fetchGetModulesStore.reducerCallback` should be updated to receive the modules into the new `serverDefinitions` instead of `modules`
* `selectors.getModules` should be updated to recursively/deep-merge its `clientDefinitions` over the `serverDefinitions` before returning a normalized, ~~sorted~~, object, similar to how it does now
	- if `serverDefinitions` are `undefined`, the selector should return `undefined`
	- `clientDefinitions` should take precedence over `serverDefinitions` but only for keys which are passed when registered (no defaults other than client-only settings)
* `resolvers.getModules` should not require changes
* Remove `waitForModules` and its control as no longer used
* Remove `modules` state as no longer used

#### Tests

* Update Jest tests for module registration – particularly `modules.test.js` to cover these changes

## Implementation Brief

* Merge #2026 

## QA Brief

* Review implementation changes and added tests to verify the AC is met

## Changelog entry

* Simplify module registration in JavaScript and only allow one registration call per module.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
