### ISSUE TITLE
Cancel previous workflow runs on newer refs

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2027]
## Feature Description

Our GitHub Action workflows currently run until completed or fail for every commit they are triggered by.

In most cases however, it is usually undesirable for a workflow to continue running once another workflow for the same branch has started. In some cases, this can even cause a race condition where git-based deploy jobs fail due to upstream changes cause a push to fail. This can result in deployed assets not reflecting the latest state for their respective PR/branch or cause deployed artifacts to be left in the target repo longer than they should be due to a similar conflict in the prune/remove workflow job.

Travis has similar functionality available to automatically cancel builds for a branch/PR when a newer commit is pushed as it essentially "invalidates" the previous run. There's little benefit in letting the jobs finish as we have a limited number of concurrent jobs that can run. This is only manageable via the [settings for the repository for Travis](https://travis-ci.com/github/google/site-kit-wp/settings), but we should enable these as well:
![image](https://user-images.githubusercontent.com/1621608/93198371-9dcd9c00-f755-11ea-9202-b87d10011b56.png)

For GitHub Actions, we can leverage the [`cancel-workflow-action`](https://github.com/marketplace/actions/cancel-workflow-action) to get similar behavior for our actions. (It's not quite as good as Travis' as it requires the job to run which in turn requires availability in the queue)

This (in combination with the settings above for Travis and the recently added `fast_finish` configuration) will help us to run our builds as efficiently as possible within our limits for maximum concurrent jobs/builds.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* GitHub Action workflows for queued/pending, or in progress runs should be automatically cancelled when a newer commit is pushed to the same branch

## Implementation Brief

* Merge #2361 

## QA Brief

* Review the [Actions](https://github.com/google/site-kit-wp/actions) log for the repository
* Check workflows for VRT, Plugin Zips, and Storybook to verify cancelled workflows are present (shown by the gray octagon with ❕ inside) - e.g.  
![image](https://user-images.githubusercontent.com/1621608/99103292-09ae7280-25e8-11eb-9d67-8439ad3eac22.png)

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@aaemnnosttv Not high priority to finish within this sprint, but since you already implemented it, and if this is good to go, we can just add Sprint 36 to it.

**Comment by aaemnnosttv** [comment]
👍  – there's one caveat to this which I read about when looking into this before which is that since the cancellation is triggered by your own workflow it won't work until that job runs; it sounds more obvious that it might seem if you're coming from another CI provider. Travis cancels all older job runs automatically, whereas this would potentially wait in the queue of other jobs (depending on our [max concurrent job limit](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#usage-limits)) before it could run and trigger others to be cancelled. It's not ideal, but better than nothing given the current options available with GHA.

**Comment by aaemnnosttv** [comment]
@felixarntz I tweaked the ACs here to be more accurate to the desired outcome and less specific to the implementation which is slightly different now. Should be ready for review now 👍

**Comment by asvinb** [comment]
[VRT Test](https://github.com/google/site-kit-wp/actions?query=workflow%3A%22Visual+Regression+Testing%22):
![image](https://user-images.githubusercontent.com/31818/99523825-04b73d80-29b1-11eb-9dee-eaccea459e42.png)
Cancelled workflow present ✔️ 

[Plugin Zip](https://github.com/google/site-kit-wp/actions?query=workflow%3A%22Plugin+Zip+Files%22):
![image](https://user-images.githubusercontent.com/31818/99523988-3d571700-29b1-11eb-94fe-00c587ade9fd.png)
Cancelled workflow present ✔️

[Storybook](https://github.com/google/site-kit-wp/actions?page=4&query=workflow%3AStorybook):
![image](https://user-images.githubusercontent.com/31818/99524117-6677a780-29b1-11eb-9ecc-799178d5586c.png)
Cancelled workflow present ✔️

QA: ✅
