### ISSUE TITLE
Improve copy when users decide to not insert Adsense code

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#2031]
## Bug Description

When users decide not to insert the Adsense code snippet via Site Kit by toggling off _Let Site Kit insert Adsense code on your site_  a message appears informing the user of the following: 

> By not placing the code, AdSense will not show ads on your website unless you’ve already got some AdSense code.

<img width="1259" alt="Screen Shot 2020-09-04 at 11 14 22 AM" src="https://user-images.githubusercontent.com/8108643/93245052-8c799500-f73f-11ea-83d7-55c34f051312.png">

The copy could be a bit more clear. For example:

> By not placing the code, AdSense will not show ads on your website unless you’ve already placed AdSense code on your site.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
#2962 requests another copy change in the same string, going a bit further though. The suggestions from both are being combined there; as such, closing this as a duplicate.
