### ISSUE TITLE
Clear errors correctly when resetting

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2033]
## Bug Description

During the AdSense setup, reset logic is fired when the user returns to the screen after having been idle for more than 15 seconds. As part of the reset logic, a call is made to `receiveError( undefined )` (to clear the "global" error), which as of #1814 is no longer valid usage because that function now requires an error to be passed. See screenshot below:
![Screenshot 2020-09-15 at 12 11 27](https://user-images.githubusercontent.com/3531426/93254065-9e156980-f74c-11ea-8f71-b8a4f3879553.png)

As part of this issue, let's fix this invariant violation, but at the same time add a way to properly clear multiple errors at the same time via a `clearErrors( baseName )` - complementing similar selectors implemented via #1859. We should also update various `reset*` actions to include resetting related errors.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `createErrorStore` function should be expanded so that the returned store also includes a new action `clearErrors( baseName )`:
    * `baseName` should be an optional parameter.
    * If `baseName` is provided, all errors in the store that apply to `baseName` should be cleared.
    * If `baseName` is not provided, all errors in the entire store should be cleared (including the legacy `error` store property).
* The existing `clearError` should be modified to _also_ support the legacy `error` store property, similar to how `receiveError` does:
    * If `baseName` is provided, it should behave like it already does today.
    * If `baseName` is not provided, it should clear the `error` store property. A TODO annotation should be added here similar to the one in `receiveError` to remove this once all instances of the legacy behavior have been removed.
* The following store actions for resetting data should include calls to the new `clearErrors()` for the relevant `baseName` (selector name) used to originally obtain that data:
    * `modules/adsense` `resetAccounts`
    * `modules/adsense` `resetAlerts`
    * `modules/adsense` `resetClients`
    * `modules/adsense` `resetURLChannels`
    * `modules/analytics` `resetAccounts`
* The invalid `receiveError( undefined )` call in the AdSense `SetupMain` component should be replaced with a `clearError()` call which is now the "proper" way to clear the legacy error.

## Implementation Brief

* In `createErrorStore` store:
    * Modify `clearError` to clear the legacy `error` store property if no `baseName` is provided (including TODO annotation per the ACs).
    * Introduce `clearErrors` that either clears all store errors or all errors for a given `baseName`.
    * Add tests for the new behavior.
* Add `yield errorActions.clearErrors( 'getAccounts' )` to `modules/adsense` `resetAccounts` action.
* Add `yield errorActions.clearErrors( 'getAlerts' )` to `modules/adsense` `resetAlerts` action.
* Add `yield errorActions.clearErrors( 'getClients' )` to `modules/adsense` `resetClients` action.
* Add `yield errorActions.clearErrors( 'getURLChannels' )` to `modules/adsense` `resetURLChannels` action.
* Add `yield errorActions.clearErrors( 'getAccounts' )` to `modules/analytics` `resetAccounts` action.
* In AdSense `SetupMain` component, replace `receiveError( undefined )` with `clearError()`.

## QA Brief

* No "Invariant Violation" console errors should be raised when returning to the AdSense setup flow after having been idle for more than 15 seconds:
    * Open AdSense setup flow, open console.
    * Navigate to another window or tab for more than 15 seconds.
    * Then navigate back.

## Changelog entry

* Fix console error when unfocusing and refocusing tab in AdSense setup flow.

**Comment by aaemnnosttv** [comment]
IB looks good for the most part. The only thing to revise is the way `clearErrors` is called in other actions as only plain actions should be `yield`ed.

```diff
- yield dispatch( STORE_NAME ).clearErrors( ... )
+ yield errorActions.clearErrors( ... )
```

Where `errorActions` are imported from `create-error-store` https://github.com/google/site-kit-wp/blob/1a07d991bcac6da618df80f939c9819de25d24da/assets/js/googlesitekit/data/create-fetch-store.js#L28

**Comment by felixarntz** [comment]
@aaemnnosttv Updated! We currently have one `yield dispatch...` in our codebase in `assets/js/modules/analytics/datastore/properties.js` that we should probably adjust similarly as well.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ryanwelcher** [comment]
Currently, createErrorStore has no tests and after some discussion with @aaemnnosttv, we're going to hold on adding tests for the new functionality added  here until #1859 is merged.

**Comment by cole10up** [comment]
**Tested:**

Installed lated release candidate, activated and setup. Started Adsense setup, set it idle, came back:

![image](https://user-images.githubusercontent.com/57115907/94210505-c5bead00-fe83-11ea-948c-858fc703aaa6.png)

No errors, only warnings.

Passed QA ✅
