### ISSUE TITLE
Introduce `core/user/data/user-input-settings` REST endpoint

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2036]
There should be a REST endpoint that allows to store and retrieve user input settings data, relying on an external API route on the proxy service.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a REST endpoint `GET:core/user/data/user-input-settings` which retrieves user input data for the current user. It should:
    * If there is cached data (see below), return that immediately.
    * Otherwise, Issue a `POST` request to `Google_Proxy::url( '/settings/' )`, with the following data:
        * An `Authorization` header of `Bearer: {token}` with the user's access token.
        * A URL-encoded body containing `site_id` and `site_secret`.
    * The response of that is a JSON object of `settingID => settingInfo` pairs, where `settingInfo` is an object with properties `values` (array of current values specified for the setting) and `scope`, which can be either "site" or "user" depending on whether the setting applies to the entire site or is per user.
    * On success, cache the results, and then return that response:
        * All entries of `scope: 'site'` should be stored in a regular transient.
        * All entries of `scope: 'user'` should be stored in a user transient.
        * The expiration time for both should be a week.
        * The request above should only be issued if at least one of the two caches is expired or not present.
    * On failure, don't cache and return a `WP_Error` JSON response (as usual).
* There should be a REST endpoint `POST:core/user/data/user-input-settings` which updates user input data for the current user.
    * It should expect a body parameter `settings`, which should be a map of `settingID => values`.
    * It should issue a `POST` request to `Google_Proxy::url( '/settings' )`, with the same data as the above `GET` route, plus another piece of data in the URL-encoded body `settings`, passed through from the REST body parameter.
    * The response has the same structure as the one from the above `GET` route.
    * On success, cache the results the same way like the response from the `GET` route above, and return that response.
    * On failure, don't cache and return a `WP_Error` JSON response (as usual).
* For both endpoints, they should fail if either
    * the proxy is not being used
    * the site is not connected
    * the user is not authenticated
* The internal PHP API to get and set the user input data should be standalone, i.e. not just baked into the REST endpoints. It should be usable directly without calling the REST endpoint.

### Temporary mocks of API

Since the proxy service does not have these endpoints implemented yet (but we need to start this work now), its behavior should be temporarily mocked as follows:

* Intercept the server-side request to the above two proxy routes through some `wp_remote_request` middleware.
* For both routes, return a JSON success response like the following (those 5 are the only settings that will initially be supported by the proxy service):
```json
{
	"role": {
		"values": [],
		"scope": "user"
	},
	"postFrequency": {
		"values": [],
		"scope": "user"
	},
	"goals": {
		"values": [],
		"scope": "site"
	},
	"helpNeeded": {
		"values": [],
		"scope": "site"
	},
	"searchTerms": {
		"values": [],
		"scope": "site"
	}
}
```
* Rely on an aggregate temporary option prefixed with `_googlesitekit_` for the three keys with `scope: 'site'`, and an aggregate temporary user option prefixed with `_googlesitekit_` for the two keys with `scope: 'user'`.
* For the `POST` route, update the temporary option/user option accordingly. If `settings` includes any setting ID other than the five above, fail with a 400 error.
* The implementation for this mocking can be "quick and dirty" as it is temporary. Let's not worry about a proper class infrastructure, and we can use WP functions like `get_option` etc directly here without e.g. registering settings.

#### Step 1

* Create a new `Core\Util\User_Input_Settings` class:
  * The constructor should accept and set:
    * `Google\Site_Kit\Core\Authentication\Authentication` instance into a private `$authentication` property;
    * `Google\Site_Kit\Core\Storage\Transients` instance into a private `$transients` property - optional, instantiate if not provided;
    * `Google\Site_Kit\Core\Storage\User_Transients` instance into a private  `$user_transients` property - optional, instantiate if not provided.
  * `is_connected_to_proxy()` private method:
    * Return `false` if the proxy is not being used;
    * Return `false` if the site is not connected;
    * Return `false` if the user is not authenticated;
    * Otherwise return `true`;
  * `sync_with_proxy( $settigns )` private method:
    * Call `wp_remote_post` function using:
      * An URL retrieved from `Google_Proxy::url( '/settings/' )`.
      * An `Authorization` header of `Bearer: {token}` with the user's access token.
      * A URL-encoded body containing `site_id` and `site_secret`, plus `settings` if the `$settings` argument is not null.
    * Return a `WP_Error` on failure (response is wp_error or response code is not between 200 and 299).
    * Get body from the response using `wp_remote_retrieve_body` function and decode it using `json_decode` function.
    * Loop through the response settings and save settings with the `site` scope using `$transient` instance and settings with the `user` scope using `$user_transient` instance. See "_Temporary mocks of API_" section for the response data schema.
    * Return decoded body.
  * `get_settings()` method:
    * Return a `WP_Error` if `is_connected_to_proxy()` returns `false`.
    * Get site settings from `$transient` and user settings from `$user_transient` and return combined settings if both are present and not expired. Use the same schema from "_Temporary mocks of API_" section for combined settings.
    * If either setting is expired or not present, call `sync_with_proxy( null )` method and return a result of it.
  * `set_settings( $settigns )` method:
    * Return a `WP_Error` if `is_connected_to_proxy()` returns `false`.
    * Call `sync_with_proxy( $settigns )` method and return results of it.

#### Step 2

* Edit `REST_Routes::get_routes` method:
  * Add a new `REST_Route` instance to the `$routes` array with `core/user/data/user-input-settings` URI and two endpoints:
    * The first one with `WP_REST_Server::READABLE` method and a callback function that instantiates a `User_Input_Settings` instance and returns a result of the `User_Input_Settings::get_settings()` method call.
    * The second one with:
      * The `WP_REST_Server::CREATABLE` method.
      * A callback function that instantiates a `User_Input_Settings` instance and returns a result of the `User_Input_Settings::set_settings( $request['settings'] )` method call.
      * An `args` array that contains definition for the `settings` parameter which is an associative array of setting values that can be either a string or array of strings.

#### Step 3

* Edit `REST_Routes::register` method:
  * Add a new hook for the `pre_http_request` filter that accepts three arguments: `$pre`, `$args` and `$url`.
  * Return `$pre` if `$url` doesn't equal to `Google_Proxy::url( '/settings/' )`.
  * Parse `$args['body']`, grab new settings if it is available, compose settings to adhere schema defined in the "_Temporary mocks of API_" section and save it in the site options using `update_option` function with `_googlesitekit_temp_userinput` key.
  * Return the results of the `get_option( '_googlesitekit_temp_userinput' )` call, use mock data defined in the "_Temporary mocks of API_" section as a default value if the option doesn't exist yet.
  * Add a `@TODO` note to remove this hook when the actual endpoint is implemented on the proxy site.

## QA Brief

* Install [Basic Authentication handler](https://github.com/WP-API/Basic-Auth) plugin
* Use the following CLI command to send a GET request to the user input settings (don't forget to replace `{username}`, `{password}` and `{domain}` with your actual values):

  ```sh-session
  curl --user {username}:{password} http://{domain}/wp-json/google-site-kit/v1/core/user/data/user-input-settings
  ```
  * Make sure it returns JSON encoded data that equals to the default value defined in the "_Temporary mocks of API_" section.
* Use the following CLI command to send a POST request to the user input settings endpoint:

  ```sh-session
  curl --user {username}:{password} --location --request POST http://{domain}/wp-json/google-site-kit/v1/core/user/data/user-input-settings --form 'data[settings][role][]=admin' --form 'data[settings][postFrequency][]=daily' --form 'data[settings][goals][]=business' --form 'data[settings][goals][]=blogging' --form 'data[settings][helpNeeded][]=no' --form 'data[settings][searchTerms][]=test'
  ```
  * Make sure it returns JSON encoded data that equals to posted values.
* Repeat the GET request and verify that it returns JSON encoded data which has been saved on the previous step.

## Changelog entry

* Introduce `core/user/data/user-input-settings` REST datapoint.

**Comment by felixarntz** [comment]
@eugene-manuilov IB mostly looks good, just a few comments mostly on naming.

> Create a new `Core\REST_API\Routes\UserInputSettings` class

I think this class should be in `Core\REST_API` since it's not a REST API-exclusive class. There isn't really a suitable space for it, I'd say we should just put it to `Core\Util` for now. Also the class name should not use camel-case.

> The constructor should instantiate a `Google\Site_Kit\Core\Storage\Transients` instance into a private `$transient` property and a `Google\Site_Kit\Core\Storage\User_Transients` instance into a private `$user_transient` property

Let's accept them as optional constructor parameters and only instantiate if not provided. The property names should be suffixed with an `s` to match the class names, like we do elsewhere. Note that the class will likely also need access to `Google\Site_Kit\Core\Authentication\Authentication`, to get access token and site credentials for the request.

> `is_ready()` method

Maybe this should receive a more specific name like `is_connected_to_proxy()`? I don't think this should be public anyway, but better to use more descriptive names.

> `request( $settigns )` method

Maybe this should be named e.g. `sync_with_proxy( $settings )`? Same as above anyway, I don't think this should be public.

> `save_settigns( $settigns )` method

Let's name this `set_settings( $settings )` - on the server-side there's only the notion of `get` vs `set`. The only reason why it's called `save` on the client is because on the client `set` means update, without saving. But that is nothing that we have to worry about on the server.

**Comment by eugene-manuilov** [comment]
@felixarntz IB has been updated. Please, take another look.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QA brief here?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv updated.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Tested the endpoint behaves as expected using `googlesitekit.api.(get|set)`. Values are received, persisted, and returned as defined.

**Comment by sa2015ksa** [comment]
> There should be a REST endpoint that allows to store and retrieve user input settings data, relying on an external API route on the proxy service.
> 
> _Do not alter or remove anything below. The following sections will be managed by moderators only._
> 
> ## Acceptance criteria
> * There should be a REST endpoint `GET:core/user/data/user-input-settings` which retrieves user input data for the current user. It should:
>   
>   * If there is cached data (see below), return that immediately.
>   * Otherwise, Issue a `POST` request to `Google_Proxy::url( '/settings/' )`, with the following data:
>     
>     * An `Authorization` header of `Bearer: {token}` with the user's access token.
>     * A URL-encoded body containing `site_id` and `site_secret`.
>   * The response of that is a JSON object of `settingID => settingInfo` pairs, where `settingInfo` is an object with properties `values` (array of current values specified for the setting) and `scope`, which can be either "site" or "user" depending on whether the setting applies to the entire site or is per user.
>   * On success, cache the results, and then return that response:
>     
>     * All entries of `scope: 'site'` should be stored in a regular transient.
>     * All entries of `scope: 'user'` should be stored in a user transient.
>     * The expiration time for both should be a week.
>     * The request above should only be issued if at least one of the two caches is expired or not present.
>   * On failure, don't cache and return a `WP_Error` JSON response (as usual).
> * There should be a REST endpoint `POST:core/user/data/user-input-settings` which updates user input data for the current user.
>   
>   * It should expect a body parameter `settings`, which should be a map of `settingID => values`.
>   * It should issue a `POST` request to `Google_Proxy::url( '/settings' )`, with the same data as the above `GET` route, plus another piece of data in the URL-encoded body `settings`, passed through from the REST body parameter.
>   * The response has the same structure as the one from the above `GET` route.
>   * On success, cache the results the same way like the response from the `GET` route above, and return that response.
>   * On failure, don't cache and return a `WP_Error` JSON response (as usual).
> * For both endpoints, they should fail if either
>   
>   * the proxy is not being used
>   * the site is not connected
>   * the user is not authenticated
> * The internal PHP API to get and set the user input data should be standalone, i.e. not just baked into the REST endpoints. It should be usable directly without calling the REST endpoint.
> 
> ### Temporary mocks of API
> Since the proxy service does not have these endpoints implemented yet (but we need to start this work now), its behavior should be temporarily mocked as follows:
> 
> * Intercept the server-side request to the above two proxy routes through some `wp_remote_request` middleware.
> * For both routes, return a JSON success response like the following (those 5 are the only settings that will initially be supported by the proxy service):
> 
> ```json
> {
> 	"role": {
> 		"values": [],
> 		"scope": "user"
> 	},
> 	"postFrequency": {
> 		"values": [],
> 		"scope": "user"
> 	},
> 	"goals": {
> 		"values": [],
> 		"scope": "site"
> 	},
> 	"helpNeeded": {
> 		"values": [],
> 		"scope": "site"
> 	},
> 	"searchTerms": {
> 		"values": [],
> 		"scope": "site"
> 	}
> }
> ```
> 
> * Rely on an aggregate temporary option prefixed with `_googlesitekit_` for the three keys with `scope: 'site'`, and an aggregate temporary user option prefixed with `_googlesitekit_` for the two keys with `scope: 'user'`.
> * For the `POST` route, update the temporary option/user option accordingly. If `settings` includes any setting ID other than the five above, fail with a 400 error.
> * The implementation for this mocking can be "quick and dirty" as it is temporary. Let's not worry about a proper class infrastructure, and we can use WP functions like `get_option` etc directly here without e.g. registering settings.
> 
> ## Implementation Brief
> #### Step 1
> * Create a new `Core\Util\User_Input_Settings` class:
>   
>   * The constructor should accept and set:
>     
>     * `Google\Site_Kit\Core\Authentication\Authentication` instance into a private `$authentication` property;
>     * `Google\Site_Kit\Core\Storage\Transients` instance into a private `$transients` property - optional, instantiate if not provided;
>     * `Google\Site_Kit\Core\Storage\User_Transients` instance into a private  `$user_transients` property - optional, instantiate if not provided.
>   * `is_connected_to_proxy()` private method:
>     
>     * Return `false` if the proxy is not being used;
>     * Return `false` if the site is not connected;
>     * Return `false` if the user is not authenticated;
>     * Otherwise return `true`;
>   * `sync_with_proxy( $settigns )` private method:
>     
>     * Call `wp_remote_post` function using:
>       
>       * An URL retrieved from `Google_Proxy::url( '/settings/' )`.
>       * An `Authorization` header of `Bearer: {token}` with the user's access token.
>       * A URL-encoded body containing `site_id` and `site_secret`, plus `settings` if the `$settings` argument is not null.
>     * Return a `WP_Error` on failure (response is wp_error or response code is not between 200 and 299).
>     * Get body from the response using `wp_remote_retrieve_body` function and decode it using `json_decode` function.
>     * Loop through the response settings and save settings with the `site` scope using `$transient` instance and settings with the `user` scope using `$user_transient` instance. See "_Temporary mocks of API_" section for the response data schema.
>     * Return decoded body.
>   * `get_settings()` method:
>     
>     * Return a `WP_Error` if `is_connected_to_proxy()` returns `false`.
>     * Get site settings from `$transient` and user settings from `$user_transient` and return combined settings if both are present and not expired. Use the same schema from "_Temporary mocks of API_" section for combined settings.
>     * If either setting is expired or not present, call `sync_with_proxy( null )` method and return a result of it.
>   * `set_settings( $settigns )` method:
>     
>     * Return a `WP_Error` if `is_connected_to_proxy()` returns `false`.
>     * Call `sync_with_proxy( $settigns )` method and return results of it.
> 
> #### Step 2
> * Edit `REST_Routes::get_routes` method:
>   
>   * Add a new `REST_Route` instance to the `$routes` array with `core/user/data/user-input-settings` URI and two endpoints:
>     
>     * The first one with `WP_REST_Server::READABLE` method and a callback function that instantiates a `User_Input_Settings` instance and returns a result of the `User_Input_Settings::get_settings()` method call.
>     * The second one with:
>       
>       * The `WP_REST_Server::CREATABLE` method.
>       * A callback function that instantiates a `User_Input_Settings` instance and returns a result of the `User_Input_Settings::set_settings( $request['settings'] )` method call.
>       * An `args` array that contains definition for the `settings` parameter which is an associative array of setting values that can be either a string or array of strings.
> 
> #### Step 3
> * Edit `REST_Routes::register` method:
>   
>   * Add a new hook for the `pre_http_request` filter that accepts three arguments: `$pre`, `$args` and `$url`.
>   * Return `$pre` if `$url` doesn't equal to `Google_Proxy::url( '/settings/' )`.
>   * Parse `$args['body']`, grab new settings if it is available, compose settings to adhere schema defined in the "_Temporary mocks of API_" section and save it in the site options using `update_option` function with `_googlesitekit_temp_userinput` key.
>   * Return the results of the `get_option( '_googlesitekit_temp_userinput' )` call, use mock data defined in the "_Temporary mocks of API_" section as a default value if the option doesn't exist yet.
>   * Add a `@TODO` note to remove this hook when the actual endpoint is implemented on the proxy site.
> 
> ## QA Brief
> * Install [Basic Authentication handler](https://github.com/WP-API/Basic-Auth) plugin
> * Use the following CLI command to send a GET request to the user input settings (don't forget to replace `{username}`, `{password}` and `{domain}` with your actual values):
>   ```
>   curl --user {username}:{password} http://{domain}/wp-json/google-site-kit/v1/core/user/data/user-input-settings
>   ```
>   
>   
>   
>   * Make sure it returns JSON encoded data that equals to the default value defined in the "_Temporary mocks of API_" section.
> * Use the following CLI command to send a POST request to the user input settings endpoint:
>   ```
>   curl --user {username}:{password} --location --request POST http://{domain}/wp-json/google-site-kit/v1/core/user/data/user-input-settings --form 'data[settings][role][]=admin' --form 'data[settings][postFrequency][]=daily' --form 'data[settings][goals][]=business' --form 'data[settings][goals][]=blogging' --form 'data[settings][helpNeeded][]=no' --form 'data[settings][searchTerms][]=test'
>   ```
>   
>   
>   
>   * Make sure it returns JSON encoded data that equals to posted values.
> * Repeat the GET request and verify that it returns JSON encoded data which has been saved on the previous step.
> 
> ## Changelog entry
> * Introduce `core/user/data/user-input-settings` REST datapoint.

https://github.com/WP-API/Basic-Auth
