### ISSUE TITLE
Implement core/user datastore action and selector for user input settings

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2037]
Based on the REST endpoint introduced in #2036, a datastore action to update user input settings and a datastore selector to retrieve user input settings should be added to the `core/user` store.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

While this relies on REST endpoints from #2036, implementation can start at the same time since the contracts are already established and Jest tests can be added via mocks. This won't be in production use before both issues are completed anyway.

* The `core/user` JS datastore should receive a new selector `getUserInputSettings()`:
    * It should have a resolver that fetches data from `GET:core/user/data/user-input-settings` (see #2036) and puts it in the datastore.
    * It should return a map of `settingID => settingValues` (i.e. extract the values from the `settingInfo` object returned by the REST endpoint, see #2036 for more details on the expected response format).
* The `core/user` JS datastore should receive a new action `setUserInputSettings( values )`.
    * It should receive a `settingID => settingValues` map and update those settings client-side. `settingValues` must always be an array of strings.
* The `core/user` JS datastore should receive a new action `saveUserInputSettings()`.
    * It should save the current client-side settings to the server by using `POST:core/user/data/user-input-settings` and passing `settings` data (`settingID => settingValues` map).
    * It should return the JSON response on success. The client-side settings should be updated from that response (in case they are minimally different if e.g. something failed).
* The `core/user` JS datastore should receive a selector `getUserInputSetting( settingID )` that wraps `getUserInputSettings()` and extracts the corresponding setting value if present.
* The `core/user` JS datastore should receive an action `setUserInputSetting( settingID, value )` that wraps `setUserInputSettings( values )` and passes the corresponding setting value.
* In other words, this API should work pretty much exactly the same as the API returned by the `createSettingsStore` function - the selectors and actions should use the names above though, plus there is an extra restriction that settings must always be arrays of strings.

## Implementation Brief

* All selectors/actions can be added to the same, new file: `assets/js/googlesitekit/datastore/user/`
    * Add a new selector `getUserInputSettings()` using `createFetchStore` [example of a `get` action here](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/datastore/alerts.js#L36-L58) user-input.js`. It should return data from the `GET:core/user/data/user-input-settings` REST request.
    * Add a new selector: `getUserInputSetting( settingID )` that retrieves a particular setting, or `undefined` if it doesn't exist or is loading.
    * Add a new action `setUserInputSettings( values )` that saves new values client-side. `values` should be a dictionary (an object with key/value structure `{ [settingID: string]: settingsValues: Array<string> }`). It should update/add settings values but not remove old values.
    * Add a new action `setUserInputSetting( settingID, values )` that sets a particular value using the `setUserInputSettings()` action.
    * Add a new action `saveUserInputSettings()` using `createFetchStore` [example of a `set` action here](https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/reset.js#L29-L39). `values` should be sent from the client-side values stored in state (`getUserInputSettings()`). They should be sent using `POST:core/user/data/user-input-settings` to the REST API. The response received from the REST API should be saved in state as the new, canonical state for user input settings—overriding any local changes that were not persisted on the server.

Add relevant Jest tests for the above selectors/actions, using the expected responses from #2036 as mock data/fixtures for the tests.

## QA Brief

* The Jest tests should pass and cover the responses outlined in the AC for #2036, but there's little else to test here.

## Changelog entry

* Introduce `getUserInputSettings` selector and `setUserInputSettings` and `saveUserInputSettings` actions on `core/user` store.

**Comment by tofumatt** [comment]
I think the IB here is straightforward based on the AC's details, so the IB largely echoes the ACs but mentioned using `createSettingsStore` and the params validation we should be using. Let me know if there's anything missing from it, but I think the ACs here are really clear and instructive, so I didn't want to go overboard on the IB 🙂

**Comment by felixarntz** [comment]
@tofumatt How do you intend to rely on `createSettingsStore` in terms of naming? The selectors and actions from there always use `*Settings` / `*Setting`, but now we need `*UserInputSettings` / `*UserInputSetting`. Plus, how do you incorporate the array of strings validation if relying on `createSettingsStore`? I think these two points would require a bit more explanation.

**Comment by tofumatt** [comment]
Indeed, I think I meant to reference them more as inspiration rather than use them directly. The ACs mention the APIs being similar, which originally I misread as them having the same signatures, but I see now how that wouldn't add up.

I think these can be straightforwardly-implemented using the IB provided but I've removed the mention of using `createSettingsStore` directly. Your point about the API being similar in the ACs makes sense, but I've left any mention of it out of the IB.

I think that means this should be good now 🙂

**Comment by felixarntz** [comment]
IB ✅ , except (probably copy-paste error):
> All selectors/actions can be added to the same, new file: `assets/js/googlesitekit/datastore/user/`

This should be `assets/js/googlesitekit/datastore/user/user-input-settings.js`.

**Comment by tofumatt** [comment]
QA ✅
