### ISSUE TITLE
Scaffold new admin screen `googlesitekit-user-input`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2038]
A new administration screen `googlesitekit-user-input` should be added, which should not be available in the admin menu but will be linked or redirected to under certain circumstances in the future.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In PHP, a new Site Kit admin screen `googlesitekit-user-input` should be added.
    * It should not appear in the admin menu.
    * It should require capability `googlesitekit_manage_options` for access.
    * It should have title "User Input".
    * It should enqueue a new asset `googlesitekit-user-input` (see below).
    * It should render `<div id="js-googlesitekit-user-input" class="googlesitekit-page"></div>`, to be populated by JS.
* A new JS feature flag `userInput` should be added that is only enabled during `development`.
* A new JS asset with filename and handle `googlesitekit-user-input` should be added and registered in the PHP `Assets` class.
    * For now, this should just receive scaffolded code to initialize a separate React app similarly to e.g. in `googlesitekit-dashboard.js` (loading translations, wrapping in root etc.), and render a new component `UserInputApp` (to be put into `assets/js/components/user-input/UserInputApp.js`).
    * The `UserInputApp` component should for now be the following:
        * If `userInput` feature flag is active: A `div` containing an untranslatable string "TODO: Implement logic and UI.".
        * Otherwise: A `div` containing an untranslatable string like "Cheatin', huh?" 😄 

## Implementation Brief

* Add a new `Script` instance to the array returned by `Assets::get_assets`
    - `handle` of `googlesitekit-user-input`
    - `src` of `$base_url . 'js/googlesitekit-user-input.js'`
    - `dependencies` to use the default common `$dependencies`
* Add a new `Screen` instance to the array returned by `Screens::get_screens`
    - `slug` of `self::PREFIX . 'user-input'`
    - `args.title` of `User Input` (translatable)
    - `args.capability` of `Permissions::MANAGE_OPTIONS`
    - `args.enqueue_callback` that enqueues `googlesitekit-user-input`
    - `args.render_callback` should output the HTML to use for the React render target  
        ```html
        <div id="js-googlesitekit-user-input" class="googlesitekit-page"></div>
        ```
    - `args.parent_slug` can be omitted as this will be `null` by default and will not appear in the admin menu.  
* Update `webpack.feature-flags.config.js` to set `featureFlags.userInput.enabled = 'development'` similar to existing flags
* Update `webpack.config.js` to add a new entry to the `webpackConfig.entry` under "New Modules (Post-JSR)"
    - key of `googlesitekit-user-input` that points to its asset in `./assets/js/googlesitekit-user-input.js`
* Create a new `UserInputApp` as a functional component and default export in `assets/js/components/user-input/UserInputApp.js`
    - Scaffold the return/rendered output according to the AC
    - i.e. if `featureFlags.userInput.enabled`, return a non-translatable string literal: `TODO: Implement logic and UI.` otherwise [`Cheatin’ uh?`](https://core.trac.wordpress.org/changeset/42811)
* Create `assets/js/googlesitekit-user-input.js`
    - Scaffold this to render `UserInputApp` to its render target (`#js-googlesitekit-user-input`)
    - See `assets/js/googlesitekit-settings.js` for a good example of what's needed here as it will be very similar

#### Tests

* PHPUnit – no expected additions/changes
* Storybook
    - Scaffold a new file for `user-input.stories.js` with a single story for the new `UserInputApp`

## QA Brief
* There should be no User Input menu item available under the Site Kit menu
* The User Input page should be accessible by manually going to `/wp-admin/admin.php?page=googlesitekit-user-input`
* In a development env, the page should display 'TODO: Implement logic and UI.`
* In a production env. the page should display `Something went wrong.`

* 

## Changelog entry

* Scaffold new `googlesitekit-user-input` screen.

**Comment by felixarntz** [comment]
IB ✅ 

@aaemnnosttv 
> note this should never be visible to an end user because the feature flag will exclude it from a production build entirely

Theoretically this is visible to an end user if they are very curious, following Site Kit development and hit the `googlesitekit-user-input` screen URL (since the feature flag only affects JS, and the screen code will be there in PHP).

**Comment by aaemnnosttv** [comment]
> Theoretically this is visible to an end user if they are very curious, following Site Kit development and hit the `googlesitekit-user-input` screen URL (since the feature flag only affects JS, and the screen code will be there in PHP).

Hmmm yeah, my mistake. I think I had the logic mentally backwards for what message to show there based on the feature flag when I wrote that. I'll update that bit – thanks!

**Comment by cole10up** [comment]
**Tested**

Installed and activated latest SK, confirmed development build displays the correct screen:
![image](https://user-images.githubusercontent.com/57115907/95493080-d295d300-0950-11eb-8aa3-abd02df8cd39.png)

Non development:
![image](https://user-images.githubusercontent.com/57115907/95493139-e9d4c080-0950-11eb-9f4b-298b6f3d4876.png)

Confirmed menu items all function properly and nothing is broken.

Passed QA ✅
