### ISSUE TITLE
Implement base JS components for `googlesitekit-user-input` screen

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2039]
Following up on the new `googlesitekit-user-input` admin screen introduced in #2038, JS components for its UI should be implemented and used on the screen. The actual UI design will be handled in a follow-up issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* JS components for the new `googlesitekit-user-input` admin screen from #2038 should be implemented which cover the necessary functionality for that screen, and then they should be incorporated into the `UserInputApp` entry component from #2038. Let's not worry about exact appearance as part of this issue (that can happen afterwards in #2040). Still, please have a look at the [UI mocks](https://www.figma.com/file/K4MXDvLRULqRRz2zpMlh5e/SiteKit---Phase-1%3A-Onboarding?node-id=1098%3A16956) to get an idea of what it will look like later, as it should help clarify the functionality too.
* The overall app should consist of the regular Site Kit header (existing component) and a main content wrapper.
* The following UI sections should be present as main content:
    * A header saying _Customize Site Kit to match your goals_ and a short subtitle beside it: _Get metrics and suggestions that are specific to your site by telling Site Kit more about your site_
    * Components for the five user input questions. These should use common components wherever possible. Please refer to the UI mocks for more information on copy for each. The questions are (setting ID: _question_ (type, scope)):
        1. `role`: _Which best describes your team/role in relation to this site?_ (single choice, per user)
        2. `postFrequency`: _How often do you create new post for this site?_ (single choice, per user)
        3. `goals`: _What are the goals of this site?_ (multiple choice, entire site)
        4. `helpNeeded`: _What do you need help most with for this site?_ (multiple choice, entire site)
        5. `searchTerms`: _To help us identify opportunities for yoursite, enter the top three search terms that you’d like to show up for_ (list of free-text keywords separated by comma, entire site)
    * A component for the overview of all questions and the provided answers, with the ability to go back and edit, or submit ([see mock](https://www.figma.com/file/K4MXDvLRULqRRz2zpMlh5e/SiteKit---Phase-1%3A-Onboarding?node-id=1098%3A17156)).
* High-level functionality should be as follows:
    * For retrieving and setting current values for the questions, the selectors and actions from #2037 should be used. Every setting is stored as an array of string values here, i.e. for the single choice questions, just use index 0. For the multiple choice questions, check if the option is in the array of values.
    * All possible options for the questions (except free text of course) should use predefined slugs for the respective value - i.e. they shouldn't just use the label of the answer because those should be translatable and are therefore not suitable to be stored as a response. The value slugs are currently not yet defined, but let's for now just go with a "slugified" value of the user-facing English label (e.g. `__( "Sell products or services", 'google-site-kit' ) -> "sell-products-or-services"`).
    * There is one active question at a time (by default question 1.). The following question (if any) should be partially visible below already, but not actually interactive.
    * Answering a question proceeds the active question to the next. Empty responses should not be possible, i.e. also for multiple choice at least one checkbox has to be active.
    * After answering the last question, the overview UI should be shown.
        * If the user clicks to edit the answers for one question, that question should become active again. The user should then click through that and all following questions (potentially making changes) to reach the overview UI again.
        * If the user submits, all user input settings should be saved. Then the user should be redirected to the Site Kit dashboard.
    * The questions that apply to the entire site should show an annotation _This question applies to the entire site and may have an effect for other users._ If the **initial** value for such a question is not empty, it should also be added that _It has already been answered by another administrator._
        * It should be displayed in place of where [in this mock](https://www.figma.com/file/K4MXDvLRULqRRz2zpMlh5e/SiteKit---Phase-1%3A-Onboarding?node-id=1098%3A17524) you see a similar annotation and user photo.
        * The actual logic to determine and display the exact user should be implemented separately later.
* While this will probably be the case by nature of JS components, it should be ensured that these components are easily reusable elsewhere, since we'll need to implement a similar UI inside a new settings area later (see #2041).

## Implementation Brief

* Use [Header](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/header.js) component and reference other main apps (eg https://github.com/google/site-kit-wp/blob/d0b31e9f893701119947cca757f900cb9835e8a7/assets/js/components/dashboard/dashboard-app.js#L40-L82) for what the "Header + Main content/component" should look like.
* Add the following UI in the main content section:

### Header Section
* A header saying _Customize Site Kit to match your goals_ and a short subtitle beside it: _Get metrics and suggestions that are specific to your site by telling Site Kit more about your site_
<img width="290" alt="Screenshot 2020-10-06 at 16 53 08" src="https://user-images.githubusercontent.com/90871/95226949-6f435e00-07f5-11eb-80bd-9179c2d0fe02.png">

    
### User Input Section

* Have a consistently-formatted left-hand component with a header, text, and info box with link as shown in:
<img width="336" alt="Screenshot 2020-10-06 at 17 32 12" src="https://user-images.githubusercontent.com/90871/95230488-dfec7980-07f9-11eb-9c21-c678456b475d.png">
*Components for the five user input questions. Please refer to the [UI mocks](https://www.figma.com/file/K4MXDvLRULqRRz2zpMlh5e/SiteKit---Phase-1%3A-Onboarding?node-id=1098%3A16956) for more information on copy for each.

The questions are (setting ID: _question_ (type, scope)):
    1. `role`: _Which best describes your team/role in relation to this site?_ (single choice, per user)
      This should have multiple `@material/radio` type radio components with a single choice.
    2. `postFrequency`: _How often do you create new post for this site?_ (single choice, per user)
      This should have multiple `@material/radio` type radio components with a single choice.
    3. `goals`: _What are the goals of this site?_ (multiple choice, entire site)
      This should have multiple `@material/checkbox` type checkbox components that should require at least one answer but allow for two answers.
    4. `helpNeeded`: _What do you need help most with for this site?_ (multiple choice, entire site)
      This should have multiple `@material/checkbox` type checkbox components that should require at least one answer but allow for up to three answers.
    5. `searchTerms`: _To help us identify opportunities for yoursite, enter the top three search terms that you’d like to show up for_ (list of free-text keywords separated by comma, entire site)
      This should have a free-form Material `Input` component, customized to add each keyword to a "pill"-type component inline to the Input tag after "Enter"/"Return"/"comma" is typed. See https://material-ui.com/components/autocomplete/#customized-hook for an example of the type of behaviour we'd want here. This component should require one answer minimum and allow for a maximum of three answers.

(In the interest of time, the component for `searchTerms` could be simplified and split each term by `" "` or `","` in the code for now without implementing that "tag-style" UI.)

* A component for the overview of all questions and the provided answers, with the ability to go back and edit, or submit ([see mock](https://www.figma.com/file/K4MXDvLRULqRRz2zpMlh5e/SiteKit---Phase-1%3A-Onboarding?node-id=1098%3A17156)). This would involve using `Button` component with "Back" and "Next" actions that caused the current page to change.

* Use the new User Input selectors from #2037 to populate the components, including existing answers from other users for site-wide questions and existing answers for user-specific questions if appropriate.
* See the ACs for logic on how to handle existing answers and displaying who answered them, if possible

* Use the actions from #2037 to allow users to submit their answers to the questions.
* Use slugified, non-translated answers to non-open-ended questions

## QA Brief

* Add the following line to your `wp-config.php` file:
  ```php
  define( 'SHOW_USER_INPUT_SETTINGS_PAGE', true );
  ```
* Go to the `Site Kit` > `User Input` page.
* The component, when rendered, should match the UI mocks.
* Answer questions as one user, then access the User Input screen as another user and observe that "site-wide" questions are answered. (They won't yet show _who_ answered them, but they should indicate that they were previously answered by an existing user.)

## Changelog entry

* Implement UI components to use in `googlesitekit-user-input` screen.

**Comment by tofumatt** [comment]
The ACs + UI mocks here are quite thorough, and also (appreciably) flexible enough that the IB here doesn't feel like it needs a lot more explanation in the IB. I tried to clarify or point out some things there and outline the QA process, but I don't feel an issue with as detailed an AC as this needs further IB. Let me know if that's okay! 😄

**Comment by felixarntz** [comment]
@tofumatt Overall I agree we don't need to go super in depth here, but I think it would be good to add a high-level list of the components you intend to create, with proposed names and a brief note/sentence on what they'd do.

**Comment by tofumatt** [comment]
I've expanded on the components a bit and added some screenshots, but I want to be careful not to overly describe the components as the mocks are a much better reference here, and most of them rely on existing MDC React components we have. If there's more specificity still-needed here let me know, I can see us maybe needing it for the "tag" input for keywords.

If so though, that might require it's own issue to implement that UI.

**Comment by felixarntz** [comment]
@tofumatt Note that this issue is mostly about the implementation of logic and basic content and markup for all of these components. For precise styling #2040 is responsible. Of course that doesn't mean that we shouldn't do already here what's super basic (such as left-aligning text etc.), but we shouldn't worry about exact styling and adding a bunch of CSS here.

In other words, your QA Brief item "The component, when rendered, should match the UI mocks." is a bit over-eager I'd say :)

IB ✅  though

**Comment by wpdarren** [comment]
@felixarntz @cole10up I have a site all set up ready to test this but I am unable to find the mocks.  I was given access to Figma yesterday but there are a lot of files in there and unsure where to start to look for the UI mocks.  Could you please offer me some guidance on this?

**Comment by wpdarren** [comment]
### QA update: Fail

**Failed:** 

As user 1:  I completed all of the 5 questions and could see the confirmation page https://d.pr/i/ilCMir 
As user 2:  When I logged in and went to the user input page, the first and second question no data appeared. The 3rd, 4th and 5th question, I could see the data selected. I did a quick screencast here to show you what I am seeing. https://d.pr/v/OWnRp1 

**Confirmed:** 

1. Added `define( 'SHOW_USER_INPUT_SETTINGS_PAGE', true );` to wp-config.php file 
2. The user input page loaded `wp-admin/admin.php?page=googlesitekit-user-input` https://d.pr/i/IVtY0B
3. Confirmed that all screens were as per the UI mocks but with some observations. See note below. 

**Screenshots:** 1/5 https://d.pr/i/IVtY0B 2/5 https://d.pr/i/nHtmec 3/5 https://d.pr/i/eBxCAw 4/5 https://d.pr/i/pR9BrK 5/5 https://d.pr/i/HDMgiu and confirmation page https://d.pr/i/ilCMir

**Observations:** The font color on the question options were slightly lighter than in the mocks but are viewable for the user. There is also placement text on all of the pages, which I am assuming should not be there? https://d.pr/i/wzqlSD

**Comment by eugene-manuilov** [comment]
> As user 2: When I logged in and went to the user input page, the first and second question no data appeared.

@wpdarren, the first two questions are user-scoped and its answers don't show up to other users. So, this is expected behavior.

**Comment by wpdarren** [comment]
### QA update: Pass

**Confirmed:**

1. Added define( 'SHOW_USER_INPUT_SETTINGS_PAGE', true ); to wp-config.php file
2. The user input page loaded wp-admin/admin.php?page=googlesitekit-user-input https://d.pr/i/IVtY0B
3. Confirmed that all screens were as per the UI mocks but with some observations. See note below.
4. Confirmation screen appeared with answers to questions  https://d.pr/i/ilCMir
5. When logged in as a second user, data for questions 3,4,5 were appearing.  See comment above re. question 1 and 2. 

Screenshots: 1/5 https://d.pr/i/IVtY0B 2/5 https://d.pr/i/nHtmec 3/5 https://d.pr/i/eBxCAw 4/5 https://d.pr/i/pR9BrK 5/5 https://d.pr/i/HDMgiu and confirmation page https://d.pr/i/ilCMir

### Environment:

WP: 5.5.3
PHP: 7.3.21
SitKit: 1.19.0
