### ISSUE TITLE
 Explore how to show connection between user actions and results in performance.

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#204]
Explore the idea of star performers - content that works better than others against the same timeframe. If we can establish some connection between you did this and then this happened.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
This is too high-level and should be considered at the widget/module level. Closing this, let's incorporate this thinking in designing every module and widget.
