### ISSUE TITLE
Implement settings block for user input UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2041]
A new settings box should be added in the Site Kit > Settings > Admin Settings tab, which exposes the same UI that is part of the preview UI for the user input screen (see #2038, #2039, #2040). It should reuse components from #2039.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Site Kit settings "Admin Settings" tab, another box should be added, as the very first box (above "Plugin Status").
* If the current user has not yet completed the user input flow, it should have the same content as the notification from #2043 (without the dismiss button.
* If the current user has already completed the user input flow, it should display the part of the preview UI of the user input screen that shows the questions with their answers (see screenshot below). The "Edit" links should link to the `googlesitekit-user-input` screen, with query parameters that will ensure the corresponding question is shown initially.
* Components implemented in #2039 and #2043 should be reused for the UI, splitting them out and adding props to tweak behavior as necessary (the UI can be reused, but some button/link behavior needs to be different).

### Screenshot of relevant section of User Input screen
<img width="707" alt="Screenshot 2020-10-29 at 10 08 02" src="https://user-images.githubusercontent.com/3531426/97607785-ae1c9c00-19ce-11eb-89ee-597d4d780d2f.png">

## Implementation Brief

* Add another box section above https://github.com/google/site-kit-wp/blob/3a6d747e3e27795c7de81a896bb1969ac7bdcaa4/assets/js/components/settings/settings-admin.js#L35 in `assets/js/components/settings/settings-admin.js`
  * **If the user input flow has not been completed:** use the contents rendered inside the notification in #2043, but without a "dismiss" button as it isn't a notification here. The main part of that UI should be a component that can be reused for this to work, so it should either be implemented that way or refactored in this ticket.
  * **If the user input flow has been completed:** resuse component from #2039 to show the questions and their existing answers (see the provided mockup screenshots), with edit links that link to the User Input URLs to the relevant answer so the user can edit that question. The User Input app should respond to a URL provided that points to: 1. edit mode 2. the specific question
* Allow the redirect URL used in `UserInputPreview` to be overriden via a prop passed to `UserInputQuestionnaire`. This should be passed from `UserInputQuestionnaire` to `UserInputPreview` to override the URL at https://github.com/google/site-kit-wp/blob/e442ac5dc7568a134d1602ac6150d3c2483a88e4/assets/js/components/user-input/UserInputPreview.js#L60. This will allow `UserInputQuestionnaire` to return the user to the admin tab they were on after completing/updating the questionnaire. (See discussion at https://github.com/google/site-kit-wp/issues/2041#issuecomment-727071988)
* Add ability—likely with a prop—for `UserInputSettings` from #2043 to have a customized/overridable "Edit" action—that will be what we use to redirect the user to the relevant question URL when clicked in the context of this new component displayed in the Admin tab.
* The query param used can be `question` (eg: `/user-input?question=3` as the URL). The relevant query param and its value can be checked using a React hook: https://github.com/pbeshai/use-query-params. (Alternatively, we could use `useHash` from `react-use` here, if preferred, as we are planning to use that hook elsewhere in the app. Then the URL would be `/user-input#question-3`)
* Refactor `UserInputQuestionnaire` to store the current question in the relevant `query-param` or `hash` value. It's currently stored in `state` (https://github.com/google/site-kit-wp/blob/2308b75e39fd441febaea63382ed02cf7958abad/assets/js/components/user-input/UserInputQuestionnaire.js#L43), but using the URL querystring/hash will mean linking to the relevant question will automatically be handled by the component/hook on load.

## QA Brief

* Reset site kit if already set up.
* Connect site kit.
* Go to settings -> Admin Settings.
* A notification should popup like this:
	![image](https://user-images.githubusercontent.com/72751210/101055167-b3fa3400-35af-11eb-815f-245da9ab5efd.png)

	It should not have dismiss button link.
* Click on Let's go
* At each step a query param `question` must be visible. And it should change as you move to next or go back to questions.
* If reloaded at any point, you must come back to the first question (unless it is submitted already).
* After submitting, go to admin settings and this block should popup
![image](https://user-images.githubusercontent.com/72751210/101058327-07ba4c80-35b3-11eb-817b-c0064e600e69.png)
* If you click on any edit button, you should go directly to that question.
* After editing and submitting now, page should be redirected back to the Admin Settings page.
## Changelog entry

* Implement user input block to edit responses under `Site Kit > Settings > Admin Settings`.

**Comment by felixarntz** [comment]
@tofumatt The IB here is a bit too high-level IMO and doesn't go much further than the ACs. I think it would be good to describe a high-level plan to restructure the existing components as needed. For example, the `UserInputPreview` is impossible to be used for this in its current state: It would need to be split so that there is another component within it which _only_ shows the questions but not the button UI below, and furthermore it would need to be updated with e.g. a prop to modify what should happen when the user clicks on an "Edit" link.

I also think it would be good to explain a bit how to implement the query parameter functionality to focus on a specific question based on a parameter, including a proposed name for that.

**Comment by felixarntz** [comment]
@tofumatt IB mostly LGTM, just one more comment:

> Allow the "Back" and "Next" buttons to be changed to "Cancel" and "Submit" buttons in `UserInputQuestionnaire`

What would these modifications be used for? The idea is that each "Edit" link in the settings panel overview would link to the `googlesitekit-user-input` screen to the respective question, but from that point on, that screen would work the same way it currently does. The only thing that should arguably be different is that, at the end, it should maybe take the user back to `googlesitekit-settings` instead of `googlesitekit-dashboard` (but that is not defined in the ACs, so worth discussing). Let's proceed without it for now, i.e. only link to the screen (to the respective question) and that's it.

**Comment by tofumatt** [comment]
Ah, okay! I was thinking that the user would only change their answer to one particular question at a time if they have already answered all questions. I suppose it's a judgement call on that UX for the first pass at this, but my thought was that if the user has already completed the setup flow but later wants to edit a question, it could be that only the answer to _that question_ has changed.

But having them go through the rest of the flow to the end seems fine, it's not a big deal to keep pressing "next".

The point about where to redirect the user to at the end of the flow is a good point though. I've updated the IB to remove the "Back"/"Next" buttons for now, but added a bit about a redirect URL.

**Comment by felixarntz** [comment]
@tofumatt Yeah, potentially it's worth revisiting this in the future whether it makes more sense to only edit one question at a time. For now, the UI flow was intended to go through the full thing, but good point raising that 👍 

IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz – one thing to note that I'm not sure is within the scope of this issue but should be addressed at some point is that in the user input screen components it says "You can always edit your answers after your submission in Settings." although that isn't entirely accurate since the settings screen links to the user input screen to edit previous answers (they aren't directly editable on the settings screen).

**Comment by aaemnnosttv** [comment]
My feedback was addressed, but I'll take another quick look once @tofumatt approves 👍

**Comment by tofumatt** [comment]
Happy with the changes! One minor note left in the PR; if you want to commit it before merging that's cool, but nothing else from me 👍🏻

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅

**Comment by felixarntz** [comment]
@marrrmarrr Looking at the current state here, this looks a bit odd without any heading:
![Screenshot 2020-12-14 at 14 59 04](https://user-images.githubusercontent.com/3531426/102145932-fa0b8f00-3e1c-11eb-9cab-6b0952620583.png)

Should we add one? What should it be? We could make it look similar to the "Plugin Status" heading below.

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr perhaps the heading could be something like "Site Profile"?

**Comment by marrrmarrr** [comment]
@felixarntz @aaemnnosttv Let's call this "You site goals". 
Is it possible to add a short explanation there too, to give context what this will be used for? 
E.g. "Based on your responses, Site Kit will show you metrics and suggestions that are specific to your site to help you achieve your goals" or something along these lines?

**Comment by cole10up** [comment]
### QA ✅

Tested:
**Confirmed user input UI is available within Admin settings**
![image](https://user-images.githubusercontent.com/57115907/104556944-4224f980-55f5-11eb-9564-33f83c91f578.png)

Ensured different browser sizes, tab order, and general function of the input IU within the settings block functioned properly.

![image](https://user-images.githubusercontent.com/57115907/104557057-71d40180-55f5-11eb-86cc-26af47c59f0a.png)
![image](https://user-images.githubusercontent.com/57115907/104557102-84e6d180-55f5-11eb-8e9f-a1cc5bc721ab.png)

Confirmed the results displayed properly within the settings block
![image](https://user-images.githubusercontent.com/57115907/104557339-f030a380-55f5-11eb-8ffa-23c7d80f3cc4.png)

Confirmed browsers and mobile view
![image](https://user-images.githubusercontent.com/57115907/104557406-0f2f3580-55f6-11eb-8bd8-9f98d4a49da2.png)

Heading looks good. Sending to Approval.
