### ISSUE TITLE
Display dashboard notification when user input is required

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2043]
Returning users that are already connected to Site Kit and have updated to the new version which exposes the user input flow should be prompted with a notification on the dashboard about the new feature and related capabilities. See #2042 for related logic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a notification "Customize Site Kit to match your goals", which is displayed on the Site Kit dashboard if the user needs to still fill out the user input questions.
* The notification should look like [this](https://www.figma.com/file/f07vatCPHzubuJoXkgd5RU/SiteKit---Phase-1_-Onboarding?node-id=1098%3A16859).
* The notification should be displayed if:
    * ...the `featureFlags.userInput` is enabled (see #2038).
    * ...the JS `core/user` store's `getUserInputState()` selector returns anything but `completed`.
    * ...the notification is not stored as dismissed on the client (see below).
* The CTA button should be a link that points to the `googlesitekit-user-input` admin screen (see #2038).
* The Dismiss link should dismiss the notification client-side with a timeout of 3 hours.
* For storing the dismissal, let's not worry about a new (proper) API, we should be able to rely on the existing client-side code that stores notification dismissals in `sessionStorage`.

## Implementation Brief

* UserInputSettings notification:
  * Create `assets/js/components/notifications/UserInputSettings.js` file and appropriate functional component;
  * Implement the user input settings notification component using design provided in the AC;
    * Use `Notification` component with the following properties:
      * `dismissExpires` should be set to `10800` (3 * 60 * 60 seconds = 3 hours)
      * `ctaLink` should use a URL received from the `getAdminURL( 'googlesitekit-user-input' )` selector from the `core/site` datastore.
  * Don't render the notification (return `null`) if `getUserInputState()` selector from the `core/user` datastore returns `completed`.
* In the `assets/js/components/notifications/index.js` file:
  * Add a new condition that checks if `featureFlags.userInput.enabled` is truthy and adds `UserInputSettings` notification to the `googlesitekit.ErrorNotification` filter like its done for `DashboardAuthScopesAlert`.

## QA Brief

**To test, a development build must be run locally – release zips will not work.**

1. To verify this notification hasn't already been dismissed, clear your browser session storage.
2. Dispatch an action via browser console: `window.googlesitekit.data.dispatch( 'core/user' ).receiveUserInputState( 'missing' )`
    1. Warning may show without completing any action (automatically determines if missing), but we should dispatch an action to get this state explicitly to verify/QA
3. Confirm that the notification exists on the dashboard page
    1. ![image](https://user-images.githubusercontent.com/8092736/99190217-2945b800-271a-11eb-9816-bc3e17278bea.png)
4. Click "Let's Go" button
    1. Do not complete the setup steps
    2. Verify that you were taken to `/wp-admin/admin.php?page=googlesitekit-user-input`
5. Go back to dashboard
    1. Re-complete steps 1 and 2
6. Click "Remind me later" link
    1. Verify that the notification is dismissed and stays dismissed after a reload

## Changelog entry

* Implement Site Kit dashboard notification for when requesting user input to be completed.

**Comment by eugene-manuilov** [comment]
@felixarntz IB is ready for review. Unfortunately, I can't set an estimate for this ticket because I don't have access to the file with designs.

@tofumatt do you have an access to that file? Can you help me to estimate it?

**Comment by eugene-manuilov** [comment]
@felixarntz I have updated the link to the designs file and added an estimate.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@caseymorrisus Quick update here: The copy of the notification has been changed in the meantime - can you update it in the PR to the following please? _Answer 5 questions and Site Kit will customize your dashboard with specific metrics and opportunities that match your site’s goals_

(This has also been updated in the Figma file.)

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QA Brief above?

**Comment by aaemnnosttv** [comment]
## QA ✅ 

1. Tested that notification showed up as expected 
![image](https://user-images.githubusercontent.com/1621608/101058828-41c92580-3596-11eb-9a2a-1b91e5e0771a.png)
1. Tested that the primary button navigates to the user input screen 
![image](https://user-images.githubusercontent.com/1621608/101058858-50174180-3596-11eb-8d7d-0ff0982dd35a.png)
1. Tested that notification did not show again after a page reload once dismissed
