### ISSUE TITLE
Implement new UI for splash screen

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2046]
The splash screen should receive the new UI design previously created.

<img width="717" alt="Screenshot 2020-09-15 at 17 18 14" src="https://user-images.githubusercontent.com/3531426/93277748-75569980-f777-11ea-9224-82ada15fc978.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the `featureFlags.userInput` is enabled, the Site Kit splash screen UI should be modified to look like [this](https://www.figma.com/file/K4MXDvLRULqRRz2zpMlh5e/SiteKit---Phase-1%3A-Onboarding?node-id=1098%3A17463). (Otherwise, the current UI should be displayed.)
* The copy for all cases except the `else` case in the current `SetupProxy` component should be maintained, except that the button should _always_ say "Sign in with Google". Only for the `else` case the copy from the new design should be used.
    * Let's also fix a somewhat off description here for the `revoked` case, it shouldn't say `click "Start Setup"`, it should say `click "Sign in with Google"`, because there is no "Start Setup" button.

## Implementation Brief

 
In the [SetupUsingProxy component:](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/setup/setup-proxy.js)
 - add the `classnames` package as external dependency. `import classnames from 'classnames';`
 - import the `SvgIcon` component from ../../util. `import { SvgIcon, trackEvent } from '../../util';`
 - set `startSetupText` as a constant which will have the following value: "**Sign in with Google**" and remove the `startSetupText` variable from the conditions.
 - update the description for the "revoked" condition to: "**Site Kit will no longer have access to your account. If you’d like to reconnect Site Kit, click "_Sign in with Google_" below to generate new credentials.**"
 - update the title and description for the else condition to the following:
 -- title: "**Set up Site Kit**"
 -- description: "**Get insights about how people find and use your site, how to improve and monetize your content, directly in your WordPress dashboard**"
 - add the following markup for the walking person image just after the `.mdc-layout-grid__inner` element. The image should be previously be exported as a SVG in the `/assets/svg/` folder.
```
{ featureFlags.widgets.userInput.enabled && (
		<div
			className="
				googlesitekit-wizard-progress__icon
				mdc-layout-grid__cell
				mdc-layout-grid__cell--span-12-tablet
				mdc-layout-grid__cell--span-6-desktop
			"
		>
			<SvgIcon id="person-walking" width="570" height="337" />
		</div>
	) }
```
 - update the following markup `<div className="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">` to conditionally load the appropriate class names using the classnames function. If `featureFlags.userInput` is enabled, the class names should be `mdc-layout-grid__cell mdc-layout-grid__cell--span-6-desktop`.
```
<div
	className={ classnames(
		'mdc-layout-grid__cell',
		'mdc-layout-grid__cell--span-12-tablet',
		{
			'mdc-layout-grid__cell--span-6-desktop': featureFlags.widgets.userInput.enabled,
		}
	) }
>
```

In `/assets/sass/components/wizard/_googlesitekit-wizard-progress.scss`, add the following markup:
```
.googlesitekit-wizard-progress__icon {
	text-align: center;

	svg {
		height: auto;
		max-width: 100%;
	}

	@media (min-width: $bp-desktop) {
		order: 2;
	}
}
```

## QA Brief

 
- Go in Site Kit settings, Admin Settings and reset the plugin by clicking the "Reset Site Kit"
- You will be redirected to the splash screen where it should match the designs.
- If featureFlags.userInput is false, then the walking person icon should not show up. This means that the new UI should only show up in the development version of the plugin and the UI should remain unchanged on the production version.

## Changelog entry

* Implement UI for new splash screen based on authentication service improvements.

**Comment by felixarntz** [comment]
@asvinb IB ✅ 

Regarding the QA Brief (which strictly isn't necessary to provide at this stage, but not a big deal), I think it'd be good to clarify that looking at the newly implemented UI requires a development build of the plugin. And then on a production build of the plugin the changes shouldn't be visible (i.e. the current version of the UI should be displayed).

**Comment by asvinb** [comment]
Thanks @felixarntz . I'll add that to the QA Brief.

**Comment by cole10up** [comment]
Feature flag false: 
![image](https://user-images.githubusercontent.com/57115907/97397322-36535200-18a6-11eb-845e-26fb4358706f.png)

Development:
![image](https://user-images.githubusercontent.com/57115907/97397439-74e90c80-18a6-11eb-96fc-95dc947f0959.png)

**Compared to the UX above - the person looks to be on the wrong side of the copy/functionality**

Also, looking farther it seems the image isn't wrapping either when the window size is lowere.

![image](https://user-images.githubusercontent.com/57115907/97397500-9a761600-18a6-11eb-8a43-84ccf6faae65.png)

Sending back to Execution for adjustments.

**Comment by asvinb** [comment]
Hey @cole10up 
Did you clear your cache because it looks fine locally. Here is what I can see:
![image](https://user-images.githubusercontent.com/31818/97409385-f2e4fc00-1916-11eb-91a9-12c31cbe8822.png)

![image](https://user-images.githubusercontent.com/31818/97409420-04c69f00-1917-11eb-9c12-50ccc2c1318d.png)

Am on 
![image](https://user-images.githubusercontent.com/31818/97409470-15771500-1917-11eb-8a8c-3805fb3cd071.png)

**Comment by cole10up** [comment]
@asvinb yes - I cleared session storage, cache etc.

![image](https://user-images.githubusercontent.com/57115907/97464291-a14d6900-1938-11eb-9284-416d0a779245.png)

I've added you to hellogoodbye.today - the site that I am experiencing this with. Please let me know if you see this on hellogoodbye.today

**Comment by asvinb** [comment]
@cole10up Just checked on hellowgoodbye.today and this is what I can see:
![image](https://user-images.githubusercontent.com/31818/97467786-f9e32d00-195d-11eb-9b88-c90c2fff7b0d.png)
![image](https://user-images.githubusercontent.com/31818/97467845-0b2c3980-195e-11eb-8e07-95a735c55f4b.png)

Not sure why you are not seeing the correct layout. Can you try in incognito mode?

**Comment by cole10up** [comment]
**Retested**

Incognito and separate browsers experiences are showing:
![image](https://user-images.githubusercontent.com/57115907/97528045-11281780-196a-11eb-82f3-e576107ce65d.png)

![image](https://user-images.githubusercontent.com/57115907/97528060-184f2580-196a-11eb-8fc4-acbb69bf3e57.png)

![image](https://user-images.githubusercontent.com/57115907/97528097-2a30c880-196a-11eb-9b33-f64b09f8a035.png)

Confirmed setup and functionality of the plugin. 

Passed QA ✅

**Comment by cole10up** [comment]
Thanks for double checking @asvinb !
