### ISSUE TITLE
Switch `core/user/data/user-input-settings` REST endpoint to use remote API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2048]
As a follow-up to #2036, let's switch the new `core/user/data/user-input-settings` REST endpoint to actually use the remote API route on the proxy service, once that is implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The request interception mocks temporarily implemented as part of #2036 should be removed so that the two `core/user/data/user-input-settings` REST endpoints use the actual remote endpoint.
* In addition to the above, there are a few missing pieces in the current implementation, plus one detail that changed during #2039:
    * The URL path for the route should be `/site-management/settings/` instead of `/settings/`.
    * The JSON request body sent to the Site Kit Service endpoint must include the settings map under a `settings` key, not as the root value.
    * The JSON request body must also include `site_id` and `site_secret`. This must be included at all times, regardless of whether settings are set or not.
    * The JSON request body must also include `client_user_id` (the current WordPress user ID) _if_ settings are being set. It shouldn't be included if settings are only being read though.

## Implementation Brief

* Delete a hook for the `pre_http_request` filter in the `REST_Routes::register` method.
* Modify JSON data sent to Site Kit service (in `User_Input_Settings` class) per the ACs (ensuring a JSON body is _always_ passed, just with different parameters based on whether `$settings` is not empty).

## QA Brief

* Open the `REST_Routes` class and make sure there is no hook for the `pre_http_request` is available.
* Examine user input settings to make sure it still works and saves your answers.

## Changelog entry

* Switch `core/user/data/user-input-settings` REST endpoint to use remote authentication service API endpoint.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by felixarntz** [comment]
@benbowler @fhollis I just noticed this issue was added to the sprint and is being worked on, which I missed to see before, I think there was some misunderstanding here. Since this relies on the route being implemented on the authentication service, which is still in progress on our end, this cannot be completed yet. While we're close to finishing it, we cannot merge this until the endpoint exists.

@benbowler Feel free to continue the work on this issue, but you won't be able to actually test it until the endpoint is available. I'll leave an update here once it is.

I've also made one tiny addition to the ACs, the current URL used for the endpoint is not correct against where it's being exposed now, but that should be trivial to update.

**Comment by benbowler** [comment]
Thanks @felixarntz, this is in the `enhancement/2048-user-input-settings-rest-endpoint` branch ready whenever the API endpoint is available. Drop me a message on here when it's ready.

**Comment by benbowler** [comment]
@felixarntz do you think this endpoint will be available in time to get this complete in this sprint?

**Comment by benbowler** [comment]
@felixarntz testing with the staging URL `https://site-kit-dev.appspot.com/site-management/settings/` it always returns `{"error":"missing authentication token"}`.

Other URLs on the staging proxy such as `OAUTH2_SITE_URI` work without issues.

**Comment by benbowler** [comment]
Complete and tested as working with the staging proxy.

**Comment by asvinb** [comment]
- Checked `/includes/Core/REST_API/REST_Routes.php` and there is no `pre_http_request` hook present.
- Went through the user input screens and updated the values. Updated values are saved.

QA: ✅
