### ISSUE TITLE
Fix incorrect translation strings

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2049]
There are several important principles when it comes to providing translatable strings:
* Translation strings should always consist of full sentences that make sense on their own - they should never be composed out of concatenated strings.
* Variable values that need to be included in translation strings should always use placeholders like `%s`, never concatenation.
* Basically, no concatenation should ever be used around translation strings, unless it is to separate two individual sentences from each other to avoid an overly long translation string (which would have the drawback that a change in one sentence would also invalidate translations for all the other sentences).
* Translation strings should contain as little markup as possible - e.g. a string containing `<strong>%s</strong>` should instead place the `strong` tags as part of the placeholder value. Still, it should be included where it cannot be avoided (rather than splitting up the string, per the above points).
* If a translation string could mean multiple things, `_x` should be used to provide a context to briefly explain the intended purpose in as few words as possible.
* Translation strings should not include trailing spaces.

There are numerous occurrences of translation strings in Site Kit where these principles are violated, causing issues with localization. Furthermore, there are some instances where translator comments could be clarified.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Translatable strings in Site Kit should not violate the translation principles outlined on top of this issue.

## Implementation Brief

* Review translation strings across the plugin codebase to find violations of the above principles, and also look out for almost similar strings that should be combined into a single one.
* Fix the problems.
* Merge #2051.

## QA Brief

* General smoke testing, but in particular test the following:
    * Test whether the Site Kit dashboard and the Site Kit module pages still look like they did before.
    * Check that the publisher win notification for "Total Stats" (requires site with more than 5 published posts with Search Console data available at the point of new plugin activation) looks like before, including a "for month" suffix after the numbers.
    * Check that the WP dashboard widget renders blue boxes about Search Console and Analytics data being unavailable when using a site that doesn't have data on those services (e.g. a new site).

## Changelog entry

* Fix various translation strings to no longer violate localization best practices.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest SK.

Ran a series of regression tests around:

- Dashboard and modules, look and feel. **Pass**
![image](https://user-images.githubusercontent.com/57115907/94212744-dd992f80-fe89-11ea-9225-0c46205dbc24.png)

- Search Console publisher win notification **Unable to test this one as the site I tried to install SK on kept removing me after 10 seconds of use. Unsure what is happening. Time permitting I don't have another site to test this on**
![Acessar ‹ Oi ie – Brasileiros na Irlande — WordPress](https://user-images.githubusercontent.com/57115907/94212672-a75bb000-fe89-11ea-82ab-74124560a789.gif)

- WP Dashboard blue boxes. **Pass**

![image](https://user-images.githubusercontent.com/57115907/94212658-9b6fee00-fe89-11ea-881f-e2bc4b22728f.png)

Passed QA knowing search console win notification wasn't tested ✅
