### ISSUE TITLE
Remove unused module properties

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2050]
The `Module` base class in PHP currently supports a few module info properties that, while partially being declared by other modules, aren't used anywhere. These are legacy code, and to my knowledge some of those were actually never used for anything. Let's get rid of those.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PHP `Module` class should no longer support the following module information fields/properties, all of which are unused:
    * `group`
    * `feature`
    * `tags`
* All PHP module classes should be updated to no longer populate those values.
* It should be double-checked that none of those are referenced in any JS code.

## Implementation Brief

* In `Google\Site_Kit\Core\Modules\Module`:
    * Remove the `group`, `feature`, and `tags` properties and `property-read` annotations.
    * Remove the `group`, `feature`, and `module_tags` keys from the `prepare_info_for_js` method.
* Remove `group` definition from `AdSense`, `Analytics`, `Optimize`, `PageSpeed_Insights`, and `Tag_Manager`.
* Remove `tags` definition from `AdSense`, `Optimize`, and `Tag_Manager`.
* `feature` is not defined by any module class, so nothing needed here.
* Search JS codebase for `group`, `feature`, and `module_tags`, and ensure those don't reference these values anywhere.
* Update PHPUnit tests for modified classes accordingly (mostly just removing the same keys from arrays of expected keys)

## QA Brief

* Double-check that `module.[group|feature|tags]` properties are not referenced anywhere in JS

## Changelog entry

* Remove unused properties in module PHP classes.

**Comment by aaemnnosttv** [comment]
@felixarntz it's worth noting that there are a number of tests that will need to be updated as a result for all of the places where this is changed but they should all be very small and easy to make. This will be required for the build to pass anyways but good to call attention to ahead of time. I'll amend the IB to mention it, otherwise IB ✅

**Comment by caseymorrisus** [comment]
Verified that `module.[group|feature|tags]` properties are not referenced anywhere in JS by searching every instance of group, feature, and tags (to catch destructuring, can't only search for `module.group` for example as you could write ` const { group } = module`.

Passed QA ✅
