### ISSUE TITLE
The plugin should not send any data if the wp_get_environment_type() is detected as anything other than production

### ISSUE THREAD

**Issue by lukecav** [google/site-kit-wp#2054]
https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/
https://developer.wordpress.org/reference/functions/wp_get_environment_type/

No data should be sent to Google if the `WP_ENVIRONMENT_TYPE` system variable is not production.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the function `wp_get_environment_type()` exists (we should _not_ polyfill this one) and it it returns anything other than "production", all Site Kit tags (Analytics, AdSense, Tag Manager) that collect data should not be rendered.

## Implementation Brief

* create a new `Tag_Production_Guard` common tag guard class similar to `Tag_Verify_Guard` in the same `Core/Tags/Guards` location
* in the `can_activate` method of the new class use the function `wp_get_environment_type()` to return `TRUE` if the environment is `production` and the function exists
* also return `TRUE` if the function does not exist
* update the `register_tag` methods used by Adsense, Analytics, Analytics 4 and Tag Manager to include the new `Tag_Production_Guard`.  For example the Adsense code is in `Modules/Adsense.php`.  The additional code will be something like `$tag->use_guard( new Tag_Production_Guard() );`

### Test Coverage

Add tests to a new `Core/Tags/Guards/Tag_Product_GuardTest` file.
* if the `wp_get_environment_type()` function does not exist test that `TRUE` is returned
* if the functions does exist test what the tag guard returns based on whether `WP_ENVIRONMENT_TYPE` is set to `production` or not.  The environment variable can be set using `putenv`:
  * `putenv( 'WP_ENVIRONMENT_TYPE=development' )` sets it to `development`
  * `putenv( 'WP_ENVIRONMENT_TYPE' )` unsets the variable

### Visual Regression Changes

* n/a

## QA Brief

* Take a look at `Setting the environment type
` https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/
* Enable any of the modules that enable tag guard (e.g. Adsense, Analytics, Analytics 4 and Tag Manager )
* Set your environment type to `local` and save the page source for the home page of your site that end users see (e.g. http://sitekit.test) to `local.txt`
* Change it back to `production` and save the page source for the home page to `production.txt`
* Take a diff between the `local.txt` and `production.txt`, ensure that the local doesn't contain the tags in the page source, example screenshot:

<img width="1420" alt="Screen Shot 2021-07-27 at 10 32 06 AM" src="https://user-images.githubusercontent.com/373931/127114281-7bb8c461-568d-489c-aa9a-93c218f19c79.png">

## Changelog entry

* Add a new tag guard that prevents rendering tags for non-production environments.

**Comment by aaemnnosttv** [comment]
@felixarntz this sounds like a good idea and something we could probably implement as a common tag guard. What do you think?

**Comment by eclarke1** [comment]
@Hazlitte would it be possible to add an estimate here now the IB is completed?

**Comment by aaemnnosttv** [comment]
> * in the `can_activate` method of the new class use the function `wp_get_environment_type()` to return `TRUE` if the environment is `production` and the function exists

@Hazlitte The ACs only define what should happen if the function exists, so if it doesn't we must assume it is a production environment (like today) or else we'd break Site Kit for any version of WP before this was added in 5.5.

Also, for older issues like these, please make sure to fill in any parts of the issue that are missing in the template (e.g. test coverage and VRT). I've added the missing sections but they still need to be filled in.

Although the logic is fairly simple here, this is a common tag guard so it would be good to cover with a test or two. Now that we have the ability to remove or redefine functions and constants in our tests with [`runkit`](https://www.php.net/manual/en/ref.runkit7.php) we could use this to support these tests as well. This shouldn't be a big lift to the issue but worth adding I think.

**Comment by Hazlitte** [comment]
Thank you @aaemnnosttv.  I have updated the IB to reflect your observation on the AC and a description for PHPUnit tests using runkit.

**Comment by aaemnnosttv** [comment]
Thanks @Hazlitte – just about there, just a few corrections to make regarding the tests.

> if runkit/runkit7 is not installed skip the tests

After looking at this again, I think we can actually get by without this since the function will exist in some environments/jobs and not in others (i.e. `PHP (PHP 5.6, WordPress 4.7)`) – more on this below.

If the function doesn't exist, we should test it returns `true`.

If it does exist, we can test the guard based on the various values of `WP_ENVIRONMENT_TYPE`.

I just found that we don't need to worry about messing with the `WP_ENVIRONMENT_TYPE` constant. As long as it isn't defined (which it shouldn't be in our tests), we can set and unset this as an environment variable instead which doesn't require any runkit hackery (which is best to avoid if we can).

We can set the env variable like so:

```php
// Set to non-production value
putenv( 'WP_ENVIRONMENT_TYPE=development' );

// Unset the variable – getenv( 'WP_ENVIRONMENT_TYPE' ) will return `false`
putenv( 'WP_ENVIRONMENT_TYPE' );
```

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
Unfortunately we can't run
`putenv( 'WP_ENVIRONMENT_TYPE=development' )` as  

due to
https://github.com/WordPress/WordPress/blob/f5713b8d717b398efe7de40c869f77543fb2068e/wp-includes/load.php#L195

**Comment by asvinb** [comment]
### QA: ❌ 

- Created a new site on jurassic.ninja (https://competent-darkling.jurassic.ninja/)
- Installed the Site Kit plugin and tester plugin
- Switched to develop branch via tester plugin
- Connected Tag Manager service
- Inspected the FE and saw Tag Manager snippet inserted.
- Edited the theme's `functions.php` and added `define( 'WP_ENVIRONMENT_TYPE', 'local' );`
- Refreshed the homepage, Tag Manager snippet is still there.

**Comment by ivankruchkoff** [comment]
Putting the define into your theme functions is too late and it has already been set in WordPress far earlier and it cannot be overridden, see the unit test where we have to override the static variable: https://github.com/google/site-kit-wp/pull/3734/files#diff-cd9bfad4b0a994c130af2d7fce75605bab9e19e99ccea0a3124f6ca73e69c4f4R46

Here's what I have between staging / production in a diff after setting the variable in wp-config.php:
https://editor.mergely.com/7eHVtWqc/

Are you able to compare @asvinb ? Can you also confirm what the function https://developer.wordpress.org/reference/functions/wp_get_environment_type/ returns.

**Comment by asvinb** [comment]
### QA: ✅  

- Created a new site on jurassic.ninja (https://competent-darkling.jurassic.ninja/)
- Installed the Site Kit plugin and tester plugin
- Switched to develop branch via tester plugin
- Connected Tag Manager service
- Inspected the FE and saw Tag Manager snippet inserted.
- Edited the `wp-config.php` and added `define( 'WP_ENVIRONMENT_TYPE', 'local' );`
- Refreshed the homepage, Tag Manager snippet is not there.

**Comment by asvinb** [comment]
Thanks @ivankruchkoff . All good now when I defined `WP_ENVIRONMENT_TYPE` in `wp-config.php` 😅

**Comment by andyblackwell** [comment]
Why would you forcibly disable the ability to develop/debug on a non-prod environment?

https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/
we've used a setup like this ^ to use the non-production auth flow to allow this to work for development purposes

**Comment by aaemnnosttv** [comment]
@andyblackwell This issue was about preventing service tags from being placed in non-production environments  while allowing Site Kit's dashboards to still work. I think it could be useful to allow this to be overridden without requiring the environment type to change.

Would you please elaborate on your situation?

**Comment by andyblackwell** [comment]
sorry, I missed that there was a reply

The use case is mainly the need to be able to develop & test in a non-prod environment. Things like writing code to set custom dimensions, firing events, trigger pageviews on infinite scroll, passing new events & data to GTM, or test that upgrading the plugin still works well in our setup and with our other plugins. None of this is possible at the moment with this change, and we need to downgrade to an older version in order to at least test some of those things.

I think at minimum there should be a filter to allow disabling this check

**Comment by aaemnnosttv** [comment]
Thanks @andyblackwell, that makes sense. May I also ask if there is a reason why it would be impractical to temporarily set the WP environment type to `production` to do this testing? Are there other safeguards related to this being set to a non-production type that are in place that you are trying to preserve?

**Comment by andyblackwell** [comment]
We do have environment specific configurations and safeguards as you eluded to that stem from the env that is set, so that isn't an option.

**Comment by aaemnnosttv** [comment]
Thanks @andyblackwell – I opened a [new issue](https://github.com/google/site-kit-wp/issues/4774) to allow for more control 👍

**Comment by aaemnnosttv** [comment]
Hi @andyblackwell 👋 just wanted to follow-up with you to let you know that the upcoming release (1.78.0) will include a new filter to control which environment types tags will be output for. See #4474 for details.
