### ISSUE TITLE
Explore expanding types of in-product notifications

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#206]
Show when recent posts have cracked the top 10 - this could also be a publisher win. We could also track how they're performing against each other?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
This is part of the notifications product scoping and UXD work, but not super helpful on its own. Closing.
