### ISSUE TITLE
Migrate AdSense page "Performance" widget to use Widget API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2065]
The "Performance over the last x days" widget on the AdSense module page should be refactored as a new component that is registered and rendered using the Widget API.

The existing component should be untouched and only be renamed, giving it a `Legacy` prefix.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `ModuleOverviewWidget` should be added in `assets/js/modules/adsense/components/module/ModuleOverviewWidget.js`.
* It should be implemented as a functional, hook-based, datastore-driven widget component that renders the existing "Performance over the last x days" block on the AdSense module page, in a refactored way.
    * In other words, it should replicate what the legacy `AdSenseDashboardWidgetOverview` and `AdSenseDashboardWidgetSiteStats` components display. These components were already refactored at a previous point so the new component should be able to reuse most of the code. The main things to change is to create the API requests themselves instead of receiving data via props, as well as to use `Widget*` components via props.
    * Sub-components can be implemented as necessary. If reusable, they should go into `assets/js/modules/adsense/components/common`. Otherwise (if specific to just this widget), they should go into a new `assets/js/modules/adsense/components/module/ModuleOverviewWidget` directory; in this case, the main widget component should go into the `index.js` file within that directory.
* The `AdSenseDashboardWidgetOverview` and `AdSenseDashboardWidgetSiteStats` components should be renamed, receiving a `Legacy*` prefix.
* The new component should be used to register a new widget in `assets/js/modules/adsense/index.js` (for testing, requires to enable the `widgets.moduleScreens` feature flag):
    * slug: `adsenseModuleOverview`
    * width: `WIDGET_WIDTHS.FULL`
    * priority: `1`
    * wrapWidget: `false` (since it needs to render `Widget` manually to add the `Header` prop
    * widget area: `AREA_MODULE_ADSENSE_MAIN`

## Implementation Brief
* Create a new file `assets/js/modules/adsense/components/module/ModuleOverviewWidget.js` which will export the `ModuleOverviewWidget` functional component.
* `ModuleOverviewWidget` should have the following props: `Widget`, `WidgetReportZero` and `WidgetReportError`, similar to what is done in `assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js`.
* `ModuleOverviewWidget` should take most of the code from the following files:
	* `assets/js/modules/adsense/components/dashboard/AdSensePerformanceWidget.js` with the following changes:
		* Remove the `handleDataSuccess` and `handleDataError` props usage.
		* Remove usage of the `AdSenseDashboardWidgetOverview` and `AdSenseDashboardWidgetSiteStats`.
	* `assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidgetOverview.js` with the following changes:
		* Remove the `handleDataSuccess` and `handleDataError` props usage.
	* `assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidgetSiteStats.js` with the following changes:
		* Remove the `handleDataSuccess` and `handleDataError` props usage.
	* If there are any errors in the `getReport` queries, render the `WidgetReportError` component, passing `adsense` as value for the `moduleSlug` prop and the `error` as well.
	* If there is no data for any `getReport` queries, render the `WidgetReportZero` component instead of `ReportZero` component, passing `adsense` as value for the `moduleSlug` prop.
* Create a new file `assets/js/googlesitekit/widgets/components/WidgetHeaderTitle` which will export the `WidgetHeaderTitle` functional component.
	* `WidgetHeaderTitle` should have only 1 prop, `title` which is a `string` and render the same markup as the title of the legacy component (For e.g `Performance over the last 28 days`) without any grid markup/class names.
* Create a new file `assets/js/googlesitekit/widgets/components/WidgetHeaderCTA` which will export the `WidgetHeaderCTA` functional component.
	* `WidgetHeaderCTA` should have the following props:
		* `href`: String
		* `label`: String
		* `external`: bool (default: `true`)
	* and it should use the `Link` component to render the external CTA leading to a module's service frontend. For e.g `See full stats in AdSense`.
* `ModuleOverviewWidget` should render the same markup from `AdSensePerformanceWidget` and `AdSenseDashboardWidgetSiteStats` combined, wrapped within the `Widget` component, similar to how it's done in `DashboardPopularKeywordsWidget` but with the following change:
	* Update the usage of the `Widget` component to add the `Header` prop. The value of the `Header` prop is a function which returns the title (for e.g `Performance over the last 28 days`) using the newly added `WidgetHeaderTitle` component and the CTA (`See full stats in AdSense`) using the `WidgetHeaderCTA` component. The function should only render 2 child elements since flexbox is going to be used to space them out in the header. Refer to the legacy components on how the values for the title and CTA are set.
* Using `assets/sass/widgets/_widgets.scss`,
	* Edit the `.googlesitekit-widget__header` class name to use `flexbox`, with the `justify-content` set to `space-between`.
	* Remove margins from headings within the `.googlesitekit-widget__header` class name.
	* Make sure children within the `.googlesitekit-widget__header` class name stack properly on small screens, with a margin of `16px` between the child elements.
* Edit `assets/js/modules/adsense/index.js` and register a new widget with the following properties:
	* Component: `ModuleOverviewWidget`,
	* slug: `adsenseModuleOverview`
	* width: `WIDGET_WIDTHS.FULL`
	* priority: `1`
	* wrapWidget: `false`
	* widget area: `AREA_MODULE_ADSENSE_MAIN`
* Edit `/stories/module-adsense-components.stories.js` to add a new stories for the `ModuleOverviewWidget` under the `AdSense Module/Components/Module Page/` group, showing the following states:
	* When the data is loading.
	* When there is no data.
	* When there is an error.
	* When data has loaded.
* The `AdSenseDashboardWidgetSiteStats` and `AdSenseDashboardWidgetOverview` components should be renamed, receiving a `Legacy*` prefix and references should be updated.

## Test Coverage
* N/A

## Visual Regression Changes
* N/A

## QA Brief
* Visit the "AdSense" dashboard where the new widget should be displayed above the legacy one.
* Both widgets should function the same way and display the same data.

## Changelog entry

* Migrate AdSense module page overview widget to use Widget API.

**Comment by asvinb** [comment]
@felixarntz About the following note in the AC:
**The main things to change is to create the API requests themselves instead of receiving data via props, as well as to use Widget* components via props.**
Turns out that the components are already making the requests themselves and no data is being received via props. Let me know if am missing something here. 
Thanks!

**Comment by felixarntz** [comment]
@asvinb IB is mostly looking good, some feedback though
> Turns out that the components are already making the requests themselves and no data is being received via props. Let me know if am missing something here.

The AC is referring to `AdSenseDashboardWidgetOverview` and `AdSenseDashboardWidgetSiteStats`, which _do_ receive props for some of the values used in the API request, so it was mostly about that. Since all of these components will be combined into the new one, that shouldn't matter anymore though, so your IB looks okay regarding that.

> `ModuleOverviewWidget` should render the same markup from `AdSensePerformanceWidget` and `AdSenseDashboardWidgetSiteStats` combined, wrapped within the `Widget` component, similar to how it's done in `DashboardPopularKeywordsWidget`.

Note that the appearance of the widget should match what there is today. In other words, using `Widget` the same way that `DashboardPopularKeywordsWidget` does is not sufficient, since it would be missing the header and footer the (widget) box currently has on the AdSense module page in its legacy version. The end result here should visually match exactly what is currently on the AdSense module page for that box.

**Comment by asvinb** [comment]
@felixarntz I've updated the IB to include a note to create a new `WidgetHeader` component which should cater for the widget header and we don't need the widget footer since there's none currently :)

**Comment by felixarntz** [comment]
@asvinb Almost good to go now, except for some feedback on `WidgetHeader`:

* The name for the component is a bit odd, given the `Widget` component itself already has the concept of a widget header (see the CSS class it adds). Overall the component shouldn't be necessary I think (see below).
* Since there already is a widget header, we shouldn't need to render another wrapper element. How about we update the `googlesitekit-widget__header` CSS rules in general to use flexbox, with horizontal `space-between`, with the content left-aligned for only a single item? This doesn't break any existing usage. This way we don't need another component at all. We can just render the widget title as first element and the CTA as second element, right in the component.
* Expanding on the above, if needed, I'd be much more in favor of specific components for the widget title and CTA, e.g. `WidgetHeaderTitle` and `WidgetHeaderCTA`.

**Comment by asvinb** [comment]
@felixarntz I've updated the IB but a couple of notes:

- I think we don't need the extra `WidgetHeaderTitle` and `WidgetHeaderCTA` since if they were to be, they would just return some text without any logic attached. I think it'll be overkilled to have them :)
- I'am thinking whether we should actually keep the custom `WidgetHeader` component like I originally wrote, mainly because the current header implementation for the legacy components is using Material UI's grid for the padding and spacing. If we're going to use the flexbox only approach, we'll have to add a class name to cater for the padding or a wrapping container to handle the padding, not to mention to have the header elements stack on small screens. So basically, am wondering instead of the flexbox approach, whether to go with the current grid implementation. I can certainly see the custom header component to be used for other widgets as well, which is not AdSense specific.

Let me know what you think :)

**Comment by felixarntz** [comment]
@asvinb 
> I think we don't need the extra `WidgetHeaderTitle` and `WidgetHeaderCTA` since if they were to be, they would just return some text without any logic attached

I don't have a strong preference on having them or not having them, but I think having them, even though they will be super simple, would inform to have the same markup for all of these; for example `WidgetHeaderTitle` would include the standard heading tag with classes, and `WidgetHeaderCTA` would always be an external CTA leading to a module's service frontend. Yes they are super simple, but without having them we would rewrite the same type of markup in every widget header, leaving (admittedly just a tiny bit) more room for error. I'll leave that up to you.

> I'am thinking whether we should actually keep the custom `WidgetHeader` component like I originally wrote, mainly because the current header implementation for the legacy components is using Material UI's grid for the padding and spacing

Hmm I think we could still solve this just by defining some additional styles for `googlesitekit-widget__header` (good point on the gaps, we should make sure this looks good on mobile too). When looking at the existing styles there, it does already use the correct padding, without adding full complexity of the grid; so I think let's rather define more styles for the above class rather than introducing a new component using the grid just to get the spacing.

Let me know your thoughts.

**Comment by asvinb** [comment]
Sounds good @felixarntz . I've updated the IB to reflect your thoughts. Let's also tweak the styles for the `googlesitekit-widget__header` class name so that its direct children stack on small screens since we already have the padding in place :)

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- The "AdSense" module - Performance widget -  the new widget functions the same way and displays the same data as the legacy widget. 

![image](https://user-images.githubusercontent.com/73545194/113417068-3fb48d80-93f5-11eb-8678-2ce6c999e54d.png)
