### ISSUE TITLE
Migrate AdSense page "Performance by page" widget to use Widget API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2066]
The "Performance by page over the last x days" widget on the AdSense module page should be refactored as a new component that is registered and rendered using the Widget API.

The existing component should be untouched and only be renamed, giving it a `Legacy` prefix.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `ModuleTopEarningPagesWidget` should be added in `assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget.js`.
* It should be implemented as a functional, hook-based, datastore-driven widget component that renders the existing "Performance by page over the last x days" block on the AdSense module page, in a refactored way.
    * In other words, it should replicate what the legacy `DashboardAdSenseTopPages` and `AnalyticsAdSenseDashboardWidgetTopPagesTable` components display.
    * Sub-components can be implemented as necessary. If reusable, they should go into `assets/js/modules/adsense/components/common`. Otherwise (if specific to just this widget), they should go into a new `assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget` directory; in this case, the main widget component should go into the `index.js` file within that directory.
* The `DashboardAdSenseTopPages` and `AnalyticsAdSenseDashboardWidgetTopPagesTable` components should be renamed, receiving a `Legacy*` prefix.
* The new component should be used to register a new widget in `assets/js/modules/adsense/index.js` (for testing, requires to enable the `widgets.moduleScreens` feature flag):
    * slug: `adsenseModuleTopEarningPages`
    * width: `WIDGET_WIDTHS.FULL`
    * priority: `2`
    * wrapWidget: `false` (since it needs to render `Widget` manually to add the `Header` prop
    * widget area: `AREA_MODULE_ADSENSE_MAIN`

Hint: Technically, the new component needs to be very close to the already refactored `DashboardTopEarningPagesWidget` widget component, so that should make it fairly trivial to implement the new component, even with the minor differences in UI.

## Implementation Brief
* Create a new file `assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget.js` which will export the `ModuleTopEarningPagesWidget` functional component.
* `ModuleTopEarningPagesWidget` should have the following props: `Widget`, `WidgetReportZero` and `WidgetReportError`, similar to what is done in `assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js`.
* `ModuleTopEarningPagesWidget` should take most of the code from `assets/js/modules/analytics/components/dashboard/AnalyticsAdSenseDashboardWidgetTopPagesTable.js` with the following changes:
	* Remove the use of the `withData` HOC. Instead, to get the report data, query the data store using the `getReport` selector.
	* Check if the data report from `getReport` is available via the `hasFinishedResolution` selector of the module's data store and if it's not available, render the `<PreviewTable padding />` component.
	* Check if there is an error for the `getReport` selector via the `getErrorForSelector` selector of the module's data store. If there is an error, then render the `WidgetReportError` component, passing `adsense` as value for the `moduleSlug` prop and the `error` as well.
	* Check if we don't have any data for the report via the imported `isZeroReport` function from `assets/js/modules/search-console/util/is-zero-report.js`. If this is the case, render the `WidgetReportZero` passing `adsense` as value for the `moduleSlug` prop.
	* Instead of using the `getDataTableFromData` function to render the table, use the newly added `ReportTable` component. #2249
	* `ModuleTopEarningPagesWidget` should render the data table wrapped within the `Widget` component, similar to how it's done in `DashboardPopularKeywordsWidget`
* Edit `assets/js/modules/adsense/index.js` and register a new widget with the following properties:
	* Component: `ModuleTopEarningPagesWidget`,
	* slug: `adsenseModuleTopEarningPages`
	* width: `WIDGET_WIDTHS.FULL`
	* priority: `2`
	* wrapWidget: `false`
	* widget area: `AREA_MODULE_ADSENSE_MAIN`
* Edit `/stories/module-adsense-components.stories.js` to add a new stories for the `DashboardPopularKeywordsWidget` under the `AdSense Module/Components/Module Page/` group, showing the following states:
	* When the data is loading.
	* When there is no data.
	* When there is an error.
	* When data has loaded.
* The `DashboardAdSenseTopPages` and `AnalyticsAdSenseDashboardWidgetTopPagesTable` components should be renamed, receiving a `Legacy*` prefix.

## Test Coverage
* N/A

## Visual Regression Changes
* N/A

## QA Brief

You will need to enable the `widgets.moduleScreens` feature, and have Adsense linked.

* Go to the AdSense module page, `/wp-admin/admin.php?page=googlesitekit-module-adsense`
* There should now be a new `Performance by page over the last 28 days` Widget, second from top.
* This new widget should be identical to the legacy version at the bottom of the page
* A key difference is that it should prompt you to link AdSense if you haven't already done so (it's possible to get the legacy version to render without doing this properly by forcing it with the tester settings)
* The widget should handle zero data, AdSense not being linked, error and loading states as well. It might help to use Storybook to verify this.
* The legacy version should render same as before, at the bottom of the page.

## Changelog entry

* Migrate AdSense module page "Top earning pages" widget to use Widget API.

**Comment by tofumatt** [comment]
IB ✅

**Comment by felixarntz** [comment]
Moving this to the 1.31.0 release since it's not critical. If it gets ready by tomorrow, we can reassess.

**Comment by cole10up** [comment]
@johnPhillips - Can we get some QA notes on this one? Giving me an idea what to focus on for testing. I assume regression around Adsense as a whole but I want to be sure.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Can see a new Performance by page over the last X days Widget and it is identical to the legacy version. - [Screenshot](https://user-images.githubusercontent.com/73545194/115749622-2fa62300-a38f-11eb-973a-61a671792165.png)
- You are prompted to link AdSense and Analytics if you haven't already done so - [Screenshot](https://user-images.githubusercontent.com/73545194/115749793-61b78500-a38f-11eb-910c-bc1dc8f594bb.png)
- The widget handle zero data, AdSense not being linked, error and loading states as well. This was checked on Storybook
- The legacy version renders as before, at the bottom of the page. - [Screenshot](https://user-images.githubusercontent.com/73545194/115750172-ca066680-a38f-11eb-9c4a-56ab24c31cd6.png)
