### ISSUE TITLE
Migrate Analytics page "Top content" widget to use Widget API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2068]
The "Top content over the last x days" widget on the Analytics module page should be refactored as a new component that is registered and rendered using the Widget API.

The existing component should be untouched and only be renamed, giving it a `Legacy` prefix.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `ModulePopularPagesWidget` should be added in `assets/js/modules/analytics/components/module/ModulePopularPagesWidget.js`.
* It should be implemented as a functional, hook-based, datastore-driven widget component that renders the existing "Top content over the last x days" block on the Analytics module page, in a refactored way.
    * In other words, it should replicate what the legacy `AnalyticsDashboardWidgetTopPagesTable` component displays.
    * Sub-components can be implemented as necessary. If reusable, they should go into `assets/js/modules/analytics/components/common`. Otherwise (if specific to just this widget), they should go into a new `assets/js/modules/analytics/components/module/ModulePopularPagesWidget` directory; in this case, the main widget component should go into the `index.js` file within that directory.
* The new component should be used to register a new widget in `assets/js/modules/analytics/index.js` (for testing, requires to enable the `widgets.moduleScreens` feature flag):
    * slug: `analyticsModulePopularPages`
    * width: `WIDGET_WIDTHS.FULL`
    * priority: `2`
    * wrapWidget: `false` (since it needs to render `Widget` manually to add the `Header` prop
    * widget area: `AREA_MODULE_ANALYTICS_MAIN`
* `AnalyticsDashboardWidgetTopPagesTable` should be renamed to have a `Legacy*` prefix added.

Hint: For the implementation it might be useful to look at `DashboardPopularPagesWidget` which renders something very similar, just with less columns and different header/footer in the dashboard.

## Implementation Brief

* Implement requirements defined in the AC

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Set up sitekit and tester plugins on your local;
* Activate and connect the Analytics module;
* Enable the `widgets.moduleScreens` feature in the tester plugin settings;
* Go to the Analytics module page and make sure that you see the new Top Content widget above the legacy one. It should look and work the same as the legacy one.

## Changelog entry

* Migrate Analytics module page popular pages widget to use Widget API.

**Comment by eugene-manuilov** [comment]
@felixarntz this is ready for IB review. All implementation requirements already defined in the AC and I have nothing to add to it.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz should this not use `ReportTable` internally? I think we should hold on merging this until that one is merged after which this one should be updated to use it as well.

**Comment by felixarntz** [comment]
@eugene-manuilov Once #2918 is merged, can you please update the PR for this one accordingly? In addition to applying it against the updated from #2918, please make sure to use the new `ReportTable` component (see above comment).

I'll mark this as blocked by #2918.

**Comment by felixarntz** [comment]
@eugene-manuilov This still needs a QA Brief.

**Comment by eugene-manuilov** [comment]
@felixarntz do you mind reviewing #3034? I have added storybook stories for the new widgets.

**Comment by felixarntz** [comment]
Thanks @eugene-manuilov - left some feedback there.

**Comment by eugene-manuilov** [comment]
Thanks, @felixarntz. PR is updated. I have also reworked the widget stories generator function to generate a loading state for widgets which revelated a few issues in other stories/components which have been fixed. So, please, don't be surprised to see additional changes there :smile:

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@eugene-manuilov on the new Top content widget the `See full stats in Analytics` and `Source: Analytics` links point to the `Audience Overview` report on Google Analytics but on the legacy widget it points to `Pages` report. 

Everything else matches up the same.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Compared the legacy and Analytics module page and made sure that the new Top Content widget looks and works the same as the legacy one.

**_New widget_**
![image](https://user-images.githubusercontent.com/73545194/113149456-9b501100-9265-11eb-8a6f-b0764164fe26.png)

**_Legacy widget_**
![image](https://user-images.githubusercontent.com/73545194/113149478-a1de8880-9265-11eb-8f89-8a31d2a026c0.png)
