### ISSUE TITLE
Migrate Analytics page "Top acquisition channels" widget to use Widget API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2069]
The "Top acquisition channels over the last x days" widget on the Analytics module page should be refactored as a new component that is registered and rendered using the Widget API.

The existing component should be untouched and only be renamed, giving it a `Legacy` prefix.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `ModuleAcquisitionChannelsWidget` should be added in `assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget.js`.
* It should be implemented as a functional, hook-based, datastore-driven widget component that renders the existing "Top acquisition channels for the last x days" block on the Analytics module page, in a refactored way.
    * In other words, it should replicate what the legacy `LegacyAnalyticsDashboardWidgetTopAcquisitionSources` component displays.
    * Sub-components can be implemented as necessary. If reusable, they should go into `assets/js/modules/analytics/components/common`. Otherwise (if specific to just this widget), they should go into a new `assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget` directory; in this case, the main widget component should go into the `index.js` file within that directory.
* The new component should be used to register a new widget in `assets/js/modules/analytics/index.js` (for testing, requires to enable the `widgets.moduleScreens` feature flag):
    * slug: `analyticsModuleAcquisitionChannels`
    * width: `WIDGET_WIDTHS.FULL`
    * priority: `3`
    * wrapWidget: `false` (since it needs to render `Widget` manually to add the `Header` prop
    * widget area: `AREA_MODULE_ANALYTICS_MAIN`

Hint: You can review the **old** `DashboardAllTrafficWidget` component (look at the codebase for an older release such as 1.23.0) as it renders almost the same high-level UI as this component. Note that, while the dashboard All Traffic widget was completely replaced with the new version, the separate widget here should be kept as is, i.e. this issue should simply replicate it as a Widget API-based widget.

## Implementation Brief

* Create a new file `assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget.js` which will export the `ModuleAcquisitionChannelsWidget` functional component.
* This new component should have the following props: `Widget`, `WidgetReportZero` and `WidgetReportError`, similar to what is done in `assets/js/modules/analytics/components/dashboard/DashboardPopularPagesWidget.js`.
* Most of the code for this component can come from `LegacyAnalyticsDashboardWidgetTopAcquisitionSources`, with the following exceptions:
	* Remove the `withData` HOC and get the report data using the `getReport` selector, passing the `dateRange`, `trafficSourcesReportDataDefaults` and `url` as arguments.
	* Use the store's `hasFinishedResolution` selector to determine whether the component is in a loading state. If it is, return a ` <PreviewTable rows={ 4 } rowHeight={ 50 } />` component.
	* Use the store's `getErrorForSelector` to determine if the component is in an error state, and if so, return a `<WidgetReportError>`, passing the error.
	* Use the Analytics module's `isZeroReport` util to determine whether the data is an empty report. If it is, return a `<WidgetReportZero moduleSlug="analytics" />` component.
	* Instead of using the `getDataTableFromData` function to render the table, use the newly-added `ReportTable` component. #2249
	* Return a `<Widget noPadding>` component that contains the table as a child. The `Widget` should have `Header` and `Footer` props set as follows:
		* Footer should be a `SourceLink` component (you can generate the `href` prop using the Analytics store's `getServiceReportURL` method, passing in date range arguments using the `generateDateRangeArgs` utility).
		* Header should be a new component (you can put it in `assets/js/modules/analytics/components/common` so we can re-use it) that renders the widget title and 'See full stats in Analytics' external link as in the legacy component. 
* Edit `assets/js/modules/analytics/index.js` and register a new widget with the following properties: 
	* slug: `analyticsModuleAcquisitionChannels`
	* component:  `ModuleAcquisitionChannelsWidget`
	* width: `WIDGET_WIDTHS.FULL `
	* priority: `3` 
	* wrapWidget: `false` (since it needs to render Widget manually to add the `Header` prop) 
	* widget area: `AREA_MODULE_ANALYTICS_MAIN`
	* Note that in order to see this, you'll need to enable the `widgets.moduleScreens` feature flag using the tester settings plugin
* Edit `stories/module-analytics.stories.js` to use the new component, adding stories for the following states:
	* Loading
	* Loaded
	* No data
	* Error

## QA Brief

* Enable the feature flag `widgets.moduleScreens` in tester plugin.
* Open /wp-admin/admin.php?page=googlesitekit-module-analytics and compare the two dashboards.

**QA: eng** 
Before Merge compare these two stories
https://google.github.io/site-kit-wp/storybook/pull/3035/?path=/story/analytics-module--top-acquisition-pie-chart
https://google.github.io/site-kit-wp/storybook/pull/3035/?path=/story/analytics-module-components-module-page-acquisition-channels-widget--loaded

After merge compare these two stories
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module--top-acquisition-pie-chart
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-components-module-page-acquisition-channels-widget--loaded

If you want the same data in both charts to compare, you can tweak the two legacy components:
LegacyAnalyticsDashboardWidgetTopAcquisitionSources:
from:
```
function LegacyAnalyticsDashboardWidgetTopAcquisitionSources( { data } ) {

```
to:
```
function LegacyAnalyticsDashboardWidgetTopAcquisitionSources( { data2 } ) {
	const data = [ { nextPageToken: null, columnHeader: { dimensions: 'ga:channelGrouping', metricHeader: { metricHeaderEntries: [ { name: 'Sessions', type: 'INTEGER' }, { name: 'Users', type: 'INTEGER' }, { name: 'New Users', type: 'INTEGER' } ] } }, data: { dataLastRefreshed: null, isDataGolden: null, rowCount: 4, samplesReadCounts: null, samplingSpaceSizes: null, rows: [ { dimensions: [ 'Organic Search' ], metrics: [ { values: [ '55', '14', '3' ] } ] }, { dimensions: [ 'Referral' ], metrics: [ { values: [ '13', '17', '39' ] } ] }, { dimensions: [ 'Direct' ], metrics: [ { values: [ '10', '73', '89' ] } ] }, { dimensions: [ '(other)' ], metrics: [ { values: [ '62', '98', '7' ] } ] } ], totals: [ { values: [ '62', '98', '7' ] } ], minimums: [ { values: [ '55', '14', '3' ] } ], maximums: [ { values: [ '62', '98', '7' ] } ] } } ];
	global.console.log( data2 );
```

LegacyDashboardAcquisitionPieChart:
from:
```
	const processedData = extractAnalyticsDataForPieChart( data, { keyColumnIndex: 1 } );
```
to:
```
	const data2 = [ { nextPageToken: null, columnHeader: { dimensions: 'ga:channelGrouping', metricHeader: { metricHeaderEntries: [ { name: 'Sessions', type: 'INTEGER' }, { name: 'Users', type: 'INTEGER' }, { name: 'New Users', type: 'INTEGER' } ] } }, data: { dataLastRefreshed: null, isDataGolden: null, rowCount: 4, samplesReadCounts: null, samplingSpaceSizes: null, rows: [ { dimensions: [ 'Organic Search' ], metrics: [ { values: [ '55', '14', '3' ] } ] }, { dimensions: [ 'Referral' ], metrics: [ { values: [ '13', '17', '39' ] } ] }, { dimensions: [ 'Direct' ], metrics: [ { values: [ '10', '73', '89' ] } ] }, { dimensions: [ '(other)' ], metrics: [ { values: [ '62', '98', '7' ] } ] } ], totals: [ { values: [ '62', '98', '7' ] } ], minimums: [ { values: [ '55', '14', '3' ] } ], maximums: [ { values: [ '62', '98', '7' ] } ] } } ];
	const processedData = extractAnalyticsDataForPieChart( data2, { keyColumnIndex: 1 } );
```

## Changelog entry

* Migrate Analytics module page Top Acquisition Channels widget to use Widget API.

**Comment by tofumatt** [comment]
IB ✅

**Comment by felixarntz** [comment]
@ivankruchkoff Please implement the widget header here in the same way that is done for `ModuleOverviewWidget`, using the same components that were merged in #2918.

**Comment by ivankruchkoff** [comment]
Raised a bug relating to booleans being treated as strings https://github.com/google/site-kit-wp/issues/3043

That affects this ticket as we need to add the url param to the request per legacy dashboard:
https://github.com/google/site-kit-wp/blob/713821b7a2b9f9704aa47eac7b108da4b8e011d3/assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget/index.js#L57

legacy approach:
https://github.com/google/site-kit-wp/blob/713821b7a2b9f9704aa47eac7b108da4b8e011d3/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopAcquisitionSources.js#L134

In my testing,  global._googlesitekitLegacyData.permaLink is false, which encodes a query string param &url=false, which is parsed as string false, failing this condition:
https://github.com/google/site-kit-wp/blob/713821b7a2b9f9704aa47eac7b108da4b8e011d3/includes/Modules/Analytics.php#L490

which gives us this incorrect $dimension_filter_clause here https://github.com/google/site-kit-wp/blob/713821b7a2b9f9704aa47eac7b108da4b8e011d3/includes/Modules/Analytics.php#L979

```json
                {
                    "operator": null, 
                    "filters": [
                        {
                            "caseSensitive": null, 
                            "dimensionName": "ga:pagePath", 
                            "expressions": [
                                "http://false"
                            ], 
                            "not": null, 
                            "operator": "EXACT"
                        }
                    ]
                }
```

**Comment by ivankruchkoff** [comment]
Updated the storybook story, left the `url` param omitted in https://github.com/google/site-kit-wp/pull/3035/files#diff-f337ee195409cc0f52475e53d164fa95f0b3efbd37ffbd63069d2f4ec0113593R55  per the comment above. 

**New**
https://google.github.io/site-kit-wp/storybook/pull/3035/?path=/story/analytics-module-components-module-page-acquisition-channels-widget--loaded

**Old**
https://google.github.io/site-kit-wp/storybook/pull/3035/?path=/story/analytics-module--top-acquisition-pie-chart

**Comment by bakoorahnin** [comment]
[اداوت شرح الربح من بلوجر 2021.txt](https://github.com/google/site-kit-wp/files/6237973/2021.txt)

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

- The spacing in the columns is different between the new and legacy `Top acquisition channels` widget. 

New widget - [Screenshot](https://user-images.githubusercontent.com/73545194/113579676-36c2f680-9657-11eb-898d-98a85eeb85ad.png)

Legacy widget - [Screenshot](https://user-images.githubusercontent.com/73545194/113579733-480c0300-9657-11eb-8caf-b9ec94b3816e.png)

The `See full stats in Analytics` and `Source: Analytics links` point to the correct acquisition report but the default day is 7 days, rather than the date period selected, i.e. 28 days. Is this expected? 

![image](https://user-images.githubusercontent.com/73545194/113579924-8acddb00-9657-11eb-8417-248326067b89.png)

**Comment by ivankruchkoff** [comment]
@wpdarren to the second part of that, the acquisition report being only 7 days instead of 28 days, that's expected behaviour, and we can confirm that by ensuring that the **four** urls all point to the same place: `See full stats in Analytics` and `Source: Analytics links` in both the new widget and the old one.

**Comment by ivankruchkoff** [comment]
Got a CR to address the issues https://github.com/google/site-kit-wp/pull/3092/files?diff=split&w=1

Added screenshots with the fix applied in desktop and mobile renderings.

![after-mobile](https://user-images.githubusercontent.com/373931/113625560-eb3c2880-9615-11eb-8354-9d82faa56a6d.png)
![after-desktop](https://user-images.githubusercontent.com/373931/113625571-ed9e8280-9615-11eb-9ee7-cd42007492cd.png)

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff ! Back to you @wpdarren 👍

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Compared the two dashboards for the new and legacy `Top acquisition channels` widget.
- Checked that the `See full stats in Analytics` and `Source: Analytics` links point to the correct report. 

@ivankruchkoff I've noticed that the  `Organic Search` row is still a little squashed up, but this occurs in the latest version of Site Kit, so is not a cause of this migration. I'll submit a separate ticket for this. 

![image](https://user-images.githubusercontent.com/73545194/113717870-a354f880-971e-11eb-8d4d-159b466b1a13.png)

**Comment by tofumatt** [comment]
QA ✅

Tested the new and old versions: they look the same but the new one is rendered all widget-y 👍🏻
