### ISSUE TITLE
Explore reCaptcha integration

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#207]
Look at adding reCaptcha to Site Kit

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
Unclear what benefit this would bring to Site Kit users, no requests have come in from anyone. Closing as "maybelater".
