### ISSUE TITLE
Allow registering module setup components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2074]
Every Site Kit module's setup component should be registered via a new (optional) `setupComponent` argument which contains the component for the setup.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `registerModule` action in the `core/modules` store should receive a `setupComponent` argument that is optional and by default is set to a new `DefaultModuleSetup` component.
* The `DefaultModuleSetup` should essentially render the skeleton that all existing setup components have, but nothing more (it's for now just an "unused" fallback but it should exist):
    * It should render its output in a `<div className="googlesitekit-setup-module googlesitekit-setup-module--{moduleSlug}" />`.
    * It should include a `<h2 className="googlesitekit-heading-3 googlesitekit-setup-module__title" />` containing the module title.
    * It should include a `<form className="googlesitekit-{moduleSlug}-setup__form" onSubmit={ finishSetup } />`, containing only the `<div className="googlesitekit-setup-module__action" />` with the "Confirm & Continue" button.
* The `SetupWrapper` component should be updated to rely on registered module setup components:
    * It should be refactored to a functional component using hooks (except for relying on `global._googlesitekitLegacyData.setup.moduleToSetup` which shouldn't be refactored yet as part of this).
    * Instead of the `googlesitekit.ModuleSetup-${ slug }` filter, it should rely on the registered module setup component via the `core/modules` store.
    * The `onSettingsPage` and `isEditing` props should be removed from here.
* All Site Kit modules that currently add their settings pages via the `googlesitekit.ModuleSetup-${ slug }` should instead rely on the `registerModule` action from the `core/modules` store, passing only the `setupComponent` for now.

## Implementation Brief

* Create `DefaultModuleSetup.js` in `js/googlesitekit/modules/components` and import it to `datastore/modules.js`
* Add the implementation for `DefaultModuleSetup`details as described in the AC section.
* Add the new `setupComponent` argument to the `registerModule` action with `DefaultModuleSetup` as the default value.
* Refactor the `SetupWrapper` in `assets/js/components/setup/setup-wrapper.js` to a functional component using hooks:
    * `getSiteKitAdminURL`  ==> `select('core/site').getAdminURL()`
* Follow AC for the remainder of the items that require refactoring.
* Update the modules to register their settings pages via the data store rather than the filter in the `index.js` files at the root of each module in`assets/js/modules`

## QA Brief

* General testing (components won't load at all if not set up) for several setup flows:
  * AdSense
  * Analytics
  * Optimize
  * TagManager
* Verify no existence of `googlesitekit.ModuleSetup-${ slug }` in the codebase

## Changelog entry

* Allow registering a `setupComponent` when calling the `registerModule` action on the `core/modules` store.

**Comment by felixarntz** [comment]
IB ✅ 

@ryanwelcher Based on whether this or #1623 gets done first, one may need to integrate with the `registerModule` calls from the other.

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest develop Site Kit.

Tested the following modules:

AdSense - **Pass**
Analytics - **Pass**
Optimize - **Pass**
TagManager - **Pass**

Confirmed functionality with all modules connected:
![image](https://user-images.githubusercontent.com/57115907/98063445-eb38c200-1e04-11eb-815b-158e45d71bbc.png)

Confirmed no existence of googlesitekit.ModuleSetup-${ slug } in the source code on multiple pages
![image](https://user-images.githubusercontent.com/57115907/98063513-16231600-1e05-11eb-8532-0611a78db035.png)

Passed QA ✅

**Comment by aaemnnosttv** [comment]
@cole10up 

> Confirmed no existence of googlesitekit.ModuleSetup-${ slug } in the source code on multiple pages

Just to clarify that this is about the code base (as mentioned in the QA brief) not the page source. I've double-checked this on my end, so that's all good but something to keep in mind going forward 👍
