### ISSUE TITLE
Update WordPress dashboard widget to functional component using datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2075]
The WordPress dashboard widget for Site Kit should be refactored to become a functional component relying on the datastore. It should not rely on the Widget API at this point and not be extensible in any way. All sub-components of the dashboard should be part of "Site Kit core" (i.e. in `assets/js/components`), even those relying on certain modules (`assets/js/modules` should only contain files that are relevant for the respective module JS entrypoints, i.e. register things in Site Kit core).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `WPDashboardMain` component should be renamed to `WPDashboardApp`.
* A feature flag `widgets.wpDashboard` should be introduced. (While this won't for now use the actual Widgets API, it still underlies several similar requirements.)
* Individual components (using hooks and datastore exclusively) should be added in `assets/js/components/wp-dashboard` for all components that are added via the `googlesitekit.WPDashboardHeader` or `googlesitekit.WPDashboardModule` filter:
    * `WPDashboardUniqueVisitors` and `WPDashboardSessionDuration` (from legacy component `WPAnalyticsDashboardWidgetOverview`)
    * `WPDashboardClicks` and `WPDashboardImpressions` (from legacy component `WPSearchConsoleDashboardWidgetOverview`)
    * See the existing `Dashboard*Widget` components which will have most of the code for these already included, so a lot is available for copy-paste.
* If the above feature flag is enabled, `WPDashboardApp` should render the above new components right above the legacy `WPDashboardModules` component, in the same order in which they're displayed now.
    * Like before, the components that have their legacy versions filtered in via `googlesitekit.WPDashboardHeader` should be rendered within the `div.googlesitekit-wp-dashboard-stats` wrapper, the other ones (via `googlesitekit.WPDashboardModule`) after that container.
    * If the Analytics module is not active and connected, instead of the `WPDashboardUniqueVisitors` and `WPDashboardSessionDuration` components, the `AnalyticsInactiveCTA` should be displayed, similarly to today.
* `WPDashboardModules` should be renamed to `LegacyWPDashboardModules`.
* `WPDashboardModule` should be renamed to `LegacyWPDashboardModule`.
* `WPDashboardHeader` should be renamed to `LegacyWPDashboardHeader`.
* All files in `assets/js/components/wp-dashboard` should have names that match the component name that they export.

## Implementation Brief

* Rename `components/wp-dashboard/wp-dashboard-main.js` to `components/wp-dashboard/wp-dashboard-app.js` `WPDashboardMain` becomes `WPDashboardApp`, updating all references.

* Add a feature flag in `webpack.feature-flags.config.js` (or `feature-flags.json` if #2316 is complete), `widgets: { wpDashboard: { enabled: 'development' }`

* Create two new functional components based on `/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetOverview.js`:
`components/wp-dashboard/wp-dashboard-unique-visitors.js` `WPDashboardUniqueVisitors`
`components/wp-dashboard/wp-dashboard-session-duration.js` `WPDashboardSessionDuration`

The first component (WPDashboardUniqueVisitors) is responsible for: https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetOverview.js#L106-L112

The second (WPDashboardSessionDuration) for: https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetOverview.js#L113-L119

* Create another two new functional components based on `/js/modules/search-console/components/wp-dashboard/WPSearchConsoleDashboardWidgetOverview.js`:
`components/wp-dashboard/wp-dashboard-clicks.js` `WPDashboardClicks`
`components/wp-dashboard/wp-dashboard-impressions.js` `WPDashboardImpressions`

The first component (WPDashboardClicks) is responsible for:  https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/modules/search-console/components/wp-dashboard/WPSearchConsoleDashboardWidgetOverview.js#L69-L75
 
The second (WPDashboardImpressions) for: https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/modules/search-console/components/wp-dashboard/WPSearchConsoleDashboardWidgetOverview.js#L62-L68

* In WPDashboardApp (that we renamed at the start), use our feature flag from above to render the Dashboard components (for reference how we check feature flags: https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/components/dashboard/dashboard-app.js#L70 , how we check if a module is active: https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/googlesitekit/modules/datastore/modules.js#L468  and how we check if a module is connected https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/googlesitekit/modules/datastore/modules.js#L498 )

Part 1)
Add this rendering with a `feature flag test` just above the closing `<div/>` in https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/components/wp-dashboard/wp-dashboard-main.js#L46
```js
        if ( isModuleActive( 'analytics' ) && isModuleConnected( 'analytics' ) ) {
            <WPDashboardUniqueVisitors />
            <WPDashboardSessionDuration /> 
        } else {
            <AnalyticsInactiveCTA />
        }
```

Part 2) Add this rendering with a `feature flag test` just above `<WPDashboardModules />` in https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/components/wp-dashboard/wp-dashboard-main.js#L47
```js        
    <WPDashboardImpressions />
    <WPDashboardClicks />

```

* Rename:

* From `components/wp-dashboard/wp-dashboard-modules.js` `class WPDashboardModules` 
* To `components/wp-dashboard/legacy-wp-dashboard-modules.js` `class LegacyWPDashboardModules` 
* From `components/wp-dashboard/wp-dashboard-module.js` `class WPDashboardModule` 
* To `components/wp-dashboard/legacy-wp-dashboard-module.js` `class LegacyWPDashboardModule` 
* From `components/wp-dashboard/wp-dashboard-header.js` `class WPDashboardHeader` 
* To `components/wp-dashboard/legacy-wp-dashboard-header.js` `class LegacyWPDashboardHeader` 

## QA Brief

In the WP Dashboard, the Site Kit widget's Stats must be rendered twice, once by the newly created components and again by the legacy components. They should be visually equal, except that for now only the old version (the one at the bottom) includes the "Top content over the last 28 days" table.
This must happen only in a **development** build, controlled by the `widgets.wpDashboard` feature flag. It needs to be tested in two states, with Analytics active and with Analytics inactive.

## Changelog entry

* Update the plugin's WordPress dashboard widget to rely on functional hook-based components using the datastore.

**Comment by felixarntz** [comment]
@ivankruchkoff IB mostly LGTM, just a few points of feedback:
* The new components that are gonna be created for this need to also use the component name as file name. Maybe this wasn't entirely clear from the ACs, but the even though they use Search Console and Analytics APIs, they should be within `assets/js/components/wp-dashboard` too, so they should underly the same naming principles. In other words, while the old versions of these files are within the module-specific directory, the new ones shouldn't be since they're part of the "core" Site Kit code.
* One other detail I overlooked myself in the ACs: We need to check whether the Analytics module is `active` _and_ `connected`. Checking only whether it's active won't be sufficient as we'd re-introduce erroring API requests like in #2358.

**Comment by ivankruchkoff** [comment]
> @ivankruchkoff IB mostly LGTM, just a few points of feedback:
> 
> * The new components that are gonna be created for this need to also use the component name as file name. Maybe this wasn't entirely clear from the ACs, but the even though they use Search Console and Analytics APIs, they should be within `assets/js/components/wp-dashboard` too, so they should underly the same naming principles. In other words, while the old versions of these files are within the module-specific directory, the new ones shouldn't be since they're part of the "core" Site Kit code.

In the IB, I have the components in the assets/js/components/wp-dashboard folder:

> components/wp-dashboard/wp-dashboard-unique-visitors.js WPDashboardUniqueVisitors
> components/wp-dashboard/wp-dashboard-session-duration.js WPDashboardSessionDuration

So filename is `assets/js/components/wp-dashboard/wp-dashboard-unique-visitors.js`, function is `WPDashboardUniqueVisitors`

> * One other detail I overlooked myself in the ACs: We need to check whether the Analytics module is `active` _and_ `connected`. Checking only whether it's active won't be sufficient as we'd re-introduce erroring API requests like in #2358.

Updated with pseudo code for isModuleConnected call and a reference to isModuleConnected selector.

**Comment by felixarntz** [comment]
@ivankruchkoff Oh I see, `assets/js/components/wp-dashboard` is the correct location. The IB is referring to `components/wp-dashboard`, so I wasn't sure whether you were meaning `assets/js/components/wp-dashboard` or `assets/js/modules/*/components/wp-dashboard`, that's why I left that comment.

In this case, IB ✅

**Comment by tofumatt** [comment]
Unclear to me why the `ReportTable` component is blocking this issue from being implemented, as from what I can see there's no mention of it in use by this component (or even any sub-components). Is it alright to remove that dependency to unblock this issue?

**Comment by aaemnnosttv** [comment]
@felixarntz [one question for you here](https://github.com/google/site-kit-wp/pull/2482#pullrequestreview-552349874), otherwise this should be good to go.

**Comment by wpdarren** [comment]
### QA Update: ❌ Fail 

@aaemnnosttv @kostyalmm 

- On Development build. When Google Analytics is activated. Within the Search Funnel Analytics stats, the graphs look slightly different but the stats are the same. I have highlighted this in the screenshots -  [Top](https://user-images.githubusercontent.com/73545194/104319978-ab850980-551c-11eb-837c-21cd45a25b9d.png) and [Bottom](https://user-images.githubusercontent.com/73545194/104320003-b50e7180-551c-11eb-98c5-349c4df3e321.png)
- For clarification. In the QA brief it mentions `"Top content over the last 28 days" table.` Is this relating to the 
`Most popular content` module? If so, this appears on top and bottom of the page. The brief suggestions that it should only be at the bottom. I couldn't see any modules with this title within the dashboard. 

**Verified:**

- When on the develop branch but not on development build, the modules are not duplicated in the dashboard.
- On Development build. When Google Analytics is deactivated the dashboard looks the same between the top and bottom modules.

**Comment by eugene-manuilov** [comment]
@wpdarren looks like you are referring to the site kit dashboard which is located at the `/wp-admin/admin.php?page=googlesitekit-dashboard` URL. However, this ticket is intended for the WordPress dashboard page located at the `/wp-admin/` URL. There is the `Site Kit Summary` widget that displays some data and expected to be changed.

**Comment by wpdarren** [comment]
@eugene-manuilov ahhh that's a facepalm moment.  Thank you. I'll retest this.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- When on the develop branch but not on development build, the modules are not duplicated in the WP dashboard.
- On Development build. When Google Analytics is deactivated the WP dashboard looks the same. - [Screenshot](https://user-images.githubusercontent.com/73545194/104454936-8dcda800-55e1-11eb-8d85-3a26b5a43781.png)
- On Development build. When Google Analytics is activated. The Site Kit widget's Stats are rendered twice and visually equal. - [Screenshot](https://user-images.githubusercontent.com/73545194/104454442-d33da580-55e0-11eb-9264-a907d6ce8dff.png)
- When on the develop branch but not on development build, the modules are not duplicated in the dashboard. - [Screenshot](https://user-images.githubusercontent.com/73545194/104455557-6d521d80-55e2-11eb-81e7-6527d54bbe19.png)
