### ISSUE TITLE
Update admin bar menu to functional component using datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2076]
The admin bar menu for Site Kit should be refactored to become a functional component relying on the datastore. It should not rely on the Widget API at this point and not be extensible in any way. All sub-components of the admin bar menu should be part of "Site Kit core" (i.e. in `assets/js/components`), even those relying on certain modules (`assets/js/modules` should only contain files that are relevant for the respective module JS entrypoints, i.e. register things in Site Kit core).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A feature flag `widgets.adminBar` should be introduced. (While this won't for now use the actual Widgets API, it still underlies several similar requirements.)
* Individual components (using hooks and datastore exclusively) should be added in `assets/js/components/adminbar` for all components that are added via the `googlesitekit.AdminbarModules` filter:
    * `AdminBarUniqueVisitors` and `AdminBarSessions` (from legacy component `AnalyticsAdminbarWidgetOverview`)
    * `AdminBarClicks` and `AdminBarImpressions` (from legacy component `SearchConsoleAdminbarWidgetOverview`)
    * See the existing `Dashboard*Widget` components which will have most of the code for these already included, so a lot is available for copy-paste.
* If the above feature flag is enabled, `AdminBarApp` should render the above new components right above the legacy `AdminBarModules` component, in the same order in which they're displayed now.
    * If the Analytics module is not active, instead of the `AdminBarUniqueVisitors` and `AdminBarSessions` components, the `AnalyticsInactiveCTA` should be displayed, similarly to today.
* `AdminBarModules` should be renamed to `LegacyAdminBarModules`.
* All files in `assets/js/components/adminbar` should have names that match the component name that they export.

## Implementation Brief

* Add a feature flag in `feature-flags.json` `widgets: { adminBar: { enabled: 'development' }`

* Create four new components:
* `AdminBarUniqueVisitors` `assets/js/components/adminbar/AdminBarUniqueVisitors.js` code should be a functional component based on https://github.com/google/site-kit-wp/blob/39a79205909d539f2cf2b7bcbfc07d2cce90f10f/assets/js/modules/analytics/components/adminbar/AnalyticsAdminbarWidgetOverview.js#L95-L107

* `AdminBarSessions` `assets/js/components/adminbar/AdminBarSessions.js` code should be a functional component based on https://github.com/google/site-kit-wp/blob/39a79205909d539f2cf2b7bcbfc07d2cce90f10f/assets/js/modules/analytics/components/adminbar/AnalyticsAdminbarWidgetOverview.js#L108-L120

* `AdminBarClicks` `assets/js/components/adminbar/AdminBarClicks.js` code should be a functional component based on https://github.com/google/site-kit-wp/blob/39a79205909d539f2cf2b7bcbfc07d2cce90f10f/assets/js/modules/search-console/components/adminbar/SearchConsoleAdminbarWidgetOverview.js#L65-L77 

* `AdminBarImpressions` `assets/js/components/adminbar/AdminBarImpressions.js` code should be a functional component based on https://github.com/google/site-kit-wp/blob/39a79205909d539f2cf2b7bcbfc07d2cce90f10f/assets/js/modules/search-console/components/adminbar/SearchConsoleAdminbarWidgetOverview.js#L52-L64 

Just before rendering `AdminBarModules` https://github.com/google/site-kit-wp/blob/39a79205909d539f2cf2b7bcbfc07d2cce90f10f/assets/js/components/adminbar/AdminBarApp.js#L78 we will render the new `AdminBarUniqueVisitors` and `AdminBarSessions` with a fallback to `AnalyticsInactiveCTA` if Analytics module is neither active nor connected. Followed by `AdminBarImpressions` and `AdminBarClicks` before `AdminBarModules` (which will be renamed to `LegacyAdminBarModules`)

```js
if ( featureFlagTest ) {
    if ( moduleActiveAndConnected('analytics')) {
        <AdminBarUniqueVisitors />
        <AdminBarSessions />
    } else {
        <AnalyticsInactiveCTA />
    }

    <AdminBarImpressions />
    <AdminBarClicks />
}
<LegacyAdminBarModules />
```

Reference for an existing `featureFlag` test ( reference: https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/components/dashboard/dashboard-app.js#L70 )
Reference for checking if a module is active: https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/googlesitekit/modules/datastore/modules.js#L468  Reference for checking if a module is connected https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/assets/js/googlesitekit/modules/datastore/modules.js#L498 )

* Finally make sure all tests pass.

## QA Brief
* Navigate to a page on the front end, after logging in as admin.
* Make sure you have the admin bar displayed on a page where you have some analytics and search data.
* Upon hovering the "Site Kit" menu in the admin bar, the following data should be displayed:
	- Total Users
	- Total Sessions
	- Total Impressions
	- Total Clicks
* Disconnect the `Analytics` module and visit the page on the front end again.
* Instead of "Total Users" and "Total Sessions" being displayed, there will be a CTA to prompt the user to setup Analytics.

## Changelog entry

* Update the plugin's admin bar menu to rely on functional hook-based components using the datastore.

**Comment by kostyalmm** [comment]
@felixarntz The AC seems to be quite outdated. Can you please update it accordingly?
Moving this to AC and assigning it to you. Please assign the task to me once you are done so that I can work on the IB.

**Comment by felixarntz** [comment]
@kostyalmm Maybe I'm missing something, where specifically do you think the ACs are outdated? Can you clarify?

**Comment by kostyalmm** [comment]
As mentioned in the AC, we need to add a `AdminBarApp` component, right? But it is already [there](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/adminbar/AdminBarApp.js) (added 20 days ago)
I think the AC will change with that.

**Comment by felixarntz** [comment]
@kostyalmm Thanks for clarifying, makes sense. I've updated the ACs, the only change necessary though was to remove the first bullet point about introducing that component.

**Comment by ivankruchkoff** [comment]
@felixarntz we don't have a corresponding `SearchConsoleInactiveCTA`  as a fallback for `AdminBarClicks` and `AdminBarImpressions` the way we do with `AnalyticsInactiveCTA`. So we're always rendering those components?

**Comment by felixarntz** [comment]
@ivankruchkoff Yes, Search Console is a required module in Site Kit, so it's not possible to use the plugin without it. Therefore we don't have any CTAs for Search Console.

**Comment by felixarntz** [comment]
IB ✅

**Comment by asvinb** [comment]
@aaemnnosttv I've noticed that the data returned is different from what the legacy components are returning. Is it something which is expected because we are now using the `startDate` and `endDate` instead of `dateRange` ?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Verified: When Analytics module is disconnected and you visit the page on the front end, instead of "Total Users" and "Total Sessions" being displayed, there will be a CTA to prompt the user to setup Analytics.  

![image](https://user-images.githubusercontent.com/73545194/103914613-0e555a00-5145-11eb-9383-4d96bb08d3f7.png)
