### ISSUE TITLE
Switch module pages to use Widget API in production

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2077]
The Search Console module page should, once all widgets have been migrated to use the Widget API, been updated to use the new UI in production. All legacy widget components, as well as any actions or filters on that page in JavaScript, should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `widgets.moduleScreens` feature flag should be removed.
    * Everything that was previously only used with that flag active should now be unconditionally active.
    * Everything that was previously not used with that flag active should now be entirely removed.
* The `LegacyModuleApp` component and all usage should be removed.
* All usages of the `googlesitekit.ModuleApp-*` JS filter (including the components that are only used in conjunction with that filter) should be removed. These are mostly some components within `assets/js/modules/*/components/dashboard`.
* Any now irrelevant Storybook coverage based on this legacy architecture should also be removed. No replacements need to be implemented as part of this issue. If any of these stories is part of VRT, those should be removed as well. As part of writing the IB, please check which stories are now no longer relevant.

## Implementation Brief
* Update `feature-flags.json` to remove the `widgets.moduleScreens` feature flag.
* Using `assets/js/components/module/ModuleApp.js`,
	* Remove references to `widgets.moduleScreens`
		* `WidgetContextRenderer` should be rendered unconditionally.
		* Remove the `LegacyModuleApp` component and delete corresponding JS file.
* Using `assets/js/modules/adsense/index.legacy.js`,
	* Remove the `googlesitekit.ModuleApp-` hook and the corresponding component file (`AdSenseDashboardWidget`) and all `Legacy-*` components within it.
* Using `assets/js/modules/analytics/index.legacy.js`,
	* Remove the `googlesitekit.ModuleApp-` hook and the corresponding component file (`LegacyAnalyticsDashboardWidget`).
* Remove `assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidget.js` and all `Legacy-*` components within it.
* Using `assets/js/modules/search-console/index.legacy.js`,
	* * Remove the `googlesitekit.ModuleApp-` hook and the corresponding component file (`GoogleSitekitSearchConsoleDashboardWidget`).
* Remove `assets/js/modules/search-console/components/dashboard/GoogleSitekitSearchConsoleDashboardWidget.js` and all `Legacy-*` components within it except for the `LegacyDashboardWidgetPopularKeywordsTable` component which is used by `assets/js/modules/search-console/components/dashboard-details/DashboardDetailsWidgetKeywordsTable.js`.
* Review references to deleted files and update accordingly.
* Review the stories in the files below to remove stories which use the deleted components:
	* `stories/module-analytics.stories.js`
	* `stories/module-adsense.stories.js`
	* `stories/module-search-console.stories.js`

### Test Coverage
* Failing tests, if any, should be updated to cater for deleted legacy components.

### Visual Regression Changes
* Expected changes to tests which are using the deleted components.

## QA Brief
Verify that:
* all module pages are using the Widget API
* the `widgets.moduleScreens` feature flag has been removed (i.e. isn't included in the list in the Tester plugin)
* additional points mentioned in the AC have been met (e.g.  there should be no instance of the`googlesitekit.ModuleApp-*` JS filter in the codebase, legacy module page stories should have been removed, etc.)

## Changelog entry

* Update module page dashboards to use Widget API unconditionally and remove legacy implementations.

**Comment by eugene-manuilov** [comment]
@asvinb it's a good start, but we don't need to delete **all** legacy components. We need to delete only those legacy components that are used on module pages and leave legacy components for dashboard and details pages.

**Comment by asvinb** [comment]
@eugene-manuilov Correct, we are not deleting all legacy components. In the IB I've mentioned to remove legacy components which are used in components which we are going to delete. For e.g `LegacyAnalyticsDashboardWidget` uses the `LegacyAnalyticsDashboardWidgetSiteStats` component. The latter is not used anywhere except in that component:
https://github.com/google/site-kit-wp/search?q=LegacyAnalyticsDashboardWidgetSiteStats
So it's safe to remove it.

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb! IB :heavy_check_mark:

**Comment by felixarntz** [comment]
I just discovered a bug #3667, which effectively blocks this issue. We need to fix that one before rolling out the new `widgets.moduleScreens` behavior to everyone.

**Comment by felixarntz** [comment]
@tofumatt @aaemnnosttv @eugene-manuilov This must not be merged until `develop` is open for 1.38.0 release issues.

**Comment by cole10up** [comment]
### **QA ✅**

Ran a series of regression tests around each module. Ensured modules are functioning properly.

No issues on my end. Sending to approval.
