### ISSUE TITLE
Initial state registered improperly for stores

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2083]
## Bug Description

When working on #2052, the tests for `createFetchStore` started failing where `state` was becoming `undefined`, simply by changing the default reducer case from `{ ...state }` to return `state`. After digging into this I found that the problem was due to how JS handles a rest spread with `undefined`.

![image](https://user-images.githubusercontent.com/1621608/93756085-2a240700-fc0d-11ea-9d40-2a1e583db5a7.png)

Because we were previously spreading `state` into a new object in the default reducer case, the `undefined` initial state was becoming an empty object.

In the test, the test fetch store is created like this, where the result of `createFetchStore` is naturally expected to be a valid store definition:

```js
storeDefinition = createFetchStore( STORE_PARAMS );
registry.registerStore( STORE_NAME, storeDefinition );
```

The store definition here is an object defined as below, the same way we do for all of our stores.

https://github.com/google/site-kit-wp/blob/937477bef14cc9ea2e39f9a59a960dd3e2dd11d9/assets/js/googlesitekit/data/create-fetch-store.js#L276-L283

This causes the store's initial state to be `undefined` initially because `registerStore` expects the initial state to be defined as [`store.initialState`](https://github.com/WordPress/gutenberg/tree/master/packages/data#initialstate) rather than `store.INITIAL_STATE`.

Instead, our stores have been receiving their initial state as a kind of side-effect of `Data.combineStores` which provides the combined initial state to the combined reducer: https://github.com/google/site-kit-wp/blob/d0b31e9f893701119947cca757f900cb9835e8a7/assets/js/googlesitekit/data/utils.js#L187-L190

This doesn't seem to affect the actual initial state for our stores that use `combineStores`, but does essentially cause lower-level utility stores to be registered incorrectly. Our store definitions should be valid and consistent at all levels. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All data store definitions should provide the initial state under the `initialState` key, not `INITIAL_STATE`

## Implementation Brief

* Update all store definitions, partials, exports, utility functions, and tests to use `initialState` instead of `INITIAL_STATE`

## QA Brief

* No behavioral changes should be observable
* All tests should pass – required for PR to be merged anyways

## Changelog entry

* Fix initial datastore state being registered incorrectly to ensure consistent initial state.

**Comment by tofumatt** [comment]
Huh, wild, thanks for catching that!

IB ✅ from me.

**Comment by felixarntz** [comment]
@aaemnnosttv How critical is that? Since #2052 is already merged, I'm wondering whether we should squeeze this into this current sprint in favor of something else.

**Comment by aaemnnosttv** [comment]
@felixarntz this has been around for quite a while so I don't think it's an emergency. It only seems to affect the lower-level stores which don't use `combineStores` before they're registered. It's probably not a large effort to address, as it's mostly just a key change, but it's possible something else may come of it so I allocated a bit more time in the estimate just to be safe.

I can put together a quick PR soon to see if there's any conflicts that need to be resolved, otherwise it should be fairly straightforward and we could potentially include it if you'd like.

**Comment by tofumatt** [comment]
QA ✅
