### ISSUE TITLE
Analytics data is not yet available, please check back later.

### ISSUE THREAD

**Issue by lsmense** [google/site-kit-wp#2085]
## Bug Description

Google Analytics has been configured for my website (https://welcome.covfel.org) through the Google Site Kit UI.  The current status is "Analytics is connected." However, the dashboard is showing Analytics data is not yet available, please check back later." This has been showing for the last 24 hours.  I can provide login details at request.

Note that Google Analytics is properly showing user statistics on analytics.google.com.

## Steps to reproduce

1. Login to the WordPress dashboard
2. Click on "Site Kit"
3. Click on Analytics

## Screenshots

![image](https://user-images.githubusercontent.com/71647888/93770947-de606600-fbea-11ea-9a77-f33648794e4f.png)

## Additional Context

 - PHP Version: 7.2.33
 - OS: Windows 10
 - Browser Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - Plugin Version 1.16.0
 - Device: Lenovo X270

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reaching out. Initial support requests can be submitted using the plugins WordPress support forum. 

If you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing your Site Health information using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) we'd be happy to assist.
