### ISSUE TITLE
Vertical Axis displays format inconsistent with tooltip

### ISSUE THREAD

**Issue by ryanwelcher** [google/site-kit-wp#2095]
The vertical axis for in `AnalyticsDashboardWidgetSiteStats` displays standard numbers which is inconsistent with what it being displayed in the tooltip.

The most obvious example is the Session Duration. The tool tip displays `mm:ss` while the vertical axis displays seconds:
![sitekit_session_duraction.png](https://images.zenhubusercontent.com/5e74b5396e1fdc722577f6d3/bf8244df-34c0-4807-a9a4-a47bdd67c382)
It may also be an improvement to add a % sign after the label for Bounce Rate as well.
![sitekit_bounce_rate.png](https://images.zenhubusercontent.com/5e74b5396e1fdc722577f6d3/59cc3c23-0bd9-4119-9852-76759f9218d0)
This may be a limitation of the [API](https://developers.google.com/chart/interactive/docs/customizing_axes#number-formats), but further discovery is required to determine if we can format the labels appropriately.

Discovered during QA for #2008.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics graph on the Analytics module page should have its y-axis labels number formatting based on the values that the graph displays (relying on `numFmt` if possible):
    * For the "Bounce Rate" the values should be formatted as percentages.
    * For the "Session Duration" the values should be formatted as durations. It would be great if we could display these labels in multitudes of minutes instead of seconds when applicable (e.g. "1m", "2m", instead of "50", "100", the latter of which do not correspond to a full minute).

## Implementation Brief

We currently show Session Duration in the graph as seconds, however charts can take a 'timeofday', https://developers.google.com/chart/interactive/docs/datesandtimes#working-with-timeofday which takes an array of integers of the following format:
`[HOURS, MINUTES, SECONDS, MILLIS]`

This function is used for formatting the data:
https://github.com/google/site-kit-wp/blob/fa3df25c8c6cb11ab600262174c7fbfbcbaf7692/assets/js/modules/analytics/util/index.js#L164

and it is called from here to render the chart https://github.com/google/site-kit-wp/blob/fa3df25c8c6cb11ab600262174c7fbfbcbaf7692/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetSiteStats.js#L121

For Sesson Duration data, we need to change it from 
`{"type":"number","label":"Session Duration"}`
to
`{"type":"timeofday","label":"Session Duration"}`
The session duration should be changed from a float in a string to an array, so from 196.385 to `[0,3,16,385]` (0 hours, 3 mins, 16s, 385 millis), see the screenshot in the comment for how this will look after it's updated: https://github.com/google/site-kit-wp/issues/2095#issuecomment-774572066

To add a percentage sign % after the label bounce rate, update the label:
https://github.com/google/site-kit-wp/blob/fa3df25c8c6cb11ab600262174c7fbfbcbaf7692/assets/js/modules/analytics/util/index.js#L204

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief
* Visit the "Analytics" main dashboard.
* Click on the "Bounce Rate" tab.
* There should be the **%** sign after the "Bounce Rate" label.
* Click on the "Session Duration" tab.
* The y-axis values of the chart should be in the following format: hh:mm:ss

## Changelog entry

* Fix formatting of y-axis values for Bounce Rate and Session Duration on Analytics overview chart.

**Comment by ivankruchkoff** [comment]
Adding some quick screenshot examples:

**Current approach: seconds only**
<img width="1086" alt="seconds-only" src="https://user-images.githubusercontent.com/373931/107133550-42d04900-689e-11eb-8b37-0ec05129fd5e.png">

**Timeofday as hh:mm:ss**
<img width="1103" alt="hh-mm-ss" src="https://user-images.githubusercontent.com/373931/107133553-57acdc80-689e-11eb-9f15-1e51c59a2b22.png">


**Timeofday as hh:mm (everything is 60x multiplied)**
<img width="1092" alt="Screen Shot 2021-02-06 at 5 21 52 PM" src="https://user-images.githubusercontent.com/373931/107133699-d48c8600-689f-11eb-98f9-2d5a40c883ad.png">

**Comment by ivankruchkoff** [comment]
To elaborate on formatting, https://developers.google.com/chart/interactive/docs/reference#formatters, we may be able to do vAxis.format for `ss` on durations that are in seconds, `mm:ss` for durations less than an hour, which will allow the second case in our screenshots while not having `00:00:XX` for sites with short durations.

**Comment by felixarntz** [comment]
@ivankruchkoff I think it makes most sense here to be consistent with Analytics and always use the `hh:mm:ss` format - can you clarify that in the IB? Other than that, this should be good to go!

**Comment by felixarntz** [comment]
IB ✅ 

@ivankruchkoff Can you add an estimate? That's still missing.

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@asvinb on smaller screens the y-axis values are not displaying for the Session Duration.  It's possible that this is expected due to the amount of characters, but would like to check. 

**Verified:**

- On the "Bounce Rate" tab, there is a % sign after the "Bounce Rate" label.

![image](https://user-images.githubusercontent.com/73545194/108208803-79db1000-7164-11eb-821f-ba2fec9c22b8.png)

- On the "Session Duration" tab, the y-axis values of the chart is in the following format: hh:mm:ss.

![image](https://user-images.githubusercontent.com/73545194/108208803-79db1000-7164-11eb-821f-ba2fec9c22b8.png)

**Comment by asvinb** [comment]
@wpdarren I would say, let's create another ticket for that. Ideally, we can reduce the chart area on small screens and then resize it on large screens but I think it's worth a ticket on its own. What do you think @aaemnnosttv ?

**Comment by aaemnnosttv** [comment]
@asvinb I would say it's probably worth addressing here if it's not too much effort as we shouldn't introduce changes that have detrimental side effects, but I'm sure what the best solution is here. Can you show in a screenshot what it would look like if we adjusted the sizing in mobile like you said?

**Comment by asvinb** [comment]
@aaemnnosttv Here is how the chart will look like if we set the `chartArea` to :
`
chartArea: {
				height: '80%',
				width: '100%',
				left: 60,
			},
`
![image](https://user-images.githubusercontent.com/31818/108515806-ed089180-72de-11eb-969f-c668ec7a229b.png)
and desktop:
![image](https://user-images.githubusercontent.com/31818/108516029-2e993c80-72df-11eb-9aca-520fe2fb44a8.png)

What do you think?

**Comment by aaemnnosttv** [comment]
@asvinb it looks good to me, although your first screenshot looks a bit overly-squished but I think this is due to the extra padding added in storybook.

> For whatever reason, the y axis is only displaying `hh:mm` instead of `hh:mm:ss` but it looks like this:

So you mean `00:03` is 3 min there? On larger viewports is it showing seconds as well? If so, I'm guessing it's an optimization the chart is doing.

**Comment by asvinb** [comment]
@aaemnnosttv Yes, the first screenshot is because of the padding in storybook. As for the format, yes, 00:03 means 3 mins here, but it should display hh:mm:ss but maybe as you said, the chart is doing some optimization. I issued a new PR to fix the y-axis: https://github.com/google/site-kit-wp/pull/2855
Can you review?
Thanks!
