### ISSUE TITLE
Merge Analytics & Tag Manager decoupling branch into `develop`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2096]
The `feature/ga-gtm-separation` branch should be merged into `develop`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tag Manager should no longer depend on Analytics being active. See #1380.
* There should be Analytics-related guidance in the Tag Manager setup flow if an Analytics property is found in the Tag Manager container. See #1381.
* There should be Tag Manager-related guidance in the Analytics setup flow if Tag Manager is active and an Analytics property is found in the Tag Manager container. See #1382.
* Tag Manager should still not be included in the list of modules to activate in the "Congratulations" notifications because it is a more advanced module. See #2025.

## Implementation Brief

* Open PR from `feature/ga-gtm-separation` against `develop`.

## QA Brief

Generally already covered via dependency issues #1380, #1381, #1382, #2025. Still, check these flows at a high level:
* Set up (in Tag Manager frontend) a container that contains an Analytics tag, with the same Analytics property ID you intend to use for Site Kit.
* Test 1: Activate Tag Manager before Analytics. Select the container with the Analytics tag. See prompt informing about Analytics, and continue to Analytics setup. You should get redirected to OAuth consent screen and afterwards the Analytics setup. There, the property that you have in your Tag Manager container should be force-selected. Complete setup.
    * Afterwards, go to Analytics settings and ensure it says "Snippet is not inserted" (because Tag Manager handles it).
* Test 2: Activate Analytics before Tag Manager. Select the property which you have set up in your Tag Manager container. Complete setup. Then, activate Tag Manager. Select the container with the Analytics tag. You should see a notice informing that you already have an Analytics tag setup and that it matches, so that the plugin will use Tag Manager instead of the Analytics snippet from now on. Complete setup.
    * Same as in test 1: Afterwards, go to Analytics settings and ensure it says "Snippet is not inserted" (because Tag Manager handles it).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Setting the estimate to 7 mostly due to QA (even though the individual pieces were previously QAd already). Code review should be minimal because all of this has already been reviewed and merged into the feature branch.

**Comment by aaemnnosttv** [comment]
IB ✅  😄

**Comment by cole10up** [comment]
This was tested as part if https://github.com/google/site-kit-wp/issues/1382 and https://github.com/google/site-kit-wp/issues/1381

Shifting to approval
