### ISSUE TITLE
Analytics DashboardTopEarningPagesWidget shows data error when restricted metrics are requested

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2098]
## Bug Description

In the QA for #1901, @cole10up found that the new `DashboardTopEarningPagesWidget` component displayed a data error with restricted metrics, where the legacy version of the same component correctly showed the "Link Analytics with AdSense" CTA. The data error shouldn't be shown here because the error is expected in this case, and is how we detect if the two services are linked.

## Steps to reproduce

1. Set up Site Kit using a development build
1. Set up AdSense
1. Set up Analytics using an account/property that is not linked with the AdSense account used
1. Navigate to the Site Kit dashboard
1. Notice the widget-based component shows a data error
1. Notice the legacy component shows the blue "Link Analytics with AdSense" CTA

## Screenshots

Widget-based component
![image](https://user-images.githubusercontent.com/57115907/94110278-3d92c600-fdf7-11ea-85c1-1d4369abc6c8.png)

Legacy component
![image](https://user-images.githubusercontent.com/57115907/94110313-4a171e80-fdf7-11ea-9e0c-3ca42e22c63f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DashboardTopEarningPagesWidget` should only show a data error component if the error is not a restricted metrics error for AdSense metrics specifically

## Implementation Brief

* Add a new `isRestrictedMetricsError( error, matchMetric )` utility function
    - Returns `true` if `error` is a `400` error for `Restricted metric(s) [...]`, otherwise `false`
    - Optionally accepts a `matchMetric` parameter for matching against specific metrics (in this case `ga:adsense`)
* In `DashboardTopEarningPagesWidget`, move the `isAdSenseLinked` conditional before the `error` conditional  
_Was originally designed to use the new `isRestrictedMetricsError` utility instead, but this is simpler_
* Update the existing logic used for detecting restricted adsense metrics in `analytics/datastore/report.js` to use the new utility
* Merge #2097 

## QA Brief

* Follow the steps to reproduce above
* Both components should show the blue "Link Analytics with AdSense" CTA

## Changelog entry

* Fix new AdSense Top Earning Pages widget displaying error instead of CTA to link AdSense and Analytics.

**Comment by felixarntz** [comment]
@aaemnnosttv @cole10up Since this only affects the new widget which is not in production, I think we can just add this to next release.

**Comment by felixarntz** [comment]
@aaemnnosttv Regarding the IB, mostly LGTM. However, I also think maybe we should change the order of the error clause and the clause whether AdSense and Analytics aren't linked? If they aren't linked, it doesn't even matter if there is an API error.

**Comment by aaemnnosttv** [comment]
> maybe we should change the order of the error clause and the clause whether AdSense and Analytics aren't linked? If they aren't linked, it doesn't even matter if there is an API error.

That works for me. I realize now that the resolver where we conditionally set `adsenseLinked` in a failure would have run by the time the lower conditionals run due to the `loading` guard which means its value will be up-to-date and the utility is unnecessary in this component for now. I still think it's a good addition and clarifies the use in the resolver for `getReport` though. I'll update the IB and PR 👍

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest development build. 

Setup Adsense:
![image](https://user-images.githubusercontent.com/57115907/95555127-2c84b000-09c6-11eb-97e5-ae75ff932520.png)

Setup Analytics account not linked to the Adsense account:
![image](https://user-images.githubusercontent.com/57115907/95555031-052de300-09c6-11eb-89cc-2f6172890180.png)

Confirmed issue no longer displays. Confirmed current modules function properly

Passed QA ✅
