### ISSUE TITLE
Compatibility with PHP 7.x.x.

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#21]
**FILE: google-site-kit/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP/Stream.php**

> ----------------------------------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
> ----------------------------------------------------------------------------------------------------------------------------
>  182 | WARNING | Global with anything other than bare variables is discouraged since PHP 7.0. Found ${$host}
> ----------------------------------------------------------------------------------------------------------------------------

**FILE: google-site-kit/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php**

> ----------------------------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
> ----------------------------------------------------------------------------------------------------------------------
>  10 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
> ----------------------------------------------------------------------------------------------------------------------
> 

**FILE: google-site-kit/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php**

> ----------------------------------------------------------------------------------------------------------------------------------------------------------
> FOUND 45 ERRORS AND 1 WARNING AFFECTING 26 LINES
> ----------------------------------------------------------------------------------------------------------------------------------------------------------
>   792 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>   792 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>   825 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>   825 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>   828 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>   828 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>   833 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>   833 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>   842 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>   842 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>   852 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>   852 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>   855 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>   855 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1132 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1132 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1160 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1160 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1165 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1165 | ERROR   | Function mcrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1174 | ERROR   | Function mdecrypt_generic() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1177 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1177 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1659 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1659 | ERROR   | Function mcrypt_list_algorithms() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1738 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1738 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1739 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1739 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1744 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1744 | ERROR   | Function mcrypt_module_close() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1851 | ERROR   | The constant "MCRYPT_MODE_ECB" is deprecated since PHP 7.1 and removed since PHP 7.2
>  1852 | ERROR   | The constant "MCRYPT_MODE_CBC" is deprecated since PHP 7.1 and removed since PHP 7.2
>  1854 | ERROR   | The constant "MCRYPT_MODE_CFB" is deprecated since PHP 7.1 and removed since PHP 7.2
>  1855 | ERROR   | The constant "MCRYPT_MODE_NOFB" is deprecated since PHP 7.1 and removed since PHP 7.2
>  1856 | ERROR   | The constant "MCRYPT_MODE_STREAM" is deprecated since PHP 7.1 and removed since PHP 7.2
>  1859 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1859 | ERROR   | Function mcrypt_module_open() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1860 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1860 | ERROR   | Function mcrypt_module_open() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1866 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1866 | ERROR   | Function mcrypt_module_open() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  1866 | ERROR   | The constant "MCRYPT_MODE_ECB" is deprecated since PHP 7.1 and removed since PHP 7.2
>  1871 | ERROR   | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
>  1871 | ERROR   | Function mcrypt_generic_init() is deprecated since PHP 7.1 and removed since PHP 7.2; Use OpenSSL instead
>  2610 | WARNING | Function create_function() is deprecated since PHP 7.2; Use an anonymous function instead
> ----------------------------------------------------------------------------------------------------------------------------------------------------------

**FILE: google-site-kit/vendor/phpseclib/phpseclib/phpseclib/Crypt/Random.php**

-------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 2 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------------
  69 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
  69 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 108 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and removed since PHP 7.2; Use openssl (preferred) or pecl/mcrypt once available instead
 108 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1 and removed since PHP 7.2; Use random_bytes() or OpenSSL instead
 108 | ERROR | The constant "MCRYPT_DEV_URANDOM" is deprecated since PHP 7.1 and removed since PHP 7.2
-------------------------------------------------------------------------------------------------------------------------------------------------------

**FILE: google-site-kit/vendor/symfony/yaml/Parser.php**

> --------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
> --------------------------------------------------------------------------------------------------
>  72 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
> --------------------------------------------------------------------------------------------------

**FILE: google-site-kit/vendor/symfony/yaml/Inline.php**

> --------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
> --------------------------------------------------------------------------------------------------
>  55 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
> --------------------------------------------------------------------------------------------------
> 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by jamesozzie** [comment]
@sviluppomania Thanks for the info, I have filed this as a bug now for further investigation

**Comment by sviluppomania** [comment]
Hello @jamesozzie  ,
as you can see from my report, there are many compatibility errors with PHP 7 and higher versions.
As you can still see, the directory that leads to the file and all the errors are in bold.

A question:
Why didn't you consider sites that use PHP 7?

**Comment by felixarntz** [comment]
@sviluppomania Thanks for the follow-up. The violations are caused by a third-party dependency we don't have control over. I will look into whether we can replace it with an alternative or solve the problems upstream.

**Comment by terrafrost** [comment]
phpseclib author here. If this library isn't being used then it shouldn't be a dependency, I get it, BUT that doesn't change the fact that all but one of the "issues" identified by this static analysis tool are completely 110% bogus.

- if mbstring is installed and mbstring.func_overload is set such that functions like `strlen` / `substr` / etc would be overloaded phpseclib throws a "_Overloading of string functions using mbstring.func_overload is not supported by phpseclib_" exception. See https://github.com/phpseclib/phpseclib/issues/1239

- mcrypt is only used IF IT'S AVAILABLE for speed. OpenSSL is preferentially used if it's available BUT if it isn't then mcrypt is used because a pure-PHP implementation cannot hope to match even mcrypt's speed. And when it is used the error suppression operator is used. See https://github.com/phpseclib/phpseclib/issues/1028

As for the one issue that isn't 100% bogus...  the `${$host}` issue...  I contend that fixing that issue would be a BC break. It's used for the SFTP stream wrapper. phpseclib 1.0 / 2.0 support `fopen('ssh2.sftp://$session/path/to/file', 'r');`. Note the single quotes. phpseclib dev-master, however, doesn't support that. [i]That[/i] supports `fopen("ssh2.sftp://$session/path/to/file", 'r');` (note the double quotes). In-so-doing, dev-master is able to emulate libssh2's SFTP stream wrapper more faithfully than the 1.0 / 2.0 branches are. Here's the PR where this was done: https://github.com/phpseclib/phpseclib/pull/787 . Now, I'll admit...  the global requirement that the 1.0 / 2.0 branch has means that that functionality can't very easily be used inside of functions because you'd have to declare `$session` in the function, as well. I may actually be willing to change this (backport the afore mentioned PR) in the 2.0 branch because (1) my suspicion is that it's not really being used by any projects and (2) if BC breaking in minor releases was completely verboten some bugs would be impossible to fix. I'm not sure I'd call this a "bug", as such, since it is working as designed, but, depending on my mood, I may be willing to be a little more flexible on some things.

If anyone can convince me that any of the issues raised brought up in this ticket are legit I will PayPal you $100 dollars. I do apologize that I can't do more but I don't have pockets nearly as deep as Google does.

**Comment by terrafrost** [comment]
I mean, seriously, phpseclib is unit tested up on Travis CI up to PHP 7.4snapshot. If these issues were legit the unit tests would be failing but they're not.
