### ISSUE TITLE
Better clarify the Source link

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#210]
During beta we found that user didn't understand the source link
The context here is that users:
1) didn't understand this was an action they could do;
2) didn't understand this leads to a more detailed subreport (thought it would take them to either the full product or to some help page)

To address this, let's:
1) make the font bigger
2) change the current "source" noun to an action verb like "See more" or "drill down"
3) mention the existence of the subreports -- e.g. "Drill down in the Analytics report/section" (what are these formally called?)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
These links now take users directly to the FE of the actual product (GA, SC). This is indicated by a relevant icon. This is no longer a valid issue.
