### ISSUE TITLE
Tracking opt-in request fails on multisite for super admins that don't belong to the site

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2103]
## Bug Description

On a regular multisite network, Site Kit can be configured per-site just like on a normal single site install.

When Site Kit is active on a sub-site on the network, the REST request used when toggling anonymous usage tracking fails with a 404 when the user is not a member of the current site. This is only possible for super admins who can access all sites across the network without being added.

## Steps to reproduce

1. Activate Site Kit on a sub-site of a multisite network
1. Log in as a super admin who is not added to the sub-site (`wp-admin/network/site-users.php`)
1. Go to the Site Kit splash page
1. Toggle tracking opt-in
1. See "Invalid user ID" error

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/94190599-fc60eb80-feb4-11ea-8c0e-9fac58721553.png)

![image](https://user-images.githubusercontent.com/1621608/94191834-ce7ca680-feb6-11ea-82bf-eaed19ecd544.png)

## Additional Context

This only seems to affect the `wp/v2/users/me` route we use for this. Other Site Kit routes seem to work fine.

The actual response from the server:

```json
{
  "code": "rest_user_invalid_id",
  "message": "Invalid user ID.",
  "data": { "status": 404 }
}
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `GET:core/user/data/tracking` datapoint in PHP which returns an object like `{ enabled: true|false }`, based on the option's value.
    * The response for this REST endpoint should be preloaded on pageload.
    * Note: `trackingEnabled` should still be included in `_googlesitekitBaseData` since it's needed for the general admin tracking logic. Since we don't load all our JS code (e.g. the datastores) on all WP admin pages (which should be kept that way), for the basic tracking we need to continue to rely on the PHP-to-JS object data.
* There should be a new `POST:core/user/data/tracking` datapoint in PHP which expects an `enabled` argument, updates the option based on it, and then returns an object like `{ enabled: true|false }`, based on the updated value.
* There should be a new JS datastore selector `isTrackingEnabled()` in the `core/user` store which relies on the `GET:core/user/data/tracking` datapoint.
* There should be a new JS datastore action `setTrackingEnabled( enabled )` in the `core/user` store which sends the data to `POST:core/user/data/tracking`.
* The `OptIn` component should be updated to rely on the new selector and action to read and write the tracking enabled state.
* The `Google\Site_Kit\Core\Util\Tracking_Consent` class should be updated to no longer override the `register` method, so that the setting is no longer exposed in the regular WP user REST API endpoints.

## Implementation Brief

* Add a new private method `get_rest_routes` to the `Tracking` class. It should return an array with a new REST route instance that uses the `core/user/data/tracking` URI and the array of the following endpoints:
  * An endpoint for the `GET` method with a callback function which returns an object like `{ enabled: true|false }`, based on the user setting value that can be get using the `Tracking_Consent` class;
  * An endpoint for the `POST` method with a callback function that receives the `enabled` value from the request, saves it using the `Tracking_Consent` class, and returns the same response as the endpoint for the `GET` method.
* Add new hooks to the `Tracking::register` method:
  * A hook for the `googlesitekit_apifetch_preload_paths` filter should add the following URI to the filtered list of paths:
    ```
    '/' . REST_Routes::REST_ROOT . '/core/user/data/tracking'
    ```
  * A hook for the `googlesitekit_rest_routes` filter should merge an array received from the `get_rest_routes` method with incoming rest routes and return merged array.
* Add a new selector `isTrackingEnabled()` to the `core/user` datastore that returns the returns `TRUE` if the tracking feature is enabled;
* Add a new action `setTrackingEnabled( enabled )` to the `core/user` datastore that saves the tracking setting using the `POST:core/user/data/tracking` endpoint;
* Update the `OptIn` component to rely on the new selector and action to read and write the tracking enabled state;
* Remove the `Tracking_Consent::register` method.

### Test Coverage

* Update existing tests if any is failing due to the aforementioned changes;
* Add js tests to test new selector and action.

### Visual Regression Changes

* N/A

## QA Brief

* Set up a multisite instance and create a new site there;
* As a super admin, go to the newly created site and activate the Site Kit plugin there;
* Once the notification with the Sign-in CTA appears, click on the `Help us improve ...` checkbox and make sure that works correctly (you don't see errors);
* Once you sign in to the site kit on that site, go to the admin settings and make sure that your selection is preserved and you see the checkbox selected. Try to deselect/select it in the admin settings and make sure it saves its state correctly.

## Changelog entry

* Fix bug where tracking opt-in was not working for multisite administrators when not being a member of the site.

**Comment by felixarntz** [comment]
@eugene-manuilov IB mostly LGTM, just one thing:
> Add a new REST route to the `REST_Routes::get_routes()` method

We shouldn't add new REST routes to this centralized class, they should rather go into an area related to the feature they're related to - only some overarching routes and leftovers are still in that class which is more responsible for the REST infrastructure.

We could either add the REST route in a new method in `Core\Util\Tracking_Consent`, or we could use an entirely new class `Core\Util\REST_Tracking_Consent_Controller`, similar to what @aaemnnosttv suggested in #2648. Might be worth putting the 2 (or now 3?) tracking classes into its own namespace too, maybe `Core\Util\Tracking`.

**Comment by eugene-manuilov** [comment]
> We shouldn't add new REST routes to this centralized class ... We could either add the REST route in a new method in Core\Util\Tracking_Consent ...

Okay, got it. Updated IB to add the new route to the `Core\Util\Tracking` class.

> or we could use an entirely new class Core\Util\REST_Tracking_Consent_Controller ... Might be worth putting the 2 (or now 3?) tracking classes into its own namespace too, maybe Core\Util\Tracking.

Yeah, maybe but I think it is out of scope for this ticket. Maybe we should create a follow-up ticket?

**Comment by felixarntz** [comment]
IB ✅ 

@eugene-manuilov Can you open a follow-up issue for moving the logic into a REST controller class?

**Comment by eugene-manuilov** [comment]
> Can you open a follow-up issue for moving the logic into a REST controller class?

@felixarntz #2764 is created.

**Comment by felixarntz** [comment]
@eugene-manuilov Can you add a QA Brief please?

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Tested the opt-in toggle on and off on a multisite logged in as a super-user without being added to the site

* Requests were all successful
* Tracking opt-in/out was persisted as expected
* Tracking loads when opted-in and does not when opted-out
