### ISSUE TITLE
AdSense dashboard error when Portuguese AO90 language is selected

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2105]
## Bug Description

As mentioned in a [WordPress support topic](https://wordpress.org/support/topic/site-kit-message-data-error-in-adsense-and-missing-add-txt-code/) when the Portuguese (AO90) language is active the below dashboard error appears. No AdSense metrics are available and there's no obvious way to bypass this without switching language at present.

``Invalid value 'pt_PT_ao90'. Values must match the following regular expression: '[a-zA-Z_]'`

The below response appears in the console:

```
googlesitekit-dashbo…b0e46cfbfbb5db.js:4 WP Error in data response 
Object
code: 400
data: {status: 400, reason: "invalidParameter"}
message: "Invalid value 'pt_PT_ao90'. Values must match the following regular expression: '[a-zA-Z_]+'"
__proto__: Object
```
`
## Steps to reproduce

1. Setup AdSense on a site
2. Set Portuguese AO90 as you primary language 
3. Visit the main Site Kit or AdSense specific dashboard

## Screenshots

Main dashboard error
![image](https://user-images.githubusercontent.com/41326532/94273424-50fb7980-ff3c-11ea-8a71-501e412e91f4.png)

AdSense dashboard error

![image](https://user-images.githubusercontent.com/41326532/94273516-6ffa0b80-ff3c-11ea-9f2f-ada00c033179.png)

## Additional Context

- Ads don't appear to be impacted
- No warnings or errors appear when visiting the AdSense dashboard on the AdSense Web UI
- Previous discussion on locale settings in #1309

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Locales sent along with AdSense API requests should always be sanitized to only include the standard first two segments (e.g. `pt_PT` instead of `pt_PT_ao90`, or `de_DE` instead of `de_DE_formal`).

## Implementation Brief

While the API docs don't explicitly state the regex pattern for matching locale, https://developers.google.com/adsense/management/v1.4/reference/reports/generate, it's clear that it's facing issues with integers in the locale based on the screenshot.

There are two WordPress functions responsible for fetching locale, both of which will return `pt_PT_ao90` when it is selected:
get_locale - https://developer.wordpress.org/reference/functions/get_locale/
get_user_locale - https://developer.wordpress.org/reference/functions/get_user_locale/

We will create a new function on the `Context` class
https://github.com/google/site-kit-wp/blob/4739c5c87ea9e068b0ef0c2beda4fe79e185f9e9/includes/Context.php

`public function get_locale( $context = 'site', $format = 'default' ) {}`

This function calls one of two functions to get the locale:
$context is one of `user` which calls `get_user_locale()`, or `site` which calls `get_locale()`

$format param is responsible for transforming the value prior to returning it.
The following three values need to be supported to account for our current use cases:
`default` - returns the value as is
`language-code` -  this returns everything before the first underscore so `te` becomes `te`, `nl_NL_formal` becomes `nl`
`language-variant` - this returns everything before the second underscore, so `pt_PT_ao90` becomes `pt_PT`, `bel` becomes `bel` and `pt_BR` becomes `pt_BR`

In the following places, the calls to the `get_*_locale` functions are called and will need to be updated to use the new method:
```
Core/Assets/Assets.php:781: 'locale' => get_user_locale(),
Core/Authentication/Clients/OAuth_Client.php:644: 'hl' => get_user_locale(),
Core/Authentication/Google_Proxy.php:139: $params['hl'] = get_user_locale();
Core/Authentication/Google_Proxy.php:162: $query_args['hl'] = get_user_locale();
Modules/AdSense.php:520: 'locale' => get_locale(),
Modules/PageSpeed_Insights.php:118: 'locale' => substr( get_locale(), 0, 2 ),
```

Ensure there are no other cases of calling `get_user_locale()` and `get_locale()` directly.

* 

## QA Brief

* Set the locale on your WordPress site to `Português (AO90)` `pt_PT_ao90` via /wp-admin/options-general.php 
<img width="469" alt="Screen Shot 2021-04-08 at 3 12 47 PM" src="https://user-images.githubusercontent.com/373931/114102858-f3e26800-987c-11eb-81d1-52705614a95a.png">

* Ensure that you can enable Adsense module and see earnings reports in Portuguese.
* Repeat the same with the following languages to ensure that the Adsense report loads and shows, even if it's in english.
* `<option value="bel" lang="be">Беларуская мова</option>`
* `<option value="de_DE_formal" lang="de">Deutsch (Sie)</option>` 

## Changelog entry

* Resolved language issue on AdSense dashboard for certain Site Languages.

**Comment by cole10up** [comment]
**Tested**

Installed, Activated and setup latest Site Kit. Activated Adsense and changed the language to Portuguese AO90

![image](https://user-images.githubusercontent.com/57115907/96547160-768c5200-1260-11eb-9051-89857cae8956.png)

Saved and checked Adsense
![image](https://user-images.githubusercontent.com/57115907/96547202-899f2200-1260-11eb-898f-0914888d2068.png)

![image](https://user-images.githubusercontent.com/57115907/96547234-9c195b80-1260-11eb-98b9-858fa96dd41a.png)

No errors were displayed.

Flipped the date range to 14 days and noticed:

![image](https://user-images.githubusercontent.com/57115907/96547498-092cf100-1261-11eb-987e-6ccba4258953.png)

Sending this to Execution as this is confirmed to be an issue.

**Comment by ivankruchkoff** [comment]
The IB of this ends up being the PHP analogue to the JS in #1309, and we can take it a step further by creating a get_site_kit_locale function which takes an optional context = 'user' parameter, that does the replacement and proxies to the corresponding `get_locale()` and `get_user_locale()` functions.

The upshot is that we don't need to call substr everywhere we use the core functions.

**Comment by felixarntz** [comment]
@ivankruchkoff I like that idea! Maybe a new method in `Context`? Would be great if you could incorporate that idea into the IB.

**Comment by ivankruchkoff** [comment]
> @ivankruchkoff I like that idea! Maybe a new method in `Context`? Would be great if you could incorporate that idea into the IB.

Updated the IB.

The params `2char`/`5char` sound rather arbitrary, however they are more intuitive than:

- ISO 639-1 language code
- Equivalent of BCP47, the ISO 639-1 language code followed by iso-3166-2 alpha2

Further reading for the curious:

- https://en.wikipedia.org/wiki/ISO_639-1
- https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes
- https://tools.ietf.org/html/bcp47
- https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

Some languages have multiple alphabets/writing systems:

- uz-Cyrl-UZ (Uzbek, Cyrillic, in Uzbekistan)
- uz-Latn-UZ (Uzbek, Latin, in Uzbekistan)
- iu-Latn-CA ( Inuktitut in Latin in Canada)
- iu-Cans-CA (Inuktitut in Latin in Canada)

You'll find the same with Azeri, Mongolian, Punjabi, the language(s) spoken in Serbia, Hrvatia, Bosnia, Montenegro...

iu-Cans-CA
--




iu-Latn-CA
--




- 

mn-Cyrl-MN - Mongolian, in Cyrillic, as used in Mongolia.

**Comment by felixarntz** [comment]
@ivankruchkoff Mostly LGTM, just the names `2char` / `5char` indeed sound a bit odd and too specific/technical to me. I'd rather go with something more intuitive like `language` / `locale` maybe? The suffixes that WordPress may add (e.g. `-formal`) are usually unsupported and in no way standardized. As far as I'm aware, the first segment identifies the language, and together with the second segment it makes it a locale, and then any following segment just further specifies said locale.

Maybe the names I'm proposing aren't perfect either, and we can think about it further. But `2char` and `5char` is too technical - e.g. the `iu-Latn-CA` example wouldn't really work with that. From that perspective I'm wondering: Does `iu-CA` also exist? Or is the `Latn` specification in the middle mandatory?

**Comment by ivankruchkoff** [comment]
Updated to `language-code` and `language-variant`.

Some places call it a locale, others a variant. I'm happy with either.

Alphabet `Latn`/`Cyrl` is an optional parameter, but also in this case, it's irrelevant as WordPress doesn't have these locales available to choose from.

I took the full list of available languages from WordPress admin (5.7):
https://gist.github.com/ivankruchkoff/e0c804929d4a236733010af5b930c7b6

Filtered for just the value field
https://gist.github.com/ivankruchkoff/73399c8286fe2a150aa2425cbed606f6

Took just the first 5 chars, and got this list
https://gist.github.com/ivankruchkoff/b9a07ade0c40abd674d38a4f7d9a3365

A few things stick out:
1) Picking some of these languages and calling `get_locale()` on them does not return the 2char or 5char variant, instead it uses the [3char](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) language code. E.g. Belarusian, Yakut
2) From what I could find in Google Analytics documentation, only a subset of those languages are supported https://support.google.com/analytics/answer/1008006?hl=en
3) A different list of languages is supported across Google Adsense https://support.google.com/adsense/answer/9727?hl=en

Should any of those impact our implementation here? A quick browse of the lists in 2/3 show that the languages with the 3char language codes aren't supported in either Google Product, is the fallback behaviour to en-US? 

The 3 character languages trimmed to 2 characters may trim down to the correct 2 char code, as is the case for Belarusian, or may not as is the case for [Yakut](https://en.wikipedia.org/wiki/Yakut_language), which goes from `sah` to `sa` which is the code for [Sanskrit](https://en.wikipedia.org/wiki/Sanskrit).

My take is that we leave a comment in the function about some peculiarities about WordPress language codes in the admin, the links to the supported languages in the Google products, and still do the `substr` `2`/`5` char approaches.

**Comment by felixarntz** [comment]
@ivankruchkoff Thanks for the detailed analysis!

The new names you're proposing sound solid to me. Regarding the approach, I think we may need to be a bit more fine-grained than just saying 2 or 5 characters. How about the following:

* Split the WordPress locale string by underscore.
* If `language-code`, return the first segment (no matter how many characters, realistically that's 2 or 3).
* If `language-variant`, check if the second segment is all-uppercase. If so, return it too. If not, it's something else which we should ignore, so in that case it should just return the first segment, effectively the same as `language-code` would for such a locale.

I would go with a generic approach like the above for now, extracting to a "simple" language code or variant. We shouldn't need to exactly match the list of locales supported by the different Google services, that would require manual maintenance and open a bit of rabbit hole. The only thing I wanna make sure is our approach works for "uncommon" language codes/variants as well (like the 3-letter ones you called out).

Let me know your thoughts; if you agree, please update the IB accordingly.

**Comment by ivankruchkoff** [comment]
@felixarntz 

- Updated the QA instructions to ensure we test a few languages that could cause bugs.
- Updated the IB to have `language-code` be everything before first underscore, and `language-variant` everything before the second underscore as there is currently no scenario in WordPress where a Site Language contains an underscore but is then followed by capital letters.

**Comment by felixarntz** [comment]
@ivankruchkoff Sounds good! IB ✅

**Comment by Hazlitte** [comment]
I have been following 'Steps to reproduce' and @cole10up's follow up notes but I have not been able to recreate this bug using the develop branch on my local development environment.

**Comment by wpdarren** [comment]
QA Update:

**Verified:**

Please note: I was unable to recreate the initial issue with the locale set to `Português (AO90)` but can confirm:

- You can enable Adsense module and see earnings reports. The error message did not appear. 

[Screenshot 1](https://user-images.githubusercontent.com/73545194/116417987-a5990700-a833-11eb-9568-fd83d2edeb0a.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/116418008-aa5dbb00-a833-11eb-852e-fffc8a0033f1.png)

- I also repeated the same with `Deutsch (Sie)` and `Беларуская мова`. The error message did not appear.
