### ISSUE TITLE
Add pointers to admin menu and admin bar integration

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#211]
As discussed earlier, let's add WordPress pointers to make discovery of the admin menu and the admin bar integration easier.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
This is a fragment that will be addressed via the larger visual language redesign. Closing.
