### ISSUE TITLE
Fix Search Console deep links for domain properties to filter only current site

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2110]
## Bug Description

#1917 fixed data for Search Console domain properties to only be displayed for the current site. However, now Search Console deep links to the service frontend are still not considering this, resulting in potentially inconsistent information. Following up on #1923, if the site is using a Search Console domain property, all Search Console URLs deep links (except those that are already for specific URLs) should be updated to include an extra argument to only include URLs that are part of the site.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All deep links to `https://search.google.com/u/1/search-console/performance/search-analytics` in Site Kit widgets (both new and legacy) should be updated to include an extra query parameter `page=*{siteURL}` where `{siteURL}` is the reference site URL, without trailing slash at the end.
    * The query parameter should only be added if the site uses a Search Console domain property (starting in `sc-domain:`).
    * The exception to this are deep links for single URL details view where that `page` query parameter is already added based on the current entity URL.

## Implementation Brief

* Add an `isDomainProperty()` selector to `modules/search-console` data store that offers a boolean return value to check if a property is a Domain Property:
```js
isDomainProperty: createRegistrySelector( ( select ) => () => {
	const domain = select( STORE_NAME ).getPropertyID();

	return domain && domain.startsWith( 'sc-domain:' );
} ),
```
* Add relevant tests for the above selector and include it in the Search Console data store.
* Use `useSelect( () => select('core/site').getReferenceSiteURL() )` to get the `referenceSiteURL`, then remove the trailing slash from it if needed. The rest of the IB assumes it's stored in a `referenceSiteURL` variable.
* Add a <code>page: \`*${ referenceSiteURL }\`</code> param to the `query` param for all `getServiceURL()` selector calls with URLs (`path` params) using `/performance/search-analytics`, _if_ `select( 'modules/search-console' ).isDomainProperty() === true`. (And as long as they don't have an existing `page` param, see the ACs.)

## QA Brief

* Install Site Kit and set it up with a site that uses a Search Console domain property and has Search Console data.
* Search Console deep link URLs (in both new widgets, via development build, as well as legacy widgets) should be updated with the new `page=*$REFERENCE_SITE_URL` query params, unless they are for a specific URL (in which case they, as before, should have a `page=!$SPECIFIC_URL` query param).

## Changelog entry

* Fix Search Console deep links to point to correct locations in case of a domain property as well.

**Comment by felixarntz** [comment]
@tofumatt Note that this is dependent on #1923, there will be a couple more URLs to update once that is merged. What's missing from the IB is a note on how to differentiate between whether the Search Console property is a domain property (starting with `sc-domain:`) or not. Only if it's a domain property, this extra handling is needed.

I'd suggest removing the exact mentions of specific files and rather say something like "everywhere where a Search Console URL like `performance/search-analytics` is linked to"

**Comment by tofumatt** [comment]
I updated the IB here, but the suggestion made to apply this everywhere the url `performance/search-analytics` is linked to confused me in addition to the comment about `sc-domain:`—I only see that in one place in the current codebase: https://github.com/google/site-kit-wp/blob/099cac9a45e52cb90bc4473a68f37eb7f6f45666/assets/js/components/setup/search-console.js#L179-L190

**Comment by felixarntz** [comment]
@tofumatt Every URL where we link to Search Console contains a `property_id` query parameter which is the Search Console property ID, i.e. we're already retrieving that in every such case. _Only_ if that value starts with `sc-domain:`, we should add the `page=*{siteURL}` query parameter - otherwise nothing should be changed from what's already in place. It might be worth outsourcing the `sc-domain:` check into an `isDomainProperty` utility function within the Search Console module code.

Another nitpick: Can you double-check the IB for formatting? It's kind of hard to read right now because something is off with the ` characters.

**Comment by tofumatt** [comment]
Ah, sorry, I misunderstood. I thought we were adding `sc-domain:` in places but I see it's part of the existing URL and we need to check for it. Thanks, I'll get this sorted now 👍🏻

**Comment by felixarntz** [comment]
@tofumatt IB mostly good, except

> Add a <code>page: \`*${ referenceSiteURL }\`</code> param to the `query` param for all `getServiceURL()` selector calls with URLs (`path` params) using `/performance/search-analytics`, _if_ `select( 'modules/search-console' ).isDomainProperty() !== true`.

This should be exactly the opposite, the parameter should only be added if it _is_ a domain property (`=== true`) :)

**Comment by tofumatt** [comment]
> This should be exactly the opposite, the parameter should only be added if it _is_ a domain property (`=== true`) :)

Argh, indeed! I originally wrote it as `!== false` then realised we should check for `true` in case it returned `undefined` while loading. I forgot to change the `!==` though 😅 

All set now! 👍🏻

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
@aaemnnosttv @cole10up @kostyalmm 

_Search Console deep link URLs (in both new widgets, via development build, as well as legacy widgets) should be updated with the new page=*$REFERENCE_SITE_URL query params, unless they are for a specific URL (in which case they, as before, should have a page=!$SPECIFIC_URL query param)._

I want to make sure that I am understanding this QA brief.   When SK has been set up for a domain with SC data, I can see the list of search queries.  When I look at the URLs in the console they appear as `https://search.google.com/search-console/performance/search-analytics?**resource_id=https%3A%2F%2Fhivevine.com%2F**&num_of_days=28&authuser=hello%40hivevine.com&query=%21what%20is%20freelance%20work` I am assuming that the reference site URL is resource_id within the URL?

**Comment by kostyalmm** [comment]
@wpdarren , firstly please make sure that you have access to a search console domain property. It is of the format `sc-domain:<>`
Set site kit up with this property and go to the search console page. Then check if a `*` character is prepended to the page parameter for the links that lead to the Search Console. Also, please check the same for search console components present on the Dashboard page of the Site Kit plugin.

**Comment by wpdarren** [comment]
@cole10up @aaemnnosttv an update on this ticket. I have tried to set up a domain property on search console but to do this you need to add a TXT record on the domain name.  I've completed this task but when I go into verify the domain in SC, it's not seeing the change to the DNS record yet.   If we have a site, which has a domain property, and data, that would speed the QA up on this ticket. I'd need access to the site and SC permissions given to my 10up Google account.

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren – I have a domain property I can test with so I'll take over here 👍

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Checked SC deep links in new and old widgets, on main dashboard and page dashboards to ensure the `page` query parameter was correctly added when Site Kit was configured with a SC domain property.

<details>
<summary>Screenshots</summary>

**Main dashboard (new widget)**
![image](https://user-images.githubusercontent.com/1621608/98348666-b6558680-2021-11eb-8704-3246ae46cea8.png)

**Main dashboard (legacy widget)**
![image](https://user-images.githubusercontent.com/1621608/98348817-e4d36180-2021-11eb-9277-46948dc8643a.png)

**Single page dashboard** (scoped to URL)
![image](https://user-images.githubusercontent.com/1621608/98348961-10eee280-2022-11eb-99b0-19e6f9603de6.png)

**URL opens in Search Console correctly**
![image](https://user-images.githubusercontent.com/1621608/98349108-44ca0800-2022-11eb-832e-13e3fdf9336a.png)

</details>
