### ISSUE TITLE
Adsense doesn't show ads only sometimes

### ISSUE THREAD

**Issue by marimanga** [google/site-kit-wp#2113]
I had this problem over a year and couldn't fix it neither find what's the problem. Adsense never emailed me or sent a notification on my account that this is the problem why we don't show ads. I have auto-ads and ads appears only 1 page other pages are blank spaces, No policy violations no nothing at all my site is ready on my account everything is fine but ads doesn't show. I tried ads troubleshooter at the end it redirect me "Are you wordpress user , yes , check if your code was implemented correctly or use sitekit" i use site kit from beginning. I have 1,315 pages reviewed in 30 days and i'm sure 50% that this is why ads doesn't show but on that 1 page which ads appears after 2-3 refreshes ads gone. It's making me confusing. If you could take a look at my site i will appreciate it alot 👍 

My site https://listpune.com

**Comment by jamesozzie** [comment]
Thanks for reaching out and providing additional information. Unfortunately we're limited to Site Kit plugin support and unable to troubleshoot AdSense specific queries. 

While there are a variety of reasons why ads may not be appearing as desired if you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on our WordPress support forum and then provide your Site Health information using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) we'd be happy to check that your snippet is inserted and the AdSense module successfully connected.
