### ISSUE TITLE
WPML Compatibility: switching language from top admin bar disconnects and prompts setup

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#2118]
## Bug Description

When using the [WPML plugin](https://wpml.org/), switching languages from the [top admin bar](https://jmp.sh/oqHqyzd) disconnects Site Kit and prompts the setup process due to detecting a change in the URL:

<img width="1429" alt="notice to reconnect after change in URL" src="https://user-images.githubusercontent.com/8108643/94758923-6c5af000-0353-11eb-8695-fafc4667a66b.png">

## Steps to reproduce

1. Install and configure the WPML plugin
2. Change the language selection from the top admin bar
3. See Site Kit disconnect and notice to reconnect appear

## Additional Context

 - PHP Version: 7.3.16
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.17.0
 - Device: MacBook Air

Video: https://recordit.co/vLmmvjusME

Related support topics: 

https://wordpress.org/support/topic/site-kit-asks-me-to-reconnect-all-the-time/
https://wordpress.org/support/topic/site-kit-asks-me-to-be-reconnected-when-change-language-flag-wpml/
https://wordpress.org/support/topic/wpml-issue-17/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by Nerdiyde** [comment]
Hey Guys, i have the same issue. I'm not using WPML but WPGlobus. Just wanted to let you know. :)

**Comment by joecarletto** [comment]
Hi guys, I've the same bug and I'm using WPML

**Comment by xanxano** [comment]
Hi!
The same thing, wpml with one domain per language...
We are waiting for the updates! ;-)

**Comment by adamsilverstein** [comment]
Thanks for the feedback @xanxano, @joecarletto & @Nerdiyde. We are working to address this issue in https://github.com/google/site-kit-wp/issues/2131.

**Comment by ernee** [comment]
Hi there! Just a quick update that we'll be reaching out to language plugins to help with the solution. 

@Nerdiyde I've been trying to recreate the issue with WPGlobus, but have yet to see it occur. Could you share more about your configuration and how to reproduce the issue? Thanks so much!

**Comment by Nerdiyde** [comment]
@ernee Hey, 
hmm, I did not really do anything special to provoke this error. :/ Not even sure that the issue is related to WPGlobus. Just mentioned it because others mentioned WPML as a possible source. Maybe its related to an other plugin? Please tell me what other information might be helpful? :) Thanks for fixing this btw. :)

**Comment by ernee** [comment]
@Nerdiyde thanks for the reply! It would be great to get more info about your setup. Could you provide your [Site Health information](https://i.imgur.com/Rtkmsba.png) through [this form](https://forms.gle/NYxN6Dy1NUKed6R28) (note: you may want to place the [support forum topic](https://wordpress.org/support/topic/site-kit-asks-me-to-reconnect-all-the-time/page/2/#post-13485866) you replied to in the corresponding field)?

**Comment by Nerdiyde** [comment]
@ernee You should have received my site health infos. :)

**Comment by ernee** [comment]
@Nerdiyde thanks for providing the info! So, I've been testing several plugins you have and their configurations, but haven't been able to recreate the issue you experienced. Could you provide/ try the following to help us narrow down what could be the source of the issue on your site:  
1)

**Comment by hifi-vd** [comment]
Hi, I have the same problem with very often reconnecting Site Kit and using WPML. I am using Google Tag Manager as connector for Google access codes. Before the codes were in the templates and I had no problem. But with every update of the templates I lost access, so changed to Tag Manager. It would be fine to solve this "reconnect" problem, because WPML and Tag Manager are great and very common tools. Thanks

**Comment by ered15** [comment]
Having same issue, have the last WP installation and using Site Kit by Google 1.18.0, WPML Version 4.4.3 every time I change  the language in the top bar it asks to reconnect.

**Comment by ernee** [comment]
Thanks @hifi-vd and  @ered15 for reporting! We've reached out to the team at WMPL to help with a fix. We'll keep this issue updated on the progress.

**Comment by Rescovedo** [comment]
Finally found my friends with the same issue <3

**Comment by LCthur** [comment]
Hey guy, I'm using WPML and I have the same problem.

**Comment by adamsilverstein** [comment]
Hi everyone, thanks for your patience while we worked on a solution for this. We added a filter into Site Kit and are working with WPML to ensure we are compatible. For full compatibility, you will need to be using the latest version of Site Kit and the next version of WPML - the fix should go out with WPML 4.4.5 (next release).

**Comment by joecarletto** [comment]
Well done, @adamsilverstein!

**Comment by adamsilverstein** [comment]
👋 Hello reporters - the new WPML version updated has started rolling out. When you have the new (WPML 4.4.5) version installed, can you please re-check Site Kit and ensure you correctly remain connected when switching languages?

**Comment by ernee** [comment]
Reported in [this support topic](https://wordpress.org/support/topic/site-kit-asks-me-to-reconnect-all-the-time/page/3/#post-13659404), it appears the issue persists when selecting "All languages" from the top admin bar language switcher (Site Kit disconnects). Here is a [video](https://recordit.co/cko9AryCp8).

**Comment by ernee** [comment]
WPML is planning to release the fix for the remaining issue in their next version 4.4.7. We'll follow up when it is available.

**Comment by SamManders** [comment]
I'm having the same issue, but I'm using TranslatePress. Seems like most translated sites suffer from this issue...
If there will be any solution I'd be happy to hear it.

**Comment by ernee** [comment]
WPML version 4.4.7 has just been released with the remaining fix to address the issue with the "All languages" admin bar setting.  

@SamManders thanks for reporting. We've been trying to replicate the issue using TranslatePress. Could you send us a recording and/ or a detailed step-by-step of what causes the issue on your site? You can use the app like [Recordit](https://recordit.co/) to make a video. Many thanks!

**Comment by ernee** [comment]
Closing this issue since it is resolved with WPML. 

We have a few other multilingual plugins we'll be reaching out to as well. If you haven't already, please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) if you are experiencing this issue with another plugin (not WPML).

**Comment by adamsilverstein** [comment]
@Nerdiyde If possible, can you please test adding this mini plugin to your WPGlobus install, this should correct this compatibility issue you reported: https://gist.github.com/adamsilverstein/199f3a4cfe8b4ccc881713a7ece05438

**Comment by Nerdiyde** [comment]
Hey guys,
I did install the patch @adamsilverstein provided. Thanks a lot for your work! :)
Do you need anything as some kind of "success report"? 
Thanks and best regards
Fab

**Comment by adamsilverstein** [comment]
Here is a "mini plugin" you can install if you are still experiencing an issue with your install: https://gist.github.com/adamsilverstein/199f3a4cfe8b4ccc881713a7ece05438

**Comment by jamesozzie** [comment]
@Nerdiyde Great to hear it. We'll certainly keep you in mind should we be looking for user case studies or blog posts. If you haven't already done so we'd love to hear your [feedback](https://wordpress.org/support/plugin/google-site-kit/reviews/#new-post).

**Comment by vmajor** [comment]
Related issue, perhaps. I am using TranslatePress and keep getting disconnected. I will look for/make a separate issue for this.

**Comment by adamsilverstein** [comment]
@vmajor Thanks for your comment. 

I have reported this issue to translatepress support and opened the following issue to help improve the compatibility with Site Kit: https://github.com/phpzio/translatepress/issues/4. Can you please link to or comment on this issue for visibility?

**Comment by jamesozzie** [comment]
@vmajor Just to let you know TranslatePress have made updates to their plugin to ensure Site Kit users remain connected. If you have any further queries on this feel free to reach out via the Site Kit [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit/#new-post).
