### ISSUE TITLE
Simplify Widget component registration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2119]
## Feature Description

Similar to #2024 for module registration, we can simplify the way widgets are registered as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `actions.registerWidget` should not use `getRegistryKey` or a separate object for `WidgetComponents` and can pass `component` through to the reducer as `payload.component` and stored in `state[ slug ].component`.
* `actions.registerWidget` should no longer be a generator function and all asynchronous use should be converted to synchronous
* All use of `WidgetComponents`, `getRegistryKey` and `setRegistryKey` in `assets/js/googlesitekit/widgets/datastore/widgets.js` should be removed

## Implementation Brief

* Update `actions.registerWidget` to simply return an action with `slug`, `settings`, and `component` properties
* Update the reducer for `REGISTER_WIDGET` to combine the given `slug`, `settings`, and `component` into the state for the widget
* Update `selectors.getWidget` to return `widgets[slug] || null`
* Merge #2134

### Test Coverage

* Update relevant Jest tests for `widgets.js` to no longer use `WidgetComponents`

### Visual Regression Changes

* N/A

## QA Brief

* Nothing observable from the user's perspective, this should be a clean refactor behaviorally
* Check the codebase to make sure all instances of `WidgetComponents` are removed and widget registration is synchronous throughout

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB and approach ✅ from me. We discussed this earlier and I think it's a good simplification.

I'll leave it assigned to @felixarntz as I think it's worth both our review 🙂

**Comment by felixarntz** [comment]
IB ✅ , except one detail that I already pointed out in the CR review - no need to separate `settings` and `component` anymore, we can just rely on `settings.component` like it is passed.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: All look good.
