### ISSUE TITLE
Remove weekday alignment functionality from Analytics and Site Kit as a whole

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2122]
## Bug Description

In the Analytics Audience Overview chart, one plot is for the most recent period for the currently selected date range, and another plot is added for the previous period. Additionally, the previous period is shifted so that the week days align between the periods when compared.

**Example with last 28 days**
![image](https://user-images.githubusercontent.com/1621608/94902635-2ca21e80-04a1-11eb-839a-69cf37091cc1.png)

**The same date with last 90 days**
![image](https://user-images.githubusercontent.com/1621608/94902697-480d2980-04a1-11eb-9b59-69592d2e3b2e.png)

Note the days of the week are not aligned (Wed vs Thu instead of Wed vs Wed) with the 90 day date range where they are with 7, 14, and 28 day periods. Of course, those are all even multiples of 7 days, but in #1280 we updated this so that weekdays should align regardless of the period.

## Steps to reproduce

1. Set up Analytics using a site that has at least 90 days of data
1. Go to Analytics dashboard in Site Kit
1. See week days are aligned on default 28 day range view
1. Switch date range to last 90 days
1. See week days are not aligned

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should not do weekday alignment for Analytics when a 90 day period is requested.
* More broadly, weekday alignment functionality should be completely removed from Site Kit, i.e. from its PHP and JS date parsing infrastructure.
* In other words, the bug originally reported here can be ignored, since the underlying functionality should be removed entirely. We can reconsider a more appropriate implementation of weekday alignment across all services at a later stage if it seems useful.

## Implementation Brief

* remove the `weekDayAlign` parameter and logic from the `getDateRangeDates` function in the `date-range` component
* remove the import of `getPreviousWeekDate` from `date-range` component
* delete `get-previous-week-date` component
* remove export of `get-previous-week-date` from `date-range/index`
* delete the `get-previous-week-date.test` file

* edit the `parse_date_range` method in `Module.php`
  * remove the `$weekday_align` parameter
  * remove the logic that move the dates if `$weekday_align` is true

* edit the `create_data_request` method in `Analytics.php`
  * remove the fifth parameter of this method call:
    ‘$this->parse_date_range( $date_range, 1, 1, true, true );’

### Test Coverage

* update js tests to remove the usage of `weekDayAlign`

* update PHPUnit tests to:
  * remove the usage of`$weekday_align` from `FakeModule.php`
  * remove the `test_parse_date_range_weekday_align` test from `ModuleTest.php`
  * remove the `data_parse_date_range_weekday_align` data provider from `ModuleTest.php` as well

### Visual Regression Changes

* N/A

## QA Brief

No user-facing change here so doing QA:Eng check that the IB has been implemented properly

## Changelog entry

* Remove weekday alignment functionality for previous period from Analytics module and Site Kit entirely.

**Comment by aaemnnosttv** [comment]
@felixarntz This seems to only affect the server-side parsing as the newer client-based logic correctly identifies the starting compare date as Sat Apr 4th instead of Sun 5th for the same start date.

![image](https://user-images.githubusercontent.com/1621608/94904262-bb179f80-04a3-11eb-8b89-d8d28b0f1271.png)

The same behavior is observable in the current release so it isn't related to recent changes on the client.

**Comment by adamsilverstein** [comment]
The underlying issue here is that the chart currently uses an approach that doesn't use day alignment, even though we did adjust to use day alignment for the percent comparison change calculations.

The chart relies on data from this query: https://github.com/google/site-kit-wp/blob/168e6f45de73c831294c43dc59f392700b408d68/assets/js/modules/analytics/util/index.js#L396-L429

This data includes up to the last 180 (90 days x 2) of data. Then, in `extractAnalyticsDashboardData` we split the data into the two blocks of time we need:

https://github.com/google/site-kit-wp/blob/168e6f45de73c831294c43dc59f392700b408d68/assets/js/modules/analytics/util/index.js#L173-L177

The date ranges in the chart should always start on the (closest) same day of the week  - for 90 days the previous date range needs to shift back one day).

We can either use `multiDateRange` in this data request (and adjust the splitting logic), or request 183 days of data, and shift the start day to align to the closes matching weekday (moving forward or backward up to three days), as we do in the `multiDateRange` date range calculations.

**Comment by adamsilverstein** [comment]
@aaemnnosttv & @tofumatt I did a little investigating since I worked on the original changes in https://github.com/google/site-kit-wp/issues/1280. Findings above ^^.

**Comment by aaemnnosttv** [comment]
@adamsilverstein I think using `multiDateRange` makes more sense, particularly because some dates may overlap between the two ranges so it definitely fits better into a "separate ranges" paradigm. This is also how it's already designed to work with the JS-based parsing as well, which passes `compareStartDate` and `compareEndDate`: https://github.com/google/site-kit-wp/blob/099cac9a45e52cb90bc4473a68f37eb7f6f45666/includes/Modules/Analytics.php#L972-L984

**Comment by tofumatt** [comment]
I'm sorry, but I had a look through the PHP code here in the past and the JS code, including how the ranges are split, the requests mades, etc.

I think I'm totally lost on how, exactly, this stuff all connects together.

At first what seems obviously to me was to change the start date in the query to match the end date so things would align. I tried changing some of the JS as well as suggested here but I think I might be missing a step or a clear understanding on how the data path here works.

I'm going to unassign myself from this one as I'm not clear on the path of the data here and it seems @aaemnnosttv has a better sense of it, so as to not block the issue I'm moving the assignment. If I'm missing something simple please let me know and re-assign it to me. 😅

**Comment by aaemnnosttv** [comment]
@adamsilverstein @felixarntz looking into an IB for this, I don't think this is fixable as-is without substantial changes.

My understanding of the problem is that we need to change how the report request is made to be a true multi-date range request, rather than the range math and splitting that we do with `compareDateRanges` which is a bit of a hack based on our previous understanding of how the API worked. However, changing this in the current data request (`siteAnalyticsReportDataDefaults`) would break the utilities we have for parsing the results (`extractAnalyticsDashboardData` and `extractAnalyticsDashboardSparklineData`) which are tightly coupled to the format of the response.

Given that this is just a 1 day difference in a single date range, I would say it's not worth the effort or risk to address now as it should be handled as we refactor our components. As soon as we move to _using_ the date range parsing/handling on the client (which is limited to the refactored components now) then we'll be forced to deal with this because the response will change. It doesn't seem like a good idea to push this right now while maintaining the legacy components, so I suggest we keep this as a known issue, but put it on the back burner until the Analytics components are migrated and we both need to make this change, and legacy components will be gone.

**Comment by adamsilverstein** [comment]
> Given that this is just a 1 day difference in a single date range, I would say it's not worth the effort or risk to address now as it should be handled as we refactor our components

Sounds reasonable, especially given that this only affects the chart - the numbers and percent changes are accurate already.

**Comment by aaemnnosttv** [comment]
Moving back to AC for revision.

**Comment by benbowler** [comment]
@felixarntz what has changed since this was moved back into AC in Oct 2020

**Comment by benbowler** [comment]
I unassigned myself here as I don't think I'll be able to get a handle on this with my remaining time.

**Comment by Hazlitte** [comment]
@aaemnnosttv I have been looking at how the `parse_date_range` method works in `Module.php` and it appears to already fulfil the server side requirement of the Acs.  Are there any known cases where it is not working as required?

**Comment by tofumatt** [comment]
I tried the suggested IB here and still saw off-by-one days of weeks in the Analytics dashboard.

The server-side implementation is, I think, correct, but the client-side has issues maybe?

Either way, visiting http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-module-analytics then selecting "90 days" on a site with data (ElasticPress.io, for instance) will show the error.

**Comment by Hazlitte** [comment]
Hi @tofumatt,
My IB test seems to work best I realised that I failed to specify which set of data to slice in the IB so I added previousMonthRows to:
`if 90 days has been selected slice the previousMonthRows data starting at row 6`

**Comment by aaemnnosttv** [comment]
Note there is a bug with the 90 day view in the widget-based version of the Analytics dashboard which may complicate the discovery here. See #3232

**Comment by Hazlitte** [comment]
I investigated this further and the IB resolves this bug on the legacy dashboard widget.  It does not solve a similar bug which is in the refactored Analytics widget.

**Comment by tofumatt** [comment]
So, first: my apologies, looks like I had the Widget Module pages feature flag enabled when I tested the IB and I noticed this _does_ fix the bug in the non-widget version.

I see why the fix works—but it's a hardcoded solution that'll only work for 90 days or date numbers that match this problem.

Let's instead take an approach where we slice starting from whatever value will get us an array length that can be evenly divided by 7, something like: `rows.slice( rows.length % 7, rows.length - days )`. That way we don't need to special-case the 90-day thing and it'll keep working if we ever change the date arguments 🙂 

Will a similar approach work for the widget-based chart too? If it's that straightforward a fix it'd be good to get there too, as I notice it's also off but different. Or do we already have an issue open for that?

**Comment by aaemnnosttv** [comment]
@Hazlitte @tofumatt my initial impression here is that slicing the rows returned from the API a certain way is likely fixing the issue in the wrong place as we already have specific pieces of code in place that deal with day of the week alignment. Let's first understand why the existing code is falling short to make sure we're addressing this in the right place.

Since this is primarily related to dates, I would make sure we're passing `weekDayAlign: true` to the `getDateRangeDates` selector everywhere its needed (probably all uses in Analytics reports). Let's check this first since it is not `true` by default.

For client side logic, see our date utils (specifically `getPreviousWeekDate`). These have fairly thorough test coverage but we should review these to make sure things are correct, specifically for 90 day range.

Also keep in mind that the alignment should be to the _closest_ day (a detail of how the weekday align works), the alignment in the 90 day range is off by 1 so the comparison range should only be shifted that much. It's okay to have overlapping dates as a result (the alternative of orphaned dates would be worse).

Regarding the server side – hopefully no changes are needed there as this is probably the most complex part. Given that the widgets API is starting to roll out now it may not be worth fixing things there if there are problems. For legacy report requests though, this may be a slice-related problem depending on how the report data comes back. It may be as simple as "slice current from end, slice previous from beginning" rather than simply cutting the rows in half since the total number of rows may not be even if there is overlap between periods.

**Comment by aaemnnosttv** [comment]
@felixarntz I took another look at the charts on the service and found mixed results regarding weekday alignment.

The only place I see weekday alignment is on the top-level Google Analytics home dashboard. This also has similar date ranges to choose from: 7, 28, 90 (+others/custom). For the 7 and 28 ranges, we see the alignment we would expect, although these ranges are even divisions of 1 week so it isn't actually doing any shifting here.

When viewing the 30 day range, we can observe weekday alignment in effect as it is not evenly divisible number of weeks.

| Last 28 days | Last 30 days |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1621608/116863755-6db50980-ac0f-11eb-8fa7-453c5d377adf.png) | ![image](https://user-images.githubusercontent.com/1621608/116863764-73125400-ac0f-11eb-9e66-3b6aec6c3f56.png) |

When viewing the 90 day range, the tooltip shows the highlighted nodes as representing 1 week rather than a single day which is a substantial difference than we have but is doing some alignment again because 90 is not evenly divisible by 7.

![image](https://user-images.githubusercontent.com/1621608/116862790-f2068d00-ac0d-11eb-9576-033f34f7ffd8.png)

However, when clicking into the charts in the reporting views, the weekday alignment is no longer observed.

![image](https://user-images.githubusercontent.com/1621608/116863096-70632f00-ac0e-11eb-9ecc-0194c5b2d42f.png)

![image](https://user-images.githubusercontent.com/1621608/116863026-5590ba80-ac0e-11eb-81a6-c4340cd7ebf0.png)

When the option for _Compare to_ is set to **Previous period** it simply defines the comparison range as the previous date range which ends on the day before the primary range begins.

This leads me to conclude that we have to choose which view we want to be consistent with as we can't be consistent with both. Should we maybe make weekday alignment a configurable preference for the view?

**Comment by felixarntz** [comment]
Moving this back to ACs to revisit.

**Comment by felixarntz** [comment]
After discussion with @marrrmarrr, we have decided to entirely drop weekday alignment functionality in Site Kit for now. It is used inconsistently in Site Kit, and implementing it in a proper way across all services _and_ with the potential ability to also disable it requires more exploration.

The default behavior for most services (and even for Analytics in most places) is to not do that, so we will stick to that for now. Last but not least, for 3 out of our 4 date ranges, weekday alignment is naturally a given anyway.

I'll update the ACs and refocus this issue to remove weekday alignment functionality from the plugin, instead of fixing this bug which therefore is now obsolete.

cc @aaemnnosttv @adamsilverstein

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by danielgent** [comment]
I'm assuming _"date-range component"_ in the IB refers to the `date-range` datastore :smile:

**Comment by danielgent** [comment]
Yes, I think in the IB everything is called a component (Which is definitely incorrect in React vocabulary!)

e.g. _delete get-previous-week-date component_ is actually a util function :thinking:

**Comment by danielgent** [comment]
I'm adding a QA:Eng label because I don't see any user-facing change here to be QA'd normally

**Comment by eugene-manuilov** [comment]
> I'm adding a QA:Eng label because I don't see any user-facing change here to be QA'd normally

Yes, it makes sense. Thanks, @danielgent.

**Comment by tofumatt** [comment]
IB ✅
