### ISSUE TITLE
Google Site Kit: Analytics Gathering Data & Search Console Gathering Data

### ISSUE THREAD

**Issue by brijeshp1993** [google/site-kit-wp#2124]
Hi,

I have install site kit by google plugin with deactivate W3 total cache plugin and install in incognito window, google search console and analytic console both are verified successfully but still I am facing  "Analytics Gathering Data" issue. for you information i have attached below SS. 
![image](https://user-images.githubusercontent.com/62394608/94924861-ec13c680-04db-11eb-9fe0-541b93018746.png)

Both services are showing me as connected,
![image](https://user-images.githubusercontent.com/62394608/94925129-57f62f00-04dc-11eb-8f46-9966a83bda5a.png)

please let me know, what I am missing here.

**Comment by jamesozzie** [comment]
Thanks for reaching out. Initial support requests can be submitted using the plugins WordPress support forum. 

If you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing your Site Health information using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) we'd be happy to assist. 

Note also that the notice you encounter can appear if there is no Analytics data yet available, your configuration may already be correct.
