### ISSUE TITLE
getting Looks like you don't have Analytics account yet. Once you create it click "Re-fetch my account" and Site Kit will locate it.

### ISSUE THREAD

**Issue by yzeek** [google/site-kit-wp#213]
Looks like you don't have Analytics account yet. Once you create it click "Re-fetch my account" and Site Kit will locate it.

tried gazillion times and even created a new property

**Comment by srcek** [comment]
Same problem here. Whatever I do it doesn't find any Analytics accounts

**Comment by jamesozzie** [comment]
@yzeek Can you try the below, which will hopefully assist getting your Analytics working.

1. Remove the Analytics [module](https://i.imgur.com/6ppIDwZ.png) (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
2. Temporarily deactivate your other active WordPress plugins
3. Install Site Kit in a new incognito window (so Chrome extensions don't interfere and caching inactive)

And yes, as @srcek mentioned sometimes a workaround is to temporarily disabled such plugins while installing and configuring Site Kit. 

Let me know if that fixes the issue, if not we can troubleshoot further.

**Comment by mbdiener** [comment]
I had the same issue where re-fetch my account wasn't working. I was able to resolve by removing the analytics module and reinstalling it. I also did deactivate my cache plug-in but am not certain if that had any effect.

**Comment by jamesozzie** [comment]
@mbdiener What caching plugin are you using?

**Comment by mbdiener** [comment]
@jamesozzie I’m using Litespeed Cache on this site. I was using WP Fastest Cache but switched to Litespeed on the recommendation of my hosting company (bigscoots.com). It has made a positive difference.

**Comment by robwent** [comment]
I'm still seeing the same problem after disabling plugins.
In the console I get these errors:

```A bad HTTP response code (400) was received when fetching the script.

54 Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
www.domain.com/:1 
Blocked script execution in 'https://www.domain.com/?tagverify=1' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.```

**Comment by jamesozzie** [comment]
@robwent @yzeek Can you please try remove the [Analytics module](https://i.imgur.com/6ppIDwZ.png) (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit) before then temporarily disabling all other plugins and then try installing again via an incognito window? That way there will be no caching interference and any potential Chrome extensions are deactivated.

**Comment by robwent** [comment]
Working now, thanks

**Comment by jamesozzie** [comment]
@robwent Good to hear. Can you let me know what security, analytics or firewall plugins you were using if any?

**Comment by robwent** [comment]
@jamesozzie Initially I disabled supercache in the settings and wiped the cache, then disabled the plugin along with others and still had the problem.

The only security plugin is a jetpack module which works on the admin login page. I previously had wordfence but deleted the rules they add to the htaccess file.

For analytics I have 'Google Analytics Post Pageviews' which adds hits for posts in the post list screen (Would be a good feature).

Using incognito seemed to fix it when taking the same steps.

I still see the same warnings in the console on the sitekit settings page but analytics is connected now.

**Comment by jamesozzie** [comment]
Thanks for the update @robwent 

@yzeek Let me know if you are still encountering problems.

**Comment by robwent** [comment]
To add a bit more confusion :)

I just installed the plugin on a multisite install.

For the first site, I went to the supercache settings, disabled caching and then deleted the cache and then analytics connected ok.

I went to the second site and got the message about not having an account. Even incognito didn't work even though I had taken the same steps to disable and delete the cache.

3rd site that never had caching enabled got the same message.

It seems to take a long time to get a response from analytics, almost like it's just timing out.

**Comment by robwent** [comment]
Or maybe api request limits when trying to connect multiple sites through the same gmail account?

**Comment by jamesozzie** [comment]
@robwent Caching plugins can cause issues during the setup stage, and yes, API request limits also. 

In your case also you might have ran into problems as you were using a multi site installation. You can see [here](https://github.com/google/site-kit-wp/issues/276) more information on multi site installations, which is on the roadmap.

**Comment by Eddy005** [comment]
the same problem, no work, keep showing Re-fetch my account, even reinstall still no working

**Comment by robwent** [comment]
Seems odd that this only affects analytics and not other services.
