### ISSUE TITLE
Add filter to modify home URL result (e.g. for comparison)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2131]
#1857 added logic that disconnects a user when the site's `home_url()` has changed. This logic intentionally relies on the real home URL used (including any filters on it), to get the real URL used, which may differ from what is stored in the database. However, this can cause problems with e.g. multilingual plugins which filter the home URL based on which language is currently active (e.g. to append path segments like `/de/` or `/es/`). This then results in a disconnect whenever the user switches from one language to another in the backend.

Site Kit should offer a filter `googlesitekit_home_url` to get the base home URL of a site (which mostly is relevant for what gets registered on the authentication service). Plugins that modify the home URL in more dynamic ways (e.g. multilingual plugins or domain mapping plugins) can then use that filter to ensure their URL modifications still keep the home URL used by Site Kit "stable". It could also be referred to as essentially the "canonical home URL" in terms of Site Kit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new method `Context::get_canonical_home_url()` which calls `home_url()` and runs it through a new `googlesitekit_canonical_home_url` filter.
* The new method should be used throughout the plugin codebase in every place where currently `home_url()` is called, except if that call is decoupled from core Site Kit logic (e.g. entity detection is not using `Context` at all, the relevant modifications happen within `Context` itself). In other words, the only classes where these calls should not be updated are `Entity_Factory` and `WP_Query_Factory`.

## Implementation Brief

* Add a new public `Context::get_canonical_home_url() : string` method
	- Returns the result of `apply_filters( 'googlesitekit_canonical_home_url', home_url() )`
* Update usage of `home_url()` to use new canonical home URL in source code (all uses already have access to a `context` property instance so it should be a clean replacement)
	- [See relevant search results here](https://github.com/search?q=home_url+repo%3Agoogle%2Fsite-kit-wp+path%3Aincludes+language%3APHP+language%3APHP+-filename%3AEntity_Factory.php+-filename%3AWP_Query_Factory.php+language%3APHP+language%3APHP+language%3APHP+language%3APHP&type=Code&ref=advsearch&l=PHP&l=PHP)
	- Use in `Entity_Factory` and `WP_Query_Factory` should be left unchanged (excluded from results above already)
	- Use in existing PHPUnit tests and E2E utilities shouldn't need to be changed

### Test Coverage

* Update `ContextTest.php` with coverage for the new method

### Visual Regression Changes

* N/A

## QA Brief

* Install a multi-lingual plugin like WPML that makes other languages available under URLs like `https://example.com/de/...` or `https://example.com/ja/...` etc.
* Set up a few languages (3 at least).
* Install experimental mini plugin from [this gist](https://gist.github.com/felixarntz/267580bb4d40ce4503c1250a8c7cc975).
* Check that Site Kit remains connected when navigating from between languages in the admin.

## Changelog entry

* Introduce `googlesitekit_canonical_home_url` filter, allowing (e.g. multilingual) plugins that contextually alter the home URL to fix potential issues with Site Kit.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
QA ✅ 

* Set up WPML with multiple languages using a permalink structure which included the language code in the URL
* Was able to reproduce the disconnect that can happen when toggling between languages in WP Admin
* Enabled experimental plugin leveraging new filter and was unable to reproduce disconnect
