### ISSUE TITLE
Launch user input to everyone instead of having it behind feature flag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2133]
This issue is about making the full user input flow available in production.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `featureFlags.userInput` should be removed. Anywhere where they are used in JavaScript or PHP, they should be removed and only the logic inside of them should be run. The respective `else` (if there was any) should be removed.

**Before merging a PR for this, please confirm with @felixarntz for whether this is okay to be shipped.**

## Implementation Brief

- Edit `stories/setup.stories.js` and `stories/user-input.stories.js` to remove occurrences where `userInput` is enabled.
	- `enableFeature( 'userInput' );`
- Edit `.storybook/config.js` to remove references to `userInput`
- Edit `feature-flags.json` to remove references to `userInput`
- Edit `assets/js/components/user-input/UserInputApp.js` and `assets/js/components/legacy-notifications/index.js` to remove the check if `userInput` is enabled.
- Edit `includes/Core/Authentication/Authentication.php` to remove the check whether `userInput` is not enabled.

### Test Coverage

* No changes to tests.

### Visual Regression Changes

* No visual regressions.

## QA Brief
Check that:
- The userInput feature flag is not enabled in the tester plugin
- The setup User Input component is displayed on the dashboard
- The Your Site Goals component is displayed in admin settings

## Changelog entry

*

**Comment by felixarntz** [comment]
@adamsilverstein FYI the ACs here currently include a `TBD` for the `mode` query parameter value. The eventual value will depend on how we implement this on the service.

**Comment by tofumatt** [comment]
IB ✅

**Comment by sudhanshu16** [comment]
I've raised a PR regarding this issue. Can somebody check #2568, I am not sure how to fix the e2e error. Locally, I get a different error altogether. The IB doesn't mention any changes to the tests but is there anything I am missing?

Thanks for your time.

**Comment by felixarntz** [comment]
@fhollis This one isn't ready for Sprint 41, since we won't be able to roll out the User Input feature in the next release yet. Maybe this accidentally made it in?

cc @johnPhillips See above, this will need to wait a few more sprints before it can be done. Once ready, we should be able to continue with the PR you've already started.

**Comment by felixarntz** [comment]
@eclarke1 @fhollis As mentioned before, this must not be merged, as the user input feature is not ready to launch, let alone launch without a feature flag.

I will move this issue back to ACs so that it remains there until we can actually consider it.

**Comment by tofumatt** [comment]
My understanding is User Input is now rolled out to all users, correct?

Is there any reason to keep this feature flag around or can we move this to execution? The ACs/IB still look largely good to me, so assigning this to @felixarntz to check if it's okay to move out of stalled given the issue text.

If so we should maybe move it to IB to just double-check the IB is still relevant, given this issue is over a year old at this point 😅

**Comment by aaemnnosttv** [comment]
> My understanding is User Input is now rolled out to all users, correct?

@tofumatt no, it hasn't been rolled out to anyone yet. I'm guessing this feature flag will be repurposed for the summary widget which this is planned to be released with.

**Comment by aaemnnosttv** [comment]
Moving this one back for now as it won't be ready for a while yet.
