### ISSUE TITLE
Ensure every module store has a canSubmitChanges selector and submitChanges action

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2136]
So far all Site Kit module stores that support editing settings via their settings panel have a `canSubmitChanges` selector, which checks whether the current client-side settings are valid to be saved, as well as a `submitChanges` action, which actually submits the changes persistently with the server. While these two have been added to stores by convenience so far, going forward it should be ensured that _every_ module store (per using the `createModuleStore` utility) has this selector and action respectively.

Related: #2108

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new utility function `createSubmitChangesStore( options )` in `assets/js/googlesitekit/modules/create-submit-changes-store.js`:
    * Accepts an optional argument `submitChanges`, which needs to be an asynchronous function which receives `registry` as only parameter. The default should be `() => { return {}; }`.
    * Accepts an optional argument `validateCanSubmitChanges`, which needs to be a function which receives `registry.select` as first parameter and `state` as second parameter. The default should be an empty `() => {}`.
    * The function should return a (partial) store with:
        * A `submitChanges` action and related reducers, behaving exactly like existing `submitChanges` implementations in module stores (e.g. `modules/analytics`). The `SUBMIT_CHANGES` control should be a registry control that simply calls the provided `submitChanges` function. That function should then return a result object, with an `error` property if the process failed.
        * A `canSubmitChanges` selector, which is the `safeSelector` created via `createValidationSelector` (see #2108) with the provided `validateCanSubmitChanges` function. That function should then return `true` or `false`.
        * An `isDoingSubmitChanges` selector, which should look at whether the `isDoingSubmitChanges` flag is set in state or not. It should return `true` or `false`.
* `createModuleStore` should be expanded to also include the new optional `canSubmitChanges` and `submitChanges` arguments and based on them include the partial store from `createSubmitChangesStore` in the returned module store. The defaults here should be based on the existing usages and on whether the module has settings:
    * If `settingSlugs` is not set (i.e. there are no settings for the module), the defaults should be the same no-op defaults like in `createSubmitChangesStore`.
    * If `settingSlugs` is set (i.e. there is a settings store as part of the module), the defaults should be:
		**`submitChanges`:**
		```js
		async( registry ) => {
			if ( registry.select( storeName ).haveSettingsChanged() ) {
				const { error } = await registry.dispatch( storeName ).saveSettings();
				if ( error ) {
					return { error };
				}
			}
			await API.invalidateCache( 'modules', slug );
			// TODO: Remove once legacy dataAPI is no longer used.
			invalidateCacheGroup( TYPE_MODULES, slug );
			return {};
		}
		```
		**`validateCanSubmitChanges`:**
		```js
		( select ) => {
			invariant( ! select( storeName ).isDoingSubmitChanges(), 'cannot submit changes while submitting changes' );
			invariant( select( storeName ).haveSettingsChanged(), 'cannot submit changes if settings have not changed' );
		}
		```
* All stores that currently implement `canSubmitChanges` and `submitChanges` should be migrated to removing their actual store implementations and instead passing the respective functions to `createModuleStore`.

## Implementation Brief

* Create `assets/js/googlesitekit/modules/create-submit-changes-store.js` which exports the `createSubmitChangesStore` function as the default, returning:
	- `actions.submitChanges` - essentially the same async action generator that is included in stores today
	-- Should include calls to `clearError` for `submitChanges` at the beginning and by `receiveError` in the `catch` block if an error is called
	- `controls[ SUBMIT_CHANGES ]` - a registry control which calls and returns the result of the provided `submitChanges` function internally
	- `selectors.canSubmitChanges` - set to `createValidationSelector( validateCanSubmitChanges ).safeSelector`
	- `selectors.validateSubmitChanges` - set to `createValidationSelector( validateCanSubmitChanges ).dangerousSelector`
	- `selectors.isDoingSubmitChanges` - returns `true` if `submitChanges` is in progress, otherwise `false`
	- `reducer` - handles changes to `state.isDoingSubmitChanges` from `(START|FINISH|CATCH)_SUBMIT_CHANGES` actions
* Update `create-module-store.js`
	- Accept an optional `submitChanges` function - defaults to function in AC
	- Accept an optional `validateCanSubmitChanges` function - defaults to function in AC
	- Include/combine the store partial from `createSubmitChangesStore` if `settingSlugs` is set (i.e. only if `createSettingsStore` is called) in the returned store
* Update existing stores that use `submitChanges` to pass the the necessary implementations to `createModuleStore`
	- Extract the definition of `baseModuleStore` in `datastore/index.js` to a new `datastore/base.js` module
		- This new module is where the new submit changes functions can be defined and passed to `createModuleStore`
		- The `index.js` only then needs to `import baseModuleStore from './base'` and leave it as the first item in the aggregate store as it is now
	- Tag Manager
		- port `SUBMIT_CHANGES` control to `submitChanges` argument
		- port `canSubmitChanges` logic to validation argument  
		_This will require the least changes as it is already using a validation utility and is the basis for this issue – all other modules should use this as a reference_
	- AdSense
		- default `submitChanges`
		- port existing `canSubmitChanges` to validation argument
	- Analytics
		- port `SUBMIT_CHANGES` control to `submitChanges` argument
		- port `canSubmitChanges` logic to validation argument
	- Optimize
		- default `submitChanges`
		- port existing `canSubmitChanges` to validation argument
* Remove from module data store definitions (`{slug}/datastore/settings.js`):
	- `actions.submitChanges`
	- `selectors.canSubmitChanges`
	- `selectors.isDoingSubmitChanges`
	- `controls[ SUBMIT_CHANGES ]`
	- Related logic in `reducer`

### Test Coverage

* Create `assets/js/googlesitekit/modules/create-submit-changes-store.test.js` to include unit tests for `createSubmitChangesStore`
* Update `assets/js/googlesitekit/modules/create-module-store.test.js` to cover added selectors using defaults and provided values to `canSubmitChanges` and `submitChanges` args
* Update module store tests
	- Add a new `datastore/base.test.js`
	- Move submit-changes related tests to the new module/test-case
	- Update tests for `canSubmitChanges` to use the new `validateSubmitChanges` selector for tests that expect `canSubmitChanges` to return `false` to ensure this is happening for the right reason by making assertions against the error thrown  
	_Again, see Tag Manager for reference_

### Visual Regression Changes

* N/A

## QA Brief

* Make sure Analytics, Optimize, Adsense, and Tag manager modules use the new functionality introduced in the `createSubmitChangesStore` partial store.
* Make sure Analytics and Tag Manager modules use custom `submitChanges` and `validateCanSubmitChanges` functions for `createSubmitChangesStore`.
* Make sure Optimize and Adsense modules use just `validateCanSubmitChanges` function for `createSubmitChangesStore`.
* Go to the settings page and try to edit and save settings for the aforementioned modules. It should work as usual without visual or behavioral changes.

## Changelog entry

* Modify the `createModuleStore` JavaScript function so that every module store has a `canSubmitChanges` selector and a `submitChanges` action.

**Comment by aaemnnosttv** [comment]
@felixarntz I think the definition here could be updated a bit to leverage the new suggested utility in #2108 which is validation-based. We don't want to re-introduce the ambiguity of simple boolean logic here I don't think.

In particular, I think this function should take a `validateSubmitChanges` function, rather than `canSubmitChanges` since the latter can be derived from the former, and we can get the "strict" version at the same time.

So going off your example for the default logic, it might look something like this:

```js
function createSubmitChangesStore( { storeName, ...options } ) {
	invariant( storeName, 'storeName is required.' );
	const defaultValidateSubmitChanges = ( select ) => {
		const { isDoingSubmitChanges, haveSettingsChanged } = select( storeName );
		invariant( ! isDoingSubmitChanges(), 'cannot submit changes while submitting changes' );
		invariant( haveSettingsChanged(), 'cannot submit changes if settings have not changed' ); 
	};
	const defaultSubmitChanges = async ( registry ) => {
		if ( registry.select( storeName ).haveSettingsChanged() ) {
			const { error } = await registry.dispatch( storeName ).saveSettings();
			if ( error ) {
				return { error };
			}
		}
		await API.invalidateCache( 'modules', slug );
		// TODO: Remove once legacy dataAPI is no longer used.
		invalidateCacheGroup( TYPE_MODULES, slug );
		return {};
	}
	const {
		validateSubmitChanges = defaultValidateSubmitChanges,
		submitChanges = defaultSubmitChanges,
	} = options;
	invariant( typeof validateSubmitChanges === 'function', 'validateSubmitChanges must be a function.' );
	invariant( typeof submitChanges === 'function', 'submitChanges must be a function.' );

	// `createValidationSelector` does not exist yet (@see https://github.com/google/site-kit-wp/issues/2108)
	const canSubmitChanges = createValidationSelector( validateSubmitChanges );
	
	return {
		actions: {
			submitChanges: /* TODO */,
		},
		controls: {
			[ SUBMIT_CHANGES ]: createRegistryControl( ( registry ) => ( ...args ) => {
				return submitChanges( registry, ...args );
			} ),
		},
		selectors: {
			// ... 
			canSubmitChanges: canSubmitChanges.safeSelector,
			validateSubmitChanges: canSubmitChanges.dangerousSelector,
			// ...
		},
		
	};
}
```

I realize that's basically the implementation, but I think it helps to see it in context :smile:

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv SGTM - I've updated the ACs, also I'll mark this as blocked by #2108.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@eugene-manuilov Can you still add a QA Brief for this one?

**Comment by eugene-manuilov** [comment]
@felixarntz QA Brief is added.

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

While the ACs are met by the current implementation, there are a few details that seem to have been missed in code review and should be addressed.

Specifically, in the `submitChanges` action of the `createSubmitChangesStore`, as it mixes `yield`ing actions and `dispatch` calls.
Using `dispatch` also requires the `storeName` argument to `createSubmitChangesStore`, but this is unnecessary given the other yielded actions and undesirable that these might be dispatched onto different stores.

Using `dispatch` is unnecessary because the error actions can be yielded directly, as we do in the `createFetchStore`. This isn't anything special about those actions – all actions can be yielded directly, it just requires the raw action objects which are only available from the unbound action creator (or using literals/references). This eliminates the need for `dispatch`, `getRegistry`, and `storeName` which simplifies the action substantially. It also absolves the need to check for the existence of the bound action creator from the result of the `dispatch( storeName )` call.

I'll put together a quick PR to address this as it's mostly a small change.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

As mentioned before, the ACs were already met by the previous implementation, the PR that followed only simplified things and made it more consistent.
