### ISSUE TITLE
Rely on submitChanges and canSubmitChanges in settings components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2137]
Following #2136, every module store now has a `submitChanges` action and a `canSubmitChanges` selector. The legacy `SettingsModule` and `SettingsModules` components should start making use of that.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SettingsModule` (singular) component should be modified:
    * It should receive a `canSubmitChanges` prop via the `withSelect` HOC by selecting `canSubmitChanges( slug )` from the `core/modules` store.
    * The "Confirm Changes" button should be marked as disabled if either `isSavingModule` (like today) or `! canSubmitChanges`.
    * The component should also receive a `submitChanges` function prop via the `withDispatch` HOC from the `core/modules` store.
    * The component should **not be further refactored, or as little as possible**.
    * The `handleEdit` call with `'confirm'` should be expanded to pass the `submitChanges` prop as the third argument.
* The `SettingsModules` (plural) component should be modified to receive `submitChanges` as an optional third parameter to the `handleButtonAction` function, which is only relevant if `action === 'confirm'`
    - Instead of running the `googlekit.SettingsConfirmed` filter, it should call the given `submitChanges( slug )` (if present).
    - If the `submitChanges` call resolves to an object that has an `error` property, the promise should be rejected with that `error` to flow through the `catch` logic, otherwise it should be resolved normally as a successful completion.
    * The component should **not be further refactored, or as little as possible**.
* From every module's `SettingsEdit` component, the `useEffect` usages that toggle the disabled state of the "Confirm Changes" button and that hook in the `googlekit.SettingsConfirmed` filter should be removed, as they are now covered by the above automatically.

## Implementation Brief

* Edit the `assets/js/components/settings/settings-module.js` file:
  * Update `withSelect` HOC to get a `canSubmitChanges` value using the `canSubmitChanges( slug )` selector from the `core/modules` store;
  * Update the `Confirm Changes` button to be switched to disabled state when the `isSavingModule` variable is true or the `canSubmitChanges` property is false;
  * Import [`compose` ](https://github.com/WordPress/gutenberg/tree/master/packages/compose#api)function from the `@wordpress/compose` package and use it to compose HOCs for the `SettingsModule` components;
  * Add [`withDispatch`](https://github.com/WordPress/gutenberg/tree/master/packages/data#withDispatch) HOC that returns `submitChanges` action function from `core/modules` datastore;
  * Update the `Confirm Changes` button to pass `submitChanges` property into the `handleEdit` function call as the third argument when `hasSettings && setupComplete` is true.
* Update the `handleButtonAction` method in the `assets/js/components/settings/settings-modules.js` file:
  * It should receive `submitChanges` as an optional third parameter;
  * It should call `submitChanges( module )` function instead of `googlekit.SettingsConfirmed` filter;
  * Update the logic of the function to work as defined in the AC.
* Update `SettingsEdit` components in modules to remove `useEffect` hooks that add a hook for the `googlekit.SettingsConfirmed` filter.

### Test Coverage

* Adjust existing tests when needed.

### Visual Regression Changes

* No visual changes are expected.

## QA Brief

* Ensure that editing settings in the settings panels on Site Kit's _Settings > Connected Services_ tab still work as expected, specifically around the following:
    * ensure that the submit button changes its "disabled" vs "not disabled" state as before
    * ensure that saving settings works as before, i.e. when changing a setting and then clicking a button, afterwards that value should be saved and the new value should be reflected in the UI
* This should be tested for all modules that have editable settings:
    * AdSense
    * Analytics
    * Optimize
    * Tag Manager

## Changelog entry

* Reduce complexity of implementing and registering `settingsEdit` components for a module by centrally handling setting submission.

**Comment by felixarntz** [comment]
@aaemnnosttv I've opened #2182 as a new dependency for this one, which will simplify the component code / decouple it from the module-specific store. The ACs have been updated accordingly.

**Comment by felixarntz** [comment]
@eclarke1 I'll remove this from Sprint 35 and instead add #2182, which is a new dependency for this one.

**Comment by aaemnnosttv** [comment]
@felixarntz – AC's look good to me. There are some implicit changes which aren't mentioned like the use of `modulePromise` which might simply be replaced with the result of the `submitChanges` call (rather than awaiting it). I think the only change we'd need to make there is accept the value in the `then` callback and throw if `response.error` or return rejected Promise there to hit the `catch`. I think we could change that function to use await though instead, even if it resulted in a few more line changes.

Will be nice to remove another filter (this one must be really old since it's even a `googlekit.` namespace) and all of those workarounds from the new components 👍

**Comment by aaemnnosttv** [comment]
@felixarntz I reworded a few bits in the ACs to clarify a few things; let me know what you think. If you agree, I think this is ready for an IB.

**Comment by felixarntz** [comment]
@eugene-manuilov IB mostly looks good, however I think there's one thing off: The `submitChanges` action needs to be used by `SettingsModules`, not `SettingsModule`. So the `withDispatch` component should only be relevant for `SettingsModules`, and then `@wordpress/compose` isn't needed anymore.

**Comment by eugene-manuilov** [comment]
@felixarntz I have followed the AC which states the following:

> * The SettingsModule (singular) component should be modified:
>   * The handleEdit call with 'confirm' should be expanded to pass the submitChanges prop as the third argument.
> * The SettingsModules (plural) component should be modified to receive submitChanges as an optional third parameter to the handleButtonAction function, which is only relevant if action === 'confirm'

Do we need to update AC then?

**Comment by felixarntz** [comment]
@eugene-manuilov Oh I'm sorry, I somehow misunderstood my own ACs when revisiting 🤦 

This is all good, IB ✅

**Comment by felixarntz** [comment]
@kostyalmm @tofumatt Noticed after merging the PR that it missed some parts of the ACs:
> From every module's `SettingsEdit` component, the `useEffect` usages that toggle the disabled state of the "Confirm Changes" button and that hook in the `googlekit.SettingsConfirmed` filter should be removed, as they are now covered by the above automatically.

The original PR only removed this in the Tag Manager module but not the other modules, and it only removed the `useEffect` taking care of the button action but not the `useEffect` taking care of the button's `disabled` state.

I'll open a follow-up PR.

**Comment by felixarntz** [comment]
I've updated the QA Brief here to test the user-facing flows - this could have unintended side effects, so should go beyond an engineering QA.

**Comment by tofumatt** [comment]
> The original PR only removed this in the Tag Manager module but not the other modules, and it only removed the useEffect taking care of the button action but not the useEffect taking care of the button's disabled state.

Argh, I missed that too 🤦🏻 

Reviewing the new PR now 👍🏻

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

These checks were completed on AdSense, Analytics, Optimize and Tag Manager

- Submit button (Confirmed changes) is deactivated when module settings initially edited.  When a change is made to the settings then the button is activated. - [Screenshot](https://user-images.githubusercontent.com/73545194/99667931-07e12500-2aa8-11eb-979b-93367a5822c2.png)
- When a module setting is changed, it is saved and stored. This is also reflected in the UI.  - [Screenshot](https://user-images.githubusercontent.com/73545194/99668301-81791300-2aa8-11eb-8355-2e163ae1e794.png)
- When editing settings on a module, the other module settings are locked. - [Screenshot](https://user-images.githubusercontent.com/73545194/99668714-0e23d100-2aa9-11eb-9bc2-1afc8bce4632.png)
- Confirmed that all modules can be disconnected from within Connected Services tab. Dialog boxes appear with active disconnect button.  - [Screenshot](https://user-images.githubusercontent.com/73545194/99669140-9bffbc00-2aa9-11eb-91e4-1855b01a09eb.png)
