### ISSUE TITLE
file size to big for upload

### ISSUE THREAD

**Issue by dejandre** [google/site-kit-wp#214]
## Bug Description

The uploaded file exceeds the upload_max_filesize directive in php.ini.

this is on my wp dashboard upload plugin...

**Comment by swissspidy** [comment]
What's the value of `upload_max_filesize` on your server then? For reference, the plugin folder is ~6.8MB in size.

**Comment by jamesozzie** [comment]
@dejandre Close this issue now, as it's not Site Kit specific. If you have any issues changing your PHP `upload_max_filesize` limit your web host provide should be able to assist.
