### ISSUE TITLE
Optimize the size of the generated analytics-advanced-tracking.js file.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#2142]
## Feature Description

#1728 and #2092 introduce the advanced Analytics events tracking API that embeds a javascript file into a page markup. Currently, that javascript file is passed through webpack to correctly transpile its code into a code supported by maintained browsers. The problem with this approach is that webpack blows up the generated file by adding its own code to properly resolve dependencies. We need to find a way how to minify the amount of auxiliary code in the generated file and make it as small as possible.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The production build version of the `assets/js/analytics-advanced-tracking.js` asset should be of minimal size, while still leveraging the benefits of combining imported files into one and transforming modern JavaScript code into old browser-compatible JavaScript code.
    * In particular, we should attempt to minimize all the boilerplate that Webpack includes by default. Usually, this isn't a big concern, but in the frontend where we only use small snippets of JavaScript, it makes the amount considerable.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I think this may be a non-issue after the recent changes added in #2152 ?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv kind of, but there is still webpack boilerplate that we need to try to get rid of.

**Comment by aaemnnosttv** [comment]
Sounds good @eugene-manuilov , just checking if this was still relevant or not 👍

**Comment by kuasha420** [comment]
### IB Investigation Report

Currently, the production `assets/js/analytics-advanced-tracking.js` file is fairly lean and from my understanding, only dead code on that file is the webpack-runtime codes. There's no built in switch completely strip out webpack runtime in webpacl(4?). The only option that doesn't polite the file with  runtime code is `runtimeChunk: true` but it just creates a separate file for runtime. 

I do not think there is any clean way to omit the runtime from being added to the entrypoint without introducing some other tools like gulp/rollup but I am not convinced that this complexity is a worthy trade for the potential kilobytes gain.

Any thoughts will be appreciated.

cc: @eugene-manuilov @aaemnnosttv

**Comment by tofumatt** [comment]
I agree with @kuasha420's analysis on this one; I took a look at the production build of `analytics-advanced-tracking.js` and it's less than 2kb:

<img width="928" alt="Screenshot 2021-09-07 at 21 58 37" src="https://user-images.githubusercontent.com/90871/132410140-aed86e94-25c5-40b5-a0a6-cc2e3577548a.png">

I don't see much Webpack boilerplate in this file, and by the time it's gzipped this file is very, _very_ tiny. I think we can safely close this issue as no longer needed.
