### ISSUE TITLE
Data stores are registered twice

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#2145]
## Bug Description

Data store are all registered twice and duplicated, leading to bugs when they are accessed by their store name—multiple stores with the same name (eg. `'core/user'` exist and cause issues like in #1848).

To reproduce this issue you need the [Redux Devtools extension](https://github.com/reduxjs/redux-devtools) installed.

## Steps to reproduce

1. Go to the Site Kit dashboard
2. Open your browser's developer tools
3. Open the "Redux" panel
4. Click "Autoselect instances" to show the list of data stores and observe multiple stores registered with the same name.

## Screenshots

![2020-10-07 23 12 32](https://user-images.githubusercontent.com/90871/95393852-3a1d3580-08f3-11eb-9271-108623e4ae62.gif)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Only one datastore with each name should appear in the Redux Devtools list
* #1848's QA brief should be consistently reproducible

## Implementation Brief

* Update all datastore index module exports to only `export default store`
	- Remove all `export { STORE_NAME }` exports from all datastore index modules
* Fix all broken imports/references in modules where `STORE_NAME` is imported from a datastore index

### Test Coverage

* The root cause of the issue requires multiple bundles/entry-points to exist which not reproducible in our test environment

### Visual Regression Changes

* N/A

## QA Brief

* All data store tests should still pass after imports are adjusted and `export { STORE_NAME }` are removed.
* All modules where `registerStore` is called should only export the store object

## Changelog entry

* Fix bug where some data stores would be registered multiple times in JS.

**Comment by eugene-manuilov** [comment]
Hm... it's weird but I can't reproduce it anymore... @tofumatt do you know how to reproduce it? I'll keep an eye on it and if I see doubled stores again, I'll spend some time to debug it.

**Comment by tofumatt** [comment]
For me it seems intermittent as well, so it's possible there's a race condition that exists when stores are being registered or something like that. We do have a lot of code that checks for the existence of globals like `googlesitekit.data` and creates them if they're `undefined`. Not sure if some of that is overlapping or something?

**Comment by aaemnnosttv** [comment]
Redux DevTools won't show duplicate stores from the same app in my experience. What you're likely seeing are stores from other tabs.

After digging into this a bit more, I found that _some_ stores are indeed being registered more than once. This is due to the datastore being registered when the index is imported. Normally this wouldn't be a problem since the file should only be imported once; but it isn't 😄  There are a number of places where we import the `STORE_NAME` from the index, instead of the `constants` module. E.g. https://github.com/google/site-kit-wp/blob/3a5b6d9871598791fedf478042f0f150510a474b/assets/js/components/permissions-modal/index.js#L29

Whenever this happens from a source file in a separate entry point, the datastore will be imported causing it to be registered again; once for each additional entry point where it is imported from.

I think the easiest solution here is to not export anything from a store's index module other than the `store` itself which is also [what stores do in Gutenberg](https://github.com/WordPress/gutenberg/blob/de00373601ec1d5a4f11eea0827968696b568637/packages/edit-post/src/store/index.js).

**Comment by tofumatt** [comment]
> Redux DevTools won't show duplicate stores from the same app in my experience. What you're likely seeing are stores from other tabs.

Ah, interesting. That'd explain why @eugene-manuilov and I were having trouble consistently reproducing that bit.

-----

IB ✅ though, sounds good. Thanks for digging into this one. 👍🏻

**Comment by asvinb** [comment]
@aaemnnosttv Thanks for catching that. I've created another PR to fix it. Can you review? thanks!

**Comment by tofumatt** [comment]
Hmmm, looks like there could be a deeper issue here, all related to the automatic registering of stores/side-effects.

There are still other exports in files like: `assets/js/googlesitekit/modules/datastore/index.js`.

See:

* https://github.com/google/site-kit-wp/blob/3571133f387d089c50796748e918b3c50c6136b3/assets/js/googlesitekit/modules/datastore/index.js#L33-L38
* https://github.com/google/site-kit-wp/blob/3571133f387d089c50796748e918b3c50c6136b3/assets/js/modules/adsense/datastore/index.js#L63-L68
* https://github.com/google/site-kit-wp/blob/3571133f387d089c50796748e918b3c50c6136b3/assets/js/modules/analytics/datastore/index.js#L65-L70
* https://github.com/google/site-kit-wp/blob/3571133f387d089c50796748e918b3c50c6136b3/assets/js/modules/search-console/datastore/index.js#L43-L48
* https://github.com/google/site-kit-wp/blob/3571133f387d089c50796748e918b3c50c6136b3/assets/js/modules/tagmanager/datastore/index.js#L82-L89

I'm not sure if we're importing those for use _other_ than in tests, but even so: exporting them creates the implicit notion that it's safe to import them. But that'll cause the registration to happen multiple times.

I think we need a follow-up issue to check if an implicit module registration has occurred and not do it again. If we're to stick with these side-effects, we need to ensure they only happen once.

So I think this is QA ✅, but maybe we want to open a new issue to prevent automatic registration from happening multiple times? What do you think @aaemnnosttv and @felixarntz?

**Comment by tofumatt** [comment]
Filed #2223 as a follow-up.
