### ISSUE TITLE
Fix translation strings that incorrectly combine "last %s" and "%s days"

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2146]
After #1923 and #317, we now have a function called `getCurrentDateRangeDayCount`, which returns the number of days from the current date range. There are several translation strings like "... over the last %s" which are then filled with "%s days", which is problematic because this breaks a single expression into two separate strings - it works in English, but not in most other languages where there are more denominators than "the" :)

Example:
**Incorrect:** `sprintf( __( 'Top content over the last %s' ), sprintf( __( '%s days' ), 28 ) )`
**Correct:** `sprintf( __( 'Top content over the last %s days' ), 28 )`
**Even better:** `sprintf( _n( 'Top content over the last %s day', 'Top content over the last %s days', 28 ), 28 )` (although this is strictly not necessary right now because we never have 1 day)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All translation strings containing "last %s" should be modified to "last %s days" and only fill in the number of days (see `getCurrentDateRangeDayCount`).
* The translation string "Top content over the last 28 days" used in the WP dashboard should be replaced with "Top content over the last %s days", filling in 28, to avoid an unnecessary "duplicate" translation string.
* The function `getCurrentDateRange` should be removed (all its usages should be replaced by the above).

## Implementation Brief

* Update https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidget.js#L210 to use:

```js
const currentDateRange = getCurrentDateRangeDayCount();
sprintf( _n( 'Performance over the last %s day', 'Performance over the last %s days', currentDateRange ), currentDateRange )
```

* Make a similar change, using `sprintf( _n() )`-style translations, for:
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/common/AcquisitionSources.js#L84
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/common/AcquisitionSources.js#L89
 * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/dashboard/AnalyticsAdSenseDashboardWidgetLayout.js#L43
 * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidget.js#L190
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidget.js#L221
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidget.js#L243
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopAcquisitionSources.js#L69
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopAcquisitionSources.js#L74
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/search-console/components/dashboard/GoogleSitekitSearchConsoleDashboardWidget.js#L199
  * https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/modules/search-console/components/dashboard/GoogleSitekitSearchConsoleDashboardWidget.js#L223
  * Update https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/util/date-range.js#L90 to use a `sprintf( _n() )`-format translation as well.
* Update an `/* translations: */` help comments to reflect the new translation format where appropriate

### Test Coverage

* 

### Visual Regression Changes

* There should be none, as the only text changes are for date range values of `1`, which we don't currently have.

## QA Brief

* All "In the last X days" time strings should still function properly in English and other locales—although other translations may not be immediately available after merging if the strings update.

## Changelog entry

* Fix a few translation strings that were concatenating date ranges, making them correctly translatable.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@tofumatt IMO the estimate seems a bit high at 7, since this is only copy changes. It's a bunch but I would guess this is closer to a 3 - what do you think?

**Comment by tofumatt** [comment]
QA ✅

All translations look good 👍🏻
