### ISSUE TITLE
Data error in Search Console

### ISSUE THREAD

**Issue by RogersSteffan** [google/site-kit-wp#215]
## Steps to reproduce

1. Go to 'Site Kit'
2. Click on 'Search Console'
3. See error in screenshot, "Data error in Search Console
User does not have sufficient permission for site 'https://www.vegavitamins.co.uk/'. See also: https://support.google.com/webmasters/answer/2451999." As I am a verified owner of the account, I should have all the permissions.

## Screenshots

![Capture2](https://user-images.githubusercontent.com/52779202/61037572-3e426680-a3c3-11e9-91e4-9c419e342419.PNG)

## Additional Context

 - PHP Version: 7.0.33
 - OS: Windows
 - Browser: chrome
 - Plugin Version 1.0.0-beta.1.0.1
 - Device: Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@RogersSteffan Thanks for reporting. As you are the owner of the property from with Search Console lets try troubleshoot further. First do you mind sharing and [console errors](https://i.imgur.com/f5WfLb3.png).

Next do you mind resetting Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit). After that please activate Site Kit again but in an [incognito window](https://i.imgur.com/ALzgiHp.png). During the verify stage please ensure you use the same Google account which is the property owner from within Site Kit.

**Comment by jamesozzie** [comment]
@RogersSteffan Did you manage to attempt installing and activating Site Kit again?

**Comment by cre8tivediva** [comment]
I have a client experiencing this issue. She just reported it. It looks normal when I sign it, but for her it doesn't. Could this be because I am connected as a "user" and connected the plugin? Should we disconnect and have the "owner" connected to the plugin?

**Comment by jamesozzie** [comment]
@cre8tivediva If you want to raise a new issue we can look into this for you. Please include all relevant details, and check to ensure if you already have Search Console setup that you have applied all access permissions to the same Google account for that user.

**Comment by drawcard** [comment]
I am having this problem, I went through the onboarding process and I was made an owner for my domain, via HTML verification. However I can't see any data coming from Search Console via the plugin, getting the same errors. I have tried uninstalling and reinstalling the plugin.

![image](https://user-images.githubusercontent.com/1435638/72227660-594e9700-35ef-11ea-9a76-d19e0db041f9.png)
