### ISSUE TITLE
Enforce CTA acronym to be capitalized and fix violations

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2150]
Via #1493, ESLint now flags violations of our rule that acronyms should be capitalized. The list of the acronyms to check is manually maintained based on what we're generally using. One acronym missing from there is `CTA`, which we in some places use incorrectly as `Cta` within variable and prop names.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `CTA` should be one of the acronyms required to be capitalized by the `camelcase-acronyms` ESLint rule.
* All violations to that rule should be fixed, including prop renamings throughout the codebase where needed.

## Implementation Brief

* Add `CTA` as to list of `acronyms` variable in `packages/eslint-plugin/rules/camelcase-acronyms.js`.
* Run ESLint throughout the codebase.
* Fix all flagged violations (e.g. by renaming `footerCtaLink` to `footerCTALink`).

### Test Coverage

* 

### Visual Regression Changes

* N/A

## QA Brief

- No visual changes should occur as a result of these changes.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ShubhamPalriwala** [comment]
I'd like to resolve this issue if it is open !

**Comment by tofumatt** [comment]
QA ✅

Tried a variable with `Cta` and it failed, as expected 👍🏻
