### ISSUE TITLE
Outlook do is no't received e-mail the verification to enter the website. [YOU NEED THE ONE CELL]

### ISSUE THREAD

**Issue by bruno-hashimoto** [google/site-kit-wp#2155]
## Bug Description

Outlook do is no't received e-mail the verification to enter the website but you can solve with your mobile.

## Steps to reproduce

1. Go to ' go to your mobile and access www.github.com.br with the mobile version. (If do not appear, decrease zoom the navigation.'

2. Click on 'setting and change your e-mail to gmail or any '

3. Enter your PC or Notbook and access again.

4. Success.

**Comment by jamesozzie** [comment]
@bruno-hashimoto If you have a query in relation to the Site Kit WordPress plugin feel free to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue.

**Comment by bruno-hashimoto** [comment]
> @bruno-hashimoto If you have a query in relation to the Site Kit WordPress plugin feel free to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue.

Hi man, thanks for answer. I did not know where post this information. 

Really this information is not a question, is a solution. 

(sorry, my inglish is bad).
