### ISSUE TITLE
when click GET OAUTH CREDENTIALS i get field [project_id] has issue [project_id contains invalid characters]

### ISSUE THREAD

**Issue by saalgu** [google/site-kit-wp#216]
when click GET OAUTH CREDENTIALS i get field [project_id] has issue [project_id contains invalid characters]

**Comment by jamesozzie** [comment]
@saalgu Thanks for reporting. Do you mind trying the steps below so we can troubleshoot further?

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png)
3. Temporarily deactivate your other active WordPress plugins
4. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
5. Install Site Kit in a new incognito window (so Chrome extensions don't interfere and caching inactive)

Let me know if the above works. Very important to check in an incognito window also, AdBlockers can also sometimes cause interference during setup.

**Comment by jamesozzie** [comment]
@saalgu Did you have any luck progressing with the Site Kit installation? If you are encountering the same issue with verification you can generate your own verification code using the steps below:

1. Follow the steps you previously followed to get the "Couldn't create project" error
2. Close the "Couldn't create project" window
3. In the address bar of your window paste the following in:
4. https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
5. Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
6. Press enter, with your cursor in the address bar (as if you are visiting that URL)
7. Press the "GET OAUTH CREDENTIALS" button
8. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

An alternative is to also change the language of wordpress to English US before changing your "Site Title" and "Tagline" to English from the settings menu.
