### ISSUE TITLE
Fix broken AdSense Storybook stories

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2161]
Several AdSense setup Storybook stories recently broke via some change, rendering no actual component content, e.g.:
<img width="1519" alt="Screenshot 2020-10-12 at 15 25 49" src="https://user-images.githubusercontent.com/3531426/95797302-069c2b80-0ca4-11eb-9f3b-818c8daac056.png">

The following stories are affected:
* No account
* No account (existing tag)
* Disapproved account

The only issues recently modifying the AdSense `SetupMain` component are #1919 and #2033, potentially one of them caused this somehow.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense setup Storybook stories "No account", "No account (existing tag)", and "Disapproved account" should show the expected UI as before (instead of not rendering any actual content inside the setup wrapper.

## Implementation Brief

* Make sure that all calls to the `receiveError` action in the `stories/module-adsense-setup.stories.js` file have three parameters: error object, action name, and an array of arguments used for the action call (or just an empty array if an action has been called without arguments).

### Test Coverage

* Not needed

### Visual Regression Changes

* Not needed

## QA Brief

* Start storybook and open `AdSense Module / Setup` stories. Make sure all stories display appropriate content that is relevant to the story's name.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
