### ISSUE TITLE
Update deprecated `set-env` use in GitHub Actions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2162]
## Bug Description

Certain actions recently started raising warnings about deprecated use ([example run](https://github.com/google/site-kit-wp/actions/runs/304019610))

> The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Currently the only workflow which uses this is the Storybook workflow. We should either upgrade the usage to use the [new file-based method](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable) or use an [output parameter](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) instead.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `set-env` command should no longer be used in GitHub Actions

## Implementation Brief

* Update workflow files to use `set-output` instead of `set-env` commands.

### Test Coverage

* Not needed

### Visual Regression Changes

* Not expected

## QA Brief

* Check that all workflow actions pass successfully.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
QA ✅
