### ISSUE TITLE
Cannot read property 'isSecondAdmin' of undefined dashboard error

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2166]
## Bug Description

A user in the WordPress support forums encountered the following dashboard error:
`Cannot read property 'isSecondAdmin' of undefined dashboard error`

Unknown at what stage this occurs, or whether Site Kit has worked for this user previously. Domain possibly https://l0l0l.io/ based on users WP profile. 

## Additional Context

 - [WP Support Topic](https://wordpress.org/support/topic/site-kit-encountered-an-error-9/) (no additional information provided)
- Dashboard error may appear during compatibility check during setup looking at error notice

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@cole10up Escalating to L1 for review in the event you're familiar with this issue. 

Unable to reproduce from support side. Attempted trying to setup SK consecutively from two administrator accounts although only encounter "Client credentials don't exist" notice.

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest SK as multiple administrators. 

Unable to reproduce this issue. Setting to closed.
