### ISSUE TITLE
Unhandled promise rejections don't cause tests to fail

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2168]
## Bug Description

Due to the asynchronous nature of the datastore, some tests are capable of having functions finish their execution after the test has completed. This can result in unhandled promise rejection warnings in the console between tests. Because this happens between tests, and also because it is probably being written to stdout/stderr directly, our `jest-console` mocks to fail tests on unexpected console messages won't catch this either.

If you scan the output from a Jest run, you will see output like this scattered throughout in a few places:
```
(node:58626) UnhandledPromiseRejectionWarning: Invariant Violation: properties must be an array.
(node:58626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This particular error is happening due to an `invariant` call that fails the assertion but "gets away with it" due to its use in an async call. In order for these to cause a test failure, they need to be called synchronously, or we need to `await` the promise in the test. There are a few places in our tests where we aren't doing this properly and so a few of these errors have managed to linger around.

There are quite a few issues on the Jest repo about this, but https://github.com/facebook/jest/issues/5311 seems to be a good one for anyone new to the problem.

## Steps to reproduce

1. Run `npm run test:js`
1. See one or more `UnhandledPromiseRejectionWarning`s in the console output on completion even with all tests passing

## Screenshots

**On Travis**
![image](https://user-images.githubusercontent.com/1621608/95906264-9a542180-0da2-11eb-92f6-6dd35a4c5a1d.png)

**Locally**
![image](https://user-images.githubusercontent.com/1621608/95906296-a213c600-0da2-11eb-977d-824c035cc4c9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No `UnhandledPromiseRejectionWarning` should be raised by Jest tests (`npm run test:js`)
* Tests raising an `UnhandledPromiseRejectionWarning` should cause a test to fail when possible

## Implementation Brief

* Add minimal asynchronous wait after each test in global setup
* Fix failing tests due to existing unhandled rejected promises causing test failures
* Merge #2169 

### Test Coverage

* No additional coverage needed

### Visual Regression Changes

* N/A

## QA Brief

* Checkout a20b0bf267939d3cb88bcebe79b49edf9925c559 and run `npm run test:js`
* See tests that were previously raising `UnhandledPromiseRejectionWarning`s (hard to see without singling them out) are now failing
* Checkout latest to see that no `UnhandledPromiseRejectionWarning`s are raised, and no tests are failing

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

Moved right into Merge Review, as I reviewed the PR as well.

**Comment by cole10up** [comment]
**Tested**

Built the latest develop version of SK, ran - confirmed all tests passed and no UnhandledPromiseRejectionWarning were seen
![image](https://user-images.githubusercontent.com/57115907/96221977-51d26a80-0f40-11eb-89de-084740ab6afb.png)

Passed QA ✅
