### ISSUE TITLE
Images load inconsistently in VRT causing CI job failures

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2172]
## Bug Description

Images in Storybook generally render just fine when using locally. However, when used in combination with Backstop for VRT, recent reports show images not loading is the most common cause for a scenario failure, requiring the job to be re-run - after which it usually passes.

This may have something to do with configured timing for backstop or a race condition with images loading and the backstop ready event.

## Steps to reproduce

This seems to be specific (or at least substantially more likely) to conditions when run in CI

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/96102426-2e2b0800-0edf-11eb-840d-c4f2f17bd3db.png)

![image](https://user-images.githubusercontent.com/1621608/96102343-1c496500-0edf-11eb-93ed-3595a54e6d18.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* BackstopJS should wait until all images have loaded (if any) before capturing screenshots

## Implementation Brief

* Update Storybook's `preview-head.html` which is responsible for signaling BackstopJS that it is ready via console.log to trigger this ready only after the `load` event, and all images have finished loading (if any)
* Merge #2173 

### Test Coverage

* N/A

### Visual Regression Changes

* Hopefully it should have no more false-positive failures! 😄 

## QA Brief

* This is hard to QA outside of CI as this is where the problem is reproducible (although not with 100% consistency)

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

Code reviewed as well; in merge review now.

**Comment by aaemnnosttv** [comment]
This one still has issues which seem to be unrelated to the new changes, so I'm bringing it back for another pass.

**Comment by tofumatt** [comment]
(Leaving this in CR as I assume you want both @felixarntz and I to have a look, but if you assigned to both just so whoever saw this first would review it—feel free to merge 😄)

**Comment by eugene-manuilov** [comment]
Moving this issue back to the CR column and assigning it to @aaemnnosttv to review #2213.

**Comment by tofumatt** [comment]
QA ✅

(As mentioned, it's tough to QA this locally, but we'll watch the CI for improvements. I ran it locally and it was fine, but that's to be expected…)

**Comment by aaemnnosttv** [comment]
VRT has been stable since merging the last PR so that's a very good sign 😄  🤞
