### ISSUE TITLE
Refactor trivial class-based components to functional components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2178]
All class-based components in `assets/js/components` which only contain a `render` method without outside data access should be migrated to functional components.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following (trivial) class-based components should be refactored to functional components:
    * `Link`
    * `MiniChart`
    * `PreviewBlock`
    * `PreviewBlocks`
    * `PreviewTable`
    * `ProgressBar`
    * `SignIn`
    * `SourceLink`
    * `Sparkline`
    * `Spinner`
* All their files should be renamed so that the file names match the component names, and all import references should be updated accordingly.
* The `assets/js/components/colors.js` file should be removed, and the variable inside should be used directly in the `MiniChart` component, which is the only component using it.

## Implementation Brief

* Remove `assets/js/components/colors.js`, moving its contents directly into `assets/js/components/mini-chart.js`.
* Change `assets/js/components/link.js` to `assets/js/components/Link.js`.
* Change `assets/js/components/sparkline.js` to `assets/js/components/Sparkline.js`.
* Change `assets/js/components/spinner.js` to `assets/js/components/Spinner.js`.
* Change `assets/js/components/mini-chart.js` to `assets/js/components/MiniChart.js`. Do the same for the rest of these components, using a filename that exactly matches the ComponentName in all filenames:
    * `MiniChart`
    * `PreviewBlock`
    * `PreviewBlocks`
    * `PreviewTable`
    * `ProgressBar`
    * `SignIn`
    * `SourceLink`
* Change the above components to function components from class-based components along with updating their filenames and imports (note that VSCode will auto-update imports for you, if you use it and have that setting enabled):
<img width="686" alt="Screenshot 2020-10-16 at 22 28 21" src="https://user-images.githubusercontent.com/90871/96310246-e8656100-0ffe-11eb-81fa-54e5f68d4f60.png">

### Test Coverage

* No additional tests needed.

### Visual Regression Changes

* There should be no change to visuals.

## QA Brief

* Ensure setup and settings pages especially continue to work normally, as much of the refactored components are used there.
* Ensure Analytics dashboard's charts have not changed from this refactor.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
