### ISSUE TITLE
Confirm Your Choices - Clicking on Allow

### ISSUE THREAD

**Issue by IanBeacon** [google/site-kit-wp#218]
## Bug Description

When setting up upon clicking on the Allow button when confirming my choices I get taken to the homepage of the website

## Steps to reproduce

1. After creating Client Id and moving to the Authenticate section
2. From the SiteKit Dashboard from within WordPress admin click on 'Sign In WIth Google'
3.  Choose Account
4. Allow, Allow
5.  Confirm Your Choices> ~Clicking Allow takes me to the websites homepage.

## Additional Context

 - PHP Version:  7.1.3.0
 - OS: Windows 10
 - Browser: Chrome
 - Plugin Version 1.0.0
 - Device: PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@IanBeacon Can you please form the following steps: 
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png)
3. Temporarily deactivate your other active WordPress plugins
4. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
5. Install Site Kit in a new incognito window (so Chrome extensions don't interfere and caching inactive)

Let me know if the above works, if not we can troubleshoot further.

**Comment by mjcombe** [comment]
I have same issue, returns to home page, upon checking Site Kit Dashboard the Verify URL is still greyed out.

**Comment by jamesozzie** [comment]
@IanBeacon Did you try the suggestions above, all 5 steps? A plugin in particular could be impacting this issue, but let me know after you check. If it works it would be great to know what plugins you had active.

**Comment by mjcombe** [comment]
> @IanBeacon Did you try the suggestions above, all 5 steps? A plugin in particular could be impacting this issue, but let me know after you check. If it works it would be great to know what plugins you had active.

Yeah I have tried those steps and had all plugins deactivated but still no joy. Frustrating.

**Comment by jamesozzie** [comment]
@mjcombe Can you share any [console errors](https://i.imgur.com/f5WfLb3.png) you are seeing?

**Comment by mjcombe** [comment]
There aren't any, once I click to confirm choices it goes back to my home page with a different url.

I have just tried on another domain and the same.

I go back to the Site Kit and step 3 is greyed out.

**Comment by mjcombe** [comment]
This is the string after my url

?oauth2callback=1&code=4%2FgwHhccRvGt8q4-3r53igeosZJGIVZu_LGZKVNEoSafKp4RDiN2GdRrzeeDfaggTmZqTxr9bBKbHNAuk7OGAx4Qc&scope=email%20profile%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification&authuser=0&session_state=12646b1faeaef9483657863e35cff8f370224258..958b&prompt=consent

**Comment by jamesozzie** [comment]
@mjcombe Are you using iThemes security, or do you have any additional security or Firewall software in use, not directly on your WordPress site? Is it possible also you can test with an alternative theme (again in incognito mode?).

**Comment by IanBeacon** [comment]
> @IanBeacon Can you please form the following steps:
> 
> 1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
> 2. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png)
> 3. Temporarily deactivate your other active WordPress plugins
> 4. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
> 5. Install Site Kit in a new incognito window (so Chrome extensions don't interfere and caching inactive)
> 
> Let me know if the above works, if not we can troubleshoot further.

I've tried all of the 5 steps above and I am still having the same problem.

**Comment by IanBeacon** [comment]
> @mjcombe Are you using iThemes security, or do you have any additional security or Firewall software in use, not directly on your WordPress site? Is it possible also you can test with an alternative theme (again in incognito mode?).

Fixed!!!  Disabled modsec in cPanel and it is now working.

**Comment by jamesozzie** [comment]
@IanBeacon Great news, and thanks for letting us know. Did you re-enable the ModSecurity module after setting up, with everything working fine?

**Comment by mjcombe** [comment]
I have spoken with my hosting company as I could not see this option in cPanel and they do not offer it....?

**Comment by jamesozzie** [comment]
@mjcombe Do you have any AdBlocker installed? It would be great if you could test on another computer also.

**Comment by mjcombe** [comment]
> @mjcombe Do you have any AdBlocker installed? It would be great if you could test on another computer also.

Tested on another computer in a different location with no plugins and incognito.

Same issues, just flips back to my own website and url not verified.

**Comment by jamesozzie** [comment]
@mjcombe Thanks for checking. Can you share the following information:
- Active theme in use
- PHP version (Preferably a screenshot of your PHP settings)
- WordPress version & site Kit version

If you want to share your site also I can check if I can see anything from my side. Your theme might also have some security features of additional plugins.

**Comment by mjcombe** [comment]
SiteKit 1.0.0-beta.1.0.1
WordPress 5.2.2 running OceanWP theme.
Running PHP version: 7.2.19
[https://ne1webdesign.co.uk/](url)

**Comment by jamesozzie** [comment]
@mjcombe I am unable to recreate the same issue using that theme. Were you previously, or at present using MonsterInsights or iThemes security? Let me know of any security or firewall plugins you have been using.

**Comment by mjcombe** [comment]
> @mjcombe I am unable to recreate the same issue using that theme. Were you previously, or at present using MonsterInsights or iThemes security? Let me know of any security or firewall plugins you have been using.

I disabled iThemes security from the start. No other security as far as I'm aware and have connected to  GA without any issues. Thanks.

**Comment by jamesozzie** [comment]
@mjcombe Can you uncheck this box in your iThemes security plugin:
_"Limits the number of characters that can be sent in the URL."_

Then please check again, you might need to disconnect the Analytics module first. (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)

**Comment by mjcombe** [comment]
> @mjcombe Can you uncheck this box in your iThemes security plugin:
> _"Limits the number of characters that can be sent in the URL."_
> 
> Then please check again, you might need to disconnect the Analytics module first. (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)

I have iThemes disabled.

There are no setting fro Site Kit - only a Dashboard...

**Comment by mjcombe** [comment]
I've spent too much time on this now, think I will wait for a more stable version to come out then try again. Thanks :(

**Comment by IanBeacon** [comment]
> I've spent too much time on this now, think I will wait for a more stable version to come out then try again. Thanks :(

I'm 99% sure your problem is ModSecurity.  I would go back to your hosting company and ask them to look at it again.

**Comment by jamesozzie** [comment]
Closing this issue now with @ianbeacon having connected successfully

@mjcombe There have been plugin updates since you reported issue. Feel free to raise a new issue with any console errors if you are encountering the same redirection issue.
