### ISSUE TITLE
Add `getModuleDependantNames` and `getModuleDependencyNames` selectors

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2180]
The `core/modules` store should receive new selectors that expose the list of module names that are dependencies / dependants of a given module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/modules` store should have a new selector `getModuleDependencyNames( slug )`:
    * It should return an array of module names that are `dependencies` of the module identified by the given `slug`.
    * If modules haven't loaded yet, it should return `undefined`.
    * If the module doesn't exist or doesn't have any dependencies, it should return an empty array.

* The core/modules store should have a new selector `getModuleDependantNames( slug )`:
    * It should return an array of module names that are `dependants` of the module identified by the given `slug`.
    * If modules haven't loaded yet, it should return `undefined`.
    * If the module doesn't exist or doesn't have any dependants, it should return an empty array.

## Implementation Brief

* In  `assets/js/googlesitekit/modules/datastore/modules.js`, add the new `getModuleDependencyNames` selector to the `baseSelectors` object.
* The selector should leverage `createRegistrySelector`  and accept `slug` as a parameter ( see `isModuleActive` as an example )
* Retrieve the module via `geModule(slug)`
	* If the returned module is not loaded ( `undefined` ), return `undefined`
	* If the module is not found( `null` ) return an empty array
	* If there are `dependencies`, return an array of module names based on the slugs in the array, looking up the module by its slug in the store.
* 
* In  `assets/js/googlesitekit/modules/datastore/modules.js`, add the new `getModuleDependantNames` selector to the `baseSelectors` object.
* The selector should leverage `createRegistrySelector`  and accept `slug` as a parameter ( see `isModuleActive` as an example )
* Retrieve the module via `geModule(slug)`
	* If the returned module is not loaded ( `undefined` ), return `undefined`
	* If the module is not found( `null` ) return an empty array
	* If there are `dependants`, return an array of module names based on the slugs in the array, looking up the module by its slug in the store.

### Test Coverage

* Add related tests to `modules.test.js`

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

* Add selectors `getModuleDependencyNames` and `getModuleDependantNames` to `core/modules` store.

**Comment by felixarntz** [comment]
@ryanwelcher Looks like you accidentally removed part of the ACs? See the original content of the ACs, which has a second overarching bullet point (we also need a `getModuleDependantNames` selector), which is also missing from the IB.

> Return `module.dependants` which should be an array of dependencies or an empty array.

This needs to be `module.dependencies` instead of `module.dependants` (for this selector, the other selector needs to look at `module.dependants`). Furthermore, this shouldn't just return that value, it should instead return the module **names** (`module.dependencies` is an array of module slugs) - looking the module names up by slug from the store.

**Comment by ryanwelcher** [comment]
@felixarntz my apologies! I have added the missing AC portion back and updated the IB. Please let me know if there is anything further I should change.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
