### ISSUE TITLE
Add actions and selectors for centrally checking module settings submission state

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2182]
The `core/modules` store should provide a central management layer for handling submission of module settings (which is generally handled in each module's own store, see #2136). Note while #2136 has the goal of every module store providing these actions and selectors, that issue is _not_ a dependency. The code here should work regardless of whether the module store has the action/selector or not.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/modules` store should receive a registry selector `canSubmitChanges( slug )` that checks for store `modules/${ slug }` for whether it exists and has a `canSubmitChanges` selector. If yes, it should return that one's result. Otherwise, it should return `false`.
* The `core/modules` store should receive a registry selector `isDoingSubmitChanges( slug )` that checks for store `modules/${ slug }` for whether it exists and has a `isDoingSubmitChanges` selector. If yes, it should return that one's result. Otherwise, it should return `false`.
* The `core/modules` store should receive an action `submitChanges( slug )` that via a registry control checks for whether store `modules/${ slug }` exists and whether it has a `submitChanges` action. If yes, it should dispatch that action and return the result. Otherwise it should return an object with a single `error` property, similar to how the `submitChanges` action (see #2136) would if an error happened.

## Implementation Brief

* Add a new file to the `core/modules` datastore: `assets/js/googlesitekit/modules/datastore/changes.js`. The actions/selectors/etc. described below should be added to this file.
* Add a new `canSubmitChanges( slug )` registry selector that returns <code>!! select( \`modules/${ slug }\` ).canSubmitChanges && select( \`modules/${ slug }\` ).canSubmitChanges();</code>.
* Add a new `isDoingSubmitChanges( slug )` registry selector that returns <code>!! select( \`modules/${ slug }\` ).isDoingSubmitChanges && select( \`modules/${ slug }\` ).isDoingSubmitChanges();</code>.
* Add a new `submitChanges( slug )` action with an associated registry control that:
  * Checks for the existence of <code>registry.dispatch( \`modules/${ slug }\` ).submitChanges</code>
  * If the action exists: dispatches <code>registry.dispatch( \`modules/${ slug }\` ).submitChanges()</code> and returns its result.
* If the action doesn't exist, return an object with the shape: <code>{ error: \`'modules/${ slug }' does not have a submitChanges() action.\` }</code>

### Test Coverage

* Add relevant tests for these selectors/actions to `assets/js/googlesitekit/modules/datastore/changes.test.js`
  * Check for a slug that does not exist/is not defined for each selector (`select( 'core/modules' ).canSubmitChanges( 'not-a-real-slug' )` should not error, but instead return `false`)
  * Check for a slug that does not exist/is not defined in actions (`registry.dispatch( 'core/modules' ).submitChanges( 'not-a-real-slug' )` should return an error)
  * Check that normal operation of the selectors/actions as described above works as-expected.

### Visual Regression Changes

* None.

## QA Brief

* All relevant new tests should run; no other QA needed.

## Changelog entry

* Add selectors `canSubmitChanges` and `isDoingSubmitChanges` and action `submitChanges` to `core/modules` datastore.

**Comment by felixarntz** [comment]
@tofumatt IB ✅ 

I just think that `assets/js/googlesitekit/modules/datastore/changes.js` is a bit _too_ generic of a name - maybe we should call the file `submit-changes.js` or `settings.js` (the latter is the file name we also use for those selectors and actions in each module store)?

**Comment by tofumatt** [comment]
QA ✅
