### ISSUE TITLE
Refactor `SettingsModule` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2183]
The `SettingsModule` component should be refactored to be a functional component, relying fully on the datastore. It should be split into sub-components where it makes sense.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SettingsModule` component should be refactored into a new functional, hook-based, datastore-driven `SettingsActiveModule` component (the file should also be renamed to match the component name).
* The new component should be only for the use-case that the module is already active, so it can assume that. For the scenario where previously `SettingsModule` was also rendered for the inactive modules (see now `SettingsInactiveModules` as of #2184), that component should now use the existing `SetupModule` component directly, which the current `SettingsModule` component simply wraps. Further refactoring of the _inactive_ module settings component should not be necessary.
* The `SettingsActiveModule` component should now entirely rely on module data from the datastore (`getModule` selector based on the `slug` prop) instead of using the `getModulesData()` legacy function.
* In general, it should no longer use _any_ legacy functions, e.g. module deactivation should also happen via the datastore.
* The `SettingsActiveModules` component should be updated accordingly, if needed (those changes should be minimal though since its refactoring should already be completed when defining this issue, see #2184).
* The following now unused legacy functions should be removed:
    * `getReAuthURL`
    * `activateOrDeactivateModule`
    * if anything else comes up as unused during IB / execution, it should be removed too

## Implementation Brief
* Rename `SettingsModule` component from `/assets/js/components/settings/settings-module.js` to `SettingsActiveModule` component and rename file accordingly.
* Refactor `SettingsActiveModule` to be a functional component with the following changes:
	* Legacy functions such as `getReAuthURL` and `activateOrDeactivateModule` should removed in favour of querying the module data store.
	* To get the auth URL, query the data store like this:
		```js
		const moduleStoreName = useSelect( ( select ) => select( CORE_MODULES ).getModuleStoreName( slug ) );
		const adminReauthURL = useSelect( ( select ) => select( moduleStoreName )?.getAdminReauthURL() );
		```
	* The `getDependentModules` should be removed in favour of getting the module dependants like this:
		```js
		const dependents = useSelect( ( select ) => select( CORE_MODULES )?.getModuleDependantNames( slug ) );
		```
	* Since all modules are assumed to be active, the `activateOrDeactivate` function can be simplified and possibly renamed to use `deactivateModule` function which can be imported as such:
		```js
		const { deactivateModule } = useDispatch( CORE_MODULES );
		```
	* From the examples above, `useDispatch` and `useSelect` can be imported as such:
		```js
		const { useSelect, useDispatch } = Data;
		```
* Review unused variables used throughout the component. For e.g the `isSaving` state variable is not used anywhere.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* Make sure that settings for active modules work the same as in the latest production version.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QA Brief?

**Comment by eugene-manuilov** [comment]
Added.

**Comment by wpdarren** [comment]
@eugene-manuilov I am wondering if you could clarify a little bit more about what you mean by `Make sure that settings for active modules work the same ` in the QAB.  Do you mean, test to make sure that settings can be changed and saved, or do we need to go into more detail with making sure that the settings actually function as expected when changed?

**Comment by eugene-manuilov** [comment]
@wpdarren I mean that all functionality should be re-tested because underlying setting components have been completely reworked.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Checked to make sure the same settings appear between develop and latest release for all modules. 
- Went through each module and made sure that the settings behaved the same as latest release, i.e. settings saved, fields behaved the same, i.e. could be made active and deactivate them. 
- Tested the behaviour of the individual settings and made sure they functioned as expected.

**Comment by aaemnnosttv** [comment]
@wpdarren – would you please take another look at this? It seems module deactivation is not working as expected now for some modules. For modules with a dedicated page, after deactivating you end up on the module page and with an error on the screen. Can you confirm?

![image](https://user-images.githubusercontent.com/1621608/115382825-cb902d00-a1dd-11eb-95a1-19d352a583a8.png)

**Comment by wpdarren** [comment]
@aaemnnosttv sure, I certainly did not see that when testing, but will set up a test site and take another look.

**Comment by wpdarren** [comment]
@aaemnnosttv the message does appear when you try and disconnect a module, i.e. Analytics.  Bit baffled because I am pretty confident that I tested this, but yes you are right, this is an issue. 

![image](https://user-images.githubusercontent.com/73545194/115545832-2b4d0d80-a29c-11eb-8bae-4e80d487fc8f.png)

**Comment by felixarntz** [comment]
@aaemnnosttv The most severe issue right now is that this redirects to `/wp/wp-admin/admin.php?page=googlesitekit-module-analytics&slug=analytics&reAuth=false` now when it should redirect to the Site Kit dashboard instead.

The other issue about the settings UI showing up again is related to us not waiting for the redirect as it should happen. We don't necessarily need to cater for that throughout all of Site Kit's settings page UI, however the disconnect dialog should definitely remain open all the way until the user lands back on the Site Kit dashboard. So we'll probably need to use the `isNavigating` selector here.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**  

- Activated all modules on Site Kit, and then deactivated them one-by-one in the Settings.  All modules redirected back to the dashboard after clicking on the disconnect button. The issue [reported above](https://github.com/google/site-kit-wp/issues/2183#issuecomment-823985934) is also fixed. 

https://user-images.githubusercontent.com/73545194/115694692-02d71900-a359-11eb-920b-770fec52aca5.mov
