### ISSUE TITLE
Remove `SettingsModuleHeader` component and related CSS

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2185]
The `SettingsModuleHeader` component is unused. We should remove it and all CSS that only applies to markup from that component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The unused `SettingsModuleHeader` component should be removed.
* All CSS rules that apply to markup/classes that is only output by that component should be removed.

## Implementation Brief

- Remove the following files:
  - `/assets/js/components/settings/settings-module-header.js`
  - `/assets/sass/components/settings/_googlesitekit-settings-module-header.scss`

Update `/assets/sass/admin.scss` to remove the following import: `@import "components/settings/googlesitekit-settings-module-header";`

### Test Coverage

* 

### Visual Regression Changes

* No changes

## QA Brief

* No visual regression changes
* All unit tests pass.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@asvinb IB ✅ 

Maybe this would be one of the rare cases where we should use the 1 estimate? Let's keep in mind that estimate exists for a reason, and while only a tiny portion of issues qualifies for _that_ little work, I think this one does - unless I'm missing something.

**Comment by asvinb** [comment]
Makes sense @felixarntz . Estimate updated to 1

**Comment by tofumatt** [comment]
QA ✅
