### ISSUE TITLE
Refactor `SettingsOverlay` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2186]
The `SettingsOverlay` component should be refactored to be a functional component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SettingsOverlay` component should be refactored to be a functional component.
* The file should be renamed to `SettingsOverlay.js`, and all import references should be updated accordingly.

## Implementation Brief

* Change `SettingsOverlay` to a functional React component, using its existing `render` method as the basis for the function component.

### Test Coverage

* No additional test coverage is needed, but existing tests should pass without modification.

### Visual Regression Changes

* None.

## QA Brief

* Ensure settings page still works as expected after refactor.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by ryanwelcher** [comment]
Manual inspected settings page and everything works as expected

QA ✅
