### ISSUE TITLE
Refactor `AnalyticsInactiveCTA` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2188]
The `AnalyticsInactiveCTA` component should be refactored to a functional component using the datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `AnalyticsInactiveCTA` component should be refactored to a functional component using the datastore and hooks.
    * It shouldn't use any legacy utility functions or globals anymore to get data.
    * The only legacy function that's okay to keep is `showErrorNotification` since there's no replacement yet.
* Its file should be renamed so that the file name matches the component name, and all import references should be updated accordingly.
* There should be a working Storybook story for the button under "Global".

## Implementation Brief

* Change the static `AnalyticsInactiveCTA.setupAnalyticsClick` method to be a normal async callback function named `activateModule` that looks like:

```js
		const { activateModule } = useDispatch( MODULES_STORE );

		const activateModule = async () => {
			const { error, response } = await activateModule( 'analytics' );

			if ( ! error ) {
				global.location = response.moduleReauthURL;
			} else {
				showErrorNotification( GenericError, {
					id: 'analytics-setup-error',
					title: __( 'Internal Server Error', 'google-site-kit' ),
					description: error.message,
					format: 'small',
					type: 'win-error',
				} );
			}
		};
```

* Change `const { canManageOptions } = global._googlesitekitLegacyData.permissions;` to use hooks `const canManageOptions = useSelect( ( select ) => select( USER_STORE ).hasCapability( PERMISSION_MANAGE_OPTIONS ) );` where `USER_STORE` is from `import { STORE_NAME as USER_STORE, PERMISSION_MANAGE_OPTIONS } from '../googlesitekit/datastore/user/constants';`
* Change the class-based component to be a function-based component, with the function being largely based off the existing `AnalyticsInactiveCTA`'s `render()` method.
 Add a new Storybook story to `stories/module-analytics-cta.stories.js` under storiesOf( 'Global', module ).add( 'AnalyticsInactiveCTA', () => {} ), demonstrating the CTA, possibly including an error state if straightforward to implement.

### Test Coverage

* Add test coverage for the click actions for this component, both when the error state occurs and when the response is valid and there's a redirect.

### Visual Regression Changes

* There should be no visual changes as a result of this refactor.

## QA Brief

* Setup a Site Kit site without Analytics but with Search Console data, then visit the main dashboard. The Analytics CTA on the dashboard should function identically to how it did before this change.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@tofumatt IB ✅ 

> [...] demonstrating the CTA, possibly including an error state if straightforward to implement.

Probably the error state won't be needed here. That legacy function `showErrorNotification` will add an error to display on top of the Site Kit dashboard, which is outside the component, so we don't need to worry about the error state here since it doesn't have any visual implications on the component.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Verified:

- Setup site that has SC data but only had SC module activated for the latest release of SK. 
- Then changed to the develop branch and reconnected the site.  

The SC data for Analytics CTA was the same with the update. 
Compared data and GUI. No console errors and the module looks the same, no difference. 

![image](https://user-images.githubusercontent.com/73545194/98680779-d4faab00-239c-11eb-9645-cd46b1e2f390.png)
