### ISSUE TITLE
Refactor MDC-driven components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2189]
The following MDC JS API-driven components in `assets/js/components` should be refactored to become functional components:

* `Button`
* `Checkbox`
* `Dialog`
* `Menu`
* `Radio`
* `Switch`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following components in `assets/js/components` relying on `MDC*` JS components should be refactored to become functional components:
    * `Button`
    * `Checkbox`
    * `Dialog`
    * `Menu`
    * `Radio`
    * `Switch`
* Lifecycle methods should be replaced with hooks.
* Their files should be renamed to match the respective component name, and all import references should be updated accordingly.
* Every component should have a Storybook story in "Global" (if not yet available).

## Implementation Brief
In the [Button component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/button.js),
- update the imports from `import { Component, createRef } from '@wordpress/element';` to `import { useRef, useEffect } from '@wordpress/element';`
- refactor component to be a functional one using the `useRef` and `useEffect` hooks.
- rename file from `button.js` to `Button.js`
- Update the following files to use the correct path for the renamed component:
    - /assets/js/components/settings/settings-module.js
    - /assets/js/components/PostSearcher.js
    - /assets/js/components/setup/site-verification.js
    - /assets/js/components/setup/setup-proxy.js
    - /assets/js/components/setup/search-console.js
    - /assets/js/components/activation/activation-main.js
    - /assets/js/components/Dialog.js
    - /assets/js/components/signin.js
    - /assets/js/components/ErrorHandler/ErrorComponent.js
    - /assets/js/components/ErrorHandler/index.js
    - /assets/js/components/dashboard-splash/dashboard-splash-intro.js
    - /assets/js/components/dashboard-splash/dashboard-splash-outro.js
    - /assets/js/components/setup.js
    - /assets/js/components/user-menu.js
    - /assets/js/components/notifications/notification.js
    - /assets/js/components/setup-wizard/wizard-step-complete-setup.js
    - /assets/js/components/setup-wizard/wizard-step-authentication.js
    - /assets/js/modules/optimize/components/setup/SetupForm.js
    - /assets/js/modules/tagmanager/components/setup/SetupForm.js
    - /assets/js/modules/tagmanager/components/common/AccountCreate.js
    - /assets/js/modules/adsense/components/setup/SetupAccountCreate.js
    - /assets/js/modules/adsense/components/setup/SetupSiteAdd.js
    - /assets/js/modules/adsense/components/setup/SetupAccountApproved.js
    - /assets/js/modules/adsense/components/setup/SetupSiteAdded.js
    - /assets/js/modules/analytics/components/setup/SetupForm.js
    - /assets/js/modules/analytics/components/common/AccountCreateLegacy.js
    - /assets/js/modules/analytics/components/common/AccountCreate/index.js
    - /stories/buttons.stories.js

In the [Checkbox component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/checkbox.js),
- update the imports from `import { Component, createRef } from '@wordpress/element';` to `import { useRef, useEffect } from '@wordpress/element';`
- refactor component to be a functional one using the `useRef` and `useEffect` hooks.
- create the following file: `/stories/checkboxes.stories.js` which will contain the story for the Checkbox component.
- the story should at least contain the following:
  - default checkbox
  - checked checkbox 
  - disabled checkbox
- rename file from `checkbox.js` to `Checkbox.js`
- Update the following files to use the correct path for the renamed component:
    - /assets/js/components/optin.js
    - /assets/js/material-components/index.js

In the [Dialog component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/dialog.js),
- update the imports from `import { Component, createRef } from '@wordpress/element';` to `import { useRef, useEffect } from '@wordpress/element';`
- refactor component to be a functional one using the `useRef` and `useEffect` hooks.
- the state is unused and can be removed.
- rename file from `dialog.js` to `Dialog.js`
- update the following files to use the correct path for the renamed component:
    - /assets/js/components/settings/settings-module.js
    - /assets/js/components/reset-button.js
    - /assets/js/components/user-menu.js
    - /assets/js/components/permissions-modal/index.js
    - /assets/js/material-components/index.js
    - /stories/modal-dialog.stories.js

In the [Menu component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/menu.js),
- update the imports from `import { Component, createRef } from '@wordpress/element';` to `import { useRef, useEffect } from '@wordpress/element';`
- refactor component to be a functional one using the `useRef` and `useEffect` hooks.
- create the following file: `/stories/menu.stories.js` which will contain the story for the Menu component.
- rename file from `menu.js` to `Menu.js`
- update the following files to use the correct path for the renamed component:
    - /assets/js/components/user-menu.js
    - /assets/js/material-components/index.js

In the [Radio component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/radio.js),
- update the imports from `import { Component, createRef } from '@wordpress/element';` to `import { useRef, useEffect } from '@wordpress/element';`
- refactor component to be a functional one using the `useRef` and `useEffect` hooks.
- rename file from `radio.js` to `Radio.js`
- update the following files to use the correct path for the renamed component:
    - /assets/js/material-components/index.js
    - /stories/radio.stories.js

In the [Switch component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/switch.js),
- update the imports from `import { Component, Fragment, createRef } from '@wordpress/element';` to `import { useRef, useEffect, Fragment } from '@wordpress/element';`
- refactor component to be a functional one using the `useRef` and `useEffect` hooks.
- rename file from `switch.js` to `Switch.js`
- update the following files to use the correct path for the renamed component:
    - /assets/js/modules/tagmanager/components/common/UseSnippetSwitch.js
    - /assets/js/modules/adsense/components/common/UseSnippetSwitch.js
    - /assets/js/modules/analytics/components/common/TrackingExclusionSwitches.js
    - /assets/js/modules/analytics/components/common/UseSnippetSwitch.js
    - /assets/js/modules/analytics/components/common/AnonymizeIPSwitch.js
    - /assets/js/material-components/index.js
    - /stories/switch.stories.js

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* No visual regressions.
* Everything should look and function the same way as before the changes.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@asvinb IB ✅ 

Just wanting to say for next time you probably don't need to put the exact lists of all the files to replace paths in into an IB like that, it adds a bit of unnecessary clutter. Something like that could be summarized like "Update path references everywhere where path `xyz` is imported to `...`" :)

**Comment by asvinb** [comment]
> @asvinb IB ✅
> 
> Just wanting to say for next time you probably don't need to put the exact lists of all the files to replace paths in into an IB like that, it adds a bit of unnecessary clutter. Something like that could be summarized like "Update path references everywhere where path `xyz` is imported to `...`" :)

👍 @felixarntz

**Comment by eugene-manuilov** [comment]
@asvinb i have approved your changes, but VRT check has failed in your PR. Could you please check it and fix it?

**Comment by asvinb** [comment]
@eugene-manuilov I re ran the VRT checks and everything passes now 🤷  :)

**Comment by eugene-manuilov** [comment]
Awesome! Thanks, @asvinb!

**Comment by cole10up** [comment]
### QA ✅

Ran a series of visual and functional regression tests. Setting up every module and confirming functionality as well as look and feel.

GA: ✔️
Adsense: ✔️
PSI: ✔️
Tag Manager: ✔️
Optimize: ✔️

Sending to Approval.
