### ISSUE TITLE
Refactor `GoogleChart` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2190]
The `GoogleChart` component should be refactored to a functional component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GoogleChart` component should be refactored to a functional component using hooks.
* Its file should be renamed so that the file name matches the component name, and all import references should be updated accordingly.

## Implementation Brief

* Rename `assets/js/components/google-chart.js` to `assets/js/components/GoogleChart.js`. Update all imports accordingly, or use VSCode's feature to do it automatically:
<img width="663" alt="Screenshot 2020-10-16 at 22 44 12" src="https://user-images.githubusercontent.com/90871/96311316-1e0b4980-1001-11eb-8429-af1a7d4d4115.png">

* Refactor the component to a functional component. Use object destructuring to unpack concerned props.

* Refactor the `GoogleChart` to use hooks. The main bit of refactoring will be around `componentDidMount`/`componentDidUpdate`/`componentWillUnmount` by using `useEffect` hooks. Apart from that `useState` will be used to replace state variables and `useRef` for `chartRef`.  
	* Call `updateChart` whenever any of `selectedStats, options, singleStat` props change.
	* Add event listener on mount and remove them on unmount

* There are additional, small refactors needed, but they're mostly trivial/obvious ones resulting from a class-to-functional component refactor.

### Test Coverage

*  No additional tests needed.

### Visual Regression Changes

* There should be no visual changes resulting from this refactoring.

## QA Brief

*   Ensure Analytics dashboard's charts have not changed from this refactor.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

**Verified:**

Compared a site on the develop branch to latest release.  Checked the GA dashboard charts to ensure no differences. 
No errors in the console.  Confirmed that the refactor did not cause any issues. 

![image](https://user-images.githubusercontent.com/73545194/98828191-bebf1e80-2472-11eb-8c1d-1e23b5445d1b.png)
