### ISSUE TITLE
Refactor `ResetButton` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2191]
The `ResetButton` component should be refactored to a functional component using the datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ResetButton` component should be refactored to a functional component using the datastore and hooks.
* Its file should be renamed so that the file name matches the component name, and all import references should be updated accordingly.
* There should be a working Storybook story for the button under "Global".

## Implementation Brief

* Rename `assets/js/components/reset-button.js` to `assets/js/components/ResetButton.js`. Update all imports accordingly, or use VSCode's feature to do it automatically:
<img width="663" alt="Screenshot 2020-10-16 at 22 44 12" src="https://user-images.githubusercontent.com/90871/96311316-1e0b4980-1001-11eb-8429-af1a7d4d4115.png">

* Refactor the `ResetButton` to use hooks. The main bit of refactoring will be around `componentDidMount`/`componentWillUnmount`. Something like:

```js
const [ dialogActive, setDialogActive ] = useState( false );
const handleCloseModal = useCallback( ( event ) => {
    if ( 27 === event.keyCode ) {
        setDialogActive(false);
    }
}, [ setDialogActive ] );
useEffect( () => {
    global.addEventListener( 'keyup', handleCloseModal, false );

    return global.removeEventListener( 'keyup', handleCloseModal );
}, [ handleCloseModal ] )
```

* Change `splashURL` to use `useSelect( ( select ) => select( CORE_SITE ).getAdminURL( 'googlesitekit-splash' ) );` instead of the current `global._googlesitekitBaseData.splashURL`.
* Remove `postResetURL` from state and make it a constant in the component, as it does not change.
* Refactor `handleUnlinkConfirm()` to use `dispatch( 'core/site' ).reset()`
* There are additional, small refactors needed, but they're mostly trivial/obvious ones resulting from a class-to-functional component refactor.
* Add a new Storybook story to `stories/ResetButton.js` under `storiesOf( 'Global', module ).add( 'ResetButton', () => {} )`, demonstrating the reset button and its modal dialog in use.

### Test Coverage

* Adding test coverage for the `ResetButton` is welcome, largely around the handling of modal clicks if appropriate.

### Visual Regression Changes

* There should be no visual changes resulting from this refactoring.

## QA Brief

* Resetting the site (and opening the reset dialog then cancelling the reset action) should continue to work as it did before this refactor. Resetting the app should continue to clear local storage/session storage and not leave data cached in the browser.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- When the `Reset this Site` link is clicked in Settings the dialog box appears. The user is able to cancel the reset by clicking on the `clear` link or pressing `Esc key`  [Screenshot](https://user-images.githubusercontent.com/73545194/99264234-269eac00-285b-11eb-82be-799df6b905ca.png)
- When the Reset button is clicked the associated Google account is disconnected and the local/session storage data is deleted and no data is cached. [Screenshot](https://user-images.githubusercontent.com/73545194/99264533-8dbc6080-285b-11eb-8828-3a5411265d36.png)

This was tested from the user menu and reset link within settings.
