### ISSUE TITLE
Refactor `UserMenu` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2192]
The `UserMenu` component should be refactored to a functional component using the datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `UserMenu` component should be refactored to a functional component using the datastore and hooks.
* Its file should be renamed so that the file name matches the component name, and all import references should be updated accordingly.
* There should be a working Storybook story for the button under "Global".

## Implementation Brief

* Rename `assets/js/components/user-menu.js` to `assets/js/components/UserMenu.js`;
* Rename user menu import in the `assets/js/components/header.js` file to use the new file name;
* Edit the `assets/js/components/UserMenu.js` file:
  * Add a new `UserMenu` function that does the following:
    * Uses the `useSelect` hook to pull `proxyPermissionsURL`, `userEmail` and `userPicture` data;
    * Uses the `useState` hook to define `dialogActive` and `menuOpen` state properties;
    * Uses the `useCallback` hook to define `handleMenu`, `handleMenuItemSelect`, `handleDialog` and `handleUnlinkConfirm` callbacks:
      * the `handleMenu` callback should toggle the `menuOpen` state;
      * the `handleMenuItemSelect` callback should replicate the logic from the legacy `handleMenuItemSelect` method;
      * the `handleDialog` callback should hide the menu and toggle the `dialogActive` state;
      * the `handleUnlinkConfirm` callback should hide the dialog, clear web storage and redirect to the splash screen like it's done in the legacy `handleUnlinkConfirm` method.
    * Uses the `useEffect` hook to execute a side effect after the component is mounted:
      * Use no dependencies for this hook to make sure it gets triggered on the initial render only;
      * It should add event listeners defined in the legacy `componentDidMount` method;
      * It should return a cleanup function that removes event listeners like it is done in the legacy `componentWillUnmount` method.
    * Return markup generated by the legacy `render` method and update it to use new hooks and state variables.
  * Remove the legacy `UserMenu` class;
  * Remove `withSelect` HOC.
* Add a new story to the "global" section of the storybook that renders the user menu component.

### Test Coverage

* Add js tests which check that dialog and menu can be opened when a user clicks on appropriate menu items.

### Visual Regression Changes

* Not needed

## QA Brief

* Set up the Site Kit on your site;
* Go to the Site Kit dashboard:
  * [ ] the user menu is displayed in the header and it contains picture and email of the current user;
  * [ ] the dropdown menu is shown if you click on the menu button;
  * [ ] the dropdown menu gets hidden when you press the escape button or click outside of the dropdown menu;
  * [ ] the dialog is displayed if you click on the disconnect menu item;
  * [ ] the dialog gets hidden when you press the escape button or click on the `Cancel` button;
  * [ ] you get disconnected if you click on the `Disconnect` button of the dialog;

## Changelog entry

* N/A

**Comment by rushilp2311** [comment]
Hi @felixarntz, I could take this issue

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

**Verified:**

From the Site Kit dashboard:

-  the user menu is displayed in the header and it contains picture and email of the current user  [image](https://user-images.githubusercontent.com/73545194/99261908-47193700-2858-11eb-95ab-89780caf1fdd.png)
-  the dropdown menu is shown if you click on the menu button [image](https://user-images.githubusercontent.com/73545194/99261923-4ed8db80-2858-11eb-8a49-904f8df742d1.png)
-  the dropdown menu gets hidden when you press the escape button or click outside of the dropdown menu
-  the dialog is displayed if you click on the disconnect menu item [image](https://user-images.githubusercontent.com/73545194/99261958-57c9ad00-2858-11eb-858c-e667201ee5f4.png)
-  the dialog gets hidden when you press the escape button or click on the Cancel button
-  you get disconnected if you click on the Disconnect button of the dialog [image](https://user-images.githubusercontent.com/73545194/99261985-62844200-2858-11eb-8094-232d8543064e.png)
