### ISSUE TITLE
Refactor `Modal` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2193]
The `Modal` component should be refactored to a functional component using hooks.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Modal` component should be refactored to a functional component using hooks.
* Its file should be renamed so that the file name matches the component name, and all import references should be updated accordingly.

## Implementation Brief

- Rename `/assets/js/components/modal.js` to `/assets/js/components/Modal.js`
- Update `import { Component, createPortal } from '@wordpress/element';` to `import { createPortal, useEffect } from '@wordpress/element';`
- Refactor component to be a functional component, using the `useEffect` hook
- Update the Modal import in the following file:
	- /assets/js/components/reset-button.js
	- /assets/js/components/user-menu.js
	- /assets/js/components/permissions-modal/index.js

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief
All the Modals should function identically how it did before this change. Try:
* Opening the Reset Site Kit modal.
* Opening the Disconnect account modal by clicking on the email address in the top right corner.

## Changelog entry

* N/A

**Comment by rushilp2311** [comment]
Hi @felixarntz, I would like to work on it if no one is handling this issue.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Thank you @rushilp2311 for your offer to help with this issue - feel free to open a pull-request against this issue! We have some [documentation about contributing to engineering](https://github.com/google/site-kit-wp/wiki/Engineering) available.

Please refer to the implementation brief that @asvinb has added to the issue description above for how to technically implement the changes.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

Opened the Reset Site Kit modal. Reset the site successfully. 

![image](https://user-images.githubusercontent.com/73545194/98831002-fda2a380-2475-11eb-933b-eae6de2d093f.png)

Opened the Disconnect account modal and revoked access then reset Site Kit. 

![image](https://user-images.githubusercontent.com/73545194/98830900-e4015c00-2475-11eb-87fc-d5b390c360b6.png)

![image](https://user-images.githubusercontent.com/73545194/98830916-e95ea680-2475-11eb-8aec-b6f15198a6e0.png)

After revoking access and resetting Site Kit, the site connected as expected.
