### ISSUE TITLE
Refactor `ModulesList` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2194]
The `ModulesList` component should be refactored to a functional component using the datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ModulesList` component should be refactored to a functional component using the datastore and hooks.
    * It shouldn't use any legacy utility functions or globals anymore to get data.
    * The only legacy function that's okay to keep is `showErrorNotification` since there's no replacement yet.
* The logic handling the case where a module cannot be activated because of a missing dependency module should be removed - it should be unreachable anyway because such modules are already filtered out before.
* Its file should be renamed so that the file name matches the component name, and all import references should be updated accordingly.
* There should be a working Storybook story for the button under "Global".

## Implementation Brief

* Rename `assets/js/components/modules-list.js` to `assets/js/components/ModulesList.js`;
* Rename modules list import in the `assets/js/components/notifications/dashboard-setup-alerts.js` file to use the new file name;
* Edit the `assets/js/components/ModulesList.js` file:
  * Add a new `ModulesList` function that does the following:
    * Uses the `useSelect` hook to pull `modules` from the modules datastore;
    * Uses the `useState` hook to define `isSaving` state property;
    * Uses the `useCallback` hook to define `setupModuleClick` callback that replicates the logic defined in the legacy method:
      * Dispatch the `activateModule` action and grab `moduleReauthURL` from its response;
      * Call the `trackEvent` function like its done in the `activateOrDeactivateModule` function;
      * Redirect the browser to the `modlueReauthURL` received from the `activateModule` actions;
      * Don't call the `refreshAuthentication` function since it is handled automatically by module activation now.
    * Returns markup similar to the one generated by the legacy `render` method but with new variables received from hooks;
  * Remove the legacy `ModulesList` class;
* Add a new story to the "global" section of the storybook that renders the modules list component.

### Test Coverage

* Not needed

### Visual Regression Changes

* Not needed

## QA Brief

* Disconnect the Site Kit on your site if it has been already connected;
* Sign in again;
* Check the following:
  * [ ] Make sure you see `Congrats on completing the setup for Site Kit!` notification on the dashboard with a list of modules;
  * [ ] The modules list look the same as it looked before;
  * [ ] You can activate a module by clicking on the `Connect Service` link.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@eugene-manuilov – IB looks good for the most part.

Re: `setupModuleClick`:
- It would be good to mention that calling `refreshAuthentication` manually won't be necessary anymore as that's handled automatically by module activation.
- Would you please elaborate on how `getReAuthURL` should be updated to use a selector instead since this is per-module?

**Comment by eugene-manuilov** [comment]
> It would be good to mention that calling refreshAuthentication manually won't be necessary anymore as that's handled automatically by module activation.

Updated.

> Would you please elaborate on how getReAuthURL should be updated to use a selector instead since this is per-module?

Is there a `getReAuthURL` selector? I haven't seen it yet...

**Comment by aaemnnosttv** [comment]
@eugene-manuilov It's on the `core/modules` store as `getAdminReauthURL`. See assets/js/googlesitekit/modules/create-info-store.js

**Comment by eugene-manuilov** [comment]
@aaemnnosttv thanks, I see it now. Looks like it is not that easy to replace the function with that selector. I think it requires more thoughts and it is a subject of a separate ticket to replace all `getReAuthURL` occurrences with the new selector. So, I would suggest keeping using the `getReAuthURL` function for now.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov the AC says "The only legacy function that's okay to keep is `showErrorNotification` since there's no replacement yet."

@felixarntz given the lack of an immediate replacement for the above, do you think we should address it here or in a separate issue? Maybe we just need to expose `SELECT_MODULE_REAUTH_URL` on `core/modules` as an action on the store?

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov I think we don't need to keep `getReAuthURL` and we don't even need to use the `getAdminReauthURL` selector: When activating a module via the datastore, the module's reauth URL is returned by that async action. It actually needs to be done this way - if the selector is used in a `useSelect`, it will be called before that module has been activated which may cause the reauth URL returned to be different, due to potentially requested extra scopes that require going through the OAuth flow.

Which lack of replacement are you referring to? If it's `showErrorNotification`, let's not worry about that one, I think that's gonna go away as part of the notification center epic.

**Comment by aaemnnosttv** [comment]
> When activating a module via the datastore, the module's reauth URL is returned by that async action.

I keep forgetting that this was added, thanks for clarifying! 😄 

> Which lack of replacement are you referring to?

I was just pointing out the AC only expected the one legacy function to be kept.

**Comment by eugene-manuilov** [comment]
@felixarntz the current implementation of the `setupModuleClick` function uses the `activateOrDeactivateModule` function which activates selected module and tracks module status change event. If we switch to dispatch the `activateModule` action, we will lose that event tracking. Is it okay or we need to add module status event tracking to the datastore as well?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- `Congrats on completing the setup for Site Kit!` notification appears on the dashboard with a list of modules. - [Screenshot](https://user-images.githubusercontent.com/73545194/100235302-31e28d80-2f67-11eb-97c1-f8eb8389d6d5.png)
- The modules list is displayed the same as it was before. Compared with latest release - [Screenshot](https://user-images.githubusercontent.com/73545194/100235302-31e28d80-2f67-11eb-97c1-f8eb8389d6d5.png)
- I was able to activate GA module by clicking on the Connect Service link. - [Screenshot](https://user-images.githubusercontent.com/73545194/100235386-52124c80-2f67-11eb-80ce-afca3493239e.png)
