### ISSUE TITLE
Cache key collision between modern and legacy cache APIs

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2197]
## Bug Description

Currently Site Kit has two separate cache APIs used for storing data in the browser.

1. The legacy [`dataAPI` cache](https://github.com/google/site-kit-wp/blob/114f7f226b5b3596daf8d120edc1666849a18617/assets/js/components/data/cache.js)
1. The modern [API cache](https://github.com/google/site-kit-wp/blob/114f7f226b5b3596daf8d120edc1666849a18617/assets/js/googlesitekit/api/cache.js)

These two are _nearly_ identical in their usage, in that they both target `sessionStorage` and generate and use the same cache keys for the same inputs, but the _values_ which are cached by the two are not the same. This could lead to a conflict where the two implementations compete with each other to set a value for the same key with different values.

![image](https://user-images.githubusercontent.com/1621608/96243125-f8eceb80-0fac-11eb-82b2-6e08797970b5.png)

Note that some values start with `value` (legacy) while others start with `timestamp`.

The key difference is that the legacy cached data is stored as an object with `value` and **`date`** (float) while the modern cache stores the cache as an object with `value` and **`timestamp`** (int).

Since both cache APIs reference their expiration/TTL values on different keys, both will be seen as invalid/expired cache values by the other implementation.

It's worth noting that originally, the modern cache API targeted local storage instead of session storage which would have mitigated a potential conflict but that was changed in #1780.

It's also worth noting that I have not observed a bug as a result of this, but the potential is there so this should be fixed.

The easiest and safest solution here would be to use different cache key prefixes between the two implementations rather than worry about keeping the cache values consistent.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The storage key prefixes used by the modern and legacy cache APIs should be different, with the legacy cache API using a prefix containing `legacy`.
* The modern and legacy cache implementations should not operate on the others values in any way (read/update/delete).

## Implementation Brief

* Change the existing legacy prefix for the cache key in https://github.com/google/site-kit-wp/blob/f8b2c6570f0748f7b5a15f40063d1aa1d8252502/assets/js/components/data/cache.js from `'googlesitekit_'` to `'googlesitekit_legacy_'`. This applies to:
  * `getStorage().removeItem( 'googlesitekit_' + key );`
  * `getStorage().setItem( 'googlesitekit_' + key, JSON.stringify( toStore ) );`
  * `const cache = JSON.parse( getStorage().getItem( 'googlesitekit_' + key ) );`

### Test Coverage

* Add a test to ensure that a cache value set by the new API cannot be read by the old API and vice-versa.

### Visual Regression Changes

* None.

## QA Brief

* Jest unit tests should pass, that should be sufficient for QA here.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
I think the original plan was to have them use similar cache keys on purpose, but fair point: they should either have the same shape or have different keys. I guess the idea was to share the data, but as mentioned that won't work here.

An IB that slightly changes our cache keys would be fine by me 👍🏻

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
