### ISSUE TITLE
Error: cURL error 2: 

### ISSUE THREAD

**Issue by lakshsyal123** [google/site-kit-wp#2198]
Hey

I am getting this problem when I configure the analytics account.

https://prnt.sc/v0iklf

Please help.

Thanks

**Comment by ernee** [comment]
@lakshsyal123 thanks for reaching out! We've seen this error in cases where the server environment needs to have a particular version of cURL to prevent it. Here's the related [issue for reference](https://github.com/google/site-kit-wp/issues/1575). Unfortunately, there isn't anything we can do on our side. You'll need to contact your host to address this further.
