### ISSUE TITLE
ESlint and Stylelint not running in Travis

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#220]
## Bug Description

Currently the only linting happening on Travis is PHPCS. 

The Travis config should be updated to run ESlint and stylelint as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* ESlint and stylelint are running in travis, during the job indicated for linting by `SNIFF=1`
* Errors raised by either check should fail the build

## Implementation Brief

Update the `"$SNIFF" == "1"` portion of the `script` in `travis.yml` to include:
```
npm run lint:css || exit 1
npm run lint:js || exit 1
```

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Implementation brief looks solid.

**Comment by aaemnnosttv** [comment]
@felixarntz Ready for review
