### ISSUE TITLE
`receiveError` and `clearError` should require `args`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2210]
## Bug Description

Following up on #1814, #1859, and #2033, there appears to be one thing that was previously missed or not considered: Currently it is valid to call the `receiveError` and `clearError` actions with a `baseName` parameter while not passing an `args` parameter. This should **not** be allowed because:
* `receiveError` and `clearError` apply to one **specific** error. Only passing `baseName` doesn't identify a specific error (which is different for `clearErrors`, where only passing `baseName` is expected because it will clear all errors from that `baseName`).
* Either `args` needs to be required, or at least `args` should default to `[]`, to make cases where the selector or action doesn't even support any arguments more intuitive. However I think it makes sense to be explicit and always require `args` (for parameter-less actions/selectors an empty array needs to be passed).

Note that the legacy behavior, where `receiveError` and `clearError` also work without `baseName` and `args` entirely, should not be affected by this change - we'll need to maintain this until all legacy usage has been phased out (not part of this issue).

Related: #2174 (which would have been avoided, had we implemented this in the first place)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The partial store returned from `createErrorStore` needs to be updated:
    * `receiveError` should either require only `error` or it should require all three parameters. In other words, if `baseName` is provided, `args` must be provided as well (and it must be an array).
    * `clearError` should either require no parameters or it should require all two parameters. In other words, if `baseName` is provided, `args` must be provided as well (and it must be an array).
* The tests that check required parameters etc should be adjusted accordingly.
* All usages of `receiveError` and `clearError` must be reviewed to ensure that they are:
    * either legacy usage (neither passing `baseName` nor `args`), which should not be updated here
    * or passing both `baseName` and `args`

## Implementation Brief

* Add a check for `args` in `receiveError` after https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/googlesitekit/data/create-error-store.js#L47:

```js
if ( baseName ) {
    invariant(
        args && Array.isArray( args ),
        'args is required (and must be an array) when baseName is specified.'
    );
}
```

* The same check should be added to https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/googlesitekit/data/create-error-store.js#L65
* Update instances like https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/googlesitekit/data/create-settings-store.js#L177 that don't supply args. When there would not be any arguments to supply, instead supply an empty array. Note that the `invariant` checks from above should cause many existing instances that need updating to fail and thus should be found from unit tests, but other instances should be checked for through the code as well.

### Test Coverage

* Update tests to ensure the new checks are working.
* Tests like https://github.com/google/site-kit-wp/blob/af48c90e7eb72a700fd15e951491731f08758c4c/assets/js/googlesitekit/data/create-error-store.test.js#L77-L80 will need to be refactored to indicate this should cause an error rather than work.

### Visual Regression Changes

* There should be no visual check from this improvement.

## QA Brief

* All error handling and tests should continue to work as normal.

## Changelog entry

* Fix bug where errors would be inconsistently keyed and not cleared as expected in certain cases.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
