### ISSUE TITLE
Change the "Start Setup" reference to match the "Sign in with Google" button after disconnecting Site Kit

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2214]
## Bug Description

After disconnecting Site Kit the there is a notice suggesting to click on "Start Setup". The "Start Setup" text should reflect the button text - "Sign in with Google" 

![image](https://user-images.githubusercontent.com/41326532/96621831-041f7e80-1301-11eb-9e73-1bedce0e28ee.png)

## Steps to reproduce

1. Disconnect Site KIt
2. View the notice provided

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Looks like this was already addressed as a side effect of #2029 (issue #1857), so this should be invalid.
