### ISSUE TITLE
Display notice to inform about GA4

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2219]
Google Analytics has for a while supported a new "Web + App" property type. While in the UI this isn't obvious, this type of property uses a completely different Analytics infrastructure (different UI in Analytics frontend as well as entirely separate API).

Site Kit does currently not support using such a property, partly because the API is just started to be rolled out (currently it's only open for testing). However, at the same time, this "Web + App" type of properties will in the long term become the recommended way to use Analytics, and some Analytics users already see prompts to update their "Web" property to a "Web + App" property.

Again, it should be clarified that the new type of properties are not interoperable with the old type of properties in any way. Users that migrate from one to the other are recommended to "double-tag" for a while, coninuing to use the "Web" property for insights while already starting to populate the "Web + App" property with data until it feels appropriate to fully switch.

We're currently scoping out the necessary work to support the new Analytics API in Site Kit and how the old and new Analytics would be related in the UI (or not), but for now we should add a notification in Site Kit clarifying the current state for users that may already want to use or have a "Web + App" property.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics setup and settings UI should render a blue **unconditional** notification above the main content (i.e. above the three dropdowns or the potential text above the dropdowns).
    * The notification should have copy: _Got a Google Analytics 4 (GA4) property and want to find out how to use it with Site Kit? Learn more here._
    * The second sentence should be an external link to a URL `https://sitekit.withgoogle.com/documentation/ga4-analytics-property/`.

Reference PM mock: 
<img width="721" alt="Screenshot 2020-10-21 at 16 39 06" src="https://user-images.githubusercontent.com/13304791/96750601-6c876200-13cc-11eb-8b1f-503b0f733ffe.png">

## Implementation Brief

* Modify `SettingsNotice` component in `assets/js/components/settings-notice.js`...
    * ...to support `children` instead of the limited `message` prop
    * ...to support `type` instead of the limited `isSuggestion` prop
* Update `SettingsNotice` usage in AdSense `UseSnippetSwitch` component to render the message as a child of the component instead of passing as regular prop.
* Introduce `GA4Notice` component in `assets/js/modules/analytics/components/common/GA4Notice.js` which renders a `SettingsNotice` with content per the ACs.
* Place the `GA4Notice` component on top of the Analytics components `SetupForm`, `AccountCreate`, `AccountCreateLegacy`, and `SettingsForm`.
* Create Storybook story for the `GA4Notice`.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Set up the Analytics module. Verify the notice about the new Analytics is showing on top of the main content UI.
    * Verify that it also shows in the UI for creating a new Analytics account.
* Go to Analytics settings afterwards. Go to Edit, and verify that the notice also shows up there.

## Changelog entry

* Display notice about new Analytics and link to relevant support resource.

**Comment by aaemnnosttv** [comment]
@felixarntz IB looks good to me, the only correction I would make is regarding the components to change for Analytics. I think `SettingsForm` would be more appropriate to change than `SettingsEdit`.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest Site Kit release. During setup confirmed the message and URL for GA4

![image](https://user-images.githubusercontent.com/57115907/96907873-ac902880-1450-11eb-88cb-f641fb3ca268.png)

Confirmed different browser sizes and mobile look good

Checked the URL, currently drives to a 404 page.
![image](https://user-images.githubusercontent.com/57115907/96907909-bfa2f880-1450-11eb-9eab-3c08ea3e831d.png)

Confirmed with @ryanwelcher that this is expected and will be live after we release.

Checked settings page setup:
![image](https://user-images.githubusercontent.com/57115907/96908007-e4976b80-1450-11eb-9941-66d1227d24e0.png)

Confirmed new account setup page:
![image](https://user-images.githubusercontent.com/57115907/96908073-fda01c80-1450-11eb-8e39-3e47d09c5b74.png)

Passed QA ✅
