### ISSUE TITLE
GA4 Detection

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2220]
Issues around supporting GA4 in Site Kit and facilitating migration

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by perks98** [comment]
Hi, any updates. All new properties that I do for customers use the new GA4 and your plugin doesn't support it at the moment. Would you know if you can downgrade new properties?

**Comment by ernee** [comment]
@perks98 thanks for your inquiry! Please reference [this document](https://sitekit.withgoogle.com/documentation/ga4-analytics-property/) on how to implement the Google Analytics 4 ID on your site with Site Kit. Note you can use the new Google Analytics 4 along with the Universal Analytics (which will surface data in Site Kit's dashboards). Feel free to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) in our support forum if you have further questions.

**Comment by AndrewErman** [comment]
It looks like the plugin doesn't send transaction data (purchases, add to cart events etc..) to GA4. Could somebody advise, whether this is in backlog and if yes - what would be the estimates?

**Comment by felixarntz** [comment]
@AndrewErman Supporting GA4 in Site Kit is a high priority for us, but there are some complexities that we'll need to figure out. Our initial focus is to facilitate double-tagging, where sites use both a classic UA property _and_ a GA4 property for a transitional period, until Site Kit has full support for GA4 reporting.

**Comment by AndrewErman** [comment]
@felixarntz thank you for the answer. Well, will wait and hope then. But what would you recommend as a workaround for those cases when UA is not available? If i understand correctly - i can't create any new UA properties anymore.

**Comment by ernee** [comment]
@AndrewErman please reference [this document ](https://sitekit.withgoogle.com/documentation/ga4-analytics-property/)with recommendations on how to implement your GA4 property.

**Comment by perks98** [comment]
Is GA4 going to be implemented yet in your plugin? All new properties created in Google Analytics is made now with GA4, For the company I work for the whole purpose of using your plugin is to add Google Analytics tracking code and have Google Search Console to view on WordPress. We haven't been able to use your plugin since my initial message back in October 2020, and using Tag Manager for all my new customers moving forward is impractical. We've not been using any tracking plugins and adding the tracking code manually at the moment...

**Comment by bethanylang** [comment]
@perks98 Thanks for getting in touch. GA4 implementation is a high priority for us in the coming months and we're starting the build process soon. Continue to follow this thread for more details on timeline and next steps.

**Comment by pedrosanta** [comment]
We have been using the Tag Manager approach as suggested by Google Technical document and it has been working well as a temporary workaround. With that being said I still feel the roadmap on @bethanylang is still of importance to make the onboarding/setup of GA simpler.

**Comment by bethanylang** [comment]
@pedrosanta Absolutely! As an update, our current timeline for this integration is end of June. We'll share here if things change.

**Comment by gerardreches** [comment]
> @pedrosanta Absolutely! As an update, our current timeline for this integration is end of June. We'll share here if things change.

Hi @bethanylang , is the timeline still on track?

**Comment by bethanylang** [comment]
@gerardreches Shifted slightly to first week of July.   :)

That said, we will be rolling this out to users incrementally over the course of a few releases, so depending on which rollout group you are in, you may not receive it until a bit later.

**Comment by Stanzilla** [comment]
In https://sitekit.withgoogle.com/documentation/ga4-analytics-property/#:~:text=Creating%20and%20connecting%20a%20new%20GA4%20property it says that a notice should now be displayed to add GA4 to my existing setup. I do not get that though. I verified in the Site Health tool that the feature itself is available to me though 
![image](https://user-images.githubusercontent.com/75278/126400432-357b0b93-3c3a-4ec6-b923-17c67cce2611.png)

**Comment by bethanylang** [comment]
@Stanzilla All support for the Site Kit plugin is provided on our [WordPress.org support forum](https://wordpress.org/support/plugin/google-site-kit/). If you [create a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) there, we'd be happy to take a look and help you troubleshoot. Thanks!

**Comment by nicwinn** [comment]
> @gerardreches Shifted slightly to first week of July. :)

Of what year @bethanylang ;)

**Comment by bethanylang** [comment]
@nicwinn The addition of GA4 to Site Kit was released back in July, though this issue remains open for future additions to this feature.  :)  You can see more info in our documentation here: https://sitekit.withgoogle.com/documentation/ga4-analytics-property/.

**Comment by a2425rdl** [comment]
Rianah.org

**Comment by justinkruit** [comment]
So the UA will stop working soon, and this plugin still needs one to make the data work? How long will it take to get up to date? We've created GA4 properties for a while now, and it's a shame to see a Google plugin still not being up to date on their own code.

**Comment by ErikThiart** [comment]
Issue is still not fixed? ( Wasted 3 hours now, just to find out the problem is on Google's side )

**Comment by jmzolezzi** [comment]
For the time being, it appears that GA4 is supported, but stats are not show inside WordPress (unless you load Universal Analytics as well, which is not ideal due to big javascript size).

As per [the article](https://sitekit.withgoogle.com/documentation/using-site-kit/ga4/) mentioned before:

> At this time, GA4 statistics are not reported within Site Kit’s dashboards. GA4 statistics can be viewed in your [Analytics account](https://analytics.google.com/). However, the addition of GA4 data to Site Kit’s dashboards and reporting is in Site Kit’s roadmap.

Hopefully GA4 is added soon, it would be nice to use Site Kit vs other analytics plugins.

**Comment by STRML** [comment]
It is a strange situation to see Site Kit prompting you to migrate from UA to GA4 ASAP, as UA will stop working in mere months. 

But then Site Kit itself does not support showing analytics from GA4.

So, if I migrate, I lose functionality. If I don't, I'll eventually lose all access.

**Comment by bethanylang** [comment]
Hi all! We are actively working on integrating GA4 for the Site Kit Dashboard in #6169 and its associated issues. We don't have an exact timeline for releasing this just yet, but it will certainly be available prior to the [Universal Analytics sunset](https://support.google.com/analytics/answer/11583528?hl=en) scheduled for July 1, 2023.
