### ISSUE TITLE
Remove vestigial console mocks

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2231]
## Feature Description

In #1770 we upgraded `@wordpress/scripts` to the latest version which included using `@wordpress/jest-console` via `@wordpress/jest-preset-default`.

This replaced the need to implement our own console mocks, but the existing usage in test setup and teardown was overlooked.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No `console` methods should be manually mocked or spied on in Jest test setup

## Implementation Brief

* Delete [`tests/js/setup-mocks.js`](https://github.com/google/site-kit-wp/blob/57efa7c53b4b4bfe06b599856e686157edcba005/tests/js/setup-mocks.js) is only used for setting up spies on console methods
    - Remove entry in `setupFiles` in `tests/js/jest.config.js`
* Remove `console.*.mockClear` calls https://github.com/google/site-kit-wp/blob/57efa7c53b4b4bfe06b599856e686157edcba005/tests/js/setup-before-after.js#L9-L13
* Fix any failing tests as a result (none expected)

### Test Coverage

* No change

### Visual Regression Changes

* N/A

## QA Brief

* `npm run test:js` should function similarly as before with no console errors or unexpected console output.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

(I added a very basic QA brief.)

**Comment by ryanwelcher** [comment]
Ran `npm run test:js` and saw no unexpected console output.

QA ✅
