### ISSUE TITLE
Pass actual dates in API calls in AdSense widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2235]
The AdSense `dashboard` and `pageDashboard` widgets should be migrated to pass `startDate` and `endDate` instead of `dateRange` with their API requests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following widgets should pass `startDate` and `endDate` (using the `core/user` `getDateRangeDates` selector) instead of `dateRange` to their `getReport` calls:
    * `DashboardSummaryWidget`
    * `DashboardTopEarningPagesWidget`
* The dates sent should match (compare the API responses) what the server would have previously computed from the passed `dateRange` parameter (e.g. depending on the `offsetDays` value passed to `getDateRangeDates`).

## Implementation Brief

* Update `DashboardSummaryWidget` and `DashboardTopEarningPagesWidget` components to use the `getDateRangeDates` selector from the user datastore to pull `startDate` and `endDate` dates. These dates must be set as `startDate` and `endDate` properties in the report args object instead of just `dateRange`.

### Test Coverage

* Not needed.

### Visual Regression Changes

* Not expected.

## QA Brief

* Make sure the aforementioned widgets use the new date range dates instead of ranges.

## Changelog entry

* Rely on JavaScript date parsing for AdSense widgets.

**Comment by felixarntz** [comment]
IB ✅

**Comment by benbowler** [comment]
## ✅ QA:Eng Approved
