### ISSUE TITLE
Couldn't create Project: Google Site Kite Error during OAuth 

### ISSUE THREAD

**Issue by thejoydutta** [google/site-kit-wp#224]
During OAuth of site kite in one, my website shows below error

**field [project_id] has issue [project_id contains invalid characters]**

![image](https://user-images.githubusercontent.com/42054702/61107078-97ca9400-a49c-11e9-8917-e149443316f4.png)

**Comment by jamesozzie** [comment]
@thejoydutta Thanks for reporting. Can you let me know what security or firewall plugins you are using, if any, and also your WordPress and Site URL from your WordPress [settings](https://i.imgur.com/MkFLF0E.png)?

As a workaround you can attempt the following: 
- Reset Site Kit ((Site Kit > Settings > Admin Settings > Reset Site Kit)
- At the popup screen where you see the error close click on the Site Kit text on the upper left of the screen (at the OAuth stage). Then manually create the project. Here is a [demo](https://recordit.co/CiviYgnMTY). For the "redirect URI" you can enter your full website URL followed by a ??oauth2callback=1
