### ISSUE TITLE
Replace legacy admin bar menu with refactored version in production

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2241]
Eventually the refactored version of the admin bar menu should be exposed in production, and the legacy version should be deleted.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `widgets.adminBar` feature flag should be removed. Conditionals wrapped into a check for it in JS should be removed, i.e. the inner parts should run unconditionally.
* The `LegacyAdminBarModules` component should be removed.
* All usages of the `googlesitekit.AdminbarModules` filter should be removed.
* All folders `assets/js/modules/*/components/adminbar` should be removed.
* The new version (now available in production builds) should look the same like the legacy version before (should already be taken care of via #2076, but added here to double-check).

## Implementation Brief

* Remove the `widgets.adminBar` feature flag from `feature-flags.json`.
* Remove the `widgets.adminBar` feature flag from the `resetFeatures` function in `.storybook/config.js`.
* Remove all conditional wrappers around code that use this flag in `assets/js/components/adminbar/AdminBarApp.js`.
* Remove the `assets/js/components/adminbar/LegacyAdminBarModules` component.
* Remove all usages of the `googlesitekit.AdminbarModules` filter from these files:
   * `plugins/google-site-kit/assets/js/modules/analytics/index.legacy.js`
   * `assets/js/modules/search-console/index.legacy.js`
   * `stories/adminbar.stories.js`
* Remove all admin bar folders from withing components `assets/js/modules/*/components/adminbar`.

### Test Coverage

* No changes expected.

### Visual Regression Changes

* No changes expected.
## QA Brief

* Set up your site and prepare a page that has active Google Analytics and Search Console data (for example set your Custom Site URL to https://www.elasticpress.io with the Developer Settings plugin and create a page with the slug /features/).
* Test that the data in each of the admin bar sections in the new admin bar match the data in each of the legacy admin bar sections.

<img width="1200" alt="Screenshot 2021-01-15 at 14 41 01" src="https://user-images.githubusercontent.com/119352/104740316-b9ff3b00-573f-11eb-9bf8-8be1ac92df96.png">

## Changelog entry

* Enhance admin bar implementation to be powered by the `googlesitekit.data` registry and its stores.

**Comment by benbowler** [comment]
IB added.

**Comment by felixarntz** [comment]
@benbowler IB mostly LGTM, we'll also need to remove the flag from the `resetFeatures` function though which is used in Storybook. Can you add this to the IB and then move over to Execution Backlog?

**Comment by benbowler** [comment]
Updated IB based on @felixarntz feedback and added and estimate. Moving to Execution Backlog now.

**Comment by benbowler** [comment]
Pushed and added a QA Brief

**Comment by benbowler** [comment]
I reversed the blocking here. Otherwise, we have to build out conditional logic to show the previous and new version of the admin bar in Storybook. It's simpler to switch to the new data-driven admin bar and then we only have to update Storybook to show the new admin bar.

**Comment by benbowler** [comment]
Fixed the merge conflict with develop.

**Comment by cole10up** [comment]
### QA ❌

**Tested:**

Checked on my personal site and I'm seeing differences between legacy admin bar menu and the latest SK admin bar

SK:
![image](https://user-images.githubusercontent.com/57115907/107178181-78e9f780-6988-11eb-93a6-59723069a4d9.png)

Admin:
![image](https://user-images.githubusercontent.com/57115907/107178203-843d2300-6988-11eb-8549-c83d4ca4d27e.png)

Checked individual page stats:
![image](https://user-images.githubusercontent.com/57115907/107178233-928b3f00-6988-11eb-89dc-818edf3b23a9.png)

@benbowler see above. Added you to my site for review

**Comment by felixarntz** [comment]
@cole10up Was this using a production build? It might be that the numbers are slightly different because we fixed some date range offsets in all the refactored code. Can you test this again using a development build, focusing on the comparison between the refactored version of the Site Kit dashboard (the one on top) with the new admin bar?

cc @benbowler

**Comment by cole10up** [comment]
### QA ❌

Thanks @felixarntz 

Retested on a development build:

Admin:
![image](https://user-images.githubusercontent.com/57115907/107320663-02b3c680-6a56-11eb-9c07-c695f8927880.png)

Hover state testing a smaller window/mobile is looking pretty rough:
![image](https://user-images.githubusercontent.com/57115907/107321223-03009180-6a57-11eb-8eed-70a2916a11b6.png)

Individual page stats:
![image](https://user-images.githubusercontent.com/57115907/107320845-5aeac880-6a56-11eb-85de-e67a9ca1d81a.png)

Looking good for individual page stats and the admin bar using a development build. Issue with smaller window/mobile above.

@benbowler

**Comment by aaemnnosttv** [comment]
@benbowler I took a closer look at this and confirmed that the appearance looks broken from 601px to 782px (inclusive) which sounds to be the only thing remaining here.

**Comment by benbowler** [comment]
Thanks @aaemnnosttv and @cole10up, I saw this separately on my personal site as well but I didn't track it down to this specific breakpoint.

Addressing it now.

**Comment by benbowler** [comment]
I've addressed this in a [new PR](https://github.com/google/site-kit-wp/pull/2776).

![2021-02-09 12-41-28 2021-02-09 12_42_49](https://user-images.githubusercontent.com/119352/107365577-e3a84980-6ad4-11eb-9b50-494be180007c.gif)

**Comment by cole10up** [comment]
### QA ✅ 

Retested:
![image](https://user-images.githubusercontent.com/57115907/107465500-55a18280-6b17-11eb-8fa3-07681d8a56e2.png)

Looks good on my end, sending to approval
