### ISSUE TITLE
Introduce AdSense utility function `isZeroReport` and use it in new widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2242]
There should be a new AdSense utility function `isZeroReport`, similar to the legacy `isDataZeroAdSense` function but without some of the legacy details. The new function should be used in all refactored AdSense widgets for the respective conditional which takes care of returning the "no-data" component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new function `isZeroReport` should be added in `assets/js/modules/adsense/util/is-zero-report.js`:
    * It should expect a `report` object like the one coming from the `modules/adsense` `getReport` selector.
    * If `report` is `undefined`, it should return `undefined` (to account for loading state).
    * Otherwise, it should return `true` if `report?.rows` is not set or empty or if `report?.totals` is not set or empty. It should also return `true` if none of the values in `report.totals` is greater than 0.
    * Otherwise it should return `false` (i.e. there _is_ data).
* The `DashboardSummaryWidget` component should use the above function instead of manual checks, for all reports `today`, `period`, `daily`.

## Implementation Brief

* Create a new `assets/js/modules/adsense/util/is-zero-report.js` file;
* Add a new `isZeroReport` function to the `is-zero-report.js` file that satisfies requirements defined in the AC section;
* Add `export * from './is-zero-report';` to the `assets/js/modules/adsense/util/index.js` file;
* Update the `DashboardSummaryWidget` component to use the new `isZeroReport` function instead of manual checks, for all reports.

### Test Coverage

* Create a new `assets/js/modules/adsense/util/is-zero-report.test.js` file;
* Add tests to check the `isZeroReport` function.

### Visual Regression Changes

* No visual changes should occur as a result of these changes.

## QA Brief

* Check the `DashboardSummaryWidget` component to make sure it uses the new `isZeroReport` function for all reports.
* There should be no visual changes on the dashboard page.

## Changelog entry

* Improve logic to determine whether an AdSense API report response is "empty", via new `isZeroReport` function for AdSense.

**Comment by felixarntz** [comment]
IB ✅

**Comment by caseymorrisus** [comment]
QA ✅
