### ISSUE TITLE
Introduce Analytics utility function `isZeroReport` and use it in new widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2243]
There should be a new Analytics utility function `isZeroReport`, similar to the legacy `isDataZeroForReporting` function but without some of the legacy details. The new function should be used in all refactored Analytics widgets for the respective conditional which takes care of returning the "no-data" component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new function `isZeroReport` should be added in `assets/js/modules/analytics/util/is-zero-report.js`:
    * It should expect a `report` object like the one coming from the `modules/analytics` `getReport` selector.
    * If `report` is `undefined`, it should return `undefined` (to account for loading state).
    * Otherwise, it should return `true` if `report?.[ 0 ]?.data?.rows` is not set or empty or if `report?.[ 0 ]?.data?.totals?.[ 0 ]` is not set or empty. It should also return `true` if none of the values in `report[ 0 ].data.totals[ 0 ]` is greater than 0.
    * Otherwise it should return `false` (i.e. there _is_ data).
* The following (widget) components should use the above function instead of manual checks, for all reports:
    * `DashboardAllTrafficWidget`
    * `DashboardBounceRateWidget`
    * `DashboardGoalsWidget`
    * `DashboardPopularPagesWidget`
    * `DashboardUniqueVisitorsWidget`
    * `DashboardTopEarningPagesWidget` (AdSense)

## Implementation Brief

* Create a new `assets/js/modules/analytics/util/is-zero-report.js` file;
* Add a new `isZeroReport` function to the `is-zero-report.js` file that satisfies requirements defined in the AC section;
* Add `export * from './is-zero-report';` to the `assets/js/modules/analytics/util/index.js` file;
* Update components listed in the AC to use the new `isZeroReport` function instead of `isDataZeroForReporting` or `! data || ! data.length`.

### Test Coverage

* Create a new `assets/js/modules/analytics/util/is-zero-report.test.js` file;
* Add tests to check the `isZeroReport` function.

### Visual Regression Changes

* No visual changes should occur as a result of these changes.

## QA Brief

* Check the components defined in the AC to make sure they use the new `isZeroReport` function.
* There should be no visual changes on the dashboard page.

## Changelog entry

* Improve logic to determine whether an Analytics API report response is "empty", via new `isZeroReport` function for Analytics.

**Comment by felixarntz** [comment]
IB ✅

**Comment by benbowler** [comment]
@felixarntz we need your comment in the PR https://github.com/google/site-kit-wp/pull/2369#discussion_r525125512

**Comment by felixarntz** [comment]
@benbowler Replied.

**Comment by aaemnnosttv** [comment]
@felixarntz @benbowler I'm getting an error now due to the utility allowing `undefined` to pass through which is possible due to the selectors in some widgets defining `loading` as `! isResolving`, but this can result in data being `undefined` initially before `loading` is set to true (before resolvers start). 

https://github.com/google/site-kit-wp/blob/4708e025503a007f27f5b45e9d15295f7d8f8952/assets/js/modules/analytics/components/dashboard/DashboardUniqueVisitorsWidget.js#L90

E.g. on the dashboard, I'm getting this:

```
Cannot read property '0' of undefined

    in DashboardUniqueVisitorsWidget (created by WhenAnalyticsActive(DashboardUniqueVisitorsWidget))
    in WhenAnalyticsActive(DashboardUniqueVisitorsWidget) (created by WidgetRenderer)
    in div (created by Widget)
    in div (created by Widget)
    in Widget (created by WidgetRenderer)
    in div (created by WidgetRenderer)
    in WidgetRenderer (created by WidgetAreaRenderer)
    in div (created by Row)
    in Row (created by WidgetAreaRenderer)
    in div (created by Grid)
    in Grid (created by WidgetAreaRenderer)
    in div (created by Cell)
    in Cell (created by WidgetAreaRenderer)
    in div (created by Row)
    in Row (created by WidgetAreaRenderer)
    in div (created by WidgetAreaRenderer)
    in div (created by Grid)
    in Grid (created by WidgetAreaRenderer)
    in WidgetAreaRenderer (created by WidgetContextRenderer)
    in div (created by WidgetContextRenderer)
    in WidgetContextRenderer (created by DashboardApp)
    in div (created by Cell)
    in Cell (created by DashboardApp)
    in div (created by Row)
    in Row (created by DashboardApp)
    in div (created by Grid)
    in Grid (created by DashboardApp)
    in div (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by GoogleSitekitDashboard)
    in GoogleSitekitDashboard
    in RestoreSnapshots (created by Root)
    in ErrorHandler (created by Root)
    in Root
```

This happens here https://github.com/google/site-kit-wp/blob/4708e025503a007f27f5b45e9d15295f7d8f8952/assets/js/modules/analytics/components/dashboard/DashboardUniqueVisitorsWidget.js#L121 because `loading` is false and `sparkLineData` is `undefined` 

I think E2E didn't catch this because E2E runs in "production" mode and this is triggered by new widgets. Updating the logic for `loading` to use `! hasFinishedResolution` instead works. Should this be done as a follow-up to this issue or another one though? Other widgets may be affected as well this is just what I've run into so far, but I recall we had to use similar logic in settings components before too.

**Comment by felixarntz** [comment]
@aaemnnosttv Good point! I've opened #2436 to fix this throughout the plugin. While this doesn't affect production, would be great to fix it for the same release (1.22.0). It should be a fairly small issue, we should prioritize it and move something else to the following sprint as needed.

**Comment by benbowler** [comment]
@aaemnnosttv @felixarntz I can see that #2436 has now been completed, are there any additional actions to take on this issue or can it now proceed to QA?

**Comment by aaemnnosttv** [comment]
This is good for QA now @benbowler now that it isn't blocked by the unrelated error 👍

**Comment by benbowler** [comment]
Thanks for un-assigning.

**Comment by tofumatt** [comment]
QA ✅
