### ISSUE TITLE
Refactor `TableOverflowContainer` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2248]
The `TableOverflowContainer` component should be refactored to become a functional component using hooks, and it should be moved to its own component file.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `TableOverflowContainer` component should be refactored to a functional component using hooks.
* It should be moved out of `assets/js/components/data-table.js` into its own file `assets/js/components/TableOverflowContainer.js`.
* All import references should be updated accordingly.
* A global Storybook story should be added for `TableOverflowContainer`, with some manually created table with any rows and columns inside - it should be a fairly large table to demonstrate the overflow capacity (e.g. 30 rows, 15 columns or something like that).

## Implementation Brief

* Create a new `assets/js/components/TableOverflowContainer.js` file that exports `TableOverflowContainer` functional component;
* Update all from `data-table.js` file to use the new `TableOverflowContainer.js` file to import `TableOverflowContainer` component.
* Replicate the logic from the legacy component in the new `TableOverflowContainer` component:
  * Use the `useState` hook to define `isScrolling` state property;
  * Use the `useEffect` hook to add an event listener for the `resize` event.
* Remove the legacy `TableOverflowContainer` component from the `assets/js/components/data-table.js` file.
* Add a new story to the "global" section of the storybook for the new `TableOverflowContainer` component (see requirements in the AC section).

### Test Coverage

* Not needed

### Visual Regression Changes

* Not needed

## QA Brief

* Check that all imports of the `TableOverflowContainer` component use the new file.
* Check that the new component replicates the logic from the legacy one.
* Check that there is no visual regression caused by the new component.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by caseymorrisus** [comment]
QA ✅
