### ISSUE TITLE
Unable to Authenticate with Google

### ISSUE THREAD

**Issue by sliceypete** [google/site-kit-wp#225]
Currently trying to configure SiteKit but I can get past step two.

I can create the Client ID, but on step two "Authenticate with Google" I end up on a blank screen after signing into google.

I choose my gmail account, then grant permission for 
- "View and mange Search Console data for your verified sites"
- Manage the list of sites and domains you control

It then brings me to a page to "Confirm your choices", I leave everything checked and hit "allow".

After clicking allow I get tossed to a blank page

URL: https://www.XXXX_XXXX.com/?oauth2callback=1&code=4/hAFKsFsTKkKycb8pHRz356RuWd5OPzM6h7m_qMegFntwSfgqfwRlFRx65NLMc2IYoyURThjheRwS3g9sdiLcejY&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/webmasters%20https://www.googleapis.com/auth/siteverification&authuser=0&session_state=f7b5b74f17eaf6887a4e84a4b9955656dc2afbe7..c65e&prompt=consent

Going back to the Sitekit dashboard states I am still on step 2 and I should sign into Google.

I have try multiple browsers (safari, chrome) and using private windows.

I am not sure what to try next.

Let me know if I should provide more infomation

**Comment by jamesozzie** [comment]
@sliceypete As you have checked from a private window can you next try to check with any caching or security plugins deactivated? Also let me know if you have the ModSecurity active if using a CPanel host.

**Comment by dbrado** [comment]
I'm getting the same result only I'm thrown back to my dashboard (no blank screen) I then have to go into site kit plugin only to find I'm still on step two

**Comment by jamesozzie** [comment]
@dbrado Do you have any security/firewall or caching plugins active on your site? Can you try the following: 
- Remove the [Analytics module](https://i.imgur.com/6ppIDwZ.png) (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
- Temporarily deactivate your other active WordPress plugins
- Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)

**Comment by kelwin17** [comment]
same issuee

**Comment by sliceypete** [comment]
@jamesozzie Just tried what you suggested and I got it working! Thanks for all the help!

I just had to disable my caching & security plugin to Authenticate, once it completed I re-enabled my plugins, no problems so far.

**Comment by jamesozzie** [comment]
@kelwin17 Thanks for letting us know. 

@sliceypete Have you tried all the suggestions above? If so please inform me if you have modsecurity active or any other Firewall rules within your current web host.
