### ISSUE TITLE
Modify behavior of `quarter` widgets to still render two columns in a single row on mobile viewports

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2250]
In the Widget API, widgets with a registered width of `quarter` are configured to fill the entire grid row on mobile viewports. However, this is different from how such widgets are rendered today in the "legacy widgets". See last two screenshots in https://github.com/google/site-kit-wp/issues/1898#issuecomment-693178796 for the visual disparity.

The behavior should be changed so that `quarter` widgets only take half the grid row width on mobile viewports. Note that they also behave differently on tablet viewports, however for tablets the new behavior is actually more appropriate since with the old behavior the row content gets pretty cramped. Therefore the Widget API behavior should only be changed for mobile viewports.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `WidgetAreaRenderer` component should be modified so that on mobile viewports `quarter` widgets only fill half the width of a grid row (via `mdc-layout-grid__cell--span-2-phone` CSS class).

## Implementation Brief

* Add `'mdc-layout-grid__cell--span-2-phone'` to `WIDTH_GRID_CLASS_MAP[WIDGET_WIDTHS.QUARTER]` in [`assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js`](https://github.com/google/site-kit-wp/blob/59dd50c732dd2849f903c0e098726cfb8e4c3d24/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L42)

### Test Coverage

* No additional tests needed for this change.

### Visual Regression Changes

* If any widget VRTs were relying on the (incorrect) "full-width-on-mobile" behaviour, they'll need updating.

## QA Brief

* Replicate the steps at https://github.com/google/site-kit-wp/issues/1898#issuecomment-693178796 but notice that "quarter"-sized widgets are now half-width on mobile.

## Changelog entry

* Modify widgets registered with `quarter` width to render for half the screen width on mobile viewports.

**Comment by saideepesh000** [comment]
@felixarntz, hi can I work on this

**Comment by felixarntz** [comment]
IB ✅ 

@tofumatt Wouldn't this one be worth using the 1 estimate? :)

**Comment by felixarntz** [comment]
@saideepesh000 Thanks for your interest in helping on this! We would like to get this implemented within the next 2 weeks, do you think you'll be able to create a pull-request with the fix described in the "Implementation Brief" above? It'd be great to have you as a contributor 🎉

**Comment by saideepesh000** [comment]
@felixarntz, Yes, I think it would be fairly an easy issue.

**Comment by saideepesh000** [comment]
> 
> 
> @felixarntz, Yes, I think it would be fairly an easy issue.

Edit: Actually it is such a huge project that I broke my system while cloning and installing it, and finally I could not(npm run build) build the code for development. Sorry for the inconvenience and I may not going to work on this. Thanks

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:** 

- Activated SK and GA within the development build. 
- Observed that quarter-sized widgets are now half-width on mobile.

Dashboard on mobile
![image](https://user-images.githubusercontent.com/73545194/98953836-25f2d680-2538-11eb-92a7-47a9bba86de3.png)

Dashboard on tablet 
![image](https://user-images.githubusercontent.com/73545194/98953923-3a36d380-2538-11eb-8e8a-bc5323a33b4e.png)

Analytics on mobile 
![image](https://user-images.githubusercontent.com/73545194/98953967-4458d200-2538-11eb-98b5-7ac6a2ea1b69.png)

![image](https://user-images.githubusercontent.com/73545194/98954005-4f136700-2538-11eb-86dd-00752043a090.png)

Single post on mobile
![image](https://user-images.githubusercontent.com/73545194/98956635-3bb5cb00-253b-11eb-923d-fedecd9ac478.png)
