### ISSUE TITLE
Combine similar CTA components returned from widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2252]
Widgets may return certain predefined components to indicate certain states:
* `ReportError`
* `ReportZero`
* `ActivateModuleCTA`
* `CompleteModuleActivationCTA`

The last three of those are module-specific and will result in the same UI for each instance they are displayed in (for the same module). If multiple widgets next to each other return the same of those components (i.e. same component with same props), such components should be aggregated and only displayed once. For example, if the Analytics module is not active, only a single `ActivateModuleCTA` for Analytics should be displayed in the "Search Funnel" widget area instead of two, even though it results from two different widgets.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Multiple instances of `ReportZero`, `ActivateModuleCTA`, and `CompleteModuleActivationCTA` returned by adjacent widgets in the same row should be combined per the module that they apply to.
    * The widget widths of widgets combined should be combined. For example, three quarter widgets returning the same component for the same module should result in a single three-quarter width version of that component being rendered.
    * For example, if two quarter adjacent widgets return `ReportZero` for Search Console and the next two quarter widgets return `ActivateModuleCTA` for Analytics, they should be combined to be one half `ReportZero` for Search Console and one half `ActivateModuleCTA` for Analytics.
    * Components should not be combined if they would span across multiple rows. For example, if in the above scenario there was another two quarter widgets returning `ActivateModuleCTA` for Analytics, they should be combined with each other, but not with the previous combination of two `ActivateModuleCTA` for Analytics because this would mean they would be combined across rows, which would mess up the UI.
* Widgets should not have to set state for this to work. They should only have to return the specific comments, and those components should internally support handling the necessary details (e.g. via state and `useEffect` or similar).
* There should be Storybook coverage for widgets where some of them return certain special state components, some in ways that would be combined etc., to test the behavior. The following stories in particular should be included:
    1. 4 quarter widgets: Normal, `ReportZeroData` Search Console, `ReportZeroData` Analytics, `ActivateModuleCTA` AdSense
    2. 4 quarter widgets: `ReportZeroData` Search Console, `ReportZeroData` Search Console, `ReportZeroData` Analytics, `ReportZeroData` Analytics
    3. 4 half widgets: `ReportZeroData` Search Console, `ActivateModuleCTA` Analytics, `ActivateModuleCTA` Analytics, `ActivateModuleCTA` AdSense
    4. 2 half widgets `CompleteModuleActivationCTA` Search Console, 1 quarter widget `CompleteModuleActivationCTA` Search Console, 1 quarter widget `CompleteModuleActivationCTA` Analytics, 1 quarter widget "normal", 1 quarter widget `CompleteModuleActivationCTA` Analytics

## Implementation Brief

* The `core/widgets` datastore should receive a new action:
    * `setWidgetState( slug, Component, metadata = {} )` receives the `WPComponent` and props that are relevant to indicate "commonalities" (i.e. widgets with the same `Component` and `metadata` would be combined).
    * `unsetWidgetState( slug, Component, metadata = {} )` receives the same parameters as `setWidgetState` and will unset the corresponding widget state.
* The `core/widgets` datastore should receive a new selector:
    * `getWidgetState( slug )` returns an object with `Component` and `metadata` properties from above.
* New components `WidgetReportZero`, `WidgetActivateModuleCTA`, and `WidgetCompleteModuleActivationCTA` should be introduced:
    * They should require a `widgetSlug` prop.
    * They should require a `moduleSlug` prop and wrap the respective component without the `Widget*` prefix. They should also pass on any other props to the child component.
    * They should rely on `useEffect` to call `setWidgetState` with a cleanup callback to call `unsetWidgetState`.
    * The existing `ActivateModuleCTA` and `CompleteModuleActivationCTA` components should be modified to have their `slug` prop renamed to `moduleSlug` so that the signature matches exactly their `Widget*` variants (minus the `widgetSlug` prop). For `ReportZero`, the prop is already called `moduleSlug`.
* Every widget should receive props `WidgetReportZero`, `WidgetActivateModuleCTA`, and `WidgetCompleteModuleActivationCTA`, which are wrapped/scoped versions of the general components mentioned above - scoped as in that the `widgetSlug` is already internally passed there, so that the widget component that may render them doesn't manually need to pass the slug, which would be error-prone.
* Remove `AnalyticsInactiveCTA` and rely on `ActivateModuleCTA` instead, allowing widgets to consistently use the latter component and without requiring us to implement a `WidgetAnalyticsInactiveCTA` which would be overly specific. For now, let's just move the alternative title and description into the `ActivateModuleCTA` component to still have them centralized. This should be revisited and improved - let's just add a TODO for now, as we shouldn't update the canonical module description etc in this issue.
* Modify the existing `getWidgetClassNames()` into a `getWidgetLayout()` that does not only return the resulting class names for each widget, but also the final column width for each widget and the row index for each widget (while there's only a single `Row` component in a widget area, widgets may extend beyond the visual row and thus be spread across multiple rows).
* Introduce a new `combineWidgets()` function that receives the active widgets, their current widget states, plus the class names, column widths and row indexes from `getWidgetLayout()`. This function will take care of detecting whether consecutive widgets in the same row have a similar state (i.e. same `Component` and `metadata`). If so, adjust class names and specify override components (see below) as necessary.
* Update `WidgetRenderer` so that it can receive an optional `OverrideComponent` prop. If it is passed, render that one instead of the registered widget component. Technically, still render the actual widget component too but hide it via CSS. This is necessary for the hooks to work.
* Update `WidgetAreaRenderer` to use `getWidgetLayout()` and then `combineWidgets()`. Then pass the return values of the latter (i.e. the final CSS class names and the potential override components) to `WidgetRenderer`.
* Add the Storybook stories from the ACs under `Global/Widgets`.
* Merge #2538.

### Test Coverage

* Add Jest tests for the new `getWidgetLayout` and `combineWidgets` functions.
* Add Jest tests for the new `Widget*`-prefixed components.

### Visual Regression Changes

* N/A

### Regular
1. Use a development build.
2. Set up Site Kit without any extra module activated.
3. Ensure that the CTA to set up Analytics and the CTA to set up PageSpeed Insights look exactly the same for the new widgets API-powered part of the dashboard as it does for the legacy part of the dashboard.

### Engineering
1. Check the `Global/Widgets/Widget Area\Special combination states` story in Storybook.
2. Ensure that all 4 stories from the ACs are implemented and that the widgets within them are combined as expected:
    * Adjacent widgets of the same special type (`ReportZero`, `ActivateModuleCTA`, `CompleteModuleActivationCTA`) must be combined as long as they are for the same module.
    * Any blue box must span the grid column width that all the widgets that it is resulting from would have spanned, had they been rendered regularly (i.e. without a special state).

## Changelog entry

* Implement logic to automatically combine UI for widgets that are in special states, e.g. widgets without sufficient API response data, or widgets that require a specific module to be set up first.

**Comment by felixarntz** [comment]
@aaemnnosttv Let me know your thoughts on the preliminary IB I added here. We can further discuss this in our meeting, let's finalize it then.

**Comment by aaemnnosttv** [comment]
@felixarntz 

> Multiple instances of `ReportZero`, `ActivateModuleCTA`, and `CompleteModuleActivationCTA` returned by adjacent widgets in the same row should be combined per the module that they apply to.

Just to clarify, I think we want to combine sibling widgets in the same row, not necessarily only those that are directly adjacent, correct? Things are already quite complicated as it is and this would make it even more so, but I don't think the immediate next/previous element is as important as those within the same row.

Also, a widget area only renders a single row of widgets, correct? I think you mentioned before that it can be multiple rows but I only see a single `<Row>` for `widgetsOutput` in the renderer component.

Regarding the IB, I would prefer to avoid using the datastore for managing this as I don't think it offers much benefit except for it's lack of coupling from the component hierarchy. In this case however, I think the hierarchy is particularly more relevant than others and even useful as it defines the boundary for aggregation. Let's see if we can come up with a solution that uses local state or otherwise more hierarchically-scoped.

I think we should be able to do something like this instead...see below. The key would be to make the object unique according to the `metadata` as you said, but I think we can use the same technique. We would only then need access to the same values for calculating how many instances of a component had been hidden (i.e. total - 1). let me know what you think:
https://codesandbox.io/s/singular-render-pe4ht

**Comment by felixarntz** [comment]
@aaemnnosttv 
> Also, a widget area only renders a single row of widgets, correct? I think you mentioned before that it can be multiple rows but I only see a single `<Row>` for `widgetsOutput` in the renderer component.

Oh, now I see where the confusion came from. Yes, it renders only one `Row` component, but the widgets will automatically float across multiple (visual, not React) rows if their grid classes extend the available 12 column grid. That's what I mean when I say widget areas can contain multiple rows.

So yes, we should only combine similar widgets in the same row, but that requires us to know the visual row layout already, rather than relying on `Row`.

> Regarding the IB, I would prefer to avoid using the datastore for managing this as I don't think it offers much benefit except for it's lack of coupling from the component hierarchy.

Sounds good to me, I'll update those parts.

> I think we should be able to do something like this instead...see below.

After revisiting this end of last week, I don't think the approach of rendering only the first instance of a type is a good approach here because of the following: We'll want to support in the future passing custom messages to those CTAs like "Looks like there are no visitors." etc. However, those messages **should not** be part of the `metadata` that affects whether the widget has a similar state as another one. In other words, if we rendered the first one of a group, we'd potentially render a text like "Looks like there are no visitors." for other widgets that display different things as well, which would be incorrect - so for those cases we need to instead render the more generally applicable "Analytics gathering data" or something content. Therefore I think we'll need to just bypass rendering those actual components completely and instead render an overarching more general one.

**Comment by felixarntz** [comment]
@aaemnnosttv Can you have a look at this once you're back?

**Comment by felixarntz** [comment]
@aaemnnosttv I've proceeded with the PR and pretty much completed the implementation per the IB. Please review the IB and PR. Maybe we can clean up a bit the approach of hiding components via CSS - let's discuss next week.

**Comment by aaemnnosttv** [comment]
Sounds good @felixarntz – we've already discussed this one so much I think the IB has already been approved here, we were mostly deciding between the various approaches we had discussed. While I would like to have tried the alternate approach to compare with, I don't think the two are that different in principal (yours uses the datastore whereas mine uses component state). We can always iterate on this to optimize if/where needed so I'm not really worried about it and this has already been delayed long enough.

This is basically IB ✅  and we continue with your PR (not sure if it's 100% ready for review yet or not?) but would you please  complete the Test Coverage and VRT sections above? Also, is 19 still an accurate estimate? I feel like this one is probably closer to a 30, but that may be a bit skewed by how much of the time has been definition so far. Once you've added/reviewed these, please go ahead and move it to the appropriate next column 👍

**Comment by felixarntz** [comment]
@aaemnnosttv Added a note about test coverage, I think it makes most sense to add Jest tests for the new utility function which is about the heavy lifting and complex logic here. And we can also add Jest component tests for the `Widget*` wrapper components.

The PR is ready for review production code-wise, the tests are still to add. With those still needed, I agree bumping the estimate to 30 makes sense. The definition was most of the work here though overall, so far I've invested about 15 hours into writing the actual code.

I'll move this to CR, it would be great if you could review the new functions etc before I add tests for them, mostly in terms of whether we want to keep the signatures, approach etc. I'll then add tests in the first iteration.

**Comment by wpdarren** [comment]
### QA Update: Failed  ❌ 

I have some observations between the new widgets API-powered part of the dashboard to legacy.

1. The top part of the dashboard (I'm assuming this is the new widgets API-powered part) has console data  where as the bottom part does not. It has a message saying `Search Console data is not yet available, please check back later.` I had assumed that this should be displaying data based on the connected account. 

2. The bottom part of the dashboard has large white borders around some of the modules, and the left and right margin/padding is smaller. The two areas do not seem to be aligned as per screenshots. 

3. The bottom part of the dashboard does not have the `Page Speed and Experience` header and also description underneath. 

These are the differences I can see, which according to the QAB, the two should look the same. 

Top part of the dashboard
![image](https://user-images.githubusercontent.com/73545194/105505051-71c5b700-5d03-11eb-886e-bdf317502427.png)

Bottom part of the dashboard
![image](https://user-images.githubusercontent.com/73545194/105505260-b5202580-5d03-11eb-91b2-48d819ffaa5d.png)

**Comment by felixarntz** [comment]
@wpdarren That looks like something we definitely need to fix. Before this PR (e.g. [development build of the latest release](https://github.com/google/site-kit-wp/wiki/refs/heads/master/google-site-kit-dev.zip)), on the same site you were testing, what did the Search Funnel widget look for you there? Did it also show 0s or the blue "No data available" block?

Trying to figure out whether this part got broken by this issue or was already incorrect before.

**Comment by wpdarren** [comment]
@felixarntz  It isn't something that I have observed before. This testing was done with a site with very little data. I can check with my other site with more data to see if I can replicate this. Would that help?

**Comment by felixarntz** [comment]
@wpdarren No this would indeed only happen with a site without Search Console data. I was meaning to ask, have you tested an older Site Kit version (e.g. 1.24.0) on that same site?

**Comment by felixarntz** [comment]
@cole10up Would be great if you could check for the above if you find time today ^

**Comment by wpdarren** [comment]
@felixarntz @aaemnnosttv 

With SiteKit 1.24.0 on development build.  I have re-tested this with the same site after clearing cache, refreshing the development build and the issue with search console data no longer exists. The data is now appearing in both sections of the dashboard. That said, the data is slightly different. See screenshots below.   

Top part of the dashboard:

![image](https://user-images.githubusercontent.com/73545194/105838286-ddad6580-600a-11eb-8ebb-8683e63665b9.png)

Bottom part of the dashboard. 

![image](https://user-images.githubusercontent.com/73545194/105838345-f1f16280-600a-11eb-99ae-7724077b15bd.png)

Please note that the two other issues [detailed here](https://github.com/google/site-kit-wp/issues/2252#issuecomment-765457521) still exist. 

`The bottom part of the dashboard has large white borders around console module under popularity. The left and right margin/padding is smaller. The two areas do not seem to be aligned as per screenshots.`

`The bottom part of the dashboard does not have the Page Speed and Experience header and also description underneath.
`

**Comment by felixarntz** [comment]
@wpdarren The data graph being slightly different is expected, it's due to another change from #2522. However, what still looks incorrect to me is that the "Clicks" widget in your screenshot shows 0. It never should, not in the old nor in the new part of the dashboard. That seems unrelated to the changes in this issue though, if you already encountered it in 1.24.0.

@aaemnnosttv What do you think? IMO we should be able to move this and open follow-up issues. @wpdarren Maybe we can jump on a call and go through it together?

**Comment by aaemnnosttv** [comment]
@felixarntz

> However, what still looks incorrect to me is that the "Clicks" widget in your screenshot shows 0. It never should, not in the old nor in the new part of the dashboard.

Could this not be due to there being non-zero clicks in the previous period? It should only not show zero if there are no clicks at all, but I don't think it's normal that it wouldn't show zero data if there was data in the previous period.

Unless there's actually a regression that somehow affects the current dashboard from the changes we introduced here, then it shouldn't block this issue and we can open new issues for the rest.

**Comment by wpdarren** [comment]
@felixarntz this is a site that gets no traffic from Google, so I suspect that there will be zero clicks in the previous period as @aaemnnosttv mentioned.  Happy to jump on a call if you would like to put a meeting in my diary. FYI. I am usually offline from 8am PST, but can stop a little later if this helps with the scheduling.

**Comment by aaemnnosttv** [comment]
@felixarntz @wpdarren I was able to reproduce this by adding a non-zero number of clicks into data for the previous range

![image](https://user-images.githubusercontent.com/1621608/105990496-37656c80-60ab-11eb-9843-84fe7c23facc.png)

This is indicated by the % difference/change arrow also since a zero-sum value in the previous period results in no change as shown above for the impressions.

I believe this is expected behavior as a zero data component should only be shown if there is no data at all, not just for the current period.

As for the difference in impressions shown, this wouldn't have changed as a result of the changes in this issue (if anything probably https://github.com/google/site-kit-wp/issues/2237).

Regarding the changes in widget padding – I think these are probably intentional, but @felixarntz will need to confirm.

> The left and right margin/padding is smaller. The two areas do not seem to be aligned as per screenshots.

Are you referring to the difference between the new widget-based dashboard and the legacy one? If so, this was intentional until now (to tell them apart) but we have #2646 to make them consistent.

> The bottom part of the dashboard does not have the Page Speed and Experience header and also description underneath.

Another one for @felixarntz to confirm.

**Comment by wpdarren** [comment]
`Are you referring to the difference between the new widget-based dashboard and the legacy one? `

@aaemnnosttv  Yes, I am.  Thanks for confirming this is covered in #2646.

**Comment by felixarntz** [comment]
@aaemnnosttv @wpdarren 
> Could this not be due to there being non-zero clicks in the previous period? It should only not show zero if there are no clicks at all, but I don't think it's normal that it wouldn't show zero data if there was data in the previous period.

Oh right, I didn't think about that. Yes, the blue "no data" box should only appear if there's no data in the current _and_ the previous period. So this is correct.

Looks like this issue is good to go. I'll move back to QA and reassign to you @wpdarren to confirm. If there's nothing else here, we can probably move to Approval.

**Comment by wpdarren** [comment]
@felixarntz I'd like you to confirm that you've seen these two points. 

- The left and right margin/padding of the widgets is smaller. The two areas do not seem to be aligned as per screenshots.

- The bottom part of the dashboard does not have the Page Speed and Experience header and also description underneath.

Top part of the dashboard
![image](https://user-images.githubusercontent.com/73545194/105505051-71c5b700-5d03-11eb-886e-bdf317502427.png)

Bottom part of the dashboard
![image](https://user-images.githubusercontent.com/73545194/105505260-b5202580-5d03-11eb-91b2-48d819ffaa5d.png)

**Comment by felixarntz** [comment]
@wpdarren Ah, thanks for flagging this. I think it's okay to proceed with it as is though, as it's not critical and not a result of this issue.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- The CTA to set up Analytics and the CTA to set up PageSpeed Insights look exactly the same for the new widgets API-powered part of the dashboard as it does for the legacy part of the dashboard.
