### ISSUE TITLE
Introduce `core/site` selector `getDeveloperPluginState`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2254]
There should be a new selector `getDeveloperPluginState` in the `core/site` store which returns information about whether the Site Kit developer plugin is installed etc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/site` store should receive a new selector `getDeveloperPluginState`.
    * The selector should have a resolver that via `createFetchStore` calls the existing `core/site/data/developer-plugin` REST datapoint and from the response populates its data.
    * The selector should return the response data object, or `undefined` if not loaded yet.

## Implementation Brief

* Create a new `assets/js/googlesitekit/datastore/site/developer-plugin.js` file:
  * Use `createFetchStore` to create a partial store for the `core/site/data/developer-plugin` REST endpoin:
    * Use `getDeveloperPluginState` as a base name;
    * Add a control callback function that sends a GET request to the `developer-plugin` endpoint;
    * Add a reducer callback function that saves received data under the `developerPluginState` property;
    * Assign created partial store to the `fetchGetDeveloperPluginState` variable.
  * Define the new `getDeveloperPluginState` resolver that calls `fetchGetDeveloperPluginState` action of the `fetchGetDeveloperPluginState` variable if there is no developer plugin data in the store yet;
  * Define the new `getDeveloperPluginState` selector that returns a value from  the `developerPluginState` property of the site datastore state;
  * Export the new partial datastore.
* Import developer plugin partial store in the `assets/js/googlesitekit/datastore/site/index.js` file and it into `Data.combineStores()` function call.

### Test Coverage

* Create jest tests that cover the new selector functionality.

### Visual Regression Changes

* Not needed.

## QA Brief

* Check that the new selector is implemented and correctly added to the site datastore.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
