### ISSUE TITLE
Reorganize setup components to separate from legacy components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2256]
Current and legacy components are right now both located in `assets/js/components/setup`. This should be reorganized so that all legacy components that we still need to keep for development sites support are separated.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `assets/js/components/setup-wizard` folder should be renamed to `assets/js/components/legacy-setup`.
* The `SearchConsole` and `SiteVerification` components in `assets/js/components/setup` should be moved to `assets/js/components/legacy-setup`.
* The `SetupWrapper` component should be renamed to `ModuleSetup`, and its file should be renamed to `ModuleSetup.js`.
* All import statements for those files should be updated accordingly.

## Implementation Brief

* Rename `assets/js/components/setup-wizard` to `assets/js/components/legacy-setup`
* Move the following components to `assets/js/components/legacy-setup`
    * `SearchConsole`, change the following imports:
        * `assets/js/components/setup-wizard/wizard-step-search-console-property.js`
    * `SiteVerification`, change the following imports
        * `assets/js/components/setup-wizard/wizard-step-verification.js`
* Refactor `SetupWrapper` component:
    * Rename the component to `ModuleSetup`
    * Rename the file to` ModuleSetup.js`
    * Change the imports in the following files:
        * `assets/js/components/dashboard-splash/dashboard-splash-app.js`
        * `assets/js/components/setup/setupwrapper.js`
        * `assets/js/googlesitekit-dashboard.js`
        * `assets/js/googlesitekit-module.js`
        * `stories/module-adsense-setup.stories.js`
        * `stories/module-analytics-setup.stories.js`
        * `stories/module-optimize-setup.stories.js`
        * `stories/modules-tagmanager-setup.stories.js`

### Test Coverage

* All tests should work as expected

### Visual Regression Changes

* No addition to VRT. Existing VRTs should pass.

## QA Brief

* Disconnect and reset the plugin.
* Site Kit setup should work as expected. No new functional changes.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@kostyalmm IB ✅ , can you add an estimate please? :)

**Comment by kostyalmm** [comment]
Estimate ✅

**Comment by cole10up** [comment]
### QA ✅

Disconnected and reconnected SK, ran a series of functional tests - no issues.

Sending to Approved.
