### ISSUE TITLE
Refactor `ErrorHandler` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2257]
The `ErrorHandler` component should be refactored to a functional component using hooks.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ErrorHandler` component should be refactored to a functional component using hooks.
* The component should use internal state as needed.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by rushilp2311** [comment]
Hi, @felixarntz I could take this issue.
I have read the Contributing guide.I did all that's given in the guide  but I am still not able to run  the site locally can you please guide me through it.

**Comment by asvinb** [comment]
@felixarntz Looks like our ErrorHandler component is acting like as an "Error Boundary" and as per the docs, https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries, only class components can be error boundaries. Thus we won't be able to refactor this one into a functional one.

**Comment by felixarntz** [comment]
@asvinb Thanks for looking into that, looks like we can't change this one. Closing as invalid for now.
