### ISSUE TITLE
Split legacy parts out of `DashboardSplashApp` component and refactor the modern parts

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2259]
The `DashboardSplashApp` should be refactored to become a functional component using hooks and the datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DashboardSplashApp` should be copied to a separate file in the same folder as `LegacyDashboardSplashApp`. They should then be separated accordingly:
    * The `LegacyDashboardSplashApp` should be kept almost untouched, it should **not** be refactored. However, all references to `usingProxy` should be removed, and only the functionality that assumes `! usingProxy` should be maintained (which is most of this component).
    * The `DashboardSplashApp` should then become a very simple functional component using hooks and the datastore:
        * It should rely on the `core/site` selector `isUsingProxy`. If `undefined`, it should return `null`. If `false`, it should just return the `LegacyDashboardSplashApp`. If `true`, it should just return the `SetupProxy` component.
* All components in `assets/js/components/dashboard-splash` except for the `DashboardSplashApp` should also be prefixed with `Legacy*`.
* Unrelated change: The `DashboardApp` (in `assets/js/components/dashboard`) should be changed to become a functional component - which is trivial because it doesn't include any logic.

## Implementation Brief
- Copy and rename the following file: `/assets/js/components/dashboard-splash/dashboard-splash-app.js` file to `LegacyDashboardSplashApp.js` in the same folder.
- Using `/assets/js/components/dashboard-splash/LegacyDashboardSplashApp.js` file
        - Remove all references to `usingProxy` while keeping `! usingProxy` references
- Using the file `/assets/js/components/dashboard-splash/dashboard-splash-app.js`,
	- Update component to be a function one, using `useState` for the component's state.
	- Add `import { STORE_NAME as CORE_SITE } from '../../googlesitekit/datastore/site/constants';`
	- Import useSelect `const { useSelect } = Data;`
	- Check if we are using the proxy using the following snippet: `const usingProxy = useSelect( ( select ) => select( CORE_SITE ).isUsingProxy() );`
	- If `usingProxy` is `undefined`, the component should return `null`. If `false`, it should just return the `LegacyDashboardSplashApp`. If `true`, it should just return the `SetupProxy` component.
- Using the folder:  /assets/js/components/dashboard-splash/
	- Rename `dashboard-splash-intro.js` to `LegacyDashboardSplashIntro.js`
	- Rename `dashboard-splash-main.js` to `LegacyDashboardSplashMain.js`
	- Rename `dashboard-splash-module.js` to `LegacyDashboardSplashModule.js`
	- Rename `dashboard-splash-notifications.js` to `LegacyDashboardSplashNotifications.js`
	- Rename `dashboard-splash-outro.js` to `LegacyDashboardSplashOutro.js`
	- Rename `dashboard-splash-service.js` to `LegacyDashboardSplashService.js`
- Update path references everywhere where above renamed files are mentioned.
- Using the file: `assets/js/components/dashboard/dashboard-app.js`
	- Update the component to be a functional one
	- Rename file to `DashboardApp.js` and updated path references accordingly.

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

* N/A

**Comment by asvinb** [comment]
@felixarntz For the DashboardApp, I've suggested in the IB to rename the file from `dashboard-app.js` to `DashboardApp.js` I'am even thinking about renaming all the files in assets/js/components/dashboard to be Pascal case. Let me know if you're ok with that, I'll tweak the IB to reflect that.

**Comment by felixarntz** [comment]
@asvinb Renaming the `DashboardApp` file makes sense to me in terms of these changes. Let's not worry about the other ones for now, there is #2260 that will eventually require all remaining files to be renamed anyway, so that's more suitable there.

The IB looks solid, only one thing is not mentioned there, which is that `LegacyDashboardSplashApp` will also require some modifications, it shouldn't just be an untouched copy of `DashboardSplashApp`: It should no longer contain `usingProxy` checks and only the functionality that currently is used for `! usingProxy` should be kept in there.

**Comment by asvinb** [comment]
@felixarntz I did mention about removing the usingProxy checks and keep only the ! usingProxy. It's mentioned in the first child of the first bullet point.  :)

**Comment by felixarntz** [comment]
@asvinb Can you clarify where? Maybe we're misunderstanding each other here or I'm not seeing where you referencing - there is no first child of the first bullet point in the IB as far as I can tell. It _is_ mentioned in the first child of the first bullet point of the ACs, but it's not mentioned in the IB :)

The IB only mentions to create `LegacyDashboardSplashApp` as a copy, and then further down it mentions that it should be included in `DashboardSplashApp` if `! usingProxy`. But the IB nowhere mentions any changes required to make _inside_ `LegacyDashboardSplashApp`, which is what I'm getting at. In that component, only the logic for `! usingProxy` should be kept.

**Comment by asvinb** [comment]
@felixarntz Would you believe I look at it many times and didn't notice that I was actually looking at the AC instead of the IB 🤦  Apologies for that. The IB has been updated.

**Comment by felixarntz** [comment]
@asvinb No worries, that's what I thought - it happens 👍 

IB ✅

**Comment by benbowler** [comment]
## QA Comment

Considering the other changes in this issue, should `assets/js/components/dashboard-splash/dashboard-splash-app.js` be renamed `assets/js/components/dashboard-splash/SashboardSplashApp.js`

**Comment by benbowler** [comment]
Ignore the above comment @asvinb, I was checking in the branch not the merged down version where this has been addressed.

## QA:Eng Approved ✅
