### ISSUE TITLE
Require component-based file names in `assets/js/components`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2260]
The existing ESLint rule to enforce file names to match their default export component names should also be enabled for any JS files within `assets/js/components`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing ESLint rule to enforce file names to match their default export component names should also be enabled for any JS files within `assets/js/components`.
* All remaining files within that directory that violate that requirement should be renamed accordingly.

## Implementation Brief
- Using `.eslintrc.json`
	- Update the `files` array for the `filenames/match-exported` rule to include `assets/js/components/*.js`
- Run `npm run lint:js`
- Fix all the ESLint errors by renaming the file names to match the exported name. For e.g `assets/js/components/modules-list.js` should be updated to `assets/js/components/ModulesList.js`
- Update all references to the new file names.

### Test Coverage

* 

### Visual Regression Changes
- No visual regressions should be noted.

## QA Brief

* Checkout the branch and run `npm run lint:js` - you should not see any linter violations for `filenames/match-exported`.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: all looks good!
