### ISSUE TITLE
Handle global error notifications via `googlesitekit-api`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2261]
The legacy data API includes some special error handling that sets global notifications. Some similar behavior was already implemented in `googlesitekit-api` relying on the datastore. This issue is exposing the new behavior behind a feature flag. It is furthermore about separating the related pieces from the rest of the notifications which is mostly legacy and should remain untouched.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `assets/js/components/notifications` folder should be renamed to `assets/js/components/legacy-notifications`. All import references should be updated accordingly.
* A new `assets/js/components/notifications` folder should be created.
* The components `AuthError` and `DashboardAuthScopesAlert` should be moved from the `legacy-notifications` folder to the `notifications` folder. The latter should be renamed to `UnsatisfiedScopesAlert`. Again, all import references should be updated accordingly.
* A new functional component `ErrorNotifications` should be added in `assets/js/components/notifications`. It should simply render both `AuthError` and `UnsatisfiedScopesAlert`.
* A new feature flag `storeErrorNotifications` should be introduced. It should be `true` for development builds, `false` for production builds.
* The `Header` component in `assets/js/components` should be modified: If the new `storeErrorNotifications` flag is `true`, the component should render the new `ErrorNotifications` component _right above_ the legacy `ErrorNotification` component.

## Implementation Brief

* Rename `assets/js/components/notifications` to `assets/js/components/legacy-notifications`, use your IDE for this so you can update references.
* Make directory `assets/js/components/notifications`
* Move `assets/js/components/legacy-notifications/AuthError.js` to `assets/js/components/notifications/AuthError.js`
* Move `assets/js/components/legacy-notifications/DashboardAuthScopesAlert.js` to `assets/js/components/notifications/UnsatisfiedScopesAlert.js`
* In `assets/js/components/notifications/UnsatisfiedScopesAlert.js`, rename the default function export `export default function UnsatisfiedScopesAlert()`
* Update all references from `DashboardAuthScopesAlert.js UnsatisfiedScopesAlert` to `UnsatisfiedScopesAlert.js UnsatisfiedScopesAlert`
* Update all references for all components in `assets/js/components/legacy-notifications` to the new location (previously: `assets/js/components/notifications`)
* Create `assets/js/components/notifications/ErrorNotifications.js`, it will look like this:

```js
import { Fragment } from '@wordpress/element';

import AuthError from './AuthError';
import UnsatisfiedScopesAlert from './UnsatisfiedScopesAlert';

export default function DashboardAuthScopesAlert() {
    return (
        <Fragment>
            <AuthError />
            <UnsatisfiedScopesAlert />
        </Fragment>
    )
}
```

* Add a feature flag, this will be either in webpack.feature-flags.config.js or feature-flags.json depending on the status of #2316
```js
storeErrorNotifications: { enabled: 'development' }
```

```js
import ErrorNotification from '../components/notifications/error-notification';
import * as LegacyErrorNotification from '../components/legacy-notifications/error-notification';

// SNIP
			</section>
		</header>
	{ featureFlags.storeErrorNotifications.enabled && ( <ErrorNotification /> ) }
	<LegacyErrorNotification />
</Fragment>

```            

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Reset site kit if already setup
* Sign in
* go to settings
* Start setup of a module
* press back before even allowing anything
* refresh or go to dashboard, same two error notifications must be visible. One from `ErrorNotification`(`withFilter`) other from `ErrorNotifications`.

## Changelog entry

* Add support for displaying datastore-driven global error notifications in the plugin header.

**Comment by felixarntz** [comment]
@ivankruchkoff IB ✅ , just one detail, I think you forgot to mention which file the last code snippet applies to (I assume it is the `Header` component).

For the future, I'd advise to use more abstract explanation for IBs rather than writing a chunk of the code already, since that makes it a bit hard to digest and discuss. At that point it almost becomes a partial code review (for example in one snippet you're incorrectly referring to an `ErrorNotification` component instead of `ErrorNotifications`; not a big deal since this is an IB, but just pointing that out). Furthermore, if another approach ended up being more feasible, a lot of code would have been unnecessarily written.

**Comment by felixarntz** [comment]
@kostyalmm Can you add the QA Brief here?

**Comment by kostyalmm** [comment]
QA brief ✅

**Comment by wpdarren** [comment]
@kostyalmm I have an incomplete module setup and can see the `incomplete setup` as seen in your screenshot, but the `error notifications` doesn't appear on the settings page within the module.  Where would you expect the notifications to appear, within settings or else where within SK?  FYI I am using the `develop` branch. 
 
![image](https://user-images.githubusercontent.com/73545194/100742644-14556e00-3416-11eb-9eb1-9a4c7ad8a8f0.png)

**Comment by kostyalmm** [comment]
@wpdarren I have updated the brief. The brief wasn't very accurate, my bad 😅

**Comment by wpdarren** [comment]
### QA update: ⚠️ Engineer to confirm 

@kostyalmm perfect.  Yes, I see the behaviour as expected from the QA brief ([Screenshot](https://user-images.githubusercontent.com/73545194/100750936-ac0c8980-3421-11eb-8c50-13c146357f59.png))  but I have an observation.  

Here are the steps to recreate this scenario:

1. I reset SiteKit 
2. Connect my Google account and sign in.
3. From within the dashboard (same happens in settings as well) I connect to a service, i.e. Analytics. 
4. For a brief 2-3 seconds the `error notifications` messages appear on the screen before the Google sign in page pops up (to connect my account) Here's a screencast https://d.pr/v/xenekd (sorry, couldn't attach it here) 

That wasn't happening before so want to make sure this is as expected.  It's very brief and you do get directed to Google signup page, which is the correct behaviour.  Please could you confirm?

**Comment by kostyalmm** [comment]
@wpdarren yes I am aware of this issue. This happens because when the user clicks on "Connect Service", the module is activated in the datastore(before the user is redirected to the google login flow). Since it is not setup yet(has unsatisfied scopes), the notification comes up.

Also, this `ErrorNotifications` component is rendered only when `showErrorNotifications` flag is enabled (only in dev right now). I think some more work will be done on this component before rolling out to prod. 

@felixarntz awaiting your confirmation on this.

**Comment by wpdarren** [comment]
@kostyalmm @felixarntz other than this observation, based on the QA brief, this has passed, but please let me know if you would like me to move this to approved or not, especially if there's additional work that needs completing. Thank you.

**Comment by felixarntz** [comment]
Good catch @wpdarren - this should definitely not be the case!

@kostyalmm This is somewhat due to a race condition: We need to refresh the authentication data after activating a module to know whether new scopes are required. But since the plugin caters for that by redirecting to the OAuth screen, it does not make sense for the error to pop up in this split second before the user will fix it. We'll need to somehow flag that the plugin is currently navigating away to OAuth, and in that case the error shouldn't be shown.

It's a problem that has come up in other places too with slightly different outcome. So far we've been using internal component state like `isNavigating` and `setIsNavigating`, but here that wouldn't work because the error is handled outside of the component. So maybe we'll need a datastore-wide version of that. What do you think?

cc @aaemnnosttv

**Comment by kostyalmm** [comment]
@felixarntz adding a `navigatingToOAuth` to `core/site` (or creating `global`/`core/global`) sounds fine to me. 🤔 

cc @aaemnnosttv

**Comment by aaemnnosttv** [comment]
@felixarntz I think the solution here shouldn't be specific to a particular navigation, since this will definitely come up again and like you said, we're already using some workarounds in various components.

Two solutions come to mind:
1. Add an event listener on page navigation events and update state in the store accordingly on navigation. Then we can expose this via selectors to components to be centrally navigation aware.
1. Make the datastore responsible for handling all navigation via actions. E.g. `dispatch( 'core/location' ).assign( url )`.  
This would set various state in the store before invoking the navigation itself.

I somewhat prefer the first option as the simplest and wouldn't require our actions to be used by the consumer since it would be driven by browser events. This may be problematic to do reliably cross-browser but I think [`onunload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event) should be a good start to look into.

**Comment by felixarntz** [comment]
@kostyalmm @aaemnnosttv @wpdarren We're a bit late for making those changes to this issue which has already been merged for the release. I think it'd make sense to open a follow-up issue to fix this remaining problem and prioritize for the upcoming sprint. Since that problem only occurs in a development build, we're okay shipping the already merged code without a user-facing regression.

@aaemnnosttv Can you open a follow-up issue with your ideas above? Then we can move this one to Approval probably.
