### ISSUE TITLE
Update REST_Routes tests to account for the new /batch/v1 endpoint

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#2264]
## Feature Description

The next version of WordPress will include a new endpoint that allows bulk operations on the REST endpoints. It has been already implemented and added to the core. It causes PHP Tests for the nightly build to fail. We need to adjust the `Core\REST_API\REST_RoutesTest::test_register` test to account for this change.

Here is the original ticket for the batch endpoint feature: https://core.trac.wordpress.org/ticket/50244

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* REST Route tests should only be concerned with Site Kit-registered routes (i.e. `google-site-kit/v1/*` endpoints only)
* The presence or absence of WP registered ["meta endpoints"](https://github.com/WordPress/wordpress-develop/blob/7be470140493a482d910576f9740450babea4a1c/src/wp-includes/rest-api/class-wp-rest-server.php#L96-L106) should not cause our tests to fail

## Implementation Brief

* Update `Google\Site_Kit\Tests\Core\REST_API\REST_RoutesTest::test_register` test to filter out other endpoints (not registered in the plugin) from the routes list received from the REST server.
* Update expected routes list not to include the root route (`/`).

### Test Coverage

* PHP tests should pass correctly for the night build.

### Visual Regression Changes

* No visual changes expected.

## QA Brief

* Check that PHPUnit tests pass for the nightly build.

## Changelog entry

* Fix failing PHPUnit tests for compatibility with upcoming WordPress 5.6.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

https://travis-ci.com/github/google/site-kit-wp/builds/205553763
![image](https://user-images.githubusercontent.com/1621608/101011656-53e19e80-356b-11eb-8c25-1d2154ebf7a1.png)
