### ISSUE TITLE
Error when disconnecting and trying to reconnect

### ISSUE THREAD

**Issue by alexshomper** [google/site-kit-wp#227]
## Bug Description
I downloaded and installed the latest version of the Site Kit Plugin. I went through the Installation Wizard without any Problems. Connected Google Analytics, Search Console, and Site Speed Insights. In the Site Kit Dashboard it said, that there might be something wrong with the API Key. So I disconnected Site Kit from my Account. Deactivated the Plugin and reactiveted it. Then I started the Installation again from the beginning, with Signing in to my Google Account, granting all the required access. But then the error occurs: "**You did not grant access to one or more of the requested scopes. Please grant all scopes that you are prompted for.**"

## Steps to reproduce
1. Install Site Kit and connect Google Account
2. Disconnect Google Account
3. Deactivate Site Kit
4. Reactivate Site Kit
5. Try reconnecting Google Account

## Screenshots

![Bildschirmfoto 2019-07-12 um 14 18 09](https://user-images.githubusercontent.com/359535/61128473-3b726f00-a4b2-11e9-86f8-ab153b33550c.png)

## Additional Context
 - PHP Version: 7.2.20
 - OS: OS X Yosemite
 - Browser Chrome
 - Plugin Version 1.0.0-beta.1.0.1
 - Device: iMac 27", End 2019

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by alexshomper** [comment]
Ok, I tried the same process again in an Inkognito Window, and it worked.
Signing in with my Google Account did all the job, I did not even have to reconnect Google Analytics, Search Console, and Site Speed Insights.

Plus: Sight Speed Insights does not produce the API Key Error anymore…

**Comment by jamesozzie** [comment]
@alexshomper Thanks for letting us know, and nice troubleshooting. Caching plugins and browser extensions can sometimes interfere during the setup stage.
