### ISSUE TITLE
Update GitHub actions and Travis CI jobs to explicitly use Composer v1

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#2270]
## Feature Description

Currently, our GitHub actions and Travis CI configuration rely on the `composer:latest` docker image to install composer dependencies. Unfortunately, the `latest` tag has been updated approximately an hour ago to point to the 2nd version of Composer and our CI/CD jobs start failing because they can't install composer dependencies. We need to explicitly specify the 1st version of Composer to be used until we rework our setup to be compatible with Composer v2.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* CI jobs relying on Composer shouldn't fail.

## Implementation Brief

* Merge #2269.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Verify that CI tests still pass.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Bringing this back to Execution as GitHub actions has updated their runners to use Composer v2 now.
https://github.com/actions/virtual-environments/blob/ubuntu18/20201026.1/images/linux/Ubuntu1804-README.md#php

**Comment by eugene-manuilov** [comment]
@aaemnnosttv #2282 is approved. Assigning it to you to merge it.

**Comment by tofumatt** [comment]
QA ✅
