### ISSUE TITLE
Allow registering module store name

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2271]
Right now there are a couple of places in the codebase where a module's store name is assumed to be `modules/{slug}`. While this is the default value and we exclusively rely on it and don't have modules with custom store names, it _is_ (and should be) allowed to be different. Therefore we should allow the store names to be registered.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `registerModule` action of the `core/modules` store should support an optional `storeName` argument to provide the module store's name.
    * The value should not have a default.
    * If no value is specified, it should be assumed that the module does not have its own datastore.
* Anywhere in the codebase where currently `modules/{slug}` is assumed to be the store name (except of course where this value is used as the default when creating a module store), it should instead be relied upon the `storeName` module registration value. If there is none, the functionality should be assumed to not exist and, where applicable and possible, use sane fallback values.

## Implementation Brief

* In `assets/js/googlesitekit/modules/datastore/modules.js`
	* Add `storeName: null` to [`moduleDefaults`](https://github.com/google/site-kit-wp/blob/fedee50421b4b8bcdefc4ed47bb49bdda3b39794/assets/js/googlesitekit/modules/datastore/modules.js#L49-L64)
	* add `storeName` to the objects passed as the second parameter and to the `settings` object return in the action payload.
	* Add `selectors.getModuleStoreName` as a registry selector that accepts a `slug`
		- selects `module = getModule( slug )`
			* returns `undefined` if the `module` is `undefined` (not resolved yet)
			* returns `module?.storeName || null`
* Update references to `modules/${ slug }` – for tests just update to something like `tests/` instead as it isn't particularly significant, but to ensure all previous uses are removed
	- `SettingsRenderer` + test
		- use `core/modules` for the store name to select `isDoingSubmitChanges` (passing through the `slug`) instead of selecting from the module store now that core selectors are in place
		- update `haveSettingsChanged` with a fallback value of `false` in case the module does not have a settings store
			- A module without settings cannot have changed settings so this works without changing any dependent logic
	- Modules `createInfoStore` in `assets/js/googlesitekit/modules/create-info-store.js` + test
		- Make `storeName` a required argument, require with `invariant`
		- Rename `options` to `args`, mark others as optional args in doc block
	- `createModuleStore` + test
		- Make `storeName` a required argument, require with `invariant`
		- Rename `options` to `args`, mark others as optional args in doc block
	- `controls[ SELECT_MODULE_REAUTH_URL ]` in `assets/js/googlesitekit/modules/datastore/modules.js`
		- use the new `getModuleStoreName` selector
		- Return early if the `storeName` is falsey
	- `actions.submitChanges` in `assets/js/googlesitekit/modules/datastore/settings.js`
		- change to be a normal action that returns an object
		- move current dispatch logic to a new registry control for the action
		- dispatch `submitChanges` via `core/modules` using the `slug` instead of using the module store directly  
		The core action already includes the same logic to return the same error if the module store does not have the `submitChanges` action
	- `selectors.*` in `assets/js/googlesitekit/modules/datastore/settings.js` + test
		- use the new `getModuleStoreName` selector
		- the existing conditional chaining will handle a non-existent `storeName` already

### Test Coverage

* Update relevant Jest tests for cases where `storeName` is now a required argument and add a test accordingly

### Visual Regression Changes

* N/A

## QA Brief

* Configure SiteKit with the Analytics integration
   * Navigate to the [SiteKit Plugin settings](http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-settings)
   * Click on "Analytics" to open the analytics settings
   * Click "Edit"
   * Edit the settings for the Analytics (such as *Let Site Kit place code on your site*)
   * Confirm that click save stores the new settings you have selected
   * Confirm that click cancel will **not** save the settings you selected

## Changelog entry

* Add `storeName` argument to `registerModule` action of the `core/modules` store to specify the name of the JS datastore for the module.

**Comment by felixarntz** [comment]
@ryanwelcher The changes described for `assets/js/googlesitekit/modules/datastore/modules.js` sound good, however we'll also need to update all `registerModule` calls from Site Kit modules to include the `storeName` argument, otherwise this will break in combination with the component changes where we should no longer assume `modules/${ slug }`.

One thing to describe a bit further in the IB is to e.g. give a list of files in which `modules/${ slug }` needs to be updated, and any related notes if doing this replacement is not trivial (e.g. if one of the components currently doesn't have access to the datastore etc.).

**Comment by felixarntz** [comment]
@aaemnnosttv Mostly LGTM, but a bit of feedback:
> * returns `module.storeName` otherwise (`module` should be an object)

While this somewhat makes sense, maybe we should account for that a module might not have a store (i.e. not pass `storeName`), in which case this would return `undefined`, which would be a bit odd because that is also the "loading" result. Maybe we _could_ add a "default" (contrary to what the ACs say), the empty string. This way the value is distinct, but still would evaluate to a false-y check, and it would indicate that the module exists but does not have a store.

The other thing is, since some modules may not have a `storeName`, we will need to account for that in the logic that uses the new selector. In async code that should be trivial with conditional clauses based on the return value. For components like `SettingsRenderer` though, we cannot do that since they use hooks, so in there I think it would make sense to add some checks for the dependant variables like `isDoingSubmitChanges` and `haveSettingsChanges` (I believe it would already work as is, but we should be strict enough to make it obvious that those variables could be `undefined`). For example, probably if `isDoingSubmitChanges` is `undefined`, the `useEffect` in there shouldn't do anything.

**Comment by aaemnnosttv** [comment]
> Maybe we _could_ add a "default" (contrary to what the ACs say), the empty string. This way the value is distinct, but still would evaluate to a false-y check, and it would indicate that the module exists but does not have a store.

Yeah, I think every module property should be defined in [`moduleDefaults`](https://github.com/google/site-kit-wp/blob/fedee50421b4b8bcdefc4ed47bb49bdda3b39794/assets/js/googlesitekit/modules/datastore/modules.js#L49-L64) but I like the idea of giving it a falsey default other than `undefined`. In this case I think `null` may be preferable over an empty string since it's more commonly used in the codebase as an intentional empty value. I'd rather not introduce yet another falsey value that means something else. `undefined` = loading or unintentionally not existent, `null` = not set or intentionally not existent (like a component).

> For components like `SettingsRenderer` though, we cannot do that since they use hooks, so in there I think it would make sense to add some checks for the dependant variables like `isDoingSubmitChanges` and `haveSettingsChanges` (I believe it would already work as is, but we should be strict enough to make it obvious that those variables could be `undefined`)

Sounds good I'll take another look and make sure those are covered 👍

**Comment by aaemnnosttv** [comment]
@felixarntz IB is updated and ready for another pass 👍

**Comment by felixarntz** [comment]
@aaemnnosttv 
> In this case I think `null` may be preferable over an empty string since it's more commonly used in the codebase as an intentional empty value. I'd rather not introduce yet another falsey value that means something else. `undefined` = loading or unintentionally not existent, `null` = not set or intentionally not existent (like a component).

SGTM!

IB ✅

**Comment by benbowler** [comment]
Increased the estimate slightly after speaking to @eclarke1.

**Comment by benbowler** [comment]
@aaemnnosttv dropped a note to discuss the last two points on this card when you're back next week.

**Comment by benbowler** [comment]
Added a QA brief

**Comment by tofumatt** [comment]
QA ✅

**Comment by aaemnnosttv** [comment]
Just found one instance of where this was missed due to a timing around the merge. Will open a quick follow-up PR to address it.

**Comment by eugene-manuilov** [comment]
QA :warning: 

Everything works as expected, but there is one thing that I think we need to address in the scope of this ticket. I am talking about hardcoded store names in module registration calls. I think we should use the appropriate `STORE_NAME` constants which can be imported from the module datastore `constants` files.

For example, the following is the Analytics module registration. It has its store name hardcoded:

https://github.com/google/site-kit-wp/blob/622f0bd76d21e752e4c2b1a5514c6d02b4f8daf5/assets/js/modules/analytics/index.js#L50-L59

But we should use this constant:

https://github.com/google/site-kit-wp/blob/622f0bd76d21e752e4c2b1a5514c6d02b4f8daf5/assets/js/modules/analytics/datastore/constants.js#L19

Same for other modules.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
