### ISSUE TITLE
Document functions on public googlesitekit.modules object

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2272]
The functions on the public API object `googlesitekit.modules` should be documented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All functions on the public API object `googlesitekit.modules` should be documented:
    * `activateModule`
    * `deactivateModule`
    * `registerModule`

## Implementation Brief

	/**
	 * Registers a module.
	 *
	 * @since 1.13.0
	 * @since 1.20.0  Introduced the ability to register settings and setup components.
	 * @since n.e.x.t Introduced the ability to add a checkRequirements function.
	 *
	 * @param {string}      slug                             Module slug.
	 * @param {Object}      [settings]                       Optional. Module settings.
	 * @param {string}      [settings.name]                  Optional. Module name. Default is the slug.
	 * @param {string}      [settings.description]           Optional. Module description. Default empty string.
	 * @param {string}      [settings.icon]                  Optional. Module icon. Default empty string.
	 * @param {number}      [settings.order]                 Optional. Numeric indicator for module order. Default 10.
	 * @param {string}      [settings.homepage]              Optional. Module homepage URL. Default empty string.
	 * @param {WPComponent} [settings.settingsEditComponent] Optional. React component to render the settings edit panel. Default none.
	 * @param {WPComponent} [settings.settingsViewComponent] Optional. React component to render the settings view panel. Default none.
	 * @param {WPComponent} [settings.setupComponent]        Optional. React component to render the setup panel. Default none.
	 * @param {Function}    [settings.checkRequirements]     Optional. Function to check requirements for the module. Throws a WP error object for error or returns on success.
	 */

* Edit the `assets/js/googlesitekit/modules/index.js` adding a new docblock comment to each of these three functions:
    * `activateModule`
      * Add a title and single-line description of this function to add a module to the store.
      * Add `@since`, `@param` and `@return` descriptions for each based on the [docblock of the internal function](https://github.com/google/site-kit-wp/blob/c279f1b156952de53aafbc0961ffbc0e502fa1e6/assets/js/googlesitekit/modules/datastore/modules.js#L143-L154).
    * `deactivateModule`
      * Add a title and single-line description of this function to deactivate a module in the store.
      * Add `@since`, `@param` and `@return` descriptions for each based on the [docblock of the internal function](https://github.com/google/site-kit-wp/blob/c279f1b156952de53aafbc0961ffbc0e502fa1e6/assets/js/googlesitekit/modules/datastore/modules.js#L172-L181).
    * `registerModule`
      * Add a title and single-line description of this function to register a module in the store.
      * Add `@since`, `@param` and `@return` descriptions for each based on the [docblock of the internal function](https://github.com/google/site-kit-wp/blob/c279f1b156952de53aafbc0961ffbc0e502fa1e6/assets/js/googlesitekit/modules/datastore/modules.js#L218-L236).

### Test Coverage

* No additional test coverage allowed

### Visual Regression Changes

* There should be no visual regression changes

## QA Brief

* Read the comment block for the functions `activateModule`, `deactivateModule` and `registerModule` in `assets/js/googlesitekit/modules/index.js`  - They should accurately describe each of the functions role in the application.

## Changelog entry

* N/A

**Comment by saideepesh000** [comment]
@felixarntz, Hi, how can I know what these functions do inorder to document them.

**Comment by saideepesh000** [comment]
@felixarntz @aaemnnosttv @tofumatt, I wanted to set up this project into the wordpress plugins for contributing, but when I click activate, it's thrown this error on wordpress. 

`Warning: include(C:\Bitnami\wordpress-5.5.1-2\apps\wordpress\htdocs\wp-content\plugins\site-kit-wp/includes/vendor/composer/autoload_classmap.php): failed to open stream: No such file or directory in C:\Bitnami\wordpress-5.5.1-2\apps\wordpress\htdocs\wp-content\plugins\site-kit-wp\includes\loader.php on line 26`

**Comment by benbowler** [comment]
## ✅ IB Written

**Comment by felixarntz** [comment]
@benbowler IB ✅  Can you add an estimate for this issue?

**Comment by asvinb** [comment]
Comment blocks present and accurate

QA: ✅
