### ISSUE TITLE
Refactor codebase to rely on Grid, Row, and Cell components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2273]
We have `Grid`, `Row` and `Cell` React components (introduced by the PR for #2039) to render containers to create a Material UI layout grid. Most of the Site Kit codebase however doesn't use them but instead hard-codes those classes which is error-prone and furthermore results in more code.

The codebase should be refactored to always rely on those dedicated components. This would furthermore make it a simple task to in the future make changes to the grid system etc. because it would all happen in only one place.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All components should use grid components for layout rather than implementing with CSS classes
* Use of the following classes should be replaced with the respective grid component:
    * `mdc-layout-grid` – `<Grid />`
    * `mdc-layout-grid__inner` – `<Row />`
    * `mdc-layout-grid__cell` – `<Cell />` – this will take the most work due to responsive grid classes that need to be converted to props as well
        * [See here for a reference](https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/assets/js/material-components/layout/Cell.js#L48-L66) to how the cell align/span/start classes map to props

## Implementation Brief

* Look for the `mdc-layout-grid-*` string across all files and replace as per below the components defined in the AC.
* Extra class names if present can be added via the `className` prop of the components.
* See here for a how to find them all
![image](https://user-images.githubusercontent.com/1621608/132493143-6b905bbc-fff2-4ca7-b161-6b2c8b79a751.png)

### Test Coverage
* No new tests to be added.

### Visual Regression Changes

* Should explicitly not affect VRTs.

### `QA:Eng`

* Secondary round of CR + QA to ensure no visual or behavioural change has been effected by this update. While all areas should be carefully examined, particular attention should be paid to areas where there is some logic and notably the [`DashboardSummaryWidget`](https://github.com/google/site-kit-wp/pull/4608/files#diff-5cc841e545f161a83da5721c030f752769179ee5ffec24803b63cbae17e947c0) which necessitated a minor change to the document structure (effectively, adding a new `div` due to replacing the grid class from the `Widget` classname with a `Grid` element).

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz I think this one is ready to start moving forward. Once the legacy components are removed we'll probably have less to do here as well so I've added these as dependencies here. Onward to ACs!

**Comment by aaemnnosttv** [comment]
@felixarntz now that all the legacy components are mostly removed, it looks like we only have ~30 files to update (including a few stories). I'll add some provisional ACs to get this going and leave it with you to review 👍

**Comment by felixarntz** [comment]
@aaemnnosttv LGTM!

**Comment by kuasha420** [comment]
QA: :heavy_check_mark: 

* Went through the code to make sure everything is right.
* Tested most of the UI elements where changes were made and couldn't find any visual or behavioral difference. 
* The special cases also looks and behaves correctly. 

Sending this to `Approval`. If I missed anything, I'm sure it will be caught in the smoke testing. On that note, @aaemnnosttv, when you prepare the next release, would you kindly mention keeping our eyes open during smoke testing about this ticket, please?
