### ISSUE TITLE
Detect changes in the admin URL to refresh URLs registered on the authentication service

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2277]
## Bug Description

#1857 resolved a long-standing issue where sites that would change their URL would run into problems with Site Kit. Now, whenever the site's home URL changes, Site Kit will detect that and disconnect the user. The **user** will then be prompted to reconnect, and Site Kit will automatically update the URLs registered on the authentication service. (Note that this only works if the **site** is already/still connected at that point.)

A secondary problem is that the admin URL may also change occasionally, e.g. when a site migrates to a setup where WordPress lives in a subdirectory of the site's home URL (e.g. [Bedrock](https://roots.io/bedrock/)). We should also implement detecting changes to the admin URL and make Site Kit behave the same way.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Context` class should receive a new method `get_canonical_admin_url( $path = '' )`:
    * Based on whether network mode is active or not, the method should call `network_admin_url()` or `admin_url()`. These functions should be called parameter-less though (i.e. don't pass the `$path`).
    * It should then run the value through a new `googlesitekit_canonical_admin_url` filter.
    * _Then_ the path should be appended.
* All calls throughout the plugin to the `admin_url` WordPress function should instead use `Context::get_canonical_admin_url`.
* When Site Kit is connected (`googlesitekit_authorize_user`), the current canonical admin URL should be stored in an option like it is already the case for the canonical home URL.
* On `admin_init` if the admin URL is changed, a flag should be set so that on `shutdown` a request to the proxy is made to update the URLs _if_ the site is using the proxy and _if_ it is connected. (This is already existing logic, right now it happens when e.g. updating the `blogname` option).
    * Because here this trigger for the request is not _action_-based but happens on pageload, there should be extra protection in place to ensure that this logic cannot result in tons of update URL requests being sent. Plugins to weird things to WordPress URLs, so if let's say for whatever reason the admin URL changes on every pageload, it should be ensured that an API request to update the URLs will not be sent more often than once per hour.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by Rescovedo** [comment]
I would like to add a comment that it doesn't only relates to migration but also this bug affects all Wordpress users with websites that support multiple languages like mine. Every time I use WPML to change between languages, Sitekit disconnects.

**Comment by ernee** [comment]
@Rescovedo thanks for reaching out! You may be experiencing [this issue](https://github.com/google/site-kit-wp/issues/2118) for which we've been working with the WPML team to resolve. Please feel free to follow it for updates on when the fix is out.

**Comment by felixarntz** [comment]
This is no longer relevant now that we automatically check any outdated URLs on setup (see #2383).
