### ISSUE TITLE
Implement Congrats dashboard notification for submitting user input settings

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2283]
A new Site Kit dashboard notification should be implemented for when a user has successfully submitted their user input flow data.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new notification should be implemented using the `Notification` component:
    * Its layout should look similar to the screenshot below.
    * It should use the image from the screenshot below as SVG (SVG is also pasted below).
    * The copy for the heading should be: _Congrats! You set your site goals._
    * The copy for the content should be: _Now Site Kit will begin showing you suggestions how to add more metrics to your dashboard that are relevant specifically to you, based on the goals you shared._
* The notification should be displayed in the Site Kit dashboard when a certain query parameter indicating that the user input flow was completed is present - i.e. when the user is redirected to the Site Kit dashboard after completing the user input flow screen (see #2039), that query parameter should be included.
* The notice should be hooked in in a similar way like the authentication success notification is currently displayed. In other words, this should use filters etc. Refactoring is a non-goal for this issue.

### Screenshot of similar-looking notification (different content)
<img width="640" alt="Screenshot 2020-10-29 at 09 35 39" src="https://user-images.githubusercontent.com/3531426/97604410-b2df5100-19ca-11eb-94e4-0f7a82e1804e.png">

### SVG of icon above
```
<svg width="79" height="89" viewBox="0 0 79 89" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="39.5" cy="49.3164" r="39.5" fill="#FEF7E0"/>
<path d="M59.7215 56.9186L65.8528 63.3447L67.0319 64.4649L54.7693 77.8477L46.1028 66.3514C44.9434 66.2335 44.4049 66.2571 42.5655 66.1156C40.2663 65.9387 37.4364 65.4082 34.7245 62.991C32.0125 60.5738 25.2722 52.2218 20.9881 46.3066C17.5097 42.8872 10.093 33.8553 12.4984 32.8649C14.9037 31.8744 24.9969 44.0073 25.9992 42.5924C27.0014 41.1775 19.8679 28.4432 19.8679 28.4432C17.7848 24.6307 14.5854 19.1283 18.217 18.8925C21.8486 18.6567 28.5343 35.3999 31.4821 34.0439C32.4254 32.8649 26.7775 14.3175 26.353 9.69539C25.9285 5.07331 29.4774 4.27158 30.3028 6.39397C31.1282 8.51636 35.6089 30.4476 38.0849 30.6835C40.561 30.9193 36.7291 12.4073 37.6724 7.2193C38.4143 3.13897 41.0916 4.97897 41.7991 7.21931C42.5066 9.45964 42.9628 21.8013 43.5088 23.9626C44.9237 29.5633 45.1595 30.1529 48.9916 36.7559C52.0573 42.0383 53.5312 40.2539 53.8849 38.7014C53.5312 36.0484 53.036 29.7874 53.8849 25.9671C54.7339 22.1468 57.6188 21.6634 58.9551 21.8992C58.7782 23.2552 59.7215 31.9805 60.7827 42.7693C61.6316 51.4004 60.429 55.7984 59.7215 56.9186Z" fill="#F3B091"/>
<path d="M32.6026 63.2877L23.5234 71.4236L18.4533 75.6094L8.43091 61.7549C12.8329 60.0845 21.5661 55.8712 21.2832 52.381C21.0002 48.8909 9.3742 33.5153 7.90032 31.7467C6.42643 29.978 8.19509 27.1482 10.5533 29.7422C12.9115 32.3362 19.88 40.1655 20.6346 37.7601C21.3893 35.3547 14.916 21.0757 12.7346 16.4183C10.5533 11.7609 13.6779 9.69746 16.0361 13.9422C18.3943 18.1869 23.7475 28.6574 24.6436 29.978C25.7637 31.6288 26.6481 33.987 27.1197 32.3362C27.497 31.0156 21.6369 8.45936 20.6346 4.15563C19.6324 -0.1481 23.1697 -0.796581 24.6436 2.74071C26.1175 6.27799 31.3055 23.2571 31.3055 23.2571C31.9147 24.9079 33.3454 28.1268 34.1943 27.7967C35.0433 27.4665 32.8973 7.39817 32.6026 4.15563C32.3078 0.913095 36.2578 1.03101 36.9652 4.15563C37.6727 7.28026 39.5121 20.5806 40.0309 25.2026C40.6794 30.9803 42.8608 35.343 44.6884 35.8736C46.1505 36.2981 51.2065 26.2639 53.4138 24.1415C55.621 22.0191 57.3048 24.3183 56.1846 26.7355C55.0645 29.1526 51.9045 35.06 49.8764 40.7668C47.3414 47.9004 50.6429 48.5489 46.457 56.7437C43.1084 63.2995 35.8254 63.838 32.6026 63.2877Z" fill="#B03F3C"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M73.7644 68.9795C69.9257 75.6536 64.1931 81.1002 57.3003 84.5857L52.8125 76.8798L67.0102 62.6953L73.7644 68.9795Z" fill="#90A4AE"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M62.5787 81.3735C60.912 82.5754 59.1478 83.6506 57.3003 84.5848L52.8125 76.8789L56.3021 73.3672L62.5787 81.3735Z" fill="#78909C"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M2.79581 63.9394L11.5028 58.1266L23.2478 74.4001L17.1121 81.8637C10.7303 77.4652 5.70603 71.2383 2.79581 63.9394Z" fill="#EDED33"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M12.2249 77.8868L20.3659 70.3752L23.2486 74.4001L17.1129 81.8636C15.3782 80.668 13.7438 79.3374 12.2249 77.8868Z" fill="#F9AB00"/>
</svg>
```

## Implementation Brief
- Using `assets/js/components/user-input/UserInputPreview.js`, update the [following line](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/user-input/UserInputPreview.js#L60) to include the following parameter to the URL: `notification=user_input_success`
  - `global.location.assign( `${ dashboardURL }&notification=user_input_success` );`
- Using `assets/js/components/notifications/index.js`, update the line where there are the [authentication checks](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/index.js#L54) to check for the following notification slug: `user_input_success`
- Create the following file: `assets/js/components/notifications/UserInputSuccessNotification.js` which will contain the notification.
- Using `assets/js/components/notifications/UserInputSuccessNotification.js`,
  - import the congrats image (`userInputSuccessImage`) and the `Notification` component
  - create the `UserInputSuccessNotification` functional component which should render the following:
```
<Notification
    id="user-input-success"
    title={ __( 'Congrats! You set your site goals.', 'google-site-kit' ) }
    description={ __( 'Based on your goals, now Site Kit will begin showing you suggestions how to add more metrics to your dashboard that are relevant specifically to you', 'google-site-kit' ) }
    smallImage={ global._googlesitekitLegacyData.admin.assetsRoot + userInputSuccessImage }
    dismiss={ __( 'OK, Got it!', 'google-site-kit' ) }
    format="small"
/>
```
- Using `assets/js/components/notifications/dashboard-setup-alerts.js`, 
  - add a case for the `user_input_success` notification slug which should render the `UserInputSuccessNotification` component.
- Using `stories/notifications.stories.js`, add a new story for the `UserInputSuccessNotification` notification

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Go to `/wp-admin/admin.php?page=googlesitekit-user-input`
* Fill out the form, and submit it.
* Once you are redirected to dashboard, you should see the congrats notification (similar to the screenshot).

## Changelog entry

* Implement success notification displayed after completing the user input flow.

**Comment by asvinb** [comment]
@felixarntz Looking at the latest designs, looks like this is the correct icon, which is slightly different from what you posted
![image](https://user-images.githubusercontent.com/31818/98536430-40f7e900-22a1-11eb-9090-52ac0580e05b.png)
The layout is also slightly different, with the "OK Got it!" CTA below the titles instead of being next to them

**Comment by felixarntz** [comment]
@asvinb The design in the Figma file for the notification is no longer the exact way it should be implemented, per a conversation that I had with @marrrmarrr. The way it is described in the ACs is how it should be, using the SVG icon that is in there and using a similar layout to how our existing notifications look. So for this issue you can basically ignore the Figma file.

Regarding the IB: I think it'd be worth implementing the new notification as its own reusable component, and only coupling it to the existing `DashboardSetupAlerts` component where needed. We could introduce e.g. a `UserInputSuccessNotification` component, and then in `DashboardSetupAlerts` render that in case of `notification=user_input_success`. This way the component is also usable on its own and more decoupled.

**Comment by asvinb** [comment]
Thanks for letting me know @felixarntz . We'll keep the layout as we currently have and use the icon you attached.
About the new component, I thought of that initially, i.e having it in its own file, but then I checked DashboardSetupAlerts and saw how all the Notifications live in there. Anyway, the IB has been updated 😃

**Comment by felixarntz** [comment]
IB ✅ 

@asvinb Looking at existing code is always a good idea - although in some cases we have a bunch of legacy code that could have been structured in a better way, so I think in those cases it makes sense to diverge and e.g. make "modern" components standalone, so that they're coupled to the legacy code as little as possible.

**Comment by cole10up** [comment]
### QA ⚠️

Activated latest development build and completed the user input settings.

Confirmed:
![image](https://user-images.githubusercontent.com/57115907/100827514-c2124e00-3411-11eb-85cc-4a2c3da1e287.png)

Notice the icon doesn't match the figma design:
![image](https://user-images.githubusercontent.com/57115907/100827574-e5d59400-3411-11eb-95c8-6745cf12b084.png)

Confirmed Firefox, Edge, Chrome, Safari and mobile

![image](https://user-images.githubusercontent.com/57115907/100827721-4238b380-3412-11eb-96e6-1cd65c832e1c.png)

Confirmed the 'OK, got it!' link functions.

@felixarntz, the screenshot on this ticket both in my comment and in the AC has an icon that doesn't match. Just confirming that this is expected.

**Comment by kostyalmm** [comment]
@cole10up please see [this comment](https://github.com/google/site-kit-wp/issues/2283#issuecomment-724200249) from @felixarntz. The Figma doesn't seem to be accurate.

**Comment by felixarntz** [comment]
@cole10up @kostyalmm That is correct, the Figma file is outdated. The notification should look like the screenshot in the issue description (only with different copy per the ACs).

**Comment by cole10up** [comment]
Thanks guys! Sending over to approved.

**Comment by marrrmarrr** [comment]
tested user input flow with dev build.
