### ISSUE TITLE
Remove publisher wins

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2285]
Publisher wins have become more of a maintenance burden than they are useful in their current state. In hindsight of the upcoming notification center epic which will introduce more helpful notifications about insights and milestones, the current feature should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The publisher wins notifications feature should be entirely removed, including any existing test coverage etc.
* Utility functions that are only used by the feature should be removed as well, if any.

## Implementation Brief

* Remove `assets/js/components/publisher-wins/`
* Remove `assets/sass/components/global/_googlesitekit-publisher-wins.scss`
* Remove `tests/backstop/reference/google-site-kit_Global_Notifications_Publishing_Win_*.png`
* Remove publisher wins (side-effect) imports:
  * https://github.com/google/site-kit-wp/blob/5c7a4027735674afa9cea46e1c02135078f8c8fa/assets/js/components/dashboard/DashboardApp.js#L28
* https://github.com/google/site-kit-wp/blob/5c7a4027735674afa9cea46e1c02135078f8c8fa/assets/js/components/dashboard-splash/DashboardSplashApp.js#L22
* Remove publisher win counts from PHP (see: https://github.com/google/site-kit-wp/pull/2417/files#diff-d389fa4d82a8e94394cf7fa68f451fbb13d0ffa40164129ad2338a0659a8a1d3R67-L186).
  * Remove https://github.com/google/site-kit-wp/blob/develop/includes/Core/Util/Activation_Flag.php#L76-L86
  * Remove https://github.com/google/site-kit-wp/blob/develop/includes/Core/Util/Activation_Flag.php#L144-L186
* Remove any other publisher wins code not including CSS classes (see below)
* The list is quite long, so essentially: clean up and merge #2417 🙂 

Of note: I didn't include removing `assets/sass/components/global/_googlesitekit-publisher-wins.scss` or renaming the `googlesitekit-publisher-win` CSS classes found, for instance, in the [`Notification`](https://github.com/google/site-kit-wp/blob/310b83f68bb2c9ad8df6eb16a071f2d8c3ebd7ad/assets/js/components/notifications/notification.js#L43) component. It seems like those styles are used by other components and that refactor could be done separately.

### Test Coverage

* Remove tests that are no longer needed for publisher wins.

### Visual Regression Changes

* Remove publisher wins VRT tests.

## QA Brief

* The publisher wins notifications (notifications related to new posts, eg a notification congratulating the user on their first post after installing Site Kit) should no longer appear.

## Changelog entry

* Remove legacy publisher win notifications.

**Comment by felixarntz** [comment]
@tofumatt IB, mostly LGTM - agreed, let's not refactor anything, just remove publisher wins things.

One follow-up question: What needs to be removed on the PHP side? 🤔

**Comment by tofumatt** [comment]
Ah, sorry, it's in the draft PR attached, but I added the PHP code to remove in the IB now, I meant to add it and seemingly forgot! 😅 

It's largely `private` code that isn't used anywhere else anymore and doesn't cause any test failures, so seems safe to remove as it's just about setting the post count of a site when Site Kit is activated, and since that's only used for publisher wins seems good to remove as well.

**Comment by felixarntz** [comment]
@tofumatt Ah good point - I had forgotten this PHP logic exists. Makes me even more happy now 😆 

IB ✅

**Comment by asvinb** [comment]
- Resetted and connected Site Kit again
- Published a post
- No publisher wins notifications displayed.

QA: ✅
