### ISSUE TITLE
Pass specific dates in Search Console deep links

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2286]
After #2237, all dynamic JS Search Console deep links in the new widgets (any JS links pointing to `performance/search-analytics...`) should be updated to pass the correct dates in the URLs.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All widgets (using the Widget API) that include Search Console deep links should be updated to pass the exact dates from the currently selected date range in the URL:
    * The `num_of_days` query parameter should no longer be used.
    * Instead, it should be query parameters `start_date` and `end_date`, both in the format `YYYYMMDD` (e.g. `start_date=20201001&end_date=20201028`).

## Implementation Brief
* Create new file `/assets/js/modules/search-console/util/report-date-range-args` and using newly created file,
	* Create a new function `generateDateRangeArgs` which accepts the returned object from the getDateRangeDates selector. The object contains the following keys:
		* `startDate`
		* `endDate`
		* `compareStartDate`: if compare is true when calling `getDateRangeDates`.
		* `compareEndDate`: if compare is true when calling `getDateRangeDates`.
	* The `generateDateRangeArgs` should return an object with the following keys:
		* `'start_date': startDate.replace( /-/g, '' ),`
		* `'end_date': endDate.replace( /-/g, '' ),`
	* `start_date` and `end_date` must be in the format: `YYYMMDD`
* Using the files listed below:
	- Import the `generateDateRangeArgs` function from `/assets/js/modules/search-console/util/report-date-range-args` and call the function by passing in the result of the `getDateRangeDates` selector of the user store (if not already present in the component).For e.g
		```js
		const { startDate, endDate } = select( CORE_USER ).getDateRangeDates( { offsetDays: DATE_RANGE_OFFSET } );
		```
	- Replace occurrences of `num_of_days` parameter by spreading the returned object of the `generateDateRangeArgs` function.
* List of files:
	- `assets/js/modules/search-console/components/dashboard-details/DashboardDetailsWidgetKeywordsTable.js`
	- `assets/js/modules/search-console/components/dashboard/LegacySearchConsoleDashboardWidgetKeywordTable.js`
	- `assets/js/modules/search-console/components/dashboard/LegacyDashboardWidgetPopularKeywordsTable.js`
	- `assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js`
	- `assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js`
	- `assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js`
	- `assets/js/modules/search-console/components/dashboard/LegacySearchConsoleDashboardWidgetTopLevel.js`
	- `assets/js/modules/search-console/components/dashboard/GoogleSitekitSearchConsoleDashboardWidget.js`

### Test Coverage
* Add new tests for the `generateDateRangeArgs` function.

### Visual Regression Changes
* There should be no visual changes.

## QA Brief
* Visit the "Dashboard" and "Search Console" pages.
* Inspect any URLs which point to `performance/search-analytics...`
	* The `num_of_days` parameter should not be present
	* The `start_date` and `end_date` parameters should be present in the following format: `YYYYMMDD`

## Changelog entry

* Include current dates in Search Console deep links so that the service frontend shows the same time period as Site Kit.

**Comment by aaemnnosttv** [comment]
@asvinb IB looks good, just a few points to address

* Let's introduce a utility for mapping the date range dates to args/params like we did in #2287  
Even though SC doesn't have a dedicated selector for its service report URL (yet) we can use a utility to abstract the details as to how dates translate to URL parameters rather than requiring that to be known in every place it's used.

It's also worth noting that while the report selector may use `compareStartDate` for the `options.startDate` where a previous period's data is used for comparison, the service dashboard `search.google.com` does not show data in this way (no relative performance metrics over time!) and so values for `start_date` and `end_date` parameters should always come from the same dates returned by `getDateRangeDates` regardless of whether `compare*` dates are present or not.

**Comment by asvinb** [comment]
@aaemnnosttv IB updated.

**Comment by aaemnnosttv** [comment]
@asvinb – very close just a few details to clarify:

> If `compareStartDate` and `compareEndDate` keys are present, then only `compareStartDate` should be used as `start_date` and `compareEndDate` should be ignored, using `endDate` instead. Search console does not show data in this way (no relative performance metrics over time).

This is only relevant for args to the `getReport` selector, not the args handled by the utility. The utility would always return `{ start_date: startDate, end_date: endDate }` where `(start|end)Date` is the formatted version of the key from `getDateRangeDates`, just like you described: "The `generateDateRangeArgs` should return an object with the following keys" ... "`start_date` and `end_date` must be in the format: `YYYMMDD`."

All that to say, I think what you have is good, but this bullet point is unnecessary I think and makes more sense to remove. Args passed to `getReport` should remain unchanged, while providing the full object returned by the `getDateRangeDates` selector to the utility function.

> Add new tests for the `getDateRangeDates` function.

This is not the name of the new utility referenced above 😄

**Comment by asvinb** [comment]
@aaemnnosttv I removed the bullet point you mentioned above, however I think this part needs some clarification:
**Args passed to getReport should remain unchanged, while providing the full object returned by the getDateRangeDates selector to the utility function.**
Actually we should pass the same arguments passed to `getReport` to the utility function. For e.g here, https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js#L56-L61, so that we get the same dates and not just spread the full object returned by the `getDateRangeDates` selector.

**Comment by aaemnnosttv** [comment]
@asvinb I think maybe we're misunderstanding each other 😄 

Here's what I mean:

```js
const dateRangeDates = select( CORE_USER ).getDateRangeDates( { offsetDays: DATE_RANGE_OFFSET } );
const dateRangeArgs = generateDateRangeArgs( dateRangeDates );
const { startDate, endDate } = dateRangeDates;
const report = select( STORE_NAME ).getReport( { startDate, endDate } );
```

Or for uses with comparison

```js
const dateRangeDates = select( CORE_USER ).getDateRangeDates( { offsetDays: DATE_RANGE_OFFSET, compare: true } );
const dateRangeArgs = generateDateRangeArgs( dateRangeDates );
const { compareStartDate, endDate } = dateRangeDates;
const report = select( STORE_NAME ).getReport( { startDate: compareStartDate, endDate } );
```

In the end when constructing the URL for the service, it would always do something like this:

```js
const path = '/performance/search-analytics';
const query = {
	// url,
	// page,
	// resource_id,
	...dateRangeArgs, // Replaces num_of_days
};
const url = select( STORE_NAME ).getServiceURL( { path, query } );
```

Does that make more sense? If not, let's jump on a quick call but I think this is good to go now.

**Comment by asvinb** [comment]
Ah makes sense @aaemnnosttv . Moving IB again for final review :)

**Comment by aaemnnosttv** [comment]
IB ✅  

Bumping the estimate one up given that this is a GFI and will take a bit longer accordingly.

**Comment by tofumatt** [comment]
Moving back to Execution and marking as blocked by #2674; I can't get the E2E tests passing to review this.

Once #2674 is merged and this issue's PR/branch merges in the latest `develop`, this should be unblocked.

**Comment by felixarntz** [comment]
@tofumatt See my response in #2287: Is every e2e test failing? I've seen these failures too but usually it works after 2-3 attempts. It's definitely worth fixing this, but we shouldn't block production-affecting issues because of that unless they _really_ consistently make e2e tests fail.

**Comment by tofumatt** [comment]
I had restarted the tests over a dozen times in each PR, so even if they were intermittent failures they were happening most of the time. That said, @johnPhillips mentioned that he merged the latest E2E fixes into these branches and they look to be passing now. Yay! 🎉

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- On the `Search Console ` page fo URLs that start with `performance/search-analytics` the URL does not include `num_of_days` parameter. 
- On the `Search Console ` page fo URLs that start with `performance/search-analytics` the URL includes the `start_date` and `end_date `parameters in YYMMDD format. 
- The `start_date` was changed depending on the date period (i.e. 7, 14, 28 and 90 days)

- On the `Dashboard` page fo URLs that start with `performance/search-analytics` the URL does not include `num_of_days` parameter. 
- On the `Search Console ` page fo URLs that start with `performance/search-analytics` the URL includes the `start_date` and `end_date `parameters in YYMMDD format. 
- The `start_date` was changed depending on the date period (i.e. 7, 14, 28 and 90 days)

`/performance/search-analytics?resource_id=https%3A%2F%2Fdomain.com%2F&start_date=20210107&end_date=20210203&authuser=hello%40domain.com&query=%21search%20term`
