### ISSUE TITLE
Remove unused legacy splash screen content

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2290]
The `LegacyDashboardSplashApp` component (see #2259) contains a bunch of UI and logic that has been unused for a very long time. The screen's purpose is to guide the user through the initial setup or subsequent connection flow for the plugin.

Right now it also has logic to conditionally render a module setup flow (never used for this purpose) as well as render the legacy `DashboardSplashMain` component which in the very early days of the plugin (before 1.0.0-rc) acted as some intro page with an overview of the plugin.

Basically, the only thing that's still relevant here is the legacy setup flow when not using the proxy, i.e. the `SetupUsingGCP` component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `LegacyDashboardSplashApp` component should be removed.
* Usage of the `LegacyDashboardSplashApp` component should be replaced with `SetupUsingGCP` directly.
* All components that were only used as part of `LegacyDashboardSplashApp` should also be removed, e.g. `DashboardSplashMain`, `DashboardSplashNotifications`, and most other `DashboardSplash*` components.
* Any CSS that was only used for those legacy components should be removed.
* Any further assets that were only used in those legacy components, such as certain images, should be removed too.
* Storybook coverage and VRT coverage that may exist for the removed components should be removed too.

## Implementation Brief

* Remove the usage of `LegacyDashboardSplashApp` from `DashboardSplashApp`, remove the `else if` statement
* Remove `LegacyDashboardSplashApp`
* Remove `DashboardSplashMain`
* Remove `LegacyDashboardSplashNotifications`
* Remove `LegacyDashboardSplashIntro`
* Remove `LegacyDashboardSplashModule`
* Remove `LegacyDashboardSplashService`
* Remove `LegacyDashboardSplashOutro`
* Remove
   ```scss
	@import "components/dashboard/splash/googlesitekit-splash";  
	@import "components/dashboard/splash/googlesitekit-splash-intro";  
	@import "components/dashboard/splash/googlesitekit-splash-module";  
	@import "components/dashboard/splash/googlesitekit-splash-outro";  
	@import "components/dashboard/splash/googlesitekit-splash-service";
   ```
   from `admin.scss`. Also remove these files individually as well.
 * Remove `assets/images/service-analytics.jpg` 
 * Remove `assets/images/service-search_console.jpg`
 * Remove `stories/splash.stories.js` as well.
 * Remove the story from `storybook-data.js`, run the `visualtest` and `visualapprove` the removed references.

### Test Coverage

* No new tests to be added

### Visual Regression Changes

* The VRT for `Splash` must be removed after these changes

## QA Brief

* Make sure the Splash story is removed from storybook
* VRT for the same must be removed as well

## Changelog entry

* Remove legacy splash screen and the associated components.

**Comment by felixarntz** [comment]
@kostyalmm The IB doesn't contain the part about updating `DashboardSplashApp` to use `SetupUsingGCP`. Maybe you omitted that because it's already clear from the ACs, so that's okay - just wanted to highlight. ✅

**Comment by benbowler** [comment]
Moved back to Execution because it's failing E2E tests.

**Comment by benbowler** [comment]
E2E tests are now passing.

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅ 
Assigning to you since Travis is out of order.

**Comment by asvinb** [comment]
No Splash screen in Storybook and VRT all passing
QA ✅
