### ISSUE TITLE
Remove legacy `googlesitekit.moduleHasSetupWizard` filter

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2291]
There is a legacy filter `googlesitekit.moduleHasSetupWizard` available which is unused and doesn't have a valid purpose anyway after #2074. It should be removed. Furthermore, the `GoogleSitekitModule` component should be refactored to a functional component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GoogleSitekitModule` component should be refactored to a functional component using hooks and the datastore.
    * The constructor is irrelevant since the same value can just be looked up from the global in the render function.
* The `googlesitekit.moduleHasSetupWizard` should be removed. The component should no longer check for that value and display the `Setup` component solely based on `showModuleSetupWizard`.

## Implementation Brief

* Refactor `GoogleSitekitModule` component to be a functional component:
	* Since using state for `showModuleSetupWizard` is not required:
	   ```js
	   const showModuleSetupWizard = global._googlesitekitLegacyData.setup.showModuleSetupWizard;
	   ```
	 * Move the `render` function body out to the functional component body.
	 * Keep `moduleToSetup` as it is.
	 * Remove `moduleHasSetupWizard` (use of `applyFilter`) as it is no longer required.

### Test Coverage

* No additional tests required

### Visual Regression Changes

* No visual changes should occur

## QA Brief

* All the module pages like `adsense`, `analytics` etc should function as they did before.
* If a module is not setup, then the module setup component must be rendered as it already does.

## Changelog entry

* Remove legacy `googlesitekit.moduleHasSetupWizard` JS filter.

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: The `GoogleSitekitModule` component is refactored and the `googlesitekit.moduleHasSetupWizard` filter is removed.
