### ISSUE TITLE
Modify error message shown to AMP users when connecting GTM after Analytics

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2292]
## Bug Description

If an AMP user has the Analytics module setup successfully and then they decide to connect Tag Manager to an account (which already has the correct Universal GA Tag setup) the following notice appears in the case where there is no tags in the related AMP container:

![image](https://user-images.githubusercontent.com/41326532/97644815-363c8900-1a43-11eb-900d-f8f4f8beed6a.png)

The above isn't completely accurate as it can occur if a user **_does_** have a matching property in their web container. The problem is they don't have any Tags setup in their AMP container. 

A more suitable notice to display may be the following:
_Error: Looks like you’re already using Google Analytics within your Google Tag Manager configurations. However, the configured Analytics tags reference different property IDs **or are incomplete**. You need to configure the same Analytics property in both containers._

## Steps to reproduce

1. Setup a new account in GTM and create a web and AMP container
2. Within the web container setup a GA Universal tracking tag & publish (All pages as the trigger)
3. Create an empty AMP container (No need to publish - the same notice appears if published)
4. Setup SK and connect the Analytics module on an AMP site (transitional or reader mode). Use the same property as used in your GTM Analytics Tag
5. Attempt to connect the Tag Manager module

## Additional Context

 - Occurs with transitional & reader mode AMP (official plugin)
 - Standard mode allows setup to proceed 
 - Doesn't occur if a GTM account has no AMP container, setup can proceed 
 - Plugin Version: 1.19.0
 - AMP Plugin: 2.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update the current error message to the following text:
_Error: Looks like you’re already using Google Analytics within your Google Tag Manager configurations. However, the configured Analytics tags reference different property IDs, or the setup process was not fully completed. You need to configure the same Analytics property in both containers._

## Implementation Brief

* Update the error message in `assets/js/modules/tagmanager/components/common/FormInstructions.js` (the top error message) to the copy above.

### Test Coverage

* No new tests required; existing tests should pass.

### Visual Regression Changes

* Images of the error message may need updating.

## QA Brief

* Follow the 'Steps to reproduce' instructions in the description above to display the message and check that it has been updated.
* You can check the error message in Storybook at https://google.github.io/site-kit-wp/storybook/develop/?path=/story/tag-manager-module-setup-secondary-amp--multiple-property-ids-analytics-active

## Changelog entry

* Update error message shown to AMP users when connecting Tag Manager after Analytics.

**Comment by wpdarren** [comment]
QA reproduced this message which appears when  you connect Tag Manager to an account that already has the correct Universal GA Tag setup.   https://d.pr/i/mySxPw

**Comment by nafekim** [comment]
I've encountered the same error for a wordpress site using Site Kit. 

Regarding the steps:

1. Does it matter if the GA Universal tag in the web container measures pageviews vs events? (note I'm looking to setup event tracking for some buttons).

2. What does "Setup SK" mean?

Would it be possilbe to see a loom video of the steps? 

Thanks in advance!

**Comment by jamesozzie** [comment]
@nafekim If you're stuck or having any issues while connecting any of the Site Kit modules feel free to open a WordPress [support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on the Site Kit forum and we'd be happy to assist from there. 

> Does it matter if the GA Universal tag in the web container measures pageviews vs events? (note I'm looking to setup event tracking for some buttons).

This depends on how you want to track your website, both work when it comes to Site Kit plugin integration via Tag Manager. The Analytics product experts would be able to assist with queries in relation to the difference between both measurements. 

> What does "Setup SK" mean?

This refers to setting up Site Kit, with SK an abbreviation in this case.

**Comment by marrrmarrr** [comment]
@jamesozzie when you suggested "However, the configured Analytics tags reference different property IDs or are incomplete", did you mean "the setup was not completed"? 
"Incomplete" could be interpreted as e.g. a character is missing from the tag or similar.

**Comment by jamesozzie** [comment]
@marrrmarrr Correct, that's what I was trying to portray, "_the setup was not completed_" would indeed be more suitable than "are incomplete" in this context.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Confirmed that the message has been changed on my local site and also the Storyboard. 

![image](https://user-images.githubusercontent.com/73545194/123265337-d96e7100-d4f2-11eb-8d54-14a3b5beb08e.png)
