### ISSUE TITLE
Update Composer dependencies to their latest versions

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2295]
We haven't updated Composer dependencies in a while, so let's do that again. Particularly the Google API libraries should be kept up to date.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All Composer dependencies, primarily the Google API libraries, should be up to date.

## Implementation Brief

* Add `google/apiclient-services` to our `composer.json` explicitly, since we actually require it directly. It's more than a dependency of `google/apiclient`.
* Run `composer update`.
* Test some basic behavior of the plugin and fix potential failures, e.g. if Google API classes are no longer loading.
* Merge #2296.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* This should mostly be covered implicitly by regular smoke testing.
* However, let's do some extra testing to QA this issue specifically. We should visit all of the following areas and make sure they don't result in a blank page or some other (fairly obvious) error:
    * The Site Kit dashboard
    * The Site Kit dashboard details view for a single URL
    * The Site Kit widget in the WordPress dashboard
    * The Site Kit admin bar menu in the frontend
    * All 4 module setup flows (AdSense, Analytics, Optimize, Tag Manager)

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
