### ISSUE TITLE
Introduce `ActivateModuleCTA` and `CompleteModuleActivationCTA` components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2299]
The `AnalyticsInactiveCTA`, `DashboardPagespeedCTA`, as well as the legacy `getSetupIncompleteComponent` components are fairly similar in behavior. Let's introduce generic components:
* `ActivateModuleCTA` which suggests to activate a specific module and has a button to activate it
* `CompleteModuleActivationCTA` which prompts to complete activation of a specific module and has a button to continue the module setup

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `ActivateModuleCTA` component should be introduced:
    * It should receive the module slug as required `slug` prop.
    * It should also support optional string props for `title` and `description`. The defaults should be the following:
        * Title: _Activate %s_ (where `%s` is the module name)
        * Description: value of the module's `description` field if not empty, or alternatively _%s module needs to be configured_ (where `%s` is the module name)
    * A CTA label _Set up %s_ (where `%s` is the module name) should be passed to the inner `Link` component.
    * The functionality and UI should be similar to the existing `AnalyticsInactiveCTA` component.
* A new `CompleteModuleActivationCTA` component should be introduced:
    * It should receive the module slug as required `slug` prop.
    * It should also support optional string props for `title` and `description`. The defaults should be the following:
        * Title: _Complete %s activation_ (where `%s` is the module name)
        * Description: _%s module setup needs to be completed_ (where `%s` is the module name)
    * A CTA label _Complete setup_ should be passed to the inner `Link` component.
    * A CTA aria-label _Complete %s setup_ (where `%s` is the module name) should be passed to the inner `Link` component.
    * The functionality and UI should be similar to the existing `AnalyticsInactiveCTA` component, except that the CTA button should not activate the module, but link to the module's "reauth URL" (to complete the setup flow).
* The `AnalyticsInactiveCTA` component should be simplified to simply rely on the new `ActivateModuleCTA` component with custom props where needed.
* The `DashboardPageSpeedCTA` component should be simplified to simply rely on either the `ActivateModuleCTA` or the `CompleteModuleActivationCTA` component based on whether the module is not connected or not active, only passing the `slug` prop to them.
* The `getSetupIncompleteComponent` function should be modified to use the `CompleteModuleActivationCTA` component, passing `module` as `slug` prop to it.

## Implementation Brief
- Using `assets/js/components`
	- Create new file `ActivateModuleCTA.js`
	- Create new file `CompleteModuleActivationCTA.js`
- Using `assets/js/components/ActivateModuleCTA.js`
	- Create a new functional component called `ActivateModuleCTA` with the following props:
		- `slug` (required)
		- `title` (default: _Activate %s_ (where `%s` is the module name))
		- `description` value of the module's `description` field if not empty, or alternatively _%s module needs to be configured_ (where `%s` is the module name)
	- `ActivateModuleCTA` should render the same markup and functionality as `AnalyticsInactiveCTA` component with the following changes:
		- `onSetupAnalytics` function should be renamed to `onCTAClick` which is more generic
		- Remove hardcoded `analytics` slug/string by the `slug` prop
		- Pass on `ctaLabel` and `ctaAriaLabel` prop to the `CTA` component (with content per the ACs) which we will update later
	- To get the module name, we can query the store like this:
		```js
		const module = useSelect( ( select ) => select( MODULES_STORE ).getModule( slug ) );
		```
- Using `assets/js/components/CompleteModuleActivationCTA.js`
	- Create a new functional component called `CompleteModuleActivationCTA` with the following props:
		- `slug` (required)
		- `title` (default: _Complete %s activation_ (where `%s` is the module name))
		- `description` (default: _%s module setup needs to be completed_ (where `%s` is the module name))
	- `CompleteModuleActivationCTA` should render the same markup and functionality as `AnalyticsInactiveCTA` with the following changes:
		- `onSetupAnalytics` function should be renamed to `onCTAClick` which is more generic
		- Pass on `ctaLabel` and `ctaAriaLabel` prop to the `CTA` component (with content per the ACs) which we will update later
		- `onCTAClick` should link to the module's "reauth URL" (to complete the setup flow). To get the reauth URL:
			```js
			import {
				getReAuthURL,
			} from '../util';
			...
			...
			const onCTAClick = useCallback( async () => {
				global.location = getReAuthURL( slug, true );
			} );
			```
- Using `assets/js/components/AnalyticsInactiveCTA.js`
	- Remove all existing logic and render the `ActivateModuleCTA` component with the existing values for the `title`, `description` and `ctaLabel`.
- Using `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeedCTA.js`
	- Import the `ActivateModuleCTA` and `CompleteModuleActivationCTA` components
	- Render the above components using the following logic:
		- If module is active && connected, `DashboardPageSpeedCTA` should just return null.
		- If module is not active it should return `ActivateModuleCTA`.
		- If module is not connected (i.e. otherwise) it should return `CompleteModuleActivationCTA`.
- Using `assets/js/components/notifications/setup-incomplete.js`
	- Update the cta variable to use the `CompleteModuleActivationCTA` component
		```js
		const cta = <CompleteModuleActivationCTA slug={ module } />;
		```
- Using `assets/js/components/notifications/cta.js`
	- Add new `aria-label` props which is proxied to the `Link` component
- Add new stories in `/stories` for the `ActivateModuleCTA` and `CompleteModuleActivationCTA` components

### Test Coverage

* Tests must be updated for any label changes

### Visual Regression Changes

* 

## QA Brief

* There should not be any visual changes.
* Specifically, the setup CTAs for Analytics and PageSpeed Insights on the dashboard should look the same like before.

## Changelog entry

* Introduce `ActivateModuleCTA` and `CompleteModuleActivationCTA` components to centrally manage UI for those scenarios.

**Comment by felixarntz** [comment]
@asvinb IB mostly looks good, just a few bits of feedback:
> Create new file `ActivateModule.js`

The file and component should be called `ActivateModuleCTA` (relevant throughout other mentions in the IB too).

> Create a new functional component called `ActivateModule` with the following props

The `description` prop implementation here is not complete (see ACs), it should first check if the module identified by `slug` has a `description` and if so, use that.

> Using `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeedCTA.js`

Here the logic for which of the two components to render needs some refinement:
* Either we implement the component assuming that it will only be rendered if the PSI module is not connected. If so, we'll only need to check for `active` and based on whether it's active render one or the other component.
* Or we make it more standalone so that it performs the full check. If so:
    * For `active && connected` it should just return `null`.
    * For `! active` it should return `ActivateModuleCTA`.
    * For `! connected` (i.e. otherwise) it should return `CompleteModuleActivationCTA`.

**Comment by asvinb** [comment]
Thanks for catching that @felixarntz . IB has been updated as per your comments. Can you check again?
Thanks!

**Comment by felixarntz** [comment]
@asvinb IB mostly looks good now, however one thing I missed before: The IB mentions introducing props for `aria-label` of the CTA, but that shouldn't be necessary. We should be able to use a single translation string which hides part of the text to non-screen-reader users (e.g. like `Complete<span class="screen-reader-text"> Analytics</span> setup`), using the `VisuallyHidden` component alongside `createInterpolateElement`.

Let's think about how we can address this requirement here. @aaemnnosttv What do you think about this? Should we give the `CTA` component specific support (like replace a `span` element inside the string with `VisuallyHidden` via `createInterpolateElement`) or should we alter the `CTA` component to also allow receiving `label` as a `WPElement`? Maybe we could even remove `label` as prop and rely on `children` instead, although that might go a bit too far.

**Comment by aaemnnosttv** [comment]
> We should be able to use a single translation string which hides part of the text to non-screen-reader users (e.g. like `Complete<span class="screen-reader-text"> Analytics</span> setup`), using the `VisuallyHidden` component alongside `createInterpolateElement`.

@felixarntz it looks like the `ctaLabel` prop isn't even needed, since the only usage of this right now is right here (which is actually wrong)
https://github.com/google/site-kit-wp/blob/0e0ae8c6e279c5ea9d80bb9ccbe1ed0fb206be01/assets/js/components/wp-dashboard/wp-dashboard-modules.js#L56
Note the only difference is the lowercase "a" in Analytics, where this would be correct if it were using the default prop.

That to me shows that adding support for a `ctaLabel` prop is a bit premature and adds complexity that we don't need now and may never need. So I would propose that we remove that prop and pass the alternate screen reader version as an `aria-label` on the `Link` used for the CTA instead.

In the future should we need more flexibility here, we'll have more context to inform the approach.

---

Regarding the IB, one thing to note is that we shouldn't use the legacy `getReAuthURL` util, but use `getAdminReauthURL` on the module's store instead.

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds good, let's get rid of the `ctaLabel` as a prop. This way we can handle both the link text and the link `aria-label` internally in the `*CTA` components.

@asvinb I've updated the ACs based on ^ and also updated the IB based on it, which was only a minor change (mostly removal of the `ctaLabel` and `ctaAriaLabel` props).

IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz @asvinb per my last comment – we should no longer be using the legacy `getReAuthURL` utility function which is still in the IB – instead we should use the `getAdminReauthURL` selector from `core/modules` 🙂

**Comment by aaemnnosttv** [comment]
Reopening this one after encountering an error when `module` is `undefined`.

**Comment by felixarntz** [comment]
Follow-up QA ✅ 

Complete Analytics activation CTAs now show up as expected without triggering a JS error:
![Screenshot 2020-12-21 at 11 29 17](https://user-images.githubusercontent.com/3531426/102814671-d9dd5200-437f-11eb-88ef-8e9c7404ea74.png)
