### ISSUE TITLE
Domain used for reporting is not consistent, resulting in duplicates

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#23]
**Describe the bug**
When sending reporting data, the plugin currently sends the "site url" sometimes with and sometimes without the trailing slash, resulting in duplicated tracking entries. 

**To Reproduce**
1. Set up the plugin on a new domain.
2. Check the domain sent for tracking events.

**Expected behavior**
The domain used for tracking should be consistent, never including a trailing slash.

**Screenshots**

**System Information (please complete the following information):**
 - PHP Version: 
 - Plugin Version [e.g. 22]

**Additional context**
- Please add any additional information about the bug.

**Comment by ThierryA** [comment]
@bjackson27 has this been QA'ed?
