### ISSUE TITLE
Couldn't create project

### ISSUE THREAD

**Issue by balusahu977** [google/site-kit-wp#230]
field [project_id] has issue [project_id contains invalid characters]

**Comment by jamesozzie** [comment]
@balusahu977 Thanks for reporting. At the screen where it displays that error message do you mind trying the following:
- In the address bar look at the full address (It should look something similar to https://developers.google.com/web/site-kit/?sitename=**yourwebsitecom**&siteurl=**http://yourwebsite.com**)
- Change your website address in both highlighted entries above, in the first entry (yourwebsitecom) enter your without using only standard alphabelticletters. In the second entry enter your full website address, including the http or https. 
- Press enter

At that stage a new window should pop up, allowing you to continue to retrieve your credentials. 

Can you let me know if that works for you?

**Comment by jamesozzie** [comment]
@bjackson27 I will close this ticket now but if you are encountering the same issue feel free to reopen.
