### ISSUE TITLE
Finalize copy for user input screen and notifications

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2302]
Currently the user input screen (#2039) is not fully finalized and partially still includes some placeholders. The final wording needs to be defined and implemented before this can launch.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy of the `googlesitekit-user-input` screen (implemented in JS via #2039) should be updated per the latest version of the [Figma file](https://www.figma.com/file/f07vatCPHzubuJoXkgd5RU/SiteKit---Phase-1_-Onboarding?node-id=1098%3A16956).
    * Please review the **Desktop** mocks of the User Input screen (copy has only been updated there, not on the other viewport mocks).
    * Changes have been made to the 5 questions, the description for each question, and the answers to choose from (including one newly added possible answer in one case).
    * Please enable comments on the Figma file, and review all comment bubbles on those screens. In some cases, they include requirements to copy changes (e.g. in case of copy changes to each question, where it wasn't possible to edit them).
    * Changes made to the questions should be in sync with the copy of these questions as displayed in the overview/preview.

## Implementation Brief

* Edit the `UserInputQuestionInfo` component in the `assets/js/components/user-input/UserInputQuestionInfo.js` file:
  * Add a new property `description`;
  * Replace the static copy in the paragraph below the title with the new `description` property. Make sure that the paragraph is not rendered if the description is empty;
* Edit the `UserInputQuestionWrapper` component in the `assets/js/components/user-input/UserInputQuestionWrapper.js` file:
  * Add a new `description` property, it should be proxied to the rendered `<UserInputQuestionInfo ... />` tag;
  * Add a new `nextLabel` property, it should be used as the next button label with the current `__( 'Next', '...' )` fallback if the `nextLabel` is empty.
* Edit the `UserInputQuestionnaire` component in the `assets/js/components/user-input/UserInputQuestionnaire.js` file:
  * Change the title for the last question to be: **_To help us identify opportunities for your site, enter the top three search terms that best describe your site's content._**
  * Add `description` props to the questions with the following messages:
    * 1st question: **_This will help Site Kit show tips that help you specifically in your role._**
    * 2nd question: **_Based on your answer, Site Kit will suggest new features for your dashboard related to content creation._**
    * 3rd question: **_Based on your answer, Site Kit will tailor the metrics you see on your dashboard to help you track how close you’re getting to your specific goals._**
    * 4th question: **_Based on your answers, Site Kit will tailor the metrics and advice you see on your dashboard to help you make progress in these areas._**
    * 5th question: **_Site Kit will keep you informed if people start finding you in Search for these terms._**
  * Add the `nextLabel` property with `__( 'Preview', '...' )` value to the 5th question.
* Edit answers in the `assets/js/components/user-input/util/constants.js` file:
  * `USER_INPUT_ANSWERS_POST_FREQUENCY`:
    * Change the label for the `daily` answer to be: **_Daily / multiple times a day_**
    * Change the label for the `weekly` answer to be: **_Weekly / multiple times a week_**
    * Change the label for the `monthly` answer to be: **_Monthly or less_**
  * `USER_INPUT_ANSWERS_GOALS`:
    * Add the new answer `generate_leads` (right after _Publish a blog_) with **_Generate leads_** label.

### Test Coverage

* N/a

### Visual Regression Changes

* The static copy on the user input screen should change accordingly to the IB

## QA Brief

* Go to the user input settings page (/wp-admin/admin.php?page=googlesitekit-user-input) and make sure you see static copy changes mentioned in the IB.

## Changelog entry

* Finalize copy for new `googlesitekit-user-input` screen.

**Comment by felixarntz** [comment]
@eugene-manuilov IB ✅ , just two nit-picks:
> Add a new property `subtitle`;

Maybe better call this `description` instead? Nit-pick, but it's not really a subtitle.

> Add the new answer `generate_leads` with **_Generate leads_** label.

Would be good to clarify that it should be added _right after_ **_Publish a blog_**.

**Comment by eugene-manuilov** [comment]
@felixarntz ok, updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
## QA ❌

Tested the content across multiple browsers and window sizes, compared to the Figma file above. As well as general functional testing.

See Detailed Test Results Below:

<details>
 <summary>Content Comparison</summary>

Note - Figma screenshots do not include the adjustments added from the team's comments - which I added under each screenshot with adjustments
 Figma Question 1:
![image](https://user-images.githubusercontent.com/57115907/98772576-e2636580-239b-11eb-8132-c969ccf8cb14.png)

Develop Question 1:
![image](https://user-images.githubusercontent.com/57115907/98772602-f6a76280-239b-11eb-8b5c-80e82523038c.png)

Figma Question 2:
![image](https://user-images.githubusercontent.com/57115907/98772633-0161f780-239c-11eb-8f36-562ccd278886.png)
Comment -  Change "post" to "posts" (plural)
Develop Question 2:
![image](https://user-images.githubusercontent.com/57115907/98772686-23f41080-239c-11eb-9807-cf20c5df5692.png)

Figma Question 3:
![image](https://user-images.githubusercontent.com/57115907/98772702-2f473c00-239c-11eb-9e58-68d05dc98dd6.png)
Comment - Add "Generate leads" answer

Develop Question 3:
![image](https://user-images.githubusercontent.com/57115907/98772764-59006300-239c-11eb-9926-99f87d9624bf.png)

**Notice - User is able to select 1 answer and move on by clicking next although copy states 'Choose only two (2) answers'**

Figma Question 4:
![image](https://user-images.githubusercontent.com/57115907/98772815-77665e80-239c-11eb-886c-f4816d801b22.png)

Develop Question 4:
![image](https://user-images.githubusercontent.com/57115907/98772850-8b11c500-239c-11eb-91ac-f2a3a41c1cb4.png)

**Notice - User is able to select 1 or 2 answers and move on by clicking next although copy states 'Choose only three (3) answers' also seeing this copy in Develop and not on the Figma design 'This question applies to the entire site and may have an effect for other users.'**

Figma Question 5:
![image](https://user-images.githubusercontent.com/57115907/98772975-c57b6200-239c-11eb-9cf2-5283c474bff6.png)
Comment - Change content to To help us identify opportunities for your site, enter the top three search terms that best describe your site's content." 

Develop Question 5:
![image](https://user-images.githubusercontent.com/57115907/98773003-d926c880-239c-11eb-8ae2-a07acd73987f.png)

**Notice - Instructional copy is missing from the form 'Minimum one (1), maximum three (3) keywords' from the Figma design, Also noticed this copy exists in develop that isn't in the Figma design 'This question applies to the entire site and may have an effect for other users.'**

Figma Summary:
![image](https://user-images.githubusercontent.com/57115907/98774217-69660d00-239f-11eb-9731-a3018a167e68.png)

Develop Summary:
![image](https://user-images.githubusercontent.com/57115907/98774242-7682fc00-239f-11eb-8373-b9d60474297b.png)

**Notice seeing long running answers over or underlap other answers as well as empty answers shown for 'Other' answers - looks to be a bug**

**Functionality I noticed for questions 3 and 4 - when they have a limit to the amount of items to select, the user can select items that aren't the 'Other' selection and still click into the form to write in the 'Other' item which then removes a prior selected item**
</details>

**Sending back to Execution for both content and functional adjustments**

**Comment by cole10up** [comment]
Speaking with @asvinb - 

Two adjustments are called out above specifically about the content

- Question 4 and 5 **in develop** are showing the following extra copy 'This question applies to the entire site and may have an effect for other users.' which isn't in the Figma design
- Question 5 is missing the instructional copy from the input form 'Minimum one (1), maximum three (3) keywords' from the Figma design

**Comment by asvinb** [comment]
@cole10up As per conversation I had with @eugene-manuilov , the copy 'This question applies to the entire site and may have an effect for other users.'  should only appear if the question `scope` is set to `site` and it should be correct.
As for the missing placeholder, I've issued another PR to fix that.

**Comment by cole10up** [comment]
@asvinb - One question as I tried 2 different sites. One with many users and another with one admin. Both are showing the copy 'This question applies to the entire site and may have an effect for other users.' on questions 3 and 4. What drives if the scope is set to 'site' or not?

Also, I checked the instructional copy on question 5. It seems the font color is too dark compared to the Figma design. Can we adjust and make it a lighter, more grayed out gray?

**Figma:**
![image](https://user-images.githubusercontent.com/57115907/98877784-23a85380-2436-11eb-858f-f441756ad695.png)

**Development:**
![image](https://user-images.githubusercontent.com/57115907/98877806-2efb7f00-2436-11eb-8531-111e31490428.png)

Also noticing above that there is some padding before the 'Separate with commas or the Enter key' in the Figma design versus development, however there is a comment to align copy above the the field from Mariya 'align this text and the text below the input box with the box' so this isn't a needed change. Just noting for anyone checking the differences.

Sending back to Execution pending the question about scopes set to 'site' as well as the adjustment of the instructional copy to a more lighter font.

**Comment by asvinb** [comment]
@eugene-manuilov Can you help out here please, namely the "scopes set to 'site' ". Can you provide some more details how it works?
@cole10up AS per our conversation in Slack, we have another ticket which tackles the styling of those pages: https://github.com/google/site-kit-wp/issues/2040
Because if you compare what we have on develop now with the designs in Figma, there are a lot of inaccuracies. The fonts are off in some places, buttons are too small. Let's tackle all styling related issues in the said ticket.

**Comment by eugene-manuilov** [comment]
@asvinb questions with `site` scope apply to the whole site and can be answered by any user with appropriate capabilities. It also means that any user will see site-scope answers previously selected by another user.

In opposite to it, there are user-scoped questions (the first two) which are collected on a per-user basis. Answers for such questions can be viewed and edited only by a user who has answered on it. In other words, I can see/edit my and site-scope answers, you can see/edit yours and site-scope answers, but I can't see yours and you can't see my answers.

**Comment by cole10up** [comment]
### QA :white_check_mark:

Thanks @eugene-manuilov and @asvinb for the clarification. This is good from my end, I'll followup with my findings when https://github.com/google/site-kit-wp/issues/2040 comes into QA.
