### ISSUE TITLE
Tag Manager & Analytics not working

### ISSUE THREAD

**Issue by jonbstrong** [google/site-kit-wp#2303]
I have set up Site Kit on my wordpress site and connected successfully to Tag Manager & Analytics. 
However, when I check my site (spotlightpodcasting.com), neither Google Analytics or any tags are triggered.
I've set this up successfully before on other sites, so am not sure why this is occurring here.

**Comment by jamesozzie** [comment]
@jonbstrong Apologies for the delayed response, we've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.
