### ISSUE TITLE
Delete an old Analytics Tag 

### ISSUE THREAD

**Issue by asitaaa** [google/site-kit-wp#231]
## No place to remove the old tag

Where is the place where I delete the old tag and enter a new one?

**Comment by jamesozzie** [comment]
@asitaaa If the tag was placed via Site Kit then you can navigate to the Analytics settings and choose to "[Remove Snippet](https://i.imgur.com/6ppIDwZ.png)". 
Site Kit > Settings > Analytics > Edit > Remove Snippet. 

If there was already a tag placed then it could be a case whereby you have a plugin which was previously used to place your tag, or else a theme setting or a manual insertion method. If you want to share your URL I can take a look.
