### ISSUE TITLE
Mark user input settings state flag as completed upon completion

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2310]
Following up on #2039 and #2042, the `googlesitekit_user_input_state` flag option should be set to `completed` once user input settings are submitted and complete.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit_user_input_state` flag option should be set to `completed` once user input settings have been saved on the proxy and are set for everything.
* The [logic currently used to check for whether settings have been completed](https://github.com/google/site-kit-wp/pull/2215/files#diff-fd8b5c88edabac5e94ebf3751d5ea639f149dec14a1296a74b6890617a92bf2dR1220-R1228) should be moved to some reusable method which can be used both after syncing values with the proxy as well as in the `admin_init` check when the flag option is empty.

## Implementation Brief

* Add a new public function `get_user_input_state` to the `Core\Authentication\Authentication` class. It should return the private `$user_input_state` property.
* Add a new public function `are_settings_empty` to the `Core\Util\User_Input_Settings` class. It should get the current settings using the `get_settings` function if settings aren't provided via arguments and return TRUE if there is at least one setting with empty `values`, otherwise, return FALSE (see [here](https://github.com/google/site-kit-wp/pull/2215/files#diff-fd8b5c88edabac5e94ebf3751d5ea639f149dec14a1296a74b6890617a92bf2dR1220-R1228) for reference).
* Update the `verify_user_input_settings` method of the `Authentication` class to use the new `are_settings_empty` method of the `$this->user_input_settings` instance instead of hardcoded logic.
* Update the `set_settings` function of the `User_Input_Settings` class to set settings state flag after successfully saving user input settings on the proxy server.

### Test Coverage

* Add appropriate tests to the `Tests\Core\Util\User_Input_SettingsTest` class to check the new `are_settings_empty` method and the new behavior of the `set_settings` method.

### Visual Regression Changes

* No visual changes should be visible on the plugin pages.

## QA Brief

* Check that the `Authentication` class has a new method to get user input state instance and it uses the `are_settings_empty` function to determine whether there are empty settings.
* Check that the `User_Input_Settings` class has a new static method and it sets user input state flag after successful submission.
* Make sure PHPUnit tests the new functionality of the `User_Input_Settings` class.

## Changelog entry

* Mark user input state as completed once user has submitted their information.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> Add a new public static function `are_settings_empty` to the `Core\Util\User_Input_Settings` class.

Hmm, I'm not a big fan of using a static method here if it's avoidable. Since that class should have access to the current settings, I think this should rather be a non-static method that doesn't take any parameters and looks at the current settings instead.

> Update the `set_settings` function of the `User_Input_Settings` class to set settings state flag after successfully saving user input settings on the proxy server.

How do you envision do that? As far as I can tell, right now that class doesn't have access to the user input state class.

> Add a new public function `get_user_input_state` to the `Core\Authentication\Authentication` class. It should return the private `$user_input_state` property.

Potentially we could instead remove the `$user_input_state` property from that class and make it a private property of `User_Input_Settings`, since the user input state is dependent on the user input settings. This would give control of the user input state to the `User_Input_Settings` class, also fixing my response above this one: For example, if you update user input settings, that class would immediately be able to check if the settings are complete, and based on that set the user input state flag internally. (In theory, it could also be that user input settings are suddenly no longer completed, so in that case it would also need to set the flag to `missing` again). For cases where we need to access the user input state from elsewhere, the class could still be exposed via a public method on `User_Input_Settings`. What do you think?

**Comment by eugene-manuilov** [comment]
> > Add a new public static function are_settings_empty to the Core\Util\User_Input_Settings class.
>
> Hmm, I'm not a big fan of using a static method here if it's avoidable. Since that class should have access to the current settings, I think this should rather be a non-static method that doesn't take any parameters and looks at the current settings instead.

It will be used in the Authentication class to determine whether settings have empty values or not. So, we can't make it be non-static.

> > Update the set_settings function of the User_Input_Settings class to set settings state flag after successfully saving user input settings on the proxy server.
>
> How do you envision do that? As far as I can tell, right now that class doesn't have access to the user input state class.

```php
public function set_settings( $settings ) {
    if ( ! $this->is_connected_to_proxy() ) {
        return new WP_Error( 'not_connected', __( 'Not Connected', 'google-site-kit' ), array( 'status' => 400 ) ) );
    }

    $response = $this->sync_with_proxy( $settings );
    if ( ! is_wp_error( $response ) ) {
        $this->authentication->get_user_input_state()->set(
            self::are_settings_empty( $response )
                ? User_Input_State::VALUE_MISSING
                : User_Input_State::VALUE_COMPLETED
        );
    }

    return $reponse;
}
```

> > Add a new public function get_user_input_state to the Core\Authentication\Authentication class. It should return the private $user_input_state property.
>
> Potentially we could instead remove the $user_input_state property from that class and make it a private property of User_Input_Settings, since the user input state is dependent on the user input settings. 

Honestly, both places aren't perfect for keeping an instance of the `User_Input_State`. Both classes, `User_Input_Settings` and `Authentication` rely on it and one class will need to pull an instance from another one. So, I think it won't give us any benefit. DI containers can solve this coupling problem very nicely, but it's out of scope and out of priority for now :smile: 

> For example, if you update user input settings, that class would immediately be able to check if the settings are complete, and based on that set the user input state flag internally. (In theory, it could also be that user input settings are suddenly no longer completed, so in that case it would also need to set the flag to missing again). 

See the example above. We can already do it.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> It will be used in the Authentication class to determine whether settings have empty values or not. So, we can't make it be non-static.

The `Authentication` class has access to the `User_Input_Settings` instance, so it could call the method on that instance I think.

> See the example above. We can already do it.

Ah yes, you're right. I looked again and saw that `User_Input_Settings` has access to the `Authentication` instance. I think that's a bit counter-intuitive, because the `Authentication` class is the "god-class" for all authentication-related behavior, and preferably access from there should only go one way, so I would have preferred to pass more class instances with more granular functionality to `User_Input_Settings`. But anyway, the way it is now, we can do it as you're suggesting.

Overall I think this is good, except for that I still think we should be able to use a non-static method.

**Comment by eugene-manuilov** [comment]
Sounds good. I have updated IB to use a non-static method.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> Add a new public function `are_settings_empty` to the `Core\Util\User_Input_Settings` class. It should accept settings array [...]

Following up on my previous question, why do we need to pass `settings` to the method? Since it's in the `User_Input_Settings` class, I think it could be simplified to just look at the current settings. I don't think there is a scenario where we need to check this for settings which are not the current settings.

**Comment by eugene-manuilov** [comment]
> @eugene-manuilov
> 
> > Add a new public function `are_settings_empty` to the `Core\Util\User_Input_Settings` class. It should accept settings array [...]
> 
> Following up on my previous question, why do we need to pass `settings` to the method? Since it's in the `User_Input_Settings` class, I think it could be simplified to just look at the current settings. I don't think there is a scenario where we need to check this for settings which are not the current settings.

By passing settings as a parameter, we can eliminate a need to re-fetch settings after synchronizing it in the `set_settings` method. Plus, it will be easier to write phpunit tests for that function if we provide settings via args.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> By passing settings as a parameter, we can eliminate a need to re-fetch settings after synchronizing it in the `set_settings` method.

I don't think we would need to re-fetch settings, they'd be cached already:
1. Set settings via API call. Return value is the up-to-date settings (same response that we would get from the API in a call to get the settings), so we can cache them.
2. Check if current settings are empty via new method. This will call `get_settings()`, which will already have valid cached data from the `set_settings` call.

I think requiring settings here is counter-intuitive and as far as I can tell doesn't save us an API call.

> Plus, it will be easier to write phpunit tests for that function if we provide settings via args.

That's a fair point, but the ability to write unit tests IMO shouldn't dictate the production usage to be more complicated. How about supporting a `$settings` parameter but making it optional? This would satisfy the needs for unit tests, but for production usage it would rely on the current settings which is what I'd expect of a method on a class that manages these settings.

**Comment by eugene-manuilov** [comment]
> How about supporting a $settings parameter but making it optional? This would satisfy the needs for unit tests, but for production usage it would rely on the current settings which is what I'd expect of a method on a class that manages these settings.

Yes, I like it. Updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* Completed user input fields
* Verified `completed` status
	```
	⚡  wp user meta get 1 wp_googlesitekit_user_input_state
	completed
	```
* Deleted user setting for user input state
	```
	⚡  wp user meta delete 1 wp_googlesitekit_user_input_state
	Success: Deleted custom field.
	```
* Reloaded admin screen and checked user input state to verify that it was set correctly
	```
	⚡  wp user meta get 1 wp_googlesitekit_user_input_state
	completed
	```
* Verified test coverage in `\Google\Site_Kit\Tests\Core\Util\User_Input_SettingsTest::test_are_settings_empty`
