### ISSUE TITLE
Delete site from authentication service upon uninstallation

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2311]
When the plugin is uninstalled, it should delete the site from the authentication service (via an available endpoint there). Note that this is only possible if the site is currently connected (has site ID and site secret).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* An uninstall hook should be added that, when the plugin is being uninstalled, issues a `POST` request to the authentication service proxy URL with path `/o/oauth2/delete-site/`.
    * The request should only be sent if the site is currently connected.
    * The request should include URL-encoded body parameters `site_id` and `site_secret`.

**Note that this endpoint is not yet live. Before this gets tested and merged, it should be confirmed that it has been published.**

## Implementation Brief

* Add a public method `unregister_site()` to `Google\Site_Kit\Core\Authentication\Google_Proxy`. (#2044 should add the respective counterpart `register_site()` to that class.) This method should send a `POST` request to Site Kit Service as described in the ACs.
* Add an `uninstall.php` file which, if the `WP_UNINSTALL_PLUGIN` constant is there, simply loads the main plugin file to bootstrap the plugin, and after that triggers a parameter-less action `googlesitekit_uninstallation`.
* Implement class `Google\Site_Kit\Core\Util\Uninstallation`:
    * Implement a private `uninstall()` method which calls the new `Google_Proxy::unregister_site()` method. Wrap it in a `try catch` statement, just to ensure it won't cause a fatal error blocking the user from uninstalling.
    * Implement a public `register()` method which hooks the private `uninstall()` method into `googlesitekit_uninstallation` using a closure.
* Instantiate the new `Uninstallation` class in the root of `Plugin::register` (so that it runs "immediately"), and call its `register` method.
* Merge #2317.

### Test Coverage

* 

### Visual Regression Changes

* 

### Plugin side testing
* Install [Log HTTP Requests](https://wordpress.org/plugins/log-http-requests/)
    - Log found under (wp admin) > _Tools_ > _Log HTTP Requests_
* Install Site Kit and go through the setup flow.
* Verify that deleting the plugin triggers a request to the authentication service's `/o/oauth2/delete-site/` route  
_Currently only implemented on the staging proxy – so if not using this, a 404 is expected, otherwise it should be a 200 response_

### Proxy side testing
* Verify that, after setting up the plugin, deleting it marks the site as deleted on the authentication service.
* Also verify that deleting the plugin results in a corresponding activity log.

## Changelog entry

* Unregister the site from the authentication service when the plugin is deleted.

**Comment by aaemnnosttv** [comment]
@felixarntz it seems using `uninstall.php` is preferred over [`register_uninstall_hook`](https://developer.wordpress.org/reference/functions/register_uninstall_hook/#source) since this would cause the `uninstall_plugins` to be additionally queried on every page load as it isn't an autoloaded option.

I understand the main difference is that the plugin isn't loaded normally when using the uninstall file where it is with the hook.

Ideally we could have a simple uninstall file that does something like this instead, but I'm not sure that it would work.
```php
<?php // uninstall.php
if ( defined( 'WP_UNINSTALL_PLUGIN' ) ) {
    include_once __DIR__ . '/google-site-kit.php';
    do_action( 'googlesitekit_uninstallation' );
}
```

Also, perhaps `googlesitekit_uninstall` might be a better name for the action where it matches the word used in core functions and filename?

Everything else LGTM. Assigning back to you for potential revision, but I'll have a look at the PR too given the timeliness of this one 👍

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds good, I've updated the IB.

**Comment by aaemnnosttv** [comment]
IB ✅ 

One non-blocking question remains from my previous comment that maybe you didn't see regarding the name of the action

> perhaps `googlesitekit_uninstall` might be a better name for the action where it matches the word used in core functions and filename?

If you'd prefer to keep `googlesitekit_uninstallation`, that's fine with me too, just a suggestion 🙂 

Moving forward to execution and assigning back to you @felixarntz for the PR to be updated for the change in approach.

**Comment by felixarntz** [comment]
@aaemnnosttv I'd prefer `googlesitekit_uninstallation` because it's in line with our other actions for activation and deactivation.

**Comment by felixarntz** [comment]
@adamsilverstein Can you take care of QA for this one? Since it involves service-side checks. I think you already did most of this anyway.

**Comment by adamsilverstein** [comment]
Sure, I will give it another test against develop.

**Comment by aaemnnosttv** [comment]
Looks like a typo was missed in CR which is causing the uninstall to fail with a fatal. Will submit a quick PR to fix this.

```
[05-Nov-2020 08:36:11 UTC] PHP Warning:  Use of undefined constant __FILE - assumed '__FILE' (this will throw an Error in a future version of PHP) in /srv/users/usera12f8d5d/apps/usera12f8d5d/public/wp-content/plugins/google-site-kit/uninstall.php on line 17
[05-Nov-2020 08:36:11 UTC] PHP Warning:  require_once(./google-site-kit.php): failed to open stream: No such file or directory in /srv/users/usera12f8d5d/apps/usera12f8d5d/public/wp-content/plugins/google-site-kit/uninstall.php on line 17
[05-Nov-2020 08:36:11 UTC] PHP Fatal error:  require_once(): Failed opening required './google-site-kit.php' (include_path='.:/opt/sp/php7.4/lib/php') in /srv/users/usera12f8d5d/apps/usera12f8d5d/public/wp-content/plugins/google-site-kit/uninstall.php on line 17
```

**Comment by aaemnnosttv** [comment]
Assigning to you @felixarntz as I can't merge to master 😄

**Comment by adamsilverstein** [comment]
Tried testing against develop and I'm seeing PHP warnings/fatals mentioned above. Once this is fixed I will try again.

**Comment by aaemnnosttv** [comment]
@adamsilverstein can you try again using master?

**Comment by adamsilverstein** [comment]
I built from master and gave this another test on a fresh install. Everything worked as expected:

* Noted site marked in service when plugin deleted, unmarked when I reinstalled and connected another module.
* Noted request in "Log HTTP Requests" log to delete-site endpoint. 

@felixarntz - Just noticed when testing this that the delete endpoint is at `o/oauth2/delete-site`: what do you think about moving this to `sitemanagement/delete-site` instead?
