### ISSUE TITLE
 Code added to WordPress admin pages outside of Site Kit

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#2315]
## Bug Description

As reported in [this support topic](https://wordpress.org/support/topic/my-personal-email-is-being-displayed-next-to-google-adsense-id-on-page-source/) in relation to the Adsense connection, there is code added to WordPress admin pages not related to Site Kit.

## Steps to reproduce

1. Setup Site Kit/ connect Adsense
2. View WordPress admin page source code where Site Kit is not present
3. See code (in particular scripts starting with `<script id='googlesitekit-apifetch-data-js-extra'>`)

## Additional Context

 - PHP Version: 7.3.23
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.19.0
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On WP Admin screens where there's no Site Kit functionality (i.e. any non-Site Kit admin screen except the WP dashboard and the WP plugins screen), the only Site Kit data and scripts loaded (check HTML source code) should be the `googlesitekit-base` JavaScript file and the related `_googlesitekitBaseData` JS object.

## Implementation Brief

* Remove `googlesitekit-apifetch-data` as dependency from the `googlesitekit-base` script in PHP.

### Test Coverage

* No additional coverage needed

### Visual Regression Changes

* N/A

## QA Brief

* Go to the Plugins screen or another screen without Site Kit contents and ensure no `<script id='googlesitekit-apifetch-data-js-extra'>` can be found.

## Changelog entry

* Ensure that REST API preloaded data is not computed and included outside of Site Kit admin screens.

**Comment by felixarntz** [comment]
While the support thread is focused on a piece of information in `_googlesitekitLegacyData` (which is not exposed anywhere it shouldn't be), there is an actual (minor) problem here, which is that we unnecessarily include certain Site Kit information on pages that are not owned by Site Kit (any WP Admin page, e.g. "Pages" or "Media"). Those non-Site Kit WP Admin pages should only ever include two things: The `googlesitekit-base` JavaScript file, plus the PHP-to-JS data that is needed for that file to work.

However, currently we also include `_googlesitekitAPIFetchData` with all API-preloaded data for those pages, which causes quite a bit of logic to unnecessarily run on every WP Admin pageload. I believe this was introduced in https://github.com/google/site-kit-wp/commit/e317a7b0b242a9d22b5c23cc210ae0af21c60bb0 (accidentally? Or was that on purpose?).

cc @aaemnnosttv

**Comment by aaemnnosttv** [comment]
@felixarntz in the commit you reference there, `window._googlesitekitAPIFetchData` was being set in the inline script called in the `before_print` callback of `googlesitekit-base`, it only moved to being a named `Script_Data` dependency but it was still run as part of the base handle before that.

The more expensive part which has changed since then is that we include the preloaded data in the API fetch data now, but I don't believe that commit was problematic on its own.

With that said, I don't think the base data should depend on the API fetch data so the proposed change should be an improvement 👍 

IB ✅  
(I filled in the test-related parts there as well since nothing is needed)

**Comment by felixarntz** [comment]
@aaemnnosttv Thanks for clarifying, that makes sense.

**Comment by cole10up** [comment]
### **QA ✅**

Activated latest develop, navigated to a few pages that don't have SK content. Checked if <script id='googlesitekit-apifetch-data-js-extra'> was present.

![image](https://user-images.githubusercontent.com/57115907/100551139-c2ed8900-3233-11eb-9aa1-eed21aa2899f.png)

![image](https://user-images.githubusercontent.com/57115907/100551198-06e08e00-3234-11eb-8a75-6ef0f45a725e.png)

![image](https://user-images.githubusercontent.com/57115907/100551214-15c74080-3234-11eb-8314-0c110865fa8c.png)

Looks good, sending to approval.
