### ISSUE TITLE
Wrong Individual Post Page Stats

### ISSUE THREAD

**Issue by phamquangbaoplus** [google/site-kit-wp#2318]
## Steps to reproduce

1. I have 2 posts in 2 languages, 2 post-slug is same (Polylang Pro)

- http://domain.com/cat/post-slug
- https://domain.com/vi/cat/post-slug

2. Go to https://domain.com/wp-admin/admin.php?page=googlesitekit-dashboard&permaLink=http://domain.com/cat/post-slug

3. It shows details of https://domain.com/vi/cat/post-slug

## Additional Context

 - PHP Version: 7.4
 - OS: Windows 10
 - Browser: Chrome
 - Plugin Version: 1.19.0
 - Device: PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@phamquangbaoplus Apologies for the delayed response, we've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.
