### ISSUE TITLE
Page isn't Working: HTTP ERROR 414

### ISSUE THREAD

**Issue by Loganson** [google/site-kit-wp#232]
![IMG_0171](https://user-images.githubusercontent.com/52833711/61149695-5db2bf80-a4a7-11e9-8cae-9c68c235b6b3.jpg)

Get the "Client ID" when you sign in to your Gmail account and "Allow" it goes to this page or a blank page. I've had both happen.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ahmadawais** [comment]
@westonruter @felixarntz I have the same issue with https://AhmadAwais.com/

![issue](https://on.ahmda.ws/f727e8/c)

Can you folks help :)

**Comment by ahmadawais** [comment]
I removed the following part of the URL to make it work.

```
&scope=email%20profile%20https://www.googleapis.com/auth/analytics.edit%20https://www.googleapis.com/auth/analytics.manage.users%20https://www.googleapis.com/auth/analytics.readonly%20https://www.googleapis.com/auth/analytics%20https://www.googleapis.com/auth/webmasters%20https://www.googleapis.com/auth/siteverification%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid

```

**Comment by ahmadawais** [comment]
On second thought, SiteKit says it's authenticated but it won't load any data since I edited the callback URL. It's stuck at API requests being 414 as you can see here.

![](http://on.ahmda.ws/668d1c/c)

**Comment by jamesozzie** [comment]
@ahmadawais Thanks for reporting. If you are using a security or Firewall plugin there can be limited on long URL strings, which is the likely cause. 

If you are using iThemes security can you uncheck [this option](https://i.imgur.com/7OyyYyI.png) and see if it resolves the issue.

**Comment by Loganson** [comment]
Yes, you got it. disabled the security plugins and installed. That solved it for me.
