### ISSUE TITLE
Enforce valid user input states with sanitize_callback

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2323]
## Feature Description

In #2042 we added a new `User_Input_State` user setting for storing the user input state. The setting has limited options for the values which are valid to set. This is currently implemented as as part of `User_Input_State::set`, but where possible we try to leverage core functionality through registered options/settings to have our logic applied more globally. As such, using a `sanitize_callback` to handle the same logic is better suited to applying this logic which also applies to setting the value via the REST API or wp-cli as well, not just the one method.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The validation for valid values to be set for the `googlesitekit_user_input_state` user option should be enforced via a `sanitize_callback` registered for the user meta

## Implementation Brief

* In `User_Input_State`, override the `get_sanitize_callback` method to return a closure which accepts a `$value` and returns `false` if the given value is not one of the valid options (just like is done in the `set` method currently)
* Remove the `User_Input_State::set` method

### Test Coverage

* No changes should be necessary to existing PHPUnit coverage
* A test could be added to show that the restriction also applies when calling `update_user_option` as well

### Visual Regression Changes

* N/A

## QA Brief

* Identify your username in WP, referenced below as `admin` (replace with your username if different)
* Run `wp user meta set admin wp_googlesitekit_user_input_state required`
    - `wp user meta get admin wp_googlesitekit_user_input_state` should output `required`
* Run `wp user meta set admin wp_googlesitekit_user_input_state completed`
    - `wp user meta get admin wp_googlesitekit_user_input_state` should output `completed`
* Run `wp user meta set admin wp_googlesitekit_user_input_state missing`
    - `wp user meta get admin wp_googlesitekit_user_input_state` should output `missing`
* Run `wp user meta set admin wp_googlesitekit_user_input_state invalid`
    - `wp user meta get admin wp_googlesitekit_user_input_state` should output nothing

## Changelog entry

* Improve validation of user input submission states.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@cole10up @wpdarren – if you guys aren't familiar with wp-cli, then feel free to tag this one as **QA:Eng** 👍

**Comment by cole10up** [comment]
Going to tag this one QA:Eng. I setup WP-CLI on my local. And immediately started having issues connecting to the database. I spent a bit of time troubleshooting this issue here: https://wordpress.stackexchange.com/questions/290793/wp-cli-error-establishing-a-database-connection-in-localhost-mamp

I have my creds matching wp-config.php and my local. Still receiving the following:

![image](https://user-images.githubusercontent.com/57115907/102581653-d9aa3180-40b5-11eb-8bd0-95d4e5a490c3.png)

I'll pass this one along to QA Engineering and continue to troubleshoot.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:
