### ISSUE TITLE
Revise global "Permissions issue accessing data" notice for additional users if they only have access to some services

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2329]
## Bug Description

At present if a second administrator logs into Site Kit and verifies ownership they may not have permissions to an already connected Analytics account. In this case the "`Permissions issue accessing data`" notice could be improved. Alternatively it may be removed considering a suitable notice does appear within the product [product widgets](https://i.imgur.com/Z7mZOFY.png). 

![image](https://user-images.githubusercontent.com/41326532/98267272-19dca700-1f83-11eb-84be-e56dfc9a8b90.png)

## Steps to reproduce

1. Setup SK and connected the SC and Analytics modules
2. Create another WP administrator account
3. Setup Site Kit with this new account, using a Google account which doesn't have access to that Analytics property
4. After verification the global notice appears on the main Site Kit dashboard 

## Screenshots

_Image of the Analytics widget notice_

![image](https://user-images.githubusercontent.com/41326532/98270915-472b5400-1f87-11eb-89bc-d489d0aca4ce.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The global warning "Permissions issue accessing data" should be removed and no longer ever appear.
* The `DashboardPermissionAlert` component and all of its usage should be removed.

## Implementation Brief

* Remove `assets/js/components/notifications/dashboard-permission-alert.js`
* Remove `addFilter` from `assets/js/components/data/index.js` when the `reason` is `'forbidden'`

### Test Coverage

* 

### Visual Regression Changes

* No changes

## QA Brief

* When the **Steps to reproduce** mentioned above are followed, the notification provided in the screenshot with text 
	```
	This account does not have access to the requested data.
	```
	does not appear anymore.

## Changelog entry

* Remove outdated dashboard notification warning vaguely about missing permissions, which is now covered with more specific widget CTAs.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

**Verified:**

- Within the dashboard the Analytics data no permission message can be found - [Screenshot](https://user-images.githubusercontent.com/73545194/100231556-26409800-2f62-11eb-8b91-2ac7271f333a.png)

- When I go to the Google Analytics module the permissions message does appear. 

![Screenshot](https://user-images.githubusercontent.com/73545194/100231933-a23ae000-2f62-11eb-8082-0ad513c1aeba.png)

**Comment by benbowler** [comment]
Hey @wpdarren, the Bug Description is a little confusing, going by the acceptance criteria the aim of this PR was to:

- The global warning "Permissions issue accessing data" should be removed and no longer ever appear.

The warning this is referencing is:

![98267272-19dca700-1f83-11eb-84be-e56dfc9a8b90](https://user-images.githubusercontent.com/119352/100235490-66812580-2f24-11eb-9fd1-e0b63303699c.png)

I followed the QA steps and, even when switching the date range selector the "Permissions issue accessing data" does not appear:

<img width="1866" alt="Screenshot 2020-11-25 at 13 44 11" src="https://user-images.githubusercontent.com/119352/100235864-d42d5180-2f24-11eb-9421-9226c8a3c0b6.png">
<img width="1866" alt="Screenshot 2020-11-25 at 13 44 19" src="https://user-images.githubusercontent.com/119352/100235873-d8f20580-2f24-11eb-890e-982ea978d6b0.png">
<img width="1866" alt="Screenshot 2020-11-25 at 13 44 26" src="https://user-images.githubusercontent.com/119352/100235875-da233280-2f24-11eb-9848-989a0633c6c8.png">

The errors that appear on each widget are: "suitable notice does appear within the product product widgets".

**Comment by wpdarren** [comment]
@benbowler okay, since it's the `Permissions issue accessing data ` message I am checking for then yes, this passes.

I am am still confused why the **Data error in Analytics** messages appear when changing the date period to anything but 28 days.  This seems odd to me. It should be consistent for all date periods in my opinion.  I'll look into this and see if it needs a ticket creating or is expected behaviour. 

QA Pass ✅ 

Verified:  Permissions issue accessing data message does not appear on the dashboard.    [Screenshot](https://user-images.githubusercontent.com/73545194/100231556-26409800-2f62-11eb-8b91-2ac7271f333a.png)
