### ISSUE TITLE
Property setting doesn't get fully created

### ISSUE THREAD

**Issue by asitaaa** [google/site-kit-wp#233]
When I create a new account for analytics in site-kit, it doesn't fully get created. Hence, I can seem to remove it from my Google Analytics dashboard.
![2019-07-12_11-17-49](https://user-images.githubusercontent.com/52835521/61150079-656a6800-a497-11e9-8871-1f403377e7cf.png)

**Comment by jamesozzie** [comment]
@asitaaa Thanks for reporting, hopefully we can assist with this. I assume you mean a new "Property" as accounts must be created from Analytics and not within Site Kit (although Site Kit does direct users to Analytics when they choose to create a new account). 

When adding a new Site Kit property do you know if you had a property with the same name in your Analytics previously? If it was deleted it's common to appear greyed out as in your screenshot, and within your Analytics it should appear as if you have 2 of the same property IDs. 

If you want to take a video grab of the process showing your Site Kit new property creation to then viewing the property in your Analytics? We can then troubleshoot further, and I will test on my side and see if I can recreate the problem also.

**Comment by jamesozzie** [comment]
@asitaaa Did you manage to get the Analytics module setup successfully?

**Comment by asitaaa** [comment]
Hi James,

Unfortunately, I'm still having issues. Let me explain. I had two tracking
code in one.
[image: 2019-07-25_09-42-02.png]

So, I deleted the second one and created its own account. However, I still
fetches the old one.

[image: 2019-07-25_09-43-18.png]

I've tried unloading the plugin and reloading it again. No luck.

**Comment by jamesozzie** [comment]
@asitaaa Looking at your initial screenshot also the property is greyed out. This means the property is either scheduled for deletion already or that you don't have full admin permissions to that property. If it's the former (scheduled for deletion) then you can wait for 35 days before it's removed from view using that account. 

If the primary issue you are encountering remains (Analytics property not being created) please inform me what error message or notice you are receiving from within Site Kit. The images you referenced did not attach with your last message.

**Comment by jamesozzie** [comment]
@asitaaa Are you encountering the same issue with Analytics from your Site Kit setup?

**Comment by jamesozzie** [comment]
@asitaaa I will close this ticket now, if the issue remains feel free to reopen.
