### ISSUE TITLE
Analytics: Refetch account not working

### ISSUE THREAD

**Issue by rastarchele** [google/site-kit-wp#234]
Already Have Google Analytics But not Fetching  - Tell me to sign up again - 

![61009072-c26bfe00-a371-11e9-9d8f-d0120cf9b20a](https://user-images.githubusercontent.com/41326532/62315521-68042000-b48d-11e9-8cc8-679b81c15657.png)

Additional context: See @IanJSaul below: 

> I have repeated the steps above, disabled every plugin on the site, and switched it to one of the default WP themes while troubleshooting, and have had no luck getting it to fetch my Analytics.
> 
> I've reset the Site Kit plugin, bypassed all caching options, specifically CloudFlare, and wipe all caches before testing.
> 
> Tried two browsers with no plugins enabled on them, cleared all browser caches, etc.

Here is the XHR responses:

{"accounts":[{"created":"2014-09-06T17:53:33.397Z","id":"54516992","kind":"analytics#account","name":"Demo Account","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/54516992","starred":null,"updated":"2019-06-10T17:56:03.215Z","permissions":{"effective":["READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/54516992/webproperties","type":"analytics#webproperties"}},{"created":"2015-05-19T15:16:46.171Z","id":"63132339","kind":"analytics#account","name":"DBO","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/63132339","starred":null,"updated":"2019-06-03T14:53:42.792Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/63132339/webproperties","type":"analytics#webproperties"}},{"created":"2015-08-27T00:23:22.902Z","id":"66843629","kind":"analytics#account","name":"DEC","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/66843629","starred":null,"updated":"2019-02-12T00:07:22.694Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/66843629/webproperties","type":"analytics#webproperties"}},{"created":"2018-02-21T16:00:38.054Z","id":"114524566","kind":"analytics#account","name":"GLO","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/114524566","starred":null,"updated":"2019-02-12T00:07:43.046Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/114524566/webproperties","type":"analytics#webproperties"}},{"created":"2018-08-30T22:14:16.647Z","id":"125004248","kind":"analytics#account","name":"DAC","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/125004248","starred":null,"updated":"2019-02-12T00:06:12.477Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/125004248/webproperties","type":"analytics#webproperties"}},{"created":"2018-11-30T01:10:36.707Z","id":"130186507","kind":"analytics#account","name":"KDM","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/130186507","starred":null,"updated":"2019-02-12T00:08:22.553Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/130186507/webproperties","type":"analytics#webproperties"}},{"created":"2019-01-18T22:24:16.638Z","id":"132742205","kind":"analytics#account","name":"HRE","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/132742205","starred":null,"updated":"2019-02-12T00:07:57.215Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/132742205/webproperties","type":"analytics#webproperties"}}],"properties":[],"profiles":[]}

#375

**Comment by MarksSmartCribs** [comment]
I am having the same problem

**Comment by MarksSmartCribs** [comment]
Looks like you don't have Analytics account yet. Once you create it click "Re-fetch my account" and Site Kit will locate it.

**Comment by rastarchele** [comment]
Same here - need solution🥺😔

**Comment by neilcoza** [comment]
I have pressed the re-fetch button many times. To check I still had an account I logged in independent of the plugin. No problem there

**Comment by seanchk** [comment]
I'm having the same problem.  SiteKit won't fetch my existing Analytics account.

**Comment by jamesozzie** [comment]
@rastarchele Can you try the following and see if you are able to connect Analytics:
1. Disconnect the Analytics module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
2. Temporarily deactivate other active WordPress plugins
3. Open your WordPress admin panel in an incognito window
4. Add the Analytics module again (Site Kit > Settings > Connect more service > Analytics)
5. Follow the setup procedure 

Please then see if Site Kit can identify your existing account.

**Comment by Anscha3** [comment]
Hi, I have the same problem and followed your advice but got the same result, that the process did not find my Analytics account, although I can login the normal way. 

I deactivated the plugin "Google Analytics for WordPress by MonsterInsights" in case the was a problem between those two plugins.

**Comment by jamesozzie** [comment]
@rastarchele Did you get a chance to deactivate your other plugins and check again? As @Anscha3 mentioned there are some plugins which can conflict with Site Kit.

**Comment by Anscha3** [comment]
Hi James, I deactivated plugin by plugin until I got to "Insert Headers and Footers" after that, the process was able to finish configuring. Thank you very much for this hint, James!

**Comment by IanJSaul** [comment]
Aloha,

I have repeated the steps above, disabled every plugin on the site, and switched it to one of the default WP themes while troubleshooting, and have had no luck getting it to fetch my Analytcis.

I've reset the Site Kit plugin, bypassed all caching options, specifically CloudFlare, and wipe all caches before testing.

Tried two browsers with no plugins enabled on them, cleared all browser caches, etc.

**Comment by jamesozzie** [comment]
@IanJSaul Do you have any security or firewall extension installed and active on your web host? 
Can you also send any chrome console errors or [XHR responses](https://i.imgur.com/jLBwBdH.png)?

**Comment by IanJSaul** [comment]
I notice from browsing a few other threads that this may be related to either Cloudways or DigitalOcean.

I managed to add multiple other nearly identical (we run a standardized security and plugin suite on all sites), however, on this 4th-5th one, I'm running into this issue, so it doesn't make perfect sense for it to be tied to the servers.

I very much appreciate your assistance with this.

Here is the XHR responses:

{"accounts":[{"created":"2014-09-06T17:53:33.397Z","id":"54516992","kind":"analytics#account","name":"Demo Account","selfLink":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/54516992","starred":null,"updated":"2019-06-10T17:56:03.215Z","permissions":{"effective":["READ_AND_ANALYZE"]},"childLink":{"href":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/54516992\/webproperties","type":"analytics#webproperties"}},{"created":"2015-05-19T15:16:46.171Z","id":"63132339","kind":"analytics#account","name":"DBO","selfLink":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/63132339","starred":null,"updated":"2019-06-03T14:53:42.792Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/63132339\/webproperties","type":"analytics#webproperties"}},{"created":"2015-08-27T00:23:22.902Z","id":"66843629","kind":"analytics#account","name":"DEC","selfLink":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/66843629","starred":null,"updated":"2019-02-12T00:07:22.694Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/66843629\/webproperties","type":"analytics#webproperties"}},{"created":"2018-02-21T16:00:38.054Z","id":"114524566","kind":"analytics#account","name":"GLO","selfLink":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/114524566","starred":null,"updated":"2019-02-12T00:07:43.046Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/114524566\/webproperties","type":"analytics#webproperties"}},{"created":"2018-08-30T22:14:16.647Z","id":"125004248","kind":"analytics#account","name":"DAC","selfLink":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/125004248","starred":null,"updated":"2019-02-12T00:06:12.477Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/125004248\/webproperties","type":"analytics#webproperties"}},{"created":"2018-11-30T01:10:36.707Z","id":"130186507","kind":"analytics#account","name":"KDM","selfLink":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/130186507","starred":null,"updated":"2019-02-12T00:08:22.553Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/130186507\/webproperties","type":"analytics#webproperties"}},{"created":"2019-01-18T22:24:16.638Z","id":"132742205","kind":"analytics#account","name":"HRE","selfLink":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/132742205","starred":null,"updated":"2019-02-12T00:07:57.215Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https:\/\/www.googleapis.com\/analytics\/v3\/management\/accounts\/132742205\/webproperties","type":"analytics#webproperties"}}],"properties":[],"profiles":[]}

**Comment by jamesozzie** [comment]
@IanJSaul It's probably worth looking deeper into this, and creating a separate issue to dig deeper find the root cause. Before we do can you check the following from your Google Cloud Console:
- Ensure you have [enough resources](https://console.cloud.google.com/cloud-resource-manager) to create a new project. Clicking on the "Create Project" button should inform you of your remaining quota. While the project gets created in advance of adding the Analytics module please confirm. 
- Ensure there are no [API key restrictions](https://i.imgur.com/p9c4S3M.png)

**Comment by IanJSaul** [comment]
The latest release 1.0.3 has fixed the issue.

The only other change I made during this period, was to not only disable, but also uninstall Breeze, which is a Cloudways specific caching plugin.

Thank you James!

**Comment by jamesozzie** [comment]
@rastarchele Are you encountering the same issue when attempting to setup the Analytics module? If so please attempt temporarily deactivating any security or firewall plugins one by one before attempting the Analytics module setup.
