### ISSUE TITLE
Webpack dist grows with every change in watch mode

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2344]
## Bug Description

In #1700 we updated our build process to write content hashes into our webpack bundle filenames to avoid conflicts with aggressive browser/cdn/plugin caching. While this works well, it currently doesn't clean up after itself when running in watch mode.

This causes unnecessary files to accumulate, which aside from the wasted disk space, increases CPU usage noticeably when making changes as webpack is both generating new files, and the editor is indexing them.

## Steps to reproduce

1. Run `npm run watch`
1. Modify `assets/js/googlesitekit-activation.js` and save (the file is arbitrary – any bundle that's built with a hash in the file name will work)
1. Notice there are now duplicate entries in `dist/assets/js` for this module

```
-rw-r--r--   1 aaemnnosttv  staff   615K Nov 10 22:48 googlesitekit-activation.19dfb03d188a9fe4e5d9.js
-rw-r--r--   1 aaemnnosttv  staff   436K Nov 10 22:48 googlesitekit-activation.19dfb03d188a9fe4e5d9.js.map
-rw-r--r--   1 aaemnnosttv  staff   615K Nov 10 22:48 googlesitekit-activation.5a32dc60289c284f93fe.js
-rw-r--r--   1 aaemnnosttv  staff   436K Nov 10 22:48 googlesitekit-activation.5a32dc60289c284f93fe.js.map
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Only the current version of a bundle should be present in the `dist` directory, regardless of which mode Webpack is running in (watch or not)

## Implementation Brief

* Edit the main `wepback.config.json` file:
  * Change output.filename to be `mode == 'production' ? '[name].[contenthash].js' : '[name].js'`

### Test Coverage

* Not needed

### Visual Regression Changes

* No visual changes are expected as a result of this change

## QA Brief

* Run `npm run watch` command and check that generated assets don't have hashes in filenames.
* Build production assets with `npm run build:prod` and make sure that generated assets have hashes in filenames.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@eugene-manuilov here's the issue I mentioned last week. cc: @felixarntz @tofumatt

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: Webpack works as expected: uses hashes for the production build and builds assets without hashes in the development mode.
