### ISSUE TITLE
Refactor numeric event keyCode references with @wordpress/keycodes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2345]
## Feature Description

We currently use a number of event listeners on keyboard events which listen for specific key codes to identify which key was pressed. Since the event's `keyCode` is numeric, it makes the code less expressive and harder to read without additional comments.

The [`@wordpress/keycodes`](https://github.com/WordPress/gutenberg/tree/master/packages/keycodes) package exports nice named constants for all the keys, as well as a few functions for identifying more complex combinations.

We should update our references to key codes with the named constants to make them easier to read and work with.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instances or references to numeric values for `event.keyCode` should be replaced with the equivalent named exports from the [`@wordpress/keycodes`](https://github.com/WordPress/gutenberg/tree/master/packages/keycodes) package

## Implementation Brief
- Install the [`@wordpress/keycodes`](https://github.com/WordPress/gutenberg/tree/master/packages/keycodes) package as `dependency` (not as a `devDependency`)
- Using the following files:
	- `/assets/js/components/settings/settings-module.js`
	- `/assets/js/components/ResetButton.test.js`
	- `/assets/js/components/user-input/UserInputKeywords.js`
	- `/assets/js/components/UserMenu.js`
	- `/assets/js/components/ResetButton.js`
	- `/assets/js/components/UserMenu.test.js`
	- Import the necessary key constant to be used. For e.g:
		```js
		import { ESCAPE } from '@wordpress/keycodes';
		```
	- Replace the check for the keyCode by the constant. For e.g
		```js
		if ( ESCAPE === e.keyCode ) {
			...
		}
		```
- Breakdown of key codes along with their constant:
	- 13: `ENTER`
	- 27: `ESCAPE`
	- 32: `SPACE`
- Using `/components/user-input/UserInputKeywords.js`
	- Since comma, keycode 188, is not supported by `@wordpress/keycodes`, create a new constant for the comma keycode, `COMMA`
	- Update all references to the 188 keycode by the `COMMA` constant

### Test Coverage
- No new tests to be written. Existing tests should pass.

### Visual Regression Changes

- No visual regressions should occur.

## QA Brief

All these should pass:
* Click on the email address on the top right to open up `UserMenu`.
	* Press Escape to close it
	* Select any option using arrow keys and press space/enter to trigger the expected behavior.
	* Click disconnect, a modal dialog must open, press escape to close it.
* Go to settings -> Admin Settings and click on `Reset` button. A modal should popup which can be closed by pressing escape.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz @tofumatt

**Comment by aaemnnosttv** [comment]
@asvinb – this mostly looks good to go, just a few points to refine.

* Let's note that `@wordpress/keycodes` should be installed under `dependencies` rather than a devDependency to be explicit about that
* Regarding the lack of a `COMMA` export from that package, let's refactor that component to use a constant anyways, as if the package exported it, but just define it in the file for now – we can always move it if it's needed elsewhere but that's a bit of a special case as far as key codes go 😄 
* Don't forget to fill in the "Test Coverage" section, even if there are no changes to be made, just say so 👍 
* Regarding the estimate, we generally only use `1` for the simplest of simple tasks since this is almost impossible to fit ENG+CR+QA into 1hr, so let's bump it up a little bit even though this is rather simple

**Comment by asvinb** [comment]
@aaemnnosttv IB updated as per your comments.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
@aaemnnosttv I know I am late to the party, but I want to suggest not using `@wordpress/keywords` because it brings an additional [~82kb](https://bundlephobia.com/result?p=@wordpress/keycodes@2.16.0) to our bundle which is a big price for using just 3 constants from that package. Let's better define those constants in our codebase and use it instead of `@wordpress/keywords`?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I don't think that accounts for dead code elimination that webpack does.

Here's a diff of before/after, using `bundlesize` with `develop` and this branch after (with hashes omitted to focus on file size differences)

The result is about `0.1KB` difference in some files.

<details>
  <summary>diff</summary>

```diff
diff --git a/test.txt b/test.txt
index 5893cae3e..4b1ff6f80 100644
--- a/test.txt
+++ b/test.txt
@@ -4,19 +4,19 @@
 
  PASS  ./dist/wpdashboard.js: 454B < maxSize 270KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-activation.js: 42.07KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-activation.js: 42.06KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-adminbar.js: 59.91KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-adminbar.js: 60.07KB < maxSize 280KB (gzip) 
 
  PASS  ./dist/assets/js/googlesitekit-api.js: 9.4KB < maxSize 280KB (gzip) 
 
  PASS  ./dist/assets/js/googlesitekit-base.js: 2.1KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-dashboard-details.js: 69.31KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-dashboard-details.js: 69.35KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-dashboard-splash.js: 59.45KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-dashboard-splash.js: 59.62KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-dashboard.js: 71.39KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-dashboard.js: 71.43KB < maxSize 280KB (gzip) 
 
  PASS  ./dist/assets/js/googlesitekit-data.js: 3.46KB < maxSize 280KB (gzip) 
 
@@ -28,28 +28,28 @@
 
  PASS  ./dist/assets/js/googlesitekit-i18n.js: 3.83KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-module.js: 67.69KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-module.js: 67.73KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-modules-adsense.js: 59.88KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-modules-adsense.js: 59.92KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-modules-analytics.js: 61.54KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-modules-analytics.js: 61.94KB < maxSize 280KB (gzip) 
 
  PASS  ./dist/assets/js/googlesitekit-modules-optimize.js: 17.36KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-modules-pagespeed-insights.js: 31.02KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-modules-pagespeed-insights.js: 31.03KB < maxSize 280KB (gzip) 
 
  PASS  ./dist/assets/js/googlesitekit-modules-search-console.js: 18.3KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-modules-tagmanager.js: 31.4KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-modules-tagmanager.js: 31.49KB < maxSize 280KB (gzip) 
 
  PASS  ./dist/assets/js/googlesitekit-modules.js: 15.04KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-settings.js: 74.83KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-settings.js: 74.86KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-user-input.js: 72.34KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-user-input.js: 72.39KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-vendor.js: 223.2KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-vendor.js: 224KB < maxSize 280KB (gzip) 
 
  PASS  ./dist/assets/js/googlesitekit-widgets.js: 11.73KB < maxSize 280KB (gzip) 
 
- PASS  ./dist/assets/js/googlesitekit-wp-dashboard.js: 59.95KB < maxSize 280KB (gzip) 
+ PASS  ./dist/assets/js/googlesitekit-wp-dashboard.js: 60.13KB < maxSize 280KB (gzip) 
```

</details>

If it were 82KB like you're saying, then yes I agree it would be too much, but I think this is quite marginable and should be fine.

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

**Verified:** 

- When clicking on the email address on the top right to open up `UserMenu` the menu closes when Escape key is pressed.
- When clicking on the email address on the top right to open up `UserMenu` and you are able to move through the options with the arrow keys and space/enter to select an option. 
- When `disconnect` option is selected, the dialog box opens and it closes when Escape key is pressed. 
- Going to settings -> Admin Settings and clicking on Reset button the modal opens and can be closed by pressing the Escape key.
