### ISSUE TITLE
Unable to Fetch Data Error 400 / REST API ISSUE

### ISSUE THREAD

**Issue by loganlucky** [google/site-kit-wp#235]
## Bug Description

Data doesn't fetch. I have iThemes Security, but disabling it didn't help. I don't have the blocking of long links selected, tried to select it, then it bring error 414. 

Tried to disconnect, reset, delete cloud, disable plugins and so on. 

I have all, except jquery and XRM disabled in function.php from this post.
Maybe I need to enable any of them?
https://geekflare.com/wordpress-performance-optimization-without-plugin/

Is REST API needed for this plugin? How can I fix this?

## Screenshots

![error400](https://user-images.githubusercontent.com/52837404/61153907-574b3480-a4f5-11e9-888a-127ae1daeb4d.jpg)

![image](https://user-images.githubusercontent.com/52837404/61153995-9aa5a300-a4f5-11e9-9422-16359541dd40.png)

## Additional Context

 - PHP Version: 7+
 - Browser Chrome
 - Plugin Version Newest
 - Device: PC

#150

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by loganlucky** [comment]
Missing request parameter. How do I add it?

**Comment by loganlucky** [comment]
Bump?

**Comment by jamesozzie** [comment]
@loganlucky Thanks for reporting. Do you mind checking the following:
1. ithemes: In your ithemes please untick [this setting](https://i.imgur.com/7OyyYyI.png)
2. Check if you hosting if you have any Firewall or additional security extensions in place (ie. modsecurity). If so temporary disable them,
3. Change your active WordPress theme 
4. Check your site incognito mode to rule out any possible interfering browser extensions

Let me know if any of the above result in your Site Kit dashboard working

**Comment by loganlucky** [comment]
Hey, James, 
1.Never ticked. Tried also deleting it, no change.
2. Disabled all, no change.
3. Same thing with other themes.
4. In incignito same thing. 

Something is blocking connection to the server?

**Comment by jamesozzie** [comment]
@loganlucky ModSecurity might have conflicting settings if you have that enabled at web host level. What other security/firewall/caching plugins are you using?

**Comment by jamesozzie** [comment]
Potential fix #339

**Comment by loganlucky** [comment]
ModSecurity, it was disabled, but no change. I don't see fix in that post, will you fix in next version?

**Comment by jamesozzie** [comment]
@loganlucky If possible can you attempt with another site on the same server, or for further troubleshooting use a plugin such as [Duplicator](https://wordpress.org/plugins/duplicator/) to copy your own site to another server before testing. This can rule out the issue being with your hosting environment or configuration?

You can also share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard if the above fails to find any issue.

**Comment by jamesozzie** [comment]
@loganlucky Did you have a chance to test setting up Site Kit again? If you are encountering the same issue feel free to share you Site Health info and I can see if we can notice anything which could be impacting your setup.
