### ISSUE TITLE
Lint all first-party JS + PHP

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2355]
## Feature Description

A recent travis run raised some javascript linting issues, we need to make sure we're linting all code the same as our CI pipeline.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All JS tracked in the repository should be included ESLint checks, unless explicitly ignored in the `.eslintignore`
	- `.storybook`
	- `assets/js`
	- `packages`
	- `stories`
	- `tests`
	- `./` (config files)
* All PHP tracked in the repository should be included in PHPCS checks, unless explicitly ignored in the `phpcs.xml`
	- `bin`
	- `includes`
	- `tests`
	- `./` (top level plugin and config files)
* All paths which are included in linting checks should also be checked at the time of commit
	- commits containing invalid code according to linting standards should be blocked by Husky's pre-commit hook

## Implementation Brief

* Change the [lint-staged](https://github.com/google/site-kit-wp/blob/39a79205909d539f2cf2b7bcbfc07d2cce90f10f/package.json#L78) directive from `"assets/js/**/*.js"` to `"*.js"` so that [.eslintignore](https://github.com/google/site-kit-wp/blob/develop/.eslintignore) will be the gatekeeper for what is / isn't tested.

### Test Coverage

N/A
### Visual Regression Changes

N/A

## QA Brief

Change code (js/php/css) from every top level directory in repo, ensure that it runs through a linter on git commit.

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@ivankruchkoff – I've updated the ACs here to be a bit more robust, just to make sure we have everything covered. Can you review the IB to see if that's the only change that's needed? I have a feeling the `lint-staged` config is a bit overly specific regarding JS.

**Comment by ivankruchkoff** [comment]
`.eslintignore` defines which files should be ignored from lint,`lint-staged` is our pre-commit hook in `package.json` that specifies which linters should be called for their corresponding glob patterns. The aim of this ticket is more to ensure that we're linting every file that changes prior to committing.

**Comment by aaemnnosttv** [comment]
> The aim of this ticket is more to ensure that we're linting every file that changes prior to committing. I _think_ our linting config is correct, but our pre-commit linting hooks are letting some things slip through unlinted.

@ivankruchkoff I also think the linting config is correct, since this came up I think it's worth revisiting both to make sure we're all covered. I'll look into that more closely and revise the ACs.

**Comment by aaemnnosttv** [comment]
@ivankruchkoff – The ACs should be good to go here – regarding the IB, we should rely on the respective tool-specific ignore files as the source of truth as to what to lint and what not to. As to the lint-staged config, this should already be done for PHP where it includes `*.php` so let's do the same for JS, unless there's some reason why we can't/shouldn't 👍

**Comment by ivankruchkoff** [comment]
@aaemnnosttv agreed. `*.js` would be best and would allow `.eslintignore` to make the determination for what can be ignored.

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff – IB ✅ although it can be simplified a bit and doesn't need the reference to the branch anymore since that isn't really needed.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark:

Everything works as expected. I am moving this ticket to the Approval column, however, I have one question: do we need to add `/node_modules/*` to the `.eslintrc.json` file? Seems like eslint ignores it anyway, so we might not need it but I don't see where it is configured :thinking:
