### ISSUE TITLE
Move Lint tests to GitHub Actions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2367]
## Feature Description

As part of our initiative to move our CI jobs to GitHub Actions, this issue is for moving our Lint tests. This corresponds to the job that runs on Travis by the same name.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new GitHub Actions workflow definition should be created for "Lint"
* The workflow should contain a job for running all the same linting checks that we run on Travis
* The workflow and job should fail under the same conditions as they do today when running on Travis
* All Lint checks, Lint-only variables ("SNIFF"), and related script steps should be removed from `.travis.yml`
* Previous runs of the workflow should be cancelled automatically by newer runs using our `cancel.yml` workflow by [adding the workflow filename of the workflow to the list provided to `workflow_id`](https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/.github/workflows/cancel.yml#L23) 
* The workflow should be a required check (set in repo settings)

## Implementation Brief

* Add a `lint.yml` file to our `.github/workflows/` folder.
* Inside that task, have two jobs:
  1. A job for using PHP 7.4, installing composer dependencies (including dev dependencies, then running `composer lint`.
  2. A job for running `npm run lint:js` followed by `npm run lint:css`.
* Remove all "SNIFF" related tasks in `.travis.yml`
* Merge #2537.
* Set the Repo Settings to require the new workflow named "Lint". (@felixarntz will need to handle this)

### Test Coverage

* None needed.

### Visual Regression Changes

* No changes.

## QA Brief

* The PR (#2537) should pass and should include "Code Linting" checks:
 
<img width="968" alt="Screenshot 2020-12-17 at 00 49 12" src="https://user-images.githubusercontent.com/90871/102423797-b160fb00-4001-11eb-8e94-b408463994f7.png">

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :warning: Overall it looks good, however workflow files contain the `ready_for_review` activity type which doesn't make sense there. @tofumatt can you delete it from both files?

**Comment by asvinb** [comment]
Checked the PHP and JS linting checks here:
https://github.com/google/site-kit-wp/pull/2537/checks

and both pass.

QA: ✅
