### ISSUE TITLE
Move PHP Tests to GitHub Actions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2368]
## Feature Description

As part of our initiative to move our CI jobs to GitHub Actions, this issue is for moving our PHP tests. This corresponds to the job that runs on Travis by the same name.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new GitHub Actions workflow definition should be created for each of the "PHP Tests" jobs we have currently defined in Travis
* The workflows should contain a job for running the same PHP Test jobs that we run on Travis
* The workflows and jobs should fail under the same conditions as they do today when running on Travis
* All PHP Tests, PHP-only variables, and related script steps should be removed from `.travis.yml`
* Previous runs of the workflow should be cancelled automatically by newer runs using our `cancel.yml` workflow by [adding the workflow filename of the workflow to the list provided to `workflow_id`](https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/.github/workflows/cancel.yml#L23) 
* The workflows should be a required check (set in repo settings)
	- Exception: The PHP Tests for WordPress nightly should not be required

## Implementation Brief

* Add a `php-tests.yml` file to our `.github/workflows/` folder.
* Following the format of the storybook tests, add our existing "PHP tests": `composer test` using the setup in `.travis.yml`
* Use the default `mysql` service provided by GitHub Actions using https://github.com/google/site-kit-wp/pull/2545/files#diff-8b304272438502fbcb449090052d2e707da4b71c84982948503c8f5f6532b0adR20-R24
* Use a "matrix" approach to run the tests on multiple versions of PHP.
* Merge #2545.
* Set the Repo Settings to require the new workflow named "PHP Tests" except those allowed to fail (@felixarntz will need to handle this):
  * All tests using `WordPress: Nightly` are allowed to fail

### Test Coverage

* None needed.

### Visual Regression Changes

* No changes.

## QA Brief

* The PR (#2545) should pass and use GitHub Actions to run the new check named "PHP Tests":

<img width="1061" alt="Screenshot 2020-12-17 at 18 38 08" src="https://user-images.githubusercontent.com/90871/102528852-0438c200-4097-11eb-9491-892e769de5fa.png">

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅  😆  Moving over to Execution for the last pieces @tofumatt

**Comment by felixarntz** [comment]
Moving back to Execution to address comments by @eugene-manuilov

**Comment by asvinb** [comment]
PHP tests passing here:
https://github.com/google/site-kit-wp/actions/runs/436524505
![image](https://user-images.githubusercontent.com/31818/102994359-5a46b300-4538-11eb-9b54-e781bf1fafb6.png)

QA: ✅
