### ISSUE TITLE
Won't let me select my existing GA code

### ISSUE THREAD

**Issue by TrustedSamurai** [google/site-kit-wp#237]
I've progressed through the Google SiteKit setup on my WordPress site.  When trying to select my GA code SiteMap say's it cannot find a code for my site.  When I select to CREATE AN ACCOUNT it sends me to GA.  When I enter the details for GA and finalise it I end up with two accounts in GA for the same web site.  And SiteMap still won't find either of them.

So I deleted the second one because I don't want a new GA code.  

It would be good if SiteMap let me enter my GA UA-xxxxxxx code.

Thank you.

John.

![Screenshot_1](https://user-images.githubusercontent.com/14268836/61168236-5e725100-a58e-11e9-92ea-cae9a1e27e4e.jpg)

**Comment by jamesozzie** [comment]
Hi John. Thanks for the input, hopefully we can assist. When you see the "Refetch My Account" notice there is a chance your verification process is incomplete. When you go back to the Site Kit dashboard do you see any other notice, such as "Issue accessing data"? 

With regards your request for allowing the manual input of Analytics account codes it's not something on the roadmap, with the API implementation providing a more secure connection method.
