### ISSUE TITLE
PHP Fatal Error Google Site Kit

### ISSUE THREAD

**Issue by jessmgamble** [google/site-kit-wp#2371]
## Bug Description

PHP Warning:  include(/staging/wp-content/plugins/google-site-kit/includes/vendor/composer/autoload_classmap.php): failed to open stream: No such file or directory in /staging/wp-content/plugins/google-site-kit/includes/loader.php on line 26

creates fatal error on site - I know very little, but how do I fix this?

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@jessmgamble Thanks for reaching out. Initial support requests can be submitted using the plugins [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/#new-post). 

If you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing details such as the below we'd be happy to assist:
- At what stage do you encounter this issue?
- Have you attempted reinstalling the plugin?

Let me know if you have any questions on the above.
