### ISSUE TITLE
Fix unreliable logic to update site URLs registered on authentication service

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2383]
#1857 made a significant improvement for supporting sites which have changed their URL, by detecting whether the URL has changed compared to the URL that the site had been set up with. Users will be automatically disconnected from those sites, and once they reconnect, an extra request will be made to the authentication service to update the URLs.

However, there are some scenarios where this logic can be bypassed, for example:
1. Site Kit is used on a staging site.
2. The site is then being launched to production on another URL, maintaining the database (so that site ID and site secret are still there).
3. However, the host provides automatic functionality that helps with the migration, replacing all old staging URLs with the new URL in the database, which unfortunately will also replace the URL that was intentionally stored as "original URL" by Site Kit.
4. The result is that Site Kit does not detect that the URL has changed because it also changed in the option to compare with.

We should make the flow for updating the authentication service URLs as needed more reliable, which is what this issue is about. We should keep the local URL detection itself as is, since disconnecting the user with an explanation is still a more seamless UX. This issue should solely focus on introducing the ability to change the authentication service URLs even if no local change has been detected. This can be accomplished by introducing new route functionality on the authentication service which allows a connected site to access its currently stored information.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new method `Google_Proxy::fetch_site_fields( Credentials $credentials )` should be introduced:
    * It should return early if there are no credentials.
    * It should issue a similar request as `Google_Proxy::sync_site_fields` does, however **only** passing the `site_id` and `site_secret` body parameters.
    * On success, it should `json_decode` the response as associative array and return it. On error, it should return the `WP_Error`.
* A new method `Google_Proxy::are_site_fields_synced( Credentials $credentials )` should be introduced:
    * It should call the above new "remote" `fetch_site_fields` method, as well as the existing "local" `get_site_fields` method.
    * It should return the error if `fetch_site_fields` returned an error.
    * It should return `true` if all keys in the local site fields are also in the remote site fields with the same values. Otherwise it should return `false`.
* The `Authentication::handle_sync_site_fields` method should be modified: The condition to call `Google_Proxy::sync_site_fields` should be modified to check if the above `Google_Proxy::are_site_fields_synced` returns `false`. In other words, every time a user connects, we should check the current site info from the proxy and update it if needed.
* Somewhat unrelated cleanup: We should no longer pass the `nonce` parameter in `Google_Proxy::sync_site_fields`.

**Note that the authentication service functionality here is not yet implemented. The code will only work once that's done (pending green light from @felixarntz).**

## Implementation Brief

* Add new methods `Google_Proxy::fetch_site_fields( Credentials $credentials )` and `Google_Proxy::are_site_fields_synced( Credentials $credentials )` that satisfy requirements defined in the AC;
* Update the `Authentication::handle_sync_site_fields` method to call `$this->google_proxy->sync_site_fields( ... )`  only if `$this->google_proxy->are_site_fields_synced( ... )` returns `FALSE`;
* Remove the `nonce` argument from the remote request body in the `Google_Proxy::sync_site_fields` method.

### Test Coverage

* Update existing tests when needed;
* Add phpunit tests to check `Google_Proxy::fetch_site_fields` and `Google_Proxy::are_site_fields_synced` methods. Use a hook for the `pre_http_request` filter to mock proxy server responses.

### Visual Regression Changes

* No visual changes are expected.

## QA Brief

1. Use the staging plugin so that you can test Site Kit against the staging version of the proxy. (Also remember to use a `@get10up.com` email address for testing the staging proxy.)
2. Use a site for which you can later easily change the URL (e.g. to a subdomain of the current domain or something like that).
3. Set up Site Kit (against the staging proxy).
4. Afterwards go to your site's database and do a full search-replace of the current site URL with the new site URL (make sure the domain is mapped so you can still use the site afterwards).
5. Go to your WordPress site which should now live on the old URL. Site Kit may show up as broken (it should at least if you wait for an hour, which will be the next time it attempts to refresh its data).
6. Regardless of whether it's broken or not, disconnect your account (**do not reset though**). You should then be able to go through the setup flow again, successfully. There should be no errors like `redirect_uri_mismatch` or something like that. (Basically Site Kit should automatically recognize the change in data and update the information on the proxy so that the flow still works afterwards.)

## Changelog entry

* Ensure that all URIs on the authentication service are automatically refreshed as necessary when connecting as a user to an already connected site, fixing issues where sites could get stuck after updating their URLs.

**Comment by felixarntz** [comment]
IB ✅

**Comment by benbowler** [comment]
Re: "..the authentication service functionality here is not yet implemented. The code will only work once that's done (pending green light from @felixarntz)..." Has this work been completed?

**Comment by benbowler** [comment]
From sprint planning session 23 November 2020 the authentication service functionality will be completed within the week so I will continue on this ticket.

**Comment by benbowler** [comment]
I've completed the work and am moving it to CR - however, this shouldn't be merged until @felixarntz has finished the linked authentication work.

**Comment by felixarntz** [comment]
@benbowler I've updated the QA Brief here. There's quite some details to consider in this particular case, so don't worry about not having put all that here. Just a general remark for future QA Briefs, unless the change is not user-testable, try to describe how the functionality that is affected by the change can be tested, rather than verifying that a certain piece of code exists. 👍

**Comment by tofumatt** [comment]
QA ✅
