### ISSUE TITLE
Make Reset button available in a consistent location (for "emergency")

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2384]
At the moment, Site Kit provides two places where the plugin can be reset:
* The setup screen, via a secondary action button
* The settings screen (Admin Settings tab)

It has proven multiple times to be a problem that both of these buttons can only be accessed conditionally. The settings button can only be accessed when connected (for obvious reasons), while the setup button can only be accessed when there is no other user that currently has credentials. While the latter should mostly show up when relevant, there is still potential that the plugin is stuck and needs to be reset while some users already (or rather still) have an access token, preventing the button from showing up in the setup screen.

We could make the button in the setup screen show up unconditionally (which is how it used to be), however that is not a good idea because then it becomes too "easy" to reset which may unexpectedly mess up the setup for other already connected users. Instead, we should add another Reset button in a "somewhat hidden/special" area which can always be accessed by an administrator.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Add a section in the Tools > Available Tools menu
* Heading: Reset Site Kit 
* Content: Resetting will disconnect all users and remove all Site Kit settings and data within WordPress. You and any other users who wish to use Site Kit will need to reconnect to restore access. 
* Link or button: Reset Site Kit 
* When clicked, Site Kit should be reset (similar to the existing Reset button in Site Kit).
* Only administrators (more specifically, users that can setup Site Kit) should be able to see this and reset.
* The implementation should be basic WordPress & PHP, not load/use React like we do usually.

## Implementation Brief

* Create a new `includes/Core/Admin/Available_Tools.php` file with a new class:
  * Use `Method_Proxy_Trait` trait to bind action/filter hooks with private methods;
  * Add a new private method `render_tool_box` that should do the following:
    * Do nothing if the current user can't set up Site Kit (`! current_user_can( Permissions::SETUP )`);
    * Output the following block using heading, content and button from the AC:
      ```html
      <div class="card">
          <h2 class="title">/* heading */</h2>
          <p>
              /* content */
              /* link styled as a button */
          </p>
      </div>
      ```
    * Use `admin_url( 'admin.php?action=googlesitekit_reset' )` to get reset URL and `wp_nonce_url` function to add a nonce argument to it.
  * Create a new public method `register` that adds a new hook for the `tool_box` action and calls the `render_tool_box` method (via using `get_method_proxy` from the aforementioned trait).
* Instantiate a new instance of the `Available_Tools` class and call its `register` method in the `init` hook of the `Plugin::register` method.
* Update `includes/Core/Util/Reset.php` to add a new hook for the `admin_action_googlesitekit_reset` action in the `register` method.
  * Verify nonce and check that the current user has capabilities to set up Site Kit before calling the `Reset::all` method.
  * After reset is done, redirect the user to the Site Kit dashboard page.

### Test Coverage

* N/A

### Visual Regression Changes

* A new box should be added to the Available Tools page that lets appropriate users reset Site Kit.

## QA Brief

* Reset tool is found under _Tools > Available Tools_ from the admin menu
* Ensure Site Kit is successfully reset after clicking the button
* Ensure client side storage is cleared on reset as well

## Changelog entry

* Include button to reset Site Kit under "Available Tools" in WordPress, as a way to reset the plugin data e.g. when currently not being connected.

**Comment by tofumatt** [comment]
IB ✅

It's not a super-discoverable reset, but I guess that's the point. Probably worth highlighting this option in support documents for users who get "stuck", as otherwise this would be tough to find, especially for a casual WordPress user not aware of those options.

**Comment by felixarntz** [comment]
This is good to go for 1.30.0, and better to include it sooner than later since it'll help with a bunch of support requests.

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

**Verified:**

- Reset tool is found under Tools > Available Tools from the admin menu

![image](https://user-images.githubusercontent.com/73545194/113856037-4c5d2b00-97d3-11eb-94fd-db7d1c22e17a.png)

- Site Kit is successfully reset after clicking the button

- The client side storage is cleared on reset. 

![image](https://user-images.githubusercontent.com/73545194/113856135-68f96300-97d3-11eb-8f92-9d31c21a2865.png)
