### ISSUE TITLE
Please do not show other managed sites

### ISSUE THREAD

**Issue by sergiodaia** [google/site-kit-wp#2386]
## Feature Description

Being a web agency, i'd like that my clients cannot possibly view the list of all the other clients as it happens right now here in the context menu voice 'Manage Sites' which redirects to:
https://sitekit.withgoogle.com/site-management/permissions

Please note that as the client logs in his site, he's not able to log with my analytics account but he's still able to see all my clients list

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@sergiodaia The "Manage Sites" feature is intended to list all the sites granted access to the Site Kit service with your Google account. 

The current recommendation and best practice is to create separate WordPress administrator accounts for your clients, who can then use these individual administrator logins to setup Site Kit (signing in with their own Google account). Providing you know their associated Google account you can provide them access to the individual services in advance of providing them access (Analytics, etc.).

I'll still make this as a feature request to remove the managed sites option, for the team to review.

**Comment by sergiodaia** [comment]
Thank you for the feedback. It theory it would work, but i'd like, if feasible, to hide that option for the clients and use a grand unique account for all the clients. It's more practical and requires less emails and interactions for the sitekit integration. Thanks nevertheless :)

Have a nice day
