### ISSUE TITLE
Getting an issue while login with google accounts

### ISSUE THREAD

**Issue by KritarthHandicrafts** [google/site-kit-wp#239]
Authorisation Error
Error 403: restricted_client
This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console.
Learn more
Request Details
response_type=code
access_type=offline
client_id=737538405799-huiq6df8na9l7lntm68s1k122ei3nuqh.apps.googleusercontent.com
redirect_uri=https://www.kritarthhandicrafts.com?oauth2callback=1
prompt=consent
display=page

**Comment by jamesozzie** [comment]
@KritarthHandicrafts Thanks for reporting. Do you mind trying the steps below so we can troubleshoot further?

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png)
3. Temporarily deactivate your other active WordPress plugins
4. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
5. Install Site Kit in a new incognito window (so Chrome extensions don't interfere and caching inactive)

Let me know if the above works. Very important to check in an incognito window also, AdBlockers can also sometimes cause interference during setup.

**Comment by jamesozzie** [comment]
@KritarthHandicrafts Did you have any luck setting up Site Kit by following the suggested steps?

**Comment by KritarthHandicrafts** [comment]
I followed steps many time but unfortunately I am unable to login in Google
site plugin In 2nd step

Paras Madan

**Comment by jamesozzie** [comment]
Are you a G Suite user? If so you might not have access to create a project using Google Cloud Platform. 

If you are not a G Suite use can you try create your credentials using the steps below:
- In the address bar of your window paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
- Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
- Press enter, with your cursor in the address bar (as if you are visiting that URL)
- Press the "GET OAUTH CREDENTIALS" button
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit

**Comment by jamesozzie** [comment]
@KritarthHandicrafts Did you have any success in setting up Site Kit after attempting the above steps?
