### ISSUE TITLE
Scaffold components for new All Traffic widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2392]
The main components for the new All Traffic widget (see [Figma file](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1198%3A271)) should be scaffolded, and state handling should be prepared.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new constant for the form name to use in the `core/forms` store for the new widget should be added to `assets/js/modules/analytics/datastore/constants.js`:
    * `FORM_ALL_TRAFFIC_WIDGET` (value `analyticsAllTrafficWidget`)
* A new `DashboardAllTrafficWidgetV2` component should be introduced in `assets/js/modules/analytics/components/dashboard/`, as a completely new version of the `DashboardAllTrafficWidget` component:
    * On the left column, it should render two new sub-components `TotalUserCount` and below `UserCountGraph` (see below).
    * On the right column it should render two new sub-components `DimensionTabs` and below `UserDimensionsPieChart` (see below).
    * At the bottom right, it should render a source link that points to the Analytics frontend. For now it should point to `getServiceReportURL( 'trafficsources-overview' )`.
    * See the [Figma file](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1198%3A271) for what it should look like eventually (_not_ all part of this issue though).
* The `TotalUserCount`, `UserCountGraph`, `DimensionTabs`, and `UserDimensionsPieChart` components should be scaffolded as empty components for now, in a new directory `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2`.
* The `TotalUserCount` and `UserCountGraph` components should support two optional props (via `prop-types`):
    * `dimensionName` should be an Analytics dimension name to filter results by (e.g. `ga:country`).
    * `dimensionValue` should be a value for that Analytics dimension name to filter results by (e.g. `India`).
    * Background: If both props are provided, the count/graph should display user counts only for the users to which that dimension filter applies. Otherwise, it should render user counts without a filter (i.e. all users entirely).
    * While we usually access values directly from the datastore (the widget will use `core/forms`), for these two components it makes sense to use props to decouple them from the widget's state.
* Necessary logic to pass the props to `TotalUserCount` and `UserCountGraph` should be added to `DashboardAllTrafficWidgetV2`:
    * It should select `getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionName' )` and `getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionValue' )` from the `core/forms` store and pass these as props to both components.
    * If `dimensionName` is not set, it should default to `ga:channelGrouping`.
* The `DashboardAllTrafficWidgetV2` component should be wrapped in the `whenActive` HOC similar to how `DashboardAllTrafficWidget` is.
* The `DashboardAllTrafficWidgetV2` component should be registered as `analyticsAllTrafficV2` widget, with the same properties and for the same widget areas that the existing `analyticsAllTraffic` widget is registered. Since widgets are still behind a feature flag anyway, it is okay to keep both the old and new All Traffic widget in place for now.
* A Storybook should be added for the overall `DashboardAllTrafficWidgetV2` component.

## Implementation Brief

* Add `export const FORM_ALL_TRAFFIC_WIDGET = 'analyticsAllTrafficWidget';` to `assets/js/modules/analytics/components/datastore/constants.js`
* Create `assets/js/modules/analytics/components/dashboard/Version2/DashboardAllTrafficWidgetV2.js` that renders a two-column layout with:
    * `<TotalUserCount />` and `<UserCountGraph />` in the left column.
    * `<DimensionTabs />` and `<UserDimensionsPieChart />` in the right column.
    * It should select, from the `'core/forms'` datastore, the following values to pass to `TotalUserCount` and `UserCountGraph`:
        * const dimensionName = `getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionName' ) || 'ga:channelGrouping';`
        * const dimensionValue = `getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionValue' );`
    * Should be exported wrapped in `whenActive` (see: https://github.com/google/site-kit-wp/blob/d6eb2f54af60db4bcdbc5d768983fb8012ccd175/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget.js#L137)
    * At the bottom right of the component, render a source link that points to the Analytics frontend. For now it should point to `getServiceReportURL( 'trafficsources-overview' )`.
* Scaffold components for the above sub-components, for now they can `return null;`:
    * `assets/js/modules/analytics/components/dashboard/Version2/TotalUserCount.js`
        * Should take `dimensionName` and `dimensionValue` props; see ACs.
    * `assets/js/modules/analytics/components/dashboard/Version2/UserCountGraph.js`
    * `assets/js/modules/analytics/components/dashboard/Version2/DimensionTabs.js`
    * `assets/js/modules/analytics/components/dashboard/Version2/UserDimensionsPieChart.js`
* Register the new V2 widget similar to the existing one: https://github.com/google/site-kit-wp/blob/d6eb2f54af60db4bcdbc5d768983fb8012ccd175/assets/js/modules/analytics/index.js#L55-L67. Its slug should be `analyticsAllTrafficV2`, with the same properties and for the same widget areas that the existing `analyticsAllTraffic` widget is registered.
* Add a storybook entries for the new components in `stories/module-analytics-components.stories.js` and for the new widget in `stories/module-analytics.stories.js`. Basic stories should suffice for now as no changes will be seen by changing props yet.

Reference image, for anyone without Figma access or wanting to reference the layout easily in this issue:

<img width="668" alt="Screenshot 2020-11-26 at 19 07 49" src="https://user-images.githubusercontent.com/90871/100387538-3cad2900-3020-11eb-9d8f-3254d0e7d33f.png">

### Test Coverage

* No useful Jest test coverage can be added yet as the component will contain little functionality, though scaffolding the test files could be useful.

### Visual Regression Changes

* No VRT changes should be seen yet and no VRT should be added as these components are still heavily in-flux.

## QA Brief

* A new (empty except source link) All Traffic widget should appear on the dashboard, using a Site Kit development build. It should not appear using a production build.
`All Traffic Widget V2` story must appear in the `Analytics Module/Components/Dashboard/All Traffic Widget V2`. 
The source link must go to `trafficsources-overview` report.

## Changelog entry

* Scaffold components for a new version of the Analytics All Traffic widget.

**Comment by tofumatt** [comment]
One note: the AC said to add the form constant to `assets/js/modules/analytics/components/datastore/constants.js`; I amended it to `assets/js/modules/analytics/datastore/constants.js` which is the actual file path 🙂 

Also, I think it would be nicer to organise the subcomponents in a `Version2` subfolder. I changed that slightly from the original ACs, but I think it's a bit clearer. We can use the `DashboardAllTrafficWidgetV2` folder name instead if you prefer.

**One question about:**

> * If `dimensionName` is not set, it should default to `ga:channelGrouping`.

From context, it seems like this should be the default value _passed_ to both `TotalUserCount` and `UserCountGraph`, not their `defaultProps`. That's how I wrote the IB, but it means that the `dimensionName` prop isn't really optional as stated in the ACs—we can make it optional but presumably without it the component would need to `return null`. If that intended, or should it be a default prop of the above components rather than the default assumed value to pass when `core/forms` returns nothing for those values?

**Comment by eugene-manuilov** [comment]
> One note: the AC said to add the form constant to `assets/js/modules/analytics/components/datastore/constants.js`; I amended it to `assets/js/modules/analytics/datastore/constants.js` which is the actual file path 

@tofumatt but you copied the wrong file path to your IB :smile::

> * Add `export const FORM_ALL_TRAFFIC_WIDGET = 'analyticsAllTrafficWidget';` to **`assets/js/modules/analytics/components/datastore/constants.js`**

**Comment by eugene-manuilov** [comment]
I also have a question: do we really need to store `dimensionName` and `dimensionValue` in the `core/forms` datastore? It seems like overkill to me because this information lives only in the scope of the widget itself and doesn't go out. So, I think it would be better to keep it in the widget state and pass it to underlying components.

**Comment by felixarntz** [comment]
@eugene-manuilov As mentioned earlier, let's for now rely on the `core/forms` store. Using a datastore allows better control about the state. Eventually, we should use a more appropriate store for such data, e.g. a `core/ui` store.

**Comment by felixarntz** [comment]
@tofumatt The IB looks good to me. There are a few pieces missing, but those are specified in detail already in the ACs, like the exact slug for registering the widget. One thing you're not mentioning in the IB at all is adding the source link which should also be done in this issue as defined in the ACs. That source link should be in the main component, it shouldn't be controlled by one of the scaffolded sub-components. Could you add a reference to that?

**Comment by tofumatt** [comment]
Sure thing! I too figured the ACs were clear enough on the slug as you say, but I also added the slug explicitly in the IB just for clarity 🙂

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
### QA ✅

Confirmed development build currently has an empty source widget.
![image](https://user-images.githubusercontent.com/57115907/102443751-55d04680-3fdc-11eb-8426-93a062e9ff73.png)

Checked the source link drives to the correct page:
![image](https://user-images.githubusercontent.com/57115907/102443789-6e406100-3fdc-11eb-99eb-85777adfcceb.png)

Confirmed non development build doesn't show this blank widget:
![image](https://user-images.githubusercontent.com/57115907/102443842-8d3ef300-3fdc-11eb-9476-5193de9f17ff.png)

Sending to approval.
