### ISSUE TITLE
User Input UI issues

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#2394]
## Bug Description

This bug issue will track the items discovered in https://github.com/google/site-kit-wp/issues/2040

## Issues:

**Question 3**
- User is able to select 1 answer and ungray the 'Next' button although the instructional copy says 'Choose only two (2) answers' suggesting you must choose 2 and only 2.

![image](https://user-images.githubusercontent.com/57115907/99589538-f8c37f80-29a0-11eb-8a2e-80e482f592bd.png)

**Question 4**
User is able to select 1 answer and ungray the 'Next' button although the instructional copy says 'Choose only three (3) answers' suggesting you must choose 3 and only 3.

![image](https://user-images.githubusercontent.com/57115907/99589573-0416ab00-29a1-11eb-9628-8598af81c041.png)

**Question 5**
Instructional copy stays within the keywords field after user enters a keyword. Should be removed after one item is entered

![image](https://user-images.githubusercontent.com/57115907/99589477-e34e5580-29a0-11eb-9ddb-4956e6adfbb9.png)

**Negative**
User is able to tab to next questions and fill out items that are grayed out (note below I was able to type in 'test' within the grayed out 'Other:' field

![image](https://user-images.githubusercontent.com/57115907/99589441-d92c5700-29a0-11eb-9869-41e75c7b5c29.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@cole10up would you please refresh this issue to contain only the parts which are still relevant? There have been a number of updates to U.I. since this issue was created. If they're all resolved, then let's close it out 👍

**Comment by aaemnnosttv** [comment]
@wpdarren is this something you could help look into? Let's find out if this is still relevant and if so, how much.

**Comment by wpdarren** [comment]
@aaemnnosttv sure, will have a look at this once we have the sprint out of the way.

**Comment by wpdarren** [comment]
@aaemnnosttv we can close this in my opinion.  On question 3 and 4 the text has changed to tell the user they can select up to 2 or 3 options. On question 5 is fixed and works as Cole requested. The negative issue in the ticket is fixed too with the recent accessibility improvements on the user input form.

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren !
