### ISSUE TITLE
Add more flexibility to the Notification component layout.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#2395]
## Feature Description

The `Notification` component relies on the `format` prop to render the appropriate class names for the cells within the grid. This is restrictive since in some cases we want to display the `Notification` differently. For e.g, having the content and the image being 50% wide each, which is not possible right now unless we overwrite the styles for the class names (for e.g `mdc-layout-grid__cell--span-6-tablet mdc-layout-grid__cell--span-8-desktop`). Overwriting the styles will definitely lead to maintenance issues later down the road.
Thus, let's look into how we can update the `Notification` component so that it's more flexible and does not rely on hard coded class names for the layout.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* The grid column sizing for the notification component should be flexible and controlled via props
    - The class names for the content area (the wrapper after `smallImage`) of the notification component should be dynamic.
    - The class names for the `.googlesitekit-publisher-win__image-large` parent element should be dynamic.

## Implementation Brief

**DRAFT**

- Using `assets/js/components/notifications/notification.js`
	- Add the `contentLayoutClassName` prop. Default value should be null. If it's null, then the `layout` [variable](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/notification.js#L161-L178) remains unchanged. If the `contentLayoutClassName` is not null, then `layout` variable is set to `contentLayoutClassName`
	- Add the `winImageLayoutClassName` prop. Default value should be null. Introduce a new variable `layoutImage` which should take the value of `winImageLayoutClassName`. If the latter is null, then the default value should be `mdc-layout-grid__cell--order-1-phone mdc-layout-grid__cell--order-2-tablet mdc-layout-grid__cell--span-2-tablet mdc-layout-grid__cell--span-4-desktop`
		```js
		layoutImage = 'mdc-layout-grid__cell--order-1-phone ' +
			'mdc-layout-grid__cell--order-2-tablet ' +
			'mdc-layout-grid__cell--span-2-tablet ' +
			'mdc-layout-grid__cell--span-4-desktop ';
		```
	- Replace the winImage div [class names](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/notification.js#L349-L354) by the following:
		```js
		<div className={ classnames(
			'mdc-layout-grid__cell',
			layoutImage,
		) } >
		```

### Test Coverage

* 

### Visual Regression Changes

No visual regressions should be present.

## QA Brief

No visual regressions. All components should remain unchanged.

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb Is this still worth doing? What's the pain point specifically from not having it? I guess I'm asking because all existing notifications are in place without this.

**Comment by aaemnnosttv** [comment]
@felixarntz As I recall, this issue was created due to limitations implementing a notification layout (maybe for User Input?). I think we may have been able to do it but it may have required extra styles where ideally we could simply pass some alternate props to the `Notification` to alter the layout.

Was there any more context to add here @asvinb ?

**Comment by aaemnnosttv** [comment]
Closing this one as the `BannerNotification` is already far too flexible which has made it overly complicated and needs to be broken into separate components.
