### ISSUE TITLE
Remove duplicate error message from SettingsModule

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2396]
## Bug Description

The `SettingsModule` component currently displays the error message from the `error` provided to it by its parent `SettingsModules` component. The `error` comes from the module promise created when settings are saved.

Since the error is now displayed in all settings components, this results in a duplicate 

![](https://user-images.githubusercontent.com/57115907/99614031-84530580-29cd-11eb-81d7-533582087ec2.png)

This also somewhat distorts the header of the settings module because it renders a red box on top of the normal output.

## Steps to reproduce

1. Trigger an error when submitting changes for module settings
    - Easiest to do currently by creating a new container with GTM using the same name for web and AMP containers (See #2274)
1. See the same error message displayed twice (module header and in settings component)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SettingsModule` component should not render its `props.error.message`, and surrounding elements for displaying it should be removed
* The error style (red border) should be preserved

## Implementation Brief

* Remove these lines https://github.com/google/site-kit-wp/blob/fedee50421b4b8bcdefc4ed47bb49bdda3b39794/assets/js/components/settings/settings-module.js#L259-L276

### Test Coverage

* No changes necessary

### Visual Regression Changes

* None expected (current stories using `SettingsModule` do not render an error state)

## QA Brief
* Create a new container with GTM using the same name for web and AMP containers on the SiteKit settings page.
* The error message: `Error: Returned an error response for your request.` should be displayed once.
* _Before_
![image](https://user-images.githubusercontent.com/31818/101775882-9118d400-3b09-11eb-8bcb-fbd3b7536f70.png)
* _Expected_:
![image](https://user-images.githubusercontent.com/31818/101775893-96761e80-3b09-11eb-8780-39e421fdeae9.png)

## Changelog entry

* Remove duplicate error message UI on top of module settings panel, since error messages are now displayed within the panel's main content already.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅

**Comment by wpdarren** [comment]
### QA update: ⚠️ Engineer to Confirm

@aaemnnosttv I'm not quite seeing the same behaviour.  The message `Error: Returned an Error response for your request` does not appear as you can see from the screenshot below.  Any ideas why this would be? 

![image](https://user-images.githubusercontent.com/73545194/102215345-8d73bb80-3f14-11eb-947f-70debd0b28a2.png)

**Comment by aaemnnosttv** [comment]
Hey @wpdarren – the error you're seeing in the interface there is more about form validation rather than an error from the request which is needed to trigger the component-wide error.

I can't tell just from your screenshot, but you should be able to trigger the error by setting **both** dropdowns to "Setup a new container" with the same new name for both (but doesn't exist in your containers yet) and then submitting the form. It's expected to not work as you have it there since you already have a container with the given name.

**Comment by wpdarren** [comment]
@aaemnnosttv perfect, thank you! 

### QA update: Pass ✅ 

**Verified:**

When Web and AMP containers are created with the same name the request error appears 
![image](https://user-images.githubusercontent.com/73545194/102219814-f1997e00-3f1a-11eb-97b3-82816e26ffa1.png)
