### ISSUE TITLE
Couldn't create project -  warning field [project_id] has issue [project_id contains invalid characters]

### ISSUE THREAD

**Issue by United982000** [google/site-kit-wp#24]
Can't create the OAUTH Credentials.. After clicking on the "get Credentials" Button i got the Error:
Couldn't create project -  warning field [project_id] has issue [project_id contains invalid characters]

![Bildschirmfoto 2019-06-21 um 10 48 28](https://user-images.githubusercontent.com/52067994/59910428-26a23e80-9412-11e9-82bb-8ff1e2b0accc.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by jamesozzie** [comment]
@United982000 Do you mind checking the following:

- Test installing Site Kit on another WordPress site you have
- From your [Google Developers console](https://console.developers.google.com) check that you didn't exceed your project quota. (IAM & admin > Quotas)

Can you also let me know if there are any special characters in your website name (ğ etc) and if you are using any Firewall or security plugin.

**Comment by United982000** [comment]
Hi there,
Yes, i have it installed on 2 other Domains on the same server with the same Configuration... Without Problems..
Quotas looks good.. Theres nothing close to the limits..

The Domain has no special characters and i deactivated Wordfence for testing..  But no change..  It also did not bother on the other 2 Projects.

**Comment by jamesozzie** [comment]
Thanks for checking. Do you mind also letting me know the following:
PHP Version:
Hosting OS:  
Browser:
Plugin Version:
WordPress version:
PHP Version: 

If possible include your site URL. I will mark it as a bug and revert back if more information is needed.

**Comment by United982000** [comment]
sure

PHP Version: 7.1
Hosting OS: cPanel
Browser: Chrome
Plugin Version: 1.0.0-beta.1
WordPress version: 5.2.2
Site: www.picoo.de

thx :)

**Comment by felixarntz** [comment]
@United982000 Can you share what is listed in the "Project Name" and "Application Name" on that page before opening the modal (with the error)?

**Comment by United982000** [comment]
Project Name: Site Kit
The title of your new Google Cloud Platform project.
Application Name: Site Kit on https://www.picoo.de
The name of the app asking for consent, as publicly displayed to authenticating users.

**Comment by jamesozzie** [comment]
@United982000 Do you mind [deleting](https://i.imgur.com/EoA1edo.png) that newly created project and also try installing (after [resetting](https://i.imgur.com/9U437Vq.png) via Site Kit.

Please also try to activate Site Kit again in [incognito](https://i.imgur.com/ALzgiHp.png) mode, to ensure a clear cache and no Ad Blocker or Chrome extensions are active.

**Comment by MohamadFtah** [comment]
I'am having the same issue
no quota limits

PHP Version: 7.3
Hosting OS: virtualmin 
Browser: Chrome, Opera
Plugin Version: 1.0.0-beta.1
WordPress version: 5.2.2

**Comment by jamesozzie** [comment]
@MohamadFtah Can you also please [delete](https://i.imgur.com/EoA1edo.png) that project from your Google Cloud Console, before resetting Site Kit and trying again?

Please share or send a screenshot of your "Project Name" and "Application" name during initial setup. The project name should reflect the title you have under "Settings > General" from your WordPress admin dashboard.

**Comment by VisionGlobal45** [comment]
Hi i have been facing the same problem what is there in that image.. How can i fix the problem please make a respond to this message.

**Comment by rehanoo** [comment]
I'm also having the same issue and unable to install the plugin.

**Comment by MohamadFtah** [comment]
I fixed it guys, just install the Credentials manually, when you click the get Credentials it will load a page with ur website and some other info like app name or program name ,  just ignore that and click the "site-kit" tab from top of the page and go from there it will asks you to choose a project, just select a new project and fill info with first page info. 
I might be missing a step cause I don't remember, but you'll figure it out.

**Comment by saalgu** [comment]
> I fixed it guys, just install the Credentials manually, when you click the get Credentials it will load a page with ur website and some other info like app name or program name , just ignore that and click the "site-kit" tab from top of the page and go from there it will asks you to choose a project, just select a new project and fill info with first page info.
> I might be missing a step cause I don't remember, but you'll figure it out.

i don't understand what you did to fix this issue
please clarify more

**Comment by rehanoo** [comment]
Ok here is how I was able to fix the following issue
[project_id] has issue [project_id contains invalid characters]

I created a new project in
https://console.cloud.google.com

For project ID I removed the default ID and created a new one using alphabets and numbers only. 
Ran the setup again on the website for Oauth and it worked.

But I'm still stuck on the second problem where it is not redirecting back tot he Google site kit plugin page.

Any idea's what to do?

**Comment by jamesozzie** [comment]
@rehanoo When you say it's not redirecting back to the Site Kit plugin page where is it directing you, back to your admin dashboard? Do you mind trying to repeat the process you already did with plugins deactivated and using an incognito window?

**Comment by rehanoo** [comment]
@jamesozzie it is redirect to my website homepage but with a long URL. Let me get back home and I'll send it to you. 

BTW I didn't deactivate any plugins or used incognito window. Just made the changes I mentioned above in my comment

**Comment by rehanoo** [comment]
https://247digiital.com/?oauth2callback=1&code=4%2FgwF8yE31WIy6bK3K2eQ8qP3SSQRdczCGe4xVfKc4b8bKfaovaLBVDAop0PwmjemYKWPOGuHs5KaZ7wbaEmQcVuI&scope=email%20profile%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification&authuser=0&session_state=6f1be694f9bb48689528f40e5706ccaea68265d5..8791&prompt=consent

**Comment by jamesozzie** [comment]
@rehanoo Thanks for the update. Do you mind repeating the process, but also perform the following:
- Deactivate all other plugins
- Activate an alternative theme (preferably a base WordPress theme)
- Re-start the setup using Chromes incognito mode. 

You can enable plugins and your preferred theme after, but please check and let me know. Other users have reported conflicts with some plugins, in additional to potential AdBlocker Chrome extensions.

**Comment by rehanoo** [comment]
Are you aware of the plugins?? Can you name any here please?? I don't have any ad blocker extensions installed either. 

I'll need some time to do what you are asking.

**Comment by jamesozzie** [comment]
@rehanoo The following have been reporting by others:
- ithemes security pro
- WP Super cache
- Google Analytics Dashboard
- Monster Insights
Do you have any of those installed, or caching/security plugins you can temporarily disable?

**Comment by rehanoo** [comment]
Yes I do have ithemes security (basic) and wp super cache. I'll disable them and try it again. 

But can I activate them again when it starts working?

**Comment by rehanoo** [comment]
Didn't work. It is still redirecting to the homepage with that long URL. Is there any manual way to do the second step?

**Comment by jamesozzie** [comment]
@rehanoo With your ithemes security can you uncheck the "Limits the number of characters that can be sent in the URL" option? This fixed the same problem for another user, #150

**Comment by alothaimeen** [comment]
I had the same issue and solve it by changing the language of wordpress to English US and changing 

Site Title and Tagline to English from settings.  You must do all these changes not one of them

**Comment by rehanoo** [comment]
> @rehanoo With your ithemes security can you uncheck the "Limits the number of characters that can be sent in the URL" option? This fixed the same problem for another user, #150

The option you are referring to is already disabled.

**Comment by hamedmoody** [comment]
This is because url that created in wordpress has extra space before project name:
![image](https://user-images.githubusercontent.com/9475089/61178813-2826e700-a60b-11e9-89ee-3e7c4625c634.png)

**Comment by DelicateGlint** [comment]
Thank you for the help. My hosting service didn't know what to do... your tip solved my problem. Tip for anyone who has a wordpress site where the characters in the under "site title" under General---> settings are not in latin characters (for me it was in Hebrew for example) Make sure your site title is in latin character. This solved the problem for me...

**Comment by jamesozzie** [comment]
Another workaround while this is being worked on is to manually generate your credentials. 

- Close the "Couldn't create project" window
- In the address bar of your window paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
- Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
- Press enter, with your cursor in the address bar (as if you are visiting that URL)
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit

**Comment by Tansch** [comment]
Attempt to manually generate the credentials:

Close the window "Project could not be created"
Paste this link in the address bar:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com

Replace yourwebsitecom and http://yourwebsite.com with your own site details.
also include https or http

https://www.hidendesign.at/google-site-kit-einrichten-wordpress/

**Comment by hzv4424** [comment]
> Another workaround while this is being worked on is to manually generate your credentials.
> 
> * Close the "Couldn't create project" window
> * In the address bar of your window paste the following in:
>   https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
> * Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
> * Press enter, with your cursor in the address bar (as if you are visiting that URL)
> * The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit

i have same issue 
this method solve problem

**Comment by jamesozzie** [comment]
@United982000 Were you able to create your own credentials using the suggested method above?

**Comment by hzv4424** [comment]
> @United982000 Were you able to create your own credentials using the suggested method above?

yes 
after changing url 
error not appeared.

**Comment by Adi010** [comment]
Hey Guys i had exactly the same issue with the google search consol setup.
What i did and what helped me to solve it.
In wordpress i clicked on Settings-General-Site Title= here i wrote the name of my website example: www.mywebsite.com (write your webiste name) and after that i refreshed the google browser and it worked immediately . Try it out may it work for you too it should. 
And please youse the chrome browser deactivate all addblockers and other plugins during the installation process.

**Comment by United982000** [comment]
> @United982000 Were you able to create your own credentials using the suggested method above?

Yes, worked..  Not all services can be connected but the most are doing well.. Thanks a lot ;)

**Comment by hfrid** [comment]
Agreed, that typo (extra whitespace) is what is causing the problem!
