### ISSUE TITLE
403 error during Analytics account creation 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2400]
## Bug Description

During Analytics account creating within Site Kit one user is unable to proceed. After they click on the "Create Account" button they are directed to a 403 error, with the below console error:

```
GET http://www.**domainhidden****/wp-admin/admin.php?page=googlesitekit-splash&googlesitekit_connect=1&nonce=b3c97833d3&redirect=http%3A%2F%2Fwww.**domainhidden****%2Fwp-admin%2Fadmin.php%3Fpage%3Dgooglesitekit-settings%23settings%2Fanalytics%2Fedit&additional_scopes%5B0%5D=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.provision 403 (Forbidden)
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-settings.08e988e1f939c10ec910.js:43
s @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
forEach.e.<computed> @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
n @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
_next @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Promise.then (async)
n @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
_next @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-settings.08e988e1f939c10ec910.js:43
s @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
forEach.e.<computed> @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
n @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
_next @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-settings.08e988e1f939c10ec910.js:43
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-settings.08e988e1f939c10ec910.js:43
Ui @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
ka @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
t.unstable_runWithPriority @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Nr @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Sj @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Lj @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
(anonymous) @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
t.unstable_runWithPriority @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Nr @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Br @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Hr @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
te @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
Nd @ /wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.e83b9bd244c78c4132c2.js:1
```

## Additional Context

 - Support Topic: https://wordpress.org/support/topic/403-on-creating-analytics-account/#post-13683434
 - Existing Analytics user
 - No issues connecting Analytics using existing account and property within the setup flow
 - SK version 1.20.0
- Same issue occurs when browsing from Chrome incognito window
 - SH info [provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=get10up.com&gxids=7628#response=ACYDBNiNfr8TENKtEuH6bFPM5bpAmMAGxwYDClvGEfIOoyO2cHkJHiny5LMZveJkdHPRGbo)
- Existing Analytics user

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Escalating to L1, unable to reproduce at support level with the same plugins, default configurations.

**Comment by wpdarren** [comment]
@jamesozzie @cole10up I haven't been able to recreate this on my test site.  I've tried to gain access to the SH info but the link in the ticket takes me to the form rather than data. Any chance I could have access, or, info on the users set up? Thanks.

**Comment by wpdarren** [comment]
**L1 update:**  I am unable to reproduce this on a few test sites with different setups.  Other than Elementor Pro, I was also able to set up a site as per the user Site Health info.

**Comment by jamesozzie** [comment]
Another user ran into this same issue:
https://wordpress.org/support/topic/error-403-google-analytics/#post-13702560

I'll try and test setup with a Google account with no existing Analytics accounts.

**Comment by jamesozzie** [comment]
I've tried using a Google account with no existing Analytics accounts. Unable to reproduce this same issue after manually creating an account and GA4 property. 

- Setup new Analytics account
- Followed standard setup experience and added a new property (GA4)
- Logged back into site and setup SK with this account
- No issues setting up a new account from within SK

**Comment by abdullah1908** [comment]
Tried different tricks by installing different optimization plugin to escalate the issue. Unbale to reproduce this issue in anyway.
cc: @jamesozzie

**Comment by bethanylang** [comment]
@jamesozzie With you and @abdullah1908  both unable to replicate, should this move to L2?

**Comment by bethanylang** [comment]
Thanks, @jamesozzie! Moving to L2.

**Comment by bethanylang** [comment]
Per discussion with @aaemnnosttv in Slack, this is likely related to the Mod_Security issues that we saw a few months ago and were fixed. We've had no recent reports, so closing this for now and we can reopen if needed.

**Comment by aaemnnosttv** [comment]
For reference, the issue this looks like (also shares a similar title) is https://github.com/google/site-kit-wp/issues/3532
