### ISSUE TITLE
Fix spelling errors

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2401]
## Bug Description

There are a few minor spelling errors in the code base, some user-facing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no spelling errors in the code base

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/2402

### Test Coverage

* N/A

### Visual Regression Changes

* None expected

## QA Brief

* Mostly insignificant changes to strings, some of which do not affect the resulting built plugin at all (tests/comments)
* Make sure that spelling changes to functions or any other functional pieces were updated in all instances

## Changelog entry

* Fix various spelling errors throughout the UI of the plugin.

**Comment by felixarntz** [comment]
IB ✅ 😆

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: all looks good.
