### ISSUE TITLE
Search Console dashboard infinite loading state when lacking permissions to property

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2403]
## Bug Description

Currently the Search Console dashboard will remain in an infinite loading state if the user does not have sufficient permissions to the property. This is visible in the batch data responses in the console.

<details>
<summary>batch response</summary>
	
```json
{
	"modules::search-console::searchanalytics::14bf456def2282c15006e28a71ed9b45": {
		"code": 403,
		"message": "User does not have sufficient permission for site 'https://example.com/'. See also: https://support.google.com/webmasters/answer/2451999.",
		"data": {
			"status": 403,
			"reason": "forbidden"
		}
	},
	"modules::search-console::searchanalytics::8d4c4f45a7123a18487d0b9fb7d2587c": {
		"code": 403,
		"message": "User does not have sufficient permission for site 'https://example.com/'. See also: https://support.google.com/webmasters/answer/2451999.",
		"data": {
			"status": 403,
			"reason": "forbidden"
		}
	}
}
```

</details>

![image](https://user-images.githubusercontent.com/1621608/99720805-f3585900-2ab6-11eb-8b20-aef54ac22ad4.png)

## Steps to reproduce

1. Set up Site Kit
1. Using the Developer Settings plugin, change your Custom Site URL to `https://example.com`
1. Navigate to the Search Console module dashboard page
1. See perpetual loading state

## Additional Context

Tested with 1.21 but confirmed the issue is present in 1.20 as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Search Console dashboard should not display an infinite loading state under any conditions, but specifically when the user does not have sufficient permissions to the property

## Implementation Brief

After digging into this a bit I found that the problem had to do with a bug in the way the legacy dataAPI handled multiple requests for the same request (cache-key). It's related to how when a batch request is made, the individual requests are grouped by request key (cache key), so that each unique data request is only made once to the server. When the response comes back, the handler needs to iterate over all request objects for the cache key for both error handling and resolving the response (sending data back to the caller for each request object).

I believe the problem was due to the line below where an error was raised due to attempted destructuring from `undefined` which stopped iteration and resulted in a rejected promise before data could be resolved (resulting in infinite loading).
https://github.com/google/site-kit-wp/blob/24e4cf02daffd797106b9566a6185229ae2e4983/assets/js/components/data/index.js#L207

* Merge #2600 – also cleans up the affected area a bit and makes it easier to understand what's going on with better variable names and comments without changing too much.

### Test Coverage

* No changes

### Visual Regression Changes

* N/A

## QA Brief

* Test loading the search console dashboard using both a URL that you have access to, and one that you don't (e.g. `https://www.example.com`)
* The SC dashboard should load normally in the happy path case and show an appropriate data error in the insufficient permissions case

## Changelog entry

* Fix bug in legacy API layer dealing with errors in a batch response that could result in infinite loading states on module pages.

**Comment by aaemnnosttv** [comment]
@felixarntz as mentioned in the IB, I think this one is more serious than just an infinite loading state in SC since it seems to be caused by the error handling in the legacy dataAPI:
![image](https://user-images.githubusercontent.com/1621608/104026607-d98de500-51ce-11eb-8d2b-7cfe9a9354d7.png)

I think this also means that we're not getting accurate event tracking right now for errors that are part of a batch request since this is essentially throwing an error right before `handleWPError` is called.

Escalating to a P0.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@aaemnnosttv @eclarke1 @fhollis Added this to Sprint 40 since it's a bug worth including and already has an almost finished PR.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- For a site that I do not have access to, the appropriate permission message appear.  The loading message did not run on an infinite loading state.  - [Screenshot](https://user-images.githubusercontent.com/73545194/104462193-33394980-55eb-11eb-81e7-b762bfaa9e27.png)
- For a site that I do have access to, the SC dashboard loaded normally.
