### ISSUE TITLE
Rename `WPComponent` arguments to use capitalized names

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2413]
Any arguments or props that require a `WPComponent` / `ComponentType` should be updated to have a capitalized name, to indicate the required argument type better (e.g. `SettingsEditComponent` instead of `settingsEditComponent`). This will eliminate the need to rename arguments before rendering them.

See https://github.com/google/site-kit-wp/issues/2381#issuecomment-730196523 for context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All arguments accepting `WPComponent`s should receive a capitalized name instead of starting with a lowercase letter.
    * In `registerModule` of `core/modules` store.
    * In `registerWidget` of `core/widgets` store.
* The documentation of `core/widgets` should be updated to reference `WPComponent` as required type instead of `React.Component`.
* The `registerWidget` function exposed on `googlesitekit.widgets` should have its documentation updated accordingly.
* All usage of these arguments should be updated to use the new names, i.e. renaming them to render them will no longer be necessary (since they'll already be capitalized).

## Implementation Brief

* Rename all the arguments of type `WPComponent` to be capitalized, with updated documentation in the following:
	* `registerModule` in `assets/js/googlesitekit/modules/datastore/modules.js`
	* `registerWidget` in `assets/js/googlesitekit/widgets/datastore/widgets.js`
* Use `WPComponent` instead of `React.Component` in `assets/js/googlesitekit/widgets/index.js`'s `registerWidget`. Also update the renamed arguments from the point above.
* Search for the usage of the arguments and rename them accordingly. Also remove any renaming done(capitalizing name when using) in the usage. 

	Example:
	In `assets/js/components/setup/setup-wrapper.js`, rename the usage to `SetupComponent` also update the destructure statement like
	```diff
	- const { setupComponent: SetupComponent } = module;
	+ const { SetupComponent } = module;
	```

### Test Coverage

* No additional tests required. Update tests if and when required to accommodate renamed arguments.

### Visual Regression Changes

* No visual changes.

## QA Brief

* The site kit module setup must look and work exactly as before
* Widgets must look the same. The stories for widgets must look the same as well.

## Changelog entry

* Rename arguments across various datastore actions requiring a `WPComponent` type to use capitalized names to better indicate a `WPComponent` (and not a `WPElement`) is required.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
