### ISSUE TITLE
Add plugin version to usage tracking data

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2416]
## Feature Description

All Site Kit users have the option to opt-in/out of anonymous usage tracking, which can be toggled at any time on the plugin settings page as well as during set up. In #1999 we extended this to include information to track API errors on the client which has already been useful in finding which errors users experience most. One valuable bit of information that is missing which we don't currently include in our event tracking is the plugin version itself. This is important to add as a dimension to allow us to segment data by release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `trackEvent` should include the plugin version as a [custom dimension](https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets) for the event (as `dimension4`).

## Implementation Brief

* Add `dimension4: global.GOOGLESITEKIT_VERSION || ''` to the `trackEvent` function in the `assets/js/util/tracking/createTrackEvent.js` file. The `global.GOOGLESITEKIT_VERSION` variable will be replaced with the actual plugin version once changes from #2334 are merged into the develop branch.

### Test Coverage

* Update existing javascript tests in the `assets/js/util/tracking/index.test.js` file to work correctly with the new dimension.

### Visual Regression Changes

* No visual changes are expected.

## QA Brief

* Set up site kit on your site;
* Install a tool that can debug GA requests (something like [this](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en));
* Opt-in for anonymous usage tracking.
* Go to the analytics settings and change profile, it should trigger a new event tracking.
* Check that the current plugin version is sent under the `dimension4` key in the GA tracking request.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv Good idea! I've amended the ACs to mention it should be under `dimension4` (which might be logical, but wanted to clarify since it ties in with how we set up dimensions in the GA property). I'll set that up on our end then.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
### QA ✅

Setup GA debugger and Tag Assistant, confirmed clicking anonymous tracking with both browser plugins enabled displayed the plugin version properly:
![image](https://user-images.githubusercontent.com/57115907/101721982-15ae1880-3a5e-11eb-8dd8-6dc0ca6ed49a.png)

Sending to Approval
