### ISSUE TITLE
Deprecate legacy functions with modern alternatives and prune dead code

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2418]
## Feature Description

There are a number of legacy functions in the codebase which have newer implementations which should be used instead for all new usage.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All legacy functions which are no longer used should be deleted
    - Imports/exports and tests do not count as usage. In this case, only references in source files/components should be considered
    - Please list these instances in the IB
* Any remaining legacy functions with a modern alternative (e.g. `getSiteKitAdminURL` - replaced by `select( CORE_SITE ).getAdminURL(...)`) should be annotated as `@deprecated n.e.x.t Use x instead.`
    - Please list these instances in the IB
    - Most (if not all) of these will likely be under `assets/js/util/index.js`

## Implementation Brief

Delete the following from `assets/js/util`:
* `refresh-authentication.js`
* `average-object-list-value.js`
* `cache-data.js`

Using `assets/js/util/index.js` delete the following functions:
* `removeURLFallBack`
* `removeURLParameter`
* `getDaysBetweenDates`
* `validateOptimizeID`

Delete the following from `assets/js/util/test`:
* `removeURLParameter.js`
* `getDaysBetweenDates.js`
* `validateOptimizeID.js`
* `getSiteKitAdminURL.js`
* `averageObjectListValue.js`

In the following components remove the import of `getSiteKitAdminURL` and replace calls to it with the store equivalent `useSelect( ( select ) => select( CORE_SITE ).getAdminURL( page , args ) )`.  In each case add imports for `useSelect` and `CORE_SITE`:
* `js/components/data-table`
* `js/components/legacy-setup/SetupUsingGCP`
* `js/components/setup/ModuleSetup`
* `js/modules/adsense/components/dashboard/LegacyAdsenseDashboardMainSummary`

In `js/util/index` remove the `getSiteKitAdminURL` function and its tests in `assets/js/util/test/getSiteKitAdminURL.js`

### Test Coverage

* run js tests and check that they pass.

### Visual Regression Changes

* n/a

## QA Brief

As per the IB, check:
* `util` files have been deleted
* functions have been removed for `index.js`
* associated tests have been deleted
* calls to `getSiteKitAdminURL` have been replaced

Also check js and VRT tests pass.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv Can you give some examples of which functions you're thinking about?

**Comment by aaemnnosttv** [comment]
@felixarntz off the top of my head: `refreshAuthentication`, `getReAuthURL`, `getSiteKitAdminURL`, and probably a few others in the top-level utils.

**Comment by aaemnnosttv** [comment]
We actually have a number of utils which are completely unused now, such as `toggleConfirmModuleSettings` and `removeURLParameter` too which would be good to clean up. I'll work on compiling a list for the ACs.

**Comment by tofumatt** [comment]
IB ✅ 

I wonder about _"annotate the getSiteKitAdminURL function with `@deprecated n.e.x.t Use selector getAdminURL instead.`"_ in the ACs though. The function won't be used anywhere in the codebase anymore, so why not remove it entirely?

Handing this over to @aaemnnosttv as he touched the ACs most recently.

@aaemnnosttv Any reason to keep that function around instead of removing it and its test file (`assets/js/util/test/getSiteKitAdminURL.js`)? It isn't used anyplace else anymore:

<img width="263" alt="Screenshot 2021-07-07 at 14 48 18" src="https://user-images.githubusercontent.com/90871/124770600-5f96a880-df32-11eb-899d-450a4c5fdeeb.png">

**Comment by tofumatt** [comment]
(The ACs mentioned to deprecate anything that was still being used, but in this case `getSiteKitAdminURL` is not, so I've amended the IB because it won't be used anywhere.)

IB ✅

**Comment by Hazlitte** [comment]
@tofumatt During execution I have discovered that `SetupUsingGCP` is a class component so the call `getSiteKitAdminURL` cannot be replaced with the `useSelect` hook.  Do you think it would be best to therefor leave the `geSiteKitAdminURL` function and tests for now and remove them when this component is refactored?

**Comment by tofumatt** [comment]
In that case let's use the [`withSelect` Higher-Order Component](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#withSelect) to get the data from the data store. It behaves similarly to `mapStateToProps` from Redux, and will let us get data from the data store and remove the legacy function.

Better to rely on that everywhere and remove the legacy component than to keep a lot of stuff around for that one file.

You can see an example of `withSelect` usage in our codebase here: https://github.com/google/site-kit-wp/blob/fea531210eeba8f7767526da6f7197e1a332f866/assets/js/components/higherorder/withData.js#L374-L380

**Comment by danielgent** [comment]
## QA :white_check_mark:

Confirming all code removed as per IB

Tests and VRTs all pass on `develop`
