### ISSUE TITLE
The response is not a valid JSON response

### ISSUE THREAD

**Issue by bburzycki** [google/site-kit-wp#242]
Trying to figure out this error message when on step one of initial setup. I get my code - and when i submit it it presents the error. Then in some cases when you exit the screen it will no longer show the error and bring up the SIGN INTO GOOGLE prompt.
![2019-07-13_085046](https://user-images.githubusercontent.com/52861870/61173702-b9cf1f80-a54b-11e9-9436-4f3c37bb206e.jpg)

Anyone else seeing this?

**Comment by jamesozzie** [comment]
@bburzycki Thanks for reporting. Do you mind trying the following, and using the resulting JSON response at the screen you highlighted.

1. In the browser address bar (preferably using an incognito window) visit the following:
https://developers.google.com/web/site-kit/?sitename=**yourwebsitecom**&siteurl=**http://yourwebsite.com**
2. Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
3. Press enter, with your cursor in the address bar (as if you are visiting that URL)
4. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit you highlighted. 

Please let me know if that works, allowing you to proceed with the setup.

**Comment by bburzycki** [comment]
Yeh this is honestly strange - it seems the services just do not confirm they are working until page reloads or days later they all of a sudden start working. An example of this is I went into the site today and all of a sudden analytics is working - thou slowly - and then I try to hook up PageSpeed - I need to enter the API key which i do then nothing it just sits there. I go away from the page and back to it and it then is connected.

Seems like some slightly strange buggy operation. 

Does anyone know the server side PHP version that needs to be running for Site Kit to work properly?

**Comment by jamesozzie** [comment]
@bburzycki Site Kit requires PHP 5.4 and upwards. I didn't encounter the same issue, if you want to try the below we can see if the issue arises again.

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png)
3. Temporarily deactivate your other active WordPress plugins
4. Install Site Kit in a new incognito window (so Chrome extensions/caching doesn't interfere with the setup process)

Let me know if the above works. AdBlockers and such browser extensions or software can also sometimes cause interference during setup, so be sure to check using an incognito window.

**Comment by jamesozzie** [comment]
@bburzycki Did you have any luck setting up Site Kit? If the above steps don't resolve your issue you can manually create your credentials.

**Comment by bburzycki** [comment]
I am waiting to move my server to the latest php to see if its resolves the issues

**Comment by Prospection** [comment]
Have the same issue
The response is not a valid JSON response
tried all above, got php 7.1.31, clean WP installation. No plugins.

**Comment by jamesozzie** [comment]
@Prospection Can you try and implement your own JSON response using the steps below:
- In the browser address bar (preferably using an incognito window) visit the following:
- https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com (Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http)
- Press enter, with your pointer in the address bar (as if you are visiting that URL)
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit you highlighted.
- Please let me know if that works, allowing you to proceed with the setup.

**Comment by Prospection** [comment]
I managed to fix it. Appeared that in WP health page I had a warning that rest api does not works good . After I fixed this Site Kit went fine.

Thank you

**Comment by jamesozzie** [comment]
@Prospection Good to know. If you are able to replicate the issue can you share the warning you encountered using the Site Health tab?

**Comment by Prospection** [comment]
I am unable to replicate error, but site health had a text something like:
**The REST API did not behave correctly problem with function context** or content.

**Comment by Prospection** [comment]
@jamesozzie hope it helps. Basically there was a problem with fresh WP install, unrelated to Site Kit
