### ISSUE TITLE
Add support for querying Analytics reports with dimension filters

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2421]
Currently it is not possible to use dimension filters when requesting an Analytics report. This should be implemented as it is needed for the new Analytics All Traffic widget (see #2420).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GET:report` datapoint in the Analytics class should be expanded to support an optional `dimensionFilters` argument:
    * The argument should be specifiable in a simple way, as a map of `dimensionName => dimensionValue` pairs. They should then be parsed into the necessary `Google_Service_AnalyticsReporting_DimensionFilter` (see also https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#DimensionFilter) structure required for the Google API request internally, with operator `EXACT`. All entries in the map should then be added as a new `Google_Service_AnalyticsReporting_DimensionFilterClause` (see also https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#DimensionFilterClause), with operator `AND`.
    * This dimension filter clause then needs to be combined with the existing dimension filter clause based on the `page` query parameter (see `Analytics::create_analytics_site_data_request`).
* The `getReport` selector of the `modules/analytics` datastore should be enhanced accordingly, so that the new `dimensionFilters` argument is supported. The argument should also be documented as one of the selector's `options`.

## Implementation Brief

* Update the `Google\Site_Kit\Modules\Analytics` class:
  * Check if the `$data['dimensionFilters']` isn't empty the handler for the `GET:report` endpoint and copy over its values into the appropriate `dimensionFilters` property of the `$request_args` variable. Please, make sure you to filter out dimensions that are not listed in the `$request_args['dimensions']` array;
  * Update the `create_analytics_site_data_request` method to populate dimension filters if `$args['dimensionFilters']` property isn't empty. See AC for additional details.
* Update the report datastore in the `assets/js/modules/analytics/datastore/report.js` file:
  * Add `dimensionFilters` validator to the `validateParams` function of the `fetchGetReportStore` store. It should check whether `dimensionFilters` is a map of dimension names and values and all dimension names are also defined in the `dimensions` option.
  * Update jsdoc for the `getReport` selector to list `dimensionFilters` argument of the options paramter.

### Test Coverage

* Adjust existing tests if any are failing.

### Visual Regression Changes

* Not expected.

## QA Brief

* Check the handler for the `GET:report` endpoint in the Analytics class and make sure it processes dimension filters correctly.

## Changelog entry

* Add support for a `dimensionFilters` argument to the Analytics `GET:report` REST datapoint in PHP and the `getReport` selector in JS.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅

**Comment by ivankruchkoff** [comment]
Resolved MR issues, back to you @felixarntz.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: All looks good. Dimension filters work as expected.
