### ISSUE TITLE
Implement `TotalUserCount` component for new All Traffic widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2423]
After scaffolding the `TotalUserCount` component in #2392, it should now actually be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `TotalUserCount` component for the Analytics `DashboardAllTrafficWidgetV2` should be fully implemented:
    * It should encompass the UI around the user count in the top left corner of the widget (see [Figma file](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1198%3A271)), including the small header "Users", the big number, the percentage change below and the date range beside the percentage change.
    * It should display data from an Analytics report for the metric `ga:users`, dates based on the current date range (including previous date range in order to compute the percentage change), and optionally the current entity URL, if there is one.
    * If both the `dimensionName` and `dimensionValue` props are present, it should also consider those for querying the report, as `dimensionFilters`.
    * If both `dimensionName` and `dimensionValue` are present, the "Users" header text should be changed to become almost like a breadcrumb like "Users > {dimensionValue}". The `dimensionName` should (at least for now) **not** be part of this header, because that context will be obvious in combination with the other components around this one. (This is potentially worth revisiting, but for now we should stick to the design as is.)
* The existing Storybook story for  `DashboardAllTrafficWidgetV2` should have its setup updated, to populate the registry with corresponding test report data, so that the UI rendered by `TotalUserCount` is visible there.

## Implementation Brief

* Edit the `TotalUserCount` component in the `assets/js/modules/analytics/components/dashboard/Version2/TotalUserCount.js` file:
  * Define two props for the component: `dimensionName` and `dimensionValue` which should be passed from the parent component (`DashboardAllTrafficWidgetV2`).
  * Add new `useSelect` hooks which do the following:
    * Pulls `startDate`/`endDate` and `compareStartDate`/`compareEndDate` dates from the `core/user` datastore using the `getDateRangeDates` selector with `{ compare: true }` args;
    * Pulls report data from the `module/analytics` datastore using the `getReport` selector with `ga:users` metrics, selected dimension name and value (if it's not empty), and `startDate`/`endDate` dates received from the aforementioned selector;
    * Pulls report data from the `module/analytics` datastore using the `getReport` selector with the same params but in this time using `compareStartDate`/`compareEndDate` dates as `startDate`/`endDate` dates.
  * Implement the required markup and styles to match the UI defined in the provided Figma file. See AC for more details.
    * Use the previous period data to calculate the change (use `changeToPercent` helper function).
* Update the storybook setup for the  `DashboardAllTrafficWidgetV2` component to properly configure the `TotalUserCount` component.

### Test Coverage

* Not needed

### Visual Regression Changes

* The new all traffic widget should start showing the total number of users in the left top corner.

## QA Brief

* Set up the plugin on your site;
* Activate and connect the Analytics module;
* Go to the dashboard page and make sure you see the new All Traffic widget;
* Make sure that the total number of users changes when you change the active tab in the widget;
* Make sure that the total number of users also changes when you change the current period.

## Changelog entry

* Implement `TotalUserCount` component for new Analytics All Traffic widget.

**Comment by tofumatt** [comment]
IB ✅

**Comment by felixarntz** [comment]
@eugene-manuilov This should be unblocked now that #2421 is merged.

**Comment by eugene-manuilov** [comment]
Thanks, @felixarntz! Just marked it as ready for review!

**Comment by wpdarren** [comment]
@eugene-manuilov a few observations:

1. Please could you clarify what you mean by:

`Make sure that the total number of users changes when you change the active tab in the widget;`

I am not seeing an active tab in the widget.  

2. There isn't any whitespace between the percentage character and `in the last 28 days`

![image](https://user-images.githubusercontent.com/73545194/104194396-3fdb6780-545c-11eb-8ba9-9c44b2a985ad.png)

3. In the figma file there is a breadcrumb above the number of users.  Has that changed from the designs?

**Comment by eugene-manuilov** [comment]
@wpdarren 

> Please could you clarify what you mean by:
>> Make sure that the total number of users changes when you change the active tab in the widget;

When you switch between channels, locations, and devices, the total number of users should reset to display the total number of users for the newly selected dimension.

> There isn't any whitespace between the percentage character and in the last 28 days

Looks like you see the old styles. Could you please clear your browser cache?

> In the figma file there is a breadcrumb above the number of users. Has that changed from the designs?

You need to select a slice in the pie chart to see a specific value. Once you do it, the slice label will be shown in the breadcrumbs.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- The new All Traffic widget appears in the dashboard 
- The total number of users changes when you change the active tab in the widget 
- The total number of users also changes when you change the current period 

https://user-images.githubusercontent.com/73545194/104201195-71f0c780-5464-11eb-9d60-e50690b007f8.mov
