### ISSUE TITLE
Implement `DimensionTabs` component for new All Traffic widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2424]
After scaffolding the `DimensionTabs` component in #2392, it should now actually be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The dimension tabs for the new All Traffic widget should be fully implemented and should encompass the tabs UI in the top right corner of the widget (see [Figma file](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1198%3A271)).
* Clicking on dimension tabs should change the active tab to the one which has been just clicked.

## Implementation Brief

* Implement the new `DimensionTabs` component:
   * It should encompass the tabs UI in the top right corner of the widget (see [Figma file](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1198%3A271)).
    * The component should select the current dimension from the `core/forms` store via `getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionName' )`, and the active tab should be based on that. If not set, the default should be `ga:channelGrouping`.
    * Selecting another tab should result in the above value being updated in the datastore via `setValues( FORM_ALL_TRAFFIC_WIDGET, { dimensionName: {selectedTab}, dimensionValue: '' } )`.
    * The tabs should be referring to the following `dimensionName` values:
        * Channels: `ga:channelGrouping`
        * Locations: `ga:country`
        * Devices: `ga:deviceCategory`

### Test Coverage

* Not needed

### Visual Regression Changes

* Dimension tabs should be added to the new All Traffic widget and they should match UI designed in the provided Figma file.

## QA Brief

* Set up the plugin on your site;
* Go to the dashboard page and make sure you see dimension tabs in the new All Traffic widget;
* Make sure when you click on a tab it becomes select and the previously selected tab loses its selection status.

## Changelog entry

* Implement main tabs UI for the new All Traffic widget.

**Comment by eugene-manuilov** [comment]
@felixarntz this is ready for IBR. I have extracted implementation details from the AC and adjusted it a little bit to define the expected outcome of this ticket more clearly. Hope it works for you.

**Comment by felixarntz** [comment]
@eugene-manuilov See my other comment regarding moving/updating ACs; IB ✅

**Comment by tofumatt** [comment]
Just noting that the QA brief left @asvinb and I a bit confused: the components rendered here are empty, but that first led us to think there was a bug. Turns out this was just scaffolding so it's okay, but outlining things like "empty components are expected" in the QA brief would make for faster QA in the future 🙂

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

The 3 tabs (Channels, Locations and Devices) appear within the All Traffic widget as per the figma file. As noted in Matthew's comment above, there is no data in the module and are empty. When you click on a tab it appears active and and the previously selected tab loses its selection status. - [Screenshot](https://user-images.githubusercontent.com/73545194/103542122-6b4bd880-4ed7-11eb-9b58-3b4bb1a8af8a.png)
