### ISSUE TITLE
Add interactivity to `UserDimensionsPieChart` component for new All Traffic widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2426]
The `UserDimensionsPieChart` component implemented via #2425 should be enhanced so that it is possible to click on a certain pie slice to make it the "current" slice (`dimensionValue`), which will result in the adjacent `TotalUserCount` and `UserCountGraph` components rendering information for only that `dimensionValue`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `UserDimensionsPieChart` component should be enhanced to support an "active" state for the different pie slices:
    * It should select `getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionValue' )` from `core/forms` to have awareness of what is the active `dimensionValue` (default none).
    * If there is an active `dimensionValue`, that slice should be highlighted like it is in the [Figma file](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1198%3A400). It should also be highlighted in the legend below.
    * Clicking on another slice should update the active slice to that one, via dispatching `setValues( FORM_ALL_TRAFFIC_WIDGET, { dimensionName, dimensionValue: newlySelectedValue } )` on `core/forms` - **except** when clicking on an aggregated "Others" entry, it should not be possible to select those.
    * Clicking the active slice should unselect it, via dispatching `setValues( FORM_ALL_TRAFFIC_WIDGET, { dimensionName, dimensionValue: '' } )` on `core/forms`.
* This functionality can be tested by looking at the `DashboardAllTrafficWidgetV2` as a whole: Clicking a pie slice should result in the total user count and the graph on the left to show data specific to that selected slice.
* If not already present, some slice-specific test data should be added to the Storybook story for `DashboardAllTrafficWidgetV2` so that the behavior is testable there.

## Implementation Brief

The main part of this ticket is going to be implemented in the PR for #2423. To complete this ticket, we need to implement the following task:

* Update the select event listener in the `UserDimensionsPieChart` component to reset the `dimensionValue` property when a slice is unselected (the `getSelected` method returns an empty array) or the `Others` slice is selected;

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Set up the plugin on your site;
* Activate and connect the Analytics module;
* Go to the dashboard page;
* Make sure you see the new All Traffic widget with user dimensions chart and total users number;
* By clicking on a single slice, an appropriate dimension value should be selected and the total number of users should reflect it to display the selected number;
* When the `Others` slice is selected or another slice is unselected, the dimension value should be reset and the total number of users should display general information.

## Changelog entry

* Add interactivity to new All Traffic widget so that selecting a pie chart slice contextually updates the count and graph displayed.

**Comment by eugene-manuilov** [comment]
@felixarntz this is ready for IBR but I am not sure that it is possible to implement the first point in the AC:

```
It should select getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionValue' ) from core/forms to have awareness of what is the active dimensionValue (default none).
```
Looks like we don't even need it because when we switch dimensions, the dimension value is reset and we always get the chart with nothing selected.

**Comment by felixarntz** [comment]
@eugene-manuilov Your IB is missing the main point of this issue which needs to be to manage the `dimensionValue` field for the widget via the `core/forms` store. Your PR #2532 does not cover that, so it needs to be covered here.

The reason we need to manage this in the store are the other components in `DashboardAllTrafficWidgetV2` outside of `UserDimensionsPieChart`, which should display different content based on the active pie slice. Please update the IB to add getting and setting `dimensionValue` to `UserDimensionsPieChart`.

**Comment by eugene-manuilov** [comment]
> Your PR #2532 does not cover that, so it needs to be covered here.

@felixarntz it's implemented in the branch for 2423 which doesn't have a PR yet. You can see my changes here: https://github.com/google/site-kit-wp/compare/feature/2425-user-dimensions-pie-chart...feature/2423-total-user-count#diff-ed3d73b94f10ea79867db833cc8ee305ffc13b3f87b1ae7f53ab483498135bb9R82

**Comment by felixarntz** [comment]
@eugene-manuilov Sorry, I confused the issue numbers there. IB ✅

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

**Verified:**

- The new All Traffic widget is displayed with user dimensions chart and total users number.
- When clicking on a single slice, the appropriate dimension value displays the total number of users. 

![image](https://user-images.githubusercontent.com/73545194/104451458-8788fd00-55dc-11eb-9aac-6eade1839986.png)
- When the Others slice is selected or another slice is unselected, the dimension value should be reset and the total number of users should display general information. 

![image](https://user-images.githubusercontent.com/73545194/104451522-a38c9e80-55dc-11eb-9dd8-d7ee1bde4977.png)

@eugene-manuilov based on the QAB, this has passed but I do have a few UX observations. 

1. When you select a single slice, and then change the date selection to any other period, i.e. 90 days.  The module reloads and the correct number of users is displayed for that slice, but the issue is that the slice is no longer selected.
2. Sometimes the number of users takes approx. 5-6 seconds to display, and the area where the data appears is blank. Could we have a loading icon appear, so that the user knows data will appear. 

Neither of these are big issues. Would you like me to create tickets for these observations?

**Comment by eugene-manuilov** [comment]
Thanks, @wpdarren! These are good points! I think, each worth a new ticket. Could you please create it?

**Comment by wpdarren** [comment]
@eugene-manuilov yes, have made a note to create these tickets when this sprint is compete.
