### ISSUE TITLE
Implement correct source link for new All Traffic widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2428]
#2392 scaffolded the `DashboardAllTrafficWidgetV2` with a source link appearing on the bottom right of the widget. This issue is about contextually adjusting this source link to point to the relevant location.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics source link in the `DashboardAllTrafficWidgetV2` should be updated to be contextual (always using `getServiceReportURL` selector):
    * The report type passed to the selector should be based on the `dimensionName` variable (already present in that component):
        * For `ga:channelGrouping`: `trafficsources-overview`
        * For `ga:country`: `visitors-geo`
        * For `ga:deviceCategory`: `visitors-mobile-overview`
        * Any other value (which is not supposed to happen) should also assume `trafficsources-overview`.
    * It should also take the current entity URL into account if there is a current entity (select from `core/site` store). If present, arguments need to be passed to `getServiceReportURL` like `{ 'explorer-table.plotKeys': '[]', '_r.drilldown': 'analytics.pagePath:' + href }`, where `href` is the path segment of the current entity URL, in order to filter results in the Analytics frontend by only that URL. See legacy `AnalyticsAdSenseDashboardWidgetTopPagesTable` component for a related code example.
* The same link URL should also be used for the current "Others" slice (if present) in the `UserDimensionsPieChart` (see #2425). This might require some coordination with that issue, depending on what gets done first.

## Implementation Brief

* Edit the `getServiceReportURL` selector in the `assets/js/modules/analytics/datastore/service.js` file:
  * Remove `joinPaths` import from the `path` module;
  * Rework `path` variable in the `getServiceReportURL` selector to use a string template with `escapeURI` tag function (from the `assets/js/util/escape-uri.js` file) instead of using `joinPaths` function. Please, make sure that if `argsSegment` is empty, no empty segment is added to the generated URL.
* Update the `DashboardAllTrafficWidgetV2` component:
  * Use an appropriate type based on the current `dimensionName` (see mapping in the AC) and the current entity information (see details in the AC) to get the correct source link using the `getServiceReportURL` selector;
  * Update the source link to use the new service report URL and pass it to the `UserDimensionsPieChart` component as the `sourceLink` prop.

### Test Coverage

* Adjust existing tests if any are broken due to current changes.

### Visual Regression Changes

* No visual changes are expected.

## QA Brief

* Set up the plugin on your site and connect the Analytics module;
* Go to the dashboard page and check the source link at the bottom and the "others" link in the user dimensions chart component. Those links should lead to appropriate locations based on the selected dimension and the current entity information.

## Changelog entry

* Implement dynamic source link in the new All Traffic widget.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> Rework `path` variable in the `getServiceReportURL` selector to use a string template with `escapeURI` tag function (from the `assets/js/util/escape-uri.js` file) instead of using `joinPaths` function

Why is that necessary? Is there something broken in the current behavior? I would think the only thing (if any) to adjust in `getServiceReportURL` itself would be to allow for the `argsSegment` to not be present (i.e. no args).

**Comment by eugene-manuilov** [comment]
@felixarntz, currently, we import `path` from node.js core which can be considered as a bad practice if there is a good alternative that doesn't rely on node.js. That's why I added that piece to the IB to update service URLs using string templates.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

**Verified:**

- Source link under 'Pages' section directs the user to the Page analytics
- Source link under 'Top Acquisition' section directs the user to the Acquisition Overview.
- The 'others' link in user dimensions points to the user page in analytics
- Dashboard: source link under 'All Traffic' points to the Acquisition Overview.
- Dashboard: source link under 'Unique Visitors from Search' points to the Audience Overview
- Dashboard: source link under 'Most popular content' points to Page analytics.

**Comment by wpdarren** [comment]
@cole10up I have assigned this back to QA because it's related to https://github.com/google/site-kit-wp/issues/2424 and I misunderstood the QA brief. I think this needs to be QA'd after 2424.

**Comment by wpdarren** [comment]
@eugene-manuilov I'd like some clarificcation on the QA brief please. 

`Go to the dashboard page and check the source link at the bottom and the "others" link in the user dimensions chart component. `

I am seeing the source link in the dashboard page within the All Traffic widget points to Acquisition Overview within Google Analytics.  Where else should I be looking? Please could you direct me to the The user dimensions chart?  I'm not seeing this on the new module.

**Comment by eugene-manuilov** [comment]
@wpdarren the user dimensions chart will is being implemented in #2425 and we will need to QA it there. For this ticket, it's okay to test just the source link at the bottom of the widget.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- the source link in the dashboard page within the new All Traffic widget points to Acquisition Overview within Google Analytics.
