### ISSUE TITLE
Use `! hasFinishedResolution` instead of `isResolving` to indicate loading state

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2436]
## Bug Description

Noticed before as a potential weakness, the use of the meta selector `isResolving( selector, args )` to indicate loading state is problematic, as it will return `false` for the brief moment that the selector has not _started_ resolving yet, which is not accurate. In fact, it can lead to unexpected behavior and JavaScript bugs as noticed in https://github.com/google/site-kit-wp/issues/2243#issuecomment-733885140.

All code (which is exclusively widgets now) should be updated to use `! hasFinishedResolution( selector, args )` instead, which will return `true` in case the selector hasn't started resolving, which is what we actually want here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All (refactored) widgets should be updated to use `! hasFinishedResolution` instead of `isResolving`.
* Effectively, all usages of `isResolving` in the codebase should be replaced with this check (with widgets right now being the only usage of it).
* The PageSpeed Insights widget (`DashboardPageSpeed`) uses the custom selector `isFetchingGetReport` instead, which should also be replaced with using `! hasFinishedResolution` for the `getReport` selector, since that is more accurate here as well.

## Implementation Brief

* Update all widgets to use `! store.hasFinishedResolution` instead of `store.isResolving` when determining `loading` state.
* Update the `DashboardPageSpeed` widget to use `hasFinishedResolution` selectors instead of `isFetchingGetReport`.

### Test Coverage

* Update existing tests if any is failing

### Visual Regression Changes

* Widgets should stop showing empty states before loading state.

## QA Brief

* Set up site kit on your site;
* Go to the dashboard page and make sure that all new widgets don't show empty states before loading data.

## Changelog entry

* Fix race condition where widgets could run into an error when their necessary datastore selector had not started resolving yet.

**Comment by eugene-manuilov** [comment]
@felixarntz @tofumatt @aaemnnosttv I came across this issue when I worked on a fix for setState errors and have already converted all widgets to use `hasFinishedResolution` instead of `isResolving` :man_shrugging:. Here is a link to my PR that contains these (and other) changes: https://github.com/google/site-kit-wp/pull/2412. Let me know if you want me to extract changes related only to this ticket into a separate PR.

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov – would you please separate out only the module-specific changes related to this into a new PR?Then maybe the IB here can simply be "Merge #{new PR}". This will make this issue a bit quicker and make the CR easier on the other issue as well 😄

**Comment by eugene-manuilov** [comment]
@aaemnnosttv IB is added. Do you mind to review it?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov while there are many changes in that PR which would be good to do, the PR contains much more than is necessary to resolve this issue. Let's keep it to only changing the existing logic for `loading` unless otherwise necessary. Other refactoring can go into a follow-up issue where we can review it as more of a 1-1 changeset.

E.g. all the changes should be similar to this:
```diff
diff --git a/assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js b/assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js
index a8475b751..7a58f8714 100644
--- a/assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js
+++ b/assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js
@@ -72,7 +72,7 @@ function DashboardClicksWidget() {
 		return {
 			data: store.getReport( args ),
 			error: store.getErrorForSelector( 'getReport', [ args ] ),
-			loading: store.isResolving( 'getReport', [ args ] ),
+			loading: ! store.hasFinishedResolution( 'getReport', [ args ] ),
 			serviceURL: store.getServiceURL( { path: '/performance/search-analytics', query: serviceBaseURLArgs } ),
 		};
 	} );
```

If you'd prefer to update the IB without an accompanying PR for now, that's fine too.

**Comment by eugene-manuilov** [comment]
IB is updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

- The dashboard module does not show empty states before loading data.  Created a screencast to show behaviour. [screencast](https://user-images.githubusercontent.com/73545194/100748495-584c7100-341e-11eb-90de-0ecc135169b5.gif)
