### ISSUE TITLE
Alias domains reset Site Kit activation

### ISSUE THREAD

**Issue by archon810** [google/site-kit-wp#2437]
## Bug Description

Our sites are hosted on multiple servers, all accessible as www.SITE.com. But each server is also accessible with its direct alias, for example www1.SITE.com, www2.SITE.com, etc.

After updating from Site Kit 1.10 to 1.21, I found that if Site Kit was active on www and I went to www1.SITE.com, there was a message from Site Kit:

> Looks like the URL of your site has changed. In order to continue using Site Kit, you’ll need to reconnect, so that your plugin settings are updated with the new URL. Reconnect

At some point later (not right away though), I found that Site Kit was disconnected on www.SITE.com and had to relogin to my Google account to reactivate it:

> Reconnect Site Kit
> Looks like the URL of your site has changed. In order to continue using Site Kit, you'll need to reconnect, so that your plugin settings are updated with the new URL.

The fact that it doesn't disconnect right away is especially tricky because you may not notice for a while, though at least it seems like the Analytics tags continued serving in this state. Regardless, this behavior is not ideal, and this is the only plugin we have installed that does this.

## Steps to reproduce

1. See above for steps.

## Screenshots

![image](https://user-images.githubusercontent.com/469543/100289898-d5fc1280-2f2e-11eb-85dd-bffab863951d.png)

![image](https://user-images.githubusercontent.com/469543/100289882-ced50480-2f2e-11eb-9930-40a470e5aac1.png)

## Additional Context

 - PHP Version: 7.4
 - OS: OpenSUSE 15.2
 - Browser Chrome
 - Plugin Version 1.21.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by archon810** [comment]
Another variation that could happen instead of getting logged out straight up:
![image](https://user-images.githubusercontent.com/469543/101550895-f2537280-3964-11eb-944b-f46a990a172f.png)

**Comment by archon810** [comment]
Confirmed issue is still present in 1.22.0.

**Comment by jamesozzie** [comment]
@archon810 Thanks for reaching out and providing details on this. What's seems to be occurring here is the admin URLs used when accessing your site (between your differing domain alias's) not matching the URL registered on the Site Kit service. 

Similar issues were raised by users or common language plugins, once a logged in users switches languages that results in a URL structure change. We're working on making changes to the way Site Kit checks users admin URL, with the fix as per #2277 applying to your site once released. Feel free to subscribe to that issue for further updates.

**Comment by archon810** [comment]
@jamesozzie Was this supposed to be resolved in the latest update since #2383 and #2277 are both done now? I installed 1.24.0 but the issue persists.

**Comment by jamesozzie** [comment]
@archon810 Thanks for checking up on this. I'll discuss this with the team and try to find out more. I'll update you here as soon as I have more information. In the meantime is it possible for you to use the same domain alias each time while logging into your admin panel?

**Comment by adamsilverstein** [comment]
@archon810 thanks for raising this issue.

@jamesozzie is correct: because you access wp-admin from different URLs, Site Kit is getting confused and things your site domain has changed. When this happens you are disconnected and need to go thru the setup flow again. 

To fix this issue, you can use a filter we provide in Site Kit to set your canonical domain: `googlesitekit_canonical_home_url`. Site Kit will always use the domain returned from this filter.

You can add the filter to your theme, or this mini plugin will lock your domain from Site Kit's perspective to what you have set in Settings->Site Address: https://gist.github.com/adamsilverstein/199f3a4cfe8b4ccc881713a7ece05438

Please give that a try and let us know if this resolves your issues.

**Comment by archon810** [comment]
This worked, thank you. I wonder if there's a better, more automated solution, but at least we have this workaround now.

**Comment by adamsilverstein** [comment]
> This worked, thank you. I wonder if there's a better, more automated solution, but at least we have this workaround now.

@archon810 Excellent! Finding a solution that works for everyone is challenging due to the diverse ways users run WordPress. The filter is the best way we have found so far.

**Comment by adamsilverstein** [comment]
Closing as resolved.
