### ISSUE TITLE
Webpack bundles running in separate runtimes results in duplicate module initialization

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2444]
## Bug Description

Currently Site Kit loads multiple webpack entry bundles on a single page much like WordPress core does, with the main difference that it does not create one entry for each library/module which is also assigned to a global. While we mirror much of the approach used by Gutenberg, we bundle our own dependencies separately to provide a more stable and predictable result.

Because we run separate entries, we've encountered problems in the past such as React hook errors where a separate instance of React (or some internal dependency) was not referencing the same instance. As a workaround, we created shims for modules which were sensitive to this, which proxied the access through a ["private" global](https://www.merriam-webster.com/dictionary/oxymoron) in order to preserve a single shared instance across all of our entries, while using the package as normal (e.g. `import { Fragment } from '@wordpress/element'`).

It turns out the reason for this is due to a specific setting in our Webpack configuration for [`optimization.runtimeChunk`](https://v4.webpack.js.org/configuration/optimization/#optimizationruntimechunk) which is currently set to `false`.

From the docs:

> Default is `false`: each entry chunk embeds runtime.
>
> Imported modules are initialized for each runtime chunk separately, so if you include multiple entry points on a page, beware of this behavior. You will probably want to set it to single or use another configuration that allows you to only have one runtime instance.

As stated, setting to `false` causes modules to be initialized separately for each entry rather than only once for use in a _shared runtime_, which is what we want.

> The value 'single' instead creates a runtime file to be shared for all generated chunks.

`single` is just an alias/shortcut for a more verbose syntax which lets you specific the name you want but this is what we want.

Issues like #2247 are also likely caused by this. This is also like the cause of recent issues such as https://github.com/google/site-kit-wp/issues/2145.

## Steps to reproduce

> Requires code changes to show based on current `develop`

1. Delete module shim and webpack handling for `@wordpress/element` and `__non-shim`
1. Build
1. Load the splash page
1. See React hook error  
![image](https://user-images.githubusercontent.com/1621608/100423899-78360a80-3095-11eb-8739-d79c55af8cae.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Webpack entries for "Module Entry Points" should use a shared runtime
* Module shims, webpack aliases and any other related configuration to enable these workarounds should be removed for:
    - `@wordpress/element`
    - `@wordpress/hooks`
    - `react`

## Implementation Brief

* Merge #2445

### Test Coverage

* Remove tests for removed shims

### Visual Regression Changes

* N/A

## QA Brief

* Everything should continue to work as before as this is mostly a build-level change.

## Changelog entry

* Fix various low-level technical bugs due to duplicate module initialization by relying on a single reused Webpack runtime across entrypoints.

**Comment by tofumatt** [comment]
IB ✅

We talked about this in Slack yesterday and reading through the docs this all sounds great. Kicking myself for not finding this one before, great work 🎉

**Comment by eugene-manuilov** [comment]
IB ✅, however, the implementation in the associated PR introduces a new regression which I mentioned in a comment there.

**Comment by aaemnnosttv** [comment]
Thanks guys, let's address the rest in code review 👍

**Comment by asvinb** [comment]
App working as usual. No errors in the console or in the app.

QA ✅
