### ISSUE TITLE
Insufficient permissions in Analytics - Suddenly appearing on all connected sites

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2450]
## Bug Description

After updating to the latest version of the plugin a [user in the support forums](https://wordpress.org/support/topic/insufficient-permissions-in-analytics-bug/#post-13717035) is encountering the notice below on all connected sites:
“Insufficient permissions in Analytics
_Your Google account does not have sufficient permissions for this Analytics account, so you won’t be able to see stats from it on the Site Kit dashboard. This service was originally connected by the administrator ****“_ 

The is despite the same WordPress administrator account being the same logged in user mentioned in the notice above. This started occurring approximately 1 week ago, possibly around the time of the 1.21.0 release. 

The WordPress administrator user has no issues previously, and has multiple sites connected to Site Kit (all using the same Analytics account, with different properties). 

Various troubleshooting steps performed, including the below:
- The user confirmed full permissions
- Reviewed plugins and connected users in one example sites Site Health info
- Account not marked as "Trashed" in Analytics
- Reset Site Kit
- Disconnecting associated account
- Adding another Google account to the connected Analytics account, then logging into as a new admin user and connecting Site Kit with that Google account

## Additional Context

 - SH info provided for one impacted site
 - Plugin version 1.21.0
- ManageWP and some optimisation plugins active

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Some useful videos provided within the [support topic](https://wordpress.org/support/topic/insufficient-permissions-in-analytics-bug/#post-13717035). 

The user has access to the referenced property within the [latest video](https://www.loom.com/share/8a898b09821e4df3a9b9b1c249e35d9f), with the user confirming all properties are part of the same account. 

Awaiting further troubleshooting results with user, while escalating to L1 for further review.

**Comment by wpdarren** [comment]
### Escalation L1 update:

- Set up 3 sites, activated v1.20.0 Site Kit on each one and used the same Google account but different properties for GA. 
- Logged into GA and could see the three properties as expected. 
- Updated Site Kit to v1.21.0 and observed no messages re permissions in GA module or dashboard. 
- Reset Site Kit on all 3 sites, and reconnected them again with the same Google account and appropriate GA properties. All connected fine, no permission issues. 

@jamesozzie  after watching the video a few times, I spotted that the user appears to have an Analytics plugin activated. Could this be the cause of this issue, a conflict?  [Screenshot](https://user-images.githubusercontent.com/73545194/100879883-f9066380-34e6-11eb-9bd3-e50f95585d17.png)

**Comment by jamesozzie** [comment]
@wpdarren Thanks for checking. Awaiting feedback from the user in relation to removing the snippet via another plugin, I'll let you know as soon as I have an update.

**Comment by jamesozzie** [comment]
The user was able to resolve this issue, with the site in question having additional plugins with Analytics features. Closing as the user was able to resolve on other sites .

**Comment by Spacena** [comment]
I am facing the same issue still in 2022. The problem is across all websites set up with Site Kit and GA4. I think the problem is Site Kit can't connect well with GA4; for earlier it worked well with Universal Google Analytics.

**Comment by wpdarren** [comment]
@Spacena thanks for getting in touch. I suspect that this is because Site Kit only supports the display of UA data and not yet GA4 within it’s dashboards. You can find out more information on this in our [Using Google Analytics 4 (GA4) guide](https://sitekit.withgoogle.com/documentation/using-site-kit/ga4/). Here you will also find our [GitHub issue](https://github.com/google/site-kit-wp/issues/2220) for further GA4 work so please feel free to follow this for future updates on GA4 within Site Kit.

**Comment by techtwists** [comment]
I have fixed my problem through deleting manually creating property and reconnect again analytics account in WordPress dashboard . this process will create analytics property automatically .
