### ISSUE TITLE
Make feature flags dynamic

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2452]
## Feature Description

Currently our feature flags are defined in `webpack.feature-flags.config.js` (soon to be `feature-flags.json`) which is provided as `featureFlags` to all modules in JS via Webpack. Feature flags allow us to using avoid long-running feature branches and merge code before it is ready for production use. Originally, the thought was that non-production feature code would be tree-shaken out for releases but that isn't really the case and is actually more of a feature than a bug as it allows translations to be prepared before the features are enabled in a subsequent release.

One major drawback of the current approach however is that is problematic to test these features, particularly in E2E. The build we use for E2E uses a normal production build, with added utilities for use in the tests. This means that only production features will be enabled (i.e. no flag-specific features).

This is also a bit of a problem in Storybook where `featureFlags` is treated as a global that persists across stories. This means that enabling a feature in one story will cause it to be enabled in another which may be specific to the current production case. This can lead to unexpected results when viewing Storybook and switching between stories. VRT is more/less unaffected by this since Backstop loads the story iframe directly for each case rather than switching via the UI.

Given the changes coming in #2316, it makes sense to build on this to make the server the source of truth when it comes to available/enabled features.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `feature-flags.json` should be restructured into a single-level key-value structure, removing the `enabled` key entirely
_E.g. `userInput.enabled` would be `userInput` – `widgets.dashboard` may remain, but as a single string key_
* The `FeatureFlagsPlugin` should be removed from the `webpack.config.js`
* `webpack-feature-flags-plugin` dependency should be removed
* `featureFlags` should be removed as an allowed global from the ESLint config and all usage should be updated to consume the value via the `useFeature` hook

### PHP

* Feature activation should be provided from the server as part `_googlesitekitBaseData` as `enabledFeatures` as a list of feature keys/paths that are enabled
* The `FeatureFlags::enabled` method should be made filterable by passing the result through a new `googlesitekit_is_feature_enabled` filter
	- the filterable value is the boolean value to be returned by the method
	- the filter should pass the `FeatureFlags::$mode` as the second parameter to the filter

### E2E

* There should be a new `enableFeature( feature )` E2E utility function to enable a feature by its feature "path" (e.g. `userInput` or `widgets.dashboard`)
* There should be a new `disableFeature( feature )` E2E utility function to disable a feature by its feature "path"
* All features should be disabled by default in E2E until explicitly enabled
* Enabled features should be reset after each test case (perhaps any time Site Kit is reset) so that no features are enabled again

### JS

* There should be a new internal module in `assets/js/features/index.js` which exports `enabledFeatures` which returns a copy of `global._googlesitekitBaseData.enabledFeatures` or an empty array if none present
_This should be the only reference to the global object in JS_
* No entry point or asset instance should be created for this, it is for internal importing only

### React

* There should be a new React context created in `assets/js/components/FeaturesProvider/context.js` using `enabledFeatures` as the default value to `React.createContext`
* The above `Context.Provider` component should be the default export from `assets/js/components/FeaturesProvider/index.js`
	* See [RegistryProvider](https://github.com/WordPress/gutenberg/blob/77be77c60fc8bedc9c930d3c89a783a1b0f4be2f/packages/data/src/components/registry-provider/index.js) as an example
* There should be a new `useFeature( path ) : bool` custom hook in `assets/js/components/hooks/` which checks if the given feature is in the list of enabled features via context
	- All components that reference `featureFlags.{ some path }.enabled` should be updated to use this hook instead
		```js
		const userInputEnabled = useFeature( 'userInput' );
		```
* The `Root` component should include `FeaturesProvider` as the highest wrapping child of its `ErrorHandler`
* Feature-specific stories should be updated to be wrapped with a `FeaturesProvider` with the list of enabled features as its `value`
	- The existing `enableFeature` and `disableFeature` utilities should be removed
* All features should be disabled by default in Storybook unless enabled explicitly with a `FeaturesProvider`

## Implementation Brief

* Edit `/feature-flags.json` into a single-level key-value structure, removing the `enabled` key entirely.
* Edit `webpack.config.js` to remove `FeatureFlagsPlugin`.
* Remove `webpack-feature-flags-plugin` dependency from `package.json`.
* Edit `.eslintrc.json` to remove `featureFlags` references.
* Add `enabledFeatures` key to the array returned by the `get_inline_data` method in `/includes/Core/Assets/Assets.php`. `enabledFeatures` is a list of feature keys/paths that are enabled, read from `feature-flags.json`
* Update the `enabled` static method in `/includes/Core/Util/Feature_Flags.php` to add the `googlesitekit_is_feature_enabled` filter.
	- the filterable value is the boolean value to be returned by the method
	- the filter should pass the `FeatureFlags::$mode` as the second parameter to the filter. Mode can be `production` or `development`.
* Create a new file in `/tests/e2e/utils/` called `features.js` which has 2 functions:
	- `enableFeature`
	- `disableFeature`
		- Both functions have a `feature` parameter which enables or disables a feature, by setting/removing the feature in `_googlesitekitBaseData.enabledFeatures` object.
	- All features should be disabled by default in E2E until explicitly enabled
* Review tests in `/tests/e2e/specs` to use the `enableFeature` and `disableFeature` functions. Enabled features should be reset after each test case.
* Create `/assets/js/features/index.js` which exports a variable named `enabledFeatures` which returns a copy of `global._googlesitekitBaseData.enabledFeatures` or an empty array if none present.
* Create the `assets/js/components/FeaturesProvider/` folder and using that folder:
	- Create `context.js` using `enabledFeatures` as the default value to `React.createContext`. [Example](https://github.com/WordPress/gutenberg/blob/77be77c60fc8bedc9c930d3c89a783a1b0f4be2f/packages/data/src/components/registry-provider/context.js)
	- Create `index.js` which exports the `Provider` from `context.js`
* Using `/assets/js/hooks`
	- Create a new file `useFeature.js` which exports a function `useFeature`
	- The `useFeature` function should accept a `path` as parameter and return a `boolean` if the path is in `enabledFeatures`. The latter can be retrieved via the Context API.
* Using `/assets/js/components/root/index.js`
	- Include the `FeaturesProvider` component which wraps all the components within the `ErrorHandler` component.
* Refactor all occurrences of `featureFlags.{ some path }.enabled` across components to use the `useFeature` hook.
* Review stories which use the `enableFeature` and `disableFeature` functions to instead use the `FeaturesProvider` component with the list of enabled features as its value.
	- All features should be disabled by default in Storybook unless enabled explicitly with a FeaturesProvider
* Using `/stories/utils/features.js`, remove the `enableFeature` and `disableFeature` functions.

### Test Coverage
* Add a new test for the `useFeature` hook.

### Visual Regression Changes

* There should be no visual changes.

## QA Brief

* Feature flags should all be set in `window._googlesitekitBaseData.enabledFeatures` on page load, based on the page mode (production or development) and the values in `feature-flags.json`.

## Changelog entry

* Introduce infrastructure for dynamically controlled feature flags via a `googlesitekit_is_feature_enabled` filter.

**Comment by felixarntz** [comment]
@aaemnnosttv ACs so far look good to me, just one thing: I'm not sure about the need for a `assets/js/features.js` file. If this only exports the global, I don't think it should live at the same level as the entry points. I think we could have the one reference to `_googlesitekitBaseData.enabledFeatures` in `FeatureProvider`, as the default value for the enabled features, if no such prop is provided.

Regarding server-side implementation (which we'll still need to add to the ACs): We could keep the current approach where by default, all features are enabled if the current build is a development build (via #2316). There could be a filter `googlesitekit_is_feature_enabled` that filters a boolean and also receives the "feature path" as well as the current build mode. The e2e plugins could use this filter (e.g. via an option to store), and we could also build something into the tester plugin that allows to enable/disable features via an option, using the same filter.

**Comment by aaemnnosttv** [comment]
Thanks for the feedback @felixarntz ! A few replies to your comments below:

> I'm not sure about the need for a `assets/js/features.js` file.

It's not strictly necessary to have that as a separate module – the idea there is that it would be cleaner to mock in tests as a module than changing a global which requires manual teardown whereas module mocks are scoped to the current test case.

It would also standardize access for any cases where the value might be needed outside of a component.

> If this only exports the global, I don't think it should live at the same level as the entry points.

That's fine, it can go anywhere, but it seems relevant to be fairly top-level.

> I think we could have the one reference to `_googlesitekitBaseData.enabledFeatures` in `FeatureProvider`, as the default value for the enabled features, if no such prop is provided.

Again, I'm accounting for possible usage outside of components (e.g. a `modules/analytics/index.js`) where we may want to conditionally register a widget/widget-area, etc and I think it would be better to abstract the use of the global behind a module which gives us a bit more flexibility and makes it easier to change later if we decide to source the value from somewhere else. We actually had an issue for refactoring our use of globals in a similar way a long time ago but we punted on that part at the time. See https://github.com/google/site-kit-wp/issues/1004  under "Update consuming code > Original details"

> Regarding server-side implementation (which we'll still need to add to the ACs): We could keep the current approach where by default, all features are enabled if the current build is a development build (via #2316).

Once the server is the source of truth for feature availability, I don't think the build mode is particularly relevant anymore other than perhaps using different defaults. The concept of the current environment is related of course but not as coupled as originally thought since it doesn't (or will no longer) tree-shake out any feature-specific code. For that reason, which command the assets were built with shouldn't really affect which features are enabled. The primary difference between `google-site-kit.zip` and `google-site-kit-dev.zip` should be build-related differences like added source maps, less compression/obfuscation, etc. Behavior and feature activation should be the same IMO.

Which features are enabled by default is worth discussing a bit more, but my general take on it is that I would prefer more of an A/B behavior rather than A+B when a feature is enabled. This will become more important in the future as well once we start using features in production.

> There could be a filter `googlesitekit_is_feature_enabled` that filters a boolean and also receives the "feature path" as well as the current build mode.

Yeah that sounds good to me, although similar to my previous comment, I wonder if we should expose the "build mode" as the environment instead - e.g. introducing a `googlesitekit_env() : string` function. Then said filter would only pass the name of the feature in addition to the boolean and the env could be reached for as needed.

---

One thing which we should still add here is better support for feature-specific styles. I think the cleanest solution for this right now would be to add all the active features as classes to the `html` or `body` (only for logged-in users though). I'll look into this a bit and add something to the ACs for it.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> It's not strictly necessary to have that as a separate module – the idea there is that it would be cleaner to mock in tests as a module than changing a global which requires manual teardown whereas module mocks are scoped to the current test case.

I'm in favor of exposing this via a module, but couldn't this be an internal module and not an actual entrypoint that we need to load its own JS file for in production? I think we could have the `FeatureProvider` as a class which by default reads enabled features from the global (again, that would be the only reference to `_googlesitekitBaseData.enabledFeatures` in JS), but can be passed an alternative configuration (e.g. via a setter). Tests could use that to mock a certain feature enabled state.

> Once the server is the source of truth for feature availability, I don't think the build mode is particularly relevant anymore other than perhaps using different defaults. The concept of the current environment is related of course but not as coupled as originally thought since it doesn't (or will no longer) tree-shake out any feature-specific code.

I think the build mode still remains relevant, IMO we should continue to rely on it for defaults like you're saying. Experimental features like currently the Widgets API or User Input would still be behind feature flags that would by default only be enabled in a development build. With the dynamic approach, we should be able to alter this at runtime, but we should maintain that behavior. Eventually I think we would have two types of features:
1. Experimental features where the feature flag is enabled only based on whether it is a development build.
2. Remote-controlled features where the feature flag is enabled depending on an API call to the service.

Many features would start as 1. and then become 2. eventually. The latter will be a follow-up and not part of this issue, but we should consider it for how we implement this issue.

The ability to control enabled features should be more of an extension mechanism rather than the built-in default: Site Kit has its own approach (development build and remote API) to determine whether a feature is active, but it would provide the `googlesitekit_is_feature_enabled` filter to **override** that default behavior, which would be used in e.g.
* e2e tests
* the tester plugin, which would e.g. store a WordPress option where the user can control enabled features

> One thing which we should still add here is better support for feature-specific styles.

I think this is an important conversation to have, but I'd prefer to decouple the CSS part from this one and focus on it afterwards.

**Comment by aaemnnosttv** [comment]
@felixarntz 

> I'm in favor of exposing this via a module, but couldn't this be an internal module and not an actual entrypoint that we need to load its own JS file for in production?

Yes, I wasn't suggesting we create an actual entry point for it – I just defined the module as being very top-level but I see now how that may have looked like it was to be an entry point 🙂 

> I think we could have the `FeatureProvider` as a class which by default reads enabled features from the global (again, that would be the only reference to `_googlesitekitBaseData.enabledFeatures` in JS), but can be passed an alternative configuration (e.g. via a setter). Tests could use that to mock a certain feature enabled state.

I'm thinking it would look very much [like this](https://github.com/WordPress/gutenberg/blob/cf4fb98cabc6eacb4a5708da2bb0eaf64ff43fe2/packages/data/src/components/registry-provider/context.js), except replace `defaultRegistry` with the import for `enabledFeatures` (wherever it comes from). `FeatureProvider` is just a `Context.Provider`. In tests, we could always wrap a component with `<FeatureProvider value={ features }>` to force specific features to be enabled for Storybook, etc – just like we do with the registry provider (it's just tucked into `WithTestRegistry`).

> Eventually I think we would have two types of features:
> 1. Experimental features where the feature flag is enabled only based on whether it is a development build.
> 2. Remote-controlled features where the feature flag is enabled depending on an API call to the service.

Yes although I think this differentiation should be opaque to the client. The only thing the client should care about is whether or not a feature is enabled. How that is determined would be entirely up to the server now, whether that comes from build configuration, options, or remote requests. I think we're probably on the same page about this but just clarifying my point.

> Which features are enabled by default is worth discussing a bit more, but my general take on it is that I would prefer more of an A/B behavior rather than A+B when a feature is enabled. This will become more important in the future as well once we start using features in production.

(From my previous comment ^) – just want to make sure we're on the same page here as I think this is an important differentiation to make in contrast to how we're currently using the flags which I think is also a pre-requisite to using dynamic feature activation in production.

**Comment by felixarntz** [comment]
@aaemnnosttv I agree with pretty much all your comment above, just one question: I'm not sure I understand your "A/B vs A+B" point. Can you elaborate a bit?

Once we've decided that, can you complete the ACs for this one? We should get this moving soon.

**Comment by aaemnnosttv** [comment]
@felixarntz 

> I'm not sure I understand your "A/B vs A+B" point. Can you elaborate a bit?

Sure – I meant that currently our use of feature flags is mostly _additive_ right now rather than either-or. That is, feature flags in some places render duplicate components (e.g. widgets API) rather than rendering a different component/feature in its place. This is perhaps more specific to only these refactoring type "features" where A is production and B is the refactored version. We would never enable two different versions of the same feature simultaneously in production so I think we should do the same in development. I think there is some value in being able to see both simultaneously when we're specifically checking for consistency, so maybe in development there could be a way to enable both explicitly, but my main point here was that in this case specifically we should have a one-or-the-other approach rather than both as this will complicate things with E2E tests as well.

Of course there will be cases where a feature is purely additive, but in cases where we have version A and version B we should actually have two separate feature flags rather than just one for the new part.

Perhaps something like this?

```js
someFeature.stable.enabled = 'production';
someFeature.beta.enabled = 'development';
```

> Once we've decided that, can you complete the ACs for this one? We should get this moving soon.

Sure, I'll get these wrapped up as soon as we have the last bits clarified 👍

**Comment by aaemnnosttv** [comment]
@felixarntz I think this is ready for IB now. There are a few small changes to the ACs from the initial draft.

* I have it exporting `enabledFeatures` from `assets/js/features/index.js` although clarified that this is internal only (I don't think this really belongs in components since it's intended to be used outside of components in some cases)
* `useFeatures` is now `useFeature( path )` so we don't need to worry about exposing the underlying value/structure to the consumer (at least in React)

Otherwise, this should be good to go. I would expect this is probably a 30, if it helps for planning.

If you're good with the ACs, let's move it forward 👍

**Comment by felixarntz** [comment]
@aaemnnosttv LGTM!

**Comment by tofumatt** [comment]
IB ✅

Thanks for the thorough ACs and IBs on this one. I dig the `useFeature()` hook! 👍🏻

**Comment by aaemnnosttv** [comment]
@asvinb @tofumatt – The IB looks good, just one thing to call out which could be a bit more clear:

> Create a new file in `/tests/e2e/utils/` called `features.js` which has 2 functions:
>	- `enableFeature`
>	- `disableFeature`
>		- Both functions have a `feature` parameter which enables or disables a feature, by setting/removing the feature in `_googlesitekitBaseData.enabledFeatures` object.

Note that we can't simply manipulate the global variable in E2E since it won't have any effect after the page loads. We also need to persist the enabled features (probably in an option) and then filter the feature activation using the new `googlesitekit_is_feature_enabled` filter from an E2E mu-plugin. Similar to other E2E utilities, these should be simple wrappers for `wpApiFetch` (I realize now that this is a violation of `sitekit/camelcase-acronyms` 🤔 ) with an accompanying E2E Rest route. If the option starts with `googlesitekit_` it will be deleted with all the others on every reset, which should be sufficient for that part of the ACs I think.

**Comment by aaemnnosttv** [comment]
⚠️ @tofumatt this is not working as expected when using a built zip as `feature-flags.json` is not included as-is, so `enabledFeatures` is always empty, even for a development build.

This detail was missed in the original definition and I'm not sure that we want to simply copy over that file. Bringing this back for a follow-up, but should be quick once we decide exactly how this should be handled.

cc: @felixarntz

**Comment by felixarntz** [comment]
@aaemnnosttv I thought about that too. We should have the feature flags available somewhere, so maybe we should just include that file in the built production ZIP as well.

In the near-term, we should also change it to only use this file (or potentially another way) to have a central list of which feature flags exist, only to know that, and have _all_ of them set to `false` by default, i.e. there should no longer be a differentiation between production and development builds. We'd then add UI to enable/disable features to the tester plugin.

**Comment by aaemnnosttv** [comment]
> In the near-term, we should also change it to only use this file (or potentially another way) to have a central list of which feature flags exist

@felixarntz we could potentially add a `Feature_Flags::get_available_features()` method which returns essentially `array_keys( static::$features )`. That would be easy to add even now.

> i.e. there should no longer be a differentiation between production and development builds.

`$mode` and related logic should be easy to remove. In this case, I think the `feature-flags.json` can be a simple list of feature names/keys since the activation is ultimately handled by the server; any `true`/`false` value there would be irrelevant, and we would always assume `false` by default anyways.

---

See [my PR above](https://github.com/google/site-kit-wp/pull/2677). I've added it to the `config.json` for now to get it working again, but we can iterate on that with the changes you've described here as well if you'd like.

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds good. I've opened #2683, to handle this in a follow-up issue.

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: Everything works as intended. Created a minor follow up issue with an additional suggestion: #2697

**Comment by eugene-manuilov** [comment]
QA :x: actually found one issue with E2E tests. Will work on a fix for it.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I think QA is basically done now, but sending back to you to confirm.

**Comment by eugene-manuilov** [comment]
Yep, all set, @aaemnnosttv!
