### ISSUE TITLE
E2E tests failing for nightly builds due to expect( '/' ).toHaveValidAMPForUser()

### ISSUE THREAD

**Issue by benbowler** [google/site-kit-wp#2455]
## Bug Description

E2E tests for the nightly build are failing ** in multiple places** due to the same, new error with `expect( '/' ).toHaveValidAMPForUser()`.

```
 FAIL  tests/e2e/specs/modules/tagmanager/setup.test.js (80.92s)
  ● Tag Manager module setup › Setup with AMP active › with Primary AMP › validates Homepage AMP for logged-in users
    Expected logged-in user to have valid AMP
      229 | 
      230 | 			it( 'validates Homepage AMP for logged-in users', async () => {
    > 231 | 				await expect( '/' ).toHaveValidAMPForUser();
          | 				                    ^
      232 | 			} );
      233 | 
```

The primary matter to determine here is whether or not the new version of WordPress causes Site Kit's tags/output to be invalid AMP markup. However, the test may only be failing because of changes in the new default theme which is not valid AMP apart from anything to do with Site Kit. Either way, this is important to address as while the WP nightly E2E build is allowed to fail, this will become WP latest as soon as WP 5.6 is released next week and the E2E job for WP latest is _not_ allowed to fail, so this would become a blocker for any PR to be merged.

## Steps to reproduce

Run a build on TravisCI.

## Additional Context

 E2E test config:  E2E=1 WP_VERSION=nightly

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E tests should pass for WordPress 5.6
    * If for some reason the new default theme has invalid AMP, the E2E setup script should be updated to use a known AMP-safe theme (e.g. TwentyTwenty)

## Implementation Brief

* Update `bin/local-env/install-wordpress.sh` to switch to the `twentytwenty` theme once WordPress core install/update is complete
* For older versions of WP, `twentytwenty` will need to be downloaded and installed before activating
* Merge https://github.com/google/site-kit-wp/pull/2474

### Test Coverage

* No changes needed

### Visual Regression Changes

* N/A

## QA Brief

* The E2E test job should pass for WordPress nightly – "E2E Tests (WordPress nightly)" in Travis  
_This job is normally allowed to fail and so the job failing wouldn't prevent the PR from being merged here as it normally does. The job should still be allowed to fail, but for this issue specifically it needs to pass._

## Changelog entry

* Make e2e tests pass for WordPress 5.6.

**Comment by tofumatt** [comment]
Right now I'm seeing these errors in my PHP logs when accessing my local site with AMP enabled in "Standard" mode. Even with Site Kit disabled I see that using Twenty Twenty as a theme.

<img width="857" alt="Screenshot 2020-12-02 at 15 45 43" src="https://user-images.githubusercontent.com/90871/100895739-cd1eba00-34b5-11eb-98a7-6b1f6b3c908f.png">

It seems to be failing when parsing a CSS stylesheet in the page whilst using Output Buffering. Beyond that I have no idea what's happening yet, and the AMP plugin makes no mention of it. I'll file a bug there if I can find better steps to reproduce, but I'm not yet sure what's causing it…

**Comment by aaemnnosttv** [comment]
@tofumatt – that's odd. What version of AMP do you have installed? Do you have xdebug enabled by chance?

**Comment by tofumatt** [comment]
Latest version of AMP… XDebug is enabled on my site, but this never used to happen, I'll try disabling it…

**Comment by tofumatt** [comment]
Still happening with XDebug disabled on that site. I'm quite stumped…

**Comment by felixarntz** [comment]
@westonruter Are you aware of any incompatibilities between the AMP plugin and nightly WP / WP 5.6? Our e2e tests are failing and it seems to be related to the AMP plugin, see https://github.com/google/site-kit-wp/issues/2455#issuecomment-737317301

**Comment by westonruter** [comment]
Do you have any code that is doing `ob_start()` inside of a sanitizer or any other logic that runs during output buffer processing? That will cause this error.

**Comment by westonruter** [comment]
Actually, I think the issue is that you're running out of memory during CSS processing. This is causing an error to be emitted which is then as a side effect causing the output buffer failure.  This came up before, actually with @aaemnnosttv. See comments at/after https://github.com/ampproject/amp-wp/issues/1915#issuecomment-527411833.

So check for other PHP errors in the log.

**Comment by tofumatt** [comment]
Noted, thanks! I thought it might've been a bug causing those errors, as elsewhere in our test suite we were seeing errors with AMP + Site Kit + WordPress Nightly (5.7). Seems like they might not be related, I'll keep digging.

Cheers @westonruter! 👍🏻

**Comment by aaemnnosttv** [comment]
@westonruter this seems to be specific to testing with the new Twenty Twenty-One theme. With the same code the AMP tests pass for me using Twenty Twenty.

I took a look in the browser using the AMP validator extension and it also indicates that Twenty Twenty-One has invalid AMP markup: 
![image](https://user-images.githubusercontent.com/1621608/100999753-c9e30700-3565-11eb-8bbb-7d63e427d60c.png)

The strange thing here is that the `html` element doesn't have the `data-ampdevmode` attribute that it seems to be finding, and this is with only the AMP plugin active in incognito mode 🤔  

Here are the first two lines from the page source:
```html
<!DOCTYPE html>
<html lang="en-US" amp="" i-amphtml-layout="" i-amphtml-no-boilerplate="" transformed="self;v=1">
```

I see there's an issue for the theme's compatibility over at https://github.com/ampproject/amp-wp/issues/5423 but don't see anything about this in particular.

@tofumatt I'll add an IB here to avoid using Twenty Twenty-One for now.

**Comment by tofumatt** [comment]
Great minds, I was trying this out too and nearing this idea 🙂 

IB ✅ (Code reviewed and looks good as well!)

**Comment by benbowler** [comment]
## ✅ QA:Eng Approved

I verified that the [E2E Tests (WordPress nightly)](https://travis-ci.com/github/google/site-kit-wp/jobs/453622388) completed successfully for this merge.

**Comment by westonruter** [comment]
> The strange thing here is that the `html` element doesn't have the `data-ampdevmode` attribute that it seems to be finding, and this is with only the AMP plugin active in incognito mode 🤔

I've found that the AMP Validator extension can be confused by incognito mode. It seems to perform the validation check as a non-incognito window. Try signing out of WordPress instead.

**Comment by aaemnnosttv** [comment]
Thanks @westonruter – I no longer see any validation errors when logged out with only AMP active.

The issue we were seeing definitely seems to be related to Twenty Twenty-One though because everything works just fine only by changing the theme back to Twenty Twenty.

**Comment by westonruter** [comment]
I wonder if it is purely due to a difference in the CSS size. I see that Twenty Twenty has a `style.css` that is 120KB whereas Twenty Twenty-One's `style.css` is 152KB. Perhaps that additional 32KB is causing the Docker container's memory to run out?
