### ISSUE TITLE
Reduce excessive amount of Analytics report requests for AdSense linked check

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2457]
When Analytics and AdSense are active, some widgets use the Analytics Reporting API to query for AdSense-related metrics. Those requests result in an error if the AdSense account and the Analytics property are not linked.

This has been a long-standing problem, because there is unfortunately no endpoint in the Analytics Management API that exposes whether such a link exists or not. There is an [endpoint for Google Ads links](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/webPropertyAdWordsLinks), but none for AdSense links.

The Analytics frontend uses an internal `linkableproperties` endpoint for this information as seen here:
<img width="1669" alt="Screenshot 2020-11-30 at 11 29 45" src="https://user-images.githubusercontent.com/3531426/100654941-6e174480-32ff-11eb-8a51-65522822e6ff.png">

We cannot use it, so it looks like we're limited to relying on the approach we're already using. However, we should explore ways to issue fewer of these erroring requests: Generally we don't cache API error responses, which is why this request is fired basically on every pageload, resulting in an excessive amount of error requests, which could be avoided. We should consider caching certain errors on the client-side too.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit-api` layer's cache approach should be modified so that cache TTL is determined based on the cache entry and is stored with each entry rather than specified manually when reading an entry:
    * `setItem` should receive:
        * A new `ttl` parameter that specifies the entry's time-to-live in seconds and defaults to `3600`. `ttl` should be included in the cache field alongside the existing `timestamp` and `value`.
        * An optional `isError` parameter (default `false`) that indicates whether the cached value is an error. That should also be stored in the cache field as `isError`.
    * `getItem` should have its `cacheTimeToLive` parameter removed. Instead, the found item's `ttl` property value should be used to determine whether it's expired or not. If an item doesn't have a `ttl` property (needed for BC), it should be considered expired.
* The `cacheTTL` argument of the `siteKitRequest` function should be used in the `setItem` call instead of the `getItem` call, based on the above changes.
* The logic for potentially dispatching some store actions, which is currently part of the `catch` clause in `siteKitRequest`, should be moved to a reusable `dispatchAPIError` function. The `trackAPIError` and console error logging parts should not be included in that.
* The error `catch` clause of `siteKitRequest` should be enhanced as follows: If the error object has a `error.data.cacheTTL` field, the error should be stored the same way, with the `ttl` as defined in the error object and `isError` passed as `true`. The clause should then call `dispatchAPIError` before rethrowing the error.
* After a successful `getItem` call in `siteKitRequest` it should be checked whether the `isError` field of the item is `true`. If so, it should go through `dispatchAPIError` and then be thrown like the regular error would have been rethrown at the end. It shouldn't be tracked or logged as API error though because it is a cached result.
* On the PHP side, the `Analytics` exception handling function should be updated so that a "Restricted metrics error" (see `isRestrictedMetricsError` in JS) receives a `cacheTTL` of 10 minutes in its error data. This ensures this specific type of error will be cached for 10 minutes, so that Site Kit doesn't trigger those requests as excessively. At the same time, 10 minutes is low enough so that a user that actually links AdSense with Analytics doesn't have to wait for one hour to see that action being recognized by Site Kit.

## Implementation Brief

- Using `/assets/js/googlesitekit/api/cache.js`
	- Update the `setItem` function to add a new parameter (object) with the following keys:
		- `ttl`: parameter that specifies the entry's time-to-live in seconds and defaults to `3600`
		- `isError`: parameter that indicates whether the cached value is an error and defaults to `false`
	- Move and rename the `_timestamp` parameter to within the object created above along with the default value. For e.g
		```js
		export const setItem = async ( key, value, {
			ttl = 60 * 60,
			timestamp = Math.round( Date.now() / 1000 ),
			isError = false,
		} = {} ) => {
			const storage = await getStorage();

			if ( storage ) {
				try {
					storage.setItem( `${ STORAGE_KEY_PREFIX }${ key }`, JSON.stringify( {
						timestamp,
						ttl,
						value,
						isError,
					} ) );
		```
	- The newly added parameters, i.e `ttl` and `isError` must be stored in the cache field alongside the existing `timestamp` and `value` values.
	- Update the `getItem` function:
		- to remove the `cacheTimeToLive` parameter.
		- to use the newly added parameter `ttl`  to determine whether the item in the cache is expired or not. If the `ttl` property is not present, then it is considered expired.
- Using `/assets/js/googlesitekit/api/index.js`
	- update the `setItem` call to use `cacheTTL` value for `ttl` parameter.
	- update `getItem` to no longer use the `cacheTTL` value.
	- Add a new function `dispatchAPIError` which contains the code to dispatch store actions in the `catch` clause of the `siteKitRequest` function. The `trackAPIError` and console error logging parts should stay within the `catch` clause.
	- Enhance the `catch` clause of`siteKitRequest` to better handle errors.
		- If the error object has a `error.data.cacheTTL` field, the error should be stored the same way, with the `ttl` as defined in the error object and `isError` passed as `true`. The clause should then call `dispatchAPIError` before rethrowing the error.
	- After a successful call to `getItem`, check if `isError` of the item is `true`. If so, it should go through `dispatchAPIError` and then be thrown like the regular error would have been rethrown at the end.
- Using `/includes/Modules/Analytics.php`
	- Update the `exception_to_error` method to include `cacheTTL` with the value set to 10 mins in the error data if there is a "Restricted metrics error"

### Test Coverage
* Update existing tests for `getItem` and `setItem` to cater for the new parameters.

### Visual Regression Changes
* There should be no visual changes.

## QA Brief
* Connect the "Adsense" and "Analytics" services and go to the Dashboard.
* Open Devtools and the following error message appears in the console. _**Restricted metric(s): ga:adsenseRevenue, ga:adsens….com/analytics/devguides/reporting/core/dimsmets.**_
* Refresh the page.
* The error should not show up for 10 mins.
* If you don't have an "Adsense" account, you can use the tester plugin to simulate Adsense data. Set:
	- Force AdSense account status: true
	- Force AdSense site status: added
	- Force AdSense report data: yes
	- Force Analytics report data: adsense

## Changelog entry

* Improve JS API caching layer to cache certain error responses if they include a `cacheTTL` extra data property, allowing to avoid excessive Analytics API requests when the AdSense account is not linked.

**Comment by aaemnnosttv** [comment]
> After a successful `getItem` call in `siteKitRequest` it should be checked whether the `value` is a `WP_Error`-like object. If so, it should be thrown instead of returned. The special logic that dispatches datastore actions for certain errors currently in the `catch` clause should be run for those errors as well. It shouldn't be tracked or logged as API error though because it is a cached result.

I think we can improve this part a bit. I don't think we should check the shape of the response to determine if it was previously caught. Instead, I think we could include an `error` or `isError` as a top-level property on the cached object (on the same level as `value`). In addition to this, I don't think we should throw it because that would require additional logic to avoid being reported again. For that, I think we simply want to extract a common error response handler function that is used with the return in both cases but doesn't include everything in the `catch`.

https://github.com/google/site-kit-wp/blob/160b5d1393cee4cce60574827564b5b02cd8b78e/assets/js/googlesitekit/api/index.js#L115-L121
Here `getItem` could return an additional `isError` variable and if `cacheHit && isError` it could return `handleError( value )`.

As for this chunk https://github.com/google/site-kit-wp/blob/160b5d1393cee4cce60574827564b5b02cd8b78e/assets/js/googlesitekit/api/index.js#L142-L153
I think this would be better to implement with an action that the core user store can listen on which also removes the coupling between the catch here and the data store.

```js
	} catch ( error ) {
		global.console.error( 'Google Site Kit API Error', error );
		trackAPIError( { method, datapoint, type, identifier, error } );

		doAction( 'googlesitekit.api.error', error, { method, datapoint, type, identifier } );

		throw error;
	}
```

The `doAction` could then be the body of the aforementioned `handleError` function which would be called from cache hits and caught errors.

The core user store could add the action on to it right after it's registered where it already has a reference to the global registry:
https://github.com/google/site-kit-wp/blob/160b5d1393cee4cce60574827564b5b02cd8b78e/assets/js/googlesitekit/datastore/user/index.js#L54-L55

Alternatively, the registered store returned by `registerStore` could be used instead:
```js
const registeredStore = Data.registerStore( STORE_NAME, store );
addAction( 'googlesitekit.api.error', 'googlesitekit.core/user.apiError', ( error ) => {
	if ( error.code === ERROR_CODE_MISSING_REQUIRED_SCOPE ) { 
		registeredStore.dispatch( actions.setPermissionScopeError( error ) );
 	} else if ( error.data?.reconnectURL ) {
		registeredStore.dispatch( actions.setAuthError( error ) );
 	} 
} )
```

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv I've updated the ACs based on some of your feedback.

> [...] Instead, I think we could include an `error` or `isError` as a top-level property on the cached object

Agreed, that makes it more clear and doesn't rely on inspecting the response, which couples it too much to the format. Updated in the ACs.

> In addition to this, I don't think we should throw it because that would require additional logic to avoid being reported again. For that, I think we simply want to extract a common error response handler function [...]

I've updated the ACs to outsource the common logic to a `handleAPIError` function, which does not include API error logging and tracking because that should only apply to non-cached errors actually coming from an API request. However, we still need to throw the error in the end - it doesn't matter whether it's cached or from an API request just made, it's still an error that should have the same impact on the consumer (in our case the datastore control).

> I think this would be better to implement with an action that the core user store can listen on which also removes the coupling between the catch here and the data store.

Regarding this and your following idea, I think that sounds good, but IMO goes beyond the scope of this. We can decouple the API layer from these datastore-specific parts in a separate follow-up issue.

**Comment by aaemnnosttv** [comment]
@felixarntz ACs look good, with one tweak:

```diff
- handleAPIError
+ dispatchAPIError
```

I think this clarifies the intent/behavior of this function since error tracking and logging are both technically both part of the error "handling" (as well as anything else in the `catch`). This makes it more clear that this part of the handling is specific to data store actions.

> Regarding this and your following idea, I think that sounds good, but IMO goes beyond the scope of this. We can decouple the API layer from these datastore-specific parts in a separate follow-up issue.

I'll open a new issue for implementing this part 👍 

Moving this forward to IB since the above is just a naming change which could easily be reverted if you feel strongly about the previous.

**Comment by aaemnnosttv** [comment]
@asvinb – IB looks great overall. Just a few points to clarify:

> `setItem` should receive:
        * A new `ttl` parameter that specifies the entry's time-to-live in seconds and defaults to `3600`. `ttl` should be included in the cache field alongside the existing `timestamp` and `value`.
        * An optional `isError` parameter (default `false`) that indicates whether the cached value is an error. That should also be stored in the cache field as `isError`.

`setItem` currently has the following signature:
https://github.com/google/site-kit-wp/blob/68d07d368da86e7b93b9201176cf5fba1af2fb0d/assets/js/googlesitekit/api/cache.js#L205-L210

For the new parameters, lets pass those via a new 3rd parameter as an object of options and move the `timestamp` and its default there as well:
```js
export const setItem = async ( key, value, {
	ttl = 60 * 60,
	timestamp = Math.round( Date.now() / 1000 ),
	isError = false,
} = {} ) => {
	const storage = await getStorage();

	if ( storage ) {
		try {
			storage.setItem( `${ STORAGE_KEY_PREFIX }${ key }`, JSON.stringify( {
				timestamp,
				ttl,
				value,
				isError,
			} ) );
```

> Update the `Analytics` exception handling function in PHP should be updated so that a "Restricted metrics error" (see `isRestrictedMetricsError` in JS) receives a `cacheTTL` of 10 minutes in its error data.

There is already some handling of this error in place in the Analytics class, see `\Google\Site_Kit\Modules\Analytics::exception_to_error`. We only need to return the error differently for that case, where now it simply updates a setting and returns the default error from the base method.

**Comment by asvinb** [comment]
@aaemnnosttv IB has been updated. Can you check? Thanks!

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
### QA ✅

Installed Analytics and Adsense followed the QA Brief paying attention to the console. I was unable to receive an error message. Refreshed multiple times, ensured each page was loading properly and nothing was broken.

![image](https://user-images.githubusercontent.com/57115907/106101823-4ff97500-60f3-11eb-98a1-58303beca057.png)

Sending to approval

**Comment by aaemnnosttv** [comment]
@cole10up – it looks like you have the Analytics data simulating a connected state which would not trigger the relevant error.
I think these two points in the QAB are inaccurate and should be skipped: 
![image](https://user-images.githubusercontent.com/1621608/106129040-92a96480-6168-11eb-8eff-1e46bd71ec33.png)

With a clean cache, you should see a "Restricted metric(s):" error in the console on the initial request (it may show more than once depending on the number of requests) but after that it should not show up again for another 10 min.

Can you give it another pass? cc: @wpdarren

**Comment by wpdarren** [comment]
@aaemnnosttv like Cole, I do not see any error messages in the console.  

1. Cleared cache
2. Connected Adsense and AnalytIcs (I am using a site that has Analytics and Adsense connected previously)
3. Refreshed the dashboard and looked in the console but no error appearing. 

Please note that I do have the tester plugin but the two options you mentioned were skipped. 

cc. @cole10up

**Comment by aaemnnosttv** [comment]
@wpdarren 
> I am using a site that has Analytics and Adsense connected previously

This will prevent the error 😄  – you need to use AdSense and Analytics accounts which are _not linked_ to observe the error that this issue is about.

**Comment by wpdarren** [comment]
@aaemnnosttv ah buggar, noted. On it.

**Comment by wpdarren** [comment]
@aaemnnosttv okay, we are getting somewhere! 😄 

I now see the error message:

![image](https://user-images.githubusercontent.com/73545194/106137845-441abb00-61a6-11eb-9e2d-9ae5d296aae5.png)

I have refreshed the page a few times and waited for a couple of minutes, and it still appears.  According to the QAB, it suggests it should not appear for around 10 minutes. Any thoughts?

**Comment by aaemnnosttv** [comment]
@wpdarren One more thing to note: I was wrong to say that the error/warning would no longer show in the console – it would. The difference is that the request that results in this error is no longer made (as the error response is cached now for a short time). So to verify, you'll need to observe the network requests. Once triggered initially, the cache should be primed so that refreshing the page should still result in the same error shown without an additional request causing it.

If it's too complicated, we can have an engineer look at this but I forgot this detail of the implementation that the console error would still be expected. The main thing here is that the error is cached and thus not retried on every request like it was before.

**Comment by wpdarren** [comment]
@aaemnnosttv thanks for the additional information. 

I've had a look at network for the dashboard and noticed most are saying `no-cache` in the headers but it could be that I am looking at the wrong requests. I'd be happier if an engineer looked at this to be honest. 

![image](https://user-images.githubusercontent.com/73545194/106149644-77b11180-61b5-11eb-93ba-c762e497a1a6.png)

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Error is cached now and no longer re-requested via the modern `googlesitekit-api` API once cached.

**Does not affect legacy data API, but this change will reduce the number of error requests made**

<details>
<summary>Screenshots</summary>

* Initial Error  
![image](https://user-images.githubusercontent.com/1621608/106175996-6f4ddc00-619f-11eb-9628-77e9aa76f14e.png)
* After page reload  
![image](https://user-images.githubusercontent.com/1621608/106175993-6ceb8200-619f-11eb-95c8-ed2f5a0e6bf7.png)
* Cached error  
![image](https://user-images.githubusercontent.com/1621608/106175986-6b21be80-619f-11eb-98d1-dafe668520e9.png)
* Request is made again after cached error is deleted
![image](https://user-images.githubusercontent.com/1621608/106175982-68bf6480-619f-11eb-9111-bd67e07b0fc0.png)
* Does not affect legacy data API (restricted error request still made here via batch request)
![image](https://user-images.githubusercontent.com/1621608/106175974-665d0a80-619f-11eb-8925-161333b28105.png)  
![image](https://user-images.githubusercontent.com/1621608/106176322-d5d2fa00-619f-11eb-8693-45c130886af2.png)

</details>
