### ISSUE TITLE
Change incorrect Search Console data threshold (back) to 2

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2458]
#2284 modified the threshold for requesting Search Console data from 3 days to 1 day ago. However, this was based on a miscommunication that the Search Console API would expose "fresh data" (data from 1 day ago), when it actually does not expose that. The Search Console frontend displays such "fresh data", but it doesn't come from the public API unfortunately.

So we'll need to change the threshold to 2 to provide the most accurate data for the current date range. (We _do_ have data for 2 days ago, so that's better than the previous 3 days, but we don't have data for 1 day ago.)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The threshold / offset for displaying Search Console data when parsing the date range into dates should be changed from 1 to 2 days, in both PHP and JavaScript (for the latter, see related #2237).

## Implementation Brief

* Change the passed `$offset` parameter in the `Search_Console` class's `parse_date_range` call from 1 to 2.
* Introduce a `DATE_RANGE_OFFSET` constant in `assets/js/modules/search-console/datastore/constants.js` with value 2.
* Update the `getDateRangeDates` calls to pass `offset: DATE_RANGE_OFFSET` (via the above constant) in:
    * `DashboardClicksWidget`
    * `DashboardImpressionsWidget`
    * `DashboardPopularKeywordsWidget`

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Ensure that the dates displayed for Search Console data (e.g. the graph on the Search Console page) displays data up until 2 days ago and includes the 7/14/28/90 day range until that day.

## Changelog entry

* Fix Search Console latest data threshold back to 2 days ago as that is the latest data the API provides.

**Comment by aaemnnosttv** [comment]
This issue is missing #2237 as a dependency, so I'll add that.

Otherwise, IB ✅

**Comment by benbowler** [comment]
I've completed this task but note that I've based the PR on my other blocking ticket #2447. Once this is merged the PR can be updated to base on the develop.

**Comment by felixarntz** [comment]
@benbowler See my comment on #2447, that one involves a bit more complexity than originally envisioned, so we won't be able to get it into the release. This one here, however is trivial - can you open a PR against `develop` with only the PHP part? This will fix the user-facing issue against the current codebase.

**Comment by benbowler** [comment]
@felixarntz I've created a new [PR here against `develop` with just the updates to ` Search_Console.php`](https://github.com/google/site-kit-wp/pull/2469).

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

- Dates displayed for Search Console displays data up until 2 days ago, i.e. 12/1 - [Screenshot](https://user-images.githubusercontent.com/73545194/101017563-36c9c180-35a5-11eb-8243-d937ae5b81cb.png)
- Dates displayed for Search Console displays data up until 2 days ago and includes the 7/14/28/90 day range - [Screenshot](https://user-images.githubusercontent.com/73545194/101017612-48ab6480-35a5-11eb-80dc-13c643e975df.png)
