### ISSUE TITLE
Fix JS date range parsing logic for AdSense widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2459]
#2235 moved responsibility for parsing AdSense date ranges from the server to the client. However, one thing was missed during definition of the issue, which was considering the day offset for AdSense API requests. On the server-side it is `1`, but now on the client-side it is `0`. The original behavior should be maintained so this will need to be updated.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The refactored AdSense widgets should use a day offset of `1` when calling the `getDateRangeDates` selector. The value should not be hard-coded in the widgets, but it should come from an API-specific constant.
* Since the offsets to use are API-specific and one of the widgets uses the AdSense API while the other uses the Analytics API, the two offsets should come from different sources.

## Implementation Brief

* Introduce a `DATE_RANGE_OFFSET` constant in `assets/js/modules/adsense/datastore/constants.js` with value 1.
* Introduce a `DATE_RANGE_OFFSET` constant in `assets/js/modules/analytics/datastore/constants.js` with value 1.
* In the AdSense `DashboardSummaryWidget`, update the `getDateRangeDates` call to pass the argument `offsetDays: DATE_RANGE_OFFSET` with the AdSense-specific constant.
* In the AdSense `DashboardTopEarningPagesWidget`, update the `getDateRangeDates` call to pass the argument `offsetDays: DATE_RANGE_OFFSET` with the Analytics-specific constant.

### Test Coverage

* N/A

### Visual Regression Changes

* The Storybook stories for `AdSense Module/Components/Dashboard/Summary Widget` and `AdSense Module/Components/Dashboard/Top Earning Pages Widget` are currently broken (likely since #2235). In order to fix this, we'll need to set up the mock data in Storybook correctly so that report data is provided for the actual dates based on the current date range.
* Since we don't want to deal with the actual date in Storybook, we need to have a way to centrally provide an alternative reference date:
    * Add internal action `setReferenceDate` to `core/user` (in `assets/js/googlesitekit/datastore/user/date-range.js`) and store it in a `referenceDate` state property. Its initial value should be the `YYYY-MM-DD` string of today. This action should only be used for testing to replace the real "today" with a fixed reference date.
    * Add selector `getReferenceDate` to `core/user`.
    * Update `getDateRangeDates` to use the store's referenceDate, unless the `referenceDate` argument is provided.
    * Add related test coverage.
* Update the fixtures for the `DashboardSummaryWidget` and `DashboardTopEarningPagesWidget` components to be the correct values:
    * Set up a reference date via the new internal datastore action (using `2020-09-12` in accordance with currently used fixture data).
    * For both widgets, instead of `dateRange: 'last-28-days`, specify `startDate: '2020-08-15', endDate: '2020-09-11` (results of `getDateRangeDates( { offsetDays: 1 } )` for `last-28-days` and reference date `2020-09-12`).
    * Remove the fixture files and instead move these definitions into the Storybook file since the fixtures are only used there and they are coupled to other data in this Storybook setup (particularly the reference date).

## QA Brief

* Use a development build.
* With Analytics and AdSense set up (use the tester plugin if needed to mock AdSense states and data), ensure that the two **refactored** AdSense widgets on the dashboard request their data with the current date range where the last date (`endDate`) is always 1 day before the current date. (Without this fix, the `endDate` would be the current date, which was problematic because AdSense wouldn't yet have the fresh data for it.)
    * You can do so via dev tools. Clean the session storage, then go to Network > XHR before refreshing/loading the SK dashboard page. You should see requests to `modules/adsense/data/earnings` and `modules/analytics/data/report`. All of those requests that have an `endDate` should have that date set to 1 day before the current day.
* Ensure the AdSense `DashboardSummaryWidget` and `DashboardTopEarningPagesWidget` Storybook stories all show up as expected (i.e. without some JS error).

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
> No visual changes, but for cleanup, update widget fixtures in `assets/js/modules/adsense/datastore/__fixtures__` for those two widgets to pass corresponding `startDate` and `endDate` arguments instead of `dateRange`.

@felixarntz can you clarify what's needed here? I found only a few instances of `dateRange` in those fixtures but can you elaborate on how the date range slug should be translated into the start/end dates? (Particularly because the estimate is so small)

**Comment by felixarntz** [comment]
@aaemnnosttv I've opened a PR for this already, it might clarify the IB a bit. The approach of putting the mock data into the JS file makes it a bit full, but at the same time having the data as a fixture is more error-prone, since it doesn't indicate that certain fields in those fixtures are dependent on certain Storybook data configuration. Let's think about how we could improve this while still keeping it connected.

**Comment by aaemnnosttv** [comment]
Thanks @felixarntz that helps a lot.

> The approach of putting the mock data into the JS file makes it a bit full, but at the same time having the data as a fixture is more error-prone, since it doesn't indicate that certain fields in those fixtures are dependent on certain Storybook data configuration. Let's think about how we could improve this while still keeping it connected.

I think this is where factories are useful, or a kind of hybrid fixture that allows for some dynamic bits.

Looks good so far though. IB ✅

**Comment by wpdarren** [comment]
@aaemnnosttv this might be my lack of experience using the `Network > XHR` section in Dev tools, but I do not see `modules/adsense/data/earnings` and `modules/analytics/data/report` either before refreshing or after the SK dashboard.  I am using the development build.  Here's what I am seeing  - [Screenshot](https://user-images.githubusercontent.com/73545194/101350313-b919f480-38c9-11eb-86a2-0e9856d38985.png) 

Any advice to help me QA this ticket?

**Comment by aaemnnosttv** [comment]
@wpdarren you need to first clear the session storage which is probably why you're not seeing the requests (they're already cached). To do this go to the Application tab in dev tools and clear the storage for the current domain.
![image](https://user-images.githubusercontent.com/1621608/101369719-4d2b9200-38b1-11eb-9046-244096e0eec7.png)

Alternatively, you can run this from the browser's console:
```
sessionStorage.clear()
```

After that, you should see the requests go through on the next page reload (after which they'll be cached again).

The XHR sub-tab/filter on the Network tab is where you should see them although the Name will probably just say `earnings` or `report`.

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

Verified: the end date is the date before today's date (I'm on the 8 December here in Malaysia) so the date is 12/07/2020. 
 - [Screenshot](https://user-images.githubusercontent.com/73545194/101384205-15ded480-38f5-11eb-8562-0d31fe4c8f31.png)  This was the case for both Adsense and Analytics. 

- No Javascript errors appear in the dashboard for Adsense and Analytics modules.
