### ISSUE TITLE
Error trying to set up Site Kit for WordPress

### ISSUE THREAD

**Issue by jonams27** [google/site-kit-wp#2462]
When trying to set up Site Kit by Google for WordPress I keep on getting the following error: 
****
400. That’s an error.
The server cannot process the request because it is malformed. It should not be retried. That’s all we know.
****
Any recommendation as to what I should do? This happens after I attempt to "Sign in with Google" during the set-up.

**Comment by jamesozzie** [comment]
Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist and hopefully get you successfully connected. 

Please include as much relevant information to your support topic as needed to assist with this issue, such as whether the same issue occurs from a browser [incognito window](https://i.imgur.com/ALzgiHp.png). You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.
