### ISSUE TITLE
Helper Plugin - redirect_uri_mismatch. wp-admin callback URI not added when setting up on a staging site

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2463]
## Bug Description

As reported by one user in the [support forums](https://wordpress.org/support/topic/redo-the-plugin-setup-on-site-kit-plugin/#post-13731987) when following the [guide to set Site Kit up on a staging site](https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/) the below error appears:

```
Authorization Error
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://staging.myexamplesite.com/wp-admin/index.php?oauth2callback=1, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}
```

I've been able to reproduce this one two sites, and I've had to [manually add my wp-admin callback URI](https://i.imgur.com/PJL9XBg.png) as an Authorized redirect URIs in the API Console. 

![image](https://user-images.githubusercontent.com/41326532/100784735-8a9ea400-3407-11eb-9abf-aab8b383cdd9.png)

## Steps to reproduce

1. Setup a staging site
2. Follow all steps on the [setup guide](https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/)
3. Setup Site Kit
4. After click on "Sign in with Google" the error appears

## Additional Context

 - SK version 1.21.0
 - Separate issue but during setup [the formatting](https://i.imgur.com/EXxo36h.png) of the Site Kit tab on developers.google.com seems out of place

A workaround is to manually include the full admin path as an authorized URL in the API Console for the created profect, before setting up Site Kit (and after applying the settings to the Developer settings)
`https://staging.mysite.com/wp-admin/index.php?oauth2callback=1
`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by wpdarren** [comment]
**L1 Escalation check.**  

Can confirm that this issue occurs when setting connecting to Google account after setting up a staging site  - [Screenshot](https://user-images.githubusercontent.com/73545194/100864582-2516ea00-34d1-11eb-80ea-a8830c8f54f0.png)  ✅

**Comment by adamsilverstein** [comment]
@jamesozzie - Since we maintain the tester plugin internally currently, I copied this ticket over to an internal task. Closing this out in favor.

**Comment by abdullah1908** [comment]
Team has fixed this issue internally for helper plugin and its good to go with the staging site setup.
