### ISSUE TITLE
Can't GET OAUTH CREDENTIALS

### ISSUE THREAD

**Issue by yasserberrehail** [google/site-kit-wp#247]
## Bug Description

For a website with an arabic title, it shows an error when trying to GET OAUTH CREDENTIALS :
Couldn't create project

field [project_id] has issue [project_id contains invalid characters]

## Steps to reproduce

1. Go to 'Sit kit dashboard'
2. Click on 'developers.google.com/web/sitekit'
3. Scroll down to 'GET OAUTH CREDENTIALS'
4. See error 'Couldn't create project,,,, field [project_id] has issue [project_id contains invalid characters]'

## Additional Context

 - PHP Version: 7.2.2
 - Browser Chrome
 - Plugin Version 1.0.0-beta.1.0.1
 - Website: in Arabic

**Comment by jamesozzie** [comment]
@yasserberrehail Thanks for reporting. Can you please try this workaround and let me know if you manage to get to the next stage?

- Close the "Couldn't create project" window
- In the address bar of your window paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
- Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
- Press enter, with your cursor in the address bar (as if you are visiting that URL)
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit

**Comment by yasserberrehail** [comment]
It Worked perfectly !

So the problem is within website arabic title ?

**Comment by jamesozzie** [comment]
Can you send the full address address that was being generated and I can check? Or share a [screenshot](https://i.imgur.com/LDdZw8j.png) of the auto generated project details (Site name & application name).
