### ISSUE TITLE
Remove deprecated `sudo` key from Travis config

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2475]
## Bug Description

The top-level `sudo` key in the Travis config is deprecated now and no longer has an effect.

![image](https://user-images.githubusercontent.com/1621608/101021443-99f12f00-3578-11eb-836a-269f693718de.png)

While this will have no change on the build to keep or remove, it will resolve the warning we currently see about the build config which we shouldn't get in the habit of ignoring.

![image](https://user-images.githubusercontent.com/1621608/101021635-d45acc00-3578-11eb-9037-0bb39d80f40a.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no build warnings or errors in the Travis CI build configuration

## Implementation Brief

* Remove `sudo: required` from the Travis config;
* Add `os: linux` to the Travis config.

### Test Coverage

* Not needed

### Visual Regression Changes

* Nothing should change on the UI

## QA Brief

* Travis CI jobs should pass;
* There should be no warnings or infos when you view the config file on the build jobs page.

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
IB ✅ 😄

**Comment by tofumatt** [comment]
Now that we've removed our Travis CI checks, this is redundant, so closing this issue. 🙂
