### ISSUE TITLE
Update AdSense widgets to no longer pass special dateRange parameters

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2477]
#2235 (and follow-up #2459) already modified the "typical" `dateRange` parameters in refactored AdSense widgets to be replaced with `startDate` and `endDate` parameters. There are some special cases in the `DashboardSummaryWidget` though which use `dateRange` values that are only used and supported by the AdSense module specifically, so those cannot use the centralized `getDateRangeDates` selector. Let's migrate those too though via another appropriate way 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense `DashboardSummaryWidget` should no longer pass `dateRange` parameters to the API.
    * For `today`, this can be done by simply getting the reference date from the `core/user` store and using it for both `startDate` and `endDate`.
    * For `this-month`, we need to introduce some other selector (maybe best in the `modules/adsense` store because it's specific to that for now) that returns the current reference date as `endDate` and the first date of the same month as `startDate`.
* The Storybook setup for this widget needs to be adjusted so that it still works as before these changes.

## Implementation Brief

* Change `todayArgs` in `DashboardSummaryWidget` to use:
```js
const referenceDate = select( CORE_USER ).getReferenceDate();

const todayArgs = {
	startDate: referenceDate,
	endDate: referenceDate,
	metrics,
};
```
* Get the start of the month using an approach like:
```js
const referenceDateFormat = new Intl.DateTimeFormat( 'en', { year: 'numeric', month: '2-digit', day: '2-digit' } );
const startOfMonth = referenceDate ? referenceDateFormat.format(
	new Date(
		new Date( referenceDate ).getFullYear(),
		new Date( referenceDate ).getMonth(),
		1
	)
) : undefined;
```
* Change `dailyArgs` to use:
```js
const dailyArgs = {
	startDate: startOfMonth,
	endDate: referenceDate,
	metrics,
	dimensions: [ 'DATE' ],
};
```

I don't feel a selector is relevant right now because this format is only used in this single component (along with the legacy component). If required the logic could be split out into a registry selector that used `getReferenceDate`, but right now doing the calculation inside the only component that needs it seems fine to me. Let me know what you think, but if you wanted we can easily amend the IB to add a `getStartOfMonthRelativeToReferenceDate()` selector 😅 

### Test Coverage

* Add Jest tests to `DashboardSummaryWidget` ensuring it calls `getReport` with the correct, expected arguments. Particular testing around the start of month args can be done.

### Visual Regression Changes

* No changes to VRT should result from these changes.

## QA Brief

* Setup and configure your environment with test Adsense data.
* Confirm that the data displayed in the AdSense DashboardSummaryWidget widget after these changes matches the data returned and displayed on the current release. Test each date range (7 days through to 90 days).
<img width="497" alt="Screenshot 2021-01-07 at 12 35 41" src="https://user-images.githubusercontent.com/119352/103893992-21850d00-50e6-11eb-8911-985df0574193.png">

## Changelog entry

* Get rid of remaining usage of legacy `dateRange` argument in AdSense widgets.

**Comment by felixarntz** [comment]
@tofumatt Makes sense to not add a selector for this very specific date format but do it in the component instead - IB ✅

**Comment by benbowler** [comment]
I began working on [tests for the DashboardSummaryWidget](https://github.com/google/site-kit-wp/commit/74c87cd5a88b2a66149e8b395eab224c1951f6f9) but to complete them will take me over the estimate for this ticket.

**Comment by benbowler** [comment]
Add a QA Brief

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

Verified:

The data displayed in the AdSense `DashboardSummaryWidget `widget matches the data returned and displayed on the current release. All date ranges were tested (7 days through to 90 days).  e.g. [Develop branch](https://user-images.githubusercontent.com/73545194/105184534-67bc8080-5b6a-11eb-8b59-eb03dcb67974.png) and [Latest release ](https://user-images.githubusercontent.com/73545194/105184577-74d96f80-5b6a-11eb-9c8e-39aa0f5df9d2.png)
