### ISSUE TITLE
Core Site Kit Functionality | Plugin activation

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#248]
## Bug Description

Set up e2e testing for, Core Site Kit Functionality, for Plugin activation (note was perviously set up with WP Assure here: https://gitlab.10up.com/google/google-site-kit-tests/merge_requests/1 )

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tests plugin activation flow including the success message shown after activation that leads users to the setup wizard.

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@swissspidy it looks like this one may already be covered by `plugin-activation.test.js`. 

Is there anything else needed here?

**Comment by swissspidy** [comment]
I don't think I have access to that GitLab repository. If you can send me an invitation I can compare that test with `plugin-activation.test.js` to see if anything's currently missing here.

**Comment by swissspidy** [comment]
Looks like this was indeed inadvertently fixed by #163 already 🙂

**Comment by swissspidy** [comment]
Closing since it was addressed in the PR referenced above.
