### ISSUE TITLE
Create a listFormat util to handle converting an array to string in i18n manner.

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2486]
## Feature Description

In JS, when combining an array of elements into a string, we want to do so in a manner that is consistent with i18n rules. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Similar to how we have a [numberFormat](https://github.com/google/site-kit-wp/blob/39a792059/assets/js/util/i18n.js#L35) utility function,  we should create a listFormat utility which makes use of [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat) and is polyfilled appropriately in [unsupported browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat#Browser_compatibility ) such as safari.

## Implementation Brief

There is already a partially complete PR to address some of the functionality in #2471 (there is already some feedback on the PR).

In `assets/js/util/i18n.js` create a `listFormat` utility which takes an `array: list` and `object: options`. Ensure that it uses Intl.ListFormat for the implementation and that instead of a fallback to `list.join(', ')` we ensure that browsers have the relevant polyfill applied.

We already have the polyfill available via [polyfill-library](https://github.com/google/site-kit-wp/blob/39a792059/package.json#L143 ) see [package details](https://github.com/Financial-Times/polyfill-library/tree/master/polyfills/Intl/ListFormat).

We have previously addressed this using the following:

```js
/* translators: used between list items, there is a space after the comma. */
const listSeparator = __( ', ', 'google-site-kit' );
errorMessage = sprintf( messageTemplate, inactiveModules.join( listSeparator ), module.name );
```
The existing PR should already address using the utility in place of the [previous approach](https://github.com/google/site-kit-wp/blob/39a79205909d539f2cf2b7bcbfc07d2cce90f10f/assets/js/googlesitekit/modules/datastore/modules.js#L425).

Ensure that the [written tests](https://github.com/google/site-kit-wp/pull/2471/files#diff-678060f38a2438fbd8e0ee2c6c8e5368c3a99ee0cac5efb569cc3f2a7707cb57R7) all pass. 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* In a [browser with Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat#Browser_compatibility), calling the listFormat utility ```listFormat(['a','b'])``` should return ```"a and b"```, in a browser that doesn't support it (e.g. safari), ```listFormat(['a','b'])``` should return ```"a, b"```. List format [can be found here](https://github.com/google/site-kit-wp/blob/6fef92da19a5da5f1a98089ed388bb069cf2ef76/assets/js/util/i18n.js#L61).
* 
## Changelog entry

* Introduce `listFormat` function to format entries in a comma-separated list.

**Comment by asvinb** [comment]
@ivankruchkoff Can you add the QA brief.

Thanks!

**Comment by asvinb** [comment]
Chrome ✔️ :
![image](https://user-images.githubusercontent.com/31818/102591237-2419c580-412b-11eb-9d11-7f58d9247c02.png)

Safari ✔️ :
![image](https://user-images.githubusercontent.com/31818/102591374-5c210880-412b-11eb-8f0b-23b845f159e4.png)

QA: ✅
