### ISSUE TITLE
NPM install fails with Node 14 on MacOS

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2487]
## Bug Description

We recently updated our Node version (as defined in the nvmrc) from v10 to v14, the latest LTS version.

While this worked fine in CI and even locally for most tasks, `npm install` fails when attempting to build/rebuild `fsevents` v1 which is required by dependencies of `@storybook/react` as well as `webpack`.

Installing the latest `fsevents` (v2) as a dev-dependency solves the problem.

## Steps to reproduce

1. Run `npm install` or `npm ci` on MacOS
1. See many errors and eventually command failure 
```
> fsevents@1.2.4 install /.../google-site-kit/node_modules/fsevents
> node install
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

See https://github.com/fsevents/fsevents/issues/339#issuecomment-700883596

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `npm install` and `npm ci` commands must succeed on MacOS

## Implementation Brief

* Merge #2488 (adds `fsevents@latest` to `devDependencies` in `package.json`)

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Ensure `npm install` works with a fresh checkout of the repository (run `nvm install` first to ensure proper Node version)  
This covers the clean install case as well
* Make sure Storybook starts
* Test webpack running in watch mode (`npm run watch`), and that file changes are detected

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@aaemnnosttv IB should be just `Merge #2488`, shouldn't it?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov that's basically what it is, it just adds a little detail as to what it's doing. You're right though that it could be omitted.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv IB :heavy_check_mark: but I would update it to be something like this to escape unnecessary confusion:

```
* Merge #2488 (adds fsevents@latest to devDependencies in package.json)
```

**Comment by tofumatt** [comment]
QA ✅
