### ISSUE TITLE
Core Site Kit Functionality | Client ID/Secret entry

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#249]
Set up testing for Core Site Kit Functionality, Client ID/Secret entry. Note this was perviously set up with WP Assure here: https://gitlab.10up.com/google/google-site-kit-tests/merge_requests/1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by circlecube** [comment]
I worked on this today and have made good progress. Should be able to clean it up and submit for review tomorrow. 

Tests in place for:
* disabled button on load
* disabled button on invalid data
* enabled button on valid data
* pressing button with valid data brings user to step 2

**Comment by lilybonney** [comment]
@circlecube - I believe @swissspidy left some comments on the CR for you to address. Moving this back to Development for that work. Once you're finished, just move this back to Code Review for a second pass. Thanks!

**Comment by circlecube** [comment]
Thank you @lilybonney, issues are addressed and back to code review with @swissspidy now.

**Comment by felixarntz** [comment]
@circlecube Please make sure to assign the issue as applicable next time: Either just unassign yourself if you completed the first iteration, or unassign yourself and assign back the original reviewer if you worked on it as part of a request for changes. :)

Just assigned this back to @swissspidy accordingly.

**Comment by swissspidy** [comment]
Review done, now awaiting QA.

**Comment by lucymtc** [comment]
QA looks good
