### ISSUE TITLE
Make data store navigation-aware

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2497]
## Feature Description

Currently there are a few instances in the plugin where we need to account for whether or not a navigation is in progress, so that we can show a progress bar after a form submission for example. Until now, we have managed to work around this on a case-by-case basis and in a local component scope.

As a reoccurring need, it makes sense to address this in a more holistic way by exposing navigation state to consumers via the data store. There are also cases where it makes sense to be managed at a bit of a higher level as a navigation may not "belong" to any specific component, or may not even be triggered by UI within Site Kit.

See related thread here: https://github.com/google/site-kit-wp/issues/2261#issuecomment-737322569

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `core/location` data store, defined in `assets/js/googlesitekit/datastore/location/`. It should have an entrypoint file `assets/js/googlesitekit-datastore-location.js` which also has a corresponding PHP asset. The asset should become part of the core dependencies.
* The store should include:
    * A `navigateTo( url )` action, which sets a flag that a navigation is happening and then redirects the user to that URL (via `global.location.assign`).
    * A `isNavigating()` selector, which returns a boolean based on whether or not a navigation is currently in progress.
    * A `getNavigateURL()` selector, which returns the URL that is currently being navigated to (if a navigation is currently in progress).
* Existing workarounds for handling in-progress navigation (e.g. post module setup submit) should be refactored to use the new `isNavigating` selector.
* The `UnsatisfiedScopesAlert` should be updated to only show up if there is currently no navigation happening using the new `isNavigating` selector (potentially this should be more specific to only navigations to OAuth connect URLs).

## Implementation Brief

- Create new folder `/assets/js/googlesitekit/location`
- Using newly created folder:
	- Create `constants.js` which exports the `STORE_NAME` constant which is set to `core/location`
	- Create `navigation.js` which will contain the different selectors.
- Create `/assets/js/googlesitekit/location/index.js` taking another datastore as example.
- Create `/assets/js/googlesitekit-datastore-location.js` which imports `assets/js/googlesitekit/datastore/location`
- Edit `webpack.config.js` to include a new entry point file `assets/js/googlesitekit-datastore-location.js`
	```js
	'googlesitekit-datastore-location': './assets/js/googlesitekit-datastore-location.js',
	```
- Using `/assets/js/googlesitekit/location/navigation`
	- Add the following action:
		- `navigateTo` with `url` as param which sets a flag that a navigation is happening and then redirects the user to that URL via `global.location.assign`
	- Add the following selectors:
		- `isNavigating` which returns a boolean based on whether or not a navigation is currently in progress.
		- `getNavigateURL` which returns the URL that is currently being navigated to (if a navigation is currently in progress).
- Review all components where we handle in-progress navigation (e.g. post module setup submit) to use the `isNavigating` selector.
	- For e.g `/assets/js/modules/adsense/components/setup/SetupAccountCreate.js`
- Using `/assets/js/components/notifications/UnsatisfiedScopesAlert.js`
	- Add condition to only display that component if there is no navigation happening using the new isNavigating selector (potentially this should be more specific to only navigations to OAuth connect URLs).

### Test Coverage

* Add test for the action and selectors for the location datastore

### Visual Regression Changes

* There should be no visual changes.

#### User-facing QA

* Set up the plugin on your local site and make sure that, when using a development build and activating a new module, no notification about unsatisfied scopes briefly pops up;

Once this is tested, please, add the `QA:Eng` label and leave it in the `QA` column.

#### Engineering QA

* Make sure the new `core/location` datastore is added to the codebase;
* Make sure we use the new datastore for all navigations instead of using `global.location.assign` calls;

## Changelog entry

* Introduce `core/location` JS store, rely on it for redirects, and fix notification about unsatisfied scopes unnecessarily appearing before an OAuth redirect.

**Comment by aaemnnosttv** [comment]
@felixarntz ACs look good to me for the most part.  One thought here:

> The `UnsatisfiedScopesAlert` should be updated to only show up if there is currently no navigation happening using the new `isNavigating` selector (potentially this should be more specific to only navigations to OAuth connect URLs).

Rather than conditionally showing the alert, perhaps we should conditionally show a progress bar or overlay instead? I think we could provide a better experience here as well by providing feedback as to what's happening, rather than suddenly sending the user through OAuth – some users may not understand this requires temporarily leaving your site.
I'm not suggesting we add a paragraph to an overlay when this happens but we could use this opportunity to provide _some kind_ of messaging. E.g. "We'll be right back, new permissions required by Analytics..." something like that. I'm not sure what the best wording to use there would be – we could also leave it off and keep a bare progress bar, similar to other places in the plugin.

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv 
> Rather than conditionally showing the alert, perhaps we should conditionally show a progress bar or overlay instead?

It would make sense to show some sort of loading indicator in the component that actually triggers the requirement for the new scope being needed (which we're already doing in some cases) - for example that would be helpful when activating a new module where right now there's no UI reflecting that loading state.

For the `UnsatisfiedScopesAlert` though, I don't think it makes sense. The problem with it is that it shows up at all - it shouldn't. It's a warning that something is wrong which pops up out of nowhere, and in this case there isn't anything actually wrong because the need for scopes will be satisfied via the ongoing redirect to OAuth. Having the alert pop up with a loading bar (or any other copy) would still be unexpected UX I think.

Loading indicators (or OAuth information messages) like that should be incorporated into the component where that redirect was triggered. But I think that's better as separate follow-up issues.

I think this should be good for an IB then.

**Comment by aaemnnosttv** [comment]
> Having the alert pop up with a loading bar (or any other copy) would still be unexpected UX I think.

I was suggesting that the alert wouldn't be visible because the progress bar or overlay, etc would cover it. In that way it would kind of take over the interface so that it wouldn't matter that the alert might be displayed underneath or not.

**Comment by felixarntz** [comment]
@aaemnnosttv Ah okay, that makes sense. I'd still say we should decouple that though since it's a different enhancement. For now let's fix the bug that happens in a development build via this issue, and then we can have a follow-up for general loading/copy overlay for when redirecting to OAuth.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@eugene-manuilov Can you add a QA Brief here? Most importantly it should cover that, when using a development build and activating a new module, no notification about unsatisfied scopes briefly pops up.

**Comment by eugene-manuilov** [comment]
QA brief is added.

**Comment by felixarntz** [comment]
@eugene-manuilov I'm not sure this should be a "QA: Eng" because it includes a user-facing change (even though for now only in the dev build) that should go through regular QA. Maybe we can define a workflow for such cases where both is needed. cc @aaemnnosttv

**Comment by eugene-manuilov** [comment]
@felixarntz I have updated the QA brief and removed the `QA: Eng` label for now. I have asked to add that label back once the regular QA is done. Does it work for you?

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

When using a development build and activating a new module, no notification about unsatisfied scopes pops up. I was able to activate Analytics, Adsense and Pagespeed with no messages appearing on the FE, or within Console. 

Tagged `QA:Eng` for their tests.

**Comment by asvinb** [comment]
### Eng QA: ✅ 

- Checked the codebase, navigation data store is present. ✔️ 
- Checked for usage of `global.location.assign`. It's only present in the navigation data store ✔️
