### ISSUE TITLE
Ship flag mode file with Site Kit development build ZIP

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2498]
## Bug Description

The `dist/config.json` file determines whether the current build is a production or development build, via #2316. Intentionally, that file is not included in the production ZIP bundle because for that ZIP file we can through that avoid additional file reading and JSON parsing logic to run on every pageload. However, we didn't consider development ZIP bundles in that thought: Those ZIP files are currently missing the file too, but in there it's necessary for PHP to know that this is a development build.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `release` script should be updated: If the current build is not a production build, it should also copy the `dist/config.json` file so that it is included in the bundle ZIP.

## Implementation Brief

* Read the `flagMode` from the `dist/config.json` in the release script
* If the `flagMode !== 'production'`, include the `config.json` in the zip, at the same path
* Merge https://github.com/google/site-kit-wp/pull/2500

### Test Coverage

* None needed

### Visual Regression Changes

* N/A

## QA Brief

* Run `npm run release-zip` – inspect the resulting zip file to ensure `dist/config.json` is **not** present
* Run `npm run dev-zip` – inspect the resulting zip file to ensure `dist/config.json` **is present**

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
### QA ✅

Confirmed dist/config.json is **not present** in release-zip
![image](https://user-images.githubusercontent.com/57115907/101570543-80425400-398b-11eb-9293-db6c8045d463.png)

Confirmed dist/config.json is **present** in dev-zip
![image](https://user-images.githubusercontent.com/57115907/101570616-ac5dd500-398b-11eb-8ee6-3f5cb480ca4d.png)

Sending to approved
