### ISSUE TITLE
Only point to specific question and back when editing user input question

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2499]
Currently, when previewing user input questions at the end of the flow or when viewing the responses from within settings, when clicking "Edit", you land on the `googlesitekit-user-input` screen with the regular behavior that you'll have to go through all (following) questions.

This should be updated so that you only have to re-answer the question you're intending to edit, rather than having to click through the following ones again too.

@tofumatt already highlighted that UX flaw in a comment for #2041 around the settings UI. That has now been revisited and should be enhanced for _both_ the settings UI and the regular preview at the end of the flow.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When clicking "Edit" in the Preview UI of the `googlesitekit-user-input` screen, the question displayed should not surface "Previous" and "Next" buttons, but rather a single "Back" button (is that the best wording here?). That button should internally set the new responses in the datastore and then return the user to the preview UI (rather than requiring to go through all following questions again).
* When clicking "Edit" in the settings UI around user input questions, the question displayed should not surface "Previous" and "Next" buttons, but rather a single "Submit" button. That button should internally set the new responses in the datastore _and_ immediately submit it to the REST API / authentication service (**different from the first bullet point**) and then return the user to the settings UI (rather than requiring to go through all following questions again).
* The copy and behavior of the buttons on a user input question should be contextually modifiable (e.g. via props) to cover the above use-cases.

**Note**: The difference in behavior between the two cases is due to the fact that in the user input screen, responses are submitted via the "Submit" button in the preview UI (which is also why the question button there should not say "Submit"). In the settings UI there is no "Submit" button so changing the responses for a question should immediately submit it.

## Implementation Brief

We should use hash-based URLs to track and set the current question/position/behaviour of the `UserInputQuestionnaire` component, rather than the internal state variable (`activeSlug`) currently used.

While in the future this could (and likely should) be moved to use a real router like React Router, for now we'll implement the URL handling with the `react-use` `useHash` hook mentioned in #2041. What would make sense is supporting URLs like:

* `/wp-admin/admin.php?page=googlesitekit-user-input#/` -> Show the User Input preview UI with all questions answered (if already answered). Redirect to `#/question/1` if not answered.
* `/wp-admin/admin.php?page=googlesitekit-user-input#/question/1` -> Show the first question with the ability to advance to the next one.
* `/wp-admin/admin.php?page=googlesitekit-user-input#/question/1/single` -> Show the first question but set the "submit" button to replace the "next" button. Return to the "Summary" route (`#/summary`) after answering.
* `/wp-admin/admin.php?page=googlesitekit-user-input&redirect=$REDIRECT_URL#/question/1/single` -> Show the first question but set the "submit" button to replace the "next" button with a redirect to a particular page after submitting the updated answer.
* `/wp-admin/admin.php?page=googlesitekit-user-input#/summary` -> Show all questions after answering them, before submitting them. If all questions have been answered, show the summary without the "back" + "Submit" buttons.

* Add `react-use` to `package.json`, then use hash values to control routing on the User Input page (`/wp-admin/admin.php?page=googlesitekit-user-input`) to control:
  * If the user is on the preview/dashboard or a particular question
  * The current question
  * Whether the question should be asked solo or move to the next one
* Add a `useHash` hook to the `UserInputQuestionnaire` component, using the question `:id` in the `/question/:id` hash "route" in place of `activeSlugIndex`.
* Convert the existing `activeSlug`/`setActiveSlug` implementation to use [`setHash()`](https://reactrouter.com/web/api/history) to change slug position.
* Convert "Edit" links/buttons in `UserInputPreviewGroup` to a `setHash()` call that points to the relevant question. If the questions have already been answered and only one question should be answered (the "edited" one) before the user is returned to the "Summary" (`#/summary`), use the `#/question/1/solo` route.
* Render `<UserInputPreview />` when the `#/summary` route is active.
* Any root/default/empty URL should default to rendering `#/summary` (if questions have been answered) or `#/question/1` if not.

### Test Coverage

* Adding tests to ensure that when a single question is answered/submitted its change is immediately submitted would be good.

### Visual Regression Changes

* No visual changes to existing components should be made, but new components with different button actions would be present.

## QA Brief

* Reset your site and reconnect.
* Complete the "Customize Site Kit to match your goals" user input questions as normal
* From the summary page, confirm that clicking "Edit" next to a question allows you to edit a single question and click "Back" to return to the summary **without submitting**.
<img width="1157" alt="Screenshot 2020-12-31 at 13 34 54" src="https://user-images.githubusercontent.com/119352/103412445-06a61c00-4b6d-11eb-93b5-8ac69e7a61b7.png">
<img width="1158" alt="Screenshot 2020-12-31 at 13 35 07" src="https://user-images.githubusercontent.com/119352/103412449-09a10c80-4b6d-11eb-857e-11652d4a5d04.png">

 * Submit your answers and navigate to [the admin settings page](http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-settings#admin).
 * From this admin page, confirm that clicking "Edit" next to a question takes you to edit a single question and clicking "Submit" saves the result to that single questions change.

## Changelog entry

* Improve UX for modifying user input settings, removing the requirement to click through subsequent questions when only wanting to change a specific response.

**Comment by felixarntz** [comment]
cc @marrrmarrr

**Comment by tofumatt** [comment]
I think the best approach here is to adopt a router and add much more flexibility and ability to externally set the parameters of the page (with the hash routes) to this component. I'm estimating high largely because the existing component will need to be changed (and simplified) which could take a fair bit of time, but the actual router work should be straightforward if the implementer is familiar with React Router 😄

It could take a bit less time but I think it's good to budget for some extra code review time on this one as well, since it'll be our first instance of a router.

**Comment by felixarntz** [comment]
@tofumatt I think introducing a React router is too broad of a change to make here. We can solve this with props almost like you already worked towards during #2041, so let's go that approach for now. I am not against introducing `react-router` where it makes sense, but let's discuss that in its own issue where we can discuss the tradeoffs and review where it would be applicable, without having this discussion being affected by user-facing behavior changes, and without having this discussion block progress on user-facing behavior.

As you already indicate by the estimate, this would be a big change, and I'm pretty sure we can implement prop-based changes here in a lot less time (I'd assume between 11 and 19 points).

Can you write an IB that relies on component changes as needed, and then open a separate issue with a proposal for a router, why it would make sense and where it would make sense?

**Comment by tofumatt** [comment]
My concern with opting not to use a router is we need to end up building a fair amount of one ourselves without. I think the difference is closer to the higher-end of a 19-point issue still without React Router… which it's frankly the lower end of a 30 point issue with React Router.

I guess I'm wary of us spending time building our own implementation of this too many times instead of using React Router first and having more consistency over the experience.

Ultimately I think it will be more effort to implement the router separately, but I'll update the IB here to use the `useHash` hook and update the hashes that way.

**Comment by tofumatt** [comment]
Looking at it again, I think it might not be too bad using a `useHash` hook after all. We _do_ lose things like the back button and other "router" benefits we'd get for free, but I think it should be straightforward enough to implement without the router.

I'll file a follow-up issue on exploring React Router as well 🙂

**Comment by felixarntz** [comment]
@tofumatt Great, IB ✅

**Comment by benbowler** [comment]
This work is ready for review, I've created a PR against #2041 as it relies on the work there.

**Comment by benbowler** [comment]
QA Brief added.

**Comment by cole10up** [comment]
### QA ⚠️

Tested: 
**Confirmed editing, saving, not saving but hitting back button, tab order etc**
![Site Kit by Google Settings ‹ Hellogoodbye1 — WordPress (1)](https://user-images.githubusercontent.com/57115907/104558264-67b30280-55f7-11eb-87ed-9fc628ef43ac.gif)

@felixarntz the link for settings below drives to global settings, is there anyway we can have that URL drive to admin settings?

![image](https://user-images.githubusercontent.com/57115907/104558494-beb8d780-55f7-11eb-987f-07e865fec8df.png)

**Comment by felixarntz** [comment]
@cole10up Good catch, that would be a quick UX improvement. @eugene-manuilov Can you open a follow-up PR to link to the "Admin Settings" tab directly?

**Comment by eugene-manuilov** [comment]
@felixarntz #2622 is created. Could you please take a look at it?

**Comment by cole10up** [comment]
### QA ✅

Retested and its looking good.

**One thing I did notice that is worth a discussion**

On my test site prior to retesting this latest merge for the settings link I did the following:

1. I reset SK
2. Deactivated the plugin
3. Deleted the plugin
4. Downloaded the latest release candidate
5. Activated the plugin and setup SK
6. Flipped to a development build and navigated to Admin Settings

Notice:
![image](https://user-images.githubusercontent.com/57115907/104689756-f12a0980-56b7-11eb-9bef-e7c12997499b.png)

I expected to be asked to start the the user input questions over and **not see my old answers** given I reset, deactivated and deleted the plugin I had used prior to this build.

Should we log a new issue for this @felixarntz ?
