### ISSUE TITLE
Leverage Webpack to expose modules on Site Kit global

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2501]
## Feature Description

Currently we have a number of JS entry point source files which solely expose an internal module on the `googlesitekit` global object, similar to `window.wp` in WordPress core.

E.g. https://github.com/google/site-kit-wp/blob/dc2cb956993b8d6e47592884264c37a70bcd9895/assets/js/googlesitekit-i18n.js#L29-L30

As an example of this approach that was introduced previously (and later removed) – something like this would work for any module where we simply want to make some module (in this case `@wordpress/i18n`) available on `window.googlesitekit[ name ]`.
https://github.com/google/site-kit-wp/blob/6751990ec21e2966186d6de4ab39e7ce33d5a9b3/webpack.config.js#L314-L335

Gutenberg uses a similar technique to build its libraries ([source](https://github.com/WordPress/gutenberg/blob/873f94106a11e11bfab0184998421907dc6370c5/webpack.config.js#L72-L78)).

One thing to pay attention to in such a refactoring would be for potential regressions fixed by #2444 as "library" modules likely don't share a runtime as can be done with others. For this reason, it may be necessary to keep some of our library entry points around. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
I don't think this issue is actionable (it's been left alone for over four years). I'm actually not clear on what its next steps are, and I think it's safe to simply close this issue as a won't fix.
