### ISSUE TITLE
Change icon argument of registerWidgetArea to require a `WPComponent` SVG

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2505]
Following up on #2143 and #2413, we should also update the `icon` argument of the `registerWidgetArea` action in `core/widgets` to require an SVG passed as `WPComponent` rather than a string.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `registerWidgetArea` action of `core/widgets` should be updated to support an `Icon` argument instead of `icon`. The required type should be `WPComponent`.
* `WidgetAreaRenderer` should be adjusted to render `Icon` as a component, passing `width` and `height` having the same value, using the same size as is currently used for the module icons on top of each module screen (e.g. `googlesitekit-module-search-console`).
* Tests and any usage should be updated to pass an SVG as component instead of passing a string.

## Implementation Brief

* Update the `registerWidgetArea` action in the `assets/js/googlesitekit/widgets/datastore/areas.js` file to accept `Icon` instead of `icon` in the passed settings object;
* Update the `WidgetAreaRenderer` component to use the new `Icon` component (if it's available) instead of rendering an image tag with icon src. Add `width` and `height` properties with `33` as their values to the rendered `Icon` component.

### Test Coverage

* Update existing tests if any are failing.

### Visual Regression Changes

* N/A

## QA Brief

* Check that the `registerWidgetArea` action accepts `Icon` WPComponent instead of `icon` string;
* Check that the `WidgetAreaRenderer` component renders the `Icon` component instead of an image tag;

## Changelog entry

* Rename `icon` argument of `registerWidgetArea` to `Icon` and require it to be a `WPComponent` (e.g. an SVG).

**Comment by eugene-manuilov** [comment]
> ... any usage should be updated to pass an SVG as component instead of passing a string.

@felixarntz do we use icons for widget areas already? I haven't found one in the codebase. :thinking:

**Comment by felixarntz** [comment]
@eugene-manuilov No we don't use any widget area icons yet, but this will be needed for the module pages: On the Analytics page for example, there would be a single "Analytics" widget area that uses the Analytics module icon as icon, like it is right now. That was the idea behind this.

**Comment by felixarntz** [comment]
IB ✅

**Comment by asvinb** [comment]
- Check that the registerWidgetArea action accepts Icon WPComponent instead of icon string ✔️ 
- Check that the WidgetAreaRenderer component renders the Icon component instead of an image tag ✔️ 

QA: ✅
