### ISSUE TITLE
Remove Module datapoints for individual settings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2507]
## Feature Description

Currently we have a number of datapoints defined for modules that simply return a single value from the module's settings.

These are legacy datapoints which were used to both request individual settings from the client but also were used internally to retrieve these values in many places. Another purpose that these datapoints provided in the past was to abstract the key of the setting it was stored in. This is because the convention used for setting keys had changed or been renamed several times in the past.

We addressed much of this with the addition of `Module_Settings` classes quite a while ago, which handles things like default values, as well as legacy key migration automatically.

In addition to the abstraction provided by the data store that we use for interacting with settings on the client now, these individual datapoints are no longer needed and unnecessarily complicate things where used.

A few examples of these datapoints are (not a comprehensive list):
* Analytics: `(GET|POST):(account-id|profile-id|use-snippet`
* AdSense: `(GET|POST):(account-id|client-id)`
* Tag Manager: `(GET|POST):(account-id|container-id)`

<details>
	<summary>All current settings by module</summary>
	
```json
{
  "site-verification": [],
  "search-console": [
    "propertyID"
  ],
  "adsense": [
    "ownerID",
    "accountID",
    "clientID",
    "accountStatus",
    "siteStatus",
    "accountSetupComplete",
    "siteSetupComplete",
    "useSnippet"
  ],
  "analytics": [
    "ownerID",
    "accountID",
    "adsenseLinked",
    "anonymizeIP",
    "internalWebPropertyID",
    "profileID",
    "propertyID",
    "trackingDisabled",
    "useSnippet"
  ],
  "pagespeed-insights": [],
  "optimize": [
    "ownerID",
    "ampExperimentJSON",
    "optimizeID"
  ],
  "tagmanager": [
    "ownerID",
    "accountID",
    "ampContainerID",
    "containerID",
    "internalContainerID",
    "internalAMPContainerID",
    "useSnippet"
  ]
}
```

</details>

Note: datapoint names are snake-case while setting keys are camelCase (with the exception of our acronym casing rules)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All module datapoint definitions and create/parse handlers for individual settings should be removed
* All internal (server-side) `get_data` and `set_data` calls for these datapoints should be updated to use the module's `Settings` instance directly instead
* All client-side references to these (if any remain) should be updated to read/update the setting using non-legacy methods where possible, otherwise using existing legacy functionality as a last resort or where changes to use modern methods would require an unreasonable amount of changes.

#### Analytics

* Remove all `account-id`, `anonymize-ip`, `internal-web-property-id`, `profile-id`, `property-id`, `tracking-disabled`, and `use-snippet` definitions from the definitions list in the `get_datapoint_definitions` method;
* Remove all `account-id`, `anonymize-ip`, `internal-web-property-id`, `profile-id`, `property-id`, `tracking-disabled`, and `use-snippet` handlers in the `create_data_request` method;
* Update all occurrences of `$this->get_data( 'account-id' )`, `$this->get_data( 'profile-id' )`, `$this->get_data( 'tracking-disabled' )`, and `$this->get_data( 'property-id' )` to use the Analytics settings instance;
* Remove definition and handler for `connection` endpoints and rework all occurrences of the `$this->get_data( 'connection' )` to use the Analytics settings instance;

#### AdSense

* Remove all `account-id`, `account-status`, `use-snippet`, `setup-complete`, `connection`, and `client-id` definitions from the definitions list in the `get_datapoint_definitions` method;
* Remove all `account-id`, `account-status`, `use-snippet`, `setup-complete`, `connection`, and `client-id` handlers in the `create_data_request` method;
* Update all occurrences of `$this->get_data( 'account-id' )` and `$this->set_data( 'account-id', ... )` to use the AdSense settings instance;
* Update the `settings` datastore to use the module settings instead of the `use-snippet` endpoint (see `assets/js/modules/adsense/datastore/settings.js`).

#### Tag Manager

* Remove all `account-id`, `connection`, and `container-id` definitions from the definitions list in the `get_datapoint_definitions` method;
* Remove all `account-id`, `connection`, and `container-id` handlers in the `create_data_request` method;
* Update the `is_connected` method to pull the appropriate container ID from the module settings instead of calling `get_data` methods for `container-id` datapoint.

### Test Coverage

* Update `AnalyticsTest`, `AdSenseTest`, and `Tag_ManagerTest` classes to account for the aforementioned changes.

### Visual Regression Changes

* No visual changes are expected as a result of these changes.

## QA Brief

* Set up the plugin on your site;
* Activate and connect Analytics, AdSense, and Tag Manager modules;
* Make sure you can edit the settings of those modules, it saves correctly and you can view changed settings after refreshing the page.
* No PHP notices should be raised when Site Kit is active (added as follow-up to initial PR here)

## Changelog entry

* Remove various old REST datapoints in AdSense, Analytics, and Search Console modules that were only present to access specific settings and unused.

**Comment by aaemnnosttv** [comment]
cc: @felixarntz

**Comment by aaemnnosttv** [comment]
@eugene-manuilov IB is off to a good start, but missing a few datapoints:

**Analytics**
* `connection` – while not a setting itself, it's essentially a legacy version of the settings endpoint
* `tracking-disabled` – maps to `trackingDisabled` option

**AdSense**
* `account-status`
* `connection`
* `use-snippet` – currently used by `fetchSaveUseSnippetStore` but this should be able to be updated to use `saveSettings` (or `fetchSaveSettings`) since the update route can accept a partial of settings to merge.
* `setup-complete` – not a setting but seems to be completely unused

**Tag Manager**
* `connection`

Note about all the `connection` datapoints, the only one that seems to be actually used is in the Analytics class so these should all be easy/safe to remove/refactor.

**Comment by eugene-manuilov** [comment]
Thanks, @aaemnnosttv! IB is updated and ready for review.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by benbowler** [comment]
## ✅ QA:Eng Approved

**Comment by aaemnnosttv** [comment]
## QA ❌ 

This results in the following notice now:
```
PHP Notice:  Trying to access array offset on value of type bool in /var/www/html/wp-content/plugins/google-site-kit/includes/Modules/AdSense.php on line 370
```

Taking a closer look, this is happening here where we're accessing `$option['accountID']` now instead of using `get_data` as we did before.

**Before**
https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/includes/Modules/AdSense.php#L448-L451

**After**
https://github.com/google/site-kit-wp/blob/df38a87cef996a23f35434400d5eac632b604df8/includes/Modules/AdSense.php#L367-L370

This happens because this is requested within the constructor of the `AdSense` module (really the base `Module` constructor) which calls `setup_info`, which in turn calls this remaining call to `get_data( 'reports-url' )`.
https://github.com/google/site-kit-wp/blob/df38a87cef996a23f35434400d5eac632b604df8/includes/Core/Modules/Module.php#L128

The problem is not that it calls `get_data` but that this call happens before the module's settings are registered, since this is triggered by `Modules`, before it has a chance to register the settings.
https://github.com/google/site-kit-wp/blob/df38a87cef996a23f35434400d5eac632b604df8/includes/Core/Modules/Modules.php#L252-L256
https://github.com/google/site-kit-wp/blob/df38a87cef996a23f35434400d5eac632b604df8/includes/Core/Modules/Modules.php#L197-L202

---

All that to say that, this is an odd case where we can't rely on module defaults being present, and fixing that is beyond the scope of this issue. For now, we should simply fix the logic so that it works the same as before without any notice.

@eugene-manuilov would you please address? 🙂

**Comment by eugene-manuilov** [comment]
Thanks, @aaemnnosttv. How about something like in the #2679? What do you think?

**Comment by eugene-manuilov** [comment]
Actually, that PR isn't going to work... Need to think about it a little bit more. Will work on it on Monday.

**Comment by aaemnnosttv** [comment]
## QA ✖️ 

The Optimize module still has a few datapoints which need to be removed. This was missed in the IB.

I'll open a quick follow-up to address.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* No settings-specific datapoints remain!
* _Optimize_ no longer has any datapoints, and related methods have been removed (due to changes in a semi-recent issue which no longer requires all modules to implement them)
* All module datapoints now all reference a `service` in their definition
	- The only exception here seems to be `GET:tag-permission` although this probably should have a service too (like GTM), but that's out of scope here

<details>
	<summary>All module datapoint definitions</summary>
	
* https://github.com/google/site-kit-wp/blob/8b8340008cf7b687e1c1da118278322a0fe36ef4/includes/Modules/AdSense.php#L197-L207
* https://github.com/google/site-kit-wp/blob/324379e25c61e8098e7637402219090da7211869/includes/Modules/Analytics.php#L348-L372
* https://github.com/google/site-kit-wp/blob/8b8340008cf7b687e1c1da118278322a0fe36ef4/includes/Modules/Search_Console.php#L173-L180
* https://github.com/google/site-kit-wp/blob/1680f18750ea7fc778d39a5a5feab64d0d1b24d0/includes/Modules/Site_Verification.php#L138-L145
* https://github.com/google/site-kit-wp/blob/324379e25c61e8098e7637402219090da7211869/includes/Modules/Tag_Manager.php#L242-L255
* https://github.com/google/site-kit-wp/blob/1680f18750ea7fc778d39a5a5feab64d0d1b24d0/includes/Modules/PageSpeed_Insights.php#L61-L65

</details>
