### ISSUE TITLE
Replace deprecated eslint-loader with eslint-webpack-plugin

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2509]
## Bug Description

[The `eslint-loader` package is now deprecated](https://github.com/webpack-contrib/eslint-loader#warning-deprecated) and [`eslint-webpack-plugin`](https://github.com/webpack-contrib/eslint-webpack-plugin) is recommended in its place.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The functionality provided by `eslint-loader` should be replaced with `eslint-webpack-plugin`  
See https://github.com/webpack-contrib/eslint-webpack-plugin#migrate-from-eslint-loader

## Implementation Brief

* Install `eslint-webpack-plugin` as a development dependency;
* Delete `eslint-loader` dependency;
* Remove eslint-loader from the common rules array:
  https://github.com/google/site-kit-wp/blob/026f7d3e022356335c420d276fdd31366ea6342c/webpack.config.js#L117-L123
* Create a new `plugins` array similar to the `rules` one and add the `ESLintPlugin` plugin to it;
  * Pass options from the `eslint-loader` to the eslint plugin constructor.
* Destruct plugins array in the plugin section of each configuration as we do it with the rules array.

### Test Coverage

* Not needed

### Visual Regression Changes

* No visual changes are expected

## QA Brief

* Make sure the eslint plugin catches formatting errors when you build assets.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by Hazlitte** [comment]
QA ✅
I tested npm builds and watch and edited a few different files with linting errors.  All errors were caught.
