### ISSUE TITLE
Setup & Authorization Flow: Test Site Verification

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#251]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

This issue should expand on the existing test made in #250, covering the Site Verification.

* Instead of faking the `googlesitekit_site_verified_meta` user option to be already set after coming back from the authentication, the flow should actually be tested.
* Internal REST API requests (partly proxying Google API requests) need to be filtered/overridden to return certain dummy responses to match the scenarios.
* two alternative scenarios:
    1. `GET siteverification-list` datapoint request returns that the user isn't verified for the site
        * user sees a non-editable input field with the site URL and has to confirm they want to be verified
        * then `POST siteverification` datapoint needs to be faked
        * user is then forwarded to next step (Search Console)
    2. `GET siteverification-list` datapoint request returns that the user is already verified for the site
        * user is automatically forwarded to next step (Search Console)

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz when you say "two alternative scenarios" it's a total of 2 scenarios that we're testing, correct?
