### ISSUE TITLE
Update all copyrights in code to 2021

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#2511]
## Feature Description

We currently have a mix of `"Site Kit by Google, Copyright 2019"` and `"Site Kit by Google, Copyright 2020"` (see: https://github.com/google/site-kit-wp/pull/2482#discussion_r537769171) in the codebase. Given it'll soon be 2021, I'm filing this now for us to run a quick search + replace of these strings to:

1. unify them
2. update them to the right year, en masse

Of course, this should not be merged until 2021. 🙂 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All docstring headers should contain `Site Kit by Google, Copyright 2021 Google LLC `
* There should be no `Copyright 2019` or `Copyright 2020` in the code base

## Implementation Brief

* Do a search + replace of the entire codebase for `Copyright 2019 Google` -> `Copyright 2021 Google`
* Do a search + replace of the entire codebase for `Copyright 2020 Google` -> `Copyright 2021 Google`

### Test Coverage

* None.

### Visual Regression Changes

* None (unless any VRTs include the copyright notice, in which case they're safe to update.)

## QA Brief

* None needed.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@johnPhillips I cannot find a PR for this issue although it is in CR. Can you give me the link please? For the future, please use the ZenHub UI at the bottom of the PR view to connect the PR to the respective issue.

**Comment by aaemnnosttv** [comment]
@felixarntz I just reviewed and merged the PR and then noticed that there was one remaining instance left to update 🤦 
https://github.com/google/site-kit-wp/blob/1680f18750ea7fc778d39a5a5feab64d0d1b24d0/assets/sass/widgets/_googlesitekit-widget-adsense-performance.scss#L4
Would you mind fixing this last one as a direct push to develop? It seems silly to run the builds again twice for a 1 character change in a doc block. I suppose we could just include it as part of another PR too, but assigning to you to make the call 😄 
cc: @johnPhillips
