### ISSUE TITLE
Add (React) Router 

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#2514]
## Feature Description

In order to improve navigation behaviour in components, expose state in the URL when appropriate, give users more control of the plugin with browser history, and lessen our implementation of routers with things like `useQueryParams` and `useHash`, I think it's time we adopted an actual Router and started implementing routes in our components.

There are instances in the plugin already (like the [SettingsApp](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/settings/settings-app.js#L54)) where we effectively implement a `HashRouter`—we could simplify our code and use more idiomatic React Router patterns using React Router.

There are also things like the User Input questions (see #2499) where using a Router would allow us more declarative control over the behaviour of a component—especially when linked to from other parts of the plugin.

Due to its widespread usage, knowledge/guides for it, and its reliability, [React Router](https://reactrouter.com/) is the recommended library from me.

Using React Router could even open us up to inter-linking the entire plugin with React, but this would require more effort in terms of asset management by JS and prefetching of data. It's worth exploring, but much later.

For now, the focus of this issue is to add React Router to the plugin, and to migrate a single section of the plugin that relies on a "homemade" router to React Router. I would nominate the `SettingsApp` to migrate to a `HashRouter`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A React Router `Router` component should be added as a common wrapper to all React apps
* `SettingsApp` should be updated to use using `<Route />` components and `<Link>` components
    * It should continue to respond to the same top-level (`#settings`/`#connect`/`#admin`) hash URLs and the sub-URLs for `#settings/`
        * These should be updated to "redirect" to the new hashes below
    * Additionally, the hashes used for each tab should be updated as follows:
        * `#/connected-services` - Connected services tab
        * `#/connected-services/{moduleSlug}/{view/edit}` - Connected services tab with specific module panel opened (in view or edit state)
        * `#/connect-more-services` - Connect more services tab
        * `#/admin-settings` - Admin settings tab
* Active Module state for `SettingsApp` is no longer stored in `state`, but in the route.

## Implementation Brief

* `npm install --save react-router-dom`
* If permitted by the components, change the `<Tab>` components to use a `<Link>` directly so the user can see the URL they are about to navigate to in their browser. If not possible, update the `handleActiveIndexUpdate` prop to use `history.push()` instead of `setState()`.
* Refactor the existing approach https://github.com/google/site-kit-wp/blob/89da36a15ce166500a423a73ba513d607959e62d/assets/js/components/settings/settings-modules.js#L239-L252 to something like:
```js
<Switch>
	<Route path="settings">
		<div className="
			mdc-layout-grid__cell
			mdc-layout-grid__cell--span-12
		">
			<Layout>
				<!-- Nested routes could be used here. -->
				{ activeModules }
			</Layout>
		</div>
	</Route>
</Switch>
```
* The handling of which module is active and whether or not it is in `view` or `edit` state should also be handled by the Router. See https://reactrouter.com/web/guides/quick-start/2nd-example-nested-routing for how we can nest multiple routers to achieve this effect. The routes should look like this:
  * `#/connected-services` - Connected services tab (all module panels closed)
  * `#/connected-services/:moduleSlug/:action` - Connected services tab with specific module panel opened for module based on `:moduleSlug` param, in `view` or `edit` state, based on `:action` param.
  * `#/connect-more-services` - Connect more services tab
  * `#/admin-settings` - Admin settings tab
  * It could be appropriate to add simple "redirect" routes to these routes from the old (`#settings`/`#connect`/`#admin` routes respectively, if straightforward)
* Remove hash handling, state setting of data from hash, and state passing in `SettingsApp`. All state related to the hash should be handled by the Router going forward
* Use a `<HashRouter>` high in our component tree (likely https://github.com/google/site-kit-wp/blob/89da36a15ce166500a423a73ba513d607959e62d/assets/js/components/root/index.js#L33), but rely on `<Switch>` cases throughout the code to manage routing.

### Test Coverage

* We'll need to add a router to our Jest test wrapper so that components relying on a `<Router>` in their parent structure don't cause Jest tests to fail.
* Adding tests to ensure the routes behave as-expected, with Jest tests, is appropriate here.
* End-to-end tests should all continue to work as-expected, unless the change from tab handler to `<Link>` components results in slight changes to some Settings page E2E tests.
* Jest tests should largely remain the same, but some tests relying on implementation details in `SettingsApp` and its children make require updates.

### Visual Regression Changes

* No VRT changes should come from these changes.

## QA Brief

- Verify redirects work as expected (with base URL being `/wp-admin/admin.php?page=googlesitekit-settings`)
    - `#admin` redirects to `#/admin-settings`
    - `#connect` redirects to `#/connect-more-services`
    - `#settings` redirects to `#/connected-services`
    - `#settings/:moduleSlug` redirects to `#/connected-services/:moduleSlug`
        - For example: `#settings/adsense` → `#/connected-services/adsense`
    - `#settings/:moduleSlug/view` redirects to `#/connected-services/:moduleSlug`
        - For example: `#settings/adsense` → `#/connected-services/adsense`
    - `#settings/:moduleSlug/edit` redirects to `#/connected-services/:moduleSlug/edit`
        - For example: `#settings/adsense/edit` → `#/connected-services/adsense/edit`
- Verify accordions functionality has not regressed
    - Clicking on an accordion for a module opens that module (and closes any other open modules, only 1 can be open)
    - Clicking on an accordion for a module that is already open closes that module
- Verify accordions change URL/route properly
    - Clicking on an accordion for a module (when opening) should modify the URL to be `#/connected-services/:moduleSlug`
        - For example: Clicking the accordion for "AdSense" should open the accordion and change the URL to `#/connected-services/adsense`
        - Clicking this accordion again should close the accordion and change the URL back to `#/connected-services`
- Verify Module Editing functions as expected. When editing a module:
    - URL should change to `#/connected-services/:moduleSlug/edit` , for example: `#/connected-services/adsense/edit`
    - Other modules should have "Section locked while editing" overlayed and be disabled.
    - The "Cancel" button should return back to the view state (and remove `/edit` from the URL)
    - "Disconnect Analytics from Site Kit" link should behave as it did before, displaying a modal which allows you to disconnect a module from Site Kit.
- Verify tab functionality has not regressed. Clicking a tab switches to the proper tab panel.
- Verify tabs change URL/route properly.
    - "Connected Services" → `#/connected-services`
    - "Connect More Services" → `#/connect-more-services`
    - "Admin Settings" → `#/admin-settings`

## Changelog entry

* Refactor settings tabs with React Router and update URL hashes with more user-friendly names.

**Comment by felixarntz** [comment]
@tofumatt It would be great if we could define the hash URL hierarchy to use for the Settings page and the router in a bit more detail. How about this:

* `#/connected-services` - Connected services tab
* `#/connect-more-services` - Connect more services tab
* `#/admin-settings` - Admin settings tab
* `#/connected-services/{moduleSlug}/{view/edit}` - Connected services tab with specific module panel opened (in view or edit state)

**Comment by tofumatt** [comment]
Agreed, and I like those new, more explicit routes too. I also added a note about adding a few `<Redirect />` routes in there—it's very easy to do (one line) and we could do it for completeness.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@caseymorrisus @felixarntz I just noticed with the current implementation that if you navigate back in a way that results in a hash change, the app does not update accordingly. I was going to open this as an issue but I would expect the router will fix this. @caseymorrisus can you confirm that this will work as expected with the router-based implementation?

![Kapture 2021-01-29 at 14 19 27](https://user-images.githubusercontent.com/1621608/106274826-8b07bf80-623d-11eb-8333-c8eb55a6e45a.gif)

**Comment by caseymorrisus** [comment]
@aaemnnosttv I can confirm that this is fixed with the `react-router` implementation (which I'm spending time on today).

**Comment by aaemnnosttv** [comment]
@felixarntz @tofumatt there were some decisions made in the comments that weren't reflected in the current ACs so I've updated them 👍

**Comment by tofumatt** [comment]
@aaemnnosttv Can you assign @wpdarren after reviewing and merging this PR? 🙏🏻

**Comment by cole10up** [comment]
### **QA ✅**

**Confirmed the following below per the QA brief.**

Verify redirects work as expected (with base URL being /wp-admin/admin.php?page=googlesitekit-settings)
#admin redirects to #/admin-settings
#connect redirects to #/connect-more-services
#settings redirects to #/connected-services
#settings/:moduleSlug redirects to #/connected-services/:moduleSlug
For example: #settings/adsense → #/connected-services/adsense
#settings/:moduleSlug/view redirects to #/connected-services/:moduleSlug
For example: #settings/adsense → #/connected-services/adsense
#settings/:moduleSlug/edit redirects to #/connected-services/:moduleSlug/edit
For example: #settings/adsense/edit → #/connected-services/adsense/edit
Verify accordions functionality has not regressed
Clicking on an accordion for a module opens that module (and closes any other open modules, only 1 can be open)
Clicking on an accordion for a module that is already open closes that module
Verify accordions change URL/route properly
Clicking on an accordion for a module (when opening) should modify the URL to be #/connected-services/:moduleSlug
For example: Clicking the accordion for "AdSense" should open the accordion and change the URL to #/connected-services/adsense
Clicking this accordion again should close the accordion and change the URL back to #/connected-services
Verify Module Editing functions as expected. When editing a module:
URL should change to #/connected-services/:moduleSlug/edit , for example: #/connected-services/adsense/edit
Other modules should have "Section locked while editing" overlayed and be disabled.
The "Cancel" button should return back to the view state (and remove /edit from the URL)
"Disconnect Analytics from Site Kit" link should behave as it did before, displaying a modal which allows you to disconnect a module from Site Kit.
Verify tab functionality has not regressed. Clicking a tab switches to the proper tab panel.
Verify tabs change URL/route properly.
"Connected Services" → #/connected-services
"Connect More Services" → #/connect-more-services
"Admin Settings" → #/admin-settings

Sending to approval.
