### ISSUE TITLE
Support Multiple Google Tag Manager Containers

### ISSUE THREAD

**Issue by timnolte** [google/site-kit-wp#2519]
## Feature Description

Google supports the use of multiple GTM containers on a single site. (https://developers.google.com/tag-manager/devguide?hl=en#multiple-containers) Please look at supporting this feature. Currently the [Google Tag Manager for WordPress](https://wordpress.org/plugins/duracelltomi-google-tag-manager/) plugin already supports this and I'd prefer to stick with Site Kit and not have to move back to using that plugin to accomplish this.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for your suggestion, I've labeled this as a feature request for further consideration by the team. Note that while Tag Manager does allow for multiple Tags to be contained on a site it's also recommended to keep containers to a minimum. 

Feel free to keep watch of this feature request and be sure to [share your thoughts](https://wordpress.org/support/plugin/google-site-kit/reviews/#new-post) on the plugin so far.

**Comment by timnolte** [comment]
Yeah, the hard part will be determining what limit to put in the plugin, if any. Maybe there could be an option to turn this feature on with a some baseline limit and a filter that could allow a site developer/owner to override that limit.

**Comment by felixarntz** [comment]
After review with the team, this is out of scope for Site Kit. While Tag Manager supports multiple containers, Google's recommendation is to keep it to a minimum, similar to how it is for Analytics properties. Therefore Site Kit will stick to enabling the recommended approach, also given the cognitive overhead this would create for users.
