### ISSUE TITLE
WP admin description; add content related to support forum and writing a review

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#2520]
## Feature Description

At the end of the plugin description in the 'Plugins' menu within WordPress admin, suggest adding some content related to the support forum and writing a review. As per #2156 we could suggest adding a link for "Ask a Question" which will direct users to https://wordpress.org/support/plugin/google-site-kit/#new-post as well as adding a link for "Write a Review" which will direct users to https://wordpress.org/support/plugin/google-site-kit/reviews/#new-post

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/59321d89-b844-4f08-897d-59b65107c9f0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@marrrmarrr What should be the updates here for the wordpress.org readme? We only have access to modify the copy within the "Description" tab in the screenshot above.

**Comment by fhollis** [comment]
Closing this ticket as advised by @marrrmarrr as we already have references to both support and reviews in very close proximity to the description text
cc @eclarke1
