### ISSUE TITLE
Test accessing WordPress Dashboard

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#253]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After plugin is set up, in the Dashboard:
* From SC, the dashboard should show total clicks and total impressions for the site for the past 28 days. 
* If the user hasn't set up GA yet, show CTA with link to the start of the GA setup process. 
* If the user has set up GA, display top 5 pages sorted by Views, total unique visitors, and average time on page. 
* Display link to go to the main Site Kit dashboard. 

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by adamsilverstein** [comment]
Potential tests:
* Dashboard widget should load (or not as appropriate for user)
* Widget should contain site kit header, link to site kit dashboard, set up analytics CTA
* Clicking "Visit your Site Kit Dashboard" link should take you to the dashboard.
* Clicking "Set up Analytics" CTA link should take you to the Analytics setup page

**Comment by felixarntz** [comment]
@ThierryA @tofumatt @aaemnnosttv Do we even need e2e tests for something like this? There's no user interaction tested here, this should be covered by visual regression testing, shouldn't it?

**Comment by aaemnnosttv** [comment]
It could be tested, e.g. making sure that it's only visible to users with the proper role/cap, but this can probably be done more efficiently in PHPUnit. Testing things like the anchors linking to the right places would probably be better suited for Jest. 

I'm not sure the value/confidence this e2e test would offer would be worth the cost; at least as it is now. Perhaps revisit later?

**Comment by tofumatt** [comment]
Agreed; this doesn't really have any user interaction and is better-serviced by lighter-weight tests. We can do this with Jest assuming we have a "setup" Jest helper we're confident in (which we should).

I don't think this should be an E2E test—instead of revisiting later we should probably consider this a unit/integration test, not E2E. A label change should suffice, right?

**Comment by felixarntz** [comment]
This is invalid, no need to test a single click in the WP dashboard, which just displays data (covered by visual regression tests).
