### ISSUE TITLE
Check authentication service to determine remote-enabled features

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2533]
The `Feature_Flags` class currently only determines feature availability based on the current build mode. As part of the "Remote-controlled features" epic, this should be expanded to connect to the authentication service which will expose a new endpoint that for a given site returns the remotely controlled features and whether they're enabled.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new utility class `Remote_Controlled_Features`. It should include a public method `get_features()` which issues a (cached) request to the authentication service (rely on the `Google_Proxy` class for the URL) as follows:
    * POST request to the proxy URL with path `/site-management/features/`
    * send URL-encoded body parameters `site_id`, `site_secret`, `platform` ("wordpress/google-site-kit"), and `version` (plugin version)
    * the response will be an object map of feature identifiers and their enabled/disabled state as boolean
    * The request should not be issued if the site is not using the proxy or if there are no site ID and site secret.
    * The response should be cached in a transient for 1 day.
* The new `Remote_Controlled_Features` class should include a `register` method that adds a filter for `googlesitekit_is_feature_enabled`.
    * It should return early if the site does not have `site_id` and `site_secret`.
    * For every feature that is included as a key/property in the API response object from the `get_features()` method, it should override the value and set it to `true` or `false` based on that response (every key/property contains an object with an `enabled` property that has that boolean). Any value that is not within the response is not a remotely controlled feature and should remain untouched, i.e. rely on its original value (coming from the `feature-flags.json` file).

Example response:
```json
{
    "userInput": { "enabled": true },
    "widgets.dashboard": { "enabled": false }
}
```

#### includes/Core/Authentication/Google_Proxy.php:

* Add a new constant `FEATURES_URI` with `'/site-management/features/'` value;
* Add a new public method `request( $uri, Credentials $credentials, array $args = array() )`
  * Return a new WP_Error with the `oauth_credentials_not_exist` code if the `$credentials->has()` call returns falsy result;
  * Create a new array `$request_args` that has empty arrays under `headers` and `body` keys;
  * Copy headers and body from the incoming `$args` array, if they are not empty, into appropriate `headers` and `body` properties of the `$request_args`;
  * If the incoming `$args['access_token']` variable is not empty, use it to compose the `Authorization` header (`'Bearer ' . $access_token`) and add it to the `$request_args['headers']` array;
  * Using the incoming `$credentials` variable, get credential values and add it to the `$request_args['body']` array under `site_id` and `site_secret` keys. See an example here:
    https://github.com/google/site-kit-wp/blob/cc9299e728466542513281afa127f173c9aaf521/includes/Core/Authentication/Google_Proxy.php#L112-L119
  * If the incoming `$args['mode']` variable equals to `'async'`, add `'timeout' => 0.01` and `'blocking' => false` items to the `$request_args` array;
  * If the `$args['json_request']` is true, add the appropriate `Content-Type: application/json` header to the `headers` array and encode the body using `wp_json_encode` function;
  * Call the `url` method providing the incoming `$uri` variable and assign the result to the `$url` variable;
  * Call the `wp_remote_post` function using `$url` and `$request_args` variables and assign the result to the `$response` variable;
  * Return the `$response` variable if it is a WP_Error object;
  * Return a new WP_Error object if the response status code is not between 200 and 299 using the `request_failed` error code and passing `array( 'status' => $code )` as error data;
  * Retrieve the response body and decode it using the `json_decode` function into an array;
  * Return a new WP_Error object if the decoded value is falsy or it contains the `error` field. Use the `error` field value as the error code or use the `failed_to_parse_response` code if the decoded value is falsy.
  * Return the decoded value.
* Update `fetch_site_fields`, `unregister_site`, `sync_site_fields`, and `exchange_site_code` methods to use the new `request` method.
* Add a new public method `get_features( Credentials $credentials )`:
  * It should call the `request` method using:
    * The `FEATURES_URI` constant as the uri argument;
    * An array with `'platform' => 'wordpress/google-site-kit'` and `'version' => GOOGLESITEKIT_VERSION` values as the body argument;
    * And the incoming `$credentials` variable as the credentials argument.
  * Return the result of the `request` method call as is.
* Add a new public method `sync_user_input_settings( Credentials $credentials, $access_token, $settings = null )`:
  * It should call the `request` method using:
    * The `USER_INPUT_SETTINGS_URI` constant as the uri argument;
    * The incoming `$credentials` variable as the credentials argument;
    * An array with `'json_request' => true` and the following  values as the `'body'` property:
      * `'settings' => $settings`
      * `'access_token' => $access_token`
      * `'client_user_id' => (string) get_current_user_id()`;
  * Return the result of the `request` method call as is.

#### includes/Core/Authentication/Authentication.php:

* Add a new private method `filter_features_via_proxy( $feature_enabled, $feature_name )`:
  * It should call the `Google_Proxy::get_features` method providing the credentials object;
  * Return non-modified `$feature_enabled` argument if the result of the `Google_Proxy::get_features` method call is a WP_Error object;
  * Cache the result of that method call for 1 day;
  * Return `TRUE` if `$feature_name` is enabled in the features list returned from the proxy server;
  * Otherwise return the original and non-modified `$feature_enabled` variable;
* Add a new hook for the `googlesitekit_is_feature_enabled` filter that calls the `filter_features_via_proxy` method using `$this->get_method_proxy( ... )` helper;
* Rework the `handle_site_code` method to handle a possible WP_Error object returned from the `Google_Proxy::exchange_site_code` method call instead of using try/catch block;

#### includes/Core/Util/User_Input_Settings.php:

* Update the `User_Input_Settings::sync_with_proxy` method to use the new `Google_Proxy::sync_user_input_settings` method instead of manually composing `wp_remote_post` call.

#### includes/Core/Util/Uninstallation.php:

* Remove the try/catch section from the `uninstall` method and just call `$google_proxy->unregister_site( ... );`.

### Test Coverage

* Add tests to check the new `Google_Proxy::request` method;
* Add tests to check the new `Authentication::sync_proxy_features` method.

### Visual Regression Changes

* No visual changes are expected as a result of this ticket.

## QA Brief

* Ensure that the API request to the proxy to check for remote-controlled features is successfully made (e.g. by looking for the transient in the database, should contain an empty array at this point since no features are remote-controlled yet).
* Ensure that the enabled features are correctly controlled by the API response. While the proxy currently returns an empty array, you should be able to modify the transient in the DB directly to e.g. add `userInput => true`. In that case, the `userInput` feature should be enabled.
* Make sure to deactivate the feature override capabilities in the Site Kit tester plugin if you're using that, since it would otherwise conflict with QA here.

## Changelog entry

* Add ability to remotely control enabled feature flags.

**Comment by felixarntz** [comment]
@aaemnnosttv Would be great if you could go over the ACs here.

**Comment by aaemnnosttv** [comment]
Adding a note here that we should also include the list of enabled features as a custom dimension in our anonymous event tracking.

**Comment by aaemnnosttv** [comment]
@felixarntz my first impression here is that the `Feature_Flags` class doesn't need to be aware of `Remote_Controlled_Features`.

There are at least two options to integrating this here which do not require changes to `Feature_Flags`, which as a fully static class seems odd to receive a method for storing an instance of another class:
1. Use `Remote_Controlled_Features` to decorate or otherwise merge on top of the value represented in the `JSON_File` for `feature-flags.json`. That is, `Feature_Flags` would receive a configuration which is already remote-controlled.
1. `Remote_Controlled_Features` leverages the `googlesitekit_is_feature_enabled` filter to control the enabled state. This could be hooked once in the `Plugin`'s `register` method and could use whatever logic it wants for manipulating the enabled state of each feature.

In either case, we'd probably want to pre-fetch the features early on so that calls to `Feature_Flags::enabled` wouldn't be blocking (requesting features on-the-fly).

As for the persistence, what do you think about serve stale cache and refresh the stored value in the background (similar to syncing site fields)? For this reason, it might be better to store it as an option and handle the expiration more manually.

**Comment by felixarntz** [comment]
@aaemnnosttv Thanks for the feedback, good points. I've updated the ACs based on your suggested approach 2. Regarding the asynchronous request, I don't think that's feasible here, as we'll need to also update the option after receiving the request response. So I don't think the non-blocking request approach would work here. For syncing site fields it does because we're simply sending data and don't care about the response. I think since this request would not happen more often than once per day, the one time slightly longer wait should be acceptable.

**Comment by eugene-manuilov** [comment]
@felixarntz @aaemnnosttv this is ready for IBR. I went slightly beyond the requested functionality to refactor the Google_Proxy class a little bit. It will help us to eliminate the existing repeating code and will make it easier to add new methods to call the proxy server endpoints. Plus, it seems like we don't need the `Remote_Controlled_Features` class because that hook fits nicely in the Authentication class itself. Let me know what you think.

**Comment by felixarntz** [comment]
@eugene-manuilov Overall I think the proposed refactoring is a great idea. It nicely reduces a bunch of duplicate code, centralizes proxy request management in the class, and addresses some inconsistencies that have come up as a result of duplicating code for similar tasks (some use `WP_Error`, some throw `Exception`; now, all of them should use `WP_Error`). While doing this requires more work and touches some extra areas, I think it's worth putting in the effort.

There are a few problems with the IB that need to be addressed:
> Return a new WP_Error with the `oauth_credentials_not_exist` code if the $credentials variable is not empty and its `has()` method returns falsy result;

I think this should also return the error if the variable isn't set? We _always_ need to pass credentials. Maybe better, it should be a required parameter.

> Add the `'Content-Type' => 'application/json'` header to the `$request_args['headers']` array and json encode the body using `wp_json_encode` function;

This doesn't work, since most requests to the proxy rely on a URL-encoded body (and have to). The only request that JSON-encodes the body is the one to `/site-management/settings/`. So by default, this should not use JSON in the request - only the response is always JSON. We could introduce an extra method parameter to indicate whether the request body should be sent as JSON and only in that case set the `'Content-Type' => 'application/json'` header and encode the body. Only the new `Google_Proxy::sync_user_input_settings` method would then use that.

> Add a new public method `request( $uri, array $body, Credentials $credentials = null, $access_token = null, $mode = 'sync' )`

This method has a bunch of parameters, and with the other one we'll need (see above) it becomes even more. I think we should restructure it to rely on an array of arguments, so that the order is less relevant. For example, what about if we wanted to have a request with an empty body, but would still need credentials? Calling `request( $uri, array(), $credentials )` would be weird.

How about we use the format `request( $uri, $args )`? This would give us some flexibility and brings it also intuitively in line with e.g. `wp_remote_post`:
* `body` would require an array to be passed. If there is a `headers` argument which includes a `Content-Type: application/json`, we'd JSON-encode the `body` argument.
* `credentials`, `access_token`, and `mode` would be custom arguments which modify `wp_remote_post` arguments as before (e.g. based on `credentials` we'd set extra fields within the `body` argument).
* We could pass a modified version of `$args` through to `wp_remote_post` directly. We'd remove our 3 custom arguments from it and make the adjustments as needed, but then we could pass them through. This way we make this method quite flexible, it's basically a customized proxy-specific layer around `wp_remote_post` - almost like our JS `numFmt` is around `numberFormat`.

> Add a new private method `sync_proxy_features( array $features )`:

I don't like using the term "sync" here, as it makes me think this would send these features to the proxy the same way `sync_site_fields` and `sync_user_input_settings` does. However, it is read-only on the proxy end. I think we should name it `filter_proxy_features` or `filter_features_via_proxy`.

**Comment by eugene-manuilov** [comment]
> I think this should also return the error if the variable isn't set? We always need to pass credentials. Maybe better, it should be a required parameter.

Yep, updated it to be a required parameter.

> This method has a bunch of parameters, and with the other one we'll need (see above) it becomes even more. I think we should restructure it to rely on an array of arguments, so that the order is less relevant. For example, what about if we wanted to have a request with an empty body, but would still need credentials? Calling request( $uri, array(), $credentials ) would be weird.
> 
> How about we use the format request( $uri, $args )? This would give us some flexibility and brings it also intuitively in line with e.g. wp_remote_post: ...

Yep, agree with what you say. Updated the request function to accept `$args` array as the third parameter but left `$credentials` as a second one because it is required.

**Comment by felixarntz** [comment]
@eugene-manuilov One last thing to iterate:
> * Add a new public method `sync_user_input_settings( Credentials $credentials, $access_token, $settings = null )`:
>  * It should call the `request` method using:
>    * The `USER_INPUT_SETTINGS_URI` constant as the uri argument;
>    * The incoming `$credentials` variable as the credentials argument;
>    * An array with `'settings' => $settings`, `'access_token' => $access_token`, and `'client_user_id' => (string) get_current_user_id()` values as the `$args['body']` argument;
>      * Don't forget to JSON encode `$settings` if it is not null using `wp_json_encode` function.

This is still slightly off. The entire `$args['body']` needs to be JSON encoded, not only `$settings`. Since the `request` method however adds body arguments (e.g. `site_id` and `site_secret`), we can't JSON-encode the body before calling `request`.

I think we should overall move the responsibility for JSON-encoding into the `request` function, based on another argument (e.g. `$args['json_request']`). This way the `request` method basically _always_ expects an array (or nothing) for `$args['body']`, and then, if `$args['json_request']` is `true`, it adds the corresponding `Content-Type` header and encodes the entire `$args['body']`.

**Comment by eugene-manuilov** [comment]
Yes, I like it. Updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@eugene-manuilov FYI I added an example response to the ACs. It's slightly updated from before, originally we were thinking of using a simple map of features and booleans, but this has been expanded to a map of features and their objects, to allow for future compatibility if we want to add additional fields. Shouldn't affect the IB though, only the actual implementation.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Tested the below example response:

```json
{
    "userInput": { "enabled": true },
    "widgets.dashboard": { "enabled": false }
}
```

Resulted in the `googlesitekit_remote_features` transient containing a value

```php
array (
  'userInput' => 
  array (
    'enabled' => true,
  ),
  'widgets.dashboard' => 
  array (
    'enabled' => false,
  ),
)
```

And `enabledFeatures` as `["userInput"]`

Noting that the implementation does not use a `Remote_Controlled_Features` class as defined in the ACs, but this was not included in the IB either which @felixarntz approved so assuming that the ACs weren't updated after this change was accepted. The functionality works as expected though, which is the important part.
