### ISSUE TITLE
Test accessing WordPress Admin Bar - from front end & wp-admin

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#254]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Test that Site Kit admin bar menu (G) shows when logged in as admin visiting single post with Search Console stats in frontend
* Test that Site Kit admin bar menu (G) shows when logged in as admin editing single post with Search Console stats in editor
* Without Analytics module active: Test that when hovering over Site Kit admin bar menu, it loads
    * displays post title, "total clicks" and "total impressions"
    * displays Analytics CTA
    * displays "More details" link pointing to detailed page stats
* With Analytics module active: Test that when hovering over Site Kit admin bar menu, it loads
    * displays post title, "total clicks" and "total impressions"
    * displays "total users" and "total sessions"
    * displays "More details" link pointing to detailed page stats

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by adamsilverstein** [comment]
Potential tests:
* Viewing a single post, the Adminbar menu should display on both the front end and admin (edit post) screen, or not - as user appropriate  
* when hovering over menu, dropdoewn should load and display dropdown menu
* dropdown menu should contain string 'Stats for:' and the post title
* dropdown menu should contain ? search console display, analytics CTA
* clicking analytics CTA should take you to analytics setup page (maybe consider adding a helper for this test which repeats wherever we show the Analytics CTA)
* clicking "more details" link should open dashboard with url passed as `permaLink` query parameter (`admin.php?page=googlesitekit-dashboard&permaLink=[ENCODED URL]`)

**Comment by adamsilverstein** [comment]
This passes QA in my testing, moving to Acceptance. 

To test I ran the tests from #597 in interactive mode and watched as they tested the Adminbar dropdown.

**Comment by marrrmarrr** [comment]
Tested with/without GA in FE and in wp-admin. LGTM.
