### ISSUE TITLE
Can't complete setup on a Cloudflare site - redirecting to homepage after signing in

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2544]
## Bug Description

As reported in the [WordPress support forums](https://wordpress.org/support/topic/google-site-kit-continuously-asking-for-sign-in/#post-13799090) one user is encountering setup issues with the plugin redirecting to the users homepage after completing the sign in process. 

## Additional Context

 - Plugin version 1.22.0
 - No issues previously on this site
 - HCapthca and DDOS protection enabled at Cloudflare level
 - The same issue occurs when attempting setup using the Health Check & Troubleshooting mode
 - Using cloudflare in "[Development Mode](https://www.google.com/search?q=cloudflare+developer+mode&oq=cloudflare+developer+mode&aqs=chrome..69i57.7624j1j7&sourceid=chrome&ie=UTF-8)" also results in the same issue 
 - No apparent changes to the users domain or admin path
 - Awaiting proxy check

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@jamesozzie Noticed that this is not assigned to anyone - should this be assigned to you for further testing before going to L1?

**Comment by jamesozzie** [comment]
@bethanylang Good find, I'll self assign that and performing some updated testing.

**Comment by jamesozzie** [comment]
Closing this as I setup a site with Cloudflare last week. Confirmed [all records point to Cloudflare](https://i.imgur.com/Sz1uXNY.png) after changing nameservers on a clean WP install. No issues setting up Site Kit 1.31.0. 

Reset Site Kit on this same successfully site today and [setup proceeded fine](https://i.imgur.com/SzKIoGD.png). This included a setup using a second administrator, in total 2 admins.
