### ISSUE TITLE
Fix unstable E2E tests for write scope permissions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2547]
## Bug Description

In #2301 we disabled a few E2E tests which had been notorious for being unstable on Travis, and seemed to become even more so on GHA. These tests have been marked as skipped with a TODO to address – this is that TODO.

See `tests/e2e/specs/modules/analytics/write-scope-requests.test.js`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No E2E tests should be marked as skipped

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/2632

### Test Coverage

* E2E coverage is increased by un-skipping 2 tests that we disabled in #2301 which should run reliably now

### Visual Regression Changes

* N/A

## QA Brief

* Run the following E2E test command repeatedly to see if the property or profile creation tests will fail at:  
`await page.waitForSelector( '.mdc-dialog--open'` (or at all)
```
npm run test:e2e -- tests/e2e/specs/modules/analytics/write-scope-requests.test.js
```
Each run takes about 45-50 sec or so for me.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by cole10up** [comment]
### QA ⚠️

Tested:
Pulled down latest dev build locally. Started my local env

![image](https://user-images.githubusercontent.com/57115907/106080633-51fc0d80-60cc-11eb-98f9-d5fe7768b63b.png)

Ran the following commands:
`npm install`
`composer install`
`npm run build`
`npm run test:e2e -- tests/e2e/specs/modules/analytics/write-scope-requests.test.js`

Notice the following:
![image](https://user-images.githubusercontent.com/57115907/106080719-7d7ef800-60cc-11eb-9413-e25d930efea4.png)

Tried to restart docker and tried again, same results.

@aaemnnosttv, anything I should change here?

**Comment by cole10up** [comment]
Removing my assignment as I might have an issue with my local causing the above.

**Comment by aaemnnosttv** [comment]
@cole10up That would be expected with a normal production build. For E2E, we need some extra things so it requires a different command for the build: `npm run build:test`.
Try this and give it another shot 👍

**Comment by tofumatt** [comment]
Ran the tests several times, once even during a Google Hangouts call with high CPU usage—all passed except once so looks good to me!

The one failure I got after 5+ runs was a waitForNavigation error that I believe is unrelated:

<img width="701" alt="Screenshot 2021-01-28 at 16 35 39" src="https://user-images.githubusercontent.com/90871/106169161-f9d61180-6186-11eb-8026-16f5b952716b.png">

QA ✅
