### ISSUE TITLE
Cant install the plugin again after that i deleted it from my wordpress site

### ISSUE THREAD

**Issue by atbinsh** [google/site-kit-wp#2548]
## Bug Description

Cant install the plugin again after that i deleted it from my wordpress site it says the plugin already exists on your site

## Steps to reproduce

1. Go to 'add new plugin'
2. Click on 'install'
3. Scroll down to 'google site kit'
4. See error ' Installation failed: Destination folder already exists.'

## Screenshots
![Capture](https://user-images.githubusercontent.com/76187928/102557744-de60ec80-4099-11eb-919f-2de2c8febd81.PNG)

## Additional Context
=
this problem was only for my account i have tried it with three different browsers and devices but it was showing the same error

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist and ensure you get setup successfully. 

Note that this issue can be resolved by removing or renaming the existing Site Kit directory on your website, which exists from your previous install. You'll find it by navigating to `wp-content/plugins/google-site-kit` within your WordPress directory, just .

Feel free to [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) and we can ensure you get the plugin setup successfully.
