### ISSUE TITLE
Add auto-submission of every new URL

### ISSUE THREAD

**Issue by pizienolamitica** [google/site-kit-wp#2552]
## Feature Description

Hi Google team,
How can I automatically submit the new URLs of my site to the Google Search Console?
Bing has built this handy feature with a plugin and an API.

Name of Bing's WordPress plugin: Bing URL Submissions Plugin
Link to the plugin: https://it.wordpress.org/plugins/bing-webmaster-tools/

it would be essential for us web developers and to prevent plagiarism. 
And it would be amazing a similar function on Google Kit for WordPress

Thanks

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for opening a GitHub feature request. 

> How can I automatically submit the new URLs of my site to the Google Search Console?

As mentioned in your [WordPress support topic](https://wordpress.org/support/topic/add-auto-submission-of-every-new-url/) new content added or updated will result in your the WordPress core sitemap using the ping-o-matic service to inform search engines of such updates. 

I will however add this as a feature request which can be review by the team. Be sure to subscribe to this for any updates on this.

**Comment by marrrmarrr** [comment]
Hey @pizienolamitica, thanks for the suggestion! As James mentioned, since a bunch of similar functionality is available via WP core sitemaps, submitting every URL to Google is not on Site Kit's radar for now.
