### ISSUE TITLE
Fix currency metrics overlapping in AdSense page graph

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2555]
Follow-up to #1921: On top of the new AdSense graph, the two currency metric values currently overlap if the numbers are too high:
![Screenshot 2020-12-21 at 09 25 39](https://user-images.githubusercontent.com/3531426/102804480-b067fa80-436e-11eb-8779-e882b6fc8f56.png)

This occurs for the following reasons:
* Currency formatting does not shorten big numbers in the same way we do it for individual numbers (e.g. 35,000 vs 35K).
* The currency itself may take a considerable amount of space.

We have a few alternative options here:
* Make the four columns dynamic width so that those that are too big can be expanded when possible (e.g. in the above case, the Page CTR would always be a more narrow column, allowing other columns to use some extra space). This would be the most bulletproof fix (as it would generally make these data block groups more flexible), but might look a bit ugly - let's try it though and see.
* Introduce a new number formatting style (as follow-up/related to #2200) that somehow mixes `metric` formatting with `currency` formatting to get values such as `US$35K`.
* Display the currency code in a smaller font somehow. This would require some UX explorations.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DataBlock` groups above Site Kit module page graphs (Search Console, Analytics, AdSense) should support flexible widths for cases where numbers are too big. Numbers shouldn't extend their containers.
* For the common case where the numbers fit well, each `DataBlock` should continue to have the same size like today (25%).

## Implementation Brief

* Approve VRT changes in #2557 and fix other checks if any still fails
* Merge #2557

### Test Coverage

* Not needed

### Visual Regression Changes

* Performance metrics tabs on the Adsense page should have dynamic width when its value is too long.

## QA Brief

* Set up the Site Kit plugin on your local;
* Activate AdSense and connect it to an existing account or use the tester plugin to receive fake numbers;
* Go to the AdSense page and check the styles of the performance metrics tabs. It should become wider if there are too long numbers and remain the same if the numbers fit well.

## Changelog entry

* Fix AdSense overview graph UI so that the available space for the total numbers expands as necessary.

**Comment by eugene-manuilov** [comment]
> Make the four columns dynamic width so that those that are too big can be expanded when possible (e.g. in the above case, the Page CTR would always be a more narrow column, allowing other columns to use some extra space). This would be the most bulletproof fix (as it would generally make these data block groups more flexible), but might look a bit ugly - let's try it though and see.

@felixarntz here is my try, let me know if it works for you: https://google.github.io/site-kit-wp/storybook/pull/2557/?path=/story/adsense-module--performance

**Comment by felixarntz** [comment]
@eugene-manuilov LGTM, also per @marrrmarrr. Is it possible to make it still distribute the widths all the same for the cases where everything would fit though? Otherwise we'll get this arguably more weird layout even for cases where it's not needed. 🤔

**Comment by eugene-manuilov** [comment]
@felixarntz how about now? I have updated styles for tabs to have at least 25% of the full width. It makes it look like regular tabs when everything fits nicely and dynamic tabs when something big is shown. Does it look good for you?

**Comment by felixarntz** [comment]
@eugene-manuilov That looks good to me!

**Comment by eugene-manuilov** [comment]
awesome! @felixarntz if you add AC, I can add IB for it.

**Comment by felixarntz** [comment]
@eugene-manuilov Done!

**Comment by eugene-manuilov** [comment]
@felixarntz IB is added.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- The styling on the performance metrics tabs looks good with high amounts.  I checked this on [desktop](https://user-images.githubusercontent.com/73545194/104459232-6e397e00-55e7-11eb-91d2-a34c56cc2a82.png) and [mobile](https://user-images.githubusercontent.com/73545194/104459280-7db8c700-55e7-11eb-9803-7e401259810b.png)
