### ISSUE TITLE
Remove images from legacy setup flow that only applies to special development workflow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2558]
There are a few images in the plugin that only the legacy setup flow (see `assets/js/components/legacy-setup`) uses. Since this flow is only relevant for developers and has been for a long time, in preparation for #2468 we should remove all images that are exclusively used in there.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following images (and their usage) that are exclusively used in the legacy setup flow should be removed:
    * `rocket-body.png`
    * `rocket-cloud.png`
    * `rocket-dust.png`
* The images should simply not be displayed in the component.
* Any related CSS should be removed.

## Implementation Brief

* Remove the three images and their usage from the `WizardStepCompleteSetup` component.
* Remove all CSS related to the `googlesitekit-rocket` classes.
* Make the main column span the full 12 columns now, removing the column that used to contain the rocket animation.
* Merge #2559.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Run Site Kit on a local site with the [Developer Settings plugin](https://sitekit.withgoogle.com/service/download/google-site-kit-dev-settings.zip) active.
* Configure the developer plugin to use a custom GCP app and a public site that your Google account is already a verified owner for, has a Search Console property, and has access to.
* Go through the setup flow (which via the above configuration should use the legacy setup flow instead of the regular proxy setup flow).
* Verify the last step does not show the launching rocket and that there are no (visual) errors.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Local site, with the legacy setup flow,  the last step does not show the launching rocket and that there are no errors.

  ![image](https://user-images.githubusercontent.com/73545194/102881545-fc5a9280-4487-11eb-8ec1-1ddb2036ae4c.png)
