### ISSUE TITLE
Replace deprecated node-sass with dart-sass

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2561]
## Feature Description

From the repo for `node-sass`:

> **Warning:** [LibSass and Node Sass are deprecated](https://sass-lang.com/blog/libsass-is-deprecated).
While they will continue to receive maintenance releases indefinitely, there are no
plans to add additional features or compatibility with any new CSS or Sass features.
Projects that still use it should move onto
[Dart Sass](https://sass-lang.com/dart-sass).

https://github.com/sass/node-sass

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `node-sass` should be removed as a dependency
* The latest version of `sass` should be added as a dependency and configured to be used as the implementation for `sass-loader`

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/2562

### Test Coverage

* N/A

### Visual Regression Changes

* No style changes should result as of this change

## QA Brief

* This is mostly a transparent refactoring but there are some slight differences in the two sass compiling implementations
* The build should continue to run successfully for dev and production builds

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
@felixarntz – just a heads up that this one already has a PR (maybe we should add a label for this to help with prioritization?)

**Comment by felixarntz** [comment]
@aaemnnosttv Let's discuss this in our next standup what would make most sense there for project management.

**Comment by wpdarren** [comment]
@eugene-manuilov @aaemnnosttv I am assuming, that we need to disconnect, reconnect Google account and make sure all the modules are connected as expected or both dev branch and production build. Is that correct?  If not, please provide additional details, as the QAB is a little vague.  Thank you!

**Comment by eugene-manuilov** [comment]
@wpdarren, no need to disconnect or reconnect. Just make sure that styles look the same and nothing has been changed on the UI as a result of this ticket.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Checked SiteKit build on test site including all modules and settings in develop branch and development build. Nothing out of the ordinary appears on the FE.
