### ISSUE TITLE
Refactor store aliases with named exports

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2563]
## Feature Description

We currently export a `STORE_NAME` constant from the `constants.js` module for each module and core data store. When referenced within the context of itself (the same store) we use it with the same name. However, when this constant is imported for use in another store as is often needed, we alias it to be named in a way.

E.g. the `export const STORE_NAME = 'core/site'` would be imported as `import { STORE_NAME as CORE_SITE }`

https://github.com/google/site-kit-wp/blob/8dc8de99f9225f62972c2bb82f67f6e3d39651ad/assets/js/modules/optimize/components/common/UseSnippetInstructions.js#L30-L34

We have _many_ instances of this throughout the codebase, but there are a few common challenges that we face when importing the store name in this way:

* Inconsistency: new engineers often get tripped up by this convention which is somewhat arbitrary as an alias
* Inefficiency: importing `STORE_NAME` is a bit cumbersome since we have so many and especially when the constant is already imported, we lose the ability to leverage auto-import functionality (e.g. using VS Code)

These can both be solved by providing the "external" store name as a named export rather than using an alias.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All registered data store `STORE_NAME` constants should be available to import as named exports
* All `STORE_NAME` **aliases** should be replaced with imports of the named export
    * All un-aliased uses should remain unchanged

## Implementation Brief
* Review occurrences where `STORE_NAME` is aliased and add a new export name where the aliased `STORE_NAME` is defined. For e.g
	```js
	export const STORE_NAME = 'core/site';
	export { STORE_NAME as CORE_SITE };
	```
* Review occurrences where `STORE_NAME` is aliased throughout the app and update them to use the named export instead.
* All un-aliased uses should remain unchanged

### Test Coverage
* To tests needed or to be updated.

### Visual Regression Changes
* There should be no visual changes.

## QA Brief
* Search through the codebase for instances of `STORE_NAME` imported with an alias, e.g. `import { STORE_NAME as `
* There should be none remaining
* Instances where `STORE_NAME` is imported, but *not* as an alias are fine, e.g. `import { STORE_NAME, ... } from`

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@asvinb 

> For e.g
> ```js
> export const STORE_NAME = 'core/site';
> ```
> becomes
> ```js
> export const CORE_SITE = 'core/site';
> ```

We don't want to change the existing `export const STORE_NAME =` exports. This would break the usage of this constant where it would continue to be imported as-is.

We only want to provide an _additional_ export of the `STORE_NAME` using the name it will be referenced by externally.

E.g.
```js
export const STORE_NAME = 'modules/adsense';
export { STORE_NAME as MODULES_ADSENSE };
```

Then the aliases would be updated to use the new named export instead.

**Comment by asvinb** [comment]
Ah! Gotcha @aaemnnosttv . IB updated

**Comment by aaemnnosttv** [comment]
@asvinb the IB is good but doesn't address the second point of the AC: "All STORE_NAME aliases should be replaced with imports of the named export" which is the main point of this issue 🙂

**Comment by asvinb** [comment]
Updated @aaemnnosttv

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@johnPhillips I've merged the first PR to avoid an endless mega PR. There are a handful of updates left to make. Would you please open a new PR for these last few instances?

**Comment by aaemnnosttv** [comment]
Looks like one more instance slipped through the original PR. Seems to be the _real_ last instance though 😄

**Comment by eugene-manuilov** [comment]
QA :warning: Found a few more places:

https://github.com/google/site-kit-wp/blob/026f7d3e022356335c420d276fdd31366ea6342c/assets/js/components/setup/CompatibilityChecks/checks.js#L20

https://github.com/google/site-kit-wp/blob/026f7d3e022356335c420d276fdd31366ea6342c/assets/js/components/setup/CompatibilityChecks/CompatibilityErrorNotice.js#L31

https://github.com/google/site-kit-wp/blob/026f7d3e022356335c420d276fdd31366ea6342c/assets/js/components/setup/CompatibilityChecks/index.js#L38

**Comment by asvinb** [comment]
QA ❌ 
@johnPhillips I see there is one instance that has been missed:
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/optimize/components/setup/SetupMain.js#L37

Sending ticket back to you :)

**Comment by asvinb** [comment]
### QA: ✅ 
- No more STORE_NAME aliases.
