### ISSUE TITLE
Не могу выбрать другой аккаунт

### ISSUE THREAD

**Issue by busfase** [google/site-kit-wp#2565]
## Bug Description

Search console и Adsense зарегистрированы на разные аккаунты. Если подключен Search console на первый, не могу подключить adsense, который зарегистрирован на другой аккаунт.
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@busfase Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Note that it's recommended to use the same Google account to connect all services from the same WordPress administrator account. You can however provide access to the different Google services at service level, such as AdSense or Analytics.

**Comment by busfase** [comment]
Oh, thanks a lot. I shared my rights and it all worked! Good luck to you!
