### ISSUE TITLE
Only menu items translated for some languages - No dashboard string translations rendering

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2566]
One user reported [language translation issues](https://wordpress.org/support/topic/argh-google/) in the support forums, following on from #2171. From testing on support side translations strings are not consistently working rendering as expected, with only the menu items translated in some cases, despite languages being 100% or almost 100% complte. 

The user who reported this is a Danish translation contributor, with more information in the [supporting WordPress topic.](https://wordpress.org/support/topic/argh-google/) 

[Video created a video](https://recordit.co/ciuyxohXPJ) showing this behavior on one of the sites from SK support. You'll see the below:
- Language switched between German, Portuguese and English in both my WordPress general settings & user profile
- Updating from 1.22.0 to 1.23.0 (the issue persists with both plugin versions)

[Another video](https://recordit.co/ffd2xw52W4) showing Spanish fully translated with Indonesian only translating the menu items. 

Indonesian Bahasa - Only tab translated  (Listed as 80% translated)
Spanish - no issue (Listed as 100% translated)
Danish - No translations  (Listed as 100% translated)
Portuguese Brazilian - Only tab translated  (Listed as 80% translated)

![ads](https://user-images.githubusercontent.com/41326532/103085194-e3152b80-45d8-11eb-8fe7-2519596cba0f.gif)

## Additional Context

 - Issue occurs on both sites tested in support
 - Occurs on one site from 1.22.0 and also after upgrading to 1.23.0
 - One site did have translation updates available although after upgrading and switching languages the same issue persists
 - Tested on German, Portuguese (Brazil), Spanish and Indonesian (Bahasa)
 - In each case on support side only the "Settings" tab button is translated
 - After deactivating Site Kit on one of the problematic sites and activating once more translations worked until they were switched once more - with all translations then reverting to English (apart from the menu item)
 - No caching plugins active on the 2 sites tested in support
 - Occurs on support side with just Site Kit and AMP plugins actve (SH info provided below)
 - On support side user language is set to WordPress default

<details>
  <summary>Support side Site Health info</summary>
  
``
### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/vhosts/plastiskip.com/httpdocs
wordpress_size: 132.37 MB (138798900 bytes)
uploads_path: /var/www/vhosts/plastiskip.com/httpdocs/wp-content/uploads
uploads_size: 170.83 MB (179128225 bytes)
themes_path: /var/www/vhosts/plastiskip.com/httpdocs/wp-content/themes
themes_size: 122.42 MB (128367363 bytes)
plugins_path: /var/www/vhosts/plastiskip.com/httpdocs/wp-content/plugins
plugins_size: 388.05 MB (406901925 bytes)
database_size: 75.52 MB (79186604 bytes)
total_size: 889.19 MB (932383017 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Twenty Nineteen (twentynineteen)
version: 1.7 (latest version: 1.9)
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, amp, widgets
theme_path: /var/www/vhosts/plastiskip.com/httpdocs/wp-content/themes/twentynineteen
auto_update: Disabled

### wp-themes-inactive (13) ###

Divi: version: 4.6.6, author: Elegant Themes, Auto-updates disabled
AMPFace: version: 1.6.0, author: James Ozzie Osborne, Auto-updates disabled
Ascend: version: 1.4.6, author: Kadence Themes, Auto-updates disabled
Astra: version: 2.5.5, author: Brainstorm Force (latest version: 2.6.2), Auto-updates disabled
Blocksy: version: 1.7.47, author: CreativeThemes (latest version: 1.7.57), Auto-updates disabled
Noor: version: 5.6.02, author: PixelDima, Auto-updates disabled
OceanWP: version: 2.0.3, author: Nick, Auto-updates disabled
Pinnacle: version: 1.7.12, author: Kadence WP, Auto-updates disabled
Pixwell: version: 5.7, author: Theme-Ruby, Auto-updates disabled
Reco Child: author: EstudioPatagon, version: (undefined), Auto-updates disabled
Reco: version: 4.5.5, author: EstudioPatagon, Auto-updates disabled
Twenty Twenty: version: 1.5, author: the WordPress team (latest version: 1.6), Auto-updates disabled
Twenty Twenty-One: version: 1.0, author: the WordPress team (latest version: 1.1), Auto-updates disabled

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.7.2

### wp-plugins-active (2) ###

AMP: version: 2.0.9, author: AMP Project Contributors, Auto-updates disabled
Site Kit by Google: version: 1.23.0, author: Google, Auto-updates disabled

### wp-plugins-inactive (66) ###

Advanced Custom Fields PRO: version: 5.9.3, author: Elliot Condon, Auto-updates disabled
Advanced WordPress Reset: version: 1.1.1, author: Younes JFR., Auto-updates disabled
AMP Badge: version: 1.0.0, author: James Osborne, Auto-updates disabled
AMP Popup: author: Your Name Here, version: (undefined), Auto-updates disabled
Antispam Bee: version: 2.9.3, author: pluginkollektiv, Auto-updates disabled
Asset CleanUp: Page Speed Booster: version: 1.3.7.1, author: Gabriel Livan (latest version: 1.3.7.2), Auto-updates disabled
Autoptimize: version: 2.7.8, author: Frank Goossens (futtta) (latest version: 2.8.1), Auto-updates disabled
bbPress: version: 2.6.6, author: The bbPress Contributors, Auto-updates disabled
Classic Editor: version: 1.6, author: WordPress Contributors, Auto-updates disabled
CoBlocks: version: 2.5.0, author: GoDaddy (latest version: 2.5.3), Auto-updates disabled
Complianz | GDPR/CCPA Cookie Consent: version: 4.8.2, author: Really Simple Plugins, Auto-updates disabled
Contact Form 7: version: 5.3, author: Takayuki Miyoshi (latest version: 5.3.2), Auto-updates disabled
Dima Take Action: version: 1.0.5, author: PixelDima, Auto-updates disabled
Disable plugins / themes updates: version: 1.1.1, author: Vincent Guesné, Auto-updates disabled
Disable REST API: version: 1.5.1, author: Dave McHale, Auto-updates disabled
Disable REST API for Real: version: 2.1.1, author: Samuel Aguilera, Auto-updates disabled
Easy Digital Downloads: version: 2.9.26, author: Sandhills Development, LLC, Auto-updates disabled
Elementor: version: 3.0.15, author: Elementor.com, Auto-updates disabled
Envato Market: version: 2.0.1, author: Envato, Auto-updates disabled
Export All URLs: version: 4.1, author: Atlas Gondal, Auto-updates disabled
Fast Velocity Minify: version: 2.8.9, author: Raul Peixoto, Auto-updates disabled
hCaptcha for Forms and More: version: 1.6.3, author: hCaptcha, Auto-updates disabled
Health Check & Troubleshooting: version: 1.4.5, author: The WordPress.org community, Auto-updates disabled
Instant Indexing: version: 1.0.0, author: Rank Math, Auto-updates disabled
iThemes Security: version: 7.9.0, author: iThemes, Auto-updates disabled
Jetpack by WordPress.com: version: 9.0.2, author: Automattic (latest version: 9.2.1), Auto-updates disabled
Kadence Blocks – Gutenberg Blocks for Page Builder Features: version: 1.9.7, author: Kadence WP (latest version: 1.9.9), Auto-updates disabled
LiteSpeed Cache: version: 3.6, author: LiteSpeed Technologies (latest version: 3.6.1), Auto-updates disabled
LuckyWP Table of Contents: version: 2.1.4, author: LuckyWP, Auto-updates disabled
Noor Assistant: version: 3.1.13, author: PixelDima, Auto-updates disabled
Ocean Extra: version: 1.6.8, author: OceanWP, Auto-updates disabled
Ocean Social Sharing: version: 1.1.0, author: OceanWP, Auto-updates disabled
Pixwell Core: version: 5.7, author: Theme-Ruby, Auto-updates disabled
Plugins Garbage Collector (Database Cleanup): version: 0.12, author: Vladimir Garagulya, Auto-updates disabled
Pretty Links: version: 3.2.1, author: Pretty Links, Auto-updates disabled
PWA: version: 0.5.0, author: PWA Plugin Contributors, Auto-updates disabled
Rank Math SEO: version: 1.0.52.1, author: Rank Math (latest version: 1.0.55), Auto-updates disabled
Reco Theme Functions: version: 4.5.5, author: Estudio Patagon, Auto-updates disabled
Redux: version: 4.1.23, author: Redux.io + Dovy Paukstys (latest version: 4.1.24), Auto-updates disabled
Salt Shaker: version: 1.2.7, author: Nagdy, Auto-updates disabled
Scripts-To-Footer: version: 0.6.4.1, author: Joshua David Nelson, Auto-updates disabled
Stop Spammers: version: 2020.5.1, author: Trumani (latest version: 2021.1), Auto-updates disabled
Thrive Architect: version: 2.6.2.1, author: <a href="http://www.thrivethemes.com">Thrive Themes</a>, Auto-updates disabled
Thrive Product Manager: version: 1.2.4, author: Thrive Themes, Auto-updates disabled
TranslatePress - Multilingual: version: 1.9.0, author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban, Auto-updates disabled
Virtue/Ascend/Pinnacle Toolkit: version: 4.9.6, author: Kadence WP, Auto-updates disabled
Web Stories: version: 1.1.0, author: Google (latest version: 1.2.1), Auto-updates disabled
WooCommerce: version: 4.7.1, author: Automattic (latest version: 4.8.0), Auto-updates disabled
WooSidebars: version: 1.4.5, author: WooCommerce, Auto-updates disabled
Wordfence Security: version: 7.4.14, author: Wordfence, Auto-updates disabled
WordPress Zero Spam: version: 4.10.2, author: Ben Marshall, Auto-updates disabled
WP-DBManager: version: 2.80.3, author: Lester 'GaMerZ' Chan, Auto-updates disabled
WP-Sweep: version: 1.1.3, author: Lester 'GaMerZ' Chan, Auto-updates disabled
WP All Import: version: 3.5.6, author: Soflyy, Auto-updates disabled
WPBakery Page Builder: version: 6.4.2, author: Michael M - WPBakery.com, Auto-updates disabled
WP Cerber Security, Anti-spam & Malware Scan: version: 8.6.7, author: Cerber Tech Inc. (latest version: 8.7), Auto-updates disabled
WP Content Copy Protection & No Right Click: version: 3.1.3, author: wp-buy, Auto-updates disabled
WP Crop Stop: version: 0.1.2, author: Alex Egorov, Auto-updates disabled
WP External Links: version: 2.47, author: WebFactory Ltd, Auto-updates disabled
WPForms Lite: version: 1.6.3.1, author: WPForms (latest version: 1.6.4), Auto-updates disabled
WPGlobus: version: 2.6.0, author: WPGlobus, Auto-updates disabled
WPML Multilingual CMS: version: 4.4.4, author: OnTheGoSystems, Auto-updates disabled
WP Rocket: version: 3.7.5, author: WP Media, Auto-updates disabled
Yoast SEO: version: 15.1.1, author: Team Yoast (latest version: 15.5), Auto-updates disabled
Yoast SEO Multilingual: version: 1.2.4, author: OnTheGoSystems, Auto-updates disabled
Yoast SEO Premium: version: 15.1.2, author: Team Yoast, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 16M
upload_max_filesize: 16M
max_effective_size: 16 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 7 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 1536
	imagick::RESOURCETYPE_MAP: 7 GB
	imagick::RESOURCETYPE_MEMORY: 4 GB
	imagick::RESOURCETYPE_THREAD: 3
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.07

### wp-server ###

server_architecture: Linux 3.10.0-957.5.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.2.34 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 16M
php_post_max_size: 16M
curl_version: 7.29.0 NSS/3.44
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.5.68-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/vhosts/plastiskip.com/httpdocs/wp-content
WP_PLUGIN_DIR: /var/www/vhosts/plastiskip.com/httpdocs/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### google-site-kit ###

version: 1.23.0
php_version: 7.2.34
wp_version: 5.6
reference_url: https://plastiskip.com
amp_mode: secondary
site_status: connected-site
user_status: authenticated
connected_user_count: 1
active_modules: site-verification, search-console, analytics
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_view_module_details: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_publish_posts: ✅
search_console_property: https://plastiskip.com/
analytics_account_id: 1838•••••
analytics_property_id: UA-1838•••••••
analytics_profile_id: 2335•••••
analytics_use_snippet: yes

### amp_wp ###

amp_mode_enabled: transitional
amp_reader_theme: legacy
amp_templates_enabled: post, page, attachment, is_singular, is_front_page, is_home, is_archive, is_author, is_date, is_search, is_404, is_category, is_tag
amp_serve_all_templates: true
amp_css_transient_caching_disabled: false
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 232
amp_css_transient_caching_time_series: 
	20201215: 0
	20201216: 21
	20201217: 49
	20201218: 65
	20201219: 67
	20201220: 68
	20201221: 68
	20201222: 118
	20201223: 171
amp_libxml_version: 2.9.1

``
 
</details>
 
![image](https://user-images.githubusercontent.com/41326532/103083370-2de07480-45d4-11eb-9016-dd0b682dd05d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
@jamesozzie looks like something wrong happened on the WordPress side itself and translations files got messed up on the server. I have logged into one of your sites and deleted downloaded translations via ssh, then switched back to German, downloaded translations again and it starts working. Can you try it on your end and let me know if it works correctly now?

**Comment by jamesozzie** [comment]
The user unfortunately gave up on the plugin, therefore had to update to provide.
