### ISSUE TITLE
Test Key User Flows for Admin | Editor WP Dashboard

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#257]
Set up Test Key User Flows for Admin|Editor WP Dashboard
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* n/a

## Implementation Brief

* n/a

## Changelog entry

* Test Key User Flows for Admin|Editor WP Dashboard

**Comment by adamsilverstein** [comment]
Closing this in favor of https://github.com/google/site-kit-wp/issues/253 where we will cover WP Dashboard all user types
