### ISSUE TITLE
Use Google CDN for serving fonts, libraries etc

### ISSUE THREAD

**Issue by OC2PS** [google/site-kit-wp#2575]
## Feature Description

As a dominant online service provider, Google serves a large proportion of the online population every day. Through the provision of many services, Google sends various fonts and libraries (e.g. jQuery) to these users' devices, where they are cached. Often, these same libraries are needed by other websites, including WordPress websites running Site Kit. However, these websites, not recognizing the already downloaded libraries/fonts etc, then proceed to download these again, from their own servers. This wastes bandwidth, disk space, and makes for a poor user experience by slowing down the websites. Site Kit can solve some of this by switching these websites to downloading libraries/fonts directly from Google CDN. This way, the user devices will recognize that they already have downloaded/cached these libraries/fonts, and wouldn't need to download again.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
When it comes to jQuery this is prepackaged with WordPress, with no duplicate jQuery scripts requested by Site Kit. This is served from your WordPress install as can be seen in [this WordPress developer article](https://developer.wordpress.org/reference/functions/wp_enqueue_script/#default-scripts-and-js-libraries-included-and-registered-by-wordpress). 

In relation to Google Fonts there is an open feature request ([#208](https://github.com/google/site-kit-wp/issues/208)) in relation to integration within Site Kit. Feel free to include any input to that issue or subscribe for further updates. 

Note that using the service at present it’s recommended to implement by making use of the suggested methods at Google Fonts (<link> tag or @import), by requesting the font files from https://fonts.googleapis.com. If you would prefer to use a locally hosted version of any Google Font be sure to mention this preference with the existing GitHub issue.

**Comment by OC2PS** [comment]
@jamesozzie The rationale for closing this doesn't make sense.

I am aware that jQuery is packaged with WordPress, and have indicated as much in the original post. The point is, rather than serve jQuery from the site (WordPress), Site Kit can give an option to serve jQuery from Google CDN, thereby increasing site speed, improving user experience, and reducing internet bandwidth usage.

Again, to clarify, I am not saying Site Kit duplicates jQuery usage. The point of this ticket is that whenever anything in WordPress needs jQuery, that should be served from Google CDN (or, practically, in 90% users' case, from their browser's cache, since they probably already have a copy of Google CDN's jQuery cached).

**Comment by ThierryA** [comment]
@OC2PS these are great suggestions, ideally having all resources loading from CDNs would definitely be a good improvement. With that said, I can see how automatically mapping assets to CDN would open a set of important challenges to ensure that user sites don't break (first thing that comes to mind is dependencies management, version conflicts etc.). 

This kind of "advanced" performance automating is currently not on Site Kit roadmap but happy to keep this issue open which will be revisited from time to time. In an ideal world, I would love to see performance/caching plugins taking a closer look at such features.

**Comment by marrrmarrr** [comment]
Hi @OC2PS, thanks for the suggestion! As Thierry mentioned already, we're focussing on making it as easy as possible for the slightly less savvy users to make the most of their WP sites, so this type of advanced functionality is not on Site Kit's radar for the time being.
