### ISSUE TITLE
One-click Google CDN

### ISSUE THREAD

**Issue by OC2PS** [google/site-kit-wp#2576]
## Feature Description

CDNs perform a great service by caching content at the "edge" and serving from there. I would love to use Google CDN for my site, but the process of setting it up is so darn technical (as opposed to setting up, say CloudFlare).

CloudFlare setup is usually a single click setup, often integrated into the hosting company's cPanel or custom software. Occasionally, (if the DNS is elsewhere), it requires slight manual intervention to the extent to adding a CNAME record.

Google CDN, on the other hand, requires technical knowledge and a series of manual steps. It would be nice if Site Kit were to offer “one click” Google CDN set up for WordPress websites.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for the suggestion. With many complexities involved for a Google or Site Kit CDN this isn’t something we are considering at present, with many third party plugins providing such functionality.

While there are no plans to create a public Google CDN have you considered using [AMP](http://amp.dev/)? AMP content is eligible to be served from AMP Cache, with AMP scripts and components all served from a CDN. There is also an [AMP plugin](https://wordpress.org/plugins/amp/) that makes the process of adopting AMP much easier than manually applying AMP to your site.
