### ISSUE TITLE
Ensure the toggle to allow Site Kit to place Analytics tracking code on a users site remains once they've disconnected Tag Manager (with an existing Analytics snippet tag)

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2579]
## Bug Description

At present one typical Site Kit setup scenario may be where a user first connects Analytics, allowing Site Kit to insert the tracking snippet. They may then connect the Tag Manager module, with may contain an existing Analytics tag, which Site Kit then switches to. 

If a user then disconnects Tag Manager the plugin reverts to the Analytics module UI property alone. While the toggle to "[Let Site Kit place code on your site](https://i.imgur.com/5S5sPME.png) may have been initially on before connecting Tag Manager the toggle is then off, resulting in no Analytics data being captured. 

https://i.imgur.com/Fw9IkkT.png

Some possible solutions to ensure users have Analytics tracking code remaining on their site (if chosen) include:

1. **Adding a notice when disconnecting Tag Manager**: This must also account for users who disable the Tag Manager configuration to allow Site Kit to insert Tag Manager code. 
2. **Ensure the toggle to allow Site Kit insert Analytics code is on by default**: One consideration with this solution is the user may have intentionally disabled the toggle before activating Tag Manager. This would be then reverting to a configuration the user chose not to select. 

## Steps to reproduce

1. Connect the Analytics module and allow SK to insert the Analytics tracking snippet
2. Connect the Tag Manager module to a container with an existing Analytics Universal Tracking snippet 
3. Site Kit switches to the Tag Manager placed UA snippet
4. Disconnect the Tag Manager module
5. The Analytics snippet once again becomes active although the default configuration is that Site Kit does not insert the Analytics tracking snippet, resulting in a user potentially not have any Analytics data

## Additional Context

 - [Video demonstrating issue](https://recordit.co/Cj5QXfLYY3)
 - While there have been no support topics open in relation to this there is a possibility of users not being aware of the status of their Analytics snippet. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should store a flag option for the Analytics module in case the Analytics `useSnippet` option gets changed from `true` to `false` due to the user having enabled Tag Manager with a matching Analytics tag.
* Then, if the Tag Manager module later gets disconnected, in case that new Analytics flag is enabled, `useSnippet` should be "restored" to `true`.

#### Analytics module:

* Apply the `googlesitekit_analytics_can_use_snippet` filter to the result of the `Analytics\Tag_Guard::can_activate` method.
* Add `'canUseSnippet' => true,` to the Analytics settings default values:
  https://github.com/google/site-kit-wp/blob/622f0bd76d21e752e4c2b1a5514c6d02b4f8daf5/includes/Modules/Analytics/Settings.php#L157-L169
* Add the `googlesitekit_analytics_can_use_snippet` filter to the option filter in the Analytics settings class. It should work similarly to the `adsenseLinked` property but set `canUseSnippet` one.
  https://github.com/google/site-kit-wp/blob/622f0bd76d21e752e4c2b1a5514c6d02b4f8daf5/includes/Modules/Analytics/Settings.php#L63-L132
* Add `canUseSnippet` slug to the setting slugs in the `assets/js/modules/analytics/datastore/base.js` file.
* Get `canUseSnippet` setting using the `getCanUseSnippet` selector in the `UseSnippetSwitch` component. If the value is false, then disable the Switch component and display a message that the Analytics snippet is controlled by another module.
* Update the snippet section in the `SettingsView` component to display that the snippet is controlled by another module when `canUseSnippet` is `false`.
* Remove `setUseSnippet( false )` line in the `useExistingTagEffect` effect:
  https://github.com/google/site-kit-wp/blob/622f0bd76d21e752e4c2b1a5514c6d02b4f8daf5/assets/js/modules/analytics/hooks/useExistingTagEffect.js#L89

#### Tag Manager module:

* Add `'gaPropertyID' => ''` and `'gaAmpPropertyID' => ''`  to the Tag Manager settings default values:
  https://github.com/google/site-kit-wp/blob/e0727e8c420b9217311324ece18576cc53085d88/includes/Modules/Tag_Manager/Settings.php#L74-L84
* Add `gaPropertyID` and `gaAmpPropertyID` slugs to the setting slugs in the `assets/js/modules/tagmanager/datastore/base.js` file.
* Update the `selectContainerByID` selector from the Tag Manager datastore to set the appropriate Analytics property ID. Use the `getLiveContainerAnalyticsTag` selector to receive a property ID for a container.
  https://github.com/google/site-kit-wp/blob/e0727e8c420b9217311324ece18576cc53085d88/assets/js/modules/tagmanager/datastore/containers.js#L150-L158
* Add a new private method `can_analytics_use_snippet` to the `Tag_Manager` module class:
  * It should accept a single argument indicating the original state of the `canUseSnippet` property from the Analytics module.
  * Return `false` if either `gaPropertyID` or `gaAmpPropertyID` setting isn't empty (based on the current AMP mode) and the `useSnippet` setting of the Tag Manager module is truthy.
  * Otherwise just return the original value.
* Add a new hook for the `googlesitekit_analytics_can_use_snippet` filter that calls the private `can_analytics_use_snippet` method (use `$this->get_method_proxy` to use private method as a hook for a filter).

### Test Coverage

* Update the `SettingsTest` classes for Analytics and Tag Manager modules to account for the aforementioned changes.
* Update the `Tag_GuardTest` class for the Analytics module to test the new filter added to the `can_activate` method.

### Visual Regression Changes

* As a result of this change, the Analytics "use snippet" control should be disabled if the Tag Manager contains a container with the Analytics account.

## QA Brief

1. Connect the Analytics module and allow SK to insert the Analytics tracking snippet.
2. Connect the Tag Manager module to a container with an existing Analytics Universal Tracking snippet.
3. Site Kit switches to the Tag Manager placed UA snippet.
4. Disconnect the Tag Manager module.
5. The Analytics snippet from the Analytics module is once again inserted.

## Changelog entry

* Fix problem where Analytics snippet placement would not be re-instated after disconnecting Tag Manager module when it was previously taking care of the Analytics tag.

**Comment by eugene-manuilov** [comment]
@felixarntz IB is ready for review. I have outlined a slightly different idea of how to solve this issue. Please, let me know if you don't like it or you want to change something and I'll update it.

**Comment by felixarntz** [comment]
@eugene-manuilov I like the overall suggested approach from your IB, it's a clean alternative. I have one suggestion though: How about, instead of calling the GTM API from the server and caching the result in a transient, we actually store the found Analytics tag property ID in an actual GTM option? We already fetch it during GTM setup/settings, so we could set it as an option on the client, and it would be saved in the regular option update.

This way, we don't need to make requests on demand from the server, but we can rely on the option for the GTM Analytics tag (which is based on the container selected) and whether it's the same tag like the one used in Analytics.

**Comment by eugene-manuilov** [comment]
> How about, instead of calling the GTM API from the server and caching the result in a transient, we actually store the found Analytics tag property ID in an actual GTM option? ... This way, we don't need to make requests on demand from the server, but we can rely on the option for the GTM Analytics tag (which is based on the container selected) and whether it's the same tag like the one used in Analytics.

Yes, it a good suggestion too, but unfortunately I don't think it's going to work well because we won't be able to correctly detect a situation when someone removes the Analytics container in the Tag Manager console.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> Yes, it's a good suggestion too, but unfortunately I don't think it's going to work well because we won't be able to correctly detect a situation when someone removes the Analytics container in the Tag Manager console.

That is a good point. However, this is a much wider-reaching issue that has been relevant in Site Kit's behavior since day 1. All sorts of detections currently only happen in the setup flow or settings flow, which also applies to detect existing tags etc.

Rather than addressing one piece of the problem here, I'd rather have us follow our existing approach where the detection happens in JS during setup/settings editing for this particular issue. It addresses the overall problem here, since that option would get removed when GTM is disconnected. So I'd prefer if we went with the option approach here, controlled by JS.

Regarding the broader problem, we should think about how we can come up with a solid approach there which we can use to address the problem across all areas. Let's set up a meeting to discuss next week (cc @aaemnnosttv).

**Comment by eugene-manuilov** [comment]
Sounds good, @felixarntz. IB is updated. Could you please check it again?

**Comment by felixarntz** [comment]
IB ✅

**Comment by benbowler** [comment]
I've worked through the IB but the `canUseSnippet` setting is not being set correctly.

**Comment by eugene-manuilov** [comment]
Probably because you check the wrong settings in the `can_analytics_use_snippet` method, no? :thinking: 

https://github.com/google/site-kit-wp/blob/b1b7fdd5c77b29d38a58c6e4a5efa12c556c2b9d/includes/Modules/Tag_Manager.php#L657-L659

**Comment by benbowler** [comment]
Hey @eugene-manuilov, I've corrected above but the implementation doesn't solve the issue. Digging into the flow I can repeat the test scenario with one of my personal websites with and active GTM setup. I can see that this code:

https://github.com/google/site-kit-wp/blob/57159a5e0ad5262fb997c8de833dfe833de49fe8/assets/js/modules/tagmanager/datastore/containers.js#L151-L166

Never runs if you have a single google analytics property set up with Analytics before activating GTM with a duplicate code.


https://user-images.githubusercontent.com/119352/107380517-d8a9e500-6ae5-11eb-9eaf-aaeeb71380d9.mp4



My solution would be to create a new actions called something like `setGaProperyID` that would be called from the same useEffect in `assets/js/modules/tagmanager/hooks/useExistingTagEffect.js` but when  `analyticsModuleActive && singleAnalyticsPropertyID` instead.

```
	// Set the containerId and related settings when there is a single analytics property previously set up with Google Analytics.
	if ( analyticsModuleActive && singleAnalyticsPropertyID ) {
		console.log( 'existingTag', existingTag );
		await setGaPropertyID( existingTag );
	}
```

What do you think of this addition?

**Comment by eugene-manuilov** [comment]
Hi @benbowler. 

> My solution would be to create a new action called something like setGaProperyID that would be called from the same useEffect in assets/js/modules/tagmanager/hooks/useExistingTagEffect.js but when analyticsModuleActive && singleAnalyticsPropertyID instead

I don't think it will help because it looks like we also need to set GA property IDs in AMPContainerSelect and WebContainerSelect components  :thinking:. Can you try adding a new `useEffect` hook to these components that sets the appropriate GA property ID whenever the corresponding container ID is changed? Something like this would work:

```javascript
// assets/js/modules/tagmanager/components/common/WebContainerSelect.js:

const gaPropertyID = useSelect( ( select ) => select( STORE_NAME ).getLiveContainerAnalyticsPropertyID( accountID, containerID ) );

const { ..., setGaPropertyID } = useDispatch( STORE_NAME );
useEffect( () => {
    setGaPropertyID( gaPropertyID );
}, [ containerID ] );
```

Let me know if it helps.

**Comment by benbowler** [comment]
I've implemented the above, one other issue I've come across is that because the hook on `canUseSnippet` only happens on the PHP side, if you update the Tag Manager settings then immediately click to Analytics it doesn't update until your refresh:


https://user-images.githubusercontent.com/119352/107782443-fd4dc900-6d40-11eb-9d83-60e85d109554.mp4

**Comment by eugene-manuilov** [comment]
@benbowler let's probably use `setCanUseSnippet` function from the Analytics settings datastore to set its state manually when selected containers are changed in GTM settings. No need to submit this change, we just need to pretend it has changed before the user refreshes the page.

cc @felixarntz

**Comment by aaemnnosttv** [comment]
@felixarntz I don't see anything in the IB about the customization of the disconnect modal which would likely require significant changes to implement. Is this still a requirement?

**Comment by cole10up** [comment]
### **QA ✅**

**Tested**

1. Connected Analytics module with the snippet inserted
2. Connected Tag Manager module with a container using an existing universal snippet
3. Disconnected Tag Manager module

Noticed:
Analytics module functions just fine, tracking snippet is inserted - no issues.
