### ISSUE TITLE
Introduce factory for Analytics response mock data

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2584]
After #2236, the `module-analytics-components.stories.js` file is now full of inlined fixtures, which is due to the mock data being dependent on the `referenceDate` used for the story. While we could have continued to use fixtures, doing so is in another way confusing as it decouples the two pieces entirely and obfuscates that they are connected.

(#2425 added some new fixtures for this, so it's a bit mixed up now between fixtures and inlined responses. Either way, none of this is what we should end up with, so let's improve this here.)

We should introduce an Analytics-specific test utility, which generates Analytics response data.

We should also think about how this would affect request args definition in Storybook and tests - whether we should use fixtures there, factories, or just inline them (since those are _a lot_ simpler than response data).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a function like `getAnalyticsMockResponse( requestArgs, options )` which generates a full Analytics response for the given request `requestArgs`. `options` would allow for additional tweaks to the response,_ if needed_ (TBD during IB / implementation).
    * This can basically replicate logic which we already have in PHP via the Site Kit tester plugin. It'll be based on some hard-coded mock values, combined with logic to arrange them accordingly to get the correct response format for the request.
    * The function should respect request arguments `startDate`, `endDate`, `compareStartDate`, `compareEndDate`, `metrics`, `dimensions`, `orderby`, and `limit`, all of which affect the format of the response. Other arguments like `url` or `dimensionFilters` don't need to explicitly be supported: While they realistically would result in different numbers being returned, we only care about returning the proper response format for the request in this mock function.
    * The function should support the following metrics for now (in any combination within the `metrics` argument):
        * `ga:users` (type `INTEGER`)
        * `ga:newUsers` (type `INTEGER`)
        * `ga:sessions` (type `INTEGER`)
        * `ga:goalCompletionsAll` (type `INTEGER`)
        * `ga:pageviews` (type `INTEGER`)
        * `ga:uniquePageviews` (type `INTEGER`)
        * `ga:bounceRate` (type `PERCENT`)
        * `ga:avgSessionDuration` (type `TIME`)
        * `ga:adsensePageImpressions` (type `INTEGER`)
        * `ga:adsenseCTR` (type `PERCENT`)
        * `ga:adsenseRevenue` (type `CURRENCY`)
        * `ga:adsenseECPM` (type `CURRENCY`)
    * The function should support only the following _specific_ `dimensions` values for now:
        * `[ 'ga:date' ]`
        * `[ 'ga:channelGrouping' ]`
        * `[ 'ga:pageTitle', 'ga:pagePath' ]`
* The Analytics Storybook stories should use the above function instead of inlining response mock data.
* All Analytics fixtures for report data or args should be deleted from the plugin.

## Implementation Brief

* Add `getAnalyticsMockResponse( requestArgs )` function in a new file within `assets/js/modules/analytics/util`.
* Implement a `dummyMetrics` const which is a map of an Analytics metric and an array of 15 values for it. Cover all metrics required per the ACs. The `Analytics_Data_Provider` PHP class from the Site Kit tester plugin currently only fully supports AdSense metric values, but adding values for the other Analytics metrics should be fairly trivial.
* Re-implement logic based on the `Analytics_Data_Provider` PHP class from the Site Kit tester plugin in the new JS function to create a mock Analytics API response in the correct format.
    * Add support for altering the mock response based on the request arguments listed in the ACs, all of which are also covered by the PHP implementation.
    * Add support for all metrics from the ACs, with row values, totals, minimums and maximums formatted based on each one's `type`. The PHP class contains most of that already, so it can be reimplemented similarly.
    * Add support for the exact `dimensions` values required by the ACs.
        * The PHP implementation mostly only supports `[ 'ga:date' ]` at this point. If this is the `dimensions` value, iterate through all dates within the provided dates from the request, similar to how it's done there.
        * For `[ 'ga:pageTitle', 'ga:pagePath' ]`, rely on a hard-coded list of 12 "web pages". Simply generate them e.g. by a for loop and use "Test Post %d" for the `ga:pageTitle` and "/test-post-%d/" for the `ga:pagePath`. Then iterate over these hard-coded values, i.e. the response should include 12 `rows`.
        * For the other required `dimensions`, use a hard-coded list of 6 realistic values for each of `ga:channelGrouping` (include "(other)") and `ga:country` (include "(not set)"), plus the three standard values "desktop", "mobile", "tablet" for `ga:deviceCategory`. To generate the response `rows` for these, basically we only need to iterate over the hard-coded dimension names and combine them with hard-coded metric values dynamically, similar to how it is done for `ga:date` (with the simplification that here we have a hard-coded list and don't need to go over all dates within the date range). Essentially, the response should for these dimensions include exactly as many `rows` as there are hard-coded dimension names.
        * If `dimensions` is not provided or empty, include a single row which "re-includes" the totals. This might not seem intuitive, but that's how the Analytics API responses behave in that case.
    * Overall, look at some real Analytics API responses to understand the needs here. While the PHP implementation already covers a lot of what is required here and needs to be re-implemented in JS, having real Analytics API responses handy is crucial for understanding what's going on and what's needed in terms of formatting to match that real response format.
* Replace usage of fixtures in all Analytics widget stories (every usage of `generateReportBasedWidgetStories` with `moduleSlugs: [ 'analytics' ]`) with relying on the new `getAnalyticsMockResponse`. If the function is correctly implemented, each of the stories should continue to show up in its regular loading state after exchanging the fixtures for the function, in each case providing the same `requestArgs` as are present in the story's `options`.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Make sure that storybook stories for Analytics widgets work correctly: https://google.github.io/site-kit-wp/storybook/pull/2746/

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz 

> There should be a function like `getAnalyticsMockResponse( requestArgs, options )` in `tests/js/analytics.js` which generates a full Analytics response for the given request `requestArgs`.

* Why not keep the file in `assets/js/modules/analytics/` like other tests and utilities for the module? I realize it isn't particularly specific to the data store where our other fixtures and factories are, so perhaps it could live in `assets/js/modules/analytics/__factories__` instead?

> It'll be based on some hard-coded mock values, combined with logic to arrange them accordingly to get the correct response format for the request.

Perhaps the mock values could be provided as the 3rd argument, which could default to some hardcoded object. The function would be more flexible however if these values weren't fixed in the function itself. That would also likely simplify the `options`. We could have higher-level factories that pass different values through to be built in a more composable way rather than having a single function that does many things.

One thing to note which I think is important here given the use with Storybook is that these should be pure functions which always return the same result for the same input. This is different than other factories we have with the datastore which use `faker` internally to generate random data to fill in the blanks where specific values aren't provided.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> Why not keep the file in `assets/js/modules/analytics/` like other tests and utilities for the module?

Good point. I think we could add a file `assets/js/modules/analytics/util/getAnalyticsMockResponse.js` for the function.

> Perhaps the mock values could be provided as the 3rd argument, which could default to some hardcoded object.

I'm not opposed to that, but at this point I also don't see the need for it. We could for now follow a similar approach that the tester plugin is using on the PHP side.

> One thing to note which I think is important here given the use with Storybook is that these should be pure functions which always return the same result for the same input.

Agreed.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
QA ✅
