### ISSUE TITLE
Enhance localization of prepareSecondsForDisplay

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2588]
## Feature Description

The `prepareSecondsForDisplay` utility takes a number in seconds and returns a formatted human-readable duration as the respective number of hours, minutes, and seconds. As it is, it currently uses hardcoded abbreviations for `s`, `h`, and `m` as well as building the resulting string by concatenating the pieces from left to right. This is not ideal for localization and should be improved to provide a more consistent experience for users across supported locales.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `prepareSecondsForDisplay` should return properly localized numeric values, handled by the `numberFormat` utility  
_Note: we normally use `numFmt` for all formatting, but we're using `numberFormat` directly here since this will be called from within `numFmt` – there's no reason to support extra shorthand, etc_
* hours, minutes, and seconds should be formatted as `style: unit` with `hour`, `minute`, or `second` as the `unit`, respectively
* The formatted units of time should be concatenated with a translatable format string as there is no standard for formatting a number with multiple units
* The output should remain consistent with the current implementation for the default locale
* `numFmt` should respect any unit-related (e.g. `unitDisplay`) options, if provided when `style: duration` is explicitly passed
* `prepareSecondsForDisplay` should be renamed to better reflect its function of formatting the given `seconds` into a duration
* This function should no longer be used outside of `numFmt` and tests

## Implementation Brief

1. Refactor `prepareSecondsForDisplay` so that:
  * it is no longer exported
  * it has a new name: `durationFormat`
  * it accepts a number `seconds` as a parameter
  * it accepts a second `options` parameter, which is an object of type `Intl.NumberFormatOptions`
  * it parses the seconds into hours, minutes and seconds
  * it passes each into `numberFormat`, using appropriate `style` and `unit` options (e.g. hour would be `{ style: 'unit', unit: 'hour' }`) 
  * if the `options` parameter has been passed, then it should be passed through to `numberFormat` as well so that options like `unitDisplay` are reflected in the output.
  * it concatenates the formatted units using a translatable format string (e.g. `_x( '%$1s %$2s %$3s', 'duration of time', 'google-site-kit' )`). Remember to include a `translators: comment` above that to indicate that the first is hours, the second placeholder is for minutes, and the third is for seconds
  * if the number of hours is 0, they should not be included in the output. Similarly, if the number of hours and minutes is 0, the function should only return the number of seconds.
2. Refactor `numFmt` so that:
  * the call to `prepareSecondsForDisplay` is replaced with a call to the new function `durationFormat` when `'s'` or `{ style: 'duration' }` is passed as the second parameter, returning the result
  * when the `options` parameter is `'s'`, then `{ unitDisplay: 'narrow' }` is passed as the second argument to `durationFormat`
  * when the `options` parameter is `{ style: 'duration' }`, with no `unitDisplay` option set, then the default `{ unitDisplay: 'short' }` is passed
  * Calling `numFmt` with a specific `options.unitDisplay` set (e.g. `{ style: 'duration', unitDisplay: 'long' }`) means it is passed through.

### Examples: 
```js
// locale here is 'en-US'
numFmt( 9, 's' ); // '9 s'
numFmt( 10000, 's' ); // '2h 46m 40s'
numFmt( 10000, { style: 'duration' } ); // '2 hr 46 min 40 sec'
numFmt( 10000, { style: 'duration', unitDisplay: 'narrow' } ); // '2h 46m 40s'
numFmt( 10000, { style: 'duration', unitDisplay: 'long' } ); // '2 hours 46 minutes 40 seconds'
```
3. Tidy up
* Incorporate the tests for `prepareSecondsForDisplay` (`/assets/js/util/test/prepareSecondsForDisplay.js`) into the tests for `numFmt` (`/assets/js/util/test/numFmt.js`), refactoring them to reflect the requirements above as necessary.
* Update the documentation for `prepareSecondsForDisplay`, changing the name and adding `@private`, as this is now an internal function
* Check the codebase for calls to `prepareSecondsForDisplay` and refactor them to use `numFmt` (e.g. `assets/js/modules/analytics/util/index.js`)

### Test Coverage

* As mentioned, the tests for `prepareSecondsForDisplay` should be updated to reflect the requirements above, and then incorporated into the tests for `numFmt`
* All other pre-existing tests should pass

### Visual Regression Changes

* There should be no regressions anywhere we print a formatted duration 

## QA Brief

* Check that anywhere we use `numFmt` with the `'s'` or `{ style: 'duration' }` params (very few instances - searching for `datapointUnit` can help) the output on the screen is unchanged
* Check that there are no remaining instances of `prepareSecondsForDisplay` anywhere in the codebase

**Related to follow up PR #2958**
* Using Safari
* Load WP dashboard
* Load Site Kit dashboard(s)
* [Observe no full-page errors](https://github.com/google/site-kit-wp/issues/2948#issuecomment-797007638)

## Changelog entry

* Enhance localization of duration formatting

**Comment by johnPhillips** [comment]
> prepareSecondsForDisplay should return properly localized numeric values, handled by the numFmt utility

@aaemnnosttv I notice that `numFmt` itself calls `prepareSecondsForDisplay` internally (although this only happens if you pass `style: 'duration'` and it doesn't seem that we currently do that anywhere in the codebase at the moment).  

It also appears we don't really make use of `prepareSecondsForDisplay`, although we use `numFmt` all over the place.

So I'm a bit confused as to whether the end goal is that one would do this:
```js
const formattedString = numFmt( seconds, { style: 'duration'} ); // calls prepareSecondsForDisplay internally
```
Or this?
```js
const formattedString = prepareSecondsForDisplay( seconds ); // calls numFmt internally
```

If we go with the first option, we may as well remove the export of `prepareSecondsForDisplay` and just keep it as an internal helper. 

If we go with the second option, we are introducing a second way to format numbers in the case of time.

Let me know what you think, or if I have misunderstood the ACs here?

**Comment by johnPhillips** [comment]
Note: @aaemnnosttv and I discussed this offline, and we agreed that the second option made more sense, ie.
- `numFmt` should be the utility we use for formatting time
- `prepareSecondsForDisplay` can be used by `numFmt` internally, but it shouldn't be public

First draft of IB added accordingly.

**Comment by aaemnnosttv** [comment]
@johnPhillips the IB looks like a good start here, although there are a few points yet to address.

Currently, `prepareSecondsForDisplay` returns a value like `2m 3s`, whereas your example uses a different format for the unit. `NumberFormat` controls this by the `unitDisplay` option which defaults to `short` but can also be `long` or `narrow`. For consistency with the current `prepareSecondsForDisplay` output, we should use `narrow` however, I think we should only apply this when we use the shorthand option to `numFmt( num, 's' )`. Otherwise, if `numFmt( num, { style: 'duration', unitDisplay: 'long' } )` is called, it should use the provided option instead.

This isn't a 100% backwards compatible change, but for our current use it should be fine because we aren't passing `duration` explicitly anywhere, and we're only using the shorthand `s` in one component.

Second, as per the ACs:
> The formatted units of time should be concatenated with a translatable format string as there is no standard for formatting a number with multiple units

This is important that we don't simply concatenate the string together. Even though `NumberFormat` will produce i18n-friendly values for the individual units of time, the combined string must be translatable for it to be fully i18n (think LTR languages, but there may be other cases). It's not a perfect solution, but I think it's the best we can do for now.

Lastly, since `prepareSecondsForDisplay` is becoming an internal function that isn't intended to be used directly other than by `numFmt`, I think we can give it a better name. How about `durationFormat( seconds, options )` ? I realize this is a bit different than the original ACs, so I'll update them. I've left the specific name out of the ACs so feel free to suggest an alternative 👍 

Other than that, please add an estimate with your updated IB. Thanks!

**Comment by johnPhillips** [comment]
Thanks @aaemnnosttv, I update the IB. Hope I included everything.

One thing:
> we're only using the shorthand s in one component.

I couldn't find any instances of `numFmt` with the `'s'` parameter?

**Comment by aaemnnosttv** [comment]
> I couldn't find any instances of `numFmt` with the `'s'` parameter?

@johnPhillips look for [`datapointUnit`](https://github.com/google/site-kit-wp/search?q=datapointUnit&type=), which is passed through as the second parameter to `numFmt` where it's used.

**Comment by aaemnnosttv** [comment]
@johnPhillips IB looks great!

The only thing I saw which was very slightly off was from the first example:
```js
numFmt( 9, 's' ); // '9 s'
```
This should result in `9s` since the shorthand would include the `narrow` format. Not worth sending back for revision, but just thought I'd point that out to avoid potential confusion during implementation.

IB ✅

**Comment by ivankruchkoff** [comment]
QA ✅

`$ ack -i prepareSecondsForDisplay || echo 'no instances'`
no instances

Also ran the numFmt util manually supplying different locales to test it out, all looks good.

**Comment by aaemnnosttv** [comment]
Unfortunately [Safari does not support some of these options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#browser_compatibility) 😞   Pulling this back to Execution to address.
cc: @felixarntz @ivankruchkoff

**Comment by ivankruchkoff** [comment]
Taking a look at this now to push out a fix.

**Comment by ivankruchkoff** [comment]
So there are a few options here (my preference is for option 3):
1) Use a polyfill, however I don't like that due to https://github.com/google/site-kit-wp/blob/4a8f2f2035e178618e1c8927c5ee7c3b6ec41e2e/assets/js/util/i18n.js#L264 and the sheer size of the polyfill: https://www.npmjs.com/package/@formatjs/intl-numberformat

2) Using a different js library for calculating times, e.g. https://github.com/iamkun/dayjs

3) Using a fallback to handle the safari case (which throws a `RangeError` when options.style is not one of `decimal`, `percent`, or `currency`:

Wrap the call to 
```js
numberFormat( hours, {
  ...options,
  unit: 'hour',
} );
``` 
in a try {} catch, if an exception is thrown we set `options.style = 'decimal';`

which means that instead of `3h 2m 6s` we will have `3 2 6`, so we need to have two versions of string for `sprintf`
`'%3$s %2$s %1$s'` and ` '%3$sh %2$sm %1$ss',`

This gives us the benefit of internationalised approach in browsers that support it, and a fallback to the current approach of XXh YYm ZZs that we currently have.

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff – I agree that the 3rd option is the best choice here.

@johnPhillips are you able to pick this up for a follow-up PR?

**Comment by tofumatt** [comment]
QA ✅

No full-page errors observed with Safari 14.0.3.
