### ISSUE TITLE
Test Key User Flows for Admin | Editor WP Admin Bar - From dashboard

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#259]
Set up Test Key User Flows for Admin|Editor WP Admin Bar - From dashboard

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* n/a

## Implementation Brief

* n/a

## Changelog entry

* Test Key User Flows for Admin|Editor WP Admin Bar - From dashboard

**Comment by adamsilverstein** [comment]
Closing this in favor of https://github.com/google/site-kit-wp/issues/254 which will test the WordPress Admin Bar integration both from the front and back end, for all user types.
