### ISSUE TITLE
Standardize formatting of single sentences and phrases

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2597]
## Bug Description

As noticed in https://github.com/google/site-kit-wp/issues/2381#issuecomment-756178985 have a number of places in the plugin where text is formatted inconsistently regarding the use of a period/full-stop at the end. This should be applied consistently throughout the plugin.

## Steps to reproduce

1. Set up Site Kit
2. See inconsistent text formatting in blue CTAs on Site Kit dashboard

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/103994490-c0217480-519f-11eb-9d4e-92c722ba68d1.png)
![image](https://user-images.githubusercontent.com/1621608/103994492-c1eb3800-519f-11eb-9336-3b4a9d1f292a.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Top level headings should have no punctuation (e.g. "Learn more what visitors do on your site")
* For the "body" text, if there is more than one sentence, full stops and other punctuation should be used. Else leave without.
    * If there is a single sentence followed by a separate link, punctuation should also be used, however _not_ on the link.

More info on Material writing guidelines here:
https://material.io/design/communication/writing.html#principles
(look up the section "Skip unnecessary punctuation")

## Implementation Brief

* Review the section on "Skip unnecessary punctuation" as detailed above
* Search the React code for implementations of the `CTA` component ( `assets/js/components/legacy-notifications/cta.js` )
* Check the punctuation of the `title` and `description` props being passed to the `CTA` component and update as necessary
  * `title` should always lack punctuation
  * `description` varies based on its content:
    * **single sentence**: should have no punctuation
    * **more than one sentence**: all sentences should have punctuation
    * **more than one sentence**, but last sentence is a link: all sentences except the last should have punctuation

### Test Coverage

* N/A

### Visual Regression Changes

* Check visual tests and update as necessary.

## QA Brief

* Ideally check every CTA to make sure it fits our punctuation rules
* A lot of CTA text comes from network responses/errors so, realistically, check the changes done do fit the punctuation rules and have a look around the plugin

## Changelog entry

* Standardize punctuation and formatting of various sentences and phrases throughout the plugin.

**Comment by tofumatt** [comment]
@Hazlitte Can you please fill in the test coverage and VRT sections? I imagine some VRTs will need to update as a result of the text changes.

Also, while the ACs here pretty much outline the implementation of the issue, it would be good to clarify it the IB. It seems the approach is:

* `title` should always lack punction
* `description` varies based on its content:
  * **single sentence:** should have no punctuation
  * **more than one sentence:** all sentences should have punctuation
  * **more than one sentence, but last sentence is a link:** all sentences except the last should have punctuation

It'd be good to explicitly outline the approach in the IB 🙂

**Comment by tofumatt** [comment]
IB ✅

**Comment by danielgent** [comment]
Apologies @tofumatt @Hazlitte , but I'm sure exactly what changes I have to make


A common example where the description is one sentence and there is a link

![ctaexample](https://user-images.githubusercontent.com/8496063/115727818-42ffc100-a384-11eb-838a-8ee278b7c4a9.png)

With code

```
<CTA
  title={ __( 'Link Analytics and AdSense', 'google-site-kit' ) }
  description={ __( 'Get reports for your top earning pages by linking your Analytics and AdSense accounts.', 'google-site-kit' ) }
  ctaLink={ supportURL }
  ctaLabel={ __( 'Learn more', 'google-site-kit' ) }
/>
```

The IB speaks about the `description` prop containing Links. I have not seen this. There are separate props `ctaLink` and `ctaLabel`. 

I'm not sure if a CTA with single sentence `description` and a string for `ctaLabel` should end the description with a period 

I think the IB may not mention the correct props?

**Comment by aaemnnosttv** [comment]
> If there is a single sentence followed by a separate link, punctuation should also be used, however not on the link.

@marrrmarrr just to clarify – is this example correct then?
![ctaexample](https://user-images.githubusercontent.com/8496063/115727818-42ffc100-a384-11eb-838a-8ee278b7c4a9.png)

Or is this only referring to a following link on the same line? E.g. 
![image](https://user-images.githubusercontent.com/1621608/115858954-39379580-a438-11eb-93bd-8bd7580e1276.png)

**Comment by marrrmarrr** [comment]
This is referring to cases where the link is on the same line.

**Comment by danielgent** [comment]
I've created a PR for this but the e2e tests keep failing for WordPress 4.9 and Gutenberg 4.9 :thinking: 

For the last few runs just this e2e test fails.  Odd given that this PR is just text changes! I was expecting to find the test wanting some text to have a full stop but no


One concern is that a lot of these `CTA`s have their text set dynamically by network responses (errors mostly).  See a previous commit where I removed all my comments for suspect calls: https://github.com/google/site-kit-wp/pull/3316/commits/e02ba5a8d69a95e16b0873597b591ffb7e502519

Apart from that, I went through as well as I could!

**Comment by aaemnnosttv** [comment]
@wpdarren that's a good point – I think these would be encompassed as part of this issues as well. Your example there makes sense as one that should not have a full stop 👍

**Comment by wpdarren** [comment]
@danielgent as per [my comment](https://github.com/google/site-kit-wp/issues/2597#issuecomment-838722592) and confirmation from Evan above, any page that has a description like the example in my comment should not have a full stop/period.  This would be the case on all of the plugin pages. I have moved this ticket back to execution.

**Comment by danielgent** [comment]
![also-fix-this](https://user-images.githubusercontent.com/8496063/118020588-85e8ff00-b35a-11eb-9078-e5f30692eb28.png)
The formatting also needs fixing here I believe (too many full stops)

But this is on the proxy in another repo right @aaemnnosttv ?

**Comment by aaemnnosttv** [comment]
@wpdarren yes, that is not something we can change here, but I already raised this with @felixarntz and @adamsilverstein so it's probably just a matter of whenever they can get to it.

**Comment by danielgent** [comment]
I've gone through and fixed any remaining formatting issues that I can see.

I also spent some time going through the code and search for instances of strings that end with full stops, to then check the formatting.   But it felt risky to make changes without actually seeing the output!  and most instances are in our `invariant` calls (not user-facing) or in our stories

**Comment by wpdarren** [comment]
@danielgent @aaemnnosttv any thoughts on the periods in setting descriptions? All of the module messages look good. 

![image](https://user-images.githubusercontent.com/73545194/118283714-91a60400-b4c7-11eb-9715-f11a0e1f9ca0.png)

**Comment by danielgent** [comment]
@wpdarren The one you highlighted is actually ok right? (As it is two sentences)  But *the others* all have periods when they are one sentence, violating formatting rules! :smile: 

I thought I went through the whole app. I'll make this change now :+1:

**Comment by wpdarren** [comment]
@danielgent good point about the one I have highlighted!  I will assign it to you, but assign it back to me when you've made the change and I'll do my final checks 👍

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

Checked every CTA to make sure it fits our punctuation rules including dashboard, all modules and settings. 

![image](https://user-images.githubusercontent.com/73545194/118494481-1be5a680-b71a-11eb-9ede-e19f96f90ca3.png)

![image](https://user-images.githubusercontent.com/73545194/118494534-299b2c00-b71a-11eb-9e74-bc66e6f81734.png)

@danielgent thanks for your work on this one!
