### ISSUE TITLE
Authorization Flow | Author + Contributor

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#260]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* This should probably expand on the existing test from #256.
* The flow for an Author or Contributor is entirely similar to the one for an Editor.
* The only difference is that, after coming back from Google OAuth, they must land on the splash screen instead of the dashboard (they don't have permission to view the dashboard).

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@bjackson27 @aaemnnosttv What is this about? A contributor cannot "activate Site Kit". Could you please clarify?

**Comment by aaemnnosttv** [comment]
Perhaps this is a test to ensure that a contributor cannot activate Site Kit?

**Comment by swissspidy** [comment]
That doesn't really make sense as that's core's job to prevent. Perhaps it's about the auth flow?

**Comment by felixarntz** [comment]
@aaemnnosttv Given your comment https://github.com/google/site-kit-wp/issues/221#issuecomment-516314075, this is probably about the initial authentication for a contributor.

**Comment by lucymtc** [comment]
@felixarntz noting here the message for author and contributor in splash page is different ( merged in this PR https://github.com/google/site-kit-wp/pull/322), should we include this in the acceptance criteria?
