### ISSUE TITLE
Add amp-story-auto-ads support for Web Stories

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2602]
Now that [AdSense supports Web Stories](https://blog.amp.dev/2020/12/10/google-launches-programmatic-ads-for-web-stories/), Site Kit should start supporting that as well for users which have AdSense set up.

Most of it should be straightforward, however a complication is that users are also required to choose an ad unit for their web stories - so it's different from regular `amp-auto-ads` where it just works without providing an ad unit. We can introduce a new dropdown in AdSense settings, which should only show when the module is fully connected and when the [Web Stories plugin](https://wordpress.org/plugins/web-stories/) is also active.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `GET:adunits` datapoint in the `AdSense` class in PHP which relies on `accountID` and `clientID` request arguments to return a list of adunits (via https://developers.google.com/adsense/management/v1.4/reference/accounts/adunits/list).
* There should be a new `getAdUnits( accountID, clientID )` selector in the `modules/adsense` store which is powered by the above endpoint.
* There should be a new setting `webStoriesAdUnit` in `AdSense\Settings` (also needs to be supported in JS) with the default value of an empty string.
* If the [Web Stories plugin](https://wordpress.org/plugins/web-stories/) is active, the AdSense settings panel should include UI for the new setting with label _Web Stories Ad Unit_.
    * In view mode, it should display the value (ad unit ID) or "None".
    * In edit mode, it should be a dropdown powered by the `getAdUnits()` selector, passing the current `accountID` and `clientID` setting values. It should also offer an empty option like "Select ad unit" (default).
    * In edit mode, there should be a description below: _This ad unit will be used for your Web Stories. Learn more (about creating an ad unit for Web Stories)_ (the part in parentheses should only be available for screen readers)
    * The Learn more link should point to https://support.google.com/adsense/answer/10175505#create-an-ad-unit-for-web-stories
* If the AdSense module is connected and the `clientID`, `useSnippet`, and `webStoriesAdUnit` options are truthy, an `amp-story-auto-ads` tag should be injected into via `web_stories_print_analytics` hook. See [here](https://support.google.com/adsense/answer/10175505#embed-the-ad-unit-in-your-web-story) for the required format (we also need to use the `clientID` option for that).
* The value of the new option should also be exposed in the debug fields as `adsense_web_stories_adunit_id`.

## Implementation Brief

**Adunits endpoint**

* Add a new `GET:adunits` datapoint to the returned array of `AdSense::get_datapoint_definitions` in the file `includes/Modules/AdSense.php`.
* Add a new case within `Adsense::create_data_request` for `GET:adunits`, within this case statement:
   * Check if `$data['accountID']` or `$data['clientID']` are not set and show a new `WP_Error` in that case like so: `return new WP_Error( 'missing_required_param', sprintf( __( 'Request parameter is empty: %s.', 'google-site-kit' ), 'accountID' ), array( 'status' => 400 ) );`
   * Get the adsense service using `$service = $this->get_service( 'adsense' );`;
   * The return the list of adsense story types using `$service->accounts_adunits->listAccountsAdunits( accountID, clientID )`

**Settings View**
* Create a new selector called `getAdUnits( accountID, clientID )` in the file: `assets/js/modules/adsense/datastore/adunits.js` - **model it on an existing selector such as `assets/js/modules/adsense/datastore/urlchannels.js`.**
   *  This selector should request the new `adunits` API you created above:
```
//...
return API.get( 'modules', 'adsense', 'adunits', { accountID, clientID }, {
// ...
```
* Add the new setting `webStoriesAdUnit` to the settingsSlugs array in `includes/Modules/AdSense/Settings.php` and `assets/js/modules/adsense/datastore/base.js` so that it will be handled in PHP and stored in JS by the core `submitChanges` action.

* Add the new setting to the settings page `assets/js/modules/adsense/components/settings/SettingsView.js`
   * Title the new setting  _Web Stories Ad Unit_.
   * **View Mode**
   * Display the value (ad unit ID) or "None".
   *  **Edit Mode**
   * Display a select dropdown that with a default empty value of "Select ad unit" 
   * Build the select dropdown options using the new selector `const adUnits = useSelect( ( select ) => select( STORE_NAME ).getAdUnits( accountID, clientID ) );`, using the current client-side settings for these two parameters.
    * Add a description below: _This ad unit will be used for your Web Stories. Learn more (about creating an ad unit for Web Stories)_ (the part in parentheses should only be available for screen readers)
    * Link *Learn more* to https://support.google.com/adsense/answer/10175505#create-an-ad-unit-for-web-stories

**Conditionally Show Setting Based on Web Stories Plugin**

* Update PHP `Assets::get_inline_base_data()` method to include a `webStoriesActive` key, relying on a `defined( 'WEBSTORIES_VERSION' )` check.
* Modify JS `getSiteInfo` resolver in `core/site` store to include the new field in `state.siteInfo`.
* Add JS selector `isWebStoriesActive()` in `core/site` store relying on `getSiteInfoProperty( 'webStoriesActive' )`.
* In the SettingsView `assets/js/modules/adsense/components/settings/SettingsView.js`, only display the settings form if `const webStoriesActive = useSelect( ( select ) => select( CORE_SITE ).isWebStoriesActive() );` is `true`.

**AMP Tag**

* Modify `includes/Modules/AdSense/AMP_Tag.php` (Web Stories is always AMP):
    * For rendering the story-specific tag, the class needs awareness of the ad unit chosen. Therefore, add a public `set_story_ad_slot_id( $ad_slot_id )` method to the class and assign it to a private property.
    * Create a new private method `render_story_auto_ads()` to the class.
        * In this new function, render the output like so:
```
			printf('
				<amp-story-auto-ads>
					<script type="application/json">
						{
							"ad-attributes": {
							"type": "adsense",
							"data-ad-client": "%s",
							"data-ad-slot": "00000000"
						}
					}
				</script>
				</amp-story-auto-ads>
				',
                                 $this->tag_id,
                                 $this->story_ad_slot_id,
);
```
    * Modify the `AMP_Tag::register()` method:
        * If `is_singular( 'web-story' )`, add hook like so: `add_action( 'web_stories_print_analytics', $this->get_method_proxy( 'render_story_auto_ads' ) );`. 
        * Move the existing action, filter, and enqueued script into the `else` clause for the above, so that those pieces only get invoked for AMP that is _not_ a web story.
* Modify the `AdSense\Tag_Guard` class: If `is_singular( 'web-story' ) && ! $settings['webStoriesAdUnit']`, return false. For web stories, the tag must only be rendered if a story-specific ad unit is provided.
* Modify the `AdSense::register_tag` method:
    * Remove `web-story` from the initial clause. At this point, it only needs to be kept for BC with the old `amp_story` format, which we shouldn't worry about in terms of actually adding support.
    * Make the `$this->context->is_amp()` check into a full if else conditional block. For the AMP case, call the new `set_story_ad_slot` method to pass `$settings['webStoriesAdUnit']`.

**Site Health**
 * Add the value of the new webStoriesAdUnit field to the debug fields as `adsense_web_stories_adunit_id`:
https://github.com/google/site-kit-wp/blob/ce582d1910bdf0104792da6f3975a19586ed186d/includes/Modules/AdSense.php#L172-L203

**Storybook**
* Update the storybook for the Adsense Settings to show this new setting `stories/module-adsense-settings.stories.js`.

### Test Coverage

* Add tests to cover the new `getAdUnits` selector in `assets/js/modules/adsense/datastore/adunits.test.js`.
* Add tests to confirm the `render_web_story_ad_unit` function returns correctly in `tests/phpunit/integration/Modules/AdSenseTest.php`

### Visual Regression Changes

* The visual regression tests should show changes on the `module-adsense-settings` *only*. No other VRT should have to be updated.

## QA Brief

* 
* Install the latest version of the tester plugin.
* Enable the Adsense module.
* Install the [Web Stories for WordPress](https://github.com/google/web-stories-wp) plugin.
* You will now see the new setting to select the AdUnit in the AdSense settings.
* The select field will be empty - this is expected as the tester plugin doesn't currently provide adunits in the response.

## Changelog entry

* Add support for AdSense auto ads to Web Stories, allowing to choose an AdSense ad unit to use which will then result in an `amp-story-auto-ads` element being injected.

**Comment by swissspidy** [comment]
>an `amp-story-auto-ads` tag should be injected into the `web_stories_story_head`

The docs are not very clear, but the tag actually needs to be added before the closing `</amp-story>` tag, so the correct place would be the `web_stories_print_analytics` hook.

NB: here's the current UI in the Web Stories plugin: https://github.com/google/web-stories-wp/pull/5611

**Comment by felixarntz** [comment]
@swissspidy Good catch, corrected it!

**Comment by benbowler** [comment]
IB added as well as tests + VRT and estimate.

**Comment by swissspidy** [comment]
> Return `is_plugin_active('web-stories')` from this endpoint.

Might be safer to check for `defined( 'WEBSTORIES_VERSION' )`, in case the plugin slug is not `web-stories` for some reason.

**Comment by tofumatt** [comment]
Updated the IB with @swissspidy's suggestion, but aside from that the IB looks good to me I think. ✅

**Comment by aaemnnosttv** [comment]
I realize this one is already in motion but after reviewing a bit with @johnPhillips I have some concerns about this issue.

- It doesn't seem like a good candidate for a good first issue label. It involves digging into _many_ different areas of the codebase; any one of which on its own might be a GFI, but taking them all in one issue is too much IMO. Also, any issue with the largest estimate we can give probably shouldn't be a GFI regardless.
- There seems to be some inaccuracies in the IB:
    - The `GET:adunits` datapoint handler describes accessing `accountID` and `clientID` from request parameters, but the ACs say these should come from module options).
    - `$service->adunites->listAdunits( $data['accountID'] )` – (typo in the service property) but also this method only accepts a client ID – the proper resource seems to be `$service->accounts_adunits->listAccountsAdunits( accountID, clientID )`

Other things seem like they could be improved as well, such as the suggestion to add a datapoint for `GET:web-stories-plugin-active`. This would be better passed via one of our globals at page load I think like we do with the AMP mode.

I believe @johnPhillips has held on executing this one for now but I think a secondary review on the IB would be good before we continue here. Assigning to @felixarntz for review since he's both the most familiar with this issue but with the AdSense module in general.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> It doesn't seem like a good candidate for a good first issue label. It involves digging into many different areas of the codebase; any one of which on its own might be a GFI, but taking them all in one issue is too much IMO. Also, any issue with the largest estimate we can give probably shouldn't be a GFI regardless.

Maybe you're right. I agree it's definitely on the more complex end of GFIs, but for pretty much every piece here there's existing code to base the implementation on. I think having a distinct feature like this allows to get a good idea of how different pieces in the plugin relate and work together. Probably the part that makes it less GFI-feasible is that we need some extra logic for knowing whether the Web Stories plugin is active in JS, in combination with all the other things. Anyway, let's keep it non-GFI then.

> The `GET:adunits` datapoint handler describes accessing `accountID` and `clientID` from request parameters, but the ACs say these should come from module options).

Indeed, the IB is correct here, I've updated the ACs. Some things only become obvious when you look into the implementation in more depth :)

Regarding the other feedback, I've updated the IB, also regarding a few other things:
* Use correct Google API service class.
* Rely on `_googlesitekitBaseData` for whether Web Stories is active.
* Rely on modifying the AdSense `AMP_Tag` class for rendering `amp-story-auto-ads` instead of adding a separate decoupled method to the `AdSense` main class (see #475).

Passing back to you for review.

**Comment by aaemnnosttv** [comment]
IB LGTM ✅

**Comment by swissspidy** [comment]
@aaemnnosttv @felixarntz Once this is implemented, how can we on our side detect whether Site Kit is already displaying AdSense ads in stories so that we disable our own integration & can inform the user? e.g. using `get_option(...)`

**Comment by aaemnnosttv** [comment]
@swissspidy You should be able to check for the value of the chosen `webStoriesAdUnit` in the `googlesitekit_adsense_settings` option array. E.g.
```php
$settings = get_option( 'googlesitekit_adsense_settings' );
$ad_unit  = isset( $settings['webStoriesAdUnit'] ) ? $settings['webStoriesAdUnit'] : null;
```

**Comment by benbowler** [comment]
I've worked through this based on the IB and tests alone as I don't have an active AdSense account to test with. I've requested an AdSense account for a personal domain but it's yet to be approved.

Changes are in [PR for code review](https://github.com/google/site-kit-wp/pull/2766).

**Comment by benbowler** [comment]
QA Brief is TBC because I'm unable to test currently without and AdSense account.

**Comment by felixarntz** [comment]
@benbowler Can you add a QA brief to this one?

**Comment by benbowler** [comment]
QA Brief added @wpdarren.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

The new setting to select the AdUnit in the AdSense settings.

![image](https://user-images.githubusercontent.com/73545194/109011960-70b1ec00-76ec-11eb-8364-5eb030e6c4d3.png)

The select field does have options in but those are from my Google Adsense account, so makes sense for them to be in the dropdown.  When I selected an ad unit, and clicked on save, no errors appeared in console or FE. 

![image](https://user-images.githubusercontent.com/73545194/109012156-a6ef6b80-76ec-11eb-9e8b-c0c6b663a7cc.png)

Within the settings after save, the Google Adsense ID appeared. 

![image](https://user-images.githubusercontent.com/73545194/109012413-f2097e80-76ec-11eb-8fc1-30033d236443.png)

The `Learn More` was displayed and linked through to the correct Adsense help guide. 

![image](https://user-images.githubusercontent.com/73545194/109012583-241ae080-76ed-11eb-9f83-688bfdc1008b.png)
