### ISSUE TITLE
Migrate WP dashboard widget's "Top content over the last x days" table to functional component using datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2610]
#2075 focused on replicating the WP dashboard widget's UI via new functional components using the datastore. One piece that was missed during ACs and IB review was the "Top content over the last x days" table that appears at the bottom when Analytics is active.

Since the new UI is currently only shown in a development build, that is okay for now, but we need to also migrate that table before we can launch the new WP dashboard widget in production. Let's do that.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new functional hook-based `WPDashboardPopularPages` component that relies on the datastore and renders the exact same UI as its legacy version.
    * It should not use any legacy functions, i.e. it should create its request object individually and extract data from its response manually, similar to closely related refactored components, such as the Analytics Top Pages table in the dashboard (a lot of the code we'll be able to copy from there).
* The component should be integrated into the new WP dashboard widget component infrastructure (behind `widgets.wpDashboard` feature flag) with similar placement as it has in the legacy WP dashboard widget.

## Implementation Brief

* Create a new file to export a functional component `WPDashboardPopularPages` in `/assets/js/components/wp-dashboard/WPDashboardPopularPages.js`
* For rendering of the widget, its content will be based on: `/assets/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetTopPagesTable.js`
https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetTopPagesTable.js
* For functionality of the widget, see these components:
* https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidget.js#L1
* https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopPagesTable.js#L1
* Report fetching occurs here: https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetTopPagesTable.js#L107-L115 and can be done with `select( MODULES_ANALYTICS ).getReport()` selector, see reference here https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/datastore/report.js#L145

Update `/assets/js/components/wp-dashboard/WPDashboardApp.js` to include a call to the new `WPDashboardPopularPages` 
https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/components/wp-dashboard/WPDashboardApp.js#L70

* To view the widget for testing, open the WordPress main dashboard page `/wp-admin/index.php`

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Use a development build (`npm run dev`)
* Go to the main WP dashboard (`/wp-admin/index.php`)
* Examine the Site Kit dashboard widget (entitled **Site Kit Summary**) and note the two tables entitled **Top content over the last N days**
* The top table is the new functional component; the bottom one is the legacy one
* Ensure that the new (top) table is exactly the same as the legacy (bottom) table (loading states, on various screen sizes etc)

## Changelog entry

* Migrate top content table in WP dashboard widget to functional hook-based component using the datastore.

**Comment by tofumatt** [comment]
The IB here is missing an estimate, could you add one? 🙂 

Also, I think it's worth noting, especially as this is marked as Good First Issue, where the existing data for that component comes from and to note we should be using the `select( MODULES_ANALYTICS ).getReport()` selector to get the data in the new functional/hooks-based component. The call to get the report data is done here: https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/components/wp-dashboard/WPAnalyticsDashboardWidgetTopPagesTable.js#L107-L115 using the old `withData` higher-order-component, which a new developer might be less familiar with. Worth adding that bit of guidance into the IB as well I think since it's marked as a good first issue.

Otherwise looks good though!

**Comment by tofumatt** [comment]
IB ✅

**Comment by felixarntz** [comment]
@johnPhillips A QA Brief is still missing here, can you add one? It should focus on using a development build and ensuring the appearance between the old and new version should match.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- The new (top) table is exactly the same as the legacy (bottom) table 

Tested this on various screen sizes. Also ran it through on Browser Stack on FF, Chrome, Safari and Edge. 

[Screenshot](https://user-images.githubusercontent.com/73545194/107225016-35a88b00-6a53-11eb-8524-c3a30d1ede08.png)
