### ISSUE TITLE
Backstop occasionally hangs indefinitely before generating test report 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2618]
## Bug Description

Last week I noticed some VRT jobs which ran for hours before I cancelled them (this probably shouldn't be possible either and we should have a reasonable max-runtime for all jobs). The backstop job seemed to run fine but it would hang at the very end where it would normally open the report and finish. I've seen this locally some too, but never in CI. Not sure what it was but last week it was happening quite a bit on Friday.

I found [an issue on the Backstop repo](https://github.com/garris/BackstopJS/issues/1208) from a few months ago where others seemed to be reporting the same thing and I opened this PR to test. It ran fine, even on Friday when other issues were having trouble but maybe it was just a coincidence. Other users reported the problem went away when by removing readyEvent.

## Steps to reproduce

1. Run `npm run test:visualtest`
2. Sometimes the command will never finish

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/104562235-c22c7d00-5650-11eb-9982-5fb2e1ee3c79.png)
![image](https://user-images.githubusercontent.com/1621608/104562137-9f01cd80-5650-11eb-8ff8-7daff1877ac0.png)
![image](https://user-images.githubusercontent.com/1621608/104562176-b0e37080-5650-11eb-87ef-60ecc395ab57.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* BackstopJS should be configured to use `readySelector` instead of `readyEvent` in all cases
* The `preview-head.js` should be updated to add a `backstopjs-ready` class to the `body` element instead of using `console.log` as it did before

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/2604

### Test Coverage

* No changes needed

### Visual Regression Changes

* This is a configuration change which should only enhance the stability of VRT runs
* No other changes needed

## QA Brief

* This one is difficult to reproduce consistently
* Try running `npm run test:visualtest` multiple times to see if it gets stuck when running
    * The command takes ~5 min on average to run in CI, locally it may be +/- a little bit but you'll know it's stuck if your terminal stops printing lines for 10+ seconds and it looks like this: 
![image](https://user-images.githubusercontent.com/1621608/104563293-226fee80-5652-11eb-8a96-c0ed13e14052.png)
    * A successful run should always end with output like this (locally it should also open a browser window with the report so it's hard to miss 😄 ) 
![image](https://user-images.githubusercontent.com/1621608/104563598-84305880-5652-11eb-9018-2778fa5c0e59.png)

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by cole10up** [comment]
### QA ✅

Ran npm run test:visualtest locally, multiple times. Didn't experience any hanging during my tests.

Output was displayed to me each time:
![image](https://user-images.githubusercontent.com/57115907/104693556-b7a8cc80-56be-11eb-8d59-66962bdd4076.png)

Sending to approval
