### ISSUE TITLE
Change font styles in All Traffic V2 `TotalUserCount` to match those of our regular `DataBlock`s

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2623]
#2423 introduced the `TotalUserCount` component. Unfortunately, the Figma file design linked to there was outdated, so we added some custom styles there that should not be applied.

[This is the correct Figma design](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1284%3A175) - to be precise, the font style/size/color etc. for every part of the `TotalUserCount` UI should entirely match those that are used in our regular `DataBlock` components.

This will also result in the new widget integrating more nicely with the existing widgets where otherwise it would have felt a bit too foreign.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Users" label, the total count, and the percentage change should all match in text style/size/color the respective similar text that is used in `DataBlock` components (e.g. in the "Search Funnel" widget area below).
* Custom styles added earlier to make the current version of the text appear like it does should be removed.

## Implementation Brief

* Update styles for the `TotalUserCount` (found in [assets/sass/widgets/_googlesitekit-widget-analyticsAllTrafficV2.scss](https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/sass/widgets/_googlesitekit-widget-analyticsAllTrafficV2.scss)) component to match the design in the Figma file provided in the description.
* Remove the previous styles that are no longer needed for the total user count component.

### Test Coverage

* N/A

### Visual Regression Changes

* The total user count section of the new all traffic widget should look like on the new Figma file.

## QA Brief

* Set up the plugin;
* Activate and connect the Analytics module;
* Go to the dashboard page and make sure that the new all traffic widget has appropriate styles for the total user count block and that the fonts match the fonts in e.g. the Search Funnel widget below.

## Changelog entry

* Modify font styles in the new All Traffic widget to match font styles used in Search Funnel widget and elsewhere throughout the plugin.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the font style matches that of the values in the Search Funnel widget.  Compared CSS and font family. Also checked on mobile devices to make sure that the value was readable on all screen sizes. 

![image](https://user-images.githubusercontent.com/73545194/105491640-95800180-5cf1-11eb-8bb4-6b8934711aa9.png)

**Comment by felixarntz** [comment]
**QA** ⚠️ 

Forwarding test feedback from Aaron here: In his testing, the ">" character in "Users > ..." did not show up. I haven't encountered this, but it may be a browser-specific issue. Overall it's probably a better idea to render it instead of using the CSS `content` rule - I'm sure that would address his problem.

@eugene-manuilov Could you make this change? It was technically already here before this issue, but this is the most related one for this release.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

On the new dashboard module the `>` appears after `Users` So the full text reads `Users > Organic Search`

![image](https://user-images.githubusercontent.com/73545194/106215912-f1281e80-620c-11eb-9f11-52cc67b14166.png)

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

The `>` is appearing after Users, i.e. `Users > Organic Search`
Checked this for all slices in the pie chart with different date periods. 

![image](https://user-images.githubusercontent.com/73545194/106220218-f6d63200-6215-11eb-8608-e9cfcdafc6ea.png)
