### ISSUE TITLE
Use pie slice color for `UserCountGraph` chart line when one of the pie slices is selected

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2625]
The `UserCountGraph` (see #2422) contextually may show data for a specific pie slice selected in the `UserDimensionsPieChart` (see #2425). One requirement there that was missed from the original [Figma design](https://www.figma.com/file/NzvJTPFdqUVJC9Q1mmih4e/Google-SK-UX-Enhancements10up?node-id=1284%3A412) (and, unrelated to that, also suggested by @tofumatt) is that the color of the graph line in that case should match the color of the selected pie slice.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a specific pie slice in the new All Traffic widget is selected, the line graph in the same widget should have the same color as the slice.
* Only when no specific slice is selected, it should have its current blue color.
    * Note that, despite the Figma design, we should stick to using the line chart, as the chart library does not allow us to use the area chart style in the way we intend to.

## Implementation Brief

* Update google chart `onSelect` listener in the `UserDimensionsPieChart` component to set the `dimensionColor` value [along with the `dimensionValue`](https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/UserDimensionsPieChart.js#L87-L95) based on the selected pie slice. If a slice is unselected or the Others slice is selected reset the dimension color by passing an empty string.
* Update the `handleTabUpdate` callback in the `DimensionTabs` component to reset the `dimensionColor` value by assigning an empty string to it.
* Update the `UserCountGraph` component to select the current `dimensionColor` value from the forms datastore and use it as the current color for the graph or fallback to the hardcoded one if the `dimensionColor` is empty. (Colours are set here: https://github.com/google/site-kit-wp/blob/7ee258d11ee6c429be9e2e931fedfed5d92dd2f4/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/UserCountGraph.js#L133)

### Test Coverage

* Not required.

### Visual Regression Changes

* The user count graph should reflect the color of the selected pie slice in the user dimensions chart or fallback to the blue color if nothing or the Others is selected.

## QA Brief

* Set up the plugin;
* Activate and connect the Analytics module;
* Go to the dashboard page and make sure that the user count graph uses the color of the selected pie slice in the user dimensions chart or the blue color when nothing or the Others is selected.

## Changelog entry

* Modify new All Traffic widget so that the line chart always uses the same color indicated by the currently selected pie slice.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

- On the Channel dimension tab, when I click the 'Other' slice the color of the graph changes correctly but the number of users doesn't update.  In this case, the user total should be `1` but it's displaying the total users, `875`

![image](https://user-images.githubusercontent.com/73545194/105353092-c432a500-5c29-11eb-82ae-ead7b3f9344f.png)

- On the Location dimension tab, when I click the 'Other' slice the color of the graph changes correctly but the number of users doesn't update.  In this case, the user total should be `427` but it's displaying the total users, `875`

![image](https://user-images.githubusercontent.com/73545194/105353316-0bb93100-5c2a-11eb-8c92-7a0030011e79.png)

**Comment by eugene-manuilov** [comment]
@wpdarren @johnPhillips if I remember correctly, the `Others` shouldn't be selectable and the user count graph should display the total number of users as it does when nothing is selected.

@johnPhillips could you please create a follow-up PR that reset the dimension color to an empty string when the `others` slice is selected? See how we do it for the `dimensionValue` variable.

**Comment by johnPhillips** [comment]
@eugene-manuilov @wpdarren I think I have managed to address this in https://github.com/google/site-kit-wp/pull/2666

**Comment by felixarntz** [comment]
@wpdarren @eugene-manuilov The Others slice shouldn't affect the graph. It should still be "normally" selectable so that it is highlighted and shows the tooltip until unselected, but it should never alter the line chart.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Verified: On the dashboard page the user count graph uses the color of the selected pie slice in the user dimensions chart or the blue color when nothing or the others is selected. Screenshots:  [Other screenshot](https://user-images.githubusercontent.com/73545194/105493875-ed6c3780-5cf4-11eb-97c4-3024f638bda8.png) - [Slice color change](https://user-images.githubusercontent.com/73545194/105493400-51dac700-5cf4-11eb-9de4-0b812c0ef4a9.png)

@felixarntz is there a reason why the 'others' slice in the chart should not be altered?  From a user perspective, if I click the slice I am going to assume that the chart should be updated like the rest of the slices. Just wondering if this might create a few user tickets. I am happy to pass this based on the QAB but just wanted to understand why this decision was made.
