### ISSUE TITLE
Implement framework for "feature tour tooltips"

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2626]
We need to integrate a set of JS components to Site Kit to enable tooltip-based guided tours through new product features. These should be possible to be applied across any Site Kit-owned screen and encompass one or more tooltips that can be navigated through sequentially.

<img width="606" alt="Screen Shot 2021-01-14 at 1 52 28 PM" src="https://user-images.githubusercontent.com/3531426/104653644-c3b96d80-566f-11eb-9722-f35d9b21458b.png">

We should try to find a suitable JS library that helps us with this issue, rather than implementing everything ourselves.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should include a set of reusable JavaScript components (e.g. `TourTooltips` with `TourTooltip` children) that can be used to display a tooltip-based guided tour through certain new product features.
* The `TourTooltips` component should be configurable with one or more `TourTooltip` instances that have a sequential order.
    * Each tooltip should follow the [design of the blue tooltips in this Figma file](https://www.figma.com/file/RL66yqI7W2Gdlt910KFVYK/Tooltips-%2F-coachmarks?node-id=105%3A65). They're using Material design, so we should use a corresponding dependency for Material tooltips if available.
    * The headline and body content should be custom-specified per `TourTooltip`. It should be possible to use basic HTML elements like links, emphasized content etc in the copy.
    * Every tooltip should have an "x" in the upper right corner which dismisses the tooltips sequence overall.
    * There first tooltip in the sequence must always have a "Next" button which goes to the next tooltip (unless it is also the last tooltip, see below).
    * The last tooltip in the sequence must always have a "Got it" button which dismisses the tooltips sequence overall.
    * All tooltips in between should have both a "Back" and "Next" button for navigating between tooltips.
* Every tooltip should be attached to a certain DOM element on the page, and the tiny triangle on its edge should point to that element (the triangle can appear on any edge of the tooltip). Tooltips should appear in a way that they're always within the viewport, and if the next tooltip is outside of the viewport, it should be scrolled there.
* While a tooltips tour is currently shown, no interaction with other elements on the screen should be possible (i.e. there should be an overlay).
* When a sequence of tooltips is dismissed, it should be stored in `localStorage` (for now) so that the tooltips do not show up again for that user.
    * This will be a temporary solution, so we shouldn't put any effort into building a wrapper around `localStorage` or any nice API. We can use the browser API as is.
* There should be a Storybook story of _some_ suitable UI (let's try to keep it simple) with a functioning tooltips guidance overlay, using the new components. The example doesn't need to be realistic, but it needs to show correct behavior of the tooltip tour.

## Implementation Brief

- Add `react-joyride` as a dependency. Docs for the library can be found [here](https://docs.react-joyride.com/).
- Create a `TourTooltips` component, which acts as a wrapper around a `Joyride` custom implementation that's set up for our specific use case. [Can use this gist as a base to get a head start.](https://gist.github.com/caseymorrisus/5452952e7ec8d561c95cf91aa4a6d53c)
    - Uses new `core/ui` datastore to set and retrieve values for `stepIndex` and `run` .
        - `stepIndex` controls the current step of the tour, passing this prop turns `react-joyride` into controlled mode which requires us to keep and update internal state ourselves as a response to events passed into `handleJoyrideCallback`.
    - Uses `useLocalStorage` hook from `react-use` to simplify "reactifying" (re-rendering automatically based on value updates) Local Storage `get` & `set` methods.
        - Adds `shouldSkipTour`  (`true` or `undefined` being possible values) and `setShouldSkipTour` method to set skippable state in Local Storage.
    - Has `startTour` method to conditionally start tour using `setValue( runKey, true )` behind a Local Storage value existance check via `shouldSkipTour`.
    - Has `changeStep` method to conditionally change step forwards or backward depending on action sent (eg: `ACTIONS.PREV` should go back a step).
        - `index` and `action` args are passed in directly from the `react-joyride` [callback](https://docs.react-joyride.com/callback).
    - Has `endTour` method to stop tour using `setValue( runKey, false )` as well as setting Local Storage item using `setShouldSkipTour( true )` to stop repeat tours.
    - Has `handleJoyrideCallback` method to respond to `react-joyride` event, status, & action callbacks [as defined here](https://docs.react-joyride.com/callback).
        - Uses various combinations of events, statuses, & actions to determine how to update our own internal state (`changeStep → next | prev` || `endTour`)
        - `shouldChangeStep` needs to check for `hasCloseAction` to avoid unnecessary hook calls when checking against `ACTIONS.CLOSE` as `react-joyride` also sends `EVENTS.STEP_AFTER` which would trigger an unnecessary `changeStep` call.
    - Uses `useMount` hook to call `startTour` after content has been mounted.
    - Maps `steps` values to create `parsedSteps` with otherwise repeated (non-necessary) info.
    - Can pass `options` object to `styles` prop of `Joyride` component to override styles (arrow, text, etc).
    - Passes `TourTooltip` component (created in next step) to `tooltipComponent` prop of `Joyride` component to allow custom functionality (indicators).
- Create the `TourTooltip` component that is passed into `Joyride`. [Can use this gist as a base to get a head start.](https://gist.github.com/caseymorrisus/f5b9c6db0398621eeeb1bb27499a64f8)
    - Creates `indicatorArray` to display indicator dots based on the number of total steps. Sets active style if `indicatorIndex` is equal to `index` (index of current step of tour).
    - Displays back button if not the first step (`index !== 0`), gets functionality automatically by spreading `backProps` to button.
    - Display next button if not the last step (`! isLastStep`), gets functionality automatically by spreading `primaryProps` to button.
    - Displays final button (Got it) if it is the last step (`isLastStep`), gets functionality automatically by spreading `closeProps` to button.
    - Display close button (X), which must be absolutely positioned, gets functionality automatically by spreading `closeProps` to button.
- Items in gists are unstyled and use generic elements (`button`, `div`). We should use components from `material-components` to enable the majority of desired styles (and adding [custom styles](https://docs.react-joyride.com/styling) where necessary).
    - There doesn't seem to be a single component to handle styling but it looks like we can use a combination of the following low-level material components to achieve the desired result with the addition of minimal CSS: `Card`, `CardActions`, `CardContent`, & `Button`.
        - [Material UI docs for Cards](https://material-ui.com/components/cards/#complex-interaction)
        - [Material Design docs for Cards](https://material.io/components/cards#anatomy)
            - See [Anatomy section](https://material.io/components/cards#anatomy) for quick access to relevant info on the `Card` component.
- Close button (X icon in top right corner) should be exported from Figma file and replace text within gist.
- Integrate `TourTooltips` within Storybook story to demonstrate the correct behavior of the component. Module components should have enough elements present (many stories are single elements) to properly demonstrate a tour.

**Example Implementation:**

```jsx
const steps = [
  {
    target: '.step-1',
    title: 'Title for step 1',
    content: 'This is the first step'
  },
  {
    target: '.step-2',
    title: 'Title for step 2',
    content: 'This is the second step'
  },
  {
    target: '.step-3',
    title: 'Title for step 3',
    content: (
      <p>
        This is content for step 3, <a href="#">wow!</a>
      </p>
    )
  },
];

// ... within render method using a `feature` tour as an example
<TourTooltips steps={steps} tourID="feature" />

```

### Test Coverage

* Jest tests should be added for feature tour functionality (next, back, close, not displaying tour again, etc). 
* Storybook story will add VRT tests.

### Visual Regression Changes

* Storybook story will add VRT tests.

## QA Brief

I added the `QA: Eng` label as this feature is only exposed within Storybook for the associated PR. Test steps mimic very closely with unit tests, but it can't hurt to double-check — this verifies unit tests are valid.

### General Tests

- Verify `content` renders correctly — corresponds to "Headline" in the UI screenshot above.
- Verify `title` renders correctly — corresponds to "How the new feature..." in the UI screenshot above.
- Verify `tourID` usage within LocalStorage key, eg: `sitekit-${ TOUR_ID }__has-encountered-tour`

### State Changes via Custom Callback Handler

**Next Step Button**

- Verify switches tour to next step when clicked.
- Verify does not exist if on the last step.

**Back Button**

- Verify switches tour to the previous step when clicked.
- Verify does not exist on the first step.

**Close Tour Button — SVG (X) Icon**

- Verify tour closes when clicked.
- Verify tour completion status is persisted.

**Close Tour Button — "Got it" Button on Last Step**

- Verify tour closes when clicked.
- Verify tour completion status is persisted.

**LocalStorage Conditional Rendering**

- Verify tour starts when no persisted tour status is found.
- Verify tour does not start when persisted tour status is found.

## Changelog entry

* Implement React components for rendering tooltip tours.

**Comment by felixarntz** [comment]
@caseymorrisus IB mostly LGTM, a few follow-up comments:
* Currently you're handling state within the components. Our usual approach is to use the datastore (e.g. we could use the `core/ui` store from #2456 to store the current step. It should be possible with the `react-joyride` library to pre-open a specific step right? This would come in handy for Storybook if we wanted to have e.g. individual stories per opened tooltip.
* Since we will have several different tours, it might be useful to give every `TourTooltips` an ID that identifies the tour (we will need this anyway to persistently store dismissed tooltip tours on the server). That ID could be used to manage state as well (e.g. `select( CORE_UI ).getValue( `${ tourID }Step` )`). Since we wouldn't need to add extra datastore infrastructure and could use the `core/ui` store, I think that's worth including here, rather than relying on `useState`.
* Did you search for any Material component that has the tooltip design from the Figma file? I somewhat expected that to already exist since the Figma design is not our own and just comes from what's regularly used in e.g. various Google service frontends. If there is none and we have to implement the design ourselves, that's okay, but I think this should be clarified a bit in the IB since it's a considerable amount of CSS work.
* The estimate seems a bit on the low end. You've already done a bunch of prerequisite work with the gists, but overall I'd still expect this to be at least an 11, maybe a 15 - what do you think?

**Comment by felixarntz** [comment]
@caseymorrisus One follow-up question that I thought about: The Figma file has the DOM element that the tooltip is applied to highlighted, it darkens out all the rest of the UI. Did you consider that, is this possible to achieve with `react-joyride`?

**Comment by caseymorrisus** [comment]
@felixarntz I just pushed up changes to the associated gists for the `TourTooltips` and `TourTooltip` components as well as the descriptions of required work within the IB itself. 

### Addressing your concerns:
- Pre-opening `react-joyride` is achieved via `stepIndex` prop to control the active step (requires complete control, no initial values).
- Modified to use `core/ui` datastore to handle tour `run` and `stepIndex` values and removed `useState`.
- `tourID` prop was added to top-level component alongside `core/ui` implementation to handle multiple tours in-store.
- I searched through the Material Design & UI docs (among a few others) and could not find a suitable high-level component but was able to find multiple composable low-level components (`Card`, `CardActions`, & `CardContent`) which should get us very close (assuming they aren't the exact intended components already). See [Anatomy](https://material.io/components/cards#anatomy) section for quick access to relevant info on the `Card` component.
- Highlighting the active targeted DOM element and adding a darkened overlay is default behavior within `react-joyride` and can be customized with multiple props (highlight is `spotlight` internally & overlay is `overlay`).

**Comment by felixarntz** [comment]
@caseymorrisus IB ✅ 

I'm still a bit concerned about the estimate on this, but since you've already done a bunch of work via the gists, as long as you take this issue for execution it should be okay. What I'm mostly thinking about regarding the estimate is that this is a completely new feature and we may run into some technical quirks, or the CSS part might require some polishing iterations. But let's go with this as is; would be great if you could pick this up early next week!

**Comment by ivankruchkoff** [comment]
QA ✅

All the steps in the QA brief checked out.
