### ISSUE TITLE
Settings not preserved after granting additional scope

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2627]
## Bug Description

When performing an action that requires more than the default read-only scopes, we request the additional scope needed on-the-fly; e.g. creating a new property or profile in Analytics setup/settings. While the underlying functionality (store snapshot/restore) is working as expected, a recent change is causing the settings rollback to be triggered after the state is restored which essentially "forgets" the previous settings state which leaves the form in a different state since the "create" options are no longer selected.

## Steps to reproduce

1. Set up Analytics
2. Edit Analytics settings to create a new property (without previously granting scope)
3. Submit (pop-up should prompt to grant additional scope)
4. Grant scope
5. Upon returning to settings UI, notice that property select is no longer on the "create" option

## Additional Context

This is likely due to changes/refactoring to `SettingsApp` where the initial render may not have `isEditing` as `true` which would cause the settings rollback to be triggered since settings would have changed. See #2187.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Closing this in favor of tracking via #2187 where we'll need to fix this for the same release.
