### ISSUE TITLE
Redirecting to homepage after signing in - on a Cloudflare enabled site

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2628]
## Bug Description

[One user in the support forums](https://wordpress.org/support/topic/plugin-wont-connect-to-my-account-after-adding-google-tag-manager/#post-13911599) is encountering being redirected after sign in at the setup stage in Site Kit. This started to occur after the Tag Manager module setup. 

The user has attempted many troubleshooting steps, including the following:
- Modified site URLs
- Performed setup check using Health Check & Troubleshooting Plugin
- Reset site on the SK service
- [Site Health info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiOHQgCYTYsRLmjYto5oO20tmRY2uGdg0gDXJk99rNkroOz22gng2kgKIuqEeXJdak) provided

The user has provided useful information via a video in their Site Health information, displaying Content Security Policy errors. At present the site uses DDOS via their Cloudflare configuration, awaiting further tests with Cloudflare configuration changes on test site with similar setup. 

## Additional Context

 - Initially during setup there were mismatching URLs evident from checking REST endpoints
 - Site Kit 1.23.0
 - Plugin worked fine previously, occurred during Tag Manager setup
 - Site was not defined as fully https in general settings at some stage

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
[Another possible impacted user](https://wordpress.org/support/topic/google-site-kit-continuously-asking-for-sign-in) - awaiting response after resetting the site on the Site Kit service . The same site also features Cloudflare DDOS protection & HCaptcha integration.

**Comment by jamesozzie** [comment]
Useful insights provided by the user to replicate the issue:
1. Install an SSL certificate from Cloudflare at hosting level (on a site already connected to Site Kit via http)
2. Activate bot fight mode from the Firewall >> Tools section in Cloudflare

**Comment by abdullah1908** [comment]
Hey @jamesozzie ,

Here is the activity done so for on Cloudflare server & unable to reproduce the issue:
- SSL configured on demo
- Fight Mode ON
- Reset Site Kit Settings
- Configured Search Console Property
- Configured Analytics
- Configured Page Speed

**Comment by jamesozzie** [comment]
Additional details in #1558

**Comment by jamesozzie** [comment]
Performed some additional testing on a Cloudflare site setup
- Setup WordPress on a popular hosting provider (non https)
- Pointed nameservers to Cloudflare, confirmed successful records applied at Cloudflare level
- Left all Cloudflare configuration settings [as default](https://i.imgur.com/6ZTEp1t.png) (with no SSL applied at service level)
- Installed Site Kit 1.24.0 - Setup with no issues, Analytics & GTM also connected with no issues
- There is an option to apply an [Origin Certificate](https://imgur.com/DjRN5SV) via Cloudflare although from the current shared hosting environment used this was not possible
- Switched "SSL/TLS encryption mode" to flexible and re-attempted SK setup  with Analytics - no issues
- Switched "SSL/TLS encryption mode" to "Full (strict)" and re-attempted SK setup  with Analytics - no issues
- Switched to "[Under Attack Mode](https://imgur.com/MsiKMek)" and encountered a "Your site may not be ready for Site Kit" notice. Used the same browser session while logged into Cloudflare, with the service maybe having whitelisting my IP
- Clicked on "Proceed" regardless and I was directed to a Cloudflare DDOS page, which eventually allows me to access the "Sign in with Google" screen
- Signed in with no issue, with Site Kit connected success. 
- Setup Analytics - no issue (new account selected)
- Setup Tag Manager - no issue (new account selected)

Following up with impacted user for additional information

**Comment by bethanylang** [comment]
@jamesozzie Any update here?

**Comment by jamesozzie** [comment]
@bethanylang No update from the user impacting, with their site not found on the service. As I believe this is an edge case lets close this one. We can reopen if this is raised by another user.
