### ISSUE TITLE
The analytics not showing exact price. and maybe cause that I get ads limit

### ISSUE THREAD

**Issue by rachidev84** [google/site-kit-wp#2633]
My currency is MAD , MOROCCAN DIRHAMS, 1 MAD = 9 USD
this is the screenshot: https://i.postimg.cc/PNGddnYr/aaaa.png
Today I get ads limit : 10 click and I earn 0.5 dollars. google says it from invalid traffic. ( all traffic comes from reddit and facebook users)
I think google kit plugin somehow caused this problem cause of showing wrong earning.

**Comment by jamesozzie** [comment]
@rachidev84 Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist.  

Please include as much relevant information to your support topic. From looking at the context already provided it would be useful to know whether the same information appears within your AdSense dashboard from adsense.google.com, which can be accessible by clicking on the "_View full stats in AdSense link_" from within your Site Kit AdSense dashboard:

![image](https://user-images.githubusercontent.com/41326532/104921143-d645e680-5990-11eb-9e5d-617728415ecd.png)
