### ISSUE TITLE
Site Kit Dashboard Tests | Date range filter 

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#264]
Set up Site Kit Dashboard Tests | Date range filter 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Dashboard: Test user selecting different date range causes stats across the page to update accordingly
    * when user switches back to date range from before, same data like before shows up
    * include one "zero data" API response in this which should only apply to the selected timeframe (e.g. going from 28 days to 7 days) --> it should result in a no data CTA
* Dashboard Details: Test user selecting different date range causes stats across the page to update accordingly
    * when user switches back to date range from before, same data like before shows up
* Search Console module screen: Test user selecting different date range causes stats across the page to update accordingly
    * when user switches back to date range from before, same data like before shows up
* Analytics module screen: Test user selecting different date range causes stats across the page to update accordingly
    * when user switches back to date range from before, same data like before shows up

## Implementation Brief

* n/a

## Changelog entry

* Site Kit Dashboard Tests | Date range filter

**Comment by tofumatt** [comment]
Looks good:

<img width="703" alt="Screenshot 2019-09-25 18 46 36" src="https://user-images.githubusercontent.com/90871/65626746-debd2580-dfc5-11e9-96f0-8c0233239ce7.png">
<img width="698" alt="Screenshot 2019-09-25 18 45 16" src="https://user-images.githubusercontent.com/90871/65626749-df55bc00-dfc5-11e9-9bd8-7c4f7323d27e.png">

Full test suite passed as well 👍
