### ISSUE TITLE
Decouple date utils from core/user datastore

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2641]
## Feature Description

In #1925 we moved date range parsing to the client, which introduced new date-related infrastructure to the `core/user` store. As part of this, multiple date-related utilities were introduced, such as `getDateString`, `getPreviousDate`, `getPreviousWeekDate`, and `isValidDateInstance` to name a few.

These utilities are completely independent of the datastore and relevant to other parts of the codebase. As such, we should move them to be under the generic `assets/js/utils` directory instead.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All date range utility functions should be moved under a new `assets/js/util/date-range/` directory which should contain all relevant utilities from these locations
    * `assets/js/googlesitekit/datastore/user/utils/`
    * `assets/js/util/date-range.js`
* All date range utilities should be exported from the index of this directory

## Implementation Brief

See https://github.com/google/site-kit-wp/pull/3206
* Extract out remaining functions in `/assets/js/util/date-range/index.js` so this file just exports
* merge #3206

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check that files have been refactored as per AC and that tests pass and everything builds.
* No change expected to user

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by Hazlitte** [comment]
**QA Eng ✅**
