### ISSUE TITLE
Improve (Other) & Others Dimension for new All Traffic widget 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#2642]
## Bug Description

For the new Analytics module on Site Kit Dashboard, under the pie chart on `channels` dimension, there is a slice for `(other)` and `others` which is confusing.

On #2425 @felixarntz commented. 

> Regarding the "(other)", I agree that's confusing, but it's expected right now because the way that the API segments that is likely different from our approach for "Others" (which is to simply cut off entries other than the first five). We cannot omit "Others" because to us "(other)" is a dimension like any other, and it looks like the Google API response also has entries after that, which wouldn't be reflected if we just stripped our "Others".
> 
> Let's think about this separately and not worry about it as part of the initial implementation.

This ticket was created to start the discussion on if this can be improved to avoid confusion. 

## Steps to reproduce

Have a website connected to Site Kit that has a good amount of traffic. 

1. Go to 'Site Kit Dashboard'
2. Scroll down to 'All Traffic'
4. Look for the new Analytics module with users and the pie chart. 

## Screenshots

![image](https://user-images.githubusercontent.com/73545194/105041002-738e4100-5a9d-11eb-902d-bfb3e16097f8.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tooltips for the All Traffic widget pie slices should be adjusted in certain cases:
    * If the value is "(other)", the tooltip should include an external link below the regular numbers and percentages: _Learn more about what "(other)" means_ It should link to `https://support.google.com/analytics/answer/1009671` (via `getGoogleSupportURL` selector).
    * If the value is "(not set)", the tooltip should include an external link below the regular numbers and percentages: _Learn more about what "(not set)" means_ It should link to `https://support.google.com/analytics/answer/2820717` (via `getGoogleSupportURL` selector).

## Implementation Brief

(Use http://localhost:9001/?path=/story/analytics-module-components-dashboard-all-traffic-widget-v2--loaded with locations to check what a chart with both "Others" and "Not set" values look like.)

* Change the source link if the `source` is `"others"` and add another link that `Learn more about what "(other)" means` with a `getGoogleSupportURL` link to https://support.google.com/analytics/answer/1009671
* Check to see if the `source` is `"(not set)"` (see example of how this is done with "others" here: https://github.com/google/site-kit-wp/blob/1680f18750ea7fc778d39a5a5feab64d0d1b24d0/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/UserDimensionsPieChart.js#L162-L170) and add the text `Learn more about what "(not set)" means` with a `getGoogleSupportURL` link to https://support.google.com/analytics/answer/2820717

### Test Coverage

* No additional tests needed for this.

### Visual Regression Changes

* This likely won't change anything aside from hover/active states on the pie chart so should not have VRT changes.

## QA Brief
* Visit http://localhost:9001/?path=/story/analytics-module-components-dashboard-all-traffic-widget-v2--loaded 
* Click on the "Locations" tab
* Click on the "Others" slice from the chart. 
* There should be a link in the tooltip, with the label: "Learn more about what "(other)" means" and it should link to https://support.google.com/analytics/answer/1009671
* Click on the "Not Set" slice from the chart.
* There should be a link in the tooltip, with the label: "Learn more about what "(not set)" means" and it should link to https://support.google.com/analytics/answer/2820717

## Changelog entry

* Add contextual documentation links to new All Traffic widget to explain special dimension values "(not set)" and "(other)".

**Comment by felixarntz** [comment]
@wpdarren Thanks for raising this. I've discussed this one with @marrrmarrr. Since this is a regular Analytics dimension value, we shouldn't omit it or alter the results in any way that would differ from how it's displayed in Analytics FE. However, we can help the user by clarifying what this "(other)" special state means (the same applies to "(not set)" which is another special value). I've added ACs accordingly.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- On the 'Others' slice, there is a link in the tooltip, with the label: "Learn more about what "(other)" means" and it links to the correct URL in the QA Brief.
- On the "Not Set" slice, there is a link in the tooltip, with the label: "Learn more about what "(not set)" means" and it links to the correct URL in the QA Brief.
