### ISSUE TITLE
Change SK dashboard to only show either Widgets API-based or legacy version

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2647]
Currently, when running a development build of Site Kit, the Widgets API-based version of the plugin dashboard is displayed on top of its current/legacy version. In preparation for the production rollout, we should modify this behavior so that only one of the two versions is rendered. This also applies to the single URL view.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the `widgets.dashboard` flag is enabled, the dashboard should only render the new Widgets API-based UI, i.e. `DashboardMain` (and its wrapping elements) should not be rendered.
* If the `widgets.pageDashboard` flag is enabled, the single URL / page dashboard ("dashboard details") should only render the new Widgets API-based UI, i.e. `DashboardDetailsModules` (and its wrapping elements) should not be rendered.

## Implementation Brief

* Update the `DashboardApp` component to render the legacy part only if the widget feature flag has falsy value;
* Update the `DashboardDetailsEntityView` component to render the legacy part only if the widget feature flag has falsy value.

### Test Coverage

* Update existing tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* Main and details dashboards should display either new widgets or legacy ones only.

## QA Brief

* Set up the plugin on your local;
* Build development assets using `npm run dev` command and make sure that you see only new widgets on main and details dashboards;
* Build production assets using `npm run build` command and make sure that you see only legacy widgets on main and details dashboards;

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eugene-manuilov IB looks technically good. However, after #2646, which is marked as a blocker, the implementation will slightly change from your IB. It shouldn't change the necessary work though. Can you maybe make the IB less specific and say in both overall components only render the legacy part as an `else` clause to the existing `if` clause for the feature flag?

**Comment by eugene-manuilov** [comment]
Updated. Is it better now, @felixarntz?

**Comment by felixarntz** [comment]
IB ✅

**Comment by asvinb** [comment]
**Dev mode**:
Main dashboard: No `DashboardMain` component found.
Search console dashboard: No `DashboardDetailsModules` component found.

**Prod mode:**
Main dashboard: `DashboardMain` component found.
Search console dashboard: `DashboardDetailsModules` component found.

### QA ✅
