### ISSUE TITLE
Implement logic for triggering feature tour tooltips

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2648]
While #2626 introduces the essential JS functionality for rendering tooltip tours, we'll also need to implement a reliable way of detecting whether a specific tooltip tour should be triggered. For example:

* A tour specific to introducing a newly introduced feature to Site Kit should only be displayed to users that have already used the plugin before. A new user should not be confronted with various tooltip tours for features which for them have "always" been there.
* When a user completes or dismisses a tooltip tour, it should never be displayed to that user again, so it needs to be stored reliably in a persistent way. Using `localStorage` is infeasible, and even for the server-side storage it needs to be ensured that this storage does not get wiped on disconnect/reset like typical `googlesitekit_*` options are.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Exposing the user's initial Site Kit version in JS
* A new JS selector `getInitialSiteKitVersion()` should be added to the `core/user` store. It should receive the value of the `Core\Authentication\Initial_Version` option from #2692, which should be initially provided on pageload via PHP-to-JS data on `_googlesitekitUserData`.

### Storing a user's completed/dismissed tours
* A new user setting `googlesitekitpersistent_dismissed_tours` (array of strings; the `googlesitekitpersistent_` prefix must be used to prevent the option from being deleted on reset/disconnect) should be introduced and registered.
* A new REST datapoint `GET:core/user/data/dismissed-tours` should be introduced. It should return an array of dismissed tour slugs (basically the current value of the current user's `googlesitekitpersistent_dismissed_tours` option). This endpoint should be added to the REST endpoints to be preloaded on pageload.
* A new REST datapoint `POST:core/user/data/dismiss-tour` should be introduced which requires a `slug` parameter. It should add the tour identified by `slug` to the current user's `googlesitekitpersistent_dismissed_tours` option. It should return the updated list of dismissed tours.
* A new JS selector `getDismissedTours()` should be added to the `core/user` store, relying on the response from `GET:core/user/data/dismissed-tours`.
* A new JS selector `isTourDismissed( slug )` should be added to the `core/user` store, relying on the `getDismissedTours()` selector to check whether the tour identified by `slug` is included in that list.
* A new JS action `dismissTour( slug )` should be added to the `core/user` store, relying on calling the `POST:core/user/data/dismiss-tour` datapoint. It should also update the dismissed tours stored on the client, via the response from the API datapoint.

### PHP 

* Create a new `Dismissed_Tours` class in the `Core/Feature_Tours` namespace (new), extending `User_Setting`
	- Set the `OPTION` class constant to `googlesitekitpersistent_dismissed_tours`  
	This should be annotated to call attention to the naming convention which is intentionally different than our normal `googlesitekit_` prefix such that it is ignored by our normal reset routine
	- Add a public `add( string $slug )` method
		- loads the current value of the setting, ensuring it is an array
		- adds the given `$slug` to the list
		- saves the new value
	- Overload the `get_sanitize_callback` method, providing a function which ensures an array of unique values is always returned
* Create a new `REST_Controller` class in the `Core/Feature_Tours` namespace (should not extend `WP_REST_Controller`)
	- The constructor should require a `Context` instance, and accept optional `User_Options` and `Dismissed_Tours` instances
	- Add a `get_rest_routes` method which returns `REST_Route` instances for the following new endpoints as described in the ACs:
		- `GET:core/user/data/dismissed-tours`
			- Essentially returns a response as `dismissed_tours->get() ?: array()`
			- Requires `Permissions::VIEW_DASHBOARD`
		- `POST:core/user/data/dismiss-tour`
			- Requires `$request[data][slug]` to be passed as a string (`api.set` passes `data`/body params through under a top-level `data` key)
			- Merges the given `slug` into the
			- Requires `Permissions::VIEW_DASHBOARD`
	- Add a public `register` method and add the following:
		- Hook the `get_rest_routes` method onto the **`googlesitekit_rest_routes`** filter  
		(see `Authentication` for an example of this hook)
		- Hook a filter callback onto **`googlesitekit_apifetch_preload_paths`** to include the new `GET:core/user/data/dismissed-tours` route in the list of paths  
		(see existing uses of this filter for examples of its use)
* Create a new `Feature_Tours` class in the `Core/Feature_Tours` namespace
	- The constructor should require a `Context` instance, and accept optional `User_Options`
		- It should instantiate and store a `Dismissed_Tours` instance as a class property (`dismissed_tours`)
		- It should instantiate and store a `REST_Feature_Tours_Controller` instance as a class property (`rest_controller`)
	- Add a public `register` method and add the following:
		- Call `register` on `dismissed_tours`
		- Call `register` on `rest_controller`
	- Instantiate this class and call its `register` method in the **`init`** callback in `Plugin::register`
* Update filter callback in `Authentication` on **`googlesitekit_user_data`** to set `initialVersion` in the user data via the class’ `initial_version` instance property (`initial_version->get()`)
	- Note there are currently 2 different hooks on `googlesitekit_user_data` which are unnecessarily separate and should be combined

### JS

* Update `assets/js/googlesitekit/datastore/user/user-info.js` with a new `getInitialSiteKitVersion` selector
	- Will function like `selectors.isVerified()`, returning `initialVersion` from `state`
	- Also needs a resolver to populate the data if not set yet
* Extend `core/user` datastore
	- Create a new store partial in `assets/js/googlesitekit/datastore/user/feature-tours.js`
		- Use `createFetchStore` to create fetch infrastructure with a base name of `getDismissedTours`
			- The `controlCallback` should return `API.get` to `core/user/data/dismissed-tours` (without cache)
			- THe `reducerCallback` should set `dismissedTours` with the response
		- Add `initialState.dismissedTours = undefined`
		- Add `selectors.getDismissedTours`, returning `{(string[]|undefined)}`
		- Add `resolvers.getDismissedTours`, which dispatches `fetchGetDismissedTours` if `dismissedTours` is `undefined`
		- Add `selectors.isTourDismissed( slug )` as a registry selector which selects `getDismissedTours` and returns `true` if the list contains the given `slug`, `false` if it does not, and `undefined` if the selector also returns `undefined` (i.e. not resolved yet)
		- Add `actions.dismissTour( slug )` which should add the given `slug` to the list of `dismissedTours` immediately after which it should dispatch `fetchDismissTour( slug )`
		- Use `createFetchStore` to create fetch infrastructure with a base name of `dismissTour`
			- Requires that a string `slug` is provided
			- The `controlCallback` should return `API.set` to `core/user/data/dismiss-tour` with the given `slug` in the request data
			- The `reducerCallback` should set `dismissedTours` with the response by dispatching the `receiveGetDismissedTours` action from the first fetch store

### Test Coverage

* Add PHPUnit tests for `Dismissed_Tours`
* Add PHPUnit tests for `REST_Controller`
* Add PHPUnit tests for `Feature_Tours`
* Update `AuthenticationTest` to cover changes to filtered user data
* Add Jest tests for new selectors and non-fetch actions

### Visual Regression Changes

* N/A

## QA Brief

Note dismissed feature tours are not deleted in any way yet so you may want to test with a fresh site, or a new user to start from a blank slate

* Do minimal set up to get to Site Kit dashboard
* From the browser console, get the list of dismissed tours like so:
	```
	googlesitekit.data.select( 'core/user' ).getDismissedTours()
	```
* You should see `undefined` at first, and this should trigger a XHR request to a Site Kit rest endpoint `core/user/data/dismissed-tours`
* Run the same command again after a second or two and you should see an array `[]`
* Now run this command to simulate dismissing a tour:
	```
	await googlesitekit.data.dispatch( 'core/user' ).dismissTour( 'tour-a' )
	```
* You should get a `response` and `error` back.
	- The `response` should be a list of all of the dismissed tours every time you call this
	- The `error` should be empty
* It should never show duplicate tours after using the selector above, or dispatching the `dismissTour` action
* Once a tour is dismissed, check the other selector for testing if it is:
	```
	googlesitekit.data.select( 'core/user' ).isTourDismissed( 'tour-a' )
	```
* This should return `true` or `false` depending on if the given tour slug is in the list of dismissed feature tours
* One more selector to try:
	```
	googlesitekit.data.select( 'core/user' ).getInitialSiteKitVersion()
	```
* This will likely return the current version of Site Kit, but it only returns the first version of Site Kit you used. We aren't able to know from previous versions so this will be inaccurate for previous users but it will work fine for our needs.
* The initial Site Kit version, and the dismissed tours values should not be deleted by disconnect or plugin reset

## Changelog entry

* Implement REST datapoints and JS datastore infrastructure for getting and dismissing tooltip tours.

**Comment by aaemnnosttv** [comment]
@felixarntz IB ready for review!

One thing I didn't include here (perhaps warrants its own issue) is the need to extend our E2E infra with a utility to reset everything – including persistent values like these new ones. As it is now, they would linger and leak between tests. It shouldn't make a difference now, but will bite us later if we don't preempt it.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> One thing I didn't include here (perhaps warrants its own issue) is the need to extend our E2E infra with a utility to reset everything – including persistent values like these new ones. As it is now, they would linger and leak between tests. It shouldn't make a difference now, but will bite us later if we don't preempt it.

Couldn't that be a fairly simple utility, like a mini REST endpoint that deletes the options? I feel like that would be good to include here, to avoid unexpected changes from these values persisting.

The IB otherwise looks mostly good, but some feedback on naming below.

> Create a new `Dismissed_Tours` class in the `Core/User` namespace

> Create a new `REST_Feature_Tours_Controller` class in the `Core/User` namespace

> Create a new `Feature_Tours` class in the `Core/User` namespace

Why use this namespace? It looks like this would be introducing a new pattern where we use namespaces according to JS stores. That's a good idea to discuss, but that would be a pattern to then adopt further. I don't think we should intertwine this with existing namespaces though as that would get confusing. This namespace would mostly be relevant for the REST API which is why this is related to our JS datastores at all. Maybe REST controllers could go into `Core\REST_API\Controllers` as root namespace, and then we could still have a sub-namespace for where this belongs (e.g. in regards to JS stores). For example, this one could be `Core\REST_API\Controllers\Core_User\REST_Feature_Tour_Controller`.

The downside of this approach is it puts all REST controllers together and thus decouples them from their feature-specific usage, i.e. from other related classes.

The alternative would be to stick with the existing feature-specific approach and simply define a new `Core\Feature_Tours` namespace for all of the above classes. I think at this point that's the path I'd prefer as it is simpler and doesn't require us to rethink the whole structure.

> - Add `actions.dismissTour( slug )` which should add the given `slug` to the list of `dismissedTours` immediately after which it should dispatch a fetch request to `fetchSetDismissTour`
> - Use `createFetchStore` to create fetch infrastructure with a base name of `setDismissTour`

This should use a base name of `dismissTour` (and the fetch request should be to `fetchDismissTour` accordingly), since the base name should always match the public action / selector name. Otherwise the error triggering would key the errors incorrectly.

**Comment by aaemnnosttv** [comment]
> Couldn't that be a fairly simple utility, like a mini REST endpoint that deletes the options? I feel like that would be good to include here, to avoid unexpected changes from these values persisting.

@felixarntz sure, that's what I had in mind and was going to include it originally but this isn't the first issue to introduce such an option (that would have been #2692). I've added it to the IB, but it isn't really needed yet so given the size of the issue already, this part could easily be extracted into a separate issue.

> Why use this namespace? It looks like this would be introducing a new pattern where we use namespaces according to JS stores.

I wasn't intending to mirror the name of the datastore, but it just seemed like the right namespace to use. I don't think that we should avoid using a namespace because we use a similar organization on the client.

> The downside of this approach is it puts all REST controllers together and thus decouples them from their feature-specific usage, i.e. from other related classes.

Agreed, I thought about it going in `REST_API` as well and came to the same conclusion.

> The alternative would be to stick with the existing feature-specific approach and simply define a new `Core\Feature_Tours` namespace for all of the above classes. I think at this point that's the path I'd prefer as it is simpler and doesn't require us to rethink the whole structure.

Sounds good to me 👍 

> This should use a base name of `dismissTour` (and the fetch request should be to `fetchDismissTour` accordingly), since the base name should always match the public action / selector name

👍

**Comment by felixarntz** [comment]
@aaemnnosttv IB ✅ 

I've split out the e2e/CLI-related parts into a new issue #2748 as you suggested. The IB parts you added I moved there as is, those are good to go as well. I've added an estimate of 7 for the other one, that should be reasonable.

**Comment by felixarntz** [comment]
@fhollis Did you accidentally move this back to "IB Review"? I approved it yesterday, so it should be in EB.

**Comment by asvinb** [comment]
Followed QA steps as per screenshot below: ✔️ 
![image](https://user-images.githubusercontent.com/31818/108477991-625b6e80-72ad-11eb-9992-4016b880e462.png)

After plugin reset/disconnect: ✔️ 
![image](https://user-images.githubusercontent.com/31818/108478321-c716c900-72ad-11eb-98a8-4609b606610d.png)

### QA: ✅
