### ISSUE TITLE
Site Kit Dashboard Tests | Dashboard Search

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#265]
Set up Site Kit Dashboard Tests | Dashboard Search

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* Test dashboard post search with title that matches multiple, post titles should be displayed in dropdown
    * user clicks on one of them, then on "View data", is taken to detailed page stats dashboard for that particular URL
* Test dashboard post search with title without match, "No results found" should be displayed in dropdown
* Test dashboard post search with URL that matches, post title should be displayed in dropdown
    * user clicks on it, then on "View data", is taken to detailed page stats dashboard for that particular URL
* Test dashboard post search with URL without match, "No results found" should be displayed in dropdown

## Implementation Brief

* n/a

## Changelog entry

* Site Kit Dashboard Tests | Dashboard Search

**Comment by tofumatt** [comment]
This test is also failing for me, after a fresh checkout/install/site reset:

```
 FAIL  tests/e2e/specs/dashboard/search.test.js (25.834s)
  ● Site Kit dashboard post search › displays results when searching with a post title, and loads
 the details page when clicking View Data

    TimeoutError: Element .autocomplete__option (text: "/hello world/i") not found

      waiting for function failed: timeout 500ms exceeded

  ● Site Kit dashboard post search › displays results when searching with a URL, and loads the details page when clicking View Data

    TimeoutError: Element .autocomplete__option (text: "/hello world/i") not found

      waiting for function failed: timeout 500ms exceeded

  ● Site Kit dashboard post search › displays "No results found" when searching by title if no post is found

    TimeoutError: Element .autocomplete__option (text: "/no results found/i") not found

      waiting for function failed: timeout 500ms exceeded

  ● Site Kit dashboard post search › displays "No results found" when searching by URL if no post is found

    TimeoutError: Element .autocomplete__option (text: "/no results found/i") not found

      waiting for function failed: timeout 500ms exceeded
```

I'm not sure if the timeout here is simply too short, but these are all failing on my MacBook Pro running Node 10.

**Comment by tofumatt** [comment]
I'm getting errors with E2E tests on my machine so I'm leaving this in QA for someone else to test locally.

**Comment by tofumatt** [comment]
All good now!

<img width="695" alt="Screenshot 2019-09-25 18 42 49" src="https://user-images.githubusercontent.com/90871/65625725-4c685200-dfc4-11e9-991b-a367a79722f5.png">

Full test suite ran fine as well, so ✅for QA.
