### ISSUE TITLE
Update tooltip tour components to persistently dismiss tours

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2650]
#2626 introduced tooltip tour JS components, relying on a temporary mechanism to dismiss a specific tour by storing its slug in `localStorage`. #2648 introduced the server-side and client-side infrastructure for persistent storage of such a dismissal, so we now need to switch the JS components to rely on that mechanism.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Instead of storing dismissed tooltip tours in `localStorage`, they should be dismissed via the `dismissTour( slug )` action of the `core/user` store.

## Implementation Brief

* Update the `TourTooltips` component:
  * Use the `isTourDismissed( slug )` selector of the `core/user` datastore instead of checking a variable in the localStorage to determine whether a tour is dismissed;
  * Call the `dismissTour( slug )` action of the `core/user` datastore instead of setting a variable in the localStorage when a tour ends.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Connect Site Kit and set up Analytics.
* Ensure your `googlesitekit_initial_version` user option is set to an old version of Site Kit, below 1.25.0.
* Go to the dashboard, the "All Traffic" widget feature tour should show up.
* Once you've completed it, it shouldn't show again when you reload the dashboard.
* Delete your local storage. When visiting the dashboard now, the tour should _still_ not show again, since it's stored in the WordPress database now as part of this issue.

## Changelog entry

* Implement persistent dismissal of feature tours, stored in the database.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@eugene-manuilov #2626 is now merged.

**Comment by felixarntz** [comment]
@eugene-manuilov Looks like @aaemnnosttv included this in #2934 (PR for #2739). We somewhat forgot to tag this issue here with the release. It's probably fine to keep this in #2934 now, since it's only a small chunk of code there anyway and since #2866 is out of date.

I'll add the release now (keep this issue for tracking) and close the outdated PR.

**Comment by aaemnnosttv** [comment]
Unfortunately the PR where this was introduced broke the story for the `TourTooltips` component.

![image](https://user-images.githubusercontent.com/1621608/112619778-604a7980-8e30-11eb-9a1d-395d353a7b9e.png)

Sending back for a quick followup.

**Comment by felixarntz** [comment]
#3030 (fix for the broken Storybook story) is now merged in `develop` (not urgently needed in `master` since it doesn't affect the release ZIP).

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Can confirm that when the Tooltip tour is completed, and local storage is cleared, the tour does not re-appear on the All Traffic widget in Site Kit Dashboard.  
- Checked the [StoryBoard](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global--tourtooltips) to make sure that the error reported does not appear.
