### ISSUE TITLE
Modify `ModuleApp` to support rendering Widgets API widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2653]
In order to migrate all module pages to use the Widgets API, we first need to modify the `ModuleApp` component so that it can render widgets (i.e. render a separate version of the page in addition to the current/legacy UI).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Modules should be able to register a widget context in JS that is used to render their admin screen via a new `screenWidgetContext` argument for the `core/modules` `registerModule` action.
* All modules that are configured to have their own admin screen in PHP (see `Module_With_Screen`) should also register a `screenWidgetContext`:
    * `moduleSearchConsole` for `search-console`
    * `moduleAnalytics` for `analytics`
    * `moduleAdsense` for `adsense`
    * These context names were already added via #2062, but they should no longer be defined as constants in the core `assets/js/googlesitekit/widgets` module (since they are not really parts of the core infrastructure). They should instead be defined in a `assets/js/modules/*/constants.js` file per module.
* All these modules should also register a single "main" widget area for their own context. This has already been implemented in #2062, however, similar as the contexts, they should no longer be defined in the core `assets/js/googlesitekit/widgets` module. Instead, the widget area slugs should be defined in `assets/js/modules/*/constants.js` per module, and the calls to register every module's widget area should also be moved from `assets/js/googlesitekit/widgets/register-defaults.js` into `assets/js/modules/*/index.js` per module.
* A new feature flag `widgets.moduleScreens` should be added, similar to the existing `widgets.*` flags.
* The module's screen component in JS should, if the above feature flag is enabled, render the widgets for their registered context (_if_ a `screenWidgetContext` for the module is registered) via `WidgetContextRenderer`. The widgets will be implemented later, but the screen should already include a duplicate version of the page's header and footer (see #2646 for related changes to the dashboard screen).

### Screen widget context registration

* Add `screenWidgetContext` argument to the `registerModule` action of `core/modules`.
* Add a `getScreenWidgetContext( moduleSlug )` selector to the `core/modules` store which returns the registered context string, or `null`.
* For Search Console, Analytics, and AdSense:
    * Remove the definitions of module-specific contexts in `assets/js/googlesitekit/widgets/default-contexts.js` and instead specify them in the respective `assets/js/modules/*/constants.js` file (for Search Console and Analytics, add that file), then add them to the `registerModule` call in `assets/js/modules/*/index.js`.
    * Remove the definitions of module-specific widget areas in `assets/js/googlesitekit/widgets/default-areas.js` and their widget area registrations in `assets/js/googlesitekit/widgets/register-defaults.js` and instead specify them in the respective `assets/js/modules/*/constants.js` file, then add every module's screen context-specific `registerWidgetArea` call to the `registerWidgets` function in the `assets/js/modules/*/index.js` file.

### Screen widget context rendering
(This part is a lot similar to the work done in #2646.)

* Add the new `widgets.moduleScreens` feature flag to `feature-flags.json`.
* Rename the `ModuleApp` component to `LegacyModuleApp` and move it into a new directory `assets/js/components/module` (similar to existing `assets/js/components/dashboard`, `assets/js/components/dashboard-details` etc.).
* Introduce a new `ModuleApp` functional hook-based component in `assets/js/components/module`:
    * Require `moduleSlug` as prop.
    * Call the new `getScreenWidgetContext` selector from `core/modules`.
    * Render main Site Kit header UI similar to the existing module-specific components, essentially centralizing these parts, which are currently duplicated across module files:
        * Render the Site Kit header bar via `<Header />`. Include `<DateRangeSelector />` if the module is already connected (via `isModuleConnected` selector).
        * Render the container that will include any module-specific notifications from the REST API, via `<Alert module={ moduleSlug } />`.
        * Remove these two pieces from the module-specific legacy components `AdSenseDashboardWidget`, `AnalyticsDashboardWidget`, and `GoogleSitekitSearchConsoleDashboardWidget`, since they will be rendered within here later. We don't need to duplicate that part since it is completely the same between widget-based and legacy version.
    * If the `widgets.moduleScreens` feature flag is enabled and there is a `screenWidgetContext` for the module, render a `WidgetContextRenderer` for the `screenWidgetContext`:
        * Pass the `className` prop as `googlesitekit-module-page googlesitekit-module-page--${ moduleSlug }`.
        * Pass the `Header` prop with a new `ModuleHeader` component that renders the respective module's `PageHeader` similar to how it is today, relying on module-specific registration data instead of hardcoded values. To render the icon, use the component returned by the `getModuleIcon( moduleSlug )` selector. For the title, use the module name. Then, render a status message like `%s is connected` or `%s is not connected` based on whether the module is connected or not (via `isModuleConnected` selector, see above).
        * Pass the `Footer` prop with a new `ModuleFooter` component that renders a `HelpLink` within a `div` that causes it to render right-aligned.
    * Below (for now unconditionally), render the `LegacyModuleApp` component, which will for now keep the current UI in place that is not based on the widgets API.
* Update `assets/js/googlesitekit-module.js` (`GoogleSitekitModule`):
    * Render the new `ModuleApp` component instead of the (now renamed) `LegacyModuleApp` component.
    * For the required `moduleSlug` prop, pass `googlesitekitCurrentModule.slug`. (This, as well as the other legacy globals in use here, should be refactored away at some point, but not as part of this issue.)

### Test Coverage

* N/A

### Visual Regression Changes

* There should be no visual regressions.

## QA Brief

* With the `widgets.moduleScreens` feature flag enabled, every Site Kit module screen (Search Console, Analytics, AdSense) should now display a secondary version of its UI, on top of the legacy UI.
* As part of this issue, that secondary UI should only be comprised of the duplicate header with the module title, icon and connected state, as well as the duplicate footer, which is the "Help" link. These two areas should look the same as their legacy counterparts below.
* The main content of the new UI should for now be empty, eg:

<img width="1320" alt="Screenshot 2021-02-18 at 22 15 19" src="https://user-images.githubusercontent.com/90871/108428653-cd1d9300-7236-11eb-87ca-8a6973307327.png">

**Follow-up PR-specific (#2949)**
* Activate Analytics or AdSense without completing the module setup
* Navigate to the Site Kit dashboard
* From the admin menu, navigate to the module's dashboard page
* Before this PR, a client side error could be observed briefly before a client-side navigation landed the user back on the module set up screen
    * After this PR, the client side error should no longer happen as the redirect will happen on the server side

## Changelog entry

* Implement infrastructure for rendering widgets in Site Kit module screens.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: All looks as intended.

**Comment by aaemnnosttv** [comment]
⚠️ The changes here introduce a bug where the error boundary component is shown momentarily when doing a client side redirect to the module's setup screen. I'll push a quick follow-up PR to fix it.

**Comment by asvinb** [comment]
- Testing Search Console, AdSense and Analytics pages. The header is showing with empty content.

**Search Console**:
![image](https://user-images.githubusercontent.com/31818/111138802-ce25b400-8599-11eb-9182-8bd15927b38f.png)

**AdSense**:
![image](https://user-images.githubusercontent.com/31818/111138931-f57c8100-8599-11eb-9986-438982f11ac2.png)

**Analytics**:
![image](https://user-images.githubusercontent.com/31818/111139054-17760380-859a-11eb-95d2-fd004c5c8553.png)

- Connected Analytics, did not complete setup and went to the Analytics dashboard page. No errors displayed.

### QA: ✅
