### ISSUE TITLE
Analytics Page Pie Chart Labels Issue

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2655]
## Bug Description

Occasionally pie chart labels are off on /admin.php?page=googlesitekit-module-analytics in pie chart with label _Top acquisition channels over the last 28 days_

## Steps to reproduce

This occurs intermittently, but I've been able to repro twice with the following approach.
1. Start with a fresh site that isn't connected, (delete all options starting with googlesitekit_)
2. Connect site.
3. Connect analytics module by Connecting the Service and picking the account and pressing Configure Analytics.
4. As soon as you've pressed connect service and while you see the progress bar, open the dashboard, and then go to Analytics in sidebar, scroll to Top acquisition channels over the last 28 days as fast as possible.
5. If you're lucky, you've triggered the bug as per screenshot below, it occurred 2 out of 6 attempts in trying to repro on Mac, Chrome ( Version 87.0.4280.141 (Official Build) (x86_64) )

## Screenshots

How it looks when incorrect:
<img width="645" alt="Screen Shot 2021-01-19 at 10 44 19 PM" src="https://user-images.githubusercontent.com/373931/105137543-51e68700-5aa8-11eb-8995-ab703d893762.png">

How it should look:
<img width="702" alt="Screen Shot 2021-01-19 at 10 45 25 PM" src="https://user-images.githubusercontent.com/373931/105137546-5448e100-5aa8-11eb-9116-2b3d1aa43b47.png">

## Additional Context

 - PHP Version: N/A
 - OS: N/A
 - Browser chrome ( Version 87.0.4280.141 (Official Build) (x86_64) )
 - Plugin Version 1.24.0
 - Device: Macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics pie charts should always have their percentage labels centralized in the pie slice. They shouldn't move outside of the pie slice (see above screenshot) unless necessary (e.g. pie slice is very small).
    * This problem seems to not be consistently reproducible. Both @benbowler and @ivankruchkoff have encountered it with the legacy All Traffic dashboard widget.
    * The legacy All Traffic widget will soon be removed, so the bug might no longer be relevant there. However, we still have similar UI in the Analytics module page ("Top acquisition channels over the last 28 days"), so it should be ensured the bug doesn't happen there.
    * Most work of fixing this issue will likely be debugging - if this takes beyond ~5 hours without making significant progress in being able to consistently reproduce the issue, let's re-evaluate whether the effort is worth it.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by asvinb** [comment]
@aaemnnosttv @felixarntz I spent some time trying to reproduce, across different browsers but was unable to. I'am not sure whether we should continue looking into the issue unless we can consistently reproduce it.

**Comment by aaemnnosttv** [comment]
@felixarntz – is this still relevant now that this component was replaced by the new All Traffic widget?

**Comment by felixarntz** [comment]
@aaemnnosttv Ah right - I'm gonna close this. I have at some point seen a similar visual bug with the new one, but not recently. So unless it comes up again, we don't need to do anything about this issue.

**Comment by aaemnnosttv** [comment]
@felixarntz actually I misread the issue. This is about the component on the Analytics module page which still uses this component which looks very similar to the old all traffic widget but is still there at the bottom of the module page.
