### ISSUE TITLE
Basic Module Tests | Search Console (dashboard testing only)

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#266]
Set up Basic Module Tests | Search Console (dashboard testing only)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* n/a

## Implementation Brief

* n/a

## Changelog entry

* Basic Module Tests | Search Console (dashboard testing only)

**Comment by felixarntz** [comment]
Search Console setup should be covered in an E2E issue for the plugin setup flow. Once it's set up, the functionality is trivial and there's no user interaction - so no purpose to test its data display in the Site Kit dashboard, as it's covered by visual regression testing.
