### ISSUE TITLE
Include enabled features in Site Health

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2662]
The enabled feature flags for the site should be included in the Site Health section.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be an `enabled_features` entry in Site Kit's Site Health information.
* It should list all features that Site Kit supports and have the checkmark or x next to them, similar to how we list granted scopes.

## Implementation Brief

* Add a new public static method `get_available_features` to the `Google\Site_Kit\Core\Util\Feature_Flags` class that returns keys from the static `$features` array;
* Edit the `Google\Site_Kit\Core\Util\Debug_Data` class:
  * Add a new private method `get_feature_fields`:
    * Define a new `$value` array;
    * It should grab all features using the `Feature_Flags::get_available_features` method;
    * Loop through all features populating the `$value` array with the feature slug as a key and `✅` or `⭕` as a value based on whether the feature is enabled or not (use `Feature_Flags::enabled( $feature )` to determine it);
      * See the `Debug_Data::get_required_scopes_field` as an example.
    * Return a new array with two fields: `'label' => __( 'Features', '...' )` and `'value' => $value`.
  * Add the `enabled_features` section to the `$fields` array in the `get_fields` method the calls the `get_feature_fields` method to get features.

### Test Coverage

* N/A

### Visual Regression Changes

* The new section should be added to the site health information. It should display available features and their status.

## QA Brief

* Set up the plugin on your local;
* Go to the site health page and make sure that you see the new features list.

## Changelog entry

* Include available and enabled Site Kit features in Site Health information.

**Comment by felixarntz** [comment]
@eugene-manuilov IB ✅ , just one thing:

> Add a new public static method `get_all_features` to the `Google\Site_Kit\Core\Util\Feature_Flags` class

I've updated this to `get_available_features`, see #2683. There's some overlap with that issue, so let's consider that when working on them.

**Comment by cole10up** [comment]
### QA ✅ 

Checked latest development build and confirmed the features status list is now displayed:
![image](https://user-images.githubusercontent.com/57115907/107179736-24487b80-698c-11eb-9e20-57d49ee636a5.png)

Sending to approval
