### ISSUE TITLE
Module Setup Flow | Tag Manager

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#267]
Module Setup Flow | Tag Manager
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
_Note: these ACs describe how the existing flow should be tested. Once important improvements to the flow are made (cf #433), the test should be adjusted to account for these as well._ 

**Case 1: There is no associated tag manager account with that google account** 
* Send user to GTM FE create a container (GTM opens in a new tab)  
* Once completed, user goes back to Site Kit, clicks “re-fetch my account” 
* New account + container appear as pre-selected in drop-down (also an option to set up a new container from the dropdown) 
* User clicks “confirm and continue” 
* GTM code is inserted.

**Case 2: There is an associated tag manager account with that google account** 
* Show drop-down with existing Account and container 
* User selects the account and container 
* User clicks “confirm and continue” 
* GTM code is inserted.

## Implementation Brief

* n/a

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv Yes, the AC should be that the code is placed indeed (just updated it). We don't even cover existing tags for Tag Manager yet (see #433 for that).

**Comment by tofumatt** [comment]
Tested this locally and it works. Not much else to QA for a test passing on Travis, but here we go:

<img width="695" alt="Screenshot 2019-09-20 13 25 52" src="https://user-images.githubusercontent.com/90871/65326791-2e58b700-dbaa-11e9-97d9-472f3d0b99f7.png">
