### ISSUE TITLE
Module Setup Flow | Optimize 

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#268]
Module Setup Flow | Optimize

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
_Note: these ACs describe how the existing flow should be tested. Once improvements to the flow are made, the test should be adjusted to account for these as well._

Once the user clicks "set up Optimize" from the Settings page: 
* Test that the input box + instructions to paste the container ID are displayed. 
* Test that a warning is displayed if the user enters an incorrectly formatted container ID. 
* With GA snippet added by another plugin/user: test that the message _"You disabled analytics auto insert snippet."_ is displayed, as well as instructions how the user can add the Optimize snippet on their own.
* Test that the user is redirected to the dashboard once they click "Configure Optimize", and the success message is displayed: 
_"Congrats on completing the setup for Optimize! To set up experiments and see the results, go to Optimize"_

## Implementation Brief

* n/a

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Note that currently changing the Optimizer ID doesn't silently fail and close the page:

![2019-09-13 14 42 51](https://user-images.githubusercontent.com/90871/64867266-f8a95080-d634-11e9-9281-31f690303c6f.gif)

So it might be worth writing a failing E2E test that doesn't submit an invalid ID (the setup process will not submit one) and enabling it once that bug is fixed.

Also worth noting: this form/input has issues with keyboard accessibility and an `<Enter>` keypress in the input itself does not submit the form. I would expect it to; it might also be worth writing a failing E2E test for that as we should implement that behaviour.

**Comment by tofumatt** [comment]
I'm still working on this, and due to the slow nature of iterating on E2E tests and the number involved (as well as a few gotchas I encountered with selector behaviour for the tabs), I'm bumping this up to a small size.

**Comment by aaemnnosttv** [comment]
> With GA snippet added by another plugin/user: test that the message "You disabled analytics auto insert snippet." is displayed, as well as instructions how the user can add the Optimize snippet on their own.

As for this item, the behavior for an existing tag is the same as if the snippet was disabled via the settings, so this is how it is configured in the test using the API via our `setupAnalytics` utility.

![image](https://user-images.githubusercontent.com/1621608/66807638-246c6e80-ef32-11e9-8d0c-dc859a10f436.png)

**Comment by adamsilverstein** [comment]
The E2E tests passed QA here, moving to Approval.

### Testing procedure
* Run new test added in https://github.com/google/site-kit-wp/pull/627: 
`npm run test:e2e -- tests/e2e/specs/modules/optimize/activation.test.js --no-cache`
* Run complete test suite:
`npm run test:e2e -- --no-cache`

Noting that two tests fail here, however I see the same failures in the `feature/auth-proxy` branch. These failures are unrelated to the work on this issue. Ref https://share.getcloudapp.com/geuYznA0 https://travis-ci.com/google/site-kit-wp/jobs/246718576
