### ISSUE TITLE
Make feature flags definition build-agnostic

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2683]
Following up on #2452, specifically https://github.com/google/site-kit-wp/issues/2452#issuecomment-765586302, we should remove the connection between certain features being automatically enabled based on the build mode. Which ones are active should eventually instead only rely on the remote-controlled service (see #2533) and on a checkbox-based UI in the Site Kit tester plugin (to be implemented by @felixarntz).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `feature-flags.json` file should be modified to be simply an array of all feature flags that exist.
* The `dist/config.json` should be updated accordingly to include that array in a `featureFlags` property. `flagMode` should be renamed to a more usage-agnostic `buildMode`. We should still keep awareness of the build mode, even though it won't be used for now.
* The `Feature_Flags` PHP class should be updated accordingly, to read the array. For each of these features, it should use `false` by default, with the only possible way to change the value being the existing filter. It should receive a new public `get_available_features()` method which simply returns all available features (there's some overlap with #2662 - in case this method already exists, it should be updated as needed).
* The "flag mode" / "build mode"-related pieces should be completely removed from the `Feature_Flags` class. They should instead be added to a new utility class `Build_Mode`, which has public static `get` and `set` methods. It should be initialized together with the `Feature_Flags` class in the `Plugin` main class.

## Implementation Brief

* Update the `feature-flags.json` file to contain an array of features;
* Rename the `flagMode` property in the `CreateFileWebpack` plugin to be `buildMode`;
* Update the `Feature_Flags::enabled` method to use just `FALSE` instead of `$feature_enabled` variable for the `googlesitekit_is_feature_enabled` filter;
* Add a new `Feature_Flags::get_available_features` method that returns `static::$features` property (**update:** modify the existing method introduced via #2662 instead)
* Remove all existing functionality in the `Feature_Flags` class related to the "flag mode";
* Add a new `Core\Util\Build_Mode` flag that has public static `get` and `set` methods that return or set the current build mode for the plugin;
* Update the `Plugin::load` method to call `Build_Mode::set` method instead of `Feature_Flags::set_mode`.

### Test Coverage

* Update the existing tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* N/A

## QA Brief

* A development build should no longer differ in functionality from a production build by default, i.e. there should not be two different versions of the dashboard, user input flow should not be enabled in the development build by default etc.
* Regardless of which build is being used, all features should be deactivated by default. The standard way to toggle features on and off should be the Site Kit tester plugin (version 1.4.0 or higher).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by asvinb** [comment]
- Dev and production builds both render the same dashboard.
- Enabled the `widgets.dashboard` feature flag via the Tester plugin and looked for the `DashboardImpressionsWidget` component on the dashboard, which is displayed only when `widgets.dashboard` is enabled. `DashboardImpressionsWidget`  is present.
- Disabled the `widgets.dashboard` feature flag via the Tester plugin and looked for the `DashboardImpressionsWidget`, and it's not present.

### QA: ✅
