### ISSUE TITLE
Remove custom retry map for exponential retries.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#2688]
## Bug Description

In https://github.com/google/site-kit-wp/pull/2442 / https://github.com/google/site-kit-wp/commit/b1b73c93215f0cd1eac88df8a88dfc7ae561fb7c we added a custom retry map for exponential retries. The main reason we added this was to avoid retrying for lightouseErrors which can return a 500 code even when not retryable.

Since that time, I opened a PR to add this config to the upstream library which has now been merged: https://github.com/googleapis/google-api-php-client/pull/2010. The client config now matches ours, so we can remove our custom config:

https://github.com/adamsilverstein/google-api-php-client/blob/b4aadd3a71213a19a9076af90a1cbef85eec8a83/src/Task/Runner.php#L75-L86

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The exponential retry feature should use the default configuration.
* The PHP API client should be running at least version 2.9.0 (when the upstream change was released)

## Implementation Brief

* In `/includes/Core/Authentication/Clients/OAuth_Client.php`:
  * Remove the retry map array.
  * Remove the line setting the retry config: `$client->setConfig( 'retry_map', $this->retry_map );`
* In `composer.json` update the version for `google/apiclient` to the [latest released version](https://github.com/googleapis/google-api-php-client/releases). (currently 2.9.1). 

### Test Coverage

* No change.

### Visual Regression Changes

* No change.

## QA Brief

* Engineer to confirm the retry map has been removed.

## Changelog entry

* Update Google API client library and remove custom configuration to retry failed API requests as it is now covered in the library itself.

**Comment by felixarntz** [comment]
Noting here that we'll need to require at least version 2.9.0 of the `google-api-php-client` to make this change.

**Comment by felixarntz** [comment]
@adamsilverstein Can you update the ACs and IB based on the above? Afterwards should be good.

**Comment by adamsilverstein** [comment]
👍🏼 Updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by benbowler** [comment]
Added a PR and QA:Eng line.

**Comment by tofumatt** [comment]
QA ✅
