### ISSUE TITLE
Store initially used Site Kit version per user

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2692]
Originally part of #2648, we decided to take the part of storing a user's initially used Site Kit version out of that issue so that we can squeeze it into the current 1.25.0 release. This is necessary because we want to ship the first set of tooltips in the following release, and it requires us to already start collecting active version information before.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new user setting `googlesitekitpersistent_initial_version` (string) should be introduced and registered.
    * The `googlesitekitpersistent_` prefix should be used for any settings that require more persistent storage, **which should only be in specific circumstances**. By using the special prefix, this data will not be wiped on disconnect or reset.
* When a user receives a new access token (action `googlesitekit_authorize_user`) or receives a refreshed access token (new action to introduce: `googlesitekit_reauthorize_user`), the `googlesitekitpersistent_initial_version` option should be set (to the current plugin version) if it wasn't set before.
    * Of course this doesn't work retroactively, but that's fine. This mechanism will allow us in the future to know for every user what version of Site Kit they first used, and we'll be able to provide tooltip contextually.

## Implementation Brief

* Add `Core\Authentication\Initial_Version` class which extends `User_Setting` for the new `googlesitekitpersistent_initial_version`.
* Add protected property for it in `Core\Authentication\Authentication` and instantiate it in the constructor.
* Add `do_action` call for new `googlesitekit_reauthorize_user` to `Core\Authentication\Clients\Google_Site_Kit_Client::fetchAccessTokenWithRefreshToken` in the clause where the access token is set, at the end. It should pass through the response data (in `$creds` variable) similar to the existing related `googlesitekit_authorize_user` action.
* In `Core\Authentication\Authentication`, if the `Core\Authentication\Initial_Version` option value is empty, add a callback to both `googlesitekit_authorize_user` and `googlesitekit_reauthorize_user` which will set the `Core\Authentication\Initial_Version` option value to the current Site Kit version.

### Test Coverage

* Add tests to `AuthenticationTest` class that ensures the `Authentication::register` method adds the new hooks as expected, and also ensure that triggering the hook in that case results in the option being set afterwards.

### Visual Regression Changes

* N/A

## QA Brief

**This requires direct database access to verify.**

* After going through the initial Site Kit setup/OAuth flow, a `googlesitekitpersistent_initial_version` user meta should be set to the current Site Kit version for the user you connected.
* After disconnecting and then reconnecting again in another Site Kit version (manually modify `GOOGLESITEKIT_VERSION`), the value stored in the `googlesitekitpersistent_initial_version` meta should still be the one from before.
* When refreshing an access token and the `googlesitekitpersistent_initial_version` user meta is not set (manually delete the value from the DB and set the `expires_in` of the current access token to a very short duration, e.g. 1), it afterwards should be set (again, to the current Site Kit version).

## Changelog entry

* Store initial Site Kit version per user for more targeted messaging in the future and introduce `googlesitekit_reauthorize_user` action.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Tested
* Unconnected user, no initial version – current version set on authentication
* Unconnected user, with initial version – current version not set/updated on authentication
* Connected user, no initial version – current version set on reauthentication
* Connected user, with initial version – current version not set/updated on reauthentication
* Initial version is still present after user disconnect when set
* Initial version is still present after reset when set
