### ISSUE TITLE
Adsense doesn't detect existing site when using camelcase URLs in WordPress settings

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#2695]
## Bug Description

Originally reported in [this support topic](https://wordpress.org/support/topic/unable-to-connect-adsense-in-site-kit/), the Adsense module doesn't detect an existing site in an Adsense account when using camelcase URLs in the WordPress settings:

<img width="750" alt="site in Adsense account" src="https://user-images.githubusercontent.com/8108643/105928053-12fd8780-5ffa-11eb-8343-c2fbf4077356.png">

<img width="674" alt="camelcase WP settings" src="https://user-images.githubusercontent.com/8108643/105928098-27da1b00-5ffa-11eb-9ce4-e8c0d9402fb0.png">

<img width="1072" alt="site not detected by Adsense module" src="https://user-images.githubusercontent.com/8108643/105928204-57892300-5ffa-11eb-930d-cea6b086823c.png">

## Steps to reproduce

1. For a site that is already listed in Adsense account, change URLs in WordPress site settings to camelcase
2. Attempt to connect the Adsense module 
3. Notice Adsense module does not detect site and prompts adding already existing site to account. 

## Additional Context

 - PHP Version: 7.4.14
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.24.0
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The site URL matching logic in the AdSense setup flow (see `determineSiteStatus`) should be modified to always compare the URLs lower-case.
    * Potentially it would be worth implementing a comprehensive solution that also includes all normalization done by `Google_URL_Normalizer`, but since that would involve bringing this server-side solution to the client, it might be too much at this point.

## Implementation Brief

* edit `assets/js/modules/adsense/util/status.js`
* modify the `determineSiteStatus` function
* convert `siteURL` `toLowerCase` before it is passed to the `hasSiteURL` check

### Test Coverage

* Add test coverage for this new behaviour in `determineSiteStatus`.

### Visual Regression Changes

* N/A

## QA Brief
This can be tested as follows using a local installation:
* In Site Kit settings disconnect Adsense if it is connected
* Using the Developer Settings plugin change the `Custom Site URL` to include uppercase characters. (e.g. `https://wWw.ElasticPress.io`)
* Connect Adsense and check that it detects the site correcly in lower case

## Changelog entry

* Fix issue with AdSense existing site detection when using camelcase URLs in WordPress settings

**Comment by tofumatt** [comment]
The ACs here mention modifying `determineSiteStatus` to convert the URL to lowercase inside its function, which I think is the better approach here. Rather than relying on the developer knowing when to modify their site's URL. So let's move the `toLowerCase` into the utility function itself instead, so developers don't need to modify their site's URL.

**Comment by tofumatt** [comment]
IB ✅, but please remember to add Test Coverage and VRT sections—even if, in the case of VRT, it's "N/A". Just make sure not to leave them blank 🙂

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

**Verified:**

- When the URL is in camel case, and Google Adsense was reconnected, the URL was recognised. 
- This was tested on a .ninja site as per QAB, and live domain, when the URL was changed in WordPress settings. 

![image](https://user-images.githubusercontent.com/73545194/114871979-709cb580-9e2c-11eb-96eb-628728b27339.png)
