### ISSUE TITLE
Show more dates on All Traffic graph

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2699]
The new All Traffic widget graph only shows the start and end date on its x-axis. It should include more dates in between, similar to how our other graphs in the plugin behave.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The new All Traffic widget graph on the left should have more dates on its x-axis, not just start and end date. Regarding how many dates to show it should match the configuration of our other graphs in the plugin (e.g. the one on the Analytics module page).
    * Despite showing more dates like in existing graphs, the labels should remain in the date format that they currently have though (e.g. Dec 29), even though that is also different from our existing graphs (where it is e.g. 12/29/20).

## Implementation Brief

* Remove the `chartOptions.hAxis.ticks` property:
  https://github.com/google/site-kit-wp/blob/8b8340008cf7b687e1c1da118278322a0fe36ef4/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserCountGraph.js#L77

### Test Coverage

* N/A

### Visual Regression Changes

* The user count graph should start showing more dates on the horizontal axis.

## QA Brief

* Set up the site kit plugin on your local;
* Activate and connect the Analytics module;
* Go to the dashboard page;
* Make sure that you see more than 2 dates on the horizontal axis of the user count graph.

## Changelog entry

* Show more than just two dates on the All Traffic widget's line chart.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  Fail ❌ 

There is some inconsistency with the displaying of the horizontal axis dates depending on the date period selected.

**For 7 days on desktop:** there are three dots (...) on the first date and then 6 dates are displayed (the 6th is quite close to the vertical axis)  

![Screenshot](https://user-images.githubusercontent.com/73545194/106763087-71b5a780-6671-11eb-9fb3-49d8acae3f0f.png)

**For 7 days on small screens (iOS and Android phones):** there are no dates on the horizontal axis. 

[Screenshot](https://user-images.githubusercontent.com/73545194/106763774-24860580-6672-11eb-891d-2d6e648a06c5.png)

**For 14 days on desktop:** this looks fine. 

**For 14 days on small screens (iOS and Android phones):**  there are no dates on the horizontal axis. 

[Screenshot](https://user-images.githubusercontent.com/73545194/106763774-24860580-6672-11eb-891d-2d6e648a06c5.png)

**For 28 days on desktop:** this looks fine. 

**For 28 days on on small screens (iOS and Android phones):**  this looks fine. 

**For 90 days on desktop:** the first date, i.e. December is not displayed at the beginning but further along the horizontal axis. Not a big issue, but looks inconsistent. 

**For 90 days on small screens (iOS and Android phones):**  the first date, i.e. December is not displayed at the beginning but further along the horizontal axis. Not a big issue, but looks inconsistent. (the 6th is quite close to the vertical axis) - 

![Screenshot](https://user-images.githubusercontent.com/73545194/106762126-7fb6f880-6670-11eb-9eb0-ea03fa5e6c48.png)

**Comment by felixarntz** [comment]
Thanks @wpdarren! The most important thing we should try to avoid here is seeing shortened dates anywhere. Regarding the amount of dates displayed, it's okay that that varies depending on screen size - although I would think even for narrow viewports there would at least be enough space to display start and end date maybe?

cc @benbowler

**Comment by benbowler** [comment]
Hey @felixarntz, I've created a new [PR 2765](https://github.com/google/site-kit-wp/pull/2765) which uses distinct breakpoints to update the number and offset of the ticks and I've tested it at the base width of each breakpoint and it no longer cuts off any of the ticks and it now shows up to four ticks on larger screens and more dense datasets.

During this work, I noticed that now that we have data in the thousands (from the traffic spike on Elasticpres recently) the yAxis labels are cut off again in some cases, if there isn't a ticket for this case there should be one made:

![Screenshot 2021-02-06 at 08.41.30.png](https://images.zenhubusercontent.com/54c7c87f7c6ccc6277a70347/b2380f2d-bd88-4f2b-a610-53e9d3fb510c)

**Comment by benbowler** [comment]
I've moved this back to Execution as it needs the `numberOfDays` value to be moved to a new selector.

**Comment by benbowler** [comment]
I've created the new selector as well as tests, full details are in the [**Technical Choices** section in the PR](https://github.com/google/site-kit-wp/pull/2765).

**Comment by wpdarren** [comment]
### QA Update: Confirm with Engineer ⚠️ 

@benbowler A few observations that I want to highlight. 

1) On Desktop for 7 days, there are only 2 dates.  There are 4 days on 14, 28 and 90 days. 

![image](https://user-images.githubusercontent.com/73545194/107616152-750bed00-6c88-11eb-8f50-7e94fe8e4da4.png)

2) On Mobile for 7, 14, 28 and 90 days, there are only 2 dates appearing.  [Screenshot](https://user-images.githubusercontent.com/73545194/107616486-227f0080-6c89-11eb-8c3f-6a6e23861bcc.png)

With the QAB stating more than 2 I'd like to check if these two observations are expected.

**Comment by benbowler** [comment]
Hey Darren,

Thanks for the QA, based on your points:

1. This is correct, because of the sparsity of the data the "middle tick" looks out of line so I removed it if the number of days was 7 across all breakpoints. This is how it looks otherwise:

<img width="565" alt="Screenshot 2021-02-11 at 14 11 09" src="https://user-images.githubusercontent.com/119352/107648504-50a61580-6c74-11eb-80a1-35d33ad070f1.png">

2. This is how I initially defined it, I've added in a third tick on mobile in the new PR for all except where number of days is 7.

3. Good spot, I've increased the outer date offset on this data size and screen size to 7 days now and it appears to show correctly in my testing right down to the old iPhone SE size: .

Into CR with @aaemnnosttv now.

**Comment by aaemnnosttv** [comment]
@benbowler looks good to me but it would be great if @wpdarren could confirm as well.

On a side note, it looks like there are some other issues unrelated to these changes at this viewport size such as the vertical axis labels being truncated to `...` and the date range select covering the main logo.

Also – @benbowler in your screenshot there it looks like you're showing the widget-based dashboard (hence the extra indentation) rather than what would be seen in a production build. E.g. I see this:
![image](https://user-images.githubusercontent.com/1621608/107656044-6d4e4780-6c8c-11eb-92cf-694efa326455.png)

**Comment by aaemnnosttv** [comment]
@felixarntz one quick follow-up PR here for you to review: https://github.com/google/site-kit-wp/pull/2791

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- I can see more than 2 dates on the horizontal axis of the user count graph for desktop and mobile. 
- The issues reported above are fixed. 

![image](https://user-images.githubusercontent.com/73545194/107666858-f172f000-6cc9-11eb-9e95-bcea8612703a.png)

@aaemnnosttv just want to make sure [this comment](https://github.com/google/site-kit-wp/issues/2699#issuecomment-774431940) doesn't get missed from @benbowler 

`During this work, I noticed that now that we have data in the thousands (from the traffic spike on Elasticpres recently) the yAxis labels are cut off again in some cases, if there isn't a ticket for this case there should be one made:`

Would you like me to create a ticket for this?

**Comment by aaemnnosttv** [comment]
> `During this work, I noticed that now that we have data in the thousands (from the traffic spike on Elasticpres recently) the yAxis labels are cut off again in some cases, if there isn't a ticket for this case there should be one made:`
> Would you like me to create a ticket for this? 

@wpdarren It sounds like we may have (or had) an issue like this, so let's make sure it's not a duplicate first but otherwise please do! 👍
