### ISSUE TITLE
Basic Module Tests | Analytics - PageSpeed Insights: API key entry when PSI active

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#270]
Set up Basic Module Tests | Analytics - PageSpeed Insights: API key entry when PSI active

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* n/a

## Implementation Brief

* n/a

## Changelog entry

* N/A

**Comment by swissspidy** [comment]
Code review: ✅
