### ISSUE TITLE
Fix All Traffic line chart alignment

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2708]
In the new All Traffic widget, the line chart (`UserCountGraph`) currently shows weirdly "indented", compared to the big number above (`TotalUserCount`). This is different from the original design where the graph on its left side aligns with the outer padding of the entire widget.

When I looked at the DOM, it seems the extra spacing is added by the Google charts library itself. Let's see if we can either get rid of it (preferred) or fix it via CSS in some other way (negative margin?).

Furthermore, the line chart's bottom end should be aligned with the bottom end of the `UserDimensionsPieChart`, i.e. the legends for both should pretty much appear on the same row.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The left end of the line chart in the new All Traffic widget should align with the left end of the big number and text above. It should no longer be indented further than the regular widget padding.
* The bottom end of the line chart in the new All Traffic widget should align with the bottom end of the pie chart, i.e. the legends should appear as if they were on the same line.

## Implementation Brief

* To fix the positioning of the chart horizontally, change the `UserCountGraph` `chartArea` param to:
```js
chartArea: {
	height: '90%',
	left: '-5%',
	top: '5%',
	width: '90%',
}
```
* To line them up vertically add the following CSS:
```scss
.googlesitekit-widget--analyticsAllTraffic__user-count-chart {

	@media (min-width: $bp-desktop) {
		margin-top: 1.4vw;
	}

	@media (min-width: $bp-xlarge) {
		margin-top: 0;
	}
}
```
* To maintain the dates appearing in the wider widget, we (sadly) cannot show the farthest-out dates; if we do, Google Charts will hide them. So let's move the dates we show on the horizontal axis below the chart to be one day ahead of the `startDate` and one day before the `endDate`.
* Merge #2712.

### Test Coverage

* No tests for this issue.

### Visual Regression Changes

* No VRT changes should result from these changes.

## QA Brief

* The charts should appear in-line with each other and the line chart of total users should not be "pushed in" to the center of the left side of the All Traffic Widget, eg:

<img width="1166" alt="Screenshot 2021-01-28 at 21 42 50" src="https://user-images.githubusercontent.com/90871/106202461-e55b3e80-61b1-11eb-9e57-0d0608b8cf6a.png">

## Changelog entry

* Ensure line chart in All Traffic is correctly left-aligned with the total user count.

**Comment by felixarntz** [comment]
@tofumatt High-level IB almost good to go, however I don't think it fully covers this point of the ACs yet though:
> The bottom end of the line chart in the new All Traffic widget should align with the bottom end of the pie chart, i.e. the legends should appear as if they were on the same line.

Your screenshot still has the legend of the pie chart higher than the dates of the line chart. Is it possible to align those to be on the same level?

(I'll also start reviewing the PR, since it already covers the other part.)

**Comment by tofumatt** [comment]
> Your screenshot still has the legend of the pie chart higher than the dates of the line chart. Is it possible to align those to be on the same level?

You mean these, right:

<img width="820" alt="Screenshot 2021-01-28 at 19 03 26" src="https://user-images.githubusercontent.com/90871/106186020-93a7b980-619b-11eb-94bc-8ef06db48a43.png">

If so, indeed it is, and I'm just realising that screenshot might not even be up-to-date as I tweaked the alignment after. But it wasn't _perfect_, and they can certainly be made to line up. I'll do that this evening, in about an hour and ping you when it's ready. Just requires slight tweaks to the CSS.

**Comment by felixarntz** [comment]
IB ✅  - there's some feedback to address in the PR though.

**Comment by felixarntz** [comment]
@aaemnnosttv Can you give the PR a quick test?

**Comment by felixarntz** [comment]
**QA** ⚠️ 

y-axis values of the line chart in the All Traffic widget are no longer displaying.

**Comment by felixarntz** [comment]
QA ⚠️ 

The x-axis labels and the legend still do not align. This was actually missed to catch during review of #2712 where the fix to another visual regression introduced by this also broke the alignment once again.

This is not a highly critical issue for the release, so I've opened #2738 to actually address that.

cc @tofumatt @aaemnnosttv

**Comment by felixarntz** [comment]
I'll move this to Approval.
