### ISSUE TITLE
Module Setup Flow | AdSense: Different test user accounts

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#271]
Set up AdSense activation with each of the (10) test user accounts (one for each status):

| AdSense Status            | State         |
|---                        | ---           |
| `noAdSenseAccount`        | No account.    |
| `disapprovedAccount`      | There is an AdSense account, it is disapproved, suspended, terminated etc. |
| `disapprovedAccount`      | There is an AdSense account, but the AFC account is disapproved. |
| `disapprovedAccount`      | There is an AdSense account, but an AFC was never set up (i.e. created through AdMob). |
| `accountGraylisted`       | New AdSense account, not disapproved. |
| `accountPendingReview`    | New AdSense account, not disapproved, Phone verification has not been done *OR* billing information has not been done. |
| `accountPendingReview`    | New account not disapproved/terminated. No url has been approved yet. |
| `accountPendingReview`    | Account is not disapproved, but the current url is disapproved (other url(s) have been approved). no data |
| `accountPendingReview`    | Account not disapproved/terminated. The current url has not been added to the account (but other urls have been). |
| `accountActive`           | Account not disapproved/terminated. The current url has been approved. |

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* n/a

## Implementation Brief

* n/a

## Changelog entry

* AdSense activation with each of the test user accounts

**Comment by felixarntz** [comment]
@bjackson27 @aaemnnosttv What are the "test user accounts"?

**Comment by aaemnnosttv** [comment]
@felixarntz I've updated the description to include the cases from our document.

**Comment by felixarntz** [comment]
Closing in favor of #940.
