### ISSUE TITLE
"All Users" in All Traffic widget breadcrumb should link to overall view

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2715]
When the left side of the All Traffic widget shows data for a filtered subset of all users, the "All Users" segment of the "All Users > ..." breadcrumb should look like a link. When clicked, it should result in the overall graph being displayed again and the respective pie slice being unselected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "All Users" segment of the "All Users > ..." breadcrumb should be a link that, when clicked, goes back to the regular "All Users" view, displaying the overall graph.
* When that happens, the respective pie slice should also be no longer selected.

## Implementation Brief
* Using `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/TotalUserCount.js`
	* Add a link around the `All Users` text if there is a `dimensionValue`.
	* Upon clicking the link, it should clear the `dimensionValue` and `dimensionColor`.
		```js
		const { setValues } = useDispatch( CORE_FORMS );
		const showAllUsers = ( e ) => {
			e.preventDefault();

			setValues( FORM_ALL_TRAFFIC_WIDGET, { dimensionValue: '', dimensionColor: '' } );
		};
		```
### Test Coverage
* No changes expected.

### Visual Regression Changes
* No changes expected.

## QA Brief

* Set up your Site Kit and connect the Analytics module.
* Visit the dashboard.
* Click on a segment in the pie chart of the "Your Traffic at a Glance" widget.
* The "All Users" text will become a link that resets the select pie segment.

## Changelog entry

* When viewing a specific segment of users in the All Traffic widget, make the "All Users" breadcrumb a link to go back to the overall users view.

**Comment by felixarntz** [comment]
IB ✅

**Comment by benbowler** [comment]
Added an IB.

**Comment by wpdarren** [comment]
### QA Update:

**Verified:**

- When you click on a segment in the pie chart on the "Your Traffic at a Glance" widget, the "All Users" text becomes a link that resets the select pie segment. 

- Tested this on all 3 dimensions and with different date periods, i.e. 7, 14,28 and 90 days. 
- Tested this on mobile devices with different screen sizes. 

![image](https://user-images.githubusercontent.com/73545194/107221882-2f181480-6a4f-11eb-870d-9a9b09e77f3e.png)
