### ISSUE TITLE
"Others" slice in All Traffic widget should not be selectable

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2716]
The "Others" slice in the new All Traffic widget should not be selectable, since it doesn't alter the UI on the left at all. Indicating it as being selectable results in confusing UX.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any "Others" slice displayed in the All Traffic widget pie chart should not be selectable, and it visually shouldn't be indicated as selectable.
* Its tooltip should still show when hovering.

## Implementation Brief
* Using `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js`
	* Clear the chart's selection if the 'Others' slice is selected by calling:
		```js
		chart.setSelection( [] );
		```
	* Add a new state variable called `selectable`. This will act as a flag whether we want to have the chart slices to be selectable by adding `cursor: pointer` to the graph.
		```js
		const [ selectable, setSelectable ] = useState( false );
		```
	* Listen to the `onmouseover` event of the chart and set the chart to be not selectable if the label of the slice hovered is `Others`
		```js
		chartData.onMouseOver = global.google.visualization.events.addListener( chart, 'onmouseover', ( e ) => {
			const { row } = e;

			if ( ! row ) {
				setSelectable( false );
			}
			const { dataTable } = GoogleChart.charts.get( chartID ) || {};
			setSelectable( dataTable.getValue( row, 0 ) !== __( 'Others', 'google-site-kit' ) );
		} );
		```
	* Listen to the `onmouseout` event as well, to make the chart not selectable.
		```js
		chartData.onMouseOut = global.google.visualization.events.addListener( chart, 'onmouseout', () => {
			setSelectable( false );
		} );
		```
	* Conditionally add the `googlesitekit-widget--analyticsAllTraffic__selectable` class name to the container containing the chart if `selectable` is `true`.
		```js
			<div className={ classnames(
				'googlesitekit-widget--analyticsAllTraffic__dimensions-chart',
				{
					'googlesitekit-widget--analyticsAllTraffic__dimensions--loading': ! loaded,
					'googlesitekit-widget--analyticsAllTraffic__selectable': selectable,
				}
			) }>
		```
	* Update the code for the `select` event so that `setValues` is not called when `isOthers` is `true`.
* Using `assets/js/components/GoogleChart.js`
	* Remove the mouse over and mouse out listeners from the chart, similar to how the `onSelect` and `onReady` listeners are removed.
* Using `assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss`
	* Add the newly added class name: `googlesitekit-widget--analyticsAllTraffic__selectable`
	* Move the [existing CSS code](https://github.com/google/site-kit-wp/blob/9da5402e860b9333022b2082dfd74cbec0709f22/assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss#L109-L115) which adds `cursor: pointer` to the pie to be within `googlesitekit-widget--analyticsAllTraffic__selectable`.

### Test Coverage
* No changes expected.

### Visual Regression Changes
* No changes expected.

## QA Brief

* The 'Others' slice of the pie chart in the All Traffic Widget should not show `cursor: pointer` on hover (i.e. the arrow should not change to a hand to indicate that you can select it)
* Clicking on "Others" should result in there not being any active selected pie slice, i.e. the "All Users" graph should be displayed on the left. (This is a temporary state; eventually this clicking on "Others" should not have any effect, i.e. maintain any previous selection, but for now the current improvement from this issue should be good to go.)

## Changelog entry

* Ensure that any "Others" slice in the All Traffic widget is not indicated as selectable and cannot be active.

**Comment by felixarntz** [comment]
@asvinb Is there no way to define this per piece of data when providing it to the chart? If not, maybe this is an okay approach. @eugene-manuilov Would be good if you could review the IB here as well.

**Comment by eugene-manuilov** [comment]
@asvinb @felixarntz I am not sure that using `cursor` styles will prevent the Others slice to be selectable (at least because you can also select a slice by clicking on a legend item). I think what we really need to do is to immediately clear selection in the handler function for the `select` event when a user selects the Others slice.

**Comment by asvinb** [comment]
@eugene-manuilov I've updated the IB to reflect that. Basically we call  ```chart.setSelection( [] );``` if the "Others" slice is selected. We need to keep the CSS updates so that the cursor is not set to pointer when hovering the "Others" slice.

**Comment by eugene-manuilov** [comment]
@asvinb IB almost looks good. The last piece to add is to remove event listeners when the google chart component is unmounted. Check the `GoogleChart` component, we should do it in the same way how we remove event listeners for `ready` and `select` events.

**Comment by asvinb** [comment]
IB updated @eugene-manuilov

**Comment by eugene-manuilov** [comment]
@asvinb I don't see where we set `onMouseOver` and `onMouseOut` properties in the IB. Plus, it shouldn't replace existing `onSelect` and `onReady` listeners like it is shown in your snippet.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: Engineer to confirm ⚠️ 

@johnPhillips a quick observation that I'd like clarified. 

As you can see on the screenshot below, when you hover over the `others` slice, while the pointer cursor does not appear, the highlight around the slice appears and stays until you hover away.  Is this expected? I am assuming it is but would like to check. 

**Verified:**

The `Others` slice of the pie chart in the All Traffic Widget does not show cursor: pointer on hover 
The `Others` slice displays the "All Users" graph on the left.  

![image](https://user-images.githubusercontent.com/73545194/107517624-f1e78a00-6be8-11eb-8c6a-b700365cf50f.png)

**Comment by johnPhillips** [comment]
Hi @wpdarren, thanks for this. There has been a bit of to and fro with this issue because we were unable to implement certain requirements. Perhaps double check with @felixarntz?

**Comment by wpdarren** [comment]
@felixarntz would be good to get your opinion on this.  IMO, it makes sense to have the highlight around the slice but wasn't sure from the QAB if this is expected or not.

**Comment by felixarntz** [comment]
@wpdarren This is acceptable at this stage, although you're correct that preferably it shouldn't be the case. We'll need to put more work into our general usage of the charts (see #2714), where these things should be tackled.

**Comment by wpdarren** [comment]
### QA Update: Passed

**Verified:**

- The `Others` slice of the pie chart in the All Traffic Widget does not show cursor: pointer on hover 
- The `Others` slice displays the "All Users" graph on the left.  

Also tested this with different date periods, i.e. 7, 14, 28 and 90 days + checked on Browserstack for other browsers. 

![image](https://user-images.githubusercontent.com/73545194/107517624-f1e78a00-6be8-11eb-8c6a-b700365cf50f.png)
