### ISSUE TITLE
Legacy dashboard layout shifts when enabling Analytics via CTA

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2719]
## Bug Description

Currently, the main dashboard layout slightly varies in its structure and widget positions depending on whether or not the Analytics module is active. This results in an unexpected visual glitch when activating Analytics via the CTA on the dashboard.

![Kapture 2021-01-29 at 12 09 11](https://user-images.githubusercontent.com/1621608/106261923-ea100900-622a-11eb-9b61-09dd70412df7.gif)

This is due to conditional logic in the layout that is based on whether or not Analytics is active, when in fact it should be based on the connected state of the module (i.e. whether or not its setup is completed).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no layout changes on the main dashboard when activating the Analytics module

## Implementation Brief

* Update the `PostSearcher` dashboard widget component's conditional logic for grid classes to be based on the Analytics module's connected state rather than active state using the `isModuleConnected` selector
* Merge https://github.com/google/site-kit-wp/pull/2720

### Test Coverage

* N/A

### Visual Regression Changes

* No changes expected

## QA Brief

* Analytics should be able to be activated via the dashboard CTA without causing a shift in the layout before the page navigates

## Changelog entry

* Avoid layout shift when enabling the Analytics module via the Site Kit dashboard CTA.

**Comment by felixarntz** [comment]
Good catch! IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified the initial issue on the latest release when you click on the `Setup Analytics` CTR, there is an unexpected visual glitch.  When on `develop` branch the glitch does not appear. I am also able to setup Analytics without any issues.
