### ISSUE TITLE
Search Console dashboard overview chart display problems when more than 2 metrics selected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2721]
## Bug Description

Currently the dashboard overview component on the Search Console dashboard has a few problems when multiple metrics are selected at the same time.

1. Axis labels on the right side of the overview chart become stacked as more than 2 metrics are selected.  
	* **2 metrics**  
	![alive-snare jurassic ninja_wp-admin_admin php_page=googlesitekit-module-search-console](https://user-images.githubusercontent.com/1621608/106267413-4591c500-6232-11eb-939a-a986c4886f75.png)
	* **3 metrics**  
	![alive-snare jurassic ninja_wp-admin_admin php_page=googlesitekit-module-search-console (1)](https://user-images.githubusercontent.com/1621608/106267419-475b8880-6232-11eb-9cd6-f892aab26575.png)
	* **All 4 metrics**  
	![alive-snare jurassic ninja_wp-admin_admin php_page=googlesitekit-module-search-console (2)](https://user-images.githubusercontent.com/1621608/106267426-488cb580-6232-11eb-84ff-da08a87b2d36.png)
1. The width of the chart is wider when 3 or 4 metrics are selected (see above)

Similar components on the Analytics and AdSense dashboards do not have these problems because they only allow a single metric to be selected at a time.

## Steps to reproduce

1. Go to the Search Console dashboard when connected to a site with data in SC
2. Select additional metrics in the overview chart
3. See axis labels overlap as above

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When more than two metrics are enabled in the Search Console graph on the Search Console module page, their labels should not be displayed for the y-axis, since they would overlap. There is already a legend above, which is sufficient.

## Implementation Brief

* Edit the `setOptions` method of the `SearchConsoleDashboardWidgetSiteStats` component:
  * Remove the following lines: https://github.com/google/site-kit-wp/blob/fa3df25c8c6cb11ab600262174c7fbfbcbaf7692/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetSiteStats.js#L88-L96 https://github.com/google/site-kit-wp/blob/fa3df25c8c6cb11ab600262174c7fbfbcbaf7692/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetSiteStats.js#L105
  * Add the following settings to the `else` clause when the `selectedStats` length is less than 3:
    ```javascript
    if ( 3 <= selectedStats.length ) {
        ...
    } else {
        options.vAxis.textStyle = {
            color: '#616161',
            fontSize: 12,
        };
        options.vAxis.titleTextStyle = {
            color: '#616161',
            fontSize: 12,
            italic: false,
        };
    }
    ```

### Test Coverage

* N/A

### Visual Regression Changes

* Axis labels should be hidden when 3 or more metrics are selected.

## QA Brief

* Set the width of your browser viewport to at least `1400px` wide
* Visit the "Search Console" page in Site Kit for a site with data
* Highlight three or more metrics: the legends on the left/right side of the screen should disappear.
* Deselect metrics until 2 or fewer metrics are selected: the legends should appear.

## Changelog entry

* Fix bug with Search Console module page graph where overlapping legends would be displayed when selecting more than 2 metrics.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv this seems like not an issue anymore. See here:

https://github.com/google/site-kit-wp/blob/fa3df25c8c6cb11ab600262174c7fbfbcbaf7692/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetSiteStats.js#L104-L109

We already hide it when we have 3+ stats selected. Or I miss something?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov it's still there. You can see what I mean here

![Kapture 2021-02-10 at 18 39 53](https://user-images.githubusercontent.com/1621608/107541122-775e4080-6bcf-11eb-9f95-9bfad3983cac.gif)

Note when selecting the 3rd stat it changes in size (probably a result the width change there) so that appears to be intentional. The part which is not right is the text on the far right side which overlaps when 3 or 4 are selected.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv yeah, I understand the issue in the description, but I can't reproduce it on my end. I see that we have the appropriate code in the develop branch that deals with your issue.

**Comment by tofumatt** [comment]
Ah, the problem is that this is only apparent at very large viewports. You need a browser viewport width of about 1680px before they show when three are clicked:

<img width="1390" alt="Screenshot 2021-02-11 at 20 32 46" src="https://user-images.githubusercontent.com/90871/107695299-50277200-6ca8-11eb-9169-32c2ca1bb01a.png">

IB ✅

**Comment by felixarntz** [comment]
@tofumatt Can you add a QA Brief here please?

**Comment by tofumatt** [comment]
@felixarntz Sure thing! I thought I added one but I might've forgot to hit save 🤦🏻

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

With browser viewport to at least 1400px wide: 

- When I highlight three or more metrics: the legends on the left/right side of the screen disappear.

![image](https://user-images.githubusercontent.com/73545194/108358854-2e8b3500-722a-11eb-9e81-2cb0a57e4a8b.png)

- When I highlight two or fewer metrics: the legends appear. 

![image](https://user-images.githubusercontent.com/73545194/108358875-3519ac80-722a-11eb-9b7d-d16d0e38a5e7.png)
