### ISSUE TITLE
WP core checkbox styles introduce odd visual effect

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2722]
## Bug Description

Recently I've noticed an odd element appear very briefly when starting the AdSense setup flow. It appears to be related to WP core checkbox styles that add an image using a data-uri on the `::before` pseudo-element for checked checkboxes.

![image](https://user-images.githubusercontent.com/1621608/106273631-a83b8e80-623b-11eb-9440-7abc15c0ff3a.png)
![image](https://user-images.githubusercontent.com/1621608/106273547-89d59300-623b-11eb-8daf-fe5e977ea2e8.png)

For some reason this is visible on initial load (under some conditions - perhaps when cache is disabled via devtools?) but disappears quickly.

This like affects all switch components which we use instead of checkboxes, but I've only seen it in AdSense setup.

## Steps to reproduce

1. Activate AdSense to initiate setup flow
2. As soon as the component loads, look for the checkbox just to the left of the switch for the AdSense snippet (disappears quickly)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The visual bug where a checkmark shows beside the toggles in the AdSense setup (see screenshot above) flow should be fixed.

## Implementation Brief
* Using `assets/sass/vendor/_mdc-switch.scss`, hide the '::before' pseudo selector of the `mdc-switch__native-control` class name

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

1. Activate AdSense to initiate setup flow.
2. As soon as the component loads, look for the checkbox just to the left of the switch for the AdSense snippet - it should now not show the hidden checkbox.

Eng: This can also be tested on a disabled checkbox, mark a checkbox as disabled using the inspector at it will no longer show the extra tick. 

Before:

<img width="123" alt="Screenshot 2021-02-16 at 15 04 36" src="https://user-images.githubusercontent.com/119352/108080952-529f1880-7068-11eb-90d2-2a1fc83cc602.png">

After:

<img width="84" alt="Screenshot 2021-02-16 at 15 03 13" src="https://user-images.githubusercontent.com/119352/108080937-4e72fb00-7068-11eb-9ccf-9d6bb2fe9159.png">

## Changelog entry

* Fix visual bug where in the AdSense flow the toggle element could be overlapped by a checkmark icon.

**Comment by tofumatt** [comment]
IB ✅

**Comment by benbowler** [comment]
@aaemnnosttv  I actually saw this and fixed it in #2602. I'll create a fresh PR for this issue.

**Comment by benbowler** [comment]
Moved into CR and QA brief added.

**Comment by cole10up** [comment]
### QA ❌

Ran a series of tests around setup of Adsense from the settings page and dashboard. 

Noticed dashboard setup flow is fixed:
![Sign in - Google Accounts](https://user-images.githubusercontent.com/57115907/108807938-59db9000-755a-11eb-8517-8f44cea1950d.gif)

Settings page setup isn't fixed:
![Site Kit by Google Settings ‹ SupremeQA — WordPress](https://user-images.githubusercontent.com/57115907/108807959-65c75200-755a-11eb-8d8e-100b70a6d6a6.gif)

Paused from my gif above:
![image](https://user-images.githubusercontent.com/57115907/108807994-75df3180-755a-11eb-9c56-ccb9e40d875e.png)

Sending back to Execution @benbowler

**Comment by aaemnnosttv** [comment]
@cole10up I think this may be a CSS cache issue for you. I've double checked this on my end and it looks correct from what I can see. I took a few screenshots to compare between branches, although these switches were manually disabled to produce the effect. If it is still possible to see without doing this then we'll need to take a closer look. I did not observe a flicker of the image on load though.

| `master` | `develop` |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1621608/108818130-9db5b000-75c1-11eb-992b-6cfc4f20e307.png) | ![image](https://user-images.githubusercontent.com/1621608/108818142-a27a6400-75c1-11eb-9427-60c57112bdec.png) |
| ![image](https://user-images.githubusercontent.com/1621608/108818157-a908db80-75c1-11eb-9842-abd0361c5ca8.png) | ![image](https://user-images.githubusercontent.com/1621608/108818160-aa3a0880-75c1-11eb-9193-629ac9197dff.png) |

Assigning to @wpdarren to give this another pass. Please make sure your browser cache is disabled ensure that old styles are not influencing the result.
