### ISSUE TITLE
Allow PHP8

### ISSUE THREAD

**Issue by TorbenLundsgaard** [google/site-kit-wp#2724]
## Feature Description

Start testing all pull requests on PHP8

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new GitHub action that replicates the "PHP (PHP 7.4, WordPress Latest)" one, except that it uses PHP 8.0.
* Any failures, errors or warnings that this job results in should be addressed.
    * For the IB, it's probably best to set up PHP 8 locally and run the tests to see where failures, errors and warnings come up.

## Implementation Brief

* Create a new PHP test Github Action: '.github/workflows/php-tests-wp-latest-php-8-0.yml' from the existing: `.github/workflows/php-tests-wp-latest-php-7-4.yml` actions, updating the PHP version to `8.0`.
* Update the 7 tests that fail because of [`Method ReflectionParameter::isArray() is deprecated`](https://php.watch/versions/8.0/deprecated-reflectionparameter-methods#isArray)
   1. `Google\Site_Kit\Tests\Core\Authentication\AuthenticationTest::test_require_user_input` - `tests/phpunit/integration/Core/Authentication/AuthenticationTest.php`
   1. `Google\Site_Kit\Tests\Core\Authentication\AuthenticationTest::test_require_user_input__without_feature` - `tests/phpunit/integration/Core/Authentication/AuthenticationTest.php`
   1. `Google\Site_Kit\Tests\Core\Authentication\AuthenticationTest::test_disconnect` - `tests/phpunit/integration/Core/Authentication/AuthenticationTest.php`
   1. `Google\Site_Kit\Tests\Core\Authentication\Clients\OAuth_ClientTest::test_authorize_user` - `tests/phpunit/integration/Core/Authentication/Clients/OAuth_ClientTest.php`
   1. `Google\Site_Kit\Tests\Core\Authentication\Clients\OAuth_ClientTest::test_refresh_profile_data` - `tests/phpunit/integration/Core/Authentication/Clients/OAuth_ClientTest.php`
   1. `Google\Site_Kit\Tests\Modules\Analytics\Advanced_Tracking\Script_InjectorTest::test_inject_event_script` - `tests/phpunit/integration/Modules/Analytics/Advanced_Tracking/Script_InjectorTest.php`
   1. `Google\Site_Kit\Tests\Modules\AnalyticsTest::test_handle_provisioning_callback` - `tests/phpunit/integration/Modules/AnalyticsTest.php`.

### Test Coverage

* Test updates are mentioned in the IB, no additional tests or changes to tests are required.

### Visual Regression Changes

* No visual regression changes are required.

## QA Brief

* Review "PHP Tests" check run for "PHP 8.0" – ensure runs as expected
* Review other "PHP Tests" checks run normally – changes were made that affect all PHP Tests, including (and specifically) the multisite variant

## Changelog entry

* Add support for PHP 8 and ensure its maintenance via CI.

**Comment by benbowler** [comment]
I set up the GitHub action and ran in the attached draft PR, I also used `PHPCompatibility/PHPCompatibilityWP` to check for compatibility issues with `8.0` and didn't find any.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Giving this a bit of a larger estimate since it isn't clear exactly what's needed to fix the `Method ReflectionParameter::isArray() is deprecated` problem. We've seen this when PHP 8 was first introduced and it's raised by method calls within PHPUnit when creating mocks, so there is nothing in our tests to update.

WordPress core recently back-ported some fixes for this into its PHPUnit library but I was still seeing these errors when I last tried it.

**Comment by ivankruchkoff** [comment]
QA ✅

Reviewed the following four github action checks:
https://github.com/google/site-kit-wp/runs/2060528495
https://github.com/google/site-kit-wp/runs/2060528543
https://github.com/google/site-kit-wp/pull/2867/checks?check_run_id=2033453353
https://github.com/google/site-kit-wp/pull/2867/checks?check_run_id=2033453301
