### ISSUE TITLE
Search Console > Average CTR and Position Data Rounding Issue

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#2725]
## Bug Description

While testing the latest 1.25.0 zip file,  I noticed a rounding issue with the `Average CTR` and `Position` data within the Search Console module.  This is not an issue on 1.24.0 as you can see on the screenshot below. 

On 1.25.0 latest zip

![image](https://user-images.githubusercontent.com/73545194/106293685-40139980-6289-11eb-9f1b-f0cf74039dc3.png)

![image](https://user-images.githubusercontent.com/73545194/106299117-c3d08480-628f-11eb-8836-f63ca296fce8.png)

On 1.24.0 latest release 

![image](https://user-images.githubusercontent.com/73545194/106291992-41dc5d80-6287-11eb-96ba-e6100c4149b7.png)

## Steps to reproduce

1. Go to 'Search console module'
2. Click on 'Average CTR and/or Position' tabs
3. Scroll down to 'the graph' and hover over the line chart. 
4. See rounding of the CTR and Position data. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Numbers displayed in the Search Console graph on the Search Console module page should be formatted inside Site Kit (e.g. in `SearchConsoleDashboardWidgetSiteStats`), instead of passing numbers through to the charts library as is.

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/2726

### Test Coverage

* No change

### Visual Regression Changes

* N/A

## QA Brief

* Go to Search Console dashboard on site with data
* Toggle on CTR and Position data points on the overview chart
* Inspect values for CTR and Position in tooltips when hovering lines (as shown above)
* Ensure floating point numbers are a maximum of 3 fractional digits

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz – After taking a closer look at this, I found it was a result of changing the version of the Google Charts library that we load. Reverting d3fc387cf63e28669b140f88dafc466db5be052f restores the previous behavior.

We could (and probably should) update `SearchConsoleDashboardWidgetSiteStats` to format the numbers itself rather than chart defaults.

**Comment by felixarntz** [comment]
@aaemnnosttv Agreed. How much work do you think formatting these values in our component would involve? Technically this is a regression, so preferably should be fixed for the release.

**Comment by aaemnnosttv** [comment]
> How much work do you think formatting these values in our component would involve?

@felixarntz – probably not that much; I'll take a look now.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- The values for CTR and Position in tooltips when hovering lines are a maximum of 3 fractional digits.  
- All of the other values in Search console chart appear as expected. 
- Checked date periods, 7, 14, 28 and 90 days. 

![image](https://user-images.githubusercontent.com/73545194/106463069-e18d2c00-64d1-11eb-9a4f-24734fc6f10e.png)

![image](https://user-images.githubusercontent.com/73545194/106463089-e81ba380-64d1-11eb-8ab0-77743783f3f5.png)
