### ISSUE TITLE
AdSense Dashboard Summary displays data inconsistently with others

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2734]
## Bug Description

Currently, the AdSense summary widget on the Site Kit dashboard displays 3 metrics with a Sparkline for each to show the performance over time. This widget displays the information a bit differently than elsewhere which is a bit confusing (since it isn't mentioned anywhere in the interface).

Specifically, the Sparkline for the metric is only for data starting from the beginning of the month, regardless of the current date range. This also has the potential to result in a particularly odd state on the first day of the month where the sparkline appears as a single dot (or blank) since there is not enough points to draw a line.

![image](https://user-images.githubusercontent.com/1621608/106440685-c98dbc00-6481-11eb-9a14-69368039c874.png)
Compared to how the widget would look on the previous day, it looks broken (even though it's working as designed)
![image](https://user-images.githubusercontent.com/1621608/106441587-e7a7ec00-6482-11eb-8b38-e38faa21226c.png)

Other odd diversions from other components is how the change % is displayed for total earnings, which only shows the change over the last day. Again, this is not labelled so the user is not able to understand that this is what it means; one would assume it would reflect the change from the previous period like other components do.

This affects both new and old versions of the same widget.

## Steps to reproduce

1. Use development build (to allow customizing reference date with Widget API version)
1. Activate AdSense (can use Tester to force report data)
1. Navigate to the Site Kit dashboard and run this in the console:  
```
googlesitekit.data.dispatch( 'core/user' ).setReferenceDate( '2021-02-01' )
```
1. See the widget without a sparkline (or single dot)

## Additional Context

This affects versions going back several releases, so it's not a regression or error in recent refactorings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New and old AdSense dashboard summary widgets (i.e. refactored and legacy version) should display their sparklines for the current date range period instead of only from the start of the current month onwards.
    - The request for the start of the month until the current day of the month should be removed and no longer used.
* Since it's now no longer used, support for the special `this-month` date range should be removed from the `modules/adsense` JS store.
* The temporary JS hack around `prev-date-range-placeholder` should be removed since it has been unused for a while.
* Support for the following unused AdSense special date ranges should be removed from the `AdSense` PHP class:
    * `yesterday`
    * `same-day-last-week`
    * `this-month`
    * `this-month-last-year`
    * `prev-7-days`
    * `prev-14-days`
    * `prev-28-days`
    * `prev-90-days`

## Implementation Brief

* Update `DashboardSummaryWidget` and `LegacyAdSenseDashboardMainSummary` components to use the selected date range reports instead of reports for the current month.
* Remove `this-month` from the list of valid date ranges in the `assets/js/modules/adsense/datastore/report.js` file.
* Remove the following statement:
  https://github.com/google/site-kit-wp/blob/fa3df25c8c6cb11ab600262174c7fbfbcbaf7692/assets/js/components/data/utils/request-with-date-range.js#L34-L42
* Edit the `includes/Modules/AdSense.php` file and remove support for the date ranges defined in the AC.

### Test Coverage

* Update existing tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* The summary widgets should start to display sparklines built for the currently selected date range.

## QA Brief

* A great way to QA this fix would be to try to replicate the "first of month" bug mentioned where the sparklines would be empty for an AdSense page on the first of the month.
* But since that isn't always possible, the QA for this fix is to ensure all AdSense data (for example spark line charts) use the currently set date range in the Date Range selector on the top right of the page instead of using from the start of the current month as their range.

## Changelog entry

* Fix AdSense dashboard summary widget to include data for the current date range in its sparklines rather than only data from the 1st of the current month.

**Comment by felixarntz** [comment]
@aaemnnosttv I reduced the user-facing changes here a little bit, to only focus on fixing the weird sparkline behavior. The `today` date range is still relevant since that value is used here as change, instead of a percentage. While I agree that's also worth revisiting, it's a bigger change that we should discuss, where the sparkline part is more trivial. I've defined the ACs around that and included some legacy date range cleanup.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
### QA ⚠️

Ran a series of regression tests with Adsense Dashboard Summary focusing on date range adjustment.

Mock data is incrementing properly. Unable to reproduce this issue during my tests.

7 Days
![image](https://user-images.githubusercontent.com/57115907/109260996-04022480-77b4-11eb-87a8-0c4c11e3c284.png)
 
 14 Days
![image](https://user-images.githubusercontent.com/57115907/109261169-4297df00-77b4-11eb-96ed-707b1c9a0b18.png)

28 Days
![image](https://user-images.githubusercontent.com/57115907/109261197-4fb4ce00-77b4-11eb-82c2-717bf0702779.png)

90 Days
![image](https://user-images.githubusercontent.com/57115907/109261211-56dbdc00-77b4-11eb-81ca-a4096c344c4b.png)

I noticed the ^$22.34 consistent across each date range. Clicking into Adsense module page doesn't show the ^$22.34
![image](https://user-images.githubusercontent.com/57115907/109261412-9b677780-77b4-11eb-9029-402df9ab4ddf.png)

Is this something we should explore further @aaemnnosttv?

**Comment by aaemnnosttv** [comment]
> I noticed the ^$22.34 consistent across each date range. Clicking into Adsense module page doesn't show the ^$22.34

@cole10up this is a bit odd, but the changes made here are specific to the spark line graph. The change value you're seeing there is only showing the current day change so that is expected to be the same across all ranges. I think this could be labelled better for clarity, but it seems to be working as expected.

Put another way, the spark lines should be drawn based on the current date range, whereas before it was always drawn based on first-of-month to the current-day-of-month.

Assigning to @wpdarren for another pass.

**Comment by wpdarren** [comment]
### QA Update:

**Verified:**

The spark lines are drawn based on the current date range, the values continuously change on each range. 

**7 days**
![image](https://user-images.githubusercontent.com/73545194/109308986-aafec300-787d-11eb-98fb-0d7754586903.png)

**14 days**
![image](https://user-images.githubusercontent.com/73545194/109309016-b4882b00-787d-11eb-93d4-a00a76234277.png)

**28 days**
![image](https://user-images.githubusercontent.com/73545194/109309047-bd78fc80-787d-11eb-8690-b8f8a42c8ee6.png)

**90 days**
![image](https://user-images.githubusercontent.com/73545194/109309076-c669ce00-787d-11eb-8116-ba4de71d3990.png)

I also compared the data to what is showing in the Adsense module.
