### ISSUE TITLE
Site Kit Settings | Settings-> Admin: opt in/out to tracking

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#274]
Set up Site Kit Settings | Settings-> Admin: opt in/out to tracking

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* n/a

## Implementation Brief

* n/a

## Changelog entry

* N/A

**Comment by swissspidy** [comment]
Review: ✅
