### ISSUE TITLE
Add Analytics events for interacting with All Traffic widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2740]
We should add Analytics events for certain interactions with the new All Traffic widget that was introduced in 1.25.0.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following Analytics events should be sent when interacting with the new All Traffic widget:
    * `tab_select`: User selects a specific tab (event label should be the dimension name, e.g. `ga:device`)
    * `slice_select`: User selects a specific pie slice (event label should be the dimension name and dimension value, e.g. `ga:device:tablet`)
    * `help_click`: User clicks "(other)" or "(not set)" help link in tooltip (event label should be `(other)` or `(not set)`)
    * `others_source_click`: User clicks on the Analytics deep link in the "Others" tooltip (no event label)
* For all of these events, the event category should be `all_traffic_widget`.

## Implementation Brief
* Using `/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/DimensionTabs.js`
	* Import `trackEvent` from `../../../../../util`
	* Update the `handleTabUpdate` function to call the `trackEvent` function with the following values:
		* Category: **all_traffic_widget**
		* Action: **tab_select**
		* Label: The selected dimension name.
* Using `/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js`
	* Import `trackEvent` from `../../../../../util`
	* Update the `onSelect` callback of the chart to track when a slice is selected using the values below. `trackEvent` function should be called only then a slice is selected, i.e when dimension name is set, and not when deselecting a slice.
		* Category: **all_traffic_widget**
		* Action: **slice_select**
		* Label: The selected dimension name and dimension value, separated by **:**. For e.g `ga:device:tablet`.
	* Update the `getTooltipHelp` function to:
		* Add a new param to the function, `rowLabel` which will populate a new `data-row-label` attribute on the anchor tag.
		* Add a new class name to the anchor tag, `googlesitekit-cta-link__tooltip`.
	* Update calls where `getTooltipHelp` is called, to add the `rowLabel` as the third parameter.
	* Add a new `onClick` event listener to the `div` wrapping the `GoogleChart` component. The `onClick` callback should be a function which checks whether the target contains the `googlesitekit-cta-link__tooltip` class name and get the `data-row-label` attribute. Based on the data attribute, i.e either **(other)** or **(not set)** or **Others**, the `onClick` callback should call the `trackEvent` function with the following logic:
		* If the data attribute is either **(other)** or **(not set)**, use the following values:
			* Category: **all_traffic_widget**
			* Action: **help_click**
			* Label: The value for which the link was clicked, i.e either **(other)** or **(not set)**.
		* If the value is **Others**, use the following values:
			* Category: **all_traffic_widget**
			* Action: **others_source_click**
			* Label: null

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* Install the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) extension to your Google Chrome browser and activate it on your local site;
* Set up the plugin on your local and activate tracking for your site in the admin settings;
* Activate and connect the Analytics module;
* Go to the dashboard page and make sure you see the all traffic widget;
* Open browser console, click on a dimension tab, and make sure you see a new GA event has been fired and tracked in your console;
* Now select different slices and make sure you see the appropriate GA events in your console;
* Finally, click on a link in the tooltip for a slice for `(other)`, `(not set)` or `Others` label and make sure the appropriate event is fired again.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
> Update the `getTooltipHelp` function to add an `onClick` event listener if the label is either **(other)** or **(not set)** or **Others**. 

@asvinb I don't think this will work because `getTooltipHelp` returns a string of HTML to add to the tooltip.

In this case I think `UserDimensionsPieChart` needs to add a single deferred event listener to handle the click events since we don't have direct control over the tooltip. One question for @felixarntz thought before we update this:

@felixarntz I thought we were going to remove links from tooltips (thus making the above a non-issue), but I didn't see an issue for this yet.

Also, one question I have about the intended behavior: should the events be triggered when a user _deselects_ the slice since this is also a select action, or are we only interested in events with all values?

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb Let's keep the links for now - the problem is more that the tooltips don't always overlay the slices IMO. We'll still have to look into that, but let's not remove links from tooltips because of that issue.

Regarding the `slice_select` events, they should only be triggered when the slice is selected (i.e. when the new `dimensionValue` is set, rather than emptied).

**Comment by asvinb** [comment]
👍  Thanks for catching that @aaemnnosttv . IB has been updated.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb, the IB looks just about ready but it seems we're still missing a step for handling the `others_source_click` event. It looks like you have this as part of the `help_click` action, but it should be separate per the ACs.

**Comment by asvinb** [comment]
> Thanks @asvinb, the IB looks just about ready but it seems we're still missing a step for handling the `others_source_click` event. It looks like you have this as part of the `help_click` action, but it should be separate per the ACs.

Updated @aaemnnosttv

**Comment by aaemnnosttv** [comment]
Thanks @asvinb, I think the only thing left is regarding the tracking on slice selection which should only happen when a slice is being selected, not on deselection which happens when you select the currently selected slice. See https://github.com/google/site-kit-wp/issues/2740#issuecomment-780061422

**Comment by asvinb** [comment]
@aaemnnosttv I've updated the IB to make it clear that tracking should only occur when a slice is selected :) I already mentioned when a slice is selected before, but made it clearer now 😁

**Comment by aaemnnosttv** [comment]
Thanks @asvinb !

IB ✅

**Comment by wpdarren** [comment]
@eugene-manuilov likely to be user error, but I am not seeing any Google Adsense events when I click on a dimensions tab, a slice, including `(other)` ` (not set)` or Others.  Would you be able to include a screenshot of what you see, so I can compare it. Just wanting to make sure that I am looking at the right place in the console. 

![image](https://user-images.githubusercontent.com/73545194/109112942-65a39e00-7776-11eb-85bf-f29389bccaef.png)

I'm wondering if it is because I'm using the tester plugin.  

With the GA chrome extension, as you can see its only picking up the Google Analytics container. 

![image](https://user-images.githubusercontent.com/73545194/109113319-07c38600-7777-11eb-8ff4-70cf29b822bb.png)

**Comment by eugene-manuilov** [comment]
> ...but I am not seeing any Google Adsense events when I click on a dimensions tab...

@wpdarren have you installed the extension mentioned in the QA brief? Once you install it and activate (by clicking on its icon), you will see logs in your browser console (open the `Console` tab in the developer tools). Also, don't forget to opt-in for tracking in the admin settings.

This is what you should see if you activate that extension and activated tracking in the admin settings:
![Screenshot from 2021-02-25 09-30-40](https://user-images.githubusercontent.com/873049/109118804-793a0f00-774c-11eb-8da9-5a18f9e7ab9d.png)

Here is what you will see when you select a slice and a custom event is sent:
![Screenshot from 2021-02-25 09-30-48](https://user-images.githubusercontent.com/873049/109118915-a1c20900-774c-11eb-94c2-c146f81971d5.png)

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@eugene-manuilov An observation. When I click on a  `Others` there is no trigger in the console. I am wondering if it is [related to this](https://github.com/google/site-kit-wp/issues/2714#issuecomment-785674747) that I reported on another ticket.  Please note that I do not have a test site with `(other)`, `(not set)` so unsure if that works. 

Could you confirm if you are able to recreate this? 

**Verified:**

- On a dimension tab, a new GA event has been fired and tracked in your console

![image](https://user-images.githubusercontent.com/73545194/109169751-19c71800-77bb-11eb-80e3-89664dc2c057.png)

- With different slices selected, they appear in the GA events in your console

![image](https://user-images.githubusercontent.com/73545194/109169850-32373280-77bb-11eb-9758-c91e553fbf5b.png)

**Comment by eugene-manuilov** [comment]
@wpdarren it's expected behavior because `Others` is not selectable since it is not a real slice.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- On a dimension tab, a new GA event has been fired and tracked in your console

![image](https://user-images.githubusercontent.com/73545194/109169751-19c71800-77bb-11eb-80e3-89664dc2c057.png)

- With different slices selected, they appear in the GA events in your console

![image](https://user-images.githubusercontent.com/73545194/109169850-32373280-77bb-11eb-9758-c91e553fbf5b.png)
