### ISSUE TITLE
All Traffic dimension tabs not displaying on small screen sizes

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#2743]
## Bug Description

Discussed this with @felixarntz on #2663. 

For small screens (iPhone 6 similar screen sizes) not all of the dimension tabs are displayed on the new All Traffic widget. I realise you can swipe across to see the next tab but it is not obvious. Only a minor issue since very few people will be using mobile in the WordPress dashboard but thought I would raise it. 

## Steps to reproduce

1. Use a phone with small screen size, i.e. `iPhone6`. 
2. Connect `Google Analytics`
3. Scroll to the `All Traffic` widget
4. Look for the dimension tabs and observe that not all 3 are appearing. 

## Screenshots

[Screenshot](https://user-images.githubusercontent.com/73545194/106609908-12886200-65a1-11eb-8e47-f94d6315e399.png)

## Additional Context

 - OS: iOS and Android
 - Browser: Chrome & Safari
 - Plugin Version: Latest version
 - Device: iPhone6 and similar screen sizes.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On narrow viewports (smaller than `tablet`), the three tabs in the All Traffic widget should render as a dropdown with three options instead (like the one below).
![image (1)](https://user-images.githubusercontent.com/3531426/107295785-f5321880-6a24-11eb-8a84-02f0d0910271.png)

## Implementation Brief
* Using `/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/DimensionTabs.js`
	* Import the `Select` and `Option` components from `/assets/js/material-components`
	* Loop through the existing `tabs` constant to build the dropdown using the `Select` and `Option` components.
	* The `value` of each option should be the dimension index from the `tabs` constant.
	* The `onEnhancedChange` callback for the `Select` component can use the existing `handleTabUpdate` function.
	* Wrap the `Select` component within a container which is only visible on small screens, using `display: none` (`$bp-mobileOnly`).
	* Wrap the `TabBar` component within a container which is hidden on small screens only.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief
* Visit the main dashboard where we have the "All Traffic widget"
* Resize browser to < 600px
* A dropdown should appear instead of the tabs.
* Selecting an option from the tab should show updated charts data.
* Resize browser to > 600px
* The dropdown should no longer be visible, instead the tabs should be.

## Changelog entry

* Display All Traffic widget dimension tabs as a dropdown on narrow viewports.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- When viewing the "All Traffic widget" on a mobile (<600px) the dropdown appears.  I am able to select each dimension and the pie chart updates and correct stats appear in the user section.  [Screenshot](https://user-images.githubusercontent.com/73545194/108059028-dd473e00-708f-11eb-9b80-679d764d7ec4.png)

- When viewing the "All Traffic widget" on a tablet or desktop (>600px) the dropdown disappears and is replaced with the three dimension tabs.  [Screenshot](https://user-images.githubusercontent.com/73545194/108059038-e3d5b580-708f-11eb-902a-97d2c1012028.png)
