### ISSUE TITLE
Search Console x-axis labels truncated on 90 day charts

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2747]
## Bug Description

Currently our charts used on most overview pages show dates below the chart along the x-axis. This works fine in most cases, and the chart will dynamically show less labels as the width of the viewport gets narrower. However, even on a large display, the 90-day range results in some of the labels being individually truncated with what seems to be a `text-overflow: ellipsis;` style.

![image](https://user-images.githubusercontent.com/1621608/106648510-0b5d5600-6599-11eb-9a32-8ed2980ce81f.png)

## Steps to reproduce

1. Go to the Search Console dashboard page with a site that has at least 90 days of data
2. Select the 90 day date range
3. See squished labels

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the Search Console module page, when selecting 90 days, the dates on the x-axis of the graph should not be truncated. Less dates should be displayed as applicable to make it appear in a better way.

## Implementation Brief

* In `modules/search-console/components/dashboard/SearchConsoleDashboardWidgetSiteStats.js`, we need to ensure that  the following rule is added to the chart's `options`:
```javascript
// This small reduction in height gives the x-axis labels the room they need
chartArea.height = '77%'; 
```

### Test Coverage

* No new tests need to be added; existing ones should all pass.

### Visual Regression Changes

* This should introduce no new regressions.

## QA Brief

* Go to the Search Console module page
* Select the 'last 90 days' date range
* Investigate the chart at various screen widths: none of the horizontal axis labels should truncate 

## Changelog entry

* Fix Search Console x-axis labels on 90 day charts

**Comment by tofumatt** [comment]
The ACs here mention reducing the number of labels that appear rather than making them all fit, but I think I prefer your solution as it's less-complex and lets the chart library manage things for us.

But I wonder why we'd bother to use anything but this solution for all sizes? I tried it and it seems/looks fine, so rather than change the style based on the number of days shown (which seems a bit odd to me and might strike someone as unexpected), let's just use those options as the default options for all date range views for this component, if others are cool with that.

**Comment by johnPhillips** [comment]
@aaemnnosttv Do you have any thoughts on this? 

Happy to look into an IB that generates the number of ticks based on the date range, but the chart seems to have lots of automatic measures for adjusting the labels to fit the space (rotation, stacking, ellipses etc), the behaviour of which might change and represent a 'moving goal' over time. I feel like we'd be potentially generating work for ourselves down the line by monkey patching it with our own logic.

Agreed as well that it might appear strange to stumble across this fix and see the chart style change based on the date range. Might a comment be the simple answer here? 

My personal inclination is to do the bare minimum to tidy up this edge case and let it do its thing in other cases. However, I'm very happy to look into just applying this rule on all date ranges as Matt suggests. 

I'll defer to you guys as you have more experience with these charts! :-) Let me know what you think, and I'll happily update the IB in the direction you recommend.

**Comment by aaemnnosttv** [comment]
@johnPhillips I agree that it's best to delegate the label management to the chart library as much as we can and avoid special date-range specific cases. In this case, it seems like the `chartArea.height` is the only change needed. The text is already slanted automatically if all elements don't fit when drawn upright, which is good. I don't think we should change the chart to always slant the text because it's less readable that way. We shouldn't compromise the other 3 date ranges for consistency with the special case.

Let's keep the height change and leave the `slantedText` to its default automatic behavior 👍

**Comment by johnPhillips** [comment]
@aaemnnosttv and @tofumatt 
There is an edge case on 90 days where the screen is very wide: the labels get stacked. That was the reason for forcing the slant on 90 days. 

Are we ok with this?

![Screenshot 2021-02-26 at 11 45 04](https://user-images.githubusercontent.com/2470911/109296433-3188b580-7828-11eb-9374-5ad0f895d743.png)

**Comment by aaemnnosttv** [comment]
Oh I guess my screen isn't wide enough to see that 😄 thanks for the screenshot.

I don't think it's too bad. The main thing for me is for them not to be truncated which is what this was originally about.

Anything more than that is a visual change that we'll need approval from @felixarntz on.

**Comment by johnPhillips** [comment]
@aaemnnosttv Mine isn't either, in that screenshot I am using the 'responsive' setting on dev tools at a width of "2500". Feels like an edge case 😂

I'll adjust the IB - thanks for your input!

**Comment by aaemnnosttv** [comment]
IB ✅  😄

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

On the Search Console module page, with a 'last 90 days' date range, the chart at various screen widths, none of the horizontal axis labels truncate. 

![image](https://user-images.githubusercontent.com/73545194/109969257-aa0edb00-7d2e-11eb-8275-fac67602a019.png)

@aaemnnosttv I do want to make an observation that on a 27" monitor with 2560 × 1440 pixels the labels start to look odd but aren't truncated. 

![image](https://user-images.githubusercontent.com/73545194/109970005-8730f680-7d2f-11eb-9d63-b209ecb02081.png)
