### ISSUE TITLE
Allow reset of persistent Site Kit options

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2748]
#2692 and #2626 have introduced a new pattern where Site Kit options or user options that are persistent should not be deleted when resetting or disconnecting.

For regular production use, it **must not** be possible to delete those settings. However, for development, allowing this is crucial, e.g. in e2e tests. Including persistent reset functionality in the plugin itself (rather than only E2E) could be useful in QA as well, but for now we should keep support limited to development tools.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new PHP class `Core\Util\Reset_Persistent` which works the same as `Core\Util\Reset`, but deletes all options and user options that start with `googlesitekitpersistent_` (_only_ those). Its REST route should be `core/site/data/reset-persistent`.
* There should be an e2e utility that uses the above endpoint and can be leveraged to reset the persistent settings.
* The `googlesitekit reset` WP-CLI command should be extended to support an optional `--persistent` flag. If set, it should also reset the persistent settings using the above new class.

## Implementation Brief

* Update the `Core\Util\Reset` class
	- Remove `final`
	- Update `self::` to `static::`
	- Extract `'core/site/data/reset'` to new `REST_ROUTE` class constant
* Create a new `Core\Util\Reset_Persistent` class, extending `Reset`
	- `KEY_PATTERN = 'googlesitekitpersistent\_%';`
	- `REST_ROUTE = 'core/site/data/reset-persistent'`
	- Instantiate and register in `Plugin::register` like `Reset`  
	_We could alternatively only register this in an E2E mu-plugin but it could be useful in other contexts (see below)_
* Update the `resetSiteKit` E2E utility to accept an object of options
	- Define `[options.persistent]` which should default to `false`
	- If `options.persistent` is `true`, send a request to `core/site/data/reset-persistent` as well, just after the main reset request
* Update the E2E `bootstrap.js` to calls to `resetSiteKit` to pass `persistent` as `true`
* Extend the `Reset_CLI_Command` in a similar way to support an optional `--persistent` flag which when provided runs the persistent reset.

### Test Coverage

* Add PHPUnit tests for `Core\Util\Reset_Persistent`

### Visual Regression Changes

* N/A

## QA Brief

```
$ wp option add googlesitekit_foo bar
Success: Added 'googlesitekit_foo' option.
$ wp option add googlesitekitpersistent_foo bar
Success: Added 'googlesitekitpersistent_foo' option.
$ wp option get googlesitekit_foo
bar
$ wp option get googlesitekitpersistent_foo
bar
$ wp google-site-kit reset
Success: Settings successfully reset.
$ wp option get googlesitekit_foo
Error: Could not get 'googlesitekit_foo' option. Does it exist?
$ wp option get googlesitekitpersistent_foo
bar
$ wp google-site-kit reset --persistent
Success: Settings successfully reset.
$ wp option get googlesitekitpersistent_foo
Error: Could not get 'googlesitekitpersistent_foo' option. Does it exist?
```

## Changelog entry

* Allow resetting persistent Site Kit options via WP-CLI.

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
@felixarntz adding a new endpoint that replicates the behavior of the existing one seems like overkill. Why not to add the `?persistent=true` argument to the existing reset endpoint and update the Reset class to remove persistent options as well if requested?

**Comment by wpdarren** [comment]
@eugene-manuilov @aaemnnosttv is this for `QA:Eng`? If not, please could we have additional information on what is to test?

**Comment by aaemnnosttv** [comment]
@wpdarren I've marked it for eng QA 👍

**Comment by tofumatt** [comment]
QA ✅
