### ISSUE TITLE
Expose registry select and dispatch to module `checkRequirements` functions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2749]
## Feature Description

In #2587 we did away with accessing the global registry outside of our JS entry points. A complications of this change exposed areas where we were previously reaching for this instance where we shouldn't, such as the `checkRequirements` function for AdSense, which selects `isAdBlockerActive` from its datastore.

Given that datastore access is a reasonable dependency for module `checkRequirements` functions (see #2130) to have access to, we should provide it to those functions rather than encouraging global access.

See the original discussion here: https://github.com/google/site-kit-wp/pull/2593#discussion_r562093340

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `checkRequirements` function that can be registered for each module (via `registerModule` action of `core/modules`) should be passed the current `registry`, so that it can e.g. access `registry.select` as needed.
* The AdSense module `checkRequirements` function should be modified to use the provided `registry`, and the hack where the necessary selector is temporarily saved into a variable which was needed before should be removed.

## Implementation Brief
In `assets/js/googlesitekit/modules/datastore/modules.js`:
* Pass `registry` as a parameter to the call to `module.checkRequirements()`:
https://github.com/google/site-kit-wp/blob/b460234894bcbe28dd31a9422b57293e78021977/assets/js/googlesitekit/modules/datastore/modules.js#L453
* Add an `@since` comment to the doc block for `registerModule` in `assets/js/googlesitekit/modules/index.js` to reflect that checkRequirements now accepts a `registry` parameter.

In `assets/js/modules/adsense/index.js`:
* Remove the `let isAdBlockerActive = () => {};` on line 55.
* Remove the line in the `registerStore` function that sets `isAdBlockerActive`, and the `TODO` comment.
* Modify the signature of `checkRequirements` to accept the new `registry` parameter:
https://github.com/google/site-kit-wp/blob/b460234894bcbe28dd31a9422b57293e78021977/assets/js/modules/adsense/index.js#L77
* Refactor the call to `isAdBlockerActive` to use `registry.select( STORE_NAME ).isAdBlockerActive()` instead:
https://github.com/google/site-kit-wp/blob/b460234894bcbe28dd31a9422b57293e78021977/assets/js/modules/adsense/index.js#L78-L80

### Test Coverage

* No new tests required; existing tests should pass.

### Visual Regression Changes

* N/A

## QA Brief

* Verify that the hack in the AdSense module's `checkRequirements` function has been removed
* Check that flows that use the `checkRequirements` call still work correctly. e.g.:
  * Connecting to AdSense
  * Feature tours

## Changelog entry

* Improve the AdSense AdBlocker check.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by Hazlitte** [comment]
**QA ✅**
* Code is as per the IB
* Adsense connection flow works fine

**Comment by aaemnnosttv** [comment]
## QA ❌ 

The PR was implemented as the IB, but this is not (or is no longer) correct. I'm not sure if the underlying code changed since the IB was written but the previous selector was asynchronous, but it [has been changed to use the synchronous `registry.select`](https://github.com/google/site-kit-wp/pull/3485/files#diff-730069ff939870d1e1640e27bfe2b107916e1c80b45f1c210a7f90118279cc8d). The behavior here is important to remain asynchronous as it was.

Assigning back to @johnPhillips for a follow-up. cc: @tofumatt

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Previous feedback addressed by #3534 👍 

Thanks @johnPhillips !
