### ISSUE TITLE
Checking compatibility animation appears when disconnecting a site

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#2751]
## Bug Description

When a user clicks on the `Disconnect Site` link in the user menu, the screen appears to confirm that the site is disconnected but the `Checking compatibility` animation appears directly next to the `Reset Site Kit` link on load. I suspect that this should not be appearing when disconnecting?  If this is expected behaviour could we improve the UI so that there's space between the animation and reset link.

## Steps to reproduce

1. Go to the `user menu` in the top left corner
2. Click on `Disconnect Site`
3. The screen will appear confirming the site is disconnected
4. Observe the `Checking compatibility` animation

## Screenshots

![Annotation on 2021-02-02 at 21-06-41](https://user-images.githubusercontent.com/73545194/106605106-7b6cdb80-659b-11eb-8108-4b488ec359c0.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by fhollis** [comment]
Agreed to close as duplication of #2756
