### ISSUE TITLE
Admin Toolbar - error on hover: `Failed to execute ‘createElement’ on ‘Document’  

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2753]
## Bug Description

[One user is](https://wordpress.org/support/topic/failed-to-execute-createelement-on-document-error-message/#post-13997792) encountering the below message when hovering over the Site Kit admin dashboard menu icon:

```
Failed to execute 'createElement' on 'Document': The tag name provided ('core/location') is not a valid name.

    in core/location
    in div
    in withData(a)
    in a
    in Unknown
    in Unknown
    in WithFilters(a)
    in div
    in div
    in div
    in div
    in r
    in Unknown
    in Unknown
    in a
    in e
```

## Additional Context

 - Plugin Version: 1.25.0  
 - Awaiting Health Check & Troubleshooting Plugin check (some optimisation plugins active). When checking source code multiple optimisations evident, with assets combined
 - Site URL and full Site Health information provided [in form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=get10up.com&gxids=7628#response=ACYDBNidSRToMhOhFyc4DiYPe7dhUG5r9NkY-Mz-tCfYKTl4dmPvdRkJmkPjRw2tK5_FmEY)
 - No Site Kit related console errors when checking their site

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by agoll** [comment]
Howdy, 
User here. I've attached a video capture of the issue. 
I'm working (day job) at the moment, so I'll gather other info periodically throughout the day. 
This is an issue only I am able to see, and I suspect that this is a plugin compatibility issue. 

https://user-images.githubusercontent.com/34747792/106773180-07175400-65fe-11eb-9ab5-07473f1c66b0.mp4

**Comment by agoll** [comment]
Logged into website via "incognito" (as recommended in WP thread) and also MSFT Edge, and the problem went away. I only have blue boxes with "gathering data" messages (interesting as yesterday my dashboard showed data). 
Screenshot is from MSFT Edge, logged in. 
![gathering-data](https://user-images.githubusercontent.com/34747792/106794183-b14ea600-6615-11eb-8ca1-8695db4a78df.PNG)

Closed out original chrome browser, re-opened and disabled ALL browser extensions, closed browser and re-opened and issue persists. Logged out and logged back in with same result. 
Turned off SG Optimizer which defers render blocking JS and combines JS files for page loading speed and there was no change....

**Comment by jamesozzie** [comment]
Many thanks for the update and thorough testing. As the same issue is not occurring from an incognito window have you tried [clearing your browsers cache](https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en)?

**Comment by agoll** [comment]
WordPress auto-updated for me this morning and the problem seemed to have resolved itself! 
I love when these pesky odd bugs solve themselves. 

While this is now a moot point; my next step (and still a possibility) would have been to disable the black admin bar on the front end via the functions.php (aka: write a plugin).... 

Thanks so much for all of your help!

**Comment by jamesozzie** [comment]
@agoll No problem at all, thanks for bringing this to our attention, and happy to hear it's working as normal. I'll also pass this over to an engineer to check whether they can recreate the issue using the same setup as your own. 

@abdullah1908 Do you want to take a look at the details and see if there is any action required on the plugin side?

**Comment by abdullah1908** [comment]
Thanks @jamesozzie looking into it.

**Comment by abdullah1908** [comment]
@jamesozzie I couldn't replicate at my end as I tried on SG server. It might be the extensions installed in browser.
