### ISSUE TITLE
Don't show Reset link while compatibility checks are in progress

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2756]
## Bug Description

![image](https://user-images.githubusercontent.com/1621608/106868421-6eed9d80-66d7-11eb-81f9-65423379368d.png)

## Steps to reproduce

1. Go to splash page after reset or disconnect (or just for first time)
2. Notice the reset link displayed adjacent to the sign in button while "Checking compatibility" is in progress

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The link to [Reset Site Kit](#) should not be shown while compatibility checks are in progress

## Implementation Brief
* Using `/assets/js/components/setup/SetupUsingProxy.js`
	* Update the condition to show the `ResetButton` component by checking if `complete` is true.

### Test Coverage
* No changes expected.

### Visual Regression Changes
* No changes expected.

## QA Brief

* Follow `Steps to reproduce` above, and verify that the `Reset` link doesn't appear until the check has finished.

## Changelog entry

* Reset link hidden while compatibility checks are in progress

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
### QA ✅ 

Confirmed the current bug:
![Plugins ‹ Hellogoodbye1 — WordPress](https://user-images.githubusercontent.com/57115907/108301986-ef8caf00-7157-11eb-8ff1-5c5fb6bf2049.gif)

Installed latest develop and checked setup and reset screen again:
![Site Kit by Google Dashboard ‹ Hellogoodbye1 — WordPress (10)](https://user-images.githubusercontent.com/57115907/108302142-38446800-7158-11eb-99da-eadba5273236.gif)

Confirmed setup functions properly. Basic smoke test passed.
