### ISSUE TITLE
Refactor Tracking related classes

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#2764]
## Feature Description

While working on IB for #2103 it turned out that we would need to refactor tracking related classes that currently live in the Utils folder. We should create a separate namespace (let's say `Google\Site_Kit\Core\Tracking`) and move `Google\Site_Kit\Core\Util\Tracking` and `Google\Site_Kit\Core\Util\Tracking_Consent` classes into it. Furthermore, we need to refactor the REST API endpoint added in the aforementioned ticket into its own class `REST_Tracking_Consent_Controller` and put it into the same namespace.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new namespace `Google\Site_Kit\Core\Tracking` should be added.
* Classes `Google\Site_Kit\Core\Util\Tracking` and `Google\Site_Kit\Core\Util\Tracking_Consent` should be moved into the new namespace.
* A new `REST_Tracking_Consent_Controller` class should be added into the same namespace.
* Rest routes defined in the Tracking class should be moved to the controller class.
* Overall the new Tracking namespace should follow the approach used for Dismissals and Feature_Tours.

## Implementation Brief

* Add a new folder `Tracking` in the `includes/Core` directory.
* Move  `Google\Site_Kit\Core\Util\Tracking` and `Google\Site_Kit\Core\Util\Tracking_Consent` classes into the new `Tracking` folder and update namespaces in both files.
* Add a new `REST_Tracking_Consent_Controller` class to the `Tracking` folder.
* Move REST-related functionality from the `Tracking` class into the new `REST_Tracking_Consent_Controller` class.

### Test Coverage

* Move `TrackingTest` and `Tracking_ConsentTest` classes into the corresponding folder as well and update namespaces in it.
* Fix broken phpunit tests.

### Visual Regression Changes

* N/A

### New installations

![2021-12-21_13-01](https://user-images.githubusercontent.com/3921289/146987956-6bc7326f-3e3d-4b07-a583-f3e00be4239a.png)

1. During the installation of the plugin enable the checkbox to enable tracking.

![2021-12-21_13-39](https://user-images.githubusercontent.com/3921289/146987936-aaa7bb2e-a907-446c-a6ab-9bdef2aae224.png)

2. A request to the tracking endpoint was done (review the network tab on the browser)
3. Reload the page and the selection should be saved,
3. Repeat the process unchecking the tracking option.

### Existing installations.

1. Complete the setup of site kit.
![2021-12-21_13-58](https://user-images.githubusercontent.com/3921289/146990345-7eeebedc-90d1-422b-a306-281494f80390.png)

2. Go to Dashboard > Site Kit > Settings > Admin Seetings
3. Scroll to the bottom and enable/disable the tracking setting
4. Refresh the page and observe your setting was saved as expected. 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you propose some ACs for this?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv could you please review AC?

**Comment by aaemnnosttv** [comment]
Looks good to me @eugene-manuilov 👍

**Comment by tofumatt** [comment]
IB ✅ 

Sounds good to me 👍🏻

**Comment by eugene-manuilov** [comment]
@mitogh could you please add QAB?

**Comment by mitogh** [comment]
QAB :heavy_check_mark:  @eugene-manuilov

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_New installation_

- When tracking checkbox is enabled, the tracking endpoint appears in the network tab.  The tracking continues to be enabled after a page reload.  
- When the tracking checkbox is disabled, the tracking endpoint does not appear, and continues to be disabled on page reload.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/148039114-cb1903e8-9701-4603-8d03-0ba3baf67cf7.png)

![image](https://user-images.githubusercontent.com/73545194/148039140-5e9f86f2-495e-4770-ada0-65fdcfcc0c15.png)

</details>

_Existing installation_

- When tracking checkbox is enabled, the tracking endpoint appears in the network tab.  The tracking continues to be enabled after a page reload.  
- When the tracking checkbox is disabled, the tracking endpoint does not appear, and continues to be disabled on page reload.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/148039490-24b38fb0-67c4-444c-866f-7993fb053191.png)

![image](https://user-images.githubusercontent.com/73545194/148039524-1f59d6a6-3d58-42e2-9239-60bbf0f46206.png)

</details>
