### ISSUE TITLE
Difficulty moving site from Test URL to Production URL

### ISSUE THREAD

**Issue by NexPlex** [google/site-kit-wp#2767]
## Bug Description

We do our WordPress build on wptest.xxxx.com then move it to www.xxxx.com. After installing and configuring G Site Kit on wptest.xxx.com all works well without errors.

When we migrate the wptest site to www site G site kit shows this error: **"Site Kit can’t access necessary data"** If we click on "Redo Setup" we get this error: **'redirect_uri' mismatch**

## Screenshots

![image](https://user-images.githubusercontent.com/34607168/107128111-ed7d4300-686f-11eb-938a-20debb130322.png)

## Additional Context

 - PHP Version: 7.3.14
 - Browser [e.g. chrome, safari] Chrome or MS edge
 - Plugin Version [e.g. 22] 1.25.0
 - Device: [e.g. iPhone6]  PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by NexPlex** [comment]
I found the directions for setting up a staging environment. 
https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/

**Comment by jamesozzie** [comment]
@NexPlex Glad to hear you were able to setup the site via a stagign site setup. If you encounter any issues be sure to [open a WordPress support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post), where we'd be happy to assist.
