### ISSUE TITLE
Couldn't initialize - Service 'webmasters.googleapis.com' not found 

### ISSUE THREAD

**Issue by NexPlex** [google/site-kit-wp#2768]
## Bug Description

Pressing on GET OAUTH CREDENTIALS this errors pops up:

Couldn't initialize
Service 'webmasters.googleapis.com' not found or permission denied.

## Steps to reproduce

1. From WordPress "Site kit developer setting" page click on. Create your credentials(opens in a new tab)
2. new page opens
2. scroll to the bottom
3. click on Get oAuth Credentials
4. get error
5. Couldn't initialize
Service 'webmasters.googleapis.com' not found or permission denied.

## Screenshots

![image](https://user-images.githubusercontent.com/34607168/107129076-bc087580-6877-11eb-9a38-0c8031cdb914.png)

## Additional Context

 - PHP Version: 7.3.14
 - Browser [e.g. chrome, safari] chrome
 - Plugin Version [e.g. 22] 1) site kit 1.25.0 2) Dev settings 0.4.0
 -  - Device: [e.g. iPhone6] PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@NexPlex Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. We can also open this GitHub issue should we determine any bug or issue with setting up Site Kit on a staging site. 

Please include as much relevant information to your support topic as needed to assist with this issue. In your case this may include the staging site URL or your Site Health information. You can use [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) to share privately after creating a support topic.

**Comment by abdullah1908** [comment]
@jamesozzie I am opening this issue as I can reproduce it at my end.

**Comment by abdullah1908** [comment]
The same [issue](https://github.com/google/site-kit-wp/issues/2463) is already created. Currently we are working on this issue internally & will update here once its fixed.

**Comment by abdullah1908** [comment]
Our team has fixed the issue internally & now the helper plugin should work with the staging site setup.
