### ISSUE TITLE
Stopped after allow/allow/next - then blank page

### ISSUE THREAD

**Issue by BMUZAMMIL** [google/site-kit-wp#277]
Stopped after I allowed/allowed and after I hit next
**This is the URL:**
https://www.qrence.com/?oauth2callback=1&code=4/hwF5krEAaSyF4y491APb-XhcSMwtoUQzDVxs-pr1JBMXBKaY9aOEhJV5Q4vFmyD9vv907r5njn3y0QcJSgmuJ9c&scope=email%20profile%20https://www.googleapis.com/auth/webmasters%20https://www.googleapis.com/auth/siteverification%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&session_state=eae8e76829f2e18bc8e43a3519fdffe766e3c33d..46c4&prompt=consent

**Comment by BMUZAMMIL** [comment]
I will wait for the full release. uninstalled the plugin.

**Comment by jamesozzie** [comment]
@BMUZAMMIL Sorry to hear you are encountering issues. There could be a number of reasons you are see a blank page, such as security/firewall plugins or your server environment. 

Please try the following steps to activate Site Kit. If unsuccessful you can reply with any console errors and we can investigate further:  
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png)
3. Temporarily deactivate your other active WordPress plugins
4. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
5. Install Site Kit in a new incognito window (so Chrome extensions don't interfere and caching inactive)

**Comment by iamshaharyar** [comment]
@jamesozzie I have tried all these steps again after resetting the site kit and also disabled all plugins to check but it's still not working. Its showing up like that http://prntscr.com/offkrr

**Comment by jamesozzie** [comment]
@BMUZAMMIL I will close this issue now, but if the issue remains feel free to reopen. If so please add any console errors that appear and provide any screenshots displaying the error
