### ISSUE TITLE
Link to Analytics FE for AdSense widgets based on Analytics data

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2772]
## Bug Description

Site Kit currently has deep links to the AdSense frontend on all AdSense widgets. While at first glance this seems to be expected, there are some AdSense widgets which are actually powered by Analytics. These widgets only show data when Analytics is also active and when the AdSense account is linked to the Analytics property.

These links should be updated to go to the relevant Analytics frontend area instead. The base URL for the relevant report is `https://analytics.google.com/analytics/web/#/report/content-publisher-overview`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense top earning pages widget on the Site Kit dashboard as well as the top earning pages widget on the AdSense module page should deep link to the relevant Analytics report, using the `getServiceReportURL` selector from the `modules/analytics` store. For `type`, they should pass `content-publisher-overview`.
* The labels for all of these source links should be modified to refer to "Analytics" instead of "AdSense", where not already the case.
* For those components where the datastore is being used (at least the refactored version of the AdSense dashboard widget), the dates based on the current date range should be passed to the selector (see other usages of the Analytics `getServiceReportURL` selector for reference).
    * If this is trivial to achieve for the legacy components, it's worth doing - but we shouldn't make any significant changes to the code in these components.

## Implementation Brief

* Modify the `DashboardTopEarningPagesWidget` component in the AdSense module to use the `getServiceReportURL` selector instead of the `getServiceURL`;
  * Pass `content-publisher-overview` as the first argument into the `getServiceReportURL` selector;
  * Pass `{ '_u.date00': startDate, '_u.date01': endDate }` as the second argument into the selector (`startDate` and `endDate` should be formatted to `YYYYMMDD`).
* Modify the `AnalyticsAdSenseDashboardWidgetLayout` component in the Analytics module:
  * Grab the current range start and end dates using the following selector:
    ```javascript
    const dateRangeDates = useSelect( ( select ) => select( CORE_USER ).getDateRangeDates( {
        offsetDays: DATE_RANGE_OFFSET,
    } ) );
    ```
  * Use the `getServiceReportURL` selector from the `modules/analytics` datastore instead of the `getServiceAccountSiteURL` from the `modules/adsense` datastore:
    * Pass `content-publisher-overview` as the first argument into the `getServiceReportURL` selector;
    * Pass `{ '_u.date00': startDate, '_u.date01': endDate }` as the second argument into the selector (`startDate` and `endDate` should be formatted to `YYYYMMDD`).
  * Update the `headerCTALabel` property to use `See full stats in Analytics` text.

### Test Coverage

* N/A

### Visual Regression Changes

* Source links should be updated to lead to the appropriate pages in the Analytics FE.

## QA Brief

* Go to the Site Kit dashboard (`/wp-admin/`)
  * the AdSense 'top earning pages' widget should deep link to the correct Analytics report
  * the label should refer to "Analytics" instead of "AdSense"
* Go to the AdSense module page (`/wp-admin/admin.php?page=googlesitekit-module-adsense`)
  * the 'top earning pages' widget here should also deep link to the relevant Analytics report
  * the label should refer to "Analytics" instead of "AdSense"

## Changelog entry

* Update link on AdSense module page to point to Analytics which is more accurate due to the source of the data.

**Comment by johnPhillips** [comment]
Note: this is one of the issues assigned to me this sprint - I will pick it up in execution once the IB has been reviewed 👍

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
CR ✅   but will hold on merging due to the timing of the current cycle, unless @felixarntz wants to include it.

**Comment by aaemnnosttv** [comment]
@johnPhillips would you please add a QA brief above?

**Comment by wpdarren** [comment]
### QA Update: Engineer to confirm ⚠️ 

@johnPhillips on the QAB it says 
```
Go to the AdSense module page (/wp-admin/admin.php?page=googlesitekit-module-adsense) the 'top earning pages' 
widget here should also deep link to the relevant Analytics report
the label should refer to "Analytics" instead of "AdSense"
```
When I go that page, this is what I see.  

![image](https://user-images.githubusercontent.com/73545194/109275172-55132680-784f-11eb-8d7d-c9cc25d56b1b.png)

- I don't see `top earning pages` but I do see `Performance by page over the last XX days`
- I also don't see any link label for `Analytics` There is a `See full stats in Analytics`

Please could you confirm if this is correct, or, am I seeing the wrong screen?  I am looking at the `develop` branch. 

**Verified:**

- On the Site Kit dashboard, the AdSense 'top earning pages' widget link to the correct [Analytics report](https://analytics.google.com/analytics/web/#/report-home/a184504120w254830281p233972010) and the label refers to `Analytics` 

![image](https://user-images.githubusercontent.com/73545194/109274282-47a96c80-784e-11eb-961d-3a977dc26abf.png)

**Comment by johnPhillips** [comment]
Hi @wpdarren 
I think this is confusing and possibly partially down to a poor QAB by me, so apologies about that. 

Working through your points:

> I don't see top earning pages but I do see Performance by page over the last XX days

I assumed that the AC was referring to that widget because it does show page earnings and there is nothing else on this module page that it could plausibly be referring to. However, I've then compounded the confusion by using the same wording in the QAB, so I'm sorry about that. Either way, I think this must be the widget it means 👌

> I also don't see any link label for Analytics There is a See full stats in Analytics

Yes, this is correct. It used to say `See full stats in Adsense`, so the QAB here (`the label should refer to "Analytics" instead of "AdSense"`) is referring to this change.

![Screenshot 2021-02-26 at 10 26 42](https://user-images.githubusercontent.com/2470911/109288824-49a70780-781d-11eb-8554-1aff3347611e.png)

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- On the Site Kit dashboard, the AdSense 'top earning pages' widget link to the correct [Analytics report](https://analytics.google.com/analytics/web/#/report-home/a184504120w254830281p233972010) and the label refers to `Analytics` 

![image](https://user-images.githubusercontent.com/73545194/109274282-47a96c80-784e-11eb-961d-3a977dc26abf.png)

- On the Google Adsense mobile, the list of pages by performance appear along with a link to the report in Analytics. 

![image](https://user-images.githubusercontent.com/73545194/109275172-55132680-784f-11eb-8d7d-c9cc25d56b1b.png)
