### ISSUE TITLE
AdSense dashboard summary widget should deep link to AdSense FE

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2774]
The AdSense dashboard summary widget currently links to the AdSense module page, which is inconsistent behavior from all the other dashboard widgets (which deep link to the respective Google service frontend). The widget should be updated to deep link to the relevant AdSense report in the Google service frontend.

This is a follow-up improvement to #2689.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The source links in the AdSense dashboard widget (**only the refactored version**, no need to bother with the legacy one!) should link to the relevant AdSense frontend report, using the `getServiceReportURL` selector from the `modules/adsense` store.
    * They should pass the dates based on the current date range, taking into account the offset (use `generateDateRangeArgs`).
* The source links should then be marked as external links.

## Implementation Brief

Update the `DashboardSummaryWidget` component in the `assets/js/modules/adsense/components/dashboard/DashboardSummaryWidget.js` file to do the following:
* Select the current date range with:
  ```javascript
  const dateRangeDates = useSelect( ( select ) => select( CORE_USER ).getDateRangeDates( {
      offsetDays: DATE_RANGE_OFFSET,
  } ) );
  ```
* Get date range args using `generateDateRangeArgs( dateRangeDates )`;
* Using the `getServiceReportURL` selector from the `modules/adsense` datastore, create the following URLs:
  * the `rpmReportUrl` using date range args and `gm: 'pageViewsRpm'`;
  * the `earningsUrl` using date range args and `gm: 'earnings'`;
  * the `impressionsUrl` using date range args and `gm: 'monetizableImpressions'`;
* Update `source` properties of DataBlock elements to use the appropriate report URLs instead of the `href` constant;
* Add `external: true` to `source` properties of DataBlock elements to make source links look like external ones.

### Test Coverage

* N/A

### Visual Regression Changes

* Source links in the AdSense summary widget should lead to the relevant AdSense report in the Google service frontend instead of the plugin AdSense dashboard.

## QA Brief

* Set up the plugin on your local;
* Activate and connect the AdSense module;
* Go to the dashboard page and make sure that you see the AdSense summary widget;
* Make sure that the source links lead to the relevant AdSense reports in the Google service frontend.

## Changelog entry

* Update links on new version of AdSense dashboard summary widget to deep link to the respective area in the AdSense frontend.

**Comment by felixarntz** [comment]
IB ✅ 

@eugene-manuilov Great job finding out the relevant metric arguments - I was thinking to just link to the overall AdSense report overview which would already be an improvement, but if we can link to the specific metric report, even better!

**Comment by wpdarren** [comment]
@johnPhillips @felixarntz just wondering if this has merged successfully?

Still seeing the source Adsense links in the module, rather than Google reports. 

Tried this on the `develop` branch and also with `development build` using the tester plugin. 

![image](https://user-images.githubusercontent.com/73545194/109827097-68baf480-7c76-11eb-9d8c-22242efe382e.png)

**Comment by felixarntz** [comment]
@wpdarren did you activate the widgets.dashboard feature flag? By now, it is irrelevant which build you're using, it's now all controlled through the feature flag check boxes in the tester plugin.

**Comment by wpdarren** [comment]
@felixarntz I didn't but no one had communicated that to me.  I will relook at this testing.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

Within Site Kit Dashboard, the Adsense source links lead to the relevant reports in the Google service frontend.

![image](https://user-images.githubusercontent.com/73545194/109976325-9c5d5380-7d36-11eb-8058-818211c2d7c8.png)
