### ISSUE TITLE
I am trying to create " Get Oauth Credentials" but encountered error message "field [project_id] has issue [project_id contains invalid characters]"

### ISSUE THREAD

**Issue by SiewTin** [google/site-kit-wp#278]
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reporting. Can you please try this workaround and let me know if you manage to get to the next stage. #24 

- Close the "Couldn't create project" window
- In the address bar of your window paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
- Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
- Press enter, with your cursor in the address bar (as if you are visiting that URL)
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit

**Comment by SiewTin** [comment]
Hi James,

Thanks for reply and instruction.  I managed to copy to my site.
Unfortunately, I got the error message below when I tried to sign in to my
google account

.*Error: redirect_uri_mismatch*

The redirect URI in the request, https://marketingpat.com?oauth2callback=1,
does not match the ones authorized for the OAuth client. To update the
authorized redirect URIs, visit:
https://console.developers.google.com/apis/credentials/oauthclient/79557254425-3a1fipi9ftguocf07rdq668uddk7bkap.apps.googleusercontent.com?project=79557254425

Learn more
<http://developers.google.com/accounts/docs/OAuth2Login#setredirecturi>
Request Details

   - response_type=code
   - access_type=offline
   - client_id=
   79557254425-3a1fipi9ftguocf07rdq668uddk7bkap.apps.googleusercontent.com
   - redirect_uri=https://marketingpat.com?oauth2callback=1
   - state=
   - scope=https://www.googleapis.com/auth/userinfo.profile
   https://www.googleapis.com/auth/userinfo.email
   https://www.googleapis.com/auth/webmasters
   https://www.googleapis.com/auth/siteverification
   - prompt=consent

Appreciate your help. Thanks.

**Comment by jamesozzie** [comment]
@SiewTin Can you please try the following steps:

1. Delete the newly create [project](https://i.imgur.com/EoA1edo.png) from your Google Cloud Console
2. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
3. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png), along with 
4. Temporarily deactivate your other active WordPress plugins
5. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
6. Install Site Kit in a new incognito window (so Chrome extensions/caching doesn't interfere with the setup process)

**Comment by annakjaer** [comment]
> @SiewTin Can you please try the following steps:
> 
> 1. Delete the newly create [project](https://i.imgur.com/EoA1edo.png) from your Google Cloud Console
> 2. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
> 3. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png), along with
> 4. Temporarily deactivate your other active WordPress plugins
> 5. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
> 6. Install Site Kit in a new incognito window (so Chrome extensions/caching doesn't interfere with the setup process)

Hi, I have encountered the same problem and I tried to use your solution as described above, however, I don't have a cloud console account which costs money and I won't give them my card details even though they don't autorenew after the free trial, and my sitekit plugin doesn't have a ''settings'' section, so I cannot reset it. I've tried deactivating it, I've tried incognito mode - nothing works. Any other suggestions on how to fix this ? Why will the sitekit not just allow me to change the name? I cannot edit ANYTHING.

**Comment by jamesozzie** [comment]
@annakjaer Are you seeing the same error message during authentication as the original (field [project_id] has issue [project_id contains invalid characters])? If so can you try to manually create your credentials from the same screen using the steps below:

- Close the window where you see the error message
- In the address bar of your window paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
- Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
- Press enter, with your cursor in the address bar (as if you are visiting that URL)
- Click on the "GET OAUTH CREDENTIALS" button
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

An alternative to the above steps is to try change the language of wordpress to English US before changing your "Site Title" and "Tagline" to standard English characters from the settings menu (during Site Kit setup)
 
With regards signing up to Google Cloud Platform there is no charge having Site Kit setup a project using your standard Google account.  If any of the above fail to resolve your issue please send me any console errors that appear and inform me what WordPress plugins you have in use.

**Comment by annakjaer** [comment]
It is the same problem as the person who started this thread.

I tried the other solution as well, but still got the project id error.

I've tried looking in the cloud console, but there appear to be no projects
set up there.

**Comment by annakjaer** [comment]
I have Bluehost, elementor pro, Google analytics, Ithemes security, jetpack, polylang, redirection, review slider, wpforms lite, and yoast seo.

**Comment by jamesozzie** [comment]
Do you mind trying the following, as there is a configuration option with iThemes which may be the cause:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. If you are using iThemes security can you uncheck [this](https://i.imgur.com/7OyyYyI.png) option from the general settings
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

Please let me know if it works after you perform the above steps

**Comment by annakjaer** [comment]
Site kit doesn't have a settings section on my computer. All I can do is
deactivate and delete under plugins.

**Comment by michelfortin** [comment]
@jamesozzie I followed all the steps in this thread. Nothing is working. I can't even reset site kit because I click and nothing happens.

**Comment by jamesozzie** [comment]
@michelfortin @annakjaer Site Kit support has moved to the [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit). If you want to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) from there we would be happy to assist. Please provide as much information with the support topic in order for us to best support you.
