### ISSUE TITLE
Ensure ad code doesn't run on 404 URLs

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2784]
## Bug Description

As per [one users comments](https://wordpress.org/support/topic/need-to-remove-adsense-ads-code-from-non-content-page-like-404-contact-etc/#post-14008754) in the WordPress support forums AdSense policy dictates that ads should not be displayed on 404 URLs. 

Consider adding a conditional statement to ensure ads don't appear on such URLs. 

More insights on AdSense policy available [here](https://support.google.com/adsense/answer/1346295?hl=en), with the below guidance included:
_Publishers are not permitted to place ads on any non-content based pages like thank you, error, log in, or exit pages._

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense snippet should not be included on any WordPress 404 URLs (`is_404()`), neither for AMP nor for non-AMP.
* This should be unconditional and always take effect, there should be no setting for it.

## Implementation Brief

* Update the `Modules\AdSense\Tag_Guard::can_activate` method to return `FALSE` if `is_404()` returns `TRUE`.

### Test Coverage

* Update the `Tests\Modules\AdSense\Tag_GuardTest` class to make sure that `Tag_Guard::can_activate` method returns correct result for 404 pages.

### Visual Regression Changes

* N/A

## QA Brief

* Activate and connect AdSense module with use snippet setting enabled;
* Go to the homepage or any page on the frontend and make sure that ad code is added to the page;
* Go to a non-existing page (it should result in 404 status) and make sure that ad code is not added.

## Changelog entry

* Ensure that the AdSense snippet is not included on 404 pages in the frontend.

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QA Brief?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- On the homepage the ad code is added to the page - [Screenshot](https://user-images.githubusercontent.com/73545194/113722227-cf727880-9722-11eb-86fe-4689bd0da449.png)

- On a non-existing page (404) the ad code is not added  - [Screenshot](https://user-images.githubusercontent.com/73545194/113722124-b669c780-9722-11eb-8d8b-3d73a6580a2c.png)
