### ISSUE TITLE
Add option to disable ad signals and remarketing

### ISSUE THREAD

**Issue by collimarco** [google/site-kit-wp#2786]
## Feature Description

Please provide an option (e.g. "Disable ads and remarketing") that sets the following options:

```
'allow_google_signals': false,
'allow_ad_personalization_signals': false
```

We don't want to collect data for marketing and ads, so we need an option to opt-out. This is an option that you must provide for privacy. 

Until we don't have that options in Site Kit we'll keep using other custom solutions.

Thanks

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Many thanks for the suggestion. I've added this as a feature request, Note that all features requested are periodically reviewed by our product team, however there is no ETA or guarantee this will make it to future releases.

**Comment by aaemnnosttv** [comment]
Thanks for the request! Please follow #3053 for updates regarding this enhancement.
