### ISSUE TITLE
Improve user input confirmation wording.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#2790]
## Feature Description

The wording for the string after the user completes the user input flow is confusing (as flagged by the French translation team). We should improve this string to make it clearer.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The confirmation message should read: `Now Site Kit will begin suggesting metrics to add to your dashboard that are relevant specifically to you, based on the goals you shared.`

## Implementation Brief

* Change the confirmation string in `assets/js/components/notifications/UserInputSuccessNotification.js`

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* The wording in the confirmation message after completing the User Input flow should be according to the ACs.

## Changelog entry

* Improve wording for the confirmation notification after submitting user input settings.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- The wording in the confirmation message after completing the User Input flow now reads as:

`Now Site Kit will begin suggesting metrics to add to your dashboard that are relevant specifically to you, based on the goals you shared.`

![image](https://user-images.githubusercontent.com/73545194/107756543-50cf0f80-6d5f-11eb-8558-2cf91b5a4af5.png)
