### ISSUE TITLE
Implement tracking events for user input flow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2793]
## Feature Description

There should be internal GA tracking events for opted in users, covering the user input flow.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Note that, while most of these events are expected to happen on user interaction (e.g. click), some of them are based on element visibility (e.g. should trigger as soon as the respective UI is rendered).

* The following Analytics events should be sent when interacting with the new user input flow and related UI:
    * `question_advance`: User clicks "Next" button on a question (event label should be the slug of the current question, e.g. `role`).
    * `question_return`: User clicks "Previous" button on a question (event label should be the slug of the current question, e.g. `helpNeeded`).
    * `summary_view`: The user input preview view appears.
    * `summary_submit`: User clicks "Submit" button in the user input preview view.
    * `summary_edit`: User clicks "Edit" link on one of the questions in the user input preview view (event label should be the slug of the question to edit, e.g. `role`).
    * `question_update`: User clicks "Update" button on a question, after getting there via editing in the user input preview view (event label should be the slug of the question to edit, e.g. `role`).
    * `settings_view`: The user input settings panel appears.
    * `settings_edit`: User clicks "Edit" link on one of the questions in the user input settings panel (event label should be the slug of the question to edit, e.g. `role`).
    * `question_submit`: User clicks "Submit" button on a question, after getting there via editing in the user input settings panel (event label should be the slug of the question to edit, e.g. `role`).
    * `success_notification_view`: The "Congrats" user input notification appears.
    * `success_notification_dismiss`: User clicks "OK got it" on the "Congrats" user input notification.
    * `prompt_notification_view`: The user input prompt notification appears.
    * `prompt_notification_start`: User clicks "Let's go" on the user input prompt notification.
    * `prompt_notification_dismiss`: User clicks "Remind me later" on the user input prompt notification.
* For all of these events, the event category should be `user_input`.

## Implementation Brief
* The `trackEvent` function used in the files below can be imported from `/assets/js/util/`.
* For all the events tracked below, the event category should be `user_input`
* Using `/assets/js/components/user-input/UserInputQuestionnaire.js`,
	* Update the `next` function to call the `trackEvent` function with the following parameters:
		* Action: `question_advance`
		* Label: the slug of the current question which can be obtained by calling: `steps[ activeSlugIndex ]`
	* Update the `back` function to call the `trackEvent` function with the following parameters:
		* Action: `question_return`
		* Label: the slug of the current question which can be obtained by calling: `steps[ activeSlugIndex ]`
	* Update the `goToPreview` function to call the `trackEvent` function with the following parameters:
		* Action: `question_update`
		* Label: the slug of the current question which can be obtained via: `steps[ activeSlugIndex ]`
* Using `/assets/js/components/user-input/UserInputPreview.js`,
	* Use the `useEffect` hook to call the `trackEvent` function with the following parameters:
		* Action: `summary_view`
	* Update calls to the `goTo` function to a new function, `handleGoTo` which should call the `goTo` function with the existing parameters and the `trackEvent` function with the following parameters:
		* Action: `settings_edit` if the `single` URL param value is `settings`, or `summary_edit` if `single` URL param value is `user-input`
		* Label: the slug of the current question which can be passed directly to the `handleGoTo` function.
	* Update the `onClick` event of the submit button to call a new function, `handleSubmit` which will call the `submitChanges` prop and `trackEvent` function with the following parameters:
		* Action: `summary_submit` if the `single` URL param value is `settings`, or `question_submit` if `single` URL param value is `user-input`.
		* Label: the slug of the current question which can be obtained by accessing the `question` URL param.
	* We could have tracked the submit event in the `submitChanges` function of the `UserInputQuestionnaire` component but the function can be used elsewhere than on the preview screen.
* Using `/assets/js/components/notifications/UserInputSuccessNotification.js`,
	* Use the `useEffect` hook to call the `trackEvent` function with the following parameters:
		* Action: `success_notification_view`
	* Add a new callback `onDismiss` to the `Notification` component which calls the `trackEvent` function with the following parameters:
		* Action: `success_notification_dismiss`
* Using `/assets/js/components/notifications/UserInputSettings.js`,
	* Use the `useEffect` hook to call the `trackEvent` function with the following parameters:
		* Action: `prompt_notification_view`
	* Add a new callback `onCTAClick` to the `Notification` component which calls the `trackEvent` function with the following parameters:
		* Action: `prompt_notification_start`
	* Add a new callback `onDismiss` to the `Notification` component which calls the `trackEvent` function with the following parameters:
		* Action: `prompt_notification_dismiss`

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief
* Enable `Tracking` in `Settings`
* ![image](https://user-images.githubusercontent.com/31818/110450581-c6b76400-80dc-11eb-80d3-cfc68eb8a372.png)
* Install the `Google Analytics Debugger` Chrome extension: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna
* Open the browser console and make sure the requests are being fired with the appropriate parameters. Check the AC for the parameters.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB looks good for the most part, but I think we should always call `trackEvent` inside a `useEffect` hook rather than inside functions that change the step/slug/activeIndex like `next`, `back`, `goToPreview`, or `goTo`. So instead of calling `trackEvent` when `next` or `back` are called, we should call `trackEvent` inside a `useEffect` hook that fires when `activeSlug` changes.

That way, if there are multiple ways to change the slug in the future we don't have to add more `trackEvent` calls; we can track the event based on the state value changing. This will also help us once #2514 is implemented, because we can change all of the `useEffect` dependencies to the `activeSlug` based on the route instead of the `activeSlug` based on internal state.

**Comment by asvinb** [comment]
@tofumatt I thought of that as well, i.e using the `useEffect` hook that fires when `activeSlug` changes. However how we would know whether the user clicked on the `next` or `back` button or even clicking on the `Edit` link on the preview screen to edit the question, since in all of those cases, the hook will be fired.

**Comment by tofumatt** [comment]
Ah, shoot, right. Thanks for the context on that one! 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
@asvinb  I'm looking at the AC’s and the 1st one, says `question_advance: User clicks "Next" button on a question (event label should be the slug of the current question, e.g. role)` Are we sure it should be the current question slug appearing in console?  When I click “Next” button, I see the slug for the previous question. i.e. I am on question 2 which is post frequency.  I click the next button, and what appears in the console is `postFrequency` not `goals`

The same applies with the back button.

**Comment by felixarntz** [comment]
@wpdarren That is the expected behavior, the tracking events should send the slug of the question you're currently on. I guess the events are more of an "advance from" than an "advance to".

**Comment by wpdarren** [comment]
@felixarntz I want to clarify to make sure I’m not misunderstanding:  I am on Question 1 on the user input screen: I complete the question and click “Next” button,  I go to question 2.  When I look in the log for the `eventLabel`, I see the slug for `role` which is the **previous** question. The current question is no.2 which is `post frequency`  In the AC it says the` event label should be the slug of the current question` so I am not expecting to see `role` but it should be `postfrequency`. 

Is the AC wrong but what I see correct? (edited)

**Comment by asvinb** [comment]
@wpdarren This is correct. If you're on the first question, for e.g role, you click on the "Next" button, you will see the slug "**role**" being sent, while at the same time, you switch to the next question, which is "**postFrequency**". So the current question is the one before the next button is clicked.

**Comment by wpdarren** [comment]
### QA Update: Engineer to confirm ⚠️ 

- I have gone through the ACs and made sure that all of the actions are included in the log file.  All looks good but 
@asvinb my only observation is when you are on the admin settings screen `wp-admin/admin.php?page=googlesitekit-settings#admin` and you see all of the questions and answers, this appears in the log as `settings_view` but when I go to edit one of the questions, and you go back to the user input screen, changed the answer and update, nothing is logged, other than `settings_view` when you are redirected back to the admin settings screen.  Should it be?

**Comment by asvinb** [comment]
@wpdarren As per the AC, you should see the following:

- settings_edit: User clicks "Edit" link on one of the questions in the user input settings panel (event label should be the slug of the question to edit, e.g. role).
- question_submit: User clicks "Submit" button on a question, after getting there via editing in the user input settings panel (event label should be the slug of the question to edit, e.g. role).

So on top of `settings_view`, you should also see `settings_edit` when clicking on the "Edit" link and then `question_submit` when you click on the "Submit" button on a question.

**Comment by wpdarren** [comment]
@asvinb yes, you're right. I do see those, but the log file changes very quickly when Site Kit redirects to the admin settings page, so all you see at the end is the results `settings_view` details.  I'll mark this as passed. 

### QA Update: Pass ✅ 

I have gone through the ACs and made sure that all of the actions are included in the log file. All looks good
