### ISSUE TITLE
Php 8.0.0 notice

### ISSUE THREAD

**Issue by oguilleux** [google/site-kit-wp#2797]
Hello,

This notice appears with php 8 :

Deprecated: uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /wp-content/plugins/google-site-kit/includes/Core/Modules/Modules.php on line 267

Good luck

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no warnings about incorrect `uasort` usage in PHP 8.

## Implementation Brief

* Merge #2804.

### Test Coverage

* N/A (will be covered via #2724)

### Visual Regression Changes

* N/A

## QA Brief

* Use the plugin on an environment with PHP 8, with `WP_DEBUG` and `WP_DEBUG_DISPLAY` enabled.
* There should be no PHP notice about deprecated `uasort()` usage (see issue description).

## Changelog entry

* Fix PHP 8 notice for deprecated `uasort()` usage.

**Comment by adamsilverstein** [comment]
Hi @oguilleux thanks for opening this issue.

We had discussed this issue although I couldn't find an open issue or PR addressing it. I have a proposed fix in https://github.com/google/site-kit-wp/pull/2804 which fixes the issue in my local testing.

**Comment by adamsilverstein** [comment]
cc: @felixarntz I know we discussed this issue, are we already tracking elsewhere?  I found https://github.com/google/site-kit-wp/issues/2724 however this is more about adding PHP 8 to the test runs.

**Comment by felixarntz** [comment]
@adamsilverstein I assume this would be exposed via running tests on PHP 8.0, and that issue has the goal of addressing all such problems. However, since you've already opened a PR for this specific one, let's do that one individually.

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

- With a local site set up on PHP 8.0 and `WP_DEBUG` and `WP_DEBUG_DISPLAY` set to `True`. 
- There is no PHP notice about deprecated `uasort()` usage.

This is a screenshot of the error on 1.25.0 but it does not appear when changing to the develop branch. 

![image](https://user-images.githubusercontent.com/73545194/107936795-06979980-6fbe-11eb-9337-1f3c01f8dd88.png)
