### ISSUE TITLE
Block external WP HTTP requests in E2E

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2798]
## Feature Description

In our PHPUnit tests, we block all out going HTTP requests to prevent external factors from influencing test results.

We should do the same for E2E, the difference is that we can do better to completely disconnect the server side from making external connections using Docker.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No external server-side HTTP requests should be allowed in E2E tests via the WP HTTP API

## Implementation Brief

* Update `bin/local-env/docker-compose.yml` to set additional configuration via the `WORDPRESS_CONFIG_EXTRA` environment variable already used in the Docker service definition
	* [Set the `WP_HTTP_BLOCK_EXTERNAL` constant to `true`](https://github.com/google/site-kit-wp/pull/2799/files#diff-7f3de7c3ccd5e7d9decf2a88b626862a7edcbba443f523cb45b2a816628013fbR14), but only for non-WP-CLI commands (since they share the same config) – this is necessary to allow for the E2E provisioning scripts to work which largely use WP CLI to install/update WP, plugins, and themes which need access to the external network

### Test Coverage

* No change in coverage, may require updates to E2E if tests fail due to failing HTTP requests 

### Visual Regression Changes

* N/A

## QA Brief

* Remove the existing docker volume for the local environment using `docker volume rm googlesitekit-e2e_wordpress_data`
* Start the local environment running `npm run env:start` command
* Visit `http://localhost:9002/wp-admin/` and log in using `admin`/`password` credentials
* Verify that the WordPress site works
* Now create a new file (name doens't matter) in the `tests/e2e/mu-plugins` folder and put the following content into it:
   ```php
   <?php

   add_action(
   	'init',
   	function() {
   		$resp = wp_remote_get( 'https://api.github.com/repos/google/site-kit-wp' );
   		if ( ! is_wp_error( $resp ) ) {
   			wp_die( "WP_HTTP_BLOCK_EXTERNAL doesn't work!" );
   		}
   	}
   );
   ```
* Go back to the browser and refresh the page. Verify that you don't see the error screen with the message `WP_HTTP_BLOCK_EXTERNAL doesn't work!`.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@aaemnnosttv the `WP_HTTP_BLOCK_EXTERNAL` constant does block all external requests, why do you think we need a proxy server? I think if adding this constant is sufficient, then we shouldn't change the docker-compose configuration, should we?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov correct, but that only applies to WP. The idea here is to prevent the Guzzle-based Google client (or anything else) from making external connections as well.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv ok, but in this case, if we block all external requests then all requests sent by Guzzle-based client will fail with timeout errors, right? I am afraid it can cause additional slowness, can't it? :thinking:

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I don't think it will timeout since it should fail to connect right away, but that's a valid concern. I believe I tried something else first which did have the timeout problem but I don't think this one does. I can check again though.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov – it seems that this does time out like you mentioned which would be a no go.

I started experimenting with adding `extra_hosts` to the `wordpress` service for the various APIs which didn't work (I think it failed because of HTTPS) but could be nice as we could control the responses.

```yml
    extra_hosts:
      - "sitekit.withgoogle.com:127.0.0.1"
      - "www.googleapis.com:127.0.0.1"
      - "searchconsole.googleapis.com:127.0.0.1"
```

These could live on another service in the environment as well as long as it was connected to the internal network. If this can work then the timeouts should be acceptable as they would only happen in cases we hadn't accounted for yet.

Will come back to this again but we should probably remove the Next Up here for now (cc: @felixarntz @eclarke1).

**Comment by aaemnnosttv** [comment]
Moving to _Stalled_ for now; will revisit later.

**Comment by aaemnnosttv** [comment]
@felixarntz the remaining part has been opened in #3957 👍

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QAB?

**Comment by eugene-manuilov** [comment]
Added.

**Comment by ivankruchkoff** [comment]
QA: ✅

Logging the error message gives:
```
object(WP_Error)#1167 (3) {
  ["errors"]=>
  array(1) {
    ["http_request_not_executed"]=>
    array(1) {
      [0]=>
      string(39) "User has blocked requests through HTTP."
    }
  }
  ["error_data"]=>
  array(0) {
  }
  ["additional_data":protected]=>
  array(0) {
  }
}
```
