### ISSUE TITLE
Regression in legacy all traffic widget dimension tabs styling changed

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2801]
## Bug Description

The styling of the dimension tabs changed from the previous release 1.25.0

**Before (matches design)**
![image](https://user-images.githubusercontent.com/1621608/107764176-6da41c80-6d38-11eb-9aa3-af5f16ee3f8a.png)

**After** (current RC)
![image](https://user-images.githubusercontent.com/1621608/107764207-77c61b00-6d38-11eb-92dd-1066ef1eaeb4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The styling of the legacy all traffic widget (specifically the dimension tabs) should remain consistent with the previous release

## Implementation Brief

* Update the styles which are scoped by the widget `slug` to include the same top-level selector using the legacy slug, as well as the current "modern" one
* Merge https://github.com/google/site-kit-wp/pull/2802

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Load the plugin using v1.25.0 of the plugin with Analytics connected
* Observe SK dashboard
* Upgrade to the release candidate
* Check that the all traffic widget dimension tabs are centered over the pie chart and in title case (not all caps)

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

The all traffic widget dimension tabs are centered over the pie chart and in title case.

![image](https://user-images.githubusercontent.com/73545194/107938561-8a528580-6fc0-11eb-8434-8cb139e9d5c9.png)
