### ISSUE TITLE
Analytics Module: Multi domain support / polylang

### ISSUE THREAD

**Issue by TompieD** [google/site-kit-wp#281]
i have found that the plugin doesn't know the difference between some pages with the same permalink on another domain.
i'm using polylang plugin for multi lingual site and for example the home page on the english domain and the dutch domain are the same metrics while infact it has other clicks and impressions.
is google planning for a domain check where to get the metrics from?

**Comment by jamesozzie** [comment]
@TompieD Can you share your URL or even permalink structure using polylang and I can look into this further?

**Comment by TompieD** [comment]
![permalink structure](https://user-images.githubusercontent.com/485158/61410533-c7d2c680-a8e4-11e9-92f9-ce4b60710ed8.png)
![polylang settings](https://user-images.githubusercontent.com/485158/61410534-c7d2c680-a8e4-11e9-85cf-3dd598b8c709.png)
![stats dog be](https://user-images.githubusercontent.com/485158/61410535-c7d2c680-a8e4-11e9-961b-574a0c53fc52.png)
![stats wr be](https://user-images.githubusercontent.com/485158/61410537-c7d2c680-a8e4-11e9-8839-159c9c96bcbe.png)
![wp config](https://user-images.githubusercontent.com/485158/61410735-25671300-a8e5-11e9-8bc0-eb35e408f715.png)
I have taken some screenshots, sorry that the WordPress is in dutch. If you need any more details, be free to ask. I also included a part of wp-config.php what you maybe could use. 
All dns records refer to the same hosting server. In that hosting server i have made several vhosts like in the polylang config.

**Comment by jamesozzie** [comment]
Closing this as we have #325 open as a feature request. Adding domain URL support should resolve this

**Comment by gabrielstuff** [comment]
Hello, As https://github.com/google/site-kit-wp/issues/325 is now closed, can we assume that it is working now ? 
I didn't find any documentation about setting up multi-domain tracking.

Thanks
