### ISSUE TITLE
Allow proxy-side user input UI to show up when feature is manually enabled on plugin side

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2814]
## Bug Description

#2755 fixed the integration between the remote-controlled `userInput` feature flag and the proxy, which needs to determine itself during setup whether the feature is enabled for the given site. This works for the common use-case where features are always disabled by default and may only be enabled by remote control via the proxy.

However, #2759 moves to a more customizable approach where features can be enabled in any other way and no longer rely on a development build to be enabled. The Site Kit tester plugin exposes a UI to modify the enabled flags via checkboxes. If now the `userInput` checkbox is enabled there, the proxy won't know that. It will currently still act as if the site didn't know whether the feature is enabled, making an internal request to check for the feature flag. If then the proxy decides the feature is not active for the site, it wouldn't show the UI for it, even though the site has effectively overruled the proxy, deciding the feature _must_ always be enabled. Fixing this is already relevant now, since the proxy will already check whether `userInput` is enabled (right now `false` for every site).

Let's address this by introducing an additional (temporary) proxy support flag: While the `user_input_flow` support flag indicates that the current version technically supports the user input flow, we should introduce a `user_input_flow_feature` support flag that is only set if the feature is already known to be enabled before setup (e.g. via tester plugin).

This will be temporary and can be removed once the user input feature is fully rolled out so that every supporting Site Kit version uses it anyway.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the `userInput` feature flag is enabled (before setup), a `user_input_flow_feature` support flag should be added to `OAuth_Client::get_proxy_setup_supports()`.

## Implementation Brief

* Merge #2815.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

Note this is currently only testable when using the staging version of the proxy.

**Using a production build**
* When enabling the `userInput` feature flag checkbox in the Site Kit tester plugin (version >= 1.4.0), the "Tell Site Kit more about your site" step should appear in the proxy UI during setup if you haven't responded to the questions before.
* When the `userInput` feature flag checkbox is disabled, the step should never show up.

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
@aaemnnosttv I have installed the tester plugin (1.4.0) and when I enter `userInput` in the feature flag checkbox, and save settings, the default entry of `Array` re-appears. I have tried this with all the options in the `Force enabled feature flags` field. 
Any ideas what could be causing this? 

![image](https://user-images.githubusercontent.com/73545194/108217998-2fab5c00-716f-11eb-9f2b-d446952ff8a0.png)

**Comment by wpdarren** [comment]
@aaemnnosttv I have activated the plugin fix,and the `"Tell Site Kit more about your site"` step is appearing with the `userInput ` enabled or disabled. I'm wondering if it is because of this `Note this is currently only testable when using the staging version of the proxy.` Please could you clarify what this means? Do I have to use the Dev plugin?

**Comment by felixarntz** [comment]
@wpdarren There is another problem that causes the UI in the tester plugin to not work as expected, see https://10up.slack.com/archives/CFFRMC5DE/p1613563727026500?thread_ts=1613531414.023300&cid=CFFRMC5DE @aaemnnosttv will open a quick PR to get that into `develop`, afterwards this should be ready to be re-QAd.

**Comment by felixarntz** [comment]
@wpdarren #2820 has been merged now, so this should be good for re-testing with the latest `develop` branch.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- When enabling the userInput feature flag checkbox in the Site Kit tester plugin (version >= 1.4.0), the "Tell Site Kit more about your site" step appears in the proxy UI.
- When the userInput feature flag checkbox is disabled, the "Tell Site Kit more about your site" step does not appear.
