### ISSUE TITLE
Analytics data is not available after the Site Kit update 1.26.0

### ISSUE THREAD

**Issue by vtlpsk** [google/site-kit-wp#2822]
## Bug Description

Google Analytics not working properly for the whole day after the latest Site Kit update (1.26.0).

Site Kit shows me this error:
`Quota Error: Number of recent failed reporting API requests is too high, please implement exponential back off.`

Google Analytics doesn’t show any data. Just blank pages.
And this error:
```
Resource is not available. Please try again later.
One or more of the services on which we depend is unavailable. Please try again later after the service has had a chance to recover.
Error ID: b6700a61-aef5-4580-97f3-e10e016ff7b1
```
## Screenshots
![Screenshot 2021-02-18 at 02 00 45](https://user-images.githubusercontent.com/4630500/108284203-76a84a00-718d-11eb-897a-dc9d191aac58.png)
![Screenshot 2021-02-18 at 02 01 28](https://user-images.githubusercontent.com/4630500/108284207-77d97700-718d-11eb-9c94-772d12a887fc.png)

What’s going on? Any idea how to fix this?

**Comment by jamesozzie** [comment]
@vtlpsk Thanks for opening a GitHub issue and providing useful insights. Can you share whether the issue still exists, and if so can you attempt disconnecting the Analytics module and connecting once more? I suspect this may have been a service level quote message.

**Comment by vtlpsk** [comment]
@jamesozzie 
Yes, the issue still exists. It's a strange coincidence that this started happened after updating the Site Kit plugin.
Reconnecting doesn't change anything:
<img width="529" alt="Screenshot 2021-02-18 at 13 04 51" src="https://user-images.githubusercontent.com/4630500/108350138-8440ec80-71ec-11eb-81f0-eca715017f97.png">

Analytics still doesn't show any data and I keep getting an error:
<img width="627" alt="Screenshot 2021-02-18 at 13 26 01" src="https://user-images.githubusercontent.com/4630500/108350459-e7328380-71ec-11eb-8ef3-08e4e5339b1f.png">

It looks like Google Analytics banned me for exceeding the limits of calls to API. I can't imagine how I could exceed the limits. The only thing I used was the Site Kit plugin.

**Comment by jamesozzie** [comment]
Thanks for sharing. I've been unable to recreate this same experience but I'll perform some additional tests. 

In the meantime can you share whether you can see any data from your account when using the [Google Analytics query explorer](https://ga-dev-tools.appspot.com/query-explorer/)? Please check on both the account and property you've used within Site Kit and another Analytics property.

**Comment by vtlpsk** [comment]
@jamesozzie 
Unfortunately, I have only one account and property.
I get a 500 error after I Run Query.

<img width="491" alt="Screenshot 2021-02-18 at 14 13 31" src="https://user-images.githubusercontent.com/4630500/108356184-7c854600-71f4-11eb-8c32-04df66d98bbf.png">

**Comment by dbmatre** [comment]
This is worldwide issue faced by many analytics user https://twitter.com/googleanalytics/status/1362240056111427584

**Comment by vtlpsk** [comment]
It seems it just started working again.
Thank you @jamesozzie @dbmatre.

**Comment by jamesozzie** [comment]
@vtlpsk Thanks for bringing this to our attention, this seemed to impact some users only. Likewise @dbmatre, thanks for sharing
