### ISSUE TITLE
Add enabled features to anonymous usage tracking

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2827]
## Feature Description

With enabled features starting to vary across installs, it's important that we include this in our event tracking to be able to segment by feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `trackEvent` should be updated to include a list of all enabled features as a custom dimension for all tracked events

## Implementation Brief

* Update `trackEvent` in `assets/js/util/tracking/createTrackEvent.js` to include a new `dimension5` key in its event data, with a value of `enabledFeatures` as a comma-separated list

### Test Coverage

* Jest tests for `trackEvent` should be updated to ensure the new dimension is included and formatted properly

### Visual Regression Changes

* N/A

## QA Brief

* Using the latest version of the tester plugin enable more than one feature
* Install the Tag Assistant Chrome extension
* Enabling tracking in the plugin triggers an event that can be viewed in the Tag Assistant
* Check custom metrics in Tag Assistant for Dimension 5 being with a list of the enabled features

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
@Hazlitte @aaemnnosttv first time using Tag assistant extension, but I enabled it for tracking. 

I am unsure what this means:

`Check custom metrics in Tag Assistant for Dimension 5 being with a list of the enabled features`

Please could you clarify the steps or, provide a screenshot of what I should be seeing? 

![image](https://user-images.githubusercontent.com/73545194/109980780-3aebb380-7d3b-11eb-8903-728a5cde5571.png)

**Comment by Hazlitte** [comment]
@wpdarren In the Tag Assistant select the Google Analytics tag -> Events ->Custom Metrics.  Then you should see Dimension 5.
![Screenshot 2021-03-04 at 17 06 56](https://user-images.githubusercontent.com/5174233/110001625-7458fa80-7d0c-11eb-83f3-f392f7398d3d.png)

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Verified:  In dimension 5 I could see the two features that were selected in the tester plugin. 

![image](https://user-images.githubusercontent.com/73545194/110121717-b2801800-7df9-11eb-9a4e-c6977e8900c0.png)
