### ISSUE TITLE
After preview, back/next can change to update

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2829]
## Bug Description

After preview screen has shown, and we choose to edit one item, next/back buttons change to update

## Steps to reproduce

1. Open /wp-admin/admin.php?page=googlesitekit-user-input
2. Go through flow to 5th question.
3. Press preview.
4. Press back, and notice that on 5/5 Back/Preview buttons show.
5. Now on preview edit any question and update.
6. Now press back, and notice that on 5/5 only an Update button is shown.

## Screenshots

See screen recording:

https://user-images.githubusercontent.com/373931/108405788-61a3d900-71d6-11eb-8876-3fd3359c8188.mp4

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the user input preview step, the back button should be removed so that there is only a "_Submit_" button.
* The only way to get back to a previous question should then be to go through the "_Edit_" link on the respective question. The question should in that case only have a single "_Update_" button.
* In other words: As soon as the user has reached the preview stage for user input, they should never be able to navigate through questions via back/next again, it should always be editing one question at a time.
* The current notion of "_Update_" vs "_Submit_" on each question should be maintained:
    * If the user is in the preview of the user input flow, editing an answer should result in the button on the question to say "_Update_". Clicking it should update the answer locally in the client; only submitting in the preview should actually submit the changed answer to the WordPress / Google API.
    * If the user is in the user input section in "Settings > Admin Settings", editing an answer should result in the button on the question to say "_Submit_". In this scenario, clicking the button should immediately submit the updated response to the WordPress / Google API, since there is no extra layer here to confirm. In this scenario, you are no longer previewing "locally", you are editing what you've already submitted before.

## Implementation Brief

* Remove the 'back' button and `back` prop from `assets/js/components/user-input/UserInputPreview.js`
* Remove the `back` prop that is passed into the `UserInputPreview` component from `assets/js/components/user-input/UserInputQuestionnaire.js`

### Test Coverage

* No new tests; existing ones should pass

### Visual Regression Changes

* When going back to a question from the preview, the buttons should look as follows:
  * A single 'update' button if going through the flow for the first time (i.e. not via 'settings')
  * A single 'submit' button if going via 'settings'
* There should be no 'back' button on the preview stage.

## QA Brief

1. With a fresh install, go through the user input flow until you reach the preview stage.
  * There should be no 'back' button on the preview stage, just a 'submit'. The only way to go back and edit a question is by clicking 'edit' on the question.
* After hitting 'edit' and going back to a question, there should be a single 'update' button. Pressing this:
  * will take you back to the preview screen, where your changes to that question should be reflected
  * should NOT make a network request to the API
* When the 'submit' button on the preview screen is clicked, a network request to the API is made to persist your answers on the proxy.
2. Now go to "Settings > Admin Settings" to see the preview screen again, which should reflect your saved answers. 
  * There should be no button. 
  * To edit a question, you must click 'edit' on the given question
* After hitting 'edit' and going back to a question, there should be a single 'submit' button. Pressing this:
  * SHOULD make a network request to the API to persist your answers on the proxy.
  * will take you back to the preview screen, where your changes to that question should be reflected

## Changelog entry

* Change to preview / next button behaviour in User Input flow

**Comment by felixarntz** [comment]
IB ✅

**Comment by Hazlitte** [comment]
### QA  ✅
Works exactly as described in the QA Brief.
