### ISSUE TITLE
OAuth credentials

### ISSUE THREAD

**Issue by VinsMach** [google/site-kit-wp#283]
the return after OAuth credentials going in home. I can't conclude the installation

**Comment by jamesozzie** [comment]
@VinsMach Do you mind trying the following, this same issue was reported previously, #117  

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. If you are using iThemes security can you uncheck [this](https://i.imgur.com/7OyyYyI.png) option from the general settings
3. Temporarily deactivate your other active WordPress plugins
4. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

Please let me know if it works after you perform the above steps.

**Comment by jamesozzie** [comment]
Closing this ticket with no response from submitter
