### ISSUE TITLE
Contributor Documentation

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2830]
Epic for adding comprehensive product documentation for internal and external contributors

[Initial proposal](https://docs.google.com/document/d/1uiLfbH6EUsOBryjHd3HdhRnwjNM6iw4-ug5Z183mduw/edit)

[Contributor documentation priority voting](https://docs.google.com/spreadsheets/d/1WybRWRnRQOERNd-9uOfJyrKREiRdJvFfZyxdl04lHwU/edit?resourcekey=0-im1KpyJEE7v0vmQt2ZoKug#gid=0)

**Comment by bethanylang** [comment]
Closing as we're not actively working on this right now.
