### ISSUE TITLE
User Input preview display quirks

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2837]
## Bug Description

The preview for user input has a few quirks which were recently discovered which should be addressed before launch.

1. Long freeform answers can overflow horizontally  
![image](https://user-images.githubusercontent.com/1621608/108726706-677c2000-7530-11eb-8a03-2beab2b10909.png)
2. On mobile, the preview pill/bubble radius looks a odd/inconsistent with multi-line answers
![image](https://user-images.githubusercontent.com/1621608/108726907-9eeacc80-7530-11eb-9504-f242d926f5b5.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The answer bubbles in the User Input flow preview should have a consistent border radius, no matter the number of lines, width, height etc.
* Long content in a custom answer should not be able to mess up the layout; in other words, the bubbles should should always be limited to the maximum available width, and the inner content should wrap as possible and in no case overflow.
* Custom answers should be trimmed (i.e. spaces at the beginning and end should be cut off).
* Any answers provided under "Other" should be prefixed with "Other:" in their bubble, and if nothing is entered they should just say "Other". In other words, the bubble content should be like "Other: something custom I entered" or "Other".

## Implementation Brief
* Using `/assets/sass/components/user-input/googlesitekit-user-input-preview.scss`,
	* Update the `.googlesitekit-user-input__preview-answer` class to:
		* Add `word-break: break-word;` to prevent characters from overflowing.
		* Set `border-radius` to `30px` on small screens only. The border radius should be `100px` for tablet and above.
* Using `/assets/js/components/user-input/UserInputPreviewGroup.js`,
	* Create a new constant, `isOther`, which checks whether `values` can be found in `options` (example can be found in `/assets/js/components/user-input/UserInputSelectOptions.js`) and the question number is not `5`.
	* Before rendering the `value`, check if `isOther` is `true`. If this is the case, display the `Other:` text before the `value`
* Using `/assets/js/googlesitekit/datastore/user/user-input-settings.js`,
	* Update the `saveUserInputSettings` action to trim values within the `settingssettings[ key ]?.values` variable.

### Test Coverage
* Add an additional test for the `saveUserInputSettings` action which checks whether user input values are saved without spaces at the beginning and at the end.

### Visual Regression Changes
* N/A

## QA Brief

* Go to the user input settings flow and select answers providing long custom answers in `other` fields;
* Make sure your answers look correctly on the preview page and the acceptance criteria are met.

## Changelog entry

* Fix various visual glitches in the user input flow summary view and trim free text content entered for any "Other" choice.

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
> Any answers provided under "Other" should be prefixed with "Other:" in their bubble, and if nothing is entered they should just say "Other". In other words, the bubble content should be like "Other: something custom I entered" or "Other".

@felixarntz I believe you said a value for Other should always be required. This issue isn't about this validation but the ACs make it sound like this is okay. Assigned to you in MR to confirm.

**Comment by felixarntz** [comment]
@aaemnnosttv Indeed, the ACs here were written before we clarified that. It should always be required to enter something for "Other".

**Comment by felixarntz** [comment]
@eugene-manuilov Can you add a QA Brief here please?

**Comment by wpdarren** [comment]
### QA Update: To clarify with Engineer ⚠️ 

@eugene-manuilov an observation, when no text is entered into the 'Other' field, the preview, shows it as `Other:` but looking at the AC, it should be `Other` with no colon. 

![image](https://user-images.githubusercontent.com/73545194/110632653-d8832f00-81e2-11eb-9823-51c47f9af34c.png)

**Verified:**

- The answer bubbles in the User Input flow preview has a consistent border radius.
- Long content in a custom answer does not be able to mess up the layout.
- Custom answers are trimmed (i.e. spaces at the beginning and end should be cut off).
- Any answers provided under "Other" are prefixed with "Other:" in their bubble

**Comment by eugene-manuilov** [comment]
@wpdarren I think without colon it will be confusing because it will look like a part of the entered text. So, I think we can consider the version with colon as expected behavior. cc @felixarntz

**Comment by wpdarren** [comment]
@eugene-manuilov thats fine, just didn't want to assume anything. 

### QA Update: Pass ✅ 

**Verified:**

- The answer bubbles in the User Input flow preview has a consistent border radius.
- Long content in a custom answer does not be able to mess up the layout.
- Custom answers are trimmed (i.e. spaces at the beginning and end should be cut off).
- Any answers provided under "Other" are prefixed with "Other:" in their bubble
- If the 'Other' is blank then "Other:" appears in the bubble. 

![image](https://user-images.githubusercontent.com/73545194/110632653-d8832f00-81e2-11eb-9823-51c47f9af34c.png)
