### ISSUE TITLE
Update modules fixture

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2838]
## Bug Description

As [recently discovered](https://github.com/google/site-kit-wp/pull/2730#discussion_r579096938), our [modules list fixture](https://github.com/google/site-kit-wp/blob/1b262188b56189aef458129f0f59a4eba4a70b9c/assets/js/googlesitekit/modules/datastore/fixtures.json) does not accurately represent a default state. It's also a bit inconsistent with most of our other fixtures in a few ways. We should update it for consistency.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The modules fixture should be consistent with the response from the `GET:core/modules/data/list` datapoint on a clean install (or freshly reset)
* Any reference URL in the fixture should use `http://example.com`
* The name and location of the fixture should be moved to `assets/js/googlesitekit/modules/datastore/__fixtures__/list.json`

## Implementation Brief

* Reset Site Kit and go to splash page
* Run `copy(await googlesitekit.api.get('core','modules','list'))` in browser console
* Update contents of fixture with copied data
* Move fixture to `assets/js/googlesitekit/modules/datastore/__fixtures__/list.json`
* Update broken tests and references to use new location
* Update any references which assumed Analytics was active/connected rather than requiring it by using `withActive` or `provideModules`
* Ensure Storybook is not broken

### Test Coverage

* No change

### Visual Regression Changes

* N/A

## QA Brief

* Make sure that module fixtures are up-to-date;
* Make sure that the file with module fixtures is moved to the `__fixtures__` folder;
* Make sure that js tests pass and storybook is not broken.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@eugene-manuilov Can you please add a QA Brief?

**Comment by eugene-manuilov** [comment]
QA Brief is added.

**Comment by tofumatt** [comment]
QA ✅
