### ISSUE TITLE
Increase in visitors when lighthouse is enabled

### ISSUE THREAD

**Issue by andizer** [google/site-kit-wp#284]
## Bug Description
Since I activated the sitekit plugin with almost all options enabled (analytics, search console, adsense and lighthouse) 
I discovered a large increase in the amount of unique visitors with a bouncerate of 100% is happening. It looks like the lighthouse check is doing a short request and it is caught up by google analytics. 
The amount of extra visitors is around the 50 and for me it is a big surprise to see such increase in visitors because I have a small blog.

The only thing that I didn't set up was the implementation of the analytics code. This code is added by myself.

## Steps to reproduce

1. Set up lighthouse on a site with analytics enabled. 
2. An increase of visitors should occur.

## Additional Context

 - PHP Version: 7.3
 - Plugin Version [e.g. 22] Latest beta

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@andizer If you create a view for the property you would like to measure there is an option to exclude known bots and spiders. You will find the option from within a view on your property ID [here](https://i.imgur.com/ooenBW1.png). 

You can also find more information about creating custom filters [here](https://support.google.com/analytics/topic/1034830). 

For additional information on this issue you can see this [Github issue](https://github.com/GoogleChrome/lighthouse/issues/8144) on the Lighthouse repository.

**Comment by gmmedia** [comment]
Same issue here.

**Comment by jamesozzie** [comment]
Closing this as there is an [option](https://i.imgur.com/ooenBW1.png) from within Analytics to create views, which provide the option to exclude visitor numbers "from known bots".
