### ISSUE TITLE
You do not have permission to authenticate with Site Kit

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2840]
There have been reports of users encountering the below dashboard error, despite having full WordPress administrator access:
`"You do not have permission to authenticate with Site Kit"`

Check for all causes of this issue and improve messaging where possible within Site Kit. 

Instances:
- https://wordpress.org/support/topic/you-dont-have-permissions-to-authenticate-with-site-kit-2/ - **_Resolved by changing protocol_**
- https://wordpress.org/support/topic/error-unable-to-authenticate-site-kit/ - **_Resolved by temporarily disabling caching & security plugins_**
- https://wordpress.org/support/topic/you-dont-have-permissions-to-authenticate-with-site-kit/ - **_Resolved, the problem being a user didn't grant all permissions during the Analytics setup process only_**
- https://wordpress.org/support/topic/you-dont-have-permissions-to-authenticate-with-site-kit-6/ - **_No response from user_**
- https://wordpress.org/support/topic/no-permission-to-authenticate/page/2/ - _**Resolved - Site migration issue**_

Unable to reproduce this exact message so far support side. Details on internal testing performed so far [available here](https://app.asana.com/0/1185360131189553/1199938125092438/f). These tests include the following:
- Setting up Site Kit from a https admin panel URL on a site with both http and https available (no redirection in place and URLs defined in WP as non secure). 
- Switching defined URLs to secure and setting up SK as non secure 

Further tests ongoing. 

## Additional Context

 - There have been reports of this occurring from previous various of Site Kit (since 1.15.0
 - This notice appears despite users confirming they are using full WP administrator roles

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Update on this issue. After various tests I've been able to reproduce this by following the steps below ([Internal task](https://app.asana.com/0/1185360131189553/1199938125092438/f)):

1. Setup SK and Analytics on a site that is http (both defined URLs http://www.site.com, including the www)
2. Activate https and setup a redirect to ensure secure traffic (at hosting level, no plugins). No preferred www prefix was defined.
3. Change the defined URLs within SK to https://mysite.com (without the www), both the prefix and protocol were modified
4. Login to site once requested
5. The notice appears that URL has been modified 
6. Follow OAuth setup flow
7. After clicking on my email I get redirected to a screen with the notice 

![image](https://user-images.githubusercontent.com/41326532/112145210-fdf43d80-8bd1-11eb-885b-736f0d4f20cf.png)

Console Error:
`GET https://www.***redacted***.com/wp-admin/index.php?oauth2callback=1&authuser=2&code=4%2F0AY0e-g6daAbxdGQH2qc1rXd4BZYA6Wozrqx88Ha74bk08vyCBHgtHEfdgyYDPr6IgIe9BQ&prompt=consent 403`

From further testing this can occur with particular redirection configurations. For those impacted please check for any forced redirection or preferred domain prefix configurations (www / non www) at host level. On a Plesk control panel I was able to proceed when the "Preferred domain" option at host level was "none", meaning both www and non www were accessible.

**Comment by jamesozzie** [comment]
@abdullah1908 Assigning to L1 to see if any action is required or further testing necessary. Particular hosting configurations with preferred domain prefix's may result in this notice. It may be worth checking both https and www changes along on some of the shared hosting platforms we have.

**Comment by abdullah1908** [comment]
I am unable to recreate this issue while updating http to https & it worked for me smoothly. You may find further details on [internal task](https://app.asana.com/0/1199554277512201/1200102646337966).

**Comment by bethanylang** [comment]
Thanks, @abdullah1908. So that we can avoid having to view issues across multiple systems, can you please share the troubleshooting steps that you went through here in GitHub?

**Comment by abdullah1908** [comment]
Sure @bethanylang here are the steps that I followed:
- Install Site Kit on subdomain
- Change http to https
- Setup Site Kit & configured Google Services
- I couldn't see any notice & it worked smoothly.
- See [recording](https://www.loom.com/share/9c10462b534b47119b159df9008fe7e7) for further details.

**Comment by bethanylang** [comment]
This was likely fixed by https://github.com/google/site-kit-wp/issues/2935. Closing!
