### ISSUE TITLE
Allow search terms in user input to stack / span multiple lines

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2841]
## Bug Description

Search keywords should not be limited to appearing in a single line input field, as this causes problems (see screenshots):

![Screenshot from 2021-02-17 17-34-54](https://user-images.githubusercontent.com/3531426/108756510-739aba00-74fd-11eb-9cde-bcbd3b59803a.png)
![Screenshot from 2021-02-17 17-33-41](https://user-images.githubusercontent.com/3531426/108756515-75647d80-74fd-11eb-888e-c78509491b3b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Search keywords in the user input flow question 5 should never overflow the field.
* The field itself should have a flexible height, and the search keyword bubbles should be allowed to stack on top of each other if they otherwise would exceed the available width.
* The help description shouldn't be padded from the left side like it is right now.

## Implementation Brief
* Using `/assets/sass/components/user-input/googlesitekit-user-input-controls.scss`,
	* Update the `.googlesitekit-user-input__text-options` class to remove the `height` and `padding-bottom`. Since we are removing the `padding-bottom`, set the `min-height` to `60px`. Lastly set `flex-wrap` to `wrap`.
	* Update the `.mdc-text-field` to add `12px` margin bottom.
	* Update the `.googlesitekit-user-input__text-option` to add a margin bottom of `12px`.
* Remove the `margin-left` from `.googlesitekit-user-input__note`
* Add the removed `margin-left` to `.googlesitekit-user-input__select-options + .googlesitekit-user-input__note` since the note is an immediate sibling of the select options which is always either a list of checkboxes or radio buttons where it should have the indentation.

### Test Coverage

* No change

### Visual Regression Changes

* Should be none

## QA Brief

* 

## Changelog entry

*

**Comment by asvinb** [comment]
@felixarntz By "help description shouldn't be padded from the left side like it is right now.", do you mean the text below the input?
![image](https://user-images.githubusercontent.com/31818/108974457-ebecb100-769e-11eb-87f0-e3be7db468b3.png)

**Comment by aaemnnosttv** [comment]
> @felixarntz By "help description shouldn't be padded from the left side like it is right now.", do you mean the text below the input?

@asvinb yes, I believe that's what he's referring to.

**Comment by asvinb** [comment]
@aaemnnosttv @felixarntz In that case, we will be moving away from the designs. As per Figma (the screenshot I posted here: https://github.com/google/site-kit-wp/issues/2841#issuecomment-784914132, the "help description" has some left spacing. Can you confirm we shall remove the left spacing and not follow the designs?

**Comment by felixarntz** [comment]
@asvinb Yes, that spacing should be removed even though it is in the original Figma design. However, **it should only be removed anywhere where it is below a text field** (i.e. only the last question right now); the indentation makes sense when it is below a list of radio buttons or checkboxes, where it matches the indentation of the text above, but it looks weird when below a full-width text input.

**Comment by asvinb** [comment]
Sounds good @felixarntz . IB updated.

**Comment by aaemnnosttv** [comment]
> * Using `/assets/sass/components/user-input/googlesitekit-user-input-module.scss`,
	* Add a new nested class name `.-no-left-margin` under the `.googlesitekit-user-input__note` class name which has left margin set to `0`.
> * Review screens where the `.googlesitekit-user-input__note` is used and is positioned after an input text (not radio or checkboxes). If that is the case, add the `no-left-margin` class name to the element having the `.googlesitekit-user-input__note` class name. An example is the `Question 5: To help us identify opportunities for your site, enter the top three search terms that best describe your site’s content.` screen. 

@asvinb a few ideas about alternate approaches:

Remove the `margin-left` in the base `googlesitekit-user-input__note` and do one of these:

* Add the `margin-left` to `.googlesitekit-user-input__select-options + .googlesitekit-user-input__note` since the note is an immediate sibling of the select options which is always either a list of checkboxes or radio buttons where it should have the indentation.
* Move the `div.googlesitekit-user-input__note` within the `.googlesitekit-user-input__select-options`
    * Add `margin-left` to `.googlesitekit-user-input__select-options .googlesitekit-user-input__note` (less fragile selector but changes DOM structure)

What do you think?

**Comment by asvinb** [comment]
@aaemnnosttv My preference would be the first option, i.e targeting the sibling. However like you mentioned, it's quite fragile, and am just curious if we'll ever find ourselves in a situation where we don't need to add the margin left to the help text when followed by radios/checkboxes. If we're pretty sure that won't happen, then i say, let's go for option 1, like you suggested :)

**Comment by aaemnnosttv** [comment]
Sounds good @asvinb 

IB ✅

**Comment by ivankruchkoff** [comment]
Spun up a branch with the changes, it doesn't look quite right cc @asvinb and @aaemnnosttv :
https://github.com/google/site-kit-wp/tree/bug/2841-allow-user-input-terms-to-multiline
`bug/2841-allow-user-input-terms-to-multiline`

**Before**
<img width="543" alt="Screen Shot 2021-03-09 at 3 34 50 PM" src="https://user-images.githubusercontent.com/373931/110553114-55cc7800-80ed-11eb-8720-1e1d8d94fe95.png">
<img width="535" alt="Screen Shot 2021-03-09 at 3 34 56 PM" src="https://user-images.githubusercontent.com/373931/110553113-5533e180-80ed-11eb-92c8-d456886b7261.png">

<img width="568" alt="Screen Shot 2021-03-09 at 3 36 10 PM" src="https://user-images.githubusercontent.com/373931/110553111-549b4b00-80ed-11eb-9b14-9dbad615af39.png">

After

<img width="567" alt="Screen Shot 2021-03-09 at 3 36 15 PM" src="https://user-images.githubusercontent.com/373931/110553148-6846b180-80ed-11eb-9498-ad865714bb34.png">
<img width="573" alt="Screen Shot 2021-03-09 at 3 36 24 PM" src="https://user-images.githubusercontent.com/373931/110553145-67ae1b00-80ed-11eb-8ea8-e9ebd471c503.png">
<img width="539" alt="Screen Shot 2021-03-09 at 3 36 36 PM" src="https://user-images.githubusercontent.com/373931/110553144-67158480-80ed-11eb-8cce-74ad490902ee.png">
<img width="543" alt="Screen Shot 2021-03-09 at 3 38 33 PM" src="https://user-images.githubusercontent.com/373931/110553248-90ceab80-80ed-11eb-8fb2-96fad74e48d1.png">

**Comment by aaemnnosttv** [comment]
@asvinb can you take over the draft PR and see if we can get this finished up in time for the release?

**Comment by asvinb** [comment]
@ivankruchkoff I made some tweaks to the CSS. Can you check if everything is ok now?

**Comment by ivankruchkoff** [comment]
Looks great to me, both desktop and mobile. However some conflicting rules in current `develop` branch break this, 

https://github.com/google/site-kit-wp/blame/develop/assets/sass/components/user-input/googlesitekit-user-input-controls.scss#L87
https://github.com/google/site-kit-wp/blame/develop/assets/sass/components/user-input/googlesitekit-user-input-controls.scss#L128

**Comment by eugene-manuilov** [comment]
@felixarntz I think this ticket doesn't make sense anymore after we merged #2842. Shall we close this or you think we still need to do something else?

**Comment by felixarntz** [comment]
@eugene-manuilov Yes agreed. The current state after #2842 already handles any long input smoothly and without weird overflow. Multiple search terms already stack as needed, and if one of them is super long, it is scrollable horizontally so all good 🎉
