### ISSUE TITLE
Fix bad UX approach for typing search terms in user input flow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2842]
## Bug Description

Currently when typing the search terms in the last question of the user input flow, the approach is unintuitive:

* Users have to add the separator for the search term to be actually recognized / turned into a blue bubble.
* If you're only adding a single search term, this will result in the CTA button still being disabled although you've already typed the search term.
* If you're adding more than one search term, it can result in the last one being stripped, just because the user didn't add yet another separator after the last one.

The overall approach of waiting until the separator is typed before "recognizing" the search term results in those issues.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The approach for handling what the user is typing for search keywords should be improved so that the user should always be typing _within_ a blue bubble. To be more precise:
    * As soon as the user starts typing, a blue bubble should be added (for the first search term). The user should then type _within_ that bubble.
    * When the user presses one of the separators, they should "leave" the bubble.
    * If they then continue typing, the next blue bubble should be added (similar like before), and the user should once again type within that bubble.
    * This should work until there is a third bubble. Pressing a separator again should not have an effect at that point.
* A user should be able to individually edit the search keyword bubble content.
* The ability to delete a search term by clicking the "X" on the bubble should be maintained as before.

## Implementation Brief

* The required functionality is implemented in #2884. Use that PR as a starting point for your changes.
* The remaining part is to update styles of input fields used for editing search terms to match the current styles of the search terms bubbles.

### Test Coverage

* Update existing tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* Search terms should become editable now and the UX flow should change as per AC.

## QA Brief

* Go to the user input settings flow and proceed to the last question where you can type search terms.
* Make sure the search terms control works as described in the AC section.

## Changelog entry

* Improve UX around entering search terms in the user input flow.

**Comment by eugene-manuilov** [comment]
@felixarntz this is ready for IB review. I have a question regarding the following:

> If they click between one of the bubbles or after the last one, they should be creating a new one if they start typing (unless there are already three bubbles, once again, as that is the limit).

What do you mean by "click between"? How we can determine whether it has been clicked between or not between bubbles? :thinking:

Can you check #2884? It is a prototype that implements the logic explained in the AC but uses a slightly different approach than detecting clicks between bubbles. Please, let me know if it works for you.

**Comment by felixarntz** [comment]
@eugene-manuilov The current IB doesn't really describe how to do it; that can be okay if the work is fairly trivial or if the PR easily shows it, but I wasn't able to build it locally due to a `Can't resolve '../../../svg/close.svg'` error - can you check? Overall I think a bit of explanation would help.

> What do you mean by "click between"? How can we determine whether it has been clicked between or not between bubbles?

In principle we should be able to listen to where the user clicked (or otherwise navigated) I'd think. For example, in the Gutenberg editor, when you apply special formatting (e.g. _italic_ text or `code`) and then navigating with the arrow keys, Gutenberg differentiates/recognizes whether you are within the special-formatted segment of text or outside of it. In a similar way, I'd expect we'd be able to recognize whether the user's cursor is _within_ a blue bubble or outside of it. For example:

1. You start typing; the first blue bubble immediately appears, so you type in there.
2. You type a comma; the cursor leaves the first bubble.
3. You continue typing; a second bubble appears, so you type in there.
4. You navigate backwards with the left-arrow key until you are in the regular text area between the two bubbles (or click between the two bubbles), then you continue typing; a new bubble appears **between the first and second bubble**, so you type in there.

As soon as there are three bubbles, typing between them would no longer be possible.

**Comment by eugene-manuilov** [comment]
> I wasn't able to build it locally due to a `Can't resolve '../../../svg/close.svg'` error - can you check? Overall I think a bit of explanation would help.

@felixarntz this should be fixed now. I forgot to push that file. Could you please try it again? I think it should satisfy your requirements except for the logic with clicks between bubbles. Please, let me know if the implemented logic is sufficient or not.

**Comment by felixarntz** [comment]
@eugene-manuilov Behavior in the PR looks good to me after testing, that should do it; just a bunch of things regarding the styling is not implemented yet, but you mentioned already that this was only due to this being a draft PR - IB ✅

**Comment by eugene-manuilov** [comment]
@asvinb can you help me with styles for this ticket? I have implemented the logic but styles are still off.

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

- As soon as the user starts typing, a blue bubble is added. The user then types within that bubble. - [Screenshot](https://user-images.githubusercontent.com/73545194/110765468-2bb2bb80-828f-11eb-8749-41188c8300fc.png)
- When the user presses one of the separators, they leave the bubble. The cursor is outside. 
- When they continue typing, the next blue bubble is added and the user can type within that bubble. - [Screenshot](https://user-images.githubusercontent.com/73545194/110766629-55b8ad80-8290-11eb-8a9f-f5d2e4703d5e.png)
- When the user presses one of the separators, they leave the bubble. The cursor is outside. 
- When they continue typing, the final blue bubble is added and the user can type within that bubble. - [Screenshot](https://user-images.githubusercontent.com/73545194/110766926-a6c8a180-8290-11eb-92a3-8f49c1b5c1c7.png)
- Pressing a separator again does  have an effect after typing in the final search term. 
- A user can individually edit the search keyword bubble content.
- A user can delete a search term by clicking the "X" on the bubble.
