### ISSUE TITLE
Use more appropriate wording in last user input question

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2843]
The last question uses "keyword" in one place, "search term" in another. "Term" overall seems more suitable since it is possible to enter more than one word (i.e. spaces within a single term are allowed).

Furthermore, the "Enter" key should no longer be referred to as such, since that is not always the name of that key.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Leave the question copy as-is (mentioning "terms" and "search terms")
* Update the copy inside the input box to "Enter minimum one (1), maximum three (3) terms"

## Implementation Brief
* Using `/assets/js/components/user-input/UserInputKeywords.js`, update the `TextField` `label` from `Minimum one (1), maximum three (3) keywords` to `Enter minimum one (1), maximum three (3) terms`

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* Check that the wording of the last user input question says "Enter minimum one (1), maximum three (3) terms"

## Changelog entry

* Clarify wording in last user input question about search terms.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

The wording of the last user input question says `Enter minimum one (1), maximum three (3) terms`

![image](https://user-images.githubusercontent.com/73545194/111306634-69e71b00-8693-11eb-8199-4988f17782c8.png)
