### ISSUE TITLE
Avoid loss of user input responses due to navigating away

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2844]
## Bug Description

When the user navigates away from the user input screen without submitting their responses, they currently all get lost. This is most problematic because there is a link to "Settings" on that page that seems like it would be worth clicking it; but overall it is a problem that the responses aren't saved anywhere because the user could navigate away from the page at any point.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user input responses should be temporarily stored in the browser (e.g. local storage) as the user goes through the user input flow, so that they are still in place, should they leave the page before submitting them.
* The storage should explicitly still be temporary, i.e. nothing should be sent to WordPress or the authentication service other than on submission, as it is now.
* Once the user submits the responses to the API, the temporary browser storage should be cleared, as the source of truth is now the API.
* The "Settings" link that appears on each user input question should no longer be a link. The copy should be kept, it just shouldn't link to "Settings" because otherwise it makes it too "easy" to accidentally navigate away from the screen.

## Implementation Brief

* Edit `user-input-settings` datastore:
  * Update the `setUserInputSetting` action:
    * Read the `user-input` property from the local storage with an empty object fallback if the property doesn't exist;
    * Add the current timestamp plus one hour to the `user-input` object under the `ttl` property;
    * Add the incoming values to the `values` property of the `user-input` object;
    * Save the `user-input` object in the local storage. Here is an example of the `user-input` object structure:
      ```javascript
      {
          "ttl": 1234567890,
          "values": {
              "setting1": [...],
              "setting2": [...],
              ...
          }
      }
      ```
  * Update the `saveUserInputSettings` action to remote the `user-input` item from the local storage.
  * Update the `getUserInputSettings` selector:
    * Read the `user-input` property from the local storage;
    * Do nothing if the `user-input` object is empty or its `ttl` value is less than the current timestamp;
    * Otherwise, merge values from the `values` property of the `user-input` object with user input settings received from the server.
* Remove the link to "Settings" page in the `UserInputQuestionNotice` component.

### Test Coverage

* Update the existing tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* N/A

## QA Brief

_Note: it's easiest to test this in Storybook and it will still work there, because the User Input questionnaire is only shown once._

* Load the User Input Questionnaire on a new site. By default, no questions should show as answered. (This requires enabling the "`userInput`" feature flag on the site.
* Answer one or more questions then navigate away from the User Input questions, to another site or another page on your WordPress dashboard.
* Return to the User Input questions (by returning to the Site Kit dashboard on a new site with the `userInput` flag enabled). The questions you previously answered should be filled in.
* Complete your questions and submit them.
* Navigate to "Settings" and edit your answers, changing some to new answers but don't save the answers. Navigate away from the page.
* Navigate back to the "Edit answers" page again—your "changed, unsaved" answers should not persist and the answers should be the same ones you submitted the first time.

## Changelog entry

* Cache user input responses temporarily in browser until it is submitted while the user is going through the flow, to prevent accidentally losing entered data.

**Comment by felixarntz** [comment]
@eugene-manuilov I think it would be good to limit the time we consider the `localStorage` values valid. Potentially we should include a timestamp there to expire them after, let's say 1 hour. If you leave the user input flow without saving, but then don't come back to it in an hour, I think it's safe to assume they didn't accidentally leave the flow.

> Update the `getUserInputSettings` selector to populate settings using user input settings from the local storage if setting received from the server has empty `values` array

I think we should always use the `localStorage` value if it exists and is still valid, as we should be able to assume it is more up to date than what comes from the server then (especially since `localStorage` value is cleared upon saving anyway). We should make sure to merge it though, so that, in case the API response now includes another key, the data is still in the complete shape. (It's unlikely there'll be additional keys anytime soon, but I think that's worth doing.)

**Comment by eugene-manuilov** [comment]
Nice idea! IB is updated and ready for review.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: 

- When the user completes one or more questions, navigates away and then returns to the User Input questions, the answers appear for the questions answered.

- After submitting answers, and editing a question in settings. The user then changes the answer but does not save. When navigating away from the page, you go back into edit the answer, the changed, unsaved selection is _not_ selected.  The original question answered is still selected.
