### ISSUE TITLE
Introduce (contextual) help icon in Site Kit header bar

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2846]
The Site Kit header bar should include a help icon that, when clicked, exposes a dropdown with various help links. This should globally replace the need for the "Need help?" link in the Site Kit footer.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new feature flag `helpVisibility` should be introduced.
* If the feature flag is enabled, the Site Kit header bar should include a Help icon which exposes a dropdown with three help links per the [Figma file](https://www.figma.com/file/pvsqJE5yZe9cFeNlTKUEiU/Google-SK-UX-Part-3-Enhancements10up?node-id=1437%3A11).
    * On the AdSense screen, an additional "Get help with AdSense" link should be displayed.
* If the feature flag is enabled, the "Need help?" link in the footer should no longer appear.
* A new `HelpMenu` component should be introduced which renders the help menu icon (use a translatable `Help` label for screen readers) and a list of links in the dropdown, per the [Figma file](https://www.figma.com/file/pvsqJE5yZe9cFeNlTKUEiU/Google-SK-UX-Part-3-Enhancements10up?node-id=1437%3A11).
* The individual links should be using a new `HelpMenuLink` component each. The default implementation of `HelpMenu` should automatically render three `HelpMenuLink`s (also per Figma):
    * "Fix common issues" (https://sitekit.withgoogle.com/documentation/fix-common-issues/)
    * "Read help docs" (https://sitekit.withgoogle.com/documentation/)
    * "Get support" (https://wordpress.org/support/plugin/google-site-kit/)
* The `HelpMenu` component should support rendering additional `HelpMenuLink`s passed via `children`. These should be rendered _before_ the default links.
* The `Header` component should be updated to render its `children` unconditionally, not only when the user is authenticated. Any usage where currently `children` are passed require an authenticated user anyway and otherwise are unreachable.
* All screens that render the `Header` component should be updated to render the `HelpMenu` as its first (or only) child, if the `helpVisibility` feature flag is enabled.
    * On the AdSense module page (both legacy and refactored widget version) and the AdSense setup page, an extra `HelpMenuLink` should be included as `HelpMenu` child: It should say "Get help with AdSense" and link to (TBD, please ask @felixarntz as you're working on that issue/PR) (see also [Figma](https://www.figma.com/file/pvsqJE5yZe9cFeNlTKUEiU/Google-SK-UX-Part-3-Enhancements10up?node-id=1437%3A270)).
* If the `helpVisibility` feature flag is enabled, the "Need help?" link should be removed throughout the entire plugin. The `PageFooter` component should remain though as central point to control the page's footer, even though it will eventually only return `null`.

## Implementation Brief
* Add the `helpVisibility` to the array in `/feature-flags.json`.
* Using `/assets/js/components/PageFooter.js`,
	* import the `useFeature` hook from `/assets/js/hooks/useFeature.js` and test if `helpVisibility` flag is enabled.
	* show the `HelpLink` if the flag is not enabled.
* Create new file `/assets/js/components/help/HelpMenuLink.js` which will export the `HelpMenuLink` functional component.
	* The component has the following props:
		* `href`: string
		* `label`: string
	* Use the `Link` component to render the `href` and `label` props, wrapped between the following tag:
		```js
		<li
			className="mdc-list-item"
			role="menuitem"
		>
			<Link href={ href } external>{ label }</Link>
		</li>
		```
	* The `external` prop is passed to the `Link` component since all links are external ones. Please note that as per the designs, there should not be any external icon displayed next to the menu items.
* Create new file `/assets/js/components/help/HelpMenu.js` which will export the `HelpMenu` functional component:
	* The `HelpMenu` component is very similar to the `UserMenu` component and is a good reference to start with, with the following changes:
		* Instead of using the `Menu` component, render the menu markup within the component itself. 
			```js
			<div className="mdc-menu mdc-menu-surface">
				<ul
					aria-hidden={ false }
					aria-orientation="vertical"
					className="mdc-list"
					role="menu"
					tabIndex="-1"
				>
				...
				</ul>
			</div>
			```
		* Add the `children` prop which will be rendered within the `<ul>` tag.
		* Create a new constant, `defaultMenuItems` which is an array of objects containing the `href` and `label` keys. Set the value of the constant to the following:
			```js
			const defaultMenuItems = [
				{
					label: __( 'Fix common issues', 'google-site-kit' ),
					href: 'https://sitekit.withgoogle.com/documentation/fix-common-issues/',
				},
				{
					label: __( 'Read help docs', 'google-site-kit' ),
					href: 'https://sitekit.withgoogle.com/documentation/',
				},
				{
					label: __( 'Get support', 'google-site-kit' ),
					href: 'https://wordpress.org/support/plugin/google-site-kit/',
				},
			];
			```
		* Loop through the `defaultMenuItems` constant and render the items using the `HelpMenuLink` component. The `children` prop should be rendered before the default menu items.
		* Use the `icon` prop of the `Button` component to render the help icon and since only an icon is being displayed for the button, use the `VisuallyHidden` component within the `Button` component to render the `Help` text for screen-readers.
* Edit `/assets/js/components/Header.js` to unconditionally render the `children` prop.
* Update occurrences where the `Header` component is used to include the `HelpMenu` component as its first child if the `helpVisibility` flag is enabled:
	* Import the `useFeature` hook from `/assets/js/hooks/useFeature.js` to test for the `helpVisibility` flag.
	* If `helpVisibility` flag is enabled, render the `HelpMenu` component
	* For e.g in the `DashboardApp` component, `/assets/js/components/dashboard/DashboardApp.js`, usage of the `Header` component should be:
		```js
		<Header>
			{ helpVisibilityEnabled && (
				<HelpMenu />
			) }
			<DateRangeSelector />
		</Header>
		```
		where `helpVisibilityEnabled` has been previously been set by calling `useFeature( 'helpVisibility' );`
* On the AdSense module page (both legacy and refactored widget version) and the AdSense setup page, an addition menu item should be added to the `HelpMenu` component via the `children` prop, using the `HelpMenuLink` component. The values for the `label` prop should be `Get help with AdSense` and the `href` prop is TBD for now. For e.g, the `AdSenseDashboardWidget` should be updated to the following:
	```js
	<Header>
		{ helpVisibilityEnabled && (
			<HelpMenu>
				<HelpMenuLink href="TBD" label={ __( 'Get help with AdSense', 'google-site-kit' ) } />
			</HelpMenu>
		) }

		{ moduleStatus === 'connected' && <DateRangeSelector /> }
	</Header>
	```

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

### Without feature flag enabled

* You should not see a difference in the header on any page—no new help icon link should be visible
* Without the `helpVisibility` feature flag enabled, you should continue to see the "Need help?" link in the bottom footer of the page:
<img width="273" alt="Screenshot 2021-03-12 at 16 28 35" src="https://user-images.githubusercontent.com/90871/110968957-0a65d400-8350-11eb-81bf-98eb863f1ce1.png">

### With the feature flag enabled

* Enable the `helpVisibility` feature flag. You should not see the "Need help?" link at the footer of the site anymore.
* You should see a help icon that opens a dropdown menu in the header of every Site Kit page (except the manual GCP setup page).
  * On any non-AdSense page the header should have three options:
    * Fix common issues
    * Read help docs
    * Get support
  * On any AdSense page, there should be an extra link for a total of four links:
    * Get help with AdSense
    * Fix common issues
    * Read help docs
    * Get support

The help menu should look like this:

<img width="960" alt="Screenshot 2021-03-12 at 16 27 31" src="https://user-images.githubusercontent.com/90871/110969566-bb6c6e80-8350-11eb-8f28-908a10d8da78.png">

![2021-03-12 16 27 13](https://user-images.githubusercontent.com/90871/110969600-c6270380-8350-11eb-8121-b913636c911c.gif)

## Changelog entry

* Introduce new contextual help menu in Site Kit header bar and on the authentication service.

**Comment by felixarntz** [comment]
@asvinb IB mostly looks solid, a few points of feedback:
> Use the `Link` component to render the `href` and `label` props, wrapped between the following tag

The links should all open in a new tab; can you include that in the IB? They shouldn't receive the external icon though, since all of these links by definition are external, so they shouldn't be separately marked as such.

> * Create new file `/assets/js/components/help/HelpMenu.js` which will export the `HelpMenu` functional component:
>	* The `HelpMenu` component is very similar to the `UserMenu` component and is a good reference to start with, with the following changes:
>		* Import the `useFeature` hook from `/assets/js/hooks/useFeature.js` and test if `helpVisibility` flag is enabled.
>		* Return `null` if the flag is not enabled.

The feature flag shouldn't be handled _within_ this component, that feels counter-intuitive. The component should be self-contained. Rather than that, wherever we render the `HelpMenu`, we should only do that if the flag is enabled.

> Loop through the `defaultMenuItems` constant and render the items using the `HelpMenuLink` component. The menu items should be rendered before the `children` prop value.

This should be the other way around: `children` should be rendered before the `defaultMenuItems`.

> Update occurrences where the `Header` component is used to include the `HelpMenu` component as its first child.

See my above feedback: Here we should have the feature flag check instead, not within `HelpMenu`.

**Comment by asvinb** [comment]
Thanks @felixarntz . IB has been updated. Can you check again?

**Comment by felixarntz** [comment]
IB ✅

**Comment by Hazlitte** [comment]
I have made progress on this ticket in brach https://github.com/google/site-kit-wp/tree/enhancement/2846-help-icon.

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@tofumatt @aaemnnosttv a few observations:

1)  On mobile, the icon causes placement issues with the account icon and date range dropdown. I tested this on a few different small screen sizes. Tablets seem to be fine. - [Screenshot](https://user-images.githubusercontent.com/73545194/111785557-b9c61c00-88f7-11eb-86aa-5020e22d7ac0.png)
2) When you click the icon on mobiles, on Adsense pages, part of the options in the dropdown are cut off depending on the screen width.  Seems okay on non Adsense pages. Solving the issue above might solve this. - [Screenshot](https://user-images.githubusercontent.com/73545194/111785899-25a88480-88f8-11eb-879c-0050b8d8969f.png)
3) This is my personal opinion :) On desktop, do you think the icon is helpful on its own? Wondered if we should have 'Need Help' as the text next to the icon. Just looks a little odd all alone on the header. 

**Verified:**

With `helpVisibility` feature flag disabled. 

- No differences can be found in the header on any page (no new help icon link is visible) - [Screenshot](https://user-images.githubusercontent.com/73545194/111784920-ea598600-88f6-11eb-8f9e-13e0292fe0b4.png)
- The `Need help?` link appears in the bottom footer of the page  - [Screenshot](https://user-images.githubusercontent.com/73545194/111785054-1412ad00-88f7-11eb-8196-0be10342dae8.png)

With `helpVisibility` feature flag enabled. 

- The "Need help?" link does not appear in the footer of the site.  - [Screenshot](https://user-images.githubusercontent.com/73545194/111785304-66ec6480-88f7-11eb-98b8-0bd5219178b2.png)
- The help icon appears on the top of all pages.   
- On Adsense pages the additional option appears in the dropdown. `Get Help with Adsense` - [Screenshot](https://user-images.githubusercontent.com/73545194/111784507-70c19800-88f6-11eb-8c9d-9dfeb5b52458.png)
- On non Adsense pages only the 3 identified options appear in the dropdown.  - [Screenshot](https://user-images.githubusercontent.com/73545194/111784652-9c448280-88f6-11eb-90ab-c8c03ad15fa6.png)
- All of the options in the dropdown, when clicked go to the appropriate page on Google.

**Comment by tofumatt** [comment]
1. I've done my best in a follow-up PR to improve the mobile styling:
<img width="571" alt="Screenshot 2021-03-22 at 12 16 10" src="https://user-images.githubusercontent.com/90871/111992165-03d41b00-8b0d-11eb-9e8d-2bc809ccb90f.png">
but there are still issues when the string is longer on an iPhone 8 screen size (eg translated):
<img width="432" alt="Screenshot 2021-03-22 at 12 31 54" src="https://user-images.githubusercontent.com/90871/111992207-0f274680-8b0d-11eb-9bb1-b404e3091042.png">

We'll need to create a more flexible mobile design for the header (removing the "Site Kit" text and just having the "G" logo there might be better?).

2. This seems to be a bug with the `Menu` component—the text shouldn't ever go off-screen I think, but I don't think there's a straightforward fix for now. We could file a follow-up issue for it.

3. Unfortunately there definitely isn't space for this in the current design, but I agree 🙂

**Comment by aaemnnosttv** [comment]
@tofumatt would it not be better to remove the label from the date range menu in mobile like we do with the user menu? Not sure why that one in particular would be special in this viewport size. We shouldn't need to use an alternate logo in mobile but I suppose that's possible too. I would think that would be more of a last resort though.

**Comment by tofumatt** [comment]
Ah, true actually. I considered doing just "28 days" over "Last 28 days", but yes, removing the text entirely would work as long as we highlight the currently-selected item in the dropdown. Let's do that 👍🏻

**Comment by tofumatt** [comment]
Update: it now looks like this which I think is a lot better:

<img width="475" alt="Screenshot 2021-03-22 at 21 09 27" src="https://user-images.githubusercontent.com/90871/112058762-e629a480-8b52-11eb-91cd-f614c72b43fd.png">

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@tofumatt I am pretty confident that it was removed before, but when I look at the pages, other than the Site Kit dashboard, they all have the "Need help?" link in the bottom footer of the page. Could you clarify if this is expected or not? Other than this, it's looking great on smaller screen sizes now. 

![image](https://user-images.githubusercontent.com/73545194/112310280-5a914e80-8cdf-11eb-87f8-c27c248becdc.png)

**Verified:**

With `helpVisibility` feature flag disabled. 

- No differences can be found in the header on any page (no new help icon link is visible) - [Screenshot](https://user-images.githubusercontent.com/73545194/111784920-ea598600-88f6-11eb-8f9e-13e0292fe0b4.png)
- The `Need help?` link appears in the bottom footer of the page  - [Screenshot](https://user-images.githubusercontent.com/73545194/111785054-1412ad00-88f7-11eb-8196-0be10342dae8.png)

With `helpVisibility` feature flag enabled. 

- The help icon appears on the top of all pages.   
- On Adsense pages the additional option appears in the dropdown. `Get Help with Adsense` - [Screenshot](https://user-images.githubusercontent.com/73545194/111784507-70c19800-88f6-11eb-8c9d-9dfeb5b52458.png)
- On non Adsense pages only the 3 identified options appear in the dropdown.  - [Screenshot](https://user-images.githubusercontent.com/73545194/111784652-9c448280-88f6-11eb-90ab-c8c03ad15fa6.png)
- All of the options in the dropdown, when clicked go to the appropriate page on Google. 
- I also checked the help icon with mobile and tablet screen sizes and it's looking great now. (nice work @tofumatt) - [Screenshot](https://user-images.githubusercontent.com/73545194/112308042-a262a680-8cdc-11eb-86cd-c509af3d1c3f.png)

**Comment by tofumatt** [comment]
That's not expected, I wonder if there was a merge conflict I missed or they were added back? I'm taking a look right now.

**Comment by tofumatt** [comment]
There are a lot of other `<HelpLink />`s not mentioned in the IB actually, but I suppose I should've searched for them 😓

Quick PR incoming to fix that 😄

**Comment by felixarntz** [comment]
@tofumatt The PR is almost ready, should be a quick update.

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

**Verified:**

With `helpVisibility` feature flag disabled. 

- No differences can be found in the header on any page (no new help icon link is visible) - [Screenshot](https://user-images.githubusercontent.com/73545194/111784920-ea598600-88f6-11eb-8f9e-13e0292fe0b4.png)
- The `Need help?` link appears in the bottom footer of the page  - [Screenshot](https://user-images.githubusercontent.com/73545194/111785054-1412ad00-88f7-11eb-8196-0be10342dae8.png)

With `helpVisibility` feature flag enabled. 

- The help icon appears on the top of all pages.   
- On Adsense pages the additional option appears in the dropdown. `Get Help with Adsense` - [Screenshot](https://user-images.githubusercontent.com/73545194/111784507-70c19800-88f6-11eb-8c9d-9dfeb5b52458.png)
- On non Adsense pages only the 3 identified options appear in the dropdown.  - [Screenshot](https://user-images.githubusercontent.com/73545194/111784652-9c448280-88f6-11eb-90ab-c8c03ad15fa6.png)
- All of the options in the dropdown, when clicked go to the appropriate page on Google. 
- The `Need help?` link does not appears in the bottom footer of the page  
- I also checked the help icon with mobile and tablet screen sizes and it's looking great now. (nice work @tofumatt) - [Screenshot](https://user-images.githubusercontent.com/73545194/112308042-a262a680-8cdc-11eb-86cd-c509af3d1c3f.png)
