### ISSUE TITLE
Implement tooltip for new contextual help feature

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2847]
The contextual help feature introduced via #2846 should receive a tooltip that highlights the addition to the screen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new tooltip "tour" (with just a single step) should be added: It should appear on the dashboard if the user's initial Site Kit version is below 1.29.0 (TBD, depending on when we'll ship this feature), target the new help icon, and the copy for the only step should be as follows:
    * Heading: _Need help?_
    * Content: _Access the Site Kit docs or ask a question in our support forum from here._
    * As tooltip tours work by default, this should have a "Got it" button to dismiss the tooltip "tour".
    * The tooltip tour should use the slug `helpVisibility` internally.
    * The tooltip tour should only be shown if the `helpVisibility` feature flag is enabled.
    * See also [Figma](https://www.figma.com/file/pvsqJE5yZe9cFeNlTKUEiU/Google-SK-UX-Part-3-Enhancements10up?node-id=1408%3A475).
* Only one tooltip tour should be displayed at a time. If both the existing `allTrafficWidget` and the new `helpVisibility` tooltip tour are relevant, the `allTrafficWidget` one should be displayed first. Once that is completed/dismissed, the `helpVisibility` one should show up, **after a minimum period of 2 hours (so that the user isn't overwhelmed by many tooltips right after each other)**.

## Implementation Brief

* Create a new file `assets/js/feature-tours/help-visibility.js` that exports an object with the following properties:
  * `slug` should be `helpVisibility`;
  * `contexts` should be an array with `VIEW_CONTEXT_DASHBOARD` and `VIEW_CONTEXT_PAGE_DASHBOARD` values;
  * `version` should be `1.29.0`;
  * `checkRequirements` should ensure the tour only shows up when the `helpVisibility` feature flag is enabled
  * `steps` should be an array with a single item: 
    * `target` should contain a selector which can be used to find the help menu icon in the DOM (coordinate/get that information based on #2846, which implements that icon)
    * `title` should be `Need help?`;
    * `content` should be `Access the Site Kit docs or ask a question in our support forum from here.`;
    * `placement` should be `bottom-start`.
* In the `assets/js/feature-tours/index.js` file, import an object from the `help-visibility.js` file and add it to the end of the array that is exported by default in this file.

**Preventing successive tours**

Outlined below is a strategy to store a timestamp in the browser cache whenever a tour is dismissed. Using a few added selectors to the feature tours datastore, consumers can simply check "are feature tours on cooldown?". Currently, this would simply not render any tours. The rationale for using the browser cache specifically is: 1) simplicity, but also 2) it handles the upgrade case well due to the cache naturally being invalidated on upgrade.

> The upgrade case is:
>  * User qualifies to see a feature tour for a given view
>  * User sees and dismisses tour
>  * Tours are now on cooldown for the next 2 hours
>  * User upgrades Site Kit within the cooldown period in which the new version adds a new tour
>  * User should see the next tour right away, but any subsequent tours would be on cooldown again as usual

* Add `initialState.lastDismissedAt` of `undefined`
* Add `actions.receiveLastDismissedAt( timestamp )`
  - Returns an action object with the timestamp in the payload which is handled in the reducer
    - type: `RECEIVE_LAST_DISMISSED_AT`
    - payload: `{ timestamp: Date.now() }`
* Add `controls[ CACHE_LAST_DISMISSED_AT ]`
  - takes the `timestamp` from its action's payload and sets it in the cache using `setItem` from `assets/js/googlesitekit/api/cache.js`
    - The value should receive a TTL of 2 hours (add a new constant for this)
  - The key can be `feature_tour_last_dismissed_at` (will receive additional prefixing/namespacing automatically) and the value should be the timestamp
* Add `actions.setLastDismissedAt( timestamp )`
  - yields both `receiveLastDismissedAt` and an internal/private action type (basically same as the receive action just with a different `type`) which is handled by the control to persist the value
* Update `actions.dismissTour` in `assets/js/googlesitekit/datastore/user/feature-tours.js`
  - After yielding the action to dismiss the tour, yield `setLastDismissedAt( Date.now() )`
* Add `selectors.getLastDismissedAt` to return `lastDismissedAt` from state
* Add `resolvers.getLastDismissedAt` to asynchronously load the value from cache and receive it in the state using `SET_LAST_DISMISSED_AT`
* Add `selectors.areFeatureToursOnCooldown` as a registry selector which selects `getLastDismissedAt`
  – if not resolved yet it should return `undefined`
  - if the `lastDismissedAt` timestamp is within the last 2 hours (let's define a constant for this value to share with the above reference with the cache api) then return `true` (on cooldown)
  - otherwise return `false`
* Update `FeatureTours` to select `areFeatureToursOnCooldown` and update its guard condition to include this value
  - if `areFeatureToursOnCooldown` returns `true`/truthy then the component should return `null` regardless whether or not there are qualifying tours for the view

### Test Coverage

* Add test coverage for added actions and selectors to `feature-tours` store partial

### Visual Regression Changes

* A new tooltip tour should appear for the help menu.

### Viewing the tour
* Enable `helpVisibility` in the tester plugin. You can verify that this feature is enabled by examining `_googlesitekitBaseData.enabledFeatures` in the browser console. 
* Ensure that you are using version `<= 1.29`. 
* Navigate to the Site Kit dashboard or page dashboard screens
* You should see the helpVisibility tooltip aligned over the help menu

### Dismissing the tour and setting the cache
* Dismiss the tour, either by hitting the `x` or 'Got it'
* Open up the Application tab in devtools and verify that there is a `feature_tour_last_dismissed_at` item in the session storage cache. It should have a `ttl` of 2 hours (7200).
* To verify that the cache is being used correctly, first ensure that the `helpVisibility` tour is next in the queue by entering this in the console: `googlesitekit.data.dispatch('core/user').receiveGetDismissedTours(['allTrafficWidget'])`.
* You should not see the `helpVisibility` tour, because of the item in the cache.
* If you now delete the item from the cache, or enter `googlesitekit.data.dispatch('core/user').receiveLastDismissedAt(null)`, the tour should reappear.

### Cooldown period
* No tours should appear during the cooldown period. In order to check this without waiting 2 hours, you might want to change the value of `FEATURE_TOUR_COOLDOWN_SECONDS` [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/user/feature-tours.js#L39). If you change it to, for example, `30`, then the ttl on the cache item should be `30` and the tour should not appear again until 30 seconds later.

### Contexts
* The tour should appear on the main Site Kit and page dashboards.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eugene-manuilov I think it would be best to wait with the IB for this one until #2739 is defined. That one is for the first tooltip tour and should include introduction of the basic management layer for tooltip tours (since they should be centrally controlled, not within a specific component).

**Comment by eugene-manuilov** [comment]
@felixarntz I have updated the IB to work with the new infrastructure for the tooltip tours. So this is ready for review.

**Comment by felixarntz** [comment]
@eugene-manuilov (or whoever is taking over this): The current IB looks solid against the original ACs. However, we have to make an adjustment here which I have just added to the ACs (in bold, at the end).

Please amend the IB with a **reusable** way to ensure that different tooltip tours are not shown after each other within the "time out" mentioned in the IB. For example, a flag with a timeout could be set when dismissing a tooltip tour, to ensure no new tooltip tour is triggered until 2 hours later. The estimate needs to be updated as well, since it originally didn't include that part.

**Comment by felixarntz** [comment]
@aaemnnosttv IB ✅ 

+1 for using client-side storage only for this.

I've amended the ACs and IB with one detail that was missing before, which is that the tooltip must only be shown if the `helpVisibility` feature flag is enabled.

I'll also remove #2846 as being a blocker here; it's a blocker for completing the implementation but not for starting it.

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt @eugene-manuilov Since #2846 was already merged, this here also needs to go with it as mentioned; let's make sure to pick this up over anything else for the release or not the release. The user input stuff is less urgent.

Alternatively, we need to revert #2846 from `develop` as those should be shipped together.

**Comment by felixarntz** [comment]
@johnPhillips Can you please add a QA Brief here?

**Comment by tofumatt** [comment]
QA ✅
