### ISSUE TITLE
Center align tabs "Channel, Locations, Devices" over the pie chart

### ISSUE THREAD

**Issue by aarondruck** [google/site-kit-wp#2849]
## Bug Description

The tabs Channel, Locations, and Devices, are not center aligned over the pie chart.  They're floating to the left, on a wide screen.

## Steps to reproduce

Look at the main dashboard / Site Overview page.  It's in the section called "Your Traffic at a Glance"

## Additional Context

Mac, Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@aarondruck Can you re-check that with the latest Site Kit version? This should already be the case by now.

**Comment by felixarntz** [comment]
Closing per internal reply.
