### ISSUE TITLE
analytics module cross domain support for advanced users?

### ISSUE THREAD

**Issue by Insomnia88** [google/site-kit-wp#285]
Hi I just installed the sitekit and wanted to use the analytics module but receive an error that it cannot find any analytics account. Since there are already topics about this error I don't want to focus on it alone but ask how it's about the support for multiple cross linked domains? 
I don't wonder why the module cannot find any "target url" because my properties in analytics don't necessarily have the correct URL (for reasons of advanced GA usage). I am using the GTM to setup the different codes based on the URL for me. I guess this isn't supported by the sitekit yet? If not, will this be included in the future?  

#281

**Comment by jamesozzie** [comment]
@Insomnia88 Before I added this as a feature request can you let me know the following:
1. Please provide an example of the domain setup you are using (ie. subdomains or more advanced implementation methods)? 
2. Have you inserted your Tag Manager container code into your theme files or via a third party plugin?

**Comment by Insomnia88** [comment]
@jamesozzie 
1. They are different domains, like "a-sattelite-example.fr" and "another-sattelite-example.co.uk" that redirect the user to another one like "example.com". The "example.com" domain also includes the codes for the other domains "a-sattelite-example.fr" and "another-sattelite-example.co.uk".
2. I inserted it manually in my theme files, no plugin.

**Comment by jamesozzie** [comment]
@Insomnia88 I will close this issue now as I have labeled #281 as a feature request.
