### ISSUE TITLE
Fix tooltip in "Others" pie chart slice

### ISSUE THREAD

**Issue by aarondruck** [google/site-kit-wp#2850]
## Bug Description

In the "Your Traffic at a Glance" module on the Site Overview page - it's difficult to click the "Others" popup/tooltip, when you hover over "OTHERS" on the pie chart, in the Locations tab.

You can't click on "See the detailed breakdown in Analytics" in the tooltip, because as soon as the mouse stops hovering on the pie chart slice, the tooltip disappears.

## Steps to reproduce

1. In the "Your Traffic at a Glance" card, click on Locations
2. Hover over the "OTHERS" pie slice with your mouse
3. Try to click on "See the detailed breakdown in Analytics" in the tooltip"

## Additional Context

Mac, Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This was already done via #2737 - closing.
