### ISSUE TITLE
User Input: Only show note saying "question applies to other users" if other users on the site exist

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#2852]
## Feature Description

Currently we show a notice during the third question in the User Input flow that the question will affect the entire site and affect other users on the site. While this text could be clarified (see #2853), it is redundant if you are the only user (or at least the only _admin_) on the site who can use Site Kit/answer the question.

![image](https://user-images.githubusercontent.com/90871/108788933-ff99f980-7570-11eb-89d5-4b2511cfc02a.png)

We should detect if the current user going through the User Input flow is the only admin user who can answer questions for Site Kit—if they are, then we shouldn't show this notice at all because it's not providing useful context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "this question applies to other users" notice is only shown if more than one WordPress user can activate/use Site Kit and answer the questions in the User Input flow.

## Implementation Brief

* Update `includes/Core/Assets/Assets.php` to add a new value of site info called `totalUsers` that returns the value of the WP function `count_users()`.

https://github.com/google/site-kit-wp/blob/b530a81526f142fe2aecbe3f8e4fa694e644c17b/includes/Core/Assets/Assets.php#L651-L669

---
* Update `assets/js/googlesitekit/datastore/site/info.js` adding `totalUsers` as a new key in the resolver `getSiteInfo()`.
* Add a new selector in `assets/js/googlesitekit/datastore/site/info.js` called `getTotalUsers` that returns the new store value `totalUsers` added above.
* Update `assets/js/components/user-input/UserInputQuestionInfo.js`:
   * Get the total users using the selector we created above `const totalUsers = useSelect( ( select ) => select( CORE_SITE ).getTotalUsers() );`
   * Add a new condition to the wrapper around the text "*This question applies to the entire site and may have an effect for other users.*" if `totalUsers > 1`'

https://github.com/google/site-kit-wp/blob/b530a81526f142fe2aecbe3f8e4fa694e644c17b/assets/js/components/user-input/UserInputQuestionInfo.js#L63-L67

### Test Coverage

* Update the test `assets/js/googlesitekit/datastore/site/info.test.js` to confirm the `totalUsers` value is passed.

### Visual Regression Changes

* The UserInput VRT should be updated as this message won't be visible if the totalusers < 2.

## QA Brief

1. Use a WordPress site where you're the only admin.
2. In that circumstance, when going through the user input flow, the box stating that this question also applies to other users _should no longer_ be displayed.
3. Then, use another site where there is at least one other admin user.
4. In that circumstance, when going through the user input flow, the site-wide questions _should_ still include that box informing that this question also applies to other users.

## Changelog entry

* Only show notice about a user input question affecting other users of the site if there is more than one authorized user on the site overall.

**Comment by felixarntz** [comment]
@benbowler IB looks great, there's only one thing to change here:

> Update `includes/Core/Assets/Assets.php` to add a new value of site info called `totalUsers` that returns the value of the WP function `count_users()`.

The `get_inline_data` method is populating `_googlesitekitLegacyData`, which shouldn't be touched anymore. For new kind of basic information like this we should use `_googlesitekitBaseData` instead, exporting the value on there.

**Comment by benbowler** [comment]
Thanks @felixarntz, I've updated the IB to reference `get_inline_base_data` to pass the basic information to `_googlesitekitBaseData`.

**Comment by felixarntz** [comment]
Thanks @benbowler, IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz I was just looking this over with @benbowler and was thinking we probably don't want to add a user query to the base data since this will run on every admin page if I recall. I have some ideas what we could do but wanted to confirm that this would be something to avoid, correct?

**Comment by felixarntz** [comment]
@aaemnnosttv There is now a PR for this by @eugene-manuilov that looks solid against the ACs / IB, but I agree it would be great to avoid that. Can you share your ideas, either here or on the PR #2906?

**Comment by aaemnnosttv** [comment]
Sure thing @felixarntz – I left a review on it with my thoughts and some alternate approaches. It would be great if you could weigh in there with your thoughts before sending this back into execution to avoid additional back and forth. Assigning to you for review 👍

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

With one admin user: when going through the user input flow, the box stating that this question also applies to other users is no longer displayed. 

![image](https://user-images.githubusercontent.com/73545194/111314992-e9c5b300-869c-11eb-9f0f-66d1cc302a8b.png)

With two admin users: when going through the user input flow, the site-wide questions still inform that this question also applies to other users. 

![image](https://user-images.githubusercontent.com/73545194/111315162-11b51680-869d-11eb-8090-6a18c180c852.png)
