### ISSUE TITLE
User Input: Clarify the wording on the third question's note about "other users of this site"

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#2853]
## Feature Description

The wording on the third question in the user input flow wasn't entirely clear for several folks on the Site Kit team using the feature. It was suggested that we clarify that "site" refers more to their "WordPress site", and any other wording clarifications to be made here.

![image](https://user-images.githubusercontent.com/90871/108789204-ac747680-7571-11eb-80ec-c7e931d76902.png)

### From the original bug bash notes:

> Further clarity around this sentence may help some people who are potentially sceptical about impacting other users and therefore they are unwilling to progress through User Input as a result.

> What sort of effect does it have for other users? Could I break something for other people? If I have mycoolsite.com (running on e.g. Shopify) and mycoolsite.com/blog/ (running on WordPress with SiteKit installed), how do I know which is the entire site? As a tech person, I would think entire site is only the WordPress instance. As an editor with access to both the Shopify site and the WordPress site, I would think it applies across all of mycoolsite.com.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy for the note should be updated to: "The goals you pick will apply to the entire WordPress site: any other admins with access to Site Kit can see them and edit them in Settings."  

## Implementation Brief

* edit `assets/js/components/user-input/UserInputQuestionnaire.js`
* update the `description` prop on line 215 to the copy in the acceptance criteria above.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check that the description wording of suer input question 3 has been updated to: "The goals you pick will apply to the entire WordPress site: any other admins with access to Site Kit can see them and edit them in Settings."  

## Changelog entry

* Clarify explanation of user input responses' potential effects on other users of the site.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ Query with engineer

@Hazlitte I would like to query if `The goals you pick will apply to the entire WordPress site: any other admins with access to Site Kit can see them and edit them in Settings.` should be in the note when there are more than one administrators, rather than the question description?  

As you can see the original description is overwritten and this text appears in the description.

![image](https://user-images.githubusercontent.com/73545194/112623363-395b6a00-8e67-11eb-80d2-f5a3d8022b38.png)

How it looks now. 

![image](https://user-images.githubusercontent.com/73545194/112623038-ceaa2e80-8e66-11eb-88d4-267e1ecadc8c.png)

**Comment by aaemnnosttv** [comment]
## QA ❌ 

The IB was incorrect in its identification of the change to be made. The `description` of the question should not be changed, instead the note about the scope of the change should be updated: https://github.com/google/site-kit-wp/blob/ad6ec0d9110029af34f063df93bbd696248724e4/assets/js/components/user-input/UserInputQuestionInfo.js#L70

However, the note in the ACs is question-specific where as the notice in this component is generic, so it is not as simple as just updating the text shown in this scenario.

Assigning to @tofumatt to redefine and address.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Confirmed that the description wording of user input question 3 has been updated to: `The goals you pick will apply to the entire WordPress site: any other admins with access to Site Kit can see them and edit them in Settings.`
- Checked to make sure that the description wording displays correctly on smaller screen sizes. 

![image](https://user-images.githubusercontent.com/73545194/117824657-9455ee80-b266-11eb-96a2-103a95c013cf.png)
