### ISSUE TITLE
SiteKit disconnecting spontaneusly

### ISSUE THREAD

**Issue by vmajor** [google/site-kit-wp#2854]
## Bug Description

While editing products in the backend, after several product edits a blue notification popup appears with the following message:

"Looks like the URL of your site has changed. In order to continue using Site Kit, you’ll need to reconnect, so that your plugin settings are updated with the new URL. Reconnect"

## Steps to reproduce

1. Go to WooCommerce Products listing
2. Click on edit any product and repeat editing at least 4 to 5 products. Save the edits. (see EDIT, disconnection is time related)
3. See the error message appear on the top of the next product you edit.

## Additional Context

 - PHP Version: 7.2.24-0ubuntu0.18.04.7
 - OS: Ubuntu 18.04
 - Browser: Brave
 - Plugin Version: 1.26.0
 - Device: Desktop

Since the previously documented bug exhibiting similar behaviour was attributed to WPML perhaps this one is related to the TranslatePress plugin that we are using.

EDIT: disconnection appears to be entirely spontaneous. SiteKit disconnects even without any activity on the back end, just passing of time.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Many thanks for reaching out. As we've moved Site Kit support over to the WordPress support forums we have a process in place whereby we troubleshoot from there first before escalating to GitHub if necessary. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. Should we determine a bug which you may have already identified we can certainly re-open this issue after performing some additional checks. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.  I'm in particular curious to see if there are other administrator roles accessing your site.
