### ISSUE TITLE
Use more appropriate wording in the question help text

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#2857]
## Feature Description

Currently, the helper text that tells how many answers we can select is a bit confusing. The "only" feels like a requirement to select a specific number of answers to be able to proceed. We need to update the wording to say that a user needs to select at least one but no more than X answers. Perhaps we should use "up to X" instead of "only X".

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy of "Choose only x answer(s)" on the questions in the user input flow should start with "Choose up to..." instead of "Choose only...".

## Implementation Brief

* Update "Choose only x answer(s)" copy in `UserInputSelectOptions` per the ACs.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Using a fresh install with the tester plugin enable the userInput feature
* Setup the plugin and go through the user input flow of questions
* Check that the helper text below the answers of each question has changed to 'Choose up to'

## Changelog entry

* Update copy to clarify multiple choice behavior in user input flow.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- the helper text below the answers of each question has changed to `Choose up to`

![image](https://user-images.githubusercontent.com/73545194/110628411-f0a47f80-81dd-11eb-9642-b63111b0780f.png)
