### ISSUE TITLE
New Goals widget behaves slightly different than old one

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2858]
## Bug Description

There are a few behavioral inconsistencies between the legacy implementation of the Analytics Goals widget and the refactored version, which should be corrected in the latter.

Originally noticed in https://github.com/google/site-kit-wp/issues/2646#issuecomment-779773565

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The new Goals widget should only display the `WidgetReportZero` component if there is overall no Analytics data, but _not_ if there are simply 0 goals that have been reached, which is a common scenario and doesn't mean there is no Analytics data available.
    * The widget should reuse the same report/query that the "Unique Visitors" widget uses, simply to determine if there is no Analytics data available (i.e. if there are no users entirely). If so, it should display `WidgetReportZero`.
    * The main report for goal completions should not underly the same check, i.e. a 0 in there should still be displayed in the regular widget UI.

## Implementation Brief

* Open `assets/js/modules/analytics/components/dashboard/DashboardGoalsWidget.js`
* Inside the `useSelect` block on line 49, generate a new `totalUsers` report using the following arguments:
```js
{
	startDate,
	endDate,
	url, // see note below
	compareStartDate,
	compareEndDate,
	metrics: [
		{
			expression: 'ga:users',
			alias: 'Total Users',
		},
	],
};
```
* Note that the `url` can be generated using the `CORE_SITE`'s `getCurrentEntityURL` selector
* Refactor the `isZeroReport` check to use the new `totalUsers` report rather than the `data`. `WidgetReportZero` should be returned if there are no users, not if the `goals` data is empty.

### Test Coverage

* No new tests required; existing tests should pass

### Visual Regression Changes

* None

## QA Brief

* Go to the Site Kit dashboard and observe the 'Goals Completed' widget in the search funnel.
* `WidgetReportZero` should be displayed if there are no users (i.e. there is no data), but if there _is_ data, the sparkline should be rendered, even if `goals` data is 0.

## Changelog entry

* Fix refactored Analytics goals widget behavior to match legacy version.

**Comment by felixarntz** [comment]
IB ✅ 

@johnPhillips Going forward, please don't add a changelog entry to issues, that should typically happen before merge by the merging code reviewer. 👍

**Comment by felixarntz** [comment]
Marking as P0 since it blocks widget API rollout in the dashboard.

**Comment by aaemnnosttv** [comment]
@cole10up @wpdarren – if you don't have any Analytics accounts with zero goal completions to test with then feel free to mark this as QA:Eng but I feel like it shouldn't be hard to find a property that doesn't have any. Note that it still requires a non-zero number of [goals](https://support.google.com/analytics/answer/1012040?hl=en) created for the current view/profile (see https://support.google.com/analytics/answer/1032415) for the widget to display the number rather than the "Use goals to measure success" CTA.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ Engineer to confirm observation. 

@aaemnnosttv this is looking good but if you look at the screenshot below, the `Goals Completed` title and data does not align with the `Unique Visitors from Search`  Unsure if this is part of this issue, or if it needs a new ticket? 

Unique Visitors from Search
 
**Verified:**

On a site that has a goal created in GA, but zero goal completions, the sparkline is rendered. No CTR appears. 

![image](https://user-images.githubusercontent.com/73545194/111764032-bcb41300-88dd-11eb-846e-24cc72853df4.png)

**Comment by aaemnnosttv** [comment]
@wpdarren I think this should be a new issue. It's due to the missing change arrow since a change of zero currently results in nothing output there; not a result of this issue 👍

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 
 
**Verified:**

On a site that has a goal created in GA, but zero goal completions, the sparkline is rendered. No CTR appears. 

![image](https://user-images.githubusercontent.com/73545194/111764032-bcb41300-88dd-11eb-846e-24cc72853df4.png)
