### ISSUE TITLE
Data error in Analytics - Wordpress Site Kit

### ISSUE THREAD

**Issue by yasmineyvette** [google/site-kit-wp#2860]
I was wondering if I could get some help with an issue I encountered. My site kit all of a sudden ran into an issue yesterday where it won't load. When I go to the Site Kit dashboard, I get an error that says 'Data error in Analytics <p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p>'

I also get an error under the page speed and experience section that says 'Error: There has been a critical error on this website. 
Learn more about debugging in WordPress.'

Any help on how to fix this would be greatly appreciated. 

![site kit error 1](https://user-images.githubusercontent.com/66844716/108916155-19782280-75eb-11eb-8a06-6b9448c06abd.PNG)
![site kit error 2](https://user-images.githubusercontent.com/66844716/108916162-1bda7c80-75eb-11eb-9a69-bc759c9bd7e4.PNG)

**Comment by jamesozzie** [comment]
Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. We can reopen this GitHub issue should we determine any fix or bug to be address on the Site Kit side.

As the notice you're encountering can occur in various situations feel free to share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.
