### ISSUE TITLE
Unperformant database migration query for site with large number of users

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2870]
## Bug Description

A user [recently reported](https://wordpress.org/support/topic/takes-down-a-server-with-large-user-and-user-meta-table-and-regular-traffic/) that Site Kit was responsible for making a very slow database query (30+s) on their website that had 22k+ users. This seems to be due to the way that WP constructs meta queries that reference multiple meta keys.

## Steps to reproduce

1. Get a site with 20k+ users
2. Set the `googlesitekit_db_version` to something below `1.8.1`
3. Load wp admin
4. Observe very slow DB query

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The database migration for v1.8.1 should take well under 1s, even on sites with 10s of thousands of users and hundreds of thousands of rows in the `usermeta` table

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/3123

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Load up a site with lots of users, `wp option update googlesitekit_db_version 1.7` load a page in the admin, notice that it isn't slow to load, and that `wp option get googlesitekit_db_version` now gives you `1.8.1`.
* To see how long the time takes to run the query you can add something like `error_log( time() . ' start' );` here:
* https://github.com/google/site-kit-wp/blob/5ab69ce0024454bcc2ffe8a938ae007e856f2a80/includes/Core/Util/Migration_1_8_1.php#L107
*  and something like `error_log( time() . ' finish' );` here:
* https://github.com/google/site-kit-wp/blob/5ab69ce0024454bcc2ffe8a938ae007e856f2a80/includes/Core/Util/Migration_1_8_1.php#L129

If you do a before / after merge comparison (e.g. release 1.28.0) you can get a good idea of the expected times.

## Changelog entry

* Improve performance of potentially slow database query to migrate user data from an older version of Site Kit.

**Comment by ivankruchkoff** [comment]
The cause of this is due to the following `get_users()` query:

https://github.com/google/site-kit-wp/blob/7a9bc2e2dfd27abdfbfb370cb22b55ee63a7f061/includes/Core/Util/Migration_1_8_1.php#L242

The query run is:
```
SELECT DISTINCT wp_users.* FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id )  INNER JOIN wp_usermeta AS mt1 ON ( wp_users.ID = mt1.user_id ) WHERE 1=1 AND (
  wp_usermeta.meta_key = 'wp_googlesitekit_site_verification_file'
  OR
  mt1.meta_key = 'wp_googlesitekit_site_verification_meta'
) ORDER BY user_login ASC LIMIT 0, 20
```

Which on a site with 58k users is quite high (22s on the hardware I have available).

When we simplify the query to 
```
select distinct wp_users.* from wp_users where wp_users.ID in (
    select wp_usermeta.user_id from wp_usermeta where meta_key in ( 'googlesitekit_site_verification_file', 'googlesitekit_site_verification_meta' )
)
```
it runs in negligible speed (300ms).

The question is, @felixarntz / @aaemnnosttv do we want to go down this path of a sql query, or look for a way improving the query performance by way of `WP_User_Query`?

**Comment by aaemnnosttv** [comment]
> The question is, do we want to go down this path of a sql query, or look for a way improving the query performance by way of `WP_User_Query`?

@ivankruchkoff I think it will be more effort than it's worth to try to use `WP_User_Query` – we should just use a direct query. We do this in a few other places as well, such as reset and disconnect (pretty much anywhere we might touch all users).

> it runs in negligible speed (300ms).

That's much better than 22s 😄  – in my testing I seem to recall that it ran much faster by using the original query but only using a single join (rather than once per meta key as WP builds it). It looks like the sub-select may be a bit slower; either way, the performance would be good enough though. Can you also try the alternate query I just described on your mega site?

**Comment by ivankruchkoff** [comment]
> > The question is, do we want to go down this path of a sql query, or look for a way improving the query performance by way of `WP_User_Query`?
> 
> @ivankruchkoff I think it will be more effort than it's worth to try to use `WP_User_Query` – we should just use a direct query. We do this in a few other places as well, such as reset and disconnect (pretty much anywhere we might touch all users).
> 
> > it runs in negligible speed (300ms).
> 
> That's much better than 22s 😄 – in my testing I seem to recall that it ran much faster by using the original query but only using a single join (rather than once per meta key as WP builds it). It looks like the sub-select may be a bit slower; either way, the performance would be good enough though. Can you also try the alternate query I just described on your mega site?

Updated the IB (it's a PR), both queries are identical in performance:
```
select distinct wp_users.* from wp_users where wp_users.ID in (
    select wp_usermeta.user_id from wp_usermeta where meta_key in ( 'googlesitekit_site_verification_file', 'googlesitekit_site_verification_meta' )
)
```

```
 select distinct wp_users.* from wp_users, wp_usermeta where wp_users.ID = wp_usermeta.user_id and wp_usermeta.meta_key in ( 'googlesitekit_site_verification_file', 'googlesitekit_site_verification_meta' )
```

Since we don't need to even get_users, I've simplified it to just the 
`select wp_usermeta.user_id from wp_usermeta where meta_key in ( 'googlesitekit_site_verification_file', 'googlesitekit_site_verification_meta' )` portion

**Comment by aaemnnosttv** [comment]
> both queries are identical in performance

Great, thanks for checking 👍 

IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

DB query ran in less than 0.01s on a test site with 20k+ users.

![image](https://user-images.githubusercontent.com/1621608/115374723-c7601180-a1d5-11eb-91d0-caed84913898.png)

![image](https://user-images.githubusercontent.com/1621608/115374740-c9c26b80-a1d5-11eb-89ae-6e13bcfe09ba.png)

**Comment by zelim-khan** [comment]
My wp-admin page was not opening at all when installed the latest version site kit from wordpress plugin directory.  when i change Migration_1_8_1.php file with [this ](https://github.com/google/site-kit-wp/blob/72dd77b4c5c771f79b666fbe79049b9f1b4f2425/includes/Core/Util/Migration_1_8_1.php)  it started working but the page takes 25 seconds to load. Can you help me figure this out? I have 190k + users.

**Comment by bethanylang** [comment]
@zelim-khan Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic. Thanks!

**Comment by zelim-khan** [comment]
Hey Mrs. Beth,

There is a problem with wordpress support, I cannot register. that's why I wrote it from here. What other way can I find a solution?

**Comment by bethanylang** [comment]
@zelim-khan It's best for us to provide support via the forums. Can you please contact forum-password-resets@wordpress.org for assistance with logging in? Please let them know the exact issue that you're experiencing. Thank you!
