### ISSUE TITLE
Regression: Ad blocker detection not working consistently.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#2871]
## Bug Description

When using Site Kit when I have an Ad Blocker enabled, I expect to be warned that AdSense will not work properly (because the ad blocker blocks the AdSense API requests). Even after I have successfully enabled AdSense, if I visit the AdSense page or settings screen, I expect a user warning since the UI will not work correctly - data will not load and settings will not save.

Previously in https://github.com/google/site-kit-wp/issues/1666 we made sure Ad blocker detection stayed on even after AdSense setup was completed. Testing on the current release with uBlock Origin, however, Ad blocker  detection does not appear to be working:

ad blocker enabled, settings screen:
![image](https://user-images.githubusercontent.com/2676022/109070159-5f96ba00-76af-11eb-9ace-9e96c0baa00a.png)

connect screen:

![image](https://user-images.githubusercontent.com/2676022/109071442-f7e16e80-76b0-11eb-8d28-7d456ba24c4e.png)

what I expect to see is:

![image](https://user-images.githubusercontent.com/2676022/109071500-09c31180-76b1-11eb-9db4-55577fbf70b3.png)

## Steps to reproduce

1. Install and configure Site Kit.
2. Install an ad blocker extension.
3. Try setting up Ad Sense.
4. On a site with AdSense setup complete, try visiting settings or the AdSense screen ad blocking enabled.

Note: I noticed that ad blocker test file on my site has a hash and is named `pagead2.ads.42506bcc5b7225cd1f05.js`. My ad blocker does not block it, likely because of the hash. The file should be named `pagead2.ads.js` as it was when added in https://github.com/google/site-kit-wp/issues/1491. 

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@adamsilverstein Can you retry this again with the latest Site Kit version? We generally changed the approach to detect ad blockers to be more reliable in that release.

**Comment by aaemnnosttv** [comment]
@adamsilverstein looks like this issue was opened before we enhanced adblocker detection in #2794 which added support for uBlock Origin as well. This was also recently verified in another recent adblocker-related issue in https://github.com/google/site-kit-wp/issues/3018#issuecomment-813690400. Closing this out as fixed 👍
