### ISSUE TITLE
User Input: Preview | steps that selected other and no text was entered look strange on preview screen

### ISSUE THREAD

**Issue by fhollis** [google/site-kit-wp#2873]
When viewing the preview screen, the questions where other selected are not clear what the selection was: 

![image.png](https://images.zenhubusercontent.com/5f904e0d457f8cf7fc805b39/2771aafa-e67c-471c-928c-313907af4edd)

**Comment by fhollis** [comment]
Comment from Mariya: this should be fixed by the task above (not letting pick "Other" without entering text)

**Comment by felixarntz** [comment]
This one is already covered in #2837.
