### ISSUE TITLE
User Input: Flow should not trigger after granting additional scopes

### ISSUE THREAD

**Issue by fhollis** [google/site-kit-wp#2874]
When you're already connected, the user input flow is not "forced" upon you; by design you only see a dashboard notification that prompts you to do it instead. Only when you connect (or re-connect after disconnecting), the user input flow should be forced.

However, right now an existing user is also forced to answer the questions when they just want to activate a new module. After going through OAuth, the user input flow shows up the same way it would during the initial connection.

In this context it feels unrelated and IMO shouldn't happen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user input flow should never trigger after simply granting additional scopes. It should only be triggered when authenticating (i.e. get the first access token/refresh token after not being connected).

## Implementation Brief

Update this action:
https://github.com/google/site-kit-wp/blob/6e9e320c0aacca2745760c69c482593a9ee51462/includes/Core/Authentication/Clients/OAuth_Client.php#L737

From
```php
do_action( 'googlesitekit_authorize_user', $token_response );
```

To:
```php
do_action( 'googlesitekit_authorize_user', $token_response, $scopes, $previous_scopes );
```
The parameter $scopes already exists several lines up.

Get $previous_scopes with this:
https://github.com/google/site-kit-wp/blob/6e9e320c0aacca2745760c69c482593a9ee51462/includes/Core/Authentication/Clients/OAuth_Client.php#L416

Update our hook call `googlesitekit_authorize_user` in
https://github.com/google/site-kit-wp/blob/6e9e320c0aacca2745760c69c482593a9ee51462/includes/Core/Authentication/Authentication.php#L296 to use the $previous_scopes parameter and to check whether or not `$previous_scopes` is empty before calling `$this->require_user_input();`

### Test Coverage

* Add an integration test to ensure we don't need to go through user_input flow when it hasn't yet been completed, the site is already connected and we're enabling a new module:

https://github.com/google/site-kit-wp/blob/9ec8c986bce621bc44071674c0475c6964db14dd/tests/phpunit/integration/Core/Authentication/AuthenticationTest.php#L332

### Visual Regression Changes

* 

## QA Brief

* Enable user input feature.
* Connect a new site and ensure you are taken to the user input page `/wp-admin/admin.php?page=googlesitekit-user-input`.
* Now reset your site.
* Disable user input feature.
* Connect the new site and ensure you are *NOT* taken to the user input page (as the feature is disabled).
* Enable user input feature.
* Connect another module, e.g. analytics.
* After going through oauth flow (https://accounts.google.com/signin/oauth/consentsummary...), when you return back to sitekit, ensure that you are *NOT* taken to the user input page (even though the feature is enabled).

## Changelog entry

* Ensure that the user is not sent to the user input flow when granting additional scopes after being already authenticated, even if submitting the user input response is still required.

**Comment by aaemnnosttv** [comment]
> In the following file, add another conditional check to ensure we aren't already verified:
> ...`$this->verification->get()`

@ivankruchkoff – verification state is about the user's verification as having sufficient access to the site as provided by the Site Verification API and is not related to authentication with Google APIs which is what the ACs are referring to here.

We need to probably make a change in `OAuth_Client::authorize_user` to either:
* Capture whether or not the user had an access token or not before the new one is set and pass this through the `googlesitekit_authorize_user` action
* Introduce a new action that only fires when receiving an access token when the user didn't previously have one

The first option seems like the simpler change as the action introduced by the second might be a bit overly-specific. Would be good to get @felixarntz 's thoughts on this as well.

**Comment by felixarntz** [comment]
@aaemnnosttv @ivankruchkoff Another alternative would be to introduce another action before the user receives the authorization token in WordPress, e.g. a `googlesitekit_pre_authorize_user` action. This would allow us to hook into it, check if the user has no access token, and only then hook into `googlesitekit_authorize_user`.

I think passing whether an access token previously existed with the existing action is also overly specific, just in another way; so I think we should be passing something that somehow either fits with the already existing `$token_response` parameter, or fits into the general purpose of `googlesitekit_authorize_user`.

Maybe we could manually "assemble" the previous token response associative array from the user options currently stored (i.e. create the array with `access_token`, `expires_in`, `created`, `refresh_token`, and `scope`). If none exists, we could pass `null`, or an empty array. That way it would fit well with the existing parameter, and it would allow the hooked in function to make all sorts of assessments about what was updated. For example, it could also check which scopes were added or removed compared to before. I.e. the signature would be
```
do_action( 'googlesitekit_authorize_user', $token_response, $previous_token_response );
```

Alternatively if we don't wanna fiddle with manually re-creating that data, we could put the focus only on scopes, which is the main reason why `googlesitekit_authorize_user` fires not only when initially authorizing. We could pass the new scopes and existing scopes arrays as new parameters with the action (if we do that, we should sort them both IMO, to make the comparison more intuitive). I.e. the signature would be
```
do_action( 'googlesitekit_authorize_user', $token_response, $scopes, $previous_scopes );
```

With the above, the hooked-in function could simply check if `$previous_scopes` is empty - if so, it is the _first_ authorization.

Now that I've dumped all my brainstorm here, I'm personally leaning towards the latter, passing the new and previous scopes array with the action.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

After going through the steps in the QAB - and on the last step, through the Oauth flow, when you return back to Site Kit you are not taken to the user input page (even though the feature is enabled).

![image](https://user-images.githubusercontent.com/73545194/113298718-b33f9780-932e-11eb-9b9e-d95edd85d47f.png)
