### ISSUE TITLE
User Input: Update copy to "Choose up to 3 answers"

### ISSUE THREAD

**Issue by fhollis** [google/site-kit-wp#2875]
You don't have to choose 3, if you don't want to so the copy should read: "Choose up to 3 answers"
![image.png](https://images.zenhubusercontent.com/5f904e0d457f8cf7fc805b39/db2b6847-eef1-4b45-b9fc-fcbcfbb4ec6b)

**Comment by felixarntz** [comment]
This is already covered via #2857.
