### ISSUE TITLE
Add tracking events for PageSpeed widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2877]
There are a few new tracking events that should be implemented for the PageSpeed widget.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* GA tracking events for interacting with the PageSpeed Insights widget should be added:
    * `widget_view`: should be triggered **once** during page lifecycle when the widget becomes visible in the viewport, e.g. when the user scrolled to it
    * `default_tab_view`: should be triggered without user interaction, based on which tab is rendered by default (event label should be either "field" or "lab")
    * `tab_select`: when clicking the "Field" or "Lab" tab (event label should be either "field" or "lab")
    * `stack_pack_expand`: when opening a stack pack recommendation in the accordion (event label should be the audit ID)
* The event category should be `pagespeed_widget` for all of them

## Implementation Brief
* Install the `react-intersection-observer` package as a dependency which will allow us to know when an element is visible on the page.
* Using `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js`,
	* Use the `useEffect` and `useInView` hooks as described here [https://github.com/thebuilder/react-intersection-observer/blob/master/docs/Recipes.md#track-impressions] to track when the widget is visible within the viewport. If the widget is visible, i.e `inView` is `true`, call the `trackEvent` function with the following parameter:
		* action: `widget_view`
	* Use the same `useEffect` hook as in the previous bullet point to also track which tab is rendered by default. The `trackEvent` function must be called with the following parameters:
		* action: `default_tab_view`
		* label: `field` or `lab` depending on the selected tab. The latter can be obtained via the `dataSrc` variable which needs to be stripped of the `data_` prefix because the values can be `data_lab` or `data_field`.
	* Update the `updateActiveTab` function to call the `trackEvent` function with the following parameters:
		* action: `tab_select`
		* label: `lab` if the "Lab" tab has been selected or `field` if the "Field" tab has been selected.
* Using `assets/js/components/Accordion.js`,
	* add 2 new props:
		* `onOpen`: callback when the accordion item is opened.
		* `onClose`: callback when the accordion item is closed. Though it will not be used in this ticket, it can be helpful for other use cases later down the road.
	* Update the `toggleAccordion` function to call the `onOpen` and `onClose` props based on the `isActive` variable.
* Using `assets/js/modules/pagespeed-insights/components/common/Recommendation.js`,
	* Create a new function, `handleOnOpen` which should call the `trackEvent` function with the following parameters:
		* action: `stack_pack_expand`
		* label: the value of the `auditID` prop.
	* Add the `onOpen` prop to the `Accordion` component which should take the value of `handleOnOpen`.
* The `trackEvent` function used in the above bullet points can be imported from from `assets/js/util/tracking`.
* The category value for the `trackEvent` function used in the above bullet points should be `pagespeed_widget`.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief
* Enable Tracking in Settings
![image](https://user-images.githubusercontent.com/31818/114040209-74609300-9894-11eb-9ef0-8a0e3679fc46.png)
* Install the Google Analytics Debugger Chrome extension: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna
* Open the browser console and make sure the requests are being fired with the appropriate parameters. Check the AC for the parameters.

## Changelog entry

* N/A

**Comment by asvinb** [comment]
@felixarntz In the AC, it's not mentioned what should be the value for the `category` parameter of `trackEvent` function. I assumed it to be `dashboard-pagespeed-insights-widget` in the IB, but can you confirm which value to use? Thanks!

**Comment by felixarntz** [comment]
@asvinb Excellent - IB ✅ 

Thanks for catching the missing event category, I forgot to add it. It should be `pagespeed_widget`, I've updated both the ACs and your IB with it.

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- GA tracking events for interacting with the PageSpeed Insights widget should be added:

`widget_view` triggered once during page lifecycle when the widget becomes visible in the viewport.

![image](https://user-images.githubusercontent.com/73545194/114710076-e850de80-9d5f-11eb-9eda-fd8b6423dae2.png)

`default_tab_view` triggered without user interaction, based on which tab is rendered by default.

![image](https://user-images.githubusercontent.com/73545194/114710123-f141b000-9d5f-11eb-88f5-a0433441b8d0.png)

`tab_select` triggered when clicking the "Field" or "Lab" tab (event label is either "field" or "lab")

![image](https://user-images.githubusercontent.com/73545194/114710163-fe5e9f00-9d5f-11eb-9046-c029d2c5732c.png)

`stack_pack_expand` triggered when opening a stack pack recommendation in the accordion.

![image](https://user-images.githubusercontent.com/73545194/114710403-4251a400-9d60-11eb-94d3-dfa0ae9461d8.png)

The event category is `pagespeed_widget` for all of them
