### ISSUE TITLE
Long drop-up menus may have some unselectable items

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2885]
## Bug Description

Our `Select` component will automatically show its select options in a "drop-up" menu rather than a dropdown based on its position in the viewport (and probably the number of items within).

This has the potential to result in a situation where some items are un-click/select-able because they are behind the main Site Kit header element.

## Steps to reproduce

This is not specific to any module but is probably most like to affect Analytics, due to the several `Select` components that are present on the setup and settings views.

1. Authenticate with a Google account that has many Analytics accounts/properties (or just create as many as needed)
2. Toggle open the select menu for the entity with a large number of options
3. See the menu flipped up and partially under the header

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/109328735-76c9d900-7862-11eb-999f-eca2f669b384.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Open Site Kit menus should not be obstructed by the main header element that spans across the top of all Site Kit screens  

## Implementation Brief
* Using `assets/sass/vendor/_mdc-menu-surface.scss`,
	* Increase the `z-index` for the `.mdc-menu-surface--open` class name from `11` to a value higher than `12` since the Site Kit header has a `z-index` of `12`.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* Authenticate with a Google account that has many Analytics accounts/properties
* Go to the analytics tab
* Toggle open the select menu for the entity with a large number of options
* See the menu flipped up
* Observe it is now on top of the header

## Changelog entry

* Fix a bug where select menu components could be partially covered by the Site Kit header making some items unclickable.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
QA Update: Fail ❌ 

@danielgent initially, I was going to pass this and then I noticed something a little quirky! 😄  When the page initially loads, the menu on toggle flips up to the top.  If you scroll slightly scroll down the page and then toggle the menu, it flips down.  Here's a screencast to show you this in action. 

Also, I noticed somethings it's a little inconsistent depending on where you click on the menu to open it. 

https://user-images.githubusercontent.com/73545194/115701267-83991380-a35f-11eb-9122-ab73058f1c08.mov

**Comment by aaemnnosttv** [comment]
@wpdarren that's expected. The menu will open up or down depending of the position of the menu in the viewport. This issue is specific to making sure the header doesn't cover the menu when it drops up which seems to be the more common behavior.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- When the user toggles open the select menu, the menu flips up and is now on top of the header.  The header doesn't cover the menu. This was tested on desktop and mobile. 

![image](https://user-images.githubusercontent.com/73545194/115703236-c956db80-a361-11eb-94c7-d66789e4da93.png)
