### ISSUE TITLE
User input responsive enhancements

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2886]
## Bug Description

This is a catch-all issue for responsive enhancements for the user input flow, particularly on viewports smaller than desktop.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/109336000-7550de80-786b-11eb-8823-3a92c72a0a8f.png)
_Right alignment of blurb and buttons is a bit odd at this viewport size_

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On extra narrow viewports:
    * The user input note "You can always edit..." should span the full width instead of being right-aligned.
    * <del>The button group at the bottom (e.g. "Back" and "Next") should be left-aligned instead of being right-aligned.</del>

## Implementation Brief
* On question 5, remove margin left from `.googlesitekit-user-input__note` which should align the "Separate with commas or the Enter key" text with the input text above it.
* On the preview screen, set the margin left to `0`, and set the width to `100%` for the `.googlesitekit-user-input__preview .googlesitekit-user-input__question-instructions--notice` class name.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief
See main branch (before my changes) https://google.github.io/site-kit-wp/storybook/master/?path=/story/user-input--userinputapp

See my changes on develop (https://google.github.io/site-kit-wp/storybook/develop/?path=/story/user-input--userinputapp) and ensure that the:
* Fifth screen: "Separate with commas" text is left-aligned
* Final (preview) screen: "You can always edit" text  is left-aligned

## Changelog entry

* Update user input styles to fix visual issues on small devices

**Comment by tofumatt** [comment]
@asvinb Those mockups look good to me. Given the "Edit" button is the only touch-target it seems fine to me. 👍🏻

**Comment by asvinb** [comment]
Thanks @tofumatt . @aaemnnosttv Can you check the IB and let me know what you think?

**Comment by felixarntz** [comment]
@asvinb I agree the font sizes here aren't perfect, but reducing them partly doesn't resolve the issue. For example, in your screenshot with reduced font sizes it now is weird that the question font size looks smaller than the one for the explanation above.

Let's not change font sizes in this issue - can you open another one to explore that please?

**Comment by asvinb** [comment]
@felixarntz Ticket created: https://github.com/google/site-kit-wp/issues/3016 :)

**Comment by asvinb** [comment]
Progress bar alignment will be fixed in #2985

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Engineer clarification ⚠️ 

@danielgent when I look at the main and develop storybook screens:

- Final screen: "You can always edit" text looks the same on both main and develop. I could not see any difference. 

Is this how it should look? 

![image](https://user-images.githubusercontent.com/73545194/115030057-3cdb9180-9ef9-11eb-8a61-faf0c3aec6a8.png)

Also, when I updated my test site to `develop` branch, I could not see either of these changes. 

Should this be merged?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

With small screen size (mobile devices): 

- Fifth screen: "Separate with commas" text is left-aligned - [Screenshot](https://user-images.githubusercontent.com/73545194/115031051-54ffe080-9efa-11eb-94be-48d866fa08e4.png)
- Final (preview) screen: "You can always edit" text is left-aligned  - [Screenshot](https://user-images.githubusercontent.com/73545194/115031090-5e894880-9efa-11eb-8c2d-98e16a395f5e.png)
- Also confirmed the storyboard screens differences main and develop for smaller screen sizes.
