### ISSUE TITLE
Analytics view selection not preserved by useExistingTagEffect for properties with multiple views

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2888]
## Bug Description

The `useExistingTagEffect` in Analytics will set/select the account and property for an existing detected Analytics property, either from a tag on the page or GTM container tag. Due to logic in the `selectProperty` action which clears the current profile (view), this has the effect of selecting the first profile whenever Analytics settings are edited.

https://github.com/google/site-kit-wp/blob/5268ae9f21e589a8c3104a4d98f63b372a88a916/assets/js/modules/analytics/hooks/useExistingTagEffect.js#L78-L88

The presence of an existing tag forces the detected account and property to be selected, but the view can always be changed since this is specific to reporting only.

For properties with multiple views, this will cause the chosen view to be changed when Analytics settings are edited if the previously selected view is any one other than the first.

### Pre-Setup ###
1. Find a UA tag that your account has access to, you can do this by setting up with analytics module and then looking at the page source for the following `gtag("config", "UA-` and noting that `UA-XXXXXXXX-X` tag.
2. Setup a new view for your tag that is not `All Web Site Data` for the analytics tag that you had just noted.
<img width="227" alt="Screen Shot 2021-04-19 at 10 18 31 AM" src="https://user-images.githubusercontent.com/373931/115277112-b9888e80-a0f8-11eb-8f10-fc33b66a9f0c.png">

### Repro ###
See the video attached:

1. Enable sitekit tester plugin, and add the UA tag from above to `Place Analytics existing tag` in the settings page `/wp-admin/admin.php?page=googlesitekit-tester`
2. Disconnect Analytics if it's already connected, and open the `Set Up Analytics` link
3. Pick your new view, save it.
3. Edit Analytics settings again.
4. Notice the first view is now selected `All Web Site Data` in the dropdown and "Configure Analytics" is blue indicating settings have changed and saving is possible, if you pick the view you created, the `Configure Analytics` button will go grey as you are no longer changing the setting.

https://user-images.githubusercontent.com/373931/115278119-ee491580-a0f9-11eb-900d-e7833d70acf8.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The presence of an Analytics tag should not change the selected view when the detected account and property matches the currently configured values

## Implementation Brief

* Inside `assets/js/modules/analytics/datastore/properties.js`, before line [177](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/properties.js#L177), use the `.getProfileID` selector to cache the existing profile ID in a variable, e.g. `existingProfileID`, before it is cleared.
* Line [189](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/properties.js#L189) is where the first matching profile that is attached to this property is selected, so we need to refactor this with some additional logic:
  * First find the previously selected profile by looping through `profiles` and returning the profile with an ID that matches the `existingProfileID` we cached earlier, for example:
  ```js
  const existingProfile = profiles.find( ( { id: ID } ) => ID === existingProfileID );
  ```
  * If there is a profile that matches, dispatch `.setProfileID` with the matching profile's ID
  * If there is no matching profile, revert to the previously existing logic at line 189, where a `matchedProfile` is found and set:
  ```js
  const matchedProfile = profiles.find( ( { webPropertyId } ) => webPropertyId === propertyID ) || { id: PROFILE_CREATE }; // eslint-disable-line sitekit/acronym-case
  registry.dispatch( STORE_NAME ).setProfileID( matchedProfile.id );
  ```

* Add new test cases to `assets/js/modules/analytics/datastore/properties.test.js` to cover this new logic. In the scenario where there is currently an existing `profileID` selected: 
  * if the pre-existing profileID has a `webPropertyId` that matches the `propertyID`, then this profile should be set
  * if not, but if there is another profile that has the correct `webPropertyId`, then that profile should be set
  * if there are multiple other profiles with the correct `webPropertyId`, then the first matching profile should be set
  * otherwise, in the case that a profile doesn't yet exist for this property, then a profile with the ID `PROFILE_CREATE` should be set

### Test Coverage

* New tests as described above; existing tests should pass

### Visual Regression Changes

* When editing Analytics settings when there is an existing tag with multiple views, if a vew was previously selected, it will appear in the views dropdown. 

## QA Brief

* Follow the steps to reproduce above. 
* Ensure that when you go back to the setup analytics screen that your previously selected view is in the dropdown, rather than the first view. The video in the repro steps shows the bug and you shouldn't be able to get that to occur.
 
## Changelog entry

* Fix a bug that could cause the first profile to be selected in Analytics Settings when an existing tag was detected.

**Comment by tofumatt** [comment]
That cached variable might need to be a piece of component state or something, but the particular implementation doesn't really matter. Sounds good!

IB ✅

**Comment by aaemnnosttv** [comment]
@johnPhillips @tofumatt - as a bug fix, let's be sure to add/update Jest coverage for `useExistingTagEffect` accordingly.
Would you please update the IB to include this? I would expect the estimate to increase as a result as well which is fine.

**Comment by johnPhillips** [comment]
@tofumatt @aaemnnosttv I've added instructions around updating the test coverage and increased the estimate accordingly. Let me know if I missed anything?

**Comment by aaemnnosttv** [comment]
@johnPhillips one thought, otherwise LGTM!

>   * if the pre-existing profileID has a `webPropertyId` that matches the `propertyID`, then this profile should be set

Maybe just a semantic difference, but if the current profile is for the selected property, the profile should be unchanged, which is slightly different than being set (potentially again).

**Comment by johnPhillips** [comment]
@aaemnnosttv My mental model of this was that the profileID was emptied...

https://github.com/google/site-kit-wp/blob/d0d782517a334a89070d1db9044f259ad799281d/assets/js/modules/analytics/datastore/properties.js#L177

...and then either the `defaultProfileId ` is used to select a profile, 
https://github.com/google/site-kit-wp/blob/d0d782517a334a89070d1db9044f259ad799281d/assets/js/modules/analytics/datastore/properties.js#L180-L183

or the first one in the stack was used once the property ID was set. 

https://github.com/google/site-kit-wp/blob/d0d782517a334a89070d1db9044f259ad799281d/assets/js/modules/analytics/datastore/properties.js#L189-L190

This would mean that the profile ID would always need to be set again. I now wonder whether I'm missing something. You mean because the profiles resolver will re-select it? 🤔

**Comment by ivankruchkoff** [comment]
Followed the IB, but having some difficulty repro-ing the original issue.

**Comment by johnPhillips** [comment]
Hey @ivankruchkoff this took me a while to get working as well. 
I needed to add my existing analytics tag to get it working:
- Go to settings / analytics and copy the property name (e.g. `UA-12345678-3`)
- Go to tester settings and paste it into the 'place existing analytics tag' field.

Let me know if that helps - if that's the issue we should add it to the QAB so it doesn't trip anyone else up.
If that doesn't help you might need to ask @aaemnnosttv

**Comment by ivankruchkoff** [comment]
Thanks @johnPhillips  Instructions helped, updated the QA / repro instructions.

**Comment by ivankruchkoff** [comment]
I'm seeing this fail consistently in GH e2e, but not locally:
` PASS  tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js (56.962s)` (locally)

GH:
```
FAIL specs/modules/analytics/setup-with-account-no-tag.test.js (21.685s)
  ● setting up the Analytics module with an existing account and no existing tag › using Proxy auth › pre-selects account and property if the tag matches one belonging to the user

    TimeoutError: Element .mdc-select__selected-text (text: "/test profile z/i") not found

      waiting for function failed: timeout 500ms exceeded


Test Suites: 1 failed, 29 passed, 30 total
```

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

- Able to reproduce the bug. 
- The new view is selected when I edit the Analytics settings, rather than the first view.
- Also confirmed that when you select another view, the save button is active and I am able to change it. 
- Unable to recreate the bug on `develop` branch

![image](https://user-images.githubusercontent.com/73545194/116570916-87e6a300-a902-11eb-9db9-3e7c6f9cfd06.png)
