### ISSUE TITLE
Couldn't create project:  have a problem when installing the plugin 

### ISSUE THREAD

**Issue by khaled77889** [google/site-kit-wp#289]
## Bug Description
Couldn't create project
warning
field [project_id] has issue [project_id contains invalid characters]

## Screenshots
<a href="https://imgur.com/2qP3ZE5"><img src="https://i.imgur.com/2qP3ZE5.jpg" title="source: imgur.com" /></a>

 - PHP Version: 7.2.19 (Supports 64bit values)
 - OS:  cPanel
 - Browser [chrome]
 - Plugin Version 1.0.0-beta.1.0.1
 - Device: [PC]
- Website URL https://review-plus.com/

I have seen many topics that have the same problem
I tried to try some solutions
- I used incognito and did not succeed with me
- I tried another website and encountered the same problem
- I deleted the plugin and added it again and I deleted the cache files for the Google Web site and I re-experience and faced the same problem
- I also tried another web browser

what should I do?
Are there other solutions?

Noticeable
The site uses Arabic (RTL)
Is language the cause of the problem?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@khaled77889 Thanks for reporting. Can you please try this workaround and let me know if you manage to get to the next stage?

- Close the "Couldn't create project" window
- In the address bar of your window paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
- Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
- Press enter, with your cursor in the address bar (as if you are visiting that URL)
- Press the "GET OAUTH CREDENTIALS" button
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

Please let me know if that works for you.

**Comment by khaled77889** [comment]
In fact, I've tried a lot to solve this problem
I found this comment on another issue and I used it and did not work with me
But I tried to look a lot at the case and I used this solution again but I added two new things
In fact, I do not know exactly how the problem was solved, but I'll tell you what you did, maybe someone else would benefit
- First I added the site to Domain verification
<a href="https://imgur.com/Y4nlrTo"><img src="https://i.imgur.com/Y4nlrTo.jpg" title="source: imgur.com" /></a>

Secondly, I found the URL pointing to the error has a different URL than that found in the Authorized redirect URI

<a href="https://imgur.com/qsFyJ74"><img src="https://i.imgur.com/qsFyJ74.jpg" title="source: imgur.com" /></a>

The URL was review-plus.com/?oauth2callback=1
I modified it to review-plus.com?oauth2callback=1
And it worked 👍 

Thanks jamesozzie for your reply

**Comment by jamesozzie** [comment]
@khaled77889 Thanks for the info, very useful indeed. Did you create your own OAuth credentials or use the Site Kit generated credentials?

**Comment by khaled77889** [comment]
I use the Site Kit generated credentials
1- i have use https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com

2- and Replace the yourwebsitecom and also http://yourwebsite.com with my site details.
As you explained

3- and also deleted the cache for Google and my website
4- and modified the URL as explained above

But I have applied all these steps before adding the code in the plugin in my website

**Comment by jamesozzie** [comment]
@khaled77889 Are you encountering the same issue? You mentioned you had it resolved previously, if so I will close the issue.

**Comment by moaid500** [comment]
I used to have same issue the past and fixed with this website help 
[قصة عشق](https://bare-eq.life/)
