### ISSUE TITLE
Analytics Account Sign Up page is cut off at bottom when a user setup an account on Analytics

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#2891]
## Bug Description
Analytics Sign Up bottom page cut off when user lands from the Site Kit. User can't proceed next while setting up account.
## Steps to reproduce

1. Go to Analytics Settings Page
2. Click on new account
3.  Go to the Analytics page & you'll see bottom page is cut off.

## Screenshots

Please see [recording](https://www.loom.com/share/25be700e342744d08d7ec3cdcd211e29) while settings up account through Site Kit.

Its working fine when we try to setup through Analytics Service dashboard. Please see recording [here](https://www.loom.com/share/30abd33ce54e44f7bd7fdc3d5be12bc0).

## Additional Context

 - PHP Version: 7.4.14
 - OS: [e.g. iOS]: Linux
 - Browser [e.g. chrome, safari]: Chrome 88.0.4324.190
 - Plugin Version: 1.27.0

User reported issue on [Site Kit support page](https://wordpress.org/support/topic/analytics-page-is-cut-off-at-bottom-where-submit-button-is-located/):

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@adamsilverstein Shouldn't this have been fixed by now? I thought they already took care of it. Maybe this issue is no longer relevant, checking with you.

**Comment by bethanylang** [comment]
@felixarntz Thanks for checking on this - I seemed to remember it being fixed, too, but I couldn't find an associated ticket.

**Comment by adamsilverstein** [comment]
This has been resolved upstream by the Analytics and no longer occurs in my testing.  I ran thru creating an account again and the TOS screen works as expected, seems like they have simplified it a bit as well (it is shorter). 


https://user-images.githubusercontent.com/2676022/110681952-9da7d980-8197-11eb-994c-31d4d6d9351a.mp4

Closing as resolved. If this issue is recurring, feel free to re-open.
