### ISSUE TITLE
Use icon for user input keyword list item delete button

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2896]
## Feature Description

The keyword bubble items on step 5 of the user input flow currently use the character `x` in the close/delete button. This would be better to use a real icon. It's important that the colors are preserved though.

| Hover | Focus |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1621608/109538760-243e2600-7ac9-11eb-9fbd-0cebd6d3076d.png) | ![image](https://user-images.githubusercontent.com/1621608/109539134-a2023180-7ac9-11eb-802e-0fd9fd522d7a.png) |

Looking at the icons available via `@wordpress/icons`, `cancelCircleFilled` or `closeSmall` should be used

![image](https://user-images.githubusercontent.com/1621608/109539350-e097ec00-7ac9-11eb-96c5-6316fddf4fdd.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The colors for the search term bubble text and close icon should be reverted to be what they were before, see screenshots above.

## Implementation Brief
* Using `assets/sass/config/_variables.scss`,
	* Add a new variable `$c-user-input-color` which should be set to `$c-denim`.
* Using `assets/sass/components/user-input/googlesitekit-user-input-controls.scss`,
	* Set the `min-width` for `.googlesitekit-user-input__text-option button` to `35px` so that the is enough room for the icon dimensions to match the designs.
	* Set the SVG within `.googlesitekit-user-input__text-option button` to have a height and width of `11px` respectively. Update the `fill` value for the `path` to use `$c-user-input-color`
	* Add the following selector `.mdc-text-field .mdc-text-field__input` within `.googlesitekit-user-input__text-option` where the color is set to `$c-user-input-color` and the `font-weight` is set to `500`.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* navigate to user input question 5/5 and enter a couple of terms
* check that the close icon `button` has a `min-width` of  `35px`
* check that the close icon `svg` has a height of `11px` and a width of `11px`
* check that the close icon `svg` `fill` has the color `#1967d2`
* check that the text field `input` has the color `#1967d2` and `font-weight` of `500`

## Changelog entry

* Fix low-contrast color for keyword bubbles in the user input flow.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv I think we don't need this ticket anymore because the icon for the delete button has been updated in #2842 

![keywords](https://user-images.githubusercontent.com/873049/110797324-a248bc80-8281-11eb-91d5-0b990dcc4c6e.png)

**Comment by aaemnnosttv** [comment]
@eugene-manuilov it may be that we don't need it although Aaron was specific about preserving the colors though which seem to be a bit different now. Did we decide to change it?
cc: @felixarntz

**Comment by felixarntz** [comment]
@aarondruck Can you check the above? https://github.com/google/site-kit-wp/issues/2896#issuecomment-796839745 has a screenshot on what the bubbles currently look like - is that good to go or do we need to make any additional changes?

**Comment by aarondruck** [comment]
We should keep the bubble and text colors the same as before.  It was for contrast/accessibility.

**Comment by felixarntz** [comment]
Updated ACs, back to IB.

**Comment by tofumatt** [comment]
For clarity, the button in question is here: https://github.com/google/site-kit-wp/blob/857b07eae65ad4f5ca367c4f8eccd48419a17411/assets/js/components/user-input/UserInputKeywords.js#L137-L141 🙂 

IB looks good!

IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the close icon button has a min-width of 35px  - [Screenshot](https://user-images.githubusercontent.com/73545194/112627541-b9380300-8e6c-11eb-9284-acf9e11a8a59.png)
- Verified that the close icon svg has a height of 11px and a width of 11px. - [Screenshot](https://user-images.githubusercontent.com/73545194/112627527-b4734f00-8e6c-11eb-8322-1921afa2dfb6.png)
- Verified that the close icon svg fill has the color #1967d2  - [Screenshot](https://user-images.githubusercontent.com/73545194/112627555-bd642080-8e6c-11eb-8806-8c63d4ff0709.png)
- Verified that the text field input has the color #1967d2 and font-weight of 500 - [Screenshot](https://user-images.githubusercontent.com/73545194/112627570-c1903e00-8e6c-11eb-9225-bd1b527ece72.png)

**Comment by wpdarren** [comment]
@aaemnnosttv @felixarntz since this has passed QA, unsure if this needs to be included in master branch if it's going to be included in this sprint?

**Comment by aaemnnosttv** [comment]
@wpdarren not all issues for a sprint will go in the release for the sprint so it's okay that this is only in develop now. It should be tagged with the next release though since it is merged and won't be included in 1.29 (cc @tofumatt)

**Comment by felixarntz** [comment]
@tofumatt @eugene-manuilov ^ the above is something to look out for in the future. Issues that are not tagged with a release can typically have their PRs merged into `develop` as long as we're still far away enough from the release, unless there are special circumstances that would prevent that. It's important though to add the release to those issues once the PR is actually merged. I did that for this one but please look out for that in the future.

Once we get to the second week of a sprint and finalizing the release and what goes in, that is where we should be more conservative on what to merge, especially bigger PRs. If in doubt, either ping or bring up the issue in a meeting so we can review together whether it should be merged yet.
