### ISSUE TITLE
Clarify requirement of "Other" value when choice is selected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2897]
## Feature Description

It isn't currently obvious that the text input for a choice of "Other" is required to be a valid choice. This should be visually enhanced, possibly using a placeholder and or an added validation state on the input.

![Kapture 2021-03-01 at 20 39 51](https://user-images.githubusercontent.com/1621608/109542872-50a87100-7ace-11eb-9cd6-b2011e4a90e3.gif)

[Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/user-input--userinputapp)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When clicking "Other", the cursor should automatically focus on the input field afterwards so that it is visually highlighted (with the cursor flashing).

## Implementation Brief

* edit the `/assets/js/components/user-input/UserInputSelectOptions.js`
* add a hidden`label` to the `Input` component using the `visually-hidden` WordPress CSS class
* add a React `ref` to the `Input` component
* modify the `onClick` function to check if the 'other:' checkbox has been checked.  If it is checked set the `focus` on the `ref` of the input component.
* If `onClick` the checkbox is not checked, disable the `ref` of the input component.

The behaviour should be:
* 2 items selected, neither of which is "Other": "Other" text input is disabled; no interaction/click handling, etc.
* 2 items selected, one of which is "Other": "Other" text input is enabled.
  * If the user deselects the "Other" checkbox, do not modify user focus.
* 1 or fewer items selected, one of which is "Other": "Other" text input is enabled.
  * If the user deselects the "Other" checkbox, do not modify user focus.
* If the user selects the "Other" checkbox, change the user focus to the "Other" text input.
* If the user selects the "Other" text field directly and then enters text into the input, automatically check the "Other" checkbox. (If the user focuses then blurs the input without typing, do not activate the "Other" checkbox)

### Test Coverage

* No change to tests

### Visual Regression Changes

* No visual regressions

## QA Brief

* Use a fresh install of WordPress
* Enable userInput with the tester plugin
* Go through the user input flow of questions
* On questions with Radio buttons:
  *  check that the other text input field is always enabled
  *  check that if the other radio button is not checked typing in text input field sets it to checked
* On questions with Check boxes:
  *  check that typing in the other text input field set the other checkbox to checked
  *  check that the other text input field is disabled when the maximum number of checkboxes are selected and one of them is not the other checkbox

## Changelog entry

* Automatically focus the "Other" text input upon selecting the "Other" option in a list of radio buttons or checkboxes.

**Comment by aaemnnosttv** [comment]
@felixarntz @tofumatt I helped @Hazlitte a bit with this being his first IB so it would be great if one of you would take the review 👍

**Comment by tofumatt** [comment]
Approach here looks good, but I have a few notes. 🙂

1. There was mention of adding a `placeholder` attribute here, that might be helpful. Relatedly, I noticed there's no `label` attribute for the "Other" input:

<img width="651" alt="Screenshot 2021-03-04 at 14 03 42" src="https://user-images.githubusercontent.com/90871/109975351-7746f180-7cf2-11eb-827d-34bbda8bde78.png">

That's not great anyway, but now that we're going to move focus to that input after user interaction with another element, we should label it so screenreader users aren't confused about where they're entering text into after clicking a checkbox. It can (and should) be a visually hidden label, but a label will make the proposed interaction less confusing.

2. Let's not blur focus artbitrarily:

> If `onClick` the checkbox is not checked, blur the `ref` of the `Input` component.

We shouldn't be blurring user focus, especially to nothing, after a click event elsewhere. That will be very confusing for a screenreader user as clicking on an item will entirely remove their focus on the page. I'm not sure why this is required here anyway, so I think it can be safely removed.

----

Once these are addressed in the IB I think we're good 🙂

**Comment by Hazlitte** [comment]
Thanks @tofumatt, I have updated the brief from your notes.

**Comment by tofumatt** [comment]
This still mentions

> If `onClick` the checkbox is not checked, blur the `ref` of the input component.

I think what this means is that if the text field is clicked when the "Other" checkbox isn't checked, then blur the input selection so the user can't type in it. But it'd be better to set the `<Input />`'s `disabled` prop to be `true` when the "Other" checkbox isn't activated and there are already two active selections elsewhere. That way the user can't interact with the text input when they aren't allowed to activate it. But we should never be blurring the user's focused element, especially if we aren't changing focus to something else. Blurring the user's input will result in a confusing, loss-of-place experience for keyboard users and screenreader users.

Essentially the behaviour should be:

* **2 items selected, neither of which is "Other":** "Other" text input is disabled; no interaction/click handling, etc.
* **2 items selected, one of which is "Other":** "Other" text input is enabled.
  * If the user deselects the "Other" checkbox, do not modify user focus.
* **1 or fewer items selected, one of which is "Other":** "Other" text input is enabled.
  * If the user deselects the "Other" checkbox, do not modify user focus.
* **1 or fewer items selected, "Other" is not selected:** "Other" text input is enabled.
  * If the user selects the "Other" checkbox, change the user focus to the "Other" text input.
  * If the user selects the "Other" text field directly, automatically check the "Other" checkbox.

**Comment by Hazlitte** [comment]
@tofumatt Everything you have added makes great sense, thank you.  The one point that confuses me is '1 or fewer items selected, "Other" is not selected: "Other" text input is enabled.'.  Why would we enable the "Other" input if the "Other" checkbox is not selected?

**Comment by tofumatt** [comment]
> Why would we enable the "Other" input if the "Other" checkbox is not selected?

My expectation would be that the text input itself is clickable/focusable if "Other" can be selected, and clicking the text box then inputting text would automatically "check" the "Other" checkbox.

So in fact, I'd expect that "Other" is not checked when the input is _focused_, but only when it has a _value_ set. (eg once the user focuses the input AND types something into the "Other" text input.

I clarified that bit in the IB, so I think this is good-to-go 😄 

IB ✅

**Comment by wpdarren** [comment]
@felixarntz @aaemnnosttv I have set up a fresh WP site, added Site Kit and enabled userInput with the tester plugin. For a 
 radio button question, when I select the 'Other' option, I was expecting the cursor to appear in the text input field based on the QAB:`- check that the other text input field is always enabled`

For me the behaviour is the same as before. I have cleared cache. Am I missing something obvious here?


https://user-images.githubusercontent.com/73545194/110719951-b7edc000-8248-11eb-924d-7daa6a54e7d3.mov

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@Hazlitte @aaemnnosttv  I am observing weird behaviour with the radio button and check boxes.   

1) As you can see on this screencast below - in this example, you start typing in the text input field, and the radio button is checked, but when you press the space bar to type a new word, the radio button is unchecked. This is the same behaviour on check box fields. 

https://user-images.githubusercontent.com/73545194/110764199-b85c7a00-828d-11eb-8bda-e19d008a38a3.mov

2) If the user selects the `other` radio button or check box, and types in the text input field. They then decide to uncheck the other option, the text input remains there.  Should this be removed automatically? As you can see from the screenshot, I have selected 3 answers but the text in other appears.  It doesn't appear in the preview. Thoughts? 

![image](https://user-images.githubusercontent.com/73545194/110763705-22c0ea80-828d-11eb-9523-7a1f9029dd4e.png)

**Verified:**

On questions with Radio buttons:

- The other text input field is always enabled when you select the `other` radio button. [Screenshot](https://user-images.githubusercontent.com/73545194/110761187-68c87f00-828a-11eb-80c9-a669eb52ebe3.png)

On questions with Check boxes:

- The other text input field is always enabled when you select the other check box. - [Screenshot](https://user-images.githubusercontent.com/73545194/110763201-94e4ff80-828c-11eb-82da-5af332c8c4ec.png)


- The other text input field is disabled when the maximum number of checkboxes are selected and one of them is not the other checkbox. - [Screenshot](https://user-images.githubusercontent.com/73545194/110762973-58190880-828c-11eb-8e55-fc1933b0c8b2.png)

**Comment by aaemnnosttv** [comment]
@wpdarren confirmed: the space bar triggers the box/radio to be unchecked, although I noticed you can still click next. After going back again, the radio is checked as it should be. Still odd though; the radio/checkbox should not be affected by input in the text field.

**Comment by tofumatt** [comment]
QA ❌

I noticed an issue with this that I think @Hazlitte mentioned seeing but then couldn't immediately reproduce:

![2021-03-11 18 36 54](https://user-images.githubusercontent.com/90871/110837246-e4c9c380-8298-11eb-9403-a8f8ef80f8a4.gif)

When only "Other" is selected it isn't disabled when it starts/ends with a space:

![2021-03-11 18 38 11](https://user-images.githubusercontent.com/90871/110837434-1e9aca00-8299-11eb-810c-155ee4bfb1a0.gif)

It seems to only happen when other items are selected, but it means you can wind up with "Others" as an option but a disabled input, which isn't good.

**Comment by ivankruchkoff** [comment]
@tofumatt the behaviour for disabled attribute on `Other` will be addressed in https://github.com/google/site-kit-wp/issues/2828 it seems there's a bit of overlap in these two tickets about that.

**Comment by felixarntz** [comment]
@tofumatt @Hazlitte @ivankruchkoff Indeed, this is still broken. We don't need to worry about other radio/checkboxes being unexpectedly checked or unchecked (part of #2828), but what should not happen here is having a space at the end of the input causing the "Other" choice to be disabled.

#2950 addressed the problem only partially.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

Confirmed that when you press the space bar while typing in the input field it does not deselect the radio button or checkboxes. I also tested this with a space at the end.  

**Radio buttons:**
- The other text input field is always enabled when you select 'Other'  [Screenshot](https://user-images.githubusercontent.com/73545194/111144659-5324c380-85c2-11eb-9ac0-070aeb1a3b02.png)

- When the radio button is not checked, typing in text input field sets it to checked.  - [Screenshot](https://user-images.githubusercontent.com/73545194/111144834-8f582400-85c2-11eb-9fc3-a529fc802c3c.png)

**Checkboxes**
- Typing in the text input field set the other checkbox to checked  - [Screenshot](https://user-images.githubusercontent.com/73545194/111146239-2a9dc900-85c4-11eb-908b-253932097d37.png)

- The  text input field is disabled when the maximum number of checkboxes are selected - [Screenshot](https://user-images.githubusercontent.com/73545194/111146108-06da8300-85c4-11eb-8be4-48f048c9f1ed.png)
