### ISSUE TITLE
User Input: Allow Other without detail in How often do you create new posts for this site? 

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2902]
## Feature Description

For **How often do you create new posts for this site?** Allow **Other** without specifying details.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For **How often do you create new posts for this site?** Allow **Other** without specifying details.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@ivankruchkoff Which original task does this relate to? I think this should be handled together with #2897 instead.

**Comment by felixarntz** [comment]
@ivankruchkoff After talking through this with @marrrmarrr, it was clarified that the "Other" option should _always_ require text input. This is already covered via #2907, so this issue here should be a `wontfix` / `invalid`.
