### ISSUE TITLE
Allow only one button to be in hover/active/click state.

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2903]
## Feature Description

We currently have three button states, **Normal**, **Hover**, and **Click**.  Normal can change to **Click** state via **Hover** but we shouldn't ever have more than one button in Hover/Click state.

<img width="408" alt="button-states" src="https://user-images.githubusercontent.com/373931/109577069-d36b0500-7aa9-11eb-9409-d1e3c96c4720.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure only one button can be active at a time (hovered/clicked), that includes keyboard focus, so that only one button at most can be in the not _normal_ state (the screenshot shows one button in hover and another in click state).

## Implementation Brief

* Remove background color and text underline styles for the "on hover" state of "Edit" buttons on the preview screen (`assets/js/components/user-input/UserInputPreviewGroup.js`).

### Test Coverage

* N/A

### Visual Regression Changes

* Hover effects will be removed from "Edit" buttons on the preview screen.

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
I'm a bit confused by the ACs here—it says that only one button can be in "not normal" state and includes mention of `:focus` state… but it's possible to have one element with `:focus` style and then a separate element with `:hover` style (as both states can and should be allowed to exist on separate elements at the same time).

It seems like the intention here to _not_ allow items to have a hover state, right? But isn't that less useful to people? I don't see a problem in allowing a focus and hover state to exist on buttons. 🤔

Could you clarify the intention here a bit more @ivankruchkoff?

**Comment by ivankruchkoff** [comment]
The intention here is that `:focus`  cancels `:hover` and vice-versa. Thinking it through, it does feel like a very artificial scenario and maybe we just close the ticket as only folks testing the app will try and get it in this state.

**Comment by ivankruchkoff** [comment]
Chatting with @tofumatt a bit more, it probably makes sense to close this out as it feels very tricky and not particularly accessibility friendly to try and unfocus an element that is in `:focus` when we `:hover` over another one, or to cancel the `:hover` state when we `:focus` an element.

From a practical point of view I think only people who are testing will simultaneously hover with the mouse and use tab to focus through elements.

What do you think @felixarntz can we close this out?

**Comment by felixarntz** [comment]
@ivankruchkoff @tofumatt Makes sense - revisiting this, it doesn't really make sense, the current behavior looks perfectly correct. Potentially the styles could be changed, but the current IB says to remove the hover styles entirely, in which case there would be no visual indication of hovering anymore.

Closing as suggested.
