### ISSUE TITLE
All traffic widget styles inconsistent in Storybook

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2904]
## Bug Description

The styling of the all traffic widget in Storybook is inconsistent with the styles in WordPress which show correctly.

This is due to its styles being coupled to its `widgetSlug` which is not consistent in Storybook (see `generateReportBasedWidgetStories`). This may only affect the tab bar which is the most obvious, but it may affect other parts as well.

See the current component in Storybook here:
https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-components-dashboard-all-traffic-widget--loaded

## Screenshots

**Storybook**

![image](https://user-images.githubusercontent.com/1621608/109638938-44b4c180-7b57-11eb-80f4-1dff01cba433.png)

**On Dashboard**

![image](https://user-images.githubusercontent.com/1621608/109638093-429e3300-7b56-11eb-946f-e575601b9214.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All styles on the new All Traffic widget should be independent of the widget slug (or CSS classes derived from it)
* The All Traffic Widget stories should be visually consistent with the widget rendered in WordPress

## Implementation Brief
* Using `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js`,
	* Add the `googlesitekit-widget__analytics--all-traffic` class name in addition to the existing `googlesitekit-widget--footer-v2` class name to the `Widget` component.
* Using `assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss`,
	* Replace the `.googlesitekit-widget.googlesitekit-widget--analyticsAllTraffic` selector by `.googlesitekit-widget__analytics--all-traffic`.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* Check the story above (https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-components-dashboard-all-traffic-widget--loaded) and ensure the spacing is not off as reported in the issue.
* Check that the All Traffic Widget on the dashboard of the site remains the same and hasn't changed based on this change.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@tofumatt from the QAB, I should be seeing the correct widget styles but [looking at Storyboard](https://google.github.io/site-kit-wp/storybook/master/?path=/story/analytics-module-components-dashboard-all-traffic-widget--loaded), it's still showing the incorrect font and alignment for the tabs. This is what I see:

![image](https://user-images.githubusercontent.com/73545194/114712562-cf95f800-9d62-11eb-90c2-410991a717ba.png)

The widget looks as expected in Site Kit dashboard.

![Screenshot](https://user-images.githubusercontent.com/73545194/114712843-213e8280-9d63-11eb-967b-9e8fd5857d9f.png)

**Comment by tofumatt** [comment]
I think this is a build error—the story looks like this for me locally:

<img width="1107" alt="Screenshot 2021-04-14 at 14 37 01" src="https://user-images.githubusercontent.com/90871/114719348-e3276b80-9d2e-11eb-81f3-a3fde0ed7328.png">

Seems like the Storybook isn't getting updated?

**Comment by tofumatt** [comment]
Argh, no, this was my bad setting the QA brief 😆 

I copied the URL @aaemnnosttv used in the issue, but it was pointed to the `main` branch which, of course, hasn't updated yet.

@wpdarren: the new URL in the QA brief points to Storybook in `develop`, which should work just fine. Sorry! 😅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that the Storybook is fixed for the widget style issues and this matches the style/design in Site Kit dashboard 

![image](https://user-images.githubusercontent.com/73545194/114732234-f0ffdf80-9d74-11eb-80f8-bf170051b77a.png)
