### ISSUE TITLE
Issue with SiteKit plugin when cloning a website

### ISSUE THREAD

**Issue by jordane2086** [google/site-kit-wp#2905]
I recently cloned my site to test developing a demo site. With this, since I cloned it the old site disconnected from sitekit and keeps pulling the new site up in Analytics rather than the actual domain/website it is on. I deleted the cloned site and the issue still persists. As well as clearing cache, server cache, etc. nothing helps. Anyone have a fix for this?

**Comment by jamesozzie** [comment]
Hi @jordane2086. It sounds like your old site which is registered on the Site Kit service could be resulting in issues with your cloned site. If you'd like to pop over and [create a WordPress support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) we can assist from there. We can re-open this GitHub issue if necessary after performing some troubleshooting steps., which may include using the "Reset" option. Note that resetting Site Kit will result in all services becoming disconnected, for all connected users.

**Comment by jordane2086** [comment]
Thank you. I found that there was a button within the plugin that allowed
me to clear the plugin settings/data and then I restarted the plugin set up.

Warm Regards

Jordan Erickson

Creative Director, Conceptualized Design
www.ConceptualizedDesign.com <https://www.conceptualizeddesign.com/> | Schedule
a consult <https://calendly.com/conceptualized-design>
+1.785.236.1777 <+17852361777>

Need to submit a Support, Update, or Change Request? Click Here
<https://clients.conceptualizeddesign.com/support/>, or email us at:
Support@conceptualizeddesign.com
Who's powering your digital marketing? Learn about Us.
<https://conceptualizeddesign.com/>
If you need to sign up for a web hosting plan, please Visit Our Website and
Sign Up <https://www.conceptualizeddesign.com/services/website-care-plan/>.
Want to tell us how we are doing? Leave us a review on our Facebook
<https://www.facebook.com/pg/conceptualizeddesign/reviews/> and Google
<https://www.google.com/search?q=manhattan%20ks%20web%20designer&oq=manhattan+ks+web+designer&aqs=chrome..69i57.5040j0j7&sourceid=chrome&ie=UTF-8&npsic=0&rflfq=1&rlha=0&rllag=39195145,-96605908,3922&tbm=lcl&rldimm=2471664026053194898&lqi=ChltYW5oYXR0YW4ga3Mgd2ViIGRlc2lnbmVyGYioBSiqEogUWg4KDHdlYiBkZXNpZ25lcg&ved=2ahUKEwjO0PqZ297hAhWNLlAKHcnvA5cQvS4wAHoECAoQIQ&rldoc=1&tbs=lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2#lrd=0x87bdd1ffa066bd19:0x224d1d5615033492,1,,,&rlfi=hd:;si:2471664026053194898,l,ChltYW5oYXR0YW4ga3Mgd2ViIGRlc2lnbmVyGYioBSiqEogUWg4KDHdlYiBkZXNpZ25lcg;mv:!1m2!1d39.2323029!2d-96.48734239999999!2m2!1d39.160160499999996!2d-96.6161874;tbs:lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2>
 pages.

<https://www.conceptualizeddesign.com/>

<https://www.facebook.com/conceptualizeddesign/>
<https://www.linkedin.com/company/3623365/>

Notice: This e-mail is covered under the Electronic Communications Privacy
Act, 18 USC 2510-2521, and is legally privileged. The information contained
in this e-mail is intended only for use of the individual or entity named
above. If the reader of this message is not the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited. If you have received this
communication in error, please immediately notify us by telephone at the
above number and permanently delete all copies of the original message.

ᐧ

**Comment by jordane2086** [comment]
Will do, thank you!

Warm Regards,

Jordan Erickson

Creative Director, Conceptualized Design
www.ConceptualizedDesign.com <https://www.conceptualizeddesign.com/> | Schedule
a consult <https://calendly.com/conceptualized-design>
+1.785.236.1777 <+17852361777>

Need to submit a Support, Update, or Change Request? Click Here
<https://clients.conceptualizeddesign.com/support/>, or email us at:
Support@conceptualizeddesign.com
Who's powering your digital marketing? Learn about Us.
<https://conceptualizeddesign.com/>
If you need to sign up for a web hosting plan, please Visit Our Website and
Sign Up <https://www.conceptualizeddesign.com/services/website-care-plan/>.
Want to tell us how we are doing? Leave us a review on our Facebook
<https://www.facebook.com/pg/conceptualizeddesign/reviews/> and Google
<https://www.google.com/search?q=manhattan%20ks%20web%20designer&oq=manhattan+ks+web+designer&aqs=chrome..69i57.5040j0j7&sourceid=chrome&ie=UTF-8&npsic=0&rflfq=1&rlha=0&rllag=39195145,-96605908,3922&tbm=lcl&rldimm=2471664026053194898&lqi=ChltYW5oYXR0YW4ga3Mgd2ViIGRlc2lnbmVyGYioBSiqEogUWg4KDHdlYiBkZXNpZ25lcg&ved=2ahUKEwjO0PqZ297hAhWNLlAKHcnvA5cQvS4wAHoECAoQIQ&rldoc=1&tbs=lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2#lrd=0x87bdd1ffa066bd19:0x224d1d5615033492,1,,,&rlfi=hd:;si:2471664026053194898,l,ChltYW5oYXR0YW4ga3Mgd2ViIGRlc2lnbmVyGYioBSiqEogUWg4KDHdlYiBkZXNpZ25lcg;mv:!1m2!1d39.2323029!2d-96.48734239999999!2m2!1d39.160160499999996!2d-96.6161874;tbs:lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2>
 pages.

<https://www.conceptualizeddesign.com/>

<https://www.facebook.com/conceptualizeddesign/>
<https://www.linkedin.com/company/3623365/>

Notice: This e-mail is covered under the Electronic Communications Privacy
Act, 18 USC 2510-2521, and is legally privileged. The information contained
in this e-mail is intended only for use of the individual or entity named
above. If the reader of this message is not the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited. If you have received this
communication in error, please immediately notify us by telephone at the
above number and permanently delete all copies of the original message.

ᐧ
