### ISSUE TITLE
User Input: "Other" choice not required when multiple

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2907]
## Bug Description

Steps 3 and 4 of the user input flow allow multiple choices with an option to provide an "other" value. The  single-option steps that offer an option to provide "Other" all require a non-empty, non-whitespace value to be provided.

## Steps to reproduce

1. Enable `userInput` feature
1. Start user input flow
2. On step 3 or 4 select one less than the required number of choices (excluding "Other")
3. Select "Other", without providing a value for it
4. See "Next" button is enabled

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/109695129-3c2eac00-7b94-11eb-8be1-0d8481815cbd.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Entering a text alongside the "Other" choice in a User Input question should _always_ be required when the radio button/checkbox is enabled in order to proceed, for every question.

## Implementation Brief

* edit `assets/js/components/user-input/UserInputQuestionWrapper.js`
* modify the `disabled` prop of the next `Button` to check if any of the values in the `values` array are empty and disable the button if there is. Specifically, https://github.com/google/site-kit-wp/blob/f3eea273ba67e3319457f8b22601461e3813954b/assets/js/components/user-input/UserInputQuestionWrapper.js#L101 can be changed to `disabled={ values.some( ( value ) => value.trim().length === 0 ) }`

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Check the following on the multiple choice questions 3 and 4 of the user input flow:
  * The next button is disabled when other is selected but no text has been entered in the other text field.
* Check that the next button is not disabled on the 5th question when only one or two search terms are entered.

## Changelog entry

* Ensure entering a text is required when choosing the "Other" option for a question in the user input flow.

**Comment by felixarntz** [comment]
@aaemnnosttv Did we decide here that entering something should _not_ be required? Not sure I recall; there's definitely the issue of visibility of the input, but I'm not sure about this one here.

**Comment by aaemnnosttv** [comment]
@felixarntz you'll have to check with @marrrmarrr. I'm also not sure but it's similar/related to #2897 in that it allows an empty value where others do not. So one way or the other it's inconsistent.

**Comment by felixarntz** [comment]
@aaemnnosttv Talked through this with @marrrmarrr: Entering something here should always be required.

**Comment by tofumatt** [comment]
IB ✅

It looks like the code here already _intended_ to do this from what I can tell, but it wasn't implemented properly? https://github.com/google/site-kit-wp/blob/f3eea273ba67e3319457f8b22601461e3813954b/assets/js/components/user-input/UserInputQuestionWrapper.js#L101

Anyway, I made a note indicating specifically what was wrong here and the fix. 👍🏻

**Comment by aaemnnosttv** [comment]
@felixarntz @tofumatt – perhaps this might be best as a follow-up issue, but I feel that there is room for improvement in communicating that the Other input is required when chosen. Currently it could be missed that this is needed as there is no visual or cue otherwise.

![image](https://user-images.githubusercontent.com/1621608/111290877-3edad800-864f-11eb-9a82-b099d2864f8e.png)

Perhaps the easiest change here would be to pass `noLabel` to the input (maybe only when `other` is selected) for its label to render as a placeholder:

![image](https://user-images.githubusercontent.com/1621608/111290953-5914b600-864f-11eb-95eb-0d715a423b57.png)

It might also be good to stylize the border/accent of the input to bring more attention to it that it is currently invalid.

**Comment by tofumatt** [comment]
@aaemnnosttv Indeed, there is an issue open for that already: #2993. So yes, let's do it, but in a separate issue. 🙂

**Comment by aaemnnosttv** [comment]
@tofumatt 👍 

@Hazlitte please sync your PR with the latest on develop and fix the errors in E2E then this should be good to go 👍  If you have questions about what's needed there, please reach out to @eugene-manuilov as he wrote the [tests for the user input flow](https://github.com/google/site-kit-wp/blob/develop/tests/e2e/specs/user-input-questions.test.js).

**Comment by Hazlitte** [comment]
@aaemnnosttv OK, will do 👍

**Comment by eugene-manuilov** [comment]
@aaemnnosttv assigning back to you for code review. I have fixed the e2e issue and a regression introduced by the original approach.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov please review the QA Brief and update, if appropriate.

**Comment by eugene-manuilov** [comment]
Updated QA slightly to verify that the 5th question works as intended.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

The next button is disabled when other is selected but no text has been entered in the other text field. 

![image](https://user-images.githubusercontent.com/73545194/112314089-93332700-8ce3-11eb-8b6a-2df502b5c1f3.png)

The preview (next) button is not disabled on the 5th question when only one or two search terms are entered.

![image](https://user-images.githubusercontent.com/73545194/112314168-a80fba80-8ce3-11eb-829a-9d0cf863739d.png)
