### ISSUE TITLE
Site Kit outputting Analytics snippet by default - on sites with existing Analytics snippets

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2909]
## Bug Description

At present when a user already has an existing Analytics snippet placed on their site there are duplicate snippets output if a user then chooses to connect the Analytics module within Site Kit. The toggle to "Let Site Kit place code on your site" is toggled on by default - although a user would not be unaware as these configuration options are not available until a user revisits their Site Kit Analytics settings page. 

Gif below showing duplicate snippets placed (one manual and another via SK)

![ex](https://user-images.githubusercontent.com/41326532/109726180-275d1300-7baa-11eb-8933-45b15f64e228.gif)

Tested as far back as Site Kit 1.21.0, the same occurred - happy to check further back if required. 
1.27.0 - [video showcasing experience](https://recordit.co/qhAWEbeVx9)
1.23.0 - [video showcasing experience](https://recordit.co/khHKnENpCT)
1.21.0 - [video showcasing experience](https://recordit.co/bfwXDhI3mv)

## Steps to reproduce

1. Manually insert an Analytics tracking snippet
2. Install and setup Site Kit
3. Connect the Analytics module
4. During the module setup screen a user will not be prompted on whether they want Site Kit tp insert the snippet, rather the module will complete connection
5. Analytics snippet appears twice (one manual placement, another via SK)
6. A user must go back into their Analytics settings screen within Site Kit to disallow Site Kit to place their snippet

## Additional Context

 - Started occurring from unknown Site Kit version - checked as far back at 1.21.0 when this same experience was occuring
 - No support topics open in relation to this although possible bounce rate implications, testing ongoing
 - Occurs with AMP or non AMP sites (tested on transitional mode AMP sites along with non AMP sites)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When there is an existing Analytics snippet in the frontend, the Analytics snippet from Site Kit should not be placed.
    * This should primarily be fixed in the Analytics setup flow; but as well in the Analytics settings panel (e.g. if an existing snippet was inserted _after_ setting up Analytics).
* At some point this used to work as expected, but something must have broken it - apparently a while ago. Note that, while in case of a GTM snippet we now rely on `canUseSnippet` through a filter, we either need to store a separate option to indicate an existing snippet is present or alternatively simply set `useSnippet` to `false` if that is detected.

## Implementation Brief

* Update Analytics’ `useExistingTagEffect` to call `setUseSnippet( false )` when there is a detected existing tag (regardless of access) https://github.com/google/site-kit-wp/blob/f3eea273ba67e3319457f8b22601461e3813954b/assets/js/modules/analytics/hooks/useExistingTagEffect.js#L79-L84
* Leave existing GTM-related logic alone

### Test Coverage

* Update `assets/js/modules/analytics/hooks/useExistingTagEffect.test.js` to cover this change in logic

### Visual Regression Changes

* N/A

## QA Brief

* Install and activate Site Kit plugin but don't set it up
* Install the tester plugin and use the `Place Analytics existing tag` feature
* Check that a frontend page has the GA tag inserted in the page
* Setup Site Kit
* Connect the Analytics module
* Check that a frontend page still only has the GA tag inserted by the tester plugin and a second one has not been inserted too

## Changelog entry

* Fix bug where Analytics snippet could still be placed when an existing snippet was already present in the frontend.

**Comment by jamesozzie** [comment]
@felixarntz Let me know if you want to open a separate GH issue in relation to the configuration options not appearing upon initial Analytics setup (when an existing snippet already exists before SK setup)

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Engineer to confirm ⚠️ 

@Hazlitte Following the steps in the QAB, this passes, but I have a scenario that I'd like some clarification on. 

On another of my test sites, within the theme, I have inserted the GA code in the header, but I have also connected Analytics within Site KIt.  In the settings, in the latest release, the `Let Site Kit place code on your site` is enabled by default.  
On the develop release though it is disabled.  Is this expected? 

Note: the `confirm changes` button is also active, where usually it's inactive unless you make a change. 

![image](https://user-images.githubusercontent.com/73545194/113865447-ac0d0380-97de-11eb-9a79-575027d39cd0.png)

**Comment by Hazlitte** [comment]
Hi @wpdarren, I looked into this and then we discussed it on standup.  The behaviour is expected and the team has noted that there is a UX issue here that needs assessing.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Went through the tasks in the QAB and the frontend page still only has the GA tag inserted by the tester plugin and a second one has not been inserted.   - [Screenshot](https://user-images.githubusercontent.com/73545194/113969003-c2f73880-9866-11eb-8021-b94439a6ba4a.png)

@Hazlitte the UX issue you mention, I am assuming a separate ticket will be submitted for this?

**Comment by Hazlitte** [comment]
Hi @wpdarren, 
I have created a new ticket for this as tagged above, #3115.
Thank you for spotting the problem.
