### ISSUE TITLE
Inconsistency for components error message when user has no access to Analytics account

### ISSUE THREAD

**Issue by lucymtc** [google/site-kit-wp#291]
## Bug Description

Inconsistency for components error message when a second admin has no access to Analytics account that has been previously been setup by first admin.

## Steps to reproduce

1. Login as admin, activate and authenticate Site Kit.
2. Connect Analytics module and configure selecting account, property and view.
3. Logout and login again as a different admin.
4. Go through Site Kit authetication flow and authenticate with google account that has no access to Analytics account setup for the site. 
5. Go to Site Kit dashboard and see the inconsistent messages. 

## Screenshots

![Screen Shot 2019-07-17 at 14 28 54](https://user-images.githubusercontent.com/1204359/61375496-51f83c00-a89f-11e9-8613-579d514a7308.png)

## Additional Context
Related https://github.com/google/site-kit-wp/issues/52

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@lucymtc Any idea why that is different? It should have the same logic regardless of which admin is logged in.

**Comment by felixarntz** [comment]
This should no longer be a problem after the refactoring of these components, as they now all use the correct differentiation between error states and zero states. Once the refactored widget-based version of the dashboard rolls out, nobody should see this broken state any longer.
