### ISSUE TITLE
Upgrade npm dependency

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2911]
## Feature Description

Our package-lock.json lockfileVersion is at version 1, ( see https://raw.githubusercontent.com/google/site-kit-wp/develop/package-lock.json ```  "lockfileVersion": 1,``` ).

Our .nvmrc specifies node 14 but doesn't specify a version of npm. NPM 6 is bundled with the release, but there's nothing stopping you from doing `npm i -g npm@7`

NPM v7 has an updated package lockfile version https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json/#lockfileversion

Running different versions of npm (even if it's the same version of node) creates big changes with every `npm install`. 

We can solve this by doing one of the following:
- specify an npm engine version via https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines but this isn't _strict_ and per the docs `Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.`

We can do one of the following to standardise on npm7:
1) Introduce npm7 via config and also make it a point to upgrade our package-lock and reject CRs with lockfile version 1. OR
2) Bump node version to node 15 which includes npm7. This seems like the easier/more consistent option. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of #6026
