### ISSUE TITLE
Async compatibility checks make E2E unstable

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2913]
## Bug Description

In #2255 we refactored the `CompatibilityChecks` component for consistency with our latest standards and practices. Part of this refactoring involved extracting the checks that it provides into a generic `useChecks` hook. This changed the way checks were previously run in series (sequentially) to running them all at once. This is a bit more time-efficient as each check doesn't wait for the one before it to finish. However, in E2E it causes a potential race condition where a check that makes a request will be aborted/cut-off by an error raised in another check. A failed fetch request then triggers a console error to be logged which will fail the test because we can't `expect()` it consistently one way or the other.

## Steps to reproduce

1. Run E2E tests until they fail
2. Notice an error is logged where the error message is "You are probably offline."

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `useChecks` should run all checks sequentially and only run the next check if the current one did not raise an error

## Implementation Brief

* Merge #2917 

### Test Coverage

* No changes

### Visual Regression Changes

* N/A

## QA Brief

* With devtools open, and observing XHR requests navigate to the Site Kit splash screen
* Observe check requests made one after another for the setup tag, health checks, and amp CDN
    * Each request should be made only after the previous one succeeds
    * No request to `google-site-kit/v1/core/site/data/developer-plugin` should be observed

To test a failing-check condition where no further checks should run:
* Start the E2E environment (reset if necessary)
* Navigate to the splash screen
* Observe warning (due to localhost)
* No setup tag, health checks, or amp CDN request should be made
* A request to `google-site-kit/v1/core/site/data/developer-plugin` should be observed in this case which is expected when there is a failing check

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Nice find! 👍🏻

Part of me wonders about only running them sequentially in "test mode" or something, but they're not a common point-of-contact in the app so even if the sequential version is a bit slower in-use it's a rare thing and that's probably fine. 🙂 

IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Looking at the [recent E2E runs](https://github.com/google/site-kit-wp/actions/workflows/e2e-tests-wp-latest.yml?query=is%3Acompleted), stability seems to be much better with the only failures here being legitimate failures.

![image](https://user-images.githubusercontent.com/1621608/110761750-c47a1480-8258-11eb-8abf-fe887be59d02.png)
