### ISSUE TITLE
Site Kit Blog News on WordPress Event and News Dashboard Widget

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#2915]
## Feature Description

Suggestion to add [Site Kit News](https://sitekit.withgoogle.com/news) on WP Event and News Dashboard widget. It'd be useful for the Site Kit users to see the latest updates.
## Acceptance criteria

* 

## Implementation Brief

- We can use [`dashboard_primary_feed`](https://developer.wordpress.org/reference/hooks/dashboard_primary_feed/) hook to implement. It seems feed is disabled for the Site Kit News at the moment.
### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kuasha420** [comment]
We have discussed this in one of our recent review meetings and decided to not do it at the moment. The most relevant Site Kit news are about new releases which we have once every two week. We decided not to add those in the core widget. 

In the future, we may decide to do something similar with our own Site Kit dashboard widget. 

Closing this one for now.
