### ISSUE TITLE
Use alternate Composer setup in E2E jobs for efficiency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2919]
## Feature Description

We recently updated our E2E actions to run Composer using the `php-actions/composer` action. Using this action adds ~2 minutes to the job run because it requires building the container to use which provides both Composer v1 and v2.

This is much less efficient than how we run Composer for PHP Tests which installs Composer using `shivammathur/setup-php@v2` – which takes ~45s.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E test jobs for GitHub actions should be updated to install and/or run Composer in a way that is more efficient than `php-actions/composer`

## Implementation Brief

* Merge #2921

### Test Coverage

* No change

### Visual Regression Changes

* N/A

## QA Brief

* Review run time for `setup-php` and `composer install` steps in E2E jobs on GitHub actions
* See total time for these steps is now ~15s compared to ~2.5m before  
![image](https://user-images.githubusercontent.com/1621608/110109452-24367280-7db6-11eb-9f02-a66533bcdf1a.png)

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
@eugene-manuilov @aaemnnosttv please could you provide steps for running E2E jobs on GitHub actions, this isn't something I have done before, but happy to learn!

**Comment by eugene-manuilov** [comment]
@wpdarren E2E jobs are run automatically, we can't run them manually. You can compare existing e2e tests for a PR before merging changes for this ticket with a PR that has been created after these changes have been merged.

**Comment by wpdarren** [comment]
@eugene-manuilov @aaemnnosttv wooosh, that went right over my head! :) More direction here would be welcome.

**Comment by cole10up** [comment]
### QA ✅

Before:
PR 20 days ago
![image](https://user-images.githubusercontent.com/57115907/110593601-a2857280-8130-11eb-9264-24260428995a.png)

After:
PR today
![image](https://user-images.githubusercontent.com/57115907/110593497-7d90ff80-8130-11eb-931e-a43b0b3f947d.png)

Sending to approved
