### ISSUE TITLE
Add Travis-CI job for testing with multisite

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#292]
In preparation of #276, there should be a job in Travis-CI that uses multisite. We already have a few multisite-specific tests (that currently aren't run at all in CI), and also the regular ones should be run to ensure they don't unexpectedly break because of multisite nuances. Having a multisite job is crucial for long-term quality of the product.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There is a job in the Travis-CI configuration running PHPUnit tests in a WordPress multisite environment.
* The multisite-specific PHPUnit tests annotated with `@group ms-required` are run.
* The Travis-CI build including the new job passes.

## Implementation Brief

* Introduce a new job in `.travis.yml` that is identical to the third job (PHP 7.3, WP latest), except that it has an additional `WP_MULTISITE=1` env variable (supported by core [here](https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/includes/bootstrap.php#L79)).
* Run tests locally with the environment variable set (e.g. `WP_MULTISITE=1 gulp phpunit`) and fix errors if any come up.
* If any of the failing tests are actually invalid when running multisite, they should be annotated with a `@group ms-excluded`).

## Changelog entry

* N/A

**Comment by ThierryA** [comment]
IB LGTM!

**Comment by felixarntz** [comment]
QA is good, multisite tests are running as expected and pass.
