### ISSUE TITLE
`npm install` fails on Linux and Windows machines

### ISSUE THREAD

**Issue by ChrisAntaki** [google/site-kit-wp#2928]
## Bug Description

`npm install` fails on Linux and Windows machines. This happens because `fsevents` only installs on Mac machines. `fsevents` is set to a `devDependency`, which is a required dependency. We can fix the issue by setting `fsevents` to an `optionalDependency` instead :sunglasses: 

## Steps to reproduce

1. Run 'npm install' on Linux or Windows machine
2. See error

## Screenshots
![image](https://user-images.githubusercontent.com/1216762/110376223-c8fbbe80-8007-11eb-9464-11a45bb48ae4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@ChrisAntaki Can you try this again with the latest `develop` build? This was also noticed elsewhere, and I just merged #2746 which removes `fsevents`.

**Comment by ChrisAntaki** [comment]
Excellent, #2746 fixes this issue
