### ISSUE TITLE
AdSense dashboard console errors on Safari

### ISSUE THREAD

**Issue by lucymtc** [google/site-kit-wp#293]
## Bug Description
After setting up AdSense, the AdSense dashboard is not showing any data and trowing JS errors in the console. Not happening in Chrome or Firefox, only on Safari.
After removing all the browser extensions error persisted.

```
 TypeError: new Intl.NumberFormat(navigator.language, {
      style: 'currency',
      currency: currencyCode
    }).formatToParts is not a function. 
```

## Steps to reproduce

1. In Safari setup AdSense
2. Go to the AdSense Dashboard. 
3. See the errors in the console.

## Screenshots

![_safari-adsense-setup-console-error-A](https://user-images.githubusercontent.com/1204359/61381327-31ce7a00-a8ab-11e9-9371-e65cd1d2ae6a.png)
![_safari-adsense-setup-console-error-B](https://user-images.githubusercontent.com/1204359/61381345-385cf180-a8ab-11e9-8d0b-71094ba98f63.png)

## Additional Context

 - PHP Version: 7.3
 - OS: macOS High Sierra 10.13.4
 - Browser: Safari 11.1
 - Plugin Version: 1.0.0-beta.1.0.1
 - Device: macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts#Browser_compatibility

Gutenberg is not using it either, but only relies on the `format` method which _is_ supported in all browsers.

**Comment by aaemnnosttv** [comment]
Closing in favor of #1107
