### ISSUE TITLE
Allow modifying the active Search Console property

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2937]
## Feature Description

It should be possible to modify the Search Console property used for the current site via the UI. Typically, most sites only have a single property that would match the current site, but there certainly can be sites that have more than one property that would match. For those sites, it is beneficial to allow them select a specific property among those.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Search Console settings panel should receive an actual edit view (`SettingsEdit`), which shows a single dropdown to specify the Search Console "Property", controlling the respective module option (`propertyID`).
* The dropdown should list the available property IDs that the user has access to, **which apply to the current site**.
* A datastore selector `getMatchedProperties()` should be introduced to `modules/search-console`, returning the available sites that match the current site URL. The existing `GET:matched-sites` REST datapoint can be used to receive only those properties.
* When the active Search Console property is changed **and submitted**, the user that made the change should become the new Search Console module owner, i.e. the Search Console module should now also have a specific owner like the other modules, instead of relying on the global Site Kit-wide owner. `propertyID` should be the only owned key.
* Storybook coverage should be added for the new Search Console edit view.

#### js:

* **Datastore:**
  * Create a new `settings.js` file in the datastore folder.
    * It should export a new `submitChanges` function that dispatches `saveSettings` action if there are settings that have been changed (use `haveSettingsChanged` selector). Plus it should invalidate cache for the Search Console module. See similar function in the Analytics module for more details.
    * It should export a new `validateCanSubmitChanges` function that validates `propertyID` value using the `invariant` function.
  * Update `Modules.createModuleStore` function call in the `assets/js/modules/search-console/datastore/index.js` file. Add `validateCanSubmitChanges` and `submitChanges` properties to the module store arguments using the `validateCanSubmitChanges` and `submitChanges` functions imported from the `settings.js` file.
  * Add a new datastore selector `getMatchedProperties` to a new datastore partial `datastore/properties.js`. It should call the existing `GET:matched-sites` endpoint in the resolver to retrieve data for matched sites. See reports datastore as an example of how to create a new fetch store.
* **Components:**
  * Create a new component `assets/js/modules/search-console/components/common/PropertySelect.js` to display a dropdown for the `propertyID` setting.
    * Use the `getMatchedProperties` selector to retrieve available properties. This selector should return a list of site objects. Use `siteUrl` properties of each site object in the list to populate the dropdown. If a `siteUrl` value starts with `sc-domain:`, then strip it and use only the remaining part with the ` (domain property)` suffix.
    * Use the `AccountSelect` component from the Analytics module as an example.
  * Create a new `assets/js/modules/search-console/components/settings/SettingsForm.js` functional component. It should display `StoreErrorNotices` and `PropertySelect` elements. Use the `SettingsForm` component from the Optimize module as an example.
  * Create a new `assets/js/modules/search-console/components/settings/SettingsEdit.js` functional component. It should be identical to one from the Optimize module.
  * Remove `! autoActivate` check for the `Edit` button in the `assets/js/components/settings/settings-module.js` component.
  * Add the new `SettingsEdit` component to the Search Console module registration args under `SettingsEditComponent` property.

#### php:

* Add a new `ownerID` property to the default settings of the `Search_Console` module. It should use zero as its default value.
* Update the Seach Console settings class:
  * Add the `Setting_With_Owned_Keys_Trait` trait.
  * Call the `register_owned_keys` method in the `register` method.
  * Add a new `get_owned_keys` method that returns an array with only 'propertyID` value.
* Add the `Module_With_Owner_Trait` trait to the `Search_Console` class and remove the `get_owner_id` method from the class itself.

#### storybook:

* Add storybook stories to cover new property selection functionality.
* Add storybook stories to cover different module settings states. See similar stories for the Analytics module and replicate it for the Search Console module.
* Update existing storybook stories for the Search Console module settings to correctly work with the aforementioned changes.

### Test Coverage

* Add js tests for the new `getMatchedProperties` selector.
* Add js tests for new `validateCanSubmitChanges` and `submitChanges` functoins.
* Add the `Module_With_Owner_ContractTests` trait to the Search Console module class to test the new ownerID functionality.
* Fix existing tests if anything is broken due to the aforementioned changes.

### Visual Regression Changes

* The Search Console module should have editable settings after implementing the required changes.

## QA Brief

* Go to the search console settings.
* Make sure you can change the current property selected for the site.
* Make sure your changes persist after you save it and refresh the window.
* Make sure that the selected property is being used when you visit the dashboard or search console pages.

## Changelog entry

* Allow modifying the active Search Console property in the module's settings panel, relevant for example when a site has multiple applicable properties.

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov – IB looks great for the most part, just a few things to elaborate on a little bit:

> Add a new datastore selector `getMatchedProperties`. It should call the existing `GET:matched-sites` endpoint in the resolver to retrieve data for matched sites.

This should go in a new data store partial; how about `datastore/properties.js`?

> Create a new component `assets/js/modules/search-console/components/common/PropertySelect.js` to display a dropdown for the `propertyID` setting. Use the `AccountSelect` component from the Analytics module as an example.

What should be used for values and what should be used for the text content of each option? We can probably use `siteUrl` for both. We may however want to display domain properties differently since end users may be confused by `sc-domain:example.com`.

Also, since this is the first editable setting for SC, we'll need to create a `datastore/settings.js` that defines its `submitChanges` and related validation. One important part to add in particular is [the cache invalidation on settings save](https://github.com/google/site-kit-wp/blob/9f92b89b0951af458063c7208608d2f3cbb7d1b9/assets/js/modules/analytics/datastore/settings.js#L92-L94) so that users don't see stale cached data for the wrong property if they change it.

Finally, regarding Storybook, let's also add a/story(ies) for Settings Edit like we do for other modules. Currently we just have Settings View. https://google.github.io/site-kit-wp/storybook/develop/?path=/story/search-console-module-settings--view-open-with-all-settings

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov 
> What should be used for values and what should be used for the text content of each option? We can probably use `siteUrl` for both. We may however want to display domain properties differently since end users may be confused by `sc-domain:example.com`.

Good point regarding the domain properties. Indeed, the values should always be the `siteUrl` value (which is basically the `propertyID`). For domain properties (starting in `sc-domain:`), the text content should be `sprintf( __( '%s (domain property)', 'google-site-kit' ), siteUrl.replace( /^sc-domain:/, '' ) )`, for URL properties the text content should be simply the `siteUrl`. This is in line with how we already use labels in the legacy setup flow (see `search-console.js` legacy component).

**Comment by felixarntz** [comment]
@eugene-manuilov (or whoever is taking over): IB almost LGTM, just one quick thing to fix

> If a `siteUrl` value starts with `sc-domain:`, then strip it and use only the remaining part.

This shouldn't just strip the prefix, it should also append "(domain property)" to it, see https://github.com/google/site-kit-wp/issues/2937#issuecomment-795834670.

**Comment by eugene-manuilov** [comment]
@felixarntz IB is updated. Please, assign it to me if it looks good to you and I'll take care of it this week.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Need engineer clarification ⚠️ 

@eugene-manuilov am I right in thinking that for the Google account connect to the website, the properties assigned against that account should be appearing in the dropdown?  

On my test site, I only see the URL for the current site.

![image](https://user-images.githubusercontent.com/73545194/114397781-a09c4c80-9bd1-11eb-84fa-0520d90b8bc2.png)

But the Google account has a number of associations, these are not appearing in the dropdown. 

![image](https://user-images.githubusercontent.com/73545194/114397856-b742a380-9bd1-11eb-95f4-ceac9557996b.png)

Maybe it's my lack of understanding, but I am trying to figure out what the scenario is on why you would want to select another console property.  Please could you clarify?

**Comment by eugene-manuilov** [comment]
@wpdarren you should see accounts with matched URLs in that dropdown. I am not sure how to add more properties to your account to be able to test it. @felixarntz can you help us to figure it out?

**Comment by felixarntz** [comment]
@wpdarren Most sites will only have a single property to choose from, so that's expected. To test the behavior with multiple you can either create a Search Console domain property for your site's URL (however that requires DNS level verification, so might be some work) or create another Search Console URL property. The latter should be easier, e.g.:
* Make sure your site is also accessible over HTTP (temporarily, I guess).
* Go to https://search.google.com/search-console and in the property dropdown, choose "Add new property".
* There you can enter the same URL of your site, but with HTTP instead of HTTPS. If your site is accessible, the verification should work accordingly.

Let me know if there are issues with this.

**Comment by aaemnnosttv** [comment]
Looks correct for me using my personal site where I have both properties:
![image](https://user-images.githubusercontent.com/1621608/114525265-a5531600-9c4e-11eb-8465-64724d5dec1e.png)

**Comment by wpdarren** [comment]
@felixarntz I added https and http version of my domain using `URL prefix` but I was unable to see both in the dropdown. I can add a DNS record for the domain and see if that works, but should the different prefixes work?

**Comment by felixarntz** [comment]
@wpdarren Just to make sure, have you checked https://www.google.com/webmasters/verification/home? This has a list of all URLs / properties you're verified for. Do both show up there as expected? Otherwise, it would be great if you could test this for a domain property too.

Actually, there may be a small issue here regarding URL properties that came from the ACs; @eugene-manuilov Right now we only list properties based on the matching logic that is also used to find the correct Search Console property right (i.e. allowing either the exact URL property or the exact domain property)? I think for the dropdown, it may be more appropriate to use a "slightly less precise" approach, e.g. if you have both an HTTP and HTTPS version of the property, both should be displayed in the dropdown, no matter what your site actually uses. The same would apply to www vs non-www.

Potentially worth covering this as a follow-up issue, if what I'm suspecting is correct here.

**Comment by eugene-manuilov** [comment]
> I think for the dropdown, it may be more appropriate to use a "slightly less precise" approach, e.g. if you have both an HTTP and HTTPS version of the property, both should be displayed in the dropdown, no matter what your site actually uses. The same would apply to www vs non-www.

@felixarntz I have created a PR for it: #3189. Do you mind reviewing it?

**Comment by wpdarren** [comment]
> @wpdarren Just to make sure, have you checked https://www.google.com/webmasters/verification/home? This has a list of all URLs / properties you're verified for. Do both show up there as expected? 

@felixarntz - yes, both URLs are verified and show up as expected. 

Since @eugene-manuilov has created a PR, I am going to put this to Code Review. Please assign me and move it back to QA and I will run through the testing on this + test it with a domain property too.

**Comment by felixarntz** [comment]
@wpdarren Ready for re-QA after the update (please use the `main` branch for this one since it is part of the release).

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

- User can change the current property selected for the site.
- The changes persist after you save it and refresh the window.
- Checked that the selected property is being used when you visit the dashboard or search console pages.

![image](https://user-images.githubusercontent.com/73545194/115538729-18ced600-a294-11eb-98ff-45e02270fce9.png)

Note: I am testing this with a domain property, but I am waiting for DNS update and for it to be verified. I am going to pass this as it passes the QAB, but will update this ticket if any issues arise with the domain property.
