### ISSUE TITLE
Migrate `DashboardUniqueVisitorsWidget` Storybook coverage to follow new v6 best practices

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2940]
With Storybook now in v6, we should migrate a few particular stories to follow the new best practices established in [this doc](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit). Migrating all existing stories is not a high priority, we can keep most old stories in their existing state; they should only be migrated on demand.

This issue is about migrating a specific datastore-driven (connected) component to follow the new Storybook v6 best practices. As part of this, some general infrastructure for the new best practices (e.g. global decorators, reusable components) should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A global Storybook decorator should be implemented that wraps every story in a `WithTestRegistry`.
    * It needs to be verified that this does not break existing stories which might already have their own `WithTestRegistry` (i.e. the closest test registry wins?).
* A new component `WithRegistrySetup` should be added within `tests/js`, that should be used in any decorators that need to populate the test registry:
    * It should take `func` and `children` props.
    * It should only render `children` if an internal state flag `ready` (with initial value `false`) is set to `true`; otherwise should return `null`.
    * It should run the `func` on first render, passing the registry to it via `useRegistry()`, and once it has completed set the internal state flag `ready` to `true`.
* The Analytics `DashboardUniqueVisitorsWidget` component should receive an accompanying `DashboardUniqueVisitorsWidget.stories.js` file, with new Storybook coverage that follows the [new Storybook best practices](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit). Particularly:
    * It should use `Modules/Analytics/Widgets/DashboardUniqueVisitorsWidget` for its title.
    * It should have 6 different stories: one for its regularly loaded state, one for zero data state, one for error state; then, the exact same three states for the case where an entity URL is set (i.e. irl that would be on the single URL page dashboard).
    * If there is some data needed in the datastore which is common for all 6 stories, a component decorator should be implemented that takes care of it via `WithRegistrySetup`.
    * For any other data needed in the datastore, story-specific decorators should be added, which use `WithRegistrySetup`.
* The existing Storybook coverage for `DashboardUniqueVisitorsWidget` from before should be removed.

## Implementation Brief

In `.storybook/preview.js`
Remove the deprecated `addDecorator` calls, change them to be in the following format:
```
export const decorators = [
	( Story ) => {
		return (
			<WithTestRegistry callback={ setupRegistry }>
				<div className="googlesitekit-plugin-preview js">
					<Story />
				</div>
			</WithTestRegistry>
		);
	},
	// Decorators run from last added to first
	( Story ) => {
		resetGlobals();
		return Story();
	},
];
```

You'll find if that's the only change you make, that your storybook will no longer load, as the following code will be called:
https://github.com/google/site-kit-wp/blob/cd220ad/assets/js/modules/pagespeed-insights/index.js#L43

prior to any of the global decorators. To work around this, we initialise the global variable earlier. 

To do this, we create two files `.storybook/utils/resetGlobals.js` which exports the `resetGlobals()` function from `/.storybook/preview.js` and `/.storybook/polyfill-globals.js`, which imports and runs the `resetGlobals()` we created.  Add a comment in the `/.storybook/preview.js` file to explain why `.storybook/polyfill-globals.js` needs to be imported first. (to ensure all globals are setup before any other imports are run).

 https://github.com/google/site-kit-wp/blob/6e39b10b6b52cc3c118d397404f9a64559b81272/.storybook/preview.js#L38

Create the `WithRegistrySetup` component following the ACs in `tests/js/utils.js`, it will be used to populate the registry that we instantiate in the global decorator.

Create the `DashboardUniqueVisitorsWidget.stories.js` stories in `assets/js/modules/analytics/components/dashboard/DashboardUniqueVisitorsWidget.stories.js` refer to the ACs.

Use https://google.github.io/site-kit-wp/storybook/pull/YOURCR/ to ensure the stories are rendering correctly.

Update `stories/module-analytics-components.stories.js` to remove stories pertaining to `DashboardUniqueVisitorsWidget`.

### Test Coverage

* No change

### Visual Regression Changes

* Should require no changes

## QA Brief
* Run storybook via the following command: `npm run storybook`
* Check if all stories are loading
* Check if the stories under `Modules/Analytics/Widgets/DashboardUniqueVisitorsWidget` are loading.

## Changelog entry

* N/A

**Comment by ivankruchkoff** [comment]
IB reviewer: 
Checkout `feature/2940-dashboard-unique-visitors-widget-storybook6-stories`
Confirm that `npm run storybook` compiles and loads tests for you at http://localhost:9001/

Remove this line:
https://github.com/google/site-kit-wp/blob/6e39b10b6b52cc3c118d397404f9a64559b81272/.storybook/data/wp-admin-admin.php-page%3Dgooglesitekit-dashboard-googlesitekit.js#L4

Notice that the storybook no longer compiles due to https://github.com/google/site-kit-wp/blob/cd220ad/assets/js/modules/pagespeed-insights/index.js#L43

Any ideas for how we can work around this to clean up the IB and simplify this approach?

**Comment by aaemnnosttv** [comment]
> Any ideas for how we can work around this to clean up the IB and simplify this approach?

@ivankruchkoff the legacy globals are necessary for now and resetting them for every story is critical to avoid changes leaking between stories. We could make it a little cleaner perhaps by moving `resetGlobals` into a dedicated decorator (as it was before) rather than merging it into the one for the registry, we'd just want to ensure that it runs first (this is probably why it failed before because decorators run in reverse order).

E.g.

```js
const setupRegistry = ( { dispatch } ) => {
	// @TODO setupRegistry
	global.console.log( 'setupRegistry' );
};

export const decorators = [
	( story ) => global.console.log( 'first' ) || story(),
	( story ) => global.console.log( 'second' ) || story(),
	( Story ) => {
		resetGlobals();
		return (
			<WithTestRegistry callback={ setupRegistry }>
				<div className="googlesitekit-plugin-preview js">
					<Story />
				</div>
			</WithTestRegistry>
		);
	},
	( story ) => global.console.log( 'second-to-last' ) || story(),
	( story ) => global.console.log( 'last' ) || story(),
];
```
logs:
```
preview.js:108 last
preview.js:107 second-to-last
preview.js:91 setupRegistry
preview.js:96 second
preview.js:95 first
```

So we could move `resetGlobals` to a dedicated decorator function in the array, after the test registry decorator.

**Note**
- The global decorator providing `WithTestRegistry` would no longer receive a `callback` prop
- We need to preserve the wrapping [`.googlesitekit-plugin`](https://github.com/google/site-kit-wp/commit/6e39b10b6b52cc3c118d397404f9a64559b81272#diff-98b614e1838b171ee71c04450a8f1a562753193fb7d4f53a4de8b9b5a7e980eeL97) in the global decorator as well

---

Regarding the IB – mostly looks good, just one question:

> Create the `WithRegistrySetup` component following the ACs in `tests/js/utils.js`, and using the component `WithTestRegistry` as a reference for the functionality

I'm not quite sure what you mean by the last part "using the component `WithTestRegistry` as a reference for the functionality". The new component will interact with the registry, but isn't reimplementing `WithTestRegistry` as it may sound. Could you clarify what to reference here?

**Comment by aaemnnosttv** [comment]
IB ✅  

As a side note, don't forget to always populate the sections for Test Coverage and VRT. In this case, there shouldn't be any just something to keep in mind. This helps us differentiate between "none needed" and "needed, but forgot" scenarios 😄

**Comment by ivankruchkoff** [comment]
Had a look at the approach @asvinb, it makes sense. 👍 

It might be worth having a think about composing the `setupRegistry` from the decorator into something that's able to be used across all the stories in `Analytics` module, thus reducing the amount of boilerplate setup required for every story. Any thoughts there @aaemnnosttv ?

**Comment by aaemnnosttv** [comment]
@asvinb @tofumatt I left a comment on the PR with an alternate branch based on the current PR to consider. cc: @felixarntz

**Comment by tofumatt** [comment]
I responded to the comment here: https://github.com/google/site-kit-wp/pull/3230#issuecomment-832902137

I like your approach and think we should use it 👍🏻

**Comment by aaemnnosttv** [comment]
I pushed a few more changes in light of some of the more recent changes around enabled features and I think this should be good to go now. Assigning to @tofumatt, @eugene-manuilov, and @felixarntz for review the suggested approach going forward.

**Comment by tofumatt** [comment]
I left a comment: https://github.com/google/site-kit-wp/pull/3230#pullrequestreview-661265697.

Overall I like the changes 👍🏻

**Comment by eugene-manuilov** [comment]
Approved the PR and left a comment.

**Comment by danielgent** [comment]
QA: ✅

All looks fine :smile:
