### ISSUE TITLE
Migrate `Button` Storybook coverage to follow new v6 best practices

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2941]
With Storybook now in v6, we should migrate a few particular stories to follow the new best practices established in [this doc](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit). Migrating all existing stories is not a high priority, we can keep most old stories in their existing state; they should only be migrated on demand.

This issue is about migrating a specific presentational (non-connected) component to follow the new Storybook v6 best practices.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The general `Button` component should receive an accompanying `Button.stories.js` file, with new Storybook coverage that follows the [new Storybook best practices](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit). Particularly:
    * It should use `Components/Button` for its title.
    * It should have individual stories for each of its 5 different states (see existing stories), relying on [story args](https://storybook.js.org/docs/react/writing-stories/args#story-args). Similar to the examples in the documentation, a single `Template` should be used with arguments different for each of the 5 scenarios.
* The existing Storybook coverage for `Button` from before should be removed.

## Implementation Brief

* Familiarise yourself with the `Site Kit: Storybook v6 usage` doc.
* Make a copy of `stories/buttons.stories.js` to `assets/js/components/Button.stories.js`
* Break up the combined stories into a set of individual stories for each button variant.
* For the backstop params in https://github.com/google/site-kit-wp/blob/ef1a7e5/stories/buttons.stories.js#L68-L72 use `component parameters` for them: https://storybook.js.org/docs/react/writing-stories/parameters#component-parameters
* Rebuild the stories via `npm run build:storybook` or by keeping `npm run storybook` running as you make story changes. 
* Compare visually each individual story in storybook v6 format to the old format of story (v5), you can do this by comparing your updated stories with https://google.github.io/site-kit-wp/storybook/master/ or https://google.github.io/site-kit-wp/storybook/develop/ and comparing with `/dist/index.html`
* When the stories match visually, remove the old format of story `stories/buttons.stories.js`
* Run backstop to ensure visual regression testing work correctly `npm run test:visualtest`
* Update the changed images `npm run test:visualapprove`, ensuring that they are only changes between `v5` and `v6` of storybook, rather than regressions we've introduced.

Created `feature/2941-button-storybook6-stories` branch as part of writing this IB which does some of the execution too.

### Test Coverage

* No change

### Visual Regression Changes

* Storybook stories will be updated with no user facing changes.

## QA Brief

* Check the file `stories/buttons.stories.js` has been deleted
* Check the code in `assets/js/components/Button.stories.js` fulfils with IB.  Note that the AC and comments below suggest using the Storybook V6 `Template` approach which has been done but this isn't mentioned in the IB.
* Check that visual regression testing works,  `npm run test:visualtest`.

## Changelog entry

* N/A

**Comment by ivankruchkoff** [comment]
Writing an IB for a blocked ticket was somewhat tricky, so I took some of the work @asvinb did to update storybook in https://github.com/google/site-kit-wp/pull/2723/files, added it to a branch `feature/2941-button-storybook6-stories` and went through https://storybook.js.org/blog/storybook-6-migration-guide/ to get things to build.

I took a pass at migrating the tests from the old format to the new, and wrote up the IB in the process and put out a draft PR that I used to guide the IB: https://github.com/google/site-kit-wp/pull/2959

This still requires changes to backstop, and the other work in #2128, before we can proceed.

**Comment by aaemnnosttv** [comment]
>  Rebuild the tests `npm run build:storybook`

@ivankruchkoff – just wanted to point out that you don't need to run a full build every time you change something. Running `npm run storybook` will hot reload any component/story changes other than main configs. The `test:visualtest` command will also run a fresh build so not needed to run separately before that (unlike E2E for example).

> For the [backstop params](https://github.com/google/site-kit-wp/blob/ef1a7e5/stories/buttons.stories.js#L68-L72) in use story args for them: https://storybook.js.org/docs/react/writing-stories/args#story-args

I don't think args are the right place for these, as args are mostly intended to be props for the component. These should continue to be passed as [parameters](https://storybook.js.org/docs/react/writing-stories/parameters) as they are now 
![image](https://user-images.githubusercontent.com/1621608/111195251-bdd6fe80-85c4-11eb-977c-6aa97deca928.png)

In this case specifically, they would be defined as [Component Parameters](https://storybook.js.org/docs/react/writing-stories/parameters#component-parameters).

Finally, one minor nitpick/clarification I have is just regarding the terminology: you referred to them as tests and visual tests however the testing aspect is purely related to the integration with Backstop; stories are not tests by themselves but rather pieces of our component library 🙂

**Comment by ivankruchkoff** [comment]
Updated and adding another reminder that `feature/2941-button-storybook6-stories` exists to handle a big part of this.

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff. This is good to go, just 2 small details to note:

* The AC says we should use a `Template` component for applying the args as shown in the docs. Not sure this needs an additional mention in the IB, but I just noticed that your branch does not use this approach.
* Let's bump the estimate up one as even though this should be fairly straightforward, anything which isn't trivial should probably be a little higher to be on the safe side (I'll update it now)

IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz – assigning to you regarding a question I have on the PR.

**Comment by asvinb** [comment]
`Button.stories.js` implemented as per AC.

### QA: ✅
