### ISSUE TITLE
Migrate `AdminBarApp` Storybook coverage to follow new v6 best practices

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2942]
With Storybook now in v6, we should migrate a few particular stories to follow the new best practices established in [this doc](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit). Migrating all existing stories is not a high priority, we can keep most old stories in their existing state; they should only be migrated on demand.

This issue is about migrating a specific view component (i.e. a component consisting of multiple sub-components) to follow the new Storybook v6 best practices.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New `*.stories.js` files should be added for the following connected admin bar components, each following the [new Storybook best practices](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit) (please check `DashboardUniqueVisitorsWidget.stories.js` from #2940 for reference):
    * `AdminBarClicks` (including decorator using `WithRegistrySetup` for populating datastores)
    * `AdminBarImpressions` (including decorator using `WithRegistrySetup` for populating datastores)
    * `AdminBarSessions` (including decorator using `WithRegistrySetup` for populating datastores)
    * `AdminBarUniqueVisitors` (including decorator using `WithRegistrySetup` for populating datastores)
    * each of them should have a decorator using `WithRegistrySetup` for populating datastores), there should be two stories (one for having data available, the other one for zero data state), and the title used should be `Views/AdminBarApp/{ComponentName}`
* `AdminBarZeroData` should also be accompanied by its own `AdminBarZeroData.stories.js` file with a simple purely presentational single story, the title should also be `Views/AdminBarApp/{ComponentName}` here.
* `AdminBarWidgets` should be accompanied by its own `AdminBarWidgets.stories.js` file, which should rely on reusing decorators declared in its sub-components (see above) wherever possible. It should include the following stories:
    * Analytics active & connected, data available for every sub-component
    * Analytics active & connected, zero data for both Analytics sub-components
    * Analytics active & connected, zero data for all sub-components
    * Analytics inactive, data available for every (Search Console) sub-component
    * Analytics inactive, zero data for every (Search Console) sub-component
* The existing Storybook coverage for `AdminBarApp` (and any of the other admin bar components) from before should be removed.

## Implementation Brief
* Once #2940 has been merged.
* Create the `stories.js` files for the components as mentioned in the AC.
* For the `AdminBarClicks`, `AdminBarImpressions`, `AdminBarSessions` and `AdminBarUniqueVisitors` stories,
	* Since they are widget based and for the decorators in those stories to be re-usable in the `AdminBarApp` and `AdminBarWidgets` component, create a new template which renders the `WidgetAreaRenderer` component.
	* Bind each stories of the components to the template and add decorators to each stories where the data store is populated using the `WithRegistrySetup` component.
	* Story decorators should be defined outside of the `decorators` property and exported so that they can be imported easily later.
	* At the component level decorator, register and assign widgets to widget areas similar to what is done in #2940.
	* To populate the datastore for the above components, most of the code can be found in `stories/adminbar.stories.js` and can be copied over.
* Create the story file for the `AdminBarWidgets` and `AdminBarApp` components, having stories as mentioned in the AC while re-using the decorators from sub component stories. To re-use the decorators, import the exported decorators from the sub component stories files and spread the imported decorators in the current story `decorators` key.
* Delete the `stories/adminbar.stories.js` file.

### Test Coverage
* No changes needed

### Visual Regression Changes
* The `Admin Bar` test should be updated to use the new `.stories.js` file.

## QA Brief
* Run storybook locally via the `npm run storybook` command.
* Ensure the stories are rendered as per the AC.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
> To re-use the decorators, import the stories from the sub component stories files and spread the imported decorators in the current story `decorators` key.

Did you mean import `decorators` from the subcomponent story files? I don't think we need to import the actual stories, right? The decorators are exported separately, I think.

**Comment by asvinb** [comment]
@tofumatt The decorators will be per story and we'll need to import them from the stories file. Let me know if that makes sense :)

**Comment by tofumatt** [comment]
@asvinb Right, but we're just importing the `decorators` exports from those stories, not the "stories" themselves, right? eg. `AdminBarWidgets` would `import { decorators } from './subStory';`, right?

**Comment by tofumatt** [comment]
IB ✅

**Comment by Hazlitte** [comment]
**. QA Eng ✅ **
`AdminBarApp` stories are rendering in storybook as per the AC.
