### ISSUE TITLE
Implement GA tracking events for All Traffic feature tooltip tour (and tooltip tours in general)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2944]
Feature tour should send GA tracking events for interaction with them (for users that have opted in).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Every feature tour should include its event category for GA tracking in its definition. For now, the only tour that exists is `allTrafficWidget`; it should use `all_traffic_widget` for its GA event category (for parity with other tracking events for the feature).
* The tooltip tour components should trigger the following GA tracking events to be sent:
    * `feature_tooltip_view` (for every tooltip displayed; event label should be the current tooltip step, starting at index 1)
    * `feature_tooltip_dismiss` (when dismissing via the X button; event label should be the current tooltip step, starting at index 1)
    * `feature_tooltip_advance` (when clicking the "Next" button; event label should be the current tooltip step, starting at index 1)
    * `feature_tooltip_return` (when clicking the "Back" button; event label should be the current tooltip step, starting at index 1)
    * `feature_tooltip_complete` (when clicking the "Got it" button; event label should be the current tooltip step, starting at index 1)

## Implementation Brief

* Using `TourTooltips` component, import the `trackEvent` function from the `assets/js/util/tracking/index.js` file;
* Add a new property `gaEventCategory` to the TourTooltips component and mark it required;
* Update `handleJoyrideCallback` function in the TourTooltips component to track the following events using `gaEventCategory` property as actual event category value and `data.index + 1` value as label:
    * `feature_tooltip_view` event when `data.type = EVENTS.TOOLTIP && data.lifecycle = LIFECYCLE.TOOLTIP`;
    * `feature_tooltip_dismiss` event when `data.action = ACTIONS.CLOSE && data.lifecycle = LIFECYCLE.COMPLETE`;
    * `feature_tooltip_advance` event when `data.action = ACTIONS.NEXT && data.lifecycle = LIFECYCLE.COMPLETE`;
    * `feature_tooltip_return` event when `data.action = ACTIONS.PREV && data.lifecycle = LIFECYCLE.COMPLETE`;
    * `feature_tooltip_complete` event when `data.status = STATUS.FINISHED && data.lifecycle = LIFECYCLE.COMPLETE`;
* Add `gaEventCategory` property with `all_traffic_widget` value to the `allTrafficWidget` object in the `assets/js/feature-tours/index.js` file;
* Update the `FeatureTours` component to pass `nextTour.gaEventCategory` into TourTooltips' `gaEventCategory` property.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Enable anonymous usage tracking on activation notice or splash/settings screen
* Enable Tag Assistant (or other browser extension for inspecting GA events)
* Ensure your user's `googlesitekitpersistent_initial_version` user option is below `1.25.0`
    You can set this with wp-cli using  
    ```sh
    # Get your DB prefix (otherwise you can replace its output with the default `wp_`)
    PREFIX=$(wp db prefix)
    # Assuming your user's ID is 1 (replace with your ID / username / email)
    wp user meta set 1 "${PREFIX}googlesitekitpersistent_initial_version" 1.20.0
    ```
* Delete any dismissed tours
    ```sh
    wp user meta delete 1 "${PREFIX}googlesitekitpersistent_dismissed_tours"
    ```
* Activate Analytics with site that has data (pie chart needs to load to trigger tour)
* Navigate (if needed) to Site Kit dashboard
* Observe events tracked with the respective event category, action, and label as described in the ACs

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@aaemnnosttv @tofumatt  when I click on the `X` icon to close the Tooltip tour, in the log I see `feature_tooltip_complete` but according to the QAB, this should be `feature_tooltip_dismiss` I've looked through the log and cannot find this event type.

![image](https://user-images.githubusercontent.com/73545194/112413211-c5cc3680-8d5a-11eb-860a-8091f1e57656.png)

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren – looking at your log there (and based on the existing test coverage) this condition you found is specific to dismissing on the last step of the tour (with the X/close button). I've opened a follow-up PR for this including added test coverage for this case but it would be great if you could confirm once it's merged.

**Comment by aaemnnosttv** [comment]
@wpdarren – this is ready for another pass, although you'll want to wait for this to finish first: https://github.com/google/site-kit-wp/actions/runs/686519346 Then you can test with the latest `master`

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

I have gone through the AC's and made sure that the correct event data is included in the log file.
