### ISSUE TITLE
Filtering out traffic & Admin and Copywriters in backend and front end

### ISSUE THREAD

**Issue by Tristan29photography** [google/site-kit-wp#295]
## Feature Description
Hi there,
It would be great to filter out the Admin and copywriters traffic both in back end and front end. 

In advance many thanks
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@Tristan29photography There is a feature request for this although there is  a worksaround by

#88

**Comment by jamesozzie** [comment]
@Tristan29photography There is an open feature request for this, #88. Within Analytics you can also create a view for the property you would like to measure which excludes bots and spiders. You will find the option from within a view on your property ID [here](https://i.imgur.com/ooenBW1.png). 

You can also find more information about creating custom filters [here](https://support.google.com/analytics/topic/1034830).
