### ISSUE TITLE
AdSense "Performance by page over the last X days" deep links do not include date range

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2951]
## Bug Description

The links in the top pages table on the AdSense module dashboard which is shown when there is a linked Analytics account does not include the current date range in its deep link.

## Steps to reproduce

1. Set up Site Kit with AdSense and a linked Analytics account
2. Navigate to AdSense dashboard
3. Note the current date range
3. Click on a link in the "Performance by page over the last X days" table
4. See the date range in Analytics does not match the date range selected in Site Kit

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Deep links in the `LegacyAnalyticsAdSenseDashboardWidgetTopPagesTable` component should include date range args in the report args used for constructing the report service URL

## Implementation Brief
* Using `/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsAdSenseDashboardWidgetTopPagesTable.js`,
	* Import the `generateDateRangeArgs` from `assets/js/modules/analytics/util/report-date-range-args.js`.
	* Query the user's date range selection by querying the user data store with the `getDateRangeDates` selector, passing the `DATE_RANGE_OFFSET` constant from `assets/js/modules/analytics/datastore/constants.js` as value to the `offsetDays` key.
	* Update usage of the `getServiceReportURL` selector to spread the result of the `generateDateRangeArgs` function, passing the user's date range as parameter to the function.
	* Changes above should also be applied to the new widget based component, most specifically the following file: `assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget/Table.js`

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief
You will need to enable the `widgets.moduleScreens` feature using the tester plugin.
* Follow the 'steps to reproduce' above
* The links in the new (top) widget and the legacy (bottom) widget should all contain a date range 

## Changelog entry

* Update AdSense "Performance by page over the last X days" deep links to include date range

**Comment by tofumatt** [comment]
The IB had adjustments made now that #2987 is merged (the original IB mentioned this, but I made them concrete). Essentially just that the component `AnalyticsAdSenseDashboardWidgetTopPagesTable` is now `LegacyAnalyticsAdSenseDashboardWidgetTopPagesTable` Otherwise looks good!

IB ✅

**Comment by johnPhillips** [comment]
@asvinb CC @tofumatt Just noticed that the service URLs in the legacy and new widgets are different.

`LegacyAnalyticsAdSenseDashboardWidgetTopPagesTable` uses the Analytics store to generate the service URL:

https://github.com/google/site-kit-wp/blob/b460234894bcbe28dd31a9422b57293e78021977/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsAdSenseDashboardWidgetTopPagesTable.js#L73

`ModuleTopEarningPagesWidget` uses the AdSense store:

https://github.com/google/site-kit-wp/blob/f45198b9bb32de60b1161241ece4594ac4b21386/assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget/Table.js#L47

I was responsible for the latter during a recent refactor, so I am guessing that's the incorrect one... 🙈 

Can you confirm? Obviously we need to use the right `generateDateRangeArgs ` util depending on which store we use. 
Thanks!

**Comment by johnPhillips** [comment]
Update: I've discussed with @aaemnnosttv and we concluded that the behaviour in the legacy widget is correct. I have refactored the new widget accordingly 👍

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

**Verified:**

When I click on a link in the "Performance by page over the last X days" table, the date range matches the date range selected in Site Kit.  I tested this with `widgets.moduleScreens` feature enabled and disabled and the correct dates appear.

7 days  -` u.date00=20210427&_u.date01=20210503/ `
14 days  - `u.date00=20210420&_u.date01=20210503/ `
28 days - `u.date00=20210406&_u.date01=20210503/`
90 days - `u.date00=20210203&_u.date01=20210503/ `

I also made sure that the `See full stats in Analytics` link had the date on too, based on selection in Site Kit.
