### ISSUE TITLE
E2E broken with latest wordpress image

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2954]
## Bug Description

A recent update to the wordpress docker image has broken E2E runs, mostly because the WordPress database is no longer created automatically in the image's entrypoint. This affected `wpenv` and many other projects as well.

The simplest fix to unblock us is to pin the `wordpress` image to a tag before this happened and we can revisit in the future. In the meantime, we'll have a more consistent/reproducible E2E environment. We should potentially do this going forward anyways to avoid surprise breaking changes in our dependencies.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `wordpress` image in the `docker-compose.yml` for our E2E environment should use the `5.6-php7.4` tag to avoid the recent breaking changes in the `latest`/`5`/`5.7` images.

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/2955

### Test Coverage

* No change

### Visual Regression Changes

* N/A

## QA Brief

* N/A – if E2E tests run again, this has done its job 😄 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:
