### ISSUE TITLE
Analytics chart vAxis labels inconsistent when showing session duration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2967]
## Bug Description

On the Analytics module dashboard, when viewing the chart with Session Duration selected, the vertical axis labels may appear as `mm:00` followed by `:30` between. 

## Steps to reproduce

1. Go to Analytics dashboard
2. Select Session Duration
3. See screenshot similar to below

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/111213889-ed443600-85d9-11eb-94ab-9933028164c5.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics dashboard widget/chart should have consistent formatting of its labels for the vAxis when session duration is selected

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/2968

### Test Coverage

* No change

### Visual Regression Changes

* No changes expected because no existing scenarios are likely affected

## QA Brief

* Check the Analytics dashboard page as per the steps to reproduce noting before/after in formatting of vAxis labels when Session Duration is selected

## Changelog entry

* Fix vertical axis labels for Session Duration graph on Search Console module page to not mix minutes and hours.

**Comment by felixarntz** [comment]
IB ✅ 😆

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

The Analytics dashboard page has the correct vAxis labels when Session Duration is selected. 

![image](https://user-images.githubusercontent.com/73545194/111611673-ac396500-8817-11eb-80ab-90f24a8282c4.png)
