### ISSUE TITLE
Incorrect order of Clicks and Impressions data blocks + trends in admin bar vs single URL page

### ISSUE THREAD

**Issue by lilybonney** [google/site-kit-wp#297]
Addressed by PR #892 

---

## Bug Description

The admin bar dropdown shows clicks then impressions, while the Site Kit dashboard (and WP dashboard) shows impressions then clicks - the latter makes more sense as impressions > clicks.

However, the trend stats underneath are not re-ordered, which results in showing the wrong trend for each stat:

How stats are currently displayed in the admin bar: 
![URL-admin](https://user-images.githubusercontent.com/13304791/68954120-a535b900-07c3-11ea-9d20-ca2b5420337b.png)

In the single URL detailed report, the order is reversed for clicks and impressions, but the trend numbers are not, resulting in contradictory reporting:  
![URL-dashboard](https://user-images.githubusercontent.com/13304791/68954137-a8c94000-07c3-11ea-9d1d-9d8ddc293bd2.png)

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The stats should be displayed in the same order both in the admin bar and in the single URL page: impressions followed by clicks
* The trend change stats should match the correct metric: impressions trend change for impressions, and clicks trend change for clicks. 

## Implementation Brief

* Swap the order of data blocks in `<SearchConsoleAdminbarWidgetOverview>` so that total impressions are shown first
* Correct references to change and sparkline data columns in `<SearchConsoleDashboardWidgetTopLevel>`
* Merge #892 

## Changelog entry

* Display impressions before clicks in admin bar as that is the commonly expected order.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

Order is consistent in both screens, looks good! 👍

**Comment by marrrmarrr** [comment]
👁👍
