### ISSUE TITLE
Scaffold analytics-4 internal module in PHP

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2974]
Since GA4 Analytics properties and UA properties are entirely different and separate, the infrastructure and basic API for GA4 should be implemented in a separate (fully internal) module. [See more information on the overall approach](https://docs.google.com/document/d/11DMYyAGhtFHO8bMH107pacC8iMpD9PJ9BTaR6IF_B5E/edit?resourcekey=0-0CgoW31PILS2t6JGZ6w_yA#heading=h.ft5rt9liuag2).

This issue is for scaffolding the `analytics-4` module PHP class that will serve as foundation for the new internal module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

There should be a new `Google\Site_Kit\Modules\Analytics_4` module class:
* Should be marked as `internal`.
* Should have the slug `analytics-4` and name `Analytics 4 (Alpha)`.
* Other module information fields should match what the existing `analytics` module uses.
* Should declare the same base scopes as required like the main Analytics module (the new APIs rely on the same scopes).
* Should declare a single service `analyticsadmin`, which is the [Admin API integration class from the PHP client library](https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/GoogleAnalyticsAdmin.php) (the respective namespace needs to be added to the PHP Scoper configuration so that it is included in the build).
* Should be accompanied by a `Google\Site_Kit\Modules\Analytics_4\Settings` class which encompasses the following settings:
    * `accountID` (Analytics account ID, which effectively matches the UA account ID, since accounts are not technically different; yet, the module should already be self-contained and therefore store this)
    * `propertyID` (Analytics GA4 property ID; contrary to UA, this is not the value to include in the tag, this is more comparable to the `internalWebPropertyID` setting of the main Analytics / UA module)
    * `webDataStreamID` (Analytics GA4 web datastream ID; part of the GA4 property; this is automatically set or created based on the GA4 property specified by the user)
    * `measurementID` (Analytics GA4 measurement ID; this is the value to include in the tag, which is technically defined by the web datastream)
    * `useSnippet` (whether to place the Analytics GA4 snippet; if `useSnippet` is also enabled for the main Analytics / UA module, double tagging will be used)
* Should also include the concept of module ownership via the respective PHP traits, with `ownerID` being controlled by `accountID`, `propertyID`, `webDataStreamID`, and `measurementID` settings
* Should also expose Site Health information for each of the five settings
* Should expose the following REST datapoints (under the `analytics-4` module namespace):
    * `GET:accounts` (queries accounts via [accounts.list](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/list))
    * `GET:properties` (queries GA4 properties for an account via [properties.list](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties/list))
    * `GET:webdatastreams` (queries GA4 web data streams for a GA4 property via [properties.webDataStreams.list](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams/list))
    * `POST:create-property` (creates a GA4 property for a given account via [properties.create](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties/create); should use the site address host as property name)
    * `POST:create-webdatastream` (creates a GA4 web data stream for a given GA4 property via [properties.webDataStreams.create](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams/create); should use the site address host as data stream name, and also set the default URI based on the site address)

## Implementation Brief

* Create the `Analytics_4` class PHP file starting from [the already implemented class in this experimental branch from last year](https://github.com/google/site-kit-wp/compare/experimental/analytics-4-module#diff-057a7c0b7d3ca6ea365f58acd6913b97a0b3bd5fa2bd139b1bb492fd4e7d1725), then remove the parts that are out of scope of this issue:
    * `GET:report` and `GET:tag-permission` datapoints and related methods
    * all functionality about rendering tags
    * the `analyticsdata` API service
    * AdSense linking-related functionality
    * assets-related functionality (with that being part of #2977)
* Create the `Analytics_4\Settings` class PHP file starting from [the respective class from the same experimental branch](https://github.com/google/site-kit-wp/compare/experimental/analytics-4-module#diff-503ffbe23639f21ba83454821007728f404c05a113e789e22bc691c97b93805f), removing the settings which are not part of the ACs
* Add the `GoogleAnalyticsAdmin` service to the PHP Scoper configuration so that those classes are included in the build
* Update the `Modules` class to allow for numbers in module slug names for the REST routes (see https://github.com/google/site-kit-wp/compare/experimental/analytics-4-module#diff-ba139661aaccfb4281aa55301a0066504c2d7712a5d48fad8cd62be4c1d31463)
* Complete and merge #2982

### Test Coverage

* Add test coverage for `Analytics_4` class, similar to test coverage for the `Analytics` class
* Add test coverage for `Analytics_4\Settings` class, similar to test coverage for the `Analytics\Settings` class

### Visual Regression Changes

* N/A

## QA Brief

* Ensure the new Analytics class is implemented per the ACs.
* Make sure tests pass.

## Changelog entry

* Scaffold `analytics-4` module PHP class.

**Comment by aaemnnosttv** [comment]
@felixarntz I updated `webDatastreamID` -> `webDataStreamID` per my previous comment in the doc.

IB ✅

**Comment by felixarntz** [comment]
@aaemnnosttv Thanks for updating this throughout the other issues - was about to do that :)

**Comment by tofumatt** [comment]
QA ✅
