### ISSUE TITLE
Add ga4setup feature flag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2975]
There should be a new `ga4setup` feature flag that toggles whether the new GA4 support during the Analytics setup flow (plus related infrastructure such as the internal module, see #2974) is enabled. [See more information on the overall approach](https://docs.google.com/document/d/11DMYyAGhtFHO8bMH107pacC8iMpD9PJ9BTaR6IF_B5E/edit?resourcekey=0-0CgoW31PILS2t6JGZ6w_yA#heading=h.ft5rt9liuag2).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new feature flag `ga4setup`.
* If the `ga4setup` feature flag is enabled, the new `Google\Site_Kit\Modules\Analytics_4` class (module slug `analytics-4`) should be registered alongside the existing core modules (see `Google\Site_Kit\Core\Modules\Modules`).
    * While this class is being implemented in #2974, the implementation of this issue can already get started regardless, since the class name is defined. #2974 is required to be merged first though.
* The `Google\Site_Kit\Core\Modules\Modules` PHP class should be further amended so that the `analytics-4` module's activation status always depends on the `analytics` module; in other words: Instead of storing `analytics-4` in the list of active modules in the database, rely on the value for `analytics` to determine activation status.

## Implementation Brief

* Add `ga4setup` to the feature flags array in the `feature-flags.json` file.
* Update the `Modules::__construct` method to add the new `Google\Site_Kit\Modules\Analytics_4` module to the `$core_modules` array if the `ga4setup` feature flag is enabled. Use the `Feature_Flags::enabled` method to determine whether the `ga4setup` flag is enabled.
* Update the `Modules::get_active_modules_option` method to add `analytics-4` slug to the `$option` variable if it contains the `analytics` slug.

### Test Coverage

* Update the existing phpunit tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* N/A

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@eugene-manuilov IB looks good, with one suggestion:
- Instead of modifying `Modules::get_active_modules_option`, how about we return `'force_active' => true,` from the GA4 module's `setup_info` method when Analytics is in the list of active module slugs. We'd probably have to check the option directly (module classes don't have access to `Modules` anyways) but this seems like it might be a better alternative. What do you think?

**Comment by eugene-manuilov** [comment]
> Instead of modifying `Modules::get_active_modules_option`, how about we return `'force_active' => true,` from the GA4 module's `setup_info` method when Analytics is in the list of active module slugs. We'd probably have to check the option directly (module classes don't have access to `Modules` anyways) but this seems like it might be a better alternative. What do you think?

I think it will be more cumbersome if we go this route. However, I can't say that I like the approach of hard coding module slugs in the Modules class anyway. From my point of view, we should make the `Analytics_4` class inherit the `Analytics` class and override/extend appropriate methods to achieve the desired functionality.

**Comment by aaemnnosttv** [comment]
> From my point of view, we should make the `Analytics_4` class inherit the `Analytics` class and override/extend appropriate methods to achieve the desired functionality.

Something like this could still happen in a different issue, but I think simply extending the current `Analytics` class would have its own problems. If anything, we could extract a base class that they would then both extend, but I'm not sure there's really that much they have in common to share.

IB ✅

**Comment by eugene-manuilov** [comment]
@aaemnnosttv 

> ... I'm not sure there's really that much they have in common to share.

By using inheritance we don't "share" common functionality between two classes, we extend the existing functionality in the main class by overriding methods in the child class:

```php
class Module {
    protected function get_datapoint_definitions() {
        return array();
    }
}

class Analytics extends Module {
    protected function get_datapoint_definitions() {
        return array(
            'GET:accounts-properties-profiles' => ...,
            ...
        );
    }
}

class Analytics_4 extends Analytics {
    protected function get_datapoint_definitions() {
        return array_merge(
            parent::get_datapoint_definitions(),
            array(
                'GET:v4-accounts' => ...,
                'POST:create-v4-property' => ...,
                ...
            )
        );
    }
}
```

```diff
 class Modules {
     ...
     private $core_modules = array(
         Site_Verification::class,
         Search_Console::class,
-        Analytics::class,
+        Analytics_4::class,
         Optimize::class,
         Tag_Manager::class,
         AdSense::class,
         PageSpeed_Insights::class,
     );
     ...
 }
```

> ... I think simply extending the current `Analytics` class would have its own problems...

Which one do you envision?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov Let's take the conversation to a call or document 🙂

**Comment by felixarntz** [comment]
@eugene-manuilov While the two classes are fairly similar, they shouldn't depend on each other implementation-wise. We can outsource common functionality to separate classes that can be reused across both when it makes sense, but `Analytics_4` is not an extension of `Analytics` (and not vice-versa either). They should both be their standalone module classes.

**Comment by Hazlitte** [comment]
**QA Eng** ✅
