### ISSUE TITLE
Scaffold googlesitekit-modules-analytics-4 JS asset and modules/analytics-4 datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2976]
As part of the infrastructure to add GA4 support, there should be a new `googlesitekit-modules-analytics-4` JS asset including a `modules/analytics-4` datastore, for the new internal `analytics-4` module class implemented in #2974. [See more information on the overall approach](https://docs.google.com/document/d/11DMYyAGhtFHO8bMH107pacC8iMpD9PJ9BTaR6IF_B5E/edit?resourcekey=0-0CgoW31PILS2t6JGZ6w_yA#heading=h.ft5rt9liuag2).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `assets/js/modules/analytics-4` module directory.
* There should be a new `assets/js/modules/analytics-4/datastore` directory should for now only have an `index.js`, `base.js`, and `constants.js` file, creating a `modules/analytics-4` datastore which is nothing more than a base module store (via `createModuleStore`), and exposing a `registerStore( registry )` function like the existing stores do. The base module store should include support for the following `settingSlugs` (see related #2974 definition):
    * `accountID`
    * `propertyID`
    * `webDataStreamID`
    * `measurementID`
    * `useSnippet`
* There should be a new `assets/js/modules/analytics-4/index.js` file which simply exports through the above `registerStore` function for now (further functionality than the datastore will be added to the module at some point in the future).
* There should be a new `assets/js/googlesitekit-modules-analytics-4` JS file (also as entrypoint in webpack). It should call the `registerStore` function from the above with the Site Kit registry (`Data` from `googlesitekit-data`).

## Implementation Brief

* Create a new file `assets/js/modules/analytics-4/datastore/constants.js`:
  * Export the `STORE_NAME` constant with `module/analytics-4` value;
  * Export an alias of the `STORE_NAME` constant with the `MODULES_ANALYTICS_4` name.
* Create a new file `assets/js/modules/analytics-4/datastore/base.js` that should create and export a new module store using the `createModuleStore` function from the `googlesitekit-modules` package. Use the following params when creating the new module store:
  * The `slug` should be `analytics-4`;
  * The `args` object should have `storeName` and `settingSlugs` properties:
    * Use `STORE_NAME` constant for the `storeName` property.
    * Use an array with `accountID`, `propertyID`, `webDataStreamID`, `measurementID`, and `useSnippet`values for the `settingSlugs` property.
* Create a new file `assets/js/modules/analytics-4/datastore/index.js` that should combine module stores and export that combined store as default export. For now, the `combineStores` function from the `googlesitekit-data` package should container only `baseModuleStore` store imported from the `base.js` file (in the future more stores will be added).
  * This file should also export the `registerStore` function that accepts a registry object and calls the `registerStore` action providing the `STORE_NAME` constant and combined data store instance as parameters.
* Create a new file `assets/js/modules/analytics-4/index.js` that should re-export the `registerStore` function from the `datastore/index.js` file.
* Create a new file `assets/js/googlesitekit-modules-analytics-4.js` that should call imported `registerStore` function providing the `Data` object imported from the `googlesitekit-data` package.
* Add a new entry to the webpack config with `googlesitekit-modules-analytics-4` name and the path to the `assets/js/googlesitekit-modules-analytics-4.js` file as entry value.
* Add the new module to the `allCoreModules` list that is intended to make module datastores available in js tests: https://github.com/google/site-kit-wp/blob/8df049f73589fea2ef5de13b711d23bef1ec70fe/tests/js/utils.js#L53-L55

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check the source code of the new `Analytics 4` module located in the `assets/js/modules/analytics-4` folder.
* Make sure it satisfies requirements defined in the AC section.

## Changelog entry

* Introduce JS data store `modules/analytics-4` as infrastructure for upcoming GA4 integration.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov – IB looks good – one thing we should add is importing the store and adding it to this array so that it is available in all test registries: https://github.com/google/site-kit-wp/blob/8df049f73589fea2ef5de13b711d23bef1ec70fe/tests/js/utils.js#L53-L55

**Comment by eugene-manuilov** [comment]
Good catch, @aaemnnosttv. IB is updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
@aaemnnosttv do you mind reviewing #3089?

**Comment by Hazlitte** [comment]
Hi @eugene-manuilov, @aaemnnosttv,
I noticed that this ticket is in the QA column but doesn't have a QA brief.

**Comment by Hazlitte** [comment]
Great, thanks @eugene-manuilov. 👍 
I noticed there are a couple of other QA tickets without briefs on them too.  I'm working on an IB now.  I'll come back to this later.

**Comment by Hazlitte** [comment]
**QA Eng ** ✅
