### ISSUE TITLE
Register googlesitekit-modules-analytics-4 JS asset in Analytics_4 PHP class

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2977]
To connect the work from #2974 and #2976, the new `googlesitekit-modules-analytics-4` JS asset should be registered by the new `Analytics_4` PHP module class, ensuring that the JS asset will be enqueued if the `ga4setup` feature flag (see #2975) is enabled. [See more information on the overall approach](https://docs.google.com/document/d/11DMYyAGhtFHO8bMH107pacC8iMpD9PJ9BTaR6IF_B5E/edit?resourcekey=0-0CgoW31PILS2t6JGZ6w_yA#heading=h.ft5rt9liuag2).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Analytics_4` PHP class introduced in #2974 should implement `Module_With_Assets`, registering a `googlesitekit-modules-analytics-4` script asset which is the `assets/js/googlesitekit-modules-analytics-4.js` file introduced in #2976.

## Implementation Brief

* Update the `Analytics_4` PHP class to implement the `Module_With_Assets` interface and to use the `Module_With_Assets_Trait` trait.
* Add a new protected method `Analytics_4::setup_assets()`. It should return an array with a single `Script` instance that uses the `googlesitekit-modules-analytics-4` slug and the following args (see an example [here](https://github.com/google/site-kit-wp/blob/523fd50a1f0d7f4212c1fa0bddf7be45ac606a68/includes/Modules/Optimize.php#L248-L267)):
  *  `src` should point to the `dist/assets/js/googlesitekit-modules-analytics-4.js` script;
  * `dependencies` should be an array with the following dependencies:
    * `googlesitekit-vendor`
    * `googlesitekit-api`
    * `googlesitekit-data`
    * `googlesitekit-modules`
    * `googlesitekit-datastore-site`
    * `googlesitekit-datastore-forms`

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Make sure that the `googlesitekit-modules-analytics-4.js` script is loaded in the admin.

## Changelog entry

* Introduce new JS asset for upcoming GA4 integration.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by Hazlitte** [comment]
**QA Eng** ✅

With the `ga4setup` feature flag enabled the `googlesitekit-modules-analytics-4.js` script is loaded in admin.
