### ISSUE TITLE
Implement the ability to query and create GA4 properties via modules/analytics-4 datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2979]
The `modules/analytics-4` datastore should allow querying and creating GA4 properties.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/analytics-4` datastore should get a new selector `getProperties( accountID )` which uses the `GET:modules/analytics-4/data/properties` REST datapoint to list GA4 properties for an account, similar to how the `modules/analytics` selector of the same name does for UA properties.
* The `modules/analytics-4` datastore should get a new action `createProperty( accountID )` which uses the `POST:modules/analytics-4/data/create-property` REST datapoint to create a new GA4 property for an account.
    * [Learn more about the GA4 property object shape returned by the API (and REST datapoint) here.](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties#Property)

## Implementation Brief

* Create `assets/js/modules/analytics-4/datastore/properties.js` file to export partial datastore. Use the [`assets/js/modules/analytics/datastore/properties.js`](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/properties.js) datastore as an example.
  * Create a new fetch store for the `properties` endpoint:
    * Use `getProperties` base name.
    * Issue a GET request to the `modules/analytics-4/data/properties` endpoint with `accountID` query argument.
    * Set received properties under appropriate accountID key in the `properties` property of the state object in the `reducerCallback` callback.
    * The `argsToParams` callback should convert the incoming `accountID` argument to an object with `accountID` property.
    * Make sure that `accountID` is not empty in the `validateParams` callback.
  * Create a new fetch store for the `create-property` endpoint:
    * Use `createProperty` base name.
    * Issue a POST request to the `modules/analytics-4/data/create-property` endpoint with `accountID` query argument.
    * Add received property to the appropriate accountID key in the `properties` property of the state object in the `reducerCallback` callback.
    * The `argsToParams` callback should convert the incoming `accountID` argument to an object with `accountID` property.
    * Make sure that `accountID` is not empty in the `validateParams` callback.
  * Create a new `baseActions` object which contains a single generator function `*createProperty( accountID )`. This function should invoke and yield the `fetchCreateProperty` action from the fetch datastore created for the `create-property` endpoint and return the result of the execution. See an example [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/properties.js#L114-L119).
  * Create a new `baseSelectors` object which contains a single function `getProperties( state, accountID )` that returns properties associated with the provided accountID.
  * Create a new `baseResolvers` object which contains a single generator function `*getProperties( accountID )`. This function should invoke and yield the `fetchGetProperties` action from the fetch datastore created for the `properties` endpoint and return the result of the execution if the `getProperties` selector returns `undefined`.
  * Combine stores created for two endpoints with a new store created using `baseActions`, `baseSelectors` and `baseResolvers` objects and export the combined store as default export of the file. See an example [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/properties.js#L412-L423).
* Import the `properties` store in the `datastore/index.js` file and add it to the resulting `Data.combineStores(...)` function call.

### Test Coverage

* Add js tests for the new properties datastore.

### Visual Regression Changes

* N/A

## QA Brief

* Make sure that properties datastore in the analytics-4 module satisfy requirements defined in the AC section.

## Changelog entry

* Implement JS data store infrastructure to query and create GA4 properties.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@eugene-manuilov please add a QA Brief.

**Comment by eugene-manuilov** [comment]
QA brief is added.

**Comment by tofumatt** [comment]
QA ✅
