### ISSUE TITLE
Address Contributor issues - adminbar and confirmation message

### ISSUE THREAD

**Issue by lilybonney** [google/site-kit-wp#298]
## Bug Description

After logging in Contributors see:

* "Editing one of your posts" should be "viewing one of your published posts" - Contributors cannot edit their published posts and no data is available for draft posts.

## Screenshots

![Welcome to Site Kit message](https://user-images.githubusercontent.com/52471748/61414689-79262c00-a8e6-11e9-9eb7-6a5acbcd7d41.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Text changed to "viewing one of your published posts"

## Implementation Brief

`googlesitekit.permissions` have the same values for authors and contributors. Add new value to `canPublishPosts`
Show requested text depending on `canPublishPosts` permission https://github.com/google/site-kit-wp/blob/develop/assets/js/components/dashboard-splash/dashboard-splash-app.js#L119

## Changelog entry

*

**Comment by felixarntz** [comment]
Implementation brief looking good!

**Comment by lilybonney** [comment]
Assigning to @marrrmarrr for final review/approval!

**Comment by marrrmarrr** [comment]
LGTM
