### ISSUE TITLE
Implement the ability to query and create GA4 web data streams via modules/analytics-4 datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2980]
The `modules/analytics-4` datastore should allow querying and creating GA4 web datastreams.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/analytics-4` datastore should get a new selector `getWebDataStreams( propertyID )` which uses the `GET:modules/analytics-4/data/webdatastreams` REST datapoint to list GA4 web data streams for a property.
* The `modules/analytics-4` datastore should get a new action `createWebDataStream( propertyID )` which uses the `POST:modules/analytics-4/data/create-webdatastream` REST datapoint to create a new GA4 property for an account.
    * [Learn more about the GA4 web datastream object shape returned by the API (and REST datapoint) here.](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams#WebDataStream)

## Implementation Brief

* Create `assets/js/modules/analytics-4/datastore/webdatastreams.js` file to export partial datastore.
  * Create a new fetch store for the `webdatastreams` endpoint:
    * Use `getWebDataStreams` base name.
    * Issue a GET request to the `modules/analytics-4/data/webdatastreams` endpoint with `propertyID` query argument.
    * Set received datastreams under appropriate propertyID key in the `webdatastreams` property of the state object in the `reducerCallback` callback.
    * The `argsToParams` callback should convert the incoming `propertyID` argument to an object with `propertyID` property.
    * Make sure that `propertyID` is not empty in the `validateParams` callback.
  * Create a new fetch store for the `create-webdatastream` endpoint:
    * Use `createWebDataStream` base name.
    * Issue a POST request to the `modules/analytics-4/data/create-webdatastream` endpoint with `propertyID` query argument.
    * Add received datastream to the appropriate propertyID key in the `webdatastreams` property of the state object in the `reducerCallback` callback.
    * The `argsToParams` callback should convert the incoming `propertyID` argument to an object with `propertyID` property.
    * Make sure that `propertyID` is not empty in the `validateParams` callback.
  * Create a new `baseActions` object which contains a single generator function `*createWebDataStream( propertyID )`. This function should invoke and yield the `fetchCreateWebDataStream` action from the fetch datastore created for the `create-webdatastream` endpoint and return the result of the execution. See an example [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/properties.js#L114-L119).
  * Create a new `baseSelectors` object which contains a single function `getWebDataStreams( state, propertyID )` that returns web datastreams associated with the provided propertyID.
  * Create a new `baseResolvers` object which contains a single generator function `*getWebDataStreams( propertyID )`. This function should invoke and yield the `fetchGetWebDataStreams` action from the fetch datastore created for the `webdatastreams` endpoint and return the result of the execution if the `getWebDataStreams` selector returns `undefined`.
  * Combine stores created for two endpoints with a new store created using `baseActions`, `baseSelectors` and `baseResolvers` objects and export the combined store as default export of the file. See an example [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/properties.js#L412-L423).
* Import the `webdatastreams` store in the `datastore/index.js` file and add it to the resulting `Data.combineStores(...)` function call.

### Test Coverage

* Add js tests for the new webdatastreams datastore.

### Visual Regression Changes

* N/A

## QA Brief

* Check the `webdatastreams` datastore of the `analytics-4` module and make sure it contains actions and selectors requested in the AC section.

## Changelog entry

* Update the `modules/analytics-4` store with actions and selectors for creating and querying web data streams.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QA Brief?

**Comment by tofumatt** [comment]
QA ✅
