### ISSUE TITLE
Implement modules/analytics-4 datastore functionality for matching web datastream with property

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2981]
The `modules/analytics-4` datastore should be able to find a matching web data stream for a given property and the current site, as well as selecting it based on the property selected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/analytics-4` datastore should have a new selector `getMatchingWebDataStream( propertyID )` which, for the given property, checks whether there is a web data stream for that property that matches the current site’s URL in its `defaultUri` field (similar comparison to how we’re typically doing, i.e. ignore HTTP/HTTPS, www/non-www) and if so returns that web data stream object, or otherwise `null`.
* The `modules/analytics-4` datastore should have a new action `selectProperty( propertyID )` that sets the GA4 `propertyID` setting based on the given property and then handles side effect selections (similar to the `selectProperty` action in `modules/analytics`, however with slightly different behavior, focusing on the nested web data stream instead of profile/view):
    * Start by emptying any `webDataStreamID` and `measurementID` if set from before.
    * If set to create a new property, do nothing else.
    * Otherwise, check if there is a matching web data stream via `getMatchingWebDataStream` and if so set `webDataStreamID` and `measurementID` accordingly (the latter via the web data stream’s `measurementId` field).
    * Note that GA4 property objects have a [`name` attribute in the format `properties/{propertyID}`](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties#Property).  
The actual `propertyID` needs to be extracted from that string.
    * Note that GA4 web data stream objects have a [`name` attribute in the format `properties/{propertyID}/webDataStreams/{webDataStreamID}`](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams#WebDataStream).  
The actual `webDataStreamID` needs to be extracted from that string.

#### Step 1

* Add `export const PROPERTY_CREATE = 'property_create';` to the `assets/js/modules/analytics-4/datastore/constants.js` file.
* Create a utility function `isValidPropertyID( propertyID )` in the `assets/js/modules/analytics-4/util/validation.js` file. It should return `TRUE` if the `propertyID` is a string and consists of digits only.
* Create a utility function `isValidPropertySelection( propertyID )` in the `assets/js/modules/analytics-4/util/validation.js` file. It should return `TRUE` if the `propertyID` equals to `PROPERTY_CREATE`, otherwise call the `isValidPropertyID` function and return its result.

#### Step 2

* Add a new action `waitForWebDatastreams( propertyID )` to the `webdatastreams` datastore. It should return an action object with `WAIT_FOR_WEBDATASTREAMS` type and `{ proprtyID }` payload.
* Add a new controller `[ WAIT_FOR_WEBDATASTREAMS ]`  to the `webdatastreams` datastore. It should wait till the `getWebDatastreams( property )` selector is resolved. See an example here: https://github.com/google/site-kit-wp/blob/9ee354a5cc560159b900269e9b4b7955f9e1e146/assets/js/modules/analytics/datastore/properties.js#L222-L237

#### Step 3

* Add a new selector `getMatchingWebDatastream( propertyID )` to the `webdatastreams` datastore.
  * Pull web datastreams using the `getWebDataStreams` selector and reference URL using the `getReferenceSiteURL` selector of the `core/site` datastore.
  * Loop through all web datastreams and find one that has a domain name of the `defaultUri` property matching the domain name in the reference site URL ignoring `www.` prefix.
  * Return matched web datastream if one is found, otherwise NULL.
* Add a new action `selectProperty( propertyID )` to the `webdatastreams` datastore.
  * Validate the incoming `propertyID` using `isValidPropertySelection` function.
  * Set propertyID setting using `setPropertyID` action.
  * Empty `webDatastreamID` and `measurementID` settings using `setWebDatastreamID( '' )` and `setMeasurementID( '' )` actions.
  * Return if the `propertyID` equals to `PROPERTY_CREATE`.
  * Otherwise, wait till web datastreams are resolved by dispatching the `waitForWebDatastreams` action. See an example here: https://github.com/google/site-kit-wp/blob/9ee354a5cc560159b900269e9b4b7955f9e1e146/assets/js/modules/analytics/datastore/properties.js#L167
  * Grab matching web datastream using `getMatchingWebDatastream` selector. If it returns falsy result, do nothing and return. Otherwise set `webDatastreamID` and `measurementID` settings using `name` and `measurementId` properties of the matched web datastream. See the AC for instructions on how to extract datastream ID.

### Test Coverage

* Add tests for new actions and selectors.

### Visual Regression Changes

* N/A

## QA Brief

* Check `getMatchingWebDataStream` selector and `selectProperty` action and make sure that they satisfy requirements in the AC.

## Changelog entry

* Implement data store selector to detect whether a GA4 property has a web data stream that matches the current site.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
