### ISSUE TITLE
Clicking on any "See full stats in Analytics" link opens a 7 reporting period (no matter what reporting period was active within the plugin dashboard)ting period selected within the Site Kit dashboard

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2983]
## Bug Description

When clicking on the "See full stats in Analytics" a user is directed to the associated report on the Google Analytics web UI however it is always a report for the previous 7 days. This is regardless of what reporting period was selected within Site Kit. 

![ex](https://user-images.githubusercontent.com/41326532/111553492-6b404280-877c-11eb-876f-17c3e9f0db5e.gif)

- Example reporting URL within Site Kit (which directs users to a 7 day report):
`https://analytics.google.com/analytics/web/?authuser=****handle****%40gmail.com#/report/visitors-overview/a185640201w256367898p234768263/`

- Example 14 day reporting period URL within Analytics (Once changed from a 7 day to a 14 day reporting period within the Analytics UI):
`https://analytics.google.com/analytics/web/?authuser=****handle****%40gmail.com#/report/visitors-overview/a185640201w256367898p234768263/_u.date00=20210304&_u.date01=20210317/`

## Steps to reproduce

1. Navigate to any Analytics dashboard
2. Select any reporting period (other than the 7 day)
3. The Analytics web UI opens the 7 day report
4. Users must manually select the dates once more in the Analytics web UI

## Additional info

- Tested on SK 1.25.0, 1.27.0 and 1.28.0 - Same behaviour
- All Analytics links do direct users to the correct report, just the report period is always 7 days
- The behavior is the same for both the primary Site Kit dashboard and the Analytics dashboard links
- From checking GA4 it seems similar parameters can be passed: _u.date00%3D20210309%26_u.date01%3D20210310

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The **refactored versions of the** three widgets on the Analytics module page should all include the relevant date range parameters in their links to the Analytics frontend (see #2287 where this was already implemented for all existing Analytics widgets back then). Specifically:
    * `ModuleOverviewWidget` (see #2067)
    * `ModulePopularPagesWidget` (see #2068)
    * `ModuleAcquisitionChannelsWidget` (see #2069)
* The logic here already exists (via #2287), so this is only about using the approach from there in the new widget components too.

## Implementation Brief
* Using the following files:
	* `assets/js/modules/analytics/components/module/ModuleOverviewWidget/Header.js`,
	* `assets/js/modules/analytics/components/module/ModulePopularPagesWidget/Header.js`
	* `assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget/Header.js` once #3035 has been merged,
* Import the `generateDateRangeArgs` from `assets/js/modules/analytics/util/report-date-range-args.js`.
* Query the user's date range selection by querying the user data store with the `getDateRangeDates` selector, passing the `DATE_RANGE_OFFSET` constant from `assets/js/modules/analytics/datastore/constants.js` as value to the `offsetDays` key.
* Update usage of the `getServiceReportURL` selector to spread the result of the `generateDateRangeArgs` function, passing the user's date range as parameter to the function.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* 
* ensure the feature flag `widgets.moduleScreens` is set
* navigate to Site Kit's Analytics screen
* Change time period in header (to anything but _Last 7 days_)
* Open **See full stats in Analytics** links for each of the Widgets
* Observe the date range in Google Analytics matches that of Site Kit

## Changelog entry

* Fix Analytics links in new widgets on the Analytics module page to take into account selected days

**Comment by abdullah1908** [comment]
I can recreate this issue at my end & moving to execution.

**Comment by bethanylang** [comment]
Removed the Escalation label as this issue is now going through the Execution pipeline.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:

**Verified:**

These tests were run all widgets on the Google Analytics module in Site Kit. 

- Tested on 90 days - dates in Analytics (19 Jan 2021-18 Apr 2021)
- Tested on 28 days - dates in Analytics (22 Mar 2021-18 Apr 2021)
- Tested on 14 days - dates in Analytics (12 Apr 2021-18 Apr 2021) 
- Tested on 7 days - dates in Analytics (12 Apr 2021-18 Apr 2021)
