### ISSUE TITLE
Data error in Analytics, Request parameter is empty: metrics

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2986]
As reported in the [WordPress support forums](https://wordpress.org/support/topic/request-parameter-is-empty-metrics/#post-14201035) one user encounters dashboard error messages in both the Analytics and PageSpeed Insights widgets.

Analytics 
`Data error in Analytics, Request parameter is empty: metrics.`

Pagespeed Insights:
`Error: Request parameter is empty: strategy.`

This started occurring randomly, with Site Kit 1.27.0 active when reported. 

Console Errors:

![image](https://user-images.githubusercontent.com/41326532/111628109-bfccd780-87e7-11eb-90ac-5ac4f52fee2e.png)

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check
- [x] Incognito mode 
- [x] Checked users Site Health info, no identified causes
- [x] Additional .htaccess rules applied
- [x] Confirmed no modification of Site Kit placed snippet
- [ ] Uninstalled and reinstalled plugin
- [ ] User confirmed no "Critical errors" in their Site Health status
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Reset Site Kit
- [ ] Disconnected Site Kit
- [ ] Disconnected impacted service and connected once more
- [ ] Checked does the same occur from another admin users account
- [ ] Checked setup / viewing dashboards from another WordPress administrator account
 

## Additional Context

 - Plugin version: 1.27.0
 - [Site Health info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhe6GsQ3vwv5w4u7tMxIUPouwyanI-xKQRrlGc3me-b5uRrfLFPZ_wbBd1n92Ao0E4)
- Awaiting additional insights after updating to 1.28.0
 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@abdullah1908 Assigning to L1 for further inspection. No addition checks done on support side, with no addition insights from impacted user.

**Comment by abdullah1908** [comment]
For now I couldn't find any way to escalate this issue as I checked with the existing Site Kit setup. Also found the error in [Site Kit codebase](https://github.com/google/site-kit-wp/blob/develop/stories/utils/generate-widget-stories.js#L174) where its defined but couldn't get any clue. 

There would require more insights on it to escalate this issue*.

**Comment by bethanylang** [comment]
@abdullah1908 Based upon your last comment, it sounds like we don't have enough details to replicate and this might be an edge case. In that case, does it make sense to close this for now as we did with #3057 @jamesozzie ?

**Comment by bethanylang** [comment]
Closing.
