### ISSUE TITLE
Fix errors caused by "__experimentalResolveSelect" method removal from @wordpress/data

### ISSUE THREAD

**Issue by caseymorrisus** [google/site-kit-wp#2989]
The `develop` branch is throwing a new error due to a dependency update on the latest version of `@wordpress/data`. It looks like `registry.__experimentalResolveSelect` has been graduated to stable status via [#28544](https://github.com/WordPress/gutenberg/pull/28544). Unfortunately, the `__experimental` prefix has been completely removed without a deprecation phase — causing errors when checking if a module is active. I discovered this while doing post-merge testing of [#2514](https://github.com/google/site-kit-wp/issues/2514) — module activation is disabled (originally thought the merge broke newly introduced logic). An error is thrown within `<SetupModule>` as `__experimentalResolveSelect` is no longer a function.

There are two ways to fix this issue:

1. Set `@wordpress/data` version to the previous version — `4.26.8`
2. Modify all instances to use `registry.resolveSelect` — find & replace should work as this is only a name change.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@caseymorrisus I think this should naturally be handled in #1769. If you agree, let's close it; otherwise let's clarify why it would be needed separately 👍

**Comment by aaemnnosttv** [comment]
Closing as a non-issue with the current code base and something we will need to address in #1769 when we upgrade the package anyways.
