### ISSUE TITLE
Explore enhancements for site owner notifications

### ISSUE THREAD

**Issue by lilybonney** [google/site-kit-wp#299]
**Description**

There are a number of potential enhancements for site owner notifications to be explored further.

There are some nuances with the "increase in $METRIC" wins. The expectation of the user is that some time has to pass, so there are two time periods to compare and calculate the increase "before" and "after" - it's confusing to see the win right at setup, since they just started using the module.

What might help here is to understand better the comparison timeframes that trigger these wins.

E.g. For the "increased page views" we could show a timeframe: "over the past 4 weeks"

![Increased page views](https://user-images.githubusercontent.com/52471748/61415170-eab2aa00-a8e7-11e9-98b9-6127fc65acd8.png)

Do we have wins for other timeframes (e.g. week or similar?) Can we show this win after a week has passed since setup, when the user logs in again?

For increased visitors, we don't show the timeframe -- is this "record-high" since we started measuring? Since you set up the plugin? Since the site was created?

![Congrats on more website visitors](https://user-images.githubusercontent.com/52471748/61415286-26e60a80-a8e8-11e9-8292-7f794f18a26c.png)

Most of the other wins have well defined triggers (X published posts), so for these we won't need to add extra conditions.

For "First XX posts", let's say the user activates the plugin, and they already have XX posts published on that site -- would we immediately show that win?

**Comment by marrrmarrr** [comment]
Adding some relevant comments from the discussion in the support forum: 
https://wordpress.org/support/topic/not-ready-for-primetime-send-this-back-to-beta/#post-12173601 

#1 state the period to which the traffic increase is compared to.
#2 have an option to configure traffic comparison “congratulation alerts” to a periods such as “a year ago”, “last thirty days”, or “last week”

**Comment by marrrmarrr** [comment]
This will be part of Notifications work, but not helpful on its own. Closing.
