### ISSUE TITLE
Daily Stats

### ISSUE THREAD

**Issue by myedgy** [google/site-kit-wp#2990]
Hi there,

Regarding this support ticket: https://wordpress.org/support/topic/today-stats/#post-14206004 

I create a feature request.

Can you add a “today” and “yesterday” tab in the overviews (Analytics, Search Console, AdSense)? 
Because now it’s only Last 7 days, Last 14 days, Last 28 days and Last 90 days.

Also, an “active users in real time” for the analytics tab would be great.

Today and yesterday are viewed a lot in my past counter. I miss this option a lot in a plugin that's made by Google. And I'm not the only one: 

– https://github.com/google/site-kit-wp/issues/631
– https://github.com/google/site-kit-wp/issues/2757

Thank you for considering this.

**Comment by jamesozzie** [comment]
Many thanks for opening a GitHub issue. As this look similar to the feature request you've already referenced (#631) I'll close this as a duplicate. 

I noticed also you added some additional context to that existing feature request, which is excellent. All feedback is super useful as we're planning on allowing users to customize the dashboards as per [this comment.](https://github.com/google/site-kit-wp/issues/631#issuecomment-633557226)
