### ISSUE TITLE
Mis-alignment of Goals title and data in Site Kit Dashboard 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#2992]
## Bug Description

While testing #2858  I noticed that the `Goals Completed` title and data does not align with the `Unique Visitors from Search ` due to the missing change arrow because a change of zero currently results in nothing output there.

![image](https://user-images.githubusercontent.com/73545194/111764032-bcb41300-88dd-11eb-846e-24cc72853df4.png)

Would be good that it is aligned in the widget. 

## Steps to reproduce

Find a test site with `Google Analytics` connected. 
The GA account has to have goals set up, but with zero completions. 
Go to Site Kit Dashboard and look under `Search Funnel`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Goals widget content should be vertically aligned with the other widgets in the Search Funnel, even if there is no change percentage displayed below the sparkline.
* This should be fixed in a holistic way, so that other widgets with that appearance would get that fix as well.

## Implementation Brief

* Refactor `assets/js/components/DataBlock.js`:
  * where the percentage change is formatted, change the control flow to format 0 if there is no change (i.e. `changeFormatted` should be `0%` in this scenario) instead of ignoring it.
  *  Output this `0%` inside the `span.googlesitekit-data-block__value` when there is no change, instead of outputting nothing.
  * Add a CSS class, `googlesitekit-data-block__change--no-change` to `.googlesitekit-data-block__change` when the change is 0.
* In `assets/sass/components/global/_googlesitekit-data-block.scss`, add a `visibility: hidden` style rule for `googlesitekit-data-block__change--no-change`. 

### Test Coverage

* No new tests; existing tests should pass.

### Visual Regression Changes

* The goals widget should have the same visual spacing as the other widgets when there is no change in Goals, even though the percentage change is not visible.

## QA Brief

* Follow 'steps to reproduce' above
* The goals widget should have the same visual spacing and alignment as the other Search Funnel widgets, even though it is not displaying the percentage change.

## Changelog entry

* Fix broken alignment of data block elements when there is one with zero data.

**Comment by tofumatt** [comment]
IB ✅

**Comment by cole10up** [comment]
### **QA ✅**

Setup goals on my personal site, confirmed the alignment below after the merge in develop:
![image](https://user-images.githubusercontent.com/57115907/114996616-dc464900-9e53-11eb-940f-fcb0998de1e8.png)

Checked window sizes:
![image](https://user-images.githubusercontent.com/57115907/114996712-f2eca000-9e53-11eb-949e-668ed016b0a1.png)

![image](https://user-images.githubusercontent.com/57115907/114996797-0992f700-9e54-11eb-9317-7a47b2b57d51.png)

Looks great, setting to approval
