### ISSUE TITLE
Add placeholder to all "Other" text input fields in user input flow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2993]
When the "Other" text input field is not focused, it's basically impossible to notice it visually. Therefore, a placeholder should be added to make it clear that this option supports custom input.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All text input fields for an "Other" choice throughout different questions of the user input flow should have a placeholder _Enter your own answer here_

## Implementation Brief

* Edit the file `assets/js/components/user-input/UserInputSelecfoptions.js`
* Because the `TextField` component does not support both a label and a placeholder add a `<label>` for the text field of `Enter your own answer here` with a class of `screen-reader-text` to hide it.
*  Add the prop `noLabel` to the `TextField` to output the label as a placeholder

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Using the user input flow
* For questions 1 - 4 of 5, check that the "Other" field has a placeholder of "Type your own answer" and a hidden label of "Enter your own answer here". ( `class="screen-reader-text"` ) 

## Changelog entry

* Add placeholder to all "Other" text input fields in user input flow

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Looks like this accidentally landed in "Approval" instead of "Code Review"? Moving it back.

**Comment by Hazlitte** [comment]
@felixarntz Apologies, my mistake, thank you for spotting that.

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- For questions 1 - 4 of 5, the `Other` field has a placeholder of `Type your own answer` appears
- In a ddition, a hidden label of `Enter your own answer here` can be found in the code. 
- This was tested on desktop and mobile/tablet devices. 

![image](https://user-images.githubusercontent.com/73545194/114551493-0e11b100-9c96-11eb-80b0-75b64ddf34b5.png)

@Hazlitte @felixarntz while this is not linked to this ticket, I wanted to add an observation: when you select an answer other than `Other` the screen is grey and inactive, but the `Type your own answer` text stands out still.  I am wondering if this could be also greyed out so it looks inactive like the rest of the form.  Hope this makes sense. 

Would you like me to create a new ticket for this? 

![image](https://user-images.githubusercontent.com/73545194/114554368-3ea71a00-9c99-11eb-9524-1a6ea6b14e2c.png)

**Comment by felixarntz** [comment]
@wpdarren Ah good observation, yeah this looks weird as is. A new follow-up issue sounds great, thanks!
