### ISSUE TITLE
Make use of new wp_get_inline_script_tag() function 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2994]
## Feature Description

As of WordPress 5.7 there has been a new wp_get_script_tag() function that can be used for outputting certain scripts. [One user in the support forums](https://wordpress.org/support/topic/use-new-wp_get_inline_script_tag-to-allow-for-nonce-and-proper-csp/) raised the question of Site Kit using this new function within the plugin. 

Information on this new function below:
[Introducing script attributes related functions in WordPress 5.7
](https://make.wordpress.org/core/2021/02/23/introducing-script-attributes-related-functions-in-wordpress-5-7/)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Google\Site_Kit\Core\Util\BC_Functions` should receive the following functions that were added in WordPress 5.7:
    * `wp_get_script_tag( $attributes )`
    * `wp_print_script_tag( $attributes )`
    * `wp_get_inline_script_tag( $javascript, $attributes )`
    * `wp_print_inline_script_tag( $javascript, $attributes )`
* For each of these, if the respective function exists, it should be used as is. If not, each function should receive its most basic implementation to return/output the respective tag (without any additional nuances added by the WP function, e.g. default attributes, applying filters etc.), i.e. something like the following:
    * `wp_get_script_tag( $attributes )` should simply return the `<script>` tag with the required attributes.
    * `wp_print_script_tag( $attributes )` should `echo wp_get_script_tag( $attributes );`.
    * `wp_get_inline_script_tag( $javascript, $attributes )` should simply return the `<script>` tag with the required attributes. and the JavaScript code inside (separated with newlines the same way it is in the [core function](https://developer.wordpress.org/reference/functions/wp_get_inline_script_tag/)).
    * `wp_print_inline_script_tag( $javascript, $attributes )` should `echo wp_get_inline_script_tag( $javascript, $attributes );`.
    * To get the attributes string, a similar private method similar to WP's [`wp_sanitize_script_attributes( $attributes )`](https://developer.wordpress.org/reference/functions/wp_sanitize_script_attributes/) can be used.
    * Note: The goal here is not to exactly replicate (and thus also maintain) core's behavior for these functions. The goal is just to have the most basic replacement available so that Site Kit can simply call these functions to render script tags without being concerned whether the function is available. Only with a WP core version that actually has these tags the user should get the relevant benefits (e.g. a future WordPress version might add automatic `nonce` attribute insertion etc.).
* All PHP code in which Site Kit currently manually returns or outputs an empty `script` tag (with a `src` attribute) should use `BC_Functions::wp_get_script_tag()` / `BC_Functions::wp_print_script_tag()`.
* All PHP code in which Site Kit currently manually returns or outputs a `script` tag with JS content inside should use `BC_Functions::wp_get_inline_script_tag()` / `BC_Functions::wp_print_inline_script_tag()`.

## Implementation Brief

Using the class `Core/Util/BC_Functions.php`:

* Add a private function `sanitize_attributes` which receives the `$attributes` array and returns a string of the key value pairs similar to the [wp_sanitize_script_attribute](https://developer.wordpress.org/reference/functions/wp_sanitize_script_attributes/) core function which was added in 5.7.

* Add a public function `wp_get_script_tag` which receives the `$attributes` array
  * if the `wp_get_script_tag` function exists use it with the `$attributes` and return the result
  * if the function does not exist create an attributes string of the key value pairs using the new `sanitize_attributes` method and return it with a `<script>` tag.  Something like:
    `sprintf( "<script %s></script>\n", $attributes_string ) );`

* Add a public function `wp_print_script_tag` which receives the `$attributes` array
  * if the `wp_print_script_tag` function exists use it with the `$attributes` and return the result
  * if the function does not exist return `echo wp_get_script_tag( $attributes )`

* Add a public function `wp_get_inline_script_tag` which receives `$javascript` and `$attributes`
  * if the `wp_get_inline_script_tag` function exists use it with `$javascript` and `$attributes` and return the result
  * if the function does not exist return a `<script>` tag with an attributes string from `sanitize_attributes` with the `$javascript` contained within the tag.  Similar to:
    `sprintf( "<script%s>%s</script>\n", $attributes_string, $javascript )`

* Add a public function `wp_print_inline_script_tag` which receives `$javascript` and `$attributes`
  * if the `wp_print_inline_script_tag` function exists use it with `$javascript` and `$attributes` and return the result
  * if the function does not exist use the similar new method in this class and `echo $this->wp_get_inline_script_tag( $javascript, $attributes )`

Search the PHP code for the manual output of `<script>` tags.  Where suitable, if the return or output is:
* an empty `<script>` tag with a `src` attribute, use `BC_Functions::wp_get_script_tag()` or `BC_Functions::wp_print_script_tag()` accordingly
* a `<script>` tag with JS content inside, use `BC_Functions::wp_get_inline_script_tag()` or `BC_Functions::wp_print_inline_script_tag()` accordingly

### Test Coverage

* n/a

### Visual Regression Changes

* n/a

## QA Brief

* All the manially output `script` tags that contain javascript code should be using the new static methods of BC_Functions. 
* Aforementioned `script` tags should work on all supported SiteKit versions of WordPress.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
@kuasha420 would you please add a QAB?

**Comment by kuasha420** [comment]
@aaemnnosttv Done!

**Comment by tofumatt** [comment]
QA ✅
