### ISSUE TITLE
Can't setup Analytics

### ISSUE THREAD

**Issue by eduardogoncalves** [google/site-kit-wp#3]
**Describe the bug**
Can't setup Analytics on my site: https://www.saibatudomt.com.br/

`Blocked script execution in 'https://www.saibatudomt.com.br/?tagverify=1' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

![image](https://user-images.githubusercontent.com/4308648/59809909-d1aadf00-92d0-11e9-9b33-98b0cb9b3a5e.png)

![image](https://user-images.githubusercontent.com/4308648/59809944-facb6f80-92d0-11e9-8de2-f168d0e93186.png)

**System Information (please complete the following information):**
 - Plugin Version  1.0.0-beta.1

**Comment by jamesozzie** [comment]
@eduardogoncalves Can you temporarily disable AMP and then try to connect Analytics again.

**Comment by eduardogoncalves** [comment]
I disabled AMP, and change my theme to Twenty Seventeen, but didn't work.

![image](https://user-images.githubusercontent.com/4308648/59855078-38b4ac00-9342-11e9-8c54-bacf69898eab.png)


![image](https://user-images.githubusercontent.com/4308648/59855024-17ec5680-9342-11e9-9ac0-3079104afcf5.png)

**Comment by Jaymesbond11** [comment]
Got the same issue for this website [susannevolkert.de](https://www.susannevolkert.de). I have installed everything and the ticks are all green ("Connected"). Nevertheless the analytics data is not shown. I have got the same failure as described.

**Comment by ivankristianto** [comment]
Thanks for the report @eduardogoncalves and @Jaymesbond11 
This is related to issue #11 
and we are currently working to fix it.

**Comment by jamesozzie** [comment]
Duplicate of #11

**Comment by eduardogoncalves** [comment]
close #3 in favor of #11
