### ISSUE TITLE
Ensure adding a www prefix doesn't result  in reporting of Analytics and AdSense from that date only (or vice versa)

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3005]
## Bug Description

As raised in the [WordPress support forums](https://wordpress.org/support/topic/past-performance-not-showing-after-url-change-from-www-to-non-www-subdomain/page/2/#post-14219206) at present when a user adds www to their site URL they're then prompted to setup Site Kit once more, with the plugin identifying this new URL.

With any such www prefix modifications Site Kit should maintain the same Analytics or AdSense data, and not populate dashboards or display data based only on this new URL.  

## Steps to reproduce

1. Login to a site with Analytics and AdSense data
2. Add www in the defined URLs under "_Settings > General Settings_" in a standard WordPress setup
3. Login to your site once more and setup Site Kit
4. Wait for data to appear - the services will already be connected, but the dashboards and data that are populated will be based on the www version of your site only, with no legacy information from before the www change. 

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/112059363-a9aa7880-8b53-11eb-8dce-6db36a9a08de.png)

## Additional Context

 - Tested and reproduced in support, Site Kit version 1.28.0
 - A filter was introduced recently for reporting on a WordPress specific install only, with some sites using WordPress within a subdirectory of a primary non WordPress domain

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics reports should request data for the current domain **regardless of with or without `www.` prefix**.
    * The existing [Analytics report endpoint](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet) dimension filter that filters by `ga:hostname` can be updated relying on the [`IN LIST` operator](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#operator).
* AdSense reports should request data for the current domain **regardless of with or without `www.` prefix**.
    * The existing [AdSense report endpoint](https://developers.google.com/adsense/management/v1.4/reference/accounts/reports/generate) `filter` parameter can be updated with the necessary [`OR` logic](https://developers.google.com/adsense/management/reporting/filtering#OR).

## Implementation Brief

* Update the `Analytics::create_analytics_site_data_request` method:
  * Use the `IN_LIST` operator instead of `EXACT` for the `ga:hostname` dimension;
  * Update expressions for the same dimension to include the hostname with and without leading `www.`.
* Update the `AdSense::create_adsense_earning_data_request` method to use the hostname for the `DOMAIN_NAME` filter with and without `www.`.
  * Check the documentation on how to use a filter with `OR` logic: https://developers.google.com/adsense/management/reporting/filtering#OR

### Test Coverage

* Update existing tests if any is broken due to the aforementioned changes.

### Visual Regression Changes

* N/A

## QA Brief

This brief is based on testing from a local environment.  If testing on a published website edit the site URL in `Settings -> General Settings` as usual and add/remove the `www.` prefix.
* Reset Site Kit
* Use Site Kit developer settings plugin to set the custom site url to `https://www.elasticpress.io`
* Setup Site Kit
* Connect Analytics
* Connect Adsense
* Check Analytics page data `Site Kit -> Analytics` and note the four main values as per the screenshots in the issue description
* Check Adsense page data `Site Kit -> Adsense` and note the four main values

* Reset Site Kit
* Use Site Kit developer settings plugin to set the custom site url to `https://elasticpress.io`
* Setup Site Kit
* Connect Analytics
* Connect Adsense
* Check Analytics page data again and that they match the noted values
* Check Adsense page data again and that they match the noted values

## Changelog entry

* Ensure changing the site URL between HTTP and HTTPS or `www.` and non-`www.` does not impact the results displayed in Analytics and AdSense widgets.

**Comment by bethanylang** [comment]
Noting that per discussion in today's meeting, it appears that this only affects `www` vs. non-`www` change, **not** `https` vs. `http` change.

**Comment by tofumatt** [comment]
IB ✅

**Comment by felixarntz** [comment]
If this gets ready by tomorrow, we should include it in the 1.30.0 release - let's try to prioritize it.

cc @Hazlitte @aaemnnosttv

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

Tested this fix on a live site.  Initially, it was set to `domain-name.com` and I made a note of the Analytics and Adsense data. I then changed the domain name to `www.domain-name.com` and reconnected to Site Kit.  When looking at the two modules the data remained the same between the www and non www domain change in general settings.
