### ISSUE TITLE
site kit is keep on disconnecting from my website.

### ISSUE THREAD

**Issue by Zameer42** [google/site-kit-wp#3006]
I have connected the google site kit with my website. but it keeps on disconnecting from my website after some time. I always have to connect it again. I don't know why is it happening. would really appreciate your input on this issue.

**Comment by jamesozzie** [comment]
Hi @Zameer42. Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.
