### ISSUE TITLE
Ad Blocker detected despite no such ad blocker active

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3007]
## Bug Description

As reported in #1491 one user is unable to view their AdSense dashboards within Site Kit, with an Ad Blocker notice appearing. This notice appears despite checking while in troubleshooting mode using the Health Check & Troubleshooting plugin - from a Chrome browser incognito window

Ad AdSense level the below is reported:
```
Your site isn’t ready to show ads
We’ve found some policy violations on your site which means your site isn’t ready to show ads yet.
```

## Screenshots

**_There are some Ad Block code references when checking the users source code_** 

![image](https://user-images.githubusercontent.com/41326532/112163081-97c4e600-8be4-11eb-8301-d76bb91514c4.png)

**Console errors that appear below**

![image](https://user-images.githubusercontent.com/41326532/112163215-b88d3b80-8be4-11eb-9546-29ae3b4b3fa7.png)

_**CORS policy notices**_

![image](https://user-images.githubusercontent.com/41326532/112163810-4701bd00-8be5-11eb-8a95-c6e8533c75cf.png)

## Additional context
- Site is not approved at AdSense level yet
- User does have AdSense traffic (via YouTube)
- User is unable to open WP support topic

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check
- [x] Incognito mode 
- [ ] Checked users Site Health info, no identified causes
- [x] Confirmed no modification of Site Kit placed snippet
- [ ] Uninstalled and reinstalled plugin
- [ ] User confirmed no "Critical errors" in their Site Health status
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Disconnected Site Kit
- [ ] Disconnected impacted service and connected once more
- [ ] Reviewed error logs 
- [ ] Reviewed XHR requests 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@rafapontederino Let's troubleshoot this issue from here as opposed to the previously closed support topic. In order to do so please share a full list of plugins you have active, or preferably provide your [Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) here.

**Comment by rafapontederino** [comment]
@jamesozzie attached is the list of plugins. But in the Site Health Information form, I confuse about 
![Screenshot (49)](https://user-images.githubusercontent.com/80829188/112183398-812b8880-8bfe-11eb-9431-75bbacf92c42.png)
![Screenshot (50)](https://user-images.githubusercontent.com/80829188/112183403-825cb580-8bfe-11eb-9329-f914e0332d8a.png)
![Screenshot (51)_LI](https://user-images.githubusercontent.com/80829188/112183404-825cb580-8bfe-11eb-814f-ccd1ca7e2ca8.jpg)


what to input for the first answer, could you please provide more info?

**Comment by jamesozzie** [comment]
@rafapontederino Apologies, my mistake. You can use [this WordPress URL](https://wordpress.org/support/topic/read-first-welcome-to-the-site-kit-support-forums-3/) reference to share.

**Comment by rafapontederino** [comment]
@jamesozzie I did submit my Site health Information form

**Comment by jamesozzie** [comment]
Many thanks for sharing. I noticed what looks like a GoDaddy CDN active on your site, with content served from secureservercdn.net. Can you try and disable this CDN at host level and let me know if the same issue persist? 

You'll need to also make your website live while checking, it seems down at present.

**Comment by rafapontederino** [comment]
Could you please tell me where exactly I can disable the CDN?

**Comment by rafapontederino** [comment]
I still cannot access secureservercdn.net
![Screenshot (52)](https://user-images.githubusercontent.com/80829188/112224596-c4e8b700-8c2b-11eb-9bcd-cd01676dd452.png)

**Comment by jamesozzie** [comment]
@rafapontederino You don't access that domain directly. Please check for any CDN options within your GoDaddy configuration, or any other caching or optimization feature from your GoDaddy hosting configuration. Once you temporarily disable any such feature please ensure your site is live before attempting to connect the AdSense module once more.

**Comment by rafapontederino** [comment]
Yes finally :)
Thanks, @jamesozzie. But what I should do with the CDN configuration? Should I keep it off, or I need to turn on it again?

![Screenshot (53)_LI](https://user-images.githubusercontent.com/80829188/112292879-d06ec900-8c91-11eb-8532-7efcb980e752.jpg)
![Screenshot (54)_LI](https://user-images.githubusercontent.com/80829188/112292889-d2388c80-8c91-11eb-8469-babd4d0d251b.jpg)

**Comment by jamesozzie** [comment]
@rafapontederino I'll need to check this configuration myself, I can't be sure. Please allow me some time to check. In the meantime can you confirm that when you access the AdSense tab or the AdSense edit screen within Site Kit (Site Kit > Settings > AdSense > Edit) that you no longer see the Ad Blocker related notice?

**Comment by rafapontederino** [comment]
@jamesozzie Ok thanks, I don't see any Ad Blocker-related notice.

![Screenshot (55)](https://user-images.githubusercontent.com/80829188/112302582-8ab6fe00-8c9b-11eb-980e-c8c5fc64ae8c.png)
![Screenshot (56)](https://user-images.githubusercontent.com/80829188/112302589-8b4f9480-8c9b-11eb-9cdb-48575c9837eb.png)
![Screenshot (57)](https://user-images.githubusercontent.com/80829188/112302592-8be82b00-8c9b-11eb-8b89-9f4a66906dc1.png)

**Comment by jamesozzie** [comment]
Great to know, really appreciate your screenshots and troubleshooting efforts, in particular as others did report similar notices in the support forums. I'm going to check a similar setup today and I'll inform you of any CDN findings.

**Comment by rafapontederino** [comment]
Thanks, @jamesozzie, many thanks for your help and support. Looking forward to hearing some updates from you

**Comment by jamesozzie** [comment]
I've tested a GoDaddy install and I've been [unable to recreate](https://recordit.co/3i12JVYko4) the same notice from my side. If it's possible for you to share the following we can hopefully ensure you can once again reenable the GoDaddy CDN:

1. Do you have any [additional services](https://i.imgur.com/v32mLOV.png) active at GoDaddy hosting level?
2. Did you recently switch to https on your site?
3. Did you have Site Kit setup on this site previous from another domain, I noticed a migration plugin active.

**Comment by jamesozzie** [comment]
Impacted users from support forums - 4 in total so far (1 in this GitHub thread and not in support forums)  -  GoDaddy users while 1 unconfirmed although likely from inspection

- https://wordpress.org/support/topic/ad-blocker-detected-you-need-to-disable-it-in-order-to-set-up-adsense-2 **Unresolved** ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNik_JWvvqQPOfYIGqQPkDJ_chOIDKDXyImYwWERLGZKWeAXvlmD4K0LQj5ZPwE98Lk)) 
- https://wordpress.org/support/topic/ad-blocker-detected-you-need-to-disable-it-in-order-to-set-up-adsense-3 **Unresolved** ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNi7daldAUBE5p1kdG0XMwmH_gs9bp_betJdB_nRNjtKG7chm4J8iD92WV2NJxj9IuM)) 
- https://wordpress.org/support/topic/ad-blocker-detected-you-need-to-disable-it-in-order-to-set-up-adsense/ **Unresolved**

No common plugins from inspecting all 3 provided SH info forms. Caching at hosting level possible cause.

**Comment by rafapontederino** [comment]
1. I don't have any additional services active at GoDaddy hosting level (see picture below)
2. I did not switch to HTTPS, but since the SSL certificate is qualified, the HTTPS is on (I am not sure about this)
3. I have migrated the content from wp localhost that I've created, no site kit set up on the localhost

![Screenshot (59)](https://user-images.githubusercontent.com/80829188/112312115-bc819200-8ca6-11eb-81ca-e3a446dcb8d2.png)

**Comment by jamesozzie** [comment]
@rafapontederino Many thanks for sharing the additional insights. As we've now identified the cause I'll close this support based issue as I've added context to a bug report (#3018)

I'll check this with the team as this requires further inspection.

**Comment by rafapontederino** [comment]
I tried to deactivate migrating plugin, then enabled the CDN, but it turns back to adblocker detected (pictures are attached)

![Screenshot (74)_LI](https://user-images.githubusercontent.com/80829188/112684510-70d01380-8e73-11eb-96f8-fceaf2c9d4c5.jpg)
![Screenshot (75)_LI](https://user-images.githubusercontent.com/80829188/112684520-72014080-8e73-11eb-973f-bda1aace8ec3.jpg)
![Screenshot (76)_LI](https://user-images.githubusercontent.com/80829188/112684521-73326d80-8e73-11eb-9684-88eef00c550e.jpg)

**Comment by jamesozzie** [comment]
Thanks for the update @rafapontederino, you're insights have been super helpful while we investigate this. I've added other impacted users to #3018. 

If you're looking for perform additional troubleshooting on this (as we're also doing) feel free to share a video recording of your experience _**while in troubleshooting mode**_ using the Health Check & Troubleshooting plugin. If you can once again have your [console errors](https://imgur.com/KyLAzgH.png) tab open in Chrome developer tools we may be able to gather insights on possible causes. 

You can use a service such as [Loom](https://www.loom.com/) or [RecordIt ](https://recordit.co/)to share privately, and use the same form you previously used if you prefer to share privately.

**Comment by rafapontederino** [comment]
Thanks @jamesozzie I didn't find any error report in console errors

![Screenshot (76)](https://user-images.githubusercontent.com/80829188/112689809-0c18b700-8e7b-11eb-8b48-d109e8db147b.png)

**Comment by rafapontederino** [comment]
Hi @jamesozzie , Now I cannot open my website purnapraja.org nor the wp-admin. Do you think what is the problem? I tried to enable the CDN but still not work.

Nb: I put 2 banners of a hosting provider (but not GoDaddy), do you think it could be the problem?

**Comment by rafapontederino** [comment]
@jamesozzie Now I can open it

**Comment by rafapontederino** [comment]
But so so slow

**Comment by jamesozzie** [comment]
@rafapontederino Good to hear it's working for you once more. I can't be sure what was occurring. We're still investigate the CDN conflict with Site Kit. If you happen to encounter further hosting related queries the GoDaddy support channels are quite good.

**Comment by jamesozzie** [comment]
@rafapontederino Just to let you know we're aware of the problem and we're working on a [solution at present](https://github.com/google/site-kit-wp/issues/3018). Thank you once again for helping us to identify this, therefore ensuring the plugin works for others as expected. While you were the first to report this other users have since reported the same.
