### ISSUE TITLE
Weird behavior of the search term input fields

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3009]
## Bug Description

Search term input fields don't allow you to enter a space at the end (thus users can't enter search terms consisting of multiple words) and when you try to edit an existing keyword, the cursor jumps to the end.

## Steps to reproduce

1. Go to the search terms screen of the user input settings flow.
2. Try to enter a multi-word keyword or edit something in the middle of the entered keyword.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Looks like this was already fixed in another issue/PR 👍 
![image](https://user-images.githubusercontent.com/1621608/114531429-90798100-9c54-11eb-8d57-22c2f9221eb7.png)
