### ISSUE TITLE
Render ad blocker warning in AdSense dashboard widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3011]
## Bug Description

For the legacy/current version of the dashboard, the ad blocker warning renders above the two AdSense widgets when relevant (see e.g. https://github.com/google/site-kit-wp/issues/1491#issuecomment-804935887). This is a bit odd, but it's not worth fixing it for the legacy widgets.

For the refactored versions using the Widget API though, both AdSense widgets that render in the dashboard should be updated to conditionally return the ad blocker component.

Note that this problem only surfaces with the `widgets.dashboard` feature flag enabled at this point.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense `DashboardSummaryWidget` and `DashboardTopEarningPagesWidget` components should be updated to render the `AdBlockerWarning` component only if an ad blocker is enabled.
* The `AdBlockerWarning` returned should be wrapped in the same `Widget` container that would be regularly used for the respective widget.

## Implementation Brief

* Ensure that the `widgets.dashboard` feature flag is enabled 

### 1. DashboardSummaryWidget

* Open the [DashboardSummaryWidget](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/components/dashboard/DashboardSummaryWidget.js)
* Inside the select block at the top of the function, include a check to the AdSense store's `isAdBlockerActive` selector to determine if ad blockers are enabled.
* If Ad blockers are enabled, return early using the `AdBlockerWarning` component, being sure to wrap it in the same `Widget` markup as the happy path return statement, i.e.: 
  ```JS
  <Widget className="googlesitekit-dashboard-adsense-stats mdc-layout-grid">
    <div className="mdc-layout-grid__inner">
      <div className="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
        // ... AdBlockerWarning component
      </div>
    </div>
  </Widget>
  ```
* This new early return should come first, above the existing early returns (for error / loading etc.)

### 2. DashboardTopEarningPagesWidget
* Open [DashboardTopEarningPagesWidget](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js)
* Inside the select block at the top of the function, include a check to the AdSense store's `isAdBlockerActive` selector to determine if ad blockers are enabled.
* If Ad blockers are enabled, return early using the `AdBlockerWarning` component, being sure to wrap it in the same `Widget` markup as the happy path return statement, i.e.: 
  ```JS
  <Widget noPadding Footer={ /* ... */ }>
    // ... AdBlockerWarning component
  </Widget>
* This new early return should come first, above the existing early returns (for error / loading etc.)

### Test Coverage

* No new tests required; existing tests should pass.

### Visual Regression Changes

* Ad blocker warning should appear where the AdSense components normally appear on the dashboard, if ad blockers are detected.

## QA Brief

* Ensure the `widgets.dashboard` feature flag is enabled
* Ensure AdSense is connected
* Turn on your ad blocker of choice
* Visit the Site Kit dashboard and scroll down to the AdSense components under the `Earnings` heading
* You should see an ad blocker warning where the widgets would normally be.

## Changelog entry

* Update AdSense dashboard widgets to render ad blocker warning

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  Engineer for clarification ⚠️ 

@johnPhillips this passes the QAB, but I noticed error messages in the console and wanted to make sure that this was correct.  There are a number of errors with the same message  `Google Site Kit API Error method:GET datapoint:earnings type:modules identifier:adsense error:"You are probably offline."` This might be expected but wanted to check. 

**Verified:**

When user visits the Site Kit dashboard and scrolls down to the AdSense components under the Earnings heading,  an ad blocker warning where the widgets would normally be.

![image](https://user-images.githubusercontent.com/73545194/115256813-77c30c80-a127-11eb-815b-d33bc00cde65.png)

**Comment by johnPhillips** [comment]
@wpdarren thanks for checking.
I believe that's all to be expected. The console is telling you that the client (i.e. the browser) has blocked the requests. That will be the ad blocker.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

When user visits the Site Kit dashboard and scrolls down to the AdSense components under the Earnings heading, an ad blocker warning where the widgets would normally be.  - [Screenshot](https://user-images.githubusercontent.com/73545194/115269275-0be6a100-a133-11eb-9095-969714d4b149.png)
