### ISSUE TITLE
Include option to insert the Anti Flicker snippet when connecting Optimize

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3013]
## Feature Description

When a user is setting up Optimize at present it's required for the user to setup the Experiment at [optimize.google.com](https://optimize.google.com)

During testing the experiment it's always suggested that users install the anti flicker snippet. While this is only a suggestion which most users won't require having this as an option will allow users to insert this snippet without having to manually insert this into their theme files. 

![image](https://user-images.githubusercontent.com/41326532/112205039-4d575f80-8c0c-11eb-9a48-e7bca0dab7f6.png)

Example anti flicker snippet ([reference](https://support.google.com/optimize/answer/7100284#example-anti-flicker-snippet)):

```
<HTML>
<HEAD>
<!-- anti-flicker snippet (recommended)  -->
<style>.async-hide { opacity: 0 !important} </style>
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',4000,
{'CONTAINER_ID':true});</script>
```

Additional context
- [Reasons why a user may need to install the anti flicker snippet ](https://support.google.com/optimize/answer/7100284?hl=en)
- This suggestion is always shown to users during Optimize setup
- This was raised by a couple of users in the support forums. ([Topic One](https://wordpress.org/support/topic/optimize-page-flickers-how-to-fix/#post-14227976) | [Topic Two](https://wordpress.org/support/topic/avoid-content-flicker-with-optimize/#post-14231126) )

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new Optimize module boolean setting `placeAntiFlickerSnippet` should be implemented, with a default value of `false`.
* If the setting is enabled, the [anti-flicker snippet](https://support.google.com/optimize/answer/7100284#example-anti-flicker-snippet) should be inserted in the head of the page as outlined in these docs.
* When viewing the Optimize settings panel, the new setting value should be displayed as:
    * _Anti-flicker snippet_
    * _Snippet is inserted_ or _Snippet is not inserted_
* When editing the Optimize settings, the new setting should be modifiable via toggle:
    * _Place anti-flicker snippet on your site_
    * There should be a description below, with copy depending on whether the toggle is active or not:
        * Active: _Site Kit will add the code automatically._
        * Inactive: _Site Kit will not add the code to your site._
        * In both cases, there should be an external "Learn more" link behind it, that points to https://support.google.com/optimize/answer/7100284.
* The settings panel UI above should be added below the field for the Optimize ID, and above the AMP experiment field (which is only displayed if AMP).

## Implementation Brief
* Update the `settingSlugs` array in `assets/js/modules/optimize/datastore/base.js` to add `placeAntiFlickerSnippet`.
* Create `assets/js/modules/optimize/components/common/PlaceAntiFlickerSwitch.js` which exports the `PlaceAntiFlickerSwitch` functional component.
    * Check if the anti flicker snippet option is enabled by querying the Optimize module's data store via the `getPlaceAntiFlickerSnippet` selector which returns a `boolean`.
    * `PlaceAntiFlickerSwitch` should render the `Switch` component with the label as per the AC and below it, there should be a description below, with copy depending on whether the toggle is active or not together with a "Learn More" link as per the AC.
    * The `checked` prop of the `Switch` component should be the value of the result of the `getPlaceAntiFlickerSnippet` selector.
    * Define a callback function when the `Switch` is toggled and the function should dispatch the `setPlaceAntiFlickerSnippet` action with the opposite of the result of the `getPlaceAntiFlickerSnippet` selector.
* Update `assets/js/modules/optimize/components/common/index.js` to export the newly created `PlaceAntiFlickerSwitch` component.
* Update `assets/js/modules/optimize/components/settings/SettingsForm.js` to include the `PlaceAntiFlickerSwitch` component which should be added before the `AMPExperimentJSONField` component.
* Using `assets/js/modules/optimize/components/settings/SettingsView.js`,
    * Query the Optimize module's data store via the `getPlaceAntiFlickerSnippet` selector to check if the setting is enabled or not.
    * Display the text (third bullet point) as per the AC depending on the above value.
* Using `includes/Modules/Optimize/Settings.php`,
    * Update the `get_default` method to add a new item in the array, `placeAntiFlickerSnippet` having `false` as value.
    * Add the `get_sanitize_callback` protected method which makes sure that the `placeAntiFlickerSnippet` option is a `boolean`.
* Create `includes/Modules/Optimize/Tag_Guard.php` which has the `Tag_Guard` class that extends `Module_Tag_Guard`.
	* It should have the `can_activate` function which returns a `boolean` if the `placeAntiFlickerSnippet` setting is `true`. `includes/Modules/Analytics/Tag_Guard.php` can be used as reference.
* Create `includes/Modules/Optimize/Web_Tag.php` which as the `Web_Tag` class that extends `Module_Web_Tag`.
	* It should have the public `register` method and protected `render` method.  `includes/Modules/AdSense/Web_Tag.php` can be used as reference.
	* The `render` method should output the snippet as per the AC.
* Using `includes/Modules/Optimize.php`,
	* Add the private `register_tag` function which is hooked to the `template_redirect` action.
	* `register_tag` should call the `register` method of `includes/Modules/Optimize/Web_Tag.php` is it's not AMP and the tag is not blocked.
	* `includes/Modules/Tag_Manager.php` can be used as reference to how use `Tag_Guard` as well.
* Update existing `Optimize` stories to add new stories when `placeAntiFlickerSnippet` is enabled/disabled. 

### Test Coverage
* Add tests for the `PlaceAntiFlickerSwitch` component.

### Visual Regression Changes
* New switch should be showing up in Optimize settings.

## QA Brief
* Setup the Optimize module.
* Go to the module's settings and "Anti-flicker snippet" status should read "Snippet is not inserted"
* Edit the settings and activate the switch for "Place anti-flicker snippet on your site" and save changes.
* The text for "Anti-flicker snippet" should read "Snippet is inserted"
* Visit the frontend and check if the snippet in the AC is preset in the markup.

## Changelog entry

* Add option to insert the Anti Flicker snippet when connecting Optimize.

**Comment by aaemnnosttv** [comment]
@felixarntz seems like a worthwhile enhancement to add. Any reason not to add it?

**Comment by felixarntz** [comment]
@aaemnnosttv IMO yes, that should be technically trivial. Paging @marrrmarrr for confirmation. This should be an easy win with worthwhile benefits for our Optimize users.

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB looks good in general, but the part that explains how to render the snippet needs to be updated to use the Tag/Guard approach as we do it for AdSense/Analytics/Tag Manager snippets.

**Comment by asvinb** [comment]
Thanks @eugene-manuilov . IB updated. Can you check again please?

Thanks!

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark: Thanks, @asvinb.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@asvinb one small UI observation on smaller screen sizes, i.e. Android and iOS mobiles.  When you edit the Optimize settings, there's a large gap between the container ID field and the switch.  In the screenshot you will see the AMP fields but even with the AMP plugin deactivated the same issue occurs. 

![image](https://user-images.githubusercontent.com/73545194/128207396-77130f41-1c92-4e6e-8da0-bafad2fe66c3.png)

**Verified:**

Optimize module is set up:

- When you go to the module's settings the `Anti-flicker snippet` status reads `Snippet is not inserted`  [Screenshot](https://user-images.githubusercontent.com/73545194/128207659-27c05a00-55b2-4555-b691-8400d4a20b94.png)
- When activating the `Place anti-flicker snippet on your site` switch, the text reads `Snippet is inserted`  [Screenshot](https://user-images.githubusercontent.com/73545194/128207820-77d44ac6-47ca-4eec-b5a1-28c5a47f5bde.png)
- When viewing the source code, the snippet in the AC is preset in the markup.  [Screenshot](https://user-images.githubusercontent.com/73545194/128207708-8589c1ba-4d08-4b2d-a4f6-9326cf80b2af.png)


Additional tests:

- Installed AMP plugin to make sure layout of the settings passed with the additional fields. 
- Checked the UI changes on our supported browsers 
- Checked the UI changes on Android and iOS devices

**Comment by wpdarren** [comment]
@asvinb I have assigned this back to QA, and will get it approved from our conversation on Slack.  I'll also create a new ticket for the UI issue observed here since it is not linked.  Thank you!

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

Optimize module is set up:

- When you go to the module's settings the `Anti-flicker snippet` status reads `Snippet is not inserted`  [Screenshot](https://user-images.githubusercontent.com/73545194/128207659-27c05a00-55b2-4555-b691-8400d4a20b94.png)
- When activating the `Place anti-flicker snippet on your site` switch, the text reads `Snippet is inserted`  [Screenshot](https://user-images.githubusercontent.com/73545194/128207820-77d44ac6-47ca-4eec-b5a1-28c5a47f5bde.png)
- When viewing the source code, the snippet in the AC is preset in the markup.  [Screenshot](https://user-images.githubusercontent.com/73545194/128207708-8589c1ba-4d08-4b2d-a4f6-9326cf80b2af.png)


Additional tests:

- Installed AMP plugin to make sure layout of the settings passed with the additional fields. 
- Checked the UI changes on our supported browsers 
- Checked the UI changes on Android and iOS devices
