### ISSUE TITLE
Add tracking for client side errors

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3014]
## Feature Description

In #1999 we added event tracking for API errors on the client – whenever an API request results in an error, we track that as an event in our anonymous usage tracking for improving the product. While useful, this only covers API errors. We already have an error boundary in place for other errors where React gets into an unrecoverable state; we should add similar tracking to this as well to report errors that result in the error boundary to be triggered which is much more severe compared to an API error.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ErrorHandler` component in `assets/js/components/ErrorHandler/index.js` should be updated to track events for caught errors
* The error should be tracked with the following event attributes:
    * category: `react_error`
    * action: `handle_{screenContext}_error`
    * label: error message (and related trace)

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/3215

### Test Coverage

* Would be good to add but this change is a bit timely and straightforward to test (also there are no existing tests for ErrorHandler)

### Visual Regression Changes

* None

## QA Brief

* Set up event tracking inspection (e.g. Tag Assistant) and opt in to tracking
* Add `assets/js/components/ErrorHandler/ErrorComponent.js` on the page somewhere and click it
* Observe data in event

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz assigning to you to add event details, although these could probably be added later as well.

**Comment by felixarntz** [comment]
@aaemnnosttv Do the ACs here sound good to you?

**Comment by aaemnnosttv** [comment]
Sounds good, except let's use `react_error` for the category instead to be more specific.

**Comment by aaemnnosttv** [comment]
@felixarntz Moving to IBR since we've already discussed the ACs 👍  If we want to add tests, I could add these tomorrow; probably a good idea but maybe more for the future since we've already verified this for the most part.

**Comment by asvinb** [comment]
* Added the `ErrorComponent` component to the dashboard.
* Clicked on the "Simulate An Error" button.
* Tracking details sent as per screenshot and as per AC:
![image](https://user-images.githubusercontent.com/31818/115849859-5b301880-a436-11eb-9214-a8be987c22c3.png)


### QA: ✅
