### ISSUE TITLE
User input font sizes on small screens

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#3016]
## Feature Description

The current font sizes for the user input components are quite large on mobile (as per designs), however the user input screen should still look good and usable if we apply the same font sizes from the desktop breakpoint to the mobile breakpoint. The changes should be applicable to text only elements (not buttons, inputs). A quick mockup of how the user input preview screen will look if we reduce the font sizes (current and after):
**Current:**
![image](https://user-images.githubusercontent.com/31818/112303097-55b7a500-8cb5-11eb-8719-0e2193535ab7.png)

**After reducing font sizes and line heights:**
![image](https://user-images.githubusercontent.com/31818/112303075-4fc1c400-8cb5-11eb-91a1-eb9a77afc429.png)

The above screenshot is not perfect but we need to find the right balance between the font sizes so that some headings do not look smaller than some body text.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@aarondruck Can you review this suggestion? The currently used font sizes (from the original design) indeed look odd on mobile viewports - I'm not sure the best approach to go about it though, in terms of which sizes to use.

**Comment by aarondruck** [comment]
Yea we should reduce the font sizes and line heights for mobile

We should be using responsive font sizes and line heights.

**Comment by aaemnnosttv** [comment]
This is no longer accurate regarding the current state of User Input.
