### ISSUE TITLE
google site kits can't pass "Authenticate with Google".

### ISSUE THREAD

**Issue by amedeusv** [google/site-kit-wp#302]
Refer to Google Site Lits wordpress plugin - At the process of "Authenticate with Google" which ask to singin to google, after signin complete it lead me to my home page, after get back to wordpress Google site kits setting, i still remain at the same stage which is "Authenticate with Google". it just keep repeating and never move to next step to verify URL. what wrong?

**Comment by HaloPhoto** [comment]
I have the same problem. After signing into google it bounces back to "Authenticate with Google" and won't progress. Where are we going wrong?

**Comment by jamesozzie** [comment]
@amedeusv @HaloPhoto Do you mind performing the following steps, this is similar to issue #117  

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. If you are using iThemes security can you uncheck [this](https://i.imgur.com/7OyyYyI.png) option from the general settings
3. Temporarily deactivate your other active WordPress plugins
4. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

Please let me know if you encounter the same issue after trying the above

**Comment by HaloPhoto** [comment]
Hi - deactivating my other plugins did the trick for me. Thank you

**Comment by Mte90** [comment]
I confirm to have the same issue but I disactivated we and ithemes and problem was persisting.
So I disabled all the plugins and the problem persist anyway, maybe because I am using wp 4.9?

**Comment by jamesozzie** [comment]
@Mte90 Site Kit is [compatible](https://github.com/google/site-kit-wp/blob/develop/README.md) with WordPress 4.9. Can you check the following and see if you can pass the authentication stage:
- Disable AdBlockers or attempt authentication from an incognito window 
- Disable ModSecurity from within your web host if active

Please share any console errors if the above fails.

**Comment by Mte90** [comment]
I cleaned the htaccess and the user doesn't have any adblocker...

**Comment by hablaviajero** [comment]
I have the same problem, i dont know how to solve it, i tried Every thing jamesozzie said. 
I have Wordpress 5.5.2

**Comment by jamesozzie** [comment]
@hablaviajero @amedeusv @Mte90 The authentication flow will be modified in future releases, but in order to troubleshoot further can you please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard?

**Comment by jamesozzie** [comment]
@amedeusv Are you encountering the same issue with Site Kit setup?
