### ISSUE TITLE
Prune unused SVGs

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3025]
## Feature Description

Since moving to using inline svgs rather than a sprite, we're able to do more with a single vector file (such as using a different `fill` via css) that we couldn't do before. Additionally, some graphics that were used before are simply no longer needed and can be removed. Doing a simple diff between the files in the repo and the svgs we import in JS, we can see there are about 20 that are no longer used. We should of course take a closer look at these to make sure first but anything which is no longer needed should be deleted.

```diff
diff --git a/all-svgs.txt b/currently-used-svgs.txt
index 936479bfc..d43a8b561 100644
--- a/all-svgs.txt
+++ b/currently-used-svgs.txt
@@ -1,44 +1,24 @@
 adsense.svg
 analytics.svg
-arrow-angled.svg
-arrow-back.svg
-arrow-dropdown.svg
-arrow-external.svg
-arrow-link.svg
-arrow-negative.svg
-arrow-positive.svg
-arrow.svg
-check.svg
-chevron-down.svg
-chevron.svg
 close.svg
 congrats.svg
-dashboard.svg
 date-range.svg
 device-size-desktop-icon.svg
 device-size-mobile-icon.svg
 error.svg
 exclamation.svg
 help.svg
-info.svg
 lock.svg
 logo-g.svg
-logo-g_white.svg
-logo-google-cloud.svg
-logo-google.svg
-logo-google_solid.svg
 logo-sitekit.svg
 optimize.svg
 pagespeed-insights.svg
 pencil.svg
 person-sitting.svg
 person-walking.svg
-plus.svg
 rocket.svg
 search-console.svg
-settings.svg
 sun-small.svg
 tagmanager.svg
 thumbs-up.svg
 trash.svg
-warning.svg
```

Additionally, anything we can leverage `@wordpress/icons` for instead (e.g. `close.svg`) would be great to identify and make sure that we're not using different icons for the same thing in different places.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any source svg files which are no longer used (i.e. imported) anywhere should be deleted
* The following SVG components should be converted to svg files and moved to `assets/svg`
    * `assets/js/components/legacy-notifications/error.js`
    * `assets/js/components/legacy-notifications/warning.js`

## Implementation Brief
* The following SVG files are no longer used and can be safely deleted:
    * arrow-angled.svg
    * arrow-back.svg
    * arrow-dropdown.svg
    * arrow-external.svg
    * arrow-link.svg
    * arrow-negative.svg
    * arrow-positive.svg
    * arrow.svg
    * chevron-down.svg
    * chevron.svg
    * dashboard.svg
    * info.svg
    * logo-g_white.svg
    * logo-google_solid.svg
    * logo-google-cloud.svg
    * logo-google.svg
    * plus.svg
    * settings.svg
    * warning.svg

### Test Coverage
* No tests needed.

### Visual Regression Changes
* There will be visual changes due to the use of new icons.

## QA Brief

There should be no user-facing changes.

The icons extracted out can be seen here
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-notifications--small-with-error
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-notifications--small-with-warning

## Changelog entry

* N/A

**Comment by alicelovescake** [comment]
Hey!    

First time contributor! Would love to take a stab at this issue this week. Thanks for providing great detail.

**Comment by tofumatt** [comment]
IB ✅ 

@alicelovescake Thanks for your interest! The team who works on Site Kit usually assigns issues to Sprints/Releases and we haven't had too many third-party contributors in the past so our systems aren't perfectly set up for non-team-contributors, but if you are still able to take on the issue let us know. Since it isn't a high-priority issue we'll try to keep anyone on the usual team away from it so there's no overlap 😅

**Comment by aaemnnosttv** [comment]
> The following SVG files can be replaced by icons from the `@wordpress/icons` package

@asvinb @tofumatt let's not replace any of these icons as part of this issue as that would require more review since these would be user-facing changes. There will likely be some icons we can't replace where a material icon is preferred but changing icons is out of scope here.

**Comment by alicelovescake** [comment]
@tofumatt totally understand that, thanks. I would still love to help do the clean up if that is ok!

Based on @aaemnnosttv's comment, I'll leave the replacing of the SVG icons with `@wordpress/icons` as it's a little less straightforward. 😄

**Comment by Hazlitte** [comment]
@aaemnnosttv @asvinb @tofumatt,  As per the IB, I double checked and confirmed the removal of the list of icons that can be deleted.  I didn't find any new ones that can be removed.
With the second part of the IB I tried replacing the svg files with @wordpress/icons.  I ran into some strange behaviour with icon sizes and colours for the 'close' and 'help' icons which needs a bit more investigation.  I was unable to test replacing the `check` icon as it involves invoking the `SetupUsingGCP` process which I am unsure how to do in my local environment.
I think the third part of the IB needs someone with a better eye than me or as suggested, a discussion, to decide whether to replace them.
Should we just go with removing the icons in this task and separate the replacement of icons into another task?  Or shall I investigate the sizing and colour behaviour in more detail within the scope of this issue?

**Comment by aaemnnosttv** [comment]
@Hazlitte the replacement with WordPress/icons was supposed to be removed from the IB but looks like it wasn't updated after I asked for this change. I'll update it 👍

**Comment by danielgent** [comment]
This ticket is ready for Code Review, but as it's not in the current sprint I'll leave it in Execution.

I have some concerns about the ticket though.

The AC says
_"The following SVG components should be converted to svg files and moved to assets/svg
assets/js/components/legacy-notifications/error.js
assets/js/components/legacy-notifications/warning.js"_

But the IB doesn't say to change these. I've just gone ahead and done this.

**However** there already exists an `error.svg`. I created a new `error-2.svg` but the existing `error.svg` is only slightly different to the SVG I removed in `error.js`.

![error-comparison](https://user-images.githubusercontent.com/8496063/129070686-c9d49831-ba1a-4b8b-b2ac-8cac887b5b5e.png)




Also the VRT changes section says:
_"There will be visual changes due to the use of new icons."_

What new icons? Surely there should be no VRT changes. Only unused icons are deleted, and SVGs extracted out should appear the same, which is what I've done.

There are no VRT changes on my PR. I added widths to the Icons so they exactly matched the previous implementation.

**Comment by danielgent** [comment]
Also, if my above comment is correct, this should be **QA:Eng** then as there are no user facing changes.

**Comment by aaemnnosttv** [comment]
Thanks @danielgent!

> The AC says [...] But the IB doesn't say to change these. I've just gone ahead and done this.

Thank you - not sure why those weren't mentioned in the IB but this should still be done.

> However there already exists an error.svg. I created a new error-2.svg but the existing error.svg is only slightly different to the SVG I removed in error.js.

We definitely shouldn't have two different instances of the same icon – those look like the same thing just with different positions in the document. Is there any reason why we can't consolidate on using the current `error.svg` for both?

> Also the VRT changes section says:
> "There will be visual changes due to the use of new icons."
> What new icons?

The original IB suggested replacing some of these with icons from `@wordpress/icons` which was decided against (https://github.com/google/site-kit-wp/issues/3025#issuecomment-831995166) but that was after the IB was already approved and that part wasn't updated.

You're right though that there should not be any visual changes here 👍 

> Also, if my above comment is correct, this should be QA:Eng then as there are no user facing changes.

There _shouldn't_ be any user facing changes so this this should be QA'd as usual. The "eng" part of it will be verified during CR so there isn't much need to do that again in QA.

**Comment by danielgent** [comment]
Makes sense @aaemnnosttv 

I've removed the extra `error-2.svg` and am using the existing `error.svg` instead.

I had to adjust the size slightly but due to the different view box there is a slight change in a VRT

![VRT change](https://user-images.githubusercontent.com/8496063/129226952-51e9f147-f39a-4952-99fd-824ae87a8703.png)

**Comment by aaemnnosttv** [comment]
Thanks @danielgent – that sounds good to me, the difference looks negligible but thanks for raising 👍

**Comment by danielgent** [comment]
This is outside the current sprint *but* it's ready for Code Review so I've set it to that

**Comment by wpdarren** [comment]
@eugene-manuilov  @aaemnnosttv wondering if you could offer any direction on `There should be no user-facing changes`  It's a little vague.  I see the notifications on Storybook but unsure where those would usually appear.  Any additional for the QAB would be appreciated. Thanks!

**Comment by aaemnnosttv** [comment]
@wpdarren sure, basically we want to make sure that no icons were removed that are still used. We shouldn't see any missing icons. Also two different error icons were consolidated into one (they were basically the same just minor sizing differences but this was covered by VRT). So mostly looking over our use of icons to make sure none are missing 😄

**Comment by wpdarren** [comment]
### QA Update: ✅ 

I have been through Site Kit plugin, including activation, deactivation, and generated a few errors and warnings, no icons are missing. When smoke testing will continue to keep a look out for any missing icons.
