### ISSUE TITLE
Add tracking events for help visibility menu links

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3027]
As a follow-up to #2846, there should be tracking events for the 4 (3 regular + 1 in AdSense) links in the global help menu dropdown.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the user clicks one of the links in the global help dropdown (`helpVisibility` feature flag), a GA tracking event `click_outgoing_link` (event category `global_help_menu`) should be sent. The event should have a label based on which link was clicked:
    * `adsense_help`
    * `fix_common_issues`
    * `documentation`
    * `support_forum`

## Implementation Brief

* Add an extra `gaEventLabel` prop to `HelpMenuLink`. When it's passed, the `HelpMenuLink` should `trackEvent` with event name `click_outgoing_link` and event category `global_help_menu` when the link is clicked (using an `onClick` handler).
* The three default `HelpMenuLink`s in the `HelpMenu` component should receive the `gaEventLabel` prop per the ACs.
* The extra `HelpMenuLink` in the `ModuleApp` component should also receive the `gaEventLabel` prop (`adsense_help`, per the ACs).

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Setup a new jurassic.ninja site.
* Make a release zip and upload it to the new site.
* Setup Site Kit and enable tracking in admin settings.
* Install the tester plugin.
* Enable the `helpVisiblity` feature flag.
* Click on the links in the drop down help menu in the plugin header and check that GA tracking events are sent when the menu links are clicked on.  Check the query string parameters contain the values as detailed in the AC.  Example:

![Screenshot 2021-03-29 at 16 19 17](https://user-images.githubusercontent.com/5174233/112859389-b165a200-90aa-11eb-8782-3759091c4f74.png)
 

## Changelog entry

* Add tracking events for help visibility menu links.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
### **QA ✅**

Followed the QA brief with a new JN site. Confirmed that GA tracking events are sent when the menu links are clicked after enabling the helpVisiblity feature.

Sending to approval.
