### ISSUE TITLE
Unable to initially register spaces when inputting search terms during user input flow

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3028]
## Bug Description

When following the user input flow during step 5 when submitting a search term, spaces are not being registered. This is only when initially typing, not allowing words to be split until a user navigates back or places the curser within existing characters.

See steps below to reproduce:

![2021-03-26-10-58-52](https://user-images.githubusercontent.com/41326532/112621977-486bf900-8e22-11eb-8661-8cda1ad0abc6.gif)

## Steps to reproduce

1. Follow user input flow
2. On step 5 at the search terms spaces are not being recognized (until revisted)

## Additional Context

 - Occurs on both Windows and Mac environments
 - SK 1.29.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When entering search terms, users should be able to use the space to input multi-word phrases.  

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by abdullah1908** [comment]
I can replicate the same at my end. One thing more, its not allowing **keys(comma & enter)** to make term separate.
![Screenshot (42)](https://user-images.githubusercontent.com/14175927/112625522-dd85e680-8e50-11eb-8cc2-3623d44e798f.png)

**Comment by wpdarren** [comment]
@jamesozzie using a mac, I am unable to include a space, but I must admit to thinking that these worked more like tags, so wouldn't usually have a space.

**Comment by marrrmarrr** [comment]
@felixarntz do we need to add some upper bound check here to make sure people don't write a "search term" that's 50 words long?

**Comment by felixarntz** [comment]
This has been fixed at this point, also see #3009.

@marrrmarrr For the upper boundary, good point, I've opened #3229 to cover that.
