### ISSUE TITLE
User Input - Delete SVG icon has changed behaviour of the Enter key when entering search terms

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3029]
## Bug Description

For the 5th question on the user input screens:

With the introduction of the svg delete icon button in #2896 the behaviour of the enter key has changed. 

When you press enter to move on to the next search term, you are not sent to the input field, but instead the cursor goes to the delete icon. You have to press enter twice to go to the input field and enter next search term. 

Here you can see it in action on the screencast. 

https://user-images.githubusercontent.com/73545194/112630751-00c08e00-8e71-11eb-9458-583350b81bde.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
cc: @tofumatt @felixarntz

**Comment by aaemnnosttv** [comment]
@wpdarren this seems to no longer be a problem, can you confirm?

**Comment by wpdarren** [comment]
@aaemnnosttv I've tested this and the issue is no longer an issue, I think this was possibly fixed as part of the accessibility improvements ticket for user input.  This ticket can be closed. 👍
