### ISSUE TITLE
Cookie nonce invalid

### ISSUE THREAD

**Issue by Thierry1980** [google/site-kit-wp#303]
## Bug Description

When I paste the Oauth code I retrieve from Google and click "proceed" I keep getting the error "Cookie nonce is invalid"

## Additional Context

 - PHP Version: 
 - OS:  iOS
 - Browser chrome
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@Thierry1980 Please follow the steps below to try and proceed with your Site Kit setup. 

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. If you are using iThemes security can you uncheck [this](https://i.imgur.com/7OyyYyI.png) option from the general settings and see if it resolves the issue. 
3. Temporarily deactivate your other active WordPress plugins
4. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png). This step is very important as incognito mode means your browser extensions are disabled and you have a clear cache.

If you are not using ithemes can you let me know of the following:
- Web Host Environment
- Security / Firewall plugins in use
- PHP Version
- Console Errors
- PHP Errors

**Comment by jamesozzie** [comment]
I will close this issue now. If you are encountering the same issue feel free to reopen, and include any console errors or additional context.
