### ISSUE TITLE
Change Data Not Appearing in Audience overview for Analytics on 7 Days

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3038]
## Bug Description

The `Bounce rate` is misaligned due to not displaying the change data.  I only noticed this on date period of 7 days.  All other periods were fine. This looks to be an issue from Site Kit 1.28.0 because the previous version displayed the data as expected.

![image](https://user-images.githubusercontent.com/73545194/112845341-57c79c80-90d7-11eb-86de-a96818c94e99.png)

On Site Kit 1.27.0 this is what appears for the same site, date period. 
![image](https://user-images.githubusercontent.com/73545194/112852128-361de380-90de-11eb-959f-8da53f0b238b.png)

## Steps to reproduce

1. Connect 'Google Analytics
2. Go to the 'Google Analytics module'
3. Change the date period to 7 days. 
4. Observe the Bounce rate and the missing data underneath the percentage. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@jamesozzie this seems to be working now (v 1.29.0), are you still seeing an issue? 
<img width="945" alt="Screen Shot 2021-04-12 at 16 42 28" src="https://user-images.githubusercontent.com/13304791/114413371-38883f00-9bae-11eb-93ef-c07c2bd5deab.png">

**Comment by wpdarren** [comment]
@jamesozzie @marrrmarrr yes, I have just looked on the same test site and this does appear to be fixed. 

![image](https://user-images.githubusercontent.com/73545194/114414848-c6c9e880-9be1-11eb-93f2-9106eb0b9ecd.png)

**Comment by jamesozzie** [comment]
@marrrmarrr @wpdarren Looks good to me also from my side

**Comment by marrrmarrr** [comment]
All right, thanks for confirming! Closing this one out.
