### ISSUE TITLE
Include dates in all service deep links for refactored module page widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3042]
This is a follow-up to #2286, #2287, and #2689: Once we have refactored all widgets across the Site Kit module screens, we need to ensure all of these refactored widgets now include the date parameters for the current date range in the deep links to the respective Google service frontend.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Deep links to Google services (typically found in the widget header, e.g. "See full stats in...", or in the widget footer, e.g. "Source: ...") should always include date parameters for the current date range in the following widgets:
    * Search Console `ModuleOverviewWidget` (see #2063)
    * Search Console `ModulePopularKeywordsWidget` (see #2064)
    * AdSense `ModuleOverviewWidget` (see #2065)
    * AdSense `ModuleTopEarningPagesWidget` (see #2066)
    * Analytics `ModuleOverviewWidget` (see #2067)
    * Analytics `ModulePopularPagesWidget` (see #2068)
    * Analytics `ModuleAcquisitionChannelsWidget` (see #2069)
* Some of the above _might_ already have this in place if it was considered during implementation / CR. If so, great - let's just make sure to audit each of them to ensure it works as expected. You can review #2286 (Search Console), #2287 (Analytics), and #2689 (AdSense) for how these dates need to be provided per the respective Google service, and there are already code examples in the dashboard widgets that you should be able to almost copy/paste from.

## Implementation Brief
* Using the following files:
	* `assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget/Header.js`
	* `assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget/Footer.js`
	* `assets/js/modules/analytics/components/module/ModuleOverviewWidget`
	* `assets/js/modules/analytics/components/module/ModulePopularPagesWidget/Header.js`
	* `assets/js/modules/analytics/components/module/ModulePopularPagesWidget/Footer.js`
* Import the `generateDateRangeArgs` function from `assets/js/modules/analytics/util/report-date-range-args.js`.
* Get the user selected date range by querying the user data store using the `getDateRangeDates` selector, with `DATE_RANGE_OFFSET` from `assets/js/modules/analytics/datastore/constants.js` as value for the `offsetDays` key.
* Update calls to the `getServiceReportURL` selector by including the result of the `generateDateRangeArgs` function, passing the user selected date range as parameter.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* ensure the feature flag widgets.moduleScreens is set
* navigate to Site Kit's Analytics screen
* Change time period in header (to anything but Last 7 days)
* Check footer links to analytics for "Top content over the " and "Top acquisition channels over " widgets
* Observe the date range in Google Analytics matches that of Site Kit

Previously these were always opening the last 7 days regardless of what date range was being displayed

Now Analytics should open with the same date range as Site Kit

## Changelog entry

* Update remaining external links in widgets on module pages to include correct date range parameters

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Only the new widgets should be updated with the Site Kit period. 

**Verified:**

- 90 days (Jan 20, 2021-Apr 19, 2021) in the report for `Top content over the` `Top acquisition channels over` widgets
- 28 days (Mar 23, 2021-Apr 19, 2021) in the report for `Top content over the` `Top acquisition channels over` widgets
- 14 days (Apr 6, 2021-Apr 19, 2021) in the report for `Top content over the` `Top acquisition channels over` widgets
- 7 days (Apr 13, 2021-Apr 19, 2021) in the report for `Top content over the` `Top acquisition channels over` widgets
