### ISSUE TITLE
Customized Dashboard / Goal-Based Reporting

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3050]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
Closing as all issues are Stalled and we're managing this is newer epics.
