### ISSUE TITLE
Add ESLint "quotes" rule

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3056]
## Feature Description

As mentioned in https://github.com/google/site-kit-wp/pull/2836#discussion_r604605246, we are lacking rules about our quote markers in JS. We should add the https://eslint.org/docs/rules/quotes rule to our ESLint code. I'm surprised it isn't already in our base config.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* JS string literals should be single-quoted by default. Double quotes should only be allowed when it avoids escaping single-quotes in string. Backtick <code>`</code> strings should only be allowed when using template literals.

## Implementation Brief

* Add the ESLint `quotes` rule with the following config: `quotes: ["error", "single", { "allowTemplateLiterals": true, "avoidEscape": true }]`
* Fix any strings in violation of the new rule.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Ensure the ESLint rules are working by creating a variety of strings in a JS file and seeing if they trigger ESLint errors.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by Hazlitte** [comment]
** QA Eng ** ✅
