### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3057]
## Bug Description

[One user in the support forums](https://wordpress.org/support/topic/cannot-read-property-name-of-undefined/) in encountering the below error, possibly in the main dashboard. 
`Cannot read property 'name' of undefined.
`
Troubleshooting ongoing

## Additional Context

 - [WordPress support forum topic](https://wordpress.org/support/topic/cannot-read-property-name-of-undefined/) | [Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com&gxids=7826#response=ACYDBNiqtrrPNUXmAeCEF9gOSMqr3b0Kf-qLYb4kcgytO-5XOz2hpigS5KXuiblZOXHswWI) 
 - This has occurred for a few weeks now for this user (including after updating the plugin)
 - The original reporter is also encountering a "Data error in Analytics Request parameter is empty: metrics." error in their Analytics dashboard
 - 2 connected users
 - Migration plugin active
 - Object caching plugin active
 - AMP active (transitional mode)
 - No indication of additional htaccess rules

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@jamesozzie Should this be assigned to you in L0 or should it go to L1?

**Comment by jamesozzie** [comment]
@bethanylang Self assigning now. Most likely difficult to reproduce without additional insights although some additional pre-flight checks as discussed in todays sync may assist impacted users.

**Comment by jamesozzie** [comment]
As the impacted user here also encountered a `Data error in Analytics, Request parameter is empty: metrics.` notice I suspect this is in line with #2986, which was discussed in our internal sync. Both this and the linked issue may be server related, with query parameters are not being handled properly as per [this separate issue](https://github.com/google/site-kit-wp/issues/2782#issuecomment-814909070) or by hosting security restrictions. This may be identified during setup with changes made to the pre flight setup. 

@bethanylang While we mentioned changes to the pre flight checks I don't see any GitHub issue based on yesterdays discussion. 

In addition with no additional insights or response from the user on this particular issue & related support topic I'm closing this for the moment. To be reopened should we encounter this once again.
