### ISSUE TITLE
Point user to where PSI module is found after activating it

### ISSUE THREAD

**Issue by lilybonney** [google/site-kit-wp#306]
## Feature Description

When Analytics and AdSense have been activated, the Site Kit dashboard can grow quite long.

If PSI is then also activated, the user is redirected to the main dashboard screen and sees nothing, because the PSI component is now located below the fold. 

This is a slightly confusing user experience, but can be mitigated by adding new functionality to automatically scroll someone down to a module in the dashboard (once they've activated it), so it's immediately visible and they can see that their action had the expected result.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this in favor of #532
