### ISSUE TITLE
Ensure all Site Kit widgets always return their content wrapped in a `Widget`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3060]
Several of our new widgets do not have their "special state" content (e.g. error, zero data, module activation CTA etc.) wrapped in the `Widget` component as expected, which is (mostly) a regression from the legacy UI. See example below:

**Legacy UI**
![image (1)](https://user-images.githubusercontent.com/3531426/113167157-4cb85d80-91f8-11eb-9989-dacd08cee612.png)

**Widget-based UI**
![image (2)](https://user-images.githubusercontent.com/3531426/113167200-593cb600-91f8-11eb-9569-78e4cbdadc0b.png)

While this was also wrong for _some_ of the boxes in the legacy UI, we should now make sure to get it right all the way for the widget-based UI.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All widget components should have their special state components wrapped in a `Widget` component, including the correct `Header` and `Footer` props (if the widget normally uses those).
* More specifically: All widget components that are registered with `wrapWidget: false` need to be audited for this and updated if they return `PreviewBlock`, `WidgetReportError`, `WidgetReportZero`, `WidgetActivateModuleCTA`, or `WidgetCompleteModuleActivationCTA` without wrapping it in the `Widget` component. When updating, the `Widget` component used needs to use the same `Header` and `Footer` props as the widget when it is normally loaded.
    * Widget components that are registered with `wrapWidget: true` (which is the default) don't need to be audited/updated, since they will always be wrapped in `Widget` automatically (and should never use that component themselves, as a result).

## Implementation Brief
* Using the following files:
	- `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js`
	- `assets/js/modules/analytics/components/dashboard/DashboardPopularPagesWidget.js`
	- `assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js`
	- `assets/js/modules/adsense/components/dashboard/DashboardSummaryWidget.js`
	- `assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js`,
* wrap the `Preview*`, `WidgetReportError` and `WidgetReportZero` components within the `Widget` component, keeping the same props when the component is rendered correctly.

### Test Coverage
* N/A

### Visual Regression Changes
* Visual changes should apply to above components if any, especially for the loading, error states.

## QA Brief
* For each of the files noted int he IB above: 
  * Confirm that all `Preview*`, `WidgetReportError` and `WidgetReportZero` states are wrapped in a `Widget` component
  * Visually inspect them (Storybook might help here) to make sure there is no excessive visual regression, although some small changes might be noticeable in some states. 

## Changelog entry

* Update Site Kit widgets to always return their content wrapped in a `Widget`

**Comment by tofumatt** [comment]
Looks good; I double-checked all the components with `wrapWidget: false` and this looks like the complete set that need fixing.

IB ✅

**Comment by eugene-manuilov** [comment]
@johnPhillips could you please add QAB?

**Comment by Hazlitte** [comment]
**QA Eng ✅**
