### ISSUE TITLE
Containers for hidden widgets break sibling grid styles

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3062]
## Bug Description

Currently when a widget's output is overridden by an `OverrideComponent` (currently only one of a few special states which are aggregated in a row), the original widget output is still rendered in a sibling div which is hidden with CSS. This is because the original/real widget needs to be rendered in order for its widget state to be set correctly.

For the widgets dashboard, this results in extra padding where there shouldn't be any due to `grid + grid` styles that no longer work.

## Steps to reproduce

1. Set up Site Kit without Analytics connected
2. Disable `widgets.dashboard` feature
3. Observe spacing between "Site Overview" and "Search Funnel" headers
4. Enable `widgets.dashboard` feature and compare

## Screenshots

**Legacy**
![image](https://user-images.githubusercontent.com/1621608/113169678-83b95e00-924e-11eb-8b03-bc9fd33a831f.png)

**Widget-based**
![image](https://user-images.githubusercontent.com/1621608/113169701-874ce500-924e-11eb-85ef-c243cca5c0e6.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The presence of hidden containers (`.googlesitekit-hidden`) should not cause any visual differences in the widget-based layouts.

## Implementation Brief

* Using `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js`,
	* Import the `HIDDEN_CLASS` constant from `assets/js/googlesitekit/widgets/util/constants.js`.
	* Update the markup returned by the `! activeWidgets.length` check by wrapping `widgetsOutput` within the `Grid` component which has the following class names:
		* `HIDDEN_CLASS` constant.
		* `.googlesitekit-widget-area`
		* `.googlesitekit-widget-area--<slug>` where `slug` is the slug of the widget area.
		* `.googlesitekit-widget-area--<style>` where `style` is the style of the widget area.

### Test Coverage
* N/A

### Visual Regression Changes
* Possible visual changes to the dashboard if any.

## QA Brief

* Set up Site Kit without Analytics connected
* Disable widgets.dashboard feature
* Observe spacing between "Site Overview" and "Search Funnel" headers
* Enable widgets.dashboard feature and compare
* Observe spacing between "Site Overview" and "Search Funnel" headers is the same **with** the widgets.dashboard feature enabled

## Changelog entry

* Fix visual spacing problems with widget-based dashboard due to empty containers disrupting grid layout.

**Comment by felixarntz** [comment]
@aaemnnosttv Added ACs here - let me know if that sounds good to you.

**Comment by aaemnnosttv** [comment]
Sounds good to me @felixarntz . My only concern about moving them potentially somewhere else is regarding widget state, but I think we should be able to simply them render (nothing) in place 👍

**Comment by asvinb** [comment]
@aaemnnosttv I think the easiest option would be to take the elements out of the grid. I tested that solution and seems to be working fine. Let me know your views.

**Comment by aaemnnosttv** [comment]
> I think the easiest option would be to take the elements out of the grid.

@asvinb you're right but I think the portal is probably unnecessary. In this case, an inactive widget is only one of two conditions:
* A widget with no widget state (i.e. it isn't rendered yet)
* A widget that renders `WidgetNull` (which could happen for a number of reasons)

In both cases the output is effectively nothing already, so the added wrapper div with a hidden class _should be_ redundant. If for whatever reason this is not the case and there is some weird condition/state where it isn't this simple then we could go with the portal-based solution, but that should be more of a last resort. So I think it's okay to keep in the IB, but again, as a fallback. The primary approach should be to simply remove the wrapping div with the hidden class.

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb I would suggest to try the approach about just rendering the "empty" widgets without the `.googlesitekit-hidden` div. As long as this doesn't cause any "flickering" as widgets become active/inactive, that should be a good approach.

Regardless of that, it might make sense to move these "inactive" widgets to another location in the virtual DOM, so that they could _never_ disrupt the grid.

Maybe we should combine both approaches.

**Comment by aaemnnosttv** [comment]
> I would suggest to try the approach about just rendering the "empty" widgets without the `.googlesitekit-hidden` div

@felixarntz This should be the only approach needed until we find that another is necessary. I think we may be making more work than needed out of this otherwise. Let's see if the flicker that we're concerned about is possible first.

**Comment by asvinb** [comment]
@aaemnnosttv @felixarntz I've updated the IB, let me know if that works. I'am not sure about the "flickering" since I didn't see anything weird. However, I think that if anything which is hidden but provides functionality must be outside of the grid because later down the road, it can mess up CSS selectors, even though the chance is very small.

**Comment by aaemnnosttv** [comment]
@asvinb it's a bit confusing, but we're not actually hiding anything. In this case, "hidden" actually means non-existent 😄  Inactive widgets are those that render `WidgetNull` or have no state (not rendered yet). We currently do something very similar when rendering a widget area if there are no active widgets:

https://github.com/google/site-kit-wp/blob/0e03a537ab1abe5d81bc617bd93e558e65f34a69/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L77-L84

We essentially need to do the same thing right here at the widget level:
https://github.com/google/site-kit-wp/blob/0e03a537ab1abe5d81bc617bd93e558e65f34a69/assets/js/googlesitekit/widgets/components/WidgetRenderer.js#L64-L66

So there are literally no elements rendered to the DOM for an inactive widget (except right now we're adding the wrapping div to hide it which is the problem), but the widget _components_ still need to be rendered by React, even though it will result in no output in the resulting HTML. If you're still confused, let me know and we can jump on a quick call.

**Comment by asvinb** [comment]
@aaemnnosttv Following our conversation, I updated the IB where I suggest we use both the `Portal` approach and not rendering anything is the widget element having the hidden class is empty. I tried the suggestion of moving the hidden class to be a sibling of the `OverrideComponent` component in `WidgetRenderer` but it does not work for all cases it seems. I can still see some stray elements having the hidden class name.

**Comment by aaemnnosttv** [comment]
> The `Portal` component should take all of the code of the `Modal` component, `assets/js/components/Modal.js` with the following tweak

Sounds good. Let's update `Modal` to use `Portal` internally as well.

> * Using `assets/js/googlesitekit/widgets/util/constants.js`, add a new constant `HIDDEN_CLASS_NULL` having value `googlesitekit-hidden-null`.
* Using `assets/js/googlesitekit/widgets/util/combine-widgets.js`, add the `HIDDEN_CLASS_NULL` to the list of class names in addition to the existing `HIDDEN_CLASS` if the widget has `null` as class name. The `HIDDEN_CLASS_NULL` will be used to differentiate between null/not null components.

This part (and following based on it) will need some revision now that #2671 has been merged as `combineWidgets` is no longer concerned with class names. Maybe we can use `activeWidgets` to check since only active, zero-width widgets should be rendered in the portal.

**Comment by asvinb** [comment]
@aaemnnosttv I've updated the IB, can you check it out?

**Comment by aaemnnosttv** [comment]
Thanks @asvinb ! We're almost there I think 😄 

> Create `Portal.js` which exports the `Portal` functional component.
	* The `Portal` component should take all of the code of the `Modal` component, `assets/js/components/Modal.js` with the following tweak:
		* Add the `slug` prop which will should be added as class name to the dynamically generated element so that is easy to identify the portal.

Regarding the added `slug` - if this is purely for identifying the output, then let's not add it. I think this is partially solving a different problem which is that as-is, this may potentially add several portal targets to the DOM, which aren't really necessary.

As for `Modal` I suppose this could even be renamed to `Portal` for now since there is nothing modal-specific about it. In the future, it might make sense to WP slot fill components for this to have named slots that can have multiple fills from different components without adding a new DOM target for each. I don't think we need to go there for this issue though.

One important detail which is missing is that the contents of the portal that is used in this case need to be hidden since the elements passed to it may be non-null such is the case those displaced by override components.

Finally, I don't think using a portal should be necessary at all since we have full control over where the widgets are rendered and all information needed to know whether or not a widget should be hidden or not is available in the area renderer. We should actually be able to go back to a single hidden div in the widget area for all hidden **active** widgets. This caused a problem before with _inactive_ widgets (which render null) because unmounting them causes them to become active.

All that to say that I think we can simplify the changes needed like so:
- Reintroduce a single hidden div for each widget area for rendering all hidden non-null widgets for the area
    - This should only render zero-width **active** widgets
    - `widgetsOutput` should be updated to no longer render these (without using `filter` though because `gridColumnWidths` and override component arrays are indexed according to the array of all widgets)
- Zero-width inactive widgets should no longer be wrapped and can be rendered in place as-is

Even though I think we're simplifying things here, it still feels a bit complicated. Feel free to reach out for clarification 😄

**Comment by asvinb** [comment]
@aaemnnosttv I've updated the IB. Let me know what you think. If it's still not ok, let's jump on a call :)

**Comment by aaemnnosttv** [comment]
@asvinb - turns out this is still quite complicated, particularly with the widget null cases since it may still display a wrapping container (with nothing in it) meaning we always need to apply some wrapping element to hide it. This is a problem for these components specifically due to the infinite render loop that is triggered by unmounting them.

I think the only way forward here right now is to:

- Ensure every widget is always wrapped with a div that we can conditionally add the hidden class to rather than moving it anywhere
- Eliminate the need for `.grid + .grid` styles by applying classes for "collapsing" padding between adjacent grids dynamically

Also, I think the problem seems to be more with a widget context that has a header and widget areas inside that may be all inactive widgets rather than grids inside the area, but I need to do a bit more investigation.

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb Apologies for chiming in late here (and possibly lacking some context), but as far as I read through, I don't see a reason why we cannot just remove the `.googlesitekit-hidden` container, as you previously suggested Evan. Are there indeed widget flickering issues, or are these containers ever _not_ empty? I'm concerned with the approach taken here getting more complicated than it needs to.

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb Ah I see now there sometimes _is_ some output that becomes visible when just removing the `.googlesitekit-hidden` container, so that wouldn't be feasible.

How about just always rendering the `.mdc-layout-grid` wrapper for a widget area and hiding it when necessary? This keeps the expected DOM structure intact in a simple way, while hiding the content as necessary. See https://github.com/google/site-kit-wp/compare/demo/3062-intact-grid-regardless-of-inactive for a quick draft of this approach

**Comment by aaemnnosttv** [comment]
@felixarntz yes it is possible – a widget that returns `WidgetNull` will still be an empty wrapper if it has `wrapWidget: true`. We could conditionally not wrap a widget which is inactive in the renderer but that may cause the inactive -> active -> inactive render loop due that happens when unmounting an inactive widget since unsetting the null widget state makes it active again.

The other case is the widget component which is displaced by an override component since this is a normal widget that still needs to be rendered but is visually aggregated.

The hidden grid wrapper approach is one that I though of before too, although I forget if there was a reason why it wouldn't work 🤔  That's definitely worth a try.

It's important that we don't move inactive widgets though, for the reason mentioned above.

**Comment by aaemnnosttv** [comment]
@asvinb it looks like @felixarntz 's approach solves it. While this is technically not compatible with the ACs, I'll update them to allow for it since this is definitely the cleanest/simplest solution.

Not sure there is anything much left to do, but it would be great if you could spend a few minutes to check if there are any cases that aren't covered by this. If there aren't let's update the IB to do this and move it forward 👍

**Comment by asvinb** [comment]
Thanks @felixarntz . I've checked and it works fine :) @aaemnnosttv I've updated the IB to reflect @felixarntz 's approach. Can you take a look?

Thanks!

**Comment by aaemnnosttv** [comment]
IB ✅  😄

**Comment by wpdarren** [comment]
### QA Update: Needs clarification from engineer ⚠️ 

The QAB states `Observe spacing between "Site Overview" and "Search Funnel" headers` and reading the AC it suggests that we should not see any visual differences in the widget-based layouts. I do see a difference though. 

With the widgets.dashboard feature disabled, `the mdc-layout-grid` is 1259x1284px with 24px padding.
![image](https://user-images.githubusercontent.com/73545194/115536199-73b2fe00-a291-11eb-8d9b-2cfb42b3b449.png)

With the widgets.dashboard feature enabled, the `the mdc-layout-grid` is 1259x74px with 24px padding. 
![image](https://user-images.githubusercontent.com/73545194/115536384-a826ba00-a291-11eb-9cf3-f46d71f9c3d4.png)

Is this expected?

**Comment by aaemnnosttv** [comment]
@wpdarren If you look at the `widgets.dashboard` in the current release, you'll see it has twice the padding between the Site Overview and the next heading. That's essentially what this is about, not really that the two are entirely identical. You can see this in @danielgent 's screenshots here: https://github.com/google/site-kit-wp/pull/3177/files#r615791773

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- The spacing between "Site Overview" and "Search Funnel" headers is the same with the widgets.dashboard feature disabled/enabled. 

![image](https://user-images.githubusercontent.com/73545194/115689476-061bd600-a354-11eb-9ec9-5e6fb03fc732.png)
