### ISSUE TITLE
Rename "Popularity" / "Top Queries" section to "Acquisition" for new widget-based UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3065]
The section currently labelled "Popularity" on the Site Kit dashboard and "Top Queries" on the single URL view should be relabelled "Acquisition" **for the widget-based UI only**. The top keywords widget should then always display its full "Top search queries for your site" heading.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the `widgets.dashboard` feature flag is enabled, the dashboard section "Popularity" should say "Acquisition" instead.
* When the `widgets.pageDashboard` feature flag is enabled, the single URL view section "Top Queries" should say "Acquisition" instead.
* On the technical side, this should also be updated similarly: The `AREA_DASHBOARD_POPULARITY` and `AREA_PAGE_DASHBOARD_POPULARITY` widget area constants should be renamed (including their actual string values) to use the term "Acquisition" instead of "Popularity". Obviously its usage throughout then needs to be updated.
* The `DashboardPopularKeywordsWidget` should have its primary column title (currently "Keyword") updated:
    * On the dashboard, it should say "Top search queries for your site".
    * On the single URL view (i.e. if there is an entity URL), it should say "Top search queries for your page".

## Implementation Brief
* Using `assets/js/googlesitekit/widgets/register-defaults.js`,
	* update the title for the `AREA_DASHBOARD_POPULARITY` widget to `Acquisition`.
	* update the title for the `AREA_PAGE_DASHBOARD_POPULARITY` widget to `Acquisition`
	* rename the `AREA_DASHBOARD_POPULARITY` and `AREA_PAGE_DASHBOARD_POPULARITY` to `AREA_DASHBOARD_ACQUISITION` and `AREA_PAGE_DASHBOARD_ACQUISITION` respectively.
	* all references to the above renamed variables should be updated to use the updated names.
Using `assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js`,
	* Update the `title` of the first column of the table based on the following conditions:
		* `Top search queries for your site` if we are on the dashboard.
		* `Top search queries for your page`, if we are on the single URL view page.

### Test Coverage
* N/A

### Visual Regression Changes
* Changes for the above components should be noted.

## QA Brief

* Using the tester plugin enable the following feature flags:
  * widgets.dashboard
  * widgets.pageDashboard
* On the dashboard check that the first column of the table in the Acquisition widget says 'Top search queries for your site'
* On a 'Detailed Page Stats' page check that the first column of the table in the Acquisition widget says 'Top search queries for your page'   

## Changelog entry

* Rename "Popularity" / "Top Queries" section to "Acquisition" for new widget-based UI

**Comment by asvinb** [comment]
@felixarntz In the AC, there is mention of the feature flags. Turns out that the widgets will only be displayed if the feature flags are enabled. Thus we don't need to cater for the Legacy ones. Let me know if am missing anything here.

**Comment by felixarntz** [comment]
@asvinb Yes, I just mentioned the feature flags as a clarification that they need to be enabled to even see a change here.

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On the dashboard the first column of the table in the Acquisition widget says 'Top search queries for your site' - [Screenshot](https://user-images.githubusercontent.com/73545194/114550434-c63e5a00-9c94-11eb-82dc-3bff95db4a59.png)
- On a 'Detailed Page Stats' page the first column of the table in the Acquisition widget says 'Top search queries for your page' - [Screenshot](https://user-images.githubusercontent.com/73545194/114550450-cc343b00-9c94-11eb-9cc4-5353c20330b7.png)
- Also checked the widget and text on smaller screen sizes.
