### ISSUE TITLE
Connecting a second Google account to a service reverts all previously connected services to that account

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3066]
## Bug Description

As reported by a [user in the support forums](https://wordpress.org/support/topic/site-kit-adsense-wont-connect/), our current workflow when a user tries to connect different Site Kit services to different Google accounts is confusing from a user perspective.

In this case, the user had most of the Google services that she wanted to connect to Site Kit under one Google account, but one Google service (AdSense) under a separate Google account. She was able to successfully set up Search Console, Analytics, and PageSpeed Insights with Account A. However, when she attempted to set up AdSense with Account B, she had trouble getting it to connect successfully. When she was eventually able to log in, the three services that she had set up under Account A had been "reverted" to Account B. Most of these services already had Account B as an admin user, so she was still able to successfully see data, but others (Search Console) did not, resulting in permissions errors.

If we don't intend for users to connect different Google account to different services, it would be great if we could be clearer about that upfront so that they don't try to do so and encounter permissions errors. Providing a warning and/or instructions about providing access permissions across all accounts would allow users to use multiple accounts without losing access to data in SK. Alternatively, we could put mechanisms in place to keep users from connecting more than one Google account.

## Steps to reproduce

I was able to replicate this issue.

1. Install Site Kit
2. Connect at least one Site Kit service via a Google account – here (https://jmp.sh/hLa7GUm+/Screen+Shot+2021-03-31+at+3.25.56+PM.png) I've connected Search Console, Analytics, and PageSpeed Insights to bethanychobanianlang@gmail.com
3. Connect an additional Site Kit service via a *different* Google account – here (https://jmp.sh/CcxAFkC+/Screen+Shot+2021-03-31+at+3.27.09+PM.png) I am using bethany.lang@get10up.com to connect to GTM
4. Click through the Let's get you set up screens to allow data and verify ownership
5. Upon return to the Dashboard, the Google account will have changed (see https://jmp.sh/UfVABht+/Screen+Shot+2021-03-31+at+3.28.05+PM.png)
6. When you attempt to view more details about one of the services connected with the initial account, permissions errors will display – here, I tried to view Analytics: https://jmp.sh/Wh4DTP7+/Screen+Shot+2021-03-31+at+3.29.11+PM.png

## Screenshots

See steps to reproduce.

## Additional Context

 - PHP Version: 7.4.15
 - OS: macOS Big Sur
 - Browser: Chrome
 - Plugin Version: 1.29.0
 - Device: Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@bethanylang you're right that Site Kit currently doesn't support "blending" information from different Google services via multiple accounts. However, we don't control the account selection page content (that lives on accounts.google.com), so we can't affect how/if people select the same account. 
Do you think that having a page in our upcoming docs would help with this?

**Comment by felixarntz** [comment]
The behavior outlined in this issue is currently expected, as Site Kit only supports a single Google account per WordPress account, to encourage best practices. While it is unlikely that this will change anytime soon, we are heavily working on delegated dashboard view sharing (related: #6) which will allow users to view certain data delegated from another user's Google account, if they choose to share it. As part of this it will be possible for different WordPress (and Google) accounts to control different parts of the shared data, which should largely eliminate the need to have multiple Google accounts in a single WordPress account - since at that point the data will be possible to come from different sources.

I will keep this issue open for now since it technically touches on a different lack of support, but I believe it will be much less relevant once dashboard view sharing is available.

**Comment by bethanylang** [comment]
Thanks @felixarntz – closing!
