### ISSUE TITLE
PHP Tests jobs sometimes fail to due to DB connection

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3068]
## Bug Description

It seems that there may be a bit of a race condition when the PHP test jobs run in that the MySQL server may not be ready by the time we attempt to run mysql commands to set up the DB:

![image](https://user-images.githubusercontent.com/1621608/113267318-e2c6b380-92de-11eb-8de6-893c38eb7ef3.png)

The weird part is that it already seems to be doing something like this:

![image](https://user-images.githubusercontent.com/1621608/113272804-b150e680-92e4-11eb-8bdd-baa6e6439cea.png)

Relevant post: [Using the MySQL Service with Github Actions](https://firefart.at/post/using-mysql-service-with-github-actions/)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHP Tests job definitions should be updated to ensure the mysql service is properly waited for to ensure these jobs don't fail due to the above mentioned connection issue

## Implementation Brief

* Merge #3082

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* PHP Tests check should stop failing due to MySQL connection issues.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
