### ISSUE TITLE
Storybook stories for setup broken

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3074]
## Bug Description

The Storybook stories for setup using proxy always show the error from the compatibility checks, even for the standard cases where there should be no error. Furthermore, the tracking opt-in checkbox UI is missing from all of these stories.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Storybook stories for setup using proxy should only display a compatibility checks error if the respective story is explicitly named to show such an error.
* The Storybook stories for setup using proxy should always display the opt-in checkbox for tracking.
* The Storybook stories for setup using proxy for the disconnected case should show the correct wording for when access was revoked.

## Implementation Brief

* Merge #3075.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Verify the setup using proxy Storybook stories behave as specified in the ACs.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz it seems as if the setup stories for the "Disconnected" cases may also be not displaying as expected - they look the same as "Start" and "Start [User Input]" respectively. We should probably update the ACs to include these as well.

**Comment by felixarntz** [comment]
@aaemnnosttv I was mentally including them in "Storybook stories for setup using proxy" since they are a subset of that. But I can clarify.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
