### ISSUE TITLE
first time isuse

### ISSUE THREAD

**Issue by bakoorahnin** [google/site-kit-wp#3084]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@bakoorahnin If you're running into any particular issues with Site Kit feel free to [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) in the WordPress support forums and we'd be happy to assist. Please include additional context such as a description of the issue you're encountering or any error message encountered. 

If you wish to suggest a new feature or improvement feel free to add some additional details to this GitHub issue so I can reopen this and label it accordingly.
