### ISSUE TITLE
Module sorting uses wrong property in some components

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3093]
## Bug Description

Some components that list modules also sort them before rendering (this is likely goes back to pre-datastore design as `getModules` currently returns a "sorted" object).

In the legacy schema, a module is sorted by its `sort` property, however in the current schema, modules have a `order` property instead. There are a few instances in the refactored components where this property was not updated and modules are still sorted using a reference to the old (and now undefined) `sort` property. 

Because the `sort` property is undefined in the current module schema, this should result in no change when sorting because the result for every comparison would be the same.

![image](https://user-images.githubusercontent.com/1621608/113671073-8e487d00-96be-11eb-8eb4-9d3eff863d42.png)

In some cases, the sorting may no longer be necessary since `getModules` returns a sorted value.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Modules should always be sorted by their `order` property (if needed) when using the current/modern schema
* Legacy modules (i.e. those returned by `getModulesData()`) should always be sorted by their `sort` property

## Implementation Brief

* Merge #3094

### Test Coverage

* None needed

### Visual Regression Changes

* Should be none

## QA Brief

* Check the codebase to make sure all instances of module sorting have been updated
* Check areas in UI to ensure modules are sorted as expected (based on their defined `order`)

## Changelog entry

* Fix regression where modules may be sorted incorrectly on the plugin's settings screen.

**Comment by tofumatt** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
QA Update: Fail ❌


Searched through codebase for where we sort modules `ack --js '\.sort\('`, manually inspecting each result to ensure it pertained to modules:

```
googlesitekit/modules/datastore/modules.js:89: .sort( ( a, b ) => a.order - b.order )
components/settings/SettingsInactiveModules.js:62: .sort( ( a, b ) => a.order - b.order )
components/settings/SettingsActiveModules.js:82: .sort( ( module1, module2 ) => module1.sort - module2.sort );
components/ModulesList.js:91: .sort( ( a, b ) => a.order - b.order )
```

The third one in that list is a missed case so I put out a PR: https://github.com/google/site-kit-wp/pull/3112/files

**Comment by johnPhillips** [comment]
QA ✅

Searched the codebase as @ivankruchkoff did above, but used ripgrep with `'\.sort\('`. I was able to see the missed case he mentions has been fixed. I was unable to find any remaining instances.
