### ISSUE TITLE
Nothing happens after oauth.

### ISSUE THREAD

**Issue by sekanderb** [google/site-kit-wp#31]
**Describe the bug**
I click sign in with Google and authorize the site. After giving all the permissions, I am redirected to the site homepage. When get back to the Site Kit dashboard, I see the sign in option again.

**Expected behavior**
The authentication process should have completed and the step should have moved to Verify URL.

**System Information (please complete the following information):**
 - PHP Version: 7.3.6
 - OS: OSX Mojave
 - Browser: Chrome 75.0.3770.100 (Official Build) (64-bit)
 - Plugin Version: 1.0.0-beta.1
 - Device: MacBook Air

**Additional context**
I have checked for theme and plugin conflicts. But the issue is still there.
I have SSL enabled on my site from Let's Encrypt free SSL.

**Comment by jamesozzie** [comment]
@sekanderb When you say you are redirected to your site homepage do you mean your Site Kit dashboard? Is this after creating and authorising your client ID or at the next step when verifying your account.

Let me know also if you see any errors on screen or using Dev tools, and a screenshot of those errors if possible. 

In the meantime also please try installing again after temporarily deactivating other plugins. See if the same issue arises using another Google account.

**Comment by sekanderb** [comment]
I meant mysite.com, not mysite.com/wp-admin

This happens after allowing permissions to access my analytics and other google service data. I did not see any error message on chrome dev tools.

I was trying from my office computer. But when I tried the same site with the same details and same Gmail account from my home, it worked. The plugin is now working perfectly on my personal blog.

We will install this plugin on our company website soon. Currently, we are writing a blog post about the installation experience and will try to recommend to our customers. Do you know a place where we can share the blog post to help more users?

**Comment by jamesozzie** [comment]
@sekanderb Glad you were able to get it working. If you encounter this issue again please document the steps to reproduce the error. And we would love to hear more of your blog post. Feel free to reach out to @ThierryA also. As you are aware it's a developer release at the moment, with work ongoing for general release, so any input you have would be great.
