### ISSUE TITLE
Add general selector to match the site URL and use it to get the matching GA4 web data stream

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3105]
In order to know whether Site Kit needs to create a new web data stream for the GA4 property that the user has selected or whether it can use an existing one, the `modules/analytics-4` store should offer a selector.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/site` datastore should get a new selector `isSiteURLMatch( url )`.
    * It should rely on the `getReferenceSiteURL` selector and then create the permutations of it, in a similar way that the `Module::permute_site_url` method does in PHP (creating variants with HTTP/HTTPS and www/non-www).
    * It should then check whether the passed `url` is among those variants (ensuring the comparison is made in lower-case, for the edge-case that one of the URLs is capitalized).
    * If the passed `url` is a match, it should return `true`, otherwise `false`.
* The `modules/analytics-4` datastore's `getMatchingWebDataStream( propertyID )` selector should be updated to rely on the new `isSiteURLMatch` selector instead of using its own matching logic.

## Implementation Brief

* Add a new selector `isSiteURLMatch( url )` to the `googlesitekit/datastore/site/info.js` datastore. It should pull the current reference site URL and compare it with the incoming `url` argument ignoring protocol, `www.` subdomain prefix, and trailing slash in both URLs. In other words, it should return `TRUE` for `http://example.com/` and `https://www.example.com` URLs, but `FALSE` for `http://example.com/` and `http://example.com/subsite/`.
* Update the `getMatchingWebDataStream( propertyID )` selector from the `analytics-4` module to use the new `isSiteURLMatch( url )` selector instead of relying on custom logic to compare URLs.

### Test Coverage

* Add js tests to check the new selector.

### Visual Regression Changes

* N/A

## QA Brief

* Verify that the new `isSiteURLMatch` selector is added to the `core/site` datastore.
* Check that the `getMatchingWebDataStream` selector from the `modules/analytics-4` datastore uses it.

## Changelog entry

* Add a selector to the `core/site` datastore for checking whether or not a given URL matches the site's reference URL.

**Comment by felixarntz** [comment]
This is almost a duplicate of #2981, but it comes with one nuance worth including, which is the reusable `isSiteURLMatch` selector. I'll rephrase the ACs accordingly.

**Comment by felixarntz** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
This ticket is missing a QA brief @eugene-manuilov

**Comment by Hazlitte** [comment]
**QA Eng ✅**
