### ISSUE TITLE
Implement rendering GA4 tags in the frontend

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3106]
Similar to the `Analytics` class, the `Analytics_4` class should also support rendering tags in the frontend.

Note that it should be avoided though that both of them render their individual tags. There is a concept of double tagging which should be leveraged instead for the case that both modules need to render tags.

At the same time, the implementations should be standalone out of the box. _If_ both modules should render their tags, the `Analytics_4` module should not render its tag individually, but instead hook in to the tag logic of the `Analytics` module to add its own tag ID in there.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Analytics_4` module class should get a new private method `register_tag()`, similar to the one that the `Analytics` module has. However, it should be hooked into `template_redirect` **at a later priority** (see below why).
    * Since GA4 currently doesn't support AMP, in that case it shouldn't do anything. In other words, return early if AMP.
    * Otherwise, it first should check whether the `googlesitekit_analytics_init_tag` has already run. If so, it means the `analytics` module will output its snippet, so `analytics-4` needs to integrate (see requirements below).
    * If the action has not run before, it should output its tag individually (see requirements below).
* If the `Analytics_4` option `useSnippet` is disabled or if no `measurementID` is stored, it should of course not output a tag.

### Integrating with the `analytics` tag from `analytics-4`

* The `measurementID` should be added as an additional `config` variable in the UA, prefixed with "G-". [See here for details on double tagging](https://developers.google.com/analytics/devguides/collection/ga4/basic-tag?technology=gtagjs)

### Rendering an individual `analytics-4` tag

* It should be possible to use the `Google\Site_Kit\Modules\Analytics\Web_Tag` class as is, with the `measurementID` used as tag ID (and `analytics-4` as module slug), since the snippet basically is the same as for UA properties. [See here for details on what a GA4 snippet should look like](https://developers.google.com/analytics/devguides/collection/ga4)

## Implementation Brief

* Add a new class `Modules/Analytics_4/Tag_Guard` which should be identical to the `Tag_Guard` class from the `Analytics` module. The only difference is that it should check whether `measurementID` setting is empty instead of `propertyID`.
* Add a new class `Modules/Analytics_4/Web_Tag`:
  * Add a new public `register` method.
  * Add a new private `enqueue_gtag_script` method:
    * Add the following snippet if the `googlesitekit_analytics_init_tag` action has been already triggered:
    ```php
    $config = sprintf( 'gtag("config", "G-%s");', esc_js( $measurementID ) );
    wp_add_inline_script( 'google_gtagjs', $config );
    ```
    * Otherwise, render the snippet from the [documentation](https://developers.google.com/analytics/devguides/collection/ga4) using the similar approach from the Web_Tag class from the Analytics module.
  * Add a new hook for the `wp_enqueue_scripts` action in the `register` method that proxies the call to the `enqueue_gtag_script` method.
    * Use `20` priority for this hook to make sure it runs after the analogical hook is run in the Analytics module.
* Add a new private `Analytics_4::register_tag` method. It should work similarly to the analogical method from the Analytics module but ignoring AMP mode.
* Add a new hook for the `template_redirect` action to the `Analytics_4::register` method that proxies the call to the `Analytics_4::register_tag` method.

### Test Coverage

* Add phpunit tests for the new Tag_Guard class.

### Visual Regression Changes

* N/A

## QA Brief

* Check the Analytics_4 module and make sure that its Tag_Guard checks `useSnippet` and `measurementID` settings to determine whether or not to allow tag rendering.
* Also check the Web_Tag class of the same Analytics_4 module to make sure it adds its `measurementID` setting (via `$this->tag_id`) to the gtag script generated by the Analytics module if Analytics renders it. Otheriwse make sure it renders the gtag script on its own.

## Changelog entry

* Implement the technical infrastructure for rendering GA4 snippets in the frontend, including support for double tagging integrating with a UA snippet.

**Comment by eugene-manuilov** [comment]
> If the Analytics_4 option useSnippet is disabled or if no measurementID is stored, it should of course not output a tag.

@felixarntz there is no `useSnippet` setting in the `analytics-4` module, thus there is no way to display GA4 tag when GA module or its `useSnippet` setting is disabled. We probably need to update AC to remove instructions that can't be implemented, don't we? Also, I think we can simplify implementation if we use `googlesitekit_gtag_opt` filter and manually add inline script to the `google_gtagjs` one.

**Comment by felixarntz** [comment]
@eugene-manuilov 
> there is no `useSnippet` setting in the `analytics-4` module

I think there is (the `Analytics_4\Settings` class has it), or otherwise there should be. For now it should just always be active (default is `true` anyway), the UI to control it will be implemented in a future issue. So that should be able to implemented as stated in the ACs.

> Also, I think we can simplify implementation if we use `googlesitekit_gtag_opt` filter and manually add inline script to the `google_gtagjs` one.

While this is possible technically, it shouldn't be done, because filters in WordPress should never cause side effects like this. A more appropriate way would be to hook into `wp_enqueue_scripts` (at a later priority than `Analytics\Web_Tag` does) and add the inline script from there.

Can you update the IB to not use the filter, and also add something about the alternate logic based on whether double tagging is used or not?

**Comment by eugene-manuilov** [comment]
@felixarntz IB is updated.

**Comment by felixarntz** [comment]
@eugene-manuilov Great, +1 for using a separate `Web_Tag` class and the `wp_enqueue_scripts` action regardless of whether the Analytics tag is modified or a separate tag is added. IB ✅

**Comment by aaemnnosttv** [comment]
@eugene-manuilov please add a QAB 😄

**Comment by tofumatt** [comment]
QA ✅
