### ISSUE TITLE
Widget-based dashboard header + subheader is separated from widget area with set margin rather than grid

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3119]
## Bug Description

The header + subheader (highlighted in the screenshots) on the new widget-based dashboard have a fixed margin to separate them from the widget area, which leads to a minor difference in the before/after of these components.

That alone isn't a huge deal, as it's a pixel difference and a few developers on the call even thought the newer version looked a bit better. But its implementation seems off, as it's vertically spaced away from the widget area body with a fixed-value `margin-bottom` instead of relying on the grid system. Here are before/after screenshots:

### Before

<img width="1056" alt="Screenshot 2021-04-08 at 21 35 49" src="https://user-images.githubusercontent.com/90871/114093277-d03a1480-98b2-11eb-91fd-1ba6d4988e1b.png">

### After (Widget-based)

<img width="922" alt="Screenshot 2021-04-08 at 21 35 22" src="https://user-images.githubusercontent.com/90871/114093297-d6c88c00-98b2-11eb-9a98-029597c9abd5.png">

If the margins are removed the Widget-based version, the header + subheader go right against the widget area, which looks bad:

<img width="1273" alt="Screenshot 2021-04-08 at 21 39 47" src="https://user-images.githubusercontent.com/90871/114093386-f52e8780-98b2-11eb-82c4-68b068a1160f.png">

## Steps to reproduce

1. Enable `widgets.dashboard` feature flag in the Tester Plugin
2. Visit the Site Kit dashboard
3. Observe the screenshot above and notice the spacing between the widget header and body isn't the same as other grid spacing, depending on viewport.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `.googlesitekit-widget-area-header` should not be separated from the widget area (`.googlesitekit-widget-area-widgets`) with a margin, but instead using a grid-gap/some grid spacing mechanism.

## Implementation Brief

* Remove the fixed `margin-bottom` from `.googlesitekit-widget-area-header`.
* Replace it with code that adds the correct margins based on the MDC CSS variables, similar to the existing Widgets CSS approach: https://github.com/google/site-kit-wp/blob/264631cb9bb5a82d9ac36e0c19af42206a2934a5/assets/sass/widgets/_widgets.scss#L53-L61
* Merge #3122.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Enable `widgets.dashboard` feature with the Tester Plugin using commit `7a9bc2e2dfd27abdfbfb370cb22b55ee63a7f061`.
* Visit the Site Kit dashboard.
* In a new tab, check out `develop` and visit the dashboard.
* The gap between the header + subheader should be set to `var(--mdc-layout-grid-margin-desktop, 24px)` on a desktop browser size (above 1000px, less than 1400px wide, for instance).

## Changelog entry

* Update widget header styles to use grid mechanics instead of static margins

**Comment by felixarntz** [comment]
@tofumatt I think this is less about using the grid for this element rather than it is about just the spacing being incorrect. We can keep the `margin-bottom` that it has right now, but the problem is that it is `1rem` which doesn't match the spacing used elsewhere.

When looking at the grids throughout the plugin, they use e.g. `var(--mdc-layout-grid-margin-desktop, 24px)` on desktop. So basically, we need to ensure the spacing for our custom `.googlesitekit-widget-area-header` matches the grid spacing.

To get the right spacing, you can use the same approach that is currently applied in `assets/sass/widgets/_widgets.scss` for the `.googlesitekit-widget__header` etc selectors. Basically use the same, but put that in `margin-bottom`; then the spacing is correct.

**Comment by tofumatt** [comment]
Ah, I caught that but wasn't sure about copying those values… because `--mdc-layout-grid-margin-desktop` didn't exist anywhere in _our_ codebase, I think that's why we went with the `1rem` solution originally, but I'll take a look at getting access to them.

I see now how the widgets approach it which is neat: https://github.com/google/site-kit-wp/blob/264631cb9bb5a82d9ac36e0c19af42206a2934a5/assets/sass/widgets/_widgets.scss#L53-L61

But as part of this implementation we should have comments in that CSS with the explicit CSS variables so future developers can easily search for it in the codebase rather than doing what I did with their own, rogue values again 😅

**Comment by felixarntz** [comment]
@tofumatt Your draft PR is correct, the IB isn't - please don't include code in IBs unless really necessary, for _that_ particular reason that the IB review shouldn't need to be somewhat of a code review :)

I'll give this an IB ✅  though since that's just an oversight and the PR is already there.

**Comment by tofumatt** [comment]
@felixarntz Ah, indeed, thanks! 👍🏻 

I adjusted it to mention using the widget CSS approach and not directly use the code, just to clarify. But sounds good 🙂

**Comment by Hazlitte** [comment]
**Q Eng ✅**
