### ISSUE TITLE
Bug with Divi builder

### ISSUE THREAD

**Issue by PATRICEINFORMATIQUE** [google/site-kit-wp#313]
Hi i install your plugin this morning and it make a bug with divi theme and builder, just for information 
I send the same request to divi developpers 
have a gpod day 

Patrice

**Comment by jamesozzie** [comment]
@PATRICEINFORMATIQUE Can you please provide the following so we can investigate further:
- Any [console errors ](https://i.imgur.com/f5WfLb3.png)in your browser at the page where you see the error
- Screenshot of the error message

**Comment by jamesozzie** [comment]
I will close this issue now. If you are encountering the same issue feel free to reopen, and include any console errors or additional context.
