### ISSUE TITLE
Allow 3P capability management plugins to get list of Site Kit capabilities

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3130]
There are various 3P plugins which allow managing WordPress capabilities. Site Kit's capabilities are currently not available in an easy-to-access way, so introducing a utility method that returns a list with all of its base capabilities would be helpful.

Originally requested by @JoryHogeveen via #987.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `get_capabilities()` method in the `Permissions` class which returns an array with all of Site Kit's base capabilities.

## Implementation Brief

* Complete and merge #987. Or, since the PR #987 is quite old and has gotten stale, we may need to open a new one for this.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Ensure the new method returns all Site Kit base capabilities (expect the publish one, which is unused and will soon be completely removed).

## Changelog entry

* Add method to get list of all base capabilities used by Site Kit.

**Comment by Hazlitte** [comment]
Hi @felixarntz, I'm not sure what to do about test coverage here.  I checked the PHPUnit files and there isn't a test file for the Permissions class.

**Comment by Hazlitte** [comment]
@felixarntz Ok, thank you for confirming.

**Comment by ivankruchkoff** [comment]
QA ✅

```
$ wp eval 'var_dump( \Google\Site_Kit\Core\Permissions\Permissions::get_capabilities() );'
array(6) {
  [0]=>
  string(26) "googlesitekit_authenticate"
  [1]=>
  string(19) "googlesitekit_setup"
  [2]=>
  string(33) "googlesitekit_view_posts_insights"
  [3]=>
  string(28) "googlesitekit_view_dashboard"
  [4]=>
  string(33) "googlesitekit_view_module_details"
  [5]=>
  string(28) "googlesitekit_manage_options"
}
```

These correspond to:
```php
	/*
	 * Custom base capabilities.
	 */
	const AUTHENTICATE        = 'googlesitekit_authenticate';
	const SETUP               = 'googlesitekit_setup';
	const VIEW_POSTS_INSIGHTS = 'googlesitekit_view_posts_insights';
	const VIEW_DASHBOARD      = 'googlesitekit_view_dashboard';
	const VIEW_MODULE_DETAILS = 'googlesitekit_view_module_details';
	const MANAGE_OPTIONS      = 'googlesitekit_manage_options';
```
