### ISSUE TITLE
Update to latest Google charts library version

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3133]
[A new Google charts library version was recently published](https://developers.google.com/chart/interactive/docs/release_notes#upcoming:-april-2021), however it caused critical JS errors in Site Kit (see #3132), so we ensured to keep using version 49 for now. We should still figure out where these errors are actually coming from in regards to the new version 50 release of the charts library, fix them, and update.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should use version 51 of the Google charts library throughout (both in PHP and JS where version 49 is referenced, this needs to be updated).
* The new version should not result in any JS errors on Site Kit screens where charts are present.

## Implementation Brief

* Update the `chartVersion` prop on the `GoogleChart` component
* ~~In `Core/Assets.php` change 49 to 50 in the `googlesitKit-google-charts` `Script` object~~
* Remove the `googlesitkit-google-charts` `Script` instance and references to it

### Test Coverage

* n/a

### Visual Regression Changes

* Check visual tests but no changes are anticipated

## QA Brief

* There should be no changes to the Charts.
* Go through Site Kit and check as many charts as possible.

## Changelog entry

* N/A

**Comment by Hazlitte** [comment]
Whilst looking into this I found that I can cause the same errors to occur ( as noted in #3132 ) by setting the Google Charts version in `Assets.php` to 50 and the version in the `GoogleChart` component to 49.

The following scenarios work:

1. `Assets.php` : 50, `GoogleChart`: 50
2. `Assets.php` : current, `GoogleChart`: 50
3. `Assets.php` : 50, `GoogleChart`: remove `chartVersion` prop
4. `Assets.php` : current, `GoogleChart`: remove `chartVersion` prop

I shall update the IB with the third of these scenarios.

**Comment by eclarke1** [comment]
@Hazlitte would it be possible to add an estimate here now the IB is completed please?

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by danielgent** [comment]
I'm getting some very odd errors in storybook that free failing on a v51 of google charts :thinking:   (Which we aren't loading!)
https://www.gstatic.com/charts/51/js/jsapi_compiled_default_module.js

In `.storybook/preview-head.html` I've updated the version to 50 (which isn't in the IB)

**Comment by danielgent** [comment]
See the version 50 upgrade PR here https://github.com/google/site-kit-wp/pull/3334 and how it fails the VRT and Storybook Test steps (Storybook crashes with errors like this)

![v50-errors](https://user-images.githubusercontent.com/8496063/129614783-9e93b888-81ff-4c75-8173-e0ade873ced1.png)


However I created a PR with Google Charts upgraded to v51 and those tests pass https://github.com/google/site-kit-wp/pull/3881

_**Just the PHP Tests / PHP (PHP 7.4, WordPress Nightly) (pull_request)  test is failing in both PRs.  Seems odd though that the PHP tests only fail for one specific version**_ - I'll check if there's some other issue here by making a new PR with no changes

**Comment by danielgent** [comment]
Failing PHP test is happening on new PRs that only have comment changes - https://github.com/google/site-kit-wp/pull/3882/checks?check_run_id=3343479892 - not related to this PR then

**Comment by danielgent** [comment]
Failing PHP test has now been fixed :+1:

**Comment by aaemnnosttv** [comment]
No rush on this but a few questions for @felixarntz in the review.

**Comment by felixarntz** [comment]
@aaemnnosttv I _think_ I already replied to them but then forgot to reassign the issue, at least I don't see any other questions. Just to confirm, is #3881 the correct PR? Asking since there's also #3334.

**Comment by cole10up** [comment]
### **QA ✅ **

Ran regression tests on Adsense, Search Console and Adsense.
![image](https://user-images.githubusercontent.com/57115907/131554090-4a332eed-1261-4287-a06a-291a0cdd071f.png)
![image](https://user-images.githubusercontent.com/57115907/131554279-dc9817ca-b235-4508-a99b-9ad76b278a7f.png)
![image](https://user-images.githubusercontent.com/57115907/131554361-2d236836-df22-45bf-8d39-8a06105fe5f9.png)
![image](https://user-images.githubusercontent.com/57115907/131554389-73194f69-bee5-4922-bee2-d819425f6a65.png)
![image](https://user-images.githubusercontent.com/57115907/131554414-4941276a-92b0-41f7-9ae8-126ab9881357.png)

Sending to Approval
