### ISSUE TITLE
 Ad blocker detected, you need to disable it in order to set up AdSense.

### ISSUE THREAD

**Issue by holdnroark** [google/site-kit-wp#3137]
## Bug Description

 Ad blocker detected, you need to disable it in order to set up AdSense.

I have had adsense operating for months and, all of a sudden my ads disappeared.

I have the message " Ad blocker detected, you need to disable it in order to set up AdSense." in site kit on top of my adsense block.

It has been this way over a month
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. We can reopen this GitHub issue should we determine any issue to be addressed on the plugin side. 

Note also that if you're using the latest version of Site Kit (1.30.0) which was just released we have improved Ad Blocker detection to ensure users are less likely to encounter this notice during setup with particular hosting providers. (#3018)

When opening a support topic please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.
