### ISSUE TITLE
Styling Issue for Small Screen Sizes on Google Analytics Module

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3138]
## Bug Description

While testing #2069 I came across a styling issue with the `Top acquisition channels` widget on Analytics module.   The text `Organic Search` is not readable on small screen sizes, as you can see on the screenshot below.  The devices tested were Pixel 2, iPhone X and other Android/iOS phones. Tablets seemed to be fine. 

## Steps to reproduce

1. Make sure `Analytics` is connected
2. Go to the module on a mobile screen size 
3. Scroll down to `Top acquisition channels over the last X days`
4. See styling issue in the table after the pie chart. 

## Screenshots

![image](https://user-images.githubusercontent.com/73545194/114572402-06f49e00-9caa-11eb-82fa-9a27a0d7ffa9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Fields where the text doesn't fit in the column width should be wrapped on multiple lines as necessary, so they don't overlap with the neighbouring fields. 

## Implementation Brief

* edit the `LegacyAnalyticsDashboardWidgetTopAcquisitionSource` component
* remove `TableOverflowContainer` from the being imported and from the rendering of the JSX

### Test Coverage

* N/A

### Visual Regression Changes

* Check visual regression tests and update as necessary

## QA Brief
* Follow the steps above to reproduce and verify that the issue has been fixed.
* Note: this issue seems to affect the legacy and new versions of the widget, so both need testing. For the legacy widget, disable the `widgets.moduleScreens` feature, and for the new version, enable it.

## Changelog entry

* Improve table views on mobile screens.

**Comment by aaemnnosttv** [comment]
> Using `/assets/sass/components/global/_googlesitekit-source-link.scss`
> Remove the whole rule with the selector `.googlesitekit-table-overflow__container` as we don't want any of this now

@danielgent these styles don't seem relevant to the issue here since it's a single `font-size` rule only 🤔 
https://github.com/google/site-kit-wp/blob/27342ee6405bbea9a567439024d735214f4ca1c2/assets/sass/components/global/_googlesitekit-source-link.scss#L19-L21
Did you mean to reference a different stylesheet?

Also, don't forget to always populate all sections of the IB as per the guidelines.

**Comment by danielgent** [comment]
@aaemnnosttv Thanks for that!  Ooops.  I put the link to the previous stylesheet :facepalm: 

I read through the IB Guidelines doc again.  I just checked the VRT and there are two changes.  One is exactly what we want :star_struck:  (it's exactly the issue listed above! **The current backstop image in the repo shows the error** https://github.com/google/site-kit-wp/blob/develop/tests/backstop/reference/google-site-kit_Analytics_Module_Top_Acquisition_Pie_Chart_0_document_0_small.png ) 

**BUT** the VRT uncovered an error with my IB. It causes a change on another VRT :star_struck: 
Here there are less columns on the table so the current rules work fine and don't need changing
https://github.com/google/site-kit-wp/blob/develop/tests/backstop/reference/google-site-kit_Global_Data_Table_0_document_0_small.png

I'll revisit the IB now

**Comment by danielgent** [comment]
I'm reverting my previous IB completely.

This looks like a bug with the `TableOverflowContainer` that has been present for a while (given we have backstop images in the repo showing this bug https://github.com/google/site-kit-wp/blob/develop/tests/backstop/reference/google-site-kit_Analytics_Module_Top_Acquisition_Pie_Chart_0_document_0_small.png )

My previous change involves breaking other parts of the site where `TableOverflowContainer` works correctly e.g.
https://github.com/google/site-kit-wp/blob/develop/tests/backstop/reference/google-site-kit_Global_Data_Table_0_document_0_small.png

The offending component in the ticket description screenshot is the `LegacyAnalyticsDashboardWidgetTopAcquisitionSources`.  We can remove the `TableOverflowContainer` and then this will _"fix"_ the issue, but this component does lots of things and I don't want to remove classes from it in a hurry!

**Comment by Hazlitte** [comment]
I have added a bit more detail to clarify the last statement in the IB and provided an example PR.
Here are screenshots of the regressions.  A regression is necessary to fulfil the IB but this approach has side effects.  I am unsure whether the other regressions are acceptable or I should spend more time investigating this issue.  What do you think?

<img width="1337" alt="Screenshot 2021-05-12 at 09 58 35" src="https://user-images.githubusercontent.com/5174233/117948185-ca4baf00-b308-11eb-8ea3-17abbf9f0912.png">
<img width="1326" alt="Screenshot 2021-05-12 at 09 58 49" src="https://user-images.githubusercontent.com/5174233/117948199-cd469f80-b308-11eb-81fb-476268c9ea01.png">

**Comment by aaemnnosttv** [comment]
@Hazlitte those changes don't look right to me either.

@asvinb I realize this wasn't your IB but can you take a look and see what else is needed?

**Comment by asvinb** [comment]
@Hazlitte @aaemnnosttv Had a quick look at it and I think we can go a simpler route by targeting the first cell of the table which has a list to have `white-space: normal;` instead of the whole table, since the issue is pretty much specific with this table type.
So if we just add `white-space: normal;` to the [CSS class name here](https://github.com/google/site-kit-wp/blob/develop/assets/sass/components/global/_googlesitekit-table.scss#L181), there will be minimum of regressions.
This is how it'll look:
![image](https://user-images.githubusercontent.com/31818/118151459-b4331100-b424-11eb-86b4-4b69c8182761.png)

**Comment by Hazlitte** [comment]
@asvinb Your approach is simpler and more efficient than mine.  Thank you 👍
@aaemnnosttv I have updated the IB with @asvin's approach.

**Comment by aaemnnosttv** [comment]
@Hazlitte @asvinb the problematic whitespace style seems to be coming from the `TableOverflowContainer` which is the expected behavior as this container was designed to keep content from wrapping so that it overflows to allow horizontal scrolling. That may not be working as intended anymore, I'm not sure, but why not remove `TableOverflowContainer` from `LegacyAnalyticsDashboardWidgetTopAcquisitionSources` instead if it's undesirable in this context than override its style?

**Comment by asvinb** [comment]
Thanks for the context @aaemnnosttv . In that case, definitely, let's remove `TableOverflowContainer` from ` LegacyAnalyticsDashboardWidgetTopAcquisitionSources` 🙂

**Comment by Hazlitte** [comment]
@aaemnnosttv Removing the render of `TableOverflowContainer` from `LegacyAnalyticsDashboardWidgetTopAcquisitionSources` works well.  I have updated the IB accordingly.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by johnPhillips** [comment]
Just to note that the new version of the widget (`AcquisitionChannelsTable) also uses the `TableOverflowContainer` component and is showing the bug. I've therefore applied the same fix there, otherwise this issue may resurface when we launch the `widgets.moduleScreens` feature.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Can confirm that the `Organic Search` channel is displaying on smaller screen sizes.  I checked this on a few different mobile devices with FIrefox, Chrome, Safari etc. [Screenshot](https://user-images.githubusercontent.com/73545194/122937583-02172f00-d36a-11eb-955d-0efe39e4e425.png)
