### ISSUE TITLE
I can not connect with the google account

### ISSUE THREAD

**Issue by alaikke** [google/site-kit-wp#315]
I can not connect with the Google account, it returns to the main WordPress dashboard and nothing happens.
Can anyone help us?

Similar to #315

**Comment by jamesozzie** [comment]
@alaikke Can you perform the following steps and see if the same issue occurs ?
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate your other active WordPress plugins 
3. Temporarily activate an alternative theme
4. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png) as opposed to a different browser

If the above fails to resolve the issue please inform me of the following:
- Web Host Environment
- Console Errors
- PHP Errors 
- Any Firewall or security software on your web host (ie. ModSecurity)

**Comment by jamesozzie** [comment]
@alaikke I will close this issue now. If you are encountering the same issue feel free to reopen, and include any console errors or additional context.
