### ISSUE TITLE
Scaffold Idea Hub module class

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3150]
The new Idea Hub module should have its PHP module class scaffolded and added, behind a new feature flag for it. [See more information on the overall approach](https://docs.google.com/document/d/1mIBLvv-v2Y3OMiHsOn5kMu3Fnt-wAqbWDnAiuraTy0k/edit).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new PHP module class `Google\Site_Kit\Modules\Idea_Hub`, following the example of other module classes, specifically containing the following:
    * API scopes (via `Module_With_Scopes`): The only scope should be "https://www.googleapis.com/auth/ideahub.read".
    * Settings (via `Module_With_Settings` and a dedicated `Google\Site_Kit\Modules\Idea_Hub\Settings` class): The only setting for now should be `ideaLocale`, which expects a language or locale string (e.g. `en_US` or `es`).
    * An `is_connected` implementation that requires the `ideaLocale` option to be set / not empty.
    * An `on_deactivation` implementation that deletes all settings on deactivation, as usual.
    * A Site Health integration (via `Module_With_Debug_Fields`), which for now only exposes the value of `ideaLocale`, as `idea_hub_idea_locale` ("Idea Hub idea locale").
    * The class should not have any API services for now.
    * The class should use module slug `idea-hub`, name `Idea Hub`, description of `TODO.`, CTA of `TODO.`, order of `7`, `homepage` and `learn_more` should for now just be set to `https://www.google.com`.
* The class should also have the following REST datapoints scaffolded (**not implemented**):
    * `GET:new-ideas`
    * `GET:saved-ideas`
    * `GET:draft-post-ideas`
    * `GET:published-post-ideas`
    * `POST:create-idea-draft-post`
    * `POST:update-idea-state`
    * Each of the above should for now just return a closure that returns `null` (i.e. an empty implementation). The closure is needed because only a callback or a Google API request object are valid return values.
    * Despite all of the data points using the same empty implementation for now, they should each have their own `switch` case, to allow them to be similarly worked on without any merge conflicts.
    * In other words, every data point should have its own `switch` case which does `return function() { return null; }`. Each of these should also have the same `TODO: Implement this.` comment.
* There should be the usual test coverage for both the module class and the settings class. The class itself should not yet be integrated anywhere though, it should just be scaffolded. The rest happens in follow-up issues.

#### includes/Modules/Idea_Hub.php
* Create a new file, `includes/Modules/Idea_Hub.php`, containing a new class `Google\Site_Kit\Modules\Idea_Hub`.
* This new class should 
  * implement the following interfaces: `Module_With_Scopes`, `Module_With_Settings`, `Module_With_Debug_Fields` 
  * use the following traits: `Module_With_Scopes_Trait`, `Module_With_Settings_Trait`
* Declare a const `const MODULE_SLUG = 'idea-hub';`  
* Add a get_scopes function
  ```php
	public function get_scopes() {
		return array(
			'https://www.googleapis.com/auth/ideahub.read',
		);
	}
  ```
* Add a register function  

```php
public function register() {
		$this->register_scopes_hook();

		$this->register_screen_hook();
```

* Add an is_connected function 
```php
	public function is_connected() {
		$required_keys = array(
			'ideaLocale',
		);

		$options = $this->get_settings()->get();
		foreach ( $required_keys as $required_key ) {
			if ( empty( $options[ $required_key ] ) ) {
				return false;
			}
		}

		return parent::is_connected();
	}
```    

* Add a deactivation function
```php
	public function on_deactivation() {
		$this->get_settings()->delete();
	}
```

* Add a get debug fields function
```php
public function get_debug_fields() {
    $settings = $this->get_settings()->get();

    return array(
        'idea_hub_idea_locale'         => array(
            'label' => __( 'Idea Hub idea locale', 'google-site-kit' ),
            'value' => $settings['ideaLocale'],
            'debug' => Debug_Data::redact_debug_value( $settings['ideaLocale'] ),
        ),
    );
}
```

* Add a datapoint definition function (to make it easier for future dev, alphabetically sort all the keys):
```php
protected function get_datapoint_definitions() {
	return array(
		'GET:draft-post-ideas' => array( 'service' => '' ),
		'GET:new-ideas' => array( 'service' => '' ),
		'GET:published-post-ideas' => array( 'service' => '' ),
		'GET:saved-ideas' => array( 'service' => '' ),
		'POST:create-idea-draft-post' => array( 'service' => '' ),
		'POST:update-idea-state' => array( 'service' => '' ),
	);
}
```    

* Add your scaffolded request object for the given datapoints (again: to make it easier for future dev, alphabetically sort all the switch cases):

```php
protected function create_data_request( Data_Request $data ) {
	switch ( "{$data->method}:{$data->datapoint}" ) {
		case 'GET:draft-post-ideas':
			// @TODO implementation
			return function() {
				return null;
			};
		case 'GET:new-ideas':
			// @TODO implementation
			return function() {
				return null;
			};
		case 'GET:published-post-ideas':
			// @TODO implementation
			return function() {
				return null;
			};
		case 'GET:saved-ideas':
			// @TODO implementation
			return function() {
				return null;
			};
		case 'POST:create-idea-draft-post':
			// @TODO implementation
			return function() {
				return null;
			};
		case 'POST:update-idea-state':
			// @TODO implementation
			return function() {
				return null;
			};
	}
	return parent::create_data_request( $data );
}
```

* Add a setup info function
```php
protected function setup_info() {
    return array(
        'slug'        => self::MODULE_SLUG,
        'name'        => _x( 'Idea Hub', 'Service name', 'google-site-kit' ),
        'description' => __( 'TODO.', 'google-site-kit' ),
        'cta'         => __( 'TODO.', 'google-site-kit' ),
        'order'       => 7,
        'homepage'    => __( 'https://www.google.com', 'google-site-kit' ),
        'learn_more'  => __( 'https://www.google.com', 'google-site-kit' ),
    );
}
``` 

#### includes/Modules/Idea_Hub/Settings.php

* Create a new directory, `includes/Modules/Idea_Hub`, and a new file inside it: `Settings.php`
* Add a new setting to contain all settings: `const OPTION = 'googlesitekit_idea_hub_settings'`
* Add a function to get default

```php
protected function get_default() {
    return array(
        'ideaLocale' => '',
    )
```
FYI https://github.com/google/site-kit-wp/issues/2105 covers creating a sitekit function to get the locale.
    

### Test Coverage

Time to create some tests for our two new files. Create and scaffold as much of the tests as you can for these two files:

#### tests/phpunit/integration/Modules/Idea_HubTest.php

`tests/phpunit/integration/Modules/Idea_HubTest.php`
Reference test file:
https://github.com/google/site-kit-wp/blob/e17b5d0f715ee5c9b97e08d7ea153bf538271ef7/tests/phpunit/integration/Modules/Analytics_4Test.php

#### tests/phpunit/integration/Modules/Idea_Hub/SettingsTest.php

`tests/phpunit/integration/Modules/Idea_Hub/SettingsTest.php`
Reference test file:
https://github.com/google/site-kit-wp/blob/e17b5d0f715ee5c9b97e08d7ea153bf538271ef7/tests/phpunit/integration/Modules/Analytics_4/SettingsTest.php

### Visual Regression Changes

N/A

## QA Brief

* Review added module class and tests satisfy ACs

## Changelog entry

* Scaffold new `Idea_Hub` PHP class.

**Comment by tofumatt** [comment]
Overall approach looks good to me. 👍🏻 

IB ✅

**Comment by tofumatt** [comment]
QA ✅
