### ISSUE TITLE
Add ideaHubModule feature flag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3151]
There should be a new `ideaHubModule` feature flag to control availability of the new Idea Hub module. [See more information on the overall approach](https://docs.google.com/document/d/1mIBLvv-v2Y3OMiHsOn5kMu3Fnt-wAqbWDnAiuraTy0k/edit).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new feature flag `ideaHubModule`.
* If the `ideaHubModule` feature flag is enabled, the new `Google\Site_Kit\Modules\Idea_Hub` class (see #3150) should be registered alongside the existing core modules (see #2975 for similar work being done for the `Analytics_4` module class).
    * While this class is being implemented in #3150, the implementation of this issue can already get started regardless, since the class name is defined. #3150 is required to be merged first though.

## Implementation Brief

* Add `ideaHubModule` to the feature flags array in the `feature-flags.json` file
* Update the Modules::__construct method to add the new `Google\Site_Kit\Modules\Idea_Hub` module to the `$core_modules` array if the `ideaHubModule` feature flag is enabled. Use the `Feature_Flags::enabled` method to determine whether the `ideaHubModule` flag is enabled
* Update the `Modules::get_active_modules_option` method to add `idea-hub` slug to the `$option` variable if it contains the idea hub slug

### Test Coverage

* Update the existing PHPUnit tests if any are failing due to these changes

### Visual Regression Changes

* N/A

## QA Brief

* Enable the featureFlag `ideaHubModule` and from your dashboard, run this JS in the console:
```js
wp.apiFetch( { path: '/google-site-kit/v1/core/modules/data/list' } ).then( ( modules ) => {
    console.log( modules );
} );
```
* You should see the module in the response, then do the same with the flag disabled, and you should see no module.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by Hazlitte** [comment]
**QA Eng ✅**
