### ISSUE TITLE
Scaffold Idea Hub JS asset and datastore

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3152]
The new Idea Hub module needs to have a JS asset for client-side functionality, and its datastore should be scaffolded. [See more information on the overall approach](https://docs.google.com/document/d/1mIBLvv-v2Y3OMiHsOn5kMu3Fnt-wAqbWDnAiuraTy0k/edit).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `assets/js/modules/idea-hub` module directory.
* There should be a new `assets/js/modules/idea-hub/datastore` directory should for now only have an `index.js`, `base.js`, and `constants.js` file, creating a `modules/idea-hub` datastore which is nothing more than a base module store (via `createModuleStore`), and exposing a `registerStore( registry )` function like the existing stores do. The base module store should include support for only the `ideaLocale` setting slug (see related #3150 definition).
* There should be a new `assets/js/modules/idea-hub/index.js` file which simply exports through the above `registerStore` function for now (further functionality than the datastore will be added to the module at some point in the future).
* There should be a new `assets/js/googlesitekit-modules-idea-hub` JS file (also as entrypoint in webpack). It should call the `registerStore` function from the above with the Site Kit registry (`Data` from `googlesitekit-data`).

### Create the datastore
* Create a new `assets/js/modules/idea-hub` module directory, containing the following file and directory structure:
```
  assets/js/modules/idea-hub
  │   index.js
  │
  └───  datastore
      │   index.js
      │   base.js
      │   constants.js

```
* Inside `datastore/constants.js`:
  * declare and export a `STORE_NAME` constant with a value of `modules/idea-hub` 
  * declare and export an aliased `{ STORE_NAME as MODULES_IDEA_HUB }` constant
* Inside `datastore/base.js`
  * Import the `STORE_NAME` constant from the constants file
  * Create and export `baseModuleStore` constant using `Modules.createModuleStore` that uses the slug `idea-hub`, and contains `ideaLocale` in the `settingSlugs` array
  ```js
    const baseModuleStore = Modules.createModuleStore( 'idea-hub', {
      storeName: STORE_NAME,
      settingSlugs: [
        'ideaLocale'
      ],
    } );
  ```
* Inside `datastore/index.js`:
  * Import the `STORE_NAME` constant from the constants file
  * Import the `baseModuleStore` function from the base file
  * Export a `registerStore` function that uses the `STORE_NAME` and the `baseModuleStore`:
  ```js
  export const registerStore = ( registry ) => {
        registry.registerStore( STORE_NAME, baseModuleStore );
  };
  ```
* Inside the root `idea-hub/index.js` file:
  * Import the `registerStore` function from `./datastore/index.js`, aliasing it to `registerDataStore`
  * Export a `registerStore` constant that calls `registerDataStore`, passing the registry:
  ```js
  export const registerStore = ( registry ) => {
    registerDataStore( registry );
  });
  ```

### Create entry point in Webpack
* Create a file `assets/js/googlesitekit-modules-idea-hub.js`, and inside it
  * Import `Data` from `googlesitekit-data`
  * Import the `registerStore` function from `assets/js/modules/idea-hub/`
  * Call the `registerStore` function, passing it `Data` (the registry) 
* Inside `webpack.config.js`, add a new entry point (with the other module entry points around line 152):
  ```js
  'googlesitekit-modules-idea-hub': './assets/js/googlesitekit-modules-idea-hub.js',
  ```

### Test Coverage

* No new tests; existing ones should pass

### Visual Regression Changes

* No changes

## QA Brief

* Verify that a a base module store has been created and registered

## Changelog entry

* Scaffold new `modules/idea-hub` data store in JS.

**Comment by tofumatt** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
QA ✅
1. Enabled feature flag `/wp-admin/admin.php?page=googlesitekit-tester` - `ideaHubModule`
2. Opened dashboard `/wp-admin/admin.php?page=googlesitekit-dashboard`
3. Checked for store: `googlesitekit.data.stores["modules/idea-hub"]` - exists.
4. Checked page source for separate javascript file - exists
`<script src='/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-idea-hub.js' id='googlesitekit-modules-idea-hub-js'></script>`
