### ISSUE TITLE
Register Idea Hub JS asset in Idea_Hub PHP class

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3153]
To connect the work from #3150 and #3152, the new Idea Hub module class in PHP should register the new Idea Hub JS asset. [See more information on the overall approach](https://docs.google.com/document/d/1mIBLvv-v2Y3OMiHsOn5kMu3Fnt-wAqbWDnAiuraTy0k/edit).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Idea_Hub` PHP class introduced in #3150 should implement `Module_With_Assets`, registering a `googlesitekit-modules-idea-hub` script asset which is the `assets/js/googlesitekit-modules-idea-hub.js` file introduced in #3152.

## Implementation Brief

* Open the Idea_Hub class, `includes/Modules/Idea_Hub.php`
* This class should implement `Module_With_Assets` and use the `Module_With_Assets_Trait`
  * First add them to the class 
    ```php
    use Google\Site_Kit\Core\Modules\Module_With_Assets;
    use Google\Site_Kit\Core\Modules\Module_With_Assets_Trait;
    /* ... */
    implements Module_With_Assets
    /* ... */
    use Module_With_Assets_Trait;
    ```
  * Now add an implementation of `setup_assets`, with a basic selection of dependencies:
  ```php
  protected function setup_assets() {
	$base_url = $this->context->url( 'dist/assets/' );

	return array(
		new Script(
			'googlesitekit-modules-idea-hub',
			array(
				'src'          => $base_url . 'js/googlesitekit-modules-idea-hub.js',
				'dependencies' => array(
					'googlesitekit-vendor',
					'googlesitekit-api',
					'googlesitekit-data',
					'googlesitekit-modules',
				),
			)
		),
	);
  }
  ``` 

### Test Coverage

* No new tests; existing tests should pass

### Visual Regression Changes

* N/A

## QA Brief

* Make sure that the `ideaHubModule` feature flag is enabled
* Visit the SK dashboard, and verify that the `dist/assets/js/googlesitekit-modules-idea-hub.js` has been loaded
* Verify that the `modules/idea-hub` datastore is available (e.g. by using Redux devtools)

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by Hazlitte** [comment]
**QA Eng ✅**
