### ISSUE TITLE
Implement Idea Hub infrastructure (with mocks) for querying new ideas

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3155]
The Idea Hub infrastructure to retrieve new ideas should be implemented, with mock data for now since we cannot use the real API yet. [See more information on the overall approach](https://docs.google.com/document/d/1mIBLvv-v2Y3OMiHsOn5kMu3Fnt-wAqbWDnAiuraTy0k/edit).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GET:new-ideas` data point of the new `Idea_Hub` module class should be implemented to return a mocked response, hard-coded into a variable (see below for the response to return). The `TODO` annotation for this data point should be modified to say `TODO: Implement this with the real API endpoint.`.
* The `modules/idea-hub` datastore should get a new selector `getNewIdeas( options )` which uses the `GET:modules/idea-hub/data/new-ideas` REST datapoint to list ideas.
    * `options` should be optional and support properties `offset` and `length`.
    * `options` **must not** be passed through to the server at this point. The server should always return all new ideas. Instead, it should only be used within the selector itself, to return a slice of the available new ideas. In other words, the resolver should also ignore `options` and only request the data once, if it's not available in the store state yet.

The following mock response should be used for the `GET:new-ideas` data point:
```json
[
    {
        "name": "ideas/17450692223393508734",
        "text": "Why Penguins are guanotelic?",
        "topics": [
            {
                "mid": "/m/05z6w",
                "display_name": "Penguins"
            }
        ]
    },
    {
        "name": "ideas/14025103994557865535",
        "text": "When was sushi Kalam introduced?",
        "topics": [
            {
                "mid": "/m/07030",
                "display_name": "Sushi"
            }
        ]
    },
    {
        "name": "ideas/7612031899179595408",
        "text": "How to speed up your WordPress site",
        "topics": [
            {
                "mid": "/m/09kqc",
                "display_name": "Websites"
            }
        ]
    },
    {
        "name": "ideas/2285812891948871921",
        "text": "Using Site Kit to analyze your success",
        "topics": [
            {
                "mid": "/m/080ag",
                "display_name": "Analytics"
            }
        ]
    },
    {
        "name": "ideas/68182298994557866271",
        "text": "How to make carne asada",
        "topics": [
            {
                "mid": "/m/07fhc",
                "display_name": "Cooking"
            }
        ]
    }
]
```

## Implementation Brief
* Once #3150 and #3152 have been merged.
* Using `includes/Modules/Idea_Hub.php`,
	* Update the `GET:new-ideas` endpoint in the `create_data_request` function to return the following mocked data:
	```js
	[
	    {
	        "name": "ideas/17450692223393508734",
	        "text": "Why Penguins are guanotelic?",
	        "topics": [
	            {
	                "mid": "/m/05z6w",
	                "display_name": "Penguins"
	            }
	        ]
	    },
	    {
	        "name": "ideas/14025103994557865535",
	        "text": "When was sushi Kalam introduced?",
	        "topics": [
	            {
	                "mid": "/m/07030",
	                "display_name": "Sushi"
	            }
	        ]
	    },
	    {
	        "name": "ideas/7612031899179595408",
	        "text": "How to speed up your WordPress site",
	        "topics": [
	            {
	                "mid": "/m/09kqc",
	                "display_name": "Websites"
	            }
	        ]
	    },
	    {
	        "name": "ideas/2285812891948871921",
	        "text": "Using Site Kit to analyze your success",
	        "topics": [
	            {
	                "mid": "/m/080ag",
	                "display_name": "Analytics"
	            }
	        ]
	    },
	    {
	        "name": "ideas/68182298994557866271",
	        "text": "How to make carne asada",
	        "topics": [
	            {
	                "mid": "/m/07fhc",
	                "display_name": "Cooking"
	            }
	        ]
	    }
	]
	```
	* Update the `TODO` annotation as well to: `TODO: Implement this with the real API endpoint.`
* Using `assets/js/modules/idea-hub/datastore`,
	* Create new file `new-ideas.js` which should create a new store, `fetchGetNewIdeasStore` using the `createFetchStore` function (Data stores from other modules can be taken as example).
		* The `baseName` of the store should be `getNewIdeas`.
		* The `modules/idea-hub/data/new-ideas` REST endpoint should be used to grab the data. Even though we have an `options` parameter passed to the `getNewIdeas` selector (see below), the `options` must not be passed through to the server at this point.
		* Using the `reducerCallback` function of the `createFetchStore` function, slice the data returned from the API using the values from the `options` parameter.
	* Default state of the data store should contain the `newIdeas` property which is an empty array.
	* Add a new selector `getNewIdeas` which accepts an object as parameter `options`. The latter should be optional and support properties `offset` and `length`. The selector should return the list of ideas, which is the `newIdeas` state property.
	* Add a new resolver `getNewIdeas` which should first check if there is any data in the store before requesting data from the REST endpoint.

### Test Coverage
* Tests for the `getNewIdeas` selector should be added.

### Visual Regression Changes
* N/A.

## QA Brief

* Ensure tests run.
* Try it out `googlesitekit.data.stores["modules/idea-hub"].selectors.getNewIdeas({length: 1, offset:1})`

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
I know it's a bit more effort, but wouldn't it be nicer to pass the `options` through to the server now and then have the server code filter the array returned based on the options? That's the plan here but we're doing it client-side instead of on the server.

Assuming the server will eventually handle this, why not write the "temporary" code only once: on the server where it'll get replaced? That way we can write the client-side code once.

Is there any reason not to do it that way, @felixarntz? Are we concerned the API is too "alpha" to predictably write the client code for?

**Comment by felixarntz** [comment]
@tofumatt The approach here is explicitly to not handle pagination on the server, not eventually either - so keeping the pagination options on the client-side is regardless of whether we use the API mock or the real API. We're not going to have pagination on the server-side because we will never request more than a 100 ideas, which will be available in a single response. Plus, we will only show pages with 4-5 ideas, i.e. the experience of making 20 requests while browsing between pages would be a worse experience.

**Comment by tofumatt** [comment]
Ah, okay! Thanks for the clarification 👍🏻 

In that case: IB looks good 🙂 

IB ✅

**Comment by asvinb** [comment]
- All tests pass when running `npm test:js`.
- Activated the ` ideaHubModule` feature flag and data is being returned when the `googlesitekit.data.stores["modules/idea-hub"].selectors.getNewIdeas({length: 1, offset:1})` command is run in the the console.
<img width="641" alt="Screenshot 2021-05-04 at 12 18 01" src="https://user-images.githubusercontent.com/31818/116977093-111b2280-acd3-11eb-90b0-be070e696622.png">

### QA: ✅
