### ISSUE TITLE
Implement Idea Hub infrastructure for querying saved ideas

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3156]
The Idea Hub infrastructure to retrieve saved ideas should be implemented, with an empty response for now since we cannot use the real API yet. [See more information on the overall approach](https://docs.google.com/document/d/1mIBLvv-v2Y3OMiHsOn5kMu3Fnt-wAqbWDnAiuraTy0k/edit).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GET:saved-ideas` data point of the new `Idea_Hub` module class should be implemented to return an empty array (basically indicating that no ideas are saved). The `TODO` annotation for this data point should be modified to say `TODO: Implement this with the real API endpoint.`.
* The `modules/idea-hub` datastore should get a new selector `getSavedIdeas( options )` which uses the `GET:modules/idea-hub/data/saved-ideas` REST datapoint to list ideas.
    * `options` should be optional and support properties `offset` and `length`.
    * `options` **must not** be passed through to the server at this point. The server should always return all new ideas. Instead, it should only be used within the selector itself, to return a slice of the available new ideas. In other words, the resolver should also ignore `options` and only request the data once, if it's not available in the store state yet.
    * This should follow the same implementation as #3155.

## Implementation Brief
* Once #3150 and #3152 have been merged.
* Using `includes/Modules/Idea_Hub.php`,
	* Update the `GET:saved-ideas` endpoint in the `create_data_request` function to return an empty array.
	* Update the `TODO` annotation as well to: "TODO: Implement this with the real API endpoint."
* Using `assets/js/modules/idea-hub/datastore`,
	* Create new file `saved-ideas.js` which should create a new store, `fetchGetSavedIdeasStore` using the `createFetchStore` function (Data stores from other modules can be taken as example).
		* The `baseName` of the store should be `getSavedIdeas`.
		* The `modules/idea-hub/data/saved-ideas` REST endpoint should be used to grab the data. Even though we have an `options` parameter passed to the `getSavedIdeas` selector (see below), the `options` must not be passed through to the server at this point.
		* Using the `reducerCallback` function of the `createFetchStore` function, slice the data returned from the API using the values from the `options` parameter.
	* Default state of the data store should contain the `savedIdeas` property which is an empty array.
	* Add a new selector `getSavedIdeas` which accepts an object as parameter `options`. The latter should be optional and support properties `offset` and `length`. The selector should return the list of ideas, which is the `savedIdeas` state property.
	* Add a new resolver `getSavedIdeas` which should first check if there is any data in the store before requesting data from the REST endpoint.

### Test Coverage
* Tests for the`getSavedIdeas` selector should be added.

### Visual Regression Changes
* N/A

## QA Brief

* Ensure tests run.
* Try it out `googlesitekit.data.stores["modules/idea-hub"].selectors.getSavedIdeas();` should return an empty array.

## Changelog entry

* Add Idea Hub saved idea selectors and actions.

**Comment by tofumatt** [comment]
IB ✅

**Comment by asvinb** [comment]
- All tests pass.
- Running the `googlesitekit.data.stores["modules/idea-hub"].selectors.getSavedIdeas();` command in the console returns an empty array.

### QA: ✅
