### ISSUE TITLE
Implement infrastructure for storing Idea Hub idea information with WordPress posts

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3157]
Since the Idea Hub module will allow creating WordPress posts based on Idea Hub ideas, it should be possible to store an idea's full information within a post. [See more information on the overall approach](https://docs.google.com/document/d/1mIBLvv-v2Y3OMiHsOn5kMu3Fnt-wAqbWDnAiuraTy0k/edit).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Google\Site_Kit\Modules\Idea_Hub\Post_Idea_Name` class should be implemented which extends `Google\Site_Kit\Core\Storage\Post_Meta_Setting`.
    * Its meta key should be `googlesitekitpersistent_idea_name`.
    * Its type should be a string (it's expecting a slug).
* A new `Google\Site_Kit\Modules\Idea_Hub\Post_Idea_Text` class should be implemented which extends `Google\Site_Kit\Core\Storage\Post_Meta_Setting`.
    * Its meta key should be `googlesitekitpersistent_idea_text`.
    * Its type should be a string (it's expecting a human-readable label).
* A new `Google\Site_Kit\Modules\Idea_Hub\Post_Idea_Topics` class should be implemented which extends `Google\Site_Kit\Core\Storage\Post_Meta_Setting`.
    * Its meta key should be `googlesitekitpersistent_idea_topics`.
    * Its type should be an array (it's expecting a list of objects / associative arrays, each with `mid` and `display_name` fields).
    * Its sanitize callback should ensure every entry within the array is an associative array with `mid` and `display_name` string fields.
* The `Idea_Hub` class should register the new `Post_Meta_Setting`s implemented.
* The `Idea_Hub` class should receive two new protected methods:
    * `set_post_idea( int $post_id, array $idea ) : bool`: Stores metadata in the given post based on the idea passed, relying on the 3 `Post_Meta_Setting`s. `$idea` is expected to be an associative array for a single idea (see #3155 for the exact format of such an idea).
    * `get_post_idea( int $post_id ) : array | null`: Returns an idea array based on the post metadata (relying on the 3 `Post_Meta_Setting`s) stored in the post, or returns `null` if any of the 3 pieces of data is not stored. The returned idea format should match the idea format returned by the API (see #3155 for the exact format of such an idea).

## Implementation Brief

Following #3154,

Create a new file `includes/Modules/Idea_Hub/Post_Idea_Name.php`

```php
class Post_Idea_Name extends Post_Meta_Setting {
	const META_KEY = 'googlesitekitpersistent_idea_name';
}
```    

Create a new file `includes/Modules/Idea_Hub/Post_Idea_Text.php`

```php
class Post_Idea_Text extends Post_Meta_Setting {
	const META_KEY = 'googlesitekitpersistent_idea_text';
} 
```    

Create a new file `includes/Modules/Idea_Hub/Post_Idea_Topics.php`

```php
class Post_Idea_Topics extends Post_Meta_Setting {
	const META_KEY = 'googlesitekitpersistent_idea_topics';

	protected function get_type() {
		return 'array';
	}

	protected function get_sanitize_callback() {
		return function ($option) {
			// @TODO: Sanitize callback should ensure every entry within the array
			// is an associative array with mid and display_name string fields.
			return $option;
		};
    }
}

```    

Update the `register()` function in `includes/Modules/Idea_Hub.php` to register each of the new `Post_Meta_Setting`s above.

Add two new functions to `includes/Modules/Idea_Hub.php`, `set_post_idea()` and `get_post_idea()` per the AC.

### Test Coverage

Update `tests/phpunit/integration/Modules/Idea_HubTest.php` to add `test_set_post_idea()` and `test_get_post_idea()`

### Visual Regression Changes

* N/A

## QA Brief

* Check the Idea_Hub class to make sure it registers settings defined in the AC.
* Also verify that the Idea_Hub has two new methods `set_post_idea` and `get_post_idea` and they work as required in the AC.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@ivankruchkoff the `Post_Meta_Setting::get_type` method already returns `string` by default, so there is no need in overriding this method in `Post_Idea_Name` and `Post_Idea_Text` classes. Also, please, try to avoid using code snippets when possible. Better use narrative statements that explain what needs to be done in specific places.

> Update tests/phpunit/integration/Modules/Idea_HubTest.php

Could you please elaborate a little bit more here? What exactly needs to be updated there? Do we need to add new tests or update existing ones?

**Comment by ivankruchkoff** [comment]
> @ivankruchkoff the `Post_Meta_Setting::get_type` method already returns `string` by default, so there is no need in overriding this method in `Post_Idea_Name` and `Post_Idea_Text` classes. Also, please, try to avoid using code snippets when possible. Better use narrative statements that explain what needs to be done in specific places.

Updated

> 
> > Update tests/phpunit/integration/Modules/Idea_HubTest.php
> 
> Could you please elaborate a little bit more here? What exactly needs to be updated there? Do we need to add new tests or update existing ones?

Updated

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by asvinb** [comment]
@eugene-manuilov The `get_post_idea` method should return null if any of the 3 pieces of data is not stored. I don't see that part implemented. Can you check please?

### QA: Waiting for engineer to confirm

**Comment by eugene-manuilov** [comment]
@asvinb yes, it hasn't been added. I'll create a follow up PR.

**Comment by tofumatt** [comment]
Thanks @asvinb, sorry I missed that bit in the PR! 😓

**Comment by asvinb** [comment]
No worries @tofumatt .
### QA ✅
