### ISSUE TITLE
The response is not a valid JSON response. (Google Site Kit)

### ISSUE THREAD

**Issue by SintoJoseph** [google/site-kit-wp#316]
I was trying to install Google Site Kit on my wordpress site. After getting Site Kit: Get OAuth Credentials and pasting on the plugin I get The response is not a valid JSON response. message. I am not using any Ad blocker. 
![google site kit error](https://user-images.githubusercontent.com/53149638/61593955-d7634f80-ac03-11e9-853b-8a48a4bd4456.JPG)

**Comment by jamesozzie** [comment]
@SintoJoseph Thanks for reporting. This looks similar to #242. It would be great to find out more about this error, as I have not been able to recreate. Can you please follow the steps below:  

1. Please check your WordPress site settings under "Settings > General" in your WordPress dashboard. Confirm your WordPress Address (URL) and Site Address (URL) match, and ensure they have a https prefix if you are using a https website. 
2. Restart the Site Kit setup process again
3. If the same error appears close the "Couldn't create project" window
4. In the address bar of your window paste the following in: https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
5. Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
6. Press enter, with your cursor in the address bar (as if you are visiting that URL)
7. Press the "GET OAUTH CREDENTIALS" button
8. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

If the above fails please inform me of the following:
- Web Host Environment
- Security / Firewall plugins in use
- PHP Version
- Console Errors
- PHP Errors

**Comment by SintoJoseph** [comment]
Hi,
    I tried your steps mentioned but I get error message.

   - Web Host Environment:   Hostinger
   - Security / Firewall plugins in use Cloudflare (I disabled it and tried
   but still getting error)
   - PHP Version 7.1
   - Console Errors  Nil
   - PHP Errors   Nil

Thanking You,

Regards,

[image: looking for desiring bride]

Sinto Joseph

Entrepreneur | YouTuber

Mobile No.: +91-8197452685

Website: www.finysel.com

Live a Life you Love it all that matters.

Connect or follow me on:

[image: facebook.png] <https://www.facebook.com/sinto.joseph2> [image:
youtube.png] <http://www.youtube.com/c/SintoJosephnet?sub_confirmation=1>
[image:
twitter.png] <https://twitter.com/SintoJoseph> [image: google-plus.png]
<https://plus.google.com/u/0/101540631261441440343> [image: pinterest.png]
<https://in.pinterest.com/finysel/> [image: linkedin.png]
<https://in.linkedin.com/in/sinto-joseph-4484b31b>

**Comment by quangbahoa** [comment]
I fixed this error by remove space after json line. If you got error again just copy json from Google then paste to plan text editor then copy and paste to Site Kit step.

**Comment by SintoJoseph** [comment]
Hi,
   Thanks it Worked !
Thanking You,

Regards,

[image: looking for desiring bride]

Sinto Joseph

Entrepreneur | YouTuber

Mobile No.: +91-8197452685

Website: www.finysel.com

Live a Life you Love it all that matters.

Connect or follow me on:

[image: facebook.png] <https://www.facebook.com/sinto.joseph2> [image:
youtube.png] <http://www.youtube.com/c/SintoJosephnet?sub_confirmation=1>
[image:
twitter.png] <https://twitter.com/SintoJoseph> [image: google-plus.png]
<https://plus.google.com/u/0/101540631261441440343> [image: pinterest.png]
<https://in.pinterest.com/finysel/> [image: linkedin.png]
<https://in.linkedin.com/in/sinto-joseph-4484b31b>

**Comment by quangbahoa** [comment]
@SintoJoseph Closed this issue please!

**Comment by vikaskumawat80** [comment]
Getting "The response is not a valid JSON response." Tried everything but not working.

Web Host Environment: Azure Web App Linux
Security / Firewall plugins in use: No
PHP Version: 7.2.13
Console Errors: The response is not a valid JSON response.
PHP Errors: NA

**Comment by jamesozzie** [comment]
@vikaskumawat80 Can you try and implement your own JSON response using the steps below:
- In the browser address bar (preferably using an incognito window) visit the following:
- https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com (Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http)
- Press enter, with your pointer in the address bar (as if you are visiting that URL)
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit you highlighted.
- Please let me know if that works, allowing you to proceed with the setup.

**Comment by obiwankanobewannabe** [comment]
In my case this was caused by an  IThemes Security issue: It was fixed by unchecking the "Filter Long URL Strings" in System Tweaks in iThemes Security settings (and saving of course).
According to IThemes, the purpose of this is "Limits the number of characters that can be sent in the URL. Hackers often take advantage of long URLs to try to inject information into your database."
This was all discussed in this closed thread:
https://github.com/google/site-kit-wp/issues/316

In the thread, it states that Ithemes would drop that option. But the thread was from 2019 and ithemes has NOT done that.
Also, I am concerned that not having this option check leaves a bit of a security hole. 
So I'd like to raise the issue again as to can this be addressed on the Google Site kit side by cutting back your string length to something more reasonable.

Thanks.

**Comment by jamesozzie** [comment]
@quangbahoa Thanks for sharing. We've had internal discussions on this and using the the various Google Services API's at present it's normal for the full strings to have varying lengths depending on the parameters. While other methods we've investigated are not as suitable if you want to open a feature request the team can review once more.

**Comment by neftelimov** [comment]
Help, please. 

A network error occurred and the request could not be completed.
![scrnli_2-08-2021 г-_12-45-03 ч-](https://user-images.githubusercontent.com/88317927/127841267-aaaf5eed-bff6-4800-aae6-3907dab2fa99.png)

**Comment by jamesozzie** [comment]
@neftelimov If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on the WordPress support forums where we provide initial plugin assistance we'd be happy to assist. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.  

I would also advise uninstalling the plugin in full and reinstalling once more. You don't need to disconnect or reset Site Kit before doing so, it looks like you're encountering the setup flow from an older version of the plugins somehow.

**Comment by dawidmosk** [comment]
In my case was with other "helping" plugins. Basically disabled all except basic.
