### ISSUE TITLE
Display UA property IDs next to property names in dropdowns

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3164]
While this issue is not strictly related to GA4 and will immediately result in a user-facing change, it is a step towards GA4 where this will be more crucial; as it is now, it is still an enhancement, since sometimes the name of a property may be duplicated and therefore not clearly indicate which property it is.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing Analytics (UA) `PropertySelect` dropdown should be updated to always display the property ID after the name in parentheses, e.g. "My Property (UA-123456-7)".

## Implementation Brief

* Update dropdown option labels in the `PropertySelect` component (`assets/js/modules/analytics/components/common/PropertySelect.js`) to display the property `id` attribute in parentheses after `name`: https://github.com/google/site-kit-wp/blob/a24a1f3c588c73eb1b3a72d0221f7a66ca461882/assets/js/modules/analytics/components/common/PropertySelect.js#L90-L98
* Use `sprintf( __( '%1$s (%2$s)' ), name, id )` to ensure the string is translated/localized properly.

### Test Coverage

* Update existing PropertySelect tests if any of them fails due to the aforementioned changes.

### Visual Regression Changes

* Property IDs will be displayed in the dropdown field after property names.

## QA Brief

* Connect Analytics in Site Kite
* In `Settings` edit the Analytics settings
* Check that the `Property` field displays the name and property ID

## Changelog entry

* Update Analytics property select options to display property IDs in addition to names.

**Comment by tofumatt** [comment]
Looks good, but I added one note to use `sprintf( __( '%1$s (%2$s)' ), name, id )`, so the string is translated/localized properly. I figured better to leave it here than in the code review in case someone missed it, as it's an easy oversight not to translate things like these.

IB ✅

**Comment by aaemnnosttv** [comment]
@Hazlitte would you please add a QA brief?

**Comment by Hazlitte** [comment]
@aaemnnosttv Yes of course.  Apologies that I forgot to do that.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Confirmed that the Property field displays the name and property ID when you edit Analytics in the settings. 

![image](https://user-images.githubusercontent.com/73545194/116280610-c5232780-a780-11eb-9449-1c2d611e735d.png)
