### ISSUE TITLE
Implement selector to get all UA + GA4 properties

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3167]
There should be a selector to get all Analytics properties, i.e. including both UA and GA4. The transitional UI for users that have both UA and GA4 should be implemented as part of the `analytics` module, as such this selector should become part of the `modules/analytics` datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/analytics` store should have a new selector `getPropertiesIncludingGA4( accountID )`.
    * It should rely on the `modules/analytics` selector `getProperties` to get all UA properties for the account.
    * _If_ the `modules/analytics-4` store is available, it should rely on its `getProperties` selector to get all GA4 properties for the account.
    * If both are being combined, it should sort the two lists of property objects (**which have a different format**) together, first by property name, then by property ID (e.g. "Same Name (12345)" should come before "Same Name (UA-12345-6)"). The sorting should happen in a memoized way to not cause performance issues.

## Implementation Brief
* Using `assets/js/modules/analytics/datastore/properties.js`,
	* Add new selector `getPropertiesIncludingGA4`:
		* which relies on the `getProperties` selector to get all UA properties for the account.
		* If the `modules/analytics-4` data store is available, use the `getProperties` selector to get all GA4 properties for the account.
		* Combine the results of the `getProperties` selector for both data stores first by property name, then by property ID (e.g. "Same Name (12345)" should come before "Same Name (UA-12345-6)") and then return the combined list.

### Test Coverage
* Add tests for the new `getPropertiesIncludingGA4` selector.

### Visual Regression Changes
* N/A

## QA Brief

Ensure tests pass and `npm run build` runs without errors.

## Changelog entry

* Implement selector to get all UA + GA4 properties.

**Comment by tofumatt** [comment]
@felixarntz @asvinb I'm not sure about the ACs here, namely:

> The `modules/analytics` store should have a new selector `getAllProperties( accountID )`.

This will result in two very similar selectors, `getProperties( accountID )` and `getAllProperties( accountID )` in the store, which is confusing to read. The distinction between the two isn't evident from their names, and I could even see the potential for a developer to read them as the same thing. I think it's better we go one of two routes:

1. Augment the existing selector with a second, `options`-type argument with a `includeGA4Properties` attribute, set to false by default. eg. `getProperties( accountID )` behaves as it does today, but `getProperties( accountID, { includeGA4Properties: true } )` returns both UA + GA4 properties. This is my preferred approach.
2. Name the selector something like `getPropertiesIncludingGA4( accountID )`, so it's very explicit what the difference is.

Other than that the ACs and IB look good, but I think we should make this clearer to avoid developer confusion in the future.

**Comment by felixarntz** [comment]
@tofumatt Good point! I went with keeping it a different selector but using a more clear name. I've updated this in the ACs and IB (which was already looking good), so IB ✅

**Comment by tofumatt** [comment]
QA ✅
