### ISSUE TITLE
Allow matching a GA4 property by data in its web data stream

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3168]
For UA properties (i.e. the current `analytics` module), we're trying to match a property in two situations:
* When trying to find the default property to show in the dropdown, we try to match a property by the current site URL.
* When checking whether the current user has access to an existing tag, we try to match a property by the current tag ID.

In GA4, unfortunately this becomes more complicated: While for UA properties the URL and tag ID are both stored within the property object (the tag ID even _is_ the property ID), for GA4 properties both the URL and tag ID (now called "measurement ID") are stored within one of the web data streams, which a property has multiple of and which, unfortunately (!), have to be separately queried.

This is potentially a very expensive operation, depending on how many properties the user has access to. However, this is where we currently are, and it will not change before launch, although it may at some point later in the future. At this point, #3104 provides the foundation to at least not completely overload the server with requests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be two new actions in the `modules/analytics-4` datastore `matchPropertyByURL( properties, url )` and `matchPropertyByMeasurementID( properties, measurementID )` which work almost the same way as in they iterate over all web data streams for the given properties to find the matching property either by the given URL or the given measurement ID.
    * Use the `getWebDataStreamsBatch( properties )` selector (see #3104) for groups of 10 property IDs each, to eventually get all web data streams for all properties (i.e. if less than 10 properties are passed, only a single batch request is needed). Every time a response is received, iterate over the web data streams to see if any of them matches the second parameter passed (see below for details). If a matching web data stream is found, return the enclosing property via the `getProperty` selector; otherwise, if the end is reached and none is found, return `null`.
        * When matching a URL, rely on the web data stream's `defaultUri` field.
        * When matching a measurement ID, rely on the web data stream's `measurementId` field.
        * For both actions, allow the second parameter to be either a single (string) value or an array of multiple (string) values. It's not necessary to explicitly validate it, but the function should perform a `contains` comparison instead of an `===` comparison if an array is passed.
    * Explicitly, the individual web data stream batch requests should not all be fired at once, but rather sequentially, to only make requests as needed. For example, if the first request already comes back with one of the matching web data streams, the second one shouldn't be made.

## Implementation Brief

* Create a new generator action `matchPropertyByURL( properties, url )` in the properties datastore of the `analytics-4` module.
  * Split properties array into chunks by 10 properties each.
  * Loop through all chunks calling the `getWebDataStreamsBatch` selector for each slice to retrieve web data streams batches. Use the following snippet as an example how to get web data streams:
    ```javascript
    const webdatastreams = yield Data.commonActions.await( registry.__experimentalResolveSelect( STORE_NAME ).getWebDataStreamsBatch( ... ) );
     ```
  * Loop through each web data stream of the returned batch and try to find one that has a matching URI comparing `defaultUri` property of a web data stream with the incoming `url` parameter. If `url` is an array, loop through each URL in the array and compare it with the `defaultUri`.
  * If a datastream is found, break the loop and return a full property object using `getProperty( ... )` selector.
  * Otherwise return null.
* Create a new generator action `matchPropertyByMeasurementID( properties, measurementID )` in the properties datastore of the `analytics-4` module.
  * Use the same approach to get web data stream batches but instead of comparing URIs, compare measurement IDs.

### Test Coverage

* Add js tests for the new actions.

### Visual Regression Changes

* N/A

## QA Brief

* JS Unit tests should pass; they are the only place this functionality is used right now.

## Changelog entry

* Add selectors to select a GA4 property from webdata stream contents.

**Comment by felixarntz** [comment]
@eugene-manuilov Mostly LGTM, just one thing:

> Loop through each web data stream of the returned batch and try to find one that has matching URI using `isSiteURLMatch` selector from the `core/site` datastore. If `url` is an array, loop through each URL in the array and compare it with the current site URL.

This shouldn't need to use `isSiteURLMatch`, the idea is that it receives any URLs that it should match via the `url` parameter. In other words, this is a low-level action which should only be used internally by other selectors or actions, and _those_ would then use `isSiteURLMatch` as needed. If we were using `isSiteURLMatch` here, the action would be more like `matchPropertyBySiteURL( properties )`, but it should be `matchPropertyByURL( properties, url )` so that the URLs can be specified in the consuming code.

**Comment by eugene-manuilov** [comment]
Ah... yes, good catch, @felixarntz. I have updated IB to compare `url` with `defaultUri` property of a web data stream.

**Comment by felixarntz** [comment]
IB ✅

**Comment by johnPhillips** [comment]
QA ✅
Verified that the JS tests pass.
