### ISSUE TITLE
Implement GA4 selector to check if Admin API is generally working correctly

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3169]
The GA4 implementation will initially rely on an alpha version of the Analytics Admin API, which is clearly problematic in a way, but is currently needed. Furthermore, given that the GA4 functionality at this point is not essential to using Site Kit, it will entirely be implemented in a way that, should one of the key API requests fail, the functionality is ignored, assuming that there was a breaking change in the API.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `modules/analytics-4` selector `isAdminAPIWorking()` which returns a boolean for whether the Admin API is "essentially working correctly" (or `undefined` if not loaded yet).
    * Returns `true` if both `modules/analytics-4` selectors `getProperties` and `getWebDataStreams` have resolved successfully (for _any_ selector parameters).
    * Returns `false` if one of them resulted in an error.
    * Returns `undefined` otherwise.

## Implementation Brief

* Create a new partial datastore `assets/js/modules/analytics-4/datastore/api.js`. It should follow the general approach of defining different parts of a datastore (like base actions, controllers, resolvers, etc) and export combined store along with base bits via named export. See `properties` partial datastore for reference.
* Add a new `isAdminAPIWorking` selector:
  * It should return `TRUE` if:
    * The `state['properties']` object has at least one account with a non-empty array of properties;
    * The `state['webdatastreams']` object has at least one property with a non-empty array of web datastreams;
    * There are no entries in the `state['errors']` object which key start with `getProperties::` prefix;
    * There are no entries in the `state['errors']` object which key start with `getWebDataStreams::` prefix.
  * It should return `FALSE` if there is at least one error in the `state['errors']` object with these prefixes;
  * It should return `undefined` if `state['properties']` and `state['webdatastreams']` objects are empty and there is no errors in the `state['errors']` object with previously defined prefixes.

### Test Coverage

* Add js tests to cover possible cases for the new selector.

### Visual Regression Changes

* N/A

## QA Brief

* Assert that the new selector has been implemented as per AC
* Check that my tests are testing against the AC correctly
* All other tests and checks should pass

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Livin' on the edge! 😎 

IB ✅

**Comment by johnPhillips** [comment]
QA ✅

- Everything seems implemented correctly as per the AC
- The tests pass
