### ISSUE TITLE
Implement Analytics datastore infrastructure to determine which UI to display (UA vs GA4 vs both)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3170]
Now that we have both an UA Analytics module (`analytics`) and an (internal) GA4 Analytics module (`analytics-4`), we need to cater for a combined setup flow. At this point, the `analytics` module is still the source of truth and required, and the `analytics-4` module solely provides extra functionality purely related to GA4. Eventually, they will be further decoupled though until at some point the `analytics` module can be removed, keeping only the `analytics-4` module (this is likely more than a year away though, and not part of the initial GA4 MVP at all).

For now, the entire setup flow will remain part of the `analytics` module, however it will now have to cater for whether the `analytics-4` module is also there and whether the user has GA4 properties or not.

The end result should be that every user going through the Analytics setup flow now chooses both a UA property and a GA4 property, effectively double tagging to populate data for both of them.

One of the pieces needed is a separated setup UI based on circumstances:
* Either `ua`, if the user only has UA properties in the currently selected account. This is effectively what we have today.
* Or `ga4`, if the user only has GA4 properties in the currently selected account.
* Or `ga4-transitional`, if the user has both UA properties and GA4 properties in the currently selected account.
* Another possible return value needs to be `legacy`, which is for only the case that the GA4 store is not loaded or that the API does not work.

This issue adds the first piece of infrastructure for this, which is a selector to determine the correct "setup flow mode".

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/analytics` datastore should get a new selector `getSetupFlowMode()`:
    * If the `modules/analytics-4` store is not available, it should return “legacy”.
    * If the `modules/analytics-4` store selector `isAdminAPIWorking()` (see #3169) returns `false`, it should return “legacy”. If it returns `undefined`, it should also return `undefined` (indicating "not loaded yet").
    * If there is no account selected, it should return “ua”.
    * If there is an account selected for which the `modules/analytics-4` store selector `getProperties` returns an empty array (i.e. no GA4 properties), it should return “ua”.
    * If there is an account selected for which the `modules/analytics` store selector `getProperties` returns an empty array (i.e. no UA properties), it should return “ga4”.
    * If there is an account selected for which both the `modules/analytics` and `modules/analytics-4` selectors `getProperties` return a non-empty array, it should return “ga4-transitional”.

## Implementation Brief

* Create a new `setup-flow.js` file in the  `assets/js/modules/analytics/datastore` folder that defines and exports the standard partial datastore.
* Add a new selector `getSetupFlowMode()` to the setup flow datastore and implement requirements from the AC section.
* Import the new `setup-flow` datastore in the `assets/js/modules/analytics/datastore/index.js` file and add it to the combine stores list.

### Test Coverage

* Add js tests for the new selector.

### Visual Regression Changes

* N/A

## QA Brief

* Assert that the new selector has been implemented as per AC

* Check that my tests are testing against the AC correctly

* All other tests and checks should pass

* Site Kit uses `undefined` to indicate loading so check extra functionality *not* on AC and IB for returning `undefined` when any dependent data is still being fetched

## Changelog entry

* Add selectors to check which Google Analytics UI should be active.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@danielgent After working on ACs for some of the follow up issues here, I noticed we need to make a small change here (should be trivial): For the cases that GA4 is not loaded or that the GA4 Admin API is not working, the selector should now return a new value "legacy" instead of "ua", since in that case we need to display UI that fully ignores GA4, while "ua" should indicate UI that focuses on "ua" but still supports and has messaging around GA4. Please consider that update when working on a PR.

I've updated this in the ACs. Your IB is still valid as is.

**Comment by Hazlitte** [comment]
**QA Eng ✅**
