### ISSUE TITLE
Implement Analytics datastore infrastructure to control primary property type in GA4-transitional flow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3171]
Related to #3170 (learn more about the different setup flows between UA and GA4 there), if the "ga4-transitional" setup flow mode is active, we will eventually have a single dropdown which lists _all_ Analytics properties (i.e. including both UA and GA4, see also #3167). In addition to that, there will also be a dropdown to choose the respective other one (e.g. if you choose a GA4 property in the overall dropdown, a separate UA property dropdown would appear, and vice-versa).

In order to know which property should be selected in the overall dropdown, we need to know whether to "give precedence" to the current GA4 or UA property. This is only relevant on the client-side, to not alter whether we show the UA property or GA4 property in the dropdown other than what the user originally selected there. From a data perspective, it doesn't matter at all from which point we look at it, and this selection therefore should not be persisted in any way.

In other words, this infrastructure is only relevant when the "ga4-transitional" setup flow mode is used. Otherwise, the user would only have UA properties _or_ GA4 properties anyway, but not both types.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/analytics` datastore should have a new selector `getPrimaryPropertyType()`:
    * It should either return “ua” or “ga4” (eventually based on what type of property is selected in the primary dropdown for the "ga4-transitional" flow), relying on a value stored in state.
    * The initial/default value should be “ua”.
* To modify the result for the above selector, the `modules/analytics` datastore should also have an action `setPrimaryPropertyType( type )`:
    * It should only allow “ua” or “ga4” as possible values for `type`.
    * It should modify the value stored in state.

## Implementation Brief
* Using `assets/js/modules/analytics/datastore/properties.js`,
	* Add a new state variable `primaryPropertyType` having the default value: `ua`
	* Add a new action `setPrimaryPropertyType` which has `type` as parameter. The latter can either be `ua` or `ga4`.
	* The `setPrimaryPropertyType` action should update the state variable to the `type` value.

### Test Coverage
* Add test for the `setPrimaryPropertyType` action.

### Visual Regression Changes
* N/A.

## QA Brief

Check that the code has been implemented as the AC describes

## Changelog entry

* Implement Analytics datastore infrastructure to control primary property type in GA4-transitional flow

**Comment by tofumatt** [comment]
IB ✅

**Comment by danielgent** [comment]
The AC mentions a new `getPrimaryPropertyType` but the IB does not mention it

I'm going to assume that the AC is correct and add this new `getPrimaryPropertyType` with tests

Stop me if that's wrong! :smile:  @tofumatt  @asvinb

**Comment by Hazlitte** [comment]
**QA Eng ✅**

* code implemented as per the AC
* js tests pass
