### ISSUE TITLE
Consolidate JS linting and JS tests workflows into one

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3175]
## Feature Description

In #2969 we overhauled our GitHub actions to be much more selective with when each of them runs to be more efficient with build time. This issue is intended to further enhance that by combining JS linting and tests into a single workflow so that JS tests don't run if there is a linting failure.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The current `js-tests.yml` and `js-css-lint.yml` workflows should be combined into a single workflow
* The JS tests should run only after JS linting has passed successfully
* CSS linting should continue to run first as it runs the fastest
* `paths` should be updated to combine rules from both as needed

## Implementation Brief

* Check PR https://github.com/google/site-kit-wp/pull/3302
* Check that  `js-tests.yml` and `js-css-lint.yml` have been merged together successfully (no paths missing)
* Check that workflow is running

### Test Coverage

* The same number of tests should be run as before.

### Visual Regression Changes

* N/A

## QA Brief

* Check that new job is working correctly on GitHub

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@tofumatt anything you want to add/change here?

**Comment by tofumatt** [comment]
Nothing to add, that looks exactly right 👍🏻

**Comment by tofumatt** [comment]
(Note: I'm leaving this assigned to me for Code Review as I have some feedback for the PR and having reviewed the IB think it makes sense, but we'll get to this in a later sprint or at least after everything in Sprint 49 is complete 🙂 )

**Comment by johnPhillips** [comment]
QA ✅
New job seems to be running well
