### ISSUE TITLE
Don't show notifications until at least a day after first login

### ISSUE THREAD

**Issue by lilybonney** [google/site-kit-wp#318]
## Feature Description

User testing has shown that it can be confusing for a site owner to start receiving notifications in the same session as setup. Delaying notifications until at least a day after the first login is a good strategy to mitigate this.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
We'll open a new issue to revisit publisher wins notifications holistically.
