### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3185]
## Bug Description

There have been reports of the below dashboard error, occurring once the primary Site Kit dashboard is accessed. 

No further insights at present, unreproducible in support without sufficient steps to reproduce. 

```
Cannot read property '0' of null

    in UserDimensionsPieChart
    in div
    in Cell
    in div
    in Row
    in div
    in Grid
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in DashboardAllTrafficWidget
    in WhenAnalyticsActive(DashboardAllTrafficWidget)
    in div
```

Impacted support topics:

- https://wordpress.org/support/topic/error-1517/#post-14335700 | SK 1.30.0 | **Closed - no response**
- https://wordpress.org/support/topic/cannot-read-property-0-of-null-after-upgrade-to/ | SK 1.24.0 | **Closed - no response** 
 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@bethanylang Thoughts on escalating this? No response from both reports in the support forums.

**Comment by bethanylang** [comment]
@jamesozzie I say let's close it for now as we just don't have enough detail to reproduce.
