### ISSUE TITLE
User Input UX/UI improvement for Multiple Select Questions 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3188]
## Bug Description

On the User input screens, when the user is on a multiple select question, i.e. question 3 and 4.  The user selects an answer other than `Other` the screen is grey and inactive, but the `Type your own answer` text stands out still. I am wondering if this could be also greyed out so it looks inactive like the rest of the form. 

![image](https://user-images.githubusercontent.com/73545194/115233052-581fea00-a10f-11eb-906b-d6065903eef2.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In user input questions where an "Other" option exists: When that option is not selected, the text input placeholder should also have the same lighter "disabled" color as the rest of the text for those options.

## Implementation Brief
* Using `assets/js/components/user-input/UserInputSelectOptions.js`,
	* within the `useEffect` hook, set `disabled` to `true` if the following conditions are met (AND): 
		* `max` > 1 (which means we are targetting checkboxes) and
		* `max === values.length`, i.e we've reached the number of max items to be selected and
		* `other` is blank.
* Using `assets/sass/components/user-input/googlesitekit-user-input-controls.scss`,
	* set the `opacity` of disabled input texts to `0.25`

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

Make sure when that the _Other_ option is disabled, its text input looks like this (and not like the screenshot above)
![after](https://user-images.githubusercontent.com/8496063/116135004-d6146000-a6d0-11eb-9ba8-9591c80cef38.png)

## Changelog entry

* Improve User Input "Others" help text when the input field is disabled.

**Comment by danielgent** [comment]
Two things @asvinb :smile: 

1. There's no `useEffect` inside `UserInputSelectOptions`! I think you mean the `useCallback` (I just tried it out and it works if I put your logic in the callback!)

2. Is it better to be more explicit with the CSS classes in the IB?  (Genuine question! I don't know)

I found that by adding `.mdc-text-field--disabled` to this rule 

```
.mdc-checkbox--disabled,
.mdc-checkbox--disabled + label {
  opacity: 0.25;
}
```

It worked! (but that may be too detailed for an IB)

**Comment by asvinb** [comment]
Hey @danielgent 
For the `useEffect`, I meant to use it even though it's not there 😄 . And for the CSS classes, I don't think for this particular case we should be explicit like that. It just about providing the guidelines :)

**Comment by danielgent** [comment]
Thanks @asvinb !  Makes sense. We don't want the IBs too low level :smile: 

IB :white_check_mark:

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Verified that on the multiple selection questions, when the maximum amount of answers is reached (excluding `other`) the `Type your own answer` text is hidden. 

![image](https://user-images.githubusercontent.com/73545194/117010857-26994800-ace5-11eb-954b-7ab0e9d0c45a.png)
