### ISSUE TITLE
Don't show more than one notification per session

### ISSUE THREAD

**Issue by lilybonney** [google/site-kit-wp#319]
## Feature Description

Linked to:
https://github.com/google/site-kit-wp/issues/318

Product Manager to update issue details when ticket is prioritized.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
We'll open a new issue to revisit publisher wins notifications holistically.
