### ISSUE TITLE
Only run GH actions for PRs against specific branches

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3192]
While we restrict our GitHub actions for pushes to only run against `main` and `develop`, we don't do that for pull-requests - they currently trigger the workflows no matter which branch a PR is opened against.

This currently causes quite some overload in our Actions queue, which is largely caused by a separate branch `feature/swg-module` (in which an early exploration for a potential future feature is happening), since the early work is also being reviewed in a PR (against another separate branch `feature/swg-module-reviewed`).

While it can be beneficial to run workflows also for PRs against other branches than `main` and `develop`, we should choose an opt-in approach on a case-by-case basis, rather than running the workflows on any PR, due to the problems this can cause (see above).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All GitHub workflows should only be triggered for pull-requests which are opened against either `main` or `develop`.

## Implementation Brief

* Merge #3193.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* When opening a PR against a random branch other than `develop` and `main`, the GitHub workflows should not run.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv I've already pushed the same changes that are in #3193 to the feature branch in question, to prevent more workflows from spinning up. This effectively serves as QA I'd argue :)

**Comment by aaemnnosttv** [comment]
IB+CR ✅

**Comment by ivankruchkoff** [comment]
QA:Eng ✅

If your branches `feature/swg-module` and `feature/swg-module-reviewed` are constantly getting `develop`/`main` merged into them, then that will solve the issue on those branches too, otherwise make sure to cherrypick this commit into each of those branches @felixarntz
