### ISSUE TITLE
I have google analytics account already setup and I can't connect my analytics to google sitekit

### ISSUE THREAD

**Issue by ShubhamGohar** [google/site-kit-wp#320]
I can't connect my existing analytics account to google sitekit as it tells me to create an account and it didn't fetch my previous analytics account data.

**Comment by jamesozzie** [comment]
@ShubhamGohar This is potentially caused via a caching or security plugin. Can you please try the following and should the issue persist we can troubleshoot further:

1. Disconnect the Analytics module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
2. Temporarily deactivate any caching plugin (Autoptimize, WP Super Cache etc)
3. Open Site Kit in a new incognito window (so Chrome extensions/caching doesn't interfere with the setup process)
4. Connect the Analytics module (Site Kit > Settings > Connect other services > Analytics)

Let me know if the above works. 

#213

**Comment by archon810** [comment]
Same issue here: https://github.com/google/site-kit-wp/issues/324.

**Comment by peeayecreative** [comment]
> @ShubhamGohar This is potentially caused via a caching or security plugin. Can you please try the following and should the issue persist we can troubleshoot further:
> 
> 1. Disconnect the Analytics module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
> 2. Temporarily deactivate any caching plugin (Autoptimize, WP Super Cache etc)
> 3. Open Site Kit in a new incognito window (so Chrome extensions/caching doesn't interfere with the setup process)
> 4. Connect the Analytics module (Site Kit > Settings > Connect other services > Analytics)
> 
> Let me know if the above works.
> 
> #213

Followed these steps and still getting and endless connecting Analytics animations and when I try to re-fetch the account.

**Comment by jamesozzie** [comment]
@ShubhamGohar What other security/caching plugins are you using?

**Comment by jamesozzie** [comment]
@ShubhamGohar I will close this issue now. If the issue persists feel free to reopen and include any console errors.

**Comment by JoryHogeveen** [comment]
Same issue here, tried the same steps.
One note, I manage many analytics accounts for clients all in one profile. Not sure if this might be related.
