### ISSUE TITLE
Allow (programmatically) to do a full reset of Site Kit

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3201]
When resetting Site Kit, most data that the plugin creates (all `googlesitekit_` options and user options) are wiped. However, there is some essential data that cannot easily be restored which therefore does not get wiped on reset (prefixed with `googlesitekitpersistent_`).

We should allow to do a "hard reset" that even wipes those options. This caters for users that truly want to start fresh or that want to get rid of Site Kit data entirely.

Since this is not a generally encouraged usage, for now this should only be allowed programmatically.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new filter applied `googlesitekit_hard_reset_enabled`, which expects a boolean. The default value should be `false`.
* If the filtered value is `true`, anytime a Site Kit reset is triggered, it should also wipe all data that starts in `googlesitekitpersistent_`:
    * options
    * user options
    * post meta (as of #3154)

## Implementation Brief

In `includes/Core/Util/Reset.php`:
 * Create a new `public function maybe_hard_reset()`
   * Return if `apply_filters( 'googlesitekit_hard_reset_enabled', false )` is `false`.
   * Instantiate a new `Reset_Persistent` with `$this->context`
   * Call `$reset_persistent->all()`
 * In the rest route handler, after the call to `$this->all()` add a call to `$this->maybe_hard_reset().`
 * Add the same call to `$this->maybe_hard_reset()` in the `handle_reset_action()` after `$this->all()`.

https://github.com/google/site-kit-wp/blob/develop/includes/Core/Util/Reset.php#L240-L241

### Test Coverage

* Update `tests/phpunit/integration/Core/Util/ResetTest.php`

### Visual Regression Changes

* N/A

## QA Brief

* Test the filter works in both the action `admin_action_googlesitekit_reset` and the reset button of the interface `window.googlesitekit.data.stores["core/site"].actions.fetchReset()`
* Check for the presence / absence of `persistent` meta as appropriate `wp user meta list admin|grep googlesitekitpersistent`
* 
## Changelog entry

* Introduce a new filter that allows for persistent data to be deleted during reset.

**Comment by felixarntz** [comment]
@aaemnnosttv Is this waiting for anything? I don't recall, but I'd be okay with moving this forward to IB as is.

**Comment by eugene-manuilov** [comment]
Thanks, @ivankruchkoff. IB almost looks good. Let's extract the same functionality into a new private method `maybe_hard_reset` instead of repeating the code in two methods.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by fhollis** [comment]
Hi @felixarntz that's been added to Sprint 61, thanks!
cc @eclarke1

**Comment by kuasha420** [comment]
This is a `QA:Eng` right? @eugene-manuilov

**Comment by kuasha420** [comment]
## QA: :warning: 

@eugene-manuilov the `Test Coverage` section suggests adding test for the newly added functionality in the `ResetTest` but I see no test there involving the `hard reset`. 

Other than that, everything seems to be fine. I have verified,

* Adding thee newly introduced filter and returning `true` (added in the `function.php` of the theme) results in all persistent values being cleared upon reset (by UI or console). 
* CLI Outputs:

![Screenshot_20211104_002704](https://user-images.githubusercontent.com/6187401/140170939-4a3bd6e8-b55e-4078-8b93-edbd897f1f74.png)

```
# Striped output
$ 10updocker wp user meta list admin|grep googlesitekitpersistent # before reset
1       wp_googlesitekitpersistent_initial_version      1.44.0

$ 10updocker wp user meta list admin|grep googlesitekitpersistent # after soft reset
1       wp_googlesitekitpersistent_initial_version      1.44.0

$ 10updocker wp user meta list admin|grep googlesitekitpersistent # after hard reset
# nothing shown
```
Assigning back to @eugene-manuilov for the Test Coverage.

**Comment by kuasha420** [comment]
## QA: :heavy_check_mark: 

Thank you for adding the unit tests, @eugene-manuilov. LGTM. Sending to `Approval`.
