### ISSUE TITLE
Display date range for the admin bar data contextually

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3202]
As originally requested in #1190 (among other enhancements), the admin bar is currently lacking any awareness of what date range the data displayed is for. It is always for the last 28 days, but that may be unclear to the user.

We should add the information that the data is for the last 28 days somewhere in here:
![image](https://user-images.githubusercontent.com/469543/75603490-ab565980-5a83-11ea-85e7-9890d6ceaf21.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A small text "over the last x days" should be displayed below the page title in the Site Kit admin bar menu stats, similar to the design below.
* The text should use a placeholder for the number of days, even though for now it always needs to use `28` (since the data in the admin bar is always for the last 28 days). If possible it should re-use a similar already existing translation string.

![image (2)](https://user-images.githubusercontent.com/3531426/117993064-41c31380-b2f4-11eb-81ca-82b4e4fc3b01.png)

## Implementation Brief
* Using the `AdminBarApp` component,
    * Within the `googlesitekit-adminbar__title` container, add a paragraph tag with the following class name: `googlesitekit-adminbar__title--date-range`.
    * Within the paragraph, display the text as per the AC's first bullet point, where `x` is the number of days.
    * To get the number of days, query the user data store via the `getDateRangeNumberOfDays` selector.
    * An example of how the string can be translated:
        ```js
        sprintf(
                /* translators: %s: number of days */
                _n( 'over the last %s day', 'over the last %s days', 28, 'google-site-kit', ),
                28,
            )
        ```

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* Visual changes expected for the `AdminBar` app.

## QA Brief

* Be logged into an installation of WordPress with Site Kit installed
* View any page
* Observe the admin bar has changes as per AC

## Changelog entry

* Display date range for data in the Admin Bar

**Comment by felixarntz** [comment]
@marrrmarrr Any idea on where to add the date range? We could for example:
* Display a suffix "in the last 28 days" after every change percentage (this works well on big screens, but might be a bit much for smaller viewports)
* Display a single subtitle like "Overview for the last 28 days" in a single place, e.g. below the page title

**Comment by eugene-manuilov** [comment]
> Within the paragraph, display the following text: over the last 28 days where 28 is a placeholder variable and the value will always be 28.

@asvinb let's better use the `getDateRangeNumberOfDays` selector instead of hardcoded `28`.

**Comment by asvinb** [comment]
Sounds good. Updated @eugene-manuilov

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

- Verified that the text `over the last x days` is displayed below the page title in the Site Kit admin bar menu stats. The place holder of 28 days appears.  
- Tested the admin bar stats on smaller screen sizes on various mobile devices. 

![image](https://user-images.githubusercontent.com/73545194/122947030-bf595500-d371-11eb-87cd-9950ce643d01.png)
