### ISSUE TITLE
Replace ad-hoc commit linting with commitlint and Conventional Commits

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3216]
## Feature Description

Currently, we use our own format for commit messages and an ad-hoc approach to verify that commit messages satisfy it. Although it works as intended, there some things that we can do better.

If we replace our proprietary format for commit messages with more broadly popular [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), we will make our project more predictable for engineers who want to contribute to the project or are ramping up to the team. Another benefit of using this specification is that it will discipline engineers to write better commit messages and create more granular commits. Finally, this specification is already accompanied by an NPM package that helps to automate the verification of commit messages: [commitlint](https://github.com/conventional-changelog/commitlint).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing for now
