### ISSUE TITLE
Limit effective values for Google proxy base URL

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3217]
## Feature Description

The Google proxy service allows for an alternate base URL to be set using a constant which is necessary to be able to test with a non-production version of the proxy. We should limit this to something more specific rather than allowing any URL. One idea might be restricting it by host name and falling back to the default if the URL does not match `*.withgoogle.com`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GOOGLESITEKIT_PROXY_URL` constant must be validated whether its defined value are within the following list:
    * `https://sitekit.withgoogle.com`
    * `https://site-kit-dev.appspot.com`
* For any other URL, it should ignore the constant value, effectively falling back to the default.
    * While it might seem more intuitive to solve this in a different way and not have a constant for the entire URL at all, we should keep the existing approach so that existing tooling does not need to be updated.

## Implementation Brief

* edit `Google_Proxy.php`
* Rename the `BASE_URL` constant to `PRODUCTION_BASE_URL`
* Add a new constant to the constant list `STAGING_BASE_URL = 'https://site-kit-dev.appspot.com';`
* Update `url` method conditional to additionally check if the `GOOGLESITEKIT_PROXY_URL` is one of the following as well as if it is defined:
    * `PRODUCTION_BASE_URL`
    * `STAGING_BASE_URL`
* Update the conditional to set the url to `self::PRODUCTION_BASE_URL` by default  

### Test Coverage

* Add tests for this change to `Google_Proxytest.php`

### Visual Regression Changes

* N/A

## QA Brief

Define `GOOGLESITEKIT_PROXY_URL` as `https://site-kit-dev.appspot.com`, this will be your URL base for the google permissions when you try and auth.

Define it again as `https://example.com` and confirm that you're at the prod url `https://sitekit.withgoogle.com`

## Changelog entry

* Limit effective values for Google proxy base URL

**Comment by felixarntz** [comment]
@aaemnnosttv Added ACs!

**Comment by tofumatt** [comment]
Rather than keeping `const BASE_URL = 'https://sitekit.withgoogle.com';` in that file around, let's change it to be a more explicit variable name, eg `PRODUCTION_BASE_URL`. Then we can add another `const STAGING_BASE_URL = 'https://site-kit-dev.appspot.com';`, and the `url()` method can check against both those constants rather than burying the strings used to check things down in the url function itself. Plus: it's a bit more self-documenting that way.

**Comment by Hazlitte** [comment]
👍. IB Updated.

**Comment by tofumatt** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
In CR, but the testing for this is somewhat hard as it depends on testing constant values which can't be easily redefined, see
https://github.com/google/site-kit-wp/pull/3495/files#diff-a14a2e665675d8f03868671e7779374b1892e29b38dbb48251dae256aebea520R160

I'm thinking the github actions by default don't have the runkit7 extension so we can't really redefine constants.

Changing processIsolation for independent tests also caused problems so I changed it back. https://github.com/google/site-kit-wp/pull/3495/commits/8c4e572062c7b7d4224c5480257cd856c42810d1#diff-e35810879ec42bdd81797b3ccb72f6de28a8b4a0e3bfdba43183e133e866b892R4 

We can create a second function which `url()` calls and passes `GOOGLESITEKIT_PROXY_URL` as a param and test that function easily, but it wasn't in the IB.

**Comment by eugene-manuilov** [comment]
> In CR, but the testing for this is somewhat hard as it depends on testing constant values which can't be easily redefined, see
> https://github.com/google/site-kit-wp/pull/3495/files#diff-a14a2e665675d8f03868671e7779374b1892e29b38dbb48251dae256aebea520R160
> 
> I'm thinking the github actions by default don't have the runkit7 extension so we can't really redefine constants.
> 
> Changing processIsolation for independent tests also caused problems so I changed it back. [8c4e572#diff-e35810879ec42bdd81797b3ccb72f6de28a8b4a0e3bfdba43183e133e866b892R4](https://github.com/google/site-kit-wp/commit/8c4e572062c7b7d4224c5480257cd856c42810d1#diff-e35810879ec42bdd81797b3ccb72f6de28a8b4a0e3bfdba43183e133e866b892R4)
> 
> We can create a second function which `url()` calls and passes `GOOGLESITEKIT_PROXY_URL` as a param and test that function easily, but it wasn't in the IB.

@ivankruchkoff see my comment here: https://github.com/google/site-kit-wp/pull/3495#discussion_r649874498

**Comment by Hazlitte** [comment]
** QA Eng ✅ **
As per the QA brief I changed the `GOOGLESITEKIT_PROXY_URL` constant using the Google Staging Proxy plugin and the results were as expected.
