### ISSUE TITLE
AdSense snippet not inserted on AMP sites using the legacy reader theme.

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3218]
## Bug Description

Based on [one users experience](https://wordpress.org/support/topic/how-i-can-confirm-google-adsense-is-activated-on-amp-pages/) in the Site Kit support forums AdSense code is not placed on users AMP URLs when using the AMP plugins legacy reader theme. When adding `wp_body_open()` manually to the reader mode templates ([html-start.php](https://github.com/ampproject/amp-wp/blob/develop/templates/html-start.php) specifically) template manually the AdSense code is inserted, although this hook is not part of the legacy theme by default. 

To ensure AdSense code is placed with this reader mode theme the `amp_post_template_body_open()` hook should be used. 

_Note that I had initially [opened a GitHub issue](https://github.com/ampproject/amp-wp/issues/6084) with the AMP plugin in relation to this, since closed as Site Kit should be using the `amp_post_template_body_open()` hook as opposed to `wp_body_open()` for sites using AMP via the reader mode legacy theme. (https://github.com/ampproject/amp-wp/pull/1143)_

[Video demonstrating behaviour
](https://recordit.co/iLwLpYnMRk)
## Steps to reproduce

1. Install and setup Site Kit
2. Allow the plugin to insert AdSense code when connecting the AdSense module
3. Activate AMP using the legacy reader theme. There will be no AdSense code placed.
4. Switch themes while in reader mode, ad code will be placed
 
## Additional Context

 - Unsure how long this has been occurring, only 1 support topic in based on this. The same occurs from testing as far back as SK v1.23.0
 - wp_body_open() was never part of the AMP plugins reader mode theme
 - Reproducible in support

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's AdSense snippet should also show up in the AMP versions of sites which rely on the legacy reader theme (formerly the default experience of "Reader mode").
* In order to do that, Site Kit should rely on the `amp_post_template_body_open` hook in the same way it does for the `wp_body_open` hook (for non-AMP, plus the other AMP cases).
* Since the `amp_post_template_body_open` hook may not be available, there should also be a fallback (similar to how it is for `wp_body_open`), in this case relying on `amp_post_template_footer`.
* The existing comments for the AdSense-related hooks being added should no longer include "AMP Reader". Instead, similar comments should be included for "AMP Reader" above the two new usages.

## Implementation Brief

* In `Google\Site_Kit\Modules\AdSense\AMP_Tag::register`, hook the `render` method into `amp_post_template_body_open` and also into `amp_post_template_footer`. Since the method only prints the snippet if it wasn't printed before, this results in the expected behavior and no double output.
* Add comments above the two new lines:
    * <code>// For AMP Reader (if \`amp_post_template_body_open\` supported).</code> above the respective hook.
    * <code>// For AMP Reader (as fallback).</code> above the fallback hook (`amp_post_template_footer`).
* Remove the `AMP Reader` bit from the two existing comments instead since they actually only apply to the other AMP scenarios mentioned there.

### Test Coverage

* No changes needed

### Visual Regression Changes

* N/A

## QA Brief

* Install and setup Site Kit
* Connect Adsense and allow the plugin to insert AdSense code
* Activate AMP with the legacy reader theme
* Check AdSense tag snippet has been placed on the page

## Changelog entry

* Fix output of AdSense snippet in AMP Reader mode.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- The AdSense tag snippet has been placed on the page when the AMP plugin is activated and legacy reader theme

![image](https://user-images.githubusercontent.com/73545194/121547855-6d750e80-ca04-11eb-8d35-ffdc3177da59.png)
