### ISSUE TITLE
Do not make Google API request if default scopes are missing

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3227]
Currently, if the user for some reason does not complete the OAuth flow after activating a module (e.g. by just returning via the browser's Back button), they (as expected) see an error that they need to grant additional scopes. However, currently Site Kit's behavior is largely unaffected by this, still making Google API requests as usual, which results in a bunch of error API requests that could have been avoided from the start.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If a REST data point which relies on a "service" (i.e. a Google API) is used when the current user has not granted the basic scopes required by the module that the service/API is part of, the request should fail with a permissions error before actually reaching the individual data point logic, **so that no actual request is sent to the Google API** (since that would fail anyway).
* In other words, `Module::validate_data_request` should be enhanced so that, if the REST data point relies on an API service (see `service` argument of the data point) and the module's basic scopes are not yet granted, it throws an appropriate `Insufficient_Scopes_Exception`, similar to how it is already done for specific data points which require additional scopes.
    * The error/exception message used for this scenario should be `Site Kit can’t access the relevant data from %s because you haven’t granted all permissions requested during setup.`, where the placeholder should be the module name.

## Implementation Brief

* Refactor `Module::validate_data_request` to include the following additional logic:
	* Determine if the data point relies on a service (i.e. `$definitions[ $datapoint_key ]['service']` is set)
	* Determine if the module's scopes are granted, for example:
	```php
	$scopes =  $definitions[ $datapoint_key ]['scopes'];
	$oauth_client = $this->authentication->get_oauth_client();
	
	$scopes_granted = $oauth_client->has_sufficient_scopes( $scopes )
	```
	* If the datapoint requires a service and the scopes are not granted, throw an `Insufficient_Scopes_Exception`, with the message `Site Kit can’t access the relevant data from %s because you haven’t granted all permissions requested during setup.`, passing the module name as the placeholder.
* Update the relevant tests to provide coverage for this new logic

### Test Coverage

* New test coverage should be added for the logic above; existing tests should pass.

### Visual Regression Changes

* None anticipated.

## QA Brief

1. Set up Site Kit with just Search Console connected
2. Create a second admin user, and log in to Site Kit as that user in a different browser / incognito window. So now you should be logged in as two separate admin users.
3. Verify that both users see the same Search Console data correctly
4. Now connect Site Kit to Analytics with the first user account.
5. The second user should now see a modal as described in the ACs, because they haven't yet granted the base scopes for Analytics.

## Changelog entry

* Fix a bug where Google API requests would be made when necessary scopes were not granted.

**Comment by asvinb** [comment]
@johnPhillips Can you add a QA brief? Thanks!

**Comment by aaemnnosttv** [comment]
@johnPhillips sending back to Execution for follow-up that we found 👍

**Comment by Hazlitte** [comment]
**QA ✅**
I connected Site Kit to Search Console for both admin users.  When I connected Analytics with the first admin user the message was displayed as expected for the second admin user.
