### ISSUE TITLE
Add upper boundary for how long manual user input responses can be

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3229]
As noted in https://github.com/google/site-kit-wp/issues/3028#issuecomment-817868670, Site Kit should limit how much users can enter in the manual text input fields for the user input flow.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All "Other" input text fields in the user input flow questions should be limited to **100** characters.
* Every search term in the last user input flow question should be limited to **40** characters.

## Implementation Brief

Using `assets/js/components/user-input/UserInputSelectOptions.js`
* Add an attribute `maxLength` with a value of 100 to the "Other" `<Input />`

Using `assets/js/components/user-input/UserInputKeywords.js`
* Add an attribute `maxLength` with a value of 40 to the keyword `<Input />`

### Test Coverage

* No changes to existing tests
* As `maxlength` this is native browser functionality it does not need testing

### Visual Regression Changes

* N/A

## QA Brief

Go to the UserInput component on Storybook 
* this - PR https://google.github.io/site-kit-wp/storybook/pull/3368/?path=/story/user-input--userinputapp
* main - https://google.github.io/site-kit-wp/storybook/main/?path=/story/user-input--userinputapp

There are "Other" inputs on the first four questions
* Try and enter more than 100 characters into an "Other" input field
* Observe no more than 100 characters can be entered

Then on the last question
* Try creating tags longer than 40 characters
* Observe this cannot be done

_To test this in WordPress ensure the feature flag `userInput` is enabled_

## Changelog entry

* Add upper boundary for how long manual user input responses can be

**Comment by felixarntz** [comment]
@marrrmarrr What do you think we should have as limits here? I went with two different limits overall, one for free text for the "Other" choices, and another (probably lower) limit on the search term length. Assigning to you to define these.

**Comment by danielgent** [comment]
For the  _"Other"_ input text fields we can just use the `maxlength` attribute. I tested this out and it works with `@material/react-text-field`

`maxlength` is fully supported across browsers
![can-i-use](https://user-images.githubusercontent.com/8496063/118300650-798fae00-b4e2-11eb-941f-53cfc017b950.png)

See an example: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength#examples

There are lots of issues with native number inputs in browsers (I've had to recreate functionality in React a few times) but IIRC the text input is reliable and we can use these attributes

**Comment by danielgent** [comment]
The tag input `UserInputSelectOptions` also uses the same `@material/react-text-field` so we can use the same `maxlength` attribute

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

Within storybook and a jurassic.ninja test site the following was verified: for userinput

- No more than 100 characters could be entered into an "Other" input field.
- I tried to type in more than 100 characters and it would not allowed me. I also copied and pasted a paragraph of text over 100 characters and it cut it off at the limit.

- For tags, no more than 40 characters could be entered. 
- I tried to type in more than 40 characters and it would not allowed me. I also copied and pasted a paragraph of text over 100 characters and it cut it off at the limit. 

In addition, I ran through these tests in Chrome, Safari, Edge and Firefox. Plus Android and iOS mobile device.
