### ISSUE TITLE
Analytics Site Stats chart shows zero values for current 90 day range in widget-based module dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3232]
## Bug Description

The Site Stats chart on the widget-based Analytics module screen does not show properly for the 90 day date range. 

## Steps to reproduce

1. Set up Site Kit with Analytics
2. Enable `widgets.moduleScreens` feature
3. Navigate to Analytics module screen
4. Switch to 90 day date range
5. See current values are all zero

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/116263174-d4ef3b80-a781-11eb-8d8c-4f6f81b2758c.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Stats displayed on the Analytics module dashboard should be consistent between widget-based and non-widget-based layouts for all available date ranges 

## Implementation Brief

* Update the default value for the `row_limit` property to be an empty string (`""`) in the `Analytics::create_analytics_site_data_request` method: https://github.com/google/site-kit-wp/blob/46e0d0803e2fec749a9938e9bca171f3fab09ceb/includes/Modules/Analytics.php#L896

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Enable the `widgets.moduleScreens` feature flag in the tester plugin.
* Set up and connect the Analytics module.
* Go to the Analytics module page and make sure that the new widget-based audience overview shows correct charts for all date ranges.

## Changelog entry

* Fix a bug where Analytics report data was incomplete for the 90-day date range when also requesting data for the previous period affecting the widget-based module dashboard.

**Comment by felixarntz** [comment]
@eclarke1 This error only appears on the Site Kit module pages, not on the dashboard, so it's not critical (since we didn't open up the module pages yet). Removing this from the epic.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I believe your suggested change will fix it in this case, but given that the underlying problem is in the Analytics class, what do you think about changing this line? https://github.com/google/site-kit-wp/blob/46e0d0803e2fec749a9938e9bca171f3fab09ceb/includes/Modules/Analytics.php#L896

The API has a default limit of 1000 rows per page which would be more than enough for our use so far. If we removed our limit here, we wouldn't need to pass the limit in most of our requests on the client (if not all). Our use of `limit` in other places (like GA4) has been to increase the number of rows returned above the default rather than restrict it. cc: @felixarntz

**Comment by eugene-manuilov** [comment]
> I believe your suggested change will fix it in this case, but given that the underlying problem is in the Analytics class, what do you think about changing this line?
> 
> https://github.com/google/site-kit-wp/blob/46e0d0803e2fec749a9938e9bca171f3fab09ceb/includes/Modules/Analytics.php#L896
> 
> The API has a default limit of 1000 rows per page which would be more than enough for our use so far. If we removed our limit here, we wouldn't need to pass the limit in most of our requests on the client (if not all). Our use of `limit` in other places (like GA4) has been to increase the number of rows returned above the default rather than restrict it.

Yes, it is also a possible solution for this issue, but it will have a broader effect on the codebase than adding the `limit` argument to one report args. Not sure if it is bad or good...

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I think it's better to fix the underlying issue here to prevent this from popping up again later. 100 seems like a bit of an arbitrary limit. The 90 day range is the only one that would be affected by this as all the other ranges are well under it, even with `compare: true`.

Thoughts @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov I think removing the arbitrary limit in the `Analytics` class makes sense. I also agree it probably doesn't make sense to pass `limit` unless we want to increase it beyond the default (which probably won't ever be necessary unless we want more than `last-500-days` :)

**Comment by eugene-manuilov** [comment]
Ok, sounds good to me. IB is updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Was able to recreate the issue on the latest release. 
- On develop branch, the data is appearing in the chart for 7, 14, 28 and 90 days. when the `widgets.moduleScreens` feature flag in the tester plugin.
- Made sure that the data appeared in the legacy widget for 7, 14, 28 and 90 days. when the `widgets.moduleScreens` feature flag was disabled in the tester plugin.

https://user-images.githubusercontent.com/73545194/117669735-22ff3880-b19f-11eb-8cbb-7403f6390075.mp4
