### ISSUE TITLE
Fix PHP method to permute site URLs so that it also considers any path present in the site URL

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3233]
As noticed in https://github.com/google/site-kit-wp/pull/3176/files#r621493850, the existing implementation of the `Module::permute_site_url` method is incorrect. This is not really critical, since it is only used in 3 places where either this bug doesn't affect the usage (because it's only to get hostnames anyway) or the surface area is tiny (the only place this really causes a problem is the non-proxy setup flow, which almost nobody uses).

Yet, this is wrong and therefore needs to be fixed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Module::permute_site_url` should have its behavior fixed to not only look at the hostname, but also any potentially existing path segment in the given URL:
    * The path should always have its trailing slash removed (i.e. if the path is `/`, it should still have "no path" in the returned URLs).
    * Examples:
        * `https://example.com/blog/` should result in `https://example.com/blog`, `https://www.example.com/blog`, `http://example.com/blog`, and `http://www.example.com/blog`
        * `http://www.example.com/` should result in `https://example.com`, `https://www.example.com`, `http://example.com`, and `http://www.example.com`
* Tests should be added to verify the new behaviour.

## Implementation Brief

* edit the `permute_site_url` method in the `Core/Modules/Module` class
* instead of passing a second parameter to `wp_parse_url` just pass the `$site_url` to return an array of the url's components
* create a new variable ( eg. `$host_and_path` ) that returns a string of the host and path with any trailing slashes removed:
    `untrailingslashit( $parsed_url['host'] . $parsed_url['path'] )`
* replace the `$host` variable in the rest of the method with the new `$host_and_path` one

### Test Coverage

* add tests to `integration/Core/Modules/ModuleTest.php` to cover the functionality of `permute_site_url`

### Visual Regression Changes

* N/A

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
This was already fixed in https://github.com/google/site-kit-wp/commit/e4b9ab4cd78034b6818802cdd769daed5ca80156. I didn't realize there was already an issue for it, and looks like @felixarntz did too 😄  https://github.com/google/site-kit-wp/pull/3671#discussion_r668142468.

Closing this one as fixed 👍
