### ISSUE TITLE
 Google Analytics  Erreur : The response is not a valid JSON response.

### ISSUE THREAD

**Issue by iheblhbib** [google/site-kit-wp#3234]
When i launch Google Analytics , i get this error "Erreur : The response is not a valid JSON response." , i don't know why !!

react_devtools_backend.js:2557 Google Site Kit API Error method:POST datapoint:create-account-ticket type:modules identifier:analytics error:"The response is not a valid JSON response."

**Comment by jamesozzie** [comment]
Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. Should we determine a bug or action to be address on the plugin side we can reopen this GitHub issue. 

In many cases such notices are as a result of plugin conflicts, so feel free to include your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.
