### ISSUE TITLE
Analytics: Refetch my account not working

### ISSUE THREAD

**Issue by Serkan69** [google/site-kit-wp#324]
I have read all other same issues and set up the site kit as shown and 100% correct, but somehow all will connect besides Google Analytics eventhough I have an account...

If I click on refetch my account data...it will try to connect forever but wont load at all :(
Eventhough when trying to create a new account, it wont load that neither.

I have also disabled Autoptimize and WP Super Cache and do not use any security plug in.

How can I fix this?

PS: I am using atm MonsterInsight, which just works fine.

Thanks for all help!

As mentioned from @madbradj below:

> I have several sites on my own server. I have managed to configure 4 sites with Search Console, Analytics and Page Speed. No problems.
> 
> But the 5th site, which is more complex does not allow me to configure Analytics. This is the initial error from console when I am on the refetch my account screen: wp-json/google-site-kit/v1/modules/analytics/data/get-accounts?_locale=user 500 (Internal Server Error)
> _ @ api-fetch.min.js?ver=3.1.2:1

Additional context: See @IanJSaul #234 below:

> I have repeated the steps above, disabled every plugin on the site, and switched it to one of the default WP themes while troubleshooting, and have had no luck getting it to fetch my Analytics.
> 
> I've reset the Site Kit plugin, bypassed all caching options, specifically CloudFlare, and wipe all caches before testing.
> 
> Tried two browsers with no plugins enabled on them, cleared all browser caches, etc.
> 
> I notice from browsing a few other threads that this may be related to either Cloudways or DigitalOcean.
> 
> I managed to add multiple other nearly identical (we run a standardized security and plugin suite on all sites), however, on this 4th-5th one, I'm running into this issue, so it doesn't make perfect sense for it to be tied to the servers.

{"accounts":[{"created":"2014-09-06T17:53:33.397Z","id":"54516992","kind":"analytics#account","name":"Demo Account","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/54516992","starred":null,"updated":"2019-06-10T17:56:03.215Z","permissions":{"effective":["READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/54516992/webproperties","type":"analytics#webproperties"}},{"created":"2015-05-19T15:16:46.171Z","id":"63132339","kind":"analytics#account","name":"DBO","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/63132339","starred":null,"updated":"2019-06-03T14:53:42.792Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/63132339/webproperties","type":"analytics#webproperties"}},{"created":"2015-08-27T00:23:22.902Z","id":"66843629","kind":"analytics#account","name":"DEC","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/66843629","starred":null,"updated":"2019-02-12T00:07:22.694Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/66843629/webproperties","type":"analytics#webproperties"}},{"created":"2018-02-21T16:00:38.054Z","id":"114524566","kind":"analytics#account","name":"GLO","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/114524566","starred":null,"updated":"2019-02-12T00:07:43.046Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/114524566/webproperties","type":"analytics#webproperties"}},{"created":"2018-08-30T22:14:16.647Z","id":"125004248","kind":"analytics#account","name":"DAC","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/125004248","starred":null,"updated":"2019-02-12T00:06:12.477Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/125004248/webproperties","type":"analytics#webproperties"}},{"created":"2018-11-30T01:10:36.707Z","id":"130186507","kind":"analytics#account","name":"KDM","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/130186507","starred":null,"updated":"2019-02-12T00:08:22.553Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/130186507/webproperties","type":"analytics#webproperties"}},{"created":"2019-01-18T22:24:16.638Z","id":"132742205","kind":"analytics#account","name":"HRE","selfLink":"https://www.googleapis.com/analytics/v3/management/accounts/132742205","starred":null,"updated":"2019-02-12T00:07:57.215Z","permissions":{"effective":["COLLABORATE","EDIT","MANAGE_USERS","READ_AND_ANALYZE"]},"childLink":{"href":"https://www.googleapis.com/analytics/v3/management/accounts/132742205/webproperties","type":"analytics#webproperties"}}],"properties":[],"profiles":[]}

**Comment by jamesozzie** [comment]
@Serkan69 Can you try the following and see if you are able to get Analytics working:
1. Disconnect the Analytics module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit).
2. Deactivate Monster Insights 
3. Connect the Analytics module in Site Kit? 

Once Analytics is setup from within Site Kit then you can enable the Monster Insights plugin again. If the steps above fail to resolve the issue can you please inform me of the following:
- Any additional plugins you have active
- Console error messages you see in the Analytics dashboard from within Site Kit

**Comment by dmorizz** [comment]
Doesn't work for me either. This is my 3rd time (different dates) of trying to connect with WP site.

All cache plugins are deactivated. Done in an incognito window. Keep on going trying to connect but never connecting. I am also logged into my analytics account and is open in another tab.

I'll deactivate plugin again until there is a solution.

**Comment by archon810** [comment]
I was unable to activate either today on our dev site. The property selector only sees one of the properties and only shows that one property in the dropdown and not all the other properties that I need.

Using the latest beta as of today. 1.0.2.

**Comment by blairworks** [comment]
I'm having the same problem as well in connecting to my existing Google Analytics profile. My Breeze cache plugin and my other Google analytics plugin were both disabled. This was also attempted in an incognito window. 

I was able to connect to an existing Search Console profile OK.

**Comment by Serkan69** [comment]
> @Serkan69 Can you try the following and see if you are able to get Analytics working:
> 
> 1. Disconnect the Analytics module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit).
> 2. Deactivate Monster Insights
> 3. Connect the Analytics module in Site Kit?
> 
> Once Analytics is setup from within Site Kit then you can enable the Monster Insights plugin again. If the steps above fail to resolve the issue can you please inform me of the following:
> 
> * Any additional plugins you have active
> * Console error messages you see in the Analytics dashboard from within Site Kit

I have tired it again, but wont work :(

I am using following plug ins:
Astra Pro
Astra Widgets
DSGVO All in one for WP
Elementor
Elementor Addon Elements
Elementor Pro
Germanized für WooCommerce
Google Captcha (reCAPTCHA) by BestWebSoft
Insert Headers and Footers
Loco Translate
Mailchimp for WordPress
PayPal PLUS für WooCommerce
Reading Progress Bar
Redirection
SVG Support
WooCommerce
WooCommerce Amazon Pay Gateway
WooCommerce Cart
WooCommerce PayPal Checkout Gateway
WooCommerce Stripe-Gateway
WPS Hide Login
WPS Limit Login
WPvivid Backup Plugin

Since it is a live-website, I do not want to disable all of them :(
I have alrdy tried to disable those two also:
WPS Hide Login
WPS Limit Login
But would not work.

Maybe you could tell me, what plug in causes the issue here.

Thanks a lot!

**Comment by jamesozzie** [comment]
@Serkan69 Can you try to deactivate the following (after disconnecting the Analytics module) and see if you have any success?
- Insert Headers and Footers
- DSGVO

Please share any console errors you encounter here.

**Comment by peeayecreative** [comment]
> I'm having the same problem as well in connecting to my existing Google Analytics profile. My Breeze cache plugin and my other Google analytics plugin were both disabled. This was also attempted in an incognito window.
> 
> I was able to connect to an existing Search Console profile OK.

Exact same setup/issue here.

**Comment by Serkan69** [comment]
> @Serkan69 Can you try to deactivate the following (after disconnecting the Analytics module) and see if you have any success?
> 
> * Insert Headers and Footers
> * DSGVO
> 
> Please share any console errors you encounter here.

@jamesozzie it is unfortuantely not working :(

Analytics
Looks like you don't have Analytics account yet. Once you create it click "Re-fetch my account" and Site Kit will locate it.

When I click on Re-Fetch it will just load the progress bar, but do nothing :(

**Comment by jamesozzie** [comment]
@Serkan69 Have you tried using an incognito window? If not please attempt the same steps again (disabling Monster Insights first) and then re-connecting the Analytics module. 

If that fails please share any [console errors](https://i.imgur.com/f5WfLb3.png) you see on the same screen where you don't see your analytics account.

**Comment by Serkan69** [comment]
@jamesozzie 
yes, like i said, i have set it up correctly and also tried as people mentioned before the incognito mode with google chrome, but it didnt work either :(

Also I do not get any errors, it is tryting to connect, and re-fetch my analytics account, for ever....while nothing is happening.

**Comment by jamesozzie** [comment]
@Serkan69 Thanks for checking. You have a large number of plugins, any of which could be conflicting. It would be great to try and rule some of them out if you were to setup a staging site. If you have the capacity you could also check the following:
- Firewall / security software setup on your host
- Desktop applications with networking / web features
- Check using an alternate theme 

Do you have any other site you can check the setup from?

**Comment by Serkan69** [comment]
@jamesozzie 
Sooo I have just checked the google site kit on a different site, same webhoster, same computer, same security, same brwoser. Just with different plug ins.

So it has to do anything with any of my plug ins it seems....but which one could it be?

**Comment by jamesozzie** [comment]
@Serkan69 Nice troubleshooting, it would be great to find out which one. I know you've tested a couple already, maybe we try more by process of elimination? I'm not familiar with all those plugins, but I can check some also

**Comment by Serkan69** [comment]
@jamesozzie 
yeah, thank you very much!
I will try to check some of them by tomorrw:
It is definately not:
Astra Pro
Elementor
Elementor Pro
WPvivid Backup Plugin
DSGVO All in one for WP
Insert Headers and Footers
WPS Hide Login
WPS Limit Login

the rest ill disable one by one...and see then :)

**Comment by blairworks** [comment]
So, I have a site that is not yet public and so I gradually disabled all my plugins one by one. Still the same problem -- even after disabling all plugins and then reactivating Site Kit. Then, I changed my theme from Elementor's Hello Theme to the default TwentyNineteen theme and still have the problem. 

All of this was done from within an Incognito window and I made sure the Varnish cache was turned off. 

No errors in the Chrome console either on the initial connection attempt or the endless "refetch" after failure.

wordpress: 	5.2.2
php version: 	7.3.6-1+0~20190531112546.39+jessie~1.gbp6131b7 (Supports 64bit values)

**Comment by jamesozzie** [comment]
@blairworks Thanks for the info. Do you have any potential conflicting software either install on your local computer or security/firewall programs active on your web host?

**Comment by blairworks** [comment]
@jamesozzie Not that I know of. This site is using a DigitalOcean instance using a management interface by Cloudways. I've never run into any previous firewall-related issues over there and so I'm thinking it is fairly permissive. Also, please note I had no trouble connecting to my Search Console profile -- that seemed to work just fine.

I looked through the logs that I have access to for PHP, Nginx, and Apache and did not see anything that jumped out of me. These both got 200 responses (sanitized from the Apache access log):

- "GET /wp-json/google-site-kit/v1/modules/analytics/data/get-accounts?_locale=user HTTP/1.0" 200 17715 "https://example.com/wp-admin/admin.php?page=googlesitekit-module-analytics&reAuth=true&slug=analytics" 
- "GET /?tagverify=1&timestamp=1564448154344 HTTP/1.0" 200 10723 "https://example.com/wp-admin/admin.php?page=googlesitekit-module-analytics&reAuth=true&slug=analytics" 

Is there any kind of logging of the interaction in Site Kit itself I can turn on?

**Comment by madbradj** [comment]
I have several sites on my own server. I have managed to configure 4 sites with Search Console, Analytics and Page Speed. No problems. 

But the 5th site, which is more complex does not allow me to configure Analytics.  This is the initial error from console when I am on the refetch my account screen: wp-json/google-site-kit/v1/modules/analytics/data/get-accounts?_locale=user 500 (Internal Server Error)
_ @ api-fetch.min.js?ver=3.1.2:1

So analytics is stuck on the continuous connecting bar.

**Comment by IanJSaul** [comment]
Having the same issue, and am hosting on DO via Cloudways.

**Comment by archon810** [comment]
In my case, downgrading to 1.0.1 fixed the issue and I was able to select the right property in the list. 1.0.2 does not find the didn't property and only lists a single site that isn't the right one, even though the JSON contains all the sites.

I'll probably start a new ticket for this issue.

**Comment by Serkan69** [comment]
how can i download, downgrade to 1.0.1???
maybe that would work for me :)

**Comment by jamesozzie** [comment]
@Serkan69 I wouldn't suggest downgrading versions, the current Site Kit version remains a developer release with improvements on the previous version. You issue seems to be plugin related based on your previous tests. Did you get a chance to check the plugins you mentioned?

**Comment by scottwyden** [comment]
I have the same issue with api-fetch.min.js giving a 500 error. I have different plugins, have tried without plugins active and run on WP Engine. No luck getting past it.  I have another site also on the same WPE server and it connected fine.

**Comment by quindo** [comment]
Can Confirm WP Super Cache was causing this issue for me.  Disabling Caching (Not the plugin) fixed it.

**Comment by jamesozzie** [comment]
#375

**Comment by Serkan69** [comment]
Sooo a final update for all:
Finally I have made it!!!
It was one of the WooCommerce plug ins:
Germanized für WooCommerce
PayPal PLUS für WooCommerce
WooCommerce
WooCommerce Amazon Pay Gateway
WooCommerce Cart
WooCommerce PayPal Checkout Gateway
WooCommerce Stripe-Gateway

I cant say clearly which one, because after disabling all of them, it finally works!
Then you can easily just turn on all plug ins back again :)

Thanks!

Hope those things will be fixed for the final version.

**Comment by jamesozzie** [comment]
@Serkan69 That's useful to know, thanks for the input. I will check them out myself for further investigation

**Comment by jacksparrow9573** [comment]
I have the same issue, I tried all of this method but its doesn't [work](https://www.kobitaokahini.com/category/quote) yet

**Comment by jamesozzie** [comment]
@jacksparrow9573 If you want to create a new support topic on the [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit/) we can assist from there. We have moved Site Kit support over to that platform.
