### ISSUE TITLE
Update UA and GA4 dropdowns behavior to only show once parent is specified

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3243]
Currently, the Analytics dropdowns for account, property and profile/view always display, with the latter two being disabled until the respective parent entity has been specified. In relation to the upcoming GA4 setup flow, this should be modified so that the user only sees the dropdowns once they actually allow a selection to be made. This should be changed for the existing infrastructure though too, i.e. it will affect Site Kit production behavior already today.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics (UA) `PropertySelect` component and the Analytics 4 (GA4) `PropertySelect` component should be adjusted so that they return `null` as long as no valid account ID has been specified yet (i.e. based on `! isValidAccountID`).
    * They should otherwise maintain their loading state as is, returning `null` should only happen as long as no account ID is specified yet.
* The Analytics (UA) `ProfileSelect` component should be adjusted so that it returns `null` as long as no valid account ID or no valid (UA) property ID has been specified yet (i.e. based on `! isValidAccountID` and `! isValidPropertyID`).
* As usual, it must be ensured that the Storybook coverage for these components still works as expected, with any potentially now irrelevant stories for them (e.g. disabled state that now is no longer possible) being removed.

## Implementation Brief

For the three dropdowns:
* Analytics (UA) `PropertySelect`
* Analytics 4 (GA4) `PropertySelect` 
* Analytics (UA) `ProfileSelect`

Return null if there is no account ID

And also for the Analytics (UA) `ProfileSelect`

Return null is there is no property ID

#### Storybook changes

The Analytics section has two stories:  `Account Property Profile Select (none selected)` and `Account Property Profile Select (all selected)`
* Remove `"all selected"` story
* Prefill redux with data for every account in the existing accounts fixture: _(By dispatching `properties` and `profiles` for each account id)_
* The story should be interactive

### Test Coverage

No existing tests currently fail because of the above change

Add extra tests for the three dropdowns to assert that null is returned when
* no accountID for all three
* no propertyID for the Profile Select

### Visual Regression Changes

Checked and there should be no visual regression changes with above changes

## QA Brief

The UA `PropertySelect` and the `ProfileSelect` changes can easily be seen on storybook
https://google.github.io/site-kit-wp/storybook/pull/3330/?path=/story/analytics-module--account-property-profile-select

Here you can observe the changes are made as per the AC

Also they can be seen in WordPress but as we have a few flows, to get an empty account I had to select to create an account, then go back (as IIRC the account is being prefilled)

## Changelog entry

* Only show Google Analytics property and profile selection if the parent (account/property) is valid.

**Comment by eugene-manuilov** [comment]
@danielgent we also need to mention storybook changes requested in the AC. Could you please update the IB?

**Comment by danielgent** [comment]
Sure thing @eugene-manuilov !  Apologies, I forgot that Backstop uses only the Storybook stories that we configure :smile: 

I'll manually check storybook now

**Comment by danielgent** [comment]
Hey @eugene-manuilov .

I was thinking there would be more instances of this in StoryBook (I thought it would show all the difference states just for the `PropertySelect`

But actually these are not used in many places on storybook

There is a new GA4 section that just shows the GA4 PropertySelect (no change here)

But then the Analytics section has `Account Property Profile Select (none selected)` and `Account Property Profile Select (all selected)`

The latter isn't changed but the former now just shows one select (as expected!)

![now-shows-disabled-state](https://user-images.githubusercontent.com/8496063/117042350-2496af80-ad0c-11eb-8b8c-28bd58282768.png)
![now-only-shows-one](https://user-images.githubusercontent.com/8496063/117042351-252f4600-ad0c-11eb-858e-1323a82d5b0f.png)

Ideally what I'd want is this to be fully interactive so it can be seen working, but what do you think? It's kind of fine how it is (or at least no more broken than it currently is as interacting with the selects leads to exceptions)
![exception](https://user-images.githubusercontent.com/8496063/117042466-50199a00-ad0c-11eb-9482-59d74468fc4e.png)

**Comment by eugene-manuilov** [comment]
> Ideally what I'd want is this to be fully interactive so it can be seen working, but what do you think? It's kind of fine how it is, or at least no more broken than it currently is, as interacting with the selects leads to exceptions!

@danielgent yes, it would be awesome if we can make it fully interactive. It will require a bit of work to properly configure datastores though. In this case, we will be able to merge two stories (`none selected` and `all selected`) into one and maybe even convert it to storybook 6 :thinking: 

Could you please update IB to mention changes required to update those stories?

**Comment by danielgent** [comment]
@eugene-manuilov I've run out of time this week, but I can keep on this ticket next week :+1: 

I read up for a bit and I'm clearer now on Storybook 6 and Component Story Format.  I haven't used it for a few years and there have been big changes recently (with all the add-ons I used to use being deprecated :smile: )

I'm not sure what we do in Storybook though for components that do network requests.  I'll look through all the stories on Monday though and see if I can find an example :+1:

**Comment by eugene-manuilov** [comment]
@danielgent we just pre-set values that are going to be received via network using `receive*` actions. For instance, you can see it here: https://github.com/google/site-kit-wp/blob/8c341d37f0ba40d83ce5a8a067ac223f42c4f9d8/stories/module-analytics-settings.stories.js#L95-L111

**Comment by danielgent** [comment]
@eugene-manuilov Thanks. That's really easy actually. No depdency injection of API classes or anything like that :smile: 

I've just had a play around then locally and I got something working.

**Comment by eugene-manuilov** [comment]
@wpdarren I found one issue with the profile select dropdown. I'll create a follow-up PR to fix it.

**Comment by wpdarren** [comment]
### QA Update: 

Tested this on [Storyboard here](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module--account-property-profile-select) 

**Verified:**

- The Analytics (UA) PropertySelect component and the Analytics 4 (GA4) PropertySelect component is null by default.  -- [Screenshot](https://user-images.githubusercontent.com/73545194/119996794-fc2a6a00-bfc6-11eb-890e-3c462e0a90e9.png)
- The Analytics (UA) ProfileSelect component is null.  - [Screenshot](https://user-images.githubusercontent.com/73545194/119996817-00ef1e00-bfc7-11eb-909b-2312cd0c8730.png)
