### ISSUE TITLE
Implement Analytics setup form UI for accounts that only have UA properties

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3248]
The UI for the scenario that an Analytics account has only UA properties available (yet with GA4 support) should be implemented.

For details on this UI, see:
* [design doc section](https://docs.google.com/document/d/11DMYyAGhtFHO8bMH107pacC8iMpD9PJ9BTaR6IF_B5E/edit#heading=h.6t1gq9q9bzg3)
* [Figma design](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A9057)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The UI from the [Figma design](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A9057) should be implemented in the `SetupFormUA` component that was scaffolded in #3247.
    * One exception: For the blue notification, rely on our existing `SettingsNotice` component for the look for now, to keep this simple. The notification design will be updated to the one specified in the Figma file in a follow-up issue.
* Technically, the UI implementation should largely follow what is in `SetupFormLegacy`:
    * A `StoreErrorNotices` for the `modules/analytics` store should be on top, followed conditionally by `ExistingTagNotice` and `ExistingGTMPropertyNotice`.
    * The main dropdowns should be rendered in a `.googlesitekit-setup-module__inputs` container, followed by another `.googlesitekit-setup-module__inputs` container for the `ProfileNameTextField`, if creating a new profile/view.
* Another technical requirement to specifically point out is that this component should automatically set the `modules/analytics-4` store's property ID setting to `PROPERTY_CREATE`: Since this scenario is for when the account has no GA4 properties, the user doesn't need to select anything, instead it is clear that a new GA4 property needs to be created.
* Basic Storybook coverage for rendering `SetupForm` with this UI state (i.e. so that `SetupFormUA` is shown) should be implemented.

## Implementation Brief
* Using `SetupFormUA`,
	* Copy the code from `SetupFormLegacy` with changes as per the second bullet point in the AC.
	* Drop downs should be implemented as per the AC.
	* Upon component mount, use the `selectProperty` action of the `analytics-4` data store to set the property ID to `PROPERTY_CREATE` as per the third bullet point in the AC.
* Update stories for `SetupForm` so that `SetupFormUA` can be displayed.

### Test Coverage
* No additional tests needed.
* Existing tests should pass.

### Visual Regression Changes
* N/A

## QA Brief
* Run storybook locally via the following command: `npm run storybook`
* Visit the Analytics -> Setup -> SetupFormUA story.
* Use `Redux DevTools` to check if the `SET_PROPERTY_ID` action has been dispatched upon page load, with `property_create` as value.
* Choose a property from the Property dropdown. After selecting a property, a blue notice as per the designs should appear before the "Configure Analytics" button.

### Extra criteria for follow-up QA

* The submit button for the above scenario should be active and not disabled.
* The double spacing above the notice (visible in e.g. the screenshot in https://github.com/google/site-kit-wp/issues/3248#issuecomment-850487876) should be reduced to have more appropriate spacing, effectively similar to the spacing above the dropdowns.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
> Use the selectProperty selector of the analytics-4 data store to set the property ID to PROPERTY_CREATE as per the third bullet point in the AC.

@asvinb the `selectProperty` is an action, not a selector. Plus, could you please provide more details on when exactly we need to set ga4 property ID to `PROPERTY_CREATE`? On render? On mount? On select a new value?

**Comment by eugene-manuilov** [comment]
Also, I think this ticket is more 7 than 11. I'll update the estimate down.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by asvinb** [comment]
@aaemnnosttv Can you check out my comment here: https://github.com/google/site-kit-wp/pull/3351#issuecomment-840628498
Thanks!

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- The SET_PROPERTY_ID action is dispatched upon page load, with `property_create` as value.
- After selecting a property, a blue notice as per the designs appears before the "Configure Analytics" button.

![image](https://user-images.githubusercontent.com/73545194/120005092-66dfa380-bfcf-11eb-9683-c16a56f10473.png)

**Comment by felixarntz** [comment]
### Approval ⚠️ 

@eugene-manuilov I'm not sure this is entirely related, but I cannot submit the form in this scenario since the button is disabled (also visible in Storybook, see @wpdarren's screenshot above). I just want to make sure there is another piece missing and this is expected currently?

**Comment by eugene-manuilov** [comment]
@felixarntz, unfortunately, I can't reproduce your issue with the disabled submit button, but I have found a few more issues and created a follow-up PR that fixes them:

1. whitespace between dropdowns and the GA4 property notice 
1. insufficient scopes issue when creating a new GA4 property
1. missing timezone field for the new GA4 property

Do you mind reviewing it?

**Comment by felixarntz** [comment]
@eugene-manuilov Reviewed it - the PR mostly lgtm, but the above problem is also happening in Storybook, so there it is definitely reproducible.

**Comment by eugene-manuilov** [comment]
@felixarntz I have created a new PR #3483 that uses the `main` branch as base. It contains all changes that #3479 has plus a fix for the issue with the submit button.

**Comment by cole10up** [comment]
### **Approval ⚠️**

Retested the above and noticed the following when a smaller browser window/mobile is used, long property names move the drop down out of the frame.
![image](https://user-images.githubusercontent.com/57115907/120943526-3a6d0b00-c6e4-11eb-81df-685eb64da9f4.png)

@felixarntz @eugene-manuilov should we spin up a bug for this or take this ticket back in?

**Comment by eugene-manuilov** [comment]
@cole10up this is a UI issue that is not relevant to the GA4 functionality. Let's create a new ticket for it and mark this ticket as passed QA if you have nothing else than this.

**Comment by cole10up** [comment]
@eugene-manuilov done. The new ticket for this issue is here: https://github.com/google/site-kit-wp/issues/3497

Sending to approval
