### ISSUE TITLE
Implement Analytics setup form UI for accounts that only have GA4 properties

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3249]
The UI for the scenario that an Analytics account has only GA4 properties available should be implemented.

For details on this UI, see:
* [design doc section](https://docs.google.com/document/d/11DMYyAGhtFHO8bMH107pacC8iMpD9PJ9BTaR6IF_B5E/edit#heading=h.qabd3d3txjj6)
* [Figma design](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A9053)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The UI from the [Figma design](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A9053) should be implemented in the `SetupFormGA4` component that was scaffolded in #3247.
    * One exception: For the blue notification, rely on our existing `SettingsNotice` component for the look for now, to keep this simple. The notification design will be updated to the one specified in the Figma file in a follow-up issue.
* Technically, the UI implementation should largely follow what is in `SetupFormLegacy`:
    * A `StoreErrorNotices` for the `modules/analytics` store should be on top. `ExistingTagNotice` and `ExistingGTMPropertyNotice` should not be included in this scenario for now.
    * The main dropdowns should be rendered in a `.googlesitekit-setup-module__inputs` container.  For the property dropdown, the `analytics-4` module's `PropertySelect` component needs to be used instead of the `analytics` one. The `ProfileSelect` and `ProfileNameTextField` are not necessary here since GA4 properties do not support profiles.
* Another technical requirement to specifically point out is that this component should automatically set the `modules/analytics` store's property ID and profile ID settings to `PROPERTY_CREATE` and `PROFILE_CREATE` respectively: Since this scenario is for when the account has no UA properties, the user doesn't need to select anything, instead it is clear that a new UA property needs to be created.
* Basic Storybook coverage for rendering `SetupForm` with this UI state (i.e. so that `SetupFormGA4` is shown) should be implemented.

## Implementation Brief
* Using `SetupFormGA4`,
	* Copy the code from `SetupFormLegacy` with changes as per the second bullet point in the AC.
	* Drop downs should be implemented as per the AC.
	* Upon component mount, use the `selectProperty` action of the `analytics` data store to set the property ID to `PROPERTY_CREATE` as per the third bullet point in the AC.
* Update stories for `SetupForm` so that `SetupFormGA4` can be displayed.

### Test Coverage
* No new tests needed.

### Visual Regression Changes
* N/A

## QA Brief

* Create a new site on https://jurassic.ninja/
* Go to Google Analytics and create a new account with a new GA4 property only for the new site
* Go back to the new site, install and connect the SK plugin
* Go to the plugin settings and activate the Analytics module
* Select the newly created account on the Analytics setup page.
* Make sure the form looks exactly like on the Figma design.
* Make sure that a new UA property and profile are created once you save the selected account.

## Changelog entry

* Add setup variant for Analytics accounts with only GA4 properties.

**Comment by eugene-manuilov** [comment]
@asvinb could you please elaborate more on when and how `propertyID` and `profileID` need to be set to `PROPERTY_CREATE` and `PROFILE_CREATE` values? On mount? On render? Or on a new property select? Also, what should happen if I select a GA4 property that has no UA property and then select another GA4 property that already has a UA property?

**Comment by eugene-manuilov** [comment]
Going to reduce the estimate here to 7 since 11 seems to be too much for this ticket.

**Comment by asvinb** [comment]
@eugene-manuilov I updated the IB to make it clearer because I thought it was clear from the AC, which says : "this component should automatically "

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QA brief?

**Comment by eugene-manuilov** [comment]
Added.

**Comment by danielgent** [comment]
I created this GA4 property
![existing-ga4](https://user-images.githubusercontent.com/8496063/120642547-5323b980-c475-11eb-8318-6074e6adec7e.png)


* _Make sure the form looks exactly like on the Figma design._
And I can see it here
![confirm-can-see-ga4](https://user-images.githubusercontent.com/8496063/120642537-4e5f0580-c475-11eb-818e-20c2fe650edc.png)



* _Make sure that a new UA property and profile are created once you save the selected account._

This was created

![new-ua](https://user-images.githubusercontent.com/8496063/120642683-7babb380-c475-11eb-8918-184cdccf88bd.png)
