### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by quangbahoa** [google/site-kit-wp#326]
## Bug Description

Blank page after update to beta 1.0.2
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at a (googlesitekit-admin.js:1)
    at Object.0 (commons.js:1)
    at a (googlesitekit-admin.js:1)
    at Module.174 (googlesitekit-admin.js:1)
    at a (googlesitekit-admin.js:1)
    at n (googlesitekit-admin.js:1)
    at googlesitekit-admin.js:1
    at googlesitekit-admin.js:1
googlesitekit-settings.js:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at l (googlesitekit-settings.js:1)
    at Module.184 (googlesitekit-settings.js:1)
    at l (googlesitekit-settings.js:1)
    at a (googlesitekit-settings.js:1)
    at googlesitekit-settings.js:1
    at googlesitekit-settings.js:1
allmodules.js:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at s (allmodules.js:1)
    at Module.<anonymous> (allmodules.js:1)
    at s (allmodules.js:1)
    at Object.<anonymous> (allmodules.js:1)
    at s (allmodules.js:1)
    at a (allmodules.js:1)
    at allmodules.js:1
    at allmodules.js:1
```

## Steps to reproduce

1. Dashboard widget does show
2. admin.php?page=googlesitekit-dashboard
3. admin.php?page=googlesitekit-module-search-console
4. admin.php?page=googlesitekit-module-analytics
5. admin.php?page=googlesitekit-settings

## Screenshots
- http://prntscr.com/ojavni

## Additional Context

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.10
	MySQL version: 5.5.5
	PHP Version: 7.3.4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://***
	Home URL: http://***
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Permalink Structure: /%postname%
	Language: en-US
	Timezone: 7
	Debug Mode: Inactive

== Theme ==
	Name: Cleon 2019
	Version: 1.3.2
	Author: TheThemeio
	Child Theme: Yes
	Parent Theme Name: TheSaaS
	Parent Theme Version: 1.3.6
	Parent Theme Author: TheThemeio

== User ==
	Role: administrator
	WP Profile lang: vi
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Breeze
		Version: 1.0.11
		Author: Cloudways

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Cleon Admin
		Version: 1.0.1
		Author: Lê Duy Quang

	Login No Captcha reCAPTCHA (Google)
		Version: 1.6.4
		Author: Robert Peake

	Really Simple SSL
		Version: 3.2.3
		Author: Rogier Lankhorst, Mark Wolters

	Site Kit by Google
		Version: 1.0.0-beta.1.0.2
		Author: Google

	TheElementor
		Version: 1.5.9
		Author: Elementor.com

	The SEO Framework
		Version: 3.2.4
		Author: Sybre Waaijer

	WPForms Lite
		Version: 1.5.3.1
		Author: WPForms

	WP Mail SMTP
		Version: 1.5.2
		Author: WPForms

== Debug ==
	Errors: There are no errors to display
				

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@quangbahoa Thanks for report, and context. It would be great to try and figure out the root cause, do you mind trying to follow the same steps using a default WordPress theme, with the Breeze plugin deactivated?

**Comment by quangbahoa** [comment]
I found it. Site Kit conflict with `Remove query string from static resources` function.

```
 function remove_cssjs_ver( $src ) {
    if ( strpos( $src, '?ver=' ) )
        $src = remove_query_arg( 'ver', $src );
    return $src;
}
add_filter( 'style_loader_src', 'remove_cssjs_ver', 10, 2 );
add_filter( 'script_loader_src', 'remove_cssjs_ver', 10, 2 );
```

**Comment by jamesozzie** [comment]
@quangbahoa Where did that function exist?

**Comment by quangbahoa** [comment]
@jamesozzie  It's a custom function and maybe include in some cache plugins.

**Comment by jamesozzie** [comment]
Thanks @quangbahoa. I couldn't locate a similar function in Breeze but good to know.
