### ISSUE TITLE
React error when Site Kit admin menu is moved from top-level 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3263]
## Bug Description

As reported in the WordPress support forums when using the [Admin Menu Editor plugin](https://wordpress.org/plugins/admin-menu-editor/) a React dashboard error appears if nesting the Site Kit primary dashboard within a custom added top level menu. 

Reproducible in support. As per the users experience this only occurs with Site Kit placed inside a custom added menu via the same plugin. I haven't encountered this same issue with other custom placements of the Site Kit menu option via plugins or via custom_menu_order. 

While any solution may be applicable on the Admin Menu side adding this here for a second review. 

![image](https://user-images.githubusercontent.com/1621608/120616713-1ef2cd80-c462-11eb-8750-97210c7caaf6.png)

```
Target container is not a DOM element.

    in NotificationCounter (created by GoogleSitekitDashboard)
    in GoogleSitekitDashboard
    in RestoreSnapshots (created by Root)
    in ErrorHandler (created by Root)
    in Root
```

<details>
<summary>Original screenshot</summary>

![image](https://user-images.githubusercontent.com/41326532/116702908-8cbe5c00-a9c1-11eb-8cff-05f27d5e765e.png)

</details>

## Steps to reproduce

1. Install the Admin Menu plugin (https://wordpress.org/plugins/admin-menu-editor)
2. Add a custom menu (Seeings > Menu Editor)
3. Add a custom menu (https://adminmenueditor.com/free-version-docs/how-to-add-new-menu/)
4. Cut the Site Kit dashboard menu and place under the newly created menu
5. Access the Site Kit dashboard from it's new location

## Additional Context

 - Site Kit 1.31.0
 - Admin Menu Editor Version 1.9.9 
 - One support topic in so far
 - Occurs with free version of plugin (and I assume Pro also)
 - Other Site Kit dashboards not impacted, all work when nested

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No React errors should be raised if the Site Kit menu items are not top-level items in the WP admin menu
* The `NotificationCounter` component should not be rendered if its [portal target](https://github.com/google/site-kit-wp/blob/e4a4d2b787b46c00f6fe1a6bc47c771ea79eb4c1/assets/js/components/legacy-notifications/notification-counter.js#L101) does not exist

## Implementation Brief
* ~~Using `assets/js/components/legacy-notifications/notification-counter.js`, update the `container` parameter of the `createPortal` function to target the first link with the href `admin.php?page=googlesitekit-dashboard` in the left admin menu. For e.g `document.getElementById( 'adminmenu' )?.querySelector( 'a[href="admin.php?page=googlesitekit-dashboard"] .wp-menu-name' )`~~
* Using `assets/js/components/legacy-notifications/notification-counter.js`, update the `render` function to return `null` if the `#toplevel_page_googlesitekit-dashboard .wp-menu-name` element does not exist.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Follow the same steps as to reproduce the issue.
* No errors should be displayed and Site Kit should load fine.

## Changelog entry

* Prevent rendering errors when the Admin Menu has been customized.

**Comment by jamesozzie** [comment]
Escalating this for further review. Happy to communicate with third party plugin if necessary, should any resolution be applicable on their side.

**Comment by aaemnnosttv** [comment]
Summarizing my findings:
* This isn't specific to the Admin Menu Editor, it is a result of moving the Site Kit menu item to a different place in the menu (specifically moving it to be the child of another menu)
* Likely a rare edge case for sites with highly-customized menus or substantially customized wp-admin
* Should be relatively low effort to fix

Moving forward to Execution.

**Comment by aaemnnosttv** [comment]
> Using `assets/js/components/legacy-notifications/notification-counter.js`, update the `container` parameter of the `createPortal` function to target the first link with the href `admin.php?page=googlesitekit-dashboard` in the left admin menu. For e.g `document.getElementById( 'adminmenu' )?.querySelector( 'a[href="admin.php?page=googlesitekit-dashboard"] .wp-menu-name' )`

@asvinb what would happen if this selector had no match? We still want to avoid creating the portal if the target doesn't exist. Secondarily, I'm not sure we should worry about trying to adapt this to work for a sub-menu. I'm pretty sure WP doesn't have any of these so I think we can simplify this by just not rendering the counter in this case. There's not much benefit to adding the counter there if it will be hidden anyways. What do you think?

**Comment by asvinb** [comment]
Good point @aaemnnosttv . I've updated the IB to return null if the container does not exist. However I'am thinking whether we can improve the selector which relies on the element having the `toplevel_page_googlesitekit-dashboard` id. 🤔

**Comment by aaemnnosttv** [comment]
> I'm thinking whether we can improve the selector which relies on the element having the `toplevel_page_googlesitekit-dashboard` id. 🤔

@asvinb I'm not sure we can. If the menu is not top-level, no one will see the notification count (and WP may not display the counter properly either). As it is, this selector would match it anywhere in the menu as long as it's top level so I think that's all we need for now. Open to suggestions for improvement though, but let's first understand the scenario(s) which would require a different selector before we try to make it more flexible 🙂 

IB ✅

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅

- Following the steps to recreate the issue. When switching to the `develop` branch, I can verify that no errors are displayed and Site Kit loads fine. 

https://user-images.githubusercontent.com/73545194/126647915-f9f07812-d396-4da4-99c9-e0e9e07f10e4.mp4
