### ISSUE TITLE
Homepage doesn't have a "Detailed Page Stats" view

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3265]
## Bug Description

As [reported in the WordPress support forums](https://wordpress.org/support/topic/detailed-page-stats/page/3/#post-14391898) one user is encountering an issue whereby there is no detailed page stats for their homepage. While their homepage does appear (twice) in the "Top Content" table the detailed page stats link for each URL result in the message:

_"It looks like the URL https://www.sitename.com/ is not part of this site, therefore there is no data available to display."_

Unable to reproduce so far in support from testing with a similar environment. 

[Video showing behaviour](https://www.loom.com/share/66cf400f99e3407780a2d242cb77b6bf)

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/116898453-4cafe100-ac2e-11eb-90f8-2f4d857f3db5.png)

![image](https://user-images.githubusercontent.com/41326532/116898500-5a656680-ac2e-11eb-86eb-71e91d6cd34a.png)

## Additional Context

 - Started occurring after updating to 1.31.0
 - The admin toolbar doesn't have the Site Kit tab on the users homepage, while it does on others (including with the Health Check & Troubleshooting plugin)
 - Both URLs in the top content table refer to the homepage, just different titles - with one displaying a "(not set)" value (different total click views)
- Language plugin active although their homepage doesn't include any language based path or indicator
- The user did kindly provide their [SH information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNheSNBZOmavT7LLpE8hveHk2D39atT727fStypVzF23Pc8jjbJs2f_ZS00SnbeGIdo)
- Litespeed server architecture
- All services [connected fine](https://imgur.com/F9n6uyH)
- The detailed page stats URL is correct, pointing to what should be their homepage statistics ([image](https://imgur.com/bpRb5j8))

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check - [image](https://imgur.com/U07yH7o)
- [x] Incognito mode 
- [x] Checked users Site Health info, no identified causes
- [x] Additional .htaccess rules applied (Additional rules evident)
- [x] Uninstalled and reinstalled plugin
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Disconnected impacted service and connected once more
- [x] Tested the same setup (Divi theme with the same site title, including "⋆" character) - Awaiting data
- [x] Confirmed a standard Analytics setup (on the Analytics set) - [no issues](https://imgur.com/E3ihMI2)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Recreated the same "Not Set" page by removing the overall "Site Title" and description from the defined values in a WordPress general settings screen. [No issues](https://recordit.co/rPjGbOozSV) with clicking on this link on this test site. 

Troubleshooting ongoing with possible old WPML database records possibly a factor. The admin toolbar doesn't appear on the homepage for the impacted user, indicating possible changes at some stage.

**Comment by bethanylang** [comment]
@jamesozzie Any update on this one, or shall we close?

**Comment by jamesozzie** [comment]
I've been unable to determine the cause so far, awaiting a response from the impacted user for one additional check, unable to reproduce on my side. I'll close if there is no response this week.

**Comment by jamesozzie** [comment]
Closing this as unreproducible. No further insights gathered so far, awaiting feedback from impacted user.

**Comment by jamesozzie** [comment]
Reopening with the issue still occurring for the impacted user. Awaiting further details on changing the homepage type to an individual post or page.

**Comment by jamesozzie** [comment]
Escalating this as I've been unable to determine the cause with further insights from the impacted user. The users homepage lists a collection of latest posts and it wasn't possible to switch to a single page or post. The user did kindly attempt switching only for their site to go down. 

There is also another user encountering the same issue although no further insights gathered so far:
https://wordpress.org/support/topic/url-is-not-part-of-this-site-therefore-there-is-no-data-available-to-display/

**Comment by jamesozzie** [comment]
Possibly related to #2862 however for this particular user their homepage doesn't use any query param.

**Comment by bethanylang** [comment]
@jamesozzie Have we had any other reports of this issue since last August?

**Comment by jamesozzie** [comment]
@bethanylang No additional reports since that time. Should the issue be related to a non standard content type or template we've since [improved the wording](https://github.com/google/site-kit-wp/issues/4097).

With no updates from the impacted user I propose we close this one.

**Comment by bethanylang** [comment]
@jamesozzie Thanks for confirming. I'll mark this one as closed for now, but we can reopen if we get any other reports.
