### ISSUE TITLE
Fix misspelling in README.md

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3267]
There is a misspelling in `README.md`, which refers to "Contributor Handhook" instead of "Contributor Handbook"; originally reported via #1340.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The misspelling of "Contributor Handhook" in `README.md` should be fixed.
* "Any kind of contributions to Site Kit by Google are welcome." should be changed to the more grammatically correct "Any kind of contribution to Site Kit by Google is welcome.".

## Implementation Brief

* Either iterate on #1340 or fix it in a new PR.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* The problems in `README.md` outlined in the ACs should be fixed.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 FYI added this to the sprint, but this already had a PR that worked as is, and QA should be minimal, so technically the estimate here is probably even less than 1.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- The misspelling of "Contributor Handhook" in README.md  is fixed.
- The text has changed to `Any kind of contribution to Site Kit by Google is welcome.`

![image](https://user-images.githubusercontent.com/73545194/117017009-2c922780-aceb-11eb-9066-db0054e2a568.png)
