### ISSUE TITLE
Fix broken link in `readme.txt`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3268]
## Bug Description

The link to `https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/` found in `readme.txt` is broken due to a "Markdown typo"; originally reported via #2863.

See how it is broken here:
<img width="727" alt="Screen Shot 2021-05-03 at 1 27 34 PM" src="https://user-images.githubusercontent.com/3531426/116929491-5a0ba200-ac13-11eb-83fe-b2757195c2b5.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The link to `https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/` (see "Learn how to use Site Kit with a staging environment" text) in `readme.txt` should work as expected.

## Implementation Brief

* Remove breaking space between the markdown link text and URL in the area described by the ACs in `readme.txt`.
* Merge #2863.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* The link to `https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/` (see "Learn how to use Site Kit with a staging environment" text) in `readme.txt` should be in correct Markdown (i.e. work as expected).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 Similar to #3267 here, this already had a working PR and QA should be super quick, so I've added it to the sprint and release.

**Comment by asvinb** [comment]
### QA: ✅ 

The "Learn how to use Site Kit with a staging environment" text is now a link as per screenshot below:
![image](https://user-images.githubusercontent.com/31818/116977780-e4b3d600-acd3-11eb-8aad-ea8ab6c2bc90.png)
