### ISSUE TITLE
Unknown Error after trying to authenticate with a Google Account

### ISSUE THREAD

**Issue by levidurfee** [google/site-kit-wp#327]
## Bug Description

I was getting an "Unknown Error" message after I tried authenticating with Google.

## Steps to reproduce

1. Get Client Configuration
2. Attempt to sign in with a Google account
3. See "Unknown Error"

## Additional Context

The Wordpress site is behind Cloudflare. The `WordPress Address (URL)` and the `Site Address (URL)` weren't using `http`, but I was accessing the site over `https` which indicated I was using the Flexible SSL solution. After changing my general config to use `https` the error no longer occurred.

Putting this here in case it may help someone else.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@levidurfee Thanks for the input. And you are correct, adding the https in the site settings and WordPress Address URL has indeed fixed this issue for others, in particular for those who are not redirecting to their https site. 

#4
