### ISSUE TITLE
Implement getting Idea Hub ideas for which there is a WordPress draft or published post

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3270]
Infrastructure for getting Idea Hub ideas for which a WordPress draft post or published post respectively exists should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GET:draft-post-ideas` REST data point should be implemented:
    * It should query WordPress draft posts that have Idea Hub idea metadata attached (i.e. include a meta query for the meta keys outlined in #3157). The query should be unlimited for now.
    * It should return an array of idea objects/associative arrays (see #3155 for the shape of an idea object), expanded with the following fields for each idea:
        * `postID` (integer, post ID, see also #3269)
        * `postEditURL` (string, post edit URL, see also #3269)
    * In other words, the response shape should be similar to e.g. the `GET:new-ideas` endpoint, except that it has additional fields for each entry.
* The `GET:published-post-ideas` REST data point should be implemented, the same way as `GET:draft-post-ideas`, except that it looks for published posts instead of draft posts.
    * The response shape should also be the same, except that in addition to `postID` and `postEditURL`, each idea object also gets a `postURL` field, which should be the URL to view the post in the frontend.
* The `modules/idea-hub` JS store should get a new selector `getDraftPostIdeas( options )`, similar to the existing `getNewIdeas` and `getSavedIdeas` selectors, except that it relies on `GET:draft-post-ideas`.
* The `modules/idea-hub` JS store should get a new selector `getPublishedPostIdeas( options )`, similar to the above `getDraftPostIdeas` selector, except that it relies on `GET:published-post-ideas`.

## Implementation Brief
* Using `includes/Modules/Idea_Hub.php`,
    * Update the `GET:draft-post-ideas` case from the `create_data_request` method to return the list of draft post ideas using `WP_Query` with the following options:
        * `post_status` set to `draft`
        * `fields` set to `ids` since we only need the post IDs
        * `posts_per_page` set to `-1` since the query should be unlimited for now as per the AC.
        * `no_found_rows` set to `true` since pagination is not needed.
        * `meta_query` set to an array of arrays where `key` is set to the three meta keys used to store the values for the name, text and topics of an idea. The meta keys can be found in:
            * `includes/Modules/Idea_Hub/Post_Idea_Name.php`
            * `includes/Modules/Idea_Hub/Post_Idea_Text.php`
            * `includes/Modules/Idea_Hub/Post_Idea_Topics.php`
            * `relation` set to `AND`
    * Return the result of `WP_Query`'s `query` method.
    * Add new protected function `parse_data_response` which will be used to parse responses for datapoints. Sample implementation can be found in the `Analytics_4` module class.
        * For the `GET:draft-post-ideas` datapoint, the function should do the following:
            * Use the `array_map` function along with the `$response` property to have an array containing the following keys:
                * `postID`: the ID of the post obtained via the currently iterated result.
                * `postEditURL`: the edit URL obtained via `get_edit_post_link()`
                * `name`, `text` and `topics`: the values are obtained by calling the `get_post_meta` function and accessing the values via the meta keys mentioned earlier.
            * Return the result of the `array_map` function.
* Create `assets/js/modules/idea-hub/datastore/draft-ideas.js`,
    * Most of the code can be copied over from `assets/js/modules/idea-hub/datastore/saved-ideas.js` with the following changes as per the AC:
        * Update the API URL to query the `GET:draft-post-ideas` endpoint by updating `API.get` in the `controlCallback` function.
        * Rename `savedIdeas` references to `draftIdeas`.
        * The selector name should be `getDraftPostIdeas`.
        * Remove the `validateParams` property from the `createFetchStore` function because the options are not sent to the API. This change shall also be applied to the existing `saved-ideas.js` and `new-ideas.js` store partials.
* Edit `assets/js/modules/idea-hub/datastore/index.js` to include the new store partial.
* Repeat the same process to get data for published post ideas with the following changes:
    * The `GET:published-post-ideas` case from the `create_data_request` must be updated and `post_status` should be set to `publish`.
    * Add case to handle the `GET:published-post-ideas` datapoint in `parse_data_response`
    * Add `postURL` in the data returned, which can be obtained via `get_permalink()`
* The `getPublishedPostIdeas` selector should live in `assets/js/modules/idea-hub/datastore/published-ideas.js` and the API URL should be `published-post-ideas`.

### Test Coverage
* Create `draft-ideas.test.js` which will contain tests for the `getDraftPostIdeas` selector.
* Create `published-ideas.test.js` which will contain tests for the `getPublishedPostIdeas` selector.

### Visual Regression Changes
* N/A

## QA Brief
* Create a draft post which has the following custom fields set:
    * `googlesitekitpersistent_idea_name`
    * `googlesitekitpersistent_idea_text`
    * `googlesitekitpersistent_idea_topics`
* Run the following command in the browser console and check if the newly created draft post details are returned as per the AC.
    * `googlesitekit.data.stores["modules/idea-hub"].selectors.getDraftPostIdeas();`
* Publish the draft post.
    * Running `googlesitekit.data.stores["modules/idea-hub"].selectors.getDraftPostIdeas();` should return an empty array.
    * Running `googlesitekit.data.stores["modules/idea-hub"].selectors.getPublishedPostIdeas();` should return the published post details.

## Changelog entry

* Add selectors to get draft and published posts created using Idea Hub ideas.

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. It's a good start but IB still needs more details, especially js selectors. Could you please describe which changes need to be made in the createFetchStore calls to cater to the new endpoints? We also need to mention that we need to use the appropriate `post_status` parameter in the WP_Query calls to select the correct posts.

As to the datapoint handlers, we need to update the IB to say that posts should be pulled in the `create_data_request` method and processed in the `parse_data_response` method. It should be done something like this:

```php
function create_data_request( ... ) {
    switch ( ... ) {
        case '...':
            return function() {
                $wp_query = new \WP_Query();
                return $wp_query->query( array( ... ) );
            };
    }
}

function parse_data_response( $data, $response ) {
    switch ( ... ) {
        case '...':
            $post_ideas = array();
            foreach ( $response as $post_id ) {
                $post_ideas[] = ...
            }
            return $post_ideas;
    }
}
```

**Comment by asvinb** [comment]
@eugene-manuilov IB updated to include the points to mentioned. Can you check again?
Thanks!

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB almost looks good. Here are a few minor points that we need to update:

> postID: the ID of the post obtained via get_the_ID()

There is no need to call `get_the_ID` function because `WP_Query::query()` method already returns an array of IDs. We can just loop through that array and compose a new one with extended details:

```php
$posts = array();

foreach ( $response as $post_id ) {
    $posts[] = array(
        'postID' => $post_id,
        ...
    );
}

return $posts;
```
> Most of the code can be copied over from assets/js/modules/idea-hub/datastore/saved-ideas.js with the following changes...

The `fetchGetSavedIdeasStore` datastore contains the `validateParams` property which is not needed for the new fetch datastores because they don't have parameters. So, let's explicitly mention to make sure that `validateParams` property isn't copied to the new fetch datastores settings.

**Comment by asvinb** [comment]
@eugene-manuilov @eugene-manuilov IB has been updated as per your suggestions.

Thanks!

**Comment by asvinb** [comment]
Thanks @eugene-manuilov . IB updated as per your comments :)

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB :heavy_check_mark:

**Comment by tofumatt** [comment]
QA ✅
