### ISSUE TITLE
Scaffold Idea Hub module in JS

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3273]
The `idea-hub` module should be registered in JS so that it can be activated (only if the `ideaHubModule` feature flag is enabled).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `registerModule( modules )` function should be implemented in `assets/js/modules/idea-hub/index.js` which registers the `idea-hub` module:
    * It should for now only include the `storeName` argument and the `Icon` argument.
    * For `Icon` it should reference [the icon used for the module in this Figma file](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A6889), which should be included as SVG.
* It should be called in `assets/js/googlesitekit-modules-idea-hub.js`, similar how it is done in other modules.

## Implementation Brief

1. Inside `assets/js/modules/idea-hub/index.js`:
  * Export a function, `registerModule`, which recieves a single parameter, `modules`, and uses it to call the `modules.registerModule` function. It should pass a string, `'idea-hub'` as the first argument, and the second argument (an object) should contain `storeName` and `Icon` properties. There are examples of how to do this in the root of other modules, e.g. `modules/analytics/index.js`.
  * For the `storeName`, import and use `MODULES_IDEA_HUB` from the constants file in the Idea Hub datastore. 
  * See the directions and Figma link in the AC above for the `Icon`. This should be included as an SVG file in the `assets/svg` directory, similar to how `analytics.svg` and others have been done.
2. Inside `assets/js/googlesitekit-modules-idea-hub.js`, 
  * import `Modules` from `googlesitekit-modules`
  * extend the existing import from the Idea Hub module to include the `registerModule` function we just defined
  * call the new `registerModule` function, passing `Modules` as the argument
  * Again, you can use another module, such as the Analytics module, as an example throughout.

### Test Coverage

* No new tests required; existing ones should pass.

### Visual Regression Changes

* None anticipated.

## QA Brief

* Enable the `ideaHubModule` feature flag in the tester plugin
* Using Redux tools check that `core/modules` has an action of type `REGISTER_MODULE` that has a payload containing:
  * `storeName(pin):"modules/idea-hub"`
  * `slug(pin):"idea-hub"`

## Changelog entry

* Add Idea Hub JS module (only active with the Idea Hub feature flag).

**Comment by tofumatt** [comment]
I tweaked `STORE_NAME` here and had it reference `MODULES_IDEA_HUB` instead, because it's clearer to use the more explicit constant name.

Otherwise looks good!

IB ✅

**Comment by asvinb** [comment]
1. Enabled the `ideaHubModule` feature flag via the tester plugin.
2. Checked for payload as per QA brief which is present as per screenshot.
![image](https://user-images.githubusercontent.com/31818/117998427-f260ff80-b354-11eb-90b0-ff17f98e731f.png)

### QA: ✅
