### ISSUE TITLE
Scaffold Idea Hub widget with tabbed UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3274]
The new ideas widget for the Idea Hub module should be scaffolded, including its tabbed UI. For now, each tab should be empty though, as these will be implemented in a follow-up issue. It should be possible to link to a specific tab in the widget.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `DashboardIdeasWidget` should be scaffolded in `assets/js/modules/idea-hub/components/dashboard`:
    * The widget should be scaffolded to look like [in this Figma file](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A2653), **excluding the actual content of each tab**, i.e. the list of ideas and the footer that has the pagination should be left out, to be implemented later. For now each tab should just be empty.
    * The three tabs should for now just have their basic labels, without any number suffix indicating the amount of ideas.
    * The filtering UI from the Figma design should not be implemented, i.e. completely ignored.
    * If the `idea-hub` module is not active or not connected, the widget should not be rendered.
    * The component should manually render the `props.Widget` component to ensure the default padding is not added, since manual padding needs to be added for the inner components per the Figma design.
    * It should be possible to link to one of the tabs directly, i.e. every tab should have its own unique ID attribute. If the current URL has that ID as anchor, the tab should be automatically focused (otherwise, i.e. by default, the "New" tab should be focused).
        * This should explicitly not be implemented using React Router, since it is not really a route, as it is embedded in the dashboard where it is just one of many widgets. Using an anchor link is more appropriate here.
* The new component should be registered via a new `registerWidgets( widgets )` function in `assets/js/modules/idea-hub/index.js` which is then called in `assets/js/googlesitekit-modules-idea-hub.js`, as usual. The widget should be registered as follows:
    * `width` should be `WIDGET_WIDTHS.HALF`
    * `wrapWidget` should be `false` as the widget needs to have special padding manually taken care of (see above)
    * The only widget area should be `AREA_DASHBOARD_ACQUISITION`.
    * `priority` should be `2`, taking over this slot from the existing `analyticsPopularPages` widget, which should instead be moved to `3`.
* A Storybook story for the scaffolded widget should be added.

## Implementation Brief
* Create new file `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js` which will export the `DashboardIdeasWidget` functional component, and using that file,
    * import the `Tab` and `TabBar` components from `@material/react-tab` and `@material/react-tab-bar` respectively.
    * implement the three tabs as per the AC with their tab content empty:
        * add a new state variable called `activeTabID` to manage which tab is active and the appropriate content to display in the tab area.
        * use the `handleActiveIndexUpdate` prop of the `TabBar` component to change the active tab.
        * use the `Grid`, `Row` and `Cell` components for the layout.
        * create functional components which will be rendered when their respective tab is active, i.e  `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/NewIdeas.js` which will export the `NewIdeas` functional component. It will be rendered if the `New` tab is active. The same logic applies to the `Saved` and `Drafts` tabs.
    * style the tabs and title as the per the designs in Figma.
    * use the `useHash` hook to get and set the hash when the tab index changes. We can prefix the hash by `ideas-`. For e.g `ideas-saved`, `ideas-new`, `ideas-draft`.
    * when the component is mounted, check if there is a hash and if it falls in the list from the previous bullet point,
        * set the active tab based on the hash.
        * use `window.scrollTo` to automatically scroll the user to the `DashboardIdeasWidget` widget, taking into account the sticky header. That means that any part of the component should not be hidden behind the header.
    * use the `whenActive` HOC to check whether the `idea-hub` module is connected and active when exporting the component.
    * Any class names used in the component should follow the BEM methodology, with the `googlesitekit-idea-hub` prefix. For e.g `googlesitekit-idea-hub__tabs`, `googlesitekit-idea-hub__tab--active`.
* Using `assets/js/modules/idea-hub/index.js`, export the `registerWidgets` function which registers the `DashboardIdeasWidget` widget with details as per in the AC. Examples of registering widgets can be found in other modules `index.js` files.
* Update `assets/js/googlesitekit-modules-idea-hub.js` to call the `registerWidgets` function defined in the previous bullet point.
* Using `assets/js/modules/analytics/index.js`, update the `priority` of the `analyticsPopularPages` widget from `2` to `3`.
* Create new file `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss` which will contain all the styles for the `DashboardIdeasWidget` component.
* Create `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget.stories.js` which will contain the story for the `DashboardIdeasWidget` component.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Run Storybook via the following command: `npm run storybook`
* Check if the Modules -> Idea Hub -> Widgets -> DashboardIdeasWidget -> Ready story matches the designs in Figma.

## Changelog entry

* Add an initial widget for the Idea Hub ideas.

**Comment by asvinb** [comment]
@felixarntz If we run the anchor link to scroll the user to the component, we might have an issue where part of the component will be hidden by the sticky header. I have added the IB where I suggest we use `window.scrollTo` for that purpose while taking into consideration the header. Then the hash will be managed similarly to what we do in the `SettingsApp` component. Let me know what you think.

**Comment by felixarntz** [comment]
@asvinb That sounds great! IB ✅

**Comment by cole10up** [comment]
**QA ✅**

Tested:

Ran `npm run storybook`

![image](https://user-images.githubusercontent.com/57115907/118917559-01602880-b8e6-11eb-9100-faa379824807.png)

Confirmed tabbed UI functionality in storybook on multiple browsers
![image](https://user-images.githubusercontent.com/57115907/118917635-25bc0500-b8e6-11eb-9b7b-10844a145817.png)

Sending to Approval
