### ISSUE TITLE
Implement CTA in Idea Hub widget for when the module is not activated

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3275]
When the Idea Hub module is not active (but the `ideaHubModule` feature flag is enabled), the Idea Hub ideas widget should show a dismissible CTA to activate the module to users with the necessary permissions.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js` should be implemented, as a custom version of the `ActivateModuleCTA` / `CompleteModuleActivationCTA`.
    * It should be scoped to the `idea-hub` module's needs and implement the custom design from [this Figma file](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A5623), instead of relying on the regular blue UI.
    * The "Learn more" link should lead to a (for now non-existing) URL `https://sitekit.withgoogle.com/documentation/idea-hub-module/`.
    * While the Figma design includes a `x` in the upper right corner to dismiss the CTA, this should not be implemented yet (neither the functionality nor the `x` button itself).
    * If the `idea-hub` module is already active but not connected, the copy on the button should say "Complete setup" instead of "Set up". The rest of the UI shouldn't differ between the two scenarios.
* The scaffolded widget from #3274 should, instead of returning `null` when the widget is not active or not connected, return the new `DashboardCTA` component.

## Implementation Brief

* Create a new component file, `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js`, which exports a functional component called `DashboardCTA` 
* Following `ActivateModuleCTA` as an example, 
  * Get the module information using the `getModule` selector from the Modules store, passing the module slug ('idea-hub')
* Build out the design from the Figma file included above in the ACs
  * Note that the 'x' and dismissal functionality should not be implemented for now
  * An Idea Hub logo should be included under `assets/svg` as part of #3273
* Include an `onClick` handler for the CTA, following `ActivateModuleCTA` as an example: 
  * Get the `activateModule` action from the Modules store and the `navigateTo` action from the Location store.  
  * On CTA click, call `activateModule`, then attempt to `navigateTo` the `response.moduleReauthURL`
  * If this fails, show a `GenericError` 
* Using the `module` information we got earlier, determine whether the module is `active` and `connected`
  * If the module is already active but not connected, the copy on the button should say "Complete setup" instead of "Set up". 
  * The rest of the UI shouldn't differ between the two scenarios. 
* Inside the `DashboardIdeasWidget` component created in #3274:
  * Get the module information as we did in the CTA widget, and determine whether the module is `active` and `connected`
  * If the widget is not active or not connected, return the new `DashboardCTA` component instead of `null`.

### Test Coverage

* No test coverage required.

### Visual Regression Changes

* None anticipated.

## QA Brief

* Make sure the `ideaHubModule` and `widgets.dashboard` features are enabled
* On the Site Kit dashboard, in the *Acquisitions* widget area, you should now see the `DashboardCTA` component
* The component should look like the Figma design (see ACs), without the 'x'.
* The "Learn more" link should lead to a (for now non-existing) URL `https://sitekit.withgoogle.com/documentation/idea-hub-module/`
* If the module is not active or connected, the CTA button should say 'Set up'
* If the module is active, but not yet connected, the CTA button should say 'Complete set up'
* There should be corresponding stories for these two states in Storybook under `Modules > Idea Hub > components > dashboard > DashboardCTA`

## Changelog entry

* Add a module activation CTA for Idea Hub to the Site Kit dashboard.

**Comment by felixarntz** [comment]
@johnPhillips IB ✅ 

Note that I've added one point to the ACs (which doesn't require IB changes though), which is the specific URL that the "Learn more" link should point to.

**Comment by asvinb** [comment]
### QA: ❌ 

Refer to annotated screenshots for issues:
Large Screens:
![image](https://user-images.githubusercontent.com/31818/120321274-2d22db80-c2f4-11eb-86bb-4beba4b084b9.png)

Small Screens:
![image](https://user-images.githubusercontent.com/31818/120321393-4e83c780-c2f4-11eb-97fd-97c1161dbad4.png)

**Comment by aaemnnosttv** [comment]
@johnPhillips looks like the main things missing here are:
- Component should be wrapped with `Widget` (provided via props)
    - This also solves the "Should have height 100% to match the height of the adjacent widget"
    - Also addresses missing shadow
    - For storybook, we probably need to use `withWidgetComponentProps` on the template's inner component
- Body layout in WP does not wrap the way it does in Storybook without an added `display: flex`
- For the non-caps button, I think we can use `Link` for this (should be just switching the component I think)
- Regarding the Learn More link, I think the `inherit` prop is needed there 

Let me know if there's anything else.

**Comment by johnPhillips** [comment]
@asvinb and @aaemnnosttv Thanks both. The list and screenshots are a great help.

Can I ask: what size viewport is that 'Small screens' screenshot, and what is the minimum viewport width we support?
I'm using the smallest setting in dev tools (360px) and it's not overflowing. 
However, the 'Small Mobile' setting in storybook takes it down to 220px (which seems slightly excessive) and it **does** overflow there:

| Browser 360px | Storybook 'small mobile' |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/2470911/120357205-15038a00-c2fd-11eb-8983-a76e6f82ff4c.png"> | ![Screenshot 2021-06-01 at 17 15 44](https://user-images.githubusercontent.com/2470911/120357548-788db780-c2fd-11eb-8ed2-113db6b228f5.png) |

The designs don't cover this edge case, so should it wrap / stack here? i.e. 
  Icon 
  copy ⏎
  learn more ⏎
  button ⏎

Also, @aaemnnosttv: could you please elaborate on this as I am not sure I understand:
> Body layout in WP does not wrap the way it does in Storybook without an added display: flex

**Comment by johnPhillips** [comment]
Bumping the estimate to 19 after a conversation with @fhollis

**Comment by aaemnnosttv** [comment]
Back to you @asvinb for another pass 👍

**Comment by asvinb** [comment]
### QA: ✅ 

- `DashboardCTA` matches Figma designs and fulfils the AC.
