### ISSUE TITLE
Implement idea list tabs and basic interaction in Idea Hub widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3276]
The UI and basic interaction of the three tabs in the Idea Hub ideas widget should be implemented (without the contextual per-idea functionality for now).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The three tabs for the Idea Hub widget that was scaffolded in #3274 should be implemented, with the design following [what is in the Figma file](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A1819):
    * Every tab should list ideas using its respective selector (`getNewIdeas`, `getSavedIdeas`, `getDraftPostIdeas`).
    * Every idea entry should have the following controls available that are visible at all times:
        * A button to create a new draft post, if there is no draft post for it yet (i.e. in "New" or "Saved" tab).
        * A button to view the draft post, if there is one already (i.e. in "Drafts" tab).
    * Every idea entry should have the following controls available _only when hovering/focusing the entry:
        * A button to save the idea for later if not saved yet (i.e. in "New" tab).
        * A button to unsave the idea if saved (i.e. in "Saved" tab).
        * A button to dismiss the idea if it is not saved yet and no draft post exists yet (i.e. only if in "New" tab).
    * No functionality for any of the above per-idea controls should be implemented yet, i.e. individual empty callbacks with `TODO` annotations should be used for each of the interactions.
    * The filtering UI from the Figma design should not be implemented, i.e. completely ignored.
    * The "Saved" and "Drafts" tab labels should be enhanced so that they include the total number of saved ideas / draft ideas available.
    * Every tab should list 4 ideas at a time and support pagination. In other words, it should always pass pagination arguments to the respective selector.
    * Pagination should be tracked within the component, individually per tab.
    * Pagination should be rendered at the bottom of each tab, with the total number as well as pagination arrows. The button to go to the previous page should be disabled if on page 1, the button to go to the next page should be disabled if already on the last page (i.e. for the next page the selector returns no ideas).
    * If for any of the 3 tabs no ideas are available, special state should be rendered:
        * For the "New" tab, the [yellow side kick with corresponding copy, as in this Figma design](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A6443), except that it should show within the tab, not as the only thing in the entire widget.
        * For the "Saved" tab, the [blue side kick with corresponding copy, as in this Figma design](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A5181).
        * For the "Drafts" tab, the [red side kick with corresponding copy, as in this Figma design](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20338%3A3890).

## Implementation Brief
* Once #3270 and #3274 have been merged.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`,
    * Query the `idea-hub` data store with the selectors below to get the post count for new ideas, saved ideas and draft ideas.
        * `getNewIdeas` to get the total number of new ideas.
        * `getSavedIdeas` to get the total number of saved ideas.
        * `getDraftPostIdeas` to get the total number of draft ideas.
    * Get the post count for the results of the selector calls above and display the count in each tab label.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/NewIdeas.js`,
    * Query the `idea-hub` data store via the `getNewIdeas` selector to retrieve the list of new ideas.
    * Display and style the list of ideas as per the designs in Figma. 
    * For each idea, the following buttons must be present:
        * a button to dismiss the idea (visible only upon hovering the idea).
        * a button to save the idea for later (visible only upon hovering the idea).
        * a button to create a new draft post (always visible).
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/SavedIdeas.js`,
    * Query the `idea-hub` data store via the `getSavedIdeas` selector to retrieve the list of saved ideas.
    * Display and style the list of ideas as per the designs in Figma. 
    * For each idea, the following buttons must be present:
        * A button to unsave the idea (visible only upon hovering the idea).
        * a button to create a new draft post (always visible).
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/DraftIdeas.js`,
    * Query the `idea-hub` data store via the `getDraftPostIdeas` selector to retrieve the list of draft ideas.
    * Display and style the list of ideas as per the designs in Figma. 
    * For each idea, the following buttons must be present:
        * a button to view the draft post (always visible).
* All styles for the above components should go in `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`.
* Toggling the visibility of the buttons upon hover should be achieved using CSS only.
* Create new file `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Pagination.js` which exports the `Pagination` functional component which has the following props:
    * setPage: function (function from the parent component to set the page. See further below)
    * total: number (Total number of ideas).
    * page: number (Current page)
    * ideasPerPage: number (the number of ideas per page)
    * handleBack: function (called when the previous arrow is clicked and used to change the page number via the `setPage` prop)
    * handleNext: function (called when the next arrow is clicked and used to change the page number via the `setPage` prop)
* The `Pagination` component should render the content as per the designs in Figma with the above props and implemented as per the AC.
* Create `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-pagination.scss` which will contain all the styles associated to the `Pagination` component.
* To handle pagination in the above 3 child components (applicable to each of them):
    * Create a new constant called `ideasPerPage` which is set to `4`.
    * Create a state variable `page`, having `1` as default value.
    * Using those 2 values, calculate the `offset` property value which are passed on to the `getNewIdeas`, `getSavedIdeas` and `getDraftPostIdeas` selectors along with the `length` property which should be set to the `ideasPerPage` constant.
    * Include the `Pagination` component passing the appropriate props.
* Refer to the AC about what should be rendered if there is no data in any of the tabs.
* Any class names used in the component should follow the BEM methodology, with the `googlesitekit-idea-hub` prefix.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Run storybook locally by running the `npm run storybook` command.
* Check if the "Idea Hub -> Widgets -> DashboardIdeasWidget" stories render as per the designs in Figma as interaction is as per the AC.

## Changelog entry

* Implement idea list tabs and basic interaction in Idea Hub widget

**Comment by tofumatt** [comment]
Thanks! Looks good 🙂 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Every tab lists ideas using its respective selector (getNewIdeas, getSavedIdeas, getDraftPostIdeas).

Every idea entry has the following controls available that are visible at all times:
- A button to create a new draft post, if there is no draft post for it yet (i.e. in "New" or "Saved" tab).
- A button to view the draft post, if there is one already (i.e. in "Drafts" tab).

![image](https://user-images.githubusercontent.com/73545194/119676767-05d09800-be36-11eb-8cb6-daadfbc44c2e.png)
![image](https://user-images.githubusercontent.com/73545194/119676797-0bc67900-be36-11eb-83d7-b60b29093203.png)

- A button to save the idea for later if not saved yet (i.e. in "New" tab).
- A button to unsave the idea if saved (i.e. in "Saved" tab).
- A button to dismiss the idea if it is not saved yet and no draft post exists yet (i.e. only if in "New" tab).

- The "Saved" and "Drafts" tab labels includes the total number of saved ideas / draft ideas available.

![image](https://user-images.githubusercontent.com/73545194/119678985-e9cdf600-be37-11eb-9b2d-a46a6dcdfeaf.png)

- Every tab lists 4 ideas at a time and support pagination.
- Pagination is tracked within the component, individually per tab.
- Pagination is rendered at the bottom of each tab, with the total number as well as pagination arrows. 
- The button goes to the previous page is disabled if on page 1
- The button goes to the next page should be disabled if already on the last page.

![image](https://user-images.githubusercontent.com/73545194/119679114-ffdbb680-be37-11eb-8ba8-8d0d12e15dc5.png)

- For the "New" tab, the yellow side kick with corresponding copy, as in this Figma design  - [Screenshot](https://user-images.githubusercontent.com/73545194/119679663-72e52d00-be38-11eb-8216-171aba820165.png)
- For the "Saved" tab, the blue side kick with corresponding copy, as in this Figma design. - [Screenshot](https://user-images.githubusercontent.com/73545194/119679691-77a9e100-be38-11eb-98a8-1888314ed41d.png)
- For the "Drafts" tab, the red side kick with corresponding copy, as in this Figma design. - [Screenshot](https://user-images.githubusercontent.com/73545194/119679725-7ed0ef00-be38-11eb-98a6-472e6cd086ae.png)
