### ISSUE TITLE
Add support to place Google Ads conversion ID in Analytics AMP snippet

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3282]
While #3161 allows specifying the Google Ads conversion ID and having Site Kit integrate it with the Analytics snippet, the initial enhancement didn't include AMP support due to time constraints. Support for also integrating the Ads conversion ID with the `amp-analytics` snippet placed by the Analytics module should be added via this issue.

See [this comment](https://github.com/google/site-kit-wp/issues/3161#issuecomment-827975122) for more context, plus [the official documentation](https://developers.google.com/google-ads/amp/conversion-measurement#option_1_global_site_tag).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `amp-analytics` snippet placed by the `Analytics\AMP_Tag` class should incorporate the Google Ads conversion ID (`adsConversionID` setting) if specified, placing it in the `config` JSON object alongside the GA measurement ID as outlined in https://developers.google.com/gtagjs/devguide/amp#installation.

## Implementation Brief

* Change the `'config'` value in https://github.com/google/site-kit-wp/blob/db4d6444f12e4185f1ff36e2602e3b6fe14a1fc6/includes/Modules/Analytics/AMP_Tag.php#L128 to be built separately and conditionally, adding the Ads Conversion ID if available, eg:

```php
$config = array(
    $this->tag_id => array(
        'groups' => 'default',
        'linker' => array(
            'domains' => array( $this->home_domain ),
        ),
    ),
);

if ( ! empty( $this->ads_conversion_id ) ) {
    $config[ $this->ads_conversion_id ] => array(
        'groups' => 'default',
    );
}
```

### Test Coverage

* Add a PHPUnit test to ensure this value is only output in the config when available—if this is straightforward to do. (I'm not sure if we have tag insertion test infrastructure already, but adding it would be overkill.)

### Visual Regression Changes

* N/A.

## QA Brief

* Enable AMP (Standard mode) on your site with a compatible theme (Twenty-Twenty works), enable the Analytics module, then add an Ads Conversion ID to the Analytics module in Settings.
* View the page in AMP mode (anonymously, so the `<amp-analytics>` tag appears, as it won't for signed-in users.
* Ensure the `{ "$adsConversionID": { "groups": "default" } }` JSON appears in the tag's `config`.

## Changelog entry

* Update `amp-analytics` tag to include configuration for an ads conversion ID when provided.

**Comment by felixarntz** [comment]
@eclarke1 We are awaiting internal input for the technical requirements for this one, but it should eventually end up being a 3 estimate or 7 maximum.

**Comment by tofumatt** [comment]
From the docs linked this seems _very_ straightforward, so I think this is 3 estimate unless I'm missing something 🙂

**Comment by felixarntz** [comment]
@tofumatt IB pretty much good to go, except you don't need to break out `config` in order to do that: `$gtag_amp_opt['config'][ $this->ads_conversion_id ] = ...` works too and requires less code changes :)

**Comment by tofumatt** [comment]
That requires doing `$gtag_amp_opt[ 'vars' ][ 'config' ][ $this->ads_conversion_id ] = …`, which to me is a bit less easy-to-follow, because they're similar attributes (all stuff that goes in "config"), but is accessed in different variables with different nesting.

The code change I'm making is a bit more lines but I think it's more explicit while actually being less verbose, because `$config` is "complete" by the time it's passed to `$gtag_amp_opt`, meaning future work on it/reading of the logic is in one place. 🙂 

I think it's better to break out config and fully define it before moving on, as it'll make the logic easier to parse for the future.

**Comment by felixarntz** [comment]
@tofumatt Fair point, we can create the `$config` in a separate variable and then insert it into the full `$gtag_amp_opt`. I think doing this is not really common in PHP, but certainly more of a personal preference, and your argumentation for it makes sense. IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

When viewing the AMP mode (the `<amp-analytics>` tag appears in the source code) I can see the { "$adsConversionID": { "groups": "default" } } JSON in the tag's config. 

![image](https://user-images.githubusercontent.com/73545194/118498649-2bff8500-b71e-11eb-9d8c-f74daac2068d.png)
