### ISSUE TITLE
Display notice or error for existing GA4 tag in Analytics when applicable

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3289]
If there is an existing GA4 tag in the frontend (see #3288), the user should be informed about it in Analytics setup / settings. If they don't have access to the related property or web data stream, they should be blocked.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**Note:** In order to check that an existing GA4 tag matches a certain GA4 property, it needs to be checked whether the GA4 property has a web data stream that includes the measurement ID indicated by the existing tag.

* In the `ga4` version of the Analytics setup flow (see #3249), if there is an existing GA4 tag (see #3288):
    * If a GA4 property is selected and it is the same one as indicated by the existing tag, the following note should be displayed above the dropdowns:  
      > _An existing Google Analytics 4 tag was found on your site with the ID G-{measurementID}. Since this tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._

      In this case, the `analytics-4` / GA4 `useSnippet` option should be turned off.
    * Otherwise (i.e. if no GA4 property is currently selected or if it does not match the existing tag), the following note should be displayed above the dropdowns:  
      > _An existing Google Analytics 4 tag was found on your site with the ID G-{measurementID}._
* In the `ga4transitional` version of the Analytics setup flow (see #3250):
    * If there is an existing UA tag (i.e. `getExistingTag` in `modules/analytics` store) but no existing GA4 tag (i.e. `getExistingTag` in `modules/analytics-4` store):
        * If a UA property is selected and it is the same one as indicated by the existing tag, the following note should be displayed above the dropdowns:  
          > _An existing Universal Analytics tag was found on your site with the ID {propertyID}. Since this tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._

          In this case, the `analytics` / UA `useSnippet` option should be turned off.
        * Otherwise (i.e. if no UA property is currently selected or if it does not match the existing tag), the following note should be displayed above the dropdowns:  
          > _An existing Universal Analytics tag was found on your site with the ID {propertyID}._
    * If there is an existing GA4 tag (i.e. `getExistingTag` in `modules/analytics-4` store) but no existing UA tag:
        * If a GA4 property is selected and it is the same one as indicated by the existing tag, the following note should be displayed above the dropdowns:  
          > _An existing Google Analytics 4 tag was found on your site with the ID G-{measurementID}. Since this tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._

          In this case, the `analytics-4` / GA4 `useSnippet` option should be turned off.
        * Otherwise (i.e. if no GA4 property is currently selected or if it does not match the existing tag), the following note should be displayed above the dropdowns:  
          > _An existing Google Analytics 4 tag was found on your site with the ID G-{measurementID}._
    * If there is an existing UA tag _and_ an existing GA4 tag:
        * If both a UA property and a GA4 property are selected both of which match the respective existing tag, the following note should be displayed on top of the dropdowns:  
          > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site. Since these tags refer to the same properties you have selected here, Site Kit will not place its own tags and rely on the existing ones. If later on you decide to remove these tags, Site Kit can place new tags for you._

          In this case, both the `analytics-4` / GA4 `useSnippet` and the `analytics` / UA `useSnippet` options should be turned off.
        * Otherwise, if a UA property is selected which matches the existing UA tag, the following note should be displayed on top of the dropdowns:  
          > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site. Since the Universal Analytics tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._

          In this case, the `analytics` / UA `useSnippet` option should be turned off.
        * Otherwise, if a GA4 property is selected which matches the existing GA4 tag, the following note should be displayed on top of the dropdowns:  
          > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site. Since the Google Analytics 4 tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._
          
          In this case, the `analytics-4` / GA4 `useSnippet` option should be turned off.
        * Otherwise, the following note should be displayed on top of the dropdowns:  
          > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site._
* All notes here should visually appear just as plaintext, without a "notice" wrapper, i.e. similar to `ExistingTagNotice`.

## Implementation Brief

* Update the `ExistingTagNotice` component in the `analytics` module:
  * Return the original message if the `ga4setup` feature flag is not enabled.
  * Get the existing tag for the `analytics-4` module using the `getExistingTag` selector.
  * Get `propertyID` settings of `analytics` and `analytics-4` modules.
  * If the existing UA tag is not empty but GA4 tag is empty, then:
    * Display the following message if a UA property is selected and it is the same one as indicated by the existing tag:

      > _An existing Universal Analytics tag was found on your site with the ID {propertyID}. Since this tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._
    * Otherwise display the following message:

      > _An existing Universal Analytics tag was found on your site with the ID {propertyID}._
  * If the existing GA4 tag is not empty but UA tag is empty, then:
    * Display the following message If a GA4 property is selected and it is the same one as indicated by the existing tag:

      > _An existing Google Analytics 4 tag was found on your site with the ID G-{measurementID}. Since this tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._
    * Otherwise display the following message:

      > _An existing Google Analytics 4 tag was found on your site with the ID G-{measurementID}._
  * If both tags exist and not empty:
    * Display the following message if both a UA property and a GA4 property are selected both of which match the respective existing tag:

      > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site. Since these tags refer to the same properties you have selected here, Site Kit will not place its own tags and rely on the existing ones. If later on you decide to remove these tags, Site Kit can place new tags for you._
    * Otherwise, display the following message if a UA property is selected which matches the existing UA tag:

      > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site. Since the Universal Analytics tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one._
    * Otherwise, display the following message if a GA4 property is selected which matches the existing GA4 tag:

      > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site. Since the Google Analytics 4 tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you._
    * Otherwise, display the following message:

      > _An existing Universal Analytics tag with the ID {propertyID} and an existing Google Analytics 4 tag with the ID G-{measurementID} were found on your site._

* Update the `SetupFormGA4` component:
  * Render the `ExistingTagNotice` component above the dropdowns.
  * Get the existing tag for the `analytics-4` module using the `getExistingTag` selector.
  * Add a new `useEffect` hook that sets the `useSnippet` setting for the `analytics-4` module to `false` if the existing tag is not empty and there is a web data stream for the currently selected property that has `measurementID` equal to the existing tag. Otherwise, it should set it to `true`.
* Update the `SetupFormGA4Transitional` component:
  * Render the `ExistingTagNotice` component above the dropdowns.
  * Get the existing tag for `analytics` and `analytics-4` modules using the respective `getExistingTag` selectors.
  * Add a new `useEffect` hook that:
    * Sets `useSnippet` settings of the `analytics` and `analytics-4` modules to `true` at the beginning.
    * If the existing UA tag is not empty but GA4 tag is empty, then sets the `useSnippet` setting of the `analytics` module to `false` if a UA property is selected and it is the same one as indicated by the existing tag.
    * If the existing GA4 tag is not empty but UA tag is empty, then sets the `useSnippet` setting of the `analytics-4` module to `false` If a GA4 property is selected and it is the same one as indicated by the existing tag.
    * If both tags exist and not empty:
      * sets `useSnippet` settings of `analytics` and `analytics-4` modules to `false` if both a UA property and a GA4 property are selected both of which match the respective existing tag.
      * sets `useSnippet` setting of the `analytics` module to `false` if only a UA property is selected which matches the existing UA tag.
      * sets `useSnippet` setting of the `analytics-4` module to `false` if only a GA4 property is selected which matches the existing GA4 tag.
* Add storybook stories for each case.

### Test Coverage

* Add js tests that verify `useSnippet` manipulations in the aforementioned components.

### Visual Regression Changes

* N/A

## QA Brief

* Refer to the ACs to test that the messages appear based on the tags you have set for the site. Given there are a lot of options, you can check the storybook stories (https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-setup-setupformga4--without-existing-tag) to view the various permutations.

## Changelog entry

* Add support for Google Analytics 4 tags in the notices for existing Google Analytics tags in the Analytics setup.

**Comment by felixarntz** [comment]
I have significantly updated the ACs here to no longer enforce anything, other than preventing duplicate tags when the same property like an existing tag is selected. This follows our new approach that we'll in the future implement for old Analytics and Tag Manager modules as well - only guidance with notifications, no complex account lookup which is really not supported by the APIs anyway.

**Comment by marrrmarrr** [comment]
Slightly edited the notifications for the different options.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov - the IB is off to a good start but there are a few things to address.

You mention updating the setup form components but we should probably introduce specific existing tag notice components like are currently used elsewhere so that the logic for which message etc is encapsulated within it.

The other thing which I think is important to mention is around the behavior of the `useSnippet` disabling. If a user were to select a different property after selecting one matching the existing tag, the snippet should not remain disabled.

Please also elaborate on where this would be handled. In UA GA and in GTM we have the `useExistingTagEffect` which I think would be good to keep, even if simple for this purpose.

**Comment by eugene-manuilov** [comment]
> You mention updating the setup form components but we should probably introduce specific existing tag notice components like are currently used elsewhere so that the logic for which message etc is encapsulated within it.

IMO this is overkill, we can reuse the existing `ExistingTagNotice` component for it. Update the IB to mention it.

> The other thing which I think is important to mention is around the behavior of the useSnippet disabling. If a user were to select a different property after selecting one matching the existing tag, the snippet should not remain disabled.

I have added instructions to use a `useEffect` hook for `useSnippet` modifications.

**Comment by aaemnnosttv** [comment]
> I have added instructions to use a `useEffect` hook for `useSnippet` modifications.

It might still be worth extracting a custom hook for this to aid in testing which I think is important for this mechanic, but if it's just as easy to do it with the form itself, that's fine.

Otherwise the IB looks good, but please add test coverage for covering programmatic changes to `useSnippet` since this is rather important but also not something we can see/verify during setup.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by danielgent** [comment]
This ticket should be marked as blocked by #3249 and #3250 for the `SetupFormGA4` and `SetupFormGA4Transitional` respectively (currently on develop these are just placeholders)

Currently @tofumatt  and @aaemnnosttv are code reviewing these tickets

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

As per the QAB, I went through Storyboard and checked all of the entries in the AC. 

_In the ga4 version of the Analytics setup flow, if there is an existing GA4 tag :_

- When GA4 property is selected and it is the same one as indicated by the existing tag, the note is displayed above the dropdowns.  [Screenshot](https://user-images.githubusercontent.com/73545194/121220704-c3b74580-c87c-11eb-8bf8-31e33653d9dd.png)
- When GA4 property is currently selected or if it does not match the existing tag, the following note is displayed above the dropdowns. [Screenshot](https://user-images.githubusercontent.com/73545194/121221014-0ed15880-c87d-11eb-87d8-30410b1f2101.png)

_In the ga4transitional version of the Analytics setup flow_ 

- If a UA property is selected and it is the same one as indicated by the existing tag, the note is displayed above the dropdowns.  [iScreenshot](https://user-images.githubusercontent.com/73545194/121222092-23622080-c87e-11eb-9cae-2dd8aeacc773.png)
- If no UA property is currently selected or if it does not match the existing tag), the note is displayed above the dropdowns:- [Screenshot](https://user-images.githubusercontent.com/73545194/121222625-9ff4ff00-c87e-11eb-88b5-afd0d160556f.png)

_If there is an existing GA4 tag (i.e. getExistingTag in modules/analytics-4 store) but no existing UA tag_

- If a GA4 property is selected and it is the same one as indicated by the existing tag, the note is displayed above the dropdowns:  [Screenshot](https://user-images.githubusercontent.com/73545194/121223911-edbe3700-c87f-11eb-8fed-43fe2f7f4c7d.png)
- if no GA4 property is currently selected or if it does not match the existing tag, the note is displayed above the dropdowns: 
[Screenshot](https://user-images.githubusercontent.com/73545194/121222625-9ff4ff00-c87e-11eb-88b5-afd0d160556f.png)

_If there is an existing UA tag and an existing GA4 tag:_

- If both a UA property and a GA4 property are selected both of which match the respective existing tag, the note is dis
- played on top of the dropdowns: [Screenshot](https://user-images.githubusercontent.com/73545194/121223911-edbe3700-c87f-11eb-8fed-43fe2f7f4c7d.png)
- If a UA property is selected which matches the existing UA tag, the note is displayed on top of the dropdowns: [Screenshot](https://user-images.githubusercontent.com/73545194/121222625-9ff4ff00-c87e-11eb-88b5-afd0d160556f.png)
