### ISSUE TITLE
AdSense account not found

### ISSUE THREAD

**Issue by coolnaveesh** [google/site-kit-wp#329]
Google has accepted my domain and request when i click continue i get this message.Please help me 

**Data error in AdSense
Account not found.**
![git](https://user-images.githubusercontent.com/37809262/61825394-eead7180-ae7d-11e9-8f4d-cf8222ffaee9.jpeg)

**Comment by jamesozzie** [comment]
@coolnaveesh Can you please try the following and should the issue persist we can troubleshoot further:

1. Disconnect the AdSense module (Site Kit > Settings > AdSense > Edit > Disconnect AdSense from Site Kit)
2. Temporarily deactivate any caching plugin (Autoptimize, WP Super Cache etc)
3. Open Site Kit in a new incognito window (so Chrome extensions/caching doesn't interfere with the setup process)
4. Connect the AdSense module (Site Kit > Settings > Connect other services > Analytics)

Let me know if the above works. Very important to check in an incognito window also, AdBlockers can also sometimes cause interference during setup.

**Comment by coolnaveesh** [comment]
working.Thanks
