### ISSUE TITLE
Alter module setup success notification related to GA4 double-tagging to inform about current reporting situation

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3290]
After completing the Analytics module setup with GA4 support, the user should be informed in the success notification that for now Site Kit only displays reporting data from the UA property that was configured.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For Analytics specifically and **only if the `ga4setup` feature flag is enabled**, the existing success notification for completing the module setup should have its copy slightly adjusted:
    * It should have an additional explanation below the "Congrats ..." title, which says "You'll only see Universal Analytics data for now." and is then accompanied with a "Learn more" link that leads to `https://sitekit.withgoogle.com/documentation/ga4-analytics-property/`. This is based on [this Figma design](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A8278), however all unrelated design changes should not be implemented here as they don't relate to GA4.

## Implementation Brief
- Using `assets/js/modules/analytics-4/index.js`,
    - Use the `isFeatureEnabled` function to check if the `ga4setup` feature flag is enabled.
    - If `ga4setup` feature flag is enabled, call `addFilter` from `@wordpress/hooks` with the following parameters:
        - hookName: `googlesitekit.SetupWinNotification-analytics`
        - namespace: `googlesitekit.OptimizeSetupWinNotification`
        - callback: function which as `winData` as parameter.
    - Within the callback function, set the values below for the `winData` properties below as per the AC:
        - `description`
        - `learnMore.label`
        - `learmMore.url`
    - Return the updated `winData` object in the callback function.
- Note that the designs in Figma will not match what is currently implemented, but as per the AC, this is out of scope for this ticket.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

QA NOTES

Setup does not yet work for GA4 so in order to see these code changes

* ensure Analytics is not set up
* ensure ga4setup flag is disabled
* setup Analytics
* land on the success page
* enable ga4setup flag
* refresh analytics' success page
* see changes listed in AC and IB

## Changelog entry

* Update success notification for the Analytics module when GA4 support is activated

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by cole10up** [comment]
**### QA ✅**

Confirmed GA4 setup is disabled:
![image](https://user-images.githubusercontent.com/57115907/120941886-258b7a00-c6da-11eb-9d55-7a8e84de3afb.png)

Setup analytics and landed on the splash page:
![image](https://user-images.githubusercontent.com/57115907/120941938-64213480-c6da-11eb-9215-4d3bc6cf6188.png)

Enabled GA4 setup and saved:
![image](https://user-images.githubusercontent.com/57115907/120941996-b6625580-c6da-11eb-8fb5-8a4cf0b696b5.png)

Refreshed the success splash page in a separate tab:
![image](https://user-images.githubusercontent.com/57115907/120942071-42747d00-c6db-11eb-86e8-db276d4b6f78.png)

Confirmed the functionality of the Learn more link in a new window. Tab order etc. 

Sending to testing approved.
