### ISSUE TITLE
Fix incorrect (standalone) placement of GA4 tag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3293]
#3106 originally implemented placing GA4 tags in the frontend. However, one thing in the definition of that issue was actually incorrect: The measurement ID that is placed in the snippet must _always_ be prefixed with `G-`.

The documentation is not very clear about this, but when looking in the Analytics settings, you can actually see that in the snippet the `G-` prefix is always present, also in the standalone version, not just when double tagging.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The measurement ID that is set in the `analytics-4` module should, when used in the frontend tag/snippet _always_ be prefixed with `G-`.
* In other words, instead of manually prefixing with `G-` only for double tagging (when integrating with a regular/UA Analytics snippet), the `$tag_id` set should itself have the `G-` prefix since it's never needed without it within the `Web_Tag` implementation.

## Implementation Brief

* Add the constructor to the `Modules\Analytics_4\Web_Tag` class that accepts two arguments: `$tag_id` and `$module_slug`.
  * Call the parent constructor passing the incoming `$tag_id` prefixed with `G-` and `$module_slug` variable as is.
* Remove `G-` prefix from the following format string: https://github.com/google/site-kit-wp/blob/8c341d37f0ba40d83ce5a8a067ac223f42c4f9d8/includes/Modules/Analytics_4/Web_Tag.php#L46

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check `includes/Modules/Analytics_4/Web_Tag.php` to ensure that:
  * the constructor method has been added as per the IB
  * the `enqueue_gtag_script` method has been updated as per the IB

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@eugene-manuilov IB looks good except if we're prefixing the `tag_id` in the constructor, we'd need to remove the prefix added in `Analytics_4\Web_Tag::enqueue_gtag_script`.

**Comment by eugene-manuilov** [comment]
Good catch @aaemnnosttv. IB is fixed.

**Comment by Hazlitte** [comment]
Hi @eugene-manuilov and @aaemnnosttv,
The IB says `Call the parent constructor passing the incoming $tag_id prefixed with G- and $module_slug variable as is.`
The `Analytics_4\Web_Tag` class extends `Analytics\Web_Tag`.  I have checked the parent class and it doesn't appear to contain a constructor.
