### ISSUE TITLE
Disable Google Analytics measurement per-property

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3294]
## Feature Description

Initially mentioned in #2211 (but not limited to that issue), now that Site Kit is aware of Analytics tags in Tag Manager containers and those the property IDs must match, we should be able to be more targeted with our disabling of Analytics measurement for logged-in users by using the property-specific method rather than complete opt-out. This would be preferable because the current method will disable all Analytics measurement for all properties on the page, including Site Kit's usage tracking on the front end but also tracking by other plugins, etc. rather than only the property configured in the Analytics &/or GTM modules.

See [Disable Google Analytics measurement](https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out)

For AMP, we may need to continue to use the same opt-out or simply change the output of the `amp-analytics` tag as it does not seem to support the same property-specific mechanism.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For non-AMP, Site Kit should no longer use the "catch-all" Analytics opt-out snippet, but instead print a more granular opt-out snippet, which affects only the specific Analytics properties configured in Site Kit:
    * In case tracking should be disabled for the current user, the `Analytics` module should print the `window['ga-disable-GA_MEASUREMENT_ID'] = true;` snippet (see [docs](https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out)) for the following measurement IDs:
        * The UA property ID.
        * The GA4 (web data stream) measurement ID, if one is set.
        * _If_ Tag Manager is active: The Tag Manager UA property ID (see Tag Manager's `gaPropertyID` setting), if one is set that differs from the UA property ID (currently not possible since the same one is enforced, but this will change in the future and the logic should already cater for it - no need to specifically QA it for now).
            * While this is related to the Tag Manager module, the Analytics opt-out is fully controlled by the Analytics module, so the logic should be kept together in here.
* For AMP, since a property-specific mechanism is not available, nothing should change from the current opt-out snippet.

## Implementation Brief

* In the `Analytics::print_tracking_opt_out` method:
  * Grab the current `accountID` and `propertyID` from the Analytics settings.
  * Replace `window["_gaUserPrefs"] = ...` code with `window['ga-disable-{$propertyID}'] = true;`.
  * Fire a new `googlesitekit_analytics_tracking_opt_out` action at the end of the method passing `propertyID` and `accountID` as action arguments.
* Add a new hook to the `Analytics_4` class for the `googlesitekit_analytics_tracking_opt_out` action that does the following:
  * Grabs the current `measurementID` from the Analytics_4 settings.
  * Renders a script with the following content if the `measurementID` is not empty:
    ```
    <script>window['ga-disable-{$measurementID}'] = true;</script>
    ``` 
* Add a new hook to the `Tag_Manager` class for the `googlesitekit_analytics_tracking_opt_out` action that does the following:
  * Grabs the current `gaPropertyID` from the `Tag_Manager` settings.
  * Renders a script with the following content if the `gaPropertyID` is not empty and doesn't equal `propertyID` passed to the hook params:
    ```
    <script>window['ga-disable-{$gaPropertyID}'] = true;</script>
    ``` 

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Enable `Analytics_4` and `Tag Manager` 
* In /wp-admin/admin.php?page=googlesitekit-settings#/connected-services/analytics/edit `Exclude from Analytics` > `All logged-in users`
* Load the home page in non amp mode while logged in and ensure that the three script tags from Implementation Brief are present just after `<!-- Google Analytics user opt-out added via Site Kit by Google -->`
 
## Changelog entry

* Update GA measurement opt-out mechanism for logged-in users to be property-specific.

**Comment by aaemnnosttv** [comment]
@felixarntz I think this one should still be possible due even with the change in course around how we will be handling existing tags in the future. My understanding is that we will no longer require Analytics and GTM to select the same property but the fact that we store the Analytics property ID now for GTM should still allow us to do this, even if they were different IDs, we may just need to add multiple opt-outs on the page 🤔

**Comment by aaemnnosttv** [comment]
>   * Execute the `googlesitekit_analytics_tracking_opt_out` action at the end of the method passing `accountID`, `propertyID`, and `profileID` as action arguments.

@eugene-manuilov this part was a little unclear. I think you mean to add this as a new action to fire here since this doesn't exist yet but just checking 🙂 

Regarding the parameters for it, the `profileID` isn't relevant since this is used for reporting only and has no presence on the front end. The `propertyID` is the only one I think is really needed so I think it makes sense to make that the first/primary value to the action. We could leave out the `accountID` as well unless it's really needed, in which case that could be the second argument.

Another important consideration about this action is that we probably want to scope it into the non-AMP case specifically (similar to how hooks in `Blockable_Tag_Interface` are web/amp-specific). That way, the other modules hooking in don't also need to check the AMP mode as it will be hook-specific, otherwise we'd be generating invalid AMP markup in an AMP context. Given that AMP needs the full opt-out still, we don't need to implement the AMP version of the same hook here just yet.

Otherwise this looks good to me 👍

**Comment by eugene-manuilov** [comment]
@aaemnnosttv IB is updated. Please, take a look.

> Another important consideration about this action is that we probably want to scope it into the non-AMP case specifically (similar to how hooks in `Blockable_Tag_Interface` are web/amp-specific). That way, the other modules hooking in don't also need to check the AMP mode as it will be hook-specific, otherwise we'd be generating invalid AMP markup in an AMP context. Given that AMP needs the full opt-out still, we don't need to implement the AMP version of the same hook here just yet.

Updated the action name to be `googlesitekit_analytics_web_tracking_opt_out`.

**Comment by aaemnnosttv** [comment]
> Updated the action name to be `googlesitekit_analytics_web_tracking_opt_out`.

Thanks @eugene-manuilov – I didn't actually mean the hook name should change, although I can see why you did. For cases where we have web/amp hooks, the web hook doesn't have `web` in the name, only the `amp` one is different (see `includes/Core/Modules/Tags/Module_Web_Tag.php`). I just meant that the firing of that hook should be guarded by the `! is_amp` condition rather than "at the end of the method" where it would always run for both.

I'll tweak this detail in the IB and then this is good to go!

IB ✅

**Comment by tofumatt** [comment]
Given another issue I've flagged as a Good First Issue involves tag output code, I think this one can be included in the Good First Issue label because the parts of the code base it touches and the QA steps are similar.

**Comment by wpdarren** [comment]
@ivankruchkoff would like a little clarification. I have `GA4` and `Tag Manager` enabled.  In GA settings: `Exclude from Analytics` is disabled for `All logged-in users` Is that correct? 

I go to the source code on the homepage while logged in (not AMP) and I do not see `<!-- Google Analytics user opt-out added via Site Kit by Google -->` 

Here is what I see.  

![image](https://user-images.githubusercontent.com/73545194/131518687-c3277764-2119-4c76-98f8-ce769b551534.png)

**Comment by ivankruchkoff** [comment]
@wpdarren , so you have analytics disabled for logged in users

<img width="475" alt="Screen Shot 2021-09-01 at 11 17 28 AM" src="https://user-images.githubusercontent.com/373931/131628873-3cca849b-551e-47d5-a0c9-678ce4c98734.png">

you are logged in when you view the site front end
<img width="549" alt="Screen Shot 2021-09-01 at 11 18 10 AM" src="https://user-images.githubusercontent.com/373931/131628928-f8a98334-6476-40ed-bad8-cd2e0a5406e2.png">

and you do not see the opt-out snippet in the page source?
<img width="846" alt="Screen Shot 2021-09-01 at 11 18 53 AM" src="https://user-images.githubusercontent.com/373931/131629045-cda55bcc-246d-434a-bcf8-6e32f52afdea.png">

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@ivankruchkoff I do now, can only put it down to user error!  I do have a question though, the QAB mentions 3 script tags but I am only seeing two.  I do not see anything for Tag Manager, but it is active. Reading the AC though it mentions that this might not be included at this time. I'd just like to make sure that no tag manager ID should not appear at this stage. 

When I load the home page in non amp mode while logged in the three script tags from Implementation Brief are present just after `<!-- Google Analytics user opt-out added via Site Kit by Google -->`


**Verified:**

1. The `window['ga-disable-GA_MEASUREMENT_ID'] = true;` snippet appears.
2. The `UA property ID` appears.
3. The `GA4 (web data stream) measurement ID` is set.

![image](https://user-images.githubusercontent.com/73545194/131670604-92d18843-bd42-4d92-8a12-7f804be33f60.png)

**Comment by ivankruchkoff** [comment]
It's two tags when the gtm tag is identical to the ua tag, three tags when the gtm tag differs from the ua tag.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:

The `window['ga-disable-GA_MEASUREMENT_ID'] = true;` snippet appears.
The `UA property ID appears`.
The `GA4 (web data stream) measurement ID` is set.
The  `GTM tag` appears when its different than UA
