### ISSUE TITLE
Automatically set related GA4 property if there is an existing GA4 tag with permission

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3297]
When there is an existing UA tag that the user has access to ("tag permission"), the UA property is automatically set in the `modules/analytics` store. The same should be implemented for GA4, automatically setting the GA4 property in the `modules/analytics-4` store if there is an existing GA4 tag that the user has access to (based on #3288).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `getAccounts` resolver in the `modules/analytics` store should be enhanced to also consider a potential existing GA4 tag **if the `modules/analytics-4` store exists**.
    * It should wait for the GA4 `getExistingTag` selector and, if there is an existing tag, for the GA4 `getTagPermission` selector.
    * If there is an existing GA4 tag and tag permission for it:
        * If there is no existing GA4 tag, the GA4 `selectProperty` action needs to be used to "enforce" the property. In that case, the "primary property type" also needs to be set to "ga4" (since the primary dropdown in the `ga4transitional` case needs to then be set to the enforced GA4 property).
        * If there also is an existing UA tag and tag permission for it, it also needs to be checked whether both properties from the existing tags belong to the same account. If so, the GA4 `selectProperty` action needs to be used to "enforce" the property.
* The GA4 `PropertySelect` component should be enhanced to have awareness of a potential existing GA4 tag. If there is one, the dropdown should be disabled (the above logic will already ensure that the correct GA4 property is set).
* The `PropertySelectIncludingGA4` component should be enhanced to have awareness of potential existing UA or GA4 tags. If there is either, the dropdown should be disabled (the above logic will already ensure that the correct UA and GA4 properties are set). If there are existing tags for both types, the expected behavior is that the UA property should be selected (since the default "primary property type" is "ua" anyway).

## Implementation Brief

In the getAccounts resolver:
https://github.com/google/site-kit-wp/blob/e186b3c60cd0ea6276c3e8b3b7470c26d942ddf8/assets/js/modules/analytics/datastore/accounts.js#L218

First check if ga4 is enabled: `if ( isFeatureEnabled( 'ga4setup' ) ) {`
If it is call `getExistingTag` from https://github.com/google/site-kit-wp/issues/3288 (this comes from `assets/js/googlesitekit/data/create-existing-tag-store.js`) similar to how we call it for the regular analytics store:
https://github.com/google/site-kit-wp/blob/e186b3c60cd0ea6276c3e8b3b7470c26d942ddf8/assets/js/modules/analytics/datastore/accounts.js#L227

If it returns `accountID` and `propertyID` (rather than `null` indicating no tag) call `getTagPermission` selector (also from #3288).

if the `accountID` matches the `UA` account ID 
https://github.com/google/site-kit-wp/blob/e186b3c60cd0ea6276c3e8b3b7470c26d942ddf8/assets/js/modules/analytics/datastore/accounts.js#L269

Call `selectProperty` action (`analytics-4`) on the `propertyID` via:
https://github.com/google/site-kit-wp/blob/e186b3c60cd0ea6276c3e8b3b7470c26d942ddf8/assets/js/modules/analytics-4/datastore/properties.js#L144

Call `setPrimaryPropertyType` action (`analytics`) with `ga4` via:
https://github.com/google/site-kit-wp/blob/e186b3c60cd0ea6276c3e8b3b7470c26d942ddf8/assets/js/modules/analytics/datastore/properties.js#L242

Update the `PropertySelect` component (see https://github.com/google/site-kit-wp/issues/3166 ) to disable the dropdown if `hasExistingTag` (similar to the non ga4 implementation) - https://github.com/google/site-kit-wp/blob/e186b3c60cd0ea6276c3e8b3b7470c26d942ddf8/assets/js/modules/analytics/components/common/PropertySelect.js#L81

Update `PropertySelectIncludingGA4` (introduced in https://github.com/google/site-kit-wp/issues/3246 ) to disable the dropdown if either a `UA` or `GA4` tag is present `hasExistingTag` on the `analytics` store and `hasExistingTag` on the `analytics-4` store.

### Test Coverage

Update the following tests as appropriate:

`modules/analytics/datastore/accounts.test.js` - with / without ga4 enabled
`modules/analytics-4/components/common/PropertySelect.test.js` - ensure disabled attribute works correctly
`modules/analytics-4/components/common/PropertySelectIncludingGA4.test.js`  - ensure disabled attribute works correctly

### Visual Regression Changes

Update the following stories as appropriate and add new screenshots:
`stories/module-analytics.stories.js`
## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
QA ✅

**Comment by felixarntz** [comment]
@tofumatt I'm sure you meant "IB" above? Sorry just wanted to ensure :)

**Comment by felixarntz** [comment]
I'm going to temporarily move this back to ACs. After revisiting this issue in regards to our newly defined approach for existing tag permission, we may be able to close this. I'll confirm tomorrow with @marrrmarrr.

cc @eclarke1 @fhollis If we close this, let's reassess capacity and whether there's anything else worth including in the sprint.
