### ISSUE TITLE
Anonymize your IP address data in Google Analytics

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#33]
Hello,
you should add the possibility to anonymize the IP address between the settings (Google Analytics) of the plugin, other plugins that integrate Analytics grant this possibility.

**Comment by jamesozzie** [comment]
#18

**Comment by jamesozzie** [comment]
Duplicate of #18

**Comment by sviluppomania** [comment]
@jamesozzie 
There is a solution?

**Comment by jamesozzie** [comment]
@sviluppomania I have marked this as an enhancement for further investigation on issue #18
