### ISSUE TITLE
Phase out some unnecessary legacy module fields

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3301]
Some of the fields which are part of each module's "info" (see `Module::setup_info`) are no longer relevant and therefore should be removed (from all modules and any related infrastructure). A few related enhancements should also be made.

This is not technically super-high priority, but it's a simple change, cleans up some code, and most importantly allows us to simplify the info that needs to be defined for the new `idea-hub` module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following `Module` info fields should be adjusted as specified:
* The `cta` field should be completely removed, including its `cta` value in the data prepared for JS.
* The `learn_more` field should be completely removed, including its `learnMore` value in the data prepared for JS.
* The `group` field should be completely removed.
* The `tags` field should be completely removed.
* It should be possible for the `homepage` field to be empty (that should also be the default set in the `Module` base class).
    * In other words, any place where the `homepage` field of a module is used for UI (there is only one, in the `SettingsActiveModule`'s footer) its surrounding UI should only be displayed if the field's value is truthy (i.e. don't display the link if `homepage` is false-y).

### `cta` field
- Inside `includes/Core/Modules/Module.php`, remove:
	- the `cta` field and logic from `parse_info` and from `prepare_info_for_js`
	- the `cta` comment from the class's doc block
- Remove any references in `Core/Modules/ModuleTest.php`, and make sure the tests pass.
- Remove the references in the individual Module classes, e.g.
	-  `includes/Modules/Optimize.php`
	- `includes/Modules/Search_Console.php` 
	- `includes/Modules/Idea_Hub.php` etc.

### `learn_more`, `group` and `tags` fields
- Follow the steps above for the `learn_more`, `group` and `tags` fields

### `homepage` field
- Inside `includes/Core/Modules/Module.php`, 
	- set the `homepage` assignment to an empty string in `parse_info`
- Refactor the logic in `assets/js/components/settings/SettingsActiveModule/Footer.js`
	- Don't display the `Link` if `homepage` is false-y

### Test Coverage

* Some unit tests may need refactoring to pass once these values are removed. No new tests required.

### Visual Regression Changes

* Images of the `SettingsActiveModule` footer may need updating for the scenario where `homepage` is falsey and the `Link` is not rendered.

## QA Brief

* Verify that the ACs above are fulfilled.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by asvinb** [comment]
Checked the Modules for the fields to be removed: ✅ 

### QA: ✅
