### ISSUE TITLE
The service is currently unavailable.

### ISSUE THREAD

**Issue by michaelserra** [google/site-kit-wp#331]
The service is currently unavailable.
Every Time I try to install I get this error.
![image](https://user-images.githubusercontent.com/53310376/61890145-de74b100-aed4-11e9-96db-928eceb8e433.png)

**Comment by jamesozzie** [comment]
@michaelserra Can you please try this workaround and let me know if you manage to get to the next stage, 

- Close the "Something went wrong" window
- Access [this](https://developers.google.com/web/site-kit/?firstplacefitnessequipment.com=yourwebsitecom&siteurl=https://firstplacefitnessequipment.com) link
- Press the "GET OAUTH CREDENTIALS" button
- Under "Select or create new project" click on "Create a new project" and press "Next"
- Fill in the fields such as "Project Name"
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

Can you let me know if the above resolves your issue. And if not please inform me if you are using G Suite.

**Comment by michaelserra** [comment]
This did not work. I am in G Suite.

*Michael Serra*
*First Place Fitness Equipment*
*Sales Rep.*
MSerra@FirstPlaceFitnessEquipment.com
904-998-0738 office
www.1PFE.com <http://www.1pfe.com/>

*Find A Location Near You Click Here!
<http://firstplacefitnessequipment.com/home/our-locations/>*

**Comment by hakkennce** [comment]
even i'm  facing the problem

**Comment by jamesozzie** [comment]
@michaelserra I suspect there could be security software / firewall settings restricting the ability to proceed, alternatively there could be restrictions on the creation of projects in Google Cloud Platform from within your G Suite account. 

Just to rule out this being a network/firewall issue can you attempt again using your browser in a new incognito window, preferably on a different machine?

Please also copy and paste any [console errors](https://i.imgur.com/f5WfLb3.png) if you see them and we can troubleshoot further.

**Comment by Schwarttzy** [comment]
Same boat, keep getting "Something went wrong, warning The service is currently unavailable."

**Comment by jamesozzie** [comment]
@Schwarttzy We can check for any G suite restrictions next. [Here](https://support.google.com/a/answer/9197205?hl=en) is a guide to enable Google Cloud Platform from G Suite. If you are not an administrator can you check with your admin to see Google Cloud Platform is enabled. 

On the page where you seeing the error message can you share any console error message.

**Comment by swissspidy** [comment]
Looking at https://status.cloud.google.com, it seems like there were some service disruptions yesterday.

Please try again today 🙂

**Comment by kaupok** [comment]
@swissspidy Still an issue.

![image](https://user-images.githubusercontent.com/3765564/61955621-11e23900-afc4-11e9-8981-edd2da264e96.png)

**Comment by michaelserra** [comment]
I have it up and running today... Seems it might have been service
disruptions.

*Michael Serra*
*First Place Fitness Equipment*
*Sales Rep.*
MSerra@FirstPlaceFitnessEquipment.com
904-998-0738 office
www.1PFE.com <http://www.1pfe.com/>

*Find A Location Near You Click Here!
<http://firstplacefitnessequipment.com/home/our-locations/>*

**Comment by swissspidy** [comment]
Excellent. I am closing this for now then.
