### ISSUE TITLE
PageSpeed Insights jump link no longer works on widget-based dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3310]
## Bug Description

After activating the PageSpeed Insights module, the success notification includes a link to "jump to the bottom" to where the module widget is to see the results. It seems that the related anchor/ID is no longer present in the widget-based version of the dashboard.

![image](https://user-images.githubusercontent.com/1621608/117338050-c94cf480-aea6-11eb-8848-3795b25c9750.png)

## Steps to reproduce

1. Ensure `widgets.dashboard` feature is enabled
2. Activate PageSpeed Insights
3. Click link to "jump to bottom"
4. Scroll position does not jump to PSI widget

## Additional Context

* Still works as expected in non-widget-based version of dashboard

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PageSpeed Insights jump link displayed after activation should work consistently in both widget and non-widget versions of the Site Kit dashboard
    * Clicking this link should "jump" down to the scroll position of the PageSpeed section and dashboard widget

## Implementation Brief

* Merge 3312

### Test Coverage

* No changes needed

### Visual Regression Changes

* No changes expected

## QA Brief

* Enable PageSpeed Insights
* Test that jump link works with `widgets.dashboard` on and off (may require mini plugin to disable)
* Ensure jump link works while report is loading as well as loaded

## Changelog entry

* Fix regression where jump link to PageSpeed Insights widget in success notification no longer worked.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the `Jump to the bottom of the dashboard to see how fast your home page is` link now jumps down to the page speed section on Site Kit Dashboard.
