### ISSUE TITLE
Update AdSense earnings widget layout on smaller viewports

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3317]
## Bug Description

On the `Earnings` widget for Google Adsense on Site Kit Dashboard, once you have large amounts in the data, the graphs start to look unreadable or not very useful, which does not make for a great user experience.  You can see from the screenshot below.  

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/978607d8-a924-4e47-ae57-dc31aede1542)

I am wondering if we should hide the graphs on small screen sizes, or look at the layout for the data?

Please note that the change values do not appear in this screenshot because I am using the tester plugin on this site.  You can see how it looks for smaller values as an example. [Screenshot](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/1330391a-d485-4bc8-aa79-40ece7dcca18)

## Steps to reproduce

1. Activate `Google Adsense` module with an account that has data (use Tester plugin)
2. Go to the `Site Kit Dashboard `
3. Scroll down to the `Earnings` widget and observe graphs. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense Earnings widget should be updated to adapt its layout on `phone` viewport sizes
* The layout should stack into 3 rows as follows:
	- Primary Metric
	- Sparkline
	- Change arrow and source link
* E.g.  
![image](https://user-images.githubusercontent.com/1621608/119130630-21f0c580-ba41-11eb-9461-ad66fc88dea5.png)
  _Note the change and source link should be vertically aligned in this adaptation as well_  
![image](https://user-images.githubusercontent.com/1621608/119130487-fa016200-ba40-11eb-8508-3b854844aa48.png)

## Implementation Brief

Using `_googlesitekit-data-block.scss` add mobile media queries to:
* set the `.googlesitekit-dashboard-adsense-stats &` section of `.googlesitekit-data-block` to:
  * a `flex-direction` of `column`
  * `align-items` of `normal`
*  align the content to the right in`.googlesitekit-data-block__change-source-wrapper`
Adjust the spacing to resemble the image in the AC. 

### Test Coverage

* n/a

### Visual Regression Changes

* Check and update visual regression tests

## QA Brief

1. Activate `Google Adsense` module with an account that has data (use Tester plugin)
2. Go to the `Site Kit Dashboard `
3. Scroll down to the `Earnings` widget and observe graphs.

The graphs should appear on a new row, unlike the screenshots above where they are awkwardly floated to the side.

## Changelog entry

* Improve AdSense graphs on mobile screens.

**Comment by aarondruck** [comment]
Maybe just drop the "Source: Adsense" below the $?

so layout could be something like:

Page RPM
$3.66 (chart)
Source: Adsense

... and so on

**Comment by felixarntz** [comment]
@aaemnnosttv @aarondruck Sounds good, let's do it like that!

**Comment by aaemnnosttv** [comment]
@aarondruck @felixarntz I've updated the ACs with an in-browser visual mockup based on your direction – let me know if you'd like to see anything differently here otherwise we can move this forward to IB 👍

**Comment by felixarntz** [comment]
LGTM!

**Comment by eclarke1** [comment]
@Hazlitte would it be possible to add an estimate here now the IB is completed please?

**Comment by eugene-manuilov** [comment]
> set the .googlesitekit-dashboard-adsense-stats to:
>   a flex-direction of column
>   align-items of normal

@Hazlitte the `.googlesitekit-dashboard-adsense-stats` class is added to the outer container of the widget and changes in it won't affect data block elements. We need to update styles of DataBlock elements.

**Comment by Hazlitte** [comment]
Thanks @eugene-manuilov, I just realised that I forgot to specify the `.googlesitekit-dashboard-adsense-stats &` section of `.googlesitekit-data-block`.  I have updated the IB.

**Comment by eugene-manuilov** [comment]
Thanks, @Hazlitte. IB :heavy_check_mark:

**Comment by tofumatt** [comment]
Tagging this as a good first issue—it will require setting up the Tester Plugin to get the AdSense data loaded, but the change itself is straightforward to make.
