### ISSUE TITLE
Legacy component console errors appearing when `widgets.moduleScreens` feature is enabled

### ISSUE THREAD

**Issue by johnPhillips** [google/site-kit-wp#3321]
## Bug Description

Console errors are appearing from legacy components on module screens when the `widgets.moduleScreens` feature is enabled. 

Example from the Analytics module screen:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in LegacyAnalyticsDashboardWidget
    in FilteredComponent (created by WithFilters(ModuleApp))
    in WithFilters(ModuleApp) (created by ModuleApp)
```

Looks like the issue might be because all the `index.legacy.js` files are still imported and therefore run even when this feature flag is on. 

https://github.com/google/site-kit-wp/blob/ef1a7e5d475953ff8dba4d00c02ddcf9e701b7f1/assets/js/modules/index.js#L22-L25

## Steps to reproduce

1. Enable the `widgets.moduleScreens` feature via the Site Kit Tester Settings plug in
2. Go to a module page (e.g. `/wp-admin/admin.php?page=googlesitekit-module-search-console`)
3. Open the browser console.
4. See errors.

## Additional Context

 - OS: Mac OS
 - Browser [Chrome, Safari, Brave]
 - Plugin Version [1.32.0]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @johnPhillips ! After looking into this I found that it is related to #3226 which is still in QA so I'm going to close this one out in favor of fixing it there 👍
