### ISSUE TITLE
E2E tests failing for E2E WordPress 4.9, Gutenberg 4.9

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3326]
## Bug Description

E2E tests are failing for `WordPress 4.9, Gutenberg 4.9` both on GitHub **and** running locally

The number of tests failing is consistent (on GitHub and locally)

```
Test Suites: 7 failed, 23 passed, 30 total
Tests:       7 failed, 76 passed, 83 total
```

## Steps to reproduce

See all the most recent PRs 
https://github.com/google/site-kit-wp/pull/3325
https://github.com/google/site-kit-wp/pull/3323
https://github.com/google/site-kit-wp/pull/3322
https://github.com/google/site-kit-wp/pull/3316

The same tests are always failing with `Object(...) is not a function` being logged, and thus getting

```
expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    [[Error: TypeError: Object(...) is not a function
```

*or* this message
    `Execution context was destroyed, most likely because of a navigation.`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by westonruter** [comment]
AMP <a href="https://github.com/ampproject/amp-wp/releases/tag/2.1.2">v2.1.2</a> is now published on WordPress.org

**Comment by aaemnnosttv** [comment]
Thanks @westonruter – I can see [this is passing again](https://github.com/google/site-kit-wp/runs/2608303535), so I'm going to close this out 👍  Cheers!
