### ISSUE TITLE
Change Device Legends to Title Case on All Traffic Widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3327]
## Bug Description

This is a UI improvement for the Device tab on the All Traffic widget within Site Kit Dashboard. 

Currently, on the legends, `desktop`, `mobile` and `tablet` are in lower case, but it would be good to have them in title case. This would then match the other legends on Channels and Locations.  From a conversation with Evan on Slack, it was discussed that a potential would be to make the change in CSS, since the legends come through like this from the Google Analytics API. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/d50f8368-9310-4948-947d-328da9eca938)

## Steps to reproduce

1. Go to 'Site Kit Dashboard'
2. Click on 'Device' tab.
3. See legends underneath the pie chart. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The descriptions in the legend for the different slices should be displayed in Title Case. 

## Implementation Brief
* Using `assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss`, update the `.googlesitekit-widget--analyticsAllTraffic__legend-slice` class name to have `text-transform: capitalize`.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Follow the steps to reproduce above and verify that the legends are now in Title Case.

## Changelog entry

* Update All Traffic widget legend slice labels to use title case.

**Comment by aaemnnosttv** [comment]
@aarondruck @marrrmarrr – this should be a simple change although I'm not sure if there is a reason these should be left as-is or not? From what I can see this is how they come back from the API so it doesn't seem like an intentional choice.

**Comment by aarondruck** [comment]
Title Case sounds good to me.

**Comment by tofumatt** [comment]
While it would be good to inventory our use of all-caps throughout the app (because all-caps are not very accessible), having things be consistent for now is good and that inventory should be all-encompassing.

So for now this sounds good, IB ✅

**Comment by aaemnnosttv** [comment]
> While it would be good to inventory our use of all-caps throughout the app (because all-caps are not very accessible), having things be consistent for now is good and that inventory should be all-encompassing.

@tofumatt this issue is about changing `mobile` to `Mobile` (title case), not all caps `MOBILE` – is that what you thought?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Confirmed that on the `Device` tab of the `All Traffic` widget, the legends are in title case. 

![image](https://user-images.githubusercontent.com/73545194/121688951-f26f2f00-cabb-11eb-8523-986dfe59ee5a.png)

- Tested this change on primary browsers and mobiles using Browserstack.
