### ISSUE TITLE
Oauth service not available

### ISSUE THREAD

**Issue by everything-it** [google/site-kit-wp#333]
Tried to set up activated plugin, but couldn't get past the 1st step. This is discouraging...

Maybe you need to test for existing Google accounts in the registration process? Because I have multiple accounts, which I now have a hard time navigating there are so many features...I was hoping that this would pull everything in to 1 place and make it easier...but not if it doesn't work. 

Also you may need to test for other installed and activated Google plugins (Google sitemap, Google analytics, etc) ...can they interfere at all? ...just wondering...as no mention of anything, and there is A LOT of Google stuff out there! :-O

**Comment by swissspidy** [comment]
There seemed to be some service disruption during the time of your report, which caused the plugin setup to not function properly.

Perhaps you could try it again today?

During the setup you can choose with which Google account you'd like to connect with.

**Comment by jamesozzie** [comment]
@everything-it Did you have any luck setting up Site Kit? If you share the error message or console error I can hopefully assist.
