### ISSUE TITLE
Tag Manager does not disable snippet when existing tag detected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3338]
## Bug Description

When an existing tag is detected (meaning it is output by something other than Site Kit) modules should disable their own snippet to avoid double tagging.

## Steps to reproduce

1. Configure a GTM tag to be output without using Site Kit for a container that your user has access to
2. Set up GTM, the existing tag should be detected and force the selection of its account and container
3. After setup is completed, check the output on the frontend to see both tags output for GTM

![image](https://user-images.githubusercontent.com/1621608/117842542-b3fd0f00-b286-11eb-8193-e6855217764d.png)

Alternatively, an existing tag detected after the module is setup when editing settings should cause the snippet to be disabled. No warning is currently shown in this scenario.

![image](https://user-images.githubusercontent.com/1621608/117842271-713b3700-b286-11eb-9386-44ff94e084f4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Tag Manager setup and settings edit components should automatically toggle off the module's snippet if an existing tag is detected and the tag matches the selected container ID, regardless of tag permissions

## Implementation Brief

* Update Tag Manager's custom `useExistingTagEffect` hook to set `useSnippet` to `false` if `hasExistingTag` similar to how it is done in the Analytics module, additionally checking for container ID match https://github.com/google/site-kit-wp/blob/29f4144035e710cbe8e9273f4509bc7b440ab189/assets/js/modules/analytics/hooks/useExistingTagEffect.js#L91-L93 

### Test Coverage

* Update `assets/js/modules/tagmanager/hooks/useExistingTagEffect.test.js` to cover this change

### Visual Regression Changes

* No changes expected

## QA Brief

1. First find out your GTM code, you can do this by setting up GTM as normal, then looking at the page source of your homepage, and seeing a code like:
GTM-XXXXXXX. Also note that the use snippet is ON.
2. Next update your theme or add a plugin to output your GTM code (change XXXXXX for your GTM code):
```php

<?php
add_action( 'wp_head', function() { ?>
        <script async src="https://www.googletagmanager.com/gtm.js?id=GTM-XXXXXX"></script> <!-- MANUAL -->
<?php });
```
3. Go to set GTM settings, you should see the use snippet toggle is off. - /wp-admin/admin.php?page=googlesitekit-settings#/connected-services/tagmanager/edit

<img width="738" alt="Screen Shot 2021-08-22 at 3 14 05 PM" src="https://user-images.githubusercontent.com/373931/130353048-d4513709-8272-4697-9102-09c943470743.png">

## Changelog entry

* Fix a bug where Site Kit did not disable Tag Manager tag when an existing tag was detected.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When Google tag manager is activated and the tag appears in the source code. The switch is enabled to add the code. 

![image](https://user-images.githubusercontent.com/73545194/130805046-b596755f-18e3-41bb-a67b-1a8dc0700673.png)

- When the Google tag is added as part of a plugin, the toggle is off in SK settings, and the message appears.

![image](https://user-images.githubusercontent.com/73545194/130804998-18e4d7f0-995c-4f66-8278-d84498bc574f.png)
