### ISSUE TITLE
Add `wp-prettier` to handle formatting of JS

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3340]
## Feature Description

[`wp-prettier`](https://www.npmjs.com/package/wp-prettier) is a fork of `prettier` – a very popular and opinionated code formatter which offers more robust formatting than our current capabilities with ESLint. It also integrates with ESLint though so the two can work together. The idea is that prettier makes for consistent code style automatically so that code review can focus entirely on the content of the changes rather than the style.

The fork is maintained by [Automattic](https://github.com/Automattic/wp-prettier) and used by Gutenberg so it's safe to assume it will be taken care of for the foreseeable future.

Adding this will likely require a very large initial diff if we also decide to format the entire codebase as part of the PR. Not doing so might introduce unrelated changes in subsequent PRs if the editor is configured to auto-format on save. Gutenberg uses it in their `lint-staged` configuration to format as a pre-commit action before linting which would be good to add as well to not rely on running it manually or editor-configuration. With that said, any 3rd-party integrations for prettier should also work because the executable keeps the same name (i.e. `node_modules/.bin/prettier` not `wp-prettier`).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* [`wp-prettier`](https://www.npmjs.com/package/wp-prettier) should be added as a dev-dependency
* The [ESLint configuration](https://github.com/google/site-kit-wp/blob/cf506108e8d41b9bfb0e2832b04409b7b50eaa3a/.eslintrc.json#L3) should be updated to extend `plugin:@wordpress/eslint-plugin/recommended` (as opposed to the current `recommended-with-formatting`).  
_See https://github.com/WordPress/gutenberg/blob/trunk/packages/eslint-plugin/README.md#usage for more information._
* All code should be formatted as part of this issue.  
**For this reason, this issue should be scheduled and executed in a way that minimizes disruption and conflicts for the rest of the team**

## Implementation Brief

* Install wp-prettier using `npm i --save-dev "prettier@npm:wp-prettier@latest"`
* Add Prettier to the VSCode Extensions recommendations file and add this file to the repo
* Add a new package script: `"lint:js-fix": "wp-scripts format-js"`
* Update to `plugin:@wordpress/eslint-plugin/recommended` in our ESLint config. This means our `lint-staged` script doesn't need to be updated, as ESLint will warn about linting errors and Prettier errors.
* Run `npm run lint:js-fix` to fix all errors.
* A few `// eslint-disable-line` comments need to be changed to be `// eslint-disable-next-line` because Prettier will move the comments to the next line, negating the ignore and causing ESLint errors. When testing, there were only a few (I think under 10) of these. 🙂 
* See #3768 for a draft PR that does everything here except the last two points regarding formatting and ESLint disable comments.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* `npm run lint:js` should output no errors.
* Modifying whitespace in the code and saving it (without editor auto-formatting) should show Prettier errors when running `npm run lint:js`. 
* Modifying whitespace in the code and saving it (without editor auto-formatting), then trying to commit said change, should result in `lint-staged` giving a Prettier error from ESLint.
* Using VSCode and the [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode), the editor should use the project-local Prettier and format code accordingly on save.

## Changelog entry

* N/A

**Comment by danielgent** [comment]
If there's any way I could upvote this issue then this is my upvote :heavy_check_mark: 

From both my own experience and watching the repo, there's a *lot* of back-and-forth with basic formatting issues that this could fix automagically

This is compounded by us being a distributed team and working with scrum (we can't just grab any ticket while waiting for a formatting fix in a CR)  :smile:

**Comment by aaemnnosttv** [comment]
@felixarntz @tofumatt @eugene-manuilov are you all happy with these ACs going forward? Anything to change, something we should do differently or include that's missing?

**Comment by eugene-manuilov** [comment]
Yes, looks good to me!

**Comment by tofumatt** [comment]
ACs look good to me as well, let's do it 👍🏻

**Comment by danielgent** [comment]
@tofumatt Makes total sense!  It'll make a big PR but will make everything much easier going forward :smile:

**Comment by felixarntz** [comment]
@tofumatt That makes sense to me - we need to time this well, but I agree, I'd prefer to have one disruptive change rather than afterwards making CR more complicated for many PRs to come.

If you agree @aaemnnosttv please amend the ACs accordingly - then we can move this forward.

**Comment by aaemnnosttv** [comment]
Sounds good to me @felixarntz 👍  My main concern was the timing and maybe we could avoid the mass update by letting Husky handle it in chunks but I've updated the ACs to mention that everything should be formatted as well as the importance of timing. Thanks all!

**Comment by tofumatt** [comment]
I've marked this as a 7 just because the formatting and QA might take some time and make this longer than a 3, but barely so. I think we can fit this into the end of this sprint, after #1997 and #2258 are merged.

**Comment by eclarke1** [comment]
@tofumatt I understand this ticket is one that needs to be carefully timed, so if we want to bring it into Sprint 54 let's definitely do this to cause as minimal disruption as possible. cc @fhollis

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt – I've also updated the AC to remove the point about applying lint fixes in the pre-commit hook for JS files as we had previously discussed.

IB ✅

**Comment by eugene-manuilov** [comment]
QA :heavy_check_mark: prettier works as expected.

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov Not sure if I'm missing something here, but is the Prettier configuration correct like we want? Didn't we use to have spaces in a lot more places than it's doing now? I'm a little confused by seeing the "corrections" it makes.

**Comment by aaemnnosttv** [comment]
@felixarntz what spaces are you referring to? The thing about Prettier is that it intentionally has almost zero configuration. Code can essentially only be formatted one way and that's the point. This is essentially why Automattic had to fork it to use WP code style since it differs from the original Prettier.

I agree that many of the changes it made are not as good as they were before in some places and some of the "decisions" it makes are a bit odd, but the tradeoff is that all JS everywhere will be consistently formatted now and it's no longer something we need to spend time on in CR. So it will probably look weird for a while but in the end should be a net positive.

Is that what you were asking about? 😄

**Comment by aaemnnosttv** [comment]
@felixarntz if you're not seeing the proper formatting (e.g. missing spaces), it may also be that you need to restart your editor, and if you're using VS Code you may need to install the extension (and/or ensure it's enabled) as well as set Prettier to be the default formatter 😄

**Comment by felixarntz** [comment]
@aaemnnosttv Thanks, I think this was purely an error on my end. The way the code now is formatted overall is good - at some point when I wrote my previous comment, my VS Code for some reason told me to remove spaces in places where there should be spaces. But I think that may indeed have happened only because I didn't restart the editor after pulling in those changes.
