### ISSUE TITLE
Weekday alignment for secondary date range to compare to

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3346]
In the Analytics service frontend, **on the overview page only**, the metrics that are shown in the graph use "weekday alignment", which means that the data which is being compared to is offset-ed so that every individual comparison date falls on the same weekday. This is naturally the case when we use date ranges that are a multitude of a week (e.g. last 28 days), but for other date ranges does not happen by default (e.g. last 90 days).

At some point, we've implemented "weekday alignment" in Site Kit, using it only in Analytics for the 90 day period specifically. This resulted in an inconsistent experience though, so per #2122 it was decided to remove this to rely on the more common default of not doing weekday alignment "forcibly".

This issue is to explore potentially re-allowing weekday alignment in a more consistent fashion, potentially controllable by the end user.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
The old weekday alignment code did have bugs and gotchas, and given this one has been stalled for three years I'm going to close it to help us triage issues 🙂 

This could be a bit of a nicety but isn't required and probably more trouble than it's worth 😄
