### ISSUE TITLE
`Cannot read property 'clicks' of undefined` error on Search Console widget-based dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3348]
## Bug Description

When viewing the Search Console dashboard, it is possible to encounter the following fatal error:

```
Cannot read property 'clicks' of undefined

    in Stats (created by ModuleOverviewWidget)
    in div (created by Widget)
    in div (created by Widget)
    in Widget (created by WithWidgetSlug(Widget))
    in WithWidgetSlug(Widget) (created by ModuleOverviewWidget)
    in ModuleOverviewWidget (created by WidgetRenderer)
    in WidgetRenderer (created by WidgetAreaRenderer)
    in div (created by Cell)
    in Cell (created by WidgetCellWrapper)
    in WidgetCellWrapper (created by WidgetAreaRenderer)
    in div (created by Row)
    in Row (created by WidgetAreaRenderer)
    in div (created by WidgetAreaRenderer)
    in div (created by Grid)
    in Grid (created by WidgetAreaRenderer)
    in WidgetAreaRenderer (created by WidgetContextRenderer)
    in div (created by WidgetContextRenderer)
    in WidgetContextRenderer (created by ModuleApp)
    in ModuleApp (created by GoogleSitekitModule)
    in GoogleSitekitModule
    in RestoreSnapshots (created by Root)
    in ErrorHandler (created by Root)
    in Root
```

The problem happens when the API returns an odd number of rows for a request that includes the previous range for comparison. This leads to an off-by-one situation when iterating over the previous data due to the way the rows are sliced.

https://github.com/google/site-kit-wp/blob/db4d6444f12e4185f1ff36e2602e3b6fe14a1fc6/assets/js/modules/search-console/components/module/ModuleOverviewWidget/Stats.js#L108-L115

The error happens right here because the `index` in the array of `previous` rows does not exist (because it was not returned from the API:

https://github.com/google/site-kit-wp/blob/db4d6444f12e4185f1ff36e2602e3b6fe14a1fc6/assets/js/modules/search-console/util/site-stats-data.js#L65

This is likely a matter of timing regarding when data is available as it is the very last (most recent) row which is missing
![image](https://user-images.githubusercontent.com/1621608/118090608-71e0e400-b3d2-11eb-82ba-6ac55f705018.png)

This request was for a 28 day range + compare which should have returned 56 rows (28 * 2), but instead it returned 55 (54 + 1 for the 0th row).

![image](https://user-images.githubusercontent.com/1621608/118091624-b4ef8700-b3d3-11eb-9098-ac678d865d0e.png)

## Steps to reproduce

1. Visit Search Console dashboard with empty cache
    - This depends on timing related to data availability from the API where the most recent day's data is not yet available 

## Additional Context

* Introduced in 1.30.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Search Console report data consumers should not assume an even number of rows when handling report data that includes the comparison range
* Values referenced in a missing row should use a zero value as a fallback

## Implementation Brief

* Finish and merge #3349 

### Test Coverage

* Add tests for `partitionReport`

### Visual Regression Changes

* There should be none, but possible if we a reference image based on a fixture that was based on an incomplete report
* Not likely though since this only seemed to affect the widget-based dashboard which does not have VRT coverage yet

## QA Brief

* All dashboards and widgets that display stats/charts with comparison data (i.e. previous range plot or change percent) should be checked to ensure no errors are present and things look as expected
* There was [one visual change in the Analytics audience overview chart](https://github.com/google/site-kit-wp/pull/3349#issuecomment-841155061) which resulted in slightly different data shown in the chart
* Ensure the above steps to reproduce do not result in an error
* Widget-based and legacy views/dashboards should be checked including different date ranges

## Changelog entry

* Fix potential `Cannot read property 'clicks' of undefined` JS error that could occur when an uneven number of Search Console report rows was returned.

**Comment by felixarntz** [comment]
IB ✅ 

@aaemnnosttv @eclarke1 @fhollis Let's squeeze this into the current sprint and upcoming release. A PR is already underway so this should be doable. If needed maybe we can postpone #3272 for the next sprint?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

As per conversation with @aaemnnosttv QA have run through a first pass for this ticket. 

- All dashboards and widgets that display stats/charts with comparison data have been checked.
- On widgets with tabs for different data, i.e. Audience overview, the comparison data/graphs were checked. 

[Screenshot 1](https://user-images.githubusercontent.com/73545194/118823927-4fa70480-b8b1-11eb-8765-208176f9f092.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/118823940-52a1f500-b8b1-11eb-8728-d76381127fb3.png) - [Screenshot 3](https://user-images.githubusercontent.com/73545194/118823962-559ce580-b8b1-11eb-8a20-dca9e53a6f89.png) - [Screenshot 4](https://user-images.githubusercontent.com/73545194/118823974-59c90300-b8b1-11eb-8be4-8c2e3351593b.png)

This testing was done on widget-based and legacy views/dashboards including different date ranges.

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren ! @felixarntz I asked @wpdarren to give this a first pass earlier in the week if they had capacity since we had some extra time while you were away. Given the timeliness around the release and the larger footprint of the PR I thought we could perhaps iterate on any regressions while we were waiting for the next round of CR. Luckily none were found 😄 

I think the only changes to the branch were additions to the test since Darren tested so this is probably good to go right to approval but I'll send it into QA just in case there is anything left to do.

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds good, let's bypass another round of QA then. cc @wpdarren
