### ISSUE TITLE
Implement `surveys` data store partial

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3355]
## Feature Description

The user data store will be the backbone of the user feedback surveys on the client, connecting components to the backend and handling client-side persistence as necessary.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/user` data store should be extended with a new `surveys` store partial which provides the following:
	* `actions.triggerSurvey( triggerID, options )`
		- `triggerID` should be a string and is **required**
		- `options` is an optional object.
		- `options.ttl` should be an integer for time in milliseconds. Defaults to `0`
		- When dispatched, this action should first check two conditions before making a request:
			1. If the `getCurrentSurvey` selector returns a survey, no further action should be taken
			1. Check a trigger-specific cache key (see `googlesitekit/api/cache`)
				- If it returns as a cache-hit – no further action should be taken (the value isn't currently needed but may be in the future)
				- If it does not return a cache-hit – a POST request should be made to `core/user/data/survey-trigger` with the `triggerID` as a POST data parameter
		* If the `survey-trigger` request is made successfully and the `ttl` is a positive value, a trigger-specific cache key should be set with the given `ttl` (`Number` in ms)
			- If the response includes a `survey_payload` and `session`, these should be received into the state as `currentSurvey` and `currentSurveySession` respectively but **only if they are not set yet** – that means that the store will only hold a single survey at a time for now regardless of the trigger
	* `actions.sendSurveyEvent( eventID, eventData )`
		- `eventID` should be a string and is `required`
		- `eventData` should be a plain object. Default: empty object
		- When dispatched, this action should make a POST request to `core/user/data/survey-event` with the following POST data:
			- `event` – plain object in the shape of : `{ [eventID] : eventData }`
			- `session` – plain object with `session_id` and `session_token` from `getCurrentSurveySession` selector
	* `selectors.getCurrentSurvey()`  
		This selector returns the current survey object which corresponds to the `survey_payload` which is received into the store as `currentSurvey`. If none, it should return `null`
	* `selectors.getCurrentSurveySession()`  
		This selector returns the current session object which corresponds to the `session` which is received into the store as `currentSurveySession`. If none, it should return `null`
* Server-side REST endpoints will be implemented in a separate issue
* Test coverage should be added for new actions and selectors

## Implementation Brief

Create a file `assets/js/googlesitekit/datastore/user/surveys.js`

Declare two stores:

`const fetchTriggerSurveyStore = createFetchStore...`
`baseName: triggerSurvey`
`controlCallback`: takes a param { triggerID }, calls API.set( 'core', 'user', 'survey-trigger') where the triggerID is passed through as a `POST` param.
`reducerCallback`: the endpoint returns `survey_payload` and `session`, add then to the state as `currentSurvey` and `currentSurveySession` if we don't have anything in the state for those two items.
`argsToParams` - specified to provide params to the controlCallback `(triggerID) => {triggerID}`

`const fetchSendSurveyEventStore = createFetchStore`
`baseName: sendSurveyEvent`
`controlCallback`: takes 2 params { event, session }, calls API.set( 'core', 'user', 'survey-event') and passes them as `POST` params `event` and `session`
`argsToParams` - specified to provide params to the controlCallback `(event, session) => {event, session}`

Create an initialState
```js
const baseInitialState = {
	currentSurvey: null,
	currentSurveySession: null,
};
```

In the `baseActions` add `triggerSurvey( triggerID, options )`:
Format for params:
```
triggerID should be a string and is required
options is an optional object.
options.ttl should be an integer for time in milliseconds. Defaults to 0
```

1. `select( STORE_NAME ).getCurrentSurvey()` - if this returns a non null, return.
2. If the above is null, call `getItem` `assets/js/googlesitekit/api/cache.js` with the cacheKey created via `createCacheKey` using the `triggerID` parameter.
3. If the `cacheHit` is `false`, call the action `yield fetchTriggerSurveyStore.actions.fetchTriggerSurvey( triggerID )`
4. If a valid response is received from the endpoint, call `setItem` with an empty object `{}`.

References:
https://github.com/google/site-kit-wp/blob/a8c59db9795753a42d9cd9bfaf6644f0fd71bc79/assets/js/googlesitekit/api/cache.js#L167
https://github.com/google/site-kit-wp/blob/a8c59db9795753a42d9cd9bfaf6644f0fd71bc79/assets/js/googlesitekit/api/index.js#L63

In the `baseActions`, add another action `sendSurveyEvent( eventID, eventData)`
```
eventID should be a string and is required
eventData should be a plain object. Default: empty object
```
The action calls the control callback with an `event` object (created by doing { [eventID]: eventData } ), and a session from `getCurrentSurveySession` this is an object with the following properties `{ session_id, session_token }`. This happens by calling the action from the `fetchSendSurveyEventStore` store. 
```js const { response, error } = yield fetchSendSurveyEventStore.actions.fetchSendSurveyEvent( event, session); ```

In the `const baseSelectors` add two selectors:
`getCurrentSurvey()` which returns the state's `currentSurvey`
and `getCurrentSurveySession()` which returns the state's `currentSurveySession`

### Test Coverage

Add your tests to `assets/js/googlesitekit/datastore/user/surveys.test.js` for the following:
Action - `triggerSurvey`
Action - `sendSurveyEvent`
Selector - `getCurrentSurvey`
Selector - `getCurrentSurveySession`

### Visual Regression Changes

* N/A

## QA Brief

This issue adds a few actions and selectors to the `core/user` store, which should mostly be covered by the added unit tests. They can also be tested somewhat in the browser but the underlying endpoints don't exist yet so the requests are expected to fail for now (which is fine)

* `await googlesitekit.data.dispatch( 'core/user' ).triggerSurvey( 'test' )` should result in a request
* `await googlesitekit.data.dispatch( 'core/user' ).sendSurveyEvent( 'test-event' )` should result in a request (but a survey with `session` needs to be manually received first or it will not) – e.g. dispatch first: `receiveTriggerSurvey( { session: {} }, { triggerID: 'test' } )`
* `googlesitekit.data.select( 'core/user' ).getCurrentSurvey()` should only return `null` for now (unless manually received – see above – although the value returned here would be set as the `survey_payload` in the received object)
* `googlesitekit.data.select( 'core/user' ).getCurrentSurveySession()` should only return `null` for now (unless manually received – see above)

## Changelog entry

* Add initial actions and selectors to `core/user` data store for handling user surveys.

**Comment by felixarntz** [comment]
@aaemnnosttv ACs mostly LGTM. I assume not depending on existence of the actual REST data points is fine since for the tests they'd get mocked anyway. Just two points of feedback:

> `actions.requestSurvey( triggerID, options )`

Let's keep this named as `triggerSurvey` as in the design doc and more closely following the related naming which is phrased around the `POST`ing action of triggering a survey rather than requesting one (which would be more of a `GET`).

> This selector returns the current survey object which corresponds to the `survey_payload` returned from the response of `requestSurvey` or `null` if none

Maybe worth clarifying here that it should return the _first_ survey? In theory there may be multiple surveys in state (and they're keyed by ID).

**Comment by aaemnnosttv** [comment]
> Let's keep this named as `triggerSurvey` as in the design doc

I only see `requestSurvey` in the doc – are we looking at the same one? 😄 

> Maybe worth clarifying here that it should return the _first_ survey? In theory there may be multiple surveys in state (and they're keyed by ID).

That's a good point, but if they're keyed by ID (trigger or survey ID?) then we should have a field to sort the values by to determine the order if not a simple list/queue. We shouldn't rely on order defined IMO.

**Comment by felixarntz** [comment]
@aaemnnosttv Oops my bad - I misremembered the design doc myself, but let's use `triggerSurvey` as it's more appropriate (updated this now in the design doc). 😆 

Regarding the order, I think we can revisit this in the future once there is a potential surface area to have multiple surveys at the same time. For now, the simple moment in time that the survey was triggered should suffice, i.e. the survey that's triggered first should be first.

So strictly, keying them by an ID (if we use one, let's use the trigger ID) isn't strictly necessary for now, although that may be helpful already for testing (e.g. look up by trigger). I'll leave it up to you to decide whether a simple list of surveys will do here for now.

**Comment by aaemnnosttv** [comment]
@felixarntz ready for another look over 👍

**Comment by felixarntz** [comment]
@aaemnnosttv LGTM!

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff – this is off to a good start; a few comments for you to iterate on:

> `const fetchCreateSurveyTriggerStore = createFetchStore...`
> `baseName: createSurveyTrigger`

This is probably an undocumented convention, but you should see all instances of `createFetchStore` are set using a variable that includes the `baseName` of the fetch store: https://github.com/google/site-kit-wp/blob/82bb1a9947fd7add1ceda4520404fa56d580aadd/assets/js/googlesitekit/data/create-notifications-store.js#L72-L73
Things are a little less clear for fetch stores for POST requests, but they should be pretty close. The variable names are purely for consistency of course, but the `baseName` influences the name of the actual actions that are built so this is much more important.

Let's update the `baseNames` for these to be `triggerSurvey` and `sendSurveyEvent` as this is also somewhat of a convention that these align with the names of actions that call them.

> `controlCallback`: takes a param `{ triggerID }`, calls `API.set( 'core', 'user', 'survey-trigger')`
> `controlCallback`: takes 2 params `{ event, session }`, calls `API.set( 'core', 'user', 'survey-event')`

In order for params to be available to the control callback, `argsToParams` needs to be provided to `createFetchStore` and `validateParams` should be added as well. Also, it isn't clear that `triggerID` is needed to be passed to the underlying API request. You don't need to fix the code here per se, but let's make it clear that the parameter should be sent through with the same name in the `API.set` call. 

> If the above is null, call getItem `assets/js/googlesitekit/api/cache.js` with the cacheKey created via `createCacheKey`

This is a good idea 👍  As far as the `queryParams` part of that call goes this should only have `triggerID` for now.

One thing which is missing is that the corresponding `setItem` needs to be manually called  if the `survey-trigger` request is successful. As mentioned in the ACs, the actual value isn't currently used, so curious if you have any ideas for what to use as that value, but otherwise an empty object would probably be fine.

Otherwise, the rest looks good although let's bump up the estimate a little bit to be on the safe side.

**Comment by ivankruchkoff** [comment]
@aaemnnosttv 

- Updated the estimate.
- Updated store base names.
- Added calls to `argsToParams`
- Explicitly stated post params `triggerID` and `event` / `session` respectively.
- Explicitly stated that `triggerID` is used for cache key.
- Added call to `setItem` with empty object. 

Given that we have a ttl, is it worth calling setItem with a ttl and the current time? I'm not sure what the ttl is used for and if we need to capture it via setItem in the cache.

**Comment by aaemnnosttv** [comment]
> Given that we have a ttl, is it worth calling setItem with a ttl and the current time? I'm not sure what the ttl is used for and if we need to capture it via setItem in the cache.

@ivankruchkoff the `ttl` essentially defines how long we should wait before the same trigger can be fired again. So currently the presence of the cache alone is all we need, the value isn't relevant yet but I think storing an object makes sense and allows for extending in the future, should we need to. 

> 3. If the `cacheHit` is `false`, call the endpoint `yield fetchCreateSurveyTriggerStore.actions.fetchCreateSurveyTrigger( triggerID )`

The fetch store and action names need to be updated here.

> The action calls the control callback with an `event` object (created by doing { [eventID]: eventData } ), and a session from `getCurrentSurveySession` this is an object with the following properties `{ session_id, session_token }`

I know what you mean by this but let's make it more clear that this action calls the respective action from its fetch store.

Otherwise, this is just about ready to go 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
Taking over the code review here in the interest of time since Evan won't be around Monday 🙂

**Comment by aaemnnosttv** [comment]
## QA ❌ 

Looks good overall, but a few things are missing:

* `triggerSurvey` does not send a request when `ttl` is `0`, but it should (it just doesn't set a "cooldown" cache value
* The cache key used for `triggerSurvey` references the `survey-event` datapoint instead of `survey-trigger`

I'll create a quick follow-up to fix.

**Comment by asvinb** [comment]
### QA: ✅ 

- `await googlesitekit.data.dispatch( 'core/user' ).triggerSurvey( 'test' )` results in a request being made. 
- `await googlesitekit.data.dispatch( 'core/user' ).sendSurveyEvent( 'test-event' )` results in a request being made after session is manually received.
- `googlesitekit.data.select( 'core/user' ).getCurrentSurvey()` returns `null` (session not manually received)
- `googlesitekit.data.select( 'core/user' ).getCurrentSurveySession()` returns `null` (session not manually received)
