### ISSUE TITLE
Incorrect use of `useMount`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3372]
## Bug Description

In #3072 we updated a number of `useEffect` hook instances to use `useMount` instead in order to satisfy the new linting rule which does not like an effect with an empty list of dependencies. While this has been a clean replacement in most instances, there are a few left over which are used improperly where a function is returned in the function given to the hook which is relevant for `useEffect`. However, `useMount` does not support this so the effect is essentially never cleaned up.

## Additional Context

* https://github.com/streamich/react-use/blob/master/docs/useMount.md

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instances of `useMount` with a function that returns another function as an effect cleanup should be updated to use `useEffectOnce` instead

## Implementation Brief

* Replace `useMount` with `useEffectOnce` hooks in the following files:
  * `assets/js/components/Menu.js`
  * `assets/js/components/Modal.js`

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check `Menu` and `Modal` components and verify that they don't use `useMount` hooks any more.

## Changelog entry

* N/A

**Comment by rbrishabh** [comment]
Hey @tofumatt, if you want, I can take this one up! You can review it when I come up with a solution. would that be helpful?

**Comment by tofumatt** [comment]
@aaemnnosttv @eugene-manuilov The IB mentioned changing `useMount` to `useEffect`, but I think we can use [`useEffectOnce`](https://github.com/streamich/react-use/blob/master/docs/useEffectOnce.md#useeffectonce) as mentioned in the ACs instead, so I modified the IB with that… but the approach looks right.

IB ✅

**Comment by tofumatt** [comment]
@rbrishabh Sorry but this issue, while straightforward, will be handled by the core development team as we need to land it in the upcoming release 🙂

**Comment by rbrishabh** [comment]
No problem! Thank you for your reply

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* All instances of `useMount` that had return functions for effect cleanup have been updated with `useEffectOnce` instead.
