### ISSUE TITLE
Clean up API quota error display

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3373]
## Feature Description

When quota rate limits are hit, the returned error message from the API currently returned on the **Create your Analytics account** screen as:

![image](https://user-images.githubusercontent.com/12189958/118682324-56108000-b7ce-11eb-9b55-c343bf2b6faa.png)

(screenshot from @wpdarren)

It looks significantly better on the Analytics screen when Analytics is already connected:

![image (1)](https://user-images.githubusercontent.com/12189958/118682583-95d76780-b7ce-11eb-94c1-3a1b15546775.png)

(screenshot from @adamsilverstein)

Can we clean up the error so it's properly escaped, etc. on all screens where it can appear and looks like Adam's screenshot?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
This is the same issue as raised on GA4 Bug Bashing, so bumping to P0 and adding GA4 epic.

**Comment by aaemnnosttv** [comment]
@felixarntz @adamsilverstein this is due to the way the response comes back from the server which is returning the error as encoded JSON rather than as the error itself.

Here is a quota error from creating a profile as seen by our API client (some headers omitted for brevity)
```
POST https://analytics.googleapis.com/analytics/v3/management/accounts/12345/webproperties/UA-12345-7/profiles

HTTP/1.1 403 Forbidden
Content-Type: application/json; charset=UTF-8
Server: ESF

{
  "error": {
    "code": 403,
    "message": "Quota Error: User Rate Limit Exceeded.",
    "errors": [
      {
        "message": "Quota Error: User Rate Limit Exceeded.",
        "domain": "usageLimits",
        "reason": "userRateLimitExceeded"
      }
    ]
  }
}
```

And here is the quota error when creating an account ticket

```
POST https://sitekit.withgoogle.com/analytics/v3/provisioning/createAccountTicket

HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Server: Google Frontend

{"error":"bad response code: 403\nResponse: {\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Quota Error: User Rate Limit Exceeded.\",\n    \"errors\": [\n      {\n        \"message\": \"Quota Error: User Rate Limit Exceeded.\",\n        \"domain\": \"usageLimits\",\n        \"reason\": \"userRateLimitExceeded\"\n      }\n    ]\n  }\n}\n"}
```

As you can see the top-level `error` is another Google Service error object which was encoded as a string.

It looks like this is an issue with the response from the Site Kit service rather than the way we handle it in the plugin.

**Comment by felixarntz** [comment]
@bethanylang Do you want to still keep this open for tracking purposes? I'll ping you on our Asana task; we can technically close this one since it's not a plugin issue

**Comment by bethanylang** [comment]
@felixarntz Yep, sounds good. Closing.
