### ISSUE TITLE
Implement User Surveys REST Controller

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3374]
## Feature Description

In #3355, we defined a number of actions that rely on REST endpoints that do not yet exist. This issue is for adding the necessary handling for those on the server side.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `Google\Site_Kit\Core\User_Surveys\REST_User_Surveys_Controller` class should be implemented, similar to the `REST_Feature_Tours_Controller`
	- Dependencies should be provided as needed via the constructor
	- Should have a test case added for it (see `REST_Feature_Tours_ControllerTest`)
* It should register the following REST routes and corresponding remote endpoints on the Site Kit service:
	* `POST:core/user/data/survey-trigger`
		- Requires a `triggerID` as a non-empty string request parameter
		- Forwards request to the Site Kit service as `POST:/survey/trigger/` with JSON-encoded body:
			- `site_id`: Current site ID.
			- `site_secret`: Current site secret.
			- `access_token`: Current user’s access token.
			- `trigger_context`: An object containing the following fields:
				- `trigger_id`: The trigger ID, as received from the client.
				- `language`: Current user's WP locale
		- Response should be returned back to the client
	* `POST:core/user/data/survey-event`
		- Requires an `event` object passed from the client
		- Requires a `session` object passed from the client with `session_id` and `session_token` fields
		- Forwards request to the Site Kit service as `POST:/survey/event/` with JSON-encoded body:
			- `site_id`: Current site ID.
			- `site_secret`: Current site secret.
			- `access_token`: Current user’s access token.
			- `session`: Object with `session_id` and `session_token` fields received from the client
			- `event`: Object with data passed from the client
		- Response should be returned back to the client
* All routes must require the user to be authenticated
* All routes require that the site is connected via the proxy

#### `Google_Proxy` class

* Add a new public method `send_survey_trigger( $credentials, $access_token, $trigger_id )`.
  * It should call the `Google_Proxy::request` method passing `/survey/trigger/` as the first argument, the incoming `$credentials` object as the second argument, and an array with the following fields as the third argument:
    ```
    'access_token' => $access_token`,
    'json_request' => true,
    'body' => array(
        'trigger_context' => array(
            'trigger_id' => $trigger_id,
            'language' => ... // current user locale
        ),
    ),
    ```
  * Return results of the `request` method call without modifications.
* Add a new public method `send_survey_event( $credentials, $access_token, $session, $event )`.
  * It should follow the logic from the `send_survey_trigger` method but use `/survey/event/` as the first parameter and the following array as the `body` property of the array passed as the third parameter:
    ```
    'session' => $session,
    'event' => $event,
    ``` 

#### `REST_User_Surveys_Controller` class

* Create a new class `REST_User_Surveys_Controller` in the `includes/Core/User_Surveys` folder. Use `REST_Feature_Tours_Controller` as an example in terms of registering routes, the methods to implement, etc.
  * Add a public constructor that accepts only the `Authentication $authentication` argument.
  * Add a new protected method `get_rest_routes` that returns an array of `REST_Route` objects for the endpoints defined in the AC. Each REST route should do the following:
    * Verify that the current user is authenticated (using `$authentication->is_authenticated()`) and proxy is used (using `$authentication->credentials()->using_proxy()`) in the `permission_callback` property.
    * Define the `args` property with the expected schema for the incoming arguments. See how we did it for the user input settings: https://github.com/google/site-kit-wp/blob/43dd2936086ea4b9bda71d038abb4b343fe981e5/includes/Core/REST_API/REST_Routes.php#L318-L348
    * Call the appropriate method of the `Google_Proxy` class (defined above) to send a request to the proxy server and return a response from it.
      * Use `Google_Proxy` class instance by calling `$authentication->get_google_proxy()` to get the instance of the `Google_Proxy` class.
      * Use `$authentication->get_oauth_client()->get_access_token()` to get the access token.
      * Use `$authentication->credentials()` to get the credentials object.
  * Add a new public method `register` that adds a new hook for the `googlesitekit_rest_routes` filter. The hook should merge the incoming $routes with the REST routes returned by the `get_rest_routes` method. See how it's done in the feature tours controllers: https://github.com/google/site-kit-wp/blob/43dd2936086ea4b9bda71d038abb4b343fe981e5/includes/Core/Feature_Tours/REST_Feature_Tours_Controller.php#L76-L81
* Register the `REST_User_Surveys_Controller` class in the hook for the `init` action defined in the `Plugin::register` method. You can do it like this: https://github.com/google/site-kit-wp/blob/43dd2936086ea4b9bda71d038abb4b343fe981e5/includes/Plugin.php#L191

### Test Coverage

* Create new phpunit tests for the `REST_User_Surveys_Controller` class. See `REST_Feature_Tours_ControllerTest` for inspiration on how to structure this file.
  * Ensure the ACs are met in these unit tests.

### Visual Regression Changes

* N/A

## QA Brief

* Check the `Google_Proxy` class and verify that it has two new public methods: `send_survey_trigger` and `send_survey_event`. Those methods should satisfy requirements defined for forwarded requests to the proxy server defined in the AC.
* Check the `REST_User_Surveys_Controller` class and verify that it registers two endpoints: `POST:core/user/data/survey-trigger` and `POST:core/user/data/survey-event`. Also, validate that those endpoints satisfy requirements defined in the AC and call the appropriate methods from the `Google_Proxy` class.

## Changelog entry

* Add REST routes for user survey endpoints.

**Comment by felixarntz** [comment]
ACs lgtm!

**Comment by eugene-manuilov** [comment]
> * It should register the following REST routes and corresponding remote endpoints on the Site Kit service:
>   * `POST:core/user/data/survey-trigger`
>     - Requires a `trigger_id` as a non-empty string request parameter
>     - Forwards request to the Site Kit service as **`POST:/survey/trigger/`** with JSON-encoded body: ...
>   * `POST:core/user/data/survey-event`
>     - Requires an `event` object passed from the client
>     - Requires a `session` object passed from the client with `session_id` and `session_token` fields
>     - Forwards request to the Site Kit service as **`POST:/survey/trigger/`** with JSON-encoded body: ...

@aaemnnosttv AC says to proxy `survey-trigger` and `survey-event` to the same `/survey/trigger/` endpoint. Is it intentional? Shouldn't `core/user/data/survey-event` request be proxied to the `/survey/event/` endpoint?

**Comment by eugene-manuilov** [comment]
@tofumatt it's a good start for IB however I think we need to provide more details. Here is what we need to clarify:
* which methods we need to add to the rest controller class;
* how we should validate the request data for each endpoint;
* how we should send a request to the proxy server;
* how we should process a response from the proxy server. What should happen when we get an error response from the proxy? etc.

**Comment by tofumatt** [comment]
Sounds good, I've updated the IB to be more explicit/specific about the methods to use for requests, etc. I omitted things like params and what to send to the proxy as they're already outlined thoroughly in the linked Google Doc, and didn't want to copy/paste them here since they're already available there.

One point is that the most obvious way to me to make HTTP requests to the Proxy in this case is using the private `request()` method, but… it's private. It's not clear to me _why_ such a method would be private given it's quite a useful thing to expose for other parts of the plugin that want to make requests to the proxy.

So I say we make it public, but I'll admit the layers of classes and the approach to the REST Client section of the plugin isn't intuitive to me and I might have that approach totally wrong. In the interest of time for the issue though, it might be better if I'm way off-base for someone more experienced to take it over, because I'm not sure I'm barking up the wrong tree—if I am I found nothing else that serves as the proper example for this approach. 😓

**Comment by aaemnnosttv** [comment]
> @aaemnnosttv AC says to proxy `survey-trigger` and `survey-event` to the same `/survey/trigger/` endpoint. Is it intentional? Shouldn't `core/user/data/survey-event` request be proxied to the `/survey/event/` endpoint?

@eugene-manuilov – yes, correct. I've updated it in the ACs, thanks for checking!

**Comment by eugene-manuilov** [comment]
> > One point is that the most obvious way to me to make HTTP requests to the Proxy in this case is using the private request() method, but… it's private. It's not clear to me why such a method would be private given it's quite a useful thing to expose for other parts of the plugin that want to make requests to the proxy.
> 
> > tofumatt I agree although I'm not sure if this was previously discussed (eugene-manuilov?). My guess is that it was made private by default since we didn't have a use for it outside of that class yet.

@aaemnnosttv @tofumatt this has been made intentionally. The Google_Proxy class implements [facade pattern](https://en.wikipedia.org/wiki/Facade_pattern) which provides an interface via its public methods to interact with the proxy server endpoints. The `request` method is an internal helper that encapsulates the common logic required to send a request to the proxy server and not intended for public usage.

> if the IB needs further iteration how do you feel about taking over and then assigning to me for review? The IB is looking pretty close at first glance, but as tofumatt said the issue is a bit timely and it's important we move this forward today.

Sounds good to me. IB is updated and ready for your review, @aaemnnosttv

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov !

The IB looks great for the added controller. I would like to see us potentially restructure the `Google_Proxy` class in the future so that we don't need to add new methods every time we add an endpoint but it's good for now. 

IB ✅

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov I've updated the ACs here to also require passing the `site_secret` to the proxy - originally it only required passing `site_id`. Looking at the PR #3440, this is already the case anyway (since the regular `Google_Proxy` method for sending a request does just that), so this doesn't require any additional work on the plugin side. I was gonna open a new issue, but it looks like that's not needed.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QAB?

**Comment by eugene-manuilov** [comment]
QAB is added.

**Comment by asvinb** [comment]
### QA: ✅ 

* `Google_Proxy` has 2 new methods defined as per AC.
* `REST_User_Surveys_Controller` registers 2 endpoints as per the AC.
* Required parameters enforced in `REST_User_Surveys_Controller`.
