### ISSUE TITLE
Implement a `CurrentSurvey` component

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3375]
## Feature Description

The `CurrentSurvey` component is the entrypoint for rendering the current survey (if any) for the user. It's responsible for retreiving the current survey from the `core/user` data store and rendering it at the top-most level.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `CurrentSurvey` component should be created as a functional, hook-based, connected component
* It should be added to the `Root` component so that it is rendered as part of every React app in Site Kit
	- A `userFeedback` feature flag should be added and used to conditionally render the `CurrentSurvey`
* Additionally, `CurrentSurvey` should only be rendered (or always return `null`) if the site is using the proxy (see `isUsingProxy` in `core/site`)
* It should use the `getCurrentSurvey` selector added in #3355 to retrieve the survey to render from the datastore, if any
	- If none, it should render `null`
	- If a survey object is returned, it should render a `Survey` component passing through the survey `question` and `completion` as `questions` and `completions` props respectively (see #3380)
	    - If `Survey` has yet to be implemented, an empty/placeholder component can be scaffolded in its place
* When rendering a survey, a React portal should be used to place the output as a direct child of the `<body>`
	- Survey elements should always appear in a fixed position at the bottom right-hand corner of the screen (with some distance from the edge of the browser) [as shown in the design](https://www.figma.com/file/CdBzWXXAlDFxJbgD6WGdz4/UserFeedback_PopupUI?node-id=1049%3A1125)
* Survey data and event handlers should be passed through to the rendered component as props as necessary

## Implementation Brief
* Once #3355 have been merged.
* Create new file `assets/js/components/surveys/CurrentSurvey` which exports the `CurrentSurvey` functional component.
* Update the `Root` component,
    * to conditionally render the `CurrentSurvey` component if the `userFeedback` feature flag is enabled by using the `useFeature` hook.
* Using the `CurrentSurvey` component,
    * Using the `useMount` hook, check if the site is connected via the proxy by querying the `core/site` data store via the `isUsingProxy` selector. If this is not the case, then render `null`.
    * Query the `core/user` data store via the `getCurrentSurvey` selector and use the logic defined in the AC if there is none or a survey returned.
* Styling the `CurrentSurvey` consists of only positioning the component to the bottom right of the user's screen with a `36px` spacing on the right and bottom. Child components rendered by `CurrentSurvey` will have their own styles.
* Rename the `Modal` component to `Portal` and update references to the `Modal` component to use `Portal`.
    * Add the `slug` optional prop which will should be added as class name to the dynamically generated element so that is easy to identify the portal for styling purposes. If a slug is provided, then the class name will be prefixed by `googlesitekit-portal-` and then the slug is appended.
* Within the `CurrentSurvey` component, use `Portal` to render the markup with the `slug` of the portal set to `survey`.
* All styles for the `CurrentSurvey` component should go in `assets/sass/components/survey/_googlesitekit-survey.scss`.
* Any class names used in the component should follow the BEM methodology, with the `googlesitekit-survey` prefix.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Run storybook locally via the `npm run storybook` command.
* Visit the `Components -> Surveys -> CurrentSurvey` story.
* Inspect the code and ensure that we have an element with the following class names: `googlesitekit-portal-survey googlesitekit-plugin` as a direct child of `body`.
* `Scaffolded Survey component` should be displayed to the bottom right of the page.

## Changelog entry

* Implement a component to render the current survey.

**Comment by felixarntz** [comment]
@aaemnnosttv In order for this to not depend on #3380 (which I think is the intent here), it would be good to clarify more precisely the requirement for the `Survey` component that is referenced. Either we need to mark the issue as blocked by that component one's, or we can add here that the empty `Survey` component should be scaffolded, and slightly rephrase #3380 to actually implement that scaffolded component.

**Comment by aaemnnosttv** [comment]
@felixarntz ready for another pass 👍

**Comment by felixarntz** [comment]
LGTM!

**Comment by asvinb** [comment]
@aaemnnosttv About the following line:
> Survey elements should always appear in a fixed position at the bottom right-hand corner of the screen (with some distance from the edge of the browser) as shown in the design

The styling would be done in #3379 . Just wanted to flag that out here or you wanted to style `CurrentSurvey` only for the positioning?

**Comment by aaemnnosttv** [comment]
> > Survey elements should always appear in a fixed position at the bottom right-hand corner of the screen (with some distance from the edge of the browser) as shown in the design
> 
> The styling would be done in #3379 . Just wanted to flag that out here or you wanted to style `CurrentSurvey` only for the positioning?

I think this aspect of the styling could be done here since these styles are specific to the elements that are rendered in the survey modal. All the other components/issues shouldn't need to be concerned with positioning of the survey. 

---

Thanks @asvinb – this is looking good, just a few points to iterate on:

> * Once #3355 and #3380 have been merged.

This issue only depends on #3355 – the ACs state that an (empty) `Survey` component can be scaffolded if it isn't implemented yet.

> * Taking the code from the `Modal` component as example, render the `CurrentSurvey` component in a React portal which should be the direct child of `<body>`.

Maybe it would be better to make `Modal` more flexible rather than duplicate most of it?

**Comment by asvinb** [comment]
@aaemnnosttv Ready for you to take another look.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb – super close, just a few final details.

> * Render the `CurrentSurvey` component as a child of the `Portal` component 

`CurrentSurvey` is a child of the `Root` so the `Portal` should be rendered inside `CurrentSurvey` instead.

> * Add the `slug` optional prop which will should be added as class name to the dynamically generated element so that is easy to identify the portal for styling purposes.

Minor detail, but how about we apply the same class naming for `Portal` as we do for widgets and widget areas?

E.g. https://github.com/google/site-kit-wp/blob/4b211be1ef2c6b805cc3429f5b099c44abe01739/assets/js/googlesitekit/widgets/components/Widget.js#L36-L37
https://github.com/google/site-kit-wp/blob/4b211be1ef2c6b805cc3429f5b099c44abe01739/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L90-L91

Just replace `widget(-area)?` with `portal` 😄

**Comment by asvinb** [comment]
@aaemnnosttv I may have incorrectly phrased it in the IB but that's what I meant when I said:
> Render the CurrentSurvey component as a child of the Portal component
I've changed the wording, let me know if that works now :)
+1 for the suggested class name. IB updated.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb!

IB ✅

**Comment by aaemnnosttv** [comment]
@asvinb quick note: one thing that I remembered is that we'll need to make sure that our element added to the `document.body` needs to also have a `googlesitekit-plugin` class since all of our styles are scoped by it.

**Comment by asvinb** [comment]
> @asvinb quick note: one thing that I remembered is that we'll need to make sure that our element added to the `document.body` needs to also have a `googlesitekit-plugin` class since all of our styles are scoped by it.

👍

**Comment by danielgent** [comment]
So I see it a little different to the QA brief
`Inspect the code and ensure that we have an element with the following class names: googlesitekit-portal-survey googlesitekit-plugin as a direct child of body.`

Instead I see something like
```
<body>
	<div id="root">
		<div class="googlesitekit-plugin-preview js">
			<div class="googlesitekit-plugin">
				<div class="googlesitekit-portal-survey">
					<p>Scaffolded Survey component</p>
					```
					
**BUT** I don't see the DOM structure in the QA brief mentioned in the AC, IB, or comments, so I'm going to assume that this isn't a problem :smile: 

_**QA**_ :heavy_check_mark:
