### ISSUE TITLE
Implement a `SurveyViewTrigger` component

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3376]
## Feature Description

User surveys require a trigger to be dispatched which may or may not result in a survey to be displayed. The first trigger that we will need is a view trigger. The easiest way to add this is by adding a dedicated component that triggers a view when it is first mounted. This requires the `triggerSurvey` action implemented in #3355.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `SurveyViewTrigger` component should be added which when rendered dispatches `triggerSurvey` with the necessary arguments provided via props, but should only do so **once**, when initially mounted
	- Should require a `triggerID` prop as a string
	- Should accept an optional `ttl` prop as a number
	- Should only call `triggerSurvey` if the site is connected via the proxy (see `isUsingProxy` via the `core/site` store)
* Should be added to trigger a survey when the main Site Kit dashboard is rendered
	- `triggerID` must be `view_dashboard`
	- `ttl` should be 1 hour in milliseconds
	- Should be conditionally rendered based on the enabled state of the `userFeedback` feature flag

## Implementation Brief
* Create `assets/js/components/surveys/SurveyViewTrigger.js` which exports the `SurveyViewTrigger` functional component with the props defined in the AC.
* Using the `useMount` hook, check if the site is connected via the proxy by querying the `core/site` data store via the `isUsingProxy` selector.
    * If this is the case, then dispatch the `triggerSurvey` action passing the `triggerID` prop and `ttl` prop as parameters.
* Using the `DashboardApp` component,
    * Check if the `userFeedback` feature flag is enabled by using the `useFeature` hook.
    * If this is the case, then render the `SurveyViewTrigger` component with the prop values defined in the AC.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Check that new components have been created, and changes implemented, as per the AC above

## Changelog entry

* Add React component for triggering a user survey on view.

**Comment by felixarntz** [comment]
@aaemnnosttv Do we need a flexible component like this just to call the `triggerSurvey` action? Since the particular `view_dashboard` trigger is on page view, using a component might make sense, but the intent of `triggerSurvey` is more of an event-based system, i.e. it could eventually be called directly in the related logic, the same way `trackEvent` works.

Maybe instead of starting with the abstraction we could create a specific `ViewDashboardSurveyTrigger` component or so?

I'm not saying your approach is worse, but it could raise false expectations that this is the de-facto way to use `triggerSurvey` and may not be necessary at this point.

**Comment by aaemnnosttv** [comment]
> @aaemnnosttv Do we need a flexible component like this just to call the `triggerSurvey` action?
Since the particular `view_dashboard` trigger is on page view, using a component might make sense, but the intent of `triggerSurvey` is more of an event-based system, i.e. it could eventually be called directly in the related logic, the same way `trackEvent` works.

I think it makes sense for a view-specific trigger. I would imagine most other triggers would be closer to the actual event, much like `trackEvent`. In this case, there is no clear event that equates to a view. We could technically trigger this on page load on the server side, but that doesn't mean the user actually saw it. Of course I'm not suggesting we do that but I think the component is a good place to draw the line since it wouldn't be invoked on a redirect and we don't need it to happen as soon as possible that we'd move it outside of React. In this case, I think even slightly delaying it makes it closer to an actual "view".

> Maybe instead of starting with the abstraction we could create a specific `ViewDashboardSurveyTrigger` component or so?
> 
> [...] it could raise false expectations that this is the de-facto way to use `triggerSurvey` and may not be necessary at this point.

That's okay with me but I don't think it necessarily sets the standard for how `triggerSurvey` should be used. If anything, it sets the example for how to use it for a view-specific trigger. Given that we only have a single trigger, maybe that has some influence on how `triggerSurvey` is seen to be used but I don't think we're at risk of this becoming a pattern to use for all cases if that's what you mean. If you'd prefer to have it as a one-off special component to start with that works for me 👍 

Let me know if that's what you'd like instead and I'll update the ACs.

**Comment by felixarntz** [comment]
@aaemnnosttv Those are fair points, we can go with your original ACs then.

**Comment by asvinb** [comment]
@aaemnnosttv Just a note about this line:
> Should only call triggerSurvey if the site is connected via the proxy (see isUsingProxy via the core/user store)

It should be the core/site store if am not mistaken 😁

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by danielgent** [comment]
@eugene-manuilov  I"m not sure what else to add :thinking: 

I haven't tested this at all (thus all my problems with not using the correct method signature for `triggerSurvey`) 

Is this all hooked up and working? I don't think so!

**Comment by eugene-manuilov** [comment]
Ok, in this case, we need to add `QA: Eng` tag.

**Comment by asvinb** [comment]
### QA: ✅ 

Component implemented as per AC.
