### ISSUE TITLE
Tag Manager setup stories are broken

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3381]
## Bug Description

Currently all of our stories for Tag manager setup are broken. I opened #3378 earlier to prevent this in the future but this issue is just about fixing these (and any others we might have right now) which is likely a simple fix.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/118810463-977b5b00-b8b4-11eb-8537-2b82c69de170.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No stories should be broken (i.e. displaying the Storybook red/black error boundary as shown above)

## Implementation Brief
* Update all stories in `stories/modules-tagmanager-setup.stories.js`, to have the `registry` variable destructured in the second parameter of the `add` function. The first parameter can be named `args` and it'll be unused. For e.g"
```js
.add( 'Loading', ( args, { registry } ) => {
```

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Run storybook locally via the `npm run storybook` command.
* Check if the "Tag Manager Module -> Setup -> *" stories load correctly without any errors.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Went through all of the Storybook stories on my local site and no errors occurred. 

![image](https://user-images.githubusercontent.com/73545194/121534391-161d7100-c9f9-11eb-9dcf-adfc051cdd54.png)
