### ISSUE TITLE
multiple domains setups

### ISSUE THREAD

**Issue by Bobby99as** [google/site-kit-wp#3388]
## Feature Description

allow a setting to make it where it stops complaining about URL changes for multiple domains setups. I have a clarinet and a tor domain and I'm getting sick and tired of it complaining about the URL changing. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reaching out. At present Site Kit is intended to be used on a single domain, in particular as this domain is used for reporting purposes within the various Google services. For this reason any changes to the URL will result in the notice you're encountering. 

I can also discuss your feature request with the team if you'd like to explain more on your particular setup, including the format of your domain and URL changes.

**Comment by jamesozzie** [comment]
@Bobby99as Just following up with you on this. If you can share details of your particular setup I'd be happy to try and recreate or discuss further with the team.

**Comment by bethanylang** [comment]
@bobby99as Checking in again here. It would be great to get some more details from you so that we can discuss next steps on our side. Thanks!

**Comment by Bobby99as** [comment]
> @Bobby99as Checking in again here. It would be great to get some more details from you so that we can discuss next steps on our side. Thanks!

Sorry I don't really have anything else to say except having it stop bothering people that have a website running on multiple domains like a .com and then a .onion because that would be rather nice instead of having to relink it when I go to my admin panel on my tor side instead of my .com one

**Comment by jamesozzie** [comment]
Thanks for the update @Bobby99as 

There is a canonical filter (googlesitekit_canonical_home_url) that can be used to ensure the Site Kit connected URL doesn't change. You can use [this mini plugin](https://gist.github.com/adamsilverstein/199f3a4cfe8b4ccc881713a7ece05438) on your main site. Can you inform me if this works for you with your particular setup?

**Comment by jamesozzie** [comment]
As we didn't get a response I'll closing this GitHub issue. Feel free to reopen if you'd like some assistance setting up the canonical filter or using the mini plugin, which can ensure Site Kit remains connected to a single defined URL.
