### ISSUE TITLE
Cannot read property 'activateModule' of null

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3389]
There have been a couple of Site Kit users who reported the below error, unknown at what stage so far, troubleshooting ongoing:
`Cannot read property 'activateModule' of null`

- https://wordpress.org/support/topic/site-kit-encountered-an-error-35/ | **Resolved - no response or additional insights** | SH info within topic
- https://wordpress.org/support/topic/site-kit-encounterred-an-error/ | **Resolved - no response or additional insights** | No SH info provided

## Steps to reproduce

Unknown so far

## Additional Context

 - Latest occurrence is with Site Kit 1.32.0. this site has no publicly accessible REST endpoints (awaiting  further insights)

 ## Insights & Troubleshooting Checks performed 

- [ ] Health Check & Troubleshooting plugin check
- [x] Front end check (mixed content, minified content, combined JS)
- [x] Incognito mode - the same occurs
- [x] Checked users Site Health info, no obvious  cause 
- [x] Additional .htaccess rules applied - True
- [x] Confirmed no modification of Site Kit placed snippet
- [ ] Uninstalled and reinstalled plugin
- [ ] User confirmed no "Critical errors" in their Site Health status
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Reset Site Kit (on the SK service)
- [ ] Reset previous site records (on the SK service)
- [ ] Disconnected Site Kit
- [ ] Disconnected impacted service and connected once more
- [ ] Checked does the same occur from another admin users account
- [ ] Checked setup / viewing dashboards from another WordPress administrator account
- [ ] Modified WordPress site settings (switching https > http, logging in once once more & reverting to https)
- [ ] Reviewed error logs 
- [ ] Reviewed XHR requests 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@jamesozzie Should this be assigned to you or @abdullah1908 for initial testing?

**Comment by jamesozzie** [comment]
@bethanylang I'm awaiting additional insights from impacted users in order to try and recreate.

**Comment by bethanylang** [comment]
@jamesozzie Assigned to you as you were waiting for more details from other users.

**Comment by abdullah1908** [comment]
By inspecting [SH info](https://wordpress.org/support/topic/site-kit-encountered-an-error-35/) I can see few plugins related to optimization/cache. Installed those plugins along with Astra & I can see some [JS errors in Page Speed](https://imgur.com/undefined) section. One thing that I noticed over the user website is their website [rest route is disabled](https://imgur.com/a/6fhGlQp).

**Comment by jamesozzie** [comment]
@bethanylang No additional insights or impacted users. One of the impacted users sites are not long active. Thoughts on keeping this open or closing as unreproducible?

**Comment by bethanylang** [comment]
@jamesozzie Closing for now, but of course let's revisit if we get more reports.
