### ISSUE TITLE
Link Behaviour on Create a Goal CTA on SK Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3392]
## Bug Description

On the Site Kit dashboard, when you click the `Create a Goal CTA` link, it opens up in the same window.

To be consistent with external links, the link should open in a new window. 

![image](https://user-images.githubusercontent.com/73545194/119342159-8f446680-bc8c-11eb-99b2-1e91668624ca.png)

## Steps to reproduce

1. Make sure `Google Analytics` is connected
2. Go to Site Kit Dashboard 
3. Scroll down to `Create a Goal CTA`
4. Click on the link 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of #3683 which addresses the same thing 👍
