### ISSUE TITLE
Improve User Experience When Disconnecting Modules in Settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3393]
## Bug Description

When you are disconnecting two or more modules within the settings page the user experience could be improved. 

Currently, when you disconnect a module you are redirected to the Site Kit Dashboard after it is disconnected. You then have to go back into the settings, select another module to disconnect and repeat. Rather than redirecting to the dashboard, could the user not be redirected back to the settings page?

https://user-images.githubusercontent.com/73545194/119343778-d03d7a80-bc8e-11eb-97a5-80020ff12f8a.mov

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a user successfully disconnects a module, do not redirect to the main dashboard; remain on the Settings page.

## Implementation Brief

Using `ConfirmDisconnect` rename the `dashBoardURL` constant to `settingsURL` and change it's `select` value to `getAdminURL( 'googlesitekit-settings' )`

Update the `handleDisconnect` function to use the new`settingsURL` constant instead of `dashboardURL`.

### Test Coverage

* n/a

### Visual Regression Changes

* n/a

## QA Brief

* Connect a couple of modules in Site Kit
* Disconnect both modules and after each disconnection completes check that the browser is redirected back to the settings page rather than the dashboard

## Changelog entry

* Update settings to redirect back to the settings page after disconnecting a module.

**Comment by eclarke1** [comment]
@Hazlitte would it be possible to add an estimate here now the IB is completed please?

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by cole10up** [comment]
**### QA ✅**
Confirmed disconnecting every module after setup remains on the settings page.

Verified fixed.
