### ISSUE TITLE
Make module's data response parser method aware of request data

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#340]
## Feature Description

This is a technical enhancement addressing an architectural shortcoming, most recently noticed in #335, but also in other areas of the codebase touched during the original PHP refactoring. Here's the problem:

* Google API requests are handled in two areas: There's a `create_data_request()` method and a `parse_data_response()` method. This separation exists so that batching can efficiently be done while still allowing the responses to be parsed correctly.
* The `create_data_request()` method receives the request data passed via a `$data` parameter, which is obviously crucial to handle the request.
* The `parse_data_response()` method doesn't receive that request data, so it doesn't have access to it. This is fine in 95% of cases, since it should only modify the response received from the Google APIs. However, there have been a few cases which have proven that access to the originally passed request data is occasionally necessary for correctly parsing the response. These cases currently "hack" around this by setting the needed parameter value in an internal property temporarily, to reaccess it later. This is error-prone, and now that we've established it has multiple cases where the data would be needed, we should fix this architectural shortcoming.

Long story short, `parse_data_response()` should receive the original request data as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All usages of the `parse_data_response()` method (in any module) which access request data should do so via a `$data` parameter passed to that method instead of relying on an internal class property with a temporarily-set value.
* General sanity testing needed: Check Site Kit dashboard and individual module pages and verify that requests still work as expected.

## Implementation Brief

* Add a `$data` parameter as fourth parameter to the `parse_data_response()` method (https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L409), with similar behavior like the homonymous parameter in `create_data_request()`.
* To cover singular requests, pass the `$data` variable to the method call in https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L409.
* To cover batch requests, ...
    * Set the assigned value in https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L315 to `array( $datapoint, $data )`.
    * Rename `$datapoint` to `$args` in https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L323, and add a line below: `list( $datapoint, $data ) = $args;`.
    * Change `! is_string( $results[ $key ] )` to `! is_array( $results[ $key ] ) || count( $results[ $key ] ) !== 2` in https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L337.
    * Change https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L341 to `list( $datapoint, $data ) = $results[ $key ];`.
    * Pass the `$data` variable now accessible from there to the method call in https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L345.
* Update `parse_data_response()` to include the `$data` parameter in the method signature in all six module classes, according to the base class.
* Fix ugly workarounds currently used to properly use the `$data` parameter:
    * In `Search_Console`'s `siteverification-list` route: Get rid of internal `$_siteverification_list_data` property and instead get that value from the now available `$data` method parameter.
    * In `TagManager`'s `list-accounts` route: Get rid of internal `$_list_accounts_data` property and instead get that value from the now available `$data` method parameter.
    * If #83 has been merged by now: In `Analytics`'s `get-accounts` route: Get rid of internal `$_existing_tag_account` property and instead get that value from the now available `$data` method parameter.
* Add basic PHPUnit test coverage for data infrastructure in modules:
    * Augment the existing `FakeModule` to provide a simple `GET` and `POST` datapoint that don't make any API requests. Both endpoints should have logic executed in `create_data_request()` and `parse_data_response()`.
    * Enhance the existing tests for `get_data()`, `set_data()`, and `get_batch_data()` in `ModuleTest` to ensure they actually handle these requests correctly (currently they really only check method signature, which is too basic).

## Changelog entry

*

**Comment by ThierryA** [comment]
@felixarntz do we currently have unit tests covering these methods. I suggest update the tests to fail when the current bug occurs and make sure it passes once the new implementations is done?

**Comment by felixarntz** [comment]
@ThierryA We don't currently have tests for that because it's quite complex to determine a solution on testing all the datapoints (with them making external API requests). However, I agree we should add basic coverage to make sure the `create_data_request()` + `parse_data_response()` infrastructure works as expected for both singular and batch requests. There is a `FakeModule` class already used for basic PHPUnit tests, which we could implement a very basic datapoint in for testing, that doesn't make an API request. That would allow us to test the behavior. I added this to the implementation brief.

**Comment by ThierryA** [comment]
> We don't currently have tests for that because it's quite complex to determine a solution on testing all the datapoints (with them making external API requests)

Considering that Unit Tests typically don't make external API requests but mock responses with the appropriate data structure using dummy data, we should have that at least for the endpoints we use. 

> which we could implement a very basic datapoint in for testing, that doesn't make an API request. That would allow us to test the behavior. I added this to the implementation brief.

👍

**Comment by felixarntz** [comment]
#558 will fix this instead.
