### ISSUE TITLE
Fix test:analyze command

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3405]
## Feature Description

The `test:analyze` command doesn't work due to incorrect configuration.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `test:analyze` command should work and display the bundle analyzer report in the browser.

## Implementation Brief

* Fix e2e and vrt issues
* Merge #2377 

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Run the `npm run test:analyze` command and make sure it opens the bundle analyzer report in your browser.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅  Once you get back to working on this, please refresh the PR against latest `develop` - there's currently a merge conflict, and we should make sure no other changes are now out of date.

**Comment by cole10up** [comment]
### **QA ✅**

Confirmed and validated the functionality of test:analyze 
![image](https://user-images.githubusercontent.com/57115907/127363276-83ca29fe-e985-40b7-8ed4-ceede73e62df.png)

Sending to approval
