### ISSUE TITLE
Validate Composer configuration

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3409]
Our `composer.json` should be validated in CI.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's Composer file should be checked for validity in CI, as part of the `.github/workflows/php-lint.yml` workflow.

## Implementation Brief

* Iterate on and merge #1729.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check that the Composer file is validated in the CI workflow `.github/workflows/php-lint.yml` (via GitHub Actions).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 @felixarntz FYI this is a tracking issue for a PR by a 3P contributor that I'll review.

**Comment by asvinb** [comment]
Un assigning myself from QA since I'am having a very slow internet due to some works to a cable in the region and I was setting up `act` https://github.com/nektos/act to test the actions locally.

**Comment by danielgent** [comment]
Tested -> the commits can be seen on this PR here https://github.com/google/site-kit-wp/pull/3424/commits

Tried
* break composer.json with bad characters
* update composer.json without lockfile
* break lockfile with bad characters

**QA** :heavy_check_mark:
