### ISSUE TITLE
Additional Storybook stories for Analytics-4

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#3412]
## Feature Description

In https://github.com/google/site-kit-wp/issues/3254 we extended settings components to factor in GA4,

`assets/js/modules/analytics/components/settings/SettingsView.js` url `/wp-admin/admin.php?page=googlesitekit-settings#settings/analytics/view`
`assets/js/modules/analytics/components/settings/SettingsForm.js` url `/wp-admin/admin.php?page=googlesitekit-settings#settings/analytics/edit`

Now we need to update storybook stories to account for the new functionality.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SettingsView` component should have a new story that demonstrates a case when valid UA and GA4 settings are set
* The `SettingsForm` component should have new stories that demonstrate the following cases:
  * Valid UA and GA4 settings are set and their common account is selected
  * Valid UA and GA4 settings are set, but another account with UA properties only is selected
* Existing (legacy) stories should be extended where present, otherwise Component Story Format may be used

The following settings need to be set for new stories:
* The `analytics` module:
  * `accountID`
  * `propertyID`
  * `internalWebPropertyID`
  * `profileID`
* The `analytics-4` module:
  * `propertyID`
  * `webDataStreamID`
  * `measurementID`

## Implementation Brief

Update the stories in the following URLs to account for the different scenarios in GA4 setup.

https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-settings--view-open-with-all-settings
https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-settings--edit-open-with-all-settings

### SettingsView ###

Corresponding story: https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-settings--view-open-with-all-settings
In code: https://github.com/google/site-kit-wp/blob/25344effc7a023ee4e5fd52b47584790bcd1df17/stories/module-analytics-settings.stories.js#L80

- Add a new scenario which shows the GA4 property, based on this code:
https://github.com/google/site-kit-wp/blob/f3886802e/assets/js/modules/analytics/components/settings/SettingsView.js#L99

### SettingsForm ###

Corresponding story: https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-settings--edit-open-with-all-settings
In code: https://github.com/google/site-kit-wp/blob/25344effc7a023ee4e5fd52b47584790bcd1df17/stories/module-analytics-settings.stories.js#L116

Add a scenario and extend the current one so that we have:
  * Valid UA and GA4 settings are set and their common account is selected
  * Valid UA and GA4 settings are set, but another account with UA properties only is selected

The following settings need to be set for stories:
* The `analytics` module:
  * `accountID`
  * `propertyID`
  * `internalWebPropertyID`
  * `profileID`
* The `analytics-4` module:
  * `propertyID`
  * `webDataStreamID`
  * `measurementID`

See the following references in code:
https://github.com/google/site-kit-wp/blob/f3886802e/assets/js/modules/analytics/components/settings/SettingsForm.js#L55

1. `SETUP_FLOW_MODE_LEGACY` which will show the `GA4Notice`
https://github.com/google/site-kit-wp/blob/f3886802e/assets/js/modules/analytics/components/settings/SettingsForm.js#L72

2. `SETUP_FLOW_MODE_UA` which will show the `A Google Analytics 4 property will also be created.` message.
https://github.com/google/site-kit-wp/blob/f3886802e/assets/js/modules/analytics/components/settings/SettingsForm.js#L98

* 

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check storybook stories for the Analytics module. It should have 3 new stories:
  * Once for the `SettingsView` component that demonstrates a case when valid UA and GA4 settings are set
  * And two for the `SettingsForm` component that demonstrate the following cases:
    * Valid UA and GA4 settings are set and their common account is selected
    * Valid UA and GA4 settings are set, but another account with UA properties only is selected

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@ivankruchkoff – I've refined the ACs a little bit here; assigning back to you to review the IB and revise if necessary. Thanks!

**Comment by ivankruchkoff** [comment]
> @ivankruchkoff – I've refined the ACs a little bit here; assigning back to you to review the IB and revise if necessary. Thanks!

IB, Test Coverage and VRT remain unchanged.

Per https://github.com/google/site-kit-wp/issues/3524#issuecomment-867776192 not making any points about backstop.

**Comment by eugene-manuilov** [comment]
@ivankruchkoff, unfortunately, AC and IB for this ticket are a bit outdated now - we don't rely on the setup flow types in the settings form anymore. Now we show GA4 controls only if the user has already connected an account with GA4 properties during the setup flow. If the Analytics module has been already connected by the time the release with GA4 support is published, then we don't show the GA4 dropdown in the settings form. Please, check more details in the AC section of #3586 and update the IB.

**Comment by eugene-manuilov** [comment]
@ivankruchkoff I have updated AC to correctly set expectations on which stories we need to add. Could you please update your IB to satisfy the new AC?

No need to put emphasis on setup modes, it's less important and it will be automatically picked when the correct settings are set for each module.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by danielgent** [comment]
## QA :white_check_mark:


Can see new stories

https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-settings--view-open-with-all-settings-ga4
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-settings--edit-open-with-all-settings-ga4
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-settings--edit-open-with-all-settings-ga4-new-property


And can confirm that stories are correct as per AC and IB
