### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by KinG-InFeT** [google/site-kit-wp#3415]
## Bug Description

Link broken on description text (code coverage link)

## Steps to reproduce

1. Go to page speed dashboard
2. Click on open collapse 'remove unused javascript"
3. Click on code coverage link and out 404 page

## Screenshots

![Screenshot_20210526-014102_Chrome](https://user-images.githubusercontent.com/193969/119581885-c6696380-bdc3-11eb-9fa6-ecc41801edb2.png)

## Additional Context

 - PHP Version: 7.4
 - OS: android 10
 - Browser Chrome
 - Plugin Version 1.33.0
 - Device: oneplus 5

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reaching out. This particular link while output in the PageSpeed Insights Site Kit dashboard comes from the associated API and is therefore not something we can address on the plugin site. We have however opened a GitHub issue on the Lighthouse repository. Once address this will be corrected within the Site Kit plugin. 

Feel free to subscribe to the below for updates:
https://github.com/GoogleChrome/lighthouse/issues/12473
