### ISSUE TITLE
User Input feature UX issue on iOS devices

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3420]
## Bug Description

When answering question 5 on the `User Input` feature on iOS devices (i.e. iPhone 12 both Chrome and Safari), when you start typing in the tag, the bubble does not increase as you type. This means you do not see the tag as you are typing it.  

Here's a screencast to see this issue in action. 

https://user-images.githubusercontent.com/73545194/119692229-26ebb580-be43-11eb-98fc-d077c137336d.mp4

## Steps to reproduce

On an iOS device (or use Browserstack) 

1. Make sure that UserInput is active on the tester plugin. 
2. Connect Site Kit and complete the questions 1-4
3. On question 5, as you start to type in the tag, observe the behaviour. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The text inputs for search terms on Step 5 of User Input should behave consistently on mobile as they do on desktop, particularly regarding their size which should grow wider with the length of the input. 
    * The behavior currently differs when using a real device (or simulator) rather than emulation in the browser 

## Implementation Brief

* Add `width: auto` to the `.googlesitekit-user-input__text-option .mdc-text-field`, i.e. the element that is created when you type.

### Test Coverage

* No new tests needed.

### Visual Regression Changes

* No VRT changes expected.

## QA Brief

This issue can be checked in desktop Safari.  However, as this is an IOS issue I did the following to test it after updating the code:

* Build a release zip and upload it to a site accessible using an iPhone and mobile Safari
* Upload the tester plugin and enable the UserInput feature flag
* Connect Site Kit and then on the 5th user input question check that the text field expands when it is typed into (see screencast above as a reference)

## Changelog entry

* Improve User Input tag creation on Mobile Safari.

**Comment by johnPhillips** [comment]
It turns out that the issue is also visible (though not so bad) on desktop Safari.

The best fix I have got is as follows:

```diff
+++ b/assets/sass/components/user-input/googlesitekit-user-input-controls.scss
@@ -145,9 +145,13 @@
                        }
                }

-               .mdc-text-field .mdc-text-field__input {
-                       color: $c-user-input-color;
-                       font-weight: 500;
+               .mdc-text-field {
+                       width: auto;
+
+                       .mdc-text-field__input {
+                               color: $c-user-input-color;
+                               font-weight: 500;
+                       }
                }
        }

```
This seems to completely fix desktop Safari, and mostly addresses Safari on IOS with the following notes / edge cases:
- When you start typing, the first character is sometimes clipped. As you type, it adjusts itself. This might be related to React updating the element as you type.
- Long strings of certain wider characters like `wwwwww` and `mmmm` can still produce the scrolling behaviour, although it isn't as bad. Words containing a mix of characters (i.e. not `wwwwmmm`) seem fine for the most part.

I'll add this to the IB for now, although obviously thoughts welcome.
CC @asvinb (you might know a bit more about this than me!)

**Comment by tofumatt** [comment]
Seems good to me; the lack of "scrolling" when inputting the same character repeatedly might be a weird rendering bug/rendering over-efficiency. If it scrolls when there are different characters that seems fine.

IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the text field expands when it is typed into.  This was tested on iOS on Safari, and on Safari desktop since John reported the issue there as well.  As a sanity check, I also ran checks that the text fields on question 5 worked as expected on Android and desktop, i.e. FF, Chrome. - [Screenshot 1](https://user-images.githubusercontent.com/73545194/124627668-0a9a5a00-de80-11eb-8106-d2a65ab374c5.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/124627709-1259fe80-de80-11eb-8ea5-839e910edb80.png)
