### ISSUE TITLE
WordPress Nightly E2E Tests fail because of AMP tests failing

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3429]
## Bug Description

WordPress Nightly is failing our E2E tests (specifically AMP tests—the `toHaveValidAMPForUser()` matcher). See https://github.com/google/site-kit-wp/pull/3416/checks?check_run_id=2674983821 for an example.

It looks like this change https://github.com/WordPress/wordpress-develop/blob/ea49625d59f41e17312d4c08503cd2dd567f4bda/src/wp-includes/theme-templates.php#L69-L163 (hat tip @aaemnnosttv), specifically the script tag at https://github.com/WordPress/wordpress-develop/blob/ea49625d59f41e17312d4c08503cd2dd567f4bda/src/wp-includes/theme-templates.php#L126-L158 is causing our AMP tests to fail.

I don't think this is valid to mark as an upstream issue, as I'm not sure its a goal of WordPress Core to support AMP 😅 

Looks like the easiest way to fix it would be to remove/replace the action registered here: https://github.com/WordPress/wordpress-develop/blob/849c811396dc7651e24e1323a4c67b9fda50a719/src/wp-includes/default-filters.php#L643, as it's what's causing that to be output.

Maybe that should be done upstream in the AMP plugin too though? For now we should do it to fix our tests, but presumably this will affect everyone.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The WordPress E2E Nightly tests should pass.

## Implementation Brief

* Disable the new `the_block_template_skip_link` function from running in the `wp_footer` action when running E2E tests. This can be done with an E2E plugin in the `mu-plugins` folder.
* Merge #3430

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Verify the WordPress E2E tests pass.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
(Feel free to do the Code Review on this one if the IB looks good, as the PR is all set for review and is passing the tests now 😄)

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt ! I agree this should be raised with the AMP plugin too (I don't see an issue there for it yet) but a 1 line plugin is much better than ignoring failing tests for things that are not in our control.

IB ✅
