### ISSUE TITLE
Extend issue templates with config

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3432]
## Feature Description

Currently we have a few issue templates for creating a new issue for a bug or feature request, but GitHub also supports adding additional links via a [configuration file](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

E.g. https://github.com/ampproject/amp-wp/issues/new/choose

We should leverage this to add useful links in a similar way, as well as maybe add a new template or two.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A [GitHub issue config file](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) should be created to add the following extra choices when opening an issue
	* name: Official Support Forum  
	url: https://wordpress.org/support/plugin/google-site-kit/  
    about: For plugin usage questions, please use the plugin's support forum. Before opening a new topic, please search the forum for existing topics as someone else has likely reported the issue already.
    * name: Documentation  
    url: https://sitekit.withgoogle.com/documentation/
    about: We have several guides which can be found on the [documentation on the Site Kit website](https://sitekit.withgoogle.com/documentation/), including guides for troubleshooting issues related to [setup](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/), errors that appear on the [plugin dashboard](https://sitekit.withgoogle.com/documentation/troubleshooting/dashboard/), [Analytics](https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/), and [AdSense](https://sitekit.withgoogle.com/documentation/troubleshooting/adsense/). We’re continuing to add new documentation, so continue to check the website for updates.

## Implementation Brief

* Merge the attached PR which is branched off main and the PR is targeting main. This will ensure the issue templates can be tested. The PR adds the appropriate `config.yml` file.
* NOTE: Github does not support having links within the "about" description text. So the links to specific pages in the "Documentation" description in the ACs are not possible.

### Test Coverage

* No new tests required.

### Visual Regression Changes

* No changes should occur.

## QA Brief

* Ensure the PR is merged into `main` and not `develop` only. 
* Go to create a new issue on Github or click on the following link: https://github.com/google/site-kit-wp/issues/new/choose.
* Verify the two new link options.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz I added some initial ACs. Sending your way for more details 🙂 
cc: @marrrmarrr

**Comment by felixarntz** [comment]
@aaemnnosttv Hmm this seems like it may benefit from a bit more definition overall? I agree it might be good to add the two links, and we can define wording about that, but what about leveraging forms for actual issues like bug reports etc? Maybe we scope this one more specifically to providing helpful links in GitHub issue UI, following what you already added to the ACs?

@marrrmarrr It'd probably be best for you to define the wording here, let's have a look later this week.

**Comment by aaemnnosttv** [comment]
> what about leveraging forms for actual issues like bug reports etc?

@felixarntz my initial thought is that this isn't as relevant for us as issues for bugs are either opened by us or the support team, so forms wouldn't be as useful I don't think. These are a new beta feature that I haven't seen used yet so maybe there is more utility to using them, I'm not really sure.

**Comment by felixarntz** [comment]
Sounds good, I agree we should keep things basic for now. Maybe still worth opening an issue for the _Backlog_ to go further at some point - it may make things easier for external folks.

**Comment by bethanylang** [comment]
@felixarntz @marrrmarrr This is a really old one – is this still relevant, and if so, how can we move forward? Thanks!

**Comment by aaemnnosttv** [comment]
@bethanylang still relevant, yes – will pick up in an upcoming sync

**Comment by tofumatt** [comment]
QA ✅ 

New text/links appear in the GitHub "New issue" page:

![CleanShot 2023-11-02 at 19 29 15](https://github.com/google/site-kit-wp/assets/90871/16d7ce63-7b64-42d7-893b-5d622fc8fd7d)

Bonus to @jimmymadon for including emoji 🥇
