### ISSUE TITLE
Add support and security policies

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3433]
## Feature Description

* https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository ([example](https://github.com/ampproject/amp-wp/blob/3bb15f3d660c4401b958147430664d07eb1e03e2/SECURITY.md))
* https://docs.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project ([example](https://github.com/ampproject/amp-wp/blob/3bb15f3d660c4401b958147430664d07eb1e03e2/SUPPORT.md))

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

A new `SECURITY.md` file should be added to the repository, with the following content:
```
# Security Disclosures

The Site Kit Project accepts responsible security disclosures through the [Google Application Security program](https://www.google.com/about/appsecurity/).
```

A new `SUPPORT.md` file should be added to the repository, with the following content:
```
# Support

If you encounter an issue with Site Kit, first check our [troubleshooting guide](https://sitekit.withgoogle.com/documentation/fix-common-issues/). For plugin usage questions and compatibility issues with other plugins, please use the [plugin's support forum](https://wordpress.org/support/plugin/google-site-kit). Before opening a new topic, please search the forum for existing topics as someone else has likely reported the issue already.

Find documentation and a blog with news on the [plugin website](https://sitekit.withgoogle.com).
```

## Implementation Brief

* Create `SECURITY.md` and `SUPPORT.md` as per AC.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Ensure files are avaiable in the repo at:
* https://github.com/google/site-kit-wp/blob/develop/SECURITY.md
* https://github.com/google/site-kit-wp/blob/develop/SUPPORT.md

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- Confirmed that files are available in the repo:

`https://github.com/google/site-kit-wp/blob/develop/SECURITY.md`

![image](https://user-images.githubusercontent.com/73545194/133600261-7f9c2888-3a2d-4df6-8a1d-9bf3383a99f9.png)

`https://github.com/google/site-kit-wp/blob/develop/SUPPORT.md`

![image](https://user-images.githubusercontent.com/73545194/133600291-e44941a0-8ca0-49ec-9614-18ad86318208.png)

- Checked that the content matches that of the AC. 
- Checked that the links within the files worked as expected.
