### ISSUE TITLE
Module Setup Flow | Analytics: Existing account, no existing tag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#344]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Tests must cover the following:
* User clicks Activate Analytics button in Settings
* two alternative scenarios:
    1. if there is an existing property that matches site URL
        * dropdowns are shown, matching property and owning account are preselected
        * user changes account, properties are re-fetched for that other account and displayed; since no match is found, "select ..." is preselected (empty)
        * user changes property, profiles are re-fetched for that property and displayed
    2. if there is an existing property, but none that matches the site URL
        * dropdowns are shown, account and property are both set to "select ..." (empty)
        * user selects an account, properties are fetched for that account and displayed; since no match is found, the first property in the list is preselected
        * user selects "setup new property"
* in both scenarios, completing the flow should successfully take the user to the Analytics module page

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz can you take a look at this one an update the acceptance criteria if necessary? Basically, as soon as an account is chosen, the other dropdowns select the first choice.

**Comment by felixarntz** [comment]
@aaemnnosttv I updated the acceptance criteria accordingly to match the current state (although I think this is not the preferred thing that should happen). Will consult with Mariya on what should happen here and potentially open a follow-up issue, as in either case this shouldn't be changed here.

**Comment by lilybonney** [comment]
Morning @swissspidy! Possible to finish out the CR on this one this morning? It's a blocker for a couple of other tickets we'd love to get into engineering ASAP. Thanks so much!

**Comment by lucymtc** [comment]
QA looks good. 
`npm run test:e2e:interactive -- tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js`
Behaviour and tests pass as expected.
