### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by Mrahmani71** [google/site-kit-wp#3441]
## Feature Description

Please modify the CSS code for RTL sites.
I think these codes should be added or modified
`
.googlesitekit-page {
    margin-right: -20px;
}

.googlesitekit-page {
    margin-right: -10px;
}

.googlesitekit-header .googlesitekit-date-range-selector svg {
    margin-left: 8px;
}

.googlesitekit-plugin .googlesitekit-widget--analyticsAllTraffic__dot {
    margin: 0 0 0 4px;
}

.googlesitekit-table .googlesitekit-table__head-item:first-child {
    padding-right: 0;
    text-align: right;
}

.googlesitekit-table--with-list .googlesitekit-table__body-item:first-child .googlesitekit-table__body-item-content::before {
    right: -24px;
}

.googlesitekit-table--with-list .googlesitekit-table__body-item:first-child .googlesitekit-table__body-item-content {
    margin-right: 24px;
}

.googlesitekit-table .googlesitekit-table__body-item:first-child {
    text-align: right;
}

.googlesitekit-cta-link {
    text-align: right;
}

.googlesitekit-post-searcher .googlesitekit-post-searcher__label {
    right: 30px;
}

.googlesitekit-accordion .googlesitekit-accordion__header::after {
    left: 16px;
}

.googlesitekit-cta-link.googlesitekit-cta-link--arrow, .googlesitekit-cta-link.googlesitekit-cta-link--external {
    background-position: calc(1%) center;
    padding-left: 20px;
}

.googlesitekit-settings-module .googlesitekit-settings-module__status-icon {
margin-right: 16px;
}

.googlesitekit-settings-module .googlesitekit-settings-module__title-icon {
    margin-left: 16px;
}

`
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Many thanks for the suggestion and for providing the styling. As we already have an open [RTL issue ](https://github.com/google/site-kit-wp/issues/1156) I'll close this as a duplicate. We can however review your suggestions when working on that initial issue. 

Feel free to subscribe to that issue for further updates on this.
