### ISSUE TITLE
User-ID tracking in Analytics Stats

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3442]
## Feature Description

A user asked for User-ID tracking in Analytics as Site Kit is not supporting this currently. So submitting the request on the behalf of the user.
Topic: https://wordpress.org/support/topic/user-id-tracking-code/

I can ask for more information in case if there is something required for this feature.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
> Hi, I just followed the steps to enable tracking of the User-ID in my Google Analytics account.

@abdullah1908 which steps is the user referring to? For any custom configuration of [`gtag` options](https://developers.google.com/gtagjs/devguide/configure), we do provide a `googlesitekit_gtag_opt` filter which the user can use to extend to implement any customizations that we do not provide an option in the plugin for although this does require some technical savviness. It's hard to say more than that though without knowing more about what they're trying to do.

**Comment by abdullah1908** [comment]
@aaemnnosttv as per my understanding user is referring toward setting up [User-ID tracking in Analytics](https://support.google.com/analytics/answer/3123662?hl=en#zippy=%2Cin-this-article). We have discussed this in today's weekly internal sync. As per team we'll not consider this for future as this feature doesn’t align with our roadmap for the Site Kit plugin.
