### ISSUE TITLE
Dialog Component Accessibility Issues

### ISSUE THREAD

**Issue by swissspidy** [google/site-kit-wp#345]
## Bug Description

The Dialog component uses `role="alertdialog"` and thus `aria-labelledby` and `aria-describedby` attributes. These contain the ID of the element that labels/describes the dialog: `aria-labelledby="remove-module-dialog"` and `aria-describedby="remove-module-dialog-description"`, respectively.

Now, there are a couple of issues here:

First, these attributes are not necessarily unique on the page. When the component is used N times, there will be N elements with the same `remove-module-dialog` and `remove-module-dialog-description` IDs.

This is the case on the settings screen, where "Reset Site Kit" and "Disconnect" both open dialogs.

An easy way to solve this would be to use the `withInstanceId` HOC from the `@wordpress/compose` package.

Second, the `#remove-module-dialog-description` element is usually empty. Therefore there is no actual ARIA description for the dialog. Correct would  be pointing to an element that contains a written sentence describing the dialog.

Here's a good example: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Dialog` component should be implemented in a way that cannot introduce duplicate ID attributes on a page.
* The `Dialog` component should only use `aria-labelledby` and `aria-describedby` if there are actually elements with the respective IDs that include respective content.

## Implementation Brief

* Wrap Dialog components with `withInstanceId`
* Use `instanceId` to build unique instance-specific IDs for use with aria attributes
* Only set `aria` attributes if the elements they reference aren't empty
* Merge #1082 

## Changelog entry

* Fix accessibility issues in dialog component with potentially duplicate IDs and invalid ARIA attributes.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

Tested this with NVDA and checked the output in browser. Works as expected when opening a dialog, thanks! 👍
