### ISSUE TITLE
Tag Manager: If account set and user doesn't have any, show message that they don't have access

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#346]
## Bug Description

This came up during QA in https://github.com/google/site-kit-wp/issues/181#issuecomment-516059309: If there's a Tag Manager account already set and a secondary admin doesn't have access, the message that they don't have access should take precedence over whether that user does or doesn't have accounts themselves.

## Steps to reproduce

1. Setup Site Kit as usual for the first administrator.
2. Setup Analytics and TagManager
3. Logout and login as second Administrator
4. Sign in to Google with an account that doesn't have any TagManager account
5. Go to settings page, and the error message show up.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For cases where there's an existing GTM account connected through the plugin by another admin user, and the current admin user doesn't have any accounts (and thus doesn't have access to it), the existing message that the user doesn't "have access to this Google Tag Manager account" should be displayed. In other words, this access check must take precedence over whether the current admin user has any accounts or not.

## Implementation Brief

In `\Google\Site_Kit\Modules\TagManager::parse_data_response` for the GET `list-accounts` datapoint:

Return an empty response if the user has no accounts instead of a `WP_Error`
```diff
diff --git a/includes/Modules/TagManager.php b/includes/Modules/TagManager.php
index cc0d2b4..7042683 100644
--- a/includes/Modules/TagManager.php
+++ b/includes/Modules/TagManager.php
@@ -484,7 +484,7 @@ final class TagManager extends Module implements Module_With_Scopes {
                        'containers' => array(),
                    );
                    if ( 0 === count( $response['accounts'] ) ) {
-                       return new WP_Error( 'google_tagmanager_account_empty', __( 'We didn’t find an associated Google Tag Manager account, would you like to set it up now? If you’ve just set up an account please re-fetch your account to sync it with Site Kit.', 'google-site-kit' ), array( 'status' => 500 ) );
+                       return $response;
                    }
                    if ( is_array( $this->_list_accounts_data ) && isset( $this->_list_accounts_data['accountId'] ) ) {
                        $account_id                = $this->_list_accounts_data['accountId'];

```

The user will still see an error if there is a selected account as they will have no account ID to match.

https://github.com/google/site-kit-wp/blob/b225df85d49c114e161591c91bbdb6a3c8015995/assets/js/modules/tagmanager/setup.js#L134-L141

Move the logic for displaying an error message if there is no selected account and the user has no accounts:

```diff
diff --git a/assets/js/modules/tagmanager/setup.js b/assets/js/modules/tagmanager/setup.js
index 9d3fba4..db6aa9f 100644
--- a/assets/js/modules/tagmanager/setup.js
+++ b/assets/js/modules/tagmanager/setup.js
@@ -133,6 +133,17 @@ class TagmanagerSetup extends Component {
            let errorMsg = '';
            const responseData = await data.get( 'modules', 'tagmanager', 'list-accounts', queryArgs, false );
 
+           if ( ! selectedAccount && 0 === responseData.accounts.length ) {
+               data.deleteCache( 'tagmanager', 'list-accounts' );
+               throw {
+                   code: 'accountEmpty',
+                   message: __(
+                       'We didn’t find an associated Google Tag Manager account, would you like to set it up now? If you’ve just set up an account please re-fetch your account to sync it with Site Kit.',
+                       'google-site-kit'
+                   ),
+               };
+           }
+
            // Verify if user has access to the selected account.
            if ( selectedAccount && ! responseData.accounts.find( ( account ) => account.accountId === selectedAccount ) ) {
                data.deleteCache( 'tagmanager', 'list-accounts' );

```

Continue the rest of the response for this datapoint as usual.

## Changelog entry

* Ensure that a secondary administrator who does not have any Tag Manager accounts sees a warning that they don't have access to the currently selected account.

**Comment by felixarntz** [comment]
@aaemnnosttv I think the IB is slightly incorrect:
> If the saved `accountId` does not match, then return the same response as if `0 === count( $response['accounts'] )`

This would still return the `google_tagmanager_account_empty` error as response, which would be caught in JS and thus that message would display to the user. The intended result of the ACs would be that the user instead sees the information that they don't have access (if they don't have an account, how would they). In other words, I think the logic would need to be closer to:
* If the user has no accounts (where we would typically return an error) and `$option['accountId']` is already set, return an empty array for both `accounts` and `containers` pieces of the response, instead of the error.
* The JS code would still compare the `selectedAccount`, and since there are no accounts, it would reach the logic to show the user they don't have access.

**Comment by felixarntz** [comment]
Actually, I think we should simplify the API endpoint logic here to just return the empty array if there are no accounts. It doesn't make any sense from an API architecture standpoint to consider a lack of accounts an error - it just means that there are no accounts.

This becomes evident by the fact that only for the initial setup of Tag Manager we in Site Kit consider the lack of that an error.

@aaemnnosttv Let's update the datapoint to just return an empty `accounts` and empty `containers` list if there are no accounts. The logic to display the existing error message (only in case there is no selected account yet) should be moved to the client-side.

Related: #398

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅

**Comment by adamsilverstein** [comment]
This passes QA, moving to Approval.

### Testing procedure

* follow steps above to set up error condition.
* visit the settings screen and confirm that the message stating that the user doesn't "have access to this Google Tag Manager account" shows.

This is the expected screen:

![image](https://user-images.githubusercontent.com/2676022/66585703-8d27a580-eb44-11e9-97a5-eb9cade2ac07.png)

**Comment by marrrmarrr** [comment]
LGTM.
