### ISSUE TITLE
Module Setup Flow | AdSense: Existing user, with code on site, publisher ID matching

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#347]
See https://docs.google.com/drawings/d/1-D35Wco2BtaUdHLhmec4OcsMvKIb_W_QTmx7TxqBaOA/edit

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User clicks “connect service” for AdSense 
* Requested to grant AdSense API scopes → yes
* Check if they have an account → account is detected and is already approved, AdSense code is already detected on site, the code detected on the site has the same publisher ID as the connected account (pub-xxxxxxxxxxxx are matching).
* Show screen 
_“Site Kit will place AdSense code to your site
This means Google will automatically place ads for you in all the best places.
[v] Let Site Kit place code on your site RECOMMENDED
(i) If you’ve already set up ads on your site, it may change how they appear. You can customize this later in AdSense."_
* User has the choice to “let Site Kit place code on your site” or not. Toggle is on by default.

Scenario 1: User leaves toggle “let Site Kit place code” on and clicks continue
* Plugin places AdSense code on the site
* Check Impressions via reporting API:
    * if zero → Show screen “We’re getting your site ready for ads” + link to AdSense FE requesting user to add their site to Sites tab and enable ads 
    * if non-zero → show AdSense dashboard

Scenario 2: User toggles off “let Site Kit place code” 
* Plugin DOES NOT place code on site 
* Check impressions via reporting API:
    * if zero → send user to Settings page 
    * if non-zero → then show AdSense dashboard. Redirect user to the AdSense dashboard within the plugin
* Settings page:
     * Account status: Approved
     * AdSense code: AdSense code is placed on your site

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr 

Regarding the conditions in the criteria, can we remove the "if" conditions and make these into additional scenarios if necessary?

**Comment by aaemnnosttv** [comment]
Just to confirm, if this case is for a site with Adsense code already present, it seems incorrect that Site Kit would offer to place it. Is this the expected behavior?

**Comment by OisinOConnor** [comment]
> Just to confirm, if this case is for a site with Adsense code already present, it seems incorrect that Site Kit would offer to place it. Is this the expected behavior?

Site Kit should still offer to place the code. But the screen displayed is different to when there is no AdSense code detected:
Site Kit will place AdSense code to your site

This means Google will automatically place ads for you in all the best places.

[v] Let Site Kit place code on your site RECOMMENDED

(i) If you’ve already set up ads on your site, it may change how they appear. You can customize this later in AdSense.

**Comment by OisinOConnor** [comment]
> See https://docs.google.com/drawings/d/1-D35Wco2BtaUdHLhmec4OcsMvKIb_W_QTmx7TxqBaOA/edit
> 
> _Do not alter or remove anything below. The following sections will be managed by moderators only._
> 
> ## Acceptance criteria
> * User clicks “connect service” for AdSense
> * Requested to grant AdSense API scopes → yes
> * Check if they have an account → account is detected and is already approved, AdSense code is already detected on site?
> * Show screen “Site Kit will place AdSense code to your site” → user has the choice to “let Site Kit place code on your site” or not. Toggle is on by default.
>   
>   1. if the user leaves toggle “let Site Kit place code” on and click continue
>      
>      * Plugin places AdSense code on the site
>      * Check Impressions via reporting API:
>        
>        * if zero → Show screen “We’re getting your site ready for ads” + link to AdSense FE requesting user to add their site to Sites tab and enable ads
>        * if non-zero → show AdSense dashboard
>   2. If the user toggles off “let Site Kit place code”
>      
>      * Plugin DOES NOT place code on site
>      * Check impressions via reporting API:
>        
>        * if zero → send user to Settings page
>        * if non-zero → then show AdSense dashboard. Redirect user to the AdSense dashboard within the plugin
>      * Settings page:
>        
>        * Account status: Approved
>        * AdSense code: AdSense code is placed on your site
> 
> ## Implementation Brief
> * 
> 
> ## Changelog entry
> *

This scenario is for when the code detected on the site has the same publisher ID as the connected account (pub-xxxxxxxxxxxx are matching).

**Comment by marrrmarrr** [comment]
> > Just to confirm, if this case is for a site with Adsense code already present, it seems incorrect that Site Kit would offer to place it. Is this the expected behavior?
> 
> Site Kit should still offer to place the code. But the screen displayed is different to when there is no AdSense code detected:
> Site Kit will place AdSense code to your site
> 
> This means Google will automatically place ads for you in all the best places.
> 
> [v] Let Site Kit place code on your site RECOMMENDED
> 
> (i) If you’ve already set up ads on your site, it may change how they appear. You can customize this later in AdSense.

@aaemnnosttv to further clarify, this step is offering any publisher who has an existing account without [Auto Ads](https://support.google.com/adsense/thread/1603676) enabled to upgrade to Auto Ads. So if they choose to upgrade, Site Kit will be placing code on their site, even if there was already a code.

**Comment by aaemnnosttv** [comment]
Ok, thank you! I wasn't sure if this was similar to Analytics where it can only have one code one the site at a time or not.

Moving this back to Acceptance Criteria for the individual test scenarios to be refined. Each scenario should be a single path or list of steps for the user to take (perfectly fine for common steps for each to be grouped together though, such as at the beginning). Since the conditions are under our control, these should be defined in separate scenarios if they should be tested.

**Comment by marrrmarrr** [comment]
These conditions as described match the current plugin flows. (may need to revisit later if the flows are adjusted)

**Comment by felixarntz** [comment]
Closing in favor of #940
