### ISSUE TITLE
Combine WP dashboard widget CTAs

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3474]
## Feature Description

Recently we added the functionality to combine widgets with similar special states into a bigger one to reduce the number of duplicate CTAs and to remove confusion. But if we look at the WordPress dashboard widget that has no data yet, it still shows a bunch of duplicate CTAs:

![adverse-wildcat jurassic ninja_wp-admin_index php](https://user-images.githubusercontent.com/873049/120691701-74a19700-c4af-11eb-807a-b63e50846880.png)

We need to update the WP dashboard widget to display only one CTA when there is no data.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov – we already have an issue to address this in #1147 👍
