### ISSUE TITLE
Avoid unnecessary token refresh

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3477]
## Feature Description

Access tokens that are generated for communicating for Google APIs are short-lived tokens which are only valid for one hour. Once expired, a new access token can be requested using the refresh token received during a user's initial connection. The refresh token is much longer lived and requires going through oAuth again to get a new one. The underlying PHP API Client library for Google APIs handles refreshing access tokens automatically on-the-fly when needed when a request is made.

As we have started to move away from batch requesting all data via Site Kit's `/data` REST endpoint and more towards a more traditional API architecture (making one request per endpoint), this has introduced the potential for multiple access tokens to be requested at the same time.

The most common situation for this would be on the WordPress dashboard, right after logging in for the first time in over an hour. If Analytics is connected, this would result in 4 separate requests to the Google API at the same time and since the access token would be expired at the time the request is made, a new token would be requested in each case, used once and only the last one would be kept.

![image](https://user-images.githubusercontent.com/1621608/120764670-10b7b680-c521-11eb-9b35-0c5983a183a6.png)

_4 consecutive requests to `/o/oauth2/token/` followed by 4 requests to Google APIs (3 for Analytics, 1 for Search Console)_

While the on-demand token refreshing is important, we should see how to avoid such cases where more tokens are requested than needed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Instead of mainly relying on the automated on-demand refresh of access tokens that are about to expire (which is built into the Google PHP client library), Site Kit should proactively refresh the current user's access token in that case, **outside of REST API requests** which may come in multiple at a time, causing the problem outlined. (Note that this is not a major problem, so we do not need to prevent it - but we should avoid it where possible.)
    1. On pageload: If the current user has an access token which will expire in the next 30 seconds or less, that access token should be refreshed, relying on the existing `OAuth_Client::refresh_token()` method (which used to be used, but has for a while now been unused).
    2. The same logic should run for every WordPress "heartbeat" request (see `heartbeat_tick` action), so that it also works in the case that the user stays on a Site Kit screen without a page reload for longer than the access token expiry.

## Implementation Brief

* Add new hooks for `admin_init` and `heartbeat_tick` actions to  the `Authentication` class:
  * Get the current token using `$this->token->get()` method;
  * Return early if the current token is empty or it doesn't exire in less than 30 seconds;
  * Call `$this->get_oauth_client()->refresh_token()` method.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Stop your local environment
* Configure HTTP proxy on your local machine following instructions in the [engineering workflow doc](https://docs.google.com/document/d/1vYRA-YxxZdufO6piF0gA1k60N3UxbvuqyQr_XfGgvSk/edit#heading=h.faf0umy03arh).
* Reset token creation time by running the following command:
  ```
  10updocker wp user meta set 1 wp_googlesitekit_access_token_created_at 1
  ```
* Start the mitmproxy app
* Start your local environment
* Open a non-sitekit admin page (for example `Appearance > Themes`: /wp-admin/themes.php).
* Check the mitmproxy log and confirm that you see only one request to the `https://sitekit.withgoogle.com/o/oauth2/token/` endpoint.

## Changelog entry

* Avoid potentially simultaneous token refresh requests by proactively refreshing soon-to-expire tokens.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv do you mind reviewing IB?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov overall the IB looks good but there are a few details in the AC that aren't referenced that we don't want to lose.

- This should only happen if the current user has an access token (e.g. `Authentication::is_authenticated()`) – we don't want to touch the `OAuth_Client` if this isn't the case
- The ACs say this should only happen if the token is expiring in 30 seconds or less (where you have mentioned 5 minutes) – this is based on logic which already exists in the `Google\Client::isAccessTokenExpired` method ([which we used to use](https://github.com/google/site-kit-wp/blob/cb944a40b11ae72a2b7dcbbebb3891c35564ea58/includes/Core/Authentication/Clients/OAuth_Client.php#L218-L221) for this purpose) which makes sense to use for this. I don't think it's a bad idea to refresh the token a bit earlier (given heartbeat intervals can be up to a few minutes between) but let's keep it like this for now to leverage the client's method.

As for adding a new public `maybe_refresh_token` method, I think that probably isn't necessary as the logic is simple enough that it can live in the callbacks hooked to the actions you mentioned.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv IB is updated.

**Comment by aaemnnosttv** [comment]
IB ✅  Going to bump the estimate though to allow a bit more time for CR+QA.

**Comment by felixarntz** [comment]
@eugene-manuilov Can you add a QA Brief?

**Comment by eugene-manuilov** [comment]
@felixarntz found one more issue in the `OAuth_Client::refresh_token` method that prevented token refresh on non-sitekit pages. The `refresh_token` method tried to access not initialized `google_client` instance instead of using the `get_client()` method, which caused early return and left token not refreshed.

Do you mind reviewing #4062?

**Comment by ivankruchkoff** [comment]
QA: ✅

- Installed mitmproxy and configured it, along with the disable ssl verification plugin.
- Updated meta `wp user meta set 1 wp_googlesitekit_access_token_created_at 1`
- Opened `/wp-admin/themes.php`
- Saw the following:
<img width="440" alt="Screen Shot 2021-09-23 at 12 45 18 PM" src="https://user-images.githubusercontent.com/373931/134487017-0e62105c-2a66-4d0c-9308-b7345bbc0c51.png">

<img width="568" alt="Screen Shot 2021-09-23 at 12 46 29 PM" src="https://user-images.githubusercontent.com/373931/134487044-710d85c4-15ca-443f-8df0-b5622ff394ae.png">

- No other requests
