### ISSUE TITLE
Clicks & impressions remain at zero 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3482]
## Bug Description

[One user](https://wordpress.org/support/topic/0-impressions-and-0-clicks/#post-14520933) is encountering Search Console traffic not matching Site Kit. Both the "Clicks" and "Impressions" remain at zero within Site Kit. This is a recently added property.

Site setup on a new SC property for further testing, with a similar  environment, with a connected domain type property. (previously verificed)

![image](https://user-images.githubusercontent.com/41326532/120834862-7f196a80-c55b-11eb-98e7-2f47e3d87d74.png)

## Additional Context

 - Site Kit 1.33.0
 - [SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgFbKOui0pzbkJgg27Y4ynyjeg7B3GzRzXCJK5RTvKZ6MdCHp2ZAWcuTOByyNFI2Q4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@jamesozzie Any updates on this?

**Comment by jamesozzie** [comment]
@bethanylang No update just yet unfortunately, awaiting search traffic on 3 sites setup for this purpose. I can't reproduce this on any existing test sites and for the new sites I'm awaiting Search traffic. I have pushed some test data for these sites and they are appearing in Search. I'll update this accordingly in a few days.

**Comment by jamesozzie** [comment]
Tested on some newly added test sites, new to Search Console. Unable to reproduce on 1 site while the other remains awaiting additional Search Traffic. More test traffic has pushed, keeping open for further testing. 

Note the gif below that provides a better understanding of the users issue, the Search Console tab within Site Kit displays traffic fine, the primary Site Kit dashboard doesn't include any metrics for impressions or clicks. 

![2021-07-02-14-55-31](https://user-images.githubusercontent.com/41326532/124285161-93925800-db45-11eb-98ce-9d84335e868e.gif)

**Comment by jamesozzie** [comment]
Closing as non re-producible, with the impacted users dashboards now working as expected.
