### ISSUE TITLE
Widget-based page dashboard appears blank for page not found

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3493]
## Bug Description

The page dashboard (aka dashboard details) view has two primary states based on the URL passed in the `permaLink` query parameter:
* When the permalink resolves to a post/page entity on the local WP site, it displays a dashboard of stats for that page
* When the permalink **does not** resolve to an entity on the local WP site, it renders a "not found" state with no dashboard

In the not found case above, the page dashboard currently displays a blank page, with no error in the dashboard.

This is due to logic that changed in the `WidgetContextRenderer` as part of #3226 to no longer render the context at all if there are no widget areas. This seems like a reasonable change, but breaks this specific view where it does not have any widget areas, and instead renders the "not found" output as part of its header (passed via props to the context renderer)

## Steps to reproduce

1. Set up Site Kit
1. Ensure `widgets.pageDashboard` is enabled
1. Visit `/wp-admin/admin.php?page=googlesitekit-dashboard&permaLink=https%3A%2F%2Fexample.com%2Fdoes-not-exist%2F`
1. Observe blank screen

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/121039593-e46a9700-c7b9-11eb-802a-2d1f260c846d.png)

**Expected**

![image](https://user-images.githubusercontent.com/1621608/121041402-627b6d80-c7bb-11eb-88d5-4e2cdffb5c0d.png)

## Additional Context

* Introduced in 1.33.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit page dashboard should display the "not found" message when the URL identified in the `permaLink` query parameter does not resolve to a local entity on the widget-based page dashboard

## Implementation Brief

* Merge #3496

### Test Coverage

* No changes needed or expected

### Visual Regression Changes

* No changes expected

## QA Brief

* Ensure `widgets.pageDashboard` feature is enabled
* Follow the steps above to reproduce and ensure that the "not found" output is displayed:  
![image](https://user-images.githubusercontent.com/1621608/121041402-627b6d80-c7bb-11eb-88d5-4e2cdffb5c0d.png)
* Check the page dashboard for a few posts that do exist on the local site to ensure it still loads correctly 

## Changelog entry

* Fix regression where widget-based single URL screen would show up completely empty for content not found in the WordPress site.

**Comment by felixarntz** [comment]
Since this is rather critical and a small fix per @aaemnnosttv, let's squeeze it into the next 3 hours and add it to the 1.34.0 release going out later today. 💪

**Comment by felixarntz** [comment]
@aaemnnosttv Thanks! IB + CR ✅

**Comment by felixarntz** [comment]
### QA ✅ 

Single URL view for content that doesn't exist now shows up as expected again with the widget-based version:
![Screen Shot 2021-06-07 at 4 52 27 PM](https://user-images.githubusercontent.com/3531426/121101553-eb40dc00-c7b0-11eb-90d5-16fb1f6bbb83.png)

No longer an empty screen, despite not having any widget areas - the header with the information about the current URL is present again, as expected.
