### ISSUE TITLE
Couldn't create project

### ISSUE THREAD

**Issue by maskin** [google/site-kit-wp#35]
Couldn't create project
warning
field [project_id] has issue [project_id contains invalid characters]

**Comment by Tansch** [comment]
Attempt to manually generate the credentials:

Close the window "Project could not be created"
Paste this link in the address bar:
https://developers.google.com/web/site-kit/?sitename=hidendesignat&siteurl=https://hidendesign.at

Replace „hidendesignat“ and https://hidendesign.at with your own site details.
also include https or http

https://www.hidendesign.at/google-site-kit-einrichten-wordpress/
