### ISSUE TITLE
Analytics Property is not showing

### ISSUE THREAD

**Issue by benzwk** [google/site-kit-wp#3500]
## Bug Description

Property from analytics is now showing on sitekit

## Steps to reproduce

1. Go to 'admin portal'
2. Click on 'sitekit setting' to set up analytics
3. Select 'Account'
4. Select property dropdown

## Screenshots

<img width="720" alt="Screen Shot 2564-06-08 at 17 13 44" src="https://user-images.githubusercontent.com/70436060/121162383-78069b00-c880-11eb-9397-73a12d2a16af.png">

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@benzwk Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.  We can of course reopen this GitHub issue should we determine there is something to be address on the plugin side.
