### ISSUE TITLE
User Feedback & Idea Hub CTA button to be in uppercase

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3507]
## Feature Description

Following the Bug Bash session, could we please ensure both versions of the CTA button for the User Feedback survey are in uppercase, as per styling of all other CTA buttons

![image](https://user-images.githubusercontent.com/56588136/121217856-25c27b80-c87a-11eb-8cbf-bcaab291d533.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The buttons displayed in the user feedback surveys' completion prompts should have similar visual appearance as the common Site Kit buttons (particularly, text should be transformed to uppercase).
* Other recently added buttons (probably only the Idea Hub widget CTA button at this point) should also look more similar to the common Site Kit button (uppercase-transformed text at least).

## Implementation Brief
* Using `assets/sass/components/surveys/_googlesitekit-surveys.scss`,
    * Remove all the styles for the `.googlesitekit-survey__footer .mdc-button` selector.
* Using `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-cta.scss`,
    * Remove all the styles for the `.googlesitekit-idea-hub__dashboard-cta__setup` selector.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js`,
    * Remove the `googlesitekit-idea-hub__dashboard-cta__setup` class name since the button does not need custom styles.

### Test Coverage
* N/A

### Visual Regression Changes
* N/A

## QA Brief

* Install and activate plugins
  * Site Kit tester plugin
  * [Site Kit Survey Tester plugin](https://app.asana.com/app/asana/-/get_asset?asset_id=1200430197238350)
* In the tester plugin settings
  * Set Force enabled feature flags to Always override
  * Enable the checkbox for the userFeedback feature flag
  * Enable the checkbox for the ideaHubModule feature flag 
* Reset Site Kit
* Go through the Site Kit setup flow
* Go to the dashboard and the survey should be displayed
* Answer the single question that is there, giving a 4 or 5 rating
* Check that the `LET'S GO` button text is uppercase
* Check that the `SETUP` button text of the Idea Hub widget is uppercase

## Changelog entry

* Make text casing in User Feedback and Idea Hub buttons consistent with the rest of the plugin.

**Comment by tofumatt** [comment]
IB ✅

**Comment by cole10up** [comment]
### **QA ✅**

Confirmed survey is there and the uppercase text on the button is present.
![image](https://user-images.githubusercontent.com/57115907/122167556-00acaa80-ce30-11eb-94c4-956ff582e8e8.png)

Confirmed ideahub's button is also uppercase text.
![image](https://user-images.githubusercontent.com/57115907/122167666-233ec380-ce30-11eb-9f0a-177d1c1c11a0.png)

Confirmed both buttons function properly. Sending to testing approved.
