### ISSUE TITLE
Add slide up / down animation to User Feedback survey

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3509]
## Feature Description

The User Feedback survey is missing the slide up / down animation to show / hide the survey.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user input survey box should not just appear, it should have an animation when it appears and disappears:
    * When it appears, it should slide up into view from the bottom of the screen.
    * When it disappears (e.g. completion or dismissal), it should slide down out of view back "into" the bottom of the screen.
* Potentially this can technically use https://material-ui.com/components/transitions/ - this is not a requirement though, just a note.

## Implementation Brief
* Install the `@material-ui/core` package.
* Using `assets/js/components/surveys/CurrentSurvey.js`,
    * Create a new state variable, `animateSurvey` which is a `boolean`, with `false` as default value.
    * Use the `useMount` hook to set the `animateSurvey` to `true`.
    * Create new function `handleAnimationOnExited` which calls the `setValues` action (which can be found in the `dismissSurvey` function) to hide the form. Basically the form is hidden and unmounted when the animation is complete.
    * Wrap the markup for the survey questions (not when it has been completed) within the `Slide` component, imported from `@material-ui/core` with the following props:
        * `direction="up"`
        * `in={ animateSurvey }`
        * `onExited={ handleAnimationOnExited }`
    * Update the `dismissSurvey` function to :
        * set `animateSurvey` to `false`.
        * Remove the `setValues` call since we moved it to the `handleAnimationOnExited` function.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Run storybook locally via the `npm run storybook` command.
* Visit the "Surveys -> Current Survey" story.
* The user feedback survey should slide up upon page load and slide down when closed.

## Changelog entry

* Enhance user survey display with added animation on enter and exit.

**Comment by tofumatt** [comment]
> Make calls to the `sendSurveyEvent` and `setValues` after 1 second, so that the animation has enough time to end.

I'm confused by this, why link the events and the animation? Does this mean we delay sending events until the animation is done to prevent issues with the component being unmounted after the events are completed?

I don't want to overcomplicate the issue, but that seems a bit of a brittle approach to dealing with animations for components.

I suppose we can delay `setValues` actually, but I don't think we need to delay the `sendSurveyEvent` call, because it doesn't affect the UI directly and since it's an AJAX call we should do it as soon as possible 🙂

**Comment by asvinb** [comment]
Thanks for catching that @tofumatt . Actually when I read your comment, am like it's weird that we don't have any callbacks when the animation starts or ends. I checked the docs and voila, we do have the `onExit` callback, which is called when the animation ends :) I've updated the IB to reflect that change.
Also the `Slide` component does have the `unmountOnExit` prop which like the name says, unmounts the children when existing, which we could have used. But then the form data store will not be in sync with that's visible/unmounted on the page. So I guess we can leave that to the data store to handle.

**Comment by tofumatt** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
@asvinb the AC says that `when it disappears (e.g. completion or dismissal), it should slide down out of view back "into" the bottom of the screen` but in your code you have `direction="up"` for the completion component. Shouldn't it be `direction="down"`?

**Comment by asvinb** [comment]
@eugene-manuilov That's what I thought initially while working on this task. As per the docs:
> Direction: the child node will enter from.
So the direction is only for entering, and when exiting the animation, it'll just do the reverse.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the user feedback survey slides up upon page load and slide down when closed. 
- Tested this on storyboard but also on my local site.  Screencast below. 


https://user-images.githubusercontent.com/73545194/123114394-2bea5780-d437-11eb-9e8a-b576ba2912e3.mp4

**Comment by felixarntz** [comment]
@aaemnnosttv It looks like you moved this to "Execution Backlog" after being in "Approval" - was this an accident? :)

**Comment by aaemnnosttv** [comment]
@felixarntz yes, I'm not sure how that happened 🤔 Perhaps mixed up tabs when doing release preparation, or ZenHub got confused? 🤷‍♂️  I'll put it back 😄
