### ISSUE TITLE
Reset does not clear all options and metas

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#351]
## Bug Description

Triggering a reset through Site Kit does not remove the following:

#### User Options
* `googlesitekit_redirect_url`
* `googlesitekit_search_console_property`
* `googlesitekit_site_verified_meta`

#### Options
* `googlesitekit_tracking_optin`  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Covered via #809.
