### ISSUE TITLE
Ensure User Feedback CTA links open in new tab/window

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3510]
## Feature Description

When clicking any of the CTA buttons on the User Feedback survey, please could we ensure the links open in a new tab.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any links that appear in user feedback survey completion prompts (visually displayed as buttons, but technically links) should always open in a new window/tab.
* The buttons (powered by the `Button` component) _should not_ visually include the "external" icon, but they _should_ include screen reader-only text "(opens in a new tab)" - this part should be included via `aria-label` using the same logic that is currently used in the `Link` component.

## Implementation Brief
* Using `assets/js/components/Button.js`,
    * Add the `aria-label` attribute using the same logic as in the `Link` component with the following change to the `getAriaLabel` function:
        * Instead of checking for the non existent `external` prop in the `Button` component, check if `target` is equal to `_blank`
* Using `assets/js/components/surveys/SurveyCompletion.js`,
    * Add the `target` prop to the `Button` component, with `_blank` as value.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Install and activate plugins
  * Site Kit tester plugin
  * [Site Kit Survey Tester plugin](https://app.asana.com/app/asana/-/get_asset?asset_id=1200430197238350)
* In the tester plugin settings
  * Set Force enabled feature flags to Always override
  * Enable the checkbox for the userFeedback feature flag 
* Reset Site Kit
* Go through the Site Kit setup flow
* Go to the dashboard and the survey should be displayed
* Answer the single question that is there, giving a 4 or 5 rating
* Check that the `Let's go` button link opens in a new tab

After being triggered, the survey will not be triggered again for 1 hour. To reset this delay, clear the browser cache and reload the dashboard page.

* The survey should be displayed on the dashboard again
* Answer the single question that is there, giving a 1, 2, or 3 rating
* * Check that the `Get help` button link opens in a new tab

## Changelog entry

* Update button links to show "opens in new tab" ARIA help text, and open all User Feedback links in a new tab.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that when you give a rating of 4 or 5, the `Let's go` button link opens in a new tab.
- Verified that when you give a rating of 1, 2, or 3, the `Get help` button link opens in a new tab.
