### ISSUE TITLE
Update issue template to convert Visual Regression Changes section into a comment in the IB section

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3512]
## Feature Description

Currently, we have the `Visual Regression Changes` section that is used super rarely. Let's convert it into a comment and put it in the Implementation Brief section to remind engineers to add relevant information to the implementation brief when they work on it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Visual Regression Changes` section in all issue templates should be removed.
* Instead, the main comment for the `Implementation Brief` section should be expanded as follows: _One or more bullet points for how to technically implement the feature. Make sure to include changes to Storybook and visual regression tests where relevant._

## Implementation Brief

Inside both `.github/ISSUE_TEMPLATE/feature_request.md` and `.github/ISSUE_TEMPLATE/bug_report.md`:
- Remove the `Visual Regression Changes` section
- Inside the `Implementation Brief` section, add the additional bulletpoint mentioned in the AC.

### Test Coverage

* None needed. 

### Visual Regression Changes

* None needed.

## QA Brief

* Try to create a new issue and see if the VRC section is removed and Implementation Brief section comment is expanded as per AC. 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv I've defined ACs with wording here that makes sense to me - can you check those? If they look good to you, we can move this forward.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by johnPhillips** [comment]
QA ✅

Went to create both a feature request and a bug report and the templates were as per ACs.
