### ISSUE TITLE
Idea draft posts cannot be trashed

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3514]
## Bug Description

As pointed out in https://github.com/google/site-kit-wp/issues/3357#issuecomment-856660512, draft posts that were automatically created based on an Idea Hub idea are initially empty posts (via `add_filter( 'wp_insert_post_empty_content', '__return_false' )`, which WordPress generally doesn't allow. We work around it during draft creation. However, with WordPress's built-in functionality to trash posts, that workaround is obviously not present.

Trashing a post in WordPress is technically an "update" to that post, so WordPress will still fail on it because the post is empty.

It should be possible to delete an idea draft post as expected, either by immediately deleting it or being able to trash it (in that case also untrash it).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When modifying any post **based on an Idea Hub idea** (via related metadata), such a modification should never fail due to the post being empty (i.e. having no title or no content).
    * In other words, the `wp_insert_post_empty_content` filter should be used with a dynamic callback that disables the blocking behavior if the post is an Idea Hub idea post.
    * This should work for any interaction with such a post and any post status.

### Implement `is_idea_post` method
- Add a new private function, `Idea_Hub::is_idea_post`, which should receive a single `$post_id` parameter
- The function should call `Idea_Hub::get_post_idea`, passing the `$post_id`in order to determine whether the given post is an Idea Hub post. 
- It should return `true` if the post is an Idea Hub post and `false` if not.
- Add test coverage for this new method

### Add an empty content filter to bypass Wordpress's default behaviour
- Inside `Idea_Hub::register`, add the  `'wp_insert_post_empty_content'` filter. Call the `is_idea_post` function inside it so that if the given post is an Idea Hub post, the default 'empty post' behaviour is bypassed:
```php
add_filter(
	'wp_insert_post_empty_content',
	function ( $maybe_empty, $post_id ) {
		if ( $this->is_idea_post( $post_id ) ) {
			return false; // Don't consider it empty.
		}
		return $maybe_empty;
	},
	10,
	2
);
```

### Test Coverage

* New coverage should be added for the `is_idea_post` method. Ensure existing tests still pass.

### Visual Regression Changes

* None anticipated

## QA Brief

* Enable the idea hub module via tester plugin, open the console on /wp-admin/admin.php?page=googlesitekit-dashboard,
* Create a draft Idea Hub post:
```js
googlesitekit.data.stores["modules/idea-hub"].actions.createIdeaDraftPost({
    "name": "ideas/7612031899179595408",
    "text": "How to speed up your WordPress site",
    "topics": [
      {
        "mid": "/m/09kqc",
        "display_name": "Websites"
      }
    ]
  })
```
* Go to your WordPress posts, you should see the ideahub draft, now try and trash it. If you were able to trash it, that is a success.

## Changelog entry

* Allow posts with Idea Hub drafts to be trashed.

**Comment by aaemnnosttv** [comment]
@felixarntz given that Idea Hub posts will be "empty" initially, I think we should filter this unconditionally to always allow `wp_insert_post_empty_content` for any Idea Hub post (regardless of status). Otherwise, I think this will come up again in various situations, (e.g. adding a catagory/tag, etc) and seems like a restriction that can safely be turned off for these posts.

I think essentially all we need here is something like this:

```php
add_filter(
	'wp_insert_post_empty_content',
	function ( $maybe_empty, $post_id ) {
		if ( $this->is_idea_post( $post_id ) ) {
			return false; // Don't consider it empty.
		}
		return $maybe_empty;
	}
);
```

`is_idea_post` doesn't exist but would be good to add. It might also be a good idea to add a post meta field explicitly for this purpose rather than relying on name/text/topics? E.g. `googlesitekit_idea_hub_post` meta would always be set to `1` or something. What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv Good point - I've updated the ACs accordingly.

@johnPhillips Please review the above, the code snippet in https://github.com/google/site-kit-wp/issues/3514#issuecomment-858813794 is pretty much what we'll need as a foundation.

**Comment by aaemnnosttv** [comment]
@felixarntz – based on your last comment it isn't clear if you wanted to add the post meta specifically for identifying Idea Hub posts as I suggested. You didn't add it to the AC's so would you like to handle this in a separate issue?

**Comment by felixarntz** [comment]
@aaemnnosttv Oh I missed that suggestion - I don't think that's necessary, let's rely on the three fields being present to know that it is an Idea Hub idea post.

**Comment by aaemnnosttv** [comment]
@felixarntz if we were to want or need to query all Idea Hub posts in the future, which field would we rely on to get them all?

@johnPhillips please update the IB to remove the part about the added post meta. For now the new method can probably just use `Idea_Hub::get_post_idea` internally.

**Comment by ivankruchkoff** [comment]
@tofumatt updated based on CR feedback and added QA brief. Back over to you.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@ivankruchkoff I'm on `develop` branch and idea hub module is enabled via tester plugin. I go to the Site Kit Dashboard and into console and paste the code in the QAB.  The draft post is created but when I click on the trash link, an error appears. 

![image](https://user-images.githubusercontent.com/73545194/123656615-fde68800-d827-11eb-8bf9-3129270713ed.png)

A message appears in the console as well `GET https://unpleasant-lizard.jurassic.ninja/wp-admin/post.php?post=8&action=trash&_wpnonce=b1693c5353 500`

Please also note that when I pasted the code in console an error also appeared, not sure if it's linked:

```
googlesitekit-vendor.346be2e029bd28ac57dd.js:1 POST https://unpleasant-lizard.jurassic.ninja/wp-json/google-site-kit/v1/modules/idea-hub/data/create-idea-draft-post?_locale=user 500

react_devtools_backend.js:2560 Google Site Kit API Error method:POST datapoint:create-idea-draft-post type:modules identifier:idea-hub error:"<p>There has been a critical error on this website.
```
```

**Comment by aaemnnosttv** [comment]
@ivankruchkoff as discussed earlier, I'll open a new issue to address the problem around module activation dependencies.

**Comment by aaemnnosttv** [comment]
New issue: https://github.com/google/site-kit-wp/issues/3514

**Comment by wpdarren** [comment]
I have assigned this back to QA, to re-test this after assistance from Ivan.

**Comment by ivankruchkoff** [comment]
Before trashing the post, we need to ensure that it's created correctly, the 500 critical error implies that there was some sort of error in finalising the creation of the idea hub post.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@ivankruchkoff okay, got further long this time, no error when I created the Idea hub post, and it displays as [expected](https://user-images.githubusercontent.com/73545194/123824397-eaa1ee00-d8f5-11eb-8efe-a077332dd959.png) but when I go to trash the post, I receive a Javascript error 500. 

`GET https://hivevine.com/wp-admin/post.php?post=7290&action=trash&_wpnonce=4d5d33c50d 500`

Here's a screencast 

https://user-images.githubusercontent.com/73545194/123824887-5421fc80-d8f6-11eb-9f13-9c403a50c1cf.mp4

**Comment by felixarntz** [comment]
Any update here on QA @cole10up @wpdarren @ivankruchkoff? Why was there a 500 error before, is that fixed now?

**Comment by cole10up** [comment]
**### QA ✅**

This passed for me. I was able to confirm the ideahub draft and trash functioned properly.

Sending to approval.

**Comment by cole10up** [comment]
### **QA ❌**

@felixarntz - Testing ideahub posts on a different site than the above - I am now seeing an error trying to move the draft to trash on my personal site.

![image](https://user-images.githubusercontent.com/57115907/124879465-1b32f900-df82-11eb-9461-1b6360fb3a5c.png)

I'm going to re-ope this one.

**Comment by felixarntz** [comment]
@cole10up While this is technically QA of this issue, it shouldn't be reopened now, since it targets an already closed release.

We are already aware of _certain_ problems that remain with the existing implementation, with #3639 being the follow-up issue to address those. Can you please post your findings in there, so that it can inform the work on that issue?

**Comment by cole10up** [comment]
Sounds great @felixarntz. Done ^^
