### ISSUE TITLE
Admin can potentially access Site Kit dashboard before Search Console property is set

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#352]
## Bug Description

During the Site Kit setup flow, if you somehow quickly bail out of the flow...
* after site verification has completed
* before Search Console property is set up
...you can access the Site Kit dashboard (and module pages and settings page) afterwards, even though no Search Console property is set. Because of the missing Search Console property, it will obviously appear broken, but it shouldn't be accessible at all then.

## Additional Context

The problem is that the `Permissions::VIEW_DASHBOARD` permission is dynamically granted based on whether the current user is authenticated (and verified if an admin). If the plugin isn't setup yet, you're currently required to be an admin. However, what should happen is that even as an admin, you shouldn't have this capability (or any capability other than `Permissions::AUTHENTICATE` and `Permissions::SETUP`) before the setup is complete.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Permissions other than `Permissions::AUTHENTICATE` and `Permissions::SETUP` are only granted if setup is complete, in addition to the already present checks for being authenticated (and verified if an admin).

## Implementation Brief

* Below https://github.com/google/site-kit-wp/blob/develop/includes/Core/Permissions/Permissions.php#L227, add an extra condition:
```php
// For all users, require setup to have been completed.
if ( ! $prevent_access ) {
	$prevent_access = ! $this->is_setup_complete();
}
```
This ensures that even administrators can't access anything in the plugin beyond setup/authentication-related areas (i.e. the `splash` screen), until the full setup has been completed.

## Changelog entry

* Prevent users on sites without a Search Console property from accessing the plugin dashboard.

**Comment by ThierryA** [comment]
Implementation Brief LTGM!

**Comment by circlecube** [comment]
QA - LGTM -Abandoning setup flow I am not allowed to visit dashboard or settings pages in wordpress admin. Returning and completing setup, I am then allowed to visit admin pages as expected.

**Comment by marrrmarrr** [comment]
LGTM. Verified on 2 sites.
