### ISSUE TITLE
Implement Idea Hub widget functionality for dismissing an idea

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3520]
The Idea Hub widget's functionality to dismiss an idea should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub widget functionality for saving and unsaving an idea should be implemented:
    * When clicking on the x icon in the "New" tab, the idea should be dismissed via the `dismissIdea` action of the `modules/idea-hub` data store. After completing the action, the "New" tab should be "force-refreshed" via re-running the respective API call after clearing its client-side cache.

## Implementation Brief
* Once #3556 has been merged.
* In the `reducerCallback` of the `fetchPostUpdateIdeaStateStore`, remove the idea from the `newIdeas` state variable based on the `ideaName` if `dismissed` is `true`.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js`, 
    * edit the `handleDelete` function to dispatch the async `dismissIdea` action of the module's store, passing the `name` of the idea as parameter.
    * Toggle the `isProcessing` state variable to `true` before calling `dismissIdea` and then `false` afterwards.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Visit the "Idea Hub -> Components -> Widgets -> DashboardIdeasWidget -> Ready"
* Click on the "New" tab. Check functionality to dismiss an idea

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
The processing variables being in a component rather than in the datastore is a bit concerning here because that's not really component-specific state. I can see it's already happening though and maybe we should make that a separate issue.

IB ✅

**Comment by asvinb** [comment]
Implementation has been done when working on #3519 and AC has been fulfilled. Sending to QA.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvinb when on Storybook, this works as detailed in the QAB/AC but I do not see the same behaviour when setting this up on my test site on the develop branch.  Would there be a reason for this?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

When looking at Storyboard as per the QAB:

- The `New` tab. When you click on the `X` icon the idea is removed from the tab.
