### ISSUE TITLE
Remove Idea Hub locale setting and implement minimal settings panel UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3521]
While it was initially assumed an Idea Hub-specific locale would need to be stored, it looks like this is no longer the case. In other words, the Idea Hub module will not have any settings for now.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub module should no longer support the `ideaLocale` settings.
    * For now, the `Settings` class itself and its inclusion in the Idea Hub module should not be removed though, even with it being empty. It is still being discussed whether another setting is necessary instead.
    * The module should for now no longer have any requirements for being "connected".
* The Idea Hub module should receive a settings panel implementation, via a `SettingsView` component (no `SettingsEdit`) in `assets/js/modules/idea-hub/components/settings/SettingsView.js`:
    * It should be similar to the PageSpeed Insights `SettingsView` component, simply stating "To view ideas for new content, visit the dashboard", with "visit the dashboard" being a link to the Site Kit dashboard.
        * Side requirement: The similar sentence in the PageSpeed Insights `SettingsView` should no longer end in a period (see #2597).
    * If you're looking at the settings panel in the Figma file, please ignore that. The design in there is outdated - what we have above is correct.

## Implementation Brief
* Using `assets/js/modules/idea-hub/datastore/base.js`,
    * Add `requiresSetup: false` to the object which is the second parameter of the `createModuleStore` function and remove the `settingSlugs` key.
* Using `assets/js/modules/pagespeed-insights/components/settings/SettingsView.js` as example, create a `SettingsView` component for the `idea-hub` module with the following changes:
    * Remove all `PageSpeed Insights` occurrences.
    * Set the text as per the AC.
* Using `assets/js/modules/idea-hub/index.js`,
    * Add the `SettingsViewComponent` property to the object which is the second parameter of the `registerModule` function, with the value set to the `SettingsView` component created in the previous bullet point.
* Using `includes/Modules/Idea_Hub.php`,
    * Remove all occurrences related to `ideaLocale`. For e.g the `is_connected` and `get_debug_fields` functions can be removed.
* Using `assets/js/modules/pagespeed-insights/components/settings/SettingsView.js`,
    * Remove period at the end of the content.

### Test Coverage
* PHP tests for Idea Hub should be updated remove references to the `ideaLocale` settings.

### Visual Regression Changes
* N/A

## QA Brief

* Ensure that there are no references to `idea-locale`, `idealocale` or `idea locale` in the SiteHealth info;
* Check the Idea Hub settings preview, it should display a message from the AC and contain a link to the dashboard page.

## Changelog entry

* Implement a minimal settings panel for the Idea Hub module.

**Comment by tofumatt** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
@ivankruchkoff could you please add QAB?

**Comment by ivankruchkoff** [comment]
> @ivankruchkoff could you please add QAB?

Updated. Though somewhat tricky to test removing something.

Also, having gone through the whole pipeline of CR I see I missed a step in AC 
`For now, the Settings class itself and its inclusion in the Idea Hub module should not be removed though, even with it being empty. It is still being discussed whether another setting is necessary instead.`

I think given that it's more work to add it back in, unless we need it, let's keep it out for now?

**Comment by eugene-manuilov** [comment]
:man_facepalming: @ivankruchkoff can you create a PR to add it back then?
