### ISSUE TITLE
Implement Idea Hub dashboard notification informing about the module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3523]
A Site Kit dashboard notification should be displayed to inform users about the new Idea Hub module if they have access to it. See the [Figma file](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A181) for UI design.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new notification component `IdeaHubModuleNotification` should be implemented which prompts the user to activate the Idea Hub module.
    * The overall notice should look similar to [this Figma design](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A181) (no need to follow pixel-perfect/design a new component, but follow what we already have in other notifications), _except_ for the buttons which should be left-aligned like we have in all other notifications.
    * Clicking the primary button should activate the Idea Hub module and then redirect to OAuth/module setup as usual.
    * Clicking the dismiss button should dismiss the notice persistently by storing the dismissal on the server-side. This should use the same implementation that #3360 has established, **however it must use a different identifier** (i.e. the dismissals for the notification and the widget CTA should be kept separate, even though they are for a rather similar purpose - we want to make sure people don't "accidentally" dismiss one; they should see both).
    * Notification graphic: The Idea Hub module icon.
    * Notification heading: _Get new ideas to write about based on what people are searching for_
    * Notification text: _Set up Idea Hub to get topic suggestions based on unanswered searches that match your site’s topic._
    * Notification button texts: _Set up_ / _Dismiss_
* The above notification should be shown on the Site Kit dashboard under the following conditions:
    * The `ideaHubModule` feature flag is enabled.
    * The Idea Hub module is not active.
    * The success feedback notification about having connected Site Kit or activated a module is not there (we want to avoid showing both together - it _is_ okay though to show this one alongside any remote `core/site/data/notifications` notifications).

## Implementation Brief
* Once #3360 has been merged.
* Create `assets/js/components/notifications/IdeaHubModuleNotification.js` which exports the `IdeaHubModuleNotification` functional component with the following details:
    * Create a constant for will be the predefined ID of the notification.
    * Check if the module is active by quering the modules data store via the `getModule` function, passing `idea-hub` as paramter and checking the `active` property from the result. If `active` is not `true`, return `null`.
    * Check if the notification has been dismissed by querying the user data store via the `isItemDismissed` selector, passing the ID defined in the first bullet point. If the item has been dismissed, return `null`.
    * Internally `IdeaHubModuleNotification` uses the `Notification` component with the following main prop values:
        * `title`, `description`, `ctaLabel`, `SmallImageSVG` as defined in the AC.
        * `format` should be `small`
        * `type` should be `win-success`
        * `onCTAClick`: more below.
        * `onDismiss` more below.
    * Add the `handleCTAClick` function which is the value for the `onCTAClick` prop. The function should redirect the user to the module setup screen. To get the module setup URL, query the module's data store via the `getAdminReauthURL` selector. Then dispatch the `navigateTo` action of the `core/location` data store to redirect the user. An example can be found in `CompleteModuleActivationCTA`.
    * Add the `handleOnDismiss` function which is the value for the `onDismiss` prop. The function should dispatch the `dismissItem` action of the user data store, passing a notification ID defined in the first bullet point as parameter.
* Using `assets/js/components/legacy-notifications/index.js,
    * import the `IdeaHubModuleNotification` component and create a variable by calling `createAddToFilter` with the component as parameter as it is done for the `UserInputPromptNotification`.
    * The  `IdeaHubModuleNotification` component must be hooked to the `googlesitekit.DashboardNotifications` filter (similar to what's been done with the `UserInputPromptNotification`) based on the following conditions:
        * Check if the `ideaHubModule` feature flag is enabled by using the `isFeatureEnabled` function.
        * Check if `notification` and `setup` are null, which means there are no setup notifications being shown at the same time.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Visit the "Modules -> Idea Hub -> Notications -> ModuleNotification -> Ready"
* The title, description, image should be as per the AC.
* Enable the `ideaHubModule` feature flag and don't connect the module.
* A notification with details as per the AC should appear on the main dashboard prompting the user to connect Idea Hub.
* If dismissed, check if the following XHR is made to `/wp-json/google-site-kit/v1/core/user/data/dismiss-item`

## Changelog entry

* Add Idea Hub dashboard notification to inform users about new Idea Hub module.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvinb my only observation is that on the Site Kit dashboard I see the message at the top as per AC, but also another message appears in the widget area. See screenshot.  It's possible this is expected at this point but thought I would raise it. 

![image](https://user-images.githubusercontent.com/73545194/125974153-21463740-efba-4795-8625-8159b0c2edb3.png)

- The notice looks similar to this Figma design with the buttons left-aligned. 

![image](https://user-images.githubusercontent.com/73545194/125973029-3117f2b5-d120-4b96-8942-7eff8d011aff.png)

- Clicking the `set up` button sends the user to the connect service page. 

![image](https://user-images.githubusercontent.com/73545194/125973313-9417f414-d932-4102-9772-0e5c2ed77f81.png)

- Can view the Notification graphic: The Idea Hub module icon.
- Can view the Notification heading `Get new ideas to write about based on what people are searching for`
- Can view the Notification text `Set up Idea Hub to get topic suggestions based on unanswered searches that match your site’s topic.`
- Can view the Notification button texts: `Set up` / `Dismiss` 
- Clicking the dismiss button dismisses the notice.

**Additional checks:** made sure that the notice appeared correctly for our primary supported browsers, i.e. Firefox, Safari and also mobile devices on Android and iOS.

**Comment by asvinb** [comment]
@wpdarren I think it's expected at that point. Can you confirm @aaemnnosttv ?

**Comment by wpdarren** [comment]
Thanks @asvinb - another observation I have just noticed since re-looking at this.  On the large CTA at the top of the screen. I click on the `Set Up` button. I am then redirected to the connect Idea hub page.  I check the box and click ‘Continue’ button, it redirects me to Site Kit dashboard but it's not connected.   No Google auth page appears is the only thing I noticed. 

The screencast below shows the behaviour.  When I go to Site Kit settings, the module is not connected. 

https://user-images.githubusercontent.com/73545194/126167349-539d27ae-f977-42d6-9818-1b50ffe40c4c.mp4

**Note:** I do not have the Ideas Hub connection plugin installed so this could be the cause, but it works without the plugin when I am using the smaller CTA within the widgets. At this point I do not want to make any assumptions.

**Comment by asvinb** [comment]
Thanks @wpdarren A follow up PR has been created:
https://github.com/google/site-kit-wp/pull/3739

**Comment by aaemnnosttv** [comment]
Back to you for another pass @wpdarren!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The notice looks similar to this Figma design with the buttons left-aligned. 

![image](https://user-images.githubusercontent.com/73545194/125973029-3117f2b5-d120-4b96-8942-7eff8d011aff.png)

- Clicking the `set up` button sends the user to the connect service page. 

![image](https://user-images.githubusercontent.com/73545194/125973313-9417f414-d932-4102-9772-0e5c2ed77f81.png)

- Can view the Notification graphic: The Idea Hub module icon.
- Can view the Notification heading `Get new ideas to write about based on what people are searching for`
- Can view the Notification text `Set up Idea Hub to get topic suggestions based on unanswered searches that match your site’s topic.`
- Can view the Notification button texts: `Set up` / `Dismiss` 
- Clicking the dismiss button dismisses the notice.

**Additional checks:** made sure that the notice appeared correctly for our primary supported browsers, i.e. Firefox, Safari and also mobile devices on Android and iOS.
