### ISSUE TITLE
Implement Idea Hub module feature tour(s)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3524]
Once the Idea Hub module is set up, a feature tour should be added to explain the new functionality. Potentially, another feature tour with a single tooltip should be added also on the Site Kit settings screen, to point to the new Idea Hub module when it's not yet activated.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

A new tooltip tour `ideaHubModule` should be displayed on the Site Kit dashboard _if_ the `ideaHubModule` feature flag is enabled. Additional requirements to show the tooltip:
* The Idea Hub module is active.
* The user has successfully completed Idea Hub setup.
* There are "new" ideas available in the Idea Hub widget.

Under these conditions, a tour of 3 tooltips should be displayed the next time the user logs in, to explain the following key concepts:
     * Where ideas come from and how frequently they refresh 
     * How to start a draft 
     * How to manage ideas (save & dismiss) 

**Tooltip 1**
* Position: near heading of the Idea Hub widget
* Heading: _Get inspiration for new topics to write about!_ 
* Body: _These ideas are based on unanswered searches related to the content of your site. They are organised by topics and will refresh every 2-3 days._ 

**Tooltip 2**
* Position: point to the "start a draft" icon
* Heading: _Start a draft_
* Body: _Found an interesting idea you want to write about? Create a draft! You can always get back to it later on the Posts page._ 

**Tooltip 3** 
* Position: point to the "save for later" and "dismiss" icons 
* Heading: _Save for later or dismiss_ 
* Body: _If you're not ready to create a draft about an idea just yet, add it to your "Saved" list and revisit later._ 
_If you don’t like an idea, you can dismiss it from your list._ 

## Implementation Brief

* Create a new file `assets/js/feature-tours/idea-hub-module.js` that exports an object with the following properties:
  * `slug` should be `ideaHubModule`;
  * `contexts` should be an array with `VIEW_CONTEXT_DASHBOARD` value;
  * `version` should be `1.36.0`; - with an @TODO - change this version if the launch version for the feature changes.
  * `checkRequirements` should check the following:
    * Idea Hub Module is active `["core/modules"].selectors.isModuleActive('idea-hub')`
    * The user has successfully completed Idea Hub setup. -  `["core/modules"].selectors.isModuleConnected('idea-hub')`
    * There are "new" ideas available in the Idea Hub widget. `["modules/idea-hub"].selectors.getNewIdeas()`
  * `steps` should be an array with three items: 

  1)
    * `target` selector: `.googlesitekit-idea-hub__title` see: assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js
    * `title` should be `Get inspiration for new topics to write about!`;
    * `content` should be `These ideas are based on unanswered searches related to the content of your site. They are organised by topics and will refresh every N days.`;

  2)
    * `target` selector: `.googlesitekit-idea-hub__actions--create`, this should be the first one and needs to be added to `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js` in https://github.com/google/site-kit-wp/blob/66de0dde8f218887787ce87cd224ef53edcf707e/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L119
    * `title` should be `Start a draft`;
    * `content` should be `Found an interesting idea you want to write about? Create a draft! You can always get back to it later on the Posts page`;

  3)
    * `target` selector: `.mdc-button googlesitekit-idea-hub__actions--pin` see: `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js`
    * `title` should be `Save for later or dismiss`;
    * `content` should be `If you're not ready to create a draft about an idea just yet, add it to your "Saved" list and revisit later.
If you don’t like an idea, you can dismiss it from your list.`;

* Add your tour to `assets/js/feature-tours/index.js`, loading it conditionally based on whether or not the feature flag `ideaHubModule` is enabled.

Test out your tooltip, you may need to play around with `placement` param for each step to ensure the tooltip is in a good position.

Addd new storybook story for the tooltip tour in https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-idea-hub-widgets-dashboardideaswidget--ready see the following as an example: https://google.github.io/site-kit-wp/storybook/main/?path=/story/global--tourtooltips

### Test Coverage

* Update backstop VRT to cover the new tooltip tour. 

### Visual Regression Changes

* Added new tests as above.

## QA Brief

* Set up a site with the `ideaHubModule` feature flag enabled, and add the tester plug in.
* Install the `Test Idea Hub connection` plugin ([shared in Slack](https://10up.slack.com/files/UDVPF8UR5/F0286PXDGD6/google-site-kit-idea-hub-force-connected.1.0.1.zip)) to force connect Idea Hub
* Use the tester plugin to set the Site Kit version to 1.36.0 so that only the Idea Hub feature tour runs.
* Go to the dashboard, see the Idea Hub feature tour.
* Verify that the ACs are met.
* Visit Storybook and view the new story at `?path=/story/modules-idea-hub-feature-tour--default-feature-tour` for additional checking.

## Changelog entry

* Add a new feature tour for the Idea Hub widget.

**Comment by marrrmarrr** [comment]
@felixarntz have a look and lmk if you have any questions on the ACs.

**Comment by felixarntz** [comment]
@marrrmarrr Overall sounds good, I've amended the ACs a bit to describe the requirements a bit more separately and defined an internal identifier to use for the feature tour.

I've split out the second separate feature tour you had added here into another issue #3625 - let's discuss this further before moving ahead because there are some additional complexities there (it would be a feature tour that doesn't appear on a Site Kit-owned screen, which is technically more tricky).

**Comment by ivankruchkoff** [comment]
Over to IBR, with a few questions:

`The user has successfully completed Idea Hub setup.` - what criteria can we use here? I think isActive + hasIdeas from the surrounding points will cover it off.

> Position: point to the "save for later" and "dismiss" icons

Can we point at two items in a tooltip? Or is the supplied target sufficient (pin icon)

I saw that we don't add storybook for each step of each tour and backstop screenshots in https://github.com/google/site-kit-wp/issues/2739 or https://github.com/google/site-kit-wp/issues/2847 makes sense to me to add these and that way we can catch regressions since I imagine we won't see them often when testing.

**Comment by felixarntz** [comment]
@ivankruchkoff 
> `The user has successfully completed Idea Hub setup.` - what criteria can we use here? I think isActive + hasIdeas from the surrounding points will cover it off.

It is sufficient here to check whether the module is "connected" in addition to "active" - "connected" essentially means the setup is complete.

> Can we point at two items in a tooltip? Or is the supplied target sufficient (pin icon)

Yes, pointing to the pin icon is sufficient. The idea is to just point to the general area (just in case there's a selector for e.g. a `div` that wraps both icons - but if not, pointing to the pin icon works too).

> I saw that we don't add storybook for each step of each tour and backstop screenshots in #2739 or #2847 makes sense to me to add these and that way we can catch regressions since I imagine we won't see them often when testing.

I think it's sufficient for now to create a single Storybook story that allows to walk through the tooltip tour (e.g. similar to https://google.github.io/site-kit-wp/storybook/main/?path=/story/global--tourtooltips). We don't need a story for each tooltip - although your point is valid, but we need to revisit our Backstop implementation and what we include there anyway, so let's not focus on that too much for now.

Regarding the rest of the ACs:
> `version` should be `1.29.0`;

Let's set this to `1.36.0` for now - this may still change later, it should eventually have the version where this feature will launch. Can you therefore note in the IB to also add a `TODO` comment on it?

The only thing missing from the IB is to consider the `ideaHubModule` feature flag. The entire feature tour definition should only be added to the array if that feature flag is active.

Other than those pieces, the IB looks good. Some general feedback, you don't need to re-iterate on all pieces of copy etc which is already defined in the ACs - you can just reference it, e.g. "set copy for each tooltip per the ACs". That results on less writing needed for you, and it also avoids confusion, should the AC worrding be slightly amended before execution, which by having it in the IB would require double work to change it.

**Comment by marrrmarrr** [comment]
@felixarntz I left the refresh rate unclear for now in the tooltip text -- how frequently will prompts be refreshed? If this is already clear, let's update the tooltip.

**Comment by felixarntz** [comment]
@marrrmarrr We still haven't received this information, I'll bring it up again with the API team this week. For now, let's use "will refresh every 2-3 days", which is what we already have in the codebase on the widget itself. We can update this later, but it shouldn't block this issue.

**Comment by ivankruchkoff** [comment]
@felixarntz 
> 
> It is sufficient here to check whether the module is "connected" in addition to "active" - "connected" essentially means the setup is complete.

Updated.

> 
> I think it's sufficient for now to create a single Storybook story that allows to walk through the tooltip tour (e.g. similar to https://google.github.io/site-kit-wp/storybook/main/?path=/story/global--tourtooltips). We don't need a story for each tooltip - although your point is valid, but we need to revisit our Backstop implementation and what we include there anyway, so let's not focus on that too much for now.

Updated, I left the reference to backstop to cover the single story being loaded, but can remove that too.


> Let's set this to `1.36.0` for now - this may still change later, it should eventually have the version where this feature will launch. Can you therefore note in the IB to also add a `TODO` comment on it?
Updated

 
> The only thing missing from the IB is to consider the `ideaHubModule` feature flag. The entire feature tour definition should only be added to the array if that feature flag is active.
Updated, my initial thoughts were that all the selector classes contained  `.googlesitekit-idea-hub` and thus would not ever appear.

> 
> Other than those pieces, the IB looks good. Some general feedback, you don't need to re-iterate on all pieces of copy etc which is already defined in the ACs - you can just reference it, e.g. "set copy for each tooltip per the ACs". That results on less writing needed for you, and it also avoids confusion, should the AC worrding be slightly amended before execution, which by having it in the IB would require double work to change it.

Noted.

**Comment by felixarntz** [comment]
@ivankruchkoff Excellent - IB ✅

**Comment by johnPhillips** [comment]
@felixarntz or @ivankruchkoff Can I ask what `gaEventCategory` I should pass for this feature tour? It seems to be a required prop.

**Comment by johnPhillips** [comment]
@ivankruchkoff and @felix 
I have run into a bit of unforeseen complexity regarding the third step (`Save for later or dismiss`). It's targeting a hidden element (the 'pin' button is `display: none` and only appears on hover). This means the `target` fails and the third step errors with `Target not visible`.

I've had a look around the docs and a bit of an experiment, and the best solution I currently have is something like:
- Add support for a new optional `callback` prop to [the `TourTooltips` component](https://github.com/google/site-kit-wp/blob/11cbd83725aa2efede6eced41870535721e5fd0d/assets/js/components/TourTooltips.js)
- At the end of the [`handleJoyrideCallback ` function](https://github.com/google/site-kit-wp/blob/11cbd83725aa2efede6eced41870535721e5fd0d/assets/js/components/TourTooltips.js#L157 ), call this new `callback` prop, passing on Joyride's `data` param.
- Add a new class in `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`, e.g. `googlesitekit-idea-hub__actions--pin-visible` that does `display: block` in a `$bp-tablet` media query, to cancel out the rule at line [113](https://github.com/google/site-kit-wp/blob/8a453ed75bc2ddd7066eaa535a8d77e859c3e34f/assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss#L113)
- Inside the new Idea Hub tour, add the new callback option. We could then use JQuery (seems to be available long term as a global?) to toggle the new class, for example:
```js
const STEPS = [
    { /* step 1 */ },
    { /* step 2 */ },
    {
      target: '.mdc-button.googlesitekit-idea-hub__actions--pin',
      // ...
    },
];

const ideaHubModule = {
  // ...
  steps: STEPS,
  callback: ( data ) => {
    const firstPin = `${ STEPS[ 2 ].target }:first`;

    if ( /* After second step and before third step */ ) {
      global.jQuery( firstPin ).add( 'googlesitekit-idea-hub__actions--pin-visible' );
    }

    if (  /* After third step */ ){
      global.jQuery( firstPin ).remove( 'googlesitekit-idea-hub__actions--pin-visible' );
    }
  },
}
```
What do you think?

**Comment by felixarntz** [comment]
@johnPhillips @ivankruchkoff Maybe we can simply point at the container around the pin and dismiss elements instead? The tooltip is about pinning and dismissing anyway, so we don't really need to point at one specific icon. Regardless of whether we can force-show the icons or not, I think pointing at their always visible container makes sense (and avoids any potential errors from something not being visible).

If there is a way though to make the two icons visible _in addition to the above_, then that would be super neat though - let's not use jQuery though :)

**Comment by johnPhillips** [comment]
Good point @felixarntz, for some reason I hadn't realised that step was about dismissing as well as saving. I think your suggestion of targeting the container makes a lot of sense, so I will do that 👍

Now I've got my head around Joyride, I can certainly use the callback to add a class to those buttons so they are visible for this step as well. Is something like this ok?

![Screenshot 2021-07-12 at 11 55 28](https://user-images.githubusercontent.com/2470911/125276729-75c4b000-e308-11eb-973b-2b9078b4f4b8.png)

Done without jQuery :-)

**Comment by felixarntz** [comment]
@johnPhillips That looks great to me.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@johnPhillips I have a few observations:

1. On Tooltip 1 the text reads `They are organised by topics and will refresh every N days.` whereas the AC says `They are organised by topics and will refresh every 2-3 days.` 
2. The feature tour disappears on small screen sizes like tablets and mobiles.
3. On Tooltip 2 there is no period/full stop at the end of the paragraph `Create a draft! You can always get back to it later on the Posts page` I am assuming it should have since it's part of two sentences. 
4. On Tooltip 3 the location is to the side of the topic idea as per screenshot but wondering if we be more helpful above the save and dismiss icons. 

![image](https://user-images.githubusercontent.com/73545194/125971117-fdb1205d-11f6-47f7-9ebe-200bc0395807.png)

**Comment by johnPhillips** [comment]
Hi @wpdarren, thanks for this. 

> On Tooltip 1 the text reads They are organised by topics and will refresh every N days. whereas the AC says They are organised by topics and will refresh every 2-3 days.

Ouch 🙈  I must've copied from the IB instead of the ACs. Good catch - I'll make a PR

> The feature tour disappears on small screen sizes like tablets and mobiles.
This is intentional, I believe (see https://github.com/google/site-kit-wp/issues/3003)

> On Tooltip 2 there is no period/full stop at the end of the paragraph Create a draft! You can always get back to it later on the Posts page I am assuming it should have since it's part of two sentences.

Good catch again :-) I'll add that to the PR

> On Tooltip 3 the location is to the side of the topic idea as per screenshot but wondering if we be more helpful above the save and dismiss icons.

This is how it looks with `placement` set to `'top'`:

![Screenshot 2021-07-16 at 17 15 39](https://user-images.githubusercontent.com/2470911/125978710-5c73bcc8-38d0-48c6-873e-b50ce01abab6.png)

Very happy to update it if this is preferred - @felixarntz would you like to provide a final verdict?

**Comment by johnPhillips** [comment]
I've opened a PR and provisionally set the `placement` to `'top'` - very easy to revert this if we decide against it 👍

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 


- Verified that tooltip 1 is near heading of the Idea Hub widget, with a heading of `Get inspiration for new topics to write about!`and body `These ideas are based on unanswered searches related to the content of your site. They are organised by topics and will refresh every 2-3 days.`

![image](https://user-images.githubusercontent.com/73545194/126494619-01445e19-5f8f-4989-8918-7134c3e3bbd9.png)

- Verified that tooltip 2 points to the "start a draft" icon with a heading of `Start a draft` and a body `Found an interesting idea you want to write about? Create a draft! You can always get back to it later on the Posts page.`

![image](https://user-images.githubusercontent.com/73545194/126494640-dacb0f40-e604-4d16-a368-4dfe321a2483.png)

- Verified that tooltip 3 points to the "save for later" and "dismiss" icons, with a heading of `Save for later or dismiss`
and body `If you're not ready to create a draft about an idea just yet, add it to your "Saved" list and revisit later. If you don’t like an idea, you can dismiss it from your list.`

![image](https://user-images.githubusercontent.com/73545194/126494666-ea242b4f-1552-4e2d-8fb9-e86c249db45c.png)
