### ISSUE TITLE
Intermittent VRT false positive

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3526]
## Bug Description

A VRT test for the hover button state is intermittently failing.  We should investigate and fix this, or just disable the test.

Also amazing would be to have the backstop reports hosted somewhere as it takes a while to download and extract the artifact *but* if we stop this false negative then it will be less of a problem

## Steps to reproduce

See this false-negative -> https://github.com/google/site-kit-wp/pull/3404/checks?check_run_id=2782120401
Note I haven't changed the Button component.  I can find many other failing commits on other PRs

## Screenshots

![flaky-button](https://user-images.githubusercontent.com/8496063/121328649-c9606a00-c914-11eb-8619-2877a21cb0bc.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @danielgent – I missed this and we have another issue for it which is farther along so I'll close this one in favor of #3552 .
