### ISSUE TITLE
Update E2E bootstrap to simplify test set up and tear down

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#353]
## Feature Description

Currently, there are certain actions which are being performed in nearly every E2E test that will likely need to be done in all tests, such as resetting Site Kit. This should be performed in the set up for each test by pulling these repetitive actions into the e2e bootstrap file.

Suggested Site Kit utilities to add to bootstrap:
* `resetSiteKit()` https://github.com/google/site-kit-wp/pull/348#discussion_r308745508
* `deactivateAllOtherPlugins()` https://github.com/google/site-kit-wp/pull/348#discussion_r308813872

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Since we had troubles with the e2e tests in #377, I ended up actually implementing this there. So this can be considered done 🙂
