### ISSUE TITLE
User feedback survey to be centered on mobile

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3530]
## Feature Description

On desktop the user feedback survey is appearing on the right, however on mobile it appears to be left aligned to the user. Please could we ensure the user feedback survey is centered at mobile.

![image](https://user-images.githubusercontent.com/56588136/121338371-5acfdc00-c915-11eb-8884-f4e496f513b9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the screen width is smaller than the user feedback survey width plus its right margin from the right end of the window (or at a reasonably small breakpoint where this will most likely happen), the user feedback survey should have its style adjusted to no longer be right-aligned.
    * It should instead fill the full width of the screen (this is how it is done for surveys in Google's own services). (For this reason, that style should only kick in in _very_ narrow screens.)

## Implementation Brief
* Using `assets/sass/components/surveys/_googlesitekit-surveys-modal.scss`,
    * Set the `bottom` and `right` CSS properties to `0`.
    * As from a `400px` breakpoint, set the `bottom` and `right` properties to `24px`.
    * As from the `xlarge` breakpoint (1280px), set the `bottom` and `right` properties to `34px`.
* Using `assets/sass/components/surveys/_googlesitekit-surveys.scss`,
    * Set the `max-width: 400px` rule as from a `400px` breakpoint.

### Test Coverage
* No tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* install and activate the [User feedback survey tester plugin](https://app.asana.com/app/asana/-/get_asset?asset_id=1200430197238350)
* go to Site Kit > Tester Settings
  * set Force enabled feature flags to Always override
  * enable the checkbox for the userFeedback feature flag
* go to the dashboard and the user feedback survey modal should be displayed.
* check the position of the modal on mobile, tablet and desktop as per the IB

## Changelog entry

* Improve user survey styling on mobile viewports.

**Comment by tofumatt** [comment]
Sounds good to me 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
### QA Update ❌ 

@Hazlitte for mobiles with wider screens, i.e. wider than 396 pixels, Google Pixel, then the Feedback survey still is left aligned.  Is this something we can fix easily?  You can see it in action on this screencast. 

https://user-images.githubusercontent.com/73545194/123667890-7b16fa80-d832-11eb-92e7-ecc744ee4647.mp4

**Comment by Hazlitte** [comment]
@wpdarren Good catch 🙂 I've just made some changes to the SASS for large width mobiles and done a small PR.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the feedback survey is centered on mobile devices. Tested this on various small screen sizes and primary browsers.  - [Screenshot](https://user-images.githubusercontent.com/73545194/123805616-21700800-d8e6-11eb-8cf0-cfab31a21f5b.png)
