### ISSUE TITLE
Add selected state of 300ms to user feedback survey

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3531]
## Feature Description

When one of the emoji is clicked, it instantly goes to the next state, there need to be a selected state for a moment(300ms) to show that it is selected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After selecting an emoji in the user feedback survey question of the rating type, the current UI should remain visible for a tiny bit longer before showing the next question (or completion prompt, depending on the survey). The selected emoji should show up in a selected/active state (i.e. same background/outline etc. like when hovering over it).
    * This can either be accomplished by e.g. a manual 300ms timeout, or another option would be to wait for the relevant `/survey/event/` request to succeed before switching to the next UI.

## Implementation Brief
* Using `assets/js/components/surveys/CurrentSurvey.js`,
	* Add a new state variable `hasAnsweredQuestion`, boolean with `false` as default value.
	* Update the `answerQuestion` function to:
		* Wrap the existing logic within a condition where `hasAnsweredQuestion` is `false`.
		* After the condition, set `hasAnsweredQuestion` to `true`, which means that if the user answers a question for the first time, the function will dispatch `sendSurveyEvent` and `setValues` actions and then `hasAnsweredQuestion` is `true`.
		* Call `setValues` after `300ms` using `setTimeout`, and in the callback function, set `hasAnsweredQuestion` to `false` as well.

### Test Coverage
* No new tests to be added. Existing tests must pass.

### Visual Regression Changes
* N/A

## QA Brief

* Visit https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys-currentsurvey--survey-multiple-questions-story
* Go through the questions (there should be more than two) and observe that the question text only changes after 300ms

## Changelog entry

* Add selected state of 300ms to user feedback survey

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue!

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB almost looks good. However, let's also protect the `answerQuestion` callback from double clicks to avoid calling the `sendSurveyEvent` action multiple times. Could you please update the IB to account for it?

**Comment by asvinb** [comment]
Good catch @eugene-manuilov . IB updated.

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB :heavy_check_mark:

**Comment by danielgent** [comment]
Looking at the demo on storybook (for me at least anyway on Ubuntu Chrome) the previous answer actually stays selected visually when progressing to the next answer
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys-currentsurvey--survey-multiple-questions-story

So not only do we already have some form of visual feedback for the previous answer, but also it seems weird the question changes after 300ms but the smiley face looks selected

In the branch I'm working on I'm resetting this selected visual state every time the question is answered (by using the question text as the key for the inner `SurveyQuestionComponent`
https://github.com/google/site-kit-wp/compare/enhancement/3531-user-feedback-survey-300ms#diff-0a44335e071253157aece8b6644d88a6cb6c745c9ff3a3f8cdff6abbf7b2a0bbR198

**Comment by danielgent** [comment]
So this task was given a 3 hour time estimate but there is no mention of the changes to the tests in the IB, it just says `Existing tests must pass.` (which of course they won't without changes!

From my experience, any use of `setTimeout` makes testing in Jest and React Testing Library very challenging.  I imagine we'll need to use Jest's fake timers e.g. `jest.useFakeTimers();` in order that these tests don't take a long time to run and trigger React Testing Library timeouts

**Comment by danielgent** [comment]
Surprisingly I don't see any difference in the time taken to test! So this PR is good to go IMHO :+1:

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Difficult to test this but having chatted with @danielgent I can see there's a very slight delay for the next question to appear after clicking one of the icons.  Recorded this screencast. 

https://user-images.githubusercontent.com/73545194/124765243-0f214a00-df36-11eb-9535-bc1e89869590.mp4
