### ISSUE TITLE
Clicking Set up a new account in 'Account' dropdown doesn't load anything

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3537]
## Bug Description

Clicking 'Set up new account' from the 'Account' dropdown never loads, it is in a constant spinning state

[Related Asana task](https://app.asana.com/0/1200316599642381/1200447894111338)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When choosing the "Set up a new account" option in the Analytics setup / settings account dropdown, the UI should not get stuck in an endless loading state.

## Implementation Brief

* Merge #3585

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Create a new site on jurassic.ninja
* Set up SK using a user that has no Google Analytics accounts
* Activate the Analytics module
* Make sure that the setup form loads correctly and doesn't display infinite progress bar

## Changelog entry

* Fix an infinite loading state when attempting to create a new Analytics account with GA4.

**Comment by eugene-manuilov** [comment]
Hm.... I can reproduce it neither on my local nor on a jurassic site... @jamesozzie can you still reproduce it? Can you give me access to your site if it still doesn't work on your end?

**Comment by eclarke1** [comment]
@jamesozzie just a polite reminder here to please let us know if you can reproduce this, or please provide @eugene-manuilov access to the site?

**Comment by jamesozzie** [comment]
@eclarke1 @eugene-manuilov  I'm unable to recreate this on the same site where this occurred previously.  

While trying to reproduce on the same site I'm not always able to proceed, it depends on the account selected. This seems more in line with #3535 although if you can take a look [at this example](https://recordit.co/h6GUFmKPi9) you'll see a `SetupFormGA4Transitional` notice appears. I'll continue testing this on another site.

**Comment by bethanylang** [comment]
@eclarke1 @eugene-manuilov I was able to reproduce this on two separate sites today: https://hostgator2.cmsdevrel.com/ and https://cmsdevrel.wpcomstaging.com/.

In both cases, I was able to successfully set up Search Console as the first step of SK setup. When I was returned to the Dashboard, I clicked Connect service for Analytics, approved the connection to my Google account, and then got the neverending loading bar.

https://jmp.sh/D5EXxSa+/Screen+Recording+2021-06-15+at+1.06.06+PM.gif

Both of these have logins available on the support testing sheet, which I'll share with you separately.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

- On a new site, set up with Sk for a user that has no GA account. I was able to activate the Analytics module, and the setup form loaded successfully, no infinite progress bar appears.  I was able to go through the process of setting up an account with no errors on the FE or on console.   As you can see from the screenshot below, the GA4 and UA properties were created.

- In addition, I also checked that Google Analytics was showing the newly created properties. 

![image](https://user-images.githubusercontent.com/73545194/122246959-e4a41a00-cebe-11eb-9036-3873afbd871f.png)
