### ISSUE TITLE
Can't submit the setup form when an account has UA and GA4 properties with different website URL

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3538]
## Bug Description

Can't submit the setup form when an account has UA and GA4 properties with different website URL. Looks like it happens because there is no matching web data stream for the current site

![cantsave](https://user-images.githubusercontent.com/873049/121718168-aab3cc00-caea-11eb-9952-a851e553bca8.png)

[Related Asana task](https://app.asana.com/0/1200316599642381/1200447371742681)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Analytics setup flow, if no matching web data stream for the current site already exists in the selected GA4 property, it should still be possible to submit the form.
    * In that case, the new web data stream should be created, then set upon submission.
    * This is possibly related to a similar bug in the Analytics settings screen (see #3535).

## Implementation Brief

* Merge #3565

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Create a new jurassic site
* Setup the SK plugin
* Activate the Analytics module
* On the setup form, select an account that has both GA4 and UA properties, but neither of them matches the current website URL.
* Select UA and GA4 properties and make sure that you can save the form.
* Save the form and verify that a new web data stream is created for the current website.

## Changelog entry

* Fix a problem where Analytics settings cannot be saved when selected account has UA and GA4 properties with different URLs.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that a new web data stream is created for the current website.

![image](https://user-images.githubusercontent.com/73545194/122087164-54050580-cdfc-11eb-8107-7fdf0c7ca35e.png)
