### ISSUE TITLE
Styling of property select in GA4 notice on settings page looks off

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3541]
## Feature Description

Styling of the Property select dropdown is grey instead of blue as per designs.

![image](https://user-images.githubusercontent.com/56588136/121393446-40632600-c948-11eb-813a-b51d691aa9a2.png)

Please see [Figma comment](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB?node-id=20269%3A8810&fuid=758316026848078147#86348586) here also

[Related Asana task](https://app.asana.com/0/1200316599642381/1200441839407999)
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When displayed within an info notice, any text input field should have similar appearance to the dropdowns, using a blue border etc.

## Implementation Brief

* Update `assets/sass/components/settings/_googlesitekit-settings-notice.scss` to include the styles for `.mdc-text-field` similar to what's being done for `.mdc-select`

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

Note that the fix is for the screenshot on this comment https://github.com/google/site-kit-wp/issues/3541#issuecomment-866716827
**NOT** the screenshot in the description

* Have a UA and a GA4 property set up in Analytics for a site
* Set up Site Kit on site
* Start Analytics set up
* select GA4 property
* Inside Notice component select "set up a new property"
* should now be in the same state as on the screenshot
* Observe text input is styled like selects (hover state, selected state, etc)

## Changelog entry

* Update styles of controls in the GA4 notice box on the settings page.

**Comment by asvinb** [comment]
@eclarke1 @aaemnnosttv I can't reproduce this issue. Is it browser specific? I tested in the following browsers and the select looks good to me:

Firefox:
![image](https://user-images.githubusercontent.com/31818/123071768-fdb04c00-d425-11eb-8e36-489b3299d83d.png)

Safari:
![image](https://user-images.githubusercontent.com/31818/123071801-056ff080-d426-11eb-9ca1-2b8ca92f5bbf.png)

Chrome:
![image](https://user-images.githubusercontent.com/31818/123071846-0f91ef00-d426-11eb-82f2-1aa5fd65fdcd.png)

**Comment by aaemnnosttv** [comment]
@asvinb I think this one can be closed. This issue was created out of the bug bash but I had a PR in progress which fixed this at the time.

Assigning back to @felixarntz for review but I think this is no longer an issue.

**Comment by aaemnnosttv** [comment]
Actually, I just noticed that the styles are off for other inputs in this context such as when creating a new view. I believe this is due to the current styles only accounting for select components in an info notice, so perhaps this issue could be redefined more generally?

![image](https://user-images.githubusercontent.com/1621608/123080671-db1e3300-d425-11eb-8efe-885de0a974f5.png)

**Comment by asvinb** [comment]
@aaemnnosttv I've added the IB to cater for the text input.

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb Thanks, makes sense. I've rephrased the ACs - and the IB already looks good ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- For a site with UA and a GA4 property set up in Analytics. When you select GA4 property and then 'Set up new property' in the notice component, the property, view and view name fields have blue borders, blue text.  Can also confirm that the text input is styled appropriately.  
- Checked this also in our primary browsers, i.e. Firefox, Safari, etc. 

![image](https://user-images.githubusercontent.com/73545194/124619938-5a295780-de79-11eb-9524-75cc89cc9f54.png)
