### ISSUE TITLE
Account with GA4 property only is not preselected on the setup form

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3543]
## Feature Description

Account with GA4 property only is not preselected on the setup form

[Related Asana ticket](https://app.asana.com/0/1200316599642381/1200447371742671)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On pageload of the Analytics setup flow (with `ga4Setup` flag enabled): When you have an account that has only GA4 properties _one of which has a web data stream for your current site URL_ and no account has a UA property that matches your current site URL, the matching GA4 property (and its account of course) should be preselected.
    * This effectively lands you in the `ga4` version of the setup flow, since that account has only GA4 properties.
    * If you have any UA property that matches the current site URL among your accounts, that should still take precedence. This issue is particularly for the case that you have only a matching GA4 property somewhere, but no matching UA property.
* Essentially, once preselected you should land in this UI: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-setup-setupformga4--without-existing-tag

## Implementation Brief

* Merge #3590

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Create a new jurassic site.
* Create a new Google Analytics account that has only GA4 property with the new website URL.
* Install and activate the SK plugin.
* Set up the plugin and activate the Analytics module.
* On the Analytics setup form, verify that you see your new Google Analytics account with the appropriate property. preselected.

## Changelog entry

* Ensure account and property are preselected during setup when user has a matching GA4 property only.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that for a GA4 property only, on the Analytics setup form, the new Google Analytics account with the appropriate property is preselected.

![image](https://user-images.githubusercontent.com/73545194/122575957-206aeb00-d049-11eb-8614-95ae8345a7b0.png)
