### ISSUE TITLE
Display measurement ID on the analytics settings page next to GA4 Property ID

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3545]
## Feature Description

Display measurement ID on the analytics settings page instead of ga4 property ID or next to it. Show measurement ID as well as Property, with the GA4 property below the blue link.

![image](https://user-images.githubusercontent.com/56588136/121396255-152e0600-c94b-11eb-9e18-c9fe2cd88bb9.png)

[Related Asana task](https://app.asana.com/0/1200316599642381/1200447371742663)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the `ga4Setup` feature flag is enabled and a GA4 property (and its web data stream plus the web data stream's measurement ID) is set, the measurement ID should be displayed in Analytics `SettingsView`, on the right of the "Google Analytics 4 Property" field.
    * Its label should be "Google Analytics 4 Measurement ID", but visually appear as "Measurement ID". As it's next to the "Google Analytics 4 Property" field, it will be visually clear that they're related, but we should still use a fully-descriptive label for accessibility purposes.
* The measurement ID should not appear when editing, since it is derived from the Google Analytics 4 Property selected.

## Implementation Brief
- Using `assets/js/modules/analytics/components/settings/SettingsView.js`,
    - Get the GA4 measurement ID via the `getMeasurementID` selector of the GA4 data store.
    - Duplicate the markup of the section (the `googlesitekit-settings-module__meta-item` container ) where the GA4 property ID is displayed with the following updates:
        - Label should be as per AC, prepended by `Google Analytics 4`. The latter should be wrapped between the `VisuallyHidden` so that it's only visible to screen readers to provide context for the user.
        - Value should be the GA4 measurement ID.
- Add story to reflect the state of the component

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Enable the `ga4setup` feature
* Set up Analytics with an account that includes a GA4 property ([these instructions may help](https://app.asana.com/0/1200316599642381/1200379030254853))
* Navigate to the Analytics settings (`/wp-admin/admin.php?page=googlesitekit-settings#settings/analytics/view`)
* Verify that the correct `measurementID` is present on the settings overview as per the ACs.
* Right click the `Measurement ID` subtitle in order to inspect the source code.
* Verify that the full text of the title is `Google Analytics 4 Measurement ID`, but that the `Google Analytics 4` substring is inside a `<span class="screen-reader-text">` and is therefore visually hidden.

## Changelog entry

* Display measurement ID for Google Analytics 4 property in Settings.

**Comment by tofumatt** [comment]
> Its label should be simply "Measurement ID". It's next to the "Google Analytics 4 Property" field which should make it obvious enough that this is also related to GA4.

Unfortunately this isn't great for accessibility and won't be clear to someone navigating the page without sight, as to them the contents will appear one-after-the-other without visual/grid context,

The label should contain all relevant information, but contents can be partially visually hidden, eg.: `<VisuallyHidden>Google Analytics 4 </VisuallyHidden>Measurement ID`.

I've updated the ACs here but the IB should explicitly mention the use of `<VisuallyHidden>`, or whatever approach should be used to ensure the label works appropriately.

**Comment by asvinb** [comment]
Thanks @tofumatt . Good catch. IB has been updated.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the correct `measurementID` is present on the settings overview.  
- The label is `Google Analytics 4 Measurement ID`, but visually appears as `Measurement ID`.
- The `measurement ID` does not appear when editing.
- Confirmed that there is substring is inside a `<span class="screen-reader-text">` and is therefore visually hidden.

![image](https://user-images.githubusercontent.com/73545194/123100564-24bd4c80-d42b-11eb-9723-d63eadd2578e.png)

![image](https://user-images.githubusercontent.com/73545194/123100586-2850d380-d42b-11eb-93be-a8927f9e702e.png)
