### ISSUE TITLE
Allow users to define their own GOOGLESITEKIT_ENCRYPTION_SALT constants

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3547]
## Feature Description

As per a [recently opened support topic](https://wordpress.org/support/topic/sitekit-logged-out-every-time-salt-keys-are-updated/) a user has their site setup so that their WP Salt Keys are update daily. This results in them being logged out each time, with Site Kit depending on these constants for security purposes. 

Provide either document or in product assistance for users who wish to define their own custom GOOGLESITEKIT_ENCRYPTION_KEY and GOOGLESITEKIT_ENCRYPTION_SALT constants to limit users having to reconnect. 

This could be implemented in a similar fashion to how WP does for its constants (https://api.wordpress.org/secret-key/1.1/salt/) for our own.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Closing since it's not related to plugin-side work.
