### ISSUE TITLE
Analytics and Search Console connected but no data

### ISSUE THREAD

**Issue by abmario** [google/site-kit-wp#355]
## Bug Description
I correctly connected Google Analytics and Search Console, but don't see data

**Comment by jamesozzie** [comment]
@abmario Can you please perform the following steps, the error you are encountering could be due to Ad Blocker, security plugin or chrome extension. 

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any analytics tracking or reporting plugins
3. Temporarily deactivate other active security or firewall plugins
4. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

If the above fails to resolve your issue can you please inform me of the following:
- Are you seeing an error message or notice? 
- Please share any [console errors](https://i.imgur.com/f5WfLb3.png)
- What security/firewall plugins are you using?

**Comment by abmario** [comment]
I desactivated wp-optimize, resetted site kit, and installed Site Kit in a new incognito window
And it is Always the same no data.

No error message
No console errors
Windows 10 firewall

Mario Verville, M.Sc.
34 Odette-Pinard
Québec, Qc, Ca

________________________________
De : James G <notifications@github.com>
Envoyé : Wednesday, July 31, 2019 5:18:43 AM
À : google/site-kit-wp <site-kit-wp@noreply.github.com>
Cc : abmario <marioverville@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [google/site-kit-wp] Analytics and Search Console connected but no data (#355)


@abmario<https://github.com/abmario> Can you please perform the following steps, the error you are encountering could be due to Ad Blocker, security plugin or chrome extension.

  1.  Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
  2.  Temporarily deactivate any analytics tracking or reporting plugins
  3.  Temporarily deactivate other active security or firewall plugins
  4.  Install Site Kit in a new incognito window<https://i.imgur.com/ALzgiHp.png>

If the above fails to resolve your issue can you please inform me of the following:

  *   Are you seeing an error message or notice?
  *   Please share any console errors<https://i.imgur.com/f5WfLb3.png>
  *   What security/firewall plugins are you using?

**Comment by jamesozzie** [comment]
@abmario Can you share a screenshot of your Site Kit dashboard, so I can see the notice it displays.

**Comment by abmario** [comment]
[cid:image003.png@01D54791.AF2BC910]

Mario Verville, M.Sc.
34 Odette-Pinard
Québec, Qc, Ca

________________________________
De : James G <notifications@github.com>
Envoyé : Wednesday, July 31, 2019 11:01:45 AM
À : google/site-kit-wp <site-kit-wp@noreply.github.com>
Cc : abmario <marioverville@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [google/site-kit-wp] Analytics and Search Console connected but no data (#355)


@abmario<https://github.com/abmario> Can you share a screenshot of your Site Kit dashboard, so I can see the notice it displays.

**Comment by abmario** [comment]
Problem solved, I tried with google chrome and it works

Mario Verville, M.Sc.
34 Odette-Pinard
Québec, Qc, Ca

________________________________
De : James G <notifications@github.com>
Envoyé : Wednesday, July 31, 2019 11:01:45 AM
À : google/site-kit-wp <site-kit-wp@noreply.github.com>
Cc : abmario <marioverville@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [google/site-kit-wp] Analytics and Search Console connected but no data (#355)


@abmario<https://github.com/abmario> Can you share a screenshot of your Site Kit dashboard, so I can see the notice it displays.

**Comment by jamesozzie** [comment]
@abmario Good to know. What browser were you using prior to Chrome?

**Comment by abmario** [comment]
cyberfox

Mario Verville, M.Sc.
34 Odette-Pinard
Québec, Qc, Ca

________________________________
De : James G <notifications@github.com>
Envoyé : Wednesday, July 31, 2019 3:49:11 PM
À : google/site-kit-wp <site-kit-wp@noreply.github.com>
Cc : abmario <marioverville@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [google/site-kit-wp] Analytics and Search Console connected but no data (#355)


@abmario<https://github.com/abmario> Good to know. What browser were you using prior to Chrome?
