### ISSUE TITLE
Module Setup Flow | Analytics: No existing account, no existing tag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#356]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Tests must cover the following:
* User clicks Activate Analytics button in Settings
* button link to create account (externally) should be shown
* once account has been externally created, clicking "refetch" should make it work
* afterwards, we're in the same scenario as 2 from #344 (dropdowns with account, property, profile are displayed)
* the rest doesn't need to be tested here because it's covered by #344

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by circlecube** [comment]
Little note to mention this is partially blocked by #344.

**Comment by aaemnnosttv** [comment]
This is now blocked by #154

**Comment by lucymtc** [comment]
QA looks good. 
run `npm run test:e2e:interactive -- tests/e2e/specs/modules/analytics/setup-no-account-no-tag.test.js` 
Test passed and work as expected according to acceptance criteria.
