### ISSUE TITLE
Confusing error during permission setup flow on the oauth2 callback page

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3568]
## Bug Description

The sitekit.withgoogle.com shows a confusing error if a granting permissions process is idle for ~10 mins or more. Looks like it happens because something becomes expired. In this case, we need either redirect a user back to the SK or start over.

## Steps to reproduce

1. Do something that requires granting additional scopes.
2. Click on the proceed button in the permissions popup.
3. Once you land on an accounts.google.com page, wait for ~10 mins or more.
4. Then continue your journey by accepting everything that has been asked.
5. See the error

## Screenshots

![Screenshot from 2021-06-14 19-00-33](https://user-images.githubusercontent.com/873049/121923197-5bb4a380-cd43-11eb-80fc-6705a1978590.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@eugene-manuilov Since this is a service-side problem, I've opened a task internally. In the future please open such issues there as tasks. Closing this one.
