### ISSUE TITLE
Module Setup Flow | Analytics: Existing account, has existing tag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#357]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Tests must cover the following:
* User clicks Activate Analytics button in Settings
* two alternative scenarios:
    1. if there is an existing property for that existing tag
        * dropdowns are shown, the property for the existing tag is preselected and locked (cannot be changed), and the account is locked as well; views for the property are displayed
        * a message is shown informing about the existing tracking code and that it comes from an external (non Site Kit) source
        * all a user can do here is select a view
        * completing the flow should successfully take the user to the Analytics module page
    2. if there is an existing property, but none that matches the existing tag
        * a message is shown informing about the existing tracking code and that it comes from an external (non Site Kit) source, and that the user does not have access (they need to either request access or remove the existing code)
        * in this scenario, the user is **blocked** from proceeding

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Just noting that the Analytics module must be disconnected via settings for it to recheck the existing tag. Cancelling and resuming the module setup is not sufficient.

![image](https://user-images.githubusercontent.com/1621608/62240129-8c50f580-b3d6-11e9-80a6-1c852d5d639a.png)

Resetting Site Kit would also work.

**Comment by circlecube** [comment]
Noting this is partially blocked by #344

**Comment by aaemnnosttv** [comment]
@swissspidy ready for review!

**Comment by circlecube** [comment]
QA Pass

`npm run test:e2e -- tests/e2e/specs/modules/analytics/setup-with-account-with-tag.test.js`

 PASS  tests/e2e/specs/modules/analytics/setup-with-account-with-tag.test.js (59.369s)
  setting up the Analytics module with an existing account and existing tag
    ✓ pre-selects account and property if an existing tag is found that matches one belonging to the user and 
prevents them from being changed (20615ms)
    ✓ does not allow Analytics to be set up with an existing tag that does not match a property of the user (1
7198ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        59.445s
