### ISSUE TITLE
Refactor module dashboards with common overview widget component

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3573]
## Feature Description

In #3083, we identified a number of inconsistencies between the individual module dashboard views which is due to the large amount of duplication present in each of the module overview widget components.

While those inconsistencies have been fixed for now, the duplication is still there which leaves these areas vulnerable to inconsistency in the future. Any change to one of them will need to be done to all of them.

We should extract the common elements to one or more shared components rather than re-implementing and maintaining separate instances of the same layout. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
With the generic dashboard, some of these components will be removed or significantly altered. I'm going to move this to _Stalled_ for now, since it doesn't make sense to start that work at this point.

**Comment by felixarntz** [comment]
This is no longer applicable at this point, so I'm gonna close it.
