### ISSUE TITLE
Update language on initial setup screen

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3581]
## Bug Description

The language on the initial Site Kit setup screen reads:

"Get insights about how people find and use your site, how to improve and monetize your content, directly in your WordPress dashboard"

This isn't a complete sentence. Can we change it to something like:

"Get insights on how people find your site, as well as how to improve and monetize your site's content, directly in your WordPress dashboard."

## Steps to reproduce

1. Install and activate Site Kit
2. Go to Site Kit > Dashboard to start the setup process

## Screenshots

![image](https://user-images.githubusercontent.com/12189958/122092303-c31c3300-cdd7-11eb-93df-d76a575fc4cd.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy on the initial Site Kit setup screen (see screenshot above) should be slightly adjusted to: _Get insights on how people find your site, how to improve and monetize your site's content, and how to improve page speed directly in your WordPress dashboard_

## Implementation Brief

Using the `SetupUsingProxy` component update the description:

  "Get insights about how people find and use your site, how to improve and monetize your content, directly in your WordPress dashboard"

to:

  "Get insights on how people find your site, as well as how to improve and monetize your site's content, directly in your WordPress dashboard."

### Test Coverage

*  N/A

### Visual Regression Changes

* Check VRT tests and update if necessary

## QA Brief

* Reset Site Kit
* Go to the Site Kit dashboard and check that the setup screen text has been updated as per the IB

## Changelog entry

* Update language on initial setup screen

**Comment by felixarntz** [comment]
@bethanylang The language changes make sense to me, thanks! Removing the full stop though, since per some UX guidance we've been following, for individual single-sentence copy we don't use a full stop.

I removed this from the GA4 epic since it's related to the setup flow. Paging @marrrmarrr to approve wording.

**Comment by marrrmarrr** [comment]
Since we're at it, how about we add something about Page Experience too? That is not mentioned at all right now. 

_Get insights on how people find your site, how to improve and monetize your site's content, and how to improve page speed, directly in your WordPress dashboard_

**Comment by bethanylang** [comment]
@marrrmarrr That makes sense to me, though I don't think we need that last comma:

_Get insights on how people find your site, how to improve and monetize your site's content, and how to improve page speed directly in your WordPress dashboard_

**Comment by marrrmarrr** [comment]
Sounds good!

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Verified that the text has changed to `Get insights on how people find your site, as well as how to improve and monetize your site's content, directly in your WordPress dashboard.` as per the IB. 

![image](https://user-images.githubusercontent.com/73545194/126184668-c70f66c0-1c43-48f6-927c-cf5344152f39.png)
