### ISSUE TITLE
Improve workflow for creating and connecting a new GA4 property on a connected Analytics account

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3586]
## Feature Description

The current workflow for a user who already has an Analytics account and UA property connected in Site Kit and wants to add and connect a new GA4 property is pretty confusing at the moment. Video here: https://jmp.sh/sr0X43j+/Screen+Recording+2021-06-15+at+4.18.10+PM.mp4.

- There isn't any kind of prompt or indication anywhere in the plugin (including on the Settings screen) that a new GA4 property can be set up in Settings > Connected Services > Analytics. Given that GA4 is "the future," should we be prompting user to go set up a property?
- When a user goes to Settings > Connected Services > Analytics > Edit, a notice appears that "A Google Analytics 4 property will also be created," but the "also" is unclear and there are no instructions about how to proceed, as noted in #3584.
- Clicking Confirm Changes begins the process of adding a new GA4 property. After clicking Proceed and logging into their Google account, the user is redirected back to the Settings screen with no feedback indicating that a property was created successfully. They then have to click Confirm Changes again to complete the action and see the new GA4 property on the Settings screen.

It would be great to streamline and make this workflow more user-friendly, as I think we'll get a lot of folks in support who are new to GA4 and will want to create a new property for it, but won't have any idea where to start based upon the current flow, and will be confused once they get into the Settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics settings submission logic should be altered so that the GA4-specific validation checks and submission is only run in certain conditions:
    1. In Analytics setup _always_ (i.e. if the Analytics module is not "connected" yet)
    2. In Analytics settings _only_ if a GA4 property was already set before / on page load (i.e. if the Analytics module is "connected" _and_ there is already a saved value for the GA4 property)
    * In other words, it should _not_ be run/required for existing sites that didn't go through the new setup flow and therefore haven't set up GA4 data.
* Connected to the above, the UI of the Analytics `SettingsEdit` view should be updated:
    * If no saved GA4 property is set (on page load), nothing about GA4 should be displayed. No GA4 property dropdown, no notice about an associated GA4 property being created. It should of course still be possible to submit the settings, and due to the point above it should then only save settings for the `analytics` module, but not the `analytics-4` module.
    * If a saved GA4 property is set (on page load), instead of displaying the same notice about selecting an associated GA4 property that is present in the setup flow, _just_ the GA4 property dropdown itself should be displayed, without any further information (since at this point the user already set up GA4 so should have context).
        * The label of the GA4 property dropdown should _only in this case_ be adjusted to "Google Analytics 4 Property" instead of just "Property".

Note: The above requirements were what was originally envisioned for how to handle existing sites, it looks like this somehow got lost in definition / engineering. We should not, for now, prompt existing users about GA4 unless they go through setup. This will be changed in a more appropriate way later.

## Implementation Brief

* Merge #3602

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Create a new jurassic site 
* Set up SK and activate the Analytics module
* On the setup form select an account, UA property and profile.
* **Only now activate the ga4setup feature flag.**
* Go to the Analytics settings and make sure you don't see information about GA4 in the settings form. Plus, verify that you can save make and save settings changes.
* Now, disconnect the Analytics module and activate it again.
* Now on the setup form select an account that has UA and GA4 properties.
* Select both properties and save the setup form.
* Go to the Analytics settings screen and verify that you see GA4 settings and you can change ga4 property as well as other Analytics settings.

## Changelog entry

* Enhance experience for sites with UA Analytics already configured before GA4 is enabled.

**Comment by felixarntz** [comment]
@bethanylang Thanks for raising this, those are great points. Leaving an initial reply to your three points:

1. The idea was not to immediately prompt users that already have Analytics set up. We first want to focus on new users or those who set up the module anyway. There's still a long time left (last prediction was 2023) until UA properties are no longer supported, so we don't need to catch everyone just yet. The long-term approach is definitely a prompt like you're suggesting.
2. Agreed, I think this is what we should focus on for this issue. The notices in the Analytics settings should probably use an alternate copy to clarify the situation.
3. This is due to a technical problem which has already been relevant in any other situation when you create new entities from any module settings panel (e.g. also when you choose to create a new UA property in the _current_ Analytics settings UI). Fixing this is probably something we should have a follow-up issue for, but it's technically quite the challenge, so we haven't been able to prioritize this yet. So while I agree this is a problem, it is not new, so I think we should look into this separately. There _has been_ one other problem related to this (#3550), but it looks like you didn't encounter that one. Due to the limitation, the current expected behavior is the following:
    1. You attempt the action (submit the form).
    2. Because it requires additional permissions on Google, you see a dialog with a link that redirects you to the Google OAuth consent screen, to grant the additional permissions.
    3. Then you arrive back in the plugin, in the same state that you were in before. You now have to re-submit the form, at which point this will work.

The preferred way to make point 3. work is that instead of requiring to re-submit the form the form automatically re-submits itself once you arrive back in the plugin. But as mentioned above, this is a general complex problem, which I think would be better handled in its own issue.

Let me know your thoughts!

**Comment by bethanylang** [comment]
@felixarntz Thank you for laying this all out! My thoughts below:

> The idea was not to immediately prompt users that already have Analytics set up. We first want to focus on new users or those who set up the module anyway. There's still a long time left (last prediction was 2023) until UA properties are no longer supported, so we don't need to catch everyone just yet. The long-term approach is definitely a prompt like you're suggesting.

Fair enough! That said, as we have had a fair volume of users that have been requesting this feature, it might be nice to let them know in-product that it's now available. Maybe just something on the Analytics page?

> Agreed, I think this is what we should focus on for this issue. The notices in the Analytics settings should probably use an alternate copy to clarify the situation. You've also touched on this in #3584.

👍 

> The preferred way to make point 3. work is that instead of requiring to re-submit the form the form automatically re-submits itself once you arrive back in the plugin. But as mentioned above, this is a general complex problem, which I think would be better handled in its own issue.

Agreed and understood. Let me know if you'd like me to create a separate issue for this.

In the interim, I'm drafting the documentation now that will specifically call out the need to click Confirm Changes again to see that GA4 has been successfully added.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- With only a UA property selected, no information about GA4 appears in the settings form. 
- Verified that you can change settings and save them. 
- Verified that you see GA4 settings and you can change GA4 property as well as other Analytics settings.

![image](https://user-images.githubusercontent.com/73545194/123432964-db076a00-d5c2-11eb-9f7b-5141095a4afd.png)

![image](https://user-images.githubusercontent.com/73545194/123432985-e0fd4b00-d5c2-11eb-9987-4ef6754ebabc.png)
