### ISSUE TITLE
Site Verification component already sets up Search Console

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#359]
## Bug Description

During the setup flow, the JavaScript `SiteVerification` component already deals with Search Console which it should not do in any way. There is a dedicated `SearchConsole` component (used in the respective setup wizard step) that should cover all this functionality.

It is important to distinguish that Site Verification API and Search Console API are two entirely separate entities. Search Console requires a user to be verified via Site Verification API, but Site Verification is in no way dependent on Search Console, hence these parts should be removed from the `SiteVerification` component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SiteVerification` component must no longer call any API datapoints related to Search Console (e.g. `is-site-exist`, or `save-property`).
* The `SearchConsole` component must not talk about verification, since its only responsibility is to ensure there is a Search Console property for the site. In case there isn't one already, the user should confirm to create a new property for the site/URL, rather than verify (mostly a wording change).
* The `SearchConsole` component should use the `insert` datapoint to add a new property, or the `save-property` datapoint to just store an existing property as the correct one.
* It needs to be ensured that the functionality currently (incorrectly) covered in the `SiteVerification` component still works correctly via the actual `SearchConsole` component.
* This must be specifically tested for the first admin as well as a secondary admin.

## Implementation Brief

* Inside `componenDidMount()` of `<SiteVerification>` component only go through site verification process calling `requestSitePropertyList()`. 
* Move `saveProperty()` and `isSiteExist()` methods to `<SearchConsole>` component and move the logic inside `componenDidMount` to the `<SearchConsole>` component on `componentDidMount()`

* Remove `insertPropertyToSearchConsole()` from `<SiteVerification>` component
https://github.com/google/site-kit-wp/blob/4c691659af7d975205be2957e2e7d36b26f9e8e7/assets/js/components/setup/site-verification.js#L153
and any reference to it from this component.
This method already exists in `<SearchConsole>` component.

* Remove call to datapoint `save-property` from `<SiteVerification>` component inside `onProceed` method https://github.com/google/site-kit-wp/blob/4c691659af7d975205be2957e2e7d36b26f9e8e7/assets/js/components/setup/site-verification.js#L175
`onProceed` method should only reverify site `insertSiteVerification()` 
Note: there is an open issue with bug when reverifying site https://github.com/google/site-kit-wp/issues/85

* Ensure `hasSearchConsoleProperty` is not `true` after lifecycle of `<SiteVerification>` by removing line where state is being set in `siteVerificationSetup()` https://github.com/google/site-kit-wp/blob/4c691659af7d975205be2957e2e7d36b26f9e8e7/assets/js/components/setup.js#L102
`hasSearchConsoleProperty` state should only be set in `searchConsoleSetup()`

## Changelog entry

* Decouple site verification from Search Console setup during the plugin setup flow so that site verification does not rely on any Search Console API.

**Comment by lucymtc** [comment]
@felixarntz have discussed with @aaemnnosttv about the possible approaches to go with the verification step. 
One would be to create a new REST endpoint for siteverification in `REST_Routes`
The other would be to add a siteverification module that would just be a backend module with no presence in the front end and only used for setup flow, this would definitely be simpler for implementation as we wouldn't need to change the way we request and parse data, we would just move the needed endpoints currently living in Search_Console to the new module (activated by default).

What do you think?

**Comment by felixarntz** [comment]
@lucymtc @aaemnnosttv I think a dedicated Site Verification module is a great idea. However, I'm a bit worried making this change now, as I don't think we have the concept of "backend modules" right now - we wouldn't want the user to see any of it, which would likely require some infrastructure changes (even if just small ones).

This issue is most importantly about the JavaScript components and that they don't separate Site Verification and Search Console setup as expected. I think we can keep it simple on the server and continue to use the existing site verification routes from the `Search_Console` module class.

**Comment by felixarntz** [comment]
A few pieces of feedback for the implementation brief:

> React: Move calls to search-console datapoint within the `SiteVerification` component to the `SearchConsole` component

Can you add some notes where/how these should be moved? E.g. there already is a call to `insert` in the `SearchConsole` component, but none to `save-property`.

> `SiteVerification` component needs to call `isSiteExist` (requests to `is-site-exist`) and `requestSitePropertyList` within `componentDidMount`.

Only the `requestSitePropertyList` (using `siteverification-list` datapoint) call should be needed for Site Verification. `is-site-exist` checks whether a property for the site exists in Search Console, which should be irrelevant. We can detect that for Site Verification itself via `siteverification-list`. Please clarify why, if you think this is still needed here.

Two more things:
* It has to be ensured that `hasSearchConsoleProperty` in `setup.js` is not true after lifecycle of the `SiteVerification` component (as that should be handled solely by the `SearchConsole` component).
* The parts related to a dedicated Site Verification module can be removed, if we agree that's not needed for now. From my POV, it would definitely be good to have at some point, but easier to do in a different issue, where all we need to do is move datapoints, rather than mixing with different changes. Let's see this one as a prerequisite.

**Comment by felixarntz** [comment]
Implementation brief looks good!

**Comment by felixarntz** [comment]
QA is good.

**Comment by marrrmarrr** [comment]
Verified with existing verification site and new site. LGTM.
