### ISSUE TITLE
Error: Looks like your site is not allowed access to Google account data and can't display stats in the dashboard.

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3591]
## Bug Description
A user reported an issue **Looks like your site is not allowed access to Google account data and can't display stats in the dashboard**. As per user he has configured [different GA properties for multiple websites](https://imgur.com/a/phJhRO2) which are associated with one Google Account.
Here are the different errors which he encountered since he created the topic:
- Looks like your site is not allowed access to Google account data and can’t display stats in the dashboard. To fix this, redo the plugin setup.
- Deauthorization happens time by time & need to [re-connect with Search Console](https://imgur.com/a/ng5Bsj1) to fix
- Your temporary access code is invalid or expired. Please return to your WordPress site by cancelling below and retry.
- While clicking on Manage Sites it shows `invalid parameter: ‘token’`

Topic: https://wordpress.org/support/topic/fatal-issue | [Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiP-_xJf52sm_btlNosTuifUWaooJ0QLjcdBeloSVQ5g1gP9oVUyX7n72ibwR3tE-8)

## Screenshots
![error_u6rsn8](https://user-images.githubusercontent.com/14175927/122349062-474ff100-cf65-11eb-9c1c-8d56da23c00b.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@abdullah1908 As this is expected behavior as discussed in last week's support meeting, I'm going to close this out.
