### ISSUE TITLE
Replace STORE_NAME usage with named constants

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3599]
For historical purposes we mix use of `STORE_NAME` and named constants for modules (like `CORE_SITE` or `MODULES_ANALYTICS`). But in files with multiple stores, the unnamed `STORE_NAME` provides little context, and now that the named constants are also available, we should replace all instances of `STORE_NAME` with the actual constant name (eg. `CORE_SITE`, `CORE_USER`, etc.)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instances of `STORE_NAME` throughout the code should be replaced with the "named constant" they represent.
* Any other instances of `STORE_NAME` (for instance, in [`create-settings-store.js`](https://github.com/google/site-kit-wp/blob/b6dade1a841d681c1df1f3d6fc5b5378ad5a6652/assets/js/googlesitekit/data/create-settings-store.js#L82)), should be renamed to something like `settingsStoreName` so they don't invoke confusion for current developers because of the historical context of `STORE_NAME`. Using the constant formatting in this file isn't really appropriate anyway. 🙂 

## Implementation Brief

* Replace all instances of `STORE_NAME` throughout the code with the appropriate named constant for the module.
* Remove the `STORE_NAME` variables declarations in module constants files like https://github.com/google/site-kit-wp/blob/b6dade1a841d681c1df1f3d6fc5b5378ad5a6652/assets/js/googlesitekit/datastore/location/constants.js#L19, changes it to be `export const CORE_LOCATION = 'core/location';`
* In places like https://github.com/google/site-kit-wp/blob/b6dade1a841d681c1df1f3d6fc5b5378ad5a6652/assets/js/googlesitekit/data/create-existing-tag-store.test.js#L33 that use a "Test" store/store name, change the variable to `TEST_STORE`.
* Replace https://github.com/google/site-kit-wp/blob/b6dade1a841d681c1df1f3d6fc5b5378ad5a6652/assets/js/googlesitekit/data/create-settings-store.js#L82 with a variable like `settingsStoreName`—do the same in other generated stores with an appropriate variable name.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* All unit tests and linting should continue to pass.
* Verify no `STORE_NAME` constants are used/imported/exported from `constants.js` files.
* Note that in many `create-X-store.js` files and tests there will be properties/internal variables with `STORE_NAME` values—these are separate and since they're part of the API not worth changing here. They're also internal and don't cause the confusion this issue intended to fix 🙂 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by johnPhillips** [comment]
Hey @tofumatt, just a question on this bit:
> Repace [...] with a variable like settingsStoreName—do the same in other generated stores with an appropriate variable name.

That particular function seems to return a `STORE_NAME` property:
https://github.com/google/site-kit-wp/blob/b6dade1a841d681c1df1f3d6fc5b5378ad5a6652/assets/js/googlesitekit/data/create-settings-store.js#L350-L355

Should I update this to e.g. `settingsStoreName` and then also update all the consumers? 
Or, given that it's an established part of its API, should I leave it?

**Comment by tofumatt** [comment]
Leaving that `STORE_NAME` is fine, though arguably it's a bit weird to have it be named in that constant case and we could change it to `storeName`… I'm taking over this PR so I'll see what makes sense without too much fuss, but I'd be happy to remove all instances of the `STORE_NAME` variable if it's straightforward 🙂

**Comment by wpdarren** [comment]
I feel this is a `QA:Eng` ticket but if I am incorrect then please feel free to let me know!

**Comment by asvinb** [comment]
- Searched for the `STORE_NAME` throughout the codebase and no `STORE_NAME` constants are used/imported/exported from `constants.js` files. ☑️ 
- `STORE_NAME` is only present in `create-X-store.js` files. ☑️ 

### QA: ✅
