### ISSUE TITLE
Let users control which GA4 web data stream to use

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3615]
## Feature Description

Currently, we hide all information about web data stream that is used by the Analytics module when it has GA4 integration. I understand that it has been done to reduce the complexity for users who are not familiar with data streams in GA4, but I am almost confident that it will be confusing for advanced users once they need to use a different web data stream.

One real use case that I can think of is when a user deletes a web data stream by accident that is being used by their site. If that happens, the user will need to go to the Analytics module settings and select another data stream, but they won't be able to do it because there is no web data stream dropdown on the settings form.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of #6330.
