### ISSUE TITLE
GA4 settings persist after Analytics is deactivated

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3616]
## Bug Description

When disconnecting a module, its settings are always deleted by the `Module::on_deactivation` method. However, due to some ga4-specific implementation details, this doesn't happen for GA4.

## Steps to reproduce

1. Enable `ga4setup`
2. Setup Analytics with a GA4 property
3. Deactivate the Analytics module
4. Go to `/wp-admin/options.php`
5. See `googlesitekit_analytics-4_settings` is still present. 
_Alternatively, with wp-cli you could use `wp option get googlesitekit_analytics-4_settings`_

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When `ga4setup` is enabled, the GA4 module should be deactivated when Analytics is deactivated

## Implementation Brief

* Merge #3624 

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Activate the Analytics module and select an account with both UA and GA4 properties on the setup form.
* Go to the Analytics settings and make sure that you see GA4 property in the settings view.
* Disconnect the Analytics module.
* Verify that the following commands return empty settings for `analytics` **and** `analytics-4`:
  ```sh-session
  wp option get googlesitekit_analytics_settings
  wp option get googlesitekit_analytics-4_settings
  ```

## Changelog entry

* Fix a bug where GA4 settings were not cleared when deactivating Analytics.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov – I took a look at your PR there and while it's a fairly small change, I'd rather not add a GA4 specific method there. After taking a closer look, I found we can simplify it a good deal by calling the same method with GA4 before it is done for GA. I created a branch with my work here: https://github.com/google/site-kit-wp/compare/fix/3616-ga4-deactivation-alternative

It also replaces the conditions for method existence with interfaces like we do elsewhere which is technically a bit out of scope here but it would be a nice enhancement to make at the same time I think.

Let me know what you think, and if you like it, we can switch places and you can review my IB 😄

**Comment by eugene-manuilov** [comment]
Sounds good to me, @aaemnnosttv. Let's go with your branch then. Could you please create a PR for your branch and update the IB?

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by Hazlitte** [comment]
** QA ✅  **
I setup a new site with UA and GA4 properties, a release zip build and `ga4setup` enabled.  The properties were deleted after disconnection.

**Comment by aaemnnosttv** [comment]
> I setup a new site with UA and GA4 properties, a release zip build and `ga4setup` enabled. The properties were deleted after disconnection.

@Hazlitte The properties themselves should not be deleted, only the settings values for them (all of the module's settings really). I think that's what you meant, but just wanted to clarify that no actual properties were deleted? 😅

**Comment by Hazlitte** [comment]
@aaemnnosttv Oops, yes you are right.  I meant the settings values in the options table. 🤦‍♂️
