### ISSUE TITLE
Fix release build process to exclude unnecessary files

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#362]
## Bug Description

The release ZIP created from `npm run release-zip` currently includes a few files that aren't necessary (either old relicts, or development-related):
* `/bin/local-env` directory
* `/dist/admin.js`
* `/dist/adminbar.js`
* `/dist/wpdashboard.js`

Correct me if I'm wrong, but I don't see these JS files used anywhere, the actual files for these areas are all below `/dist/assets`.

The `release-zip` command should be fixed to not include the above files in the ZIP.

cc @adamsilverstein 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When running `npm run release-zip`, the following files are not included in the resulting ZIP:
    * `/bin/local-env` directory
    * `/dist/admin.js`
    * `/dist/adminbar.js`
    * `/dist/wpdashboard.js`

## Implementation Brief

* Update the list of exclussions in the copy gulp task https://github.com/google/site-kit-wp/blob/develop/gulp-tasks/copy.js to exclude:
`/bin/local-env`
`/dist/admin.js`
`/dist/adminbar.js`
`/dist/wpdashboard.js`

Note: the dist/*.js files are being created unnecessarily, this is a known webpack issue and there is currently no straight forward way to prevent them from being created from webpack configuration. The safest is to exclude them from the zip release.

## Changelog entry

*

**Comment by adamsilverstein** [comment]
`/bin/local-env` is a new folder and will need to be explicitly excluded.
`/dist/admin.js` `adminbar` and `wpdashboard` all appear to be unintentional build artifacts - ideally these files should not be created at all.

Looks like they are coming from here: https://github.com/google/site-kit-wp/blob/6ceafe33e0b5119211d23ba7c15193cdee17a08f/webpack.config.js#L288-L337

**Comment by lucymtc** [comment]
For the js files, this is known issue in webpack and there doesn't seem to be a straight forward way to prevent these files from being created from the webpack config. The safest way is to exclude them from being added to the release zip.

**Comment by felixarntz** [comment]
Implementation brief looks good!

**Comment by lucymtc** [comment]
QA looks good
