### ISSUE TITLE
Add option to skip uninstall hook

### ISSUE THREAD

**Issue by swissspidy** [google/site-kit-wp#363]
## Feature Description

If I want to briefly delete the plugin to then upload a new version from a ZIP file, all my data is removed because of the uninstall handler.

I suggest adding an option on the settings page to toggle this behavior. Many plugins already do this, since core itself doesn't support that yet.

As a user, I'd expect to be able to turn off the data deletion in the Site Kit settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Example in Polylang:

![Screenshot 2019-09-26 at 11 29 42](https://user-images.githubusercontent.com/841956/65676899-f7265200-e050-11e9-9f3f-318d9cdb3ead.png)

**Comment by felixarntz** [comment]
Surpassed by #1069
