### ISSUE TITLE
Web Vitals measurement in Analytics

### ISSUE THREAD

**Issue by yogeshbeniwal** [google/site-kit-wp#3631]
## Feature Description

Core Web Vitals measurement is critical after these considered as ranking factor. It will be good to include Web Vitals measurement in Analytics. This can be implemented using [web-vitals](https://github.com/GoogleChrome/web-vitals/) library.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
Hey @yogeshbeniwal, thanks for the great suggestion! This is actually something we're already working on, so you'll be seeing more progress on this in the coming months!

**Comment by yogeshbeniwal** [comment]
@marrrmarrr Wondering if this has been put on hold at the moment?
