### ISSUE TITLE
User feedback form doesn't re-appear after returning to the dashboard page

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3633]
## Bug Description

An observation: the User Feedback Form Appears on the Dashboard but the user does not complete it. The user then goes to another module page and comes back to the Dashboard.  The User Feedback Form should then reappear, but it doesn't at the moment.

Related Asana ticket: https://app.asana.com/0/1200379030254833/1200498459236227

A possible solution for this issue is to cache the survey only if it has been idle for 2 mins or more and the user hasn't completed it. In this case, if the user left the dashboard page and returned back to it, they will see the survey again and can complete it.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If a user feedback survey is shown and the user doesn't interact with it and goes to another page, it should keep appearing as long as 30 seconds since first appearing haven't passed. In other words:
    * If the user clicks away from the dashboard and then returns quickly, or refreshes the dashboard within 30 seconds after the user feedback survey was triggered, it should be re-triggered.
    * If the user remains more than 30 seconds on the dashboard without interacting with the user feedback survey, it can be assumed they don't care right now, so at this point it should not be re-triggered on next page load (and instead rely on our default 1 hour timeout for triggering surveys).

## Implementation Brief
* Using `assets/js/googlesitekit/datastore/user/surveys.js`,
	* In the `triggerSurvey` function, update the logic to set the cache when `ttl` > `0` by delaying the `setItem` call by 30 seconds using `setTimeout`.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Visit the main dashboard and the user feedback is displayed.
* Within 30s, navigate to another page within the admin.
* Return to the main dashboard. The user feedback should be displayed again.
* Now wait for 35s, without interacting with the component.
* Navigate away from the page and come back to the main dashboard.
* The user feedback component should not show up

## Changelog entry

* Add a timeout to delay caching the survey by 30 seconds

**Comment by eugene-manuilov** [comment]
@felixarntz can you check the `average time on page` metric in the Analytics account that we use for usage tracking? Just want to understand how long users stay on the dashboard page. Perhaps 2mins is too much or too low and we need to select a better timeout.

**Comment by felixarntz** [comment]
@eugene-manuilov Great point! I've just checked and it's little over 2 minutes.

**Comment by eugene-manuilov** [comment]
> Great point! I've just checked and it's little over 2 minutes.

Thanks, @felixarntz. So, in this case, 2 mins timeout is too much for sure. What do you think if we reduce it to 30 or 45 seconds?

**Comment by eugene-manuilov** [comment]
@asvinb I think we can simplify the logic by wrapping the `setItem` function call into a timeout and not checking anything else. https://github.com/google/site-kit-wp/blob/e2564bf10f06d36b04c36ece7f66e2edbaf78f3f/assets/js/googlesitekit/datastore/user/surveys.js#L111

In this case, we will get the same expected behavior:
* if a user leaves the page earlier, we will display the survey again when they come back
* if a user stays longer on the page, we will cache the survey for an hour and won't show it again if they refresh the page or come back within an hour
* If a user completes the survey, we won't show it again because their feedback will be recorded

**Comment by asvinb** [comment]
You're right @eugene-manuilov 🤦  I didn't realize the form will not show up if the user interacted with it, thus I wanted to know when the user interacts with it. IB updated.
Thanks!

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb! IB :heavy_check_mark:

**Comment by eugene-manuilov** [comment]
@felixarntz assigning this to you. Please, let me know what you think regarding the timeout. If you agree with it, I'll update numbers in AC and IB sections.

**Comment by felixarntz** [comment]
@eugene-manuilov Using a timeout of 30 seconds sounds good to me. I've already updated ACs and IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Nice! Works perfect. 

- Verified that when you visit the main dashboard, the user feedback is displayed.
- When I navigate to another page within the admin and return to the main dashboard, the user feedback is displayed again.
- When I wait for 35s, without interacting with the component, navigate away from the page and come back to the main dashboard, the user feedback component does not show up
