### ISSUE TITLE
React error when changing date range using Google Translate

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3636]
## Bug Description

In #2280, we fixed a React error that is possible when React tries to update the DOM after it has been changed by Google Translate. When this happens, it results in this error (which is not particularly helpful)

```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

Looking at our metrics for reported React errors, I found that this error has still been happening to some degree since the original fixes that were released in 1.31.0.

These have been primarily reported in the following components

- `DashboardPopularKeywordsWidget`
- `DashboardTopEarningPagesWidget`
- `LegacyAnalyticsAdSenseDashboardWidgetTopPagesTable`
- `LegacyAnalyticsDashboardWidgetTopPagesTable`

## Steps to reproduce

1. Go to Site Kit dashboard in Chrome
2. Right click the dashboard and use the "Translate to" option  
_Works with translating English to English as well, but easier to use a different language to see that it has in fact been translated_
3. Once translated, change the date range
4. If it does not error immediately, change it back again and you should see something like below

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/123461323-a5c64080-d5f1-11eb-8581-de29ac174b45.png)

## Additional Context

* No known support issues opened for this

<details>
<summary>Trace</summary>

```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in Component (created by ReportTable)
    in div (created by ReportTable)
    in td (created by ReportTable)
    in tr (created by ReportTable)
    in tbody (created by ReportTable)
    in table (created by ReportTable)
    in div (created by ReportTable)
    in ReportTable (created by DashboardPopularKeywordsWidget)
    in div (created by TableOverflowContainer)
    in div (created by TableOverflowContainer)
    in TableOverflowContainer (created by DashboardPopularKeywordsWidget)
    in div (created by Widget)
    in div (created by Widget)
    in Widget (created by WithWidgetSlug(Widget))
    in WithWidgetSlug(Widget) (created by DashboardPopularKeywordsWidget)
    in DashboardPopularKeywordsWidget (created by WhenSearchConsoleActive(DashboardPopularKeywordsWidget))
    in WhenSearchConsoleActive(DashboardPopularKeywordsWidget) (created by WidgetRenderer)
    in WidgetRenderer (created by WidgetAreaRenderer)
    in div (created by Cell)
    in Cell (created by WidgetCellWrapper)
    in WidgetCellWrapper (created by WidgetAreaRenderer)
    in div (created by Row)
    in Row (created by WidgetAreaRenderer)
    in div (created by WidgetAreaRenderer)
    in div (created by Grid)
    in Grid (created by WidgetAreaRenderer)
    in WidgetAreaRenderer (created by WidgetContextRenderer)
    in div (created by WidgetContextRenderer)
    in WidgetContextRenderer (created by DashboardApp)
    in DashboardApp (created by GoogleSitekitDashboard)
    in GoogleSitekitDashboard
    in RestoreSnapshots (created by Root)
    in ErrorHandler (created by Root)
    in Root
```

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit interfaces should remain stable and interactive after translation by Google Translate
    * Specifically, toggling the date range or other updates to the layout should not raise these errors if at all possible

## Implementation Brief

The primary cause for the errors are due to unwrapped returns from `ReportTable` column `Component`s, e.g. https://github.com/google/site-kit-wp/blob/37e9cad8e29c8fa83bd8337bf9403f80243d42a4/assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js#L128

Wrapping the return of these components (must be _within_ the `Component` not around it) with a `<span>` will fix the problem.

This would entail:
* Wrap all instances of `column.Component` used in `ReportTable` instances where a plain value is returned to be wrapped in a span

E.g.
```diff
- Component: () => value
+ Component: () => <span>{ value }</span>
```

### Test Coverage

* No changes expected

### Visual Regression Changes

* No changes expected

## QA Brief

* Follow steps to reproduce above using Google Translate
* Post-translation, date range changes should not raise errors on any dashboard or module dashboard screens

## Changelog entry

* Fix potential React error when using Google Translate and then changing the date range in a Site Kit admin screen.

**Comment by aaemnnosttv** [comment]
@felixarntz ready for IBR – there are 2 options to consider, let me know what you think.

**Comment by felixarntz** [comment]
@aaemnnosttv Since we aim to get this into the release, I'd suggest going with the quick fix solution. Maybe let's do that for now and open a follow-up issue to explore the more elaborate fix. If you're okay with going with the minimal solution for now, IB ✅

**Comment by aaemnnosttv** [comment]
IB updated to only include the simple fix for now, moving forward to EB 👍

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- I was able to recreate the error using the steps above.  **QA note:** I had to translate, then change the period, and change it back again for the error to trigger. With the fix, the changes in date range did not trigger any error messages on the dashboard or on module screens. Fixed!
