### ISSUE TITLE
Add ability for modules to opt-in to unconditional registration and implement in Idea Hub

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3639]
## Feature Description

Idea Hub is the first module that has the requirement of needing to register hooks even when it isn't active.

This already happens with module settings, but we should allow for module classes themselves to have an always-on registration if they implement it. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Google\Site_Kit\Core\Modules\Module_With_Persistent_Registration` interface should be created, with a single `register_persistent` method which has no return (similar to `Module::register`)
* The Idea Hub module should be updated to implement this interface to apply it's filtering of `display_post_states` and `wp_insert_post_empty_content` for idea posts
    * Note this will also require the name, text, and topic meta class instances to also be moved to this new method as dependencies of `get_post_idea` and `is_idea_post` methods

## Implementation Brief

* Create a new file:
`includes/Core/Modules/Module_With_Persistent_Registration.php`

With a `public function register_persistent`

Update: `includes/Modules/Idea_Hub.php` to implement the interface.

Move the two filters to the `register_persistent()` function
`wp_insert_post_empty_content` and `display_post_states`
https://github.com/google/site-kit-wp/blob/59a7d90/includes/Modules/Idea_Hub.php#L84-L118

Move the three settings across to the `register_persistent` function
`$this->post_name_setting`, `$this->post_text_setting`, and `$this->post_topic_setting`
https://github.com/google/site-kit-wp/blob/59a7d90/includes/Modules/Idea_Hub.php#L121-L128

Update `includes/Core/Modules/Modules.php` `register()` to call `register_persistent` for each module that implements the interface, irrespective of whether or not it's connected.
https://github.com/google/site-kit-wp/blob/59a7d90/includes/Core/Modules/Modules.php#L236

### Test Coverage

* Add a test case to cover registering settings / filters even when module is not connected. https://github.com/google/site-kit-wp/blob/59a7d90b159a26aafb7cde5f9f457868bfdf0a8a/tests/phpunit/integration/Modules/Idea_HubTest.php

### Visual Regression Changes

* N/A

## QA Brief

* Create a draft post for an idea
* Go to the posts page and verify that you see the special state for your draft post that includes the idea name
* Now disconnect the Idea Hub module
* Go back to the posts page and verify that you still see the special state for your draft post with the idea name.

## Changelog entry

* Ensure Idea Hub draft posts are properly labelled even when Idea Hub is disconnected.

**Comment by felixarntz** [comment]
@aaemnnosttv ACs look good to me. Moving to IB.

**Comment by cole10up** [comment]
Team, per https://github.com/google/site-kit-wp/issues/3514 I ran a series of tests and noticed an issue trying to trash an idea hub post that is in draft mode.

![image](https://user-images.githubusercontent.com/57115907/124942180-42a8b680-dfc0-11eb-8bc5-ecc448486fae.png)

CC @felixarntz

**Comment by aaemnnosttv** [comment]
@cole10up is Idea Hub active?

**Comment by cole10up** [comment]
@EvanHerman - Yep, settings looked like this:

![image](https://user-images.githubusercontent.com/57115907/124961852-cec3d980-dfd2-11eb-879d-fe71544c3782.png)

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

- I created a a draft post for an idea, and within the posts page, verified that the new draft was created with the idea name
- Once I disconnected Idea Hub module, the post remains in the same state, as a draft post with the idea name. 
- Additional checks:  I was also able to edit the post despite Idea hub is disabled.  
- I was also able to trash the draft post when Idea hub was active and deactivated. (This was tested because @cole10up and I initially could not do this)

![image](https://user-images.githubusercontent.com/73545194/126168391-28d58d07-d99a-487f-bf0c-c92d657c8268.png)

![image](https://user-images.githubusercontent.com/73545194/126168413-f9d98ead-5b8b-46f0-a3d2-107cb9dde48f.png)
