### ISSUE TITLE
Duplicate Dates on Graphs when 7 Days Selected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3643]
## Bug Description

While testing #3517 I noticed that the dates on the x-axis were duplicated when 7 days was selected.  After further investigation it appears that this issue appears on all graphs, i.e. on AdSense, Analytics, etc. 

![dates](https://user-images.githubusercontent.com/73545194/123802919-b45b7300-d8e3-11eb-87c0-a499d4b67164.png)

## Steps to reproduce

1. Make sure you are on the develop branch
2. Go to a Module page, i.e. Analytics
3. Select 7 days 
4. Scroll down to the graph and observe the dates

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In any of the chronological charts on the per-module pages (Search Console, AdSense, Analytics) it should never happen that a single date is displayed multiple times as label for the x-axis.
    * This is particularly relevant for the "last 7 days" filter, in which right now it usually causes several dates to display more than once.

## Implementation Brief

In `assets/js/modules/analytics/components/module/ModuleOverviewWidget/SiteStats.js`

* Create an array of only Date objects from `dataMap`
* Add this to the options object for the key `hAxis.ticks` (Make sure to spread in `...SiteStats.options.hAxis` so as not to override any existing options)

(Work done on branch here https://github.com/google/site-kit-wp/tree/bug/3643-Duplicate-Dates-Graphs-7-Days__idea-1)

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

For each of the chronological charts on the per-module pages (Search Console, AdSense, Analytics)
* View with the "last 7 days" filter,
* Observe that no dates are repeated on the x-axis (see the original problem on the screenshot in ticket description)

## Changelog entry

* Update stats graphs not to duplicate dates when 7 days period is selected.

**Comment by aaemnnosttv** [comment]
@felixarntz I've seen this before; is it not something the charting library does normally? 🤔

**Comment by felixarntz** [comment]
@aaemnnosttv Not sure, I'm not aware of either. I'm gonna add ACs, I think it would be reasonable to look into how this can be fixed via the IB.

**Comment by danielgent** [comment]
On 1.35.0 I see this same bug. I've been trying out much older commits as well and I'm unable to *not* see these visual artifacts :thinking:

**Comment by wpdarren** [comment]
@danielgent I've just retested this in 1.35.0 and yes, the issue appears there too when you select 7 days as a date period. I've updated the description.

**Comment by danielgent** [comment]
There may be a few ways to do this, but one way I've found is to use `ticks`

See `hAxis.ticks` on https://developers.google.com/chart/interactive/docs/gallery/linechart


We can specify this in the Google Charts `options` and pass in only the labels we want to render

This is it working on branch https://github.com/google/site-kit-wp/tree/bug/3643-Duplicate-Dates-Graphs-7-Days__idea-1

![solution using ticks](https://user-images.githubusercontent.com/8496063/125803518-0099fd75-45fb-44fe-b05d-2d655681765b.png)

**Comment by danielgent** [comment]
Happy to bump the estimation up to 7 *but* if whoever reviews is happy with my branch then this task is done

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by danielgent** [comment]
@eugene-manuilov  I've just realized that @wpdarren  mentioned several modules in the description, but my IB is only for the analytics module

Not a huge problem, I'll see if I can do anything clever to not duplicate code, and then I'll assign the CR to you :+1:

**Comment by danielgent** [comment]
@wpdarren  I see this bug on the AdSense, Analytics, and Search Console pages.

I've fixed these now

![adsense-fix](https://user-images.githubusercontent.com/8496063/126200176-e4bb1ba7-4b00-426c-b20d-45aaf870fd78.png)

![search console fix](https://user-images.githubusercontent.com/8496063/126200181-e01a4213-9814-4c1e-988f-ba5b41375992.png)

Is there anywhere else you spotted?

**Comment by aaemnnosttv** [comment]
@danielgent while I don't think it's explicitly mentioned here, we should limit these changes to only the widget-based dashboard screens and components as the others are being removed in #2077 which is targeting 1.38.

**Comment by danielgent** [comment]
Good point mentioning that @aaemnnosttv !  Luckily I already had the widget feature flags turned on, so I haven't made any changes to the `Legacy` graph components e.g. `LegacyAnalyticsDashboardWidgetSiteStats`

**Comment by danielgent** [comment]
Just a headsup that my changes have caused some VRT regressions.

Upon looking at the differences, I don't think it's actually an improvement

**before and after**

![before-A](https://user-images.githubusercontent.com/8496063/126206418-a3068735-b793-448e-8a0d-2202fb6a4d35.png)

![after-A](https://user-images.githubusercontent.com/8496063/126206431-f43a2110-1b87-4fc9-859d-09c9346a749a.png)


**another before and after**

![before-B](https://user-images.githubusercontent.com/8496063/126206441-8737051b-77b4-48bf-980a-f9e85aaf97ad.png)

![after-B](https://user-images.githubusercontent.com/8496063/126206445-b52ce273-174d-447e-b703-36e76d162d74.png)

I could restrict my changes to only take effect when the user has selected _Last 7 days_

**Comment by wpdarren** [comment]
> @wpdarren I see this bug on the AdSense, Analytics, and Search Console pages.
> Is there anywhere else you spotted?

@danielgent those are the only places I noticed the duplicate dates, when 7 days was selected.

**Comment by danielgent** [comment]
@aaemnnosttv  @eugene-manuilov  Do check my last comment about the VRT changes for my open PR. It might be a showstopper (or at least require some extra code)

**Comment by eugene-manuilov** [comment]
> Do check my last comment about the VRT changes for my open PR. It might be a showstopper (or at least require some extra code)

No worries, @danielgent. This looks good to me.  We tell the google visualization library which ticks we want to use and it decides how to display it.

**Comment by eugene-manuilov** [comment]
@danielgent could you please add QAB?

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Observed that no dates are repeated on the x-axis for 7 days on `Search Console`, `AdSense` and `Analytics`. 
- Checked that no date issues appear for other periods on the same modules. 

![image](https://user-images.githubusercontent.com/73545194/126811955-90ac0095-1be8-44da-b9c9-5044e0ab06b8.png)
