### ISSUE TITLE
Remove server-side REST batch data infrastructure

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3644]
With the legacy data API no longer used (see #2258), we should also remove the related server-side infrastructure for batch requests, and the `data` batch REST endpoint.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Our batch endpoint `data` (defined in `REST_Routes` class) should be completely removed.
* The `Module::get_batch_data` method should be entirely removed.
* There is one usage of the above method that needs to continue to work, which is in the Analytics 4 `GET:webdatastreams-batch` REST datapoint. This usage should be replaced with a (much simpler) "manual" direct usage (nothing too abstracted) of the Google client library's batch functionality. At a high-level:
    * Use `with_client_defer` so that requests from `Module::create_data_request` aren't immediately executed but returned as request objects.
    * Use the `createBatch` method from the `Google_Service` instance to create a batch request.
    * Add the request objects to the batch.
    * Execute the batch and parse the results so that the overall response has the same format as now.
    * Restore original client defer mode.

## Implementation Brief

* Edit `REST_Routes` class:
  * Delete `data` endpoint declaration in the `get_routes` method.
  * Delete the `error_to_response` method.
* Edit `Module` class:
  * Delete the `get_batch_data` method.
* Update `GET:webdatastreams-batch` case in the `Analytics_4::create_data_request` method:
  * Grab the `analyticsadmin` service by calling `$analyticsadmin = $this->get_service( 'analyticsadmin' )`.
  * Create a batch request by calling `$analyticsadmin->createBatch()` method.
  * Loop through property IDs in the `$data['propertyIDs']` list:
    * For each propertyID create web data streams request by calling `$analyticsadmin->properties_webDataStreams->listPropertiesWebDataStreams( self::normalize_property_id( $data['propertyID'] ) )`
    * Add web data stream request to the batch request using `add` method.
  * Return a closure that executes the batch request and returns the results of the execution.
* Check the `GET:webdatastreams-batch` handler in the `Analytics_4::parse_data_response` method to make sure it returns the same results as it has been doing before.

_P.S.: no need to call `with_client_defer( true )` function explicitly, it will be done automatically for the `GET:webdatastreams-batch` endpoint._

### Test Coverage

* Remove `ModuleTest::test_get_batch_data` test.
* Fix broken phpunit tests

### Visual Regression Changes

* N/A

## QA Brief

* Open your WP dashboard to a page that makes the right request  e.g.http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-module-analytics&slug=analytics&reAuth=true&notification=authentication_success 
* Copy the request as a curl request.
* Run it against an env in a branch where the change exists, `develop` after this CR is merged.
* Run it again against `main` branch without the change.
* Compare the two.

<img width="1439" alt="Screen Shot 2021-07-26 at 4 57 20 PM" src="https://user-images.githubusercontent.com/373931/127001160-b4d1b576-44cd-4923-b68f-a7bbd429304d.png">

## Changelog entry

* Remove server-side REST batch data infrastructure.

**Comment by eugene-manuilov** [comment]
Felix, could you please review IB?

**Comment by felixarntz** [comment]
@eugene-manuilov IB ✅ 

Good catch about an extra call to `with_client_defer( true )` not being necessary since it's already done in `Module::make_data_request`.

**Comment by ivankruchkoff** [comment]
@eugene-manuilov  Missing something in the IB between:
For each propertyID create web data streams request by calling $analyticsadmin->properties_webDataStreams->listPropertiesWebDataStreams( self::normalize_property_id( $data['propertyID'] ) )
Add web data stream request to the batch request using add method


`GoogleAnalyticsAdminV1alphaWebDataStream` is a `Google_Model` per https://github.com/googleapis/google-api-php-client-services/blob/master/src/GoogleAnalyticsAdmin/GoogleAnalyticsAdminV1alphaWebDataStream.php#L20 

`add()` method takes something implementing `RequestInterface` per
https://github.com/googleapis/google-api-php-client/blob/master/src/Http/Batch.php#L70

**Comment by eugene-manuilov** [comment]
@ivankruchkoff when a [datapoint](https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics_4.php#L202) uses a service we [defer immediate execution](https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Module.php#L560-L564) of Google API requests. It means that when we call `...->properties_webDataStreams->listPropertiesWebDataStreams( ... )`, it does not return a list of web data streams, it returns a request object (implementing `RequestInterface`) that will be executed later to return web data streams.

**Comment by ivankruchkoff** [comment]
Results:

**Before**

```json
{
    "272263961": [
        {
            "createTime": "2021-05-13T18:02:38.922Z", 
            "defaultUri": "http://sitekit.10uplabs.com", 
            "displayName": "sitekit.10uplabs.com - GA4", 
            "measurementId": "G-VLWRQ702L6", 
            "name": "properties/272263961/webDataStreams/2603234856", 
            "updateTime": "2021-05-13T18:02:38.922Z", 
            "_id": "2603234856", 
            "_propertyID": "272263961"
        }
    ]
}
```

**After**
```json
{
    "response-1767423187": {
        "nextPageToken": null, 
        "webDataStreams": [
            {
                "createTime": "2021-05-13T18:02:38.922Z", 
                "defaultUri": "http://sitekit.10uplabs.com", 
                "displayName": "sitekit.10uplabs.com - GA4", 
                "firebaseAppId": null, 
                "measurementId": "G-VLWRQ702L6", 
                "name": "properties/272263961/webDataStreams/2603234856", 
                "updateTime": "2021-05-13T18:02:38.922Z"
            }
        ]
    }
}
```

@eugene-manuilov  / @felixarntz  We make a call to this endpoint in:
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/datastore/webdatastreams.js#L65

Do we want to update the following two places we call the endpoint?
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/datastore/properties.js#L264
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/datastore/properties.js#L299

**Comment by eugene-manuilov** [comment]
@ivankruchkoff no need to update datastores. What we need to do and what is missing in IB is that we need to unwrap results similar to how it was implemented in the legacy batch request method: https://github.com/google/site-kit-wp/blob/277034cb5213feb74fed30ad3e634aba8ce93874/includes/Core/Modules/Module.php#L350-L365

In our case, we need to add a new case for the `'GET:webdatastreams-batch'` datapoint to the `parse_data_response` method that will loop through all batch results and compose the resulting array which consists of propertyIDs as keys and web data streams arrays as values. Web data streams need to be processed in the same way as we parse web data streams for the `'GET:webdatastreams'` datapoint.

**Comment by ivankruchkoff** [comment]
Updated in https://github.com/google/site-kit-wp/pull/3755/commits/4b8db8abbfb5c8b57cc78a1865a1ab9f8f3af8d6 ( and a couple of subsequent commits );

**Before**
```json
{
   "272263961" : [
      {
         "name" : "properties/272263961/webDataStreams/2603234856",
         "measurementId" : "G-VLWRQ702L6",
         "createTime" : "2021-05-13T18:02:38.922Z",
         "updateTime" : "2021-05-13T18:02:38.922Z",
         "displayName" : "sitekit.10uplabs.com - GA4",
         "defaultUri" : "http://sitekit.10uplabs.com",
         "_propertyID" : "272263961",
         "_id" : "2603234856"
      }
   ]
}
```

**After**
```json
{
   "272263961" : [
      {
         "defaultUri" : "http://sitekit.10uplabs.com",
         "measurementId" : "G-VLWRQ702L6",
         "_id" : "2603234856",
         "_propertyID" : "272263961",
         "createTime" : "2021-05-13T18:02:38.922Z",
         "name" : "properties/272263961/webDataStreams/2603234856",
         "updateTime" : "2021-05-13T18:02:38.922Z",
         "displayName" : "sitekit.10uplabs.com - GA4"
      }
   ]
}
```

**Comment by asvinb** [comment]
### QA: ✅ 

* Disconnected Analytics module
* Switched to `develop` branch
* Proceeded to connect Analytics again with Devtools open
* Copied request made to `/wp-json/google-site-kit/v1/modules/analytics-4/data/webdatastreams-batch` as a CURL command.
* Response:
	```
	{"281028198":[{"createTime":"2021-07-29T12:37:57.250Z","defaultUri":"https:\/\/competent-darkling.jurassic.ninja","displayName":"competent-darkling.jurassic.ninja","measurementId":"G-BKL2ZYKK0X","name":"properties\/281028198\/webDataStreams\/2723020063","updateTime":"2021-07-29T12:37:57.250Z","_id":"2723020063","_propertyID":"281028198"}]}
	```
* Switced to `main` branch.
* Ran the same CURL command.
* Response:
	```
	{"281028198":[{"createTime":"2021-07-29T12:37:57.250Z","defaultUri":"https:\/\/competent-darkling.jurassic.ninja","displayName":"competent-darkling.jurassic.ninja","measurementId":"G-BKL2ZYKK0X","name":"properties\/281028198\/webDataStreams\/2723020063","updateTime":"2021-07-29T12:37:57.250Z","_id":"2723020063","_propertyID":"281028198"}]}
	```
* Both responses are the same.
