### ISSUE TITLE
Google icon appears too close to dashboard widget title

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#365]
## Bug Description

The Google icon appears too close to the "Site Kit" text in its dashboard widget title.

## Steps to reproduce

* Activate + Set up Site Kit
* View Dashboard

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/62226050-e099ac80-b3b9-11e9-91ab-c9b1b91071c8.png)

## Additional Context

 - PHP Version: 7.3
 - OS: MacOS
 - Browser Chrome
 - Plugin Version beta-1.0.2@89b75a3
 - Device: MacBook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* G icon should be displayed proportionally the same distance as on the plugin main dashboard 
![icon-name-distance](https://user-images.githubusercontent.com/13304791/63162957-3b6f0d00-c024-11e9-97d3-9144ecceb452.png)
  

## Implementation Brief

* Ensure the logo component css is included in the wpdashboard stylesheet so the logo can receive styling.
* Update `.googlesitekit-logo` with a modifier class for the smaller size.

## Changelog entry

* Fix Site Kit logo displaying incorrectly in the WordPress dashboard widget.

**Comment by felixarntz** [comment]
@aaemnnosttv I can't replicate this. Can you double-check your environment? Does it only happen on a specific page?

**Comment by felixarntz** [comment]
@marrrmarrr Can you chime in here? I think we need to decide how we fix this design bug in here and in #236.

My suggestion would be to remove the G branding in the WordPress dashboard, since these widgets all have plain-text titles (we could use "Site Kit Developer Beta" or "Site Kit (Developer Beta)"). This would automatically resolve #236 as well.

**Comment by felixarntz** [comment]
IB looking good.

**Comment by circlecube** [comment]
Addressed code review issues and moving to CR.

**Comment by aaemnnosttv** [comment]
QA looks good 👍 

![image](https://user-images.githubusercontent.com/1621608/63500846-4e298c00-c4d3-11e9-9521-fb224161ed89.png)

**Comment by marrrmarrr** [comment]
LGTM, verified on a couple sites.
