### ISSUE TITLE
Site Kit cannot access the WordPress REST API. Please ensure it is enabled

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3651]
## Bug Description

There have been multiple reports in just today with users encountering the below error, on sites which were previously connected fine:
`Site Kit cannot access the WordPress REST API. Please ensure it is enabled`

https://wordpress.org/support/topic/site-kit-cannot-access-the-wordpress-rest-api-please-ensure-it-is-enabled-3/ - **Resolved**  - Uninstall & Reinstall - another user within this topic reported the same.
https://wordpress.org/support/topic/site-kit-cannot-access-the-wordpress-rest-api-please-ensure-it-is-enabled-2/ - **Open** - [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNhrJsYVSNjWPs30uaWaeOAJGgK3_vCfn7Q0nbjSK0Ont06psaego1HKvJTbMuZ-gTk)
https://wordpress.org/support/topic/unable-to-link-with-site-kit/ - **Resolved** Reinstall - [SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNhIvdudMVs9upZnbe9-KtTG_RDmRRF6YPBtxQIeFN6fUlmUeIIrEhw5wuBhqlVTUbQ)

## Additional Context

 - Site Kit 1.35.0
 - No common plugins from inspecting the SH info provided
 - These reports all came in on the same day
 - There seem to be no issues with the REST API based on users sharing the status from their Site Health tab. From the users who provided additional insights their public REST endpoints are accessible. 
 - Different hosting providers 
 - In 2 cases users encountered errors with specific modules while connected. They then uninstalled (1 case) and reset (1 case) before the REST notice appeared when redoing the plugin setup. The unconfirmed errors may have been "There has been a critical error on this website" based on [1 users details](https://wordpress.org/support/topic/site-kit-cannot-access-the-wordpress-rest-api-please-ensure-it-is-enabled-3/#post-14611280). 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
While unable to recreate this specific issue using the same hosting platform and plan as one user - with mostly the same environment, [one user](https://wordpress.org/support/topic/site-kit-cannot-access-the-wordpress-rest-api-please-ensure-it-is-enabled-3/#post-14616234) did report that a simply uninstall and reinstall allowed them to proceed. Awaiting feedback from the other 2 impacted users.

**Comment by bethanylang** [comment]
Noting that an additional user in the same topic that James linked above reported that an uninstall/reinstall also worked for them.

**Comment by bethanylang** [comment]
@jamesozzie With no more reports of this issue and the uninstall/reinstall seemingly working for most affected users, what do you think about closing this?

**Comment by jamesozzie** [comment]
Sounds good. While there remains [one current impacted user](https://wordpress.org/support/topic/site-kit-cannot-access-the-wordpress-rest-api-please-ensure-it-is-enabled-2/) based on other reports this doesn't seem an issue to be an issue related to the plugin. 

To be reviewed should others report the same.
