### ISSUE TITLE
Broken stories in module-analytics-settings.stories.js

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3652]
## Bug Description

A lot of the stories are broken in `module-analytics-settings.stories.js`

## Steps to reproduce

Can be seen on this story and all the following stories (on both `main` and `develop`)
https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-settings--no-tag-gtm-property-w-access

## Screenshots

![broken-stories](https://user-images.githubusercontent.com/8496063/123964654-f3f19000-d9b3-11eb-9a61-6d7e6404d491.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
Plus, the menu story is broken as well: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global--menu

**Comment by aaemnnosttv** [comment]
I think this can be fixed by #3378 which we really need anyways. Otherwise we will keep getting issues like this popping up. Unless we already know what's needed to fix this and it will be a very simple fix, then we should prioritize #3378 instead which will need to fix all broken stories as part of the PR.

**Comment by aaemnnosttv** [comment]
Closing this out as these stories are fixed now.
