### ISSUE TITLE
Broken story in menu.stories.js

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3653]
## Bug Description

Story broken in `menu.stories.js`

## Steps to reproduce

Can be seen here on `main` and `develop`
https://google.github.io/site-kit-wp/storybook/main/?path=/story/global--menu

## Screenshots

![menu-broken](https://user-images.githubusercontent.com/8496063/123965204-8003b780-d9b4-11eb-9420-183a5291c8e7.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Menu` in its story`/?path=/story/global--menu` should be rendered just beneath the "Menu" text

## Implementation Brief

* Add a wrapping `.mdc-menu-surface--anchor` class to the parent element holding the `<Menu />`

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Check if [the menu](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global--menu) is rendered in the right place (just beneath the "Menu" text)

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@asvinb can you take a look at what is going on here? It looks like a css issue of some kind.

**Comment by aaemnnosttv** [comment]
The problem here is that the story does not wrap the menu with a `.mdc-menu-surface--anchor`.

More substantially, we should probably be using the `Menu` component from `@material/react-menu` rather than implementing our own using `MDCMenu` (see #2510).

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Checked that the menu is rendered just beneath the "Menu" text.

![image](https://user-images.githubusercontent.com/73545194/133460829-636c9f47-12d7-4b4d-ae84-af27355bcfa0.png)
