### ISSUE TITLE
Error: Request parameter is empty: accountID.

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3654]
## Bug Description

[One user in the support forums](https://wordpress.org/support/topic/google-site-kit-configuration-problem/#post-14611546) is encountering various errors when connecting the various Site Kit modules, with one such error below when connecting either the AdSense or Tag Manager modules:
`Error: Request parameter is empty: accountID.`

In addition to the on the primary Site Kit dashboard the below appear in particular widgets:

```
Data error in Analytics
Request parameter is empty: metrics.

Data error in Analytics
Sort key ga:pageviews is not a dimension or metric in this query.

Error: Request parameter is empty: strategy.
```

This is occurring on a primary domain only, with no such issues on a subdomain site on the same hosting platform. In the users Site Health information on an impacted site the below warning appears, however their publicly accessible REST endpoints are accessible ([example](https://www.maxicar.com.br/?rest_route=/))
`The REST API did not correctly process the query context parameter.
`

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/123965796-b9d0c000-d9ac-11eb-8d81-7614b9922933.png)

![image](https://user-images.githubusercontent.com/41326532/123965860-c8b77280-d9ac-11eb-9711-44b450e6e852.png)

## Additional Context

 - Site Kit 1.35.0
 - [SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgs6670EYzdslwPrI14q4iVUOaD3dSnuZ0O1id_OXk87XJE7EZTFRSWJ82t0iUErY8)
- [Error log provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNin-o95BvBojFNi-kRfw18JcWYxJ_zPvY41CauzPzszJ2YF2uXZhaJ8t8xoM81UCbo)
 - Messaging output seems similar to #2782

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check
- [x] Front end check (mixed content, minified content, combined JS)
- [x] Incognito mode 
- [x] Checked users Site Health info, no identified causes
- [x] Additional .htaccess rules applied
- [x] Uninstalled and reinstalled plugin
- [ ] User confirmed no "Critical errors" in their Site Health status
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [x] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [x] Reset Site Kit (on the SK service)
- [ ] Checked does the same occur from another admin users account
- [x] Reviewed error logs - Some gocache-cdn errors and Analytics 404 responses
- [ ] Reviewed XHR requests 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by abdullah1908** [comment]
It's more likely a host level issue based on the previous GitHub issue. Let's wait for the user's response that might help us in recreating this issue.

**Comment by bethanylang** [comment]
@abdullah1908 The user wasn't able to fix via troubleshooting steps and has moved on from the plugin for now. Should this escalate to L2?

**Comment by abdullah1908** [comment]
Sure @bethanylang 👍

**Comment by eugene-manuilov** [comment]
@bethanylang @abdullah1908 seems like this is the same server configuration issue as we saw in #2782 (https://github.com/google/site-kit-wp/issues/2782#issuecomment-814909070). I don't think we can do anything here and knowing that the user has already moved on we can probably close this ticket. What do you think?

**Comment by bethanylang** [comment]
@eugene-manuilov Makes sense to me! Closing.
