### ISSUE TITLE
Cached user surveys have incorrect TTL

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3655]
## Bug Description

The current implementation of the `triggerSurvey` action does not set TTL when it caches the survey: https://github.com/google/site-kit-wp/blob/eea7808d8ab973561179d2d15d9fa327485aeb15/assets/js/googlesitekit/datastore/user/surveys.js#L109-L112

It means that all surveys are cached for an hour since it is the default value for the `setItem` function.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `triggerSurvey` action should pass the provided `ttl` to the `setItem` function call to cache surveys for intended period of time.

## Implementation Brief

* Add js tests to verify that the survey is cached for specified ttl.
* Merge #3656

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check the `triggerSurvey` action and verify that it correctly passes the `ttl` parameter to the `setItem` function call.

## Changelog entry

* Add a configurable timeout to User Survey components.

**Comment by aaemnnosttv** [comment]
Good catch @eugene-manuilov 👍  As it is currently, this wouldn't result in a change in the survey cooldown period because the default `ttl` for `setItem` is 1 hour as you mentioned (which is the correct value for now).

The IB looks good, but since we're not in a rush to merge this so let's also add test coverage for this detail which should be fairly straightforward. Currently the tests only check that the validation for the `ttl` value, not that `setItem` is actually called with this value.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv, yes we can add tests. IB is updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by Hazlitte** [comment]
@eugene-manuilov @tofumat I have been working on the QA Eng for this.  I can see that `ttl` is now passed to the `setItem` call in the `triggerSurvey` action and the js tests are passing.

I enabled the `userFeedback` flag in my local environment and observed the state of local storage in the inspector. The user feedback modal is displayed and I select icon and close it.  But I never saw a key/value set.  Am I testing this wrong?

**Comment by eugene-manuilov** [comment]
@Hazlitte you don't need to select icon and close the survey. Just open the dashboard page and when the user survey appears, check the session storage, it should contain a record for that survey with the appropriate ttl (1 hour).

**Comment by Hazlitte** [comment]
Thanks @eugene-manuilov 👍

**QA ✅**

**Comment by aaemnnosttv** [comment]
> @Hazlitte you don't need to select icon and close the survey. Just open the dashboard page and when the user survey appears, check the session storage, it should contain a record for that survey with the appropriate ttl (1 hour).

@eugene-manuilov this was already the case before but essentially relying on the default `ttl` rather than the one which was provided that was incorrect. The added test coverage should cover the scenario though 👍
