### ISSUE TITLE
Idea Hub widget drafts tab not working as expected

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3660]
## Bug Description

While testing the Idea Hub module a little, I noticed a bug with the "Drafts" tab. Even though I had created a draft, it didn't show in the tab. This is likely due to something missed in #3357.

Here's the steps to replicate:
1. Create a draft for one of the new ideas from the Idea Hub widget.
2. The draft now appears in the "Drafts (1)" tab as expected.
3. Click on "View draft" to verify it's there.
4. Return to the Idea Hub widget in the dashboard.
5. Now, suddenly "Drafts" is empty again, even though that draft post exists.

It looks like this is happening somehow because the client-side cache for the `GET:draft-post-ideas` is not cleared as expected. We need to ensure the data is refreshed once a new post is created - users shouldn't need to wait for an hour to see the change reflected. Once I manually cleared the cache, it worked as expected. In other words, the endpoint implementation is fine, but there's something missing regarding cache invalidation.

Screenshots of that incorrect state:
![Screen Shot 2021-07-01 at 9 41 51 AM](https://user-images.githubusercontent.com/3531426/124160582-4208a100-da51-11eb-8f14-10426333715e.png)
![Screen Shot 2021-07-01 at 9 41 59 AM](https://user-images.githubusercontent.com/3531426/124160606-48971880-da51-11eb-96b1-016964552813.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Recently drafted posts should appear in the "Drafts" tab even after refreshing the page.

## Implementation Brief

* Update the `controlCallback` function for the `fetchCreateIdeaDraftPostStore` fetch store to return a new promise instead of returning the results of `API.set` function call. The new promise should do the following:
  * Wait for results of the `API.set( ... )` function call and assign it to a variable.
  * Call `API.invalidateCache( 'modules', 'idea-hub', 'draft-post-ideas' )` function to invalidate cache for the draft-ideas endpoint.
  * Resolve the promise passing the results of the `API.set( ... )` function call.

### Test Coverage

* Update existing tests if anything is failing due to the aforementioned changes.

### Visual Regression Changes

* N/A

## QA Brief

1. Create a draft for one of the new ideas from the Idea Hub widget.
2. The draft now appears in the "Drafts (1)" tab as expected.
3. Click on "View draft" to verify it's there.
4. Return to the Idea Hub widget in the dashboard.
5. Observe that the tab shows "Drafts (1)" as expected

Also 
* try adding lots of draft and then refresh the page and check that the same total of drafts is displayed

## Changelog entry

* Fix a bug in Idea Hub where the most recent draft idea posts were not shown after creating a new draft from idea.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
### **QA ✅**

This is verified fixed.

Ran a series of tests, checking drafts from the dashboard, cycling back and forth to the drafted post and back to the dashboard. No issues on my end, sending to approval.

![Posts ‹ I'm Safe Bracelet — WordPress](https://user-images.githubusercontent.com/57115907/125044208-98c53a80-e050-11eb-95bc-df0ca3503360.gif)
