### ISSUE TITLE
Analytics/useSnippetSwitch stories not all working

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3661]
## Bug Description

`Analytics/useSnippetSwitch` stories are giving error  `Element type is invalid: expected a string (for built-in components)`

## Steps to reproduce

See story here https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module--use-snippet-switch-toggled-on-default

## Screenshots

![storybook-fail-useSnippetSwitch](https://user-images.githubusercontent.com/8496063/124165751-7193c980-daa2-11eb-90c4-741034238266.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `useSnippetSwitch` Storybook stories should no longer fail with an error and instead display the expected UI state.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for raising this. I think we can hold on fixing these stories specifically until #3378 which will prevent these kinds of failures going forward.

**Comment by johnPhillips** [comment]
@danielgent CC @aaemnnosttv 
I think this was fixed with https://github.com/google/site-kit-wp/commit/d6cce732aa7cf22102b8fd552ddd575debfc69cb?

**Comment by aaemnnosttv** [comment]
@johnPhillips could be, are the stories fixed now?

**Comment by johnPhillips** [comment]
@aaemnnosttv Seems so 👍
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module--use-snippet-switch-toggled-on-default

**Comment by felixarntz** [comment]
@danielgent @johnPhillips @aaemnnosttv Looks like this is indeed no longer valid. Closing.
