### ISSUE TITLE
Users get stuck in Analytics setup if there is no matching property

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#367]
## Bug Description

On a new site, if you have Analytics accounts, but no property that matches the current site, you see the "Create an account" / "Re-fetch my account" buttons, although you should actually see the dropdowns (since you have 1+ account/s).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the user has an Analytics account, they should never see the UI for when they have no account ("Create an account" / "Re-fetch my account" buttons).
* In order to replicate this as easily as possible, remove the if condition around here: https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L1095 (so that it always returns only accounts, no properties or property matches).

## Implementation Brief

* This happens because of accessing a potentially undefined property without checking, in https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/setup.js#L280.
* It should only be accessed if defined.

## Changelog entry

* Fix undefined variable access which could prevent a user from completing the Analytics setup flow if they didn't have a matching property for the current site.

**Comment by aaemnnosttv** [comment]
Dropdowns show as expected.

![image](https://user-images.githubusercontent.com/1621608/62237173-d1722900-b3d0-11e9-9e8c-7d16f2892444.png)

QA passed 👍
