### ISSUE TITLE
User Input UI issue when question five loads

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3682]
## Bug Description

Spotted a UI bug when testing the User Input feature. When you arrive at question 5, two text input boxes appear by default without the user typing in any search terms. The text input box should only appear once, when the user starts to type. When the comma or enter key is pressed the next text box should appear. 

![userinput.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/4d4d32cb-1ce7-442c-beac-e8ae15e6e506)

## Steps to reproduce

1. Enable `userInput` on the Tester plugin
2. Connect Site Kit
3. Complete questions 1 - 4 
4. When you get to question 5 observe the two text boxes as per screenshot above. 

This appears on desktop and mobile. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The input for top search terms on step 5 of the User Input flow should not include any empty values when shown for the first time. E.g. 
![image](https://user-images.githubusercontent.com/1621608/125665130-7bd217b8-a6fc-4454-bad6-781b4f6c6199.png)
* Note this currently behaves correctly in Storybook; the issue only happens in WordPress 

## Implementation Brief
~~* Using `assets/js/components/user-input/UserInputKeywords.js`,
	* Make a copy of the `values` variable by using the spread operator when creating the `localValues` state variable.
	* Use the `useMount` hook from `react-use` to push an empty string to `localValues` (copying the same logic for when adding an empty string if the values array is empty.)~~

* Using `assets/js/components/user-input/UserInputKeywords.js`, remove the `|| values.length < max` condition from line 53.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Set up a new site, connect Site Kit, and enable the `userInput` feature in order to run the User Input questionnaire.
* Follow the steps to reproduce outlined above.
* Optionally add the code below, saved as `user-input-mock-empty-settings.php`, to your `wp-content/plugins` directory. Activate via the `Plugins` page as usual. This will mock an empty response from the proxy so that you can run the questionnaire over and over again from scratch if you clear your cache.

<details>
  <summary>Save the following as `user-input-mock-empty-settings.php`</summary>

```php
<?php
/**
 * Plugin Name: Site Kit by Google Mock Empty User Input Settings
 * Plugin URI:  https://github.com/google/site-kit-wp
 * Description: Utility plugin for mocking empty user input settings.
 * Version: 100
 * Author:      Google
 * Author URI:  https://opensource.google.com
 *
 * @package   Google\Site_Kit
 * @copyright 2021 Google LLC
 * @license   https://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
 * @link      https://sitekit.withgoogle.com
 */

use Google\Site_Kit\Core\REST_API\REST_Routes;

add_action(
	'rest_api_init',
	function () {

		register_rest_route(
			REST_Routes::REST_ROOT,
			'core/user/data/user-input-settings',
			array(
				'methods'             => 'GET',
				'callback'            => function () {
					return [
						"goals" => [
							"answeredBy" => "0",
							"scope" => "site",
							"values" => [],
						],
						"helpNeeded" => [
							"answeredBy" => "0",
							"scope" => "site",
							"values" => [],
						],
						"postFrequency" => [
							"answeredBy" => "0",
							"scope" => "user",
							"values" => [],
						],
						"role" => [
							"answeredBy" => "0",
							"scope" => "user",
							"values" => [],
						],
						"searchTerms" => [
							"answeredBy" => "0",
							"scope" => "site",
							"values" => [],
						],
					];
				},
				'permission_callback' => '__return_true',
			),
			true
		);
	},
	0
);

```
</details>

## Changelog entry

* Fix UI bugs in User Input's fifth question.

**Comment by aaemnnosttv** [comment]
Confirmed – this only seems to happen in WP though; it doesn't happen in Storybook.

![image](https://user-images.githubusercontent.com/1621608/125476349-0b72d239-fdfd-4c4d-86e7-b5d82b5f34f5.png)

Relevant state at this point in time
![image](https://user-images.githubusercontent.com/1621608/125476368-ed88e385-2e81-49ec-a53d-024a64b53337.png)

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by danielgent** [comment]
Unassigning. I'm not sure how to reset the state for `userInput`

**Comment by johnPhillips** [comment]
After discussion with @tofumatt we arrived at an alternative solution to the bug. I've updated the IB to reflect this as requested.

**Comment by cole10up** [comment]
### **QA ✅**

This one is all set on my end. Unable to reproduce with a new site.
![image](https://user-images.githubusercontent.com/57115907/131558226-80cb12db-ada3-4de7-be33-7bf240e921b8.png)

Sending to Approval.
