### ISSUE TITLE
Remove help visibility feature flag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3685]
The `helpVisibility` feature flag should be removed, now that the feature has been established and around for a while without any problems.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `helpVisibility` feature flag should be entirely removed.
* Any functionality that is currently behind the flag should now become the default behavior. Any functionality that is currently only used when the flag is disabled should be entirely removed.
    * Components or functions that are no longer used as a result should also be removed (potentially `HelpLink`).

## Implementation Brief
* Using `feature-flags.json`, remove the `helpVisibility` feature flag.
* Search for the `helpVisibility` string within the code base and review code where the `helpVisibility`. Any logic/component which was rendered conditionally when the `helpVisibility` feature was enabled should be rendered unconditionally now. Any code which was rendered when the feature flag was disabled should be removed. For e.g in `assets/js/components/settings/SettingsApp.js` where the `HelpLink` component is rendered when `helpVisibility` is disabled.
* Use of the `useFeature` hook with `helpVisibility` as parameter should be removed.
* The `PageFooter` component can be removed since it returns `null` when `helpVisibility` is enabled, this it can be safely removed. Update code base to remove occurrences of `PageFooter`.
* The `HelpLink` component should be deleted as well since it was rendered when `helpVisibility` was not enabled.
* The following components are class based ones and the `helpVisibilityEnabled` prop should be removed as well as the `withFeatureFlag` HOC use within them:
	* `assets/js/components/legacy-setup/search-console.js`
	* `assets/js/components/legacy-setup/SetupUsingGCP.js`
	* `assets/js/components/legacy-setup/site-verification.js`
	* `assets/js/components/legacy-setup/wizard-step-authentication.js`

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* Expected in cases where components are now being rendered unconditionally.

## QA Brief

* Verify that the `helpVisibility` feature flag no longer exists in the codebase.
* Verify that the other ACs have been met.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by Hazlitte** [comment]
**QA failed ❌**
Hi @johnPhillips, I found the`helpVisibility` string in a few places in the code:

* `components/legacy-setup/wizard-step-authentication.js`
* `feature-tours/help-visibility.js`
* `feature-tours/index.js`

**Comment by johnPhillips** [comment]
@Hazlitte the following shouldn't be removed because they are the feature tour itself (I could have been more clear on this in the QAB, sorry):

- `feature-tours/help-visibility.js`
- `feature-tours/index.js`

However, this one can go, so I'll open a PR to remove it.
- `components/legacy-setup/wizard-step-authentication.js`

**Comment by johnPhillips** [comment]
QAB updated to be more specific.

**Comment by asvinb** [comment]
Looked for `helpVisibility` string in the codebase, none found.

### QA: ✅
