### ISSUE TITLE
Issues in search for individual page or post by title or url 

### ISSUE THREAD

**Issue by lucymtc** [google/site-kit-wp#369]
## Bug Description
While searching posts by title in the individual post search "No results found" is returned when the string includes spaces or accents.
Also searching by URL returns "No results found"

## Steps to reproduce

1. Go to Site Kit -> Dashboard
2. Scroll down to "Search for individual page or post information"
3. Enter a word of an existing post title and see results showing, then add second word of that post title and see "No results found"
4. Enter word with accent from an existing post title that has that word with accent, see "No results found", then enter same word removing accent and see the results. 
5. Search by URL of an existing post and see "No results found"

## Screenshots

![_safari-search-individual-posts-A](https://user-images.githubusercontent.com/1204359/62276282-ffdd1c00-b443-11e9-9cd9-a398c3feb806.gif)
![_safari-search-individual-posts-B](https://user-images.githubusercontent.com/1204359/62276320-13888280-b444-11e9-9fc9-62ccd414d3bb.gif)

## Additional Context

 - PHP Version: 7.3
 - OS: macOS
 - Browser: chrome
 - Plugin Version 1.0.0-beta.1.0.3
 - Device: macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Searching for a post's title should work regardless of whether the title typed in the searchbar contains spaces, accents or any other kind of special character.
    * This should especially be tested with pasting entire titles into the search bar, e.g. titles with specific apostrophes or accent characters.

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Noticed that too on my site. Quite annoying :-)

**Comment by aaemnnosttv** [comment]
This is likely the same issue as #431 where the query is not being properly decoded on the server before using. Can we combine these issues @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv Agreed. I added the ACs from this issue to #431. Closing this one as duplicate.
