### ISSUE TITLE
Analytics snippet not inserted by default

### ISSUE THREAD

**Issue by lucymtc** [google/site-kit-wp#370]
## Bug Description
After setting up Analytic module the setting useSnippet is set to false when it should be true by default.

## Steps to reproduce

1. Activate Analytics module.
2. Go through setup flow and save settings.
3. Go to Site Kit -> Settings -> Connected Services
4. Expand Analytics settings and see "Snippet is not inserted"
5. In the console from devtools type `googlesitekit.modules.analytics.settings.useSnippet` and  see value is `false`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by rodneyjoyce** [comment]
Agree, I had no idea I had to go digging under settings to turn it on.

**Comment by felixarntz** [comment]
This is no longer relevant (was fixed a long time ago).
