### ISSUE TITLE
Analytics not connecting after new site uploaded

### ISSUE THREAD

**Issue by MarcMurrayUpfront** [google/site-kit-wp#3700]
## Bug Description

So my small agency developed a new website and moved out hosting to WPEngine from another host. 
When launching our new site, we just updated our DNS and pointed our existing domain to the new site hosted on WP Engine servers.
Since then, I have been able to get Search Console set up in Sitekit, but can't get analytics working at all.
It just loads infinitely (see image below for what I'm seeing)
I went as far as deleting the old site off the old server incase the existing integration hanging around was causing issues.

## Steps to reproduce

1. Install Sitekit on a site 
2. Repoint a new site to the current sites URL
3. Delete the old website files from the old server
3. Reinstall sitekit
4. Connect Search Console (works fine)
5. Connect Analytics (does not work)

## Screenshots

<img width="1119" alt="Screenshot 2021-07-13 at 16 34 03" src="https://user-images.githubusercontent.com/49201828/125481761-61655848-a4f3-4d33-976b-cbed284591f1.png">

## Additional Context

 - PHP Version: 7.4
 - OS: MacOS
 - Browser : Chrome & Firefox
 - Plugin Version Version 1.36.0
 - Device: Macbook Pro 2016

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for reaching out. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. Should we determine a bug or area of the plugin that requires attention we can always open this issue. 

Please include as much relevant information to your support topic as needed to assist with this issue. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.  From looking at the troubleshooting steps you've undertaken I can provide you with some other suggestions from within the support topic which will hopefully allow you to proceed with Analytics setup.
