### ISSUE TITLE
Include a link to the connected Analytics property within the Analytics edit screen - "See full details in Analytics"

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3703]
## Bug Description

The "See full details in Analytics" link within a users Analytics settings page directs users to their overall Analytics screen, and not specifically the connected property. This could be improved to ensure users land on the correct property. 

All other Analytics links do direct users to the connected property and account details, including in the below widgets:
- The primary dashboard links - Directing users to the same report from the selected time period
- The Analytics page links - Directing users to the visitor overview or other reported per the selected time period

Screenshot below showing a link directing users to https://analytics.google.com/analytics/web

![image](https://user-images.githubusercontent.com/41326532/125506526-7b3a3bde-4c51-4518-b425-860b52368a1b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@jamesozzie this was addressed in #3702 which added deep links to the connected property for UA + GA4.
