### ISSUE TITLE
Cannot link GA to my page

### ISSUE THREAD

**Issue by krisu7** [google/site-kit-wp#3705]
I want to connect GA4 to my website. After I click connect with analytics infinite loading bar appears and in console I get an error:

`Cannot read property 'replace' of undefined
    at o (googlesitekit-api.c423bd9792e7eed18683.js:1)
    at googlesitekit-modules-analytics-4.7b34aa738d17383f29ca.js:20
    at u (googlesitekit-vendor.739fd0f156bc499b3341.js:1)
    at Generator._invoke (googlesitekit-vendor.739fd0f156bc499b3341.js:1)
    at Generator.forEach.e.<computed> [as next] (googlesitekit-vendor.739fd0f156bc499b3341.js:1)
    at googlesitekit-vendor.739fd0f156bc499b3341.js:1`

Version of Site Kit: 1.36.0
Version of Wordpress: 5.7.2
Multisite enabled: true

**Comment by bethanylang** [comment]
Hi @krisu7! All support for the Site Kit plugin is provided on our [WordPress.org support forum](https://wordpress.org/support/plugin/google-site-kit/). If you [create a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) there, we'd be happy to take a look and help you troubleshoot. Thanks!
