### ISSUE TITLE
Pressing Escape in Settings > Connected Services makes all modals appear/disappear

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3707]
## Bug Description

Pressing the "Escape" key triggers all modals on the Settings > Connected Services page.

## Steps to reproduce

1. Go to Site Kit Settings, Connected Services
2. Type the "Escape" key
3. See all modals appear
4. Type "Escape" again
5. See all modals disappear

## Screenshots

![2021-07-14 14 18 14](https://user-images.githubusercontent.com/90871/125635570-34300118-0062-496b-84e3-7737371ea78c.gif)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Escape key should never trigger modals to _display_.
* Escape key should only hide the on-screen modal, if one is active.

## Implementation Brief

* Update https://github.com/google/site-kit-wp/blob/cf75379eb25e2a4099f1c40f4d78e60417864318/assets/js/components/settings/SettingsActiveModule/ConfirmDisconnect.js#L60-L64 to only call `handleDialog()` in the `onKeyPress` function when `dialogActive === true`, eg:
```js
const onKeyPress = ( event ) => {
	if ( ESCAPE === event.keyCode && dialogActive ) {
		handleDialog();
	}
};
```
* Merge #3709

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

1. Go to Site Kit Settings, Connected Services
2. Type the "Escape" key
3. Modal should NOT appear
4. Open any Modules' settings, click "Edit", then click "Disconnect $MODULE_NAME from Site Kit"—modal SHOULD appear
5. Type "Escape"
6. The modal should disappear
7. Type "Escape" again
8. Modal should NOT appear

## Changelog entry

* Fix bug in new React Router-based Settings Screen.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- When going to Site Kit Settings > Connected Services and the `Escape` key is pressed, the modal `does not appear`. 
- When opening any Modules' settings, and after clicking to disconnect the module, the `modal does appear`. 
- When you press the `Escape` key then `the modal disappears`. 
- When you press the  "Escape" key again `the modal does not appear`. 

https://user-images.githubusercontent.com/73545194/125656654-f6e42e23-9ef4-4e32-96be-18d237c8a430.mp4
