### ISSUE TITLE
HTML Encoded links in DashboardIdeasWidget/index.js

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#3708]
## Bug Description

In `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`

View draft links are html encoded, so we get broken links such as the following:
`http://sitekit.10uplabs.com/wp-admin/post.php?post=25&amp;action=edit`

## Steps to reproduce

- Enable idea hub
- Open http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-dashboard#new-ideas
- Create a draft from a new idea
- Try and open the link

## Screenshots

<img width="605" alt="Screen Shot 2021-07-14 at 5 42 26 PM" src="https://user-images.githubusercontent.com/373931/125642105-d8d3a07f-19bc-43d8-8fd9-e1ceacdf275b.png">

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The URLs used in the Idea Hub widget should not be HTML-encoded (e.g. `&amp;` should just be `&`).
* As a result of fixing this, when clicking a "View draft" link, you should actually land in that draft post in Gutenberg, rather than just the posts list page.

## Implementation Brief

* Avoid 'display' as second param for `get_edit_post_link()` https://developer.wordpress.org/reference/functions/get_edit_post_link/
* Merge https://github.com/google/site-kit-wp/pull/3732

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Create a draft then try and open the link for `View draft` it should take you to the draft post.
  
## Changelog entry

* Fix Idea Hub draft post links ampersand output.

**Comment by tofumatt** [comment]
IB ✅
