### ISSUE TITLE
AdSense Ads.txt auto placement via SiteKit

### ISSUE THREAD

**Issue by steffi-usa** [google/site-kit-wp#371]
Does the plugin ad the ads.txt file for adsense?

The below notice appears from users AdSense accounts when a domain gets approved for AdSense.
<img width="1348" alt="Screen Shot 2019-08-01 at 5 30 54 PM" src="https://user-images.githubusercontent.com/41326532/62310763-2457e900-b482-11e9-9934-22eb1997870b.png">

## Feature Description
Without an Ads.txt file placement on a users site warnings will appear on users AdSense account. While not visible from within SiteKit it would be useful for users to have Site Kit generate and place this file in users WordPress setup.  
https://support.google.com/admanager/answer/7441288?hl=en

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@steffi-usa While the plugin doesn't place the ads.txt file at present. It's a great suggestion for future releases. I will mark this as a feature request and keep it open. In the meantime there you can follow the steps [here](https://support.google.com/adsense/answer/7532444?hl=en) to create your own ads.txt file.

**Comment by steffi-usa** [comment]
Thank you for the answer

**Comment by marrrmarrr** [comment]
Thanks for the suggestion! Looking through the WP plugin repository, there are already a number of solutions that help with ads.txt file management and creation on WP: 
https://wordpress.org/plugins/search/ads.txt/
Site Kit's goal is to help with easy setup and automate as many of the steps as possible; creating and editing an ads.txt file seems like a process that requires more advanced tech savviness and time investment than most of Site Kit's users would usually have. I think we can close this for now.
