### ISSUE TITLE
Strange contrast / almost similar colors for link in blue notice

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3716]
## Bug Description

The link in the blue notice (e.g. the one for selecting a matching UA or GA4 property) uses regular Site Kit link colors. That dark blue is very close to the dark blue that is used for the regular notice text - without being exactly the same though. This is problematic for two reasons:
- It looks weird since my head thinks it should be the same color but it isn't.
- It is in general bad for accessibility because the link is barely distinguishable from the regular notice text.

This applies to the notice in general, in all 3 scenarios.

Text colour is rgb(25, 103, 210), link colour is rgb(26, 115, 232). So it is different.
![image](https://user-images.githubusercontent.com/56588136/125824070-cea7ce76-32bb-44df-8971-9d55ef706ad1.png)

Original Asana ticket for reference: https://app.asana.com/0/1200316599642381/1200443654792709

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Learn more link within all blue Site Kit info notices (particularly, used in the Analytics/GA4 setup flow) should be in the same variant of blue as the regular text in these notices. (Right now, it is in a _slightly_ different shade of blue.)

## Implementation Brief
* Using `assets/sass/components/settings/_googlesitekit-settings-notice.scss`,
	* within the `.googlesitekit-settings-notice--info` selector, add styles for the `a` selector, having the same color as its parent container.
	* update the styles for `.googlesitekit-settings-notice__learn-more` so that its content is right aligned on small screens only.

### Test Coverage

* N/A

## QA Brief

Check the stories for:
* Single line Settings Notice - https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-notices--settings-info-notice-single-line
* Multi line Settings Notice - https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-notices--settings-info-notice-with-children

Note that the IB has more specs than the AC. Read through comments  

## Changelog entry

* Consolidate blue colors in notice text.

**Comment by asvinb** [comment]
@Pratheep-lab Any suggestions about the following point:
> It is in general bad for accessibility because the link is barely distinguishable from the regular notice text.

**Comment by Pratheep-lab** [comment]
@asvinb Text links are mostly blue following the UI conventions, hence leave the "learn more" link as it is. (But please check if it is the right blue that we use for links in all other places.) 

Now we have only one option, so I propose to change the color of the copy and the star icon. We can use one of the SK standard blackish colors for this. (#3c4043 or #5b5b61). 

We already do this for the [warning notice:  ](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-notices--settings-warning-notice) 

Note:  This change will be reflected in all the places where this notice component is used. 

CC: @felixarntz @eclarke1 

Quick mockup here for reference: 

![image](https://user-images.githubusercontent.com/81642523/126624532-d966c452-3388-4d02-a939-cd994fd8a827.png)

**Comment by felixarntz** [comment]
Hmm, to me using the gray color on the light-blue background looks worse than before. Also if we changed that, we should probably also change the dropdown color.

I agree it makes sense to have links stand out - but here (the new proposed design you have @Pratheep-lab) the link is in a completely separate place, so it stands out sufficiently already as is IMO. It would be different if the link was within the regular text.

What do you think about this @marrrmarrr?

**Comment by marrrmarrr** [comment]
+1 on using physical separation (move Learn more to a corner) to make it clearer one is a link and the other just text.

**Comment by asvinb** [comment]
@marrrmarrr @felixarntz @Pratheep-lab Looking at our components, for e.g https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--create-new-view, the "Learn More" link is already separated, in its own corner. The screenshot in the Bug description looks to be outdated.
In that case, the IB is ready for review then.
cc @aaemnnosttv

**Comment by Pratheep-lab** [comment]
Correct we did move the learn more button to the right corner away from the text. However, the problem still exists on the mobile screen sizes as shown in the screenshot below: 
![image](https://user-images.githubusercontent.com/81642523/127641662-c5eebc5f-7d06-40a8-a4e5-f50ea971b87a.png)

On the mobile screens give some top padding for the learn more link to start with. Potentially, move the learn more link to the right corner on the mobile screens? 

Ideally, the link blue color should be bolder than the text blue color but it is not a blocker for now. 

CC: @felixarntz @asvinb @marrrmarrr

**Comment by felixarntz** [comment]
Good catch about the mobile difference @Pratheep-lab!

@asvinb The IB looks good, but given the above, could you also add to it the additional change of right-aligning the learn more link on mobile so that it is visually separated there too?

**Comment by asvinb** [comment]
@felixarntz IB updated. Can you check?

Thanks!

**Comment by tofumatt** [comment]
IB ✅

**Comment by danielgent** [comment]
@Pratheep-lab  You mentioned `On the mobile screens give some top padding for the learn more link to start with` but it didn't make it into the IB

This is what the blue notice looks like when it's a single row on some widths

![more top2](https://user-images.githubusercontent.com/8496063/128169508-e7173da6-bde4-4a76-8a77-24ed9bc773ea.png)

![more top](https://user-images.githubusercontent.com/8496063/128169515-c25ca294-46f5-436f-b136-a3ef7afde85a.png)

**Comment by danielgent** [comment]
![two colours in use](https://user-images.githubusercontent.com/8496063/128171017-659b75d3-2d68-4cac-9ecf-b89b2ff9d4e6.png)

These are the two blues that are mentioned. The one on the left is the notice text, the one on the right is royal blue
`$c-royal-blue: #1a73e8;`

This is not only used on the Learn More link (the point of this ticket) but also on the Select and Text Inputs used inside this Notice component

![blue colour](https://user-images.githubusercontent.com/8496063/128171403-cd3f24c3-64ea-4e33-9933-7728326bd7c3.png)

I'm doing this ticket as per the IB but I'm flagging this here as it seems odd not to change it everywhere :thinking:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt an observation, which I think @danielgent mentioned in a comment.  The font colour for the select dropdown (`set up a new account` text) is a different shade of blue.  The rest of the items are `#1967D2` but this is `#1A73E8`. Should this be changed as well so it is consistent? 

- Can confirm that the `Learn more` appears to the right side on smaller screen sizes.  - [Screenshot](https://user-images.githubusercontent.com/73545194/128714134-25be468b-8176-41f8-9bb7-8ac3f698e941.png)
- Can confirm that the `Learn more` font colour is the same as the notice.  - [Screenshot](https://user-images.githubusercontent.com/73545194/128714292-5532aa49-18ae-40d4-b145-c7c543bf751f.png)

**Comment by tofumatt** [comment]
Ah, I missed that comment here. Yes, fair enough—let's change that colour as well so they're all consistent.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Can confirm that all of the elements now have the same colour `#1967D2`

![image](https://user-images.githubusercontent.com/73545194/128845354-565bc2ae-7713-46a9-833d-271d5bc75ada.png)

**Verified:**

- Can confirm that the `Learn more` appears to the right side on smaller screen sizes.  - [Screenshot](https://user-images.githubusercontent.com/73545194/128714134-25be468b-8176-41f8-9bb7-8ac3f698e941.png)
- Can confirm that the `Learn more` font colour is the same as the notice.  - [Screenshot](https://user-images.githubusercontent.com/73545194/128714292-5532aa49-18ae-40d4-b145-c7c543bf751f.png)
