### ISSUE TITLE
Text on GA4 notice not vertically aligned

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3717]
## Bug Description

Two very minor styling points noticed:

- The text for the notice doesn't appear to be vertically aligned as per the design
- ~~There is an external icon on the 'learn more' link which isn't in the design~~ (irrelevant, the icon should be there for accessibility)

![image](https://user-images.githubusercontent.com/56588136/125824298-390e7423-df9f-4db0-8132-2fce86552c65.png)

Original Asana ticket: https://app.asana.com/0/1200316599642381/1200446917742552

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In any info notices (i.e. `SettingsNotice`), the icon on the left of the main body text should appear in a way that looks vertically aligned with the first line of text - at a minimum, if there _is_ only a single line of text.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz I don't think this issue is relevant any more 🙂  See https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module--ga4-notice

![image](https://user-images.githubusercontent.com/1621608/125965674-7394a880-83a5-401a-a447-8d09997f484a.png)

**Comment by felixarntz** [comment]
@aaemnnosttv Oh, you're right - closing then :)
