### ISSUE TITLE
Dismissing Idea Hub widget CTA results in a blank space

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3722]
## Bug Description

As noticed in https://github.com/google/site-kit-wp/issues/3360#issuecomment-880951245: After dismissing the CTA version of the Idea Hub widget to activate the module, its space remains empty unexpectedly. Instead, the following widgets should immediately shift up, replacing the empty space, with the appearance looking exactly as it does today without the Idea Hub feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Once the Idea Hub widget CTA is dismissed, the entire Idea Hub widget should change it's status so that it is in inactive state and the following widgets in the same widget area populate the space automatically according to their definition.
* Specifically, the Idea Hub widget must not return `null`, it needs to use `WidgetNull` instead.

## Implementation Brief

Inside `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js`:
* Destructure `WidgetNull` in the props alongside `Widget`:
  ```js
  function DashboardCTA( { Widget, WidgetNull } ) { // ...
  ```
* In the `if` block that runs when `dismissed` is `true` or `undefined`, return the `WidgetNull` component instead of `null`.

### Test Coverage

* No new tests required; existing tests should pass.

### Visual Regression Changes

* None anticipated.

## QA Brief

* Set up the plugin with the `ideaHubModule` feature enabled.
* Navigate to the dashboard, and scroll down to see the Idea Hub `DashboardCTA` widget.
* Dismiss the widget by clicking on the `x` in the top corner.
* The widget should disappear, and the surrounding widgets should reposition themselves to fill the space.

## Changelog entry

* Improve Widget layout when dismissing the Idea Hub call-to-action.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that when the widget disappears, the surrounding widgets reposition themselves to fill the space.  
- Tested this with a new site that had the collecting data widgets and also a site that has live data in the dashboard. 
- Checked how smaller screen sizes behaved when the widget was closed. 

https://user-images.githubusercontent.com/73545194/126490423-f74e27b5-ae1a-4c0f-96e1-7fc3900652ea.mp4
