### ISSUE TITLE
Improve source map quality for development

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3725]
## Feature Description

Source maps let us inspect the original source files from JS modules that have been bundled together (for us, using Webpack). Webpack exposes quite a few options for different source map strategies via the [`devtool` configuration option](https://v4.webpack.js.org/configuration/devtool/) which have different costs in terms of the quality of the information included and the time it adds to the build.

We currently use the `cheap-source-map` option as part of our build script:
https://github.com/google/site-kit-wp/blob/6123efaea980ad2c4179a2995b1d7c6178b010da/package.json#L9

This option has good performance for the initial build but slow rebuilds. It also only provides transformed (i.e. transpiled) code, which can make it difficult to track down the real source code. For example, in React all JSX would be shown as `React.createElement` calls, which is not ideal.

We should consider changing our source map configuration used for development, which provides the original source, rather than transformed lines. In initial testing `cheap-module-eval-source-map` seems like a good option without too much additional overhead in the initial build, and is faster that what we have now for rebuilds.  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The default options used for the development build should be updated to generate a higher quality source map that provides original source (can be lines only)
    * E.g. for React, the source map should show the source JSX rather than `createElement` calls
* A sensible default should be chosen to minimize the impact on build and rebuild times ([see the table here for a full comparison](https://v4.webpack.js.org/configuration/devtool/#devtool)) – we can always override this as part of the build command with a different value that does not require code changes

## Implementation Brief

* Update the `build:dev` command to use `cheap-module-eval-source-map` instead of `cheap-source-map`.
* Remove the `--debug` flag from the `build:dev` command.
* Add a new option `sourceMap` to the babel config in the `webpack.config.js` file with `mode !== 'production'` value: https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/webpack.config.js#L105-L110
* Update the `sourceMap` property of the `TerserPlugin` plugin to have the same `mode !== 'production'` value: https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/webpack.config.js#L293

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Build development assets and verify that you can see the original sources when you open a script in the "Sources" tab of the developer tools:

![2021-09-07_18-08](https://user-images.githubusercontent.com/873049/132368399-eef39d5a-1dfa-4700-928f-8d465ad19503.png)

## Changelog entry

* N/A

**Comment by danielgent** [comment]
What output would you like from this task @aaemnnosttv ?

I've been overriding my package.json with `--devtool source-map` when developing locally now. I'm not sure what I was doing before when we didn't have proper source maps :smile: 

On my laptop, `cheap-source-map` rebuilding from scratch takes about 35 seconds.
Further rebuilds (just saving the same file with no changes) take about 3/4 of a second

`source-map` takes about 45 seconds to build initially, and then rebuilds in a little over a second (just saving the same file again)

There's not much difference in these but I could experiment with way more file changes to see if I can increase the time taken (or throttle the CPU although I would hope all our developers are on modern laptops like mine :sunglasses: )

**Comment by aaemnnosttv** [comment]
@danielgent I would take a look at the docs for `devtool` linked above, particularly the table of cost breakdown for each option and the [`development`], [`qualities`](https://v4.webpack.js.org/configuration/devtool/#qualities), and (https://v4.webpack.js.org/configuration/devtool/#development) sections.

We should optimize for the default case which gives good quality (source) with minimal added time to the build and rebuilds. Any of the options with a cost of `slowest` for either shouldn't be considered. It would be good to see the actual difference in times for different options we could consider, but we can always override manually if we want the best quality in some instance for example.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov as per my last comment here, any of the options with a cost of `slowest` shouldn't be considered as this is not inline with the second point of the ACs.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv IB is updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by johnPhillips** [comment]
QA ✅

I used a diffing tool to verify that the source code in dev tools was identical to the original source files.
