### ISSUE TITLE
Multiple UI issues on User Feedback

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3726]
## Bug Description

Following the bug bash on User Feedback, there were several small UI improvements required as post-launch:

- [CTAs letter spacing](https://app.asana.com/0/1200379030254833/1200440325096534)
--  CTAs letter spacing need to be 0.25 instead of 1.25 as per the design
- [On Safari, text appears bold](https://app.asana.com/0/1200379030254833/1200440846479986)
-- The main text i.e. Based on your experience so far, how satisfied are you with Site Kit? appears bolder on desktop and mobile when browsing with Safari.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The CTA letter-spacing in the remote survey UI should be adjusted to 0.25 (see https://app.asana.com/0/1200379030254833/1200440325096534).
* The main question text in the remote survey UI should be adjusted so that it doesn't appear bolder than it should when using Safari (see https://app.asana.com/0/1200379030254833/1200440846479986).

## Implementation Brief
* Update `assets/sass/components/surveys/_googlesitekit-surveys.scss` to set the `letter-spacing` for `.googlesitekit-survey__footer .mdc-button` to `0.5px`.
* <del>The issue with the text appearing bolder on Safari can be fixed by adding the CSS below to the text or globally:</del>
```css
-webkit-font-smoothing: antialiased;
```
<del>
However as per:
https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/
https://responsivedesign.is/articles/font-smoothing/
we should avoid using that. The safe bet here is to defer to browser and platform defaults and only use font-smooth overrides sparingly and as a last resort. So, unless it's critical, I suggest we leave things as they are.
</del>

### Test Coverage
* No new tests to be added.

### Visual Regression Changes

* 

## QA Brief

* Trigger the User Feedback Survey in SK (if possible) or load the [SurveyCompletion:Review Storybook Component](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys--survey-completion-review-story) and check if the letter spacing for the CTAs (LET'S GO and GET HELP) have reduced their letter spacing to 0.25px (check the <a> for the button link that has the class mdc-button).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 @marrrmarrr I broke out the G logo misalignment bit into #4101, since that requires some more clarification, while we can already move forward the other two items here.

**Comment by eugene-manuilov** [comment]
IB looks good to me, but I want @felixarntz to check the comment about font smoothing in IB.

**Comment by felixarntz** [comment]
@asvinb I trust your judgement on this, so from my perspective we can leave it as is and not add the `-webkit-font-smoothing: antialiased;`. Paging @samitron7 here for visibility.

**Comment by eugene-manuilov** [comment]
Thanks, @felixarntz. IB :heavy_check_mark: then.

**Comment by jimmymadon** [comment]
eclarke1 @asvinb @eugene-manuilov The Asana Bugbash board ticket has some discussion which talks about perhaps not changing the letter spacing on CTAs as that might happen as part of a 'later redesign'? So just wanted to check: 
1. Do we still need to change the letter spacing?
2. Should the letter spacing change only on the CTA for the Survey like the IB suggests (and not on any other CTAs in the plugin)?
3. IB suggests changing the letter spacing to 0.5px - should this be 0.25px as the AC suggests or am I getting the units mixed up?

**Comment by asvinb** [comment]
@jimmymadon Since it's a small change and affecting only the user feedback CTA, I would say let's go ahead and make the change. As per [this comment](https://app.asana.com/0/0/1200440325096534/1200458909834393/f), there were talks mostly about whether we should use capitalize the CTA or have them all caps like we currently have. Looking back, at the proposed change in the IB, you're right, it should be `0.25px`.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Tried to trigger the user feedback form on a test site, but unsuccessfully.  I have therefore tested this on Storybook. 

- The letter spacing for the CTAs (LET'S GO and GET HELP) have reduced their letter spacing to 0.25px
- The button link has the class mdc-button.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/145824851-0dcfb37c-291a-4516-ae27-ed9848e98044.png)

![image](https://user-images.githubusercontent.com/73545194/145824867-b7fe00cf-283f-4b64-b47b-93fcf58f050d.png)

</details>
