### ISSUE TITLE
Settings edit view leads user into blocked state if module has no settings edit component

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3727]
## Bug Description

Currently the Idea Hub settings does not have any settings which can be edited, which makes it similar to PageSpeed Insights in that it only has a `SettingsView` component.

All active modules can still technically be edited though as this is the only way to disconnect a module.

For Idea Hub, the user gets into a somewhat blocked state when editing the module settings as the "Close" button to exit the edit mode is disabled. This is because the module does not have any validation for submitting changes. This is irrelevant of course because the module has no editable settings.

Also, for both modules, there is nothing rendered when the module is in edit mode, which is a bit of a poor experience. We should at least continue to render the settings view, if there is one.

## Steps to reproduce

1. Activate Idea Hub
2. Edit Idea Hub settings
3. See disabled Close button

## Screenshots

User is blocked from obvious way to exit edit mode (still technically possible by toggling module header to close it)
![image](https://user-images.githubusercontent.com/1621608/125925700-c5e346c7-2469-4ada-9900-9a06a1a8ae1d.png)

PageSpeed insights in edit mode
![image](https://user-images.githubusercontent.com/1621608/125925708-944079ff-6a08-4163-93e8-88949e1d17b9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Modules that do not implement settings validation (submit changes) should not be blocked from exiting settings edit context
* Module settings should render a module's `SettingsView` component when editing when no `SettingsEdit` component is provided

## Implementation Brief

* Finish and merge #3728 

### Test Coverage

* Add a test that the settings view component is rendered when a module without a settings edit component is edited
* Add a test that the Close button is not disabled for a module without a settings edit component when in edit mode

### Visual Regression Changes

* None expected

## QA Brief

* Activate Idea Hub and PSI modules
* When editing these modules, see that the settings view is still shown
* Ensure the Close button is not disabled when the module is edited

## Changelog entry

* Ensure the "Edit" mode for modules without a dedicated "Edit" UI for their settings can still be exited, and fall back to showing the regular "View" UI in those cases.

**Comment by felixarntz** [comment]
@aaemnnosttv IB ✅ 

Left one comment on the PR though. Another thing to pay attention to here is that we still keep the behavior intact that you can't edit Search Console settings because there it is indeed entirely pointless (since you can neither edit settings nor disconnect).

**Comment by aaemnnosttv** [comment]
> Another thing to pay attention to here is that we still keep the behavior intact that you can't edit Search Console settings because there it is indeed entirely pointless (since you can neither edit settings nor disconnect).

@felixarntz I'm not sure exactly what you mean – Search Console has settings for the domain property now 🤔  https://google.github.io/site-kit-wp/storybook/main/?path=/story/search-console-module-settings--edit-with-all-settings.

It is however still not possible to disconnect it 👍

**Comment by felixarntz** [comment]
@aaemnnosttv Oops, I had forgotten we changed that 😆

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

With Idea Hub and PSI modules activated, the settings view is still shown for both modules and the `Close` button is not disabled when the module is edited.  

![image](https://user-images.githubusercontent.com/73545194/126637598-71bdfb09-8747-422f-8941-7823dfe7443b.png)
