### ISSUE TITLE
Non-Template Based Builder Incompatibility

### ISSUE THREAD

**Issue by RenaudGagne** [google/site-kit-wp#373]
## Bug Description
Hi, I tried with various theme settings and I discovered that everything works except with Non-Template based page builders

## Steps to reproduce

1. Install Oxygen Builder
2. Setup Google Kit
3. Authentify Analytics
4. Unable to find account

## Screenshots

![Waters Edge v2 — WordPress](https://user-images.githubusercontent.com/14856170/62311099-09bd4a00-b459-11e9-97f9-6b168fcb385e.png)

## Additional Context

 - PHP Version: 7.2.7
 - OS: windows 10
 - Browser: All

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by RenaudGagne** [comment]
@jamesozzie I've also opened a ticket on Oxygen Buillder github: 
https://github.com/soflyy/oxygen-bugs-and-features/issues/459

**Comment by jamesozzie** [comment]
@RenaudGagne Can you share any console errors you see when using Oxygen Builder, errors from the same screen you highlighted, "refetch my account".
