### ISSUE TITLE
Publish VRT results somewhere

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3736]
## Feature Description

In the same way that we publish storybook for each PR, I think we should look into publishing VRT results somewhere.

When the VRTs fail on a PR it's slightly time consuming to
* download the artifact
* extract it locally
* view the report

This is compounded by the fact that we have a few false positives (e.g. https://github.com/google/site-kit-wp/issues/3552) so I find myself repeating the above manual process a lot just to see it was a false positive

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this for now as we don't have a good place to publish these to and they're already available as an artifact of the action run which is still quite a bit quicker to download than run the tests 😄
