### ISSUE TITLE
Uncaught TypeError: Cannot read property 'OverlayView' of undefined

### ISSUE THREAD

**Issue by rishnarang** [google/site-kit-wp#3738]
## Bug Description

Installing site kit in Wordpress causes other .js file with map overlay code to break. 

```
"object" == typeof google && (CustomMarker.prototype = new google.maps.OverlayView), CustomMarker.prototype.draw = function() {
        var e = this.div;
        if (!e) {
            e = this.div = document.createElement("div");
            var t = this.templateData.itemId;
            e.className = "mkdf-map-marker-holder", e.setAttribute("id", t), e.setAttribute("data-latlng", this.latlng);
            var a = _.template(j(".mkdf-info-window-template").html());
            a = a(this.templateData);
            var o = _.template(j(".mkdf-marker-template").html());
            o = o(this.markerData), j(e).append(a), j(e).append(o), e.style.position = "absolute", e.style.cursor = "pointer", this.getPanes().overlayImage.appendChild(e)
        }
        var i = this.getProjection().fromLatLngToDivPixel(this.latlng);
        i && (e.style.left = i.x + "px", e.style.top = i.y + "px")
    }, CustomMarker.prototype.remove = function() {
        this.div && (this.div.parentNode.removeChild(this.div), this.div = null)
    }, CustomMarker.prototype.getPosition = function() {
        return this.latlng
    },
```

Error: Uncaught TypeError: Cannot read property 'OverlayView' of undefined

## Steps to reproduce

Go to 'https://www.andreaabroad.com/wp-content/themes/backpacktraveler/assets/js/modules.min.js?ver=5.7.2'
Error: Uncaught TypeError: Cannot read property 'OverlayView' of undefined

## Additional Context

<img width="1440" alt="Screen Shot 2021-07-19 at 3 11 31 PM" src="https://user-images.githubusercontent.com/82465478/126233991-ababa831-edf1-4ea6-ba1c-6697b68f3cfa.png">

Works after disabling site kit

<img width="1425" alt="Screen Shot 2021-07-19 at 3 12 17 PM" src="https://user-images.githubusercontent.com/82465478/126234044-d76cc9b3-d74e-45f1-9696-4de247fb17d0.png">

<img width="1433" alt="Screen Shot 2021-07-19 at 3 12 38 PM" src="https://user-images.githubusercontent.com/82465478/126234056-34a6c27d-44f3-4b65-8247-4b372b5d3966.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@rishnarang All support for the Site Kit plugin is provided on our [WordPress.org support forum](https://wordpress.org/support/plugin/google-site-kit/). If you [create a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) there, we'd be happy to take a look and help you troubleshoot. Thanks!
