### ISSUE TITLE
Issue Accessing Data: You need to reauthenticate your Google account - error

### ISSUE THREAD

**Issue by ahiadh** [google/site-kit-wp#374]
Hello :)

After successfully connecting the site-kit to my website, it seems that the google analytics is not connected (i can see info from the search console).

I get the error "Issue accessing data You need to reauthenticate your Google account.".

Bellow there is a "click here" button that allows me to give google the permissions it asks for but goes back again to the "Issue accessing data" error.

i do get the email that says "Site Kit on (website address) app got access to your account".

Thank you!

**Comment by jamesozzie** [comment]
@ahiadh This error was reported previously and could be as a result of caching or security plugin conflicts or ad blockers. Can you try the following:
1. Remove the [Analytics module](https://i.imgur.com/6ppIDwZ.png) (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
2. Temporarily deactivate any security plugin (iThemes security, Monster Insights etc), along with any caching plugin (Breeeze, WP Super Cache etc)
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

If the above fails to resolve the issue can you use a plugin such as "[Debug Info](https://i.imgur.com/VhGa8ob.png)" to send your current WordPress environment details?

**Comment by jamesozzie** [comment]
@ahiadh Any luck getting Site Kit connected after attempting the steps above? If not please send any console errors you might see.

**Comment by ahiadh** [comment]
Hello.

it didn't help.
i'm sending the debug info...

WordPress Version: 5.2.2
Current WordPress Theme: Leader Child version 1.0.0leader
Theme Author: Pojo - http://pojo.me/
Theme URI: http://pojo.me/
PHP Version: 7.0.33
MySQL Version: 5.5.60-MariaDB
Apache Version: This information is not available.
Active Plugins:

Advanced noCaptcha & invisible Captcha (5.5)
Custom Body Class (0.7.1)
Debug Info (1.3.8)
Duplicate Post (3.2.3)
Elementor (2.6.8)
Elementor Pro (2.6.2)
Google Analytics Dashboard for WP (GADWP) (5.3.8)
Gravity Forms (2.4.11)
Head, Footer and Post Injections (3.1.3)
Insert PHP Code Snippet (1.2.6)
Loco Translate (2.3.0)
LTR <=> RTL Admin content (0.5)
Pojo Forms (1.4.7)
Prismatic (2.1)
Redirection (4.3.2)
Self-Hosted Google Fonts (1.0.1)
Site Kit by Google (1.0.0-beta.1.0.3)
Title and Nofollow For Links (1.07)
WeSafe by uPress (1.7.2)
WP Hide Post (2.0.10)
WPMU DEV Dashboard (4.7.3.1)
WP Rocket (3.2.5)
Yoast SEO (11.8)

**Comment by ahiadh** [comment]
wesafe only limits connection attempts

**Comment by jamesozzie** [comment]
@ahiadh Can you share any console errors you see, alongside any [XHR responses](https://i.imgur.com/jLBwBdH.png)? Potential fix in #89

**Comment by jamesozzie** [comment]
@ahiadh Did you manage to get the Analytics module connected in the end?

**Comment by jamesozzie** [comment]
@ahiadh I will close this issue due to lack of response. Feel free to reopen if you are encountering the same issue. Include additional information such as your site health information, console errors and XHR responses.

**Comment by jeg000** [comment]
I have this issue recently and I've seen at least 2 threads related to this error.  I have had no luck fixing the issue.  Has then been any further findings regarding this issue?
