### ISSUE TITLE
Cannot read property '__eventTarget' of null

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3741]
## Bug Description

One user in the support forums is encountering the below error after updating to Site Kit 1.37.0

```
Cannot read property '__eventTarget' of null
    in GoogleChart
    in div
    in UserCountGraph
    in div
    in Cell
    in div
    in Row
    in div
    in Grid
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in DashboardAllTrafficWidget
    in WhenAnalyticsActive(DashboardAllTrafficWidget)
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in Grid
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardApp
    in GoogleSitekitDashboard
    in RestoreSnapshots
    in ErrorHandler
    in Root
```
https://wordpress.org/support/topic/cannot-read-property-__eventtarget-of-null/

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@jamesozzie Any updates on this one?

**Comment by jamesozzie** [comment]
No response from the impacted user and unable to reproduce so far. Closing
