### ISSUE TITLE
Switch Idea Hub module REST route for updating idea states to actually use Idea Hub API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3747]
Broken out from #3518: Since the Idea Hub API route to update an idea's state is still not working correctly, the `POST:update-idea-state` REST endpoint should be connected to the actual API separately, in this issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `POST:update-idea-state` endpoint should use https://github.com/googleapis/google-api-php-client-services/blob/master/src/Google/Service/Ideahub/Resource/PlatformsPropertiesIdeaStates.php, passing platform and property similar to the other endpoints (see #3518) and the received idea name as the "ideaState" placeholder in the path. The data point should expect a single variable `ideaState` which needs to be an object / associative array with `name` (idea name string, also used in the path as mentioned right above), `saved` (boolean) and `dismissed` (boolean) fields.
* In other words, with this issue, saving/unsaving and dismissing an idea should actually begin to work / result in the idea no longer showing up in the new/saved tab.

## Implementation Brief

* Verify that the approach in #3767 works as intended when the corresponding Idea Hub API starts to work correctly. If it doesn't work as intended (see AC) then make necessary changes and send PR for code review

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Activate Idea Hub module
* Set the custom site URL setting in the Site Kit developer settings to `https://www.elasticpress.io/`
* Go to the dashboard and verify that you see new ideas
* Click on the pin icon to save the idea. Verify that the saved idea has been moved to the "Saved" ideas tab.
* Refresh the page and verify that the saved ideas list contains the recently saved idea and the new ideas list doesn't contain it anymore.
* Now unsave the idea and verify that the idea has been moved to the ideas list (at the end). Plus after refreshing the page you see it in the new ideas list and don't see it in the saved ideas anymore.
    * **NOTE:** While the above is what _should_ happen here, there appears to be currently a bug with the API that prevents the first sentence above from working. In other words, the (for now broken) accepted functionality is: When unsaving, at first the idea won't move back to the "New" tab. But it should at least have been moved there once you refresh the page. This likely needs to be fixed at the API level (also see https://github.com/google/site-kit-wp/pull/3767#discussion_r685573564).
* Dismiss an idea and verify that the idea doesn't re-appear after refreshing the dashboard page.

## Changelog entry

* Implement functionality for saving and dismissing an Idea Hub idea.

**Comment by felixarntz** [comment]
@eugene-manuilov Don't worry too much about the IB here, since it was pretty much already clear in #3518. Starting a PR and referring to that should be fine.

**Comment by eugene-manuilov** [comment]
@felixarntz basic IB is added. Could you please take a look at it?

**Comment by felixarntz** [comment]
IB ✅ 

Let's wait with updating the PR (or keep it in sync) until #3681 is merged.

**Comment by felixarntz** [comment]
@eugene-manuilov Can you also add a QA Brief here? It should include some basic testing of saving, unsaving, and dismissing, since that's now enabled by this API endpoint.

**Comment by eugene-manuilov** [comment]
@felixarntz QAB is added.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov @felixarntz  I noticed that when the idea is moved back to the new tab after un-pinning it (and refreshing), it's not at the end of the list. It appears in the same place as it was when you clicked to save the idea.  Not sure if this is part of the fix that you are currently working on but thought I'd highlight. 

**Verified:**

- New ideas appear on the dashboard.  [Screenshot](https://user-images.githubusercontent.com/73545194/128829723-3bda5b69-477f-4bc0-8898-ca4523fefb4a.png)
- When you click on the pin icon, the idea is sent to the `Saved` tab.   [Screenshot](https://user-images.githubusercontent.com/73545194/128829674-62ad8456-a2cc-401d-9ae2-b23670de3870.png)
- When you refresh the page, the idea remains in `Saved` tab and it's not in the `New` tab. 
- When I click to unpin in the `Saved` tab, the idea is not moved from the tab until you refresh the page. 
- When you dismiss an idea it is deleted and doesn't re-appear after refreshing the dashboard page.

Created this screencast of the current behaviour for reference. 

https://user-images.githubusercontent.com/73545194/128831285-7fe26c66-0137-4547-9de6-b9f68eba9c57.mp4

**Comment by eugene-manuilov** [comment]
> I noticed that when the idea is moved back to the new tab after un-pinning it (and refreshing), it's not at the end of the list. It appears in the same place as it was when you clicked to save the idea. Not sure if this is part of the fix that you are currently working on but thought I'd highlight.

@wpdarren that's fine, it doesn't have to be at the end. Apologies for confusing QAB. The most important is that the un-pinned idea is moved back to the new ideas list.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv or @felixarntz (whoever is the first) do you mind reviewing a follow-up PR that fixes the issue with un-pinned ideas? #3818

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- New ideas appear on the dashboard.  [Screenshot](https://user-images.githubusercontent.com/73545194/128829723-3bda5b69-477f-4bc0-8898-ca4523fefb4a.png)
- When you click on the pin icon, the idea is sent to the `Saved` tab.   [Screenshot](https://user-images.githubusercontent.com/73545194/128829674-62ad8456-a2cc-401d-9ae2-b23670de3870.png)
- When you refresh the page, the idea remains in `Saved` tab and it's not in the `New` tab. 
- When I click to unpin in the `Saved` tab the idea is removed and is added to the end of the list of ideas in `New` tab. 
- When you dismiss an idea it is deleted and doesn't re-appear after refreshing the dashboard page.
- When you save an idea and while its in the `Saved` tab, I am successfully able to create a draft.  The idea then moves to `Draft` tab

Created a screenshot to show the pin and unpin in action 


https://user-images.githubusercontent.com/73545194/128853449-f0ba5b24-2eab-4827-951e-126feb758b87.mp4
