### ISSUE TITLE
Some REST API responses returning incorrect status codes 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#375]
## Bug Description

Many API requests are coming back to the browser as 500 errors as a default status for a failed request due to insufficient permissions, etc - not due to an error on the server which is what `5xx` errors indicate. 

There are many places where `WP_Error`s are used as the means of returning an unsuccessful response such as `\Google\Site_Kit\Modules\Search_Console::create_data_request`. When used in this way, it's necessary to set the `status` key of the `$data` parameter, otherwise it [defaults to a `500` status](https://github.com/WordPress/WordPress/blob/84c79fcdfdac9fa6ff0b2441ba549dfc100b5ebe/wp-includes/rest-api/class-wp-rest-server.php#L150-L157).

Some endpoints aggregate multiple errors in a single `WP_Error` object which use an appropriate HTTP response code as the WP_Error's error code, but this is not sufficient for setting the HTTP status when used as a response.

Other places in the code fallback to a 500 status as the default explicitly (`\Google\Site_Kit\Core\Modules\Module::exception_to_error`) which should not be used unless a truly fatal error has happened.

Any requests which successfully reach the server and return a response but were otherwise unsuccessful, should use the appropriate response code which should likely be a `4xx` class error in most cases. The specific code it returns should be matched to the result of the response.

## Steps to reproduce

One example:

1. Reset Site Kit
1. Add valid client configuration
1. Sign in with Google
1. Verify URL using URL that does not contain a verification tag
1. See 500 error in browser console

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a request to a Google API fails, it should return the corresponding HTTP status code that the original API response came back with, rather than a 500.

## Implementation Brief

* `Module::exception_to_error()` should be modified:
    * There is some unnecessarily overcomplicated logic in here currently: `Google_Service_Exception::getErrors()` returns the same as `json_decode( Google_Service_Exception::getMessage(), true )` would - so having that same logic in here is pointless, we should just rely on `Google_Service_Exception::getErrors`.
    * Instead of hard-coding a 500 status, we should see if `$e->getCode()` is numeric and truthy (to prevent 0 being interpreted as response code).
    * For a `Google_Service_Exception`, the return value of `getMessage` will be a JSON-encoded string typically. Therefore we should instead use `getErrors` to determine the message if present, and also the reason if present. (This was already happening before, but via the above overcomplicated logic.)
* As part of this PR, the `AdSense::exception_to_error()` override should stay in place, simply because that module's JS implementation is too unstable. This will be removed via #1014.
* Merge #1264

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv It would be great if you could review / give some examples of Google API responses and how they return their error code (particularly those that contain "aggregate errors").

We should look at those HTTP response codes, e.g. if they are all 403, we should return a 403. If the Google API request results in an exception where we can't determine any response code, I'd argue we should still serve a 500, as that's also what would happen if we had never caught that exception.

**Comment by aaemnnosttv** [comment]
✅ IB

**Comment by ShahAaron** [comment]
Tested

PR code
PHP Unit tests - passed
Checked in console for 500 errors - none found

Site still functioning correctly

Passed QA ✅
