### ISSUE TITLE
Duplicate Notices in WordPress Dashboard for Summary Widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3753]
## Bug Description

On a site installing Site Kit for the first time. Created new Search Console and Google Analytics accounts on a brand new Google account. When I go to the WordPress dashboard, in the Site Kit widget Summary widget, the gathering data notices are duplicated as you can see on the screenshot below. 

This was tested on the latest version 1.37.0 and with no tester plugin installed. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/b595200d-bee7-42c4-81c6-3c9fadf80dd6)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this as fixed in #1147. Looks like I meant to close it a few months ago and it didn't go through 😄 
Thanks @wpdarren 👍
