### ISSUE TITLE
GA4 - "additional permissions required" notice despite granting all permissions

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3756]
## Bug Description

Since Site Kit created a GA4 property (from 1.36.0 onwards) user's are reporting the following dashboard notice - despite having granted full permissions when connecting Analytics:

`"additional permissions required", site kit cant access the relevant data from analytics 4 (alpha) because you haven't granted all permissions requested during setup.`

Despite the notice the Analytics module remains "connected" as per a [screen recording (link with SH info)](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNhtW4MGeTmH-XQXwW1WeXB-AWwqeK9uQvZHdmB7ecW3O1yOMnVRVgJIQNvo0KF8Foc
) from one of the impacted users below - although some users are however reporting no data for over a week (possible separate issue)

There have been at least 3 occurrences (and another user mentioning the same in an existing topic)
- https://wordpress.org/support/topic/analytics-data-is-not-yet-available-please-check-back-later-17/#post-14702896 - **Open** - SH info provided within support topic ([video also provided - showing the error](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNhtW4MGeTmH-XQXwW1WeXB-AWwqeK9uQvZHdmB7ecW3O1yOMnVRVgJIQNvo0KF8Foc))
- https://wordpress.org/support/topic/analytics-not-intergrating/ - **Resolved** unknown fix, various steps performed - [SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNgFxVIPLsArQIE4OWoANCXvKzDL_FXQYhjEeZEygV6SRCABZ21DN71Ly_omY6zhT2U)
- https://wordpress.org/support/topic/unable-to-login-to-sitekit-because-you-did-not-grant-the-necessary-permission/#post-14701085 - **Resolved** Unknown exact cause, Health Check & Troubleshooting plugin used - [SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNi1mljsCKs1MCXtU1TeDnIbtj7PemeWmlK9kQ-NnyzA6jFLALpJ6n9EZY52NguW4ho). This particular site is also redirected to a ‘redirect_uri’ mismatch notice - awaiting further insights. This is something [another user](https://wordpress.org/support/topic/invalid-analytics-redirect-uri/) reported recently (not in their own support topic - they did share their [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNgTp-hXNrS0UQ9mfvRvlfXkTZTgU4joOrE09SxmLm8MddoeuYeKmOEU3Aki1SvXWow))

The impacted sites have the below flags evident within their SH info. Awaiting checks on whether Analytics setup proceeds when allowing the plugin to create a new account as opposed to selecting a pre existing account

```
analytics_account_id: none
analytics_property_id: none
analytics_profile_id: none
analytics_use_snippet: yes
analytics_4_property_id: none
analytics_4_web_data_stream_id: none
analytics_4_measurement_id: none
analytics_4_use_snippet: yes
```

## Additional Context

 - Plugin version 1.37.0
 - Video demonstration of experience provided by one user [within their Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNhtW4MGeTmH-XQXwW1WeXB-AWwqeK9uQvZHdmB7ecW3O1yOMnVRVgJIQNvo0KF8Foc)
 - There are reports ([example topic 1](https://wordpress.org/support/topic/analytics-still-gathering-data-2), [example topic 2](https://wordpress.org/support/topic/data-is-not-available-please-check-back-later/)) of Analytics also not gathering data for a UA property once added via Site Kit since GA4 integration.  
- All existing Site Kit users, no issues before 1.36.0 or 1.37.0
- As evident from the screen recording users are asked for additional permissions when accessing the Site Kit connected property from the analytics.google.com interface also. So the issue may be stemming from the Analytics platform. 

Unreproducible so far in support, testing ongoing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
One topic remains open on this issue however the "_additional permissions required_" notice no longer appears. There does seem to be no data within the Site Kit Analytics dashboard for this site, despite data appearing within the Analytics web UI. This is the same as reported in other topics, [one recent.](https://wordpress.org/support/topic/google-site-kit-data-not-showing/#post-14737248).

**Comment by bethanylang** [comment]
@jamesozzie Any update on this one?

**Comment by jamesozzie** [comment]
There have been no additional reports of this since the last batch. No open related support topics. Let's close this one. We can reopen if we encounter anymore occurrences.
