### ISSUE TITLE
Add support for additional survey question type "multi_select"

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3761]
When the initial user feedback survey was introduced, scope of the MVP was limited to only support questions of the "rating" type, since that was the only one used for the initial survey. This should now be followed up on, with this issue focusing on the "multi_select" question type.

![Screen Shot 2021-07-26 at 3 51 57 PM](https://user-images.githubusercontent.com/3531426/127069280-ed227901-11b6-49b7-ac15-85c4c10801b8.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `SurveyQuestionMultiSelect` JS component should be introduced and integrated into the user feedback survey JS infrastructure, rendering a survey question of type "multi_select".
* The UI should look like the above screenshot and follow the "rating" question type where similar (e.g. font, spacing, G icon etc.).
* The available arguments to consider here from the Site Kit Service `/survey/trigger/` API response are fairly similar to those for the "rating" type, as follows:
    * `question.question.answer_choice` contains the list of choices, with `answer_ordinal` (int) and `text` (string), like for the rating question type.
        * In addition, an extra `write_in` boolean property should be supported within each answer choice. If set to `true`, the respective answer should offer a free-text input where the user can type something custom. In that case, the `text` field should be displayed right before the text input. The text input must be non-empty in order to proceed. The maximum character limit should be 100. (This additional free-text input concept is also used in #3760, so this should be coordinated to work similarly, potentially reuse common logic where possible.)
    * In addition, `question.question.min_choices` and `question.question.max_choices` should be supported - if present, these are integers that limit the minimum required and maximum allowed choices to provide (relevant since this is a multi-select question). The default should be 1 minimum, unlimited maximum.
* The data object for answering the question (what needs to be passed to the `answerQuestion` function prop) should look as follows:
    * A single `answer` property, containing an array of objects about the selected answers, each with its `answer_ordinal` (similar to the "rating" question type), and in addition `answer_text` (string with free-text input value, if applicable for the selected answer).
    * Example: `{ answer: [ { answer_ordinal: 2 }, { answer_ordinal: 4, answer_text: 'My custom response' } ] }`
* The new question type should have an example in Storybook where it can be inspected, similar to the existing "rating" type component.

### Additional ACs after QA

* If the `min_choices` value is provided and more than 1, a helper text should be shown below the list of answers (to clarify that one answer is not sufficient to proceed): _Choose at least %s answers_
    * This helper text can have styling similar to the helper text for the `open_text` question type (see #3762).
* The `min_choices` and `max_choices` fields need to be on the `question.question` object, not the main `question` object (this is also in the original ACs above, but the implementation is slightly off).

#### Create new component

Create `assets/js/components/surveys/SurveyQuestionMultiSelect.js`

Base on SurveyQuestionRating.js

* wrap everything in a div with class `.googlesitekit-survey__question-rating`
* Use `SurveyHeader` for the current header
* Add string props and propTypes: `question`
* Add function props and propTypes: `answerQuestion`, `dismissSurvey`
* Add number props and propTypes: `min_choices`, `max_choices`
* Add `choices` propType like on `SurveyQuestionRating` *but* with an additional boolean `write_in` key
* Use the `TextField`, `Input`, 'Checkbox', and 'Button' components
* Normalise the `choices` prop into a datastructure that, for each `answer_ordinal`, stores a `selected` bool and `answer_text` (if `write_in` is true)
* When an option checkbox is toggled, update the `selected` value in this data structure for that `answer_ordinal`
* Do not allow any TextField to be edited if that option is not checked
* In order to limit user input to 100 characters, just disallow extra characters in the TextField's onChange handler (slicing the text to 100 characters)

Set the disabled prop to true on the submit button if:
* The TextField is empty for a selected option
* There are fewer options selected than the prop min_choices allows
* There are more options selected than the prop max_choices allows

When submitting
* pass the answer to `answerQuestion` as per AC example. 

In `assets/sass/components/surveys/_googlesitekit-surveys.scss`

* Add a new rule for `.googlesitekit-survey__multi-select`
* Nest rule for `.googlesitekit-survey__body`
* Style this to match the design. Something like:
    * phone gap padding on mobile
    * horizontal desktop gap padding on desktop

#### Add new component to map on `assets/js/components/surveys/CurrentSurvey.js`

* `ComponentMap` also needs to map `multi_select` to `SurveyQuestionMultiSelect`

:exclamation:  :exclamation:  **See PR here with everything done up until here** https://github.com/google/site-kit-wp/pull/3788 :exclamation:  :exclamation: 

### Test Coverage

* Add new tests within `assets/js/components/surveys/CurrentSurvey.test.js` for the new question type.

We need to add this question type to the "main" test suite for `CurrentSurvey` to make sure the question type works as expected when "plugged in" to the rest of the survey components, next button, etc. 

### Visual Regression Changes

* None

## QA Brief

* Check that https://google.github.io/site-kit-wp/storybook/develop/path=/story/components-surveys--survey-question-multi-select-story works and behaves as per AC
* Enter the code from https://pastebin.com/x0iiFBWh into your browser console on a Site Kit dashboard page to trigger a survey with a question from #3760, this issue (#3761), and #3762.

## Changelog entry

* Add multiple choice selection questions to User Input surveys.

**Comment by danielgent** [comment]
@felixarntz I think the AC needs changing (and I don't think I should be doing that! :smile: )

The AC refers to itself
``` (This additional free-text input concept is also used in Add support for additional survey question type "multi_select" #3761, so this should be coordinated to work similarly, potentially reuse common logic where possible.)```

I think this should refer to https://github.com/google/site-kit-wp/issues/3760 !

**Comment by danielgent** [comment]
@asvinb  has some concerns with https://github.com/google/site-kit-wp/issues/3760 so I'll do as much of the IB of this as I can, but I'll leave it on hold until Asvin's questions are answered :smile:

**Comment by felixarntz** [comment]
@danielgent Good catch - I've fixed this in the ACs.

I've replied to all of @asvinb's questions, so you should be able to proceed with the IB here (to which the same things apply).

**Comment by danielgent** [comment]
I've created a PR here of this component pretty much working https://github.com/google/site-kit-wp/pull/3788

See the story here https://google.github.io/site-kit-wp/storybook/pull/3788/?path=/story/components-surveys--survey-question-multi-select-story

I've added comments to the PR. We can discuss what I should write for the IB (based on my other outstanding IB) :+1:

**Comment by aaemnnosttv** [comment]
Thanks @danielgent – please add a brief description that outlines an approach that touches on each item in the ACs. No need to duplicate what those are, but you can always use that as a kind of blueprint for your IB. The PR looks mostly good but a brief description without getting into encoding the code itself into words would be great.

Also, as mentioned on #3762 – we also need to account for added tests here. That can also be a high-level description but please add this as well and account for it in the estimate which is still needed here as well.

**Comment by aaemnnosttv** [comment]
@danielgent would you please add an estimate?

**Comment by danielgent** [comment]
Done @aaemnnosttv . I put it the same as the other ticket  :+1:

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by danielgent** [comment]
@tofumatt Assigning back to you as I have some questions :smile:

**Comment by cole10up** [comment]
### **QA ⚠️**

Tested multi_select using the QA brief code:
![image](https://user-images.githubusercontent.com/57115907/130182563-2a44200d-ddcf-416c-8bd4-96e1911a8dd1.png)

Confirmed Firefox, Chrome, Safari and Edge

Checked both links at the bottom of the modal drive to the proper links in a new tab.

@tofumatt I noticed that after the user selects over 4 items the next button is grayed out, is this expected?

![image](https://user-images.githubusercontent.com/57115907/130182930-a5a2c428-a6e9-487e-95f6-df00e6961f9e.png)

**Comment by tofumatt** [comment]
Hmm, that's sort of expected but incomplete. I suppose a better solution would be to either:

1. Disable all checkboxes when the maximum number have been reached
2. Show a warning when too many items are selected

The first option is what we do elsewhere (in User Input, for instance):

![2021-08-20 16 10 14](https://user-images.githubusercontent.com/90871/130254479-83df8a14-2358-465f-8288-f27afd437891.gif)

So I think this doesn't quite yet pass QA; I'll add that and send this back to Code Review. 👍🏻

**Comment by aaemnnosttv** [comment]
Back to you for another pass @cole10up 👍

**Comment by cole10up** [comment]
### **QA ⚠️**

![Site Kit by Google Dashboard ‹ SupremeQA — WordPress (2)](https://user-images.githubusercontent.com/57115907/130726025-c0fc39fe-4536-49eb-93fd-da9236c4f577.gif)

Alright, tested again and I see the 'Next' button grayed out after the user selects too many options - that said, it's also grayed out when they select just 1 option. Is this expected @tofumatt ?

**Comment by felixarntz** [comment]
@aaemnnosttv Added the extra ACs here - note also the actual QA problem I noticed above.
