### ISSUE TITLE
Add support for additional survey question type "open_text"

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3762]
When the initial user feedback survey was introduced, scope of the MVP was limited to only support questions of the "rating" type, since that was the only one used for the initial survey. This should now be followed up on, with this issue focusing on the "open_text" question type.

![Screen Shot 2021-07-26 at 3 52 03 PM](https://user-images.githubusercontent.com/3531426/127069302-e22e2a37-7db0-4dc0-940b-b50cdd71f0dd.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `SurveyQuestionOpenText` JS component should be introduced and integrated into the user feedback survey JS infrastructure, rendering a survey question of type "open_text".
* The UI should look like the above screenshot and follow the "rating" question type where similar (e.g. font, spacing, G icon etc.).
* The available arguments to consider here from the Site Kit Service `/survey/trigger/` API response are as follows:
    * `question.question.subtitle` should, if present, be displayed right below the text input (see screenshot).
    * `question.question.placeholder` should, if present, be displayed as a text input placeholder (see screenshot).
    * The text input must be non-empty in order to proceed. The maximum character limit should be 100.
* The data object for answering the question (what needs to be passed to the `answerQuestion` function prop) should look as follows:
    * A single `answer` property with the string from the text input.
    * Example: `{ answer: 'My open text response' }`
* The new question type should have an example in Storybook where it can be inspected, similar to the existing "rating" type component.

#### Create new component

Create `assets/js/components/surveys/SurveyQuestionOpenText.js`

Base on SurveyQuestionRating.js
* wrap everything in a div with class `.googlesitekit-survey__open-text`
* Use `SurveyHeader` to match styling
* Use the `TextField`, `Input`, `HelperText` components
* Add the following string props and propTypes: `question`, `subtitle`, `placeholder`
* Add the following function props and propTypes: `answerQuestion`, `dismissSurvey`
* HelperText should be passed into `TextField`'s `helperText` prop (with the child `subtitle`)
* In order to limit user input to 100 characters, just disallow extra characters in the TextField's onChange handler (slicing the text to 100 characters)
* If the TextField is empty, set a disabled prop to true on the submit button
* When submitting, pass the answer to `answerQuestion` as per AC

In `assets/sass/components/surveys/_googlesitekit-surveys.scss`

* Add a new rule for `.googlesitekit-survey__open-text`
* Nest rules for `.googlesitekit-survey__body`, `.mdc-text-field`, and `.mdc-text-field-helper-line`
* Style now to match the design

#### Add new component to map on `assets/js/components/surveys/CurrentSurvey.js§

* `ComponentMap` also needs to map `open_text` to `SurveyQuestionOpenText`

:exclamation:  :exclamation:  **See PR here with everything done up until here** https://github.com/google/site-kit-wp/pull/3771 :exclamation:  :exclamation: 

#### Create new story

Create `assets/js/components/surveys/SurveyQuestionOpenText.stories.js` _(Based on SurveyQuestionRating.stories.js)_
* Create story showing SurveyQuestionOpenText with props and mock handlers to show it working

### Test Coverage
* Add new tests within `assets/js/components/surveys/CurrentSurvey.test.js` for the new question type.

We need to add this question type to the "main" test suite for `CurrentSurvey` to make sure the question type works as expected when "plugged in" to the rest of the survey components, next button, etc. 

### Visual Regression Changes

* No changes

## QA Brief

* Check that https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys--survey-question-open-text-story works and behaves as per AC
* Enter the code from https://pastebin.com/x0iiFBWh into your browser console on a Site Kit dashboard page to trigger a survey with a question from #3760, #3761, and this issue (#3762).

## Changelog entry

* Add an open text type to user surveys.

**Comment by danielgent** [comment]
This is what I've done with minimal changes to our existing components (looks similar to the design but definitely not identical)

![what done](https://user-images.githubusercontent.com/8496063/127309722-2359a2f1-6f5d-4051-a5d7-6287cc5f75e1.png)

Here you can see it working

https://google.github.io/site-kit-wp/storybook/pull/3771/?path=/story/components-surveys--survey-question-open-text-story

**Comment by eugene-manuilov** [comment]
@danielgent, please, add IB.

**Comment by danielgent** [comment]
I've had a go @eugene-manuilov.  :shrug: 

Seems less clear to me than just reading the actual code, so I'm not sure if I've done what's expected

**Comment by eugene-manuilov** [comment]
Thanks, @danielgent. It's better than just "merge my PR", but still requires a bit more infomration. Could you please add more details? When you write IB, think that you write it for someone who is not familiar with your PR, so once they read your IB they understand what needs to be done. When I read an instruction like `Use SurveyHeader to match styling`, it doesn't help me at all, it just adds more questions: `for which styles?`, `how should i use it?`, `where should i use it?`, etc. The same applies to other instructions.

One more thing that is missing in IB is how the new question component should be added to the `CurrentSurvey` component. Which modifications need to be done there and in the `SurveyQuestionRating` component.

**Comment by danielgent** [comment]
@eugene-manuilov I don't see the AC telling me to touch the `CurrentSurvey` component, especially if the `SurveyQuestionRating` requires modifying as we have a few similar new components

I'm going to put changes to this IB on hold for now. The whole diff of the working PR is only about 100 actual lines of code, of that most, is copy-pasted.

**Comment by eugene-manuilov** [comment]
> I don't see the AC telling me to touch the `CurrentSurvey` component, especially if the `SurveyQuestionRating` requires modifying as we have a few similar new components

@danielgent it assumes to do it. The `Add support for additional survey question type ...` title means that that additional question type should be supported by the survey infrastructure, correct? We don't have a separate ticket that will ask us to update the `CurrentSurvey` component to use the new `SurveyQuestionOpenText` component.

**Comment by aaemnnosttv** [comment]
Thanks @danielgent – you're right that the ACs don't mention changing the `CurrentSurvey` component, but @eugene-manuilov is also right that there is a very simple change needed there in the `ComponentMap` (outside of the component) which maps each question type to the component type that doesn't make sense to do in a separate issue, which I see you've done in your PR 👍 

I think the IB is mostly good to go here with one important caveat and that is the absence of test coverage which is often not explicitly called for in the ACs. As mentioned on https://github.com/google/site-kit-wp/issues/3760#issuecomment-891786138 we want to make sure each question type is added to the "main" test suite for surveys which are the tests for `CurrentSurvey` to make sure the question type works as expected particularly when "plugged in" to the rest of the survey components, next button, etc. This is the important part to add. Optionally, more tests could be added for the component itself in a separate file for the component as we normally would but perhaps that's not really needed in addition to the others for such a simple input here. This will of course increase the estimate a bit but that's to be expected.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by danielgent** [comment]
I've added a test for this question type to `CurrentSurvey.test.js`

This wasn't mentioned in the IB though so I don't think it's been thought through :thinking: 

In order for the test to pass, it requires changes to the `CurrentSurvey` component, as `SurveyQuestionOpenText` requires different props, and `CurrentSurvey` needs to pass these in.

I'll just make these changes in anyway and then after we can discuss the best way

**Comment by danielgent** [comment]
Assigning back to you @tofumatt for another round of CR (I have some questions)

I also did 3761 and 3760 and they're very similar so
1. I'm going to assign them to you (hope you don't mind)
1. I'm going to do similar changes to the tests (break them up, turn the comments into full sentences) :+1:

**Comment by tofumatt** [comment]
@danielgent That sounds good on both accounts, thanks! 🥳

**Comment by danielgent** [comment]
PR feedback done but due to the overlap in CR with 3761 and 3760, I'll wait until putting this to CR again

**Comment by danielgent** [comment]
@tofumatt  Assigning back to you for CR! Hopefully, I've done all the required changes here from the other PRs :crossed_fingers:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@danielgent @tofumatt  The styling does not appear the same as [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys--survey-question-open-text-story). 

This is based on my test site using the code.  Screenshots on [Desktop](https://user-images.githubusercontent.com/73545194/129743116-da38fac8-86a4-445e-b998-ece1961e8ff8.png) and [Mobile](https://user-images.githubusercontent.com/73545194/129744257-19652ed1-eb9b-4ad9-abd4-d9b818e190b7.png)

An additional observation on Storybook is that the `Submit` button has too much padding around it, in my opinion.

**Comment by felixarntz** [comment]
@danielgent Just wanted to check: Have you been possibly making some test requests to the API while working on this? We've been seeing some very sparse errors in our service related to the `/survey/event/` route which only occurred about 10 times within 1 hour yesterday and again about 10 times within 1 hour earlier today (both around 7am Pacific time), so it strongly suggests this is some weird edge-case that could come from ourselves doing some testing.

Could there be a problem that Storybook somehow attempts to make a request? @wpdarren Have you clicked on some of the buttons while testing Storybook?

This is of course not a big deal, and it's mostly something where we have to fix our service code to be more defensive. I'm mostly trying to figure out where these errors are coming from. Passing random data to the API during testing might explain it.

cc @aaemnnosttv

**Comment by danielgent** [comment]
@felixarntz  I'm going to presume that is from @wpdarren testing with some code that @tofumatt wrote  :smile: 

See https://pastebin.com/qCtDMYuD

I was just about to do this to finish this ticket (there's no way I can do the styling fixes without seeing it actually on WordPress), but I'll leave this for now if it's affecting actual production data!  :sweat_smile:

**Comment by tofumatt** [comment]
@felixarntz Yeah that was actually myself and @wpdarren; as mentioned Darren wanted to QA the components on the site, so I used this code: https://pastebin.com/x0iiFBWh to get a survey to appear on the site.

I assumed it would not accept a non-real survey—which I suppose is the case but it caused the errors. At any rate, those requests are definitely intended and not a result of a weird bug/edge-case in the client code. They aren't from storybook, though I think I lazily re-used the survey ID from Storybook so they might _look_ like it. But we've been using Storybook for awhile and not seen these errors, so if they just started this week it makes sense that it's the pastebin I posted.

Sorry about that!

Are we fine to continue making requests for non-real survey IDs? Or should we stop until the API in patched?

**Comment by felixarntz** [comment]
@tofumatt Thanks for clarifying! No worries, it's totally okay to continue to test with fake surveys, it was mostly important for me to figure out whether it was caused by our own testing (vs something in the plugin being recently broken) 👍 

We'll still fix the internal error in the API of course, but it's not critical other than affecting those individual requests.

**Comment by danielgent** [comment]
@wpdarren  I've just used this JS to create a survey with an open text question
https://pastebin.com/GnK0GBUZ


But for me it looks pretty much like it does on storybook!

![looks like on storybook](https://user-images.githubusercontent.com/8496063/129942652-b1c62280-fe53-44df-9d7d-894f1beadd06.png)

On the screenshot on your comment it looked very broken with the padding all wrong. I can't replicate that! :grimacing:

**Comment by wpdarren** [comment]
@danielgent sure, I will take another look at this.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@felixarntz @tofumatt since Daniel has departed, I still have two observations that I would like to raise. 

1) On the [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys--survey-question-open-text-story) within the QAB, the padding between the input field and submit button seems too big.  I have cleared cache and viewing it in Chrome.  This is on desktop and mobile. When I also used the pastebin code on my test site, the same padding issue occurs, so think we need to look at the styling What are your thoughts? 

![image](https://user-images.githubusercontent.com/73545194/130249833-4e83374d-4597-4982-9d95-72a7111f7570.png) 

2) The placeholder text in the input field is different to Storybook. Is that just the pastebin code that's causing that?  I am assuming it is but would like to check. 

![image](https://user-images.githubusercontent.com/73545194/130250917-00f0fed9-ffd5-448b-82ac-f9cb95994922.png)

**Comment by aaemnnosttv** [comment]
Currently outputting an empty helper text div when there is no text.

![image](https://user-images.githubusercontent.com/1621608/130485111-141a3b94-f232-4478-8b4a-f76255f23db9.png)

**Comment by aaemnnosttv** [comment]
Ready for another pass @wpdarren 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified**

- Verified that the open text form appears and is displayed as per AC. 
- Checked that [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys--survey-question-open-text-story) works and behaves as per AC

![image](https://user-images.githubusercontent.com/73545194/130786963-457ddb2b-c7b3-4fd3-8647-e4ae9b9eddda.png)

**Comment by felixarntz** [comment]
### Approval ❌ 

Similar to https://github.com/google/site-kit-wp/issues/3761#issuecomment-905583299, the implementation here does not match the ACs, as it is relying on `question.subtitle` and `question.placeholder` instead of `question.question.subtitle` and `question.question.placeholder`.

The overall question schema is _always_ only including the `question_ordinal`, `question_text`, `question_type` and `question` fields. Any question type-specific fields are always nested within the last field, i.e. in `question.question`.

cc @tofumatt @aaemnnosttv
