### ISSUE TITLE
Don't use "Connected" as "alt" text for icons

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3763]
## Bug Description

There are three sections in the app where we erroneously add "Connected" inside an icon, next to text that already tells the user something (Site Kit, a module, etc.) is connected. This means a screen reader will read aloud "Connected Connected" or "Site Kit is connected Connected", which is bad UX.

We can remove a few instances of `__( 'Connected', 'google-site-kit' )` to fix this.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Assistive technology should not read "Connected connected" or "Site Kit is connected Connected".
* Icons, in general, should not have alt text if they are for visual effect and the status is already communicated via text.

## Implementation Brief

* Remove https://github.com/google/site-kit-wp/blob/fadab7cf0f3b424e33f86c96416d1bf37c7ca637/assets/js/components/ModulesList.js#L120-L122
* Remove https://github.com/google/site-kit-wp/blob/fadab7cf0f3b424e33f86c96416d1bf37c7ca637/assets/js/components/settings/SettingsAdmin.js#L155-L157
* Remove `VisuallyHidden` import from each file.

### Test Coverage

* No tests needed.

### Visual Regression Changes

* No VRTs should change as these are visually hidden elements.

## QA Brief

**ModulesList change**

* After setting up one of the core modules you will be sent back to the dashboard
* Inspect green check icons inside _Congrats on completing the setup for Analytics!_ section
* Inspect DOM (or use screen reader).  Connected should only appear once

**SettingsAdmin change**

* Go to Admin Settings page http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-settings#/admin-settings
* Inspect green check icon in Plugin Status section
* Inspect DOM (or use screen reader).  Connected should only appear once

### ModulesList changes

**before**

![ModulesList-before](https://user-images.githubusercontent.com/8496063/127737231-c9d54980-285f-4216-8b6b-adb0dc6eb563.png)

**after**

![ModulesList-after](https://user-images.githubusercontent.com/8496063/127737234-3ced7f7e-db79-4d6b-bb1d-574a3f5e1fcf.png)

### SettingsAdmin changes

**before**

![SettingsAdmin-before](https://user-images.githubusercontent.com/8496063/127737240-f4359d66-82c9-4765-9c80-720089aab22b.png)

**after**

![SettingsAdmin-after](https://user-images.githubusercontent.com/8496063/127737241-4ce651f1-3cc3-4431-862a-70d97383a5d1.png)

## Changelog entry

* Fix "Connected" messages to avoid duplicate words for screen reader

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

ModulesList change

When inspecting DOM, connected only appears once. 

![image](https://user-images.githubusercontent.com/73545194/132509934-f428dfd1-781a-4735-8b14-86cec960a820.png)

SettingsAdmin change

When inspecting DOM, connected only appears once.

![image](https://user-images.githubusercontent.com/73545194/132509976-fa187946-c11e-4309-8f36-6971fb74dd21.png)
