### ISSUE TITLE
Idea Hub post idea selectors invoke duplicate fetch requests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3772]
## Bug Description

Idea Hub's selectors for post ideas (new / saved / draft post) all have a similar implementation which results in multiple fetch requests for the same selector. This is primarily due to the way resolvers work in `@wordpress/data`. For selectors with a resolver, the resolver will always be invoked once per unique list of arguments the selector is called with. The uniqueness of the arguments is similar to the checking of dependencies with React hooks such as `useMemo`.

The problem is that the same selector is used with different arguments which don't influence the request that is made. The arguments currently only allow for slicing the result to return a subset (also a bit of a problem since this will return a new array every time).

E.g. https://github.com/google/site-kit-wp/blob/3db19cbeca41145aefc6c6c3383ee9b66e8b4121/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/DraftIdeas.js#L48-L53

Here draft post ideas are selected (all) first with no arguments to get the total number. This will result in the resolver being invoked and a fetch because they are not loaded yet. In the resolver, the `options` argument defaults to an empty object which is of course a new/different object every time. This is then passed to the internal selection of its own selector with `options` which then results in yet another invocation of the same resolver and fetch. https://github.com/google/site-kit-wp/blob/3db19cbeca41145aefc6c6c3383ee9b66e8b4121/assets/js/modules/idea-hub/datastore/draft-post-ideas.js#L45-L47

On the next line, it selects them again, this time using the slicing `args` based on the current page. This will invoke the resolver again, and as long as there are no draft post ideas in state, dispatch another fetch request (even if one or more are already in progress). For draft post ideas in particular, this happens on every page load where they're selected because the fetch does not use cache at the API layer. The resolvers for new and saved ideas have the same problem, but this isn't obvious once the response is cached, but the resolvers and fetch _attempts_ are still being invoked (see below).

If we want to keep slice arguments as part of the signature of the selectors, we should probably move the "get all" selection with the resolver to a new selector with no arguments. That way the slicing selectors would always select this without invoking additional resolver calls because it would never be called with any other parameters (since they aren't relevant to the request anyways). Alternatively, we could change the selectors to essentially be the "get all" selectors and leave the slicing to happen in the component/consumer.

**Beyond Idea Hub**

There's one more detail here which seems to be relevant to other selectors that use an object as the main argument (such as `getReport`). I haven't observed these resulting in duplicate fetches, but the potential for the same problem seems to exist. We should probably modify `createFetchStore` internals to prevent identical requests from being made at the same time (e.g. while `! isFetching(args)`) as I can't think of a case where we would want to allow that. Perhaps we could even emit a warning when this happens to better surface these in the future.

## Steps to reproduce

1. Set up Idea Hub
2. Observe network requests
3. Visit Site Kit dashboard
4. See duplicate requests
	- Requests for new and saved ideas are now cached
	- Reload the page and see duplicate requests again for draft post ideas (always uncached)

## Screenshots

**Initial page load, no Idea Hub requests cached**
![image](https://user-images.githubusercontent.com/1621608/127279458-98107758-5c82-4013-ba6c-1c361fd77d9d.png)

**Repeat page load, once cached**
![image](https://user-images.githubusercontent.com/1621608/127283005-a75639ed-ec76-4444-bbc7-791e526f635e.png)
Note resolvers and fetch requests are repeatedly invoked, even though they don't result in network requests

![image](https://user-images.githubusercontent.com/1621608/127282539-e96ab62d-0316-4080-84bd-0f306861ce21.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
@aaemnnosttv this is already addressed in #3681.

**Comment by felixarntz** [comment]
Closing as discussed earlier, since it's already covered by #3681.
