### ISSUE TITLE
Remove ga4setup feature flag

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3775]
## Feature Description

The GA4 support has been rolled out a few releases before but the `ga4setup` feature flag is still used across our codebase. While this is not a big deal, we need to remove it from our codebase and make a functionality that has been hidden by that feature flag work unconditionally.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ga4setup` feature flag should be removed
* All code that has been activated when the `ga4setup` feature flag is enabled should work unconditionally now.
* All code that has been deactivated when the `ga4setup` feature flag is enabled should be removed.

## Implementation Brief
* Update `feature-flags.json` to remove `ga4setup`
* Search for the `ga4setup` string within the code base and review code where the `ga4setup` is present. Any logic/component which was rendered conditionally when the `ga4setup` feature was enabled should be rendered unconditionally now. Any code which was rendered when the feature flag was disabled should be removed.
* Use of the `useFeature` hook with `ga4setup` as a parameter should be removed.
* Stories using the `ga4setup` feature flag should be updated as well to no longer rely on it.
* Changes should apply to PHP files as well. For e.g `includes/Core/Modules/Modules.php` where the `Analytics_4` should be loaded unconditionally.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Check code changes are done as per AC
    * Pay attention to user-facing code behind or in front of flags
* Check all tests are passing
* Check modified stories are not broken
_Note "Analytics Module/Settings" are already crashing on develop:_ https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-settings--no-tag-gtm-property-w-access

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by danielgent** [comment]
I think this could well go over 7 hours.  I've only removed the flag from a few files and there are so many failing tests.  **Lots** of endpoints need mocking, many of which haven't been done before (so may involve manual inspection of endpoints)

**Comment by danielgent** [comment]
Got to the point where there are a few failing tests and e2es. 3hrs 40 mins spent so far. I can pick this up at a later date

**Comment by danielgent** [comment]
I've spent more time and fixed a few of the react-testing-library tests. I'm not sure I've made any progress with the e2e tests. Probably better if I leave them to someone with more experience with Puppeteer and the codebase. :smile:

**Comment by danielgent** [comment]
@tofumatt So far you've fixed every e2e failing test I've had  :smile: 

I've got all the react-testing-library tests passing but I've been unsuccessful in getting all the e2e tests to pass.

The errors I get are odd and I'm not that great with Puppeteer. I  find it much harder to know what has happened than, say, Cypress. That combined with my lack of knowledge of the project means I'm wasting time so I'll stop now. :+1: 

The rest of the task is done though IMHO :smile:

**Comment by asvinb** [comment]
### QA: ✅ 
* `ga4setup` not found in codebase
* tests passing
* Storybook stories all load fine.
