### ISSUE TITLE
Unable to complete installation for Site Kit in my WordPress Site. Got The session state (799664078) didn't match the state parameter ()

### ISSUE THREAD

**Issue by olaniyimoses** [google/site-kit-wp#3778]
Please, I need help. I followed the instruction on the documentation website to install Site Kit. But when I got to Congratulation page, clicking on "Go to my Dashboard", takes me to error page showing "The session state (799664078) didn't match the state parameter ()".

I used incognito browsing windows and also disable my firewall and antivirus on my system.

Please, what should I do to resolve this problem? 

![Screenshot 2021-07-29 084309](https://user-images.githubusercontent.com/5338692/127452329-bed96eb0-412a-41b7-b7ca-dabe93c7b32d.png)

**Comment by jamesozzie** [comment]
Thanks for reaching out. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on the WordPress support forums where we perform initial troubleshooting for such queries we'd be happy to assist. 

Please include as much relevant information to your support topic as needed to assist with this issue, including any console errors on the same screen with this notice and whether you've been able to setup Site Kit on this site or another site on the same hosting platform previously. You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.  

I can keep this GitHub issue open in the meantime, should we determine any changes or fixes to be applied on the plugin side. Note that in a previous case there did seem to be a third party plugin or theme conflict likely responsible [for one user](https://wordpress.org/support/topic/the-session-state-didnt-match-the-state-parameter-2/) who encounter the same issue. I can provide you with some steps for checking this within your topic once created.

**Comment by bethanylang** [comment]
Closing this issue. @olaniyimoses If you still need assistance, please <a href="https://wordpress.org/support/plugin/google-site-kit/#new-post">create a new support topic</a> on our forum. Thank you!
