### ISSUE TITLE
Tooltips overlapped when clicked on Analytics stats while hovering to nearby stats in the graph

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3779]
## Bug Description
On the Analytics Dashboard tooltips overlapped while we clicked on the data point & then hover on the nearby stats.

## Steps to reproduce

1. Go to Analytics Dashboard
2. Click on any point on the graph to see stats
3. Hover on the nearby stats
4. You'll see both tooltips will be overlapped.

## Screenshots
Please see [this](https://www.loom.com/share/cf13fd972ad243f7be87b97921bd6123) for further clarification.

## Additional Context

 - PHP Version: 
 - Browser [Chrome 92.0.4515.107, Microsoft Edge 92.0.902.55]
 - Plugin Version [1.37.0]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by abdullah1908** [comment]
Check with @cole10up as well.

**Comment by aaemnnosttv** [comment]
Closing this one for now.
