### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by ChetnaC11** [google/site-kit-wp#378]
## Bug Description
Warning: require_once(/home/thougjz8/workoutwithcbd.com/wp-content/plugins/site-kit-wp-develop/vendor/autoload.php): failed to open stream: No such file or directory in /home/thougjz8/workoutwithcbd.com/wp-content/plugins/site-kit-wp-develop/includes/loader.php on line 18

My website is on WordPress https://workoutwithcbd.com/

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Hi there

It looks like you cloned this GitHub repository for development purposes.

If you do that, you need to **build** the actual plugin by following the steps over at https://github.com/google/site-kit-wp/wiki/Engineering, most notably `composer install`, `npm install`, and `npm run build`.

In case you don't want to contribute to the plugin and just give it a test, I recommend installing the current developer preview from https://sitekit.withgoogle.com/news/site-kit-developer-preview/ instead (see download link at the bottom).
