### ISSUE TITLE
UI issue on Average Position tab on Search Console module

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3780]
## Bug Description

On the `Search Console` module page, when you click on the `Average Position` tab, a black horizontal line appears, which is different than the other tabs.  See screencast below:

https://user-images.githubusercontent.com/73545194/127673006-f8e1aa9a-9299-475f-8900-bfe9fb24bf83.mp4

This was an issue on 1.37.0, so not a regression. I was able to recreate this on Chrome and Safari browser. 

## Steps to reproduce

1. Connect Site Kit with a test site that has Search console data. 
2. Go to the Search console module page
3. Click the `Average Position` tab
4. See UI issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren after taking a closer look, this was intentionally changed in https://github.com/google/site-kit-wp/issues/874 to mirror the same chart in Search Console. The gray line you're seeing is the zero-line that is present on all charts, it's just that this one is inverted 😄
