### ISSUE TITLE
Introduced new AdSense Code to Improve the Ad performance

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3783]
## Feature Description
Google AdSense recently introduced the [new AdSense snippet schema to improve the Ad performance](https://support.google.com/adsense/answer/10627874?hl=en). A user on the [support forum](https://wordpress.org/support/topic/new-adsense-code-to-improve-ad-performance/) also reported this.

Auto ads code example:
```
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1234" crossorigin="anonymous"</script>
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The web tag for AdSense should be updated accordingly:
	* The script `src` should include a new `client={publisher-id}` query parameter
	* The script tag should receive an added `crossorigin="anonymous"` attribute

## Implementation Brief
* Using `includes/Modules/AdSense/Web_Tag.php`
	* Update the `render` method to add the `client` URL parameter having `$this->tag_id` as value and add the `crossorigin="anonymous"` attribute to the script tag.

### Test Coverage
* No new tests to be added

### Visual Regression Changes
* N/A

## QA Brief

* Enable AdSense on a site and ensure it is placing the AdSense tag for you.
* Check the source code for new markup (ctrl+u, ctrl+f and search for ''adsbygoogle.js?client=")

## Changelog entry

* Update AdSense tag code to improve Ad performance.

**Comment by jamesozzie** [comment]
Legacy Auto ads code snippet code as provided from AdSense UI ([screenshot](https://i.imgur.com/F8nV5SU.png)):

```
`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
   "google_ad_client":"ca-pub-3467161889682403",
   "enable_page_level_ads":true
  });
</script>`
```

New Auto ads code snippet code as provided from AdSense UI ([screenshot](https://i.imgur.com/0wr49Pe.png)):

```
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3467161889682403"
     crossorigin="anonymous"></script>
```

**Comment by eugene-manuilov** [comment]
> Remove the second script tag which contains JSON encoded values.

@asvinb why do we need to remove the second script tag with JSON encoded data? It contains important configurations for ads and can be used/extended by 3rd party developers via the `googlesitekit_auto_ads_opt` filter. I think we can't delete it, can we?

**Comment by eugene-manuilov** [comment]
> Remove google_ad_client from the second script tag which contains JSON encoded values.

@asvinb AC doesn't ask us to remove something. Why do we need to delete it?

**Comment by asvinb** [comment]
That's a good question @eugene-manuilov and that raises another question about your previous comment https://github.com/google/site-kit-wp/issues/3783#issuecomment-896137586
If you look at what @jamesozzie posted here: https://github.com/google/site-kit-wp/issues/3783#issuecomment-891160237, you'll notice how the snippets differ. True the AC does not say we need to remove the values but it does not say we should keep them 😅  For e.g `google_ad_client` is now passed as the `client` URL parameter. Maybe we need to check the documentation to know more whether we should keep the JSON encoded values or not. 
What do you think?

**Comment by eugene-manuilov** [comment]
@asvinb to me it seems like we just need to add `?client=ca-pub-...` parameter to the src URL and `crossorigin="anonymous"` attribute to the script tag itself. Everything else should remain the same.

**Comment by asvinb** [comment]
@eugene-manuilov Over to you for final review.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by kuasha420** [comment]
Doesn't it need to get merged before going to QA? @tofumatt

**Comment by tofumatt** [comment]
@kuasha420 Indeed, I clicked merge but I guess it didn't take 😓 

Merged now, thanks! 😅

**Comment by kuasha420** [comment]
@tofumatt Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that when AdSense is activated, the tag is placed for you. 
- Verified the source code has the new markup `adsbygoogle.js?client=`
- Verified the source code also includes the `crossorigin="anonymous"` attribute.

![image](https://user-images.githubusercontent.com/73545194/131539719-71cd191c-e22e-492e-acf6-be3936826d83.png)
