### ISSUE TITLE
Some Google charts not displaying properly on Safari

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3784]
## Bug Description

A few Google charts in Site Kit currently aren't displaying properly due to dates being parsed differently in a few places. In particular, this has been identified to affect the charts on the module dashboards for Search Console (visible chart error) and AdSense (flat-line chart).

## Steps to reproduce

Both are easily visible in the latest version of Safari by connecting the module and visiting the module's dashboard page as long as there's data.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/127691958-0b03d0e3-6d33-472a-bcfb-1e3d6da901be.png)

![image](https://user-images.githubusercontent.com/1621608/127691966-b58600f6-d6d7-4a4a-b402-de7d1c2d8357.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Charts work consistently across all major browsers 

## Implementation Brief

* Extract a new `stringToDate` utility function to replace the problematic existing functions by the same name in `getSiteStatsDataForGoogleChart` functions
* Merge https://github.com/google/site-kit-wp/pull/3785

### Test Coverage

* Add tests for the new utility

### Visual Regression Changes

* No changes expected as the issue is browser specific

## QA Brief

* This issue fixed issues with charts on Search Console and AdSense module pages with Safari but it's worth double-checking all Google charts with Safari to make sure nothing was missed.
* Ensure you're testing using a site that has data for the service/chart
* The errors fixed are not big/fatal errors but charts not working properly (see screenshots above)

## Changelog entry

* Fix possible JavaScript error related to certain Google charts not rendering properly in Safari.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
In the interest of time, this has already been QAd ahead of merging, see https://github.com/google/site-kit-wp/pull/3785#issuecomment-891191976. Therefore skipping the formal column this time.
