### ISSUE TITLE
Allow WP "Editor" roles access to configure Analytics or provide a custom programmatic capability for Analytics edit access

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3791]
## Feature Description

As per [one request in the support forums](https://wordpress.org/support/topic/feature-request-give-editor-access/#post-14716534) one user would like the ability for "Editor" roles to be able to configure Analytics or alternatively for a filter or capability that developers can use to permit access to other roles. 

In this users case they are a web developer setting up Analytics for clients. They are aware of the pending dashboard sharing feature (#6) although they would like to extend Analytics configuration for "Editor" roles (or via any additional filter or capability)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@aaemnnosttv Currently granting access to the `manage_options` capability for the Editor role will show the Site Kit menu item and allow the user to authenticate and login to the dashboard. Adding the other base capabilities does not allow the user to view the dashboard.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – in this case I think the intention is probably to be able to view the dashboard as well. This requires another capability but all of this is possible without granting core capabilities. Closing this out as this is an advanced scenario but rather straight forward for power users who are familiar working with custom capabilities.
