### ISSUE TITLE
Add source maps to production scripts

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3797]
## Feature Description

When an error happens for our users and they create a ticket with information from the browser console log, it can be very hard to figure out what is going on there because the source code is minified (see #3706 and #3618). In order to make it a bit easier for us, we can add source maps to our production scripts. It will give us additional information that can help us to faster find the roots of the issue.

Webpack has special recommendations regarding how we can use source maps in production. We need to research whether we can use it or not. https://v4.webpack.js.org/configuration/devtool/#production

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@eugene-manuilov will this work for error reporting automatically? Looking over the docs for devtool, it seems like the source maps are only loaded on demand by devtools – I'm not sure it would add additional information to error traces in the browser if the console wasn't open, does it?

**Comment by eugene-manuilov** [comment]
Hm... looks like you are right... Okay, then this ticket is useless... Closing it.
