### ISSUE TITLE
Site Kit Requires WordPress Core

### ISSUE THREAD

**Issue by ataylorme** [google/site-kit-wp#38]
**Describe the bug**
The [`composer.json` of Site Kit requires `johnpbloch/wordpress-core`](https://github.com/google/site-kit-wp/blob/9a262cd18c33995ce5ec81bc300ff055dff2a153/composer.json#L19). When installing WordPress core from another source this causes an unwanted copy of WordPress core to be downloaded. 

Specifically, I use [`pantheon-systems/wordpress-composer`](https://github.com/pantheon-systems/wordpress-composer) as the source for WordPress core and install it to the path `web/wp`. 

Because Site Kit requires `johnpbloch/wordpress-core` another copy of WordPress core, which I do not want as a dependency, is installed to the `wordpress` directory.

I cannot find a way to _not_ have the `johnpbloch/wordpress-core` version of WordPress core downloaded.

**To Reproduce**
1. Clone [pantheon-systems/example-wordpress-composer](https://github.com/pantheon-systems/example-wordpress-composer/)
2. Add an entry for the Google Site Kit plugin in the `repositories` section of `composer.json`
	```json
	{
      "type": "vcs",
      "url": "https://github.com/pantheon-systems/wordpress-composer"
    }
	```
3. Add an entry for the Google Site Kit plugin in the `require` section of `composer.json`
	```json
	"google/google-site-kit": "1.0.0-beta.1"
	```
4. Run `composer update`
5. Verify that the Pantheon copy of WordPress core is installed to `web/wp` as wanted
6. See that an unwanted copy of WordPress core is downloaded to the `wordpress` directory

**Expected behavior**
Site Kit, a WordPress plugin, does not force a specific version of WordPress core on Composer based projects that require the plugin as a dependency.

**Screenshots**

**System Information (please complete the following information):**
 - PHP Version: `7.3`
 - OS: macOS Mojave `10.14.5`
 - Browser: N/A
 - Plugin Version: `beta1`
 - Device: Macbook Pro

**Additional context**

**Comment by ivankristianto** [comment]
Thanks @ataylorme 
That wordpress-core package is needed for unit testing.
So i think we can move it to `required-dev` only.
