### ISSUE TITLE
Scaffold SwG module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3808]
This is a tracking issue for scaffolding out the SwG module foundation - essentially putting together all the "uncontroversial" pieces about adding a new module which don't require much further design consideration since they rely on established infrastructure.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new module `subscribe-with-google`.
* It should be entirely hidden behind an `swgModule` feature flag.
* The module info should be as follows:
    * Title: _Subscribe with Google_
    * Description: _Generate revenue through your content by adding subscriptions or contributions to your publication_
    * Order: _7_
    * Homepage: _https://publishercenter.google.com/_
* It should have a settings implementation with ownership concept and the following settings:
    * `publicationID`: The publication ID to use.
    * `products`: The list of products available.
    * Both of these settings should affect module ownership.
* It should come with a JS file `assets/js/googlesitekit-modules-subscribe-with-google.js` which registers the module and its datastore in JS.
    * The datastore should for now be just a base module store with support for the two settings.

## Implementation Brief

* Complete #3120.
* Specifically, introduce the `swgModule` feature flag and make sure the module is only loaded when that feature flag is enabled.

### Test Coverage

* Add test coverage for the module class and dynamic JS components.
* Add Storybook coverage for the module setup UI and the module settings panel.

### Visual Regression Changes

* N/A

## QA Brief

* Enable the `swgModule` feature flag with the tester plugin
* Click "Set up Subscribe with Google" on the Settings > Connect More Services page
* Fill out the form, then click "Configure Subscribe with Google"
  * The Publication ID field expects a domain, such as `example.com`
  * The Products field expects a list of product names, one per line
  * You should see a congratulations message after submitting the form
* Edit the Subscribe with Google plugin's settings
  * You should be able to update the Publication ID and Products fields

## Changelog entry

* Scaffold Subscribe with Google module.

**Comment by felixarntz** [comment]
@eclarke1 @fhollis Opened this as a tracking issue for the already long-existing PR #3120 that @ChrisAntaki has been working on. I've also defined an SwG epic and label which we can use for other following issues going forward.

As discussed, this issue is something we can merge without having a design doc, since the work is architecturally similar to what Site Kit already has in other modules.

**Comment by cole10up** [comment]
### **QA ❌**

**Tested**

Confirmed feature flag
![image](https://user-images.githubusercontent.com/57115907/133003514-f1c719a2-970d-43ab-8fd5-7fa2ed10e18d.png)

Confirmed module is available in settings
![image](https://user-images.githubusercontent.com/57115907/133003548-aa16409f-c195-4384-9ba4-0f12961d26a1.png)

![image](https://user-images.githubusercontent.com/57115907/133003577-b668f0ae-74ac-4da5-bd96-60db26af8e64.png)

Confirmed the form is displayed:
![image](https://user-images.githubusercontent.com/57115907/133003559-7811a9c8-070a-4dc7-bd39-ed46db48a09c.png)

Confirmed removal of the module functions:
![image](https://user-images.githubusercontent.com/57115907/133003594-5250c2d1-3eb1-4bc0-af38-4d090edc8a1c.png)

**Noticed the following:**
User is able to submit the form without a domain as the Publication ID
![image](https://user-images.githubusercontent.com/57115907/133003650-635664ac-ad72-4c53-acdd-5a5637de936e.png)

Submitting a Publication ID with a capital letter throws a red box, no error message
![image](https://user-images.githubusercontent.com/57115907/133003725-f9317ac9-54de-4799-869f-045291fe3b45.png)

After the initial submission I saw this message:
![image](https://user-images.githubusercontent.com/57115907/133003734-55766e16-c494-4153-9a35-ac827d7e3531.png)

Console:
![image](https://user-images.githubusercontent.com/57115907/133003742-2031374d-f357-4a41-aef3-18d0ce8997b4.png)

@felixarntz see the above, sending back to Execution

**Comment by felixarntz** [comment]
@ChrisAntaki One of the QA findings above may be worth addressing:
> User is able to submit the form without a domain as the Publication ID

Maybe we can refine the validation function to do at least some rudimentary check that the input looks like a domain? I guess eventually it will be less crucial when the values come from the API, but checking that it is a domain IMO makes sense even to validate that data. What do you think?

@aaemnnosttv Is there something wrong with `develop` right now?
> After the initial submission I saw this message:
> ![image](https://user-images.githubusercontent.com/57115907/133003734-55766e16-c494-4153-9a35-ac827d7e3531.png)

The `DashboardSearchVisitorsWidget` isn't related to the changes here, so I wonder if this got broken elsewhere.

**Comment by felixarntz** [comment]
@cole10up Can you test the setup submission itself again using latest `develop`? The JS error specifically that you got above looks like was already caught in https://github.com/google/site-kit-wp/issues/3880#issuecomment-915795599 and should now be fixed.

**Comment by ChrisAntaki** [comment]
Publication IDs like `CAowz7enCw` are valid too

**Comment by ChrisAntaki** [comment]
Hey @cole10up ! I'll create a new Issue for improving the validation

**Comment by cole10up** [comment]
Thanks @ChrisAntaki!

@felixarntz, I ran another test with the latest develop and I see the Dashboard Visitor Widget error again. I can follow up on a separate ticket for this issue. Otherwise I think it's safe to push this to approval.

![Site Kit by Google Settings ‹ SupremeQA — WordPress (1)](https://user-images.githubusercontent.com/57115907/133135137-270beced-8a7d-415c-ab80-1fd845816384.gif)

**Comment by ChrisAntaki** [comment]
Hey @cole10up , here's the issue for improving the validation #4025
