### ISSUE TITLE
New Ad Code > crossorigin=”anonymous”

### ISSUE THREAD

**Issue by casacochecurro** [google/site-kit-wp#3812]
## Feature Description

There is a new JS Ad Code for Ads as this post details: 

https://support.google.com/adsense/answer/10627874

In webs with Site Kit the plugin controls this JS.

Is there any plugin update or documentation to choose the JS code with the new code?

Thanks
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by abdullah1908** [comment]
@casacochecurro thanks for submitting the issue. We are closing this as the same [issue](https://github.com/google/site-kit-wp/issues/3783) is already existed. Please subscribe for updates.
