### ISSUE TITLE
Implement GA events for Idea Hub module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3817]
Related to #3524 and #3625, which via feature tours introduce the first couple Idea Hub-focused GA events, this issue is about introducing various other GA events for capturing user interactions with the Idea Hub module and its features.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The event category for the main feature tour introduced in #3524 should be updated to `idea_hub_widget`.
* The following other Idea Hub widget events should be tracked using event category `idea_hub_widget`:
    * prompt_widget_view: User sees CTA widget (i.e. on scroll into view, like with PSI widget)
    * prompt_widget_setup: User clicks CTA button in CTA widget
    * prompt_widget_dismiss: User dismisses CTA widget
    * widget_view: User sees regular (non-CTA) Idea Hub widget, in any state (on scroll into view, like with PSI widget); this should always be followed by one of the following two events
        * widget_gathering_data_view: User sees version of the Idea Hub widget with zero data entirely (i.e. no new ideas, no ideas saved, no drafts; also on scroll into view, like with PSI widget)
        * default_tab_view: User sees Idea Hub widget with a certain initial tab open (this is the counterpart to the above "widget_gathering_data_view"); the event label should be accordingly either "new-ideas", "saved-ideas", or "draft-ideas"
    * tab_select: User clicks to select another tab; the event label should be accordingly either "new-ideas", "saved-ideas", or "draft-ideas"
    * start_draft: User clicks button to start an idea draft
    * view_draft: User clicks the link/button to view an existing idea draft
    * save_idea: User clicks the button to save an idea
    * unsave_idea: User clicks the button to unsave an idea
    * dismiss_idea: User clicks the button to dismiss an idea
    * click_outgoing_link: User clicks learn more link in Idea Hub widget; the event label should be (always) "idea_hub_learn_more"
* The following events should be tracked using event category `idea_hub_dashboard`:
    * prompt_notification_view: User sees Idea Hub CTA notification in the Site Kit dashboard
    * prompt_notification_setup: User clicks to activate Idea Hub module via the prompt notification
    * prompt_notification_dismiss: User dismisses the prompt notification
* The following events (other than the feature tour ones from #3625) should be tracked using event category `idea_hub_posts`:
    * savedposts_notification_view: User sees the "saved ideas" notification on the WP Admin posts screen (can be tracked "on page load" _if_ the notification is present, i.e. no on-scroll necessary)
    * savedposts_notification_complete: User clicks the link in the above notification
    * savedposts_notification_dismiss: User dismisses the above notification
    * newposts_notification_view: User sees the "new ideas" notification on the WP Admin posts screen (can be tracked "on page load" _if_ the notification is present, i.e. no on-scroll necessary)
    * newposts_notification_complete: User clicks the link in the above notification
    * newposts_notification_dismiss: User dismisses the above notification
* The following events should be tracked using event category `idea_hub_wpdashboard`:
    * savedposts_notification_view: User sees the "saved ideas" notification in Site Kit's WP Dashboard widget (on scroll, like with PSI widget)
    * savedposts_notification_complete: User clicks the link in the above notification

## Implementation Brief
* Update `gaEventCategory` in `assets/js/feature-tours/idea-hub-module.js` to `idea_hub_widget`
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js`,
	* Use the `useInView` hook to check whether the component is in view to call `trackEvent` with `prompt_widget_view` as action.
	* Update the `onClick` function to call `trackEvent` with `prompt_widget_setup` as action.
	* Update the `onDismiss` function to call `trackEvent` with `prompt_widget_dismiss` as action.
	* The event category for `trackEvent` calls for the above bullet points should be `idea_hub_widget`.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`,
	* Use the `useInView` hook to check whether the component is in view to call `trackEvent` with `widget_view` as action.
	* Check if there is data in any tabs by checking the length of the `newIdeas`, `savedIdeas` and `draftIdeas` constants. If there is no data, call `trackEvent` with `widget_gathering_data_view` as action.
	* In case there is data, then call `trackEvent` with `default_tab_view` as action and the active tab as label. The active tab can be obtained via the `activeTab` constant. The label should be "new-ideas", "saved-ideas", or "draft-ideas".
	* Update the `handleTabUpdate` to call `trackEvent` with `tab_select` as action and the selected tab as label.
	* The event category for `trackEvent` calls for the above bullet points should be `idea_hub_widget`.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js`,
	* Update the functions below to call `trackEvent` with the corresponding action. (function: action)
		* `handleDelete`: `dismiss_idea`
		* `handlePin`: `save_idea`
		* `handleUnpin`: `unsave_idea`
		* `handleCreate`: `start_draft`
	* Add a new `onClick` prop to the `Button` component with the `googlesitekit-idea-hub__actions--view` class name and the callback should call `trackEvent` with `view_draft` as action.
	* The event category for `trackEvent` calls for the above bullet points should be `idea_hub_widget`.
* Using `assets/js/components/notifications/IdeaHubModuleNotification.js`,
	* call `trackEvent` with `prompt_notification_view` as action when the component is mounted.
	* Update `handleOnCTAClick` to call `trackEvent` with `prompt_notification_setup` as action.
	* Update `handleOnDismiss` to call `trackEvent` with `prompt_notification_dismiss` as action.
	* The event category for `trackEvent` calls for the above bullet points should be `idea_hub_dashboard`.
* Using `assets/js/googlesitekit-idea-hub-post-list.js`,
	* If there is a notice displayed and the id of the notice is `googlesitekit-notice-idea-hub_saved-ideas`, 
		* call `trackEvent` with `savedposts_notification_view` as action.
		* Update the callback when the notice is clicked to call `trackEvent` with `savedposts_notification_dismiss` as action.
		* Listen for click event on the notice when the link is clicked to call `trackEvent` with `savedposts_notification_complete` as action.
	* If the id of the notice is `googlesitekit-notice-idea-hub_new-ideas`, the following actions: `savedposts_notification_view`, `savedposts_notification_dismiss` and `savedposts_notification_complete` should be replaced by `newposts_notification_view`, `newposts_notification_dismiss` and `newposts_notification_complete` respectively when calling `trackEvent`.
	* The event category for `trackEvent` calls for the above bullet points should be `idea_hub_posts`.
* Using `assets/js/components/wp-dashboard/WPDashboardIdeaHub.js`,
	* Use the `useInView` hook to check whether the component is in view to call `trackEvent` with `savedposts_notification_view` as action.
	* Add the `onClick` prop to the `Link` component and the callback should call the `trackEvent` with `savedposts_notification_complete` as action.
	* The event category for `trackEvent` calls for the above bullet points should be `idea_hub_wpdashboard`.
* `trackEvent` function should be imported from `assets/js/util/tracking/index.js`
* Example of usage of `useInView` hook can be found in `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js`.

### Test Coverage

* No tests to be added.

### Visual Regression Changes

* N/A

## QA Brief

* Install the `Google Analytics Debugger` extension for your Google Chrome.
* Activate tracking on the admin settings page.
* Verify that custom events defined in AC are tracked correctly.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@marrrmarrr I've defined the ACs here based on the latest spreadsheet state.

**Comment by asvinb** [comment]
@felixarntz A couple of things:

- In the AC, the label should be "new", "saved", or "drafts" for `default_tab_view` and `tab_select`. Do you think we can use `new-ideas`, `saved-ideas` and `draft-ideas` instead? Because we have the labels [mapped like that in the code](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js#L196-L198).
- In the AC, it's mentioned: 
	> newposts_notification_view: User sees the "new ideas" notification in Site Kit's WP Dashboard widget (on scroll, like with PSI widget)
	> newposts_notification_complete: User clicks the link in the above notification
- However I don't see that notification. The only notification we have is [for saved ones, here](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/wp-dashboard/WPDashboardIdeaHub.js). Let me know if am missing something? 🤔

**Comment by felixarntz** [comment]
@asvinb That's a fair point, I've updated the event labels to use accordingly in the ACs. Good catch also on the notification - that indeed isn't there (and not required), so I removed those two events from the ACs.

**Comment by felixarntz** [comment]
@asvinb IB looks good, can you just update the labels based on your suggestion above and the updated ACs?

**Comment by asvinb** [comment]
Thanks @felixarntz 
IB Updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

**Verified:**  

Went through the AC and made sure that the action/component were logged.
Using the `Google Analytics Debugger `extension, when each event and compared with AC. 

![image](https://user-images.githubusercontent.com/73545194/130792022-4a7ccbbc-085d-4d00-babf-e9f75a549292.png)
