### ISSUE TITLE
Ensure the plugin inserts the Optimize snippet in all scenarios between GA4 and UA

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3822]
## Bug Description

If a user has manually or used a third party plugin to insert their Analytics snippet (UA, GA4 or both) and then connects the Optimize module there are situations whereby the plugin won't insert the Optimize container ID - as it can't attach the container ID to a non Site Kit placed snippet. 

This can be confusing for users, who may not be aware that the plugin no longer or doesn't insert the Optimize container ID, despite both services being connected. It can come about in the following circumstances:
- A user manually inserts both a UA and GA4 snippet and then connected Optimize
- A user may revisit their Analytics settings after setting up Optimize and doesn't allow Site Kit to insert a GA4 or UA snippet (see below)

![image](https://user-images.githubusercontent.com/41326532/128904396-6ac11535-e862-4c8f-8733-534511479d83.png)

To improve awareness or resolve this issue the following could be considered:

1. Don't allow the Optimize module to be connected if Site Kit has not inserted either a UA or GA4 Analytics snippet - while also disconnecting Optimize (with a warning) if a user removes Site Kit inserted Analytics snippets while keeping the Analytics module connected
2. Insert the Optimize snippet to a users site [independent of the Analytics snippet](https://i.imgur.com/LDaKVx7.png)

## Screenshots of the various possibilities at present:
- UA and GA4 snippet placed via SK - **no issue** ([Optimize snippet added to UA tag](https://i.imgur.com/0595KOf.png))
- UA manually inserted with GA4 snippet added via SK - **no issue** ([Optimize snippet added to GA4 tag](https://i.imgur.com/j7dgI50.png)), vice versa for a GA4 manually inserted tag
- UA manually inserted with no GA4 snippet added via SK - **problem** ([Optimize container is not added via Site Kit but the service remains connected](https://i.imgur.com/cZkxG59.png))
- UA and GA4 manually inserted - **problem**([Optimize container is not added via Site Kit but the service remains connected](https://i.imgur.com/P7NfkA8.png))
 
## To reproduce the issue

1. Setup Analytics within Site Kit although with a manually inserted GA4 & UA property
2. Setup Optimize within the plugin
3. Check your sites source code, the Optimize container is not added.  

## Additional Context

 - These potential confusing issues started since Site Kit inserted GA4 snippets 
 - There has been [one support topic](https://wordpress.org/support/topic/google-optimize-tag-on-non-amp-pages-when-site-is-on-amp-standard-mode/) whereby a user did encounter this issue
- [GA4 is not supported](https://i.imgur.com/QHxlKn5.png) in Optimize at this point. That doesn't block Optimize from working or restrict the functionality of the [Check installation](https://i.imgur.com/5PxFMKF.png) feature of Optimize, as it will look for the defined UA property on a users site (defined within Optimize). It doesn't matter if this Optimize container ID is attached to the GA4 snippet. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the Analytics module's `useSnippet` option is disabled _and_ if the GA4 module is connected and its `useSnippet` option is disabled, a warning notice should appear in the Optimize setup: _Site Kit is currently configured to neither place the Universal Analytics snippet nor the Google Analytics 4 snippet. If you have manually inserted these snippets, you will have to modify them to include the Optimize ID, or alternatively you will need to enable Site Kit to place them._
* If the Analytics module's `useSnippet` option is disabled (and GA4 is either not configured or the snippet is enabled), a warning notice should appear in the Optimize setup: _Site Kit is currently configured to not place the Universal Analytics snippet. If you have manually inserted this snippet, you will have to modify it to include the Optimize ID, or alternatively you will need to enable Site Kit to place it._
* If the GA4 module is connected and its `useSnippet` option is disabled (and the UA Analytics snippet is enabled), a warning notice should appear in the Optimize setup: _Site Kit is currently configured to not place the Google Analytics 4 snippet. If you have manually inserted this snippet, you will have to modify it to include the Optimize ID, or alternatively you will need to enable Site Kit to place it._

## Implementation Brief
* Using `assets/js/modules/optimize/components/setup/SetupForm.js`, render the appropriate message as per the AC after the `AnalyticsNotice` component.
* To get:
	* `useSnippet` value, query the `modules/analytics` or `modules/analytics-4` data store via the `getUseSnippet` selector.
	* if the analytics/analytics-4 module is connected or configured, query the `core/modules` data store via the `isModuleConnected` selector, passing the module name as parameter.
* The warning message should be styled as per the `AnalyticsNotice` component.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes

* 

## QA Brief

* Follow the reproduce steps and ensure correct notice is shown in the optimize setup form.

## Changelog entry

* Add the Optimize snippet notice to settings and setup forms.

**Comment by felixarntz** [comment]
@marrrmarrr I've added ACs with preliminary wording. Can you revise that please?

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by asvinb** [comment]
### QA: ✅ 

- UA and GA4 both disabled ✔️ 
- GA enabled only ✔️ 
- UA enabled only ✔️
