### ISSUE TITLE
Removed "Updated every 2-3 days" language from Idea Hub Saved and Drafts tabs

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3832]
## Bug Description

The "Updated every 2-3 days" language currently displays on all three IH tabs on the Dashboard: New, Saved, and Drafts. It should be removed from the Saved and Drafts tabs so it only displays on the New tab.
## Screenshots

![image](https://user-images.githubusercontent.com/12189958/129054955-dbbd5c19-6eb8-4e8a-a63b-e0f076e5b4c6.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Updated every 2-3 days" copy in the Idea Hub widget should only appear when in the "New" tab.

## Implementation Brief

* Add a new optional prop, `footerText`, to the `DashboardIdeasWidget` Footer component (`assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Footer.js`).
* Add the new prop with type `string` to the `propTypes` definition for the component.
* Inside the footer component, add a conditional:
  * if the `footerText` prop has been provided, render the current `<Grid>`, `<Row>` and `<Cell>` output, the sole difference being to replace the `'Updated every 2-3 days'` text with output of the new prop. 
  * if it is NOT provided, render the `<Pagination>` component inside a straightforward `<div>` instead (with the `googlesitekit-idea-hub__footer` className applied).
* Now, inside the `index` component, pass the  `'Updated every 2-3 days'` string as the `footerText` prop to the `Footer` component only if the `activeTab` is `new-ideas`.

### Test Coverage

* This shouldn't require any new tests.

### Visual Regression Changes

* It's possible that VRT images that deal with the widget may need updating.

## QA Brief

* Set up Site Kit with Idea Hub enabled and connected.
* Go to the Dashboard Ideas widget
* Observe the footer, while cycling through the 'new', 'saved' and 'drafts' tabs, and verify that the `Updated every 2-3 days` language is only visible in the `new` tab.

## Changelog entry

* Update the IdeaHub widget to display the "Updated every 2-3 days" message only for the new ideas tab.

**Comment by eugene-manuilov** [comment]
> * if it is NOT provided, render the `<Pagination>` component inside a straightforward `<div>` instead (with the googlesitekit-idea-hub__footer className applied).

@johnPhillips we need to make sure that the Pagination component is right-aligned to be consistent across all tabs.

**Comment by johnPhillips** [comment]
@eugene-manuilov I did address this (although it's not obvious from the IB!).

If we simply remove the `<Cell>` with the '2-3 days' content but leave the remaining `Grid > Row > Cell > Pagination` structure, then the `Pagination` is left-aligned. I did look, but I couldn't find an MDC grid option to make it align-right.

However, when the `<Pagination>` is rendered inside a simple `div.googlesitekit-idea-hub__footer`, its `justify-content: flex-end;` comes into effect. This makes it right-aligned and also loses us three wrapper `div`s, which is always nice :-)

| `<Grid>` with both `<Cell>` elements | `<Grid>` with single `<Cell>`  | Using `<div>` |
| --- | --- | --- | 
| ![Screenshot 2021-08-13 at 09 33 12](https://user-images.githubusercontent.com/2470911/129331123-75abd4fd-38f8-41e2-b3cd-12dbdc43c438.png) | ![Screenshot 2021-08-13 at 09 38 31](https://user-images.githubusercontent.com/2470911/129331128-9f12509a-9fb8-4ae1-87b3-755b5200b6db.png) | ![Screenshot 2021-08-13 at 09 33 30](https://user-images.githubusercontent.com/2470911/129331125-cc3902c2-0b56-4858-a2ef-d700b096ed12.png) |

Let me know what you think.

**Comment by eugene-manuilov** [comment]
Ah... ok, then it sounds good to me. Thanks, @johnPhillips. IB :heavy_check_mark:

**Comment by wpdarren** [comment]
QA Update: ✅ 

I can confirm that the `Updated every 2-3 days` language is only visible on the `new` tab. [Screenshot 1](https://user-images.githubusercontent.com/73545194/130076955-23e5d8e3-2374-4e36-81d2-8e743c50161c.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/130076977-a105dbe0-3004-4f85-8488-02f67dd1d3d5.png)
