### ISSUE TITLE
Change Idea Hub first tour bubble language from "organise" to "organize"

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3834]
## Bug Description

The first intro bubble uses the UK version of "organise" vs. US "organize." Since this feature is US-only right now, this should change to "organize."

## Screenshots

![image](https://user-images.githubusercontent.com/12189958/129064952-d236154f-ee8b-4cf4-8b49-b9bd9fc4e3a6.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The default Idea Hub copy should use US English, specifically the word "organised" (in one of the Idea Hub feature tour tooltips) should be replaced with "organized".

## Implementation Brief

* Inside `assets/js/feature-tours/idea-hub-module.js`,  replace 'organise' with 'organize'.

https://github.com/google/site-kit-wp/blob/6ba2897937775f8522eb746ec1610fb7d16e7841/assets/js/feature-tours/idea-hub-module.js#L67

* As this is a one-liner, I have created a PR here: https://github.com/google/site-kit-wp/pull/3847

### Test Coverage

* No new tests required.

### Visual Regression Changes

* It's possible that images dealing with the feature tour might need updating.

## QA Brief

* Follow the Idea Hub set up instructions (see Bug Bash instructions here), to connect and activate Idea Hub.
* After connecting, you should see the feature tour on the dashboard.
* Verify that the first feature tour bubble now contains the correct text as per the AC.

## Changelog entry

* Update language in Idea Hub feature tour to use en-US locale for consistency.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Confirmed that the tooltip text for `organised` is changed to `organized`. 

![image](https://user-images.githubusercontent.com/73545194/129763763-c285b5a2-99d8-4512-9d81-bfb1756a3937.png)
