### ISSUE TITLE
Idea Hub feature tour not shown on initial activation

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3836]
## Bug Description

When I stepped through the process of activating Idea Hub, accepted scopes and granted access and clicked 'Continue' after agreeing to track my usage of the feature, the Intro Bubble did not display, so it wasn't clear to me that it had actually been added, I had to scroll to find the newly added module.
Not sure if this is expected behaviour, but it would be good to display this the very first time it is added to the dashboard.
The Intro Bubble only displayed for me after I navigated away from SK dashboard to posts, and then back to the Dashboard, and only after I had interacted with Idea Hub at least once.

## Steps to reproduce

1. Activate the Idea Hub module
2. Get redirected to the Site Kit dashboard
3. Note that the feature tour does not display
4. Navigate away from the dashboard (or refresh the page) to see the feature tour appear

## Screenshots

![image](https://user-images.githubusercontent.com/83005909/129161076-28a22ea4-7c90-448e-8701-ebb4b673e778.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub feature tour on the dashboard should appear immediately after Idea Hub is activated and the Site Kit dashboard is loaded (eg. on first page visit after Idea Hub is connected)

## Implementation Brief

* Update the selector used in the `ideaHubModule` feature tour to resolve-select `getNewIdeas` since this will always be empty just after initial activation so it must wait for the resolver to fulfill it https://github.com/google/site-kit-wp/blob/332a78d2c38f388662a46bf55a230b07215f6952/assets/js/feature-tours/idea-hub-module.js#L54-L55
* Merge https://github.com/google/site-kit-wp/pull/3892

### Test Coverage

* No changes 

### Visual Regression Changes

* No changes

## QA Brief

* This is easiest to test using a fresh site
    * Note this requires having new ideas to work – a helper plugin may be needed to provide them if the API isn't providing them
    * Remember to use a custom URL for a site that has ideas for it
* Activate Idea Hub
* Ensure the feature tour is shown on the initial page view of the SK dashboard 

## Changelog entry

* Fix Idea Hub Tour Activation bug.

**Comment by aaemnnosttv** [comment]
@tofumatt @eugene-manuilov ready for review!

**Comment by tofumatt** [comment]
IB ✅  knowing that this API will become non-private once we upgrade WPData (#3277).

**Comment by wpdarren** [comment]
@ivankruchkoff @aaemnnosttv do you think this can be tested while the API is not showing ideas?  I tried using the `Test Idea Hub connection` plugin (latest version 1.0.6) and when I connected Idea hub the tour did not appear.  I can trigger the tour with the URL, but in my opinion this isn't really testing this fix.  Thoughts?

**Comment by aaemnnosttv** [comment]
@wpdarren good question – using the test plugin in its current state will not test this because the problem has to do with the asynchronous resolution of ideas in the check for the tour. By using the plugin, it bypasses this by providing them up front, so it isn't representative enough to test this.

We could still use a plugin to test it (without using the real API) but it needs to actually allow for ideas to be requested from the backend. I can provide this if the API still isn't working later today.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

On a fresh test site, with idea hub activated with ideas, the tour appears when connecting the module on SK dashboard.  
Also made sure that all tour tips functioned and when completed, the tour did not reappear when the browser was refreshed. 

![image](https://user-images.githubusercontent.com/73545194/130091241-7e5062db-a392-4bbd-b3c9-f4b777a70520.png)
