### ISSUE TITLE
When i click on the view draft for an idea, it takes me to the post composer but I am unable to see the prompt associated with this draft.  is it possible to add some default text or title that shows the prompt that is associated with the post?

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3837]
## Bug Description

![image](https://user-images.githubusercontent.com/83005909/129161436-a1490c7a-355c-4222-adf6-ec30ac349585.png)

Asana link: https://app.asana.com/0/1200491083500938/1200760567419957

Asana comments: 

daishiYesterday at 4:13am
The instructions say that we should expect "In the WordPress editor, you should see an informational notice on top, explaining that this is an Idea Hub idea-based draft, including for which idea it is.".

As shown in Jeff's screenshot (which is what I'm also seeing), this informational notice is not present.
Felicity HollisYesterday at 9:24am
Also mentioned here When you create a draft from Idea hub, it creates a post and puts the title in the draft status.  Do we have any plans to include the idea as the post title? 
@Mariya Moeva is this something we decided could not be done or should we be seeing this as per the figma designs?
Felicity Hollis added to Enhancement.Yesterday at 9:24am
Mariya MoevaYesterday at 1:53pm
I think this should be shown. If the person clicks "view draft" and ends up on a completely blank page, that's a confusing experience.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
@aaemnnosttv you said that you worked on a fix for this issue. Did you figure out why it stopped working? I have upgraded my local WP to the latest version and I still see the notice on the post edit screen.

**Comment by aaemnnosttv** [comment]
The existing notice where this was shown was fixed in https://github.com/google/site-kit-wp/issues/3827 👍 

cc: @felixarntz
