### ISSUE TITLE
Broken Idea Hub pagination layout

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#3838]
## Bug Description
Upon resizing the browser to 960px, the layout of the pagination in the Idea Hub dashboard widgets looks broken.

## Steps to reproduce

1. Go to the Site Kit dashboard
3. Scroll down to the Idea Hub widget.
4. Resize browser to 960px (note: I needed to use `961px` - `981px` wide, - @tofumatt)
4. See broken layout

## Screenshots
![image](https://user-images.githubusercontent.com/31818/129163695-5d7c31a2-160c-46db-be20-5bbf344491c3.png)

## Additional Context

 - Browser: Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The pagination should always look like it does in the mockup, eg:
<img width="184" alt="Screenshot 2021-08-12 at 15 22 09" src="https://user-images.githubusercontent.com/90871/129215448-2ff29d85-ecfc-4bf6-83fa-bb27f0d32b7f.png">, even between `961px` to `981px` wide.

## Implementation Brief

To fix this, reduce the right margin on the first pagination button.

Using `assets/sass/components/idea-hub/_googlesitekit-idea-hub-pagination.scss`: 

* In the class `button.mdc-button` (Inside the class `.googlesitekit-idea-hub__pagination--buttons`)
  * Set the right margin to `0` for the first child button.

### Test Coverage

* No changes

### Visual Regression Changes

* No changes

## QA Brief
* Go to Site Kit dashboard
* Resize browser to 961px
* The layout for the pagination of the Idea Hub module should not be broken.
* Check across different breakpoints.

## Changelog entry

* Fix Idea Hub dashboard widget pagination controls from stacking in small viewports.

**Comment by danielgent** [comment]
This is an idea of how to fix this (without changing any other components, only the styling of the `Pagination`)


https://user-images.githubusercontent.com/8496063/129476407-c98effd5-679b-4b24-a7c8-5ba3ea851fe5.mp4

IB is written. Just involves removing the right margin on the first pagination button `<` for the breakpoints mentioned in the AC

**Comment by eugene-manuilov** [comment]
On my local machine, the pagination layout is broken starting from 996px. I think the most reliable way to fix this issue is to remove the right margin for the first button unconditionally. I'll update the IB.

**Comment by eugene-manuilov** [comment]
IB is udpated. @tofumatt do you mind reviewing this IB?

**Comment by tofumatt** [comment]
Works for me, IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

When the browser is resized to 961px the layout for the pagination of the Idea Hub module is not broken.
I also checked across different breakpoints to make sure the pagination displayed as expected. 

![image](https://user-images.githubusercontent.com/73545194/130083182-3c1e3b4a-fb37-4fa4-ba69-e5d1a9626af5.png)
