### ISSUE TITLE
Site verification detection broken for domain verification

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#384]
## Bug Description

Although my website is verified via domain verification (using DNS), Site Kit doesn't detect it as verified. That happens because of an undefined variable `$site_url` in the `siteverification-list` datapoint (when checking verification via `INET_DOMAIN`). Furthermore site's identifier in the Google API response contains a trailing slash, but the current site URL is not compared with a trailing slash.

This bug has only become apparent because of the work in #359: Currently the Site Verification check is only a fallback to the Search Console check, which isn't right. While testing the work to fix this (via the linked issue), I ran into this bug.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A site which is verified via domain verification should be properly recognized as already verified in the Site Kit verification step of the setup wizard.
* Both URLs should be compared in a trailing-slashed variant.

## Implementation Brief

* In the condition in https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Search_Console.php#L447:
    * Replace `$site_url` with `$current_url`.
    * Ensure the `$host` and `$current_url` are compared with trailing slash (via `trailingslashit()`).

## Changelog entry

* Fix URL comparison in Site Verification flow when comparing with a site verified with type `INET_DOMAIN` (domain verification).

**Comment by aaemnnosttv** [comment]
Implementation brief looks good!

**Comment by aaemnnosttv** [comment]
Code review approved.

**Comment by lucymtc** [comment]
QA looks good

**Comment by hadifarnoud** [comment]
can you please allow DNS verification?

**Comment by aaemnnosttv** [comment]
@hadifarnoud - Your site can use any supported method for site verification but you would have to do that manually. For users who are not yet verified for their site, Site Kit facilitates the verification process using the HTML file and meta tag methods. If your user is already verified for your site using another method, Site Kit will proceed through the set up without additional steps for the verification process.
