### ISSUE TITLE
Widget does not show optimal number of ideas per page

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3843]
## Bug Description

This probably varies between viewports and length of idea but it's a little odd that the widget could fit another idea but it isn't shown.

This might lead users to not click through to other pages of results as it looks like there are only 4 ideas due to the empty space.

![image](https://user-images.githubusercontent.com/83005909/129164825-3dd8791c-5954-4965-9ed5-d42c74223fc0.png)

**Mariya Moeva**
Yesterday at 1:34pm
_I am seeing the same, with 1-4 out of 5 ideas displayed, and lots of white space._

**Asana link:** https://app.asana.com/0/1200491083500938/1200759450014528

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* We should determine a more appropriate number of ideas to display per page, so that on viewport sizes where the Idea Hub widget appears next to another widget there is less white-space below the ideas.
    * Due to different viewports this may not always be perfectly doable, but currently it looks like we can fit at least 1-2 more ideas in there in most of these cases.
* In viewports where the Idea Hub widget does not appear next to another widget (e.g. on mobile devices), there should be no extra white-space below the ideas (since in this circumstance there is no other widget next to it that would need to have the same height).

## Implementation Brief
* Using `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`,
	* Update the existing styles for `.googlesitekit-idea-hub__content[aria-hidden="true"]` to be applied as from `desktop` breakpoint. It should also have `display:none` on smaller viewports than the `desktop` breakpoint and then `display: block` as from `desktop` to preserve existing functionality.
* Update `IDEA_HUB_IDEAS_PER_PAGE` to `5` in `assets/js/modules/idea-hub/datastore/constants.js`

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* The Idea Hub module should display 5 items instead of 4 on the main dashboard.
* Resize the browser to < than 960px and verify there is not empty white space between the ideas and pagination.
* Check if there is no horizontal scrollbar showing up

## Changelog entry

* Update the number of ideas shown per page on the Idea Hub dashboard widget.

**Comment by asvinb** [comment]
@aaemnnosttv @felixarntz 
Assuming that each idea in general will be on 2 lines, I've found that displaying 5 items should be ok. Screenshots below. According to our Analytics reports, in the top 10 screen resolutions, 63% of Site Kit users have a screen resolution of `1366px` and above, 6% have `1280px` and when I tested, 5 ideas looked good.

961px
![image](https://user-images.githubusercontent.com/31818/129559749-19d71103-a72a-4ea0-9e2a-a1be059a1fdf.png)

1280px
![image](https://user-images.githubusercontent.com/31818/129544002-e45a0236-66e9-4ab5-a073-39dae933360b.png)

1366px
![image](https://user-images.githubusercontent.com/31818/129559540-dd11b862-8095-4dde-be12-36deabdb38bb.png)

**Comment by felixarntz** [comment]
@asvinb Displaying 5 ideas looks like a good value to me - IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Idea Hub module displays 5 items instead of 4 on the main dashboard.
- Resizing the browser to < than 960px does not show any empty white space between the ideas and pagination.
- Verified that there is no horizontal scrollbar showing up

![image](https://user-images.githubusercontent.com/73545194/130081618-9b32e4ff-dafc-40e8-a835-c348342f0324.png)
