### ISSUE TITLE
"Revisit your saved ideas" appears as copy on wp-admin dashboard, even if the user doesn't have any saved ideas. 

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3845]
## Bug Description

The CTA goes to the empty "saved ideas" tab. 

![image](https://user-images.githubusercontent.com/83005909/129165087-f31c160f-2621-4525-ab68-d80292f7049e.png)

**Asana Link:** https://app.asana.com/0/1200491083500938/1200766086791616

**Evan**
@Felix Arntz looks like a logic bug https://github.com/google/site-kit-wp/blob/c26b8c6f62e62e51524592e66464f91d15257e1d/assets/js/components/wp-dashboard/WPDashboardIdeaHub.js#L66

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub CTA in the WordPress dashboard widget should show up only when a user has at least one saved idea.

## Implementation Brief

* Update the following condition in the `assets/js/components/wp-dashboard/WPDashboardIdeaHub.js` file to use `||` instead of `&&`: https://github.com/google/site-kit-wp/blob/fb6d3e8791601d19de8ef6ea561998fca89bef66/assets/js/components/wp-dashboard/WPDashboardIdeaHub.js#L66-L68

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Make sure you have no saved ideas.
* Go to the WordPress dashboard page and verify that you don't see the Idea Hub CTA in the Site Kit widget.
* Save an idea and check the WordPress dashboard widget again. Now it should display the CTA that says that you have new ideas.
* Go back and un-pin saved ideas.
* Go back to the WordPress dashboard page and verify that the Idea Hub CTA disappear again.

## Changelog entry

* Fix Idea Hub CTA for saved ideas on the WordPress dashboard to only show if the user has any saved ideas.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by danielgent** [comment]
Linked PR is done and ready for CR (but I won't move it to CR as it's outside the current sprint)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov this passes the QAB, but not sure about the font colour on the message and also 'view' link.  Seems inconsistent with other notices.  What do you think?  [Notice font colour](https://user-images.githubusercontent.com/73545194/130085150-7c71e3ba-40d2-4b3e-b23b-47391d7704ff.png) and [Link colour](https://user-images.githubusercontent.com/73545194/130085194-5aa05ee4-1c12-487e-98dd-2b78134a5418.png)
