### ISSUE TITLE
Incorrect CTA background color on Site Kit admin bar

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#3849]
## Bug Description
When using the Twenty Twenty One theme, the CTA to set up Analytics in the admin bar on the front end has an incorrect background color.

## Steps to reproduce

1. Activate the Twenty Twenty One theme
2. Do not connect the Analytics module or disconnect it if it's connected.
2. Go on the page where the Site Kit admin bar is visible
3. Click on the "Site Kit" link to open the Site Kit admin bar
4. See CTA has a black background color.

This is reproducible only using the Twenty Twenty One theme.

## Screenshots
![image](https://user-images.githubusercontent.com/31818/129201284-8993b710-ebef-435a-911e-60fd76b8fce0.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The style for links in the admin bar should be specific enough so that themes like Twenty Twenty are less likely to override it.
* Specifically, a background directive (transparent) should be provided for links so that themes using background colors for links don't override it.

## Implementation Brief
* Using `assets/sass/components/adminbar/_googlesitekit-adminbar-overrides.scss`, add `background-color: transparent` to `.googlesitekit-cta-link`

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Follow **steps to reproduce**.
* See there is no longer the black bar on the CTA link. 

## Changelog entry

* Fix Admin Bar Analytics link when using Twenty Twenty-One theme.

**Comment by tofumatt** [comment]
IB ✅ 

Tagging this as a good first issue as well.

**Comment by johnPhillips** [comment]
Just a note that the issue was actually reported on the _Twenty Twenty One_ theme, not the Twenty Twenty theme as originally described in the issue. I've updated it.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Was able to confirm the reported issue as per steps to reproduce and when switched to develop branch, styling issue was resolved. There is no longer the black bar on the CTA link.
