### ISSUE TITLE
Update formatting of exclusion switches for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3850]
## Feature Description

The `*ExclusionSwitches` components have a few details that are inconsistent between them, but also with other conventions of our UI.

* full-stops for non-sentences / descriptive phrases (e.g. "Ads will be displayed for all users." should not have a full-stop at the end)
* trailing colon after section label/heading (e.g. "Don't display ads for:" should not have a trailing colon)

**Analytics**
![image](https://user-images.githubusercontent.com/1621608/129216360-49fbefba-3f0e-46e2-91b1-b05be12ce2fc.png)

**AdSense**
![image](https://user-images.githubusercontent.com/1621608/129216345-aeba7137-ee62-47f6-8a9e-7bb0e1f4d650.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update the exclusion switches label text for AdSense  
```diff
- Don’t display ads for:
+ Exclude from Ads
```
* Remove the full-stop from the end of the descriptive text for exclusion choices for Analytics and AdSense

## Implementation Brief

* In the `AutoAdExclusionSwitches` component:
  * Replace `Don’t display ads for:` with `Exclude from Ads`
  * Remove the full-stop from the end of the following messages:
    * https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/assets/js/modules/adsense/components/common/AutoAdExclusionSwitches.js#L58-L61
    * https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/assets/js/modules/adsense/components/common/AutoAdExclusionSwitches.js#L66-L69
    * https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/assets/js/modules/adsense/components/common/AutoAdExclusionSwitches.js#L71-L74
* In the `TrackingExclusionSwitches` component:
  * Remove the full-stop from the end of the following messages:
    * https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/assets/js/modules/analytics/components/common/TrackingExclusionSwitches.js#L58-L61
    * https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/assets/js/modules/analytics/components/common/TrackingExclusionSwitches.js#L66-L69
    * https://github.com/google/site-kit-wp/blob/f54254f2bf2e71d6660c4f5f3510c89027a048bd/assets/js/modules/analytics/components/common/TrackingExclusionSwitches.js#L71-L74

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Visit the settings panels for Analytics and Adsense, and verify that the copy around the exclusion switches is as per AC.

## Changelog entry

* Improve text on AdSense and Analytics setting toggles.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Visited the settings panels for Analytics and Adsense, and verified that the copy around the exclusion switches is as per AC.

![image](https://user-images.githubusercontent.com/73545194/135261022-a7f2a9bf-43e7-4c7e-8e07-9a5715e863cb.png)

![image](https://user-images.githubusercontent.com/73545194/135261043-552ec8f0-0444-490d-b725-edb87aa8c6ec.png)
