### ISSUE TITLE
Layout of zero new ideas inconsistent with zero state for saved and draft ideas

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3854]
## Bug Description

![image](https://user-images.githubusercontent.com/83005909/129230784-fbf92d26-e319-4ec9-8fed-7a58466d8ec3.png)

**Asana** - https://app.asana.com/0/1200491083500938/1200763426754102

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@marrrmarrr is this a launch blocker? Seems like it could be a P1.

**Comment by eclarke1** [comment]
@marrrmarrr could you please advise on this one whether it is a launch blocker, or Nice to have. In Asana we have it as a launch blocker :)

**Comment by aaemnnosttv** [comment]
This has already been fixed it seems in another issue.

![image](https://user-images.githubusercontent.com/1621608/130788072-78041c35-7da4-4dad-80f6-ff2497d8cd4a.png)
![image](https://user-images.githubusercontent.com/1621608/130788082-52a686f3-002e-4e60-9bbd-541432f59317.png)
![image](https://user-images.githubusercontent.com/1621608/130788089-23cd199f-9786-4df6-b8e4-26cbaac6debf.png)
