### ISSUE TITLE
Mobile: The icons look lost. Possible adjusting of the padding to bring closer to the idea

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3855]
## Bug Description

Darren CronianYesterday at 12:27pm
I noticed this on Android and iOS phones.

![image](https://user-images.githubusercontent.com/83005909/129230983-95207b4d-7093-4108-bcd5-6330cccfb517.png)

![image](https://user-images.githubusercontent.com/83005909/129230995-9db3ddc0-0cf0-4302-ac54-b9ae568c07d3.png)

**Asana** https://app.asana.com/0/1200491083500938/1200765888444274

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no gap between text and action items within a single idea on mobile devices.

## Implementation Brief

* Update styles of the inner row (`<Row />` component) in the `Idea` component to have an empty row gap setting (using grid `row-gap` property).

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief
* Go to Site Kit dashboard using a mobile or using the emulator in your browser
* Check if the icons are closer to the idea name

## Changelog entry

* Update position of action buttons for ideas in Idea Hub dashboard widget in mobile.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that the icons are closer to the idea name.   
- Confirmed that the same applies to saved ideas and draft links. 
- Checked on various small screen sizes and supported browsers. 

![image](https://user-images.githubusercontent.com/73545194/129762745-74477119-2663-44ba-ab69-64dbf3551406.png)
