### ISSUE TITLE
When an idea has multiple topics, we need to separate them with a comma or another separator because without a separator it seems like there is one big topic

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3857]
## Bug Description

![image](https://user-images.githubusercontent.com/83005909/129231300-77f43c19-4c2f-4d1f-a4f6-9dba14d52d39.png)

![image](https://user-images.githubusercontent.com/83005909/129231313-f79af5f1-a3c0-4b74-a40a-51a6675181ef.png)

![image](https://user-images.githubusercontent.com/83005909/129231321-e77c9756-7ee5-40cb-8643-5a0ec97c1f84.png)

Please note @Pratheep-lab's comments in Asana: https://app.asana.com/0/1200491083500938/1200749910371621

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The topics that appear above an idea in the Idea Hub widget should have their styling adjusted so that they can be clearly visually separated (in case there are multiple topics).
* For that purpose, the light-blue background as seen in the last design screenshot above should be used.

## Implementation Brief

Using `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`

For the class `.googlesitekit-idea-hub__idea--topic`, add the following rules
```
background-color: $c-solitude;
border-radius: 2px;
padding: 1px 6px;
```

This is done on this open PR - https://github.com/google/site-kit-wp/pull/3867

### Test Coverage

* No changes

### Visual Regression Changes

* No changes

## QA Brief

* Go to the dashboard page.
* Verify that idea topics have a light-blue background as shown in the last design screenshot above.

## Changelog entry

* Update styles of the topic idea element to have a light-blue background.

**Comment by danielgent** [comment]
@Pratheep-lab Do you have a design file for this? On Figma or whatever

![done-by-eye](https://user-images.githubusercontent.com/8496063/129348327-3c7ab955-c946-45f5-bb66-e2cc7a034526.png)

I've just done this by eye using the JPG but it's not correct, and I know it'll end up with back-and-forth as we all guess the measurements :wink:

**Comment by Pratheep-lab** [comment]
@danielgent Sorry if the Figma file was not shared as part of the Asana task. Here is the direct link to it: https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-Idea-Hub?node-id=21108%3A4109
CC: @eclarke1 @felixarntz

**Comment by danielgent** [comment]
@Pratheep-lab  Great stuff!

I don't see the background colour `#e8f1fd` as an existing variable. I'm not sure if that's a problem on Site Kit though. I can let whoever does the IBR tell me
		
This is what I've got it looking like. Any comments?

![done-by-eye](https://user-images.githubusercontent.com/8496063/129350374-05c543d7-b1ea-459f-bf39-ffacfa564350.png)

**Comment by Pratheep-lab** [comment]
@danielgent Use this color $c-solitude: #e8f0fe; I have updated the designs as well.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@eugene-manuilov the font color is #5f6368 on my test site but on the designs it's #333333.  Also, the character spacing appears to be tight. Have to say the font color and character spacing makes the text much easier to read on the [Figma](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=21108%3A4109).

**Verified:**

Verified that idea topics have a light-blue background as shown in the screenshot.  

![image](https://user-images.githubusercontent.com/73545194/129752162-f1bff7f4-fc01-4982-aa11-e2885228155d.png)

**Comment by danielgent** [comment]
@Pratheep-lab The desired text colour `#333333` isn't a variable on Site Kit

The closest constants in `assets/sass/config/_variables.scss` are
```
$c-cape-cod: #3c4043;
$c-nearblack: #212121;
```

![near-black](https://user-images.githubusercontent.com/8496063/129767626-a60f4e32-00d5-4f6c-a2d5-fb1bd918984a.png)

![cape-cod](https://user-images.githubusercontent.com/8496063/129767629-9cd411b4-0398-4aac-99d8-e91e496632d3.png)

I'll go with `near-black` as @wpdarren  complained about contrast, but let me know! :smile:

**Comment by Pratheep-lab** [comment]
@danielgent near black looks good to me. And yes, the letter spacing needs to be more. 

Good catch @wpdarren

**Comment by danielgent** [comment]
![looks now](https://user-images.githubusercontent.com/8496063/129770134-b44bdb63-c0f8-4329-ac9c-2ec8a92c766c.png)

It looks a lot better now :smile: @wpdarren  @Pratheep-lab 

This is on this PR @eugene-manuilov https://github.com/google/site-kit-wp/pull/3893 . I'll assign the ticket to you now

**Comment by eugene-manuilov** [comment]
@wpdarren this is ready for another round of QA

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Verified that idea topics have a light-blue background as shown in the screenshot.

![34322323](https://user-images.githubusercontent.com/73545194/129908978-1d2949fc-7c08-40c0-a987-e4687b968b5f.png)
