### ISSUE TITLE
Can't dismiss or pin suggested post

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3858]
## Bug Description

I can't dismiss a suggested idea that appears in the primary widget. 
http://recordit.co/LY4iSWIaJ9

Upon each click the below console error appears:
Google Site Kit API Error method:POST datapoint:update-idea-state type:modules identifier:idea-hub error:"The response is not a valid JSON response."

![image](https://user-images.githubusercontent.com/83005909/129231619-0f18b0eb-4f1c-4214-b9af-a9c84300966f.png)

**Asana link** https://app.asana.com/0/1200491083500938/1200758607582704

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
This issue is more likely a result of the incorrect version test. The attached screenshot contains dummy ideas that used had been hardcoded before we integrated the real Idea Hub API.

@jamesozzie I am going to assign this ticket to you to confirm it on your end.

**Comment by jamesozzie** [comment]
Thanks @eugene-manuilov. I suspect all is fine with the latest version after updating. While I have no idea's suggested just yet to test with I am seeing a notice which didn't appear previously. 

![image.png](https://images.zenhubusercontent.com/5e3a96adc0f4cb7f729b1888/07444c10-f5a0-431a-a720-42b13c5b68ec)

I'll let you know once the widget is populated.

**Comment by eclarke1** [comment]
@jamesozzie @eugene-manuilov can you please confirm whether this ticket can be closed at all?

**Comment by jamesozzie** [comment]
@eclarke1 I can confirm this is no longer occurring for me. https://recordit.co/zMGQzssx4G. Happy to close.
