### ISSUE TITLE
When i click on the draft icon and say the idea is the only one showing on the page, it disappears and it looks like there are no more prompts.  i'm wondering if it should automatically switch to the previous page of prompts in this case.

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3859]
## Bug Description

Please note Asana comments....

**Asana** https://app.asana.com/0/1200491083500938/1200760567419955

## Steps to reproduce

1. Make sure Idea Hub is connected, and you are using the Idea Hub testing plugin (at least [v1.0.6](https://10up.slack.com/files/U11CQS9U1/F02B4EQMWHM/google-site-kit-idea-hub-force-connected.1.0.6.zip))
2. Go to the Site Kit dashboard and locate the Idea Hub dashboard widget. Start with the `New` tab.
3. Create a scenario where there is an 'orphan' idea, i.e. the number of pagination pages is greater than one, and on the last page there is a single idea. So if 5 ideas are shown per page, you will need n*5 + 1 ideas (e.g. 6, or 11). You can use the plugin to do this, e.g. by opening the browser console and entering `gskNewIdeas(6)` to generate 6 ideas.
4. Perform an action that will remove the idea from the page, e.g. make this single idea into a draft.
5. When the idea disappears we are left with an empty page.
6. Secondarily, the number on the pagination is incorrect. For example if you just made the 5th Idea into a draft, it will say `5-4 of 4` (see screenshot).
7. The bug can probably be reproduced in the `Saved` tab if you populate it with pinned ideas and then remove the last one on a pagination page by either unpinning it or making it a draft.

## Screenshots

![image](https://user-images.githubusercontent.com/83005909/129231729-d6cdba73-2e74-480e-ba04-203a4d61da2e.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After the only idea on the current paginated Idea Hub widget page has disappeared from the current tab (e.g. after saving a "new" idea or dismissing an idea), the user should land on the previous page of ideas instead of remaining in the (now empty) page.
* The pagination should never have a value greater than the number of ideas available in the tab (which will probably be automatically fixed by addressing the above).

## Implementation Brief

* Inside `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Pagination.js`
  * Refactor the `sprintf` so that the ternaries are pulled out and assigned to variables (e.g. `from`, `to`).
  ```js 
	const from = page === 1 ? page : // etc ;
	const to = total < page * IDEA_HUB_IDEAS_PER_PAGE ?  // etc
	// Then:
 	{ sprintf(
		/* translators: 1: from, 2: to, 3: total items */
		_x(
			'%1$s - %2$s of %3$s',
			'{from} - {to} of {total}',
			'google-site-kit'
		),
		from,
		to,
		total
	) }

  ```
  * Add a call to `useEffect` that tests whether we have just removed an 'orphan' idea (i.e. the only one left on a page), and therefore need to remove the empty page from the pagination stack. So if there is more than one page in the stack, and `from` is greater than `to`, call `handlePrev()` to decrement the page counter:
  ```js
	useEffect( () => {
		if ( page > 1 && from > to ) {
			handlePrev();
		}
	}, [ /*...*/ ] );
  ```

### Test Coverage

* No new tests required.

### Visual Regression Changes

* Unlikely to require VRT updates.

## QA Brief

* Follow the `Steps to reproduce` above.
* Verify that when the last idea on a given pagination page is removed (e.g. making a new or saved idea into a draft, or by pinning / unpinning), the pagination updates to the previous page, and that the text of the pagination is correct.

## Changelog entry

* Improve pagination behaviour in Idea Hub.

**Comment by danielgent** [comment]
I'm struggling to get any new ideas to actually show.

I'm sure I was seeing some not long ago but now I'm stuck with the message `Idea Hub is generating ideas`

I'm using https://oi.ie/ in the developer settings plugin :thinking:

**Comment by wpdarren** [comment]
@danielgent  Yes, I noticed it on elasticpress.io this afternoon too.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- You're on page 1 and with 6 ideas on the new tab: a draft is created, when the idea disappears you are not left with an empty page. You are still viewing page 1 with 5 ideas listed.
- You're on page 3 and with 11 ideas on the new tab: a draft is created, when the idea disappears you are not left with an empty page. You are viewing page 2, with 10 ideas listed. 
- When the last idea on a given pagination page is removed (as above), the pagination updates to the previous page, and the text of the pagination is correct.
