### ISSUE TITLE
Analytics: Looks like you don't have Analytics account yet / Refetch my account not working 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#386]
When adding the Analytics module some users are encountering issues connecting to existing Analytics properties when tracking code already exists on a users site. 

![image](https://user-images.githubusercontent.com/41326532/62617566-1256ca00-b90a-11e9-9625-35a21e51d25c.png)

Related Issues
#154, #213, #320, #234, #324, #237, #241

**Potential cause:** 
- Caching plugin (WP Super Cache, Breeze, AutoOptimize etc)
- WooCommerce plugins
- Ad Blockers (Sometimes packaged within browsers as opposed to browser extension ie. Opera, Cyberfox)
- Hosting security/firewall software (ModSecurity etc)

**Potential Fix:**
- Disable potential conflicting plugins and attempt connecting Analytics again
- Attempt to connect Analytics module via incognito window
- Disable any active Ad blockers (Chrome extension ad blockers or in built browser ad blockers)

If the above fails to resolve the issue please report below with the following additions:  
 - PHP Version: 
 - Browser console errors
 - Plugin Version [e.g. 22]

Alternatively provide a screenshot or copy and paste the contents of your WordPress environment using a plugin such as [Site Health Check](https://i.imgur.com/Rtkmsba.png) or [Debug Info](https://wordpress.org/plugins/debug-info/)

**Comment by lucasreina** [comment]
Hi everyone. I tried every steps to resolve my problem, but no one worked. 

PHP Version: 7.2.20 
Browser: Opera
Browser console errors
Plugin Version Version 1.0.0-beta.1.0.3
Device:  Notebook

**Comment by jamesozzie** [comment]
@lucasreina Do you mind checking using an alternative browser? If that fails to resolve the issue please perform a [Site Health check](https://i.imgur.com/Rtkmsba.png) and share the information for us to inspect?

**Comment by lucasreina** [comment]
> @lucasreina Do you mind checking using an alternative browser? If that fails to resolve the issue please perform a [Site Health check](https://i.imgur.com/Rtkmsba.png) and share the information for us to inspect?

`
### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: /%category%/%monthnum%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/tempie/public_html
wordpress_size: 83.78 MB (87846095 bytes)
uploads_path: /home/tempie/public_html/wp-content/uploads
uploads_size: 133.94 MB (140451361 bytes)
themes_path: /home/tempie/public_html/wp-content/themes
themes_size: 3.05 MB (3203127 bytes)
plugins_path: /home/tempie/public_html/wp-content/plugins
plugins_size: 189.13 MB (198319363 bytes)
database_size: 22.24 MB (23321473 bytes)
total_size: 432.15 MB (453141419 bytes)

### wp-active-theme ###

name: Twenty Nineteen
version: 1.4
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, widgets
theme_path: /home/tempie/public_html/wp-content/themes/twentynineteen

### wp-themes (2) ###

Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (26) ###

Elementor: version: 2.5.16, author: Elementor.com (latest version: 2.6.8)
Elementor Pro: version: 2.5.5, author: Elementor.com (latest version: 2.6.2)
Essential Addons for Elementor: version: 3.1.5, author: WPDeveloper
Essential Addons for Elementor - Pro: version: 3.0.3, author: WPDeveloper (latest version: 3.1.1)
Google Site Kit Dev Settings: version: 0.1.0, author: Google
Gravity Forms: version: 2.4.9.5, author: rocketgenius
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
JetBlocks For Elementor: version: 1.1.4, author: Zemez (latest version: 1.1.10.1)
Jet Elements For Elementor: version: 1.15.5, author: Zemez (latest version: 1.15.16)
JetMenu: version: 1.5.8.1, author: Zemez (latest version: 1.5.14)
Jet Parallax: version: 1.0.6, author: Zemez
Jet Popup: version: 1.2.5, author: Zemez (latest version: 1.2.8)
JetThemeCore: version: 1.1.8, author: Zemez (latest version: 1.1.12)
JetTricks: version: 1.1.8, author: Zemez (latest version: 1.2.0)
Piotnet Addons For Elementor Pro: version: 4.2.3, author: Luong Huu Phuoc (Louis Hufer) (latest version: 5.2.0)
Premium Addons PRO: version: 1.5.8, author: Leap13
Restrict Content Pro: version: 3.0.9, author: Restrict Content Pro Team
Site Kit by Google: version: 1.0.0-beta.1.0.3, author: Google
Slick Menu Pro: version: 1.1.6, author: XplodedThemes
Slick Menu Social Networks: version: 1.0.5, author: XplodedThemes
Sticky Header Effects for Elementor: version: 1.3.1, author: Rwattner (latest version: 1.3.2)
Styles & Layouts Gravity Forms: version: 4.2.1, author: Sushil Kumar (latest version: 4.2.3)
Super Store Finder Wordpress: version: 5.3, author: Joe Iz
The Plus Addons for Elementor Page Builder: version: 1.4.0, author: POSIMYTH Themes
WhatsApp Chat by NinjaTeam: version: 2.2, author: NinjaTeam
WPForms Lite: version: 1.5.2.3, author: WPForms (latest version: 1.5.4.2)

### wp-plugins-inactive (5) ###

Akismet Anti-Spam: version: 4.1.2, author: Automattic
All-in-One WP Migration: version: 6.77, author: ServMask (latest version: 7.4)
Metronet Tag Manager: version: 1.5.4, author: Ronald Huereca
Yoast SEO: Local: version: 11.5, author: Team Yoast and Arjan Snaterse
Yoast SEO Premium: version: 11.5, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.25.6.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.2.20 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 128M
php_post_max_size: 8M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false

### wp-database ###

extension: mysqli
server_version: 5.5.5-10.2.25-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/tempie/public_html/wp-content
WP_PLUGIN_DIR: /home/tempie/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by jamesozzie** [comment]
@lucasreina How have you added your Analytics tracking code to your site previously, via one of those plugins or a theme feature? If you are able to locate the source you can then temporarily remove that tag before trying  to setup the Analytics module again.

**Comment by lucasreina** [comment]
@jamesozzie I disabled every plugins and restored codes to the default, but, still don't work.

**Comment by jamesozzie** [comment]
@lucasreina Are you able to check with another site on the the same server to see if your hosting environment could be a factor? If possible check using an incognito window and no plugins. Share any [console errors](https://i.imgur.com/KyLAzgH.png) which appear, along with [XHR responses](https://i.imgur.com/jLBwBdH.png).

**Comment by lucasreina** [comment]
Yesterday, I tried again with a VPN and worked. Maybe was a problem on my internet provider or in my internet settings.

Thanks a lot for your help. God bless





---- On Qua, 14 ago 2019 06:44:06 -0300 notifications@github.com wrote ----



@lucasreina Are you able to check with another site on the the same server to see if your hosting environment could be a factor? If possible check using an incognito window and no plugins. Share any console errors which appear, along with XHR responses.

**Comment by Rustixx** [comment]
I have the same issue with Google Analytics connection. Tried everything in the first post but no success. Please find below Site Health info:

### wp-core ###

version: 5.2.4
site_language: ru_RU
user_language: ru_RU
permalink: /%category%/%postname%.html
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/i/infodomik/vygoda/public_html
wordpress_size: 512,44 MB (537334864 bytes)
uploads_path: /home/i/infodomik/vygoda/public_html/wp-content/uploads
uploads_size: 61,98 MB (64991783 bytes)
themes_path: /home/i/infodomik/vygoda/public_html/wp-content/themes
themes_size: 3,37 MB (3528815 bytes)
plugins_path: /home/i/infodomik/vygoda/public_html/wp-content/plugins
plugins_size: 83,51 MB (87563870 bytes)
database_size: 8,06 MB (8454144 bytes)
total_size: 669,36 MB (701873476 bytes)

### wp-active-theme ###

name: Astra (astra)
version: 1.6.9
author: Brainstorm Force
author_website: https://wpastra.com/about/
parent_theme: none
theme_features: astra_hooks, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, widgets, menus
theme_path: /home/i/infodomik/vygoda/public_html/wp-content/themes/astra

### wp-plugins-active (25) ###

Akismet Anti-Spam: version: 4.0.8, author: Automattic
AMP: version: 1.2.0, author: AMP Project Contributors
BJ Lazy Load: version: 1.0.9, author: Bjørn Johansen, Aron Tornberg, angrycreative
Broken Link Checker: version: 1.11.5, author: Janis Elsts, Vladimir Prelovac
Classic Editor: version: 1.2, author: WordPress Contributors
Duplicator: version: 1.3.8, author: Snap Creek
Glue for Yoast SEO & AMP: version: 0.4.3, author: Joost de Valk
Google Analytics Dashboard for WP (GADWP): version: 5.3.5, author: ExactMetrics
Health Check & Troubleshooting: version: 1.4.2, author: The WordPress.org community
Insert Headers and Footers: version: 1.4.4, author: WPBeginner
Limit Login Attempts Reloaded: version: 2.7.3, author: WPChef
Loco Translate: version: 2.2.0, author: Tim Whitlock
LuckyWP Table of Contents: version: 1.5.2, author: LuckyWP
MailChimp Forms by MailMunch: version: 3.1.2, author: MailMunch
Plugins Garbage Collector: version: 0.10.4, author: Vladimir Garagulya
Recent Posts Widget Extended: version: 0.9.9.7, author: Satrya
RSS for Yandex Turbo: version: 1.18, author: Flector
Site Kit by Google: version: 1.0.0-beta.1.0.1, author: Google
TablePress: version: 1.9.2, author: Tobias Bäthge
UpdraftPlus - Backup/Restore: version: 1.15.3, author: UpdraftPlus.Com, DavidAnderson
VDZ Yandex Metrika Plugin: version: 1.2.12, author: VadimZ
Webcraftic Clearfy – WordPress optimization plugin: version: 1.4.9, author: Webcraftic <wordpress.webraftic@gmail.com>
Webcraftic Robin image optimizer: version: 1.1.5, author: Webcraftic <wordpress.webraftic@gmail.com>
WP Telegram: version: 2.0.19, author: Manzoor Wani
Yoast SEO: version: 9.0.3, author: Team Yoast

### wp-plugins-inactive (6) ###

Cookie Notice: version: 1.2.46, author: dFactory
MailMunch - Grow Your Email List: version: 3.1.1, author: MailMunch
Popup Maker: version: 1.8.0, author: WP Popup Maker
W3 Total Cache: version: 0.9.7.5, author: Frederick Townes
Webcraftic Cyr to Lat reloaded: version: 1.1.1, author: Webcraftic
WP Translitera: version: p1.2.5, author: Evgen Yurchenko

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-0 Q16 x86_64 2018-01-05 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 47 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 47 GB
	imagick::RESOURCETYPE_MEMORY: 24 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.15

### wp-server ###

server_architecture: Linux 3.10.0--generic-shared-3.2-20160306 x86_64
httpd_software: Apache/2.2.29 (Gentoo) mod_dp/0.99.7 PHP/7.3.1
php_version: 7.3.1 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 10
memory_limit: 256M
max_input_time: 60
upload_max_size: 64M
php_post_max_size: 64M
curl_version: 7.62.0 OpenSSL/1.0.2q
suhosin: false
imagick_availability: true
server-headers: 
	server: nginx/1.15.8
	date: Thu, 24 Oct 2019 13:10:03 GMT
	content-type: text/html; charset=UTF-8
	vary: Accept-Encoding
	x-powered-by: PHP/7.3.1
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	last-modified: Tue, 22 Oct 2019 19:22:39 GMT
	link: <https://vygoda.ru/wp-json/>; rel="https://api.w.org/"
	content-encoding: gzip
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.43-84.3-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 401a40ebd5e281cf22215acdc170723a1519aaa9 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/i/infodomik/vygoda/public_html/wp-content
WP_PLUGIN_DIR: /home/i/infodomik/vygoda/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

**Comment by jamesozzie** [comment]
@Rustixx Have you tried to temporarily disable "Insert Headers and Footers" along with Updraft Plus before attempting again, via an incognito browser window?

**Comment by Rustixx** [comment]
Thank you for prompt reply!

I’ve just tried and it doesn’t help.

BR,
RI

**Comment by jamesozzie** [comment]
@Rustixx I just noticed you are also using another analytics plugin. Can you deactivate that plugin before attempting the following:
1. Disconnect the Analytics module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
2. Open Site Kit in a new incognito window 
3. Reconnect the Analytics module (Site Kit > Settings > Connect other services > Analytics)

If that fails do you have any other sites on the same server you can check with, or alternatively can you check with a different theme? It might help to determine the source of the problem.

**Comment by Rustixx** [comment]
Tried this - no success.
Unfortunately I don’t have other sites running Wordpress. I think the problem is in the authorisation process.
The other Analytics plugin uses another type of authorisation (through one-time access code) and working just fine.
Can we debug the authorisation process?

BR,
RI

**Comment by jamesozzie** [comment]
@Rustixx If you are able to use a plugin such as Duplicator you could setup/copy your site elsewhere and check for the same issue, or setup a staging site to troubleshoot with.

There is a new authentication flow in the upcoming plugin version, due for release shortly. With every users WordPress setup and hosting environment varying I can't guarantee that will solve your issue it does reduce the steps involved.

**Comment by Rustixx** [comment]
Thank you for the info. I will wait for the new release.

BTW, then I try to connect Google analytics, the system tells after 2 or 3 seconds "Looks like you don't have Analytics account yet."
Google AdSense also couldn’t connect but with infinite «Loading…» message. May be this helps to locate problem. Look like Analytics and AdSense behave differently for the same authorisation.

BR,
RI
