### ISSUE TITLE
Update Idea Hub widget footer based on selected tab

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3865]
## Feature Description

In #3773 we moved the Idea Hub widget footer into the widget itself (rather than in the "body" of the component).

This brought the widget to be more consistent with others but left a few things to be addressed.

Other related points were raised in the bug bash which can be addressed here as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following changes all apply to the Idea Hub dashboard widget

* The "Updated every 2-3 days" text in the footer should only be displayed on the tab for new ideas as these are the only ideas that are refreshed from the API
* The footer should not be displayed for zero-idea states – except on the new ideas tab (as the previously mentioned message is still relevant)
* Pagination in the footer should not be shown for zero-idea states (only applies to new ideas per above)
* The height of the widget should not change based on the selected tab (#3723)
* The "This may take 24 hours" text should be removed in all cases
* The following changes/exceptions only apply to the zero total ideas state (no new/saved/draft ideas)
	* The widget tabs should not be displayed at all (as is currently)
    * The widget footer should not be displayed at all

## Implementation Brief
* Once https://github.com/google/site-kit-wp/issues/3832 has been merged.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`,
	* Check if selectors have been resolved and there are no errors for each of the following selectors: `getNewIdeas`, `getSavedIdeas` and `getDraftPostIdeas` via the `hasFinishedResolution` and `getErrorForSelector` selectors.
	* `WrappedFooter` should be a variable, with `null` as an initial value instead of a function. The reason being we are passing a function as the value to the `Footer` prop of `Widget` which implies the prop is not null. Thus, even if the function returns `null`, an empty footer will be displayed.
	* Depending on the value of `activeTab`,
		* if it's `new-ideas`, check if there are any errors for the `getNewIdeas` selector and if it has finished resolving, to assign `WrapperFooter` the `Footer` component, passing on the `activeTab` as value to the `tab` prop and `footerText` prop set to the translatable `Updated every 2-3 days` string.
		* if it's `saved-ideas` or `draft-ideas`, check if there are any errors for the `getSavedIdeas` or `getDraftPostIdeas` selectors and if they have finished resolving to assign `WrapperFooter` the `Footer` component.
	* In all instances where the `Footer` component is used in the above bullet points, the `tab` prop should be the `activeTab` value.

### Test Coverage

* No new tests to be added.

### Visual Regression Changes

* N/A

## QA Brief

* Go to the dashboard and verify the following:
  * `Updated every 2-3 days` is shown only for the new ideas tab
  * the footer should be hidden for saved ideas and draft ideas tabs if there is no ideas for those lists
  * the `This may take 24 hours` message is deleted when there are no ideas in the new ideas list
* Double check that requirements from AC are met in the Idea Hub widget.

## Changelog entry

* Show correct footer information based on Idea Hub tab.

**Comment by aaemnnosttv** [comment]
@felixarntz anything to add/change about the ACs here?

**Comment by felixarntz** [comment]
@aaemnnosttv 
> The footer should not be displayed for zero-idea states – except on the new ideas tab (as the previously mentioned message is still relevant)

Is that correct? That's not how we have it in the designs, plus it would be confusing to have this below the message that says "This may take 24 hours".

**Comment by marrrmarrr** [comment]
@felixarntz @aaemnnosttv I think there might be two separate "zero-idea" cases here:
1) right in the beginning after setup
2) if the user clears up the entire list of new prompts (by removing, saving, or starting drafts) 

For (1), I think it doesn't make sense to show the "Updated every 2-3 days" footer.
For (2), it would make sense. (And are we showing an illustration there as well?)

**Comment by felixarntz** [comment]
@marrrmarrr I've added an extra bullet point about (1) to the ACs - cc @aaemnnosttv

**Comment by aaemnnosttv** [comment]
@felixarntz this makes sense although we should avoid conflicting timelines in the zero state and footer like you said. Maybe we should only have the "This may take 24 hours" for the tab-less zero state (no ideas at all)? If they have any ideas, then we would only show the wording in the footer. Does that make sense?

So the only addition to add to the current ACs would be that the "This may take 24 hours"  text would only be shown in the total zero ideas state which should likely only happen after the initial setup.
cc: @marrrmarrr

**Comment by felixarntz** [comment]
@aaemnnosttv That makes sense to me 👍

**Comment by aaemnnosttv** [comment]
@felixarntz updated ACs and reorganized a bit to consolidate the exceptions for that case in one place. On to IB!

**Comment by eugene-manuilov** [comment]
I have updated the `content` property of the Footer element to be `footerText` based on the IB from #3832. Everything else looks good. IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
@eugene-manuilov after triaging some of the remaining tasks for Idea Hub yesterday, we decided that the     ["This may take 24 hours" text should be removed](https://app.asana.com/0/1200491083500938/1200764679034916/f) to avoid confusion and is generally more consistent with our other zero states which don't provide a timeline. Do you think this change is worth including here or we should do this in a separate issue? It seems like it would simplify the implementation a little bit. What do you think?

**Comment by eugene-manuilov** [comment]
Yes, i can take care of it in this ticket.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov – sounds good, I've updated the ACs accordingly 👍

**Comment by wpdarren** [comment]
QA Update: ❌ 

@tofumatt @aaemnnosttv I have a few observations from the AC's

1. `The height of the widget should not change based on the selected tab (Idea Hub dashboard widget layout shift when switching tabs #3723) ` As you can see from my screencast the widget does shift when switching.  taved` and` Drafts` are fine but the New tab does shift height.   

https://user-images.githubusercontent.com/73545194/130246432-9d1cd78c-fd80-440b-99e2-c982d4b1cdd8.mp4

**Verified:**

- On the Idea hub widget on SK dashboard the `Updated every 2-3 days` text is shown only for the new ideas tab. 
[Screenshoot](https://user-images.githubusercontent.com/73545194/130247518-49b29357-f08c-4fd5-bffe-ec2af4d04659.png)
- The footer is hidden for saved ideas and draft ideas tabs if there is no ideas for those lists   [Screenshot](https://user-images.githubusercontent.com/73545194/130247491-3b6096b4-79f4-4ba5-9e21-44e999b79b67.png)
- Confirmed that the message `This may take 24 hours` does not appear when there are no ideas in the new ideas list. 
- Confirmed that the widget footer does not display on all three tabs when no ideas are displayed.  [Screenshot](https://user-images.githubusercontent.com/73545194/130247446-2bab4365-de81-47de-86bb-5d34fe099541.png)
- Confirmed that when there are no `new` ideas, the tabs are hidden  [Screenshot](https://user-images.githubusercontent.com/73545194/130247385-2ed17966-a696-4712-9ecf-74670ed5df3a.png)

**Comment by tofumatt** [comment]
Hmm, I see. Okay, I'll take this issue over and see about a tweak for that one. Thanks 👍🏻

**Comment by tofumatt** [comment]
Actually, I'm not sure I see an issue with the implementation. Maybe the ACs weren't clear enough or didn't account for widget height changing without upsetting the layout, but as-is I can't see any layout shifts happening when the height changes.

The only height shifts I can actually trigger myself are on mobile, but in that case the shifting height isn't as big a deal I think, because it doesn't cause neighbouring widgets to shift:

![2021-08-20 18 09 35](https://user-images.githubusercontent.com/90871/130269888-7a819ef6-b60a-41f4-afb0-53a40364718a.gif)

Is there a particular size I can use to have layout shifts happen on desktop? Otherwise this might actually be okay.

**Comment by wpdarren** [comment]
@aaemnnosttv I think it depends on the widget you have to the left of the Idea hub widget. If there's no data in the search console widget to the left then the Idea hub widget does shift.  If you do not feel this is an issue that's fine, but the AC does say `the height of the widget should not change based on the selected tab`

**Comment by aaemnnosttv** [comment]
@wpdarren @tofumatt – it works correctly on tabs that are in a non-zero state, the height is not preserved in the zero state. I did not test all tabs in each state but I'm guessing this is the problem.

https://user-images.githubusercontent.com/1621608/130648456-6a1b68d6-8a21-49ba-a3eb-67949a32df6f.mp4

The problem is that the footer isn't being rendered at all in this case (as intended visually) but this affects the height since there is one footer for the widget and 3 separate content areas.

I'll see what I can do here.

**Comment by wpdarren** [comment]
QA Update: ✅ 

This works perfectly now! 

**Verified:**

- The message `Updated every 2-3 days` is shown only for the new ideas tab.
- The footer is hidden for saved ideas and draft ideas tabs
- The message `This may take 24 hours message` is deleted when there are no ideas in the new ideas list.
- Confirmed the requirements from AC are met in the Idea Hub widget.
