### ISSUE TITLE
Distinguish already verified plugin users and users who verify their site during plugin setup

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#387]
## Feature Description
Let's add custom dimensions to note whenever a plugin user is already verified vs when new sites get verified and added to Search Console. 

1) Trigger: API request to fetch sites for that user (calling WebResource: list method from Verification API)	
Event category: verification_setup
Event action: verification_check_true

2) Trigger: API request to fetch sites for that user (calling WebResource: list from Verification API)
Event category: verification_setup
Event action: verification_check_false 

3) Trigger: verifying the site (calling insert method from Verification API)
Event category: verification_setup
Event action: verification_insert_tag

4) Trigger: Adding the site to SC (calling Sites#add method from SC API)
Event category: search_console_setup	
Event action: add_new_sc_property
		
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Calling WebResource: list method from Verification API and getting True as a response will fire verification_check_true event
* Calling WebResource: list method from Verification API and getting False as a response will fire verification_check_false event
* Calling insert method from Verification API will fire verification_insert_tag event
* Calling Sites#add method from SC API will fire add_new_sc_property event

## Implementation Brief

* User helper `sendAnalyticsTrackingEvent()` to trigger tracking events.

* When requesting to `siteverification-list` in site-verification.js
https://github.com/google/site-kit-wp/blob/1d41a5161b99aaae04af63ff7a3d5b68ecfe26e6/assets/js/components/setup/site-verification.js#L70 
Call `sendAnalyticsTrackingEvent( 'verification_setup', 'verification_check_true' )` if `verified` in the response is `true`.
Call `sendAnalyticsTrackingEvent( 'verification_setup', 'verification_check_false' )` if `verified` in the response is `false`.

* After calling `insertSiteVerification()`, which makes request to `siteverification` endpoint, if `response.updated` is `true` 
Call `sendAnalyticsTrackingEvent( 'verification_setup', 'verification_insert_tag' )` if `verified` in the response is `true`.

* In `insertPropertyToSearchConsole()` of the search console component https://github.com/google/site-kit-wp/blob/1d41a5161b99aaae04af63ff7a3d5b68ecfe26e6/assets/js/components/setup/search-console.js#L129
Call `sendAnalyticsTrackingEvent( 'search_console_setup', 'add_new_sc_property' )`

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Implementation brief looks good!

**Comment by felixarntz** [comment]
QA is good!

**Comment by marrrmarrr** [comment]
I confirmed these are now recored in GA. LGTM
