### ISSUE TITLE
Analytics activation Problem in G Site Kit (Wordpress)

### ISSUE THREAD

**Issue by SintoJoseph** [google/site-kit-wp#388]
I tried analytics activation in G Site Kit installed in my wordpress but I am not able to fetch my existing analytic for my site the fetching is taking for ever. Please the snapshot attached.
![Gsite kit analytics activation-1](https://user-images.githubusercontent.com/53149638/62708265-a57a2780-ba10-11e9-94f0-f8507b08b6e1.JPG)

![Gsite kit analytics activation-2](https://user-images.githubusercontent.com/53149638/62708263-a57a2780-ba10-11e9-9874-c8ba9566de61.JPG)

**Comment by jamesozzie** [comment]
@SintoJoseph Can you attempt the steps in ticket #386, hopefully some of the steps within that issue will allow you to connect.

**Comment by SintoJoseph** [comment]
Hi,
  I disabled all plugins and tried the analytic activation and it worked
thanks.
Thanking You,

Regards,

[image: looking for desiring bride]

Sinto Joseph

Entrepreneur | YouTuber

Mobile No.: +91-8197452685

Website: www.finysel.com

Live a Life you Love it all that matters.

Connect or follow me on:

[image: facebook.png] <https://www.facebook.com/sinto.joseph2> [image:
youtube.png] <http://www.youtube.com/c/SintoJosephnet?sub_confirmation=1>
[image:
twitter.png] <https://twitter.com/SintoJoseph> [image: google-plus.png]
<https://plus.google.com/u/0/101540631261441440343> [image: pinterest.png]
<https://in.pinterest.com/finysel/> [image: linkedin.png]
<https://in.linkedin.com/in/sinto-joseph-4484b31b>
