### ISSUE TITLE
Dashboard search visitors widget uses incorrect condition for whether to display zero data state

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3880]
## Bug Description

There's a problem with the `DashboardSearchVisitorsWidget`, related to the improvements in #3064: Similar to how `DashboardGoalsWidget` does, that widget should only render in a `WidgetZeroData` state if there is actually no data at all, which in this case cannot be determined based on the regularly used query of the widget alone, since that widget only queries the users from Search. We need to make this check based on whether no users at all were present in the time, otherwise it can lead to incorrect and confusing UX (see below).

<img width="1339" alt="Screen Shot 2021-08-16 at 11 26 26 AM" src="https://user-images.githubusercontent.com/3531426/129611857-29189632-b3ba-47be-bc6d-97b2791d1a56.png">
The experience here is quite confusing since the All Traffic widget shows data (because there _is_ data, even if super little), while at the same time the small widget which should display the visitors from Search displays the "zero data" blue box below. There is data, so it's not like we're waiting for data in this scenario.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DashboardSearchVisitorsWidget` should also get the number of total users in the period and only based on that show or not show the `WidgetZeroData` UI.
    * In other words, if there has been e.g. 1 user on the site in the past x days, but 0 of them came from Search, the widget should display 0 like it would display any other value. Only if there are no users at all, it should render in "zero data" state.

## Implementation Brief
* Using `assets/js/modules/analytics/components/dashboard/DashboardSearchVisitorsWidget.js`,
	* Query the total users via the `getReport` selector, passing the values for:
		* startDate
		* endDate
		* url
		* compareStartDate
		* compareEndDate
		* metrics: Array containing an object as follows:
			```js
			{
				expression: 'ga:users',
				alias: 'Total Users',
			}
			```
	* Update the condition to display the `WidgetReportZero` component if the total users is zero in addition to the existing conditions.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* To recreate the issue you will need to cover the following scenarios, and observe the `Unique Visitors from Search` widget under the search funnel section of the dashboard:
  * Zero total users, including from search (should display 'zero data' state)
  * One or more total users, but **none** from search (should display 0)
  * One or more visitors from search (should display the number)

## Changelog entry

* Fix Dashboard Search Widget zero state bug.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  ❌ 

@johnPhillips  I have a test site that has zero search but does have user data in analytics in other channels. When I go to Site Kit Dashboard, an error appears.  Not sure if this helps, but the error does not appear when you have search data. If you would like access to this site please let me know 

![image](https://user-images.githubusercontent.com/73545194/132632750-b35520cd-d13c-4c08-ba87-fd5e717544dc.png)

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

Observed the `Unique Visitors from Search` widget under the search funnel section of the dashboard:

Zero total users, including from search (should display 'zero data' state)
One or more total users, but none from search (should display 0)
One or more visitors from search (should display the number)

![image](https://user-images.githubusercontent.com/73545194/133036611-9df89a4f-0a05-4c34-91dc-3b1dc20cc67d.png)

![image](https://user-images.githubusercontent.com/73545194/133036629-6e04c154-bf39-4485-a8e8-14f1fbf0e22a.png)

@johnPhillips I did notice that the graph underneath the `Unique Visitors from Search` widget was not displaying properly, but I think we have an issue for this already. I will double check and if not, create one. I did not want to hold this up because of we are looking to release today.
