### ISSUE TITLE
PHPUnit on WordPress nightly is broken

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3883]
## Bug Description

Recently PHPUnit tests started failing on WordPress nightly due to a recently added dependency requirement that isn't provided when using the WP testing library standalone.

Tests fail like so: https://github.com/google/site-kit-wp/pull/3882/checks?check_run_id=3343479892#step:10:11

```
> phpunit
Error: The PHPUnit Polyfills library is a requirement for running the WP test suite.
You need to run `composer update` before running the tests.
Once the dependencies are installed, you can run the tests using the Composer-installed version of PHPUnit or using a PHPUnit phar file, but the dependencies do need to be installed whichever way the tests are run.

Warning: require_once(/tmp/wordpress-tests-lib/includes/../../../vendor/yoast/phpunit-polyfills/phpunitpolyfills-autoload.php): failed to open stream: No such file or directory in /tmp/wordpress-tests-lib/includes/bootstrap.php on line 106

Fatal error: require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/../../../vendor/yoast/phpunit-polyfills/phpunitpolyfills-autoload.php' (include_path='.:/usr/share/php') in /tmp/wordpress-tests-lib/includes/bootstrap.php on line 106
PHP Warning:  require_once(/tmp/wordpress-tests-lib/includes/../../../vendor/yoast/phpunit-polyfills/phpunitpolyfills-autoload.php): failed to open stream: No such file or directory in /tmp/wordpress-tests-lib/includes/bootstrap.php on line 106
PHP Fatal error:  require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/../../../vendor/yoast/phpunit-polyfills/phpunitpolyfills-autoload.php' (include_path='.:/usr/share/php') in /tmp/wordpress-tests-lib/includes/bootstrap.php on line 106
Script phpunit handling the test event returned with error code 255
```

## Additional Context

WP trunk has started requiring PHPUnit polyfills and now relies on package to be present (like a peer dependency), otherwise it will fail.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHPUnit tests for WP nightly should no longer fail due to missing dependencies

## Implementation Brief

* Add `yoast/phpunit-polyfills` as a dev dependency
* Update installed WP and `wp-phpunit` packages to the latest versions (not required to fix but should be kept up to date (previously locked at `5.7`)
* Merge https://github.com/google/site-kit-wp/pull/3884

### Test Coverage

* No added tests are necessary

### Visual Regression Changes

* N/A

## QA Brief

* PHPUnit tests for WP nightly should run completely now and finish successfully

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
@eugene-manuilov I have assigned this to `QA:Eng` but if this not the case please provide additional information in the QAB.
