### ISSUE TITLE
Idea hub bug - If visit dashboard with hash in Url then get console error

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3887]
## Bug Description

If visiting the Site Kit dashboard with a hash in the Url for the idea Hub Widget e.g. `admin.php?page=googlesitekit-dashboard#new-ideas`
*BUT* there are no results from Idea Hub

![emptystate](https://user-images.githubusercontent.com/8496063/129718447-b139fd6e-f5f3-41fc-b7cc-441c76edae8b.png)

Then we get this console error
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at googlesitekit-modules-idea-hub.js:3968
```

This happens here
https://github.com/google/site-kit-wp/blob/8b0551bf0fd37befbed8db9d7eb89f6241e0c7d8/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js#L93

```
global.window.scrollTo( {
    top: getIdeaHubContainerOffset(
        ideaHubContainer.current.getBoundingClientRect().top
    ),
    behavior: 'smooth',
} );
```

This should only run if `ideaHubContainer.current` exists

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this as fixed as part of another issue 👍
