### ISSUE TITLE
Issue: not enable google site kit plugin on step 2

### ISSUE THREAD

**Issue by Anil-Chaudhary-netclues** [google/site-kit-wp#390]
## Steps to reproduce

1. Go to 'Site kit'
2. Click on 'First step 1: Create Client ID'
3. generate a code and we have and proceed then
4. next step when we go ahead allow/allow/next click it redirect to page and then nothing happen ?

## Screenshots
Please see screenshot that i have attached.

## Additional Context

 - PHP Version: 5.6
 - Browser : Chrome, Mozilla
 - Wordpress Version : 5.2.2

i have all the try but i am not success. Please help as soon as possible.

**Comment by jamesozzie** [comment]
@Anil-Chaudhary-netclues Can you please attempt the steps below in order to get Site Kit connected:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png).

If the above fails to resolve your issue can you please share the following:
- Any console errors that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by Anil-Chaudhary-netclues** [comment]
Hi jamesozzie,
Thanks for Quick Reply.

Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit) - i am not see this step just seeing only dashboard. how can i do that.
Also, i have try all the disable plugin and check
![not seeing anything other](https://user-images.githubusercontent.com/53938165/62778163-4e865800-bacd-11e9-9fbf-030e55cfbc24.png)
 incognito window but no luck.

**Comment by Anil-Chaudhary-netclues** [comment]
Here, on more screenshot
![site_url](https://user-images.githubusercontent.com/53938165/62778255-88eff500-bacd-11e9-803a-16e4f3b8436c.png)

**Comment by jamesozzie** [comment]
@Anil-Chaudhary-netclues I can see you also have some WooCommerce plugins, can you try to disable those while attempting again? 

If that fails please share your [Site Health](https://i.imgur.com/Rtkmsba.png) information.

**Comment by Anil-Chaudhary-netclues** [comment]
Okay sure. i will do that and let you know with site Heath information.

**Comment by Anil-Chaudhary-netclues** [comment]
![step2_not_verify](https://user-images.githubusercontent.com/53938165/62847797-ce8f0680-bcf5-11e9-8829-cfaed43fddea.png)
Hi,
I have try Today on my same beta website but still not done and we are still getting error. i have inactive all the plugin but no luck.
Please look at below site Health:
`
### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/notarypubliccaym/public_html/beta
wordpress_size: loading...
uploads_path: /home/notarypubliccaym/public_html/beta/wp-content/uploads
uploads_size: loading...
themes_path: /home/notarypubliccaym/public_html/beta/wp-content/themes
themes_size: loading...
plugins_path: /home/notarypubliccaym/public_html/beta/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: RedSeal
version: 1.5.4
author: CreatopusThemes
author_website: https://themeforest.net/user/creatopus
parent_theme: none
theme_features: title-tag, widgets, menus, post-thumbnails, post-formats, automatic-feed-links, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /home/notarypubliccaym/public_html/beta/wp-content/themes/redseal

### wp-themes (4) ###

RedSeal Child Theme: version: 1.3.0, author: CreatopusThemes
Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (1) ###

Site Kit by Google: version: 1.0.0-beta.1.0.2, author: Google

### wp-plugins-inactive (26) ###

Advanced CF7 DB: version: 1.7.2, author: Vsourz Digital
Akismet Anti-Spam: version: 4.1.2, author: Automattic
All In One SEO Pack: version: 3.2.2, author: Michael Torbert (latest version: 3.2.3)
All In One WP Security: version: 4.3.9.4, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy
Booked: version: 2.2.4, author: Boxy Studio
Breadcrumb Trail: version: 1.1.0, author: Justin Tadlock
Contact Form 7: version: 5.1.4, author: Takayuki Miyoshi
Easy WP SMTP: version: 1.3.9.1, author: wpecommerce, alexanderfoxc
GDPR Cookie Consent: version: 1.7.8, author: WebToffee
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Jquery Validation For Contact Form 7: version: 4.1, author: Dinesh Karki
Justified Gallery: version: 1.4.2, author: Damian Góra
LayerSlider WP: version: 6.8.4, author: Kreatura Media (latest version: 6.9.0)
Mailchimp for WordPress: version: 4.5.3, author: ibericode
Meta Box: version: 4.18.4, author: MetaBox.io (latest version: 5.0.1)
One Click Demo Import: version: 2.5.1, author: ProteusThemes (latest version: 2.5.2)
RedSeal: version: 1.5.4, author: CreatopusThemes
Redux Framework: version: 3.6.15, author: Team Redux
Testimonials Slider and Showcase: version: 1.2.4, author: RadiusTheme
VC Templates Import & Export: version: 1.0.0, author: Tomiup
Widget Importer & Exporter: version: 1.5.5, author: ChurchThemes.com
WooCommerce: version: 3.6.5, author: Automattic
WordPress Importer: version: 0.6.4, author: wordpressdotorg
WPBakery Page Builder: version: 5.7, author: Michael M - WPBakery.com (latest version: 6.0.5)
WP Migrate DB: version: 1.0.11, author: Delicious Brains
WP Slick Slider and Image Carousel: version: 1.7.1, author: WP OnlineSupport (latest version: 1.8)

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.25.12.el7.x86_64 x86_64
httpd_software: Apache
php_version: 5.6.40 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 20M
php_post_max_size: 256M
curl_version: 7.65.3 OpenSSL/1.0.2s
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.27-cll-lve
client_version: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/notarypubliccaym/public_html/beta/wp-content
WP_PLUGIN_DIR: /home/notarypubliccaym/public_html/beta/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

**Comment by Anil-Chaudhary-netclues** [comment]
Hi jamesozzie,
Hope you are doing well.
We are waiting for your response. can you please look this issue and help us please,

Thanks!

**Comment by jamesozzie** [comment]
@Anil-Chaudhary-netclues Can you temporarily disable the following plugins, before attempting to setup Site Kit again? While you have tested deactivating already please do so using a Chrome browser and incognito window. 
- Booked
- All in one WP Security
- Redux Framework
- WooCommerce related plugins

If that fails to resolve your issue please share the following:
- Any [console errors](https://i.imgur.com/KyLAzgH.png) which appear
- Any [XHR responses](https://i.imgur.com/jLBwBdH.png)
- Any security/firewall software on your web host (such as ModSecurity)

**Comment by Anil-Chaudhary-netclues** [comment]
Hi,
I have already test with all the plugin 'InActive' and again i am here test again with 'InActive' all the plugin and just Google Kit plugin active and do the process. but i am not found anything in console. and find a two request in XHR response. so please find a attached screenshot.
Note: hubspot plugin is actived in my main Domain not in beta.

Please Help!!.

![again_not_success](https://user-images.githubusercontent.com/53938165/62940412-278f9500-bdf1-11e9-97ac-e240734f88ad.png)

**Comment by jamesozzie** [comment]
Thanks for the update, can you also share the following:
- The other XHR response details (I can see 2 from the screenshot you provided)
- Any security or Firewall plugins

In additional your theme has some features in built which connect to Google services. If you have a staging site can you test with another theme?

**Comment by Anil-Chaudhary-netclues** [comment]
Hello jamesozzie,
Thanks for help.
My issues is resolve now. Problem in on My Server "Mod Security". when security disable it worked.

Thanks!!
