### ISSUE TITLE
IdeaHub: Draft Created Message Shows on Drafts Tab Briefly

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#3902]
## Bug Description

The draft created message from new tab is also shown on the drafts tab if we switch there fast enough.

## Steps to reproduce

1. In new tab, create a draft.
2. Switch to drafts tab quickly
3. Notice that it says Draft Created before changing to View Draft

https://user-images.githubusercontent.com/373931/129885002-52251398-299c-4977-85af-da85d36fba1f.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The timeout on the "Draft created" message in the Idea Hub widget (after successfully creating a draft) should be immediately stopped/cleared if the user navigates to another tab in the widget. It basically should be ensured that this contextual hint is no longer visible once seeing the same idea in another tab (realistically the "Drafts" tab, since that's where such an idea would land then).

## Implementation Brief
* Using `assets/js/modules/idea-hub/datastore/idea-state.js`, add a new action `removeActivities` which has a mandatory parameter, `activityType`.
* `removeActivities` should remove any item in the `activities` state variable which has the same value as `activityType` parameter.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`, dispatch the `removeActivities` action within the `handleTabUpdate` passing `IDEA_HUB_ACTIVITY_CREATING_DRAFT` as value for the `activityType` parameter.

### Test Coverage
* Add tests for the newly added action.

### Visual Regression Changes
* N/A

## QA Brief

* Follow the repro steps and ensure you can no longer see `Creating draft` / `Draft created` messages in the `Drafts` tab

## Changelog entry

* Update the IdeaHub widget to not display "Draft created" message on the draft tab.

**Comment by aaemnnosttv** [comment]
@ivankruchkoff any idea where the delay between the created activity and `postEditURL` becoming available is?

**Comment by ivankruchkoff** [comment]
> @ivankruchkoff any idea where the delay between the created activity and `postEditURL` becoming available is?

Here's the cause:
https://github.com/google/site-kit-wp/blob/79bc587/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L54

https://github.com/google/site-kit-wp/blob/79bc587/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L106-L109

**Comment by asvinb** [comment]
@eugene-manuilov IB updated as per your comments. I think we can definitely clear the draft activity regardless of the tab type :)
About hiding the tab content via CSS, true we are doing that. However shouldn't the component unmount itself when it's being remove from the "New" tab? https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/NewIdeas.js#L91-L105 and then mounted again when it's created in the "Drafts" tab? https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/DraftIdeas.js#L90-L100

**Comment by eugene-manuilov** [comment]
> However shouldn't the component unmount itself when it's being remove from the "New" tab? ... and then mounted again when it's created in the "Drafts" tab? ...

Yes, it should, but it will happen on timeout, so the user can already switch the tab by the time the timeout callback is executed.

IB ✔️

**Comment by ivankruchkoff** [comment]
The IB doesn't quite address the issue, due to race condition
Should I continue with the tests for the PR @eugene-manuilov https://github.com/google/site-kit-wp/pull/4412/files

See the attached recording:



https://user-images.githubusercontent.com/373931/143661847-f69315cc-e660-4c9b-ad88-fcce5447876a.mp4


1. We click the start a draft post button.
2. https://github.com/google/site-kit-wp/blob/17d8abed9005ea0cac88280512d3de6cc6e6e964/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L100
3. We asynchronously start creating a draft
4. https://github.com/google/site-kit-wp/blob/17d8abed9005ea0cac88280512d3de6cc6e6e964/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L101
3. We change tab to drafts, removing the `creating draft` status in the process
4. https://github.com/google/site-kit-wp/pull/4412/files#diff-4a00db56a76ea7471b30f647423e8727790fd8e404f94cfb3e87e3769cb8017dR242
5. The draft post is created, shows up as `Draft created` in the drafts tab
6. https://github.com/google/site-kit-wp/blob/17d8abed9005ea0cac88280512d3de6cc6e6e964/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L102
7. https://github.com/google/site-kit-wp/blob/17d8abed9005ea0cac88280512d3de6cc6e6e964/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L149-L152
8. Timer expires, activity is removed.
9. https://github.com/google/site-kit-wp/blob/17d8abed9005ea0cac88280512d3de6cc6e6e964/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L54
10. View draft is shown.
11. https://github.com/google/site-kit-wp/blob/17d8abed9005ea0cac88280512d3de6cc6e6e964/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js#L154-L229

**Comment by eugene-manuilov** [comment]
Ok, if the proposed IB doesn't work then we need to find another approach. How about moving the timer to the `createIdeaDraftPost` action and resetting the timer ID when the `removeActivities` action is called (in the controller)?

**Comment by ivankruchkoff** [comment]
@eugene-manuilov I don't like the idea of putting presentation logic in an action.

I went down the path of not showing `DRAFT_CREATED` in the drafts tab, which gives us the following experience:

https://user-images.githubusercontent.com/373931/145134707-3984ecc6-9170-4198-a4f8-35dd53a06417.mp4

Which still allows for the temporary messaging on the `New` tab when we switch back to it within the two seconds.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When following the steps you can no longer see `Creating draft` `Draft created` messages in the Drafts tab.

https://user-images.githubusercontent.com/73545194/145410277-5bcbde7e-0cfa-46a0-a9e7-0a4713fadfbd.mp4
