### ISSUE TITLE
Show tooltips for Idea Hub icon buttons

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3906]
The icon buttons in the Idea Hub widget should have tooltips, per the [Figma file](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A2653).

See https://app.asana.com/0/1200491083500938/1200625443460145/f

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The icon buttons in the Idea Hub widgets should have tooltips using the same approach and style that is already present for e.g. the global help menu. Here are the labels to use:
    * "Save for later" (for the pin icon in the "New" tab)
    * "Dismiss" (for the x icon in the "New" tab)
    * "Remove from saved" (for the "unpin" icon in the "Saved" tab)
    * "Start a draft post" (for the create draft icon in both "New" and "Saved")

## Implementation Brief

* Inside `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js`:
  * Add a `title` prop with value "Start a draft post" to the `IDEA_HUB_BUTTON_CREATE` button
  * Make sure you use appropriate i18n, i.e. `__( 'Start a draft post', 'google-site-kit' )`
* Repeat for the other buttons, adding the labels in the AC as `title` attributes.
* This should force the `Button` component to render with a tooltip. 

### Test Coverage

* No new tests required.

### Visual Regression Changes

* It's possible that VRT images relating to the DashboardIdeasWidget component might need updating.

## QA Brief

* Idea Hub Icon Buttons will have tooltip with the texts from AC. 

## Changelog entry

* Add tooltips for action buttons in the Idea Hub dashboard widget.

**Comment by felixarntz** [comment]
@marrrmarrr The one label that wasn't present in the Figma files is the one for removing an idea from being saved (i.e. "unsaving" it). However "unsave" is a weird term, and we never formally aligned on a proper word for this action. Thoughts? I just used "Unsave idea" for now, but that may not be appropriate, so let's finalize the ACs.

Also @aaemnnosttv let me know if you have suggestions for that.

**Comment by eclarke1** [comment]
My suggestion would be 'Remove from saved ideas', I think 'Remove from saved' could work, but as we have a lot of users who are non-native speakers, it would just make it clearer to everyone if we used 'Remove from saved ideas' @aaemnnosttv what do you think?

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr I would say:
- "Save for later"
- "Remove from saved"
- "Dismiss"
- "Create draft post for idea" (this one needs the most clarification I think, hence the longest)

**Comment by marrrmarrr** [comment]
Ok, let's keep it as "remove from saved". I think there's enough context to help people understand what actually is happening.

**Comment by felixarntz** [comment]
@aaemnnosttv "Create draft post for idea" reads a bit too technical and verbose. Why not "Start a draft"? Or "Start a draft for idea"? Although IMO the "for idea" is unnecessary, we don't include the term "idea" in the other labels either and the context should make that clear.

**Comment by aaemnnosttv** [comment]
> Why not "Start a draft"? Or "Start a draft for idea"?

@felixarntz my thought is that what kind of draft is a bit ambiguous. We updated the IH CTAs to be more specific to posts so I think it makes sense to use consistent terms here as well. I would be happy to use "Start a draft post" if that works for you?

The reason I chose "create" though is that "start" to me means more like you are about to go to the editor as well (as in start _now_), where as the action is more of a "create a draft in the background but start on it whenever you want"; it sounds less disruptive/demanding. My thought is that users will be more likely to create drafts if they don't need to take action on it right away.

**Comment by felixarntz** [comment]
@aaemnnosttv "Start a draft post" sounds good. I also agree with your argumentation about using "create" instead of "start", however I'm on the other hand concerned that "create" sounds a bit more passive maybe? This may really be just my impression, but when I read "start", I think more of me starting it, but when I read "create", I read it as WordPress will create it for me - which is also technically accurate, but it makes me wonder whether people think it'll actually populate it with content or something.

**Comment by aaemnnosttv** [comment]
> when I read "create", I read it as WordPress will create it for me - which is also technically accurate, but it makes me wonder whether people think it'll actually populate it with content or something.

@felixarntz that's a good point, I didn't make that association. In that case, "start" is probably the simplest "safe" word to use here 👍

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update ✅ 

The icon buttons in the Idea Hub widgets display tooltips:
- "Save for later" (for the pin icon in the "New" tab)
- "Dismiss" (for the x icon in the "New" tab)
- "Remove from saved" (for the "unpin" icon in the "Saved" tab)
- "Start a draft post" (for the create draft icon in both "New" and "Saved")

https://user-images.githubusercontent.com/73545194/132019233-f5bdecc1-d8fd-47f3-86d9-827334c51b1f.mp4

**Comment by eugene-manuilov** [comment]
@wpdarren I think that `X` there is a well-known pattern to close something and people won't need a tooltip for it. But we need to make sure that it has the appropriate ARIA label to let screen readers read it correctly.
