### ISSUE TITLE
Update Idea Hub module description with more clear message

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3908]
The Idea Hub module description should be clarified that the suggestions come from **user-invoked** search queries.

See https://app.asana.com/0/1200491083500938/1200755649650592/f

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub module description should be updated to: _Idea Hub suggests what you can write about next, from actual questions people asked on Google Search_ 
* The Idea Hub widget description on the main dashboard should be updated to: _Ideas to write about, from actual questions people asked on Search_
* The hard-coded configuration in Storybook re-including the description should be updated accordingly as well. Also, that Storybook configuration includes a homepage URL which is actually incorrect since Idea Hub does not have a homepage to point to, so that entry should be removed / emptied.

## Implementation Brief

* Inside `includes/Modules/Idea_Hub.php`, change the module description text inside the `setup_info` method to be:
  _Idea Hub suggests what you can write about next, from actual questions people asked on Google Search_
* In `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`, update the heading text to read:
  _Ideas to write about, from actual questions people asked on Search_
  * You will probably need to add some simple CSS for larger viewports to get the `Experimental` badge to display nicely with the heading, for example by adding `display: inline-flex` to `.googlesitekit-idea-hub__title` (see images below).
* Update `assets/js/modules/idea-hub/components/setup/Setup.stories.js` as per the ACs:
  * Update the hard-coded description to match the module description above
  * Remove the `homepage` value 
 

#### Experimental badge wraps on larger viewports 
![Screenshot 2021-08-26 at 17 39 59](https://user-images.githubusercontent.com/2470911/131002708-7eb8d167-25d3-405a-a3f0-11f8b06d2be3.png)

#### Example solution with `inline-flex`
![Screenshot 2021-08-26 at 17 40 10](https://user-images.githubusercontent.com/2470911/131002709-0c249c9c-794f-4eda-a66b-3a0c34d08931.png) 

### Test Coverage

* No new test coverage required.

### Visual Regression Changes

* Some images may need updating to reflect the changes in the UI.

## QA Brief

* Without Idea Hub activated, verify that the Idea Hub module description is as per the ACs above. The description is visible in the Idea Hub CTA on the Site Kit dashboard, and in Storybook (`?path=/story/modules-idea-hub-components-dashboardcta--default-dashboard-cta`)
* Connect and activate the Idea Hub module
* Now verify that the heading of the dashboard widget is as per the ACs.

## Changelog entry

* Update descriptions for Idea Hub module and widget.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Idea Hub module description is updated to: `Idea Hub suggests what you can write about next, from actual questions people asked on Google Search` 

![image](https://user-images.githubusercontent.com/73545194/131678833-4e602f18-973f-4005-8b6e-b33332268eea.png)

- When Idea Hub is connected. The Idea Hub widget description on the main dashboard is updated to: `Ideas to write about, from actual questions people asked on Search`

![image](https://user-images.githubusercontent.com/73545194/131680310-7b271379-1675-4af7-b65f-80d27d2db087.png)

- Verified that the changes were appearing in Storybook.
