### ISSUE TITLE
Idea Hub post annotation only shown on drafts

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#3909]
## Bug Description

When you trash a draft post, the idea isn't shown in the trash.

## Steps to reproduce

1. Create a draft from an idea, notice the idea name is in the status.
2. Trash the post, idea name is not shown.
3. Restore the trashed post, and see the idea is shown again.

## Recording

https://user-images.githubusercontent.com/373931/130031511-4fe045a8-c7f4-4f7a-a4dc-d3ac43fadcb7.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub annotation added to Idea Hub created posts in the post list table should be shown for posts of all statuses, not only drafts (e.g. trashed, future, pending, private, etc) – how it is added depends on the post status, post state, and post title
* For `draft` posts with no title only, the state should be replaced by `Idea Hub Draft “{idea-name}”`
* For all other post statuses OR drafts that have titles, the annotation should be simplified to `inspired by Idea Hub`
* For all post statuses (except drafts with no title)
	- If there is already content for the post state (e.g. [`scheduled`](https://github.com/WordPress/WordPress/blob/baa81b67d19e29be29d0ac49c9bede316ab8f80a/wp-admin/includes/template.php#L2210)), combine the original content of the post state by appending the annotation like so: `{post-state}, {idea-hub-annotation}`
	- If no content exists for the post state, the annotation becomes the post state, rather than appending to it
* See https://github.com/google/site-kit-wp/pull/4061#discussion_r712384583 for reference

## Implementation Brief

* In `includes/Modules/Idea_Hub.php` -> `register_persistent()` -> `display_post_states()`:
* 1) Remove the check for post status:
https://github.com/google/site-kit-wp/blob/38ae6cb09c82acea56a5bde768028d93b3cc6580/includes/Modules/Idea_Hub.php#L165-L167

* 2) Instead of adding our message to the `draft` post state, add it for the current post's post state
https://github.com/google/site-kit-wp/blob/38ae6cb09c82acea56a5bde768028d93b3cc6580/includes/Modules/Idea_Hub.php#L173

```php
$post_states[$post->post_status ] = ... 
```

* 3) If the `post_title` is empty `"" === $post->post_title`, use the current message `sprintf( __( 'Idea Hub Draft “%s”', 'google-site-kit' ), $idea['text'] );`, otherwise if a title is set, set the message to `inspired by Idea Hub`:
https://github.com/google/site-kit-wp/blob/38ae6cb09c82acea56a5bde768028d93b3cc6580/includes/Modules/Idea_Hub.php#L173

### Test Coverage

* Update test name and test in `tests/phpunit/integration/Modules/Idea_HubTest.php::test_draft_labels()`

https://github.com/google/site-kit-wp/blob/38ae6cb09c82acea56a5bde768028d93b3cc6580/tests/phpunit/integration/Modules/Idea_HubTest.php#L97-L147
### Visual Regression Changes

* N/A

## QA Brief

* Create an idea hub draft, ensure that the posts list table shows its status message as `Idea Hub Draft ...`.
* Set a title and update the draft, ensure that the status says `inspired by Idea Hub`.
* Trash the post and ensure it still has the correct status message.

<img width="504" alt="Screen Shot 2021-09-16 at 4 11 28 PM" src="https://user-images.githubusercontent.com/373931/133618559-72629630-25ef-4ed5-b8e0-7fcb62f4400e.png">

## Changelog entry

* Update the post state for Idea Hub posts and enable it for posts of all statuses.

**Comment by marrrmarrr** [comment]
@aaemnnosttv if the post is already published, presumably the author has selected the title they thought is most relevant, so for published posts we can keep a much shorter generic annotation, e.g. "inspired by Idea Hub" or "based on a suggestion from Idea Hub".

**Comment by eugene-manuilov** [comment]
@marrrmarrr @aaemnnosttv I remember we discussed the possibility to add an icon to the title for posts created using the Idea Hub suggestions. Did we decide not to do it? We can use the Idea Hub module icon and not display additional text if the post is not drafted. If a user wants to see more details, they can open the editor and see which idea has been used for that post.

For example, something like this:
![2021-08-31_15-16](https://user-images.githubusercontent.com/873049/131501334-d8d7503b-51c6-4a26-9d4e-cece20e65b0c.png)

**Comment by marrrmarrr** [comment]
@eugene-manuilov I'm not sure how familiar users will be in the beginning with the Idea Hub icon, and if they would understand why it's there / what it means. I'd suggest adding the short text for now and revisit to add the icon at a later stage, a few months after we've rolled the feature out to 100% of eligible sites.

**Comment by aaemnnosttv** [comment]
Thanks @marrrmarrr – I like "inspired by Idea Hub" since that relates back to language we use in the CTAs and sounds a little better than "based on an idea from". I've updated the ACs accordingly so I think this can move forward to IB now. If we decide to tweak the wording we can easily do that while in progress 👍

**Comment by eugene-manuilov** [comment]
@ivankruchkoff I think we should use the `inspired by Idea Hub` message for all post statuses, except for drafted posts. Because based on the current logic in IB, if the post has pending review or private status, then the annotation message should be "Idea Hub **Draft** ..." which looks odd since the post isn't drafted. cc @aaemnnosttv @marrrmarrr

**Comment by aaemnnosttv** [comment]
@eugene-manuilov good point – I think we should probably tweak the wording instead based on the presence of a title which would only be added by the user, at which point the idea name wouldn't be needed anymore for the same reason we weren't going to show it when published.

@marrrmarrr how about we tweak the logic here to show `inspired by Idea Hub` for any post with a title regardless of status. If there is no title, we can show something like `Idea Hub suggestion "the idea name/text"` (maybe another word would be better for 'suggestion' here, but "idea" seems a bit off/repetitive. maybe 'question'?) Not to get overly verbose, we could potentially prefix it to say "**for** Idea Hub suggestion '{name}'". Thoughts?

**Comment by marrrmarrr** [comment]
SGTM for using "inspired by Idea Hub" for all posts with a title updated by the user (including posts in draft state with an updated title).

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
@ivankruchkoff – I've updated the AC's per @felixarntz 's comment on the PR to clarify the slight change in behavior here; back to you!

**Comment by ivankruchkoff** [comment]
Misunderstanding here that post_status corresponds to the state key in the post states array and that labels need to be combined.

We can have multiple states and they will be combined, which means we only have two scenarios:
1) Empty post title and post_status = draft:  `Idea Hub Draft “{idea-name}”`
2) Every other scenario: `post_state['idea'] = inspired by Idea Hub`

https://github.com/WordPress/WordPress/blob/baa81b67d19e29be29d0ac49c9bede316ab8f80a/wp-admin/includes/template.php#L2209-L2211 (note that `post_status` = `future` but `post_states['scheduled'] = Scheduled`

So by adding the label for a new post_state, we get the result we want:
<img width="387" alt="Screen Shot 2021-09-22 at 2 12 35 PM" src="https://user-images.githubusercontent.com/373931/134334180-4e98c38c-f0ea-4803-b4bc-831dd617124c.png">

Dumping the $post_states for debugging to show how labels are combined:
<img width="433" alt="Screen Shot 2021-09-22 at 2 17 49 PM" src="https://user-images.githubusercontent.com/373931/134334355-de55e602-ea9a-498b-a823-c9cdf0a98422.png">

**Comment by ivankruchkoff** [comment]
Added updates and opened https://github.com/google/site-kit-wp/pull/4104 as merging develop + pull rebase added the changes to the diff.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified**

- When you create an idea hub draft, the posts list table shows its status message as Idea Hub Draft
- When you set a title and update the draft, the status says inspired by Idea Hub.

![image](https://user-images.githubusercontent.com/73545194/134470283-0a918ea8-8dc9-4e10-9d86-d64dd1718a0a.png)

- Trash the post and ensure it still has the correct status message.

![image](https://user-images.githubusercontent.com/73545194/134470312-a56a40ce-909a-4bad-9404-a4b8dc9e3bfa.png)

- As an additional test, I restored the draft and the correct status message appears.
