### ISSUE TITLE
Site Kit icon stretched in Firefox browser - after verification

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#391]
## Bug Description

When setting up Site Kit using Firefox on mac the logo on the "Get OAuth Credentials" screen in stretched.  

## Steps to reproduce

1. Install Site Kit with Firefox browser 
2. Complete step one during current setup routine

## Screenshots

![Untitled - Gravit Designer (4)](https://user-images.githubusercontent.com/41326532/62782969-43263300-bab3-11e9-8d50-4ae8774f1252.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Since we're no longer using this external setup page as a primary tool for Site Kit, this isn't worth addressing, especially since we'll even phase out usage of it in the long term.
