### ISSUE TITLE
Allow for undismissing an idea in the Idea Hub widget

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3913]
## Feature Description

Currently ideas in the Idea Hub widget can be dismissed with a single click and no confirmation and no way to undo the action if it was done by mistake. Ideas should be able to be undismissed within a reasonable period of time.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@felixarntz @aaemnnosttv Assuming we can close this one given the removal of IH? cc @eclarke1

**Comment by aaemnnosttv** [comment]
Closing this one in favor of #6235
