### ISSUE TITLE
Update Google API client library to latest version that uses Idea Hub Beta API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3916]
The plugin is currently connecting to the `v1alpha` version of the Idea Hub API. Before launch though, we should switch to the `v1beta` version which is supposed to be published soon. To do that, we'll need to update the Google API client services library to a version where that is updated.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Google API client services library should be updated to at least `v0.213.0`.
* There should be no changes to the Idea Hub API other than the URL changing to "v1beta", _plus_ the following:
    * The Idea Hub module should now also generally require a new `https://www.googleapis.com/auth/ideahub.full` OAuth scope, in addition to the existing `*.readonly` scope.

## Implementation Brief

**The API library version mentioned in the ACs isn't released yet as of Wednesday, September 15, and it will most likely be released on Sunday, September 19.** Let's already move this issue to Execution Backlog, but engineering will be blocked until the library version release. [Please check here to see if the release is out.](https://github.com/googleapis/google-api-php-client-services/releases)

* Update the Google API client services library to the latest version which should be at least `v0.213.0` or greater.
* Verify that the Idea Hub service in the newest version has idea activities functionality.
* Verify that idea activities implemented in the Idea Hub class work with the newest version.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Make sure all the idea hub functionalities work as expected and doesn't throw any error (In UI or Console). 

## Changelog entry

* Update Idea Hub API to use v1 beta.

**Comment by eugene-manuilov** [comment]
As per this https://github.com/google/site-kit-wp/issues/3938#issuecomment-913625721, the Idea Hub activities functionality has been intentionally removed from the `v1beta`. It will be included in `v1beta` only when it becomes stable.

**Comment by eugene-manuilov** [comment]
@felixarntz IB is ready for review. Do you mind looking at it?

**Comment by felixarntz** [comment]
@eugene-manuilov IB ✅ 

You could argue though that all Idea Hub functionality should be verified whether it still works generally. That's mostly related to QA though, as mentioned the other day. cc @wpdarren

**Comment by wpdarren** [comment]
### QA Update: ✅ 

We will be completing E2E on Friday but I ran some sanity checks:

- Could set up Idea Hub and confirmed the feature tour appears
- Dismissed an idea and it was removed from the new ideas tab
- Saved an idea and it appeared in the saved tab
- Started a draft and it appeared in the drafts tab
- Went to the posts screen and the feature tour appeared for the idea hub draft
- Refreshed the Idea hub widget  to make sure the same data appears. 
- Clicked through the tabs. Used pagination to move through pages. 
- Unsaved ideas and they went back to new ideas.
- Deleted drafts in posts and they went back to new ideas.
- Correct number of ideas appeared in appropriate tabs.  No number appears when zero results. 
- No errors appeared in the console when going through these actions.

Looking good! 🚀
