### ISSUE TITLE
Remove userFeedback feature flag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3924]
Since the feature is fully rolled out, we should remove the `userFeedback` feature flag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `userFeedback` feature flag should be removed
* All code that has been activated when the `userFeedback` feature flag is enabled should work unconditionally now.
* All code that has been deactivated when the `userFeedback` feature flag is enabled should be removed.

## Implementation Brief
* Update `feature-flags.json` to remove `userFeedback`
* Search for the `userFeedback` string within the code base and review code where the `userFeedback` is present. Any logic/component which was rendered conditionally when the `userFeedback` feature was enabled should be rendered unconditionally now. Any code which was rendered when the feature flag was disabled should be removed.
* Use of the `useFeature` hook with `userFeedback` as a parameter should be removed.

### Test Coverage
* No new tests to be added

### Visual Regression Changes
* N/A

## QA Brief

* Verify that the `userFeedback` feature flag no longer exists (e.g. it no longer shows up in the Site Kit tester plugin).
* Verify that the user feedback functionality (specifically the rating survey) now shows up generally, i.e. without requiring a feature flag to be enabled.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Thanks for the PR @Patil2099! Normally it's difficult for us to accept PRs from the community but in this case the changes are so small and ready to go that we should be able to use it 👍

**Comment by wpdarren** [comment]
QA Update: ✅ 

**Verified:**

- Verified that the userFeedback feature flag no longer exists in the Site Kit tester plugin.
- Verified that the user feedback functionality now shows up generally (used code provided to paste into console) 

![image](https://user-images.githubusercontent.com/73545194/131858799-2c401615-2d21-4b2e-936b-9201b69a3f87.png)
