### ISSUE TITLE
No way to go back when user stuck on the OAuth flow

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3933]
## Bug Description
While setting up Site Kit,  if user didn't continue within specific time on oAuth flow then it shows error which is good. But a button or any link that'd land back to Site Kit screen would be a great addition.

## Steps to reproduce

1. Go to Site Kit Setup
2.  Sign with Google
3. Stay at Additional Access for Site Kit

## Screenshots
![Screenshot_32](https://user-images.githubusercontent.com/14175927/130772770-c6535360-a44c-4efc-a27c-e5a0083a0f63.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @abdullah1908 – I'll open a task to address this on the service as this isn't something we can fix on the plugin.
