### ISSUE TITLE
Allow modules to declare supported screens other than their own

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3944]
## Feature Description

In Site Kit some modules have their own screens in wp-admin (e.g. Analytics, Search Console) while others do not (e.g. Optimize). With the addition of Idea Hub, we're starting to see the need for modules to be able to declare screens that the module integrates with but aren't "owned" by the module or even registered by Site Kit at all such as the post editor or the post list view. Other core screens that Site Kit integrates with include: Plugins (after initial activation), WP dashboard, Tools, and Site Health information.

This is useful for loading general Site Kit infrastructure like assets and enabling our anonymous usage tracking in a targeted way without resorting to hardcoded exceptions. See https://github.com/google/site-kit-wp/pull/3891#discussion_r691010114

Currently, modules declare support for their own screen by implementing the `Module_With_Screen` interface and providing a `Screen` instance in its implementation via the `Module_With_Screen_Trait`. This is specific to Site Kit owned module screens though as well as only supporting a single screen.

Ideally modules should be able to use a similar API to declare support for other screens as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov @tofumatt Let's pick this one up in our sync next week - feel free to share any ideas here in advance.

**Comment by aaemnnosttv** [comment]
@felixarntz after thinking about this a bit more, I'm not sure this is needed _yet_. Given the proposed solution to loading tracking in #3972 the utility here seems mostly relevant for loading assets, however I'm not sure we need to add additional infra for handling this as all modules have access to the `Assets` instance and can already hook into any other screen to enqueue them as needed. If anything, maybe we need an added method on `Assets` to enqueue all assets for a given context to make it a bit cleaner? Right now we have more of a manual approach for the few instances where we use it where this could easily be refactored into its own method. https://github.com/google/site-kit-wp/blob/ae0b02b9accd4a6f0cb84592f575cf0750f8678a/includes/Core/Assets/Assets.php#L127-L136

I think we need to clearly understand the needs we're trying to solve otherwise as these two don't quite seem to justify changes at the module level the way I understand it now. What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv That is a good point. I was also thinking we still need to define what a "supported screen" even really means - and maybe it doesn't mean anything at this point 😂 

I agree going with the existing `Assets::enqueue_asset` via regular hooks is the most appropriate solution for now, rather than creating some architecture around what can already easily be accomplished in a WordPress-y way.

I'll close this one for now.
