### ISSUE TITLE
Introduce dashboard tour tooltips 

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#3947]
## Feature Description

Add tooltips introducing the new features for the generic dashboard. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**Tooltip 1**
- Position: highlighting the tabs 
- Heading: New! Navigate your dashboard easily with the dashboard tabs
- Text: Jump straight to the relevant section in your dashboard with just one click - no more scrolling. 
- Show four dots with the first one highlighted to indicate this is 1 out of 3
- Navigation: "Next" and "x" in top right corner to dismiss

**Tooltip 2**
- Position: highlighting the single URL search 
- Heading: Check stats for a specific post
- Text: Search by URL or by post title and your dashboard will be filtered to show stats just for that URL.
- Show four dots with the second one highlighted to indicate this is 2 out of 3
- Navigation: "Next", "Back" and "x" in top right corner to dismiss

**Tooltip 3**
- Position: highlighting the updated Search Funnel widget
- Heading: See trends over time for your site's Search metrics 
- Text: The updated Search Funnel shows you a more comprehensive view of how traffic from Search is changing. 
- Show four dots with the third one highlighted to indicate this is 3 out of 3
- Navigation: "Got it", "Back" and "x" in top right corner to dismiss

## Implementation Brief
* Create `assets/js/feature-tours/unified-dashboard.js` which exports the `unifiedDashboard` variable (object having the same structure as other files in the same folder, for e.g `assets/js/feature-tours/help-visibility.js`)
	* The `slug` should be `unifiedDashboard`
	* `context` set to `VIEW_CONTEXT_DASHBOARD`
	* `version` set to `1.50.0`
	* `checkRequirements` should be a function that checks whether the `unifiedDashboard` feature flag is enabled, via the `isFeatureEnabled` function.
	* `steps` should be an array of objects, each of which has the following properties for each tooltip:
		* Tooltip 1
			* `target` set to `.googlesitekit-navigation`
		* Tooltip 2
			* `target` set to `.googlesitekit-entity-search`
		* Tooltip 3
			* `target` set to `.googlesitekit-widget--searchFunnel`
			* `placement` set to `top`
		* The `title` and `content` properties should be set to the corresponding strings in the AC.
	* For tracking purposes, the `gaEventCategory` property should be set to `{ viewContext }_unified-dashboard`.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes

* 

## QA Brief
* Delete the `wp_googlesitekitpersistent_dismissed_tours` user option. `wp user meta delete 1 wp_googlesitekitpersistent_dismissed_tours` where `1` is the user id.
* Enable the `unifiedDashboard` feature flag.
* Go to the main dashboard.
* Ensure the unified dashboard feature tour shows up and tooltips content are displayed as per the AC.

## Changelog entry

* Add a new feature tour for the unified dashboard.

**Comment by FlicHollis** [comment]
This is not a dependency for the epic to be complete. After a conversation with @felixarntz on the Eng stand up, this can be worked on after the bug bash.

**Comment by asvinb** [comment]
@felixarntz A couple of things:
* For tracking purposes, can you let me know what should be the event category?
* For Tooltip 4, which widget is actually be targeted? Since the AC was written a long time ago, maybe it's outdated?

Let me know!
Thanks!

**Comment by felixarntz** [comment]
@asvinb Great questions.
* For the event category, let's use `{ viewContext }_unified-dashboard`.
* Correct, tooltip 4 is no longer relevant in the dashboard, so I've removed it now.

IB ✅ 

Please just add the event category to the IB. Once you've done that, feel free to move to _Execution Backlog_ without another review.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The unified dashboard feature tour show up and tooltips content are displayed as per the AC, other than there are three dots instead of 4. Confirmed this is correct. 
- Tested the feature tour on our supported browsers, ie. Chrome, Safari.
- Tested that a new site with Unified Dashboard enabled does not receive the tour, as expected.
- Tested that the feature tour does not appear on mobile screen sizes, which is expected like all other tours
- Tested with notification messages in the dashboard to make sure layout is as expected.

<details>
 <summary>Screenshots</summary>
 
![image](https://user-images.githubusercontent.com/73545194/151157596-bd366cbf-cf1a-459d-b3b3-a543c264313c.png)

![image](https://user-images.githubusercontent.com/73545194/151157737-7da6dcbe-11f3-4e7e-a92a-ed0648bb78a3.png)

![image](https://user-images.githubusercontent.com/73545194/151157767-2df7fbd4-3ccd-453e-89e5-39a57f6c0adf.png)

</details>

**Comment by asvinb** [comment]
Follow up PR: https://github.com/google/site-kit-wp/pull/4734

**Comment by eugene-manuilov** [comment]
@felixarntz do you mind taking a look as well? #4734

**Comment by felixarntz** [comment]
@asvinb @eugene-manuilov Left just one small comment on #4734 - overall that's looking great! Let me know if what I'm thinking there is feasible.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvinb @felixarntz just two observations.

1. With the tour active, if you scroll down to the button of the page theres a large gap after the last widget. Not a huge issue but thought I would mention.  I didn't notice that before. 

![image](https://user-images.githubusercontent.com/73545194/151553099-04b5cf1c-a8a5-4189-95ac-5b5a538c3f20.png)

2, The placement of the tooltip is above the widget and can see it on different screen sizes, but it is aligned to the top right, which looks a little odd.  Should it be centered? 

![image](https://user-images.githubusercontent.com/73545194/151553248-766e7485-3531-4823-b9e6-50931bb8e90a.png)

**Comment by asvinb** [comment]
@wpdarren 

- For the white space this was implemented as part of https://github.com/google/site-kit-wp/issues/4490
- For the centered tooltip, there was some discussion around it here: https://github.com/google/site-kit-wp/pull/4734#discussion_r794346072 and we decided to go with the tooltip being to the right (for now).

**Comment by wpdarren** [comment]
@asvinb thanks, noted about the alignment.  

> For the white space this was implemented as part of Last section not at top when activated #4490

But there's space underneath the WordPress footer too, I'm assuming that's not expected?  Like I said, not a huge issue as its unlikely the user will scroll down that far when going through the tour but it only occurs when it's active. 

![image](https://user-images.githubusercontent.com/73545194/151555310-0047ad39-a81f-4b0d-8e96-fd3460439e8f.png)

**Comment by asvinb** [comment]
Ah I see. Unless @felixarntz disagrees I think we can create another issue for that @wpdarren

**Comment by wpdarren** [comment]
@asvinb I agree with you that this can be a new ticket. I'll make a note to create one. 

### QA Update: ✅ 

- Verified that the tooltip and widget now appear in view on different screen sizes.
- Ran through the tooltips and they all load in the correct placements.

![image](https://user-images.githubusercontent.com/73545194/151556720-b8fc835c-dfcf-4588-9b79-cc4fbfa38a10.png)
