### ISSUE TITLE
Inconsistent data when selecting different reporting periods

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3951]
## Bug Description

As reported by [one user in the support forums](https://wordpress.org/support/topic/sometimes-sitekit-shows-0-users-for-last-28-days-and-last-90/) there is no data appearing when selecting some of the different date ranges. This doesn't always occur, just at irregular intervals. 

Summary of what the user is encountering:
- **Primary Site Kit dashboard**: The "All users" value remains at zero when selecting in the 28 day reporting period ([screenshot](https://i.imgur.com/M3AR7Wx.png))
- **Analytics dashboard**: No data for the last 28 days (Gathering Data) while there is data when selecting the 14 day reporting period

A small example of the experience can be seen below:
![2021-08-27-15-20-14](https://user-images.githubusercontent.com/41326532/131142191-2c8ec567-f9e3-463f-bffe-9cb398769c73.gif)

Further details can be see in the full video within the users [Site Health information report](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNjJ4-bN8aJRcQhdSITpgQldE-HUB_Gslk8UmyzCW2pFuX2d6X3dm85FHYYCP2KtK9o).

## Additional Context

 - [Support Topic](https://wordpress.org/support/topic/sometimes-sitekit-shows-0-users-for-last-28-days-and-last-90/) | [Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNjJ4-bN8aJRcQhdSITpgQldE-HUB_Gslk8UmyzCW2pFuX2d6X3dm85FHYYCP2KtK9o)
 - Data appears fine within Analytics using the GA web interface
 - Site Kit 1.39.0
 - No obvious conflicting plugins
- [TagAssistant ](https://tagassistant.google.com/) indicates the UA tag firing fine (no GA4 snippet)
- No GTM placed Analytics snippet

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
The impacted site has been moved to another hosting provider, with the issue no longer existing on this new host.

@bethanylang For your/eng team review. Happy to test out any possible hosting related features, nothing obvious stands out from the Site Health information kindly provided.

**Comment by bethanylang** [comment]
@jamesozzie Thank you for the update! Closing for now but we can always reopen as needed.
