### ISSUE TITLE
Update readme FAQ

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3953]
The FAQ content in the readme has been the same since 1.0.0 launch. It should be updated to better reflect actual frequently asked questions.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The FAQ section in the readme should be updated with the content from [this doc](https://docs.google.com/document/d/1Bi-VrnCdTPsS-f-Gm0Wik_gVLmN1jDuOcvISPWZQeGE/edit).

## Implementation Brief

* Merge #3954.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Ensure the FAQ section in the readme.txt file has the content from the doc (plus the original entry about Site Kit being free) linked in the ACs and it looks fine when testing with a tool like https://wpreadme.com/

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that the FAQ section in the readme.txt file has the content from the doc 
- Verified that the original entry about Site Kit being free is included in the FAQ section. 
- Verified that the FAQ/Read.me file looks fine when testing with a tool.
