### ISSUE TITLE
sitekit is not connecting with rest api

### ISSUE THREAD

**Issue by HaziqAli001** [google/site-kit-wp#3955]
I have taken all precautionary measures as mentioned in your guide. Still it is showing thw same message and html verification file isnot being uploaded

**Comment by jamesozzie** [comment]
Hi @HaziqAli001, 

If you'd like to [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on the plugins WordPress.org repository we'd be happy to assist you form there. Please include as much relevant information to your support topic as needed to assist with this issue, including any REST API specific notices you may be encountering. 

You can share your Site Health info or any additional information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) after creating a topic.  

I'll close this GitHub issue however we can reopen this should we determine a bug or fix to be applied on the plugin side.
