### ISSUE TITLE
In google site kit Analytics shows wrong report

### ISSUE THREAD

**Issue by thejoydutta** [google/site-kit-wp#396]
After connecting on om site it shows query report for the connected site but it shows the most popular content shows of one of my another site. Why does this happen? It should show popular content of the same connected site

![image](https://user-images.githubusercontent.com/42054702/62920616-e8971a80-bdc3-11e9-8c30-40ea8dcdc112.png)

**Comment by jamesozzie** [comment]
@thejoydutta If you check your Analytics account and you should see that you have traffic coming from the other mentioned site, subdomains or subpaths. Site Kit pulls in that information directly from your Analytics account. There is also a possibility that another site is using the same GA tracking code which can result in the statistics from the other site. 

One workaround is from within your Analytics account is to create a view. After creating the view you can setup a filter, to include only your own primary site, more information on this [here](https://support.google.com/analytics/answer/1033162). Using that view you can then connect this view to your Site Kit Analytics module.

**Comment by jamesozzie** [comment]
@thejoydutta Did you have any luck investigating the setup from your analytics account directly?

**Comment by grzegorz-janoszka** [comment]
I have the same, sitekit just chooses the first property and it is not possible to select another one.

**Comment by jamesozzie** [comment]
@grzegorz-janoszka Do you have any existing analytics tag placed on your site? It could be placed via a plugin or theme setting? If you check the source code of your site search for a string starting with "UA-". If you manage to find the source and you can remove you should be able to select other properties.

**Comment by grzegorz-janoszka** [comment]
Yes, I have an existing tag ending with "-3", but this plugin just chooses "-1" and it is not possible to change it.

**Comment by jamesozzie** [comment]
Can you go into your Analytics account and check the name of the property, I would suggest even changing the name to match your site name. Then clear your cache before logging into Site Kit again and disconnecting the Analytics module. (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit). You can then start the process again and see if the property it displays matches.

**Comment by grzegorz-janoszka** [comment]
James, I have in total three properties for three websites. Despite disconnecting and connecting again the Site Kit shows only the first property and the dropdown is grayed and I can't select anything else.

**Comment by grzegorz-janoszka** [comment]
I think I know how to fix it. You have to remove the GA code from your website (UA-....) and then the dropdown is not greyed and you can choose the property you want. With the GA code in your html the plugin erroneously chooses the incorrect property.

**Comment by jamesozzie** [comment]
Yeap, removing the tracking code allows you to select a property from the dropdown. Interesting that the dropdown populated with an incorrect property, but feel free to share a video clip if possible and we can take a look.

**Comment by jamesozzie** [comment]
@thejoydutta Were you able to get the Analytics module connected?

**Comment by peacockesq** [comment]
I have the same issue as grzegorz - I'll try removing the analytics code from the site to see if it helps. If so, that'll at least give you another data point. :-)
