### ISSUE TITLE
Mark "Learn More" link in Idea Hub description as external link

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3961]
The "Learn More" link in the Idea Hub setup CTA/description is an external link, but is explicitly marked to hide the "external" indicator:

![image](https://user-images.githubusercontent.com/73545194/131354073-e32496f1-3a6f-42d3-83c3-277e22844436.png)

https://github.com/google/site-kit-wp/issues/3810#issuecomment-908393123

We should remove the `hideExternalIndicator` prop so the "Learn more" link is marked as external visually.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Learn More" link in the Idea Hub CTA should be marked as an external link with the visual external indicator, eg:

<img width="137" alt="Screenshot 2021-08-30 at 16 34 57" src="https://user-images.githubusercontent.com/90871/131365073-2990452f-b755-4f67-9273-d54c0dd9ebbd.png">

## Implementation Brief

* Remove the `hideExternalIndicator` prop in https://github.com/google/site-kit-wp/blob/130d5caa44857178edaef02e74168054a220d1ae/assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js#L149

### Test Coverage

* N/A

### Visual Regression Changes

* Likely none, but this could cause a VRT change for anything using this component.

## QA Brief

* Make sure that idea hub is unconnected. 
* The Learn More Link should have the external link marker. 

## Changelog entry

* Mark the "Learn More" link in Idea Hub's description as an external link.

**Comment by aaemnnosttv** [comment]
I think the external link indicator wasn't in the original designs which generally have some minor inconsistencies with the way things are in the plugin now. cc: @felixarntz

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that the` Learn More` link has the external link marker.
- Verified that the widget styling looks good on smaller screen sizes and supported browsers. 

![image](https://user-images.githubusercontent.com/73545194/131675036-a95726b1-fa8a-4528-b3c2-31821282a44f.png)
