### ISSUE TITLE
VRT broken on develop

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3962]
## Bug Description

Our visual regression testing has broken between `main` and the current `develop`.

## Steps to reproduce

1. Checkout `develop`
2. `npm install`
3. `npm run test:visualtest`
4. See many failures

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Running `npm run test:visualtest` should pass
    * Only 1 test is known to be unstable (see #3552) - everything else should pass consistently

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/3963

### Test Coverage

* No changes

### Visual Regression Changes

* They should pass now 😄 

## QA Brief

* Run `npm run test:visualtest` – no test should fail other than the one mentioned in the ACs (maybe)

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Wow, who'd have thunk?

IB ✅ and merged 👍🏻
