### ISSUE TITLE
Idea Hub Saved and Drafts tabs show number even when 0

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3964]
## Bug Description

Per the [original design](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A180), the Idea Hub widget tab labels for "Saved" and "Drafts" should only include the number indicator _if_ there are any applicable ideas, i.e. not if there are 0 saved ideas or 0 draft ideas respectively.

This is currently incorrect, as the check for whether to add the indicator is `>=0` rather than `>0`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The number of ideas on the Idea Hub widget tab labels for saved and draft ideas should only display if the respective value is greater than 0.

## Implementation Brief

* Change the check for `savedIdeas?.length >= 0` to `savedIdeas?.length > 0` and the check for `savedIdeas?.length === undefined` to `savedIdeas?.length === 0 || savedIdeas?.length === undefined` in https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js#L257-L272
* Do the same for the `draftIdeas?.length` check in the same component.

### Test Coverage

* None.

### Visual Regression Changes

* No changes expected, but if there are VRTs for this component they'll need updating.

## QA Brief

* There should no longer be (0) in the Draft and Saved tabs of Idea Hub Dashboard Widget if there's no Draft or Saved Ideas respectively. 
* There should be (#) when there is idea in the respective tab. ie: http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-dashboard&gskNew=8 

## Changelog entry

* Fix counts on Idea Hub widget tab labels to only show up if greater than zero.

**Comment by tofumatt** [comment]
(Technically we could check for `! savedIdeas?.length` over `savedIdeas?.length === 0 || savedIdeas?.length === undefined`, but I find the explicitness of the latter to be a lot more helpful when reading the code—it communicates intent a lot more clearly, so I went with it in the IB.)

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@felixarntz @tofumatt is there a reason why we do not have a number on the `New Ideas` tab when there are ideas? I realise that this is the first tab that is loaded so it's obvious, but when you are on the other tabs, it's not as obvious. 

**Verified:**

There is no longer be (0) in the Draft and Saved tabs of Idea Hub Dashboard Widget if there's no Draft or Saved Ideas 

![image](https://user-images.githubusercontent.com/73545194/131687621-feece89d-ad93-4b70-b6dc-b4f5388d7442.png)

There is a number when there is idea in the respective tab.

![image](https://user-images.githubusercontent.com/73545194/131687778-0fc0a8fe-f400-4a50-8eb6-6b855acb487d.png)

**Comment by tofumatt** [comment]
Probably because the number will be quite large, but also because they aren't numbers the user is in control of. I think showing the number of new posts isn't very actionable, but the Saved and Drafts column are and indicate the control the user has set aside for themselves.

It makes sense to measure and display those numbers, less so the New Ideas I think.

**Comment by felixarntz** [comment]
@wpdarren Yes what @tofumatt says is correct - it is the expected behavior that "New" doesn't show any number.

**Comment by wpdarren** [comment]
### QA Update ✅ 

**Verified:**

There is no longer be (0) in the Draft and Saved tabs of Idea Hub Dashboard Widget if there's no Draft or Saved Ideas 

![image](https://user-images.githubusercontent.com/73545194/131687621-feece89d-ad93-4b70-b6dc-b4f5388d7442.png)

There is a number when there is idea in the respective tab.

![image](https://user-images.githubusercontent.com/73545194/131687778-0fc0a8fe-f400-4a50-8eb6-6b855acb487d.png)
