### ISSUE TITLE
Implement additional Idea Hub events for widget page navigation

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3980]
As a follow-up to #3817, this issue defines a few additional GA tracking events Idea Hub interactions around page navigation that should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following additional GA tracking events should be sent for their respective interactions within the Idea Hub widget:
    * `new_page_advance`: User clicks on the button to go to the next page in the "New" tab.
    * `new_page_return`: User clicks on the button to go to the previous page in the "New" tab.
    * `saved_page_advance`: User clicks on the button to go to the next page in the "Saved" tab.
    * `saved_page_return`: User clicks on the button to go to the previous page in the "Saved" tab.
    * `drafts_page_advance`: User clicks on the button to go to the next page in the "Drafts" tab.
    * `drafts_page_return`: User clicks on the button to go to the previous page in the "Drafts" tab.
* For all of these events, the event category should be `idea_hub_widget`, and the **current** page number (starting at 1, i.e. not index) should be provided as event label (e.g. if you go from page 2 to page 3, it should send 2).

## Implementation Brief

Inside `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Pagination.js`:
- Import `IDEA_HUB_GA_CATEGORY_WIDGET` from `assets/js/modules/idea-hub/datastore/constants.js`
- inside the `handleNext` callback, add the following logic
  - depending on the current tab (you could use a `switch` statement, for example), the `trackEvent` function is called with the appropriate `..._page_advance` event.
  - along with the event key, pass `IDEA_HUB_GA_CATEGORY_WIDGET` as the category parameter and the current page number as the label parameter. The function signature is `trackEvent( category, action, label )`.
  - See the following gist to get a better idea:
  ```js
  if( tab === 'new-ideas' ) {
      trackEvent( IDEA_HUB_GA_CATEGORY_WIDGET, 'new_page_advance', page );
  } else if ( tab === 'saved-ideas' ) {
      trackEvent( IDEA_HUB_GA_CATEGORY_WIDGET, 'saved_page_advance', page );
  } else if ( tab === 'draft-ideas') {
      trackEvent( IDEA_HUB_GA_CATEGORY_WIDGET, 'draft_page_advance', page );
  }
  ```
- Now repeat the process to handle the `return_...` events. You'll need to add the corresponding logic to the `handlePrev` callback.
  - Note that there are situations where the component calls  `handlePrev` via `useEffect` once (on mount) if it is on an empty page (see #3859). 
  - In these situations we don't want to fire `trackEvent`. The simplest way around this might be to add an optional parameter to `handlePrev` that defaults to `true`. We can then fire the tracking as the default behaviour, but have the option of setting the flag to `false` if we are calling `handlePrev` and don't want to track the event. For example:
  ```js
    const handlePrev = useCallback( ( shouldTrackEvent = true ) => {
      // Existing logic ...
      if ( shouldTrackEvent ) { /* add the track event calls here */ }
    }

    useEffect( () => {
      // If we do call handlePrev, set the flag to false
      handlePrev( false );
    }
   ```

### Test Coverage

* No new tests required.

### Visual Regression Changes

* None anticipated.

## QA Brief

* Install the [Chrome Analytics debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en)
* Within the Site Kit admin settings (`/wp-admin/admin.php?page=googlesitekit-settings#/admin-settings`), enable the opt in for tracking.
* Activate the Idea Hub module.
* Navigate to the Site Kit dashboard and scroll down to the Idea Hub widget.
* Open the javascript console in dev tools (Windows and Linux, press Control-Shift-J; on Mac, press Command-Option-J). 
* Use the pagination on the widget, and verify that the correct tracking is being sent as per the ACs.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@johnPhillips unfortunately, I'm not seeing any entries logged for `saved_page_advance` and `saved_page_return` when going through the pagination on the `Saved` tab.  

The `New Ideas` and `Draft` tabs are working fine as per the AC. 

**Verified:**

The following additional GA tracking events are sent for their respective interactions within the Idea Hub widget:

`new_page_advance:` User clicks on the button to go to the next page in the "New" tab.  - [Screenshot](https://user-images.githubusercontent.com/73545194/133439121-6399988d-14ff-4f1d-bfd7-308f18b93a9f.png)
`new_page_return:` User clicks on the button to go to the previous page in the "New" tab. - [Screenshot](https://user-images.githubusercontent.com/73545194/133439141-c79e2ce7-5632-49aa-b260-0e56b07b59e4.png)
`drafts_page_advance:` User clicks on the button to go to the next page in the "Drafts" tab.  - [Screenshot](https://user-images.githubusercontent.com/73545194/133439183-bc8fff18-7f98-4972-9ca2-a730c71bc4b2.png)
`drafts_page_return:` User clicks on the button to go to the previous page in the "Drafts" tab. - [Screenshot](https://user-images.githubusercontent.com/73545194/133439209-72ccb93c-8d3c-4785-9cc9-a024880c002e.png)


For all of these events, the event category is `idea_hub_widget` and the current page number as per screenshots above.

**Comment by aaemnnosttv** [comment]
Ready for another pass @wpdarren 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

The `New Ideas` and `Draft` tabs are working fine as per the AC. 

**Verified:**

The following additional GA tracking events are sent for their respective interactions within the Idea Hub widget:

`new_page_advance:` User clicks on the button to go to the next page in the "New" tab.  
`new_page_return:` User clicks on the button to go to the previous page in the "New" tab. 
`saved_page_advance:` User clicks on the button to go to the next page in the "Saved" tab.
`saved_page_return:` User clicks on the button to go to the previous page in the "Saved" tab.
`drafts_page_advance:` User clicks on the button to go to the next page in the "Drafts" tab. 
`drafts_page_return:` User clicks on the button to go to the previous page in the "Drafts" tab.

For all of these events, the event category is `idea_hub_widget` and the current page number as per screenshots above.
