### ISSUE TITLE
Allow users to enable "Enhanced measurement" tracking when configuring Analytics

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3981]
## Feature Description

Now that Site Kit can place a GA4 snippet on users site allow for users to toggle on "Enhanced Measurement", or activate this by default. This would allow for users to have event information for outbound clicks, file downloads and more.
 
From analytics.google.com this feature is enabled following the below steps:
_GA4 Admin > select your GA4 property > Data Streams > Click on your site name > Enable Enhanced Measurement_

![SWxQGBHRjl](https://user-images.githubusercontent.com/41326532/131843687-d6a035c6-7dde-40e8-b41c-b9ea21444381.gif)

There are similar open feature requests on this although this particular request if added would cover many of the asks in those topics:
https://github.com/google/site-kit-wp/issues/1207
https://github.com/google/site-kit-wp/issues/1424

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This was only recently made possible to do via the Admin API, and is currently only in alpha:
https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.dataStreams/updateEnhancedMeasurementSettings

**Comment by aaemnnosttv** [comment]
Closing as this was implemented in other issues and recently released 👍
