### ISSUE TITLE
HTML tag not surrounding opt-out snippet for Analytics when AMP installed

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3985]
## Bug Description

Found this issue when running through the QA on #1504. 

When you connect Analytics and have AMP installed, the HTML opt-out tags do not surround the snippet.  `meta name="ga-opt-out"`  At the moment the HTML tags are displayed as `<!-- Google Analytics AMP opt-out snippet added by Site Kit -->` `<!-- End Google Analytics AMP opt-out snippet added by Site Kit -->`

Evan suggested that we revisit this to make the comment part of the tag itself e.g using a data attribute.

## Steps to reproduce

1.  Connect Site Kit and activate `Analytics`
2. Install `AMP` plugin
3. Make sure that in Analytics settings that logged in users are excluded
4. Visit the FE with AMP (`?amp=1` URL)
5. Look at the source code and observe the HTML tag mentioned above. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz I took a look at this when it was originally raised and it seems to be due to HTML post-processing done by the AMP plugin which is not preserving the location of the comments around the opt-out snippet. Since it's a single tag though, we could move the comment text onto the `meta` element itself as a `data` attribute, in which case it should be preserved. Otherwise I don't think there is anything we can do here and this can probably be closed. What do you think?

**Comment by westonruter** [comment]
The AMP plugin doesn't yet remove comments but it will as of 2.2 by default with HTML minification in https://github.com/ampproject/amp-wp/pull/6568.

What's happening here is the [`AMP_Meta_Sanitizer`](https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-meta-sanitizer.php) is [reordering](https://github.com/ampproject/amp-wp/blob/3f0146e9188f19a0f21bb053dae48ef0a02958eb/includes/sanitizers/class-amp-meta-sanitizer.php#L320-L346) the `meta` tags in the `head`. This is causing the HTML comments to no longer appear next to the `meta` tag.

If the HTML comments are desired, one workaround could be to output this `meta` tag at `wp_footer`. Nevertheless, it seems adding a data attribute like `data-generator="Site Kit"` would be more elegant it would also have fewer bytes.
