### ISSUE TITLE
Site Kit header position wrong at 600px when scrolled

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3986]
## Bug Description

The current header styles have a media query which is off by 1px. This is only noticeable at 600px wide exactly and when the viewport is scrolled.

The `top: 46px` rule is still effect which leaves our header sticky but with a gap above it because the WP admin bar is not sticky/fixed below 601px. 

## Steps to reproduce

1. Emulate a viewport with a width of 600px
2. Navigate to a Site Kit screen
3. Scroll down
4. See gap above header

https://user-images.githubusercontent.com/1621608/132026096-c59fe3a5-1048-4699-a27e-165727f0b740.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The SK header should only have a fixed position from the top of the window at screen widths greater than 600px
    * The header should otherwise look and behave the same as it does today above and below 600px

## Implementation Brief

* Update the media query here to take effect 1px wider https://github.com/google/site-kit-wp/blob/207619e5fef6f95d8a89891b89c44b714701de51/assets/sass/components/global/_googlesitekit-header.scss#L37-L38

### Test Coverage

* No changes

### Visual Regression Changes

* No changes expected

## QA Brief

* Try the responsive layout while on a Google Site Kit Admin Page. 
* Try scrolling the page at 599px, 600px and 601px and observe the Site Kit Header Behavior 

## Changelog entry

* Fix positioning of the Site Kit header at the breakpoint between mobile and tablet viewports.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 I am on `develop` branch and I am still seeing the same issue at 600px. I am in incognito mode to ensure there are no caching issues.  

On 601px, the header remains at the top with WP menu bar as expected.  
On 600px, the header scrolls down the page as per the initial issue.  
On 595px, the header does stop at the top of the page.  

I am asssuming at 600px the Site Kit header should be at the top like you see in 595px. 

Here's a sceencast:

https://user-images.githubusercontent.com/73545194/133454136-8b07a08c-7e5c-4ba2-b08f-9cd51b78fed9.mp4

**Comment by wpdarren** [comment]
Issue reported above was due to caching plugin (WP Rocket) on the live site that I tested with.  🤦‍♂️ 

### QA Update: ✅ 

With a responsive layout while on a Google Site Kit Admin Page at 599px, 600px and 601px, the Site Kit Header is the same, where it is sticky at the top of the page.  I also tested this on our supported browsers.
