### ISSUE TITLE
Oops! There was a problem during set up. Please try again. Unknown Error (code: cURL error 28: Failed to connect to sitekit.withgoogle.com port 443: Connection timed out).

### ISSUE THREAD

**Issue by Ambundo** [google/site-kit-wp#3991]
This is the site check

### wp-core ###

version: 5.8
site_language: en_US
user_language: en_US
timezone: Africa/Nairobi
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/mutahifi/public_html
wordpress_size: 44.52 MB (46684294 bytes)
uploads_path: /home/mutahifi/public_html/wp-content/uploads
uploads_size: 3.44 MB (3602159 bytes)
themes_path: /home/mutahifi/public_html/wp-content/themes
themes_size: 15.24 MB (15977836 bytes)
plugins_path: /home/mutahifi/public_html/wp-content/plugins
plugins_size: 88.17 MB (92451240 bytes)
database_size: 5.16 MB (5406720 bytes)
total_size: 156.52 MB (164122249 bytes)

### wp-active-theme ###

name: OceanWP (oceanwp)
version: 3.0.5
author: Nick
author_website: https://oceanwp.org/about-me/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, align-wide, wp-block-styles, responsive-embeds, editor-styles, editor-style, menus, post-formats, title-tag, automatic-feed-links, post-thumbnails, custom-header, custom-logo, html5, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, widgets
theme_path: /home/mutahifi/public_html/wp-content/themes/oceanwp
auto_update: Disabled

### wp-plugins-active (9) ###

Contact Form 7: version: 5.4.2, author: Takayuki Miyoshi, Auto-updates disabled
Elementor: version: 3.4.3, author: Elementor.com, Auto-updates enabled
Hustle: version: 7.4.5.2, author: WPMU DEV, Auto-updates disabled
Livemesh Addons for Elementor: version: 6.14, author: Livemesh, Auto-updates disabled
Ocean Extra: version: 1.8.0, author: OceanWP, Auto-updates disabled
Really Simple SSL: version: 5.0.10, author: Really Simple Plugins, Auto-updates enabled
Site Kit by Google: version: 1.40.0, author: Google, Auto-updates disabled
Smush: version: 3.8.8, author: WPMU DEV, Auto-updates disabled
Yoast SEO: version: 17.0, author: Team Yoast, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 20M
upload_max_filesize: 10M
max_effective_size: 10 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.52.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.22 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 10M
php_post_max_size: 20M
curl_version: 7.77.0 OpenSSL/1.1.1k
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.35-cll-lve
client_version: mysqlnd 7.4.22

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/mutahifi/public_html/wp-content
WP_PLUGIN_DIR: /home/mutahifi/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### google-site-kit ###

version: 1.40.0
php_version: 7.4.22
wp_version: 5.8
reference_url: https://mutahifit.com
amp_mode: no
site_status: not-connected
user_status: not authenticated
verification_status: not-verified
connected_user_count: none
active_modules: site-verification, search-console
required_scopes: 
	openid: ⭕
	https://www.googleapis.com/auth/userinfo.profile: ⭕
	https://www.googleapis.com/auth/userinfo.email: ⭕
	https://www.googleapis.com/auth/siteverification: ⭕
	https://www.googleapis.com/auth/webmasters: ⭕
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ⭕
	googlesitekit_view_dashboard: ⭕
	googlesitekit_view_module_details: ⭕
	googlesitekit_manage_options: ⭕
enabled_features: 
	ga4setup: ⭕
	ideaHubModule: ⭕
	serviceSetupV2: ⭕
	userFeedback: ⭕
	userInput: ⭕
search_console_property: none

**Comment by jamesozzie** [comment]
@Ambundo Thanks for reaching out. We provide Site Kit initial support requests from the WordPress support forums. As you've [already opened a support topic](https://wordpress.org/support/topic/oops-there-was-a-problem-during-set-up-please-try-again-unknown-error-code/) we'd be happy to investigate this further from there, I'll provide a response within that topic shortly.
