### ISSUE TITLE
Ability to programmatically disable modules

### ISSUE THREAD

**Issue by henrywright** [google/site-kit-wp#3993]
## Feature Description

In a network install, each site admin doesn't have many technical capabilities. They are unable to perform many of the actions necessary to optimise a website for speed. For example, PageSpeed Insights includes some very useful suggestions but the suggestions aren't actionable by the site admin. They are, however, actionable by the super admin or a person with developer access.

It would be neat if the super admin could enable and disable the various modules at the network level based on whether they are useful for the site admins in the network.

By modules I'm referring to:

- Google AdSense
- Google Analytics
- Google Search Console
- PageSpeed Insights
- Tag Manager
- Optimize

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When registering the Site Kit modules internally in the Site Kit registry, the list of module class names should be filtered via a new filter `googlesitekit_available_modules`. **The filter should only allow removing items, not adding any that aren't in the unfiltered list.**

## Implementation Brief
* Using `includes/Core/Modules/Modules.php`:
  * Update the `$core_modules` array to be an associative array where keys are module slugs and values are class names.
  * Update the `setup_registry` method:
    * to apply the `googlesitekit_available_modules` filter to keys of the `$this->core_modules` array.
    * then in the `foreach` loop register modules if their slug is in the list of the available modules returned from the filter or the module is force active.

### Test Coverage
* Update `tests/phpunit/integration/Core/Modules/ModulesTest.php` to include tests for the `googlesitekit_available_modules` filter.

## QA Brief

List with the slug of all the modules.

- `site-verification`
- `search-console`
- `analytics`
- `optimize`
- `tag-manager`
- `adsense`
- `pagespeed-insights`
- `analytics-4`

Modules added via featured flags. 

- `idea-hub`
- `subcribe-with-google`

Add the following snippets of code into your `functions.php` of your active theme or in `mu-plugins/overrides.php` and place the code there.

**Disable All Modules**

```
<?php
add_filter(
	'googlesitekit_available_modules',
	function( $modules ) {
		return array();
	}
);
```

**Enable Only Search Console*

```
<?php
add_filter(
	'googlesitekit_available_modules',
	function( $modules ) {
		return array( 'search-console' );
	}
);
```

## Changelog entry

* Add the ability to programmatically disable modules using the `googlesitekit_available_modules` filter.

**Comment by jamesozzie** [comment]
Hi @henrywright,

While this feature would likely be discussed as part of our primarily multisite related issue (#276) I have added this as an open feature request for the team to review.

Be aware that we don't have a timeframe for adding full multisite support just yet however do subscribe to the [related issue](https://github.com/google/site-kit-wp/issues/276) for automatic updates. You should also hear back from a team member within this individual feature request once reviewed. Many thanks for your input!

**Comment by henrywright** [comment]
Sure @jamesozzie. Thanks for considering

Being able to disable features (PageSpeed Insights for example) would stop site admins in my network install emailing me asking how they can eliminate render-blocking resources or reduce unused JavaScript. These aren't really tasks for them; instead, they are tasks for me as a developer of the network. I obviously hugely benefit from PageSpeed Insights personally

😄

**Comment by jamesozzie** [comment]
@henrywright That's a great use case for such a feature, thank you. This request has been noted within the primary multisite related GitHub issue. Once that's being worked on you'll hear back from the team in relation to limiting the modules for super admins.

**Comment by felixarntz** [comment]
@henrywright Since Site Kit currently doesn't properly support multisite (you can only use it on a per-site level in multisite), adding a proper functionality for what you're requesting might take a while. However, what we could possibly add in a very straightforward way is e.g. a filter that allows programmatically disabling modules - would that satisfy your use-case as well?

**Comment by henrywright** [comment]
Thanks for reviewing this @felixarntz. A filter to disable modules would be perfect and would satisfy my use-case

**Comment by eugene-manuilov** [comment]
@felixarntz do you mind swapping the `googlesitekit_available_modules` filter for all modules with the `googlesitekit_is_module_available` filter that will be applied to each module individually? I think it would be a more elegant solution rather than filtering all modules together and then figuring out which module is added or deleted.

**Comment by felixarntz** [comment]
@eugene-manuilov Hmm, maybe. It may be simpler to use the filter like you're suggesting, but it would also mean we apply a filter for something rather edge-case-y several times instead of once. Also there may be cases where one party wants to conditionally control multiple modules, in which case a single filter may make that more straightforward.

I agree your suggestion is in a way more elegant and better for simple scenarios, but since the use-case here is rather an edge-case, I wonder whether we should rather focus on performance and flexibility of it.

**Comment by henrywright** [comment]
There is 1 advantage I can think of if a single filter is used instead of multiple filters. The user of the filter can provide an _allow list_.

```
add_filter(
    'googlesitekit_available_modules',
    function ( $modules ) {
        // Set the allow list
        return [
            'analytics',
            'insights'
        ];
    }
);
```

Then in the plugin you could do something like this:

```
$modules = do_action( 'googlesitekit_available_modules', $modules );
if ( in_array( 'insights', $modules ) ) {
    // Load module
}
```

This way, at a future date if a teleportation module is added to site-kit-wp, the user of the filter can decide if teleportation is useful for his or her users.If it is going to be useful he or she can add it to the filter's return array

**Comment by felixarntz** [comment]
@eugene-manuilov Great idea! Let's go with that. Assigning back to you for updating the IB.

**Comment by eugene-manuilov** [comment]
@felixarntz, IB is updated. Do you mind reviewing it?

**Comment by felixarntz** [comment]
IB ✅

**Comment by mitogh** [comment]
Hey, @eugene-manuilov @felixarntz would be worth updating the title as this ticket is no longer aiming for multi-site installations? 

Additionally would be worth updating the Changelog entry to reflect the fact that a new filter exists? 

Also wanted to ask for an update on the IB due we are currently using `in_array` on each iteration of the `foreach` according to the IB instead my suggestion would be to change the approach to create a map of available keys so we can have faster lookups and no need for `in_array` calls.

Example: 

```php
		$registry = new Module_Registry();
		$available_modules = (array) apply_filters( 'googlesitekit_available_modules', array_keys( $this->core_modules ) );
		// Create a map for faster lookup O(1) when looking for a module slug like [ 'analytics' => true ];
		$available_modules = array_fill_keys( $available_modules, true );

		foreach ( $this->core_modules as $module_slug => $module ) {
			if ( isset( $available_modules[ $module_slug ] ) ) {
				$registry->register( $module );
			}
		}
```

This removes the need to call `in_array` which currently is `O(n)` when looking for a value instead of `O(1)`

**Comment by henrywright** [comment]
Hi @mitogh 

I don't imagine the set of available modules will be huge but I agree `in_array()`, being O(n), isn't going to be as fast as your approach. +1 from me

**Comment by mitogh** [comment]
Thanks @henrywright 

Additionally, wanted to flag a scenario where all the modules are disabled via this filter this triggers an error in the U, for this new scenario I advise creating a new ticket and moving the work for that part on that ticket, due this is not the initial state of the app and can only be introduced via this filter.

![2021-12-11_11-21](https://user-images.githubusercontent.com/3921289/145689041-2ba3999e-bd33-40ce-ad8f-0ceb3f32783f.png)



```php
// Steps to replicate.
add_filter(
	'googlesitekit_available_modules',
	function( $modules ) {
		return [];
	}
);

```

Error output

```
`An error occurred while running 'mapSelect': Cannot read properties of null (reading 'getModules')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'getModules')
    at Object.eval [as current] (webpack-internal:///./assets/js/components/notifications/UnsatisfiedScopesAlert.js:102:107)
    at onStoreChange (webpack-internal:///./node_modules/@wordpress/data/build-module/components/use-select/index.js:135:46)
    at eval (webpack-internal:///./node_modules/@wordpress/data/build-module/components/use-select/index.js:155:7)
    at commitHookEffectList (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22030:26)
    at commitLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22080:9)
    at commitLayoutEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25344:7)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:385:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:440:31)
    at commitRootImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25082:9)

Original stack trace:

    in UnsatisfiedScopesAlert (created by ErrorNotifications)
    in ErrorNotifications (created by Header)
    in Header (created by DashboardApp)
    in DashboardApp (created by DashboardEntryPoint)
    in DashboardEntryPoint
    in RestoreSnapshots (created by Root)
    in ErrorHandler (created by Root)
    in Root`
```

cc @eugene-manuilov @felixarntz

**Comment by henrywright** [comment]
In addition to the empty array causing the above error, it is likely a non-array return value would also cause an error. Perhaps the solution is to be defensive and validate the value returned by the apply_filters() call to make sure it is the expected type and at least 1 valid module is specified in the array

What are your thoughts @eugene-manuilov and @felixarntz?

**Comment by henrywright** [comment]
In the PR I notice you have cast to array the return value of the apply_filters() call. The only problem to resolve now is the error you posted when the user of the filter doesn’t return a valid module. For example an empty array is returned 

The rest of the PR satisfies the IB

**Comment by eugene-manuilov** [comment]
> Additionally, wanted to flag a scenario where all the modules are disabled via this filter this triggers an error in the U, for this new scenario I advise creating a new ticket and moving the work for that part on that ticket, due this is not the initial state of the app and can only be introduced via this filter.

> In addition to the empty array causing the above error, it is likely a non-array return value would also cause an error. Perhaps the solution is to be defensive and validate the value returned by the apply_filters() call to make sure it is the expected type and at least 1 valid module is specified in the array

@mitogh @henrywright there is a bug in the implementation, once it is fixed this problem will disappear.

**Comment by eugene-manuilov** [comment]
> would be worth updating the title as this ticket is no longer aiming for multi-site installations?

I think we don't change original titles created by contributors. Felix can correct me if I am wrong 😄 

> Additionally would be worth updating the Changelog entry to reflect the fact that a new filter exists?

We update it after we merge the PR.

> Also wanted to ask for an update on the IB due we are currently using `in_array` on each iteration of the `foreach` according to the IB instead my suggestion would be to change the approach to create a map of available keys so we can have faster lookups and no need for `in_array` calls.
> 
> Example:
> 
> ```
> 		$registry = new Module_Registry();
> 		$available_modules = (array) apply_filters( 'googlesitekit_available_modules', array_keys( $this->core_modules ) );
> 		// Create a map for faster lookup O(1) when looking for a module slug like [ 'analytics' => true ];
> 		$available_modules = array_fill_keys( $available_modules, true );
> 
> 		foreach ( $this->core_modules as $module_slug => $module ) {
> 			if ( isset( $available_modules[ $module_slug ] ) ) {
> 				$registry->register( $module );
> 			}
> 		}
> ```
> 
> This removes the need to call `in_array` which currently is `O(n)` when looking for a value instead of `O(1)`

Technically saying, yes, `isset( ... )` check is faster than `in_array( ... )`, but in our case this doesn't make a notable difference because we have just a few items in that array. Anyway, feel free to implement it and we can use this approach.

**Comment by henrywright** [comment]
Hi @eugene-manuilov 

> there is a bug in the implementation, once it is fixed this problem will disappear.

Noted.

Does `force_active` mean the module will be active even if disabled by the filter? If so it could be worth making a note of this in the documentation just in case users of the filter aren't aware

**Comment by eugene-manuilov** [comment]
> Does `force_active` mean the module will be active even if disabled by the filter? If so it could be worth making a note of this in the documentation just in case users of the filter aren't aware

Yep, makes sense, thanks @henrywright. @mitogh could you please add a comment that explains it?

**Comment by kuasha420** [comment]
QA: :heavy_check_mark: 

Verified that the filter works as expected.

* Filter works for enabling/disabling single or multiple modules.
* Mandatory modules remain enabled regardless of their presence in the filter.
* Filter interacts correctly with modules behind feature flags. ( checked with Tester Plugin). 
    * Returning modules that are disable by feature flag with the filter is NOT possible.
    * But if the feature flag is enabled, it is possible to disable the module using the filter. 

LGTM.

**Comment by felixarntz** [comment]
### Approval ⚠️ 

This is working fine, but reviewing the implementation there are a few minor points worth addressing (see https://github.com/google/site-kit-wp/pull/4545#pullrequestreview-852848728). Specifically it's important we don't have the control over whether a module is force-active present in two places, which makes it error-prone.

cc @kuasha420 @eugene-manuilov @mitogh

**Comment by aaemnnosttv** [comment]
@felixarntz – these are addressed in https://github.com/google/site-kit-wp/pull/4662

**Comment by felixarntz** [comment]
### Approval ✅ 

Thanks @aaemnnosttv!

**Comment by jamesozzie** [comment]
Just noting here that the below modules are always force enabled and can't be deactivated programmatically:
- site-verification
- search-console
