### ISSUE TITLE
Update the Analytics snippet status with the "Connected Services" screen

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3996]
## Bug Description

At present a user may choose to only insert a GA4 snippet, and toggle off the option to "**_Place Universal Analytics code_**". After doing so they will see the "Analytics Code Snippet" status as "_**Snippet is not inserted**_". This can lead to confusion. 

![image](https://user-images.githubusercontent.com/41326532/132248458-895773e0-5a2f-44b1-b86c-a5aeba677bd7.png)

In order to provide further clarity consider one of the below:

- Replace the "**_Analytics Code Snippet_**" reference with a "**_Universal Analytics Code Snippet_**"
- Adding a second status for Google Analytics 4, "**_Google Analytics Code Snippet_**"

The gif below shows an example whereby a user may allow Site Kit to insert a GA4 snippet and not a UA snippet, with the status appearing as "Snippet is not inserted"

 
![L9DrPxkcjl](https://user-images.githubusercontent.com/41326532/132248610-18373a79-45a5-4401-b927-e0658fd072c3.gif)

## Steps to reproduce

1. Connect Analytics with UA + GA4 properties
2. Edit Analytics settings and toggle off placing the UA code while keeping the snippet enabled for GA4
2. Go to Analytics settings view in non-edit context
3. See "Snippet is not inserted"

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics settings panel in view mode should be slightly reorganized/expanded, as follows:
    * The "Analytics Code Snippet" (which is for UA) info should always display right below the account/property/view info (which are also mostly for UA). In other words, if GA4 is also set up, that information should show below the "Analytics Code Snippet" info.
    * The "Analytics Code Snippet" label itself should be clarified to "Universal Analytics Code Snippet".
    * If GA4 is set up, a separate piece of information should be added for the `analytics-4` module's `useSnippet` value: It should be on its own row similar to the above "Universal Analytics Code Snippet", and it should appear right below the GA4 property and web data stream information. Its label should be "Google Analytics 4 Code Snippet" and it should say either "Snippet is inserted" or "Snippet is not inserted" like the other one. Those two alternatives are sufficient here, we don't need to consider whether it comes from another plugin / existing tag or not, as this is going to be removed soon for UA as well.

## Implementation Brief
* Using `assets/js/modules/analytics/components/settings/SettingsView.js`,
	* Rename the "Analytics Code Snippet" label as per the AC.
	* Move the "Analytics Code Snippet" section below the "Account / Property / View" row.
	* Query the `MODULES_ANALYTICS_4` data store via the `getUseSnippet` selector to see if GA4 snippet is inserted.
	* Use the same HTML markup as for "Analytics Code Snippet" to display the whether GA4 snippet is inserted. The label should be `Google Analytics 4 Code Snippet` and then depending on the value returned by the `getUseSnippet` selector, display the appropriate label as per the AC.
	    * Note there is no existing tag case for the GA4 snippet, its text content is entirely based on the value of the GA4 `useSnippet` setting
	* The GA4 snippet info should be displayed below the "Google Analytics 4 Property / Google Analytics 4Measurement ID" row.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Connect Analytics with UA + GA4 properties
* Edit Analytics settings and toggle off placing the UA code while keeping the snippet enabled for GA4 and vice versa.
* Go to Analytics settings view in non-edit context
* See if the "Universal Analytics Code Snippet" and "Google Analytics 4 Code Snippet" correctly reflect the state of the snippets.

## Changelog entry

* Update the Analytics settings view panel to display "Use Snippet" settings below the appropriate property blocks.

**Comment by aaemnnosttv** [comment]
@felixarntz for this one it might make more sense to have separate snippet status fields, grouped with the respective connection settings, similar to the changes in #3807 rather than trying to update the one place to account for all variations.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb I think the only thing missing here is that the text value/feedback for the GA4 snippet has no existing tag case – it's only inserted or not as mentioned in the ACs. I'll add a note to make this more clear, otherwise this is good to go 👍 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

The `Universal Analytics Code Snippet` and `Google Analytics 4 Code Snippet` correctly reflect the state of the snippets. I set the settings to different combinations: Both UA & GA4.  Just GA4 and vice versa. Disabled GA4 and UA.  I also made sure that the changes made in the settings were updated in the source code of the FE. 

![image](https://user-images.githubusercontent.com/73545194/135863004-78f15e58-1a72-4590-846e-607a3b5c8ec2.png)

![image](https://user-images.githubusercontent.com/73545194/135863023-99c1e27a-5b3c-4306-b368-8bb4e1a91ef4.png)
