### ISSUE TITLE
Site Kit doesn't recognize a Tag Manager placed GA4 snippet

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3998]
## Bug Description

If a user sets up a GA4 tag via Tag Manager and then chooses to connect the Analytics module they're not informed that an existing GA4 tag has been placed. This is not the case for a manually inserted GA4 snippet, which Site Kit does recognize and inform users. 

 **_Manually inserted UA and GA4 snippet ([snippet used](https://i.imgur.com/Yih6qGg.png))_** 

![image](https://user-images.githubusercontent.com/41326532/132251469-be3b4b5b-d3a6-4b7e-a258-da4ecc008171.png)

**_Tag Manager (via SK) implemented UA and GA4 snippet_**

No mention of a GA4 snippet already placed. 

![image](https://user-images.githubusercontent.com/41326532/132251233-25e08e64-c6e8-4e07-8452-d8bd047bb610.png)

## Steps to reproduce

1. Setup a Tag Manager account and publish a container with both a UA and GA4 tag ([screenshot]. Ensure all page views are tracked. (https://i.imgur.com/8Q7NHNB.png))
2. Use Tag Assistant to ensure the tags are firing (both UA and GA4 - [screenshot](https://i.imgur.com/0t10E4F.png))
3. Connect the Tag Manager module within Site Kit - to that container
4. Connect the Analytics module within Site Kit. Only the UA snippet will be recognised

 
## Additional Context

 - SK 1.40.0
 - A GTM placed GA4 tag is also not recognized when only a GA4 tag in published (and not a UA tag)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz even in the context of the simplifications planned for the future around existing tags, I think we still want to detect the tag here for informative purposes, correct?

**Comment by felixarntz** [comment]
@aaemnnosttv Correct, I think the detection would be an enhancement worth adding.

**Comment by aaemnnosttv** [comment]
@felixarntz I believe this issue is no longer relevant as of #4103 which should cover this and more, correct?

**Comment by felixarntz** [comment]
@aaemnnosttv Good catch - closing this as duplicate since #4103 is already defined.
