### ISSUE TITLE
Don't request data in WP dashboard widget when hidden

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4001]
## Feature Description

When connected, Site Kit adds a widget to the WordPress dashboard which is the default landing view for all users after logging in to wp-admin. These widgets can be hidden using user-specific screen options.

![image](https://user-images.githubusercontent.com/1621608/132392681-f8ac9431-c77b-4376-b05d-e9e408233413.png)

When hidden, the Site Kit widget is still rendered (because the hiding is CSS only) so requests for data are still made. We should update our WP dashboard widget component to only request data when not hidden. Apart from the screen option, the widget could also be off screen on mobile where it may be a better experience to lazy load the data as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The WP dashboard widget should use the new `useInViewSelect` hook from #4096 for all of its API-based selector calls, replacing `useSelect` for those.
* The result should be that these API requests are only made when the WP dashboard widget is in or close to the viewport. The best way to test it is to hide the widget entirely via screen options. In that case, no API requests should be made.
    * When testing, please ensure to always clear your browser cache, since API requests are only made when nothing is cached yet.

## Implementation Brief
* When #4096 has been merged, update all use of `useSelect` by `useInViewSelect` in `assets/js/components/wp-dashboard/*.js`

### Test Coverage
* No new tests to be added. Existing tests that check the WP Dashboard widget output (E2E tests, mostly), may need to be updated to scroll to the WP Dashboard widget element to ensure it loads.

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Moving this to "Backlog" for now, since it will depend on the `useInViewportSelect` (or whatever that will be called) utility that we'll only introduce as part of the unified dashboard epic.

**Comment by felixarntz** [comment]
Closing this since it's now encompassed in #4096.
