### ISSUE TITLE
Refactor GA tracking events for module activation and setup (including Idea Hub adjustments)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4004]
As part of redefining some of our legacy GA tracking events, this issue focuses on module activation and setup. As part of that it also touches some events relevant for Idea Hub, which should be part of the Idea Hub launch.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All of the event categories mentioned below should technically rely on the `VIEW_CONTEXT_*` constants for their first name segment (i.e. don't hardcode "dashboard" but use the constant instead).

### Module activation and deactivation

* An `activate_module` GA event should be fired in the following places:
    * When clicking the button to activate a module in _Settings > Connect more services_ (event category: `settings_module-list`).
    * When clicking the button to activate a module from within an `ActivateModuleCTA` (event category: `dashboard_widget-activation-cta`). Note that this currently is only used by Analytics and PageSpeed Insights.
    * When clicking one of the buttons to activate a module from the common "success" notification on top of the dashboard which appears after successful plugin or module setup (event category: `dashboard_authentication-success-notification`). The existing `module_activate` event that is fired there should be removed / replaced with this.
    * When clicking the CTA button to activate Idea Hub in the (currently) Idea Hub-specific activation prompt notification (event category: `dashboard_module-activation-notification`). Note that there is already another event there which should not be erased - both events should be fired for the same interaction, as they are relevant in different tracking contexts.
    * For each of the above, the module slug should be used as event label.
* A `deactivate_module` GA event should be fired when **confirming the disconnect dialog** after clicking the button to disconnect a module from within _Settings > Connected services_ (event category: `settings_module-list`). The module slug should be used as event label.

### Module setup

* A `view_module_setup` GA event should be fired whenever the `ModuleSetup` component is first rendered.
* A `complete_module_setup` GA event should be fired whenever a module setup is completed (via the `finishSetup` callback within `ModuleSetup`).
* A `cancel_module_setup` GA event should be fired whenever a module setup is explicitly cancelled (via the "Cancel" button within `ModuleSetup`).
* For each of the above 3 events the event category should be `moduleSetup`, and the module slug should be used as event label.

### Idea Hub activation prompt notification

* In addition to the extra `activate_module` event within this Idea Hub notification (see above), the existing 3 events that are currently Idea Hub-specific should all be renamed, as follows:
    * The event category for the three of them should be `dashboard_module-activation-notification`.
    * The event names should be `view_notification`, `confirm_notification`, and `dismiss_notification` respectively.
    * The event label for all three of them should be the module slug, which technically can be hard-coded to `idea-hub` here.
    * Just to explain why the above renaming: In the future we are going to introduce a generic component for this that also can work for other modules, but that should not be part of this issue.

## Implementation Brief

* **Module activation and deactivation:**
  * In `assets/js/components/settings/SetupModule.js`:
    * Add `trackEvent( '${ VIEW_CONTEXT_SETTINGS }_module-list', 'activate_module', slug )` call to the `onSetup` callback.
  * In `assets/js/components/ActivateModuleCTA.js`:
    * Add `trackEvent( '${ VIEW_CONTEXT_DASHBOARD }_widget-activation-cta', 'activate_module', moduleSlug )` call before the `onCTAClick` callback.
  * In `assets/js/components/ModulesList.js`:
    * Update the `trackEvent` function call in the `handleSetupModule` callback to use `${ VIEW_CONTEXT_DASHBOARD }_authentication-success-notification` category instead of `${ slug }_setup` and `activate_module` instead of `module_activate`.
  * In `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js`:
    * Update the event names for existing `trackEvent` calls:
      * `confirm_notification` instead of `prompt_widget_setup`
      * `view_notification` instead of `prompt_widget_view`
      * `dismiss_notification` instead of `prompt_widget_dismiss`
    * Use `${ VIEW_CONTEXT_DASHBOARD }_module-activation-notification` as the event category and `idea-hub` as the event label for updated events.
    * Add `trackEvent( '${ VIEW_CONTEXT_DASHBOARD }_module-activation-notification', 'activate_module', 'idea-hub' )` call to the `onButtonClick` callback before navigation. It can be placed after the existing `trackEvent` call, but do not delete it or replace the existing `trackEvent` call.
  * In `assets/js/components/settings/SettingsActiveModule/ConfirmDisconnect.js`:
    * Add `trackEvent( '${ VIEW_CONTEXT_SETTINGS }_module-list', 'deactivate_module', slug )` call to the `handleDisconnect` callback.
* **Module setup:**
  * In `assets/js/components/setup/ModuleSetup.js`:
    * Add `useMount` hook that calls `trackEvent( 'moduleSetup', 'view_module_setup', moduleSlug )`.
    * Add `trackEvent( 'moduleSetup', 'complete_module_setup', moduleSlug )` call to the `finishSetup` callback.
    * Add a new callback for the cancel button that calls `trackEvent( 'moduleSetup', 'cancel_module_setup', moduleSlug )`.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Install the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) extension for your Google Chrome if you haven't done it yet.
* Verify that events mentioned in AC are triggered correctly.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@felixarntz this is ready for IB review but I am not sure about the following section in AC:

> All of the event categories mentioned below should technically rely on the VIEW_CONTEXT_* constants for their first name segment (i.e. don't hardcode "dashboard" but use the constant instead).

How do we need to use it for new events? :thinking:

**Comment by felixarntz** [comment]
@eugene-manuilov The IB looks pretty much good to go, regarding your question: Technically, for this issue, it would be fine to just use the constants instead of hard-coding, e.g.
* `${ VIEW_CONTEXT_DASHBOARD }_widget-activation-cta` instead of `dashboard_widget-activation-cta`
* `${ VIEW_CONTEXT_SETTINGS }_module-list` instead of `settings_module-list`

However, for other events that can happen in multiple view contexts (relevant e.g. #4006) I think it would be most appropriate if we could rely on the current view context. We have that in the `Root` component, so maybe we could build a simple `ViewContextProvider` component to use there and a `useViewContext` hook? Depending on the effort that would take we should only do that for #4006 though, since we need #4004 and #4005 ready for the Idea Hub launch.

**Comment by eugene-manuilov** [comment]
> However, for other events that can happen in multiple view contexts (relevant e.g. #4006) I think it would be most appropriate if we could rely on the current view context. We have that in the `Root` component, so maybe we could build a simple `ViewContextProvider` component to use there and a `useViewContext` hook? Depending on the effort that would take we should only do that for #4006 though, since we need #4004 and #4005 ready for the Idea Hub launch.

Yes, let's look at it in #4006. IB is updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ 

@eugene-manuilov I have been through all of the AC's but I have two observations that would like some clarification on:

On this entry in the AC: 

> When clicking the CTA button to activate Idea Hub in the (currently) Idea Hub-specific activation prompt notification

Is `dashboard_module-activation-notification` expected on both CTAs, i.e. the top banner and CTA within the Idea hub widget? I am only seeing it in the widget CTA, so wanted to check.

> The event names should be view_notification, confirm_notification, and dismiss_notification respectively.

Could you clarify where I should be seeing these event names because I cannot see them when I'm setting up, cancelling and completing the setup.  It's possible I am missing in them amongst all the events.

**Comment by eugene-manuilov** [comment]
> When clicking the CTA button to activate Idea Hub in the (currently) Idea Hub-specific activation prompt notification (event category: dashboard_module-activation-notification). Note that there is already another event there which should not be erased - both events should be fired for the same interaction, as they are relevant in different tracking contexts.
> 
> In addition to the extra activate_module event within this Idea Hub notification (see above), the existing 3 events that are currently Idea Hub-specific should all be renamed, as follows:

@felixarntz could you please confirm that these changes should be made in the Idea Hub notification component and not in the Dashboard CTA widget for Idea Hub?

**Comment by felixarntz** [comment]
@eugene-manuilov Yes, the changes should only be made on the Idea Hub notfication, that shows on top of the dashboard, not the (somewhat similar) CTA that shows within the widget. When I look at https://github.com/google/site-kit-wp/pull/4033/files#diff-f18f0c1049173587e09a47145d440a1d1853a4e4b237215aac02eaac4cccbd61, it looks like that was indeed changed in the widget, but it should only affect the dashboard notification. The widget should keep its previous `prompt_widget_view` etc events.

**Comment by eugene-manuilov** [comment]
Ok, i'll create a follow-up PR.

**Comment by eugene-manuilov** [comment]
@tofumatt do you mind reviewing a follow-up PR? #4063

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified that I have been through all of the ACs for Module activation and deactivation, Module setup and Idea Hub activation prompt notification. I can confirm that the events are triggured as per the ACs. The initial issue [reported here](https://github.com/google/site-kit-wp/issues/4004#issuecomment-920931146) has been fixed and the dashboard_module-activation-notification event is only triggered at the top large CTA, and not the widget anymore.
