### ISSUE TITLE
Update GA event categories and a few names for Idea Hub-specific events

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4005]
Related to our GA tracking event refinements, some event categories and names for Idea Hub events should be updated. This issue is limited to only renamings and no logic changes, so it should be rather straightforward.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All of the event categories mentioned below should technically rely on the `VIEW_CONTEXT_*` constants for their first name segment (i.e. don't hardcode "dashboard" but use the constant instead).
* The `idea_hub_widget` GA event category should be renamed to `dashboard_idea-hub-widget` across all usages (including widget-specific tooltip tour).
* The GA event category for the Posts screen-specific Idea Hub tooltip tour should be renamed to `postsList_idea-hub`.
* The `newposts_notification_view`, `newposts_notification_complete`, and `newposts_notification_dismiss` events should be renamed as follows:
    * The event category for the three of them should be `postsList_idea-hub-new-ideas-notification`.
    * The event names should be `view_notification`, `confirm_notification`, and `dismiss_notification` respectively.
* The `savedposts_notification_view`, `savedposts_notification_complete`, and `savedposts_notification_dismiss` events **on the Posts screen** should be renamed as follows:
    * The event category for the three of them should be `postsList_idea-hub-saved-ideas-notification`.
    * The event names should be `view_notification`, `confirm_notification`, and `dismiss_notification` respectively.
* The `savedposts_notification_view`, and `savedposts_notification_complete` events **in the WP dashboard widget** should be renamed as follows:
    * The event category for both of them should be `wpDashboard_idea-hub-saved-ideas-notification`.
    * The event names should be `view_notification`, and `confirm_notification` respectively.

## Implementation Brief

* In `assets/js/modules/idea-hub/datastore/constants.js`:
  * Update the value of the `IDEA_HUB_GA_CATEGORY_WIDGET` constant to be `${ VIEW_CONTEXT_DASHBOARD }_idea-hub-widget`
  * Update the value of the `IDEA_HUB_GA_CATEGORY_POSTS` constant to be `${ VIEW_CONTEXT_POSTS_LIST }_idea-hub`
  * Update the value of the `IDEA_HUB_GA_CATEGORY_WPDASHBOARD` constant to be `${ VIEW_CONTEXT_WP_DASHBOARD }_idea-hub-saved-ideas-notification`
* In `assets/js/googlesitekit-idea-hub-post-list.js`:
  * For the `newposts_notification_view`, `newposts_notification_complete`, and `newposts_notification_dismiss` events:
    * Update the category to be `{ VIEW_CONTEXT_POSTS_LIST }_idea-hub-new-ideas-notification`.
    * Rename event names to `view_notification`, `confirm_notification`, and `dismiss_notification` respectively.
  * For the `savedposts_notification_view`, `savedposts_notification_complete`, and `savedposts_notification_dismiss` events:
    * Update the category to be `{ VIEW_CONTEXT_POSTS_LIST }_idea-hub-saved-ideas-notification`.
    * Rename event names to `view_notification`, `confirm_notification`, and `dismiss_notification` respectively.
* In `assets/js/components/wp-dashboard/WPDashboardIdeaHub.js`:
  * Rename the `savedposts_notification_view` and `savedposts_notification_complete` events to be `view_notification` and `confirm_notification` respectively.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Install the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) extension for your Google Chrome if you haven't done it yet.
* Verify that events mentioned in AC are triggered correctly.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that all of the events mentioned in AC are triggered correctly, i.e posts feature tour, posts screen and WP dashboard.  - [Screenshot 1](https://user-images.githubusercontent.com/73545194/133641104-c4f95d1b-6fc1-475d-a1e8-ca24433aa705.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/133641133-f89b92fd-6c97-4423-9e27-e8d1c9d3b4d3.png) - [Screenshot 3](https://user-images.githubusercontent.com/73545194/133641155-006a067a-7049-4ec4-85dc-c28bc4effc7a.png)
