### ISSUE TITLE
Remove the extra Idea Hub widget state for no ideas without the tabs

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4013]
While the original Figma design had the specific state where, if there are no ideas in any of the tabs, the tabs don't even show, this is actually undesirable. It is unnecessary to have this as an extra state, it creates a weird jump because the loader UI has the tabs show up, and it also doesn't create a visual expectation of what the _populated_ widget will look like.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The extra state for not displaying the tabs when there are no ideas in the Idea Hub widget at all should be removed.
* In other words, in that situation, the widget should still show up as usual, with all three tabs in their respective zero data state.
* Since there are specific tracking events being fired for the state that there are no ideas at all (`widget_gathering_data_view` vs `default_tab_view`), the logic still needs to be kept somehow - just visually, there should be no difference from the state where you have no new ideas, but ideas in other tabs.
    * There is actually one part in this logic that is currently incorrect: The two events should be alternative, i.e. `default_tab_view` should fire if there are _any_ ideas. The current extra check for `hasManyIdeas` is incorrect and should be removed, it should just be an `else`.

## Implementation Brief

Inside `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`
* Remove the [block of code at line 235](https://github.com/google/site-kit-wp/blob/432169cf919941bf76397c1d25ec77c74334fdaf/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js#L235), because we want to render the widget even if `hasNoIdeas` is true. 
* Replace the `else if ( hasManyIdeas )` [on line 158](https://github.com/google/site-kit-wp/blob/432169cf919941bf76397c1d25ec77c74334fdaf/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js#L158) with a simple `else` - if there is even one idea we want to fire `default_tab_view`; if there are none at all we want to fire `widget_gathering_data_view`.

### Test Coverage

* No new tests required

### Visual Regression Changes

* Images related to the Idea Hub dashboard widget may need updating.

## QA Brief

* For the tracking, you'll need to add the [Google Analytics Debugger]( https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) browser extension
* Install the extension following the instructions, and then make sure you opt in to tracking via the Site Kit settings.

* When there are no ideas of any sort, the Idea Hub dashboard widget should still display the tabbed state (rather than the previous, un-tabbed 'empty' state from the designs).
* The `widget_gathering_data_view` should be fired in this scenario.
* When there is at least one idea of any sort (be it a saved idea, new idea etc), the `default_tab_view` event should be fired.

## Changelog entry

* Show Idea Hub tabs even when no ideas are available.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@johnPhillips could we jump on a call about this ticket, will ping you in Slack to arrange.  I am not seeing  `widget_gathering_data_view` in the event data. Unless it's my eyes, its difficult looking through all of the data without coffee.

![image](https://user-images.githubusercontent.com/73545194/133649490-9182a39c-040c-409b-ba92-9488161d93b5.png)

**Comment by johnPhillips** [comment]
Just a note as to how we managed to QA this. The event actually fires:
- only once
- only when the widget is in view

https://github.com/google/site-kit-wp/blob/60f800a936f5920d843fbe08c2e8aa14c5c4805c/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js#L145

So if you load the page but **don’t** scroll down, the event won’t fire. You then empty the ideas using the testing plugin, let the page load, and _then_ scroll down.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `widget_gathering_data_view` is fired when there are no ideas within the widget.  - [Screenshot](https://user-images.githubusercontent.com/73545194/133792641-314d9f1c-9834-4988-9637-f57a1bb359f1.png)

- When there is at least one idea the `default_tab_view` event is fired. - [Screenshot](https://user-images.githubusercontent.com/73545194/133792691-ced10c7f-1dad-4370-ac2f-44ee814c0e4e.png)
