### ISSUE TITLE
cURL error 6: getaddrinfo()

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4021]
## Bug Description

There have been 2 reports of a `cURL error 6: getaddrinfo()` dashboard notice from users. In one users case it occurs repeatedly, even after redoing the plugin setup as advised within the warning. For this user the notice no longer occurs when the "Regenerate Thumbnails" plugin is deactivated. 

Awaiting insights from the other impacted user. Unable to recreate the same issue support side from testing with the same plugin so far. 

- https://wordpress.org/support/topic/error-curl-error-6-getaddrinfo-thread-failed-to-start-error | **Open** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjplQpnlO3Ov1tjTGOFzornT57pjldQHIufKKtavO1g3hIemQMRPUAlgvloh5c6mtw)
- https://wordpress.org/support/topic/site-kit-stopped-working-the-response-is-not-a-valid-json-response | Impacted user to create their own support topic 
 
## Screenshots

![image](https://user-images.githubusercontent.com/41326532/133077395-c47b15cf-45c4-46be-810c-7c2332f7d6d1.png)

 - Site Kit 1.40.0
 - Unable to reproduce in support using the same Regenerate Thumbnails plugin
 - Site Kit was working previously for the [user who first report this](https://wordpress.org/support/topic/checking-structured-data-box-disappears/#post-14865622)
 - The the [second report](https://wordpress.org/support/topic/site-kit-stopped-working-the-response-is-not-a-valid-json-response) a user downloaded to PHP 7.3 from 7.4 after encountering separate issues. While SK worked as expected with PHP 7.3 they then encountered this warning. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
Per discussion on today's call, this is an expected error when the user needs to connect AdSense and Analytics. Closing this issue.

**Comment by jamesozzie** [comment]
Just adding some additional context to the above. The console errors as per the screenshot below _(which come from one one of the impacted users_) are as a result of not connecting services. 

![image](https://user-images.githubusercontent.com/41326532/134510082-7211bda2-d6b5-4ded-b39c-11145c2a1dc8.png)

The cURL specific error is likely hosting related, and not something that can be addressed on the plugin side.

**Comment by harishgeekpeek** [comment]
I found this error and i have no idea what should i Do

**Comment by jamesozzie** [comment]
Thanks for the input @harishgeekpeek. So we can determine more on this please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) over on the plugins WordPress support forums, where we provide initial support assistance. 

Please include all relevant details in order for us to assist. This may include [sharing your Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/), so we can check your current setup. I'll keep an eye out for your topic. Thank you!
