### ISSUE TITLE
Search Console dashboard search funnel widgets have extra wrapping grid cell

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4023]
## Bug Description

The Search Console widgets added to the dashboard Search Funnel widget area currently have extra wrapping grid cell div around the widget body which the other Analytics widgets in the area do not have.

https://github.com/google/site-kit-wp/blob/7694b6eaa06c9015db92dfbc2c722824b6943441/assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js#L142-L143

![image](https://user-images.githubusercontent.com/1621608/133102779-97925d86-540d-4fd4-95a7-e9c84ddfa222.png)

The widget body should only include the `DataBlock` as the Analytics’ Search Visitors and Goals widgets do.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The unnecessary extra wrapping `div` around the `DataBlock` in the Search Console `DashboardImpressionsWidget` and `DashboardClicksWidget` should be removed.

## Implementation Brief

* In the file [assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js](https://github.com/google/site-kit-wp/blob/316208ec2d86ecda90b7e86f7d772b0c5030e223/assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js), remove the rendered `div` that wraps the `DataBlock` component.
* Repeat the above, for the file [assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js
](https://github.com/google/site-kit-wp/blob/316208ec2d86ecda90b7e86f7d772b0c5030e223/assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js).

### Test Coverage

* No new tests to be added.
* Existing tests should pass.

## QA Brief

* Verify that the Impressions and Clicks widgets in the Search Funnel area have not been impacted by this change.

![image](https://user-images.githubusercontent.com/18395600/140907334-b741e37c-c02a-429c-b94d-af9dc0497460.png)

## Changelog entry

* Fix extra padding around Search Console widgets.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:
