### ISSUE TITLE
SwG module should accept non-domain Publication IDs

### ISSUE THREAD

**Issue by ChrisAntaki** [google/site-kit-wp#4025]
## Bug Description

The SwG module currently rejects non-domain Publication IDs. This is an issue, because Publisher Center will generate randomized non-domain Publication IDs

## Steps to reproduce

1. Go to the SwG module setup or settings page
2. Enter a Publication ID like "Test"
3. See validation error

## Screenshots

![image](https://user-images.githubusercontent.com/1216762/133138708-cbcf5db1-5016-4ed2-94d9-99be5e8a92db.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It should be possible to submit the Subscribe with Google module setup _and_ settings form when entering a publication ID that is not a domain. A "random" alphanumeric character combination should be allowed too.

## Implementation Brief

* Change a RegEx pattern (https://github.com/google/site-kit-wp/pull/4026/files)

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Enable the `swgModule` feature flag with the tester plugin
* Click "Set up Subscribe with Google" on the Settings > Connect More Services page
* Fill out the form
  * The Publication ID field expects a string. The string can contain letters, numbers, underscores (`_`), periods (`.`), and dashes (`-`)

## Changelog entry

* Fix validation for Subscribe with Google publication ID so that it allows non-domain input.

**Comment by felixarntz** [comment]
@ChrisAntaki IB ✅ 

Two general recommendations though for the future:
* Here it's trivial enough, but typically it's better to not start the PR before getting an IB through. Instead you could have said something like "...so that it doesn't require ending in `.[a-z]`" in the IB.
* Preferably write the IB as a set of instructions. E.g. "Change a RegEx..." instead of "I'll change a RegEx...".

**Comment by felixarntz** [comment]
@ChrisAntaki Can you please add a QA Brief to the issue?

**Comment by ChrisAntaki** [comment]
Yep, just added a QA brief :+1:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When the Publication ID field is populated, I am able to enter a string that contains letters, numbers, underscores periods, and dashes.  When any other characters are entered, the input field border turns red. 

![image](https://user-images.githubusercontent.com/73545194/133802808-51e451cd-4753-43be-bd98-856bc668cf4d.png)

@ChrisAntaki @felixarntz there are two observations outside of the scope of this ticket, and I might be jumping ahead of myself, but wanted to ask:

1) The `Product(s)` field doesn't have any validation, in that you can enter any characters.  You are also unable to leave any spaces, is that expected? I also noticed that there is no limit with the number of characters you can include in this field too.  

2) On the `Publication ID` field, when you enter a character not allowed like `&` or `$` there is no message to help the user understand what they have done wrong.
