### ISSUE TITLE
Scaffold Unified Dashboard Feature Flag

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4029]
## Feature Description

To get started on the development of the new, Unified Dashboard we'll want a feature flag to develop the new dashboard behind.

The feature flag should be named `unifiedDashboard`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A feature flag named `unifiedDashboard` should be present to develop all Unified Dashboard features behind.

## Implementation Brief

* Add a feature flag named `unifiedDashboard` to `feature-flags.json`.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* The feature flag `unifiedDashboard` should be present in `feature-flags.json`.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Not much to QA here... the feature flag is there now 😄 

## QA ✅  

https://github.com/google/site-kit-wp/blob/dbd784e137e82801f79b535c3e93094b4c4cde2a/feature-flags.json#L1

Moving to Approval 🚀
