### ISSUE TITLE
Site URLs in Google Analytics appear with double slashes at the end of paths

### ISSUE THREAD

**Issue by westonruter** [google/site-kit-wp#4036]
## Bug Description

Originally reported in https://github.com/google/site-kit-wp/issues/3752#issuecomment-887685802, I have odd-looking URLs appearing in Google Analytics:

> ![image](https://user-images.githubusercontent.com/134745/127197904-5fdb21f8-de19-45c0-be4a-77b59b6d3574.png)

Note the doubled-slashes appearing at the end of each URL. This also appears in the Analytics widget on the Site Kit dashboard:

> ![image](https://user-images.githubusercontent.com/134745/133292052-7e9684f2-0ad7-4b28-8cd5-46a7c5aecb98.png)

Note that my site, weston.ruter.net, is running AMP in the standard template mode, so it is using `amp-analytics`. The snippet added by Site Kit is as follows:

```html
<!-- Google Analytics AMP snippet added by Site Kit -->
<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json">{"optoutElementId":"__gaOptOutExtension","vars":{"gtag_id":"UA-XXXXXX-1","config":{"UA-XXXXXX-1":{"groups":"default","linker":{"proxyOnly":true}}}}}</script></amp-analytics>
<!-- End Google Analytics AMP snippet added by Site Kit -->
```

(Naturally my actual analytics account ID and not `UA-XXXXXX-1`.)

Note that I'm also running a plugin with the following PHP code:

```php
add_filter(
        'googlesitekit_amp_gtag_opt',
        function ( $gtag_opt ) {
                foreach ( $gtag_opt['vars']['config'] as &$config ) {
                        $config['linker'] = [
                                'proxyOnly' => true,
                        ];
                }
                return $gtag_opt;
        }
);
```

This was a workaround for #2010 but it's apparently no longer needed.

## Steps to reproduce

1. Have my site weston.ruter.net 😉 
2. Enable analytics 
3. Possibly enable AMP in standard template mode.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Ah, it's not AMP-specific because I actually have AMP disabled for https://weston.ruter.net/2018/02/21/spoken-word-read-along-tts/ 

Nevertheless, the `spoken-word-read-along-tts` URL ends in `//` in Analytics.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov this one is with you for a while now; is it still an issue? If so, is it still a P0?

**Comment by eugene-manuilov** [comment]
> @eugene-manuilov this one is with you for a while now; is it still an issue? If so, is it still a P0?

@aaemnnosttv I can't say exactly because I haven't had a chance to look at this issue yet.

**Comment by eugene-manuilov** [comment]
@westonruter could you please tell me what you see in Google Analytics? Do you see double slashes there too or is it just in the plugin?

**Comment by westonruter** [comment]
Yes, actually my screenshots in the description show what it looks like in Google Analytics and also the dashboard widget. In both, there are double slashes.

**Comment by eugene-manuilov** [comment]
Hm... that's weird... :thinking: Looks like something goes wrong when GA tracks page views... @aaemnnosttv or @felixarntz do you know why it can happen?

**Comment by eugene-manuilov** [comment]
I have checked the tracking event and everything seems correct to me... 

![image](https://user-images.githubusercontent.com/873049/144101850-0ec98786-4327-49b0-8bc0-7853a60f9340.png)

**Comment by westonruter** [comment]
I found someone else report this 3 years ago regarding Google Analytics generally: https://www.reddit.com/r/GoogleAnalytics/comments/9yqlic/double_slashes_in_my_data/

**Comment by bethanylang** [comment]
No other reports; closing.
