### ISSUE TITLE
Fix Storybook deprecation warnings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4042]
## Bug Description

Storybook is currently raising a number of deprecation warnings that should be addressed.

E.g. 

```
DeprecationWarning: Relying on the implicit PostCSS loader is deprecated and will be removed in Storybook 7.0.
If you need PostCSS, include '@storybook/addon-postcss' in your '.storybook/main.js' file.
```

Many warnings are also being raised during Backstop runs, due to duplicate titles.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No deprecation warnings should be raised from Storybook during build or viewing stories
    * Some deprecation warnings are only triggered when viewing a story (e.g. "Duplicate title used in multiple files; use unique titles or a primary file for a component with re-exported stories." https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-support-for-duplicate-kinds) – this can be seen during VRT runs

#### Fix for Implicit PostCSS Loader Warning:

Storybook 6 has deprecated the implicit `postcss-loader`, we must load it explicitly. See [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader).

* Add `@storybook/addon-postcss` to the project as a development dependency. 
* Add `@storybook/addon-postcss` to the addons array in `.storybook/main.js`. 
* We already have a `postcss.config.js` so we can ignore that step of the Migration Guide. 

#### Fix Duplicate Title Errors:

Duplicate Titles were also deprecated in Storybook 6. We have a few instances of that in the following files that needs to be migrated following the guide [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-support-for-duplicate-kinds). 

Affected Titles: 

* `Components/Surveys`
    * `assets/js/components/surveys/SurveyCompletion.stories.js`
    * `assets/js/components/surveys/SurveyQuestionMultiSelect.stories.js`
    * `assets/js/components/surveys/SurveyQuestionOpenText.stories.js`
    * `assets/js/components/surveys/SurveyQuestionRating.stories.js`
    * `assets/js/components/surveys/SurveyQuestionSingleSelect.stories.js`

### Test Coverage

* `npm run test:storybook` and `npm run storybook` should no longer throw any deprecation warnings. 

### Visual Regression Changes
* N/A

## QA Brief
* Ensure no deprecation warning about "implicit PostCSS loader" upon running `npm run storybook`
* Ensure no duplicate titles errors are displayed in the browser's console when running storybook.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
> * stories/report-error.stories.js

@kuasha420 this file has been migrated to `assets/js/components/ReportError.stories.js`. Could you please check if there are still duplicate titles issues in that file or it's good now? Also, let's probably bump the estimate a bit because such tasks always take longer due to different pitfalls that can't be forecasted at the beginning.

**Comment by kuasha420** [comment]
@eugene-manuilov Thanks! Duplicate Title for `Global` is no longer an issue in `develop` and has been removed from the IB. Also bumped the estimate up. Cheers!

**Comment by eugene-manuilov** [comment]
Thanks, @kuasha420. IB :heavy_check_mark:

**Comment by ivankruchkoff** [comment]
QA ✅

No deprecation warning, no duplicate titles error.
