### ISSUE TITLE
Add a content area to the Header in the Unified Dashboard for Entity Info and notifications

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4050]
## Feature Description

There should be a section in the header of the dashboard that displays content in the view between the header and the pill links, see:

<img width="840" alt="Screenshot 2021-09-28 at 16 19 49" src="https://user-images.githubusercontent.com/90871/135116463-3ddcb04e-5260-46ce-ae6f-6e290fd99c2b.png">

The logic to display this content is covered elsewhere; this issue is just above creating the component that can be used to style either the Entity information (shown above) or the Notifications that appear in this area when any are present.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new prop `subHeader` should be added to the `Header` component. It should be used to place arbitrary content in the header area highlighted in the screenshot. It should appear below the `<header>` tag in the `Header` component. (https://github.com/google/site-kit-wp/blob/5f12f3b3b59b1517bc2a0efa4d427120de2e4239/assets/js/components/Header.js#L41-L71)
* This prop should be used by the components in #4146 and #4152 to wrap their output when inside the `<Header>` component
* When the `subHeader` prop is passed components/eg. a non-`null` value, the output should match the styles in the Figma mockup: https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe/%5BMVP%5D-Generic-Dashboard?node-id=459%3A2117 (note how the bottom border/shadow of the header becomes the border/shadow of the subheader instead when there is one, i.e. it's almost like the header expands). There should be no inner padding though as that should be defined by whatever is rendered within the container.
* The component should NOT be sticky, unlike the rest of the header. When the user scrolls down the page, this section of the header should disappear and not follow the user down the page.
* The `BannerNotifications` component from #4152 should be rendered within the new sub-header container, but only if on the "main dashboard" (i.e. not if on the "entity dashboard").

## Implementation Brief

**Integration in `Header`**
* Update `Header` to accept a new `subHeader` prop which should take an optional `element`
  - If provided, this element should be rendered in a new grid inner (row), and full-width grid cell below the existing elements wrapping the main menu (i.e. as a child of `mdc-layout-grid`)
* Update `stories/header.stories.js` to add a new story for showing the header with a dummy component
* Add `subHeader={<BannerNotifications />}` to the `DashboardMainApp`'s `Header` component (https://github.com/google/site-kit-wp/blob/94ab93a3bf301b165aebfdb0b4df75a815ffd96b/assets/js/components/DashboardMainApp.js#L42) to output the notifications on the Main Dashboard.

### Test Coverage

* Add a Storybook story to show what the header looks like with "Empty" or "Dummy" content—eg the padding and extra border dividing the header from the subheader should appear, with another border between the subheader and navigation

## QA Brief
* Enable the `unifiedDashboard` feature flag.
* Check if the a notification is rendered below the header at the following URL: `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success`
* There should be no visible lines separating the header and the sub header content.
* Scroll down the page, the header should be sticky.

## Changelog entry

* Add a generic content area for the Header in the Unified Dashboard.

**Comment by tofumatt** [comment]
Totally, that's actually a way better approach and I think will totally work for what we want to do. I think I even wanted to propose it in the ACs originally, but for some reason I guess my brain went with the more imperative approach.

But Slot/Fill is way nicer AND less code! 🙂 

I've updated the ACs, let's go with that approach. If any other ACs related to this issue need updating I'll do that too 👍🏻

**Comment by tofumatt** [comment]
Hmmm, we shouldn't be rendering the `<Subheader>` area at all if there are no notifications/no entity info to show though. It requires another border to be drawn between the `Header` and the Navigation bar.

I suppose if it's currently only possible for one piece of content to appear in the header at a time—given notifications won't appear on the Entity Dashobard… maybe this should just be thought of as the "wrapper component" with no logic. I think that makes sense, but it's just a re-framing of the issue.

I've updated the ACs again, but I've assigned you to have a look at them to make sure they make sense @felixarntz. If they're good feel free to move this over to IB 👍🏻

**Comment by felixarntz** [comment]
@tofumatt Actually, one more question about the ACs:
> This prop should be used by the components in #4146 and #4152 to wrap their output when inside the `<Header>` component

How do you envision that to work? The `Notifications` component e.g. would be rendered within the `Header`, how can it pass a prop to the `Header`?

**Comment by tofumatt** [comment]
> @tofumatt Any particular reason why you removed the one extra bullet point I had added to the ACs (see #4050 (comment))? I assume it was by accident, so I've added it back for now. Let me know your thoughts - if we keep it, we should also mention that in one extra point in the IB (otherwise the IB looks good).

100% a mistake, thanks for catching that! 👍🏻 

> How do you envision that to work? The `Notifications` component e.g. would be rendered within the `Header`, how can it pass a prop to the `Header`?

I don't think it would need to be—I think the notifications component (in this case, `BannerNotifications` from #4152) could be supplied to the `subHeader` prop whenever needed (eg in the `DashboardMainApp` component, right here: https://github.com/google/site-kit-wp/blob/94ab93a3bf301b165aebfdb0b4df75a815ffd96b/assets/js/components/DashboardMainApp.js#L42).

We can supply multiple components into the `subHeader` when needed by wrapping in a `<Fragment>`, though I think for now the Main Dashboard just needs notifications and the Entity Dashboard just needs the component in #4146.

Does that sound good?

**Comment by felixarntz** [comment]
@tofumatt Ahh, thanks for clarifying. I think I was confused by the wording: "This prop should be used by the components in #4146 and #4152 to wrap their output when inside the `<Header>` component" says it should be used _by_ the components, but the way I understand you now, which makes sense to me, the prop should be used by any component to _pass_ the inner components :)

Now that that's clarified, that makes sense. Note though that current approach still **wouldn't** ensure that the sub-header only renders if there is actually something in there. That is because e.g. the `BannerNotifications` component contains logic inside and based on the logic may return `null`. In that case, there would still be an empty sub-header. Which again, _may_ not be a dealbreaker if we can ensure that empty container doesn't have a visual impact, but I want to make sure you've considered that.

**Comment by felixarntz** [comment]
Sounds good - IB ✅

**Comment by felixarntz** [comment]
@asvinb Great points. Your point about a full-width container is also in the ACs - it says there that it shouldn't have any inner padding, which I basically meant to express with that it should be full-width and not assume/restrict anything about the content within :)

**Comment by wpdarren** [comment]
@felixarntz @asvinb @tofumatt Looking at the initial description and AC's, the QAB doesn't appear to be accurate. Please could you clarify if it is, and if not, any additional info would be appreciated.

**Comment by asvinb** [comment]
@wpdarren The QAB says going to the following URL: `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success`. In doing so, the `BannerNotifications ` component will be passed to the `Header` component via the `subHeader` prop. It's a way to test the latter. Then it should match the designs in Figma, meaning there should no be any borders between the header and the sub header (`BannerNotifications` in this case), and then only the header is sticky upon scrolling.

Let me know if that clears things up.

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- There are no visible lines separating the header and the sub header content.

![image](https://user-images.githubusercontent.com/73545194/140763831-e86cb888-3361-48c2-bab5-42590169faf6.png)

- When scrolling down the page, the header is sticky.

![image](https://user-images.githubusercontent.com/73545194/140764005-51a8b1b3-c46c-40aa-a536-1071b110f7ec.png)

- Confirmed the same behaviour for small screen sizes.
