### ISSUE TITLE
Add support for trigger conditions to remote survey questions

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4051]
Per requirement for the new Idea Hub survey, we need to make an additional enhancement to the surveys infrastructure itself: Currently it's only possible to show an alternate completion prompt based on an answer to a question. We now need to expand this functionality so that it works for follow-up questions as well.

This is a launch blocker for Idea Hub, even though it's overall a general survey issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The survey infrastructure should receive support for conditionally displaying questions from the API response _if_ they include the respective data specification. More specifically:
    * If a `question` object includes a `trigger_condition` array that is not empty, that question should only be shown if all of the trigger conditions are met.
    * The format of the `trigger_condition` array can be expected to be exactly the same as for the property of the same name that is already handled for completion prompts. In other words, the logic to handle that can partly be copied, just it should affect the question that it is set on.
    * In other words, if any of the `trigger_condition` entries does not evaluate to `true` based on the answers the current user has given, the question should be skipped and not displayed to the user.
    * No validation for whether a condition is actually "reasonable" needs to be included, this can be expected to always make sense from the API. For example, an question will never include a condition that is based on an answer to a question that would only show up afterwards, as that simply wouldn't make any sense. That also means technically that the first question (`question_ordinal` 1) will never have any trigger conditions, since there are no answers that could be based on.
    * Every question within a survey will still have a different `question_ordinal`, no question will have the same as another, in order to uniquely distinguish them. That means, going forward, for example the question with `question_ordinal` 2 may not necessarily be the second question that is displayed - if it has a `trigger_condition` that isn't satisfied, it would be skipped, so that essentially the following question (`question_ordinal` 3) would be the second question that is displayed.
* A few examples to outline how this should work:
    * Let's say a survey starts with a rating question. There's another question with ordinal 2 that only shows for rating 4-5, and another question with ordinal 3 that only shows for ratings 1-2.
        * If the user rates 4, question 3 should be skipped.
        * If the user rates 2, question 2 should be skipped.
        * If the user rates 3, both questions should be skipped, i.e. after question 1 it should immediately go to the completion prompt.
    * Another example, now with a `single_select` question as first item with two options `yes` and `no`. There's another question with ordinal 2 that only shows if the user answered the first question with `yes`, and also another question with ordinal 3 that only shows if the user answered the second question with `yes`.
        * If the user answers `yes` to question 1, question 2 should be shown.
        * If the user answers `yes` to question 2, question 3 should be shown.
        * If the user answers `no` to question 1, both question 2 and 3 should be skipped.

## Implementation Brief

**The API infrastructure is currently being built. Depending on how quickly this gets implemented, the Site Kit Service part may not be ready yet. Please coordinate testing with @felixarntz.**

* The `questions` variable created in https://github.com/google/site-kit-wp/blob/48e8fe4b54b7990cb243ad66d39506957222dc4c/assets/js/components/surveys/CurrentSurvey.js#L66-L68 should be further modified/filtered when used in the rest of the component to only return the questions either:
  * with _no_ `trigger_condition` value
  * with `trigger_condition` values that are met by the existing survey data, using the `completions` variable in the component selected from the data store. Note that each `trigger_condition` shape will be the same as the conditions in `completions`, see https://github.com/google/site-kit-wp/blob/48e8fe4b54b7990cb243ad66d39506957222dc4c/assets/js/components/surveys/__fixtures__/index.js#L20-L35 for an example
* It would make the most sense to rename [`questions`](https://github.com/google/site-kit-wp/blob/48e8fe4b54b7990cb243ad66d39506957222dc4c/assets/js/components/surveys/CurrentSurvey.js#L66-L68) to `potentialQuestions` then declare `questions` below it based on the filtering described above, so other code can be kept consistent.

### Test Coverage

* Add tests to `assets/js/components/surveys/CurrentSurvey.test.js` to ensure the above described behaviour is working.

## QA Brief

* Visit https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys-currentsurvey--survey-multiple-questions-conditional-story and test out different answers, noting that different follow-up questions appear based on the first answer chosen.

## Changelog entry

* Add new conditional follow-up questions to user surveys.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by kuasha420** [comment]
QA: :heavy_check_mark: 

On the storybook, correct follow up question and/or completion appears based the value of first answer. It matches with the test case and AC. 

Pinging @wpdarren for for final rounds of QA and next step.

**Comment by wpdarren** [comment]
@kuasha420 I have picked up my QA on 4052, so if you are happy with this, I shall move to approved.
