### ISSUE TITLE
Improve instructions in Optimize setup

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#4064]
## Feature Description

Currently, the Optimize setup screen includes a sentence that reads "Please copy and paste your Optimize ID to complete your setup. You can locate this here.":

<img width="1414" alt="Screen Shot 2021-09-16 at 2 53 48 PM" src="https://user-images.githubusercontent.com/12189958/133669031-8cbf356a-c7cb-4baa-83e5-8e2eb41dc814.png">

"Optimize ID" is not correct; it should be "Container ID."

In addition, "You can locate this here" currently links to https://support.google.com/optimize/answer/6211921?hl=en-US, which is a long article about Optimize setup that doesn't include explicit instructions on where to find the Container ID. It would make more sense to link to https://optimize.google.com/optimize/home/?authuser=1&hl=en-US#/accounts, which is the main account page for Optimize and includes a list of all Containers and their IDs:

<img width="1079" alt="Screen Shot 2021-09-16 at 2 56 54 PM" src="https://user-images.githubusercontent.com/12189958/133669478-596fbe22-238b-40b3-9857-44c0e5e34296.png">

I recommend changing the text to read:

"Please copy and paste your Container ID in the field below to complete Optimize setup. You can locate this ID here." and link the final sentence to https://optimize.google.com/optimize/home/?authuser=1&hl=en-US#/accounts.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User-facing labels/references to "Optimize ID" for the Optimize module should be updated to `Optimize Container ID` in setup and settings views
    * The settings view label "Your Optimize Container ID" should also be updated for consistency
* The text "You can locate this here." should be updated as follows
    * Should link to the Optimize module's service URL with a path of `/accounts`
    * Should not have a trailing full-stop

## Implementation Brief

* Inside `assets/js/modules/optimize/` locate all `Optimize ID` copies and change it to `Optimize Container ID` inside followig files: 
     * https://github.com/google/site-kit-wp/blob/57c1d4fb61b6beada129515df8466e29e95feef2/assets/js/modules/optimize/components/common/OptimizeIDFieldInstructions.js#L43
     * https://github.com/google/site-kit-wp/blob/57c1d4fb61b6beada129515df8466e29e95feef2/assets/js/modules/optimize/components/common/OptimizeSnippetNotice.js#L51-L64
     * https://github.com/google/site-kit-wp/blob/57c1d4fb61b6beada129515df8466e29e95feef2/assets/js/modules/optimize/components/settings/SettingsForm.js#L62
     * https://github.com/google/site-kit-wp/blob/57c1d4fb61b6beada129515df8466e29e95feef2/assets/js/modules/optimize/components/setup/SetupForm.js#L87

* Change the link to optimize account by using :
```
	const accountURL = useSelect( ( select ) =>
		select( MODULES_OPTIMIZE ).getServiceURL( { path: '/accounts' } )
	);
```
 here:
https://github.com/google/site-kit-wp/blob/a86ba4b109defc7d4c89289b2ca0589da870e10b/assets/js/modules/optimize/components/common/OptimizeIDFieldInstructions.js#L34-L38 and configure `Link` to use new `accountURL `
* Remove the trailing full-stop in the copy here: https://github.com/google/site-kit-wp/blob/a86ba4b109defc7d4c89289b2ca0589da870e10b/assets/js/modules/optimize/components/common/OptimizeIDFieldInstructions.js#L47

### Test Coverage

Update/fix all relevant tests. (see `/tests/e2e/specs/modules/optimize/activation.test.js`)

## QA Brief

* In Optimize setup screen check 'You can locate this here' link to lead to the `/accounts` page without a full-stop at the end
* Check `Optimize Container ID` to appear instead of  `Optimize ID` in the text/labels/notices

## Changelog entry

* Improve instructions in Optimize setup and settings.

**Comment by aaemnnosttv** [comment]
> "Optimize ID" is not correct; it should be "Container ID."

@bethanylang this change is no big deal.

> In addition, "You can locate this here" currently links to [support.google.com/optimize/answer/6211921?hl=en-US](https://support.google.com/optimize/answer/6211921?hl=en-US), which is a long article about Optimize setup that doesn't include explicit instructions on where to find the Container ID. It would make more sense to link to [optimize.google.com/optimize/home/?authuser=1&hl=en-US#/accounts](https://optimize.google.com/optimize/home/?authuser=1&hl=en-US#/accounts), which is the main account page for Optimize and includes a list of all Containers and their IDs:

This would be a bit more consistent with other services, however Optimize doesn't seem to be consistent with other services in that it doesn't seem to allow for the user's email address to support multiple Google sign-in properly. That is, in your link you have `authuser=1` which indicates your Google account that you have your Optimize account with is not the default Google account you've signed into your browser with (i.e. you're signed in with multiple accounts). With other services we can send the user to the service URL using their email address in place of the `1` or `0`, etc which will ensure they end up on the service using the right account, or sign in if they aren't signed in with that one yet in that browser. Sometimes this authuser thing is in the URL path like `/u/1` etc but that doesn't seem to work here either.

If this is only about updating the language in the interface, it's a trivial change, but unfortunately I think we can't really use a deep link into the service without risking sending the user in with the wrong account.

**Comment by aaemnnosttv** [comment]
Note: the above problem should no longer be an issue now that we use the AccountChooser for service URLs.

**Comment by marrrmarrr** [comment]
Overall text and target link change LGTM!

**Comment by eugene-manuilov** [comment]
Thanks, @sashadoes. This is a good start, but I think it would be better if we add a bit more details. Could you please list all components where the label should be updated and provide a bit more instructions how we should update the link?

**Comment by sashadoes** [comment]
@eugene-manuilov thank you for the review and feedback. I have added new details 🙂

**Comment by eugene-manuilov** [comment]
> * Change the link according to`/accounts` here:

@sashadoes the link that you reference to lead to the support page which is not what we need. AC says: "link to the Optimize **module's service URL** with a path of /accounts". So, we need to rework the link to lead to the service URL, not to the support one.

**Comment by sashadoes** [comment]
@eugene-manuilov That Makes sense! Thank you 🙂

**Comment by eugene-manuilov** [comment]
> * Change the link to optimize account by using `const accountURL = useSelect( ( select ) => select( MODULES_OPTIMIZE ).getServiceURL());` here:

@sashadoes If you provide the full select snippet, then you need to add the `/accounts` parameter to the `getServiceURL` selector since otherwise it will return the URL to the optimize dashboard page on the service side. Could you please add a note that we need to use the `/accounts` path to make sure that we don't forget to add it?

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- In Optimize setup screen the text `Optimize Container ID` appears.
- The link leads to the /accounts page and does not have without a full-stop at the end of the text.
- Link URL is `https://optimize.google.com/optimize/home/?pli=1&authuser=2#/accounts`

![image](https://user-images.githubusercontent.com/73545194/203795944-94a3bfe6-bedd-40fb-b898-8da499540a97.png)
