### ISSUE TITLE
Remaining `helpVisibility` feature flag use

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4069]
## Bug Description

In #3685 we removed the `helpVisibility` feature flag to promote the feature to be always available although we missed one important instance which is still used for the feature tour. Now that the flag is removed this feature is technically not available by default. It will still be available to normal users due to its presence in the remote enabled flags.

## Steps to reproduce

1. Configure tester plugin to override all feature flags
2. Disable Analytics, and clear out any dismissed feature tours
3. Set initial SK version to 1.28.0
4. Visit SK dashboard
5. See help visibility tour not shown

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No usage of the `helpVisibility` feature flag should remain in the codebase

## Implementation Brief

* Remove the `checkRequirements` function for the `helpVisibility` feature tour
* Merge #4089 

### Test Coverage

* No changes

## QA Brief

* Enable tester plugin and configure it to override all feature flags with none selected
* Configure initial Site Kit version to `1.28.0`
* Clear dismissed tours for current user by deleting the `wp_googlesitekitpersistent_dismissed_tours` user meta
* Load the SK dashboard
* See help visibility tour

## Changelog entry

* Remove leftover use of `helpVisibility` feature flag.

**Comment by aaemnnosttv** [comment]
@tofumatt @eugene-manuilov I added a quick PR here given the simplicity of the change and timeliness to include this for the release. Assigning you both for whoever can get to it first 😄

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Can confirm that the help visibility tour appears as per QAB.

![image](https://user-images.githubusercontent.com/73545194/134177744-578f4199-62b6-4b72-a00d-e0ccaf4baf5e.png)
