### ISSUE TITLE
Introduce internal Site Verification module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#407]
Site Verification functionality is currently covered by the Search Console module. While there is some integration between the two APIs, they have distinct responsibilities and should not be intertwined. For example, while Search Console has a mechanism for controlling ownership of a site's Search Console property, the canonical source for actual site ownership is exposed via the Site Verification API. See related #359 for a previous confusion there.

Let's clearly split these responsibilities on the server as well by introducing a Site Verification module. The Site Verification module will be another auto-active module that is always required to run. However, it also will have one trait that is entirely new compared to the existing modules: it will be **internal** (i.e. the user should never see any of it or even know it is a module that is there).

The Site Verification module should only be responsible for providing the related datapoints on the server-side and providing the Site Verification API service. In other words, all of its initial functionality will be existing code moved there from the Search Console module.

The more substantial change will be to introduce the notion of internal modules. Those modules should have one specific difference in behavior: Anywhere where modules are listed or exposed to the user in another way, internal modules should be skipped. Each module should have an `internal` item in its properties, with a default value of `false`. Only the new Site Verification module would set this to `true`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `internal` array key (boolean) should be added to the base `Module` class, with a default value of `false`.
* Modules that are `internal: true` should be filtered out in module listings on the client, so that they are never displayed.
* A new `Site_Verification` module class should be added (server-side only).
    * It should set `internal` to true in its own data, and it should also be `force_active`, similar to `Search_Console`.
    * The `siteverification` service and responsibility for the `https://www.googleapis.com/auth/siteverification` scope should be moved from the `Search_Console` class to the `Site_Verification` class.
    * All datapoints that rely on the `siteverification` service (and the specific `siteverification` datapoint) should as well be moved from the `Search_Console` class to the `Site_Verification` class.
* The Site Verification step during plugin setup should continue to work as it does now from a user standpoint.

## Implementation Brief

* Add new `internal` array key with default value `false` to the `Module` base class, in `parse_info()`, `prepare_info_for_js()`, and a `@property-read` class annotation.
* Add `internal` key to the module schema in the `REST_Routes` class, in `get_module_schema()` and `prepare_module_data_for_response()`.
* In JavaScript, filter out modules that have the `internal` property set to `true` in [`ModulesList`](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/modules-list.js#L72) and [`SettingsModules`](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/settings/settings-modules.js#L215).
* Introduce new `Site_Verification` module class in PHP.
    * The `slug` should be `site-verification`.
    * In `setup_info()`, set `force_active` and `internal` to `true`.
    * Include `get_scopes()` method returning `https://www.googleapis.com/auth/siteverification` and remove that scope from the `Search_Console` module class.
    * In `setup_services()`, setup the 'siteverification' service (moved there from `Search_Console` module class).
    * Move all datapoints that make use of the `siteverification` service, as well as the `siteverification` datapoint, from `Search_Console` class to `Site_Verification` class.
* In [`SiteVerification` component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/setup/site-verification.js), replace `search-console` datapoint with `site-verification` datapoint.

## Changelog entry

* Introduce an internal Site Verification module, taking over applicable functionality from the Search Console module.

**Comment by aaemnnosttv** [comment]
Brief looks good to me, except this one line appears to be a typo?

> In JavaScript, filter out modules that have the inactive property set to true in ModulesList and SettingsModules.

`inactive` should be **`internal`**, correct?

**Comment by felixarntz** [comment]
@aaemnnosttv Yes, of course. :) Fixed it.

**Comment by felixarntz** [comment]
QA ✅
