### ISSUE TITLE
Update focus of Idea Hub feature tour

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4076]
## Feature Description

Currently the first step of the Idea Hub module's feature tour focuses on the _title_ of the widget. This should be updated to include the whole widget instead.

![image](https://user-images.githubusercontent.com/1621608/134019389-45a81dc8-6bf5-4cf4-88a4-fcc836e3d1da.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ideaHubModule` feature tour's first step should highlight the entire dashboard `ideaHubIdeas` widget

## Implementation Brief

* Update the `target` selector used by the `ideaHubModule` feature tour to `.googlesitekit-widget--ideaHubIdeas`

### Test Coverage

* N/A

## QA Brief

* Set up Idea Hub on a new site where the feature tour has not been seen. You should see the entire widget highlighted in the first step of the tour, not just the header as seen in the screenshot above.

## Changelog entry

* Update focus of Idea Hub module feature tour to highlight entire widget.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** Can see the entire widget highlighted in the first step of the tour, not just the header.

![image](https://user-images.githubusercontent.com/73545194/134192825-fe651c5c-6a82-46ef-a65b-b0f0fdf650a5.png)
