### ISSUE TITLE
Notifications REST endpoint should return an array of notification objects

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#408]
The `modules/(?P<slug>[a-z\-]+)/notifications` endpoint currently returns the module notifications list as part of an `items` property, which is unnecessary. Three additional values are sent as part of the root object:

* `url`
* `ctaLabel`
* `ctaTarget`

This is unexpected, since all these three should relate to the individual notification. At the moment, only one module (AdSense) makes use of the feature to send a single notification so it doesn't appear as an actual problem. But as soon as there are multiple notifications, the model with a general CTA doesn't make sense any longer.

The endpoint should be modified to return only an array of notification objects. Every notification object should contain its own `url` (renamed to `ctaUrl`), `ctaLabel`, and `ctaTarget` properties. The consuming JavaScript code must of course be updated to match the new structure.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/(?P<slug>[a-z\-]+)/notifications` route should return an array of notification objects which include `ctaUrl`, `ctaLabel`, and `ctaTarget` properties.
* Requesting AdSense notifications should continue to work properly.

## Implementation Brief

* Modify the `AdSense` module's `notifications` datapoint, with `url` (rename to `ctaUrl`), `ctaLabel`, and `ctaTarget` to be moved inside the notification associative array. Then it should only return what's currently in `items`.
* Modify notifications route in `REST_Routes` class, with `new \stdClass()` being replaced with `array()`, and the logic for putting numeric arrays into `items` being removed. The numeric array should be returned in the `WP_REST_Response` as is.
* Update [`Alert`](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/alert.js) module to match the changes in the REST response format, accessing the CTA properties from each `item`.
* Update [`getModulesNotifications()`](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/util.js#L145) to no longer return `cta` as that information is now in each notification.
    * Update [`DashboardModulesAlerts`](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/dashboard-modules-alerts.js) to access the CTA data from the notification individually (this code particularly shows why the original format of the API response does not make sense).
* Unrelated, but easy enough to fix, and in a related code area: This translator comment has no purpose and should be removed: https://github.com/google/site-kit-wp/blob/67dabf21c3fb1852ed57324eb05a9bde1e8a7a31/includes/Modules/AdSense.php#L497-L499

## Changelog entry

* Modify response format of notifications REST API endpoint to be a consistent array of objects.

**Comment by aaemnnosttv** [comment]
Brief looks good to me! 

One thing I noticed which is very minor is that there is a stray translators comment in the Adsense module which probably just needs to be moved or removed.

https://github.com/google/site-kit-wp/blob/67dabf21c3fb1852ed57324eb05a9bde1e8a7a31/includes/Modules/AdSense.php#L497-L499

**Comment by felixarntz** [comment]
@aaemnnosttv Thanks for pointing out! While unrelated, makes sense to remove as part of this. I added a note to the IB.

**Comment by aaemnnosttv** [comment]
@felixarntz One optional suggestion for you but otherwise 👍

**Comment by aaemnnosttv** [comment]
CR ✅

**Comment by felixarntz** [comment]
There is an issue here with the new logic of the `modules/(?P<slug>[a-z\-]+)/notifications` route: If a module does not provide a `notifications` datapoint, requests result in a 500 which they shouldn't.

Will open a PR to fix it.

**Comment by aaemnnosttv** [comment]
CR ✅

**Comment by felixarntz** [comment]
QA ✅
