### ISSUE TITLE
Analytics code not inserted on a site when the plugin determines a GTM inserted UA tag - despite the toggle to place the Tag Manager code removed. 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4082]
## Bug Description

If a user chooses to connect Tag Manager but **not allow Site Kit to insert the Tag Manager code** the plugin still recognizes a Tag inserted Universal Analytics tag when checking or editing the Analytics module within Site Kit. This results in no Analytics UA tracking, with the inability to allow Site Kit to insert any snippet - despite no other snippets present. 

_Image below showing a users Tag Manager setup_

![image](https://user-images.githubusercontent.com/41326532/134049460-46ae3715-470e-4ec5-b9ac-ab4ec36aafd4.png)

Image below depicting that Site Kit will not place a UA snippet as one exists within a connected Tag Manager account

![image](https://user-images.githubusercontent.com/41326532/134049872-e7c2b4ca-8600-4638-ba8f-2dc6d83a5f3b.png)

To solve this one of the following may be suitable:
- Remove the option for users to "Let Site Kit place code on your site" within Tag Manager, which has the same purpose as disconnecting the module
- Ensure that the Analytics module checks the status of that toggle with a users Tag Manager setup within the plugin

## Steps to reproduce

1. Connect Analytics
2. Connect GTM (with a container that has a UA tag)
3. Revisit the Analytics edit page within SK - the plugin has switched to the GTM snippet (the UA toggle option is disabled)
4. Revisit the GTM edit page within SK and don't allow SK to insert the GTM snippet
5. Revisit the Analytics edit screen - a user must refresh the page, at which point the toggle can be inserted to allow SK to insert the UA snippet although the messaging still states "_Site Kit will therefore not place an Analytics tag because Tag Manager already covers it."_

 - SK 1.41.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This seems related to #2583 but more on the Analytics side. I think we should opt to be informative more than anything as the logic between the two modules is already quite complex. In this scenario, I think a notice on the Analytics settings view+edit would suffice.

**Comment by aaemnnosttv** [comment]
After further review, it seems that we probably shouldn't allow for the GTM snippet to be disabled via its settings as this essentially soft-disables its entire functionality and further complicates the integration with Analytics. I thought we had an old issue for this which we decided against at the time, but was unable to find it.

@felixarntz if we were to remove this setting, it could make for an odd upgrade path where we would need to choose between two options:

- Deactivating the module (or just clearing its settings, leaving it active but unconnected) if `useSnippet` was disabled (preserving the current behavior)
- Disregarding a saved `useSnippet` value and forcing `true` requiring the user to deactivate the module to turn it off or use the tag blocking filter to disable its output

Neither of these are particularly great experience for the user without some additional notice/messaging. The former sounds like the safer option as the latter would result in JS loading unexpectedly just from upgrading Site Kit (which could also be automatic/unattended). Either way, I think we'd need some messaging in place to inform the user about this change and maybe even provide  information about what the previously configured settings were?

As it is, I think we could address the underlying issue reported here by updating the necessary logic to also check if the GTM `useSnippet` is enabled when checking from GA which shouldn't be too much effort 🤞 .

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv How about for now we keep the setting technically, but remove the UI for it? Like:
* If `useSnippet` is enabled "on pageload", don't show the control to disable it at all.
* If `useSnippet` is disabled "on pageload", show the control as is. If the user then enables it and saves, keep showing it, but don't show it again when they come back later or refresh the URL.

The latter may still be a bit weird, but I think it's less disruptive than both of the approaches you mention above. Since we're not technically removing the setting just yet, I think it would make sense to do this in combination with also checking for `useSnippet` as you are suggesting.

I think we should do both as part of this issue, and then at some point in the future we can consider removing the setting entirely.

**Comment by aaemnnosttv** [comment]
@felixarntz see my comment above. Should we make this issue dependent on the existing tag simplification epic?

**Comment by felixarntz** [comment]
@aaemnnosttv Makes sense. Once we have the epic, we can mark this blocked by it (or rather by a particular issue in that epic).

**Comment by jamesozzie** [comment]
Confirming that the GA4 snippet is placed on a site that has a GTM snippet active (when the associated web container does include a UA and GA4 snippet). This occurs whether the GTM snippet is placed or not via the "Tag Manager Code Snippet" option within Site Kit. 

Closing this issue.
