### ISSUE TITLE
Ensure Search Console widgets only show "Gathering data" box when API is actually gathering data

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4085]
Currently, Site Kit widgets are configured to show the "Search Console gathering data" box whenever the API returns a response with all 0s. This is somewhat confusing and an incorrect approach, since it could also mean that the site actually has 0 data, even though data is already being aggregated properly.

This should be adjusted, and the "Search Console gathering data" box should only be shown for 0 data if the API is actually _likely_ gathering data - _likely_ since this needs to be based on heuristics as there is no API flag that clearly states whether or not data is now ready to be served.

Related: #4086, #4087

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Search Console JS store should offer a new parameter-less selector `isGatheringData()` which issues a SC report request to the API only to see if it already has gathered any data, returning a boolean or `undefined` (on load).
    * The request must be for the `date` dimension.
    * The request should preferably match another already existing request that is fired in the Site Kit dashboard, just to not result in yet another request. Of course it is impossible to reliably prevent that, but let's make sure it uses the same report arguments like another request that is typically fired. For example, we may need to also take the current date range into account in this request.
    * The selector should return `true` if the report does not contain any rows / is empty. As soon as there is at least one row returned, the selector should return `false`.
* All Search Console widgets should, in case that it would currently display the "zero data" UI, also check if Search Console `isGatheringData` - only if that's the case, the widget should display the "zero data" UI. Otherwise it should display the regular widget content, actually "showing the 0s".

## Implementation Brief

* Add a new selector `isGatheringData()` to the `search-console` module:
  * Get the current `compareStartDate` and `endDate` values using the `getDateRangeDates` selector with `{ compare: true, offsetDays: DATE_RANGE_OFFSET }` arguments.
  * Get the current entity URL using the `getCurrentEntityURL` selector.
  * Get the result of the `getReport` selector call with the following arguments:
    * `dimensions` should be `date`;
    * `startDate` should have the `compareStartDate` variable value;
    * `endDate` should have the `envDate` variable value;
    * `url` should be set to the current entity URL if it is not empty.
  * Return `undefined` if the result is `undefined`
  * Return `true` if the result is an empty array.
  * Otherwise return `false`.
* Update `DashboardClicksWidget`, `DashboardImpressionsWidget`, and `DashboardPopularKeywordsWidget` widgets to return the `WidgetReportZero` element if the Search Console is still gathering data (checking the `isGatheringData` selector) **and** the current report is empty (using the `isZeroReport` function). If the result of the `isGatheringData` selector equals `undefined` then consider this as the report is still being loaded and display the loading state.

### Test Coverage

* Add tests for the new `isGatheringData` selector.

## QA Brief

* Create a new jurrasic ninja site.
* Install the plugin and connect it.
* Verify that the search console widgets show zero states.
* Wait a few days and check the dashboard again.
* Confirm that now dashboard widgets don't display zero states, but charts with zeros.

## Changelog entry

* Improve Search Console "gathering data" heuristics; prevents users with limited/no traffic from seeing "Gathering data" message.

**Comment by eugene-manuilov** [comment]
@felixarntz I have added IB which describes an alternative approach how to detect whether the Search Console is gathering data or not. The idea is to rely on the returned result of the search analytics query request. If it has no rows in it, then it's definitely a case when SC is gathering data. Or if the query returns rows with zero values, then SC has gathered the initial data and we can start showing stats and charts. Does it sound good to you? If so, we will need to update AC.

**Comment by felixarntz** [comment]
@eugene-manuilov Have you verified that is the case? So do we currently just auto-populate missing rows with 0s? If that is how it works, we can go with that approach, but I want to make sure we've confirmed it with testing for a new property.

**Comment by eugene-manuilov** [comment]
@felixarntz Yes, I tested it on a brand new Jurrasic ninja site. Both requests return an empty array:

```
https://agreed-markhor.jurassic.ninja/wp-json/google-site-kit/v1/modules/search-console/data/searchanalytics?startDate=2021-08-27&endDate=2021-09-23&dimensions=query&limit=10&_locale=user

[]
```
```
https://agreed-markhor.jurassic.ninja/wp-json/google-site-kit/v1/modules/search-console/data/searchanalytics?dimensions=date&startDate=2021-07-30&endDate=2021-09-23&_locale=user

[]
```

Here is another Jurassic ninja site that I have created this morning. It has started returning results for yesterday even though it has been created today:

```
https://sudden-spinner.jurassic.ninja/wp-json/google-site-kit/v1/modules/search-console/data/searchanalytics?dimensions=date&startDate=2021-07-30&endDate=2021-09-23&_locale=user

[{"clicks":0,"ctr":0,"impressions":0,"keys":["2021-09-23"],"position":0}]
````
```
https://sudden-spinner.jurassic.ninja/wp-json/google-site-kit/v1/modules/search-console/data/searchanalytics?startDate=2021-08-27&endDate=2021-09-23&dimensions=query&limit=10&_locale=user

[]
```

**Comment by felixarntz** [comment]
@eugene-manuilov Hmm yeah so that seeond item specifically makes me question whether the assumption that it always returns empty rows when it doesn't have data is true. I mean, why would the new property already return results for yesterday, when the site didn't even exist yesterday?

**Comment by eugene-manuilov** [comment]
@felixarntz I don't know, but that's probably not our "problem" because if Search Console "thinks" that it has something for a site and returns something in response, then all we need to do is just display what we get. We just need to interpret the results correctly: no rows returned - SC is gathering data, at least one row returned - SC has data for the site that we need to display.

**Comment by felixarntz** [comment]
@eugene-manuilov From a technical perspective yes, but from a user experience perspective I'd consider this questionable :)

The ACs here would provide a more appropriate user experience I think. It's definitely not great that we don't know when the Search Console property was created, that's a concern here. But we can know when the site is new or empty, and it would be more accurate here to inform the user about it instead of displaying 0 (especially if that's for a day where the site didn't even exist).

**Comment by felixarntz** [comment]
@eugene-manuilov ACs are updated based on what we discussed earlier.

**Comment by felixarntz** [comment]
@eugene-manuilov IB almost looks good, just one thing:

> In other words, use results of the `isGatheringData` selector instead of `isZeroReport`

Per what we've discussed yesterday, which I've also captured in the ACs, let's use both, not the new one instead of the old one. We should only show the is gathering data bit if `isZeroReport && isGatheringData`. While this is likely going to be the same, the report itself should still take precedence. If it is _not_ empty (which is likely not possible, but we don't know that for sure), it should display.

**Comment by eugene-manuilov** [comment]
> Per what we've discussed yesterday, which I've also captured in the ACs, let's use both, not the new one instead of the old one. We should only show the is gathering data bit if `isZeroReport && isGatheringData`. While this is likely going to be the same, the report itself should still take precedence. If it is _not_ empty (which is likely not possible, but we don't know that for sure), it should display.

@felixarntz if we use both, then we will keep showing "gathering data" boxes instead of charts with zeros when there are rows in the report with zero values. That's why we need to replace `isZeroReport` with the result of the `isGatheringData` selector.

**Comment by felixarntz** [comment]
@eugene-manuilov
> if we use both, then we will keep showing "gathering data" boxes instead of charts with zeros when there are rows in the report with zero values. That's why we need to replace `isZeroReport` with the result of the `isGatheringData` selector.

I don't think that's correct. `isZeroReport` won't change its functionality, so it will return `true` if there are either 0s or no values at all in the _widget's_ report. `isGatheringData` uses its own report per the ACs/IB, so that remains the most significant indicator. The purpose of still having `isZeroReport` is that if a value in there is actually >0, we should display it, in that case the `isGatheringData` result is irrelevant.

**Comment by eugene-manuilov** [comment]
@felixarntz ah... I see what you mean... sorry didn't get it at the beginning. Makes sense to me. IB is updated.

**Comment by felixarntz** [comment]
@eugene-manuilov Thanks, no worries. That looks great, IB ✅

**Comment by wpdarren** [comment]
QA Update:  ⚠️ 

This ticket is on hold because I need to login to the site in a few days to see if the zero states are charts with zeros.

This is what I currently see.

**Dashboard**

![image](https://user-images.githubusercontent.com/73545194/136814955-d19586d6-ca5c-42e5-8a1d-e8c7e1398634.png)

**Search console module page**

![image](https://user-images.githubusercontent.com/73545194/136814988-892e28c6-de9c-45aa-b4d8-a760f04035d4.png)
