### ISSUE TITLE
Ensure Analytics widgets only show "Gathering data" box when API is actually gathering data

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4086]
Currently, Site Kit widgets are configured to show the "Analytics gathering data" box whenever the API returns a response with all 0s. This is somewhat confusing and an incorrect approach, since it could also mean that the site actually has 0 data, even though data is already being aggregated properly.

This should be adjusted, and the "Analytics gathering data" box should only be shown for 0 data if the API is actually _likely_ gathering data - _likely_ since this needs to be based on heuristics as there is no API flag that clearly states whether or not data is now ready to be served.

Related: #4085, #4087

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics JS store should offer a new parameter-less selector `isGatheringData()` which issues a GA report request to the API only to see if it already has gathered any data, returning a boolean or `undefined` (on load).
    * The request must be for the `ga:date` dimension.
    * The request should preferably match another already existing request that is fired in the Site Kit dashboard, just to not result in yet another request. Of course it is impossible to reliably prevent that, but let's make sure it uses the same report arguments like another request that is typically fired. For example, we may need to also take the current date range into account in this request.
    * The selector should return `true` if the report does not contain any `data[0].data.rows` / is empty. As soon as there is at least one row returned, the selector should return `false`.
        * While Site Kit's Analytics requests always have the `include_empty_rows` argument enabled, it looks like that doesn't apply when there are no rows at all. When testing with the current Site Kit codebase for a new site, `data[0].data.rows` was `undefined`, so it looks like this works even with that argument enabled.
* All Analytics-based widgets (including the applicable AdSense-focused widgets) should, in case that it would currently display the "zero data" UI, also check if Analytics `isGatheringData` - only if that's the case, the widget should display the "zero data" UI. Otherwise it should display the regular widget content, actually "showing the 0s".

## Implementation Brief

* Add a new selector `isGatheringData()` to the `analytics` module:
  * Get the current `startDate` and `endDate` values using the `getDateRangeDates` selector.
  * Get the current entity URL using the `getCurrentEntityURL` selector.
  * Get the result of the `getReport` selector call with the following arguments:
    * `dimensions` should be `[ 'ga:date' ]`
    * `metrics` should be `[ { expression: 'ga:users' } ]`
    * `startDate` should have the `startDate` variable value
    * `endDate` should have the `envDate` variable value
  * Return `undefined` if the result is `undefined`
  * Return `true` if the result is an empty array.
  * Otherwise return `false`.
* Update the following widgets to return the `WidgetReportZero` element only if the Analytics is still gathering data (checking the `isGatheringData` selector) **and** the current report is empty (using the `isZeroReport` function). If the result of the `isGatheringData` selector equals `undefined` then consider this as the report is still being loaded and display the loading state.
  * `DashboardSearchVisitorsWidget`
  * `DashboardPopularPagesWidget`
  * `DashboardGoalsWidget`
  * `DashboardBounceRateWidget`
  * `DashboardAllTrafficWidget`
  * `DashboardTopEarningPagesWidget` in the AdSense module

### Test Coverage

* Add tests for the new `isGatheringData` selector.

## QA Brief

* Spin up a new jurrasic.ninja site.
* Connect Analytics Module and ensure that the Zero Data Widgets are being shown on Analytics Widgets. 
* Wait a few days. Alternatively, if you already have a public test site with Analytics where you know it doesn't get _any_ visitors, you can use that site as well.
* Analytics widgets should no longer show zero data widgets, instead, normal chart widgets shouyld be shown with zeros.  

## Changelog entry

* Update Analytics widgets to display zero state only when the Analytics account is gathering data.

**Comment by eugene-manuilov** [comment]
@felixarntz this one is also ready for IB review. It also uses a similar approach as one defined in #4085. Let me know if it looks good to you.

**Comment by felixarntz** [comment]
@eugene-manuilov I'm not sure the approach from #4085 is as applicable here. First of all, if we go with that approach we would also need to change the general way GA requests work (we currently force them to include empty rows, which would make the suggested approach here infeasible). Second, for GA we have the information when the property was created which is missing in SC, so your suggested approach certainly has more benefit for SC.

Also, empty rows could happen even when tracking breaks for example. Again, we should verify that a the rows are actually missing when the property is new and under what other circumstances that could be the case.

Maybe we need to discuss this further in our eng meeting.

**Comment by felixarntz** [comment]
@eugene-manuilov ACs are updated based on what we discussed earlier.

**Comment by felixarntz** [comment]
@eugene-manuilov Similar to https://github.com/google/site-kit-wp/issues/4085#issuecomment-930305921, just one thing:

> use the result of the `isGatheringData` selector call instead of `isZeroReport` function

The result should be used in addition to the `isZeroReport` result, only if both are `true` the "gathering data" state should be displayed.

**Comment by eugene-manuilov** [comment]
> The result should be used in addition to the `isZeroReport` result, only if both are `true` the "gathering data" state should be displayed.

@felixarntz if we use `isZeroReport` and  `isGatheringData` together, then we will keep showing the "gathering data" state instead of charts with zeros.

**Comment by felixarntz** [comment]
@eugene-manuilov IB ✅

**Comment by eugene-manuilov** [comment]
@kuasha420 could you please add QAB?

**Comment by felixarntz** [comment]
@wpdarren @kuasha420 @eugene-manuilov Flagging #4211, which potentially is more of a QA ⚠️ for this one rather than its own issue. Not opposed to work through it in its own issue, but if we verify it comes from this issue here, we can also create a follow-up PR to this one instead. Either way, this needs to be resolved for the same release (1.44.0).

**Comment by eugene-manuilov** [comment]
@felixarntz, I have added module page widgets to my PR and fixed a few more storybook issues. Could you please take another look?

**Comment by felixarntz** [comment]
@wpdarren Thanks for catching these additional problems!

@eugene-manuilov Would it be straightforward to change the line chart configurations (throughout all widgets) to always have 0 as minimum? I think that one would be good to include in the same release - we could add it as one extra AC in #4226.

@wpdarren Regarding your other two points (no line in Unique visitors widget, and lack of units when value is 0), could you open a separate follow-up issue for those? I believe those are not _as_ critical that we need them resolved right away (also as we're limited in time until the release), but it would be good to fix them for the release after.

**Comment by eugene-manuilov** [comment]
> Would it be straightforward to change the line chart configurations (throughout all widgets) to always have 0 as minimum? I think that one would be good to include in the same release - we could add it as one extra AC in #4226.

@felixarntz, yes, it is straightforward as far as I remember. I'll add it when I work on 4226.
