### ISSUE TITLE
Introduce REST route that returns all modules

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#409]
A new REST route `modules` should be introduced to list all available modules with their details. This endpoint should return an array of `$moduleDetails` objects. `$moduleDetails` would be the exact same data that the existing `modules/(?P<slug>[a-z\-]+)` route returns for an individual module.

The modules should be returned in their correct order as defined by the `order` value.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a REST route called `modules`, that returns an array of objects, with every object representing one of the available modules.
* Every object should exactly match the object returned by the respective module from the existing `modules/(?P<slug>[a-z\-]+)` route.
* Module objects should be sorted by their `order`.

## Implementation Brief

* Add new `modules` route to `REST_Routes` class, above the existing `modules/(?P<slug>[a-z\-]+)` route.
* It should only support one request method of `WP_REST_Server::READABLE`.
* The callback should call `$this->modules->get_available_modules()`, which returns the modules already sorted. It should then use `array_map( array( $this, 'prepare_module_data_for_response' ), $modules )`, and finally `array_values()` to ensure the result is an actual array in JavaScript. That should then be returned in a `WP_REST_Response`.

## Changelog entry

* Introduce `modules` REST route with read-only information about all available modules.

**Comment by aaemnnosttv** [comment]
Brief looks good to me!

**Comment by aaemnnosttv** [comment]
CR 👍

**Comment by aaemnnosttv** [comment]
QA PASS

* ✅ There should be a REST route called `modules`, that returns an array of objects, with every object representing one of the available modules.
* ✅ Every object should exactly match the object returned by the respective module from the existing `modules/(?P<slug>[a-z\-]+)` route.
* ✅ Module objects should be sorted by their `order`.

![image](https://user-images.githubusercontent.com/1621608/63841626-d2748700-c98b-11e9-8224-7ac0550e5f41.png)

Order:
```
Array
(
    [site-verification] => 0
    [search-console] => 1
    [adsense] => 2
    [analytics] => 3
    [pagespeed-insights] => 4
    [optimize] => 5
    [tagmanager] => 6
)
```
