### ISSUE TITLE
Update Idea Hub widget styles for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4092]
## Feature Description

The Idea Hub dashboard widget is stylistically inconsistent with other widgets, particularly in regards to the padding between its border and the inner content in some places.

Widgets should have 24px between the border and content on desktop as shown in the All Traffic widget

![image](https://user-images.githubusercontent.com/1621608/134140946-57d0b11a-2a69-4bc3-baaa-3c700a7340e4.png)

The Idea Hub widget has less on the header 16px gap + 8px margin on title makes for a total of 24px gap between edge and widget title, but the tab bar only has the same 16px gap.

![image](https://user-images.githubusercontent.com/1621608/134141355-fd5f7f53-1db8-4370-a04d-f3ae2cc1b0c7.png)

The idea rows only have 12px of horizontal padding (grid gap desktop of 24px / 2) which is the most obvious 

![image](https://user-images.githubusercontent.com/1621608/134142179-03561838-f79f-4ff0-9a7c-c6bf23fc3305.png)

On mobile, widgets should have 16px between the border and content

Here the Idea Hub widget has the same padding as on desktop (with the added margin on the title) although here it's worth noting that the padding on top is too much (24px instead of 16)
![image](https://user-images.githubusercontent.com/1621608/134142825-6e12be72-9347-471e-bc38-e894da317dfc.png)

Also, the same 12px horizontal padding is present in this viewport as well
![image](https://user-images.githubusercontent.com/1621608/134143160-5713c1f6-087f-45b3-8beb-4c9105f55d03.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub widget should consistently use padding for its inner content, similar to the other widgets in the dashboard (e.g. 24px on desktop).
* It also needs to be ensured that the different sections of the widget have equal spacing (e.g. currently the main section below the tabs has less padding than the tabs themselves).

## Implementation Brief

In `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`:

* Remove the `noPadding` prop on the `Widget` component.

In `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`:

* Remove padding from `googlesitekit-idea-hub__header` class. (Feel free to remove the class itself if there's nothing else, which is the case at the time of writing.)
* Change the left margin of `googlesitekit-idea-hub__title` to 0.
* Add negative horizontal margin according to screen size on the `googlesitekit-idea-hub__body` class so that it **takes back** the padding. 
    * ie. it must be the same as the horizontal padding of the widget. See below:
    * https://github.com/google/site-kit-wp/blob/a1d3e7b997f90f9e885b91f5b1e8219baf6d84f3/assets/sass/widgets/_googlesitekit-widget-adsense-performance.scss#L25-L29
* Change padding of the `googlesitekit-idea-hub__idea--single` class so that the horizontal padding is same as the padding of the widget. (This should also be responsive, see above.)
* VRT related to Idea Hub needs updating.

### Test Coverage

* N/A

## QA Brief

* The margin and padding of idea hub widget should be consistent with other widgets.
* Should have proper styling for mobile views. 
* Edge-to-edge appearance of idea hub items on hover should be intact. 

## Changelog entry

* Improve Idea Hub widget styles and padding.

**Comment by aaemnnosttv** [comment]
@eclarke1 @fhollis this is one that I raised with @felixarntz yesterday and is not launch blocking.

**Comment by aaemnnosttv** [comment]
> * add responsive padding to `googlesitekit-idea-hub` class [...]
> * Remove horizontal padding from the `googlesitekit-idea-hub__idea--single` class.

@kuasha420 this would break the edge-to-edge appearance of the idea rows which we should preserve. We can update the ACs to clarify this if needed, but the idea is to preserve the design of the widget and adjust the padding so that the inner content aligns as if it was bound by the normal padding.

What we could do (which might be the simplest) would be to remove the `noPadding` prop on the inner Idea Hub `Widget` component, and then apply a negative margin to the `.googlesitekit-idea-hub__body` class to fill the gap on the sides to allow the rows to be full width. Then we'd just need to tweak a few other styles and we'd be good to go. I think the end result should look like this 
![image](https://user-images.githubusercontent.com/1621608/135235501-f09401c4-683f-4ba2-973d-2ccc440b0fb5.png)

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by kuasha420** [comment]
// just assigning this one to myself as I'd like to work on it when it's get into a sprint.
