### ISSUE TITLE
G logo misaligned in user feedback UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4101]
## Bug Description

[The 'G' logo in the remote survey UI is misaligned](https://app.asana.com/0/1200379030254833/1200441040172151)
![image](https://user-images.githubusercontent.com/56588136/125924659-794eb6e3-cb51-411a-8fd1-edbf4b495c9c.png)

[Figma design for reference](https://www.figma.com/file/CdBzWXXAlDFxJbgD6WGdz4/UserFeedback_PopupUI?node-id=1051%3A0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The G icon next to the survey headings should be vertically centered alongside the heading, similar to how it is in the [Figma file](https://www.figma.com/file/CdBzWXXAlDFxJbgD6WGdz4/UserFeedback_PopupUI?node-id=4831%3A700).
    * In other words, the G icon and the heading need to be within a common container so that their positioning can both be vertically centered within that container.

## Implementation Brief

* Add `align-items: center` to the `googlesitekit-survey__header` class:
https://github.com/google/site-kit-wp/blob/2729377ea873747cf68261aa47ed999628ce07ab/assets/sass/components/surveys/_googlesitekit-survey-header.scss#L44

### Test Coverage

* Add a VRT scenario for the `CurrentSurvey` widget:
  * Add a `scenario` to [assets/js/components/surveys/CurrentSurvey.stories.js](https://github.com/google/site-kit-wp/blob/2729377ea873747cf68261aa47ed999628ce07ab/assets/js/components/surveys/CurrentSurvey.stories.js).
  * Update the VRT reference images by running `npm run test:visualapprove`.

## QA Brief

* View `CurrentSurvey` in Storybook and verify the G icon alignment - https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys-currentsurvey--survey-single-question-story

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The G icon next to the survey headings is vertically centered alongside the heading and matches the Figma file.

![image](https://user-images.githubusercontent.com/73545194/144052312-40343ae1-530c-472b-9808-28caf46d6226.png)
