### ISSUE TITLE
Use wp.i18n instead of googlesitekit.i18n when in Gutenberg context

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4109]
As a follow-up to #4107 at (which explicitly excludes covering the internationalization part), this issue is focused on replacing `googlesitekit.i18n` usage with `wp.i18n` usage for any Site Kit JS asset that is Gutenberg-specific. This requires us to modify our localization setup, so that in those cases we use the latter global to provide JS translations.

As a result of this issue, no Site Kit JS file other than the main entry point file for the respective functionality should be loaded in Gutenberg context. This currently applies to the `googlesitekit-idea-hub-notice` script and will in the near future apply to the SwG integration script.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt @eugene-manuilov Looking at this again, I wonder whether there's really a good case to do this. We want to use WP core dependencies for Gutenberg integrations primarily to avoid conflicts between React, but as far as I can tell the translation part shouldn't be subject to that. Of course there is also a "JS size to load/parse etc" consideration to this, but the translations should be fine to still come from Site Kit I think?

Let me know your thoughts on this, I wonder whether we should just discard this one and keep using `googlesitekit.i18n` even when in Gutenberg context.

**Comment by aaemnnosttv** [comment]
@felixarntz I agree, I don't think there is a real need for this right now that would justify the added complexity. We can always revisit it later if needed.

**Comment by felixarntz** [comment]
Closing as _maybelater_
