### ISSUE TITLE
Idea Hub post list CTA notices are no longer dismissible

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4110]
## Bug Description

The Idea Hub CTAs shown on post list pages for new and saved ideas are no longer dismissible.

## Steps to reproduce

1. Activate Idea Hub on a site that has ideas available
2. Go to post list view
3. See notice for new or saved ideas
4. Click to dismiss the notice
5. Refresh the page
6. See the notice again

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/134490241-d4ac5589-dd7f-43c7-b7cc-683529234bd3.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Idea Hub notices on the post list view should not appear after refreshing the page after dismissing

## Implementation Brief

* Restore the dismiss event listener to use a delegated listener on the notice rather than attaching an event listener directly to the dismiss element as this is added dynamically by WP core JS  
Essentially undoing the relevant portion in https://github.com/google/site-kit-wp/commit/56eef43177b3fb27d63b8c2230c5486b5281fed3#diff-ca0032794ce8ba3e86a186debb2900d206e8b98ecbcf2c6ea3f4bb7bda5fb162R56-R57

### Test Coverage

* Ideally a quick E2E test could be added for this, but we can add this in a separate issue if not enough time

## QA Brief

1. Activate Idea Hub on a site that has ideas available
2. Go to WordPress post list view (`wp-admin/edit.php`)
3. See notice for new or saved ideas
4. Click the "X" to dismiss the notice
5. Refresh the page
6. The notice should not appear

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

On `main` branch:

- Can confirm that on the post list view page, the notice appears. 
- When I click the "X" to dismiss the notice and refresh the page, the notice does not appear.
