### ISSUE TITLE
Experimental label too close to Idea Hub name in some places

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4111]
## Bug Description

The distance between the Idea Hub module title and the experimental badge is inconsistent, and in some places there is none at all.

## Screenshots

**Settings > Connected Services**
![image](https://user-images.githubusercontent.com/1621608/134498772-4f892b52-4c48-4462-8459-c5a7740e20a2.png)

**Settings > Connect More Services**
![image](https://user-images.githubusercontent.com/1621608/134492184-19b271ea-0e6f-493e-beb8-282390e057c4.png)

**Module setup**
![image](https://user-images.githubusercontent.com/1621608/134492405-e0a593ba-f460-4dfd-9d1e-ebc5ccd91516.png)

**Widget (for reference: 12px)**
![image](https://user-images.githubusercontent.com/1621608/134492503-745c6615-fe9a-467f-9acc-153599cffc15.png)

Also note that the font weight of the badge differs in some places (e.g. settings and module setup) where it inherits a heavier weight rather than remaining consistent.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be 12px between the Idea Hub module title and experimental badge in all instances
    * Note: the `Badge` component is only used for this so that makes it easy to find all instances, but the styles should not be added to the badge component/class without additional context (i.e. not to `.googlesitekit-badge` alone)

## Implementation Brief

* Update `Badge` component to accept additional class names via prop
* Add a new class for the Idea Hub badge, giving it 12px left margin
* Apply the new class on all Idea Hub badge components
* Remove now unnecessary `padding-right` on widget title
* Merge #4115 

### Test Coverage

* No change

## QA Brief

* Check the Idea Hub badges in the following places to make sure they all have consistent spacing with the experimental label
    * Settings > Connect More Services
    * Settings > Connected Services (once activated)
    * Module set up
    * Widget title

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Checked that the Idea Hub badges in the places below, all have consistent spacing with the experimental label:

Settings > Connect More Services  - [Screenshot](https://user-images.githubusercontent.com/73545194/134640567-d2d1c700-2c2e-4224-a41c-3f894af16eaa.png)
Settings > Connected Services (once activated) - [Screenshot](https://user-images.githubusercontent.com/73545194/134640556-429cfb0a-f1c0-4013-9094-81a37c492045.png)
Module set up  - [Screenshot](https://user-images.githubusercontent.com/73545194/134640501-e8a03827-9896-4614-bbb4-aa4d12b6bd27.png)
Widget title  - [Screenshot](https://user-images.githubusercontent.com/73545194/134640528-2833e089-e0b5-4c01-a8de-500eb79d1de2.png)
