### ISSUE TITLE
Add E2E tests for Idea Hub

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4113]
## Feature Description

All modules in Site Kit have E2E coverage of their set up flows and basic functionality, except for Idea Hub. This is especially important for areas where we integrate with WordPress outside of React which is seeing more instances now.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The basic setup flow for Idea Hub should be covered by E2E tests, similar to all other modules
    * This should cover normal setup through the settings screen as well as the banner notification and dashboard widget CTAs
    * Tests should primarily cover the user journeys; not component-specific data from the (fake) Idea Hub API as this is already covered in other tests

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by asvinb** [comment]
@eclarke1 @FlicHollis @aaemnnosttv I think we can close this ticket since it's no longer relevant.
