### ISSUE TITLE
Add GA tracking event for number of Idea Hub ideas shown

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4114]
Site Kit should send GA tracking data for the number of ideas rendered in the Idea Hub widget.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `widget_view` event for the `dashboard_idea-hub-widget` event category should be enhanced so that it includes the count of "rendered" new ideas as the event label.
    * This should be the count of _all_ ideas that are available in the "New" tab, i.e. not only the 5 count for the ideas that are visible right away.

## Implementation Brief

**NB: Since this issue is for the 1.42.0 release, the PR should be based on and target `main` branch.**
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`,
	* Add a new state variable `initialTotalNewIdeas` with default value set to `null`.
	* Before the `useEffect` calls, check if `initialTotalNewIdeas` is `null` and the number of new ideas is set. If this is the case, then set `initialTotalNewIdeas` to the length of the new ideas array.
	* Update the `useEffect` hook where `inView` is used to add `initialTotalNewIdeas` to the dependency array, and within the hook, check if `initialTotalNewIdeas` is not `null` when testing for `inView`. Add `initialTotalNewIdeas` as label (third parameter) to the `trackEvent` call.

### Test Coverage
* No new tests to be added.

## QA Brief
* Install the Google Analytics Debugger extension for your Google Chrome if you haven't done it yet.
* Verify that the number of new ideas are sent once for the `widget_view` event when the Idea Hub module is scrolled to.
* Create a draft post/pin/dismiss ideas from the new ideas tab and verify that no requests are sent for the `widget_view` event 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Since this issue is for the 1.42.0 release, the PR should be based on and target `main`.

**Comment by aaemnnosttv** [comment]
> * pass `newIdeas` as third parameter (label) to the `trackEvent` function call.
> * Update the dependency of the aforementioned useEffect hook and include `newIdeas`.

@kuasha420 we want to pass the number of ideas as the label, not the list of ideas itself. Also, we want to avoid this event being sent multiple times when the number of new ideas changes due to an idea being saved or draft created for. As currently defined, I think such interactions would result in this event being sent each time (due to a new array being returned when the state changes), whereas we're only interested in the total number when initially viewed, but after the selector has resolved of course 😄 .

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified that the number of new ideas are sent once for the `widget_view` event when the Idea Hub module is scrolled to.

![image](https://user-images.githubusercontent.com/73545194/134841411-93b421bd-b0ec-4e09-af48-25606090f78c.png)

Verified that no requests are sent for the `widget_view` event when you pinned, dismissed or started a draft from new ideas tab.
