### ISSUE TITLE
Replace existing useSelect calls throughout the app with useInViewSelect

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4121]
## Feature Description

Once #4096 is implemented, we should replace virtually, if not all, of our `useSelect` hooks with `useInViewSelect`.

Originally I thought it might be better to change the `googlesitekit-data` API to have `useSelect` alias our own `useInViewSelect` hook, but I think that's a bit too clever/confusing and less explicit. It also might lead to an odd import dance, so let's replace every `useSelect` hook with `useInViewSelect`.

I can't think of any calls which _don't_ warrant running the selectors on page load **except PageSpeed Insights**. These take so long to run that it could be valuable to always run those select calls immediately so they're loaded in time for the user to scroll down to them 🙂 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update all usage of `useSelect` from `'googlesitekit-data'` to import/use `useInViewSelect` instead.
* The only components that should not use this new hook are:
  * PageSpeed Insights widgets (these requests are slow to load so better to run right away)
  * `useSelect` calls in any "setup" page, where it makes sense to load the data immediately even if a piece of data is slightly out-of-view
* All VRTs, Jest tests, etc. should continue to run as normal and not need updating—this should probably be done by ensuring `useInView` always `returns true;` in Jest tests, VRTs, etc. for now. This applies to E2E tests as well, which might be a bit more complicated.

I think it's fine to use `useInViewSelect` on the Settings screen though, as many of these calls only run once a settings tab is open anyway, which means it will be on-screen.

The IB for this issue should largely focus on the groups of components that _don't_ need updating. It's possible this IB will need to include changes to tests as well to satisfy the last point of the ACs.

## Implementation Brief
* Update usage of `useSelect` to `useInViewSelect` from `googlesitekit-data` except for the following components:
	* PageSpeed Insights widgets:
		* `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js`
		* `assets/js/modules/pagespeed-insights/components/common/Recommendation.js`
		* `assets/js/modules/pagespeed-insights/components/common/Recommendations.js`
		* `assets/js/modules/pagespeed-insights/components/common/ReportDetailsLink.js`
	* Setup components:
		* `assets/js/modules/**/setup/*.js`
* Any failing tests should be updated as a result of the above changes.

### Test Coverage

* Update existing storybook, E2E, and Jest tests to function with the new useInViewSelect calls.

## QA Brief

Similar to the WordPress Dashboard issue: this feature causes widgets (_except PageSpeed Insights_) to only load once they've been scrolled into view. So, to QA this, effectively:

* Test with Unified Dashboard feature flag enabled and disabled.
* Visit all dashboard pages and ensure they load without errors.
* Note that content in view on page load (at the top of the page) will start to load and then load.
* Observe that when you scroll down to content that wasn't in view, it will still be loading, even after having sat on the page for awhile. The exception here is PageSpeed Insights, which will load even when not in view.

## Changelog entry

* Update widgets to use the `useInViewSelect` hook to fetch reports.

**Comment by asvinb** [comment]
@tofumatt I've added the IB but since #4096 is still in the works, it's difficult to me right now to evaluate the changes that should be made to the tests. I've added a large estimate though, mainly to cater for test changes. Let me know what you think.

**Comment by tofumatt** [comment]
@asvinb That makes sense, and the IB looks good. I don't think work on this should start until #4096 is merged, so I'll double-check the IB then, but for now this all seems fine.

IB ✅

**Comment by tofumatt** [comment]
Update on this issue: it turns out the `useSelect`s that can be straightforwardly updated to `useInViewSelect` is a lot more narrow than originally intended. Any loading or error selector is much more sensitive to the `undefined` returned by `useInViewSelect`.

I'm working through these but it's a bit less straightforward than we hoped. There was also a problem with our `useInView` approach—it caused way too many updates when used across the app, so we needed to adjust it to store the 'in-view" state per widget area instead of per-hook instance to prevent a "maximum depth exceeded" re-render React error.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Tested with Unified Dashboard feature flag enabled and disabled.
- Visited all dashboard pages they load without errors in the console or FE.
- When you scroll down to content that wasn't in view, it still loads, even after having sat on the page for awhile. 
- Tested with desktop and mobile screen sizes to ensure behaviour is consistent.
