### ISSUE TITLE
New Widget: Search Funnel Widget

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4123]
## Feature Description

<img width="875" alt="Screenshot 2021-09-24 at 22 04 48" src="https://user-images.githubusercontent.com/90871/134739662-db1a5b3b-f82c-46c6-8318-1f783e335b74.png">

This widget should be based on the **Analytics Overview Widget** widget design, but use the metrics in the old Search Funnel widgets:

  * Impressions (Search Console)
  * Clicks (Search Console)
  * Search Visitors (Analytics)
  * Goals (Analytics)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Create a new Search Funnel widget in `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget`.
* Based on the Analytics Overview Widget widget design, but using the metrics in the existing Search Funnel widgets:
  * Impressions (Search Console)
  * Clicks (Search Console)
  * Search Visitors (Analytics)
  * Goals (Analytics)
* If Analytics isn’t connected, show an Analytics CTA in place of the Analytics tabs
* Since data now conditionally comes from either Search Console or Analytics, the source link should reflect that: show the source based on which metric is currently selected
* Note that the old Search Funnel view was actually four separate widgets (https://github.com/google/site-kit-wp/blob/d77d4fc8d20ff6d5fa5e266c9be495c3bc3d8ae3/assets/js/modules/search-console/index.js#L60-L79 and https://github.com/google/site-kit-wp/blob/d77d4fc8d20ff6d5fa5e266c9be495c3bc3d8ae3/assets/js/modules/analytics/index.js#L84-L104). As now the content will live entirely in the overview widget, these don’t need to be four separate widgets but instead can be combined into one widget.
* The content should be site-wide for the Main Dashboard, and entity-specific for the Entity Dashboard.
  * The Main Dashboard should show "Goals" as the 4th metric, while the Entity Dashboard should show "Bounce Rate" as the 4th metric.
* This new widget should be registered when the `unifiedDashboard` feature flag is enabled, specifically added to the `mainDashboardTraffic` and `entityDashboardTraffic` widget areas as full-width widgets. It should appear after the already-registered (in #4149) `DashboardAllTrafficWidget` on each dashboard.

## Implementation Brief

Create a new file: `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget.js`

Look / feel is based on `ModuleOverviewWidget` `assets/js/modules/analytics/components/module/ModuleOverviewWidget/index.js`

Content for the widget is combined from the following four widgets (copied over rather than imported):
`assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js`
`assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js`

`assets/js/modules/analytics/components/dashboard/DashboardSearchVisitorsWidget.js`
`assets/js/modules/analytics/components/dashboard/DashboardGoalsWidget.js` - this fourth metric should be `Goals` when loaded via `mainDashboardTraffic` widget area (see below) and `Bounce Rate` otherwise.

When the `analytics` module isn't connected, for the content that would have come from there, we show `<WidgetActivateModuleCTA moduleSlug="analytics" />`

Full stats link `See full stats in Analytics / Search Console` should correspond to the service from where we obtain data.

The following widget registrations need to be conditional when `unifiedDashboard` feature flag is *disabled*:
https://github.com/google/site-kit-wp/blob/d77d4fc8d20ff6d5fa5e266c9be495c3bc3d8ae3/assets/js/modules/search-console/index.js#L60-L79
https://github.com/google/site-kit-wp/blob/d77d4fc8d20ff6d5fa5e266c9be495c3bc3d8ae3/assets/js/modules/analytics/index.js#L84-L104

In `js/modules/search-console/index.js` register our new widget `searchFunnel` when `unifiedDashboard` feature flag is *enabled*, as `widgets.WIDGET_WIDTHS.FULL` width, after the `analyticsAllTraffic` widget (see #4149) in `AREA_MAIN_DASHBOARD_TRAFFIC_PRIMARY` and `AREA_ENTITY_DASHBOARD_TRAFFIC_PRIMARY` widget areas.

### Test Coverage

Add stories in `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget.stories.js` 

## QA Brief
* Enable the `unifiedDashboard` feature flag via the tester plugin.
* Go to the main dashboard and the new SearchFunnel widget should be displayed as per the AC.
* Go to a page dashboard, for e.g http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-dashboard&permaLink=https%3A%2F%2Fwww.elasticpress.io%2Ffeatures%2F and check if the SearchFunnel widget displays as per the AC.

## Changelog entry

* Add the new Search Funnel Widget to the Unified Dashboard.

**Comment by felixarntz** [comment]
@tofumatt Related to my comment in #4122, things got a little bit mixed up here. _This_ is the new Search Funnel widget, and the ACs are mostly correct. However, in the issue title and in the first point of the ACs you are referring to the "audience overview" widget, which this is not.

It should only visually look like today's Analytics audience overview widget, but it semantically has nothing to do with it.

> Create a new Search Funnel widget in `assets/js/widgets/AudienceOverview`

Let's implement this in `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget` instead. While this is technically getting data partly from Search Console and partly from Analytics, it's mostly related to Search Console. In addition, we don't really have any widgets implemented in a general widgets folder (other than the URL search, which shouldn't be a widget in the first place, as we are now finally changing as part of this epic), and I don't think it makes sense to move this into a generic place. It relies on two modules, but it still relies on modules in general, so it's not really a "core" widget. It's also not the first time we're doing this, there are already AdSense widgets that also rely on Analytics data.

> The content should be site-wide for the Main Dashboard, and entity-specific for the Entity Dashboard.

This is generally accurate, but there is another nuance (which already exists in today's search funnel widget, but we should probably re-emphasize it here): There's one metric that differs entirely between the main dashboard and entity dashboard, the main dashboard should show "goals" as the 4th metric, while the entity dashboard should show "bounce rate" as the 4th metric.

Can you update the issue title and the above points in the ACs?

**Comment by tofumatt** [comment]
Makes sense, I think part of the confusion is sometimes referencing the Figma designs which are different from the Design Doc and PRD, and it ends up becoming quite confusing. I think it's happened in the past too 😓

I've updated the ACs to reflect everything mentioned in your comment, so moving this over to IB.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvinb @tofumatt I have `unifiedDashboard` activated and on the `develop` branch. When I set up Site Kit all is good until I am redirected to the dashboard and this permissions box appears. I know we had this issue previously.  At this stage I have not set up Analytics but wasn't expecting this to appear. Thoughts? 

![image](https://user-images.githubusercontent.com/73545194/139687550-91485937-1a8c-4855-95b6-a9e66a37d696.png)

**Comment by felixarntz** [comment]
@wpdarren The issue should be resolved now (in latest `main` branch).

**Comment by wpdarren** [comment]
### QA Update: 

- Can confirm that the search funnel widget includes Impressions (Search Console), Clicks (Search Console), Search Visitors (Analytics), Goals (Analytics)

- Since data now conditionally comes from either Search Console or Analytics, the source link reflects that. When you click on the Total Impressions and Total clicks tabs, the source is Search Console.  When you click Unique Visitors from Search or Goals then the source is Analytics.  Checked that the links redirected to the correct reports. 
- 

- If Analytics isn’t connected, an Analytics CTA appears in place of the Analytics tabs.

![image](https://user-images.githubusercontent.com/73545194/140065754-baf7be8a-e18b-4fab-a4c6-4b94c352544b.png)

**Comment by tofumatt** [comment]
@wpdarren Good catch, sorry I missed that. I've submitted a follow-up PR to correct the positioning of the widget.

**Comment by aaemnnosttv** [comment]
Ready for another pass @wpdarren 👍
