### ISSUE TITLE
Modify Widget: Most Popular Content Widget

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4124]
## Feature Description

<img width="914" alt="Screenshot 2021-09-24 at 22 03 54" src="https://user-images.githubusercontent.com/90871/134739474-c9dd7da7-6a4b-4adf-9a01-ad6466996a04.png">

The Most Popular Content Widget (`ModulePopularPagesWidget`) should be modified for use in the Unified Dashboard. The resulting widget should essentially be the `ModulePopularPagesWidget`, but modified by adding an additional column/metric: “Session Duration” when the `unifiedDashboard` feature flag is enabled.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ModulePopularPagesWidget` should output an extra column, "Session Duration", when the Unified Dashboard feature flag is enabled.
    * This data should be retrieved using the [`avgSessionDuration` metric](https://ga-dev-tools.web.app/dimensions-metrics-explorer/session#avgSessionDuration). You can see this metric being retrieved elsewhere in the plugin here: https://github.com/google/site-kit-wp/blob/7ee265439d32c19415370d75eeca72f6505e252d/assets/js/modules/analytics/components/module/ModuleOverviewWidget/index.js#L65
* The header and subheader should be modified when the `universalDashboard` feature flag is enabled.

## Implementation Brief

In `assets/js/modules/analytics/components/module/ModulePopularPagesWidget/index.js`:

* check if the `unifiedDashboard` feature flag is enabled using the `useFeature` hook.
* add `ga:avgSessionDuration` expression for `Session Duration` to the `metrics` array of `args` object [here](https://github.com/google/site-kit-wp/blob/7ee265439d32c19415370d75eeca72f6505e252d/assets/js/modules/analytics/components/module/ModulePopularPagesWidget/index.js#L64).
* conditionally add the `Session Duration` column with appropriate title, description and field (formatting) to `tableColumns` array when the `unifiedDashboard` flag is set.
* Change the header/subheader to "Most popular content"/"Pages from your site that got the most views" when the feature flag is enabled

### Test Coverage

* Not Needed

## QA Brief

* Make sure that `Session Duration` column is added in the Most Popular widget when unified dashboard is enabled. The widget should not have any changes in Normal Dashboard. 

## Changelog entry

* Add "Session Duration" to Unified Dashboard Most Popular Content Widget

**Comment by felixarntz** [comment]
@tofumatt This is probably ready to get ACs. Most importantly we need to specify where to get the session duration from, which we can find out based on our existing "Analytics audience overview" widget which currently shows that metric.

**Comment by tofumatt** [comment]
@felixarntz I'm assuming we don't want to include queries using the GA4 API right now, correct? I'm unclear if this API will work with GA4 properties, but I don't see other components including GA4 report queries so I didn't include it.

If I should add what seems to be the relevant GA4 API property to the ACs, let me know (I think, based on the [Google Analytics 4 API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema), it's the `userEngagementDuration` metric. But if that isn't needed this can be moved to IB.)

**Comment by felixarntz** [comment]
@tofumatt Correct, this should remain only using UA as is, we aren't in a position to support GA4 for reporting yet. I'll remove the "For UA properties" reference from the ACs, it may imply that there is some nuance to consider here in regards to GA4, where I'd say this is just how it has been everywhere else, since we don't have any GA4-based widgets in general yet.

**Comment by aaemnnosttv** [comment]
LGTM, but let's give it a little more time for CR + QA. I'll bump it to a 7 👍 

IB ✅
