### ISSUE TITLE
Enhance assets manifest for use in development

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4126]
## Feature Description

As of https://github.com/google/site-kit-wp/issues/2806, JS and CSS assets will be built with a content hash in the filename, but only for production builds. This was originally done for development builds as well, but resulted in the [Webpack dist directory growing in size on every change](https://github.com/google/site-kit-wp/issues/2344).

For development builds where frequent changes are very common, the hash is still valuable for ensuring the correct version of the file is loaded by the browser. Without this, we're forced to disable the network cache altogether, or use a [3rd party solution](https://wordpress.org/plugins/version-assets/) which shouldn't be necessary.

We should update the behavior of the manifest for development builds to provide the content hash as the `ver` provided to WordPress instead.

---------------	

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The structure of the generated assets manifest should be updated to be as follows:  
	`asset-handle: [ filename, version ]`
* For production builds, the `version` should always be `null`
* For development builds, the `version` should be the content hash used in the filename of the asset for production builds. (note this varies based on entry type)
* Assets should then be registered using the filename _and version_ from the manifest  
This will result in production assets loaded as `asset-url-contenthash.ext` and development assets as `asset-url.ext?ver=contenthash`

## Implementation Brief

* In `webpack.config.js`:
  * Import the `crypto` module and create a Hash object using the `crypto.createHash( 'sha256' )` call:
    ```js
    const crypto = require('crypto');
    const hashSum = crypto.createHash('sha256');
    ```
  * Update how values in the manifest array are generated in the `serialize` function of the `manifestArgs` config:
    * For each file generate its content hash if the current mode is production. You can use something like this to generate a content hash:
      ```js
      const fs = require('fs');
      const fileBuffer = fs.readFileSync('path/to/asset/file.js');

      hashSum.update(fileBuffer);
      const hex = hashSum.digest('hex');
      ```
    * Then update values of generated manifest records to be an array instead of just file name string (`"${ manifest[ key ] }"`). The first item in this array should be the same file name, whilst the second argument should be the file content hash or `null` if the current mode is production.
    * Eventually, when the manifest is generated, we should get something like this if the current mode is not production:
      ```php
       return array(
           'file1' => array( 'file1.js', 'abcdef012345' ),
           'file2' => array( 'file2.js', '54321fedcba' ),
           ...
       );
      ```
      And something like this if the mode is production:
      ```php
       return array(
           'file1' => array( 'file1.js', null ),
           'file2' => array( 'file2.js', null ),
           ...
       );
      ```
* In `includes/Core/Assets/Manifest.php`:
  * Extract the following lines of code into a new static method `get_assets()` that returns assets defined in the manifest: https://github.com/google/site-kit-wp/blob/a608bcba230cf33c225b33730b15204aecfad5f6/includes/Core/Assets/Manifest.php#L40-L45
  * Update the `get_filename` method to use the new `get_assets()` method. `get_filename()` should return the first element of the asset data: `self::$assets[ $handle ][ 0 ]` instead of just `self::$assets[ $handle ]`.
  * Add a new static method `get_version( $handle )` that is similar to the `get_filename` method but returns the second element of the asset data: `self::$assets[ $handle ][ 1 ]`.
* In `includes/Core/Assets/Script.php`:
  * Update the `register` method to get the script version using the `Manifest::get_vesion( $this->handle )` call here: https://github.com/google/site-kit-wp/blob/a608bcba230cf33c225b33730b15204aecfad5f6/includes/Core/Assets/Script.php#L75
* In `includes/Core/Assets/Stylesheet.php`:
  * Update the `register` method to get the style version using the `Manifest::get_vesion( $this->handle )` call here: https://github.com/google/site-kit-wp/blob/a608bcba230cf33c225b33730b15204aecfad5f6/includes/Core/Assets/Stylesheet.php#L71

### Test Coverage

* N/A

## QA Brief

This PR changes the way assets are loaded for the development build of SK only (although it's possible something could have changed in the production build, that would be unintentional so it should also be checked).

- A development build can be installed using the Tester plugin by selecting the "Development build" checkbox before activating your selection. (Development builds are available for all options **except** "Latest release")
- Using a development build, observe how Site Kit CSS/JS files are loaded. They should have a URL like `googlesitekit-foo.js?ver=a0b1c2d3e4f5`
    - In a production build, the same file would have a URL like `googlesitekit-foo-a0b1c2d3e4f5.js` (note the hash is expected to be different between them, `a0b1c2d3e4f5` is just a dummy placeholder here)
- One exception is `googlesitekit-i18n.js` which does not get built the same way as other JS files so this can be ignored

**`QA:Eng`**

- Ensure the browser/devtools is **not** configured to ignore/disable cache  
![image](https://user-images.githubusercontent.com/1621608/145782749-0d821e50-c4be-4ec8-a4eb-67e31f938ec0.png)
    - Also ensure [Version Assets](https://wordpress.org/plugins/version-assets/) is not enabled if you have it installed
- Run `npm run watch`
- Load the Site Kit dashboard
- Observe the hash in the `googlesitekit-dashboard.js` URL
- Make a change in `assets/js/googlesitekit-dashboard.js` (e.g. add a `console.log`)
- Reload the page
- Observe the hash in the `googlesitekit-dashboard.js` URL has changed and the added change is present without clearing the cache

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
QA Update: ✅ 

**Verified:**

- Using a development build, the Site Kit CSS/JS files are loaded with URL like googlesitekit-foo.js?ver=a0b1c2d3e4f5

![image](https://user-images.githubusercontent.com/73545194/145933531-7b640647-b265-458d-b857-5b51a9fba763.png)

I've added the `QA:Eng` labeel for additional testing in QAB.

**Comment by kuasha420** [comment]
QA: :heavy_check_mark: 

Verified that hash changes and updated file is loaded correctly using `npm run watch` when caching is not disabled. 

![Screenshot_20211215_094515](https://user-images.githubusercontent.com/6187401/146120995-2320680b-e3a2-4569-a7d4-092241169e2c.png)
![Screenshot_20211215_094635](https://user-images.githubusercontent.com/6187401/146121002-df746b0c-e322-46a4-92b0-4564fe8fc84a.png)
