### ISSUE TITLE
Implement new plugin setup success notification for unified dashboard

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4135]
Based on the new component from #4153, a new component for the plugin setup success notification should be implemented with its [new design](https://www.figma.com/file/li0bi4Sma7VwApckCAghIa/Notifications-MVP?node-id=620%3A0).

In addition, if the user dismisses that notification with a prompt to remind them again later, a [similar-looking notification with slightly different wording](https://www.figma.com/file/li0bi4Sma7VwApckCAghIa/Notifications-MVP?node-id=620%3A0) should be shown after a week.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@tofumatt I wonder whether this is the most appropriate starting point for our notifications UI rework here. We have a couple notifications in Site Kit, all of which will probably need to be slightly modified for the `unifiedDashboard`.

We may need a bit of engineering discussion around this, but it should be as basic as possible. I suggest, as a starting point, we migrate all our notifications to the new _location_ in the UI where they need to be shown, i.e. putting together the infrastructure layer around them, before changing the visual UI of those existing notifications.

We could create a single `Notifications` component that is rendered in the additional header bar container (see #4050), and that component should contain the basic logic for which notification should be returned, if any - essentially what is currently still solved purely via legacy code using filters (yikes) in https://github.com/google/site-kit-wp/blob/1.42.0/assets/js/components/legacy-notifications/index.js.

I can focus on this part of the issues going forward, so we split the load a bit.
