### ISSUE TITLE
Hide any section of the dashboard that has zero widgets

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4136]
## Feature Description

Because the [Monetization section can be dismissed/hidden](https://docs.google.com/document/d/1StGx76XXisE9MfwM1916D9fn7-H9BRiRgizRejTsecI/edit?pli=1#heading=h.r70gae7m55b9), we should create a system that allows Widget Contexts to be links to the "Pill links" in the header, and automatically hides both the Widget Context and the Pill Link when all Widget Areas in that context are empty.

This will require adding the idea of an "Empty Widget Area" to a Widget Context, and implementing a similar system to the Widget Context that we have for Widget Areas now—an awareness of them being empty and rendering something different.

In this case we likely will want to dispatch an action that flags a context as being empty.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

-   It should be possible to select from the `core/widgets` datastore whether a widget is active:
    -   A selector `isWidgetActive( widgetSlug )` should be added to `widgets.js`. It should rely on the same filtering logic that is currently applied in `WidgetAreaRenderer`, but (as the name says) _only_ for the specific widget - it should return `true` or `false`. In other words, it can rely on the `getWidgetState` selector instead of using `getWidgetStates` and then iterating through all widgets.
    -   Remember: A widget is active unless there is a specific widget state set for it that defines it as "inactive" (see current `isInactiveWidgetState` utility function).
-   It should be possible to select from the `core/widgets` datastore whether a widget area has active widgets (i.e. is active):
    -   A selector `isWidgetAreaActive( slug )` should be added to `areas.js`. It should get all widgets in the area (via `getWidgets`) and filter them by the above `isWidgetActive`. It should return `true` if that list is not empty, or `false` if it is.
-   It should be possible to select from the `core/widgets` datastore whether a widget context has active widget areas (i.e. is active):
    -   A selector `isWidgetContextActive( slug )` should be added to a new `contexts.js`. It should get all widget areas in the context (via `getWidgetAreas`) and filter them by the above `isWidgetAreaActive`. It should return `true` if that list is not empty, or `false` if it is.
-   The `WidgetAreaRenderer` component should be adjusted to no longer calculate `activeWidgets` itself. Instead, it should rely on the new `isWidgetAreaActive` selector - if it returns `false`, it should render the "hidden" version of itself that is currently rendered if `! activeWidgets.length`.
-   The `WidgetContextRenderer` component should be adjusted somewhat similarly to the `WidgetAreaRenderer`: If the above `isWidgetContextActive` selector returns `false` for it, it should render a "hidden" version of itself. That "hidden" version should consist of the following:
    -   The outer `.googlesitekit-widget-context` wrapper, with an additional `googlesitekit-hidden` class applied.
    -   The output for all `WidgetAreaRenderer`s within.
    -   In other words, it should **not** include the `Header` and `Footer` at all.
-  The `DashboardDetailsApp` should be adjusted so that the `DashboardDetailsHeader` is still rendered even with the above changes in place.
    -  For example, it could be rendered unconditionally (i.e. not in a custom `pageDashboardNotFound` widget context), with the same DOM structure wrapped around it that it has today.

## Implementation Brief

- Add a selector `isWidgetActive( slug )` to `assets/js/googlesitekit/widgets/datastore/widgets.js`
    - It should effectively return the result of `isInactiveWidgetState( select( CORE_WIDGETS ).getWidgetState( slug ) )`
- Add a selector `isWidgetAreaActive( slug )` to `assets/js/googlesitekit/widgets/datastore/areas.js` that selects all widgets in that area () and returns `true` if at least one is active; `false` if none are active, eg: `widgetAreaWidgets.some( ( widget ) => isWidgetActive( widget.slug ) )`
- Add a selector `isWidgetContextActive( slug )`  to `assets/js/googlesitekit/widgets/datastore/contexts.js`. It should, similar to the above selector, select all widget areas and filter them based on those that are active, returning `true` if one or more are active, `false` if none are active, eg: `widgetAreas.some( ( area ) => isWidgetAreatActive( area.slug ) )`
- Remove https://github.com/google/site-kit-wp/blob/6d0d17d08134d469df20d41562cf5f2ba578b259/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L61-L67 and rely on `isWidgetAreaActive( slug )` in the component instead to determine if the area is active or not
- In `WidgetContextRenderer`, get the result of `select( CORE_WIDGET ).isWidgetContextActive( slug )`. If it's `true`, return the usual/existing output; if `false`, don't output the `Header` or `Footer` props, and ensure the `.googlesitekit-hidden` class is applied to the main `.googlesitekit-widget-context` `<div>`

With this data stored and these selectors in-place, we can then query `select( CORE_WIDGETS ).isWidgetContextActive( CONTEXT_MAIN_DASHBOARD_MONETIZATION )` inside the component made in #4053 to conditionally render the "Monetization" pill link. In fact, we can do this for each pill link, so that any empty section causes a link not to be rendered... even though this scenario is only likely to come up for the Monetization section for now.

#### Existing `DashboardDetailsApp` refactoring

We'll need to make a few changes to the existing `DashboardDetailsApp` to bring it in-line with this new approach:

- In `DashboardDetailsApp`, if `currentEntityURL` is truthy, render the `WidgetContextRenderer` with the `'pageDashboard'` slug.
    - If it is false-y, render the `DashboardDetailsHeader` as is rendered here: https://github.com/google/site-kit-wp/blob/ab909c7b9f60dbf9a972688ede31cd238542cdb5/assets/js/googlesitekit/widgets/components/WidgetContextRenderer.js#L52-L60. There is already logic inside `DashboardDetailsHeader` to render this error message when `currentEntityURL` is false-y, so rendering that header should be fine for this issue.
    - Don't render the `<WidgetContextRenderer>` at all when `currentEntityURL` is false-y.

### Test Coverage

- Tests to ensure "empty" widget contexts render appropriately would be great; look to the existing empty widget area logic in case there are tests for that behaviour there.

## QA Brief

- With the Unified Dashboard feature **disabled**, perform a regression test:
  - Navigate to the Dashboard and the individual Module screens and check all widgets are still present.
  - Navigate to an invalid Entity Dashboard, e.g. with the path `/wp-admin/admin.php?page=googlesitekit-dashboard&permaLink=not-a-valid-entity`.
  - Verify the error page still displays correctly:
![image](https://user-images.githubusercontent.com/18395600/141981584-81fcc778-dcca-4dbb-9f7b-1e7c88a1921d.png)

- With the Unified Dashboard feature **enabled**, you can verify the `googlesitekit-hidden` class is being applied to the empty `monetization` context:
  - Navigate to the Dashboard and open the devtools on the Elements tab.
  - In the Elements tab, find the element for the `monetization` context - you can search for it by pressing Command+F (Mac) or Control+F (Windows/Linux) and then entering the ID selector `#monetization`.
  - The `#monetization` element should have the class `googlesitekit-hidden` applied:
![image](https://user-images.githubusercontent.com/18395600/141980128-c9b7d729-3acf-421b-8458-38edf69d48d4.png)

## Changelog entry

* Update dashboard layout to hide sections that have no widgets.

**Comment by aaemnnosttv** [comment]
> * Keep track of all empty widget areas in the datastore by adding a new state key in the Widget Area datastore (`assets/js/googlesitekit/widgets/datastore/areas.js`), something like `emptyAreas: []`.

@tofumatt is there a substantial benefit to storing empty areas rather than deriving it from existing selectors? It seems simple enough to derive every time although I'm not strictly opposed to memoizing the operation.

> * Anytime a widget area changes to have zero active widgets (eg `! activeWidgets.length` in the `WidgetAreaRenderer` component), add that WidgetArea's `slug` to the `emptyAreas` array in the datastore. If an area updates to **not** being empty, dispatch an action to remove it from the `emptyArea` array.

This part is incompatible with the changes required of the `WidgetAreaRenderer` which is missing:

> * The `WidgetAreaRenderer` component should be adjusted to no longer calculate `activeWidgets` itself. Instead, it should rely on the new `isWidgetAreaActive` selector - if it returns `false`, it should render the "hidden" version of itself that is currently rendered if `! activeWidgets.length`.

Similarly, the changes called for to the `WidgetContextRenderer` is also not covered by the current IB.

**Comment by felixarntz** [comment]
@tofumatt Maybe you missed these parts in the ACs, but I second some of Evan's points above - the AC here already specifies the required selectors/signatures, let's write the IB based on this.

It is one of those more closely eng-related ACs, but for things like this it can make sense since this is technically a third-party API where function/selector signatures can be essential and relevant to be encompassed in the ACs (e.g. to be compliant with other existing functions/selectors).

**Comment by tofumatt** [comment]
Sounds good. I think I was re-thinking the approach based on the intended outcome. But I think maybe I had a different approach in mind and glossed over the existing `isInactiveWidgetState` utility function. Also I did totally miss the context rendering bit, sorry about that!

I've re-thought the IB and it's ready for another look now 👍🏻

**Comment by aaemnnosttv** [comment]
> The `WidgetContextRenderer` component should be adjusted somewhat similarly to the `WidgetAreaRenderer`:
> * In other words, it should **not** include the `Header` and `Footer` at all.

@felixarntz I just realized that this would require additional changes to the dashboard entity app. Currently the context `Header` is what shows the entity not found message:

> _It looks like the URL http://.... is not part of this site, therefore there is no data available to display._

> With this data stored and these selectors in-place, we can then query `select( CORE_WIDGETS ).isWidgetContextEmpty( CONTEXT_MAIN_DASHBOARD_MONETIZATION )` 

@tofumatt this part still references the selector from the previous IB; I'll rename it 👍 

The IB looks great otherwise, just pending any potential change from @felixarntz on the above.

**Comment by felixarntz** [comment]
@aaemnnosttv Good catch! I've added a note on this to the ACs.

@tofumatt Since the widget context is only ever empty for the extra `pageDashboardNotFound` widget context, which is used when there's no `currentEntityURL`, I suggest in this case we change `DashboardDetailsApp` to remove that "custom" context and instead render the same markup manually. This is not particularly elegant, but it allows us to keep the same output with little new changes, and with the unified dashboard this won't be relevant anymore anyway.

One more thing (nit-pick):
> - Add a selector `isWidgetContextActive( slug )`  to `assets/js/googlesitekit/widgets/datastore/contexts.js`. It should, similar to the above selector, select all widget areas and filter them based on those that are active, returning `true` if one or more are active, `false` if none are active, eg: `widgetAreaWidgets.some( ( widget ) => isWidgetActive( widget.slug ) )`

The code sample is off here (the explanation before is correct though), it should probably be `widgetAreas.some( ( area ) => isWidgetAreaActive( area.slug ) )`.

 Can you update the IB to cover those?

**Comment by tofumatt** [comment]
> @tofumatt Since the widget context is only ever empty for the extra `pageDashboardNotFound` widget context, which is used when there's no `currentEntityURL`, I suggest in this case we change `DashboardDetailsApp` to remove that "custom" context and instead render the same markup manually. This is not particularly elegant, but it allows us to keep the same output with little new changes, and with the unified dashboard this won't be relevant anymore anyway.

I like that idea, sounds good. 👍🏻 

I think it's a bit more elegant to manually render the content than have a whole context dedicated to "error" widgets 😅 

Thanks for catching the code-sample for widget areas; I've updated that as well. Should be ready for another look now 👍🏻

**Comment by felixarntz** [comment]
IB ✅

**Comment by techanvil** [comment]
@tofumatt (as you wrote the IB), I've noticed that when it comes to updating `DashboardDetailsApp`, following the IB to the letter the page loses some styling, which is due to the top-level classes rendered by `WidgetContextRenderer` no longer being present.

Compare the current styling (the classes in question are highlighted):

![image](https://user-images.githubusercontent.com/18395600/141783627-b28fbd13-6f1f-4cfd-93fd-55bcd3246b4b.png)


With the updated version - you'll notice those classes are missing and the padding is a bit out of whack:

![image](https://user-images.githubusercontent.com/18395600/141784039-0d33477e-ac4c-4107-937a-6c19cc9939ed.png)

The simple solution is to provide these classes** as well, e.g.:

```ts
				<div className="googlesitekit-widget-context googlesitekit-module-page googlesitekit-dashboard-single-url">
					<Grid>
						<Row>
							<Cell size={ 12 }>
								<DashboardDetailsHeader />
							</Cell>
						</Row>
					</Grid>
				</div>
```

do you think this is an acceptable solution or do we need to rethink the styling a bit? Cheers

** One additional detail to note is the `googlesitekit-widget-context` and `googlesitekit-module-page` classes appear to be identical so we could conceivably use only one of them, although it may be better to use both in case something changes in one of them in the future...

**Comment by techanvil** [comment]
@tofumatt also, I am going to hazard a guess that this sentence under Test Coverage refer to a previous incarnation of the IB, would that be right? (I can see from https://github.com/google/site-kit-wp/issues/4136#issuecomment-963030859 that there was some talk of actions in an earlier iteration)...

> Depending on complexity a test to ensure actions for empty/non-empty widget areas would be great, but only if they can be done in Jest and not E2E tests.

**Comment by felixarntz** [comment]
@techanvil 

> The simple solution is to provide these classes** as well, e.g.:
> 
> ```ts
>				<div className="googlesitekit-widget-context googlesitekit-module-page googlesitekit-dashboard-> single-url">
> 					<Grid>
> 						<Row>
> 							<Cell size={ 12 }>
> 								<DashboardDetailsHeader />
> 							</Cell>
> 						</Row>
> 					</Grid>
> 				</div>
> ```

Good catch, I think that same `div` with the classes should still be present if we want to reuse the styling. An alternative approach would be to change the styles to apply to a class that's not tied to the `WidgetContextRenderer`, which feels a bit cleaner, but at the same time may not be worth the extra effort.

**Comment by techanvil** [comment]
@felixarntz thanks, I think it's probably best to reuse these classes, rather than changing the styles, which as you've suggested doesn't seem worth the effort considering this will no longer be relevant when the unified dashboard is completed.

**Comment by tofumatt** [comment]
@techanvil Argh, indeed, yes—that was from a previous IB and doesn't apply anymore 🙂 . I've removed that section from the IB just so it's extra-clear. 👍🏻 

Some tests would be good so I mentioned it there, if possible to do with Jest and not E2E 👍🏻

**Comment by techanvil** [comment]
@tofumatt cool, thanks for clarifying :). I've already added tests for the new selectors, will look at adding some for the empty context too. :+1:
