### ISSUE TITLE
Remove unused widgets after Unified Dashboard is completed

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4137]
## Feature Description

Once the Unified Dashboard is fully implemented (#3945), we should remove these widgets from the codebase as they're be unused:

* Average CTR and Average Position from Search Console hierarchical chart widget (Clicks and Impressions still present in updated Search Funnel widget)
* Sessions from Analytics hierarchical chart widget (Users still present in All Traffic widget, Session Duration and Bounce Rate still present in new content widget above)
* AdSense dashboard summary widget (all metrics still present in AdSense hierarchical chart widget)

Stories and tests related to these widgets should also be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@tofumatt I'm not sure this requires an issue, not anytime soon anyway. We'll need to keep the old widgets around for when the feature flag is not in use. Removing them will only happen once we eventually remove the `unifiedDashboard` feature flag from the codebase, a couple weeks/months after launch.

**Comment by aaemnnosttv** [comment]
Closing as no longer relevant.
