### ISSUE TITLE
Google Analytics not connecting

### ISSUE THREAD

**Issue by outlett** [google/site-kit-wp#414]
## Bug Description

Google analytics does not connect

## Steps to reproduce

Attempt to connect an analytics account that has been shared with other gmail/g suite users.

## Additional Context

I use site kit on multiple wordpress installations. It connects analytics accounts that don't have any secondary users. It is unable to connect analytics accounts that have user/s invited to manage.

I've read the other related issues on this and don't believe the 'workarounds' should be something users have to deal with, pretty much every other plugin out there related to google analytics works 'out the box' and connects fine. So why doesn't an official plugin from Google?

If I have to disable all my other plugins/clear caches/change hosting settings just to get this to work, then I guess it's better of for me to uninstall this and perhaps come back to it when this bug has been fixed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@outlett Certainly we would love Site Kit to work out of the box for all, so issues like this help us identify bugs and incompatibilities. That being said with all the possible dependency versions used by plugins trying to accomodate for as many users as possible is an ongoing task. We are still at a developer beta stage of development. 

In relation to your issue with adding the Analytics module for accounts with multiple users invited I am unable to replicate this issue. Can you let me know the following:
- Any console errors that appear, along with screenshots of any error message or notice.
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by jamesozzie** [comment]
@outlett Did you manage to set Analytics after performing the suggested steps?
