### ISSUE TITLE
Include entity context in header bar when scrolling beyond header in Entity Dashboard

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4147]
## Feature Description

The Site Kit Unified Dashboard header should load entity context and show it once the header has scrolled far enough to hide the info shown in #4050/#4146.

This condensed version of the entity context, shown once the user has scrolled down the page, should look like this:

<img width="854" alt="Screenshot 2021-09-28 at 16 04 47" src="https://user-images.githubusercontent.com/90871/135113919-0b88ef90-ccd3-44a2-b235-9c8479f6752d.png">

It should always be visible in the header as long as the main header content (again, from #4050) is not being shown.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Per discussion with @samitron7, we're going to put this issue on hold for now. Potentially we will make some slight tweaks to how the search bar and entity dashboard header should behave to use a better UX pattern than what is currently envisioned.

**Comment by FlicHollis** [comment]
Thanks for the update @felixarntz does this mean this is not expected to be completed in Sprint 63 / prior to launch?

**Comment by felixarntz** [comment]
@FlicHollis Probably not for Sprint 63, but definitely the search approach needs to be completed in one way or another prior to launch. This is now pending a decision with one of the following outcomes:
* Either we go with the new UX approach, which will mean this issue gets closed, but 2-3 new ones get opened.
* Or we go with the old approach including this, which will mean this issue remains relevant.
* Or we go with the old approach without this, which will mean this issue gets closed.

Either case will have to be resolved before launch, so this probably means we can only "complete" the launch issues for unified dashboard in Sprint 64.

**Comment by FlicHollis** [comment]
Thanks @felixarntz after discussing this with @eclarke1 and @wpdarren we believe we can continue to e-2-e testing and the bug bash with this as a known issue if all other tickets for Unified Dashboard are completed.

**Comment by felixarntz** [comment]
Per the recent related UX changes, this issue is no longer relevant, so it can be closed. I will open and define the replacement issues for the updated search and entity header UX requirements early next week.
