### ISSUE TITLE
Revise wording during Analytics setup - when a non Site Kit placed snippet is evident

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4151]
## Bug Description

When connecting the Analytics module to a site that already have a manually inserted Analytics snippet, the plugin will automatically populate the Analytics dropdown fields. The messaging within the Analytics setup appears as below:

_**An existing Universal Analytics tag was found on your site with the ID UA-*----*. Since this tag refers to the same property you have selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this tag, Site Kit can place a new tag for you.**_

The "_**Since this tag refers to the same property you have selected here**_" can lead to confusion - as a user didn't select anything, the plugin has simply prepopulated the dropdowns based on the existing property. It's not possible for users to select or change the dropdown values.

Consider changing the wording to the below:

_**An existing Universal Analytics tag was found on your site with the ID UA-*----*. As Analytics is already connected we're automatically selected the fields below and Site Kit will not place its own tag. If later on you decide to remove this tag, Site Kit can place a new tag for you.**_

## Steps to reproduce

1. Disconnect any Analytics module on a site that already has Site Kit setup
2. Add Google Analytics to a site manually, inserting the tracking code into your themes header.php file
3. Connect the Google Analytics module within Site Kit

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/135139486-7f486904-2a44-4c63-b279-da402fcae1cc.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics setup/settings copy for when there is an existing tag should be slightly modified (with all its permutations in the `ExistingTagNotice` component) to replace "property/properties you have selected here" with "property/properties selected here".

## Implementation Brief
* Using `assets/js/modules/analytics/components/common/ExistingTagNotice.js`, update the copy as per the AC.

### Test Coverage
* No new tests to be added.

## QA Brief

There are five permutations of the copy text that should be checked for a thorough QA test:

* UA tracking code manually added to site, but no GA4 code.
* GA4 tracking code manually added to site, but no UA code.
* Both UA and GA4 tracking codes manually added to site:
  * Both with properties that match the ones selected on the setup form.
  * Only the UA property matches the one selected on the setup form.
  * Only the GA4 property matches the one selected on the setup form.

For each case, follow the **Steps to reproduce** above, adding either one or both tracking codes to `header.php`.

For the cases where both UA and GA4 are added, it's possible to see the three copy permutations by selecting **Set up a new property** from the **Property** dropdowns.

By way of illustration here are screengrabs of the five permutations.

UA tracking code manually added to site, but no GA4 code:
![image](https://user-images.githubusercontent.com/18395600/142190517-2bdf6d81-9b47-4965-9098-1d89b0a2e76b.png)

GA4 tracking code manually added to site, but no UA code:
![image](https://user-images.githubusercontent.com/18395600/142190613-6ed045d2-5c98-45b5-81e0-e390a207726d.png)

Both UA and GA4 tracking codes manually added to site - both with properties that match the ones selected on the setup form:
![image](https://user-images.githubusercontent.com/18395600/142190733-bd7c3af5-635c-42c8-96e7-477f614107b2.png)

Only the UA property matches the one selected on the setup form:
![image](https://user-images.githubusercontent.com/18395600/142190817-bcd01705-98e8-4442-97a2-ee01cc457281.png)

Only the GA4 property matches the one selected on the setup form:
![image](https://user-images.githubusercontent.com/18395600/142190886-1369ddfa-e5dd-4b73-aa75-fc3bcabed5eb.png)

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@marrrmarrr @jamesozzie I suggested a simplified copy change in the ACs. The originally suggested text is a bit inaccurate because while there is an Analytics tag, we shouldn't say that it is already connected yet (which is only the case after setup). I think just removing the "you have" makes this less confusing - it can be either the user or Site Kit itself that selects the property here, so by eliminating that "you have" we resolve that inaccuracy. The other issue with a more notable change is that we actually have 5 different permutations of that message (e.g. if a UA tag was found, a GA4 tag was found, both tags were found, whether it was found in the HTML code, or in the GTM container, etc.), so we would need to cater for those too. All of these messages are currently very similar, and the removal of the "you have" fixes the problem reported here for all of them.

**Comment by eclarke1** [comment]
@felixarntz could I kindly ask what priority is this ticket please?

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by felixarntz** [comment]
@eclarke1 The P1 that @tofumatt added sgtm!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified the copy for:**

_UA manually added to header.php_ - [Screenshot](https://user-images.githubusercontent.com/73545194/142874676-053597ef-8b28-4bda-8a25-74f3d495f483.png)
_GA4 manually added to header.php_ - [Screenshot](https://user-images.githubusercontent.com/73545194/142877144-5abd1dd0-1ba0-4630-864e-ef510e5416d9.png)
_Both UA and GA4 tracking codes manually added to site_ - [Screenshot](https://user-images.githubusercontent.com/73545194/142877181-e2c71c61-e6f2-4a33-95d4-8dc0179da841.png)
_Only the UA property matches the one selected on the setup form_ - [Screenshot](https://user-images.githubusercontent.com/73545194/142877209-539c3415-68c3-443e-a60c-2d5b3d57d1c8.png)
_Only the GA4 property matches the one selected on the setup form_ - [Screenshot](https://user-images.githubusercontent.com/73545194/142877234-60af3727-4650-47db-ae10-ff504617e27c.png)
