### ISSUE TITLE
Simplify/refactor current notification component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4153]
As part of migrating notifications to the `unifiedDashboard`, the existing `Notification` legacy component should be renamed to a more specific `BannerNotification`. While the component is somewhat messy in its feature set, it should not be refactored, since the banner notifications will be entirely removed in the near future. However, we can remove a few practically unused pieces of code here as some cleanup.

This is related to #4152, which introduces the new `BannerNotifications` container component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Notification` component should be renamed to `BannerNotification`.
* Its `isDismissable` prop should be renamed to `isDismissible`.
* Its file should be moved to `assets/js/components/notifications/BannerNotification.js`.
* Its usage in other components should (of course) be updated accordingly.
* The following files should be moved:
    * `assets/js/components/legacy-notifications/cta.js` to `assets/js/components/notifications/CTA.js`
    * `assets/js/components/legacy-notifications/dashboard-setup-alerts.js` to `assets/js/components/notifications/SetupSuccessBannerNotification.js`
    * `assets/js/components/legacy-notifications/DashboardCoreSiteAlerts.js` to `assets/js/components/notifications/CoreSiteBannerNotifications.js`
    * `assets/js/components/legacy-notifications/module-settings-warning.js` to `assets/js/components/notifications/ModuleSettingsWarning.js`
    * `assets/js/components/notifications/IdeaHubModuleNotification.js` to `assets/js/components/notifications/IdeaHubPromptBannerNotification.js`
    * `assets/js/components/notifications/UserInputPromptNotification.js` to `assets/js/components/notifications/UserInputPromptBannerNotification.js`
    * `assets/js/components/notifications/UserInputSuccessNotification.js` to `assets/js/components/notifications/UserInputSuccessBannerNotification.js`
    * For all renames also adjust any Storybook or Jest files accordingly.
* The following (unused) files should be removed:
    * `assets/js/components/legacy-notifications/cta-wrapper.js`
    * `assets/js/components/legacy-notifications/nodata.js`
    * `assets/js/components/legacy-notifications/setup-incomplete.js`

## Implementation Brief
* Using `assets/js/components/legacy-notifications/notification.js`,
	* Rename component to `BannerNotification` and move and rename file to `assets/js/components/notifications/BannerNotification.js`.
	* Update references to the `Notification` component to use `BannerNotification` across files.
	* Rename the `isDismissable` prop to `isDismissible` and update references to the old prop name to the new one accordingly across files.
* Move/rename/delete files as per the 5th and 6th bullet points in the AC.
* Update stories and tests to make sure everything pass.

### Test Coverage
* All existing tests should pass.
* Ensure all stories work properly.

## QA Brief

* Notification on normal dashboard should continue to function properly. 

## Changelog entry

* Refactor legacy notification components.

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

- Verified that the notification on current dashboard continues to function properly. I went through setting up each module and made sure that the appropriate notification message appeared on the dashboard. 

![image](https://user-images.githubusercontent.com/73545194/139684315-b1bec29b-3e51-4ba7-8765-0f7cc932eaa1.png)

[Pagespeeds](https://user-images.githubusercontent.com/73545194/139684356-e55956df-5cc3-4880-bb0a-64f958effa05.png) -  [Analytics](https://user-images.githubusercontent.com/73545194/139684441-cf8c2c91-955d-4df2-810e-9850cc35c429.png)  - [AdSense](https://user-images.githubusercontent.com/73545194/139684520-e9a68ac6-c517-41dc-a607-d4aaa6b205a1.png) -  [Optimizer](https://user-images.githubusercontent.com/73545194/139684576-fdc1ea22-3656-4c7a-bbb5-e5b2e64bbae6.png) - [Tag manager](https://user-images.githubusercontent.com/73545194/139684648-640a255e-2b39-49d6-afc7-6435696bbaf3.png)

**Comment by felixarntz** [comment]
## Approval ⚠️ 

@kuasha420 @eugene-manuilov I believe this file https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/IdeaHubModuleNotification.stories.js is now incorrectly named. It targets `IdeaHubPromptBannerNotification` so that should be in its file name too.

**Comment by kuasha420** [comment]
@felixarntz submitted a follow up PR addressing the filename issue along with couple of story label changes. Should be good to go straight to `Approval` as only stories are changed and we already verified the expected functionality. 

CC: @eugene-manuilov @wpdarren

**Comment by wpdarren** [comment]
Confirmed with Arafat that we do not need to retest this as the change was related to storybook and vrt files.  Sending to approved ✅
