### ISSUE TITLE
Return full stops back to the insufficient permissions error description

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#4160]
## Bug Description

![2021-09-29_16-49](https://user-images.githubusercontent.com/873049/135281765-bc397e27-9e02-4095-906b-0a89fea74eb7.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The error message from the `getInsufficientPermissionsErrorDescription` function should always have individual sentences separated from each other with a full stop.
* At the same time, it should still ensure that the last sentence does **not** end in a full stop, per our UX guidelines (text with 1 or 2 sentences should not end in a full stop).

## Implementation Brief
* Using `assets/js/util/insufficient-permissions-error-description.js`,
	* Add a full stop, `.` at the end of every `message`.
	* Before returning the complete string from the function, check:
		* if `userInfo` is empty and remove the last `.` from `message`.

### Test Coverage
* Add tests for `getInsufficientPermissionsErrorDescription`.

## QA Brief

* 

## Changelog entry

* Add full stops to the insufficient permissions error description.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv it was removed as part of the work for #2597 (see here: https://github.com/google/site-kit-wp/pull/3316/files#diff-8e4815a7647006d9aea19dc2447a736e048c3ec903b9babb2af7934d3a06d451).

**Comment by eugene-manuilov** [comment]
@asvinb full stops should be added back to each version of the message copy and then trimmed from the end of the combined string. This is important to add full stops to all messages because it needs to be properly localized.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by eugene-manuilov** [comment]
@mitogh could you please add QAB?

**Comment by mitogh** [comment]
Thanks, @eugene-manuilov however while I was trying to find a scenario to replicate this issue I found 2 existing bugs in production that prevent us from actually testing this behavior as it should be.

- #4542
- #4543 

Let me know what the best next steps should be here instead.

cc @wpdarren

**Comment by wpdarren** [comment]
@eugene-manuilov any thoughts on how we can test this based on @mitogh comment above?

**Comment by eugene-manuilov** [comment]
@wpdarren try to edit the Analytics settings using a secondary user that doesn't have access to the selected Analytics account.

**Comment by felixarntz** [comment]
@eugene-manuilov @wpdarren The ACs here were defined a while ago and are actually not entirely correct. I don't remember exactly in which issue we had that conversation a few weeks back, but I remember for sure that we clarified that actually only single sentences should ever not end in a full stop.

This is not a big deal, but it should also be really quick to fix - can we add the full stop also to the second sentence above?

**Comment by mitogh** [comment]
A PR has been created with the requested change:

- https://github.com/google/site-kit-wp/pull/4572

cc  @felixarntz @eugene-manuilov @wpdarren

**Comment by felixarntz** [comment]
@mitogh The changes in the PR looks good, but it needs to be based on and target `main` - I left a PR comment with that as well. Can you please update it?

**Comment by mitogh** [comment]
Thanks, @felixarntz as discussed in previous PR #4572 was closed due it was based on `develop` instead I've cherry-pick the commit into a new PR #4574 and opened it against `main`.

**Comment by felixarntz** [comment]
Thanks @mitogh, merged!

Note for the future: Please keep in mind to also move and assign the issue accordingly in the project board, e.g. move from _Execution_ to _Code Review_ and unassign yourself if you're no longer working on it / waiting for someone else to review 👍

**Comment by felixarntz** [comment]
Approval (based on https://github.com/google/site-kit-wp/issues/4160#issuecomment-996023830) ✅

**Comment by mitogh** [comment]
Thanks for the flag :100: @felixarntz
