### ISSUE TITLE
Fix user input notification GA event potentially firing without showing notification

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4167]
The `${ viewContext }_user-input-prompt-notification` GA event `view_notification` is currently fired in the `UserInputPromptBannerNotification` component, which is problematic since the notification _may_ not actually be rendered at that point - the inner `UserInputSettings` component contains logic to conditionally return `null`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `view_notification` GA event in the `${ viewContext }_user-input-prompt-notification` category should only be fired if that notification is actually rendered.
    * It must be ensured though that it is still _not_ fired when that same content is rendered as part of the Site Kit settings (i.e. when `UserInputSettings` is rendered outside of `UserInputPromptBannerNotification`).

## Implementation Brief
* Using `assets/js/components/notifications/UserInputPromptBannerNotification.js`,
	* Check if the user has completed user input by querying the `core/user` data store via the `getUserInputState` selector. If the latter is equal to `completed`, then do not call `trackEvent` upon mount.

### Test Coverage
* No new tests to be added.

## QA Brief

* Enable Unified Dashboard And User Input feature flags. 
* Install and Enable Google Analytics Debugger.
* Visit Main Dashboard and see that the `view_notification` has been fired.
* Complete the User Input Setup.
* Visit Main Dashboard again. The event should no longer fire. 

## Changelog entry

* N/A

**Comment by asvinb** [comment]
@felixarntz The AC is outdated mostly because we refactored the event categories and actions. I've added the IB which takes into account the updated tracking details.

**Comment by felixarntz** [comment]
@asvinb Yep, I've updated the ACs to reflect the current names. IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- `view_notification` event in the `dashboard_user-input-prompt-notification` category is fired when notification is rendered.   - [Screenshot](https://user-images.githubusercontent.com/73545194/142229308-7b6766b0-3e53-4f8c-ac55-9e9c25b461c9.png)

- `view_notification` event is not fired when that same content is rendered as part of the Site Kit settings
- `view_notification` event is not fired when User input questions are displayed on Site Kit dashboard.
- `view_notification` event is not fired on Site Kit dashboard after completing user input questions.
