### ISSUE TITLE
Refactor notification for module alerts for unified dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4168]
The `DashboardModulesAlerts` component, which is responsible for rendering any potential module notifications (only used by AdSense at this point), is still using some odd legacy code to get those notifications instead of relying on datastore infrastructure for this purpose. It should be refactored to use each active module's `getNotifications` selector.

Then an equivalent version of it should be created that relies on the new `BannerNotification` component from #4153.

Once that refactoring is completed, the component should also be integrated into the `BannerNotifications` component (see #4152).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The `DashboardModulesAlerts` component should be refactored to use the datastore instead of utility functions. Since module notifications are only relevant for AdSense at this point (also see related #4172), it should be changed to only focus on AdSense, as we don't want to build a replacement API for the current filter-based allowlist of modules (since that would be preliminary as notifications will be revamped holistically in the future). More details below:
* The component file should be renamed/moved to `assets/js/components/notifications/AdSenseAlerts.js`.
* If AdSense is not active or if there is no AdSense account ID set yet, the component should return `null`.
* The component should otherwise request AdSense notifications via the `modules/adsense/data/notifications` REST endpoint, which it should call relying on the existing `modules/adsense` `getNotifications` selector.
* Any notifications returned should be rendered like they are today.
* The refactored component should be added to the `BannerNotifications` component from #4152. It should be rendered/be part of the rendered inner components when the AdSense module is active, unless the `notification=authentication_success` or `notification=user_input_success` query parameters are present (this should already exist as a check somewhere in the component as of #4152).
* The now unused legacy functions `modulesNotificationsToRequest` and `getModulesNotifications` should be removed. In the `getTotalNotifications` function that calls the latter, that particular if condition should simply be removed so that the function is no longer called from there.

## Implementation Brief
* Once #4152 has been merged.
* Move `assets/js/components/legacy-notifications/dashboard-modules-alerts.js` to `assets/js/components/notifications/AdSenseAlerts.js` and component renamed to `AdSenseAlerts` and using the file:
	* Check if the `AdSense` module is active by querying the `core/modules` data store via the `isModuleConnected` selector, with `adsense` as parameter.
	* Check if there is an AdSense account ID by querying the AdSense data store via the `getAccountID` selector.
	* If AdSense is not connected or there is no AdSense account ID, return `null`.
	* Check if there are AdSense notifications by querying the AdSense data store via the `getNotifications` selector.
	* Return the notifications like how they are currently.
	* Remove the `alerts` state variable as well as the utility functions used in the file such as `modulesNotificationsToRequest` and `getModulesNotifications`.
* Render `AdSenseAlerts` within `BannerNotifications` as per the AC.
* Using `assets/js/components/legacy-notifications/util.js`,
	* Remove the use of the `getModulesNotifications` function in `getTotalNotifications`
* Remove the unused legacy functions `modulesNotificationsToRequest` and `getModulesNotifications`.

### Test Coverage
* No new tests to be added.

## QA Brief
* Connect AdSense module.
* Go to the main dashboard
* Run the following command in the browser's console:
	```js
	googlesitekit.data.dispatch('modules/adsense').addNotification({
		id:'adsense-notification',
		title: 'AdSense notification',
		description: 'AdSense notification description',
		isDismissable: true,
		format: 'large',
		severity: 'win-info',
		ctaURL: 'https://..',
		ctaLabel: 'Complete setup'
	});
	```
* A notification should appear below the header.

## Changelog entry

* N/A

**Comment by asvinb** [comment]
@felixarntz Something just jumped at me. In the AC, it mentions that:
>The now unused legacy functions modulesNotificationsToRequest and getModulesNotifications should be removed. In the getTotalNotifications function that calls the latter, that particular if condition should simply be removed so that the function is no longer called from there.

It concerns the [following lines](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/legacy-notifications/util.js#L62-L69). So if we are removing the call to `getModulesNotifications`, it means that `getTotalNotifications` will always return `0` which looks incorrect to me. Maybe we are missing something in the AC here? 🤔

**Comment by felixarntz** [comment]
@asvinb Yes, that is okay. This approach to count the notifications hasn't really been working correctly for a very long time, it doesn't account for most of our current notifications. With that said, let's still not remove it entirely at this point, since we're going to eventually rebuild this for a new notification system anyway. So while it's strange, let's do it as outlined in the ACs for now, i.e. the total count will always be 0.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt I am assuming we are not running QA on the actual message at this stage?  Just noticed that the AdSense logo is quite small and didn't want to be nit-picky if it's just a check to make sure the message appears. 

![image](https://user-images.githubusercontent.com/73545194/141494389-19da076d-5dd4-43ad-bac9-ff0f744d0874.png)

**Comment by tofumatt** [comment]
@wpdarren Correct, that text is what appears in the code copied from the QA brief; the aim here is just to see the notification, so that is all good and expected 👍🏻

**Comment by wpdarren** [comment]
QA Update: ✅ 

- A notification appears below the header.

![image](https://user-images.githubusercontent.com/73545194/141494389-19da076d-5dd4-43ad-bac9-ff0f744d0874.png)
