### ISSUE TITLE
Refactor core site notification component to rely on new datastore actions to accept/dismiss notifications

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4170]
The `CoreSiteBannerNotifications` component (see #4153) should be refactored to rely on two new actions to accept or dismiss a notification in the `core/site` datastore.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The `assets/js/components/notifications/CoreSiteBannerNotifications.js` component (moved from `assets/js/components/legacy-notifications/DashboardCoreSiteAlerts.js` in #4153) should be refactored to use the datastore instead of utility functions for interacting with its notifications. More details below:
* The `core/site` datastore should receive actions `acceptNotification` and `dismissNotification`, extending the base notifications sub-store returned by `createNotificationsStore`. In other words, the two actions **must not** be implemented into `createNotificationsStore`, as they don't apply to other notifications stores.
* The `acceptNotification` and `dismissNotification` actions can probably rely on a lower-level, private action like `markNotification`. The behavior overall should be similar to the code in `assets/js/components/legacy-notifications/site/mark-notification.js`, calling the `core/site/data/mark-notification` endpoint accordingly. Since the `core/site` notifications sub-store also supports `clientNotifications` to which this doesn't apply, the actions should only trigger an API request if the notification ID given is for an entry in `serverNotifications`.
    * As always, the API call to `core/site/data/mark-notification` should happen via `createFetchStore` under the hood.
* The `CoreSiteBannerNotifications` should use the new actions instead of the functions from `assets/js/components/legacy-notifications/site/mark-notification.js`.
* The `assets/js/components/legacy-notifications/site` folder should then be removed.

## Implementation Brief
* Using `assets/js/googlesitekit/datastore/site/notifications.js`,
	* Extend `notifications` using `Data.combineStores` to include 2 new actions:
		* acceptNotification
		* dismissNotification
	* The behavior of the 2 actions should be similar to the code in `assets/js/components/legacy-notifications/site/mark-notification.js`.
	* Both actions can use another action, `markNotification` to make API calls to `core/site/data/mark-notification`.
	* The API calls should be handled via `createFetchStore` which means that `markNotification` should be an action of a data store partial created by  `createFetchStore`, and then combined to the exported store via `Data.combineStores`.
* Update `CoreSiteBannerNotifications` to use the new actions instead of the functions from `assets/js/components/legacy-notifications/site/mark-notification.js`.
* Remove `assets/js/components/legacy-notifications/site`.

### Test Coverage
* Add tests for the new actions.

## QA Brief

The behaviour here isn't changing, but the implementation is. Here's how we confirm that the new implementation works as it should:

Open the dashboard `/wp-admin/admin.php?page=googlesitekit-dashboard`

Open your dev tools and keep them open.

Use this snippet to trigger a notification on your dashboard:
```
window.googlesitekit.data.stores['core/site'].actions.receiveGetNotifications([{
        id: 'test-notification'+Math.random(),
        title: 'Google Analytics 5 Beta',
        content: 'Upgrade to the latest and greatest version of Analytics!',
        ctaURL: '#ga5-upgrade',
        ctaLabel: 'Upgrade to GA5!',
        learnMoreURL: '#learn-more',
        learnMoreLabel: 'Learn more',
        dismissible: true,
        dismissLabel: 'Dismiss this message',
}])
```

Expected notification:

<img width="578" alt="Screen Shot 2021-11-13 at 4 10 42 PM" src="https://user-images.githubusercontent.com/373931/141662676-0007d4fc-2d2c-4391-9f71-f0ed947d3c57.png">

* Press the `Upgrade...` button.
* Trigger another notification, then press the `Dismiss...` button.
* Go to the network tab, you should have two requests to `mark-notification` as per the following screenshots:
<img width="1195" alt="Screen Shot 2021-11-13 at 4 12 49 PM" src="https://user-images.githubusercontent.com/373931/141662754-6c99596e-c394-480a-937f-5a76af414dad.png">
<img width="1197" alt="Screen Shot 2021-11-13 at 4 12 54 PM" src="https://user-images.githubusercontent.com/373931/141662753-e16c9936-f11c-46c6-a356-f0d73ab2175d.png">

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@ivankruchkoff @eugene-manuilov  all is good until I click on the upgrade button.   This message appears. 

```
googlesitekit-vendor-2c139029d5338605b54a.js:1 POST https://dahazi.us2.instawp.xyz/index.php/wp-json/google-site-kit/v1/core/site/data/mark-notification?_locale=user 500
googlesitekit-api-b87799dda635c6a8279a.js:1 Google Site Kit API Error method:POST datapoint:mark-notification type:core identifier:site error:"invalid notification ID"
```
Any ideas?  I see the same in the network tab as well.

**Comment by ivankruchkoff** [comment]
@wpdarren that's a non-issue.

We're triggering a dummy remote notification, and WordPress is trying to mark it as accepted, but it doesn't exist, hence the error. 

Reference:
https://github.com/google/site-kit-wp/blob/develop/includes/Core/Notifications/Notifications.php#L190-L192

I couldn't find a valid notification ID on the original ticket https://github.com/google/site-kit-wp/issues/1110

cc @eugene-manuilov / @aaemnnosttv

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@ivankruchkoff @aaemnnosttv  Tried this again today. I am unable to pass this because I am not seeing the two requests to `mark-notification` as per the screenshots.  As per my [comment above](https://github.com/google/site-kit-wp/issues/4170#issuecomment-975468136) the error appears in console and network tabs. 

1. Unified Dashboard is enabled. 
2. I go to `/wp-admin/admin.php?page=googlesitekit-dashboard`
3. I paste in the code into console.  I observe the error. 
4. When I go to network tab, the request has the same error. 

Can you tell me why I am not seeing the two mark-notification requests? Are there any steps not included?

**Comment by aaemnnosttv** [comment]
@wpdarren please try using this instead

```js
googlesitekit.data.dispatch('core/site').receiveGetNotifications([{
        id: 'uxr_study',
        title: 'Google Analytics 5 Beta',
        content: 'Upgrade to the latest and greatest version of Analytics!',
        ctaURL: '#ga5-upgrade',
        ctaLabel: 'Upgrade to GA5!',
        learnMoreURL: '#learn-more',
        learnMoreLabel: 'Learn more',
        dismissible: true,
        dismissLabel: 'Dismiss this message',
}])
```

**Comment by ivankruchkoff** [comment]
@wpdarren this was my experience with the `id: 'uxr_study',`

https://user-images.githubusercontent.com/373931/143132476-c3885161-ee76-47ed-9495-4b22958e1692.mp4

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When clicking on the `Upgrade to GA5` button and `Dismiss this message` link the two requests to `mark-notification` appear in the network tab in the console. 

![image](https://user-images.githubusercontent.com/73545194/143241640-32b1f88a-e7e3-4bd7-97b6-90955d0be947.png)
