### ISSUE TITLE
Remove unnecessary legacy filters

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4172]
There are a few legacy JS filters that should be removed. The respective code shouldn't be further refactored though since it will be eventually removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit.TotalNotifications` JS filter should be removed, as it is unused anyway.
* The `googlesitekit.ModulesNotificationsRequest` JS filter should be removed as well. It is currently only used by the AdSense module, that usage should be removed. Instead the `adsense` module slug should simply be hard-coded into where the filter is currently applied. While that is not quite the proper approach either, it is acceptable for this legacy code, as the main purpose for now is to get rid of that "API".
    * This "API" is legacy and we won't ever use it for more than what it is used for right now (it will soon be removed and replaced with something better).

## Implementation Brief
* Using `assets/js/components/legacy-notifications/util.js`,
	* Remove the use of the `googlesitekit.TotalNotifications` filter in the `getTotalNotifications` function.
	* Update the `modulesNotificationsToRequest` function to return an array which only contains `adsense` and remove the use of `googlesitekit.ModulesNotificationsRequest`.
* Using `assets/js/modules/adsense/index.js`,
	* Remove the `googlesitekit.ModulesNotificationsRequest` filter.

### Test Coverage
* No new tests to be added.
* Existing tests should pass.

## QA Brief

Setup:
* Create a new site on https://jurassic.ninja/
* Install and activate the [Site Kit helper](https://sitekit.withgoogle.com/service/download/google-site-kit-dev-settings.zip) plugin.
* In Developer Settings, set the Custom Site URL to a site with AdSense that you have access to e.g. https://oi.ie.
* Run through the SiteKit setup - do not connect AdSense at this point.

You should now verify that the correct requests for notifications are being made. The notifications are cached, so session storage should be cleared before reloading the Dashboard and checking the devtools network tab to see the request has been made.

* Open devtools and clear session storage:
![image](https://user-images.githubusercontent.com/18395600/139689056-4dbb3485-ea23-4f5a-a41f-027b22062434.png)
* Now open the network tab. It's helpful to add a filter, e.g. `notifications`.
![image](https://user-images.githubusercontent.com/18395600/139689327-670d282c-c746-4cd0-8735-ee8376943edc.png)
* Reload the Dashboard. You should see one notifications request to `google-site-kit/v1/core/site/data/notifications`:
![image](https://user-images.githubusercontent.com/18395600/139689483-55cee267-b19a-4798-b86a-741d7fa2e217.png)
* Run through the AdSense setup process.
* Clear the session storage again.
* Reload the Dashboard. You should now see an additional notifications request being made, to `google-site-kit/v1/modules/adsense/data/notifications`:
![image](https://user-images.githubusercontent.com/18395600/139690074-c1c799cf-4297-4dfd-86df-1302482f6ea1.png)

## Changelog entry

* Remove a few legacy client side filters.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
@techanvil would you please add a QA brief?

**Comment by techanvil** [comment]
> @techanvil would you please add a QA brief?

@aaemnnosttv apologies, I thought I had. Thanks for pointing it out! I've added a QA brief, I hope it's sufficient?

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – it would be good to add a little more detail around what to look for as we probably don't have any AdSense accounts that have alerts that would be surfaced here anyways. What we can look for though is that the request is made in the devtools (could be QA:Eng here but I think @wpdarren is familiar with this) when AdSense is active, and not made when it isn't. This request is cached as well which should be kept in mind when attempting to trigger it as the request won't be made if the cache is present. So a little more detail about what to look for here would be good, again because we can't really rely on the data returned by the request for notifications, the important thing is mostly to make sure they are still requested or not as today.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv - that was most helpful. I've updated the QA brief, hopefully that provides enough info now!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Based on @techanvil excellent QAB instructions, I have confirmed:

- I see one notification request to `google-site-kit/v1/core/site/data/notifications`

![image](https://user-images.githubusercontent.com/73545194/139699867-18df258e-af2f-4c00-8629-1f2bc2dac8dd.png)

When AdSense is activated. 

- I see an additional notifications request being made, to `google-site-kit/v1/modules/adsense/data/notifications`

![image](https://user-images.githubusercontent.com/73545194/139699989-5c819722-b7a4-4a97-a746-4ac782a91436.png)

I'm approving this unless @aaemnnosttv has any other areas that we should QA.
