### ISSUE TITLE
Detect if AMP is used in order to prevent placement of both GA and GTM scripts

### ISSUE THREAD

**Issue by kmwilkerson** [google/site-kit-wp#4174]
## Bug Description

Even if AMP is not used on a site, the Site Kit GTM connection still requires an AMP container. If not selected, it automatically creates one. If the user does not know to go into this new auto-created container and set up the GA tag/trigger, the Site Kit GTM connection errors out and places **both** the standard/non-AMP GTM container script and the GA script (from the GA connection) on the page. This results in doubled data.  

The only way I was able to resolve this error of double counted data, was going into the auto-created AMP GTM container and create a tag and trigger for GA (even though it would never be used). 

## Steps to reproduce

1. Disconnect Site Kit and reconnect - the GA connection takes place in the original oAuth
2. Connect GTM, but do not select an AMP container (presumably because you don't have one because you aren't using AMP). There is no error message in the GTM connection unless you close it and reopen it. Even then the error message is vague (see screenshot 1).  
3. Go to the site and see data double counted (screenshot 2).

## Screenshots

1. ![Screen Shot 2021-09-29 at 2 42 23 PM](https://user-images.githubusercontent.com/20666833/135533508-8db3016e-8626-4e30-86b4-5b8d85a0986c.png)

2. ![Screen Shot 2021-09-29 at 2 31 07 PM](https://user-images.githubusercontent.com/20666833/135533530-e09b68c5-ae71-48ac-9c2d-ca7154f5a072.png)

## Additional Context

This error will only occur for users who are using GTM to place GA and who are not using AMP.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kmwilkerson** [comment]
@jamesozzie I'm on the Newspack team at Automattic where I'm seeing this issue on several of the sites on our platform. The sites in question don't even have the AMP plugin installed. The one thing to note is that Newspack sites are built using some of the AMP framework -- could this be leading to the detection of "AMP-ness"?

**Comment by jamesozzie** [comment]
Hi @kmwilkerson, 

In that case let me check this with a sample Newspack setup. From previous checks I think AMP is one of the plugins suggested during setup however if users don't have this active you're correct that this shouldn't result in an AMP container dropdown field when connecting Tag Manager. 

I'll check back with you here after some testing.

**Comment by jamesozzie** [comment]
Hi @kmwilkerson 

I've performed the following checks with the Newspack theme (1.49.0), the Newspack plugin (1.59.0, when connecting Tag Manager within Site Kit:
- Newspack theme, with no other plugins active - [Only a web container](https://i.imgur.com/NjjS1KX.png) dropdown appears
- Newspack theme & Newspack plugin active but the setup steps not complete within the Newspack plugin (Demo content not installed & Newspack suggested plugins not active) - [Only a web container](https://i.imgur.com/NjjS1KX.png) dropdown appears ([example](https://recordit.co/RJus8xn8uz))
- Newspack theme & Newspack plugin active - with the setup for the Newspack complete - [Both a web container & AMP container are present](https://recordit.co/GVYloczE5F). 

From the above checks it seems the AMP container during Site Kit setup is present upon completing the Newspack plugin setup steps - as you've mentioned. This is as a result of the AMP plugin being activated by default after following the Newspack plugin setup steps. Understandably this would be confusing for users - being asking to select an AMP container when they may not be aware they're using AMP. While users may not be aware AMP is active, deactivating or removing the AMP plugin does result in the AMP container dropdown on longer appearing during Tag Manager setup within Site Kit ([recording](https://recordit.co/RezQvuhlOQ)).

There are other plugins in addition to the AMP plugin that are also activated by default upon completion of the Newspack steps, including the PWA plugin and Yoast plugins, as seen below:

![P4AJuJEEPb](https://user-images.githubusercontent.com/41326532/135695013-8d6b8879-0a8f-4f8e-a7af-cc07b29f030b.gif)

As you mentioned some of the impacted sites are not using AMP can you check whether these users have deactivated the AMP plugin from their plugins page? If so and if the AMP container dropdown remains present I'd be happy to check one of their site setups. Would it be possible for you to share an impacted site URL or preferably a [Site Health information](https://i.imgur.com/Rtkmsba.png) report from one such site?

Once we figure out or determine any AMP related issue with Tag Manager that needs to be addressed we'll also check any impacted sites in relation to the double reporting of Analytics property hits. Site Kit only inserts a web container on non AMP URLs and an AMP container on AMP URLs, similar to how it places it's Analytics snippets. Unfortunately there have been reports of snippet duplication when using the Tag Manager Chrome extension with Site Kit, so this may not be related. We will however look into this after determining more on Newspack users and Tag manager when connected via Site Kit. 

Let me know if you have any questions with the above.

**Comment by jamesozzie** [comment]
@kmwilkerson Just following up with you on this. As some users are being asked to select an AMP container due to the AMP plugin active upon following the standard Newspack plugin setup wizard do you think a new feature allowing users not to select any AMP container would be of benefit for your users? That way users could choose to not include any Tag Manager snippet for their AMP URLs. 

![image](https://user-images.githubusercontent.com/41326532/135893403-91f11019-75b4-4880-94b0-8bfc39907d8f.png)

Alternatively I could create a feature request to add a link or tooltip to the AMP reference, guiding users further on this?

![image](https://user-images.githubusercontent.com/41326532/135893563-5f09a33e-ae6e-4ebc-aeb1-649fa3fb0427.png)

Let me know if you think any of the above would be useful.
