### ISSUE TITLE
Avoid refreshing token on non-Site Kit screens

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4182]
In #3477, we improved the way refresh tokens are refreshed: By doing it proactively, we avoid an excessive number of redundant refresh requests happening at the same time. However, that implementation also added the proactive refresh regardless of the admin screen, which now causes it to happen way more often than before, thus in a way having adverse effects.

We should only do this proactive refresh on a subset of screens, related to where Site Kit is used.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The proactive token refresh logic of Site Kit should only trigger on the following screens:
    * `googlesitekit-dashboard` (also for the "entity dashboard" version of it)
    * the WP dashboard (which has the Site Kit widget in it)
* For any other screens which Site Kit may still integrate with, we should keep relying on the previous refresh-on-demand logic, which should have smaller implications of excessive requests there (as much fewer API requests are used).
* The proactive token refresh should still work on both pageload and heartbeat, and in both cases it should only fire when in one of the above screens.
    * For Heartbeat, see the [`wp_ajax_heartbeat()` function](https://developer.wordpress.org/reference/functions/wp_ajax_heartbeat/) for details on how to get the screen ID.

## Implementation Brief

**The PR for this should target the 1.43.0 release, so likely be opened against `main`.**

#### `Core\Authentication\Authentication`

* Rename and update signature to `$maybe_refresh_token()` to `$maybe_refresh_token_for_screen( screen_id )`
    - If the given `screen_id` is not `dashboard` or `toplevel_page_googlesitekit-dashboard`, return
* Update the action on `heartbeat_tick` to call `$maybe_refresh_token_for_screen` function with the `$_POST[screen_id]`
* Update the previous action for `$maybe_refresh_token` on `admin_init` to be hooked on `current_screen` instead which accepts the current `WP_Screen` instance as its only parameter
    * Call `maybe_refresh_token_for_screen` passing the given `WP_Screen->id`

### Test Coverage

* Update tests for `Authentication` as needed

## QA Brief
* Stop your local environment
* Configure HTTP proxy on your local machine following instructions in the [engineering workflow doc](https://docs.google.com/document/d/1vYRA-YxxZdufO6piF0gA1k60N3UxbvuqyQr_XfGgvSk/edit#heading=h.faf0umy03arh).
* Reset the token creation time by running the following command:
  ```
  10updocker wp user meta set 1 wp_googlesitekit_access_token_created_at 1
  ```
* Start the mitmproxy app
* Start your local environment
* Open a non-sitekit admin page (for example `Appearance > Themes`: /wp-admin/themes.php) and stay there for about 5 minutes.
* Check the mitmproxy log and confirm that you don't see requests to the `https://sitekit.withgoogle.com/o/oauth2/token/` endpoint.
* Now go to the SK dashboard page and check the mitmproxy log again. Now you should see requests to the token endpoint.
* Reset the token creation time again using the wp-cli command posted above and wait 5 minutes again without refreshing the dashboard page.
* Verify that you see requests to the token endpoint again once a heartbeat request is sent.

## Changelog entry

* Update proactive token refreshing to be limited to main Site Kit and WordPress dashboards.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by kuasha420** [comment]
QA: :heavy_check_mark: 

Made sure that, 
* After resetting the token creation time, no refresh token request was sent while on Non Site Kit page.
* Refresh token endpoint was hit when navigating to Site Kit Dashboard. 
* Again resetting the token creation time and waiting on the dashboard page refreshed the token again in ~5 minutes.

![Screenshot_20211006_233725](https://user-images.githubusercontent.com/6187401/136257806-dd6eec27-5869-48b5-8090-6c1c418195a1.png)
![Screenshot_20211006_235734](https://user-images.githubusercontent.com/6187401/136257815-7273dd6f-6dff-4015-9e88-768ef007499c.png)

LGTM.
