### ISSUE TITLE
Run E2E verbosely

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4201]
## Feature Description

By default our E2E test runs output a high-level result with one line per "suite" like so:

```
PASS tests/e2e/specs/modules/tagmanager/setup.test.js (58.109s)
PASS tests/e2e/specs/modules/analytics/write-scope-requests.test.js (24.318s)
PASS tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js (22.654s)
PASS tests/e2e/specs/modules/adsense/setup-new-user.test.js (47.279s)
```

This is okay, but it hides all of the tests that are done which can be useful to review in a single list for stakeholders, or less technical folks.

By running the tests verbosely, we can get a little more output as to what we're specifically testing rather than just pass or fail. This is also more consistent with our unit tests which provide the same granularity in the output.

```
 PASS  tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js (43.72s)
  setting up the Analytics module with an existing account and no existing tag
    using Proxy auth
      ✓ pre-selects account and property if the tag matches one belonging to the user (16578ms)
      ✓ prompts for account and property if the site URL does not match a property belonging to the user (9167ms)
    using GCP auth
      ✓ includes an option to setup a new account (8805ms)
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E should output individual steps when running rather than only a per-file/suite result

## Implementation Brief

* Update `tests/e2e/jest.config.js` to set `verbose: true`

### Test Coverage

* No additional changes

## QA Brief
* Check the E2E logs for the PR linked to this issue.
* Tests should be more verbose now which now displays all the individual tests ran.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Sounds good! IB ✅

**Comment by wpdarren** [comment]
@eugene-manuilov @asvinb looking at the ticket/QAB, I'm wondering if this is `QA:Eng` but if you feel it is something I can QA, please could you add a few instructions for me?  Thank you!

**Comment by eugene-manuilov** [comment]
@wpdarren, yes, feel free to mark it as `QA:Eng` or if you want to check it too, then open latest E2E tests for the `develop` branch and verify that you can see completed tests for each suite/test file.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

LGTM 🙂 https://github.com/google/site-kit-wp/runs/4455621920?check_suite_focus=true
All of this detail wasn't shown before 
![image](https://user-images.githubusercontent.com/1621608/145206111-7d9afda1-cab5-4f81-986a-1c5f1c774131.png)
