### ISSUE TITLE
Fix odd experience if updating Idea Hub idea state failed

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4207]
Currently, the Idea Hub ideas widget doesn't properly account for errors when updating an idea state (e.g. dismissing, saving, unsaving). The idea just remains in place without explanation. We should ensure that errors (especially relevant due to potential API errors) are surfaced to end users in some way.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub widget should account for errors on all the available actions on an idea so that in case of an error (most likely is an occasional API error) the widget doesn't just silently fail, but shows an error message. It should work as follows:
    * If there is an error in one of those actions, the error message should be surfaced on top of the widget, below the heading, but above the tabs. The message should appear in red letters, the same way that errors are displayed e.g. in the module setup flows. Since this is an error and edge-case, a potential layout shift is acceptable here (we will redesign how errors are surfacing in the future, but not at this point).
    * There should only ever show one of those "update idea state" error messages at a time. In other words, whenever any of those user actions happens, _all_ errors for those actions should be cleared (currently only the error for the same action and the same idea is cleared, which is too granular).
    * If the user switches to another tab after seeing one of these errors, all the errors should be cleared as well (as the error message has been seen at that point and will no longer be contextually applicable).

## Implementation Brief
* Using `assets/js/modules/idea-hub/datastore/idea-state.js`,
	* Update the `baseName` parameter (second) of `receiveError` to always be the same value where `receiveError` is used.
	* Replace `clearError` by `clearErrors`, imported from `errorStoreActions`, having the same `baseName` as the previous bullet point.
* Create `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Error.js` which exports the `Error` functional component.
	* It should get any errors for the Idea Hub datastore via the `getErrors` selector.
	* If there are no errors, return `null`.
	* Otherwise, return the `message` property of the error within a container having `googlesitekit-error-text` as class name.
	* Since the error message can contain HTML, it should be rendered and escaped by using the `sanitizeHTML` function, imported from `assets/js/util/index.js`.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`,
	* Add the new `Error` component before the `TabBar` component.
	* Using the `useEffect` hook, check for changes to `activeTabIndex` to clear errors by dispatching the `clearErrors` action passing the same `baseName` when the errors were created.
* Update `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.stories.js` to include a story where the `Error` component is rendered.

### Test Coverage
* No new tests to be added.

## QA Brief

* Enable `ideaHubModule` feature flag and activate the module. 
* Save some of the ideas. 
* Go to Saved Tab.
* Open Network Tab on Developer Tools and Unsave an idea. 
* Right click on the post request `update-idea-state?_locale=user` and click on Block URL. 
* ![Screenshot_20211028_054428](https://user-images.githubusercontent.com/6187401/139162955-6bc1cfae-0a29-4010-a3bd-7ff569d3e9bd.png)
* Try to remove another idea from the saved.
* You should see an error message over the tab bar in red saying `you are probably offline.`
* Switch to another tab  such as New or Draft.
* The error message should get cleared. 

## Changelog entry

* Update the Idea Hub widget to clear errors when switching tabs

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- After blocking the URL as per the QAB.  When removing an idea from the saved tab,  an error message appears over the tab bar in red saying you are probably offline.
- When switching to another tab such as New or Draft, the error message should get cleared.

![image](https://user-images.githubusercontent.com/73545194/139919737-ab233d25-7c2a-4bbb-8254-1701901c377b.png)

@kuasha420 thank you for these excellent QAB notes 😄
