### ISSUE TITLE
Tag Manager doesn't pre-select the correct Tag Manager container

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4209]
## Bug Description

When connecting the Tag Manager module the select box always defaults to one particular container, and not necessarily the correct Tag Manager container. In my testing it always defaults to one particular Tag Manager container. 

Example below, the site is not associated with the preselected container:

![image](https://user-images.githubusercontent.com/41326532/136832556-02c23d6c-cd05-40d0-a415-0202acfd40cc.png)

This occurs even though the site being setup does already have a container setup. 

![image](https://user-images.githubusercontent.com/41326532/136832847-5c381643-7fc3-433a-984f-03dd1e6e5c24.png)

This can lead to obvious confusion, considering users will always be shown the warning based on the container not matching the URL. A solution to this would be to leave the select field blank or defaulting to the associated container, with each tag manager container associated with a website. 

[Recording of experience](https://recordit.co/0ypSV2dHiM) at present. 

## Steps to reproduce

1. Setup Google Tag Manager
2. View the pre selected container. If users have more than one GTM container setup it doesn't necessarily match the site being connected. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

In Tag Manager setup/settings:
* If no account is set yet, Site Kit should no longer be pre-selecting the first account from the response just like that as it is confusing. It should only pre-select the first account from the response if that is the only account available - otherwise the initial dropdown value should be empty.
* Similarly, if no container is set for the currently selected account, Site Kit should only preselect the first container from the response if that is the only one returned - otherwise the initial dropdown should be empty.
    * This should apply both to initial page load _and_ to when the user selects an account.

## Implementation Brief
* Using `assets/js/modules/tagmanager/datastore/accounts.js`,
	* Update `getAccounts` to dispatch the `selectAccount` action only if there is one account, by checking the length of `accounts` and `getAccountID` is null.
	* Update `selectAccount`:
		* to dispatch the `setContainerID` and `setInternalContainerID` actions only if there is one item in the `webContainers` array.
		* to dispatch the `setAMPContainerID` and `setInternalAMPContainerID` actions only if there is one item in the `ampContainers` array.

### Test Coverage
* No new tests to be added.

## QA Brief

* On https://tagmanager.google.com, setup Tag Manager accounts with some, one and no containers - including both Web and AMP container types. You might want to just add one account to start with, to verify the "single account" case.
* On SiteKit, Navigate to **Settings** > **Connect More Services** and click on **Set up Tag Manager**.
* You'll now be on the Tag Manager setup page. The easiest way of testing different permutations is to modify the Tag Manager accounts on https://tagmanager.google.com, and refresh the Tag Manager setup page.
  * Note that https://tagmanager.google.com has a Trash Can feature which comes in handy if you want to delete then restore an account or container. 
* Verify the account dropdown is only being pre-selected when there is only one account, as per the AC.
* Likewise verify the container dropdown is only pre-selected when there is only one container.
* Check the dropdowns are still functioning as expected in other cases.

## Changelog entry

* Update Tag Manager to pre-select account and containers only when the user has just one account.

**Comment by eugene-manuilov** [comment]
> ... and getAccountID **is not null**.

@asvinb I believe it should be `is null`, shouldn't it?

**Comment by asvinb** [comment]
> > ... and getAccountID **is not null**.
> 
> @asvinb I believe it should be `is null`, shouldn't it?

Good catch @eugene-manuilov . Updated!

**Comment by eugene-manuilov** [comment]
> * Update `selectAccount` to dispatch the `setContainerID` and `setInternalContainerID` actions only if there is one item in the `webContainers` array.

@asvinb, we also need to do the same for the AMP container: https://github.com/google/site-kit-wp/blob/bf6f38e981d420d4a2a3d7cfbe25384fd2e3de8e/assets/js/modules/tagmanager/datastore/accounts.js#L148-L153

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update:

**Verified:**

- If no account is set yet, SK no longer pre-selects the first account. 
- It no account is set yet, SK only selects the first account from the response if that is the only account available 

![image](https://user-images.githubusercontent.com/73545194/143881767-bdc5d2f1-3ba0-45ad-8ffd-afef8b930086.png)

![image](https://user-images.githubusercontent.com/73545194/143881782-ad67c4a2-2c81-4c1f-ba10-dfb456eed5a2.png)

- If no container is set for the currently selected account, Site Kit only preselects the first container from the response if that is the only one returned.
- If no container is on the account, the initial dropdown should be empty.

![image](https://user-images.githubusercontent.com/73545194/143882480-7267ffe0-b4a1-403a-b533-99a4acc6e750.png)

- This was tested on a web and AMP container types.
