### ISSUE TITLE
Refactor/enhance AdSense-specific setup/settings tracking events

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4217]
The AdSense setup/settings should have its GA tracking events refactored, plus a few new ones should be added.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

For **all** of the following events, the (new) event category should be `${ viewContext }_adsense`, where `viewContext` is the current view context (realistically either `moduleSetup` or `settings`). This includes both new events and events that should be renamed.

* In the AdSense setup, two new events should be sent "on pageload" (or more specifically when rendering the AdSense `SetupMain` component):
    * Once the AdSense account status is determined (i.e. not `undefined`), and then every time that it changes to another (non-`undefined`) account status, a `receive_account_status` event should be sent. The account status identifier should be included as event label.
    * Once the AdSense site status is determined (i.e. not `undefined`), and then every time that it changes to another (non-`undefined`) site status, a `receive_site_status` event should be sent. The site status identifier should be included as event label.
* The AdSense account dropdown (which is only used in the very rare case of multiple AdSense accounts) should fire an event `change_account` when the user selects another AdSense account.
* The `create_adsense_account` event should be renamed to `create_account`.
* The `adsense_tag_enabled` event should be renamed to `enable_tag`.
* The `adsense_tag_disabled` event should be renamed to `disable_tag`.

## Implementation Brief

* Update all events below to use the category <code>\`${ viewContext }_adsense\`</code>, where `viewContext` is obtained from `useContext(InViewContext)`.
* Add a `useEffect` hook to the AdSense `SetupMain` (https://github.com/google/site-kit-wp/blob/eb6d7750c4093c715efded685db60e0fdbb66536/assets/js/modules/adsense/components/setup/SetupMain.js#L66)
    * Once the [AdSense account status] is determined (i.e. not `undefined`), and then every time that it changes to another (non-`undefined`) account status, a `receive_account_status` event should be sent. The account status identifier should be included as event label.
    * Whenever [accountStatus](https://github.com/google/site-kit-wp/blob/eb6d7750c4093c715efded685db60e0fdbb66536/assets/js/modules/adsense/components/setup/SetupMain.js#L145) (and is not `undefined`), call <code>trackEvent( \`${ viewContext }_adsense\`, 'receive_account_status', accountStatus )</code>
    * Whenever [siteStatus](https://github.com/google/site-kit-wp/blob/eb6d7750c4093c715efded685db60e0fdbb66536/assets/js/modules/adsense/components/setup/SetupMain.js#L156) changes (and is not `undefined`), call <code>trackEvent( \`${ viewContext }_adsense\`, 'receive_site_status', siteStatus )</code>
* The AdSense account dropdown (which is only used in the very rare case of multiple AdSense accounts) should fire an event `change_account` when the user selects another AdSense account. The change happens here: https://github.com/google/site-kit-wp/blob/eb6d7750c4093c715efded685db60e0fdbb66536/assets/js/modules/adsense/components/common/AccountSelect.js#L50
* Rename the `create_adsense_account` event to `create_account`.
* Rename the `adsense_tag_enabled` event to `enable_tag`.
* Rename the `adsense_tag_disabled` event to `disable_tag`.

### Test Coverage

* N/A

## QA Brief
* Install the `Google Analytics Debugger` extension for your browser
*Go through the AdSense module setup screens and verify that events mentioned in AC are triggered correctly.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
## Approval ❌ 

This is _almost_ good, but the event category is not entirely correct for all the events, it needs to be `${ viewContext }_adsense`, not `${ viewContext }__adsense` (there is now an additional underscore there that shouldn't be). @asvinb Can you please create a follow-up PR against `main`?

**Comment by aaemnnosttv** [comment]
@felixarntz the follow-up PR has been merged and I've confirmed there are no more instances of `viewContext }__` in the codebase 👍

**Comment by felixarntz** [comment]
Thanks for the quick fix - Approval ✅
