### ISSUE TITLE
Enhance GA event dimensions sent

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4219]
The custom dimensions sent with each GA tracking event should be slightly modified and enhanced, to provide more useful contextual information.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The dimensions currently sent with every GA tracking event (see `trackEvent` method implementation) should be updated as follows:

* The value that is sent for `dimension2` should no longer be whether the user is the "first admin". Instead, it should be a comma-separated list of the current user's roles (typically only one role, but it is possible to have multiple roles e.g. via a plugin facilitating that, so this should be covered here as well).
* A `dimension6` should be added, which should be a comma-separated list of all the active modules' slugs. They should be in the order defined per the module order field.
* The two values needed for this can be added to the `_googlesitekitBaseData` global (we can't rely on the datastore here as the tracking still needs to work without loading most of Site Kit). The `isFirstAdmin` value should be removed completely.

## Implementation Brief

In `Google\Site_Kit\Core\Assets\Assets` class:

* In the `inline_data` array of `get_inline_user_data` method, add `roles` with the value `$current_user->roles`.

In the `register` method of `Google\Site_Kit\Core\Modules\Modules` class:

* add a new filter to `googlesitekit_inline_base_data` hook that adds `activeModules`  to the `data` array and passes the keys of `active_modules` as the value of it. 

In `Google\Site_Kit\Core\Authentication\Authentication` class:

* remove `$data['isFirstAdmin']` from the `inline_js_base_data` method.

In `assets/js/util/tracking/index.js` file:

* Remove `isFirstAdmin` from the destructuring assignment of `global._googlesitekitBaseData` and replace it with `activeModules`.
* get the roles of current user from `global._googlesitekitUserData`. ie. `const currentUserRoles = global._googlesitekitUserData?.user?.roles ?? [];`
* Pass both `activeModules` and `currentUserRoles` to the `initialConfig` object.

In `assets/js/util/tracking/createTracking.js` file:

* Update `DEFAULT_CONFIG` by removing `isFirstAdmin: false,` and adding `activeModules` and `currentUserRoles` with empty array as their values.

In `assets/js/util/tracking/createTrackEvent.js` file:

* Remove `isFirstAdmin` from the destructuring assignment of `config`.
* Destructure `activeModules` and `currentUserRoles` from the `config` object.
* Change the value of `dimension2` property of `eventData` object to the joined string `currentUserRoles`. ie. `activeModules.join( ', ' )`
* Add a new property `dimension6` with the comma separated list of currently active modules using `activeModules`.

Remove mentions of `isFirstAdmin` from storybook, tests and fixtures and update them with `currentUserRoles` and `activeModules` instead.

### Test Coverage

* Update failing tests.

## QA Brief

* Using Google Analytics Debugger. check the dimensions sent with some of the tracking event to make sure that the new dimensions are being sent according to the AC. 

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
@eugene-manuilov for some reason user roles remains undefined in the current iteration (when console logged etc). Putting the same `currentRoles` logic inside the `createTrackEvent` retrieves the correct roles array from the global. I have made a PR making the adjustments but do you have any idea why it wasn't working in the previous iteration? 

Cheers. 

@wpdarren thank you for catching it. <3

**Comment by eugene-manuilov** [comment]
Thanks, @kuasha420. PR is merged. Looks like the user data was loaded too late.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov @kuasha420 I am wondering how I can QA the point below in AC? 

> The two values needed for this can be added to the _googlesitekitBaseData global (we can't rely on the datastore here as the tracking still needs to work without loading most of Site Kit). The isFirstAdmin value should be removed completely.

Or is this likely a `QA:Eng` to look at? 

One small observation.  There are no spaces between the commas for roles and modules. I'm assuming that's expected?

**Verified:**

- The value for `dimension2` is set against the user role, i.e. administrator.  When a third-party user role plugin was activated (HM Multiple Roles) and an additional role was added, i.e. editor, both of these roles were in the log. 

-  The value for `dimension6` is be added, with a comma-separated list of all the active modules' slugs. They were listed in the order defined per the module order field. 

![image](https://user-images.githubusercontent.com/73545194/139681573-1facfe0b-2ba3-424b-a04f-a279d9ad964e.png)

**Comment by kuasha420** [comment]
@wpdarren the no space between commas is [intended](https://github.com/google/site-kit-wp/pull/4279#discussion_r736793097). Also that point of AC doesn't need to be QA'd as it's just code. As long as the dimensions are right from SiteKit and non-sitekit pages, we are good.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The value for `dimension2` is set against the user role, i.e. administrator.  When a third-party user role plugin is activated (HM Multiple Roles) an additional role is added, i.e. editor. Both of these roles were in the log. 

-  The value for `dimension6` is added, with a comma-separated list of all the active modules' slugs. They were listed in the order defined per the module order field. 

![image](https://user-images.githubusercontent.com/73545194/139681573-1facfe0b-2ba3-424b-a04f-a279d9ad964e.png)

**Comment by felixarntz** [comment]
## Approval ⚠️ 

Not a big deal, but @kuasha420 could you please have a look at https://github.com/google/site-kit-wp/pull/4279/files#r743058904? Would be great if we could align this in one way or the other.

**Comment by aaemnnosttv** [comment]
@felixarntz follow-up PR is merged 👍

**Comment by felixarntz** [comment]
Thanks everyone for the feedback, Approval ✅
