### ISSUE TITLE
Remove unused `LegacyDashboardAdSenseTopPages` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4227]
The `LegacyDashboardAdSenseTopPages` component is for some reason still in our codebase, but it is entirely unused and should be removed (also the component's file does not have the `Legacy*` prefix which is probably why this went undiscovered before).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The unused `LegacyDashboardAdSenseTopPages` component should be entirely removed from the codebase.

## Implementation Brief

* Remove the line which exports from `DashboardAdSenseTopPages.js` in
https://github.com/google/site-kit-wp/blob/316208ec2d86ecda90b7e86f7d772b0c5030e223/assets/js/modules/adsense/components/dashboard/index.js#L19
* Delete the file [assets/js/modules/adsense/components/dashboard/DashboardAdSenseTopPages.js](https://github.com/google/site-kit-wp/blob/316208ec2d86ecda90b7e86f7d772b0c5030e223/assets/js/modules/adsense/components/dashboard/DashboardAdSenseTopPages.js).

### Test Coverage

* No new tests needed.
* Existing tests should pass.

## QA Brief

* Make sure the component in the AC is deleted.

## Changelog entry

* N/A

**Comment by ozer619** [comment]
I would like to  work on this issue.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark: 

Note: bumped the estimate from `1` to `3`.

**Comment by shayannosrat** [comment]
Would love to take this issue as my first contribution to this repo 🚀

**Comment by asvinb** [comment]
### QA: ✅ 

No refs to `LegacyDashboardAdSenseTopPages` found in the codebase.
