### ISSUE TITLE
Event tracking in E2E tests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#423]
## Bug Description

Nothing is preventing event tracking events from firing during E2E tests which will skew reporting statistics.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* During e2e tests, no Analytics events should be sent to the Site Kit tracker.

## Implementation Brief

We can't mock `sendAnalyticsTrackingEvent` because it is built into the production bundle. Instead we can simply opt-out of Analytics tracking.

* In `e2e/config/bootstrap.js` register a listener on [`page.load`](https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-event-load) which injects the [Google Analytics Opt-Out](https://tools.google.com/dlpage/gaoptout) on every page.  
```html
<script type="text/javascript">window["_gaUserPrefs"] = { ioo : function() { return true; } }</script>
```

See https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out
This snippet opts out of ALL Analytics tracking which is what is added by the official browser extension. There is a simpler property to set on the `window` for opting out of tracking on a specific account/tag basis, but the implementation would basically be the same. It seems safer to opt out of all then to be specific about it.

## Changelog entry

*

**Comment by felixarntz** [comment]
IB ✅

**Comment by lucymtc** [comment]
QA looks good.
While running E2E tests confirming I can run `window._gaUserPrefs.ioo()` in the console and returning `true`
