### ISSUE TITLE
SwG module should allow admins to choose a revenue model

### ISSUE THREAD

**Issue by ChrisAntaki** [google/site-kit-wp#4230]
## Feature Description

SwG shows different UX to website visitors, depending on what kind of monetization model the publisher chose. Currently there are two options: "subscription" and "contribution". The SwG module should let admins choose one

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The SwG module should support an additional `revenueModel` module setting which can be set to either `subscription` or `contribution`.
* The setup flow and settings edit UI should include a dropdown to choose the `revenueModel`. The value of the setting should also be displayed in the settings view UI.
* The user-facing label should be "Revenue model", and the UI elements related to this setting should display below "Publication ID", i.e. above "Products".
* It should not be possible to complete the SwG setup or to save SwG settings without setting an `revenueModel`.
* The `revenueModel` should be required to be set in order for the SwG module to be considered "connected".

## Implementation Brief

* Create a new Select component called `RevenueModelInput`
* Update Swg's `SettingsEdit` component to show a loading indicator if the revenue model setting is undefined
* Add `RevenueModelInput` component to SwG's `SettingsForm` component, and update corresponding Storybook
* Display the revenue model on SwG's `SettingsView` component, and update corresponding Storybook
* Add `RevenueModelInput` component to SwG's `SetupForm` component, and update corresponding Storybook
* Register `revenueModel` in SwG's `datastore/base` class
* Require revenue model to SwG's `datastore/settings` class (plus tests)
* Validate the revenue model is either "contribution" or "subscription"
* Only report SwG as "connected" if revenue model is set (PHP)
* Register `revenueModel` setting, defaulting to an empty string (PHP)

### Test Coverage

- Update affected Storybook tests: `SettingsForm`, `SettingsView`, and `SetupForm`
- Update the `defaultSettings` and `validSettings` in the `SetupForm` tests
- Test the revenue model is required in the `datastore/settings` class
- Update the main PHP module's tests to define the revenue model when eliciting a "connected" response

## QA Brief

* Enable the swgModule feature flag with the tester plugin
* Click "Set up Subscribe with Google" on the Settings > Connect More Services page
* Fill out the form
  * You can set the revenue model dropdown to either Contributions or Subscriptions

## Changelog entry

* Add revenue setting to Subscribe with Google module.

**Comment by felixarntz** [comment]
Thanks @ChrisAntaki, looks good! IB ✅

**Comment by felixarntz** [comment]
@ChrisAntaki Can you also add an estimate for the issue? When deciding on one, please factor in a high-level estimate of how much code there will be to review, including potential rounds of feedback - as in, just because something might take you 1 hour to initially come up with, don't just put a 1 on it, unless it's super-straightforward to implement, code-review and test (which essentially applies almost only to wording changes).

Other than that, this is now ready for engineering!
