### ISSUE TITLE
Missing Unit Characters on Zero Data Widgets

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4238]
## Bug Description

As part of the changes on #4086 and #4085, the unit characters are not appearing on the zero values. 

**Site Kit Dashboard:**

Impressions should have a `K`

**Search console module page**

![image](https://user-images.githubusercontent.com/73545194/137766471-af69f3d7-6ff5-471e-abac-3fa7d7ee2596.png)

Total Impressions should have a `K`
Average CTR should have a `%` 

**Analytics module page**

![image](https://user-images.githubusercontent.com/73545194/137766490-bd250300-dd6e-457b-b4c5-e25d432e76b3.png)

Bounce Rate should have a `%` 
Session Duration should have `m s`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Values rendered in `DataBlock`s should still have their appropriate units applied even if the respective value is 0. Specifically, this means for example percentages like Bounce Rate should display as "0%" and durations like Session Duration should display as "0s".
    * This can be tested in various widgets that use `DataBlock`s, for example the Search Console and Analytics overview widgets on their respective module pages, or the "Bounce Rate" widget in the Search Funnel widget in the entity dashboard.

## Implementation Brief

* In `assets/js/components/DataBlock.js`, change this condition to test whether `datapoint` is defined:
https://github.com/google/site-kit-wp/blob/4fcb58149ce46d346bed4ced38124d13bfe92025/assets/js/components/DataBlock.js#L109-L110
E.g., change it to:
```typescript
			datapoint === undefined
				? datapoint
				: numFmt( datapoint, datapointUnit || undefined );
```

### Test Coverage

* Add the zero data versions of all widgets for which we have loaded variants (e.g. the Search Console and Analytics Overview widgets) to the VRT test suite.
* The happy path "loaded" variants can be seen in `.storybook/storybook-data.js`. These blocks can be copied & modified.
https://github.com/google/site-kit-wp/blob/4fcb58149ce46d346bed4ced38124d13bfe92025/.storybook/storybook-data.js#L69-L72
https://github.com/google/site-kit-wp/blob/4fcb58149ce46d346bed4ced38124d13bfe92025/.storybook/storybook-data.js#L84-L87

## QA Brief

* Setup SiteKit and connect the Analytics module, using an account with zero data.
  * If you don't yet have an account with zero data, you can create a new Wordpress site at https://instawp.io/, install SiteKit on it and setup the Analytics module. You will then need to wait for a while for the data to be initialised, at which point you will have an account with zero data.
* Referring to the AC, navigate to the widgets mentioned and verify that unit characters correctly display after the zeros.

## Changelog entry

* Fix missing unit characters issue on zero data widgets.

**Comment by aaemnnosttv** [comment]
Thanks for raising this @wpdarren – I'm not sure if units are needed here or not but it looks like some of the formatting is missing.

> Total Impressions should have a `K`

`K` would only be added for a site with lots of impressions, thus abbreviated with `K` for thousands, or `M` for millions, etc. A site with less than 1 thousand would show the number itself without metric unit. 

> Session Duration should have `m s`

This would only be `0s`, `m` is only added for durations greater than 60s.

It looks like the main problem here is that we only format the value for a datapoint if it isn't empty, so zero would be left unformatted. https://github.com/google/site-kit-wp/blob/eda6388c3f1b29b51a8cd2594e0e4bc9db1c4d95/assets/js/components/DataBlock.js#L109-L110

@felixarntz was this done intentionally at some point? I think it may have always been this way.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by asvinb** [comment]
@techanvil I'am wondering whether we actually need a VRT scenario for this ticket since we don't really need to test the UI. I think a JS test would be sufficient. Also, in either case, I think the estimate is too low as well 👍 
cc @eugene-manuilov @aaemnnosttv

**Comment by eugene-manuilov** [comment]
> I'am wondering whether we actually need a VRT scenario for this ticket since we don't really need to test the UI. I think a JS test would be sufficient. 

@asvinb we already have VR tests for loaded states of those widgets, so I think it makes sense to add VR tests for zero-data states as well since we will work on a new design for it at some point in the nearest future.

> Also, in either case, I think the estimate is too low as well +1 

As far as I see this ticket requires changes in one line of code + a few new VR tests that can be copy/pasted using existing tests for those widgets. So, `3` seems enough to me, or do you think there is something else to work on here?

**Comment by asvinb** [comment]
@eugene-manuilov Makes sense for the first point. I think `3` might be a little just since it includes VR tests, CR and QA. I remember we said `3` should be for simple changes only 🤔

**Comment by eugene-manuilov** [comment]
> we said `3` should be for simple changes only

Yep and this ticket is a simple one in my opinion. However, I think we can bump it to `7` if we add a point to add zero-data states for all widgets. I'll do go ahead and update it.

**Comment by techanvil** [comment]
Thanks @asvinb and @eugene-manuilov!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Percentages like Bounce Rate display as "0%" and durations like Session Duration display as "0s".
- I went through all of the widgets on module pages, current and unified dashboard. Both main and entity. 
- I also went through widgets with data to make sure the appropriate unit characters appear. 

[Screenshot 1](https://user-images.githubusercontent.com/73545194/144101190-997e24a9-515e-44bd-9597-adf9190049f4.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/144101203-05099d07-fdec-4be9-81e4-737f364d9b91.png) - [Screenshot 3](https://user-images.githubusercontent.com/73545194/144101228-77ab9bdf-ef83-4155-9b71-4e93fe1cc96e.png) - [Screenshot 4](https://user-images.githubusercontent.com/73545194/144101253-c0342025-0599-4005-9cb1-5602de19d80d.png) - [Screenshot 5](https://user-images.githubusercontent.com/73545194/144101277-18e2c627-ec03-4ae7-89e2-9a8ca2397936.png)
