### ISSUE TITLE
Analytics with zero data shows +100% on the Analytics page audience overview graph

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#4255]
## Bug Description

While testing https://github.com/google/site-kit-wp/issues/4226 I noticed that within the Analytics page, on the audience overview graph, if you hover over a date you'll see +100%

## Steps to reproduce

1. Setup a Jurassic Ninja site with the Site Kit plugin installed
2. Activate the Analytics module 
3. Wait a few days and then navigate to the Analytics page
4. Hover over a date in the Audience overview graph

Notice:
![image](https://user-images.githubusercontent.com/57115907/138333866-72dd63f4-9dd8-496a-b9e4-2c6e58e42f7b.png)

Expecting this functionality to match search console:
![image](https://user-images.githubusercontent.com/57115907/138334471-f42abaff-1533-4c8f-919a-6516ed5462f8.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The change percentage "calculation" between current and previous value should always work as follows:
    * If both values >0, like today.
    * If both values ==0, it should be "0%".
    * If current value ==0 and previous value >0, it should be "-100%".
    * If current value >0 and previous value ==0, it should be "100%".
* Specifically, this should also behave that way in chart tooltips with comparison percentages (see screenshot).

## Implementation Brief
* Using `assets/js/util/chart.js`,
	* Create new function `calculateDifference` which accepts 2 parameters, both integers.
		* `currentValue`
		* `previousValue`
	* The function should return the value as per the AC based on the `currentValue` and `previousValue`.
		* Please note that when both values are > 0, the logic should be the same as in the `extractAnalyticsDashboardData` from `assets/js/modules/analytics/util/index.js`
* Using
	* `assets/js/modules/adsense/util/site-stats-data.js`,
	* `assets/js/modules/analytics/util/index.js`,
	* `assets/js/modules/search-console/util/site-stats-data.js`,
		* update the `extractAnalyticsDashboardData` function to use the new function `calculateDifference` to get the value for the `difference` constant.
		* If `difference` is `0`, no SVG icon should be displayed.

### Test Coverage
* Add tests for the new `calculateDifference` function.

## QA Brief

* Follow step to reproduce in a new instawp site. 
* audience graph should no longer show +100% when zero data. 

## Changelog entry

* Fix the incorrect difference for chart values when the current and the previous values equal zero.

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. A few comments:

> Using assets/js/util/index.js, ...

Let's define the new function in the `assets/js/util/chart.js` file where we have chart-related functions.

> Using assets/js/modules/analytics/util/index.js, update the extractAnalyticsDashboardData function to use the new function calculateDifference to get the value for the difference constant...

We also need to update `getSiteStatsDataForGoogleChart` functions in AdSense and SearchConsole modules.

**Comment by asvinb** [comment]
Sounds good. IB updated @eugene-manuilov

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB ✔️

**Comment by eugene-manuilov** [comment]
@kuasha420 could you please add QAB?
