### ISSUE TITLE
AdSense module in Connect More Services Briefly flashes Grey

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#4257]
## Bug Description

In Connect More Services when AdSense is not enabled it initially shows as disabled and then shortly looks enabled.

## Steps to reproduce

Open Connect More Services with AdSense disconnected, notice that it starts off grey. See screen recording.

## Screenshots

https://user-images.githubusercontent.com/373931/138368856-add40121-b439-4c5d-82e5-2a9effbd9484.mp4

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The cards for modules that aren't activated should use a more subtle loading state for while a potential `checkRequirements` function for the module is still resolving. (This needs to be implemented generally for modules, although right now the only module this is relevant and can be tested for is AdSense, with its adblocker check logic.)
* Specifically, instead of rendering the whole card as "gray-disabled" like it is today during loading, it should render the overall card as usual and mark only the activation button itself as disabled.
* Only once the requirements check is completed and _if_ it then results in `false` (i.e. the module cannot be activated), the whole card should show as "gray-disabled".
* In other words, if the adblocker check takes a few seconds, the experience should be that the card looks almost normal while loading (you shouldn't be able to activate the module though in that time), and only if the check gives a negative result, the card should look disabled in an obvious way.

## Implementation Brief

Within `assets/js/components/settings/SetupModule.js`:
* In the `classnames` arguments, change the condition `! canActivateModule` to explicitly check for `false`, i.e. `canActivateModule === false`.
https://github.com/google/site-kit-wp/blob/a608bcba230cf33c225b33730b15204aecfad5f6/assets/js/components/settings/SetupModule.js#L85

### Test Coverage

* No tests needed.

## QA Brief

* Throttle the connection speed to approx. 10240 kbps (10Mbps) for the below steps.
* Case 1: Disable AdBlock extension in your browser. Load the page as per the video in the description above. Then click on the 'Connect More Services' tab. Check to see that the AdSense card is in colour but the 'Setup Adsense Link' should be momentarily greyed out. After this, the whole card and the link should both be in colour.
* Case 2: Enable AdBlock extension. Load the page as above and switch to the 'Connect More Services' tab. Check that the AdSense card is still in colour momentarily and the link is greyed out. After approx. a second, the whole card should be greyed out.

## Changelog entry

* Fix issue when AdSense module in the Connect More Services list briefly flashed grey.

**Comment by aaemnnosttv** [comment]
This is expected due to the asynchronous adblocker check which needs to run. Looks like it's coming from this line where we check for a simple "not" rather than `=== false` which causes it to appear disabled while the check is running. I think this is okay because we wouldn't want to wait until the check was completed to disable the CTA as a user could then potentially bypass this guard if they clicked the setup before it was disabled.

It is a bit of a flicker though so maybe we want to change the appearance of the disabled/warning state instead of the whole card.

**Comment by aaemnnosttv** [comment]
@felixarntz did we decide to only disable the link while it's loading and wait to apply the disabled style to the entire module setup CTA until we know it should be disabled? This is what I recall but just wanted to double-check.

**Comment by felixarntz** [comment]
@aaemnnosttv Yeah that was it I believe. I can add some ACs.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@jimmymadon @eugene-manuilov I have a query on case 2 in the QAB. 

> Case 2: Enable AdBlock extension. Load the page as above and switch to the 'Connect More Services' tab. Check that the AdSense card is still in colour momentarily and the link is greyed out. After approx. a second, the whole card should be greyed out.

When I have AdBlock enabled, the AdSense card and link are greyed out.  I have set the throttle on chrome as per the QAB, tried it a few times on different speeds.  Just checking if the AdSense card should be in colour. It makes sense for it to be in grey straight away to be honest. 

**Verified:**

Disable AdBlock extension on browser. The AdSense card is in colour but the 'Setup Adsense Link' is momentarily greyed out. After this, the whole card and the link are both in colour.

https://user-images.githubusercontent.com/73545194/144075707-ab0384d5-48bf-46f1-a242-57aaacdb8172.mp4

**Comment by jimmymadon** [comment]
The Case 2 in my QAB was to be in line with points 3 and 4 of the AC. However, like @wpdarren says, I myself couldn't replicate having the card in colour and then being greyed out cause the loading is instant at very slow speeds too. 
Furthermore, I also think having the card greyed out from the beginning would still meet the AC as it only does so if AdBlock is on. So I think my QAB Case 2 can be made more lenient to not check for colour in the beginning?

**Comment by eugene-manuilov** [comment]
@wpdarren, that's fine. If it shows the module card greyed out from the beginning, then it's even better for us.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Disabled AdBlock extension on browser. The AdSense card is in colour but the 'Setup Adsense Link' is momentarily greyed out. After this, the whole card and the link are both in colour.

https://user-images.githubusercontent.com/73545194/144075707-ab0384d5-48bf-46f1-a242-57aaacdb8172.mp4

- Enabled AdBlock extension on browser. The AdSense card is greyed out throughout, which is expected.

https://user-images.githubusercontent.com/73545194/144095465-8516ad2c-8148-4f60-9a1e-5bbf3b5409a1.mp4
