### ISSUE TITLE
Idea Hub: Improve UX on mobile when pinning an idea

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4265]
## Bug Description

For Idea hub on small screen sizes: 
When you pin an idea, it would be better UX to jump to the top of the widget, rather than the user having to scroll up to then click on the 'Saved ideas' tab. 

https://app.asana.com/0/1200491083500938/1200765888444289/f 

## Steps to reproduce

1. Make sure Idea hub is activated in the Tester settings
2. Go to 'Idea Hub' widget on a mobile device.
3. Click on the `Pin icon` on one of the ideas. 
4. You will see that the widget slightly shifts but not to the top.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
> When you pin an idea, it would be better UX to jump to the top of the widget, rather than the user having to scroll up to then click on the 'Saved ideas' tab.

@wpdarren why would a user want to switch to the saved ideas tab right after pinning an idea? The idea is that you would come back to it later 🙂  Even scrolling to the top after every pin would be distracting I think.

**Comment by wpdarren** [comment]
@aaemnnosttv good point. 😄  I think when I initially added this to the bug bash board, the widget was refreshing and loading at the bottom, but just taken a quick look, that doesn't seem to be the case anymore. This can be closed.
