### ISSUE TITLE
Analytics CTA Setup link causes the widget contents to "jump" during redirect to Auth Screen

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4267]
## Bug Description

When you click on the Analytics CTA widget (for instance, in the Unified Dashboard Search Funnel Widget without Analytics being connected/active), the contents of the widget changes as it goes from "entirely unconnected" to "setup not complete".

Here's a discussion for context: https://github.com/google/site-kit-wp/pull/4223#pullrequestreview-785958429

## Steps to reproduce

1. Go to the Unified Dashboard by enabling the "Unified Dashboard" feature flag in the Tester Plugin
2. Make sure Analytics is not connected
3. Click on the "Set up Analytics" link in the blue CTA on the top-right side of the screen/Search Funnel widget at the top of the page
4. See the content change from:

<img width="579" alt="Screenshot 2021-10-25 at 21 13 49" src="https://user-images.githubusercontent.com/90871/138764227-ce342b80-1748-4745-ad5d-2f64dc1e11e5.png">

to

<img width="663" alt="Screenshot 2021-10-25 at 21 13 54" src="https://user-images.githubusercontent.com/90871/138764247-1dbb6443-8a20-4401-99ab-1165f40ad09a.png">

before the page redirects.

We should _improve the UX here so that the content does not change as drastically or a progress bar with no user CTA is shown for this state_. Eg. If the user clicks on this setup link, they shouldn't be presented with the same or a different call to action while the page is redirecting to the auth flow. The next time they visit the dashboard, it's fine to show the "Setup incomplete" CTA (as seen in the second screenshot), but it should not appear between when the user clicks the link and the redirect.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When clicking on the "Set up Analytics" button link in the widget above, the widget should not change to the "Complete Analytics Setup" copy while the page redirects to the Authentication URL.
* A progress bar should replace the "Set up Analytics" link/button in the bottom of the CTA widget, so there is no CTA button/link in the widget and the user gets a visual indication that something is happening before/during the redirect
* When the dashboard is visited again (eg. after a full-page refresh), the "Complete Analytics Setup" content for the Analytics CTA widget _should_ appear as usual.

## Implementation Brief
* Using `assets/js/components/ActivateModuleCTA.js`,
	* Update the `onCTAClick` function to dispatch the `setValue` action of the `core/ui` data store, with `${ moduleSlug }_is_being_activated` as key and `true` as value.
	* Set the value to `false` if there is an error.
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`,
	* Query the `core/ui` data store to check if the analytics module is being activated, passing the `analytics_is_being_activated` key.
	* Update the condition to display `ProgressBar` if `analytics_is_being_activated` is `true`.
	* Update the condition to display `ActivateModuleCTA` and `CompleteModuleActivationCTA` if `analytics_is_being_activated` is `false`.

Note:
* There is a split second delay when the value for `isNavigatingTo` changes, maybe due to some async functions which causes the `CompleteModuleActivationCTA` to appear for 1 second before the progress bar displays.

### Test Coverage
* No new tests to be added.

## QA Brief
* Disconnect the Analytics module.
* Enable the `unifiedDashboard` feature flag.
* Go to the main dashboard.
* You will be prompted to set up Analytics.
* After clicking on the CTA to set up the module, you should see a progress bar immediately. The `CompleteModuleActivationCTA` component should not be rendered (second screenshot in the ticket description).

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

- When clicking on the "Set up Analytics" button link in the widget, it does not change to the "Complete Analytics Setup" copy.  Instead, a progress bar replaces the "Set up Analytics" link/button in the bottom of the CTA widget.  When the dashboard is visited again the "Complete Analytics Setup" content for the Analytics CTA widget appears as usual.
- Also checked the behaviour on smaller screen sizes. 

https://user-images.githubusercontent.com/73545194/141127027-91cff0be-2bed-4ddb-b5c4-ad0ab4f94f8e.mp4
