### ISSUE TITLE
Ensure gathering data messages in WP dashboard widget and admin bar UI are only shown when applicable

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4270]
Follow-up to #4085 and #4086: Those two issues only encompassed updating the UI in the Site Kit dashboard accordingly. The WP dashboard widget and the admin bar UI still surface the "gathering data" messages even in cases where the services aren't gathering data, but rather the site simply has 0 views/impressions. This issue is about fixing the UI in those areas accordingly as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The WP dashboard widget should show 0s instead of the blue "gathering data" banners for Search Console impressions and clicks respectively _if_ Search Console isn't gathering data (see `isGatheringData` selector from #4085).
* The WP dashboard widget should show 0s instead of the blue "gathering data" banners for Analytics visitors and avg. time on page respectively _if_ Analytics isn't gathering data (see `isGatheringData` selector from #4086).
    * Related to #4238, it should be ensured the units are included, i.e. "Avg. time on page" should say "0s" and not just "0".
* The WP dashboard widget should not display the popular pages table at all _if_ its Analytics report is only 0s - the "gathering data" message in its place should only be displayed if the service is truly gathering data. It doesn't add anything in that case, and showing the two Analytics-based 0 values (see above point) is sufficient to indicate that the site doesn't have any views at all.
* The WP admin bar UI should show 0s instead of the blue "gathering data" banners for Search Console impressions and clicks respectively _if_ Search Console isn't gathering data (see `isGatheringData` selector from #4085).
* The WP admin bar UI should show 0s instead of the blue "gathering data" banners for Analytics visitors and sessions respectively _if_ Analytics isn't gathering data (see `isGatheringData` selector from #4086).
* Storybook coverage for both areas showing purely 0s should be included.

## Implementation Brief

* Update the following components to display 0s instead of the blue "gathering data" banners if Search Console isn't gathering data anymore. Use the similar approach from #4085 to determine the gathering status of the Search Console module.
  * WPDashboardClicks
  * WPDashboardImpressions
  * AdminBarClicks
  * AdminBarImpressions
* Update the following components to display 0s instead of the blue "gathering data" banners if Analytics isn't gathering data anymore. Use the similar approach from #4086 to determine the gathering status of the Analytics module.
  * WPDashboardUniqueVisitors
  * WPDashboardSessionDuration
  * AdminBarSessions
  * AdminBarUniqueVisitors
* Update the `WPDashboardPopularPages` component to return `null` if Analytics is still gathering data.

### Test Coverage

* N/A

## QA Brief
* Create a new jurassic ninja site.
* Install the plugin and connect it.
* Verify that the widgets on the admin bar (frontend) and the widgets on the main WP dashboard show zero states.
* Wait a few days and check again.
* Confirm that now widgets don't display zero states, but charts with zeros.

## Changelog entry

* Update WordPress dashboard widget and admin bar stats to display zero states for Search Console/Analytics only when the respective service is gathering data.

**Comment by asvinb** [comment]
@eugene-manuilov @felixarntz While working on this issue, I'am wondering whether we should rename `isGatheringData` to `hasGatheredData` because when I read `isGatheringData`, I thought it's still grabbing the data instead of already fetching the data. For e.g [reading those lines](https://github.com/google/site-kit-wp/blob/22ded8f56153d798dcceece328dfe1467b0fea0b/assets/js/modules/search-console/components/module/ModuleOverviewWidget/index.js#L112-L118), without any context made me believe that we are testing if the report has returned 0 data and is still gathering data at the same time which sounded weird to me. I think renaming it to `hasGatheredData` is a better representation of what the selector is actually doing. For e.g:
`if ( hasGatheredData && isZeroReport( data ) ) {`
reads better IMHO.

Let me know what you think.

**Comment by felixarntz** [comment]
@asvinb I see some of the confusion you're mentioning, however I don't think that `hasGatheredData` makes the name more accurate. The selector returns `true` when the service behind the API is _overall_ still "gathering data". `hasGatheredData` would imply to me that the service already has data, which would mean the opposite of what it does now. `isGatheringData` is technically accurate, however it needs to be read as "is gathering data overall" instead of "is gathering data right now" or "is gathering data for this request".

Again though, I see the confusion here, so maybe we can find a better name. Other ideas @eugene-manuilov @tofumatt @aaemnnosttv?

**Comment by aaemnnosttv** [comment]
@felixarntz maybe something like `hasAnyData` would be less open to misinterpretation? If there is any data then it is no longer waiting to being gathered. To me I think this would be more clear that a request is no longer in progress, but even if other requests were still in progress this would return true as soon as any report returns data.

**Comment by felixarntz** [comment]
@aaemnnosttv Hmmm 🤔  `hasAnyData` sounds very much like the opposite of `hasZeroData` - which makes sense, but we now use `hasZeroData` for an individual report. We could argue that maybe a parameter-less call to `isZeroData` could replace `isGatheringData`, but I wouldn't like overloading that selector with two behaviors.

Still not convinced. Since this is a naming discussion we can't seem to find a better name for right now, I'd say let's not block this issue and proceed with `isGatheringData` for now. @asvinb Maybe add a `TODO` comment regarding finding a better name for this selector above where it is defined in each store?

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- The WP dashboard widget shows zeros for Search Console impressions and clicks respectively.   
- The WP dashboard widget shows zeros for Analytics visitors and avg. time on page respectively.
- The WP dashboard widget does not display the popular pages table at all if its Analytics report is only 0s
- Confirmed that the units are included, i.e. "Avg. time on page" says "0s" and not just "0".
- Checked the widget on desktop and small screen sizes.

![image](https://user-images.githubusercontent.com/73545194/141308192-62dad27c-3b5b-4687-9df5-30e6315163df.png)

- The WP admin bar UI shows zeros for Search Console impressions and clicks respectively.
- The WP admin bar UI shows zeros for Analytics visitors and sessions respectively.

Note: To test this ticket I used a site that had Search Console and Analytics set up a few days ago.  
I also set up a new site and can confirm that the zeros do not appear straight away.  The gathering data messages appear when the modules are connected.
