### ISSUE TITLE
Add Link on Idea Hub Setup CTA to jump to the widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4275]
## Bug Description

When a user connects Idea Hub it is not obvious where the Idea hub widget is.  

When a user connects PageSpeed, there's a link in the Setup CTA, so the user can jump down to the widget and wondered if it was worth having something similar for Idea Hub?

https://app.asana.com/0/1200491083500938/1200758733177807

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the module setup success notification for the `idea-hub` module specifically, a message link that points the user to the Idea Hub widget (i.e. anchor link to the widget) should be displayed, similarly to how it is done for the `pagespeed-insights` module.
* The message copy should be: _Jump directly to Idea Hub to see topic suggestions for your site_

## Implementation Brief

In `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`:

* Add an id to the `div` with the class name `googlesitekit-idea-hub`. It will be used as the jump anchor link.

In `assets/js/components/notifications/SetupSuccessBannerNotification.js`: 

*  Define `anchor` object with the properties `link` and `label` which are initially empty strings. 
    *  if the `slug` is `pagespeed-insights`, then the value of `link` and `label` should be the current ones used further down the file. See: 
        * https://github.com/google/site-kit-wp/blob/4fcb58149ce46d346bed4ced38124d13bfe92025/assets/js/components/notifications/SetupSuccessBannerNotification.js#L182-L194
    * otherwise, if the `slug` is `idea-hub`, 
            * The `link` should be the `id` that was added in the `SetupSuccessBannerNotification` component in the previous step prepended by a `#`. ie. `#idea-hub-jump-anchor`. 
            * The `label` should be the i18n'd string text from AC.
* In the following BannerNotification component, pass `anchor.link` and `anchor.label` as the prop value of `anchorLink` and `anchorLinkLabel` respectively.

### Test Coverage

* N/A

## QA Brief

* Activate Idea Hub on your site.
* On the `Congrats on completing the setup ...` notification, press the link on the the `Jump directly to...`.
* Ensure you are on the `idea-hub` section of the dashboard.
 
## Changelog entry

* Add a link to the Idea Hub CTA to jump to the Idea Hub widget.

**Comment by eugene-manuilov** [comment]
> ... create a object anchor using the useMemo hook that does the following:

@kuasha420 why do we need to use the `useMemo` hook here? It seems to me that there is no need in it. Let's define that object directly in the component.

**Comment by kuasha420** [comment]
@eugene-manuilov updated the IB, pardon me for this style of code and suggestions as I am too used to less/non-mutating TypeScript code. IB Updated.

**Comment by eugene-manuilov** [comment]
No worries, @kuasha420. IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@ivankruchkoff when I click on the `Jump directly to Idea Hub to see topic suggestions for your site` link it does not take me to the top of the Idea hub widget.  I checked this on current and unified dashboard. 

![image](https://user-images.githubusercontent.com/73545194/143464964-b450ebd2-6aa1-4acd-b2c5-8921446e7b79.png)

**Comment by ivankruchkoff** [comment]
@wpdarren yes, it seems that the it doesn't work based on the IB as implemented. I tried the same thing with page speed insights and the behaviour is the same when the data is loaded, see the recording:

https://user-images.githubusercontent.com/373931/143512391-a7d40b7f-8472-4d07-a019-e5563e0aaba4.mp4

**Comment by ivankruchkoff** [comment]
The approach in the IB won't work, I've added a screenshot to demonstrate, in this case it's unified dashboard + psi module.

```
document.getElementById('wpadminbar').style.opacity = '0.4';
document.querySelector('header').style.opacity = '0.4';
```

Browser scrolls to the element, but it's hidden by the google header and the wp header, so we either need to change approach to account for the height of these two elements, or come up with another approach.

<img width="1440" alt="Screen Shot 2021-11-25 at 5 28 59 PM" src="https://user-images.githubusercontent.com/373931/143513780-a89b6d87-4df8-4030-b23e-955aaceddc64.png">

**Comment by eugene-manuilov** [comment]
> ... when I click on the `Jump directly to Idea Hub to see topic suggestions for your site` link it does not take me to the top of the Idea hub widget. I checked this on current and unified dashboard.

@wpdarren that is a problem that requires reworking of the anchor link in the banner. Unfortunately, this is out-of-scope for this ticket, but we definitely need to solve this issue. Could you please create a new ticket for this issue?

For this ticket, all we need to check is that you get to the Idea Hub widget when you click on the jump link, although this is not the best UX at the moment.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

On the `Congrats on completing the setup` notification, when I press the link on the the `Jump directly to....` you are taken to the Idea hub widget on the dashboard. (including the unified dashboard) As reported above, you are not taken to the top of the widget, which is not good UX. I will create a separate ticket because this is outside of the scope of this ticket..

![image](https://user-images.githubusercontent.com/73545194/143464964-b450ebd2-6aa1-4acd-b2c5-8921446e7b79.png)
