### ISSUE TITLE
Idea Hub: Change copy on Drafts tab when no drafts created

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4276]
## Bug Description

On Idea Hub widget, on the Drafts tab. When no drafts are created the copy could be improved.

Currently, it reads: `Ideas will appear here by starting a draft from the New or Saved tab`
But it should be changed to `Ideas will appear here by starting a draft from the New or Saved tabs`

https://app.asana.com/0/1200491083500938/1200709616112965

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy in the Idea Hub widget that says `Ideas will appear here by starting a draft from the New or Saved tab` should be changed to `Ideas will appear here by starting a draft from the New or Saved tabs` ("tabs" as plural).

## Implementation Brief
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/DraftIdeas.js`, update the copy as per the AC, i.e "tabs" as plural.

### Test Coverage

* N/A

## QA Brief

* Open the Idea Hub modules.
* Make sure no draft was created in order to visualize the copy text.
* Observe the text value follows the specified IB and the word `tab` is now pluralized as `tabs`

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark: 

Note: I have bumped the estimate from `1` to `3`.

**Comment by eugene-manuilov** [comment]
@mitogh could you please add QAB?

**Comment by mitogh** [comment]
QAB :heavy_check_mark:  @eugene-manuilov  thanks.
