### ISSUE TITLE
Idea Hub: Introduce Tooltip on Connect More Services Page

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4278]
## Bug Description

For Idea Hub, in Figma, we have a tooltip on the Connect More Services page with the title 'New Feature' however when you visit this page in the plugin, no tooltip exists.  Creating this ticket so we do not forget about this functionality. 

https://app.asana.com/0/1200491083500938/1200756726857970/f

![image](https://user-images.githubusercontent.com/73545194/138905427-80a56d89-0b8e-4cd5-bb07-bb3e7461d219.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren ! After discussing with @felixarntz and @marrrmarrr we decided not to add this tour for Idea Hub.
