### ISSUE TITLE
Learn More Link on Link Analytics and AdSense CTA opens in same window

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4286]
## Bug Description

On the `Link Analytics and AdSense` CTA, there's a `Learn more` link and it currently opens the page in the same window rather than opening a new one like our other CTAs.  

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/f3a7da5a-2752-4cc7-88b2-d08549c4ae41)

## Steps to reproduce

1. Connect `AdSense` but do not link Analytics.
2. Go to `Site Kit Dashboard` and scroll down to `Earnings` widget.
3. See the CTA `Link Analytics and AdSense`
4. Click on the `Learn more` link and see behaviour.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Learn more link on the CTA to link AdSense and Analytics should open in a separate window/tab, like other "Learn more" links.

## Implementation Brief

* Add the `ctaLinkExternal` prop to the `CTA` component rendered in `AdSenseLinkCTA`.
https://github.com/google/site-kit-wp/blob/1be77237454c18764f51aee4935f4dfac8232e12/assets/js/modules/analytics/components/common/AdSenseLinkCTA.js#L40-L48

### Test Coverage

* No new tests needed.
* Existing tests should pass.

## QA Brief

1. Connect `AdSense` but do not link Analytics.
2. Go to `Site Kit Dashboard` and scroll down to `Earnings` widget.
4. Click on the `Learn more` link and observe the link now it opens in a separate window.

## Changelog entry

* Update the "Learn More" links of Analytics and AdSense CTAs to open in a new window.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified: when you click on the Learn more link, it opens in a separate window.
