### ISSUE TITLE
Invalid/non existent URL on Entity Dashboard

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#4287]
## Bug Description
If we go to the EntityPage with a non existent URL with the `unifiedDashboard` feature flag enabled, there is no error message saying that the URL does not form part of the site, similar to what is displayed when the feature flag is not enabled.

## Steps to reproduce

1. Go to the main dashboard with the `unifiedDashboard` feature flag disabled.
2. Use the "Search for individual page or post information" widget to search for a page/post within the site and click on the "View Data" button.
3. The user will be redirected to the entity dashboard, with the `permaLink` URL parameter set.
4. Change the `permaLink` path to something which does not exist. For e.g if `permaLink` was `http://my-site.com/features`, update it to `http://my-site.com/featuressss`
5. Notice the error message.
6. Enable the `unifiedDashboard` feature flag, and go the the entity dashboard where `permaLink` is incorrect.
7. There is no error message and data  of the main site is displayed.

## Screenshots
Error message when `unifiedDashboard` feature flag is disabled which should appear when the `unifiedDashboard` feature flag is enabled.
![image](https://user-images.githubusercontent.com/31818/139104113-71da1ac6-ab44-405b-8ef6-6953858c60ee.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When accessing an "Entity Dashboard" page with an invalid permalink, an error should be displayed, similar to the one displayed in the non-unified dashboard at https://github.com/google/site-kit-wp/blob/ab909c7b9f60dbf9a972688ede31cd238542cdb5/assets/js/components/dashboard-details/DashboardDetailsHeader.js#L98
    * Note that the style of the error in this component is the reference, but the content should be updated to whatever is in the AC of #4097. See my note in the code review for that issue—we should ensure the "website" link is accessible with extra, screen-reader context: https://github.com/google/site-kit-wp/pull/4351#discussion_r749732012. That copy should be: _ It looks like the URL xyz is not part of this site or is not based on standard WordPress content types, therefore there is no data available to display. Visit our <a>support forums</a> or <a><VisuallyHidden>Site Kit </VisuallyHidden>website</a> for support or further information_
    * The "support forums" bit should link to the [support forums](https://wordpress.org/support/plugin/google-site-kit/), and the "Site Kit website" bit should link to the [Site Kit website](https://sitekit.withgoogle.com/).
* We don't have any mockups/Figma files for this error state, but showing this error in the dashboard content area would make sense, with the same text as we show now (see the mockup above).
* The existing dashboard contexts should _not_ be shown, but this shouldn't require implementing infrastructure to hide all widget contexts. Essentially: we shouldn't render any of the widget contexts if the permalink isn't valid, so my instinct would be to, in https://github.com/google/site-kit-wp/blob/ab909c7b9f60dbf9a972688ede31cd238542cdb5/assets/js/components/DashboardEntityApp.js#L47, check to see if the permalink is valid. If it isn't: hide the widget area contexts. Until we've verified the permalink is invalid, it's fine to show the widget contexts to prevent weird jumping UIs during loading for the "common case". But once an invalid `permaLink` is detected, we should hide the contexts and show an error message (maybe with a link to the main dashboard).

## Implementation Brief

In `DashboardEntityApp` component, 

* get `currentEntityURL` and `permaLink` from the `CORE_SITE` using `getCurrentEntityURL` and `getPermaLinkParam` selector. 
* if `currentEntityURL` is not `null`, render the `WidgetContextRenderer` elements as normal. 
* Otherwise, render the Copy from the AC. 

## QA Brief

1. Go to the main dashboard with the `unifiedDashboard` feature flag enabled.
2. Use the "Search for individual page or post information" widget to search for a page/post within the site and click on the "View Data" button.
3. The user will be redirected to the entity dashboard, with the `permaLink` URL parameter set.
4. Change the `permaLink` path to something which does not exist. For e.g if `permaLink` was `http://my-site.com/features`, update it to `http://my-site.com/featuressss`
5. An error message informing the user that this page doesn't exist should appear.

## Changelog entry

* Add an error message for unknown pages to the Unified Dashboard.

**Comment by kuasha420** [comment]
@tofumatt sending this one to you for IBR. Also I think we should update the AC to account for the new wording introduced [here](https://github.com/google/site-kit-wp/issues/4097), is that correct? If yes, can you update the AC to mention that so there's no confusion? 

Cheers.

**Comment by tofumatt** [comment]
@kuasha420 Sounds good, great catch!

I've updated the ACs here and referenced my code review comment on the related issue regarding an accessibility tweak.

IB ✅

**Comment by kuasha420** [comment]
Not sure that happened to the estimate on this one as I remember setting a `7`  for this one. Setting estimate again.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- An error message informing the user that this page doesn't exist appears.
- Checked that no widgets appear on the page as per the AC. 

![image](https://user-images.githubusercontent.com/73545194/143006919-77e53041-5147-40b9-aceb-adff59704234.png)

**QA Note:** the URL currently goes to the Site Kit website but that will be changed with #4097. There's also no period after the sentence, but have brought that up in the same ticket. Will check that it is updated when QAing that ticket.
