### ISSUE TITLE
Allow widget contexts to have specific ID attributes (as anchors)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4288]
Since the new pill navigation in the unified dashboard needs to link to specific widget contexts (with anchor links, see #4053), widget contexts now need the ability to have ID attributes that can be linked to.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `WidgetContextRenderer` should receive support for a new optional `id` prop. If passed, it should add its value as the `id` attribute on the wrapping `.googlesitekit-widget-context` container.
* The `DashboardMainApp` and `DashboardEntityApp` should both pass `id` props to all of its `WidgetContextRenderer`s. The exact values should be (per the respective contexts):
    * `traffic`
    * `content`
    * `speed`
    * `monetization`
    * Note that both components can use the same IDs here, since they will never be rendered together.
    * Constants should be used for these values, which should also be leveraged by the pill navigation from #4053.

## Implementation Brief

* In `assets/js/googlesitekit/widgets/components/WidgetContextRenderer.js`, 
    * take a new prop `id`.
    * pass it as `id` prop of the `div` element with the className `googlesitekit-widget-context`.
    * Fix the component name in the file header comment ( `WidgetContext` ->`WidgetContextRenderer`).
* In `assets/js/googlesitekit/constants.js`,
    * Define and export the constants for the Anchor ID's from the AC. 
        * Use something like `ANCHOR_ID_TRAFFIC` for 'traffic' etc. 
        * No need to define them separately for `Main` and `Entity` dashboard as they are same as per AC.
* In `assets/js/components/DashboardMainApp.js` and `assets/js/components/DashboardEntityApp.js`,
    * Import the newly added constants and add them as `id` props to the respective `WidgetContextRenderer` components. 

### Test Coverage

* No new tests needed.

## QA Brief

* Enable Unified Dashboard. 
* Visit Main Dashboard. 
* Append the anchor links mentioned to the URL after a `#` and see the UI jumps to the section. 
* Do the same for Entity Dashboard. 
* Example: http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-dashboard#speed

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅
