### ISSUE TITLE
Ensure pills for widget contexts that are empty/inactive are not displayed

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4289]
#4053 introduced a pill navigation for the unified dashboard that points to individual widget context "section" with anchor links. Per #4136, widget contexts can contextually be empty ("inactive") though, and in that case the respective pill should not be displayed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The pill navigation introduced in #4053 should be updated as follows: For each of the pills, it should be checked whether the respective widget context is active, using the `isWidgetContextActive` selector from #4136. If it is not active, the pill should be skipped/not rendered.
    * For that purpose, each pill needs to be associated with the respective widget context (see `default-contexts.js`).
    * When on the main dashboard, the contexts should be the respective `CONTEXT_MAIN_DASHBOARD_*`.
    * When on the entity dashboard, the contexts should be the respective `CONTEXT_ENTITY_DASHBOARD_*`.

## Implementation Brief
* Using `assets/js/component/DashboardNavigation`,
	* use the `useDashboardType` hook to check whether we are on the main dashboard or entity dashboard.
	* import the `CONTEXT_MAIN_DASHBOARD_*` and `CONTEXT_ENTITY_DASHBOARD_*` constants from `assets/js/googlesitekit/widgets/default-contexts.js`
	* Based on the dashboard type, from the result of `useDashboardType`, query the `core/widgets` data store via the `isWidgetContextActive` selector, passing either the `CONTEXT_MAIN_DASHBOARD_*` or `CONTEXT_ENTITY_DASHBOARD_*` constant for every pill. Note that every pill is associated with the appropriate context. For e.g `CONTEXT_MAIN_DASHBOARD_TRAFFIC` and `CONTEXT_ENTITY_DASHBOARD_TRAFFIC` are associate to the `Traffic` tab.
	* Render the pill only if its appropriate context is active.

### Test Coverage
* No new tests to be added.

## QA Brief

* Enable unifiedDashboard feature flag.
* Make sure Adsense Module is not connected.
* In Main Dashboard, you should not see the Monetization Chip
* Connect Adsense Module. 
* The Monetization Chip Should be visible now.

## Changelog entry

* Update dashboard navigation to hide navigation chips for empty areas.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by eugene-manuilov** [comment]
@kuasha420 could you please add QAB?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When Adsense Module is not connected, the Monetization Chip does not appear on the unified dashboard. 

![image](https://user-images.githubusercontent.com/73545194/143072473-b0cf4165-11c1-4fb7-8ef7-9abc699ddb36.png)

- When Adsense Module is connected, the Monetization Chip is visible now.

![image](https://user-images.githubusercontent.com/73545194/143072515-5ba81e80-9f44-4543-ac32-b630ccbd9918.png)

- I also repeated the same process for PageSpeed Insights. 
- Checked the behaviour was the same on small screen sizes.
