### ISSUE TITLE
Individual page search by URL or title with non-primitive chars not working

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#431]
## Bug Description

When pasting a URL into the single page search box on the main dashboard, the plugin shows "No Results"
(related to issue #369 )

## Steps to reproduce

1. Go to plugin main dashboard
2. Paste an existing page URL into the Single page search box
3. Search box shows "no results"

## Screenshots

![single-page-no-results](https://user-images.githubusercontent.com/13304791/63520186-9016fa00-c4f4-11e9-9020-d0de1f89a4c3.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Searching for a post's title should work regardless of whether the title typed in the searchbar contains spaces, accents or any other kind of special character.
    * This should especially be tested with pasting entire titles into the search bar, e.g. titles with specific apostrophes or accent characters.
* When a user pastes a URL:
    * if the URL exists and we have stats for it, show individual page report with stats 
    * if the URL doesn't exist on the site, show "no results found"

## Implementation Brief

The search is failing for any non-primitive query due to the query being URL encoded before sending, but the value is not decoded on the server side before using.

https://github.com/google/site-kit-wp/blob/b225df85d49c114e161591c91bbdb6a3c8015995/includes/Core/REST_API/REST_Routes.php#L567-L570

* Decode the `query` request parameter before using it   
```php
$post_id = false;
$query = rawurldecode( $request['query'] );
```  
* Update references to `$request['query']` beyond this point to use `$query`
* If `$query` is a URL, search/replace it to convert the query URL to a local URL
    * Search `trailingslashit( $this->get_reference_site_url() )`
    * Replace `trailingslashit( home_url() )`
    * If the two are the same then this operation is a no-op so no additional check is necessary beforehand

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv IB looks good. One additional piece that we should cover is supporting URLs for when you're using a custom site URL (e.g. for local development).

To clarify by example:
* I'm on `https://my-site.local`, and I have filtered in a live site URL `https://my-site.com`.
* I have a database clone of the live site on my local site (with home URL replaced of course).
* I take a URL from the live site and paste it to my local site's Site Kit dashboard.
* Site Kit should find the corresponding post (of course that would only work when you _do_ have a live database clone).

This was not clearly stated in the ACs, but should be covered too. We could either use the `url_to_postid` filter, or specifically do the replacement in the search REST route. That only needs to happen if `Context::get_reference_site_url()` is different from `home_url()`.

**Comment by aaemnnosttv** [comment]
@felixarntz IB updated with this additional case handling.

**Comment by felixarntz** [comment]
IB ✅

**Comment by lucymtc** [comment]
QA looks good. 

Tested pasting existing and non existing URL.
Tested with steps to reproduce from #369 
Both URL and title search work as expected according to acceptance criteria.

**Comment by marrrmarrr** [comment]
LGTM.
