### ISSUE TITLE
'Let Site Kit place code on your site' toggle button defaulting to No when snippet already placed

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#4313]
## Bug Description

When connecting the Tag Manager module via Site Kit to a site that already has manually placed Tag Manager snippets the '**Let Site Kit place code on your site**' toggle button on the edit settings section defaults to **No** even if Site Kit has inserted the snippet. 

This could confuse the user and doesn't represent the fact that the snippet is already placed on the site.

## Steps to reproduce

1. Before connecting the Tag Manager module via Site Kit, manually place Tag Manager <head> and <body> snippets to your site.
2. Connect the Tag Manger module using the same GTM container code.
3. From Site Kit settings go to the Tag Manger section and check if snippet is inserted. If not edit and mark the toggle button to place the snippet and confirm changes.
4. Once snippet is marked as inserted then go into the edit settings once more.

## Screenshots

![SK-TM-Snippet-Inserted-Toggle](https://user-images.githubusercontent.com/91896826/140307989-bf200556-58a8-409f-8295-495476e63816.gif)

## Additional Context

This only occurs when GTM snippets have also been manually placed on the site. If manual snippets have not been inserted then the toggle will show as **yes** when going into the edit settings. 

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
The setting here (as in all modules) is specifically about whether or not Site Kit is responsible for placing the snippet. In this instance, the tag/snippet is already placed manually as you said so Site Kit detects this and proactively disables its own snippet to avoid double-tagging, which is important, particularly for Analytics. So this is intentional, but I agree this could be indicated a bit more clearly to differentiate between snippet or no snippet, and whether or not Site Kit is placing it or not.

**Comment by adamdunnage** [comment]
@aaemnnosttv Yes the specific issue here I am referring to is the fact that the toggle button reverts back to switched off even if it has been manually switched on and settings saved. And as you can see from the GIF I had switched this on manually to place the SK snippet which shows the 'Snippet is inserted' message but when editing that toggle is defaulting to switched off because of the function to recognise and remove the snippet due to the manually placed one I presume. But that doesn't actually reflect the toggles true current value.

**Comment by aaemnnosttv** [comment]
@felixarntz is this still relevant with the current changes in the ETS branch?

**Comment by aaemnnosttv** [comment]
Closing as this is no longer relevant in the context of the existing changes that have already been implemented in the epic.
