### ISSUE TITLE
Avoid `--undefined` in CSS class on inactive widget area

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4329]
## Bug Description

It's currently possible for an empty widget area to have an `--undefined` affix in its CSS class names, for example when opening the **current** entity dashboard with Analytics inactive which will lead to an inactive `pageDashboardAllTraffic` widget area. In there it has `googlesitekit-widget-area--undefined` in place of where it should have `googlesitekit-widget-area--boxes`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Inactive widget areas shouldn't have a `googlesitekit-widget-area--undefined` class on them.
    * Preferably they should still have the appropriate widget area style class on them (`--boxes` or `--composite` suffix).

## Implementation Brief

The problem here is the `style` variable defined on line 134 is being used on line 125, before it's defined. 
https://github.com/google/site-kit-wp/blob/42aec9873d8bf57df2da3be964ae9596f9d29b10/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L118-L134

* Within `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js`, move the relevant variable definition(s) above the conditional block where `style` is being used (i.e. move line 134 above line 118).
* Additionally, update the `classnames` usage to load class names for `slug` and `style` versions only if the appropriate values are not empty:
```js
classnames( 
	HIDDEN_CLASS, 
 	'googlesitekit-widget-area',
 	{
 		`googlesitekit-widget-area--${ slug }`: !! slug, 
 		`googlesitekit-widget-area--${ style }`: !! style,
 	}
)
```

Note: This bug could have been caught by ESLint, so I've created an issue to add the `no-use-before-define` rule to our ESLint config: https://github.com/google/site-kit-wp/issues/4361

### Test Coverage

* Add a snapshot test to the expectations for the test `should render a hidden widget area when it has no active widget` in `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.test.js`.

## QA Brief

* Make sure Analytics is disconnected/inactive. Now load the SiteKit Dashboard. 
* Using any browser's developer tools, on the Elements tab, find/search for `googlesitekit-widget-area--undefined`. There should be a couple of elements with that class. 
* Now switch to the bug-fix branch and repeat the above. There should be no elements with the `googlesitekit-widget-area--undefined` class. The same classes should have the `--boxes` class as per the AC.

## Changelog entry

* Fix the incorrect CSS class issue in the widget area renderer component.

**Comment by yusiflinurlan** [comment]
@felixarntz Hello ! Can you please assign this issue to me?

**Comment by felixarntz** [comment]
@yusiflinurlan Looks like @shayannosrat is already working on a PR. If you have another idea for the solution, feel free to open a PR yourself.

**Comment by techanvil** [comment]
@felixarntz does this still need fleshing out with an IB if we've got work in progress on it?

**Comment by felixarntz** [comment]
@techanvil So far the PR doesn't have the right solution, so I'd say we can proceed with an IB.

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil. This looks good. Let's also add a point to IB to update the `classnames` usage to load class names for `slug` and `style` versions only if the appropriate values are not empty:

```js
classnames( 
	HIDDEN_CLASS, 
 	'googlesitekit-widget-area',
 	{
 		`googlesitekit-widget-area--${ slug }`: !! slug, 
 		`googlesitekit-widget-area--${ style }`: !! style,
 	}
)
```

**Comment by techanvil** [comment]
Thanks @eugene-manuilov, sounds good and I've made the change :+1:

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil. Looks good to me. Could you please add an estimate too?

**Comment by techanvil** [comment]
@eugene-manuilov apologies, I completely forgot. Thanks for the heads up! I've now added an estimate. :+1:

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil. IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update: ✅ 

**Verified:** 

- Now when services are disconnected/inactive then there will be no elements with `googlesitekit-widget-area--undefined` class. Same class has `--boxes` class at the place of -`-undefined` as per the AC.
- Also,tested this with Unified Dashboard.



https://user-images.githubusercontent.com/94359491/145576547-6a9a5de0-3e2d-41b4-a734-775811c937e6.mp4
