### ISSUE TITLE
Improve Placement of Entity Search Loading Indicator on Unified Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4336]
## Bug Description

While testing #4049 I do not feel the loading indicator is placed in an area that's obvious for the user, at the far end of the input field, underneath the close X icon. It took a few searches on desktop before noticing it. It's more prominent on mobile and tablet devices. 

I feel it needs to be more prominent within the search box.  

## Steps to reproduce

1. Connect Site Kit 
2. Activate `unifiedDashboard` user the tester plugin
3. Go to Site Kit dashboard and use the Entity search

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The loading indicator / small progress bar for the `unifiedDashboard` search field should be updated to follow [this Figma design](https://www.figma.com/file/kKYqiUL7Fj3yAF8HHBRUhz/Custom-Dashboard?node-id=3049%3A39706), i.e. it should appear as a thin progress bar "line" above the dropdown (instead of the short line under the icon on the right like it is now).

## Implementation Brief
* Using `assets/js/components/EntitySearchInput.js`,
	* Remove the `small` prop for `ProgressBar`
* Using `assets/sass/components/global/_googlesitekit-entity-search.scss`,
	* Update the styles for `.googlesitekit-entity-search__loading`,
		* Set `right` to `0`
		* Set `bottom` to `-6px`
		* Set the border radius to `4px` across all breakpoints

### Test Coverage
* No new tests to be added.

## QA Brief

* Follow steps 1-3 in **Steps to reproduce**.
* Verify the loading indicator follows the design as per the AC.
* Check it displays correctly at different breakpoints.

Note: The loading indicator can be made to stay on the screen longer by popping open the devtools Network tab and throttling the connection, e.g. to Slow 3G. First type a query in to get the search results dropdown up and then throttle the connection or you'll be waiting a relatively long time for the initial dropdown to appear, though.
![image](https://user-images.githubusercontent.com/18395600/143226634-3d9cc06f-096c-491e-83cc-d8b1268623bd.png)

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@FlicHollis This is also a good candidate for Sprint 63.

**Comment by eugene-manuilov** [comment]
> Using `assets/sass/components/global/_googlesitekit-entity-search.scss`,
> * Update the styles for `.googlesitekit-entity-search__loading`,
>   * Set `bottom` to `-6px`

@asvinb AC says that "_as a thin progress bar "line" **above** the dropdown_". Should we use the `top: -6px` property instead of `bottom: -6px`?

**Comment by asvinb** [comment]
> > Using `assets/sass/components/global/_googlesitekit-entity-search.scss`,
> > 
> > * Update the styles for `.googlesitekit-entity-search__loading`,
> >   
> >   * Set `bottom` to `-6px`
> 
> @asvinb AC says that "_as a thin progress bar "line" **above** the dropdown_". Should we use the `top: -6px` property instead of `bottom: -6px`?

@eugene-manuilov No. The progress bar is within the search input container, not within the dropdown (which in that case would make sense to use `top: -6px`. So we need to go further down the search container :)

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- The loading indicator / small progress bar for the unifiedDashboard search field follows the Figma design, i.e. it appears as a thin progress bar "line" above the dropdown.

https://user-images.githubusercontent.com/73545194/143253127-1b99c978-7f0c-4609-80f7-d7020b764dc3.mp4

**Note:** I observed odd behaviours with the entity search that I do not feel are part of this ticket, so will create a new one.
