### ISSUE TITLE
Point to correct service UI when Analytics is being configured as part of setup

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4342]
This ties into the changes from #4341, but is **not** technically blocked by it. The two issues complement each other. Here's what this is about: When Analytics is being set up as part of the overall setup flow, the proxy should show corresponding copy. There is already a distinct UI present in the proxy that can be triggered by the plugin on demand.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `mode=analytics-step` query parameter should be **conditionally** appended to the setup URL (see `Google_Proxy::setup_url()`) if the `serviceSetupV2` feature is enabled and the `analytics` module is **active but not connected**.

## Implementation Brief
* Using `includes/Modules/Analytics.php`,
	* Within the `register` function, add the `googlesitekit_proxy_setup_url_params` filter.
	* The callback function should check
		* if the `serviceSetupV2` is enabled by calling `Feature_Flags::enabled( 'serviceSetupV2' )`
		* whether `Analytics` module is not connected via the `is_connected` method.
		* if Analytics is not connected and `serviceSetupV2` is enabled, add the `mode` key with `analytics-step` as value in the returned array.

### Test Coverage
* Update tests for `setup_url` method to test for the URL parameter when `serviceSetupV2` feature flag is enabled and Analytics is not connected.

## QA Brief

* Reset the plugin.
* Enable the `serviceSetupV2` feature flag in the tester settings.
* Go to the dashboard page and select to set up the Analytics module during the site connection process.
* When redirected to the proxy page, check the URL in the browser and make sure that it contains the `mode=analytics-step` query argument.

## Changelog entry

* Include query parameter for custom Analytics step in the service setup flow URLs.

**Comment by eugene-manuilov** [comment]
> Instantiate a new Analytics object and then call the is_connected method.

@techanvil, instead of instantiating a new instance of the Analytics class, let's add a new hook for the `googlesitekit_proxy_setup_url_params` filter to the Analytics class itself to add the required parameter to the proxy setup URL query params.

**Comment by techanvil** [comment]
Hey @eugene-manuilov, thanks for the comment but it should have been directed at @asvinb as he worked on the IB - I only briefly assigned this to myself and didn't actually do the IB work.

**Comment by asvinb** [comment]
Sounds good @eugene-manuilov . Actually the AC mentions to check whether the module is active but not connected. I don't see any method which tells us whether a module is active but not connected. There's only the `is_connected` method 🤔

**Comment by eugene-manuilov** [comment]
> I don't see any method which tells us whether a module is active but not connected

@asvinb, if a module is active, then we call the register method of the module class. Thus if we add a hook to the register method of the Analytics class, then it will be executed only if the Analytics module is active.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by eugene-manuilov** [comment]
@felixarntz can you review #4411?

**Comment by felixarntz** [comment]
@eugene-manuilov Left feedback on the PR, can you also add a QAB please?

**Comment by eugene-manuilov** [comment]
@felixarntz QAB is added.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- With the `serviceSetupV2` feature flag enabled I verified when redirected to the proxy page, the URL in the browser and it contains the `mode=analytics-step` query argument.
