### ISSUE TITLE
"Top Earning Pages" and "Performance over the last 28 days" widgets not present on the Unified Dashboard.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#4348]
## Bug Description

The **Top Earning Pages** and **Performance over the last 28 days** widgets should be present on the Unified Dashboard, but in fact are not present.

## Steps to reproduce

1. Enable the `unifiedDashboard` feature flag.
2. Connect the AdSense and Analytics modules.
3. Navigate to the Dashboard and scroll to the bottom.
4. The **Top Earning Pages** and **Performance over the last 28 days** widgets are not present on the page.

#### Technical Analysis

The `DashboardTopEarningPagesWidget` and `ModuleOverviewWidget` widgets are being registered in the `AREA_MAIN_DASHBOARD_MONETIZATION_PRIMARY` area - but only when the `unifiedDashboard` feature is **disabled**. Conversely the `AREA_MAIN_DASHBOARD_MONETIZATION_PRIMARY` area is only registered / rendered when `unifiedDashboard` is **enabled**. The net result is those widgets don't appear on the Unified Dashboard.

The relevant code is here:
https://github.com/google/site-kit-wp/blob/1be77237454c18764f51aee4935f4dfac8232e12/assets/js/modules/adsense/index.js#L107-L146
https://github.com/google/site-kit-wp/blob/1be77237454c18764f51aee4935f4dfac8232e12/assets/js/googlesitekit/widgets/register-defaults.js#L192-L285
https://github.com/google/site-kit-wp/blob/1be77237454c18764f51aee4935f4dfac8232e12/assets/js/components/DashboardMainApp.js#L66-L69

The likely solution will be to register these widgets in the same way as the `AdBlockerWarningWidget`, as seen here:
https://github.com/google/site-kit-wp/blob/1be77237454c18764f51aee4935f4dfac8232e12/assets/js/modules/adsense/index.js#L101-L103

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense widgets "Performance over the last x days" and "Top Earning Pages" should be displayed in the "Monetization" section of the main dashboard when the `unifiedDashboard` feature flag is enabled.
    * This was originally part of #4080, but looks like it wasn't properly QAd there (that ticket has `QA: Eng` on it when it probably shouldn't have).

## Implementation Brief

As @eugene-manuilov has mentioned in [this comment](https://github.com/google/site-kit-wp/issues/4348#issuecomment-973164899), we don't actually need to check the `unifiedDashboard` feature flag in `assets/js/modules/adsense/index.js` at all. 

Therefore, within `assets/js/modules/adsense/index.js`:

* Remove the conditional checks for the `unifiedDashboard` feature flag.
* The `adBlockerWarning` widget should be registered for both `AREA_MAIN_DASHBOARD_MONETIZATION_PRIMARY` and `AREA_MODULE_ADSENSE_MAIN` contexts.

### Test Coverage

* No new tests needed. Existing tests should pass.

## QA Brief

* Enable the `unifiedDashboard` feature flag.
* Activate AdSense, then visit the main Site Kit dashboard. Scroll to the bottom of the page: you should see two AdSense widgets.
* Ensure the "Performance over the last 28 days" is above the "Top Earning Pages" widget.

## Changelog entry

* Fix missing monetization widgets on the Unified Dashboard issue.

**Comment by felixarntz** [comment]
@techanvil Thanks for catching that! I've added ACs to it.

@FlicHollis As discussed earlier today, let's fix this in Sprint 63.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by eugene-manuilov** [comment]
I think we don't need to check whether the `unifiedDashboard` feature flag is enabled for widgets and widget areas in the `adsense/index.js` file at all because we never render contexts and areas for the current and unified dashboards together. So we can just add both areas (for unified and the current dashboards) to widgets and keep using the `CONTEXT_MODULE_ADSENSE` context for the `AREA_MODULE_ADSENSE_MAIN` area registration regardless of the `unifiedDashboard` feature flag.

@techanvil, could you please update IB to remove the feature flag check in that file and add both widget areas unconditionally for the `adBlockerWarning` widget?

**Comment by techanvil** [comment]
Thanks @eugene-manuilov, that's a good point. I've updated the IB accordingly.

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@tofumatt I do not see the `Top Earning Pages` on the dashboard with `unifiedDashboard` enabled. I checked and when it's disabled the widget does appear as expected. 

I tested this on two scenarios.  1) with a site only using Tester plugin and a site that has had its AdSense account approved but no ad impressions. I thought initially it might be related to the tester plugin but neither had the widget on the dashboard. 

**Verified:**

- The `Top content over the last 28 days` appears on the dashboard with `unifiedDashboard` enabled.

**Comment by felixarntz** [comment]
## Approval ❌ 

@tofumatt @eugene-manuilov I guess this wasn't explicitly mentioned in the ACs, but the order of the two widgets should be similar to today. The overall AdSense performance widget should be on top of the top earning pages widget. Can you open a follow-up PR for `main` to adjust the widget priorities accordingly?

**Comment by felixarntz** [comment]
### Approval ✅
