### ISSUE TITLE
Update ESLint to prevent backtick-quoted bare strings

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#4350]
## Feature Description

At present our linting will allow backtick-quoted bare strings, e.g.

```
`This is a string.` // No problem!
```

We should update ESLint to warn or error when using backticks for non-template strings.

The WordPress JavaScript coding standards specify that strings should use single quotation marks:

https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/

> WordPress uses single quotation marks for string declarations.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint configuration should be updated such that template literals are not allowed for simple strings by default. See https://eslint.org/docs/rules/quotes.html#allowtemplateliterals

```js
`foo` // this should raise an ESLint error
"foo" // so should this

'foo' // this is good ✅
`foo ${ bar }` // this is too ✅
```

## Implementation Brief

* In `.eslintrc.json`, remove `allowTemplateLiterals` option from the `quotes` rule.
* run `npm run lint:js` to detect all instances of incorrect backtick usage in our codebase and fix them.
    * Hint: most of them should be autofixable using `npx eslint '**/*.js' --fix`

### Test Coverage

* No changes needed.

## QA Brief

* Incorrect string examples from AC should be caught on the following:
    * VSCode(or other) intellisense 
    * Lint-Staged (When trying to commit incorrect strings.
    * `npm run lint:js`

## Changelog entry

* N/A

**Comment by eclarke1** [comment]
@kuasha420 could you kindly add an estimate here please, thank you

**Comment by kuasha420** [comment]
@eclarke1 oops, added.

**Comment by eugene-manuilov** [comment]
IB ✔️ 

> Hint: most of them should be autofixable using `npx eslint '**/*.js' --fix

@kuasha420, we have the `lint:js-fix` command to fix eslint issues 😄, so you can run `npm run lint:js-fix` and it will fix all errors that it can.

**Comment by kuasha420** [comment]
@eugene-manuilov funnily enough, that comment does not fix this issue for some reason, @aaemnnosttv and I hypothesized in our 1:1 that `wp-scripts format-js` only fixes prettier problems, but not eslint ones.

**Comment by eugene-manuilov** [comment]
Hm... okay, thanks, for letting me know. I thought it would have fixed all errors 😄

**Comment by jimmymadon** [comment]
@techanvil @eugene-manuilov I also noticed WP Coding Standards tell us to [escape single quotes in strings](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#:~:text=//%20Escape%20single%20quotes%20within%20strings%3A). So can I modify the AC to enforce this and change the IB of this story to further remove the `avoidEscape: true` from the `quotes` rule?

**Comment by asvinb** [comment]
### QA: ✅ 

ESLint complaining in different scenarios:
![image](https://user-images.githubusercontent.com/31818/145228666-3d6a5910-ac66-4065-a2ad-59f9fd8ffebe.png)
![image](https://user-images.githubusercontent.com/31818/145228843-974e7723-5a7a-4792-a4fb-d29ec53bd208.png)

ESLint not complaining:
![image](https://user-images.githubusercontent.com/31818/145228957-f3433507-f31e-4556-87b7-5da7096f4265.png)
![image](https://user-images.githubusercontent.com/31818/145229044-e323900f-dde2-48f9-b54f-a9629a3b865d.png)
