### ISSUE TITLE
AdSense account creation when the user has 2 Google accounts

### ISSUE THREAD

**Issue by henrywright** [google/site-kit-wp#4352]
## Bug Description

It is possible to have more than 1 Google account. For example: I have a personal Gmail account and a professional Workspace account.

Imagine this scenario:

 - google.com website signed in as user A
 - Site Kit on WordPress signed in as user B

If I attempt to create an AdSense account by clicking on the "Create AdSense Account" button, I get taken to the AdSense "Home" page on the Google website. In the top right corner of the page I can see I am signed in. The problem is, in Site Kit on my WordPress website, the user signed in is a different user.

## Steps to reproduce

1. Sign in to google.com with Google user A
2. In the same browser, sign in to WordPress with Google user B
3. Go to Site Kit > AdSense
4. Click on the Create AdSense Account button
5. You will be taken to google.com. Observe the account in the top right corner of the page
6. Note it can be different to the Site Kit user

## Additional Context

 - PHP Version: 7.4
 - OS: Linux
 - Browser: Chrome
 - Plugin Version: 1.45.0
 - Device: Chromebook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by henrywright** [comment]
If it helps, when I used the same Site Kit account to create and connect an Analytics account I didn't encounter this problem

**Comment by jamesozzie** [comment]
Hi @henrywright,

While different WordPress administrators can login and setup Site Kit the plugin can be connected to one AdSense account. While AdSense policy dictates that users can only have one AdSense account you can add users access to the Site Kit connected AdSense account. You'll find a support topic in the AdSense Help Center in relation to this below:
https://support.google.com/adsense/answer/2659101?hl=en

In your example if you have more than one Google account, one being a Google Workspace account, you can grant access to the Google Workspace account if your AdSense account is associated with your non Google Workspace account. That way you can sign in and setup Site Kit from either account, while also connecting the AdSense module without issue. 

The product experts at the [AdSense Help Center](https://support.google.com/adsense/?hl=en#topic=3373519) should also be able to assist with further questions when it comes to accounts and permissions within AdSense. 

I'll close this GitHub issue now as the plugin is working as expected when it comes to AdSense setup. If however you're redirected to an incorrect AdSense account during setup please check this from a Chrome browser incognito window. It may be a case you have multiple Google accounts which you were previously signed into before Site Kit setup. 

Let me know if you have any questions with the above.

**Comment by henrywright** [comment]
Hi @jamesozzie 

Thanks for your reply. I don't want to grant access to my Workspace account. Instead, this issue relates to the account creation process being interrupted because a different account is signed in.

When I attempt to create an AdSense account using Site Kit, I expect the process to use the account signed in on Site Kit, not the account signed in on google.com

**Comment by jamesozzie** [comment]
@henrywright When you're directed to AdSense from a Chrome browser [incognito window](https://i.imgur.com/ALzgiHp.png) you should be asked to sign in with your Google account. The Google account that is displayed after logging in should match the email you used to login - the same once which you've used to setup Site Kit. 

If you're is not displaying the same email which you've used to login with (which I assume is the same email you've used to setup Site Kit) then feel free to provide a screen recording if you wish. While it doesn't sound Site Kit related if this occurs within the AdSense platform I'd certainly be happy to take a look. You can use a service such as [Loom](https://www.loom.com) or [RecordIt](https://recordit.co/) to share a recording. If you'd like to share privately you can use our [Site Health information submission form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) however you'd need to [create a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) first. This is used to associate the form with a users support topic and a requirement for the form submission.

**Comment by henrywright** [comment]
@jamesozzie please see this screen recording I made. The Site Kit account is peterjimwright@gmail.com and the account on google.com is henry@lsquo.com

https://imgur.com/a/51zLgjC

**Comment by henrywright** [comment]
Sure

1. This video wasn't taken using Incognito
2. I have an existing AdSense account. This is the account signed in on google.com. That AdSense account isn't approved but that isn't really relevant because I don't want that account to be associated with Site Kit. The only reason it appears on when you are taken to google.com is it happens to be signed in

**Comment by jamesozzie** [comment]
Thanks for the update. I've performed some checks on this today and the behavior seems normal. Here is what I've been testing, with the below behavior expected:
- **From an incognito window** when connecting AdSense it will ask you to create an AdSense account - if one exists for the Google account you've used to connect AdSense. If you already have an AdSense account the plugin won't direct users to AdSense, instead it will submit that new site to be approved. 
- **From a regular browsing session** if you're already logged into your AdSense account from another tab of if you're logged into a different Google account using the browser profile after clicking on "_Create AdSense account_" within Site Kit it will switch to that existing AdSense account. Instead of creating an account it will prompt you to add the site to your existing AdSense account (if the site wasn't previously added) or show you the status of that site if it was added. 

So it looks like in order to get the experience you're looking for you'll need to not be logged into a Google account other than the once your using for Site Kit. Users should only have one AdSense account, which is likely why you're being directed to that existing google account. While I will take this up with the team and report back to you here I would expect this to be normal.

**Comment by henrywright** [comment]
Thanks for checking this @jamesozzie. 

To solve the problem I can easily log out of google.com and then the process to create an AdSense account using the Site Kit  plugin would use the account registered in Site Kit.

That said I can't ask users to use Incognito or have a single Google account or a single AdSense account. Hence the reason for this issue.

**Comment by henrywright** [comment]
@jamesozzie 

For the record, when I attempt to connect Tag Manager by going to Settings > Connect More Services, I get to choose the account to use on google.com. See

https://imgur.com/a/DQ2yJuE

**Comment by jamesozzie** [comment]
@henrywright Thanks for the update. I've noticed behavior similar to this myself. For example if I'm logged into a Chrome browser using one Google profile not associated with the account I used to setup Site Kit. 

I've also done more checks now in preparation of asking the team and it seems more a case of logging into AdSense from multiple accounts, with the issue not specific to Site Kit. See below example:

https://i.imgur.com/1WN04wA.png

So overall the behavior does seem expected. If you're looking to setup an AdSense account from within Site Kit you shouldn't be logged into any Google profile different to the one used to setup Site Kit. Alternatively you can do so from a browser incognito window.

**Comment by henrywright** [comment]
Thanks @jamesozzie that does make sense. I'll mention this to users if they encounter the problem

**Comment by jamesozzie** [comment]
No problem. Great for us to have further clarity on this also should other users ask, so thank you!
