### ISSUE TITLE
Extend data registry to allow selecting from WP data

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4357]
## Feature Description

While Site Kit uses the same `@wordpress/data` as WordPress core for state management, it has not relied on the version provided with WordPress itself for a long time. Instead this is bundled internally and uses a separate registry instance.

One challenge of this approach is when a component needs data from Site Kit's data stores _and_ WordPress core's as is becoming necessary with other issues involving new components in the block editor.

Within the context of the block editor, we need to use `withSelect` and `withDispatch` via `wp.data` to avoid multiple React instance errors as these use hooks internally. As long as a component is wrapped with Site Kit's registry provider, these HOCs will work just fine. A problem arises however when we need to select from both because registry providers only provide a single instance; closest provider wins. This is important, particularly for selecting data as this adds a listener on the registry so that the component can be notified of updates and re-render.

Luckily, `@wordpress/data` registries support an optional `parent` registry instance when creating. This allows for a registry to inherit stores from another registry. When selecting, if the given store (aka reducer key) does not exist on the registry, it will [forward the select on to its parent if present](https://github.com/WordPress/gutenberg/blob/39f883e503f05aac223fe9d9d03a49d6279192a4/packages/data/src/registry.js?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L87-L92).

This allows for selects to work across multiple registries, while allowing consuming components to update when data updates. The only limitation of this is that a store by the same name in the child would take precedence over the parent's.

We should update our registry to be created with `wp.data` as its parent, but we probably want to restrict this to be conditional to only in the editor.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If WordPress core's datastore registry is available/loaded (`window.wp.data` global), our own datastore registry (`googlesitekit-data`, or `window.googlesitekit.data` in production) should have that registry included as its parent.
    * This should typically only apply in the Gutenberg editor, but it makes sense to do this whenever WP core's registry is loaded, which can also happen in other places.

## Implementation Brief

Within the file `assets/js/googlesitekit/data/index.js`:
* Update the call to `createRegistry` to pass in `global.wp.data` for the `parent` argument, if it exists. E.g.
```js
const Data = createRegistry( {}, global.wp?.data );
```
https://github.com/google/site-kit-wp/blob/591e83d20779ed402df1fda0f3a88f02dd7ddc60/assets/js/googlesitekit/data/index.js#L44

### Test Coverage

* Add JS tests to verify the `Data` registry delegates to `wp.data` when it exists.

## QA Brief

* QA: Perform simple smoke testing to ensure nothing has broken on the dashboard.

* QA:Eng: Verify the added unit test is correct and passing.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv I defined some preliminary ACs here - what do you think?

**Comment by aaemnnosttv** [comment]
Thanks @felixarntz! If we're not overly concerned about it being registered with the parent elsewhere, then that makes it a bit simpler. We do need to be a bit more mindful about store names going forward to make sure we don't conflict with core (in case we would ever need to select from both).

Taking another look at the details, there are a few additional things we'll need to keep in mind here:

* `parent` is defined as a registry, but `wp.data` isn't a complete registry but rather a subset (plus some other things). It should be fine for this purpose since parent is only used in our version of `data` with `select`, `dispatch` and `subscribe`
* `wp.data` will vary as to which version of `@wordpress/data` it uses internally so we may need to add a compatibility layer (e.g. to support `__experimentalResolveSelect` <-> `resolveSelect`)
  * Also note that our version of `@wordpress/data` (4.12.0) does not support using a `parent` with `__experimentalResolveSelect` (although the newer version does; #1769)

**Comment by felixarntz** [comment]
@aaemnnosttv Since #1769 is quite complex and may delay this significantly, maybe we're fine with just specifying `wp.data` as `parent` for now? I understand this leaves room for future problems if we want to use more, at the same time, the use-cases for using `wp.data`-based selectors and actions are currently rare, and like you're saying I'd think right now we don't need any of the more advanced features. We could open an issue to revisit this, as a sort of TODO.

> Also note that our version of `@wordpress/data` (4.12.0) does not support using a `parent` with `__experimentalResolveSelect`

Related to what I said above, is this an actual blocker for this, or does it only mean we can't rely on `__experimentalResolveSelect` in the parent registry? The latter would probably be fine for now.

**Comment by aaemnnosttv** [comment]
I don't think it's a blocker, nor was I implying this issue was dependent on #1769. It would probably be straightforward to use `wp.data` as a parent, just making sure we don't miss any important details. If we don't use `resolveSelect` for any core  stores it should be fine, but if we did, we'd need to add a bit of a compatibility layer because that function would vary based on what version of WP core we were running in.

This is all I meant by a compatibility layer

```js
const { resolveSelect, __experimentalResolveSelect } = wp.data;
const parent = {
  ...wp.data,
  resolveSelect: resolveSelect || __experimentalResolveSelect,
  __experimentalResolveSelect: resolveSelect || __experimentalResolveSelect,
}
```

We probably don't need to worry about this for now though.

The current ACs look good to me, so I'll move this on to IB 👍

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by kuasha420** [comment]
QA: :heavy_check_mark:

Verified the correctness of the added test and it is passing.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

-  Performed simple smoke testing to ensure nothing has broken on the current, unified and entity dashboard on the develop branch. No errors in console and data loaded as expected.
