### ISSUE TITLE
Google chart tooltips overlap the plugin header

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#4360]
## Feature Description

Looks like the `z-index` value for visualization tooltips is higher than the one we use for the plugin header. This causes a UI bug like this:

![image](https://user-images.githubusercontent.com/873049/142016271-88412ec2-f02a-477c-bc15-3dac213c658f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This may be preferable than keeping them under it as we do. Dropdown/select menus also have a higher z-index than the header. Worth reviewing though.

**Comment by eugene-manuilov** [comment]
Going to close this ticket in favor of #4496
