### ISSUE TITLE
Add `no-use-before-define` ESLint rule

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#4361]
## Feature Description

Add the [`no-use-before-define`](https://eslint.org/docs/rules/no-use-before-define) ESLint rule to help prevent bugs where variables are used before they are defined.

For example, this bug would have been caught before it hit `develop`: https://github.com/google/site-kit-wp/issues/4329 

The following config would cause the least friction with the codebase while still catching use-before-define variable bugs like the one above:
```
"no-use-before-define": ["error", { "functions": false, "classes": false, "variables": false }]
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint rule `no-use-before-define` should be added to our `eslintrc.json` file.
* It should not be possible to use variables before they are defined—doing so should trigger and ESLint error.

## Implementation Brief

* Add `"no-use-before-define": ["error", { "functions": false, "classes": false, "variables": false }]` to our ESLint config. Doing this won't flag things like functions being defined at the top-level of a file after they're used _inside_ a function (eg like []`numberFormat`](https://github.com/google/site-kit-wp/blob/1bafd2e6cdc62eda8e9836b4989f81100e02ba13/assets/js/util/i18n.js#L322)), which is fine. But it should alert us when a variable is used in a problematic way before it is defined.
* Fix any issues found by this rule (it looks like there's only a few files with violations).

### Test Coverage

* No tests needed.

## QA Brief

**This needs to be QA:Eng**
- Verify the `eslintrc.json` file for the above rule declaration 
- Run `npm run lint:js` to verify all the rules are passing
- In addition, edit any `*.js` file and use a variable before it's declaration
- Verify the lint error should appear
- Do the same for a `function` declaration. This shouldn’t be an issue.

**Secondary QA**

- Ensure "Unique Visitors from Search" on the dashboard details (entity dashboard) shows the same value as the previous release (particularly for non-UD but can check both)

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by ivankruchkoff** [comment]
QA: ✅

Error correctly raised for a variable and correctly not raised for a function call.

**Comment by aaemnnosttv** [comment]
## QA :x:

As raised in #4658 this has introduced at least one regression on the dashboard details screen due to the Analytics report for unique visitors being made without the `url`.

I will review the PR again and create a follow-up for the fix.

cc: @hussain-t @eugene-manuilov @ivankruchkoff

**Comment by techanvil** [comment]
## QA: :white_check_mark: 

**Primary QA:**

* Verified the `.eslintrc.json` rule config.
* Ran `npm run lint:js`, all rules passed.
* Verified the lint error appears when using a variable before its declaration, but not when using a function.

**Secondary QA:**

* Verified that "Unique Visitors from Search" on the dashboard details (entity dashboard) shows the same value as the previous release with the unified dashboard feature both enabled and disabled.
