### ISSUE TITLE
Update unified dashboard tab bar pills to scroll to an area instead of relying on the browser anchor targets

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#4367]
## Feature Description

Unified dashboard tab bar pills (introduced in #4053) use html anchors to let users go to a specific widget area. This works perfectly, but due to our sticky header design, users don't see the top part of the widget area because the sticky header overlaps it. This is the expected default behavior of all browsers, but this is not a good user experience because they will need to manually scroll a little bit more to see the top of the selected widget area section.

We probably need to rework pills a little bit to programmatically scroll to the widget area (using the `window.scrollTo` function) taking into account the height of the header.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Instead of relying on the anchor tags for the pills navigation in the `unifiedDashboard`, the pills should result in a smooth scroll animation to the respective area.
* It must also be ensured that it actually scrolls to the correct point, which by default (i.e. plain anchor links) is not the case due to the sticky header design.

## Implementation Brief
* Using `assets/js/components/DashboardNavigation.js`,
	* Update `handleSelect` to :
		* Remove the line where we set the hash in the URL.
		* Use `history.replaceState` to set the hash (this will prevent automatic scrolling to the container).
		* Using `global.window.scrollTo`, scroll to the top of the selected hash container taking the following elements height into account:
			* the sticky header (`.googlesitekit-header`)
			* the navigation (`.googlesitekit-navigation`)
		* If the selected hash container is `traffic`, we can scroll to the top of the page since we can potentially have a sub header. `.googlesitekit-subheader`
		* If the hash is `undefined`, when we deselect a chip, the hash must be removed using the `removeQueryArgs` function from `@wordpress/url` and the URL set again using `history.replaceState`.

### Test Coverage
* No new tests to be added.

## QA Brief

* Using the [Tester Plugin](https://sitekit.withgoogle.com/service/download/google-site-kit-tester.zip), enable the `unifiedDashboard` feature flag.
* Navigate to the Dashboard.
* Verify clicking on each of the tab bar pills (Traffic, Content, Speed and Monetization) correctly scrolls to the relevant context area.
  * Note that clicking on Traffic should scroll to the top of the page.
  * If a context is empty (e.g. Monetization) then the scrolling behaviour can be ignored as the pill for an empty context is going to be hidden as a result of this ticket in the current sprint: https://github.com/google/site-kit-wp/issues/4289
* Clicking on a selected pill should deselect the pill and remove the hash part of the URL in the address bar.

## Changelog entry

* Update Unified Dashboard navigation chips to scroll to an area instead of relying on anchor targets.

**Comment by felixarntz** [comment]
@eugene-manuilov Thanks for catching that, we should definitely fix this. @FlicHollis Probably worth trying to get this into Sprint 63.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@eugene-manuilov @techanvil I have a few observations:

1. User clicks on 'Speed' and I am taken to the PageSpeed Insights widget.  When I deselect the 'Speed' chip, the background colour changes to grey, and I am assuming it should be white like the inactive chips? This applies on all chips. I noticed when you click away from the chip that the background colour changes to white. 

2. When I deselect the chip, I am not taken to the top of the page.  Should I? Unsure what the correct behaviour is.  

https://user-images.githubusercontent.com/73545194/143010139-2b3b6f47-2d25-4500-997f-46a45d4e93c9.mp4

3. When there is a notification, and you click on a chip, i.e 'Speed' you are not taken to the top of the widget. It lands half way between two widgets. Tried to capture it in this screencast. 

https://user-images.githubusercontent.com/73545194/143012262-4345381d-4c34-48f6-a0d2-9b78cffb5a19.mp4

**Verified:**

- Clicking on a selected pill deselects the pill and removes the hash part of the URL in the address bar.

**Comment by techanvil** [comment]
@wpdarren thanks for the review. Regarding points 1 and 2, my take is these are outside of the scope of this ticket; the behaviour in each case is not introduced by this PR, and not addressed by the AC or the IB. I would suggest raising these as separate tickets to be triaged.

Point 3 definitely needs a fix, I'll get onto that now. Cheers

**Comment by eugene-manuilov** [comment]
> User clicks on 'Speed' and I am taken to the PageSpeed Insights widget.  When I deselect the 'Speed' chip, the background colour changes to grey, and I am assuming it should be white like the inactive chips? This applies on all chips. I noticed when you click away from the chip that the background colour changes to white.

@wpdarren this is the correct behavior. The chip stays grey because it is active and you can select it again by hitting the "Enter/Return" key. Also you can navigate between chips using the Tab key, which when clicked, activates the next chip and makes it grey.

Ideally, we shouldn't allow users to deselect a chip at all, but unfortunately this is impossible with the Material UI library we use for chips.

> When I deselect the chip, I am not taken to the top of the page. Should I? Unsure what the correct behaviour is.

No, you shouldn't go to the top.

**Comment by eugene-manuilov** [comment]
@wpdarren the 3rd point is fixed.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Clicking the tab bar chips (Traffic, Content, Speed and Monetization) correctly scrolls to the relevant context area.
- Clicking on Traffic scrolls to the top of the page.
- Clicking on a selected chip deselects it and removes the hash part of the URL in the address bar.
- Verified 3rd point issue has been fixed and placement is correct with notification. 

https://user-images.githubusercontent.com/73545194/143069897-052001ef-8d93-422b-b11e-7f8e3b8a8c1a.mov
