### ISSUE TITLE
Decrease threshold for showing Idea Hub interaction survey

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4368]
The Idea Hub interaction trigger for surveys currently fires after 6 interactions with the widget have been made (e.g. save/unsave/dismiss an idea). We've so far received too little feedback from users, but still do not want to increase the overall rollout at this point, so the threshold here should be lowered to 3 interactions.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The number of interactions with the Idea Hub widget to fire the `interact_idea_hub` survey trigger should be reduced to 3 (instead of 6).

## Implementation Brief
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`, update the `interactionCount` check from `5` to `2`.

### Test Coverage
* Update `assets/js/modules/idea-hub/datastore/module-data.test.js` to account for above changes if there are any failing tests.

## QA Brief

* Create a new jurrasic ninja site
* Install the plugin and sign in using your Google account
* Enable the idea hub feature flag using the tester plugin
* Activate and set up the Idea Hub module
* Go to the dashboard page and perform one of the following actions three times:
  * save an idea
  * dismiss an idea
  * create a draft
* Make sure that after the 3rd action, you see the survey pops up (it may take up to 10 seconds to receive and show the survey).

## Changelog entry

* Show Idea Hub surveys after fewer Idea Hub interactions.

**Comment by felixarntz** [comment]
@FlicHollis This is a very small but important issue, could we add it to the upcoming sprint as well?

**Comment by eugene-manuilov** [comment]
> * Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`, update the `interactionCount` check from `5` to `3`.

@asvinb, if we update it to `3`, then it will mean that the survey will be triggered on the 4th interaction. AC says that it should happen after the 3rd interaction. Thus we need to update the `interactionCount` check from `5` to `2`, right?

**Comment by asvinb** [comment]
Good catch @eugene-manuilov . Updated!

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov @felixarntz in the QAB it mentions setting up a new Jurassic.ninja site but we only get ideas on `oi.ie` and `elasticpress.io` so I followed the instructions in the QAB, but on a site that is connected to `oi.ie` via the developer plugin. After going through the 3 actions, no survey appeared.  I remembered this being a tough one to test previously.  Am I right in thinking that we have to do something on the service site?

**Comment by eugene-manuilov** [comment]
> ... but on a site that is connected to `oi.ie` via the developer plugin.

@wpdarren, I think it doesn't work on your existing site because that feature tour has been already dismissed there. Can you try to do the same on a brand new jurassic.ninja site with the developer plugin configured to use `oi.ie` domain? Or maybe try to use a different admin on your existing site because feature tours are dismissed on a per-user basis. Let me know if it helps.

**Comment by wpdarren** [comment]
@eugene-manuilov I have followed the instructions in the QAB and your comment, and still cannot trigger the survey.  I did some digging though and found this from @felixarntz on [this ticket ](https://github.com/google/site-kit-wp/issues/4052#issuecomment-925172665)

> In order to trigger the notification, in addition to the plugin-side requirements, you have to be on **version 1.42.0** and you have to have activated Idea Hub in the site at least **48 hours** ago. Also as soon as you complete or close the survey, you won't be able to trigger it again on the same site and same Google account. If needed, coordinate with me to reset that.

I am assuming this will still applies.  

I have set up a site with Idea hub activated, and 1.42.0 in the tester plugin. 
Will check in 48 hours to see if I am able to trigger the survey.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified: After the 3rd action, you see the survey pops up. - [Screenshot](https://user-images.githubusercontent.com/73545194/143864630-33d04731-baad-4115-b90b-8604ad8d4d76.png)
