### ISSUE TITLE
Pill navigation overlap search dropdown

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#4370]
## Bug Description

When we search for a post/page on the unified dashboard, the pill navigation overlaps the autosuggest dropdown.

## Steps to reproduce

1. Enable the `unifiedDashboard` feature flag
2. Go to the main dashboard 
3. Click on the search icon and search for a page/post
4. Notice how the pill navigation overlaps the autosuggest dropdown

## Screenshots
![image](https://user-images.githubusercontent.com/31818/142382085-0958b5af-b58b-49cc-baa5-94cf0c5712d9.png)

## Additional Context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The search input and autocomplete contents should appear above the navigation/pill links (and by extension, above nearly all other content that isn't a modal/dialog/etc.)

## Implementation Brief

* Using `assets/sass/components/global/_googlesitekit-dashboard-navigation.scss`, decrease the `z-index` for `.googlesitekit-navigation` to `11`. The `z-index` should always be lower than that of `.googlesitekit-header`

### Test Coverage
* No new tests to be added.

## QA Brief

* enable Unified Dashboard feature flag. 
* The search results should appear over chip navigation on both Desktop and Mobile. 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment]
@eugene-manuilov @asvinb I noticed this same problem today but with other dropdowns in the header. I haven't checked, but please ensure the current IB accounts for this as well.

![image](https://user-images.githubusercontent.com/1621608/142903843-acf36f7c-0308-4944-b8ef-1a157dae57fa.png)

**Comment by asvinb** [comment]
@kuasha420 Please note that this bug has been fixed in https://github.com/google/site-kit-wp/pull/4384 . Can you hold on for now till #4384 is reviewed and merged?

**Comment by kuasha420** [comment]
@asvinb Okay, thanks for notifying!

**Comment by wpdarren** [comment]
@asvinb @kuasha420 just adding a note here that this also causes an issue on small screen sizes. I am sure this fix will cover this as well but wanted to make a note :) 

![image](https://user-images.githubusercontent.com/73545194/143249514-ff180257-6b82-4bf8-8551-703d57086367.png)

**Comment by kuasha420** [comment]
@asvinb as you've said, this issue has been fixed and merged to develop on the aforementioned PR. Did a quick test and it seems to no longer overlap on desktop/mobile. Sending it to @wpdarren for QA.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified the search results appear over chip navigation on both Desktop and Mobile. 
- Also noticed Evan's comment re. overlap of all dropdowns in the header, so also made sure those display as expected.

[Screenshot 1](https://user-images.githubusercontent.com/73545194/144055441-ab823798-fa2f-4710-b444-f021274b74f1.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/144055456-e60344b8-60c2-469c-91e9-ded2b1faabad.png) - [Screenshot 3](https://user-images.githubusercontent.com/73545194/144055476-f739cafa-3212-4cf9-9b8d-047e6a0b37b5.png)

**Comment by aaemnnosttv** [comment]
@felixarntz seeing as this was fixed in another PR, should it get an entry in the changelog?

**Comment by felixarntz** [comment]
@aaemnnosttv I think it's okay not adding one, mostly because this is a bug fix which isn't relevant to regular users anyway (since behind a feature flag). Not opposed to adding a message if you prefer though.
