### ISSUE TITLE
The necessary verification token could not be found on your site.

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4371]
## Bug Description

One [user in the support forums](https://wordpress.org/support/topic/unable-to-activate-site-kit/page/2/#post-15080561) is encountering the below error after various troubleshooting efforts. The error appears on the "Verify Ownership" stage during setup. 

**_The necessary verification token could not be found on your site. This may be related to your site using a page caching plugin. Please flush your home page cache and then try again._**

![image](https://user-images.githubusercontent.com/41326532/142406378-2164aa0a-e608-4f55-a273-61e662487e89.png)

## Additional Context

 - Site Kit 1.45.0
 - Support Topic: https://wordpress.org/support/topic/unable-to-activate-site-kit/page/2/#post-15080561
 - [Site Health Information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNj6Qs1J3YvkCfGa3113T32ZF5fy7g-uJHZGizfV21sE9iM_rEVpWHl6IhK4Qy5mR1c)
 - Recording of experience added to the users SH information above

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check
- [x] Front end check (mixed content, minified content, combined JS) - site not fully HTTPS
- [x] Incognito mode 
- [x] Checked users Site Health info, no identified causes - Previous REST related errors no longer apparant
- [x] Additional .htaccess rules applied - Tested with a renamed htaccess file
- [ ] Uninstalled and reinstalled plugin
- [x] Reset the plugin
- [x] Performed a check on the same hosting platform - Account created and tested support side. No issues with this test site ([Internal task](https://app.asana.com/0/1185360131189553/1201387440762248/f))
- [x] User confirmed no "Critical errors" in their Site Health status
- [x] Attempted setup/viewing dashboards from another device - same occurs
- [ ] Reset Site Kit (Remotely - on the SK service)
- [ ] Disconnected Site Kit
- [x] Checked does the same occur from another Google account account
- [ ] Checked setup / viewing dashboards from another WordPress administrator account

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
The impacted user provided some very useful insights with their [latest Site Health information report](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhAjMm-OISFadDuoTJOz7ypX4rqPMSlIwdr45Y2L0lu6HKL5yiNRFMMRvxxcEcTLpc). When checking from a Chrome browser incognito window with all other plugins disabled (via the Health Check & Troubleshooting plugin) they're encountering a REST API error as error as per the screenshot below:

![image](https://user-images.githubusercontent.com/41326532/142469091-433d35c0-70a7-4282-9909-4ba25e825015.png)

Despite this the users public REST endpoints are accessible. Further testing to be done on the same hosting platform for any possible hosting related security features.

**Comment by jamesozzie** [comment]
Further checks performed from the same hosting control panel (basic multisite package). No [obvious security features](http://recordit.co/kKbYiv8T3Y) that may disable the WordPress REST API. 

The same environment also setup without being able to recreate. 

<details>
<summary>Support testing SH info</summary>


```
`
### wp-core ###

version: 5.8.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/webjamuk1/domains/webjam.uk/public_html
wordpress_size: 46.37 MB (48620510 bytes)
uploads_path: /home/webjamuk1/domains/webjam.uk/public_html/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /home/webjamuk1/domains/webjam.uk/public_html/wp-content/themes
themes_size: 6.47 MB (6780262 bytes)
plugins_path: /home/webjamuk1/domains/webjam.uk/public_html/wp-content/plugins
plugins_size: 9.92 MB (10403701 bytes)
database_size: 2.06 MB (2162261 bytes)
total_size: 64.82 MB (67966734 bytes)

### wp-active-theme ###

name: Aden (aden)
version: 3.1.3
author: Infinity-Themes
author_website: http://themeforest.net/user/infinity-themes
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, post-thumbnails, widgets-block-editor, title-tag, post-formats, menus, widgets
theme_path: /home/webjamuk1/domains/webjam.uk/public_html/wp-content/themes/aden
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 2.1, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (10) ###

Aden Core: version: 1.0, author: Infinity-Themes, Auto-updates disabled
AJAX Thumbnail Rebuild: version: 1.13, author: junkcoder, ristoniinemets, Auto-updates disabled
Contact Form 7: version: 5.5.2, author: Takayuki Miyoshi, Auto-updates disabled
Easy Google Fonts: version: 2.0.4, author: Titanium Themes, Auto-updates disabled
Limit Login Attempts Reloaded: version: 2.23.2, author: Limit Login Attempts Reloaded, Auto-updates disabled
One Click Demo Import: version: 3.0.2, author: OCDI, Auto-updates disabled
Royal Backend Gallery: version: 1.0, author: Royal-Flush, Auto-updates disabled
Site Kit by Google: version: 1.45.0, author: Google, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled
Yoast SEO: version: 17.6, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (14) ###

Akismet Anti-Spam: version: 4.2.1, author: Automattic, Auto-updates disabled
Asset CleanUp: Page Speed Booster: version: 1.3.8.4, author: Gabe Livan, Auto-updates disabled
Async JavaScript: version: 2.21.08.31, author: Frank Goossens (futtta), Auto-updates disabled
Autoptimize: version: 2.9.2, author: Frank Goossens (futtta), Auto-updates disabled
Classic Widgets: version: 0.2, author: WordPress Contributors, Auto-updates disabled
Elementor: version: 3.4.8, author: Elementor.com, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Insert Headers and Footers: version: 1.6.0, author: WPBeginner, Auto-updates disabled
Really Simple SSL: version: 5.1.3, author: Really Simple Plugins, Auto-updates disabled
Redirection: version: 5.1.3, author: John Godley, Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.16.63, author: UpdraftPlus.Com, DavidAnderson, Auto-updates disabled
WP-REST-API V2 Menus: version: 0.10, author: Claudio La Barbera, Auto-updates disabled
WP File Manager: version: 7.1.2, author: mndpsingh287, Auto-updates disabled
WP Mail SMTP: version: 3.2.1, author: WPForms, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1801
imagemagick_version: ImageMagick 7.0.9-22 Q16 x86_64 2020-02-12 https://imagemagick.org
imagick_version: 3.4.3
file_uploads: File uploads is turned off
post_max_size: 64M
upload_max_filesize: 64M
max_effective_size: 64 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 45 GB
	imagick::RESOURCETYPE_DISK: 9223372036854775807
	imagick::RESOURCETYPE_FILE: 49151
	imagick::RESOURCETYPE_MAP: 45 GB
	imagick::RESOURCETYPE_MEMORY: 23 GB
	imagick::RESOURCETYPE_THREAD: 8
imagemagick_file_formats: 3FR, 3G2, 3GP, A, AAI, AI, ART, ARW, AVI, AVS, B, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DJVU, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FLV, FRACTAL, FTP, FTS, G, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, O, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, R, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0 x86_64
httpd_software: Apache/2
php_version: 7.3.19 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 30
memory_limit: 384M
max_input_time: 60
upload_max_filesize: 64M
php_post_max_size: 64M
curl_version: 7.68.0 OpenSSL/1.0.2k-fips
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.2.31-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/webjamuk1/domains/webjam.uk/public_html/wp-content
WP_PLUGIN_DIR: /home/webjamuk1/domains/webjam.uk/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 384M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### google-site-kit ###

version: 1.45.0
php_version: 7.3.19
wp_version: 5.8.2
reference_url: http://www.webjam.uk
amp_mode: no
site_status: connected-site
user_status: authenticated
verification_status: verified-non-site-kit
connected_user_count: 1
active_modules: site-verification, search-console, analytics, analytics-4
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_view_module_details: ✅
	googlesitekit_manage_options: ✅
enabled_features: 
	ideaHubModule: ⭕
	serviceSetupV2: ⭕
	swgModule: ⭕
	userInput: ⭕
	unifiedDashboard: ⭕
search_console_property: http://www.webjam.uk/
analytics_account_id: 2133•••••
analytics_property_id: UA-2133•••••••
analytics_profile_id: 2558•••••
analytics_use_snippet: yes
analytics_4_property_id: 2941150••
analytics_4_web_data_stream_id: 3057••••••
analytics_4_measurement_id: G-8Y••••••••
analytics_4_use_snippet: yes

`

```


<details/>

So to summarize there is something seemingly restricting the WordPress REST API on the users side, with no obvious plugins, theme features of hosting features being the cause. The setup above mimic's the users environment and uses the same hosting platform. Un-reproducible so far.

**Comment by jamesozzie** [comment]
Console errors shared by the user when they have no .htaccess file active (via renaming). 

![image](https://user-images.githubusercontent.com/41326532/142608139-e78d74c1-b93d-4126-b60a-9e6dc2f62044.png)

The REST related error doesn't occur with their .htaccess file reverted although this is a file with modifications. I suspect there may be a cached version of their site being served from here. Awaiting details of the contents of their htaccess file.

**Comment by jamesozzie** [comment]
From checking the users .htaccess file there doesn't seem to be anything unusual with their rules. 

<details><summary>.htaccess details</summary>


```
# BEGIN rlrssslReallySimpleSSL rsssl_version[5.1.3]
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTPS} !=on [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
</IfModule>
# END rlrssslReallySimpleSSL
# BEGIN WordPress
# De richtlijnen (regels) tussen "BEGIN WordPress" en "END WordPress" worden
# dynamisch gegenereerd en zouden alleen aangepast mogen worden via WordPress filters.
# Alle wijzigingen aan de richtlijnen tussen deze markeringen worden overschreven.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

</details>

**Comment by jamesozzie** [comment]
Escalating this for engineer review. Notes updated in original post with all troubleshooting checks performed. The user is still facing the caching plugin notice that doesn't allow setup to proceed, with the verification token not found. A video of this behavior an be found within [this Site Health information report](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhAjMm-OISFadDuoTJOz7ypX4rqPMSlIwdr45Y2L0lu6HKL5yiNRFMMRvxxcEcTLpc). 

Happy to share a login to a site from the same hosting platform with the same environment if needed.

**Comment by bethanylang** [comment]
User was able to successfully connect by manually verifying via Search Console; closing for now unless this comes up again.

**Comment by Eshaan12345** [comment]
Hey James, my analytics setup is saying that it isn't finding the necessary token and is asking me to remove cache but I did it about 4 times yet the same is going on. PLS HELP!
<img width="896" alt="8hirfkdm'dmmldk;dkewklmekmcrdwkmkmrvkmrv" src="https://github.com/google/site-kit-wp/assets/94111799/58e488fd-68b7-4825-a595-8ee2c0f06561">

**Comment by adamdunnage** [comment]
> Hey James, my analytics setup is saying that it isn't finding the necessary token and is asking me to remove cache but I did it about 4 times yet the same is going on. PLS HELP! <img alt="8hirfkdm&apos;dmmldk;dkewklmekmcrdwkmkmrvkmrv" width="896" src="https://user-images.githubusercontent.com/94111799/244278318-58e488fd-68b7-4825-a595-8ee2c0f06561.png">

@Eshaan12345 Thanks for dropping a comment here. We don't provide support via GitHub but we would be happy to help you if you could please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0).
