### ISSUE TITLE
Button within entity search input should not overlap input border upon hover/focus.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#4373]
## Bug Description
When the close icon within the entity search component has focus or is hovered, it overlaps the input's border.

## Steps to reproduce

1. Enable the `unifiedDashboard` feature flag.
2. Go to main dashboard. 
3. Click on the search icon in the header
4. Hover the close icon
5. Notice how the button background color overlaps the input border.

## Screenshots

![image](https://user-images.githubusercontent.com/31818/142427857-029a8665-ab65-4384-99b7-c3c0233022a6.png)

## Additional Context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The close button shown within the `EntitySearchInput` should not visually overlap the border of the search input when hovered. E.g. When compared with the screenshot above, it should look like this
![image](https://user-images.githubusercontent.com/1621608/143213939-cc7fdca6-825f-424a-9c88-2709699610f4.png)

## Implementation Brief

Within `assets/sass/components/global/_googlesitekit-entity-search.scss`:

* In the `googlesitekit-entity-search__actions` class, within the media query for tablet and above, change `right: 0` to `right: 1px` to allow for the border.
https://github.com/google/site-kit-wp/blob/022827b589787be0972c9158be1b818bb4096ae7/assets/sass/components/global/_googlesitekit-entity-search.scss#L37-L39

### Test Coverage

* No tests needed.

## QA Brief

* Follow steps to reproduce and ensure hovering over the close icon does not overlap the search box border for all screen sizes.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
cc @felixarntz

**Comment by eugene-manuilov** [comment]
IB looks good to me. :heavy_check_mark: @techanvil can you add the estimate?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that the close icon does not overlap the search box border for all screen sizes.

![image](https://user-images.githubusercontent.com/73545194/144258398-b3ff7846-5ff4-4811-9a94-89868e985e47.png)

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov This has been missing a release assignment, but it was merged almost three years ago according to the PR #4434. Not sure whether it was in 1.47.0 or is going into 1.48.0, I just assigned the latter for now.

Anyway, at least here it doesn't matter so much since it doesn't have/need a changelog entry anyway :)
