### ISSUE TITLE
Fix incorrect GA event category for authentication success notification

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4374]
We just noticed while looking at the GA events data for something that the plugin is triggering some events for a `{viewContext}_authentication-success-notification` category and others for a `{viewContext}_authentication-success_notification` category (underscore instead of dash). This is incorrect, and it looks like the reason for this problem were the ACs for #4054 where the latter was used although it should have been with a dash instead of underscore.

This is important to fix, but it should be a simple change.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Everywhere where a `{viewContext}_authentication-success_notification` event category is used, that event category should be adjusted to `{viewContext}_authentication-success-notification` (dash instead of underscore).

## Implementation Brief

In `assets/js/components/notifications/SetupSuccessBannerNotification.js`:

* Replace the event category `{viewContext}_authentication-success_notification` to `{viewContext}_authentication-success-notification`
* Update any failing tests.

### Test Coverage

* No new tests needed.

## QA Brief

* Verify that the events listed in the AC are all present and correct.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@FlicHollis @eclarke1 This is a very small fix for a bug we just noticed, can we put it into Sprint 63?

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
@jimmymadon could you please add QAB?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Went through setting up all of the modules (including Idea hub) and checked the event category `{viewContext}_authentication-success-notification` is appearing.  - [Screenshot](https://user-images.githubusercontent.com/73545194/143473862-cd2734af-e65f-40b0-913a-b788217c6212.png)
