### ISSUE TITLE
Remove chevron from date range select dropdown button in header

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4377]
## Feature Description

We should remove the chevron from the date range selector, in the Unified Dashboard only.

### Current

<img width="367" alt="Screenshot 2021-11-19 at 10 55 59" src="https://user-images.githubusercontent.com/90871/142611497-0f410196-78c4-4607-bde5-1b9b60e8fb7b.png">

### Intended

<img width="382" alt="Screenshot 2021-11-19 at 10 56 12" src="https://user-images.githubusercontent.com/90871/142611535-bc17f240-02e3-4a3d-9a4f-1d7b04925b24.png">

Note: The Figma mockups use slightly different icons; don't worry about those. The intention here is only to remove the chevron/"down-arrow" next to the date range selector/calendar icon. Don't worry about changing the icons or the icon styles otherwise 🙂 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The chevron should be removed from the Date range picker/icon **only on mobile viewports** and only when the `unifiedDashboard` feature flag is enabled. The Figma mocks here: https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe/%5BMVP%5D-Unified-Dashboard?node-id=2%3A13156 show it visible on desktop screens so it should only be removed on mobile.

## Implementation Brief

* On mobile viewports only, remove the `background-image` from this element: https://github.com/google/site-kit-wp/blob/d4bcbfceed3050b6cd83605a6cccbb22328ec626/assets/js/components/DateRangeSelector.js#L92 (the date range picker button). This might require adjusting the padding as well on mobile to not account for the dropdown chevron.
* These styles can be set on this element by adding a custom class `googlesitekit-header__date-range-selector-menu-unified-dashboard` to the `<Button>` element when `useFeature('unifiedDashboard')` is `true`.
  * It would be good to use `classnames` to output the `className` prop on the `Button` component here now, as there will be conditionals.

### Test Coverage

* VRT tests on mobile may require updating.

## QA Brief

* Using the [Tester Plugin](https://sitekit.withgoogle.com/service/download/google-site-kit-tester.zip), enable the `unifiedDashboard` feature flag.
* Navigate to the Dashboard and verify the chevron disappears on mobile (i.e. below the tablet breakpoint which is 600px), as per the AC.

## Changelog entry

* Remove chevron from date range select dropdown button in the header.

**Comment by eugene-manuilov** [comment]
> ... and only when the unifiedDashboard feature flag is enabled.

@tofumatt, could you, please, update IB to tell which approach to use to make sure the chevron change applies only when the unifiedDashboard feature flag is enabled?

**Comment by tofumatt** [comment]
Sounds good, added to the IB 👍🏻

**Comment by eugene-manuilov** [comment]
Thanks, @tofumatt. IB :heavy_check_mark:
