### ISSUE TITLE
Introduce admin bar integration on AMP pages

### ISSUE THREAD

**Issue by westonruter** [google/site-kit-wp#438]
## Feature Description

Currently the full admin bar integration is disabled on AMP pages:

https://github.com/google/site-kit-wp/blob/c9e27e85acfc47413aaa1dc30a3050cd14f0ed7f/includes/Core/Admin_Bar/Admin_Bar.php#L75-L92

However, thanks to a new AMP “dev mode” capability, there is now a proper way to include invalid AMP markup on an otherwise valid AMP page. When the `html` element has a `data-ampdevmode` attribute, then any element which also has this same attribute will have its validation errors suppressed. See https://github.com/ampproject/amphtml/issues/20974 and https://github.com/ampproject/amp-wp/pull/3084. In dev mode, the AMP validator extension will not complain about validation errors: https://github.com/ampproject/amphtml/issues/24176.

This is exactly what the AMP plugin has needed to prevent the admin bar from getting excluded due to the additional CSS that the admin bar requires. For details on that, see https://github.com/ampproject/amp-wp/issues/1921.

This opens up opportunities for Site Kit as well. As long as the `googlesitekit_adminbar_loader` script and its dependencies get the `data-ampdevmode` attribute added to it, then they will not get removed by the sanitizer and the admin bar on AMP pages can be just as interactive as on non-AMP pages.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When AMP dev mode is enabled (via AMP plugin >= 1.4's `amp_is_dev_mode()`), the admin bar menu of Site Kit should expand in the frontend for an AMP request just like it does for a non-AMP request. Clicking on the menu should _not_ take you to the admin like it does in AMP without dev mode.

## Implementation Brief

* Merge #505

## Changelog entry

* Add support for displaying the full Site Kit admin bar menu with stats also for AMP requests, by leveraging AMP's dev mode feature.

**Comment by tofumatt** [comment]
What are the steps to QA this issue/reproduce the results? I'm not super-familiar with AMP or the AMP plugin, so I've tried installing the latest AMP plugin and using a browser extension to load AMP pages, but I'm unclear as to what to check here. I see the admin bar in pages when I enable "Standard" AMP across the site.

I see the _Site Kit section_ in the WordPress admin bar on what claim to be "AMP pages" in the latest `develop`. If that's what this issue is referring to then it seems to be working, but I'm not clear on that/confident the AMP output is working as expected given it doesn't look any different in my browser.

So I think this is right but if someone could verify my interpretation of this issue that'd be appreciated. 🙂

**Comment by westonruter** [comment]
If you activate the AMP plugin and in the AMP plugin settings switch from “Reader” to “Standard” mode, you should then be able to the Site Kit functionality in the admin bar just the same as when AMP is turned off. Previously in AMP the Site Kit menu item would not show the details for the current URL when tapping.

In addition to the admin bar being fully functional in AMP pages, the AMP plugin should likewise not be reporting any validation errors from Site Kit. In other words, you should see a ✅ in the AMP admin bar menu item.

**Comment by tofumatt** [comment]
Hmmm, I don't see a checkmark in the admin bar, but I don't see any errors on the actual AMP details page:

![2019-11-21 12 15 27](https://user-images.githubusercontent.com/90871/69337410-af8b0380-0c58-11ea-94a8-34d7d0ec7b8a.gif)

I'm not sure if something else is off here or if that's a bug in this patch.

**Comment by tofumatt** [comment]
(I should be clear: this is a local site running on my Mac—if AMP is expecting to be able to request these URLs from a Google server somewhere I'd expect them to fail.)

**Comment by felixarntz** [comment]
@tofumatt It shouldn't have problems because of a local site, there may be issues though if your local setup doesn't allow your server to run requests against itself. Alternatively, does this site have any potentially incompatible plugins?

**Comment by tofumatt** [comment]
No other plugins are enabled, just AMP 1.4.1 and the latest Site Kit from `develop`.

Oddly I get this error when activating AMP:

<img width="1120" alt="Screenshot 2019-11-21 13 01 42" src="https://user-images.githubusercontent.com/90871/69340331-26c39600-0c5f-11ea-8d0c-1660fe6a239f.png">

I didn't notice it before; maybe it's new.

**Comment by felixarntz** [comment]
Yeah that is probably related to your server not being able to run a request to itself.

**Comment by tofumatt** [comment]
Ah, okay, looks like something was off with my local setup:

<img width="725" alt="Screenshot 2019-11-21 at 13 34 33" src="https://user-images.githubusercontent.com/90871/69342538-ab181800-0c63-11ea-977e-8bd5eb4863eb.png">

QA ✅

**Comment by marrrmarrr** [comment]
LGTM.
