### ISSUE TITLE
Improve behaviour when PageSpeed 'visit the dashboard` link is clicked in Site Kit settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4380]
## Bug Description

When you click on the `visit the dashboard` link on PageSpeed Insights settings (`wp-admin/admin.php?page=googlesitekit-settings#/connected-services/pagespeed-insights`) you are redirected to the top of the Site Kit Dashboard. It would be more user-friendly to jump down to the PSI widget.  I realise we're working on the Unified dashboard but feel this still applies.

![image](https://user-images.githubusercontent.com/73545194/142656048-4d60b642-e221-414d-91c2-66581b0ae8ac.png)

## Steps to reproduce

1. Go to 'Site Kit settings'
2. Click on 'PageSpeed Insights.'
3. Observe the `visit the dashboard` link
4. See behaviour.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `visit the dashboard` link shown in the PageSpeed Insights settings view should be updated to link to the PageSpeed section of the dashboard
    * For the Unified Dashboard, this should link to the respective `#speed` anchor
    * For the current/non-unified dashboard, this should link to the same `#googlesitekit-pagespeed-header` used by the jump link today

## Implementation Brief
* Using `assets/js/modules/pagespeed-insights/components/settings/SettingsView.js`,
	* Use the `useFeature` hook and check whether the `unifiedDashboard` feature flag is enabled.
	* If the above feature flag is enabled,
		* append `#speed`
		* else append `#googlesitekit-pagespeed-header` to `dashboardPermalink`.
* Using `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js`,
	* Use the `useFeature` hook and check whether the `unifiedDashboard` feature flag is enabled.
	* Using the `useMount` hook, if the `unifiedDashboard` feature flag is not enabled, check for the `googlesitekit-pagespeed-header` hash.
		* If the hash is present, then scroll to the widget taking the height of the header into account.

### Test Coverage
* No new tests to be added.

## QA Brief

**Testing on Unified Dashboard**
- Enable unified dashboard via the tester plugin
- Go to `Site Kit settings` and click on `PageSpeed Insights`
- Click `visit the dashboard` link
- Verify that you are navigated to the dashboard `Speed` section
- Verify `#speed` is appended to the URL

**Testing when the Unified Dashboard is disabled**
- Disable unified dashboard via the tester plugin
- Go to Site Kit setting and click on `PageSpeed Insights`
- Click `visit the dashboard` link
- Verify that you are navigated to the dashboard Page Speed section
- Verify `#googlesitekit-pagespeed-header` is appended to the URL

## Changelog entry

* Update the behaviour of the PageSpeed's `visit the dashboard` link to scroll to the PSI widget when the user lands on the dashboard page.

**Comment by aaemnnosttv** [comment]
cc @felixarntz

**Comment by asvinb** [comment]
@aaemnnosttv I noticed that if we use the `#googlesitekit-pagespeed-header` in the URL, we are not scrolled to the section. I'am wondering whether it's because initially the element is not present and the browser cannot find it on load, thus it fails to scroll to the container. We can manually scroll once the page is loaded, however I'am not sure it's worth looking into it since we'll be rolling out the unified dashboard soon. Let me know what you think, i'll update the IB to cater only for unified dashboard.

**Comment by aaemnnosttv** [comment]
@asvinb hmmm, that makes sense. Maybe we can auto-scroll `onMount` in the component if the url hash matches? I would imagine we'd need to solve the same problem in the unified dashboard as well. Do we have an issue for this @tofumatt ?

**Comment by aaemnnosttv** [comment]
@asvinb the IB looks good as far as the link changes go. As for the scrolling, can we use the same approach as in https://github.com/google/site-kit-wp/issues/4367 for the unified dashboard?

**Comment by asvinb** [comment]
@aaemnnosttv IB updated, can you review?

Thanks!

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_Testing on Unified Dashboard_

- Within PageSpeed settings, I click the `visit the dashboard` link and are navigated to the dashboard Speed section
- Confirmed that `#speed` is appended to the URL
- Tested this on desktop and small screen sizes. 

<details>
 <summary>Screencast</summary>

https://user-images.githubusercontent.com/73545194/145578908-aeff9eab-73f1-4903-9a23-022d522e925d.mp4

</details>

_Testing when the Unified Dashboard is disabled_

- Within PageSpeed settings, I click the `visit the dashboard` link and are navigated to the dashboard Page Speed section
- Confirmed that `#googlesitekit-pagespeed-header` is appended to the URL.
- Tested this on desktop and small screen sizes.

<details>
 <summary>Screencast</summary>

https://user-images.githubusercontent.com/73545194/145578961-88e01802-94fb-4210-93e0-0f4edc77ac51.mp4

</details>
