### ISSUE TITLE
New PageSpeed Insights Tool URL changed behaviour of link on widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4381]
## Bug Description

On the footer of the PageSpeed Insights widget there is a link `View details at PageSpeed Insights`

When you are on the entity dashboard (Detailed Page Stats) and you click the link above, you are redirected to `https://pagespeed.web.dev/?utm_source=psi&utm_medium=redirect` I noticed that the link in the widget is pointing to `https://developers.google.com/speed/pagespeed/insights?url=https%3A%2F%2Fdomain.com%2Furl%2F` 

I was expecting the link to open a new window and the tool analyse the URL automatically.

It appears though that the PageSpeed Insights tool URL has changed, so a change is needed in Site Kit. 

![image](https://user-images.githubusercontent.com/73545194/142660029-32b54d2b-ca93-4452-a9b2-ac961c6a9991.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The base service URL for PageSpeed Insights should be changed from `https://developers.google.com/speed/pagespeed/insights` to `https://pagespeed.web.dev`
* The pagespeed report URL linked from the dashboard widget's `ReportDetailsLink` should be updated to `https://pagespeed.web.dev/report?url={url}`

## Implementation Brief

* Change the base URL at https://github.com/google/site-kit-wp/blob/d39b3573809a05bd77caf7e00171a84ee788ecdf/assets/js/modules/pagespeed-insights/datastore/service.js#L37 to the new PageSpeed URL: `https://pagespeed.web.dev`
* Update https://github.com/google/site-kit-wp/blob/d39b3573809a05bd77caf7e00171a84ee788ecdf/assets/js/modules/pagespeed-insights/components/common/ReportDetailsLink.js#L38 to add the param `path: 'report',` to the `getServiceURL` params, eg: `select( MODULES_PAGESPEED_INSIGHTS ).getServiceURL( { path: 'report', query: { url: referenceURL } } )`
* While we're updating URLs for PageSpeed Insights, it'd be worth updating these other URLs to the new `pagespeed.web.dev` URLS:
  * Change https://github.com/google/site-kit-wp/blob/d39b3573809a05bd77caf7e00171a84ee788ecdf/assets/js/googlesitekit/modules/datastore/__fixtures__/list.json#L73 to `https://pagespeed.web.dev`
  * Change https://github.com/google/site-kit-wp/blob/d39b3573809a05bd77caf7e00171a84ee788ecdf/includes/Modules/PageSpeed_Insights.php#L174 to `https://pagespeed.web.dev`

### Test Coverage

* Jest tests will likely need updating as a result of this change.

## QA Brief

* Check that the link is updated as per AC on the PageSpeed Insights widget on the SK Dashboard (`View details at PageSpeed Insights` link).
* Check that the link is updated as per AC on the SiteKit Settings --> Connected Services --> PSI widget (`See full details in PageSpeed Insights` link).

## Changelog entry

* Update the PageSpeed Insights links to go to the `pagespeed.web.dev` domain.

**Comment by aaemnnosttv** [comment]
cc @felixarntz

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by Utkarsh1504** [comment]
I would like to work on this issue

**Comment by mohitwp** [comment]
### **QA Update : ✅** 

**Verified:**
1) Link (`View details at PageSpeed Insights link`) updated as per AC on the PageSpeed Insights widget on the SK main Dashboard and on entity dashboard.(View details at PageSpeed Insights link).
**Screenshots :**
![PSI_URL_DB_1](https://user-images.githubusercontent.com/94359491/145404140-86d18a2f-fe2e-495e-94b7-ee5acf44e1b6.png)
![PSI_URL_DB_2](https://user-images.githubusercontent.com/94359491/145404143-ba03c64e-5968-4c38-938f-49df8a7c53f2.png)



2) Link (`See full details in PageSpeed Insights link`) updated as per AC on the SiteKit Settings --> Connected Services --> PSI widget.
**Screenshot:**
![PSI_URL_Settings](https://user-images.githubusercontent.com/94359491/145403639-4bc3fef8-e2da-4bc6-ad74-a88738ca6f12.png)
