### ISSUE TITLE
AdSense code appearing when setting to display code is disabled

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4389]
## Bug Description

In Adsense settings (`wp-admin/admin.php?page=googlesitekit-settings#/connected-services/adsense/edit`) the `Let Site Kit place AdSense code on your site` setting is disabled. I should not see any AdSense code on my site, but I do. 

```
<!-- Google AdSense snippet added by Site Kit -->
<meta name="google-adsense-platform-account" content="ca-host-pub-xxxxxxxxxxxxxxx">
<meta name="google-adsense-platform-domain" content="sitekit.withgoogle.com">
<!-- End Google AdSense snippet added by Site Kit -->
```
The code appears if you are logged in or out of your website. 

It is possible that this code is expected since AdSense is connected and the account is approved, but if it is, I am wondering if we should change the copy in AdSense settings? 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/23d2be3d-ed53-49a9-a802-d59693c8fc6d)

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/6748c977-04c2-4f7b-8e1b-768db0312d9e)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren – this is expected behavior as defined by the criteria for the addition of the platform tags. See the ACs for https://github.com/google/site-kit-wp/issues/3688
