### ISSUE TITLE
Adsense adds advertising blocks to everything, completely out of control

### ISSUE THREAD

**Issue by marcdobler** [google/site-kit-wp#439]
## Bug Description

This adds blocks of advertising from everywhere on the pages completely out of control, there is no way to manage those blocks, the placement seems to randomly position blocks of advertising and especially irrelevant in their positioning, like a middle of the main article list.

## Steps to reproduce

Go to any URL from that website: https://www.sixpiecesofeight.com

## Additional Context

 - PHP Version: 7.2
 - OS: Debian
 - Browser chrome
 - Plugin Version 1.0.0-beta.1.0.4
 - Device: Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@marcdobler Site Kit places Auto Ads code on your site, which serves ads based on suitable placements. You can however set some options from within your AdSense account as below, which will apply to your site, even with Auto Ads implemented via Site Kit:

**Control Ad Formats**: You can [restrict the ad formats](https://i.imgur.com/eP1XBKO.png) in use. 
**Use URL groups**: You can [create URL groups](https://support.google.com/adsense/answer/7627395?hl=en) to specify URLs (such as your homepage) to restrict the placement of ads. As an example you specify some URLs and then disable all ad formats in use for those URLs. These will overwrite your global ad format settings. 

If you are looking for more strict control over ad placements then you can use single ads units along with other ads plugins as opposed to Auto Ads via Site Kit. [Here is a guide](https://support.google.com/adsense/answer/7527509?hl=en) to serving ads on a WordPress site.

**Comment by marcdobler** [comment]
For restricting ad format already done told some parameter.

I have done configuration yesterday night but seems like doesn't change too much thing, those auto ads implementation really look like adware.

To give a real [example](https://imgur.com/a/FOXXu64) 

After I thought I can add my self to create a placement for ads

`<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-xxxxxxxxxxxxx"
     data-ad-slot="xxxxxxxxxx"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>`

But that doesn't work at all, but to add 6 auto-ads where it looks the most strange placement ever.

**Comment by jamesozzie** [comment]
@marcdobler The AdSense [community forum](https://support.google.com/adsense/community?hl=en) might be the best place to discuss the placement of ads via Auto Ads. You'll find AdSense experts and employees contributing to that support forum.
