### ISSUE TITLE
Improve User Experience when authorisation times out

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4390]
## Bug Description

I suspect this is outside of the Site Kit plugin, but wanted to create a ticket for awareness.  

Maybe one for @adamsilverstein?

If you do not login to your Google account when connecting a module within 10 minutes, a message appears.

`The state parameter is invalid or expired. This may happen for security reasons because you have taken longer than 10 minutes in the Site Kit setup process.`

![image](https://user-images.githubusercontent.com/73545194/142913939-bc66b1d6-9605-406a-88d0-1b967b06fde4.png)

I clicked back on the browser, and the authorisation page re-appeared.  I clicked 'continue' and then received another message. 

`Your temporary access code is invalid or expired. Please return to your WordPress site by cancelling below and retrying.`

As you can see from the screenshot, there isn't any button or link to cancel/retry. 

![image](https://user-images.githubusercontent.com/73545194/142913480-57a522a1-f313-40fe-a4dc-332e2529a4c1.png)

The only way the user can get out of the process is retype their URL into the browser and try connect the module. 

Only happened to me because I was in a meeting while setting up a test site, so not huge issue. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@wpdarren Thanks for catching that! For UI issues on the service like this, could you open an Asana task instead and ping Adam or me there please? The one here could then be closed.

**Comment by wpdarren** [comment]
Thanks @felixarntz and noted for future.  👍  For reference, here's the [Asana ticket ](https://app.asana.com/0/1185360131189553/1201428661290473/f)
