### ISSUE TITLE
Include the async attribute within the AdSense snippet

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4398]
## Bug Description

As discovered by [one user in the support forums](https://wordpress.org/support/topic/render-blocking-script-2/#post-15091761) the AdSense snippet as placed by Site Kit doesn't include the async attribute, which [is recommended if manually adding AdSense code to your site](https://support.google.com/adsense/answer/9274516). 

Note that the AdSense snippet was modified recently to the newer snippet code (#3783). Within this issue the sync attribute was included/proposed. 

_How it currently appears (Site Kit 1.46.0) below:_

![image](https://user-images.githubusercontent.com/41326532/143089724-76b2816f-566d-4dbd-a7e9-6adba21d690c.png)

How is should appear below - based on the [AdSense manual insertion guide:](https://support.google.com/adsense/answer/9274516)

![image](https://user-images.githubusercontent.com/41326532/143090028-fb634cbe-f205-4829-8c50-100e615867c6.png)

This was tested on Site Kit versions 1.44.0 - 1.46.0. Happy to test older versions if required. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense (non-AMP) snippet placed by Site Kit should include the `async` attribute (boolean, i.e. no attribute value), similar to how it's included in the [manual insertion guide](https://support.google.com/adsense/answer/9274516).

## Implementation Brief
* Using `includes/Modules/AdSense/Web_Tag.php`, within the `render` method, update `adsense_script_attributes` to include `'async' => true` 

### Test Coverage
* No new tests to be added.

## QA Brief

* Connect AdSense to a SiteKit property and allow SiteKit to insert the AdSense Snippet.
* View page source for the connected website. Check that the async attribute is added before the src attribute in the snippet as shown in the bug description above.

## Changelog entry

* Update the frontend AdSense code to load asynchronously.

**Comment by felixarntz** [comment]
@eclarke1 @FlicHollis This should be a tiny fix (estimate maximum 3), but it's somewhat a high priority enhancement. Can we add this to the current sprint? We can remove e.g. #2908 or #4209 instead.

If that's okay, please also add this to the upcoming 1.47.0 release, as it would be valuable to mark for inclusion there (to give it even "higher" priority timing-wise).

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by Abhishek-90** [comment]
Is the issue still open? I would like to work on it. Can any explain it properly, I am beginner in open source and this can be my first contribution.

**Comment by jamesozzie** [comment]
@Abhishek-90 While we have a solution in place for this many thanks for your proposal to assist. We expect to have this update included with the next plugin release.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

- The async attribute is added before the src attribute in the snippet as shown in the bug description above.

```
<!-- Google AdSense snippet added by Site Kit -->
 <script async="async" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7603478468516085" crossorigin="anonymous" type="text/javascript"></script>
 <!-- End Google AdSense snippet added by Site Kit -->
```
