### ISSUE TITLE
Oauth: Couldn't create brand

### ISSUE THREAD

**Issue by kristarella** [google/site-kit-wp#44]
**Describe the bug**
When trying to generate oauth credentials I get the following error:

> Couldn't create brand
> Request contains an invalid argument.

**To Reproduce**
1. In WordPress with SiteKit plugin installed Go to wp-admin/admin.php?page=googlesitekit-splash
2. Click on link "developers.google.com/web/sitekit"
3. Click "GET OAUTH CREDENTIALS"
4. Proceed until error appears

**Expected behavior**
Credentials to be generated and shown

**Screenshots**
<img width="876" alt="Screen Shot 2019-06-24 at 12 36 14 pm" src="https://user-images.githubusercontent.com/2031017/60012617-b21f0800-967c-11e9-836b-196afb4703d2.png">

**System Information (please complete the following information):**
 - PHP Version: 7.2.19
 - Browser: Chrome
 - Plugin Version: 1.0.0-beta.1
 - Device: MacBook

**Additional context**
- The same error occurs whether I use the prefilled data from the link in the WordPress settings page, or go directly to https://developers.google.com/web/site-kit/ and enter the info from scratch

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by felixarntz** [comment]
Hi @kristarella, and thanks for the report. Could you provide us with some more information: Which "Project Name" and "Application Name" did the page display before you clicked the button?

**Comment by jamesozzie** [comment]
Hi @kristarella. Did you encounter this issue again, or were you able to proceed with the setup?

**Comment by jamesozzie** [comment]
@kristarella I will close this issue as we have a duplicate similar open issue (#159) Feel free to reopen by providing us with additional information and we can hopefully assist.
