### ISSUE TITLE
Display a count of all connected sites on the Site Kit "Manage Sites" screen

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4406]
## Feature Description

For agencies or those with a large number of sites displaying the total number of connected sites would be useful to determine any users who may be reaching the [50 sites OAuth token limitation](https://developers.google.com/identity/protocols/oauth2#:~:text=There%20is%20currently%20a%20limit,not%20apply%20to%20service%20accounts.). (To access the Manage Sites page: [Site Kit dashboard > Click on the connected email > Manage Sites](https://i.imgur.com/70pYQXN.png))

For additional context in cases whereby there are users that have 50 connected sites the oldest connected site will become disconnected upon connecting site 51. While this is an OAuth limitation it's a common cause of frustration for users, who often end up opening support topics understandably unaware of why they're often being asked to reconnect Site Kit. 

![image](https://user-images.githubusercontent.com/41326532/143443323-5a609393-9be6-4b02-adb0-22efdf305228.png)

During the setup process it may also be useful to list the total connected sites, with a link to documentation that make users aware of the current OAuth limitations. At present they may only discover this by reaching out in the support forums when a site becomes disconnected.

Additional notes:
- The list of all sites connected in the "Manage Sites" page does list the connected sites in order of newest connected already
- There is [an internal task](https://app.asana.com/0/1185360131189553/1201229140014223/f) open in relation to seeking out the possibility of increasing the OAuth limit for the Site Kit project
- We've had poor plugin reviews from agencies ([example](https://wordpress.org/support/topic/not-robust-enough-for-agencies-or-managed-sites/)) who are understandably unaware of the OAuth limitations

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@bethanylang This may be something we could considering adding to documentation if not already on your radar.

**Comment by henrywright** [comment]
This count if displayed in the network admin area when you implement #276 would be useful for super admins as well

**Comment by bethanylang** [comment]
@felixarntz @adamsilverstein Per our discussion today, a few other suggestions to improve the UX on this screen:

- Sort sites by connection date from newest to oldest
- Add display of the connection date for each site
- Update the language at the top of the screen from:

_You gave Site Kit access to site(s) that you own, including data from Google services that is associated with those sites (for example, Google Analytics data).

Remove access for sites you no longer use or trust._

to (@marrrmarrr to review):

_You've given Site Kit access to the site(s) listed below, along with their associated Google service data (such as Analytics data). Click *Remove access* to remove permissions for sites that you no longer use or trust.

You are limited to a total of 50 site connections per Google account._

**Comment by aaemnnosttv** [comment]
@jamesozzie @bethanylang this isn't something actionable on the plugin side so let's move this internally and close this.

**Comment by bethanylang** [comment]
Closing per the above comment.
