### ISSUE TITLE
Design differences on widget title and subtitle for Unified Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4407]
## Bug Description

While QA'ing #4340 I noticed a few observations, which I understand are out of scope for that ticket. 

There are a number of differences between the titles/subtitles on the main and entity dashboard and figma designs. 

- Title: the font size, color and weight is different between dashboard and figma designs.
- Subtitle: the font size and color is different between dashboard and figma designs. It is hard to read currently.
- The line height between the title and subtitle is different between dashboard and figma designs.
- The line height between the subtitle and widget is different between dashboard and figma designs.

Looking at Monetization on the main dashboard, there's a larger space between the subtitle and the widget compared with other areas. It might be because I do not have any ad impressions.  @techanvil made an observation on what could be the cause [here](https://github.com/google/site-kit-wp/issues/4340#issuecomment-979318264)

![image](https://user-images.githubusercontent.com/73545194/143452924-b0a22809-46f0-40bb-a762-0dc1c08c49aa.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should not be a gap between the Monetization header and its widget context/area
* As [spotted by @techanvil here](https://github.com/google/site-kit-wp/issues/4340#issuecomment-979318264), `AdBlockerWarningWidget` should return `<WidgetNull />` instead of `null` to ensure the spacing is correct and an "empty" widget is not rendered

## Implementation Brief

* Replace https://github.com/google/site-kit-wp/blob/a608bcba230cf33c225b33730b15204aecfad5f6/assets/js/modules/adsense/components/dashboard/AdBlockerWarningWidget.js#L39 with `<WidgetNull />` to ensure the widget is not rendered when no AdBlocker is detected.

### Test Coverage

* No tests should need updating; VRTs might need updating.

## QA Brief

* Spacing on the AdSense dashboard should be in line with other widget context/areas, eg:

<img width="1221" alt="Screenshot 2021-11-29 at 14 55 05" src="https://user-images.githubusercontent.com/90871/143890197-34571caf-9930-4268-a1ce-3f649aea39fc.png">

## Changelog entry

* Fix visual gap on AdSense dashboard added by adblocker warning widget when no adblocker is detected.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
@kuasha420 @tofumatt @felixarntz are we just fixing the gap between the Monetization header and its widget context/area? 

Was wondering about the other areas in the ticket, i.e. font sizes, line heights, etc.   If these differences to the figma designs are expected please could someone confirm and I can make sure its included in our known issues list because these will be brought up in the bug bash. Thanks!

**Comment by kuasha420** [comment]
@wpdarren AC/IB doesn't mention changing the font styles, I'd think we can add that to Bug Bash as known issues.

**Comment by wpdarren** [comment]
@kuasha420 yes, I thought that might be the case, I will add as known issues. Thank you for clarifying!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Spacing on the AdSense dashboard should be in line with other widget context/areas
- Checked the widgets on desktop and smaller screen sizes.

![image](https://user-images.githubusercontent.com/73545194/145036141-6c898981-c8a0-4c1c-9c81-9e1824abfbf3.png)
