### ISSUE TITLE
caniuse-lite is outdated

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#4418]
## Feature Description

When I build assets, the `browserslist` package reports that the version of the `caniuse-lite` package in our `package-lock.json` file is outdated and we need to update it by running the `npx browserslist@latest --update-db` command.

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `caniuse-lite` package in the `package-lock.json` has the latest version.

## Implementation Brief

* Run the `npx browserslist@latest --update-db` command.

### Test Coverage

* N/A

## QA Brief

* Run the `npm view caniuse-lite version` command to see the latest version of the `caniuse-lite` version
* Run the `npm ls caniuse-lite` and confirm that the latest version is used.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
QA ✅
<img width="570" alt="Screen Shot 2021-12-08 at 3 09 16 PM" src="https://user-images.githubusercontent.com/373931/145310373-a57bda45-e120-4cd2-bb47-103c695b68bb.png">
