### ISSUE TITLE
Add AdSense link in 'Help' dropdown when service connected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4423]
## Bug Description

Prior to Unified Dashboard, when a user went to the AdSense module page, and clicked on the 'Help' icon, an entry to link to the help page for AdSense appeared in the dropdown.  Since we've removed the module pages, we now need to make sure that the link appears on the dashboard when AdSense is activated. 

The 'Get Help with AdSense' link should be included, pointing to https://support.google.com/adsense/#topic=3373519

![image](https://user-images.githubusercontent.com/73545194/143904917-f175c33d-2d6f-4bff-ba9b-d3f39863cb16.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the AdSense module activated, the [help link for AdSense](https://github.com/google/site-kit-wp/blob/e45ffe9f188e34457d4a8640565e0360f0536291/assets/js/components/module/ModuleApp.js#L58-L67) should always be included on the dashboard's help menu below the default/always-on items
    * This affects both unified and current dashboard layouts equally, including module pages essentially making the help menu consistent across all Site Kit screens

## Implementation Brief

Within `assets/js/components/help/HelpMenu.js`:

* When the `adsense` module is active (check using the `isModuleActive` selector), add the AdSense help menu item after the last rendered `HelpMenuLink`. The menu item can be copied from here:
https://github.com/google/site-kit-wp/blob/b81b1c347f19800693f046f11d544bfbed09ed86/assets/js/components/module/ModuleApp.js#L60-L65

Within `assets/js/components/module/ModuleApp.js` and `assets/js/components/setup/ModuleSetup.js`:

* Remove the conditionally rendered AdSense help menu items.

### Test Coverage

* Update any failing tests.

## QA Brief

- Go to the Site Kit dashboard
- Make sure you have `Adsense` service connected
- Toggle the `Help` dropdown
- Verify `Get help with AdSense` link is available in the dropdown list
- Disconnect `Adsense` service
- Verify `Get help with AdSense` link is **_NOT_** available in the dropdown list
- Verify the all the above in the non-unified dashboard as well

## Changelog entry

* Update the help menu to include the AdSense help menu item in all places when the AdSense module is active.

**Comment by aaemnnosttv** [comment]
@felixarntz one alternative here is that we could simply always add the item for AdSense to the `HelpMenu` regardless of unified dashboard or not rather than only adding it on the module page (i.e. making the current help menu consistent across all pages). Then all we'd need to do is wrap the added link with `withActive`. What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv That sounds reasonable to me. @marrrmarrr What do you think?

1. Should we show the AdSense help link when the AdSense module is active?
2. Or should we show the AdSense help link when the AdSense module is active _and_ the user is in the "Monetization" tab? 

I'm thinking we should go with 1. since 2. may make it too hard and unintuitive to find that link since if you don't see it when you're in another tab you may not go look there again.

**Comment by aaemnnosttv** [comment]
> 2\. Or should we show the AdSense help link when the AdSense module is active _and_ the user is in the "Monetization" tab?

@felixarntz This would be rather odd (as well as additionally complicated as you said) for a menu item to conditionally be added/hidden in the dropdown based on what section you are looking at. It would be better to add contextual help to that widget area/context instead.

Just to clarify # 1, my suggestion would be to include the AdSense help item in the Help Menu as part of the core list of menu items (as long as the module is active), regardless of which page you're on, or if the `unifiedDashboard` feature flag is enabled or not 🙂

**Comment by eclarke1** [comment]
@marrrmarrr @felixarntz could I kindly as for your thoughts on this one please, as it has been identified as a launch blocker for Unified Dashboard, so would be great to progress through if possible.

**Comment by FlicHollis** [comment]
Hi @marrrmarrr and @felixarntz just following up on @eclarke1 request above. We would like to get this completed this sprint as it has been identified as a launch blocker. Thanks so much!

**Comment by marrrmarrr** [comment]
I think the users who would benefit from this are the subset who have activated AdSense, regardless of which module / section they're on. So this is in line with the suggestion by @aaemnnosttv [in this comment](https://github.com/google/site-kit-wp/issues/4423#issuecomment-984737033).

**Comment by aaemnnosttv** [comment]
Hey @techanvil, I've just updated the AC after confirming the suggested changes I had from before. It's not a major change but is more of a global change rather than specific to the unified dashboard or screen. 

The current IB looks good overall but I'll send it back your way for revision in light of these changes. Apologies for this change after you added the IB!

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, that's no problem. I've updated the IB accordingly. Cheers

**Comment by aaemnnosttv** [comment]
Great, thanks @techanvil 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t @aaemnnosttv I've been looking at this ticket with @mohitwp and have an observation.  At the moment the Help dropdown has been removed from the module pages. I realise we are going to be launching unified dashboard, but that will be at the end of January, and rolled out gradually I'm assuming.  Is it correct that we have removed the help icon for module pages?

**Comment by aaemnnosttv** [comment]
## QA ❌ 

@wpdarren – the help menu should not be removed from anywhere it is currently being shown. The changes here are essentially just these two:

- Showing the extra help menu item for AdSense when it is active everywhere the help menu is shown
- Moving the AdSense help menu item to the bottom of the menu

Looking at the PR I can see that these were removed in a few places where they should not have been, so thank you for catching this.

Sending back to @hussain-t for a follow-up.

**Comment by hussain-t** [comment]
Apologies! I removed it based on the IB:
>Within assets/js/components/module/ModuleApp.js and assets/js/components/setup/ModuleSetup.js:
  Remove the conditionally rendered AdSense help menu items.

I will the help menu back and create a follow up PR :)

**Comment by hussain-t** [comment]
@aaemnnosttv I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/4617) and assigned this ticket to you for reviews.

**Comment by aaemnnosttv** [comment]
Thanks @hussain-t, that's been merged now 👍 

@wpdarren – back to you for another pass.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified:
1) Verified when UFD is enabled and AdSense is connected. (Dashboard and settings page) 
2) Verified when UFD is disabled and AdSense is connected. (Dashboard, Settings, and AdSense Page)
3) Verified when UFD is enabled and AdSense is disconnected. (Dashboard and settings page) 
4) Verified when UFD is disabled and AdSense is disconnected. (Dashboard, Settings, and AdSense Page)

cc @wpdarren 

<details>

![ad1](https://user-images.githubusercontent.com/94359491/148220603-8d0854c3-df0b-4a62-863b-3ac378452fc7.png)
![ad2](https://user-images.githubusercontent.com/94359491/148220609-2e379a16-1391-4bea-b250-40c22f8cc839.png)
![ad3](https://user-images.githubusercontent.com/94359491/148220611-eaaf6434-8bbe-4fd4-827c-dd9f802241bc.png)
![ad4](https://user-images.githubusercontent.com/94359491/148220615-0bd260ab-ec42-4589-8564-076eb2734cd6.png)
![ad5](https://user-images.githubusercontent.com/94359491/148220616-21985fda-feb3-45c3-88e0-560b01fe52ec.png)

</details>
