### ISSUE TITLE
Update Pull Request Template

### ISSUE THREAD

**Issue by mitogh** [google/site-kit-wp#4424]
## Feature Description

The main idea behind this change is to take advantage of Github, expand of issues as right now the current template for Pull Requests references the issues in the same line of the text, if we instead use a list format we would gain some expansion to have quick details of the issue title.

Example:

![143803427-a1364de5-2a72-42c2-b659-1c6a41d51703](https://user-images.githubusercontent.com/3921289/143927910-73397d6d-e20c-48f1-ad1f-c16525dd4a37.png)

The image contains 2 links the first one is the link expanded when used inside of a list (within markdown) the second example is an inline text, used in the current format.

**Example of how it would look like**

PR with the proposed change:

- #4414 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The pull-request template should be adjusted so that the issue is referenced on its own line in a bullet point, like so:
```
Addresses issue:

- #
```

## Implementation Brief

* Merge #4414.

### Test Coverage

* N/A

## QA Brief

* Verify that when creating a new pull-request the template has the place to put the issue reference (`#...`) in a new line behind a bullet point marker (`- `).

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Thanks @mitogh! I opened a corresponding task for us to modify the changelog generator script here: https://app.asana.com/0/1185360131189553/1201440994101251/f

Let's time these things so that we only move the issue here forward once the changelog script has been adjusted accordingly. cc @aaemnnosttv

**Comment by mitogh** [comment]
Thank you @felixarntz

**Comment by felixarntz** [comment]
@mitogh @aaemnnosttv This can now move forward as the plugin changelog script is being adjusted accordingly (internal).

**Comment by felixarntz** [comment]
@aaemnnosttv Assigning to you to eventually merge.

**Comment by aaemnnosttv** [comment]
Merged and QA ✅ 

New PRs use the updated template which expands the referenced issue 👍 

![image](https://user-images.githubusercontent.com/1621608/148048087-17d24916-c33c-40a3-aa2c-84c83b960db9.png)
