### ISSUE TITLE
URL search should show current entity (title) initially when in the entity dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4426]
Per https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe/%5BMVP%5D-Unified-Dashboard?node-id=1330%3A9080, a few late updates have been made to give the URL search and entity dashboard header for the `unifiedDashboard` a better user experience. This is the first out of three issues which replaces #4147. The others are:
* #4427
* #4428

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

With the `unifiedDashboard` feature flag enabled:
* When landing on the entity dashboard (and a current entity is present), the URL search in the header should be "open" right away, and it should be populated with the title of the current entity.
    * In other words, this should be the initial experience, and the user shouldn't need to open the URL search or do anything to see that information in there.
    * It causes a consistent experience when landing on the entity dashboard from having typed and selected something in the URL search before. While this is not technically applicable when landing on the entity dashboard from a direct link, it is still acceptable to have open in that case as well, and we shouldn't make a differentiation about that for now - i.e. the URL search on the entity dashboard should behave like that in _any_ condition.
    * Note that the URL search endpoint (`core/site/data/post-search`) is limited in what types of content it covers, so the current entity may actually not be among "real" results the user could get from that endpoint. That is somewhat of a limitation of that endpoint, and this issue needs to enforce that the current entity title shows up in there initially (and its URL for the internal value to submit), even if it is otherwise impossible to get to it through URL search (in that case, that content can only be reached via a direct link).

## Implementation Brief
* Using `assets/js/components/EntitySearchInput.js`,
	* Check if we are on the entity dashboard by checking whether `viewContext` is set to `VIEW_CONTEXT_PAGE_DASHBOARD`. If this is the case, set `isOpen` to `true` upon component mount via the `useMount` hook.
* Using `assets/js/components/PostSearcherAutoSuggest.js`,
	* Get the current entity title by querying the `core/site` data store via the `getCurrentEntityTitle` selector.
	* Check if the `unifiedDashboard` feature flag is enabled via the `useFeature` hook.
	* Using the `useEffect` hook, with the entity title as dependency, set `searchTerm` to the title if it's not null.
	* If `unifiedDashboard` is enabled:
		* Add the `value` prop to `ComboboxInput` with `searchTerm` as value.
		* Add another condition where we check whether `debouncedValue` is empty, to check whether `debouncedValue` is different from the current entity title, which will prevent the API request from firing.
		* Update  `onSelectCallback`, to set `searchTerm` to `foundMatch.post_title` when a match is found. This will update the input text to the selected option, else upon selecting an item from the list of suggestions, the selected text will not be displayed in the input text.
		* Add another condition to display `noResultsMessage` and the surrounding wrapper by adding whether `debouncedValue` is different from the current entity title.

### Test Coverage
* No new tests to be added.

## QA Brief
* Enable the `unifiedDashboard` feature flag.
* Go the main dashboard and search for a post/page via the search form.
* You will be redirected to the entity dashboard.
* Check if the search bar at the top is opened by default, with the "searched" entity filled in. 

## Changelog entry

* Update the URL search component to display the current entity title by default.

**Comment by eugene-manuilov** [comment]
@asvinb no need to manually try to find the current entity URL and title. We can get it using `getCurrentEntityTitle` and `getCurrentEntityURL` selectors from the `core/site` datastore.

**Comment by asvinb** [comment]
Thanks @eugene-manuilov . I guess I overcomplicated things. IB updated, can you check?

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb, but I think it shouldn't be set as a placeholder. The entity title should be set as the value of the search input box.

**Comment by asvinb** [comment]
@eugene-manuilov I originally saw some issues when trying to set the value of the search input. After taking another look with fresh eyes, I was able to find a solution. Can you review once again?

Thanks!

**Comment by eugene-manuilov** [comment]
IB seems to be right, @asvinb. The only thing to mention is that all changes in the `PostSearcherAutoSuggest` component should happen when the `unifiedDashboard` feature flag is enabled.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by asvinb** [comment]
> IB seems to be right, @asvinb. The only thing to mention is that all changes in the `PostSearcherAutoSuggest` component should happen when the `unifiedDashboard` feature flag is enabled.

@eugene-manuilov After taking another look, maybe checking for the `unifiedDashboard` flag is redundant for the proposed changed in `PostSearcherAutoSuggest`  since the latter will not be displayed on entity pages. Since it will be rendered only on the main dashboard, I think if we just check for the entity title should be enough. What do you think?

**Comment by eugene-manuilov** [comment]
Actually, you are right, @asvinb. Good catch. Yes, let's go without the unified dashboard flag check then.

**Comment by asvinb** [comment]
@eugene-manuilov Over to you for final review. E2E tests are passing now.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Searched for a post/page via the search form and when redirected to the entity dashboard, the search bar at the top is opened by default, with the searched entity filled in.
- Checked this on desktop and smaller screen sizes to make sure that the behaviour was the same.  - [Screenshot](https://user-images.githubusercontent.com/73545194/145045532-58ca9589-c6f1-4566-bef9-29c5518d53b1.png)

**Comment by mitogh** [comment]
Adding some comments found during the smoke test @wpdarren 

https://user-images.githubusercontent.com/3921289/146619293-90283296-f0df-4bdd-a1e0-8f18b1d46f3f.mp4
