### ISSUE TITLE
Implement new entity dashboard header

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4428]
Per https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe/%5BMVP%5D-Unified-Dashboard?node-id=1330%3A9080, a few late updates have been made to give the URL search and entity dashboard header for the `unifiedDashboard` a better user experience. This is the third out of three issues which replaces #4147. The others are:
* #4426
* #4427

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Originally, an `EntityHeaderBanner` component was implemented as part of the `unifiedDashboard` feature to indicate which current entity the user is looking at on the entity dashboard. This design has now been discarded in favor of a new design that takes less space and is displayed in a more appropriate location.
* The `EntityHeaderBanner` component and its usage should be entirely removed.
* Instead, a new component (e.g. just called `EntityHeader`, since it's technically no longer a banner) should be implemented that follows [the entity header UI right below the pills in this Figma design](https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe/%5BMVP%5D-Unified-Dashboard?node-id=1330%3A9083) (see [this Figma design for mobile](https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe/%5BMVP%5D-Unified-Dashboard?node-id=1330%3A12574)):
    * There should be a "Back to dashboard" link on the left that points back to the main dashboard.
    * The current entity title and URL should be displayed on the right.
    * If there is no current entity, it shouldn't be displayed at all.
    * The component should have an explicit gray background and drop shadow when scrolled past so that it overlaps the other content when scrolled down (see [here in the Figma file](https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe/%5BMVP%5D-Unified-Dashboard?node-id=1330%3A9909)). In other words, the component should also be displayed fixed (on both desktop and mobile), and when scrolled past should overlap the content, hence it needs the same gray as in the overall background color.
* The new component should be integrated into the entity dashboard like in the Figma file (right below the pills navigation).
* Extra requirement: The `BannerNotifications` must never be displayed within the entity dashboard, but it is implemented like that now. This was likely a misunderstanding in a previous issue, `BannerNotifications` should only be present on the main dashboard (the same way it is today).

## Implementation Brief
* Create `assets/js/components/EntityHeader.js` which exports the `EntityHeader` functional component.
	* It should largely take the code from `assets/js/components/EntityHeaderBanner.js` with the following changes:
		* `googlesitekit-entity-header-banner-*` classes are replaced with `googlesitekit-entity-header-*` classes.
		* "Return to dashboard" should be updated to "Back to dashboard"
		* Remove `Detailed page stats for:` text.
	* Rename `assets/sass/components/global/_googlesitekit-entity-header-banner.scss` to `assets/sass/components/global/_googlesitekit-entity-header.scss` and update class names within it.
	* Style `EntityHeader` as per the Figma designs on small and large screens. Most notable changes are:
		* The "Back to dashboard" button is visible across all breakpoints. Previously it was hidden on small screens.
		* The content is always side by side across all breakpoints.
			* Use `display: flex` and `justify-content: space-between`
		* Review font sizes and spacing across all breakpoints.
		* On small screens, the current entity title is truncated with ellipsis and is on a single line. This is done by using the following CSS on the element:
			```css
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
			```
		* `EntityHeader` must be sticky, taking into account the `Header` and `DashboardNavigation` components' heights.
		* `EntityHeader` has a solid background (#f0f0f1) and drops shadow at the bottom when the page is scrolled down.
* Using `assets/js/components/DashboardEntityApp.js`,
	* Remove the `subHeader` prop of the `Header` component.
* Using `assets/js/components/Header.js`,
	* Add `EntityHeader` after `DashboardNavigation`.
* Delete `assets/js/components/EntityHeaderBanner.js` and remove references to it.

### Test Coverage
* No new tests to be added.

## QA Brief
* Turn on the Unified Dashboard feature flag and search for an entity using the search bar in the header.
* Check the new header below the Dashboard Navigation Chips is as per the Figma designs mentioned in the AC for Desktop and Mobile.
* Ensure the Header correctly 'sticks' on all different screen types and has a drop shadow on scroll.
* Test with pages that have a long title and URL link in the header. Make sure the ellipsis (...) appears at the end of a long title. For the URL, it should appear immediately after the domain name (`www.example.com/...a-very-long-url`). Test this on all screen widths.

## Changelog entry

* Implement new UI for entity dashboard header containing title and URL.

**Comment by eugene-manuilov** [comment]
> The component should have an explicit gray background so that it overlaps the other content when scrolled down (see here in the Figma file). In other words, the component should also be displayed fixed (on both desktop and mobile), and when scrolled past should overlap the content, hence it needs the same gray as in the overall background color.

@felixarntz @marrrmarrr, looking at the Figma file, it feels like widgets pass through the gray background surface. This is against Material UI principles for surfaces: https://material.io/design/environment/surfaces.html. Ideally, this component shouldn't be sticky or it should change its behavior when it becomes sticky... For example, when it becomes sticky, we can lift it up and change it to be a banner with the shadow at the bottom. :thinking:

What do you think?

**Comment by felixarntz** [comment]
@eugene-manuilov Fair point, although I don't think I can judge the best behavior to move forward with here. You could argue the gray background surface makes it part of the overall header element - although I agree with you it looks like it's below the header rather than part of the sticky header.

@samitron7 Can you please review the above and confirm whether we should move forward with the "background-gray" overlaying the widgets when scrolling?

**Comment by samitron7** [comment]
Ok to raise it up and add a drop shadow but we definitely want to make that sticky as the back to the dashboard affordance is there.

**Comment by felixarntz** [comment]
@eugene-manuilov The Figma file has been updated to include a drop shadow on the entity header when it is "scrolled past", and the ACs now mention that as well. IB overall ✅  - maybe worth adding a note on the drop shadow though (it should only be there when scrolled past, but not when on top of the page).

**Comment by eugene-manuilov** [comment]
@felixarntz, looks good to me. I have adjusted IB a little bit to mention the shadow piece.

**Comment by eugene-manuilov** [comment]
@felixarntz can you also check the #4528 PR? I have left some comments regarding styles, would be nice to have your feedback as well.

**Comment by eugene-manuilov** [comment]
@felixarntz do you mind reviewing #4528 as well?

**Comment by felixarntz** [comment]
@jimmymadon Excellent work!

I've just updated the changelog you had added here, as it should always be only one bullet point. Also adding that is typically responsibility of whoever merges the PR, so don't bother adding that in the future on issues for your own PRs. What _is_ crucial to add though is the QA Brief, can you please provide that here? :)

**Comment by jimmymadon** [comment]
@felixarntz Oops - I added my QA Brief to the Change-log section by mistake (hence the 3 points in Change-log). Have re-added the QA Brief back to where it should be! Thanks!

**Comment by felixarntz** [comment]
@jimmymadon Ahh - yeah that way it makes more sense :)

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@jimmymadon I have a few observations which could be Figma design related but wanted to check. 

1. On desktop, the `title of the page` is in Google Sans but the Figma file is Roboto. 

![image](https://user-images.githubusercontent.com/73545194/148050935-a82a8c3c-2d18-4733-9f01-95d00fb23ee1.png)

2. On mobile and desktop, the URL font size 11px as per the Figma but in my opinion it needs to be bigger. It is hard to read. 

![image](https://user-images.githubusercontent.com/73545194/148057877-8c68a0e6-768d-4bfd-ae86-9f1a4a27e83d.png)

3. On mobile the `title of the page` is in Roboto but the Figma design is Google Sans. 

4. On mobile the `Back to Dashboard` link is Roboto but the Figma design is Google Sans.

**Verified:**

- The EntityHeaderBanner component and its usage is removed.
- There is a "Back to dashboard" link on the left that points back to the main dashboard.
- The current entity title and URL is displayed on the right.
- The component has a gray background and drop shadow when scrolled past so that it overlaps the other content when scrolled down.
The new component is integrated into the entity dashboard, below the pills navigation.
- The BannerNotifications are not displayed within the entity dashboard.
- Tested this on desktop and mobile.

**Comment by jimmymadon** [comment]
@wpdarren Thanks for the feedback!

I have updated the fonts to match the Figma designs. (Point 3 mentions that On mobile the title of the page is Google Sans, but it is in Roboto in the Figma design).

I too felt that the Title and URL on mobile are tiny (11px and 10px respectively) and the URL on desktop (11px) is tiny too. I can increase URL for desktop to 12px which makes it look better. However, for mobile, I will have to increase both the Title and URL as the Title should always be larger than the URL to have the effect as per the design. Can I increase these to say 14px and 12px - or what should the final sizes be for all fonts?

**Comment by wpdarren** [comment]
@jimmymadon I am happy with those suggestions but I feel @Pratheep-lab should confirm that he's happy with this.

**Comment by Pratheep-lab** [comment]
Thanks for tagging me in @wpdarren. Proposed changes sounds good but I want to know if we have already defined any typography guidelines for elements like H1, H2, paragraph sizes in story book or code? So we can reuse it. Ideally, yes 11 px is not recommended. @jimmymadon ? 

And once the changes have been done, please share a screenshot here for review.

**Comment by jimmymadon** [comment]
@Pratheep-lab In Storybook, we have an [external link](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global--links) which is what we are using for the URL, but the Figma design uses a different colour and size.

Anyways, I also found some [standard typography styles](https://github.com/google/site-kit-wp/blob/487c88b63659dd74ddfe5954eb9edbf48de2de73/assets/sass/config/_variables.scss#L279-L305) in our code and have used them to proceed with increasing the font sizes. On mobile, I have increased the `Back to Dashboard` label size to 14px as well which makes the header look consistent (image 1 vs image 2 below). Let me know if this is fine or if I should revert.

On Mobile (with increased font of Back to Dashboard): 
<img width="482" alt="mobile-without-back" src="https://user-images.githubusercontent.com/1721319/148245062-9079e6b0-1e75-477a-b5d6-3b07f13699c3.png">

On Mobile (with increased font of Back to Dashboard) - Latest version: 
<img width="495" alt="mobile-with-large-back" src="https://user-images.githubusercontent.com/1721319/148244882-aedfe582-588c-4eb9-8c9a-73ebd856db6e.png">

On Desktop:
<img width="1475" alt="desktop" src="https://user-images.githubusercontent.com/1721319/148244374-56618cf0-2743-4433-a5b8-80e93e8f486e.png">


@eugene-manuilov On a separate note, I have decided to remove the protocol/www from the URL as after increasing the font size of the URL, it is possible that the full domain name is still too long to fit. 
Without Normalizing:
<img width="386" alt="without-normalizing" src="https://user-images.githubusercontent.com/1721319/148244642-48ffb1bf-52b2-41a7-b6eb-959d406b1a32.png">
With Normalizing:
<img width="381" alt="mobile" src="https://user-images.githubusercontent.com/1721319/148244325-8359c2a0-ee3d-417f-a88d-0537f6f46e51.png">

**Comment by jimmymadon** [comment]
@felixarntz Could you please have a look at the changes in my previous comment - if removing the protocol/www when shortening URLs is fine? Thanks!

**Comment by Pratheep-lab** [comment]
@jimmymadon Figma designs seem to be a little inconsistent with the usage of the font sizes but the changes you have done looks good. It will look better if we make the title of the page medium text from regular Google Sans.
 
On a different note, the spacing to the left of the 'Back to dashboard' is way more than the spacing given to the right of 'Sample Page'. They should be the same.

**Comment by jimmymadon** [comment]
@Pratheep-lab Thanks for the feedback. I have changed the font for the Page text and equalised the spacing as you suggested. This is how the header looks now:

<img width="379" alt="2022-01-07_mobile" src="https://user-images.githubusercontent.com/1721319/148553654-10c6d54b-0562-40ea-9e78-d2f90fb92838.png">
<img width="1322" alt="2022-01-07_desktop" src="https://user-images.githubusercontent.com/1721319/148553668-2834357b-b973-4902-bfdf-7860a945ac07.png">

**Comment by jimmymadon** [comment]
@felixarntz Just wanted to get your approval on the above minor font and font-size changes as well as removing the protocol/www when shortening URLs [as shown in this comment.](https://github.com/google/site-kit-wp/issues/4428#issuecomment-1005833739) Thanks!

**Comment by felixarntz** [comment]
@jimmymadon I think this mostly makes sense, I only have two other remarks:
* The "Back to dashboard" text is 14px on very small viewports, but then 16px elsewhere. That makes sense to me. However, the page title is always 14px, even on those larger viewports. I think it would make more sense if those two had the same size throughout, also since we don't have anything I believe that uses 14px size on larger viewports. It makes the title more readable on desktop as well.
    * If we agree on this, the takeaway would be to make the page title 16px whenever the "Back to dashboard" text is 16px (and leave it at 14px when the "Back to dashboard" text is 14px).
* Instead of stripping the protocol and www prefix, I think it would be better to strip the protocol and domain entirely if the whole URL doesn't fit. Site Kit typically only shows data for one domain anyway, and not showing that here would even be in line with how it is for example in the "Popular Pages" widget on the main dashboard. So I think we can simplify this to first remove the entire protocol and domain.
    * If we agree on this, the takeaway would be to first remove the entire protocol and domain if the URL doesn't fit, and _then_, if it still doesn't fit, shorten further as we do already now.

@Pratheep-lab Let me know your thoughts on this as well.

**Comment by jimmymadon** [comment]
@felixarntz I like both those suggestions. Will make the requested changes.

**Comment by Pratheep-lab** [comment]
Yes, both sound good to me. Happy to review the screenshots @jimmymadon

**Comment by jimmymadon** [comment]
On desktop:
<img width="1741" alt="Desktop" src="https://user-images.githubusercontent.com/1721319/149182622-cf98f19a-e70f-4902-9b99-519fd784073a.png">

On mobile:
<img width="488" alt="Mobile" src="https://user-images.githubusercontent.com/1721319/149182634-8f2313d2-250b-4db5-9be8-6397b4527a4f.png">

**Comment by Pratheep-lab** [comment]
LGTM! A minor thing that you might have probably taken care of is when the page title is really long, are we truncating it or making it into two lines on the mobile version? So nothing overlaps in a weird way.

**Comment by jimmymadon** [comment]
@Pratheep-lab Yup, we add an ellipsis (...) at the end: 
<img width="482" alt="Screenshot 2022-01-12 at 16 52 50" src="https://user-images.githubusercontent.com/1721319/149185341-d79a5ba5-405b-41ee-a074-3edd7fcd65d3.png">

Thanks for the feedback. Will move this to CR now.

**Comment by jimmymadon** [comment]
@tofumatt Thanks for the feedback. Have implemented your requested changes. Just a note on the aria-labels behaviour:

1. If I do not add the `aria-label` explicitly, it uses the child {url} like you mentioned, which is the shortened URL that is displayed on the page. It doesn't truncate the aria-label further when I tested this using long URLs. So not sure why it adds its own ellipsis in your screenshot.
<img width="920" alt="Screenshot 2022-01-13 at 10 57 09" src="https://user-images.githubusercontent.com/1721319/149318341-efba8eba-957f-4c4a-8e78-c8c81d902f4f.png">
<img width="919" alt="Screenshot 2022-01-13 at 10 02 35" src="https://user-images.githubusercontent.com/1721319/149318383-8067bf67-b9e5-4a5d-83c1-9b9efc5feabe.png">

2. If I explicitly set `aria-label={entityURL}`, it will have the full URL in the aria-label but the truncated form is displayed on the page.
<img width="940" alt="Screenshot 2022-01-13 at 10 56 34" src="https://user-images.githubusercontent.com/1721319/149318502-dea87d40-a9f8-48d0-bedc-ebc95852d8e4.png">

I have explicitly added the aria-label for now which does behaviour 2 for me above.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The EntityHeaderBanner component and its usage is removed.
- There is a "Back to dashboard" link on the left that points back to the main dashboard.
- The current entity title and URL is displayed on the right.
- The component has a gray background and drop shadow when scrolled past so that it overlaps the other content when scrolled down.
- The new component is integrated into the entity dashboard, below the pills navigation.
- The BannerNotifications are not displayed within the entity dashboard.
- Tested this on desktop and mobile.

Additional styling changes:

- The page title is 16px whenever the "Back to dashboard" text is 16px (and at 14px for mobile).
- When the entire protocol and domain URL is removed when it doesn't fit, and if it still doesn't fit, it's shorten further. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/149331011-ea819cf5-5f18-41bc-9628-e1c5825f2bfb.png)

![image](https://user-images.githubusercontent.com/73545194/149331027-38cee3d8-7da9-42f2-ab96-21c7085d9643.png)

![image](https://user-images.githubusercontent.com/73545194/149331053-1ed95020-880f-4dcf-b10f-2adbe0d5a3c6.png)

![image](https://user-images.githubusercontent.com/73545194/149331080-e8407a91-b70b-405f-96b7-9974a0daf0cc.png)

</details>

Looks much better, nice work @jimmymadon 👍
