### ISSUE TITLE
Update file naming convention for minified assets

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4436]
## Feature Description

Currently our filenames for built assets use a format like `name(-hash?).(css|js)` which generally works well. There are however some optimization plugins that tend to cause problems with Site Kit when they attempt to further/re-optimize our assets. One simple thing we can do to avoid this problem is to name our minified assets similar to WordPress core with an added `.min` before the extension. Popular optimization plugins such as WP Rocket exclude files named in this way automatically ([cite](https://github.com/wp-media/wp-rocket/blob/93af148b0891ddd5d08ed2d41dd6c7100c26761c/inc/Engine/Optimization/Minify/JS/Minify.php?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L37-L42)).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Built CSS and JS files should have a `.min` prefix added to their resulting filenames when minified (i.e. [`mode === production`](https://v4.webpack.js.org/configuration/optimization/#optimizationminimize))  
E.g. `foo-a0b1c2d3e4f5.js` would become `foo-a0b1c2d3e4f5.min.js` where `a0b1c2d3e4f5` is the content hash applied by the manifest plugin.
* The full file name should be managed by the generated asset manifest as it is today (we should have no checks outside of webpack to rewrite the extension, etc)

## Implementation Brief
* Using `webpack.config.js`,
	* Add `.min` to filenames where `mode === 'production'` and anywhere there is a `[contenthash]` or `[chunkhash]` used. This applies to JS and CSS files.
		* For e.g:
			* `[name]-[contenthash].js` should be updated to `[name]-[contenthash].min.js`
			* `[name]-[chunkhash].js` should be updated to `[name]-[chunkhash].min.js`
			* `googlesitekit-vendor-[contenthash].js` should be updated to `googlesitekit-vendor-[contenthash].min.js`
			* `/assets/css/[name]-[contenthash].css` should be updated `/assets/css/[name]-[contenthash].min.css`

### Test Coverage
* No new tests to be added.

## QA Brief

* Use a production ZIP with the latest branch from `develop` or run `npm run build`
* Open the Console to inspect the network requests
* Filter by type JS (Repeat with Filter by CSS)
* Enter the path of the plugin in order to filter only assets of the plugin `wp-content/plugins/site-kit`
![2021-12-12_11-49](https://user-images.githubusercontent.com/3921289/145723600-a684e8da-16f2-464c-83ef-8c0b64130ca5.png)

* Reload the page after `npm run build` process has been completed or after the plugin has been activated with the production version from develop.
* Observe the page and modules are working as expected and that all the assets (JS and CSS) contains the `min.`  suffix before the file extension.

## Changelog entry

* Update production assets to include a `.min` suffix in the filename.

**Comment by jamesozzie** [comment]
Along with WP Rocket I'm aware Autoptimize also don't include any JS files for minification that end with a .min.js extension ([ developer reference](https://wordpress.org/support/topic/plugin-site-kit-ha-detectado-error-en-una-entrada-de-mi-blog/)). 

Note also that a naming convention change may also address the below newly created issue: 
https://github.com/google/site-kit-wp/issues/4449

**Comment by aaemnnosttv** [comment]
> * Add the `.min` prefix to filenames where `mode === 'production'`. This applies to JS and CSS files.

@asvinb this is indeed what we want to do at a high-level but I think we need a little more clarity as to where this change is needed. We can probably generalize that this should be added (as a suffix not a prefix 😉 ) anywhere there is a `[contenthash]` or `[chunkhash]` used. I _think_ that would cover everything.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by mitogh** [comment]
Looks like there are 2 scripts that based on comments from WebPack does not require any optimization, are we looking to leave those files as they are:

- https://github.com/google/site-kit-wp/blob/main/webpack.config.js#L330
- https://github.com/google/site-kit-wp/blob/main/webpack.config.js#L332

@aaemnnosttv  @asvinb @jamesozzie

**Comment by tofumatt** [comment]
QA ❌ 

Looks like the `i18n.js` file isn't being served with the `.min` suffix:

<img width="1377" alt="Screenshot 2021-12-14 at 19 32 00" src="https://user-images.githubusercontent.com/90871/146066983-cd6a8bf5-2306-4da4-934c-77528896d1fc.png">

This can be observed in the QA screenshot above as well.

This is the case on the main site/when loading the adminbar as well:

<img width="865" alt="Screenshot 2021-12-14 at 19 34 41" src="https://user-images.githubusercontent.com/90871/146067159-6471f613-ea15-4a19-97db-8ac18c8eb3cc.png">

But everything else looks good. Looks like we need to add this logic to that file. Probably makes sense to add it to both files here: https://github.com/google/site-kit-wp/blob/ebd4273fcfc504bb51afa13cc1ea18d48e98d7fd/webpack.config.js#L363-L368

**Comment by tofumatt** [comment]
@aaemnnosttv Can you verify that [`i18n.js` and `analytics-advanced-tracking.js`](https://github.com/google/site-kit-wp/blob/ebd4273fcfc504bb51afa13cc1ea18d48e98d7fd/webpack.config.js#L363-L368) don't need to be modifed by this issue? That's what the IB implies, but I just want to make sure, as `i18n.js` won't have the `min.js` suffix here, but it's definitely being optimised, so it seems odd not to label it:

<img width="1364" alt="Screenshot 2021-12-14 at 20 13 06" src="https://user-images.githubusercontent.com/90871/146072429-cc2799bc-b6dd-4c97-9598-2721edceb596.png">

**Comment by aaemnnosttv** [comment]
@tofumatt – the `analytics-advanced-tracking` script in particular is never loaded as an external script so it's irrelevant for this one. The `i18n` script though is being optimized like you said so I think it makes sense to include here. More importantly, is that we want to ensure that this script is not "hijacked" by optimization plugins which is the main underlying motivation here.

While we're at it, we should add the same hash to these filenames as well for consistency and cache safety (again this is only really relevant for our i18n module). We don't need to do anything special for it other than include the same Manifest plugin+args we use for other entries as the relevant code elsewhere already uses the manifest to get the proper filename 👍 

I'll open a quick PR for this as there is nothing more to do after I checked that it works 😄

**Comment by tofumatt** [comment]
I reviewed this small change, but in doing so QA'd the original issue as well, so marking this now as QA ✅
