### ISSUE TITLE
Add icons to Unified Dashboard navigation

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4438]
## Feature Description

Icons should be added for each chip in the dashboard navigation component on the Unified Dashboard as shown in the [visual design](https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe?node-id=855:4304#109627477). 

![image](https://user-images.githubusercontent.com/73545194/144269866-b56bbcb8-b97a-405b-ae7f-c9a2b8372e0c.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Each `Chip` in the `DashboardNavigation` component should include its respective icon per the design
* New svg icon files should be added for each icon under `assets/svg`
* Icons should inherit the current color of the Chip when selected (or not)

<details>
	<summary>Traffic</summary>

Equalizer
```xml
<svg width="18" height="16" viewBox="0 0 18 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M7 0L10.9714 4.05312e-05V16L7 16V0ZM0 8.00004H4V16H0V8.00004ZM18 5.00004H14V16H18V5.00004Z" fill="currentColor"/>
</svg>
```
</details>
<details>
	<summary>Content</summary>

Ballot
```xml
<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M18 16V2C18 0.9 17 0 15.7778 0H2.22222C1 0 0 0.9 0 2V16C0 17.1 1 18 2.22222 18H15.7778C17 18 18 17.1 18 16ZM9 7H14V5H9V7ZM16 2H2V16H16V2ZM4 4H8V8H4V4ZM14 11H9V13H14V11ZM4 10H8V14H4V10Z" fill="currentColor"/>
</svg>
```
</details>
<details>
	<summary>Speed</summary>

Speed
```xml
<svg width="20" height="16" viewBox="0 0 20 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M18.3779 4.54281L17.1459 6.39721C17.74 7.58309 18.0309 8.89797 17.9924 10.224C17.954 11.55 17.5874 12.8458 16.9255 13.9952H3.0429C2.18267 12.5018 1.82622 10.7707 2.02639 9.05859C2.22656 7.34647 2.9727 5.74449 4.15419 4.49011C5.33569 3.23574 6.88964 2.39576 8.58567 2.0947C10.2817 1.79364 12.0295 2.04753 13.5701 2.81872L15.4231 1.5858C13.5365 0.375141 11.2987 -0.167357 9.06761 0.0450785C6.83654 0.257514 4.74112 1.21261 3.11652 2.75759C1.49192 4.30257 0.432011 6.34816 0.106336 8.56717C-0.219339 10.7862 0.208035 13.0504 1.3201 14.9976C1.49489 15.3006 1.74588 15.5525 2.04811 15.7284C2.35035 15.9042 2.69331 15.9979 3.0429 16H16.9155C17.2685 16.0014 17.6156 15.9094 17.9217 15.7334C18.2277 15.5574 18.4819 15.3035 18.6583 14.9976C19.5812 13.3977 20.0444 11.5738 19.9967 9.72706C19.9489 7.88036 19.3922 6.08278 18.3879 4.53279L18.3779 4.54281Z" fill="currentColor"/>
<path d="M8.57191 11.3989C8.75796 11.5853 8.97889 11.7331 9.22208 11.834C9.46528 11.9349 9.72596 11.9868 9.98922 11.9868C10.2525 11.9868 10.5132 11.9349 10.7563 11.834C10.9995 11.7331 11.2205 11.5853 11.4065 11.3989L17.0758 2.88867L8.57191 8.56213C8.38565 8.74832 8.23789 8.96942 8.13708 9.21279C8.03627 9.45616 7.98437 9.71704 7.98438 9.98049C7.98438 10.2439 8.03627 10.5048 8.13708 10.7482C8.23789 10.9916 8.38565 11.2127 8.57191 11.3989Z" fill="currentColor"/>
</svg>
```
</details>
<details>
	<summary>Monetization</summary>

Trending Up
```xml
<svg width="23" height="12" viewBox="0 0 23 12" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M16.1 0V2H19.067L13.1215 7.17L8.5215 3.17L0 10.59L1.6215 12L8.5215 6L13.1215 10L20.7 3.42V6H23V0H16.1Z" fill="currentColor"/>
</svg>
```
</details>

## Implementation Brief
* Save the 4 SVGs from the AC to `assets/svg/icons`.
* Using `assets/js/components/DashboardNavigation.js`,
	* Import the SVGs and add them to the corresponding chip via the `leadingIcon` prop.
	* Set styles and spacing as per the Figma designs.

### Test Coverage
* No new tests to be updated.

## QA Brief

* Turn on Unified Dashboard feature flag and check icons appear as per the Figma designs. 
* Check both, desktop and mobile sizes.

## Changelog entry

* Add icons to Unified Dashboard navigation

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified that when you turn on Unified Dashboard feature flag the icons appear as per the Figma designs on both desktop and mobile screen sizes.  - [Desktop](https://user-images.githubusercontent.com/73545194/145233841-716a8276-c7e0-4a1d-95fc-d803b5a29751.png) - [Mobile](https://user-images.githubusercontent.com/73545194/145233860-d99d9429-fc23-477d-b98f-1be22cb97dc4.png)
