### ISSUE TITLE
Can't run setup, cached Google account recovery phone number

### ISSUE THREAD

**Issue by sltmunky69** [google/site-kit-wp#4441]
## Bug Description

I tried to setup Site Kit for the first time on a Wordpress installation. I've done this before multiple times without issues on other sites and using different Google accounts, so I'm familiar with the process, but on this particular Google account, it had an old cell phone number listed on the account and it wanted to verify it with a text, which is not possible. So, I logged into said Google account, manually changed the account phone number and verified it via confirmation code, but when I go back to the setup wizard and try to login with that Google account, it brings me back to the send recovery text with old cached phone number. I've tried completely deleting out the plugin multiple times, clearing the browser cache and all cookies, searching for any remnants of site kit hiding in the files somewhere, incognito mode in Firefox, different browsers, entirely different computers, and all yield the same results, it just brings me right back to this recovery verification screen with the old phone number. I can log out and log into the Google account just fine in a different browser window and it shows the updated phone number, just not the setup wizard for Site Kit. My apologies in advance, as I likely should have raised a support issue on the forum first, rather than creating a bug report here just yet, but I already posted it. Anyways, I can't figure out how to get past this issue. Here is the URL it's trying to access:

`https://sitekit.withgoogle.com/site-management/setup/?scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters&supports=credentials_retrieval%20short_verification_token%20user_input_flow%20file_verification&nonce=65b67686ae&name=Wrestling%20Real%20Names%20and%20Aliases&url=https%3A%2F%2Fwww.wrestlingrealnamesandaliases.com&redirect_uri=https%3A%2F%2Fwww.wrestlingrealnamesandaliases.com%2Fwp-admin%2Findex.php%3Foauth2callback%3D1&action_uri=https%3A%2F%2Fwww.wrestlingrealnamesandaliases.com%2Fwp-admin%2Findex.php&return_uri=https%3A%2F%2Fwww.wrestlingrealnamesandaliases.com%2Fwp-admin%2Fadmin.php%3Fpage%3Dgooglesitekit-splash&analytics_redirect_uri=https%3A%2F%2Fwww.wrestlingrealnamesandaliases.com%2Fwp-admin%2Findex.php%3Fgatoscallback%3D1&user_roles=administrator&application_name=wordpress%2Fgoogle-site-kit%2F1.46.0&hl=en_US`

## Steps to reproduce

I'm not sure how to reproduce this error and after many web searches, I can't even find anybody that's had this same issue.

## Additional Context

 - PHP Version: PHP 7.4.26 Zend Engine v3.4.0 with Zend OPcache
 - OS: [e.g. iOS] Ubuntu 20.04.3
 - Browser [e.g. chrome, safari] Firefox 94.0.2
 - Plugin Version [e.g. 22] 1.46.0
 - Device: [e.g. iPhone6] Windows 10

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@sltmunky69 Thanks for reaching out. It sounds like you're having trouble during the plugin setup stage, whereby you're asked to verify permissions to your Google account. This is during the [OAuth](https://developers.google.com/identity/protocols/oauth2) setup flow, with OAuth being the authentication and verification system to connect Site Kit to your various Google services. 

As Site Kit doesn't store users personal details such as phone numbers during setup such account recovery or phone verification issues isn't something that we can provide support for here, nor can we make changes to how the OAuth verification works with Google accounts. You may wish to use the below resource for Google account recovery suggestions:
https://support.google.com/accounts/answer/7299973?hl=en

If as you've mentioned you can login to your Google account from other browsers and it displays the correct phone number you may wish to attempt Site Kit setup from this browser session.

If you're having other issues with Site Kit or the problem you're facing isn't on the OAuth screen feel free to [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) on the plugins support forums, where we'd be happy to look into this further for you.

**Comment by sltmunky69** [comment]
Yes, that is the exact point, I've tried it from a completely separate computer with a different web browser and it yields the exact same result, which is mind boggling. That's why my only guess is that something in the URL string that is being passed from the Wordpress installation to the `https://sitekit.withgoogle.com/site-management/setup/` somehow has something encoded in it which refers to the user account or a previous session or something that it is trying to rejoin. I will look into troubleshooting OAuth. Thank you.
