### ISSUE TITLE
Consent Management Platform (CMP) implementation

### ISSUE THREAD

**Issue by yogeshbeniwal** [google/site-kit-wp#4446]
## Feature Description

Starting a discussion on Consent Management Platform (CMP) implementation. Google provide Funding Choices as a Consent Management Platform for IAB TCF v2.0. With Ads/Analytics/Tags already implemented using Site Kit, CMP is a natural progression as addition to the list of modules.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by yogeshbeniwal** [comment]
@bethanylang May i know if this being considered for implementation?

**Comment by bethanylang** [comment]
@yogeshbeniwal Thank you!

This feature is not actively being considered at this time, but we regularly reevaluate priorities and update GitHub accordingly. You can continue to follow along here for any updates.

**Comment by marrrmarrr** [comment]
Hey @yogeshbeniwal, thanks for suggesting this feature! 
Could you share some more details of how you would use it? Purely to add a modal encouraging visitors to deactivate their ad blocker when visiting your site? 

Currently, as @bethanylang mentioned we're not considering this actively, but if we move forward with this at a later time, we'll make sure to update the issue.

**Comment by yogeshbeniwal** [comment]
@marrrmarrr Apart from encouraging visitors to deactivate ad blocker. Also to collect consent for privacy regulations and trigger/initialize various tags/ads/snippets on basis of consent. Sort of using Site Kit as a framework to build for managing those.

**Comment by yogeshbeniwal** [comment]
@bethanylang  From January 16 2024, Google will enforce to require partners using publisher products — Google AdSense, Ad Manager, or AdMob — to use a certified CMP that integrates with IAB Europe’s Transparency and Consent Framework (TCF) when serving ads to users in the European Economic Area (EEA) or the UK.

Once enforcement begins, if you send Google an ad request for EEA or UK traffic, and it does not use a TCF-certified CMP (Ad Manager, AdMob, AdSense) personalized and non-personalized ads will no longer be eligible to serve. Instead, only Limited ads will be eligible to serve on Ad Manager and AdMob and no ads will serve on AdSense.

**Comment by tofumatt** [comment]
Site Kit does now offer Ad Blocker detection/recovery for users of the AdSense module and has integrations with WP Consent API now, so I think we can close this issue as there isn't any further work to be done here. We don't envision Site Kit as being a framework to build on these further but we do offer our own support in the plugin. 🙂
