### ISSUE TITLE
AdSense Set-Up Improvements

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4447]
Asana overview tab: https://app.asana.com/0/1200474053395430/overview
Design doc: https://docs.google.com/document/d/1vNpMW4iED2scWOjpF8SKGoM8z6GUjX-WbhMpmAKeieo/edit#heading=h.xai0p0vhie15

**Comment by bethanylang** [comment]
Removed #4363as the primary work on this epic is complete and this issue will be addressed as time allows. Closing!
