### ISSUE TITLE
Existing Tag Simplification

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4448]
* [Epic](https://app.asana.com/0/1200380417187939/overview)
* [Proposal](https://docs.google.com/document/d/1sHKD_wx-CKiE7MAlABUjuGeFwOyP2PE82FgLOfyhryA/edit?usp=sharing&resourcekey=0-pn9BftblzzWnLKd3T3TTgg)

**PRs for this epic should target the [`feature/existing-tag-simplification`](https://github.com/google/site-kit-wp/tree/feature/existing-tag-simplification) branch**

**Comment by bethanylang** [comment]
Epic complete; closing.
