### ISSUE TITLE
Placement of Idea Hub Feature tour when Unified Dashboard enabled

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4453]
## Bug Description

When Idea Hub is activated and the feature tour loads, the placement of the highlighted area overlaps the tab bar when Unified Dashboard is activated. If you scroll down the page, the highlighted area does cover the Idea hub widget, but on activation of idea hub this is the initial load placement. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/690b90cd-b80c-4954-8026-9a3d1909a366)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit header and navigation's "sticky" positioning should be disabled when a feature tour is currently being displayed

## Implementation Brief

In `assets/js/components/TourTooltips.js`:
* in the `startTour` method, add a class `googlesitekit-showing-feature-tour` to the `body`. 
    * ie. `global.document.body.classList.add( 'googlesitekit-showing-feature-tour' );`
* in the `endTour` method, remove the class `googlesitekit-showing-feature-tour` from the `body`. 
    * ie. `global.document.body.classList.remove( 'googlesitekit-showing-feature-tour' );`

In `assets/sass/components/global/_googlesitekit-header.scss`:
* Add `static` positioning to the `.googlesitekit-header` class when the `body` has the newly added `.googlesitekit-showing-feature-tour` class. 

In `assets/sass/components/global/_googlesitekit-entity-header.scss`:
* Add `static` positioning to the `.googlesitekit-entity-header` class when the `body` has the newly added `.googlesitekit-showing-feature-tour` class. 

In `assets/sass/components/global/_googlesitekit-dashboard-navigation.scss`:
* Add `static` positioning to the `.googlesitekit-navigation` class when the `body` has the newly added `.googlesitekit-showing-feature-tour` class. 

```scss
.googlesitekit-plugin {

  .googlesitekit-navigation {
    ....
    
    body.googlesitekit-showing-feature-tour & {
      position: static;
    }
    ....
  }
  ....
}
````

### Test Coverage

* Add tests to `assets/js/components/TourTooltips.test.js` to check for the existence `googlesitekit-showing-feature-tour` class in body. 

## QA Brief

* Unified Dashboard feature flag must be enabled.
* On a new site, set the initial sitekit version to something old like `1.24.0` using tester plugin.
* Make sure the headers/navigations are no longer overlapping the tours' highlighted areas.
* Ensure the Unified Dashboard header is not "sticky" and scrolls off-screen when a feature tour is on-screen. When it is not, the header should remain at the top of the viewport as-usual.
* Also make sure that the page is scrolled correctly to the right place.

## Changelog entry

* Update plugin header to avoid obstructing feature tours.

**Comment by aaemnnosttv** [comment]
@felixarntz @eugene-manuilov I've added some initial ACs to get this going. How does this sound as a solution? Alternatively, we could make it specific to only this tour but I would imagine this very well may come up again.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv I like it. It's very elegant and efficient in the same time. Also, shouldn't take too much time to implement. Big :thumbs-up: from me 😄

**Comment by eugene-manuilov** [comment]
One thing that we need to make sure is that the page is scrolled correctly, when a feature tour (like one that we have for the help menu) for something in the header is displayed. Perhaps we should add it to AC?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov feature tours already scroll the target into view when activating a step so that shouldn't be a problem I don't think.

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov I like this solution, let's do it!

**Comment by eugene-manuilov** [comment]
Thanks, @kuasha420. IB almost looks good to me. One thing that is missing there is that we also need to update styles for the `.googlesitekit-entity-header` element as well. Could you please add it?

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The headers/navigations are no longer overlapping the tours' highlighted areas.
- The Unified Dashboard header is not "sticky" and scrolls off-screen when a feature tour is on-screen. 
- When the feature tour is not on-screen, the header remains at the top of the viewport as-usual.
- The page is scrolled correctly to the right location.
- Tested this on various screensizes on desktop. 
- Tested on our supported browsers, Chrome, Safari, etc. 

https://user-images.githubusercontent.com/73545194/150109737-09fee07d-fb7e-4189-8cec-936d08e6a794.mp4
