### ISSUE TITLE
Title missing off overall page metrics widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4454]
## Bug Description

The overall page metrics widget doesn't have a title within it like other widgets.  

As you can see from the screenshot the widget underneath has a title `Top Content over the last 90 days`

![image](https://user-images.githubusercontent.com/73545194/144628606-8d2bd58b-6d43-4eaf-b144-eb335aa47430.png)

Maybe we can give it a title like `Overall page metrics over X days.`

This widget appears on the main and entity dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DashboardOverallPageMetricsWidget` component renders `Overall page metrics over the last X days` title it the widget header where `X` is the number of days in the currently selected date range.

## Implementation Brief

* Add a `header` prop to the `DashboardOverallPageMetricsWidget`'s `<Widget>` component at https://github.com/google/site-kit-wp/blob/ed4ba8efae42f35d42c7c71f79e69b619380194e/assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidget.js#L277
  * The `header` prop should be a new `Header` component in the same file as `DashboardOverallPageMetricsWidget` like the `Footer` component is. The `Header` component should be similar to https://github.com/google/site-kit-wp/blob/6ba2897937775f8522eb746ec1610fb7d16e7841/assets/js/modules/adsense/components/module/ModuleOverviewWidget/Header.js#L38
  * The `Header` component should output:
```js
<WidgetHeaderTitle
  title={sprintf(
    /* translators: %s: number of days */
    _n(
      'Overall page metrics over the last %s day',
      'Overall page metrics over the last %s days',
      currentDayCount,
      'google-site-kit'
    ),
    currentDayCount
  )}
/>;
```

where `select( CORE_USER ).getDateRangeNumberOfDays()` gets the `currentDayCount`.

### Test Coverage

* No new test coverage is needed, but VRTs might need updating.

## QA Brief

- Visit the Site Kit dashboard
- Verify the overall page metrics title is displayed `Overall page metrics over the last 28 day`
- Change `Last 28 days` from the calendar dropdown and verify if the `Overall page metrics over the last X day` has the desired results

## Changelog entry

* Add title to the overall page metrics widget.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### **QA Update : ✅** 

**Verified :**
Note : Enable Unified Dashboard

-  The overall page metrics title is displayed as “Overall page metrics over the last 28 day”.
- On changing date period to 7,4,18 and 90, the title is updating.
- Verified on Safari, Chrome, Edge, Firefox and mobile devices.

<details>

![OM_1](https://user-images.githubusercontent.com/94359491/145619647-07f37171-5c6e-4a07-854b-74fe7c1fdadb.png)
![OM_2](https://user-images.githubusercontent.com/94359491/145619660-3163ea8b-c8f7-48b5-b5cc-c9ed7ac8d81e.png)

</details>
