### ISSUE TITLE
Idea Hub notice script throws errors on the widgets page

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#4466]
## Bug Description

If you go to the widgets page and open the browser console, you will see a lot of errors thrown by the Idea Hub notice script that is intended to run only when editing a post. It happens because, in the modern versions of WordPress, the widgets page has been reworked to use Gutenberg for editing widgets as well. We need to update the `assets/js/googlesitekit-idea-hub-notice.js` script to make sure it does nothing if it's executed on the wrong page.

## Screenshots

![image](https://user-images.githubusercontent.com/873049/144853807-02b202ac-f1cc-497c-b76a-b96c73fdd934.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit-idea-hub-notice.js` script does nothing if the `core/editor` datastore is not loaded.

## Implementation Brief

* In `assets/js/googlesitekit-idea-hub-notice.js`:
  * Update the `listener` function to return early if the `wp.data.select( 'core/editor' )` call returns `null` (or `undefined`).

### Test Coverage

* N/A

## QA Brief

* Go to the widgets page and verify that you don't see errors thrown from the `googlesitekit-idea-hub-notice.js` script in the browser console.

## Changelog entry

* Fix browser console errors related to Idea Hub on the Appearance > Widgets page in the WordPress Admin.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The console areas no longer appear on the widgets page when Idea Hub is activated.  

![image](https://user-images.githubusercontent.com/73545194/145407973-963ea6e6-2dd6-4bce-ba42-d02b2836630c.png)
