### ISSUE TITLE
Google API check can raise false warning under some conditions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4469]
## Bug Description

One of the checks that Site Kit makes before starting the initial set up is to see if the backend can connect to Google APIs as some hosts may be blocked from connecting due to geographic/other restrictions.

Because of the timing of when this request is made, it is expected to fail (due to lack of credentials) so a failure in this situation is considered a pass as the backend was able to communicate with the Google API.

However, it is possible for such a request to fail for a different reason but because the connection was blocked resulting in a false positive warning.

## Steps to reproduce

One way

1. Set up Site Kit, then go to Manage Sites and revoke access to the site **do not click Back**
2. In another tab, go back to the site
3. Configure the Site Kit access token to expire  
E.g. `wp user meta set 1 wp_googlesitekit_access_token_expires_in 1`
4. Deactivate and then reactivate Site Kit on the plugins page
5. See the _Your site may not be ready for Site Kit_ warning with the `google_api_connection_fail` error message

Another more likely possibility would be from changing the site's URL. If the site's URL were to change, normally we'd detect this and the user would be disconnected. However, if the user used a migration tool that did a search/replace with the site domain Site Kit would likely not detect this change which could result in a token refresh request failing with [invalid 'client_id' or 'client_secret'](https://wordpress.org/support/topic/google-site-kit-error-google_api_connection_fail/) during this check.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/144884436-5ed90157-4fa0-4481-a624-4dbecb6fcde3.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Google API connection check in `Health_Checks::check_google_api` should be made more resilient: In terms of errors (which are expected since the site will not be connected when this is checked), it should not be as strict to only allow a 401 error response to pass as "successful connection". Instead it should work so that any response that clearly comes from the Google API endpoint itself (i.e. JSON response body in the typical Google API error shape) should be interpreted as "successful connection".
    * A good approach for this may be to rely on `Google_Service_Exception` and its `getErrors` method. Typically any error response that actually comes from Google APIs should result in errors being set here.

## Implementation Brief

Within `includes/Core/Util/Health_Checks.php`:

* Use `Google\Site_Kit_Dependencies\Google_Service_Exception`.
* Update the `check_google_api` method:
  * Add a `catch ( Google_Service_Exception $e )` above the existing `catch`. Within this new catch block:
    * if `$e->getErrors()` is not empty, set `$pass = true`.
    * if `$e->getErrors()` is empty, set `$pass = false` and `$error_msg = $e->getMessage()`.
  * Simplify the existing catch block to only set `$pass = false` and `$error_msg = $e->getMessage()`.

### Test Coverage

* No new tests needed.

## QA Brief

* Go through Steps To Reproduce and confirm that there is no error:
<img width="1326" alt="Screenshot 2022-01-31 at 11 14 05" src="https://user-images.githubusercontent.com/1721319/151785822-2a51e37b-bdff-445b-8f8e-5ad425314bf2.png">

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by jimmymadon** [comment]
I was not able to reproduce the `google_api_connection_fail` error after following the Steps to Reproduce (had a quick look with @techanvil too). 

I have executed the IB and understand the false positive case that could arise though with the original `check_google_api()` method.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Went through the steps to recreate and confirmed no `Your site may not be ready for Site Kit ` warning 

![image](https://user-images.githubusercontent.com/73545194/152770751-666948f1-d0a5-4c1f-8381-35139ef0cc42.png)

**Comment by aaemnnosttv** [comment]
@wpdarren the image above shows the recently simplified plugin activation banner which no longer performs the compatibility checks. You'll need to check the splash page instead 🙂 

Would you please give this another quick pass?

**Comment by wpdarren** [comment]
@aaemnnosttv sure, will look at it next.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Went through the steps to recreate and confirmed no Your site may not be ready for Site Kit warning

![image](https://user-images.githubusercontent.com/73545194/152996466-7ba9d9c8-009c-4c84-a873-3dae062fb1eb.png)
