### ISSUE TITLE
Scaffold `dashboardSharing` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4471]
## Feature Description

Like most new features, Dashboard Sharing will be controlled by a new feature flag during development.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `dashboardSharing` feature flag should be added to the list of available feature flags in `feature-flags.json`

## Implementation Brief

* N/A

### Test Coverage

* 

## QA Brief

- Verify `dashboardSharing` is alphabetically added to the top of the list to the `feature-flags.json` file
- Verify `dashboardSharing` is available in the tester plugin dropdown on the admin header
- Verify `dashboardSharing` is available in the tester settings page checkbox list

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Moving this forward to the EB as no IB is really necessary here 😄

**Comment by ivankruchkoff** [comment]
QA ✅

1. feature-flags.json
https://github.com/google/site-kit-wp/blob/4e5bb3717b1bfd9a240a079ec4150c7d2b4e28e0/feature-flags.json#L2

2. Dropdown
<img width="218" alt="Screen Shot 2021-12-08 at 3 56 01 PM" src="https://user-images.githubusercontent.com/373931/145310046-d586e02c-c98c-477f-bc74-6b0b2fa08751.png">

3. Settings Checkbox
<img width="476" alt="Screen Shot 2021-12-08 at 3 56 26 PM" src="https://user-images.githubusercontent.com/373931/145310043-b3a94a4c-a54e-4ec9-be6b-0bf885e71c5b.png">
