### ISSUE TITLE
Add tests for `Core\Permissions`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4472]
## Feature Description

In preparation for #4522, we need to backfill some test coverage for the `Permissions` class which handles all of the custom capabilities in Site Kit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHPUnit test coverage should be added for the `Core\Permissions` class, including all public methods
    * Ensure each custom capability is tested using WP capability checking functions
    * Ensure the logic around setup completion, authentication, and verification is also covered

Note some logic is currently specific to the current user only annotated with `TODO` comments and should be left as-is for now – this issue is just about adding coverage.

## Implementation Brief

Create a file `tests/phpunit/integration/Core/Permissions/PermissionsTest.php` with the following tests for their corresponding functions:
`public function test_check_all_for_current_user();`
`public function test_get_capabilities();`

`public function test_register();` which registers the filters that we need to test as follows:

Ensure we test the following capabilities, via the `googlesitekit_user_data` filter:

https://github.com/google/site-kit-wp/blob/6feaccff1ff8676d8cbfc4d54cf2f92020577ed3/includes/Core/Permissions/Permissions.php#L24-L37

By calling `map_meta_cap` filter, ensure we cover scenarios where:
* verification has / hasn't completed:
https://github.com/google/site-kit-wp/blob/6feaccff1ff8676d8cbfc4d54cf2f92020577ed3/includes/Core/Permissions/Permissions.php#L254-L257

* setup has / hasn't completed
https://github.com/google/site-kit-wp/blob/6feaccff1ff8676d8cbfc4d54cf2f92020577ed3/includes/Core/Permissions/Permissions.php#L259-L262

* user is / isn't authenticated
https://github.com/google/site-kit-wp/blob/6feaccff1ff8676d8cbfc4d54cf2f92020577ed3/includes/Core/Permissions/Permissions.php#L251-L252

Finally, test `user_has_cap` filter.

### Test Coverage

* Add tests for the `Permissions` class as described above

## QA Brief

* Review added tests to ensure ACs are satisfied

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv ACs LGTM!

**Comment by eugene-manuilov** [comment]
@ivankruchkoff let's make it clear that we need to add phpunit tests for filters defined in the `register` method.

**Comment by hussain-t** [comment]
### QA:Eng ✅ 

- Verified the tests cases covered as described in the AC
- Executed all the tests and all are passing
