### ISSUE TITLE
Scaffold new script data global for dashboard sharing

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4473]
## Feature Description

In preparation for the client-side aspects of dashboard sharing, we need to scaffold a new global which will provide various data on page load.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Script_Data` asset should be added to the main list of Site Kit's assets with a handle of `googlesitekit-dashboard-sharing-data`
* Its `global` should be `_googlesitekitDashboardSharingData`
* The data it provides should follow a similar pattern as other script data assets, providing an empty array for now, but should be filterable using a new `googlesitekit_dashboard_sharing_data` filter
* The new sharing data asset should be added as a dependency of the main/entity dashboards, but only if the `dashboardSharing` feature flag is enabled

## Implementation Brief

In `Core/Assets/Assets.php` `get_assets()`
 * Add a new `Script_Data` with the `handle` of `googlesitekit-dashboard-sharing-data` and `global` of `_googlesitekitDashboardSharingData`. 
 * In the `data_callback` make a call to a new function `$this->get_inline_dashboard_sharing_data` which contains the following:

```php
function get_inline_dashboard_sharing_data() {
    $inline_data = array();
    return apply_filters( 'googlesitekit_dashboard_sharing_data', $inline_data );
}
```

Update dependencies for `googlesitekit-dashboard-details ` and `googlesitekit-dashboard ` to also include `googlesitekit-dashboard-sharing-data` if `Feature_Flags::enabled( 'dashboardSharing' )` is `true`.
https://github.com/google/site-kit-wp/blob/7b2e80b0408746148fb2bf4091c5f57e4aa705f3/includes/Core/Assets/Assets.php#L556-L569

### Test Coverage

* N/A

## QA Brief

- Enable `dashboardSharing` via the tester plugin
- Make sure you are in the Site Kit dashboard page
- Open the browser developer console and type `window._googlesitekitDashboardSharingData`
- Verify that you should get an empty array `[]` as a value of the above property
- Disable `dashboardSharing` via the tester plugin
- Type `window._googlesitekitDashboardSharingData` in the browser developer console
- Verify that you should get `undefined` as a value of the above property

## Changelog entry

* Add `_googlesitekitDashboardSharingData` global data.

**Comment by eugene-manuilov** [comment]
> Update the `$dependencies` array to include `googlesitekit-dashboard-sharing-data` if `Feature_Flags::enabled( 'dashboardSharing' )` is `true`.

@ivankruchkoff it should be added as a dependency to `googlesitekit-dashboard` and `googlesitekit-dashboard-details` scripts only.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- Get an empty array [] as a value of the above property when `dashboardSharing` is enabled. 
- Get undefined as a value when `dashboardSharing` is disabled. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/148036155-3d936d8d-6884-40cd-80d7-d83f6e6498eb.png)

![image](https://user-images.githubusercontent.com/73545194/148035763-4a4a4124-9308-456f-94da-73a0a07b7a79.png)

</details>
