### ISSUE TITLE
Annotate shareable module datapoints

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4474]
## Feature Description

In the context of dashboard sharing, only select module datapoints will be capable of leveraging data shared by the module's owner. Accordingly, the definition of each datapoint that should be enabled to potentially be made on behalf of the module owner will need to be annotated explicitly.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following datapoints should be updated to include a new `shareable` key which is should be set to `true` if the `dashboardSharing` feature flag is enabled  
    ```
    adsense             GET:earnings
    analytics           GET:goals
    analytics           GET:report
    idea-hub            GET:new-ideas
    idea-hub            GET:saved-ideas
    idea-hub            GET:draft-post-ideas
    idea-hub            GET:published-post-ideas
    search-console      GET:searchanalytics
    pagespeed-insights  GET:pagespeed
    ```
* `shareable` should be set on the same level of the definition as [`service` or `scopes`](https://github.com/google/site-kit-wp/blob/e66e6901ccccb4a2aeba1bb408af3af727969863/includes/Modules/Analytics.php#L346-L347)

## Implementation Brief

Using the code example for reference of where to make the update:
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Analytics_4.php#L193-L194

Add a property to EACH of the endpoints in the AC with:
```php
'shareable'  => Feature_Flags::enabled( 'dashboardSharing' )
```

Reference files:
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/AdSense.php#L198
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Analytics.php#L355
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Analytics.php#L358
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Idea_Hub.php#L445
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Idea_Hub.php#L446
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Idea_Hub.php#L447
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Idea_Hub.php#L448
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/PageSpeed_Insights.php#L69
https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/includes/Modules/Search_Console.php#L165

### Test Coverage

* N/A

## QA Brief

* Ensure each of the endpoints in the AC has the shareable key set in the datapoint definition.

## Changelog entry

* Annotate module endpoints which can be used with dashboard sharing.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kuasha420** [comment]
QA: :heavy_check_mark: 

In `develop`, All the shareable modules defined in the AC has been annotated with the appropriate value.
