### ISSUE TITLE
Update PageSpeed and Idea Hub to be modules with owners

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4476]
## Feature Description

Dashboard sharing only allows for a module to be shareable if it has an owner, which has been unnecessary for some modules until now. As modules that will be shareable via dashboard sharing, PageSpeed Insights and Idea Hub will need to be updated to support having a module owner like most other modules.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PageSpeed Insights and Idea Hub modules should be updated to be "owned" modules. While this has historically only been implemented for modules with settings that are owned (e.g. an account or property ID), dashboard sharing requires an associated module owner to facilitate sharing.
    * These modules will not have any owned settings, they only need to support a module owner via module settings 

## Implementation Brief

* In `includes/Modules/Idea_Hub/Settings.php`:
  * Add `'ownerID' => 0` to the default settings.
* In `includes/Modules/Idea_Hub.php`:
  * Implement `Module_With_Owner` interfaces.
  * Use the `Module_With_Owner_Trait` trait.
* Add a new class `includes/Modules/PageSpeed_Insights/Settings.php` that extends the `Module_Settings` class:
  * Define the `OPTION` constant with `googlesitekit_pagespeed-insights_settings` value.
  * Add a new protected method `get_default` that returns an array with the only `'ownerID' => 0` value.
* In `includes/Modules/PageSpeed_Insights.php`:
  * Implement `Module_With_Settings` and `Module_With_Owner` interfaces.
  * Use `Module_With_Settings_Trait` and `Module_With_Owner_Trait` traits.
  * Add a new protected method `setup_settings()` that returns a new instance of the PSI's `Settings` class.
  * Update the `on_deactivation` method to delete the module settings similarly how it is done in other modules: https://github.com/google/site-kit-wp/blob/487c88b63659dd74ddfe5954eb9edbf48de2de73/includes/Modules/Analytics.php#L199
  * Remove these lines from the `on_deactivation` method: https://github.com/google/site-kit-wp/blob/487c88b63659dd74ddfe5954eb9edbf48de2de73/includes/Modules/PageSpeed_Insights.php#L57-L58

### Test Coverage

* Add new phpunit tests for the PSI's `Settings` class. Use the similar approach as we use for other settings classes.
* Update phpunit tests for the Idea Hub's `Settings` class.

## QA Brief

This change is not E2E testable and will need to be `QA:Eng` tested.

**`QA:Eng`**: Additional code review to verify the requirements are met.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov ! A few minor points but overall looks good 👍 

> * Use the `Setting_With_Owned_Keys_Trait` trait.

Neither module will have any owned settings for now as mentioned in the ACs, we just need to associate an owner.

> * Remove the `Module_With_Deactivation` interface.
> * Remove the `on_deactivation` method.

While this has a TODO to remove it in a later release (which is probably okay to do with the legacy option reference), this interface and its method is still relevant for both modules as their settings should still be deleted on deactivation.

> * Define the `OPTION` constant with `googlesitekit_pagespeed_insights_settings` value.

The module slug within the option is the same as elsewhere (i.e. hyphenated) rather than snake-cased.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv IB is updated.

**Comment by aaemnnosttv** [comment]
> * Add a new public method `on_activation()` that sets the `ownerID` setting to the current user ID.

@eugene-manuilov Sorry if I missed this before, but we don't need to set the owner on activation. The modules obviously need an owner to facilitate sharing, but the owner for these will be set when sharing is enabled or changed. I just noticed we don't have an issue for this yet so I opened #4620 for it.

Please remove the proactive setting of the module owner on activation and then this should be good to go 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by kuasha420** [comment]
QA: :heavy_check_mark: 

* Code does satisfy the AC. 
* Everything is working and no regression has been spotted on `develop` while setting up and deactivating the `PageSpeed Insights` and `Idea Hub` modules.
* Newly added and existing unit tests pass. 

Sending this to approval.
