### ISSUE TITLE
Add a new `check-access` endpoint to core modules

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4478]
## Feature Description

#4579 introduces a new interface for modules to provide a reference to their currently configured service entity identified by their owned settings.

This issue builds on this infrastructure to allow for the current user's access to be checked to a module's service entity. This will be needed for things like module recovery in dashboard sharing, so we will add a new endpoint to the `core/modules` REST namespace to facilitate this for any module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/modules` REST namespace should receive a new `POST:check-access?slug={slug}` endpoint
	* This endpoint should be limited to authenticated admins only
* The handler should check access for the module identified by the `slug` request parameter or error if not found (similar to others) using the relevant method exposed by the new `Module_With_Service_Entity` interface
* The handler should return an object with the result with the following shape or a `WP_Error`:  
    ```js
    {
        access: Boolean, // true if user has access otherwise false if API returns a 403
    }
    ```
    * It should return a `WP_Error` with a `404` status if called with a non-existent module slug
    * If the module is not connected it should bypass the internal call to check access for the module and return a relevant `WP_Error`
    * Any exception thrown by the API request other than a `403` should be returned as a `WP_Error`

## Implementation Brief
* Using `includes/Core/Modules/Modules.php`,
	* Update the `get_rest_routes` method to defined a new REST route `core/modules/check-access`.
		* The value for the `methods` key should be `WP_REST_Server::EDITABLE`.
		* For the `callback`, define a function which does the following:
			* Get the `slug` request parameter.
			* Check if the module exists via the `get_module` method, passing the `slug` as parameter, else return a `WP_Error` with status `404` (third parameter of `WP_Error`) object similar to how it's done for `core/modules/data/info`
			* If the module exists, check if it's connected via the `is_module_connected` method, passing the `slug` as parameter.
				* If module is not connected return a `WP_Error`
				* If module is connected, check if the user has access by calling its `check_service_entity_access` method and return the value in the response: `access => true` or `access => false`
				* Any exception thrown by the API request other than a `403` should be returned as a `WP_Error`.
		* For the `permission_callback`, define a function which returns the value of `current_user_can( Permissions::SETUP )`.

### Test Coverage
* Tests to be added for the new endpoint.

## QA Brief
* Disconnect Analytics module.
* Using the `core/modules/data/check-access` endpoint,
	* Make a GET request and check that it fails.
	* Make a POST request and check that it fails because of the missing `slug` parameter.
	* Make a POST request with the `slug` parameter set to `foo-bar` and check that it fails because of it's an invalid module slug.
	* Make a POST request with `slug` parameter set to `analytics` and check that it fails since the module is not connected.
	* Connect the Analytics module and make a POST request similar to the previous bullet point and see if `access` is `true` in the response.

**Update - QA:Eng**
--------------------
- Verify the body params is correctly constructed 
- Verify the above API call invocation steps with the body params `JSON.stringify( { data: { slug: "analytics" } } )`
- Verify the unit tests are passing

## Changelog entry

* Add `check-access` endpoint to modules for Dashboard Sharing.

**Comment by felixarntz** [comment]
@aaemnnosttv I wonder if we could specify the contract here in some way - the current ACs here list the exact modules this is needed for, but that list is not arbitrary, it technically applies to all modules that have owned keys.

I wonder if we could somehow tie that to an interface method, e.g. something like a `check_access` in `Module_With_Owner`, or even a new interface that extends `Module_With_Owner`? It is also closely related to `Setting_With_Owned_Keys_Interface`, however that applies to each module's settings class and not the module class itself. Potentially the method I propose above could be like `check_access( Setting_With_Owned_Keys_Interface $setting )` to indicate that this only works with a setting that also implements that interface?

Regardless of how exactly, if we facilitated this functionality via an interface (maybe including a trait as well), it would be more formally specified, and then the `POST:check-access` endpoint could be implemented in a central location and only call that method above if the module implements the interface, similar to e.g. the `notifications` or `settings` endpoints for each module.

Maybe I'm overthinking this, but I think this is worth a consideration. Adding a similarly named data point to all of these modules feels a bit "arbitrary" to me.

**Comment by aaemnnosttv** [comment]
@felixarntz this somewhat relates to the discussion around all-admin modules and the idea of having a `Module_With_Service_Entity` interface or similar which would be what we would check the access for.

> if we facilitated this functionality via an interface (maybe including a trait as well), it would be more formally specified, and then the `POST:check-access` endpoint could be implemented in a central location and only call that method above if the module implements the interface, similar to e.g. the `notifications` or `settings` endpoints for each module.

I like the idea of using this approach 👍 

> Potentially the method I propose above could be like check_access( Setting_With_Owned_Keys_Interface $setting ) to indicate that this only works with a setting that also implements that interface?

I'm not sure the parameter is needed there, we only need the module to check using the current settings (at least for now). If we wanted to make it more abstract using a type rather than coupling it to the current saved settings, we could introduce a module-specific `Connection` class which would essentially hold all the values that determine the "owned" connection to the service. I think this is maybe a bit premature to introduce just yet though.

A long time ago, we used to have a `GET:connection` datapoint which later became obsolete with the introduction of module `Settings`. Perhaps `Module_With_Service_Entity` (or maybe simply `Module_With_Connection`) could do something similar by adding a `get_connection() : array` method, and we could use a trait to essentially return the subset of `owned` settings from the module's settings class?

Then the centralized handler could essentially do something like this:

```php
if ( $module instanceof Module_With_Service_Entity ) {
    $connection = $module->get_connection();

    return $module->check_access( $connection );
}
```

This is very similar to your proposed method only it would be decoupled from settings. `$connection` here could be an instance of a new class like I said but I'm not sure that would offer much just yet? What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv I like your proposed solution, let's go with that - except that I'm strongly leaning towards not using the term "connection" anywhere here, I think "service entity" is more clear (almost all modules connect to something, but not all of them have a service entity) and also doesn't conflict with anything else ("connection" is quite abstract and already used for a couple other things).

How about:
* interface `Module_With_Service_Entity`
* method `get_service_entity`, returning an array

Do you think this is the right issue to update the ACs for to introduce the interface? Or rather another one that is a prerequisite to this one?

**Comment by aaemnnosttv** [comment]
@felixarntz sounds good to me. I'll open a new issue for introducing that first as a prerequisite 👍

**Comment by aaemnnosttv** [comment]
@felixarntz I've opened the new issue which is with you for review. Regarding the check for connection, maybe this isn't needed as the underlying method for checking the service entity should validate the input and fail before attempting a request if necessary data was missing.

**Comment by felixarntz** [comment]
@aaemnnosttv I think the ACs here look good, I just left a related comment in https://github.com/google/site-kit-wp/issues/4579#issuecomment-998223878. We could potentially check if the module is also active and connected before even calling the interface method? That would help, but I also think we should check for missing variables in the interface implementation anyway, so it may be unnecessary.

From my point this can be moved to IB, just wanted to raise the above with you first.

**Comment by aaemnnosttv** [comment]
> We could potentially check if the module is also active and connected before even calling the interface method? That would help, but I also think we should check for missing variables in the interface implementation anyway, so it may be unnecessary.

Thinking about this a bit more, now that the underlying method checks an arbitrary entity we probably shouldn't call it here if the module wasn't connected because we could provide a more useful reason: "module setup isn't completed" rather than "one or more required entity fields are missing". Both will probably be needed, but the former is probably more useful in this case where we are specifically checking the current connection.

I'll update the ACs to clarify this.

**Comment by felixarntz** [comment]
@aaemnnosttv Per my comment in https://github.com/google/site-kit-wp/issues/4579#issuecomment-999001492, I think the response here could be simplified to _only_ an `{ access: Boolean }` object. Any situation where we can't clearly say it's `access: true` (200 response) or `access: false` (403 response), IMO the endpoint should return a regular error response directly from a `WP_Error`, as common in the WordPress REST API and our other endpoints asll.

**Comment by eugene-manuilov** [comment]
> It should bypass the internal call to check access for the module and return access:false early if the module is not connected and return a relevant WP_Error

@aaemnnosttv is there a typo in this criteria? How can we return `{ access: false }` and an error at the same time? If we return a WP error, then the response schema will inconsistent with the one that is returned when the user has access.

> For the permission_callback, define a function which retrns the value of current_user_can( 'administrator' )

@asvinb I think we should check whether the current user can set up the plugin by checking the `Permissions::SETUP` capability.

**Comment by aaemnnosttv** [comment]
> is there a typo in this criteria? How can we return `{ access: false }` and an error at the same time? If we return a WP error, then the response schema will inconsistent with the one that is returned when the user has access.

@eugene-manuilov yes, sorry about that. It would only return `{ access: false }` in the event that the request was able to be made but returned a 403 because they didn't have access. If it failed for any other reason, or wasn't able to be made (as in the case if the module wasn't connected), then it should return a `WP_Error` but not both.

**Comment by asvinb** [comment]
@eugene-manuilov IB updated, can you check again?

Thanks!

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by kuasha420** [comment]
### QA: :heavy_check_mark: 

* Went through the QA Brief and got the desired result. 
* Additionally tried to access with a secondary Admin who doesn't have the access and got `success: false`.

LGTM.

**Comment by techanvil** [comment]
## QA :white_check_mark:

* Confirmed the body params are correctly constructed/used.
* Ran through the original QA Brief, with updated body params to use the JSON stringified version e.g. the result of `JSON.stringify( { data: { slug: "analytics" } } )`. All points confirmed successful.
* Verified the unit tests are passing.
