### ISSUE TITLE
Add a dismissal when non-admins go to the shared dashboard for the first time from the splash page

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4479]
## Feature Description

In dashboard sharing, non-admins will see a slightly different version of the splash screen as admins do because they still don't have the option to sign-in with Google yet.

The alternate splash will function as kind of welcome to the shared dashboard, and should only be shown the first time. Once the user clicks the button to navigate to the dashboard, this should be treated similar to permanantly dismissing a notice.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a non-admin who has access to view the shared dashboard visits the splash page for the first time, the action of clicking the button and navigating to the shared dashboard should store a `shared_dashboard_splash` [dismissal item](https://github.com/google/site-kit-wp/blob/a27f08668b1d738f72672bfc5d7c61e90bef981c/includes/Core/Dismissals/Dismissed_Items.php) for the user
	- Note: [redirects will be added](https://github.com/google/site-kit-wp/issues/4525) to send the user back to the splash page from the dashboard if this dismissal is missing (and vice versa) so this cannot be added simply on the first view of the dashboard alone

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz I updated the issue here to be less implementation-specific than originally planned as there are multiple ways this could be done and I'm not sure a new admin action is the best solution here.

The simplest option might be to trigger the dismissal on the client side (as we do with all others) instead but I think it should be still reasonably simple to handle on the backend. LMKWYT?

**Comment by felixarntz** [comment]
@aaemnnosttv Can we even implement it at this point? I wonder whether this would be better as part of a frontend issue when we implement the UI. The server-side part of handling the dismissal already exists, so I'm not sure how much we can do here at this point.

**Comment by aaemnnosttv** [comment]
@felixarntz we could define a custom URL which would trigger the dismissal; later the go-to-dashboard button could be linked to this URL for non-admins. Alternatively, it could use a more client-heavy implementation as mentioned above. So it's definitely actionable now, it's more of a question of which route we'd prefer to go.

**Comment by felixarntz** [comment]
@aaemnnosttv I think a specific URL or REST route for this dismissal seems unnecessary. The current ACs are also phrased in a way that sounds like there needs to be some of that UI already there to implement it.

Maybe we can simplify this to for now create a simple class or method somewhere to conveniently check on the server-side whether the user `has_dismissed_shared_dashboard_splash` or something like that? This wouldn't be useful on its own, but important for other server-side follow-up issues, e.g. around the redirects. This issue could also include e.g. introducing a constant for that specific dismissal item key.

**Comment by felixarntz** [comment]
@aaemnnosttv Agreed - I see #4525 already is in IB review anyway. Feel free to close this issue then.
