### ISSUE TITLE
Update Site Verification module datapoints for consistency

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#448]
Datapoints in the Site Verification module should receive minor updates as outlined in the ACs.

Implementation brief should include which pieces of JS need to be updated and which e2e tests need to be updated (if any).

**Execution is blocked until #406 is merged.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Verification part of setup should still work as before.
* Parameters and return values controlled by the plugin itself should all be in camel case.
* Datapoints should be updated as follows:
    * GET verified-sites → keep as is
    * GET siteverification-list → GET verification
    * POST siteverification → POST verification
        * response should have same format as GET verification: identifier + type + verified
    * GET siteverification-token → GET verification-token

#### `GET siteverification-list`
* Rename datapoint to `verification`
* [update usage](https://github.com/google/site-kit-wp/search?q=siteverification-list&unscoped_q=siteverification-list)
* assets/js/components/setup/site-verification.js (1 call)
* E2E Site Verification API Mock plugin

#### `GET siteverification-token`
* Rename datapoint to `verification-token`
* [update usage](https://github.com/google/site-kit-wp/search?utf8=%E2%9C%93&q=siteverification-token&type=)

#### `POST siteverification`
* Rename datapoint to `verification`
* Update return value based on response from internal call to `GET verification`  
    - If the site was already verified, return response from `GET verification`  
    - If the site was not verified, call the the site verification API to get the type:
    ```php
    $verification = $this->get_service( 'siteverification' )->webResource->get( $data['siteURL'] );
    /* @var Google_Service_SiteVerification_SiteVerificationWebResourceResource $verification */
    return array(
        'identifier' => $data['siteURL'],
        'type'       => $verification->getSite()->getType(),
        'verified'   => true,
    );
    ```
* E2E Site Verification API Mock plugin
* https://github.com/google/site-kit-wp/blob/f7f99e7fe435c5f31172f81a70515dc7136b05b3/assets/js/components/setup/site-verification.js#L111-L113

## Changelog entry

* Improve datapoint behavior of Site Verification module for consistency.

**Comment by aaemnnosttv** [comment]
@felixarntz The AC mentions "response should have same format as GET verification: identifier + type + verified" for POST verification, returning an "object" for a single site, the same as GET verification. Would the `type` ever be different than `SITE`, and would `verified` ever not be `true`? It seems like they would otherwise the response would be a WP_Error of some kind.

If so, is it safe to say we can hardcode these in the response for that endpoint? `GET verification` supports domain verification as well, so could it be possible that type may be different?

**Comment by felixarntz** [comment]
@aaemnnosttv `type` can indeed be different. I think what we should do is:
* If the site was already verified, we just pass through the response from `GET verification` that is internally called in `POST verification` anyway (this is also an area where we need to update the reference).
* If the site was not already verified, after running the existing logic to do so, we can get the proper return value by calling [this API endpoint](https://developers.google.com/site-verification/v1/webResource/get) with the `siteURL` and taking what we need from that.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz in the case that the site was not already verified, it's inserting META verifications for each permuted version of the site URL. Should it not then return the site object from the successful insert request? It seems that it currently returns the site object for `siteURL` but the actual URL the verification was added for could have been different. Does this matter?

**Comment by felixarntz** [comment]
@aaemnnosttv Makes sense. It currently only errors if all insertion requests failed. We should probably only use `siteURL` if it actually among the requests that passed, and otherwise fall back to another one like you suggested.

**Comment by aaemnnosttv** [comment]
@felixarntz I assume that any changes to this part should happen in a separate issue?

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds reasonable. Would you mind creating one?

**Comment by tofumatt** [comment]
Tested the sign-in flow locally and things still work as before on the happy path (eg with a site I own).

Tested the site verification page on a URL my account didn't have access to and got the right error message.

Seems good to me! 👍
