### ISSUE TITLE
Expose shareable roles to client

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4480]
## Feature Description

In order to [populate the dashboard sharing settings](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.tphgu5b1xd6j), the client needs to be aware of which roles are available to choose from.

This issue is about extending the script data for dashboard sharing established in #4473 with a new `roles` property that will provide information about each shareable role.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`googlesitekit-dashboard-sharing-data` script data](https://github.com/google/site-kit-wp/issues/4473) should be extended to include a new `roles` property as a list of `role` objects with the following shape:  
	```
	{
		id          : string,
		displayName : string,
	}
	```
* The list of roles in the list should be equal to the set of all `WP_Roles` on the site with the `edit_posts` capability where the `role.id` maps to a `WP_Role->name`, and `role.displayName` maps to the [translated role name](https://developer.wordpress.org/reference/functions/translate_user_role/)

## Implementation Brief

In `Core/Assets/Assets.php` update the `$inline_data` in `get_inline_dashboard_sharing_data()` to return an array of `roles`, where a role is of the format `array( 'id' => 'string', 'displayName' => 'string' )`.

To get the list of roles, first get the WordPress roles:
`wp_roles()` - https://developer.wordpress.org/reference/functions/wp_roles/ and filter only those with the capability `edit_post`
The `id` is the array key and the `name` should be run through through `translate_user_role` - https://developer.wordpress.org/reference/functions/translate_user_role/ to get the `displayName` property.

### Test Coverage

* N/A

## QA Brief

- Enable `dashboardSharing` via the tester plugin
- Make sure you are in the Site Kit dashboard page
- Open the browser developer console and type `window._googlesitekitDashboardSharingData`
- Make sure you have logged in as the administrator
- Verify that you should get an array of roles. The format as mentioned in the AC/IB. 
- Verify if you're logged in as an administrator you should have an array of four roles, `Administrator`, `Editor`, `Author`, and `Contributor`. Please refer to the screenshot attached to the PR description.
- Disable `dashboardSharing` via the tester plugin
- Type `window._googlesitekitDashboardSharingData` in the browser developer console
- Verify that you should get `undefined` as a value of the above property

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When `dashboardSharing` is enabled:

- As an administrator I have an array of four roles, `Administrator`, `Editor`, `Author`, and `Contributor`. 

When `dashboardSharing` is disabled:

- I get undefined as a value of the property.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/148395905-a9d8e647-845c-4ef9-b35a-67f08c3e2560.png)

![image](https://user-images.githubusercontent.com/73545194/148395923-c22d2715-848d-4a57-a30b-98dcd1bd09c6.png)

</details>
