### ISSUE TITLE
Update Search Console module datapoints for consistency

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#449]
Datapoints in the Search Console module should receive minor updates as outlined in the ACs.

Implementation brief should include which pieces of JS need to be updated and which e2e tests need to be updated (if any).

**Execution is blocked until #406 is merged.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Search Console setup and querying Search Console data via API should still work as before.
* Parameters and return values controlled by the plugin itself should all be in camel case.
* Datapoints should be updated as follows:
    * GET sites → keep as is
    * GET matched-sites & GET is-site-exist → combine into one GET matched-sites
        * response format should be <exactMatch, propertyMatches>, where <exactMatch> is a <site> object and <propertyMatches> is a list of <site> objects, with a <site> being a <permissionLevel, siteUrl>
        * this provides all the information we need in a single route; the check whether the permission level is specific (as currently present in GET is-site-exist) should happen on the client
    * GET sc-site-analytics & GET page-analytics & GET search-keywords → combine into one GET searchanalytics
        * “dimensions” should be supported via $data and parsed into an array, e.g. when passed as comma-separated list
    * GET index-status → remove entirely because unused
    * POST save-property && POST insert → POST site
        * “siteURL” parameter in $data should become “siteUrl”
        * datapoint should be modified to work more closely to the above verification one:
            * use sites->get() for the passed URL to check whether a property exists yet
            * if not add it with sites->add() (as currently happening via POST insert)
            * in both cases, store the siteUrl should be stored in the property option
        * the return value should be the resulting <site> object (<permissionLevel, siteUrl>))

## Implementation Brief

* Update response for `GET matched-sites`
    - Response format  
    ```php
    return array(
        // If exact match is found
        'exactMatch' => array(
            'permissionLevel' => $exactSiteMatch->getPermissionLevel(),
            'siteUrl'         => $exactSiteMatch->getSiteUrl(),
        ),
        // If exact match is not found
        'exactMatch' => null,
        // Property matches a list of site objects, or empty array if none.
        'propertyMatches' => array(
            array(
                'permissionLevel' => $site->getPermissionLevel(),
                'siteUrl'         => $site->getSiteUrl(),
            ),
            // ...
        ),
    )
    ```
    - Update consuming code to use new response format
    - Update consuming code on client to check permission level as was done in `is-site-exist`
* Add new `GET searchanalytics` datapoint
    - Consolidated from `GET sc-site-analytics` and `GET search-keywords`
    - Add support for a new `dimensions` parameter in `$data`. This should be parsed as comma-separated list into an array (list) of dimensions as passed to `create_search_analytics_data_request`.
    - Add support for a new `compareDateRanges` parameter in `$data`. This is a boolean value. If truthy, the requested date range should be doubled to provide the previous range as well for comparison by passing `2` for the `$multiplier` to `parse_date_range()`.
    - Add support for a new `limit` parameter in `$data`. This will be translated to the `row_limit` for the request.
* Update `POST site` 
    - Consolidated from `POST save-property` and `POST insert`
    - Check if site exists first e.g.:  
    `$service->sites->get( trailingslashit( $data['siteUrl'] ) )`
    - If not exists, add it  
    `$service->sites->add( trailingslashit( $data['siteUrl'] ) )`
    - Ensure `siteUrl` is stored in the `PROPERTY_OPTION`
    - Returns  
    ```php
    return array(
        'permissionLevel' => $site->getPermissionLevel(),
        'siteUrl'         => $site->getSiteUrl(),
    )
    ```
* Update all instances of `siteURL` to `siteUrl`
* Update consuming code to use new datapoint and response formats, where changed
* Remove datapoints from `Search_Console::` methods: `get_datapoint_services`, `create_data_request`, `parse_data_response`
    - `index-status`
    - `is-site-exist`
    - `sc-site-analytics`
    - `page-analytics` (already removed)

#### Summary of Consuming Code to be Affected

**New / Updated datapoints**
[`GET matched-sites`](https://github.com/google/site-kit-wp/search?q=matched-sites&unscoped_q=matched-sites)
- Search Console setup (1 call)
- E2E Site Verification API Mock plugin - need to update mocked response

[`POST site`] [new]
- See `POST save-property` below
- See `POST insert` below

**Removed datapoints**

[`GET is-site-exist`](https://github.com/google/site-kit-wp/search?q=is-site-exist&unscoped_q=is-site-exist)
- Search Console setup (1 call)
- E2E Site Verification API Mock plugin
- tests/e2e/specs/auth-flow.test.js (intercepted request)

[`GET sc-site-analytics`](https://github.com/google/site-kit-wp/search?q=sc-site-analytics&unscoped_q=sc-site-analytics)
- Single call in ~6 different components
- No E2E

[`GET search-keywords`](https://github.com/google/site-kit-wp/search?q=search-keywords&unscoped_q=search-keywords)
- Single call in ~2 components
- No E2E

[`POST save-property`](https://github.com/google/site-kit-wp/search?q=save-property&unscoped_q=save-property)
- Search Console setup (1 call)
- E2E Site Verification API Mock plugin

`POST insert`
- Search Console setup (1 call)
- E2E Site Verification API Mock plugin

## Changelog entry

* Improve datapoint behavior of Search Console module for consistency.

**Comment by aaemnnosttv** [comment]
@felixarntz - a few questions for you:

* If there is no `exactMatch`, what should the value be?
* For the new `searchanalytics` datapoint, `sc-site-analytics` and `search-keywords` pass different values to `parse_date_range`. Is this required? If so, how should this be handled in the new datapoint? Similarly, `search-keywords` has a `row_limit` of 10, while the other does not.

**Comment by felixarntz** [comment]
> If there is no `exactMatch`, what should the value be?

It's currently a string, we can probably maintain that. Alternative would be an actual falsy value for JavaScript, but it would also be somewhat inconsistent. I'm certainly open to discussing this.

> For the new `searchanalytics` datapoint, `sc-site-analytics` and `search-keywords` pass different values to `parse_date_range`.

This is because for some reason we sometimes queried double the days we actually want. This shouldn't be the case, unless necessary, but we should discuss this with @adamsilverstein who I think has more context on why this change was originally made.

> Similarly, `search-keywords` has a `row_limit` of 10, while the other does not.

This is okay, we can combine the endpoints and support a `limit` argument (it should be named `limit` for consistency and simplicity, and internally map to `row_limit`). The default for the Google API endpoint if `row_limit` is not provided is 1000, so we can make it behave the same way (see https://developers.google.com/webmaster-tools/search-console-api-original/v3/searchanalytics/query)

**Comment by felixarntz** [comment]
After discussing the date ranges, let's go with the following solution: In case we need to query duplicate date ranges (e.g. we query 56 days instead of 28), we should pass a boolean `compareDateRanges` parameter. In the case of the new `searchanalytics` datapoint, depending on that the datapoint would set the `$multiplier` parameter of `parse_date_range()` to either 2 (if `compareDateRanges` true) or 1 (otherwise).

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Updating size to account for VRT data regeneration which will be necessary.

**Comment by felixarntz** [comment]
This will be blocked until #500 is done. Once unblocked, move back to QA column.
