### ISSUE TITLE
Slight inconsistencies applying breakpoints around 600px

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4491]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480204836408

There is a layout that is only active at 600px. The media queries should be aligned so the layout at 600px is either aligned with that at 599px or 601px. See attached screen capture (animated gif, click to play). There's also inconsistencies with the header icons at these breakpoints, as well as the blue line above the total impressions section (as per screenshot below and gif on the Asana ticket)

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/74b5d762-6d1c-4156-aff6-00b195b3dacb)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this out as it's no longer an issue 🙂
