### ISSUE TITLE
Slight inconsistencies applying breakpoints around 600px

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4492]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480204836408

There is a layout that is only active at 600px. The media queries should be aligned so the layout at 600px is either aligned with that at 599px or 601px. See attached screen capture (animated gif, click to play). There's also inconsistencies with the header icons at these breakpoints, as well as the blue line above the total impressions section (as per screenshot below and gif on the Asana ticket)

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/74b5d762-6d1c-4156-aff6-00b195b3dacb)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The header bar icons should not have "special" behavior at a viewport width of exactly 600px. Right now there appears to be an issue with media queries that at exactly 600px the UI there behaves neither like <600px nor like >600px which is an odd experience. Specifically:
    * The URL search icon should not be the only icon that shows its label while the other icons don't have the label.
    * The date picker icon should not be accompanied by the dropdown caret without also showing its label.
    * It doesn't really matter whether at 600px those components behave like >600px or like <600px, but it should be changed to be consistent one way or the other.
* Two more general fixes should be made that don't have to do with the 600px viewport:
    * The content of the `DataBlock`s (specifically in the new Search Funnel "Overview for the last 28 days" widget, but probably also in general) should be vertically aligned to the top, so that the (e.g. blue) line above that content isn't too far away from it on certain viewports.
        * To see this problem, make sure Analytics is not active and resize your window to be between ~900-1000px wide. The blue Analytics CTA is then relatively tall which makes the `DataBlock` content appear too far away from the line above.
    * On viewports where the Analytics CTA in the new Search Funnel "Overview for the last 28 days" widget is displayed below the two `DataBlock`s (see screenshot above), it should span the full width to not have that empty whitespace.

## Implementation Brief
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`,
	* Set `mdSize` to `4` for `quarterCellProps`
	* Set `smSize` and `mdSize` to `4` and `8` respectively for `halfCellProps`
* Using `assets/sass/components/global/_googlesitekit-data-block.scss`,
	* Set `justify-content: flex-start` for `.googlesitekit-data-block--button`
* Using `assets/sass/vendor/_mdc-button.scss`,
	* Update the media query to `$bp-mobileOnly` to include the `screen-reader-only` mixin for `.googlesitekit-plugin .mdc-button--dropdown .mdc-button__label`

### Test Coverage
* No new tests to be added.

## QA Brief

* Using the [Tester Plugin](https://sitekit.withgoogle.com/service/download/google-site-kit-tester.zip), enable the `unifiedDashboard` feature.
* Navigate to the Dashboard.
* Verify the header bar icons have a consistent layout at the mobile/tablet breakpoint crossover of 600px. The icon labels & dropdown caret should be visible at 600px and above. There should not be an layout which is *only* active at 600px.
**Mobile:**
![image](https://user-images.githubusercontent.com/18395600/145582246-eb7b4e43-806f-4cc3-a832-b25dae1556b8.png)
**Tablet:**
![image](https://user-images.githubusercontent.com/18395600/145582165-751b0f8c-b660-4b2e-9927-59002d50596c.png)
* Verify the `DataBlock` content in the Search Funnel widget has been aligned to the top:
**Before:**
![image](https://user-images.githubusercontent.com/18395600/145582650-7f68bfdf-77a0-444d-8749-649cd8693edd.png)
**After:**
![image](https://user-images.githubusercontent.com/18395600/145582461-71ef4e62-5e18-4093-8fac-caabc8e20585.png)
* In the mobile viewport, verify the Analytics CTA spans the full width of the Search Funnel widget. The PR also fixes the same issue for the Analytics Error block. These views can also be verified in Storybook, in the following stories:
* https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidget--ready-with-analytics-not-active
* https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidget--error-analytics

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ❌ 

@techanvil 

**Issue:** 
At 599PX, only date picker has title/drop-down caret. As per AC, there should not have inconsistency only at one size. Behavior should be consistent.
Tested on—Chrome Dev tool.
Kindly see screenshots at 598px, 599PX and 600PX to see the inconsistencies.
Let me know if you require more details.
<details>

![image](https://user-images.githubusercontent.com/94359491/146011617-a12943bb-ae80-4d0b-ba95-37469d4b252b.png)

![image](https://user-images.githubusercontent.com/94359491/146011651-17150b1e-a75f-4332-87cd-f7ec747753b4.png)


![image](https://user-images.githubusercontent.com/94359491/146011564-86f3b046-97b9-4371-8db8-5adae6f5b3d7.png)


</details>

**Comment by techanvil** [comment]
Hi @mohitwp, that's a bit odd. Not sure what's causing this discrepancy, as when I'm testing locally I don't see the date picker caret/text at 599px.

https://user-images.githubusercontent.com/18395600/146043578-e506bd0c-1d8e-4f6f-86e0-de9d751cf7c1.mp4

Could you please try again and double check that you don't have any cached styles for the site? If you are still finding the same issue then I suggest we jump on a call to try to figure this one out. Thanks

**Comment by mohitwp** [comment]
@techanvil Well, I tried after removing cache and still facing issue when I'm using Windows. 
I tried to figure out and found that this issue is coming only on Windows system. 
I tested this on Mac OS using BrowserStack, and this issue is not coming in Mac OS. 

Windows >Edge, Firefox, Chrome > Issue exists.
MAC > Chrome, Safari > Issue not exists.

Kindly check and let me know if you need to discuss this on call. We will jump on a call to sort this out.

Thanks !

cc @wpdarren

**Comment by techanvil** [comment]
Hey @mohitwp, thanks for investigating further - that's useful to know! I'll see about getting this fixed on Windows :+1:

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified:**

- Now, the header bar icons have a consistent layout at the mobile/tablet breakpoint crossover of 600px. The icon labels & drop-down caret are visible at 600px and above. There is not any individual which is only active at 600px.
- The DataBlock content in the Search Funnel widget has been aligned to the top.
- Tested with latest version of browsers - Chrome, Safari, Firefox and edge.

<details>

![599px](https://user-images.githubusercontent.com/94359491/146191996-269a9200-2597-4e9e-92ee-9832e29bc0f8.png)
![600px](https://user-images.githubusercontent.com/94359491/146192010-ee6c1080-1547-45b0-a05c-5217aca6a634.png)
![601px](https://user-images.githubusercontent.com/94359491/146192014-971827ac-490d-4292-a7f9-e0f85bd395df.png)


</details>
