### ISSUE TITLE
Lost focus state on search button when closing the search form

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4493]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480648448654

The `unifiedDashboard` feature flag must be enabled.

1. Using the keyboard, open the entity search form.
2. Press the ESC key to close the search form.
3. Notice how the focus state is "lost"

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the URL search field in the `unifiedDashboard` is closed (e.g. by clicking the X or pressing the esc key), the focus should land on the URL search button (which can be used to open it again). Right now the focus gets "lost".

## Implementation Brief

*  When the search field is open but then closed, focus should be moved to the "URL Search" button here: https://github.com/google/site-kit-wp/blob/4e5bb3717b1bfd9a240a079ec4150c7d2b4e28e0/assets/js/components/EntitySearchInput.js#L148
* This should only happen after the "URL Search" button has been closed, eg. focus should not be assigned on mount. A `useUpdateEffect` hook is probably the right one to use here with `isOpen` as a dependency.

### Test Coverage

* No tests for this behaviour are needed.

## QA Brief

* Pressing the "Escape" key or clicking the close/"X" icon on the URL Search after opening it should leave the "URL Search" button focused.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
If the IB here looks good feel free to move this one right into Code Review, as there's already a PR created to verify the IB here would work 🙂

**Comment by eugene-manuilov** [comment]
Thanks, @tofumatt, but could you, please, avoid using PR-as-IB approach since, if I remember correctly, we discourage it? Could you please add actual IB? Also there is one problem with the approach implemented in your PR: it sets focus on the search button on initial load which shouldn't happen. The focus should be set only when the user closes the URL search.

**Comment by tofumatt** [comment]
Fair enough, especially as that approach does have that bug. I've amended the IB, but feel free to assign this issue to me as I'll finish the execution to fix the bug after the IB is approved 🙂

**Comment by eugene-manuilov** [comment]
Thanks, @tofumatt. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified :**

- Now Pressing the "Escape" key or clicking the close/"X" icon on the URL Search after opening it leave the "URL Search" button focused.
- Verified on the latest versions of Chrome, Firefox, Safari and Edge.
