### ISSUE TITLE
All Traffic Widget tooltip overlaps header and unified dashboard navigation

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4496]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480648448634

Click on a slice of the All Traffic widget pie chart
Tooltip is displayed.
Scroll down the page.
Notice how the tooltip overlaps the unified dashboard header and navigation.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/30a1947b-630f-46d9-82fd-a468ba706295)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No tooltips from Google charts (e.g. in the All Traffic widget, but also elsewhere) should ever overlap the sticky header in the Site Kit dashboard.
* This should be fixed for both the unified dashboard and the current dashboard (i.e. with and without the `unifiedDashboard` feature enabled).

## Implementation Brief
* `.google-visualization-tooltip` should have a `z-index` lower than that of the header and sub header. In this case, it should be `8` but some thorough QA is needed to confirm this works well in all scenarios.

### Test Coverage
* No new tests to be added.

## QA Brief

- Go to the Site Kit dashboard
- Click on the `Traffic` piechart slices like `Organic search`
- Make sure the tooltip is visible
- Scroll down and verify the tooltip doesn’t overlap with the header
- Verify the same behaviour for other slices of the piechart as well
- Scroll down to the search funnel graph
- Click anywhere on the graph and make sure the tooltip is visible
- Scroll down and verify the tooltip doesn’t overlap with the header
- Disable the unified dashboard feature
- Verify the same behaviour for all the graphs and the piechart
- Verify the same behaviour on the mobile view as well

## Changelog entry

* N/A

**Comment by eclarke1** [comment]
@wpdarren to please check if this exists elsewhere already in GH

**Comment by wpdarren** [comment]
@eclarke1 not on GH, its related to Unified Dashboard but a bit of an edge case depending on if the user scrolls up while the legend is still activated (which I am sure someone will!) I've updated Asana too.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On the Traffic piechart slices, the tooltip is visible. When scrolling down and up, the the tooltip doesn’t overlap with the header. 
- On the Search funnel graph when you click on a graph the tooltip is visible, and when you scroll down and up, the tooltip doesn’t overlap with the header. 
- With unified dashboard feature disabled, the same behaviour occurs for the graphs and piechart.
- For mobile and small screen sizes the same behaviour occurs.

https://user-images.githubusercontent.com/73545194/145815038-56025d9c-9120-46b7-9052-073e9246d29d.mp4

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/145816088-1d9ee1a8-37e2-4c5e-b768-a1ed4cc5ef16.png)

![image](https://user-images.githubusercontent.com/73545194/145816111-d5b2798c-c6f5-471f-b47a-50caaf846704.png)

</details>
