### ISSUE TITLE
Content Overlaps on Mobile [Page Speed]

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4497]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480843200390

The module of page speed overlaps in mobile view,  (iPhone 6, from Chrome Simulator) from the first Tab In the Lab.

![image](https://user-images.githubusercontent.com/1621608/151138285-6f8ef4a1-b719-456c-9be3-ce2eb4cbfc83.png)

[Full size screenshot](https://camo.githubusercontent.com/c5315fdae61de6f99df19aee6182b28eb719896b89d3471cdf96d744d785f0d2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565326164333830336333373435363932333164386364372f35313461383061392d323631312d343562392d616462622d623438623732636431306231)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The dashboard PageSpeed widget footer styling should be updated as follows
    * For all viewports, the items should have the proper grid gap between them horizontally
    * For mobile viewports the source link text should be right aligned
    E.g.  
    ![image](https://user-images.githubusercontent.com/1621608/151138027-cb35c4fc-a4bc-403b-a89b-990973d4c75d.png)

## Implementation Brief
* Using `assets/sass/components/dashboard/_googlesitekit-DashboardPageSpeed.scss`,
	* Set `gap` to `16px` for `.googlesitekit-pagespeed-report__footer`.
	* Set `text-align` to `right` for `.googlesitekit-pagespeed-report__footer p`.

### Test Coverage
* No new tests to be added.

## QA Brief

* QAing this would require checking the Page Speed section in the Site Kit Dashboard in mobile view (iPhone 6, from Chrome Simulator) and making sure the footer row content doesn't overlap.
* It should look like the above screenshot in the Acceptance Criteria.

## Changelog entry

* Update styles of the PageSpeed Insights plugin to show footer correctly on mobile.

**Comment by eclarke1** [comment]
@wpdarren to check if this ticket exists elsewhere in GH

**Comment by wpdarren** [comment]
@eclarke1 funnily enough it's on my Asana task of small bugs to create tickets for that I found in this latest release QA, so I will remove it now. Although I would say it is not part of Unified Dashboard because its also an issue on current PageSpeed widget throughout the plugin.

**Comment by aaemnnosttv** [comment]
How does this look/sound @marrrmarrr ? cc: @felixarntz

**Comment by marrrmarrr** [comment]
@aaemnnosttv the ACs LGTM, seems like this should be enough to ensure no weird overlaps.

**Comment by eugene-manuilov** [comment]
IB ✅
