### ISSUE TITLE
The URL search input text overflows into the close button

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4500]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480204836398

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/64b69901-a519-4581-a6b1-7363e4959252)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The input text field of the URL search component has the right padding that equals the width of the close button.

## Implementation Brief
* Set the `padding-right` to `32px` for `.googlesitekit-entity-search .autocomplete__input`.

### Test Coverage
* No new tests to be added.

## QA Brief

- Click the search button on the Site Kit dashboard header
- Enter a long search term (text)
- Verify that the text doesn’t overflow into the close button
- Verify the same with the different screen sizes

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
> Set the padding-left to 32px for .googlesitekit-entity-search .autocomplete__input.

@asvinb shouldn't it be `padding-right`?

**Comment by asvinb** [comment]
🤦  you're right @eugene-manuilov . thanks!

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb! IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified:**

- Now the text doesn’t overflow into the close button.
- Tested on latest version of Chrome, Edge, Firefox, and Safari.
- Also tested on android and iOS devices.

![CloseIcon](https://user-images.githubusercontent.com/94359491/145820326-02dc984f-ec7a-47b9-9c98-4ca134ab6014.png)
