### ISSUE TITLE
Space is minimal between title and subtitle

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4501]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480843200400

This behavior happens in iPhone 6, using chrome emulator device.

See how: 

Finding how your audience is growing 
Track traffic to this page over time.

Are really close in this view port and there is minimal space between these 2 sections.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/7dc99932-3f5d-4650-bd3d-3a08dc90193d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The widget area header has the correct margin between title and subtitle on the mobile screen

## Implementation Brief

* Add a very small bottom margin (`0.125rem` seems appropriate) to `.googlesitekit-widget-area-header__title` (https://github.com/google/site-kit-wp/blob/e6b6890a69213a970cec7c1ca1837e72df9f1150/assets/sass/widgets/_widget-area.scss#L37). I don't see a variable for that kind of spacing anywhere obvious, but if there is one feel free to use it. Otherwise that margin seems fine.

### Test Coverage

* VRTs might need updating.

## QA Brief

- Go to Site Kit dashboard
- Check the widget area header title and subtitle
- Verify the title and subtitle have the correct margin (title should have margin-bottom)

## Changelog entry

* Improve the spacing between section titles/subtitles in the Unified Dashboard.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified:**
1) Bottom margin set to `0.125rem` for `.googlesitekit-widget-area-header__title` .
2) Now Spacing improved between title and subtitle in i-Phone 6 . Tested using BrowserStack and chrome emulator.

<details>

![widget_1](https://user-images.githubusercontent.com/94359491/148339842-a309ca0c-c4fe-4e74-9909-8ef2896725dd.png)
![widget_2](https://user-images.githubusercontent.com/94359491/148339852-d1500920-8c07-48aa-b99b-c2ec7d24e5bc.png)

</details>
