### ISSUE TITLE
URL Search "No results found" has link-style cursor on hover, but shouldn't as there's no associated action

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4503]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201481416683003

When there are no results, the mouse cursor shouldn't change, as it implies clicking the "No results found" link will do something.

## Screenshots

![2021-12-07 14 56 48](https://user-images.githubusercontent.com/90871/145901362-50f3878f-e504-42f1-87ee-4aae6b67200a.gif)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When "No results found" is displayed in the URL Search bar, there should be no hover/focus effects/styling that implies the user can interact with the "No results found" autocomplete option.
  * (As a side note, this component should really be using a dedicated autocomplete and not a combobox, because technically the user can still use the Down arrow key on their keyboard and make the "No results found" option accessible. The Reach documentation mentions this, but a ComboBox should be used when free-form text is allowed but there are suggestions to make. In our case, we don't really allow searching here with any input that doesn't return a result from our API response. But still, at least discouraging users from seeing it as interactive—which this issue does—will help a fair bit without us needing to rewrite the entire component 😅 

## Implementation Brief

* Add a new class to the `ComboBoxOption` component rendered at https://github.com/google/site-kit-wp/blob/e6b6890a69213a970cec7c1ca1837e72df9f1150/assets/js/components/PostSearcherAutoSuggest.js#L175, when there are no search results. Something like `autocomplete__option--no-results` would be fine.
* Use this new class to add styles to this component, something like:

```css
.autocomplete__option--no-results,
.autocomplete__option--no-results:hover,
.autocomplete__option--no-results[data-highlighted] {
	background: none;
	cursor: default;
}
```

would work.

### Test Coverage

* No new tests needed; VRTs likely won't need updating for this one.

## QA Brief

- Go to the Site Kit dashboard
- Type a random string in the Entity Search input
- Make sure you get `No results found` in the auto-complete
- Hover on `No results found`
- Verify the cursor pointer should have been removed

## Changelog entry

* Fix styling on "No results found" autocomplete message in Unified Dashboard.

**Comment by eugene-manuilov** [comment]
@felixarntz or @tofumatt correct me if I am wrong, but as far as I remember we don't want to display the `No results found` message in the new unified dashboard. Is it still the case?

**Comment by tofumatt** [comment]
@eugene-manuilov Not _quite_. In the old URL search the "No results found" message would be shown when there were no results (which is correct), but due to a bug with the old search logic it would also be found _while searching_, because searching reset the number of results to zero and the component considered that empty. So during search it would show the "No results found" message, which was an odd UX. The ACs for that issue (#4049) state:

> "No results" should only be shown once the result is complete and empty. Essentially, where it currently says "No results" in this screencast, should be preview/loading lines instead.

That meant to say the "No results" is valid, but only when the search is complete and there aren't any results.

**Comment by eugene-manuilov** [comment]
Ok, thanks, @tofumatt. IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified:**

- Cursor point is removed and there is no hover/focus effects/styling that implies the user can interact with the “No results found” autocomplete option.
- Verified on Chrome, Safari, Firefox, and Edge browsers.


https://user-images.githubusercontent.com/94359491/147059119-60ea805f-ae1a-4801-899a-ad0b188daec0.mp4
