### ISSUE TITLE
Search take a long time when PSI queries are running

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4505]
## Bug Description

This issue was raised as part of Unified Dashboard bug bash but is actually unrelated, please see ticket https://app.asana.com/0/1201438453642602/1201480648448640

Upon a fresh Site Kit install/reset, PSI is enabled by default and takes a lot time to grab the data. While those PSI queries are running, if you search for an entity, it takes a lot of time to display the results.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/4e3ff753-d531-45e1-aef0-7014881cd103)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz this may be a non-issue now that PSI will only load when the section is active/in-view. Thoughts?

**Comment by felixarntz** [comment]
@aaemnnosttv Hmm, kind of, but also not. This reminds me of that other issue I sometimes have, where my browser is even blocking a navigation request until the PSI request has gone through. I think we should eventually still see if there's a way that these PSI requests do not block the rest of the page, maybe we can somehow deprioritize them?

I suggest we put this into the backlog.

**Comment by aaemnnosttv** [comment]
@felixarntz sounds good – we now have the ability to cancel a request built into our fetch api, but that might not be easily doable when that fetch is called in a resolver.

I'll move it to the backlog 👍

**Comment by felixarntz** [comment]
I have run into a similar problem myself, however this is most likely happening due to a very low limit of maximum PHP processes on the server environment. There isn't really anything worth actioning on here, so closing this one.
