### ISSUE TITLE
Selecting a report range does not scroll to the section

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4506]
## Bug Description

This issue was raised as part of Unified Dashboard bug bash but is actually unrelated, please see ticket https://app.asana.com/0/1201438453642602/1201480843200412

When you are in a different section and the analytics report is not displayed in the viewport I would expect that clicking a date range from the report would take me back to the section where the report is displayed.

Currently clicking any date range from the report does not take me back to the widget with the details of the report.

Steps to replicate:

Scroll at the bottom or into a section where the module is no longer visible
Select any date range, different than the current one
Observe how you remain on the same section, no scroll takes place.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/48af5b31-000b-4d05-866e-bb769c009706)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz my understanding was that we agreed this was expected and a non-issue but correct me if I'm wrong?

**Comment by felixarntz** [comment]
@aaemnnosttv Yeah I think so There isn't really "a section" to scroll for changing the date range.
