### ISSUE TITLE
User is being regularly disconnected from Site Kit on several of their sites

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#4511]
## Bug Description

[A user in the support forums](https://wordpress.org/support/topic/i-find-the-plugin-deactivated-really-often/) is reporting that they are being disconnected from Site Kit on several of their sites regularly. 

When checking their 'Manage Sites' page they confirmed that they have 34 sites currently active. The user has filled out the [Site Health form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjjdniUO6L6D4WyEo99FG5uO-wh9RaKe0-A3f7n566n97vQ04AeCUjgG_bRI0FMT2s). The user mentions that all sites are configured and hosted differently but all connected to the same Google account. 

They only have a single admin user on all sites which is the users account but do have other users such as editors. This seems to happen randomly but often with it happening to all sites at some point.

Their site count of 34 doesn't reach a max limit and as they only have a single admin user on each site this shouldn't be hitting the refresh token limit either. 

Some of the sites the user has given us experiencing this issue are: 

- smarteus.it
- ingegneregarra.it
- energiesostenibilisrl.net

## Insights & Troubleshooting Checks performed

- [x] Confirmed no modification of Site Kit placed snippet
- [x] Front end check (mixed content, minified content, combined JS) - no issues
- [x] Checked users Site Health info, no identified causes
- [x] Checked number of active sites user has connected with Site Kit - 34 sites
- [x] Check how many connected WordPress accounts to a single Google account - Just their admin account on all sites

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@adamsilverstein Hi there! We discussed this one in the #google-open channel on 8 December and I believe you were going to do some checks on your side. This user has been awaiting a reply for quite some time if you have a chance to look into this ASAP. Thanks!

**Comment by adamsilverstein** [comment]
Hi @adamdunnage -

I spent some more time debugging this user account to see what might be causing them to get disconnected. I see they have close to the oAuth refresh token limit of 50 so I suspect this might be the source of the issue.

For reference:

>  Limits apply to the number of refresh tokens that are issued per client-user combination, and per user across all clients, and these limits are different. If your application requests enough refresh tokens to go over one of the limits, older refresh tokens stop working. 

[reference](https://developers.google.com/identity/protocols/oauth2#:~:text=Note%3A%20Save%20refresh,tokens%20stop%20working.)

And then later:

> There is currently a limit of 50 refresh tokens per Google Account per OAuth 2.0 client ID. If the limit is reached, creating a new refresh token automatically invalidates the oldest refresh token without warning.

[reference](https://developers.google.com/identity/protocols/oauth2#:~:text=There%20is%20currently%20a%20limit%20of%2050%20refresh%20tokens%20per%20Google%20Account%20per%20OAuth%202.0%20client%20ID.%20If%20the%20limit%20is%20reached%2C%20creating%20a%20new%20refresh%20token%20automatically%20invalidates%20the%20oldest%20refresh%20token%20without%20warning.)

Even though the user isn't quite at the limit with Site Kit sites, they may have other oAuth connections set up that could be adding towards a refresh token limit. Site Kit holds on the refresh token to stay connected to the oAuth service, if the user hits the refresh token limit, their oldest refresh token will be invalidated. The next time they log into that site they will need to re-authenticate to get access to the API data.

This limitation isn't ideal and we are looking at ways to fix it. My recommendation for now would be to limit the number of sites connected for each account to around 20 (or maybe 30), creating new accounts as needed to manage additional connected sites.  That will likely stop the disconnects if this is indeed the source of this user's issue.

**One other way** I could see sites getting disconnected  would be a security or host plugin setting that refreshed the cryptographic salts stored by WordPress. Changing these salts would force users to become logged out, and I can imagine some plugins or a host might configure sites to refresh salts as a hardening measure (it would invalidate all logins). I haven't seen this in typical configurations, but perhaps the user (or host) has some unusual config that does this?

**Comment by bethanylang** [comment]
Thank you so much for digging into this, @adamsilverstein. Closing.
