### ISSUE TITLE
Implement new Idea Hub prompt banner and widget notification

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4514]
The banner notification and "in-widget" notification to prompt users to activate Idea Hub have not received the attention they should have so far in our rollout of the feature. Both notifications have therefore been redesigned, and this issue is about implementing those designs.

![Screen Shot 2021-12-08 at 8 48 25 AM](https://user-images.githubusercontent.com/3531426/145248891-0e109202-00ab-4f7d-a6af-554eeb6f8c6f.png)

See https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=21473%3A4154

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The current Idea Hub prompt banner notification should be replaced with a new notification following the design from https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=21473%3A4193.
    * If possible, the new banner notification should still rely on the standard `BannerNotification` component, even though it looks quite different from others that we have. That way we don't have to re-implement all the functionality that is built into that base component.
    * A challenge here may be that the new notification looks quite different from others that we already have. Let's try to rely on custom CSS as much as possible, but it's also okay to add extra props to `BannerNotification` to support any new UI patterns needed.
    * As always, we shouldn't recreate the Figma design 100% accurately for areas where it diverges from our default pattern (for example the new notification should still use the typical button styles and bottom shadow from that other Site Kit notifications have). The main thing that is different in this notification is the overall layout.
* The current Idea Hub in-widget prompt should be replaced with a new in-widget prompt following the design from https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=21473%3A4157.
* Both notifications should continue to rely on the same dismissal behavior they use today.

## Implementation Brief
* Using `assets/js/components/notifications/BannerNotification.js`,
	* Refactor code to use the `Grid`, `Row` and `Cell` components for the layout.
	* Add new string prop `badgeLabel`:
		* If `badgeLabel` is not empty, pass the value as prop to the `label` prop of the `Badge` component. The latter should be rendered after `title`.
	* Update the `format` prop types to be strictly either of the following:
		* `small`
		* `large`
		* `larger` (new)
	* The grid contains the following containers from a high level for:
		* the `logo`
		* `SmallImageSVG`
		* `title` and other details, will be know as the `details` container for easier reference.
		* `WinImageSVG`
	* The cell width for containers housing the `logo` (12) and `SmallImageSVG` (1) will always remain unchanged. However the cell width for the `details` and `WinImageSVG` vary depending on the `format` prop. If the format is:
		* `small` or `large`:
			* For `details` container:
				* `lgSize`
					* Default: `12`
					* If `WinImageSVG` only is not empty, decrease the size by `4` (for e.g `8`)
				* `mdSize`
					* Default: `8`
					* If `WinImageSVG` only is not empty, decrease the size by `2` (for e.g `6`)
				* `smSize`
					* Default: `4`
				* For all of the above,
					* If `SmallImageSVG` is not empty, decrease the size by `1`
					* If `type` is not empty, decrease the size by `1`
				* The general idea is that on the different breakpoints, the columns total must be:
					* `smSize` -> 4
					* `mdSize` -> 8
					* `lgSize` -> 12
			* For `WinImageSVG` container:
				* `lgSize: 4`
				* `mdSize: 2`
				* `smSize: 4`
		* `larger`:
			* For `details` container:
				* `lgSize`
					* Default: `12`
					* If `WinImageSVG` only is not empty, decrease the size by `7`
				* `mdSize`
					* Default: `8`
					* If `WinImageSVG` only is not empty, decrease the size by `4`
				* `smSize`
					* Default: `4`
				* For all of the above,
					* If `SmallImageSVG` is not empty, decrease the size by `1`
					* If `type` is not empty, decrease the size by `1`
			* For `WinImageSVG` container:
				* `lgSize: 7`
				* `mdSize: 4`
				* `smSize: 4`
	* Update the styles for `WinImageSVG` when the `format` is `larger` so that the `max-width` is not limited to `200px` as it is currently for `large` format.
	* Using `assets/js/components/notifications/IdeaHubPromptBannerNotification.js`,
		* Remove the `SmallImageSVG` and `type` props.
		* Add the following new props:
			* `WinImageSVG` which is the SVG image from Figma (to be placed in `assets/svg/graphics`)
			* `badgeLabel` set to translated `Experimental` string (Disregard the "New Experimental Feature" label in Figma since it's not consistent with what we currently have)
			* `learnMoreLabel` set to translated `Learn More` string.
			* `learnMoreURL` which links to the external link `https://sitekit.withgoogle.com/documentation/idea-hub-module/`.
		* All tracking logic remains the same.
		* Update the `format` prop to `larger`
	* Style notification as per the designs in Figma. Most notable changes are:
		* When the `format` is large, there is no bottom padding for the notification wrapper so that the SVG is flushed to the bottom of the notification. **Will this type of layout be used more often in the future or it's specific to Idea Hub where the image is flushed to the bottom?**
		* Disregard font size, color changes from the designs in Figma.
	* Using `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js`,
		* Keep most of the code except for the following:
			* Component must be rendered as per the designs in Figma
				* Use the same components where applicable (`Badge` for e.g) as in `assets/js/components/notifications/IdeaHubPromptBannerNotification.js`.
				* Use the same assets, for e.g the SVG graphic.
			* The following new events should be tracked:
				* Before calling `navigateTo`, call `trackEvent` with the following parameters:
					* category: `IDEA_HUB_GA_CATEGORY_WIDGET`
					* event: `activate_module`
					* label: `idea-hub`
	* Update the styles for `DashboardCTA` with the following notable changes:
		* The CTAs are below the graphic.

### Test Coverage
* No new tests to be added.

## QA Brief
* Enable the `ideaHubModule` feature flag.
* Go to the main dashboard.
* Check if the notification at the top of the page is rendered as per the AC and the Figma designs.
* Check if the Idea Hub widget displays a prompt to connect the module as per the AC and Figma designs.
* When the Idea Hub module is not connected, the widget should be full width across all breakpoints.
* When the Idea Hub module is connected, the widget should be half width as from the desktop breakpoint (960px)
* Since the changes affect all notifications, check in Storybook if all the notifications render correctly across all breakpoints. There should not be any regressions noted in the layout.

## Changelog entry

* Update Idea Hub prompt banner notification with new design.

**Comment by felixarntz** [comment]
@marrrmarrr I'm gonna assign this to you, just because of the one thing in the Figma file we were thinking to change. Once that change has been made, please move this over to IB! :)

**Comment by eclarke1** [comment]
@felixarntz just updated the comment above to reference the new link placement now @samitron7 has moved the file to our master Idea Hub Figma file if that's ok?

**Comment by felixarntz** [comment]
Thanks @eclarke1, updated that in the ACs as well. The latest update includes the UI changes asked, so I'm gonna move this over to IB!

**Comment by asvinb** [comment]
@aaemnnosttv I noticed a few inconsistencies when working on the IB and am not sure whether it's intentional. Maybe you can help out here in case I'am missing something. I've noticed that the logic to display the cells is not always right, with sometimes a cell falling outside of the grid row. For e.g if the [`format` is `small`](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/BannerNotification.js#L212-L214), the cell widths are all wrong if `WinImageSVG` [is displayed](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/BannerNotification.js#L409-L411). On desktop, the total width can be  `11` + `4` whereas the maximum can be `12` on desktop. So I've written the IB to prevent those inconsistencies and make the layout more robust and flexible based on what is being displayed, which in turns make the `small` and `large` format redundant. So any context here is welcomed 👍 

@felixarntz Can you add the tracking details? Shall we track the same events for both use of the notification, i.e the notification shown within the header and the one shown within the widget?

Thanks!

**Comment by felixarntz** [comment]
@asvinb Thanks, clearing up those problems here makes sense, we should make sure the total widths cannot exceed the expected maximum column number per viewport, like you're saying. As far as I can tell, the IB looks good around that.

Something that I do have concerns over is using the `BannerNotification` within the widget UI. That's different from how it's done now, and I would prefer if we kept the code in `DashboardCTA` independent of `BannerNotification`, since the widget CTA is explicitly not a `BannerNotification`, and the `BannerNotification` component comes with some behavior that we may not want here. Furthermore, that proposed `stacked` format isn't really a format any banner notification should have - it would only be necessary to reuse the component in `DashboardCTA`, which is a bit misleading.

Can we keep the two notifications separate and, if anything, use common UI components between them?

> Can you add the tracking details? Shall we track the same events for both use of the notification, i.e the notification shown within the header and the one shown within the widget?

The events should all be left as-is (separate between the two, another sign the code should be kept more separate), except one thing: The `DashboardCTA` (in-widget prompt) should also fire an `activate_module` event with label `idea-hub`, right after `prompt_widget_setup`. The event category should be the same as elsewhere.

**Comment by asvinb** [comment]
Sounds good @felixarntz . IB updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by eclarke1** [comment]
@aaemnnosttv @felixarntz could I kindly ask you to add an estimate here as @asvinb is on leave today. Or @asvinb to please add tomorrow if you don't get round to this today. Thanks.

**Comment by asvinb** [comment]
@eclarke1 Estimate added.

**Comment by asvinb** [comment]
@aaemnnosttv I left a comment for you here: https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA?node-id=21473:4157#135386158 Let me know what you think.

**Comment by aaemnnosttv** [comment]
@felixarntz – thoughts about @asvinb 's [comment here](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA?node-id=21473:4157#135386158)? Can we maybe change the IH widget to not match the height of the adjacent widget?

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb I don't think we should allow decoupling the height for widgets that sit in the same row.

What was the viewport/breakpoint that [this screenshot](https://cloudup.com/cBJRVBbEJvQ) was taken? Potentially we can solve the problem by adjusting the required widget width registered for that breakpoint? In the viewport from the screenshot it looks a bit unfortunate anyway with both widgets having too little width, things are for example also very squished in the popular keywords widget there, and if the two were full width in that viewport, both would look better. So that would be the thing I'd look into first.

Other than that, probably the most appropriate would be to have an alternate portrait version of the graphic to show when applicable. But I'm also not sure we should block the issue on this point, we can also iterate once UX comes up with a more flexible solution.

**Comment by asvinb** [comment]
@felixarntz The screenshot was taken at 961px which equals to the `desktop` breakpoint and that's the last breakpoint within our grid system. I can see 2 issues we can move forward and let me know your thoughts:

1. use a portrait version of the graphic thus keeping the widgets side by side.
2. display both widgets full width **if** the Idea Hub module has not been set up. If the latter is setup, we revert to having the widgets side by side. [preferred solution]

Let me know your thoughts.

**Comment by felixarntz** [comment]
@asvinb Yeah, I think the 2nd approach is what I'm leaning towards as well. 👍

**Comment by aaemnnosttv** [comment]
@felixarntz in order to conditionally register a widget based on another module's activation/connection, we'd need to update the `Widgets` API to expose `select` somehow. What do you think?

**Comment by asvinb** [comment]
@felixarntz Temporarily assigning task to you following @aaemnnosttv 's question.

**Comment by felixarntz** [comment]
@aaemnnosttv Overall that makes sense. Could we allow passing a function for the width argument and if it is a function, call it at the right place and pass the registry (or just `select`) to it?

Alternatively, if we wanted a more quick/pragmatic approach, I think we could also check "on pageload" whether the module is active or not and simply update the registered width based on that. This way is definitely more hacky, but it also avoids building an API that we may not be confident about in terms of whether it's the right approach - and it would work because there's always a new pageload involved in changing module activation anyway (or it doesn't even happen on the dashboard).

cc @asvinb

**Comment by aaemnnosttv** [comment]
> Could we allow passing a function for the width argument and if it is a function, call it at the right place and pass the registry (or just `select`) to it?

@felixarntz I thought about this too, but more like a function for all the arguments rather than just one or two.

Alternatively, we could change where the widget is registered (dispatching `registerWidget` directly from `registerModule` where we already have access to the store).

The quickest/simplest would be to provide `select` as `widgets.select` on the instance like so and just mark it private for now and we can revisit this with a better solution if we have one later 😄 

![image](https://user-images.githubusercontent.com/1621608/150305602-bf93b506-060f-4026-9a96-12253791fa04.png)

**Comment by felixarntz** [comment]
@aaemnnosttv Having `Widgets.select` SGTM for now!

**Comment by aaemnnosttv** [comment]
@asvinb let's go with this change above for now. Then in the module's `registerWidgets`, you'll be able to access the registry's `select` on the given `widget` instance 👍

**Comment by asvinb** [comment]
@aaemnnosttv PR is good to another round of review 😁

**Comment by mohitwp** [comment]
### QA Update ❌ 

@asvinb I noticed implemented fonts size is different from the Figma design. Is it intentional? 

<details>

![image](https://user-images.githubusercontent.com/94359491/155143706-3d1b93d6-a000-461e-b7e1-3a0935419f4d.png)

![image](https://user-images.githubusercontent.com/94359491/155143771-e2261cee-f3a8-44ec-9002-9103cbbabb43.png)

</details>

**Comment by asvinb** [comment]
@mohitwp Yes it's intentional as we are using the existing styles we have in our codebase so they is consistent. The Figma designs did not take into account what we already have. :)

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified :**

- Notification at the top of the page is rendering as per the AC and the Figma designs.
- Idea Hub widget displays a prompt to connect the module as per the AC and Figma designs.
- When the Idea Hub module is not connected, the widget is full width across all breakpoints.
- When the Idea Hub module is connected, the widget is half width as from the desktop breakpoint (960px)
- Verified on Chrome,Firefox, Safari and Edge.
- Verified on android mobile and tablet.
- Verified on iPhone 13 and iPad 12.

**Comment by felixarntz** [comment]
### Approval ⚠️ 

While we originally decided to move forward with making the notification full-width on desktop when the module isn't activated, during the review together with @marrrmarrr it became clear that this is not the desired behavior here. This widget should remain half width on desktop, also in the new design implemented here. We've played around with the styling a bit to find a solution that is straightforward enough and an acceptable trade-off that doesn't require us to go back to the drawing board and deal with the complexities of choosing from multiple SVGs based on viewport and height of the neighboring widget.

Let's do it as follows:
* Change the Idea Hub widget registration back so that it is always `HALF` width on desktop too.
* Vertically align the items in `.googlesitekit-idea-hub__dashboard-cta` to the top (i.e. use `justify-content: flex-start`), so that any whitespace present only appears at the bottom of the widget box.
* Change the style on the `svg` so that, in addition to the existing `max-width: 100%`, it has a `min-width: 90%` directive as well. This ensures that even on larger screens the graphic appears slightly bigger to take more of the available space which makes it work a bit more nicely.
    * After some testing of testing of different percentage values, we decided 90% looks good. We could have also put the width to 100% at all times, but then the graphic would have gotten a bit too massive and would have too little white-space around it.
* A follow-up PR for this should be opened based on and against `main`.

While this adds a bit of extra work here, we think this should be straightforward enough to do in time for the release on Monday. @asvinb Would you be able to tackle this one tomorrow? Feel free to assign to me for CR afterwards.

**Comment by asvinb** [comment]
@felixarntz Follow up PR has been issued where I've implemented the suggested changes. Can you check and let me know if everything's ok? 
https://github.com/google/site-kit-wp/pull/4890/files

**Comment by felixarntz** [comment]
### Approval ✅ 

This was just a visual change, no additional in-depth QA is needed here. The latest version is good to go. Attached are some screenshots:

**Large tablet**
<img width="907" alt="Screen Shot 2022-02-25 at 10 15 34 AM" src="https://user-images.githubusercontent.com/3531426/155766960-f26309c5-3b0f-4a6a-b409-eac5b8ac0bbc.png">

**Small desktop**
<img width="988" alt="Screen Shot 2022-02-25 at 10 15 51 AM" src="https://user-images.githubusercontent.com/3531426/155766973-92badeda-6b16-4a79-bb1e-0e049ebad946.png">

**Large desktop**
<img width="1587" alt="Screen Shot 2022-02-25 at 10 16 24 AM" src="https://user-images.githubusercontent.com/3531426/155766987-628d49d2-1297-4e58-9372-4c1e4c97d0db.png">
