### ISSUE TITLE
Update Tag Manager module datapoints for consistency

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#452]
Datapoints in the Tag Manager module should receive minor updates as outlined in the ACs.

Implementation brief should include which pieces of JS need to be updated and which e2e tests need to be updated (if any).

**Execution is blocked until #406 is merged.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tag Manager setup and querying Tag Manager data via API should still work as before.
* Datapoint parameters and return values controlled by the plugin itself should all be in camel case.
* Datapoints should be updated as follows:
    * GET connection → keep as is
    * GET account-id → keep as is
    * GET container-id → keep as is
    * GET list-accounts → GET accounts-containers
        * see above reasoning in Analytics; this datapoint does too much, so it should have a corresponding name; we need to allow ourselves to properly implement this in the future a distinct accounts datapoint
    * GET list-containers → GET containers
        * response format should be modified to only return the array in the current containers property (the wrapping object is redundant and unexpected)
    * POST connection → keep as is
    * POST account-id → keep as is
    * POST container-id → keep as is
    * POST save → POST settings

#### `GET list-accounts`
* Rename datapoint to `accounts-containers`
* Update usage
    - `TagmanagerSetup.requestTagManagerAccounts`

#### `GET list-containers`
* Rename datapoint to `containers`
* Update response format  
    ```diff
        diff --git a/includes/Modules/TagManager.php b/includes/Modules/TagManager.php
    index cc0d2b4..9ef2a80 100644
    --- a/includes/Modules/TagManager.php
    +++ b/includes/Modules/TagManager.php
    @@ -508,12 +508,9 @@ final class TagManager extends Module implements Module_With_Scopes {
                            $this->_containers_account_id = null;
                        }
     
    -                   $response = array(
    -                       // TODO: Parse this response to a regular array.
    -                       'containers' => $response->getContainer(),
    -                   );
    +                   $response = $response->getContainer();
     
    -                   if ( 0 === count( $response['containers'] ) && ! empty( $account_id ) ) {
    +                   if ( empty( $response ) && ! empty( $account_id ) ) {
                            // If empty containers, attempt to create a new container.
                            $new_container = $this->create_container( $account_id );
                            if ( is_wp_error( $new_container ) ) {
    ```
* Update usage
    - `TagmanagerSetup.requestTagManagerContainers`

#### `POST save`
* Rename datapoint to `settings`
* Update usage
    - `TagmanagerSetup.handleSubmit`

## Changelog entry

* Improve datapoint behavior of Tag Manager module for consistency.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Assigning to @adamsilverstein to update the datacache, otherwise this should be ready for review.
