### ISSUE TITLE
Update modules to be sharing-aware

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4521]
## Feature Description

With dashboard sharing, sharing is defined at the module-level. While dashboard sharing settings control who has access to the module data, knowledge of which modules are shareable at all will belong to the individual `Module` sub-classes and core `Modules` class. This is necessary for many reasons but one important one is simply for exposing which modules are shareable to the client for use in the sharing settings interface.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The base `Module` class should receive a new public `is_shareable() : bool` method with the base implementation returning `true` if all of the following are true, otherwise `false`
	* The module is connected
	* The module implements the `Module_With_Owner` interface
	* The module has at least one [shareable datapoint](https://github.com/google/site-kit-wp/issues/4474)
_Note this should not involve a new interface and or trait as with many other `Module_` attributes_
* The `Core\Modules` class should receive a new public `get_shareable_modules() : Module[]` method which returns the `Module` instances of all shareable modules (essentially a subset of `get_active_modules`)
* The response schema for each module returned by `core/modules` REST routes should be updated to include a new `shareable: Boolean` property (See `Module::prepare_module_data_for_response`)

## Implementation Brief

In `/includes/Core/Modules/Module.php` add a `public function is_shareable()` that returns `true/false` depending on the criteria outlined in the AC. (See #4474 and the `get_datapoint_definitions()` for finding if a module has a sharable datapoint)

In `/includes/Core/Modules/Modules.php` add a `public function get_shareable_modules()` that first fetches the active modules `get_active_modules()` and then filters (`array_filter()`) the result to only return those that are sharable (the above `is_shareable()` function).
Sample code:
https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Modules.php#L250-L258

Update `prepare_module_data_for_response()`
https://github.com/google/site-kit-wp/blob/develop/includes/Core/Modules/Modules.php#L907-L920
to add a property `'shareable' => $module->is_shareable()`

### Test Coverage

* Update `tests/phpunit/integration/Core/Modules/ModuleTest.php` to add tests `public function test_is_shareable()`
* Update `tests/phpunit/integration/Core/Modules/ModulesTest.php` to add tests `public function test_get_shareable_modules()`

## QA Brief

**QA:Eng**
- Verify `is_shareable()` method is added in `/includes/Core/Modules/Module.php`
- Verify `get_shareable_modules` method is added in `/includes/Core/Modules/Modules.php`
- Verify the logic is expected in both the methods
- Verify the newly added tests `test_is_shareable` and `test_get_shareable_modules` are passing
- Verify the result in the JSON response of the `core/modules/data/list` datapoint

## Changelog entry

* Update module classes to be sharing-aware.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by techanvil** [comment]
## QA: :white_check_mark: 

- Verified `is_shareable` method is added in `includes/Core/Modules/Module.php`.
- Verified `get_shareable_modules` method is added in `includes/Core/Modules/Modules.php`.
- Verified the logic in both the methods.
- Verified the newly added tests `test_is_shareable` and `test_get_shareable_modules` are passing.
- Verified the result in the JSON response of the `core/modules/data/list` datapoint.
