### ISSUE TITLE
Extend permissions passed to client for dashboard sharing

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4523]
## Feature Description

Building on the new capabilities added in https://github.com/google/site-kit-wp/issues/4522, we need to make some changes to make them available to the client due to the module-specific nature of most of them.

Later we will enhance the `hasCapability()` selector to support use with these new meta capabilities as nothing new is needed to support additional primitive capabilities.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `Permissions::check_all_for_current_user` should be extended to include all the new capabilities added in #4522
	- For module-specific meta capabilities, a key-value entry should be added for each shareable module (this will likely require adding `Modules` as a dependency)
* Keys for meta capabilities should be serialized as: `{base_capability}::{args_json}` where `args_json` are the JSON-encoded args passed for the meta cap (in this case only the module slug is used, but this could be used for others in the future)  
E.g. checking `googlesitekit_read_shared_module_data` for `analytics` would result in the following key: `googlesitekit_read_shared_module_data::["analytics"]`

## Implementation Brief

- In `includes/Core/Permissions/Permissions.php`:
    - Modify the `check_all_for_current_user()` method to set permissions for `dashboardSharing`:
        - Add the new base capability `self::VIEW_SHARED_DASHBOARD` to the $permissions array like so:
        ```php
        $permissions = array(
	        ...
            self::VIEW_SHARED_DASHBOARD,
        );
        ```
       - Create an array of dashboard sharing meta capabilities (the new meta capabilities will be defined in #4522)
       - To construct the module-specific meta capabilities array, where the element's key needs to be constructed as `{capability}::{json_encoded_module_slug}`:
            - Update the `__construct` method to add a new optional dependency `$modules` of `Modules` type
            - This leads to create a new `private` property `$modules`
            - Get the shareable modules (array) from the `get_shareable_modules()` method of `Modules` class
            Note: Don't forget to get only the `keys` from the `$shareable_modules` array

            - Loop through the dashboard sharing meta capabilities array and the `$modules` array and then construct a new array by checking the permissions for the `meta_capability` and the `module` using the `current_user_can( $meta_capability, $module )` function
            - The newly constructed array keys should be constructed something like this as mentioned in the AC:
            
            ```php
            $new_permissions[ $meta_capability::[ wp_json_encode( $module ) ] ] 
            ```
            - The value should be the result of `current_user_can()`
       - Finally, return the combination of the existing permissions and the meta capabilities `array_merge( $permissions, $new_permissions )`

### Test Coverage

- Update the tests for `Permissions` for the dashboard sharing capabilities

## QA Brief

**QA:Eng**
- Verify the changes met the AC and IB
- Verify the extended unit tests for `check_all_for_current_user__*` have enough coverage and are passing 

## Changelog entry

* Provide client with Dashboard Sharing permissions when Dashboard Sharing is enabled.

**Comment by aaemnnosttv** [comment]
Thanks @hussain-t ! The IB is off to a good start here. As a general tip, please avoid writing the code to be used as it shouldn't be necessary, but also can turn the IB review into more of a code review, which somewhat defeats the purpose of the IB.

> * Instantiate `Modules` object and call the `get_shareable_modules()` method like so:

The `Modules` instance includes `User_Options` so it's important that we use the "main" instance which is set up in the `Plugin` class. Let's update `Permissions` to take it as a constructor dependency instead.

> * Call the `get_dashboard_sharing_capabilities()` method (which will be declared in [Define new capabilities for dashboard sharing #4522](https://github.com/google/site-kit-wp/issues/4522)) to get the newly set dashboard sharing meta capabilities

Please be careful referencing methods like this as the IB for the issue it is introduced in is not yet approved, and it isn't otherwise required by the AC. Depending on how this method ends up, it might end up with the wrong result, as that method currently returns the base capability for viewing the dashboard (which isn't module specific), and the module-specific meta capabilities for read/manage/delegate.

> * Loop through the `$dashboard_sharing_capabilities` and `$modules` arrays and then construct the array by checking the permissions using the `current_user_can()` function  like the following:

Your code shows the key `{$cap}::['{$module}']` which would not meet the AC because the segment after the `::` is to be valid JSON. I realize there are placeholders here, I'm specifically referring to the single quotes. Instead, please describe what needs to be done without PHP snippets and we can clean up any implementation details in the CR 👍 

Finally, the test coverage should include updates to the tests for `Permissions` for these dashboard sharing specific additions.

**Comment by aaemnnosttv** [comment]
Thanks @hussain-t – this LGTM, let's bump the estimate though to allow a bit more time for tests and related changes. (Updated)

IB ✅

**Comment by FlicHollis** [comment]
I have unassigned @hussain-t as he is out of office, to give the team a chance to pick this up if wanted.

**Comment by techanvil** [comment]
## QA :x: 

`QA:Eng`:

* As discussed on the followup ticket, https://github.com/google/site-kit-wp/pull/4897#discussion_r817761372, we should be properly JSON-encoding the meta args in the capability strings. A followup PR should be created for this issue to make the change.
* This may be a non-issue but I noticed the tests don't include any scenarios where the extended capabilities return `true`. Is that something that's not testable yet, or should we be included a test case where these values are `true`?
```php
Permissions::VIEW_SHARED_DASHBOARD => true,
Permissions::READ_SHARED_MODULE_DATA . "::['search-console']" => true,
Permissions::READ_SHARED_MODULE_DATA . "::['pagespeed-insights']" => true,
Permissions::MANAGE_MODULE_SHARING_OPTIONS . "::['search-console']" => true,
Permissions::MANAGE_MODULE_SHARING_OPTIONS . "::['pagespeed-insights']" => true,
Permissions::DELEGATE_MODULE_SHARING_MANAGEMENT . "::['search-console']" => true,
Permissions::DELEGATE_MODULE_SHARING_MANAGEMENT . "::['pagespeed-insights']" => true,
```

**Comment by hussain-t** [comment]
Thanks @techanvil, that's a good catch regarding JSON encoding 👍 

I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/4907) to fix it.

>should we be included a test case where these values are true

Please refer to @jimmymadon's [comment](https://github.com/google/site-kit-wp/pull/4871#discussion_r813408905) that it will be covered in #4599

**Comment by jimmymadon** [comment]
@techanvil @hussain-t My main reason for not requiring to test for `true` cases in this method was that all the new dashboard sharing cases have been tested in #4522 in `test_dashboard_sharing_capabilities()`.

**Comment by techanvil** [comment]
Thanks for following up @hussain-t and @jimmymadon, and that makes sense! Cheers

**Comment by techanvil** [comment]
## QA :white_check_mark: 

`QA:Eng`:

* Verified the changes meet the AC and IB.
* Verified the extended unit tests for `check_all_for_current_user__*` have enough coverage and are passing.
