### ISSUE TITLE
Extend proactive token refreshing to modules the current user can read shared data for

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4524]
## Feature Description

In #3477 we enhanced Site Kit to proactively refresh a user's OAuth token (later limited to specific screens in #4182) to avoid a race condition where an expired token could be refreshed multiple times when handled on-the-fly due to multiple simultaneous API requests.

With dashboard sharing, this will once again be relevant to do, but for module owner tokens (which facilitate shared module data for the modules they own).

Enhances current proactive refresh to (also) refresh the token(s) of modules that the current user can read shared data for to avoid unnecessary token refreshes either for a) token already refreshed, or b) token isn't actually needed for the current request

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Proactive token refreshing should be extended to also potentially refresh other module owner's tokens if the current user can `googlesitekit_read_shared_module_data` for that module, for each module that has been shared

## Implementation Brief
* Using `includes/Core/Authentication/Authentication.php`, update the `maybe_refresh_token_for_screen` function to do the following:
	* Grab the list of shareable modules via the `Modules` class and `get_shareable_modules` method and loop through the list of modules.
		* Check if the current user has the `googlesitekit_read_shared_module_data<module-slug>` capability and if this is the case,
			* Get the module owner ID via the `get_owner_id` method.
			* Set the current user id to be the owner ID via the `switch_user` method, passing the `ownerID` as parameter (`$restore_user = $this->user_options->switch_user( $owner_id );`). This returns a closure to switch back to the original user.
			* Grab the user token via the `get` method of `$this->token` and use the same logic to decide whether to refresh the token or not, i.e if the token is not set or does not expire in less than 5 mins.
			* Then refresh the user token using the `refresh_token` method of the `OAuth_Client` object. (`$this->get_oauth_client()->refresh_token();`)
			* Once the token is refreshed, call the closure to switch back to the original user (`$restore_user()`).

### Test Coverage
* Update `tests/phpunit/integration/Core/Authentication/AuthenticationTest.php` to add tests for the above changes.

### QA Eng
* Follow the QAB for #4182 and ensure the token is refreshed for admin users (already existing functionality).
* Since we are unable to set Module Sharing Settings in the UI as yet, make sure that the new tests written cover the dashboard sharing cases as per the AC/IB.

## Changelog entry

* Proactively refresh tokens for shared modules when Dashboard Sharing is enabled.

**Comment by eugene-manuilov** [comment]
> Get the array of ids which the module is being shared with via the sharedRoles key.

@asvinb we don't need to get the shared roles for a module. What we need to do is to get the module instance, grab the owner id using the `get_owner_id` method, and refresh the owner's token if it is about to expire.

> * instantiate a new `User_Options` object, passing the user id as second parameter.
> * instantiate a new `Token` object passing the previously created `User_Options` object.
> * instantiate a new `OAuth_Client` using the previously created `User_Options` object and available variables as it is done in `get_oauth_client`.

No need to instantiate all of these classes. There is the `switch_user` method in the `User_Options` class that we can use to switch the current user to the module owner:

```php
// Authentication.php

$restore_user = $this->user_options->switch_user( $owner_id );

$token = $this->token->get();
...
$this->get_oauth_client()->refresh_token();

$restore_user();
```

**Comment by asvinb** [comment]
Thanks @eugene-manuilov . That's very helpful! I've updated the IB, can you take another look?

Thanks!

**Comment by techanvil** [comment]
## QA :white_check_mark: 

* Ran through the QAB for #4182. Confirmed that:
  * After resetting the token creation time, no refresh token request was sent while on a non-Site Kit page.
  * Refresh token endpoint was hit when navigating to Site Kit Dashboard. 
  * Again resetting the token creation time and waiting on the dashboard page, the token was refreshed again in ~5 minutes.
* Verified that the new tests cover the dashboard sharing cases as per the AC/IB.

![image](https://user-images.githubusercontent.com/18395600/157440867-340b2852-654f-4a98-a42c-2cc1555fd8dc.png)

![image](https://user-images.githubusercontent.com/18395600/157441671-c7eb3f2e-4dc1-4012-80ed-280129e3fceb.png)
