### ISSUE TITLE
Reset a module's sharing settings on deactivation

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4526]
## Feature Description

Whenever a shared module is disconnected, its sharing settings should be reset back to the default unshared state, removing any roles or other configuration.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Module sharing settings should be deleted for a specific module when that module is disconnected/deactivated

## Implementation Brief

* In the `Core\Modules\Module_Sharing_Settings` class:
  * Add a new public method `unset_module( slug )` that unsets sharing settings for the specified module and saves the sharing settings.
* In the `Core\Modules\Modules` class:
  * Add a new private property `$sharing_settings` and instantiate it in the constructor.
  * Call the `$this->sharing_settings->register()` in the `register` method.
  * Call the `$this->sharing_settings->unset_module( $slug )` in the `deactivate_module` method before returning `true` at the very end of the method.

### Test Coverage

* Add phpunit tests for the `Module_Sharing_Settings::unset_module` method.
* Update existing tests if any is failing due to the aforementioned changes.

## QA Brief

* Ensure that module deactivation has no errors with and without the dashboardSharing Flag. 

## Changelog entry

* Remove Module sharing settings on module disconnect.

**Comment by aaemnnosttv** [comment]
> * Add a new public method `unset_module( slug )` that unsets sharing settings for the specified settings.

@eugene-manuilov – just to clarify, this should also save the settings after unsetting the module, correct?

**Comment by eugene-manuilov** [comment]
> > * Add a new public method `unset_module( slug )` that unsets sharing settings for the specified settings.
> 
> @eugene-manuilov – just to clarify, this should also save the settings after unsetting the module, correct?

Yes, of course. Updated IB to mention that it should save the sharing settings.

**Comment by aaemnnosttv** [comment]
IB ✅
