### ISSUE TITLE
Expose recoverable modules to client

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4527]
## Feature Description

[Module recovery](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.184kxp23btyr) is a new concept in dashboard sharing whereby a shared module can be recovered in the event that the module owner is lost. Later, we'll use this data to alert admins and prompt those who are eligible to recover the module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`googlesitekit-dashboard-sharing-data` script data](https://github.com/google/site-kit-wp/issues/4473) should be extended to include a new `recoverableModules` property as a list of module slugs (`string[]`) that are recoverable
* A recoverable module is a [shareable module](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.j8mstfogtglx) that meets any of the following criteria:
	- Has no owner identified by its `ownerID`
	- The user identified by the module's `ownerID` no longer (one of the following)
		- exists
		- is authenticated
		- lacks the necessary capability to share (i.e. `AUTHENTICATE`)
* Note one or more of these cases could probably be covered by some overarching logic but it's important that all are accounted for

## Implementation Brief

In `Core/Assets/Assets.php` update `get_inline_dashboard_sharing_data()` `$inline_data` add a property `recoverableModules` which will be an array of module strings.
First fetch the list of shareable modules `get_shareable_modules()` (introduced in #4521),

For each shareable module get the owner id `get_owner_id()`
https://github.com/google/site-kit-wp/blob/cf9badad4e23c528719aea864e5d74bc5ca6c890/includes/Core/Modules/Module_With_Owner.php#L29

If the owner ID doesn't correspond to a valid user ( `get_user_by( 'ID', $owner_id )` ) 
https://developer.wordpress.org/reference/functions/get_user_by/
Add the module slug to the `recoverableModules` array.

If the owner is not authenticated, add the module slug to the `recoverableModules` array.

See https://github.com/google/site-kit-wp/blob/cf9badad4e23c528719aea864e5d74bc5ca6c890/includes/Core/Authentication/Authentication.php#L625

Also ensure you're checking the module owner, and not the current user, code snippet:
https://github.com/google/site-kit-wp/blob/cf9badad4e23c528719aea864e5d74bc5ca6c890/includes/Core/Authentication/Authentication.php#L664-L671

If the owner ID does not have the `AUTHENTICATE` capability, add the module slug to the `recoverableModules` array
`user_can( $owner_id, Permissions::AUTHENTICATE );`
https://developer.wordpress.org/reference/functions/user_can/

### Test Coverage

* N/A

## QA Brief

- Enable `dashboardSharing` via the tester plugin
- Make sure you are in the Site Kit dashboard page
- Open the browser developer console and type `window._googlesitekitDashboardSharingData`
- Verify that you should get an array of `roles` and `recoverableModules`
- Verify the `recoverableModules` array should have the module slugs if the criteria is met as mentioned in the AC
- Refer the screenshot attached to the PR description
- Disable `dashboardSharing` via the tester plugin
- Type `window._googlesitekitDashboardSharingData` in the browser developer console
- Verify that you should get `undefined` as a value of the above property

**Update:**
- Mostly, the recoverable modules would be PSI and Idea Hub if active

## Changelog entry

* Expose recoverable modules information to clients.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t @eugene-manuilov there are 4 `recoverableModules`, which are connected. I also have Optimize and Tag Manager connected on this site, should I see them in the list of modules too? 

```
0: "search-console"
1: "adsense"
2: "analytics"
3: "pagespeed-insights"
```

**Comment by aaemnnosttv** [comment]
@hussain-t I found the problem here – see https://github.com/google/site-kit-wp/pull/4670#discussion_r792537640

Would you please open a follow-up PR to fix it?

@wpdarren under normal circumstances, no modules should be shown here although due to the current definition of a recoverable module `pagespeed-insights` qualifies for this because it has no `ownerID` until it is shared. I'll open a follow-up issue to refine this logic but PSI (and Idea Hub when active) would be the only exceptions that are expected here.

To test a condition where a module would become recoverable, set up Analytics with a different user. Then change that user's role to be a non-admin. Analytics should then show up as a recoverable module.

**Comment by hussain-t** [comment]
@aaemnnosttv sure, I will do that. Thanks for the investigation!

**Comment by hussain-t** [comment]
@aaemnnosttv @wpdarren I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/4725) and updated the QAB.

**Comment by aaemnnosttv** [comment]
Thanks @hussain-t, please see [my review](https://github.com/google/site-kit-wp/pull/4725#pullrequestreview-863773868) as there are a few things there left to address.

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@aaemnnosttv re. this:

> To test a condition where a module would become recoverable, set up Analytics with a different user. Then change that user's role to be a non-admin. Analytics should then show up as a recoverable module.

I was going to run through this test but before even setting it up, I noticed Analytics, AdSense, Search console appear in the `recoverableModules` and from your previous comment, I am assuming this is not correct. 

>  I'll open a follow-up issue to refine this logic but PSI (and Idea Hub when active) would be the only exceptions that are expected here.

This is what I see with all modules connected. 

![image](https://user-images.githubusercontent.com/73545194/151334570-352a9d79-9b9f-46b1-b079-444f32ebd346.png)

It's possible I am misunderstanding the AC. Thoughts?

**Comment by aaemnnosttv** [comment]
@wpdarren are you testing with the latest on `main`?

**Comment by wpdarren** [comment]
@aaemnnosttv I thought I was testing with latest main, but just refreshed it again and now only 2 modules appear. 😓 So, looks like it hadn't refreshed, or, still going through the merge.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- An array of `roles` and `recoverableModules` appears when you type `window._googlesitekitDashboardSharingData` into the console. The PageSpeed and Idea Hub modules appear when connected. 
- `Undefined` appears as a value of the above property when you type `window._googlesitekitDashboardSharingData` into the console. 

![image](https://user-images.githubusercontent.com/73545194/151344667-e8c1d4c2-7b80-41e2-b255-889e8fefba25.png)
