### ISSUE TITLE
Modify REST permission checks for some endpoints to be available to shared dashboard viewers 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4529]
## Feature Description

Since the beginning, Site Kit has always been limited to admins in WordPress. With dashboard sharing, non-admins will be able to use Site Kit for the first time. This will require some changes to permission checks for various REST requests which will need to be available to users of the shared dashboard as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Permission checks for following REST endpoints should be updated to be additionally available to users who can `googlesitekit_view_shared_dashboard`
	* All routes in the `core/user/data/*` namespace except the following datapoints:
        - `disconnect`
        - `survey-event`
        - `survey-trigger`
        - `user-input-settings`
	* `GET:core/modules/data/list`
	* `GET:core/search/data/(post|entity)-search`
	* `GET:modules/:slug/data/:datapoint`

## Implementation Brief

**Some of the to be created variable/method names are not concrete and only used for easier referencing in the following points.**

Inside the `get_routes` method of `Google\Site_Kit\Core\REST_API\REST_Routes` class:
* Add a new callable function `can_view_shared_dashboard` that returns `true` if current user has `Permissions::AUTHENTICATE` or `googlesitekit_view_shared_dashboard` capability.
* In the `routes` array, update the `permission_callback` of  `core/search/data/post-search` route with the newly defined `can_view_shared_dashboard` callable.
    * This will no longer be available in the codebase once #4646 is merged, ignore this route if that's the case.  

Do the same for the following routes as well:

* `get_rest_routes` method of `Google\Site_Kit\Core\Authentication\Authentication` class
    * `core/user/data/authentication`
* `get_rest_routes` method of `Google\Site_Kit\Core\Dismissals\REST_Dismissals_Controller` class
    * `core/user/data/dismissed-items`
    * `core/user/data/dismiss-item`
* `get_rest_routes` method of `Google\Site_Kit\Core\Feature_Tours\REST_Feature_Tours_Controller` class
    * `core/user/data/dismissed-tours`
    * `core/user/data/dismiss-tour`
* `get_rest_routes` method of `Google\Site_Kit\Core\Tracking\REST_Tracking_Consent_Controller` class
    * `core/user/data/tracking`
* `get_rest_routes` method of `Google\Site_Kit\Core\Util\REST_Entity_Search_Controller` class
    * `core/search/data/entity-search`
    * this class/route will be added on #4646. 

Inside the `get_rest_routes` method of `Google\Site_Kit\Core\Modules\Modules` class:
* Add the callable function `can_view_shared_dashboard` like the previous one.
* Add the callable function `can_view_shared_dashboard_insights` that returns `true` if current user has the `Permissions::VIEW_POSTS_INSIGHTS` capability.
* In the return array, update the `permission_callback` of `core/modules/data/list` route with the newly defined `can_view_shared_dashboard` callable.
* Update the `permission_callback` of `WP_REST_Server::READABLE` of  `modules/(?P<slug>[a-z0-9\-]+)/data/(?P<datapoint>[a-z\-]+)` route' with the `can_view_shared_dashboard_insights` callable. 

* Remove all unused callables and variables. 

### Test Coverage

* Update any failing tests. 

## QA Brief

* Make sure all the affected routes still continue to function correctly for authenticated dashboard users the `dashboardSharing` flag both enabled and disabled. 
    * `core/user/data/authentication`
       * Complete Plugin Setup to use this route.
   * `core/user/data/dismissed-items` & `core/user/data/dismiss-item`
       * Dismiss Idea Hub Banner or Monetization section to test these routes. 
   * `core/user/data/dismissed-tours` & `core/user/data/dismiss-tour`.
       * On a new site, set initial plugin version to something old (ie. 1.24.0) to trigger unifiedDashboard tour.
       * Make sure the tour appears and is dismissed as exoected. 
   * `core/user/data/tracking`
       * Update tracking settings in the site Kit Admin Settings to test it. 
   * `core/search/data/entity-search`
       * Use Entity Search (from Header).
   * `core/modules/data/list`
       * View Site Kit Settings > Connected Modules / Connect More Modules. 
   * `modules/(?P<slug>[a-z0-9\-]+)/data/(?P<datapoint>[a-z\-]+)`
       * Visit main and entity dashboard, scroll to all the sections. There should be no api errors. 

## Changelog entry

* Allow dashboard sharing users to use REST routes when using dashboard sharing view mode.

**Comment by kuasha420** [comment]
@aaemnnosttv I would like to have a few clarification on this one:

* For `core/user/data/*` routes, should both `GET` and `POST` routes be available to the `googlesitekit_view_shared_dashboard` users or just `GET`?
    * By the namespace, you meant all the roues that start with that, right? I have found the following scattered through various classes. am I missing any? 
        * `GET:core/user/data/authentication`.
        * `POST/PUT/PATCH:core/user/data/disconnect`
        * `GET:core/user/data/dismissed-items`
        * `POST:core/user/data/dismissed-items`
        * `GET:core/user/data/dismissed-tours`
        * `POST:core/user/data/dismiss-tour`
        * `GET:core/user/data/user-input-settings`
        * `POST:core/user/data/user-input-settings`
        * `GET:core/user/data/tracking`
        * `POST:core/user/data/tracking`
        * `POST:core/user/data/survey-trigger`
        * `POST:core/user/data/survey-event`
* `GET:core/search/data/entity-search` doesn't yet exist and it's currently `GET:core/search/data/post-search` until #1592 is merged. Should I add the `post-search` route or add the aforementioned ticket as a blocker?

Cheers.

**Comment by aaemnnosttv** [comment]
> * For `core/user/data/*` routes, should both `GET` and `POST` routes be available to the `googlesitekit_view_shared_dashboard` users or just `GET`?

@kuasha420 these routes are always specific to the current user so all methods should be allowed.

> * By the namespace, you meant all the routes that start with that, right? 

Yes 👍 

> I have found the following scattered through various classes. am I missing any?

It's hard to say but that looks complete. The easiest way is probably searching for `core/user/data` in `*.php` files but you could also look at the routes under `/wp-json/google-site-kit/v1` in the browser, or `array_keys( rest_get_server()->get_routes() )` in the CLI (i.e. `wp shell`).

> * `GET:core/search/data/entity-search` doesn't yet exist and it's currently `GET:core/search/data/post-search` until [Dashboard search should support URIs that don't resolve to individual posts #1592](https://github.com/google/site-kit-wp/issues/1592) is merged. Should I add the `post-search` route or add the aforementioned ticket as a blocker?

These should both get the same treatment. I wasn't expecting the `post-search` to still be around but I think one need not block the other. Ideally 1592 would go first but since you're already working on that one, I think it would be ok to implement that adjustment to the route permissions in that issue, but we could also have it as a dependency of this issue. I'd prefer to avoid additional dependencies between issues if we can avoid it though.

**Comment by kuasha420** [comment]
@aaemnnosttv one more question, for `core/user/data/survey-(trigger|event)` routes, we are currently checking if the user is authenticated and using proxy. For dashboard sharing, Do we check if the user is using proxy in addition to the new capability or just having the capability is enough? Sorry, still not fully versed on the proxy and it's significance. 

Sending the IB for review.

**Comment by aaemnnosttv** [comment]
> `core/user/data/survey-(trigger|event)` routes, we are currently checking if the user is authenticated and using proxy. For dashboard sharing, Do we check if the user is using proxy in addition to the new capability or just having the capability is enough? Sorry, still not fully versed on the proxy and its significance.

Great question. @felixarntz – should we require authentication in the permission check for the route or should we handle this in the route handler? Practically speaking, this should never be requested anyways due to changes we'll make in the action, but we should still account for it here as well I think.

**Comment by felixarntz** [comment]
@aaemnnosttv We should ensure that the survey-related endpoints still cannot be used unless authenticated. It's a bit of a flaw right now that we don't check that there, since it's not sufficient to know whether the user _can_ authenticate.

Since (at least so far) we're not going to have surveys for unauthenticated users, I'd prefer if we didn't change the capability on these endpoints and left them at `AUTHENTICATE`. We may still want to add the check that the user is also actually authenticated, but that would be unrelated to this issue.

Those are not the only endpoints that I think we can leave as is though - the user input right now also works only for authenticated users, so I think these endpoints shouldn't be changed either. And `POST/PUT/PATCH:core/user/data/disconnect` is irrelevant as well as far as I can tell, that only matters for authenticated users, since it's essentially the opposite, to "unauthenticate".

Given the above, we may need to rephrase the ACs here a little bit - not all `core/user/data/*` endpoints need to or should be accessible to users that cannot authenticate.

cc @kuasha420

**Comment by aaemnnosttv** [comment]
Thanks @felixarntz, I've amended the ACs to exclude those datapoints from the changes here.

> * Add a new callable function `can_view_shared_dashboard` that returns `true` if current user has `Permissions::AUTHENTICATE` or `googlesitekit_view_shared_dashboard` capability.

@kuasha420 specifying the name of the function is a bit of an implementation detail, especially since this will probably be local to the method (it would be more important if it were part of a Site Kit API). We probably shouldn't name it after one of the capabilities though – either capability should grant permission to make the request and removing the one it isn't named after would be a problem 😄 . It would be good to use something a little more abstract, maybe "can request user data" or something along those lines, but again that isn't really something we need to spell out here but I understand it helps to put a name to the logic.

Regarding `Permissions::VIEW_POSTS_INSIGHTS`, this is a bit odd because I don't think it's currently possible for a user to not be able to `SETUP` but is able to `VIEW_POSTS_INSIGHTS` (under normal circumstances). This permission is also mapped to `manage_options`. @felixarntz should we maybe change this to `edit_posts` or maybe even `read` and then apply restrictions on it in map_meta_cap? That is, maybe we can keep the logic we currently have for `GET:modules/:slug/data/:datapoint` and update `Permissions::VIEW_POSTS_INSIGHTS` to work similar to how `VIEW_DASHBOARD` will work for both as well as in #4599 ?

Otherwise the IB is looking good to me, but needs a few revisions per the updated ACs.

**Comment by felixarntz** [comment]
@aaemnnosttv @kuasha420 Changing `VIEW_POSTS_INSIGHTS` to rely on `edit_posts` as foundational core capability makes sense, that is even stated in a comment on it in `Permissions` that has been there forever :) Technically however, I agree `VIEW_POSTS_INSIGHTS` could even follow similar logic like `VIEW_DASHBOARD` after #4599 like you're saying, but I think it's okay that for the endpoints we simply use `VIEW_POSTS_INSIGHTS` / `edit_posts` as permission check, which de-facto allows anyone with `edit_posts` to call the endpoints. We'll have central logic within the `Module` class anyway that'll be additional permission checks for whether the current user is _actually_ eligible before passing through to the data point logic itself, based on whether the module is shared with their role etc.

So I guess either would work, using the same logic as `VIEW_DASHBOARD` is a bit stricter and therefore more precise, so probably best to go with that, rather than _just_ to use `edit_posts`.

**Comment by kuasha420** [comment]
@aaemnnosttv fixed up the IB. I'm not entirely clear about the last point, can we just use `VIEW_POSTS_INSIGHTS` instead of `Permissions::SETUP || Permissions::VIEW_POSTS_INSIGHTS || googlesitekit_view_shared_dashboard` ? 

Cheers.

**Comment by aaemnnosttv** [comment]
> So I guess either would work, using the same logic as `VIEW_DASHBOARD` is a bit stricter and therefore more precise, so probably best to go with that, rather than _just_ to use `edit_posts`.

@felixarntz do you mean to say we can use `VIEW_DASHBOARD` here instead of `VIEW_POSTS_INSIGHTS`? I also find this a bit confusing as `VIEW_POSTS_INSIGHTS` to me sounds more like a capability which could grant the ability to see the admin bar app/stats (and maybe the entity dashboard) but nothing else, but I suppose that wouldn't be possible because a user needs to visit the shared dashboard before they can make requests for data (or no?) 🤔

**Comment by felixarntz** [comment]
@aaemnnosttv My thinking was basically that for now `VIEW_POSTS_INSIGHTS` would follow the same logic that `VIEW_DASHBOARD` would use. Which technically would mean we can just scratch that capability entirely, but I think it makes sense to have a distinct capability for viewing Site Kit data "in general", e.g. in other areas than the dashboard. The requirements for that could also be different at some point.

**Comment by aaemnnosttv** [comment]
> My thinking was basically that for now `VIEW_POSTS_INSIGHTS` would follow the same logic that `VIEW_DASHBOARD` would use.

Thanks @felixarntz, last question I think – would you say this could apply even now or would only change if dashboard sharing was enabled?

**Comment by felixarntz** [comment]
@aaemnnosttv Yeah I think we could change this even now already. Although there is no variable in the `Permissions` class that automatically takes care from mapping a primitive Site Kit capability to another primitive Site Kit capability. But yeah, I think we could just grant both of these capabilities from running the exact same logic in the `user_has_cap` filter.

**Comment by aaemnnosttv** [comment]
@kuasha420 I think the remaining questions have been addressed, but let me know if you have any others; this is almost good to go 👍

**Comment by kuasha420** [comment]
@aaemnnosttv from my understanding. only having `VIEW_POST_INSIGHT` for `GET:modules/:slug/data/:datapoint` is sufficient? Is there anything we need to do in `Permissions` class as part of this ticket? If that's the case I think AC should get an update. Otherwise IB is ready for another review. 

Cheers.

**Comment by aaemnnosttv** [comment]
@kuasha420 we would continue to use `VIEW_POST_INSIGHTS` as the capability to check, but under the hood, the logic will use `VIEW_DASHBOARD` as its base capability. I've added this to the ACs for #4599 where this is more appropriate to address and made this issue dependent on that one.

> * Add the callable function `can_view_shared_dashboard_insights` that returns `true` if current user has either `Permissions::VIEW_POSTS_INSIGHTS` or `googlesitekit_view_shared_dashboard` capability.

Accordingly, this can simply check `Permissions::VIEW_POSTS_INSIGHTS` as the either-or behavior will be encapsulated within it.

I'll make this tweak real quick as this is otherwise G2G 👍 

IB ✅

**Comment by wpdarren** [comment]
@kuasha420 re. the QAB brief.  

> Make sure all the affected routes still continue to function correctly for authenticated dashboard users.

Looking at the IB and subsequent comments, I feel we need more information in the QAB to test this fully. 

I can see reference to feature tours, entity search, but I would like a little more clarity on what the affected routes are and what we should be looking out for.  The AC/IB is a little technical so please could provide more information?

**Comment by kuasha420** [comment]
@wpdarren fair point. I have added all the changed routes with description on where to find/test them. Please test with the feature flag enabled and disabled. Thank you.

**Comment by wpdarren** [comment]
QA Update: ✅ 

Thanks for the update to the QAB @kuasha420, this was really useful 👍 

**Verified:**

- I went through all of the affected routes in the QAB for authenticated dashboard user with `dashboardSharing` flag both enabled and disabled and can confirm that everything still functions as expected.  No console errors appeared.
