### ISSUE TITLE
Update AdSense module datapoints for consistency

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#453]
Datapoints in the AdSense module should receive minor updates as outlined in the ACs.

Implementation brief should include which pieces of JS need to be updated and which e2e tests need to be updated (if any).

**Execution is blocked until #406 is merged.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AdSense setup and querying AdSense data via API should still work as before.
* Datapoint parameters and return values controlled by the plugin itself should all be in camel case.
* Datapoints should be updated as follows:
    * GET connection → keep as is
    * GET account-id → keep as is
    * GET client-id → keep as is
    * GET adsense-tag-enabled → GET use-snippet
        * the option should be renamed to useSnippet as well; to remain backward-compatible, it needs to be migrated from the current one on the fly
    * GET account-status → keep as is
    * GET account-url → keep as is
    * GET reports-url → keep as is
    * GET notifications → keep as is
    * GET accounts → keep as is
    * GET alerts → keep as is
    * GET clients → keep as is
    * GET urlchannels → keep as is
    * GET earning-today & GET earning-yesterday & GET earning-... & GET earnings-this-period → GET earnings
        * “dateRange” should be allowed to have additional values to account for all the existing different variants
        * additional supported (optional) parameters should be “dimensions” (list of strings), and “limit” (integer)
    * POST connection → keep as is
    * POST account-id → keep as is
    * POST client-id → keep as is
    * POST adsense-tag-enabled → POST use-snippet
see above; required parameter should be renamed to “useSnippet”
    * POST account-status → keep as is
    * POST setup-complete → keep as is

#### `GET adsense-tag-enabled`
* Rename datapoint to `use-snippet`
* Rename `adsenseTagEnabled` option key to `useSnippet`
    - Maintain check for old key to migrate existing saved option
        - [Update usage](https://github.com/google/site-kit-wp/search?q=adsenseTagEnabled&unscoped_q=adsenseTagEnabled)
        - Almost all references are in Adsense module class
* Update usage
    - `AdSenseSettings.save`
    - `AdSenseSettings.handleadsenseTagEnabledSwitch`

#### `POST adsense-tag-enabled`
* Rename datapoint to `use-snippet`
* Rename `adsenseTagEnabled` required parameter to `useSnippet`

#### `GET earning-*`
* Combine datapoints into new `GET earnings` datapoint
    - `dateRange` (default: `last-28-days`)
        + Taken from the portion of the old datapoint name after `earning-`  
        E.g. the date range for `earning-today` would be `today`
        + Standardize date range slug for consistency using dashes
        + Create mapping of `dateRange` to `$args` to pass to `create_adsense_earning_data_request` to avoid giant switch
        + Return `WP_Error` with `400` if invalid date range requested
    - Add support for additional parameters
        + `dimensions` (list of strings)
        + `limit` (integer)
* Delete old datapoints in `Adsense::` `get_datapoint_services`, `create_data_request`, `parse_data_response`
    - `earning-today`
    - `earning-yesterday`
    - `earning-samedaylastweek`
    - `earning-7days`
    - `earning-prev7days`
    - `earning-this-month`
    - `earning-this-month-last-year`
    - `earning-28days`
    - `earning-prev28days`
    - `earning-daily-this-month`
    - `earnings-this-period`
* Update usage
    - `AdSensePerformanceWidget`
    - `AdSenseEstimateEarningsWidget`
    - `AdSenseDashboardMainSummary`
    - Handy regex for old datapoints  
    ```
    earning-(today|yesterday|samedaylastweek|7days|prev7days|this-month|this-month-last-year|28days|prev28days|daily-this-month|this-period)
    ```

## Changelog entry

* Improve datapoint behavior of AdSense module for consistency.

**Comment by aaemnnosttv** [comment]
@felixarntz this one is just about ready for review, I'm not quite sure how we can consolidate a few of the more complex date range datapoints (e.g. `earning-this-month-last-year`). How did you see it working in that case?

**Comment by felixarntz** [comment]
@aaemnnosttv That ties in a little bit with our discussion on #447 earlier.

For this specific case, let's just support additional values for `dateRange` in this new `earnings` datapoint. The handler for that datapoint can include a `switch` that transforms these values into the proper start and end date. The `default` clause could then call the regular `parse_date_range()` method.

We can partly use the values as they are in the current datapoint names following the `earning-` bit. In some cases, we should alter them for a bit more consistency, for example `prev7days` should also include dashes, or for example `this-month` and `daily-this-month` would both end up just as `this-month`, since the `daily` part only currently affects the `dimensions` value which is now also a parameter anyway.

**Comment by felixarntz** [comment]
@aaemnnosttv IB looks solid, just one feedback item:
> `dateRange` **required**
It doesn't need to be required, it can use a default of `last-28-days` just like all other `dateRange`-using datapoints do. Currently `last-28-days` isn't even used for that datapoint I believe, but it makes sense to support it for consistency (plus we should make sure we don't only support our very own use-case anyway 🙂).

**Comment by aaemnnosttv** [comment]
Updated the `dateRange` to indicate it is no longer required and should have a default value.
