### ISSUE TITLE
Add new endpoint for module recovery

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4533]
## Feature Description

In order to facilitate [module recovery](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.184kxp23btyr), this issue builds on the ability to [check the current user's access to a module's configured service entity](https://github.com/google/site-kit-wp/issues/4478) with a new endpoint to recover a specific module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/modules` REST namespace should receive a new `POST:recover-module?slug={slug}` endpoint
	* This endpoint should be limited to authenticated admins only
* The handler should first perform the following checks for the module identified by the `slug` request parameter and then, if successful, update the module owner to be the current user:
	* Check that the module is recoverable (see also https://github.com/google/site-kit-wp/issues/4527)
	* Check that the user has access to the current configured entity using [the module's `check-access` datapoint](https://github.com/google/site-kit-wp/issues/4478) 
	* On success, the handler should return an object with the following shape:  
        ```js
        {
            ownerID: Number, // New owner ID (should match current user).
        }
        ```
    * It should return a `WP_Error` in the following scenarios:
		- with a `404` status if called with a non-existent module slug
		- with a `403` status if called with a non-recoverable module slug

## Implementation Brief

* Add  a new REST route `core/modules/recover-module` to the routes list returned by the `Modules::get_rest_routes` method.
  * Use the `WP_REST_Server::EDITABLE` method.
  * In the callback:
    * Grab the `slug` parameter using the similar approach to https://github.com/google/site-kit-wp/blob/c2f2be6e165e3506ff8cae8a55cd899a0f300374/includes/Core/Modules/Modules.php#L653-L654
    * Get the module instance using the `get_module( $slug )` method.
    * Return the `404` error if the `get_module` method call throws an exception or the returning module is not sharable (`is_sharable()` returns `false`).
    * Return the `403` error if the module slug is not available in the recoverable modules list that can be obtained by calling the `get_recoverable_modules` method once #4527 is merged.
    * Return the `403` error if the current user doesn't have access to the module by invoking the `check-access` endpoint from #4478 ticket.
    * Update the module owner to be the current user ID.
    * Return a new response with `array( 'ownerID' => get_current_user_id() )` data.
  * In the permission callback, check whether the current user can set up using the `current_user_can( Permissions::SETUP )` call.

### Test Coverage

* N/A

## QA Brief

**Note:** The IB states:
>Add  a new REST route `core/modules/recover-module` 

However, that's incorrect. That was fixed in a follow-up [PR](https://github.com/google/site-kit-wp/pull/5112).

----------

- Useful `fetch` snippet if using the Chrome / browser console:
   ```javascript
    fetch("http://sitekit.10uplabs.com/wp-json/google-site-kit/v1/core/modules/data/recover-module", {
        "headers": {
            "accept": "application/json, */*;q=0.1",
            "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
            "content-type": "application/json",
            "x-wp-nonce": "81d67e1501"
        },
        "referrer": "http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-dashboard",
        "referrerPolicy": "strict-origin-when-cross-origin",
        "body": JSON.stringify({
            "data": {
                "slug": "search-console"
            }
        }),
        "method": "POST",
        "mode": "cors",
        "credentials": "include"
    });
   ```
- Using the endpoint in the snippet above (replace the x-wp-nonce with a nonce from a recent report request on local):
	* Make a GET request and check that it fails.
	* Make a POST request (removing the body) and check that it fails because of the missing `slug` parameter.
	* Make a POST request with the `slug` parameter set to `foo-bar` and check that it fails because of it's an invalid module slug.
	* Disable `dashboardSharing` and make a POST request with `slug` parameter set to `search-console` and check that it fails since the module is not shareable.
	* Enable `dashboardSharing` and make a POST request with `slug` parameter set to `search-console` and check that it fails with a 403 error because the module is not recoverable.
	* Make the module recoverable by adding the following options (add shared roles and change the owner to a non-authenticated / random user ID)
	    ```bash
      10updocker wp option update googlesitekit_dashboard_sharing '{ "search-console": { "sharedRoles": [ "editor" ], "management": "all_admins" } }' --format=json
      10updocker wp option update googlesitekit_search-console_settings '{ "ownerID": 2 }' --format=json
      ```
  * Once the search-console is recoverable, make a POST request and check the response is as per the AC. Also check if the ownerID has been updated correctly.
      ```bash
      10updocker wp option get googlesitekit_search-console_settings
      ```

## Changelog entry

* Add REST endpoint for module recovery.

**Comment by felixarntz** [comment]
@aaemnnosttv Similar question to https://github.com/google/site-kit-wp/issues/4481#issuecomment-999005412, why do we need to return the full module settings here? Wouldn't it be sufficient to return the new owner ID? Any other settings shouldn't ever change here.

**Comment by aaemnnosttv** [comment]
@felixarntz see my longer reply on #4481, but generally speaking anytime we update settings on the server we sync those changes on the client. The datastore doesn't support receiving a subset of settings into the store (updating the `savedSettings` rather than just the temporary current values) so we'd need to return the complete settings. 

> Any other settings shouldn't ever change here.

_Most likely won't have changed_ –yes, but they could have changed since the page loaded. This isn't strictly required, but more of a future-proofing safeguard with an SPA in mind. Happy to leave this out for now if you'd prefer.

**Comment by felixarntz** [comment]
@aaemnnosttv Left a reply to your comment on #4481 - I think we could return only the new `ownerID` here as well. Although in this case here I'm less opposed to the return value than in #4481 because the endpoint here only applies to one module and is an _explicit_ call to take over - while in the one from #4481 the taking over would be more of a side-effect.

**Comment by aaemnnosttv** [comment]
> I think we could return only the new `ownerID` here as well.

@felixarntz that would be fine with me if we were to also add the ability to update the owner ID in current and saved settings in the store without needing to hack around it by merging the current settings values before receiving them which would be incorrect IMO as it would be treating current client-side values as the source of truth for what is saved.

> I'm less opposed to the return value than in #4481 because the endpoint here only applies to one module and is an _explicit_ call to take over - while in the one from #4481 the taking over would be more of a side-effect.

I agree it's more of a clean separation here. How about we only update the `ownerID` then rather than updating the complete settings?

**Comment by felixarntz** [comment]
@aaemnnosttv Per #4481, how about we adjust this as well to only return the new `ownerID`?

**Comment by aaemnnosttv** [comment]
@felixarntz that sounds good to me. We could always dispatch a `fetchGetSettings` to refresh the saved settings as well, so I suppose everything doesn't need to happen in the one action. I'll update the ACs.

**Comment by tofumatt** [comment]
The design docs says that the following conditions qualify a module to be "recovered":

* The module has no owner (e.g. `! settings[ownerID]`)
* The module owner doesn’t exist anymore (e.g. account was deleted).
* The module owner is no longer authenticated (e.g. the user disconnected from SK)
* The module owner no longer has sufficient capabilities to share (i.e. `! user_can AUTHENTICATE`)

Looks like we should add one more condition to the IB: we should also return `403` if the current owner has sufficient capabilities to share the module. If they can share the module, we shouldn't allow the request to go ahead.

After that I think this is good.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov @tofumatt there's a detail here which wasn't articulated very explicitly in the ACs as it was in the [design doc](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.dnshbtaxhvp9) which says

> This request should ensure the given module is in a recoverable state and call the module’s `check-access` endpoint internally (again, if it has one) before transferring ownership to the current user.

I'll update the AC to clarify this.

**Comment by tofumatt** [comment]
IB ✅

**Comment by asvinb** [comment]
### QA: ✔️ 

* GET request fails ☑️ 
* POST request fails without body: invalid slug message ☑️
* POST request with foo-bar as slug: invalud slug message ☑️
* Disable dashboardSharing and make a POST request with slug parameter set to search-console and check that it fails since the module is not shareable. ☑️
* Enable dashboardSharing and make a POST request with slug parameter set to search-console and check that it fails with a 403 error because the module is not recoverable. ☑️
* Make the module recoverable by adding the following options (add shared roles and change the owner to a non-authenticated / random user ID) ☑️
* Once the search-console is recoverable, make a POST request and check the response is as per the AC. Also check if the ownerID has been updated correctly. ☑️
