### ISSUE TITLE
Extend Site Health info for Dashboard Sharing

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4534]
## Feature Description

Site Kit's site health report contains valuable information for our support team to help users troubleshoot problems they are experiencing. Including dashboard sharing configuration in the report will be essential to providing support once the feature is rolled out.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

If `dashboardSharing` is enabled, Site Kit's site health information should be extended with the following information

* Add a row after "Active Modules":
	- `Recoverable Modules: {comma-separated list of recoverable module names}`
		- The debug value should be a comma-separated list of module slugs
* Add rows for all shareable modules after the "Features" row and before the rows for each module
	- `{Module Name} Shared Roles: {comma-separated list of role names}`  
	If there are no shared roles, use `None` (be sure to use proper i18n, e.g. "Active Modules")
		- The debug value should be a comma-separated list of role IDs
	- `{Module Name} Management: {"Owner" or "All admins signed in with Google"}`  
		- The debug value should be the raw setting value, or `owner` if none

## Implementation Brief

- Within `Debug_Data.php`: 
    - In the `get_fields()` method, after the call to `get_active_modules_field()`, add a call to a new method `get_recoverable_modules_field()` that adds recoverable modules to `$fields` array as per the AC. 
    - This new method should be similar to the `get_active_modules_field()`. Use `Modules::get_recoverable_modules()` and format the modules as per the AC.
    - Create another method, say `get_module_sharing_settings_fields()` and fetch all shareable modules using `Modules::get_shareable_modules()`. For each of these modules, create two arrays, each containing the `label`, `value` and `debug` keys. The first array will contain the Shared Roles and the second should contain the Management setting, formatted as per the AC. To find the shared roles and management settings, use `Module_Sharing_Settings::get()`. Return an array of all the arrays generated above (2 arrays per module). Essentially, the resultant array should be formatted such that it can be directly used in the `array_merge()` call within the `get_fields()` method. Merge the new array of fields between the existing `$fields` and `$this->get_module_fields()` within that `array_merge()`. This will add 2 new rows for every shareable module as per the AC.

### Test Coverage

* No new tests are required, but the existing `Debug_DataTest.php` will have to be updated to cater for the new debug fields.

## QA Brief
* Enable the `dashboardSharing` feature flag.
* Change the sharing settings for the modules.
* Go to WordPress Site Health ( `Tools -> Site Health`) -> Site Kit by Google.
* Check the info is displayed as per the AC.

## Changelog entry

* Add Dashboard Sharing's Active Modules and Sharable Modules to Site Health.

**Comment by bethanylang** [comment]
@aaemnnosttv Noting that James had created a similar issue, #4440, which requested these specific details in SH for support: 

- ** Product *** dashboard sharing active: Yes || No
- ** Product *** dashboard sharing - who can view: NA || Administrators, Editors, Authors, Contributors
- ** Product *** dashboard sharing - manage view access: NA || Only me || Admins
- ** Product *** dashboard sharing - module owner:

**Comment by aaemnnosttv** [comment]
Thanks @bethanylang, I wasn't aware of that one but I see you've closed it so we'll plan on using this one going forward. This issue is just a placeholder for now but we'll be sure to work with you to clarify what exactly we want to include here before we start working on it 👍

**Comment by aaemnnosttv** [comment]
@felixarntz I've added some initial ACs here to get this going, let me know what you think.

As for capabilities, which do you think we should include here? I feel it would probably be too much to list out all of the read/manage/delegate meta caps for each shareable module (at least on individual lines). Maybe we could aggregate these into a single line for each?

Site Health is limited to admins as well so we wouldn't be able to capture it for a view-only user.

**Comment by aaemnnosttv** [comment]
@felixarntz actually, regarding the capabilities, these are all currently included when dashboard sharing is enabled. Should we instead change this to limit the capabilities listed here to not include the meta caps as you said?

<img width="755" alt="image" src="https://user-images.githubusercontent.com/1621608/170069788-b8c06d21-0d01-459f-80ec-86ed2c845535.png">

**Comment by eclarke1** [comment]
In the bug bash review meeting yesterday, we agreed for this one to be a launch blocker, so I have updated to P0. It is currently in Backlog, so I have moved to ACs. Please let me know if there's any concerns with this.

**Comment by felixarntz** [comment]
@aaemnnosttv Sorry for the late reply, I had missed your latest comment.

That's neat that these are already included. In that case, I'd say no need to intentionally exclude them. I don't think they're as critical, but arguably for Site Health the more information the better.

**Comment by aaemnnosttv** [comment]
I added another row to list recoverable modules but otherwise this should be good to go 👍

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@asvinb please note the change to the label for management as this has been changed in the UI as well.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- After "Active Modules" there is a new row titled `Recoverable Modules`, which when the recovery alert appears, is populated with either or the Idea Hub and PSI slugs.  When there are no recoverable modules then 'None' appears.

- After the "Features" row there is a new row titled `Shared Roles:` for each module connected, which has a comma-separated list of role names. When there are no shared modules then 'None' appears. 

- After the "Shared Roles" row this is a new roe titled `Management:` for each module connected, which has an entry depending if the access is given to other administrators or not.  The entries appear as "Owner" or "All admins signed in with Google" based on the dashboard settings modal. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/176167822-2d5b0129-d050-4ced-a671-4d6dbe31a348.png)
![image](https://user-images.githubusercontent.com/73545194/176167841-17588330-9997-48c7-a9e8-642e83342388.png)
![image](https://user-images.githubusercontent.com/73545194/176167871-b2060c3e-b478-4b0a-a544-e296099c9505.png)

</details>
