### ISSUE TITLE
Update PageSpeed Insights module datapoints for consistency

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#454]
Datapoints in the PageSpeed Insights module should receive minor updates as outlined in the ACs.

Implementation brief should include which pieces of JS need to be updated and which e2e tests need to be updated (if any).

**Execution is blocked until #406 is merged.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PageSpeed Insights setup and querying PageSpeed Insights data via API should still work as before.
* Datapoint parameters and return values controlled by the plugin itself should all be in camel case.
* Datapoints should be updated as follows:
    * GET site-pagespeed-mobile & GET site-pagespeed-desktop → GET pagespeed
        * additional supported parameter should be “strategy” (must be either “mobile” or “desktop”)

#### `GET site-pagespeed-mobile + GET site-pagespeed-desktop`
* Combine into a new `pagespeed` datapoint
* Add support for new required `strategy` parameter (enum: `mobile` / `desktop`)
* Update usage of `site-pagespeed-mobile`
    - `PageSpeedInsightsDashboardWidgetHomepageSpeedMobile`
* Update usage of `site-pagespeed-desktop`
    - `PageSpeedInsightsDashboardWidgetHomepageSpeedDesktop`

## Changelog entry

* Improve datapoint behavior of PageSpeed Insights module for consistency.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@adamsilverstein would you please regenerate the data for this one?

**Comment by felixarntz** [comment]
@adamsilverstein Let's do this just once for all these datapoint refactoring changes. See #500.

**Comment by felixarntz** [comment]
This will be blocked until #500 is done. Once unblocked, move back to QA column.
