### ISSUE TITLE
Improve error message output when a user encounters a proxy related 400 or 500 error. 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4555]
There have been reports of users encounter the below error during Site Kit setup:

_“Oops! There was a problem during set up. Please try again.
Unknown Error (code: request_failed).”_

This occurs after clicking on the "Proceed" button during site verification, after a user has granted permissions. Before getting to this state there is already a warning as per the below, before attempting Site Kit setup.

_” Looks like your site is having a technical issue with requesting data from Google services.
To get more help, ask a question on our support forum and include the text of the original error message:
google_api_connection_fail ”_

As the _**request_failed**_ error parses an error response which isn't stored improve the messaging that is output to the end user, providing more useful context where possible. 

Example video of this behavior can be found within the additional information of [this Site Health information report](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNg8TmonK7DIe_LiWsG4OihcEEzHEJtR_EYzBl9mYsLPv4NC7sygDA139_V8yDDa5g4). 

![2021-12-14-18-41-38](https://user-images.githubusercontent.com/41326532/146060059-73c38753-dc7b-4010-a211-b9d681a4d156.gif)

 ![image](https://user-images.githubusercontent.com/41326532/146058095-2864d6a9-4835-4b26-b081-2dca92bcf2be.png)## Screenshots

## Additional Context

 - Example video within [this SH info report](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNg8TmonK7DIe_LiWsG4OihcEEzHEJtR_EYzBl9mYsLPv4NC7sygDA139_V8yDDa5g4)
- This particular **_code: request_failed_** error differs to the similar code: **_http_request_failed_** error commonly reported, which is typically associated with a cURL or hosting related issue. 

Previous support topics with this error:
- https://wordpress.org/support/topic/your-site-may-not-be-ready-for-site-kit-google_api_connection_fail-3/#post-15163285 | Open | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNizWGT3J7CiQ-OAhUDQfse8EzCMSPEtkiC9zXk94bmlJ3rmkg3_PHc6hwRevSesbbA)
- https://wordpress.org/support/topic/error-your-site-may-not-be-ready-for-site-kit-3/ | Resolved - ModSecurity
- https://wordpress.org/support/topic/google-site-kit-errors-running-install/page/2/ | Resolved - Unknown fix with no response from user

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@adamsilverstein @felixarntz @bethanylang Tagging you here for notification purposes.

**Comment by felixarntz** [comment]
@jamesozzie @bethanylang Looking at this again, I may have come to an incorrect conclusion during the call where I brought up the idea of storing a message here. This error somehow comes from the proxy I believe, since that is the only way it would show up in this specific spot, and in that case that error code is all we have.

Interestingly, I couldn't find any mention of `request_failed` in either Site Kit, the third-party code that it uses, the proxy, or WordPress core, so it looks like this comes from somewhere else and is then passed through our service to the plugin, i.e. it's not an error that we'd expect anywhere at this point. We may need to dig in further, but I believe this issue here as is now somewhat irrelevant and should be closed. Let me know if that makes sense.

**Comment by henrywright** [comment]
@felixarntz `Google_Proxy::request()` seems to return an object of type `WP_Error` referencing the `request_failed` code if the response is less than 200 or greater than 299

I'm not sure of the exact request being made and don't have access to the Google Proxy server documentation so I don't know why it is responding in this way
