### ISSUE TITLE
Google AdSense Host API integration

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4559]
## Feature Description

Consider supporting the [AdSense Host API](https://developers.google.com/adsense/host). This was [proposed in the support forums](https://wordpress.org/support/topic/adsense-host-api-program/) and may be useful for network installs, whereby individual site owners can benefit from a network site using a shared revenue model with AdSense. 

- [Related support topic](https://wordpress.org/support/topic/error-your-site-may-not-be-ready-for-site-kit-3/)
- [AdSense Host API documentation](https://developers.google.com/adsense/host)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
The AdSense Host API is pretty much only relevant for very large platforms, or networks of sites. In the API documentation it speaks about 100k+ daily pageviews, which is probably a value that only a tiny fraction of Site Kit sites get to as of now. Furthermore, as Site Kit still does not properly support multisite, there wouldn't be a lot of value in implementing an AdSense Host API integration.

The use-case for this API is too narrow and specific to be valuable enough to the average Site Kit audience.
