### ISSUE TITLE
Add a loading indictor after clicking on the "Proceed" button during initial setup

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4568]
## Bug Description

During setup on a new site after clicking on the "Proceed" button it can take a long time before verification is complete. Add a loading indicator after clicking on the proceed button. This may be useful in the event that users abandon setup or refresh the page before setup is complete. 

Example video below, over 10 seconds of a delay. 
https://recordit.co/HhbOodHrrR

![image](https://user-images.githubusercontent.com/41326532/146374878-c60064d8-e4ce-4a3f-90a3-a3df52e88e09.png)

## Steps to reproduce

1. Setup Site Kit on a new domain
2. Observe the wait time after clicking on the "Proceed" button during site verification 

## Additional Context

 - Site Kit 1.47 and older versions
 - Possible changes to the setup flow may make this issue redundant

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@jamesozzie this isn't something we can action on the plugin side. Would you please move this to an internal issue for the service?

**Comment by jamesozzie** [comment]
Thanks @aaemnnosttv. 

[Asana task created](https://app.asana.com/0/1185360131189553/1201787722751716/f) for team review. Closing this issue.
