### ISSUE TITLE
Clean up minor legacy UI in the unified dashboard widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4570]
As I just reviewed the unified dashboard again with @marrrmarrr  as part of release approval, we noticed a few minor things that should be quick to address but would go a long way. As a summary, a few widget titles should be changed, the source links should show in a consistent location, and the new "overall page metrics" widget should be adjusted to only show in the entity dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The title of the new Search Funnel widget (currently _Overview for the last 28 days_) should be changed to: _Search traffic over the last 28 days_
    * Background: The current "Overview" title was likely taken over from the former Analytics module overview widget which served as a foundation for this new widget, but that title isn't quite suitable here.
* The new "Overall page metrics" widget should have its registration adjusted so that it is only registered/rendered in the entity dashboard - it should be removed from the main dashboard.
    * Background: Those metrics mostly make sense in relation to the "Top content" widget that shows in the main dashboard. Essentially, they are a "zoom-in" on a single row in that widget, which makes sense to show in the entity dashboard. The current way this widget shows in the main dashboard though is a bit confusing and out of place. We can think about a better way to include those "summary/total" page metrics in there, but for now let's get rid of it. None of these metrics were present in the previous dashboard, and while it's nice to have them, we shouldn't add them "just because we can".
* All widgets that currently display their source link in their upper right corner (usually phrased as "See full stats in ...") should have those links removed. Instead, it needs to be ensured that the same link displays in the footer of the widget, on the left, as "Source: ..." like it is in most widgets. This specifically applies to at least the Search Funnel widget, the Analytics Top Content widget, and the AdSense Performance widget.
    * These UI adjustments should be made conditionally only if the `unifiedDashboard` feature flag is enabled.
    * Background: All the widgets that currently have the source link on the upper right originate from the former module pages, where this was a common UI pattern, different from the dashboard. Now they should be changed to be consistent across the dashboard though.

## Implementation Brief
* Create `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Footer.js` which exports the `Footer` functional component.
	* It should take most of the code from `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Header.js` with the following changes:
		* Remove usage of `WidgetHeaderTitle` within the file along with associated logic.
		* Replace usage of `WidgetHeaderCTA` by `SourceLink`.
		* The `See full stats in...` text should be removed.
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Header.js`,
	* Update the `Overview for the last...` label to `Search traffic over the last...`.
	* Remove usage of `WidgetHeaderCTA` within the file.
* Using `assets/js/modules/analytics/components/module/ModulePopularPagesWidget/Header.js`,
	* Using the `useFeature` hook, check if the `unifiedDashboard` feature flag is enabled.
	* If the feature flag is enabled, do not render `WidgetHeaderCTA`. 
* Create `assets/js/modules/adsense/components/module/ModuleOverviewWidget/Footer.js` which exports the `Footer` functional component.
	* It should take most of the code from `assets/js/modules/adsense/components/module/ModuleOverviewWidget/Header.js` with the following changes:
		* Remove usage of `WidgetHeaderTitle` within the file along with associated logic.
		* Replace usage of `WidgetHeaderCTA` by `SourceLink`.
		* The `See full stats in...` text should be removed.
* Using `assets/js/modules/adsense/components/module/ModuleOverviewWidget/Header.js`, do not render `WidgetHeaderCTA` if the `unifiedDashboard` feature flag is enabled.
* Using `assets/js/modules/adsense/components/module/ModuleOverviewWidget/index.js`, pass the new `Widget` component as value to the `Footer` prop when rendering `Widget` if the `unifiedDashboard` feature flag is enabled.
* Using `assets/js/modules/analytics/index.js`,
	* Update the registration for `analyticsOverallPageMetrics` to be only present for `AREA_ENTITY_DASHBOARD_CONTENT_PRIMARY`

### Test Coverage

* 

## QA Brief

* Connect the Analytics and AdSense services.
* Using the [Tester Plugin](https://sitekit.withgoogle.com/service/download/google-site-kit-tester.zip), enable the `unifiedDashboard` feature flag.
* Navigate to the Dashboard.
* Verify the Search Funnel widget title is now "Search traffic over the last 28 days".
* Verify that all widgets no longer have the "See full stats in..." CTA in the widget header, and instead have the "Source:" link in the widget footer. Specifically, the widgets updated in the PR are:
  * Search Console `SearchFunnelWidget` (title: "Search traffic over the last 28 days").
  * Analytics `ModulePopularPagesWidget` (title: "Top content over the last 28 days").
  * AdSense `ModuleOverviewWidget` (title: "Performance over the last 28 days").
* Verify the Analytics `DashboardOverallPageMetricsWidget` (title: "Overall page metrics over the last 28 days") **is not** present on the page.
* Navigate to an Entity Dashboard and verify the `DashboardOverallPageMetricsWidget` **is** still present on the page.
* Using the [Tester Plugin](https://sitekit.withgoogle.com/service/download/google-site-kit-tester.zip), disable the `unifiedDashboard` feature flag.
* Navigate to the appropriate module page and verify the "See full stats in..." CTA is unchanged for:
  * Analytics `ModulePopularPagesWidget` (title: "Top content over the last 28 days").
  * AdSense `ModuleOverviewWidget` (title: "Performance over the last 28 days").

## Changelog entry

* Update source links on unified dashboard widgets to be consistent across all widgets.

**Comment by felixarntz** [comment]
cc @aaemnnosttv @tofumatt @eugene-manuilov

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@techanvil a few observations:

1. The external link icon does not appear on Adsense source link.
2. The Adsense source link doesn't open in a new window like the other source links.

![image](https://user-images.githubusercontent.com/73545194/149130100-c736ce5d-dccd-4373-acd3-36b09515ebb6.png)
