### ISSUE TITLE
New Search Funnel widget still showing legacy blue zero data box

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4571]
When there is no Search Console data to display (to clarify: "zero data", not "gathering data"), the Search Funnel widget still shows the legacy blue CTA - which per #4085 and #4086 should only be shown if the service is actually gathering data. This should be fixed - it is especially problematic in the case that Analytics isn't activated yet, in which case that CTA will not be shown either.

In other words, the below UI should _only_ be shown if Search Console is actually gathering data. Currently, it is also being shown when Search Console report has zero data, regardless of the "gathering data" situation.
<img width="1499" alt="Screen Shot 2021-12-16 at 9 37 56 AM" src="https://user-images.githubusercontent.com/3531426/146422802-16944877-8d23-48d1-96ad-fdc3f9d7a713.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SearchFunnel` widget should be adjusted so that it only renders in the "blue zero data box" state if the Search Console report is zero _and_ Search Console `isGatheringData`.
* Otherwise, the widget should be rendered as usual, with the Search Console metrics displaying 0s and empty charts as needed.
* For the Analytics data in the widget, it should work as follows:
    * If Analytics is not active/connected, render the CTA the same as already happens today.
    * Otherwise if the Analytics report is zero _and_ Analytics `isGatheringData`, render the blue `ReportZero` component in there, similar to the Analytics CTA, in place of the Analytics-specific tabs which therefore cannot be accessed.
    * If the Analytics report is zero but Analytics is no longer "gathering data", the metrics should be rendered as usual, like for Search Console, displaying 0s and empty charts as needed.

## Implementation Brief
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`,
	* Query the `search-console` and `analytics` data store separately via the `isGatheringData` selector to see if the data is being gathered for each module.
	* For Search Console,
		* If the selector returns `true` and the report data is zero (via the `isZeroReport` function from `assets/js/modules/search-console/util/is-zero-report.js`), render `WidgetReportZero`, with `search-console` as value for the `moduleSlug` prop.
		* The `WidgetReportZero` component should be rendered in place of the first 2 data blocks (which are Search Console specific), similar to how it's done for Analytics.
	* For Analytics,
		* Check if the analytics module is active and connected, if not, return `false` when using the `isGatheringData` selector.
		* Update the condition to render `WidgetReportZero` by adding whether the result from the `isGatheringData` selector is `true`.
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js`,
	* Query the `search-console` and `analytics` data store separately via the `isGatheringData` selector to see if the data is being gathered for each module.
	* When querying the `analytics` data store via the `isGatheringData` selector, check if the analytics module is active and connected, similar to how it's being done for `analyticsOverviewLoading`. If `isAnalyticsConnected` is `false`, return `false`.
	* If the above selector returns `undefined`, render the `PreviewBlock` similar to how it's being done today.
	* Remove `WidgetReportZero` and associated logic to render it.
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.stories.js`, update stories for cater for above scenarios.

### Test Coverage

* 

## QA Brief

- Go to the Site Kit dashboard 
- Verify If Search Console is gathering data
- Only `Search Console Gathering Data` CTA will be rendered, nothing else.
- Verify `Overview` component (that contains Analytics data) will only ever be rendered if Search Console is not gathering data
- Verify if the Analytics is in gathering data, the blue CTA for Analytics gathering data should be rendered

- **QA:Eng** - Verify the newly added stories `Analytics Gathering Data` and `Search Console Zero State ` for the `SearchFunnelWidget` component have the CTA rendered

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@asvinb The IB is almost good to go, except for one thing: Wherever we add `isGatheringData` checks for `analytics`, we need to make sure they only run if the `analytics` module is also active and connected. That limitation, which especially is relevant for `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js` where none of those checks are present is currently missing from the IB. In that file, if `analytics` isn't active and connected, the request shouldn't be made so it shouldn't impact the component's "loading" state.

**Comment by asvinb** [comment]
Thanks @felixarntz . IB updated!

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t @aaemnnosttv I would like some clarification on the last point of the QAB:

> Similarly if the Analytics is in gathering data state. Verify the blue CTA for Analytics gathering data should be rendered.

I have a scenario where there is either zero data or actual data in search console, but the `SearchFunnelWidget` (Search traffic over the last 28 days) is not appearing when Analytics is connected and gathering data. I would have expected to see the Search Console data and a gathering data box where the analytics date is shown. Am I missing something?

This is what I see in 'Traffic' on a site where it has a new Analytics account.

![image](https://user-images.githubusercontent.com/73545194/149160371-e9bb9829-77b6-4ccb-b4ca-58b26b9d7c86.png)

This is what I see in 'Traffic' on a site that has an Analytics account with data. 

![image](https://user-images.githubusercontent.com/73545194/149160034-3667aaf3-f85b-4a0b-9901-709f1aebea34.png)

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@aaemnnosttv @tofumatt I've gone through thee QABs again on this one, and have found a scenario where Analytics has zero data and search console is gathering data. It's not really covered in the QAB, but in this situation I would expect to see the zero data on the search funnel for Analytics, and gathering data box for Search console. 

![image](https://user-images.githubusercontent.com/73545194/149242515-ddfa1cf3-e83e-45f1-b200-bf030e3c531f.png)

This is basically the opposite of the [issue reported](https://github.com/google/site-kit-wp/issues/4571#issuecomment-1011108764) yesterday, which is now fixed. 

**Verified:**

- When the Search Console is in gathering data state, the blue CTA for Search Console gathering data is rendered
- When the Search Console report is zero and not gathering data, the blue CTA for gathering data is not rendered.
- When the Analytics is in gathering data state, the blue CTA for Analytics gathering data is rendered.
- The [issue reported](https://github.com/google/site-kit-wp/issues/4571#issuecomment-1011108764) is fixed when the site has zero (or live) data but Analytics is gathering data.

**Comment by hussain-t** [comment]
@wpdarren If Search Console is gathering data only `Search Console Gathering Data` CTA will be rendered, nothing else.
In other words, `Overview` component (that contains Analytics data) will only ever be rendered if Search Console is not gathering data.

Please refer to @aaemnnosttv's [comment](https://github.com/google/site-kit-wp/pull/4639#discussion_r782906437) on the PR. I will update the QAB.

Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When the Search Console is in gathering data state, the blue CTA for Search Console gathering data is rendered
- When the Search Console report is zero and not gathering data, the blue CTA for gathering data is not rendered.
- When the Analytics is in gathering data state, the blue CTA for Analytics gathering data is rendered.
- The [issue reported](https://github.com/google/site-kit-wp/issues/4571#issuecomment-1011108764) is fixed when the site has zero (or live) data but Analytics is gathering data. 
- When the Search funnel widget it is only rendered if Search Console is not gathering data.
