### ISSUE TITLE
Refactor Webpack configurations with modules

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4575]
## Feature Description

Our main webpack configuration is currently a bit unwieldy with everything in a single file spanning  ~600 lines. As it is, our build is also using Webpack's multi-compilation mode as a JS function which offers us the most flexibility in how this is composed.

We also use a custom configuration for Storybook, for which some parts of the configuration may be shareable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The [main webpack configuration](https://github.com/google/site-kit-wp/blob/bfd82b9dac98d7c91769c5f84dd5c70ac54b2981/webpack.config.js) should be refactored so its high level structure is easy to comprehend.
- Code should be lifted out of the configuration and moved in logical groups to files under a new `webpack` folder in the repository root.
- The moved code should be organised and refactored if necessary to ensure it too is easy to understand and not overly monolithic.
- The [Storybook webpack configuration](https://github.com/google/site-kit-wp/blob/bfd82b9dac98d7c91769c5f84dd5c70ac54b2981/.storybook/webpack.config.js) should be updated so it no longer imports the entire main config, rather it imports the specific parts it depends on from their new locations.

## Implementation Brief

* From `webpack.config.js`, a potential splitting suggesting can be:
  * Create `webpack/common.js`
    * You can extract here the rules, templates (e.q `manifestTemplate`, etc), externals, etc, smaller partials like these 
  * Create `webpack/config.main.js`
    * Extract the main [webpack config](https://github.com/google/site-kit-wp/blob/0c95ea52bf9a5690c29051b66bc547bf25ce8235/webpack.config.js#L275)
  * Create `webpack/config.basicModules.js`
    * Extract basic modules [config object](https://github.com/google/site-kit-wp/blob/0c95ea52bf9a5690c29051b66bc547bf25ce8235/webpack.config.js#L435-L468) that will be yielded in main webpack.config as import
  * Create `webpack/config.adminCss.js`
    * Extract also the admin css [config object](https://github.com/google/site-kit-wp/blob/0c95ea52bf9a5690c29051b66bc547bf25ce8235/webpack.config.js#L471-L521)
  * Create `webpack/testBundle.js`
    * Extract the [test bundle function](https://github.com/google/site-kit-wp/blob/0c95ea52bf9a5690c29051b66bc547bf25ce8235/webpack.config.js#L523-L547)
* Ensure all dependencies are properly imported, and if during execution it makes more sense reduce the number of files, or add additional ones.
* Update `.storybook/webpack.config.js`
  * Instead of using `mainConfig`, import `siteKitExternals`, and `svgRule` from new file replacing the current usage

### Test Coverage

* No updates needed, just ensure all scripts still work, for build, dev, tests, sotrybook...

## QA Brief

* Ensure that builds work, e2e, jest, storybook, etc.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
LGTM, thanks @techanvil 👍

**Comment by tofumatt** [comment]
@zutigrm Rather than have that many files for things like `resolve`, `externals`, etc., what about a `webpack/common` or `webpack/shared` that exported several constants for different things like `resolve`, `externals`, etc.?

I imagine they might have some shared context, and it might be easier to comprehend the shared/common stuff in one file.

Or I suppose it could be left up to the developer implementing things how much we want to split things out? But we probably don't have to be _too_ explicit about it in the IB, unless the "shared" approach suggested would for sure be too long/big of a file 😄

**Comment by tofumatt** [comment]
Sounds good! 👍🏻 

IB ✅

**Comment by nfmohit** [comment]
## QA:Eng ✅ 

* Tested developer and production builds.
* Tested E2E tests.
* Tested unit tests.
* Tested Storybook builds.
* Verified tests pass in CI.
