### ISSUE TITLE
Update plugin zips workflow to only run when necessary

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4577]
## Feature Description

Our GitHub actions workflow for building and deploying plugin zips runs when it doesn't need to in some cases ([example](https://github.com/google/site-kit-wp/pull/4576)).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The plugin zip file workflow (`zips.yml`) should only run for PRs or select branches when:
    * Source or configuration files have changed that affect the resulting zip file
    * the `zips.yml` workflow was changed  

## Implementation Brief

- Update the `.github/workflows/zips.yml` workflow to run jobs only when the PR contains changes in the following paths:
  - `.github/workflows/zips.yml`
  - `bin/release`
  - `assets/**`
  - `!assets/**/__tests__/**/*.js`
  - `!assets/**/test/*.js`
  - `!assets/**/*.test.js`
  - `includes/**`
  - `google-site-kit.php`
  - `scoper.inc.php`
  - `uninstall.php`
  - `composer.json`
  - `composer.lock`
  - `php-scoper/composer.lock`
  - `package.json`
  - `package-lock.json`
  - `postcss.config.js`
  - `webpack.config.js`
  - `feature-flags.json`

### Test Coverage

* N/A

## QA Brief

**`QA:Eng`**:

* Create a PR with a change to a file within the above list (but not an excluded file).
  * Confirm that the _Plugin Zip Files_ workflow **does** run for the PR.
* Create a PR with a change to a file outside the above list.
  * Confirm that the _Plugin Zip Files_ workflow **does not** run for the PR.
* Create a PR with a change to a JS test file under `assets/`.
  * Confirm that the _Plugin Zip Files_ workflow **does not** run for the PR.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@eugene-manuilov there are some additional files we'd want to include in the root, such as `google-site-kit.php` and various config files. We should probably also consider `bin/release`. Probably safe to ignore `*.md`. Maybe it would be less paths to only specify `paths-ignore` as we do today?

**Comment by eugene-manuilov** [comment]
Ah... yes, you are right, @aaemnnosttv. IB is updated.

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov! This looks good now, just one question: do you think it makes sense to include `.babelrc` as well? 🤔

**Comment by eugene-manuilov** [comment]
> do you think it makes sense to include `.babelrc` as well?

No, that is not needed. We use it only for jest tests.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by hussain-t** [comment]
## QA:Eng - Verified ✅ 

- Create a PR with a change to a file within the above list (but not an excluded file) - Plugin Zip Files workflow **DID** run
<img width="924" alt="Screenshot 2022-01-27 at 9 48 40 PM" src="https://user-images.githubusercontent.com/24408261/151399611-52561668-25f5-43ca-80b8-a19b404e2ee1.png">

- Create a PR with a change to a file outside the above list - Plugin Zip Files workflow **DIDN'T** run
<img width="924" alt="Screenshot 2022-01-27 at 9 33 05 PM" src="https://user-images.githubusercontent.com/24408261/151399848-ef0f243a-c6a4-422a-a56f-323002f47d3a.png">

- Create a PR with a change to a JS test file under `assets/` - Plugin Zip Files workflow **DIDN'T** run
<img width="924" alt="Screenshot 2022-01-27 at 9 43 27 PM" src="https://user-images.githubusercontent.com/24408261/151399713-72c155bb-df1a-4ee4-a61f-9e9e46d846ba.png">
