### ISSUE TITLE
Introduce module interface for service entities

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4579]
## Feature Description

Currently some module classes have a distinguishing feature that they interact with an "owned" service entity on their respective Google service which has a related `Module_With_Owner` interface. With dashboard sharing, this will evolve in modules that weren't previously "owned" being ownable, even though they don't have a service entity.

Later, this will also become important for determining "all-admin" modules.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `Google\Site_Kit\Core\Modules\Module_With_Service_Entity` interface that defines the following method:
    * `check_service_entity_access() : bool|WP_Error`
        - The implementation will vary for each module but should generally involve the simplest API request to verify the current user has access to the current configured service entity (e.g. Analytics property) or return a relevant error if not
        - If the user has access, return `true`
        - If the user does not have access to the entity specifically (i.e. the request to the Google API fails with a `403`), return `false`
        - If the request fails for any other reason, return an appropriate `WP_Error`
* This interface should be implemented for all modules that identify a service entity (e.g. Analytics property) in their owned settings. These are:
    * Search Console
    * Analytics (also Analytics 4)
    * AdSense
    * Optimize: For Optimize, there is no API to check, so here this can be a no-op for now that always returns `true`, especially since it won't be relevant for dashboard sharing anyway. Probably worth annotating with a TODO comment.

## Implementation Brief
* Create `includes/Core/Modules/Module_With_Service_Entity.php` which contains the `Module_With_Service_Entity` interface.
	* It should define the `check_service_entity_access` as per the AC.
	* Namespace should be `Google\Site_Kit\Core\Modules`
* The following class should implement the `Module_With_Service_Entity` interface and define the public `check_service_entity_access` method.
	* `includes/Modules/Search_Console.php`
	* `includes/Modules/Analytics_4.php`
	* `includes/Modules/Analytics.php`
	* `includes/Modules/AdSense.php`
	* `includes/Modules/Optimize.php`
* Update `includes/Modules/Search_Console.php`,
	* `check_service_entity_access` should do the following:
		* Use the `create_search_analytics_data_request` method to make a sample API request to the Search Console API. The `start_date` and `end_date` parameters are mandatory and can be the current date in `YYYY-MM-DD` format. `row_limit` should be `1` since we are not going to do anything meaningful with the data.
		* Check if the request fails with a `403` error and return the response as per the AC.
* Update `includes/Modules/Analytics.php`,
	* `check_service_entity_access` should do the following:
		* Use the `create_analytics_site_data_request` method to make a sample API request to the Analytics API. `row_limit` should be `1` since we are not going to do anything meaningful with the data.
		* Check if the request fails with a `403` error and return the response as per the AC.
* Update `includes/Modules/Analytics_4.php`,
	* `check_service_entity_access` should do the following:
		* Use the same logic (`listPropertiesWebDataStreams` method) to get the webdatastreams (`GET:webdatastreams`) as in the `create_data_request` method.
		* The property ID passed to `listPropertiesWebDataStreams` can be obtained from the module's settings (`propertyID`).
		* Check if the request fails with a `403` error and return the response as per the AC.
* Update `includes/Modules/AdSense.php`,
	* `check_service_entity_access` should do the following:
		* Use the `create_adsense_earning_data_request` method to make a sample API request to the AdSense API. The `start_date` and `end_date` parameters are mandatory and can be the current date in `YYYY-MM-DD` format. `limit` should be `1` since we are not going to do anything meaningful with the data.
		* Depending on the result, return the response as per the AC.
* Update `includes/Modules/Optimize.php`,
	* The `check_service_entity_access` method should always return `true` since there is no API to check. There should be a comment explaining why this the method always returns `true`.

### Test Coverage
* Tests to be added for the new `check_service_entity_access` method for all modules.

## QA Brief

This will be ready for proper QA in the #4478 ticket as it will expose a API that makes use of it. 

* QA:Eng: Ensure the correctness of added test. 

## Changelog entry

* Extend some modules with service entity awareness and access checks.

**Comment by felixarntz** [comment]
@aaemnnosttv One point of feedback about the ACs: Do we even need the `get_service_entity() : array` method, as in would we use it anywhere outside of `check_service_entity_access(array)`? If not, I'd suggest that we don't introduce it and instead only have a `check_service_entity_access() : bool|WP_Error` method.

It's a bit "vague" to me to rely on the `array` return/argument type here, I'd envision something like a `Service_Entity` class instance instead. However, I don't think it's worth going that far here (and maybe not anytime soon), so let's not get too much into that. I _do_ think though that for that reason, if we don't need a separate `get_service_entity()` method, I'd prefer to omit it to just have a "service entity format-unaware" interface. A trait could still exist for the common implementation, just on a protected method instead.

**Comment by felixarntz** [comment]
@aaemnnosttv Actually, another thing: #4478 includes a notion of a reason for why there is no access, which I think makes sense to have. How do you envision that "reason" being communicated by the method here? Would the `WP_Error` be returned to indicate no access? If so, how would we differentiate between a `WP_Error` because of no access vs because of an actual (runtime) error in the check (e.g. API request failed)?

If the `WP_Error` communicates the reason for lack of API access, then we could also simplify the method here to always return only a `WP_Error|null`, which would be a bit more "type-correct" than `WP_Error|true`.

**Comment by aaemnnosttv** [comment]
@felixarntz it sounds like you're assuming it would never return `false`, but the idea was a result of no access would be a normal expected value to encounter here and would return `false` rather than a `WP_Error`. A request failure for any other reason would return a `WP_Error`. I'll update the ACs to be more clear about that.

I also thought along the lines of your error-only suggestion, but using exceptions. So, similar to some other places, it would throw if it had no access for any reason otherwise if no exception was thrown then the user has access. This puts the responsibility on the caller to handle it in every case though. That makes a better case for `WP_Error`s but I think the boolean simplifies the most common scenarios.

**Comment by felixarntz** [comment]
@aaemnnosttv That makes sense for that point, could you also address my other feedback from above?
* Can we avoid having `get_service_entity() : array` on the interface unless we absolutely need it?
* How would this work with the "reason" field specified by #4478 if it's just a boolean return value?

**Comment by aaemnnosttv** [comment]
@felixarntz oops, sorry about that!

> * Can we avoid having `get_service_entity() : array` on the interface unless we absolutely need it?

We still need the method to be public in order for it to be called by `Modules` in the `check-access` handler. It could be included in the trait as an abstract public method but then you are somewhat doing the same thing without the benefit of the interface. If you'd prefer, we could have the interface define a `check_current_service_entity_access` which takes no parameters rather than one that accepts the entity as an argument? Or maybe, if no array is passed to it, it defaults to using the current configuration?

> * How would this work with the "reason" field specified by [Add a new `check-access` endpoint to core modules #4478](https://github.com/google/site-kit-wp/issues/4478) if it's just a boolean return value?

It would still return a `WP_Error` in some situations.

* If the user had access, `reason` would be empty or not present
* If the user did not have access (403), the check here would return `false`. In this case `reason` could be set to `no_access` for example, but in the request handler
* If the access could not be checked or failed for any other reason, a `WP_Error` would be returned which would set the `reason` using its code

**Comment by felixarntz** [comment]
@aaemnnosttv 
> We still need the method to be public in order for it to be called by `Modules` in the `check-access` handler.

Looking at the ACs from #4478, couldn't the `check-access` handler simply call a parameter-less `check_service_entity_access() : bool|WP_Error` method, to check access for the module's currently configured service entity? I don't think we need to know what the current service entity actually is for that method since it pretty much only returns a boolean anyway.

> If the user did not have access (403), the check here would return `false`. In this case `reason` could be set to `no_access` for example, but in the request handler

Per what we talked about in our call, I don't think that would provide a benefit though. My take on this is that, if anything other than a 200 or 403 is returned, something actually went wrong in the check, and in that case we shouldn't return `false` with an error reason, but instead we should return a full error response like we normally do for errors, since such a non-200/403 result would be unexpected.

**Comment by aaemnnosttv** [comment]
> couldn't the `check-access` handler simply call a parameter-less `check_service_entity_access() : bool|WP_Error` method, to check access for the module's currently configured service entity? I don't think we need to know what the current service entity actually is for that method since it pretty much only returns a boolean anyway.

Yes of course. We had originally discussed passing the entity to the method though so that's been the approach we started with. I'll update it to remove that parameter for now.

> Per what we talked about in our call, I don't think that would provide a benefit though. My take on this is that, if anything other than a 200 or 403 is returned, something actually went wrong in the check, and in that case we shouldn't return `false` with an error reason, but instead we should return a full error response like we normally do for errors, since such a non-200/403 result would be unexpected.

SGTM 👍

**Comment by felixarntz** [comment]
@aaemnnosttv LGTM! I've added a list of the specific modules that need to implement this, just to clarify.

**Comment by aaemnnosttv** [comment]
> * Namespace should be `Google\Site_Kit\Core\Modules\Module_With_Service_Entity`

@asvinb this would be the fully qualified name of the interface – the namespace would be everything except the last part 👍 

> * The following class should implement the `Module_With_Service_Entity` interface and define the public `check_service_entity_access` method.

This list is missing GA4 as mentioned in the ACs.

> * Update `includes/Modules/Search_Console.php`
>   * Get the property ID via the `get_property_id` method and then make a sample query to the Search Console API. For e.g using

This is correct but worth mentioning that the `create_search_analytics_data_request` method can be used to do the entire request, but it would probably be a good idea to set a minimal `row_limit` since that data won't actually be used.


> Update `includes/Modules/Analytics.php`,
> * `check_service_entity_access` should do the following:

Similar to SC, Analytics has a `create_analytics_site_data_request` method which uses the `viewId` from settings (which is all that's actually needed for the UA API). Again, the minimal `row_limit` should be requested. The `has_access_to_property` method is for checking access when only the property is known, such as with an existing tag.

Regarding GA4, we don't use the GA4 reporting API yet, so we'd need to probably use `GET:webdatastreams` with the configured `propertyID` as the user shouldn't be able to request the web data streams if they don't have access to the property.

> Update `includes/Modules/AdSense.php`,
> * `check_service_entity_access` should do the following:

AdSense has a similar request helper method like SC and Analytics, `create_adsense_earning_data_request`. Let's again use a minimal limit but otherwise nothing else should be needed here I think.

**Comment by asvinb** [comment]
Thanks for this your feedback @aaemnnosttv . IB has been updated as per your comments. Let me know what you think.

**Comment by aaemnnosttv** [comment]
Great, thanks @asvinb 👍 

IB ✅

**Comment by kuasha420** [comment]
@aaemnnosttv I have fixed the auto imported `Exception` class issues. I also tried to write unit test, but didn't get far due to my lack of knowledge on php unit testing class methods that calls http.

We will also need to decide on the `WP_Error` message. 

I'm sending it to CR and your away. 

Cheers.

**Comment by techanvil** [comment]
## QA :white_check_mark: 

`QA:Eng:`

* Reviewed the PHPUnit tests to ensure correctness.
* By way of reviewing the tests, also gave the overall code another review.
