### ISSUE TITLE
Typing `HOME` and `END` on the search box selects the first result instead of placing the cursor to the right place.

### ISSUE THREAD

**Issue by mitogh** [google/site-kit-wp#4584]
## Bug Description

When moving the cursor using the keyboard in the search box using the keys:

- <kbd>home</kbd>
- <kbd>end</kbd>

Removes the focus of the keyboard and returns the first result instead of placing the cursor into the right place on the search box, this behavior in inputs like the address from the browser moves the cursor to the start or to the end respectively instead.  When the search on Site KIt does not follow this behavior, this is problematic as you might want to quickly navigate to fix a typo to either side and this bug prevents you from doing so as it clears your current search.

## Steps to reproduce

1. Go to Site Kit Dashboard
2. Click on Search and type either a long sentence or a URL with results
3. Click on either  <kbd>home</kbd> if you are at the end of the cursor and see how the first result is selected if any or `No Result found` is displayed instead if none is found. Repeat the same process if your cursor is at the start of the line and type <kbd>end</kbd> instead

## Screenshots

![2021-12-17_17-46](https://user-images.githubusercontent.com/3921289/146620123-ac0e934d-5ba5-48ba-9c7e-d81dd5ac6790.png)

## Additional Context

 - PHP Version: 7.4
 - OS: iOS
 - Browser: Chrome
 - Plugin Version: 1.48.0
 - Device: iPad

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the entity search input is focused, the <kbd>Home</kbd> and <kbd>End</kbd> keys should move the cursor within the search input rather than changing the focused items in the results menu

## Implementation Brief
* Upgrade the `@wordpress/keycodes` package to the latest version, which is `3.2.4` at the time of writing to have the `HOME` and `END` keycodes.
* Using `assets/js/components/PostSearcherAutoSuggest.js`,
	* Import the `HOME` and `END` constants from `@wordpress/keycodes`.
	* Create a new ref using the `useRef` hook, to be used for `ComboboxInput`.
	* Update the `onKeyDown` function to check if:
		* The `HOME` key has been pressed and the input is not empty. If this is the case, block the default action for that key and set the cursor to the start of the input text using `selectionStart` and `selectionEnd`, using the ref previously created.
			```js
			inputRef.current.selectionStart = 0;
			inputRef.current.selectionEnd = 0;
			```
		* The `END` key has been pressed and the input is not empty. If this is the case, block the default action for that key and set the cursor to the end of the input text using `selectionStart` and `selectionEnd`, using the ref previously created.
			```js
			inputRef.current.selectionStart = inputRef.current.value.length;
			inputRef.current.selectionEnd = inputRef.current.value.length;
			```

### Test Coverage
* No new tests to be added.

## QA Brief

* Enable the `unifiedDashboard` feature flag.
* Navigate to the Dashboard.
* Type some text in the URL Search field.
* Verify the Home and End keys work as expected, moving the cursor to the start/end of the line.
* Disable the `unifiedDashboard` feature flag and repeat the above in the **Search for individual page or post information** widget.

## Changelog entry

* Update the URL search input box to work correctly when HOME or END keys are pressed.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil This issue is resolved when UFD is enabled for main dashboard and for entity dashboard.
But I've found that on **current dashboard (UFD disabled)** issue still exists. Will you resolve this issue in same PR or I create a new issue for that, or should I ignore this (since current dashboard going at some point) ?

cc @wpdarren

**Comment by techanvil** [comment]
Hey @mohitwp, thanks for bringing this up. I've taken a look and realised that I could/should have made the change in a way that would work for both the unified and non-unified dashboard.

I've just created a new PR that addresses this, so I'll move this ticket out of QA until the PR has been merged and it's ready to test again.

Cheers!

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified:**

- `Home` and `End` key functionality when UFD is enabled for main and entity dashboard.
- `Home` and `End` key functionality when UFD is disabled.
- Verified on Firefox, Chrome, Safari and Edge.
- Verified on WP 5.8.3 and 5.9 RC3.

<details>

https://user-images.githubusercontent.com/94359491/150926164-fc921d12-9140-4206-afe6-79ad21fc5d86.mp4

</details>
