### ISSUE TITLE
Add stylelint extension to VSCode Extension Recommendation and set it as default `scss` formatter

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#4586]
## Feature Description

We should add stylint vscode extension to the recommended extension array and set it as the default formatter for `scss` file so `prettier` does not incorrectly format it. It will aliviate one of the major pain point keeping `formatOnSave` enabled having to fix the style using the npm script before committing. 

We can use our existing `.vscode` workspace settings to achieve it. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `stylelint.vscode-stylelint` extension should be added to the list of recommendations in `.vscode/extensions.json`.
* `stylelint.vscode-stylelint` should be set as the default formatter for `scss` files in `.vscode/settings.json`.

## Implementation Brief

* Implement as per the AC.

### Test Coverage

* No tests needed.

## QA Brief

* QA:Eng Only
    * Should be checked by an engineer using VSCode/VSCodium or Code - OSS. 
    * Open the site kit folder, the Stylelint extension should show up as a recommendation. 
    * Install it. Then try to edit an SCSS file. 
        * The file should no longer get wrongly formatted using Prettier when using either `formatOnSave` or formatting manually. . Instead, it will be properly formatted with the Sylelint extension and respect our configuration. 
        * The auto-fixable errors will be fixed up when formatting. 
        * The rule violations will be reported like it's done for JS files. 

## Changelog entry

* N/A.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by jimmymadon** [comment]
## QA: Eng ✅ 

- Verified extension is recommended (if not already installed).
<img width="1090" alt="Screenshot 2022-11-26 at 13 19 50" src="https://user-images.githubusercontent.com/1721319/204091120-c6f3ed1e-3441-47b6-bfc6-7108942899e4.png">

- Verified rule violations are correctly displayed when typing.
<img width="1095" alt="Screenshot 2022-11-26 at 13 21 31" src="https://user-images.githubusercontent.com/1721319/204091140-361c07fd-d52e-48c9-920e-2e529965e255.png">

- Verified rule violations are fixed on save.
