### ISSUE TITLE
Update support for short array syntax

### ISSUE THREAD

**Issue by mitogh** [google/site-kit-wp#4590]
## Feature Description

The current project enforces the usage of `array()` syntax instead of `[]` in PHP, the rule being `(Generic.Arrays.DisallowShortArraySyntax.Found)` upgrading this rule and the syntax on the project can be done safely using an IDE to replace instances of `array()` with `[]`. 

Since the plugin requirements are: 

- WordPress >= 4.7
- PHP >= 5.6

The syntax for the short array is available since `PHP 5.4`, this won't be a breaking change and would be backward compatible, using short array syntax makes it "easier" to create, pass and deal with `arrays`.

This requires changing the current rule from the sniffer as well to prevent any warnings when writing this new type of array. The rule to be updated is:

- `Generic.Arrays.DisallowShortArraySyntax.Found`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kuasha420** [comment]
I think WordPress Coding Standard prefers the long syntax. See https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#declaring-arrays 

This was decided in 2019 Proposal and was not considered for revisit on the [modern proposal](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/
) as well. 

I think we try and follow the WordPress Coding Standards as closely as possible.

**Comment by aaemnnosttv** [comment]
Given the JS-centric nature of Site Kit which has no long array syntax, I think this would be okay to adopt for Site Kit – at least from the argument of readability. Other Google plugins already ignore this rule such as [Web Stories](https://github.com/google/web-stories-wp/blob/3824d2cee3e231ae0795d3b08f6eb15417f49399/phpcs.xml.dist#L5-L7) but one could also make the argument that they should also be using the long form 😄 

Thoughts @felixarntz?

**Comment by felixarntz** [comment]
I would lean against this since our coding standards should widely match the WordPress coding standards. I don't think the short array syntax provides enough benefit to diverge from the WordPress coding standards, so I'd vote to close this - maybe as `maybelater`.

**Comment by mitogh** [comment]
Agree, there's no real benefit in using one or another so closing this one for now.
