### ISSUE TITLE
Update Composer to declare allowed plugins

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4604]
## Feature Description

As of Composer 2.2, a new `allow-plugins` object was added to the schema for `config`.

For more information see: https://getcomposer.org/doc/06-config.md#allow-plugins

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Composer should not prompt/warn about Composer plugins that are needed, e.g.
    * `dealerdirect/phpcodesniffer-composer-installer`
    * `roots/wordpress-core-installer`
* This applies to both the main/root project as well as `./php-scoper`

## Implementation Brief

* Run `composer install` using Composer v2.2.0+
* Evaluate each prompt related to a Composer plugin, approving or disapproving each
	* This will update the `composer.json` with the missing configuration
* Merge #4606

### Test Coverage

* N/A

## QA Brief

* Run `composer install` using Composer v2.2.0+
* See no prompts about Composer plugins

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️
