### ISSUE TITLE
`php-scoper` failing on PHP 7.4

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4605]
## Bug Description

`composer install` recently started failing on our CI actions using PHP 7.4 related to a fatal error raised by PHP Scoper:

```
> php-scoper/vendor/bin/php-scoper add --output-dir=./third-party --force --quiet
PHP Fatal error:  Namespace declaration statement has to be the very first statement or after any declare call in the script in /home/runner/work/site-kit-wp/site-kit-wp/php-scoper/vendor/humbug/php-scoper/bin/php-scoper on line 14
Script php-scoper/vendor/bin/php-scoper add --output-dir=./third-party --force --quiet handling the prefix-dependencies event returned with error code 255
Script @prefix-dependencies was called via post-install-cmd
Error: Process completed with exit code 255.
```

This does not seem to be related to any change in our codebase as the same build that passed 2 days ago failed when run again:
* https://github.com/google/site-kit-wp/runs/4617491254 (rerun: failure)
* https://github.com/google/site-kit-wp/actions/runs/1608039564/attempts/1 (initial run: success)

## Additional Context

* Possibly related to recent release of [Composer 2.2.1](https://github.com/composer/composer/releases/tag/2.2.1) that was tagged less than 24 hours ago
* Only visible in GitHub actions so far, not able to reproduce locally using the same version of Composer and PHP on the command line
* The same error does not happen on our jobs using PHP 8 or 5.6
* Our PHP Scoper config/version has not changed in almost a year https://github.com/google/site-kit-wp/tree/a27f08668b1d738f72672bfc5d7c61e90bef981c/php-scoper https://github.com/google/site-kit-wp/blob/a27f08668b1d738f72672bfc5d7c61e90bef981c/scoper.inc.php

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `php-scoper` should continue to run successfully on PHP 7.4

## Implementation Brief

* Merge #4609 

### Test Coverage

* N/A

## QA Brief

* N/A – the fix will be visible on the PR before merging

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:
