### ISSUE TITLE
cURL error 6: getaddrinfo() while using Cloudflare

### ISSUE THREAD

**Issue by KimHEF** [google/site-kit-wp#4612]
On my selfhosted Wordpress (Ubuntu, Apache2, PHP8.0, MariaDB), the combination of Cloudflare CDN and the Sitekit-Plugin causes the Problem that the Wordpress-Health-Check gives me some Errors.

When I disable SiteKit, the errors disappears.
When I disable Cloudflare as well.
If both are enabled, the following errors appear:
"The REST API has found an error
Your website cannot reach WordPress.org at 198.143.164.251 and returned the error: cURL error 6: getaddrinfo() thread failed to start"

Does anyone have any idea what this may be and why it is occurring in this combination?

Thank you in advance.

**Comment by jamesozzie** [comment]
Hi there @KimHEF, 

If you'd like to open a [support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) in the WordPress support forums we can investigate this for you. Note that cURL related errors are typically hosting related however we can perform some additional checks, or setup an environment similar to your own. What may be occurring based on your comments could be a multi plugin conflict, with which we can perform some troubleshooting checks similar to a support topic [whereby another user encountered the same error](https://wordpress.org/support/topic/error-curl-error-6-getaddrinfo-thread-failed-to-start-error/page/3/). 

If we are able to determine any possible improvement, bug or issue with the Site Kit plugin itself we can at that point reopen this GitHub issue and escalate this for a team review.
