### ISSUE TITLE
GDPR (EU Compliance) related-features

### ISSUE THREAD

**Issue by RicaNeaga** [google/site-kit-wp#462]
## Feature Description

Plase take a look here, it's described fully by the most popular Google Analytics integration plugin staff - https://wordpress.org/support/topic/google-analytics-eu-compliance/

So please implement in your FREE plugin two features:

1. A clear and described how-to tutorial on how the website can be fully compatible with GDPR via your plugin (& Analytics) integration

2. At least a recommended solution for the Visitor Opt-In / Opt-Out Box (frontend UI). 

Or, best-case-scenario, an integrated slim feature for this, like we can find now in this very slim Analytics integration (another example than the one in the link above, Google Analytics Dashboard Plugin for WordPress by MonsterInsights) - https://plugin-planet.com/ga-google-analytics-pro/

Thanks :)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@RicaNeaga Nice suggestion, this functionality is something that has been discussed and will be implemented in future releases. 

You can also use [this](https://gist.github.com/felixarntz/2800ed9abfa13aabfa6e5c8ba9ec5066) WordPress mini plugin. It works as an extension to Site Kit to ensure IP Addresses are anonymized. 

Alternatively, [here's a description](https://felix-arntz.me/blog/customizing-google-analytics-configuration-site-kit-plugin/) of how to add filters to the plugin that would allow a developer to modify the Analytics implementation, specifically under the "Anonymizing IP Addresses" section.

**Comment by Gicminos** [comment]
In the meantime, how do you block google cookies before a prior consent from the user?

**Comment by RicaNeaga** [comment]
Not exactly a must / it's in the gray area - please see 1.3 here (given the following requirements on that page are met) - https://blog.oriel.io/2019/01/24/how-to-make-google-analytics-gdpr-compliant/

However, this must be made clear by Google, and their next wordpress plugin must have an unequivocally and fully compliant GDPR policy (enabled by default, so it can help the regular user).

**Comment by Zodiac1978** [comment]
Recent decision from the European Court of Justice is demanding opt-in for tracking cookies:
https://siriuslegaladvocaten.be/en/no-consent-no-cookie-says-the-european-court-of-justice/

If this is not possible to configure, this plugin is breaking the law in every country of the EU.

**Comment by RicaNeaga** [comment]
Nice catch :) So a consent is MANDATORY before analytics becomes active on the website.

It's a pity Google decided to put out a beta version of this plugin, calling it usable and final. Besides this GDPR ticket, there are also other woocommerce related tickets out there...

https://github.com/google/site-kit-wp/issues/202
https://github.com/google/site-kit-wp/issues/459
https://github.com/google/site-kit-wp/issues/786

Hopefully at some point Google will be more into making stable / legal / functional & usable tools for wordpress & woocommerce. No wonder their plugins are so poorly reviewed by wordpress users... https://profiles.wordpress.org/google/#content-plugins

**Comment by swissspidy** [comment]
The plugin is definitely not _final_. It's a version 1 that we wanted to share with our users who have been waiting a long time for such suite of tools.

We are now working on hard on fixing any bugs that come along such a very first version, and are carefully considering any new enhancements and features — including in the areas of e-commerce and GDPR.

**Comment by Alexxxis88** [comment]
Is there any update on this issue or workaround to make Site Kit GDPR compliant ? 

It looks like a great tool to use on clients' website, however since I'm based in Europe I can't take the risk to violate GDPR rules using it as it is.

**Comment by imagine** [comment]
I just setup my first site in WordPress. I will be using an alternative plugin until this issue is resolved. Major brand trust erosion that Google would keep this plugin active without at least a warning in the plugin description.

**Comment by AkshayRao27** [comment]
I just set one of my websites up as well. I wanted to install this plugin but it looks like this is still not implemented. Does anyone know of a workaround? If not, then I guess I'll have to look for a different plugin.

**Comment by AertHulsebos** [comment]
@all please refer to https://wordpress.org/support/topic/consent-api-integration/,

This would lay the groundwork to comply with privacy laws world wide.

**Comment by rlankhorst** [comment]
+1 for the WP Consent API integration

See also:

https://make.wordpress.org/core/features/
https://github.com/rlankhorst/wp-consent-level-api/
https://wpconsentapi.org/

For any questions on what this aims to do, see the docs, or just ask me :)

Depending on the website settings, the plugin can check for wp_has_consent('statistics-anonymous') or wp_has_consent('statistics')

The consent management plugin the webmaster has chosen can handle the actual consent. The WP Consent API will pass this through to Google Site Kit.

**Comment by mikezielonka** [comment]
Just was browsing the docs to review the current status of GDPR compliance for sitekit.  Hope this makes it into a future sprint in the near future.  👍

**Comment by radusalagean** [comment]
I spent the last couple of days trying to get SiteKit Google Analytics integrated with a consent popup on my WordPress site. The plugin is great, the first time setup was a breeze and I really wanted to keep using it, especially since this is an official plugin by Google and there is no extra unnecessary stuff attached from third parties. However, being unable to use it in a legal way (i.e. complying to GDPR laws) makes me wanna uninstall it and look for alternatives. 

I'm not a web developer, that's why I went with a WordPress blog, I only wanted to have a website up quickly, and focus instead on creating content for it.

Also checked https://github.com/google/site-kit-wp/issues/2087. I don't really understand if this API is meant for us, users of the SiteKit plugin, or if this API is even available at all.

It's probably safe to assume a lot of people install SiteKit and enable Google Analytics, then install a consent popup plugin, and then they think their site is now GDPR compliant, **meanwhile the consent popup is not hooked up to anything**, it doesn't block any analytics scripts or cookies. You can clearly see the network traffic in Chrome Developer Tools. I doubt many WordPress site owners even know how to **check if the consent popup they installed actually works**. 

I hope people in charge of this plugin can see why this is very problematic... people think they are in legality when actually they are not.

**Comment by AertHulsebos** [comment]
Hi @radusalagean the proposal exists, as can be read above.

https://github.com/google/site-kit-wp/issues/462#issuecomment-676511017

We (Complianz.io) have a direct integration and built the API, but would rather move our consent efforts toward a universal approach for any plugin that might need consent levels. I'm pretty sure between @rlankhorst & @felixarntz we can implement this rather quickly. Then any consent plugin is welcome to conform, now both Complianz & Cookiebot use the API already.

Just an FYI :-)

regards Aert

**Comment by over-engineer** [comment]
>I spent the last couple of days trying to get SiteKit Google Analytics integrated with a consent popup on my WordPress site.

@radusalagean Hey! Just out of curiosity, which consent popup were you trying to integrate with SiteKit Google Analytics?

**Comment by radusalagean** [comment]
>
> [#462 (comment)](https://github.com/google/site-kit-wp/issues/462#issuecomment-676511017)
>

@AertHulsebos Thanks, I will have a look.

>
> @radusalagean Hey! Just out of curiosity, which consent popup were you trying to integrate with SiteKit Google Analytics?
>

Hey! I tried both https://wordpress.org/plugins/cookie-law-info/ (free version of the plugin) and https://www.cookieyes.com/cookieyes-code-installation-on-wordpress/ (which is not a plugin, but they give you a script which I included in the `head`). 

The popups appeared correctly, but neither were blocking the analytics. Looks like the plugin one has integration with MonsterInsights plugin and it claims to work out of the box. I haven't tried it yet, but I will later and if it works, I'll probably use that from now on.

**Comment by srodrigo** [comment]
The only plugin I found that *hopefully* works with Site Kit is Complianz.

It'd be cool to finish proper support so other plugins can integrate, as otherwise Site Kit is not viable at all.

**Comment by adamdunnage** [comment]
@srodrigo We are in the process of updating our [GDPR compliance and privacy documentation](GDPR compliance and privacy) which will include some further third party plugin recommendations. Some of these work natively with Site Kit by providing plugin-specific configurations. Some of the more popular plugins include:

**[Cookieyes](https://wordpress.org/plugins/cookie-law-info/):**
- provides an option to switch on google consent mode from the web app
- see this guide on how to enable google consent mode for cookieyes

**[Complianz gdpr/ccpa cookie consent](https://en-gb.wordpress.org/plugins/complianz-gdpr/):**
- provides a consent management option for site kit-placed analytics snippet
- see this guide for more information

**[gdpr cookie compliance (ccpa, dsgvo, cookie consent)](https://wordpress.org/plugins/gdpr-cookie-compliance/):**
- supports both the google tag manager & google analytics consent variables natively. See here for more information.
- Google site kit integration options are included as part of a premium add-on

**[cookiebot | gdpr/ccpa compliant cookie consent and control](https://wordpress.org/plugins/cookiebot/):**
- provides a consent management option via google consent mode. See here for more information on cookiebots google consent mode.
- For further options to block scripts and check cookie types, go to plugins > available add-ons

Hope this helps and do keep an eye out for the updated documentation which will be coming soon.

**Comment by srodrigo** [comment]
@adamdunnage thanks for the update. That's absolutely brilliant!!! Do you have any idea of the ETA for the documentation update?

**Comment by adamdunnage** [comment]
@srodrigo You are very welcome. I would expect this in the next few weeks but I cannot provide a concrete date unfortunately.

**Comment by srodrigo** [comment]
@adamdunnage thanks! No problem. Not a commitment, just to have a brief idea. A few weeks sounds great :)

**Comment by jamesozzie** [comment]
Now that we have a [guide related to GDPR](https://sitekit.withgoogle.com/documentation/using-site-kit/gdpr-compliance-and-privacy/) I'll close this GitHub issue. 

We also have [consent mode added to Site Kit](https://sitekit.withgoogle.com/documentation/using-site-kit/consent-mode/), with some suggestions on consent management plugins added to that guide. These are plugins that are known to work with consent mode within Site Kit. These do have opt in/opt out configurations as per this feature request.
