### ISSUE TITLE
Disable CSS animations in VRT

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4623]
## Feature Description

Backstop JS runs are sometimes failing due to what seems to be a race condition with CSS animation (e.g. hovering a button). Since CSS animations aren't relevant in VRT, we should disable them to avoid the potential for such conflicts.

We already do this in E2E tests using a plugin borrowed from Gutenberg, but it's essentially a single line of CSS added to the page to override all animation durations.
https://github.com/google/site-kit-wp/blob/d6f2a0e503d3c6779cc02e9918e95471c22f18d1/tests/e2e/mu-plugins/e2e-disable-animations.php#L8

We should add this in VRT as well, but _only during VRT runs_, not Storybook as a whole.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* CSS animations and transitions should be disabled for VRT runs

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/4624

### Test Coverage

* N/A

## QA Brief

* Run storybook normally, ensure CSS animations work as usual
	* This can be checked on a button, progress bar, etc
* Run `npm run pretest:visualtest` to build storybook for VRT, then open `dist/index.html` to open the static storybook
	* Ensure the same CSS animations are disabled, that is they should appear "stuck" at the end of the animation

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by techanvil** [comment]
## QA: :white_check_mark:

* Ran Storybook normally and verified CSS animations work as usual.
* Built VRT Storybook via `npm run pretest:visualtest` and verified CSS animations are disabled.
