### ISSUE TITLE
Unable to Create new Analytics account in specific scenario

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4625]
## Bug Description

Odd behaviour when you try and create a new Google Analytics account on a site that previously had Analytics set up with another account.  When you create a new account you are sent into a loop, and are unable to get to the 
Google Analytics Terms of Service Agreement page. 

This only applies when you disconnect Analytics and then at a later try and create a new account on the same site. When you edit the Analytics settings and select to  create a new account this works as expected. 

Here's a screencast:

https://user-images.githubusercontent.com/73545194/148531910-7fed9c4c-b0fa-4557-b83f-9c8f6928c017.mp4

This isn't a regression because I was able to recreate the issue on latest version.

## Steps to reproduce

1. Set up Site Kit on a site and connect Google Analytics with a current account and UA/GA4 property.
2. Once connected, edit Analytics settings and disconnect the service
3. Go to the 'Connect More Services' tab within settings
4. Set up Google Analytics again, but this time, create a new account.
5. Go through the oAuth process after clicking on create account button.
6. See issue.  You will go in a continuous loop. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren that's odd. Can you confirm that this is still reproducible?

**Comment by wpdarren** [comment]
@aaemnnosttv spent some time looking and cannot recreate this now. Will keep an eye open for it incase the issue appears again. For now, we can close this ticket.
