### ISSUE TITLE
Remove AdSense functionality related to tag permission checks 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4627]
## Feature Description

The functionality around existing tag checks for AdSense is being simplified along with other modules. Compared to the other modules, the behavior for AdSense is the simplest regarding existing tags.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following selectors and related AdSense data store infrastructure (fixtures, tests, etc) should be removed:
	- `hasExistingTagPermission`
	- `hasTagPermission`
	- `getTagPermission`. 
	_Essentially everything not provided by `createExistingTagStore`_
* All use of `hasExistingTagPermission` in AdSense components should be replaced with a simple check whether the client ID from an existing tag matches the selected client ID
* The AdSense `GET:tag-permission` datapoint should be removed entirely (including the `has_access_to_client` method only used there)

**The PR for this issue should target the [`feature/existing-tag-simplification`](https://github.com/google/site-kit-wp/tree/feature/existing-tag-simplification) branch**

## Implementation Brief

In `assets/js/modules/adsense/datastore/tags.js`:
* Rename `existingTagStore` to `store` and export it .
* Remove the `combineStore` and everything else related to it such as `fetchGetTagPermissionStore`, `baseSelectors`, `baseResolvers` etc.
* Remove all the unused imports and variables. 

In `assets/js/modules/adsense/datastore/tags.test.js`:
* Remove tests for `hasExistingTagPermission`, `hasTagPermission` and `getTagPermission`.
* Remove unused imports and variables. 

In `assets/js/modules/adsense/datastore/__fixtures__`.
* Delete the folder and everything in it. 

In `Google\Site_Kit\Modules\AdSense` class:
* Remove `GET:tag-permission` from the `get_datapoint_definitions` and `create_data_request`.
* Remove the `has_access_to_client` protected function from the class. 
* Remove tests for `GET:tag-permission` from `AdSenseTest`.

In `assets/js/modules/adsense/components/setup/SetupAccountApproved.js`:
* Get the current `clientID` using the `getClientID` selector of `MODULES_ADSENSE` store. 
* For `hasExistingTagPermission`, remove the usage of `hasExistingTagPermission` selector. Use simple check to see if `existingTag === clientID`.

### Test Coverage

* Fix any broken tests. 

## QA Brief
* Check if tests pass.
* Check the AdSense setup flow if anything is broken.

## Changelog entry

* Remove functionality related to checking for existing AdSense tag permission.

**Comment by felixarntz** [comment]
ACs LGTM 👍

**Comment by tofumatt** [comment]
Works for me! I guess for now it makes sense to leave the check inline, so IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvinb @kuasha420 we need more information on the QAB here.  Please could you give more detail to the tests you want us to do.  The AC/IB is quite technical so needs more information for QA to pass this. cc @mohitwp @eclarke1

**Comment by mohitwp** [comment]
### QA Update ✅ 

> Verified Ad sense functionality with existing tag simplification
> Adsense flow working as expected.
> Verified when analytics and tag manager module not active.
> Verified after adding GTA module manually through header.php
> Verified after adding GA analytics module manually through header.php
