### ISSUE TITLE
TypeError: Cannot read properties of undefined on Dashboard with AdSense connected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4642]
## Bug Description

There's an error appearing when you select a date period, i.e 7 days on the dashboard.   The error is: `TypeError: Cannot read properties of undefined (reading 'headers') at DashboardSummaryWidget (googlesitekit-modules-adsense-afcb238cbbb8f1246e96.js:81:7294)`

![error.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/b6132fdf-bde7-427c-a7af-057ede4f63de)

A few things to highlight: 

1. This appears on the develop and main branch, when you have AdSense connected. I tested it with only Analytics and the error did not occur. 
2. The error only appears when you change the date period after Page Speed Insights widget has loaded.  If you change it as it's loading, no errors occur. 
3. The issue appears only on the dashboard (both current and unified dashboard) and not the module pages. 

Note: I tested this with tester plugin with AdSense account status as approved. This was for a fresh new site and also a site connected to oi.ie with developer plugin. 

## Steps to reproduce

1. Connect Site Kit with AdSense.
2. Go to the Dashboard and change the date period to 7 days. 
3. See the error. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No errors should be raised by changing the date range

## Implementation Brief

<details>
<summary>Explanation</summary>

The problem here happens when the AdSense `DashboardSummaryWidget` is loaded (i.e. comes into view) for any date range, and then the date range is changed while the component is no longer in view.

The selectors for `period` and other values become `undefined` due to the `useInViewSelect` reset but the component doesn't trigger a `loading` state because the selector didn't trigger a resolver as it has been "suspended".

This problem is manifesting here but isn't specific to this component and could easily happen in others where we rely on `hasFinishedResolution` to determine the loading state, although in this case, the report selectors don't rely on the date range. This results in the `getReport` selector returning `undefined` while also not resulting in an `loading` (resolving selector) state.

![image](https://user-images.githubusercontent.com/1621608/149322860-b75e2cf6-32d9-4838-92c2-b6c41c805c31.png)

Rather than always _returning_ `undefined` when the `inView` state is false, the selector should continue to return the previous in-view selected state, until it is in view again, at which point it can call the real selector again. 

Note that this is important because `useSelect` will trigger a re-render on every update of the store it selects from.

</details>

* Update `useInViewSelect` to store and return the last selected value when it was in view until it is inView again

### Test Coverage

* Update tests for `useInViewSelect`
* Finish and merge #4650

## QA Brief

1. Connect Site Kit with AdSense.
2. Go to the Dashboard and change the date period to 7 days. 
3. No error should appear. 

Additionally,

1. Load the SK dashboard with AdSense setup
1. View the AdSense widgets and allow them to fully load
1. Scroll back to the top so that the widgets are fully out of view
1. Change the date range
1. Ensure no error appears

## Changelog entry

* Fix potential off-screen widget rendering error when using `useInViewSelect`.

**Comment by tofumatt** [comment]
IB ✅ 

I think this makes the most sense, but it arguably leads to some weirdness where stale/incorrect data is on the page. I guess this is the _fastest_/easiest fix, but won't it lead to a very quick flash of content -> loading when the "stale" view is scrolled into view?

Anyway, it's better than the current bug, so I'm fine with it… at least for now 😅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When I go to the Dashboard and change the date period to 7 days, no error appears.
- When I view the AdSense widgets and allow them to fully load, and I scroll back to the top so that the widgets are fully out of view. I then change the date range and no error appears. 
- Tested this with Unified Dashboard enabled and disabled.
