### ISSUE TITLE
Update 'View draft' button in Idea Hub with an icon

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4651]
## Feature Description

Within the Idea Hub 'Drafts' tab on the dashboard, there's a button that states 'View draft' taking the user to the draft posts page in WordPress. Other tabs of the Idea Hub module feature icons, as opposed to hyperlinked text. This issue aims to replace the 'View draft' hyperlinked text with an icon similar to those used on the 'new' and 'Saved' tabs.

Figma design: https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=21614%3A4154 (Currently WIP)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This was done in https://github.com/google/site-kit-wp/issues/4266 and released in 1.70.0 😊
