### ISSUE TITLE
Module setup UI can be accessed even when module is not active

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4654]
## Bug Description

It is currently possible to land on a module setup UI by entering the respective URL, even if that module is not active. This is an edge-case, but can lead to other bugs and confusing user experience, and therefore it should be fixed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A server-side check should be added to prevent the module setup screens (requires checking the `slug` parameter etc.) from being accessed if the respective module is not active. If the module is not active, the process should `wp_die` with a 403 error `The %s module cannot be set up as it has not been activated yet.`, with the placeholder being used for the module name.
    * It should be ensured that this check fires after the (higher-priority) permission check from the screen itself.

## Implementation Brief
* Using `includes/Core/Admin/Screens.php`,
	* Update the code within the `render_callback` function for the `dashboard` screen to check for the following if `setup_module_slug` is not `null`.
		* Get the list of active modules via the `get_active_modules` method of `$this->modules`
		* Check if array contains the module slug (`$setup_module_slug`) as key.
		* If the array does not contain the module slug as key, render the message as per the AC.

### Test Coverage
* Update `tests/phpunit/integration/Core/Admin/ScreensTest.php` to test for the above changes.

## QA Brief
* Access the setup URL for a non activated module. For e.g `/wp-admin/admin.php?page=googlesitekit-dashboard&slug=analytics&reAuth=true` where `analytics` is the module slug which has not been activated yet.
* An error as per the AC should be displayed.
* Additionally, use an invalid slug in the URL above and another error message will be displayed saying it's an invalid slug. For e.g `/wp-admin/admin.php?page=googlesitekit-dashboard&slug=foo-bar&reAuth=true`

## Changelog entry

* Show error message when landing on module setup URL when the module is not active, or for an invalid module.

**Comment by tofumatt** [comment]
IB ✅

**Comment by marrrmarrr** [comment]
Generally would be nice if we gave them a next step (e.g. go to Settings / Connect more services, but within the scope of this issue things are working as expected.
