### ISSUE TITLE
Headless Wordpress

### ISSUE THREAD

**Issue by Bowriverstudio** [google/site-kit-wp#4657]
Hello

I've got a Wordpress site at admin.example.com and a frontend at example.com

I would like to install site-kit-wp on admin.example.com but display the results at example.com.  

Is there a filter or something I modify to achieve this?

Thanks

**Comment by jamesozzie** [comment]
Hi there @Bowriverstudio,

A headless setup such as your own isn't supported at this time, with no filters for this purpose. You'll find more information on this by visiting [a related GitHub issue](https://github.com/google/site-kit-wp/issues/1347#issuecomment-616767303).

There is also an open GitHub issue which you may wish to subscribe. This is in relation to exploring other options that would cater for headless setups similar to your own. Feel free to chime in with any input to this issue below:
https://github.com/google/site-kit-wp/issues/37#issuecomment-815074629

Note also that there is support for displaying data from one site (ie. example.com) on a separate domain (ie. staging.example.com) however these would have to be different WordPress installs. We have more information [on the plugin website](https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/). 

Let me know if you have any questions with the above. I'll close this in the meantime as we already have #37 open.
