### ISSUE TITLE
Unique Visitors from Search Data is Incorrect on Entity Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4658]
## Bug Description

With Unified Dashboard disabled, the Unique Visitors from Search data on Entity dashboard is incorrect. For an individual page/post it should display the data for that URL but it is displaying the site data.   This issue does not arise when Unified Dashboard is enabled.

<details>
 <summary>Screenshot showing on latest release: `3 Unique Visitors from Search`</summary>

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/d9b75e32-f298-492b-9ca0-c8a571f0939f)

</details>

<details>
 <summary>Screenshot showing on main branch: `309 Unique Visitors from Search`
</summary>

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/3011b83f-2264-45b5-81b0-32cd8e9672a0)

</details>

I've been able to recreate this on another live site (oi.ie) 

This appears to be a regression from 1.49.0. 

## Steps to reproduce

1. Connect Site Kit with Analytics.
2. Make sure Unified Dashboard is disabled
3. Go to the Entity dashboard for a specific page/URL
4. Look at the Unique Visitors from Search data. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Nice catch @wpdarren! Since this was caused in another issue for the release, I'm going to close this in favor of addressing it in the original issue (#4361) 👍
