### ISSUE TITLE
Create link to dashboard on welcome screen (After reactivating plugin)

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#466]
## Feature Description

On the welcome screen after reactivating Site Kit there is useful welcome page for users. At present all inks on that welcome page are external, there is no link for further setup. 

There are references to "visiting the dashboard" but no link to that tab. It's also a tab that's only visible once the Site Kit tab is hovered over (see screenshot). 

- Less confusion / Users can easily navigate to the dashboard

![download](https://user-images.githubusercontent.com/41326532/63763599-f4eb9f00-c8bc-11e9-89cc-8ea12cb9c620.png)

![zT6ufme6h4](https://user-images.githubusercontent.com/41326532/63764233-447e9a80-c8be-11e9-8431-1b0e20ab6ab9.gif)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This screen is no longer used and has been removed, i.e. this is no longer relevant.
