### ISSUE TITLE
Problems with "Unique Visitors from Search" part of new "Search Funnel widget"

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4660]
## Bug Description

While testing the 1.49.0 release, we came across two bugs with the "Unique Visitors from Search" part of the new "Search Funnel widget" that were most likely unrelated to the changes in the release, but need to be fixed before launch.

1. On a site with 0 (Analytics) data, a JS error `u.slice is not a function` can occur once you click on that tab.
2. On a site with a low number of unique visitors, no graph was displayed below. Possibly this is due to the Analytics API truly not returning anything for privacy reasons, but we should verify that the logic and the API request we send there is correct.

The below screenshots show the two bugs:
<img width="1630" alt="Screen Shot 2022-01-14 at 12 28 08 PM" src="https://user-images.githubusercontent.com/3531426/149511099-c5f65ce3-4360-4e63-8f1a-5ddc825ce069.png">

<img width="1600" alt="Screen Shot 2022-01-14 at 12 50 08 PM" src="https://user-images.githubusercontent.com/3531426/149511113-e7c3b9d0-f44b-4a2f-bf95-eaf2fcc1ad18.png">

While this is a critical bug (especially the first one), this doesn't need to be fixed before the upcoming release since it only surfaces behind the `unifiedDashboard` feature flag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should not be a JS error when clicking the "Unique Visitors from Search" tab in the new "Search Funnel" widget.
* There should always be a graph for the "Unique Visitors from Search" tab in the new "Search Funnel" widget (even in the case of 0, it should be a straight line like it's in the similar Search Console charts).

## Implementation Brief

- In `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js`:
    - Delete `ga:channelGrouping` from the `dimensions` array which is making an extra request that causes the API to respond with no `rows` in the `data` object. 
    See:
    https://github.com/google/site-kit-wp/blob/f2e3f19c9e7d2b3d0ac48f2558d99514a487c352/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js#L138-L141
    - In fact, we don't need the `analyticsVisitorsStatsArgs` variable (object)
    - Update the `analyticsVisitorsOverviewArgs` object's `dimensions` to have _**ONLY**_ `ga:date` element
    - Update the selectors and others to use `analyticsVisitorsOverviewArgs` instead of `analyticsVisitorsStatsArgs`

- In `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/AnalyticsStats.js`:
    - Update the `googleChartData` variable to have a fallback value of an empty array something like this:
    ```javascript
     const googleChartData = extractAnalyticsDashboardData( ... ) || [];
    ```
    This is to avoid displaying the JS error `u.slice is not a function` to the user in any case the `rows` aren't available from the API response. 
    **Note:** This error will not happen by when we remove `ga:channelGrouping` from the `dimensions`. However, it's better to have a fallback value.
    
    

### Test Coverage

- N/A

## QA Brief

- [x] Go to Site Kit dashboard's Search Funnel Widget
- [x] Make sure your site's Analytics `Unique Visitors from Search` data is `0`
- [x] Click on `Unique Visitors from Search` section
- [x] Verify the error described in  AC is not displayed
- [x] Verify the graph is displayed for `0` data with a horizontal line
- [x] Make sure `Unique Visitors from Search` data is less than the selected date (from the date range selector dropdown). (This is to verify it works for the less data as well)
- [x] Verify the similar behaviour as `0` data in the graph

## Changelog entry

* Fix a javascript error on the Analytics Unique Visitors tab of the Search Funnel widget.

**Comment by felixarntz** [comment]
@eclarke1 @FlicHollis Since this needs to be fixed before launch, I'll move it to the upcoming sprint 67.

**Comment by FlicHollis** [comment]
No problem, thanks @felixarntz

**Comment by hussain-t** [comment]
@felixarntz @asvinb I had a discussion with @aaemnnosttv regarding this issue. Evan pointed out that `ga:channelGrouping` from the `dimensions` array is causing the issue. This makes an extra request and the API response doesn’t have the `rows` array. However, it isn’t necessary for making the API call for `Unique Visitors from Search`. Do you think it was added by mistake? What are your thoughts? Thanks!

https://github.com/google/site-kit-wp/blob/f2e3f19c9e7d2b3d0ac48f2558d99514a487c352/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js#L138-L141

**Comment by felixarntz** [comment]
@hussain-t Hmm yes, looking at that code, I think the `ga:channelGrouping` dimension shouldn't be there. It's only relevant as a dimension _filter_, not a dimension.

**Comment by aaemnnosttv** [comment]
@hussain-t would you please add an estimate?

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- There is no JS error when clicking the "Unique Visitors from Search" tab in the new "Search Funnel" widget on the main and entity dashboard. All date periods were selected: 7, 14, 28 and 90 days. 
- There is always be a graph for the "Unique Visitors from Search" tab in the new "Search Funnel" widget on the main and entity dashboard.  I checked this on a site with zero data and also one with a small amount of search data. 
- As an extra confidence check, I disabled unified dashboard and made sure that the "Unique Visitors from Search" data on current dashboard (and page dashboard) was displaying with no issues or JS errors. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/151204783-709385da-21c0-4abf-81c6-5ec6641d7b3c.png)

![image](https://user-images.githubusercontent.com/73545194/151204816-3921bb1a-bf4b-4382-b94e-df43e81b025a.png)

</details>
