### ISSUE TITLE
Hover over Behaviour on an Active chip within the Tab Bar for Unified Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4664]
## Bug Description

When you visit the Unified dashboard, by default the 'traffic' chip is highlighted in the tab bar and the URL has the #traffic hash added to the URL. When you hover over the 'traffic' chip, the mouse cursor and hover style, makes it appear that you can select it. Of course, when you do nothing happens, but it's a weird UX/UI in my opinion.

Is there anything we can do to improve this? Maybe for an active chip, the hover over behaviour is removed?  This was brought up when QAing #4488 and it was identified as out of scope.

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/9638bfde-2442-4498-ae9b-9ad10e5063be)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren I don't think we need to go out of our way to disable an active chip as it _does_ still have behavior. If the chip is active and you scroll some, if you click it again, you'll be scrolled back to the top of the section which is useful. You could say maybe it should be disabled if the chip is active _and_ the scroll position is exactly at the top of the area, but I don't think that is particularly beneficial. It's better to keep the behavior consistent unless there is a good reason not to.

**Comment by wpdarren** [comment]
@aaemnnosttv I am happy to go with what you think is best, but I still feel it's weird behaviour and wondering if it would be worth running it by UX?

**Comment by aaemnnosttv** [comment]
I don't think it's really a problem but open to being convinced otherwise. Thoughts @felixarntz @tofumatt ?

**Comment by felixarntz** [comment]
@aaemnnosttv @wpdarren I also see this behavior as expected. It may also have accessibility implications, but yeah I think we should consult with UX also. cc @samitron7 @Pratheep-lab What is your take on this behavior?

**Comment by Pratheep-lab** [comment]
@wpdarren I get it that it might feel odd for some users to be able to click and nothing happens. But I believe when nothing happens, some users will infer that they are already in that section. This is the UI pattern and it is used in the same way in other websites including Google's. ([Material design right side section menu example)](https://material.io/design/introduction#principles)

Ideally, I am with you to remove the mouse hover when the respective section is exactly on the top of the screen. If the section even moves a pixel, we need to enable the mouse hover option. I'm not sure if this is worth the effort. 

And for that reason we can leave it as it is, in my opinion. 

@samitron7 @felixarntz Thoughts?

**Comment by Pratheep-lab** [comment]
@wpdarren On a related note, potentially another issue: 

The mouse clicked state, ie the grey colored box showing up on the 'Content' chip should disappear once the mouse moved away from the chip. Otherwise you see this weird use case (Screenshot below) when the users scrolls, the content chip is in grey and the following chip 'Speed' goes to blue active state.  

![image](https://user-images.githubusercontent.com/81642523/152241446-1e400432-c742-4337-95e7-fb0b0328fc17.png)

This will confuse the users! 

CC: @felixarntz

**Comment by wpdarren** [comment]
@Pratheep-lab  I am fine with that, just wanted a UX opinion on the issue. 

> On a related note, potentially another issue: The mouse clicked state, ie the grey colored box showing up on the 'Content' chip should disappear once the mouse moved away from the chip. Otherwise you see this weird use case (Screenshot below) when the users scrolls, the content chip is in grey and the following chip 'Speed' goes to blue active state.

Yes, I have mentioned this once or twice before and was told it was not possible with how we've implemented the tab bar and chips.  I would like @felixarntz opinion on this though because I agree it's an odd experience. The only way you can remove the grey coloured box is if you click somewhere on the page.

**Comment by aaemnnosttv** [comment]
> The mouse clicked state, ie the grey colored box showing up on the 'Content' chip should disappear once the mouse moved away from the chip. Otherwise you see this weird use case (Screenshot below) when the users scrolls, the content chip is in grey and the following chip 'Speed' goes to blue active state.

@Pratheep-lab the gray color is the focus state of the chip which both independent from the active/selected chip and isn't mouse-specific. This is important for keyboard navigation and is part of the default behavior of the chip component, so it's intentional 🙂
