### ISSUE TITLE
Not a Valid JSON response when searching for a post or page

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4665]
## Bug Description

This issue has arisen from testing `URL search` on Unified Dashboard, but this is also an issue with the `Search for individual page or post information` on the current dashboard.  When you type in a search term, the message 'No results found' appears along with an error message in the console. 

`react_devtools_backend.js:4045 Google Site Kit API Error method:GET datapoint:post-search type:core identifier:search error:"The response is not a valid JSON response."`

Around 5-10 seconds later the results appear in the dropdown. 

https://user-images.githubusercontent.com/73545194/149775098-77630018-de6b-468a-a9b4-800e05431015.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a `siteKitRequest` is canceled (currently only used with the `post-search` endpoint), the error raised should not be treated as a normal error in that it should bypass all of the existing error handling, the most observable of which is the logging in the console
* The "No results found" message should not be shown while there is a request in progress
   * That is, the loading state should be preserved until the most recent fetch has finished

## Implementation Brief

* Merge #4669

### Test Coverage

* Update tests for `siteKitRequest`

## QA Brief

* Using the post search field on the dashboard, type into the input in varying speeds
* No console errors should be logged when an in progress fetch is canceled
* The loading state should be preserved until typing has stopped and the last request has completed

## Changelog entry

* Improve post search autocomplete behaviour when typing during autocomplete API requests.

**Comment by wpdarren** [comment]
@aaemnnosttv  I have created a screencast with the network data as per Slack. 

https://user-images.githubusercontent.com/73545194/149892654-2bfb2086-2ad0-4f25-9f57-64b118ac354e.mp4

This is a screenshot of Console errors too.  

`react_devtools_backend.js:4045 Google Site Kit API Error method:GET datapoint:post-search type:core identifier:search error:"You are probably offline."`

![image](https://user-images.githubusercontent.com/73545194/149892849-89b53198-2df9-4967-ac4c-4720a84ecdb6.png)

It's looking like my site is the issue because when I create a new site, and use the developer plugin to connect to the URL, the issue doesn't arise. That said, my content, theme and plugins are not on the new site.  If it's easier, I can give you admin access to the site and assign you to search console so you can try and recreate. Let me know and I can sort that.

**Comment by aaemnnosttv** [comment]
@wpdarren that looks like the expected behavior, although one probably won't see it unless the request takes longer than a certain amount of time which seems to be what you're seeing.

We recently updated the post search to cancel a previous request when the input changes which results in a "failed request" but this is expected/intentional.

So this is fine, but I think we can change this so that it doesn't show up as an error in the console 👍

**Comment by wpdarren** [comment]
@aaemnnosttv from a UX perspective I don't think it is good. I understand why we're seeing the canceled data in network, but why does the `no results found` appear when you're still typing? That's confusing in my opinion. I wouldn't expect that to appear until I have stopped typing.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_Tested this on the URL search with Unified Dashboard and the current post/page search on current dashboard._

- No console errors are logged when an in progress fetch is canceled.
- The loading state is preserved until typing has stopped and the last request has completed.

https://user-images.githubusercontent.com/73545194/150507681-9003abeb-16cf-43a3-8314-887a2c646f4a.mp4
