### ISSUE TITLE
Add a hasZeroData selector for Analytics

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4673]
## Feature Description

For the new Zero States features to be properly implemented, we need a way to explicitly check if a module has "zero data" as opposed to "gathering data". Obviously any site that's gathering data will also have "zero data", but we can use logic tailored to each "module" (eg Google Service) that Site Kit uses to check if there's no data available from the Google API because the site is new or if there's data because there's been nothing of note.

Essentially, we want to be able to tell the difference in Analytics: "Do I have no data in my Analytics report because my site is very new/my Analytics account is very new or is there is no data because my site is not popular/has received no visits?"

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `hasZeroData()` selector for the Analytics module's datastore that checks to see if there is no data for Analytics despite `isGatheringData()` returning `false`.
* This selector should `return false` if any data is found. The selector should `return true` if no data for a "representative" Analytics request—likely whatever the default dashboard request would be (eg. 28 days)—is found but `isGatheringData() === false`.

## Implementation Brief

- In `assets/js/modules/analytics/datastore/report.js`:
    - Add a new selector `hasZeroData` that checks for zero data state as described in the AC
    - The `hasZeroData` selector will have the following logic:
        - Get the report data from `select( MODULES_ANALYTICS ).getReport( args )` selector:
        - Reuse the logic for getting the `args` to pass to `getReport( args )`  from `isGatheringData`, see:
        https://github.com/google/site-kit-wp/blob/27b8e040ec85ab9fb94efebebf44defc544a26d3/assets/js/modules/analytics/datastore/report.js#L296-L315
        - Return `undefined` if the `report` data is `undefined`
        - Get the gathering data state from the `isGatheringData()` selector
        - Get whether the report data has zero state or not, by using the `isZeroReport( report )` helper function from `assets/js/modules/analytics/util/is-zero-report.js`
        - Return `undefined` if either `isGatheringData() === undefined || getReport() === undefined`
        - Return `false` if `isGatheringData() === false && isZeroReport() === false`
        - Return `true` otherwise (essentially, if `isGatheringData() === true || isZeroReport() === true`). Note, this can be the default return value, to ensure we always return from the function

### Test Coverage

- Add test cases for the `hasZeroData` selector

## QA Brief

**QA:Eng**
- Verify the changes met AC and IB
- Run the newly added tests for `hasZeroData` from `assets/js/modules/analytics/datastore/report.test.js`
- As an extra verification, could call the `hasZeroData` selector from `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js` component to check what `hasZeroData` returns
- For the above, verify if the report data is available, it should return `false` otherwise `true`

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Looks good to me; essentially the same approach as in Search Console, which makes sense.

IB ✅

**Comment by jimmymadon** [comment]
### QA: Eng ❗ 

> * Verify the changes meet AC and IB.  

The changes do meet the IB - however, I wanted to clarify the following line within the IB @tofumatt: 
> Return true otherwise (essentially, if isGatheringData() === true || isZeroReport() === true).
 
In my understanding of the [design doc](https://docs.google.com/document/d/1gRBpyGYA0IEE0wVw1cA__lG23xZCmAo68RS8SNGYRto/edit#heading=h.watrt4vcnnna), would it make more sense to keep it `undefined`? I.e., shouldn't `hasZeroData()` return true if **AND ONLY IF** `isGatheringData()` is false AND `isZeroReport()` is true. This would properly distinguish the state of "Gathering Data" and "Zero Data".

> * Run the newly added tests for `hasZeroData` from `assets/js/modules/analytics/datastore/report.test.js`

✅ All tests pass.
![Screenshot 2022-02-21 at 20 00 48](https://user-images.githubusercontent.com/1721319/155025348-ade0b61a-cc77-4e26-9c07-a5b010b0d7ec.png)

> * As an extra verification, could call the `hasZeroData` selector from `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js` component to check what `hasZeroData` returns
> * For the above, verify if the report data is available, it should return `false` otherwise `true`

✅ Tested each scenario in the `SearchFunnelWidget/index.js` component:
<img width="427" alt="Screenshot 2022-02-21 at 20 37 25" src="https://user-images.githubusercontent.com/1721319/155025297-cd0a742c-ebb3-43e9-bd5a-36d0f0269fd1.png">
<img width="417" alt="Screenshot 2022-02-21 at 20 33 51" src="https://user-images.githubusercontent.com/1721319/155025316-31b976a0-eb5e-4549-9154-3702a5415d6f.png">

**Comment by tofumatt** [comment]
@jimmymadon I'm not sure if we've _really_ explicitly codified that anyplace, but it's tough for me because _technically_ `hasZeroData` is true when gathering data or a zero report. Conceptually/logically I'd expect the "has zero data" selector to return `true` in either case. It's for the UI to prioritise which case we show first, so the trick to ensuring we present the right data for the user is checking for `isGatheringData` before `hasZeroData`.

I think this makes sense for the developer as well… "gathering data" strikes me, anyway, as a state that is more "early" than "has data but it's all zero". But technically: but have zero data. The conditionals to render the UI/present this information should be where that logic is contained, I think.

Unless there's another issue that behaves differently than this, but I think no because it's basically the same logic as the Search Console widget so I think this makes sense.

Does that seem okay @jimmymadon? Or are there edge cases that won't cover? Or some sort of oddity here I missed?

Or does it just not make sense and you think it'd be clearer if these two selectors were mutually exclusive?

**Comment by jimmymadon** [comment]
@tofumatt 

> Conceptually/logically I'd expect the "has zero data" selector to return true in either case.

This is fine for me - I think both ways make sense 😄  `gatheringData` does mean there is no data yet and if we assume no data = zero data, then your logic checks out. I originally understood that `gatheringData` should not simply imply `hasZeroData`, if you treat "zero data" as more of a value, rather than simply null/no data. So just thought it was worth flagging.

> It's for the UI to prioritise which case we show first, so the trick to ensuring we present the right data for the user is checking for `isGatheringData` before `hasZeroData`

True, depending on how these are defined, the UI can be adapted easily either way. If we have proceeded like this for the Search Console widget, then it is better to be consistent. 

So...

## QA:Eng ✅
