### ISSUE TITLE
GA4 issues when connecting Analytics, unable to select or place snippet. 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4677]
## Bug Description

There seem to be multiple connected issues during GA4 property selection and also with viewing the existing property, as [highlighted by one user in the forums](https://wordpress.org/support/topic/ga4-settings-disappear/). This is reproducible in support, with the plugin not handling GA4 properties as it did before. 

**The main issue is new users are unable to select or place a GA4 property snippet using Site Kit.** 

A summary of issue findings including the below, occur on all test sites at present (3 tested so far):
- If selecting a GA4 property initially after selecting an account that has an existing GA4 property the screen reloads to only display the UA properties ([video](https://recordit.co/JnSqJ4xUIe))
- If an existing non SK placed GA4 snippet exists users are permitted to select a different GA4 property
- In both cases above when revisiting the GA4 settings overview there are no GA4 reference ([screenshot](https://i.imgur.com/JtwKywZ.png))
- When editing the Analytics settings there is a greyed out GA4 property box ([screenshot](https://i.imgur.com/X0smh04.png))
-  Despite granting all GA4 permissions previously users are asked to grant further permissions each time. 

![2022-01-19-11-10-25](https://user-images.githubusercontent.com/41326532/150118825-4d0738db-28f1-44cf-a67f-4c8cd021bea8.gif)

**Console Errors with the greyed out GA4 box when revisiting (_see screenshot of these errors further down_)**

```
Error handling response: TypeError: self.processResponse is not a function
    at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10
/wp-json/google-site-kit/v1/modules/analytics-4/data/webdatastreams-batch?propertyIDs%5B0%5D=279129939&_locale=user:1 Failed to load resource: the server responded with a status of 500 ()
googlesitekit-api-26ce8eaec5dba8b68ca9.js:1 Google Site Kit API Error method:GET datapoint:webdatastreams-batch type:modules identifier:analytics-4 error:"<p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p>"
(anonymous) @ googlesitekit-api-26ce8eaec5dba8b68ca9.js:1
```

**Video 1: Exhibiting GA4 issues during setup: [Video](https://recordit.co/GVeSITKkqU)**
- A new burner site is setup
- SK is setup
- During Analytics setup with a GA account that has a UA and GA4 property for selection once the GA4 property is selected it reloads, only to show a UA property
- There us no GA4 property

**Video 2: Experience with an existing GA4 snippet: [Video](https://recordit.co/xAN1Uoz49j):**
- Site Kit recognizing a manually inserted GA4 snippet, prior to connecting the Analytics module
- The plugin allows a user to continue to select a different snippet if they wish
- When checking the Analytics settings within SK there is no GA4 information output ([screenshot](https://i.imgur.com/JtwKywZ.png))
- When editing the Analytics settings there is a strangle formatted greyed out GA4 select box, that doesn't display the previously connected GA4 snippet, which was manually placed ([screenshot](https://i.imgur.com/X0smh04.png))

## Steps to reproduce

1. Setup Analytics within SK on a new site. Notice the unusual GA4 behaviour if selecting a GA4 property from the dropdown if one exists. If non exist proceed with a standard setup
2. The greyed out GA4 box exists when revisiting your Analytics settings

## Screenshots

<details>
    <summary>Big screenshots</summary>

![image](https://user-images.githubusercontent.com/41326532/150113285-26363fff-2c16-4724-8116-5c657ac2847f.png)

![image](https://user-images.githubusercontent.com/41326532/150112461-61ffe2a1-a1c6-443c-a187-8c68f51eb8bf.png)

![image](https://user-images.githubusercontent.com/41326532/150112500-1ad64514-4381-4bbf-807c-c1bee88c681a.png)

</details>

## Additional Context

 - Occurs on support sites using SK 1.48.1 and 1.49
 - [WordPress support topic with this behaviour](https://wordpress.org/support/topic/ga4-settings-disappear/)
 - Occurs on sites with only SK active, all other plugins disabled
 - Tested with burner site
 - This doesn't seem to impact older sites that already have GA4 properties setup 
 - The GA4 snippet remains placed on a users site even if the settings overview or editing the settings doesn't express this

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Per [this documentation](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.dataStreams), the Google Analytics Admin API endpoints for web data streams have changed. Now all types of data streams (we only care about web data streams in Site Kit) are in this one endpoint, and per the documentation the shape of the resources have slightly changed as well (see `stream_data` property). Site Kit's internal implementation should be updated to rely on the new endpoints.
* The [Google API PHP client services library](https://github.com/googleapis/google-api-php-client-services) should be updated to version **0.230.0**.
    * Please verify as part of the IB (e.g. by doing a quick update locally or in a draft PR) that this doesn't make relevant modifications to other (non `GoogleAnalyticsAdmin`-related) API client classes that Site Kit is using. If there is something in there, please raise it in the IB or comment so we can decide what to do about it.
* The `GET:webdatastreams` and `GET:webdatastreams-batch` datapoints should be adjusted to rely on the new [properties.datastreams/list](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.dataStreams/list). In order to still return exclusively _web_ data streams, the results of that API call need to be filtered on our end so that only those data streams that are web data streams (`stream_data` is in the [web data stream-specific shape](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.dataStreams#WebStreamData)).
* The `POST:create-webdatastream` should be adjusted to rely on the new [properties.datastreams/create](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.dataStreams/create).
* See [this class](https://github.com/googleapis/google-api-php-client-services/blob/ec64bbf1d6af9475bee7b1ce4fc0ed8a0a8d8889/src/GoogleAnalyticsAdmin/Resource/PropertiesDataStreams.php#L32) from the library which has to be used for that, by accessing its instance from the `GoogleAnalyticsAdmin` service.

## Implementation Brief

**Create PR against `main`.**

* Update `google/apiclient-services` to the latest version `0.230.0`

#### `Analytics_4`

* Update `GET:webdatastreams*` and `POST:create-webdatastream` request creation handlers to use the `properties_dataStreams` resource of the `analyticsadmin` service instead of `properties_webDataStreams`
    * Update the response parsing handlers to filter the response to include only data streams with a `type` of `WEB_DATA_STREAM`
    * For `create_webdatastream`, the request needs to move the web-specific data fields into a new `GoogleAnalyticsAdminV1alphaDataStreamWebStreamData` object 
* Update `filter_webdatastream_with_ids` to match `dataStreams` instead of `webDataStreams`

#### Datastore & client

* Update references to `webdatastream.measurementId` and `webdatastream.defaultUri` to get the measurement ID from the new location `datastream.webDataStreamData.measurmentId` and `datastream.webDataStreamData.defaultUri`
* Finish and merge https://github.com/google/site-kit-wp/pull/4690
    - Requires updating some remaining instances of references as mentioned above and general polish

### Test Coverage

* Update tests, fixtures, etc as needed

## QA Brief

* This issue substantially changed the way the GA4 module communicates with the API for datastreams (the entity connecting a property to a measurement ID) so GA4 functionality should be thoroughly tested including:
	* Analytics with GA4 setup + settings
		* GA4 property matching based on reference URL
	* GA4 property creation
	* Existing GA4 property, without a matching measurement ID (datastream)
    * Existing Analytics setup, enabling GA4
    * Analytics account provisioning (should also create a GA4 property + datastream/measurement ID)

## Changelog entry

* Update Google Analytics 4 integration to use new `dataStreams` endpoint after breaking change in alpha API.

**Comment by aaemnnosttv** [comment]
Update: this appears to be related to changes to the [`properties.webDataStreams`](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams) endpoints of the `v1alpha` version of the Analytics Admin API. Investigation is ongoing.

**Comment by felixarntz** [comment]
@aaemnnosttv I've defined ACs here, still pending a new release of the PHP client services library. Would appreciate if you could already have a look if that sounds reasonable to you.

**Comment by aaemnnosttv** [comment]
@felixarntz this is ready for your review. See my working draft PR here https://github.com/google/site-kit-wp/pull/4690/files?w=1

**Comment by felixarntz** [comment]
@aaemnnosttv  IB ✅

**Comment by wpdarren** [comment]
###   QA Update: ✅ 

**Verified:**

- Successfully created a new Google Analytics account with UA and GA4 property. 
- Reset Site Kit and re-connected Analytics. The UA and GA4 property appeared automatically based on reference URL
- Deleted the matching measurement ID (datastream) on GA4 property. Reset Site Kit and re-connected Analytics. The GA4 property was automatically selected but when I clicked on Configure analytics button, a popup appeared asking for permissions to create a new measurement ID. Checked Analytics and settings and new measurement was created.
- Created a new GA4 property from within settings, so that the account has two GA4 properties. The new property was created and settings was updated.
- Reset Site Kit and re-connected Analytics. The two GA4 properties appeared. The latest GA4 appeared by default but I was able to change it to the other GA4 property. 
- Created a new Google Analytics account with only a UA property. 
- Set up new site and connected Analytics. Thee UA property was automatically selected. When I clicked on Configure analytics button, a popup appeared asking for permissions to create a GA4 property. Can see that a new GA4 property was created in settings. 
- Also looked at a site that has GA4 setup and I was able to go to the settings, and field was not greyed out. I was able to create a new GA4 property, select a new property etc. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/150802539-1f431a68-4c1a-478b-8fcf-175752bf85e5.png)
![image](https://user-images.githubusercontent.com/73545194/150802551-b88723ec-10e9-4a30-bf2c-81c86dc04e11.png)
![image](https://user-images.githubusercontent.com/73545194/150802567-e481d416-8765-4a73-8935-aa85298e9a41.png)
![image](https://user-images.githubusercontent.com/73545194/150802596-e5c12952-5c06-455c-bd8e-dd3a6b837d84.png)
![image](https://user-images.githubusercontent.com/73545194/150802617-276d0d0d-7d2d-41d1-adca-9d9c6dc967ab.png)
![image](https://user-images.githubusercontent.com/73545194/150802637-2a513085-bc33-4889-81fe-253481e5b43a.png)

</details>

**Comment by aaemnnosttv** [comment]
@wpdarren the part of the API we're using now should be unaffected by the upcoming changes but it would be good to do some testing post-update just to be sure.
