### ISSUE TITLE
Add more GA events for unified dashboard UI elements

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4682]
There should be a few additional GA events for opted-in users, to track specific interactions with some of the new UI elements.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA tracking events (grouped by category) should be implemented:

### Category `{viewContext}_headerbar`
* Name: `open_urlsearch`: user clicks the search icon to open the URL search text input
* Name: `close_urlsearch`: user clicks the "x" or otherwise closes the URL search text input

### Category `{viewContext}_headerbar_urlsearch`
* Name: `open_urldetails`: user proceeds to navigate to a specific URL search result

### Category `{viewContext}_navigation`
* Name: `tab_select`: user clicks on one of the tabs/pills in the navigation
    * Include the slug of the pill as event label (e.g. "traffic")
* Name: `tab_scroll`: one of the tabs/pills in the navigation becomes active by the user scrolling to the respective area
    * Include the slug of the pill as event label (e.g. "traffic")
* Name: `return_to_dashboard`: user clicks on the "Back to dashboard" link (in the entity dashboard header)

### Category `{viewContext}_adsense-cta-widget`
* Name: `widget_view`: widget becomes visible (similar how this is implemented e.g. in the PageSpeed Insights widget)
* Name: `activate_module`: user clicks the button to activate the module (_only_ when the button activates the module, _not_ when it is there to complete the setup)
    * Include "adsense" as event label (it should always be that, since that's the only relevant module, however it should still be included since that is the case for all other existing variants of the `activate_module` event
* Name: `dismiss_widget`: user clicks the secondary button that will dismiss the widget (after a confirmation dialog)
* Name: `dismiss_dialog_confirm`: user confirms dismissing the widget in the dialog
* Name: `dismiss_dialog_cancel`: user cancels dismissing the widget in the dialog

## Implementation Brief
* Using `assets/js/components/EntitySearchInput.js`,
	* Update the functions below to call `trackEvent` function with their corresponding details:
		* function: `onOpen`
			* category: `{viewContext}_headerbar`
			* name: `open_urlsearch`
		* function: `onClose`
			* category: `{viewContext}_headerbar`
			* name: `close_urlsearch`
	* Update the category for `open_urldetails` from `{viewContext}_headerbar` to `{viewContext}_headerbar_urlsearch`
* Using `assets/js/components/DashboardNavigation.js`,
	* Update the functions below to call `trackEvent` function with their corresponding details:
		* function: `handleSelect`
			* category: `{viewContext}_navigation`
			* name: `tab_select`
			* label: The `chipID` variable
		* function: `onScroll`
			* category: `{viewContext}_navigation`
			* name: `tab_scroll`
			* label: The `closestID` variable
* Using `assets/js/components/EntityHeader.js`,
	* Update the `onClick` function to call `trackEvent` with the following details:
		* category: `{viewContext}_navigation`
		* name: `return_to_dashboard`
* Using `assets/js/modules/adsense/components/common/AdSenseConnectCTA.js`,
	* Detect if the widget is in view using the same technique as in `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js` using the `useIntersection` hook.
	* When the widget is visible, call `trackEvent` with the following details:
		* category: `{viewContext}_adsense-cta-widget`
		* name: `widget_view`
	* Update the functions below to call `trackEvent` function with their corresponding details:
		* function: `handleConnect`
			* category: `{viewContext}_adsense-cta-widget`
			* name: `activate_module`
			* label: `adsense`
		* function: `handleConnect`
			* category: `{viewContext}_adsense-cta-widget`
			* name: `activate_module`
			* label: `adsense`
		* function: `handleDismissModule`
			* category: `{viewContext}_adsense-cta-widget`
			* name: `dismiss_widget`
		* function: `handleConfirmDialog`
			* category: `{viewContext}_adsense-cta-widget`
			* name: `dismiss_dialog_confirm`
		* function: `handleDismissDialog`
			* category: `{viewContext}_adsense-cta-widget`
			* name: `dismiss_dialog_cancel`

### Test Coverage
* No new tests to be added.

## QA Brief

* Use the Google Analytics Debugger Browser Extension to check if events fire correctly as per the AC.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 @FlicHollis This issue is also necessary for the `unifiedDashboard` epic launch, so I've included it in the current sprint and upcoming release. It shouldn't be too major, let's evaluate which other issue we can remove from the sprint instead.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update ❌ 

@jimmymadon I'm seeing odd behaviour with the `tab_scroll` event: 

Bear with me as I go through my process 😄 

- When the dashboard loads, the traffic chip is selected by default and the event label is `traffic` which is correct. I then click each chip in the order that they are in the tab menu and the event label is correct for each chip. All good. I then click on the traffic chip again, the dashboard scrolls to the top, and and the event label is `traffic` which is correct. This is where I start to see the odd behaviour:

Next, I click on the speed chip, and the event label is `content` even though you can see from my screenshot I am in the speed area of the dashboard. 

![image](https://user-images.githubusercontent.com/73545194/151163766-227e4e30-3a3d-4fc2-90ef-d162ce5d314f.png)

After scratching my head, this issue appears on all chips, when you visit the dashboard and then click a chip outside of the order of the chips in the menu.  E.g. load the Site Kit dashboard, click on the monetization chip and the event label is `content` Bit of an odd one and only appears for the the `tab_scroll` event.

**Verified:**

**Category {viewContext}_headerbar**

- open_urlsearch: appears as per the AC
- close_urlsearch: appears as per the AC

**Category {viewContext}_headerbar_urlsearch**

- open_urldetails: appears as per the AC

Category {viewContext}_navigation

- tab_select: appears as per the AC
- tab_scroll: appears as per the AC
- return_to_dashboard: appears as per the AC

**Category {viewContext}_adsense-cta-widget**

- widget_view: appears as per the AC
- activate_module: appears as per the AC
- dismiss_widget: appears as per the AC
- dismiss_dialog_confirm: appears as per the AC
- dismiss_dialog_cancel: appears as per the AC

**Comment by jimmymadon** [comment]
@wpdarren When we are on ‘traffic’ and we click on ‘speed’, 3 events in total fire off: 1 `tab_select` event and 2 `tab_scroll` events (first for `content` and next for `speed`). This is because when we select a tab, the behaviour is to ‘smoothly scroll’ to that section rather than ‘jump’ to it.

@felixarntz Just to confirm, is the above behaviour definitely incorrect or is it alright? The AC for `tab_scroll` does say that when ***a user*** scrolls, we fire the `tab_scroll` event (and not when we programatically scroll to that area by selecting a chip).

**Comment by jimmymadon** [comment]
Created a follow up PR to resolve this.

**Comment by felixarntz** [comment]
@jimmymadon The `tab_scroll` event should only be fired when a tab is selected _because_ of the user scrolling around.

When the user selects a tab _themselves_, only `tab_select` should be fired. The scrolling that selecting this tab results in should then not trigger any (additional) event.

So basically for every change of the active tab, there should be either `tab_select` (if clicked on by the user) or `tab_scroll` (if "automatically" selected because of the user scrolling).

Let me know if that answers your question.

**Comment by jimmymadon** [comment]
@felixarntz @wpdarren This was a bit tricky to "fix". In addition to us programmatically scrolling when selecting a tab, the browser also scrolls when we visit a url that already has a # (causing the `tab_scroll` to fire "incorrectly" as @techanvil pointed out). I've updated the follow-up PR and added a comment on there. However, if this does not pass CR/QA tomorrow, we could revert just the single `tab_scroll` event and create a separate issue for the next sprint?

cc @eclarke1

**Comment by eugene-manuilov** [comment]
@techanvil do you mind reviewing another approach how to fix the aforementioned issue? #4740

**Comment by techanvil** [comment]
Hey @eugene-manuilov, I've taken a look, broadly looks like an improvement but the `tab_scroll` on initial page load had resurfaced. I've suggested a fix on the branch, as mentioned [here](https://github.com/google/site-kit-wp/pull/4740#issuecomment-1024333757).

**Comment by eugene-manuilov** [comment]
@felixarntz could you please review #4740 too? We need your opinion there. 🙏

**Comment by aaemnnosttv** [comment]
Due to the limited time before the release I asked @wpdarren to take a quick preview of the PR to ensure this resolved his problems that he found initially. He confirmed that it does, so I'll merge this to avoid further delaying QA.

**Comment by aaemnnosttv** [comment]
Back to you @wpdarren for another pass 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

**Category {viewContext}_headerbar**

- `open_urlsearch`: appears as per the AC
- `close_urlsearch`: appears as per the AC

**Category {viewContext}_headerbar_urlsearch**

- `open_urldetails`: appears as per the AC

Category {viewContext}_navigation

- `tab_select`: appears as per the AC
- `tab_scroll`: appears as per the AC
- `return_to_dashboard`: appears as per the AC

**Category {viewContext}_adsense-cta-widget**

- `widget_view`: appears as per the AC
- `activate_module`: appears as per the AC
- `dismiss_widget`: appears as per the AC
- `dismiss_dialog_confirm`: appears as per the AC
- `dismiss_dialog_cancel`: appears as per the AC
