### ISSUE TITLE
Fix VRT tests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4683]
## Bug Description

Our VRT tests recently started failing for what seems to be external factors. The last update to our reference images was 9 days ago in https://github.com/google/site-kit-wp/pull/4587 which only updated 6 images and we currently have 42 failures, so this wouldn't have been responsible.

The most likely cause it seems is that the Google Sans web font has changed as the diffs are highlighting changes in primary headings which are the main places this font is used. Roboto use does not raise any differences so it can't be a general web font issue.

## Steps to reproduce

* Run VRT tests on develop
* Run VRT tests on main

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/150288499-3e665cdf-6bfa-4ea9-89c2-55af6c8b3774.png)

![image](https://user-images.githubusercontent.com/1621608/150289406-7bab1ffb-35ff-4b03-b0c1-d8718e09ca67.png)

## Additional Context

- Seems to have started on 2022-01-19

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Visual regression references should be updated

## Implementation Brief

**Create PR against `main`.**

* Run VRT tests, review and approve the changes

### Test Coverage

* N/A

## QA Brief

* Verify the VRT GitHub Action workflow is working correctly and all tests are passing.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@aaemnnosttv This still needs an estimate :)

**Comment by aaemnnosttv** [comment]
> @aaemnnosttv This still needs an estimate :)

ZenHub is trolling me; I added one! :hurtrealbad: 

Done 😄

**Comment by tofumatt** [comment]
QA ✅
