### ISSUE TITLE
Fix GA tracking events for banner notifications

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4686]
There is something slightly off with how Site Kit currently sends GA tracking events for banner notifications. The original purpose of #4056 was to introduce tracking events exclusively for the remote notifications (from `core/site/data/notifications` endpoint, controlled via proxy), but there was some confusion on this and eventually this was implemented as a general set of tracking events that fire for _every_ `BannerNotification`, which results in some duplicate events that are unnecessary.

Part of the problem was that #4153 and #4170 only happened after the above issue, and those should probably have been a prerequisite to implement the GA events correctly. Anyway, this issue is about correcting the behavior.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All 4 GA events of the `${ VIEW_CONTEXT_DASHBOARD }_site-notification` category should be removed from the `BannerNotification` component and instead be integrated into the `CoreSiteBannerNotification` component, so that they only fire for those interactions with the latter type of notifications instead of all notifications.
* The event category should then be adjusted to `${ VIEW_CONTEXT_DASHBOARD }_remote-site-notification` (which was also the originally intended category for #4056 that later got changed, but shouldn't have per the above issue description).

## Implementation Brief
* Using `assets/js/components/notifications/CoreSiteBannerNotification.js`,
	* Call `trackEvent` with `${ VIEW_CONTEXT_DASHBOARD }_remote-site-notification` as category for the following:
		* Upon component mount, using the `useMount` hook:
			* name: `view_notification`
			* label: The `id` prop.
		* `onDismiss` function:
			* name: `dismiss_notification`
			* label: The `id` prop.
		* `onCTAClick` function:
			* name: `confirm_notification`
			* label: The `id` prop.
		* Add a new `onLearnMoreClick` function which calls `trackEvent` with the name set to `click_learn_more_link` and the label set to the `id` prop.
			* Add the `onLearnMoreClick` prop to the `BannerNotification` passing the newly created `onLearnMoreClick` function.
* Using `assets/js/components/notifications/BannerNotification.js`,
	* Add a new prop, `onLearnMoreClick` which is a function and should be called if defined within the `handleLearnMore` function.
	* Remove the `trackEvent` calls.

### Test Coverage
* No new tests to be added.

## QA Brief
- Make sure `Google Analytics Debugger` chrome extension is installed
- Use the `Google Analytics Debugger` to verify the GA tracking events for Banner Notifications fire according to the AC with `dashboard_remote-site-notification` category and notification ID as the label

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by techanvil** [comment]
## QA :white_check_mark: 

`QA:Eng`:

* Confirmed `view_notification`, `dismiss_notification`, `confirm_notification` and `click_learn_more_link` events firing with correct `id` and `${ VIEW_CONTEXT_DASHBOARD }_remote-site-notification` category.
* Verified these events are firing from `CoreSiteBannerNotification` rather than `BannerNotification`.
