### ISSUE TITLE
Improve GA4 detection

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4688]
## Bug Description

At present if a request made to the GA4 API fails, the plugin assumes GA4 isn’t working. This can cause issues when initially connecting Analytics and also when editing the settings.

**When initially connecting:**
- There is a blue bar to state a GA4 property will be created if the selected account has no GA4 property (even if GA4 is not available) ([screenshot](https://i.imgur.com/C8cupER.png))
- There is an assumption a GA4 snippet will be placed if a user selects a GA4 property yet this is not the case (https://recordit.co/xAN1Uoz49j)
- There is no snippet placed

**When editing the Analytics settings**
- Prior to editing at the status screen there are no GA4 notices ([screenshot](https://i.imgur.com/JtwKywZ.png))
- The GA4 property dropdown disappears on a property is selected, after appearing momentarily

The below gif demonstrates this behavior when "Editing" the Analytics options. 

![2022-01-19-11-10-25](https://user-images.githubusercontent.com/41326532/150118825-4d0738db-28f1-44cf-a67f-4c8cd021bea8.gif)

Some possible improvements could be:
- No blue bar mentioning "A GA4 property will be created" if the GA4 API is down or there are issues
- No GA4 property selection if the GA4 API is down or there are issues
- A notice is added mentioning that the GA4 API is not accessible at this point (maybe with a link to documentation)
- The Analytics status has a notice regarding GA4 availability rather than not displaying any GA4 info
- The GA4 property dropdown doesn't appear on the edit screen 

--------

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kuasha420** [comment]
Now that the GA4 API has been promoted to `beta` and we have #5574 to upgrade Site Kit to use the new beta api and #5575 to remove all the fallbacks, this issue is no longer relevant. Once those are merged, we will no longer need to check for API stability and will always have GA4. Feel free to check the aforementioned issue(s) to track the progress there.

As discussed  in the Team Review meeting. closing this one as resolved. 

cc @jamesozzie
