### ISSUE TITLE
Multiple notices stack on top of each other

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#4689]
## Bug Description

Whenever there is more than one notice triggered for a site, they are stacked on top of each other, taking up almost all the space above the fold (laptop size screen).

Let's add logic which displays only one notice at a time until either it expires or the user interacts with it (e.g. dismisses it or follows the CTA).

## Screenshots
This is an example of 3 notices stacked on top of each other:
![image](https://user-images.githubusercontent.com/13304791/150357218-22ecc6f8-ccf9-446d-9569-f922932c3bab.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If there is more than one notice triggered for a particular site, display only one at a time, following the following priority list:
    1. the success notification that appears after connecting Site Kit or a new module
    2. any remote notification from the service (i.e. from `core/site/data/notifications`)
    3. any other notification triggered by the plugin
* Once the user interacts with the notice (e.g. clicks "ok got it" or "connect service" etc) or the notice expires, display the next notice. 
* Only one notice should be displayed at a time on the dashboard.

### Implement the UI behaviour where only one notification is visible at a time

Within `assets/sass/components/global/_googlesitekit-publisher-wins.scss`:

* Add a CSS rule to hide the adjacent sibling of a `.googlesitekit-publisher-win`. In other words, within the definition of `.googlesitekit-publisher-win`, add the following:
```scss
	& + .googlesitekit-publisher-win {
		display: none;
	}
```

Within `assets/js/components/notifications/BannerNotification.js`:

* In the `dismissNotification` function, within the `setTimeout` callback, replace the following lines:
https://github.com/google/site-kit-wp/blob/9c2c0185ec6a37414cdd06812197d50c134b924e/assets/js/components/notifications/BannerNotification.js#L146-L148
* With a call to `setIsDismissed( true )`.

### Ensure the correct order of notifications

Within `assets/js/components/notifications/BannerNotifications.js`:

* Include `SetupSuccessBannerNotification` in the list contained in the `Fragment` instead of returning it on its own. Ensure the same conditions still apply to its inclusion.
* Make sure that the order of notifications is `SetupSuccessBannerNotification`, then `CoreSiteBannerNotifications`, and then the rest in the same order they are presently.

Within `assets/js/components/legacy-notifications/index.js`:

* Move the following block above the first `addFilter` call and change the priority to `10`:
https://github.com/google/site-kit-wp/blob/907a8bbfaed9a1d4ae02ec2760eee0c344760d32/assets/js/components/legacy-notifications/index.js#L79-L90

### Test Coverage

* Fix any failing tests.

## QA Brief

`QA:Eng`:

* Enable `ideaHubModule`, `userInput` and `unifiedDashboard` feature flags.
* Setup the AdSense module.
* Clear Session Storage, if this is not a fresh install.
* Navigate to `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success`, in order to display a setup success notification.
* Using the Dispatcher in Redux Devtools, mock some Core Site notifications. Select the `core/site` store and dispatch:
```js
{
    payload: {
        response: [
          {
              id: 'test-notification-1',
              title: 'Test Notification 1',
              content: 'This is test notification 1',
              ctaURL: '#test-1',
              ctaLabel: 'Test 1',
              ctaTarget: '_blank',
              learnMoreURL: '#learn-more-test-1',
              learnMoreLabel: 'Learn more 1',
              dismissible: true,
              dismissLabel: 'Dismiss 1',
          },
          {
              id: 'test-notification-2',
              title: 'Test Notification 2',
              content: 'This is test notification 2',
              ctaURL: '#test-2',
              ctaLabel: 'Test 2',
              ctaTarget: '_blank',
              learnMoreURL: '#learn-more-test-2',
              learnMoreLabel: 'Learn more 2',
              dismissible: true,
              dismissLabel: 'Dismiss 2',
          },
        ],
        params: {}
    },
    type: 'RECEIVE_GET_NOTIFICATIONS'
}
```
* Mock an AdSense notification. Select the `module/adsense` store and dispatch:
```js
{
    payload: {
        response: [
          {
              id: 'test-notification-3',
              title: 'Test Notification 3',
              content: 'This is test notification 3',
              ctaURL: '#test-3',
              ctaLabel: 'Test 3',
              ctaTarget: '_blank',
              learnMoreURL: '#learn-more-test-3',
              learnMoreLabel: 'Learn more 3',
              dismissible: true,
              dismissLabel: 'Dismiss 3',
          }
        ],
        params: {}
    },
    type: 'RECEIVE_GET_NOTIFICATIONS'
}
```
* Ensure the User Input notification is active. Select the `core/user` store and dispatch:
```js
{
  payload: {
    userInputState: 'missing'
  },
  type: 'RECEIVE_USER_INPUT_STATE'
}
```
* Verify the notifications appear one at a time as per the AC.
* Disable `unifiedDashboard` and repeat the above steps, but this time only dispatch the actions for Core Site and User Input notifications.
* Verify the notifications appear one at a time as per the AC.

## Changelog entry

* Show only one notification at a time on the Site Kit dashboard.

**Comment by techanvil** [comment]
Hi @felixarntz / @marrrmarrr, something to note regarding the AC here -

> If there is more than one notice triggered for a particular site, display the one that was triggered earlier and block the additional notices from being displayed.

When it comes to determining which notice was triggered _earlier_, we don't presently have any timestamp data on the notifications by which to order them. Would it suffice to treat the existing order of notifications as the order in which they should be displayed, i.e. the top one is displayed first?

One other question, relating to the second AC point:

> Let's add logic which displays only one notice at a time until either it expires or the user interacts with it (e.g. dismisses it or follows the CTA).

I'm not sure that we currently have notices that expire by themselves - can you please confirm if this is the case?

Thanks!

cc @aaemnnosttv

**Comment by felixarntz** [comment]
@techanvil 
> When it comes to determining which notice was triggered earlier, we don't presently have any timestamp data on the notifications by which to order them. Would it suffice to treat the existing order of notifications as the order in which they should be displayed, i.e. the top one is displayed first?

We don't have timestamp information, so it's okay to simply use the order the notifications would otherwise be displayed in.

> I'm not sure that we currently have notices that expire by themselves - can you please confirm if this is the case?

We don't, at least that's nothing to really worry about in the plugin. It can be that for example a remote notification no longer appears on another page load a bit later, if it's no longer relevant. But in that case, the "expiration" happens more on the service side, nothing the plugin would have to be concerned with.

Hope that clarifies your questions!

**Comment by techanvil** [comment]
Thanks @felixarntz, that does indeed!

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by felixarntz** [comment]
@techanvil Apologies, but after talking with @marrrmarrr about this again, we came to a conclusion that there has to be _some_ sense of priorities in there, otherwise users may miss more important notifications if they never dismiss another permanent one. I've updated the ACs around this. Could you please review and look into amending the IB?

cc @eugene-manuilov @aaemnnosttv

**Comment by techanvil** [comment]
No worries @felixarntz, I've updated the IB accordingly, cheers.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by hussain-t** [comment]
### QA:Eng Verified ✅ 
--------------------
- Verify the notifications appear one at a time as per the AC.
- Disable `unifiedDashboard` and repeat the above steps, but this time only dispatch the actions for Core Site and User Input notifications.
- Verify the notifications appear one at a time as per the AC.
