### ISSUE TITLE
Add a "gatheringData" prop to the GoogleChart and Sparkline components

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4696]
## Feature Description

The [Widget updates section of the Zero States design doc](https://docs.google.com/document/d/1gRBpyGYA0IEE0wVw1cA__lG23xZCmAo68RS8SNGYRto/edit#heading=h.dr7ijhm9hegu) mentions that line charts (rendered directly in `GoogleChart`) and graphs (eg. the chart rendered by the `Sparkline` component) should support a "Gathering data" UI state.

This prop should be passed from the parent component (which will have an awareness of whether or not the component is gathering data from the `isGatheringData()` selector for its module) to the `GoogleChart`/`Sparkline` component, causing it to render as per the design doc:

> Line charts should have a “Gathering data” overlay as well, with the X/Y axis rendered but no data in the chart.

![CleanShot 2022-01-21 at 02 07 24](https://user-images.githubusercontent.com/90871/150452872-d72069cf-bcb9-4143-a117-ded331c89c0a.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* This feature should be implemented behind the `zeroDataStates` feature flag. #4726
* The `Sparkline` component should have a new prop, `gatheringData`, that should be passed through to the `GoogleChart` component it renders. If `gatheringData` is set, the component should always output the `GoogleChart`, even if `data` is falsey, so this logic will need to be updated: https://github.com/google/site-kit-wp/blob/c7b3415f5207126acc913156464ddaf488a1e4a7/assets/js/components/Sparkline.js#L30
* The GoogleChart component should accept a new prop, `gatheringData`, that causes it to render a chart with the proper axis labels but has no data. Instead of displaying a chart with data, it should display the text "gathering data…" on top of it, like in the Figma mocks. Every GoogleChart output type should accept and use the `gatheringData` prop. It is likely that logic in the Chart components will need to be updated to reflect the lack of `data`/report data being supplied to the `GoogleChart`. This may also require setting the axis scale manually because there will be no data to inform the axis labels/markers.
  * The one exception for this issue is that `PieChart` output will be handled by #4675 and can be skipped by this issue.
* New storybook stories should be added for chart components in the "gathering data" state, as this issue won't implement them anywhere else in the app, so this will allow us to QA the components easily.

## Implementation Brief

- In `assets/js/components/GoogleChart.js`: 
    - Expect and destructure a new prop, `gatheringData` for this component and default it to false. Add it to the GoogleChart.propTypes object as a boolean (`PropTypes.bool`).
    - Further destructure `options` from the already destructured `props` as we need to modify options below. Pass the `options` to the child `Chart` component's props.
    - If the `zeroDataStates` feature flag is disabled, overwrite the `gatheringData` prop to be false after the props are destructured.
    - Use the `getDateRangeDates()` selector (with default options) from the `core/user` store. Destructure the `startDate` and `endDate`.
    - IF `gatheringData` is true AND `chartType === 'LineChart'` then check if the below options exist within `options`. If they are NOT set, default them to the ones below:
        ```
        option.vAxis.viewWindow.max = 100
        options.vAxis.viewWindow.min = 0
        options.hAxis.viewWindow.max = `endDate` returned from the `getDateRangeDates()` selector above
        options.hAxis.viewWindow.min = `startDate` returned from the `getDateRangeDates()` selector above
        ```
        **Note:** If the above default values are used, the corresponding `vAxis.ticks` and / or `hAxis.ticks` should be deleted from `options`. If `ticks` is defined and an empty array, then the default ticks above will not show on the empty chart.
        
    - Within the `return()` of the component, if `gatheringData` is true, implement an [overlay based on this structure](https://developers.google.com/chart/interactive/docs/overlays#divs). To do this:
        - Conditionally add a class `googlesitekit-chart--with-overlay` to the **parent** div of the `Chart` component. 
        - Conditionally add a new `div` component with the `googlesitekit-chart--overlay` class which should be a sibling of the `Chart` component. This component should contain the "gathering data..." text.
- In `assets/sass/components/global/_googlesitekit-chart.scss`:
    - Add styles to implement the overlay. Using the below snippet as an example, style the overlay as per the Figma Designs in the AC.
        ```scss
        .googlesitekit-chart--with-overlay {
	        position: relative;

        	.googlesitekit-chart__overlay {
        		height: 100%;
        		left: 50%;
        		position: absolute;
        		top: 50%;
        		width: 100%;
        		z-index: 10;
        	}
        }
        ```
- Create a `Component/GoogleChart` story in `assets/js/components/GoogleChart.stories.js`:
    - Add a story to render a `GoogleChart` mimicking the data and props from the `SearchConsoleStats` component. This should be a default chart with some data.
    - Create another story setting the `gatheringData` prop to `true`. The rendered component should be as per the Figma design in the AC, i.e., the data should fill the axes labels and legend but should have zero Impressions (y-axis) for all Dates (x-axis) and the "gathering data..." overlay.

### Test Coverage

* No new tests required.

## QA Brief

* Check StoryBook for the new GoogleChart -> Gathering Data component and see if it matches the Figma design mock mentioned in the Feature Description above.

## Changelog entry

* Add the gathering data state to the GoogleChart component.

**Comment by jimmymadon** [comment]
@tofumatt Tiny question - any reason why we are introducing `isGatheringData` in some components and `gatheringData` in others where the prop is implementing the same logic to show the 'gathering data...' overlays?

**Comment by jimmymadon** [comment]
@tofumatt I cannot find a Sparkline graph in the Figma design for a `gatheringData` state, other than this [AdSense Earnings](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734) widget which is likely to be removed. So for a tiny Sparkline component, if `data` is falsey and we simply render a `gatheringData` line chart, that will render a chart similar to the one in the AC Screenshot with the "gathering data..." text (which is not what we want?). So how should we proceed?
1. Just return `null` and keep the Sparkline component untouched unless we have a use case for a `gatheringData` sparkline component OR
2. Create a generic grey "flat lined" sparkline chart that spans the whole width of the chart similar to the one in the proposed [AdSense Earnings](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734) widget. Maybe there should be more Figma examples of such a sparkline being used in other `gatheringData` components if any?

**Comment by jimmymadon** [comment]
@tofumatt's comments to my questions above: 
- Will create a new issue to find and replace all isGatheringData and gatheringData props to be one or the other after all issues are merged in - no point in doing this while some issues are merged and other still in IB.
- As for Sparkline graphs, there are no Figma examples of these in the `isGatheringData` state besides AdSense Earnings widget. So we will just keep them untouched as they are always used in `Data Blocks` which show the 'gathering data' text anyways. Returning `null` when `data` is falsey will keep these graphs hidden in such component. The alternative of showing tiny flat grey sparklines may not add anything to the UI.

**Comment by jimmymadon** [comment]
@eugene-manuilov @asvinb The legend, axes labels, min/max, etc. of the `GoogleChart` all depend on the parent of `GoogleChart`. So after discussing this issue with @tofumatt, we think that it will be easier to pass down data that is similar to "Zero Data" from parent components for the `gatheringData` state . We could do this in #4697. If so, would it be worth mentioning this in 4697's IB and bumping its estimate?

**Comment by eugene-manuilov** [comment]
> The legend, axes labels, min/max, etc. of the GoogleChart all depend on the parent of GoogleChart. So after discussing this issue with @tofumatt, we think that it will be easier to pass down data that is similar to "Zero Data" from parent components for the gatheringData state . We could do this in https://github.com/google/site-kit-wp/issues/4697. If so, would it be worth mentioning this in 4697's IB and bumping its estimate?

From my understanding, the only thing we need to do is to add min/max values for axes when `gatheringData` is truthy. Everything else already provided by parent components, right? I think we can use 0 and 1 as min and max values for Y axis, and yesterday/today for X axis.

> Use GoogleChart.defaultProps to set the default to false.

The `defaultProps` is going to be deprecated. We should use default values instead:

```diff
- export default function MyComponent( { myProp } ) {
+ export default function MyComponent( { myProp = false } ) {
      ...
  }

- MyComponent.defaultProps = {
-     myProp: false,
- }
```

> * Create `stories/google-chart.stories.js`:

We should use the Storybook v6 approach for new stories. Stories in the `stories/` folder use pre-v6 approach and considered as legacy. Please, update it to mention the new approach.

**Comment by tofumatt** [comment]
(I assigned myself before realising the pings sent to me were addressed in a conversation @jimmymadon and I had last week, summed up here: https://github.com/google/site-kit-wp/issues/4696#issuecomment-1028451039)

(Un-assigning myself as @eugene-manuilov is reviewing this IB 👍🏻 )

**Comment by jimmymadon** [comment]
@eugene-manuilov Thanks for the feedback - I have updated the IB to reflect the default props and Storybook v6 changes.

As for the min/max values, did you mean we should add 'default' min/max values within the `GoogleChart` component?

I think *all* the data, including the min/max should come from the parents of the `GoogleChart` component even when `gatheringData` is truthy (and in all other cases too like Zero Data and normal data). This way the `GoogleChart` will not assume the axes will contain dates or a count. Different parent components may have different units of data - some have dates and impressions, while some graphs may have currency, etc. Currently, the `gatheringData` state doesn't apply to AdSense graphs but that might change in the future?

**Comment by eugene-manuilov** [comment]
> I have updated the IB to reflect the default props and Storybook v6 changes.

@jimmymadon Did you save your changes? I don't see it.

> As for the min/max values, did you mean we should add 'default' min/max values within the `GoogleChart` component?

Yes, if they are not defined for axes yet in the `options` and `gatheringData` is truthy.

> I think _all_ the data, including the min/max should come from the parents of the `GoogleChart` component even when `gatheringData` is truthy (and in all other cases too like Zero Data and normal data).

That would be nice, but it will require a lot of work to update all widgets and components that use charts (+ then QA everything). Much easier to update the GoogleChart component to do if on their behalf if the parent component not provided it.

> Different parent components may have different units of data - some have dates and impressions, while some graphs may have currency, etc.

As far as I remember our X axis is always dates, and Y axis is always a numeric value. We don't have other types for linear charts, do we?

> Currently, the `gatheringData` state doesn't apply to AdSense graphs but that might change in the future?

Maybe... @tofumatt can you chime in here?

**Comment by jimmymadon** [comment]
@eugene-manuilov Have updated the IB based on your comments and our conversation. The `dateRangeLength` is actually not available in `GoogleChart` but in its parent components. Is it worth fetching it or should we just default it to 28 days like I have currently in the IB?
```
const dateRangeLength = useSelect( ( select ) =>
	select( CORE_USER ).getDateRangeNumberOfDays()
);
```

**Comment by eugene-manuilov** [comment]
> @eugene-manuilov Have updated the IB based on your comments and our conversation. The `dateRangeLength` is actually not available in `GoogleChart` but in its parent components. Is it worth fetching it or should we just default it to 28 days like I have currently in the IB?
> 
> ```
> const dateRangeLength = useSelect( ( select ) =>
> 	select( CORE_USER ).getDateRangeNumberOfDays()
> );
> ```

@jimmymadon we need to use the `getDateRangeDates()` selector in the `GoogleChart` component. It will return an object with `startDate` and `endDate` dates which are min and max values for the hAxis respectively.

> * IF `gatheringData` is true AND `chartType === 'LineChart'` then check if the below options exist within `options`. If they are NOT set, default them to the ones below:
>   ```
>   option.vAxis.viewWindow.max = Date object for todays date
>   options.vAxis.viewWindow.min = Date object for 28 days ago
>   options.hAxis.viewWindow.max = 100
>   options.hAxis.viewWindow.min = 0
>   ```

`vAxis` should have `0`/`100` min/max values, `hAxis` should use dates returned by the aforementioned selector.

**Comment by eugene-manuilov** [comment]
Thanks, @jimmymadon. IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Checked StoryBook for the new GoogleChart -> Gathering Data component and it matches the Figma design mock,

![image](https://user-images.githubusercontent.com/73545194/157431683-764cc048-109f-4150-a4c6-1b40632da958.png)
