### ISSUE TITLE
Update all Widgets to pass isGatheringData prop to chart/table/other components

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4697]
## Feature Description

Every widget that has an `isGatheringData()` selector should no longer return a "loading" state when `isGatheringData()` returns `true`. Instead, any widget that is gathering data should pass `isGatheringData` to the child `GoogleChart`/`Sparkline`/`DataBlock`/`UserDimensionsPieChart`/`ReportTable` component so it renders the new "gathering data" UI implemented in #4692/#4696/#4699/#4700.

Given some refactoring might be needed to allow us to handle components with no data in their report, I think it's best to handle these changes all in one issue in case there are common design patterns/changes that become obvious while working on many components.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The changes described in this issue should only occur when the `zeroDataStates` feature flag is enabled. See: #4726. Note: it may be okay to pass the `gatheringData` prop to these components regardless of the feature flag being enabled, as rendering the "gathering data…" UI will likely be based on the feature being on.
* All components available in the Unified Dashboard that output a `DataBlock`, `GoogleChart`, `ReportTable`, or `Sparkline` should be updated to check for `isGatheringData()` if relevant and pass the result to the aforementioned components using `gatheringData={isGatheringData}`.
* The UI of these components should show "gathering data…" when they are in a "gathering data" state.

## Implementation Brief
* Look for parent components housing the components below and update them to check if they are still gathering data via the `isGatheringData` selector for the appropriate store and pass the value returned from the selector via the `gatheringData` prop for those components.
	* `DataBlock`
	* `GoogleChart`
	* `ReportTable`
	* `Sparkline`
* The components to take a look at:
	* `DashboardAllTrafficWidget`
	* `SearchFunnelWidget`
	* `DashboardPopularKeywordsWidget`
	* `ModulePopularPagesWidget`
	* `ModuleOverviewWidget`
	* `DashboardTopEarningPagesWidget`
	* `DashboardOverallPageMetricsWidget`

### Test Coverage

* No new tests to be added.

## QA Brief

* Use the tester plugin to simulate the gathering data status for Search Console and Analytics modules (see `Force ... report data` options.
* Activate the `zeroDataStates` feature flag.
* Go the unified dashboard and verify that all widgets display the correct gathering data state. Check the same on the entity page.
* Disable the `unifiedDashboard` feature flag and check plugins on the dashboard and details pages as well.

## Changelog entry

* Update widgets to pass gathering data state to components.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvinb this passes the QAB because `gathering data…` does appear on all of the search console and analytics widgets. That said, I did notice odd behaviour, which I didn't notice it when testing #4696. The `gathering data…` loads slightly early when the loading animation is running for the graphs on All traffic widget and search traffic widget.  I'm just wondering if this work had an impact on that.  Screencast here. Thoughts, welcome. 

https://user-images.githubusercontent.com/73545194/158354793-37dc9a86-80e0-4ddb-b200-696d417f32ff.mp4

**Comment by asvinb** [comment]
@wpdarren You're right, it looks a bit awkward. I tried to see if it was an easy fix but was didn't really find the cause of this behaviour. Do you mind spinning up a new ticket to address this issue?

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@asvinb @tofumatt this does pass the QAB but I thought I would see how things look with AdSense connected. Chatting to Asvin on Slack, it looks like from [this conversation](https://github.com/google/site-kit-wp/issues/4696#issuecomment-1040355199) that zero data states doesn't apply for AdSense, but I feel for gathering data it does.  Here's my scenario. 

1. On the main dashboard: with `zeroDataStates` enabled and `unifiedDashboard` disabled  I see the old style blue gathering data box for AdSense.  In the tester plugin `Force AdSense report data` is set to gathering. The `Force AdSense account status` is set to approved. 

![image](https://user-images.githubusercontent.com/73545194/158383482-7cccca5c-05f4-4562-9908-04ae19e1a901.png)

2. On the AdSense module page with same setup above.  I see the same but this is on the `Performance by page over the last 28 days` widget. 

![image](https://user-images.githubusercontent.com/73545194/158384471-cd92f148-27ff-4201-910d-008c8cd77b23.png)

I realise at some point we will be rolling out Unified Dashboard to everyone but I don't know if that will be before we roll out Zero data states.  We have asked this question in the open-channel.  I'm sending this back but if a decision has already made on this feel free to send this ticket back to QA.

**Comment by eugene-manuilov** [comment]
@wpdarren there is a ticket to fix this issue: #4908

**Comment by wpdarren** [comment]
@eugene-manuilov @asvinb Ah, I didn't do a good job at looking through the tickets.  Sorry, and thank you.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

WIth `unifiedDashboard` enabled: 

- All widgets display the correct gathering data state on the main and entity dashboard. 

With `unifiedDashboard` disabled: 

- All widgets display the correct gathering data state on the main and entity dashboard and module pages. 

- Checked on small screen sizes to make sure of no styling issues. 
- Checked the Site Kit menu bar on the front end to make sure gathering data state appeared.
- Checked the WP Dashboard to make sure gathering data state appeared.


https://user-images.githubusercontent.com/73545194/158580757-819298cc-5b5a-4b0d-a2b1-8668e708597d.mp4
