### ISSUE TITLE
Add Dashboard Notifications for modules that are gathering data (eg isGatheringData) 

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4698]
## Feature Description

As part of the Zero State design, we should show a notice to users anytime _any_ available module is gathering data (eg. the selector `select(moduleStore).isGatheringData() === true`). The notice can be [found in the Figma mocks](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=435%3A2736) will look like this:

![CleanShot 2022-01-21 at 02 18 08](https://user-images.githubusercontent.com/90871/150453901-d42f517f-c157-46a3-8382-c012f4b856ce.png)

The text in the Figma mock is accurate, but should allow for the service/module name to be dynamic (as the text will depend on which module is gathering data).

This implementation should also allow for the possibility that more than one module is gathering data. In that case, instead of a particular module name, we can say "Several services are gathering data about your site."

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* This feature should be implemented behind the `zeroDataStates` feature flag. #4726
* On the Site Kit Main and Entity Dashboards, the `search-console` and `analytics` modules (**only those!**) should be checked to see if their `isGatheringData()` selector returns `true`.
* If that is the case for at least one of them, a notification should be shown (as seen in the Figma mockup/writeup above) that warns the user that their site is gathering data. The text should be as follows (slightly different from the above Figma screenshot):
    * Heading should be one of
        * _Search Console is gathering data_
        * _Analytics is gathering data_
        * _Search Console and Analytics are gathering data_
        * depending on which of the modules is/are gathering
    * Description: _It can take up to 48 hours before stats show up for your site. While you’re waiting, connect more services to get more stats._
    * There should only be a "dismissal link" button that reads "OK, Got it!". It should dismiss the message as normal, though it will re-appear next day (the default period of time to hide a notification for) if there is still zero data in more than 24 hours

## Implementation Brief

Export the notification graphic from Figma and save it under `assets/svg/graphics/`.
![image](https://user-images.githubusercontent.com/18395600/155707680-26983084-cdba-4278-a4a2-22cff9cf14a2.png)

Within `assets/js/components/notifications/ZeroDataStateNotifications.js` (this file will be created via #4693):

In this new component:

* Import the new SVG as a component called e.g. `GatheringData`.
* Conditionally render a `BannerComponent` if the `isGatheringData()` selector for either `search-console` or `analytics` returns `true`, with the following props (use `__` from `@wordpress/i18n` to translate the text):
  * `id`: `gathering-data-notification`
  * `title`:  Use the correct heading from the AC, depending on which modules are gathering data.
  * `description`: This should be the description from the AC
  * `isDismissable`: `true`
  * `dismiss`: _OK, Got it!_
  * `dismissExpires`: 24 hours - use `getTimeInSeconds( 'day' )`
  * `format`: `small`
  * `SmallImageSVG`:  `GatheringData` (or whatever the new SVG component is called)

### Test Coverage

* No new tests needed.

## QA Brief

- Make sure `zeroDataStates` feature flag is enabled in your SK dashboard 
- Verify the newly added stories are passing
- As an extra mile testing, in `assets/js/modules/analytics/datastore/report.js`, return `true` from `isGatheringData` selector
- Verify the banner notification is displayed for `Analytics` as below:

<img width="991" alt="Screenshot 2022-03-08 at 9 26 44 AM" src="https://user-images.githubusercontent.com/24408261/157167527-47f96e70-35b6-442e-a23d-114d8b9d5ec5.png">

- In `assets/js/modules/search-console/datastore/report.js`, return `true` from `isGatheringData` selector
- Verify the banner notification is displayed for `Search Console` as below:

<img width="991" alt="Screenshot 2022-03-08 at 9 26 23 AM" src="https://user-images.githubusercontent.com/24408261/157167629-0510fabd-4341-4047-b066-2d1bbf2c390e.png">

- Return `true` from `Analytics` and `Search Console` `isGatheringData` selectors
- Verify the banner notification is displayed as below:

<img width="991" alt="Screenshot 2022-03-08 at 9 27 10 AM" src="https://user-images.githubusercontent.com/24408261/157167721-e451b0d0-f301-4b3f-88f1-61b224754101.png">

- Disable `zeroDataStates` feature flag
- Verify that `ZeroDataStateNotifications` aren't displayed

## Changelog entry

* Add notifications to site header when Analytics and/or Search Console are still gathering data.

**Comment by felixarntz** [comment]
@tofumatt The ACs here are _mostly_ good, however I think we need to clarify the wording here with @marrrmarrr, so I've moved it back to ACs. But most importantly, if the wording remains as it is in the screenshot above, the ACs need to specify that it has to be somehow dynamic. For example, what if Search Console has data, but Analytics is gathering data? In that case, the wording here would be incorrect.

I'll review this with @marrrmarrr and then we can see how to proceed.

**Comment by bethanylang** [comment]
New guide about this data state will be at https://sitekit.withgoogle.com/documentation/using-site-kit/dashboard-data-display/.

**Comment by eclarke1** [comment]
@marrrmarrr would it be possible to review the copy on the Figma file here please? We're on track to get all other Zero Data State issues into Sprint 70 starting Feb 28, so wondering if it makes sense to get this and #4693 added alongside to keep everything together?

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t @tofumatt while this passes the QAB, I do have a few observations:

1. We are asking users to think about connecting more services. Do you feel that we need to add a link to the connect more services tab within Site Kit settings? We have done that with the new service connect notifications with `serviceSetupV2` and it would be more user-friendly. 

2. The `Ok, got it` link colour is different to the figma designs. I am assuming that this is expected but wanted to check. 

![image](https://user-images.githubusercontent.com/73545194/157854821-e1782ad4-8894-4ef8-bea4-80781bc0d479.png)

3. In the QAB it mentioned `QA:Eng` but with the changes to the tester plugin, I was able to test this. Unsure if there's still any testing an engineer wants to complete?

**Verified:**

- The banner notification is displayed for Analytics as AC/Figma designs.
- The banner notification is displayed for Search console as AC/Figma designs.
- The banner notification is displayed for Search console and Analytics as AC/Figma designs.
- Checked that the stories matched expected designs
- Checked that the notifications do not appear when `zeroDataStates` is disabled
- Checked notifications on small screen sizes.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/157855834-d3975709-7341-479d-b4fc-52b2d200a80b.png)
![image](https://user-images.githubusercontent.com/73545194/157855857-d5a6cc83-6337-4e85-b071-d762afa56fa3.png)
![image](https://user-images.githubusercontent.com/73545194/157855882-6889a86d-8904-466b-a80c-281726a57411.png)
![image](https://user-images.githubusercontent.com/73545194/157855899-4e0dfc62-d431-4626-b9b7-fe58a51e8505.png)

</details>

**Comment by tofumatt** [comment]
1. That's a good point. Can you file a follow-up issue for that and link to it from here? I agree, but it's out-of-scope for this issue 🙂 
2. Yeah, that's fine. Our colours are a bit different and we'll update them en-masse in the future 😅 
3. Apologies, I should've caught that but this is all QA-able without an engineer, agreed.

Thanks 👍🏻

**Comment by wpdarren** [comment]
### QA Update ✅ 

**Verified:**

- The banner notification is displayed for Analytics as AC/Figma designs.
- The banner notification is displayed for Search console as AC/Figma designs.
- The banner notification is displayed for Search console and Analytics as AC/Figma designs.
- Checked that the stories matched expected designs
- Checked that the notifications do not appear when `zeroDataStates` is disabled
- Checked notifications on small screen sizes.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/157855834-d3975709-7341-479d-b4fc-52b2d200a80b.png)
![image](https://user-images.githubusercontent.com/73545194/157855857-d5a6cc83-6337-4e85-b071-d762afa56fa3.png)
![image](https://user-images.githubusercontent.com/73545194/157855882-6889a86d-8904-466b-a80c-281726a57411.png)
![image](https://user-images.githubusercontent.com/73545194/157855899-4e0dfc62-d431-4626-b9b7-fe58a51e8505.png)

</details>
