### ISSUE TITLE
Add isGatheringData prop and "Gathering data" state/UI to UserDimensionsPieChart

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4699]
## Feature Description

The `UserDimensionsPieChart` component should get a new boolean prop: `isGatheringData`.

When in this new "Gathering data" state, the `UserDimensionsPieChart` should output this UI from the [Figma mocks](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734):

<img width="582" alt="CleanShot 2022-01-21 at 02 33 24" src="https://user-images.githubusercontent.com/90871/150455466-9f0939e0-c05f-48c2-b06e-6dc8da4c2de5.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* This feature should be implemented behind the `zeroDataStates` feature flag. #4726
* The `gatheringData` prop, added to the `GoogleChart` component in #4696, should cause a `PieChart` component to output an empty, non-interactive pie chart with the "gathering data…" text inside the chart, as shown in the Figma mocks/screenshot above
* The `UserDimensionsPieChart` component should be updated to accept a `gatheringData` prop and should pass `gatheringData={isGatheringData}` to the `GoogleChart` component, such that when the component that is gathering data, it outputs the gathering data state. (The component that renders `UserDimensionsPieChart` will be updated as part of #4697, so this doesn't need to be done in this issue.)
* The `UserDimensionsPieChart` component should ensure the tabs at the top of the chart and the links below the chart are still rendered, but non-interactive. This means they should not be clickable and also not interactive (with either the mouse or keyboard). It would be good to include some `aria-` attributes where appropriate to note to the user that the components are gathering data and the elements are not usable whilst gathering data.

## Implementation Brief

- To disable the tabs, in `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/DimensionTabs.js`:
    - Add a `gatheringData` boolean prop
    - Add `gatheringData` to the propTypes
    - Pass `disabled={ gatheringData }` prop to the `<Tab />` element
    - To disable the dropdown on the smaller screens, Pass `disabled={ gatheringData }` prop to the `<Select />` element

- To show the gathering data state in the chart, in `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js`:
    - Add a `gatheringData` boolean prop
    - Add `gatheringData` to the propTypes
    - Pass `gatheringData={ gatheringData }` prop to the `<GoogleChart />` element. Note that adding the `gatheringData` prop to the `GoogleChart` component will be defined in #4696 
    - To disable the links below the chart, pass `disabled={ gatheringData }` prop to the `<Link />` element
    - Add `aria-label="Analytics Gathering Data"` and `role="region"` attributes to the first child `<div />` element if `gatheringData` is `true`. See:
    https://github.com/google/site-kit-wp/blob/893f917932a174268da41c8667b75d30df56885c/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js#L548
    

### Test Coverage

- N/A

## QA Brief

**QA:Eng**
- Verify the changes met the AC and implemented as per the IB
- Open `assets/js/modules/analytics/datastore/report.js` file and return `true` by default from the `isGatheringData()` selector
- Verify the `DimensionTabs` are disabled
- Verify the links below the chart are disabled
- Verify the `DimensionTabs` dropdown are disabled on the smaller screens

**QA:Eng**
**Update on the follow-up PR:**
- Open `assets/js/modules/analytics/datastore/report.js` file and return `true` by default from the `isGatheringData()` selector
- Verify the `PieChart` is disabled and non-interactive
- Verify the text should be `gathering data…`

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
Thanks, @hussain-t. A few comments:

> To disable the tabs, in `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/DimensionTabs.js`:
> 
> * Add a `isGatheringData` boolean prop
> * Pass `disabled={ isGatheringData }` prop to the `<Tab />` element

We also need to disable the `<Select>` element which is shown on smaller screens.

> * Add a `isGatheringData` boolean prop

The property name should be `gatheringData`.

> If `isGatheringData` is `true` set the following:
> * Set the `labels` value to `gathering data...` text, something like this:
> 
> ```js
> labels = {
> 	'ga:channelGrouping': __( 'gathering data…', 'google-site-kit' ),
> };
> ```
> 
> * Set the `options.pieSliceText` property value to `none`
> * Set the `options.tooltip.trigger` property value to `none`
> * Set the `options.sliceVisibilityThreshold` property value to `1`

We don't need to change chart options. The `GoogleChart` component will take care of its state when the appropriate `gatheringData` property is passed. What we need to add to IB is that we need to pass the `gatheringData` property passed to the `UserDimensionsPieChart` component to the `gatheringData` property of the `GoogleChart` element.

> * Add the classes `__dimensions-chart-gathering-data` and `__dimensions-chart-gathering-data` to the `<div />` element (where the title is rendered currently) - conditionally based on the `isGatheringData` prop.

Why do we need to change styles and add new classes? The `gathering data` text with the appropriate styles will be added by the `GoogleChart` component once #4696 is implemented.

> * Add `aria-label="Gathering Data"` attribute to the first child `<div />` element if `isGatheringData` is `true`. See:

Plus we need to add the `role="region"` attribute to that div.

**Comment by hussain-t** [comment]
Thanks for pointing it out @eugene-manuilov. I was a bit confused that the `UserDimensionsPieChart` component should be responsible for disabling the pie chart based on the screenshot. I have updated the IB and reduced the estimate to 7.

**Comment by eugene-manuilov** [comment]
Thanks, @hussain-t. IB ✔️

**Comment by eugene-manuilov** [comment]
@tofumatt do you mind looking at [this comment](https://github.com/google/site-kit-wp/pull/4841#discussion_r807195820)?

**Comment by tofumatt** [comment]
@eugene-manuilov Apologies for not getting to it sooner, was struggling through some E2E tests 😅

I've left a comment; if that's the only thing remaining I think we can commit my change and then merge, but I've assigned it back to you to be sure. Thanks 👍🏻

**Comment by asvinb** [comment]
### QA: ❗ 

* Tabs are disabled when `gatheringData` prop is `true`.
* Links below the graph are disabled when `gatheringData` prop is `true`.

@tofumatt The second point in the AC mentions the following:
> component to output an empty, non-interactive pie chart with the "gathering data…" text inside the chart, as shown in the Figma mocks/screenshot above

This has not been implemented in the PR and as per @eugene-manuilov's [comment](https://github.com/google/site-kit-wp/issues/4699#issuecomment-1026794086), this will be implemented in #4696 . I just want to confirm the AC is incorrect in this case 😁

**Comment by tofumatt** [comment]
The original intention was that this issue _would_ cover the UI for the Pie Chart, because it was a bit of a special case I believe—I thought we couldn't load "empty" data into a pie chart as easily. So the aim of this issue was to do that work here, and I don't think is in the scope of #4696.

In fact, the ACs for #4696 state this explicitly:

> The one exception for this issue is that `PieChart` output will be handled by #4675 and can be skipped by this issue.

I think either of the following options for the UI for the PieChart is fine:

* it needs to be handled by this issue, and thus sent back to execution
* it needs a new issue

I don't think we can add it onto the scope of #4696 given that issue explicitly says to ignore that part of the implementation and it's already in execution.

Let's add it back in this issue to reduce overhead.

**Comment by hussain-t** [comment]
Thanks for bringing it to attention @asvinb 👍 

Thanks @tofumatt, I initially thought that disabling the `PieChart` is part of this issue as per the AC. However, I was a bit confused after @eugene-manuilov's comment. 

NVM, I will address this in a follow-up PR 😃

**Comment by aaemnnosttv** [comment]
@asvinb ready for another pass 👍

**Comment by asvinb** [comment]
### QA: ✅ 

- PieChart styled as per Figma designs when `isGathering` data prop is `true`
- Tabs are disabled when gatheringData prop is true.
- Links below the graph are disabled when gatheringData prop is true.
