### ISSUE TITLE
Support for WP 4.9

### ISSUE THREAD

**Issue by Mte90** [google/site-kit-wp#47]
**Describe the bug**
Readme say that is compatible with WP 4.7 but doesn't seems.
![immagine](https://user-images.githubusercontent.com/403283/60014065-64a49a00-9680-11e9-93fc-e4bd436cee6d.png)

I think that is looking for JS stuff that are available only after 5.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by felixarntz** [comment]
Hi @Mte90, thanks for the report!
The plugin bundles those dependencies itself specifically to load them in these cases (pre-5.0), so they should be available then. We're gonna check what's wrong there.

Can you provide us with a bit more information? You're using WP 4.9? Do you have the Gutenberg plugin installed by any chance?

**Comment by Mte90** [comment]
WordPress 4.9 without gutenberg plugin and amp plugin installed.

**Comment by ivankristianto** [comment]
This issue is related to AMP plugin (version 1.2.0),
and it fixed in this PR:

**Comment by swissspidy** [comment]
@Mte90 Since you've already tested the version of the AMP plugin with the bugfix, can you confirm that Site Kit is now working properly as well?

**Comment by Mte90** [comment]
I can confirm that now with the latest amp is working.

**Comment by jamesozzie** [comment]
@Mte90 Good news, thanks for the update. If you have a minute leave a [review](https://wordpress.org/support/plugin/amp/reviews/) for the plugin authors with their rapid fix.
