### ISSUE TITLE
Filter Tag Manager containers by the correct usage context and support native AMP

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#470]
## Feature Description

When listing Tag Manager containers during module setup and when editing settings, we simply list all containers. However, there are Tag Manager containers that are not made for regular websites, and including them in dropdowns for Site Kit does not make sense. See `usageContext` under https://developers.google.com/tag-manager/api/v2/reference/accounts/containers#resource. We typically should only list containers with `usageContext` of `web`.

Furthermore, if the WordPress site is using native AMP, the dropdown should only include containers with a `usageContext` of `amp` (this value _is_ supported by the API although not documented in the reference).

Last but not least, when creating a new container, we currently always set the `usageContext` to `web`. If the site is using native AMP, we should instead set it to `amp`.

~~**This issue is blocked by #432.**~~

Related: #413 (that will be the next step after this, and it is where this was originally reported)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

> Updated to reference new datapoints.
> Updated case of referenced variables/props/keys to adhere to new rules

* Only `web` containers should every be handled or created by Site Kit - unless the site uses native AMP, in which case only `amp` containers should be handled or created.
* The existing `GET containers` endpoint should be enhanced so that it supports an optional `usageContext` query parameter. If provided, the containers retrieved from Google API should be filtered to only include those with the passed `usageContext`.
* The existing `POST settings` datapoint should be enhanced to also support an optional `usageContext` query parameter. The default would be `web`. The newly created container should then respect that parameter.
* Consuming JavaScript code should pass `usageContext` of `web` or `amp` in the requests, depending on whether the site uses native AMP or not.
* Any `amp` container ID should not be stored in the existing `containerID` option entry, but a distinct `ampContainerID`.
* The AMP-specific snippets should only be rendered on the page based on `ampContainerID`, not `containerID`.

## Implementation Brief

* Update `\Google\Site_Kit\Modules\TagManager::create_container` to accept a new `$usage_context` parameter, which is then passed to `$container->setUsageContext()` as an array.
* Add support for a new `usageContext` data parameter (default to `web`)
    - `GET container-id` 
        + `web` : `containerID`
        + `amp` : `ampContainerID`
    - `GET containers` - filter containers by given context
    - `POST settings`
        - pass to `create_container`
        - if context is `amp`, save container ID under `ampContainerID` key
* Update `TagmanagerSetup.handleSubmit` to pass `usageContext` to `settings` datapoint based on `googlesitekit.admin.ampMode`
    - if `primary`, pass `amp`
    - otherwise `web`
* Update `TagmanagerSetup` to use `ampContainerID` based on `googlesitekit.admin.ampMode`
* Update `\Google\Site_Kit\Modules\TagManager::print_amp_gtm` to pass `usageContext` to call to `GET container-id`
    - `\Google\Site_Kit\Modules\TagManager::print_gtm_js` no change needed as it will default to `web` context

#### Secondary

Should this also be done?

* ~~Remove `create_container` call within `GET containers`  
Seems that a GET request should not trigger a side-effect like this~~

## Changelog entry

* Only show Tag Manager containers that are relevant to the site's mode, and accordingly support AMP-first by only exposing AMP containers.

**Comment by aaemnnosttv** [comment]
> Consuming JavaScript code should pass usageContext of web or amp in the requests, depending on whether the site uses native AMP or not.

What determines whether the site uses native AMP or not? Isn't this derived from server-side context? If so, then why would we pass from server to client and back?

**Comment by aaemnnosttv** [comment]
This is blocked by changes in progress to these datapoints in #452.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> What determines whether the site uses native AMP or not? Isn't this derived from server-side context? If so, then why would we pass from server to client and back?

It comes from server-side indeed (`get_amp_mode()` from #432, the `primary` value), but the API should be decoupled from that. There will be #413 some time soon, and for that we'll need multiple GTM containers with different usage contexts. So this needs to be passed from the client.

**Comment by felixarntz** [comment]
IB ✅ 

Let's not cover the secondary item for now as it's unrelated.

**Comment by felixarntz** [comment]
This issue is more problematic than it seems because Site Kit will also show any non `web` containers today, which it must not. Great that it's already in the works, as we should prioritize this.

**Comment by tofumatt** [comment]
QA ✅

Tested this with a few sites with AMP on, in Reader mode, and off. Everything behaved as expected; only the correct contexts were shown for each mode and new properties were created with the correct mode as well.
