### ISSUE TITLE
Add connected Google account name to Settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#4707]
## Feature Description

In v1.50.0 as part of the Unified Dashboard epic, we're removing the display of the account name that is connected to Site Kit in the header.

As noted by @felixarntz in Slack, this was done to ensure consistency with other Google UI. While it does not need to display in the header, it would be good to have this information available somewhere in the plugin, presumably somewhere in Settings.

Not having the account name easily available could cause some frustration for users as we do see confusion in support about connecting multiple accounts. The support team also uses this information (when provided by users via screenshot) to confirm that they are connected to the correct account if they have questions about data displayed in Site Kit.

cc @marrrmarrr 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user icon (Google profile photo) in the Site Kit header bar should receive a tooltip (similar to how other icon buttons there have a tooltip) which is the term "Google Account" on the first line, and the current authenticated Google account email address. Basically the same as in the screenshot in https://github.com/google/site-kit-wp/issues/4707#issuecomment-1020208065, just without the name.
    * We currently don't capture the name, we only record the email address. It's not crucial to also display the name, at least not in this issue. We can re-evaluate later.

Example tooltip:
```
Google Account
hello@gmail.com
```

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Looking at UI in the Google services, they surface the information already in a tooltip. I think doing that would be a good approach for us - we already use tooltips so adding that here would be straightforward (see screenshot below). What do you think @marrrmarrr?

<img width="173" alt="Screen Shot 2022-01-24 at 2 58 27 PM" src="https://user-images.githubusercontent.com/3531426/150810248-6b771557-a37f-4129-b011-52378a5c4868.png">

**Comment by marrrmarrr** [comment]
@felixarntz this approach generally SGTM. Let's just make sure we have a version of this that works on mobile, the space there is already very knapp, this tooltip would take half of the screen width.

**Comment by aaemnnosttv** [comment]
Not sure how I missed this but thanks for opening @bethanylang !

Closing in favor of #5724 and #5775 .
