### ISSUE TITLE
Prune unused legacy notification counter

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4718]
## Feature Description

Site Kit has a notification counter which is lingering around but no longer used for some time now. This may be needed again in the future with the newer notifications system, but we shouldn't keep dead code around; we can always bring this back if needed. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`notification-counter.js`](https://github.com/google/site-kit-wp/blob/f7ada9c5aa602308a14779cf3e913a4983fade8b/assets/js/components/legacy-notifications/notification-counter.js) and any related utilities, styles, etc _only used by the counter_ should be removed

## Implementation Brief
* Remove the following files and update files where they are imported:
	* `assets/js/components/legacy-notifications/notification-counter.js`
	* `assets/sass/components/global/_googlesitekit-notifications-counter.scss`
	* `assets/js/components/legacy-notifications/util.js`
* Update `assets/js/util/standalone.js` to remove the `appendNotificationsCount` function.
	* Remove any references to `appendNotificationsCount` function, for e.g in `assets/js/googlesitekit-base.js` and delete `assets/js/util/test/appendNotificationsCount.js`.

### Test Coverage
* Update tests to cater for above changes if any.

## QA Brief

Ensure dashboard and settings still load after notification code is removed. No change in functionality should be observed.

**QA:Eng**

I don't think it is possible to test manually. However, ensure there is no usage/imports for the removed `notification-counter` files.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@asvinb I think we can remove the `assets/js/components/legacy-notifications/util.js` file as well. Can you add it to IB?

**Comment by eugene-manuilov** [comment]
> * Update `assets/js/util/standalone.js` to remove the `appendNotificationsCount` function.

Actually, one more thing. I am not sure that this needs to be removed since. At least, not in the scope of this ticket I believe. @aaemnnosttv am I right?

**Comment by asvinb** [comment]
@eugene-manuilov @aaemnnosttv I do think the `appendNotificationsCount` function needs to be removed since it looks for the `googlesitekit::total-notifications` in local storage which is set by the functions in `assets/js/components/legacy-notifications/util.js`

**Comment by eugene-manuilov** [comment]
> @eugene-manuilov @aaemnnosttv I do think the `appendNotificationsCount` function needs to be removed since it looks for the `googlesitekit::total-notifications` in local storage which is set by the functions in `assets/js/components/legacy-notifications/util.js`

If so, then we also need to remove `appendNotificationsCount` usage in the `assets/js/googlesitekit-base.js` file and delete the `assets/js/util/test/appendNotificationsCount.js` file. Can you update the IB to mention it too?

**Comment by asvinb** [comment]
IB updated following your comments @eugene-manuilov

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB :heavy_check_mark:

**Comment by tofumatt** [comment]
I've done the code review here but the QA: Eng here is just verifying that there are no imports of these files present.

That's the case, verified by searching through the repo:

<img width="312" alt="CleanShot 2022-06-16 at 13 26 26" src="https://user-images.githubusercontent.com/90871/174069529-450ce97c-5550-4bb7-9067-13b3c4b93ad3.png">

I'm marking this as QA:Eng ✅ as well, but in retrospect I don't think that QA:Eng step was needed and I probably should have removed it 😅
