### ISSUE TITLE
Error message in wp admin does not contain plugin name.

### ISSUE THREAD

**Issue by carolinan** [google/site-kit-wp#4721]
## Bug Description

Today I ran into this message in my admin screen:

`Unknown Error (code: Invalid JSON response). To fix this, redo the plugin setup.`

Please include which plugin name in the error message, because the only way I could figure out that this was related to Site Kit was to view the source.

![image](https://user-images.githubusercontent.com/1621608/151128204-650fbc91-5927-4b5f-8a17-ff1231b3f414.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All notices added to non-Site Kit screens should clearly identify as originating from the Site Kit plugin by prefixing the message with the plugin name  
E.g.  
  > Site Kit by Google: Unknown Error (code: Invalid JSON response). To fix this, redo the plugin setup.

## Implementation Brief

* Update all notices in the `Authentication` and `Idea_Hub` classes to have `Site Kit by Google:` prefix before the content of the notice: https://github.com/google/site-kit-wp/blob/14e8604318a29a7dfc928029f992c2ad8a6df60c/includes/Core/Authentication/Authentication.php#L1051-L1053 https://github.com/google/site-kit-wp/blob/14e8604318a29a7dfc928029f992c2ad8a6df60c/includes/Core/Authentication/Authentication.php#L1101-L1103 
https://github.com/google/site-kit-wp/blob/14e8604318a29a7dfc928029f992c2ad8a6df60c/includes/Core/Authentication/Authentication.php#L1154-L1156 https://github.com/google/site-kit-wp/blob/14e8604318a29a7dfc928029f992c2ad8a6df60c/includes/Modules/Idea_Hub.php#L310-L312 https://github.com/google/site-kit-wp/blob/14e8604318a29a7dfc928029f992c2ad8a6df60c/includes/Modules/Idea_Hub.php#L346-L348
(If possible this should be localized.)

### Test Coverage

* N/A

## QA Brief

* QAing this would require checking all notices from Site Kit that are displayed in non Site Kit pages of the WordPress Dashboard.
* The following notices can be checked:
  * **URL mismatch notice:** Try changing the Site URL and Home URL of the installation (I changed from `http` to `https`) and see a notice show up.
  * **Authentication notice:** From your Google account, revoke Site Kit's access to your Google account. This should make Site Kit show an authentication error (this sometimes require clearing the local and session storage).
  * **OAuth error:** While setting up Site Kit, cancel instead of continuing to give Site Kit access to Google account. This will trigger a setup interruption error.
  * **Idea Hub notices:** Set up Idea Hub (enable `ideaHubModule` feature flag from Tester Settings) and see notices from Idea Hub in your WordPress Dashboard.

## Changelog entry

* Update admin notice messages to have `Site Kit by Google:` prefixes.

**Comment by ktmn** [comment]
On a side note I'm getting this on 4 sites I checked, do I really need to redo the setup or is it a bug of some sort?

**Comment by Inside4ndroid** [comment]
i am having the exact same issue.... anyone know how we can fix this??

**Comment by aaemnnosttv** [comment]
Thank you for the request @carolinan!

As to the underlying issue, this is most likely related to a temporary disruption to the Site Kit service that we're aware of and continuing to monitor. For more information and updates, please see https://wordpress.org/support/topic/known-issue-january-25-2022-invalid-json-quota-issues/.

**Comment by aaemnnosttv** [comment]
@marrrmarrr how does this sound to you?

**Comment by tofumatt** [comment]
Are these errors localised? If so, we should localise the prefix here as well, right? I know it's pretty minor, but some languages might not want this as a prefix or whatnot… would this make sense to localise or is this always English?

**Comment by eugene-manuilov** [comment]
> Are these errors localised? If so, we should localise the prefix here as well, right? I know it's pretty minor, but some languages might not want this as a prefix or whatnot… would this make sense to localise or is this always English?

@tofumatt, I have updated IB to explicitly mention it. Please, check again.

**Comment by tofumatt** [comment]
@eugene-manuilov I don't see an update to the IB, looks like maybe it didn't take? But sounds like we should localise it, so I'll just add that to the IB and then move this to the backlog to prevent more back/forth 😅

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
IB ⚠️ We can't simply prepend the `$content` with the plugin name as this assumes the content is only text. A `Notice`'s content can be any HTML, so the proposed change would somewhat break our `Activation_Notice` which doesn't need this because it's already included in the full visual notice.

Instead, I think we should probably just apply this on a case-by-case basis in the actual notice instances (there's only 5 other notices we currently use so it shouldn't be too big of a deal 😄).

**Comment by eugene-manuilov** [comment]
Good catch, @aaemnnosttv. Thanks. IB is updated.

**Comment by aaemnnosttv** [comment]
LGTM, thanks @eugene-manuilov 

IB ✅

**Comment by aaemnnosttv** [comment]
### ⚠️ Review

@nfmohit please see my comment on your PR https://github.com/google/site-kit-wp/pull/5223#pullrequestreview-979454605.

Would you please open a follow-up PR to address it?

**Comment by nfmohit** [comment]
> ### ⚠️ Review
> @nfmohit please see my comment on your PR [#5223 (review)](https://github.com/google/site-kit-wp/pull/5223#pullrequestreview-979454605).
> 
> Would you please open a follow-up PR to address it?

Thank you for the kind review @aaemnnosttv! I have opened a new PR to address it.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

The following notices were checked:
URL mismatch, Authentication, OAuth and Idea Hub notices.

Example:
![image](https://user-images.githubusercontent.com/73545194/169835086-484ba159-bfb9-4dc8-9605-dea26db8696e.png)
