### ISSUE TITLE
Getting "This application is temporarily over its serving quota. Please try again later" while resetting Sitekit plugin

### ISSUE THREAD

**Issue by raja-anbazhagan** [google/site-kit-wp#4722]
## Bug Description

After resetting the Sitekit plugin, I'm trying to set up Sitekit again with my google account. But the login results in the following error.
![image](https://user-images.githubusercontent.com/8947215/151124024-34a77389-84a7-4a93-bd84-29669f72f48c.png)

## Steps to reproduce

1. Reset Sitekit plugin
2. Click on 'Sign in To Google'
3. Gets the above error message

**Comment by aaemnnosttv** [comment]
Hi there. We've been experiencing some degradation in the availability of the Site Kit service.

See here for more information https://wordpress.org/support/topic/known-issue-january-25-2022-invalid-json-quota-issues/

Would you please try again and let us know if you continue to experience this problem?

**Comment by raja-anbazhagan** [comment]
Yep. Now I don't see this error anymore.
