### ISSUE TITLE
Refine logic for recoverable modules

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4724]
## Feature Description

Building on the initial logic defined in #4527, the set of recoverable modules should be refined to only include modules that are shared.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The definition of a recoverable module should be refined (in addition to the existing criteria) to  modules which are currently shared with one or more user roles via the dashboard sharing settings.  
_This is particularly important to avoid "all admin modules" (such as PSI) to appear recoverable right away as they only get their owner ID by association to their dashboard sharing settings_
* This logic in `get_recoverable_modules` should be extracted into a new public `is_module_recoverable` method on the `Modules` class
	* This method should receive added test coverage

## Implementation Brief

- Extract the callback method from `Modules::get_recoverable_modules()` into a new public `is_module_recoverable` method in the same class.
- Modify this method by checking the incoming parameter and if it is a `string`, it should try to get the module instance using the `Modules::get_module()` method. This way the method should be able to accept either an instance of `Module` or a module slug string. 
- In the same method, after checking if `$module instanceof Module_With_Owner`, add a check to see if the module has any `sharedRoles` using the `Module_Sharing_Settings` class. If there are no `sharedRoles` set for the Module, then the method should `return false`.

### Test Coverage

* Add PHPUnit tests for the new `is_module_recoverable()` method. Cover the already existing cases within this method as well.

## QA Brief

**QA:Eng**
- Make sure the `dashboardSharing` feature is enabled
- Open the browser developer console and type `window._googlesitekitDashboardSharingData`
- Verify this refactor doesn’t break the existing functionality i.e. the `recoverableModules` array should be available in the console
- Verify the changes met the AC
- Verify the newly added tests are getting passed 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz anything else we should consider here?

**Comment by felixarntz** [comment]
@aaemnnosttv Hmm, why is that condition needed? Wouldn't it technically also make sense to recover a module that is not shared? For example if there are two admins, one sets up Analytics, then disappears. I guess the other admin should then still be able to recover the module, or not? Maybe I'm missing something here.

**Comment by aaemnnosttv** [comment]
> Wouldn't it technically also make sense to recover a module that is not shared? For example if there are two admins, one sets up Analytics, then disappears. I guess the other admin should then still be able to recover the module, or not?

@felixarntz module recovery was designed with dashboard sharing in mind. Part of the functionality of module recovery is to prompt other admins to "adopt" the module ownership to restore data that was previous shared. We shouldn't however do this just for a module that no longer has an owner (or doesn't have one yet) that wasn't shared.

Particularly for shared ownership modules we shouldn't show these as recoverable as it's normal for them to not have an owner which they only currently get by sharing.

We can still allow for module recovery as a simple take over outside of dashboard sharing as you're describing, but that can probably be handled as part of updating settings, etc.

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv Thanks for clarifying, sgtm!

**Comment by eugene-manuilov** [comment]
> * Extract the callback method from `Modules::get_recoverable_modules` into a new public `is_module_recoverable` method in the same class.

@jimmymadon I think if we make this method publicly accessible, then it would make sense to let it accept either module instance or module slug, because when it will be called by other classes, more than a likely, caller will have only module slug.

So, the `is_module_recoverable` method should check the incoming parameter and if it is a string, it should try to get the module instance using the `get_module` method. Could you please add it to IB?

**Comment by jimmymadon** [comment]
@eugene-manuilov Good point - have added this to the IB. I have also bumped the estimate to 7 to cater for adding PHPUnit coverage for this method and its existing cases.

**Comment by wpdarren** [comment]
### QA Update: ❌

@hussain-t I took a look at this and noticed that `recoverableModules` does not include PageSpeed Insights or Idea Hub modules, which it has when testing this previously.  When I switch to the latest release they do appear, but not on `develop` branch. According to the QAB, it would seem they should be.  Any thoughts?

![image](https://user-images.githubusercontent.com/73545194/153839346-b09bc7ac-3c4a-49a8-be02-fbceb795b289.png)

**Comment by aaemnnosttv** [comment]
> I took a look at this and noticed that `recoverableModules` does not include PageSpeed Insights or Idea Hub modules, which it has when testing this previously. When I switch to the latest release they do appear, but not on `develop` branch. According to the QAB, it would seem they should be. Any thoughts?

@wpdarren yes, this issue was essentially opened to fix that, as recoverable modules is really about restoring shared data that was interrupted by the module owner being deleted, etc. Under the initial conditions for recoverable modules, PSI and Idea Hub were included as soon as they were active as they don't have an owner until they're shared (they're special in this way).

The QAB doesn't mean that these modules should still be there, but I can see why you would think that, so thanks for flagging this! Instead I think it just meant to say that `_googlesitekitDashboardSharingData.recoverableModules` should still be set, even though it's expected for now that it would be empty. We'll QA this more later on when the functionality is built out around module recovery so this okay for now.

**Comment by hussain-t** [comment]
Thanks for clarifying this @aaemnnosttv 👍 

>Instead I think it just meant to say that _googlesitekitDashboardSharingData.recoverableModules should still be set, even though it's expected for now that it would be empty.

Yes, that's right 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that the recoverableModules array are available in the console.

![image](https://user-images.githubusercontent.com/73545194/153839346-b09bc7ac-3c4a-49a8-be02-fbceb795b289.png)

Tagging `QA:Eng` for these sections in the QAB

- Verify the changes met the AC in particular `This logic in get_recoverable_modules should be extracted into a new public is_module_recoverable method on the Modules class. This method should receive added test coverage`

- Verify the newly added tests are getting passed

**Comment by jimmymadon** [comment]
### QA: Eng Update: ✅ 

> * Verify the changes met the AC in particular `This logic in get_recoverable_modules should be extracted into a new public is_module_recoverable method on the Modules class. This method should receive added test coverage`

✅  All conditions in the AC extracted in the new method are covered by the new unit tests.

> * Verify the newly added tests are getting passed

✅  All PHPUnit tests pass on my local machine on develop and in the CI build before merge.
