### ISSUE TITLE
Create a `zeroDataStates` feature flag

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4726]
## Feature Description

As discussed today on Slack, we'll need to use a dedicated feature flag for the Zero States after all. Let's create a feature flag: `zeroDataStates`, for this epic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new feature flag named `zeroDataStates` for the Zero States issues to use.

## Implementation Brief

* Add a `zeroDataStates` feature flag to `feature-flags.json`\
* Merge #4727

### Test Coverage

* N/A

## QA Brief

* Ensure the feature flag appears in the Tester plugin and can be enabled/disabled without issue.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:
