### ISSUE TITLE
Date range selector sometimes remains open but hidden after selection

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4735]
## Bug Description

The date range selector (possibly other `Select` components as well) is staying open sometimes after a choice has been selected (see screencast below).

https://user-images.githubusercontent.com/1621608/151421572-6741c5f7-982e-4399-9936-5fc4e141f07a.mp4

It seems this is due to the `.mdc-menu-surface--animating-open` class not being removed in some cases which gives the element an inline-block style with 0 opacity

![image](https://user-images.githubusercontent.com/1621608/151421817-e06ffc65-54c1-4088-ba47-f93fa3947985.png)

## Steps to reproduce

* Change the selected date range until you can see the mouse change to a pointer under it while the menu is invisible

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The date range selector's menu should not be clickable when the menu is not open

## Implementation Brief
* Using `assets/js/components/Menu.js`, set `menuComponent.quickOpen = true` upon the component initialization. 

### Test Coverage
* No new tests to be added.

## QA Brief

* Find the time range selection in the header bar
* Make a mental note of where the menu items are on the page and pick a different timespan
* Hover up and down where the menu items were located with the open menu, be on the lookout for cursor changes. 
* The bug is easily spotted by the cursor changing to a pointer, and the timespan being changed when the invisible element is clicked.
* Expected behaviour after this change is for the menu items not being there at all once the menu is closed, which can be checked by the cursor not changing to a pointer, as detailed above.

## Changelog entry

* Fix date range selector sometimes remaining open but hidden after selection.

**Comment by techanvil** [comment]
Hi @makiost - this looks good, but please can you add a QA Brief?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On the latest release I was able to recreate the issue by the cursor changing to a pointer, and the date range was changed when the invisible element is clicked.  On the develop branch, the menu items are not hidden once the menu is closed. This was checked by the cursor not changing to a pointer.  

https://user-images.githubusercontent.com/73545194/175052429-8879e0fd-82f2-48fd-a519-360576abd11b.mp4
