### ISSUE TITLE
`Module_Sharing_Settings->register()` is being called in two places. 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#4736]
## Bug Description

Due to dependency and timing the `register` function of the newly introduced `Module_Sharing_Settings` is being called in `Google\Site_Kit\Core\Modules\Modules` and `Google\Site_Kit\Plugin`. From discussion in our last Engineering Standup, we should keep the call on `Plugins` and remove the call from `Modules`.

Note that it will mean deviation from the AC or #4526 so QA(:Eng) should keep that in mind while QAing/Approving that ticket. 

## Steps to reproduce

* See [here](https://github.com/google/site-kit-wp/blob/907a8bbfaed9a1d4ae02ec2760eee0c344760d32/includes/Plugin.php#L200) and [here](https://github.com/google/site-kit-wp/blob/907a8bbfaed9a1d4ae02ec2760eee0c344760d32/includes/Core/Modules/Modules.php#L221)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Module_Sharing_Settings` should be registered only once in  the `Google\Site_Kit\Core\Modules\Modules` class.

## Implementation Brief

* Review and merge #4737

### Test Coverage

* N/A - Make sure no test is broken. 

## QA Brief

* Make sure nothing is broken when `dashboardSharing` is enabled. 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@kuasha420 the instance of the `Module_Sharing_Settings` class should be registered in the `Modules` class since it is the only place where that instance is needed. There is no need to create a duplicate instance in the Plugin class only because we need to register it somewhere. I have update the AC and going to approve the IB but will send it back from the "code review" to update your PR.

IB ✔️

**Comment by eclarke1** [comment]
@eugene-manuilov could we please add a priority label to this one? Generally @kuasha420 we don't add estimates of 1 as we have to account for CR and QA, is this really a 1?
cc @FlicHollis

**Comment by kuasha420** [comment]
@eclarke1 I thought the issue was already well defined based on our discussion at the Stand Up and the initial definition had a ready PR (just removing one line) along with it. Cheers.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

When enabling `dashboardSharing` no errors appeared on the FE, or in console.  I also went through all of the dashboard, module pages and settings.
