### ISSUE TITLE
Potential fatal error on Posts page with Idea Hub and PHP 8

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4738]
## Bug Description

It's come to our attention that some users are getting a fatal error when visiting the Posts page in wp-admin when Idea Hub is enabled.

https://wordpress.org/support/topic/e_error-16/
https://wordpress.org/support/topic/critical-error-on-view-all-posts/

```
PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, WP_Error given in /.../wp-content/plugins/google-site-kit/includes/Modules/Idea_Hub.php:319
```

Which references line `319` here https://github.com/google/site-kit-wp/blob/73daa7da01e00c6d2cbb56bcdacfa1e2e74c3a1d/includes/Modules/Idea_Hub.php#L314-L319

The problem is that the response is not checked to be a `WP_Error` or not before caching.

This is likely related to some irregularity that we've seen with the Idea Hub API lately.

This is only a fatal error for PHP 8 – previous versions of PHP only raise a warning.

## Steps to reproduce

1. Use environment with PHP 8
2. Delete the `googlesitekit_idea_hub_saved_ideas` transient
3. Simulate a request failure to Idea Hub API
	- Locally this can be done by disconnecting your internet and loading the Posts page with Idea Hub active and transient deleted
	- Alternatively, use a plugin like [Transients Manager](https://wordpress.org/plugins/transients-manager/) to set the transient for Idea Hub manually  
	key: `googlesitekit_idea_hub_saved_ideas`  
	value:  
	  ```
	  O:8:"WP_Error":3:{s:6:"errors";a:1:{s:7:"unknown";a:1:{i:0;s:62:"cURL error 56: Received HTTP code 502 from proxy after CONNECT";}}s:10:"error_data";a:1:{s:7:"unknown";a:2:{s:6:"status";i:500;s:6:"reason";s:0:"";}}s:18:"�*�additional_data";a:0:{}}
	  ```
4. Observe fatal error (or PHP warning if not on PHP 8)

Upon closer review, there are a few other things which need to be fixed here as well.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/151530289-a7eb1f9e-7c48-4c1d-891a-738aefe6ea77.png)

![image](https://user-images.githubusercontent.com/1621608/151530219-1fa0019a-dec1-42da-b13b-73f775416485.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Idea Hub should only cache ideas from the API when the response was successful (i.e. not a `WP_Error`)
* Idea Hub should clear its cached ideas when disconnected
* Test coverage should be added to cover this behavior

## Implementation Brief

* Extract logic for getting cached ideas into a new `get_cached_ideas` method which takes a datapoint as its only argument (e.g. `new-ideas`)
	- If the associated transient is still valid (i.e. an array), return this value
		- This addresses the case for users with a cached `WP_Error` as well
	- If not, fetch the ideas from the given datapoint
		- If the response is a WP_Error, throw (makes easier handling in the caller)
		- If successful, cache the results in the same transient before returning
* Refactor the `active_callback` functions in both `Notice` instances to use this new method
* Update `on_deactivation` to delete both transients for new and saved ideas
* Finish and merge #4739 
	* Add tests (see below) and testing

### Test Coverage

* Add coverage for this by testing the `is_active` method of each `Notice` while controlling the result of the HTTP request using the `FakeHttpClient` class

## QA Brief

* With Idea Hub connected, visit the Posts page
	- You may or may not see the notice depending on if the API actually has ideas available
* Using the Transients Manager plugin, set the transient for saved ideas to an error as shown in the "Steps to reproduce" above
* Reload the Posts page
* No error or warning should be raised
* Back in the Transients Manager plugin, the transient should be updated now (assuming the request was successful)
	* There's no way to see if the request on the backend was successful or not without using an HTTP proxy which would only be feasible locally

## Changelog entry

* Fix potential fatal error on PHP 8 with Idea Hub integration.

**Comment by wpdarren** [comment]
@aaemnnosttv want to highlight again that at the moment we cannot use oi.ie for idea hub testing, until the API team add it back on.  When I tried using elasticpress.io I do not have permissions for Idea Hub.  Do you have access to help me with that? Otherwise, I am going to struggle to QA this.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

With a site on PHP8, I was able to recreate the error on the posts page with the latest version of Site Kit.  When I switched to the `main` branch and went through the steps to recreate (and QAB) the PHP error no longer appears. When I went back to the transients manager the `googlesitekit_idea_hub_saved_ideas` transient was changed.
