### ISSUE TITLE
Graph Y axis shows negative range in Search Funnel widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4742]
## Bug Description

On the Search traffic widget for Unified Dashboard displays a minus figure on the y-axis. This is an issue on main and entity dashboard. Note, that even if one field has zero data in the widget the same issue occurs. 

![image](https://user-images.githubusercontent.com/73545194/151784607-810f5b29-b447-4d1c-b97b-3c4e67b70a55.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Both `SearchConsoleStats` and `AnalyticsStats` charts of the `SearchFunnelWidget` should only show y values greater than or equal to zero (similar to all other charts used in the plugin)

## Implementation Brief

Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/AnalyticsStats.js`:

* Determine whether the chart is composed of purely zero values:
```js
	// The index of the value used to plot the graph.
	const valueIndex = 2;

	const isZeroChart = ! googleChartData
		.slice( 1 )
		.some( ( datum ) => datum[ valueIndex ] > 0 );
```
* If `isZeroChart` is `true`, set `options.vAxis.viewWindow.max` to `1`. The reference to `options.vAxis.viewWindow` is static (it points to `AnalyticsStats.chartOptions.vAxis.viewWindow`), so it should not be modified directly or the value will persist until the page is reloaded:
```js
	if ( isZeroChart ) {
		options.vAxis.viewWindow = {
			...options.vAxis.viewWindow,
			max: 1,
		};
	}
```

### Test Coverage

* Fix any failing tests. No new tests needed.

## QA Brief

* Activate the Unified Dashboard feature flag.
* Ensure Search Console and Analytics modules are activated.
* Load an Analytics site with goals set but 0 goals met.
* The Y axis of the chart should not be negative, but instead range from 0 (minimum) to 1 (maximum).

As part of doing development on this issue, I also noticed that a dashboard page with zero data for a Search Funnel page will show the negative Y axis:

<img width="1226" alt="CleanShot 2022-01-31 at 22 10 24" src="https://user-images.githubusercontent.com/90871/151881727-8cffa2c5-0c62-4af0-b054-06eaaa4e8c65.png">

This can be seen by:
* Connecting `elasticpress.io` as your Search Console/Site Kit site
* Going to the "Sample Page" Entity Dashboard
* Clicking on a Search Console stat that has "zero data"

So this should also be QA'd by testing the above three steps and ensuring they don't show a negative Y axis, and instead show a min 0, max 1 Y axis:

**Note: bounce rate should show a 0-100 y-axis range when the chart is empty since it is a percentage**

![CleanShot 2022-01-31 at 22 14 07](https://user-images.githubusercontent.com/90871/151881973-e8100821-3f0a-403d-b189-ed1731b3b340.gif)

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@wpdarren I see the issue regarding the negative range on the chart, however I don't see the limited range on the x axis – I think this may be specific to the site. How old is this site?

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
Hmm, just an update that this is a bit weirder than we thought because different stats with zeros are behaving a bit oddly… I'm still working on it, but it's a bit trickier than the ACs/IB states because ALL stats have this issue when they're zero, but we can't check for zero state; we need to check each stat for zero values…

**Comment by techanvil** [comment]
## QA :white_check_mark: 

* Verified that on the Main Dashboard -> Search Funnel widget, for zero goals:
  * Goals shows **0-1** on the Y axis.
* Verified that on the Entity Dashboard -> Search Funnel widget, for zero data:
  * Total Impressions, Total Clicks and Unique Visitors from Search show **0-1** on the Y axis.
  * Bounce Rate shows **0-100** on the Y axis.

**Comment by aaemnnosttv** [comment]
@techanvil one other detail worth checking is that when the value is non-zero (current or previous period), the max y-axis of the chart should be set as usual (based on the data in the set) but always with a min y-axis of `0`.

**Comment by techanvil** [comment]
> @techanvil one other detail worth checking is that when the value is non-zero (current or previous period), the max y-axis of the chart should be set as usual (based on the data in the set) but always with a min y-axis of `0`.

Thanks for pointing that out, @aaemnnosttv - I've gone and verified :white_check_mark:  that the Y axis starts at `0` for all of the Search Funnel charts when there is data for the chart.
