### ISSUE TITLE
Add `adsenseSetupV2` feature flag

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4753]
The new feature flag for the enhanced AdSense setup flow should be added.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `adsenseSetupV2` feature flag should be added, similar to other existing feature flags.

## Implementation Brief
* Add a `adsenseSetupV2` feature flag to `feature-flags.json`

### Test Coverage
* N/A

## QA Brief

* Check that the feature flag is available in the Site Kit Tester Settings plugin.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by techanvil** [comment]
## QA: :white_check_mark: 

Confirmed `adsenseSetupV2` exists and is toggleable in the Tester plugin.
