### ISSUE TITLE
Introduce AdSense REST data point to retrieve information about sites

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4754]
One of the key features of the enhanced AdSense setup flow will be the ability to reliably determine the status of a site (using a new AdSense API endpoint), which today's setup flow only makes assumptions about. This issue is for adding the REST infrastructure for that to the plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new REST data point `GET:sites` should be added to the AdSense module.
* The endpoint should require an `accountID` parameter to be provided.
* Using the given `accountID`, the endpoint should issue a request to the AdSense API [accounts.sites.list endpoint](https://developers.google.com/adsense/management/reference/rest/v2/accounts.sites/list).
* It should return the array within the `sites` field from the API response (i.e. "unnest" the response object similar to how Site Kit does it for most other list endpoints).

## Implementation Brief
* Using `includes/Modules/AdSense.php`,
	* Update `create_data_request` to include the `GET:sites` endpoint.
		* It should check for the `accountID` parameter, else throw a `WP_Error` similar to how it's being done for other endpoints.
		* If `accountID` is defined, get the service for `AdSense` via the `get_service` method and passing `adsense` as parameter.
		* Get all the sites via the `accounts_sites->listAccountsSites` method of the `AdSense` service, passing the `accountID` as parameter.
	* Update `parse_data_response` to parse the response for the above endpoint, returning only the `sites` array from the response.
	* Update `get_datapoint_definitions` to include the new `GET:sites` endpoint in the array with `service` to `adsense`.

### Test Coverage
* Add tests for the new endpoint.

## QA Brief
* Make a request to `/wp-json/google-site-kit/v1/modules/adsense/data/sites?accountID=<accountID>` where `accountID` is a valid account ID and see if the endpoint returns data.
* Make another request to the same URL but without `accountID` URL param and check if the response returns an error.

## Changelog entry

* Add a new datapoint to the AdSense module that returns information about sites associated with the current accountID.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
### QA:Eng Verified ✅ 
------------------------
 - Make a request to /wp-json/google-site-kit/v1/modules/adsense/data/sites?accountID=<accountID> where accountID is a valid account ID and see if the endpoint returns data.
 - Make another request to the same URL but without accountID URL param and check if the response returns an error.
