### ISSUE TITLE
Add constants for new AdSense statuses

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4755]
As part of the enhanced AdSense setup flow, a few new account and site statuses will be introduced. This issue is for scaffolding all of them.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Constants for the new AdSense account and site statuses should be added, together with the existing AdSense account and site status constants. For both account and site statuses, all statuses should be separated into three groups, each annotated with a comment (see below).
* Details on account statuses:
    * The following new account statuses should be added and annotated with a comment `V2 setup flow.`:
        * `ACCOUNT_STATUS_PENDING_TASKS`
    * The following existing account statuses should be moved together, annotated with a comment `V1 setup flow.`:
        * `ACCOUNT_STATUS_DISAPPROVED`
        * `ACCOUNT_STATUS_GRAYLISTED`
        * `ACCOUNT_STATUS_PENDING`
    * All other existing account statuses should remain together and be annotated with a comment `V1 and V2 setup flow.`.
* Details on site statuses:
    * The following new site statuses should be added and annotated with a comment `V2 setup flow.`:
        * `SITE_STATUS_NEEDS_ATTENTION`
        * `SITE_STATUS_REQUIRES_REVIEW`
        * `SITE_STATUS_GETTING_READY`
        * `SITE_STATUS_READY`
        * `SITE_STATUS_READY_NO_AUTO_ADS`
    * The following existing site status should be moved into its own "group", annotated with a comment `V1 setup flow.`:
        * `SITE_STATUS_ADDED`
    * All other existing site statuses should remain together and be annotated with a comment `V1 and V2 setup flow.`.

## Implementation Brief
* Using `assets/js/modules/adsense/util/status.js`, add the statuses as per the AC.

### Test Coverage
* No new tests to be added.

## QA Brief

**QA:Eng**
- Verify the new constants are added with the comments as described in the AC
- Verify the existing constants are grouped with the comments as described in the AC

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by asvinb** [comment]
### QA: ✔️ 

* Statuses added and comments added as per AC.
