### ISSUE TITLE
Implement datastore infrastructure to get AdSense site information

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4756]
#4754 introduces a new REST data point to get information about AdSense sites, to facilitate the enhanced AdSense setup flow. This issue is about implementing the related JS datastore infrastructure.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/adsense` datastore should receive a new selector `getSites( accountID )` that calls the `GET:sites` REST data point added in #4754.
* The `modules/adsense` datastore should also receive a selector `getSite( accountID, domain )` that calls the above `getSites` selector and attempts to find the site for the given domain in there (using lower-case comparison, similar to the existing `determineSiteStatus` utility function). The endpoint should return the site or `null` (or `undefined` if still waiting for an API response of course).
* The `modules/adsense` datastore should also receive a selector `getCurrentSite( accountID )` that calls the above `getSite` with the domain extracted from the current site URL. It can simply pass through the result.
* The `modules/adsense` datastore should also receive an action `resetSites()` that resets any already retrieved sites in the datastore (so that the next time when calling `getSites` the API request would be triggered again).

## Implementation Brief
* Create `assets/js/modules/adsense/datastore/sites.js` which will contain the sites data store partial.
* It should take most of the code from `assets/js/modules/adsense/datastore/clients.js` with the following changes:
	* The `baseInitialState` should be an object containing a `sites` property which itself is an empty object.
	* The `baseName` should be `getSites`.
	* GET API Requests should be made to `modules/adsense/sites`.
	* In the `reducerCallback` spread the response (`sites`) into the `sites[accountID]` property of the `baseInitialState`.
	* Rename `resetClients` to `resetSites` action and follow the same logic to reset the `sites` property.
	* Rename `getClients` resolver to `getSites` and follow the same logic to retrieve the sites.
	* There must be the following selectors (refer to AC for more details for each):
		* `getSites` with `accountID` as parameter.
		* `getSite` with `accountID` and `domain` as parameters.
			* It should use the `getSites` selector to get all the sites and match the site with the `domain`. A new function `determineSiteFromDomain` can be added to `assets/js/modules/adsense/util/site.js` which does that.
		* `getCurrentSite` with `accountID` as parameter.
			* It should call `getSite`, with the `accountID` and the `domain` extracted from getting the reference site URL which can be obtained by querying the `core/site` data store via the `getReferenceSiteURL` selector.

### Test Coverage
* Add tests for the new sites data store partial.

### QA Eng
* Make sure the added code meets the AC and the tests are sufficient and passing.
* Using oi.ie, test the new selectors in the console.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
## QA Verified ✅ 

- Verified the added code meets the AC and the tests are sufficient and passing.
- Verified the new selectors in the console using `oi.ie`.
