### ISSUE TITLE
Scaffold (logic for) new AdSense setup main components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4758]
In the enhanced AdSense setup flow, the account status and site status are no longer determined by a single complex function. Instead, this is now handled directly within the components. This issue is about scaffolding the higher level components and their logic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following AdSense setup components should be created, in a separate directory `assets/js/modules/adsense/components/setup/v2/`:
    * `SetupMain`
    * `SetupCreateAccount`
    * `SetupSelectAccount`
    * `SetupAccount` (with required prop `account`, like the [account API object, including our tweaks to e.g. include `_id`](https://developers.google.com/adsense/management/reference/rest/v2/accounts#Account))
* In the AdSense module registration in JS, _if_ the `adsenseSetupV2` feature flag is enabled, the _new_ (V2) `SetupMain` (see below) should be registered as the module setup component instead of the previously existing one.
* The new `SetupMain` component should be implemented with logic as follows:
    * It needs to get the current account ID setting value (see `getAccountID` selector).
    * It needs to call the `getAccounts` selector of the module.
        * If `undefined`, it should return a `ProgressBar`.
        * Otherwise, it should return the same DOM structure present in the existing (V1) AdSense `SetupMain`, with the `viewComponent` as follows:
            * If there are no accounts, it should return the above `SetupCreateAccount` component.
            * If there are multiple accounts _and_ there is no current account ID set, it should return the above `SetupSelectAccount` component.
            * Otherwise, it should return the above `SetupAccount` component, passing the prop to it.
    * A number of `useEffect` hooks should be added, mostly taken over from the existing (V1) AdSense `SetupMain` component:
        * The entire "background submit" logic should be taken over. With one major difference:
            * The `isAwaitingBackgroundSubmit` flag should be set anytime that either the `accountID`, `clientID`, `accountStatus`, or `siteStatus` setting changes compared to its currently saved value from the server (and only if the new value is not `undefined`).
        * A new `useEffect` to conditionally set the `accountID` setting on-the-fly should be added:
            * If there is only one account in the returned list from the API and no `accountID` is set yet.
            * Or if there is only one account in the returned list from the API but it does not include the currently set `accountID`.
        * A new `useEffect` to conditionally set the `accountStatus` setting on-the-fly should be added:
            * If there are no accounts in the API response, it should be set to `ACCOUNT_STATUS_NONE`.
            * If there are multiple accounts in the API response and no `accountID` set yet, it should be set to `ACCOUNT_STATUS_MULTIPLE`.
            * Otherwise (i.e. one account can be identified), it should be set to `ACCOUNT_STATUS_NO_CLIENT` (for now).
        * The entire "refresh on re-focus" logic should be taken over, with the addition of also calling the `resetSites()` action from #4756.
        * The two `useEffect`s for sending tracking events for the account status and site status changes should be taken over (i.e. the component also has to get the current value of those two module settings). One major difference:
            * Instead of `receive_account_status`, `receive_account_state` should be used for the event name.
            * Instead of `receive_site_status`, `receive_site_state` should be used for the event name.
            * This is just to later clearly differentiate V1 from V2 behavior in Analytics.
* The new `SetupCreateAccount` should be scaffolded to simply return an **untranslated** string (e.g. in a div) `TODO: UI to create new account`.
* The new `SetupSelectAccount` should be scaffolded to simply return an **untranslated** string (e.g. in a div) `TODO: UI to select account`.
* The new `SetupAccount` should be scaffolded to simply return an **untranslated** string (e.g. in a div) `TODO: UI to proceed with steps for account {accountID}` (using the `_id` from the `account` prop).
* Storybook stories for `SetupMain` in the above three alternate variants should be added.

## Implementation Brief
* Create the following files in `assets/js/modules/adsense/components/setup/v2/` which export a functional component having the same filename.
	* `SetupMain`
	* `SetupCreateAccount`
	* `SetupSelectAccount`
	* `SetupAccount`
* Using `assets/js/modules/adsense/index.js`,
	* Import the `SetupMain` component from `assets/js/modules/adsense/components/setup/v2/` and set it to be the value for `SetupComponent` if the `adsenseSetupV2` flag is enabled.
	* If the feature flag is not enabled, the `SetupComponent` should be set to the current `SetupMain` component from `assets/js/modules/adsense/components/setup/SetupMain.js`.
		* TO check if the feature flag is enabled, use the `useFeature` hook.
* For the following components, return the string as per the AC:
	* `assets/js/modules/adsense/components/setup/v2/SetupCreateAccount`
	* `assets/js/modules/adsense/components/setup/v2/SetupSelectAccount`
	* `assets/js/modules/adsense/components/setup/v2/SetupAccount`
* Using `assets/js/modules/adsense/components/setup/v2/SetupMain`,
	* It should return the same markup as the `SetupMain` component from `assets/js/modules/adsense/components/setup/SetupMain.js` including the `AdBlockerWarning` widget and the logic associated with it.
	* It should get the accounts via the `getAccounts` selector.
		* If `getAccounts` returns `undefined`, return the `ProgressBar` component.
	* It should get the account ID via the `getAccountID` selector.
	* The `viewComponent` (taken over from the original `SetupMain`) should be set to the following values based on the conditions below:
		* `SetupCreateAccount` if there are no accounts.
		* `SetupSelectAccount` if there is no account ID.
		* `SetupAccount` by default, passing the account as prop.
	* The entire "background submit" logic should be taken over from `assets/js/modules/adsense/components/setup/SetupMain.js` with the following difference:
		* The `isAwaitingBackgroundSubmit` state variable should be set anytime that either the `accountID`, `clientID`, `accountStatus`, or `siteStatus` setting changes compared to its currently saved value from the server (and only if the new value is not `undefined`). The same logic to get those values should be used. For e.g use:
			* `determineClientID` for `clientID`
			* `determineAccountStatus` for `accountStatus`
			* `determineSiteStatus` for `siteStatus`
	* A new `useEffect` to conditionally set the `accountID` (via dispatching the `setAccountID` action) setting on-the-fly should be added:
		* If `accounts` contains only 1 account and no `accountID` is set yet.
		* Or if there is only one account in `accounts` but it does not include the currently set `accountID`.
	* A new `useEffect` to conditionally set the `accountStatus` (via dispatching the `setAccountStatus` action) setting on-the-fly should be added:
		* If `accounts` is empty, it should be set to `ACCOUNT_STATUS_NONE`.
		* If `accounts` has multiple accounts and no `accountID` set yet, it should be set to `ACCOUNT_STATUS_MULTIPLE`.
		* Otherwise (i.e. one account can be identified), it should be set to `ACCOUNT_STATUS_NO_CLIENT`.
		* The above constants should be imported from `assets/js/modules/adsense/util/status.js`.
	* The logic to reset all fetched data when user re-focuses tab should be copied over from `assets/js/modules/adsense/components/setup/SetupMain.js` with a small addition where the `resetSites` action should be dispatched as well along with the other `reset*` actions.
	* The `trackEvent` calls should be carried over as well but with a different event name, as per the AC.
* Create `assets/js/modules/adsense/components/setup/v2/SetupMain.stories.js` which contains the 3 variants above, i.e where `SetupCreateAccount`, `SetupSelectAccount`, and `SetupAccount` are the components are being displayed.

### Test Coverage
* No new tests to be added.

## QA Brief
* Check if the stories render their appropriate components.
* Check if `SetupMain` was implemented as per the AC.

## Changelog entry

* N/A

**Comment by hussain-t** [comment]
## QA Verified ✅ 

- Verified the stories render their appropriate components.
- Verified `SetupMain` component was implemented as per the AC.
