### ISSUE TITLE
Google Analytics Connection Loading

### ISSUE THREAD

**Issue by abhimhasagar** [google/site-kit-wp#476]
## Bug Description
While Connecting to the google analytics, its asking for all permission then, after allow them, its showing loading sign, seems to permanent sign

## Additional Context

 - PHP Version: 7.3
 - Plugin Version [e.g. 22] Google SItekit

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@abhimhasagar There are similar issues reported in #386, with some suggested steps. If you want to look at that issue, or share your [Site Health information](https://i.imgur.com/Rtkmsba.png) here I can see if I spot anything.

**Comment by abhimhasagar** [comment]
@jamesozzie  ok got it
