### ISSUE TITLE
Scaffold (logic for) new AdSense setup site components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4760]
Following the scaffolded main components from #4758 and the scaffolded account components from #4759, this is the last component scaffolding issue, which focuses on adding the logic for an (already created/selected) site ("site" as in an AdSense site, which is an entity that has to be configured in the AdSense UI, within an AdSense account).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupAccountSite` component introduced in #4759 should be implemented with logic as follows (replacing the dummy content that is currently in there):
    * The component should receive logic to return (still dummy) content that is more specific to the current status of the site:
        * If the given `site.state` is `NEEDS_ATTENTION`, it should return an **untranslated** string `TODO: UI to inform that site {domain} (in account {accountID}) needs attention`.
        * If the given `site.state` is `REQUIRES_REVIEW`, it should return an **untranslated** string `TODO: UI to inform that site {domain} (in account {accountID}) requires review`.
        * If the given `site.state` is `GETTING_READY`, it should return an **untranslated** string `TODO: UI to inform that site {domain} (in account {accountID}) is getting ready`.
        * If the given `site.state` is `READY` and `site.auto_ads_enabled` is `false`, it should return an **untranslated** string `TODO: UI to inform that site {domain} (in account {accountID}) is ready, with auto ads disabled`.
        * If the given `site.state` is `READY` and `site.auto_ads_enabled` is `true` (i.e. otherwise), it should return an **untranslated** string `TODO: UI to inform that site {domain} (in account {accountID}) is ready, with auto ads enabled`.
    * A new `useEffect` to conditionally set the `siteStatus` setting on-the-fly should be added:
        * Based on the same conditions that are also used above, it should be set to one of the following constants:
            * `SITE_STATUS_NEEDS_ATTENTION`
            * `SITE_STATUS_REQUIRES_REVIEW`
            * `SITE_STATUS_GETTING_READY`
            * `SITE_STATUS_READY_NO_AUTO_ADS`
            * `SITE_STATUS_READY`
    * For the two cases where `site.state` is `READY` (see above), the returned `TODO: ...` sentence should be accompanied by a button which allows to complete the AdSense setup:
        * The button doesn't need to have any specific styling, but it should follow the code in the existing (V1) `SetupSiteAdded` component.
        * The button should have a similar handler like the one in that existing (V1) `SetupSiteAdded` component:
            * It should `completeSiteSetup`, but also `completeAccountSetup`.
            * On success, it should call `finishSetup` (this will need to be passed through to the component as extra prop).
* A tiny but important tweak should be made to the `SetupAccount` component introduced in #4758 and #4759:
    * In the `useEffect` to update the `siteStatus` setting on-the-fly, the entire condition for setting it to `SITE_STATUS_NEEDS_ATTENTION` should be removed, as that was just temporary and is now surpassed by the above logic in `SetupAccountSite`.
* Storybook stories for `SetupMain` in the above five alternate variants should be added.
    * They can replace (or basically iterate on) the one story for `SetupAccountSite` that was added as part of #4759.
    * In other words, after this we should have 10 stories in total for `SetupMain`.

## Implementation Brief
* Using `assets/js/modules/adsense/components/setup/v2/SetupAccountSite`,
	* It accepts the following props:
		* `account`
		* `site`
		* `finishSetup` new prop (function) to be added.
	* Return the appropriate dummy string as per the AC.
	* The constants used in the AC, for e.g `NEEDS_ATTENTION` should be imported from `assets/js/modules/adsense/util/status.js`.
	* A new `useEffect` to conditionally set the `siteStatus` (via dispatching the `setSiteStatus` action) setting on-the-fly should be added as per the AC using the same conditions to render the dummy strings. This should be applied only if `site.state` is either `NEEDS_ATTENTION` or `REQUIRES_REVIEW` or `GETTING_READY`.
	* If `site.status` is `SITE_STATUS_READY_NO_AUTO_ADS` or `READY`, append a button (`Button` component) to complete the setup for AdSense. The code to complete the setup can be copied over from `assets/js/modules/adsense/components/setup/SetupSiteAdded.js`, namely the `continueHandler` function with the following tweaks:
		* `completeAccountSetup` should be called as well after `completeSiteSetup` is called.
		* If both calls are successes, then call `finishSetup`.
* Using `assets/js/modules/adsense/components/setup/v2/SetupAccount`,
	* In the `useEffect` to update the `siteStatus` setting on-the-fly, the entire condition for setting it to `SITE_STATUS_NEEDS_ATTENTION` should be removed. Refer to AC for more details to as why.
* Update `assets/js/modules/adsense/components/setup/v2/SetupMain.stories.js` to include stories for the above variants where the appropriate components based on the site status are rendered.

### Test Coverage
* No new tests to be added.

## QA Brief
* Ensure stories are added and render correctly as per the AC.

## Changelog entry

* N/A.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
## QA Verified ✅ 

- Verified stories are added and rendered correctly as per the AC.
