### ISSUE TITLE
Implement modified snippet toggle component for enhanced AdSense setup flow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4761]
In the enhanced AdSense setup, the snippet switch will only be displayed if there is either an existing tag or if for whatever other reason the AdSense snippet is disabled. This issue is about introducing an alternate component to be used in that setup, which handles the additional logic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new selector (and related infrastructure) `getOriginalUseSnippet()` should be introduced to the `modules/adsense` datastore.
    * It should be similar to the existing `getOriginalAccountStatus()` selector in that it always returns the original value of the `useSnippet` setting that was present "on page load" (i.e. the first non-`undefined` value loaded for the setting).
    * It should follow the same implementation used for `getOriginalAccountStatus()`.
* A new component `SetupUseSnippetSwitch` should be introduced in `assets/js/modules/adsense/components/setup/v2/`:
    * It should return nothing (`null`) if the original `useSnippet` setting value (using new selector above) is `true` _and_ there is no existing tag.
        * In other words, it should only show the toggle if either the `useSnippet` setting is off or there is an existing tag.
    * It should also return nothing (`null`) if one of the two values above are still loading (i.e. `undefined`).
    * Otherwise, it should display the `UseSnippetSwitch` component, with auto-saving on change enabled, and with the following messages for when the checkbox is deactivated (i.e. when `useSnippet` is `false`):
        * If there is no existing tag: no message at all
        * If there is an existing tag for the same client ID: _You’ve already got an AdSense code on your site for this account. We recommend you use Site Kit to place the code to get the most out of AdSense._
        * If there is an existing tag for any other client ID: _Site Kit detected AdSense code for a different account pub-123456789 on your site. In order to configure AdSense for your current account pub-987654321, we recommend you use Site Kit to place the code instead._
            * In the `pub-...` references, use the account ID extracted from the existing tag (see `parseAccountID`) and the current account ID respectively.
    * If the user activates the checkbox, any of the above messaging should be followed with an additional sentence: _Make sure to remove the existing AdSense code to avoid conflicts with the code placed by Site Kit._
        * In other words, for the scenario where there is no existing tag, that sentence would be the full message, while in the other two scenarios it would be appended to the rest of the message.
    * The component should also include a `useEffect` that, if an existing tag was found, sets the `useSnippet` setting to `false` and saves it right away (unless of course that setting was already set to `false` before).
        * This should run as soon as any existing tag has been found (i.e. no longer `undefined`) and then not run again, i.e. it shouldn't affect anything the user does with the checkbox.
* Storybook coverage for the new component should be included, for the following scenarios:
    * Existing tag with same client ID
    * Existing tag with different client ID
    * No existing tag (but `useSnippet` was originally `false`)

## Implementation Brief
* Using `assets/js/modules/adsense/datastore/settings.js`,
	* Add a new selector: `getOriginalUseSnippet` which returns `state.useSnippet`
	* Add corresponding resolver which follows the same logic as `getOriginalAccountStatus` with the following differences:
		* Instead of calling `getOriginalAccountStatus`, call the newly added selector: `getOriginalUseSnippet`
* Create `assets/js/modules/adsense/components/setup/v2/SetupUseSnippetSwitch.js` which exports the `SetupUseSnippetSwitch` functional component.
	* It should return `null` if the result of the `getOriginalUseSnippet` selector is `true` and there is no existing tag (via the `getExistingTag` selector) or if both results are `undefined`.
	* It should render the `assets/js/modules/adsense/components/common/UseSnippetSwitch` component if the above conditions are not met with the following props:
		* `saveOnChange` set to `true`
		* if `getExistingTag` returns `true` for the same client ID, refer to the AC for the copy, under "If there is an existing tag for the same client ID" as value for the `checkedMessage` prop.
			* To check if the tag is for the same client ID, query the `AdSense` data store via the `getClientID` selector and check if it's equal to the tag. An example can be found in `assets/js/modules/adsense/components/settings/SettingsForm.js`
		* If there's an existing tag but the `clientID` does not match, set the `checkedMessage` prop to the copy as in per the AC, for If there is an existing tag for any other client ID"
			* Use the `parseAccountID` utility function to extract the account ID to be used within the copy.
		* Refer to the AC to add an additional line of text when the user activates the checkbox. We can check the value returned from the `getUseSnippet` selector.
	* Use the `useEffectOnce` hook from `react-use` to check if there is an existing tag to set `useSnippet` to `false` by dispatching the `setUseSnippet` action.
* Add stories in `assets/js/modules/adsense/components/setup/v2/SetupUseSnippetSwitch.stories.js` which includes the above scenarios.

### Test Coverage
* Add tests for the new selector.

## QA Brief

**QA:Eng**
- Verify the changes met AC and IB
- Verify the stories for `SetupUseSnippetSwitch` component is good enough and covers all the scenarios 
- Verify the unit tests for `getOriginalUseSnippet` selector and action are good enough and are passing

## Changelog entry

* Implement modified snippet toggle component for enhanced AdSense setup flow.

**Comment by tofumatt** [comment]
IB ✅

**Comment by asvinb** [comment]
LGTM
