### ISSUE TITLE
Remove `adsenseSetupV2` feature flag and phase out old code

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4765]
This issue is about removing the `adsenseSetupV2` feature flag at some point, later in the future once the module has been launched and rolled out to 100% of sites. This will also allow us to delete a bunch of then unused code.

This is related to the #4447 epic, but does not belong to it, since this issue can only be worked some time after launch.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Everywhere that a conditional check for the `adsenseSetupV2` feature flag is present, remove the condition and the respective other code path (i.e. when the condition is `false`).
* Any now unused AdSense components (primarily those in `assets/js/modules/adsense/components/setup/`, except those in the `v2` directory of course) should be removed.
* All components in `assets/js/modules/adsense/components/setup/v2/` should be moved one directory up, into `assets/js/modules/adsense/components/setup/`, then the `v2` directory should be deleted.
    * All references need to be updated accordingly of course.
* Any now unused AdSense utility functions (especially all the "status" functions) should be removed.
* Any now unused AdSense datastore selectors (e.g. `getServiceAccountSiteURL`) should be removed.
* Any unused account and site status constants should be removed. Note that most of the V1 constants are used for status migration routine thus cannot be removed. 

## Implementation Brief

* Files to remove feature flag from:
  * `assets/js/modules/adsense/index.js`
  * `assets/js/modules/adsense/components/common/ErrorNotices.js`
  * `assets/js/modules/adsense/components/module/ModuleOverviewWidget/index.js`
  * `assets/js/modules/adsense/components/settings/SettingsView.js`
  * `assets/js/modules/adsense/datastore/service.js`
  * `feature-flags.json`
* Remove `getSiteStatusLinkLabel` helper function in `assets/js/modules/adsense/components/settings/utils.js`
* Do not remove constants from `assets/js/modules/adsense/util/status.js`, as they are used in `legacyAccountStatuses` to determine if migration should be done in `assets/js/modules/adsense/components/module/ModuleOverviewWidget/StatusMigration.js`

#### Replace old `V1` files with `V2` files
* Remove files in `assets/js/modules/adsense/components/setup/` (except from anything from `V2` folder):
  * `index.js` and it's imports, which includes:
    * Several `SetupAccount***.js` 
    * `SetupMain.js`
    * `SetupSiteAdd.js`
    * `SetupSiteAdded.js`
    * `utils.js`
* Move files and folders from `assets/js/modules/adsense/components/setup/v2/` one level up, update the paths, and remove `V2` foolder
* `SetupMainV2` in `assets/js/modules/adsense/index.js` will be only setup file after feature flag removal and `V2` folder move, so rename it to `SetupMain`
* Remove `V2` text from [document description](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/assets/js/modules/adsense/components/setup/v2/SetupMain.stories.js#L2)

#### Datastore and util functions
* Remove `determineAccountStatus`, `determineAccountID`, `determineSiteStatus` and `determineClientID` from `assets/js/modules/adsense/util/status.js`
* Remove `getOriginalAccountStatus` selector and resolver from:
  * `assets/js/modules/adsense/datastore/settings.js`
* Remove `getServiceAccountSiteURL` from `assets/js/modules/adsense/datastore/service.js`
* `alerts` store seems to be only used in `V1` (beside having `receiveGetAlerts` in `V2` stories file, but it does nothing as it is not used anywhere in `V2` files), so it can be removed `assets/js/modules/adsense/datastore/alerts.js`
  * Delete alerts [route response](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/includes/Modules/AdSense.php#L506-L507) as well, and the [definition](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/includes/Modules/AdSense.php#L281)
* Delete `assets/js/modules/adsense/datastore/urlchannels.js` as it seems it is only used with `V1` as well (beside `receiveGetURLChannels` being present in `V2` stories, which does nothing, like `alerts`)
  * And the [route response](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/includes/Modules/AdSense.php#L527-L528)
  * As well as [route definition](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/includes/Modules/AdSense.php#L290)

### Test Coverage

* Remove feature flag from 
  * `assets/js/modules/adsense/components/setup/v2/SetupMain.stories.js`
  * `stories/module-adsense-components.stories.js`
  * Check if other stories might need re-work
  * Update any failing VRT reference images
* From `assets/js/modules/adsense/util/status.test.js`, remove:
  * `determineAccountStatus`, `determineAccountID`, `determineSiteStatus` and `determineClientID`  functions and it's usage
  * Selector - `getOriginalAccountStatus` and it's usage
* Delete `assets/js/modules/adsense/datastore/alerts.test.js` as `alerts` store is also deleted
  * And the usage [here](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/assets/js/modules/adsense/components/setup/v2/SetupMain.stories.js#L95) which is not doing anything in `V2` setup
* Delete `assets/js/modules/adsense/datastore/urlchannels.test.js`
  * And `urlchannels` store usage in this stories [here](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/assets/js/modules/adsense/components/setup/v2/SetupMain.stories.js#L102-L107) as it does nothing
* Delete old setup stories `stories/module-adsense-setup.stories.js`
* Update any failing jest test

## QA Brief

* Go through the AdSense setup and adsense widgets in the Monetization section on the dashboard and make sure everything is working properly and there's no regression. 

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 @FlicHollis Just to clarify here, while this already has ACs and relates to the AdSense setup improvements epic, it should not be worked on at this point - this issue for some time after launch.

**Comment by aaemnnosttv** [comment]
@felixarntz I think this one can be resumed now that we've been rolled out to 100% for some time now?

**Comment by felixarntz** [comment]
@aaemnnosttv Yeah, was thinking about that the other day, didn't remember we already had an issue :)

**Comment by kuasha420** [comment]
@aaemnnosttv We can pick this one back up now. However, we need to keep some of the V1 constants and things since those are used for the migration. Cheers.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified AdSense setup and functionality.
- Verified ABR functionality. 
- Verified monetization section.
- No regression found and AdSense functionality working as expected.
