### ISSUE TITLE
Remove remaining GA legacy event for AdSense

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4766]
There's still one legacy GA event for AdSense being sent, which should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `complete_adsense_setup` GA event in the AdSense setup flow should be removed as it's already covered by a newer higher-level event.

## Implementation Brief

- Remove the following line from `assets/js/modules/adsense/components/setup/SetupSiteAdded.js` and the associated import:
https://github.com/google/site-kit-wp/blob/5f3288819b42c21d0f5cbcc9c48bf8c0fdb46abc/assets/js/modules/adsense/components/setup/SetupSiteAdded.js#L54
* Review and merge #4796 

### Test Coverage

* No new tests required.

## QA Brief

- Switch On the Google Analytics Debug Chrome Extension and set the Console to "Preserve Log" as the component being tested will redirect quickly.
- Complete the setup for connecting SiteKit to AdSense (preferably using oi.ie as the Site URL in the Developer plugin) so that the setup is successful.
- After the last step, ensure the `complete_adsense_setup` event is NOT fired. 
<img width="1402" alt="Screenshot 2022-02-05 at 17 25 13" src="https://user-images.githubusercontent.com/1721319/152652259-44368eac-91ca-43f9-9baa-c9016576b328.png">

## Changelog entry

* Remove legacy Analytics event for AdSense users.

**Comment by eugene-manuilov** [comment]
Thanks, @jimmymadon. IB ✔️. However, I noticed that you have already created a PR that implements IB. Please, try to not do it in the future because we strongly discourage working on a ticket before IB is approved and before the ticket is added to the current sprint.

**Comment by jimmymadon** [comment]
@eugene-manuilov When I recently read the IB guidelines, it mentioned that for very trivial changes, it might be more efficient to include a PR and QAB. Since this was a one line change which I had to check anyways for the IB, I thought I'd include the PR - but I will avoid this in the future.
