### ISSUE TITLE
Entity dashboard header background color is slightly off with alternate color schemes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4769]
## Bug Description

When using an alternate color scheme in WP Admin, the background color of the entity dashboard header is _very slightly_ off from the WP dashboard background color which uses the default background color of the wp-admin body.

![image](https://user-images.githubusercontent.com/1621608/152120052-cbb15d4d-75dd-4799-8040-be1f5cce99d9.png)

![image](https://user-images.githubusercontent.com/1621608/152119188-6ca204ff-2c58-4701-a3d2-5139a9aac1cc.png)

Most alternate color schemes use a body background color of #f1f1f1 instead of the default #f0f0f1 which is approximately a 1% difference but is still noticeable.

The easiest solution here is to only set the background color on the entity header when sticky as it will also have an added shadow which makes it more/less impossible to see the colors are different.

## Steps to reproduce

1. Set an alternate color scheme for WP admin via the user profile (e.g Modern)
2. Visit the SK entity dashboard
3. See color mismatch when the header is not sticky (scrolled to the top of the screen)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The entity dashboard header's background color should only be set when the header is sticky

## Implementation Brief
* Using `assets/sass/components/global/_googlesitekit-entity-header.scss`,
	* Update the styles for `.googlesitekit-entity-header` to have the `background-color` set to `transparent`.
* Using `assets/sass/components/global/_googlesitekit-dashboard-navigation.scss`,
	* Update the style for `.googlesitekit-navigation--is-sticky + .googlesitekit-entity-header` :
		* to set the `background-color` to `#f1f1f1` (new SASS variable to be created if non existent)
		* include the `background-color` property in the `transition` declaration

### Test Coverage
* N/A

## QA Brief

* Follow the first two steps of the "Steps to reproduce" section mentioned above.
* Make sure the color mismatch mentioned in the issue is no longer visible.
* If double-checking with developer tools, make sure the entity header's background color stays `transparent` until the page is scrolled and the header becomes sticky.

## Changelog entry

* Fix single-page dashboard header background colour when using a non-default WordPress admin color scheme.

**Comment by aaemnnosttv** [comment]
cc: @felixarntz

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- I was able to recreate the initial issue following the  "Steps to reproduce" 
- When I refreshed the develop branch, the color mismatch mentioned in the issue is no longer visible.
- The entity header's background color stays transparent until the page is scrolled and the header becomes sticky.

![image](https://user-images.githubusercontent.com/73545194/173775672-9626b54e-7176-484f-9a75-5596efae6e44.png)
