### ISSUE TITLE
All traffic widget only shows tooltip when hovering line

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4770]
## Feature Description

Most charts in Site Kit show additional data when hovering the chart, including a vertical line and tooltip. In the All Traffic widget, the tooltip is only shown when hovering the line itself, which is unintuitive.

https://user-images.githubusercontent.com/1621608/152122582-9ab9b6e6-c38c-47d4-8338-b818dd2086bc.mp4

Compared to other charts which show a line and highlight the values on the hovered x-axis of the mouse

![image](https://user-images.githubusercontent.com/1621608/152123122-c2e6a499-da7a-41e3-8c77-b86959f59d7c.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The All Traffic Widget's User Count Graph should display a vertical line and tooltip to display the number of users on a given date when the mouse is hovered anywhere within the chart area.

## Implementation Brief

* In the [DashboardAllTrafficWidgetGA4\UserCountGraph.js ](https://github.com/google/site-kit-wp/blob/782fcdcc7a49c72a41242948b50f1a453990c4a7/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js)
  * Add `focusTarget: 'category' to the `UserCountGraph.chartOptions` object. This ensures the nearest tooltip and crosshair show up when hovering over chart instead of only showing up when hovering a single data point.
  https://github.com/google/site-kit-wp/blob/782fcdcc7a49c72a41242948b50f1a453990c4a7/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js#L261
  * Add `trigger: 'both'` to the `UserCountGraph.chartOptions.crosshair` object. This ensures the crosshair (vertical line) is shown on hover and on click.
  https://github.com/google/site-kit-wp/blob/782fcdcc7a49c72a41242948b50f1a453990c4a7/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js#L315-L319

### Test Coverage

* No tests need to be updated.

## QA Brief

* Ensure the Analytics module is connected.
* Go to the Site Kit dashboard and verify the All Visitors graph displays a tooltip when hovering.
* Verify the tooltip shows the number of users on a given date.

## Changelog entry

* Update the All Traffic widget to show tooltip when hovering over the users chart.

**Comment by tofumatt** [comment]
(Just a note: I thought this _could_ be because this chart uses the "smoothed out" curve variant, but looks like other charts that have the nice hover effect also have a curve line, so that's not it. Seems we just aren't including the right values for that chart to get the hover effect.)

**Comment by bethanylang** [comment]
@tofumatt Checking in here on if we can move forward or if you want to unassign so someone else can pick up, thanks!

**Comment by tofumatt** [comment]
Going to unassign this for now as it's low-priority. 👍🏻

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that The All Traffic Widget's User Count Graph display a vertical line and tooltip to display the number of users on a given date when the mouse is hovered anywhere within the chart area.
- Also, verified when All traffic widget is in zero data state and tooltip and vertical line showing when widget is in zero data state.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/fd3fed08-779b-4272-84d4-41d1ae401eb3)

![image](https://github.com/google/site-kit-wp/assets/94359491/f956c819-324f-4d75-815b-5b58b90a6d06)


https://github.com/google/site-kit-wp/assets/94359491/8e592f52-25cf-4249-b5a8-c8e975ed0b93

</details>
