### ISSUE TITLE
Allow testing tags in non-production environments

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4774]
## Feature Description

In #2054, we added a guard to prevent module tags from being placed in non-production environments to tracking page views, displaying ads, etc in such environments. There are however cases where it makes sense for a developer to want these tags to be rendered in a local/development/staging environment in order to test integration with them (e.g. custom Analytics events).

With this in mind, we should allow for a developer to disable/bypass the environment type guard for tags.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Tag_Production_Guard` tag guard should be replaced with a new `Tag_Environment_Type_Guard` which works similar to the current production guard, but allows for flexibility in the environments it disables tags for
* Like today, if the `wp_get_environment_type` function does not exist, it should continue to return `true`
* A new filter should be invoked to allow filtering the allowed environment types:
    *  `googlesitekit_allowed_tag_environment_types` which filters an array of valid environment types which should initially be only `production` as today
* The `can_activate` method should return `true` if the current environment type is in the filtered array 
* The `Tag_Production_Guard` class should be removed and its usage replaced with the new `Tag_Environment_Type_Guard`

## Implementation Brief

* Copy the `Tag_Production_Guard` class to a new class named `Tag_Environment_Type_Guard`. It should implement the same `Guard_Interface`.
* Within the `can_activate()` method, use `apply_filters()` with the hook name to be `googlesitekit_allowed_tag_environment_types`. Pass an array with the value `production` as the value to filter.
* Implement the remaining points within the AC which provide enough detail.

### Test Coverage

* Rework the existing tests within `Tag_Production_GuardTest`  to test the newly created filter.

## QA Brief

- There is nothing specific to be tested for these changes. However, we must ensure that all the tags are added while setting up the modules in the production environment.

**QA:Eng**
- Add the following filter and ensure the tags are being added while setting up the modules in the `development` environment.
```php
add_filter(
	'googlesitekit_allowed_tag_environment_types',
	function ( $allowed_environments ) {
		$allowed_environments[] = 'development';
		return $allowed_environments;
	}
);
```

## Changelog entry

* Update tag placement functionality to allow using tags in non-production environments.

**Comment by aaemnnosttv** [comment]
cc: @felixarntz

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@hussain-t @aaemnnosttv 

Can you please provide more information in QAB. Like,where I can find these tags and are you referring to GA tags ?

**Comment by hussain-t** [comment]
@mohitwp, yes, you have to verify whether the GA and GTM tags are added as to how it works today.

**Comment by mohitwp** [comment]
### QA update ✅ 

**Verified:**

- Verified GA, GTM and AdSense tags.
- Compared the latest release and dev branch.
- On dev branches, tags are added same as latest release branch.

Note : Added `QA:Eng` label as mentioned in QAB.

<details>

![image](https://user-images.githubusercontent.com/94359491/176162766-d7d3c871-8385-463d-be48-3e33cc67690b.png)

![image](https://user-images.githubusercontent.com/94359491/176162786-021a02c6-4703-4935-a439-cd16f46929c8.png)

![image](https://user-images.githubusercontent.com/94359491/176162821-747a4041-6ee4-4f2d-a0b7-220982efcf34.png)

![image](https://user-images.githubusercontent.com/94359491/176162869-d3130a54-bcd5-44ef-be79-c4a97c1a4432.png)

![image](https://user-images.githubusercontent.com/94359491/176162932-42b56249-4959-49b4-b2db-ff798c2f79be.png)

![image](https://user-images.githubusercontent.com/94359491/176162975-fd05114b-0862-4f16-b461-02925ff6ff71.png)

</details>

**Comment by jimmymadon** [comment]
## QA: Eng ✅ 

- Set the WP_ENVIRONMENT_TYPE to 'development'. Verified that no tag snippets (other than AdSense meta tag snippet) are added to the site.
<img width="764" alt="Screenshot 2022-06-29 at 00 39 09" src="https://user-images.githubusercontent.com/1721319/176322270-9914a4d3-e4e0-4637-9f1d-ee4431884089.png">

- Added the filter as per the QAB to `Plugin.php`'s `register()` method. Verified that Analytics, GTM and AdSense snippets are inserted.
<img width="762" alt="Screenshot 2022-06-29 at 00 49 42" src="https://user-images.githubusercontent.com/1721319/176322938-5498929b-f2f3-4be8-9acf-84c9db0fd22c.png">
