### ISSUE TITLE
Update actions to run on PRs for feature branches

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4779]
## Feature Description

We normally use feature flags to handle long-running development rather than using a separate branch until it is ready to go. In some cases, it makes sense to use a separate, shorter-lived branch when working on a few changes that will go in all together without a feature flag.

To support this, we should update our actions to run for PRs against these feature branches as they are currently limited to PRs against `main` or `develop`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All GitHub actions that run for PRs should also run for PRs against `feature/*` branches

## Implementation Brief

Update the `on` > `pull_request` > `branches` of all Github workflows to also include `'feature/**'`. 

````yml
on:
  pull_request:
      branches:
        - develop
        - main
        - 'feature/**'
````

The workflows are located in `.github/workflows` and all of them needs to be updated accordingly. 
### Test Coverage

* 

## QA Brief

* QA:ENG:
    * Create a test feature branch off of `develop`. ie. `feature/test-branch` and push it.
    * Create another branch and do a commit and push it. 
        * Make sure changed files have some js/css and php files. 
    * Create a PR from the second branch and target the feature branch. 
    * Make sure that Actions are running. 
    * Delete the PR and test branches afterwards. 

## Changelog entry

* N/A

**Comment by asvinb** [comment]
### QA: ✅ 

Actions run when PR against `feature/*` branches are issued.
![image](https://user-images.githubusercontent.com/31818/152541311-328522ea-009a-4fc0-8b34-8aa79f8793e0.png)
