### ISSUE TITLE
Plugin activation notice may be in violation of WP guidelines

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#478]
The notice displayed on activation is very big and looks a bit out of place in the context of a WP notice element.

![localhost_8080_wp-admin_plugins php](https://user-images.githubusercontent.com/1621608/63946580-03cd7f80-ca7e-11e9-97af-c76f45c0f916.png)

The banner takes up ~25% of the screen in this screenshot and the heading and button within are larger than the `<h1>` on the page.

On non Site Kit "owned" pages, elements added should blend more with WordPress core. This quality is highlighted in the [WordPress Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#11-plugins-should-not-hijack-the-admin-dashboard) for its directory. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Personally I don't interpret the admin hijacking guideline this way, but we can sync with the plugin review team to make sure.

**Comment by felixarntz** [comment]
This is fine for now. We can always reopen if we want to modify the notice.
