### ISSUE TITLE
Refactor GitHub Actions workflows with native `concurrency` configuration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4781]
## Feature Description

> Largely borrowed from https://core.trac.wordpress.org/ticket/53080

GitHub now has a new `concurrency` key for use at the workflow and job level to ensure only a single workflow run or job is in progress. When used in combination with the `cancel-in-progress` key, incomplete workflow runs can be canceled automatically to prevent running workflows unnecessarily.

The feature is currently stable and can replace the need to rely on the 3rd party `styfle/cancel-workflow-action` action which was always less than ideal because it required the job to run to cancel other runs.

Related information:
* [Announcement post](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/)
* [Documentation for `concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)
* https://github.com/styfle/cancel-workflow-action/issues/76
* https://core.trac.wordpress.org/changeset/50930

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All GitHub actions workflows that use the `styfle/cancel-workflow-action` should be updated to use the [`concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) configuration instead to cancel previous workflow runs, essentially allowing only the latest one to run at a time

## Implementation Brief

* Delete the `styfle/cancel-workflow-action`  action from all workflow files.
* Add the following snippet to each workflow file after `on` and before `jobs` sections. Please, replace the `{filename}` placeholder with the actual file name of the workflow file without extension. For example, for the `php-tests-wp-4-7-php-5-6.yml` workflow, the group value should be `php-tests-wp-4-7-php-5-6-${{ github.ref }}`.

```
concurrency: 
  group: {filename}-${{ github.ref }}
  cancel-in-progress: true
```

### Test Coverage

* N/A

## QA Brief

**QA:Eng**
- Verify the changes met AC and IB
- Create a test PR
- While the GitHub actions are running in the PR, push some updates to PR
- Verify the running actions are stopped and restarted

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
> group: {filename}-${{ github.ref }}

@eugene-manuilov – looks like we can use `github.workflow` instead of a literal filename as shown in the example here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow 🙂 

Otherwise LGTM

**Comment by eugene-manuilov** [comment]
@aaemnnosttv, yes, I saw it, but unfortunately, the `github.workflow` value will be the same for PHP and E2E tests workflows:

https://github.com/google/site-kit-wp/blob/87ca8c305a1ab1416fb0dc88e5f3d15a51a699a2/.github/workflows/php-tests-wp-latest-php-8-0.yml#L1 https://github.com/google/site-kit-wp/blob/87ca8c305a1ab1416fb0dc88e5f3d15a51a699a2/.github/workflows/php-tests-wp-latest-multisite-php-7-4.yml#L1

https://github.com/google/site-kit-wp/blob/87ca8c305a1ab1416fb0dc88e5f3d15a51a699a2/.github/workflows/e2e-tests-wp-latest.yml#L1 https://github.com/google/site-kit-wp/blob/87ca8c305a1ab1416fb0dc88e5f3d15a51a699a2/.github/workflows/e2e-tests-wp-4-7.yml#L1

It means that the same group name will be used for both php-7.4 and php-8.0 tests. And when php-8.0 tests start, php-7.4 tests will be canceled.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov got it – I thought `github.workflow` was the file name rather than the `name`. In that case I think we could use `github.job` instead which is the job ID (the string key in the workflow file) which is more/less the same 🙂 

e.g. https://github.com/google/site-kit-wp/blob/87ca8c305a1ab1416fb0dc88e5f3d15a51a699a2/.github/workflows/php-tests-wp-latest-php-8-0.yml#L36-L37

**Comment by eugene-manuilov** [comment]
> In that case I think we could use `github.job` instead which is the job ID (the string key in the workflow file) which is more/less the same

@aaemnnosttv this won't work as well because some workflow files contain multiple jobs. For example, the `zip` workflow has 3 jobs: `build-zips`, `deploy-to-wiki`, and `remove-pr`. It means that if new changes are pushed when the current job deploys the zip file, it won't be canceled because the group name of the new run will be `build-zips-...` instead of `deploy-to-wiki-...`.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov that makes sense, thanks for clarifying.

IB ✅

**Comment by asvinb** [comment]
### QA: ✅ 

- Created test PR with changes to SASS, JS and PHP files.
- GH Actions started running.
- Updated the PR to add more changes.
- GH actions in progress stopped and new actions started.
