### ISSUE TITLE
Implement new selector for shared ownership modules

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4791]
## Feature Description

Related to shared ownership modules (see https://github.com/google/site-kit-wp/issues/4790), the `core/modules` store will be extended to make these modules selectable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `getSharedOwnershipModules` selector should be added to the `core/modules` store which should return a list of module objects (the shared ownership modules)
	- This selector should have a resolver which receives the list of shared ownership modules from the dashboard sharing data global if they haven't been received yet
* A new `receiveSharedOwnershipModules` action should be added for storing the given list of module slugs in the store's state for use by the selector
* Appropriate test coverage should be added for each

## Implementation Brief

- In `assets/js/googlesitekit/modules/datastore/modules.js`, 

- Create a resolver generator function (method) `*getSharedOwnershipModules()` with the following:
    - Call `getSharedOwnershipModules()` selector and return early if the selector returns non-undefined value.
    - Destructure `sharedOwnershipModules` from `global._googlesitekitDashboardSharing`.
    - Dispatch `receiveSharedOwnershipModules` action to set `sharedOwnershipModules` in the state.

- Create an action method `receiveSharedOwnershipModules()` with the following:
    - It should accept a parameter `sharedOwnershipModules` and it should set it in the state as `state.sharedOwnershipModules`.
    - Add `sharedOwnershipModules` in the `baseInitialState` and set `undefined` as the default value.

- Create `RECEIVE_SHARED_OWNERSHIP_MODULES` case in the `baseReducer` with the following:
    - Get `sharedOwnershipModules` from the `payload`.
    - Return `sharedOwnershipModules` along with the state.

- Create `getSharedOwnershipModules()` selector with the following:
    - Get the `modules` from the `getModules` selector.
    - Return `undefined` if the `getModules` selector is not yet loaded.
    - Return `undefined` if the `sharedOwnershipModules` is `undefined` in the state.
    - It should return the modules object that maps/matches the `sharedOwnershipModules` from the `state`.

### Test Coverage

- Add test cases for `getSharedOwnershipModules` selector and `receiveSharedOwnershipModules` action

## QA Brief

**QA**
This isn't QA-able directly in the plugin yet. For now, QA here can be a simple regression test with and without dashboard sharing enabled.

**QA:Eng**
- Ensure the `dashboardSharing` feature flag is enabled.
- In the console, run `googlesitekit.data.select('core/modules').getSharedOwnershipModules()`
- Ensure it returns the expected modules.
- Disable the `dashboardSharing` feature flag and run `googlesitekit.data.select('core/modules').getSharedOwnershipModules()`
- Ensure it returns `undefined` and the console error `Could not load core/modules dashboard sharing`.

## Changelog entry

* Implement new selector for shared ownership modules.

**Comment by eugene-manuilov** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_With `dashboardSharing` feature flag enabled:_

- When I run `googlesitekit.data.select('core/modules').getSharedOwnershipModules()` in the console, it returns the expected modules. PSI and Idea Hub

_With `dashboardSharing` disabled:_

- When I run `googlesitekit.data.select('core/modules').getSharedOwnershipModules()` it returns undefined and the console error `Could not load core/modules dashboard sharing`.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/170957749-62e56b34-9f74-41d1-8f5d-fad1b6836f53.png)
![image](https://user-images.githubusercontent.com/73545194/170957771-dacb873c-5b52-4227-bf30-03fa6549164a.png)

</details>
