### ISSUE TITLE
Clicking the Site Kit logo within the header of DashboardEntityApp should redirect user to the main dashboard.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#4793]
## Feature Description
When the user is on the entity dashboard (with the `unifiedDashboard` feature flag set), another intuitive way of getting back to the main dashboard is by clicking on the Site Kit logo in the header which is a common practice on sites when on sub pages.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Given the user is on any page, when the G Site Kit Logo within the header of the plugin is clicked, then the user should be directed to the Main Dashboard. 
    * Hovering over the logo should change the cursor to identify it as a normal link. 
    * The link should be accessible (keyboard and screen-reader friendly).
* If the user is already on the Main Dashboard or any of the Splash Screens, clicking on the Logo would simply reload the page.

## Implementation Brief

- In `assets/js/components/Header.js`:
	- Locate the `<Logo />` component. Wrap it using the `<Link />` component. In the `href` prop, pass a URL to the Main Dashboard. The Main Dashboard URL can be found by using the `getAdminURL` selector of the `CORE_SITE` store, passing `googlesitekit-dashboard` string passed to it.
	- Add a class to the `<Link />` component. Add the `display: inline-block;` styles to it so that the link can be visually differentiated when focused.

### Test Coverage

- No tests need to be added/updated.

## QA Brief
* The logo in the header should be clickable and redirect the user to the main dashboard.

## Changelog entry

* Link the Site Kit logo on the entity dashboard to the main dashboard.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb – I've thought about this before too as that is a very common UX pattern. I'm not quite sure about only doing it in one place though. If we do it I think it should be across the board everywhere the header is used. If there are situations we wouldn't want that then it might be better to leave it as-is, but I'll raise it with the rest of the team to discuss 👍

**Comment by tofumatt** [comment]
My actual instinct here is to have that logo _always_ link to the main dashboard. That creates the expectation/informs the user that there is a link there, but also simplifies the logic of implementing it.

I've seen that done with little confusion across many sites, basically that it's fine to leave that sort of "Home" link there all the time.

We don't disable links in the menu:

![CleanShot 2022-10-24 at 16 36 26](https://user-images.githubusercontent.com/90871/197566819-0d89e6bc-1e45-4d8b-8a44-4ef99ff76ecd.gif)

Let's just leave it on all the time—what do you think @asvinb?

**Comment by jimmymadon** [comment]
@tofumatt I'm happy to keep the logo as a link on the main dashboard as shown in your GIF. However, what should the behaviour of clicking on the logo be on a splash page? Would the link simply reload the page?

**Comment by tofumatt** [comment]
@jimmymadon Yeah, I think in that case it'd be a link to the main dashboard and would reload the page.

It's of semi-dubious value, but it lets the user know that's a link and would even allow a user to open it in a new tab with a "command + click". I've seen that behaviour in other sites/apps and it's not confusing, so let's do that 👍🏻

**Comment by techanvil** [comment]
Hi @nfmohit, thanks for the IB. I would suggest a slightly different approach here, though. Rather than providing an `onClick` handler I would just pass the dashboard URL as the `href` attribute to the `Link`, ensuring an `a` anchor tag will be rendered. That way the link is more screen reader friendly, can be ctrl/command-clicked to open in a new window, and also will show the link address on hover.

A tweak to the styling of the anchor tag would also be needed to ensure the link is visually differentiated when focused. It looks like setting its `display` value to `inline-block` would be sufficient to achieve this.

Please take a look and see what you think.

**Comment by nfmohit** [comment]
Thank you for the kind review, @techanvil!

Should we pass the dashboard URL for all scenarios? I ask because the AC mentions the page should just be reloaded for splash screens.

**Comment by nfmohit** [comment]
Very valid point. I have updated the IB. Thank you @techanvil!

**Comment by techanvil** [comment]
Thanks @nfmohit. LGTM!

IB :white_check_mark:
