### ISSUE TITLE
Error when loading the Admin Bar stats 

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#48]
**Describe the bug**
Site Kit stats don't load in Admin Bar. Instead, we only show a progress bar. 

**To Reproduce**
1. Go to a live page of https://www.getbeans.io/ while logged in to WordPress as admin
2. Click on Site Kit icon in admin bar 
3. Site Kit element loads, but only progress bar is shown, no stats. 

**Expected behavior**
Stats should load in the Admin Bar. 

**Screenshots**
![Screenshot 2019-06-24 at 15 14 59](https://user-images.githubusercontent.com/13304791/60021919-295f9680-9693-11e9-8e3c-abff41d4f3d3.png)

**System Information (please complete the following information):**
 - OS: macOS Mojave 10.14.5 
 - Browser: Chrome Version 75.0.3770.90 
 - Plugin Version: Version 1.0.0-beta.1 
 - Device: Macbook Air 

**Additional context**
Console error from Chrome devtools:
Uncaught TypeError: Cannot read property 'mapValues' of undefined
    at Module.326 (7fe2108.js:453)
    at r (7fe2108.js:453)
    at wp.keycodes.1 (7fe2108.js:453)
    at 7fe2108.js:453

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

* All elements in the Admin bar should load when the user opens a page of their site while logged in.

**Comment by lucymtc** [comment]
@marrrmarrr what version of WordPress you are running your site on?
Can you also provide a list of installed plugins? 
Also, in the console from Chrome devtools can you type `window.lodash` from the front end while logged into WordPress and check if returns `undefined`?

**Comment by lucymtc** [comment]
This may be related to 3rd party issue, we need some more details to help reproduce. 
@marrrmarrr can you provide information listed in the previous comment and the Gutenberg version? thanks

**Comment by bjackson27** [comment]
@ThierryA noting that we aren't able to reproduce this issue. 

@marrrmarrr could you confirm that the user is still seeing this issue?

**Comment by bjackson27** [comment]
Recommending moving this back to issues.

**Comment by jamesozzie** [comment]
@bjackson27 window.lodash results in undefined for me. No additional plugins. I don't see any console errors or networks issues. Happy to investigate further or troubleshoot more if you let me know the plugins you are using @marrrmarrr

**Comment by ThierryA** [comment]
This is very specific to Beans theme as it does some scripts concatenation and enforce script to be placed in the footer. I think it is ok to close this one as it is an issue on Beans side.
