### ISSUE TITLE
Most Popular Content Overlaps on Site Kit Dashboard

### ISSUE THREAD

**Issue by bengreeley** [google/site-kit-wp#480]
## Bug Description

On certain breakpoints the content in the 'most popular content' section of the Site Kit dashboard overlaps and breaks out of the box (see screenshot). This happens when the screen width is anywhere between 1280px - 600px wide and the content within the box is long enough to not break.

## Steps to reproduce

1. Go to `/wp-admin/admin.php?page=googlesitekit-dashboard`
2. Scroll down to the "Most popular content" box on the bottom of the page
3. Resize your browser screen to any width between 1280 - 600 px (any height)
4. See the text overlapping when there is specific content long enough to push content outside the box. For my example, this is the HTML that was pushing the content
```
<tr class="googlesitekit-table__body-row"><td class="googlesitekit-table__body-item"><div class="googlesitekit-table__body-item-content"><a class="
					googlesitekit-cta-link
					googlesitekit-table__body-item-link googlesitekit-cta-link--external googlesitekit-cta-link--inherit" href="/web/20110109013238/http://www.bengreeley.com/email.php" target="_blank" rel="noopener noreferrer">Ben Greeley - Central Maine Web Development and Design</a><br><a class="
					googlesitekit-cta-link
					googlesitekit-table__body-item-url
					googlesitekit-cta-link--external googlesitekit-cta-link--inherit" href="/web/20110109013238/http://www.bengreeley.com/email.php" target="_blank" rel="noopener noreferrer">web/20110109013238/http://www.bengreeley.com/email.php</a></div></td><td class="googlesitekit-table__body-item"><div class="googlesitekit-table__body-item-content">2</div></td></tr>
```

## Screenshots

![image](https://user-images.githubusercontent.com/7133400/64034075-e4852f80-cb1b-11e9-8a37-49a56bc1e065.png)

## Additional Context

 - PHP Version: 7.2 
 - OS: Mac
 - Browser Chrome
 - Plugin Version 1.0.0-beta.1.0.5 and 1.0.0-beta.1.0.4
 - Device: Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For any browser screen width, the contents of each tile on the dashboard should adjust to fit within the tile itself (either break or move to a new line).  

## Implementation Brief

The issue seems to be due to the way tables size themselves based on their contents (particularly `th` elements). The most reliable way seems to be setting the table to `table-layout: fixed` with `width: 100%`. The current table wrapper class already has a full width to it, so this would be more about adapting the fixed layouts where needed, if not for all tables.

* Add new class for fixed table layouts  
E.g. `googlesitekit-table--fixed`
* Define column sizing for tables that should use fixed layouts by adding [`<col>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col) s

Alternatively only apply fixed layouts in smaller viewports, although this would be still vulnerable to wrapping in other viewports as it has to do with parent element size and the width of the content in the table headers defining the width of the rows.

## Changelog entry

* Fix style issues in various data tables which previously would break out of their parent containers on certain device widths.

**Comment by connorhsm** [comment]
I believe I am experiencing this.
When the URL of a most popular item is too long, it overlaps and pushes all of the views statistics outside the container, which allows for horizontal scrolling.

**Comment by felixarntz** [comment]
IB ✅ 

Let's fix this globally as you're recommending too, not only for narrow viewports.

**Comment by felixarntz** [comment]
@aaemnnosttv I was just notified by @westonruter that this also happens on e.g. the "Popularity" table (in case you weren't aware). So let's fix this for both cases. If you find more similar ones, of course those too (unless the fix would be different and more complex) :)

**Comment by tofumatt** [comment]
QA ✅

Looks good when scaled down to 800 x771:

<img width="744" alt="Screenshot 2019-11-07 11 51 29" src="https://user-images.githubusercontent.com/90871/68387005-31f1ce80-0155-11ea-82e3-42a58212046b.png">

**Comment by marrrmarrr** [comment]
Verified, lgtm
