### ISSUE TITLE
Implement new selector for checking module access

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4802]
## Feature Description

Dashboard sharing will require the ability to check whether a user has access to a given module's configured entity in some cases, such as editing a shared modules current configuration or module recovery.

In #4478, we added a new `check-access` endpoint to handle this on the backend. This issue is about adding the necessary functionality into the datastore. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `hasModuleAccess( slug ) : {Boolean|undefined}` selector should be added to the `core/modules` store to check whether the current user has access to the given module's current configuration
	- Returns `undefined` while the result is unknown
	- Returns `Boolean` once the value is known/resolved
* This selector's resolver should use the `check-access` endpoint (added in #4478) to fetch the module access state from the backend to be received into the state
	- This should use `createFetchStore` internally with a `baseName` of `checkModuleAccess`
* Test coverage should be added for the new selector and `receiveCheckModuleAccess` action created by the fetch store

## Implementation Brief

- In `assets/js/googlesitekit/modules/datastore/modules.js` file add the following:
    - Create `fetchCheckModuleAccessStore` with `createFetchStore`
        - `baseName` should be `checkModuleAccess`
        - `controlCallback` method should accept `slug` as a parameter 
        - `controlCallback` should return `API.get()` that calls the new `check-access` endpoint. The backend is being implemented in #4478 
        - Pass the `slug` to the API
        - `reducerCallback` receives `state`, `access` (API response), and `slug` (request param) as arguments
        - Return the state and the new state with the slug as key and the obtained `response.access` as the value i.e. `[slug]: response.access`
        - `argsToParams` takes `slug` as a parameter and returns the `slug` in an object
        - `validateParams` takes `slug` as parameter. It should validate the `slug`

- Create a resolver function `*hasModuleAccess` that receives `slug` as a parameter
    - If there is existing check access for the module, return early
    - It should call the `receiveCheckModuleAccess` action created by `createFetchStore` function and pass the `slug` to it. See:
    https://github.com/google/site-kit-wp/blob/61d83892c776d060bf69a0bb91e81f64e02f3d45/assets/js/modules/search-console/datastore/report.js#L90-L103

- Create `hasModuleAccess` selector that takes `slug` as a parameter
    - Get the module's access value by the `slug` that has to be filtered from the state
    - Return `undefined` while the result is unknown
    - Return the filtered `Boolean` once the value is known/resolved

### Test Coverage

- Add tests for the `receiveCheckModuleAccess` action,  `hasModuleAccess` selector

## QA Brief

**QA:Eng**
- Verify the changes met AC and IB
- Verify the new unit test cases for `receiveCheckModuleAccess` action and `hasModuleAccess` selector are good enough and are passing
- As an extra mile testing, call the `hasModuleAccess` selector and pass `search-console` as slug
- Open the browser network tab
- Verify the API request for `google-site-kit/v1/core/modules/data/check-access` has been made successfully
- Verify the response from the API request to be `{ access: [boolean-value] }`

## Changelog entry

* Add the `hasModuleAccess` selector to the `core/modules` datastore.

**Comment by eugene-manuilov** [comment]
> * Create `assets/js/googlesitekit/modules/datastore/service-entity.js` file with the following:

@hussain-t let's add it to the `assets/js/googlesitekit/modules/datastore/modules.js` file.

> * `reducerCallback` method should accept `slug` as a parameter

The `reducerCallback` function receives response as the second argument and request params formed in the `argsToParams` callback as the third argument. 

> * Return the state and the new state with the slug as key and the obtained access value as the value i.e. `[slug]: moduleAccessValue`

The response is an object, not a scalar value. See the #4478 ticket.

> * Create a resolver function `hasModuleAccess` that takes `slug` as a parameter
>   
>   * It should dispatch an action `receiveCheckModuleAccess` and pass the API response to it
> * Create an action method `receiveCheckModuleAccess` that takes `moduleAccessValue` as a parameter
>   
>   * It should return the payload with `moduleAccessValue` and the type `RECEIVE_CHECK_MODULE_ACCESS`
> * Create a reducer with the case `RECEIVE_CHECK_MODULE_ACCESS`
>   
>   * It should return the previous state and the new state from the payload

No need to create an additional action and reducer here. Check how we do it for the report selector, we need to use the same approach here. https://github.com/google/site-kit-wp/blob/ba1ce47af7eccaaf46d465ab1361fc3cb424203d/assets/js/modules/search-console/datastore/report.js#L90-L103

**Comment by eugene-manuilov** [comment]
> * Create a resolver function `hasModuleAccess` that receives `slug` and `access` (API response) as a parameter

@hussain-t why do we need the `access` as a parameter for the resolver?

> * It should dispatch the action `receiveCheckModuleAccess` and pass the API response to it. See

It should not dispatch the `receiveCheckModuleAccess` action. The resolver should call the fetch action created by the createFetchStore factory.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
