### ISSUE TITLE
Implement `getViewableModules` selector

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4805]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `getViewableModules()` selector should be added to the `core/user` store in JS, which returns the list of module slugs (i.e. `[]string`) that the current user has view access to.
    * This should only include the modules for which the current user has the `googlesitekit_read_shared_module_data` meta capability (see #4522).

## Implementation Brief
* Using `assets/js/googlesitekit/datastore/user/permissions.js`,
	* Add the `getViewableModules` selector which should do the following:
		* Query the `core/modules` data store via the `getModules` selector to get all the modules.
		* Loop through the list of modules which has `shareable` property set to `true` and check if the user has the `googlesitekit_read_shared_module_data` meta capability for the module.
			* This can be done via the `hasCapability` selector, passing the capability (`googlesitekit_read_shared_module_data`) and the module slug as parameter.
			* If the above call returns `true`, add the module slug to an array which will be returned.

### Test Coverage
* Add tests for the new selector.

## QA Brief
- Ensure `dashboardSharing` feature flag is enabled
- Open the browser console and verify the following:
    - Query `getViewableModules` selector like so => `window.googlesitekit.data.select('core/user').getViewableModules()`
    - Verify the result with `getCapabilities` selector => `window.googlesitekit.data.select('core/user').getCapabilities()`
    - If `googlesitekit_read_shared_module_data::["module-slug"]` is `true` for any modules, that module slug should be available in the `getViewableModules` resulted array
    - If all the modules have the value `false`, `getViewableModules` result should be an empty array

**QA:Eng**
- Verify the changes met AC and IB.
- Verify the test cases added for `getViewableModules` selector are good enough and are passing.

## Changelog entry

* N/A

**Comment by asvinb** [comment]
### QA: ✅ 
* Tests ☑️ 
* AC and IB ☑️
