### ISSUE TITLE
Update `triggerSurvey` to be no-op for non-authenticated users

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4806]
## Feature Description

In the context of dashboard sharing, non-authenticated users will be able to use Site Kit dashboards where we currently trigger a number of surveys. This action however requires an access token which non-authenticated users don't have.

Accordingly, this action should be updated to be a no-op in the event the current user isn't authenticated.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `triggerSurvey` action on the `core/user` store should be updated to bypass its fetch request (similar to the logic for a an existing current survey) if the current user is not authenticated
* Test coverage should be updated to cover this change
	* Existing test coverage should be updated to cover the case for users that are authenticated

## Implementation Brief

* In `assets/js/googlesitekit/datastore/user/surveys.js`, within the `triggerSurvey` action creator (generator) function:
  - Call the `isAuthenticated()` selector and if it returns false, return an empty object (bail early).

### Test Coverage

* In `assets/js/googlesitekit/datastore/user/surveys.test.js`:
  - Add a test to the `triggerSurvey` group that checks if the fetch is bypassed if the current user is not authenticated.

### QA Eng
* Make sure the added code meets the AC and the tests are sufficient and passing.

## Changelog entry

* Prevent surveys from triggering for non-authenticated users on a shared dashboard.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
## QA :white_check_mark: 

* Confirmed the added code meets the AC and the tests are sufficient and passing.
