### ISSUE TITLE
Implement `<ViewOnlySplash />`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4810]
## Feature Description

Once scaffolded in #4809, this issue is to create the component used for the splash page for users that aren't able to sign-in with Google (i.e. view-only users).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupUsingProxyViewOnly` component should be built out to implement the splash page for users who cannot authenticate (currently, all non-admins who have one or more modules shared with their user role)
	- See the [Figma design](https://www.figma.com/file/i04x83uA9U8HHBANlhS7Db/Dashboard-Sharing?node-id=773%3A16740) for the general layout although this is somewhat out-of-date so it's likely this will need some revision
	- Exact copy to use below
* The _Go to Dashboard_ button should - when clicked - dispatch an action to dismiss the `shared_dashboard_splash` item (see #4525) before navigating to the dashboard

#### Content
_Title_
> View-only Dashboard Access

_Body_
> Get insights about how people find and use your site, how to improve and monetize your content, directly in your WordPress dashboard

> {Tracking Opt-In}
> [Go to Dashboard](#)

## Implementation Brief
* Using `assets/js/components/setup/SetupUsingProxyViewOnly.js`,
	* Use the `Grid`, `Row` and `Cell` components to achieve the layout as in the designs in Figma. Refer to the AC about the wording to be used.
	* On small screens, the illustration is before the content whereas on larger screens, the order changes when they are side by side. This can be achived by using the `smOrder`, `mdOrder` and `lgOrder` of the `Cell` component.
		* For the cell containing the illustration, use `smOrder` to set the order to `1` and `mdOrder` to `2`.
		* For the cell containing the content, use `smOrder` to set the order to `2` and `mdOrder` to `1`.
	* Use the same class names as in `assets/js/components/setup/SetupUsingProxy.js` to reuse existing styles. For e.g `googlesitekit-setup__splash`, `googlesitekit-setup__content`, `googlesitekit-setup__title`, `googlesitekit-setup__description`
	* Illustration should be added in the `assets/svg/graphics` folder.
	* The `OptIn` component imported from `assets/js/components/OptIn.js` should be used to display the opt-in checkbox.
	* The `Go to dashboard` button should have a callback function as value to the `onClick` prop which should dismiss the `shared_dashboard_splash` item and navigate to the dashboard.
		* To dismiss the `shared_dashboard_splash` item, dispatch the `dismissItem` action of the `core/user` data store.
		* To get the dashboard URL, query the `core/site` data store via the `getAdminURL` selector, with `googlesitekit-dashboard` as parameter.
* Verify if story is working as expected in `assets/js/components/setup/SetupUsingProxyViewOnly.stories.js`

### Test Coverage
* No new tests to be added

## QA Brief
* Visit "Setup -> Using Proxy View-Only -> Start" story.
* Verify that the story is rendered as per the designs in Figma.
* Clicking the "Go to Dashboard" link should redirect the user within Storybook. A page should be displayed titled "Example Domain"
* The story should not match the Figma designs to perfection since we are using the styles from the current code base whereas the Figma design does not. Things to disregard:
	* CTA is uppercase
	* Disregard exact font sizes, spacings and colors.

## Changelog entry

* Implement the view only splash screen.

**Comment by aaemnnosttv** [comment]
@marrrmarrr any revisions to make or call out regarding the design or copy here?

**Comment by marrrmarrr** [comment]
Hey @aaemnnosttv, we reviewed the copy back when we approved the designs, so I think this should be ok to go as it is in Figma.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified**

- The story is rendered as per the designs in Figma.

- Clicking the "Go to Dashboard" link  redirecting the user within Storybook. A page getting display titled "Example Domain". 

- In mobile font size is different then the Figma designs.

<details>

![image](https://user-images.githubusercontent.com/94359491/166405308-f3092184-d2ea-4bc8-8222-c93cedbfa98c.png)

![image](https://user-images.githubusercontent.com/94359491/166405337-35b19e31-d867-482b-a298-8b3d287eeae4.png)

</details>
