### ISSUE TITLE
Limit widgets displayed on the shared dashboard to those which the user has access to

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4813]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `WidgetAreaRenderer` component should conditionally, _if_ in the view-only version of the main dashboard or entity dashboard (relying on the `useViewOnly()` hook from #4814), only render the widgets that the current user has access to.
    * To do that, it should rely on the `getViewableModules()` selector from #4805 and pass the result of that selector to the `getWidgets()` selector as `options.modules` (support for which was introduced in #4807).
    * For the non-view-only version of the UI, the `getWidgets()` selector call should remain as before, i.e. not rely on `getViewableModules()`.

## Implementation Brief
* Using `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js`,
	* Use the `useViewOnly` hook to check if we are in view-only version.
	* Get the list of modules the user is allowed to view by querying the user data store via the `getViewableModules` selector.
	* Update the call to `getWidgets` to include the list of viewable modules as the second parameter, with `modules` as key. This should happen if `useViewOnly` returns `true`.

### Test Coverage
* Update `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.test.js` to add tests for the above changes.

## QA Brief

* To QA this issue, enable `dashboardSharing` feature flag and enable dashboard sharing for a user. Set up a variety of Site Kit modules but don't share a particular module with other users; eg. don't share Analytics with a user but give them access to Search Console.
* Sign in as the user who has view-only access to the dashboard and ensure you only see Search Console widgets and no Analytics widgets on the dashboard.
* If you get stuck on the splash screen with only an option to sign-in, run this in the console and then navigate to the WP dashboard before navigating forward to the SK dashboard again
```js
await googlesitekit.data.dispatch( 'core/user' ).dismissItem( 'shared_dashboard_splash' )
```

## Changelog entry

* Limit widgets displayed on the shared dashboard to those which the user has access to.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv I do not think I can test this based on the QAB, because we currently cannot enable dashboard sharing for a user, or, sign in as the user who has view-only access to the dashboard. I can see the new dashboard sharing icon but that's about it at the moment.   Any suggestions on how this could be tested?

![image](https://user-images.githubusercontent.com/73545194/168832690-3e74e2fd-da58-4b46-8434-99fb970eb1f5.png)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv now that we have the plugin is it possible to test this?  I tried with the plugin, enabled Search Console as shared with an author.  Dashboard sharing feature flag is enabled.  Created an author user and logged in as that user, but when I went to the SK Dashboard it was blank with an error in the console. 

Unsure if this is ready to test, if it is, please could you update the QAB. 

`googlesitekit-polyfills-4b27974671dad93c8d7f.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'assetsURL') at Module.<anonymous> `

<img width="1800" alt="Screenshot 2022-05-23 at 16 40 34" src="https://user-images.githubusercontent.com/73545194/169779661-347e465d-9945-4948-bcc7-02719f9ab920.png">

**Comment by wpdarren** [comment]
@aaemnnosttv noted about the console!  😆   I am still struggling, so here are the steps:

1. Enabled  dashboardSharing feature flag. 
2. Updated to the latest `develop` branch.
3. Just have Search Console, PageSpeed and Analytics connected on my site as an Admin. 
4. For Shared Roles, I just enabled Author, on search console. 

![image](https://user-images.githubusercontent.com/73545194/169858343-88300637-82a4-41c2-bce0-e86f2a952d3d.png)

5. I created a new user with Author role and logged in as that user. 
6.  Browsed to the Site Kit dashboard, which is blank, with console errors 

![image](https://user-images.githubusercontent.com/73545194/169859319-d08e6813-47e7-46ee-acbc-c2236df8d32b.png)

Am I following the right steps?

**Comment by aaemnnosttv** [comment]
Following up here – the problem is due to the [view shared dashboard] capability still being tied to the splash screen dismissal until #5188 is done, so for a user which doesn't have this yet, you get stuck in this state with no way to grant it because assets aren't fully loading. I shared a code snippet to work around this in Slack, but another alternative would be to start with a user who is an admin (no sign-in necessary), set the dismissal (as in the QAB above) and then change the user's role to a non-admin for testing the shared dashboard. It's a bit of a hack but that would require no extra code changes/snippets.

Since this behavior is specific to dashboard sharing this should not affect the release.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Tested sharing PSI with editors only. When navigating to the dashboard with an editor, only PSI widget is shown.

See the screencast below. The left window is `admin`, the right is `editor`.

https://user-images.githubusercontent.com/1621608/169891998-94ffb39f-2881-408d-b061-d0b2dbf16d6f.mov
