### ISSUE TITLE
Use alternate `viewContext` for non-authenticated users

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4814]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Two new view context constants should be introduced, to represent the main dashboard and entity dashboard in their view-only versions:
    * `VIEW_CONTEXT_DASHBOARD_VIEW_ONLY`: `dashboardViewOnly`
    * `VIEW_CONTEXT_PAGE_DASHBOARD_VIEW_ONLY`: `pageDashboardViewOnly`
* If the current user is not authenticated, these two contexts should be used in place of the `VIEW_CONTEXT_DASHBOARD` and `VIEW_CONTEXT_PAGE_DASHBOARD` contexts respectively.
* The `useDashboardType()` hook should be updated accordingly to support these new types. If one of the new `*_VIEW_ONLY` contexts is the current one, the hook should still return the original one without suffix. In other words, while this hook should support the new view only versions, its return value should simply indicate whether we're on the main or the entity dashboard.
    * Not adding the two new values as potential return values keeps the code relying on one of the two current values intact.
    * It furthermore retains the hook for having a single purpose, just to tell us which dashboard type we're on, regardless of whether it's the view only version or not.
* To complement the above `useDashboardType()` hook, a new hook `useViewOnly()` should be implemented. The implementation should be similar to `useDashboardType()`, however it should simply return a boolean based on whether the current view context is one of the two new `*_VIEW_ONLY` contexts or not.
* Any usage of the `VIEW_CONTEXT_DASHBOARD` or `VIEW_CONTEXT_PAGE_DASHBOARD` constants in production code React components should be removed and replaced as follows:
    * If one of these view contexts is used to compare to the current view context, the component should rely on `useDashboardType()` and the corresponding `DASHBOARD_TYPE_MAIN` and `DASHBOARD_TYPE_ENTITY` constants instead.
    * If one of these view contexts is hard-coded in e.g. a `trackEvent` call as part of the event category, the component should rely on `useViewContext()` instead to use whatever context that hook returns instead of the hard-coded one.

## Implementation Brief

~~**Note that especially the last top-level bullet point in the ACs may justify breaking this apart into multiple PRs.** For example, one for the new code infrastructure (which is a bit more complex and may require more review), and another one for the replacements (which should be rather trivial, but touch a lot of code).~~

### Create and use new `viewContext` constants
* In `assets/js/googlesitekit/constants.js`, add the two new constants as per the AC.
* In `assets/js/googlesitekit-dashboard-details.js`:
    - Modify the `viewContext` prop passed to the `<Root />` component. Check if the current user is not authenticated by using the `useSelect` hook to call the `select( CORE_USER ).isAuthenticated()` selector. To be able to use this hook, move the `<Root />` element into the already extracted `GoogleSiteKitDashboardDetails` component.  If the user is not authenticated, pass `VIEW_CONTEXT_PAGE_DASHBOARD_VIEW_ONLY` instead of `VIEW_CONTEXT_PAGE_DASHBOARD`. 
* In `assets/js/googlesitekit-dashboard.js`:
    - Like above, modify the `viewContext` prop passed to the `<Root />` component. If the current user is not authenticated, pass `VIEW_CONTEXT_DASHBOARD_VIEW_ONLY` instead of `VIEW_CONTEXT_DASHBOARD`. Move the <Root /> component into its own component as done above in `googlesitekit-dashboard-details.js`.
* Add (don't replace!) the new `*-VIEW-ONLY` contexts to all files within `assets/js/feature-tours` where their corresponding contexts `VIEW_CONTEXT_DASHBOARD` and `VIEW_CONTEXT_PAGE_DASHBOARD` exist.
* In `assets/js/hooks/useDashboardType.js`:
    - Rename the `dashboardType` variable to `viewContext`. Then modify the return value as follows: 
    - If `viewContext` is `VIEW_CONTEXT_DASHBOARD` or `VIEW_CONTEXT_DASHBOARD_VIEW_ONLY`, return `DASHBOARD_TYPE_MAIN`.
    - If `viewContext` is `VIEW_CONTEXT_PAGE_DASHBOARD` or `VIEW_CONTEXT_PAGE_DASHBOARD_VIEW_ONLY`, return `DASHBOARD_TYPE_ENTITY`.
    - If `viewContext` is anything else, return `null`.
* Create a new file `assets/js/hooks/useViewOnly.js` and implement this hook similar to `useDashboardType` as detailed in the AC.

### Replace usage of constants with hooks
* Remove the usage of `VIEW_CONTEXT_DASHBOARD` and `VIEW_CONTEXT_PAGE_DASHBOARD` in production React components below using one of the following strategies. Ensure no further usage remains after going through the following points.
* In the following list of components:
    - Replace 
        ```javascript 
        const viewContext = useContext( ViewContextContext );
        ```
        with
        ```javascript
        const dashboardType = useDashboardType( ViewContextContext );`
        ```
    - Use the value of `dashboardType` to compare to the corresponding `DASHBOARD_TYPE_MAIN` or `DASHBOARD_TYPE_ENTITY` constants as detailed in the final point of the AC. Do this for:
    - `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`
    - `assets/js/components/EntityHeader.js`
    - `assets/js/components/EntitySearchInput.js`
* In the following components, use the value returned by `useContext( ViewContextContext )` instead of using hardcoded constants for `VIEW_CONTEXT_DASHBOARD` and `VIEW_CONTEXT_PAGE_DASHBOARD`:
    - `assets/js/components/ModulesList.js`
    - `assets/js/components/notifications/CoreSiteBannerNotification.js`
    - `assets/js/components/notifications/IdeaHubPromptBannerNotification.js`
    - `assets/js/components/notifications/SetupSuccessBannerNotification.js`
    - `assets/js/hooks/useActivateModuleCallback.js`
    -  In `assets/js/modules/idea-hub/datastore/constants.js`, remove the `IDEA_HUB_GA_CATEGORY_WIDGET` constant and individually define it within the components that use it using `useContext( ViewContextContext )` as above.

### Test Coverage

* Update `useDashboardType.test.js` to cater for the new conditions.
* Add tests for the new `useViewOnly` hook.

## QA Brief

* This issue changes an internal value that is mostly used for determining which version of a dashboard we're on (single page/entity or main), but is also used in differentiating context for events tracked particularly for components used in different places
* It should have no observable changes from the user's perspective
* A few areas to check:
    - Check for any console errors or Google Analytics event tracking errors (switch on GA Debugger). 
    - Feature tours.
    - The Idea Hub module setup and use.
    - Entity Page Dashboard.

## Changelog entry

* Use alternate `viewContext` for non-authenticated users.

**Comment by jimmymadon** [comment]
To anyone picking up the IBR:
> Add (don't replace!) the new `*-VIEW-ONLY` contexts to all files within `assets/js/feature-tours` where their corresponding contexts `VIEW_CONTEXT_DASHBOARD` and `VIEW_CONTEXT_PAGE_DASHBOARD` exist.

My understanding is that FeatureTours won't trigger for components the user does not have access to (since the components won't render in the first place). So is this 'blanket' approach fine?

**Comment by eugene-manuilov** [comment]
Thanks, @jimmymadon. Mostly looks good to me. Added two comments. Please, take a look.

> * If the current user is not authenticated (`_googlesitekitLegacyData.setup.isAuthenticated` is false),

We need to use the `isAuthenticated` selector from the `core/user` datastore instead of accessing the global legacy data which will be removed at some point.

> Note that especially the last top-level bullet point in the ACs may justify breaking this apart into multiple PRs.

We don't use multiple PRs for a single ticket intentionally. If there is a need to use two PRs for one ticket then it means that the original ticket needs to be split into two tickets instead. I think this ticket doesn't seem to be big enough to consider splitting it into multiple one.

> > Add (don't replace!) the new `*-VIEW-ONLY` contexts to all files within `assets/js/feature-tours` where their corresponding contexts `VIEW_CONTEXT_DASHBOARD` and `VIEW_CONTEXT_PAGE_DASHBOARD` exist.
> 
> My understanding is that FeatureTours won't trigger for components the user does not have access to (since the components won't render in the first place). So is this 'blanket' approach fine?

Yes, looks good to me. I think it should work correctly.

**Comment by jimmymadon** [comment]
@eugene-manuilov Didn't realise we could use selectors at this level - but of course makes sense. Have updated the IB.

As for the comment on splitting the PRs: that comment was already in the IB when I picked it up - I'm guessing @aaemnnosttv added it when writing the ACs. I agree with you that the issue doesn't seem too large to split into multiple issues now that we know what is involved here. So I am going to strike it out for now.

**Comment by eugene-manuilov** [comment]
> * If the current user is not authenticated (use the `select( CORE_USER ).isAuthenticated()` selector)

@jimmymadon let's use hooks instead of accessing the `googlesitekit.data.select` function directly. To do this, we will need to refactor those files a little bit. We can move the `<Root>` element into the `GoogleSitekitDashboardDetails` component to be able to use the `useSelect` hook and extract dashboard elements into a new component similar to  the `GoogleSitekitDashboardDetails` one.

**Comment by jimmymadon** [comment]
@eugene-manuilov Thanks - have updated the IB.

**Comment by eugene-manuilov** [comment]
Thanks, @jimmymadon. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked for any console errors (found an issue which reported #5035)
- Checked for Google Analytics event tracking errors 
- Checked the Feature tours for Idea Hub and Unified Dashboard.
- Checked the Idea Hub module setup and use.
- Checked thee Entity Page Dashboard

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/161973343-38652d45-5a1a-43aa-8c96-4477c566c93e.png)
![image](https://user-images.githubusercontent.com/73545194/161973379-358dd6f1-287d-4fc9-8c79-6f05880f1220.png)
![image](https://user-images.githubusercontent.com/73545194/161973361-069303a3-bb94-4a31-81c4-7b6f1d75cd92.png)

</details>
