### ISSUE TITLE
Conditionally render `SourceLink`s based on view context

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4815]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any widgets that include one or more `SourceLink`s should be adjusted to only render these source links **if not** in the view-only version of the dashboard. The `useViewOnly()` hook introduced in #4814 should be used to determine that.
    * The reasoning behind this change is that the links go to the Google frontend to which you'll only have access if authorized within Google's permission system. The view-only users won't have access to this in the vast majority of cases, therefore these links should not be shown.

## Implementation Brief

- In `assets/js/components/SourceLink.js`:
    - Call the `useViewOnly()` hook introduced in #4814. If it is false, return `null`.

### Test Coverage

* No new tests to be added.

## QA Brief

* All source links at the bottom of widgets should continue to appear as normal for a user not using Dashboard sharing.

#### Note for future QA

* This will not be possible to QA _now_, but in the future when a user can browse the dashboard using Dashboard sharing in a "view-only" mode, the "Source: {Service}" links at the bottom of widgets should not appear when browsing in a read-only mode.

## Changelog entry

* Update source links to hide on the view only dashboard.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- All source links at the bottom of widgets continue to appear as normal for a user not using Dashboard sharing.
- Went through the date periods, 7, 14, 28 and 90 days to ensure the correct data period appeared on the Search console and Analytics pages.
