### ISSUE TITLE
Hide write actions in `DashboardIdeasWidget` in view-only context

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4816]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub widget UI should not render the buttons that can trigger write actions when in a view-only version of the dashboard. The `useViewOnly()` hook introduced in #4814 should be used to determine that.
    * This essentially creates an alternate version of the widget that is readonly, which is needed for unauthenticated users, since they wouldn't (and shouldn't) be able to tweak anything regarding the Idea Hub data.
* An additional Storybook story for the new readonly version of that widget should be created. It can otherwise rely on the same mock data as the existing primary story.

## Implementation Brief
* Once https://github.com/google/site-kit-wp/issues/4814 has been merged.
* In `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/IdeaActivityButton.js`, if the `useViewOnly` hook returns `true` and if `activity` is not equal to `IDEA_HUB_BUTTON_VIEW`, render `Null`.
* Update `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.stories.js` to reflect above state.

### Test Coverage
* No new tests to be added.

## QA Brief

- Ensure the code changes met the AC and IB.
- Verify the newly added [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-idea-hub-widgets-dashboardideaswidget--view-only-dashboard) for the view-only version of the dashboard satisfies the AC.

## Changelog entry

* Hide Idea Hub action buttons when viewing dashboard in view-only mode.

**Comment by asvinb** [comment]
### QA: ❗ 
@hussain-t Just a small note. Instead of returning `null` here: https://github.com/google/site-kit-wp/pull/5041/files#diff-37616c7d728fc6e991bbd37c9c3bbb304688c5c6ac8dee55f3330329258e9c04R59, let's return the `Null` component which we are already importing.

**Comment by hussain-t** [comment]
> ### QA: ❗
> @hussain-t Just a small note. Instead of returning `null` here: https://github.com/google/site-kit-wp/pull/5041/files#diff-37616c7d728fc6e991bbd37c9c3bbb304688c5c6ac8dee55f3330329258e9c04R59, let's return the `Null` component which we are already importing.

Thanks, @asvinb. I have fixed this in a [follow-up PR](https://github.com/google/site-kit-wp/pull/5049) and assigned this ticket to @tofumatt.

**Comment by aaemnnosttv** [comment]
@asvinb @hussain-t I see `Null` is referenced in the IB but that may have just been a typo to have been capitalized, but it should remain as-is currently as we shouldn't use the `Null` component when we want to explicitly render `null`. The one special exception to this is `WidgetNull` which has an important side-effect for widgets. `Null` is essentially a component to facilitate polymorphism for simplifying the code. I left a review on the follow-up PR as well.

**Comment by asvinb** [comment]
Thanks for the info @aaemnnosttv ! Really good to know!

### QA: ✔️

**Comment by hussain-t** [comment]
Thanks for the clarification, @aaemnnosttv. It's good to know about it. I have closed the follow-up PR.
