### ISSUE TITLE
Create `<DashboardSharingSettingsButton />` and settings modal

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4820]
## Feature Description

The dashboard sharing settings will be exposed via a new modal which will be triggered by a new button that will eventually be integrated into the header of the main dashboard for authenticated users.

This issue is for building out the icon button and the modal it controls but none of the settings themselves.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `DashboardSharingSettingsButton` component should be created as an icon button (like others used in the Header) as shown in the [Figma design](https://www.figma.com/file/i04x83uA9U8HHBANlhS7Db/Dashboard-Sharing?node-id=737%3A18577).
	- The icon to use matches the Material [`person_add_alt`](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aperson_add_alt%3A) icon
* The modal should only be concerned with rendering the backdrop + canvas/container for the settings interface to be added in the future
	- On mobile/phone the modal should be edge-to-edge full-screen – i.e. no backdrop should be visible and no margin should be present around the modal; corners should also not be rounded
	- On larger viewports, the content area should have a max-width as in the design which is centered on the screen
	- Due to the requirements, using `<Dialog>` may not be a good fit, but the modal should be rendered in a `<Portal>`
	- For now, the contents of the modal can be placeholder text with a link to close the modal, this is only temporary for now so no attention is needed for styling the contents
	- The modal should only close by clicking the temporary close link or by pressing the escape key when open
	- Focus should be trapped within the modal while open and returned when closed
* Storybook stories should be added for the component, no integration should be done with the header yet
* New components for dashboard sharing should be created within `assets/js/components/dashboard-sharing`

## Implementation Brief
* Install the `@material/react-dialog` package.
* Create `assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.js` which exports the `DashboardSharingSettingsButton` functional component.
* Define the `dialogOpen` state variable to know whether to display/hide the modal.
* Initially it should render the `Button` component imported from `assets/js/components/Button.js` with the icon only as per the designs in Figma. The icon can be added in the `assets/svg/icons` folder.
* The `onClick` prop of `Button` should call a function to toggle the `dialogOpen` state variable.
* Wrap the markup for the dialog (see below) within `Portal` component imported from `assets/js/components/Portal.js`
* The dialog should use the components from `@material/react-dialog`. It should have the following structure:
	* `Dialog`
		* `DialogContent`: refer to the AC for the temporary content
		* `DialogFooter`: will contain the "Apply" and "Cancel" buttons
* Unfortunately `@material/react-dialog` does not have full screen support. To overcome that, add a custom class name, `googlesitekit-dialog` to `Dialog` and style the dialog so that the height is 100% (`100vh`) on small screens.
	* Using `assets/sass/components/global/_googlesitekit-dialog.scss`, add styles for `googlesitekit-dialog` as per the designs in Figma. Refer to the AC which contains some details on how the modal should look on small screens, which mirrors what we have in Figma.
	* Some key things we need to account for:
		* The back icon to close the dialog is visible on small screens only, above the title.
		* The footer should always sit at the bottom of the viewport on small screens.
* Create `assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.stories.js` which contains stories (1 for now) for `DashboardSharingSettingsButton`.

### Test Coverage
* No new tests to be added.

## QA Brief
* Visit the `DashboardSharingSettingsButton` story in storybook under "Components -> DashboardSharingSettingsButton -> Default"
* Verify the modal is styled as per the designs in Figma.
* Disregard the color of the share icon since it'll be fixed upon integration with the header.
* Disregard the button styles in the modal footer since we are using the styles from our current codebase.

## Changelog entry

* Add the new DashboardSharingSettingsButton component.

**Comment by asvinb** [comment]
@aaemnnosttv Since we'll be moving to @mui packages later, I suggested we start using their components instead of using the MDC web. Let me know what you think.

**Comment by aaemnnosttv** [comment]
@asvinb dashboard sharing is scheduled to launch long before the rebranding phase 1 so it should be done using the current components. Later, all components will be updated at once. Unless there is a new component that we'd be adding that works with both then maybe that would be ok, but generally speaking we shouldn't be mixing the new with the old.

**Comment by asvinb** [comment]
Right @aaemnnosttv , but in this case, it's a new component which is completely isolated from our current features 😁 In this case, instead of creating a new component using the current MDC web library, why not once and for all start moving to mui

**Comment by aaemnnosttv** [comment]
@asvinb it's worth considering – I think the main concern for now is around stylistic consistency which needs to be preserved until new things are ready to be rolled out but also there may be other side-effects to using both libraries at the same time that could cause issues.

I'm not against it categorically, but it may be a bit premature yet. My understanding is that we shouldn't start to use new component library elements outside of storybook yet. You're right that this is a totally new feature, but it is one that will launch before the rebranding. From a UI POV, it's also composed of relatively few material components, so I don't think updating it from MDC to another later would be a large effort.

Thoughts @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv @asvinb +1 on not using MUI components at this point. We should only start using that once we start the rebranding work. The UI here needs to fit into the current design, so trying to build it on MUI will probably run into problems. In addition to that, the amount of work to pull in the MUI components in a reasonable way into our infrastructure would go beyond the scope of this issue.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb !

Regarding the current IB, I think it might be simpler to use components from `@material/react-dialog` rather than borrowing from our current (legacy) `Dialog` and using `MDCDialog` manually as we do there (a pattern we probably shouldn't perpetuate). Looking at the component in the package, it looks like there are a number of things we'd want that it would do for us, including focus trap, and escape key binding.

I realize adding this added package may be a short-lived, but I think that's ok. I would imagine the new version will have a similar API/structure so in a way it's a bit of a stepping stone to using the newer components as well 😄 

Unless there's a reason we can't use this package, let's go this route instead and only go the primitive route as a fallback.

**Comment by asvinb** [comment]
Sounds good to me @aaemnnosttv . IB has been updated, let me know what you think.

**Comment by aaemnnosttv** [comment]
LGTM, thanks @asvinb 

IB ✅

**Comment by mohitwp** [comment]
### QA update ⚠️ 

@asvinb 

The figma design have 'person add' icon before title in desktop view of modal. Is it something which we add later with other settings ?

Figma : 
![image](https://user-images.githubusercontent.com/94359491/166408752-2a1b2a82-35f5-4d8a-bc67-10c9e9b9a3d8.png)

![image](https://user-images.githubusercontent.com/94359491/166408713-2aca347a-94b7-4b5d-99e4-a17c2b2463be.png)

**Comment by asvinb** [comment]
@mohitwp I can add the icon. :)

**Comment by mohitwp** [comment]
@asvinb Okay, thanks ! Please add it to storybook. Assigned this ticket to you.

**Comment by asvinb** [comment]
@eugene-manuilov Can you review follow up PR to add the icon?

Thanks!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- On mobile/phone the modal is edge-to-edge full-screen.
- On larger viewports, the content area have a max-width as in the design which is centered on the screen
- The modal  only close by clicking the temporary close link or by pressing the escape key when open.
- Focus trapped within the modal while open and returned when closed.

<details>

![image](https://user-images.githubusercontent.com/94359491/166464481-9ccaa817-dc56-4c19-8218-1ef50837e3b9.png)


![image](https://user-images.githubusercontent.com/94359491/166464551-b98fd9e6-29d7-4564-93de-0076406b4c16.png)


</details>
