### ISSUE TITLE
Create `<ModuleRecoveryAlert />`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4823]
## Feature Description

When a module is recoverable (shared but without a valid owner) a module recovery alert will be shown to all other authenticated admins to bring this issue to their attention. If the current user has access to the module's current configured entity the alert will offer a CTA/button to recover the module. Recovering the module essentially makes the current user the new module owner which restores access to users who were relying on the data shared by the original owner.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `<ModuleRecoveryAlert />` component should be created in `assets/js/components/dashboard-sharing`
* Uses the `getRecoverableModules` selector introduced in #4803
	- If none, return `null`  
	_Note: recoverable modules are available on page load so no initial loading state is needed for this specifically_
* No design exists for this yet, but it should render a single banner notification as described below

#### Alert Content

_Title_

> Dashboard data for some services has been interrupted

The body of the alert should vary based on the number of recoverable modules (i.e. singular or plural), and whether any of the modules are recoverable by the current user or not.

All recoverable modules will need to be checked for access to determine if the current user is able to recover them (see `checkModuleAccess()`).

While access is being checked for all recoverable modules, a progress bar should be shown until all checks are complete as the subsequent interface is dependent on the results.

Only one of the following variations will be shown, in the following order of precedence:
1. The current user has access to one or more recoverable modules
1. The current user does not have access to any recoverable modules

**The current user has access to one or more recoverable modules**

_Body for a single module_

> {ModuleName} data was previously shared with other users on the site by another admin who no longer has access. To restore access, you may recover the module as the new owner. [Learn more](#)
>
> By recovering the module, you will restore access for other users by sharing access via your Google account. This does not make any changes to external services and can be managed at any time via the dashboard sharing settings.
>
> [Recover](#) {spinner}

Clicking _Recover_ should dispatch `recoverModule(module)`, showing the spinner and disabling the button while in progress.

_Body for multiple modules_

When a user has access to multiple recoverable modules, the modules will be shown in a list with checkboxes (defaulting to checked) for each module, similar to the oAuth consent screen. 

> The data for the following modules was previously shared with other users on the site by another admin who no longer has access. To restore access, you may recover the module as the new owner. [Learn more](#)
> * [x] {Module Name 1}
> * [x] {Module Name 2}
>
> By recovering the selected modules, you will restore access for other users by sharing access via your Google account. This does not make any changes to external services and can be managed at any time via the dashboard sharing settings.
>
> [Recover](#) {spinner}

Clicking _Recover_ should dispatch `recoverModule(module)` for each checked module in the list, showing the spinner and disabling the button while in progress. The button should also be disabled if no modules are checked.

**The current user does not have access to any recoverable modules**

> {ModuleName} data was previously shared with other users on the site by another admin who no longer has access. To restore access, the module must be recovered by another admin who has access. [Learn more](#)

or

> The data for the following modules was previously shared with other users on the site by another admin who no longer has access. To restore access, the module must be recovered by another admin who has access. [Learn more](#)

### Create `ModuleRecoveryAlert` component

Create a new component `ModuleRecoveryAlert` within file `assets/js/components/dashboard-sharing/ModuleRecoveryAlert.js`.

- Retrieve the list of recoverable modules via the `getRecoverableModules` selector.
  - The list of modules will comprise objects which have `slug` and `name` properties amongst others.
- Retrieve the list of modules which the user has access to by mapping the recoverable modules to calls to the `hasModuleAccess( slug )` selector.
  - If any of the calls to `hasModuleAccess` returns `undefined` it means the state is still being resolved.
- Define a state value to track the checkboxes state. Initially set this to `null`.
- Define a state value to track the state of the `recoverModule` action being in flight, initially set to `false`.
- If the list of recoverable modules is empty, return `null`.
- If all of the calls to `hasModuleAccess` have resolved (return non-`undefined`), and the checkboxes state value is still `null`, initialise the checkboxes state. It should be an object keyed by module slug, the modules being those where the module is recoverable by the user (`hasModuleAccess` returns `true`), and all values set to `true` (all checkboxes initially checked).
- Render a `BannerNotification` component:
  - The `title` prop should be the title as defined in the AC.
  - The notification should not be dismissable.
  - If any of the calls to `hasModuleAccess` have yet to resolve, _or_ the checkboxes state value is not yet set:
    - The `description` prop should be `null`.
    - The children should be a `ProgressBar`.
  - If all the calls to `hasModuleAccess` have resolved:
    - The `learnMoreURL` prop should be defined as a placeholder `'#'`, and `learnMoreLabel` should have the text _Learn more_.
    - If there is exactly one module with access:
      - The `description` prop should be the first paragraph of the body as defined in the AC for this condition, specifically: _{ModuleName} data was previously shared with other users on the site by another admin who no longer has access. To restore access, the module must be recovered by another admin who has access._
      - The children should be:
        - The second paragraph of the body: _By recovering the module, you will restore access for other users by sharing access via your Google account. This does not make any changes to external services and can be managed at any time via the dashboard sharing settings._
        - A `Button` labelled _Recover_ with a click handler that sets the `recoverModule` in-flight state to `true`, awaits for a call to dispatch the `recoverModule` action for the module with access, and then sets the in-flight state back to `false`.
          - It should be `disabled` when `recoverModule` is in-flight.
        - A `Spinner` with the `isSaving` prop set when `recoverModule` is in-flight.
    - If there is more than one module with access:
      - The `description` prop should be the first paragraph of the body as defined in the AC for this condition, specifically: _The data for the following modules was previously shared with other users on the site by another admin who no longer has access. To restore access, you may recover the module as the new owner._
      - The children should be:
        - The list of the modules with access mapped to `Checkbox` components, each followed by the module name. Each checkbox should:
          - Be `checked` according to the corresponding checkbox's state value.
          - Have an `onChange` handler that toggles the relevant checkbox's state value.
          - Be `disabled` when `recoverModule` is in-flight.
        - The second paragraph of the body: _By recovering the selected modules, you will restore access for other users by sharing access via your Google account. This does not make any changes to external services and can be managed at any time via the dashboard sharing settings._
        - A `Button` labelled _Recover_ with a click handler that sets the `recoverModule` in-flight state to `true`, awaits via `Promise.all` for a set of calls to dispatch the `recoverModule` actions for the checked modules, and then sets the in-flight state back to `false`.
          - It should be `disabled` when `recoverModule` is in-flight, or when no modules are checked.
        - A `Spinner` with the `isSaving` prop set when `recoverModule` is in-flight.
    - If there are no modules with access:
      - If there is exactly one recoverable module:
        - The `description` prop should be the first paragraph of the body as defined in the AC for this conditions, specifically: _{ModuleName} data was previously shared with other users on the site by another admin who no longer has access. To restore access, the module must be recovered by another admin who has access._
      - If there is more than one recoverable module:
        - The `description` prop should be the first paragraph of the body as defined in the AC for this conditions, specifically: _The data for the following modules was previously shared with other users on the site by another admin who no longer has access. To restore access, the module must be recovered by another admin who has access._
  - Remember to internationalise all text via `__` from `@wordpress/i18n`.

### Storybook

- Create stories for `ModuleRecoveryAlert` stories for the variants defined by the AC.

### Test Coverage

* Add the new stories to the VRT suite.

## QA Brief

* This is not yet part of dashboard. So verify all the scenarios defined in AC with the storybook. 

## Changelog entry

* Implement module recovery alert notification.

**Comment by felixarntz** [comment]
@aaemnnosttv ACs lgtm. Obviously the wording may still be iterated upon later, but I think it's sounding good now already, except for one thing:

> To restore access, the module must be recovered by another admin who has access.

I think this is a bit too generic, we should rather address the user directly here because they _are_ another admin who has access. For example:

> To restore access, take over from the previous owner who shared the data by recovering the module.

**Comment by aaemnnosttv** [comment]
> I think this is a bit too generic, we should rather address the user directly here because they _are_ another admin who has access

Sounds good, I have tweaked it in the with-access cases to be more direct although slightly different from your suggestion. We can always refine it later like you said 👍 

Now that this issue covers all modules and cases, I'll close #4824 as it's no longer relevant.

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds good! Let's move this to IB.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 I have two observations.  

1. I ran through having multiple modules, but rather than having  both modules checkboxes enabled, I only enabled one module (Idea hub) and clicked on the recover button. All was fine, the dashboard reloaded and the single module message appeared as expected (for PSI).  When I clicked on the recover button though, nothing happened, other than error message appeared in the console. 

`googlesitekit-api-d19d27124769b3d35dd2.js:3 Google Site Kit API Error method:POST datapoint:recover-module type:core identifier:modules error:"Module is not recoverable."`

2. When I have multiple modules (PSI and Idea Hub) and both checkboxes are enabled. I click on the recover button, and for a second a single module message appears after the multiple module message disappears.  See screencast. 

https://user-images.githubusercontent.com/73545194/170695113-7768b2c8-a116-404e-80ad-771e74aa6fc6.mp4

**Verified:**

- While access is being checked for all recoverable modules, a progress bar is shown until all checks are complete.
- Confirmed title appears `Dashboard data for some services has been interrupted`
- Confirmed the `Body for a single module` is as per the AC.
- Confirmed the `Body for multiple modules` is as per the AC. 

<details>
 <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/73545194/170695811-ee3390a8-ff00-40a5-b385-94ac71b1820b.png)
![image](https://user-images.githubusercontent.com/73545194/170695798-b3b27e96-3dcf-489e-a6e7-d5648bed270d.png)

</details>
