### ISSUE TITLE
Update `<Header />` and `<UserMenu />` for main and shared dashboards

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4826]
## Feature Description

Once dependent components have been implemented behind the scenes, this issue is intended to integrate the pieces into the application, although still behind the appropriate feature flag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DashboardSharingSettingsButton` should be added into the main header between the date range select and the help menu as shown in the [Figma design](https://www.figma.com/file/i04x83uA9U8HHBANlhS7Db/Dashboard-Sharing?node-id=737%3A18577) on the main dashboard
* The `<UserMenu />` should be replaced by the `<ViewOnlyMenu />` on the view-only dashboards
* These changes should only take effect when the `dashboardSharing` feature flag is enabled
* More attention should be paid to styles and details at this point to ensure consistent design between Figma, existing, and dashboard sharing interfaces

## Implementation Brief
* Using `assets/js/components/Header.js`,
	* Import the `ViewOnlyMenu` from `assets/js/components/ViewOnlyMenu/index.js`.
	* Import the `DashboardSharingSettingsButton` from `assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.js`.
	* If `dashboardSharing` feature flag and `useViewOnly` hook both return `true`, render the `ViewOnlyMenu` instead of `UserMenu`, keeping the `isAuthenticated` check as well.
	* After `children` and before `UserMenu`/`ViewOnlyMenu`, add `DashboardSharingSettingsButton` which should be rendered only if `dashboardSharing` feature flag is `true`.
* To check if `dashboardSharing` is enabled via the `useFeature` hook, passing `dashboardSharing` as parameter.
* To check if the dashboard is in view only mode via the `useViewOnly` hook.
* Styles should match what we have in the Figma designs.
* Update `assets/js/components/Header.stories.js` to add stories when `ViewOnlyMenu` and `DashboardSharingSettingsButton` are rendered.

### Test Coverage
* No new tests to be added.

## QA Brief
* Check if the new `Header` stories render correctly as per the AC and designs in Figma. `Plugin Header with Dashboard Sharing Settings` and `Plugin Header in view-only mode`
* Enable dashboard sharing feature flag and the dashboard sharing button should be displayed in the header and entity header.
* Disable dashboard sharing feature flag and the dashboard sharing button should not be displayed in the header and entity header.
* QA Eng
    * Verify the logic within `assets/js/components/DashboardMainApp.js` and `assets/js/components/Header.js` fulfills the AC.

## Changelog entry

* Update info in plugin header for users viewing a shared dashboard.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvin I have two initial observations while testing this. 

1. In the QAB it mentions: 

> Enable dashboard sharing feature flag and the dashboard sharing button should be displayed in the header and **entity header.** 

When I set up my test site with `dashboardSharing` enabled, I can see the new dashboard sharing button but it only appears on the main dashboard.  It doesn't mention entity dashboard in the AC, so just checking if it should be displaying there?

2. The color of the dashboard sharing is `#757575` on Storybook and my test site but on Figma it is `#2E2E2E` I am assuming this is an expected Figma difference but wanted to check as it's not mentioned in the QAB.

**Comment by asvinb** [comment]
@wpdarren 
1. Good catch. It's my understanding that the button should show on the entity header since the headers, main and entity are consistent, unless am mistaken @aaemnnosttv 
2. This is expected @wpdarren We are using the existing colors in our codebase and consistent with the colors in the header.

**Comment by aaemnnosttv** [comment]
> 1. Good catch. It's my understanding that the button should show on the entity header since the headers, main and entity are consistent, unless am mistaken @aaemnnosttv

@asvinb @wpdarren correct – to be more precise, in dashboard sharing terms the main dashboard applies to both main and entity dashboards as we refer to them today, but is now referred to more specifically as the "authenticated dashboard". Hopefully in the not-too-distant-future the main and entity dashboards (authenticated or shared) will actually be different views of the same dashboard rather than separate.

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ 

@asvinb  I realise you have styled it as per the Figma designs, but I feel the icon is smaller than the help icon and could be a little larger. E.g. The help SVG path is 20x20, where as the new dashboard sharing icon is 18.33 x 13.33 and these are similar icons so should be the same size in my opinion. I realise this is only a small size change but it doesn't stand out like the help icon.  Wondered what your thoughts are?  

This is what it looks like on mobile as an example

![image](https://user-images.githubusercontent.com/73545194/168944618-bbed30a2-7fa6-44e1-a4ca-2d0b5125cbcd.png)

**Verified:**

- The new Header stories render correctly as per the AC and designs in Figma. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/168945604-dadcbc5d-48c0-480f-bfb5-7530d43f1e62.png)
![image](https://user-images.githubusercontent.com/73545194/168945617-4b8f55d4-abcd-47c3-b523-252e4f27b590.png)

</details>

- The dashboard sharing button is displayed in the main header and entity header when dashboard sharing feature flag is enabled. 
- The dashboard sharing button is not be displayed in the main header and entity header when dashboard sharing feature flag is disabled.

![image](https://user-images.githubusercontent.com/73545194/168943403-ac2226c7-1430-475f-a4ae-81d13f669479.png)

**Comment by asvinb** [comment]
@wpdarren From a technical point of view, both sizes are same. See screenshot below:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/31818/169009186-3f6ab072-7439-40fc-8f4f-7a0e41c9c8ff.png">
Basically the `viewBox` is the same and we try to have the size consistent across the icons. It's actually what's within the `viewBox` which is different. For the help one, the `path` is `20x20` whereas for the share one, it's 18.33x13.33. The thing is that 18.33 is not far from 20px and if we'll need to increase the height of the path within the 20x20 `viewBox`, the icon might look distorted. We can ask design to take a look and try to provide an path which is closer to 20x20. I would create a separate ticket to address it :)

**Comment by wpdarren** [comment]
QA Update: ✅ 

@asvinb thank you for looking at this, I will make a note to create a ticket for it. 

**Verified:**

- The new Header stories render correctly as per the AC and designs in Figma. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/168945604-dadcbc5d-48c0-480f-bfb5-7530d43f1e62.png)
![image](https://user-images.githubusercontent.com/73545194/168945617-4b8f55d4-abcd-47c3-b523-252e4f27b590.png)

</details>

- The dashboard sharing button is displayed in the main header and entity header when dashboard sharing feature flag is enabled. 
- The dashboard sharing button is not be displayed in the main header and entity header when dashboard sharing feature flag is disabled.

![image](https://user-images.githubusercontent.com/73545194/168943403-ac2226c7-1430-475f-a4ae-81d13f669479.png)
