### ISSUE TITLE
Implement event tracking for dashboard sharing

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4827]
## Feature Description

As with all new features, there will be some events and interactions we will want to measure to help us better understand how dashboard sharing is being used for users who have opted in to anonymous usage tracking.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Closing in favor of #5219, #5220, #5221.
