### ISSUE TITLE
Site Kit encountered an error Report this problem

### ISSUE THREAD

**Issue by Itechupdate** [google/site-kit-wp#4829]
## Bug Description

Sitekit is not working i even tried fixing it by changing https to http and uninstalling and then installing it. Nothing is fixing this bug. I am using Newspack and my siite health is great.

## Steps to produce bug

Everytime i try to access adsense through newspack. This comes up. But earlier it used to be fixed by itself in two three try. but this time its not happening.
## Screenshots
![sitekit](https://user-images.githubusercontent.com/98926991/153237205-94e8922f-18b2-42f7-8bd8-55241a0b4209.jpg)

Error says,
Site Kit encountered an error

Cannot read properties of undefined (reading 'MutationObserver')
    in Header
    in DashboardApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in Root

**Comment by bethanylang** [comment]
@Itechupdate As noted on your comment on another issue, we do not provide support in GitHub. Can you please [create a new support topic here](https://wordpress.org/support/plugin/google-site-kit/) so we can take a look? Thank you!

**Comment by claudiulodro** [comment]
@Itechupdate this appears to be an issue in Newspack + Site Kit. I've opened an issue here: https://github.com/Automattic/newspack-plugin/issues/1529
