### ISSUE TITLE
Analytics data is not yet available

### ISSUE THREAD

**Issue by imalisiddique** [google/site-kit-wp#483]
http://tinyurl.com/y6sp9dos
All settings are connected-
http://tinyurl.com/y272c4y9

**Comment by jamesozzie** [comment]
@imalisiddique We will require some more information from your side. Can you please inform me of the following:
- When did you setup the Analytics account for this site?
- Do you see the tracking code if the source code of your website (it should start with a UA-)?
- Do you see any [console errors](https://i.imgur.com/KyLAzgH.png?
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)

If you've just recently setup the account on Analytics you can find out more on Analytics data processing [here](https://support.google.com/analytics/answer/1070983#DataProcessingLatency).

**Comment by imalisiddique** [comment]
@jamesozzie 
1. June 2019
2. UA-25658622-5
3. No error in console
4. Site health info: https://pastebin.com/eMKmsrgf

**Comment by jamesozzie** [comment]
@imalisiddique Can you try the below, there could be another plugin, Ad Blocker or Firewall/security feature causing this error. 

- Remove the [Analytics module](https://i.imgur.com/6ppIDwZ.png) (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
- Temporarily deactivate your other active WordPress plugins (You can also try deactivating one by one, starting with "Advanced Cache" and "Really Simple SSL")
- Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)

**Comment by imalisiddique** [comment]
Thank you
