### ISSUE TITLE
Test fails if a module's component imports from `@wordpress-core`

### ISSUE THREAD

**Issue by ChrisAntaki** [google/site-kit-wp#4831]
## Bug Description

A test fails if a module's component imports from `@wordpress-core`.

For example, if the SwG module's `AccessSelector` component imports `@wordpress-core/compose`, then this test fails: "all modules › subscribe-with-google › components/plugins has an index module with all components exported" from `assets/js/modules/index.test.js`

The error message is `Cannot find module '@wordpress-core/compose' from 'AccessSelector.js'`

## Steps to reproduce

1. Import something from `@wordpress-core` in a module's component.
2. Run tests `npm run test:js:watch --files assets/js/modules/index.test.js`
3. See error

## Additional Context

The code compiles file, but a unit test fails

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ChrisAntaki** [comment]
Here's an example of a check that failed due to this: https://github.com/google/site-kit-wp/runs/5129371962?check_suite_focus=true

**Comment by aaemnnosttv** [comment]
This is somewhat expected as `@wordpress-core` is basically an alias for modules provided by core at `window.wp` which wouldn't work in Jest of course.

What we'd probably have to do is require the WP packages and add module mapping for them to the Jest config for the imports to work in the node environment.

Thoughts @tofumatt ?

**Comment by aaemnnosttv** [comment]
Closing this out for now as we don't have anything actively using `@wordpress-core` imports. Will address if/when it comes up in the future.
