### ISSUE TITLE
Update event tracking to allow segmentation by authentication

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4846]
## Feature Description

Since the beginning, using Site Kit has always been limited to authenticated admins. Starting with dashboard sharing, this limitation will no longer apply to all users using Site Kit, making it possible for non-authenticated users to use the dashboards in a read-only way. Such users will also be able to opt-in to our anonymous usage tracking which helps us to improve the product through various tracked events, such as errors.

Going forward, it will be important to be able to segment this information by which users are authenticated (with Site Kit) and which are not.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The event data in Site Kit's `trackEvent` function should be extended with a new custom dimension based on the current user's authentication status (whether or not they have an access token or not)
	- The dimension should be `dimension7`
	- The value should be `1` if authenticated, otherwise `0`

## Implementation Brief

* Update the hook for the `googlesitekit_user_data` filter in the `Authentication` class to add the `authenticated` property to the user data. Use the result of the `is_authenticated()` method call as the value for the new property.
* Add the `dimension7` property to the `eventData` object in the `createTrackEvent` function. Use `global._googlesitekitUserData?.user?.authenticated ? 1 : 0` as the value for the new dimension.
* A comment explaining what this dimension is for should be added, as it isn't self-evident from the name `dimension7`.

### Test Coverage

* N/A

## QA Brief

This issue adds a new custom dimension (`dimension7`) to all internal events tracked. This will be either `1` if the user is signed in with Google or `0` if not.

* Enable tracking in Settings -> Admin Settings
* Go to the main dashboard
* Scroll down the page
* Most GA events which are firing will have `dimension7` set to `1` since right now we only have authenticated users.
* One event for a non-authenticated user is starting the setup from the splash page (may need to [set console output to be persistent](https://developer.chrome.com/docs/devtools/console/reference/#persist) to observe this)

## Changelog entry

* Update internal event tracking to include user authentication state.

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@asvinb @aaemnnosttv could you expand on how we might test this for a non-authenticated user. In the QAB it mentions that we may need to [set console output to be persistent](https://developer.chrome.com/docs/devtools/console/reference/#persist) to observe this) but I am unsure how that will allow us to test this.  Am I missing something here?  Any additional information would be appreciated.

**Comment by aaemnnosttv** [comment]
@wpdarren you can observe an event for an unauthenticated user by enabling the tracking toggle on the splash page (no persistent console output needed)

<img width="782" alt="image" src="https://user-images.githubusercontent.com/1621608/166256406-5e40efc8-7220-492f-b106-e563bb75dd23.png">

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

For an authenticated user, the `dimension 7` GA event is `1`. 
For an unauthenticated user the dimension 7` GA event is `0`. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/166393510-3df401d6-bd5b-4d29-9cef-4349a39eaf27.png)

![image](https://user-images.githubusercontent.com/73545194/166393510-3df401d6-bd5b-4d29-9cef-4349a39eaf27.png)

</details>

**Comment by felixarntz** [comment]
@marrrmarrr I've updated our GA property to support this additional custom dimension (`authenticated`).
