### ISSUE TITLE
Provide support for insertion of the new Optimize snippet container

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4850]
## Feature Description

Site Kit inserts what's now known as a "legacy" Optimize container snippet on users sites ([article](https://support.google.com/optimize/answer/6262084)). With this legacy Optimize snippet one of the problems is a user cannot connect a GA4 property to an Optimize container, if they've used Site Kit to insert their Optimize snippet, with the below error appearing when using the "[Check Installation](https://i.imgur.com/LIep6TG.png)" feature, a requirement for an Optimize experiment to start. 

![image](https://user-images.githubusercontent.com/41326532/154054486-468c486b-3368-4a90-a743-2099779655e9.png)

To resolve this consider support for the latest Optimize snippet as recommended by the platform. Changes to the plugin that could resolve this may include one of the below:
1. **A toggle to allow the user to select their preferred snippet** (_Legacy/analytics.js snippet: For UA /AMP users, Optimize.js snippet: For connecting GA4 properties_). The toggle would eventually be phased out when GA4 is supported in AMP. 
2. **The replacement of the current Optimize snippet** to the latest Optimize snippet
3. **A notice within the Optimize setup page** that states "_If connecting an experiment to a GA4 property to following these instructions_" (with documentation on the plugin website)

_Note that if we adopt option 2 above GA4 isn't fully supported in AMP at this time. This will have implications for the JSON text area._ 

## Steps to recreate

1. Connect Analytics on a site within SK, allowing the plugin to insert a GA4 snippet
2. With the SK Analytics configurations ensure that all traffic is counted - including logged in traffic (_This is to ensure you can perform an Analytics installation check  at Optimize (without the experiment failing as your visit won't be counted_).
2. Visit [Optimize](https://optimize.google.com/) and setup a container (not need to setup the experiment just yet)
3. Connect the Optimize module within Site Kit, inputting the Optimize container ID
4. Revisit your Optimize container and setup an experiment, a A/B test 
5. Connect the experiment with your Site Kit connected GA4 property ([there is a warning](https://i.imgur.com/pNAaQeh.png) that GA4 is in beta mode)
6. Perform a "Check installation" test, which is a requirement for the experiment to begin
7. [The error appears](https://i.imgur.com/wUrgZXM.png) and users are unable to proceed with the Site Kit placed Optimize snippet

## Current SK snippet placement

The current Site Kit optimize tag looks like the below, added within a users Site Kit placed gtag.js snippet ([screenshot](https://snippyly.com/discuss/?q=Lx80sSW7X9avUYxhYz6m&EDIT=0r9YaGd1bEj2CD2Yk0Et) | [Legacy snippet setup guide](https://support.google.com/optimize/answer/6262084)):
`gtag("config", "UA-183***216-1", {"anonymize_ip":true,"optimize_id":"OPT-MS46NN9"});`

The new snippet would place one of the following snippets (differences described [here](https://support.google.com/optimize/answer/7513085)):
`sync: <script src="https://www.googleoptimize.com/optimize.js?id=OPT_CONTAINER_ID"></script>`
`async version: <script async src="https://www.googleoptimize.com/optimize.js?id=OPT_CONTAINER_ID"></script>`

## Workaround for users who wish to connect Optimize to a GA4 snippet within Site Kit 

Users can [insert their own Optimize snippet](https://support.google.com/optimize/answer/10106536) as opposed to connecting the Optimize module within Site Kit. After doing so they can setup their own Optimize experiment, at which point they'll be able to connect the experiment to the GA4 property connected to their site.  

## Additional notes:
- Optimize Help Center: [Introducing Optimize with Google Analytics 4](https://support.google.com/optimize/answer/11417589)
- Optimize Help Center: [Insatallation overview / The different types of Optimize snippets](https://support.google.com/optimize/answer/7513085)
- These GA4 connected Optimize experiment changes were first brought to our attention from a users [support forum topic](https://wordpress.org/support/topic/does-site-kit-support-ga4-google-optimize-integration/#post-15366718), from testing a similar scenario. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of https://github.com/google/site-kit-wp/issues/6466
