### ISSUE TITLE
All Traffic widget issues on a site with small amount of data

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4851]
## Bug Description

On a site that has a small amount of data (less than 5 visitors in 28 days) there are a few issues on the `All traffic` widget. 

1) Within the pie chart there's a legend on all 3 tabs, despite having zero data for that period (14 days). 

2) The `No data to display` message and illustration graphic does not appear. In this example, there's zero data for that time period (14 days).  When I select 7 days though the message and illustration does display.

![image](https://user-images.githubusercontent.com/73545194/154076113-c173ee3c-9217-43bf-a5ea-d0e4bbcfa270.png)

Let me know if you would like access to my site. 

Please note this issue occurs with Unified dashboard disabled or enabled.  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren it looks like there is data in the previous period, otherwise the change percentage would be blank/zero.

It's odd that the pie chart is blank though so perhaps that part is a bug. Can you confirm this is still an issue and if so share access to the property?

**Comment by wpdarren** [comment]
@aaemnnosttv yes, this is still an issue and there is data in the previous period. As you can see from my screencast the pie chart issue is now on 28 days, whereas 7, 14 days are the expected behaviour. Go to 90 days and you see some data. 

https://user-images.githubusercontent.com/73545194/156385795-dd174f6c-b36e-443b-a05f-88fbff5b6f05.mov

I have given you permission to search console and analytics data for `https://explorewithsound.com`

**Comment by aaemnnosttv** [comment]
@wpdarren starting with the new zero data states, the pie chart will be an empty circle without a label or legend. Not sure this is worth iterating on outside of the upcoming changes for zero states.

![image](https://user-images.githubusercontent.com/1621608/159302274-6c2a95b6-73e2-485d-b3dd-4722ae796e73.png)

@felixarntz is this complete ^ ?

**Comment by felixarntz** [comment]
@aaemnnosttv At first glance I'd say this looks like it will indeed no longer be an issue once the new zero data states are out. But I'd be curious to have @wpdarren re-check then, to ensure there isn't something else very specific causing the current experience here?

**Comment by wpdarren** [comment]
@aaemnnosttv  @felixarntz sure, I'll take a look over this with the same site and zero data states enabled.

**Comment by wpdarren** [comment]
@aaemnnosttv @felixarntz I can confirm with zero data states enabled, this is no longer an issue. For this particular site, there's zero data on 7, 14, 28 days but data on 90 days. The screenshot shows the pie chart with no legends. 

![image](https://user-images.githubusercontent.com/73545194/159474442-4ccf1a80-1cb0-4cac-aa7d-a2f232917004.png)

**Comment by felixarntz** [comment]
Thanks @wpdarren!
