### ISSUE TITLE
WordPress Site Title with characters like apostrophes appear as code

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4852]
## Bug Description

If your WordPress site title has characters like apostrophes, when you create a new Google account the code appears instead of the characters. This is the only place I could find where the site title appears by default. We need to check this though.  Of course, if you do not edit the Analytics account name it'll also appear in other areas of the plugin. 

It's also an issue on the service side, and have created an Asana ticket to fix it. 

![image](https://user-images.githubusercontent.com/73545194/154076934-6b46edd7-aef8-4486-95c1-0da96cc31aea.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Name should be used and displayed consistently with WordPress core such that HTML entities should be decoded

## Implementation Brief

* Update the definition of `siteName` in the inline base data to use `wp_specialchars_decode` with `ENT_QUOTES`
* Update `name` in `Google_Proxy::get_site_fields` for consistency

### Test Coverage

* No changes necessary

## QA Brief
* Test with a site where there are apostrophes in the site name. If you are testing locally, go in the WordPress admin and change the "Site Title" to include apostrophes [/wp-admin/options-general.php].
* Disconnect and proceed to setup Analytics again.
* Choose to setup a new account. Ensure apostrophes are displayed correctly.

## Changelog entry

* Fix display of special characters used in the site title.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

- Setting up a new Analytics account when the site title has apostrophes, it is displayed correctly. 
- When editing settings when the site title has apostrophes, it is displayed correctly. 
- When analytics is disconnected, and then reconnected, when the site title has apostrophes, it is displayed correctly. 
- Also noticed that the service pages are also now working, when the site title has apostrophes.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/161534771-7b54be6d-8d74-4db5-a2d9-760bf481aad8.png)
![image](https://user-images.githubusercontent.com/73545194/161534813-8509813c-aace-4df8-9cb6-5f62399df100.png)
![image](https://user-images.githubusercontent.com/73545194/161534851-909645cc-c3b8-4cc0-ab46-db35be903179.png)
![image](https://user-images.githubusercontent.com/73545194/161534835-59588c9c-ae0c-4c77-a819-2d2bc16f975a.png)

</details>
