### ISSUE TITLE
Alphabetize Google Analytics profiles

### ISSUE THREAD

**Issue by uogecko** [google/site-kit-wp#4853]
## Feature Description

Google Analytics profile selection menu becomes unusable when there are dozens or hundreds of profiles to choose from.  Alphabetizing this menu would resolve this usability issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following `<Select>` drop down menus should be sorted alphabetically in ascending order.
    - Search Console - Property
    - Analytics - Account, Property, Profile (View)
    - Analytics 4 - Property
    - AdSense - Account
    - Tag Manager - Account, Container
* If any of the menus have a `Set up new ___` option, that should remain last in the menu.

## Implementation Brief

- In `includes/Modules/Search_Console.php`:
    - In the `parse_data_response()` method, locate the endpoint case for `GET:matched-sites`. Inside the case, update the `$entries` variable by passing it to the `wp_list_sort()` function.
- In `includes/Modules/Analytics.php`:
    - In the `parse_data_response()` method, update the following endpoint cases:
        - `GET:accounts-properties-profiles`: Update the `$accounts` variable by passing it to the `wp_list_sort()` function.
        - `GET:profiles`: Update the returned `$response` variable by passing it to the `wp_list_sort()` function.
        - `GET:properties-profiles`: Update the `$properties` variable by passing it to the `wp_list_sort()` function.
- In `includes/Modules/Analytics_4.php`:
    - In the `parse_data_response()` method, locate the endpoint case for `GET:properties`. Inside the case, update the returned array passing it to the `wp_list_sort()` function. It should be ordered by the `displayName` property.
- In `includes/Modules/AdSense.php`:
    - In the `parse_data_response()` method, locate the endpoint case for `GET:accounts`. Inside the case, update the returned array passing it to the `wp_list_sort()` function. It should be ordered by the `displayName` property.
- In `includes/Modules/Tag_Manager.php`:
    - In the `parse_data_response()` method, update the following endpoint cases:
        - `GET:accounts`: Update the returned array passing it to the `wp_list_sort()` function.
        - `GET:containers`: Update the returned array passing it to the `wp_list_sort()` function.
        - `GET:accounts-containers`: In the `$response` variable assignment, update the `accounts` property value so that it is sorted with the `wp_list_sort()` function.
- For each of the `wp_list_sort()` function call above:
    - `$orderby` should be `name`, unless mentioned otherwise.
    - `$order` should be `ASC`.
    - `$preserve_keys` should be `true`.

### Test Coverage

- No new tests need to be added.
- Update any existing tests relevant to the above methods to reflect on the changes above.
- Fix any failing tests.

## QA Brief

* Open settings to check dropdown with properties from AC
* All dropdown options should be listed alphabetically as per eg: 
<img width="999" alt="Screenshot 2022-11-23 at 19 21 24" src="https://user-images.githubusercontent.com/16494321/203622483-19fcb7a0-d187-46ef-9048-9fe6a1996b1b.png">

**Follow-up for https://github.com/google/site-kit-wp/issues/4853#issuecomment-1340944426:**
- Verify all the dropdowns mentioned in the ACs making sure they have a single option and also multiple options.
- Verify that the reported fatal error is fixed.

## Changelog entry

* Alphabetically sort dropdown menus where appropriate.

**Comment by aaemnnosttv** [comment]
Thanks for the suggestion! I think this could be beneficial to do for all our selects, not just profiles.

**Comment by jimmymadon** [comment]
@kuasha420 I remember discussing this in our Team Review meeting a while back. However, I do not remember the conclusions on this one if we had any. Some of my questions and thoughts:
1. Do we eventually want to do this for _all_ of our components which use `<Select>`: 
    - Search Console - Property
    - Analytics - Account, Property, Profile (View), Country**, Timezone**
    - AdSense - Account
    - Tag Manager - Account, Container
Country and Timezone already are sorted and don't need further sorting. The rest are pre-sorted from the API's responses, mostly by date created (asc), which is what our existing user base could be relying on. 
1. When there are two pieces of data in an `<Option>`, such as in the Analytics Property Select, we have Property name and Property ID, should this simply sort by whatever the eventual option string begins with, ie. Property name here? 
1. Currently, on all of our selects, the "Set up a new ___" is the last option. Should this still be the case?

c.c.'ing @tofumatt if you have any thoughts on the above?

**Comment by jimmymadon** [comment]
@tofumatt Thanks for those comments. Make sense to me. I will leave out implementation details for the IB so we can discuss overriding the component, creating props, etc in the IBR. Have written down some ACs for now.

**Comment by jimmymadon** [comment]
@tofumatt Based on our AC sync discussion, @felixarntz suggested sorting the response in the backend when parsing the data response. Any thoughts? 

I've removed all implementation suggestions from the ACs. We could have this discussion at the IB level too?

**Comment by tofumatt** [comment]
@felixarntz @jimmymadon That sounds great to me. It would also be very easy to implement on the front-end and scale well 👍🏻 

Moving over to IB for the particulars of the implementation then 🙂

**Comment by eclarke1** [comment]
Please can we add a priority label to this ticket, thank you

**Comment by nfmohit** [comment]
**Note to the IB reviewer:** I have added a `P2` to it for now, but please change it if you think it should be otherwise.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by nfmohit** [comment]
@jimmymadon Hi! While reviewing the implementation, I noticed that the sorting with `wp_list_sort()` is case-sensitive. The sorted list looks like the following:

![image](https://user-images.githubusercontent.com/20284937/204126456-fcb43d96-e8d5-4970-a2d4-5660b34629dd.png)

Is this the expected outcome or do we expect a case-insensitive list? If so, we might need to change the implementation to use something like `usort` in combination with `strcasecmp`.

CC: @aaemnnosttv @tofumatt @felixarntz @eugene-manuilov @sashadoes

**Comment by jimmymadon** [comment]
@nfmohit Thanks for flagging this. I think we should proceed with case-insensitive sorting as the screenshot definitely feels wrong (and confusing!). Your suggested approach seems fine as I couldn't find a similar WP function on doing a quick search.

**Comment by sashadoes** [comment]
Put this ticket back to Execution as IB needs a change and this ticket requires someone more PHP oriented than me to finish. 
cc @aaemnnosttv / @FlicHollis

**Comment by techanvil** [comment]
Thanks @sashadoes, as mentioned on the PR, we probably don't need to update the IB here, rather someone who's comfortable making the PHP changes can finish off by applying the changes requested in https://github.com/google/site-kit-wp/pull/6198#discussion_r1036992865.

**Comment by mohitwp** [comment]
### QA Update ❌ 

@sashadoes 

- Verified on dev.
- GA4 properties drop down and toggle is not showing under Analytics settings on dev environment.
- Also, under GA4 set up banner critical error is coming and user is not able to complete set up.

![image](https://user-images.githubusercontent.com/94359491/206187284-78c521ef-fae3-4ce8-8baa-4c9f958ad0ed.png)

![image](https://user-images.githubusercontent.com/94359491/206187337-85a9d2e5-5ef7-4634-a919-446c8ee4a9f6.png)

**Comment by nfmohit** [comment]
@mohitwp Submitted a follow-up PR #6301 to address the above, thank you!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev.
- Issue mentioned [here](https://github.com/google/site-kit-wp/issues/4853#issuecomment-1340944426) is now resolved.
- Verified settings of Analytics, Search Console, Tag manager , AdSense.
- Verified set up of Search Console, Analytics, Tag manager and AdSense.
- Verified set up through GA4 Activation banner.
- Verified <Select> drop down menus sorted alphabetically in ascending order.
- Verified set up new_ option is last option in every drop down menu.

<details>

![image](https://user-images.githubusercontent.com/94359491/206984093-13e200db-6fae-47dc-a69f-2ecdcbfc5393.png)

![image](https://user-images.githubusercontent.com/94359491/206984129-82e569d4-4fb8-447f-8465-03cb2968afac.png)

![image](https://user-images.githubusercontent.com/94359491/206984239-5002a349-7b17-492d-b688-02e3766d0a36.png)

![image](https://user-images.githubusercontent.com/94359491/206984269-4bf71cbb-e065-46ed-a2d7-4b53a55993bb.png)

![image](https://user-images.githubusercontent.com/94359491/206984326-3ca26abb-fc84-4ac5-887a-f71b90c878ef.png)

![image](https://user-images.githubusercontent.com/94359491/206984358-364cc4db-c852-4f49-af2d-42c31d3c7892.png)

![image](https://user-images.githubusercontent.com/94359491/206984394-02ef9faa-0545-41ee-bdd4-355d167032dc.png)

![image](https://user-images.githubusercontent.com/94359491/206984422-c1c90547-09b4-4298-b27d-8bcfd082bf09.png)

![image](https://user-images.githubusercontent.com/94359491/206984469-203902b5-246f-4b71-82e7-f13d4f53a083.png)

![image](https://user-images.githubusercontent.com/94359491/206984494-2d20a9aa-7a9c-48ed-85fe-2a682b3df947.png)

![image](https://user-images.githubusercontent.com/94359491/206984516-c7e58276-89d8-48e8-a1e3-ec4d730c75f7.png)


</details>

**Comment by uogecko** [comment]
Just wanted to say 'thank you'!  I appreciate the effort!
