### ISSUE TITLE
Unstable PHPUnit Test in `Entity_Search_Controller`

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#4855]
## Bug Description

PHPUnit tests will sometimes fail with the following error message:

````
1) Google\Site_Kit\Tests\Core\Util\REST_Entity_Search_ControllerTest::test_post_search
Failed asserting that 18 matches expected 17.
````

These can be seen on both CI and local. 

https://github.com/google/site-kit-wp/runs/5180139045?check_suite_focus=true

![Screenshot_20220216_190827](https://user-images.githubusercontent.com/6187401/154275239-9742527a-2b3c-4157-9aed-140a38dc9b37.png)

## Steps to reproduce

1. Run `composer test` and the test will fail sometimes.
2. Same test also fails on CI sometimes for different PHP versions. 

This may be due to a race condition in post/entity insertion order or WP_Query returning data in different order. May just be cosmic interference. But we should either fix this or remove the test. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHPUnit tests should consistently pass or fail
* The unstable `test_post_search` should be updated such that its assertions do not depend on the order of posts returned

## Implementation Brief

* In `REST_Entity_Search_ControllerTest`:
    * Update the `test_post_search` method to not rely on the order of the `$data` array for validating `id`. 
    * Instead, use the `wp_list_pluck` function to get the id's of the `$data` array and use `assertContains` to assert that both post ID exists in the result. 

### Test Coverage

* The test should always pass even on multiple run consistently.

## QA Brief

* QA:Eng: 
    *  Make sure all the phpunit tests are passing on CI.
    * Re-run the WP Nightly + PHP 7.4 tests a few times to ensure there's no flakiness.
    * Run `composer test` on local a few times. The test should always pass and no longer be unstable.

## Changelog entry

* N/A

**Comment by jimmymadon** [comment]
## QA: Eng ✅ 

✅ Make sure all the phpunit tests are passing on CI.

✅ Re-run the WP Nightly + PHP 7.4 tests a few times to ensure there's no flakiness.
Ran WP Nightly and WP Latest three times. Always passes.

✅ Run `composer test` on local a few times. The test should always pass and no longer be unstable. 
Ran test 10+ times - always passes.
