### ISSUE TITLE
Provide additional context data with remote-controlled features request

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4858]
Following #4856, additional high-level criteria should be included in the `/site-management/features/` request, to allow better heuristics for whether to grant a feature for a site.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In addition to the existing body parameters `platform` and `version`, the following parameters should be sent with the `/site-management/features/` request:
    * `platform_version`: The WordPress version used.
    * `active_modules`: Space-separated list of the slugs of all active modules (including the force-active modules), sorted by the modules' `order`.
    * `connected_modules`: Space-separated list of the slugs of all (active and) connected modules (including the force-active modules), sorted by the modules' `order`.
    * `user_count`: Number of all WordPress user accounts on the site.
    * `connectable_user_count`: Number of WordPress user accounts on the site with permission to connect (i.e. currently that is the number of administrators).
    * `connected_user_count`: Number of WordPress user accounts on the site that are actually connected (i.e. that are authenticated/have an access token).

## Implementation Brief

* Update the `Google_Proxy::get_features()` method:
  * Create a new variable `$body` and assign an empty array to it.
  * Pass the $body array through the `googlesitekit_features_request_data` filter.
  * Assign the existing body properties to the `$body` array.
  * Add the `platform_version` property to the body array with the global `$wp_version` variable as value.
  * Get the number of registered users and pass it as the `user_count` property to the body array.
  * Get the number of administrators and pass it as the `connectable_user_count` property to the body array.
  * Get the number of connected users (those who have `OAuth_Client_Base::OPTION_ACCESS_TOKEN` meta) and pass it as the `connected_user_count` property to the body array. Please, use the `User_Options::get_meta_key` method to property prefix the meta key.
  * Set the $body array as the actual `body` property of the request.
* Add a hook for the `googlesitekit_features_request_data` filter to the `Modules` class that adds `active_modules` and `connected_modules` information to the filtered array.
  * `active_modules` should be a space-separated list of the slugs of all active modules (including the force-active modules), sorted by the modules' `order`.
    * `connected_modules` should be a space-separated list of the slugs of all (active and) connected modules (including the force-active modules), sorted by the modules' `order`. 

### Test Coverage

* Update the `Google_ProxyTest::test_get_features` test to verify new request params.

### QA Eng
* Configure HTTP proxy on your local machine following instructions in the [engineering workflow doc](https://docs.google.com/document/d/1vYRA-YxxZdufO6piF0gA1k60N3UxbvuqyQr_XfGgvSk/edit#heading=h.faf0umy03arh) and use mitmproxy or an equivalent tool to inspect requests.
* Delete the cached transient features data by running the following command:
  ```bash
  10updocker wp option delete _transient_googlesitekit_remote_features
  ```
* Go to the SiteKit Dashboard and check if a request was made to `site-management/features/`.
* Inspect the request to ensure the body contains the data mentioned in the AC.
* Repeat the above steps to add administrator (and other users) and check if the `user_count`, `connectable_user_count` and `connected_user_count` update correctly.
* Repeat the above steps to also check the `active_modules` and `connected_modules` update themselves when you activate and connect additional modules.

## Changelog entry

* Add additional context to remote feature request.

**Comment by eugene-manuilov** [comment]
> > Require the `ABSPATH . WPINC . '/version.php'` file in the function to make sure that the global variable `$wp_version` exists.
> 
> Why is that needed? Isn't that file always loaded by WP core?

Ah, yes, you are right. We don't need to load it. Removed it.

> > Pass the $body array through the `googlesitekit_featues` filter.
> 
> There's a typo in the filter name, but also I think we should use a more specific name, since the data filtered aren't the features. Maybe `googlesitekit_features_request_data`?

Yep, sounds good to me. Updated.

> > Get the number of connected users (those who have `wp_googlesitekit_access_token` meta)
> 
> A bit of a nit-pick, but I just want to clarify that this must not hard-code the `wp_` prefix, it depends on the user meta key prefix based on whether network mode is enabled - which, yes, we don't use at this point, but the code has supported it like that throughout.

Yep, updated.

**Comment by felixarntz** [comment]
IB ✅

**Comment by jimmymadon** [comment]
@felixarntz When testing the [PR](https://github.com/google/site-kit-wp/pull/4942) in the browser, I realised that we have a cyclic issue for adding active and connected modules. When we construct Modules, we check `if ( Feature_Flags::enabled( 'ideaHubModule' ) )`, this eventually calls `GoogleProxy::get_features()` which now uses our new filter (to add connected / active modules) which is defined within `Modules::register()`. But `Modules::register()` has not been called yet so the filter is not registered which means we don't get that data added in. 

Any thoughts on what we could do here?

c.c. @eugene-manuilov

**Comment by felixarntz** [comment]
@jimmymadon Great catch! I can think of two alternative solutions to avoid this cycle:
1. We could add an extra condition to `Authentication::filter_features_via_proxy()` to not trigger the request. Basically, if there is no value for the transient and the requested feature is `ideaHubModule`, we wouldn't trigger the request. We could use whether the module is active in the database as a fallback to assume the feature is enabled (if the user was able to activate the module in the DB, it is very likely the feature is enabled). The request would still be triggered from any other features and anyway in the cron job, so we'd still have the data updated regularly.
    * We also have to do the same for the (unreleased) `swgModule`, which is subject to the same problem. 
2. We could bypass the need to rely on the available modules altogether and instead update the new filter callback to call `Modules::get_active_modules_option()` which just looks at the database. From there we'd have to still combine it with the force-enabled modules and sort them correctly. If the option contains the `idea-hub` (or `subscribe-with-google`, see above) module, we could instantiate these module classes on the fly just in that specific method to check their connected state and know their order value.

Both is a bit odd, but my personal take is that 2. is still cleaner as it avoids the problem closer to the source, in the `Modules` class. Let me know your thoughts.

Btw I also left a few other comments on the PR.

**Comment by jimmymadon** [comment]
@felixarntz Thank you for all the comments. I have addressed the ones on the PR. 

As for the cyclic issue:
I think Solution 2 would still not work. The new filter itself is not added as `Modules::register()` has not yet run. So modifying anything within the filter won't change anything - unless I'm missing something?

Solution 1 makes sense to me - should I proceed with it then?

**Comment by felixarntz** [comment]
@jimmymadon Ah good point, makes sense. Yeah I think in that case let's go with solution 1.

**Comment by jimmymadon** [comment]
@felixarntz I have updated the PR with a quick implementation of solution 1. It does feel a bit hacky - but is this what you had in mind for checking active modules in the DB? It does solve our cyclic issue when I did some preliminary testing. Not sure if there would be any other side effects. If this looks ok then I could clean things up a bit more and perhaps add a test.

**Comment by felixarntz** [comment]
Thanks @jimmymadon, at a high level that is what I was thinking. I agree it is fairly hacky, but IMO an acceptable solution for now. I left a review on the PR though and particularly made one comment on how we can make the less at least touch fewer parts of the codebase, which I think would be valuable.

**Comment by jimmymadon** [comment]
@felixarntz Have addressed all your comments and added tests. Does look a lot simpler like you suggest. Going to move this to CR.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

* Verified `platform_version` matches the WordPress version used.
* Verified `active_modules` is a space-separated list of the slugs of all active modules (including the force-active modules), sorted by the modules' order.
* Verified `connected_modules` is a space-separated list of the slugs of all (active and) connected modules (including the force-active modules), sorted by the modules' order.
* Verified `user_count` is the number of all WordPress user accounts on the site.
* Verified `connectable_user_count` is the number of WordPress user accounts on the site with permission to connect (i.e. currently that is the number of administrators).
* Verified `connected_user_count` is the number of WordPress user accounts on the site that are actually connected (i.e. that are authenticated/have an access token).
* Reviewed the implementation 👍
