### ISSUE TITLE
Update admin bar Analytics CTA to use new design

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4867]
Follow-up to #4694: This issue is about implementing the [design for the admin bar CTA to activate Analytics](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=969%3A1936). Related: #4868

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The blue CTA to activate Analytics in Site Kit's WP admin bar UI should be replaced with a new CTA using the [Figma design here](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=969%3A1936).
    * The implementation should use the similar components from #4694 as much as possible, potentially introduce props for minor adjustments.
* Storybook coverage should be included.
* The change should be conditional on the `zeroDataStates` feature flag.

## Implementation Brief

- Refactoring `ActivateAnalyticsCTA` into a reusable global component is being implemented in #4868.

- Reuse the above `ActivateAnalyticsCTA` component in the Admin Bar:
    - Create a new component, `assets/js/components/adminbar/ActivateAnalyticsCTA.js`
        - Use `assets/js/components/ActivateAnalyticsCTA.js` in here and pass (nest) two `<PreviewGraph />` components. 
        - For the first "Traffic" `<PreviewGraph />`, extract a new SVG component - `assets/svg/graphics/cta-graph-traffic.svg` that contains everything other than the title (Traffic), i.e. extract the 'All Users' label, the area chart and the pie chart along with the dots below it. Add a flag prop, e.g. `showIcons` to the `<PreviewGraph />` component that will hide the `googlesitekit-analytics-cta__preview-graph--icons` div if set to false. 
        - The second "Unique visitors from Search" `<PreviewGraph />` will be the same as the one used in `SearchFunnelWidget/ActivateAnalyticsCTA.js`.
    - In `AdminBarWidgets.js`, if the zeroDataStates feature is enabled, then render the `assets/js/components/adminbar/ActivateAnalyticsCTA.js` component instead of `ActivateModuleCTA` component.
    - In `adminbar.scss`, import `components/global/googlesitekit-analytics-cta`. Also import `@material/button/mdc-button` under Material Imports and `vendor/mdc-button` as these are used by the button in the new `ActivateAnalyticsCTA`. 
    - Continue to modify the CSS so that the `adminbar/ActivateAnalyticsCTA.js` component matches the Figma mock in the AC. 

- Update StoryBook:
    - Add a new Story, `assets/js/components/adminbar/ActivateAnalyticsCTA.stories.js` for the new admin bar component.

### Test Coverage

* No new tests required.

## QA Brief

- With `zeroDataStates` feature flag on:
  - Verify the new Analytics CTA component in the Admin Bar looks like the Figma mock.
  - Verify `ActivateAnalyticsCTA` in `SearchFunnelWidget` has not changed.
  - Verify `ActivateAnalyticsCTA` in on the WordPress Dashboard has not changed.
- With the `zeroDataStates` feature flag off:
  - Verify the old `ActivateModuleCTA` component is rendered as normal.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
I don't see anything _too_ specific in the IB about these components and the SVGs for them/how we'll render them:

<img width="660" alt="CleanShot 2022-03-10 at 22 32 21" src="https://user-images.githubusercontent.com/90871/157766029-3cce82ee-3120-41bd-9cc7-5ae902e5f0ee.png">

I think:

> The first "Traffic" <PreviewGraph /> will require modifications to be made to the <PreviewGraph /> component to match the Figma mock. Alternatively, create a new component similar to <PreviewGraph /> with just a Title and an SVG (removing the and icons sections).

covers it largely, but does this IB include creating a new SVG for the `PreviewGraph` to use?

I think this otherwise looks good, but i'm not clear on the SVG for those components 😅

**Comment by jimmymadon** [comment]
@tofumatt Have added a bit more clarity on the SVG to extract. I've gone for the simpler approach to make everything into an SVG rather than complicate the `<PreviewGraph />` component to now accept a sub-title and 2 graphs instead of 1 and conditionally style those 3 components.

**Comment by tofumatt** [comment]
Sounds good, I think this makes sense 👍🏻 

IB ✅

**Comment by tofumatt** [comment]
Just a note here: @hussain-t caught in #4868 that this change is conditional upon the `zeroDataStates` feature flag being on—if it's not enabled the old behaviour should be maintained for now. He pointed out it applies to this issue too, so I added that note in the ACs.

I don't think it requires an update to the IB, but wanted to flag it here before you start working on it @jimmymadon  🙂

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@jimmymadon the Analytics CTA is the same layout that's on WP Dashboard. Is this correct?  I couldn't find any reference but felt it was worth checking. IMO, the figma design looks better in the admin bar, but will go with whatever was decided. 

**Test site**
![image](https://user-images.githubusercontent.com/73545194/160156361-8b3adc69-9b8a-4fbc-9df9-c8f100d0d68b.png)

**Figma mock**
![image](https://user-images.githubusercontent.com/73545194/160156526-74f69c2f-8968-4f34-b231-c268101584b0.png)

**Comment by felixarntz** [comment]
@wpdarren @jimmymadon Indeed, the graphics should be on the right of the main CTA content.

I could see how this potentially causes some _other_ spacing issues, but we should follow the Figma design and then see how we can enhance it from there, if needed.

**Comment by jimmymadon** [comment]
@wpdarren @felixarntz So it does follow the Figma Design for screens wider than 1440px. This is the same breakpoint as the CTA in the Search Funnel widget. However, things do look off if I reduce this breakpoint further. The current breakpoint is already cramped as seen in Screenshot 2 below.
1. Screen width - 2380px:
<img width="2376" alt="Screenshot 2022-03-25 at 18 19 53" src="https://user-images.githubusercontent.com/1721319/160179360-114253a2-f4bc-4bf6-b919-4437fe8140d0.png">

2. Screen width - 1441px:
<img width="1440" alt="Screenshot 2022-03-25 at 18 18 02" src="https://user-images.githubusercontent.com/1721319/160179375-db279994-aca1-4136-af4a-319d51f46c46.png">

I mentioned this to the team and said I would not start a design discussion as it would have prevented this from being merged in before the E2E QA testing / bug bash. Now that this is merged, we or perhaps even the design team can have a play around and come up with some suggestions on how this can be improved. We might have to reconsider tweaking the Admin Bar as a whole too as this CTA has little space within the bar. Perhaps we can get rid of the "More details" link taking 2 cells in the grid, reduce the width of the title cell, etc.

**Comment by felixarntz** [comment]
@jimmymadon Those are all good points. I wonder if we can easily reduce the space on the left and right sections of the admin bar menu (the title on the left, and the More information link on the right). Both of these have a lot of white-space which we could possibly reduce without losing anything.

But I agree this is worth discussing as part of the bug bash, so @wpdarren if you feel good with that, let's raise this during the bug bash instead and approve for now.

**Comment by jimmymadon** [comment]
From what I could see - it is a grid - so reducing the number of cells used by the Title and the More Details section does help compared to Screenshot 2 in my comment above. We will have to restructure the inner grid too used by the 'Statistics' datablocks.
<img width="1450" alt="Screenshot 2022-03-26 at 10 07 46" src="https://user-images.githubusercontent.com/1721319/160234829-3af2d6c3-0039-4816-a03e-7330528b1cb1.png">
.

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

@jimmymadon @felixarntz I am wondering if I had a caching problem when I first looked at this because I can see the grid and correct layout now. I will do some more testing around the admin bar for the E2E and will add it on to the known issues board if I see issues on smaller screen sizes. 

**Verified:**

With zeroDataStates feature flag on:
- The new Analytics CTA component in the Admin Bar looks like the Figma mock.
- The ActivateAnalyticsCTA in SearchFunnelWidget has not changed.
- The ActivateAnalyticsCTA in on the WordPress Dashboard has not changed.

With the zeroDataStates feature flag off:
- The old ActivateModuleCTA component is rendered as normal.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/160369540-861c8a6b-3f9e-4601-989f-9d1498304cbe.png)
![image](https://user-images.githubusercontent.com/73545194/160369556-5b7902a6-c650-442e-87bc-6476528f1d68.png)
![image](https://user-images.githubusercontent.com/73545194/160369574-726df882-4554-477f-bde7-90bbf0d7ec2e.png)

</details>

**Comment by sebastianmantel** [comment]
Here are my recommendations: 

- Remove the images on small resolutions
- Change the CTA text to SET UP NOW 
- Move "More details" next to main CTA

**Comment by Pratheep-lab** [comment]
The text says "Install Google Analytics", is that the language we commonly use? But the CTA just below that says "Set up Google Analytics". 

Suggestion: Change the text "Install Google Analytics" to "Setup Google Analytics" or "Connect Google Analytics"

@sebastianmantel 
Regarding this
> Change the CTA text to SET UP NOW 

If we change the CTA, do you think most users would get it that this is about setting up for Google Analytics? It does mention in the supporting text but I guess most users wouldn't read it and they will be using the CTA to understand what is happening here. If we want to use this "Set up now" CTA, then it would be good to add a title to this:
"Connect Google Analytics" 

And regarding this:

> Move "More details" next to main CTA

The 'More details' button takes the user to the dashboard. It is not related to this zero state. So it has to be a separate item. Maybe we can keep it below the left title "Home"? 

I would suggest to remove most of the space between the Home and the first stat, so we have more space to play with.

**Comment by bethanylang** [comment]
@Pratheep-lab We have a ticket to update that "install" language here: #5005 – I noticed the same thing about "install."  :)

**Comment by marrrmarrr** [comment]
Deleting "install Google Analytics" in the main text should win some vertical space back. 
We can also shorten the text even more, e.g. "Understand what visitors do on your site". 
+1 on keeping "Google Analytics" in the overall CTA, otherwise people don't know what exactly they'll be connecting. 
"More details" actually links to the URL-level stats for that page, so it's not part of the overall CTA, we can keep it where it is for now, but would definitely be good to look at redesigning the Admin bar overall in Phase 2 of rebranding.
