### ISSUE TITLE
Update WP dashboard widget Analytics CTA to use new design

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4868]
Follow-up to #4694: This issue is about implementing the [design for the WordPress dashboard widget CTA to activate Analytics](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=885%3A2050). Related: #4867

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The blue CTA to activate Analytics in Site Kit's WP dashboard widget should be replaced with a new CTA using the [Figma design here](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=885%3A2050).
    * The implementation should use the similar components from #4694 as much as possible, potentially introduce props for minor adjustments.
* The change should be conditional on the `zeroDataStates` feature flag.
* Storybook coverage should be included.

## Implementation Brief

- Refactor `ActivateAnalyticsCTA` into a reusable global component:
    - Move `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/ActivateAnalyticsCTA.js` to `assets/js/components/` directory.
    - Similarly move the `PreviewGraph` component into the `assets/js/components/` directory.
    - Modify `assets/js/components/ActivateAnalyticsCTA.js`:
        - It should now render child nodes of the type `<PreviewGraph />` which will be passed down to it rather than calling them within this component.
    - Create a new component, `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/ActivateAnalyticsCTA.js`:
        - Use `assets/js/components/ActivateAnalyticsCTA.js` in here and pass (nest) the two `<PreviewGraph />` components above. Essentially, move the `<PreviewGraph />` components from `components/ActivateAnalyticsCTA.js` into `SearchFunnelWidget/ActivateAnalyticsCTA.js`.
    - Update references, especially where `PreviewGraph` is being used. Also, update the imports within the above components.
    - Move/rename `_googlesitekit-widget-searchFunnel.scss` to `assets/sass/components/global/_googlesitekit-analytics-cta.scss`. In `admin.scss`, update the import reference to this file (move the import reference into the Global section).
    - Make sure the styling/working of this component within the `SearchFunnelWidget` has not changed. 

- Reuse `ActivateAnalyticsCTA` component in the WP dashboard widget:
    - Create a new component, `assets/js/components/wp-dashboard/ActivateAnalyticsCTA.js`:
        - Use `assets/js/components/ActivateAnalyticsCTA.js` and pass two `<PreviewGraph />` components.
        - For the first `Traffic`, - use `assets/svg/graphics/cta-graph-traffic.svg` SVG component. Add a flag prop, e.g. `showIcons` to the `<PreviewGraph />` component that will hide the `googlesitekit-analytics-cta__preview-graph--icons` div if set to false. 
        - For the second `Most popular content`, - group all the graphics including the `Views` text and extract them as a single new SVG component - `assets/svg/graphics/cta-most-popular-content.svg` and pass it to `<PreviewGraph />` component.
        <img width="386" alt="Screenshot 2022-03-15 at 3 32 24 PM" src="https://user-images.githubusercontent.com/24408261/158353932-f533ae1d-6308-4b90-b39f-3798daf41a7b.png">

    
    - In `assets/js/googlesitekit/widgets/util/constants.js`:
        - Import `ActivateAnalyticsCTA`.
        - Export it within `SPECIAL_WIDGET_STATES` array.
      
    - In `assets/js/components/wp-dashboard/WPDashboardWidgets.js`:
        - Retrieve the `zeroDataStates` feature status via `useFeature( 'zeroDataStates' )`.
        - Destructure `ActivateAnalyticsCTA` component from `SPECIAL_WIDGET_STATES`.
        - Conditionally render `ActivateAnalyticsCTA` component if the `zeroDataStates` is enabled. Otherwise render the existing `ActivateModuleCTA` component.
        - In `assets/sass/wpdashboard.scss`, import `components/global/googlesitekit-analytics-cta`. Also import `@material/button/mdc-button` under Material Imports and `vendor/mdc-button` as these are used by the button in the new `ActivateAnalyticsCTA`. 
        - Continue to modify the CSS so that the `wp-dashboard/ActivateAnalyticsCTA.js` component matches the Figma mock in the AC.
        - Once again ensure that the working/styling of `SearchFunnelWidget/ActivateAnalyticsCTA.js` has not changed.

- Story:
    - In `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.stories.js`, ensure the `ReadyWithActivateAnalyticsCTA` has not changed.
    - Create a new story - `assets/js/components/wp-dashboard/ActivateAnalyticsCTA.stories.js`  for the WP dashboard widget analytics CTA component.

### Test Coverage

* No new tests needed.

## QA Brief

**Updated:**
- Enable `zeroDataStates` feature flag.
- Verify `ActivateAnalyticsCTA` in `SearchFunnelWidget` has not changed.
- Ensure `ReadyWithActivateAnalyticsCTA` has not changed - `modules-searchconsole-widgets-searchfunnelwidget--ready-with-activate-analytics-cta`.
- Verify `views-wpdashboardapp-activateanalyticscta--ready` story
- Verify `views-wpdashboardapp-wpdashboardwidgets--*` stories. Especially `Ready With Activate Analytics CTA` story renders as expected.
- Disable `zeroDataStates` feature flag.
- Verify `ActivateAnalyticsCTA` is not rendered. Rather the old `ActivateModuleCTA` is rendered.

## Changelog entry

* Update the Analytics Signup CTA on the WordPress Dashboard.

**Comment by tofumatt** [comment]
@hussain-t In the future, please fill in the test coverage section of the IB, even if it's "No changes needed".

I suspect no new tests are needed and none need updating for this, but it would be good to say as much in the IB 🙂 

Otherwise looks good, so I've filled it in for now.

IB ✅

**Comment by hussain-t** [comment]
Ah, I missed that. Thanks for pointing it out, @tofumatt 👍

**Comment by hussain-t** [comment]
@marrrmarrr @felixarntz, When I implement the Figma design, it doesn’t look good on large screens (min-wdth: 1440px). Since there are three widget columns for large screens in the WP dashboard.

<img width="534" alt="Screenshot 2022-03-21 at 8 39 50 PM" src="https://user-images.githubusercontent.com/24408261/159292742-9b88bcee-5751-45ad-9260-9ac57b6ecef1.png">

---------

However, if we vertically align the CTA graphs and the CTA details as we do for the smaller screens, it does look better:

<img width="537" alt="Screenshot 2022-03-21 at 8 28 29 PM" src="https://user-images.githubusercontent.com/24408261/159293192-7bb9561d-272a-4f9c-a2ce-d501bdcf7724.png">

What do you suggest?

Thanks!

**Comment by felixarntz** [comment]
@hussain-t Great catch and great idea! +1 on going with your suggestion on vertically aligning, similar to smaller screens.

**Comment by hussain-t** [comment]
Awesome, thanks, @felixarntz 👍

**Comment by hussain-t** [comment]
Thanks, @wpdarren. I have updated the QAB.

Note: @jimmymadon observed that `ActivateAnalyticsCTA` in `SearchFunnelWidget` styles have changed i.e. the graphs and description/details are vertically aligned as we have (in this ticket) for the WP dashboard widget. I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/4971) to fix this issue.

**Comment by samitron7** [comment]
Mariya had asked me to looked at this and looking the vertical align suggestion looks great!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

The `ActivateAnalyticsCTA` in SearchFunnelWidget has not changed.
Checked the `ReadyWithActivateAnalyticsCTA` has not changed in Storybook.
The `views-wpdashboardapp-activateanalyticscta--ready` story is as per the AC/Figma designs
The views-wpdashboardapp-wpdashboardwidgets--* stories renders as expected.

In addition:

- Blue CTA to activate Analytics in Site Kit's WP dashboard widget is replaced with a new CTA as per the Figma designs.
- The new design is only activated on the  the zeroDataStates feature flag.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/159865885-93b18384-530e-4b27-9f74-83faca71b1ef.png)
![image](https://user-images.githubusercontent.com/73545194/159865940-f8bef0e4-7a79-4f59-b4d8-ec5f29ef98f6.png)
![image](https://user-images.githubusercontent.com/73545194/159866000-570a6fb5-5b9b-4597-b76a-3e3df9388dfd.png)
![image](https://user-images.githubusercontent.com/73545194/159866026-cb2541c5-312f-4097-b72d-158218802f62.png)

</details>

@felixarntz I do have a minor UX/UI difference which I discussed with @hussain-t regarding the font size of the `Traffic` and `Most popular content` titles on the new CTA, as its smaller than on the figma designs. I will create a ticket for this.

**Comment by felixarntz** [comment]
### Approval ❌ 

I realize this wasn't explicitly mentioned in the ACs, but the version of the CTA for when the module setup needs to be _completed_ should always look similar to the version when the module needs to be set up.

In other words, please use the new design for the "complete setup CTA" as well, only with the button saying "Complete setup" instead.

Currently it is still the old one:
<img width="523" alt="Screen Shot 2022-03-24 at 10 52 39 AM" src="https://user-images.githubusercontent.com/3531426/159979637-f35048c8-1350-4a33-a866-f4557c252256.png">

cc. @hussain-t @asvinb @tofumatt

**Comment by hussain-t** [comment]
Thanks, @felixarntz, that’s a good catch 👍 

However, we still have the old `Complete Setup` CTA for the `SearchFunnelWidget`; do we need to change that? If so, should it be a separate ticket?

<img width="1620" alt="Screenshot 2022-03-25 at 2 08 52 PM" src="https://user-images.githubusercontent.com/24408261/160091575-80c28e24-d7bf-4b73-8e58-b80168f622fa.png">

cc: @tofumatt

**Comment by wpdarren** [comment]
@felixarntz @hussain-t @tofumatt we already have a ticket for the 'complete setup' CTA on Analytics issue. The ticket is in AC here https://github.com/google/site-kit-wp/issues/4966 - I assumed when testing this ticket that this would be picked up there. Apologies if that is not the case. I should have checked.

**Comment by felixarntz** [comment]
Ah thanks @wpdarren I hadn't seen this issue yet. I think it's safe to say for the future that any "Activate module" CTA issue should also encompass the similar "Complete module activation" CTA, that's why I flagged this above. But since there is already a separate issue to address it, I don't think we need to block this one. So I'll approve it, will add ACs to #4966.

cc @hussain-t @tofumatt @mohitwp
