### ISSUE TITLE
"Issue accessing data" notice appear when Analytics is added

### ISSUE THREAD

**Issue by andydesigns** [google/site-kit-wp#487]
## Bug Description

After successfully connecting an Analytics account an "Issue accessing data" error notice appears. Also, the data it's pulling in seems to be from someone elses account as the top content section there is a list of posts that are not mine.

I tried doing the following but it hasn't helped:
1.Disconnect the Analytics module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
2.Temporarily deactivate any caching plugin (Autoptimize, WP Super Cache etc)
3.Open Site Kit in a new incognito window (which ensures browser extensions/caching doesn't interfere with the setup process)
4.Connect the Analytics module (Site Kit > Settings > Connect other services > Analytics)

## Steps to reproduce

1.Active Site Kit
2.Settings > Connect more services > Analytics
3.Complete setup procedure

## Screenshots
<img width="1255" alt="sitekit-error" src="https://user-images.githubusercontent.com/7305414/64174993-4f9f7080-ce52-11e9-8841-b1273cd95486.png">

## Additional Context

 - PHP Version: 7.1.31
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Plugin Version [e.g. 22] 1.0.0-beta.1.0.5
 - Device: [e.g. iPhone6] Desktop

Below is the console error and full site health info:

```
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
```

<details><summary>Site Health</summary>
wp-core
version: 5.2.2
site_language: en
user_language: en
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 2
dotorg_communication: true

wp-paths-sizes
wordpress_path: /home/folder/domain.co.uk
wordpress_size: 114.24 MB (119793724 bytes)
uploads_path: /home/folder/domain.co.uk/wp-content/uploads
uploads_size: 106.55 MB (111728843 bytes)
themes_path: /home/folder/domain.co.uk/wp-content/themes
themes_size: 2.15 MB (2257400 bytes)
plugins_path: /home/folder/domain.co.uk/wp-content/plugins
plugins_size: 78.09 MB (81886179 bytes)
database_size: 12.18 MB (12767029 bytes)
total_size: 313.22 MB (328433175 bytes)

wp-dropins (1)
advanced-cache.php: true

wp-active-theme
name: Domain
version: 0.1
author: My Name
author_website: domain.co.uk
parent_theme: GeneratePress
theme_features: align-wide, editor-styles, editor-style, automatic-feed-links, post-thumbnails, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, editor-color-palette, responsive-embeds, custom-logo, menus, widgets
theme_path: /home/folder/domain.co.uk/wp-content/themes/generatepress

wp-themes (1)
GeneratePress: version: 2.3.2, author: Tom Usborne

wp-plugins-active (21)
Advanced Custom Fields: version: 5.8.3, author: Elliot Condon
Antispam Bee: version: 2.9.1, author: pluginkollektiv
Code Snippets: version: 2.13.3, author: Shea Bunge
Cookiebot | GDPR Compliant Cookie Consent and Notice: version: 2.5.0, author: Cybot A/S
GP Premium: version: 1.8.3, author: Tom Usborne
Justified Gallery: version: 1.4.2, author: Damian Góra
Kadence Blocks - Gutenberg Page Builder Toolkit: version: 1.6.8, author: Kadence WP (latest version: 1.6.10)
Lazy Blocks: version: 1.7.0, author: nK
LF Hiker: version: 1.13.0, author: epointal
Limit Login Attempts: version: 1.7.1, author: Johan Eenfeldt
LiteSpeed Cache: version: 2.9.8.5, author: LiteSpeed Technologies
Ninja Forms: version: 3.4.18, author: The WP Ninjas
Read More: version: 2.3.4.1, author: Edmon
Safe SVG: version: 1.9.4, author: Daryll Doyle
ShortPixel Adaptive Images: version: 1.2.6, author: ShortPixel
Site Kit by Google: version: 1.0.0-beta.1.0.5, author: Google
TablePress: version: 1.9.2, author: Tobias Bäthge
TablePress Extension: Responsive Tables: version: 1.5, author: Tobias Bäthge
WP Show Posts: version: 1.1.3, author: Tom Usborne
Yet Another Stars Rating: version: 2.0.3, author: Dario Curvino
Yoast SEO: version: 11.9, author: Team Yoast

wp-plugins-inactive (1)
Search & Filter Pro: version: 2.4.5, author: Code Amp

wp-media
image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1684
imagemagick_version: ImageMagick 6.9.4-10 Q16 x86_64 2017-05-23 http://www.imagemagick.org
imagick_limits:
imagick::RESOURCETYPE_AREA: 43 GB
imagick::RESOURCETYPE_DISK: 1.844674407371E+19
imagick::RESOURCETYPE_FILE: 75000
imagick::RESOURCETYPE_MAP: 43 GB
imagick::RESOURCETYPE_MEMORY: 22 GB
imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.07

wp-server
server_architecture: Linux 3.10.0-714.10.2.lve1.4.65.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.1.31 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 64M
php_post_max_size: 64M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

wp-database
extension: mysqli
server_version: 10.0.38-MariaDB-cll-lve
client_version: 10.0.38-MariaDB

wp-constants
WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/folder/domain.co.uk/wp-content
WP_PLUGIN_DIR: /home/folder/domain.co.uk/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

wp-filesystem
wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by vijayatechlabs** [comment]
I had the same issue now fixed.

Can you let me know what are seeing in

Site kit --> Settings --> Connected Services --> Analytics

is it? "**Analytics Code Snippet, Inserted by another plugin or theme**"

then that is because you're already embedded the Google analytics property code in the theme or plugin.

Kindly remove that from the theme or plugin.

Then try connecting again.

**Comment by andydesigns** [comment]
Yes I have Google Tag Manager scripts in the header of my site. If I remove these will I not lose my Tags, Triggers and Filters?

**Comment by vijayatechlabs** [comment]
For that, you can directly connect the Google tag manager service in the site kit itself.

I hope that helps.

**Comment by andydesigns** [comment]
I just tried removing the Google Tag manager scripts, then re-connected Analytics with Site Kit and still get the same issue.

**Comment by vijayatechlabs** [comment]
For me, the above steps resolved the issue.
As suggested in other threads, please clear 
1. Cache in WP
2. Cache & Cookies in the browser (use private window)

and then try again the above steps.

Meanwhile, I try to simulate the issue.

**Comment by vijayatechlabs** [comment]
Yes, I was able to simulate the issue and the above cache/cookies clearing steps worked out.

**Comment by andydesigns** [comment]
Hmmm, its rather frustrating. I tried the above, cleared my Litespeed Server Cache, then opening Incognito browser and tried reconnecting Analytics. But still have the same issue, it still appears to be pulling in data from someone elses Analytics account, not sure how.

**Comment by vijayatechlabs** [comment]
ok, did you check the connected email account, website property?
are they fine?

I would suggest you reset the Google site kit and WP dashboard and reconnect it.
Hope it helps.

**Comment by andydesigns** [comment]
Yes connected email account and property is definitely mine.

Tried resetting site kit but no change. It appears it's pulling analytics data for this website: https://www.kissthegroom.com.au/

In the top content section, this is the url of one of the posts/pages: /about/investment-kiss-the-groom-lrp/

However, the search console data IS correct and showing data for my website.

**Comment by vijayatechlabs** [comment]
Ok, then it is better to get help from Google support team.

All the best.

**Comment by jamesozzie** [comment]
@andydesigns Is there a chance another site has the same tracking code implemented on another domain? You can create your own custom report in Analytics and filter for "hostname" to check. [Here](https://support.google.com/analytics/answer/1012243?hl=en) is a guide you can use. 

Do you have any other sites you can check on, using the same web host?

**Comment by andydesigns** [comment]
Hi @jamesozzie,
I'm pretty certain when I log into my analytics account directly it's only displaying data for my domain. I've tried installing the plugin on another site of mine on the same server and the same thing happens.

However, in response to your suggestion on my original thread here: https://github.com/google/site-kit-wp/issues/12
I contacted my host about disabling ModSecurity, they said it isn't recommended but gave me a script to add to my htaccess file which would disable it. 
The script is:
```
<IfModule mod_security2.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
</IfModule>
```
After doing this and reconnecting Google Analytics it now displays the correct data!. I've only done this on the 2nd smaller site and obviously wouldn't want to leave that script in place or use it on the larger website.
So any further advice appreciated.

**Comment by andydesigns** [comment]
Hmm, it appears even after removing that script from my .htaccess file the data is displaying correctly. I'm still reluctant to try this on my larger site though.

**Comment by jamesozzie** [comment]
@andydesigns ModSecurity needs to be deactivated for initial connection only, re-enabling after should be fine. If you have access to ModSecurity yourself on your larger site you can attempt to temporarily change the "rule set type" to "Atomic Basic ModSecurity" during setup.

**Comment by hfrid** [comment]
I have the same problem.. "Issue accessing data" :/

**Comment by jamesozzie** [comment]
@hfrid  Can you attempt the following steps in order to resolve this issue. 
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching or security suite plugins in use
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)

If the above fails to resolve the error I would suggest also checking from another device. There could be local software impacting reporting (VPN, Firewall software etc). 

If the issue persists please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) and open a new issue specific for your problem.
