### ISSUE TITLE
Weird UI Experience when selecting a GA4 property on new site

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4873]
## Bug Description

Discovered what appears to be a weird UI experience.  Create a new site, and when you go to connect Analytics, you select a previously created Analytics account, and select the UA property.  Next, when you click on the dropdown for GA4 property, a red border appears around the field and when you select a property it disappears.  

It's possible the red border appears because you have to give permissions for this GA4 property,  but the red border is confusing though in my opinion, since it disappears when you select the GA4 property.  Thoughts? 

https://user-images.githubusercontent.com/73545194/155120839-4a5307df-18d0-4f58-bc9d-790f4c302960.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@asvinb would you please have a look at this and see if maybe we have a problem with the way some of our styles are applied?

**Comment by aaemnnosttv** [comment]
No longer an issue in GM2+ 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1621608/208142609-656758b4-e951-4b2d-9b10-3680b6a59db7.png">

Note: test property shown
