### ISSUE TITLE
OAuth loop when trying to setup Analytics and choosing to "Set up a new account", if Analytics was previously connected

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4874]
## Bug Description

For sites that are new to Site Kit users can encounter an OAuth set up loop if revisiting the already connected Analytics module and then choose to create a new Analytics account. This only applies to sites that had the Analytics module previously connected to an existing account via the Site Kit plugin.

A recording of this experience can be [found here](https://recordit.co/irwmfeTOUp) 

- 0.01: Connecting the Analytics module (_new site not registered before on the service_)
- 0.28: Connecting to an existing Analytics account and property
- 0.56: Editing the Analytics module and choosing to "Set up a new account"
- 1.09: After granting all permissions I'm directed back to the "Create your Analytics account" screen

A more detailed video of the same experience when disconnecting the Analytics module and connecting once more [can be found here](https://recordit.co/YsysDAYqbN). This includes all REST responses, all valid. 

## Steps to reproduce

1. Set up a new clean WordPress site (not previously used with SK)
2. Connect the Analytics module, to an existing GA account and UA property 
3. Edit the Analytics settings within SK
4. Choose to "Set up a new account" and follow the standard Analytics setup process

## Screenshots

_Gif of experience_

![2022-02-22-13-02-49](https://user-images.githubusercontent.com/41326532/155137834-8bc299df-64de-4cf8-8f5b-be318233f643.gif)

_No console errors or invalid responses_

![image](https://user-images.githubusercontent.com/41326532/155139219-9eccc3b5-914f-4703-8aa0-7c2a9ea4b6e8.png)

## Workaround
- [Disconnect your Google account](https://i.imgur.com/aEIIZsD.png) from Site Kit and connecting once more. At this point you can successfully connect the Analytics module while choosing to select a new account within the plugin
- Reset the plugin (_not ideal - all services must once again be connected for all users_)
- ~~Disconnecting the Analytics module and connecting once more~~ _The same loop occurs_
 
## Additional Context

 - This occurs for all recent versions of the plugin, including sites that have the new Unified Dashboard (older versions to be tested). Tested from 1.50 upwards so far
 - No issues with selecting a "Set up a new a new account" initially
 - This issue is only reproducible for new sites, and possibly sites that never followed the "Set up new account" process within SK 
 - There are no console errors or invalid responses, with the issues possibly OAuth related
 - This was first discovered in mid February by @adamdunnage 
 - There were changes to the GA4 API in late January 
 - Support to check this further with older versions of the plugin

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When redirecting to OAuth to grant the additional permissions to create a new Google Analytics account, it should be ensured that both the `analytics.provision` _and_ the `analytics.edit` scope are being requested (the latter is needed right after to create the associated GA4 property, since the account creation doesn't include that).
    * Currently, this only works as expected if you don't have the `analytics.edit` permission ahead of time. If you already have it, for some reason the OAuth consent screen then only prompts you for `analytics.provision`, and because of that you lose the `analytics.edit` permission afterwards, so then it prompts you again, but only for `analytics.edit`. See https://github.com/google/site-kit-wp/issues/4874#issuecomment-1048108144 for more details.

## Implementation Brief

* Update the `handleSubmit` callback to always request both "provisioning" and "edit" scopes for the Account Creation scenario IF either scope is missing at: https://github.com/google/site-kit-wp/blob/a4d97e7993e6c674687ab54898c4ea606963860b/assets/js/modules/analytics/components/common/AccountCreate/index.js#L126
* I'm not clear why when this callback was updated it checked for either provisioning or edit availability and only added the "missing" one given account creation requires both. There doesn't seem to be any harm in asking for both in this scenario, so that's what I propose 😄 

### Test Coverage

* Existing tests might need updating but no new tests are required.

## QA Brief

1. Set up a new clean WordPress site (not previously used with SK)
2. Connect the Analytics module, to an existing GA account and UA property 
3. Edit the Analytics settings within SK
4. Choose to "Set up a new account" and follow the standard Analytics setup process
5. The OAuth flow should not continuously redirect; you should be prompted to create a New Analytics account

## Changelog entry

* Fix OAuth setup loop when creating a new Analytics account.

**Comment by felixarntz** [comment]
@jamesozzie @aaemnnosttv I've replicated this bug. Some notes:

* It happens when you already have the `analytics.edit` scope ahead of creating the account in Site Kit (e.g. because you previously created a new property during the Analytics module setup).
    * What happens here is that only the `analytics.provision` scope is being requested in the OAuth redirect, even though you'll also need `analytics.edit` to afterwards create the associated GA4 property. But apparently Site Kit only recognizes that afterwards and then auto-redirects you to OAuth again right after - but the second time requesting `analytics.edit` and no longer `analytics.provision`. So in both OAuth redirects one of the two required scopes is missing.
    * Once you've granted the `analytics.edit` scope, you're of course still stuck in that loop because that's the same circumstance that you originally started with above.
* It does not happen when you don't have the `analytics.edit` scope ahead of creating the account Site Kit (e.g. because you previously chose only existing properties during the Analytics module setup).
    * Here, both the `analytics.edit` and `analytics.provision` scope are being requested in the OAuth redirect, as expected. And afterwards, the request auto-submits itself to redirect you to the Analytics TOS, from where things can proceed as usual.

We should find a fix to this sooner than later. cc @eclarke1 @FlicHollis

**Comment by felixarntz** [comment]
@tofumatt IB ✅ 

Yes, the flaw in the current logic is that, while it may seem logical to only check for missing scopes, _both_ of these scopes have to be requested if any of them is missing. That's because both of them are considered "additional scopes", so they will not be present by default, so if one of them has already been granted, it currently gets lost and therefore won't be granted anymore when requesting/granting the other one.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified that the OAuth flow is not continuously redirecting and was prompted to create a New Analytics account. Went through the setup flow and was able to create a new account. Followed the QAB successfully.
