### ISSUE TITLE
Update PageSpeed Insights widget to avoid layout shifts between loading and loaded states

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4878]
## Feature Description

The PageSpeed Insights dashboard widget has had a rather large inconsistency in its size between its loading and loaded states. This may have been a relic of its previous version which was not so tall and had a similar sized CTA on an older version of the dashboard.

Fast forward to today and the loading state is still a simple progress bar but the loaded state is over 600px (including an indeterminate list of recommendations)

**Loading ~150px tall**
![image](https://user-images.githubusercontent.com/1621608/155287052-57e82de1-a8c9-4ac4-90b2-5b91c8f7a471.png)

**Loaded ~630+ px tall**
![image](https://user-images.githubusercontent.com/1621608/155287134-047311d1-d562-475b-b472-bcc646d2808c.png)

Ideally, the height of the widget would be the same while loading – likely by using a more accurate skeleton version of the loaded component like we do with others – to avoid such a large shift in size.

We partially addressed this recently to avoid the same shift when using the re-run test feature in #4467 by preserving the current contents until the new report data was available.

This is becoming increasingly more important to address with the unified dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The field tab and lab tab should be modified so that they will _always_ have the same height, as follows:
    * Add a third tab to the Page Experience Insights widget, called "How to improve" 
       * This tab should contain any stack pack recommendations available for the site via API (right now these are displayed under the CWV / lab metrics, increasing the height of the widget).
       * Accordingly, the recommendations should no longer show when one of the other tabs is active.
    * After loading, check if there are recommendations to improve
       * if there are recommendations, display a "How to improve" CTA button on both the field and lab tabs, leading users to the new tab where they can see the recommendations 
       * if there are no recommendations, don't display the button (but still add white-space so that the height of the widget remains the same even when the button isn't there). The "How to improve" tab should remain, but if the user clicks on it they should see a zero state (one of the "side kick" zero states illustrations + "No recommendations for now").  
    * The other height inconsistency between the field and lab tabs is that with the introduction of the INP field metric, one tab may now show 4 metric rows while the other would only show 3 metric rows. To account for that, white-space should be added below the list of 3 metrics so that it would take just as much space as if 4 metrics were in that tab.
* The loading state for the widget should be adjusted so that the box has the same height as it has when the field or lab tab is shown. (While the original goal here was to also introduce a skeleton loader, this can be done in a separate issue as it would increase the scope too much; let's first focus on avoiding any layout shifts from the change between loading vs loaded.)

**Before merging a PR for this, please request an additional merge review from @felixarntz and @marrrmarrr.**

## Implementation Brief

* In `assets/js/modules/pagespeed-insights/datastore/constants.js`, add a new constant for the recommendations tab, say `DATA_SRC_RECOMMENDATIONS` with a value of `data_recommendations`.
* In `DashboardPageSpeed` (and updating styles in `_googlesitekit-DashboardPageSpeed.scss`)::
    - Add a new `<Tab>` within the `<TabBar>` component similar to the existing tabs, using the new constant created above and following the AC. 
    - Implement the component state logic to switch active tabs, i.e. create a new `setDataSrcRecommendations` function and use it in `updateActiveTab` to change the component's state. Update the `activeIndex` prop of the `<TabBar>` component.
    - Move the `<Recommendations>` component within the `<section>` above it to render conditionally if `dataSrc` is `DATA_SRC_RECOMMENDATIONS`.
    - The logic to fetch recommendations should be moved up to this component as mentioned in the next point.
    - If `dataSrc` is either lab or field, render a `<Button>` in between the `<section>` and the `footer` of the widget. Set the `onClick` to `updateActiveTab` and update the tab to `DATA_SRC_RECOMMENDATIONS`. If there are no `recommendations`, hide the `<Button>` using `visibility: hidden`. This will allow the button to still take the same space on the screen, but will hide it and remove it from the accessibility tree.

* In `Recommendations`:
    - Move the logic to fetch recommendations up to the `<DashboardPageSpeed>` component. Pass the `recommendations` down to this component as a prop. The `referenceURL` and `strategy` props can be removed if no longer required.
    - If there are no recommendations, instead of returning null, render a new `<ZeroRecommendations>`component which simply renders a SVG (any of the `zero-state-*`, e.g. `zero-state-yellow`) along with the text as per the AC.

* In `pagespeed-insights/components/common/ReportMetric.js` (and updating styles in `_googlesitekit-ReportMetric.scss`)::
    - Add a prop which will apply the `visibility: hidden` style to the entire row element.

* In `LabReportMetrics`:
    - Add an additional `<ReportMetric>` passing the new prop to make it hidden.

* In `FieldReportMetrics` (and updating styles in `_googlesitekit-DashboardPageSpeed.scss`):
    - For the "Interaction to Next Paint" metric, always render the `<ReportMetric>` (remove the current conditional rendering). However, if `interactionToNextPaint` is true, pass the new prop to make this row hidden. 

* Finally, in `DashboardPageSpeed`, render the Progress bar "on top of" the widget's content div as per this [comment](https://github.com/google/site-kit-wp/issues/4878#issuecomment-1261468900). To do this:
    - First convert the `<Cell>` that wraps the `<ProgressBar>` and the `<p>` into a normal `<div>`. Remove the outer grid elements.
    - Then convert the `<Fragment>` that renders the whole loaded component into a standard `<div>` and wrap it with another "parent" div. Set `position: relative` for the parent div.
    - Move the entire Progress Bar div into the parent div created above, adjacent to the fully loaded content div. Add the following styles to this progress bar div so that it is positioned fixed in the centre of the parent div (and it itself doesn't take any space).
        ```css
            position: absolute;
            top: 50%;
            transform: translate(-50%, -50%);
            left: 50%;
            width: 100%;
        ```
    - The above changes will always render the Progress bar div on top of the content div. Use the existing conditions to show one or the other and hide the appropriate one using `visibility: hidden`.

**Before merging a PR for this, please request an additional merge review from @felixarntz and @marrrmarrr.**

### Test Coverage

* No new tests required.

## QA Brief

- Navigate to the Dashboard and scroll down to the PageSpeed Insights widget.
- Verify that the widget's loading state is the same height as the loaded state.
  - Check this for the scenarios with/without field data, i.e. on an established site, and a new one.
- Verify that the widget has the same height for both the "In the Lab" and "In the Field" tabs.
- Note, there may be a small height discrepancy on narrower viewports, depending on the loaded report data. For example, the string "Needs improvement" wraps here and adds a bit of height, where if it was "Good" it would be shorter. I think this is probably within an acceptable margin for now, but we may want to address it in a subsequent issue.

![image](https://user-images.githubusercontent.com/18395600/198029431-51b6ddc6-718c-4511-8a07-8820a84e1efa.png)

## Changelog entry

* Update PageSpeed Insights widget to avoid layout shifts between loading and loaded states.

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr ideally I think we wouldn't show recommendations below the data as we do now as there is no way to predict the height until the report is loaded. Should we get UX involved here as well?

**Comment by aaemnnosttv** [comment]
Noting here the points we discussed earlier about a potential path forward for this widget (pending approval from UX):

* Change loading state to use a ghost/skeleton component which is as close to the loaded state as possible, using loading blocks in place of row text and values (this could likely look similar to how the component looks now when triggering the test again)
* Move recommendations to a new dedicated tab, after lab + field tabs – this is the key change which allows us to have a deterministic height on the initial load
	* It would still be possible for a layout shift to happen on the recommendations tab as there is an unknown number of items shown in the accordion that have an unknown content length. This is acceptable because the shift would happen in response to a user's action (toggling an item to expand/close) rather than something moving "by itself" as today

**Comment by sebastianmantel** [comment]
@aaemnnosttv +1 on having skeleton loader as static or animated placeholder for the information that is loading. This will represent the structure and look of the entire view card. It gives an idea to the user regarding what kind of content is loading in each card. 

For the recommendations, I would suggest to have them on the same view as they are connected with the results. You can also use skeleton as well for for this section. If having this section on the same tab makes some issues on the loading state then we can move them to a separate card bellow. Thoughts?

**Comment by aaemnnosttv** [comment]
> For the recommendations, I would suggest to have them on the same view as they are connected with the results. You can also use skeleton as well for for this section. If having this section on the same tab makes some issues on the loading state then we can move them to a separate card bellow. Thoughts?

@sebastianmantel yes, although the problem is that we cannot know how many recommendations there will be until the results are available which would still then produce a layout shift we're trying to avoid. The skeleton component for the rest of the widget is really bringing this up to date with the others we have for consistency. The remaining challenge here is how to keep the recommendations close to the results without adding height to the widget once they're available.

**Comment by sebastianmantel** [comment]
We can define a list of 3 items for the loader and to have a "View All" CTA at the bottom (also as skeleton while loading) of the card that will expand the list of items if needed. What do you think? 

<img width="582" alt="Screen Shot 2022-04-19 at 9 44 03" src="https://user-images.githubusercontent.com/102580610/163942255-274b3505-cecb-4526-b415-ebca860016e8.png">

**Comment by aaemnnosttv** [comment]
> We can define a list of 3 items for the loader and to have a "View All" CTA at the bottom (also as skeleton while loading) of the card that will expand the list of items if needed. What do you think?

@sebastianmantel that would probably work for most sites, but technically there is no guarantee that a site will have any recommendations at all. This is rather unlikely but possible a site/page may have 2 or less, or even none.

That would require us to add static "filler" recommendations (or other content of equal size) in place of missing recommendations in the event there were less than 3 to ensure the area would always load with a consistent size.

**Comment by felixarntz** [comment]
@sebastianmantel Note that we discussed with @marrrmarrr last week to have the recommendations in a separate tab (since they apply regardless of the "In the lab" or "In the field" tab). The idea from that conversation was to (in addition to the tab itself of course) display another CTA button like "See how you can improve performance" in place of where we currently show the recommendations, which would also be a simple link to the corresponding tab. According to the user study conducted earlier, people reacted quite positively about having that button (even though it didn't convey any additional information, it felt like a more actionable experience to them).

This would fix the layout shifts reliably as it would always be just this button. I'm not saying this is the decision made, and we can continue to evaluate further options, but I wanted to provide that context.

**Comment by aaemnnosttv** [comment]
> This would fix the layout shifts reliably as it would always be just this button.

@felixarntz what if there were no recommendations? Would we render that button anyways? If not, what would go in its place?

**Comment by felixarntz** [comment]
@aaemnnosttv Good question. We may either want to still render it for consistency and put some other content into the "Recommendations" tab, or alternatively we could not render the button and still reserve a little bit of extra white-space so that it matches the height of the container regardless. That may very well be little enough white-space to not look too odd.

**Comment by aaemnnosttv** [comment]
How about a "Congrats, your site rocks" button that triggers confetti when clicked? 😄

**Comment by sebastianmantel** [comment]
Thanks for clarifying Felix! I think that having a CTA that won't show any recommendations would not be a good solution. Let's render the button only if there are recommendations to show and to display an empty state on the Recommendations tab if that's the case. We can work on the content + illustration for that. What do you think?

**Comment by felixarntz** [comment]
@sebastianmantel That sounds good to me, just saying that then we'll still have to display some potentially empty white-space in place of the button when it is _not_ there. Since we don't know prior to the data being loaded whether or not the button needs to be there (again, this is to avoid any layout shift between loading and loaded state).

**Comment by aaemnnosttv** [comment]
@felixarntz stalled out I guess. Are we abandoning this in favor of the new widget(s) whenever those come or are we still planning on doing this as an intermediate enhancement? I'm still in favor of the latter, just curious if this has maybe been discussed elsewhere? cc: @marrrmarrr

**Comment by felixarntz** [comment]
@aaemnnosttv @marrrmarrr Revised the ACs (and issue title) a bit further and moved to IB.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – a few thoughts to work through:

> * Set a CORE_UI datastore value using setValue if the length of the `recommendations` array is greater than 0.

How about we simply move the selection of `recommendations` into the parent `DashboardPageSpeed` instead? It feels a bit odd to set a global flag in the store just for this case.

> * If there are recommendations and if `dataSrc` is either lab or field, then render a `<Button>` in between the `<section>` and the `footer` of the widget. Set the `onClick` to `updateActiveTab` and update the tab to `DATA_SRC_RECOMMENDATIONS`. Wrap the button in a `div` having a fixed height so that there is whitespace even if the button is not rendered.

Setting a fixed height is subject to getting out of sync with the actual height of the element it's holding a place for. Since the element is just a button, why not render it unconditionally but apply a `visibility: hidden` style (maybe also with `aria-hidden` – not sure if that's redundant or not). That way it will always hold the right amount of space without needing to use fixed values.

Maybe we can use the same kind of strategy to account for the height of the 4th metric as well?

> * Finally, in `DashboardPageSpeed`, set a fixed height to the `<Cell>` which wraps the `<ProgressBar>`. This height should be the same as the entire component after the above changes are made (addition of the `Button` and the 4 rows for metrics).

No need to get too fancy with this since the eventual skeleton loader will solve this in a more consistent way with the rest of the UI, _but_... given the above css-based strategy, what if we use the same style initially to essentially hide all of the inner content in the same way while not hiding the progress bar (maybe position fixed on top)? We would also want to ensure the progress bar wouldn't affect the height of the inner content, but I think that wouldn't be too much effort and should provide a more stable height. What do you think?

**Comment by jimmymadon** [comment]
@aaemnnosttv Great suggestions - tested your solution for the `<ProgressBar>` height fixes and have added my findings to the IB.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – this sounds good to me although it could be a little more clear as to when something should be hidden.

> * If `interactionToNextPaint` is true, render the `<ReportMetric>` for "Interaction to Next Paint" but pass the new prop to make this row hidden.

Here I think we want to _always_ render the corresponding `ReportMetric` row (unlike now), it would only be hidden if there was no data for it.

> * Move the entire Progress Bar div into the parent div created above, adjacent to the fully loaded content div. Add the following styles to this progress bar div so that it is positioned fixed in the centre of the parent div (and it itself doesn't take any space).

I have a concern about this being positioned in the middle of the component, especially on smaller screens as the widget can be rather tall. I wonder if we can position it near the top but make it sticky so that it stays in view as the user scrolls down but always contained within the widget? If it's not actually a concern for most viewports then it's probably not worth worrying about here, but seems like it could be worthwhile, also because this component's loading state is the longest.

**Comment by jimmymadon** [comment]
@aaemnnosttv Thanks - I've clarified the `interactionToNextPaint` rendering. As for the `<ProgressBar>`, I think this is going to be a short term change - probably might not even be released if we implement #5776 in the same release. The skeleton loader which will be implemented in #5776 will overwrite this so we should probably not spend too much time perfecting this?

**Comment by aaemnnosttv** [comment]
SGTM, thanks @jimmymadon 👍 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil 

-Verified on dev environment.

Question :> I noticed that in case of any encountered error PageSpeed Insights widget layout is getting shifts between loading and loading states. Is it acceptable in the case of errors ?

2) If field data is not available then also "In the field" tab height is getting smaller than "In the lab" tab and also "how to improve" button is also showing. 

<details>


https://user-images.githubusercontent.com/94359491/199027905-5ddc63c3-f444-4426-8647-6bed2ba0453f.mp4

![image](https://user-images.githubusercontent.com/94359491/199028448-ffd57e0d-2b93-411b-8fde-8d7082afcaa7.png)

![image](https://user-images.githubusercontent.com/94359491/199029004-0c40ec47-504f-4d5f-9434-147432bb53c7.png)

</details>

**Comment by techanvil** [comment]
Hi @mohitwp, thanks for your comment. To answer your questions:

Q1) Yes, it is acceptable for the layout to shift if the widget encounters errors. We have to choose a fixed height loading state because we don't know whether there are any errors until the widget has loaded. So it's not possible for us to show a loading state that works for both success and error states. That is, unless we update the widget to be the same height for success and error states, but that is not what has been specced out in this issue. In real-world usage, the error case should be pretty unusual and so I think it's acceptable for there to be a layout shift in this uncommon scenario.

Q2) It is expected for the "In the Field" tab to have a shorter height when there is no field data, that is also as specced, and doesn't affect the layout shift between loading and loaded states. When there is no field data the "In the Lab" tab is shown first, so although there is a layout shift when clicking on "In the Field", this is in response to a user action so it's more acceptable for there to be a shift of layout as the user will be expecting something to happen.

**However**, the "How to improve" button _does_ look a bit out-of-place on the "In the Field" tab when the "Field data unavailable" message is displayed. I will create a followup PR to hide the button in this case.

Q3) This just means the recommendations should no longer show on the "In the Lab" or "In the Field" tabs. For example they were previously displayed like this:

![image](https://user-images.githubusercontent.com/18395600/199217545-552b5466-cd50-491a-a935-b966406d3bbe.png)

**Comment by aaemnnosttv** [comment]
## ⚠️ QA

I just noticed that this change has resulted in the mobile report for PSI to be requested on the initial load of the dashboard, even when the Speed section is not active. This regression is due to this `useSelect` that moved from an inner component where it wouldn't have been invoked previously.

All of a component's report-based selectors for a widget should use `useInViewSelect` to lazy-load these requests. In this case, it's less obvious that a report selector is being called because it's done so within `getAuditsWithStackPack -> getAudits -> getReport`.

@techanvil would you please open a follow-up PR to address this?

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, good spot there. I have raised a followup PR, #6097.

**Comment by aaemnnosttv** [comment]
Thanks @techanvil ! Back to you for a final pass @mohitwp 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @techanvil @aaemnnosttv !

- Verified on main environment.
- Verified points mentioned under AC.
- Verified new added tab "How to improve".
- Verified 'In the Lab" and "In the field" tab have same height.
- Verified widget loading and loaded state have same height if widget don't encountered errors.
- Verified that "How to improve" button showing under "In the Lab" and "In the field" tab when there are recommendations to improve.
- Verified clicking on "How to Improve" button navigates user to "How to improve" tab.
- As per Tom in case widget encountered errors layout shift is acceptable. https://github.com/google/site-kit-wp/issues/4878#issuecomment-1298350549
- Issue mentioned [here](https://github.com/google/site-kit-wp/issues/4878#issuecomment-1297157100) is now fixed. If field data is not available in this case "How to improve" button is not showing.
- Verified PSI widget on both main and entity dashboard.

<details>


In case of error -

![image](https://user-images.githubusercontent.com/94359491/199671983-f58cd775-6140-42de-9081-873c16e334ad.png)

![image](https://user-images.githubusercontent.com/94359491/199672028-a981bb52-ca28-4ac7-86bb-7ca43c8c78b7.png)

![image](https://user-images.githubusercontent.com/94359491/199672087-1e5e1342-c070-458b-9004-e5833ba040b2.png)

![image](https://user-images.githubusercontent.com/94359491/199672123-11f1f581-e3a0-4914-afb1-2f288675c81e.png)

Field data not available -

![image](https://user-images.githubusercontent.com/94359491/199672177-73a74728-a6c4-4f05-baea-d4872faf7531.png)

</details>
