### ISSUE TITLE
Ensure all previous old dashboard links redirect to the new Unified Dashboard

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4883]
## Feature Description

For sites that are migrated to the Unified Dashboard ensure all previous dashboard links are directed to the main dashboard. These links include the below:
- https://site.com/wp-admin/admin.php?page=googlesitekit-module-search-console
- https://site.com/wp-admin/admin.php?page=googlesitekit-module-adsense
- https://site.com/wp-admin/admin.php?page=googlesitekit-module-analytics

At present any user who may happen to visit these old wp-admin dashboard pages will land on a 403 page. 

![image](https://user-images.githubusercontent.com/41326532/155361167-1fc251ca-d5b6-4ef5-bca9-c8e0ed833d2a.png)

![image](https://user-images.githubusercontent.com/41326532/155360842-75f22074-c06f-4507-af4b-29a45c5a98b5.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is being done as part of https://github.com/google/site-kit-wp/issues/4865 for the current release now 👍
