### ISSUE TITLE
Ensure missing admin bar doesn't cause JavaScript errors

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#49]
**Describe the bug**
Site Kit currently expects the admin bar to exist while in the backend, in various areas of the code. This should not be relied on as it is possible for the admin bar to not exist even in the WordPress backend (e.g. on a Site which uses the WordPress.com admin bar provided by the Jetpack plugin). This for example causes the JavaScript error reported in #11.

Let's make sure that, wherever in the plugin we access a node that is part of the admin bar, we check for whether that node actually exists before executing logic on it.

**Comment by ThierryA** [comment]
@bjackson27 has this been QA'ed?
