### ISSUE TITLE
Idea Hub CTA graphic shouldn't include year

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4905]
## Bug Description

Very minor but an observation on the new Idea Hub CTA at the top of the dashboard and also within the widget.  The graphic says ‘What house plants are trending in 2021’  Do you think we should remove the year since we’re now in 2022?

Maybe it would best to say ‘What house plants are trending now?’  

![ideahub.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/5824204a-c6c9-4ef0-b8e0-7cb1f9cc9758)

## Steps to reproduce

1. Connect Idea Hub via the Tester plugin
2. Go to the dashboard and observe CTA at the top and in widget. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
When we get to the ACs here, worth noting this Asana issue raised by @mohitwp https://app.asana.com/0/1202559929559690/1202595662085207 that demonstrates the graphic is now in the old GM2 branding, and needs updating to Gm2+ branding. 
We can ask UX/design to provide us a new graphic here.

**Comment by aaemnnosttv** [comment]
After discussing with the team, we decided this isn't worth actioning right now as all the people who have Idea Hub available to would have likely seen this already.

Regarding the consistency of styling, this may be worth revisiting for GM3 but not worth the effort right now.
