### ISSUE TITLE
WP Dashboard: Update the popular pages widget to correctly display the gathering data state.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#4908]
## Feature Description

Following on from the work in #4711, on the WP Dashboard, when the Analytics widgets **Unique Visitors** and **Avg. Time on Page** are showing the _gathering data..._ text, the blue Analytics Gathering Data CTA should not be displayed.

See related [comments](https://github.com/google/site-kit-wp/pull/4903#issuecomment-1057291011) on the PR for #4711 for more information.

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/0db55d8b-3edd-45e0-8081-aed148e4c4ea)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* These changes are only relevant when the `zeroDataStates` feature flag is enabled.
* The `WPDashboardPopularPages` component should display the gathering data state correctly when the `isGatheringData` returns true for the Analytics module.
* In order to reproduce this scenario, follow the QA Brief in #4711.

## Implementation Brief

* In the `assets/js/components/wp-dashboard/WPDashboardPopularPages.js` file:
  * Get the `zeroDataStates` feature flag.
  * Update the condition that returns the `WidgetReportZero` element to do so only when the `zeroDataStates` feature flag is not enabled. https://github.com/google/site-kit-wp/blob/372a83b9ac570045311cefa1397c0b6f4230c454/assets/js/components/wp-dashboard/WPDashboardPopularPages.js#L114-L116
  * Add the `gatheringData={ isGatheringData }` property to the `ReportTable` element.

### Test Coverage

* N/A

## QA Brief
* Using the tester plugin, force the "gathering data" state.
* Activate the "zeroDataStates" feature flag
* Go to the main WordPress dashboard
* Verify that the "Analytics" widgets show the "gathering data..." text instead of the blue CTA.
* Disable the "zeroDataStates" feature flag
* Verify that the blue CTA is displayed. 

## Changelog entry

* Update gathering data UI in WordPress Dashboard widget.

**Comment by tofumatt** [comment]
ACs here look great, so moving this to IB 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
@asvinb 

**Issue** : On WP dashboard analytics widget showing error.

`Cannot read properties of undefined (reading 'forEach')

    in WPDashboardPopularPages
    in WithWidgetComponentProps(WPDashboardPopularPages)
    in div
    in WPDashboardWidgets
    in div
    in WPDashboardApp
    in RestoreSnapshots
    in ErrorHandler
    in Root`
```


```
**Steps:**
- Using the tester plugin, force the "gathering data" state.
- Activate the "zeroDataStates" feature flag
- Go to the main WordPress dashboard
- Analytics widget showing error.

![image](https://user-images.githubusercontent.com/94359491/159640486-1db06a8f-2414-442f-ba64-40c46ab09dfa.png)
```

**Comment by mohitwp** [comment]
@asvinb Error was showing because gathering state was not selected for analytics under tester plugin.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified:
- When "zeroDataStates" feature flag ia active then on WP dashboard page tthe "Analytics" widgets show the "gathering data..." text instead of the blue CTA.
- When "zeroDataStates" feature flag is not active then the blue CTA is displayed.
- Also, verified after activating 'servicesetupv2' and dashboard sharing feature flag.
- Verified on the latest versions of Firefox,Chrome, Edge and safari.

<details>

Screenshot 1: When "zeroDataStates" feature flag is active.

![image](https://user-images.githubusercontent.com/94359491/159663950-3428987b-9a5f-4571-b986-6dd850514cfc.png)

Screenshot 2: When "zeroDataStates" feature flag is not active.

![image](https://user-images.githubusercontent.com/94359491/159664109-86ab4109-33e2-4c07-bd66-3639c7f70251.png)


</details>

**Comment by techanvil** [comment]
## QA :x:

Unfortunately I am seeing the same error @mohitwp raised previously:

![image](https://user-images.githubusercontent.com/18395600/160160610-c55da06d-80ac-4ca5-86b0-24816e59762f.png)

This is on a freshly created site, with the `zeroDataStates` feature flag enabled, which is in a legitimately "gathering data" state as evident elsewhere:

![image](https://user-images.githubusercontent.com/18395600/160160862-f71d93f1-bf71-413f-b816-608bb1d8808f.png)

To be clear, the "gathering data" state is _not_ selected in the Tester plugin.

Looking at the JS console, I can see that `rows` is `undefined` on line 119 of [`WPDashboardPopularPages.js`](https://github.com/google/site-kit-wp/blob/baeffe75d5dba7014270a7dc8b11200f627e27a1/assets/js/components/wp-dashboard/WPDashboardPopularPages.js#L119):

![image](https://user-images.githubusercontent.com/18395600/160161451-4e5005e9-7137-4003-8cea-1a8ae99a0f93.png)

**Comment by aaemnnosttv** [comment]
Reopening due to a bug caught during release QA: https://github.com/google/site-kit-wp/issues/4960#issuecomment-1079220231

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

Can confirm that with `zeroDataStates` enabled, and not using the tester plugin for gather state, no error is appearing on the FE or in console with `main` branch.  I do have a few observations re the WP Dashboard Site Kit widget, and will highlight them as part of our E2E testing for Zero Data States. 

For now this passes the initial issue with the error message. 

![image](https://user-images.githubusercontent.com/73545194/160324887-598539db-93c9-4df9-9cc3-522439b3a852.png)

**Comment by felixarntz** [comment]
### Approval ⚠️ 

It looks like the approach from #4977 was not quite correct, as now the table gets entirely hidden in "zero" or "gathering" data states. It should still display though, just with the sentence that it is either "gathering data" or that there aren't enough visitors yet - similar to how the similar table on the dashboard works. cc @aaemnnosttv

**Comment by felixarntz** [comment]
### Approval ✅ 

Aside: I opened #4990 to complete some missing Storybook coverage around this area.
