### ISSUE TITLE
Rename AdSense `GET:earnings` endpoint to `GET:report`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4914]
For more consistent naming (both with the actual AdSense API endpoint and our other reporting endpoints in the plugin), the AdSense datapoint `GET:earnings` should be renamed to `GET:report`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense `GET:earnings` endpoint should be renamed to `GET:report`.
* All references using that endpoint need to be adjusted accordingly.

## Implementation Brief
* Using `includes/Modules/AdSense.php`, update `GET:earnings` to `GET:reports` across the file.
* Using `assets/js/modules/adsense/datastore/report.js`, replace `earnings` by `reports` in `controlCallback`.

### Test Coverage
* Update `tests/phpunit/integration/Modules/AdSenseTest.php` and `assets/js/modules/adsense/datastore/report.test.js` to reflect above changes.

## QA Brief

* This doesn't have any visual effect on the interface, just changes a bit of the way how the AdSense module in the front-end interacts with the back-end and data source.
* QAing this would require making sure the AdSense module displays the data as expected without any errors or anomalies.

## Changelog entry

* Rename AdSense REST data point `GET:earnings` to `GET:report`.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The AdSense module displays the data as expected without any errors on FE or within console. 
- Tested this on a site without tester plugin, data displays as expected.
- Tested this on a site with tester plugin, data displays as expected. 
- Tested on a site with forced gathering and zero data for AdSense, displays as expected.
- Tested this with AdSense V2 feature flag enabled and disabled.
