### ISSUE TITLE
Layout Shift when jumping sections and refreshing the page in Safari, Firefox and chrome browser.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#4920]
## Bug Description

**Issue 1 > Safari Browser**
While navigating to chips and refreshing the page layout shifts happening on the Unified Dashboard.
If analytics is not connected and content widget is not showing data then after navigating to 'Content' chip when user refreshes the page then it shows 'Traffic' chip active instead of 'Content' Chip.

#### Steps to reproduce

1. Go to 'Dashboard'
2. Make sure analytics module is not connected.
3. Click on 'Content' chip.
4. Refresh the page.
5. See error

**Issue 2 > Browser Browser**
While navigating to chips and refreshing the page layout shifts happening on the Unified Dashboard.
After navigating to other chips, when user clicks on 'Traffic chip' and refreshes the page then it creates layout shift.

#### Steps to reproduce

1. Go to 'Dashboard'
2. Click on 'Monetization' or any other chip except Traffic.
3. Click on 'Traffic' chip
4. Refresh the page.
5. See error

**Issue 3 > Firefox Browser**

While navigating to chips and refreshing the page layout shifts happening while jumping between sections on the Unified Dashboard.
If the user navigates from 'Traffic' or 'Content' chip to directly 'Monetization' chip and refreshes the page, then it creates layout shift.

#### Steps to reproduce

1. Go to 'Dashboard'
2. Click on 'Traffic or content'
3. Click on 'Monetization' chip.
4. Refresh the page.
5. See error

## Screenshots/Screencast

**Safari**

https://user-images.githubusercontent.com/94359491/155929054-6c83b6e3-f68a-4306-8897-2da949890a1a.mp4

**Firefox**

https://user-images.githubusercontent.com/94359491/155926082-a63b0da8-5d47-478c-b871-fdc1922c2cb0.mp4

**Chrome**

https://user-images.githubusercontent.com/94359491/155927631-98ce80fc-c6a6-4e9c-be77-71411cb55898.mp4

## Additional Context

  - PHP Version: 8.00
 - OS: [mac OS Monterey] [Windows 11]
 - Browser: [Safari 15.1] [Firefox – Version 97.0.1] [Chrome : Version 98.0.4758.102]
 - Plugin Version: [1.69]
 - Tool: BrowserStack
 - Device: [Laptop -1519 × 746]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
I'm not sure there is much that can be done about this without persisting datastore state between page loads or fixing the height of all widgets to be consistent between loaded and unloaded states.

**Comment by aaemnnosttv** [comment]
@mohitwp would you please take another look here now that #4878 has been applied?

**Comment by mohitwp** [comment]
@aaemnnosttv 
Verified on latest versions of Chrome, Firefox, and Safari.
I'm not able to replicate the layout shift issue. 
We can close this issue.

**Comment by aaemnnosttv** [comment]
Thanks @mohitwp – closing for now 👍
