### ISSUE TITLE
The do_parse_request filter change might affect Site Kit in WordPress 6.0

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4923]
## Bug Description

There is a change in the upcoming WordPress 6.0 release that stops unnecessary queries when developers are using the `do_parse_request` filter. 

> The search found 133 plugins using the filter. Some of the most popular ones include **Google’s Site Kit plugin (1M+ installs)**, The Events Calendar (800K installs), and AMP (500K installs). Harris suggested the change requires a dev note, as it may have unanticipated side effects. The dev note is likely to be published closer to the time of release. 

Reading [this post](https://wptavern.com/wordpress-6-0-to-introduce-performance-improvements-for-custom-pages) it would appear that we might have to investigate what impact this could have on Site Kit plugin due to the change. 

WordPress 6.0 is currently scheduled for release on May 24, 2022.

c.c. @felixarntz 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@wpdarren Thanks for flagging this. After a review of our usage of this filter, I can say that it won't be affected by the change. We only use it to add another filter, in a way that won't be affected by the code change.
