### ISSUE TITLE
Fix OAuth Client Tests that return Invalid JSON Response

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#4926]
## Feature Description

The PHPUnit tests below which test for a successful call to `OAuth_Client::refresh_token()` currently consider an `Invalid JSON Response` error to be a successful scenario.

https://github.com/google/site-kit-wp/blob/8184221884dc3fea035db83463a8a48b7f6de9c8/tests/phpunit/integration/Core/Authentication/Clients/OAuth_ClientTest.php#L69-L70

https://github.com/google/site-kit-wp/blob/d2ee68a10d1800a037f2eac8314cafee10adee9d/tests/phpunit/integration/Core/Authentication/AuthenticationTest.php#L317-L321

https://github.com/google/site-kit-wp/blob/d2ee68a10d1800a037f2eac8314cafee10adee9d/tests/phpunit/integration/Core/Authentication/AuthenticationTest.php#L377-L381

This is because these tests set the `FakeHttpClient` to be used by the `Google_Site_Kit_Client` object (`$oauth_client->google_client`) when making an Http request to fetch an OAuth2 token. 
https://github.com/google/site-kit-wp/blob/8184221884dc3fea035db83463a8a48b7f6de9c8/tests/phpunit/integration/Core/Authentication/Clients/OAuth_ClientTest.php#L66

The FakeHttpClient handler always returns a 200 code with an EMPTY response below. So attempting to parse this empty response as JSON fails and results in an error. 
https://github.com/google/site-kit-wp/blob/8184221884dc3fea035db83463a8a48b7f6de9c8/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php#L257-L258

However, as far as the tests are concerned, it still denotes successful calls to:
`OAuth_Client::get_refresh_token()` 
  --> `Google_Site_Kit_Client::fetchAccessTokenWithRefreshToken()` 
  --> `Google_Site_Kit_Client::fetch_auth_token()`
eventually denoting a successful request. 

Asserting if an error exists for a successful test scenario can be confusing/misleading and should be fixed. New tests being added are using a similar approach [deemed to be confusing as per this comment.](https://github.com/google/site-kit-wp/pull/4915#discussion_r820869191)

A possible solution could be to use something like:
https://github.com/google/site-kit-wp/blob/372a83b9ac570045311cefa1397c0b6f4230c454/tests/phpunit/integration/Core/Authentication/Google_ProxyTest.php#L537-L547

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The usage of `FakeHttpClient` in tests that include assertions for `Invalid JSON response` should be updated to allow for more useful assertions
* `OAuth_Client_Base::set_token` should be updated such that it clears any `googlesitekit_error_code` when called

## Implementation Brief

* Finish and merge https://github.com/google/site-kit-wp/compare/enhance/4926-fake-http-client
    * Update `AuthenticationTest::test_register_maybe_refresh_token_for_screen__admin` and `test_register_maybe_refresh_token_for_screen__editor_with_shared_modules` with assertion that token was refreshed using a similar pattern
    * Update `OAuth_Client_Base::set_token` to clear the `OAuth_Client::OPTION_ERROR_CODE` user option before storing the new token

### Test Coverage

* No change in coverage, existing tests will be updated

## QA Brief

- The PR fixes the existing unit tests. There are no new changes to be tested. Ensure the following updated PHP tests are passing. Testing could be done as part of CR so that we can skip the QA process:
   * `test_refresh_token`
   * `test_register_maybe_refresh_token_for_screen__admin`
   *  `test_register_maybe_refresh_token_for_screen__editor_with_shared_modules`

## Changelog entry

* N/A.

**Comment by aaemnnosttv** [comment]
> A possible solution could be to use something like:

@jimmymadon oAuth requests made by the Google Client use Guzzle internally so we can't use the `pre_http_request` filter like we do for WP HTTP requests, hence the `FakeHttpClient`. Instead, we can configure the request handler of the fake client to return something more "real" to avoid such confusing assertions.

**Comment by aaemnnosttv** [comment]
@felixarntz does the 2nd point of the AC sound good to you? I noticed the only place we delete this is in `Authentication::inline_js_base_data` which seems incorrect if the token was set successfully before this were to happen.

**Comment by felixarntz** [comment]
@aaemnnosttv SGTM!

**Comment by tofumatt** [comment]
No QA needed as this is a test-only change—moving directly to approval.
