### ISSUE TITLE
New Analytics Goals CTA looks squeezed on small screens

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#4930]
## Bug Description

While testing https://github.com/google/site-kit-wp/issues/4694 . We have noticed that blue box CTAs for goal is looking stretched in small desktop screens (laptops) and tablets.
My Laptop viewport is **1519 × 746** and Goal CTA is showing stretched in this size. Also in iPad 12 same issue is coming.

**i-pad 12**
Screen Size -12.9 in - 10.32 x 7.74 in
Resolution- 2048 x 2732 px
Viewport -1024 x 1365 dp

## Steps to reproduce

1. Enable the 'zeroDataStates' and 'unifiedDashboard' feature flags.
2. Connect the Analytics module, to an account with analytics data but no goals set up.
3. Verify the Create a new goal CTA appears as per the AC / Figma design.
4. See issue.

## Screenshots
Windows Laptop
 ![image](https://user-images.githubusercontent.com/94359491/156732609-926b367e-8c1d-4ad4-8136-dc9e2f012f12.png)

iPad 12
![image](https://user-images.githubusercontent.com/94359491/157422655-ceebd0ee-2db9-41a1-b545-6cdb96d07ce4.png)

## Additional Context

 - PHP Version: 
 - OS: [Windows 11 and Mac]
 - Browser: [chrome, safari,firefox and edge]
 - Plugin Version: [8.0]
 - Device: [Windows laptop,iPad12 ]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by wpdarren** [comment]
@mohitwp should this ticket be tagged for Zero Data States?  Any tickets we create as part of QAing an epic should have the epic assigned to them so they can be assigned to a sprint and worked on.

**Comment by mohitwp** [comment]
CTA design got update. But it is still inconsistent. I created a new site with same configuration and tester plugin settings but not getting updated CTA design. One of the older site I'm getting updated design and not in other one. So, it is inconsistent. I'll investigate further later.

**Comment by marrrmarrr** [comment]
A couple of comments on the different elements in Mohit's screenshots:
- Is it possible to reshuffle the elements in the GA Goals CTA, so that the ghost chart and the CTA button are vertically stacked. That way, both these elements wouldn't be stretched so much (e.g. right now there's a ton of white space between the heading "goals completed" and the ghost chart illustration.
- The "gathering data" state for GA should appear as the new version, not as a blue box.

**Comment by marrrmarrr** [comment]
+1 to stacking on more viewports (perhaps not the super-wide desktop one, but everything else). Would be great to see how this looks.

**Comment by felixarntz** [comment]
+1 to stacking in more viewports where needed. The only issue with the stacking (as already visible in one of the issue description screenshots) is that it makes the other metrics left of it have a lot of vertical whitespace. The alternative here would be to not show the graphic on those viewports at all - maybe worth considering.

**Comment by FlicHollis** [comment]
Hi @felixarntz and @marrrmarrr thanks for the feedback. Are we considering this a launch blocker (e.g should this be prioritised within Sprint 72)?

**Comment by eclarke1** [comment]
@marrrmarrr further to the comment from @felixarntz on the [issue in the bug bash board](https://app.asana.com/0/1201999381911618/1202017191805488) could we kindly ask you to review this and advise whether we need UX input (probably!)

**Comment by felixarntz** [comment]
@marrrmarrr As flagged by @jimmymadon in Asana, the problem here is very similar to https://github.com/google/site-kit-wp/issues/4867#issuecomment-1079299331. These should be reviewed together to come up with a solution that works for both situations.

**Comment by sebastianmantel** [comment]
My recommendation would be to remove the image on small resolutions and to modify the CTA text to "Create Goal".

**Comment by marrrmarrr** [comment]
@sebastianmantel let's look at all of them together (including [the other CTA](https://github.com/google/site-kit-wp/issues/4867#issuecomment-1079299331)) and define a new design as part of the branding work.

**Comment by felixarntz** [comment]
@marrrmarrr Moving this to Stalled for now. Feel free to move back to another column once we can realistically pick this up.

**Comment by aaemnnosttv** [comment]
Closing as this CTA is no longer shown on the (newer & only) GA4 version of the dashboard.
