### ISSUE TITLE
Update outdated documentation URLs

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#4935]
## Bug Description

With the documentation updates that have been rolling out over the past few months, there are now some outdated URLs within the product. We'll be setting up redirects for old URL > new URL, but we should also update that links in product to use the new URLs.

<details>
<summary>The following URLs need to be updated:</summary>

1. Help icon > Fix common issues

<img width="437" alt="image" src="https://user-images.githubusercontent.com/12189958/157865605-7c76987c-b670-4562-990c-73962ce91d2c.png">

Change from https://sitekit.withgoogle.com/documentation/fix-common-issues/ to https://sitekit.withgoogle.com/documentation/troubleshooting/fix-common-issues/

2. Create your Analytics Account (/wp-admin/admin.php?page=googlesitekit-module-analytics&slug=analytics&reAuth=true&notification=authentication_success) > This will create both a Google Analytics 4 and Universal Analytics property. > Learn more

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/12189958/157866012-10e5a171-285a-478c-8960-f32de5b3acd2.png">

Change from https://sitekit.withgoogle.com/documentation/ga4-analytics-property/ to https://sitekit.withgoogle.com/documentation/using-site-kit/ga4/

3. Analytics post-setup banner (/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=analytics) > You’ll only see Universal Analytics data for now. Learn more

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/12189958/157866604-a63afe34-12b4-497d-92d2-0759bea61a4d.png">

Change from https://sitekit.withgoogle.com/documentation/ga4-analytics-property/ to https://sitekit.withgoogle.com/documentation/using-site-kit/ga4/

These are the ones that I could find on my own, but to be safe, is it possible to do a search for any of the following URLs appearing in the product? I've listed them along with what URL they should be changed to if found:

* https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/staging/
* https://sitekit.withgoogle.com/documentation/install/ > should be https://sitekit.withgoogle.com/documentation/getting-started/install/
* https://sitekit.withgoogle.com/documentation/choose-tools/ > should be https://sitekit.withgoogle.com/documentation/getting-started/connecting-services/
* https://sitekit.withgoogle.com/documentation/idea-hub-module/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/idea-hub/
* https://sitekit.withgoogle.com/documentation/known-limitations-of-site-kit/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/known-limitations/
* https://sitekit.withgoogle.com/documentation/find-your-way-around-site-kit/ > should be https://sitekit.withgoogle.com/documentation/getting-started/find-your-way-around-site-kit/
* https://sitekit.withgoogle.com/documentation/uninstall/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/uninstall/
* https://sitekit.withgoogle.com/documentation/permission-levels/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/permissions/
* https://sitekit.withgoogle.com/documentation/anonymize/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/gdpr-compliance-and-privacy/
https://sitekit.withgoogle.com/documentation/feedback-survey/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/feedback-survey/
* https://sitekit.withgoogle.com/documentation/configure-site-kit-wp-config-keys/ > should be https://sitekit.withgoogle.com/documentation/using-site-kit/configure-site-kit-wp-config-keys/
</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following URLs should be changed across the entire repo, including in the `SUPPORT.md` document:
  * `https://sitekit.withgoogle.com/documentation/fix-common-issues/` to `https://sitekit.withgoogle.com/documentation/troubleshooting/fix-common-issues/`
  * `https://sitekit.withgoogle.com/documentation/ga4-analytics-property/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/ga4/`
  * `https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/staging/`
  * `https://sitekit.withgoogle.com/documentation/install/` to `https://sitekit.withgoogle.com/documentation/getting-started/install/`
  * `https://sitekit.withgoogle.com/documentation/choose-tools/` to `https://sitekit.withgoogle.com/documentation/getting-started/connecting-services/`
  * `https://sitekit.withgoogle.com/documentation/idea-hub-module/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/idea-hub/`
  * `https://sitekit.withgoogle.com/documentation/known-limitations-of-site-kit/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/known-limitations/`
  * `https://sitekit.withgoogle.com/documentation/find-your-way-around-site-kit/` to `https://sitekit.withgoogle.com/documentation/getting-started/find-your-way-around-site-kit/`
  * `https://sitekit.withgoogle.com/documentation/uninstall/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/uninstall/`
  * `https://sitekit.withgoogle.com/documentation/permission-levels/` to` https://sitekit.withgoogle.com/documentation/using-site-kit/permissions/`
  * `https://sitekit.withgoogle.com/documentation/anonymize/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/gdpr-compliance-and-privacy/`
    `https://sitekit.withgoogle.com/documentation/feedback-survey/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/feedback-survey/`
  * `https://sitekit.withgoogle.com/documentation/configure-site-kit-wp-config-keys/` to `https://sitekit.withgoogle.com/documentation/using-site-kit/configure-site-kit-wp-config-keys/`

## Implementation Brief

* Replace all of the URLs across the entire repo with the new ones above.

### Test Coverage

* Update any tests/etc. that check for these values or mock the URLs.

## QA Brief

- Verify the URLs mentioned in the AC are replaced with the new ones
- Note the following URLs from the AC aren't included in the plugin:
```
https://sitekit.withgoogle.com/documentation/install/
https://sitekit.withgoogle.com/documentation/known-limitations-of-site-kit/
https://sitekit.withgoogle.com/documentation/find-your-way-around-site-kit/
https://sitekit.withgoogle.com/documentation/uninstall/
https://sitekit.withgoogle.com/documentation/permission-levels/
https://sitekit.withgoogle.com/documentation/anonymize/
https://sitekit.withgoogle.com/documentation/feedback-survey/
https://sitekit.withgoogle.com/documentation/configure-site-kit-wp-config-keys/
```

## Changelog entry

* Update documentation URLs.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by jimmymadon** [comment]
## QA Eng ✅ 

✅ Verify the URLs mentioned in the AC are replaced with the new ones
