### ISSUE TITLE
OAuth 'no client secret' error and failure to setup Site Kit when Google Private Calendars plugin is active

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#4941]
## Bug Description

As reported by a user in the support forums it seems that when trying to set up Site Kit on a site with the Private Google Calendars plugin active you get an OAuth 'no client secret' error message with Site Kit failing to complete setup.

![image.png](https://images.zenhubusercontent.com/615c17989165ed44b4b3f263/bd54b7a2-6aad-439e-90fc-e91d90b41629)

Disabling the plugin and trying setup once more will allow setup and enabling once Site Kit has been set up doesn't seem to cause any issues. It only affects the initial setup. 

Here is an example callback url that I get when encountering this: 
https://agreeablename.s2-tastewp.com/wp-admin/index.php?oauth2callback=1&code=sitekit-d7Vtc2Uq5LXnrdNT9HTskh

**Headers:** 
![image.png](https://images.zenhubusercontent.com/615c17989165ed44b4b3f263/9635c51f-c8d5-4b34-9d9f-0a5727b6b82d) 

**Video recording of experience:** 

https://user-images.githubusercontent.com/91896826/158160824-21ccda81-0b28-46d0-a856-af2a7c1be5cf.mp4

## Steps to reproduce

1. Create a fresh new WordPress site.
2. Install the [Private Google Calendars plugin](https://wordpress.org/plugins/private-google-calendars/) and activate.
3. Install Site Kit and attempt initial setup.

## Additional Context

Support forum topic: 
https://wordpress.org/support/topic/conflict-with-private-google-calendars/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
I encountered the same, after disconnecting a previously connected site and attempting to connect once more. Recording of experience below:
 

https://user-images.githubusercontent.com/41326532/158176675-a061067c-16b5-4314-9b27-634e0aa5c784.mp4


Image below showing errors output:
![image](https://user-images.githubusercontent.com/41326532/158176425-4f564c05-6c5b-48c2-918b-5a4b5314b235.png)

Line 1084 function can be seen at the link below:
https://plugins.trac.wordpress.org/browser/private-google-calendars/trunk/private-google-calendars.php#L1084

Line 1130 function can be seen at the link below:
https://plugins.trac.wordpress.org/browser/private-google-calendars/trunk/private-google-calendars.php#L1130

Nothing was logged as a PHP error, and no invalid http requests (all evident from the above video).

**Workaround**: From testing this only occurs during setup. For impacted users they can temporarily deactivated the [Private Google Calendars](https://wordpress.org/plugins/private-google-calendars/#description) plugin before setting up the plugin. After setup, the plugin can be activated once more.

**Comment by adamdunnage** [comment]
@adamsilverstein Just to confirm after you asked yesterday that this does happen when trying to connect any module in Site Kit after completing setup and re-activating the Private Google Calendar plugin . For example:

1. Disable the Private Google Calendar plugin and complete Site Kit setup.
2. Re-activate the Private Google Calendar plugin.
3. Attempted to connect another module within Site Kit such as Analytics.

**Comment by adamsilverstein** [comment]
👍🏼  I took a look at the plugin code and gave it a test.

this plugin implements a simple [google oAuth client](https://github.com/michielvaneerd/privategooglecalendars/blob/master/lib/google-client.php) - when users connect to a private calendar, the plugin guides them through connecting by creating a GCP app and uploading the secret via the UI:

![image](https://user-images.githubusercontent.com/2676022/159028851-3abe4244-791f-43f7-820c-82df7690b446.png)

Digging into the code I see they plugin had an overly aggressive redirect check that was catching our oauth return flow and interfering with it. It looks like we aren't the only conflicting plugin and the author has already implemented a fix in response to other support requests, see https://github.com/michielvaneerd/privategooglecalendars/commit/1739322a817d0390fddbaae8edcab925082caba2 and specifically this code change:
https://github.com/michielvaneerd/privategooglecalendars/commit/1739322a817d0390fddbaae8edcab925082caba2#diff-48fbe50b67ec6dfc16ec5f314e1832b9a5db7404249f58fad0ecbb2a0056130cR1121-R1125

Looks like a new release was just pushed to .org as well:

![image](https://user-images.githubusercontent.com/2676022/159030250-b15c19ef-5c14-48ed-bacb-923ed473b59c.png)

@adamdunnage can you give this another test, it should be resolved.

**Comment by adamdunnage** [comment]
@adamsilverstein Yes it looks like this update that has recently gone out fixes the issue. Thanks for checking and confirming.

**Comment by adamsilverstein** [comment]
Good to hear, thanks for confirming. Closing this as resolved.
