### ISSUE TITLE
UX/UI Enhancement on Overall page metrics over the last X days widget titles

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4946]
## Bug Description

When on the Entity dashboard there's a minor UX/UI enhancement I feel we should make on the `Overall page metrics over the last X days` widget.  The titles are left aligned, where as the `gathering data…` text is centered.  

The `Search traffic over the last X days` widget titles are centered so would make sense to make these titles to be too.

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/907e05c9-48b7-4d37-89a9-1b4de52f5fc5)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In any `DataBlock` that is left-aligned (e.g. the one big number in the All Traffic widget, or the numbers in the Overall Page Metrics widget), the potential "gathering data..." text that can appear there should also be left-aligned.
    * More generally speaking, "gathering data..." text in a `DataBlock` should always follow the overall alignment of that `DataBlock`, i.e. it should be the same as if numbers were displayed there.
    * For example, the "gathering data..." texts in `DataBlock`s in the Search traffic widget should still remain centered as all these are centered.

## Implementation Brief

* Within `_googlesitekit-gathering-data-notice.scss`:
    - Modify `&.googlesitekit-gathering-data-notice--has-style-default`:
        - Change value of `text-align` to 'inherit'.
    - Modify `&::after`:
        - Change value of `display` to 'inline-block'.
        - Remove the `margin` property. 

### Test Coverage

* 

## QA Brief

* Enforce the gatheringData state using the Tester Plugin.
  * Verify that the alignment of all content in Data blocks on an Entity Dashboard page within the 'Search traffic over the last 28 days' is centred. 
  * Verify that the alignment of all content in Data blocks on an Entity Dashboard page within the 'Overall page metrics over the last 28 days' is left aligned. 
* Verify that no other changes should have occurred to Data blocks, when they are showing statistics/zero data, regardless of the zeroDataStates feature being on or off. (Essentially Data blocks should work as they do now normally.)

## Changelog entry

* Ensure consistent alignment of content in data blocks.

**Comment by felixarntz** [comment]
Good catch @wpdarren!

**Comment by jimmymadon** [comment]
@felixarntz If we proceed with the AC, then we should consider aligning the bottom grey line to left too.
1. Grey Line Not Aligned:
<img width="1297" alt="Screenshot 2022-03-20 at 23 39 41" src="https://user-images.githubusercontent.com/1721319/159191128-6c3f6cc3-3326-44f3-ba96-14a7e26979f1.png">

2. Grey Line Aligned:
<img width="1301" alt="Screenshot 2022-03-20 at 23 39 23" src="https://user-images.githubusercontent.com/1721319/159191134-5c8c21f1-f110-433f-8c71-75584b48c6fc.png">

Option 2 above looks better but still a bit weird to me. I would be inclined to centre everything (even if that means we have to centre the stats). Especially since the second set of Data Blocks appear on the same page - they would look a bit more consistent.

3. Everything centred (when not gathering data):
![Screenshot 2022-03-20 at 23 53 01](https://user-images.githubusercontent.com/1721319/159191441-5b41c580-2086-4ffd-9345-8afb235b3777.png)

So should we proceed with option 2 or option 3 (or option 1!)?

**Comment by felixarntz** [comment]
@jimmymadon Great catch about the lines not being aligned!

Let's go with your option 2. for now. This keeps the current design, which I'd rather not change at this point. While I see some potential value in your option 3., there are some other caveats that would raise, for example the data block in the "All Traffic" widget would probably look weird if it was centered.

Let's align the lines similarly to the text and keep left vs center alignment overall as it currently is.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

With the gatheringData state using the Tester Plugin:

- The alignment in data blocks on an entity dashboard page within the 'Search traffic over the last X days is centred.
- The alignment in data blocks on an entity dashboard page within the 'Overall page metrics over the last X days is left.
- Verified that no other changes have occurred to Data blocks, when they are showing statistics/zero data.
- Checked mobile layout for data blocks on an entity dashboard page.
- Checked all data blocks on main and entity dashboard with gathering, zero and statistics. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/161263708-9d0e967a-fed9-4d19-a858-0c248511b242.png)
![image](https://user-images.githubusercontent.com/73545194/161263731-39637ae7-7fdf-4502-9c09-1c015b0354e3.png)
![image](https://user-images.githubusercontent.com/73545194/161263771-39fcaadb-6b07-4e81-924f-571c98625f0b.png)
![image](https://user-images.githubusercontent.com/73545194/161263787-ef777d76-a625-4fd9-90ca-d0affe1062b6.png)
![image](https://user-images.githubusercontent.com/73545194/161263800-ec555e80-1041-4616-a960-0e177b367c0b.png)
![image](https://user-images.githubusercontent.com/73545194/161263828-e55ef56f-f02a-4c64-aa93-8084db6ef4d1.png)

</details>
