### ISSUE TITLE
Finalize dashboard sharing documentation URL

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4949]
There's at least a few dashboard sharing-related "Learn more" links in the plugin, however during the development of these components we had not defined what the documentation on the website would actually look like yet. During #4812, it was specified to temporarily use https://sitekit.withgoogle.com/documentation/using-site-kit/dashboard-sharing/ as link URL for now, assuming that as a potential location for the content later.

Once we have defined where the documentation will live (likely some time closer to finishing the overall implementation), we have to make sure the URLs in the plugin are correct. cc @bethanylang 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All dashboard sharing-related "Learn more" links should point to the following URL: _https://sitekit.withgoogle.com/documentation/using-site-kit/dashboard-sharing/_

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
@aaemnnosttv is the AC here finalised now we have that URL? Can this move over to IB?

**Comment by techanvil** [comment]
I've tidied up the AC to remove the TBD aspect, so it should be ready to move to IB. Still needs @aaemnnosttv to give it the :+1: though.

**Comment by techanvil** [comment]
> @techanvil if this is the final URL we will use I'm not sure there is anything to do because this is what we have been using as a placeholder.

Hmm - I thought we may not have used a placeholder in some cases but might be wrong there...

**Comment by eclarke1** [comment]
@aaemnnosttv @techanvil presuming we can close this issue now we have confirmed the final URL that Bethany provided is in fact the same as our placeholder, so we're all good here?

**Comment by techanvil** [comment]
> @aaemnnosttv @techanvil presuming we can close this issue now we have confirmed the final URL that Bethany provided is in fact the same as our placeholder, so we're all good here?

@bethanylang did state it's the final URL in her comment above, so yes, let's go ahead and close this off.
