### ISSUE TITLE
2 WP plugins using Guzzle --> PHP Fatal error

### ISSUE THREAD

**Issue by Prospection** [google/site-kit-wp#496]
As appeared we have 2 plugins using Guzzle, and both have different vendor folder, and likely different versions.

So I started to get this error:
## Bug Description
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to GuzzleHttp\Client::send() must implement interface GuzzleHttp\Message\RequestInterface, instance of GuzzleHttp\Psr7\Request given, called in /www/htdocs/***/wp-content/plugins/other_plugin/vendor/affilinet/productdata-php-sdk/src/Affilinet/ProductData/HttpClient/GuzzleClient.php on line 49 and defined in /www/htdocs/***/wp-content/plugins/google-site-kit/vendor/guzzlehttp/guzzle/src/Client.php:158

## Additional Context
WP: 5.2.2
Google Sitekit: Version 1.0.0-beta.1.0.4
**Both Guzzles versions I'll try to get asap**
PHP Version 7.1.30-nmm1
Linux dd39706 4.4.0-161-generic #189-Ubuntu SMP

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Hi there,

Thanks for posting this.

It looks like we're tracking this issue already in #223 (Guzzle specific) and #246 (similar conflict with other library). Please follow these two issues for progress on this matter.
