### ISSUE TITLE
UX/UI issue on All Traffic pie chart tabs when in gathering state

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4961]
## Bug Description

On a site that is in gathering state. I noticed a UX/UI issue on the `All traffic widget` on main and entity dashboard.  At the top of the pie chart, tabs appear active and when the user clicks on them, nothing happens. It would be better if we can make these tabs look disabled in this state. 

https://user-images.githubusercontent.com/73545194/159525757-0a793a50-54e6-48da-9290-05b6ec29cea1.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When in "gathering data" state, the tabs in the "All Traffic" widget should appear disabled.
* The cursor should also change to the disabled cursor when hovering over them.

## Implementation Brief
* Using `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/DimensionTabs.js`,
	* Check if there is zero data by querying the analytics data store via the `hasZeroData` selector.
	* Update the `Tab` and `Select` components to be `disabled` by adding whether `hasZeroData` is `true` or `gatheringData` [existing] is `true`.
* Using `assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss`,
	* Add the following styles for:
		* `.mdc-tab[disabled]`:
			* `cursor: default;`
		* `.mdc-tab[disabled] .mdc-tab__ripple`:
			* `display: none; `
		* `.mdc-tab[disabled] .mdc-tab__text-label`:
			* `opacity: 0.6; `
			* `color: $c-jumbo; `
		* `.mdc-tab--active[disabled] .mdc-tab-indicator__content--underline`
			* `background-color: $c-jumbo; `
			* `opacity: 0.6; `

### Test Coverage
* No new tests to be added.

## QA Brief

* Visit the Site Kit dashboard with Analytics connected in a gathering data state.
* Try to interact with the tabs here:
![CleanShot 2022-03-29 at 21 55 05](https://user-images.githubusercontent.com/90871/160705557-8e5c7677-9d40-4f18-91db-6aef172d1c54.png)
* They should not be accessible by either keyboard navigation nor mouse input; they should not respond to focus/hover states and essentially be totally disabled.

Also try the above steps, with the `zeroDataStates` enabled and a site with "zero data" for Analytics. The same outcome should be observed, eg. tabs that are entirely disabled.

Also test both states on mobile and ensure the dropdown is disabled, eg:

![CleanShot 2022-03-29 at 23 54 34](https://user-images.githubusercontent.com/90871/160719823-3332c6b2-936e-4676-b810-1db4d88a3262.gif)

The story at https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-components-dashboard-all-traffic-widget--zero-data-zerodatastates-enabled should also have disabled tabs instead of tabs that can be interacted with, as this issue also disables the tabs when in a zero data state.

## Changelog entry

* Disable All Traffic pie chart tabs when in gathering or zero data state.

**Comment by asvinb** [comment]
@felixarntz @marrrmarrr As per the [Material designs specs](https://material.io/design/interaction/states.html#disabled), we should not disable the tabs if unavailable.
> Disabled states cannot be inherited by: floating action buttons (FABs), bottom and side sheets, dialogs, menus, tooltips, and alerts, or navigational components (such as app bars, tabs, bottom navigation and steppers). If the action represented in the FAB is unavailable, the FAB should not appear in the composition.

In this case, maybe it'll be best to remove the tabs altogether when it's in the gathering data state. Let me know what you think.

**Comment by felixarntz** [comment]
@asvinb Hmm that's a good point. At the same time, we try to mimic the full UI as well as possible throughout, and by removing the tabs people on e.g. a new site wouldn't know what the three metrics are represented there, and also they wouldn't even know what the visible piechart would eventually be for. So from that perspective I'd be against removing the tabs entirely.

cc @samitron7

**Comment by tofumatt** [comment]
I think disabling them here is the best compromise, but we do need to make sure they're also not interact-able at all, including for keyboard users. So I think the IB is missing removing them from the tab order because they should have no interaction when activated. This probably means ensuring clicking on them doesn't trigger the tab order changing—is this already the case?

The tabs currently move when there is zero data:

![CleanShot 2022-03-28 at 15 59 15](https://user-images.githubusercontent.com/90871/160427161-6b07bab1-b805-4596-b978-0f50aadce349.gif)

But we should ensure (with a `tabIndex="-1"` and `onClick={undefined}` that nothing happens when users click/activate these, even when they _appear_ disabled.

**Comment by asvinb** [comment]
@tofumatt I checked and when the tabs are disabled, they are not tabb-able. I've updated the IB, can you review?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

With Analytics connected in a gathering data state:

- The tabs are deactivated above the pie chart. Checked on main and entity dashboard
- The tabs are deactivated above the pie chart. Checked on mobile and smaller screen sizes.

With Analytics connected in a gathering data state:

- The tabs are deactivated above the pie chart. Checked on main and entity dashboard
- The tabs are deactivated above the pie chart. Checked on mobile and smaller screen sizes.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/161990666-7a020e0c-9b4a-4e80-8935-772a36b06f24.png)
![image](https://user-images.githubusercontent.com/73545194/161990687-3e2bc37d-cd06-42f2-b7a8-1a77ef439e33.png)
![image](https://user-images.githubusercontent.com/73545194/161990713-a1985996-6b6a-48ed-934c-dc203b928190.png)

- Checked the Storybook link to make sure it worked and displayed correctly.

</details>
