### ISSUE TITLE
Provide support for non standard WordPress versions

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4963]
## Bug Description

As raised by [one user in the support forums](https://wordpress.org/support/topic/undefined-offset-1-12/#post-15463961) PHP warnings can be found if using a non standard WordPress version number (ie. An integer, version 42),

In the users case their WordPress version was changed to 42 after applying an option within their Digital Ocean droplet, with other hosting providers also offering similar features. 

The errors appear as below. They don't impact Site Kit operations or functionality:

```
wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php:348
Google\S\C\A\Assets->Google\S\C\A\{closure}()
Unknown location
Google\S\C\A\Script_Data->Google\S\C\A\{closure}()
Unknown location
Google\S\C\A\Asset->before_print()
wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php:903
Google\S\C\A\Assets->run_before_print_callbacks()
wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php:912
Google\S\C\A\Assets->run_before_print_callbacks()
wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php:159
Google\S\C\A\Assets->Google\S\C\A\{closure}()
wp-includes/class-wp-hook.php:307
do_action('admin_print_scripts')
wp-admin/admin-header.php:146
```

## Steps to reproduce

1. Hide your WP version using a security plugin, custom function or hosting control panel
2. Setup Site Kit
3. Enable error reporting
4. Check your error logs

## Additional Context

 - Site Kit 1.70.0
 - [Support topic](https://wordpress.org/support/topic/undefined-offset-1-12/#post-15461332)
[SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjSYR-QSJhMyd7RoLVM-BJu9CSqibVjnclTmhKr2CIACYepxMw8N94v3UtmZugJYmU) - No obvious cause

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should not assume that the WordPress version has a major and minor segment. While this is commonly the case, version numbers like `5` are still valid version numbers. While this isn't used by WordPress itself, there are some obscure plugins that change the WordPress version "for security reasons" to one without any `.` in it, which is currently causing a PHP notice.
* Specifically, the `Authentication::inline_js_base_data()` method should be adjusted to account for this. If no `.` is present, it should simply assume `0` for the minor version instead of splitting the version string into major and minor bit.

## Implementation Brief

* Update the version which is split by periods in `Authentication::inline_js_base_data` to be unconditionally concatenated with a trailing `.0` so that there are always at least two segments (assuming a non-empty version number)
	* This way, the `$major` and `$minor` versions remain accurate and `0` is used as a fallback in the case that the input `$version` is a single number/integer while preserving the real `$version` in the base data 

### Test Coverage

* Add a test to `AuthenticationTest` to cover a standard case as well as a non-standard WP version by filtering `bloginfo`

## QA Brief

* Follow steps to reproduce and hide the WP version (a plugin like [Sucuri](https://wordpress.org/plugins/sucuri-scanner/) can be used).
* See that there's no longer an error.

## Changelog entry

* Fix authentication issue with WordPress security plugins/other plugins that modify/obscure the WordPress version number.

**Comment by jamesozzie** [comment]
@felixarntz Let me know if you want me to run some checks using the various methods of hiding a WordPress version. No dashboard or setup errors were reported, only errors on the debug log.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@kuasha420 @wpdarren 

- I verified this issue using the test steps on both instawp and tastewp for PHP version 7.4 , 8.0 and 8.1 and SK versions 1.70.0 and 1.72.0.
- Also, verified fix on 'develop' branch.
- For hiding WP version I used [Sucuri](https://wordpress.org/plugins/sucuri-scanner/) Plugin.
- I'm not getting any error reported by user under WP debug log. 

@wpdarren can you please verify if you are able to reproduce this issue ?

**Comment by wpdarren** [comment]
@mohitwp No, I can’t recreate the initial issue either with Securi - my advice would be to chat with @jamesozzie  who initially created the ticket, and see if it looks to be fixed for him. As a double check.

**Comment by jamesozzie** [comment]
I'll perform a check on this later today and let you know. There are a few ways to hide WP version numbers. Thanks @mohitwp and @wpdarren.

**Comment by wpdarren** [comment]
@jamesozzie @mohitwp just jumping in here. I am conscious that we need to get this ticket into approved by EOD for the release. If we are unable to test this on our environments, then yes, we need to come up with a solution to get this tested. 

From reading the initial ticket I thought it was an issue with when the version is hidden with a plugin like Securi, but it appears to be more complicated than that and only affecting one user?  Is there anyway we can get access to a test site or staging site where this can be tested for this one user?

**Comment by jamesozzie** [comment]
@wpdarren I have a site already setup with DigitalOcean and SpinUpWP however there is no setting (internal testing) to hide the WP version that I can see. The impacted user is using DigitalOcean, I suspect with another service. I've reached out to ask them for further details. Until then I don't have any site where we can reproduce this. 

Correct also that this isn't just a case of a hidden WP version, it's a version without decimals. So far from the third party plugins I've checked I haven't been able to re-create.

**Comment by mohitwp** [comment]
### QA Update ✅ 



- Tested by using [override-wp-version.0.1.zip](https://github.com/google/site-kit-wp/files/8556693/override-wp-version.0.1.zip) to change WP version to integer. 

- This plugin is creating PHP warning related to Authentication.PHP under debug log same as raised by [one user in the support forums](https://wordpress.org/support/topic/undefined-offset-1-12/#post-15463961) 

` PHP Warning:  Undefined array key 1 in /s4-ruintexture/wordpress/wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php on line 845`

- No console errors.
- Verified for new set up.
- Verified for existing set up.
- Switching to 1.73.0 version remove this PHP warning.
- Site Kit operations and other functionalities working fine.

cc @wpdarren @aaemnnosttv 

![image](https://user-images.githubusercontent.com/94359491/165222826-e8000376-519a-4e45-9e1c-71c384d72617.png)
