### ISSUE TITLE
While analytics in 'gathering data' state, then clicking on 'Total clicks', 'Total impressions' or 'Unique visitors from search' throws error.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#4967]
## Bug Description

While Analytics in gathering state, then clicking on Total clicks', 'Total impressions' or 'Unique visitors from search' throws error.
Suggestion: We can disable click on cards while analytics is in gathering data state.

```
Cannot read properties of null (reading '__eventTarget')

    in GoogleChart
    in div
    in Cell
    in div
    in Row
    in div
    in ForwardRef
    in AnalyticsStats
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in SearchFunnelWidget
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in ForwardRef
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardEntityApp
    in GoogleSitekitDashboardDetails
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

## Steps to reproduce

1. Create a new site which will have default gathering state.
2. Activate the "zeroDataStates" feature flag
3. Go to Site Kit Dashboard.
4. Set up Analytics.
5. Clicks on 'Total clicks', 'Total impressions' or 'Unique visitors from search'.
6.  See Error.

## Screenshots/Screencast

https://user-images.githubusercontent.com/94359491/159649263-5225b656-35ea-4060-a8c9-804c3a989b6b.mp4

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Metrics in the Search traffic widget that say "gathering data" should not be selectable.
    * The `DataBlock` component should not call a callback passed via the `handleStatSelection` property on clicks or keys presses when in the data block is in the gathering data mode.
* The cursor should show as disabled when hovering over such metrics.

## Implementation Brief
* Using `assets/js/components/DataBlock.js`,
	* Set the `onClick` and `onKeyPress` props to `undefined` if `gatheringData` is `true` to the `googlesitekit-data-block` element. Else keep the same values, i.e `handleStatSelection && this.handleClick` and `handleStatSelection && this.handleKeyPress`.
	* Add `aria-disabled` to the `googlesitekit-data-block` element if `gatheringData` is `true`.
	* Ensure the tabindex is set to `-1` if `gatheringData` is `true`.
* Using `assets/sass/components/global/_googlesitekit-data-block.scss`,
	* Add `.googlesitekit-data-block--is-gathering-data` and set `cursor: auto`.
	* Update the selector where the hover, focus and active styles are set to the `googlesitekit-data-block--button-*` class names by excluding blocks having the `googlesitekit-data-block--is-gathering-data` class.
		```
		&--button-#{$button}:not(.googlesitekit-data-block--is-gathering-data) {
		```

### Test Coverage
* No new tests to be added.

## QA Brief
1. Create a new site which will have default gathering state.
2. Activate the "zeroDataStates" feature flag
3. Go to Site Kit Dashboard.
4. Set up Analytics.
5. 'Total Impression', 'Total clicks', 'Total impressions' or 'Unique visitors from search' from the SearchFunnel widget should not be clickable, hovered or tabbable.

## Changelog entry

* Prevent selection of metrics in the Search Traffic widget when gathering data.

**Comment by mohitwp** [comment]
I'm not able to reproduce this issue on new site. So closing this issue.

**Comment by adamdunnage** [comment]
@mohitwp I have come across this issue while testing Zero Data States this morning and can consistently recreate it on new sites. 

See below my experience:

https://user-images.githubusercontent.com/91896826/160787711-771f365e-9101-4c5b-93f8-4c254fd1b399.mp4

Are you still unable to recreate this? To recreate I create a fresh new WP site, and install Site Kit. I use the tester plugin to trigger Unified Dashboard and Zero Data States flags and do as you can see on the recording above.

**Comment by mohitwp** [comment]
@adamdunnage 


Yes, I'm also able to reproduce this issue on a new site in both which is in default gathering data state. (Not able to reproduce this issue on old sites)

https://user-images.githubusercontent.com/94359491/160795260-3a0fa80f-2c9b-45ae-bb39-a913ebd77b45.mp4

Reopening this issue again.

cc  @wpdarren

**Comment by tofumatt** [comment]
In a gathering data state, these probably shouldn't be clickable at all; eg. they should be disabled, similar to the `DimensionTabs`, see #4961.

**Comment by tofumatt** [comment]
Thanks @asvinb, looks good to me 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
@techanvil @mohitwp I am running through the QA on #5010 and noticed that the first data block has the thick border at the top as if it is active. Should we follow the same as the disabled pie chart tabs and have it a grey colour. I realise it's not in the IB/AC but thought I would mention it. 

![image](https://user-images.githubusercontent.com/73545194/162014713-2a0514b9-357c-466f-8a1b-d32faad16c56.png)

**Comment by techanvil** [comment]
Hi @wpdarren, I think you raise a good point, but I would suggest creating a new issue for this. The original bug report for this was clearly quite critical with an error being displayed on the page, hence the P0.

The question about whether to make the bar here grey is not as critical - and although I suspect we should, given it wasn't captured in the AC/IB I think it would be OK to go through the usual process, I don't think it needs to be rushed into the current release.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil Although, it is not mentioned in AC/IB but just wanted to confirm that we have disabled clicks for gathering data state but when site is in 'Zero' data state then clicks are enable for 'Total clicks', 'Total impressions' or 'Unique visitors from search' tabs although it doesn't throw error.

So, we will keep clicks enable when site is in zero data state ?

**Comment by techanvil** [comment]
> ### QA Update 
> @techanvil Although, it is not mentioned in AC/IB but just wanted to confirm that we have disabled clicks for gathering data state but when site is in 'Zero' data state then clicks are enable for 'Total clicks', 'Total impressions' or 'Unique visitors from search' tabs although it doesn't throw error.
> 
> So, we will keep clicks enable when site is in zero data state ?

Hi @mohitwp, you've raised an interesting question here.

Personally, I think it's OK for these controls to be clickable when in zero data state, when considering the widget in isolation. However, the controls on the All Traffic pie chart _are_ disabled when in zero data state, so maybe it would be appropriate to do the same here too.

Again, I'd suggest raising a separate issue so we can figure out the right approach here.

**Comment by mohitwp** [comment]
Created separate tickets for https://github.com/google/site-kit-wp/issues/4967#issuecomment-1091420787 and https://github.com/google/site-kit-wp/issues/4967#issuecomment-1090424456

https://github.com/google/site-kit-wp/issues/5056
https://github.com/google/site-kit-wp/issues/5057
