### ISSUE TITLE
Minor styling issue on all table notices on main and entity dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4981]
## Bug Description

Styling issue on main and entity dashboard on all the table notices in zero and gathering state.  When you hover over the text, the background colour changes, but I feel the text needs padding to the left side.  

<details>
 <summary>Screenshots</summary>

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/8f0b5547-779c-440f-92c6-c831ffa404f0)

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/abb49f97-518a-4026-b512-415f8a2a5486)

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `ReportTable` should be updated so that the background hover style for table body rows is disabled for zero and gathering data states

## Implementation Brief
* Using `assets/js/components/ReportTable.js`,
	* add the `googlesitekit-table__body-row-no-data` class name to cells having `googlesitekit-table__body-item-wrap` as class name.
	* remove `googlesitekit-table__body-item-wrap` class name.
* Using `assets/sass/components/global/_googlesitekit-table.scss`, remove the styles for `googlesitekit-table__body-item-wrap` and add styles for 
	* `.googlesitekit-table__body-row.googlesitekit-table__body-row-no-data`.
		* It should have `background-color: transparent;` for the `hover` state.
	* `.googlesitekit-table__body-row.googlesitekit-table__body-row-no-data td`.
		* `white-space: normal;`

### Test Coverage
* N/A

## QA Brief

* QAing this would require making sure hovering over the table notices in no data or gathering state doesn't show a background colour change. The screenshots in the description above can be used as a reference.

## Changelog entry

* Fix styles issue for report tables when they are in the gathering state.

**Comment by aaemnnosttv** [comment]
I agree that it's a bit odd but only on hover, otherwise it looks normal. If padding was added to the left, you would then see the inverse of this where the text looks misaligned when the table is not hovered which one might argue looks just as bad or worse.

Instead, I think the better enhancement to make here is to disable the hover style in the gathering data state, as this is really only intended to highlight a row among many. In the gathering state there is only one so it's irrelevant, and a bit odd that there would be a hover state for such a placeholder row.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When trying to hover over the table notices in no data or gathering state the background colour no longer changes. 
- Tested this on main and entity dashboard and also on WP Dashboard on the Site Kit widget. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/170282512-31e40c56-48f5-409d-8abb-610b3a076df0.png)
![image](https://user-images.githubusercontent.com/73545194/170282484-f9a16b11-ee01-48b2-9443-9dfb2918fc76.png)
![image](https://user-images.githubusercontent.com/73545194/170282527-2aa5e4b9-7abe-444a-8b87-92159272201a.png)
![image](https://user-images.githubusercontent.com/73545194/170282545-e01a0632-c654-40ad-9a83-8f48613332bf.png)
![image](https://user-images.githubusercontent.com/73545194/170282557-d2922257-b5d4-444e-b760-acb777ed8fdb.png)

</details>
