### ISSUE TITLE
UI/UX Issue on mobile with the longer zero state messages

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4982]
## Bug Description

UI/UX Issue on mobile with the longer zero state messages overlapping the table. Scrollbar appears underneath the text. This is an issue on main and entity dashboard tables. 

![image](https://user-images.githubusercontent.com/73545194/160404673-78810c8d-1200-4a44-99f8-cc840aa08c73.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any "gathering data" or `ZeroDataMessage` text within a `ReportTable` should be styled to wrap into multiple lines if needed. Such a message must not get cut off on narrower viewports.
    * The styling should be specific to those scenarios, regularly populated `ReportTable`s should still behave as before (no line wrapping).

## Implementation Brief
* Using `assets/sass/components/global/_googlesitekit-table.scss`,
	* Add new class name `googlesitekit-table__body-item-wrap` with the following styles:
		* `white-space: normal`
* Using `assets/js/components/ReportTable.js`,
	* Add the `googlesitekit-table__body-item-wrap` class name to the table cell when we are displaying `GatheringDataNotice` and `ZeroState`.

### Test Coverage
* No new tests to be added.

## QA Brief
* Ensure gathering data and zero state messages wrap and are not cutoff within the ReportTable component.
* The scrollbar will remain though, because of the table headers which are not responsive.

## Changelog entry

* Fix styling issues with table view on mobile when no results are available.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified** 

- Verified for both 'gathering' and 'zero' data state.
- Verified on ios and android device.
- Verified on safari and chrome browser.
- Verified for WP Dashboard, Main and entity dashboard.
- Verified gathering data and zero state messages wrap and are not cutoff within the ReportTable component.

<details>

![image](https://user-images.githubusercontent.com/94359491/161464708-8c0fecd0-8911-4f82-b6f9-77639c7c8342.png)

![image](https://user-images.githubusercontent.com/94359491/161464723-6a7b7cf3-0382-4faf-a914-6c0eea8acce1.png)

![image](https://user-images.githubusercontent.com/94359491/161464738-4e79b008-f5c9-46d8-ba44-74ca7aa9c1e1.png)

</details>
