### ISSUE TITLE
The 'Not enough traffic yet to display stats' notification not appearing on Entity Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4983]
## Bug Description

The `Not enough traffic yet to display stats` desktop notification only appears on the main dashboard.  When visiting the entity dashboard for a specific page, the notification does not appear when in zero data state.  I believe that it should. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/c9bfd84c-d4bc-4aa4-ac2a-2c1d60c92bdc)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Zero data state notifications should appear on the entity dashboard, as well as on the main dashboard

## Implementation Brief

* Create a new `EntityBannerNotifications` component as an entity dashboard-specific variant of the current `BannerNotifications` component
    - For now this would only include `ZeroDataStateNotifications` in the same way as it is in `BannerNotifications`
* Update `DashboardEntityApp` to render the new `EntityBannerNotifications` component in the `subHeader` prop of the `Header` component, similar to `DashboardMainApp`

### Test Coverage

* No changes needed

## QA Brief

- Ensure `zeroDataStates` feature flag is enabled.
- Using the tester plugin, enable the `zero` data state for Analytics and Search Console.
- Clear the session and reload the page.
- Ensure the Zero data state notification appears.
- Type `Sample Page` in the entity search input.
- Click the search results and go to the entity dashboard.
- Ensure the Zero data state notification appears as it appears in the main dashboard.

![zero-state-entity-dashboard](https://user-images.githubusercontent.com/24408261/161748457-a5da603f-23c7-4165-94e9-f21175b55213.gif)

## Changelog entry

* Add "gathering data" and "zero data" headers to single URL ("entity") dashboard pages.

**Comment by tofumatt** [comment]
Here's a screencast of where we would expect this, just for context:

![CleanShot 2022-03-30 at 13 19 02](https://user-images.githubusercontent.com/90871/160832962-ebada90f-479d-41fd-a8c8-b82928497631.gif)

**Comment by tofumatt** [comment]
Works for me! IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Using the tester plugin, with zero data state for Analytics and Search Console:

- The Zero data state notification appears on the main and entity dashboard.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/162417372-19dbdd07-b063-41ac-be19-7bb6257dbfe0.png)
![image](https://user-images.githubusercontent.com/73545194/162417380-1caa5589-f228-476e-88ce-fe1102d2fa56.png)

</details>
 

**QA note:**  When you have search console in gathering and analytics in zero (and vice versa) the notification doesn't appear on main or entity dashboard. This was discovered while QA-ing [5008](https://github.com/google/site-kit-wp/issues/5008) and is currently being fixed.  

Will retest this when that ticket is back in QA.
