### ISSUE TITLE
Blue Box CTA when AdSense and Analytics are not linked

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4985]
## Bug Description

When you have not linked your AdSense account with Analytics the old style blue box CTA appears on the main dashboard. 

Since we have refreshed the CTAs it would be a good idea to also update this. 

Unsure if we want to keep this as part of Zero Data states but assigned it just in case. 

![image](https://user-images.githubusercontent.com/73545194/160410363-c6e60267-4126-4b68-a9ab-8017a94a0bc3.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
@marrrmarrr further to the comment from @felixarntz on the [issue in the Bug Bash board](https://app.asana.com/0/1201999381911618/1202034323668430), could we kindly ask you to review this and advise whether we need UX input (probably!)

**Comment by aaemnnosttv** [comment]
This no longer seems to be an issue in GM2+

![image](https://user-images.githubusercontent.com/1621608/208135117-a3e21138-0dae-45d7-859f-f08936a5a1e9.png)

https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module-components-dashboard-top-earning-pages-widget--ad-sense-not-linked
