### ISSUE TITLE
Blue Box CTA appears on WP Admin Bar

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4986]
## Bug Description

This occurs with or without forcing the data in the tester plugin.

Analytics is set to `zero data` and Search console is set to `gathering data`.

The WP Dashboard Site Kit widget displays the old blue box CTA for Analytics, and it says "Analytics Gathering Data"

You can see from the dashboard that it is displaying zero data
![image](https://user-images.githubusercontent.com/73545194/160416694-b484ecc4-6848-400a-897e-d94d635ece67.png)

The tester plugin that it is set to zero
![image](https://user-images.githubusercontent.com/73545194/160416784-4ca67cf0-0d7d-437a-a124-0ac6fe11e3a6.png)

The same issue appears with the Admin Bar
![image](https://user-images.githubusercontent.com/73545194/160416977-fad9801d-ac7c-4d70-a7ee-5357d573a416.png)

**Note: the same applies if you have Analytics is set to `gathering data` and Search console is set to `zero data` but this time the search console says gathering when it's set to zero data**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the `zeroDataStates` flag is enabled, the WP admin bar menu components must never return `WidgetReportZero`. Instead, any widgets with a "zero report" should behave as follows:
    * If the respective service is gathering data, the widget should show "gathering data" instead of the big number, similar to how it is on the SK dashboard or WP dashboard widget already. It looks like this is already the case, but please verify.
    * If the respective service is not gathering data, the widget should just show the 0 values, similar to how it is on the SK dashboard or WP dashboard widget already.

For a possible fix, see the closely related #4989 which fixed the same problem for the WP dashboard widget.

## Implementation Brief

- In the below list of components, modify the condition to display the `<WidgetReportZero />` component to be:
    ```javascript
        if (
    	  ! zeroDataStatesEnabled &&
    	  isGatheringData &&
    	  isZeroReport( *Data )
        ) {
    ```
    where * is either searchConsole or analytics depending on the relevant component.
- Make the above change in the following components:
    - `/assets/js/components/adminbar/AdminBarClicks.js`
    - `/assets/js/components/adminbar/AdminBarImpressions.js`
    - `/assets/js/components/adminbar/AdminBarSessions.js`
    - `/assets/js/components/adminbar/AdminBarUniqueVisitors.js`

### Test Coverage

* No new tests needed.

## QA Brief
* With the tester plugin, set Analytics to `zero data` and Search console to `gathering data`.
* Enable the `zeroDataStates` feature flag.
* Check that the blue box CTA is not displayed on the front end in the admin bar.

## Changelog entry

* Don't show the "gathering data" blue box CTA on the Admin Bar.

**Comment by tofumatt** [comment]
This follows the other fixes, so looks good to me ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified** 

- Verified when search console is in gathering and analytics is in zero state.
- Verified when search console is in Zero and analytics is in gathering state.
- Now admin bar in front end not showing Blue box CTA.

<details>

![image](https://user-images.githubusercontent.com/94359491/161484720-6a923934-ec5e-4bdb-8eb3-53a899ad5c22.png)

![image](https://user-images.githubusercontent.com/94359491/161484736-9b2879d3-8f39-46cc-b833-8080ffc065f9.png)

</details>
