### ISSUE TITLE
Blue Box CTA appears when in Zero Data State on WP dashboard Site Kit widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4987]
## Bug Description

This occurs with or without forcing the data in the tester plugin.

Analytics is set to `zero data` and Search console is set to `zero data`.

The WP Dashboard Site Kit widget displays the old blue box CTA for Search console and Analytics and it says "Gathering Data" I think this could be linked to #4986 

The main and entity dashboard look as expected.

The Site Kit Admin bar says "No data available yet" 

I am assuming zero values should appear in the Site Kit widget on WP Dashboard and on the Admin Bar?

![image](https://user-images.githubusercontent.com/73545194/160421590-5870c7c0-bb39-47c3-8a63-22a51315b971.png)

![image](https://user-images.githubusercontent.com/73545194/160421617-0865d41c-6c25-4f05-bf3a-61ab4aeeda91.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@wpdarren This was already fixed yesterday via #4989, you probably ran into this before. I just verified this is no longer happening. The related #4986 is still valid though, it hasn't been fixed there yet.
