### ISSUE TITLE
Post Search returns wrong URL for found post if reference URL is filtered

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#499]
## Bug Description

If an alternate reference URL is used in place of the home URL, when loading the dashboard details using the post search feature from the Site Kit dashboard, the page link that stats are fetched for does not use the reference URL. As a result, the dashboard details view will attempt to show data/stats for the local version of the URL, not the reference URL.

This is inconsistent with the current behavior of the post search feature which also allows for searching by URL, including using a reference-based URL.

## Steps to reproduce

1. Set up Site Kit using an alternate reference URL
1. Connect a service that provides data on the dashboard-details view (e.g. Analytics)
1. From Site Kit dashboard, search for a post (using any supported method) and click View Data to navigate to the details view for that page
1. All widgets will be in a no-data state instead of showing available stats for the reference URL

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/64320927-315b8100-cfc8-11e9-8950-879c2473dad1.png)

Current display on dashboard details for a post/URL that has data

![image](https://user-images.githubusercontent.com/1621608/64321560-703e0680-cfc9-11e9-9f85-90d5888ebcb6.png)

## Additional Context

The problem is that the post's permalink is not search/replaced before returning.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When filtering in a different site URL (e.g. in local development):
    * When searching posts on the Dashboard, the found posts should link to the `dashboard-details` screen of the _actual_ live post URL (if available), not the local URL.

## Implementation Brief

```diff
diff --git a/includes/Core/REST_API/REST_Routes.php b/includes/Core/REST_API/REST_Routes.php
index 6eb99eb..f81c691 100644
--- a/includes/Core/REST_API/REST_Routes.php
+++ b/includes/Core/REST_API/REST_Routes.php
@@ -614,7 +614,11 @@ final class REST_Routes {
                            }
 
                            foreach ( $posts as $post ) {
-                               $post->permalink = get_permalink( $post->ID );
+                               $post->permalink = $this->context->get_reference_permalink( $post->ID );
                            }
 
                            return new WP_REST_Response( $posts );
```

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv Did you check whether the data shows correctly on the `dashboard-details` screen when using a live URL (which thus is not part of the actual site you're on)? We'd wanna make sure it doesn't use any internal data (like post ID) for that screen anywhere.

Regarding the implementation brief, we could probably simplify the code just calling `$post->permalink = $this->context->get_reference_permalink( $post->ID )`.

**Comment by aaemnnosttv** [comment]
> Did you check whether the data shows correctly on the dashboard-details screen when using a live URL (which thus is not part of the actual site you're on)? We'd wanna make sure it doesn't use any internal data (like post ID) for that screen anywhere.

I believe I did but I can check again. I'm not exactly sure what you mean about the internal data though.

> Regarding the implementation brief, we could probably simplify the code just calling `$post->permalink = $this->context->get_reference_permalink( $post->ID )`

Good call! I'll update it.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> I believe I did but I can check again. I'm not exactly sure what you mean about the internal data though.

I was referring to the post ID for a certain URL potentially being different between live site and local site.

IB ✅

**Comment by adamsilverstein** [comment]
This worked well in my testing, moving to Acceptance.

### Testing procedure

* Set up Site Kit locally, mapped to a live site (`elasticpress.io` in my testing) using the `googlesitekit_site_url` filter.
* Create a page on the local site with a slug matching a live URL on the mapped domain that contains data (eg. local `/blog` to get data for `elasticpress.io/blog`).
* Used the search feature to find this page, clicking thru to detail page.
* Verified data loaded correctly on the detail page.
