### ISSUE TITLE
Add missing Storybook coverage for zero data states in WP dashboard widget and admin bar

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4990]
It looks like the components for the WP dashboard widget and WP admin bar menu are missing their "zero data" representation/coverage in Storybook. There are also a few other minor issues with the Storybook coverage that should be addressed here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All Storybook stories within `AdminBarApp` and `WPDashboardApp` that currently have "Ready", "Data Unavailable", and "Gathering data" scenarios should receive an additional "Zero data" scenario.
    * The new scenario should show the UI in "zero data" state, i.e. when the report is a zero report but the service **is not** gathering data (i.e. typically showing 0s, or in case of tables the note on not having enough visitors).
    * The new scenario should be with the `zeroDataStates` feature flag enabled.
* In all the above components, the respective "Data Unavailable" story should be renamed to "Gathering data (legacy)". This UI will be phased out as it is pre-`zeroDataStates`.
* The `WPDashboardApp > WPDashboardWidgets > Ready` story should be fixed to also include the relevant Analytics parts of the widget (with regular data). Right now it is in an incomplete/impossible state where only Search Console data is present but no Analytics CTA.
* Additional stories for other scenarios of `WPDashboardApp > WPDashboardWidgets` should be added to represent the whole widget in the "zero" and "gathering" states:
    * "Zero data": Should show the entire set of widgets, with Analytics active, when both Search Console and Analytics reports have zero data (but **are not** gathering data) - with `zeroDataStates` feature enabled.
    * "Gathering data": Should show the entire set of widgets, with Analytics active, when both Search Console and Analytics are gathering data - with `zeroDataStates` feature enabled.

## Implementation Brief
* Update all `*.stories.js` files within `assets/js/components/adminbar` and `assets/js/components/wp-dashboard` to include the "Zero Data" scenario, i.e the report data is `0` and the module is not gathering data.
	* Label for the new story should be `Zero Data`.
	* The `zeroDataStates` must be enabled for those stories. This is done by passing the `features` array containing `zeroDataStates` to the `parameters` property of the story.
	* Rename stories having `Data Unavailable` story name to `Gathering data (legacy)`.
* Using `assets/js/components/wp-dashboard/WPDashboardWidgets.stories.js`,
	* Update the `Ready` story to include Analytics data.
	* Add the `Zero data` story where both, Analytics and Search Console widgets are active but have no data, with `zeroDataStates` feature enabled.
	* Add the `Gathering data` story where both, Analytics and Search Console widgets are active but are gathering data, with `zeroDataStates` feature enabled.

### Test Coverage
* No new tests to be added

## QA Brief

* Verify existing and new stories under Views/AdminBarApp and Views/WPDashboardApp. 
* Some of the already existing stories for WPDashboard do not exactly match the way the components are rendered in the production plugin. So as long as these render without any changes, then they could be accepted for now.

## Changelog entry

* N/A

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified** 


- All Storybook stories within `AdminBarApp` and` WPDashboardApp` that currently have "Ready", "Data Unavailable", and "Gathering data" now have additional "Zero data" scenario.
- The new scenario  shows the UI in "zero data" state, i.e. when the report is a zero report but the service is not gathering data (i.e. typically showing 0s, or in case of tables the note on not having enough visitors).
- Additional stories for other scenarios of `WPDashboardApp > WPDashboardWidgets` are added to represent the whole widget in the "zero" and "gathering" states:
- Verified when both SC and Analytics is in gathering state.
- Verified when SC and Analytics  is in zero data state.
- Verified when SC is in gathering state and Analytics is not set up.
- Verified when SC is in zero state and Analytics is not set up.

<details>

Story book images

![image](https://user-images.githubusercontent.com/94359491/164448894-527b7f86-09b3-4683-b7bc-45b6351a4391.png)

![image](https://user-images.githubusercontent.com/94359491/164448991-52413e4d-2c86-406d-881a-ff58a859528b.png)

Dashboard images-

![image](https://user-images.githubusercontent.com/94359491/164448141-0a9ad653-894d-45a4-bb8b-74e41a9f9c6b.png)

![image](https://user-images.githubusercontent.com/94359491/164448167-42bffb2f-d730-4d52-9a8e-e080337f4af5.png)

![image](https://user-images.githubusercontent.com/94359491/164448195-2d13c15d-670c-479a-bf59-8e5d0e02687d.png)

![image](https://user-images.githubusercontent.com/94359491/164448237-72b5c6cb-9f33-4737-9fb0-926bb93e86d9.png)

![image](https://user-images.githubusercontent.com/94359491/164448295-d31867bc-4301-4dc7-91c6-aa58d076261b.png)

![image](https://user-images.githubusercontent.com/94359491/164448336-bbbc2b97-b10b-46e4-9bec-f0b5ce2fbea0.png)

![image](https://user-images.githubusercontent.com/94359491/164448369-9cbbeec5-1003-4c2d-8960-c3a7feba8ac1.png)

![image](https://user-images.githubusercontent.com/94359491/164448398-1f45a001-61e3-4e82-8055-a607e0f7c862.png)

</details>


**Verified**

- Data Unavailable" story should be renamed to "Gathering data (legacy)

<details>

![image](https://user-images.githubusercontent.com/94359491/164448736-e7790ff4-b64a-4e9a-ab5c-e3375d0cfd6c.png)


</details>

**Verified**

- The `WPDashboardApp > WPDashboardWidgets >` Ready story now fixed to include the relevant Analytics parts of the widget (with regular data). Now it is complete and include Search Console data as well as Analytics CTA.

<details>
Storybook images 

![image](https://user-images.githubusercontent.com/94359491/164450233-8d249770-e30f-4827-a7da-e76ad8dc6e6e.png)

![image](https://user-images.githubusercontent.com/94359491/164450264-af72a1bb-4905-45b9-8029-b204b8b15afa.png)

![image](https://user-images.githubusercontent.com/94359491/164450301-b68e6dfc-c7e2-4025-b7e5-1947e00cec4b.png)

WP dashboard images

![image](https://user-images.githubusercontent.com/94359491/164450464-432cc670-c24d-41b4-9216-9b41aaf25415.png)

![image](https://user-images.githubusercontent.com/94359491/164450490-0ba0dc34-fd9c-4484-a0ee-32b71fa2e500.png)

![image](https://user-images.githubusercontent.com/94359491/164450632-ecd81e90-6d6b-41db-9b73-8d2b66fbca02.png)

</details>
