### ISSUE TITLE
Enhance presentation of internal server errors in widgets with Site Kit specific guidance

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4997]
## Bug Description

For errors that come from WordPress core, which we output in the Site Kit widgets consider including any HTML markup. At present errors such as the below can appear, which don't contain a link and have unusual formatting, with no space between the sentences. 

`"There has been a critical error on this website.Learn more about troubleshooting WordPress" `

![image](https://user-images.githubusercontent.com/41326532/160667607-5116ac63-f4e3-4310-b5c5-8f8a0cd4e5cf.png)

[Video of experience
](https://recordit.co/DkpYvhEKdv)

## Steps to reproduce

1. Set up Site Kit
2. Open a new tab and navigate to the Site Kit dashboard
3. Click on your user profile icon in the header and select "Manage Sites" from the dropdown 
4. Click the button to "Remove access" for the site you are using
5. Close the browser tab - **do not click "Back" to go back to your site as this will trigger a disconnect**
6. Wait 1 hour for the cached content to expire 
7. Revisit your Site Kit dashboard

## Additional Context

- We did decide to strip html comments previously. See https://github.com/google/site-kit-wp/issues/4169

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ReportError` component should be updated to display a custom error message for errors with a `code` of `internal_server_error`:
    * The content of the new error message should be: _There was a critical error on this website while fetching data._
* The `ReportError` component should be updated to display a custom error message for errors with a `code` of `invalid_json`:
    * The content of the new error message should be: _The server provided an invalid response._
* This logic to alter the error messages conditionally should be implemented in a reusable way so that it does not only work in the `ReportError` component, but it should also be used in the custom error notices used in the PageSpeed Insights widget (see `LabReportMetrics` and `FieldReportMetrics` components).
    * Those two components should be altered to also have the message accompanied by the "Retry" button and "Get help" link (using similar markup and copy as this combination of button/link uses elsewhere in the plugin already).
* In both cases, it should be ensured that the usual "Retry" button and following "Get help" link are present. This may already be the case based on current logic, but should be double checked, and added if not already present.

## Implementation Brief

- Create a new function, `getReportErrorMessage` (or any proper name), which accepts an `error` object and returns the message according to the AC when the `error.code` is `internal_server_error` and `invalid_json`, falling back to `error.message`.
- Use this new function to determine the error messages within the `ReportError`, `LabReportMetrics`, and `FieldReportMetrics` components.
- Create a new reusable component, `ReportErrorActions` (or any proper name).
  - It takes `moduleSlug` (`string`) and `error` (`object|array<object>`) as arguments.
  - Extract the `Request access` and `Retry` buttons and the `Get help` link from the `ReportError` component, including the `handleRetry` callback and associated code, and render them in the new component.
- Update the `ReportError`, `LabReportMetrics`, and `FieldReportMetrics`  components to render the new `ReportErrorActions` component.

### Test Coverage

* Add test cases for the `getReportErrorMessage` utility function.
* Add test cases for the `ReportErrorActions` component.
* Add stories for the `ReportErrorActions` component.
* In `assets/js/components/ReportError.stories.js`, add stories for the `internal_server_error` and `invalid_json` errors.
* In `stories/module-pagespeed-insights-components.stories.js`, add error stories for the `LabReportMetrics` and `FieldReportMetrics` components.

## QA Brief
* Check the steps to reproduce section to reproduce the bug.
* Ensure that the wording in the error message is now as per the AC.
* Stories can be verified here:
    * https://google.github.io/site-kit-wp/storybook/pull/6322/?path=/story/modules-pagespeed-insights-widgets-dashboardpagespeedwidget--error
    * https://google.github.io/site-kit-wp/storybook/pull/6322/?path=/story/components-reporterror--report-error-with-custom-internal-server-error-message
    * https://google.github.io/site-kit-wp/storybook/pull/6322/?path=/story/components-reporterror--report-error-with-custom-invalid-json-message

## QA Eng Brief
* Simulate the internal_server_error and invalid_json error messages for a specific module, for e.g for the 'GET:report' Analytics endpoint. Ensure the messages are displayed as per the AC.

## Changelog entry

* Improve error messages when encountering an internal server error in WordPress.

**Comment by jamesozzie** [comment]
@aaemnnosttv @felixarntz Adding you here for visibility on this issue.

**Comment by aaemnnosttv** [comment]
@felixarntz how does this sound? I think identifying it by the code alone should be sufficient – it's also the only part of the error returned by the wp fatal error handler that isn't filterable.

**Comment by felixarntz** [comment]
@aaemnnosttv That sounds good. I'll leave this in ACs for now, but only to finalize what to do about the documentation.

@bethanylang @jamesozzie I may not be fully up to date on the latest documentation efforts, do we already have documentation about generic dashboard errors like fatal errors or information on troubleshooting potentially related plugin conflicts? See the ACs of this issue which include a proposed documentation URL to point to. We either need to see if we already have something worth pointing to here, or otherwise we need to write corresponding documentation. If the latter, obviously this issue will be blocked by that.

cc @eclarke1 @FlicHollis for awareness

**Comment by aaemnnosttv** [comment]
@felixarntz with the updates coming to documentation/support URLs, is that all we're waiting for here?

**Comment by felixarntz** [comment]
@aaemnnosttv Updated the ACs here to use the new support endpoint, and send the `internal_server_error` error ID. This will for now lead to the troubleshooting URL, and a dedicated article could be added later if it is worth it.

**Comment by felixarntz** [comment]
@aaemnnosttv I've defined ACs here as discussed, also encompassing #5025 which I'll close as a duplicate. Please review - if it sounds good, feel free to move to IB column.

**Comment by aaemnnosttv** [comment]
LGTM, thanks @felixarntz 👍

**Comment by aaemnnosttv** [comment]
> * The service provided an invalid response.

@felixarntz one thing I just noticed – this one should perhaps be rewritten to say the "server" provided an invalid response? These usually happen from the server rather than the service.

**Comment by FlicHollis** [comment]
Hi @felixarntz just following up here, if we can answer @aaemnnosttv 's question above it looks like this can be moved to IB. Thanks!

**Comment by felixarntz** [comment]
@aaemnnosttv Makes sense, updated!

**Comment by techanvil** [comment]
Hey @hussain-t, thanks for the IB. I do have a bit of a concern about the idea of returning elements from the hook. Conceptually I feel that hooks are more suited to sharing logic whereas shared presentation should preferably be expressed via components. Admittedly there may be cases where it's necessary to return JSX or a component from a hook but I think we can avoid it in this case.

Instead, I'd suggest creating a utility function for the logic of determining the error message, and extracting the "Request access/Retry/Get help" elements into a separate component for reuse in `ReportError`, `LabReportMetrics` and `FieldReportMetrics`. How does that sound to you?

**Comment by hussain-t** [comment]
Thanks, @techanvil. Initially, I thought of having the same approach as you suggested. However, the problem is decoupling/reusing the description/message. As for the `ReportError` component, we are composing it into the `CTA` component. However, the `LabReportMetrics` and `FieldReportMetrics` render it. As these components render the error message differently, we cannot have the error message within the reusable component.

**Comment by hussain-t** [comment]
Thanks, @techanvil. I have updated the IB. LMK WDTY?

**Comment by techanvil** [comment]
Thanks for the update @hussain-t. However, I do think it's still not quite right. Note that `LabReportMetrics` and `FieldReportMetrics` each only expect a single error, so they don't need the logic to find unique errors. Also, the handling for `internal_server_error` and `invalid_json` has been dropped from the IB.

I would suggest a bit of a rewrite along these lines:

- Create a new function `getReportErrorMessage` (or any proper name), which accepts an `error` object and returns the message according to the AC when the `error.code` is `internal_server_error` and `invalid_json`, falling back to `error.message`.
- Within the `ReportError`, `LabReportMetrics` and `FieldReportMetrics` components, use this new function to determine the error messages.
- Create a new reusable component, `ReportErrorActions` (or any proper name).
  - It takes `moduleSlug` (`string`) and `error` (`object|array<object>`) as arguments.
  - Extract the `Request access` and `Retry` buttons and the `Get help` link from the `ReportError` component, including the `handleRetry` callback and associated code, and render them in the new component.
- Update the `ReportError`, `LabReportMetrics` and `FieldReportMetrics`  components to render the new `ReportErrorActions` component.

**Comment by hussain-t** [comment]
Perfect! Thanks, @techanvil; I have updated the IB.

**Comment by techanvil** [comment]
Thanks, @hussain-t!

IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@asvinb 

Verified on dev.
I followed the steps to reproduce under details and verified it 2 times, but I'm getting Data errors instead of internal server errors. 
```
Data error in Search Console
Error: Looks like your site is not allowed access to Google account data and can’t display stats in the dashboard. 
```

<details>

![image](https://user-images.githubusercontent.com/94359491/208827036-3c6893dd-8222-4eb9-9caa-b8ef8374367d.png)

![image](https://user-images.githubusercontent.com/94359491/208827070-46b399cb-d129-452d-86a3-3ec4b7fbb277.png)

</details>

**Comment by asvinb** [comment]
@mohitwp I had quite some trouble recreating the bug as well following the steps to reproduce in the ticket description. I thought I was missing something and then I manually triggered the error by changing the PHP code. That's why I also added a QA:Eng label to the ticket since we need to manually trigger the issue.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified all stories.
- As mentioned [above](https://github.com/google/site-kit-wp/issues/4997#issuecomment-1360870745) I'm not able to reproduce error via the steps mentioned under QAB.
- Assigning QA:eng label because as per Asvin error required to trigger manually by changing the PHP code.

**Comment by hussain-t** [comment]
### QA:Eng Verified ✅ 

- Verified simulating the `internal_server_error` from the server and error message.
- Verified simulating the `invalid_json ` from the server and error message.

![Screenshot 2023-01-06 at 11 11 13 PM](https://user-images.githubusercontent.com/24408261/211068519-18ff8a1e-0db3-4b16-ba1d-e6ad57c7aea0.png)

![Screenshot 2023-01-06 at 10 40 02 PM](https://user-images.githubusercontent.com/24408261/211068540-d845809c-7e5a-41c1-886e-b607b22f4599.png)

**Comment by felixarntz** [comment]
Providing a screenshot of the PSI widget with a forced 500 error here for completeness (this should probably have been mentioned in the QA Brief as something to look at).
<img width="789" alt="Screen Shot 2023-01-12 at 5 13 06 PM" src="https://user-images.githubusercontent.com/3531426/212121286-25ab293e-6951-4e19-b972-14d7b36d3a69.png">
