### ISSUE TITLE
ZeroDataMessage should not start string after colon with capital letter

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#5001]
## Bug Description

The code in https://github.com/google/site-kit-wp/blob/4c156b533f57135c49dc64ff1adf2c1e143906cb/assets/js/modules/analytics/components/common/ZeroDataMessage.js#L41-L53 has grammatical issues:

<img width="1219" alt="CleanShot 2022-03-29 at 23 34 32" src="https://user-images.githubusercontent.com/90871/160718413-87b10948-c01b-465c-93e1-9de30db32a4f.png">

There shouldn't be a capital letter—essentially a "new sentence", following the colon. _Ideally_, we should probably reformat this `i18n` string to have "page" or "site" be the `%s` part of the string, and not the entire sentence with the reasoning around it.

But given the logic of the component and the cost of that extra translation, we should instead change the prefix string to end with a full-stop/period instead of a colon.

## Steps to reproduce

1. Enable the `zeroDataStates` feature flag
2. Connect an Analytics property with zero data, or use the tester plugin to simulate zero data for Analytics
3. Visit the Site Kit dashboard and scroll to "Top Content over the last 28 days".
4. See text issue

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Translations for Search Console and Analytics zero data messages should contain correct English-language capitalisation.
* Translations used should be more distinct/not combined as they are currently.

## Implementation Brief

Change the string values and logic in `ZeroDataMessage.js` to be:

```js
if (skipPrefix) {
  return url
    ? __("Your page hasn’t appeared in Search yet", "google-site-kit")
    : __("Your site hasn’t appeared in Search yet", "google-site-kit");
}

return url
  ? __(
      "No data to display: your page hasn’t appeared in Search yet",
      "google-site-kit"
    )
  : __(
      "No data to display: your site hasn’t appeared in Search yet",
      "google-site-kit"
    );
```

This should be done in both `assets/js/modules/search-console/components/common/ZeroDataMessage.js` and `assets/js/modules/analytics/components/common/ZeroDataMessage.js`, using the above text for Search Console and `Your page hasn’t received any visitors yet` in Analytics.

Note: the old Analytics text used "hasn't gotten any visitors", but I think "received" is a better verb to use here, so let's go with that. 😅 

### Test Coverage

* No tests needed; VRTs might need updating.

## QA Brief

* Visit the Site Kit dashboard with a site with zero data for both Search Console and Analytics. (This can be forced by using the Tester Plugin and setting Analytics and Search Console to return zero data reports.)
* The main dashboard should show this in a zero state table view:
<img width="1014" alt="CleanShot 2022-04-06 at 22 54 35" src="https://user-images.githubusercontent.com/90871/162078363-24993795-65ac-495c-a1ff-091df75fa8d8.png">
* The page-specific dashboard should show this in a table view:
<img width="489" alt="CleanShot 2022-04-06 at 22 53 25" src="https://user-images.githubusercontent.com/90871/162078435-85967ef2-3d6a-46bb-8640-4263a1985159.png">

## Changelog entry

* Fix zero data state message formatting issues.

**Comment by aaemnnosttv** [comment]
I don't think it's safe to construct the translated strings in such a way as it's essentially concatenation to build two different sentences. We should only use placeholders for single dynamic values, such as a site URL, search query, name, etc. We should simply have two separate translated strings – I'm sure if one is translated the other will as well, it isn't a big overhead 😄 

If the same strings are used in more than one place, it may make sense to extract the strings to their own module (essentially dynamic runtime constants) and import them where they're used. We haven't really done this yet so I'd be fine duplicating for now too but might be something to explore going forward, that could be for another issue too though. Originally, we actively avoided doing things like this due to translations not being immediately available, but that's no longer the case.

**Comment by tofumatt** [comment]
Works for me. In this case it's _probably_ safe but that's a fair point. I don't mind going overboard make the text better localised 👍🏻 

It's probably overboard to do the dynamic runtime constants for duplicate strings for an app our size. They'll be pretty minor and we'll probably add just as much logic code to handle the imports (since we'll need to do that in every place the string is found) as we'll save reducing duplicate string output 😉 

IB updated 👍🏻

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@tofumatt I've passed this based on the QAB, but should 'Search' be capitalised? 🤔 

**Verified:**

- Main dashboard shows in a zero state table view: `No data to display: your site hasn’t received any visitors yet` and `No data to display: your site hasn’t appeared in Search yet. `
- Entity dashboard shows in a zero state table view: `No data to display: your page hasn’t appeared in Search yet`

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/162404076-aa6228d1-fe6c-459e-b565-eac91bb202c3.png)
![image](https://user-images.githubusercontent.com/73545194/162404091-f380622d-f457-4f20-942d-afa7cc94ccf3.png)

</details>

**Comment by aaemnnosttv** [comment]
> @tofumatt I've passed this based on the QAB, but should 'Search' be capitalised? 🤔

@wpdarren I wondered the same, but it's used that way in several places so it seems to be intentional. My guess is that it's short for Search Console. @marrrmarrr ?

**Comment by marrrmarrr** [comment]
@aaemnnosttv @wpdarren indeed when referring to the product ("Google Search" or "Search" for short), the word is capitalised. 
Here's an example from a [help article](https://support.google.com/webmasters/answer/9079473?hl=en): "If you still can't find your site or page in Search results..."
