### ISSUE TITLE
Fix typo in Goal CTA

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5004]
## Bug Description

The Create a New Goal CTA currently reads:

Set up goals to track how well your site fullfils...

"Fullfils" should be "fulfills."

## Screenshots

![image](https://user-images.githubusercontent.com/12189958/160863478-ec79d2e4-42a0-48f8-ac19-cc0b78da4f27.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `CreateGoalCTA` component is updated to correctly display the `fulfills` word in the description sentence.

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/5012

### Test Coverage

* N/A

## QA Brief

* Once merged, the fix should be observable here:
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidget--ready-with-create-goal-cta

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified : 

- The CreateGoalCTA component is updated to correctly display the fulfills word in the description sentence.
- Verified for both 'gathering' and 'zero' data states.

<details>

![image](https://user-images.githubusercontent.com/94359491/161253289-58913eae-43d6-4238-9af9-d1c7d407097f.png)

![image](https://user-images.githubusercontent.com/94359491/161253389-695005a0-134c-4ca4-a23f-b676a64f28dd.png)

</details>
