### ISSUE TITLE
The "gathering data" overlay is not appearing on the All Traffic widget's pie chart 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5006]
## Bug Description

The All Traffic widget's pie chart does not show the "gathering data" overlay present in the [Figma file](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734) when Analytics is gathering data. Reported on the [bug bash in Asana](https://app.asana.com/0/1201999381911618/1202030688961863/f)

Reported from the [bug bash in Asana](https://app.asana.com/0/1201999381911618/1202030688961867/f)

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/2a58c300-0773-410d-9b35-3e8bc0bbc265)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the All Traffic widget is in "gathering data" state:
    * The pie chart should have the "gathering data" overlay present in the [Figma file](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734).
    * The big number under "All Users" should be replaced with the regular "gathering data" text used elsewhere in such situations (also as seen in the Figma file).

## Implementation Brief

- In `UserDimesionsPieChart.js`:
    - If `gatheringData` is true, render the `<GatheringDataNotice />` component just before the `<PieChartZeroData />` component is rendered. Pass the new style variant (created below) prop here once created.
- In `GatheringDataNotice.js`:
    - The existing `NOTICE_STYLE.OVERLAY` variant of `GatheringDataNotice` cannot be used above as it does not match the Figma mock. So create a new style variant for this component similar to the `NOTICE_STYLE.OVERLAY` style, e.g. "NOTICE_STYLE.SMALL_OVERLAY" (= "small-overlay"). Ensure the style matches the Figma mock (add the new corresponding `&.googlesitekit-gathering-data-notice--has-style--small-overlay` style class to `_googlesitekit-gathering-data-notice.scss`). Consider moving the common SCSS from the `&.googlesitekit-gathering-data-notice--has-style-overlay` class into its own mixin so it can be used within both, the existing `&.googlesitekit-gathering-data-notice--has-style-overlay` and the new `&.googlesitekit-gathering-data-notice--has-style--small-overlay` class. 
    - Ensure that the existing overlay style used in the `<GoogleChart />` (type = Line Chart) components is not modified in any way.
---
- In `modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js`:
    - Pass `isGatheringData` as a prop to the `<TotalUserCount>` component.
- In `TotalUserCount.js`:
    - Destructure the `isGatheringData` prop. 
    - If the `zeroDataStates` feature flag is enabled and `isGatheringData` is true, render the `<GatheringDataNotice>` component after the `<h3>` element. In this case, ensure the remaining two divs, `googlesitekit-data-block__change` and `googlesitekit-data-block__datapoint` are _not_ rendered.
- In `GatheringDataNotice.js`:
    - Once again, the existing `NOTICE_STYLE.DEFAULT` or other versions of the `<GatheringDataNotice>` component will not be directly usable. So create another "NOTICE_STYLE.DEFAULT_TEXT_ONLY" (= "default-text-only") variant as above. Within `_googlesitekit-gathering-data-notice.scss`, create the corresponding class `&.googlesitekit-gathering-data-notice--has-style-default-text-only` and simply add the existing `notice-text` mixin to it. Check if this suffices otherwise add extra styles to match the Figma mock.
---
- Add a new Storybook variant, "Gathering Data (zeroDataStates enabled)", similar to the existing "Zero Data (zeroDataStates enabled)" story in `module-analytics-components.stories.js` when the widget is gathering data. Ensure both the above components show the correct 'gathering data' text as per the Figma mocks.

### Test Coverage

* No new tests required.

## QA Brief

* Verify the first point of the Acceptance Criteria is met - [see this comment](https://github.com/google/site-kit-wp/issues/5006#issuecomment-1088522672).
* Verify the new "gathering data" notice on the pie chart is displayed in the [Analytics Module component stories](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-components-dashboard-all-traffic-widget--gathering-data-zerodatastates-enabled).
* Verify that the "gathering data" notice overlay has not changed in other widgets such as Graphs.

## Changelog entry

* Add "gathering data" overlay to the All Traffic widget when Analytics is gathering data.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by jimmymadon** [comment]
Since #5007 covers the second point of the AC, I have removed that code from the attached PR. When CR-ing and QA-ing, please ignore the AC and IB related to the Total Users Count widget showing gathering data. That code has already been merged from #5007.

**Comment by jimmymadon** [comment]
@aaemnnosttv The method you came up with to add default variants for `zeroDataStates` enabled widgets which I executed as part of [this commit](https://github.com/google/site-kit-wp/pull/5026/commits/9a6f9b0b589e05327316ff190c5aa3ca11d0318c) is great. However, some stories break and require tweaks within the production components themselves. A [recent commit](https://github.com/google/site-kit-wp/commit/7f7a5cd8d9a02db35d7e2da041b9979da2f1d671) which I merged into my PR for this issue has already added a Gathering Data variant for now. So perhaps we can look into refactoring this as part of a separate issue otherwise this might not get into Approval this sprint.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The pie chart has the "gathering data" overlay present in the [Figma file](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734) on main and entity dashboard.
- The new "gathering data" notice on the pie chart is displayed in the [Analytics Module component stories](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-components-dashboard-all-traffic-widget--gathering-data-zerodatastates-enabled).
- The "gathering data" notice overlay has not changed in other widgets, i.e. graphs. Checked on main and entity dashboard.

![image](https://user-images.githubusercontent.com/73545194/162409090-eedf4c84-d655-4c1b-96c6-aed6d1ce0550.png)
