### ISSUE TITLE
The All Traffic widget shows 0 instead of the "gathering data" text

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5007]
## Bug Description

When Analytics is gathering data, the user count in the All Traffic widget should show the "gathering data" text instead of a 0. (The 0 should only be shown there when Analytics is not gathering data, but it's a "zero report".)

See attached screenshot, compared to the [Figma file which has the "gathering data" text](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734) there.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Analytics is gathering data, instead of showing a "0" under the "All Users" header (eg. showing the number of views), the text shown should be "gathering data…", as shown in the Figma mockup: https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=514%3A3734

<img width="815" alt="CleanShot 2022-03-31 at 13 08 05" src="https://user-images.githubusercontent.com/90871/161051258-f3274590-894b-4e44-822c-1b84c1a4cc99.png">

## Implementation Brief
* Using `assets/js/components/GatheringDataNotice.js`,
	* Add a new `LARGE` property in `NOTICE_STYLE` with `large` as value.
* Using `assets/sass/components/global/_googlesitekit-gathering-data-notice.scss`,
	* Add the `.googlesitekit-gathering-data-notice--has-style-large` class name which contains
		* the `notice-text` mixin
* Using `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/TotalUserCount.js`,
	* Add a new boolean prop, `gatheringData`.
	* Display the elements between `googlesitekit-data-block__datapoint` and `googlesitekit-data-block__suffix` if `gatheringData` is `false`.
	* If `gatheringData` is `true`, render the `GatheringDataNotice` component imported from `assets/js/components/GatheringDataNotice.js`, with `style` prop set to `large`.
* Using `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js`,
	* Pass the `isGatheringData` value to the `gatheringData` prop of the `TotalUserCount` component.

### Test Coverage
* No new tests to be added.

## QA Brief
* Enable the `zeroDataStates` feature flag.
* Set Analytics in "gathering" mode via the tester plugin.
* Check if the "gathering data..." message is displayed below the "Total Users" text in the All Traffic widget instead of `0`.

## Changelog entry

* When Analytics is gathering data, ensure "gathering data" is shown under All Users in the All Traffic widget.

**Comment by tofumatt** [comment]
Looks good, IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The "gathering data..." message is displayed below the "Total Users" text in the All Traffic widget instead of 0.
- Also checked on smaller screens for the "gathering data..." message placement.

![image](https://user-images.githubusercontent.com/73545194/161746648-0f14e4a1-f628-4ea7-b4d5-1c6ba51d5676.png)
