### ISSUE TITLE
Odd-looking lines below Search traffic and Overall page metrics widget numbers

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5010]
## Bug Description

For some reason, when Analytics/Search Console are gathering data, the "Search traffic" widget in the Site Kit dashboard has horizontal lines below the "gathering data" texts that replace the big numbers. It looks like these were present in the original Figma design, but I'm questioning why - they look weird and they are not present if the regular numbers are shown, so why are they shown when gathering data? That doesn't make sense to me.

The same weird UX with the horizontal lines is present in the "Overall page metrics" widget shown on the entity dashboard.

See attached screenshot. Also a second screenshot is present for comparison with regular numbers.

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/e98762f3-ad5f-4d05-a02d-6c03f124c917)

More discussion and screenshots can be found [on the Asana ticket](https://app.asana.com/0/1201999381911618/1202030688961871/f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* UI for the big numbers in the "Search traffic" _and_ "Overall page metrics" widgets should be adjusted as follows:
    * There should not be a gray horizontal line below them (specifically relevant for when they display the "gathering data..." text instead of a number, as seen in the screenshot above).

## Implementation Brief
* Using `assets/sass/components/global/_googlesitekit-gathering-data-notice.scss`,
	* Set the padding for the `span` within the `notice-text` mixin to `0`.
	* Remove the `after` pseudo-element from `.googlesitekit-gathering-data-notice--has-style-default`.

### Test Coverage
* No new tests to be added.

## QA Brief

* Create a new site and connect the Analytics module, _or_ force gathering data state for Search Console and Analytics via the Tester plugin.
* Navigate to the Main Dashboard.
* Verify that horizontal lines below "gathering data" don't appear in the "Search traffic" widget, as per the AC.
* Navigate to an Entity Dashboard.
* Verify that horizontal lines below "gathering data" don't appear in the "Overall page metrics" widget, as per the AC.

## Changelog entry

* Remove lines below "gathering data" text on chart metric selection buttons.

**Comment by tofumatt** [comment]
Assigning this to @felixarntz for now because I think we're waiting to confirm with UX if we can remove these lines, along with a few other UX questions we had from the bug bash.

I think the best solution _would_ be to remove them, I recall that's what @marrrmarrr and @eclarke1 thought as well, but let's leave this in triage just to confirm that's okay with UX 🙂

**Comment by Pratheep-lab** [comment]
I believe those lines were created in the design to represent the delta changes i.e the positive or negative arrow below the big number. But I don't see much of a value to it, especially if this makes it inconsistent, we can remove those. Below is a mock without those arrows. 
![image](https://user-images.githubusercontent.com/81642523/161057823-d55c848e-283d-4cf4-99e8-31d92e8aea74.png)

**Comment by marrrmarrr** [comment]
Yeah, we can remove them, the trend numbers are a fairly small element of this graph so no need to represent them with the strange lines.

**Comment by tofumatt** [comment]
IB ✅
