### ISSUE TITLE
Refactor `viewContext` access with custom hook

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5011]
## Feature Description

We often use a React context that we refer to as "view context" in many places. As it is, this requires a few imports and a `useContext`. This could be simplified to a single hook as we do in a few other places.

```js
import { useContext } from '@wordpress/element';
import ViewContextContext from '../path/to/components/Root/ViewContextContext';
// ...
const viewContext = useContext( ViewContextContext );
```

Should be

```js
import useViewContext from '../path/to/hooks/useViewContext';
// ...
const viewContext = useViewContext();
```

A minor refactor but would simplify 50+ instances of the above in the codebase.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The use of `useContext( ViewContextContext )` should be refactored with a new hook that returns the same value, called `useViewContext()` as shown above

## Implementation Brief
* Create `assets/js/hooks/useViewContext.js` which exports the `useViewContext` hook.
	* It should return the value of `useContext` (imported from `@wordpress/element`) with the `ViewContextContext` as the argument.
	* `ViewContextContext` should be imported from `assets/js/components/Root/ViewContextContext.js`
* Update codebase to use the new hook where we are using `useContext( ViewContextContext )`

### Test Coverage
* Add tests for the new hook.

## QA Brief

* This change touches a lot of files but the actual code change is very minimal; it's essentially a refactor.

To QA this issue, run through usual smoke tests, especially testing different "page contexts", eg. visit the main dashboard, the entity-specific dashboard, the settings page, etc. This code changes HOW we get the context we're on, the main and entity dashboards should still behave exactly as-expected and as they did before this change.

## Changelog entry

* Add `useViewContext` hook for retrieving the current view context.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@aaemnnosttv @tofumatt I feel it's not realistic to expect a smoke test on every part touched considering it's only a 7 estimate. So, I have focused on the GA events on the dashboard navigation and a few of the other widgets on main and entity dashboard. I have also looked at the events triggered on the settings. Speaking with Tom, any other testing would be picked up in the CR and also E2E testing that you complete. 

**Verified:**

- Checked the dashboard navigation on main and entity to ensure that `viewcontext `still appears in the log, i.e. `dashboard_navigation ` and pageDashboard_navigation`
- Checked the All Traffic widget for main and entity to ensure that `viewcontext `still appears in the log, i.e. `dashboard_all-traffic-widget` and `pageDashboard_all-traffic-widget`
- Checked the Authentication success notification when a module was set up, i.e. Analytics. The `viewcontext `still appears in the log, i.e. `dashboard_authentication-success-notification`
- Checked Idea Hub to ensure that `viewcontext` still appears in the log, i.e. when you click to save an idea `dashboard_idea-hub-widget`
- Checked a feature tour appeared and the `viewcontext `still appears in the log, i.e. for the Idea hub feature tour, the `dashboard_idea-hub-widget` is logged with an eventAction: `feature_tooltip_view`.

Hopefully, this will suffice but please let me know if there's anything else you'd like me to cover.
