### ISSUE TITLE
Site Kit & G4

### ISSUE THREAD

**Issue by ChelseaSianEvans** [google/site-kit-wp#5014]
## Steps to reproduce

1. Go to planmywedding.com
2. Click on page source
3. Scroll down to gtag
4. After assigning G4 property in Site Kit my analytics is still not receiving data, looking at page source it still show the old UA property with the G4 property but no data coming through, i disabled autopmise and Updraft when enabling and this still didnt work'

--
  | <script data-service="google-analytics" data-category="statistics" type="text/plain" src='https://www.googletagmanager.com/gtag/js?id=UA-77347453-3' id='google_gtagjs-js' async></script>
  | <script type='text/javascript' id='google_gtagjs-js-after'>
  | window.dataLayer = window.dataLayer \|\| [];function gtag(){dataLayer.push(arguments);}
  | gtag('set', 'linker', {"domains":["www.planmywedding.com"]} );
  | gtag("js", new Date());
  | gtag("set", "developer_id.dZTNiMT", true);
  | gtag("config", "UA-77347453-3", {"anonymize_ip":true});
  | gtag("config", "G-3XQSLGMKVP");
  | </script>

## Additional Context

 - PHP Version: 
 - Browser: Chrome
 - Plugin Version: 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Hi there @ChelseaSianEvans,

Thanks for reaching out. We provide Site Kit initial support requests from the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. 

Note also that I did check your site and the snippet placements via Site Kit are valid. You may wish to use the [tagassistant.google.com](https://tagassistant.google.com/) service to check your snippet placements. You will, however, need to temporarily disable your captcha for the service to detect your tags. 

I'll keep an eye out for your topic. We can communicate from there. Thank you!
