### ISSUE TITLE
Minor styling issue on iPad in portrait mode on Search traffic widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5016]
## Bug Description

In iPad portrait mode the `Search traffic over the last x days` widget has a minor styling issue for the `Unique Visitor from search` section, in that it is not aligned with other sections because title is in two lines.

Appears to be an issue currently but was discovered in gathering and zero data state.   This was created from an [Asana ticket](https://app.asana.com/0/1201999381911618/1202041568528961/f) 

<details>
 <summary>Screenshots</summary>

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/d7d768eb-e720-4152-aacb-12e70426e581)

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/03ac250a-dd70-4cc8-80b6-41e2b149cbdf)

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this in favor of #4582 which is already defined. Thanks!
