### ISSUE TITLE
Enhance error messages for "Invalid JSON Response" errors

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5025]
## Feature Description

The Site Kit API client on the frontend uses `@wordpress/api-fetch` under the hood which is a layer on top of `window.fetch` which is designed for interacting with the WordPress REST API. One of the features it provides is to eliminate some of the boilerplate of making fetch requests, such as resolving the JSON body from the response.

The client doesn't force a JSON response, but it does assume one by default (this can be controlled with an option). In the event that the response is not JSON-parseable (and by default attempts to parse it as such), the client will throw a generic (and very familiar looking) [`invalid_json`](https://github.com/WordPress/gutenberg/blob/08cf4a96d1f14fcdf4c55886ba237fb294f9c465/packages/api-fetch/src/utils/response.js#L34-L37) error.

This is not particularly useful to the average end user and often leads to support requests which are difficult to provide good support for due to the limited information. Accordingly, we should enhance our error handling in such cases to provide more useful, or at the very least – less cryptic messaging to the end user, and where possible additional context for support.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should never display a ["The response is not a valid JSON response"](https://github.com/WordPress/gutenberg/blob/08cf4a96d1f14fcdf4c55886ba237fb294f9c465/packages/api-fetch/src/utils/response.js#L34-L37) error message to the end user as part of its user-facing interface (console messages/logging are fine because this is developer-centric tooling)
* Instead, it should show the following, based on a few other conditions:
    * If the response status code is 504: _The service took too long to respond._ (see #4504 for reference)
    * TODO: Define other conditions.
    * Otherwise: _The service provided an invalid response._
* In all of the above cases, the error should be accompanied with the Retry button implemented via **TODO** (add issue link here for error notifications MVP issue to implement that).

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv The ACs so far seem a bit vague. What do we want to show instead? What should we do if the response is not JSON?

**Comment by aaemnnosttv** [comment]
> What do we want to show instead?

@felixarntz I meant to ask you about it, this was just intended to be a starting point so far.

As for what we show instead, it could be contextual similar to #4997 (this is mostly relevant for `ReportError` anyways I think 🤔 ). Essentially a more useful message for the user that potentially links to some SK docs for troubleshooting.

> What should we do if the response is not JSON?

That's usually the reason for the error in the first place! 😄 Another case though could be corrupted JSON, if for example, a PHP Notice were output right before the otherwise valid JSON response, or even an empty response body would also be invalid – although an HTML response could also raise this error. There are a number of things we probably could do but we could probably improve the end user experience quite a bit with even a small change (again, similar to #4997).

**Comment by felixarntz** [comment]
@aaemnnosttv Should we wait until #4997 has been implemented and then basically add other "special cases" to the handling? We could cater for certain situations (e.g. the 504 you have here) but otherwise fall back to the wording you already have in the ACs here. There should then also be a "Get help" link with the `error_id` parameter set based on what we discovered (with the fallback there being simply the `invalid_json`).

**Comment by aaemnnosttv** [comment]
@felixarntz I'm not sure this needs to wait for the other issue as the conditions for both are mutually exclusive.

> We could cater for certain situations (e.g. the 504 you have here) but otherwise fall back to the wording you already have in the ACs here.

Unfortunately we don't have access to the status code, so we can't use that as part of a condition for the handling. We could handle this differently in the PSI widget, before passing it on to a `ReportError` though?

I think for the most part this will still be a generic error, but we can provide more details in the troubleshooting doc for this case.

**Comment by felixarntz** [comment]
The ACs newly defined on #4997 cover this issue as well as it's closely related. Please follow along the other issue going forward, closing this as a duplicate.
