### ISSUE TITLE
Refactor GitHub actions into aggregate workflows

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5030]
## Feature Description

When we initially migrated from Travis CI to GitHub Actions, perhaps the biggest pain was that GHA did not support rerunning a single job, only workflows could be reran.

As of some time last month, this is no longer the case and individual jobs or even all failed jobs in a workflow can (finally) be rerun! 🎉  See the announcement here: https://github.blog/2022-03-16-save-time-partial-re-runs-github-actions/

This means we can eliminate a lot of duplicate workflow definitions where we had previously split out various test jobs into dedicated workflows as a workaround for this limitation (particularly for E2E) where rerunning everything would cost a lot of wasted time that is important to avoid for a number of reasons.

This may justify multiple issues to accomplish completely without doing a single massive PR, but we could probably also use this opportunity to DRY up some of our workflow definitions in the process (see #3969).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All E2E test actions should be refactored into a single action.
* All PHPUnit test actions should be refactored into a single action.

## Implementation Brief

* Unit tests
  * Create a `.github/workflows/php-tests.yml` workflow file.
  * Copy over the content from `.github/workflows/php-tests-wp-latest-php-7-4.yml`
  * Add a build matrix to the workflow. See [GitHub Docs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)
  * Build matrix should container `WP_VERSION` and `WP_MULTISITE` as dimensions
  * Replace all occurencies of `WP_VERSION` and `WP_MULTISITE` with the matrix variables according to GitHub Docs.
  * Rename the job to `php-tests`.
  * Rename the job name to use the matrix variables.
  * Currently multisite setup is only tested with `latest` WordPress version. Use the `include` setting from workflow matrix configuration to only test multisite with latest WordPress Version. See [Expanding or adding matrix configurations](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations) in the GitHub Docs.
  * Copy over the last step `Run Unit Tests` from the `php-tests-wp-latest-multisite-php-7-4.yml`. Conditionally run the `composer test:multisite -- --verbose` if `WP_MULTISITE` from the matrix is set to `1`, else run the default `composer test -- --verbose`
  * Change the name of the concurrency group to `php-tests-${{ github.ref }}`
  * Change the paths from `.github/workflows/php-tests-wp-latest-php-7-4.yml` to `.github/workflows/php-tests.yml` for `push` and `pull_request`.
  * Delete all other existing `.github/workflows/php-tests-*` files.
* E2E tests
  * Create a `.github/workflows/e2e-tests.yml` workflow file.
  * Copy over the content from `.github/workflows/e2e-tests-wp-nightly.yml`
  * Add a build matrix to the workflow. See [GitHub Docs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)
  * Build matrix should container `WP_VERSION` and `AMP_VERSION` as dimensions
  * Replace all occurencies of `WP_VERSION` and `AMP_VERSION` with the matrix variables according to GitHub Docs.
  * Rename the job to `e2e-tests`.
  * Rename the job name to use the matrix variables.
  * Currently with WordPress Version 5.2 we use `AMP_VERSION` `1.5.5`. Use the `include` setting from workflow matrix configuration only test WordPress version `5.2` with AMP version `1.5.5`.
  * Use and empty string as default `AMP_VERSION`. This ensures, the latest version gets installed.
  * Change the name of the concurrency group to `e2e-tests-${{ github.ref }}`
  * Change the paths from `.github/workflows/e2e-tests-wp-nightly.yml` to `.github/workflows/e2e-tests.yml` for `push` and `pull_request`.
  * Delete all other existing `.github/workflows/e2e-tests-*` files.
* Verify e2e and unit tests run for the same WordPress versions as before.

### Test Coverage

* No tests must be added. Verify all tests run as before.

## QA Brief

* No plugin QA needed; if E2E tests are passing all is good. Code Reviewer should verify all tests are still being run as before.

## Changelog entry

* N/A

**Comment by FlicHollis** [comment]
Hi @aaemnnosttv if you are not actively working on this, please could you un-assign yourself so someone else can pick up? Thanks!

**Comment by tofumatt** [comment]
ACs are good here, moving to IB 👍🏻

**Comment by aaemnnosttv** [comment]
> * Rename the job to `php-tests`.
> * Rename the job to `e2e-tests`.

@derweili One more thing to keep in mind regarding the renaming of these workflows is that each one has a reference to itself under `(push|pull_request).paths` so that it will run anytime its workflow file is changed. This might not be obvious when copying over the content but the path referenced there should be updated.

> * Use `trunk` as default `AMP_VERSION`.

@derweili a few things to note here:
- We only test with published releases of the AMP plugin, whereas `trunk` could install a pre-release version
- The setup script will install the proper 2.x version if a specific version is not provided, so the default should be an empty string https://github.com/google/site-kit-wp/blob/69bb5836de3048df0b25d95143a625625c440c84/bin/local-env/install-wordpress.sh#L110-L118

Otherwise this LGTM 👍

**Comment by derweili** [comment]
@aaemnnosttv updated as suggested. I also added an change to the concurrency group name and an update to the `Run Unit Tests` step which should conditional run the the `composer test:multisite` command.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
No additional QA to do here. Will look over again before closing – moving to Approval.
