### ISSUE TITLE
Implement GA events for zero states

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5042]
A few additional GA events for new areas from the `zeroDataStates` epic should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Both the "gathering data" and "zero data" banner notifications should fire GA tracking events for certain interactions (via `ZeroDataStateNotifications`):
    * Any of the events below should use a category depending on which of the two notifications is shown:
        * If the `gathering-data-notification` is shown, the category needs to be `{viewContext}_gathering-data-notification`.
        * If the `zero-data-notification` is shown, the category needs to be `{viewContext}_zero-data-notification`.
    * When the respective notification is shown (i.e. `useMount`), a `view_notification` event should be fired.
    * When the respective dismiss button is clicked, a `dismiss_notification` event should be fired.
    * When the learn more button is clicked (only relevant for `zero-data-notification`), a `click_learn_more_link` event should be fired.
* Two GA tracking events for the new `CreateGoalCTA` component should be added:
    * Both of the events should use `{viewContext}_search-traffic-widget` as category.
    * When the component is shown (i.e. `useMount`), a `view_analytics_goal_cta` event should be fired.
    * When the user clicks the support link "Create a new goal", a `click_analytics_goal_cta` event should be fired.

## Implementation Brief

**Note:** The banner notification events implementation would benefit from building out the two notifications as their own components and keeping the current `ZeroDataStateNotifications` component only as a wrapper for alternatively displaying one of them.

* Using `assets/js/components/notifications/BannerNotification/index.js`,
	* Add a new prop `onView` which will be a function called within the `useMount` hook if defined.
* Rename and move `assets/js/components/notifications/ZeroDataStateNotifications.js` to `assets/js/components/notifications/ZeroDataStateNotifications/index.js`. This includes `ZeroDataStateNotifications.stories.js` as well.
* Create `assets/js/components/notifications/ZeroDataStateNotifications/GatheringDataNotification.js` which exports the `GatheringDataNotification` functional component.
	* It should render the same `BannerNotification` from `index.js` having `gathering-data-notification` as `id`.
	* It should accept a `title` prop which will be used as value for the `title` prop of `BannerNotification`.
	* Category for event tracking should be: `{viewContext}_gathering-data-notification`.
	* Add the following props to `BannerNotification`:
		* `onView`: callback function should call `trackEvent` with event action set to `view_notification`.
		* `onDismiss`: Callback function should call `trackEvent` with event action set to `dismiss_notification`.
* Create `assets/js/components/notifications/ZeroDataStateNotifications/ZeroDataNotification.js` which exports the `ZeroDataNotification` functional component.
	* It should render the same `BannerNotification` from `index.js` having `zero-data-notification` as `id`.
	* Category for event tracking should be: `{viewContext}_zero-data-notification`.
	* Add the following props to `BannerNotification`:
		* `onView`: callback function should call `trackEvent` with event action set to `view_notification`.
		* `onDismiss`: Callback function should call `trackEvent` with event action set to `dismiss_notification`.
		* `onLearnMoreClick`: Callback function should call `trackEvent` with event action set to `click_learn_more_link`.
* For the above new components,
	* Import the `trackEvent` function from `assets/js/util/tracking/index.js`.
	* Get the context by using the `useContext` hook with `ViewContextContext` as parameter. `ViewContextContext` imported from `assets/js/components/Root/ViewContextContext.js`.
* Using `assets/js/components/notifications/ZeroDataStateNotifications/index.js`,
	* Replace the `gathering-data-notification` banner notification with the new `GatheringDataNotification` component, passing the `gatheringDataTitle` as value to the `title` prop.
	* Replace the `zero-data-notification` banner notification with the new `ZeroDataNotification` component.
	* Tweak the code to return early when we return `GatheringDataNotification`, thus avoiding the conditions to display `ZeroDataNotification`.
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/CreateGoalCTA.js`,
	* Import `trackEvent` and get the context as per the above.
	* The event category should be `{viewContext}_search-traffic-widget` for all `trackEvent` calls.
	* Using the `useMount` hook, call `trackEvent` with event action set to `view_analytics_goal_cta`.
	* Add the `onClick` prop to the `Button` component and callback function should call `trackEvent` with event action set to `click_analytics_goal_cta`.

### Test Coverage
* No new tests to be added.

## QA Brief
* Ensure the GA events are fired as per the AC when the gathering data and zero data notifications are rendered.
* Ensure GA events are fired as per the AC for the CreateGoalCTA

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 @FlicHollis This needs to be part of the zero data states launch, so I've added the sprint and release as needed. It should be a quite small issue though. We can remove something from dashboard sharing if necessary.

**Comment by asvinb** [comment]
@felixarntz Instead of breaking the two components on their own, I think maybe we can just add a new prop (`onMount`) to `BannerNotification`, which will be run within the `useMount` hook. Thus we can add any tracking event calls to the callback function. What do you think?

**Comment by felixarntz** [comment]
@asvinb That's a good idea, however I'd say regardless of that it still makes sense to break them into separate components. The two broken down components would be purely UI components which would make them standalone and for example also help with showing them in Storybook. The overarching component has the logic for which one to display - also including the UI for _both_ versions in there is a bit messy. By breaking down we can avoid a bunch of all the additional if statements.

With that said, I'm on board with something like `onMount`. However, I'd prefer we call this prop `onView`, as that clarifies the purpose, `onMount` would be about a React "technical detail". For example, we may at some point find a better way to implement these "on view" callbacks to make them more reliable, and maybe that implementation wouldn't use `useMount`. So let's preferably use a prop name that describes the purpose, less the implementation.

Let me know your thoughts on these.

**Comment by asvinb** [comment]
@felixarntz Totally makes sense! I've updated the IB, can you take another look?

Thanks!

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_Tested on the main and entity dashboard_

When the `gathering-data-notification` is shown, the category is `{viewContext}_gathering-data-notification`.
When the zero-data-notification is shown, the category is `{viewContext}_zero-data-notification`.
When the respective notification is shown (i.e. useMount), a `view_notification` event is fired.
When the respective dismiss button is clicked, a `dismiss_notification` event is fired.
When the learn more button is clicked, a `click_learn_more_link` event is fired.

_Tested on main dashboard_

Two GA tracking events for the new `CreateGoalCTA` component are added:
The events use `{viewContext}_search-traffic-widget` as category.
When the component is shown (i.e. useMount), a `view_analytics_goal_cta` event is fired.
When the user clicks the support link "Create a new goal", a `click_analytics_goal_cta` event is fired.
