### ISSUE TITLE
Remove hard-coded view context references in favor of `useViewContext()`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5043]
Follow-up to #4814 (however unrelated to the dashboard sharing epic): We should eliminate all remaining references to hard-coded view contexts in components in favor of relying on `useViewContext()`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No production code components (other than the entry components that pass it to `Root`) should use any `VIEW_CONTEXT_*` constant anymore, but instead rely on the view context received from `useViewContext()`.
    * A (non-exhaustive) list of view context accesses in components still present are `VIEW_CONTEXT_DASHBOARD_SPLASH`, `VIEW_CONTEXT_ACTIVATION`, `VIEW_CONTEXT_SETTINGS`, `VIEW_CONTEXT_ADMIN_BAR`, ...

## Implementation Brief

* Once the PR for #5011 has been merged and we have access to the `useViewContext` hook, replace the direct hard-coded imports of `VIEW_CONTEXT_*` in the following files/components and use the hook instead. 
    * `VIEW_CONTEXT_ACTIVATION`
        * `assets/js/components/activation/activation-app.js`
    * `VIEW_CONTEXT_ADMIN_BAR`
        * `assets/js/components/adminbar/AdminBarApp.js`
    * `VIEW_CONTEXT_DASHBOARD_SPLASH`
        * `assets/js/components/setup/SetupUsingProxy.js`
        * **Note:** `SetupUsingGCP` can not be fixed in this one, as it's a class component. 
    * `VIEW_CONTEXT_SETTINGS`
        * `assets/js/components/settings/SetupModule.js`
        * `assets/js/components/settings/SettingsActiveModule/ConfirmDisconnect.js`
        * `assets/js/components/settings/SettingsActiveModule/Footer.js`
        * `assets/js/components/settings/SettingsActiveModule/Header.js`
* For reference here's an example on how to update the components:
````js
import useViewContext from '../../hooks/useViewContext';

function SetupUsingProxy() {
    ....
    const viewContext = useViewContext();
    ....
    const onButtonClick = useCallback( async ( event ) => {
        ....
        if ( proxySetupURL ) {
            await trackEvent( viewContext, 'start_user_setup', 'proxy' );
        }
        ....
    }, [ viewContext, ...] );
} 
````

### Test Coverage

* Update any failing tests. 

## QA Brief

* Ensure event tracking is enabled during setup and set up a new Site Kit site. Using the Google Analytics testing browser extension, ensure the "category" of the `trackEvent` call is:
  * `"settings_module-list"` when performing actions like disconnecting a module on the Settings page.
  * `"splash"` when performing actions during setup
  * `"adminBar"` when performing actions related to the Admin Bar

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
I just noticed this was added to Sprint 74… but it's blocked by #5011, which hasn't been started yet. I'm going to swap this one out of this sprint in favour of #5011, because this issue depends on it.

That said, if we can get to this one in time we should add it back to the sprint 🙂

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@tofumatt I am not seeing:

`"settings"` when performing actions like disconnecting a module on the Settings page.
`"activation"` when viewing the "Congrats, Site Kit is now activated" message after Site Kit initial setup.

I am able to see the splash and adminBar. 

I have tested this on two new test sites. 

Any ideas why this could be?   

**Verified:**

- The "splash" category appears when performing actions during setup.   

![image](https://user-images.githubusercontent.com/73545194/168582973-5a5d176b-0c5c-4cf5-8225-1166652a2891.png)

- The "adminBar" category when performing actions related to the Admin Bar

![image](https://user-images.githubusercontent.com/73545194/168585238-152cf7ee-4d35-4026-a90c-f00e675a7fe6.png)

**Comment by tofumatt** [comment]
@wpdarren There's a nearly immediate navigation after clicking on the buttons that activate those `trackEvent` calls, so you might miss them after the browser redirects. 🤔 

Are you seeing _any_ events? Eg. are the categories for the events not matching the QA Brief? If they aren't matching something is wrong, but you might not be able to see the names if you don't prevent redirects or something after clicking the buttons that cause the trackEvent calls to be made.

You could try using a proxy like Proxyman to see if any calls are made to Analytics with those arguments are made? 🤷🏻‍♂️

**Comment by wpdarren** [comment]
@tofumatt I am using the Google Analytics debugger chrome extension and I can see `splash` and `adminBar` as per the QAB, but not seeing anything for `settings` and `activation` when running through those actions.   I have it set to preserve log so the issue with redirects should not be an issue.  I have just set up a new test site and still are not seeing anything in the log for these two categories.

**Comment by tofumatt** [comment]
@wpdarren I used the debugger on the latest `develop` and saw the settings module events when clicking around the settings and specifically the deactivation event mentioned in the QA brief:

![CleanShot 2022-05-17 at 20 56 15](https://user-images.githubusercontent.com/90871/168899197-4464ab17-46c7-441b-aa4b-56648b287b7d.gif)

Looks like the activation notifications appear with the context of the notification they're in so I've actually removed that bit from the QA brief, though they do seem to be working.

But as seen from the above video these events are dispatching. Can you check again @wpdarren?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@tofumatt Ah, I was looking for `settings` in the log, but yes, I can see settings_module-list. 👍 

**Verified:**

- The "splash" category appears when performing actions during setup.   

![image](https://user-images.githubusercontent.com/73545194/168582973-5a5d176b-0c5c-4cf5-8225-1166652a2891.png)

- The "adminBar" category appears when performing actions related to the Admin Bar

![image](https://user-images.githubusercontent.com/73545194/168585238-152cf7ee-4d35-4026-a90c-f00e675a7fe6.png)

- The `settings_module-list` category appears when disabling a module or clicking around the settings. 

![image](https://user-images.githubusercontent.com/73545194/168941451-0647e2a9-b702-42a2-928f-0b7200061a40.png)
