### ISSUE TITLE
Show Analytics `useSnippet` toggle when creating a new UA/GA4 property

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5045]
#4913 shows the Analytics `useSnippet` toggle under any relevant property dropdowns when there is an existing tag. One place where the toggle however isn't shown is the notice that a corresponding new property (UA or GA4) will be created. We need to provide the same toggle contextually in that case as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**Relying on the `feature/existing-tag-simplification` branch:**

* In the Analytics setup flow, if one of the two blue notices that a corresponding new UA or GA4 property will also be created is shown _and_ if there is an existing tag of that respective type (UA or GA4), the message in the notice should be accompanied with the exact same Analytics snippet toggle that was already added to the setup UI via #4913. In other words:
    * The notice about a new GA4 property being created should show the toggle for the `analytics-4` `useSnippet` setting _if_ there is an existing GA4 snippet.
        * The toggle in that case would for sure be on by default (via the `useExistingTagEffect()`), since a new property would certainly not have the same measurement ID as the existing tag.
    * The notice about a new UA property being created should show the toggle for the `analytics` `useSnippet` setting _if_ there is an existing UA snippet.
        * The toggle in that case would for sure be on by default (via the `useExistingTagEffect()`), since a new property would certainly not have the same property ID as the existing tag.

## Implementation Brief

**Any PR for this must be based on and target the `feature/existing-tag-simplification` branch.**

### SetupFormGA4
- In `assets/js/modules/analytics/components/setup/SetupFormGA4.js`:
    - If the existing GA4 tag is available, render the `SetupUseSnippetSwitch` component as a `children` prop within the `GA4PropertyNotice` component.

### SetupFormUA
- In `assets/js/modules/analytics/components/setup/SetupFormUA.js`:
    - If the existing UA tag is available, render the `SetupUseSnippetSwitch` component as a `children` prop within the `GA4PropertyNotice` component.

- Ensure the `With Existing Tag` story in `SetupFormGA4` and `SetupFormUA` satisfies the AC.

### Test Coverage

- No new tests are to be added. VRTs may need updating.

## QA Brief

- Manually add GA4 and UA tags in the `header.php`
- Setup Analytics with an account that has GA4 property only.
- Ensure the toggle snippet for the UA property is rendered in the blue `Notice` box.
- Ensure the newly added story `modules-analytics-setup-setupformga4--with-both-tags` satisfies the above.
- Setup Analytics with an account that has UA property only.
- Ensure the toggle snippet for the GA4 property is rendered in the blue `Notice` box.
- Ensure the newly added story `modules-analytics-setup-setupformua--with-both-tags` satisfies the above.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When GA4 and UA tags are in header.php and and when a Analytics account that has GA4 property only is selected, the toggle snippet for the UA property is rendered in the blue Notice box. I can also confirm that the newly added story `modules-analytics-setup-setupformga4--with-both-tags` behave the same as above. 

![image](https://user-images.githubusercontent.com/73545194/164425168-bc3450cc-5899-4836-b0d8-a041622eb3fd.png)

- When GA4 and UA tags are in header.php and and when a Analytics account that has UA property only is selected, the toggle snippet for the GA4 property is rendered in the blue Notice box. I can also confirm that the newly added story `modules-analytics-setup-setupformga4--with-both-tags` behave the same as above. 

![image](https://user-images.githubusercontent.com/73545194/164425243-6ec9e895-9913-46d9-86a4-327b45b95e74.png)

QA note: Wanted to mention that in the Site Kit settings, there's an outstanding issue where the Existing tag notices are not appearing. I flagged that in [this issue](https://github.com/google/site-kit-wp/issues/5046)
