### ISSUE TITLE
Update AdSense account statuses based on new API capabilities

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5051]
Based on the recently released new AdSense API capabilities and the [corresponding enhancements to the design doc](https://docs.google.com/document/d/1vNpMW4iED2scWOjpF8SKGoM8z6GUjX-WbhMpmAKeieo/edit#heading=h.dvwukljp9z7x), some of the account statuses we need to support needs to be tweaked. This is essentially a follow-up to #4755.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense account status constants should be tweaked as follows:
    * The `ACCOUNT_STATUS_APPROVED` status should be moved to the group of "V1 setup flow" constants, as going forward it will be replaced with a new `ACCOUNT_STATUS_READY` (value: "ready"). The latter should be added to the "V2 setup flow" group accordingly.
    * The `ACCOUNT_STATUS_PENDING_TASKS` status should be entirely replaced (not moved!) with a new `ACCOUNT_STATUS_NEEDS_ATTENTION` (value: "needs-attention").
        * Any of its usages in the codebase should then obviously be updated accordingly.
    * The following additional account statuses should be added to the "V2 setup flow" group:
        * `ACCOUNT_STATUS_CLIENT_REQUIRES_REVIEW` (value: "client-requires-review")
        * `ACCOUNT_STATUS_CLIENT_GETTING_READY` (value: "client-getting-ready")
* All usages of `ACCOUNT_STATUS_APPROVED` **in the V2 components** should be replaced with using `ACCOUNT_STATUS_READY` instead.
* Any potential references to the changed statuses in V2 Storybook should also be updated.

## Implementation Brief
* Using `assets/js/modules/adsense/util/status.js`, update the statuses as per the AC.
* Update the use of `ACCOUNT_STATUS_PENDING_TASKS` by `ACCOUNT_STATUS_NEEDS_ATTENTION` across the codebase. At the time of writing, `assets/js/modules/adsense/components/setup/v2/SetupAccount.js` is the only file that needs to be updated.
* Update the use of `ACCOUNT_STATUS_APPROVED` by `ACCOUNT_STATUS_READY` within files in `assets/js/modules/adsense/components/setup/v2` and stories if need to be.

### Test Coverage
* No new tests to be added.

## QA Brief
* Ensure the stories under AdSense -> Components -> Setup -> v2 -> SetupMain render correctly.
* Ensure the above constants were added.

## Changelog entry

* Update AdSense V2 code constants to use new API capabilities.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by asvinb** [comment]
@wpdarren That is correct. Those are only placeholders for now till we actually build the UI for them.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

I have gone through Storybook and confirmed placeholders for the components in the AC. The ticket has been labelled QA:Eng thought because in the AC it says `Any of its usages in the codebase should then obviously be updated accordingly.`

**Comment by hussain-t** [comment]
## QA Verified ✅ 

- Verified the stories under AdSense -> Components -> Setup -> v2 -> SetupMain render correctly.
- Verified the constants were added/removed as per the AC.
