### ISSUE TITLE
Set faker.seed() in Jest tests to make random values consistent

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#5053]
## Bug Description

Turns out our tests that rely on random characters have the potential to create duplicate keys and cause test failures! 😅 

<img width="1007" alt="CleanShot 2022-04-07 at 22 12 23" src="https://user-images.githubusercontent.com/90871/162312271-e19ababf-9489-40c2-920d-28fa16b408c2.png">

Reproducing this is very difficult, but we had a Jest test failure from duplicate keys here: https://github.com/google/site-kit-wp/runs/5867951906?check_suite_focus=true, caused by the code here generating the same key for two items: https://github.com/google/site-kit-wp/blob/fffd5e06fc348c4c6b8f0fcc824fe5512010d5a9/assets/js/modules/tagmanager/datastore/__factories__/builders.js#L77

We should set a consistent `faker.seed()` value before all tests for their "random" values don't change between tests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tests relying on faker data should output random, but predictable results for each test run. Essentially, a snapshot run with faker data should be the same across tests. Essentially, we should set a `faker.seed()` value for every Jest test.

## Implementation Brief

* Add:

```js
beforeEach(() => {
  faker.seed(500);
});
```

to our `tests/js/setup-before-after.js` file.

### Test Coverage

* None needed, though we _could_ add a snapshot test of random data to ensure it's consistent between tests.

## QA Brief

* A snapshot test that uses random data should pass after being run multiple times.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by techanvil** [comment]
## QA :white_check_mark: 

- Ran the ["fake data generation" snapshot test](https://github.com/google/site-kit-wp/blob/07bdf1e4783006b33d85e66700fc63095a32fd51/assets/js/fake-data.test.js#L25) 100 times (using a bash loop, see below), all passed.

```bash
for i in {1..100}; do
  if npm run test:js assets/js/fake-data.test.js > /dev/null 2>&1                                
    then echo success
    else echo fail
  fi
done
```
