### ISSUE TITLE
Data Format on Graphs are different between All Traffic widget and other widgets

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5060]
## Bug Description

A UI question: Is there a reason why we have two different data formats on the graphs on All Traffic widget and other widgets on the dashboard.  Is it better to have them consistent?  Not sure why this only just jumped out at me, but thought I would check. Personally, I find the format on the All Traffic widget easier to read because the others are in a US date format. 

![image](https://user-images.githubusercontent.com/73545194/162442141-fd8209a9-dc24-42a7-ac1b-ea9a6200d5fd.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The date format in all Site Kit graphs should be updated to use the `MMM d` format on the horizontal axis, similar to the `UserCountGraph` in the All Traffic Widget. E.g. Nov 1, Apr 3, Aug 31
* The graphs that should be updated are:
    * All the 4 graphs within the Search Funnel widget (Search traffic over the last N days) on both, the main and entity dashboards.
    * All the 4 graphs within the AdSense Module Overview widget (Performance over the last N days).

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@sigal-teller Not urgent at all, but assigning this over to you for a look when you get a moment. This issue is over a year old, so want to confirm if this is still the case and if so, if and how it should be fixed. Thanks!

**Comment by sigal-teller** [comment]
@wpdarren @bethanylang I'm not sure as this was created before I started but if I need to guess then this isn't intentionally inconsistent. Looking at the sources shows that search console uses the numbers format and GA uses the month name format, so they are probably pulled as they are without any manipulation. In any case if we're using the numbers format I would remove the year, as in the US format the day is in the middle and very hard to notice at a glimpse. 
I agree that the month in text format (the GA format) is easier to read and also overcomes the difference in formatting between US and other users. I would wait for @marrrmarrr just to make sure that I'm not missing anything that I'm not aware of here.

**Comment by marrrmarrr** [comment]
I think generally having the month + day would be ok, except for the case where the data spans a transition b/w two years, then we need a way to indicate that e.g. 2023 ended and 2024 started. 
SC shows the full date (with year) so they have no issue with that, but GA does something weird: 
![image](https://github.com/google/site-kit-wp/assets/13304791/af1f57ff-2513-4941-a7e8-4e066186619b)

@sigal-teller if we transitioned the entire dashboard to the month+day format, what options might we consider for the year transition case?

**Comment by sigal-teller** [comment]
@marrrmarrr As mentioned in this slack [thread](https://10up.slack.com/archives/C01CA828ZPZ/p1701020980747539) I also think that the date format of Month shortcut + DD will be the best option here. I don't think we should specify the year, even in case when the year is transitioning. For example, if we see DEC 22 and then JAN 13 the year transition is quite clear. We can add another tick only when a new year starts but I don't think it's necessary. 
Also, keep in mind that when hovering the chart, the bubble show the full date including the year.

**Comment by techanvil** [comment]
Hey @jimmymadon, thanks for updating the AC here, however we already have this covered by https://github.com/google/site-kit-wp/issues/5830 in the EB so I'm closing this off as a duplicate.
