### ISSUE TITLE
Update language in `AdSenseConnectCTA`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5061]
## Feature Description

The AdSense connection CTA on the unified dashboard references the original name ("Revenue") of what is now referred to as the _Monetization_ section of the dashboard. This should be updated to reflect the current name.

![image](https://user-images.githubusercontent.com/1621608/162492224-5938b034-4f08-4095-af44-15fa46b74b00.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `AdSenseConnectCTA` should be updated to refer to the "Monetization" section by the current name rather than "Revenue"

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/5062

### Test Coverage

* No changes necessary

## QA Brief

* Once merged, the change should be observable in Storybook here: https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-adsense-widgets-adsenseconnectcta--ready

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB / CR ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that the `AdSenseConnectCTA` is updated to refer to the "Monetization" section by the current name.

![image](https://user-images.githubusercontent.com/73545194/162648022-6ceff18a-daf1-4b99-a071-de26a587353d.png)
