### ISSUE TITLE
Unified dashboard nav - tour guide content change

### ISSUE THREAD

**Issue by Pratheep-lab** [google/site-kit-wp#5070]
In the latest release that included the unified dashboard feature, we have some tour guides that introduces the new top unified navigation. 

One of the tour guides, shown in the below screenshot,  refers anchor links as 'tabs'. 
<img width="1283" alt="UnifiedNav_Tourguide_QA" src="https://user-images.githubusercontent.com/81642523/162771688-77eb6c02-eec0-4712-95b4-646f18b2d80f.png">

This need to be changed as it might create a tab 'mental model' for those who read this. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The string `New! Navigate your dashboard easily with the dashboard tabs` should be changed to just `New! Navigate your dashboard easily` (removing `with the dashboard tabs`).

## Implementation Brief

* Make string change based on ACs.

### Test Coverage

* N/A

## QA Brief

* According to AC the updated copy should appear on dashboard nav - tour guide.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@marrrmarrr The UI here ended up being "pills", not "tabs". Do you have a suggestion how to update the copy here?

**Comment by Pratheep-lab** [comment]
"jump links" or "section jump links" can be used to instead of "tabs". Although some users might not understand what a jump link is but that should be okay I believe. 

> _New! Navigate your dashboard easily with the section jump links_

**Comment by marrrmarrr** [comment]
@felixarntz @Pratheep-lab  I'd suggest removing "with the dashboard tabs" altogether. this will help with the heading length as well.

**Comment by Pratheep-lab** [comment]
SGTM!

**Comment by felixarntz** [comment]
@aaemnnosttv Went ahead with what we talked about today and added an "IB" 😄

**Comment by aaemnnosttv** [comment]
IB ✅ 😄

**Comment by eclarke1** [comment]
Changing estimate to a 3 as we do not have 1's

**Comment by aaemnnosttv** [comment]
@eclarke1 while we avoid using 1 estimates, it's my understanding that they're not forbidden; if any issue qualifies for a 1, this would be one of them as it's about the smallest possible change that could be made (removing a few words in one place).

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@sashadoes 

- Verified this on dev branch using tester plugin.
- Unified dashboard nav- tour guide content changed as per AC

> The string` New! Navigate your dashboard easily with the dashboard tabs `should be changed to just `New! Navigate your dashboard easily` (removing with the dashboard tabs).

Issue > But I've noticed that if any banner is showing, then navigation tour focus is not correct. Should I create a separate issue for this ?

cc @asvinb 

![image](https://user-images.githubusercontent.com/94359491/192294369-cdd233a9-1a15-49a8-881e-a49dbccad825.png)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified this on dev branch using tester plugin.
- Unified dashboard nav- tour guide content changed as per AC.

For the issue reported [here](https://github.com/google/site-kit-wp/issues/5070#issuecomment-1258078635) . I'll create a separate ticket. 


![image](https://user-images.githubusercontent.com/94359491/192296982-9edc5881-0fc9-41c3-af41-65d2ffd9ef40.png)

**Comment by aaemnnosttv** [comment]
@mohitwp did you create an issue for the quirk you flagged above? That would be good to fix in the future. Otherwise this LGTM!
