### ISSUE TITLE
Remote user surveys no longer triggering since 1.71.0

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5073]
## Bug Description

User surveys for viewing the dashboard are no longer triggering, as I've noticed today. After some digging, it looks like this is due to #4806, which means this broke in 1.71.0.

The problem is the following: The `triggerSurvey` action now calls the `isAuthenticated` selector and bails if it is false-y. However, on page load that selector (as all our API-driven selectors) can be `undefined`, and this action call basically happens on page load, so in this case the `triggerSurvey` function bails just because the value for the selector isn't loaded yet.

This is a critical bug so we need to fix it asap and get it into the upcoming 1.72.0 release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User surveys should only not be triggered via `triggerSurvey` if the user is not authenticated. Currently the action also bails when that selector's value is `undefined`, i.e. not loaded yet.
* We need to ensure the value is loaded at the point that the action accesses it.

## Implementation Brief

**The PR should be based on `main`.**

* Replace the current approach (checking for any false-y value in `select( CORE_USER ).isAuthenticated()`, which will always return `undefined` at first, with an action to await for the value returned after the resolver has run.
* Essentially, replace https://github.com/google/site-kit-wp/blob/f05f66155e0d6d429ee3a4025fb24fd6aaacb366/assets/js/googlesitekit/datastore/user/surveys.js#L105-L109 with:

```js
const {
	__experimentalResolveSelect,
	select,
} = yield Data.commonActions.getRegistry();

yield Data.commonActions.await(
	__experimentalResolveSelect( CORE_USER ).getAuthentication()
);

if ( select( CORE_USER ).isAuthenticated() === false ) {
	return {};
}
```

### Test Coverage

* A data store test to ensure the result is returned would be a good starting-point safeguard here.

## QA Brief

* Ensure the `google-site-kit/v1/core/user/data/survey-trigger` request is made when viewing the SK dashboard
* Session storage may need to be cleared for it to be triggered again

## Changelog entry

* Fix bug where user surveys would not trigger when viewing the dashboard.

**Comment by tofumatt** [comment]
Marking as a 7 because of the tests involved but that might be overdoing it, especially if we want to add tests after-the-fact to get this out in the release.

**Comment by aaemnnosttv** [comment]
> ```js
> yield yield Data.commonActions.await(
> 	__experimentalResolveSelect( CORE_USER ).isAuthenticated()
> );
> ```


@tofumatt resolve select only works on selectors that have a resolver, so this would require selecting `getAuthentication` rather than `isAuthenticated`. (also there is a double `yield` there but I assume that's just a typo 😄 )

Otherwise LGTM – I'll update this detail in the IB and then this will be good to go 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@tofumatt @aaemnnosttv @felixarntz I have sent this to approved, but am I assuming correctly that it only gets triggered on the main dashboard. I don't see it getting requested on the entity dashboard, so wanted to check. 

**Verified:**

- The `google-site-kit/v1/core/user/data/survey-trigger` request is made when viewing the SK dashboard

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/162868203-598a3d36-2d44-4ef4-8660-eccaaf219e68.png)
![image](https://user-images.githubusercontent.com/73545194/162868218-f7c8aaf1-a9c5-4fd6-81f8-620b2bba007e.png)

</details>

**Comment by tofumatt** [comment]
Yeah, from the code we've only ever triggered it in the main dashboard app and never the entity dashboard:

* https://github.com/google/site-kit-wp/blob/f05f66155e0d6d429ee3a4025fb24fd6aaacb366/assets/js/components/DashboardMainApp.js#L135
* https://github.com/google/site-kit-wp/blob/f05f66155e0d6d429ee3a4025fb24fd6aaacb366/assets/js/components/dashboard/DashboardApp.js#L50

<img width="289" alt="CleanShot 2022-04-12 at 11 15 08" src="https://user-images.githubusercontent.com/90871/162938456-e966ad44-78ea-4ba9-9524-4e9835c76329.png">

Looks like that was seemingly the intent: https://github.com/google/site-kit-wp/issues/4786.

I guess maybe we only want surveys on the landing page? 🤷🏻‍♂️ But I think it'd be okay to add them to the entity dashboard in the future as a separate issue. What do you think @felixarntz?

**Comment by felixarntz** [comment]
@tofumatt Let's keep the `view_dashboard` surveys only in the main dashboard. It may be a nice idea to add a different `SurveyViewTrigger` with an ID like `view_entity_dashboard` for the entity dashboard though, which would allow us to send surveys specific to the entity dashboard at any time.

This issue is good to go now.
