### ISSUE TITLE
Change Learn more link in Not enough traffic notification

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5077]
## Description

In #4963, we set the Learn more link on the Not enough traffic to display stats notification to go to https://sitekit.withgoogle.com/documentation/using-site-kit/dashboard-data-display/. However, we have a new guide that has been created since then that would be a better place to put details about the new data states.

Please change the Learn more link to go to https://sitekit.withgoogle.com/documentation/using-site-kit/using-the-site-kit-dashboard/#not-enough-traffic. Note that this will currently 404 but documentation will be published prior to feature launch.

## Screenshots

<img width="885" alt="image" src="https://user-images.githubusercontent.com/12189958/162970064-087c2aea-1c59-4870-a24a-3f43b3a1592b.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any links in the plugin pointing to `https://sitekit.withgoogle.com/documentation/using-site-kit/dashboard-data-display/` should be changed to point to `https://sitekit.withgoogle.com/documentation/using-site-kit/using-the-site-kit-dashboard/#not-enough-traffic` instead.

## Implementation Brief

* In `assets/js/components/notifications/ZeroDataStateNotifications.js`:
    * Update the `learnMoreURL` value of  the second `BannerNotification` element to be the Updated URL from the AC. 

### Test Coverage

* N/A

## QA Brief

* With `zeroDataState` feature flag enabled on a zero data site, make sure the `Learn More` link points to the updated URL in the AC. 

## Changelog entry

* Update the `Learn More` link to point to the new documentation page.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by smamun19** [comment]
Can I work on this? :)

**Comment by kuasha420** [comment]
@smamun19 Generally we encourage first time contributor to work on something that is not a `P0` but since this one is fairly trivial feel free to create a PR for it. See https://github.com/google/site-kit-wp/blob/develop/CONTRIBUTING.md for details. 

Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

With zeroDataState feature flag enabled on a zero data site, the Learn More link points to the updated URL of `https://sitekit.withgoogle.com/documentation/using-site-kit/using-the-site-kit-dashboard/#not-enough-traffic`
