### ISSUE TITLE
Investigate GA4 API to see if it's possible to automatically connect GA4 property to UA property

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#5082]
## Feature Description

Currently, Site Kit does not automatically connect a GA4 property to UA property when that GA4 property has been created through the plugin. This has to be done manually using the Google Analytics 4 Property Setup Assistant which can be found in your Analytics account by going to **Admin > select your account & UA property > GA4 Setup Assistant**. 

Connecting your GA4 property this way allows users to make use of different tools outlined [here](https://support.google.com/analytics/answer/10110290). When creating a GA4 property through SK, this isn't connected automatically and needs to be manually done on the Analytics account as seen in the recording below. 

https://user-images.githubusercontent.com/91896826/163198286-5504686c-8cf3-46db-bfc1-fffc705e0749.mp4

I believe that this has been an API limitation in the past but could we investigate this once more to see if this can be triggered from the Site Kit side.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by locksmithunit** [comment]
Nice bro :)
but really, i don't think its a big issue, you can put pop up in the plugin for the client, to make sure he will connect them throw Analytics. But you must notify your clients.

It can be a cool feature, not going to lie…
But information to the client beforehand can save you the problem.

**Comment by jamesozzie** [comment]
This would be a useful addition. From some [internal testing](https://app.asana.com/0/1185360131189553/1202063303823594/f) it looks like a site could have double GA4 tags tracking at present, by following the steps below:

1. Connect a UA property with a GA4 property from analytics.google.com
2. Setup Site Kit
3. When connecting the Analytics module, select a different GA4 property to that which was connected to the UA property
4. Check your site on [tagassistant.google.com](https://tagassistant.google.com). You'll notice two different GA4 properties are receiving data (1 - The property associated with the UA property at analytics.google.com level and 2 - the property selected within Site Kit). The property GA4 connected at analytics.google.com level won't appear visible when checking a sites source code

**Comment by bethanylang** [comment]
Thanks for taking a look, @jamesozzie.

Unfortunately, we've looked into this further and discovered that this remains a limitation with the Analytics API, so it's not something that we're able to implement. It seems highly unlikely that this will be added to the API given the fact that UA is being retired in 2023.

I'll close this issue for now, but @locksmithunit please do contact us on the forums if you have any other questions. Thanks!
