### ISSUE TITLE
Feature Request: Detect existing Analytics to prevent accidental duplicate tag insertion

### ISSUE THREAD

**Issue by JayHoltslander** [google/site-kit-wp#5085]
## Feature Description

The plugin should detect if Google Analytics is already present on the website already and NOT insert Google Analytics tag code if so. Doubling up the analytics code can **really** mess up stats.

This should include if the existing Google Analytics tag is being inserted via Google Tag Manager.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Hi there @JayHoltslander,

During Analytics setup within the plugin at present the plugin does perform a check for any existing Google Analytics snippets. If it detects such a snippet already exists, it will automatically use that snippet, and not place it's own snippet. It won't allow users to insert a different snippet via the plugin. 

![image](https://user-images.githubusercontent.com/41326532/163388451-ed81d5ed-86ad-4a4c-8327-8e0b0dcdaae2.png)

In your case if site Kit is allowing you to place a secondary snippet despite a snippet already existing it's possible an additional snippet may have been placed after setting up Site Kit, via other means. It's also possible that somehow Site Kit didn't detect an existing snippet, something which is possible if an Analytics tag was added via Google Tag Manager and that Google Tag Manager container was added manually (and not via using the Site Kit Tag Manager module), see https://github.com/google/site-kit-wp/issues/4103 for more information on this. 

If you would like us to investigate your case specifically we'd be happy to do so if you want to [open a WordPress support forum topic](https://wordpress.org/support/plugin/google-site-kit/#new-post), where we can investigate this further. Should we determine a bug or improvement to the plugin we can revisit this GitHub issue from there. 

Note also that there are plans to allow users to choose what action to take when it's determined there is an existing snippet placed (https://github.com/google/site-kit-wp/issues/4448). 

I'll close this GitHub issue now however we can troubleshoot or investigate your case from a WordPress support forum topic.

**Comment by JayHoltslander** [comment]
> It's also possible that somehow Site Kit didn't detect an existing snippet, something which is possible if an Analytics tag was added via Google Tag Manager and that Google Tag Manager container was added manually (and not via using the Site Kit Tag Manager module)

Confirming that this is the case. Existing Analytics were within GTM and GTM snippet was added manually to site pre-Sitekit plugin install.
