### ISSUE TITLE
Don't fail build when eslint errors in development

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#509]
## Feature Description

Currently the build is set to fail when `eslint` errors: https://github.com/google/site-kit-wp/blob/9dda58ba62183695a35016f8bfd1b0d9bec4c508/webpack.config.js#L150. This is a good idea for _production_ builds, but when in development this is quite inconvenient; it means the gold standard for debugging, `console.log`, will cause the build to error and stop working:

<img width="938" alt="Screenshot 2019-09-09 20 20 11" src="https://user-images.githubusercontent.com/90871/64559899-3d846d00-d33f-11e9-89e0-ccb7af7fd48d.png">

This causes any code updates after the failed `eslint` run not to appear when the page is refreshed.

### Proposal

We should only enable `failOnError` when building for production (or disable it when `npm run watch` or `npm run dev` are called). This will allow developers to console log code or add temporary code that fails `eslint` without needing to add ignore comments or fix temporary code. This is especially true for quickly-inserted, temporary statements that lack proper whitespace but are not auto-formatted because we don't use prettier (which we should).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The JS build process should not fail from `eslint` issues during development.

## Implementation Brief

* Remove the `failOnError` line from the `eslint-loader` webpack plugin (or change it to be explicitly `false`.
* Add a check during the build step (for test/production builds) that `eslint` does not fail, instead of having the webpack build fail—this is the more common scenario for projects using Webpack + ESLint in my experience and better separates the concerns.

## Changelog entry

*

**Comment by swissspidy** [comment]
IB and estimate look good 👍

**Comment by adamsilverstein** [comment]
This passes QA in my testing, moving to Approval.

### Testing procedure

* Remove a semicolon in a JS file to introduce a linting error.
* Run `npm run build` - note error shows, build fails to complete.
* Run `npm run dev` - note linting error, however build completes.
* Run `npm run watch` - note linting error, however build completes and watching works as expected. Fixing the introduced error the linting automatically reruns with no error.
