### ISSUE TITLE
Analytics settings requested on every dashboard page load when not active

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5091]
## Bug Description

Currently when visiting the main dashboard when Analytics is not active, an additional request is being made to the server for the module's settings. This is due to settings only being preloaded for active modules, and is coming from the search funnel widget's `Footer` which includes selects for Analytics deep links. This in turn uses selects internally for the various IDs needed to construct the service URL which triggers the settings to be fetched. Normally this happens the same way when Analytics is active, it's only that the settings are preloaded so it wouldn't result in an actual request to the server when selected on load.

## Steps to reproduce

1. Visit the SK dashboard with Analytics inactive
2. See a network request to `google-site-kit/v1/modules/analytics/data/settings`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics settings should not be requested from the server when viewing the dashboard when the module is inactive

## Implementation Brief

* Split the `Footer` component of the Search Funnel widget into separate inner components for Analytics and Search Console. Only render one or the other (as today) based on the `service` identified by the selected metric. This fixes the problem by only running the selectors needed for the specific URL we're generating, rather than always generating all URLs.
* Finish? and merge #5093 

### Test Coverage

* No new/updated coverage needed

## QA Brief

* Loading the SK dashboard should never trigger a network request for Analytics settings (or any module's settings for that matter)

## Changelog entry

* Avoid an unnecessary network request for Analytics settings on the Site Kit dashboard when Analytics is not active.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
I believe this issue is responsible for some instability in E2E as well:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1621608/165399455-c7bf6f76-12e6-41dd-a84b-86e139a461fd.png">

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Confirmed the issue as reported to see the network request `google-site-kit/v1/modules/analytics/data/settings`
- Loading the SK dashboard does not trigger a network request for any module's settings. 
- Disconnected Analytics, AdSense and PageSpeed and made sure no request was made. 
- Tested this on the main and entity dashboard. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/165774550-6b801e10-59d8-47af-8b6c-c64371ece890.png)
![image](https://user-images.githubusercontent.com/73545194/165774573-43d2858b-0565-430c-b261-86b6afea8db5.png)

</details>
