### ISSUE TITLE
Checking GA & AdSense Exisiting Tag with Fetch instead of Iframe

### ISSUE THREAD

**Issue by ivankristianto** [google/site-kit-wp#51]
**Describe the bug**
The current implementation to check existing tag from the js client is with iframe. And the iframe has sandboxed mode, thus it will block script execution, and thown console log error. Even it is an expected behavior, it cause confusion.

**To Reproduce**
1. Activate and Authenticate Site Kit
2. Activate Analytics Service
3. Go to Site Kit > Settings
4. See error in console log.

**Expected behavior**
No console log error thrown.

**Screenshots**
![Screen Shot 2019-06-25 at 10 46 24](https://user-images.githubusercontent.com/656006/60067869-84969500-9736-11e9-82f4-a18671dbe9d5.png)

**System Information (please complete the following information):**
 - PHP Version: 7.2.14
 - OS: Mac OSX
 - Browser: Opera 60
 - Plugin Version: 1.0.0-beta.1 develop branch
 - Device: Macbook Pro

**Technical Implementation Brief**
Instead of using iframe to grab the html of the frontend site. 
We can dynamically fetch the frontend page. 
Also use timestamp when do request, for example: `https://<domain>/?tagverify=1&source=sitekit&timestamp=123456777`, so we won't hit the page cache.
Store the html content in `sessionStorage` for future use.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* Replace usage of an iframe to detect existing Analytics or AdSense tags with a fetch request.

## Acceptance criteria

* On a fresh setup, set up the Analytics module. Ensure that you can choose the property and that the snippet is placed on the site after completion.
* Do the same test for AdSense.
* Disconnect both modules again (or restart with a fresh setup).
* Insert an Analytics snippet and an AdSense snippet into the site through another means (e.g. manually, or 3P plugin).
* Start Analytics module setup again. Ensure the existing tag is detected (and thus you're locked to using that).
* Do the same test for AdSense.
* Remove the custom snippets placed manually before again.
* Go to Analytics settings and click "Edit". Make sure it no longer includes references to the already existing tag.

**Comment by circlecube** [comment]
I've been able to QA only the analytics account setup and module and all passes. 

Not able to get into an adsense account for now, but will update again once I have.

**Comment by circlecube** [comment]
Assigned this to @adamsilverstein to QA the adsense parts.

**Comment by adamsilverstein** [comment]
Both AdSense and Analytics tag detection worked as expected in my testing. I manually added/changed the tags on my site before clearing caches and going thru the flow each time.

I tested with analytics and adsense with a matching and non matching ID

Moving to Approval.

**Comment by marrrmarrr** [comment]
LGTM for Analytics. @OisinOConnor will review for AdSense next week post-release.
