### ISSUE TITLE
Add Tag Manager GA event for modifying tag placement

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5102]
Similar to how the Analytics `UseSnippetSwitch` fires a GA event when changing the setting, the Tag Manager `UseSnippetSwitch` should do that too.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Tag Manager `UseSnippetSwitch` component should fire a GA event when changing the setting, similarly to how it is present in the Analytics `UseSnippetSwitch` component:
    * Event name: `enable_tag` or `disable_tag`, depending on what the setting is changed to
    * Event category: `{ $viewContext }_tagmanager`
    * No event label should be used.

## Implementation Brief

* In `assets/js/modules/tagmanager/components/common/UseSnippetSwitch.js`
    * Get the current `viewContext` using the `useContext` hook and `ViewContextContext`.
    * Import `trackEvent` from `assets/js/util`
    * in the `onChange` callback, call `trackEvent` with the category (first param) and and event (second param) from the AC.
        * Event will be based on the new value of `useSnippet` ie. `! useSnippet ? 'enable_tag' : 'disable_tag'`

### Test Coverage

* 

## QA Brief

* Install and Enable Google Analytics Debugger Extension. 
* Disconnect and Setup Tag Manager Module.
    * See that the correct trackEvent for  Use Snippet Toggle is firing with right event name and category and it matches AC. 
       * Make sure the `enable_tag` and `disable_tag` is fired correctly depending on Toggle State. 
* Visit Tag Manager Settings and also make sure that track events for Use Snippet Toggle are firing there as well. 
* **NOTE:** The toggle will only be shown on Setup page on `feature/existing-tag-simplification` branch. So wait for `develop` to be merged to the feature branch before testing. 

## Changelog entry

* Track a Google Analytics event when toggling the Tag Manager snippet placement. Props to @smamun19 for this one!

**Comment by eugene-manuilov** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The correct `trackEvent` for Use Snippet Toggle is firing with right event name and category and it matches AC.
- The `enable_tag` and `disable_tag` is fired correctly depending on Toggle State.
- The track events for Use Snippet Toggle are firing in Site Kit Settings for Tag Manager.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/165130582-628e32af-b54d-4b48-863b-4eacea72344b.png)
![image](https://user-images.githubusercontent.com/73545194/165130569-8044779c-d9d4-4709-afe9-d67f667faa20.png)
![image](https://user-images.githubusercontent.com/73545194/165130600-f7ea7778-0f61-4171-8daa-68cafdba853b.png)
![image](https://user-images.githubusercontent.com/73545194/165130623-d0d9a8e7-edc8-4cf9-b7b9-ad4b8ec58d60.png)

</details>
