### ISSUE TITLE
Support PageSpeed Insights transition to using OAuth

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#511]
Addressed by PR #607 

---

The PageSpeed Insights API is moving away from using API keys, which comes in quite handy for us actually. This issue is about making the necessary changes ahead of time so we can switch as soon as we need to. Depending on when exactly the new version of the API goes live, we may need to do that in a "hot fix" release.

Here's the necessary changes:
* Request `openid` scope (_not_ prefixed with `www.googleapis.com...`). This can be part of the `OAuth_Client` class itself since the scope is not only associated with PSI.
    * Because it's not prefixed, we should change the scope validation in the `OAuth_Client` class, so that everything prefixed passes (as it does already), but also [these three specific scopes without prefix](https://developers.google.com/identity/protocols/googlescopes#google_sign-in).
* Make `PageSpeed_Insights` module class use the regular OAuth client instead of a custom client using an API key.
* Remove API key step required to setup PSI module, and make it a "setup-less" module (except for the OAuth scope being required which should already be the case).
* Remove API key infrastructure, including PHP class, the field being exposed in settings, and all consuming code.

The API itself will not change, so it won't move from a v5 to v6 or anything.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Connection to PageSpeed Insights API should continue to work after it switches to requiring OAuth2.
**Note:** This can only be tested after it goes live. Implementation should happen based on the above guidance, in advance (without merging though).

## Implementation Brief

* Update `OAuth_Client` to include `openid` in the default required scopes
* Update `PageSpeed_Insights` module
    - Use `OAuth_Client` in all places instead of `API_Key_Client`
* Remove classes/methods and related tests
    - `\Google\Site_Kit\Core\Authentication\API_Key`
    - `\Google\Site_Kit\Core\Authentication\Clients\API_Key_Client`
    - `\Google\Site_Kit\Core\Authentication\Authentication::get_api_key_client`
    - `core/site/data/apikey` Rest route
    - `<PageSpeedInsightsSetup>` and references to it
        - `googlesitekit.PageSpeedInsightsModuleSetupWizard`
* Update auth scope handling to allow for a whitelist of scopes that do not match `https://www.googleapis.com/auth/*` - should cover `profile`, `email`, `openid` (only the latter is actually used by this issue)
    - `Module_With_Scopes_ContractTests`
    - `\Google\Site_Kit\Core\Authentication\Clients\OAuth_Client::authorize_user`

## Changelog entry

*

**Comment by felixarntz** [comment]
@tofumatt 
> * Update `PageSpeed_Insights` module
>     - Use `Module_With_Scopes` trait
>         - Requires only `openid` scope

Note that the scope should be part of the client, not the module, as mentioned above, because it is a generic scope. If it is part of the module, we unnecessarily require an extra OAuth redirect for the user.

**Comment by aaemnnosttv** [comment]
> Note that the scope should be handled in OAuth_Client, not the module, as mentioned above, because it is a generic scope. 

My mistake. IB updated!

**Comment by felixarntz** [comment]
IB ✅ 

Made one minor change: I replaced

> currently only `openid` but could be more later perhaps

with

> should cover `profile`, `email`, `openid` (only the latter is actually used by this issue)

**Comment by aaemnnosttv** [comment]
@felixarntz assigning this one to you for now and moving to blocked. It requires a bit more detail regarding how the new module activation flow will look and work. See #607

**Comment by felixarntz** [comment]
@aaemnnosttv I replied in https://github.com/google/site-kit-wp/pull/607#issuecomment-539026499

There shouldn't be any setup step, going to the dashboard is fine.

**Comment by felixarntz** [comment]
Thanks @lilybonney for changing the labels accordingly.

Let's see if we can merge this for the beta.1.0.8 milestone or not. I haven't heard any update regarding PSI transition, but @aaemnnosttv you reported it apparently _already_ works with just OAuth (and `openid` scope). Let's keep this a priority for this week, but we need to throughly test whether it works before merging. I'll also follow up on our end.

**Comment by aaemnnosttv** [comment]
@felixarntz giving this another few tests locally, I can confirm that it works as-is 👍 

Now that PageSpeed Insights no longer requires any additional scopes of its own, should it be an always on module? It is a bit time-consuming to load the first time but that's just the nature of the statistics that it has to collect. I don't see a reason why it shouldn't be enabled as part of the core services. What do you think?

**Comment by aaemnnosttv** [comment]
I just noticed a bug with this: when activating via _Settings > Connect More Services_ it still goes to the old reauth screen with an empty widget body, instead of redirecting to the dashboard with success message as it does correctly when clicking on the activation CTA.

**Activating via _Settings > Connect More Services_**
![image](https://user-images.githubusercontent.com/1621608/67202095-87697400-f410-11e9-9a56-5a65b0cecfec.png)

**Activating via activation CTA on dashboard**
![image](https://user-images.githubusercontent.com/1621608/67202191-b97ad600-f410-11e9-8fe7-da07b8b76b19.png)

I will work on a PR to fix this now.

**Comment by adamsilverstein** [comment]
I QAed this on the `feature/auth-proxy ` branch. Overall QA passed and I am moving this to "Acceptance". I did notice one bug that deserves a follow up Issue: I am unable to deactivate PSI.

### Testing Procedure
* Build a zip from the `feature/auth-proxy` branch and upload to a new `https://jurassic.ninja/` site.
* activate the module from the CTA on the dashboard 
* Note everything worked well, data began flowing
* Delete plugin & start over, this time activating from the Settings screen.


Note: I am unable to deactivate the PSI module - it is behaving the the (required) Search console module which cannot be deactivated. I should be able to deactivate PSI, however on the settings screen there is no "Edit" link that would normally enable deactivating:

![image](https://user-images.githubusercontent.com/2676022/67236680-f9d55680-f406-11e9-82c5-eb6d86df3653.png)

I will open an issue to cover this.

**Comment by adamsilverstein** [comment]
I created this follow up issue to address the "unable to deactivate" issue noted in my QA above: https://github.com/google/site-kit-wp/issues/682

**Comment by PawelKolat** [comment]
Hi guys I usually use the https://www.googleapis.com/auth/ to authenticate. Now trying to integrate with Google PageSpeed Insights I'm struggling to find any info on how to do it. https://developers.google.com/identity/protocols/oauth2/scopes#pagespeedonline only points to OpenId. 
The get started documentation still suggests key is the main way of authorising. 
https://developers.google.com/speed/docs/insights/v5/get-started 
Could you clarify if the best way would be to use OpenId and provide a how to for PageSpeed Insight setup.

Many thanks
