### ISSUE TITLE
Extract new global for tracking configuration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5117]
## Feature Description

Initially, custom metadata used for Site Kit's custom dimensions when tracking internal events all came from the `_googlesitekitBaseData` global which is loaded across all wp-admin (for users that can use Site Kit).

As this has evolved, it now includes data from other globals which include additional data that we wouldn't want to load everywhere. Similarly, there is some data within the base global which is only used for tracking that we don't need globally either.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `googlesitekit-tracking-data` Script Data Asset should be registered which populates a new `_googlesitekitTrackingData` global
	* The data object should contain all of the properties sourced from base and user globals by `trackEvent`
	* Any properties which are only used for tracking may be removed from their previous objects (e.g. `userIDHash`), properties with existing non-tracking uses should be duplicated (e.g. `referenceSiteURL`)
* The new data asset should be added to the top-level list of `$dependencies` used by all SK screens in `Assets`
* The tracking configuration in `assets/js/util/tracking/index.js` should be updated to source the tracking configuration values from the new tracking-specific global only
	* The one exception to this is `GOOGLESITEKIT_VERSION` which is an injected top-level global

## Implementation Brief

- In `includes/Core/Assets/Assets.php`, `get_assets()` method:
  * Add `googlesitekit-tracking-data` to the top of the `$dependencies` array list.
  * Add a `new Script_Data()` with the `handle` of `googlesitekit-tracking-data` and global of `_googlesitekitTrackingData`.
  * In the `data_callback` make a call to a new method `$this->get_inline_tracking_data` which contains following properties sourced from the base and user globals by `trackEvent`:
    * `referenceSiteURL`,
    * `userIDHash`,
  * The `get_inline_tracking_data` method should return `apply_filters( 'googlesitekit_inline_tracking_data', $inline_data )`.
  * Remove the `userIDHash` property from the `get_inline_base_data()` method.
- In `includes/Core/Authentication/Authentication.php`, add a private method `inline_js_tracking_data` with the following:
  * Should receive `$data` param
  * The `isAuthenticated` property gets data from `is_authenticated()` method.
  * The `userRoles` property gets data from `wp_get_current_user()->roles` method.
  * Return the `$data`.
  * In the `register` method add a `apply_filter()` with
    ```php
    add_filter( 'googlesitekit_inline_tracking_data', $this->get_method_proxy( 'inline_js_tracking_data' ) );
    ```
- In `includes/Core/Tracking/Tracking.php`:
    * Rename the `inline_js_base_data` method to `inline_js_tracking_data`.
    * In the `register` method replace the `apply_filter()` with
    ```php
    add_filter( 'googlesitekit_inline_tracking_data', $this->get_method_proxy( 'inline_js_tracking_data' ) );
    ```
- In `includes/Core/Modules/Modules.php`, add `apply_filter()` for `googlesitekit_inline_tracking_data` similar to `googlesitekit_inline_base_data`. See:
https://github.com/google/site-kit-wp/blob/fd56e5f5fb38b18afe98828d7473e3d13c1905da/includes/Core/Modules/Modules.php#L339-L355
- Consider creating a private method `inline_js_tracking_active_modules` to reuse in both the hooks.

- In `assets/js/util/tracking/index.js`:
  * Use `global._googlesitekitTrackingData` to destructure the events instead of `global._googlesitekitBaseData`.
- In `.storybook/utils/resetGlobals.js`, add all the `trackEvent` properties under `global._googlesitekitTrackingData = {}`.
- Remove the properties we are removing from the `global._googlesitekitBaseData` object.

### Test Coverage

- No new tests are to be added.

## QA Brief

* This issue modifies the internal code which fetches data that is passed to GA events as dimension1 to dimension7. Thus, they should be tested using the GA Debugger. Verify these dimensions are populated as before and are not changed in any way.

### QA Eng

* Verify a new global window._googlesitekitTrackingData is populated as per the AC.

## Changelog entry

* Move tracking related data into its own global `_googlesitekitTrackingData` variable.

**Comment by eugene-manuilov** [comment]
> * In the `data_callback` make a call to a new method `$this->get_inline_tracking_data` which contains all of the properties sourced from the base and user globals by `trackEvent`.

@hussain-t could you please list all properties that are needed in the new tracking config and how to get them in PHP.

> Remove the following properties from the `get_inline_base_data()` method:
> * `userIDHash`, `assetsURL`, `blogPrefix`, `isNetworkMode`, and `webStoriesActive`.

Why do we need to remove `assetsURL` and `webStoriesActive` properties from the base data object? What we need to remove from the base data is the `isSiteKitScreen` property.

Also I think we need to move `trackingID` and `trackingEnabled` properties to the new tracking data object, remove them from the base data object and update all usage of these properties to rely on the tracking data object.

**Comment by hussain-t** [comment]
Thanks, @eugene-manuilov. I have updated the IB.

**Comment by eugene-manuilov** [comment]
Very nice. Thanks, @hussain-t. IB ✔️

**Comment by jimmymadon** [comment]
@wpdarren Testing 3-5 events should be sufficient as if it works for a few, it should work for all.

**Comment by wpdarren** [comment]
Thanks @jimmymadon 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified 5-6 events. Compared both latest and develop branch events. Dimensions are populating as before.

Note : Added label `QA: Eng` as mentioned in QAB.

<details>

![image](https://user-images.githubusercontent.com/94359491/175866738-631317a1-6b0c-4cc2-80fb-4a5391541071.png)

![image](https://user-images.githubusercontent.com/94359491/175866761-76ab32b3-b69b-4a05-b6a7-d541704ff8fc.png)

![image](https://user-images.githubusercontent.com/94359491/175866785-655749dc-b64a-4dbe-82b6-9d6e43863dd6.png)

![image](https://user-images.githubusercontent.com/94359491/175866811-d2e9a4db-a065-4997-9abd-91bb064c7984.png)

**Comment by nfmohit** [comment]
## QA ✅

`QA:Eng:`
- Verified that the global `window._googlesitekitTrackingData` is populated as per the AC.
![image](https://user-images.githubusercontent.com/20284937/175881212-45cc5d8d-e581-4467-baf8-0b05d2a9ba20.png)
