### ISSUE TITLE
Expose owned module settings to client

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5121]
## Feature Description

With the behavioral changes coming to settings edit interfaces in #4825, it will be necessary to identify which settings are owned and particularly when they have changed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `haveSettingsChanged` selector in `createSettingsStore` should be updated to accept an optional `keys` parameter (`string[]`)
	* If passed, the selector should return its result based on a subset of settings identified by the given list of keys
	* If not passed, it should continue to work as today (comparing the full object of settings)
* `createModuleStore` should be updated to accept an optional `ownedSettingsSlugs` argument (`string[]`) which should default to an empty array
* A new `haveOwnedSettingsChanged` selector should be generated in the resulting store definition which uses `haveSettingsChanged` internally; returning `true` if any owned setting has changed, otherwise `false`
	* If the module has no owned settings, this should always return `false`
* Module store definitions on the client should be updated to register their owned settings (see `Setting_With_Owned_Keys_Interface`)

## Implementation Brief

In `assets/js/googlesitekit/data/create-settings-store.js`:

- Add `keys` parameter to the `haveSettingsChanged` selector as per the AC.

In `assets/js/googlesitekit/modules/create-module-store.js`:

- Add optional `ownedSettingsSlugs` argument to `createModuleStore` and create the `haveOwnedSettingsChanged` selector in the resulting store definition as per the AC.
  - In the implementation of `haveOwnedSettingsChanged`:
    - If `ownedSettingsSlugs` was passed to `createModuleStore` call `haveSettingsChanged( ownedSettingsSlugs )` to check if the owned settings have changed.
    - Otherwise, return `false`.

For each PHP Module that implements `Setting_With_Owned_Keys_Interface`, review the list of keys in the module's implementation of `get_owned_keys` and update the corresponding JS-side call to `Modules.createModuleStore`, passing the list of owned keys in as `ownedSettingsSlugs`.

- AdSense:
  - PHP: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/includes/Modules/AdSense/Settings.php#L137-L142
  - JS: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/assets/js/modules/adsense/datastore/base.js
- Analytics:
  - https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/includes/Modules/Analytics/Settings.php#L161-L168
  - https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/assets/js/modules/analytics/datastore/base.js
- Analytics GA4:
  - PHP: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/includes/Modules/Analytics_4/Settings.php#L47-L56
  - JS: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/assets/js/modules/analytics-4/datastore/base.js
- Optimize:
  - PHP: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/includes/Modules/Optimize/Settings.php#L73-L77
  - JS: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/assets/js/modules/optimize/datastore/base.js
- Search Console:
  - PHP: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/includes/Modules/Search_Console/Settings.php#L71-L75
  - JS: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/assets/js/modules/search-console/datastore/base.js
- Subscribe With Google:
  - PHP: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/includes/Modules/Subscribe_With_Google/Settings.php#L47-L53
  - JS: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/assets/js/modules/subscribe-with-google/datastore/base.js
- Tag Manager:
  - PHP: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/includes/Modules/Tag_Manager/Settings.php#L57-L65
  - JS: https://github.com/google/site-kit-wp/blob/068e497a157c4b49f905fbb52b5f4dbf4689a91c/assets/js/modules/tagmanager/datastore/base.js

### Test Coverage

* Add tests for the new `haveSettingsChanged` selector, and update tests for `createModuleStore` to reflect the new behaviour.
* Fix any failing tests.

## QA Brief

* Setup each module in Site Kit and modify settings; they should continue to work as-normal. No changes should be noticed as part of this change to the behaviour of saving settings, disconnecting/reconnecting modules and their settings, etc.

## Changelog entry

* Expose owned module settings to client.

**Comment by eugene-manuilov** [comment]
> The `haveSettingsChanged` selector in `createSettingsStore` should be updated to accept an optional `keys` parameter (`string[]`)
> * If passed, the selector should return its result based on a subset of settings identified by the given list of keys
> * If not passed, it should continue to work as today (comparing the full object of settings)

@aaemnnosttv we already have the `haveSettingChanged` selector in `createSettingsStore`. Maybe we shouldn't change the `haveSettingsChanged` selector and just use multiple `haveSettingChanged` calls in the `haveOwnedSettingsChanged` selector?

https://github.com/google/site-kit-wp/blob/00a2fdf067e3931df0ba20a20f7df3ff1f8789a1/assets/js/googlesitekit/data/create-settings-store.js#L297-L307

**Comment by eugene-manuilov** [comment]
> * Add optional `ownedSettingsSlugs` argument to `createModuleStore` and, if provided, create the `haveOwnedSettingsChanged` selector in the resulting store definition as per the AC.

@techanvil @aaemnnosttv I think the `haveOwnedSettingsChanged` selector should be created regardless the module has owned settings or not. If it has those slugs, we will check whether those settings have been changed or not. If the module doesn't have owned settings, then we should return `false` and that's it. It will help us avoid a need to check whether a module has that selector. What do you think?

**Comment by techanvil** [comment]
Hey @eugene-manuilov, you've raised interesting points there. I'd certainly agree on the second, it would provide a more consistent API to always create `haveOwnedSettingsChanged` and should simplify logic for the caller as well, with it always returning `false` where there are no owned settings.

As for the first point (nb - slight typo in your comment, `haveSettingChanged` should be `hasSettingChanged`) - it's certainly a valid suggestion. I'm quite comfortable with the current AC for `haveSettingsChanged` but don't hold a strong opinion on this one.

@aaemnnosttv, how do you feel about the proposed changes?

**Comment by aaemnnosttv** [comment]
> @aaemnnosttv we already have the `haveSettingChanged` selector in `createSettingsStore`. Maybe we shouldn't change the `haveSettingsChanged` selector and just use multiple `haveSettingChanged` calls in the `haveOwnedSettingsChanged` selector?

I think if this were implemented elsewhere (e.g. in a component) that would make more sense.  However, since we're at the selector level with access to `state` it's simpler (and probably more efficient) to leverage a more flexible `haveSettingChanged` selector that is capable of operating on a subset.

> I think the `haveOwnedSettingsChanged` selector should be created regardless the module has owned settings or not. If it has those slugs, we will check whether those settings have been changed or not. If the module doesn't have owned settings, then we should return `false` and that's it. It will help us avoid a need to check whether a module has that selector. What do you think?

Yes, better 👍

I've updated the ACs accordingly. Thanks

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- Tested this with Dashboard Sharing feature flag enabled and disabled.
_(not sure if that matters but wasn't mentioned in the QAB, so didn't want to take any risks 😄)_

- Setup each module in Site Kit and modified settings; they continue to work as-normal. 
- No changes on the behaviour of saving settings
- Disconnecting/reconnecting modules worked as expected.
- Checked Admin settings to make sure they functioned as expected.
