### ISSUE TITLE
Secondary AMP UX/UI issues with Tag Manager 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5132]
## Bug Description

While testing #5044 I discovered a few issues with Secondary AMP and Tag Manager. 

1. This first issue I think is not working as expected based on my testing on Primary AMP.  I have an existing tag, and when setting up tag manager, the message appears `An existing tag GTM-PDXBRTT was found on the page. If you prefer to collect data using that existing tag, please select the corresponding account and property above.` which is expected.  When I select the Account, Web and AMP container for `GTM-PDXBRTT` the snippet toggle doesn't disable.  It does for primary AMP.  

I am assuming it should disable?  Here's a screencast.

https://user-images.githubusercontent.com/73545194/165334830-336a6c05-9ae3-4fd5-9560-4ec80b56cc05.mp4

2. In the scenario above, I saw a message in settings `An existing tag was found on your site (GTM-PDXBRTT). If you later decide to replace this tag, Site Kit can place the new tag for you. Make sure you remove the old tag first.` This is expected.  When I edit the settings though there is no message notifying me that I have an existing tag. 

See screenshot below.

3. On the same settings screen the message above the tag manager Account, Web and AMP container says `You can change these later in your settings.` and we are already on the settings page. 

**Update:** This isn't just an AMP issue, it also appears with just a web container. 

![image](https://user-images.githubusercontent.com/73545194/165336492-fb56aaee-8515-47cc-966c-7292f2869659.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
> 1. When I select the Account, Web and AMP container for `GTM-PDXBRTT` the snippet toggle doesn't disable.  It does for primary AMP.

@wpdarren I think this may be expected in secondary AMP because we don't have separate toggles for controlling the web and AMP container snippets independently. Containers are web/amp-specific so toggling them both off would result in one of them not loading if indeed there was only an existing tag for one of them (we only detect a single existing tag at the moment rather than all which is a problem here too).

For GTM specifically, I have tested this in the past and it doesn't result in duplicate loading for a container that is tagged more than once (you're welcome to test this as well to confirm) so it shouldn't really be an issue.

**Comment by aaemnnosttv** [comment]
@wpdarren following up here:

1. Snippet toggles do not switch off when an existing tag is detected that matches the selected container: this is expected as mentioned above
1. "When I edit the settings though there is no message notifying me that I have an existing tag" : this seems to have been already addressed. See https://google.github.io/site-kit-wp/storybook/develop/?path=/story/tag-manager-module-settings--edit-with-all-settings-with-existing-tag
2. "You can change these later in your settings." when already on the settings page: this has also been fixed already it seems :)

Closing this one out as everything appears to already be addressed 👍
