### ISSUE TITLE
Adjust functionality around modules with service entities

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5144]
## Feature Description

This is a follow-up issue to apply a few tweaks to functionality for modules that have service entities.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Optimize module should no longer implement the `Module_With_Service_Entity` interface as it is a special case which isn't necessary
* The core modules `check-access` REST handler should be updated to return an error if called for a module that does not implement the `Module_With_Service_Entity` interface
	* Status: `400`
	* code: `invalid_module`
	* message: `Module access cannot be checked`
* Tag Manager should be updated to implement the `Module_With_Service_Entity` interface
	* Access should be `true` if all configured containers are present in the response from `GET:containers`
		* If the site is using AMP, ensure the user has access to both web and amp containers otherwise just the main (web) container

## Implementation Brief

* In `Google\Site_Kit\Core\Modules\Modules` class: 
    * In the callback function of `core/modules/data/check-access` route:
        * Return early with an appropriately formatted `WP_Error` if `$module` is not an instance of `Module_With_Service_Entity`.
        * ie. `return new WP_Error( 'invalid_module', __( 'Module access cannot be checked.', 'google-site-kit' ), array( 'status' => 400 ) );`
* In `Google\Site_Kit\Modules\Tag_Manager` module:
    * Implement `Module_With_Service_Entity` interface. 
    * Create `check_service_entity_access` public method.
        * Get all the `$containers` for the current user using `GET:containers` datapoint or it's underlying implementation. 
        * If `$this->context->is_amp()` is `true`:
            * if both `$settings['containerID']` and $settings['ampContainerID'] are present in `$containers` list, return `true`. 
            * Otherwise return `false`
        * Otherwise (`$this->context->is_amp()` is `false`)
            * if `$settings['containerID']` is present in `$containers` list, return `true`. 
            * Otherwise return `false`
* In `Google\Site_Kit\Modules\Optimize` module:
    * Remove `Module_With_Service_Entity` interface and it's implementations.
        * Remove `check_service_entity_access` method. 
* From `OptimizeTest`:
    * Remove usage of `Module_With_Service_Entity_ContractTests` and related methods.
        * Remove `get_module_with_service_entity`, `test_check_service_entity_access_no_access` and `test_check_service_entity_access_error` methods. 

### Test Coverage

* Add tests for `Tag_Manager::check_service_entity_access` to the `Tag_ManagerTest` using the `Module_With_Service_Entity_ContractTests` trait.
* Fix any failing tests. 

## QA Brief

We can not QA the specific changes in Regular QA flow yet. 

### QA:Eng

1. Connect Optimize and Tag Manager Module 
2. Check that calling `check-access` endpoint with `JSON.stringify( { data: { slug: "optimize" } } )` fails with the `invalid_module` error from the AC since Optimize is not a module with service entity. 
3. Check the same endpoint with `JSON.stringify( { data: { slug: "tagmanager" } } )`  in both AMP and non-AMP mode and see that the access is `true`.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
### QA:Eng Verified ✅ 

- Verified calling the `check-access` endpoint with `JSON.stringify( { data: { slug: "optimize" } } )` fails with the `invalid_module` error.

![Screenshot 2022-06-07 at 2 58 56 PM](https://user-images.githubusercontent.com/24408261/172346794-1d0eadb4-ca00-47d8-a453-bef7c6f6172f.png)

- Verified the same endpoint with `JSON.stringify( { data: { slug: "tagmanager" } } )` in both AMP and non-AMP mode with the response `{access: true}`

![Screenshot 2022-06-07 at 2 59 09 PM](https://user-images.githubusercontent.com/24408261/172353640-31f07678-ab6f-4fdc-b557-274e566380dd.png)
