### ISSUE TITLE
Google Analytics stopped recording data after SiteKit activation

### ISSUE THREAD

**Issue by RealBenihime** [google/site-kit-wp#515]
## Bug Description

I think the title explains what issue I'm facing. I've used Sitekit on 3 out of +40 of my websites.
And on all 3 sites, Google Analytics Dashboard shows that 0 page views after I started using Sitekit. And now I have to explain to the bosses why for the past 28 days the sites recorded 0 PageViews. 

## Steps to reproduce

1. Install, Activate and Link Sitekit plugin to G Analytics account
2. Wait a day or 2
3. Check Google Analytics Dashboard (in my case, PageViews)
4. See error  (0 PageViews recorded, during the waited period)

## Screenshots

[Annotation-2019-09-11-101345.jpg](https://coh.ukzn.ac.za/wp-content/uploads/2019/09/Annotation-2019-09-11-101345.jpg)

## Additional Context
Due to above mentioned bug, I've uninstalled SiteKit and therefore will not appear on the list of installed plugins

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Ubuntu)
	MySQL version: (Ubuntu) v5.5.62
	PHP Version: 7.2.19-0ubuntu0.18.04.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: https://coh.ukzn.ac.za
	Home URL: https://coh.ukzn.ac.za
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 2
	Debug Mode: Active

== Theme ==
	Name: UKZN SubSite Child
	Version: 2.0
	Author: Sibongiseni Msomi
	Child Theme: Yes
	Parent Theme Name: UKZN SubSite
	Parent Theme Version: 1.0
	Parent Theme Author: Media Platform

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

== Active Plugins ==
	Analytify - Google Analytics Dashboard
		Version: 2.2.13
		Author: Analytify

	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	Custom Post Type Permalinks
		Version: 3.3.1
		Author: Toro_Unit

	Ele Custom Skin
		Version: 1.2.5
		Author: Dudaster.com

	Elementor
		Version: 2.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.5
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 3.2.1
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 3.2.0
		Author: WPDeveloper

	Livemesh Addons for Elementor
		Version: 2.8
		Author: Livemesh

	ManageWP - Worker
		Version: 4.9.1
		Author: GoDaddy

	Max Mega Menu
		Version: 2.7.2
		Author: megamenu.com

	Memphis Documents Library
		Version: 3.9.20
		Author: Ian Howatson

	Modern Events Calendar Lite
		Version: 4.5.0
		Author: Webnus Team

	Pods - Custom Content Types and Fields
		Version: 2.7.15
		Author: Pods Framework Team

	Premium Addons for Elementor
		Version: 3.7.0
		Author: Leap13

	Premium Addons PRO
		Version: 1.6.8
		Author: Leap13

	Redirection
		Version: 4.3.3
		Author: John Godley

	Smart Slider 3 Pro
		Version: 3.3.20
		Author: Nextend

	Smush
		Version: 3.2.4
		Author: WPMU DEV

	Wordfence Security
		Version: 7.4.0
		Author: Wordfence

	WP Fastest Cache
		Version: 0.8.9.7
		Author: Emre Vona

	WP News and Scrolling Widgets Pro
		Version: 1.2
		Author: WP Online Support

	Yoast SEO
		Version: 12.0
		Author: Team Yoast

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@RealBenihime Are you using the free version of [Analytify - Google Analytics Dashboard](https://wordpress.org/plugins/wp-analytify/)? Let me know and I can check from my side.

Also you can login to your Analytics dashboard to check any analytics statistics if you are encountering any problems with the Site Kit dashboard (or any other dashboards that link to your Analytics property).

**Comment by jamesozzie** [comment]
@RealBenihime I will close this issue as I didn't receive a response. If you are encountering the same issue feel free to reopen.
