### ISSUE TITLE
E2E jobs sometimes cancelled before finishing

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5152]
## Bug Description

Lately some E2E jobs are getting cancelled due to exceeding the maximum time limit for the workflow of 20 minutes:

![image](https://user-images.githubusercontent.com/1621608/165971511-a6b34dde-78bf-479e-b24c-bde65fc345f7.png)
![image](https://user-images.githubusercontent.com/1621608/165971530-a88962d2-6290-4c16-99b0-535292cf05ee.png)

This is intended to kill off zombie jobs that may otherwise run forever, wasting GHA run time. However, this is cancelling successful runs as shown above.

For E2E, we should adjust the total limit for the workflow to allow more time to complete.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The time limit for all E2E GitHub Action workflows should be updated to 30 minutes

## Implementation Brief

* Update timeout on all E2E jobs to 30  
E.g. https://github.com/google/site-kit-wp/blob/9f15b3fad5d4c4865a5b2635e74b01dd0973016c/.github/workflows/e2e-tests-wp-latest.yml#L84

### Test Coverage

* No changes needed

## QA Brief

* See E2E job is no longer cancelled when running longer than 20m 
![image](https://user-images.githubusercontent.com/1621608/165982848-75025214-9499-4dca-8f72-4a91b3f7ae96.png)

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Job no longer cancelled when running longer than 20m 
![image](https://user-images.githubusercontent.com/1621608/165983006-d805db22-6da8-4622-8e62-60a8319c8332.png)
