### ISSUE TITLE
Update and consolidate stories for existing tags 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5155]
## Feature Description

As part of the effort of simplifying cases around the handling of existing tags, we have a number of "duplicate" stories now due to the removal of "access" to a tag as a factor.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following old stories under `Analytics module / Setup` and `Analytics module / Settings` below should be removed  
    ![image](https://user-images.githubusercontent.com/1621608/166342661-45dbf5c2-510c-41e3-b13d-bb7eab8d5bb1.png)
* New stories for existing tags should be created accordingly using the newer CSF format, co-located with their respective components’ `.stories.js`
	- `Modules/Analytics/Setup/SetupFormUA/`:
		- ExistingTag – Existing UA tag, no property selected
	- `Modules/Analytics/Setup/SetupFormGA4/`:
		- ExistingTag – Existing GA4 tag, no property selected
	- `Modules/Analytics/Setup/SetupFormGA4Transitional/`:
		- ExistingTagUA – Existing UA tag, non-matching property selected
		- ExistingTagGA4 – Existing GA4 tag, non-matching property selected
		- ExistingTagUAGA4 – Existing tags, both UA+GA4 matching selected properties
		- ExistingGTMPropertyUANonMatching – GTM (UA) property that does not match the selected UA property ID
		- ExistingGTMPropertyUAMatching – GTM (UA) property that does match the selected UA property ID
	- `Modules/Analytics/Settings/SettingsEdit/`:
		- ExistingTagUA – Existing UA tag, non-matching property selected
		- ExistingTagGA4 – Existing GA4 tag, non-matching property selected
		- ExistingTagUAGA4 – Existing tags, both UA+GA4 matching selected properties
		- ExistingGTMPropertyUANonMatching – GTM (UA) property that does not match the selected UA property ID
		- ExistingGTMPropertyUAMatching – GTM (UA) property that does match the selected UA property ID

## Implementation Brief
* In `stories/module-analytics-setup.stories.js` and `stories/module-analytics-settings.stories.js`, remove the stories mentioned in the AC.
* Using `assets/js/modules/analytics/components/setup/SetupFormUA.stories.js`,
	* add a new story as per the AC for `SetupFormUA` with the setup form in its initial state, i.e no property selected.
		* In order to do so, no account should be selected.
		* The call to set the account, `registry.dispatch( MODULES_ANALYTICS ).selectAccount( accountID );` in the global story decorator might need to be moved to invidual stories where we need to set the account.
* Same points as the above but applied to `SetupFormGA4`.
* For `SetupFormGA4Transitional` and `SettingsEdit`, refer to the old stories in `stories/module-analytics-setup.stories.js` and `stories/module-analytics-settings.stories.js` for the actions to be dispatched in order to recreate the stories.
* Refer to the AC for the story names.

### Test Coverage
* VRT might need to be updated in case they are relying on the old stories.

## QA Brief

Note: Although the IB talks only about _adding_ stories, there are a number of existing stories which cover some or all of the AC and needed to be modified rather than adding new ones. As such, the story names used have been kept consistent with existing stories.

Also, note that it's not technically possible/realistic to implement the proposed **ExistingTag – Existing GA4 tag, no property selected story** so this has not been attempted.

- Check the stories listed to be removed in the AC have been removed.
  - Note that the stories **Edit, with existing tag w/ access** and **Edit, with existing tag w/o access** in `Analytics Module/Settings` were determined to be the equivalent of the listed **Existing Tag w/ access** and **Existing tag w/o access** stories and were deleted.
- Ensure the highlighted stories implement or are updated in line with the AC, notwithstanding the notes above.

![image](https://user-images.githubusercontent.com/18395600/170006038-ef45fbe6-54df-4a36-9b1f-bfe0501fe424.png)

<details>
<summary>
Screenshots for reference:
</summary>

#### `Modules/Analytics/Settings/SettingsEdit`

**With UA Tag, non-matching property selected**
![image](https://user-images.githubusercontent.com/18395600/170007140-9e79397e-71eb-43eb-9ab2-37aa6c5966dd.png)

**With GA4 Tag, non-matching property selected**
![image](https://user-images.githubusercontent.com/18395600/170007186-d64f2b28-218b-46f8-af28-5136e50f7206.png)

**With Both Tags, both UA+GA4 matching selected properties**
![image](https://user-images.githubusercontent.com/18395600/170007251-298b3e89-525e-4d44-8fce-4a61f7d4c6f1.png)

**With GTM (UA) property that does not match the selected UA property ID**
![image](https://user-images.githubusercontent.com/18395600/170007338-0407906f-6bcc-4ab7-aec3-7a18188c5830.png)

**With GTM (UA) property that does match the selected UA property ID**
![image](https://user-images.githubusercontent.com/18395600/170007400-506baefe-fa9f-4d83-b6ae-4f531768f469.png)

#### `Modules/Analytics/Settings/SetupFormGA4Transitional`

**With UA Tag, non-matching property selected**
![image](https://user-images.githubusercontent.com/18395600/170007512-eec14b62-f534-4c33-aced-4ab8b50f5704.png)

**With GA4 Tag, non-matching property selected**
![image](https://user-images.githubusercontent.com/18395600/170007579-f683e24e-3036-4720-b44e-e967474a5867.png)

**With Both Tags, both UA+GA4 matching selected properties**
![image](https://user-images.githubusercontent.com/18395600/170007647-fa6416ba-66b8-4e0b-82d0-c7bb8c0394bf.png)

**With GTM (UA) property that does not match the selected UA property ID**
![image](https://user-images.githubusercontent.com/18395600/170007721-95b80483-ab9b-463b-9d68-fc153d0c7b56.png)

**With GTM (UA) property that does match the selected UA property ID**
![image](https://user-images.githubusercontent.com/18395600/170007796-1098ca6d-ad04-4a76-8b8a-635a03634b18.png)

#### `Modules/Analytics/Settings/SetupFormUA`

**With UA Tag, no property selected**
![image](https://user-images.githubusercontent.com/18395600/170007879-603764c4-9aa8-4695-9a52-30cd87318ca4.png)

</details>

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz sounds good, how about now?

**Comment by felixarntz** [comment]
@aaemnnosttv LGTM!

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA update ⚠️ 

@techanvil @aaemnnosttv 
 **Question 1** : I found an additional story in AC which screenshots and details are not mentioned in QAB.  Is the story "`With GA4 tag , non matching property selected`" and story mentioned below are same ?

- `Modules/Analytics/Setup/SetupFormGA4/`:
		- ExistingTag – Existing GA4 tag, no property selected

**Storybook Screenshot :**

![image](https://user-images.githubusercontent.com/94359491/173763853-9db74b26-51ea-4d0f-b78e-3f5f636ec6d7.png)

https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-setup-setupformga4--with-ga-4-tag

**Question 2** : FYI , I found few additional stories under `Modules/Analytics/Settings/SettingsEdit/` . See highlighted stories under below screenshot. These stories are not on main branch and also not under QAB screenshot. Is this due to changes introduced in any other ticket ?

![image](https://user-images.githubusercontent.com/94359491/173764792-2152ffda-eb1a-4d8a-bdec-0978b8c636b1.png)

**Comment by aaemnnosttv** [comment]
> I found an additional story in AC which screenshots and details are not mentioned in QAB. Is the story "`With GA4 tag , non matching property selected`" and story mentioned below are same ?

@mohitwp yes, they are the same 👍 

> I found few additional stories under `Modules/Analytics/Settings/SettingsEdit/` . See highlighted stories under below screenshot. These stories are not on main branch and also not under QAB screenshot. Is this due to changes introduced in any other ticket ?

These were added as part of #5301

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified**

- The following old stories under `Analytics module / Setup` and `Analytics module / Settings` below are removed .
    ![image](https://user-images.githubusercontent.com/1621608/166342661-45dbf5c2-510c-41e3-b13d-bb7eab8d5bb1.png)

- New stories added under
`Modules/Analytics/Setup/SetupFormUA/`
`Modules/Analytics/Setup/SetupFormGA4/`
`Modules/Analytics/Setup/SetupFormGA4Transitional/`
`Modules/Analytics/Settings/SettingsEdit/`



<details>

![image](https://user-images.githubusercontent.com/94359491/173833756-b94b90e5-92bd-4299-b2c5-428517520a8c.png)

![image](https://user-images.githubusercontent.com/94359491/173833828-a24b60b6-71ce-4bb9-b135-b8668a3875db.png)

![image](https://user-images.githubusercontent.com/94359491/173833945-fd37b0d1-a4fa-45d8-bb63-28b2ed01cc85.png)

![image](https://user-images.githubusercontent.com/94359491/173833085-782f5ff4-4685-44d4-a749-2e02cc0787b3.png)

![image](https://user-images.githubusercontent.com/94359491/173833258-cef796b1-d344-4d06-81b2-3cb7e9abbcf5.png)

![image](https://user-images.githubusercontent.com/94359491/173833604-9e96e637-58bd-4a33-b252-ed15212ebc7a.png)

</details>
