### ISSUE TITLE
Fix odd loading experience UX in new AdSense setup flow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5159]
See https://github.com/google/site-kit-wp/issues/5106#issuecomment-1115176736: The progress bar experience in the AdSense V2 flow needs to be fixed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense V2 `SetupMain` component should always render the "wrapper" UI (AdSense title, icon etc), even when in a loading state. The `ProgressBar` should be rendered within that UI rather than instead of it.
    * See the V1 `SetupMain` component for reference which does it like that already.

## Implementation Brief
* Using `assets/js/modules/adsense/components/setup/v2/SetupMain.js`, set `viewComponent` to be `ProgressBar` if `accounts` is `undefined` instead of returning `ProgressBar` early.

### Test Coverage
* No new tests to be added.

## QA Brief
* Enable the `adsenseSetupV2` feature flag.
* Set `Force AdSense account status` to `no-client`, `needs attention` `client requires review client` `getting ready` or `ready` and observe the loading behaviour when setting up AdSense. The AdSense logo should always be visible and the progress bar should always be visible within the container area.

## Changelog entry

* Fix AdSense logo and progress bar placement in new setup flow.

**Comment by felixarntz** [comment]
IB ✅

**Comment by sancodes** [comment]
@felixarntz hello again, if this is open, can I try to tackle it? Please let me know, thank you.

**Comment by wpdarren** [comment]
QA Update: ✅ 

**Verified:**

- The AdSense logo is always be visible and the progress bar is visible within the container area.

https://user-images.githubusercontent.com/73545194/167420434-405d5a37-116a-4eee-a63f-04e221373cd8.mp4
