### ISSUE TITLE
Errors when getting OAuth credentials

### ISSUE THREAD

**Issue by wpfella** [google/site-kit-wp#517]
## Bug Description

> field [project_id] has issue [project_id contains invalid characters]

## Screenshots

![Screen Shot 2019-09-11 at 8 06 15 pm](https://user-images.githubusercontent.com/52855737/64688410-a569bd80-d4cf-11e9-820b-5f9c05406bdc.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Please keep the issue template in tact as we use this throughout the lifecycle of the issue.

I've restored the template for you. Can you please elaborate on how to reproduce this as well as provide the additional context?

**Comment by jamesozzie** [comment]
@wpfella Are you encountering the same issue when trying to setup Site Kit? It would be great to know the steps you took to reach that error. If possible please share, and include you [Site Health info](https://i.imgur.com/Rtkmsba.png)

**Comment by wpfella** [comment]
The issue is now resolved. 

All I did was log out of my google account and logged back in and tried again and it was fixed. 

Since then, I did set up Google Sit Kit on a few other websites and was never an issue. 

This was a once-off for me. But I will be interested in finding out if anyone else faced a similar issue.
