### ISSUE TITLE
Include a link to "Edit in Tag Manager" when viewing or editing the Tag Manager module

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5174]
## Feature Description

When viewing the connecting status within the plugin settings for the Analytics module there is an option to "Edit in Analytics". 

Should the Tag Manager API allow consider adding the same link for the Tag Manager module to allow users to easily navigate to and edit the tags contained within a connected container. 

https://user-images.githubusercontent.com/41326532/166954697-46c216fb-6395-465c-a961-9a2fc66ebb83.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The settings view for GTM should be updated to include an edit link next to the container ID for web and AMP containers following the implementation in Analytics for consistency
* The link should read "Edit in Tag Manager" and link to the following path on the service which should always open for the Google account the user is signed in with  
	```
	/#/container/accounts/:accountID/containers/:internalContainerID
	```

## Implementation Brief

- Get the settings view URL using the `getServiceURL` selector of the `modules/tagmanager` store.
- Construct the `path` using the `escapeURI` function with the format `/#/container/accounts/${ accountID }/containers/${ containerID }` where `accountID` and `containerID` are already available from `getAccountID` and `getContainerID` selectors respectively.
- Pass an object with the `path` property to the `getServiceURL` selector to get the final URL.
- Reuse the following elements from the Analytics settings view to display the "Edit in Tag Manager" link:
https://github.com/google/site-kit-wp/blob/1148434deb199f8957929e88862eee3f9f76ebb0/assets/js/modules/analytics/components/settings/SettingsView.js#L140-L154
- Change the module name to `Tag Manager` appropriately.
- Render it below the `Container ID` elements. It should be inlined with the `Account` and `Container ID`.

### Test Coverage

- No new tests are to be added.

## QA Brief

- Connect the Tag Manager module in Site Kit.
- Go to Site Kit -> Settings -> Connected Services -> Tag Manager.
- Verify that an `Edit in Tag Manager` link shows up besides the Container ID.
- Verify that clicking on it navigates you to the appropriate Tag Manager service page in a new tab.
- Also set up the site with the AMP plugin to be an AMP site.
- Re-setup the Tag Manager module to use an AMP container.
- Verify that the `Edit in Tag Manager` link still works as expected.
- If both web and AMP containers are configured, verify that there are two different `Edit in Tag Manager` links for each container.

## Changelog entry

* Include a link to "Edit in Tag Manager" when viewing the Tag Manager module settings.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit I have two observations:

1. When I have a web and AMP container set up, the `Edit in Tag Manager` appears alongside the web and AMP container ID, and when I click on the link it defaults to the AMP container.  I have to manually select the web container in tag manager to be able to view the settings for this container.  Reading the AC I am wondering if this is expected.

> The settings view for GTM should be updated to include an edit link next to the container ID for web and AMP containers following the implementation in Analytics for consistency.

Do you think we should have a `Edit in Tag Manager` for web and AMP separately?  It feels an odd user experience as is.

2. In the AC it mentions that the URL should be:

>  /#/container/accounts/:accountID/containers/:internalContainerID

This is the URL for the `Edit in Tag Manager` link

`https://accounts.google.com/accountchooser?continue=https%3A%2F%2Ftagmanager.google.com%2F%23%2Fcontainer%2Faccounts%2F6063412162%2Fcontainers%2F97204523&Email=qask180test%40gmail.com` 

I don't see the colon as part of the URL, i.e. for the `accountID` and `internalContainerID` Is this expected? I do seem to be taken to the correct place to edit the container, etc.

**Comment by nfmohit** [comment]
Very valid findings, thank you for highlighting them, @wpdarren!

> Do you think we should have a `Edit in Tag Manager` for web and AMP separately? It feels an odd user experience as is.

I believe we should have the link pointing to the Web container as default/primary if both web and AMP containers are connected (this isn't the case currently, I'll have to open a quick follow-up PR to achieve this). What do you think, @aaemnnosttv?

> I don't see the colon as part of the URL, i.e. for the accountID and internalContainerID Is this expected? I do seem to be taken to the correct place to edit the container, etc.

This is expected. The colons represent that `accountID` and `internalContainerID` are URL parameters and we need to pass the values for those terms instead of the literal text. Thank you for checking!

**Comment by aaemnnosttv** [comment]
> > Do you think we should have a `Edit in Tag Manager` for web and AMP separately? It feels an odd user experience as is.
> 
> I believe we should have the link pointing to the Web container as default/primary if both web and AMP containers are connected (this isn't the case currently, I'll have to open a quick follow-up PR to achieve this).

@wpdarren @nfmohit There should be one edit link for each container since the links are container-specific. I see the AC is slightly ambiguous about this but in secondary AMP there should be two separate links.

**Comment by nfmohit** [comment]
Thank you @aaemnnosttv for the confirmation. I've opened #6223 to address this.

CC: @wpdarren

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren – back to you for another pass 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified**

- An Edit in Tag Manager link shows up besides the Container ID for all types of container including AMP. 
- The Edit in Tag Manager link still works as expected.
- The Edit links appear against the container IDs and are viewable on all screen sizes. 

![image](https://user-images.githubusercontent.com/73545194/204747950-21a6aafb-fb56-4d16-87bc-e5a0a4032e89.png)
