### ISSUE TITLE
Don't allow Optimize connection if the UA or GA4 snippets were not placed via Site Kit

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5175]
## Bug Description

If a user has manually inserted **_both_** their UA and GA4 snippets and then connected the Analytics module they'll thne have the ability to connect the Optimize module. This shouldn't be the case, as Site Kit will only attach the Optimize container ID to one of these Site Kit placed snippets. 

To resolve this don't allow the Optimize container to be setup within Site Kit unless the plugin has inserted either a UA or GA4 snippet, or consider improving the notice within the Optimize module with it's not available. 

**Possible solution **

Don't allow the Optimize container to be connected unless Site Kit has been used to insert both a UA or GA4 snippet. This is due to the plugin not inserting the Optimize container ID on a non SK placed snippet. 

![image](https://user-images.githubusercontent.com/41326532/166961488-2ba2ba1c-bdbc-4e6c-aa2e-d15ba432127f.png)

**Possible improvement - add a notice similar to the below:**

![image](https://user-images.githubusercontent.com/41326532/166960186-69810952-322d-4159-93fc-e394402309dd.png)

Note that any solution to this issue would also close out https://github.com/google/site-kit-wp/issues/4084

## Steps to reproduce

1. Manually insert both a UA and GA4 snippet on your site.
2. Connect the Analytics module within SK (ensure that the plugin has not inserted either snippet).
3. The Optimize module will then be able for connection. Go ahead and connect it. 
4. The Optimize container ID you've defined within SK won't be added to your site source code, to the manually inserted snippets. 

## Additional Context

- [Recording of issue](https://recordit.co/U23uT7eoVb)
- Further details ([internal testing Asana task](https://app.asana.com/0/1185360131189553/1202218639078151/f))
- Site Kit 1.73.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@jamesozzie We've decided to stall this issue for now since it is a minor edge case for a service that is not heavily used. But we discussed the solution which would be to 'disable' the `Optimize` card within "Connect more services" with a message similar to what you have suggested. However, we would also have to show a notification banner on the dashboard in the case when the user has already connected Optimize but later toggles off Analytics (still keeping Analytics connected), which would effectively remove the Optimize snippet as well.

cc. @aaemnnosttv

**Comment by jamesozzie** [comment]
I understand @ahlamkotb. As you're based in Egypt, based on the screenshot you provided, it's normal that you'll encounter the AMP related error, with AMP being blocked in your region for reasons outside of out control. The [guide on the plugin website](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#amp-cdn-restricted) is therefore applicable to your case, with AMP being used in the Site Kit set up process. 

With regards your WordPress.org profile, unfortunately we can't provide assistance on this. Luckily, you'll find useful resources on this, and a link to the forums Slack channels below:
https://wordpress.org/support/forum-user-guide/faq/

**Comment by aaemnnosttv** [comment]
Closing this out in light of the [sunset of the Google Optimize service](https://support.google.com/optimize/answer/12979939) later this year.
