### ISSUE TITLE
Refine copy for button to skip to view-only dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5176]
Follow-up to #4811: The button currently simply says "Go to Dashboard". It should be a bit more clear on that dashboard not being the full dashboard, but the more limited view-only version of it. Alternatively, we may also want to update the copy in the description above, to potentially mention the view-only dashboard as an alternative to signing in.

Here's a screenshot of what this currently looks like:
<img width="1512" alt="Screen Shot 2022-05-05 at 9 14 07 AM" src="https://user-images.githubusercontent.com/3531426/166967029-f039b34e-8b7d-4669-95d4-faf396a21dc8.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Replace current secondary CTA copy with "Skip sign-in and view limited dashboard" 

## Implementation Brief

- In `assets/js/components/setup/SetupUsingProxyWithSignIn.js`, change the `<Link />` text to `Skip sign-in and view limited dashboard` here:
https://github.com/google/site-kit-wp/blob/a2823b7c40c1e5cd5e398d5699b0a7c9a5ea28e1/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L363

### Test Coverage

- No new tests are to be added.

## QA Brief

- QAing this issue would require granting administrators access to the view-only dashboard, logging in as a secondary administrator to view the Site Kit setup screen, and making sure that the secondary CTA copy says "Skip sign-in and view limited dashboard". But according to my observation, this isn't available yet at the moment.
- For now, please check Storybook for the "Start - with Dashboard Sharing enabled and available" story and ensure the secondary CTA has the copy "Skip sign-in and view limited dashboard", as opposed to "Go to Dashboard" in the `develop` branch.
- For convenience, I've attached a screenshot to imply what it should look like:
![Setup : Using Proxy With Sign-in - Start - with Dashboard Sharing enabled and available ⋅ Storybook 2022-05-13 22-08-12](https://user-images.githubusercontent.com/20284937/168323691-3ac1bba5-a2fe-40a1-8c67-8a0e0191d612.png)

## Changelog entry

* Update the "Skip to view-only dashboard" button text.

**Comment by marrrmarrr** [comment]
@felixarntz I updated the ACs with copy that I tried to make as concise as possible, lmkwyt.

**Comment by aaemnnosttv** [comment]
IB ✅
