### ISSUE TITLE
Rely strictly on AdSense API to determine account status

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5183]
Follow-up to #4758, #4759, #5106: The logic in the AdSense setup is now generally correct, however there is something we need to enhance: Currently, some of the states are determined based on the `accountID` and `clientID` settings, and there are a few situations where we don't update them based on the current API responses. This can lead to inconsistent behavior, especially when mocking different statuses with the tester plugin.

It can certainly have real-world implications though too: for example if you first start the AdSense setup with an account that has an AFC client set up but then delete it, when you go back to the AdSense setup, Site Kit still has that old `clientID` set, which is incorrect and leads to the wrong status being set and the wrong UI showing up.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the AdSense V2 `SetupMain` component:
    * If there are no accounts in the API response, but `accountID` is set to a non-empty value, the setting should be updated to be an empty string again (in the respective `useEffect`).
* In the AdSense V2 `SetupAccount` component:
    * If there is no AFC client in the API response, but `clientID` is set to a non-empty value, the setting should be updated to be an empty string again (in the respective `useEffect`).
    * Cleanup: The component should no longer use `getClients` which is unnecessary. That selector is internally used by `getAFCClient`, and its return value alone is sufficient for any of the conditions where the `getClients` result is currently used (e.g. loading state).

## Implementation Brief

* In `assets/js/modules/adsense/components/setup/v2/SetupMain.js`:
  * Update the existing `useEffect` hook that sets the `accountID` setting to set an empty string for the `accountID` setting if `accounts` is an empty array and current value of the `accountID` setting is not empty. https://github.com/google/site-kit-wp/blob/00a2fdf067e3931df0ba20a20f7df3ff1f8789a1/assets/js/modules/adsense/components/setup/v2/SetupMain.js#L138-L148
* In `assets/js/modules/adsense/components/setup/v2/SetupAccount.js`:
  * Update the existing `useEffect` hook that sets the `clientID` setting to set an empty string for the `clientID` setting if `afcClient` is `null` and the current value of the `clientID` setting is not empty. https://github.com/google/site-kit-wp/blob/00a2fdf067e3931df0ba20a20f7df3ff1f8789a1/assets/js/modules/adsense/components/setup/v2/SetupAccount.js#L77-L81
  * Remove the `getClients` selector call and all checks of the `clients` variable.
* Update corresponding storybook stories if any is broken due to the aforementioned changes.

### Test Coverage

* N/A

## QA Brief

For all tests below: Set the tester plugin AdSense site status to "ready".

**Ensure you have at least 1.8.2 of the Tester plugin installed.**

### Ensuring that account is reset
* Set the tester plugin AdSense account status to "needs-attention". Go to the AdSense setup (it should show the correct UI, but that's not the point here).
* Set the tester plugin AdSense account status to "none". Go to the AdSense setup (it should show the correct UI as well, still not the thing to mostly look for).
* Set the tester plugin AdSense account status to "multiple". Go to the AdSense setup. You should now see the dropdown to select an account. If you land in another situation (where your account seems as if it was already selected), it would mean the problem was not fixed as expected.

### Ensuring the client is reset
* Set the tester plugin AdSense account status to "needs-attention". Go to the AdSense setup (it should show the correct UI, but that's not the point here).
* Set the tester plugin AdSense account status to "no-client". Go to the AdSense setup. You should now see the UI where it says that you need to upgrade your AdSense account to support "AdSense for Content". If you land in another situation (where your client seems as if it was set), it would mean the problem was not fixed as expected.

## Changelog entry

* Ensure AdSense account ID and client ID are always set based on API response during setup.

**Comment by felixarntz** [comment]
Added a QA Brief for this already based on how I encountered this bug.

**Comment by eugene-manuilov** [comment]
> * In the AdSense V2 `SetupMain` component:
>   
>   * If there are no accounts in the API response, but `accountID` is set to a non-empty value, the setting should be updated to be an empty string again (in the respective `useEffect`).
> * In the AdSense V2 `SetupAccount` component:
>   
>   * If there is no AFC client in the API response, but `clientID` is set to a non-empty value, the setting should be updated to be an empty string again (in the respective `useEffect`).

@felixarntz I wonder whether we need to save settings after we reset either `accountID` or `clientID`. What do you think?

**Comment by felixarntz** [comment]
@eugene-manuilov 
> @felixarntz I wonder whether we need to save settings after we reset either `accountID` or `clientID`. What do you think?

Yes, we do. Would that not be already the case though based on the auto-submission logic from changed settings?

**Comment by eugene-manuilov** [comment]
> @eugene-manuilov
> 
> > @felixarntz I wonder whether we need to save settings after we reset either `accountID` or `clientID`. What do you think?
> 
> Yes, we do. Would that not be already the case though based on the auto-submission logic from changed settings?

I don't think so. All `set{SettingSlug}` actions just update settings in the store state and not submit changes. I have updated IB to explicitly say that we need save settings after reseting. Do you mind reviewing IB?

**Comment by eugene-manuilov** [comment]
Ah.. yes, you are right, @felixarntz. I forgot about that logic. Yes, it will automatically submit changes because the setting is changed.

**Comment by eugene-manuilov** [comment]
Removed unnecessary `saveSettings` calls from IB.

**Comment by felixarntz** [comment]
@eugene-manuilov Thanks, 2 more things about the IB:
* Instead of two new `useEffect` hooks, I suggest we put that extra code into the two existing `useEffect` hooks that call `setAccountID` / `setClientID` based on that API data.
* You say "reset" the settings, maybe it would be more clear to say "set it to an empty string"?

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
@felixarntz Matthew has a question regarding QA steps in [this comment](https://github.com/google/site-kit-wp/pull/5195#pullrequestreview-969589971). Could you please take a look at it and help him since you wrote the original QAB?

**Comment by felixarntz** [comment]
@eugene-manuilov Replied on the PR.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@felixarntz @eugene-manuilov  I have an observation:

For both of the `'Needs Attention'` tests in the QAB: 

> Set the tester plugin AdSense account status to "needs-attention". Go to the AdSense setup (it should show the correct UI, but that's not the point here). 

I was expecting to see the `Your account isn’t ready to show ads yet. You need to fix some things before we can connect Site Kit to your AdSense account.` UI for Needs Attention.  What I see is ```Add this site to your AdSense account
We’ve detected that you haven’t added this site to your AdSense account yet.``` Is this because I have selected 'None' as the site status? Wasn't 100% sure, so thought I'd check. 

![image](https://user-images.githubusercontent.com/73545194/168070154-5b8b2ff7-3e28-4721-a5d6-2177c5a9a7ee.png)

**Verified:**

_Ensuring that account is reset_

- When the tester plugin AdSense account status is set to "none", the correct UI loads when setting up AdSense.
- When the tester plugin AdSense account status is set to "multiple". the dropdown to select an account appears when setting up AdSense.

_Ensuring the client is reset_

- When the tester plugin AdSense account status to "no-client",  the correct UI appears where it says you need to upgrade your AdSense account to support "AdSense for Content", when setting up AdSense.

**Comment by eugene-manuilov** [comment]
@wpdarren looks like you have the same problem as Matthew had during code review (see here: https://github.com/google/site-kit-wp/pull/5195#pullrequestreview-969589971). He solved the problem by installing the latest version of the tester plugin. Could you please also confirm that you have the `1.8.2` tester plugin?

**Comment by wpdarren** [comment]
@eugene-manuilov yes, I am using the latest version 1.8.2.  

Let me run through it again and I will let you know if this is still an issue for me.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@eugene-manuilov I am still seeing the issue.  I tested it on the previous test site and a new one. 

It looks like Matthew's issue was to do with `multiple` but this is with `needs attention` account status.

- Set the tester plugin AdSense site status to `none`
- Set the tester plugin AdSense account status to `needs attention`
- Set up AdSense and what I see is `Add this site to your AdSense account. We’ve detected that you haven’t added this site to your AdSense account yet`. 
- Using the latest version of the tester plugin 1.8.2
- On the `develop` branch with `adsenseSetupV2` feature flag enabled.

Everything else looks fine. 

![image](https://user-images.githubusercontent.com/73545194/168113785-ac97d3f6-66ca-44cd-b689-5a2cddf52dcc.png)

![image](https://user-images.githubusercontent.com/73545194/168070154-5b8b2ff7-3e28-4721-a5d6-2177c5a9a7ee.png)

**Verified:**

_Ensuring that account is reset_

- When the tester plugin AdSense account status is set to "none", the correct UI loads when setting up AdSense.
- When the tester plugin AdSense account status is set to "multiple". the dropdown to select an account appears when setting up AdSense.

_Ensuring the client is reset_

- When the tester plugin AdSense account status to "no-client",  the correct UI appears where it says you need to upgrade your AdSense account to support "AdSense for Content", when setting up AdSense.

**Comment by felixarntz** [comment]
@wpdarren Apologies, I think that small but crucial detail about the site status to set in the tester plugin was wrong the way I had originally specified it in the QA Brief. What you're seeing is in fact expected because not having a site takes precedence over some of the other relevant criteria. So I've now updated the QA Brief to have the site status always set to "ready".

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_Ensuring that account is reset_

- When the tester plugin AdSense account status to `needs-attention`,  the correct UI loads when setting up AdSense
- When the tester plugin AdSense account status is set to `none`, the correct UI loads when setting up AdSense.
- When the tester plugin AdSense account status is set to `multiple`. the dropdown to select an account appears when setting up AdSense.

_Ensuring the client is reset_

- When the tester plugin AdSense account status to `needs-attention`,  the correct UI loads when setting up AdSense
- When the tester plugin AdSense account status to `no-client`,  the correct UI appears where it says you need to upgrade your AdSense account to support "AdSense for Content", when setting up AdSense.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/168515297-fb1f04b5-f611-4b7b-a427-a7e0c588f821.png)
![image](https://user-images.githubusercontent.com/73545194/168515300-5c1dd290-311d-4337-8e59-0ee46d425ad3.png)
![image](https://user-images.githubusercontent.com/73545194/168515307-d8ce86b3-152b-47c9-b91b-8ad9273535ff.png)
![image](https://user-images.githubusercontent.com/73545194/168515325-926f2708-e927-4394-a153-b03edba5556c.png)
![image](https://user-images.githubusercontent.com/73545194/168515339-fcefa2fe-ef18-4afc-8492-c42ae9d4c58a.png)
![image](https://user-images.githubusercontent.com/73545194/168515350-6ba2d317-2a91-4ebf-bc07-488c98cbe21a.png)

</details>
