### ISSUE TITLE
Update secondary CTA links for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5184]
## Feature Description

As raised in https://github.com/google/site-kit-wp/issues/4764#issuecomment-1118764266 and https://github.com/google/site-kit-wp/issues/4764#issuecomment-1118824807 there is an inconsistency of styling secondary links. These should be updated to be consistent.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `.googlesitekit-cta-link` styles should be adjusted to include the styles from `.googlesitekit-cta-link--inherit`, basically so that all elements that use class `googlesitekit-cta-link` today will look the same as those that use classes `googlesitekit-cta-link googlesitekit-cta-link--inherit` today.
* All usages of the class `googlesitekit-cta-link--inherit` as well as the style definition for this class should be removed.

## Implementation Brief
* Using `assets/sass/components/global/_googlesitekit-cta-link.scss`,
	* Update `.googlesitekit-cta-link` to include the styles from `googlesitekit-cta-link--inherit`
	* Remove the `googlesitekit-cta-link--inherit` class
* Remove the `googlesitekit-cta-link--inherit` class used across the codebase.

* Estimates a bit higher due to QA involved since it's a global change.

### Test Coverage
* No new tests to be added.
* VRT images might need to be updated.

## QA Brief

* QAing this would require making sure all CTA links (not buttons, mostly secondary CTA links) look similar to the "Reset Site Kit" CTA [here](https://google.github.io/site-kit-wp/storybook/main/?path=/story/setup-using-proxy-with-sign-in--analytics-inactive).
* The font family of the said links should be inherited by default, i.e. 'Roboto'.
* A few of the said links may have an intentionally different font size.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz should we standardize on `inherit: true/false?`

**Comment by felixarntz** [comment]
@aaemnnosttv They should all look like they had the `googlesitekit-cta-link--inherit` class. Since that should be the new default though, we should rather integrate that class's styles into the base `googlesitekit-cta-link` styles. I've defined ACs accordingly.

**Comment by aaemnnosttv** [comment]
IB ✅
