### ISSUE TITLE
Fix E2E unexpected "You are probably offline" errors

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5185]
## Bug Description

There are a few instances of a common error resulting in E2E instability from an unexpected console error "You are probably offline". This happens when an API request is cancelled unexpectedly (usually due to a navigation) while it is in progress. This unexpected console error causes the test to fail.

## Examples

```
FAIL specs/dashboard/search.test.js (10.806s)
  ● Site Kit dashboard post search › displays results when searching with a post title, and loads the details page when clicking View Data

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Google Site Kit API Error method:GET datapoint:entity-search type:core identifier:search error:\"You are probably offline.\""]
```

```
FAIL specs/modules/tagmanager/setup.test.js (44.838s)
  ● Tag Manager module setup › Setup with AMP active › with Secondary AMP › when validating › validates homepage AMP for logged-in users

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Google Site Kit API Error method:POST datapoint:survey-trigger type:core identifier:user error:\"You are probably offline.\""]
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E tests should not fail due to "You are probably offline" console errors

## Implementation Brief

* These errors originate from `@wordpress/api-fetch` when a fetch request throws an error. This only happens when the request truly fails (like when you're offline) or is cancelled (e.g. by a navigation) – never from a particular response's status code. As such, the simplest solution here is to add this string `You are probably offline.` to the logic we have for ignoring specific `console` messages in `bootstrap.js`.
    * If we don't want to ignore it entirely, we could simply override the console method to be `debug` which aren't monitored by `jest-console` and would be visible in the log without failing the test.

### Test Coverage

* No change in coverage

## QA Brief

* E2E tests should pass—no further QA needed.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
Moving directly to approval as no QA can be done for this issue.
