### ISSUE TITLE
Update asset bootstrapping for non-admins

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5189]
## Feature Description

As Site Kit prepares for dashboard sharing, many aspects where permissions are today need to be revisited to account for non-admins (as SK is currently restricted to today). One of the last remaining areas to address for this is the loading/bootstrapping of assets. Currently, assets are only loaded for users who can authenticate which is too restrictive for dashboard sharing.

https://github.com/google/site-kit-wp/blob/00a2fdf067e3931df0ba20a20f7df3ff1f8789a1/includes/Core/Assets/Assets.php#L104-L109

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `Assets` registration should be updated such that it performs the full registration for a shared/view-only user in the context of dashboard sharing as it does today for a user who can authenticate
	* That is, assets should load fully if a user can view any of the SK screens

Note: care should be taken to not reintroduce the bug that added the guard above. See https://github.com/google/site-kit-wp/issues/1650

## Implementation Brief

* Update the condition in the `Assets::register` method that checks whether the current user can authenticate to check for the view shared dashboard capability as well and return only if the user has none of these capabilities. https://github.com/google/site-kit-wp/blob/16aefc7586732ef65e451b4964f621766db49459/includes/Core/Assets/Assets.php#L104-L109 In other words, we should return there only if the user has neither `AUTHENTICATE` nor `VIEW_SHARED_DASHBOARD` capabilities.

### Test Coverage

* Add a basic phpunit test that checks that appropriate action and filter hooks aren't registered if the current user has no capabilities.

## QA Brief

* Make sure the Dashboard continues to load and function for authenticated admins. 
* Test with `dashboardSharing` enabled as well.

For non-admins who have a module shared with their role, ensure the splash and dashboard interfaces load – note it is expected that there will be data/report errors or failed requests due to work which is still in progress for the backend. The main thing here is that the interfaces load _at all_ for splash and dashboards where they didn't before.

Note also that until #5188 is done, an extra step will be needed to set the splash dismissal for a non-admin in order to satisfy the condition to view the dashboard. See https://github.com/google/site-kit-wp/issues/4813#issuecomment-1135037589

## Changelog entry

* Update asset bootstrapping for non-admins.

**Comment by tofumatt** [comment]
IB ✅
