### ISSUE TITLE
"Analytics Gathering Data"

### ISSUE THREAD

**Issue by webspacesau** [google/site-kit-wp#519]
## Bug Description

I have installed and been running Site Kit for over a week and it still says Gathering Data

## Steps to reproduce

I have attempted to reinstall/reset Site Kit and same issue

## Screenshots

![image](https://user-images.githubusercontent.com/32596056/64751611-08a33080-d560-11e9-91ee-414c9cc5f626.png)

## Additional Context

 - PHP Version: 7.3
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Plugin Version 5.2.3
 - Device: Testing on Windows 10 PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@webspacesau  Can you try the below, there could be another plugin, Ad Blocker or Firewall/security feature causing this error. 

- Remove the [Analytics module](https://i.imgur.com/6ppIDwZ.png) (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)
- Temporarily deactivate your other active WordPress plugins
- Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

Let me know if that fixes the issue, if not we can troubleshoot further. If the issue arises again please share any [console errors](https://i.imgur.com/f5WfLb3.png).

**Comment by jamesozzie** [comment]
@webspacesau Is your Site Kit dashboard successfully displaying your Analytics data after following the suggested steps?

**Comment by webspacesau** [comment]
Hi James, I've done a fresh install and followed your instructions above. Will let you know if I can see data appearing. Cheers, Phil.

**Comment by jamesozzie** [comment]
@webspacesau Did you have any luck viewing the various dashboard in Site Kit after testing again?

**Comment by webspacesau** [comment]
Hi @jamesozzie yes working now, thanks :)
