### ISSUE TITLE
Merge Existing Tag Simplification

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5204]
The https://github.com/google/site-kit-wp/tree/feature/existing-tag-simplification branch should be merged into `develop`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The https://github.com/google/site-kit-wp/tree/feature/existing-tag-simplification branch should be merged into `develop`.

## Implementation Brief

* Merge #4893 

### Test Coverage

* N/A

## QA Brief

* This issue brings the existing tag simplification work into the upcoming release
* Nothing regarding ETS behavior should change from the previous round of testing 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ☑️ No separate IB review needed here as this is an issue for the feature merge only.

**Comment by aaemnnosttv** [comment]
@felixarntz @techanvil I opened a small follow-up PR here to move the new settings/setup-specific `UseSnippetSwitch` variant components to their respective component directories as a minor cleanup PR.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 @aaemnnosttv as per my message on Slack. 

I have started running through the final ETS testing now that it is merged into Develop. 

Found an issue that wasn’t appearing during bug bash.  I have created a UA property within Analytics, then set up Site Kit / Analytics. It recognised the existing tag UA property, toggle was disabled, and it looked fine. Went through the set up, created the GA4 property. All good. Went to the settings and the UA snippet and toggle is appearing underneath the GA4 property, as you can see on the screenshot. 

![image](https://user-images.githubusercontent.com/73545194/169057154-5f21cda1-cab8-4426-9210-dab112cc9922.png)

**Update:** I can also confirm that the same applies with GA4 as you can see on the screenshot below.

![image](https://user-images.githubusercontent.com/73545194/169056461-2ba00932-c733-4944-9521-6c8111ea94ba.png)

The setup screens behave as expected, it appears to be just the settings for Google Analytics.

**Verified:**

**Google Tag Manager**

- Existing tag does not match selected tag. Passed. UX/UI as expected. 
- Existing tag matches selected tag. Passed. UX/UI as expected.

**Comment by aaemnnosttv** [comment]
Thanks for catching this @wpdarren – this was my mistake introduced in the follow-up PR 😄 

@kuasha420 has fixed it in #5226 so this should be all set now, but please confirm 👍

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@aaemnnosttv @kuasha420 when I tested this earlier today for `Existing UA tag matches selected primary UA tag` the UA snippet was disabled by default, which is expected. I have just re-tested this with a new site, the UA snippet is enabled by default. Do you think the settings fix we've just implemented could impact this? 

![image](https://user-images.githubusercontent.com/73545194/169086013-7bf4a7a6-0ac7-484a-9a8a-1067ae30454c.png)

I'm going to continue to test the scenarios to find any other issues, but wanted to highlight this.
