### ISSUE TITLE
Surface new Interaction to Next Paint field metric in PageSpeed widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5207]
The [Interaction to Next Paint metric](https://web.dev/inp/) was recently introduced as a new crucial field metric, with the goal to provide a more accurate representation on page interactivity than today's default, the First Input Delay metric.

The Interaction to Next Paint metric is currently experimental, but due to its importance in relation to CWV, we should surface it in Site Kit's PageSpeed widget as well - with an annotation that it is experimental.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Based on [this implementation plan](https://docs.google.com/document/d/19xHqNWgxGr7_9ZGtLqn5_jFqhhD8wQIpeDIHdB-fjqk/edit#heading=h.xc10ofhlvdhn), the PageSpeed widget should be enhanced as follows:

* FID should be moved to the end of the field metrics list.
* TBT should be moved to the end of the lab metrics list.
* INP ("Interaction to Next Paint") should be added as a 4th metric to the field metrics list, _if_ the API response includes a `loadingExperience.metrics.EXPERIMENTAL_INTERACTION_TO_NEXT_PAINT` property.
    * Its description should be: _How quickly your page responds when people interact with it_
    * It should be marked with an "experimental" badge/label, looking similar to other "experimental" badges around the product (e.g. on Idea Hub).
* The Storybook stories with field data should be updated to include the new metric.

## Implementation Brief

* Reorganize the FID and TBT metrics as outlined in the ACs.
* Add a new `experimental` boolean prop to the `ReportMetric` component:
    * If set as `true`, display a `Badge` with "experimental" label right after the `title`.
* In the `FieldReportMetrics` component:
    * Add `EXPERIMENTAL_INTERACTION_TO_NEXT_PAINT` to the map of field metrics.
    * Add a new `ReportMetric` component instance below the other ones _if_ the above property is available in the API response.
    * Set the `title` and `description` based on the ACs, and set the `displayValue` and `category` in the same way it is set for FID.
    * Set the new `experimental` prop (see above).
* Modify the Storybook API mock data so that it includes the `EXPERIMENTAL_INTERACTION_TO_NEXT_PAINT` property to ensure INP is shown.
* Complete and merge #5200.

### Test Coverage

* N/A

## QA Brief

Use a site that has field data available. If you don't have access to such a site, you can filter in the URL of such a site even when you're using another site. For example, to rely on `https://web.dev`, add this filter temporarily to your site's codebase:
```php
add_filter(
	'googlesitekit_site_url',
	function() {
		return 'https://web.dev';
	}
);
```

* With the PSI module set up and the filter included, go to the PageSpeed widget. Verify that the new "Interaction to Next Paint" metric is included as 4th metric and that its title and description match the ACs. Furthermore ensure it is marked as experimental.
* Also, with whatever values you get displayed there, do a quick cross-check whether the category label and color correctly fall under the following:
    * Values below 200 are good.
    * Values between 200 and 500 need improvement.
    * Values above 500 are poor.
* Also make sure that the First Input Delay metric is displayed right above the new Interaction to Next Paint metric.
* In the lab data tab, make sure that Total Blocking Time is now displayed as the last metric.

## Changelog entry

* Add new experimental Interaction to Next Paint field metric to PageSpeed dashboard widget.

**Comment by felixarntz** [comment]
@aaemnnosttv IB + PR are ready for review.

@eclarke1 @FlicHollis Still waiting for confirmation from @marrrmarrr on this, but we may want to ship this in the next release already. Let's not add the release to it yet, but I wanted to make sure this is on your radar.

**Comment by marrrmarrr** [comment]
@felixarntz do we have any designs on how the "experimental" label will look in this context? Will it be next to the bigger heading (the metric name)? And at what point do we aim to remove the experimental label, do we have any condition/trigger for that fron the PSI team?

Other than that, should we rename the tabs (as we discussed in your doc with Seba) in the same issue, or create a new one? 

Beyond these two things, this is good to go from my perspective.

**Comment by felixarntz** [comment]
@marrrmarrr You can see what it currently looks like in the implementation here: https://google.github.io/site-kit-wp/storybook/pull/5200/?path=/story/pagespeed-insights-module-components--dashboard-widget

So yeah, it would be next to the heading.

> Other than that, should we rename the tabs (as we discussed in your doc with Seba) in the same issue, or create a new one?

Yeah let's do that in a separate issue as it's unrelated to the new metric.

**Comment by tofumatt** [comment]
IB ✅ 

I'll review the code here as well, should be in just a bit 🙂
