### ISSUE TITLE
Admin bar stats missing in wp-admin

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#521]
## Bug Description

Stats are currently not displayed on the post edit screen of a post/page which has data. Stats currently display properly on the front end.

## Steps to reproduce

1. Set up site kit to use a site with Search console and Analytics data.
2. On the front end navigate to a post on the front end which has post specific data. eg. in the test screenshots below, the browser is at **googlesitekit.local/blog**, mapped to **thelivesite.com/blog** (not the actual domain) which has data.
3. Hover over the "G" Site Kit menu, note the dropdown opens and shows search console and analytics data for the post.
4. Click "Edit Post" to edit the post.
5. Hover over the "G" Site Kit menu, note the dropdown opens and the data blocks do not load.

Additional note: no rest api/data requests are made even when I have cleared my sessionStorage cache.

## Screenshots

**On front end**
Correctly shows data for the post.

![image](https://user-images.githubusercontent.com/1621608/64765605-17ccb300-d54d-11e9-9c50-1414abcc2026.png)

**On post edit screen**
Data blocks are missing.

![image](https://user-images.githubusercontent.com/1621608/64765629-25823880-d54d-11e9-88c2-dfc3efb579ac.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When opening the "G" Site kit menu from the post edit screen, the menu should display properly and load the correct data, matching the menu behavior on the front end.
* The menu should work correctly in WordPress 4.7, 5.0, 5.2 and 5.2 + latest Gutenberg plugin. It is important to test each configuration because the JavaScript environment is distinct for each.
 

## Implementation Brief

* Ensure modules are enqueued when Site Kit's Admin Bar is active
* Merge #864

## Changelog entry

* Fix bug where admin bar stats would not display under certain circumstances when editing a post in the backend.

**Comment by aaemnnosttv** [comment]
This one appears to be a bit of an older issue which seems to maybe be a non-issue now as of #312 (#543)

I can see this work as expected with the current release and we also have E2E tests that check for this as well added in #254.

![image](https://user-images.githubusercontent.com/1621608/66703829-5954a780-ed1f-11e9-9771-4e678a9db3fc.png)

**Comment by aaemnnosttv** [comment]
This is still an issue - testing with v1.0.2 on jurassic.ninja. Same thing as described above. Data shows properly on front end for the same page, but not in editor. Hovering the Site Kit admin bar item does not trigger any data requests either.

**Comment by archon810** [comment]
Same here, I was really confused after setting up Site Kit about how I'm supposed to be using it from the bar when the data is not there. How did 1.0 get released with such a critical bug?

**Comment by jurosko** [comment]
Same situation, I don't see it on the frontend. Site Kit 1.0.3 used:
![image](https://user-images.githubusercontent.com/7831775/68802228-d3998400-065d-11ea-84f5-f4d977fe6007.png)

**Comment by aaemnnosttv** [comment]
Thanks for confirming everyone!

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
Sorry, this one confused me—it seems it should be in code review and not To-Do, so I've moved it over. If there's anything left to do here let me know, but I think this is just waiting for review.

**Comment by aaemnnosttv** [comment]
I'm moving this back to in progress as this introduced a new issue which causes the modules to be loaded twice, duplicating the blocks in the bar. This is because the module script is detected and dynamically loaded from the admin bar loader. This doesn't appear to be necessary now and can be simplified.

**Comment by cole10up** [comment]
**Tested**

Downgraded WP to 4.7.10 and validated "G" admin stats bar is showing:
![image](https://user-images.githubusercontent.com/57115907/71013065-ea8c2580-20a4-11ea-9642-adf34fed5a19.png)

Looks good for WP 5.0.7
![image](https://user-images.githubusercontent.com/57115907/71013383-78681080-20a5-11ea-9fbd-773d8dcb975c.png)

Build showing in the corner here:
![image](https://user-images.githubusercontent.com/57115907/71013446-8fa6fe00-20a5-11ea-8051-2b0eeddd49f7.png)

Looks good for WP 5.2.5
![image](https://user-images.githubusercontent.com/57115907/71013671-e6acd300-20a5-11ea-86c6-25b121e57ce6.png)

Build showing in the corner here:
![image](https://user-images.githubusercontent.com/57115907/71013963-00e6b100-20a6-11ea-8078-c765784f9492.png)

And looks good for current 5.3.1
![image](https://user-images.githubusercontent.com/57115907/71014049-2b386e80-20a6-11ea-9ff0-d846e8a5d83e.png)

Build showing in the corner here:
![image](https://user-images.githubusercontent.com/57115907/71014072-37bcc700-20a6-11ea-8d21-124567c0c762.png)

Clicked through the stats bar 'More Details' link and navigated around checking functionality
![image](https://user-images.githubusercontent.com/57115907/71014167-58851c80-20a6-11ea-9a4e-a5d751e1f9a9.png)

Looks good

Passed QA ✅

**Comment by marrrmarrr** [comment]
👁👍
