### ISSUE TITLE
Update "An existing tag was found" message text

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5211]
## Feature Description

The current language for the message that displays when an existing UA tag that is different from the one selected in SK settings is detected is:

"An existing tag UA-*** was found on the page.
If you prefer to collect data using that existing UA tag, please select the corresponding account and property above."

<img width="756" alt="ua-existing-tag-found" src="https://user-images.githubusercontent.com/12189958/168603052-10de04a4-518e-4a91-aafc-029a63b6b14d.png">

I'd suggest that this should change to:

"A tag for a different property, UA-***, was found on your site. If you'd prefer to collect data using that property instead, please select it above."

@marrrmarrr What do you think? ^^

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@bethanylang this SGTM!

**Comment by aaemnnosttv** [comment]
This sounds like a reasonable suggestion although it does somewhat further complicate the already-rather-complex logic we have around existing tags.

@bethanylang is this something support has found to be a common point of confusion? If not, then I'm not sure the change is worth the effort.

**Comment by aaemnnosttv** [comment]
This already appears to be addressed – the language in setup and settings is consistent now.

https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-setup-setupformua--with-both-tags
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-settings-settingsedit--with-both-tags
