### ISSUE TITLE
Remove extra padding on "An associated Universal Analytics property will also be created" message

### ISSUE THREAD

**Issue by mxbclang** [google/site-kit-wp#5213]
## Bug Description

When setting up Analytics with a GA4 tag already placed, Site Kit will display a notification that a UA property will also be created. Usually these blue bar notifications have text on one side and a Learn more link on the other, but this one has a line break between the two pieces of text.

## Steps to reproduce

1. Create a GA4 property at analytics.google.com
2. Add the GA4 property to the <head> of the site
3. Install and activate Site Kit
4. Activate Analytics within Site Kit
5. This banner displays on the Connect Service > Analytics screen

## Screenshots

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/12189958/168654925-a468bd89-1f88-46ee-a000-9962f2fa50cb.png">

## Additional Context

 - OS: Monterey 12.3.1
 - Browser: Chrome Version 101.0.4951.64
 - Plugin Version: 1.74.0
 - Device: Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no gaps between the notice and learn more link in the Google Analytics Setup page. 

## Implementation Brief

* In `assets/sass/components/settings/_googlesitekit-settings-notice.scss`:
    * Remove top paddings from `googlesitekit-settings-notice__inner-row` class. 

### Test Coverage

* VRTs may need to be updated. 

## QA Brief

* Follow steps to reproduce the problem
* Ensure that the notification shows up now without the extra space as on the screenshot.

## Changelog entry

* Fix bug that caused extra spacing to appear around Universal Analytics property creation message during Analytics setup.

**Comment by aaemnnosttv** [comment]
@asvinb I feel like this used to work as described but seems to have changed at some point. Do you know what the issue may be?

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by vedant-z** [comment]
@bethanylang I am willing to take this issue.
