### ISSUE TITLE
Update "An existing Google Tag Manager property was found on your site" message

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5214]
## Feature Description

The current language for the message that displays when the same existing UA tag as the one selected in SK settings is detected is:

An existing Google Tag Manager property was found on your site with the ID UA-***. Since it refers to the same property selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this property, Site Kit can place a new tag for you.

<img width="803" alt="gtm-property-found" src="https://user-images.githubusercontent.com/12189958/168660228-3842f2f2-bad4-464c-8dd9-d1aaef282dc4.png">

The language here is slightly inaccurate as GTM uses "containers," not "properties," so the "property" language is actually referring to the GA4/UA property that is within the container.

I'd suggest that this should change to:

"A Google Tag Manager container with a tag for the selected property, UA-***, was found on your site, so Site Kit will not place its own tag. If you would prefer to have Site Kit insert this tag, remove it from your Google Tag Manager container and update later in Settings."

@marrrmarrr What do you think? ^^

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Tag Manager detects an existing tag that matches the selected tag, the text should be updated from:

> An existing Google Tag Manager property was found on your site with the ID UA-***. Since it refers to the same property selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this property, Site Kit can place a new tag for you.

to

> A Google Tag Manager container with a tag for the selected property, UA-***, was found on your site, so Site Kit will not place its own tag. If you would prefer to have Site Kit insert this tag, remove it from your Google Tag Manager container and update later in Settings."

## Implementation Brief

* Update the copy at https://github.com/google/site-kit-wp/blob/d07d09a41aeb5e8383a2f389ecde81902d7ca5cb/assets/js/modules/analytics/components/common/ExistingGTMPropertyNotice.js#L51 to use the new string in the ACs.

### Test Coverage

* VRTs may need updating; otherwise no new tests are needed.

## QA Brief

* The text for Analytics setup with GTM setup should be updated as per AC and displayed in the block as per the screenshot in the description.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on both latest and dev branch.
- On latest branch we are getting below messages-

<details>

![image](https://user-images.githubusercontent.com/94359491/192278394-cc2ec2a9-cdf2-4884-a13d-b1c3063c8164.png)

![image](https://user-images.githubusercontent.com/94359491/192278449-21bcb72f-a544-487d-a76a-6b85a9defbe4.png)

</details>

- On development branch message updated as per AC to -

> A Google Tag Manager container with a tag for the selected property, UA-***, was found on your site, so Site Kit will not place its own tag. If you would prefer to have Site Kit insert this tag, remove it from your Google Tag Manager container and update later in Settings."

The above message appear when user selects the same property in analytics.

<details>

![image](https://user-images.githubusercontent.com/94359491/192280600-bd2014fe-3d49-4959-81bc-928d98c80a9b.png)

![image](https://user-images.githubusercontent.com/94359491/192280668-cd47d833-a915-41a9-b69b-b897bc6c4bd0.png)

</details>
