### ISSUE TITLE
Update "Place Universal Analytics code" toggle if GTM is placing the tag

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5215]
## Feature Description

The current helper text under the "Place Universal Analytics code" toggle if a UA tag is detected in a GTM container is:

The code is controlled by the Tag Manager module.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/12189958/168661059-41a8ff03-8378-49fc-889d-3ef845db5ba4.png">

This reads slightly awkward and unclear to me.

I'd suggest it change to:

"The Universal Analytics code is currently being placed via a Google Tag Manager container."

@marrrmarrr What do you think? ^^

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this as UA is nearing EOL.
