### ISSUE TITLE
Implement splash screen GA events for dashboard sharing

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5219]
Based on the [custom GA events defined for dashboard sharing](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit), this issue is focused on implementing the events that are part of the splash screen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new GA event should be fired when the user clicks on the button to skip setup and go to the dashboard (i.e. for users that can authenticate but decide not to do so):
    * Event name: `skip_setup_to_viewonly`
    * Event category: `$viewContext` (i.e. typically "splash")
    * No event label
* A new GA event should be fired when the user clicks on the button to see the view only dashboard (i.e. for users that cannot authenticate but want to proceed to the view-only dashboard):
    * Event name: `confirm_viewonly`
    * Event category: `$viewContext` (i.e. typically "splash")
    * No event label

## Implementation Brief

* Update the `goToSharedDashboard` callback in the `SetupUsingProxyWithSignIn` component:
  * Update the callback function to be async.
  * Add `await` to the `dismissItem` function call.
  * Call the `await trackEvent( $viewContext, 'skip_setup_to_viewonly' )` function before navigating to the dashboard URL.
* Update the `onButtonClick` callback in the `SetupUsingProxyViewOnly` component:
  * Call the `await trackEvent( $viewContext, 'confirm_viewonly' )` function before navigating to the dashboard URL. Use the `useViewContext` hook to get the `$viewContext` variable.

### Test Coverage

* N/A

## QA Brief

* Setup the Site Kit plugin.
* Log in as another admin and go to the dashboard page.
  * You should see the link to skip the setup flow and go to the dashboard with view only mode.
  * Click on this link and verify that the appropriate GA event is sent.
* Log in as an editor and go to the dashboard page
  * Click on the button to see the view only dashboard
  * Verify that you see that the appropriate GA event is sent.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov I have a few observations on this:

For the secondary admin user account:

> You should see the link to skip the setup flow and go to the dashboard with view only mode.

1. I do see the link (see screenshot) but when I click it, the dashboard refreshes, but I do not see the view only mode UI in the header. It just refreshes the page and nothing seems to be different.  Is this expected? 

![image](https://user-images.githubusercontent.com/73545194/170408619-6eb4f15c-b4be-49f4-8793-e2da48586f3d.png)

For the editor user account:

> Log in as an editor and go to the dashboard page. Click on the button to see the view only dashboard. Verify that you see that the appropriate GA event is sent.

2.  To test this, I am using the dashboard sharing settings plugin and pasted`await googlesitekit.data.dispatch( 'core/user' ).dismissItem( 'shared_dashboard_splash' )` into console,  to view the splash page for an editor, but, I go straight to the shared dashboard and no splash screen appears.  Is there another piece of code that I can use to get to the splash page? 

**Verified:**

- When I click on the `Skip sign-in and view limited dashboard` link the appropriate GA event is sent as per AC. 

![image](https://user-images.githubusercontent.com/73545194/170468720-43f65aeb-5f96-47ce-b2db-e8d255692686.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_When logged in as another admin:_

- When I click on the link to skip the setup flow and go to the view only dashboard, the GA event is sent as per the AC. 

_When logged in as an editor:_

- When I click on the button to see the view only dashboard, the GA event is sent as per the AC. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/171018835-376cf5db-aba5-4de1-9257-baa17a49b232.png)

![image](https://user-images.githubusercontent.com/73545194/171018898-3a83ee90-da7c-4e94-8124-25a9493ecfe5.png)

</details>
