### ISSUE TITLE
Implement dashboard sharing modal GA events for dashboard sharing

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5221]
Based on the [custom GA events defined for dashboard sharing](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit), this issue is focused on implementing the events that are part of the new dashboard sharing settings modal.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new GA event should be fired when the user has changed shared roles for a module in the dashboard sharing settings modal (i.e. at the point that the click the "X" after having enabled/disabled at least one of the roles):
    * Event name: `change_shared_roles`
    * Event category: `{viewContext}_sharing`
    * Event label: the module slug for which the roles were changed
* A new GA event should be fired when the user has changed the management permission dropdown (only available if there are multiple administrators on the site) in the dashboard sharing settings modal to "All admins" (setting value is `all_admins`):
    * Event name: `change_management_all_admins`
    * Event category: `{viewContext}_sharing`
    * Event label: the module slug for which the management setting was changed
* Similar to the one above, a new GA event should be fired when the user has changed the management permission dropdown (only available if there are multiple administrators on the site) in the dashboard sharing settings modal to "Only me" (setting value is `owner`):
    * Event name: `change_management_owner`
    * Event category: `{viewContext}_sharing`
    * Event label: the module slug for which the management setting was changed
* A new GA event should be fired when the user clicks the Confirm/Apply CTA button in the dashboard sharing settings modal:
    * Event name: `settings_confirm`
    * Event category: `{viewContext}_sharing`
    * No event label
* A new GA event should be fired when the user clicks the secondary Cancel button in the dashboard sharing settings modal:
    * Event name: `settings_cancel`
    * Event category: `{viewContext}_sharing`
    * No event label

## Implementation Brief

- The current `viewContext` can be retrieved via the `useViewContext` hook.
- The `trackEvent` function can be imported from `assets/js/util/tracking`.

Within file `assets/js/components/dashboard-sharing/UserRoleSelect.js`:

- Add some local state to check whether the user has changed roles for a module. This should be initialised when the **Add roles** button is pressed and updated when the user makes changes to the list of roles.
- Add a call to `trackEvent` to the role selection close handler. As per the AC:
  - Event name: `change_shared_roles`.
  - Event category: `${viewContext}_sharing`.
  - Event label: the module slug for which the roles were changed.

<del>Within file `assets/js/components/dashboard-sharing/DashboardSharingSettings.js`</del>: (this part will be implemented in the scope of #4822 ticket, see https://github.com/google/site-kit-wp/issues/4822#issuecomment-1137022510)

- Add a call to `trackEvent` to the management permission dropdown change handler.
  - Event name:
    - When the dropdown value is `all_admins`, the event name should be `change_management_all_admins`.
    - When the dropdown value is `owner`, the event name should be `change_management_owner`.
  - Event category: `${viewContext}_sharing`.
  - Event label: the module slug for which the management setting was changed.
- Add a call to `trackEvent` to the **Apply** button click handler.
  - Event name: `settings_confirm`.
  - Event category: `${viewContext}_sharing`.
- Add a call to `trackEvent` to the **Cancel** button click handler.
  - Event name: `settings_cancel`.
  - Event category: `${viewContext}_sharing`.

### Test Coverage

* No new tests needed.

## QA Brief

Note: This is dependent on #4822 being merged before this can be tested.

* Open sharing settings and start changing roles for a module.
  * Verify that the appropriate GA event is triggered when you close roles and sharing roles have changed for the module.
* Edit roles again and now close roles select component without making changes.
  * Verify that this time no GA events have been triggered.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov an observation when I click on the 'Apply' button in the dashboard sharing settings.  I created a screencast but in short, I see GA events triggered that I wasn't expecting. Please could you confirm if this is expected?

https://user-images.githubusercontent.com/73545194/171628091-e87bf710-c1d7-4130-9e03-196cac7c5e01.mp4
