### ISSUE TITLE
Refactor capabilities as they apply to dashboard sharing settings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5229]
## Feature Description

In #4481, [capability checks](https://github.com/google/site-kit-wp/blob/76cc88498c98ae65c4a4df13fd91f5baecf83d9b/includes/Core/Modules/Module_Sharing_Settings.php#L146) were added to restrict which parts of the module sharing settings can be modified. This logic, while largely correct should be moved out of the module sharing settings class itself and live either in the controller or somewhere in between. Secondarily, the capability checks should be extended such that only users who can `DELEGATE_MODULE_SHARING_MANAGEMENT` can modify the `management` value for a module's sharing settings. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No capability checks should be performed within the `Module_Sharing_Settings` class
	* These should instead happen within the REST endpoint handler for `POST:sharing-settings` as the only place where these are managed from Site Kit.
* The application of these capability checks should be done in a way that can be easily applied elsewhere without needing to duplicate/reimplement the logic
* Specifically the two capability checks should work as follows:
	* If the user does not have the ability to `MANAGE_MODULE_SHARING_OPTIONS` for a module, no change should be made to that module's `sharedRoles` value
	* If the user does not have the ability to `DELEGATE_MODULE_SHARING_MANAGEMENT` for a module, no change should be made to that module's `management` value

## Implementation Brief

* Introduce a new `Collection_Key_Cap_Filter` utility class which is designed to filter a specific key of each item in a given collection based on a capability
	- The array key of each item in the array will be passed to the capability check as an argument for meta capability checks
* Apply the new key-cap filter to the incoming sharing settings in the `POST:sharing-settings` REST route definition before merging with the current sharing settings
	- One filter will be for the `sharedRoles` key, requiring the `MANAGE_MODULE_SHARING_OPTIONS` capability
	- One filter will be for the `management` key, requiring the `DELEGATE_MODULE_SHARING_MANAGEMENT` capability
	- Finally, `merge` the filtered result with the current sharing settings
* Update the implementation of `Module_Sharing_Settings::merge` to match `Module_Settings::merge`
* Finish and merge https://github.com/google/site-kit-wp/pull/5259

### Test Coverage

* As a generic utility class, simple tests can be added for `Collection_Key_Cap_Filter`
* Current permission-related tests for `Module_Sharing_Settings::merge` should be moved to the `REST_Dashboard_Sharing_ControllerTest`, but only where current coverage is lacking

### QA
- Create an admin user, say "admin1" and setup SiteKit but do not setup analytics. This makes "admin1" the owner of search-console.
- Create another admin user, say "admin2" and setup analytics making them the owner of analytics.
- Within the Dashboard Sharing UI, verify that both, "who can view" and "who can manage access" fields are editable by the owner of the module and setting changes take effect.
- Also verify that an admin can change the "who can view" field if the owner of that module has set the "who can manage access" setting to All Admins. Otherwise, no other admin should be able to change this setting.
- Finally, verify that only the owner of a module can change the "who can manage access" setting. No other user can change this setting.

* QA:Eng
    * Test the `core/modules/data/sharing-settings` with a API client or browser console with valid and invalid data and make sure AC is met. 

## Changelog entry

* Ensure only users with the `DELEGATE_MODULE_SHARING_MANAGEMENT` permission can modify the `management` value for a module's sharing settings.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Within the Dashboard Sharing UI, both, "who can view" and "who can manage access" fields are editable by the owner of the module and setting changes take effect. 
- An admin can change the "who can view" field if the owner of that module has set the "who can manage access" setting to All Admins. Otherwise, no other admin can change this setting.
- Only the owner of a module can change the "who can manage access" setting. No other user can change this setting.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/173566239-21aa7e4c-10c5-4b22-b29b-93fd9a7ee420.png)
![image](https://user-images.githubusercontent.com/73545194/173566257-7481b73f-e112-4266-8c21-952fb3e532da.png)
![image](https://user-images.githubusercontent.com/73545194/173566273-b63a216a-e759-4d19-b68c-dd6fecbada2d.png)
![image](https://user-images.githubusercontent.com/73545194/173566286-b0c4f8f2-6451-48e3-93d9-66bd3944113d.png)

</details>

**Comment by jimmymadon** [comment]
## QA: Eng ✅ 

Tested with the QAB of #4481. 

<details>
 <summary>Verified failed requests when feature flag is off, for GET request and POST request without body params.</summary>
<img width="537" alt="Screenshot 2022-06-16 at 16 42 45" src="https://user-images.githubusercontent.com/1721319/174113463-b681b47b-14c6-4925-9a2a-da13bb19b7f9.png">
<img width="692" alt="Screenshot 2022-06-16 at 16 45 06" src="https://user-images.githubusercontent.com/1721319/174113473-41af1095-108d-4c6c-82d9-69c5fdf0120e.png">
<img width="712" alt="Screenshot 2022-06-16 at 16 46 09" src="https://user-images.githubusercontent.com/1721319/174113481-c8bce2a4-3d38-43a0-b59c-0510f269d9ec.png">
</details>

<details>
 <summary>Verified successful adding and editing of settings along with changing owner of PSI when settings are changed with another admin.</summary>
<img width="493" alt="Screenshot 2022-06-16 at 16 44 16" src="https://user-images.githubusercontent.com/1721319/174114041-d32e12c6-3864-4273-a4a5-4767cbae3000.png">
<img width="635" alt="Screenshot 2022-06-16 at 16 51 38" src="https://user-images.githubusercontent.com/1721319/174114084-1a650e7f-b25a-47bf-a5ce-aeda3f7f8834.png">
<img width="494" alt="Screenshot 2022-06-16 at 16 49 13" src="https://user-images.githubusercontent.com/1721319/174114067-66945f79-ff48-4794-968d-1d1988ee40cb.png">
</details>
