### ISSUE TITLE
Add new selectorData object in getErrorForSelector

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#5234]
## Feature Description

In order for us to be able to retry requests that encountered errors, we need to be able to invalidate their selectors. To do this, we need to return information about the selector that caused an error to be dispatched in the `getErrorForSelector` selector.

See the design doc section for more detail: https://docs.google.com/document/d/1QIruz3fJSDQJ2cILtBHlU6ow8esyaVS3mcuaqt5QQR8/edit?resourcekey=0-nM2tn9DOjjHDWTtspbERkA#heading=h.xleqo0mvx6mv

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `getErrorForSelector` selector should return a new object whenever possible: `selectorData`. This object should contain:
  * a `storeName` attribute, with the name of the store supplied to `createErrorStore()`
  * a `name` attribute, which is the name of the selector that caused the error
  * an `args` attribute, which is an array of the arguments (if any) passed to the selector

## Implementation Brief

* Check for the `storeName` value for the current error store (based on the work done in #5235). If not available, don't return any `selectorData` because we shouldn't ever return "not enough" data to allow a reset of an error's resolver.
  * If `storeName` is a required attribute in #5235, `getErrorForSelector` should always return the `selectorData` attribute.
* If `storeName` is found, return the `selectorData` attribute with the `storeName`, `name`, and `args` attributes. These should be the `storeName` from above, the selector's name, and the array of arguments passed to the selector respectively.

### Test Coverage

* Add tests that ensure these attributes are present when `createErrorStore` is used with a `storeName` set and that the `selectorData` attributes on `getErrorForSelector` match the selector whose resolver encountered an error (use various types of arguments and no arguments at all for the selector).
* If `storeName` ends up being an optional attribute based on #5235's implementation: add tests to ensure when `createErrorStore` without a `storeName` is used, the `getErrorForSelector` selector doesn't return a `selectorData` attribute.

## QA Brief

- This adds the `selectorData` to errors, so the best way to QA this is to run through some of the selectors that produces an error state. For example, in the browser console, set an error state for the `getURLChannels` selector:

```js
googlesitekit.data.dispatch('modules/adsense').receiveError( {
	code: 403,
	message: 'Forbidden',
	data: {
		status: 403,
		reason: 'forbidden',
	},
}, 'getURLChannels', [100, 200] );
```
- Run the selector to verify it contains the `selectorData` object with the properties that matches the selector name and args:

```js
googlesitekit.data.select( 'modules/adsense' ).getErrorForSelector( 'getURLChannels', [100, 200] )
```
- Ensure this works for other selectors too.

## Changelog entry

* Update the `getErrorForSelector` selector to include selector details in the returning error.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
Thanks for testing @wpdarren. Other selectors, I mean any other selectors in our plugin. Unfortunately, we don't have any documentation for the API. For example, you could try the `getModules` selector:

```js
googlesitekit.data.dispatch('core/modules').receiveError( {
	code: 403,
	message: 'Forbidden',
	data: {
		status: 403,
		reason: 'forbidden',
	},
}, 'getModules', [] );

googlesitekit.data.select( 'core/modules' ).getErrorForSelector( 'getModules', [] )
```

LML if this makes sense. If you feel this has to be `QA:Eng`, feel free to add the label.

**Comment by wpdarren** [comment]
@hussain-t since I am unable to come up with the code for the different selectors, and to be completely honest, have no idea what I am looking out for, I would feel comfortable having an engineer looking over this. 

I'll flag it `QA:Eng` to be on the safe side.

**Comment by jimmymadon** [comment]
## QA ✅ 

- Verified the new `selectorData` object for mocked errors and real errors in the plugin.
- Screenshots:
<img width="742" alt="MockedData" src="https://user-images.githubusercontent.com/1721319/174068847-b9d942d4-5ac1-4612-b29b-35336c0ce568.png">
<img width="911" alt="RealErrorData" src="https://user-images.githubusercontent.com/1721319/174068858-e70e56a7-78d5-4be9-be93-68a9e71dec02.png">
<img width="1214" alt="RealErrorData2" src="https://user-images.githubusercontent.com/1721319/174068864-9854a04d-f673-4939-b0b8-a16ad973a804.png">
