### ISSUE TITLE
Inconsistencies in Analytics tracking exclusions switch

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5243]
## Bug Description

There are a few minor inconsistencies with the Analytics tracking exclusion switches.

One is an odd wording case if both "All logged-in users" and "Users that can write posts" are selected, the settings view shows these as a comma-separated list of separate values. If "All logged in users" this obviously includes any other subset so this should be the only thing shown.

Secondarily, there is a full-stop at the end of one of the settings view shown below.

## Steps to reproduce

1. Setup Analytics
2. Edit Analytics settings
3. Toggle off "All logged-in users"
4. Toggle on "Users that can write posts"
5. Toggle on "All logged-in users" again
6. Save settings

## Screenshots

**Primary issue**

![image](https://user-images.githubusercontent.com/1621608/169623047-71acf481-137f-44cf-a222-5ceb260f3ad6.png)

**Secondary copy issue**
<img width="373" alt="image" src="https://user-images.githubusercontent.com/1621608/169622927-7b8f9ce8-bf43-4bb0-a94b-61daf184aff2.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics tracking exclusions setting should only show "All logged-in users" when this option is enabled in the settings view
* The "Analytics is currently enabled for all visitors" text in the settings view should be without a full-stop at the end

## Implementation Brief

* Update the Analytics Settings `sanitize_callback` so that if the new value includes `loggedinUsers`, the value becomes only an array with this one value
	* This will prevent both options from being selected at the same time and the result will be synchronized back to the client on save
* Remove trailing full-stop here https://github.com/google/site-kit-wp/blob/f527d5d88920c8551625a191dcc65736c1b7158c/assets/js/modules/analytics/components/settings/SettingsView.js#L334
	* And here https://github.com/google/site-kit-wp/blob/f527d5d88920c8551625a191dcc65736c1b7158c/assets/js/modules/analytics/components/settings/SettingsView.js#L168

### Test Coverage

* Add a test in Analytics `SettingsTest` to exercise this functionality

## QA Brief

- QAing this would require following the replication steps in the description above and making sure the "Excluded from Analytics" section always says "All logged-in users" only. The first (primary issue) screenshot attached above can be used as a reference for comparison.
- Make sure all the statements in this section do not have a trailing full stop for consistency. The second screenshot (secondary issue) attached above can be used as a reference for comparison.

## Changelog entry

* Update wording for the Analytics tracking exclusions switch.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The "Excluded from Analytics" section always says "All logged-in users" only.
- The statements in this section do not have a trailing full stop.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/170669676-a40847ea-53ea-4209-8df0-956b87553198.png)
![image](https://user-images.githubusercontent.com/73545194/170669699-01b6aae9-9286-4c65-96c2-33b6d5f6a82b.png)

</details>
