### ISSUE TITLE
View only menu isn't visible on shared dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5255]
## Bug Description

In #4826 we integrated the new `ViewOnlyMenu` into the Site Kit header, but since this isn't viewable in the plugin yet, it resulted in a bug in the implementation which prevents it from being shown. 

## Steps to reproduce

1. Enable dashboard sharing
2. Set splash dismissal for shared user
3. Visit dashboard as shared user
4. See no view only menu

## Screenshots

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/1621608/170042330-1b5da78c-c14f-406c-b756-9ef2f0758f52.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The view only menu should show in the header of the shared dashboard (main & entity) when viewed as a non-authenticated user

## Implementation Brief

* Fix the condition which renders the `ViewOnlyMenu` related to the authenticated state of the user to check that the user is **not authenticated** instead of the current (opposite) logic https://github.com/google/site-kit-wp/blob/4c3dfbdf9393c9fb2caa5789f6aeec15481840a0/assets/js/components/Header.js#L88-L90
* Update `Header.stories.js` so that the authenticated state is only applied to non-view-only stories (currently it is applied to all) https://github.com/google/site-kit-wp/blob/4c3dfbdf9393c9fb2caa5789f6aeec15481840a0/assets/js/components/Header.stories.js#L248

### Test Coverage

* No changes

## QA Brief

Note: It might be necessary to follow the steps in this comment - https://github.com/google/site-kit-wp/issues/4813#issuecomment-1135037589 - to view the shared dashboard. It certainly was at the point of CR.

* Follow `Steps to Reproduce` to visit Shared Dashboard. 
* The view-only menu should be visible.
* Also Check the Header Stories, including view-only header on Storybook. 

## Changelog entry

* Make view-only menu visible on Shared Dashboard.

**Comment by eugene-manuilov** [comment]
IB ✅

**Comment by techanvil** [comment]
Hey @kuasha420, the code looks good here but I am unable to follow the **Steps to reproduce** to see it in action.

I've created a 2nd admin, ticked the Shared Roles: Administrator box on the new Sharing plugin, dismissed `shared_dashboard_splash` in the JS console, I see the **Skip sign-in and view limited dashboard** link but I can't get to the shared dashboard, it keeps bouncing me back to the splash screen.

Do you know if I am missing something here?

**Comment by techanvil** [comment]
Update on the above: I have been able to view the shared dashboard, by following the steps here - notably changing a user's role while logged in. https://github.com/google/site-kit-wp/issues/4813#issuecomment-1135037589

Assuming this is required to test the issue it would be worth mentioning this in the QA Brief. I'll add a note.
