### ISSUE TITLE
Match the wording for Analytics permission errors on both the Analytics settings page and the dashboard, or improve the settings page wording

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5266]
## Bug Description

If a user encounters an Analytics permission error the error message displayed on the Analytics edit screen differs slightly between the dashboard and the Analytics edit page. Consider changing the settings page text to match the dashboard text, which is more suitable. 

**Analytics Dashboard**
Your Google account does not have sufficient permissions to access Analytics data, so you won’t be able to see stats from it on the Site Kit dashboard. This service was originally connected by the administrator "****" — you can contact them for more information.

**Analytics settings Page**
Error: Your Google account does not have sufficient permissions for this Analytics account, so you won’t be able to see stats from it on the Site Kit dashboard. This service was originally connected by the administrator "****" — you can contact them for more information.

The reason the dashboard text is more suitable is because the mention of an Analytics "account" can be confusing. A user might have access to the Analytics account, but maybe they they don't have access to the property. 

**Note** that there are occasions when the WP admin handle is not displayed within the error above. 
**Note also** that there is another GitHub issue in relation to changing the final wording on the same error - https://github.com/google/site-kit-wp/issues/5264

An alternative to matching the wording would be to improve the settings page wording. Users can change the Site Kit inserted property if they wish, despite the error. In such cases users don't necessarily need to contact the "other" admin who connected Analytics, they can just choose to insert their own snippet. 

## Steps to reproduce

1. Setup SK and Analytics
2. Disconnect your Google account from plugin
3. Connect once more, this time using a Google account that doesn't have access to the connected property
4. Notice the difference between the settings page and the dashboard

## Screenshots

Analytics dashboard error:

![image](https://user-images.githubusercontent.com/41326532/170262429-a2f089ac-0205-4f2b-a166-7fc584b830c5.png)

Analytics settings error:

![image](https://user-images.githubusercontent.com/41326532/170262628-609c3180-f0b0-4349-abd3-a7d095685696.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@jamesozzie this shouldn't be the case anymore in settings unless the module owner were to lose access to the property 🤔 We only enable editing the connected property/view if the user has access to the currently configured entity. If they don't no error should be shown (this may still happen but there is an issue to fix it if it isn't already).

Aside from that, the message on the dashboard is more about the user not having access to the configured property (view, really) where as settings is a bit more specific to the root cause. Again, the messaging is different now to avoid encouraging users to change the connected property to one they have access to if they don't have access to the one that is currently connected, so it shouldn't be a problem.

**Comment by jamesozzie** [comment]
@aaemnnosttv I just checked this, and the same error appears ([recording](https://recordit.co/M2etwhbitu)). Funnily enough, it only appears the first time (ie. If you cancel, and edit again, it doesn't appear). 

True a second administrator can't edit the Analytics module if another administrator has configured the module, but should we remove or edit the banner notice? I ask as we have documentation for both versions on the plugin website.

**Comment by aaemnnosttv** [comment]
@jamesozzie can you take a look again now that https://github.com/google/site-kit-wp/issues/5429 is merged?

**Comment by jamesozzie** [comment]
All looks good now, thanks @aaemnnosttv 

![image](https://user-images.githubusercontent.com/41326532/188903251-726f74f6-c43b-4204-9a96-f96f479ed1c3.png)
