### ISSUE TITLE
Create GA4 Activation Banner feature flag

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5269]
## Feature Description

Create a feature flag for the GA4 Activation Banner feature.

---

## Acceptance criteria

- A new feature flag, `ga4ActivationBanner`, is created and can be toggled via the Tester plugin.

## Implementation Brief

* Add `ga4ActivationBanner` to the `feature-flags.json` file.

### Test Coverage

* N/A

## QA Brief

- Ensure the `ga4ActivationBanner` feature flag is available in the feature flags drop-down via the tester plugin.
<img width="217" alt="Screenshot 2022-06-13 at 1 25 25 PM" src="https://user-images.githubusercontent.com/24408261/173325848-886182c2-b496-48c0-a032-705dc2107cad.png">

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified 👍 

GA4 feature flag available under feature flag dropdown via the tester plugin on develop branch.

![image](https://user-images.githubusercontent.com/94359491/173556212-c23452c8-d8f2-4187-ba8d-a70e1fa318f3.png)
