### ISSUE TITLE
Implement the Reminder Component design

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5273]
## Feature Description

Implement the design for the Reminder Component in its three variants:

- Initial notice (displayed once a month until June 2023).
- Last month (displayed once every other day during the month of June 2023).
- Post-cutoff (displayed once every other day post-June 2023).

- Design Doc: https://docs.google.com/document/d/1DeWo38lcV7lvLFfcmt-mQ0iaxzB4qfiPArs_yZzYkIM/edit#heading=h.6f4wwpmmyb7h
- Figma: https://www.figma.com/file/vMaCWwr6lpk4PrJWb7jIpz/GA4-Banner-Input?node-id=1082%3A1526

---

## Acceptance criteria

- The placeholder version of the Reminder Component (see #5270) should be replaced with the fully realised design, for each of its variants. For reference, see Figma.
- For all variants display the following:
  - Secondary pane text:
    - _Full cross-device and cross-platform reporting_
    - _Set up advanced conversion tracking, e.g. when visitors submit a form or add an item to cart_
    - _Get detailed insights on how users navigate your site_
  - Learn more link:
    - Text: _Learn more about GA4_
    - Link URL: https://site-kit-dev.appspot.com/documentation/using-site-kit/ga4/
- For each variant display text as follows.
  - Initial notice:
    - Title: _Set up Google Analytics 4 now to join the future of Analytics_
    - Subtitle: _Your current Universal Analytics will stop recording stats on July 1st, 2023_
  - Last month:
    - Title: _You only have X more days to setup Google Analytics 4_ (where X is the number of days until July 1st 2023).
  - Post-cutoff:
    - Title: _Your current Universal Analytics stopped recording stats on July 1st, 2023_
    - Subtitle: _Set up Google Analytics 4 now to resume recording stats_
- Ensure icons are displayed as per the design.
- Ensure the responsive design is implemented.

## Implementation Brief

In `assets/js/components/notifications/BannerNotification/index.js`:

- Add an optional `secondaryPane` prop of type `PropTypes.node`.
- If `secondaryPane` is provided, render the entire component within a new `Grid-Row-Cell` in the root `<section>` container. Convert the `<section>` to be a flex container and the `Grid`s inside to have `flex: 1 1 0px;` to make them of equal width. Change flex-direction to column for mobile as per the Figma mock.

In `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js`:

- Create and style the "Secondary Pane" component as per the AC/Figma mock (with both the Secondary Pane text and Learn More link). Pass this component to the new `secondaryPane` prop in `BannerNotification`. Note: We cannot use the default "Learn More" link props of `BannerNotification` because this will create a link within the main banner and not in the secondary pane.
- Compute the date and switch the `title` and `description` (if there is a subtitle) props passed to the `BannerNotification` component as per the ACs.

Make any styling updates needed.

- `BannerNotification` styles can be found in `assets/sass/components/global/_googlesitekit-publisher-wins.scss`
- Consider adding/using `assets/sass/components/activation/_googlesitekit-ga4-activation-banner.scss` for styling the Secondary Pane component.

Storybook

- Create storybook variations for each of the three reminder components.

### Test Coverage

* Tests could be written for ReminderBanner.js to verify the correct title/description of components based on the date.

## QA Brief

* Verify the new StoryBook stories for the `ReminderBanner`.
* QA this similar to #5272 by changing date and verifying the appropriate Banner title, description and description icon (little image next to the description). All colours and font-sizes have been kept in line with the new design and are standard for other Banner Notifications. However, verify the layout displays as per the figma mocks on all screen sizes.

## Changelog entry

* Add a GA4 upgrade reminder notification for users who have not connected Google Analytics 4.

**Comment by techanvil** [comment]
Hey @jimmymadon, the IB is looking good, but one of the sentences is incomplete:

> Note: We cannot use the default "Learn More" link props of BannerNotification because of

Please could you amend it?

Also - I would consider upping the estimate to an 11, I have a feeling the date related stuff may add a bit of complexity to things, considering the testing involved (both automated and manual). Maybe I am being overly cautious but this looks like an issue that could have some hidden depths.

**Comment by jimmymadon** [comment]
Thanks for the review @techanvil - I agree with upping the estimate.

**Comment by techanvil** [comment]
Thanks @jimmymadon!

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@jimmymadon I have a few observations:

1. All of the Stories for `ReminderBanner` do not have the `Set up now` CTA's and the `Remind me later` link is a button. 

![image](https://user-images.githubusercontent.com/73545194/189642991-8dfac725-874d-427a-b469-17522512650f.png)

2. Minor UI issue really, but comparing figma design to what I see on mobile (i.e. iPhone 8, SE) there's a bigger space between the main and secondary pane text.  See screenshot. 

<details>
 <summary>Mobile screenshot</summary>

![image](https://user-images.githubusercontent.com/73545194/189644453-56e4fb6a-b702-4724-871f-25c7794635ba.png)

</details>

**Verified:** 

- The Reminder Component has a fully realised design, for each of its variants as per the AC. 
- The icons are displayed as per the design.
- The different notifications have a responsive design implemented.

<details>
 <summary>Screenshots</summary>

<img width="1641" alt="Screenshot on 2023-07-03 at 20-54-07" src="https://user-images.githubusercontent.com/73545194/189652245-4b076db0-8dd5-4135-aaab-843ab6c7410c.png">
![image](https://user-images.githubusercontent.com/73545194/189652104-b6a6a413-9b10-41e3-9864-022a5e0e631f.png)
<img width="1640" alt="Markup on 2023-07-03 at 20-54-17" src="https://user-images.githubusercontent.com/73545194/189652333-3af2eec0-ccad-44d0-898c-7d6b44021c1c.png">

</details>

**Comment by jimmymadon** [comment]
@wpdarren This is actually a regression from another issue where some code was renamed but that change was left out from the StoryBook file. 

I've just created a follow up PR branch for this - just a one word fix. @tofumatt - have assigned this to you as it is a very trivial merge and you CR'd this originally and many MRs are off today. 😄

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

- The Reminder Component has a fully realised design, for each of its variants as per the AC. 
- The icons are displayed as per the design.
- The different notifications have a responsive design implemented.
- Confirmed that the Stories are displaying as per the Figma and ACs

<details>
 <summary>Screenshots</summary>

<img width="1641" alt="Screenshot on 2023-07-03 at 20-54-07" src="https://user-images.githubusercontent.com/73545194/189652245-4b076db0-8dd5-4135-aaab-843ab6c7410c.png">

![image](https://user-images.githubusercontent.com/73545194/189652104-b6a6a413-9b10-41e3-9864-022a5e0e631f.png)

<img width="1640" alt="Markup on 2023-07-03 at 20-54-17" src="https://user-images.githubusercontent.com/73545194/189652333-3af2eec0-ccad-44d0-898c-7d6b44021c1c.png">

</details>
