### ISSUE TITLE
Implement the Success Component design

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5274]
## Feature Description

Implement the design for the Success Component - this is essentially just a message with a "Learn more" link.

- Design Doc: https://docs.google.com/document/d/1DeWo38lcV7lvLFfcmt-mQ0iaxzB4qfiPArs_yZzYkIM/edit#heading=h.3ufiycwdh8xj
- Figma: https://www.figma.com/file/vMaCWwr6lpk4PrJWb7jIpz/GA4-Banner-Input?node-id=1082%3A1553

---

## Acceptance criteria

- The placeholder version of the Success Component (see #5270) should be replaced with the fully realised design. For reference, see Figma.
- Display the following text:
  - Title: _You successfully set up your Google Analytics 4 property_
  - Subtitle: _GA4 is collecting data for your site. You’ll only see Universal Analytics data on your dashboard for now._
  - Learn more link:
    - Text: _Learn more about GA4_
    - Link URL: `{proxy}/support/?doc=ga4`
      - Note, this should be the URL returned by `select( CORE_SITE ).getDocumentationLinkURL( 'ga4' )`.

## Implementation Brief

- In `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SuccessBanner.js` (being created in #5270):
    - Locate the `BannerNotification` component. Within this component, add/update the following props:
	    - `title`: `You successfully set up your Google Analytics 4 property` (translatable).
		- `description`: `GA4 is collecting data for your site. You’ll only see Universal Analytics data on your dashboard for now.` (translatable).
		- `WinImageSVG`: should contain the `SuccessGreenSVG` svg component.
		- `dismiss`: `OK, Got it!` (translatable).
		- `format`: `smaller`.
		- `type`: `win-success`.
		- `learnMoreLabel`: `Learn more about GA4` (translatable).
		- `learnMoreURL`: Result of `select( CORE_SITE ).getDocumentationLinkURL( 'ga4' )`

### Test Coverage

* Verify the storybook story for this step.
* Update VRT images if required.

## QA Brief

* Visit Storybook and Check the ActivationBanner. 
* In the story, newly added graphics and learn more link should appear.
* The learn more link should point to the one defined in the AC. 

## Changelog entry

* Implement the design for the Success component from the Analytics-4 module.

**Comment by techanvil** [comment]
@jimmymadon this IB looks good, the component path will likely need updating - see https://github.com/google/site-kit-wp/issues/5270#issuecomment-1196522807 - that aside this looks good to go!

The updated path will probably be: `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/Success.js`

**Comment by nfmohit** [comment]
@techanvil I've updated the component path according to the blocking issue's IB. Thank you!

**Comment by techanvil** [comment]
Thanks @nfmohit!

IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@kuasha420 I verified storybook on main and develop branch. On main branch 'ActivationBanner' component is existed but not on develop branch. I also verified other analytics4 components, but not found required story. Can you please provide link for the storybook which need to be tested ?

**Comment by kuasha420** [comment]
@mohitwp looks like the stories were restructured the same time this was being worked on to be more separate on https://github.com/google/site-kit-wp/pull/5645/files and @nfmohit worked on it. I'll create a follow up PR to add now missing Success Component story and update the QAB accordingly. Cheers.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@kuasha420 
I found story in story book but instead of ActivationBanner like it is mentioned in AC. It is actually named as SuccessBanner in Storybook under Modules>Analytics4>SuccessBanner
Link : https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-successbanner--default

Is it updated and correct ?

![image](https://user-images.githubusercontent.com/94359491/185906545-e4d1672c-9a4f-4089-bed0-cbe6d02865fc.png)

**Comment by kuasha420** [comment]
@mohitwp This is correct as the stories were restructured. I think we may eventually need `ActivationBanner` where everything is wired together in one place, but that seems out of scope for this ticket. 

Cheers.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified SuccessBanner in Storybook under Modules>Analytics4>SuccessBanner
Link : https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-successbanner--default

- All information is as per AC
Title: You successfully set up your Google Analytics 4 property
Subtitle: GA4 is collecting data for your site. You’ll only see Universal Analytics data on your dashboard for now.
Learn more link:
Text: Learn more about GA4
Link URL: {proxy}/support/?doc=ga4

-Learn more link redirecting to [URL] (https://sitekit.withgoogle.com/documentation/using-site-kit/ga4/) as per AC.

![image](https://user-images.githubusercontent.com/94359491/185906545-e4d1672c-9a4f-4089-bed0-cbe6d02865fc.png)
