### ISSUE TITLE
Every time I try to finalize auth & login, it reboots to home page instead of finishing

### ISSUE THREAD

**Issue by johnnyscience** [google/site-kit-wp#528]
## Bug Description

auth & login never finalize & instead reload my home page

I have tried several time to get this plugin to fully activate and finish the login & authorization.  It gets to the final step where I go to verify everything and instead of finalizing it reloads my home page and none of the info is in the plugin any longer and I have to start over from scratch.

I have tried to get this to work for months now with every update that has come out.  Still won't finalize.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@johnnyscience Can you attempt the following steps in order to resolve this issue. 

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching or security suite plugins in use
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

If the above fails to resolve the issue please share your [Site Health info](https://i.imgur.com/Rtkmsba.png), or we can perform further troubleshooting steps. Local software, browser extensions or other applications could also be the cause. 

A similar issue was reported previously, #31.

**Comment by jamesozzie** [comment]
@johnnyscience Did you have any luck getting Site Kit connected?

**Comment by johnnyscience** [comment]
Ok so I had completed removed the plugin from my wordpress install. 

I just reinstalled it and went through the entire process again and I'm getting the same results.  As the final step is being completed and it's verifying my google login credentials, it loads up my website's home page instead.

I'm using Chrome to do this.

Would it help if I gave you login credentials to my wordpress?

**Comment by jamesozzie** [comment]
@johnnyscience You don't need to remove any plugin, but in order to troubleshoot it can sometimes help to temporarily deactivate any caching, security suite or firewall plugin. 

Can you attempt setup from another device to rule out the problem being with local software, VPN or firewall rules. If that fails please share your [Site Health info](https://i.imgur.com/Rtkmsba.png).

**Comment by jamesozzie** [comment]
@johnnyscience Did you get a chance to attempt Site Kit setup?

**Comment by johnnyscience** [comment]
Sorry, I didn't mean for this to close, I am still having issues with it.

I spent at least an hour, if not 2 tonight running through everything 10 times.

After your last reply regarding security suites & firewalls

Could Jetpack, Vaultpress & Sitelock be what's stopping this from finalizing?

I have all 3 installed and they each take care of security threats at various levels.

Would I need to disable all 3 of these?

Sitelock is all handled by them, I supposed I'd have to put in a special temporary request to turn the firewall off while I try the final login?

I even installed the Google Site Kit Developers tool that one of the walk-thrus suggested to do first before running through the setup process.

I have all of my Google Analytics under one gmail account and I have my main website (www.ohiocannabis.com) already setup as a Project, but every time I start the Site Kit install over, it forces me to create a new Project instead of piggy backing on the one that is already up and running and has multiple API's attached to it.

I'm going to do a screen recording of the steps I'm taking

Or would it just be easier for me to give you some login credentials so you can try and figure out exactly what the issue is?

Thank you!

**Comment by johnnyscience** [comment]
Thank you!

Perhaps we could do a screenshare sometime if you think it would help?

**Comment by jamesozzie** [comment]
@johnnyscience Can you temporarily deactivate the following plugins, there may be Google PHP Library conflicts which could impacting setup.:
- Google Analytics For Wordpress
- Events Calendar

After deactivating the above please attempt Site Kit setup again via the Chrome browser and an incognito window, which ensures there are no browser extensions or browser caching interfering with setup.

**Comment by johnnyscience** [comment]
Ok I just did all of that and still the same issue.

It must be my theme or another plugin or something.  

Not sure what to really do unless you guys have any more suggestions?

What is the difference/benefit of this Site Kit over say the Google Analytics plugin I use by Themco? (who is also the creator of the X Theme Pro I'm using)

Thanks for your help.

**Comment by jamesozzie** [comment]
@johnnyscience I don't have experience with the Themco Analytics plugin you are using, they may have similar functionality. Site Kit provides a basic dashboard of Analytics metrics, so if your plugin provides the same or similar functionality it's down to personal preference. Site Kit also features dashboards for other Google products: AdSense, Tag Manager, Search Console, Optimise and PageSpeed insights. 

Future release of Site Kit will have a new authentication flow, but if you want to attempt setup again I would suggest as you mentioned, checking after temporarily changing themes. Or you can check with another WordPress website using the same server, which may rule out the problem being at host level.

**Comment by johnnyscience** [comment]
Hmm ok well thanks for the help.  If you guys think of something else, please let me know.

Maybe I'll take another crack at it when the next big update comes out.  Until then the Google Analytics by Themeco is actually pretty good.  But I would still like to get this Site Kit installed if I can.

**Comment by jamesozzie** [comment]
@johnnyscience Do you have another site you can check with? Hopefully you won't encounter the same issue with the beta release of the plugin, which will have a new authentication flow.

**Comment by johnnyscience** [comment]
Hello, I don't at the time unfortunately.  I'll try to keep an eye out for the beta release.

Thanks again.
