### ISSUE TITLE
Auto-submit the Setup Component form having returned from the OAuth flow

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5282]
## Feature Description

Making use of the state persistence implemented in #5278, ensure the create/connect property execution is automatically continued when returning from the OAuth flow.

An example of this can be seen in the usage of the `autoSubmit` value in the Analytics `SetupForm` component.

- Design Doc: https://docs.google.com/document/d/1DeWo38lcV7lvLFfcmt-mQ0iaxzB4qfiPArs_yZzYkIM/edit#heading=h.2g0r7ejoqctz
- Figma: https://www.figma.com/file/vMaCWwr6lpk4PrJWb7jIpz/GA4-Banner-Input?node-id=1082%3A1526

---

## Acceptance criteria

- Having initiated the OAuth flow to grant the _edit_ scope, via pressing the **Create property** CTA on the Setup Component, upon returning from the the OAuth flow the Setup Component should be displayed and the property creation should automatically continue, without the user having to press **Create property** again.
- The effect should be as though the user has pressed **Create property** i.e. the activity spinner will be shown in the button while the property and measurement ID are created and connected.

## Implementation Brief

The Setup Component is being Implemented in #5270 and #5275. Add the following logic to the Setup Component:
- When the user returns from the OAuth flow, the Setup Component should be displayed using an `autoSubmit` state.
- Get `autoSubmit` state of `CORE_FORMS` store by passing `FORM_SETUP` and `'autoSubmit'` as a string.
- Create a `submitForm` async callback using the `useCallback` hook with the following:
  * It receives the `event` as an argument and prevents the event's default behavior.
  * It should submit the changes by dispatching the `submitChanges()` action of the `modules/analytics-4` store.
  * Check for permission scope error using `isPermissionScopeError` helper and pass the error object returned from the `submitChanges()` action.
  * If there that returns `true`, dispatch the `setValues` action of the `CORE_FORMS` store with `autoSubmit` set to `true`.
  * If there is no error, dispatch the `setValues` action of the `CORE_FORMS` store with `autoSubmit` set to `false`.
  * If there is no error, call the `finishSetup` callback.
- Using the `useEffect` hook, call the `submitForm` callback when the `autoSubmit` state changes and is `true`.
- If `hasEditScope` was already available, the condition in the `useEffect` hook should check for `autoSubmit` AND `hasEditScope` to call the `submitForm` callback.
- Pass `preventDefault` as an empty method within an object as the event argument to the `submitForm` callback.
- It should be similar to the `autoSubmit` logic in the Analytics SetupForm component. See:
https://github.com/google/site-kit-wp/blob/ebbe2b8ab57ee87215f28f0395da1268fdf667f2/assets/js/modules/analytics/components/setup/SetupForm.js#L60-L90

### Test Coverage

- No new tests are to be added.

## QA Brief

- Ensure `ga4ActivationBanner` feature flag is enabled.
- Ensure UA is connected, but GA4 is not connected in your SK setup.
- To get the "no existing GA4 property" variant, ensure there are no GA4 properties available in your Google account.
- Ensure the Google use doesn't have an edit scope. If this is impossible to achieve via the Analytics dashboard console, we can trick SK into thinking it isn't granted even if it is by deleting the `wp_googlesitekit_additional_auth_scopes` meta key for your user from the `wp_usermeta` table.
- Upon clicking the `Create property` CTA, ensure the user is redirected to the OAuth flow and grant access upon the return.
- Ensure the user is landed on the same setup after the successful OAuth flow and grant access.
- Ensure the form is auto-submitted after returning from the OAuth flow.
- Ensure the spinner is displayed while auto-submitting the form.
- Ensure either error or the property was created after the form auto-submit.

**Update**
- As a follow-up fix for observation `#2` from this [comment](https://github.com/google/site-kit-wp/issues/5282#issuecomment-1249998835), ensure after setting up the GA4 from the activation banner, the `Connect Google Analytics 4` button doesn't appear.

## Changelog entry

* Automatically continue creating/connecting a GA4 property on the GA4 Activation Banner upon return from the OAuth flow.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@techanvil I am seeing odd behaviour and not what the AC/QAB details.  

Here are the steps I took to test this and the outcome: 

1. Created new site on InstaWP. Connected Site Kit and created a UA and GA4 property. 
2. I went into Analytics to trash the GA4 property and it shows that this was successful. 
3. I ran the SQL command `DELETE FROM wp_options WHERE option_name = 'googlesitekit_analytics-4_settings';` to delete the GA4 account from Site Kit.  That ran successfully. 
4. Next, I went into the DB and deleted the `wp_googlesitekit_additional_auth_scopes` meta key for my user.  That was successful. 

Here is the flow that I went through:

Step 1.  On the Site Kit Dashboard, I saw the banner `No existing GA4 banner found`.  As you can see from the screenshot, there's the message appearing that I will need to give permission to create an Analytics property.  So the steps above seem to have worked as expected. 

![image](https://user-images.githubusercontent.com/73545194/190121468-61a49773-35f8-4577-a2ba-31a47d113fd1.png)

Step 2. I clicked on the `Create Property` CTA button and was redirected to the Google account slection screen to choose an account, which I did. This is the same account that I used to set up Site Kit initially. 

Step 3. I was redirected to the oAuth screen and I gave permission. 

Step 4. I was then redirected to Site Kit Dashboard and a banner notification, congratulating me for completing the setup of Site Kit. I was confused by the banner, so went to Settings for Analytics and noticed the `Connect Google Analytics 4` button.   What's interesting is that when I checked my Google Analytics account, a GA4 property was created during this process but Site Kit is not showing that. 

Step 5. When the the `Connect Google Analytics 4` button is clicked in settings, I was then sent to connect Analytics.    

![image](https://user-images.githubusercontent.com/73545194/190122868-394a37d9-e62d-4d27-9504-93f498aa683a.png)

![image](https://user-images.githubusercontent.com/73545194/190123776-794f1f40-ceee-483c-852c-fc5ce45ae405.png)

![image](https://user-images.githubusercontent.com/73545194/190123684-44439c40-b64b-48f5-afea-8b086b54a5f5.png)

**Comment by wpdarren** [comment]
### QA Update:  ❌ 

@techanvil the issue reported above is fixed but I have two new observations:

1. After giving permission via the oAuth screen there's a weird screen shift. Then the dashboard and GA4 banner notification load.  You can see this in the screencast below around 18/19 seconds.  

2. When running through the flow as per the AC/QAB, everything looks perfect.  I see the `You have Successfully set up your GA4 property` notification.  When I go to Analytics I see the new GA4 property created, but, when I go to settings, I see the `Connect Google Analytics 4` button hasn't been set up successfully. 

I also tested this in a scenario where the user does not go through the oAuth because they have given permission and the same issue occurs.  I am unsure if it is this ticket that has broken things here, or, #5837 which did pass the QAB.  I'll move this ticket back to execution so it can be investigated. 

https://user-images.githubusercontent.com/73545194/190840679-d4ecfa0d-d888-444b-9ebf-322abc702591.mp4

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/190840728-3e5c9a62-4d39-4173-96e6-728b59c09152.png)
![image](https://user-images.githubusercontent.com/73545194/190840731-7f52117e-bc41-435e-ad93-2861bf48864d.png)
![image](https://user-images.githubusercontent.com/73545194/190840739-b88daf87-ee88-46cd-8a61-af0d3ae59767.png)
![image](https://user-images.githubusercontent.com/73545194/190840741-9c5c0cdc-1b78-492a-b0c4-fba2cdd3f186.png)

</details>

**Comment by hussain-t** [comment]
Thanks, @wpdarren. I have fixed observation `#2` in this follow-up [PR](https://github.com/google/site-kit-wp/pull/5866). As for the first one, I think it could be part of #5837. cc: @techanvil

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Upon clicking the Create property CTA, the user is redirected to the OAuth flow and grant access upon the return.
  - The user lands on the same setup after the successful OAuth flow and grant access.
  - The form is auto-submitted after returning from the OAuth flow.
  - The spinner is displayed while auto-submitting the form.
  - The property was created after the form auto-submit.
  - The issue above is fixed. GA4 property is created and connected successfully. 

https://user-images.githubusercontent.com/73545194/191232611-31de7e5a-deeb-4608-9f8c-f3ad05fe3198.mp4
