### ISSUE TITLE
Refresh list of recoverable modules from the server after recovering a module.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5287]
## Feature Description

The `recoverModules` action currently updates the list of recoverable modules by directly removing the recovered modules from local state.

This should be changed so the recovered modules list is refreshed from the server instead, in keeping with the rest of `recoverModules`, where the recovered module settings and the list of modules are both refreshed from the server after the modules are recovered.

In order to achieve this the mechanism for determining the recoverable modules list should be updated. Rather than inlining the data in the page as `_googlesitekitDashboardSharingData.recoverableModules`, include a `recoverable` flag in the module objects returned by the `GET core/modules/data/list` endpoint, and update the `getRecoverableModules` selector to reference this data.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The serialized module data returned by the `GET core/modules/data/list` endpoint should be updated to include a per-module `recoverable` flag.
* The `getRecoverableModules` selector should be updated to reference the `recoverable` flag in the modules list.
* The `recoverModules` action should be updated to remove the now-unnecessary logic to update the recoverable modules list in local state.
* From a UI perspective the module recovery flow should continue to behave as it does now.

## Implementation Brief

In `includes/Core/Modules/Modules.php`:

- Within the `register` method:
  - Remove the code that sets `recoverableModules` in the `googlesitekit_dashboard_sharing_data` hook handler.
- Within the `prepare_module_data_for_response` method:
  - Add a `recoverable` flag to the module data, with the value of `$module->is_recoverable()`.

In `assets/js/googlesitekit/modules/datastore/modules.js`:

- Within the `getRecoverableModules` resolver function:
  - Remove the references to `global._googlesitekitDashboardSharingData`.
  - Instead, make a call to the `getModules` selector and create a list of module slugs for modules where the `recoverable` flag is true. Then pass this list to `receiveRecoverableModules`.
- Within the `recoverModules` action:
  - Remove the code that calls `getRecoverableModules` and `receiveRecoverableModules`.
  - Instead, yield a call to `invalidateResolver` for the `getRecoverableModules` selector.
- Delete the unused `recoverModule` action. It's not used, the behaviour is covered by `recoverModules`, and it's not worth the maintenance effort to keep an unused and unneeded function around. If we _were_ to keep it, we'd need to update it in the same way as `recoverModules`, along with its tests.

### Test Coverage

- Update the tests for `getRecoverableModules` and `recoverModules` to reflect the new implementations.
- Remove the `recoverModule` tests.
- Fix any failing tests.

## QA Brief

* Regression test the "Recover modules" banner.
  * Site up Site Kit and enable the `dashboardSharing` feature flag.
  * Put the Search Console and/or PageSpeed Insights modules into the recoverable state. This can be achieved by sharing them as a user and then disconnecting that user from Site Kit.
  * View the Dashboard as the first user to see the "Recover modules" banner.
  * Press **Recover** to recover the module(s).
  * The banner should disappear and the modules should be recovered (settings editable in Dashboard Sharing modal).

_"Recover modules" banner:_
![image](https://user-images.githubusercontent.com/18395600/187729926-956d35d4-8b84-46c7-8ca8-5967619693cb.png)

## Changelog entry

* Improve recoverable modules list handling in Dashboard Sharing.

**Comment by aaemnnosttv** [comment]
@techanvil I'm thinking perhaps we rethink this slightly to avoid the need for another endpoint which returns a reduced set of the modules list.

How about instead, we add a `recoverable` property to each module returned by the `modules/list` endpoint, [similar to how we have `shareable`](https://github.com/google/site-kit-wp/blob/d034124e36be3356f7f89bb24b1bf470380b04bf/includes/Core/Modules/Modules.php#L1190) today. We could probably do the same with a `shared_ownership` as well. This way, reloading all modules (as it happens now when dispatching `recoverModule`) would include the state of which modules are recoverable rather than requiring a separate request.

Then we could refactor the selectors to be a subset of `getModules`, similar to how they are on the backend and we could remove this state from the global which is more for data that isn't likely to change between page loads.

If that sounds good to you, let's redefine this one accordingly 👍

**Comment by aaemnnosttv** [comment]
> I think it could still make sense to add a `recoverable` flag to the modules, and move the call to refresh the module list until after all the `recover-module` calls have been made.

Yes, I thought about this as well. We should only reload all the modules once all the module recovery requests are done. It probably makes sense to update the request to allow recovering multiple modules at once too in that case, what do you think?

**Comment by kuasha420** [comment]
@aaemnnosttv I also felt the same way about being able to recover multiple modules in API level while working on the follow up PR for #4823 and created an issue for Triage #5298. Cheers. cc @techanvil

**Comment by techanvil** [comment]
Thanks @aaemnnosttv & @kuasha420. I've updated this issue to specify using a `recoverable` flag to determine the list of recoverable modules. Thanks to Arafat's work in #4823 and the work specced in #5298, no additional work should need to be done for this issue.

Note, I have also added ACs for #5298.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Regression test the "Recover modules" banner.
  - Viewing the Dashboard as the first user and I see see the "Recover modules" banner.
  - When I press the Recover button, to recover the modules, the banner disappears and the modules are recovered.

![image](https://user-images.githubusercontent.com/73545194/188859743-88cee3fa-2e81-4074-a323-8eb928314bb3.png)

![image](https://user-images.githubusercontent.com/73545194/188860003-8614eddf-1f89-433c-9bb8-ae941ed73466.png)
