### ISSUE TITLE
Avoid showing administration-related banner notifications in view-only dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5295]
## Bug Description

The view-only dashboard is currently showing banner notifications related to administration, which should not be shown in such a case of course, since the user can't act on them. See the below screenshot which shows the Idea Hub CTA banner notification to a `contributor` user.

<img width="1549" alt="Screen Shot 2022-05-27 at 4 26 19 PM" src="https://user-images.githubusercontent.com/3531426/170784917-5385718e-2702-4999-9b9a-e03caf220f4a.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* From all banner notifications part of `BannerNotifications` or `EntityBannerNotifications`, the only notification(s) that should ever be shown in a view-only context should be `ZeroDataStateNotifications`.

## Implementation Brief

* In the `BannerNotifications` component:
    * Rely on `useViewOnly` (e.g. `const viewOnly = useViewOnly()`).
    * Wrap all notifications within the rendered `Fragment` in a check whether `! viewOnly`, except for `ZeroDataStateNotifications`.
* `EntityBannerNotifications` can remain unchanged since it only contains `ZeroDataStateNotifications` anyway.

### Test Coverage

* No new tests needed.

## QA Brief

* Ensure that only zero-data state notifications display when viewing the view-only Dashboard.
* Ensure that all types of notification continue to display on the authenticated Dashboard.

## Changelog entry

* Prevent admin-related notifications from appearing on view-only dashboard.

**Comment by felixarntz** [comment]
cc @aaemnnosttv @wpdarren for awareness

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@techanvil would you please add a QA brief?

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@techanvil the QAB suggests that only `zero-data state notifications` display when using view only dashboard.  I do see the gathering state notifications though, which in my opinion, would make sense to keep being displayed.  Just checking though.  I tested this with an editor and admin role. 

![image](https://user-images.githubusercontent.com/73545194/171146815-047ee1bb-96f1-4530-bd4f-51e5250418e0.png)

**Comment by techanvil** [comment]
Hi @wpdarren, thanks for pointing this out - in hindsight the issue could have been a bit clearer. Gathering data notifications are also relevant to non-admin users and are included in the `ZeroDataStateNotifications` component mentioned in the AC. So, they should still continue to be seen.
