### ISSUE TITLE
Shared dashboard triggers errors due to non-viewable widgets rendering

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5305]
## Bug Description

The view-only dashboard limits the widgets it renders based on the viewable modules a user has access to. Due to a logic flaw, it currently renders all widgets initially if `viewableModules` have not resolved yet.

## Steps to reproduce

- Setup dashboard sharing with a non-admin, sharing only `pagespeed-insights`
- Load the shared dashboard as the non-admin
- See errors in console about requests for Search Console

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In a view-only context, widget context and area renders should return `null` so long as `viewableModules` is not an array

## Implementation Brief

* Merge #5306

### Test Coverage

* No changes needed

## QA Brief

* Follow steps to reproduce above, and compare before/after

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- When I am using a site that hasn't the latest develop branch, I do see an error message Google `Site Kit API Error method:GET datapoint:settings type:modules identifier:search-console error:"Sorry, you are not allowed to do that." googlesitekit-api-89b80b549e92ff4a79a6.js:3 ` but when I refresh the site with the latest develop branch, this error no longer appears.  Screenshots below:

Before:
![image](https://user-images.githubusercontent.com/73545194/171348803-0bb6844b-4d82-4947-9acc-f537e4687b87.png)

After:
![image](https://user-images.githubusercontent.com/73545194/171348837-36914905-0693-4fd0-9853-66f388751b03.png)
