### ISSUE TITLE
Link components are not properly disabled by prop

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#531]
## Bug Description

Originally noticed on the _Connect More Services_ tab of the Site Kit settings page, when Analytics is not active/connected, the Optimize and TagManager modules are disabled from being activated, with a message "Setup Analytics to gain access to ___".

The CTA links on these disabled modules are not disabled though, and clicking them triggers behavior (spinner) and produces an error message to appear at the top of the dashboard. These links should be disabled when the module is in this state to prevent this unexpected behavior (albeit an edge case). 

## Steps to reproduce

1. Reset Site Kit + perform minimal setup
1. Go to Settings > Connect More Services
1. Click on _Setup Analytics to gain access to TagManager_
1. See error message appear at the top of the dashboard

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/64846996-a2c5b000-d616-11e9-9689-b46c991aeb84.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It must not be possible to enable a module with unmet requirements.

## Implementation Brief

The problem is actually due to our `<Link>` component which does not pass the `disabled` prop to the inner `<SemanticLink>` to properly disable the click behavior. `disabled` is currently only used to set an additional modifier class.

* Update `assets/js/components/link.js` to pass the `disabled` prop to the inner link

## Changelog entry

* Fix bug where it was unexpectedly possible to enable a module with unmet requirements.

**Comment by aaemnnosttv** [comment]
This actually allows a user to enable a module with unmet dependencies.

E.g. User can activate Optimize by clicking on the link in the disabled box even if Analytics is not setup.

**Comment by tofumatt** [comment]
### Before
Clicking tries to activate the module:
![2019-09-25 21 11 23](https://user-images.githubusercontent.com/90871/65636244-d7a01280-dfd9-11e9-837a-3e95b7a748a7.gif)
### After
Trying to click, it doesn't try to activate the module:
![2019-09-25 21 16 44](https://user-images.githubusercontent.com/90871/65636253-dc64c680-dfd9-11e9-8111-dd25f3419bc6.gif)

Looks good! 👍

**Comment by felixarntz** [comment]
Approved!
