### ISSUE TITLE
Poor UX when connecting PageSpeed Insights

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#532]
## Bug Description

> This will likely be a non-issue when the module switches to using the normal OAuth-based authentication in #511 since there will no longer be a setup flow other than granting new scopes.

Currently, PageSpeed Insights requires an API key to use. If not already set, when activating the module, the user is prompted to provide an API key, and directed to an external site to obtain it.

Upon returning, the user then pastes in their new API key and submits the form. They are then redirected to the Site Kit dashboard, with no further notice/messaging/direction. Furthermore, the PageSpeed Insights widget is out of view at the very bottom of the dashboard. 

Ideally, I think there would at least be a success notice informing the user that their API key works, and include a jump link down to the scroll position of the PSI widget.

**Update**
Although PSI no longer requires an API key to activate, the main problem remains that after activating: the user sees a success banner, but the module itself is not visible with no indication as to where it is. Unlike other modules, PSI also does not have its own page, so it makes this all the more important.

## Steps to reproduce

1. Activate PageSpeed Insights module
1. Get API key
1. Paste in new API key
1. Submit form
1. Land on Site Kit dashboard (top) with no further feedback

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Once the user successfully completes PSI setup, adjust the banner at the top to explain where they can see the new information. 
* Below the main heading ("Congrats on completing setup...") add text "Jump to the bottom of the dashboard to see how fast your home page is." 
* "Jump to the bottom" should be a jump link that takes the user directly to the module. 

Current notification for reference: 
<img width="1073" alt="Screenshot 2020-02-19 at 12 12 22" src="https://user-images.githubusercontent.com/13304791/74829553-8f2f1b80-5311-11ea-849e-d04e1275b148.png">

## Implementation Brief

* Update the [Notification](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/notification.js) component to accept an additional prop which will contain the "Jump to the bottom of the dashboard to see how fast your home page is." text with anchor link to the PageSpeed report at the bottom of the dashboard.
* Update [Notification](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/notification.js) component to display this extra text with the link in between the \<h3\> and the description \<p\>. The text should be in-between the two in size. 
* Update [DashboardSetupAlerts](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/dashboard-setup-alerts.js) component to pass in the appropriate additional prop to `Notification` if the notification is for the PageSpeed setup.
* Add an ID (which corresponds to the anchor link in `Notification`) to the \<div\> for the PageSpeed Insights dashboard widget via the [DashboardSpeed](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/pagespeed-insights/dashboard/dashboard-widget-speed.js) component.

## Changelog entry

* Include anchor link in success notification after setting up PageSpeed Insights module.

**Comment by swissspidy** [comment]
@aaemnnosttv @felixarntz Isn't this obsolete since #511?

**Comment by aaemnnosttv** [comment]
It's definitely much better now, yes. Might be worth revisiting to see if there's anything else we can do here? i.e. the user still may not know that the module is at the bottom of the page.

**Comment by marrrmarrr** [comment]
The findability of PSI can be addressed with a notification at the top similar to what we do for other modules once they're activated ("congrats on setting up PSI!"), which can also direct users where to look. 

In the current banner, we only say "Congrats on completing the setup!" and then offer the rest of the modules that can be activated. I'll update the ACs with what I have in mind, @aaemnnosttv have a look and lmkwyt.

**Comment by aaemnnosttv** [comment]
@marrrmarrr It would be nice if we could use a jump link in that message to take the user right to the component. "Jump to insights" perhaps?

**Comment by marrrmarrr** [comment]
@aaemnnosttv if we have anchors on the main dashboard to link the users to specific points in the page, that would be great.

**Comment by tofumatt** [comment]
Looks like we could add an IB here that adds jump links to the dashboard page and improves this onboarding with relative ease, and that might be a good, easy win until these widgets are entirely refactored via the Widgets Epic (#1299).

Adding "Good First Issue" and inviting a straightforward IB to improve this a bit with minimal changes 🙂

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed latest SK, Installed PageSpeed Insights from settings page.

Noticed on dashboard the link to jump to the bottom of the page
![image](https://user-images.githubusercontent.com/57115907/84359618-bc802d80-ab7d-11ea-9dde-3b2e0ee70027.png)

Tested multiple browsers. Uninstalled PageSpeed insights, reinstalled.

Passed QA ✅
