### ISSUE TITLE
Remove URLSearchWidget

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#5320]
## Bug Description
With the `unifiedDashboard` feature flag removed, the `URLSearchWidget` is no longer used. Most likely it was missed when the feature flag was removed.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of #5471
