### ISSUE TITLE
Add Feature Tour to Dashboard Sharing

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#5328]
## Feature Description

We should add a feature tour for the new Dashboard Sharing features, in line with what's in the design doc/[Figma mockups](https://www.figma.com/file/i04x83uA9U8HHBANlhS7Db/Dashboard-Sharing?node-id=737%3A17896).

<img width="856" alt="CleanShot 2022-06-08 at 20 34 13" src="https://user-images.githubusercontent.com/90871/172701953-349ab1c3-0e1c-4110-baec-1684873161fe.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new feature tour for Dashboard Sharing should be added that includes a single overlay that highlights the new Dashboard Sharing button: https://www.figma.com/file/i04x83uA9U8HHBANlhS7Db/Dashboard-Sharing?node-id=737%3A17896
* There should be a tour focused on the element/button that shows the Dashboard Sharing modal with the text:
  * `New! Dashboard sharing` in the heading
  * `Share a view-only version of your dashboard with other WordPress roles` in the body
  * `Got it` as the dismissal button

## Implementation Brief
* Create `assets/js/feature-tours/dashboard-sharing.js` which will contain the dashboard sharing feature tour.
* Code can be copied over from `assets/js/feature-tours/help-visibility.js` with the following changes:
	* Replace `helpVisibility` by `dashboardSharing`
	* `context` should be `VIEW_CONTEXT_DASHBOARD`
	* `version` should be `1.85.0` (a version far in the future, see this comment: https://github.com/google/site-kit-wp/issues/5328#issuecomment-1154442987)
		* Add a TODO item noting this version should be changed when the feature flag is removed to the actual upcoming version when the flag is removed.
	* `gaEventCategory` should be `${ viewContext }_dashboard-sharing` [TBD]
	* The `steps` array should contain only one item with the following details:
		* `target` should be `.googlesitekit-sharing-settings__button`
		* `title` and `content` as per the AC.
		* `placement` should be `bottom-start`
	* Add `checkRequirements` which should be a function that checks whether the `dashboardSharing` feature flag is enabled, via the `isFeatureEnabled` function.
* Update `assets/js/feature-tours/index.js` to include the new feature tour.

### Test Coverage
* No new tests to be added.

## QA Brief

* QAing this would require going to the Site Kit Dashboard and making sure a feature tour tooltip appears targeting the Dashboard Sharing settings button which includes the text mentioned in the AC.
* The `dashboardSharing` feature flag needs to be turned on in the tester plugin for this to show up.
* Note that the UI can be a little different than the actual Figma design to keep it consistent with the other feature tours. Sometimes the Figma designs are out of sync with our code base. As a result, the difference is expected.

## Changelog entry

* Add a feature tour for the dashboard sharing.

**Comment by tofumatt** [comment]
Looks good to me, but I think the TBD around the GA event needs verification from @felixarntz, so I'm assigning him to review this one as well.

IB ✅ from me though 👍🏻

**Comment by FlicHollis** [comment]
@aaemnnosttv would you be able to take a look at this one?

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt – this looks fine overall, although the `version` is a bit of a tricky detail that hasn't yet really been solved properly for features that are still behind a flag. That is, someone's initial version of SK could be 1.77 just like the feature, in which case they wouldn't see the tour because it wouldn't be new for them. However, the feature might not be enabled for them until later in the 1.77 release cycle or a later release in which case they should see it as a new feature just like everyone else. This would mean they never see the feature tour. I think the easiest solution here is probably to use a far-future version number for the tour for now and then peg it to the real version when we remove the feature flag – probably with a TODO – at which point it should be accurate going forward. How does that sound to you?

**Comment by tofumatt** [comment]
Oh, right on, makes sense.

Cool, I've put a far-future version in there for now and added a note about the reasoning/comment 👍🏻

I figured `1.85.0` was fine, but if it should be adjusted in either direction and the IB's otherwise fine feel free to do that 🙂

**Comment by aaemnnosttv** [comment]
Great thanks!

Regarding the tour, we discussed extending this with additional steps earlier today that would include the sharing settings. I'll open a new issue for investigation as a potential follow-up to this one.

IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

@nfmohit 

**Issue**
Feature tour is not showing if screen width is less than 800 PX (mobile devices). 
Expected : Feature tour must appear on all screens sizes. 

https://user-images.githubusercontent.com/94359491/174765507-d4f2454f-cc0b-4a2c-8f9e-e21c5f51bf3d.mp4

**Comment by jimmymadon** [comment]
@mohitwp @nfmohit I've been working recently on a related issue and know that there is a bug which prevents us from using Feature Tours on mobile devices. So this is a known issue and should be fixed as part of #[3003](https://github.com/google/site-kit-wp/issues/3003).

https://github.com/google/site-kit-wp/blob/260d924faae9c6b08531f0441c3f7445f8b1bef6/assets/js/components/Root/index.js#L58-L63

https://github.com/google/site-kit-wp/blob/260d924faae9c6b08531f0441c3f7445f8b1bef6/assets/js/components/FeatureToursDesktop.js#L29-L31

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you, @jimmymadon 

Verified 👍 

- Feature tour is now showing for all admin users. 
- Feature tour is appearing as per figma design.

Issue mentioned here https://github.com/google/site-kit-wp/issues/5328#issuecomment-1161494439 will get resolve by #https://github.com/google/site-kit-wp/issues/3003

![image](https://user-images.githubusercontent.com/94359491/174783122-d67c6f8e-fcf5-40f5-b8fd-b14c724a4e8e.png)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt @aaemnnosttv while testing another ticket, the feature tour appeared and my instant thought was that it could be more helpful. I feel the feature tour should include a link to the Dashboard Sharing guide.  We tell the user what the icon is for, but don't tell them where to find more information.  

Would this be an easy update to add a learn more link?
