### ISSUE TITLE
Change language on Connect your Google account to Site Kit screen

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5343]
## Description

On the Connect your Google account to Site Kit screen that appears when a second admin goes to _Site Kit > Dashboard_, the following language appears:

> Site Kit has already been configured by another admin of this site. To use Site Kit as well, sign in with your Google account which has access to Google services for this site (e.g. Google Analytics). Once you complete the 3 setup steps, you’ll see stats from all activated Google products.

Historically, we haven't used the word "product" anywhere in SK to refer to Google services/modules. I'd suggest we change to:

> Site Kit has already been configured by another admin of this site. To use Site Kit as well, sign in with your Google account which has access to Google services for this site (e.g. Google Analytics). Once you complete the 3 setup steps, you’ll see stats from all activated Google services.

## Steps to reproduce

1. Connect Site Kit as an administrator
2. Log out
3. Log in as a second administrator
4. Go to Site Kit > Dashboard
5. Message will display

## Screenshots

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/12189958/173591820-42aa2470-ec2b-4c8a-ab62-1cd60f64d9c5.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The language on the splash page should be updated to refer to "Google services" instead of "products" consistently

## Implementation Brief

- In `assets/js/components/setup/SetupUsingProxyWithSignIn.js`:
  - Look for the `description` variable assignment that matches the copy mentioned in the ACs.
  - In it, replace the word `products` with `services`.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Follow steps to reproduce the issue and verify that now it says "Google services" instead of "Google products".

## Changelog entry

* Update language from "services" to "products" in the Site Kit setup screen.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The copy now says `Google services` instead of Google products.

![image](https://github.com/google/site-kit-wp/assets/73545194/6c3ce2c6-f3ae-4281-99ed-4688a4768b06)
