### ISSUE TITLE
For 'View Only dashboard' – CTAs that shared users can't use should not appear

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5346]
## Bug Description

CTAs in the dashboard that are intended for admins, without any useful info or actionable links/items when viewed in a shared context, should not be shown to "shared"/view-only Dashboard users.

Instead, we should show a different CTA informing the user that the admin needs to take steps before the module will be useable. Alternatively, we could show the user nothing as there is currently nothing really to show.

Bug bash issue: https://app.asana.com/0/1202258919887896/1202419867342280 please refer to Asana issue for background 

## Steps to reproduce

1. Connect AdSense module and enable AdSense module sharing in Site Kit.
2. Ensure AdSense property is in a state that would cause a CTA to appear for the admin user
3. Sign in as a "shared dashboard" user
4. See the CTA intended for the admin

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/dd42db60-388c-43b6-a2ba-9357e3db1408)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `AdSenseLinkCTA` component should not be shown in a view-only context

## Implementation Brief

- In `assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js`:
- Using the `useViewOnly` hook, return the `WidgetNull` component if the user has view-only access `AND` Adsense isn't linked.

### Test Coverage

- In `stories/module-adsense-components.stories.js`, add a story to render the `AdSenseLinkCTA` component if it isn't view-only context `AND` Adsense isn't linked.

## QA Brief

* Start off with AdSense in a state that would cause the "Link Analytics and AdSense" CTA to appear for the admin user
* Sign in with a user with permissions to view the module
* The "Link Analytics and AdSense" CTA should not show up for user with view only access.

## Changelog entry

* Don't show the "Link Analytics and AdSense" CTA on the view-only Dashboard.

**Comment by tofumatt** [comment]
@aaemnnosttv In the Asana task I saw you mentioned that instead of hiding the links we should show an entirely different CTA as the existing one isn't very actionable/usable to a "view-only" dashboard user.

In this case I think we ought not to show anything at all, as the wording and info shown will likely be unclear/confusing to a user not familiar with AdSense setup. I think until AdSense is ready it'd be best not to show these CTAs at all rather than creating new CTAs that basically just tell the "view-only" user that their admin needs to complete some AdSense steps.

What do you think?

**Comment by aaemnnosttv** [comment]
> In this case I think we ought not to show anything at all, as the wording and info shown will likely be unclear/confusing to a user not familiar with AdSense setup. I think until AdSense is ready it'd be best not to show these CTAs at all rather than creating new CTAs that basically just tell the "view-only" user that their admin needs to complete some AdSense steps.

@tofumatt The problem with not showing anything at all is that you may be sending a view-only user to an empty dashboard if AdSense is the only shared module, in which case we'd need a different empty state 😄 We may still need this depending on how other issues go but having a placeholder widget would probably be the simplest solution here.

Alternatively, we could maybe address this on the server side – maybe AdSense should only be considered shareable if it's in a "ready" state? This would also mean that the sharing settings would be unavailable for AdSense until it was ready too.

If we knew the account or site isn't in a "blocked" state, we could treat it as a kind of gathering data state e.g. if AdSense is pending approval, etc. I'm not sure how we would handle things if the site wasn't approved though 🤔 

Thoughts @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt We need to differentiate here:
* We shouldn't show anything at all to view-only users when it comes to CTAs. The "Link Analytics and AdSense" one is a CTA, so this widget shouldn't appear at all in view-only mode.
* However, we should still show zero data states to view-only users. That "No ad impressions yet" box indeed looks like a CTA, but it is something custom that we basically override a regular zero data state with, just in the case of AdSense.

In other words, can we avoid showing the "No ad impressions yet" box for view-only users and instead show a regular zero data state on the main AdSense widget? FWIW, this just makes me think that we should probably change this anyway in light of the `adsenseSetupV2` where that CTA doesn't really make sense anymore. I'll create a separate issue for that.

Anyway, I think we need to keep some version of what is technically a zero data state showing for view-only users, but not the "Link Analytics and AdSense" one.

> Alternatively, we could maybe address this on the server side – maybe AdSense should only be considered shareable if it's in a "ready" state? This would also mean that the sharing settings would be unavailable for AdSense until it was ready too.

What do you mean by "ready" state? Modules can't be shared unless they have their setup completed, no? Again, this CTA is a relic of the AdSense V1 limitations where we didn't really know from the Site Kit side whether the AdSense setup is really ready or not. That is different now with V2 though.

**Comment by aaemnnosttv** [comment]
> What do you mean by "ready" state? Modules can't be shared unless they have their setup completed, no? Again, this CTA is a relic of the AdSense V1 limitations where we didn't really know from the Site Kit side whether the AdSense setup is really ready or not. That is different now with V2 though.

@felixarntz gotcha, I thought we had previously stored the account/site status before as well. You're saying with the v2 setup, AdSense will never be connected until the account + site statuses are in a ready state?

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA update ✅ 

**Verified**

- Verified for admin1.
- Verified for editor with view access.
- Verified for admin with view access.
- Verified for admin2.
- The "Link Analytics and AdSense" CTA is not showing for user with view only access.

<details>

admin 1

![image](https://user-images.githubusercontent.com/94359491/176188658-9cefe1b8-f437-4278-9490-eb743509b4a6.png)

Editor with view access

![image](https://user-images.githubusercontent.com/94359491/176188826-1ce00f4d-7afa-4abc-8a4a-50a863567004.png)

Admin2 with view access

![image](https://user-images.githubusercontent.com/94359491/176188937-5aa6b102-ad23-460d-bbdc-cc717bfbcb1e.png)

Admin 2 (signed in)

![image](https://user-images.githubusercontent.com/94359491/176189089-a10096df-b179-4c90-91d3-e28b0f6522ac.png)

</details>
