### ISSUE TITLE
Remove admin toolbar tabs for services that are not shared

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5348]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202443541768560 please refer to Asana issue for background

If an admin only shares the SC module other users (ie. Editors) will still see an Analytics tab within the admin toolbar. This admin tab displays an Analytics error. 

Rather than displaying the Analytics tab, and associated error, consider removing it. 

[Recording of experience. ](https://recordit.co/Fx3JjrdSc5)

To recreate:
- Share only the SC module with an editor
- Login as the editor
- Use the admin toolbar to view a page
- The below error appears

_Data error in Analytics
Site Kit can’t access the relevant data from Analytics because you haven’t granted all permissions requested during setup._

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/bcb50b6b-cb7e-4116-9cee-01b6bf56fcb8)
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/c62df207-d709-4e89-a409-d6993df75685)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
(It's possible this is related/similar to/the same issue as #5379.)

**Comment by aaemnnosttv** [comment]
View-only users should not see the admin bar (or WP dashboard widget) – this has been fixed in https://github.com/google/site-kit-wp/issues/5202.
