### ISSUE TITLE
The response is not a valid JSON response.

### ISSUE THREAD

**Issue by harshitbits** [google/site-kit-wp#535]
Upon entering the OAuth Credentials in my WordPress plugin dashboard, I am getting this error - 'The response is not a valid JSON response.' 

Please help me with it.

**Comment by jamesozzie** [comment]
@harshitbits Can you please follow the steps below to try and proceed with your Site Kit setup:  
1. Please check your WordPress site settings under "Settings > General" in your WordPress dashboard. Confirm your WordPress Address (URL) and Site Address (URL) match, and ensure they have a https prefix if you are using a https website. 
2. Restart the Site Kit setup process again
3. If the same error appears close the "Couldn't create project" window
4. In the address bar of your window paste the following in: https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
5. Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
6. Press enter, with your cursor in the address bar (as if you are visiting that URL)
7. Press the "GET OAUTH CREDENTIALS" button
8. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

If the above fails please share your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)

Similar issues have been reported previous (#242 & #316). The fixes mentioned might not necessarily apply to your own setup but let me know if any of the above helps resolve your issue.

**Comment by jamesozzie** [comment]
@harshitbits Have you been able to get Site Kit connected after attempting the suggested steps?
