### ISSUE TITLE
Console Errors on the Shared WP for a non-admin user

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5350]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202410303658774 please refer to Asana issue for background

When I login as a non-admin user (i.e. Editor user role) and view the shared dashboard, there are console errors, but the widgets and data load.  No errors appear on the FE.  The errors are:

Google Site Kit API Error method:GET datapoint:settings type:modules identifier:search-console error:"Sorry, you are not allowed to do that."
Google Site Kit API Error method:GET datapoint:settings type:modules identifier:analytics error:"Sorry, you are not allowed to do that."
Google Site Kit API Error method:GET datapoint:settings type:modules identifier:adsense error:"Sorry, you are not allowed to do that."

All 3 of these modules are connected. 

I feel we've had this issue before, and it was fixed, but looks to be appearing again.  

[Recording of experience](https://recordit.co/Ry3fOztyXi)

![image](https://user-images.githubusercontent.com/56588136/173825004-af18ed98-5125-4934-9e12-cfa536b379d4.png)

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/66dc84b4-4025-4bab-8dfe-03ea60ccd542)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
(It's possible this is related/similar to/the same issue as #5379/#5348.)
