### ISSUE TITLE
Goals CTA widget appears on shared dashboard

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5351]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202419766205815 please refer to Asana issue for background

When the non-authenticated user (editor) has access to Analytics, the Goals CTA appears on the shared dashboard. It's my understanding that this should not appear.  

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/64af9268-9d42-473e-8834-c93227d01cd0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics "Goals" CTA should not appear in any shared dashboard context; it should only appear when the user viewing the dashboard has authenticated with Site Kit

## Implementation Brief
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`,
	* Render `CreateGoalCTA` or `CTA` if the user has been authenticated by querying the `core/user` data store via the `isAuthenticated` selector.

### Test Coverage
* No new tests to be added.

## QA Brief

- Ensure that the Goals CTA doesn't appear for non-authenticated users with view-only access to Analytics as mentioned in the AC.
- Ensure that it appears for the authenticated users.

## Changelog entry

* Do not show "Create Goals" widget on shared dashboard.

**Comment by aaemnnosttv** [comment]
> * it should only appear when the user viewing the dashboard has authenticated with Site Kit _and_ has access to the Analytics account

@tofumatt we don't currently have a way to check if the user has that kind of access to the account/property. It may be possible to request through the management API but this would substantially increase the effort needed for this change and we don't do it now so I'm going to remove that detail. We can always revisit it later in a follow-up 👍

**Comment by tofumatt** [comment]
Ah, fair enough on the access bit. In that case, looks good!

IB ✅

**Comment by hussain-t** [comment]
OMG, how did I miss that! Thanks for catching it, @techanvil 👍

**Comment by techanvil** [comment]
Thanks @hussain-t, that's great. Moving back over to QA :)

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified 👍** 

- Verified for admin user when admin user not signed in and access dashboard in view only mode.
- Verified for other non authenticated users.
- Now 'Goals CTA widget' is not appearing for users having only 'View only' access.

<details>

Admin user 'View only' dashboard 

![image](https://user-images.githubusercontent.com/94359491/175280042-c474a030-7789-47c2-a76f-68680f071f46.png)

Editor User 

![image](https://user-images.githubusercontent.com/94359491/175280096-65619f09-e8ae-47cd-8d70-52d5b500aff7.png)

</details>
