### ISSUE TITLE
Confusing UI when Secondary Admin does not have access to a module within Dashboard settings

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5353]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202443611982981 please refer to Asana issue for background

Okay, this is a difficult to explain but here goes.

You have two admin users (admin 1 (the main admin who set up SK) and admin 2 (who is just wanting to view shared dashboard)

Accidentally, admin 1 does not give permission to any modules to administrators. 

Admin 2 logs in to WordPress, and goes to Site Kit Dashboard.  
They see the splash screen saying another admin has set up Site Kit,  but there is no skip link to go to the shared dashboard.  This is simply because admin 1 has not given them permission to any modules. 

This is confusing for admin 2 because there is no UI telling them that admin 1 has to give them permission to be able to view the shared dashboard.  I feel we should update the copy of the splash screen so that admin 2 is informed to chat to with admin 1 about permissions. 

As a non admin user, Site Kit dashboard does not display, if they do not have permissions, and the same could be said about the experience here. Maybe we should have a splash screen telling them that they need to speak to admin 1 for access. 

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
As discussed earlier, this is expected behavior for now. I think we landed on leaving it for now with the assumption that the added feature tours and other language changes would help set expectations here?

**Comment by felixarntz** [comment]
I agree this is expected behavior, but we should probably address https://app.asana.com/0/1202258919887896/1202445809380611/f in order for this to be less of a concern.

@eclarke1 Given this is marked as a P0, should we open an issue for the above Asana task as well? I think once we've improved the language, this issue here is more something that we need to think further about whether we can improve UX, probably no immediate steps to take for the launch.

**Comment by eclarke1** [comment]
Certainly :) I opened an issue for that here #5374 which is a P0. Moving this one to be P1. Thanks so much for weighing in here both.
