### ISSUE TITLE
Modifying date range as non-admin prevents SC widget to load

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5355]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202443434724977

Steps to reproduce:
Login as a non-admin user, having a role which is shared with Search Console only (and no other module).
Visit the dashboard which loads normally.
Change the date range to "Last 90 days".

The Search Console Popular Keywords widget loads indefinitely. Multiple console errors appear as shown in the screenshots below.

Also worth noting that a SC request is sent when date range is changed even if the SC module is not shared with the current viewer.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/a3e093a8-2038-432a-a7b5-ca639565fc63)
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/d9392e23-88b5-4e18-beaa-83de2129daa9)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@jimmymadon I'm not able to reproduce this one. Can you confirm it's still possible on the latest and if so provide steps?

**Comment by jimmymadon** [comment]
@aaemnnosttv @eclarke1 Looks like that issue happened as a one-off and I haven't been able to reproduce this again today. 👍

**Comment by eclarke1** [comment]
Ok great news, let's get this closed then please.
