### ISSUE TITLE
Incorrect Analytics Properties defaulted when Site Kit is Set up, then Reset/Setup 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5356]
## Bug Description

Google Analytics connect service screen does not automatically add the correct UA/GA4 properties when you disconnect/reset Site Kit after setting up Site Kit and Analytics. 

![analytics.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/fc5f3920-a1cb-4c2d-ab69-9e9de96f3c4e)

When I switched to the latest release (1.75.0) the connect service page loads as expected.

No feature flags set with tester plugin.

Please note that even if you do not include Analytics within the Site Kit Set up (from the splash screen) but instead set up Analytics via the CTA on Site Kit Dashboard, the same issue occurs. 

## Steps to reproduce

Here are the steps I took:

1. New site. Set up Site Kit with Analytics.  All set up fine, no issues.
2. Disconnect/Reset Site Kit and redirected to Set up Site Kit Splash page.
3. Reconnect Site Kit with Analytics, and when you get to the connect service page, the primary property is GA4 and nothing in secondary property selected.

I was expecting to see primary property as UA property and secondary property as GA4.  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After resetting Site Kit and connecting Analytics again, if a UA account/property/profile that matches the site is found it should be selected and should appear as the "primary" analytics property selected (eg. at the top of the form).

## Implementation Brief

The problem is related to a flaw in the data request infrastructure that caused non-shared requests to have the client defer set improperly before the `parse_data_response` was called.
* Merge https://github.com/google/site-kit-wp/pull/5367 

### Test Coverage

* No changes

## QA Brief

* Follow the steps to reproduce above, the primary matched property should match a UA Analytics property and the secondary property should also match a respective GA4 property

## Changelog entry

* Fix bug that could cause Analytics properties not to be pre-selected properly during setup.

**Comment by felixarntz** [comment]
I see you self-assigned this @tofumatt but just looked at this too, from my point of view IB + CR ✅

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When a site is set up with Site Kit and Analytics, then reset. The primary matched property defaults in correctly and matches the UA Analytics property and the secondary property also matches a respective GA4 property.
- I also ran this test through with not connecting Analytics in the set up flow after resetting, instead it was connected via the CTA on SK dashboard.  The same behaviour applies as above. 
- Final test, I changed the account / properties in SK settings, and then reset the site, and the primary matched property defaults in correctly and the secondary property also matches a respective GA4 property.

![image](https://user-images.githubusercontent.com/73545194/173972652-cd45f608-64e4-4691-be56-a37d148f81b6.png)
