### ISSUE TITLE
iPhone - Manage view access >Pop up button and CTA UI issues

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5360]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202422111202689 please refer to Asana issue for background

iPhone - Manage view access >Pop up button and CTA getting hide in Safari and not showing on chrome

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/e6c3db87-6c16-4548-ab60-a08739beedcb)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* The footer containing the dialog buttons should always be visible across all breakpoints.
* `react-div-100vh` might be a possible solution.

## Implementation Brief
* Using `assets/sass/components/global/_googlesitekit-dialog.scss`, set
	* `.admin-bar .googlesitekit-dialog` to `top: 46px` instead of `23px`.
	* `.mdc-dialog__container` to `height: 100%` and then `height: auto` as from the tablet breakpoint (`$bp-tablet`)
	* `.mdc-dialog__surface` to `height: 100%` instead of `100vh`
	* `.admin-bar .mdc-dialog__surface` to `height: calc(100% - 46px)` instead of `calc(100vh - 46px)`
* Just FYI, When using `100vh`, the browser's toolbar height is not taken into consideration.

### Test Coverage
* No new tests to be added.

## QA Brief

* Open the sharing settings from the sitekit header on an iPhone using ios 15 or later
* The whole cancel/apply bar should be visible and above the address bar, and not partially hidden, as shown in the screenshot above.
* Repeat the same process in any pre ios 15 browser, ensure that there are no visual changes for the older browsers.

## Changelog entry

* Fix dashboard sharing menu footer visibility issue on iPhone.

**Comment by tofumatt** [comment]
> Just FYI, When using 100vh, the browser's toolbar height is not taken into consideration.

Is that true even when the "old-style" toolbar in iOS Safari is used? Eg. this one:

<img width="386" alt="CleanShot 2022-06-20 at 23 56 31" src="https://user-images.githubusercontent.com/90871/174686675-aea5e9b5-8ed7-4b45-bd47-04ed7ad3e76b.png">

Is the `46px` amount the toolbar height? I'd imagine that might be variable as well, based on system font size, etc.

**Comment by asvinb** [comment]
@tofumatt The 46px is the height of the WordPress admin bar. I think 100vh will work in the older style toolbars but not sure about that TBH. That's why to be on the safer side, I recommend we use 100% instead of 100vh.

**Comment by tofumatt** [comment]
Oh, right on, that makes sense. 😅  In that case: IB ✅
