### ISSUE TITLE
Implement `modules/thank-with-google` JS store foundation

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5365]
Similar to #5364: We should "migrate" the `modules/subscribe-with-google` store to become the foundation for a new `modules/thank-with-google` store.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The JS store `modules/subscribe-with-google` should be consistently renamed to `modules/thank-with-google`.
* The JS file `googlesitekit-modules-subscribe-with-google.js` should be renamed to `googlesitekit-modules-thank-with-google.js`.
    * Its reference in PHP, including the PHP handle, should also be renamed accordingly.
    * No selectors/actions/logic/settings (anything really) should be changed in the module store as part of this issue.
* Any references to the `subscribe-with-google` module slug in JS should be changed to reference the `thank-with-google` module slug (see #5364).
* Any references to the `swgModule` feature flag in JS should be changed to reference the `twgModule` feature flag (see #5364).
* Instead of using the "Google G" as icon for the (previously "Subcribe with Google") module, we should use the new Thank with Google icon which is present e.g. [here in the Figma file](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A9187).
* Any references to any "Subscribe with Google" name permutations in the JS codebase should be changed to refer to the corresponding "Thank with Google" name.
* Any `@since` annotations within the (renamed) `assets/js/modules/thank-with-google` directory should be changed to `n.e.x.t.`, de-facto making this code new.

## Implementation Brief

**Note:** The ACs are very close to code here already, so no need to rehash all of this. Please review the ACs closely together with the relevant code and point out any more complex changes necessary or follow-up questions.

* Rename `assets/js/modules/subscribe-with-google` to `assets/js/modules/thank-with-google`.    
    * Replace every instance of `subscribe-with-google` with `thank-with-google` in code and file names inside the directory. 
    * Update the code in comments accordingly as well where it references `Subscribe with Google`.
* In `assets/js/modules/**thank**-with-google/datastore/constants.js`
    * Export `modules/subscribe-with-google` as `MODULES_THANK_WITH_GOOGLE`. 
    * Delete the `STORE_NAME` constant. 
    * Update all usage of the above `STORE_NAME` with `MODULES_THANK_WITH_GOOGLE` constant.
* In `webpack.config.js` file:
    * Update the `googlesitekit-modules-subscribe-with-google` entry to `googlesitekit-modules-thank-with-google` and use the new path (post rename). 
* In the assets registration `Subscribe_With_Google/Thank_With_Google` class:
    * Update the asset name and path.
* In `assets/js/modules/thank-with-google/index.js`:
    * Update feature flag to use `twgModule`. 
    * Update Icon to the new Thank With Google Logo from the figma file. 
        * Add `thank-with-google.svg` to graphics directory. 
* Finish and merge #5392. 
    * Update failing tests. 

### Test Coverage

* Update failing tests and broken stories. 

## QA Brief

* Once both #5391 and #5392 has been merged:
    * Following QA Brief of #5364 should be sufficient.
    * Module will have the new Tank with Google Icon as par figma design. 
    * QA:Eng All mentions of SWG will be replaced with TWG in the source code. 

## Changelog entry

* Add foundation for new Thank with Google feature (JS).

**Comment by eugene-manuilov** [comment]
@kuasha420, please, do not use "PR as IB" approach for regular tickets, we strongly discourage this approach even if a ticket seems pretty straightforward.

IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@kuasha420 When I am comparing figma for the Thank with Google settings to set up the module, there are no US only and Experimental  labels. Will that be covered in another ticket? I had a quick look but couldn't find any mention. 

![image](https://user-images.githubusercontent.com/73545194/176200871-08caf8c8-4999-40e2-b8d3-30888f86304e.png)

**Verified:**

- The module name "Subscribe with Google" is changed to "Thank with Google".
- The feature flag swgModule is changed to be called twgModule.
- The new module description is: `Let your supporters show appreciation of your work through virtual stickers and personal messages`

**Comment by kuasha420** [comment]
@nfmohit Thanks for stepping in. <3 

@wpdarren This should be good to go now. Cheers.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The module name "Subscribe with Google" is changed to "Thank with Google".
- The feature flag swgModule is changed to be called twgModule.
- The new module description is: `Let your supporters show appreciation of your work through virtual stickers and personal messages`

![image](https://user-images.githubusercontent.com/73545194/176200871-08caf8c8-4999-40e2-b8d3-30888f86304e.png)
