### ISSUE TITLE
Replace $module->get_client() with $module->get_oauth_client_for_current_user()

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#5368]
## Feature Description

We should replace the [`get_client()` function in `Module.php`](https://github.com/google/site-kit-wp/blob/26304ca85a87770a1e837f904cf983ea4d8040dd/includes/Core/Modules/Module.php#L554) with something like `get_oauth_client_for_current_user()`.

See @felixarntz's comment here for context on this change: https://github.com/google/site-kit-wp/pull/5367#discussion_r898482631

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing for now
