### ISSUE TITLE
Site data keeps loading on dashboard if not signed in with my Google account

### ISSUE THREAD

**Issue by michaelH91** [google/site-kit-wp#537]
## Bug Description

Not really sure if it really is a bug or a feature, but:
If I am not signed in with my Google account in the same browser, the data is not shown in the Sitekit dashboard sometimes (spinner keeps loading, but data cannot be shown).

## Additional Context

 - PHP Version: 7.3.6
 - OS: macOS
 - Browser: Firefox Developer Edition v70.0b6
 - Plugin Version: 1.0.0-beta.1.0.6

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@michaelH91 You do not need to be logged into your browser in order for Site Kit to operate. What browser are you using, there can sometimes be issues with in built ad blockers or browser extensions. Can you try opening an incognito browser window (using the Chrome browser) and checking it you can see the various dashboards as normal?

**Comment by michaelH91** [comment]
Thanks @jamesozzie. It happened twice that the dashboard did not load correctly. Since then (and I have been using the plugin intensively), no issues anymore concerning loading the data.
