### ISSUE TITLE
Inaccurate tooltip on 'Who can manage view access' dropdown

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5370]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202420835416767 please refer to Asana issue for background

Here's the scenario:  admin 1 sets up Site Kit and connects all the modules.  In the dashboard sharing settings, they select 'Only me' for search console and analytics under 'who can manage view access' All is good.  Then admin 2 logs in and goes to the dashboard. They can see everything as expected, and then click on the 'view only' button.  They then sign into Google with their google account. They then go to the dashboard sharing settings and see that they are unable to change the permissions for search console and analytics, which is expected BUT, when you hover the 'managed by' tooltip, the message is confusing IMO. 

The tool tip says that 'admin 1 has given permission for all users to all admins (which isn't true) It then says you can change this on the dashboard.  Against the module, the correct text is displayed "Contact managing user to manage view access"  I think the tooltip is confusing. 

Agreed that this message is confusing. Maybe we could change it to something like "Contact [username] to manage view access"?

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/5defbe1d-75d5-4b7f-9a78-72c7e31ee13f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tooltip message when an admin has set a shared module's "manage view access" to "only me" should be updated to: *Contact [username] to change who can manage view access for this module.*

## Implementation Brief

* Change the tooltip at https://github.com/google/site-kit-wp/blob/76e5049ec9f9681478ab36ce37344ec3e008db0d/assets/js/components/dashboard-sharing/DashboardSharingSettings/Module.js#L220 to use the text from the AC, but only when the view access value is "Only me", not when it is set to "All admins".

### Test Coverage

* No new tests are needed for this change.

## QA Brief

* Make sure the `dashboardSharing` feature flag is turned on from the tester plugin.
* Open the Dashboard Sharing settings modal.
* In the "Who can manage view access" column, change the dropdown value to "Only me" for any one or more of the modules.
* Log into the site as a new admin and log into Site Kit with a Google account.
* Ensure that the tooltip in the "Who can manage view access" column text is according to the AC for the modules where "Only me" was selected.

## Changelog entry

* Update the tooltip for the "Managed by..." info icon on the Dashboard Sharing modal, when the module management has been set to "Only me".

**Comment by eugene-manuilov** [comment]
@tofumatt, shouldn't we display that text only if the current sharing management for the module is set to "only me"? In other words, we should keep showing the same `%s has connected this and given managing permissions to all admins. You can change who can view this on the dashboard` message if the current sharing management is set for all admins, right?

**Comment by tofumatt** [comment]
@eugene-manuilov Yes, that's what I wrote in the ACs, but I guess it wasn't clear 😅 

> The tooltip message when an admin has set a shared module's "manage view access" to "only me" should be updated

I've updated it to be a bit more clear.

**Comment by eugene-manuilov** [comment]
Thanks @tofumatt 😊. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When the "Who can manage view access" column value is set to "Only me" and I login as a second admin and connect my Google account, the tooltip in the "Who can manage view access" column text is according to the AC for the modules where "Only me" was selected.

![image](https://user-images.githubusercontent.com/73545194/175282083-ea27ff93-2ba5-4750-b3d3-49de12b6be4b.png)
