### ISSUE TITLE
Update Manage view access warning message

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5371]
## Feature Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202444327251156 please refer to Asana issue for background

When I go to the Dashboard sharing modal as an admin and change an option in a Who can manage view access dropdown, the following warning appears at the bottom of the modal:

"By clicking Apply, you are giving other admins permission to manage view-only access on your behalf to data from the Google services you selected “All Admins” for."

I can't tell if there are words missing here or I'm just having a hard time parsing.  🙂  Either way, I think it could read better. I also think the use of "data from the Google services" is a bit confusing as it could read as somehow related to managing permissions for the service itself, not SK. 

I'd suggest changing to:

"By clicking Apply, you will give other admins of your site permission to manage view-only access to Site Kit Dashboard data from the chosen Google service."

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/9a8146cd-385c-4a8f-a33e-da61476bfe1d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The message that appears when updating "Manage view access warning" should be changed to: "By clicking **Apply**, you will give other authenticated admins of your site permission to manage view-only access to Site Kit Dashboard data from the chosen Google service."

## Implementation Brief

* Update https://github.com/google/site-kit-wp/blob/26304ca85a87770a1e837f904cf983ea4d8040dd/assets/js/components/dashboard-sharing/DashboardSharingSettings/Notice.js#L54 to use the new message in the ACs.

### Test Coverage

* No new tests needed.

## QA Brief

* Enable `dashboardSharing` feature flag from the tester plugin.
* Go to the Site Kit Dashboard.
* Open the Dashboard Sharing settings modal.
* Change the value of a dropdown under the `Who can manage view access` column to `Any admin signed in with Google`.
* Make sure the notice text shown up in the footer is according to the AC.

## Changelog entry

* Update the warning notice that appears on the Dashboard Sharing modal when changing settings.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
Updated wording to clarify "authenticated admins" not all admins.

**Comment by aaemnnosttv** [comment]
Marking this as temporarily blocked by #5374 until that language is solidified.

**Comment by nfmohit** [comment]
The PR attached to this issue updates the copy.

However, I'd like to point out one behaviour which I think is a little misleading.

1. Enable `dashboardSharing` feature flag from the tester plugin.
2. Go to the Site Kit Dashboard.
3. Open the Dashboard Sharing settings modal.
4. Change the value of a dropdown under the Who can manage view access column to Any admin signed in with Google.
5. Save.
6. Open the Dashboard Sharing settings modal again.
7. Change back the recently updated dropdown to `Only me`.
8. Notice that the warning message appears again, which I think it shouldn't.

@aaemnnosttv Any feedback?

**Comment by techanvil** [comment]
> The PR attached to this issue updates the copy.
> 
> However, I'd like to point out one behaviour which I think is a little misleading.
> 
> 1. Enable `dashboardSharing` feature flag from the tester plugin.
> 2. Go to the Site Kit Dashboard.
> 3. Open the Dashboard Sharing settings modal.
> 4. Change the value of a dropdown under the `Who can manage view access` column to `Any admin signed in with Google`.
> 5. Save.
> 6. Open the Dashboard Sharing settings modal again.
> 7. Change back the recently updated dropdown to `Only me`.
> 8. Notice that the warning message appears again, which I think it shouldn't.
> 
> @aaemnnosttv Any feedback?

Hi @nfmohit, this is a good spot, but I believe it's covered by issue https://github.com/google/site-kit-wp/issues/5375 :)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When I change the dropdown under the `Who can manage view access` to `Any admin signed in with Google`, the new notice messages appears in the footer as per the AC. 

![image](https://user-images.githubusercontent.com/73545194/175046423-5baa6bd2-d2bf-45af-a980-ab51fe210339.png)
