### ISSUE TITLE
Dashboard sharing modal state is preserved after closing

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5372]
## Feature Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202436389160092 please refer to Asana issue for background

Similar to module settings which rollback to the initial/saved values/states when saved or exiting edit mode, the sharing settings modal should follow a similar pattern and start from a fresh state every time it is opened.

This means the "current" sharing settings should rollback to the saved values (we already have savedSharingSettings in state for this) and any other UI state should be reset as well (whether or not the user role select is in edit mode, no rows should be disabled, scroll position etc).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Dashboard Sharing settings modal is closed, all of its settings should be rolled back to the current saved values and any other component/UI state should be reset to their initial values.

Note: The implementation should follow a similar pattern to the way module settings work (see `rollbackSettings`)

## Implementation Brief
* Using `assets/js/googlesitekit/modules/datastore/sharing-settings.js`,
	* Add a new action `rollbackSharingSettings` with does not have any parameters and returns the `type` set to a new constant `ROLLBACK_SHARING_SETTINGS` and an empty `payload`.
	* The reducer should set `sharingSettings` to `state.savedSharingSettings` which are the original saved settings.
* Using `assets/js/components/dashboard-sharing/DashboardSharingSettings/Footer.js`,
	* Dispatch the `rollbackSharingSettings` action within the `onCancel` function if the sharing settings have changed.
		* To know if the sharing settings have changed, query the `haveSharingSettingsChanged` selector of the `core/modules` data store.

### Test Coverage
* Add new tests for the `rollbackSharingSettings` action.

## QA Brief

* Enable the `dashboardSharing` feature flag using the tester plugin.
* Go to the Site Kit Dashboard.
* Open the Dashboard Sharing settings modal.
* Make some changes to the roles and management, but do not save.
* Close the modal.
* Open the modal back again, make sure the unsaved settings aren't preserved and have been reset to the previously saved settings.

## Changelog entry

* Rollback any unsaved changes to dashboard sharing settings when closing the dialog.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
(I'm marking this as a good first issue, but it's probably a bit more complicated than other issues. Feel free to take a look at the code mentioned in the IB first before tackling it and no worries if it's a bit too much and you want to unassign yourself 😄)

**Comment by hussain-t** [comment]
@nfmohit, The expected scenario tests are supposed to be done in the `DashboardSharingSettingsButton` component. However, I just realized that we don't have a test file for that component. So, I think it's out of the scope to add tests for the `DashboardSharingSettingsButton` component. My point for adding a test is to have bulletproof testing coverage.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified 👍 

- Verified when user close modal by clicking cancel button.
- Verified when user close modal by clicking outside modal.
- Verified when user close modal by clicking esc button.


https://user-images.githubusercontent.com/94359491/176181147-580e757e-55b7-46b7-936c-9936e42ef5fe.mp4
