### ISSUE TITLE
Overlapping header items

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5373]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202442610474578 please refer to Asana issue for background

With the addition of the dashboard sharing button in the header, there is less room for all the previous items to fit together on medium screens resulting in overlapping text within the header squished dashboard sharing button. To reproduce: resize browser to 600px.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/b0bd1655-d580-4ce9-9715-5397e30151a2)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* Only icons should be displayed in the header up till the 783px breakpoint. (current implementation is up till 600px)
* As from 784px, the icons and their corresponding potential labels should be displayed. (current implementation is as from 601px)

## Implementation Brief
* Remove the CSS for showing/hiding the labels in the header for individual buttons. For e.g:
	* `assets/sass/components/global/_googlesitekit-header.scss` for `.googlesitekit-date-range-selector .mdc-button__label`
	* `assets/sass/components/global/_googlesitekit-entity-search.scss` for `.googlesitekit-entity-search .mdc-button__label`
	* `assets/sass/components/global/_googlesitekit-view-only-menu.scss` for `.googlesitekit-view-only-menu .mdc-button--dropdown .mdc-button__label`
* We have CSS which does the same thing but for individual buttons whereas we can do the same thing with minimal CSS.
* Using `assets/sass/components/global/_googlesitekit-header.scss`,
	* Target the immediate `div > button > .mdc-button__label` of `.googlesitekit-header__children` to:
		* hide them until the `$bp-wpAdminBarTablet` breakpoint.
		* show them as from `$bp-wpAdminBarTablet + 1px` breakpoint.
	* Ensure that no `.mdc-button__label` within dropdowns are affected by that CSS change.

### Test Coverage
* VRT images to be updated accordingly if any.

## QA Brief

- Enable `dashboardSharing` and `unifiedDashboard` feature flags from the tester plugin.
- Go to the Site Kit Dashboard.
- Try checking the header out from different breakpoints and make sure no overlap occurs.
- Make sure the label for the header actions aren't displayed until you reach 784px viewport width.
- Up to 783px viewport width, only icons for the header actions should be displayed (no labels).

## Changelog entry

* Fix the overlapping of some items in the plugin header in small viewports when dashboard sharing is enabled.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Label for the header actions aren't displayed until you reach 784px viewport width.
- Up to 783px viewport width, only icons for the header actions gets display (no labels).

**Note** :  I noticed that from 360px viewport width Site Kit logo gets overlapped by search icon. We have Asana ticket for this issue : https://app.asana.com/0/1202258919887896/1202424752772575
