### ISSUE TITLE
Clarify "All admins" wording in Dashboard Sharing settings

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5374]
## Feature Description

In the "Who can manage view access" section of Dashboard Sharing settings, the wording "All admins" needs more clarification. It is easily misread as "All WordPress admins" but it really means "All WordPress Admins who have authenticated with Site Kit + their Google Account". We should clarify this wording to avoid confusion.

The wording in question:

![CleanShot 2022-06-16 at 16 37 22](https://user-images.githubusercontent.com/90871/174108207-464d3052-0e90-414d-ae0e-a08f1aed7130.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The wording in the "Who can manage view access" dropdown should be updated from "All admins" to "Any admin signed in with Site Kit"

## Implementation Brief

* Update https://github.com/google/site-kit-wp/blob/26304ca85a87770a1e837f904cf983ea4d8040dd/assets/js/components/dashboard-sharing/DashboardSharingSettings/Module.js#L68 to "Any admin signed in with Site Kit"

### Test Coverage

* No news tests needed.

## QA Brief

* Make sure the `dashboardSharing` feature flag is enabled.
* Make sure there is more than one admin in the site (otherwise the "Who can manage view access" column will not show up).
* Go to Google Site Kit Dashboard.
* Open the Dashboard Sharing settings modal.
* Make sure the "All Admins" option now says "Any admin signed in with Google".

## Changelog entry

* Clarify "All admins" wording in Dashboard Sharing settings.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
@tofumatt @felixarntz would it be more clear if we said "any admin signed-in with **Google**" rather than with "Site Kit"? I feel the latter may be a bit easier to misinterpret.

Thoughts @bethanylang ?

**Comment by eclarke1** [comment]
+1 to language being orientated around 'Google' account, makes more sense to me

**Comment by nfmohit** [comment]
The current PR attached to this issue is set to replace "All Admins" with "Any admin signed in with Google" according to the above discussion. I'll be happy to change it if we decide otherwise.

While we're on the discussion about copy, @aaemnnosttv @tofumatt Do you think it is necessary to capitalise (capital for the first letter of every word) this sentence like it was before ("All Admins") and the other option ("Only Me") for consistency?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- the "All Admins" option now says "Any admin signed in with Google".
- tested on desktop and smaller screen sizes, i.e. iOS and Android mobiles. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/174798134-1e687aab-8977-4576-9c65-bf78439b535b.png)
![image](https://user-images.githubusercontent.com/73545194/174798161-7a2121f6-3838-4e28-9b21-64011c313c4c.png)



</details>
