### ISSUE TITLE
Console warning when hovering the dashboard sharing icon in the header

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5377]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202442610474564 please refer to Asana issue for background

A console warning is displayed when hovering the dashboard sharing icon in the header. 
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/69e3b4af-6a88-4951-9e6e-8c9580e9f594)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* Hovering the dashboard sharing icon in the header should not result in any warnings/errors in the console.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of #5378
