### ISSUE TITLE
Data requests fail on shared dashboard for connected but non-shared modules

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5379]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202410303658780 please refer to Asana issue for background

The main admin has connected all modules, but has not given access to all of them for administrators. When the second admin logs in and goes to the shared dashboard, all of the widgets load as expected, but errors appear in the console:

`Google Site Kit API Error method:GET datapoint:report type:modules identifier:analytics error:"Site Kit can’t access the relevant data from Analytics because you haven’t granted all permissions requested during setup."`

The message appears for each module that they do not have permission to view.

No errors appear within the dashboard itself. 

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/7e06fd5c-f9a5-45ba-9f32-e407d1f75cd9)

### Steps to Reproduce

1. Enable Dashboard Sharing
2. Using the "main admin", connect all modules, but do no grant access for all modules to others administrators. (Eg. Give all admins access to a single module like Search Console, but not Analytics or other modules)
3. Sign in as a second admin and visit the shared dashboard
4. All of the widgets load as expected, but errors appear in the browser console:

![image](https://user-images.githubusercontent.com/90871/174093467-e2f7ef88-642f-40e3-8ba2-b32ea8c6070d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Browser/console errors should not appear in the console when viewing the shared dashboard as a second admin that doesn't have access to every module on the dashboard.
* The cause of this is requests being sent to our REST API (Analytics endpoint) when Analytics is not shared with this user, so requests should not be made for modules the user doesn't have access to on the shared dashboard.

## Implementation Brief

**Preventing Analytics `getReport` API requests if the Analytics module is not shared to view**

- To check the user has access to view Analytics, using the `canViewSharedModule( 'analytics' )` selector, conditionally call the `getReport`, `getGoals`, `isGatheringData`, and `hasZeroData` selectors along with the existing conditions if there are any in the following files:
  * `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js`
  * `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`
  * `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js`
  * `assets/js/components/notifications/ZeroDataStateNotifications/index.js`
  * See:
  https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js#L79-L85

- Note: Currently, if the user doesn’t have access to Analytics, it still shows `Analytics gathering Data`. Applying the changes above in the `ZeroDataStateNotifications` will fix the problem. Refer to the following screenshot:

![Screenshot 2022-06-20 at 11 06 06 AM](https://user-images.githubusercontent.com/24408261/174548585-a473d197-860a-4a4b-b95e-dcd0f2e5657b.png)

- Note: There is a request failure for Search Console settings; however, this is being implemented in #5310 

- Refer to the WIP [draft PR](https://github.com/google/site-kit-wp/pull/5395).

### Test Coverage

- No new tests are to be added.

## QA Brief

- Follow the steps to reproduce the issue.
- Verify there are no `Analytics` API request failures/errors on the console and the network tab if the user has view-only access.
- Note: There is a request failure for Search Console settings; however, this is being implemented in #5310 

## Changelog entry

* Prevent data requests on shared dashboard for connected but non-shared modules.

**Comment by tofumatt** [comment]
IB looks good _except_ for this bit:

> Note: Fixing the above in the `ZeroDataStateNotifications` component will fix displaying the “Analytics Gathering Data” notification if the module is not shared.

We should update that component's logic as part of the IB; I presume the reason it's showing both "Search Console and Analytics" because Analytics is considered "connected" even if the current user doesn't have access to it: https://github.com/google/site-kit-wp/blob/76e5049ec9f9681478ab36ce37344ec3e008db0d/assets/js/components/notifications/ZeroDataStateNotifications/index.js#L40

Let's update that logic to check for a module being connected AND, if in a sharing `viewContext`, the user having access. Does that make sense?

We shouldn't be showing users info about modules they don't have access to, that's very confusing. If we update that logic we'll prevent a new bug from occurring with this fix 🙂

**Comment by hussain-t** [comment]
>Let's update that logic to check for a module being connected AND, if in a sharing viewContext, the user having access. Does that make sense?

Thanks, @tofumatt; in the `ZeroDataStateNotifications` component, we are already checking for `isAnalyticsConnected`. We also have to check if the user has access to view Analytics using the `canViewSharedModule` as I mentioned in the IB. With the `canViewSharedModule,` we can already check if the user has `viewOnly` within the `canViewSharedModule` selector. Please see: 

https://github.com/google/site-kit-wp/blob/d5403041feda1c06c954a86fe32bb814b20f74f8/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js#L79-L85

I have slightly tweaked the IB in case the previous one wasn't clear enough.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When on shared dashboard: Confirmed that no errors appear in the console or network. 
- When on shared dashboard: Checked that Analytics does not appear on the notification when it is not connected. 

![image](https://user-images.githubusercontent.com/73545194/175932402-6fae5474-9a43-4189-8c70-e1040467165a.png)
