### ISSUE TITLE
Misaligned information in the view-only menu

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#5381]
## Bug Description
When there are varying user names length in the view only menu, the module name and user names are not longer aligned.

## Steps to reproduce

1. Add another administrator and login to the view only dashboard.
2. Click on the view only menu.
3. Notice how the module names and module owners within the menu are misaligned.

## Screenshots
![image](https://user-images.githubusercontent.com/31818/174037780-99dd27f3-9db6-4242-a598-bd6a01d77eda.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* The width of the module icon, module name and module owner within the view only menu should be as per the Figma designs, i.e 24px for the icon, 105px for the module name and the rest for the module owner.
* All the information within the "Shared Services" section within the view only menu should be aligned.

## Implementation Brief
* Using `assets/js/components/ViewOnlyMenu/Service.js`,
	* Wrap the `Icon` component within a `span` tag with the `googlesitekit-view-only-menu__service--icon` class name.
* Using `assets/sass/components/global/_googlesitekit-view-only-menu.scss`,
	* Add styles to `googlesitekit-view-only-menu__service--icon`, `flex: 0 0 24px;`
	* Add `gap: 8px` to `.googlesitekit-view-only-menu__service`.
	* Remove the `margin-right: 8px` from `.googlesitekit-view-only-menu__service svg`.
	* Set `flex: 0 0 100px;` to `.googlesitekit-view-only-menu__service--name`.
	* Set `flex: 1` to `.googlesitekit-view-only-menu__service--owner`.

### Test Coverage
* No new tests to be added.

## QA Brief

* Follow the steps in the "Steps to reproduce" section above.
* Make sure the main admin (who sets up Dashboard Sharing) has a long username for the alignment issue to appear.
* Ensure that the alignment issue doesn't exist anymore.
* Ensure that the width of the service name is limited to 100px only when it is a user who can authenticate (e.g. an admin user), otherwise, it should be able to take as much space as it needs.

## Changelog entry

* Fix service information alignment in the view-only menu.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- the alignment issue doesn't exist anymore for long usernames. Tried this with a few different combinations and no issues with the alignment arise. I also tested this on various screen sizes including desktop, mobile devices. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/174803384-e6f9348c-b7ac-419f-94d2-1b7f169a0cdf.png)

![image](https://user-images.githubusercontent.com/73545194/174803408-b156f47f-d684-403f-9930-0aab2e4b18f0.png)

</details>

**Comment by nfmohit** [comment]
> As noted by @aaemnnosttv , only admins can see the module owner. Non-admin view-only user do not see that information which results in the module name width set to `100px` as per the IB. We should tweak the implementation even when a non-admin view-only user views the menu, the module name takes the whole available space (not limited to 100px). @nfmohit Can you check it out?

Thank you for pointing it out here @asvinb and for noticing this @aaemnnosttv! I've opened a new PR that addresses this.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit @techanvil this passes the QAB/comment but I just have a small observation and maybe this is best in a new ticket at this point but wanted to check with you. 

When you have a long name with 25 characters or longer, it does cause problems with the layout. I am wondering if we should cut the username off at a certain about of characters with ellipsis like we do on other parts of the plugin. As you can see from the screenshot on desktop it goes right to the edge.  (and the same with mobile.) 

I realise 25 characters is a silly amount of characters for a username, but users be users! 😄  Thoughts?

<details>
 <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/73545194/176890040-3d85af01-2bc2-4a41-9b65-eadecb9344fd.png)

</details>

**Verified:**

- the alignment issue doesn't exist anymore for long usernames. Tried this with a few different combinations and no issues with the alignment arise. I also tested this on various screen sizes including desktop, mobile devices.
- made sure that when logged in as a non admin user, the module is displayed amongst the whole area as [per comment](https://github.com/google/site-kit-wp/issues/5381#issuecomment-1170860100)

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/176889326-a21e31bf-98f6-46c0-b63f-4b47148553dd.png)
![image](https://user-images.githubusercontent.com/73545194/176889345-f6c5480d-1735-4967-9a51-4c589894bcbf.png)

</details>

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- the alignment issue doesn't exist anymore for long usernames. Tried this with a few different combinations and no issues with the alignment arise. I also tested this on various screen sizes including desktop, mobile devices.
- made sure that when logged in as a non admin user, the module is displayed amongst the whole area as [per comment](https://github.com/google/site-kit-wp/issues/5381#issuecomment-1170860100)

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/176889326-a21e31bf-98f6-46c0-b63f-4b47148553dd.png)
![image](https://user-images.githubusercontent.com/73545194/176889345-f6c5480d-1735-4967-9a51-4c589894bcbf.png)

</details>
