### ISSUE TITLE
Shared requests should not be attempted for recoverable modules

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5383]
## Bug Description

If a request for module data which is shared by its owner happens to be for a module which is also recoverable, it should not be attempted although this is currently what's happening.

## Steps to reproduce

1. Connect with Admin A
2. Share Search Console with Admins
3. Disconnect Admin A
4. Connect with Admin B
5. See data errors about lack of granted scopes, even though the current user has the scopes

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/174143256-fe2087e9-f14a-4d55-9df9-aa5eb5b30fad.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Module data requests for recoverable modules should not qualify to be executed as a shared request 

## Implementation Brief

* Define a new public `Module::is_recoverable` method, similar to `is_shareable`
* Return a boolean from a new filter `googlesitekit_is_module_recoverable` which defaults to `false` and passes through its slug as the only extra parameter
* Update `Modules` to hook into this filter and run the callback through its `is_module_recoverable` method
* Update the condition in `Module::get_oauth_client_for_datapoint` to additionally require the module is not recoverable (using the new method) in order to return the owner oauth client
	* Additionally, ensure the owner's client satisfies the base scopes (using `validate_base_scopes`) as a final check before returning, otherwise falling back to the default client
* Finish and merge https://github.com/google/site-kit-wp/pull/5384

### Test Coverage

* Add test for added `is_recoverable` method

## QA Brief

* Follow steps to reproduce above before and after to ensure the request works as expected when the current admin has the granted scopes if the module is recoverable

## Changelog entry

* Do not attempt to make requests for module data where the module is shared and also recoverable.

**Comment by mohitwp** [comment]
### QA Update ❌ 

@aaemnnosttv @techanvil 

**Verified** 

- Reproduced error successfully on main branch.
- Now, data errors about lack of granted scopes is not showing on the development branch.
- User is getting option to recover. 

**ISSUE**

Admin 2 is not getting access to manage view access after recovering.

![image](https://user-images.githubusercontent.com/94359491/175037115-2d69d84f-5fe4-422f-84e7-447b5e99f844.png)

https://user-images.githubusercontent.com/94359491/175037151-a12618a6-7702-4281-beaf-749262294c69.mp4

**Comment by aaemnnosttv** [comment]
@mohitwp this issue would have no effect on the sharing settings interface it only changes how requests are executed on the backend.

@techanvil did something change around module recovery where the owner is no longer being updated?

**Comment by techanvil** [comment]
> @techanvil did something change around module recovery where the owner is no longer being updated?

Nothing that I am aware of, I just tried recovering a module locally and the owner ID updated OK.

**Comment by mohitwp** [comment]
Thank you @aaemnnosttv 

### QA Update ✅ 


**Verified**

- Reproduced error successfully on main branch.
- Now, data errors about lack of granted scopes is not showing on the development branch.
- User is getting option to recover.
- Issue mentioned [here](https://github.com/google/site-kit-wp/issues/5383#issuecomment-1163080895) will get resolve by
[#5416](https://github.com/google/site-kit-wp/issues/5416)


https://user-images.githubusercontent.com/94359491/175037151-a12618a6-7702-4281-beaf-749262294c69.mp4
