### ISSUE TITLE
Widgets don't load when URL has no initial hash and traffic section isn't available

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5388]
## Bug Description

The dashboard navigation introduced with the unified dashboard controls the hash in the URL and [if not set, sets it to the fist section: `#traffic`](https://github.com/google/site-kit-wp/blob/76e5049ec9f9681478ab36ce37344ec3e008db0d/assets/js/components/DashboardNavigation.js#L164-L170). Until now, this has worked fine because all users are guaranteed to have that section available. With dashboard sharing, it's possible that the Traffic section may not be present if Search Console and Analytics are not shared with a user's role.

In this situation, a URL without a hash will still get `#traffic` set by default which also has the effect of "activating" the `useInViewSelect` hooks that all API/reporting selectors use for lazy-loading. This results in the first actually-in-view section not being active.

This is not 100% reproducible and may also involve a race condition or other factors like not scrolling after the initial load.

## Steps to reproduce

1. Setup Site Kit and share only Idea Hub with a non-admin role
2. Sign in as the non-admin user and go to the SK dashboard
3. See Idea Hub stuck in a loading state
4. Click the Content section tab to activate it
5. See Idea Hub load as usual

## Screenshots

![](https://camo.githubusercontent.com/f639e37e5c7fccfc2c535e771a418ad345e782b992e141827968565f1f93867e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565326164333830336333373435363932333164386364372f61643338623563302d613065322d346235362d383366312d303562623733336634623361)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If no hash is present in the URL on the SK dashboard, the initial hash should be set to the first available section  
Note this may not be available right away so async resolution may be needed

## Implementation Brief
* Move and rename the following files to the new folder `assets/js/components/DashboardNavigation`.
	* `assets/js/components/DashboardNavigation.js` to `assets/js/components/DashboardNavigation/Navigation.js`, renaming the component in the process.
	* `assets/js/components/DashboardNavigation.stories.js` to `assets/js/components/DashboardNavigation/index.stories.js`
	* `assets/js/components/DashboardNavigation.test.js` to `assets/js/components/DashboardNavigation/index.test.js`
* Create new file `assets/js/components/DashboardNavigation/index.js` which does the following:
	* Get the viewable modules via the `getViewableModules` selection of the `core/user` data store. Refer to `viewableModules` in `assets/js/components/DashboardNavigation/Navigation.js`
	* Return `null` if `getViewableModules` is `undefined`, else return `Navigation` imported from `assets/js/components/DashboardNavigation/Navigation.js`
* Using `assets/js/components/DashboardNavigation/Navigation.js`,
	* Add a new function `getDefaultChipID` which does the following:
		* If `viewOnlyDashboard` is `false`, return `ANCHOR_ID_TRAFFIC`
		* if `showTraffic` is `true`, return `ANCHOR_ID_TRAFFIC`
		* if `showContent` is `true`, return `ANCHOR_ID_CONTENT`
		* if `showSpeed` is `true`, return `ANCHOR_ID_SPEED`
		* if `showMonetization` is `true`, return `ANCHOR_ID_MONETIZATION`
	* Add another function `isValidChipID` which accepts a parameter, `chipID`, which returns `true` based on the following:
		* if `showTraffic` is `true` and `chipID` is `ANCHOR_ID_TRAFFIC`
		* if `showContent` is `true` and `chipID` is `ANCHOR_ID_CONTENT`
		* if `showSpeed` is `true` and `chipID` is `ANCHOR_ID_SPEED`
		* if `showMonetization` is `true` and `chipID` is `ANCHOR_ID_MONETIZATION`
		* else return `false`.
	* Update the code within `useMount`,
		* when there's no `initialHash`, instead of hard coding the hash to `ANCHOR_ID_TRAFFIC`, get the default chip ID from `getDefaultChipID` and update the hash to the default chip ID.
		* if there is an initial hash, check if it's a valid chip ID via the `isValidChipID`. If the chip ID is not valid, update the hash to the default chip ID.

### Test Coverage
* Add new tests `assets/js/components/DashboardNavigation/index.test.js` to make sure the first chip ID is selected when no hash is selected

## QA Brief

* Enable Dashboard sharing and share only PageSpeed with all other users.
* Sign in as a user who can view a shared dashboard with only PageSpeed Insights shared.
* Navigate to the Site Kit dashboard.
* Notice the URL hash is `#speed` not `#traffic`.

Using a normal Site Kit admin, the URL hash should still start with `#traffic` when viewing the Site Kit dashboard.

## Changelog entry

* Fix default Dashboard Navigation section for the view-only Dashboard.

**Comment by wpdarren** [comment]
### QA Update: ⚠️

@tofumatt this passes the QAB, but going back to the original issue with Idea Hub, I decided to run through some additional testing.  The Idea Hub widget did load with the initial `content` hash.  I noticed two console errors though that don't appear when PageSpeed is the only permitted module. 

`/index.php/wp-json/google-site-kit/v1/modules/search-console/data/searchanalytics?dimensions=date&startDate=2022-05-02&endDate=2022-06-26&_locale=user:1   Failed to load resource: the server responded with a status of 403 ()`

`googlesitekit-api-dafe70321f686df3fda1.js:3 Google Site Kit API Error method:GET datapoint:searchanalytics type:modules identifier:search-console error:"Site Kit can’t access the relevant data from Search Console because you haven’t granted all permissions requested during setup." (anonymous) @ googlesitekit-api-dafe70321f686df3fda1.js:3`

![image](https://user-images.githubusercontent.com/73545194/175954347-490c13df-75ee-4657-9361-fe752f370811.png)

Should these errors be in appearing in the console? 🤔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- URL hash appears for #speed as a user who can view a shared dashboard with only PageSpeed Insights shared.
- I also tested the scenario in the initial description around Idea Hub and the widget loaded as expected. There are two console errors but it appears these will be picked up as part of #5310. 
- Using a normal Site Kit admin, the URL hash starts with #traffic when viewing the Site Kit dashboard.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/176204669-776f5bba-7b4f-4ce0-b1eb-ebc467f7b96b.png)
![image](https://user-images.githubusercontent.com/73545194/176205076-6dd8e974-690f-41cb-8c5a-83dc8d349233.png)

</details>
