### ISSUE TITLE
Unknown Error (code: redirect_uri_mismatch)

### ISSUE THREAD

**Issue by thano** [google/site-kit-wp#539]
## Bug Description

I tried to connect Site Kit using my account. A redirect_uri_mismatch ensues when I tried connecting it via the email account I use. 

I have done the following:
- verified my site using html.
- connected both analytics and console
- used https
## Steps to reproduce

1. Go to your Sitekit Dashboard.
2. Input client ID and follow directions until done.
## Screenshots
![image](https://user-images.githubusercontent.com/7008492/64936001-6f895800-d886-11e9-93f8-32ffa1628dad.png)
![image](https://user-images.githubusercontent.com/7008492/64936040-95aef800-d886-11e9-8a3e-5f1e9dfa6677.png)

## Additional Context

 - PHP Version: 5.6.4
 - OS: linux x86
 - Browser chrome
 - Plugin Version Version 1.0.0-beta.1.0.6

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@thano Can you please check your WordPress site settings under "Settings > General" in your WordPress dashboard. Confirm your WordPress Address (URL) and Site Address (URL) match, and ensure they have a https prefix if you are using a https website. 

If you have already checked and both addresses match please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard and we can troubleshoot further.

**Comment by thano** [comment]
I see. It's now fixed. The WordPress site settings was the culprit. Thank
you!
