### ISSUE TITLE
Conflict with loginpress social login

### ISSUE THREAD

**Issue by schawki** [google/site-kit-wp#540]
## Bug Description

When I activate SiteKit and LoginPress Social Login, Social Login with Gmail doesn't work.
It seems that it keeps redirecting me again and again for authentication.
When I deactivate the Site Kit plugin, LoginPress Social Login works perfectly.

Google Site Kit prevents LoginPress Social Login with Gmail to work.

## Steps to reproduce

To reproduce the bug, you have to:
1. install SiteKit and connect it to the Google Console.
2. Then Install LoginPress and LoginPress Pro.
3. Activate Social Login in LoginPress Pro and configure it with Google Console by creating OAuth credentials in Google Console.
4. Activate Social Login with Gmail in LoginPress Pro and set up the newly created credentials.
5. Go to the connection page on the website (wp-login.php) and try to connect with Gmail.
6. You'll get a message saying that the website has technical issues.

## Additional Context

 - PHP Version: 7.1.16
 - OS: Os X 10.14.6
 - Browser Chrome, Safari, Firefox
 - WordPress version: 5.2.3
 - Plugin Version
 Site Kit by Google Version 1.0.0-beta.1.0.6
 LoginPress Version 1.3.1
 LoginPress Pro Version 2.2.1
 LoginPress - Social Login Version 1.1.0
 - Device: MacBook Pro 15" (early 2013)

I contacted WP Brigade, the editor of LoginPress, and gave them access to a staging site, but they had no luck fixing the issue. They answered that the problem is in the Site Kit plugin that is in Beta and that I should report the conflict in here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by abdulwahab610** [comment]
Hi,

I am one of the developers of [LoginPress](https://wordpress.org/plugins/loginpress/) & @schawki  reported an issue if **Site Kit by Google** is activated, user cannot able to login using Google account. When user trying to log in, s/he considered connected but stay on the same authenticate page and auth again and again in a loop.
When we deactivate the **Site Kit** plugin. A user can sign in with Google account perfectly.
In our environment, We're using [Google SDK](https://github.com/googleapis/google-api-php-client) v2.4.0

Kindly debug the issue which helps to limit conflicts with other plugins.

Thank you.
-Abdul Wahab.

**Comment by aaemnnosttv** [comment]
Hi @abdulwahab610 - _LoginPress Pro_ and _LoginPress - Social Login_ are behind a paywall which is preventing us from testing them. Can you please provide us with an account on https://wpbrigade.com/account/ or zip files we can use for testing? If so, please let us know the best way to contact you privately.

**Comment by jamesozzie** [comment]
Hi all, Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. Where we would be happy to assist from there
