### ISSUE TITLE
Revise Submit button wording for the final step in saving module settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5401]
## Bug Description

This was identified during the bug bash by James, as a post launch issue for AdSense Setup Improvement.  If a user has an approved AdSense account and their site is also approved (ready) they'll be prompted to "Configure AdSense", before the service is connected.  As there isn't any configuration applicable consider changing the wording to "Connect AdSense" or "Complete setup".

Recording of experience [here](https://recordit.co/pslDn0Q2oU). 

Asana ticket can be found here https://app.asana.com/0/1202175292782289/1202322830239183/f

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update the wording of the button which finishes a successful setup for all of our modules, ie. Google Analytics, AdSense and Tag Manager to say "Complete setup" (instead of "Configure <module name>" or "Confirm & Continue").

## Implementation Brief

* Within `assets/js/modules/analytics/components/setup/SetupForm.js`, `assets/js/modules/analytics/components/setup/SetupForm.js` (if #7929 is already merged), `assets/js/modules/adsense/components/setup/SetupAccountSite/Ready.js` and `assets/js/modules/tagmanager/components/setup/SetupForm.js`:
    * Change the submit button text to what is in the AC instead of `Configure Analytics`, `Configure AdSense` and `Confirm & Continue`.

### Test Coverage

* No new tests required but update VRT reference images and JS test snapshots as required.

## QA Brief

- Set up Site Kit.
- Set up the Analytics, AdSense, and Tag Manager modules.
- In the setup screen for each of these modules, verify that the setup form's submit button says "Complete setup" as the wording.

## Changelog entry

* Update setup buttons to use consistent language.

**Comment by ivonac4** [comment]
@marrrmarrr  Are you still planning to review this soon? If not, can you please unassign yourself so someone else can pick up? Thank you!

**Comment by ivonac4** [comment]
@marrrmarrr Sorry, I misread the comments here, I realize now it is on you to review it. Do you mind taking a look at it when you have time? Thanks!

**Comment by eugene-manuilov** [comment]
> * Update the wording of the button which finishes a successful setup for both, Google Analytics and AdSense to say "Complete set up" (instead of "Configure ").

@aaemnnosttv, I am not sure that we should change the button label for the Analytics setup form here. The intention of this ticket is to adjust the language for the AdSense setup process to have a more accurate button label when the actual configuration of the AdSense module is already completed and we need to do the final step to connect the module. In the Analytics module the setup flow is different and has only one step to save configuration and having the "Configure Analytics" label makes sense to me. What do you think?

**Comment by jamesozzie** [comment]
@eugene-manuilov @aaemnnosttv The difference with the AdSense module "Configure..." label compared to the Analytics module, is that you are configuring Analytics. There are no configurations applicable when setting up AdSense. See below images:

**AdSense module setup** - No configurations applicable
<kbd>![image](https://github.com/google/site-kit-wp/assets/41326532/42505c09-42a2-4cbe-aa40-1fda2e043822)

**Analytics module setup** - Configurations can be applied on this screen
<kbd>![image](https://github.com/google/site-kit-wp/assets/41326532/7813c691-8468-4b6a-88df-98d113f4edf4)

Considering there are AdSense configurations ([screenshot](https://i.imgur.com/YBDR9Lp.png)), maybe we could allow configuration on this screen, at least the option to enable/disable ads for logged in users. 

Maybe we could hold off on this issue and allow users to select AdSense configurations on this initial setup screen? I'm happy to open an issue for this if so.

**Comment by bethanylang** [comment]
@aaemnnosttv I meant to chime in about that! "Setup" is the noun and "set up" is the verb, so it should be "setup" here.  :)

**Comment by marrrmarrr** [comment]
@jimmymadon I think "complete setup" is a good option here.

**Comment by eugene-manuilov** [comment]
Thanks, @jimmymadon. AC and IB 🌶️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that now the wording of the button which finishes a successful setup for all of our modules, ie. Google Analytics, AdSense and Tag Manager updated to say "Complete setup" (instead of "Configure " or "Confirm & Continue").

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/035dd728-8800-467a-8fdd-100004d9e484)

![image](https://github.com/google/site-kit-wp/assets/94359491/10253d6a-4b95-4aa9-ade6-c7367543a3c0)

![image](https://github.com/google/site-kit-wp/assets/94359491/4a453cdb-49d2-478a-8b4f-b5bfe427c5f3)

</details>
