### ISSUE TITLE
Fix broken stories for Gathering Data

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5404]
## Bug Description

The `DashboardOverallPageMetricsWidget` stories for gathering data states are no longer showing properly. This is due to an invalid report being received in Storybook.

## Steps to reproduce

https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--gathering-data-zero-data-states

## Screenshots

<img width="916" alt="image" src="https://user-images.githubusercontent.com/1621608/174874299-2c3f940f-2398-4a11-aa15-82271d28ebff.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All "gathering data" stories should show a gathering data state

## Implementation Brief

* Update use of `receiveGetReport` in `DashboardOverallPageMetricsWidget` to receive an empty array instead of an empty object
	* No other improper uses found when reviewing calls to `receiveGetReport`
* Merge #5405 

### Test Coverage

* No changes

## QA Brief

* This change only affects Storybook, no changes to production code have been made
* Once merged, the fix should be verifiable in Storybook here: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--gathering-data-zero-data-states

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅ 

I'll code review this one as well 👍🏻

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- All "gathering data" stories show a gathering data state on [Storybook](All "gathering data" stories should show a gathering data state)
- Checked[ this](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--gathering-data-zero-data-states)  and [this](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--gathering-data-entity-url-zero-data-states) gathering state story. 

![image](https://user-images.githubusercontent.com/73545194/175007967-34c190c5-4386-4daf-918a-f7c8a92b72d4.png)
