### ISSUE TITLE
Replace use of `php-actions/composer` action

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5411]
## Feature Description

Our GitHub actions currently have an inconsistency regarding the way they install PHP dependencies with Composer. Some jobs use the `php-actions/composer` action, while others leverage `setup-php`.

While a dedicated action sounds like the better option, it takes much longer to run, often close to 2m compared to ~30s for the alternative.

![image](https://user-images.githubusercontent.com/1621608/175043473-720f7232-5b2b-49bf-851d-a1de91635b30.png)

**E2E job run**
![image](https://user-images.githubusercontent.com/1621608/175043502-d99722da-38f7-4cbd-af1f-d7c3751cb411.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Composer Install steps of all GitHub actions should no longer use `php-actions/composer` and instead leverage the `setup-php` action as already done in some jobs
	*  Note: composer install must be run with PHP v7.2 or higher due to PHP Scoper – for jobs that require a lower version of PHP, ensure this is set properly after installing dependencies. All plugin dependencies will be installed with compatibility with PHP 5.6, so this requirement will not affect production code. 

## Implementation Brief
* Using `.github/workflows/zips.yml`,
	* Update the `Composer Install` step to use `setup-php` similar to how it's done in: `.github/workflows/e2e-tests-wp-4-7.yml`.
		* `php-version` should be set to `7.3`
		* `tools` set to `composer:2.1`

### Test Coverage
* No new tests to be added.

### QA:Eng
- Verify that the [`Plugin Zip Files` workflow](https://github.com/google/site-kit-wp/actions/workflows/zips.yml) doesn't fail with any error related to the removal of the `php-actions/composer` action and addition of the `shivammathur/setup-php` action after merge.

## Changelog entry

* N/A.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by asvinb** [comment]
### QA: ✅ 

- Plugin Zip Files workflow doesn't fail
- Composer install doesn't fail

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/31818/193086430-2a6ea0c4-b888-4b96-9731-b9314b6ddea6.png">
