### ISSUE TITLE
Include a notification or warning if user is asked to re-connect Site Kit but then chooses a different Google account 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5413]
## Bug Description

There are various circumstances whereby a user may be asked to re-do plugin setup. See screenshot below with one such example. 

In such scenarios some of the modules may already be connected. If a user has multiple Google accounts, and they're asked to re-do plugin set up they may then choose another Google account, not the one initially used to set up Site Kit. This may result in permissions errors for the other connected modules. 

If there is a way to identify that a particular administrator has been asked to re-do plugin set up give them a pre notification of the Google account used, or provide another notification or warning during or after set up, that can result in less confusion. 

![image](https://user-images.githubusercontent.com/41326532/175100937-39eaf01b-52c7-4cbc-b331-7f5594590901.png)

![image](https://user-images.githubusercontent.com/41326532/175102019-15662d3c-0999-4d69-a333-c7c9473dcbf2.png)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is essentially the same as #5414, just though a different scenario. It's possible to change the Google account any time the user goes through oAuth. I'm going to close this one in favor of #5414 as that one is more specific as to how that is possible.
