### ISSUE TITLE
Improvements to users connecting a secondary module but using a different Google account

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5414]
## Bug Description

If a user chooses to connect secondary module (ie. Analytics), but selects a different Google account to the one used initially during Site Kit set up, they will be directed to set up Site Kit once more - using this latest Google account used to connect the secondary module. This can result in dashboard and permissions errors, as some of the other secondary modules (ie. Adsense) may have been previously connected using the Google account initially used during Site Kit setup. The plugin connected Google account has therefore been changed, but some modules remain connected and associated with a different Google. 

Improve this behavior somehow by checking the Google account used to set up secondary modules, or by adding a post connection message indicating that the module was set up using a different Google account initially used to set up Site Kit. Something similar to the below may be more insightful:

"_It looks like you used/have selected a Google account to connect <** AdSense | Analytics | module ** >" to that which you used to initially set up the plugin. You should be using the same Google account for setting up Site Kit and to connect all the available modules._"

Note that we've already improved this experience within OAuth, by limiting the Google account displayed to the Google account initially used to set up Site Kit. This however, doesn't stop users choosing to use another Google account via the ["Use another account" option during Oauth account selection](https://i.imgur.com/cPGAq0q.png). 

Any solution or improvement here could be replicated if possible for another similar issue, https://github.com/google/site-kit-wp/issues/5413

## Steps to reproduce

1. Setup Site Kit with one Google account, including the Analytics module. When selecting the Analytics property ensure only this Google account has access.
2. Connect the AdSense module, but when connecting choose to connect via another Google account
3. Revisit the Site Kit dashboard, and a permissions notice will appear within the Analytics module (which was previously connected, although through the initial Google account)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
> Note that we've already improved this experience within OAuth, by limiting the Google account displayed to the Google account initially used to set up Site Kit. This however, doesn't stop users choosing to use another Google account via the ["Use another account" option during Oauth account selection](https://i.imgur.com/cPGAq0q.png).

The important thing here is that choosing another Google account is already something you need to go out of your way to do – we already use the login hint feature to actively suggest the same Google account; but more importantly, the user will need to go through the same initial setup flow just as if they disconnected and reconnected with a different account only in a more efficient way.

I'm not sure there is anything much to fix here as this could be something a user does intentionally if they initially set up the plugin with the wrong Google account. This should also be less of a concern with dashboard sharing.

There's nothing technically wrong with changing your connected Google account so long as all of the usual requirements are met (which they are). Problems with access to Google service entities is something that can happen without changing your account. If a user changes their connected Google account that results in permissions errors, I'm not sure additional messaging is necessary.

**Comment by aaemnnosttv** [comment]
After reviewing today, we decided that this is okay for now and that we can revisit again later if needed but we feel the existing errors/notices should be sufficient for now.
