### ISSUE TITLE
Missing space between items on splash for secondary admin with access to shared dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5415]
## Bug Description

There is a minor visual bug when administrators have access to the shared dashboard and have yet to sign in.

## Steps to reproduce

1. Set up Site Kit with dashboard sharing active
2. Share a module with Administrators
3. Login as a secondary admin who has not yet signed in with Google
4. See option to skip to view-only dashboard AND Reset Site Kit with no space between

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/175116416-f833e00b-d359-49cb-b5a6-a869a2078686.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a consistent spacing between horizontal buttons and links on the splash screen in all cases 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Closing, as it's no longer to reproduce this issue - the **Skip signin** and **Reset** links are now mutually exclusive, thanks to the change introduced here: https://github.com/google/site-kit-wp/pull/5393/files#diff-f96ca2962d44ef61a23ff831c155fbbf8ae677ecf5309a724b72171822f17cc6

They are mutually exclusive by way of the `isSecondAdmin` boolean:

https://github.com/google/site-kit-wp/blob/affa782aab7b74ad44d8dbb55cdc6a5f2d854806/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L367-L387

**Comment by techanvil** [comment]
Closing, as it's no longer to reproduce this issue - the **Skip signin** and **Reset** links are now mutually exclusive, thanks to the change introduced here: https://github.com/google/site-kit-wp/pull/5393/files#diff-f96ca2962d44ef61a23ff831c155fbbf8ae677ecf5309a724b72171822f17cc6

They are mutually exclusive by way of the `isSecondAdmin` boolean:

https://github.com/google/site-kit-wp/blob/affa782aab7b74ad44d8dbb55cdc6a5f2d854806/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L367-L387
