### ISSUE TITLE
Add selectors for centralized support links

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5423]
## Feature Description

For the new Notifications MVP features to be properly implemented, we need a way to get correct support links for different documentation pages and errors that may appear when users operate on the dashboard or settings pages. The new support links use the same centralized endpoint on the proxy service to jump to actual documentation pages, the only difference between documentation and errors links is the name of the parameter that is used to identify a document (`doc` for the documentation slugs, and `error` or `error_id` for errors).

These support links will be used by different components and we need a way to allow components to get support links for different documentation pages and errors. For this purpose we need to create three new selectors in the site datastore: `getProxySupportLinkURL()`, `getDocumentationLinkURL( slug )` and `getErrorTroubleshootingLinkURL( error )`. The first selector will just return an URL to the proxy support link endpoint. The second and third selectors will use the first one and add the appropriate parameters to the URL and return it.

The proxy support link URL should be composed on the backend and returned as part of the `_googlesitekitBaseData` global object.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Google_Proxy` class should have a new constant `SUPPORT_LINK_URI` with `/support/` value.
* The `_googlesitekitBaseData` global object should include the new `proxySupportLinkURL` property that contains an URL of the support link endpoint on the proxy side.
* The `core/site` datastore should be updated as following:
  * The `info` partial datastore should be extended to include the new `getProxySupportLinkURL` selector that returns the `proxySupportLinkURL` from the `_googlesitekitBaseData` global object.
  * The `urls` partial datastore should be extended to include new `getDocumentationLinkURL( slug )` and `getErrorTroubleshootingLinkURL( error )` selectors.
    * The `getDocumentationLinkURL( slug )` selector should return support link URL returned from the `getProxySupportLinkURL` selector with `doc={ slug }` query parameter.
    * The `getErrorTroubleshootingLinkURL( error )` selector should also return support link URL returned from the `getProxySupportLinkURL` selector  with `error_id={ error.id || error.code }` query parameter if the error has either `id` or `code` properties with non-numeric value (in other words it should be textual slug, not a number). Otherwise the link URL should have `error={ error.message }` parameter.

## Implementation Brief

- In `includes/Core/Authentication/Google_Proxy.php`:
  * Add a constant `SUPPORT_LINK_URI` with the value `/support`.
- In `includes/Core/Authentication/Authentication.php`:
  * Create a private method `get_proxy_support_link_url`.
  * Return the composed URL using the `url` method from the `Google_Proxy` class and pass the `SUPPORT_LINK_URI` as an argument. 
  * In the `inline_js_base_data` method:
    * Add the `proxySupportLinkURL` property with an empty string as the value,
    * Within the `$this->credentials->using_proxy()` condition, add the `proxySupportLinkURL` property that should obtain the value from the `get_proxy_support_link_url` method.

- In `assets/js/googlesitekit/datastore/site/info.js`:
  * Destructure the `proxySupportLinkURL` property from `global._googlesitekitBaseData`.
  * Pass `proxySupportLinkURL` to the `receiveSiteInfo` action.
  * In the `RECEIVE_SITE_INFO` reducer, get the `proxySupportLinkURL` from the payload and return it within the `siteInfo` object.
  * Add `getProxySupportLinkURL` selector that calls the `getSiteInfoProperty` helper function by passing the `proxySupportLinkURL` as an argument.
- In `assets/js/googlesitekit/datastore/site/urls.js`:
  * Add `getDocumentationLinkURL` selector that receives `slug` as a required parameter.
  * Get the `proxySupportLinkURL` from `getProxySupportLinkURL` selector.
  * Return the URL string by concatenating the `proxySupportLinkURL` and `?doc={slug}`. 
  * Add `getErrorTroubleshootingLinkURL` selector that receives `error` object as a required parameter.
  * Get the `proxySupportLinkURL` from `getProxySupportLinkURL` selector.
  * Check if the `error` object's `id` OR `code` property is a non-numeric text value.
  * Return the URL string by concatenating the `proxySupportLinkURL` with the appropriate `?error_id={error.id}` OR `?error_id={error.code}`.
  * Otherwise, return the URL string by concatenating the `proxySupportLinkURL` and `?error={error.message}`.

### Test Coverage

- Add tests for the new selectors `getProxySupportLinkURL`, `getDocumentationLinkURL`, and `getErrorTroubleshootingLinkURL`.

## QA Brief

* Verify that the changes meet AC & IB
* Run unit tests, verify that they all pass, and cover the changes.
* For extra manual testing, call the following selectors in your browser console when observing the dashboard page:
  * `googlesitekit.data.select('core/site').getDocumentationLinkURL('not-enough-traffic')` - should return an URL to the support endpoint that redirects you to the correct documentation page.
  * `googlesitekit.data.select('core/site').getErrorTroubleshootingLinkURL({id: 'nonce_expired' })` and `googlesitekit.data.select('core/site').getErrorTroubleshootingLinkURL({ message: 'Curl error: host timed out.' })`- should return URLs to the support endpoint that redirects you to the correct error troubleshooting page.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@aaemnnosttv or @felixarntz do you mind reviewing AC?

**Comment by felixarntz** [comment]
@eugene-manuilov ACs look good, except could you also add the actual service support base URL so that that is part of the ACs?

**Comment by eugene-manuilov** [comment]
Thanks, @felixarntz. AC is updated. Please, check it again.

**Comment by felixarntz** [comment]
@eugene-manuilov LGTM, thanks!

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
@mohitwp I've been able to gather information to help us QA this ticket.  The QAB is engineering focused IMO, so once you have completed the QA on this ticket please add the `QA:Eng` label.  

The work involved is around error messages.  You will remember that [you tested ](https://github.com/google/site-kit-wp/issues/5236#issuecomment-1166926304) the retry button and making sure that it appears on error messages.  Well, the next step is to add a support link so the user can find out more information.  What we can do here is go through the [Error States MVP spreadsheet here](https://docs.google.com/spreadsheets/d/12x39d7j0GNqha0m7s4-Y3P5SwK9wwgxxxDnWp3svSKg/edit?resourcekey=0-IngulwDvPmI4SEq2g-f4rA#gid=0) and make sure that the support link points to the correct guide. Initially test the error states you went through previous and check on the spreadsheet the URL.  I understand that @adamdunnage has been working closely with @eugene-manuilov on this so any questions please ask them initially.

**Comment by mohitwp** [comment]
@eugene-manuilov @makiost Through using [steps mentioned here](https://github.com/google/site-kit-wp/issues/5236#issuecomment-1164448709) I'm able to generate error with retry button but that error is when user is offline. For this error we are not showing any support link. As per [Error States MVP spreadsheet here](https://docs.google.com/spreadsheets/d/12x39d7j0GNqha0m7s4-Y3P5SwK9wwgxxxDnWp3svSKg/edit?resourcekey=0-IngulwDvPmI4SEq2g-f4rA#gid=0) we shows Retry + Support link when "response is not a valid json' and "access the relevant data". Can you please help me guide me how can I generate this error ?

cc @wpdarren 

![image](https://user-images.githubusercontent.com/94359491/180943950-8e56ad39-f316-4f34-9acc-648e2fe99820.png)

**Comment by eugene-manuilov** [comment]
@mohitwp there is another ticket #5507 that adds the get help link after the retry button. That ticket is not implemented yet, thus it's a bit early to verify it on the frontend. 

I have updated QAB a bit to explain how you can test it manually on your end, see the last section with selectors that you can run in your browser console.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified:
Verified selectors using console.

- `googlesitekit.data.select('core/site').getDocumentationLinkURL('not-enough-traffic')` redirects to https://sitekit.withgoogle.com/support?doc=not-enough-traffic

- `googlesitekit.data.select('core/site').getErrorTroubleshootingLinkURL({id: 'nonce_expired' }) and googlesitekit.data.select('core/site').getErrorTroubleshootingLinkURL({ message: 'Curl error: host timed out.' })` navigating to https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#curl-errors.

![image](https://user-images.githubusercontent.com/94359491/181015398-5ae59435-4892-47a1-9735-b254745c9072.png)

Requires `QA:Eng` review.

cc @wpdarren

**Comment by tofumatt** [comment]
@mohitwp Looks like your screenshot shows the correct values but the QA writeup doesn't.

The value from `googlesitekit.data.select('core/site').getErrorTroubleshootingLinkURL({ message: 'Curl error: host timed out.' })` is actually `https://sitekit.withgoogle.com/support?error=Curl%20error%3A%20host%20timed%20out`.

But that's in the screenshot so looks good.

QA ✅
