### ISSUE TITLE
Permissions modal blocks outside clicks on WP dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5424]
## Bug Description

When a request is made that requires additional permissions to be granted on the WP dashboard, the modal doesn't display as usual and clicks are blocked in a non-obvious way.

## Steps to reproduce

1. Set up SK without Analytics
2. Sign in with a different admin and connect Analytics
3. Sign in with the first admin again
4. See permissions modal on WP dashboard

## Screenshots

https://user-images.githubusercontent.com/1621608/175376916-4421fa1f-fe4c-48b4-9931-8b3783305935.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's insufficient permissions modal should not be triggered on non-Site Kit screens

## Implementation Brief

* In `assets/js/googlesitekit/constants.js`:
    * Create a new definition named `SITE_KIT_VIEW_CONTEXTS` which should export an array of Site Kit only view contexts, e.g. `VIEW_CONTEXT_DASHBOARD`, `VIEW_CONTEXT_PAGE_DASHBOARD`, `VIEW_CONTEXT_DASHBOARD_VIEW_ONLY`, `VIEW_CONTEXT_PAGE_DASHBOARD_VIEW_ONLY`, `VIEW_CONTEXT_USER_INPUT`, `VIEW_CONTEXT_DASHBOARD_SPLASH`, `VIEW_CONTEXT_SETTINGS`, and `VIEW_CONTEXT_MODULE_SETUP`.
    * We're creating a new definition here so that this can be re-used in future if needed.
* In `assets/js/util` folder:
    * Create a new file named `is-site-kit-screen.js`.
    * Import the new `SITE_KIT_VIEW_CONTEXTS` definition.
    * From this file, export a new function named `isSiteKitScreen` which would accept `viewContext` as a parameter, and return a boolean value describing if the passed `viewContext` is a Site Kit screen.
    * Inside the function, check if the passed `viewContext` belongs to the new `SITE_KIT_VIEW_CONTEXTS` array definition.
    * Add necessary file header comments.
* In `assets/js/components/Root/index.js`:
    * Import the new `isSiteKitScreen` function.
    * Conditionally render the `<PermissionsModal />` component only if it is a Site Kit screen by passing the current `viewContext` to the `isSiteKitScreen` function:
    https://github.com/google/site-kit-wp/blob/36283af816b31d6eca0ba020b09386c45a0612ff/assets/js/components/Root/index.js#L66

### Test Coverage

* No tests need to be added/updated.

## QA Brief

* Follow the steps above to reproduce the error. 
* Navigate to the WordPress dashboard, and locate the Site Kit widget
* Ensure that the "Additional permissions required"-modal isn't present
* Ensure that all the other links on the WP dashboard can still be accessed

## Changelog entry

* Fix permissions modal issue on non Site Kit pages.

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit, 

> * Use the `global._googlesitekitTrackingData.isSiteKitScreen` value to check if the current screen is a Site Kit screen.

While this would work, we try to avoid reaching for globals in components. I think we could do this using the existing `viewContext` and its related utilities (or maybe extract a new one?).

**Comment by nfmohit** [comment]
Thank you for the kind review @aaemnnosttv! I've updated the IB to use `viewContext`. Please let me know if it looks good now 🙏

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified:

-  "Additional permissions required"-modal isn't present on WP dashboard.
- All the other links on the WP dashboard are clickable and accessible.

Note : Errors are not looking proper on WP dashboard will create separate issue for this.

https://user-images.githubusercontent.com/94359491/181176453-b9ba1ad9-5b93-4494-9fe0-4ca7c82e5427.mp4

**Comment by mohitwp** [comment]
Created separate issue for WP dashboard - Site kit widget notification design. 
https://github.com/google/site-kit-wp/issues/5615
