### ISSUE TITLE
Update presentation of existing tag in setup and settings edit views for consistency

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5426]
## Bug Description

While testing #5244 I discovered another bug which was out of scope.

When setting up Analytics via GTM setup, there's a flicker when you get to setting up Analytics. Initially the screen loads **without** the GTM message `An existing Google Tag Manager property was found on your site with the ID UA-232779384-1. Since it refers to the same property selected here` and then it loads a couple of seconds later. 

I included it on the screen cast below but jump to 0.35 seconds to see what I mean.

https://user-images.githubusercontent.com/73545194/175476255-bba78432-9498-4691-b500-2ca4497e3d51.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All module setup and settings (edit) views that include existing tag checks should remain in their initial loading states until those checks have completed
    * Said another way, the presence of an existing tag should not have a delayed effect to the layout or wording used in module settings edit or setup views
* No change should be made to the settings non-edit view

## Implementation Brief

- In the Analytics datastore (`assets/js/modules/analytics/datastore`), create a new selector named `hasFinishedLoadingGTMContainers`. In this selector:
    - Return `true` if the Tag Manager module is not available.
	- Check if the `getLiveContainerVersion` resolver from the `MODULES_TAGMANAGER` store has finished resolution with Tag Manager `accountID` and `internalContainerID` settings as parameters. Return `false` if the resolution hasn't finished.
	- If the site uses AMP, check if the `getLiveContainerVersion` resolver from the `MODULES_TAGMANAGER` store has finished resolution with Tag Manager `accountID` and `internalAMPContainerID` settings as parameters. Return `false` if the resolution hasn't finished.
	- Return `true` if none of the above conditions cuts off the function's execution.
- In `assets/js/modules/analytics/components/setup/SetupMain.js` and `assets/js/modules/analytics/components/settings/SettingsEdit.js`:
	- Locate the logic for displaying the `<ProgressBar />` component. Update its logic so that besides the existing conditions, the `<ProgressBar />` is displayed if the new `hasFinishedLoadingGTMContainers` selector is falsey.

### Test Coverage

- Add test case(s) for the new `hasFinishedLoadingGTMContainers` selector.

## QA Brief

- Follow the screencast to connect GTM using an existing container that has Analytics property.

https://user-images.githubusercontent.com/24408261/214110644-d3aa67ff-75ee-4de7-bebe-47f7231892fd.mp4

- Save and publish/submit.
- Go to Site Kit and set up the GTM module.
- Select the account and container with the Analytics property you've set up in the previous steps.
- Click the `Continue to Analytics Setup` button,
- Ensure the existing tag message appears as soon as the loader disappears. In other words, there shouldn't be any flickering to display the existing tag message.

## Changelog entry

* Improve loading of setup/settings views when an existing tag is present.

**Comment by aaemnnosttv** [comment]
Here's an example of the problem which is a bit more exaggerated by delaying the tag check specifically.

https://user-images.githubusercontent.com/1621608/208156999-d593a074-88d4-4e99-b277-cfac72723d0f.mp4

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit – is this only coming from the Analytics tag checks in GTM containers?

It looks like we're not checking for existing tags in the same places (SetupMain, SettingsEdit). Do these just happen to finish early enough that they do not result in a flicker later? If so, we should probably wait for these too.

Regarding the IB, this looks like a good candidate for a new selector since there is some logic to it which we need in multiple places. Something like `hasFinishedLoadingGTMContainers` on the Analytics store would be good I think (since it also needs to check if GTM is available).

As an aside, I think the IB could be simplified a bit by leaving out specific details about how a selector should be used/called as we can assume everyone is familiar with that (or can read the inline doc 😉).

**Comment by nfmohit** [comment]
Thank you for your kind review on this, @aaemnnosttv.

According to my investigation, this is coming up from the [`ExistingGTMPropertyNotice`](<ExistingGTMPropertyNotice />) component.

https://github.com/google/site-kit-wp/blob/afc11b01efdd5c28e34a56c146f5f0a1bdd2a42f/assets/js/modules/analytics/components/common/ExistingGTMPropertyNotice.js#L42-L46

`SetupMain` and `SettingsEdit` are _ascendants_ to `ExistingGTMPropertyNotice` where a `ProgressBar` is displayed, hence, we are utilizing the same progress bar that is used when all the other data is being loaded.

I have updated the IB to address the new selector and also made it concise. Let me know what you think. Thanks!

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit !

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The existing tag message appears as soon as the loader disappears. There isn't any flickering to display the existing tag message.  See screencast below.
- I also went into Analytics settings and made sure that the existing tag message appears on load and there is no flickering. 

https://user-images.githubusercontent.com/73545194/216345645-dc500a3a-86b6-40f5-beee-514ebc830301.mp4
