### ISSUE TITLE
Sharing Settings Modal should not be closed after applying who can view roles

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5437]
## Feature Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202445998779482 please see Asana for background (several comments on this one so please read in Asana).

The Dashboard Sharing "Edit roles" UI is a bit confusing because there is a "Close" button that appears when editing roles, but this doesn't close the modal—it exists the "Edit roles" UI. We should change this to a checkmark with different text to make it clearer that the user can exit this view with their changes intact.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When changing roles in Dashboard Sharing (eg in the "Edit roles" screen), the "X" ("Close") button's icon should be changed to a ✔️  icon with the text (`Done<VisuallyHidden> editing roles</VisuallyHidden>` instead of "Close").

## Implementation Brief

* Update the close button in the Dashboard Sharing Edit modal here: https://github.com/google/site-kit-wp/blob/a713aa42507d351c2bda2776c843167becae01c4/assets/js/components/dashboard-sharing/UserRoleSelect.js#L251-L257
* Change the icon to be a checkmark icon, eg. `<CheckIcon />` from `assets/svg/icons/check.svg`
* Change the text from "Close" to `Done<VisuallyHidden> editing roles</VisuallyHidden>`

### Test Coverage

* VRTs may need updating.

## QA Brief

* In the Dashboard sharing & permissions window, modify some of the users `Who can view` roles as in the screenshot:
<img width="1166" alt="Screenshot 2022-09-12 at 13 41 20" src="https://user-images.githubusercontent.com/16494321/189720782-69b1e4b2-0112-4df8-ae88-25d26ae1cdc1.png">

The Site Kit by Google Tester plugin is required to have this functionality.

## Changelog entry

* Update the icon on the button for exiting the "Edit roles" UI on the Dashboard Sharing modal.

**Comment by techanvil** [comment]
Hi @tofumatt, re. the IB, I am not sure about the suggestion of `ChipCheckmark`. I was curious and tried swapping it for the `CloseIcon` but could not get it to display anything. Maybe the solution is simple but it has eluded me for about half an hour of trying. So, either there's some trick to getting it to display properly or maybe we should suggest `check.svg` instead...

**Comment by tofumatt** [comment]
Ah, good shout @techanvil. I thought the chip checkmark would work, but I guess not. Using that SVG icon directly should be fine though.

**Comment by techanvil** [comment]
Cheers @tofumatt, SGTM.

IB :white_check_mark:
