### ISSUE TITLE
[project_id] has issue [project_id contains invalid caracters]

### ISSUE THREAD

**Issue by Seventhose** [google/site-kit-wp#544]
## Bug Description

Field [project_id] has issue [project_id contains invalid caracters].

Similar to #517

## Steps to reproduce

1. Go to first page setup
2. Click on Get Oauth credentials
3. Renamed the project with 3 letters name
4. See error!

* I can't do anything even if i unistall and reinstall the plugin

## Screenshots
![2019-09-17 10-27-18 Site Kit     Google Developers - Google Chrome](https://user-images.githubusercontent.com/540299/65024965-17119380-d936-11e9-8020-80186e1ec8f2.png)

**Comment by jamesozzie** [comment]
@Seventhose Thanks for reporting, can you please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard and I can hopefully assist further. 

As a workaround you can attempt the following to obtain working credentials, but please share your site health info so we can see if we can identify anything which is impacting setup. 
- In the address bar of your window paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
- Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
- Press enter, with your cursor in the address bar (as if you are visiting that URL)
- Press the "GET OAUTH CREDENTIALS" button
- The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit

**Comment by jamesozzie** [comment]
@Seventhose Are you encountering the same issues or have you been able to successfully setup Site Kit after performing the suggested steps?
