### ISSUE TITLE
Tooltip background is different between Figma and test site

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5443]
## Feature Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202422111202705 please see Asana for background 

On the figma designs the tool tip (when you have 2 or more admins) is white background with blank text. Where as on the test site it is grey background with black text. This is quite hard to read. Also the font size is bigger on the figma designs, and easier to read. 

Figma:
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/d71b1bc6-e778-4fd7-a5ad-1bebe1a6e8fd)

Chrome:
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/7abb635c-3c45-4271-be01-faf6fd247756)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Fixed in #6059
