### ISSUE TITLE
Minor UI issue with Idea Hub icon on 'View only' menu

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5446]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202419867342278 please see Asana for background

The idea hub icon is slightly larger and unaligned with the text. Only minor. 
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/27f04248-e4da-4e13-b256-5362590db4a9)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The module icon, name, and "shared by" info should all be vertically aligned/centered in the "view only" Dashboard Sharing menu.

## Implementation Brief

* Update the `<Icon />` component here to have a `height` prop with the value of `26`:
https://github.com/google/site-kit-wp/blob/1f37af065308315c8b8db350b08a5e46de7e8e10/assets/js/components/ViewOnlyMenu/Service.js#L57
* This necessarily acts as a maximum height for the icons imposing the Idea Hub icon to not be longer than the others.

### Test Coverage

* Update VRT screenshots if required.

## QA Brief

* Ensure that the `dashboardSharing` feature flag is enabled in the tester plugin.
* Go to the Site Kit Dashboard.
* Using the Dashboard Sharing settings modal, grant access to some/all modules to one or more roles, which should include the Idea Hub module.
* Log into the site using a different user having one of the granted roles.
* Open the Site Kit Dashboard as a View Only user.
* Open the View Only menu.
* Ensure that the Idea Hub icon and all the other icons are correctly placed.

## Changelog entry

* Improve "View only" menu icon alignment when viewing shared dashboard.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅

**Verified:**

- the Idea Hub icon and all the other icons are correctly placed.

![image](https://user-images.githubusercontent.com/73545194/178257090-5d41f937-999d-4902-b3cf-394d03db7a99.png)

Note: I am struggling to see the idea hub icon because of the grey background on the view only menu. I have raised this as a GM2+ issue as it's out of scope for this ticket.
