### ISSUE TITLE
Error and warning banner notifications layout can have empty column

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5447]
## Bug Description

When you do not grant the necessary permissions when setting up Site Kit or any module, an error message appears in the Site Kit dashboard.  It would be good to improve the error so that it is aligned to the left or centre. Currently the message appears to the right and it's quite close to the edge of the notification. 

This was observed on all mobile small screen sizes on Chrome and our other supported browsers. 

## Steps to reproduce

1. Start the process to sign in with Google
2. Cancel the process before granting permissions on the consent screen
3. See "Error Connecting Site Kit" banner as below

## Screenshots

<img width="931" alt="image" src="https://user-images.githubusercontent.com/1621608/229191967-d97a75c3-543e-4320-8a80-58dc837fa5fe.png">

## Additional Context

The problematic block of code is here https://github.com/google/site-kit-wp/blob/feead7ac45ed8c6fd82db9a9366a2d4b56ee54cf/assets/js/components/notifications/BannerNotification/index.js#L566-L572

Note the `setup_error` notification is one of the only `win-error` type notifications we define. `win-warning` does not appear to be used but could be via the API so we should continue to support it for now.
https://github.com/google/site-kit-wp/blob/feead7ac45ed8c6fd82db9a9366a2d4b56ee54cf/assets/js/components/notifications/ErrorNotifications.js#L63-L69

It is also worth noting that `.googlesitekit-publisher-win__icons` is absolutely positioned, so there is seemingly no use of the wrapping grid that it has.

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/1621608/229193743-133d884f-cbcb-492f-94ac-c008ba6d1e71.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Banner notifications should not have an empty grid column
    * All instances where this exists should be updated so that the content is left-aligned in place of the empty column

## Implementation Brief

- In `assets/js/components/notifications/BannerNotification/index.js`:
  - Update the `<Cell />` component wrapping the `.googlesitekit-publisher-win__icons` element to have the `smOrder`, `mdOrder` and `lgOrder` props all to `3`.
- In `assets/sass/components/global/_googlesitekit-publisher-wins.scss`:
  - Update the styling for the `.googlesitekit-publisher-win__icons` element so that it longer uses `position: absolute;` and `transform` properties. Instead, it should be converted into a flex element having `100%` `height` and content justified to the right.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Follow `Steps to reproduce`
* Check the fixed notification should be as per the screenshot 

![image](https://user-images.githubusercontent.com/18395600/235744071-cf78f3e1-bd0d-459e-9621-861e399b2e4e.png)

## Changelog entry

* Update banner notification layout to avoid unwanted empty space on the left.

**Comment by aaemnnosttv** [comment]
@wpdarren would you please check this again to see if it's still relevant in GM2+?

**Comment by wpdarren** [comment]
@aaemnnosttv yes, this is still an issue. 

<details>
 <summary>Screenshot on mobile</summary>

![image](https://user-images.githubusercontent.com/73545194/208862872-784f7b96-f2c2-4a8c-9455-c2791c120ab9.png)

</details>

**Comment by aaemnnosttv** [comment]
Thanks, this is still an issue even on desktop so I'll redefine this to be more general.

**Comment by techanvil** [comment]
Hey @nfmohit, regarding the IB, although your suggested solution would provide a fix for the problem, it would also leave us in the situation where we've got an inconsistently applied `Grid/Row/Cell` layout.

I think the more idiomatically correct thing to do here, is instead to fix the ordering for the `Cell` which surrounds `.googlesitekit-publisher-win__icons`. This can be achieved by setting its `smOrder`, `mdOrder` and `lgOrder` props all to `3`.

It would also be nice to update the `.googlesitekit-publisher-win__icons` styling to remove its absolute positioning (we could instead position it for the most part by applying Flexbox to the `Cell`, or something along those lines). However, this is probably out of scope for this issue.

**Comment by nfmohit** [comment]
IB updated, let me know if it looks good. Thank you, @techanvil!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The fixed notification is as per the screenshot for desktop.
- I also looked at different viewports in mobile and tablet as this is where the issue first occurred for me. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/235899473-33695d76-8f00-4614-827c-fd784755f278.png)
![image](https://user-images.githubusercontent.com/73545194/235899494-f9844ea3-7606-4d16-959e-7eabc1beadfa.png)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
