### ISSUE TITLE
Create Thank with Google REST publications endpoint

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5449]
The new `GET:publications` REST data point should be scaffolded for the Thank with Google module. Since the corresponding API endpoint is not yet available, it should just return an empty dummy response for now. Testing the different states before API availability will be made possible using an upcoming version of the Site Kit tester plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new REST data point `GET:publications` should be added to the TwG module.
* It should for now not require any service, and it should not be shareable.
* It should be implemented through a simple callback function that returns an empty array (which technically will be interpreted as "the user does not have any relevant publications").

## Implementation Brief

In `includes/Modules/Thank_With_Google.php`:
- Create a protected method `get_datapoint_definitions()` that returns an array of datapoint definitions.
- Return the `GET:publications` datapoint definition.
- That should be an array with the `service` key with the value of an empty string.
- Create a protected method `create_data_request` that receives `data` as a parameter that should be the type of `Data_Request`.
- It should have a switch case for the `GET:publications` datapoint.
- It should return a callback function. The callback function should return an empty array.
- Finally, the `create_data_request` method should return the `create_data_request` method from the parent.

### Test Coverage

- No new tests are to be added.

## QA Brief

* Using the browser console, run `await googlesitekit.api.get( 'modules', 'thank-with-google', 'publications' )`
* Verify an API call to the publications endpoint was successfully made
* Verify it that it returns an empty array.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅
