### ISSUE TITLE
Introduce new `getAccountChooserURL` selector

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5453]
## Feature Description

For quite some time, Google services have supported multiple sign-in to allow for users to be signed into multiple Google accounts at the same time. This makes deep-linking to external Google service UIs challenging because a user's initial/default Google account may not be the one a user is signed in with in Site Kit which can lead to problems related to mismatched accounts, lack of access, etc.

To solve this, Google has an "AccountChooser" endpoint which essentially acts as a proxy to another service URL. It works by sending the user to the chooser URL along with the user's Google email address and the destination service URL. If the user is already signed in with the given account, it will forward the user on to the service with the proper Google account selected for the given email address. If not, the user is prompted to sign in before continuing on to the final URL.

In Site Kit, we currently use a `?authuser={email}` workaround in service URLs but this is not supported by all services.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `getAccountChooserURL` selector should be added to the `core/user` store which takes a single (required) argument: the destination URL, and returns a new URL in the following format:   
	```
	https://accounts.google.com/accountchooser?continue={url-encoded-destination-url}&Email={google-email-address}
	```
	* Note the `Email` parameter name is case-sensitive
	* The `Email` value should be the URL-encoded email address of the current user's Google account
* If the email address isn't available yet, it should return `undefined`

## Implementation Brief

- In `assets/js/googlesitekit/datastore/user/user-info.js`:
    - Create a new property in the `selectors` object named `getAccountChooserURL` which uses `createRegistrySelector` to create a selector function.
	- The new function should accept a string parameter named `destinationURL`.
	- The function should start with an `invariant` function call with `destinationURL` as the first parameter and an error message as the second, e.g. `destinationURL is required.`
	- Use the `createRegistrySelector`'s `select` function to select the `core/user` store and its `getEmail()` selector to query the Google email of the current user.
	- If this email is `undefined`, return `undefined` from this selector.
	- Use `encodeURIComponent` to encode both the `destinationURL` and the queried `email`.
	- From the selector, return a template literal (string) containing a URL with the described format in the AC replacing the `{url-encoded-destination-url}` with the encoded URL and `{google-email-address}` with the encoded email.

### Test Coverage

* Add a test case in `assets/js/googlesitekit/datastore/user/user-info.test.js` that describes `getAccountChooserURL`.

## QA Brief

* Run the new unit tests and ensure that they pass, and cover the changes added by the new selector.
* For extra, manual testing, call the `getAccountChooserURL(destinationURL)`-selector with/without a destinationURL string parameter, and with/without an existing user object.

## Changelog entry

* Add new selector `getAccountChooserURL` to the `core/user` store.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
I've run through the QA steps here and they are also covered by the passing unit tests, so no QA needed on this issue.

QA ✅ 

Moving to Approval.

**Comment by felixarntz** [comment]
@tofumatt @aaemnnosttv This didn't have a changelog entry, but I think it should have one as it is a new selector, so that's worth highlighting. We should only avoid adding changelog entries for things that are largely irrelevant for end users and developers, like private code infrastructure tweaks, fixing test failures, etc.

I've added one now, would be good to include that in the changelog.
