### ISSUE TITLE
Implement publications selectors in `modules/thank-with-google` store

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5454]
The `modules/thank-with-google` store (see #5365) should include a number of selectors related to getting information about  the relevant TwG publication.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new selector `getPublications()` should be added to the `modules/thank-with-google` store:
    * It should be an API-based selector simply passing through the list of publications from the `GET:publications` REST data point (see #5449), i.e. an array of objects (or `undefined` if not loaded, as always).
    * Jest test coverage using mocks should be added, and since this is purely a `QA: Eng` issue, it doesn't need to be technically blocked by having the REST endpoint available.
* A new selector `getCurrentPublication()` should be added to the `modules/thank-with-google` store:
    * It should call `getPublications()` and then use logic to identify the current publication (see below) and return it, i.e. either the publication object or `null` (or `undefined` if not loaded, as always).
    * If the list of publications is empty, return `null`.
    * If there is only one publication in the list, return that.
    * If there are multiple publications in the list, return one of them based on the following logic:
        * If the `publicationID` module setting is already set (i.e. not empty) and that publication is in the list (check `publicationId` field in the object), return that.
        * Otherwise, if any of the publications has its `state` field set to `ACTIVE`, return that. If that applies to multiple, return the first of them.
        * Otherwise, just return the first one in the list.

### Dummy data / fixtures
API fixtures should be based on the following dummy struct for a publication object (keeping in mind of course that the API returns an array of such objects):
```json
{
  "publicationId": "TEST-PUBLICATION-ID",
  "displayName": "Test publication title",
  "verifiedDomains": [ "https://example.com" ],
  "paymentOptions": {
    "virtualGifts": true
  },
  "state": "ACTIVE"
}
```
The `state` field can be one of the following values: `ACTIVE`, `ACTION_REQUIRED`, or `PENDING_VERIFICATION`
The `paymentOptions.virtualGifts` should always be `true`.
The other fields are variable and could be anything (matching the data type though).

## Implementation Brief

- Create `assets/js/modules/thank-with-google/datastore/publications.js` file, which will contain the publications selectors.
- The `baseInitialState` should contain the `publications` property initialized to be an `undefined` value.
- Create `fetchGetPublicationsStore` using the `createFetchStore` factory function with the following details:
  * `baseName` should be set to `getPublications`.
  * `controlCallback` method shouldn't accept any parameter
  * It should return `API.get()` method that calls the `publications` endpoint for the `thank-with-google` module.
  * `reducerCallback` method receives `state`, and `publications` (API response) as parameters.
  * It should return the `publications` along with the existing state.
- Create `*getPublications()` resolver with the following details:
  * Return early if there are existing `publications` for the module.
  * Otherwise, It should call the `fetchGetPublications` action created by the `createFetchStore` function.
- Add `getPublications()` selector that returns the `publications` from the state.
- Add `getCurrentPublication()` selector with the following details:
    * It should call the `getPublications()` selector to get the `publications` from the state.
    * Return `undefined` if the `publications` is not loaded yet.
    * If the `publications` list is empty, return `null`.
    * If there is only one publication in the list, return that.
    * If there are multiple publications in the list, return one of them based on the following logic:
      * If the `publicationID` property is in the looped object item, return that object.
      * Otherwise, if any of the publications has its `state` property set to `ACTIVE`, return that. 
      * If the above applies to multiple items, return the first of them.
      * Otherwise, return the first one in the list.

### Test Coverage

- Add test coverage for the `getPublications()` and `getCurrentPublication()` selectors.

## QA Brief

- Verify the `getPublications()` selector makes an API call to the `GET:publications` endpoint regardless of whether #5449 is completed.
- Verify the unit tests are good enough and are passing.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
No further QA is needed here as it's just making sure the code exists and runs as-expected. Moving directly to Approval.

**Comment by felixarntz** [comment]
@hussain-t Yes, in the API response it's `publicationId` with lowercase `d`.

I have made another observation here, could you please address this as well? For selectors used for setup flows, we should always disable the cache. So please update the `getPublications` selector to pass `useCache: false` for its API request (similar to other module setup flow selectors, e.g. AdSense/Analytics `getAccounts`, `getProperties` etc.).

**Comment by hussain-t** [comment]
Thanks for the clarification, @felixarntz. To fix the above, I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/5542).

**Comment by wpdarren** [comment]
@hussain-t @felixarntz is there anything we can do to QA this ticket when it is through CR/MR or is is still a `QA:Eng` ticket?
