### ISSUE TITLE
Implement Thank with Google settings view UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5456]
The TwG module settings view UI should be implemented, tweaking the existing UI which was taken over from the old SwG module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG `SettingsView` component should be adjusted to display data implementing [the UI from this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A7123). Details on the different field display values below:
    * _Publication ID_ should simply display the `publicationID` setting value.
    * _Type_ should display either "Fixed" if `buttonPlacement` starts with `static_` or "Overlay" otherwise (i.e. `buttonPlacement` starts with `dynamic_`).
    * _Prominence_ should display either "High" if `buttonPlacement` is `dynamic_high`, or "Low" if `buttonPlacement` is `dynamic_low`. Or otherwise (i.e. `buttonPlacement` starts with `static_`) as follows:
        * `static_auto` --> "Auto"
        * `static_above-content` --> "Above the post"
        * `static_below-content` --> "Below the post"
        * `static_below-first-paragraph` --> "Below the 1st paragraph"
    * _Supporter wall widget_ should for now just display the static text it has in Figma, with the link pointing to the WordPress widgets admin screen.
    * _Color_ should for now simply display the value of the `colorTheme` setting. This will be properly localized later.
    * _Post types_ should display the comma-separated list of post type labels for the post type slugs stored in the `buttonPostTypes` setting.
* It should be ensured that the corresponding Storybook story (already existing, from old SwG implementation) shows up correctly (i.e. new dummy values will need to be set).

## Implementation Brief

In `assets/js/modules/thank-with-google/components/settings/SettingsView.js`: 
* Use the `DisplaySetting` component to render the values below, to keep the UI consistent with other `SettingsView` components (see comment below: https://github.com/google/site-kit-wp/issues/5456#issuecomment-1180214145)
  * get the `publicationID`, `buttonPlacement` and `buttonPostTypes` using their respective selectors from the  `MODULES_THANK_WITH_GOOGLE` store. 
  * Under `Publication ID`, output the `publicationID` setting value.
  * Type should display either:
    * "Fixed" if `buttonPlacement` starts with `static_`
    * "Overlay" otherwise (i.e. `buttonPlacement` starts with `dynamic_`).
  * Determine the value of Prominence according to AC and output the correct value based on the logic in the ACs.
  * For Supporter Wall, see the ACs as well (eg. display static text with a link).
  * For Color Theme, return the value of the `colorTheme` setting. But add a `// TODO:` comment and possibly file a follow-up issue about localizing the colors, because these values are not localized.
  * For Button Post Type: show an unordered list (`<ul>`) of each post type label "Thanks with Google" is enabled on. This differs from the Figma UI, because there's no way to translate a dynamic list of post types. That said, if every post type that matches the available post types on the site is enabled, we could should detect this and show the string "All post types" instead.
    * For WordPress 4.x sites (or, more accurately, as a fallback for any site that doesn't have `select('core')` available, display a list of `posType` `slug`s.
    * For WordPress 5+ sites, ensure the `wp-data` JS asset is loaded on the Settings page, then use `select('core').getPostTypes()` to get post type information for each post type.
      * The post types returned should be filtered to only posts that are `viewable`. Otherwise, we'll get new post types like navigation menus, etc. in the response. If `getPostTypes()` allows filtering at the API request level instead of client-side; if so, use that. See:
<img width="1052" alt="CleanShot 2022-07-13 at 11 56 23" src="https://user-images.githubusercontent.com/90871/178717990-3091e890-d217-4ba6-9146-eba1c4364961.png">
* Return `null` from the component if all selectors aren't resolved yet. ie. value is `undefined`.
* Create the Layout using layout components `Grid`, `Row`, and `Cell`.

### Test Coverage

* Tests should largely be in the form of Storybook stories, which will be transferred from the existing SwG implementation and the dummy data updated.

## QA Brief

* Verify the [new Storybook stories](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-settings-settingsview--default) match the Figma mock.

## Changelog entry

* Implement Thank with Google settings view UI.

**Comment by felixarntz** [comment]
@tofumatt Good question, I defined the ACs based on fixing an inconsistency I had previously spotted in the Figma file, which has since been addressed in Figma, however in a different way than what I was thinking 😆 
How it is in Figma now is all good, and I've updated the ACs accordingly.

**Comment by tofumatt** [comment]
Thanks, sounds good! 👍🏻

**Comment by eugene-manuilov** [comment]
> * Under `Publication ID`, output the `publicationID` setting value.

I think it is worth mention that we should use the `DisplaySetting` component when we want to render a value to be consistent with other `SettingView` components. Maybe it is even worth refactoring the `DisplaySetting` component a bit to display the setting label as well to have the same layout for all displayed settings 🤔. We can render this markup in that component: https://github.com/google/site-kit-wp/blob/c952124fa9de3f3b558f54c075d7f9f304ba57d8/assets/js/modules/analytics/components/settings/SettingsView.js#L115-L122

> * Determine the value of Prominence according to AC. As for implementation, a switch case can be used.

An object is more performant than a switch, however this is very important because the performance gain will be extraordinary small.

> * For Color Theme, return a translated string based on the value of the `colorTheme` setting. eg. for `blue` return `__( 'Blue' )`, etc.

AC says that we just need to display the color as is for now, it will be localised properly later on.

> * For Button Post Type: show an unordered list of each post type "Thanks with Google" is enabled on. This differs from the Figma UI, because there's no way to translate a dynamic list of post types. 

AC says that we need to display a comma separated list of post type **labels**, not an unordered list of post types. It means that we need to pass post types labels from php to js to be able to display labels.

> That said, if every post type that matches the available post types on the site is enabled, we could should detect this and show the string "All post types" instead.

👍 

> * We don't have existing `SettingsView` Jest tests for any of our `SettingsView.js` components, but some `SettingsEdit.test.js` files exist. It would be good, but maybe not required in the interest of time, to add a few Jest tests for behaviour like the "Button Post Type" logic.

Yes, this seems to be out of scope for this ticket.

**Comment by tofumatt** [comment]
@marrrmarrr For the "Post type" section in the Thanks with Google UI, there is a _considerably_ easier/faster way to implement this feature for WordPress 5+ users that requires us writing nearly zero code using built-in functions to WordPress.

It would mean for users of WordPress 4.x, they would get untranslated post types in "slug" format, eg. `post` rather than `Post` (and always in English).

We can add the localised version for 4.x users, but given the low number of users of Site Kit with that version, the eventual plans to raise the minimum version of WordPress for new versions of Site Kit, and the extra time involved, would it be acceptable to have this "slug" fallback for 4.x WordPress users in the UI?

**Comment by felixarntz** [comment]
@tofumatt I'm personally not opposed of making this a slightly worse experience for WordPress 4.x users, I'd argue we should probably bump the version requirement soon anyway.

One important detail that I want to confirm based on your comment though, note that the labels we intend for this control would be plural, e.g. `Posts`. I think your proposed solution `select('core').getPostType( postType )` will still allow to get us that, so that may be fine. However, have you checked yet how that function works? I just want to make sure it doesn't cause a single REST API call per post type. If that was the case, it wouldn't be feasible to use for us since it would be too slow.

**Comment by tofumatt** [comment]
The `postType` returned should allow us to use either single or plural—usually plural is the "default" value returned in PHP and I think the same in JS, so that should be fine.

I'll check about combining API requests, that's a good point. I'd think in _most_ scenarios it'd be one for posts and one for pages… but yeah, we should see about combing API requests 🤔

**Comment by tofumatt** [comment]
Bumping to a higher estimate because of the WP Data integration and tests required for WP 4 and WP 5 code paths. It might not take this long, but good to budget a bit more time here as it's the first time we'll be using `wp.data` registries outside Gutenberg.

**Comment by felixarntz** [comment]
@tofumatt IB looks good, except a detail in regards to the `getPostTypes()` selector usage: I think we should filter them by which ones are `viewable` rather than whether they support a `title`, as the `viewable` field is the one that more accurately describes whether they are relevant / queryable for the website frontend.

**Comment by felixarntz** [comment]
IB ✅

**Comment by jimmymadon** [comment]
Just flagging that the [Figma](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=1205%3A6049) does not match the existing `<SettingsView>` / `<DisplaySetting>` component styles used by other modules.

**Comment by felixarntz** [comment]
@jimmymadon In what sense does it not match? Can you clarify?

If there is minor differences in e.g. font style / size etc., we should rather follow what we have already in the other settings panels than those exact styles in Figma.

**Comment by jimmymadon** [comment]
@felixarntz Yes sorry - that is what I meant. Differences in font weight, colour, etc.

Existing styles in settings:
<img width="899" alt="Screenshot 2022-07-18 at 23 50 56" src="https://user-images.githubusercontent.com/1721319/179715437-9a1515a8-b65d-4dbc-9e1f-2d41df62f376.png">

Figma:
<img width="1248" alt="Screenshot 2022-07-18 at 23 50 24" src="https://user-images.githubusercontent.com/1721319/179715544-6c0415ff-8b3e-43e2-9d6f-1871c9ba068b.png">

**Comment by felixarntz** [comment]
@jimmymadon Thanks for clarifying, yes in that case we should stick to what we have in terms of fonts, colors etc.

It's always a complexity that due to the lack of an actual style guide in Site Kit the UX team doesn't have too clear of a reference from the real product, since they typically only look at product screenshots. With the eventual GM3 redesign we should aim to improve that and have a cohesive style guide in Storybook that can be used as a reference for UX.

**Comment by jimmymadon** [comment]
>Supporter wall widget should for now just display the static text it has in Figma, with the link pointing to the WordPress widgets admin screen.

@felixarntz In WP 6.0.1, the "widgets admin screen" does not exist in the Appearance menu and there is only a single link to the 'Editor'. So should the above link conditionally point to the widgets admin screen if available and to the editor if not?

**Comment by kuasha420** [comment]
@jimmymadon does this only happen on a them with Full Site Editing support?

**Comment by felixarntz** [comment]
@jimmymadon I believe what @kuasha420 says it's correct - what you're saying is probably only the case when using a FSE theme like Twenty Twenty Two.

Good point raising this though, since for FSE themes the widgets admin screen is indeed irrelevant. Probably the best for now is to link to the widgets admin screen when using a traditional/classic theme, and to that new "Editor" screen when using an FSE theme.

**Comment by jimmymadon** [comment]
@tofumatt I can see that @eugene-manuilov has added postTypes with slugs and labels [which you are happy with](https://github.com/google/site-kit-wp/pull/5606/files#r931252907). So I will just wait for this to get merged and use the new selector to finish of this issue as well.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified**

- The TwG SettingsView component matches the UI from the Figma design.  There are some slight style differences but reading through the comments, we want to keep the settings style the same amongst all the modules. 
- In addition the data is displayed as per below:
  - `Publication ID` displays the publicationID setting value.
  - `Type` displays either "Fixed" or "Overlay"
  - `Overlay/Prominence` displays either "High" or "Low" 
  -  `Fixed `displays either  "Auto",  "Above the post",  "Below the post" or "Below the 1st paragraph"
  - `Add supporter wall` points to the Site Editor for Full Site edit theme, or to the Widgets admin for any other theme. 
  - `Color` displays the value, i.e Black, Green etc.
  - `Post types` displays the types set up on the site and are listed comma delimited.  
 
- I used a third-party plugin and created new post types and these did appear in the UI when setting up TwG and when editing settings. When all post types are selected All post types appears.
- Tested the view settings component on desktop and mobile devices to ensure no styling issues. 
- When TwG settings are saved, I looked at the source code to ensure that the parameters in the AC are correct. 

**Note:**  some of the parameters in the AC have changed as per #5533.

![image](https://user-images.githubusercontent.com/73545194/182839995-728a44e3-535a-4bc8-92b8-c09ffbfaea46.png)
