### ISSUE TITLE
Add "US only" label to Thank with Google module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5457]
The Thank with Google module will initially only be available for Google accounts in the US, so the module should be annotated as such.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Everywhere the TwG module is annotated with _Experimental_ in the UI, a second badge _US only_ should be displayed as well (see [this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A2988) for example).

## Implementation Brief

* In `assets/js/components/settings/SettingsActiveModule/Header.js`, `assets/js/components/settings/SetupModule.js`, and `assets/js/modules/thank-with-google/components/setup/SetupMain.js` files:
    * Locate the `<Badge />` component.
    * Add another badge after the existing `<Badge />`.
    * Use the label text: `US only`.
    * Only for the first two files - `Header.js` and `SetupModule.js`, make it show up only if the module `slug` is `thank-with-google`.

### Test Coverage

* Update VRT images if applicable.

## QA Brief

* Ensure that the "US Only" badge is displayed beside the "Thank with Google" module in the following places:
    * Settings -> "Connect More Services" tab (when TwG is disabled).
    * "Thank with Google" setup screen (during TwG setup).
    * Settings -> "Connected Services" tab (when TwG is enabled).

## Changelog entry

* Add "US only" label to Thank with Google module.

**Comment by tofumatt** [comment]
IB ✅
