### ISSUE TITLE
Implement reusable `ImageRadio` component for an image-based radio group

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5459]
The Thank with Google setup and settings UI will require a new type of component which is effectively like a group of radio buttons, however with images used instead of the radio buttons. This should be implemented as a generic component, and it should follow the general appearance of the [corresponding UI under "Prominence" in this Figma file](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A6511).

<img width="322" alt="CleanShot 2022-07-13 at 14 57 48" src="https://user-images.githubusercontent.com/90871/178751537-c3bd980b-64d7-411c-b9b9-775a0b24ce02.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new reusable React component `ImageRadio` should be implemented, which should behave like a radio button however display as an image.
    * It should represent a single radio button, similar to the existing `Radio` component.
    * It should facilitate creating a [UI like under "Prominence" in this Figma file](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A6511), in other words it would need to have props for the image (passing a component e.g. an SVG would give the most flexibility here), the label (e.g. "Low" in the Figma design), and the (optional) description (e.g. "Floating Thank button at the bottom of the page" in the Figma design).
    * Clicking on the image should change the state of the underlying radio button, while the radio button itself should be invisible.
    * Most props from the `Radio` component should be supported as well, however `disabled` and `readonly` explicitly do not have to be supported, as we do not have a design for how they should change in such a situation.
* The component should be accessible as possible, e.g. paying attention to correct focus states, visibility, ARIA labels and roles etc.
* A generic Storybook story for the component should be added, with at least two instances of it next to each other so that changing the radio state in a radio group can be tested there as well.

## Implementation Brief

- Create the `ImageRadio` component in `assets/js/components/ImageRadio.js`.
  - Add CSS as required to `assets/sass/components/global/_googlesitekit-image-radio.scss`
- Copy over the code from the current `Radio` component as a foundation.
- Get rid of the unwanted `disabled` and `readonly` props.
- Add the following props:
  - `image`: Optional. This will be an element with the expectation of an SVG element being passed in.
  - `label`: The label to display under the image.
  - `description`: Optional. Description to display under the label or image.
  - `aria-label`: Optional. ARIA label to apply to the image.
- Update the component to render the image and text.
  - If the `image` prop is not supplied, render the `label` in place of the image, as seen under "Type" in the [Figma file](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG).
- Hide the `input` element by making use of the `VisuallyHidden` component.
- Move relevant props from the `input` to the image, e.g. the click/keydown handlers, `tabIndex` etc.
- As discussed in the AC and in [Accessibility](https://docs.google.com/document/d/17ysrd8ya64T8rAgSriEo7MJxYyLf_nvm7nOn2KR248o/edit#heading=h.6w6xrqq4re8t) in the design doc:
  - Make sure the image handles the other various behaviours that radio buttons support e.g. hover state, focus outline, and the pointer cursor.
  - Add an ARIA role of `aria-role="radio"` to the image.
- Ensure no unneeded code, HTML classes etc. remain in the component.
- Add a Storybook story as described in the AC.

### Test Coverage

- Add the story to the VRT suite.

## QA Brief

* Locate the component in Storybook ( Global -> Image Radios)
* Ensure that the css has been implemented according to the [Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=1205%3A5703)
* For extra manual testing, you can change the props given in the [story itself](https://github.com/google/site-kit-wp/blob/1fa8f75cad165f1f0adc004fe1c672211db1d259/stories/imageradio.stories.js) 

## Changelog entry

* Add a new enhanced radio button component that allows for using graphics for choices.

**Comment by tofumatt** [comment]
@techanvil Awesome, thanks!

Fair point on the `propTypes` anyway. I don't think we need to go overboard on it, I was probably just being too strict-thinking! 😅 

IB ✅

**Comment by tofumatt** [comment]
(Assigning to @makiost as it was requested earlier 🙂 , but feel free to unassign yourself if other things come up, or move it into Execution column once you start.)

**Comment by tofumatt** [comment]
There is now a Figma design for the interactive states here, so this can be resumed: https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=1484%3A9129 🙂 

Let me know if you have any questions, @makiost 👍🏻

**Comment by wpdarren** [comment]
@makiost @tofumatt I've been looking at this ticket with @mohitwp and we understand it's a check from Storyboard to Figma CSS, but what about the items in the AC?  I feel that the QAB needs to be a little more detailed when I am reading the AC.  If a CSS comparison that's fine, but wanted to check before we jump into this QA.   Thoughts welcome?

**Comment by makiost** [comment]
> ### QA Update: ⚠️
> @makiost @tofumatt I've been looking at this ticket with @mohitwp and we understand it's a check from Storyboard to Figma CSS, but what about the items in the AC? I feel that the QAB needs to be a little more detailed when I am reading the AC. If a CSS comparison that's fine, but wanted to check before we jump into this QA. Thoughts welcome?

Hey, @wpdarren! This one is a bit tricky, as we have some limitations in testing all of the states and interactions in Storybook. The testing will be easier once the component is inserted in the TwG-settings setup and can be used in a "real world"-scenario, so a CSS and accessibility check is what we can do within storybook for now.

 The inspector console can be used to check more of the points in the AC, e.g. the `radio`-role on the component, as well as checking that the hidden `input`-element has the attributes corresponding to the image radio component (a checked, hidden input corresponds to a checked ImageRadio, etc). Should I update the QAB to include the inspector testing as well?

**Comment by wpdarren** [comment]
@makiost I feel the information you have given us here is fine.  We can compare the CSS with Storybook and Figma designs for now, including looking at the console for the checks in AC.  @mohitwp are you okay with taking this ticket on now we have the confirmation from Maciej?

**Comment by mohitwp** [comment]
@wpdarren Yes, working on it.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@makiost 

- I've noticed that the background color for the radio button is different. 

<details>

![image](https://user-images.githubusercontent.com/94359491/181007768-6feaba8b-f634-47fa-84d9-9e3db8d84a78.png)

![image](https://user-images.githubusercontent.com/94359491/181007893-a6e98049-acdf-43cc-834c-8ede1f19f146.png)

</details>

Also, noticed that width and height of the radio buttons are different from the Figma design. Is this intentional ?

<details>

![image](https://user-images.githubusercontent.com/94359491/181008260-ac2d2f81-4460-493b-a425-d8359ceaae21.png)

![image](https://user-images.githubusercontent.com/94359491/181008331-c1e704c0-dbf1-4bdc-bbff-35884b38eb3e.png)

![image](https://user-images.githubusercontent.com/94359491/181008502-c804786a-03a0-45f1-a2c3-cf7f12497cdc.png)

![image](https://user-images.githubusercontent.com/94359491/181008603-ab6232ab-e74b-4d92-9e29-c87179f659b1.png)

</details>

**Comment by tofumatt** [comment]
@mohitwp The width of the buttons should change with the contents, so the difference in width is okay.

But the background colour is a good catch, thanks! I didn't even notice it.

@makiost Can you make a small, follow-up PR for this issue just updating the background colour of the `ImageRadio` components without an image? Eg, this one:

<img width="344" alt="CleanShot 2022-07-26 at 15 33 31" src="https://user-images.githubusercontent.com/90871/181034399-807d3ea1-e466-4714-9554-894d7c9b25ad.png">

**Comment by makiost** [comment]
@tofumatt The follow up PR is now in CR 👍

**Comment by aaemnnosttv** [comment]
@makiost I found a few more things when reviewing your PR, please see the review for details 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 


Background color issue is now resolved.

<details>

**StoryBook**
![image](https://user-images.githubusercontent.com/94359491/181703771-31091b93-f9ec-452f-96d2-3d284efe96a5.png)

**Figma**
![image](https://user-images.githubusercontent.com/94359491/181703818-b268f469-e608-41c5-96d7-de62b42ce5a5.png)

</details>

**Comment by aaemnnosttv** [comment]
## Approval ⚠️ 

This looks good when comparing with the design, although there are a few details that are not quite right:

- The ACs call for a story that allows for the radio state to be changed but the current story has fixed/static states
- The current story raises the following console warning:  
> Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

This need not block the release as this isn't used yet but should be addressed in a follow-up issue.

**Comment by wpdarren** [comment]
@aaemnnosttv would you like us to create a ticket for this or have you already done so?

**Comment by aaemnnosttv** [comment]
@wpdarren created 😉
