### ISSUE TITLE
E2E Environment set up is run twice in Travis

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#546]
## Bug Description

In the current Travis config:
https://github.com/google/site-kit-wp/blob/4bd761ff60559e1a2fa3e65257b6fbceae0a1c7a/.travis.yml#L87-L88

This causes the install script to run twice unnecessarily. The `env:reset-site` command does not need to run on Travis as this is intended for resetting an existing environment. This is unnecessary on Travis as the environment is freshly installed and provisioned on every run.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/65031073-42ea4480-d949-11e9-9f43-562647fbf148.png)

## Additional Context

Example from recent job: https://travis-ci.com/google/site-kit-wp/jobs/236377778#L1422-L1506

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2Ee tests still run successfully

## Implementation Brief

* Remove the call to `env:reset-site` from `.travis.yml`

## Changelog entry

* N/A

**Comment by swissspidy** [comment]
After applying the same change to the AMP plugin in https://github.com/ampproject/amp-wp/pull/3275 I can confirm that removing that call makes sense.

Let's follow the proper processes on this one though :-)

**Comment by tofumatt** [comment]
Not much to QA here: the tests are still reset locally when the `npm run env:reset-site` command is used, but it's not longer used in Travis as expected. 🤷‍♂

Looks good to me!
