### ISSUE TITLE
Determine and show whether and where the Thank with Google supporter wall widget is placed

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5462]
The TwG settings UI should inform the user about whether and where the Thank with Google supporter wall widget is placed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG module should be able to determine (from the server-side) whether the module's supporter wall widget (see #5451) has already been added to a widget area.
    * Preferably, it should also be able to determine the exact list of sidebars / widget area names that it has been added to (i.e. array of strings). However, if during IB research it comes out that this would significantly complicate the implementation and increase the estimate, we may be okay only surfacing a more basic "is placed _somewhere_ or not" boolean.
    * Let's try to limit this to an `11` or maximum `15` estimate. If determining the exact widget areas makes it go beyond that, we can do the simpler approach.
* The above value (whichever of the two it is) should be made available to the JS side. It does not matter much how, except _if_ the logic to determine the above is somewhat expensive, a REST endpoint would be preferable over computing the value on every admin page load (especially since it won't be needed on every page load).
* The TwG `SettingsView` component's _Supporter wall widget_ information (see #5456) should be adjusted to be dynamic based on the above value:
    * If not placed at all, it should say what it does currently.
    * If placed and we know which areas, it should say "Placed in %s", where the placeholder is a comma-separated list of the sidebar / widget area names.
    * If placed and we don't know where, it should simply say "Active".
* It should be ensured that the existing TwG `SettingsView` Storybook story still shows correctly.
* A second Storybook story for the component should be added which shows the UI when the widget is already placed somewhere.

## Implementation Brief

* In the `Thank_With_Google` module:
  * Add a new datapoint `GET:supporter-wall-sidebars` to the datapoint definitions in the `get_datapoint_definitions` method.
  * Add a new case for the `GET:supporter-wall-sidebars` datapoint in the `create_data_request` method that returns an anonymous function that does the following:
    * Gets a list of all sidebars with their widget instance IDs using the `wp_get_sidebars_widgets` function.
    * Finds all sidebars that contain instances of the supporter wall widget which can be done by checking whether a sidebar contains a widget instance ID that matches the `googlesitekit-twg-supporter-wall-[0-9]+` pattern.
      * If a sidebar doesn't contain the supporter wall widget instance, but contains an instance of the block width (`block-[0-9]+`) then we need to check whether the block widget contains a legacy widget with the supporter widget in it. This can be done by pulling all instances of the block widget using `get_option( 'widget_block' )` call and checking the correct instance content on inclusion of the `googlesitekit-twg-supporter-wall` slug in it.
      * If it turns out that all sidebars have at least one instance of the supporter wall widget, the function should return `array( 'All sidebars' )` immediately.
    * Returns the array of found sidebar names. In order to get a sidebar name, call the `wp_get_sidebar` function to get sidebar details and take the `name` property from it.
* Add a new partial datastore `supporter-wall` to the `thank-with-google` module:
  * Create a new fetch store that pulls sidebars information for the supporter wall widget.
  * Add a new resolver `getSupportWallSidebars` that calls fetch stores' selector to get sidebars information if it hasn't been loaded yet into the state. 
  * Add a new selector `getSupportWallSidebars` that returns sidebars information.
* Update the `SettingsView` component in the `thank-with-google` module:
  * Get the sidebars information for the supporter wall widget calling the `getSupportWallSidebars` selector.
  * Update the appropriate section for the supporter wall widget information to display a small progress bar if the sidebars information is loading.
  * Display the same text and link as before if the sidebars information is an empty array.
  * Display comma separated sidebars if the sidebars information is not empty.

### Test Coverage

* Add jest tests for the new selector.

## QA Brief

* Add the supporter wall widget to a sidebar.
* Go to the TwG settings view and verify that you see the sidebar name there in the field for the supporter wall widget.
* Add the supporter wall widget to all sidebars.
* Go back to the settings view and verify that now you see the "All sidebars" text there.
* Remove all supporter wall widgets from all sidebars.
* Go back to the settings view and verify that now it shows the link to the widgets page.

## Changelog entry

* Determine and show whether and where the Thank with Google supporter wall widget is placed.

**Comment by eugene-manuilov** [comment]
@felixarntz, could you please review IB?

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@eugene-manuilov just one observation. 

When I added the widget to all the sidebars, the settings view shows it as 'all sidebars' in lower case. The other settings are in sentence case. Wondering if we should change this to 'All sidebars' for consistency.  Just to add: if you create a custom sidebar and name it in lowercase the issue issue applies with the widget name.  Not sure we can do anything about that?

![image](https://user-images.githubusercontent.com/73545194/182853264-354a0675-d9d9-4adf-8543-084c094b0121.png)

![image](https://user-images.githubusercontent.com/73545194/182855313-78642195-653d-4362-8b2f-9e22a1b2cd10.png)

**Verified:**

- When adding TwG widget to a sidebar, you see the sidebar name in the field for the supporter wall widget.
- When you remove all supporter wall widgets from all sidebars, the settings view now shows the link to the widgets page.

<details>
 <summary>Section Title</summary>



</details>

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When adding TwG widget to a sidebar, you see the sidebar name in the field for the supporter wall widget.
- When you remove all supporter wall widgets from all sidebars, the settings view now shows the link to the widgets page.
- Issue fixed from my [comment above](https://github.com/google/site-kit-wp/issues/5462#issuecomment-1205241875), the setting now appears as All sidebars.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/182855729-bbb3df24-3451-4819-93da-998907023113.png)
![image](https://user-images.githubusercontent.com/73545194/182855783-815be7dd-cb0c-471a-bc7f-c98b5f6dc7f8.png)
![image](https://user-images.githubusercontent.com/73545194/183071275-69725ae4-51df-42bc-b405-a8779b2a4434.png)

</details>
