### ISSUE TITLE
Remove legacy widget area constants.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5476]
## Feature Description

These widget area constants are unused, from the pre-unified dashboard days, and should be removed.

https://github.com/google/site-kit-wp/blob/82be6e111ff4ce67fa91bbe51fff3a47caed967d/assets/js/googlesitekit/widgets/default-areas.js#L19-L28

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The widget area constants detailed in the Feature Description should be removed.
* Ensure all references to them are removed from the codebase.

## Implementation Brief

* In `assets/js/googlesitekit/widgets/default-areas.js`:
    * Remove all the definitions and exported object properties for the widget area constants mentioned in the Feature Description.
* In `assets/js/googlesitekit/widgets/register-defaults.js`:
    * Remove the `registerWidget` function call for the `WIDGET_URL_SEARCH` widget.
    * Remove relevant imports which have become unnecessary after removing the said function call.
* Delete the following files:
    * `assets/js/googlesitekit/widgets/default-widgets.js`
    * `stories/dashboard.stories.js`
    * `assets/js/googlesitekit/widgets/components/URLSearchWidget.js`

### Test Coverage

* No tests need to be added/updated.

## QA Brief

* Same as AC. This ticket removes outdated functionality and linked stories in Storybook. All functionality should remain the same.

## Changelog entry

* Remove legacy widget area constants.

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – I came across this when I found the `URLSearchWidget` still around in Storybook (#5476). This is still being registered to the legacy widget area as well, so we should go through and make sure anything still using these (only) is also removed. This would probably come up anyways after removing them but just calling it out ahead of time 👍

**Comment by techanvil** [comment]
> Thanks @techanvil – I came across this when I found the `URLSearchWidget` still around in Storybook (#5476). This is still being registered to the legacy widget area as well, so we should go through and make sure anything still using these (only) is also removed. This would probably come up anyways after removing them but just calling it out ahead of time +1

Thanks @aaemnnosttv - I have added a second point to the AC to emphasis this.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by hussain-t** [comment]
@nfmohit, just a note for the future, tickets like these kinds of changes (deleting the legacy code) shouldn't be 3-pointers. This should've been 7 since we have to review it and test it carefully. Thanks!

**Comment by nfmohit** [comment]
> @nfmohit, just a note for the future, tickets like these kinds of changes (deleting the legacy code) shouldn't be 3-pointers. This should've been 7 since we have to review it and test it carefully. Thanks!

Understood and noted. I'll keep it in mind. Thank you, @hussain-t!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Confirmed that the URL search widget is [removed from Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/dashboard--url-search-widget)
- Went through the entity and main Site Kit Dashboard to ensure no issues appear in the UI.  
- Also checked the view only dashboard with dashboard sharing enabled.  

**Note:**  This was a quick check but we will make sure to complete a more thorough test when we do release QA.
