### ISSUE TITLE
Add setup error code information to the global base data object.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5479]
## Feature Description

Currently, if setup has failed, the global `_googlesitekitBaseData` object contains only an error message and redo URL. We also need to provide the original error code passed from the proxy server as the `setupErrorCode` property on the global object.

https://github.com/google/site-kit-wp/blob/16a446a84e4f111b75dd951f26e542dc2ebd3758/includes/Core/Authentication/Authentication.php#L850

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The global `_googlesitekitBaseData` object should contain the new property `setupErrorCode` which value should contain an error code returned by the proxy server if setup fails.
* The `core/site` datastore should have a new `getSetupErrorCode` selector that returns the `setupErrorCode` from the global object.
* The `ErrorNotifications` component should be updated to display the "get help" link that leads to the `{proxy}/support/?error_id={setupErrorCode}` URL which can be obtained using the `getErrorTroubleshootingLinkURL` selector introduced in https://github.com/google/site-kit-wp/issues/5423.

## Implementation Brief

In `includes/Core/Authentication/Authentication.php`:
- In the `inline_js_base_data` method, add the `setupErrorCode` property with a `null` value.
- Within the `! empty( $error_code )` condition, add the `setupErrorCode` property to set the value. Just below setting the value for `setupErrorMessage` property.
- The value should be the same as the `$error_code` which was obtained from `$this->user_options->get( OAuth_Client::OPTION_ERROR_CODE )`.

In `assets/js/googlesitekit/datastore/site/info.js`:
- Destructure the `setupErrorCode` property from `global._googlesitekitBaseData`.
- Pass `setupErrorCode` to the `receiveSiteInfo` action.
- In the `RECEIVE_SITE_INFO` reducer get it from the payload and return it within the `siteInfo` object.
- Add `getSetupErrorCode` selector that calls the `getSiteInfoProperty` helper function by passing the `setupErrorCode` as an argument.

In `assets/js/components/notifications/ErrorNotifications.js`:
- Get `setupErrorCode` using the `getSetupErrorCode` selector.
- Get the get help link for setup error using the `getErrorTroubleshootingLinkURL` selector.
- Pass an (error) object to the `getErrorTroubleshootingLinkURL` selector that contains the `code` property with the value of `setupErrorCode`.
- Pass `learnMoreLabel` and `learnMoreURL` props to the `BannerNotification` component.
- The `learnMoreLabel` should be "Get help".
- The `learnMoreURL` should be the URL returned by the `getErrorTroubleshootingLinkURL` selector.

### Test Coverage

- Add test cases for the `getProxySupportLinkURL` selector.
- In `assets/js/components/notifications/ErrorNotifications.test.js`, add a test case that verifies the get help link is available in the document.

## QA Brief

* Setup Site Kit. 
* Go to Setup another module. ie. Analytics.
* Hit `Cancel` when the setup flow asks for permission.
* You should see the Get Help Link in the dashboard with correct url for error code `access_denied`.

## Changelog entry

- When setup fails with an error from the proxy, show a "get help" link that leads to the relevant support page for the given error code.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov would you be able to confirm the behaviour detailed below is correct.  In the QAB it does not mention the behaviour when you click on the get help link, so I'd like to make sure that this is expected.  Thank you! 

**Verified:**

- When I connect Analytics, and then hit cancel at the oAuth page,  I am redirected back to the Site Kit Dashboard and 
a message appears with a `Get Help Link`.  The URL has the `access_denied` added to the end of the URL. 
`https://sitekit.withgoogle.com/support?error_id=access_denied`. 
- When the link is clicked, a new tab opens up and I am redirected to `https://sitekit.withgoogle.com/documentation/troubleshooting/using-troubleshooting-mode/ `

![image](https://user-images.githubusercontent.com/73545194/180997042-e0131bc6-1db9-4758-b93d-d7d864841f8e.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When I connect Analytics, and then hit cancel at the oAuth page,  I am redirected back to the Site Kit Dashboard and a message appears with a `Get Help Link`.  The URL has the `access_denied` added to the end of the URL. 
`https://sitekit.withgoogle.com/support?error_id=access_denied`. 
- When the link is clicked, a new tab opens up and I am redirected to `https://sitekit.withgoogle.com/documentation/troubleshooting/using-troubleshooting-mode/ `
- When I click on the `Redo the plugin setup` button I am sent back to the oAuth page to give permission. 

![image](https://user-images.githubusercontent.com/73545194/180997042-e0131bc6-1db9-4758-b93d-d7d864841f8e.png)
