### ISSUE TITLE
Add a "get help" link to the "reconnect_after_url_mismatch" notice. 

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5481]
## Feature Description

We need to add a new "Get Help" link to the notification that appears when site has changed its URL. The URL for the new "get help" link should be obtained using the `getDocumentationLinkURL` selector introduced in https://github.com/google/site-kit-wp/issues/5423.

https://github.com/google/site-kit-wp/blob/16a446a84e4f111b75dd951f26e542dc2ebd3758/includes/Core/Authentication/Authentication.php#L1110-L1117

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "reconnect after url mismatch" notification should display a new "Get Help" link that leads to the `{proxy}/support/?doc=url-has-changed` URL.

## Implementation Brief

- In `includes/Core/Authentication/Authentication.php`:
    - Locate the `get_reconnect_after_url_mismatch_notice` method.
	- Inside the method's `Notice` class definition, in the second parameter array, locate the function in the `content` property.
	- Inside the function, when the `$content` variable is assigned, add a full stop after the closing `</a>` tag. After the full stop, add a new `<a>` tag with `href` attribute having the fifth placeholder (`%5$s` - the support link) and the content as the sixth placeholder (`%6$s` - the get help string). It should also have a `target` attribute with the value of `_blank`.
	https://github.com/google/site-kit-wp/blob/4306cdda53c54ee2a4dcc16cbd9459352d9c0c9b/includes/Core/Authentication/Authentication.php#L1116
        - The fifth placeholder value should be `/?doc=url-has-changed` appended to the `get_proxy_support_link_url()` method of the same `Authentication` class. It should be escaped with `esc_url()`.
        - The sixth placeholder should be `Get Help` (translatable).
- In `assets/js/components/setup/SetupUsingProxyWithSignIn.js`:
    - Compose the "Get Help" link URL:
        - Use the `getDocumentationLinkURL` selector with the slug `url-has-changed` from the `core/site` store and assign it in a variable named `urlHasChangedHelpLink` (or something more relevant).
    - Create a new reassignable variable named `getHelp`.
    - After the `description` is displayed, check if `getHelp` is truthy and if so, display a `<Link />` component with an `href` prop pointing to the `getHelp` variable and an `external` prop with `true`. The content of the component should be `Get Help` (translatable).
    https://github.com/google/site-kit-wp/blob/4ebc69975bc624731085b12974fbb44142eb060c/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L303-L305
    - In the case where `DISCONNECTED_REASON_CONNECTED_URL_MISMATCH === disconnectedReason` is true and `urlHasChangedHelpLink` is truthy, assign `urlHasChangedHelpLink` to the `getHelp` variable.
    https://github.com/google/site-kit-wp/blob/4306cdda53c54ee2a4dcc16cbd9459352d9c0c9b/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L207-L215

### Test Coverage

- Verify the `Setup -> Using Proxy with Sign-in -> Disconnected - URL Mismatch` stories.
- Update VRT images if required.

## QA Brief

* Locate the Setup -> Using Proxy with Sign-in -> Disconnected - URL Mismatch story in storybook
* Verify that a new _Get help_-link has been added below the description
* Verify that the link opens in a new tab and that the URL is `<proxiedSupportURL>/?doc=url-has-changed`

----

* Create a new site and sign in with Site Kit.
* Change the URL of the site so Site Kit shows the "URL Mismatch notice" when accessing the dashboard.
* Verify there is now a "Get help" link beneath the URL mismatch notice message and it opens a `?/doc=url-has-changed` link in a new tab.

## Changelog entry

* Add a help link to the "site URL has changed" notice when Site Kit detects your site URL has changed.

**Comment by adamdunnage** [comment]
@eugene-manuilov Is this the same as what we have documented [here](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#redirect-uri:~:text=Unknown%20Error%20(code%3A%20redirect_uri%20mismatch))? Or is it slightly different?

**Comment by eugene-manuilov** [comment]
> @eugene-manuilov Is this the same as what we have documented [here](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#redirect-uri:~:text=Unknown%20Error%20(code%3A%20redirect_uri%20mismatch))? Or is it slightly different?

@adamdunnage, no this is different. This issue is for the case when the URL of the site has changed. The issue you are referring to happens during OAuth process.

**Comment by adamdunnage** [comment]
@eugene-manuilov Okay thanks for explaining. In which case I think that yes we should it from the errors document to the "learn more" redirects. 

@bethanylang Do you agree?

**Comment by bethanylang** [comment]
Makes sense to me, thanks!

**Comment by eugene-manuilov** [comment]
Thanks, @adamdunnage and @bethanylang. Adam, will you remove the "reconnect_after_url_mismatch" row from the error redirects and add it to the "learn more" redirects?

I have updated AC to use the redirect link from the documentation redirects but left the same "get help" label. The only question is where do we need to put that "get help" link, right after the `reconnect` link?

**Comment by eugene-manuilov** [comment]
Thanks, @nfmohit. Mostly looks good to me. Have a few comments:

> extend the `$content` variable with concatenation and include a new `<p>` tag containing a link (`<a>`) tag.

No need to put the new link into a separate `<p>` tag, it will make the link appear below the notice message. We need to add the get help link after the reconnect one.

> * Use the `getDocumentationLinkURL` selector with the slug `url-has-changed` from the `core/site` store and assign it in a variable named `alreadyConfiguredGetHelpLink` (or something more relevant).

How about `urlHasChangedHelpLink`?

**Comment by eugene-manuilov** [comment]
> * add a new `<p>` tag containing a `<Link>` component.

Same here, no need to put it into a separate `<p>` tag. It should go in the same paragraph.

**Comment by nfmohit** [comment]
Thank you @eugene-manuilov! I've updated the IB so that the `Get Help` link appears right after the `Reconnect` link.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
QA Update ⚠️ 

@eugene-manuilov @makiost 

I tried to create this scenario using dev plugin. I enter correct URL in dev plugin first and after that 'sign in with google' and done set up for site kit. Again, change custom URL under dev plugin and navigated to site kit dashboard. Here on dashboard I'm getting 'insufficient permission error' instead of 'URL mismatch notice'. 
Can you please guide me how can I create this scenario. Let me know if i missing any step ?

**Comment by eugene-manuilov** [comment]
@mohitwp I think the easiest way to replicate this scenario is to create a multisite instance with subdirectories. Such setup will allow you to create a subsite with a subfolder URL that you can change as you want on the general settings page. Just do something like this:

1. Create a new site.
1. Activate the multisite mode and configure it to be subdirectories.
1. Create a new subsite.
1. Install, activate and connect site kit on the subsite.
1. Go to the general settings and change the URL to a different folder.
1. Go back to the SK dashboard and verify that you see the get help link.

Let me know if it helps.
