### ISSUE TITLE
Add a "get help" link to the authentication request failed message.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5484]
## Feature Description

When the request to the authentication proxy fails, we show the wp_die screen with the appropriate message to the user. We need to update that message to include the new "get help" link that leads to the `{proxy}/support/?error_id=request_to_auth_proxy_failed` URL which can be obtained using the `getErrorTroubleshootingLinkURL` selector introduced in #5423.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Setup:: handle_action_setup_start` method should be updated to include the new "get help" link at the end of the error message for failed requests to the authentication server. The "get help" link should lead to the `{proxy}/support/?error_id=request_to_auth_proxy_failed` URL. https://github.com/google/site-kit-wp/blob/16a446a84e4f111b75dd951f26e542dc2ebd3758/includes/Core/Authentication/Setup.php#L133-L144

## Implementation Brief

- In `includes/Core/Authentication/Setup.php`:
    - In the class `__construct` method, create a new class property named `proxy_support_link_url` which should call the `get_proxy_support_link_url` method from the `Authentication` class instance (accessible via the `$authentication` parameter).
    https://github.com/google/site-kit-wp/blob/a6dd7a4dccfedb11fd82201e56408d9f1c7bd14e/includes/Core/Authentication/Setup.php#L84-L94
    - In the `handle_action_setup_start` method:
        - Before checking error for `$oauth_setup_redirect`, create a new variable named `$oauth_proxy_failed_help_link`.
        https://github.com/google/site-kit-wp/blob/a6dd7a4dccfedb11fd82201e56408d9f1c7bd14e/includes/Core/Authentication/Setup.php#L133
            - The variable should contain a `sprintf` function with:
                - translatable string as the first parameter. The string should contain an `<a>` tag with:
                    - `href` attribute, value for which should be the first placeholder (`%1$s` - the troubleshooting URL).
                    - `target` attribute, value for which should be `_blank`.
                    - content should be the second placeholder (`%2$s` - the Get Help string).
                - the second parameter should be `/?error_id=request_to_auth_proxy_failed` appeneded to `$this->proxy_support_link_url`. The entire URL should be escaped using `esc_url()`.
                - The third parameter should be `Get Help` (translatable).
        - The first error message should be updated:
        https://github.com/google/site-kit-wp/blob/a6dd7a4dccfedb11fd82201e56408d9f1c7bd14e/includes/Core/Authentication/Setup.php#L139
            - The existing placeholder (`%s`) should be changed to `%1$s`.
            - After the existing string, a full stop should be added followed by a second placeholder (`%2$s` - the get help link) and a full stop.
            - A new third parameter should be added to the  `sprintf` function call, which should simply be the `$oauth_proxy_failed_help_link` variable.
        - The second error message should be updated:
        https://github.com/google/site-kit-wp/blob/a6dd7a4dccfedb11fd82201e56408d9f1c7bd14e/includes/Core/Authentication/Setup.php#L143
            - The string should be wrappped with a `sprintf` function.
            - A placeholder (`%s`) should be appended to the existing string followed by a full stop.
            - The second parameter for the `sprintf` function should be the `$oauth_proxy_failed_help_link` variable.

### Test Coverage

In `tests/phpunit/integration/Core/Authentication/Setup_Test.php`:

- Update the `test_handle_action_setup_start__wp_error` test case to check for the full error message (the first error message in the IB).
- Add a new test case to check for the second error message in the IB.

## QA Brief

* QAing this would require reproducing an error when the `Sign in with Google` button is clicked. In order to get the error:
    * Go to the Site Kit connect splash screen (disconnect/reset if required).
    * Add this snippet to the site's `wp-config.php` file: `define( 'WP_HTTP_BLOCK_EXTERNAL', true );`.
    * Once added, click on the `Sign in with Google` button.
* The error message should contain a `Get Help` link, clicking on which should open the relevant support page in a new tab.

## QA:Eng

* In order to reproduce the second error, the only way I could find was to alter the condition.
https://github.com/google/site-kit-wp/blob/fed860f7411d8e2c6ae037715e90f20fc5202d25/includes/Core/Authentication/Setup.php#L176-L192
    * Alter the condition here so that `wp_die()` is called even though the `filter_var()` is truthy.
    * Go to the Site Kit connect splash screen (disconnect/reset if required).
    * Once added, click on the `Sign in with Google` button.
* The error message should contain a `Get Help` link, clicking on which should open the relevant support page in a new tab.

## Changelog entry

* Add a "get help" link to the message that appears when a request to the authentication proxy fails.

**Comment by techanvil** [comment]
IB :white_check_mark: 

@nfmohit I added a couple of points about writing tests and bumped the estimate to allow some extra time.

**Comment by nfmohit** [comment]
> @nfmohit I added a couple of points about writing tests and bumped the estimate to allow some extra time.

Brilliant, thank you @techanvil!

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit thanks for the QAB instructions!    I've followed them though and when I click on the sign in with Google button, this message appears rather than the expected behaviour in the QAB. 🤔 

![image](https://user-images.githubusercontent.com/73545194/183395261-74f39167-5dcd-48f4-85e2-be1b5ad1a04d.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The error message should contain a Get Help link, clicking on which should open a support page in a new tab.

![image](https://user-images.githubusercontent.com/73545194/183431308-e7773af1-0995-4df8-af19-ec30746314a2.png)

**Comment by hussain-t** [comment]
### QA:Eng verified ✅ 

- The error message should contain a `Get help` link, clicking on which should open a support page in a new tab.

![Screenshot 2022-08-09 at 2 29 36 PM](https://user-images.githubusercontent.com/24408261/183610747-82eef6b4-9a3a-4e98-ad1d-c37b318ed89e.png)

- The link matches `/support/?error_id=request_to_auth_proxy_failed`.

![Screenshot 2022-08-09 at 2 29 49 PM](https://user-images.githubusercontent.com/24408261/183610926-fc921cfd-5314-4dd7-99ea-4455323eeaba.png)

**Comment by felixarntz** [comment]
@nfmohit @techanvil Not a blocker, but I found one minor caveat in https://github.com/google/site-kit-wp/pull/5635#pullrequestreview-1070206745. If you find a few minutes to address this in a PR against `main`, that'd be perfect.

**Comment by nfmohit** [comment]
> @nfmohit @techanvil Not a blocker, but I found one minor caveat in [#5635 (review)](https://github.com/google/site-kit-wp/pull/5635#pullrequestreview-1070206745). If you find a few minutes to address this in a PR against `main`, that'd be perfect.

@felixarntz On it now. Thank you for pointing it out!

**Comment by eugene-manuilov** [comment]
@felixarntz #5681 PR has been merged into `main`. Moving this ticket back into Approval, since it has already been QA-ed.
