### ISSUE TITLE
Update all "Learn More" links to use the new /support/?doc= approach.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5485]
## Feature Description

We need to update all "Learn More" links in the plugin to use the new approach for support links that requires using `{proxy}/support/?doc={slug}` URLs instead of direct links to the documentation site. This approach will allow us to decouple the plugin codebase from actual documentation pages and shift routing responsibility on the proxy service shoulders.

The new "learn more" URLs should be computed using the new `getDocumentationLinkURL` selector introduced in #5423.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All learn more links in the plugin should be updated to use the new `{proxy}/support/?doc={slug}` URLs instead of hardcoded ones.
* Slugs for replaced documentation URLs should be taken from the first column of this spreadsheet: https://docs.google.com/spreadsheets/d/19dgLTylSt6rbBDZi5yiIYuCbuHA75KLjZMgAwlwfYBg/edit

## Implementation Brief

- All the files that use the hard-coded links for `Learn more` / `Learn more ...` should be updated using the `getDocumentationLinkURL()` selector of the `CORE_SITE` store.
- The `slug` parameter for the `getDocumentationLinkURL()` selector should be taken from the first column of the spreadsheet that matches the existing hardcoded URLs.

### Test Coverage

- No new tests are to be added.

## QA Brief

* Browsing the plugin, no support links (eg. links with "Learn more" text) should have `href` values that point directly to `https://sitekit.withgoogle.com/documentation`. Instead, learn more links should point to `https://sitekit.withgoogle.com/support?doc=`.

## Changelog entry

* Update support documentation links to use the new URL structure.

**Comment by felixarntz** [comment]
@eugene-manuilov ACs LGTM, however can you make the slugs from that doc all lowercase? This may be by accident anyway, but it would be a bit of a weird convention to have some start with a capital letter.

**Comment by eugene-manuilov** [comment]
Thanks, @felixarntz. Slugs are updated. Moving this ticket to IB.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@tofumatt @eugene-manuilov 

- I explore site kit dashboard and settings for 'Learn More' links and also followed this doc https://docs.google.com/spreadsheets/d/19dgLTylSt6rbBDZi5yiIYuCbuHA75KLjZMgAwlwfYBg/edit .

- I found that 2 slugs under doc are not redirects of 'Learn more' they are basically 'Get help' redirects - 'adblocker detected ' and 'url-has-changed'. 

- Also, I'm not sure how can I create scenario to get notification about `'url-not-part-of-this-site'` and `staging`  which are mentioned in https://docs.google.com/spreadsheets/d/19dgLTylSt6rbBDZi5yiIYuCbuHA75KLjZMgAwlwfYBg/edit . Can you please guide me how can I get 'Learn more' link for these two cases?

cc @wpdarren

**Comment by tofumatt** [comment]
> I found that 2 slugs under doc are not redirects of 'Learn more' they are basically 'Get help' redirects - 'adblocker detected ' and 'url-has-changed'.

Do you mean the text for these URLs is "Get help" instead of "Learn more"? If so, that is fine. The URLs still work as expected, right?

> Also, I'm not sure how can I create scenario to get notification about `'url-not-part-of-this-site'` and `staging` which are mentioned in https://docs.google.com/spreadsheets/d/19dgLTylSt6rbBDZi5yiIYuCbuHA75KLjZMgAwlwfYBg/edit . Can you please guide me how can I get 'Learn more' link for these two cases?

For these two errors ("URL not part of this site" and "staging") I'd say this can be skipped as the process to trigger that error is very niche and the code for it is exactly the same as the rest of the changes. To be honest I'm not even sure of the exact QA steps to get there right now, but if the rest of the changes worked without issue than this can be QA'd.

**Comment by mohitwp** [comment]
> > I found that 2 slugs under doc are not redirects of 'Learn more' they are basically 'Get help' redirects - 'adblocker detected ' and 'url-has-changed'.
> 
> Do you mean the text for these URLs is "Get help" instead of "Learn more"? If so, that is fine. The URLs still work as expected, right?
> 

Yes, these 'get help' links also working as expected.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- I explore site kit dashboard and settings for 'Learn More' links and also followed this doc for https://docs.google.com/spreadsheets/d/19dgLTylSt6rbBDZi5yiIYuCbuHA75KLjZMgAwlwfYBg/edit 

-  Learn more links now pointing to `https://sitekit.withgoogle.com/support?doc=`

- All links are also redirecting to correct support document.

<details>

Idea hub: 

![image](https://user-images.githubusercontent.com/94359491/184065036-a4709ba6-8140-485b-ac95-6fa837bc96a0.png)

Fix common issues:

![image](https://user-images.githubusercontent.com/94359491/184065069-c37eac9e-7a1f-4799-b615-a89cad19ba3c.png)

dashboard-sharing

![image](https://user-images.githubusercontent.com/94359491/184065146-afae55b5-6d5b-435b-8beb-abfa6567c04b.png)

ga4:

![image](https://user-images.githubusercontent.com/94359491/184065187-f211aa70-1c16-4c5e-8c27-e858920b1949.png)

not-enough-traffic :

![image](https://user-images.githubusercontent.com/94359491/184065201-b84723c6-8acf-4fac-adc5-df8d42aab53e.png)

already configured :

![image](https://user-images.githubusercontent.com/94359491/184065273-53c2aa1d-a6bc-4f00-a79f-1a6a61dc681c.png)

staging :

![image](https://user-images.githubusercontent.com/94359491/184065306-68e9e43c-66e5-473c-bdfb-35d8b7390046.png)

</details>
