### ISSUE TITLE
Prevent fatal error from sharing data being available for a non-existent module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5488]
See [this Slack thread](): We need to make sure that, if sharing data for a module which is no longer available is part of the sharing settings, submitting/modifying the sharing settings does not result in a fatal error. This currently happens for me consistently, because I have previously configured sharing settings for Idea Hub, but now disabled the module entirely (which can happen either through the `googlesitekit_available_modules` filter or in some cases feature flags).

Screenshot:
<img width="922" alt="Screen Shot 2022-06-30 at 11 28 53 AM" src="https://user-images.githubusercontent.com/3531426/176776664-52be115a-67f2-4869-b9ac-271e33f2b035.png">

The PHP fatal error I get is: `PHP Fatal error: Uncaught Exception: Invalid module slug idea-hub.` in `/includes/Core/Modules/Modules.php:557`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No fatal error must be triggered from submitting sharing settings that include data for a module that is not (realistically "no longer") available.
* If sharing data for a non-existent module is submitted, it should be ignored.
    * In other words, if sharing data for this module was previously set in the database option, it should just be kept at what it was before. If there was none set before, it should not be set either.

## Implementation Brief

- In `includes/Core/Modules/Modules.php`:
    - Create a new public method named `module_exists()` which accepts the parameter `$slug`.
    - Inside the method, simply use `get_module( $slug )` in a try/catch block returning `true` if it doesn't throw, and `false` if it does (similar to the `is_module_connected()` method).
    - Inside the `array_walk` callback for both `'add_option_' . Module_Sharing_Settings::OPTION` and `'update_option_' . Module_Sharing_Settings::OPTION` action hooks' callbacks, before getting the module data, do a check if the module exists using the new  `module_exists()` method. Execute the remaining code only if the module exists:
    https://github.com/google/site-kit-wp/blob/dbb1fe1a84d93188e85f5b0f4d8a79e313abcbab/includes/Core/Modules/Modules.php#L369
    https://github.com/google/site-kit-wp/blob/dbb1fe1a84d93188e85f5b0f4d8a79e313abcbab/includes/Core/Modules/Modules.php#L394

### Test Coverage

* No tests need to be added/updated.

## QA Brief

- Open the dashboard sharing settings modal and view a module that has been shared.
- The easiest one is enabling/disabling the Idea Hub feature flag.
- Ensure the Idea Hub feature flag is enabled.
- Make a change to a module and verify that it works.
- Disable the Idea Hub feature flag.
- Make a change to a module and verify that it doesn't throw any API error or display any error notices.

## Changelog entry

* Prevent error from appearing when sharing data exists for a non-existent module.

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit, your suggested approach would work, but let's adjust it slightly.

> * Create a new public method named `does_module_exist()` which accepts the parameter `$slug`

Let's use `module_exists(slug)` instead which is a bit more consistent with what we have and core convention (e.g. [`metadata_exists`](https://developer.wordpress.org/reference/functions/metadata_exists/), [`term_exists`](https://developer.wordpress.org/reference/functions/term_exists/))

> * Inside the method, just return a boolean value checking if the provided `$slug` exists in `get_available_modules()`.

Here we can simply use `get_module(slug)` in a try/catch returning `true` if it doesn't throw, and `false` if it does.

> * Inside this `array_walk` callback, before getting the module data, do a check if the module exists using the new  `does_module_exist()` method.

Note we need the same check in the callback for `add_option_` and `update_option_` there, not just the one place.

**Comment by nfmohit** [comment]
Thank you for the kind and detailed review @aaemnnosttv! I've updated the IB according to your suggestions.

**Comment by aaemnnosttv** [comment]
Great, thanks!

IB ✅

**Comment by hussain-t** [comment]
@makiost, could you update the QAB with more information?
>View a module that has been shared, but that has been removed. (Easies one is the idea hub feature flag in settings)
Ensure that no critical errors display in the module.

For example,
- Open the dashboard sharing settings modal and view a module that has been shared.
- The easiest one is enabling/disabling the Idea Hub feature flag.
- Ensure the  Idea Hub feature flag is enabled.
- Make a change to a module and verify that it works.
- Disable the Idea Hub feature flag.
- Make a change to a module and verify that it doesn't throw any API error or display any error notices.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified :


- Tested this on develop branch.
- Verified this for IDEA hub feature flag by following QAB.  Now we are not getting API error. 
- Also verified for other module like PSI and analytics via disconnecting module. It is not creating any API error.

cc @wpdarren
