### ISSUE TITLE
Organize `allTrafficWidget` feature tour

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5490]
## Feature Description

All feature tours currently live in their own file, except one for the first feature tour: `allTrafficWidget`. This should be moved to its own file just like the others.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The definition of the `allTrafficWidget` feature tour should be moved to its own file and exported as the default export
* The default export of `feature-tours/index` should not change

## Implementation Brief

* Inside `assets/js/feature-tours`:
    * Create `all-traffic-widget.js` which will contain the `allTrafficWidget` feature tour.
    * The file header comment can be copied over from `dashboard-sharing.js` by replacing the title of the feature tour with `All Traffic Widget`.
    * From `index.js`, copy over the entire `allTrafficWidget` definition object to the new `all-traffic-widget.js` file and export it as the default export for the file.
    * Move the relevant imports from `index.js` over to `all-traffic-widget.js` now that `allTrafficWidget` has been moved over.
    * Import `allTrafficWidget` from `all-traffic-widget.js` into `index.js` and make sure it is exported from `index.js` as default (this export is already being done now).

### Test Coverage

* No tests need to be added/updated.

## QA Brief

* Since this issue is just a refactor, there is no new functionality that needs to be tested. 
* Verify the allTrafficWidget feature tour, which was introduced in v1.25.0 (set this or earlier in the Tester Plugin's "Force initial Site Kit plugin version") still works normally.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by hussain-t** [comment]
Just a note, based on the GH history, @jimmymadon, you seemed not to have it assigned to you while in **Execution**.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `allTrafficWidget` feature tour still works normally.

https://user-images.githubusercontent.com/73545194/188642380-c0538a75-9589-4cce-a8e8-0265e6a2a9da.mp4
