### ISSUE TITLE
Top Earning Pages widget cannot determine adsense linked status in view-only mode for non-admin user

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5493]
## Bug Description

When AdSense and Analytics are both connected and shared, and the user is on the view-only Dashboard, the following call to `getAdsenseLinked` results in a console error due to the call to the Analytics settings endpoint not being allowed. This results in the widget rendering normally even when AdSense is not linked.

https://github.com/google/site-kit-wp/blob/6874c2e65ac45e4c1da65473a9a66669a8db3d6e/assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js#L121

See https://github.com/google/site-kit-wp/issues/5310#issuecomment-1168498502

## Steps to reproduce

1. Connect and share both AdSense and Analytics.
2. Navigate to the view-only Dashboard as a user whose rule the above modules are shared with.
3. The error should appear in the JS console.

## Screenshots

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/c6148e5a-32aa-4997-a4bd-82aa0c44d40c)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.77.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The view only dashboard should have awareness of the `adsenseLinked` state normally provided on load via the Analytics settings without having access to the module's settings
* No error should be raised due to a failing request for module settings
* When AdSense is linked with Analytics, no error should be raised on the view only dashboard when both modules are connected
	* When AdSense is not linked, it is expected that a restricted metrics error would be raised by the report request as there is no way to know proactively that the two are not linked.

## Implementation Brief

In `assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js`:
- Modify the `useSelect` hook that returns the `getAdsenseLinked` selector to return only if the user is not on the view-only dashboard **AND** the `getReport` call for Analytics is done using `hasFinishedResolution`. In other words, return `undefined` early if the user is on the view-only dashboard **AND** the `getReport` call for Analytics is still loading; otherwise, return the `getAdsenseLinked` selector.

### Test Coverage

- No new tests are to be added.

## QA Brief

According to AC the TypeError on the screenshot above should not appear in the DashBoard any more. All functionality should remain the same.

**Note for the QA team:** One little detail that we've discovered while code reviewing the PR for this issue is that in order to replicate the error in the console reported in this issue, besides the replication steps mentioned in the issue description, the Analytics and Adsense modules need to be shared with a non-administrator role (e.g. `editor`) and the view only dashboard should be accessed with that non-administrator role.

## Changelog entry

* Ensure the AdSense Linked status is correctly available in the Top Earning Pages widget when in view-only mode.

**Comment by aaemnnosttv** [comment]
@hussain-t the current IB does not satisfy the AC which does not call for hiding the widget on the view only dashboard. The widget _should work_ on the view only dashboard, the main problem here is how a view-only user wouldn't have access to the `adsenseLinked` value which is stored in module settings (even though it isn't really a setting). Perhaps what we should do here is make this value available somewhere else that a view-only user would have access to, and remove this from the module's settings. There isn't a clear best place for it to go that I can think of so we should brainstorm some solutions here.

**Comment by hussain-t** [comment]
Thanks, @aaemnnosttv. I have updated the IB to have a new REST endpoint to expose the data. Apart from that, we could create a new option for `adsenseLinked` instead of storing it in settings, that way, we avoid the situation where this one setting is visible to everyone whereas the rest are restricted. That could potentially be done in a follow-up issue.

**Comment by aaemnnosttv** [comment]
> * Add a new REST endpoint `GET:adsense-linked`, which returns the casted `bool` value of the `googlesitekit_analytics_adsense_linked` property from the Analytics options:

@hussain-t I think adding a REST endpoint to return a single boolean is overkill for this situation. Also, the `googlesitekit_analytics_adsense_linked` option is a legacy option that we only reference when there is no saved Analytics settings. It isn't updated like the current setting is when we detect the two are linked.

After thinking about this a bit more, I think all we have to do is delay the calling of the `getAdsenseLinked` selector until the Analytics `getReport` call is done loading in the `DashboardTopEarningPagesWidget`. This is where the restricted metrics are requested and requesting these will populate the `adsenseLinked` state after which selecting it will not trigger the fetch for Analytics settings in the resolver. The fact that we cache this error response for a short time when they are not linked should prevent this from being triggered on every request.

We can apply this change only when view-only to preserve the normal behavior for signed in users.

If that makes sense and sounds good to you, then let's do that 👍

**Comment by hussain-t** [comment]
Thanks, @aaemnnosttv, that makes perfect sense 👍 

It could be a 3-pointer; however, I have set it to 7 to have more space for testing. We can also add the GFI label to this ticket.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by nfmohit** [comment]
### Note

One little detail that I've discovered while code reviewing the PR for this issue is that in order to replicate the error in the console reported in this issue, the Analytics and Adsense modules need to be shared with a non-administrator role (e.g. `editor`) and the view only dashboard should be accessed with that non-administrator role. I've added this bit to the QA brief so that it doesn't get missed.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on develop environment using tester plugin.
- I'm able to reproduce issue on latest environment while accessing 'View only dashboard' with the user role having access to Analytics and AdSense.
- On dev branch - I'm not getting any console errors while accessing 'View only dashboard' with the user role having access to Analytics and AdSense.
- If AdSense not linked to Analytics, then `restricted metrics error` showing in console for both view only and admin dashboard, and it is same as latest environment.
- Verified for default WP role as well as for Custom user role.

<details>

Error on latest environment

![image](https://user-images.githubusercontent.com/94359491/192756888-1a82b71c-2c84-40fe-b245-aeb7232c82f3.png)

When AdSense not linked to Analytics -

![image](https://user-images.githubusercontent.com/94359491/192757120-73fd0d94-9238-4502-863e-a72b12136e84.png)

Develop branch -

Error in console not showing when AdSense linked to Analytics-

![image](https://user-images.githubusercontent.com/94359491/192757567-f28fd662-6eca-45cd-a897-3a7599f18a00.png)

![image](https://user-images.githubusercontent.com/94359491/192757617-a929695e-2b88-4592-bf45-28ab5d628372.png)


When AdSense not linked to Analytics -

![image](https://user-images.githubusercontent.com/94359491/192757337-891011e9-e9c4-488e-87ca-b18d098d62dd.png)

![image](https://user-images.githubusercontent.com/94359491/192757391-4b4769ff-18e6-45ee-a872-ddb3811189ca.png)

</details>
