### ISSUE TITLE
AdSense settings page showing account as not ready

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5498]
## Bug Description

Based on [one users report in the WordPress support forums](https://wordpress.org/support/topic/why-is-the-ad-still-showing-and-my-googleyour-site-isnt-ready/#post-15794261) the AdSense settings page within Site Kit are showing an account as not ready, despite being as approved AdSense account and having the site approved. 

From support I encounter this same behavior when checking an approved AdSense account, on a site that is also approved, and which has ads being served. 

The screenshot below is from the text site we used for AdSense, where ads are appearing on the site, and the account and site are approved. 

![image](https://user-images.githubusercontent.com/41326532/177118374-ac0cb969-7b5b-43f9-832f-7bb48e27452d.png)

The SH info for the support site don't reflect what's output in the SH settings page:

![image](https://user-images.githubusercontent.com/41326532/177120065-0f3ff4d0-7b36-474a-bafe-38aa8c9f726b.png)

**Note: This doesn't impact ads being served, it's only the status within a users AdSense settings.** 

## Steps to reproduce

1. Login to a site that is connected to AdSense, with an approved account and site
2. Check the Site Kit settings page

## Additional Context

 - The user shared their SH info with the support topic, showing an approved AdSense account and site. Ads do appear on this users site
 - The same appears on the oi.ie test site used in support, where ads appear, yet the SK settings page display a "Your site isn’t ready to show ads yet" notice within the settings page
- SK 1.77.0
- adsenseSetupV2 on the impacted users site and the support testing site
- the same occurs if disconnecting and then reconnecting the AdSense module. It will mention the site is ready for ads, and direct to the SK dashboard. Only if a user revisits their AdSense settings will they see the incorrect status ([Recording of experience](https://recordit.co/0rIF5MOuJe))

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a site's AdSense status is in the `"ready"` status, it should show a message `"Your site is ready for ads"` instead of `"Your site isn’t ready to show ads yet"`.

## Implementation Brief

* Add a new `case` statement to `assets/js/modules/adsense/components/settings/SettingsView.js`'s `switch ( accountStatus )` statement:

```js
case ACCOUNT_STATUS_READY:
	accountStatusLabel = __(
		'Your site is ready for ads',
		'google-site-kit'
	);
	break;
```

* Merge #5502.

### Test Coverage

* No new tests needed.

## QA Brief

1. Login to a site that is connected to AdSense, with an approved account and site. Using `oi.ie` is a good call here, because it exhibits the bug.
2. Check the Site Kit settings page.
3. The Account Status should be "Your site is ready for ads":

<img width="765" alt="CleanShot 2022-07-04 at 22 17 12" src="https://user-images.githubusercontent.com/90871/177217280-b09af6fb-bdd5-49b3-89d2-1af0ac05adc0.png">

## Changelog entry

* Fix AdSense status issue that appeared when an account was ready.

**Comment by jamesozzie** [comment]
Tested this on another AdSense site, with the same issue occurring. 
- SK 1.77.0
- AdSense setup v2
- SK settings page show the site as not ready while the SH info and AdSense platform confirm this as a site ready for ads


https://user-images.githubusercontent.com/41326532/177132969-e44bf2a3-6c2b-4c4e-8780-1304ee9bb868.mp4

**Comment by tofumatt** [comment]
Looks like this is a result of us missing a condition here: https://github.com/google/site-kit-wp/blob/5c84f29b4ef9f150addae1df3b20ef2aae12a35b/assets/js/modules/adsense/components/settings/SettingsView.js#L79

Those sites are showing as status `ready` but we don't have a case for that.

Should be an easy fix; I'll add ACs/etc. now. 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on 'main' branch.
- I'm able to reproduce issue on 'dev' and 'latest release' branch. 
- Issue is resolved on main branch. 
- Verified when 'adsensesetupv2' feature flag enabled.
- Verified when 'adsensesetupv2' feature flag disabled.

<details>

![image](https://user-images.githubusercontent.com/94359491/177302051-d1051210-b748-4139-9011-f3766c40e396.png)


https://user-images.githubusercontent.com/94359491/177303595-8bbbcd80-ef5e-4cdc-8f20-07e9042ed832.mp4

</details>
