### ISSUE TITLE
Search traffic widget showing gathering data on Analytics fields that are zero data state

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5499]
## Bug Description

While completing Release QA, I noticed odd behaviour that could be recreated in 1.77.0 and 1.78.0. 

Google Analytics is at zero data state and Search console is gathering data state.

On the `Search traffic over the last 28 days` widget on the dashboard, the `Unique Visitors from Search` and `Goals` fields have 'gathering data' although these are Analytics data, and should be showing zero.   

I was able to recreate this with and without the tester plugin.  Please note that no feature flags are enabled. 

As you can see from the screenshot, Analytics is zero data on the All traffic widget. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/d624173c-46ca-401f-8727-278da08ee41e)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
@aaemnnosttv I have moved this to AC as @wpdarren just created this - however please could you let us know if this should indeed go in the sprint this week based on its urgency in your opinion? cc @FlicHollis

**Comment by aaemnnosttv** [comment]
@wpdarren I'm unable to reproduce this. Can you provide steps to reproduce and/or share access to a site where this can be observed?

**Comment by wpdarren** [comment]
@aaemnnosttv  I have been able to recreate this on a few sites on InstaWP.   So, I set up a new site, had zero data set in the tester plugin (but the applies even without forcing it in the plugin) and then went to the Site Kit Dashboard and on Search traffic over the last X days widget, the Unique Visitors from Search and Goals fields have 'gathering data'

Here's a screencast:

https://user-images.githubusercontent.com/73545194/177559347-46389c08-faa8-4dd2-b1c7-ef9260293a14.mp4

**Comment by aaemnnosttv** [comment]
@wpdarren this was reported on the UA version of the dashboard. Can you reproduce it with GA4? If not, feel free to close.

**Comment by bethanylang** [comment]
@wpdarren Guessing that you couldn't reproduce, so changing this to `not planned` since it's not an issue in the GA4 version of the dashboard. Thanks!

**Comment by wpdarren** [comment]
@bethanylang Yes, I couldn't recreate this issue, so I closed the ticket.  I didn't realize there's a 'Not planned' option!
