### ISSUE TITLE
Getting validation error on homepage and archive pages:The extension 'amp-auto-ads' was found on this page, but is unused. Please remove this extension

### ISSUE THREAD

**Issue by TMsravan** [google/site-kit-wp#550]
Getting validation error on homepage and archive pages: The extension 'amp-auto-ads' was found on this page but are unused. Please remove this extension

https://hayatistudio.com/amp/

https://hayatistudio.com/sports/amp/

Due to this amp pages are not getting validated.

https://monosnap.com/file/nozsxqlXPYSfDS8NffVKIse8izlW8k

**Comment by jamesozzie** [comment]
@TMsravan You will need to raise support question for the WordPress plugin amp for wp. I can't see any trace of amp auto ads setup on your site by Site Kit. 

And for additional information on your AMP URL's you only have the auto ads header code placed, and not the body code. See steps [here](https://ampforwp.com/tutorials/article/how-to-set-auto-ads-in-amp/#3-with-the-help-of-our-ampforwp-plugin), or submit a support request on the relevant WordPress [support forum](https://wordpress.org/support/plugin/accelerated-mobile-pages/).

**Comment by TMsravan** [comment]
For ADS we are using : Ads for WP - Advanced Ads & Adsense Solution for WP & AMP

I have deactivated this plugin as well and checked the issue.

Please see recorded video:

https://drive.google.com/file/d/1vuwLzm98XGhPFlLNmoRD585LCSkDXbB7/view

We didn't place any auto ads header code in head section in AmpforWp plugin.

Please see this screenshot: https://monosnap.com/file/K9v0V0ACBtkv5i5ZHDPdQ9YohMPpBy

**Comment by jamesozzie** [comment]
@TMsravan Thanks for the video, very useful. As you are using a mix of plugins it's hard to pinpoint the exact issue. Some caching plugins also concatenate scripts and stylesheets, which could impact your amp validation errors. Can you try the following:
- Temporarily disabling your caching plugins
- Temporarily disable the Cloudfare plugin
- Activate Site Kit
- From an incognito window perform an amp validator test on your site

**Comment by saadhiyarao** [comment]
@jamesozzie I tried these steps but still have the issue https://bustimings.in/

**Comment by jamesozzie** [comment]
@saadhiyarao If you'd like to [open a WordPress support from topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) we would be happy to take a look. 

Note that while Site Kit does insert Auto Ads for AMP code if a user has selected that option you may find better luck posting the question with the [AdSense Help Center](https://support.google.com/adsense/?hl=en#topic=3373519). There could be a variety of reasons why ads don't appear on your site, resulting in AMP validation errors. We'll help you as much as we can in Site Kit Support by checking your snippet placements and AdSense module setup.
