### ISSUE TITLE
Truncate module owner's username if too long for view-only menu

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5500]
## Bug Description

While testing #5381 I identified a small observation/enhancement that was out of scope. 

On Dashboard Sharing, in the view only menu, when you have an administrator with a username that is 25 characters or more, it causes problems with the layout.  I am wondering if we should cut the username off at a certain amount of characters with ellipsis like we do on other parts of the plugin. As you can see from the screenshot on desktop it goes right to the edge. (and the same with mobile.). I realise 25 characters is a silly amount of characters for a username, but users be users! 😄 

<details>
 <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/73545194/176890040-3d85af01-2bc2-4a41-9b65-eadecb9344fd.png)

</details

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The service owner area of the view-only menu should not extend beyond the menu, regardless of the length of its contents
* Usernames that do not fit into the given area should be truncated with an ellipsis: e.g. 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/1621608/182445504-59888096-dc9f-4f34-a2d5-7915c6ba7039.png">
	- The truncated element should show the full untruncated username on hover

## Implementation Brief

* Update `.googlesitekit-view-only-menu__service--owner` with the following additional CSS rules
    * `text-overflow: ellipsis`
    * `overflow: hidden`
* Update the element containing the username (currently a `strong` tag) with a `title` attribute with the same value so that the full username is visible on hover

### Test Coverage

* Update VRT reference images for any affected view-only menu scenarios

## QA Brief

* Go to the Site Kit Dashboard as a view-only user.
* Open the Dashboard Sharing view-only menu.
* Verify that longer usernames are truncated with ellipsis (...) instead of just cutting off or going beyond the container (similar to the screenshot in the ACs).

## Changelog entry

* Truncate long usernames in Dashboard Sharing.

**Comment by eugene-manuilov** [comment]
> Update `.googlesitekit-view-only-menu__service--owner` with the following additional CSS rules
> * `text-overflow: ellipsis`
> * `overflow: hidden`

@aaemnnosttv we should also add the `title` attribute with the owner name so that users can see it when they hover over the element.

**Comment by aaemnnosttv** [comment]
Good call @eugene-manuilov – I'll add this as well 👍

**Comment by eugene-manuilov** [comment]
Thanks, @aaemnnosttv. IB ✔️

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- Longer usernames are truncated with ellipsis (...) instead of just cutting off or going beyond the container (similar to the screenshot in the ACs).

<details>
 <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/73545194/186051824-9acf666b-19fd-471c-aad1-b76893467363.png)

</details>
