### ISSUE TITLE
Add a users site status to the AdSense settings screen

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5503]
## Bug Description

Now that we can determine a users site status, which we output in a users Site Health info, include this within the AdSense settings page. This would be an improvement to asking users to click on a link to the AdSense platform to determine the status. 

<kbd> ![image](https://user-images.githubusercontent.com/41326532/177280985-14a8b113-5978-4044-bc55-b6667e41448d.png)

**A site status as it may appear within a users SH info can be seen below:**

<kbd> ![image](https://user-images.githubusercontent.com/41326532/177281689-4ce4e330-5fb8-4602-89cb-006ef7a97c9c.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The AdSense `SettingsView` component should be enhanced to support the V2 account and site statuses and thus display more accurate information on the account and site. More specifically:
* The "Account Status" field should display a correct message also supporting the V2 account statuses.
    * `ACCOUNT_STATUS_NEEDS_ATTENTION`, `ACCOUNT_STATUS_CLIENT_REQUIRES_REVIEW`, `ACCOUNT_STATUS_CLIENT_GETTING_READY` --> use the same message as for `ACCOUNT_STATUS_NO_CLIENT` and `ACCOUNT_STATUS_DISAPPROVED`
    * `ACCOUNT_STATUS_READY` --> already covered, good as is
* The "Site Status" field should, _if_ the `adsenseSetupV2` flag is enabled, display a message about the site status in front of the link to see the site status in AdSense.
    * `SITE_STATUS_NEEDS_ATTENTION`, `SITE_STATUS_REQUIRES_REVIEW` --> _You need to fix some things before your site is ready._
    * `SITE_STATUS_GETTING_READY` --> _Your site is getting ready._
    * `SITE_STATUS_READY` --> _Your site is ready for ads._
    * `SITE_STATUS_READY_NO_AUTO_ADS` --> _Your site is ready, with auto-ads disabled._
    * Whenever one of the above messages is displayed there (i.e. when `adsenseSetupV2` flag is enabled), the link to the site status in AdSense should be displayed right after, however it should then simply say "View in AdSense" (instead of the "Check your site status").
        * This link should be made more accessible for screen reader users by including a hidden part of the sentence so that for screen reader users it says "View site in AdSense". See a similar link in the Analytics `SettingsView` for how to do that.

## Implementation Brief

* Create a set of conditionals in the AdSense `SettingsView` component that follows the logic outlined in the ACs.
* See PR #5563 for a starting point on this issue.

### Test Coverage

* No new tests required.

## QA Brief

* Note: It is not easily possible to test this enhancement using the Force AdSense Account/Site Status feature of the Tester plugin.  This is because before AdSense setup V2 is complete, the Settings view solely shows the "Complete Setup" link. And once AdSense is connected, the site account/status comes back as "ready". So try this on real AdSense connected site data too.

## Changelog entry

* Update the AdSense settings to display the site status when available.

**Comment by felixarntz** [comment]
@eclarke1 @FlicHollis This is a follow-up that support raised, which is something we missed during the `adsenseSetupV2` work. Would be great if we could get that into the upcoming sprint and the 1.80.0 release.

**Comment by tofumatt** [comment]
Given the attached PR is more than a few lines, an IB solely consisting of "Merge a PR" is a bit tough to review 😉

I've amended the IB to mention the switch case, but in the future best to at least include a summary of the PR's approach.

I guess in this case the ACs are the approach, but in that case it's fine to just say that rather than making the PR as the IB. 😅

**Comment by tofumatt** [comment]
IB ✅

**Comment by jimmymadon** [comment]
@tofumatt I agree - should've just mentioned to follow the ACs for the IB here. 

There was probably no need to 'try this out' as it was a bit straightforward. But for some reason I did (probably wanting to check if the `siteStatus` was available here). So having spent time reading the issue / testing it out, it made sense to just complete it and add the QAB. Guess this can be directly CR/MR'd and moved to QA?

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified 👍 

- Verified when 'adsensesetupV2' feature flag is active.
- Verified using 'oi.ie' site.
- Also, verified after forcing adsense status to 'ready' using tester plugin.

<details>

![image](https://user-images.githubusercontent.com/94359491/181221064-c86dd809-2dbb-4d94-a3aa-e8175411934c.png)

![image](https://user-images.githubusercontent.com/94359491/181221111-cd176c76-4c02-483b-a01a-e4051a7cae74.png)

</details>

**Comment by aaemnnosttv** [comment]
Thanks @jamesozzie – this looks like a site that went through the v1 setup flow, in which case I don't think we would know if the site is ready or not by that status as before. Perhaps we should amend this change to remove the added status label in this case. I'll create a quick PR for this.

Part of this seems to be a separate issue where we should perhaps consider updating the site status if we detect an older one and the v2 setup is enabled.
