### ISSUE TITLE
Update the ReportError component to show the get help link

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5507]
## Feature Description

We need to add the "Get Help" link to the `ReportError` component to let users to get to the appropriate documentation page for the given error.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ReportError` component should be updated to display the "Get Help" link as shown on the [Figma mock](https://www.figma.com/file/Udjruyv8y648ZqyahCAzCK/Notification---Errors?node-id=10%3A10) next to the retry button, if the retry button is displayed at all. 
![image](https://user-images.githubusercontent.com/873049/177322515-e9609662-5fbe-45c1-8683-ddfd63b2bb0e.png)
    * Clicking on the Get Help link should redirect the user to the appropriate page on the documentation site.
    * The UI of the `ReportError` component **should not** change, this is out of scope for this ticket, the only thing that is required is to add the "get help" link with a small extra text `Retry didn't work?` in a similar way that it is done on the Figma mock.
    * If the "Retry" button does not apply to the `ReportError`, only the "Get help" link should be displayed instead (still with the same regular link appearance, but without the "Retry didn't work?" prefix).

## Implementation Brief

In `assets/js/components/notifications/CTA.js`:
- Add an optional prop `children`.
- Render the `children` property at the end of the `.googlesitekit-cta` div.

In `assets/js/components/ReportError.js`:
- Update the `CTA` element rendering to use the children approach to render the retry button appended with `Retry didn’t work?` text and `Get help` link. If there is no retryable errors, then just display the `Get help` link in children.
  - Remove `ctaType` and `ctaLabel` props from the `CTA` component
  - Move the `onClick` property from the `CTA` component to the retry button defined in children. 
  - Fix the styles of the button and text alignment (only) to match the Figma design.
- To get an URL for the "get help" link, pass the first item of the `retryableErrors` array to `getErrorTroubleshootingLinkURL()` selector of `CORE_SITE` store.

### Test Coverage

- In `assets/js/components/ReportError.test.js`, add a test case that verifies the get help link is available in the document.
- In `assets/js/components/ReportError.stories.js`, verify the existing stories that render the `Retry` button has the get help link.

## QA Brief

* Check the ReportError stories to see the newly added Get Help links. 
    * Check Variants with both Retryable and Not-retryable errors. 
* To test it on a real site:
    * Add the following **PHP** snippet on a mu-plugin or function.php.
    * Visit the Dashboard to see the Errors. 
    * There should be get help link. 

```php
add_filter(
	'rest_pre_dispatch',
	function( $res, $_s, $req ) {
		if ( $req->get_route() == '/google-site-kit/v1/modules/analytics/data/report' ) {
			return new WP_Error( 'rest_bad_request', 'Intentionally broken for testing.', array( 'status' => 400 ) );
		}
		return $res;
	},
	10,
	3
);
```

## Changelog entry

* Add "get help" links to error messages.

**Comment by eugene-manuilov** [comment]
@felixarntz could you please review the AC?

**Comment by eugene-manuilov** [comment]
Updated. Does it look okay now, @felixarntz?

**Comment by felixarntz** [comment]
@eugene-manuilov Thanks, LGTM!

**Comment by eugene-manuilov** [comment]
Thanks, @hussain-t. A few comments for you and one for Felix.

> * Add an optional prop `getHelpURL`.
> * If `getHelpURL` is defined, render a `<p>` element with `Retry didn’t work? Get help` text next to the `Retry` button.

This "retry didn't work" phrase and the whole get help concept seems to be out of scope for the `CTA` component. I think it would be better if we define it in the `ReportError` component and pass it into the `CTA` one.

> * To get the `getHelpURL`, pass the first item of the `retryableErrors` array to `getErrorTroubleshootingLinkURL()` selector of `CORE_SITE` store.

I understand why we want to get the first item of the retryable errors list but it does not include some errors that need "get help" links as well. For example, errors for required scopes and insufficient permissions will also need "get help" links, but we don't display the retry button for them.

@felixarntz, what should we do in this case? Just display the "Get Help" link instead of the Retry button?

**Comment by eclarke1** [comment]
@eugene-manuilov given Hussain may not be heading on parental leave, do you feel like you could finish up this IB, or identify someone else to hand this over to please?

**Comment by eugene-manuilov** [comment]
@felixarntz could you please review IB and answer the question in this https://github.com/google/site-kit-wp/issues/5507#issuecomment-1180229924 ?

**Comment by felixarntz** [comment]
@eugene-manuilov Apologies for missing this earlier. We should then only show the "Get help" link if "Retry" does not apply. I have added an additional point to the ACs for this.

@hussain-t The IB looks good to me as is, the only thing should be now to add a reference to the new point and how to implement that.

**Comment by eugene-manuilov** [comment]
Thanks, @felixarntz. I took over IB for this ticket. IB is updated. Does it look good now?

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov the stories in Storybook do not look like the FIgma design mocks.   I'm [looking at](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-reporterror--default-report-error) the `ReportError` components.   It might be because of the GM2+ styling but struggling to test based on the QAB.  Thoughts?

**Comment by eugene-manuilov** [comment]
> the stories in Storybook do not look like the FIgma design mocks. I'm [looking at](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-reporterror--default-report-error) the `ReportError` components.

@wpdarren check AC it says that UI changes are out of scope for this ticket. Just new link should be added.

> ... but struggling to test based on the QAB.
>
> Also, rather than relying on Storybook to QA this, do we have instructions where we can trigger these report errors, maybe some code or a browser extension that we can use to make them error? I'd like to be able to test this on a site.
>
> Thoughts?

@kuasha420 could you please provide a more detailed QAB and maybe a snippet that can be added to the `functions.php` file to break some report requests?

**Comment by mohitwp** [comment]
Hi @kuasha420 ,
When you have time can you please look into the QAB ?

**Comment by kuasha420** [comment]
@mohitwp I have updated the QA Brief. Cheers cc @wpdarren

**Comment by mohitwp** [comment]
### QA Update ✅ 

- I verified error notification for both Retryable and Not-retryable errors.
- I generated 'Retryable' error through code mentioned in QAB and by using network tab. 
- Verified on mobile devices.

<details>

![image](https://user-images.githubusercontent.com/94359491/183081274-b2ec6dfb-b217-460a-b03d-6ff4dc58c351.png)

![image](https://user-images.githubusercontent.com/94359491/183081324-d6cc3673-19d2-4dce-b20d-711a020ad619.png)

![image](https://user-images.githubusercontent.com/94359491/183081359-273bb473-5f22-43b2-b828-fe599e5ac265.png)

![image](https://user-images.githubusercontent.com/94359491/183081574-cfd443d1-eb1a-4dee-ba6d-ff17f2efd620.png)


</details>
