### ISSUE TITLE
Add ESLint rule to enforce consistent use of boolean JSX attributes

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5508]
## Feature Description

Following up on this comment, https://github.com/google/site-kit-wp/pull/5336#discussion_r910222392, we should make use of the [`react/jsx-boolean-value`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) ESLint rule to enforce boolean attribute notation to always be `someAttribute` as opposed to `someAttribute={ true }`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint rule [`react/jsx-boolean-value`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) should be added to our ESLint config, using the value `"never"` to enforce boolean attribute notation as described in the Feature Description.
* Any resulting linting errors should be fixed.

## Implementation Brief

- Within `.eslintrc.json`:
  - Add `react/jsx-boolean-value` to the rules object with the configuration `[ "error", "never" ]`.
- Run `npm run lint:js-fix` to fix any resulting linting errors.

### Test Coverage

* No new tests needed.

## QA Brief

**No QA needed.**

* This doesn't actually affect any code as the changes are just code styling—JSX treats this as the same thing, so no QA is needed for this change, as long as the tests still pass.

## Changelog entry

* N/A

**Comment by bethanylang** [comment]
@techanvil Checking in here, thanks!

**Comment by techanvil** [comment]
Thanks @bethanylang, I've not forgotten about this, just had a number of things on my plate and have been trying to balance those with the ongoing sprint requirements as usual. I should be getting round to this one soon.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
Nothing more to do here, sending to Approval
