### ISSUE TITLE
Minor UX/UI issue on Dashboard Sharing feature tour in specific scenario

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5521]
## Bug Description

A very minor UX/UI observation. Where the user dismisses the tour at step 1 and they click on the dashboard sharing settings icon, the tour is triggered again. When the tour tooltip appears on 'add user role' the highlighted area slightly overlaps the icon. It's more of an issue on Safari but noticed it on Chrome too.

![image](https://user-images.githubusercontent.com/73545194/177988740-82306c9f-31b4-4886-ae85-9fd3ceffe6a5.png)

Worth noting that moving to the next step then moving back will move the outline to the correct place:

![CleanShot 2022-07-08 at 14 32 20](https://user-images.githubusercontent.com/90871/178002134-62133d56-d415-4757-adc2-fa6ddd861ff1.gif)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When dismissing the first step of the feature tour for Dashboard Sharing, then opening Dashboard Sharing modal and seeing the next step of the tour, the tour should appear over the "Add Roles" section without looking like it's "off". eg it should look like this:

<img width="1003" alt="CleanShot 2022-07-08 at 14 31 57" src="https://user-images.githubusercontent.com/90871/178002035-47fce103-1be1-4ee4-9935-2f5a1907b2a3.png">

## Implementation Brief

In `assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.js`:

- Change the following `useEffect` to a `useCallback`, assigning the result to a constant with a suitably descriptive name, and remove the use of `dialogOpen` from it.
https://github.com/google/site-kit-wp/blob/970de0d270d0495f077427507b742eb3be09e6d6/assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.js#L106-L111
- Pass the resulting callback to the `Dialog` using the [`onOpen`](https://github.com/material-components/material-components-web-react/tree/v0.15.0/packages/dialog#dialog) prop.

### Test Coverage

- No new tests needed.

## QA Brief

* Enable the dashboard sharing feature flag
* Open the feature tour and dismiss it after its first step
* Open the dashboard sharing settings again
* The feature tour should resume in the correct step, with the tooltip positioned correctly above the relevant component.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Great find @techanvil 👍 

IB ✅

**Comment by makiost** [comment]
> ### QA Update: ⚠️
> @makiost in the QAB it says:
> 
> > The feature tour should not pop up again on this branch, compared to the current version where it pops up again.
> 
> Is that correct? When I click on dashboard settings icon the modal does pop up with the feature tour appears a it displays correctly now.
> 
> ![image](https://user-images.githubusercontent.com/73545194/182416994-07acf044-c054-4bb6-8012-46ce481ddb62.png)

My bad! You're correct, @wpdarren , the tour resumes at the correct spot with the correct tooltip placement. I'll update the QA brief right away!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When dismissing the feature tour and then clicking on the dashboard sharing settings icon, the feature tour appears and the tooltip is positioned correctly above the all roles field. 
- Tested this on a few different screen resolutions and the tooltip always highlighted the all roles field. 

![image](https://user-images.githubusercontent.com/73545194/182595256-c97d1484-8e4c-4ca3-9a0f-b78e4f252018.png)
