### ISSUE TITLE
Update readme FAQ section on AdSense ads

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5523]
There is new content for the "Why aren't any ads appearing on my site after I connected AdSense?" FAQ item that should be incorporated into the plugin `readme.txt`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Why aren't any ads appearing on my site after I connected AdSense?" FAQ item in `readme.txt` should be updated with the [revised content in this doc](https://docs.google.com/document/d/1-WqN4EjRdw1bM8i1bFGY_yc6r5ATObR7tRDpgpThX7o/edit?resourcekey=0-HCR0cYrCQHY4KhDVcxMAYg).

## Implementation Brief

* In `readme.txt`:
*  Search for the `Why aren’t any ads appearing on my site after I connected AdSense?`-string to locate the section to be changed

<details>
  <summary>Replace the section with the following copy</summary>
  
```
If you're new to AdSense when you connect via Site Kit, your new AdSense account and your site will need to be manually reviewed and approved for ads by the AdSense team. Ads will not display until your account and site have been approved. [Check out this guide for more information about the approval process and timeline.](https://support.google.com/adsense/answer/76228)

You can check your approval status in Site Kit by going to **Settings > Connected Services > AdSense** and clicking **Check your site status**. This link will direct you to AdSense. If you see "Ready," your account and site have been approved and should be displaying ads. If you see "Getting ready...," your account and site are still under review and your site will not display ads until they have been approved.

If Site Kit has successfully added the AdSense snippet to your site and your account and site have been approved, but your site is still not showing ads, [contact the AdSense Help Center for assistance](https://support.google.com/adsense/#topic=3373519).

You can find out more information on how Site Kit works with AdSense in our [Managing AdSense guide](https://sitekit.withgoogle.com/documentation/using-site-kit/managing-adsense/).

```
</details>

### Test Coverage

* No new tests/updates to existing tests need to be added for this issue.

## QA Brief

* Use any text editor to check the changes in the readme.txt file.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
cc @bethanylang @jamesozzie

**Comment by techanvil** [comment]
Hey @makiost, looks like some of the formatting has been lost in your copy/paste - notably the **bold**. Even though the file is `readme.txt` it's still using the markdown format, so please can you update the text with the necessary formatting?

**Comment by makiost** [comment]
@techanvil Wrapped the copy in a code block now, so that GH doesn't format it automatically.  👍

**Comment by makiost** [comment]
> > @techanvil Wrapped the copy in a code block now, so that GH doesn't format it automatically. +1
> 
> Hey @makiost, I guess I should have been a bit more specific. The words/phrases **Settings > Connected Services > AdSense**, **Check your site status** and the **and** are bold in the source document. Could you please wrap these in the markdown `**bold**` syntax, just to make sure this detail isn't missed?
> 
> Feel free to revert to non-code-block or keep as it is, I thought it was alright before in that regard, but it's also perfectly OK in a code block too :)
> 
> To be honest, I should probably have referred you to the **Avoid duplicating the ACs in the IB** section in the [handbook](https://docs.google.com/document/d/17eVCooecdDD2s6HluvZA3jBEH7hrGKgudJ3Tyu3JlZA/edit#heading=h.1h39rkiqvgjc) but we are not super strict about these guidelines and I figured it's also quite useful to have the copy here in case the source doc is unavailable for some reason.

Aah, totally missed the bolder text @techanvil 👍 I added the copy here since I had to request access to the document to get it, so I thought it would be good to drop it here, so that the engineer picking it up for execution has everything to complete the task, just in case they need to request access as well.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by aaemnnosttv** [comment]
Nothing to QA here, moving to Approval 👍
