### ISSUE TITLE
Implement TwG setup UI for publication setup completed scenario

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5525]
Follow-up to #5455: The actual UI for the `SetupPublicationActive` component should be implemented based on the Figma design.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupPublicationActive` component should have its proper UI implemented, from [this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A6408).
    * Since the 3 other UIs for different scenarios (see #5526, #5527, #5528, also the 3 alternate screens next to this one in Figma) are very similar to this one (only different copy, different button behavior, potentially different button style), consider implementing a reusable component that uses props for the pieces that can vary based on the 4 scenarios for the publication step.

## Implementation Brief

Create a new reusable component called `SetupPublicationScreen` (or any suitable name) in `assets/js/modules/thank-with-google/components/common` directory with the following details:
- It takes the following props:
  * `title` - the title string
  * `description` - the description string
  * `children` - the children to render. We can compose and render with any children we want in this approach. Either it could be a `Button` or `Link` component.
- Render the `title` and `description` strings as `h3` and `p` tags respectively.
- Fix the `title` and `description` styles to match the Figma design.
- Render the `children` passed as props.

In `assets/js/modules/thank-with-google/components/setup/SetupPublicationActive.js`. This component is being implemented in #5455:
- Render the `SetupPublicationScreen` component with the following props:
  * `title` - "Congratulations!"
  * `description` - "Your account is now active. To get started, customize the appearance of Thank with Google on your site."
  * Render the `Button` component, which is being implemented in #5455 as children of the `SetupPublicationScreen` component.
  * Add `ariaLabel` prop to the `Button` with the value "Customize Thank with Google".
- If necessary, create a common class to fix the button styles to match the Figma design so that it can be used in the setup-related components.

### Test Coverage

- Verify the `SetupMain` component story for this scenario works as expected.

## QA Brief

* QAing this would require making sure the **Thank with Google** publication setup completed scenario is according to the Figma design as mentioned in the AC.
* For CR, [this story](https://google.github.io/site-kit-wp/storybook/pull/5576/?path=/story/modules-thank-with-google-setup-setupmain--publication-active) can be used for verification.
* For QA, [this story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup-setupmain--publication-active) can be used for verification.

## Changelog entry

* Implement Thank with Google setup UI for the publication setup completed scenario.

**Comment by hussain-t** [comment]
@felixarntz, what should happen when the `Customize Thank with Google` button is clicked?

**Comment by felixarntz** [comment]
@hussain-t This was deliberately excluded from the ACs here since implementing the button behavior is already part of the #5455 ACs. Please review those for context. So this shouldn't be changed to a link, but keep the behavior implemented as part of that issue.

The rest of the IB looks good, though one thing: You're including many props in the list, which makes sense given the flexibility needed. However, I think we could reduce the number of props by passing a single prop for the entire button/link JSX. This would give the caller entire flexibility of what to render, and the `SetupPublicationScreen` would only need to worry about rendering whatever is passed there in the correct place. I think that would make the API a bit simpler. Also some of the button/link prop names are a bit confusing or unclear to me, so having a single prop for the entire piece may work better.

**Comment by hussain-t** [comment]
Thanks for the clarifications, @felixarntz 👍 I have updated the IB.

**Comment by felixarntz** [comment]
@hussain-t IB ✅ 

One small follow-up, not a blocker for the IB though: Does the button really need an `aria-label`? Isn't the button label itself enough since it is also a text? cc @tofumatt for additional input in regards to a11y

**Comment by hussain-t** [comment]
You are right, @felixarntz. We can omit the `aria-label` attribute if the button has a label. As per the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label), we could use `aria-labelledby` if the button has visible text.

>aria-label can be used in cases where text that could label the element is not visible. If there is visible text that labels an element, use [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) instead.

>The purpose of aria-label is the same as aria-labelledby. Both provide an accessible name for an element. If there is no visible name for the element you can reference, use aria-label to provide the user with a recognizable accessible name. If the label text is available in the DOM, and referencing the DOM content and acceptable user experience, prefer to use aria-labelledby. Don't include both. If both are present on the same element, aria-labelledby will take precedence over aria-label.

However, I would like to your @tofumatt's thoughts on this before modifying the IB. Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `SetupPublicationScreen` matches the figma design:
  - title - `Congratulations!`
  - description - `Your account is now active. To get started, customize the appearance of Thank with Google on your site.`
  - The button has copy `Customize Thank with Google` This isn't mentioned in the AC/IB, but it matches figma. 
  - The button has an ariaLabel - "Customize Thank with Google"
  - The title and description strings are h3 and p tags respectively.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/180441938-c95de7c2-be47-4515-9c5e-c6a29c1027bb.png)
![image](https://user-images.githubusercontent.com/73545194/180441961-ed7cacd8-f339-4fee-977e-12b873661ee9.png)
![image](https://user-images.githubusercontent.com/73545194/180441985-54093591-0a64-462b-903a-c6f99eed6f1e.png)
![image](https://user-images.githubusercontent.com/73545194/180442016-a6625f46-644c-4065-a5e6-ad8517a423a3.png)

</details>

**Note:** There are a few points to make here for reference.  1) the button does not point to a URL right now. When clicked the same screen loads with a TODO message. 2)  I have noted a few UI issues to the figma designs [in this ticket ](https://github.com/google/site-kit-wp/issues/5528) so won't duplicate those here.  If changes are made then they will made across the 3 TwG splash screens.
