### ISSUE TITLE
Implement TwG setup UI for publication action required scenario

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5526]
Follow-up to #5455: The actual UI for the `SetupPublicationActionRequired` component should be implemented based on the Figma design.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupPublicationActionRequired` component should have its proper UI implemented, from [this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A6360), reusing the applicable components introduced in #5525.
* The button should technically be a simple link, for now pointing to `https://publishercenter.google.com/` (opening in a new tab).

## Implementation Brief

In `assets/js/modules/thank-with-google/components/setup/SetupPublicationActionRequired.js`. This component is being implemented in #5455:
- Render the `SetupPublicationScreen` component (which is being implemented in #5525) with the following props:
  * `title` - "Complete your account setup"
  * `description` - "Finish the setup to customize and add Thank with Google on your site."
  * Render the `Button` component as children, with the translated copy "Complete your account setup". It should have the following props:
    * `href` - `https://publishercenter.google.com/`
    * `target` - "_blank"
    * `ariaLabel` - "Complete your Thank with Google account setup".
  * If a class was created for the `Button` component to match the Figma designs in #5525, add it to the `Button` component.

### Test Coverage

- Verify the `SetupMain` component story for this scenario works as expected.

## QA Brief

- Ensure the Thank with Google publication action required scenario matches the Figma design.
- For CR, [this story](https://google.github.io/site-kit-wp/storybook/pull/5592/?path=/story/modules-thank-with-google-setup-setupmain--publication-action-required) can be used for verification.
- For QA, [this story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup-setupmain--publication-action-required) can be used for verification.

## Changelog entry

* Implement the Thank with Google setup UI.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t  I have one observation that I'd like to share.

1. The IB reads `Render the Button component as children, with the translated copy "Complete your account setup"` but the text I see on the button is `Complete setup` To be fair, this does match figma, but wanted to check. Could you confirm what the correct text should be for the button? 

**Verified:**

- The `SetupCreatePublication` matches the figma design for action required.
  - title - `Complete your account setup`
  - description - `Finish the setup to customize and add Thank with Google on your site.`
  - The button URL is `https://publishercenter.google.com/` and opens in a new window. 
  - The button ariaLabel - `Complete your Thank with Google account setup`.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/180446372-00f4dc01-0aff-4325-b626-3e6f92a7312d.png)
![image](https://user-images.githubusercontent.com/73545194/180446400-4e876771-9565-436c-b034-34d791e50f02.png)

</details>

**Comment by hussain-t** [comment]
@wpdarren, I was the one who wrote the IB. It could be incorrect. The text should match the Figma design as it was implemented. Thanks for checking.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `SetupCreatePublication` matches the figma design for action required.
  - title - `Complete your account setup`
  - description - `Finish the setup to customize and add Thank with Google on your site.`
  - The button URL is `https://publishercenter.google.com/` and opens in a new window. 
  - The button ariaLabel - `Complete your Thank with Google account setup`.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/180446372-00f4dc01-0aff-4325-b626-3e6f92a7312d.png)
![image](https://user-images.githubusercontent.com/73545194/180446400-4e876771-9565-436c-b034-34d791e50f02.png)

</details>
