### ISSUE TITLE
Implement TwG setup UI for customization

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5529]
Follow-up to #5455: The actual UI for the `SetupCustomize` component should be implemented based on the Figma design.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupCustomize` component should have its proper UI implemented, from [this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=1205%3A4865), using the `ImageRadio` component from #5459 for its controls for "Type", "Prominence", and "Color".
* There is one part of the UI that needs to display conditionally: If the "Type" is set to "Overlay", the "Prominence" UI below should be displayed. Otherwise ("Type" set to "Fixed"), the other UI about auto vs manual placement from [this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=1205%3A5852) should be displayed below.
* Changing any of the controls should update the corresponding TwG settings on the client-side. Only clicking the primary submit button should send the API request to actually set the settings on the server-side. The controls map to the different TwG settings as follows:
    * "Type" and the control below (whichever of the alternate two) affect the `buttonPlacement` setting:
        * "Type" set to "Overlay" and "Prominence" set to "Low" --> `dynamic_low`
        * "Type" set to "Overlay" and "Prominence" set to "High" --> `dynamic_high`
        * "Type" set to "Fixed" and below placement set to "Auto" --> `static_auto`
        * "Type" set to "Fixed" and below placement set to "Manual > Above the post" --> `static_above-content`
        * "Type" set to "Fixed" and below placement set to "Manual > Below the post" --> `static_below-content`
        * "Type" set to "Fixed" and below placement set to "Manual > Below the 1st paragraph" --> `static_below-first-paragraph`
    * "Color" maps to the `colorTheme` setting and should set the selected color's identifier (not the human-readable label).
    * "Post types" maps to the `buttonPostTypes` setting and should set the array of post type identifiers/slugs (not the human-readable labels).
* Since the TwG `SettingsEdit` UI will basically display the same content (see #5531, also [here in Figma]()), reusable "common" components for the TwG settings controls should be implemented as much as possible so that they can be reused for the UI in #5531.

## Implementation Brief

* In `assets/js/modules/thank-with-google/components/common`, create the following functional React components:
    - `TypeRadio`,
    - `ProminenceRadio`,
    - `PositionRadio`,
    - `ColorRadio` and 
    - `PostTypesSelect`.
* Each of the above components should:
    - Have a `<h4>` for the title of the setting (Type, Prominence, Position, Color, Post Types).
    - Have a `<p>` in the `ColorRadio` and `PostTypesSelect` components for the description of the setting.
    - Use the new `<ImageRadio>` component for the radio options for Type, Prominence, and Color.
        - For `TypeRadio`, do not pass the `image` prop. Only pass label and description.
        - For `Prominence` and `Color`, pass an SVG image exported from the Figma mock in the AC.
        - Pass the `label` prop for all the radio options.
    - Use the `<Radio>` component for the radio options in `PositionRadio`.
    - For `<PostTypeSelect>`, build a new `<MultipleSelect>` component with MDC Chips as selectable options as per this [figma mock](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=1642%3A7082). Fetch the `postTypes` array using `select('core').getPostTypes()` as defined in #5456 (checking compatibility with versions < WP 5).
    - Refer to the ACs for the appropriate setting and its corresponding value name to be used for each setting.
* In `assets/js/modules/thank-with-google/components/common`, create another `<ButtonPlacement>` component that wraps `<TypeRadio>`, `<ProminenceRadio>` and `<PositionRadio>`. Use local state to conditionally render one of `<ProminenceRadio>` or `<PositionRadio>`, depending on the selection within `<TypeRadio>` mentioned in the AC. 
* Within each of the above 'settings' components, viz.`<ButtonPlacement>`, `ColorRadio` and `PostTypesSelect`:
    - Select the current value of the corresponding setting using the `getButtonPlacement`, `getgetColorTheme` and `getButtonPostTypes` selectors respectively from the `MODULES_THANK_WITH_GOOGLE` datastore. 
    - Use the selected value to render the appropriate radio/select option. 
    - Create an `onChange` handler function which sets the new selected value when the radio/select option is changed. Dispatch the `set<settingName>` action from the `MODULES_THANK_WITH_GOOGLE` datastore to update the setting value in the datastore. Use the setting values from the ACs. Refer to existing settings/setup common components such as in `modules/analytics/components/common` - PropertySelect, AccountSelect, etc. for additional detail.
* Within the new `<SetupCustomize>` component scaffolded in #5455:
    - Add the `<ButtonPlacement>`, `<ColorRadio>` and `<PostTypesSelect>` components created above to match the Figma mocks. Ensure the submit button logic already scaffolded creates the request to successfully store updated settings / option values in the datastore.
* Create `SetupCustomize.stories.js` rendering the `<SetupCustomize>` component in StoryBook v6.  

### Test Coverage

* No new tests required.

## QA Brief

* Verify that storybook for common components, the settings form and the setup customize components look and work correctly according to AC.

## Changelog entry

* Add the Thank with Google Setup UI.

**Comment by tofumatt** [comment]
I think this looks good, just one question: do you think this is the right place to add Storybook stories for these two states (eg. one for each of the `TypeRadio` values)?

Otherwise looks good to go. I don't think we've explicitly talked about adding those stories yet, so let's do that here 🙂

**Comment by jimmymadon** [comment]
@tofumatt So I have already asked for a Story for the whole parent `SetupCustomize` component. Changing the `TypeRadio` within should switch between showing the `ProminenceRadio` or `PositionRadio`. Would that not be enough? Is it good practise to have a separate story for each individual state?

**Comment by tofumatt** [comment]
@jimmymadon Oh, shoot, I just missed that at the end.

No, it's totally fine (and efficient) to combine them. All good! 👍🏻 

IB ✅

**Comment by jimmymadon** [comment]
@tofumatt I've updated this IB to include the `<MultiSelect>` component and bumped up the estimate. This component will be reused in #5531 so not much to change there.

**Comment by tofumatt** [comment]
IB ✅ 

It's not in the IB explicitly but adding some tests and/or storybook stories, time-permitting, for the Multiple Select here would be good.

**Comment by eugene-manuilov** [comment]
@felixarntz, there is a radio box for the `Manual` option on the figma design. What should happen when a user clicks on it? Which option should be selected?

![www figma com_file_t5zDpQ28Lo7ZyRcOpGdqgu_TwG_node-id=1205%3A7472](https://user-images.githubusercontent.com/873049/180841245-8da610dd-9ce7-4305-8290-345d0e5c179e.png)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov Just two observations to share. 

1. When a `Fixed` type is selected, and then `Auto` position, in the settings it appears under `Prominence`  Maybe we could  change the title to `Prominence/Position` to avoid any confusion? 

![image](https://user-images.githubusercontent.com/73545194/182394594-eb7ba0a1-1382-4177-b3da-f3b79bbc66f4.png)

2. When I select `Media` in the list of post types, the source code shows it as `attachment` for `buttonPostTypes` vIs this correct? 

**Verified:**

- Checked the figma designs to my test site. 
- Made sure that all of the fields displayed correctly in Site Kit settings screen. 
- Checked that changing any of the controls updates the corresponding TwG settings on the client-side. 
- Looked at the source code and checked the controls map to the different TwG settings as per the AC. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/182398359-dc9e96a1-a04a-49c3-b054-8760dd92b313.png)
![image](https://user-images.githubusercontent.com/73545194/182398390-60999848-4ced-47af-a1eb-cc29534b5f19.png)
![image](https://user-images.githubusercontent.com/73545194/182398413-5c3698e7-f625-4c4a-a280-a8ab7d091e94.png)

</details>

**Comment by eugene-manuilov** [comment]
> 1. When a `Fixed` type is selected, and then `Auto` position, in the settings it appears under `Prominence`  Maybe we could  change the title to `Prominence/Position` to avoid any confusion?

@wpdarren this is out of scope for this ticket. I think it would be better to ask Jimmy to update it in the #5456 ticket since that ticket is responsible for the settings view portion.

> 2\. When I select `Media` in the list of post types, the source code shows it as `attachment` for `buttonPostTypes` Is this correct?

Yes, that's correct. `Media` is just a label for the attachment post type.

**Comment by jimmymadon** [comment]
> 1. When a `Fixed` type is selected, and then `Auto` position, in the settings it appears under `Prominence`  Maybe we could  change the title to `Prominence/Position` to avoid any confusion? 

@wpdarren I can make this tiny change easily on the TwG Settings View page. Do we need any approval from UX or anyone on this?

**Comment by wpdarren** [comment]
@jimmymadon @eugene-manuilov thanks for the comments here.  I've had a chat on Slack and we are going to create a ticket for the title but also for the language used.  So, for now lets leave it as it is.  I'll get on with approving this ticket.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked the figma designs to my test site. 
- Made sure that all of the fields displayed correctly in Site Kit settings screen. 
- Checked that changing any of the controls updates the corresponding TwG settings on the client-side. 
- Looked at the source code and checked the controls map to the different TwG settings as per the AC. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/182398359-dc9e96a1-a04a-49c3-b054-8760dd92b313.png)
![image](https://user-images.githubusercontent.com/73545194/182398390-60999848-4ced-47af-a1eb-cc29534b5f19.png)
![image](https://user-images.githubusercontent.com/73545194/182398413-5c3698e7-f625-4c4a-a280-a8ab7d091e94.png)

</details>
