### ISSUE TITLE
No images on Google Site Kit Dashboard, Search console or Analytics Dashboards.

### ISSUE THREAD

**Issue by amentaj** [google/site-kit-wp#553]
## Bug Description

When I go to look at my Google Site Kit Dashboard, Search Console or Analytics dashboards there is no image.  The main WordPress dashboard shows the information, but the specific dashboard does not.

## Steps to reproduce

1. Go to WordPress Admin Editor
2. Click on G Site Kit - Dashboard
3. See error (blank screen)

## Screenshots
![image](https://user-images.githubusercontent.com/33556008/65088991-6e8d1f00-d989-11e9-9650-5343765fc091.png)

## Additional Context

 - PHP Version: 7.0
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome and Edge
 - Plugin Version [e.g. 22] Beta

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@amentaj Can you please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard? If you can also try installation from another computer to rule device to rule out the issue being with any particular software on your machine (VPN, security suite or other)

**Comment by amentaj** [comment]
`Health Info:
### wp-core ###

version: 5.2.3
site_language: en
user_language: en
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/jamenta/public_html
wordpress_size: 45.56 MB (47773020 bytes)
uploads_path: /home/jamenta/public_html/wp-content/uploads
uploads_size: 89.72 MB (94078101 bytes)
themes_path: /home/jamenta/public_html/wp-content/themes
themes_size: 26.08 MB (27345558 bytes)
plugins_path: /home/jamenta/public_html/wp-content/plugins
plugins_size: 125.12 MB (131193669 bytes)
database_size: 14.57 MB (15281289 bytes)
total_size: 301.05 MB (315671637 bytes)

### wp-active-theme ###

name: Twenty Sixteen
version: 2.0
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, custom-logo, post-thumbnails, menus, html5, post-formats, editor-style, editor-styles, wp-block-styles, responsive-embeds, editor-color-palette, customize-selective-refresh-widgets, custom-background, custom-header, jetpack-responsive-videos, jetpack-geo-location, infinite-scroll, widgets
theme_path: /home/jamenta/public_html/wp-content/themes/twentysixteen

### wp-themes (9) ###

Business Inn: version: 1.1.1, author: ProDesigns
Lyrical: version: 1.1.3, author: GoDaddy
Medical Circle: version: 2.0.0, author: acmethemes
One Page Express: version: 1.2.10, author: Horea Radu
Primer: version: 1.8.7, author: GoDaddy
Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
WP iClean Responsive: version: 1.2.4, author: WP Online Support
Zincy Lite: version: 1.1.34, author: 8Degree Themes

### wp-mu-plugins (1) ###

installatron_hide_status_test.php: author: (undefined), version: (undefined)

### wp-plugins-active (20) ###

Accelerated Mobile Pages: version: 0.9.98.9, author: Ahmed Kaludi, Mohammed Kaludi
Akismet Anti-Spam: version: 4.1.2, author: Automattic
Black Studio TinyMCE Widget: version: 2.6.9, author: Black Studio
Booking Ultra Pro Complement: version: 1.0.40, author: Booking Ultra Pro
Booking Ultra Pro CORE: version: 1.0.78, author: Booking Ultra Pro
Booking Ultra Pro Professional & Ultimate: version: 1.0.0, author: Booking Ultra Pro
Classic Editor: version: 1.5, author: WordPress Contributors
Contact Form 7: version: 5.1.4, author: Takayuki Miyoshi
Custom CSS and Javascript: version: 2.0.9, author: Potent Plugins
GA Google Analytics: version: 20190902, author: Jeff Starr
GD LinkedIn Badge: version: 2.5, author: Milan Petrovic
Google XML Sitemaps: version: 4.1.0, author: Arne Brachhold
Jetpack by WordPress.com: version: 7.7.1, author: Automattic
NextGEN Gallery: version: 3.2.15, author: Imagely
PHP Compatibility Checker: version: 1.5.0, author: WP Engine
Simple Links: version: 4.6.5, author: OnPoint Plugins
Site Kit by Google: version: 1.0.0-beta.1.0.6, author: Google
Social Media and Share Icons (Ultimate Social Media): version: 2.4.0, author: UltimatelySocial
Wordfence Security: version: 7.4.0, author: Wordfence
YouTube: version: 13.1.1, author: EmbedPlus Team

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1684
imagemagick_version: ImageMagick 6.9.4-10 Q16 x86_64 2017-11-14 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 62 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 62 GB
	imagick::RESOURCETYPE_MEMORY: 31 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.66.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.0.33 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 32M
php_post_max_size: 32M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.44-cll-lve
client_version: 5.6.42

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/jamenta/public_html/wp-content
WP_PLUGIN_DIR: /home/jamenta/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 120207820
ssl_cert: No
time_diff: undefined
version_option: 7.7.1:1567797838
old_version: 7.7:1567538286
public: Public
master_user: #1 jamenta (james.amenta@gmail.com)
current_user: #1 jamenta (james.amenta@gmail.com)
tokens_set: Blog User
blog_token: g!pan)@&ngV!ph#7UwBnw3@r!GPXBLHY
user_token: *VDQBB7HfzB@umudPS0KOZ(QY^w5p(yX
version: 7.7.1
jp_plugin_dir: /home/jamenta/public_html/wp-content/plugins/jetpack/
plan: free
HTTP_HOST: www.yourpersonalslp.com
SERVER_PORT: 443
HTTPS: on
REMOTE_ADDR: 165.225.38.119
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Wed, 05 Sep 2018 19:37:43 +0000","queue_finished":"Wed, 05 Sep 2018 19:37:43 +0000","send_started":"Wed, 05 Sep 2018 19:37:44 +0000","finished":"Wed, 05 Sep 2018 19:37:44 +0000","sent":{"constants":1,"functions":1,"options":1,"users":1},"sent_total":[],"queue":{"constants":1,"functions":1,"options":1,"users":1},"config":{"options":true,"functions":true,"constants":true,"users":[1]},"total":{"constants":1,"functions":1,"options":1,"users":1}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/www.yourpersonalslp.com","siteurl":"https:\/\/www.yourpersonalslp.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

`

**Comment by adamsilverstein** [comment]
@amentaj Hi, thanks for sharing the site info, I am looking into this issue.

Can you also please share any [console errors ](https://imgur.com/KyLAzgH) you see?

**Comment by amentaj** [comment]
![image](https://user-images.githubusercontent.com/33556008/65171578-2ddce680-da19-11e9-8cd9-991e2c93fcaa.png)

**Comment by adamsilverstein** [comment]
@amentaj Thanks for the update. So far I have been unable to reproduce. Those errors don't appear to come from Site Kit. Is that on the Site Kit Dashboard page? 

It looks like you had previously configured and used Site Kit, this error occurred when you upgraded to the latest version, is that right?

I'm testing in chrome beta on a mac so far - you are on windows 10/chrome, right?

Can you try these steps and let me know if they resolve the issue:

* Try a "Clear Cache and Hard Reload" - in chrome this shows when you right click the refresh button when the debugger console is open:

![image](https://user-images.githubusercontent.com/2676022/65172647-9a9cb480-da0a-11e9-850c-e8d805e195a5.png)

* Try disabling other plugins temporarily to see the issue is resolved.

**Comment by amentaj** [comment]
Thank you @adamsilverstein, it was one of my other plugins.  I'll need to get with the developer of that plugin to see what they can do but now at least I know what the problem is.

**Comment by adamsilverstein** [comment]
Thanks for confirming @amentaj - Can you tell us what plugin (and version) was conflicting so we can be aware of the issue?  Was the plugin new? its odd that Site Kit worked previously and failed when you upgraded.

If you want to message me this information privately to me I'm on twitter `@roundearth`. Thanks again.

**Comment by amentaj** [comment]
Sure, the plugin is Booking Ultra Pro CORE v1.0.78.
