### ISSUE TITLE
Use “cta” prefix for TwG settings instead of “button” prefix

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5533]
During the design doc reviews for Thank with Google, it was decided to name the TwG settings `ctaPlacement` and `ctaPostTypes` rather than the more generic `buttonPlacement` and `buttonPostTypes`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG setting `buttonPlacement` should be renamed to `ctaPlacement` throughout the entire codebase.
* The TwG setting `buttonPostTypes` should be renamed to `ctaPostTypes` throughout the entire codebase.
* This also affects the JS selectors which will need to be adjusted including all its usage:
    * Because of our convention of using capitalized acronyms, the selectors/actions should be `getCTAPlacement`, `setCTAPlacement`, `getCTAPostTypes`, `setCTAPostTypes` respectively, so in the datastore definition for these settings they will need to be manually tweaked to avoid them having "Cta" instead of "CTA". There is already code that does this for the Optimize module's `ampExperimentJSON` setting that can probably be used here as well.
    * All usages of the old named selectors and actions for these settings needs to be updated accordingly of course.

## Implementation Brief

Rename the `buttonPlacement` setting with the `ctaPlacement` setting and `buttonPostTypes` with the `ctaPostTypes` in the following files:
- `includes/Modules/Thank_With_Google.php`
- `includes/Modules/Thank_With_Google/Settings.php`
- `tests/phpunit/integration/Modules/Thank_With_GoogleTest.php`
- `assets/js/modules/thank-with-google/components/setup/SetupForm.test.js`
- `assets/js/modules/thank-with-google/datastore/base.js`
- `assets/js/modules/thank-with-google/datastore/settings.test.js`

In `assets/js/modules/thank-with-google/util/validation.js`:
- Rename the `isValidButtonPlacement` function to `isValidCTAPlacement`.
- Rename the `buttonPlacement` parameter to `ctaPlacement`.
- Rename the `isValidButtonPostTypes` function to `isValidCTAPostTypes`.
- Rename the `buttonPostTypes` parameter to `ctaPostTypes`.

In `assets/js/modules/thank-with-google/datastore/settings.js`:
- Rename the `getButtonPlacement` selector to `getCTAPlacement`.
- Rename and `getButtonPostTypes` to `getCTAPostTypes`.

In `assets/js/modules/thank-with-google/datastore/settings.test.js`:
- Rename the `setButtonPlacement` selector to `setCTAPlacement`.

In `assets/js/modules/thank-with-google/datastore/base.js`:
- Rename the following generated selectors and actions to capitalize `Cta` to `CTA`.
  * `getCtaPlacement` selector to `getCTAPlacement`
  * `getCtaPostTypes` selector to `getCTAPostTypes`
  * `setCtaPlacement` action to `setCTAPlacement`
  * `setCtaPostTypes` action to `setCTAPostTypes`
  * The same as we do for Optimize module's `ampExperimentJSON` setting. See:
https://github.com/google/site-kit-wp/blob/5dc7365154f6e5001ad9a4c9f80242486c3bda06/assets/js/modules/optimize/datastore/base.js#L38-L58

### Test Coverage

- Update any failing tests.

## QA Brief

* Verify that the Thank with Google settings view and edit form work correctly. This can be checked in Storybook for now.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Looks good to me! IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t @eugene-manuilov 

When I look at the source code when TwG is set up and has settings saved, I see the new prefix `ctaPlacement `and `ctaPostTypes` but I can see references to `buttonPlacement` and `buttonPostTypes`.  Is that expected?

![image](https://user-images.githubusercontent.com/73545194/182610556-e97c2f9c-352a-490d-bd63-aadf7222157e.png)
![image](https://user-images.githubusercontent.com/73545194/182610581-65b25e87-5c87-41b5-95b0-832d5143e152.png)

**Comment by eugene-manuilov** [comment]
> When I look at the source code when TwG is set up and has settings saved, I see the new prefix `ctaPlacement `and `ctaPostTypes` but I can see references to `buttonPlacement` and `buttonPostTypes`. Is that expected?

@wpdarren that is probably your previous settings, so this is expected. You can check it on a brand new site, you shouldn't see them there.

> I am also wondering if this should be labelled QA:Eng after due to these entries in the AC, or is that picked up at CR?

Yes, let's add the `QA:Eng` label. 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@eugene-manuilov you're correct, didn't use a fresh site 🤦  

**Verified:**

- The TwG setting buttonPlacement is renamed to ctaPlacement when looking at the TwG settings in source code.
- The TwG setting buttonPostTypes is renamed to ctaPostTypes when looking at the TwG settings in source code.
- Tested to make sure that the settings functionality works for TwG on my fresh test site. 
- Checked Storybook to make sure that the Thank with Google settings view and edit form work correctly. 

![image](https://user-images.githubusercontent.com/73545194/182626526-73fad22d-5f84-4a58-8e0e-96f6f441815c.png)
![image](https://user-images.githubusercontent.com/73545194/182626565-65f58e4c-4b84-43f9-a748-b41c60186990.png)

Left this in QA for an engineer to check the JS entries in the AC.

**Comment by kuasha420** [comment]
### QA:Eng :heavy_check_mark: 

* All the JS selectors has been correctly renamed to follow our convention. 
* All the variables and functions has been renamed to the new cta prefix, both in SCSS, JS and PHP. 
* All the comments and js/phpdocs are also accurate and correctly replaces button with cta. 

LGTM.
