### ISSUE TITLE
Complete TwG success banner notification UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5536]
The TwG success banner uses some slightly custom UI from the default module setup success banner, which should be implemented here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The regular module `SetupSuccessBannerNotification` should be updated to have special copy ints for the `thank-with-google` module: Under the banner title (above the "Ok, got it"), it should have the following:
    * Copy: _Thank with Google is visible to your visitors. To see metrics, open the administrator panel._
    * The "open the administrator panel" should be a link to `https://publishercenter.google.com/` for now (opening in a new tab).

## Implementation Brief

In `assets/js/components/notifications/SetupSuccessBannerNotification.js`:
- Have a condition that checks the `slug` is equal to `thank-with-google`.
- If it is `true`, then:
  * Update the `winData.description` to have the `Thank with Google is visible to your visitors. To see metrics,` copy.
  * Update the `winData.learnMore` to have the following:
    * `label`: `open the administrator panel.`
    * `url`: `https://publishercenter.google.com/`
    * `target`: `LEARN_MORE_TARGET.EXTERNAL`

### Test Coverage

In `assets/js/components/notifications/SetupSuccessBannerNotification.stories.js`, add a story for the Thank with Google module that covers the above scenario.

## QA Brief

* Visit the story over at `?path=/story/components-setupsuccessbannernotification--thank-with-google`
* Ensure that the copy is correct
* Ensure that the `open the administrator panel`-link opens the URL given in AC in a new tab

## Changelog entry

* Include specific copy for Thank with Google on the setup success banner.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@makiost the title of the notification is `Congrats on completing the setup for Thank With Google!` but the rest of the references to the feature are `Thank with Google` 

For consistency, please could we make this small change, so that `with` is all in lowercase?  Thank you! 

![image](https://user-images.githubusercontent.com/73545194/179218769-2b0c2f9e-5ae9-49ed-96b7-8bc64acab905.png)

**Comment by wpdarren** [comment]
@makiost while working on the test plan for TwG, I noticed that the figma designs is not referenced in this ticket, but the success banner does look different than what I see in Storybook. 

This is in figma
![image](https://user-images.githubusercontent.com/73545194/180007439-b1faa4fc-4092-4b13-ba1b-faf85e10b90b.png)

The difference is the graphic to the right.  

Are you aware if the Figma design is incorrect, and we are going with how the other success banner graphic looks now?
