### ISSUE TITLE
Finalize TwG links to Publisher Center

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5537]
The TwG implementation for now uses a few links to `https://publishercenter.google.com/`, which eventually need to be replaced with their appropriate links based on the TwG creator admin UI that is still being worked on on the Google service side.

This issue is blocked until those URLs are clearly defined.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The base URL for creating a new TwG publication (see `getServiceCreatePublicationURL` selector) should be changed from `https://publishercenter.google.com/` to `https://publishercenter.google.com/twg/onboarding`.
    * The rest should remain as is, e.g. the `sk_url` query parameter.
* Everywhere we link to `https://publishercenter.google.com/publications/{publicationID}/overview` (see `getServicePublicationURL` selector), we should change that URL to be `https://publishercenter.google.com/twg/{publicationID}/home` instead.
    * In addition, that URL should also be wrapped in the `getAccountChooserURL` selector so that it is Google account aware.

## Implementation Brief

- In `assets/js/modules/thank-with-google/datastore/constants.js`:
    - Change the value of the `PUBLISHER_CENTER_URL` constant to `https://publishercenter.google.com/twg`.
- In `assets/js/modules/thank-with-google/datastore/publications.js`:
	- Update the `getServiceCreatePublicationURL` selector:
        - Inside the `url` variable, update the first parameter of the `addQueryArgs` function so that `/onboarding` should be appended to the existing value. It should look something like this:
        ```js
        const url = addQueryArgs( `${ PUBLISHER_CENTER_URL }/onboarding`, {
            sk_url: select( CORE_SITE ).getHomeURL(),
        } );
        ```
	- Update the `getServicePublicationURL` selector:
	    - Create a new variable named `url` with the following value: `${ PUBLISHER_CENTER_URL }/${ encodeURIComponent( publicationID ) }/home`.
		- Pass this `url` variable to the `getAccountChooserURL` selector from the `core/user` store and return the result.

### Test Coverage

* In `assets/js/modules/thank-with-google/datastore/publications.test.js`:
    * Update both test cases for `getServiceCreatePublicationURL` and `getServicePublicationURL` to reflect the above changes.

## QA Brief

- To verify the `getServiceCreatePublicationURL` selector returns the correct URL:
  * Go to the TwG create publication setup screen or the [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup--create-publication) and verify the `Create account` button URL is expected as per the AC.
- To verify the `getServicePublicationURL` selector returns the correct URL:
  * Go to the TwG publication action required setup screen or the [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup--publication-action-required) and verify the `Complete setup` button URL is expected as per the AC.
  * Go to the TwG publication pending verification setup screen or the [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup--publication-pending-verification) and verify the `Check your status` button URL is expected as per the AC.
  * Complete the TwG publication setup or the [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-setupsuccessbannernotification--thank-with-google) and verify the `open the administrator panel` link in the setup success banner notification is expected as per the AC.

## Changelog entry

* Finalize Thank with Google links to the Publisher Center.

**Comment by felixarntz** [comment]
@eclarke1 I added a new label `blocked upstream` for any issues which are blocked by external factors, and added it to this issue and #5753 for now. We can continue using that label for any similar situations in the future.

**Comment by eclarke1** [comment]
@felixarntz @aaemnnosttv based on the email from Juan, can you confirm if this can now be unblocked and added to Sprint 84?
cc @FlicHollis

**Comment by felixarntz** [comment]
Thanks for the ping @eclarke1, indeed! I've added ACs.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t while the links appear to be pointing to the correct URL based on the AC, I did notice that when  I click on the CTA, I am redirected to `https://publishercenter.google.com/u/1/` which is a blank screen.  Is this expected? 

**Verified:**

- The `Create Account` CTA button points to 
`https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2Fonboarding%3Fsk_url` 

- The `Complete Set Up` CTA button points to 
`https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAowqu68Cw%2Fhome&Email` and when reading the AC, looks to be correct.  

- The `Check your Status` CTA button points to `https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAowqu68Cw%2Fhome&Email=` and when reading the AC, looks to be correct.

- The `Customize Thank with Google` CTA points to Site Kit. When TwG is customized I am redirected to the Site Kit dashboard with where a notification appears.
- There's an `open the administrator panel` link on the notification.  This points to  `https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAowqu68Cw%2Fhome&Email=` and when reading the AC, looks to be correct.

**Comment by wpdarren** [comment]
@felixarntz chatting to Hussain re my observation above with the URL and blank screen.  We noticed that when you refreshed the page, the publisher centre did load.  I am unsure why there's a redirect and the initial blank page though. From the Site Kit side, the URLs look correct based on the AC.

**Comment by felixarntz** [comment]
@wpdarren The TwG team is still working on those URLs and they are aware of ongoing problems at the moment. I don't see the same problems that you do (maybe related due to US vs non-US location), but I also get e.g. a 404 when I go to any of the publication URLs.

It's probably not worth focusing too much on this right now, until the TwG team gives us the green light that they've completed their work. If any of those issues still persist then, we need to raise them.

In any case, this issue shouldn't be blocked by it as it's correct on our end, and those problems are external.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@felixarntz thank you for the clarification!  

**Verified:**

- The `Create Account` CTA button points to 
`https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2Fonboarding%3Fsk_url` 

- The `Complete Set Up` CTA button points to 
`https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAowqu68Cw%2Fhome&Email` and when reading the AC, looks to be correct.  

- The `Check your Status` CTA button points to `https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAowqu68Cw%2Fhome&Email=` and when reading the AC, looks to be correct.

- The `Customize Thank with Google` CTA points to Site Kit. When TwG is customized I am redirected to the Site Kit dashboard with where a notification appears.
- There's an `open the administrator panel` link on the notification.  This points to  `https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAowqu68Cw%2Fhome&Email=` and when reading the AC, looks to be correct.

Note: The URLs are as expected but currently, they redirect to `https://publishercenter.google.com/u/1/` (even on US VPN) so as per Felix's comment above, we aren't blocking this issue because of that. When we do our final E2E on the plugin-side in October, we can make sure that the links function as they should.
