### ISSUE TITLE
Prettier upgrade introducing unexpected changes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5539]
## Bug Description

[`wp-prettier` introduced the first non-beta release](https://www.npmjs.com/package/wp-prettier) in the past few years last month and since then it has been automatically installed in some cases (e.g. dependabot PRs) due to it's loose version constraint.

The latest version (2.6.2) sees our current codebase as invalid and breaks the linting job, citing many lines. E.g. https://github.com/google/site-kit-wp/runs/7256800657?check_suite_focus=true

We should lock the version we're currently using and follow up with a dedicated issue to upgrade it to coordinate the major diff it will require.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* npm should only install version `2.2.1-beta-1` for `wp-prettier`
* Running `lint:js` on develop should flag no prettier violations

## Implementation Brief

* Merge #5540 

### Test Coverage

* No change

## QA Brief

* Not much to check here
* Try installing from a clean install
* Try running `lint:js` to ensure nothing is flagged

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️
