### ISSUE TITLE
Analytics permissions notice appears for non admins, within the Search Traffic widget 

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5551]
## Bug Description

Asana bug bash issue: https://app.asana.com/0/1202258919887896/1202591289744465 please see Asana task for background and additional comments.

If an administrator has set up Site Kit, and connects the plugin to an Analytics property that only they have access to, a non administrator may encounter the below:

_**Data error in Analytics**
Site Kit can’t access the relevant data from Analytics because you haven’t granted all permissions requested during setup._

The above message (also attached, see screenshot) shouldn't display for non administrators. 

Interestingly, for secondary administrators who login, the error message differs. 

_**Insufficient permissions in Analytics**
Your Google account does not have sufficient permissions to access Analytics data, so you won’t be able to see stats from it on the Site Kit dashboard. This service was originally connected by the administrator "jamesozzie" — you can contact them for more information._

There should be no error message output to non admins suggesting they didn't grant permissions. 

Full recording of experience can be [found here](https://recordit.co/Ow6TdAwU1D). 

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/5adbd4f8-2d46-4004-8023-beb3443fbdcf)

## Steps to reproduce

1. Setup SK, including GA, using a GA property that only the this admin account (adminA) has access to
2. Create a secondary administrator user (adminB) and an editor role
3. Login from a separate browser session as adminB and set up SK. Notice the typical and expected Analytics permissions errors
4. From back in the adminA session, grant sharing permissions (SC - all roles, Analytics - all roles except administrators)
5. Disconnect adminA
6. Revisit the session for adminB and refresh the page. Two module recovery notice will appear. Press the "Recover" button. 7. You'll then encounter the non-recoverable notice (Analytics).  
8. Notice the permissions error within the Analytics widget remains. 
9. Logout of the adminB (from the same browser session) and login from the editor role account. The error appears

## Screenshots

Steps from the below video:
- 2.20: Dashboard sharing applied from adminA (SC - all roles, GA - only editors)
- 3:19: Recoverable module notice appears when adminB is logged in
- 3.26: Non recoverable notice appears
- 3:29: The permission notice for Analytics appears (as expected) within adminB's "Search Traffic" widget
- 3:57: Logging out as adminB
- 4:02: Loggin in a editor
- 4:17: Once the view only dashboard appears, the error as described in this GH issue appears

https://user-images.githubusercontent.com/41326532/178720400-8fc48561-fd58-4357-8a77-40b0de905450.mp4

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This should be fixed by https://github.com/google/site-kit-wp/issues/5470, pending confirmation from @jamesozzie

**Comment by jamesozzie** [comment]
Confirming all good with 1.79.0, working as expected, with the issue no longer occurring. 

![image](https://user-images.githubusercontent.com/41326532/178797052-6808bad8-8118-4278-b04e-88664f530895.png)

**Comment by aaemnnosttv** [comment]
Thanks @jamesozzie!
