### ISSUE TITLE
Remove ellipsis from "Manage sites" option

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5552]
## Feature Description

I know this is super nitpicky, but: Can we remove the ellipsis from after "Manage sites" in the dropdown on the dashboard? They're not necessary.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/12189958/178725669-1ad043e2-a5c1-4016-ae19-304ca673bb95.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
I agree! [I've raised this on the design](https://www.figma.com/file/jV9HznsU4ZseiLKZ0CDb80?node-id=27:2056#330657083) that we'll be using in the upcoming updates to the user menu in #5775 – it's not worth a dedicated issue for this. Thanks!
