### ISSUE TITLE
Introduce custom GitHub Actions check for an assigned Release before merging

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5554]
## Feature Description

Until now, assigning a release to a PR's respective issue has always been a requirement for merge but one that was enforced manually. This issue is about introducing a new check via GitHub Actions to require that the release is assigned for PRs against develop or main.

This will not actually block a PR from being merged, but the failing check should be sufficient to prevent this from happening.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new GitHub Actions workflow should be created for Zenhub checks
	* It should only run for pull requests against `develop` or `main`
	* It should not run for PRs created by `dependabot` or forks
* When run, it should check that its [connected issue](https://help.zenhub.com/support/solutions/articles/43000615530-zenhub-issue-and-pr-connections) is assigned to a Zenhub Release
	* If no release is assigned, the check should fail (otherwise it should pass)
	* The check should use the Zenhub GraphQL API (see https://developers.zenhub.com/graphql-api-docs/getting-started)
		* A new secret `ZENHUB_GQL_API_TOKEN` should be used where needed
* The check should run when a PR is created or `synchronized`, but should also be possible to trigger with a manual action (such as a comment or checkbox tick)

### Create a `check-issue-has-release` node script in `bin`.
* Using the following GQL query, retrieve the connected issue's assigned release.
````gql
query($repositoryGhId: Int!, $issueNumber: Int!){
  issueByInfo(repositoryGhId: $repositoryGhId, issueNumber: $issueNumber) {
    connections {
      nodes {
        number
        releases {
          nodes {
            title
          }
        }
      }
    }
  }
}
````
* Here the `repositoryGhId` is `191387173` (site-kit-wp's GH ID) and `issueNumber` is the Pull request ID which can be obtained from `PULL_REQUEST_NUMBER` ENV variable. 
* The query requires a bearer authentication using the `Authorization` header which can be `ZENHUB_GQL_API_TOKEN` variable mentioned in the AC (should be created by a repo owner) and used. 
* The `POST` request should be made against `https://api.zenhub.com/public/graphql` endpoint
* The API will return a response in the following shape:
````JSON
{
  "data": {
    "issueByInfo": {
      "connections": {
        "nodes": [
          {
            "number": 6552,
            "releases": {
              "nodes": [
                {
                  "title": "1.98.0"
                }
              ]
            }
          }
        ]
      }
    }
  }
}
````
* Exit with a zero code (success)  if,  `data.issueByInfo.connections.nodes[0].releases.nodes[0].title` exists, meaning the connected issue has a release assigned.
* Otherwise, exit with a non zero code to indicate the check failed `process.exit(1)`. 

### Create `.github/workflows/check-issue-has-release.yml` workflow

* See our existing `storybook.yml` for a head start and make the following changes as needed. 
* Give it a descriptive title. ie. `The connected issue must have a ZenHub release assigned`.
* The action should run once a PR has been made against the `develop`, `main` and `'feature/**'` branches.
    * This should not run on `push`
    * This should not run on draft or forked PR. 
    * The check should only run for `opened`, `reopened`, `edited` and `synchronize`
    * No `paths` should be specified. 
* In the `jobs` section, 
    * Setup node using the `actions/setup-node@v3` action.
    * Set up the necessary environment variables needed for the previously created script.
        * `PULL_REQUEST_NUMBER` -> `github.event.number`
    * Use [should-run-github-action](https://github.com/bahmutov/should-run-github-action) to run the `check-issue-has-release` script when the `Ensure the corresponding issue has a ZenHub release assigned.` checkbox is checked in PR description. 

## Test Coverage

* N/A

## QA Brief

* Approve the PR if it looks good, then check to see if the check is run. Make sure you don't attach a release to this issue so it fails; afterward, attach the release and re-run the check. Then it should pass 🙂 

## Changelog entry

* N/A

**Comment by FlicHollis** [comment]
Hey @kuasha420 I notice this was assigned to you a while ago. Has this IB been started? If not, feel free to unassign yourself so that any of the team can pick it up. Thanks so much!

**Comment by FlicHollis** [comment]
Hi @kuasha420 just following up on my comment above If you are not actively working on this, perhaps you could  un-assign yourself for someone else to pick up. Let me know what you think, thanks!

**Comment by FlicHollis** [comment]
Hi @kuasha420 thanks so much for coming back to me, makes sense and one IB to look at in the next sprint then, thanks!

**Comment by bethanylang** [comment]
@kuasha420 Checking in here – can you please move forward or unassign if someone else should pick up? Thanks!

**Comment by techanvil** [comment]
Hey @kuasha420, nice work on the IB here, and good find for that ` should-run-github-action` action!

I've got a few fairly minor comments to make, please see what you think.

- The script name `check-release` is a little ambiguous, I'd suggest a more explicit name like `check-issue-has-release`.
- The same applies for `.github/workflows/check-release.yml`, which I'd suggest updating to match the new script name.
- The error conditions in the description for the script implementation seem like false positives could still occur (say the request fails, for example). How about we simplify it to say, it should exit without error if a release title is found in the response, otherwise no release is found and it should exit with an error (non-zero exit code)?
- The way the IB is phrased makes it sound as though we should copy the `on: types` list from `storybook.yml` and add `edited`, however we don't need to run this new action on `closed`. It's a small detail but it might be worth mentioning to be clear.
- The point "Setup node and env variables." is a bit vague, I'm wondering if either this should have a bit more information about the variables it's referring to, or otherwise could simply be left out as it's not really adding much information as it stands and could probably just be inferred.
- There's no `Exp: SP` label, does the estimate need to be bumped and the label applied?

**Comment by kuasha420** [comment]
@techanvil Thank you for your valuable feedback and pointing out the improvements. I think I've addressed every one of your feedback. Regarding `Exp: SP`, for some reason I thought the experiment was over. :sweat_smile: I have added the label and bumped up the estimate to `19`. Cheers.

**Comment by kuasha420** [comment]
Hi @techanvil!

The `storybook.yml` has the `ready_for_review` because that workflow gets skipped for draft PR. I don't think we need this here because we're not skipping this workflow for draft PR. 

Thank you.

**Comment by techanvil** [comment]
Hey @kuasha420, thanks for clarifying that. Somehow I failed to register that point in the IB and make the connection.

Well, that being the case, this looks good to go!

IB :white_check_mark:

**Comment by tofumatt** [comment]
Assigning this to @aaemnnosttv as it probably needs him to set the `ZENHUB_GQL_API_TOKEN` secret in the GitHub repo.

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt – I've started a conversation internally to get this added. Please leave it with me for now; there's no rush on this 👍

**Comment by swissspidy** [comment]
btw, if you need some inspiration for implementing this, I built this in the past: https://github.com/GoogleForCreators/web-stories-wp/blob/7863b2a18b8e6fb3e0b1621659c1acfb2350484d/.github/workflows/add-milestone.yml

**Comment by aaemnnosttv** [comment]
@tofumatt I've opened an alternative based on your branch for your consideration. Assigning back to you to review 👍

**Comment by tofumatt** [comment]
Moving directly to Approval since there's no QA to do here. 😄
