### ISSUE TITLE
Add the "learn more" link to the SetupUsingProxyWithSignIn component when the site has been configured by another admin.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5559]
## Feature Description

When the site has been configured by another admin, we display a message on the sign in page that tells users about it. We need to add the "learn more" link to that message.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The description message for the second admin case in the `SetupUsingProxyWithSignIn` component should be appended with the new "learn more" link that leads users to the `{proxy}/support/?doc=already-configured` page.

## Implementation Brief

- In `assets/js/components/setup/SetupUsingProxyWithSignIn.js`:
    - Compose the "Learn More" link URL:
        - Use the `getDocumentationLinkURL` selector with the slug `already-configured` from the `core/site` store and assign it in a variable named `secondAdminLearnMoreLink` (or something more relevant).
    - Create a new reassignable variable named `learnMore`.
    - After the `description` is displayed, check if `learnMore` is truthy and if so, display a `<Link />` component with an `href` prop pointing to the `learnMore` variable and an `external` prop with `true`. The content of the component should be `Learn More` (translatable).
    https://github.com/google/site-kit-wp/blob/4ebc69975bc624731085b12974fbb44142eb060c/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L303-L305
    - In the case where `isSecondAdmin` is true, assign `secondAdminLearnMoreLink` to the `learnMore` variable.
    https://github.com/google/site-kit-wp/blob/4ebc69975bc624731085b12974fbb44142eb060c/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L215-L224

### Test Coverage

* Verify the `Start - with Dashboard Sharing enabled and available` and `Start - with Dashboard Sharing enabled and available but there is only one admin` stories in `assets/js/components/setup/SetupUsingProxyWithSignIn.stories.js`.
* Update VRT images if required.

## QA Brief

* Set up Site Kit.
* Open the Dashboard Sharing settings modal and provide the administrator role access to one or more modules.
* Sign into the site as a second admin.
* Open the `/wp-admin/admin.php?page=googlesitekit-splash` page.
* Verify that a "Learn More" link is present after the description text.
* Verify that clicking on the learn more link opens the relevant documentation in a new tab.
* Verify the **Using Proxy With Sign-In** `Start - with Dashboard Sharing enabled and available` and `Start - with Dashboard Sharing enabled and available but there is only one admin` stories contain the "Learn More" link.

## Changelog entry

* Add a help link to sign in screen when Dashboard Sharing has been enabled by another admin.

**Comment by eugene-manuilov** [comment]
@felixarntz, ok, found one more link that needs its own issue. This time, it should be the last one for sure. Does AC look good to you?

**Comment by felixarntz** [comment]
@eugene-manuilov LGTM! I assume you added this to the spreadsheet for support?

**Comment by eugene-manuilov** [comment]
> * Update this string to include a link labelled `Learn More`. `createInterpolateElement` can be used to add this link.

@nfmohit, I think we can avoid using the `createInterpolateElement` approach and simply create one more optional variable `learnMore` that will be used to display the link after the description if `learnMore` is not empty:

```
let title;
let description;
let learnMore;

if ( 'revoked' === getQueryArg( location.href, 'googlesitekit_context' ) ) {
    ...
} else if ( isSecondAdmin ) {
    title = __(
        'Connect your Google account to Site Kit',
        'google-site-kit'
    );
    description = __(
        'Site Kit has already been configured by another admin of this site. To use Site Kit as well, sign in with your Google account which has access to Google services for this site (e.g. Google Analytics). Once you complete the 3 setup steps, you’ll see stats from all activated Google products.',
        'google-site-kit'
    );
    learnMore = secondAdminLearnMoreLink;
}

...

return (
    ...
    <p className="googlesitekit-setup__description">
        { description }
        { learnMore && <Link href={ learnMore } ...> }
    </p>
);
```

**Comment by nfmohit** [comment]
Neat suggestion, updated the IB. Thank you @eugene-manuilov!

**Comment by eugene-manuilov** [comment]
Thanks, @nfmohit. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A "Learn More" link is present after the description text.
- When clicking on the learn more link opens the [relevant documentation](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#already-configured) in a new tab.
- The stories detailed in the QAB contain the "Learn More" link.


<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/183088515-a69f6731-86a5-43a2-b91e-0b84c514d788.png)
![image](https://user-images.githubusercontent.com/73545194/183088532-dbdcbc1e-e1f1-4ad4-9672-e5bc6f3b3a64.png)

</details>
