### ISSUE TITLE
Update active consumers metadata when accessing shared dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5568]
Follow-up to #5567: This issue is about refreshing the active consumers data whenever a user with shared access uses the shared dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Using the infrastructure from #5567: Whenever an unauthenticated user in the plugin is accessing the **shared** dashboard, the `active_consumers` meta key for those users (module owners) that the current user gets access from for any module from should be looked up. For each of them, if the current user is not yet in that list, they should be added, or more precisely, their `id` and `roles` should be added. Also see [design doc section](https://docs.google.com/document/d/1KODBTcjRjDNNgYd4Qv-d0XlapdYkmBdyzqNTFmEg9Rg/edit?resourcekey=0-eZkvc2ChBvVP_U_p7DdtwQ#heading=h.qjeawqqo05cs).
* Particular attention should be paid to the queries to use for this:
    * It needs to be avoided that the implementation results in a database query running every time that the shared dashboard is accessed (e.g. avoid it by using a transient).
    * Try optimizing the queries that are used. As always, we should preferable use core functions. However, if using them is only possible with taking a significant performance hit, a custom query may be better.

## Implementation Brief

- Within OAuth_Client.php:
    - Create a new private reference and set it to an instance of the `Active_Consumers` class within the constructor, passing the same `User_Options` instance of `OAuth_Client`.
    - Create a new public method, say `add_active_consumer()` which will take a `WP_User` user as a parameter. It should then delegate the call to another method within `Active_Consumers`, say `Active_Consumers::add()` which should set the user's ID and the array of roles (both available in `WP_User`) to the setting (using `Active_Consumers::set()`), if the setting does not already contain the `user_id` as a key (which can be checked using `Active_Consumers::get()`).
 - Call the new method within the `Module::execute_data_request()` method, in the conditional block where we set `is_using_shared_credentials` to true.

 - Notes on caching: 
     - The method to fetch and refresh the Active_Consumers record will only run when an Module Datapoint request is made. Once the datastore in the browser has this data, we do not call the API every time we load the dashboard. 
     - Fetches from `Active_Consumers` are cached automatically since it eventually uses the `get_metadata_raw()` method (within `meta.php`) which in turn does use `wp_cache_get()`. 

### Test Coverage

* Update the `test_get_data()` and `test_set_data()` methods which call the protected `Module::execute_data_request()` in `ModuleTest.php`. 
* Cover any other additional code/methods  with corresponding PHPUnit tests.

## QA Brief

- Go to the `wp_usermeta` table and ensure the `wp_googlesitekit_active_consumers` isn't available.
- Create a couple of users, one with the `editor` role and the other with the `contributor` role.
- Share a few modules with `editor` and `contributor`. For example, share Analytics and Search Console using Dashboard Sharing.
- Login to the view-only dashboard as the new users.
- Go to the `wp_usermeta` table and ensure the `wp_googlesitekit_active_consumers` is available with the value of an array that consists of `[user's id]` as the key and the roles as the value as described in the AC.

## Changelog entry

* Update shared user metadata when accessing shared dashboard.

**Comment by FlicHollis** [comment]
Hey @jimmymadon same with this one - Has this IB been started? If not, feel free to unassign yourself so that any of the team can pick it up. Thanks so much!

**Comment by jimmymadon** [comment]
@FlicHollis I have made some progress on them and will get them into IBR asap.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – regarding the use of `Active_Consumers`, I'd prefer if we avoid `User_Options::switch_user()` as that could have unintended consequences, especially if it's a shared instance.

Instead, I'm thinking it might make sense to add this as a method to the `OAuth_Client` which would have its own private instance of `Active_Consumers` which would use the same `User_ _Options` instance of the class. Then, in the `execute_data_request`, we already have the `owner_oauth_client` which is scoped to the module owner thus always pointing to the right user. It could expose a method to "add active consumer" or something along those lines which might take a `WP_User` which provides both the ID and list of roles. Then the only thing we'd need to do is call it for shared requests, which we already have the condition for as you identified. How does that sound?

**Comment by jimmymadon** [comment]
Thanks @aaemnnosttv - sounds much cleaner! Updated the IB.

**Comment by jimmymadon** [comment]
Thank you @aaemnnosttv - that makes sense. IB updated.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

 
@hussain-t 

- Verified on dev environment.

- Under `wp_usermeta `table `wp_googlesitekit_active_consumers` is available when user with shared role permission  access site kit dashboard. DB creates entry  for every every new user role under `wp_googlesitekit_active_consumers`  . 
- I noticed that we are not creating separate entry for each users. We actually defining user id value using 'i'. example -` a:4:{i:2;a:1:{i:0;s:6:"editor";}` - Here i:2 is user id.

I have below questions related to this - 

**Q1)** Are we going to keep entry for deleted users and user role because currently if I delete any user or user role having shared permission then it's entry is not getting delete from `wp_googlesitekit_active_consumers` ?

Q2) Based on the AC - Do you feel this needs the `QA:eng` label adding for an engineer to have a look ?

![image](https://user-images.githubusercontent.com/94359491/198602402-744c6ea6-5891-4e5c-a33f-f786e57021b6.png)

**Comment by jimmymadon** [comment]
@mohitwp 

> - I noticed that we are not creating separate entry for each users. We actually defining user id value using 'i'. example -` a:4:{i:2;a:1:{i:0;s:6:"editor";}` - Here i:2 is user id.

This seems to be the correct behaviour. The user IDs within the same row should be of the view-only users you logged in as and the `user_id` within the `wp_usermeta` table for that row should be that of the admin(s) of the site that shared the modules.

> **Q1)** Are we going to keep entry for deleted users and user role because currently if I delete any user or user role having shared permission then it's entry is not getting delete from `wp_googlesitekit_active_consumers` ?

Based on my [comment](https://github.com/google/site-kit-wp/issues/5569#issuecomment-1295278071) in #5569, we will be deleting the whole row regularly every time an admin's token is refreshed. So new records will be created regularly as well and this row of data will generally be 'fresh'. So there should be no need to delete data from this record if a user or role is deleted.

> Q2) Based on the AC - Do you feel this needs the `QA:eng` label adding for an engineer to have a look ?

I did indirectly QA:Eng'ed / tested this issue when testing #5569 so we can move this to Approval if everything else looks ok.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you for answering my questions [here](https://github.com/google/site-kit-wp/issues/5568#issuecomment-1297131170) .

- Verified on dev environment.

- Under `wp_usermeta `table `wp_googlesitekit_active_consumers` is available when user with shared role permission  access site kit dashboard. DB creates entry  for every every new user role under `wp_googlesitekit_active_consumers` .

- Technical points under AC is already verified by Jimmy as part of testing https://github.com/google/site-kit-wp/issues/5569

![image](https://user-images.githubusercontent.com/94359491/198602402-744c6ea6-5891-4e5c-a33f-f786e57021b6.png)
