### ISSUE TITLE
Send new `active_consumers` body parameter in “refresh_token” request

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5569]
Follow-up to https://github.com/google/site-kit-wp/issues/5567: This issue is about sending the active consumers data alongside any `refresh_token` request.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Requests to the `/o/oauth2/token/` service endpoint with `grant_type` set to `refresh_token` (i.e. requests to refresh an access token) should be updated to include an additional `active_consumers` body parameter _if_ the user for which the token is refreshed has (non-empty) `active_consumers` user metadata available.
    * The `active_consumers` parameter should be a string with the `active_consumers` metadata sanitized as follows:
        * Each entry in the root array separated by a space.
        * The `id` and `roles` segments for each entry separated by a colon (`:`).
        * Each role separated by a comma.
        * For example, `array( array( 'id' => 2, 'roles' => 'administrator', 'shop_owner' ), array( 'id' => 13, 'roles' => 'editor' ) )` should be `2:administrator,shop_owner 13:editor`.
* This was originally outlined in [this design doc section](https://docs.google.com/document/d/1KODBTcjRjDNNgYd4Qv-d0XlapdYkmBdyzqNTFmEg9Rg/edit?resourcekey=0-eZkvc2ChBvVP_U_p7DdtwQ#heading=h.oyd5bia88ba6). It is not a must to follow exactly that implementation, but it will definitely require overriding the `​​Google\Site_Kit_Dependencies\Google\Auth\OAuth2` class as stated there (and integrating that new class into our proxy-specific OAuth client class). A potential idea would be to decouple allowing addition of other parameters from the specifics of adding _this_ particular `active_consumers` parameter, so that the logic for that parameter could e.g. be part of the entry point class added for this feature in #5567.
* **Update:** Once a `refresh_token` request has been completed successfully, the `active_consumers` meta data entry for the user whose refresh token was refreshed should be deleted, effectively causing a reset, so that afterwards it will be populated from zero again. This is crucial to not always keep sending the same user IDs along to the service even if some of them are no longer using the plugin or haven't recently used it.

## Implementation Brief

* Please read ["Note to the IB Reviewer"](https://github.com/google/site-kit-wp/issues/5569#issuecomment-1272403309) for reasoning and alternatives considered for some of the below.

* Within `includes/Core/Authentication/Clients/`, create a new class `OAuth2`:
    - This class should extend `/third-party/google/auth/src/OAuth2.php` (`​​Google\Site_Kit_Dependencies\Google\Auth\OAuth2`).
    - Create (override) the `generateCredentialsRequest()` method which should:
        - Accept an array of key-value pairs as params to be added to the body of the refresh token request. (Make the parameter optional with a default value of an empty array).
        - Call the parent `​​Google\Site_Kit_Dependencies\Google\Auth\OAuth2::generateCredentialsRequest()` method which returns an instance of `Google\Site_Kit_Dependencies\GuzzleHttp\Psr7\Request`. 
        - Get the `grantType`. If the `grantType` is anything other than `refreshToken`, return the `Request` as is.
        - If the `grantType` is `refresh_token`, then modify the body of the `Request`. Get the params for this request using `Request::get_body()` which returns a `Stream`. Convert the stream to a string using `\Google\Site_Kit_Dependencies\GuzzleHttp\Psr7\Utils::copyToString($body)`. Finally, use ` \Google\Site_Kit_Dependencies\GuzzleHttp\Psr7\Query::parse($string)` to convert the string to an associative array of params. Add the `param` passed to this method into this array and use `\Google\Site_Kit_Dependencies\GuzzleHttp\Psr7\Utils::modifyRequest($body)` to update the body.
* Within `includes/Core/Authentication/Clients/Google_Site_Kit_Proxy_Client`:
    - In `createOAuth2Service()`, use the new `OAuth2` class created above keeping everything else the same.

* Within `includes/Core/Authentication/Clients/Google_Site_Kit_Client`: 
    - Modify the signature of the `fetchAuthToken()` method to accept the new OAuth2 class created above.

* Within `Activity_Metrics`:
    - Create a method, say `get_for_refresh_token()`, which for now will fetch the `active_consumers` record, convert the array to a string as per the AC and return an array with `active_consumers` as the key and the string as the value.

* Within `OAuth_Client`:
    - Create a new private reference and set it to an instance of the `Activity_Metrics` class within the constructor, passing the same `Context` and `User_Options` instances of `OAuth_Client`.
    - Within the `refresh_token()` method, call the `get_for_refresh_token()` and pass the result to `fetchAccessTokenWithRefreshToken()` and eventually to `generateCredentialsRequest()`.

### Test Coverage

* Update existing tests if necessary (`OAuth_ClientTest::test_refresh_token`) and add new PHPUnit tests for all the new methods defined in the IB.

### QA:Eng

- In `includes/Core/Dashboard_Sharing/Activity_Metrics/Activity_Metrics.php`:
    - Within the `register` method, set some dummy active consumers using the `set` method of the `Active_Consumers` class. The dummy data could look something like the following:
    ```php
    $this->active_consumers->set(
        array(
            1 => array( 'administrator', 'editor' ),
            2 => array( 'author', 'contributor' ),
            3 => array( 'subscriber' ),
        )
    );
    ```
- Stop your local environment.
- Configure HTTP proxy on your local machine following instructions in the [engineering workflow doc](https://docs.google.com/document/d/1vYRA-YxxZdufO6piF0gA1k60N3UxbvuqyQr_XfGgvSk/edit#heading=h.faf0umy03arh).
- Reset token creation time by running the following command:
  ```
  10updocker wp user meta set 1 wp_googlesitekit_access_token_created_at 1
  ```
- Start the `mitmweb` app (GUI for `mitmproxy`).
- Start your local environment.
- Open Site Kit Dashboard.
- Check the `mitmproxy` log and confirm that you see only one request to the `https://sitekit.withgoogle.com/o/oauth2/token/` endpoint.
- Check the `mitmweb` log and confirm that request to the `https://sitekit.withgoogle.com/o/oauth2/token/` endpoint includes `active_consumers` key in its body, with your dummy data as the value but in the format as described in the ACs.

**Update:** Verify that after a successful request to refresh a token through another view-only dashboard user, the _sharing_ user's (the one whose token was refreshed) `active_consumers` meta key is deleted.

## Changelog entry

* Send active consumers data alongside the request to refresh an access token.

**Comment by jimmymadon** [comment]
Note to IB Reviewer:

>Accept an array of key-value pairs as params to be added to the body of the refresh token request. (Make the parameter optional with a default value of a null array).

Originally considered creating and applying a filter which could be used by other classes to "add" whatever params needed to be sent with the `refresh_token` request. This would have serious security concerns.

> Create a method, say `get_for_refresh_token()`, which for now will fetch the `active_consumers` record

The [design doc section](https://docs.google.com/document/d/1KODBTcjRjDNNgYd4Qv-d0XlapdYkmBdyzqNTFmEg9Rg/edit?resourcekey=0-eZkvc2ChBvVP_U_p7DdtwQ#heading=h.oyd5bia88ba6) refers to passing the `User_Options` instance to the new `OAuth2` class so we can fetch the `active_consumers` setting for that user when adding the metadata params to the refresh_token request. But this AC further suggests:
>A potential idea would be to decouple allowing addition of other parameters from the specifics of adding _this_ particular `active_consumers` parameter, so that the logic for that parameter could e.g. be part of the entry point class added for this feature in #5567.

So I think the `Activity_Metrics` class can be used to group any and all metrics we want to pass as metadata within the `refresh_token` request. This does not have to be limited to `active_consumers` and can be used to fetch other metrics in the future from their relevant settings classes.

**Comment by tofumatt** [comment]
IB ✅

**Comment by jimmymadon** [comment]
### ⚠️ QA

@felixarntz The implementation does meet the AC here. However, the Design Doc says:
>Once the request has been completed successfully on the plugin side, the “active_consumers” metadata for the relevant owner that just had their token refreshed should be deleted, so that any users with shared access through that user will have to access the Site Kit dashboard again before the next time a token needs to be refreshed, to remain considered as active users.

Should this be done as part of this issue or should we create another one?

Verified (Instead of following the QAB, I used real `active_consumers` data created by the code merged in #5568 by creating an admin and two view-only users):
- When there is no `wp_googlesitekit_active_consumers` in the DB or if it's value is empty, the token refresh request does not contain the `active consumers` data.
![Screenshot 2022-10-28 at 18 24 56](https://user-images.githubusercontent.com/1721319/198698032-b244f5fb-61a7-44ee-a152-628da15e1378.png)

- When a view-only user with a single WP role lands on the view only dashboard making requests, the `wp_googlesitekit_active_consumers` gets updated. When the refresh token is manually 'expired' as suggested in the QAB, the request does contain the correct data. Verified this with a user with two roles, including a custom role as well.
![Screenshot 2022-10-28 at 18 13 36](https://user-images.githubusercontent.com/1721319/198698857-af9882b6-cc7f-4dec-a163-f185ff0f9106.png)
![Screenshot 2022-10-28 at 18 25 48](https://user-images.githubusercontent.com/1721319/198698762-b805b128-7977-47bb-9cf3-c79f217c5d8f.png)

- Verified that the request contains data from multiple view-only users as well.
![Screenshot 2022-10-28 at 18 16 42](https://user-images.githubusercontent.com/1721319/198698970-5fa78e09-d0ed-4cec-be98-0563d60e1dfb.png)

**Comment by felixarntz** [comment]
@jimmymadon Thank you for flagging this, my bad for missing this in the ACs. This is critical though, so I have added a point to the ACs, which should be sufficient. Since we still have a week until the next release and since most likely this will only involve deleting a single meta key, I think that should be reasonable to add in a follow-up PR for this issue. cc @nfmohit

**Comment by nfmohit** [comment]
Thank you for the confirmation, @felixarntz!

@jimmymadon As Felix mentioned, I have moved this issue to execution and self-assigned it to work on the follow-up PR.

**Comment by nfmohit** [comment]
I have opened #6093 to address the update above.

**Comment by jimmymadon** [comment]
## QA ✅ 

- Verified all scenarios as described in my previous comment. 
- Further verified that the `active_consumers` record is deleted when a `refresh_token` request is made. Also verified that when a user uses access tokens from two admins, only the admin whose token was refreshed gets their record deleted (the other admin's record still exists in the DB) until their token is refreshed.

<Details>
<Summary>Screenshots:</Summary>

![Screenshot 2022-11-02 at 17 26 41](https://user-images.githubusercontent.com/1721319/199563008-30a8328c-8ec3-401f-a0fd-b61052c01580.png)

![Screenshot 2022-11-02 at 17 29 47](https://user-images.githubusercontent.com/1721319/199562716-cb996755-08c6-4617-a50b-8c4795bb4992.png)

![Screenshot 2022-11-02 at 17 34 38](https://user-images.githubusercontent.com/1721319/199562741-0ae49895-c6b2-4507-84a4-49b62b4315d3.png)

</Details>
