### ISSUE TITLE
Remove Space underneath new AdSense CTA

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5578]
## Bug Description

Currently, we have a large blank space  underneath the new Google AdSense CTA on the Site Kit dashboard.

Minor, but would look better if the CTA was closer to the footer. 

![image](https://user-images.githubusercontent.com/73545194/180014691-d84ca586-33bf-4f60-90a1-7011e0cd5cc8.png)

## Steps to reproduce

1. Create a new site and connect Site Kit
2. Go to 'Site Kit Dashboard'
3. Click on 'Monetization'
4. You will scroll down to the AdSense CTA
5. See space underneath. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This isn't specific to AdSense but the last section on the page which happens to be AdSense at first but will be the previous section if the CTA is dismissed for example.

This was done intentionally in https://github.com/google/site-kit-wp/issues/4490 👍
