### ISSUE TITLE
Refactor datapoint contextual data to use new class

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#558]
## Feature Description

Currently the `$data` object passed to `create_data_request` is an array.

https://github.com/google/site-kit-wp/blob/82d9f4164e3d400fec8221fa7f750298b17859b7/includes/Core/Modules/Module.php#L389-L399

This works just fine as a parameter, but within the handlers for each datapoint (currently limited to `create_data_request` but soon to also include response parsing in #340) this becomes a bit cumbersome when having to deal with keys potentially existing in the `$data` object due to PHP's limitations for arrays.

Ideally, we could access keys directly without needing to write extra code to handle potentially non-existent keys. Similar to WP's `WP_REST_Request` object, we could wrap the `$data` object passed in `create_data_request` with our own `Request` type object which would implement [`ArrayAccess`](https://www.php.net/manual/en/class.arrayaccess.php).

This would allow for consuming code to be cleaned up considerably and less vulnerable to errors related to non-existent keys.

It could also contain the other parameters as well such as `$datapoint` and `$method` to make the full context of a datapoint request available via a single object (similar to `WP_REST_Request`).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new class `Google\Site_Kit\Core\Util\Data_Request` should be introduced that implements `ArrayAccess`.
    * Its constructor should receive arguments `method`, `type`, `identifier`, `datapoint`, and `data` (see [JS API]() for what these are).
    * The entire class should be read-only, only the constructor should be able to write data into it.
* Update signatures of `Module::create_data_request()`, `Module::parse_data_response()`, and `Module::execute_data_request()` to only accept an instance of the above class.
* The `Module::create_data_request()` and `Module::parse_data_response()` methods should receive the same class instance for the same request.
* Module classes need to be updated to be compatible with the new method signatures.
* Modules that currently use ugly temporary class properties to access request data from `parse_data_response()` should be updated to directly rely on the `Data_Request` instance.

Note: The new class should be able to cater for all kinds of data requests (which are not limited to modules, see JS API). However, in the rest of the PHP infrastructure it is fine to only use it internally in `Module` for now. We can make further updates later.

## Implementation Brief

* Create new `Data_Request` class, implementing `ArrayAccess`
    - `$request[key]` will return `$data[key]` from the provided data object or `null` if not set
    - `$request[key] = new value` will not mutate the `$data` object
    - Add getters for accessing all values of parameters passed via the constructor
        - `get_method()`
        - `get_type()`
        - `get_identifier()`
        - `get_datapoint()`
        - `get_data`
    - Add `to_array` and `from_array` helpers to allow for creating new data request objects from an existing object
    - PHPUnit coverage
* Update the signatures of `Module::create_data_request()`, `Module::parse_data_response()`, and `Module::execute_data_request()` to `( Data_Request $data )`.
* Update `get_data` and `set_data` methods to create `Data_Request` objects from parameters to pass to `execute_data_request`
* Update Module `(create|parse)_data_request` method bodies to use data request objects instead of current parameters.
* Update `Module::get_batch_data` to create `Data_Request` objects for each `$dataset` to be passed to `(create|parse)_data_request`
* Update `parse_data_response()` to include the `$data` parameter in the method signature in all six module classes, according to the base class.
* Fix ugly workarounds currently used to properly use the `$data` parameter:
    * `\Google\Site_Kit\Modules\TagManager::$_list_accounts_data`
    * `\Google\Site_Kit\Modules\TagManager::$_containers_account_id`
    * `\Google\Site_Kit\Modules\Site_Verification::$_siteverification_list_data`
    * `\Google\Site_Kit\Modules\Analytics::$_data`
* Add basic PHPUnit test coverage for data infrastructure in modules:
    * Augment the existing `FakeModule` to provide a simple `GET` and `POST` datapoint that don't make any API requests. Both endpoints should have logic executed in `create_data_request()` and `parse_data_response()`.
    * Enhance the existing tests for `get_data()`, `set_data()`, and `get_batch_data()` in `ModuleTest` to ensure they actually handle these requests correctly (currently they really only check method signature, which is too basic).

## Changelog entry

* Make full data request available to the respective `Module` class's response handler.

**Comment by felixarntz** [comment]
This issue surpasses #340 because it fixes the same thing in a cleaner way. I'll close #340.

**Comment by felixarntz** [comment]
Note regarding implementation brief: Please have a look at #340, parts of that can be reused (e.g. regarding basic PHPUnit coverage).

**Comment by felixarntz** [comment]
IB ✅ 

@aaemnnosttv Regarding

> Update Module `(create|parse)_data_request` method bodies to use data request objects instead of current parameters.

let's simply assign the values from the `Data_Request` instance to the already-used variables on top of the respective method. That keeps the other required changes at a minimum to make it less error-prone.

**Comment by aaemnnosttv** [comment]
> let's simply assign the values from the `Data_Request` instance to the already-used variables on top of the respective method. That keeps the other required changes at a minimum to make it less error-prone.

That's what I was thinking as well 👍

**Comment by aaemnnosttv** [comment]
Heads up @adamsilverstein I'm sending this one your way for QA 🏄 
Let me know if you have any questions!

**Comment by adamsilverstein** [comment]
This looks great, nice improvements here @aaemnnosttv! I'll give this a test.

**Comment by adamsilverstein** [comment]
QAing this issue everything looks good, moving to Approval.

I tested data flow and checked for any errors.
Reviewing the AC, I can verify:
 - [x] New class Data_Request implements ArrayAccess
 - [x] Updated signatures of Module::create_data_request(), Module::parse_data_response(), and Module::execute_data_request() - they now take the `Data_Request` object.
 - [x] verified create_data_request and parse_data_response use the same Data_Request object.
 - [x] verified all Module updated with new signatures
 - [x] verified removal of code that temporarily stored request data in favor of relying on Data_Request instance


### Testing Procedure
* Rest site kit and run thru activating search console, analytics and pagespeed insights.
* Verify data flowing correctly for each service.
* Note no PHP notices or errors, no console errors.
* Repeat tests with PHP 5.4 and PHP 7.3.

**Comment by adamsilverstein** [comment]
Immediately after posting this I noticed an error when setting up AdSense, holding off on approval. Here are the details of the error, checking for a fix now:

`PHP Warning:  array_merge(): Expected parameter 2 to be an array, object given in /site-kit-wp/includes/Modules/AdSense.php on line 554`

![image](https://user-images.githubusercontent.com/2676022/67584936-e29aaf80-f70b-11e9-9246-a3e7e2ec2759.png)

**Comment by adamsilverstein** [comment]
@aaemnnosttv The code handling dates in AdSense.php is expecting an array here, looks like we need to update the date handling as you did elsewhere in https://github.com/google/site-kit-wp/pull/695. 

This failed QA, moving back to To Do.

**Comment by aaemnnosttv** [comment]
@felixarntz are you able to perform the final QA on this one? @adamsilverstein said that the AdSense datapoint error was the only failure and he confirmed that this was fixed by #715.

**Comment by felixarntz** [comment]
Final QA ✅
