### ISSUE TITLE
Set Correct Owned Keys For Thank With Google Settings

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5587]
## Feature Description

When converting old SwG Settings Class to TwG Class, we accidentally made All the settings keys owned keys which is not correct. Only the `publicationID` should be an owned key. Let's remove the others from the owned keys and add tests accordingly. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `publicationID` should be the only owned setting for Thank with Google
* The `Google\Site_Kit\Tests\Modules\Thank_With_Google\SettingsTest` (added in #5461) test case should implement the `Setting_With_Owned_Keys_Trait` for consistency with others

## Implementation Brief

* In the `get_owned_keys` method of `Google\Site_Kit\Modules\Thank_With_Google\Settings` class:
    * Only keep `publicationID` and remove others from the return array. 
* In `Google\Site_Kit\Tests\Modules\Thank_With_Google\SettingsTest` class: 
    * Import and use `Google\Site_Kit\Tests\Core\Storage\Setting_With_Owned_Keys_ContractTests`.
    * Implement the `get_setting_with_owned_keys` protected method.
    * See `Google\Site_Kit\Tests\Modules\Tag_Manager\SettingsTest` for an example. 

### Test Coverage

* The existing and newly added TwG tests should pass. 

## QA Brief

**This is maybe best QA'd as a QA:Eng as we don't have the UI to connect TwG module or change settings.**

* Complete TwG Setup by pasting the following snippet in browser console after clicking Connect Service on Thank with Google. 
```js
( async () => {
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.setPublicationID( 'Test-Pub_id' );
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.setColorTheme( 'blue' );
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.setButtonPlacement( 'dynamic_low' );
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.setButtonPostTypes( [ 'post' ] );
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.saveSettings();
	window.location.href = '/wp-admin/admin.php?page=googlesitekit-settings#/connected-services';
} )();
```
* Check the current TwG owner ID with the following snippet. 
```js
googlesitekit.data
		.select( 'modules/thank-with-google' ).getOwnerID()
```
* Switch to another admin account and connect site kit. 
* Change a non-owned key such as `buttonPostType` using the following snippet:
```js
( async () => {
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.setButtonPostTypes( [ 'post', 'page' ] );
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.saveSettings();
	window.location.href = '/wp-admin/admin.php?page=googlesitekit-settings#/connected-services';
} )();
```
* Make sure the change is saved.
```js
googlesitekit.data
		.select( 'modules/thank-with-google' ).getButtonPostTypes()
```
* Check that the ownerID has not been changed.
```js
googlesitekit.data
		.select( 'modules/thank-with-google' ).getOwnerID()
```
* Now change the `publicationID`.
```js
( async () => {
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.setPublicationID( 'Test-Pub_NewId' );
	await googlesitekit.data
		.dispatch( 'modules/thank-with-google' )
		.saveSettings();
	window.location.href = '/wp-admin/admin.php?page=googlesitekit-settings#/connected-services';
} )();
```
* The `ownerID` should now change to the new admins ID.
```js
googlesitekit.data
		.select( 'modules/thank-with-google' ).getOwnerID()
```
* Rerun the `get` snippets if first time they return `undefined`. 

## Changelog entry

* Update the TwG module to have only publicationID setting as owned.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by eugene-manuilov** [comment]
> * No need to QA this regularly as long as the tests pass.

@kuasha420 we need to make sure that the owner ID is not getting changed when other settings are changed. Could you please update QAB with instructions how to change TwG settings and how to verify that the owner ID hasn't changed?

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@kuasha420 thank you so much for the detailed QAB, this helped a lot!   I just have one observation. 

I pasted the code to change a non-owned key such as buttonPostType using the snippet.

When I ran this code I received an error:

```
googlesitekit.data
		.select( 'modules/thank-with-google' ).setButtonPostTypes()
```

Error message:

```
VM1397:2 Uncaught TypeError: googlesitekit.data.select(...).setButtonPostTypes is not a function
    at <anonymous>:2:42
```

All of the other steps worked perfect, even the steps after running this code.    Any thoughts?

**Comment by kuasha420** [comment]
@wpdarren I made a copy paste error here as the snippet would be the following:

```js
googlesitekit.data
		.select( 'modules/thank-with-google' ).getButtonPostTypes()
```

Also rerun the snippets to `get` if it returns `undefined` first time. 

Cheers.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Ran through the steps in the QAB:  
  - Checked the current TwG `owner ID` with the following snippet. (it appeared as '1') 
  - Switched to another admin account and connected site kit 
  - Changed a non-owned key `buttonPostType` using the snippet.
  - Confirmed that the change had saved to the `buttonPostType`
  - Confirmed that the `ownerID` has not been changed. (was still appearing as '1')
  - Changed the` publicationID` and confirmed that the `ownerID` has changed (it appeared as '2')

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/181047027-19b2cdc2-50ab-493b-92a3-544b13c6c225.png)
![image](https://user-images.githubusercontent.com/73545194/181047245-d4526d1d-ee27-419e-a18a-37440285a4ed.png)

</details>
