### ISSUE TITLE
PHPUnit tests broken on nightly

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5593]
## Bug Description

Due to a recent change in WordPress trunk that renamed the wpdb class' filename, our PHPUnit tests for WP nightly have broken due to the core WP files and WP test lib files installing versions that are out of sync.

## Steps to reproduce

1. See a recent PHP Tests run for WP nightly https://github.com/google/site-kit-wp/runs/7455626865?check_suite_focus=true#step:9:15

## Screenshots

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/1621608/180299714-5cab6694-8687-4344-a644-8e35d1335403.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PHP tests for the WP nightly build should not fail due to missing files

## Implementation Brief

* Update the bundled `install-wp-tests.sh` script to the latest version defined in the WP-CLI scaffold repo
	* This fixes the problem by using `svn` to checkout the latest core files rather than downloading the https://wordpress.org/nightly-builds/wordpress-latest.zip which is not always up-to-date with trunk
* Move the bundled script from `tests/bin` to `tests/phpunit/bin` so that changes to it trigger PHP Tests (the script is specific to PHPUnit tests anyways)
	* Update references to this in the `tests/README.md`
* Merge https://github.com/google/site-kit-wp/pull/5594

### Test Coverage

* No changes other than tests against WP nightly should run again rather than erroring during the initial bootstrapping process

## QA Brief

* PHP Tests against develop may not run for this issue's PR because it only targets a shell script

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅ 

I'll merge this as well 👍🏻

**Comment by tofumatt** [comment]
(Moved directly to approval as there's no QA needed here; tests are now passing so issue is resolved.)
