### ISSUE TITLE
Updating analytics UI for public 

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#56]
## Feature Description

Introduce settings to control Analytics parameters.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by felixarntz** [comment]
Potentially we should provide an option to allow for anonymizing IPs (see #18).

#55 makes any kind of adjustments possible, now as part of this one we need to figure out which parameters we want to display settings UI for.

**Comment by marrrmarrr** [comment]
IP anonymisation for GA is already implemented in [1.1.4](https://github.com/google/site-kit-wp/releases/tag/1.1.4); closing this generic issue.
