### ISSUE TITLE
Remove the "Create Client ID" step (step 1) from the Setup Flow

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#560]
## Feature Description

Remove step 1: "Create Client ID": that is presented immediately after installing the plugin and clicking the Dashboard or "Set up Site Kit".  

Users are currently presented with 

![image](https://user-images.githubusercontent.com/2676022/65280900-8df18c80-daee-11e9-9d8b-a11dd7c046c5.png)

This step can be removed _in a feature branch_ in preparation for upcoming setup changes. 

There will only be 4 steps in the setup flow (as it is currently for secondary Admins):

![image](https://user-images.githubusercontent.com/2676022/65281353-a7df9f00-daef-11e9-98e5-7015cc016e71.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Create Client ID" step from the current setup flow should no longer be present. For this flow, the client ID and secret will always need to be provided via filter in the future.
* The other steps should be renamed accordingly.

## Implementation Brief

* Remove step definition  
https://github.com/google/site-kit-wp/blob/39e8d2de110dd34c8c6711239b3018b41d1545b8/assets/js/components/setup-wizard/wizard-steps.js#L31-L37
* Remove `WizardStepClientCredentials`
* Update E2E tests
* Update Storybook/VRT
    - Update Setup/Client ID story to show the new Step 1

## Changelog entry

* Remove first setup step for client credentials since those should only be provided via the authentication proxy or filter.

**Comment by felixarntz** [comment]
Implementation brief ✅

**Comment by felixarntz** [comment]
Updating the milestone because this needs to be in the same release as the proxy.

**Comment by felixarntz** [comment]
QA ✅
