### ISSUE TITLE
Prevent dashboard from crashing when async SVG fails to load

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5605]
## Bug Description

There have been a couple of users who reported a `Loading chunk 33 failed` dashboard error, both since Site Kit 1.79.1. 

```
Loading chunk 33 failed.
(error: http://domainname.com/wp-content/plugins/google-site-kit/dist/assets/js/33-a742fa632cd94e4fa105.js)
in Unknown
in LazyContentSVG
in Suspense
in ContentSVG
in div
in div
in div
in Cell
in div
in ForwardRef
in ForwardRef
in ContentAutoUpdate
in div
in ForwardRef
in section
in AdSenseConnectCTA
in div
in div
in Widget
in WithWidgetSlug(Widget)
in AdSenseConnectCTAWidget
in WidgetRenderer
in div
in Cell
in WidgetCellWrapper
in div
in ForwardRef
in div
in div
in ForwardRef
in WidgetAreaRenderer
in div
in WidgetContextRenderer
in DashboardMainApp
in DashboardEntryPoint
in RestoreSnapshots
in ErrorHandler
in StrictMode
in Root
```

## Additional Context

 - SK 1.79.1
 - No SH info so far
 - One site does seem to have mismatching URLs, evident from checking their public REST endpoints
 - Awaiting further details

## Impacted sites
- https://wordpress.org/support/topic/loading-chunk-33-failed/ | **Open** | No SH info
- https://wordpress.org/support/topic/site-kit-encountered-an-error-74/ | **Open** | No SH info
- https://wordpress.org/support/topic/site-kit-encountered-an-error-75/ | **Open** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNglaTX8QFbNrwYw1ddjDcllMH8-xOp_hbzj8xF-uBrmgzZRfayXVy18qlKxVPUM1wo)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Lazy-loaded graphics should be loaded in a common way that prevents a failed import from crashing the dashboard
	* In this case, a suitable light-weight non-lazy-loaded fallback should be rendered in its place. For now this can simply be an error message styled similar to use in other places:
	> Error: Failed to load graphic.
	* This should be an edge case so we don't need to make it a polished experience.

## Implementation Brief
* Create `assets/js/components/MediaErrorHandler.js` which exports the class based `MediaErrorHandler` component.
	* The component should have the same logic as `assets/js/components/ErrorHandler/index.js` with the following changes:
		* It should accept a required string prop `errorMessage`.
		* The `copied` state variable and associated functionality should be removed, leaving the `error` and `info` state variables.
		* There should only be the `componentDidCatch` and `render` functions.
		* The `render` function should render `children` if there's no `error` and `errorMessage` in case there's one.
		* The `errorMessage` should be wrapped within a `p` tag and should be styled using the same color as for error messages. (#7a1e00)
* Using `assets/js/modules/adsense/components/common/AdSenseConnectCTA/ContentSVG.js`,
	* Wrap the existing components within `MediaErrorHandler` with `errorMessage` prop set as per the AC.
* Add stories for `MediaErrorHandler` within `assets/js/components/MediaErrorHandler.stories.js`
* Note: To reproduce/simulate error, delete `0.js` or `1.js` in `dist/assets/js/`

### Test Coverage
* Add tests for the `MediaErrorHandler` component.

## QA Brief

- Ensure that you are using the development build of Site Kit.
- Ensure that Adsense is not set up and the Adsense Connect CTA widget is visible.
- Enter the file manager and go to the `wp-content/plugins/google-site-kit/dist/assets/js` folder.
- Rename the `0.js`, `1.js`, or `2.js` file, or all of them to something like `*.old.js` so that the application cannot find them.
- Go to the Site Kit Dashboard.
- Verify that the dashboard doesn't crash.
- Verify that the Adsense Connect CTA widget shows an error according to the ACs for the missing graphics.
- Verify the Components > MediaErrorHandler Storybook story.

**Follow-up Update**
- Follow the above first three steps.
- Rename the `3.js` file to something like `3.old.js` so the application cannot find it.
- Ensure the IdeaHub CTA widget shows an error according to the AC for the missing graphics. Refer the screenshot below:

![Screenshot 2022-11-15 at 11 49 16 AM](https://user-images.githubusercontent.com/24408261/201844255-ef24390d-93e7-43bc-a5b4-a5b37fc5c21f.png)

## Changelog entry

* Prevent dashboard from crashing when async SVG fails to load.

**Comment by jamesozzie** [comment]
One more report of this today. One similarity to another impacted user is that this user has their site as https, yet their REST endpoints indicate both site references as http. Awaiting further details from correspondence with user.

**Comment by jamesozzie** [comment]
I've been trying to recreate this based on the reports we have so far, although with no luck at this point. [Internal testing task](https://app.asana.com/0/1185360131189553/1202675091380974). 

We have no Site Health information reports yet, and my testing was based on mixed content, and mismatching URLs. Awaiting further insights from impacted users.

**Comment by jamesozzie** [comment]
With [one users SH info now provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNglaTX8QFbNrwYw1ddjDcllMH8-xOp_hbzj8xF-uBrmgzZRfayXVy18qlKxVPUM1wo) I set up a site with the same plugins and theme active. In my case I wasn't able to recreate. 

From reviewing both site URLs which we now have it looks like both are using CDNs, one Cloudflare and the other Amazon's Litesail. Awaiting further insights

**Comment by jamesozzie** [comment]
[One user reported](https://wordpress.org/support/topic/site-kit-encountered-an-error-75/) that this issue no longer occurs once both their site URLs are defined as https. With [one other impacted](https://wordpress.org/support/topic/site-kit-encountered-an-error-74/) user having mismatching URLs I suspect this may also be the cause for that user, who didn't yet respond to our last query. 

With one other impacted user making use of a free hosting provider that did result in setup issues based on previous resting at support level we'll keep this open for another few days to check for further reports.

**Comment by jamesozzie** [comment]
[Another user](https://wordpress.org/support/topic/site-kit-encountered-an-error-87/) reported the same error this week. As with other impacted users, this seems to come from mismatching URLs defined within their WordPress settings (site address and WordPress address). One may be https, the other http, or a site served a secure, but with the site URLs referencing http only. 

[Testing performed to try and recreate](https://app.asana.com/0/1201238173167296/1203106992759645/f) based on the same scenario - a secure site with their site URLs as http. 

For those impacted by this error, check your WordPress general settings, to ensure your site URLs are correct. 

Keeping this open for the moment, to discuss or test further.

**Comment by bethanylang** [comment]
@aaemnnosttv Tagging you in here as we discussed this in today's support/eng sync. Let's see if we can make this a clearer message for users.

**Comment by aaemnnosttv** [comment]
After taking a look here, I think we can make some small changes to make for a better experience in such a scenario. Moving forward to AC 👍

**Comment by asvinb** [comment]
@eugene-manuilov I initially thought about the same thing but looking at the `ErrorHandler` component, it's mostly what we need, except that we don't want to render the `Notification` component but render a custom message. On top of that we already have tracking, what's why i was more inclined to reuse the existing `ErrorHandler` with the added flexibility of displaying a custom error message. Happy to hear your thoughts about it, but happy to have a separate component as well :)

**Comment by eugene-manuilov** [comment]
@asvinb, yes, I understand your intention, but I think we should still use a separate component and not change the `ErrorHandler` component to avoid making even more changes there in the future if we decide to add a fallback image or anything else to the error boundary for svg images.

**Comment by asvinb** [comment]
Thanks @eugene-manuilov ! IB updated!

**Comment by aaemnnosttv** [comment]
## ⚠️

Looking at the PR that was merged, the solution is incomplete as only one component was updated. There are still other lazy-loaded graphics which should be updated. The ones for TwG will be removed soon so we don't need to touch those. This leaves the one for Idea Hub here:
https://github.com/google/site-kit-wp/blob/82474ec5796066b76a2ef281882304a4603d7fef/assets/js/modules/idea-hub/components/common/IdeaHubPromptSVG.js#L28-L30

Secondarily, the idea here was that this would introduce a common component/api for rendering lazy graphics, which would make it easier to make sure this isn't missed in the future. This wasn't very explicit in the requirements about how that should happen so perhaps it may have been a bit too loose 😄 We can iterate on this with a follow-up issue, but for now we will need at least one follow up PR to address the missed usage above.

**Comment by hussain-t** [comment]
@aaemnnosttv @nfmohit I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/6147) that wraps the `LazyIdeaHubPromptSVG` with the `MediaErrorHandler` component.

![Screenshot 2022-11-15 at 11 49 16 AM](https://user-images.githubusercontent.com/24408261/201859526-171f093f-f85a-4b9a-902b-49ffdbbd9c6e.png)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit just one question.

While the dashboard loads and the error message in the AC appears, there are a lot of console errors. I am assuming this is expected but did not want to assume. Please could you confirm?

![image](https://user-images.githubusercontent.com/73545194/202134413-2861eaf3-28d2-485e-91f6-15e6db3c1a8e.png)

**Verified:**

Using the development build of Site Kit.

- After making the changes in the QAB:
  - The dashboard doesn't crash.
  - The Adsense Connect CTA widget shows an error according to the ACs for the missing graphics.
  - The Components > MediaErrorHandler Storybook story is correct.
  - The IdeaHub CTA widget shows an error according to the AC for the missing graphics. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/202137031-4b1205b4-cbee-41ea-a1a6-e169eb5a9704.png)
![image](https://user-images.githubusercontent.com/73545194/202137059-95e9c38b-4259-47c0-9def-a3da51baa1d2.png)
![image](https://user-images.githubusercontent.com/73545194/202137084-0805377a-c933-4911-a59b-709d7795ea9c.png)

</details>

**Comment by nfmohit** [comment]
@wpdarren This is expected. We are even introducing a new console error for each SVG loading failure.

https://github.com/google/site-kit-wp/blob/585ddc3a885c16550b74d608bce745ec96659cb3/assets/js/components/MediaErrorHandler/index.js#L45

While we want such failures to not crash our application and make it unusable, we would still want relevant console errors to show up to trace such unexpected behaviour.
