### ISSUE TITLE
Oauth is generating API key instead of Client Credentials

### ISSUE THREAD

**Issue by zaadams** [google/site-kit-wp#561]
Hi,
When trying to connect Site Kit to WP, On step 1 for creating new client ID, I follow the link and when I arrive at the page, I click Generate OAuth Credentials. Instead of giving me Client Credentials, It gives me an API Key. The Plug in is not wanting an API Key.

<img width="1920" alt="Capture" src="https://user-images.githubusercontent.com/55561531/65283314-07d84480-daf4-11e9-9270-5973db65385c.PNG">

**Comment by vamshi428** [comment]
I have the same problem help me

**Comment by enricoy** [comment]
Same here.

**Comment by fether-dev** [comment]
same here

**Comment by Sanjoy123456** [comment]
Same here

**Comment by jamesozzie** [comment]
@zaadams @enricoy @Sanjoy123456 @fether-dev @vamshi428 I assume you used the Site Kit link on the https://developers.google.com/web/site-kit webpage to capture your credentials. If so can you download Site Kit from the [dedicated website](https://sitekit.withgoogle.com/) and then install as you would any other WordPress plugin. There is a setup procedure that takes a few clicks from where you can obtain your credentials. 

Please inform me if that works for you, and if not can you please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard and we can look into this further?

**Comment by dannydickson** [comment]
I'm having this issue as well. Thanks for looking into it @jamesozzie. Let us know what you find out.

**Comment by usmanswift** [comment]
> @zaadams @enricoy @Sanjoy123456 @fether-dev @vamshi428 We are looking into this at the moment, please bear with us while we investigate.

I'm facing the same issue....

**Comment by ayohewitt** [comment]
@jamesozzie, We got the same issue as well. Thanks for working on this. I'm looking forward to working with Site Kit for the first.

**Comment by michaelgenova** [comment]
same here

**Comment by thesavvydon** [comment]
i am also having this issue

**Comment by genc74** [comment]
also get the same issue, i get only API key not the OAuth Client ID Conf

**Comment by AdelDima** [comment]
I hope this gets fixed soon.

**Comment by ayohewitt** [comment]
Is there a way to manually config the client ID? I already have a Google Cloud Project created, can I insert my apps credentials into a code snippet template? Maybe this could be a temporary work-around?

**Comment by hfrid** [comment]
Yup same issue here..

**Comment by kama003** [comment]
yes the same problem even I try to get Client Credentials  from API console but it didn't work

**Comment by Invariant-Change** [comment]
@jamesozzie Any fixes yet?

**Comment by usmanswift** [comment]
You can manually set it up by entering details in given code


{ "web": { "client_id": "**Client ID Goes Here**", "project_id": "**Project ID Goes Here**", "auth_url": "https://accounts.google.com/o/auth2/auth", "token_url": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_secret": "**Client Secret Goes Here**", "redirect_uris": [ "https://**yourdomain.com**?oauth2callback=1" ] } }

**Comment by usmanswift** [comment]
> You can manually set it up by entering details in given code
> 
> { "web": { "client_id": "**Client ID Goes Here**", "project_id": "**Project ID Goes Here**", "auth_url": "https://accounts.google.com/o/auth2/auth", "token_url": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_secret": "**Client Secret Goes Here**", "redirect_uris": [ "https://**yourdomain.com**?oauth2callback=1" ] } }

Example is given below

{ "web": { "client_id": "1031765-a0i7j5327d40fvcmmkaug2s81eb.apps.googleusercontent.com", "project_id": "news-angels-156987741", "auth_url": "https://accounts.google.com/o/auth2/auth", "token_url": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_secret": "EHeTYxchhvuufvTlYq", "redirect_uris": [ "https://newsangels.com?oauth2callback=1" ] } }

**Comment by hfrid** [comment]
And do you know the client-ID and client_secret ?

**Comment by usmanswift** [comment]
Here some Images to get Project ID, Client Secret and Client ID etc

![Screenshot 1](https://user-images.githubusercontent.com/55594780/65374930-b624eb00-dca8-11e9-8280-aa2ca428ed49.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/55594780/65374931-b9b87200-dca8-11e9-9bf4-c8443e79c5cf.jpg)
![Screenshot 3](https://user-images.githubusercontent.com/55594780/65374934-bb823580-dca8-11e9-8be8-0416b05fd83e.jpg)
![Screenshot 4](https://user-images.githubusercontent.com/55594780/65374935-be7d2600-dca8-11e9-912d-9bfad1b05c60.jpg)
![Screenshot 5](https://user-images.githubusercontent.com/55594780/65374936-c0df8000-dca8-11e9-89e0-42a82a92877d.jpg)
![Screenshot 6](https://user-images.githubusercontent.com/55594780/65374938-c210ad00-dca8-11e9-867f-ff2a6884f679.jpg)
![Screenshot 7](https://user-images.githubusercontent.com/55594780/65374939-c63cca80-dca8-11e9-84f6-de6e816ed73e.jpg)
![Screenshot 8](https://user-images.githubusercontent.com/55594780/65374941-c6d56100-dca8-11e9-9c00-85684c6f2148.jpg)
![Screenshot 9](https://user-images.githubusercontent.com/55594780/65374946-ca68e800-dca8-11e9-84ea-19dee88325bb.jpg)

**Comment by usmanswift** [comment]
> And do you know the client-ID and client_secret ?

![Screenshot 5](https://user-images.githubusercontent.com/55594780/65374985-74487480-dca9-11e9-979f-ac5726adc84e.jpg)

**Comment by usmanswift** [comment]
> And do you know the client-ID and client_secret ?

Let me know if it works or not.

**Comment by ayohewitt** [comment]
@usmanswift , Thank you so much!! lifesaver. It worked for me. And it is also good to know how to do this manually as well. Thanks again bro!

**Comment by usmanswift** [comment]
> @usmanswift , Thank you so much!! lifesaver. It worked for me. And it is also good to know how to do this manually as well. Thanks again bro!

I'm glad, I was helpful.

**Comment by adampatterson** [comment]
@usmanswift Thanks a lot! I Was struggling for sure.

I found this which might help, One you correctly enter your callback details you can download the JSON config here.
![image](https://user-images.githubusercontent.com/31537/65433397-2717f000-ddda-11e9-8ab1-4d4236aa39e9.png)

**Comment by usmanswift** [comment]
> @usmanswift Thanks a lot! I Was struggling for sure.
> 
> I found this which might help, One you correctly enter your callback details you can download the JSON config here.
> ![image](https://user-images.githubusercontent.com/31537/65433397-2717f000-ddda-11e9-8ab1-4d4236aa39e9.png)

Good Idea, thanks for sharing

**Comment by swissspidy** [comment]
**Good news everyone!**

The issue with the client credentials generation has been resolved and you should all be able to set up Site Kit as expected.

If you still experience issues, please let us know.
