### ISSUE TITLE
Open text survey question entry field should show more text / be multi-line

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#5612]
## Bug Description

When serving user surveys with a an open ended question (the `SurveyQuestionOpenText` element), the text input area is a single line input field that shows a small number of characters - allowing for maybe five to ten words. This makes it very difficult to see what you have typed and enter more than a small amount of text. 

Instead this field should probably be a multi-line `textarea` which would allow for a couple of lines of text entry (and can expand).

## Steps to reproduce

1. Trigger a survey with an open text question (for example, the new design survey)
2. Review the entry field, try typing a sentence into the text area

## Screenshots

![image](https://user-images.githubusercontent.com/2676022/181063062-5e757c2f-3c8c-4c7b-9cc1-19f8138eebf6.png)
(question blurred out)

## Additional Context

* I experimented with this in https://github.com/google/site-kit-wp/pull/5597/files 
* The change needs testing to ensure the layout accommodates the larger field area

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The open text survey question entry text field should be a multiline text area.
* Its character limit should be raised to 200.

## Implementation Brief

* Complete #5597 based on the ACs (character limit increase still has to be added).

### Test Coverage

* No changes
* Update VRTs if needed

## QA Brief

* TBD steps to trigger a survey manually
* This can also be checked in Storybook `?path=/story/components-surveys--survey-question-open-text-story`

## Changelog entry

* Update the open text survey question entry field to allow multiline text input.

**Comment by aaemnnosttv** [comment]
@adamsilverstein we currently have a 100 character limit on the input of this field which was part of the original spec for this question type (see https://github.com/google/site-kit-wp/issues/3762). Is there a particular reason why we need this? If not should we remove it or just increase it to something more generous?

**Comment by adamsilverstein** [comment]
> we currently have a 100 character limit on the input of this field which was part of the original spec for this question type (see #3762).

Ah, that is good to know, I didn't realize we had that limit set already. I'm not sure why that limit was set so low originally, maybe because our initial questions had short answers.

> Is there a particular reason why we need this? If not should we remove it or just increase it to something more generous?

I can't think of any reason from the back end although I think it makes sense to have some limit here as a sanity check and to prevent abuse. 100 could be slim depending on the type of question we ask though, something open ended would be hard to answer in that much space. so maybe we can increase this a bit to 200 or 400? This sentence alone is ~140: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

**Comment by adamsilverstein** [comment]
> we currently have a 100 character limit on the input of this field which was part of the original spec for this question type (see #3762).

cc: @felixarntz Any reason we should keep this limit so small you can think of Felix?

**Comment by felixarntz** [comment]
@adamsilverstein @aaemnnosttv Not sure where that came from, maybe let's raise it to 200 then.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- I tried to use the code we used when initially testing open text survey field #3762 but unfortunately, it didn't work. So, I could only QA this based on [Storybook here](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys--survey-question-open-text-story).

- Confirmed that I was able to add multiple lines of text and no styling issues. 

![image](https://user-images.githubusercontent.com/73545194/181407098-ae9e4b0e-d477-4c5d-80ba-4eeafdeb4718.png)
