### ISSUE TITLE
WP Dashboard - Error notifications are not properly showing on WP dashboard widget.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#5615]
## Bug Description

Site kit errors on WP dashboard appears without space and alignment. 

## Steps to reproduce

1. Set up SK without Analytics
2. Sign in with a different admin and connect Analytics
3. Sign in with the first admin again
4. See errors notifications under Site kit widget on WP dashboard.

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/181245408-2ab977d9-4656-4bd2-b36e-788b7785a1a7.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* Only unique errors should be displayed per module on the WP dashboard. For e.g we should not have 2 insufficient permissions errors displayed for the Analytics module.
* There should be margins/spacing between the error components such that they do not touch each other.

## Implementation Brief

* Each `WidgetReportError` should generate an ID internally using [`useInstanceId`](https://github.com/google/site-kit-wp/blob/76d59e9796858f895620fc325c16247bf4166bbb/assets/js/components/surveys/SurveyQuestionMultiSelect.js#L51-L54).
* When a `WidgetReportError` receives an `error` (eg. the `moduleSlug` + `error` props are not `null`/`undefined`), it should dispatch a `core/ui` `set` action that sets {`WidgetReportError-${moduleSlug}-${error.name}`: instanceID}. It's possible multiple components will dispatch this at the same time, but that's fine.
  * Each `WidgetReportError` should select for the same `WidgetReportError-${moduleSlug}-${error.name}` value in the `core/ui` store. If the instanceID returned matches the one for this `WidgetReportError`, output the error.
  * If not, output `null`
  * Optionally: on unmount, we can clear the `core/ui` store of the value of the widget that is rendering, but it probably isn't required.
* Change `margin-top` to the `googlesitekit-cta--error class` on the main WP dashboard's widget section for Site Kit to address the issue with spacing if more than one error appears 

This way we don't need to replace error rendering logic in individual components, and this behaviour would be transparent to whatever calls `<WidgetReportError />` in the future.

### Test Coverage

* Add test cases for the `WidgetReportError` component, ensuring multiple `WidgetReportError` for the same slug + error only render one error.

## QA Brief

* Follow the steps to reproduce. 
* Only error per module should be displayed. 

## Changelog entry

* De-duplicate and fix the layout for errors in the WP Dashboard widget.

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by sashadoes** [comment]
Hi @mohitwp, I struggle to reproduce this issue, I think it was already fixed. Could you please confirm?
<img width="1000" alt="Screenshot 2023-02-17 at 11 05 05" src="https://user-images.githubusercontent.com/16494321/219632032-735c4886-7355-4a84-a942-1eb724ac1a03.png">

**Comment by mohitwp** [comment]
@sashadoes You are on Site Kit Dashboard. Check SK widgets on WP dashboard.

**Comment by tofumatt** [comment]
The IB here doesn't address the possibility of two distinct errors appearing and overlapping—but a straightforward solution would be to add `margin-top` to the `googlesitekit-cta--error` class on the main WP dashboard's widget section for Site Kit. That means they don't touch the header's line either:

<img width="623" alt="CleanShot 2023-02-21 at 15 05 55" src="https://user-images.githubusercontent.com/90871/220381978-d3f6f8c5-b903-4739-9c3c-90f495ef5eb9.png">

-----

In terms of creating a new wrapper component and evaluating the children—I'm not sure that's needed. The existing `WidgetReportError` gets both the `moduleSlug` and `error` values as props. It also gets the `widgetSlug` prop. It seems like we could have `WidgetReportError` generate an ID internally using [`useInstanceId`](https://github.com/google/site-kit-wp/blob/76d59e9796858f895620fc325c16247bf4166bbb/assets/js/components/surveys/SurveyQuestionMultiSelect.js#L51-L54) for each instance, and have them save in the `core/ui` store which one is displaying the error for a particular slug + error combo, and then have all other `WidgetReportError` errors check if their ID is rendering a particular error.

That way we don't need to replace error rendering logic in individual components, and this behaviour would be transparent to whatever calls `<WidgetReportError />` in the future.

Does that make sense?

**Comment by sashadoes** [comment]
Thanks, @tofumatt for the review and feedback. I made an update.

**Comment by tofumatt** [comment]
Hi @sashadoes, the IB proposed isn't _quite_ what I meant, and would have the issue that if multiple `error` + `slug` widgets rendered at the same time they would both see no `error` + `slug` combo…

The `useInstanceId` should be the instance ID for each `WidgetReportError` instance… the first one to "claim" that error can register itself in the store and that way it'll be the only component to render the output. Even if another `WidgetReportError` overwrites that claim, then the other widgets won't render anything so it'll never "double-render" like it does now.

We want to check that the "registered" instanceID in the store matches the instanceID for a particular `WidgetReportError`.

I'll modify the IB here to reflect that 🙂

**Comment by aaemnnosttv** [comment]
@techanvil I see you added this to 1.113.0 but it doesn't appear to be merged yet and it's too late for this to be added to the current release. You probably meant to set it to the next one but I'll unassign it for now as these should be set just before merging or on issues where it's known earlier that a particular issue needs to land in a specific release.

**Comment by techanvil** [comment]
> @techanvil I see you added this to 1.113.0 but it doesn't appear to be merged yet and it's too late for this to be added to the current release. You probably meant to set it to the next one but I'll unassign it for now as these should be set just before merging or on issues where it's known earlier that a particular issue needs to land in a specific release.

Thanks @aaemnnosttv - this was indeed a bit preemptive, and it should be 1.114.0 as you've pointed out. I must have been on autopilot! Thanks for the catch.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

WAs able to recreate the issue:

- Only unique errors are  displayed per module on the WP dashboard. 
- There are margins/spacing between the error components such that they do not touch each other.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/174e1af8-e46d-4ed7-aac1-fc855c84c822)
![image](https://github.com/google/site-kit-wp/assets/73545194/f25aa35e-dea3-47a3-88f7-9776f0541ec4)
![image](https://github.com/google/site-kit-wp/assets/73545194/37af5e68-d078-462b-ac9c-677ecbbf6c76)



</details>
