### ISSUE TITLE
Extract Google product names from translatable strings for consistency

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5617]
## Feature Description

Currently, we don't have strict rules regarding product names in translatable strings thus our translations contain product names which may be translated by the community. This become more important with the launch of the Thank with Google integration. People that aren't familiar with the Thank with Google product may not understand what this mean and translate it into their local languages.

We need to update our translation strings to exclude product names from it and use placeholders instead that will be replaced with actual product names in the runtime.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
@felixarntz or @aaemnnosttv could you, please, help to define AC? Not sure which approach is the right for this, seems like the `sprintf` one is the best, what do you think?

**Comment by tofumatt** [comment]
This can be closed as #7650 is more/less this issue, and has more discussion/context.
