### ISSUE TITLE
Add selector to retrieve meta-data for a given error.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5618]
## Feature Description

_This has been identified as a requirement in order to get https://github.com/google/site-kit-wp/issues/5494 working - for more info see the related comment thread in the issue, although the proposed solution has changed a bit since then._

In order to be able to show a retry button in the `ErrorNotice` component that allows a selector error to be retried, we need a new selector that retrieves the meta-data for an error that allows [`selectorData`](https://github.com/google/site-kit-wp/blob/cc86db8f12665a5badf9a5bbbe48d20cce087d8b/assets/js/googlesitekit/data/create-error-store.js#L194-L198) to be derived for a given error object which relates to a selector.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- We want the ability to look up meta-data for a given error object, the meta-data specifically being the `baseName` and `args`. In order to facilitate this we need to cache the `args` for an error (at present only a non-reversible hash of the args is being stored, as part of the error key).
- `args` should be stored separately in the store. These can also be keyed by the error key. Update the error store `initialState` to be as follows, and ensure `errorArgs` is updated at the same time `errors` is.
```js
const initialState = {
  errors: {},
  errorArgs: {}, /* Add this property */
  error: undefined,
};
```

- Create a new error store selector, `getMetaDataForError` which takes an `error` object as its argument.
  - Lookup the error key for the object by iterating over the `errors` state property - `errors` is a map of error key to error object.
  - The error keys have the form `${ baseName }::${ argsHash }`.
  - Lookup the `args` object in the new `errorArgs` state property.
  - Return the selector data as `{ baseName, args }`. Return a memoized object instance avoid potential rerendering issues.
  - Otherwise return `null`.

- `getMetaDataForError` can be integrated via https://github.com/google/site-kit-wp/issues/5494 which will need to call it in `StoreErrorNotices` - possibly calling it indirectly, e.g. another selector, `getSelectorDataForError` could be introduced which also checks for the existence of a selector corresponding to `baseName` on the store.

- Add a followup issue to replace usage of `getErrorForSelector` with a combination of `getError` and `getMetaDataForError` (or `getSelectorDataForError`), and remove `getErrorForSelector` entirely.

_Note: Added the https://github.com/google/site-kit-wp/issues/5858 followup issue for `getErrorForSelector` removal._

## Implementation Brief

- Implement as per the AC.

### Test Coverage

* Add test coverage for the new `getMetaDataForError` selector.

## QA Brief

* N/A. Although a small addition was made to the error store reducer, the thorough suite of unit tests provides assurance that the existing behaviour still works as expected. Beyond that, the addition of the `getMetaDataForError` selector is not user facing, and the Code Review process is sufficient here.

## Changelog entry

* Add selector to retrieve meta-data for a given error.

**Comment by techanvil** [comment]
Hey @aaemnnosttv, just assigned this to you for a review of the AC...

**Comment by eclarke1** [comment]
@aaemnnosttv just a polite reminder on this one please as it's for Sprint 82, plus it's blocking an issue with @makiost that's already complete and waiting to be merged

**Comment by aaemnnosttv** [comment]
@eclarke1 thanks for the reminder – I haven't forgotten, just been giving it some thought as I think we might want to take a different approach.

**Comment by techanvil** [comment]
Hi @aaemnnosttv, I have updated the AC. I did have another think about the idea of using a `Map` with the error as the key, and in fact fleshed out the potential AC for it. I do like the idea, but just find it a bit hard to fully get behind the thought of adding this non-serializable component to the error store. What if we want to snapshot the error store later? I suppose we could always rewrite it then to remove the `Map`...

To be honest, I am pretty on the fence here and would really have no objection to switching to the `Map` version if you prefer this route...

<details>
<summary>
For the sake of argument here is the AC for a `Map` version.
</summary>

## Acceptance criteria

- We want the ability to look up selector data for a given error object. In order to facilitate this we'll use a `Map` instance, as `Map` allows keying by objects.
- In `createErrorStore`, create a new `Map` instance. Create it at the same level as `initialState` so it's closed over in the same way.
- For each action type, create a corresponding `control` that updates the `Map`.
  - `RECEIVE_ERROR`: Store the `baseName` and `args`, keyed by the `error` object. Store them as `{ name, args }` to avoid potentially having to memoize a renamed version later.
  - `CLEAR_ERROR` / `CLEAR_ERRORS`: Lookup the error object(s) and delete their `Map` entries.

- Create a new error store selector, `getSelectorDataForError` which takes an `error` object as its argument.
  - Lookup the selector data, i.e. `name` and `args`, for the `error` in the `Map`.
  - Use `createRegistrySelector` and check for the existence of a selector by that name on the store.
  - If the selector does exist, return the selector data. Return the object instance retrieved from the `Map` to ensure the same object is returned each time and avoid potential rerendering issues.
  - Otherwise return `null` or `undefined`.

- `getSelectorDataForError` can be integrated via https://github.com/google/site-kit-wp/issues/5494 which will need to call it in `ErrorNotice`.

- Add a followup issue to replace usage of `getErrorForSelector` with `getError` and then call `getSelectorDataForError` where we need the selector data in `ReportError`. `getErrorForSelector` can be removed entirely.

</detail>

**Comment by aaemnnosttv** [comment]
> I have updated the AC. I did have another think about the idea of using a `Map` with the error as the key, and in fact fleshed out the potential AC for it.

Thanks @techanvil! It certainly helps to see things side-by-side when decisions get tricky/nuanced so I think this qualifies 😄 

> I do like the idea, but just find it a bit hard to fully get behind the thought of adding this non-serializable component to the error store. What if we want to snapshot the error store later? I suppose we could always rewrite it then to remove the `Map`...

I hear you. Regarding concerns about serializability: `Error` instances aren't serializable either, so as long as we're aiming for compatibility with these then that wouldn't be possible in either case.

It's also worth noting that [`@wordpress/data` already uses `Map`s in the core "metadata" stores](https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/namespace-store/metadata/reducer.js#L30-L36) that are bundled into every store to track the invocation of selectors with resolvers. This is already not included in our store snapshotting because that state is – while part of the same redux state tree – [isolated at a higher level than ours](https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/namespace-store/index.js#L136-L139) ("private" if you will). So resolver state is not preserved as part of the store snapshotting either.

With that said, I think the tradeoff with the `Map` is losing the ability to lookup an error's arguments after restoring a state snapshot which seems like something we should avoid.

How about we keep the ACs you have, and add a selector for getting the arguments with a given `error`? We should be able to reverse-lookup the error's key in the state and its args by the same key (as you have defined). Maybe that even makes some of the other changes unnecessary as we would still be able to look up the args by error alone. What do you think?

**Comment by techanvil** [comment]
Hi @aaemnnosttv, thanks for the comment/suggestion - I like the idea of doing a reverse lookup and have updated the AC, it's ended up as a bit of a mix between the two proposals.

> I hear you. Regarding concerns about serializability: `Error` instances aren't serializable either, so as long as we're aiming for compatibility with these then that wouldn't be possible in either case.

Yup, this aspect did occur to me too... My thoughts being along the lines of, the `Error` object case is presumed to be the outlying, not-so-expected scenario, and we should be able to address it by updating the calls to `receiveError` within a `catch` block, or similar. It's definitely another angle we'd need to tackle if we do want to snapshot the store or otherwise ensure full serializability.

> It's also worth noting that [`@wordpress/data` already uses `Map`s in the core "metadata" stores](https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/namespace-store/metadata/reducer.js#L30-L36) that are bundled into every store to track the invocation of selectors with resolvers. This is already not included in our store snapshotting because that state is – while part of the same redux state tree – [isolated at a higher level than ours](https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/namespace-store/index.js#L136-L139) ("private" if you will). So resolver state is not preserved as part of the store snapshotting either.

Thanks, I had not spotted that, useful to know! Interesting to see that the `EquivalentKeyMap` uses deep-equality rather than strict equivalence to determine a match for the key. This suggests it would lend itself slightly more easily to serializing - although of course, only if the keys are themselves properly serializable, e.g. not `Error` objects.

> With that said, I think the tradeoff with the `Map` is losing the ability to lookup an error's arguments after restoring a state snapshot which seems like something we should avoid.
> 
> How about we keep the ACs you have, and add a selector for getting the arguments with a given `error`? We should be able to reverse-lookup the error's key in the state and its args by the same key (as you have defined). Maybe that even makes some of the other changes unnecessary as we would still be able to look up the args by error alone. What do you think?

As mentioned at the top - sounds good to me, and I have updated the AC accordingly (although ending up with a bit of a mix).

If you are happy with it, we could probably add an IB which just says "implement as per the AC" as the AC is so implementation-detailed, what do you think?

**Comment by aaemnnosttv** [comment]
@techanvil This is looking great, just one more thought and then I think we can move forward with this as an AC+IB as you suggested.

> * Create a new error store selector, `getSelectorDataForError` which takes an `error` object as its argument.

I think we can simplify this to `getArgsForError` as the storage will be tied to `receiveError`. Given the direction here, I don't think we need to make this specific to selectors even if that's the only way it will likely be used.

Before the whole addition of `selectorData`, `getErrorForSelector` and `getErrorForAction` were purely semantic differences but the same thing under the hood.

I would suggest we keep the main lookup selector here agnostic to action/selector (similar to `getError` or `getErrors`) and if we later find that more scoping is needed, we can add type-specific selectors that do the cross-referencing with registered action/selector names.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv. I have updated the AC to remove the selector-specific aspects. However, and sorry for yet more back and forth here, I have proposed the name `getMetaDataForError` rather than `getArgsForError` as we also need to return the `baseName`, as well as `args`. I've also added an IB which simply points to the AC.

**Comment by aaemnnosttv** [comment]
@techanvil ah of course, I forgot about the `baseName` 👍  That all sounds good, we just need an estimate here (as well as the test coverage section) and then this should be good to go!

**Comment by techanvil** [comment]
Thanks @aaemnnosttv - have updated accordingly and moved to IBR.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Agreed with QAB that it's not necessary here. Moving to Approval 👍
