### ISSUE TITLE
Minor UI improvement on Idea Hub connect service screen

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5626]
## Bug Description

Minor UI issue on the service connection screen for Idea Hub.

This text is too big in my opinion. 

`I agree that Idea Hub will track my usage of the feature (e.g. creating a draft; saving/dismissing ideas) in order to provide better idea suggestions`. 

This font is 16px.  I feel this should be 14px.  

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/d867510f-8792-4759-a6d7-3bd7b0b2f221)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this one in favor of #6235
