### ISSUE TITLE
Address large file sizes of Thank with Google SVGs

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5627]
## Feature Description

These Thank with Google SVGs are a bit on the large side and should be reduced in size.

- `assets/svg/graphics/twg-dynamic-high.svg`: **4.7 MB**

![twg-dynamic-high](https://user-images.githubusercontent.com/18395600/184192174-a8348a92-e798-439c-aead-a01fe5a23afb.svg)

- `assets/svg/graphics/twg-dynamic-low.svg`: **1.1 MB**

![twg-dynamic-low](https://user-images.githubusercontent.com/18395600/184192190-ab2d668c-671e-4f9a-a293-c6715e0d4977.svg)

- `assets/svg/graphics/thank-with-google-setup.svg` **1.2 MB**

![thank-with-google-setup](https://user-images.githubusercontent.com/18395600/184191948-38438d81-6710-4776-95fd-f6e2d30d5343.svg)

We are already lazy loading these images which provides some mitigation to their size but they should be optimised; as @eugene-manuilov alludes to [below](https://github.com/google/site-kit-wp/issues/5627#issuecomment-1199847486), using JPEG rather than PNG (they appear to be PNG as opposed to GIF) for the embedded images is one tangible avenue for optimisation.

By way of illustration here's the current output of WebPack Bundle Analyzer (run `npm run test:analyze` to generate):

![image](https://user-images.githubusercontent.com/18395600/182430441-b84c75fd-edfe-43fc-813d-9930708a6e51.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Optimized versions of the images have been provided by [Seba](https://10up.slack.com/archives/C01CA828ZPZ/p1660551779449579?thread_ts=1660238147.601399&cid=C01CA828ZPZ). These should be incorporated into the plugin instead of the placeholders.

## Implementation Brief

- Finish and merge #5688

### Test Coverage

* 

## QA Brief

- Start the Thank with Google setup and verify the updated image appears on the Setup Publication view:
![image](https://user-images.githubusercontent.com/18395600/184652092-85bea3fc-bc1b-48c7-8a34-9e31f6abcffb.png)

- Enter the Customize view and verify the updated images appear for the Prominence options:
![image](https://user-images.githubusercontent.com/18395600/184651824-d8fad5de-e60c-49ae-afae-ae54460720e2.png)

### `QA:Eng`:

Perform a sanity check on the resulting zip size.

- Generate the plugin zipfile with `npm run build:production && npm run zip`.
- Verify the generated zip has a size in the expected range of around 3MB.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@techanvil this is a known issue and we already have a workaround for it in the `develop` branch that loads that big svg lazily: https://github.com/google/site-kit-wp/blob/918a52cdbec25111561063b77008860647b2996d/assets/js/modules/thank-with-google/components/setup/SetupPublicationScreen.js#L36-L38

It means that the svg image is not bundled into the twg module bundle and not affects their size. In the future, we need to ask the designer to manually resize and optimise images used in the svg file to have much smaller size and proper format (jpeg instead of gif for the last image in the svg file).

**Comment by techanvil** [comment]
Thanks @eugene-manuilov! I should have spotted that. I've updated the issue based on what `develop` looks like now...

**Comment by eclarke1** [comment]
@felixarntz @techanvil just moved this over to the AC column and added a P0 label as my understanding is this may not block bug bash, but is something we would like to address for launch. If you agree with this, please could we add ACs?

**Comment by felixarntz** [comment]
Update: While we will follow up separately on optimizing these images, they already have a negative impact right now even with TwG unreleased, as they blow up the plugin ZIP file size. I have opened #5679 as a high priority issue to just temporarily remove them so that this is fixed for next Monday's release.

We will need to follow up internally to get optimized versions of these SVGs, and after that we can move the issue here forward.

**Comment by techanvil** [comment]
Regarding the optimized versions, I have reached out to Seba and Sigal on the UX Slack channel as these images appear to have been extracted from the TwG Figma file, so hopefully one of them will be in a position to provide optimized versions.

**Comment by techanvil** [comment]
@felixarntz @aaemnnosttv Seba has provided the optimized versions of these, I've created a draft PR with them included in it and updated the AC.

**Comment by techanvil** [comment]
Thanks @felixarntz!

**Comment by aaemnnosttv** [comment]
## QA:Eng ✅ 

- Inspected size of production zip: 3.1MB (see https://github.com/google/site-kit-wp/actions/runs/2861200864)
- <details><summary>JS file sizes for production build</summary>

	```
	7.9K 31-4865412fd06ff3985d7e.js
	6.1K 32-a5489b103a87b8ad5f7e.js
	9.9K 33-2696ba934fb83d598a0d.js
	100K 34-68cd65ce7655f3496d73.js
	 27K 35-69d9be293f6bb240fc0c.js
	128K 36-d4b9f44659d1251de63e.js
	 44K 37-901cb420582493a5606d.js
	9.4K 38-2e58c3b7329f6d8a9d79.js
	1.6K analytics-advanced-tracking-10a628cd2acd13ac224f.js
	102K googlesitekit-activation-93293df197dc6bad83c1.js
	144K googlesitekit-adminbar-540385041e8744dd9ffd.js
	 31K googlesitekit-api-0e004237b49dd3341b7e.js
	2.1K googlesitekit-base-c54222a6c4ef19e42a7b.js
	241K googlesitekit-dashboard-71367977b44039f68d25.js
	209K googlesitekit-dashboard-details-9ad49567cae711372ac7.js
	248K googlesitekit-dashboard-splash-876495a9fa2cce1297d7.js
	5.6K googlesitekit-data-500d1e4ef29b545a156e.js
	 31K googlesitekit-datastore-forms-dce66c3ba6127e0eb765.js
	6.1K googlesitekit-datastore-location-2f8d4ae428816622fd1a.js
	 57K googlesitekit-datastore-site-58d27d0126086de9dd6a.js
	 31K googlesitekit-datastore-ui-ae496746d21bf8e564b6.js
	119K googlesitekit-datastore-user-e61885080aaf88e09ee1.js
	 11K googlesitekit-i18n-e29c32171c9d96a19747.js
	129K googlesitekit-idea-hub-notice-6c50bd89bb45893bc1ca.js
	 97K googlesitekit-idea-hub-post-list-33fa970fca5c838d5bd4.js
	292K googlesitekit-modules-adsense-06395e853c4357793070.js
	287K googlesitekit-modules-analytics-19f666e1f858f93ed2e8.js
	 79K googlesitekit-modules-analytics-4-17133da76342e0c3ef81.js
	 78K googlesitekit-modules-e195242522d93945b874.js
	107K googlesitekit-modules-idea-hub-54a57b945838d293f49e.js
	 73K googlesitekit-modules-optimize-a7e97bdad0fd997feb51.js
	 66K googlesitekit-modules-pagespeed-insights-91d262c03f51be4fdb0c.js
	142K googlesitekit-modules-search-console-718abcdb646f9c128876.js
	122K googlesitekit-modules-tagmanager-b4edf0339bc5fc17f201.js
	 95K googlesitekit-modules-thank-with-google-962c44330991a377e319.js
	592B googlesitekit-polyfills-38b7d81924781dc42d19.js
	183K googlesitekit-settings-b318f9ef47a2d5719b09.js
	162K googlesitekit-user-input-e1395b3c141450a000f6.js
	1.1M googlesitekit-vendor-522a23e1926a0d413973.js
	 73K googlesitekit-widgets-f85da7edad3839b67645.js
	244K googlesitekit-wp-dashboard-131bbaa4e640e6414130.js
	2.8K runtime-4953542745b7c57f6dc6.js
	```

	</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified 👍 

- Optimized versions of the images have been provided by [Seba](https://10up.slack.com/archives/C01CA828ZPZ/p1660551779449579?thread_ts=1660238147.601399&cid=C01CA828ZPZ).
- Setup Publication view showing updated image.
- Verified Customize view. The updated images appearing for the Prominence options.
