### ISSUE TITLE
Something went wrong - The project cannot be created because you have exceeded your allotted project quota.

### ISSUE THREAD

**Issue by usmanswift** [google/site-kit-wp#563]
![Screenshot (242)](https://user-images.githubusercontent.com/55594780/65340795-739bd980-dbe8-11e9-8da6-af29daf1960f.png)

When I click on developers.google.com/web/sitekit in wp dashboard, it returns this error as shown in the screenshot.

**Comment by jamesozzie** [comment]
@usmanswift Can you [delete](https://i.imgur.com/EoA1edo.png) the Site Kit created project from [Google Cloud Platform](https://console.cloud.google.com/projectselector2/home) before attempting to setup Site Kit again?

**Comment by usmanswift** [comment]
> @usmanswift Can you [delete](https://i.imgur.com/EoA1edo.png) the Site Kit created project from [Google Cloud Platform](https://console.cloud.google.com/projectselector2/home) before attempting to setup Site Kit again?

It's not listed in Google Cloud Platform. The one I created few days ago (NewsAngels) is present there but not "News Angels" which Site Kit shows during authentication.

**Comment by usmanswift** [comment]
> @usmanswift Can you [delete](https://i.imgur.com/EoA1edo.png) the Site Kit created project from [Google Cloud Platform](https://console.cloud.google.com/projectselector2/home) before attempting to setup Site Kit again?

I think, my account project creating limit is reached. I have deleted some projects but they have gone in 30 days duration of deletion. Even doing that, I am still not able to create new projects manually. Can you permanently delete projects, which are requested to be deleted?

**Comment by usmanswift** [comment]
> @usmanswift Can you [delete](https://i.imgur.com/EoA1edo.png) the Site Kit created project from [Google Cloud Platform](https://console.cloud.google.com/projectselector2/home) before attempting to setup Site Kit again?

Project issue is now fixed but, it just gave me an api key, which Site Kit does not support. I want something else not just the pasted....

**Comment by usmanswift** [comment]
> > @usmanswift Can you [delete](https://i.imgur.com/EoA1edo.png) the Site Kit created project from [Google Cloud Platform](https://console.cloud.google.com/projectselector2/home) before attempting to setup Site Kit again?
> 
> Project issue is now fixed but, it just gave me an api key, which Site Kit does not support. I want something else not just the pasted....

It says "Unable to parse client configuration values." when I paste the key...

**Comment by jamesozzie** [comment]
@usmanswift There was an issue ([#561](https://github.com/google/site-kit-wp/issues/561)) which was resolved today which could have been impacting your own installation and setup. Can you check and see if you are now able to continue with setup?

**Comment by usmanswift** [comment]
> @usmanswift There was an issue ([#561](https://github.com/google/site-kit-wp/issues/561)) which was resolved today which could have been impacting your own installation and setup. Can you check and see if you are now able to continue with setup?

Ya, now its generating credentials now, but when I try to connect analytics or speedinsights to Site kit, it gives an error that this app is not safe...

![Screenshot (255)](https://user-images.githubusercontent.com/55594780/65711853-37b4b880-e0af-11e9-8e11-b2b3a9d91e6e.png)

**Comment by jamesozzie** [comment]
@usmanswift You can click on "Advanced" and then "go to...." to proceed with setup. The app is a new project created on your own Google Cloud Platform, and this message is part of the usual authorization flow. You can find out more on how it works [here](https://support.google.com/cloud/answer/7454865?hl=en).

**Comment by jamesozzie** [comment]
@usmanswift Were you able to successfully setup Site Kit in the end?

**Comment by usmanswift** [comment]
> @usmanswift Were you able to successfully setup Site Kit in the end?

Yes, I was, I knew about "advanced", I just wanted to let you know about this issue...
