### ISSUE TITLE
For the "See full details in <modulename>", include a deep link to ensure users land on the service page with the connected Google account

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5642]
## Bug Description

Within the module specific settings screens, there are links to “See full details in <modulename>”. These links, direct users to a particular page at service level. When clicking on these links, the links don't include any Google account or email paramater. This means if a user is logged into their browser with a different Google account to that used to connect Site Kit, they may be unaware they have to switch Google accounts after landing on a service page (ie. analytics.google.com) in order to view stats on the Site Kit connected property. 

To improve this, considering adding a deep link which includes passing the connected Google account, or rename the "See full details in <modulename>" to simply a link to the service, by removing the "See full details in" text. 

<kbd> ![image](https://user-images.githubusercontent.com/41326532/182430091-4af2f08d-3059-4d2b-bc1e-6d98d08ec475.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "See full details in {module-name}" link in the active module settings footer which links to the module's homepage should be updated to use an "accountchooser" version of the same URL to ensure the user is always sent to the destination in the context of their signed in Google account

## Implementation Brief

- In `assets/js/components/settings/SettingsActiveModule/Footer.js`:
    - Using the `getAccountChooserURL` selector from the `core/user` store, passing in the `homepage` property from the `module` variable.
	- Locate the `See full details in` link and update its `href` prop to use the value derived from the above selector.

### Test Coverage

- No tests need to be added/updated.
- Update VRT references if required.

## QA Brief

* Check the "Details" link in the footer section of any module in the settings
* The link should contain account email

## Changelog entry

* Add user account email to "Details" link to improve deep-link user experience.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked the "Details" link in the footer section of any module in the settings and the link contains the account email. 
- Set up every module and made sure that the full details link included the URL AND redirected me to the correct page for each module with my connected Google account. 

https://user-images.githubusercontent.com/73545194/196161578-f50caf48-424a-4ee2-b018-ea2993f5180b.mp4
