### ISSUE TITLE
Change the wording when an existing Analytics property was found via GTM, during Analytics set up

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5648]
## Bug Description

If a user tried to connect the Analytics module, but there is already an Analytics property firing on their site via Google Tag Manager, the Analytics module will state the following:
**An existing Google Tag Manager property was found on your site with the ID UA-229****...**

This is incorrect, as it's an Analytics property that was found, not a Google Tag Manager property. The Analytics property was added via Tag Manager, however, it's not a Tag manager property being referenced. 

To improve this notice consider the below change or similar, to the wording of this. 

```diff
- An existing Google Tag Manager property was found on your site with the ID UA-229653484-1.
+ An existing Google Analytics property with the ID UA-229653484-1 was found on your site, added by Google Tag Manager.
```

Any wording changes, similar to the above suggestion, can be made to the [ExistingGTMPropertyNotice.js file](https://github.com/google/site-kit-wp/blob/8b62084b7d3ddfd3440d69647ddae9752de8be68/assets/js/modules/analytics/components/common/ExistingGTMPropertyNotice.js)

## Steps to reproduce

1. Set up Site Kit without including Analytics
2. Connect the GTM module, with a container that has an existing Universal Type Analytics property tag added
3. Connect the Analytics module within Site Kit

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/182653040-a90a73e1-3dd9-43c2-9a15-795c5c8db883.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The wording of the notice shown when an Analytics property is detected in the configured GTM container should be updated as follows:  
> An existing Google Analytics property with the ID {property ID} was found on your site, added by Google Tag Manager.

## Implementation Brief

In `assets/js/modules/analytics/components/common/ExistingGTMPropertyNotice.js`:
* Locate the two calls to the `sprintf`-function using the old wording 
* Replace the copy with the one given in the AC, exchanging `{property ID}` with a sprintf string placeholder (`%s`)

### Test Coverage

* No new tests are needed for this issue.

## QA Brief

* Follow AC. The result should be next:

<img width="1230" alt="Screenshot 2022-09-14 at 13 03 57" src="https://user-images.githubusercontent.com/16494321/190217770-acd9f82d-9c1d-4c6e-96e9-64bd3f2661b1.png">

Also check the setup for the case where the Property ID selected in the dropdown matches the Property ID found in the GTM container. The text should then be ->  "An existing Google Analytics property with the ID UA-229****...**  was found on your site, added by Google Tag Manager. Since it refers to the same property selected here, Site Kit will not place its own tag and rely on the existing one. If later on you decide to remove this property, Site Kit can place a new tag for you.". For example:

![image](https://user-images.githubusercontent.com/18395600/191464996-78ce55cd-51ed-4719-b8c3-bb858d12e871.png)

## Changelog entry

* In the Analytics set up, change the wording when an existing Analytics property was found via GTM.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@sashadoes I verified this and found that wording in case of Scenario 1 is changed successfully. But there is another scenario mentioned under QAB. Can you please provide more details, how can I generate this case ? I tried but not getting the desire changes.

cc @wpdarren 

<details>

Case 1:

![image](https://user-images.githubusercontent.com/94359491/191205568-7c4fa908-926e-4111-8ed5-6a1d57dda0c1.png)

</details>

**Comment by techanvil** [comment]
Hi @mohitwp, the 2nd scenario refers to the case where the Property ID selected in the Property dropdown matches the Property ID found in the GTM container. I have tweaked the QAB and added a screenshot for illustration. Please let me know if you need any further info on this one.

**Comment by mohitwp** [comment]
Thank you @techanvil 

QA Update ✅ 

- Verified for both the scenarios on dev environment.
- In both cases, changes implemented as per AC.

<details>

Case 1-

![image](https://user-images.githubusercontent.com/94359491/191205568-7c4fa908-926e-4111-8ed5-6a1d57dda0c1.png)


Case 2-

![image](https://user-images.githubusercontent.com/94359491/191472962-9cb4794f-de21-4ff6-ae19-021b51859db1.png)

</details>
