### ISSUE TITLE
PageSpeed Score Differences

### ISSUE THREAD

**Issue by reinhardjung** [google/site-kit-wp#565]
## Steps to reproduce

1. Click on 'Dashboard'
3. Scroll down to 'SPEED'
4. There is only (87) but on the Live "PageSpeed Insights"-Site there is (95)

## Additional Context

 - PHP Version: 7.3.4-1+ubuntu16.04.1+deb.sury.org+3
 - OS: [Mojave 10.14.6]
 - Browser [chrome]
 - Plugin Version [1.0.0-beta.1.0.6]
 - Device: [iMac]

![Desktop 87](https://user-images.githubusercontent.com/298616/65383672-f0c66c00-dd18-11e9-8f64-83ae58ef9a51.png)
![Desktop 95](https://user-images.githubusercontent.com/298616/65383675-f754e380-dd18-11e9-8d23-013933307c2d.png)

**Comment by swissspidy** [comment]
Hi there!

It is normal to not get the same score every time you run the analysis.

Variability in performance measurement is introduced via a number of channels with different levels of impact. Several common sources of metric variability are local network availability, client hardware availability, and client resource contention.

You can learn more about how PageSpeed Insights works [here](https://developers.google.com/speed/docs/insights/v5/about).
