### ISSUE TITLE
Install the SwG client API library

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5650]
## Feature Description

Thank with Google will rely on the `subscribewithgoogle` API which will not be have its client library available via the main https://github.com/googleapis/google-api-php-client-services package until after launch. As a temporary workaround, we can generate and install the same client library bindings for PHP which we can later remove once available in the official client services. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PHP client library files for the `subscribewithgoogle` v1 API should be generated and added as a new Composer package under `/packages/apiclient-services-subscribewithgoogle`
	* A single `SubscribewithGoogle.php` will be generated which can live in the root
	* The package name should be `google/apiclient-services-subscribewithgoogle`
* The plugin should be updated to require the new package as non-dev Composer dependency
* The added client library files should be prefixed just like any other client service, with the production code using the generated prefixed versions under `/third-party/google/`

## Implementation Brief

* Generate client library file `SubscribewithGoogle.php` under the path in the AC and create the necessary `composer.json` in the same directory
* Add a new definition under the main `composer.json` for the plugin to define a new `path` type Composer repository for the new package
* Update PHP Scoper configuration to include the added package

### Test Coverage

* Add a basic test ensuring the new prefixed dependencies are present

## QA Brief

* N/A – automated tests should be sufficient for this

## Changelog entry

* Add Thank with Google PHP client library.

**Comment by tofumatt** [comment]
Evan and I discussed this a bit offline as well; he'll handle the build so assigning it to him.

IB ✅

**Comment by tofumatt** [comment]
Moving directly to approval since no QA is required.
