### ISSUE TITLE
Popular Content Links Are Broken

### ISSUE THREAD

**Issue by stllrnet** [google/site-kit-wp#566]
In the section "Popular Content" of the dashboard, does appear a hyperlink which should redirect you to the actual page you're viewing the stats. Anyway, it appears SiteKit is adding the current permalink on the dashboard instead of redirecting me to the page.

So basically, instead of taking me to https://domain.com is taking me to https://domain.com/wp-admin/Agencia%20de%20Marketing%20para%20Pymes%20&%20Startups%20%7C%20Domain%20WP

**Comment by swissspidy** [comment]
This is the same issue as in #554, so potentially a valid bug.

Could you please provide some more context and include the permalinks setup you have along with any redirection rules or additional information? The Site Health data from WordPress would be very useful for us.

Thanks!

**Comment by jamesozzie** [comment]
@stllrnet Did you get a chance to review this issue? If the same problem remains please provide additional context, or share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard.

**Comment by stllrnet** [comment]
Hi! Sorry for the delay, the problem is currently happening to me.

[LINK TO VIDEO](https://youtu.be/Ir9iue02hvY)

Here's my Site Health Data... Score: 100


### wp-core ###

version: 5.2.4
site_language: es_ES
user_language: es_ES
permalink: /blog/%postname%/
https_status: true
user_count: 2
dotorg_communication: true

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: GeneratePress Child
version: 0.1
author: Tom Usborne
author_website: https://tomusborne.com
parent_theme: GeneratePress

### wp-themes (2) ###

GeneratePress: version: 2.3.2, author: Tom Usborne
Twenty Nineteen: version: 1.4, author: el equipo de WordPress

### wp-plugins-active (10) ###

CoBlocks: version: 1.16.1, author: GoDaddy
Elementor: version: 2.7.4, author: Elementor.com
Elementor Pro: version: 2.7.2, author: Elementor.com
GP Premium: version: 1.8.3, author: Tom Usborne
Mailgun: version: 1.7.1, author: Mailgun
Pods - Custom Content Types and Fields: version: 2.7.15, author: Pods Framework Team
Rank Math SEO: version: 1.0.33, author: Rank Math
Site Kit by Google: version: 1.0.0-beta.1.0.8, author: Google
SpinupWP: version: 1.1.2, author: Delicious Brains
WP Offload Media Lite: version: 2.2.1, author: Delicious Brains

### wp-server ###

server_architecture: Linux 4.15.0-65-generic x86_64
httpd_software: nginx/1.15.8
php_version: 7.3.10-1+ubuntu18.04.1+deb.sury.org+1 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.58.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-constants ###

WP_HOME: https://luzoculta.co
WP_SITEURL: https://luzoculta.co
WP_CONTENT_DIR: /sites/luzoculta.co/files/wp-content
WP_PLUGIN_DIR: /sites/luzoculta.co/files/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: nginx/1.15.8
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: Sí
pods-session-save-path-writable: Sí
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Sí
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: Sí
pods-memory-current-usage: 22,544M
pods-memory-current-usage-real: 8,000M
pods-network-wide: No
pods-install-location: /sites/luzoculta.co/files/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Sí
pods-api-cache: Sí

**Comment by jamesozzie** [comment]
@stllrnet Thanks for the additional information, very useful. I am unable to recreate the same issue from my side. Do you have any other WordPress websites on the same server you can test with, to check if the same problem arises?

**Comment by stllrnet** [comment]
Hi James! Yes, I have other sites installed on this server and they have the same problem.

[Here's a video](https://youtu.be/ppn4SCOpdFk)

**Comment by jamesozzie** [comment]
@stllrnet I see that site is using the same theme and some of the same plugins. Can you temporarily deactivate the "SpinupWP" plugin and modify your permalink structure before checking again?

**Comment by stllrnet** [comment]
I did what you told and the problem continues. I also deactivated every single plugin, except 'Site Kit' and refreshed the permalinks, and again, problem continues.

**Comment by AndreiIgna** [comment]
Same problem here. The widget on Dashboard has broken links.

<img width="687" alt="Screenshot 2019-10-28 at 10 33 14" src="https://user-images.githubusercontent.com/263021/67667666-9307ee00-f96e-11e9-9544-4eb40323d532.png">

For example, top content links should point to `site.com/`, but instead it points to `site.com/wp-admin/__page_title__`.
Maybe a template string contains `site_url + page_title` instead of `site_url + page_url`?

**Comment by jamesozzie** [comment]
@stllrnet @AndreiIgna The latest version of the plugin is available now, RC2. You can download it [here](https://sitekit.withgoogle.com/service/download/google-site-kit.zip). Please check if the same issue persists.

**Comment by stllrnet** [comment]
@jamesozzie I can confirm issue is solved. At least on my side, funny that @AndreiIgna is also working with content on spanish. Would love to know what was causing this tho.

**Comment by jamesozzie** [comment]
@stllrnet Good to know. And the fix referenced in #598 also resolved this issue with the latest Site Kit release, hopefully you're enjoying using the product.
