### ISSUE TITLE
Add details on popup when user disconnects Thank with Google

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5661]
## Bug Description

When a user disconnects Thank with Google a popup appears asking them to confirm the disconnection.  On other modules we have a message informing the user what they will no longer have access to. To be consistent we should create a message for TwG on this popup confirmation box. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/18618be6-140a-47b4-ba6b-243e78e6bcde)

## Steps to reproduce

1. Go to Site Kit settings
2. Click on Thank with Google
3. Click on the 'edit', then the Disconnect Thank with Google from Site Kit link
4. See popup box with message asking user to disconnect. 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
Include the following text on the disconnect popup: 
- Description: _By disconnecting the Thank with Google module from Site Kit, you will no longer have access to:_
- List item 1: _Virtual stickers and personal messages from your supporters_
- List item 2: _Revenue from any paid virtual stickers supporters send you_
  

## Implementation Brief

In `assets/js/modules/thank-with-google/index.js`, within the `registerModule` function, add the following:
- Add the `features` property to the `modules.registerModule` method's second parameter, which is an object.
- The value should be an array of translated strings below:
  * _Virtual stickers and personal messages from your supporters_
  * _Revenue from any paid virtual stickers supporters send you_
- Note: The description will already be displayed by providing the `features` property.

### Test Coverage

- No new tests are to be added.

## QA Brief

- Go to Site Kit settings.
- Click on Thank with Google.
- Click on the `edit`, then click on the `Disconnect Thank with Google from Site Kit` link.
- Ensure the description and the list items are displayed.

![Screenshot 2022-08-16 at 12 14 21 PM](https://user-images.githubusercontent.com/24408261/184822788-b3ac4fac-3bd1-4a63-ae47-d02426b8ca7e.png)

## Changelog entry

* Show a list of features on the Thank with Google disconnection modal.

**Comment by eclarke1** [comment]
@aaemnnosttv Mariya is OoO all week, could anyone else contribute to progressing this one instead?

**Comment by eclarke1** [comment]
@marrrmarrr as quickly as possible w/c Aug 15 when you're back, could we kindly ask you to add ACs here so we can aim to get this issue into Approval by Aug 19 ahead of bug bash. Thank you

**Comment by marrrmarrr** [comment]
@aaemnnosttv @eclarke1 updated! LMK if you need any more context here

**Comment by eclarke1** [comment]
Thanks so much @marrrmarrr I will move this over to IB now as we want to get it into Approval by Friday this week.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified description and the list items are displaying under pop up confirmation box.
- Verified font and button styles. It is matching with existing style.
-  Verified in mobile devices.

![image](https://user-images.githubusercontent.com/94359491/185034290-109648f8-0364-4954-a215-61a017251355.png)
