### ISSUE TITLE
Prefix `keyframes` names to avoid global namespace conflict

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5662]
## Bug Description

As [reported by a user in the support forums ](https://wordpress.org/support/topic/poorly-defined-css-class-bleeding-into-other-elements/#post-15892150) there is no Site Kit specific prefix for the `@keyframes pulse` rule used on the Site Kit admin toolbar. This is resulting in the rule overwriting the Beaver Builder rule using the same class. 

The rule can be found [here](https://github.com/google/site-kit-wp/blob/1e8c5fa56671802c358ec714a1c16d52c8be64f2/assets/sass/components/global/_googlesitekit-preview-block.scss#L51) I believe, and is output in the below file on the users site:
`/wp-content/plugins/google-site-kit/dist/assets/css/googlesitekit-adminbar-css-9d1dbd2f9a5079ea1900.min.css`

## Screenshots

<kbd> ![image](https://user-images.githubusercontent.com/41326532/183127888-fe2fdc16-9ebe-4d61-ae58-27e7c142d032.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All `@keyframes` names used in CSS animations used by Site Kit should be updated with a `googlesitekit-` prefix

## Implementation Brief

* In your editor, locate all the `@keyframes` definitions
* Add a `googlesitekit`-prefix to each of them
* Locate all of the instances of animations in the project
* Update each instance to include the prefix in the animation name

### Test Coverage

* No new tests needed.

## QA Brief
* There should be no difference in the loading animation while waiting for components to be rendered. (Pulse animation). The "Global -> Preview Block" story can be checked as well.
* There should be no changes to the animations within the AdSense Connect CTA widget. QAing the story for that component should be enough. (Modules -> AdSense -> Widgets -> AdSenseConnectCTA)

## Changelog entry

* Prefix all `keyframes` names to avoid global namespace conflict.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- There is no difference in the loading animation while waiting for components to be rendered.  Checked this on the Dashboard after clearing cache on a site that has zero and live data. 
- There should be no changes to the animations within the AdSense Connect CTA widget.  
- Also checked the Stories in the QAB and they look as expected.
