### ISSUE TITLE
Additional Permission Required pop up appearing on Thank with Google settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5664]
## Bug Description

Currently, when you view Thank with Google settings, the `Additional Permissions Required` popup appears. I noticed that when setting the module up, I am not asked to login to my Google account to give permission.  

This seems to be due to a recent change because when testing previously, I was asked for permission.  Here's a screencast of setting up TwG and what happens when you go to view the settings. 

https://user-images.githubusercontent.com/73545194/183400114-c19272c9-7a7e-4416-9416-c98242842617.mp4

## Steps to reproduce

1. Set up TwG and observe that you are not asked to give permission.
2. Go to Settings for TwG 
3. See Additional Permissions required popup

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren – this was due to something missed in #5534, so we can address it there.

Cloing this in favor of the follow-up PR on that one.
