### ISSUE TITLE
Legacy widget for Supporter Wall not available in FSE themes

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5665]
## Bug Description

Discovered this while testing #5451 

Currently, we are using the legacy widget for Thank with Google Supporter wall.  For users who are using a Full Site Editor (FSE) theme, i.e. 2022, they will be unable to add the widget.  The widget does not appear when you try and add it to a widget area on a FSE theme.  

@eugene-manuilov observed that the legacy widgets component has been disabled for the new post editor intentionally, and there's a [Github ticket](https://github.com/WordPress/gutenberg/issues/24900) for this.  

While the new block-based widget for the supporter wall is out of scope, it's very likely that this will create some support tickets from users, so I am wondering if there's anything we can do to fix this issue - or is it a case of communicating this to our users beforehand?   

Since we're only launching to a small audience initially, this does not feel like a launch blocker. 

https://user-images.githubusercontent.com/73545194/183436066-f11ef9ce-e674-4700-bdc6-2177cf80af92.mp4

## Steps to reproduce

1. Make sure a FSE theme like 2022 is activated
2. Go to Editor in the Appearance menu. 
3. Select a widget area, i.e. Sidebar
4. Search for the Thank with Google widget. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Just a note to mention that I spotted this section in the docs for the Legacy Widget block: [Using the Legacy Widget block in other block editors (Advanced)](https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/#using-the-legacy-widget-block-in-other-block-editors-advanced)

> You may optionally allow the Legacy Widget block in other block editors such as
the WordPress post editor. This is not enabled by default.

I am not sure if that means it would work on an FSE theme - and I think it would probably be a bit of a blunt instrument for enabling the widget if so. Nevertheless, I just wanted to flag it up in case it's useful.

**Comment by eclarke1** [comment]
Closing this issue out now given TwG status
