### ISSUE TITLE
Update relevant TwG field names and values based on TwG API changes

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5669]
See https://github.com/google/site-kit-wp/issues/5534#issuecomment-1209013106: Since the original API definition, some fields in the API response shape have changed. The plugin implementation needs to be adjusted accordingly, mostly on the client-side.

A related more server-side focused issue is #5653.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All references to a TwG publication's `state` field (including fixtures) should be updated to use the field name `onboardingState`.
* The possible values checked for for this `state` (now `onboardingState`) field should also be updated as follows (these values are currently stored in constants):
    * `ACTION_REQUIRED` --> `ONBOARDING_ACTION_REQUIRED`
    * `PENDING_VERIFICATION` --> `PENDING_VERIFICATION` (no change)
    * `ACTIVE` --> `ONBOARDING_COMPLETE`
* All references to a TwG publication's `virtualGifts` field (only fixtures at this point) should be updated to use the field name `thankStickers`.
* It should be verified that all Storybook integrations still behave correctly as before.

## Implementation Brief

**Update the `state` field with `onboardingState`**

- In `assets/js/modules/thank-with-google/datastore/constants.js`, update the following constant (state) values:
  * `ACTION_REQUIRED` --> `ONBOARDING_ACTION_REQUIRED`
  * `ACTIVE` --> `ONBOARDING_COMPLETE`
  * Update the constant names to keep them consistent with the new values.
- Update the imports and usages in `assets/js/modules/thank-with-google/components/setup/SetupMain.js` and `assets/js/modules/thank-with-google/components/setup/SetupMain.stories.js`.
- Update the usages in `assets/js/modules/thank-with-google/components/setup/SetupMain.test.js` and `assets/js/modules/thank-with-google/datastore/publications.test.js`. Import and use the constants instead of the hard-coded values.

**Update the `virtualGifts` field with `thankStickers`**

- Update the usages of `virtualGifts` with `thankStickers` in the following files:
  * `assets/js/modules/thank-with-google/datastore/publications.test.js`
  * `assets/js/modules/thank-with-google/components/setup/SetupMain.test.js`
  * `assets/js/modules/thank-with-google/components/setup/SetupMain.stories.js`

### Test Coverage

- Ensure the modified stories are working as expected.
- Ensure the tests are passing in the modified test files.

## QA Brief

**QA:Eng**

- The changes have to be verified as `QA:Eng` across the entire code base.
- Ensure the `state` field in the publication object has been renamed to `onboardingState`.
- Ensure the values of the constants are changed as per the AC.
- Ensure the `virtualGifts` property has been renamed to `thankStickers`.
- Verify all the tests are passing in `assets/js/modules/thank-with-google/datastore/publications.test.js` and `assets/js/modules/thank-with-google/components/setup/SetupMain.test.js`.
- Verify the stories in `assets/js/modules/thank-with-google/components/setup/SetupMain.stories.js` work as before.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
I have added the `QA:Eng` label to this ticket as per the QAB, but if it is felt that we can test any part of this please provide instructions and I'm happy to take a look at it.

**Comment by techanvil** [comment]
## QA :white_check_mark: 

- Ensure the `state` field in the publication object has been renamed to `onboardingState`. :white_check_mark: 
- Ensure the values of the constants are changed as per the AC. :white_check_mark: 
- Ensure the `virtualGifts` property has been renamed to `thankStickers`. :white_check_mark: 
- Verify all the tests are passing in `assets/js/modules/thank-with-google/datastore/publications.test.js` and `assets/js/modules/thank-with-google/components/setup/SetupMain.test.js`. :white_check_mark: 
- Verify the stories in `assets/js/modules/thank-with-google/components/setup/SetupMain.stories.js` work as before. :white_check_mark:

**Comment by techanvil** [comment]
Hi @hussain-t, I have run through the QA items for the sake of completeness. However in future, please consider that the points about checking the codebase and tests are aspects that are covered in the Code Review stage, and there's no need to duplicate them in QA.

> - Ensure the `state` field in the publication object has been renamed to `onboardingState`.
> - Ensure the values of the constants are changed as per the AC.
> - Ensure the `virtualGifts` property has been renamed to `thankStickers`.
> - Verify all the tests are passing in `assets/js/modules/thank-with-google/datastore/publications.test.js` and `assets/js/modules/thank-with-google/components/setup/SetupMain.test.js`.

**Comment by hussain-t** [comment]
Thanks, @techanvil; I agree with you. However, I was not sure what else could be tested besides the mentioned points in QAB.

**Comment by techanvil** [comment]
> Thanks, @techanvil; I agree with you. However, I was not sure what else could be tested besides the mentioned points in QAB.

That's OK, just bear in mind that we are trying to keep QA as user-facing as possible, so `QA:Eng` should only be used sparingly when necessary, and not to cover aspects which are already covered elsewhere, for example in CR.

Indeed, it's perfectly OK to _not_ have a QAB at all if there's a good reason for it.
