### ISSUE TITLE
Just get the API key in setup

### ISSUE THREAD

**Issue by thune** [google/site-kit-wp#567]
Hi

Tried to install Google Site Kit and I just got the API Key and not the client configuration snippet.
![oauthcredentials-google-site-kit](https://user-images.githubusercontent.com/646779/65389516-69e4b400-dd57-11e9-876e-620f9b65284e.png)

Regards
Øystein

**Comment by jony2323** [comment]
i am having the same problem. no full code just single line api code and error Unable to parse client configuration values

**Comment by zoi555** [comment]
I'm having precisely the same issue, anybody had any luck resolving this?

**Comment by hellojess7** [comment]
I am having the same issue as well. 
![GSK Auth ](https://user-images.githubusercontent.com/55683318/65405682-28292d00-dd9a-11e9-861b-90ae48160d66.png)

**Comment by kaelhoel** [comment]
Experiencing the same issue with a fresh install. The layout appears to be broken on the page which presents your project details, and requesting the OAuth Credentials leads to the above result which others have shown.

![image](https://user-images.githubusercontent.com/48452614/65415807-c814a400-ddf6-11e9-8fbd-d0931141e533.png)

**Comment by swissspidy** [comment]
Thanks for your reports everyone! We're already tracking this in #561 and are currently investigating this.

A workaround has been posted at https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770 which you could use in the meantime.

**Please follow #561 for any updates on this.**
