### ISSUE TITLE
Add a graph of visitors and various reporting period options to the Site Kit summary widget on the WP Admin dashboard

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5670]
## Bug Description

Consider adding the following to the Site Kit summary widget on the WP Admin dashboard. 
1. A graph of visitors
2. A selective reporting period. Currently it only displays a 28 days reporting period. 

This graph could be a modified version of current "All users" widget on the Site Kit dashboard, as per the image below:

<kbd>![image](https://user-images.githubusercontent.com/41326532/183641914-a232a7b1-7a24-4e01-a1e3-135d3a9ebdef.png)

An example, which the [user who submitted this feature request](https://wordpress.org/support/topic/feature-request-customize-the-dashboard) kindly shared, can be seen below, from the JetPack stats dashboard. 
 
<kbd>![image](https://user-images.githubusercontent.com/41326532/183642194-6d9d2835-b9de-4013-8907-f6001fe488f6.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
We added a new graph to the Site Kit Summary widget in #631 .
The remaining bit about controlling the date range is covered by #5589.
