### ISSUE TITLE
Request only TwG publications for the current verified site URL/domain

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5671]
Follow-up to #5534 (see https://github.com/google/site-kit-wp/issues/5534#issuecomment-1208313249), to address [this TODO comment](https://github.com/google/site-kit-wp/pull/5652/files#diff-f484944f8f737a196b627b845da4d99e5ebc0959adb9eb27b21fdb695b3e079eR244).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG `GET:publications` data point should be completed, by requesting only publications for the relevant verified site using the `filter` parameter for the TwG API request:
    * The current Search Console property ID should be used, with the relevant permutations ("http" and "https" for URLs, "www" and "non-www" in any case).
    * If it is a domain property (`sc-domain:...`), the `filter` parameter should be: `domain = "example.com" OR domain = "www.example.com"` (using the permutations of the domain following `sc-domain:`)
    * If it is a URL property (`http://...` or `https://...`), the `filter` parameter should be: `site_url = "https://example.com/" OR site_url = "http://example.com/" OR site_url = "https://www.example.com/" OR site_url = "http://www.example.com/"` (using the permutations of the full URL)
* It should be ensured that the API response then only includes publications for the corresponding URL. This may require coordination with the TwG team so that they can create multiple test publications accordingly, to make sure that this parameter works (you need at least two publications, one of a URL or domain from what you will pass in the parameter, and another one for any other site).

## Implementation Brief

- In `includes/Modules/Search_Console.php`:
    - At the end of the `register` method, use `add_filter` to add a callback function to the filter hook named `googlesitekit_thank_with_google_publications_filter` (or something more relevant). Inside the callback function:
	    - Run the `get_property_id` method of the same class and assign it to a variable named `$search_console_property_id`.
        - Create a stripped out version of the property ID and assign it to a variable named `$raw_url` (or something more relevant):
            - Using `str_replace`, remove all instances of `sc-domain:`, `https://`, `http://`, and `www.`.
            - Using the `normalize_url` method of the `Google\Site_Kit\Core\Util\Google_URL_Normalizer` class to normalize the stripped out value.
        - Check if `$search_console_property_id` is a domain property by seeing if it starts with `sc-domain:` ( e.g. `0 === strpos( $search_console_property_id, 'sc-domain:' )` ).
            - If it is a domain property, create a string containing `domain = "{ $raw_url }" OR domain = "www.{ $raw_url }"` and assign it to a variable named `$filter`.
            - If it is not a domain property:
                - Update the `$raw_url` variable using `trailingslashit` with the existing value of `$raw_url`.
                - Create another string containing `site_url = "https://{ $raw_url }" OR site_url = "http://{ $raw_url }" OR site_url = "https://www.{ $raw_url }" OR site_url = "http://www.{ $raw_url }"` and re-assign it to the `$filter` variable.
		- Return the `$filter` variable from the callback function.
- In `includes/Modules/Thank_With_Google.php`:
    - Locate the `TODO` comment mentioned in the issue description in the `create_data_request` method. Replace it with the following:
        - Use `apply_filters` to call the callback function that has been assigned to the `googlesitekit_thank_with_google_publications_filter` hook with an empty string passed as the filter value (second parameter). Assign it to a variable named `$filter`.
        - Create a new array containing one element with the key as `filter` and value as the `$filter` variable and assign it to a variable named `$optParams`.
        - In the `listPublications` method call, pass the `$optParams` variable as the method parameter.

### Test Coverage

No tests need to be added/updated.

### QA:Eng

- Ensure that the Thank with Google module is not active.
- Go to `Site Kit -> Settings -> Connect More Services`.
- Open the `Browser Developer Tools -> Network` tab.
- Click on `Set up Thank with Google`.
- Observe the response of the `/google-site-kit/v1/modules/thank-with-google/data/publications` endpoint.
- Compare the response with the same endpoint in:
    - `develop` branch for CR.
    - `main` branch for MR/QA.
- Ensure that the response only includes publications for the current verified site URL/domain.

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
> In `includes/Modules/Search_Console.php`:
> * Make the `get_property_id` method to be public so that it can be accessed from other classes.

@nfmohit instead of opening the `get_property_id` method in the SC module, we should use a new filter in the `GET:publications` handler that will allow us to use a hook in the SC class to add constrains to the listPublications params. In this case, we will avoid a need to directly access the SC class in the TwG module thus avoid though coupling there.

**Comment by nfmohit** [comment]
Thank you @eugene-manuilov! I have updated the IB.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
> @nfmohit instead of opening the `get_property_id` method in the SC module, we should use a new filter in the `GET:publications` handler that will allow us to use a hook in the SC class to add constrains to the listPublications params. In this case, we will avoid a need to directly access the SC class in the TwG module thus avoid though coupling there.

Just a heads up that I suggested a different solution for this in CR. In the future, I think it would make sense to make the property ID generally available to all modules but for now it would be a little cleaner to grab it via settings.

**Comment by wpdarren** [comment]
@nfmohit IMO, I don't think the QAB is `QA:Eng`, Mohit or I should be able to test this for you. If you feel it's more engineering that's fine, but thought I would mention 😄

**Comment by nfmohit** [comment]
> @nfmohit IMO, I don't think the QAB is `QA:Eng`, Mohit or I should be able to test this for you. If you feel it's more engineering that's fine, but thought I would mention 😄

Sure thing, @wpdarren! I only marked this with a `QA:Eng` because to test this, we'd need multiple publications returning from the API. @aaemnnosttv [mentioned](https://10up.slack.com/archives/CBKKQEBR9/p1660851836551339?thread_ts=1660846811.055289&cid=CBKKQEBR9) he could test it.

**Comment by wpdarren** [comment]
@nfmohit Ah thank you, I didn't realise you needed multiple publications. Yes, I agree `QA:Eng` is best for this one! 😄

**Comment by aaemnnosttv** [comment]
## QA:Eng ✅ 

* Checked `filter` argument is constructed properly for both domain and URL prefix type SC properties
* Checked publications returned from the API match the given filter for both domain and URL prefix properties

Moving to approval as there isn't much else to QA here.
