### ISSUE TITLE
Add the GA4 Activation Banner to the Entity Dashboard

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5673]
## Feature Description

Show the GA4 Activation Banner on the Entity Dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 Activation Banner should be included on the Entity Dashboard, when the `ga4ActivationBanner` feature flag is enabled.

## Implementation Brief

- In `assets/js/components/notifications/EntityBannerNotifications.js`:
    - Use the `useFeature` hook passing the `ga4ActivationBanner` string to it and assign it to a variable named `ga4ActivationBannerEnabled`.
    - In the return statement, render the `<ActivationBanner />` component (`assets/js/modules/analytics-4/components/dashboard/ActivationBanner`) only if `ga4ActivationBannerEnabled` is truthy.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* With the `ga4ActivationBanner` feature flag enabled, navigate to the entity dashboard
* Ensure that the ga4 activation banner renders correctly
* Navigate to the entity dashboard without the feature flag enabled
* The component should not be present.

## Changelog entry

- Add the Google Analytics 4 Activation Banner to the Entity Dashboard.

**Comment by aaemnnosttv** [comment]
@techanvil I've tweaked the language to hopefully avoid misinterpretation that the banner should be displayed/visible when the feature flag is enabled as it has its own logic for determining that as well which is still relevant of course.

**Comment by techanvil** [comment]
Good shout @aaemnnosttv, thanks!

**Comment by nfmohit** [comment]
@techanvil I believe including the GA4 Activation Banner to the Main Dashboard has been already done at #5270. Do we need to update the ACs?

I have added the IB for the Entity Dashboard.

**Comment by techanvil** [comment]
Thanks @nfmohit, not sure how I missed that. I've updated the rest of the issue accordingly. Cheers!

**Comment by nfmohit** [comment]
Thank you @techanvil!

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by techanvil** [comment]
@makiost I tweaked the QAB to explicitly mention the entity dashboard rather than just the dashboard.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified when `ga4ActivationBanner` feature flag enabled.
- On entity dashboard - ga4 activation banner renders correctly
- Verified when `ga4ActivationBanner` feature flag disabled.
- On entity dashboard - ga4 activation banner is not present.

https://user-images.githubusercontent.com/94359491/185054090-17c172da-d176-4991-93b8-5c1eade0683e.mp4
