### ISSUE TITLE
Avoid too large TwG SVGs from being part of the ZIP file

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5679]
See #5627: There are a few way too large SVGs in the plugin now from TwG. While TwG is behind a feature flag right now, the files of course are already in the plugin and are imported in the TwG bundle, which more than doubles the ZIP file size (~3.9MB --> ~7.9MB).

While #5627 is focused on getting more optimized versions of these SVGs and incorporating them into the plugin, we should remove the current graphics (or at least avoid them from being imported) right now to fix the massive ZIP file size.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The 3 TwG SVG files flagged in #5627 must no longer be part of the plugin ZIP.
    * The files don't have to be removed from the repository, but they must no longer be imported so that they don't become part of the ZIP.
    * It is perfectly fine that there are no more graphics available in their place at this time, until that can get fixed via #5627.
    * A `TODO` comment should be added on each temporary placeholder component which should eventually be replaced with a specific one of these SVG graphics.

## Implementation Brief

**Please create the PR for this issue against `main`.**

* In `assets/svg/graphics`:
    * Create empty version of `thank-with-google-setup.svg`, `twg-dynamic-high.svg` and `twg-dynamic-low.svg` ie. `twg-dynamic-low-placeholder.svg`, just keeping the viewbox size and removing everything inside the `svg` tag.
    * Put a `TODO` comment in the file to remove these when we have optimized SVG. 
* In `assets/js/modules/thank-with-google/components/common/ProminenceRadio.js` and `assets/js/modules/thank-with-google/components/setup/SetupPublicationScreen.js` components: 
    * Update the imports of `DynamicLowSVG`, `DynamicHighSVG` and `ThankWithGoogleSetup` to use the newly created empty svg graphics. 
    * Add a `TODO` comment here as well. 
* Finish and merge #5680 

### Test Coverage

* VRTs may need to be updated. 

## QA Brief

* QA:ENG - 
    * Switch to `main` branch. 
    * Run `npm run build:production` and `npm run zip`.
    * The generated zip should no longer be 7+mb. It will be around 3. `ls -lh`

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- I am labelling this as `QA:Eng` as per the QAB, but I have just generated the zip file [from main](https://github.com/google/site-kit-wp/wiki/refs/heads/main/google-site-kit.zip) and it's 3MB.

**Comment by nfmohit** [comment]
### QA Verified ✅ 

> The generated zip should no longer be 7+mb. It will be around 3.

![image](https://user-images.githubusercontent.com/20284937/184317298-ccd3daa5-f8fd-48f9-9042-cb77158bed2a.png)

![image](https://user-images.githubusercontent.com/20284937/184317432-6ed84b8f-2d4b-4a1a-8ed6-2acadf002cd6.png)
