### ISSUE TITLE
UX/UI issues discovered on Thank with Google module

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5689]
## Bug Description

While running through my test plan for Thank with Google, I noticed a number of styling / missing images from the module that were not appearing when we initially completed the QA. These will be brought up at the bug bash so ideally, it would be good to get these fixed and not have them as known issues. 

<details>
	<summary>Non-issues</summary>

1.  The background colour of the CTA on the pending verification splash screen. The colour is `#161B18` rather than `#3C7251`

![image](https://user-images.githubusercontent.com/73545194/184609472-b1a0c4e9-22ac-4fc1-8f2d-07dac81b4892.png)

Issue 2 and 3 are part of the fix in #5627 

2. The images on the splash pages are no longer appearing as you can see from the screenshot above.  The screenshot below is what is appearing on Figma designs and were there previously.  I am using 1.90.0 of the tester plugin but I know we have a new version so it could be possibly linked but unsure.

3. The images within the image radio buttons are no longer appearing when customizing TwG.  Also the size of the two buttons are no longer the same height.
</details>

4. When using Safari, the colour border is square instead of round like on Chrome and other browsers.  We've had this issue with other elements of Site Kit (i.e. chip navigation on dashboard), but thought it was worth highlighting.  
![image](https://user-images.githubusercontent.com/73545194/184613831-209c6ecd-301b-428c-a248-1d61a3fc9904.png)

5. Extra padding in setup and settings  
	<details>
		<summary>Screenshots</summary>	
	
	**Setup with extra padding**
	![image](https://user-images.githubusercontent.com/1621608/184710738-3cf19b7b-9472-446e-8b47-75df747de346.png)
	**Settings view with extra padding**
	![image](https://user-images.githubusercontent.com/1621608/184710152-c126dc65-62e4-44a1-bee0-bdcd3d5b7694.png)
	**Settings edit with correct padding**
	<img width="479" alt="image" src="https://user-images.githubusercontent.com/1621608/184710633-3aaa884c-87c6-40de-b968-748f2e93ced3.png">
	**Example setup with correct padding**
	![image](https://user-images.githubusercontent.com/1621608/184710657-fb2db75d-97e9-47c7-b9c2-047870757f55.png)
	</details>
6. Minor layout shift when selected **Prominence** choice changes

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The elements of the TwG setup/settings should display consistently across major supported browsers, specifically regarding the use of rounded corners which all support (currently some elements appear with square corners/borders in Safari)
* TwG setup and settings views should have surrounding whitespace consistent with other modules
* There should be no shifting of content when toggling between choices for the CTA overlay "Prominence"

## Implementation Brief

The border radius issue in safari is caused by the browser not applying border radius styles to `outline`-properties in CSS. This can be remedied by refactoring the outline to use a pseudo element instead.

In `assets/sass/components/global/_googlesitekit-image-radio.scss`:
* Add a new `::after` pseudoelement to the `.mdc-image-radio__background` selector
* Position it absolutely and give it the same border radius as the element in `.mdc-image-radio__content` 
* Remove the outline-property from the `.mdc-image-radio__content` selector and add it to the `::after` element as an border
* Update the hover, active and focused state accordingly, changing the outline to the border property on the `::after` element

In `assets/sass/components/thank-with-google/_googlesitekit-twg-color-radio.scss`:
* Add the 50% border radius property to the aforementioned pseudo element  when its used in a two-color radio

The layout shifting is caused by the outline getting thicker in the checked state, and the border getting thinner to compensate for it. 
When refactoring the outline to a pseudo-element, ensure that the combined width of the white border on `mdc-image-radio__content` and the green/gray border on `.mdc-image-radio__background::after` is the same for both the checked and unchecked variants.

The extra padding is caused by the use of nested grid elements in the module, both adding 24px of padding inside of the module. 
In `assets/js/modules/thank-with-google/components/settings/SettingsView.js`:
* Refactor the use of `<Grid>...</Grid>`  to closer match the implementation of the `SettingsView` component in other modules (e.g: `assets/js/modules/tagmanager/components/settings/SettingsView.js`, `assets/js/modules/analytics/components/settings/SettingsView.js`)

### Test Coverage

* 

## QA Brief

* Observe both TwG Setup and Settings page from Safari and other browser. 
* Rounded corners should work across the browser on Image and Color Radio Buttons.
* Match with latest [figma](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A12781) design. 
* There should no longer be any layout shift on changing Prominence value

## Changelog entry

* Update Thank with Google setup and settings views for consistency with other modules and major browsers.

**Comment by eclarke1** [comment]
Added P1 label as a nice to have for bug bash.

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren 

Regarding #1 – this is intentional and part of the design for the ["Pending Approval" step in Figma](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=1781%3A11338).

As for #4 – is this still a problem with other browsers for the other elements you mentioned or we were able to fix it? It's not ideal but I feel like this should be doable in Safari as well. Definitely not a launch blocker 😄

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Observed both TwG Setup and Settings page from Safari and Chrome (desktop and mobile) 
- Rounded corners work across the browser on Image and Color Radio Buttons.
- There is no longer any layout shift on changing Prominence value.
- Checked that setup and settings page match the figma designs. 

<details>
 <summary>Screencasts</summary>

![image](https://user-images.githubusercontent.com/73545194/193557651-29e1b09b-19d7-4a8c-940a-66b801f6c52c.png)

https://user-images.githubusercontent.com/73545194/193557763-6e8c4e18-f9a7-4448-92dd-16a2372e0929.mp4


https://user-images.githubusercontent.com/73545194/193557775-af2618b3-bff9-42c9-818f-baac7c39fd23.mp4

</details>
