### ISSUE TITLE
Unable to parse

### ISSUE THREAD

**Issue by Sunpro2** [google/site-kit-wp#569]
the following are screen shots that i receive.
![2019-09-23 (1)](https://user-images.githubusercontent.com/53017932/65432777-6b5abe80-dde1-11e9-9743-4ab5243e6151.png)

![2019-09-23](https://user-images.githubusercontent.com/53017932/65432830-84fc0600-dde1-11e9-92f2-4c6275a4769c.png)

**Comment by swissspidy** [comment]
Thanks for your report! We're already tracking this in #561 and are currently investigating this.

A workaround has been posted at https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770 which you could use in the meantime.

**Please follow #561 for any updates on this.**
