### ISSUE TITLE
TwG init JS breaks with older browsers

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5694]
## Bug Description

The init snippet for TwG currently uses an arrow function which will throw a syntax error on older browsers.

## Steps to reproduce

1. Connect TwG
2. Load a page/post enabled with TwG using IE 11
3. See syntax error 

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/184707017-063aa99a-8b16-40cb-ae56-fb9c7831a182.png)

Note `Promise` is also not available in `thank.js` but this is outside of SK

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `init` snippet of the TwG web tag must not use modern language features including arrow functions

## Implementation Brief

* Update https://github.com/google/site-kit-wp/blob/34f1524149b416151bda62147771f6bcc269430f/includes/Modules/Thank_With_Google/Web_Tag.php#L112 to use a normal function instead of an arrow function

### Test Coverage

* No changes

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Note `thank.js` doesn't support IE 11, but this is probably worth doing to avoid errors raised unnecessarily and implicating Site Kit.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
@aaemnnosttv @tofumatt, this has been fixed via https://github.com/google/site-kit-wp/issues/5535:

https://github.com/google/site-kit-wp/blob/82cfb69bf80d3d95c2a6019eda8a1df9dfbad9fb/includes/Modules/Thank_With_Google/Web_Tag.php#L148

**Comment by techanvil** [comment]
Closing as already fixed.
