### ISSUE TITLE
WordFence thought Site Kit file was malicious

### ISSUE THREAD

**Issue by jasoncsking** [google/site-kit-wp#57]
The free version of the WordFence plugin for WordPress sprung a false positive the day after I installed Site Kit. It said:

> * This file may contain malicious executable code: wp-content/plugins/google-site-kit/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php

I just wanted to make you aware, in case there's anything you could tweak to avoid this happening, or in case there's a way to get whitelisted by WordFence. WF is such a popular plugin, this could happen to a lot of people.

Perhaps once Site Kit is in the WP repository, this won't happen, not sure!

**Comment by ivankristianto** [comment]
Thanks @jasoncsking 
this is related to this issue as well: https://github.com/google/site-kit-wp/issues/21
We are planning to remove the dependency with phpseclib for sure.

**Comment by jamesozzie** [comment]
Thanks for reporting. I will close this as #21 is being worked on
