### ISSUE TITLE
Combine all Analytics OAuth permission requests during set up

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5703]
## Bug Description

When connecting the Analytics module after setting up Site Kit for the first time there are two different OAuth permission requests at present. The first one appears before you select your UA Analytics account when connecting the module, and the second appears when selecting a GA4 property. The second one seems to be unavoidable, even if you don't use Site Kit to create a GA4 property (ie. You select an existing one)

_If possible_, merge the OAuth permission requests during the initial OAuth request when connecting the Analytics module. 

https://user-images.githubusercontent.com/41326532/185172513-802ebd6c-f8ae-4c85-847c-c48bba459e34.mp4

## Steps to reproduce

1. Set up a new site using InstaWP or TasteWP
2. Set up Site Kit (without GA)
3. Connect the GA module
4. You'll have to go through OAuth permissions twice, granting different permissions of course, but still going through the OAuth flow twice
 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks James! Ideally, we'd only send users through oAuth once but we can't do that without knowing all the scopes a user would need up front. We could of course technically request everything all the time, but that would be out of line with security and privacy best practices.

This issue assumes there are always two separate oAuth flows as part of the Analytics setup, but that isn't always the case.

The first flow is what grants the minimum requirements we need to read data from the Google Analytics reporting and management APIs for the dashboard and setup respectively. By default we only request readonly permissions where available to not give Site Kit any more permission than it needs (until it needs it) as a best practice. If the user already has UA and GA4 properties for the current site, no additional oAuth flows would be necessary. In some odd cases, a user may have a GA4 property already created that they want to use, but there is no matching web data stream (measurement ID) for the site, so in that case we would also need to request the edit scope to be able to create that for the user (just as if they didn't have a property for either UA/GA4).

Finally, we plan to completely separate the storage of tokens for write access and the "main" token a user gets to satisfy the basic requirements for all active modules which is not compatible with a "combined" oAuth flow approach where everything could be requested at once.

I hope that makes sense – TL;DR we can't do this 😄
