### ISSUE TITLE
Implement internal cache object for `googlesitekit-api`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#571]
## Feature Description

Related to #570, a `cache` object should be introduced to provide an infrastructure for looking up and storing values in a (semi-)persistent cache. This cache layer should be based on existing cache logic from `data.js`, decoupled from how cache keys are generated for API requests specifically. Nonetheless, for now this object should be internal to the `googlesitekit-api` script.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The script should export an object with the following methods:
    * `get( key, maxAge )` (should equal `getCache()` from `data.js`)
    * `set( key, data )` (should equal `setCache()` from `data.js`)
    * `delete( key )` (should equal `deleteCache()` from `data.js`)
    * `getKeys()` (should return all keys currently in the cache, to make something like `invalidateCacheGroup()` from `data.js` possible; note that this should not include _all_ keys in `localStorage` / `sessionStorage`, but only those affiliated with Site Kit)
* The script should be located in `assets/js/api/cache`, with an `index.js` file as entry point (to be used by `googlesitekit-api` later).
* The script should not rely on anything from other (existing) Site Kit JS code. Even though it will use data already present in `SiteKitCore/util`, let's rather copy the related functionality, as the existing variant should eventually be deleted. We want to decouple the new APIs from any existing code.
* There should be solid Jest test coverage for each of the four methods.

## Implementation Brief

* Create a cache library relying on `localStorage`/`sessionStorage` for persistent storage in `assets/js/googlesitekit/api/cache`.
* Reuse existing cache code found in `data.js` (https://github.com/google/site-kit-wp/blob/5ff50e123b22c761a8ec2563d71c6782297bcfcd/assets/js/components/data.js#L312), but copy it rather than using it directly.
* Caching behaviour should mimic the existing `data.js` behaviours/APIs; `googlesitekit.admin.nojscache` set to `true` should disable the cache entirely.
* Reduce code complexity by eliminating the "variable" cache (https://github.com/google/site-kit-wp/blob/39e8d2de110dd34c8c6711239b3018b41d1545b8/assets/js/components/data.js#L320-L323). I'm not sure why this was added; for our use-case the performance wins of avoiding a few extra calls to `localStorage` are likely to be minimal—and going forward our data store itself should function as an in-memory cache, so let's remove this code now to simplify things.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB written and ready for review.

I think localForage would be a good library to use for this kind of cache storage as we: won't need to have as much boilerplate code for our interactions with the persistent storage and we can use the more flexible/performant IndexedDB for storage. Its footprint on bundle size isn't too much but it'll reduce the code we need to maintain in our own library (and reduce the tests we need to write to verify the actual storage of data works).

Just one note about the existing AC:

I think the folder used should be `assets/js/googlesitekit/api/cache` rather than `assets/js/api/cache`, related to the discussion in #570.

(I think we aren't worried about using this cache outside of API requests, right? If we want to cache things like state in the future we likely want to use some kind of redux/offline library or something that caches our store, not arbitrary keys.)

**Comment by felixarntz** [comment]
@tofumatt 
Can `localForage` be scoped to only consider certain keys? For example, we only would want `getKeys()` to return the keys that actually are from Site Kit (i.e. what we currently prefix with `googlesitekit_`), without the prefix though because that is internal to the cache implementation.

I'm still not convinced on the use of an external library for something that
* is fairly simple
* we have already implemented and know that it works

Refactoring the existing code to use `localForage`
* is more work than just pretty much copying over what we already have
* would (despite its small size) increase the bundle size further than the very specific code we currently have for that
* introduce another dependency

All of the above _may_ certainly be worth it, and I'm not against using `localForage`. However, I don't think there is anything time-critical about doing that, since the existing implementation works just fine. That is why I suggested to discuss for the future in another issue, which you opened #611. 
The JSR is complex enough as it is, so for now let's be pragmatic and reuse what we can reuse, specifically with that code having been written just about a month ago or so.

**Comment by tofumatt** [comment]
> Can localForage be scoped to only consider certain keys? 

Yes. Each localForage instance is scoped to its own database, so if we create our own instance somewhere, like in a `storage.js` file:

```js
import localforage from 'localforage';

const siteKitStorage = localforage.createInstance({
  name: 'googlesitekit',
});

export default siteKitStorage;
```

that we'd import from, we'd only be interacting with our database. See: https://github.com/localForage/localForage#multiple-instances

-----

I agree with your assessment that we should move the discussion on localForage over to #611, especially as we aren't persisting any data right now that would need _migrating_. I've updated the IB for now to exclude adding the external dependency. 👍

**Comment by felixarntz** [comment]
IB ✅
