### ISSUE TITLE
Test coverage for Analytics metrics and dimensions validation methods

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#5728]
## Bug Description

https://github.com/google/site-kit-wp/blob/1f21788d996f25a72320795fe7b80a16d962cc53/includes/Modules/Analytics.php#L1368-L1459

It would be great to get some test coverage on these methods, but I see how that could be a bit problematic as-is. Maybe we could extract these into validation-specific classes? The class could be specific to validating shareable report dimensions so we could unit test it pretty easily and leave the `is_using_shared_credentials` bit to control whether or not such validation is applied or not.

Then we might add only a test or two to the Analytics class to make sure it is wired-up as expected.

_Originally posted by @aaemnnosttv in https://github.com/google/site-kit-wp/pull/5721#discussion_r952960002_

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this has coverage has been added with the current implementation.
