### ISSUE TITLE
Dashboard sharing controller set to dynamically defined property

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5731]
## Bug Description

The core `Modules` class has a property for `$rest_controller` which isn't used. It also assigns the dashboard sharing controller instance to an undefined property.

https://github.com/google/site-kit-wp/blob/412f9126c6bbb6736faa33107d1a3346232e21b4/includes/Core/Modules/Modules.php#L143
https://github.com/google/site-kit-wp/blob/412f9126c6bbb6736faa33107d1a3346232e21b4/includes/Core/Modules/Modules.php#L196

Dynamically defined properties (properties that are set but aren't defined on the class) still work but are [deprecated in PHP 8.2](https://wiki.php.net/rfc/deprecate_dynamic_properties).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The core `Modules` class should not define any properties dynamically

## Implementation Brief

* Rename the `$rest_controller` property to `$rest_dashboard_sharing_controller`

### Test Coverage

* No changes needed

## QA Brief

* This is such a small change that it can be QA'd by an engineer during CR.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
## QA :white_check_mark: 

- Verified the code change.
- Smoke tested Dashboard Sharing settings to check the corresponding REST API still functions as expected.
