### ISSUE TITLE
Replace waitFor render with waitForRegistry in tests

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5734]
## Feature Description

As a small code cleanup we should replace usage of `waitFor( () => render( ...` with `waitForRegistry` in tests. The use of `waitForRegistry` is a bit more explicit.

E.g. https://github.com/google/site-kit-wp/blob/850b76940f069581d12a855c12a9ded801699fad/assets/js/modules/tagmanager/components/settings/SettingsEdit.test.js#L102-L104

Can be rewritten as:

```js
const { container, waitForRegistry } = render(
	<SettingsEdit />,
	{ registry }
);
await waitForRegistry();
```

See https://github.com/google/site-kit-wp/pull/5713/files#r954298667

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instances of `waitFor` which wait upon the result of a `render` should be replaced with usage of `waitForRegistry`, as per the Feature Description.

## Implementation Brief

* Replace all (or most, if some aren't appropriate to replace) instances of `const { container } = await waitFor( () => render( <Component />, { registry } ) );` with:

```js
const { container } = render( <Component />, { registry } );

await waitForRegistry();
```
* Most other instances of `await waitFor( [...] )` are not waiting for the registry to be ready/waiting for a render and can be left as-is. The only one worth replacing or exploring is https://github.com/google/site-kit-wp/blob/412f9126c6bbb6736faa33107d1a3346232e21b4/assets/js/modules/analytics/components/settings/SettingsEdit.test.js#L107

### Test Coverage

* No new tests needed.

## QA Brief

* Technical task which improves test experience in React. No changes to the application.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
> * Technical task which improves test experience in React. No changes to the application.

@sashadoes could you please update QAB and add more details? We usually need to provide certain instructions that can be used by other engineers to properly check changes. Just explain what and where should be checked to confirm that this ticket is done correctly.

**Comment by nfmohit** [comment]
### QA:Eng ✅ 
- Verified that all instances of `waitFor` which wait upon the result of a `render` have been replaced with usage of `waitForRegistry`.
