### ISSUE TITLE
Supporter wall section is missing from setting page in edit mode

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5736]
Even after adding the supporter wall widget it doesn't appear in the edit settings at all

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Supporter wall widget" section should be added to the settings edit view for the Thank With Google module as designed in the [Figma document](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A12620) (between Prominence and Color settings)
	* There is no corresponding UI for this in the TwG setup; the setup customize view is consistent with the current settings edit view in this way 
* Note there are separate states for this section depending on whether or not the supporter wall widget has been placed or not. These can be described as:
	* Activate (no widget placed yet) – includes CTA to activate (place) the widget
	* Edit (widget exists in 1 or more sidebars) – includes CTA to edit
	* In both cases the CTA should open the widgets admin screen, but in a new tab/window to preserve any other changes to the module settings that may not have been saved yet

## Implementation Brief
* Create `assets/js/modules/thank-with-google/components/common/SupporterWall.js` which exports the `SupporterWall` functional component.
* The HTML returned by the component should be wrapped within a `div` having the `googlesitekit-twg-setting-field` and `googlesitekit-twg-supporter-wall` class names.
* It should follow the same markup as one of the other settings component, for e.g `assets/js/modules/thank-with-google/components/common/ColorRadio.js`, i.e the title should be a `h4` heading and the description a paragraph.
* Check if a supporter wall has been added by querying the `modules/thank-with-google` datastore via the `getSupporterWallSidebars` selector.
	* If the selector returns an empty array:
		* display the description as per the designs in Figma. "A supporter wall page shows the list of everyone who has supported..."
		* return a string as per the designs in [Figma](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A12644), prompting the user to activate a wall widget. It should link to the widgets page and open in a new tab.
		* The link to the widget page can be obtained by querying the `core/site` datastore via the `getWidgetsAdminURL` selector.
	* If the array returned by the selector is not empty,
		* Display the widget position as per the [designs](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A13230)
		* Display the list of widget positions as comma delimited string (in case there are many)
		* The link to edit the widget position should point to the widgets admin URL in a new tab.
* Update `assets/js/modules/thank-with-google/components/settings/SettingsForm.js`, to render the newly added `SupporterWall` component before `ColorRadio`.
* Add new stories for `SupporterWall` for both use cases.

### Test Coverage
* No new tests to be added.

## QA Brief

- Ensure that the `twgModule` feature flag is enabled in the tester plugin.
- Go to the `Site Kit -> Settings` page.
- Activate `Thank with Google` if not active already.
- Click on `Edit` within the `Thank with Google` module to make the edit screen show up.
- Verify that a new section `Supporter wall widget` has shown up among the settings.
- Verify that it shows up according to the ACs and Figma:
    - It shows a simple description text according to the Figma designs if no widget is placed.
    - It shows the widget position(s) if a widget is placed.
    - The link to the widget settings is visible, shows `Activate`/`Edit` accordingly, and opens in a new tab in case of editing the widget.
- Verify the `Modules/Thank with Google/Common/SupporterWall` Storybook story with both states.
- Verify one there is only _one_ sidebar on the site and all sidebars are selected, the name of that sidebar appears instead of the text "All sidebars"

## Changelog entry

* Add the Thank with Google Supporter Wall Widget to settings.

**Comment by techanvil** [comment]
Hi @asvinb, the IB looks good. I just have one question, why do we need the `showSupporterWall` prop? I'm not sure if I am missing something, but as far as I can see the only production-side use of `SettingsForm` is in `SettingsEdit` so we should be able to assume the `SupporterWall` component will always be rendered...

**Comment by asvinb** [comment]
Good catch @techanvil , you're right. I thought it was part of the setup flow for that module. IB updated!

**Comment by techanvil** [comment]
Nice one @asvinb!

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A new section Supporter wall widget has shown up among the settings.
- The new section is displayed  according to the ACs and Figma
  - It shows a simple description text according to the Figma designs if no widget is placed.
  - It shows the widget position(s) if a widget is placed.
- The link to the widget settings is visible, shows Activate/Edit accordingly, and opens in a new tab.
- The `Modules/Thank with Google/Common/SupporterWall `Storybook story is aspected in both states.
- Tested on desktop and small screen sizes. 
- Checked to make sure the new area it doesn't appear when you first customize TwG.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/188590550-551d8b8d-b51c-4a0c-92d6-7f0d00352b84.png)
![image](https://user-images.githubusercontent.com/73545194/188590575-fea1b7ca-c5f5-47f6-8a96-33bc5ebdbcd7.png)
![image](https://user-images.githubusercontent.com/73545194/188590592-c510b89d-c862-4bb5-abbb-1412b9702bc9.png)

</details>

**Comment by felixarntz** [comment]
## Approval ⚠️ 

@nfmohit @tofumatt One tiny tweak to make here: We should restrict the "All sidebars" special case to only show when there are at least 2 sidebars in total. If the site has only 1 sidebar and that is populated we should rather show just that sidebar name like usually.

**Comment by tofumatt** [comment]
@felixarntz Makes sense, thanks! I've added a small follow-up PR against `main` for the fix 👍🏻

**Comment by aaemnnosttv** [comment]
I confirmed the change when reviewing so this doesn't need to go through full QA again 👍 

Thanks all!

**Comment by nfmohit** [comment]
Thank you for pointing that out, @felixarntz!

Thank you for addressing this in my absence, @tofumatt!
