### ISSUE TITLE
Settings view label is incorrect for the Type: Fixed position choices

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5737]
## Description

The settings view currently shows "Prominence" as the label for the second option which varies based on the "Type" choice. Prominence should only be shown for the "Overlay" type selection where as **Position** is the proper label for choices related to the "Fixed" type selection.

### Steps to reproduce

- Go to connected Services>TwG settings
- Select Type -Fixed and it's position
- Confirm changes
- Check updated changes on settings page 
- Label is 'Prominence' instead of 'Position'

### Screenshots

![Position bug](https://user-images.githubusercontent.com/93320881/186724200-ca542fa3-0356-46dc-a257-91d89b236671.png)

![Position bug 2](https://user-images.githubusercontent.com/93320881/186724228-7a4c5221-6750-4d7a-9e54-c77e152d08b1.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The settings view for TwG should be updated such that only `Prominence` **OR** `Position` is displayed (just as in the edit view), based on the current selected **Type**
	* If `Type: Overlay` is selected, show only `Prominence` and its respective value
	* If `Type: Fixed` is selected, show only `Position` and its respective value

## Implementation Brief

First, create a utility function to determine the placement type. This will be created in `assets/js/modules/thank-with-google/util/settings.js`.

- Move the `TYPE_OVERLAY` and `TYPE_FIXED` consts from `assets/js/modules/thank-with-google/components/common/TypeRadio.js` to `assets/js/modules/thank-with-google/util/settings.js`.
- Create a new function `getPlacementType` in `settings.js`.
  - This should take a `ctaPlacement` argument.
  - If `ctaPlacement` is falsey, return `null`.
  - If `ctaPlacement` starts with `'static'`, return `TYPE_FIXED`.
  - Otherwise, return `TYPE_OVERLAY`.
- Replace the two places we currently check for a substring of `'static'` with calls to the new function.

https://github.com/google/site-kit-wp/blob/a713aa42507d351c2bda2776c843167becae01c4/assets/js/modules/thank-with-google/components/common/CTAPlacement.js#L38

https://github.com/google/site-kit-wp/blob/a713aa42507d351c2bda2776c843167becae01c4/assets/js/modules/thank-with-google/util/settings.js#L109

Again in `assets/js/modules/thank-with-google/util/settings.js`, rename the following functions to improve clarity:

- Rename `getType` to `getPlacementTypeLabel` - this is to help distinguish it from the new `getPlacementType` function.
- Rename `getProminence` to `getPlacementLabel` - this is because it returns labels for both Prominence and Position types. "Placement label" is a generic term we can use here.

In `assets/js/modules/thank-with-google/components/settings/SettingsView.js`:

- Update the hard-wired _Prominence_ label to instead use a call to `getPlacementType`, displaying _Prominence_ for `TYPE_OVERLAY` and _Position_ for `TYPE_FIXED`.

### Test Coverage

- Add tests for `getPlacementType`, and update the tests for the renamed functions.
- Update any failing VRT tests.

## QA Brief

* Ensure that the `twgModule` feature flag is enabled from the tester plugin.
* Go to `Site Kit -> Settings`.
* Activate the `Thank with Google` module.
* Open the `Thank with Google` module accordion and click on `Edit`.
* Verify that the settings view for TwG only shows `Prominence` **OR** `Position`, based on the current selected **Type**
	* If `Type: Overlay` is selected, shows only `Prominence` and its respective value.
	* If `Type: Fixed` is selected, shows only `Position` and its respective value.

## Changelog entry

* Fix placement label issue on the Thank with Google settings page.

**Comment by tofumatt** [comment]
I like it! 👍🏻

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified :**

- If Type: Overlay is selected, shows only Prominence and its respective value.
- If Type: Fixed is selected, shows only Position and its respective value.

<details>

![image](https://user-images.githubusercontent.com/94359491/187644229-60c6e907-97c5-4bdb-8431-6ee3a38a5b36.png)

![image](https://user-images.githubusercontent.com/94359491/187644294-774e7c9b-3b65-4a13-8efa-295e66e9412d.png)

</details>
