### ISSUE TITLE
After connecting TwG, the service appears as "Not connected" until customised. Revise the wording on this screen

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5738]
## Feature Description

If you connect TwG, you'll encounter a "Congratulations" notice (as per the screenshot attached). If a user exits this screen, or presses the cancel button, the module will appear as "Not connected" if checking the status within Site Kit. 

In order to avoid confusion, with users possibly unsure of what account is active (with the module not connected), consider revising the below text:

Congratulations!
Your account is now active. To get started, customize the appearance of Thank with Google on your site.

To something like the below:

Set up almost complete!
Thank with Google is now active. Next you'll need to customize the appearance on your site to complete set up.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Update the text to the following:
* Heading: _Setup almost complete!_ 
* Content: _Thank with Google is now active. To complete setup, customize its appearance on your site._
* CTA: _Customize Thank with Google_

## Implementation Brief

- In `assets/js/modules/thank-with-google/components/setup/SetupPublicationActive.js`:
    - In the `<SetupPublicationScreen />` component, update the props:
	    - `title`: as mentioned in `Heading` in the ACs (translatable).
		- `description`: as mentioned in `Content` in the ACs (translatable).

### Test Coverage

- In `assets/js/modules/thank-with-google/components/setup/SetupMain.test.js`, update the expected text content to match the text mentioned in `Content` in the ACs for the `should render the publication active screen if the current publication onboardingState is 'ONBOARDING_COMPLETE' and the module setting publicationID is not set` test case.
- Update VRT scenarios if required.

## QA Brief

* Connect TwG for the first time and verify the updated wording of the CTA/message after initial connection is complete (just before the Customise TwG form appears).

## Changelog entry

* Update the wording on the Thank with Google "setup publication" screen.

**Comment by FlicHollis** [comment]
For @marrrmarrr and Seba to pick up with Josh next week.
cc @eclarke1

**Comment by marrrmarrr** [comment]
@aaemnnosttv added the new copy in the ACs (adjusted from what was suggested in the issue description).

**Comment by eclarke1** [comment]
Thanks @marrrmarrr moving this over to IB

**Comment by techanvil** [comment]
IB :white_check_mark:
