### ISSUE TITLE
'No account' setup step copy inconsistent with design

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5739]
## Bug Description

The copy on the 'No account' splash screen does not match Figma.

- [Current implementation Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup--publication-action-required)
- [Design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A10388)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy for the "No account" set up step should match the design, eg: "To get started, create an account. Currently available only in the US. If setup failed because you're outside the US, disconnect Thank with Google in your Settings."
	* All other steps should match as well but this one seems to be the only one which is not consistent

## Implementation Brief

In `assets/js/modules/thank-with-google/components/setup/SetupCreatePublication.js`:
* Update the "To get started, create an account. Currently available only in the US." copy to match the one provided in the [Figma sketch](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A10388), eg "To get started, create an account. Currently available only in the US. If setup failed because you're outside the US, disconnect Thank with Google in your Settings."

### Test Coverage

* Update the test in `assets/js/modules/thank-with-google/components/setup/SetupMain.test.js` with the new copy 

## QA Brief

- Ensure the `twgModule` feature flag is enabled.
- Using the tester settings plugin, set `NONE` to `Force Thank with Google publication status`.
- Set up TwG and ensure the description copy matches the one in the Figma design in the create publication screen.
- For CR, ensure [this story](https://google.github.io/site-kit-wp/storybook/pull/5773/?path=/story/modules-thank-with-google-setup--create-publication) matches the copy in the Figma design.
- For QA, ensure [this story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup--create-publication) matches the copy in the Figma design.

## Changelog entry

* Update copy on the Thank with Google "No account" setup step.

**Comment by aaemnnosttv** [comment]
@marrrmarrr would you please confirm this copy is correct?

**Comment by marrrmarrr** [comment]
@aaemnnosttv the [copy in Figma](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A10417
) has an extra sentence covering a corner case where we can't tell from the API response that the person already tried to do the setup and was blocked because they're not in the US. Confirming that should be the copy in the product.

**Comment by eclarke1** [comment]
Thanks @marrrmarrr moving to IB to implement the copy as per this [design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A10388)

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The description copy matches the one in the Figma design in the create publication screen.
- The [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup--create-publication) matches the copy in the Figma design.

![image](https://user-images.githubusercontent.com/73545194/188249258-320eef84-17cf-4e65-98ed-081dec4c7633.png)
