### ISSUE TITLE
Setup screen graphic is smaller than designed

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5740]
Setup screen SVG looks smaller than the Figma design. See actual screen and Figma design screens below:

<img width="320" alt="Actual screen" src="https://user-images.githubusercontent.com/93320881/186726593-97dbc5ba-6f4a-415d-9672-1136eb4898a3.png">

<img width="320" alt="Figma design" src="https://user-images.githubusercontent.com/93320881/186726613-39b4711d-5770-4638-85c8-a2f8208f44e0.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The size of the rendered `graphics/thank-with-google-setup.svg` graphic on setup screens should be updated to be consistent with the design (currently 391x222 but confirm in doc)

## Implementation Brief

* Update dimensions of `ThankWithGoogleSetup` for consistency with the design

### Test Coverage

* No additions; VRT will likely need regenerating for TwG scenarios with this graphic

## QA Brief

- Go to Thank with Google module setup screen.
- Ensure the SVG graphic size matches the Figma design.

<img width="1289" alt="Screenshot 2022-09-02 at 9 15 35 PM" src="https://user-images.githubusercontent.com/24408261/188190937-2d5427ae-814e-435f-953f-5471f9edfb85.png">

## Changelog entry

* Correct the size of the Thank with Google setup graphic.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- According to the figma designs the SVG graphic for TwG should be `325 x 206`.  I went through the setup screens and confirmed that the SVG matches the designs.

![image](https://user-images.githubusercontent.com/73545194/188249652-f5474a7a-8540-42ac-bc9b-92f6391e41fc.png)
