### ISSUE TITLE
Remove unused ModulesList component

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5741]
## Feature Description

It appears `ModulesList` is no longer used, and should be removed from the codebase.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Confirm `ModulesList` is not in use, and remove it and any related, unneeded code (`ModulesListItem`, stories, etc).

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Created with AC, please review! cc @aaemnnosttv @felixarntz

**Comment by aaemnnosttv** [comment]
We already have an issue for this, which stalled out: https://github.com/google/site-kit-wp/issues/5471 (the similarity of issue number is quite remarkable). Closing in favor of that one 👍
