### ISSUE TITLE
Fixed position Thank CTA elements may appear outside content bounds 

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5743]
Seeing the Thanks button inline with my post/layout, but then another element outside the margins of my site. It looks "off" to me on desktop:

<img width="320" alt="Desktop" src="https://user-images.githubusercontent.com/93320881/186729370-596ba8be-676b-4e27-9a13-7927049cb38d.png">

On mobile it stacks these buttons, which seems a bit crowded as well.

<img width="228" alt="Mobile" src="https://user-images.githubusercontent.com/93320881/186729455-f9970ce7-bee7-4457-a858-0508007797fb.png">

From @felixarntz : I suggest we fix this by simply wrapping our initial markup in a div. I tested that locally and it works like a charm.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG CTA button and counter should appear within the "main content" bounds in the theme's layout.
    * Changing the markup or styling in minimal ways to achieve this is perfectly fine, e.g. the two placeholder tags with the custom attributes could be wrapped in another container.
    * Note that the TwG JS library overwrites some attributes, so this has to be accounted for in the solution here as well.

## Implementation Brief
* Using `includes/Modules/Thank_With_Google/Web_Tag.php`,
	* Update `cta_placeholder` within `update_the_content` to wrap the existing HTML markup within a `div`.

### Test Coverage
* No new tests to be added.

## QA Brief

- Set up Thank with Google on a site with an active publication.
- Ensure that you are viewing from a US IP address in order for Google's TwG script to work properly.
- Navigate to a WordPress page where the TwG CTA is visible, e.g. a single post or page.
- The CTA buttons should appear within the bounds of the content.

For example:

![image](https://user-images.githubusercontent.com/18395600/187486929-7efe64f7-7e2c-4333-a3b4-02c1733ef6ff.png)

_Note, the buttons will appear slightly out of alignment with each-other and could do with a bit of spacing too. This will be addressed as part of issue https://github.com/google/site-kit-wp/issues/5744._

## Changelog entry

* Add wrapping element to inline Thank With Google CTA button and counter.

**Comment by tofumatt** [comment]
Nice and simple, I dig it 🙂 

IB ✅

**Comment by wpdarren** [comment]
QA Update: 

**Verified:**

- The CTA buttons appear within the bounds of the content when the `Type` is Fixed.
- The CTA buttons still appear as an overlay when the  `Type` is Overlay.
- Checked the CTA buttons on desktop and mobile. No styling issues found. 
- Tested with a few popular WordPress themes.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/187651465-c324144e-378d-4e6c-9d32-6bdabd56e4af.png)
![image](https://user-images.githubusercontent.com/73545194/187651489-144f8d3e-83f8-412d-8489-33f6f9e7d758.png)

</details>
