### ISSUE TITLE
Publications endpoint returns non-public properties in response

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5745]
This may be an artifact of the built client library we're using as I don't think we've had to do this before, it's a simple fix though.

<img width="320" alt="Example" src="https://user-images.githubusercontent.com/93320881/186730563-cf4aa045-e56a-4e8d-8831-d985fac76f40.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Publications returned from the API should only include public fields
i.e. no fields prefixed with a `*` or relating to internal class names

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/5758

### Test Coverage

* No changes necessary

## QA Brief

This PR is intended to change the structure of the response returned from the SK API endpoint for `publications`.

Once TwG is active, you can run this command in the console from any screen that shows SK stats (e.g. wp or SK dashboards)

```js
await googlesitekit.api.get('modules','thank-with-google','publications',{},{useCache: false})
```
Try this command in the console before/after this PR is applied on a site that has a publication for it. On the 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
After looking into this a bit closer, I found I wasn't able to reproduce this on other sites and then found this is actually a problem within our Tester plugin rather than in Site Kit, so I'll open a change for this there. If we decide to make changes here, it applies to all other modules that return API models, not just TwG.
