### ISSUE TITLE
Services page mobile view - badges should be placed one by the other

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5746]
Both "Experimental" and "US only" badges should be placed in the same line, preferably aligned with the logo icon. If it's not possible, then below the "Thank with google" text.

![Badges](https://user-images.githubusercontent.com/93320881/186763743-414a5df3-e5ac-4c1f-8b7e-187e625918c7.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The badges/icons (eg. "Experimental" and/or "US Only") should be in a container that prefers to render in this order:
  1. In its entirety (eg. all items, no wrapping), next to the name of the module
  2. In its entirely (eg. all items, no wrapping), underneath the name of the module (left-aligned with the icon)
  3. Wrapping as they currently do when all badges can't fit on one line
* This approach should _not_ rely simply on breakpoints that work for the English text, because these badges will have varied lengths for different locales. Likely some kind of flex/flex-wrap/grid solution is needed here.

## Implementation Brief

In `assets/js/components/settings/SetupModule.js`:
https://github.com/google/site-kit-wp/blob/develop/assets/js/components/settings/SetupModule.js#L115-L121

* Wrap the two badges in a `div`-container
* Give  the new wrapper a descriptive class name

In `assets/sass/components/settings/_googlesitekit-settings-connect-module.scss`:
* The new wrapper should share the same properties as  the  `.googlesitekit-settings-connect-module__heading` selector

### Test Coverage

* 

## QA Brief

* Check badges in Settings->Connect more services as per screenshots.
<img width="696" alt="Screenshot 2022-09-12 at 21 04 09" src="https://user-images.githubusercontent.com/16494321/189785682-c1ce2f50-b707-4d1b-aa8b-d589a09b0abd.png">
<img width="478" alt="Screenshot 2022-09-12 at 20 58 00" src="https://user-images.githubusercontent.com/16494321/189785691-c04b7ffe-94c2-460f-bcd6-975d3f19b54c.png">

## Changelog entry

* Improve layout of services badges in mobile viewport.

**Comment by makiost** [comment]
Since `googlesitekit-settings-connect-module__heading` is already a flex-wrap container, and the badges are both an inline `span`, we don't need to update any css to achieve the desired effect.

**Comment by FlicHollis** [comment]
Hi @makiost I notice this has gone to IBR but has not yet got an estimate, please could one be added? Thanks!

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified-

- Verified on different viewports.
- Added additional badges.
- Verified for different languages.
- Badges are showing as per AC.

<details>

![image](https://user-images.githubusercontent.com/94359491/191242548-22700769-9e77-4e79-bffc-3bd18467f23c.png)

![image](https://user-images.githubusercontent.com/94359491/191242578-5ad82411-0c6b-4de4-b373-6838e5d5b014.png)

![image](https://user-images.githubusercontent.com/94359491/191242605-b308d1f1-7ab9-4ae1-9320-b5ef9504279c.png)

![image](https://user-images.githubusercontent.com/94359491/191242635-4ccf5c01-fe39-49f7-a2e7-e7e06dce4cff.png)

![image](https://user-images.githubusercontent.com/94359491/191242657-18440036-ed34-44c6-bb27-dcf910725ac8.png)

![image](https://user-images.githubusercontent.com/94359491/191242684-1d4ee9e8-83a0-4a7c-8d9d-0947d52eda45.png)

</details>
