### ISSUE TITLE
Setup banner mobile view doesn't match the Figma design

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5747]
Attached both screenshot for comparison.
Margins are incorrect (especially at the top and can be reduced in the bottom to avoid too much scrolling for the "cancel" action
Elements order is incorrect - logo should be at the top of the page and then the image
"Congratulations" font size is incorrect

![Current State](https://user-images.githubusercontent.com/93320881/186764296-d4785f1e-d7b0-449a-849e-8af6d56c6ccf.png)

<img width="126" alt="Figma Design mob" src="https://user-images.githubusercontent.com/93320881/186764321-174802ca-8e34-4dc5-b48c-39b546f60baf.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The UI for all 4 alternate TwG setup states (before the "Customize" step) should be adjusted to follow the [Figma designs for mobile](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A15342).
    * To clarify, the focus here needs to be purely on the mobile design (or more precisely, once the content there gets stacked on top of each other), not larger viewports.

## Implementation Brief

- In `assets/js/modules/thank-with-google/components/setup/SetupHeader.js`:
    - Relocate the `<Badge />` components to appear before the module title.
	- Adjust the styling of this component so that the badges and the module title do not appear in the same line. They should appear in different lines according to the Figma designs.
- In `assets/js/modules/thank-with-google/components/setup/SetupPublicationScreen.js`:
	- Inside the wrapping `<Fragment />` component, add two `<Cell />` components which should span the entire row on all viewports.
	- Inside the first `<Cell />`, render the `<SetupHeader />` component.
	- Inside the second `<Cell />`, render a `<Row />` component inside which, render two `<Cell />` components which should span the entire row in mobile, and half of the row in tablet and desktop.
	- For the first `<Cell />` component:
	    - Add a `className` of `googlesitekit-setup__icon`.
		- Add an `mdOrder` and `lgOrder` prop with the value of 2.
		- Inside it, display the `<Suspense />` component containing the `<ThankWithGoogleSetup />` component.
	- Inside the second `<Cell />` component, display:
	    - The `div.googlesitekit-setup-module__publication-screen` element containing the `title` and `description` props.
		- The `children` prop.

### Test Coverage

* No tests need to be added/updated.
* Update VRT scenarios if required.

## QA Brief

- Commence testing on a site where Thank with Google is not activated.
- Ensure that the `twgModule` feature flag is enabled in the tester plugin.
- Proceed with activating the Thank with Google module.
- Verify that the structure of the module setup screens matches the Figma designs mentioned in the ACs. More specifically, the difference marked in the issue description should be addressed.

## Changelog entry

* Adjust Thank with Google banner in mobile view to match designs.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by eclarke1** [comment]
Conscious that @wpdarren is currently doing E2E testing on TwG, is this something we want to hold off merging until after TwG launch on Nov 7, or @wpdarren are you comfortable testing this as part of E2E testing?

**Comment by tofumatt** [comment]
I think this is worth merging and is a small change—it's entirely visual and doesn't really impact functionality/testing flow, so I think it's safe to merge even with the E2E testing.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The structure of the module setup screens matches the Figma designs mentioned in the ACs for mobile and small screen sizes. Tested this with an iOS and Android phone/tablet. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/199157887-841cdf15-af3c-43cc-8515-57d80ef6302b.png)
![image](https://user-images.githubusercontent.com/73545194/199157910-50b0e28e-d1c8-41e3-8ada-e0a25eeaadfe.png)
![image](https://user-images.githubusercontent.com/73545194/199157919-3439d498-dafa-4baa-8a6c-b8aab3693226.png)
![image](https://user-images.githubusercontent.com/73545194/199157927-88767f9f-f118-4a69-abc2-418c850ff5e8.png)

</details>
