### ISSUE TITLE
Customize TwG mobile view doesn't match Figma design

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5748]
Large buttons should have rounded corners
"Overlay" and "Fixed" should be one by the other
Margins are incorrect
Color circles have squares around them
Post types - chips should have constant inner margins on both sides regardless of their content

![Customize mobile view](https://user-images.githubusercontent.com/93320881/186764760-6166278b-5e4f-4c66-aafc-42c576bc48db.png)

(Potentially a known issue with Safari)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG "Customize" UI in both setup and settings should be adjusted to precisely follow the [Figma design for mobile](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A15193) (and [desktop](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A11266) where applicable). For example:
    * The large "image buttons" should have rounded corners.
    * Margins should be adjusted where possible (without conflicting with general Site Kit margins though, i.e. we shouldn't have different margin in this setup/settings UI compared to other modules' setup/settings UI).
    * Color circles have squares around them.
    * Post types chips should have constant inner margins on both sides regardless of their content

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
I took a look through the ACs here and compared the existing UI to the Figma designs and… it looks like it's all correct now, aside from the squares around the colour select items, which is a known Safari-only bug that's documented in a separate issue (and affects more than just the Thank with Google settings), see #4994.

<img width="764" alt="CleanShot 2022-09-14 at 15 19 41" src="https://user-images.githubusercontent.com/90871/190180248-3e5fb243-c432-429b-9173-ca9ed7c706e8.png">

I think this issue can be closed in this case, as the issues here have been fixed elsewhere.

**Comment by tofumatt** [comment]
(Not tagging with the release since this can be closed as fixed elsewhere.)
