### ISSUE TITLE
Need help resetting project

### ISSUE THREAD

**Issue by johnfleming** [google/site-kit-wp#575]
Having an issue getting client configuration file.   It takes me directly to Get OAuth Credentials and never show the Client Configuration snippet.   I don't see where to pull this?

Thnaks

**Comment by swissspidy** [comment]
Hi there!

Thanks for your report. There is currently an issue with the OAuth credentials step. We're already tracking this issue in #561 and are working hard on resolving it. In the meantime, a possible workaround has been posted in https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770.

Please follow the conversation in #561 for any updates.

If it's not the same issue as yours, feel free to leave a comment here with some screenshots and we can reopen this issue.

Thanks!
