### ISSUE TITLE
Image Radio Button settings overflow at narrow viewports ~320px

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5752]
Image Radio Button settings overflow at narrow viewports ~320px. 

These settings are problematic around 320px and slightly wider viewports.

![Image Radio Button](https://user-images.githubusercontent.com/93320881/186767070-7bbc2f85-33ab-434c-8ad4-4553fcbadd3b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ImageRadio` component should display at browser viewport widths as low as `320px`. If there is an image inside it, it should be shrunken rather than forcing the component to be wider than the viewport. Beyond `320px` it's not a concern, as beyond that it's reasonable there are layout issues.
* The Thank with Google settings should not overflow over the parent components.

## Implementation Brief

- In `assets/sass/components/global/_googlesitekit-image-radio.scss`:
    - For `.googlesitekit-image-radio`, set `width` to `100%`, but change it to `fit-content` with a minimum viewport width of a tablet (`600px`, accessible via `$bp-tablet`).
    - For `.googlesitekit-image-radio .image-radio .mdc-image-radio__background .mdc-image-radio__content`:
        - Remove the `min-height` property.
        - Set `max-width` to `16.5rem`.
        - Set `width` to `100%`, but change it to `16.5rem` with a minimum viewport width of a tablet (`600px`, accessible via `$bp-tablet`).
- In `assets/sass/components/thank-with-google/_googlesitekit-twg-color-radio.scss`:
    - For `.googlesitekit-twg-color-radio__options .googlesitekit-image-radio`, set `width` to `fit-content`.

### Test Coverage

- No tests need to be added/updated.
- Update VRT references if required.

## QA Brief
* Go to the TwG settings.
* Resize the browser to 320px.
* Ensure all components fit within the content area.

## Changelog entry

* Fix issue with buttons in Thank with Google settings on very small screens.

**Comment by eugene-manuilov** [comment]
IB ✔️
