### ISSUE TITLE
If there are multiple supporter wall widgets only one is visible on the frontend site

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5753]
On creation of two supporter wall widgets, only the first one appears on the frontend website.

<img width="227" alt="Multiple wall widgets" src="https://user-images.githubusercontent.com/93320881/186767527-330932d1-3c41-4c35-af3e-c333706fc8e3.png">

Fix for this may be on JS library side.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing as fixed upstream now 👍
