### ISSUE TITLE
Design of 'Post-type' chips doesn't match design

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5754]
As per screenshot which shows a side by side of plugin <> figma design, the 'Post type' selection chips are different.

<img width="320" alt="post type chips" src="https://user-images.githubusercontent.com/93320881/186768021-1f3b6fb6-3a13-4b93-9386-e6e572bad18a.png">

This should stay consistent with the Dashboard Sharing flow

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The design of the TwG post type chips should be updated to actually follow the relevant [Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A11266), consistently across both setup and settings UI.

## Implementation Brief

- If you take a closer look at the Figma design, you'll notice that the design of the post-type chips actually matches the design of the chips in `<UserRoleSelect />`, i.e. the user role chips used in the Dashboard Sharing settings dialog. In this scenario, it'd be wise to create our own `Chip` component which utilises the same `@material/react-chips` package, but is defined with our own unique class and styles so that it can be seamlessly used across the codebase.
- In `assets/js/components`, create a new file named `Chip.js`. This file:
    - Should export a functional component named `Chip`. This component:
        - Should accept the following props:
            - `id`
            - `label`
            - `onClick`
            - `selected`
            - `className`
            - Assign any other props to a spread variable named `props`.
        - Should return `<Chip />` component from the `@material/react-chips` package returned. 
            - Pass the following props to this returned `<Chip />` component:
                - `chipCheckmark`: `<ChipCheckmark />` component from the `@material/react-chips` package.
                - `data-chip-id`: `id` prop.
                - `id`: `id: prop.
                - `key`: `key` prop.
                - `label`: `label` prop.
                - `onClick`: `onClick` prop.
                - `onKeyUp: `onClick` prop.
                - `selected`: `selected` prop.
                - `className`: Use the `classnames` package to add a unique classname (e.g. `googlesitekit-chip`) and any other classnames passed through the `className` prop.
                - Pass any other props from the spread `props` variable.
- In the `assets/sass/components/global` folder, create a new file named `_googlesitekit-chip.scss` and in the file, add styles for the `_googlesitekit-chip` class. The styles can be taken from the `<Chip />` component in `<UserRoleSelect />`. Include the file in `assets/sass/admin.scss` for it to be built.
- Add a Storybook story for the new `<Chip />` component.
- Replace all instances of the `<Chip />` component from the `@material/react-chips` package with our new `<Chip />` component, just passing through the required props to make them work.
- In `assets/js/modules/thank-with-google/components/common/PostTypesSelect.js`, just before all the post type chips are shown, render an `All` chip, clicking on which should toggle selecting all the available post types. This should be similar to the `All` chip in `assets/js/components/dashboard-sharing/UserRoleSelect.js`:
https://github.com/google/site-kit-wp/blob/078972e3484185293fa7cf732121e65bd6f5bb7a/assets/js/components/dashboard-sharing/UserRoleSelect.js#L221-L233
https://github.com/google/site-kit-wp/blob/078972e3484185293fa7cf732121e65bd6f5bb7a/assets/js/components/dashboard-sharing/UserRoleSelect.js#L142-L149

### Test Coverage

* No tests need to be added/updated.
* Updated VRT references if required.

## QA Brief

* Ensure that the `twgModule` feature flag is enabled from the tester plugin.
* Set up Thank with Google if not set up already.
* Go to the Thank with Google **customisation** screen.
* Scroll down to the `Post types` section.
* Ensure that the design of the chips matches the Figma designs.
* This PR also updates the underlying structure of the Dashboard Sharing role select chips keeping the design the same. Ensure that the role select chips function properly as well.

## Changelog entry

* Update the design of the "chip" components in the Thank with Google settings.

**Comment by eugene-manuilov** [comment]
@nfmohit, thanks for IB, but the idea for this ticket is not to refactor the chip component itself. What we need here is to update styles for chips used in the TwG settings/setup forms to look like on the Figma design and add the `All` chip that once selected, will select all chips (similarly to how it works for dashboard sharing).

**Comment by nfmohit** [comment]
I have included the addition of the `All` chip, but kept the rest as is since the designs for the Dashboard Sharing User Role Select chips are as same as these Post Type chips (as discussed in Slack). Thank you, @eugene-manuilov!

**Comment by eugene-manuilov** [comment]
Thanks, @nfmohit. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@nfmohit I noticed that 'Post type' chip title font size is 14px in Figma, but implemented design have 12px. Is it because DS sharing chips have same font size ?

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified on dev branch using instaWP site and tester plugin.

- TWG post type chips now implemented as per Figma design.
- Verified 'All' chips added and on click of 'All' chips—all the chips gets selected.
- Verified chips design on both settings and customization screen.
- Verified Dashboard sharing role chips functionality. It is working fine.

<details>

Customization screen

![image](https://user-images.githubusercontent.com/94359491/190634256-e8f07751-d9ba-4f02-ae16-551f0d4bdd8a.png)

Settings screen

![image](https://user-images.githubusercontent.com/94359491/190634304-59d88c19-558f-4fca-b08f-2231ec1dbeb7.png)

</details>
