### ISSUE TITLE
Add more info as to what the 'Supporter wall' is in Settings

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5756]
When I do not have the Supporter wall enabled, and I visit the Settings page, there is no explanatory text to advise what it is and why I should enable it. 
We do have that in the 'Supporter wall banner' but I suspect many people will click 'Maybe later' and forget about it, and then return to settings and have no incentive to add.
Could we potentially add a 'i' icon to display a tooltip or something?

<img width="320" alt="Supporter wall" src="https://user-images.githubusercontent.com/93320881/186769952-2056fb78-1cbe-4f6a-b543-0cada70541ba.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the TwG Settings view when no supporter wall widget is placed yet, add some explanatory text below the "Heading" and above the CTA:
_A supporter wall widget shows the list of people who supported your site using Thank with Google._
* This should be visually similar to the related text in the settings edit view

## Implementation Brief

* Inside `SettingsView.js` -> 
https://github.com/google/site-kit-wp/blob/da8f2f9d312a71f0806888968fed60190a6d7bf9/assets/js/modules/thank-with-google/components/settings/SettingsView.js#L94-L105
* Place new`<p>` with text from AC before the `<p>` above.
* Add a new parent container (`div` or `Fragment`) as JSX expressions must have one parent element
* Style `<p>` with text from AC to look similar as here -> https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/thank-with-google/components/common/PositionRadio.js#L67

### Test Coverage

VRT may need update

## QA Brief

* Ensure Thank with Google is set up on your site and that you have not yet added the supporter wall widget.
* Open the Thank with Google settings UI
* In the TwG settings wall view the new block with an info text should appear according to AC. 
* EG -> 
<img width="938" alt="Screenshot 2022-10-10 at 17 32 44" src="https://user-images.githubusercontent.com/16494321/194913761-7c9bef01-190c-4cc9-bec4-7d5dc8643d76.png">

## Changelog entry

* Add more context to the "Supporter Wall" setting in Thank with Google settings.

**Comment by marrrmarrr** [comment]
@aaemnnosttv I added some copy for the Settings, do you think we should open a separate issue for adding a default title to the widget itself?

**Comment by aaemnnosttv** [comment]
Thanks @marrrmarrr – yes, I think we should tackle the changes to the widget separately. I'll open an issue for that 👍 

As for the language, it reads well to me but "everyone" may be slightly inaccurate as I believe it only shows supporters who have chosen to support publicly, correct? That is, you can receive private contributions that wouldn't cause someone to show up on your wall, right? A minor detail but maybe worth clarifying here.

**Comment by aaemnnosttv** [comment]
Following up here – that issue for the default title was created here 👍 

- https://github.com/google/site-kit-wp/issues/5785

**Comment by aaemnnosttv** [comment]
Thanks @marrrmarrr – I tweaked the AC to be specific to the settings view here since the edit mode already has similar text.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev.
- Verified In the TwG settings wall view the new block with an info text appear according to AC.
- When Supporter wall widget is added than info is not appearing under settings.

<details>

![image](https://user-images.githubusercontent.com/94359491/196111907-268dec21-7042-4450-a4f1-41531a3e1611.png)

![image](https://user-images.githubusercontent.com/94359491/196111931-f5a96241-85c8-4f36-86a6-7f4a044af065.png)

</details>
