### ISSUE TITLE
JS console error appears when pressing "Set up now" on the GA4 Activation Banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5760]
## Bug Description

When pressing the Set up now button on the GA4 Activation Banner an error appears in the JS console. See screenshots below.

## Steps to reproduce

1. Ensure the GA4 Activation Banner is visible on the Dashboard. One way to achieve this is to connect Analytics and then delete the `googlesitekit_analytics-4_settings` WordPress option. Session storage may also need to be cleared.
3. Click on **Set up now**.
4. Observe the JS error in the console.

## Screenshots

_1. Press **Set up now**._
![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/57fb2434-2b9b-4354-8582-3f23e213dca9)

_2. The banner successfully moves to the next stage, but an error appears in the console:_
![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/014ef707-b9ae-449c-9212-8bb1cf91344a)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: spotted on 1.82.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No JS console error should appear when pressing **Set up now** on the GA4 Activation Banner.

## Implementation Brief

* Being a trivial commit (3 line change), I have just pushed my changes to the attached PR which can be moved straight to QA if it looks good.
* In `BannerNotification/index.js`, use the `useMountedState()` hook from `react-use` which returns a function that will check if the component is mounted or not.
* In `handleCTAClick()`, use this function to wrap the state update `setIsAwaitingCTAResponse( false );` which should only happen if the component is mounted. (The error occurs on this line as the line before changes the `step` state variable in the `ActivationBanner` component causing the child components to re-render).
 
### Test Coverage

* No new tests required.

## QA Brief

* Follow the steps to reproduce and verify the console error does not show.
* Also verify existing Banner Notifications, especially the [Module Recovery Alert notification](https://github.com/google/site-kit-wp/issues/4823) which should all still work normally (dismissing, clicking on CTAs, etc.).

## Changelog entry

* Prevent updating Banner Notification component state when unmounted.

**Comment by techanvil** [comment]
IB :white_check_mark: 

Good shout on `useMountedState` :+1:

**Comment by jimmymadon** [comment]
@techanvil Nice catch - have updated the PR!

**Comment by techanvil** [comment]
Nice one @jimmymadon.

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

-  The console error does not show when you click on the `Set up now` CTA button.
-  Existing Banner Notifications, i.e. Module Recovery Alert notification should continue to work (see note) 

**Note:** Currently, the zero and gathering data state notifications are not working due to the bug in #5148 which is currently being worked on. I checked to make sure the other banner notifications appeared.

![image](https://user-images.githubusercontent.com/73545194/188596380-7d314a51-04fa-4fb0-83c0-23d576fe015e.png)

![image](https://user-images.githubusercontent.com/73545194/188600989-0ef714a4-4104-4042-a8b5-ea625c6ba307.png)
