### ISSUE TITLE
Update link url on AdSense "We're getting your site ready for ads" set-up landing page

### ISSUE THREAD

**Issue by OisinOConnor** [google/site-kit-wp#577]
### Update 1:
Parse subdomains down to root domains in the deep link to AdSense:
Site Kit currently links to the “Sites” page of AdSense with this link:
https://www.google.com/adsense/new/sites?url={$sitekit-site-url}&source=site-kit
where ($sitekit-site-url) is the **full url** of the WordPress site. 
Change requested: change the value of ($sitekit-site-url) to only display the root domain. Any subdomains or folders will need to be parsed out. e.g. if the WordPress install is on www.example.com, blog.example.com or example.com/blog the inserted value should be **example.com** like so:
https://www.google.com/adsense/new/sites?url=example.com&source=site-kit

### Update 2:

Current URL linked from "Ads":
https://www.google.com/adsense/new/myads/auto-ads

Change the url that links from "Ads" to:
https://www.google.com/adsense/new/myads/sites/preview?url=example.com
where example.com is the site's URL.

![DazHjhamsjF](https://user-images.githubusercontent.com/6488453/66853282-ce6dea00-ef76-11e9-8629-0a6e17c7ac1b.png)

Screen to update:
### We’re getting your site ready for ads
AdSense is reviewing your site. Meanwhile, make sure you’ve completed these steps in AdSense.

1. Added your site xxx.com in Sites
2. Enabled ads in Ads
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This has already been done as part of the AdSense setup refactoring which happened about a year ago. The expected URLs outlined here are in place.
