### ISSUE TITLE
Don't rely on untranslated whitespace between elements; always localize as much prose as possible

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#5771]
## Feature Description

A quick search of our codebase shows about 20 instances of us using `{ ' ' }` in the codebase. While this isn't _always_ incorrect, we frequently use it to separate two bits of prose that are related or sometimes even part of the same sentence/paragraph/etc.

<img width="270" alt="CleanShot 2022-08-30 at 19 37 07" src="https://user-images.githubusercontent.com/90871/187516818-4ddd3085-ab9f-48ce-91db-c66130febaca.png">

Oftentimes this isn't _hugely_ problematic, but `__( 'Foo bar <a>link text</a>' )` is more localisable than `__( 'Foo bar' ){ ' ' }__( '<a>link text</a>' )`. For context and an explanation, see this comment thread: https://github.com/google/site-kit-wp/pull/5660#discussion_r943462410

We should audit our existing usage of **untranslated** whitespace to separate content and replace it with more i18n-friendly strings where possible.

It could also be worth implementing an ESLint rule that warns/errors when using `{ ' ' }`—this can be disabled per-instance, but would be a warning by default to prevent this happening again in the future.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All `{ ' ' }` whitespaces should be removed from the codebase. (Including in the `tour-tooltips.stories.js` file, which is not translated, but `createInterpolateElement` could still be used for consistently in approach throughout the codebase.)
* All instances of `$ComponentOrTextA{ ' ' }$ComponentOrTextB` should be replaced with `createInterpolateElement( __( '' ) )` such that the whitespace is part of a localisable string and not part of the code directly.
  * See this example for the correct usage with `sprintf`: https://github.com/google/site-kit-wp/blob/2de1085ce6449d0e638aeb1dead14b477de2644f/assets/js/modules/tagmanager/components/settings/SettingsForm.js#L82-L95
  * And without `sprintf`: https://github.com/google/site-kit-wp/blob/2de1085ce6449d0e638aeb1dead14b477de2644f/assets/js/modules/analytics/components/settings/UASettingsView.js#L94-L102

## Implementation Brief

* Replace every instance of `{ ' ' }` with `createInterpolateElement` as outlined in the ACs. There should be 17 instances in total to replace:
<img width="277" alt="CleanShot 2023-01-31 at 23 57 37" src="https://user-images.githubusercontent.com/90871/215910913-e4757f76-9815-4035-8c87-5bfa0d8c9946.png">

The description mentions an ESLint rule, but it'd be an awkward one to create, and since this issue eliminates this usage entirely, it should stick out in the future when done, so we can skip that. 🙂 

### Test Coverage

* No new tests are needed, but all existing tests should still pass.

## QA Brief

* There's no specific flow to QA here because this modifies various small strings to render the same but with a better ability to be translated.
* Things to do to QA these changes:
  * Note any "Learn more" links during setup/onboarding/notifications and make sure they still work/still appear in their usual places.
  * Test new site setup and ensure the site compatibility notices still render correctly.
  * Ensure the "Opt in to Analytics usage" checkbox still appears correctly on mobile and desktop viewports during Site Kit setup.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Agreed, the ESLint rule would probably be overkill in terms of complexity vs problem. We can always revisit again, if we need to scratch that particular itch.

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Thanks @mohitwp   I ran a test on the compatibility notices and looks good. 

Here's one example: 

![image](https://github.com/google/site-kit-wp/assets/73545194/5408cc93-c87b-4971-b600-4c3c4bb17845)

**Comment by tofumatt** [comment]
This was meant to go into Code Review, not QA. I must've clicked on the wrong thing, so moving it back to CR. Apologies for the confusion! 😅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked all "Learn more" links during setup/onboarding/notifications and they still work/still appear in their usual places.
- Tested new site setup and the site compatibility notices still render correctly.
- The "Opt in to Analytics usage" checkbox still appears correctly on mobile and desktop viewports during Site Kit setup.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/ed92c044-d4cf-49d9-ab16-1d53f9541003)
![image](https://github.com/google/site-kit-wp/assets/73545194/4f14bdd8-e637-4fcd-8caf-5b147c3095d3)
![image](https://github.com/google/site-kit-wp/assets/73545194/6faf6b9c-b801-45e1-8906-d8d8f090c79b)
![image](https://github.com/google/site-kit-wp/assets/73545194/632dde94-f6b2-4956-9660-3696bdf50cf9)
![image](https://github.com/google/site-kit-wp/assets/73545194/bcd958fc-4440-453a-a40e-87f06b614748)
![image](https://github.com/google/site-kit-wp/assets/73545194/a5f2fbc1-2fd4-470e-b878-89f69ddbccbc)
![image](https://github.com/google/site-kit-wp/assets/73545194/79eefb1a-435d-4ab6-8a93-63f752850c06)
![image](https://github.com/google/site-kit-wp/assets/73545194/45408cb7-9729-45e3-ba40-c75a0b7131fe)
![image](https://github.com/google/site-kit-wp/assets/73545194/75f38577-c392-4be0-99b3-c9a875f4f0fe)
![image](https://github.com/google/site-kit-wp/assets/73545194/d00b40b3-415f-457c-b940-e0200fc0b779)
![image](https://github.com/google/site-kit-wp/assets/73545194/625eb7a3-2456-4b27-8e3c-b785606caefa)

</details>
