### ISSUE TITLE
Update `setup-node` action use to simplify builds with v3 features

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5786]
## Feature Description

We currently use the `setup-node` GitHub action in many of our jobs, which also includes some extra boilerplate to read the node version from our `.nvmrc` file and then provide that to the action.

As of v3 of the action, it now supports a [`node-version-file`](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file) argument, essentially first-class support for what we're currently doing.

The action also can handle dependency caching now as well without the need for using `actions/cache` separately which can further simplify our usage. See https://github.com/actions/setup-node#caching-global-packages-data

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All use of the `setup-node` GitHub Action should be updated to use `v3`
* The manual steps for reading the `.nvmrc` file should be removed in favor of the `node-version-file` param
* The `actions/cache` steps for NPM dependencies should be removed in favor of the new `cache` param

## Implementation Brief
* Update `*.yml` files,
	* which make use of the `setup-node` GH action to use `v3`, i.e updating `actions/setup-node@v1` to `actions/setup-node@v3`
		* add the `node-version-file` option with the value set to `.nvmrc` as per https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file
		* add the `cache` option, with the value set to `npm` as per https://github.com/actions/setup-node#caching-global-packages-data
	* Remove any `Cache Node - npm` steps which make use of the `actions/cache` action.
	* Remove any `Read .nvmrc` steps

### Test Coverage

* N/A

## QA Brief

- This can be tested during the CR; hence the QA process could be skipped.
- Ensure the Setup Node action runs successfully using the Node version from the `.nvmrc`.

## Changelog entry

* Update and simplify GitHub workflows to use v3 version of `setup-node` action.

**Comment by kuasha420** [comment]
Nice find! New version of `setup-node` also has built in `npm` caching, is that something to include here as well so we can get rid of our custom one as well?

**Comment by aaemnnosttv** [comment]
> New version of `setup-node` also has built in `npm` caching, is that something to include here as well so we can get rid of our custom one as well?

Oh nice! I'll update the definition here to be more about `setup-node` than the specific parameter 👍

**Comment by aaemnnosttv** [comment]
@kuasha420 AC added – it's rather explicit so not sure there's really much to add for an IB here but maybe a list of affected workflows to be updated would be sufficient along with the estimate 👍 

FYI it looks like `cache: 'npm'` (this is also used in their example [here](https://github.com/actions/setup-node#caching-global-packages-data)) is all that's needed for the caching as it uses a few lockfile patterns [by default](https://github.com/actions/setup-node/blob/9f3a02bbd17adc05b078145bb8f676c84be77e89/src/cache-utils.ts#L16) so it seems even simpler to use 😄

**Comment by aaemnnosttv** [comment]
> * add the `node-version-file` option with the value set to `.nvmrc` as per [actions/setup-node@`main`/docs/advanced-usage.md#node-version-file](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md?rgh-link-date=2022-09-03T02%3A34%3A24Z#node-version-file)

Thanks @asvinb, this might not be entirely clear that this option replaces existing manual reading of the `.nvmrc` file and providing that to the setup action. This could potentially leave an unnecessary step behind in the process. I'll tweak this part to clarify to move this forward but otherwise this looks good 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by techanvil** [comment]
Have checked that workflows run successfully having merged this to `develop`.

![image](https://user-images.githubusercontent.com/18395600/196987722-ffd023ae-c6eb-4686-b732-db5001e7f737.png)

Also drilled into them to verify they fully ran e.g.

![image](https://user-images.githubusercontent.com/18395600/196988351-1061c107-c7ba-4ca7-8625-01a91100acb9.png)

![image](https://user-images.githubusercontent.com/18395600/196988442-d8f22168-f466-46ea-a304-f3682e1d50cf.png)
