### ISSUE TITLE
error show adsense account in my all sites 

### ISSUE THREAD

**Issue by Azharhn** [google/site-kit-wp#5794]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Hi @Azharhn 

Thanks for opening a GitHub issue. So we can determine more on this please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) over on the plugins WordPress support forums, where we provide initial support assistance. 

Please include all relevant details in order for us to assist. This may include [sharing your Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/), so we can check your site and your current AdSense status. 

I'll close this GitHub issue, and keep an eye out for your topic. If we can determine a bug, or something that should be addressed within the plugin we can reopen this issue.
