### ISSUE TITLE
Erro: Quota Error: User Rate Limit Exceeded.

### ISSUE THREAD

**Issue by iconio** [google/site-kit-wp#5797]
## Bug Description

When trying to connect with the Analytics Service a error happens:
*Erro: Quota Error: User Rate Limit Exceeded.*

In my case, there is only 3 property in 1 account.

## Steps to reproduce

1. Install SiteKIT Wp plugin
2. Connect with your Google Account
3. Setup the Analytics service

## Screenshots
https://ibb.co/9hL2C6c

## Additional Context

 - PHP Version: 7.4.28
 - OS: Linux
 - Plugin Version: 1.82.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Hi @iconio, 

Apologies for the late response. This error which you encountered is a Google Analytics API quota limit, which can occur if you’ve been making configuration changes within Site Kit, even if you have 3 properties in one account. It usually occurs if multiple changes were made within a short period of time.

As the limits refresh every hour, I suspect you're no longer encountering this error. If you run into this, or any further errors you can reach out to us from the [WordPress plugin support forums](https://wordpress.org/support/plugin/google-site-kit/#new-post), where we provide initial support.
