### ISSUE TITLE
"Sign in with Google" to wp-login

### ISSUE THREAD

**Issue by JayHoltslander** [google/site-kit-wp#58]
> We plan to expand the plugin’s capabilities and integrations in the future; we’d love to get your feedback on which products and features we should prioritize.

Would be nice if Site Kit could add a "Sign in with Google" button option to Wordpress' login screen.

[![](https://developers.google.com/identity/images/btn_google_signin_dark_normal_web.png)](https://developers.google.com/identity/sign-in/web/)

Currently this [freemium plugin](https://wordpress.org/plugins/google-apps-login/) (No affiliation) adds this functionality.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by tofumatt** [comment]
I don't think this is really inline with the current goals of Site Kit, which is largely around easy setup and integration of Google products with a WordPress website. While signing in with Google is a service, it would be quite separate from the rest of Site Kit, and also require installing Site Kit to use anyway 😄

I'll close this for now as it's not on the roadmap and probably out-of-scope for Site Kit, but thanks for the suggestion 🙂
