### ISSUE TITLE
Problem in getting client configuration

### ISSUE THREAD

**Issue by emindsca** [google/site-kit-wp#580]
![Screenshot (82)_LI](https://user-images.githubusercontent.com/55710920/65448539-aa772700-de56-11e9-92df-14fa4e8e2991.jpg)

As in the attached image instead of the client configuration, I am getting the API key. Please tell me how to get the client configuration.

**Comment by dragonunit** [comment]
I am getting the same issue.

**Comment by Kevin-Abrams** [comment]
Same Issue

**Comment by fellyph** [comment]
I've got the same issue as well.

**Comment by swissspidy** [comment]
Hi all!

Thanks for your reports. We're already tracking this issue in #561 and are working hard on resolving it. In the meantime, a possible workaround has been posted in https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770.

Please follow the conversation in #561 for any updates.

Thanks again.
