### ISSUE TITLE
Enhance TwG HTTPS restriction to be based on home URL rather than current request

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5806]
#5710 implemented logic to hide the TwG module for sites which are not on HTTPS, however it did so in a somewhat unreliable way: The `is_ssl()` function is primarily for whether the current request is HTTPS, not necessarily about how the site is generally configured. More importantly, it means this is focused on how WP Admin is configured rather than the frontend, which is what really matters here.

So we should change this to be based on whether the _frontend_ does use HTTPS or not (via `home_url()`).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The logic to show/hide the TwG module should be changed to be based on whether the home URL uses HTTPS or not (rather than relying on `is_ssl()` and the `HTTP_X_FORWARDED_PROTO` header).

## Implementation Brief

In `includes/Core/Modules/Modules.php`, modify the `should_enable_twg` method with the following:
- Remove the code that checks using `is_ssl()` and `HTTP_X_FORWARDED_PROTO` headers.
- Instead, check if the home URL uses HTTPS using the same logic as `wp_is_home_url_using_https` WordPress built-in function. That's due to the `wp_is_home_url_using_https` function being introduced in WordPress 5.7.0, so we can't use it directly to support older versions of WordPress.

### Test Coverage

- In `tests/phpunit/integration/Core/Modules/ModulesTest.php`, update the `should_enable_twg` method tests for the above changes.

## QA Brief

- Testing should be the same as #5710 
- Install the plugin on a site without SSL.
- The Thank with Google module will not appear in the Settings > Connect More services.
- **QA:Eng**
    * Build the plugin in `development` mode `npm run build:dev`
    * The TwG module should still show up in non-HTTPS sites. i.e. `http://sitekit.10uplabs.com/`

## Changelog entry

* Improve reliability of the check for SSL when determining Thank with Google module availability.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
Hi, @hussain-t 
Do you have any website which don't have SSL certificate and any site where I can manage SSL certificate. I tried InstaWP and TasteWP both not provide option to create site without SSL or to manage this. Also, tried ngrok using local server, but it is also not working.  I tried this command` C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors` which previously was allowing  us to create site without SSL, but it is also not working now. 

cc @wpdarren

**Comment by hussain-t** [comment]
@mohitwp, unfortunately, I don't have any WordPress sites. I think @wpdarren has.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@hussain-t Thank you ! Got website access from @wpdarren. 

I verified this on site without SSL (HTTP) and 'The Thank with Google' module is not appearing in the Settings > Connect More services.

When I put back SSL into the site and logged in again, then the 'The Thank with Google' module starts appearing in the Settings > Connect More services.


**But I've noticed another issue -**
If site don't have SSL and if 'TwG' feature flag is active then after completing set up of site when user navigates to dashboard it shows 'map select' error for 'getSupporterWallPrompt'). I verified this with both Twenty twenty and twenty twenty two theme. I'm getting same error and admin user is not able to access the site kit dashboard due to this error. 
Is this error coming due to "Supporter wall widget banner" ?

cc @wpdarren 

```
``An error occurred while running 'mapSelect': Cannot read properties of null (reading 'getSupporterWallPrompt')
The error may be correlated with this previous error:
TypeError: Cannot read properties of null (reading 'getSupporterWallPrompt')
    at Object.current (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-678a55075ebc683c20ea.js:74:8776)
    at e (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:94087)
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:94252
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:83865
    at Array.forEach (<anonymous>)
    at o (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:83837)
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:82254
    at p (http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:74694)
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:79875
    at http://hivevine.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-2b9feebf5aa70af8ce1d.js:7:77290

Original stack trace:

    in ThankWithGoogleSupporterWallNotification
    in BannerNotifications
    in div
    in Header
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root``
```

<details>

Error on Site kit Dashboard -

![image](https://user-images.githubusercontent.com/94359491/193210085-62615d87-5f42-4274-803f-8532d86f2efd.png)

Settings > connected services (Site without SSL)

![image](https://user-images.githubusercontent.com/94359491/193210242-7cc3f821-9b95-4e4d-9ad7-e7b1903b913f.png)


Settings > connected services (Site with SSL)

![image](https://user-images.githubusercontent.com/94359491/193210348-a6d8cc17-5d26-43d9-b087-585347c39319.png)

**Comment by hussain-t** [comment]
Thanks, @mohitwp. Yes, this is due to #5538. Since you have some observations on that ticket, I can fix the above along with those.

**Comment by mohitwp** [comment]
### QA Update ✅ 

@hussain-t Thank you ! Got website access from @wpdarren. 

I verified this on site without SSL (HTTP) and 'The Thank with Google' module is not appearing in the Settings > Connect More services.

When I put back SSL into the site and logged in again, then the 'The Thank with Google' module starts appearing in the Settings > Connect More services.

Issue I mentioned in the [comment](https://github.com/google/site-kit-wp/issues/5806#issuecomment-1263187236) will get resolve through connected PR of #5538 .


<details>

Settings > connected services (Site without SSL)

![image](https://user-images.githubusercontent.com/94359491/193210242-7cc3f821-9b95-4e4d-9ad7-e7b1903b913f.png)


Settings > connected services (Site with SSL)

![image](https://user-images.githubusercontent.com/94359491/193210348-a6d8cc17-5d26-43d9-b087-585347c39319.png)

**Note** - As per QAB putting tag QA:eng.

</details>

**Comment by nfmohit** [comment]
### QA:Eng ✅ 

- Built the plugin in development mode by running `npm run build:dev`.
- Verified that the TwG module still shows up in non-HTTPS sites. i.e. 1http://sitekit.10uplabs.com/`.
