### ISSUE TITLE
I need the Oauth Credentials but get an API

### ISSUE THREAD

**Issue by jpgif** [google/site-kit-wp#581]
How can i get the code to embed instead of the api key ?
If i paste the api key on the site it says : Unable to parse client configuration values.
Thanks

**Comment by TrueZeal** [comment]
Same thing here. When I click "Get OAuth Credentials" (Big Blue Button)
I get the pop-up with:
Site Kit: Get OAuth Credentials
You're all set!
You're ready to start developing!
YOUR API KEY ****
BUT;
Site Kit beta for developers
says "Unable to parse client configuration values."
if I submit the API Key.

**Comment by swissspidy** [comment]
Hi all!

Thanks for your reports. We're already tracking this issue in #561 and are working hard on resolving it. In the meantime, a possible workaround has been posted in https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770.

Please follow the conversation in #561 for any updates.

Thanks again.
