### ISSUE TITLE
Inconsistent `Date` usage resulting in different values between timezones

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5816]
## Bug Description

This came to my attention from a date-related test failing for me locally (currently in EST) but not in CI or for others. After taking a closer look, I found the problem which we have solved elsewhere but wasn't used in this place which took someone running it in the right timezone to expose this flaw.

The problem has to do with how `Date` parses a string given to it, and how different inputs can affect the resulting timezone the date has in unexpected ways. This particularly affects the format Site Kit uses, which is why we introduced the `stringToDate` utility.

These two lines instantiate a `Date` directly and are subject to this bug:
https://github.com/google/site-kit-wp/blob/58166ba87f6de1c03d1809d974096b26d1c08148/assets/js/modules/adsense/util/data-mock.js#L252-L253

Looking

## Steps to reproduce

1. Run `npm run test:js -- adsense/util/data-mock` in the EST timezone

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/189247781-34a1a96e-1bca-43f7-b0eb-bc57d685cf0c.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instantiation of `Date` objects from a date string such as `YYYY-MM-DD` should be updated to use the `stringToDate` utility

Note: `adsenseDateToInstance` looks similar but takes an object and should be kept.

## Implementation Brief

- In `assets/js/modules/adsense/util/data-mock.js`, update the `startDate` and `endDate` to use the `stringToDate` utility function from `assets/js/util/date-range/string-to-date.js` instead of `new Date()` constructor.
- Update all the `Date` instantiations that take a date string as an argument to use the `stringToDate` utility function instead of the `new Date()` constructor.
- Note: To test it using the EST timezone, add the following script in the `package.json` and run it:
```js
"test:jstz": "TZ=America/New_York cross-env BABEL_ENV=test NODE_ENV=test jest --config=tests/js/jest.config.js --passWithNoTests"
```

### Test Coverage

* Some tests will be updated as part of the code to be changed
* No added tests or removals

## QA Brief

* Date handling across the plugin has been updated, so test date picker functionality and ensure no regressions exist and that the date ranges selected by the plugin are as-expected/consistent with the behaviour before this issue. Essentially: date handling in the plugin should not change 🙂 

## Changelog entry

* N/A.

**Comment by aaemnnosttv** [comment]
@hussain-t while this issue was originally raised around the failure I experienced in `adsense/util/data-mock.js`, the problem exists everywhere we're using the date constructor in that way, which is why the ACs call for this to be updated everywhere 🙂

**Comment by hussain-t** [comment]
Thanks, @aaemnnosttv. I have updated the IB generically without much detail specifying each file since there are many instances. I have slightly bumped up the estimate.

**Comment by aaemnnosttv** [comment]
Thanks @hussain-t – please remember to always populate the Test Coverage section even when no changes are needed as is the case here. I'll update this for now, to move it forward.

IB ✅

**Comment by tofumatt** [comment]
(Since @techanvil is out I'll take over the code review for this issue 👍🏻 )

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

For the main and entity dashboard, I compared the data between latest version and develop for 7, 14, 28 and 90 days. The two matched as expected. I also selected the different date periods and made sure that the all traffic pie chart and data tabs continued to work with no regressions.

**Comment by aaemnnosttv** [comment]
Everything seems to be working fine here. I noted a few small instances where the replacement seems to have been missed here https://github.com/google/site-kit-wp/pull/5880#pullrequestreview-1133502404 but we can handle that in a follow up.

**Comment by aaemnnosttv** [comment]
On second thought, it would be much quicker to fix this now with a quick PR 😄

**Comment by aaemnnosttv** [comment]
My mistake, this is all good! 👍
