### ISSUE TITLE
Unable to parse client configuration values.

### ISSUE THREAD

**Issue by GitHubDarci** [google/site-kit-wp#582]
This is the second site I have tried to authorize and I have the same message
![Screenshot 2019-09-21 10 15 22](https://user-images.githubusercontent.com/55635705/65470910-f8256c80-de21-11e9-95c5-5f56e945656d.png)
![Screenshot 2019-09-23 16 48 57](https://user-images.githubusercontent.com/55635705/65470968-2d31bf00-de22-11e9-9750-3a55c2aa7ad4.png)
![Screenshot 2019-09-23 16 49 15](https://user-images.githubusercontent.com/55635705/65470971-328f0980-de22-11e9-9770-3fd1ec36b5b0.png)

**Comment by swissspidy** [comment]
Hi there!

Thanks for your report. We're already tracking this issue in #561 and are working hard on resolving it. In the meantime, a possible workaround has been posted in https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770.

Please follow the conversation in #561 for any updates.

Thanks again.
