### ISSUE TITLE
Ignore deprecated message from WP core in 4.7

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5825]
## Feature Description

Our E2E test for WP 4.7 is raising a PHP deprecation notice from core as [seen here](https://github.com/google/site-kit-wp/actions/runs/3038633991/jobs/4892584906#step:13:266):

```
PHP Deprecated:  The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /var/www/html/wp-admin/includes/class-wp-ajax-upgrader-skin.php on line 103
```

This should be added to our list of ignores for WP 4.7 as deprecations from core shouldn't cause our E2E tests to fail.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E tests should not fail due to PHP deprecation notices raised by WP core

## Implementation Brief

* Add the offending deprecation notice in the description above to the list of ignores for WP 4.7 in `tests/e2e/config/wordpress-debug-log/log-ignore-list.js`

### Test Coverage

* No new tests needed; E2E tests for WP 4.7 should now all pass.

## QA Brief

* No QA needed; WP 4.7 E2E tests passing in CI is sufficient QA.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
Moving straight to Approved - have confirmed the deprecation notice is no longer appearing in the log, see https://github.com/google/site-kit-wp/actions/runs/3041451084/jobs/4898574008
