### ISSUE TITLE
Unable to parse client configuration values in Site Kit setup

### ISSUE THREAD

**Issue by appmyhome** [google/site-kit-wp#583]
after generating a "client configuration snippet" key and copying it into the client configuration dialog box, Site Kit gives this error, "Unable to parse client configuration values".

**Comment by swissspidy** [comment]
Hi there!

Thanks for your report. We're already tracking this issue in #561 and are working hard on resolving it. In the meantime, a possible workaround has been posted in https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770.

Please follow the conversation in #561 for any updates.

Thanks again.
