### ISSUE TITLE
Reduce font size on Idea Hub Connect Service screen

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5831]
## Bug Description

On the Idea Hub service connection screen the font sizes are inconsistent. 

I would like to see the font size reducing for the track my usage text.

`I agree that Idea Hub will track my usage of the feature (e.g. creating a draft; saving/dismissing ideas) in order to provide better idea suggestions`

## Screenshots

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/5c67182f-2b1f-4350-b9b9-2d29b384f77a)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing this one in favor of #6235
