### ISSUE TITLE
get_transient( 'googlesitekit_setup_token' ) called on every page load

### ISSUE THREAD

**Issue by maciejmackowiak** [google/site-kit-wp#5836]
## Bug Description
Currently plugin checks for googlesitekit_setup_token transient on every page load.
It adds unnecessary db query(if there is no object cache of course) just for maybe outputing that meta tag.
Shouldn't that be handle better?

https://github.com/google/site-kit-wp/blob/develop/includes/Plugin.php#L119

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Hi @maciejmackowiak, 

Thanks for opening a GitHub issue. I'll check your query with the team, before providing an update on this here.

**Comment by bethanylang** [comment]
@maciejmackowiak Thanks again for getting in touch! The impact of this transient being loaded is very, very small, so at this time we don't plan to remove it. If you're seeing that it's having a larger impact on your site, please do let us know by creating a <a href="https://wordpress.org/support/plugin/google-site-kit/">new topic on our support forum</a> with more details about what you're seeing, and we'd be happy to do some troubleshooting with you. Thank you!
