### ISSUE TITLE
Conflict with Updraft Backups

### ISSUE THREAD

**Issue by webspacesau** [google/site-kit-wp#584]
## Bug Description

My scheduled backups using Updraft Backups are failing since installing Google Site Kit. See error message:
Error Message: Argument 1 passed to Google_Client::__construct() must be of the type array, object given, called in /var/www/rocketstack/wp-content/plugins/updraftplus/methods/googledrive.php on line 825 (Code: 0, line 92 in /var/www/rocketstack/wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php)

## Steps to reproduce

If I deactivate Site Kit then Updraft starts working again

## Screenshots

![image](https://user-images.githubusercontent.com/32596056/65487042-5b2e0680-dee9-11e9-9e13-dd6fea3dc5db.png)

## Additional Context

 - PHP Version: 7.3
 - OS: Ubuntu 18
 - Browser Chrome
 - Plugin Version 1.06
 - Device: PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Thanks a lot for your report!

We're aware of this current incompatibility and are tracking the progress of fixing this in #246. Please follow that issue for any updates.
