### ISSUE TITLE
Add new stylelint rule to disable selector concatenation.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#5846]
## Feature Description
We have parts in the code (SASS) where selectors are concatenated.
For e.g https://github.com/google/site-kit-wp/blob/develop/assets/sass/widgets/_widgets.scss#L79-L81
The problem with this approach is although technically there is nothing wrong, this can make the code unreadable over time. Also looking for specific selectors using this approach makes is difficult since we'll need to go through the code, especially if the selectors are deeply nested.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* `.stylelintrc` must be updated so that selector concatenation are flagged.
* There should not be any errors/warnings in the codebase as a results of updating `.stylelintrc`

## Implementation Brief

* Inside `wp-content/plugins/google-site-kit/.stylelintrc`:
    * Add the following rule:  `"selector-nested-pattern": "^(?!&__|&--|&-|&_).*"`
* Run `npm run lint:css` and fix all style erros

## QA Brief

* Smoketest following views to verify the views look good/unchanged after refactoring the styles.
  * Site Kit setup wizzard
  * Admin bar
  * Analytics 4 Banner
  * Dashboard
    * PageSpeed
    * Report Metrics
    * Charts
  * Settings
  * User input survey
  * Analytics Edit-Settings

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Awesome, doing this will make it way easier to search through the code 👍🏻 

Moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
@derweili, could you please add QAB?

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.

Tested below views to verify the views look good/unchanged after refactoring the styles.
- Site Kit setup wizzard
- Admin bar
- Analytics 4 Banner
- Dashboard
- PageSpeed
- Report Metrics
- Charts
- Settings
- User input survey
- Analytics Edit-Settings
- Also, done some additional checks related to analytics settings, GA4 activation banner on different dates.
- Tested site in zero data state and gathering view.
- Tested dashboard sharing functionality.

Note : When we set up analytics through GA4 activation banner then it's creating 2 properties and it's a known issue https://github.com/google/site-kit-wp/issues/6529
