### ISSUE TITLE
Error: Invalid site state null

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5852]
## Bug Description

~~One user is~~ Multiple users are encountering a "Error: Invalid site state null" message when trying to connect the AdSense module. It occurs before OAuth, and without any browser console errors. 

The initial user shared a recording of their experience within their support topic. This can be viewed [here](https://www.youtube.com/watch?v=mz4KbnxyYuE&feature=emb_title). 

There is a page loader evident on their site, which may be contributing to checking their site. There may also be issues with the PHP version (8.1.10) which remains in Beta support for their version of WP, although [during internal testing](https://github.com/google/site-kit-wp/issues/5852#issuecomment-1286002660) I wasn't able to recreate this issue with PHP 8.1 and 2 subdomain sites.

Note also that this can occur when an AdSense account and site are approved, as evident from other reports (see below impacted users). This doesn't stop ads from appearing, or stop Site Kit from placing the AdSense snippet. 

One impacted user encounters this error on one subdomain site but not another. 
- [SH info from site impacted](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhLVRalzDKjnv12yfJ5XK2vAvhGWzDATWilQT1Kapk-Q1z8RKYjzpbHZgtVeQSkPcs)
- [SH info from site not impacted](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiawNX_iz7vg525nbo_TXb0kvzFEpczPv22ceAyujrW1X9BsfrYkpr9qGbwARQb8NU), with AdSense set up complete

Based on the above user, who encounters this on one site, it looks like the response from the site check displays differently. 
Subdomain site where this doesn't occur:
```
adsense_account_status: ready
adsense_site_status: ready
adsense_use_snippet: yes
```

Subdomain site where this does occur:
```
adsense_account_status: ready
adsense_site_status: none
adsense_use_snippet: yes
```

## Steps to reproduce

Unable to recreate so far. [Internal testing with various scenarios performed here](https://app.asana.com/0/1200206407034013/1203005805095331). 

## Screenshots

<img width="905" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/b71ddad0-1838-4360-96b2-b76f13e95ed5">

## Additional Context

 - Original report 
 - PHP Version: 8.1.10 (Awaiting a user check with 7.4)
 - Site Kit 1.83.0
 - The users AdSense account status is "ready"
 - No issues connecting the other modules
 - Nothing output in their SH status
 - [SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhQGK0YJUKL1cHpF6sqJpSu3SQTUdNvUenRY5vCPQyF2KfIDEOODe7mKSHw1xdJXkk)

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check - The same occurs with only SK active
- [x] Front end check (mixed content, minified content, combined JS) - Nothing obvious, REST endpoints accessible
- [x] No CND used
- [x] Incognito mode - The same occurs
- [x] Checked users Site Health info, no identified causes
- [x] Additional .htaccess rules applied - Yes, additional rules applies
- [x] Confirmed no modification of Site Kit placed snippet
- [ ] Uninstalled and reinstalled plugin
- [x] User confirmed no ""Critical errors"" in their Site Health status
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Reset Site Kit (on the SK service)
- [ ] Disconnected Site Kit
- [x] Disconnected impacted service and connected once more - The same occurs
- [ ] Reviewed error logs 
- [ ] Reviewed XHR requests 
- [ ] PHP 8.1 check - can't replicate. AdSense completes set up fine. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense module's internal matching of an AdSense Site by domain should be updated as follows:
	* Only sites with a non-empty `state` should ever be matched
	* An exact match should always be attempted first
	* Matching a sub-domain to its parent domain site, should be enhanced to avoid false positive matches 

## Implementation Brief

* Update `determineSiteFromDomain` to fulfill all of the criteria from the AC 
* Merge https://github.com/google/site-kit-wp/pull/7151

### Test Coverage

* Update tests to cover new criteria

## QA Brief

* This is a very specific scenario which is no longer possible to create on AdSense, so it requires an existing account with a list of sites that include a subdomain site where the subdomain is alphabetically sorted before the parent domain.
	* Alternatively, this can be consistently reproduced using development tools to control the API response (ask @aaemnnosttv)

## Changelog entry

* Fix a bug that could prevent AdSense from being set up on a subdomain.

**Comment by jamesozzie** [comment]
This is possibly due to the parent domain not be added within AdSense. To be updated after some internal testing.

**Comment by BxtGeek** [comment]
my parent domain is approved for the AdSense and getting the sane error

**Comment by jamesozzie** [comment]
Thank you @BxtGeek. If you'd like to [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) we can look into your case individually. Appreciate you letting us know this is also impacting you. We can add your own details to this issue if you do open an individual support topic. 

I'm also escalating this with further reports of this error above, and also with the impacted users below:
- https://wordpress.org/support/topic/google-adsense-68/ | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhXN3Z7wKF26ygVyjsCaz4upDZDoFqoHCwjtc0IsFFdlWh2xpTRMs9f4kHwSk4mklE) | **Open**
- https://wordpress.org/support/topic/error-invalid-site-state-null-4/ | No SH info | **Open**  

I've been doing [some internal testing](https://app.asana.com/0/1185360131189553/1203005805095331/f
) on this error, and I've been unable to recreate this same error in the following scenarios. 
- Adding a subdomain site (on an approved AdSense site), adding the subdomain via Site Kit and not the AdSense platform.
- Adding a subdomain via AdSense first (to an approved AdSense site), and then connecting Site Kit and AdSense on this site.

One issue I found, possibly unrelated, was when adding the subdomain via Site Kit, the subdomain was never listed on adsense.googe.com when checking the sites tab. Separate issue to be created for this. 

------------

For those impacted by this, Site Kit will insert your AdSense snippet, with ads ready to appear. You may wish to [manually add the subdomain](https://support.google.com/adsense/answer/9130110?hl=en) from adsense.google.com if you find the domain wasn't added when adding via Site Kit.

**Comment by jamesozzie** [comment]
[Tested this on a Taste WP site](https://recordit.co/FeQ24zUiRf) using PHP 8.1. I can't replicate the same error. This site is a subdomain site although the parent domain is not added in my AdSense account. 

Also tested this on a personal site whereby the parent domain is approved for ads. I can't replicate the same error in this case also, with PHP 8.1.1. ([recording](http://recordit.co/yHS9Jiyxhp))

**Comment by jamesozzie** [comment]
More details on this added to the main content of this issue. One user is encountering this on one subdomain site but not the other. 

[SH info from site impacted](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhLVRalzDKjnv12yfJ5XK2vAvhGWzDATWilQT1Kapk-Q1z8RKYjzpbHZgtVeQSkPcs)
[SH info from site not impacted](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiawNX_iz7vg525nbo_TXb0kvzFEpczPv22ceAyujrW1X9BsfrYkpr9qGbwARQb8NU), with AdSense set up complete

Based on the above user, who encounters this on one site, it looks like the response from the site check displays differently.

Subdomain site where this doesn't occur:

```
adsense_account_status: ready
adsense_site_status: ready
adsense_use_snippet: yes
```

Subdomain site where this does occur:

```
adsense_account_status: ready
adsense_site_status: none
adsense_use_snippet: yes

```

**Comment by oussjarrousse** [comment]
Site Kit By Google with AdSense integration was working perfectly on my website. 

After resetting the plugin. I attempted to reconnect it again to the same Google Analytics, etc. Everything worked fine except AdSense Integration. AdSense integration started showing the error: "Error: Invalid site state null".

I have already created a support request on wordpress.org  https://wordpress.org/support/topic/error-invalid-site-state-null-wordpress-org/ and I have submitted the form with the site heath information.

I did many experiments this morning (maybe too many) on the wordpress instance side and on the Google AdSense, and Google Analytics side (property management, linked). My experiments concluded with deleting my site from AdSense and trying to create the site again (so it is currently again in the "getting ready" status).

I already checked all the following items

- [x]  Health Check & Troubleshooting plugin check - The same occurs with only SK active
- [x]  Front end check (mixed content, minified content, combined JS) - Nothing obvious, REST endpoints accessible
- [x]  No CND used
- [x]  Incognito mode - The same occurs
- [x]  Checked users Site Health info, no identified causes
- [ ]  Additional .htaccess rules applied - Yes, additional rules applies
- [ ]  Confirmed no modification of Site Kit placed snippet
- [x]  Uninstalled and reinstalled plugin
- [x]  User confirmed no ""Critical errors"" in their Site Health status
- [ ]  Attempted setup/viewing dashboards from another device
- [x]  Temporary disabled WAF rules at host level - including ModSecurity
- [ ]  Checked site setup and dashboard from another WordPress site on the same hosting platform
- [x]  Reset Site Kit (on the SK service)
- [x]  Disconnected Site Kit
- [x]  Disconnected impacted service and connected once more - The same occurs
- [ ]  Reviewed error logs
- [ ]  Reviewed XHR requests
- [ ]  PHP 8.1 check - can't replicate. AdSense completes set up fine.

**Comment by adamdunnage** [comment]
@oussjarrousse Thanks so much for the detailed comment you've added here and all the information it's very welcome. If you could continue to provide answers and information via your support forum topic that would be great and we will happily add anything further to this issue that is relevant.

**Comment by adamdunnage** [comment]
One user in the support forum has managed to resolve this issue by taking the following steps:

1. Logged into their AdSense account and navigated to sites 
2. Selected the affected site and deleted the sub-domains associated with that domain
3. Navigated back to Site Kit > Settings and attempted AdSense setup once more

This time the user was not greeted with the **Error: Invalid site state null** message and was able to go through the setup steps. 

It was also flagged that while the user was debugging this issue that when Site Kit made the following call:

`google-site-kit/v1/modules/adsense/data/sites?accountID=pub-6684699731701146&_locale=user`

The following response was returned:

`[{"autoAdsEnabled":null,"domain":"blog.jarrousse.org","name":"accounts\/pub-6684699731701146\/sites\/blog.jarrousse.org","reportingDimensionId":"ca-pub-6684699731701146:blog.jarrousse.org","state":null},{"autoAdsEnabled":true,"domain":"jarrousse.org","name":"accounts\/pub-6684699731701146\/sites\/jarrousse.org","reportingDimensionId":"ca-pub-6684699731701146:jarrousse.org","state":"READY"}]`

Note that the “state” of the subdomain blog.jarrousse.org was set to “null”, which looks to be what was causing the issue when trying to connect AdSense.

I have not yet been able to test this following the steps the user took but I will try to replicate this and provide a further update once tested. But this does raise a couple questions:

1. Why would state of the subdomain for a connected AdSense return this error message after Site Kit has been reset and setup attempted once more?
2. Could we update the wording on this error message to be more user friendly and perhaps provide a little more information?

**Comment by adamdunnage** [comment]
I was unable to recreate this error based on the above which means I am unable to test the steps taken by the user that fixed this. I attempted this with both an existing subdomain and a newly created one. I also tried with AdSense in the '**getting ready**' state and also once approved and connected.

**Comment by prateekkkkk** [comment]
Hello Adam, I tried the above workaround and it works like a charm. Thanks.

**Comment by jamesozzie** [comment]
[Another user in the support forums](https://wordpress.org/support/topic/google-adsense-68/#post-16185732), previously impacted, was able to proceed without the error appearing, by following [the steps](https://github.com/google/site-kit-wp/issues/5852#issuecomment-1301786516) which @adamdunnage suggested above.

**Comment by jamesozzie** [comment]
Adding here that the workaround suggested above didn't allow [one user in the support forums](https://wordpress.org/support/topic/getting-below-error-in-to-google-site-kit-for-google-adsense-for-subdomain/#post-16330586) to proceed with completing AdSense module connection.

**Comment by bethanylang** [comment]
@jamesozzie I chatted with Evan about this one today and he thinks that this could be occurring because there's a response coming back from the AdSense API that Site Kit does not expect. If that's the case, we can make an update on our side to accommodate for it, but we need to know what has changed.

As with #6036, can you follow up with our AdSense contacts on this one? I'll keep this open for now for possible next steps.

**Comment by jamesozzie** [comment]
The AdSense team have stated that subdomains are being retired from the platform next week. Based on this, and no recent reports of this error I think we can close this one @bethanylang @adamdunnage, or keep an eye out for reports once subdomains are no longer active.

**Comment by bethanylang** [comment]
Thanks @jamesozzie! Agreed that this is okay to close. I'll close out as not planned but do let us know if you see this come up again.

**Comment by jamesozzie** [comment]
This error remains in place for some users setting up Site Kit on a subdomain, even with the parent domain approved. 

This is a bigger problem now than when previously, as the workaround previously was to remove the subdomain site from adsense.google.com before allowing the subdomain site to be added via Site Kit. In AdSense now, with recent changes, subdomain sites are not listed within the "Sites" tab. It's therefore not possible to remove any subdomain sites, making the workaround not feasible. 

[Latest report ](https://wordpress.org/support/topic/error-invalid-site-state-null-8/#post-16778774)| [SH info from this user](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjTHT06HtLnIAzjB65m8HYQwXBNkTMM5ZbAngO_ymJ6HS9-AQNpKXroW7hJ3R8zh5E) | [Recording of experience](https://www.loom.com/share/c83dfa7b05aa475b80c90ddc1231f932)

[Internal testing with recordings](https://app.asana.com/0/1185360131189553/1204723898882892/f). Unable to recreate this from various tests.

**Comment by adamdunnage** [comment]
@aaemnnosttv  A [user in the support forum](https://wordpress.org/support/topic/subdomain-cannot-complete-adsense-connection/#post-16806101) who has also recently experienced this issue has provided a possible cause and a workaround to this issue.

This looks to be an issue with an API call request returning the previously added and approved subdomains  **autoAdsEnabled** and **state** values as `null`.

The workaround is explained in the users [blog](https://blog.boggy.tw/) and how they were able to resolve this issue.

**Comment by aaemnnosttv** [comment]
Thanks @adamdunnage! After looking into this a bit more, I think we can address it.

This seems to be related to changes in AdSense about subdomain sites, some of which were published back in February here https://support.google.com/adsense/answer/12170421?hl=en

What I'm seeing is that the AdSense admin does not show subdomain sites in the list of the sites under your account. It does however still return subdomain sites that were previously added from the API – these are the ones that don't have a site `state` (which becomes `null` in the process).

AdSense no longer allows you to add subdomain sites to your account at all. Attempting to do so will trigger one of the following errors:
- `URL must be a valid top-level domain.` (if the top-level domain is not yet in your account)
- `It looks like you've already added this site ` (when the top-level domain is already added)

Again, this implies that the conditions here are only possible for accounts with subdomains that were previously added when it was possible.

As far as preventing this going forward, I've looked into some changes we can make on our end to ensure we don't try to use one of these invalid sites 👍

**Comment by aaemnnosttv** [comment]
While testing more, I noticed an additional condition for this error to happen which makes it a bit more specific to the site (and hence has been more difficult to reproduce). It only seems to happen when the subdomain is alphabetically "earlier" than the top level domain.

That is, if site `example.com` and `www.example.com` are in the list, `example.com` will still be used as the site. But if the subdomain is `blog.example.com` then this is the site that would be matched. Again, this requires the subdomain site to exist in AdSense to the above still applies but is a specific nuance that is also confirmed in James' latest report above https://github.com/google/site-kit-wp/issues/5852#issuecomment-1570076213

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv I have gone through and completed my testing around setting up AdSense with all the different scenarios around account and site statuses.  All looks good. 

I have added a meeting in our calendars for tomorrow to go through the more complex, sub-domain testing.
