### ISSUE TITLE
Fix mutation of state in widget areas reducer.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5859]
## Bug Description

In a couple of spots in the widget areas reducer, we are mutating Redux state in-situ rather than returning a new object instance in the spirit of immutable data.

https://github.com/google/site-kit-wp/blob/88985106531cc7249ed924bb032e682b7e7fee2a/assets/js/googlesitekit/widgets/datastore/areas.js#L128-L134

This was discovered by accident while working on https://github.com/google/site-kit-wp/issues/5618 - having initially [migrated](https://github.com/google/site-kit-wp/pull/5857/commits/33a9c884d03ab70bbe9bff63ac62dd3859c60309) the error store reducer to use Immer, JS tests which exercised these lines of the widget areas reducer started [failing](https://github.com/google/site-kit-wp/actions/runs/3066691339/jobs/4952149956#step:9:38). This, apparently due to the Immer reducer freezing the combined state, resulting in an error being thrown when the mutation was attempted.

The migration of the error store reducer was then [rolled back](https://github.com/google/site-kit-wp/pull/5857/commits/fcbc21afaff8b464547b3d502f30ec5ec5bf07fa) in order to separately address this issue.

## Steps to reproduce

It's not clear whether this is currently causing any behavioural problems, however the bug is evident when examining the source code, as Redux state should treated as immutable data.

## Additional Context

 - PHP Version: N/A
 - OS: N/A
 - Browser: N/A
 - Plugin Version: 1.83.0
 - Device: N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The widget areas reducer should not mutate the Redux state. It's probably worth migrating it to use Immer via `createReducer` at the same time.

## Implementation Brief
* Using `assets/js/googlesitekit/widgets/datastore/areas.js` and `assets/js/googlesitekit/widgets/datastore/widgets.js`,
	* Import `createReducer` from `assets/js/googlesitekit/data/create-reducer.js`
	* Update `reducer` to use the curried form of `produce` (via `createReducer`)
		* Existing parameters remain the same.
		* Update any logic where we update deeply nested values by spreading nested objects by directly changing the value with the given path.
		* No need to return the updated `state`, it's implied.

### Test Coverage
* Failing tests need to be fixed.

## QA Brief

* Ensure widgets on the dashboard and entity dashboard still render without issues. (This issue modifies some internal state-handling logic, but should have no user-facing changes.)

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Have created and added AC, please review.

cc @aaemnnosttv

**Comment by aaemnnosttv** [comment]
Thanks @techanvil, LGTM 👍

**Comment by aaemnnosttv** [comment]
> * Failing tests need to be fixed.

@asvinb my understanding is that using the Immer reducer would fix the tests that would have failed previously?

Overall LGTM though 👍 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

The issue [reported above](https://github.com/google/site-kit-wp/issues/5859#issuecomment-1266678594) is not related to this ticket so needs further investigation.  I will create a ticket or investigate if it is related to 5772, which seems similar too. 

**Verified:**

The widgets on the dashboard and entity dashboard still render without issues:
  - Tested on a site with live data for all modules on the main and entity dashboard.
  - Tested on a site with zero and gathering data states on the main and entity dashboard.
  - Tested that Idea Hub widget rendered when the feature flag is enabled. 
  - Tested that the data appeared in the Site Kit widget on WP Dashboard
  - Tested that the data appeared in the Admin bar.
