### ISSUE TITLE
Alert text for AdSense notifications

### ISSUE THREAD

**Issue by OisinOConnor** [google/site-kit-wp#586]
## Feature Description

Remove "Alert found!" heading from the notification panel. It doesn't add much to the notification. The text of the notification is sufficient. e.g. below, the message itself is enough
<img width="1275" alt="AdSense alert" src="https://user-images.githubusercontent.com/6488453/65516990-eb644f80-ded9-11e9-876e-c742787596ad.png">
 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When displaying AdSense notifications, remove the "Alert found!" heading. 

## Implementation Brief

Remove the title (or pass an empty string) in the AdSense `GET notifications` datapoint handler.

```diff
 						return array(
 							array(
 								'id'            => 'adsense-notification',
-								'title'         => __( 'Alert found!', 'google-site-kit' ),
 								'description'   => $alert->getMessage(),
```

## Changelog entry

* Remove redundant notification title for AdSense notifications.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
I had a look at this and think I've fixed it, but QAing/testing the change locally is difficult. I need to find the right account with this AdSense state to test it….

**Comment by cole10up** [comment]
**Tested**

Ran through a series of users and am not seeing 'Alert Found!'
![image](https://user-images.githubusercontent.com/57115907/69268602-505bbf00-0b84-11ea-8259-5fabecb41fa7.png)

![image](https://user-images.githubusercontent.com/57115907/69268745-92850080-0b84-11ea-9c9f-6c8bc8257949.png)

![image](https://user-images.githubusercontent.com/57115907/69269147-44bcc800-0b85-11ea-8f35-5169d08745d9.png)

Passed QA ✅
