### ISSUE TITLE
Remove the "Developer Beta" Tag

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#587]
## Feature Description

Remove the "Developer Beta" tag/language that appears throughout the plugin ahead of the release. Some key points to include:

**Plugin Activated:**
![image](https://user-images.githubusercontent.com/2676022/65554821-df7f8a00-dee7-11e9-8598-c245b6b07c79.png)

#### Header
Setup Flow
![image](https://user-images.githubusercontent.com/2676022/65554871-0fc72880-dee8-11e9-89d9-f7c483cd565d.png)

**Site Kit Dashboard (Same)**
![image](https://user-images.githubusercontent.com/2676022/65554953-5026a680-dee8-11e9-9197-8f7fb8362528.png)

**WordPress Dashboard**
![image](https://user-images.githubusercontent.com/2676022/65554980-65033a00-dee8-11e9-954b-3d936d67c49a.png)

## Acceptance criteria

* In all occurrences of the Site Kit logo or title, there must be no mention of "Developer Beta" any longer.

## Implementation Brief

* Remove `\Google\Site_Kit\Context::is_beta`
    * Remove references & usage
        - `Dashboard.php`
        - `Activation.php`
        - Relevant tests
* Remove beta logic from `assets/js/components/logo.js`
* Remove beta style variants in `assets/sass/components/global/_googlesitekit-logo.scss`
* Remove `assets/svg/logo-g-beta.svg`
* Remove `assets/svg/logo-sitekit-beta.svg`
* Remove `build:beta` in package.json
* Remove beta references in `webpack.config.js`

## Changelog entry

*

**Comment by felixarntz** [comment]
IB ✅

**Comment by adamsilverstein** [comment]
This passes QA in my testing, moving to Approval.

### Testing procedure
* Reset plugin and deactivate.
* Activate plugin, go thru setup, activate modules, check dashboard, wp dashboard.
* Note: the "Developer Beta" tag no longer appears anywhere.
* Search codebase for the word 'beta' to verify completely removed.

**Comment by marrrmarrr** [comment]
LGTM
