### ISSUE TITLE
GA4 Activation Banner appearing on Entity Dashboard in view only

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5870]
## Bug Description

On the entity Site Kit dashboard screen, the GA4 banner is appearing in view only. It's not on the main dashboard.

We should remove the banner from the entity dashboard when a user is on view only. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/8eeded12-71a8-4ae6-92bc-fa4213e8e396)

## Steps to reproduce

1. Enable the GA4 and Dashboard Sharing feature flags
2. Connect Site Kit including Analytics without a GA4 property
3. Make sure that the GA4 banner is appearing on the Site Kit Dashboard 
3. As an administrator give access to Search console and Analytics to a non Admin role. 
4. Create a non admin user and login. 
5. Observe that the GA4 banner appears on the entity dashboard but not the main. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 activation banner should never appear on a view-only dashboard (main or entity)

## Implementation Brief

In `assets/js/components/notifications/EntityBannerNotifications.js`:
- Render the `ActivationBanner` component only if the user is not on a view-only dashboard using the `useViewOnly` hook along with the existing `ga4ActivationBanner` condition.

### Test Coverage

- No new tests are to be added.

## QA Brief

According to AC, GA4 ActivationBanner should not appear for view-only mode.

## Changelog entry

* Ensure the GA4 Activation Banner does not appear on the Entity Dashboard when in view only mode.

**Comment by eugene-manuilov** [comment]
IB ✔️
