### ISSUE TITLE
Remove pre-WP5.2 PHP polyfill code, including test code

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5875]
# 🚨 Note: do not merge until Release `1.88.0` 🚨

Together with bumping the minimum WordPress version requirement to 5.2 (see #5874), we should remove any polyfill code that is only in Site Kit for WordPress versions lower than 5.2.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any polyfill code that is only present in the plugin to cater for WordPress versions below 5.2 (i.e. any WordPress version between 4.7 and 5.1) should be removed.
* This should apply to the entire codebase (PHP and JS, production code and test/utility code).

## Implementation Brief

**This can be started, but it must not be merged until `develop` is open for the 1.88.0 release.** When you open a pull request for this issue, please add the same annotation to the top of the PR to minimize the chance of an accidental early merge. :)

- Remove `BC_Functions::rest_preload_api_request` and `BC_Functions::load_script_textdomain` methods.
- Update the above methods' usage to use them directly from WordPress instead.
- Delete `packages/wp-phpunit-polyfill` directory and remove it as a dependency in `composer.json`.

### Test Coverage

- Fix any failing tests.

## QA Brief

- This PR doesn't include any visual/behavioural changes. This just changes how a few methods are sourced in the back-end.
- To ensure there is no regression, you can go through setting up Site Kit, setting up modules, and verifying everything loads and looks well in the Site Kit Dashboard and Settings.
- Verify that there are no console errors or network request failures.

## Changelog entry

* Remove now unnecessary polyfills for WordPress versions older than 5.2, according to new version requirement.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by tofumatt** [comment]
Moving this to the next sprint and adding a note to the issue that this shouldn't be merged until `1.88.0`. 👍🏻

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Ensured there are no regressions when going through setting up Site Kit, setting up modules.
- Verified everything loads in the Site Kit Dashboard and Settings.
- There are no console errors or network request failures.
