### ISSUE TITLE
Update pre-WP5.2 React components to use hooks

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5876]
A few React components that are intended for use within Gutenberg currently don't rely on hooks to support pre-WordPress 5.2 versions (WordPress 5.2 introduced support for React hooks). With support for WordPress versions below 5.2 being removed with #5874, those components should be changed to follow the established Site Kit pattern of using React hooks.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any code that integrates with Gutenberg (look for e.g. `@wordpress-core/...` imports) should be modified to follow latest best practices compatible with WordPress 5.2 (most importantly use React hooks where relevant).
    * Quite possibly, the `googlesitekit-idea-hub-notice.js` file is the only such instance.

## Implementation Brief

**This can be started, but it must not be merged until `develop` is open for the 1.88.0 release.** When you open a pull request for this issue, please add the same annotation to the top of the PR to minimize the chance of an accidental early merge. :)

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

* Update code integrating with Gutenberg to use React hooks instead, following the new WordPress version requirement of 5.2.

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt Maybe you can have a look, I'm unsure whether there is anything to do here actually. The one Gutenberg integration we have (Idea Hub notification) is not a regular component in the first place, so I'm not sure if the original idea here applies there. In any case, it would be good to review that code and see if there are pieces which we can now modernize as we drop pre-WP 5.2 support.

**Comment by FlicHollis** [comment]
Hi @aaemnnosttv is there an update on this one? If no action is needed, we can close. Thanks so much!

**Comment by tofumatt** [comment]
Just had a look through the code and I confirmed what @felixarntz said: there's actually nothing actionable/needed here now. The only place we integrate with Gutenberg _currently_ isn't using React components so there's nothing to change.

Closing this as a won't fix 🙂

**Comment by cliffordp** [comment]
FYI: This was added to v1.88.0's changelog as an Enhancement, but I see it turned out to be 'nothing to change' and 'wontfix'.
<img width="484" alt="image" src="https://user-images.githubusercontent.com/1812179/203541104-3f279289-65ae-4f9c-b997-fc5ea8892f3c.png">
