### ISSUE TITLE
Site Kit: Get OAuth Credentials

### ISSUE THREAD

**Issue by Shericebl** [google/site-kit-wp#588]
Its not allowing me to enter my key to complete the process.

**Comment by swissspidy** [comment]
Hi there!

Thanks for your report. There is currently an issue with the OAuth credentials step. We're already tracking this issue in #561 and are working hard on resolving it. In the meantime, a possible workaround has been posted in https://github.com/google/site-kit-wp/issues/561#issuecomment-533803770.

Please follow the conversation in #561 for any updates.

Thanks!
