### ISSUE TITLE
Can't connect Tag Manager if the selected container has a UA and GA4 tag that differ from the connected GA properties. 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5881]
## Bug Description

If a user has Analytics connected, and then tries to set up the Tag Manager module, they can't select a GTM container if it contains a UA and/or a GA4 snippet that doesn't match the existing connected properties in Analytics (further testing requested). There is no warning or notice as to why you can't connect, and no console error relating to this. The "Confirm & Continue" button is greyed out.

https://user-images.githubusercontent.com/41326532/191927990-6e8e720f-4abd-4082-93ca-fd8a30fef710.mp4

The same isn't true if Analytics is not connected. A user will see a "_Looks like you’re already using Google Analytics within your Google Tag Manager configuration..._" notice. [Recording of this experience](https://recordit.co/Kd6CoeQA7M).

To be analyzed further before escalating. 

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@jamesozzie Is this still relevant given that UA is gone now? Can you please re-test and close if not? Thanks!

**Comment by jamesozzie** [comment]
This can be closed. Tested today and Tag Manager can be connected with any container, whether the container has a GA4 tag that differ from SK connected property or not.
