### ISSUE TITLE
GA4 Activation Banner -> Setup Banner -> "existing property" variants: Only need edit scope when creating a property or measurement ID

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5882]
## Feature Description

At the moment on the GA4 Activation Banner, when on the Setup Banner in the "existing property" variants, we are always checking for the _edit_ scope and if it's not present we a) show the message as highlighted below, and b) redirect to OAuth when pressing the CTA.

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/baf9810e-689d-4acf-9594-e6f58491df7e)

In fact, the _edit_ scope is only needed when creating a property ID or measurement ID. That means that when we're simply connecting an existing property & measurement ID the message & redirect to OAuth is not needed.

Asana bug bash link: https://app.asana.com/0/1202913874897532/1203048840923000

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- On the GA4 Activation Banner, when on the Setup Banner in the "existing property" variants, with is a property selected in the dropdown with a valid measurement ID, do not show the "You will need to give Site Kit permission..." message and do not redirect to OAuth when pressing the CTA.

_Note, check the `analytics-4` `submitChanges` function for implementation tips._

## Implementation Brief

- `In assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js`:
    - Inside the `handleSubmitChanges` function, before pusing `EDIT_SCOPES` to the `scopes` array, besides the current condition, also check if `ga4PropertyID` is `PROPERTY_CREATE`.
	- Inside the `if` statement for `variant` state being `VARIANT.EXISTING_PROPERTY`, locate the footer message mentioned in the ACs and feature description, and add another condition for displaying it, eg. check if `ga4PropertyID` is `PROPERTY_CREATE`.

### Test Coverage

- No tests need to be added/updated.
- Update VRT references if required.

## QA Brief

- Set up Site Kit so the GA4 Activation Banner appears
- For the case when we're simply connecting an existing property & measurement ID the message from AC & redirect to OAuth should not happen.

## Changelog entry

* Only request Analytics edit scopes in the GA4 Activation banner when required to create a new property.

**Comment by FlicHollis** [comment]
Hi @techanvil, I have just updated this priority to a P0 as this has been identified as a launch blocker. Thanks.

**Comment by techanvil** [comment]
AC is added and ready for a review.

cc @aaemnnosttv

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev environment.
- Verified when user don't have edit scope permission.
- On the GA4 Activation Banner, when on the Setup Banner in the "existing property" variants, with is a property selected in the dropdown with a valid measurement ID, then the "You will need to give Site Kit permission..." message is not showing  and user is not redirecting to OAuth when pressing the CTA.
- When user try to set up new property then "You will need to give Site Kit permission..." message is showing  and user  redirecting to OAuth when pressing the CTA.

<details>

![image](https://user-images.githubusercontent.com/94359491/194876104-529bc3c8-04eb-4a81-a44d-4a06b68d0930.png)

![image](https://user-images.githubusercontent.com/94359491/194876138-d7237a0d-b17c-4da5-a1c5-b0bcb202f51c.png)

![image](https://user-images.githubusercontent.com/94359491/194876186-0f3c879f-6517-43f6-be77-7959a90a497f.png)


https://user-images.githubusercontent.com/94359491/194876036-98ae365c-884d-4b7b-91f5-28013f74fcd4.mp4


https://user-images.githubusercontent.com/94359491/194876051-cb086b76-11c9-4f0c-b099-9f948e13d697.mp4

</details>

**Comment by aaemnnosttv** [comment]
## ⚠️ Approval

The implementation here only considers when the property select is set to create a new property, but we must also consider the web data stream (which is where the related measurement ID comes from). If a user were to select a GA4 property that does not have a corresponding data stream for the current site's URL, this will be created which also requires the edit scope.

![image](https://user-images.githubusercontent.com/1621608/197027352-3bb8fe85-bbaf-48ec-9a89-2b0e63605d22.png)


This is mentioned in the AC but may not have been clear that both cases need to be considered.

Nothing is terribly broken here as the permissions modal pops up as usual in this case, but should be addressed here for consistency.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

On the GA4 Activation Banner, when on the Setup Banner in the "existing property" variants, with is a property selected in the dropdown with a valid measurement ID, then the "You will need to give Site Kit permission..." message is not showing and user is not redirecting to OAuth when pressing the CTA.

![image](https://user-images.githubusercontent.com/73545194/197323315-b0920cd1-00f2-4033-982a-1b8454553e67.png)

On the GA4 Activation Banner, when on the Setup Banner in the "existing property" variants, with is a property selected in the dropdown does not have a valid measurement ID, then the "You will need to give Site Kit permission..." message is showing and user is redirecting to OAuth when pressing the CTA.

![image](https://user-images.githubusercontent.com/73545194/197323951-30024ba4-72f9-40ae-b9f5-79c072d8e242.png)

On the GA4 Activation Banner, when there is no GA4 property and edit scopes have been removed in the database to recreate a user not having access to create a GA4 property, then the "You will need to give Site Kit permission..." message is showing and user is redirecting to OAuth when pressing the CTA.

![image](https://user-images.githubusercontent.com/73545194/197324071-ea1a3312-5ff5-4ae3-b2f4-d6bb0658c9dd.png)
