### ISSUE TITLE
Prevent users from connecting GA4 without access to UA

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5886]
## Feature Description

Analytics is a bit of a special case when it comes to modules as it is essentially one but technically implemented as two under the hood. In https://github.com/google/site-kit-wp/issues/4825 we added guardrails to the module settings edit views for modules with service entities to prevent an admin without access to the configured entity to change it.

For GA4, we do the same thing – prevent the user from changing the connection without access. Since older configurations could be setup without GA4, we should additionally require that only admins that have access to the current configured UA entity can connect or change the GA4 connection. 

At the same time, we should evaluate if it should even be possible for UA and GA4 to have different module owners, which is currently possible.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Settings Edit screen for Analytics should be modified to prevent an admin from connecting or changing the connected GA4 property without having access to the connected UA entity
	* The loading state should wait for access to be checked for both UA + GA4 (if connected) before showing the main settings form interface
* If GA4 **is not connected**, the toggle to enable GA4 (not the snippet) should be disabled with an added notice explaining that user needs access to UA in order to connect GA4 (exact copy below). The style here should largely follow what is already in place for the insufficient access restrictions in the settings view. The notice should specifically indicate the owner of the main/UA Analytics module as the point of contact for access.  
    > {username} configured Analytics and you don’t have access to its configured property. Contact them to share access or setup Google Analytics 4.
* If GA4 **is connected**, the existing logic in place around insufficient access restrictions for `analytics-4` should be amended to also require the user has access to the current UA `analytics` entity in order to change the connected GA4 entity. In this case, the notice shown should use alternate copy (see below) and have a higher priority over the GA4 notice. E.g. if the user didn't have access to the UA or the GA4 entities, they would only see the notice about UA  
    > {username} configured Analytics and you don’t have access to its configured property. Contact them to share access or change the configured Google Analytics 4 property.
* The current messages which are shown when a user does not have access to the current configured entity should be amended for consistency  
    > {username} configured {Analytics} and you don’t have access to its configured property. Contact them to share access or change the configured property.

    Where `{Analytics}` is either `Analytics` or `Analytics 4` respectively.

## Implementation Brief

- In `assets/js/modules/analytics/components/settings/SettingsForm.js`:
    - Locate the `<GA4SettingsControls />` component.
	    - Remove the `hasModuleAccess` prop passed to it.
		- Pass both `hasAnalyticsAccess` and `hasAnalytics4Access` props to it.
- In `assets/js/modules/analytics/components/common/GA4ActivateSwitch.js`:
    - Accept a new prop named `disabled`.
	- Pass the `disabled` prop to the `<Switch />` component.
- In `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`:
	- Accept `hasAnalyticsAccess` and `hasAnalytics4Access` props to the component instead of `hasModuleAccess`. Do not replace the usages of `hasModuleAccess` because we will create a new variable with the same name.
	- Locate the `<GA4ActivateSwitch />` component and add the `disabled` prop to it. The `disabled` prop should be truthy only if `hasAnalyticsAccess` is falsey.
	- Check if the `analytics-4` module is connected by running the `isModuleConnected` selector from the `core/modules` store.
	- Create a new boolean variable named `hasModuleAccess`. It should be `true` if `analytics-4` is connected, and both `hasAnalyticsAccess` & `hasAnalytics4Access` are truthy.
	- Update the `<SettingsNotice />` component:
		- Display it if any of the following conditions are met, replacing current condition(s):
	        - If `analytics-4` is not connected and `hasAnalyticsAccess` is falsey.
			- If `analytics-4` is connected and `hasAnalyticsAccess` is falsey.
			- If `analytics-4` is connected and `hasAnalyticsAccess` is truthy, but `hasAnalytics4Access` is falsey.
		- Leaving all the other props in it intact, update the `notice` prop depending on the above conditions.
		    - If the first condition is met, display the first message quoted in the ACs.
			- Otherwise, if the second condition is met, display the second message quoted in the ACs.
			- Otherwise, if the third condition is met, display the third message quoted in the ACs with `Analytics 4` replacing `{Analytics}`.
- In `assets/js/components/settings/SettingsActiveModule/Header.js`:
    - Display the `Connect Google Analytics 4` CTA only if the current user has access to Analytics (UA).
	- In order to check if the current user has access to Analytics (UA), a `useSelect` hook usage similar to `hasAnalyticsAccess` from `assets/js/modules/analytics/components/settings/SettingsEdit.js` can be used.
- In `assets/js/modules/analytics/components/settings/SettingsControls.js`:
    - Update the `notice` prop of the `<SettingsNotice />` component to match the third message quoted in the ACs with `Analytics` replacing `{Analytics}`.
- In `assets/js/modules/analytics/components/settings/SettingsForm.stories.js`:
    - Replace the `Settings w/o module access` story with two distinct stories, one with no access to Analytics and the other with no access to Analytics 4.

### Test Coverage

- Fix any failing tests. A potential test that could fail is the `should render a button to connect GA4 if Analytics is connected but GA4 is not` test case in `assets/js/components/settings/SettingsActiveModule/Header.test.js`.
- Update VRT references if required.

## QA Brief

- Connect Analytics (UA) but not GA4 as an **Admin1**.
- To mimic disconnecting GA4, delete `googlesitekit_analytics-4_settings` from the `wp_options` table.
- Go to the settings page and ensure the `Connect Google Analytics 4` CTA is visible on the Module header for the **Admin1**.
- Click on the CTA and ensure no access required notices are displayed as per the AC.
- Login as an **Admin2** using another Google account and ensure the `Connect Google Analytics 4` CTA is not visible since the **Admin1** initially set up Analytics.
- Expand the `Analytics` header and click on the `Edit` link to go to the `/edit` page. This is the same page that will be navigated when we click the `Connect Google Analytics 4` CTA.
- Ensure the `Activate Google Analytics 4 and place code on your site.` toggle switch is disabled when the user doesn't have access to the `Analytics` (UA).
- Ensure the notices are displayed as per the AC.
- In the `Modules -> Analytics -> Settings -> SettingsEdit` storybook, ensure the following newly added stories are as expected:
   * `Settings w/o UA and GA4 access, GA4 not connected`
   * `Settings w/o UA and GA4 access, GA4 connected`
   * `Settings w/o Analytics access, GA4 connected`
   * `Settings w/o Analytics-4 access, GA4 connected`
   * `Settings w/o UA and GA4 access, fallback owner name`

#### Update
* Follow the above steps and ensure the `Connect Google Analytics 4` CTA is still visible for the second admin who doesn’t have access to Analytics.

#### Update
* Ensure the `Connect Google Analytics 4` CTA is hidden for the users who don't have Analytics access; instead shows a status `Google Analytics 4 is not connected`. Please refer to this [comment](https://github.com/google/site-kit-wp/issues/5886#issuecomment-1334119936) for more details.

#### Update
* Verify that the flicker reported [here](https://github.com/google/site-kit-wp/issues/5886#issuecomment-1335764490) doesn't occur anymore and a progress bar is appropriately shown when access is being checked.

## Changelog entry

* Prevent users from changing the Google Analytics 4 configuration when they don't have access to the currently configured Universal Analytics property.

**Comment by techanvil** [comment]
IB :white_check_mark:

@nfmohit I made a minor adjustment and fixed a typo which you can see in the edit history, I didn't think these merited the round trip!

**Comment by jimmymadon** [comment]
@aaemnnosttv Partially assigned this to you only to get your thoughts on this [CR comment](https://github.com/google/site-kit-wp/pull/6098#discussion_r1019133187). Thanks!

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t I have a few observations. 

1.  It feels a weird UX/UI experience when logged in to Admin2 user when I have no GA4 property. The settings area where the status is displayed (connected or complete setup) is blank. Whereas when there is a UA and GA4 then the status is connected even though the admin2 user does not have access to either properties. 

Wondered on your thoughts on this. 

![image](https://user-images.githubusercontent.com/73545194/203829052-e4fe1253-b532-4cc0-b2da-48049d2dfd65.png)

2. For UA property, the notice is below the dropdown fields where as for GA4 the notice appears further down. I feel to be consistent we should have the notice in the same location for UA and GA4. 

![image](https://user-images.githubusercontent.com/73545194/203831235-0eb5e0f3-a235-4a48-bc05-7e77d30d1711.png)

3. The icon for the notice looks quite large compared with the text and there's too much padding around it and the message. Not sure if we have any direction with UX here but looks odd.  See screenshot above.  

**Verified:**

- The Connect Google Analytics 4 CTA is visible on the Module header for the Admin1. 
- No access required notices are displayed as per the AC.
- As an Admin2 using another Google account and the Connect Google Analytics 4 CTA is not visible.
- The Activate Google Analytics 4 and place code on your site. toggle switch is disabled when the user doesn't have access.
- The notices are displayed as per the AC.
- The stories are as per the QAB. 

<details>
 <summary>Details</summary>

![image](https://user-images.githubusercontent.com/73545194/203832811-7a91c4f5-6a19-4a4e-95ad-c0179e267bd6.png)
![image](https://user-images.githubusercontent.com/73545194/203832835-3cf26466-e106-413d-997c-4d4e5452f461.png)
![image](https://user-images.githubusercontent.com/73545194/203832858-803b0492-3ba8-4eba-9185-5183e1d5f4a6.png)

</details>

**Comment by hussain-t** [comment]
Thanks, @wpdarren. Regarding your observations:

>It feels a weird UX/UI experience when logged in to Admin2 user when I have no GA4 property. The settings area where the status is displayed (connected or complete setup) is blank. Whereas when there is a UA and GA4 then the status is connected even though the admin2 user does not have access to either properties.

I agree with you. However, the implementation was done per the IB, i.e.; it should be hidden if the user doesn’t have access to Analytics. I think that part of IB was based on this point of AC:

>The Settings Edit screen for Analytics should be modified to prevent an admin from connecting or changing the connected GA4 property without having access to the connected UA entity

However, I think the IB was incorrect; we should display the CTA instead because the AC goes on restricting the setting UI. @nfmohit, WDYT, since you worked on the IB? cc: @techanvil 

>For UA property, the notice is below the dropdown fields where as for GA4 the notice appears further down. I feel to be consistent we should have the notice in the same location for UA and GA4.

I agree with this as well. However, this should be a separate ticket because we didn’t change how we render the notice as part of the implementation; rather, it changes the notice copies only.

>The icon for the notice looks quite large compared with the text and there's too much padding around it and the message. Not sure if we have any direction with UX here but looks odd. See screenshot above.

This should be a separate ticket as well since we didn’t change any designs as part of the implementation. Perhaps we can have this and the above issue in the same ticket if that makes sense.

**Comment by hussain-t** [comment]
@wpdarren, @nfmohit, well, it could also be correct to hide the `Connect Google Analytics 4` CTA if the user doesn’t have Analytics access because the user is restricted from connecting GA4. @jimmymadon, WDYT, did you implicitly mean to hide the CTA in the AC?

**Comment by jimmymadon** [comment]
> @wpdarren, @nfmohit, well, it could also be correct to hide the `Connect Google Analytics 4` CTA if the user doesn’t have Analytics access because the user is restricted from connecting GA4. @jimmymadon, WDYT, did you implicitly mean to hide the CTA in the AC?

@hussain-t That is a good question. The value of showing the CTA is for the admin to realise GA4 is not connected and eventually request access to the UA / GA4 property from the other admin. I personally feel having the CTA might be better.  It is always better to inform the user why they cannot do something rather than simply hide options. Also, the ACs for this issue do not directly ask us to modify the `SettingsHeader` - only the `SettingsEdit` form. So let us keep the CTA as before.

c.c. @aaemnnosttv

**Comment by hussain-t** [comment]
Thanks for the clarification, @jimmymadon. I agree with you. It's better to show the CTA and inform the user why they can connect GA4. I will create a follow-PR revert it.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t based on the QAB:  

> Ensure the Activate Google Analytics 4 AND place code on your site toggle switch is disabled when the user doesn't have access to the Analytics (UA).

While the GA4 property downdown is disabled, the toggle switch underneath is enabled by default.  This is when you only have a UA property set up.  I noticed the switch is enabled for both admin users (the one who set up GA and the admin2). Actually, I am not sure if even the UA property switch should be enabled too. As the second admin user who does not have access to connect Analytics, I would expect all the switches to be disabled.  What do you think? 

![image](https://user-images.githubusercontent.com/73545194/204791591-e0c610a9-e971-4382-bd99-25481b7f11a1.png)

**Comment by hussain-t** [comment]
@wpdarren, the QAB refers to "the toggle to enable GA4 (not the snippet toggle)" as per the below point in AC:
>If GA4 is not connected, the toggle to enable GA4 (not the snippet) should be disabled...

The one you're referring to is the snippet toggle. Both are different. 

FYI, the below points from QAB are irrelevant since the behavior of clicking the edit link was changed in #5145 in this follow-up [PR](https://github.com/google/site-kit-wp/pull/6128) as it sets the state to enable GA4. However, when you refresh the `/edit` page, you can see the toggle to enable GA4.

>- Expand the `Analytics` header and click on the `Edit` link to go to the `/edit` page. This is the same page that will be navigated when we click the `Connect Google Analytics 4` CTA.
>- Ensure the `Activate Google Analytics 4 and place code on your site.` toggle switch is disabled when the user doesn't have access to the `Analytics` (UA).

That brings the question of having inconsistency between two behaviors when clicking the edit link and refreshing the page. If that's a problem, then we should address it in a separate issue.

**Comment by felixarntz** [comment]
## Approval ❌ 

@hussain-t @jimmymadon The ACs are all satisfied, however one thing that was apparently added as part of the IB was to also alter the button in the settings panel header. Entirely removing it when lacking access (see 2nd screenshot above) is not desirable here, as it looks inconsistent with the other panel headers and furthermore doesn't provide any status information.

We decided on the following:
* Instead of showing nothing at all in that situation, we should still show a regular status text with icon (i.e. similar to the "Connected" ones), as follows:
    * Use the same warning icon that is present in the regular activate GA4 situation.
    * Copy: "Google Analytics 4 is not connected" (do _not_ use a button, just plain text)

Could you open a follow up PR against `main` with that change?

**Comment by hussain-t** [comment]
Thanks, @felixarntz. Sounds good. I will make the changes 👍

**Comment by hussain-t** [comment]
@felixarntz, I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/6241) against `main` with the above changes.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When I login as 'admin2' and use a different Google account, in the settings for Analytics:
  - The same warning icon that is present in the regular activate GA4 situation.
  - Copy: "Google Analytics 4 is not connected" with no button, just plain text. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/205300788-e79c7813-7464-410b-a8b2-21e2ec22e03f.png)

![image](https://user-images.githubusercontent.com/73545194/205300811-3a2079a0-d62d-4502-9f86-86cb207857e3.png)

</details>

**Comment by aaemnnosttv** [comment]
## ⚠️ Approval

This looks good but introduces a flicker when another admin who has access views the settings screen because it logically defaults to the no-access case. This results in the status text turning into the button once the check request completes.

https://user-images.githubusercontent.com/1621608/205374700-90dd1171-8421-4917-b98a-788b196a8b6a.mp4

The flicker is exaggerated in the screencast above using network throttling but we should add a  mini progress bar here while the check-access request is in progress so that it doesn't switch from one to another.

**Comment by nfmohit** [comment]
@aaemnnosttv I've created #6270 to address [this](https://github.com/google/site-kit-wp/issues/5886#issuecomment-1335764490). Thank you!

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit 👍 there's a little more to do on that one but not much, I've sent it back with you.

More importantly, **this issue seems to have introduced a regression (currently in `main`)** from the current release regarding the behavior of the "Activate Google Analytics 4 and place code on your site." toggle for users who don't have GA4 enabled yet. This could have been missed due to another bug that I discovered which was introduced in 1.88.0 which has the effect of automatically enabling/skipping this toggle. See https://github.com/google/site-kit-wp/issues/6271.

The issue here however is that once GA4 is enabled/toggled-on, the property select remains disabled.

Both of these should really be fixed for the release.

**Comment by aaemnnosttv** [comment]
@wpdarren this is ready for review again – please note also that your observation https://github.com/google/site-kit-wp/issues/6271#issuecomment-1337531952 should be resolved as well.

Just to note for QA as well, the cases we want to ensure are checked here are:

- Module owner (always has access)
	- never sees progress bar, always sees button to Connect GA4 
- Non-module owner, with access
	- sees progress bar with warning, then button to Connect GA4
- Non-module owner, without access
	- sees progress bar with warning, then status text that GA4 is not connected

In all cases, if GA4 is connected, there should be no progress bar and it should always show as "Connected" as other modules.

We also want to see that the height of the collapsed module settings row does not change between loading and loaded states in each case. This is somewhat less important than all the other functional details but is something we paid attention to addressing in CR.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Module owner (always has access) - never sees progress bar, always sees button to Connect GA4
- Non-module owner, with access - sees progress bar with warning, then button to Connect GA4
- Non-module owner, without access - sees progress bar with warning, then status text that GA4 is not connected
- In all cases, if GA4 is connected, there is no progress bar and it always shows as "Connected" as other modules.
- The height of the collapsed module settings row does not change between loading and loaded states in each case. 
- The issue reported on 6271 is fixed. I am able to create a new property. 

https://user-images.githubusercontent.com/73545194/205737353-59ad199d-8ed0-4ae8-affa-6e9fc828ceb4.mp4

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/205737202-fb3c9a2f-554f-4879-8f42-78ecf653cab4.png)
![image](https://user-images.githubusercontent.com/73545194/205737218-47d27570-e85b-4436-896f-25cb45f566bc.png)
![image](https://user-images.githubusercontent.com/73545194/205737294-2d05a509-fc95-45d0-9a49-9444cd58de21.png)
![image](https://user-images.githubusercontent.com/73545194/205737312-f8b98b62-f3b1-4ef6-a051-225c18f2068f.png)

</details>
