### ISSUE TITLE
Update API route for loading and saving updated User Input questions

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5889]
## Feature Description

Once the user input questions are updated in #5888 , the `core/user/data/user-input-settings` route should be updated to reflect the changes,

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Not needed, this will be covered in #5888 so this one can be closed. 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@kuasha420 see https://github.com/google/site-kit-wp/issues/5888#issuecomment-1276720590

**Comment by kuasha420** [comment]
@aaemnnosttv Can you see my comment and updated AC on #5888, and if that satisfies your recommendation, close this one? Cheers!

**Comment by aaemnnosttv** [comment]
Closing in favor of #5888.
