### ISSUE TITLE
Implement standalone screen with field to paste verification token

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#589]
## Feature Description

For the new authentication flow, we'll need a **standalone** screen (decoupled from existing setup flow) that contains a (relatively wide) text input field where a user can paste a site verification token. Clicking a button "Proceed" should store the token as that user's verification tag, and for now just redirect back to the dashboard (will later be integrated with the new flow, redirecting to the appropriate step).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Implement standalone Site Kit admin screen `googlesitekit-verification-token` that is available under a distinct URL. The screen should not be linked to from anywhere.
* Show UI similar to the below mock on that screen.
![Screenshot 2019-09-25 at 09 21 05](https://user-images.githubusercontent.com/3531426/65578828-dd184100-df76-11e9-8ff9-26b49462ab4c.png)
* The "Proceed" button should only be enabled if there is a verification token (a `<meta>` tag) in the field.
* On clicking "Proceed", store the verification token as the user's verification tag (see `Verification_Tag` class), and also set their verified flag (see `Verification` class).

## Implementation Brief

* Register a new standalone screen in
    - `Site_Verification` in conjunction with `Module_With_Screen_Trait`  
    or
    - `Core\Admin\Screens`
* Use `<PageSpeedInsightsSetup>` as a starting point for the main portion of the interface
    - Replace textarea with wide text input component
    - Add basic field validation for `meta` tag  
    (should be wide enough to fit a site verification meta tag without cropping)
    - Only enable/allow submit/proceed if meta input is valid
* Add new `core/user/data/verification-tag` route
    - `POST core/user/data/verification-tag` should save the tag for the current user  
    ```php
    $this->authentication->verification_tag()->set( $tag );
    ```
* When submitted, the tag is saved using the new route and the user is navigated to the Site Kit dashboard with a success notice.

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz do you see this screen as being part of the Site Verification module or registered separately in Core\Screens?

What permissions should be required to access this screen?

Should we plan on adding E2E test coverage as part of this?

**Comment by felixarntz** [comment]
@aaemnnosttv Apologies for the time spent on the IB, but we were able to bypass the necessity for this screen (which is great because it means no more copy+paste in the setup flow!). We will send the verification token over from the proxy directly and handle that in the plugin.
