### ISSUE TITLE
Add “Cancel” button in User Input page

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5892]
## Feature Description

For the updated User Input, it was decided to make answering the question entirely "Optional" for the user during any part of the flow. Therefore, there should be a "Cancel" button added to the User Input Page. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The User Input page should implement a `Cancel` button as seen on the [design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=967%3A26839). 
* It should be available on all the questions page as well as the Review page. 
* Clicking on it should take the user back to Site Kit Dashboard. 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
As mentioned in https://github.com/google/site-kit-wp/issues/5888#issuecomment-1276720590, I think this could fall under the issue to implement the design since it is a small detail, although it would be good to call out specifically.

**Comment by kuasha420** [comment]
@aaemnnosttv Can you close this one in favor of #5890 ?

**Comment by aaemnnosttv** [comment]
Closing in favor of #5890
