### ISSUE TITLE
Implement new inline Edit question interface in the User Input Review page

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5893]
## Feature Description

The 'Edit' functionality of User Input Review screen is a way for users to make changes to their answers before submitting. Currently, clicking it takes the user back to the questions screen which is a cumbersome UX. To make the experience better, the new Inline edit interface from the Figma design should be implemented. It is similar to how Edit Settings behaves on the Connected Services page. ie. expend the question for editing, lock out other questions, etc. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Review screen of User Input page should implement the new inline 'Edit' functionality as seen in the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=2076%3A61567) design. 
* Clicking on Edit should expand the question with all available answers where user can update their choice(s).
* Clicking "Edit" on an already opened question should close it and update the answer.
* Clicking "Edit" on a different question while another one is open should close the previously opened one and expand the new one. 
* If the minimum answer requirement is not met and the user closes the inline editor, an error message should be raised as seen in the [design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=2196%3A62664).  
* Similar error message should also be displayed when the user tries to save the answers while not answering a question. 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@kuasha420 given the similarity with #5897 – I would imagine we would use some shared component in both places – would it make sense to do this in a single issue? Or, if we decide it's best to have separate issues, I would expect one of them to cover the majority of the implementation, and maybe the settings-specific issue would include differences that are only applied there.

Otherwise, I feel like we risk building this out inefficiently.

**Comment by kuasha420** [comment]
Hi @aaemnnosttv, I have combined this one with #5891. If it makes sense, can you close this one? Cheers.
