### ISSUE TITLE
Remove functionality around the no longer used answer edit mechanism using ‘single’ URL parameter from the User Input page

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5894]
## Feature Description

Once the inline answer editing is implemented in #5893 and #5897, The current mechanism to edit an answer using "single" parameter in URL will no longer be in use and should be removed with all related code and tests. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The mechanism to go to a specific question in the `user-input` page using the URL parameter should be removed from the code base. 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kuasha420** [comment]
Not sure if the Inline Edit issues should block this one. Without blocking,  the\ Edit functionality will be broken until #5893 and #5897 are complete. But I don't think That's really needed.

**Comment by aaemnnosttv** [comment]
@kuasha420 depending on your response to those two issues, perhaps this should happen in the issue where we implement the inline editing, that way there's no dependency. It should be fairly low effort to clean up and of course won't be used anymore after that point as well.

**Comment by kuasha420** [comment]
Thanks for the suggestion, Evan! This will be covered as part of #5897 where we stop using this functionality in favor or inline editing. So closing this one as duplicate.
