### ISSUE TITLE
Implement new inline Edit answer interface for User Input Settings

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5897]
## Feature Description

#5893 implements "inline" answer editing interface to the review screen of User Input page. The User Input settings is very similar looking with "Edit" buttons on the questions with a few differences. The same inline editing interface should be added here as well according to the updated design which expands the question the user is editing and blocks out the other questions as seen in the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=910%3A24310) design. 

Also, Once the inline answer editing is implemented in https://github.com/google/site-kit-wp/issues/5893 and here, The current mechanism to edit an answer using "single" parameter in URL will no longer be in use and should be removed with all related code and tests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The User Input section of Admin Settings page should implement the new inline edit interface for both [desktop](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=910%3A24310) and [mobile](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=1764%3A46682). 
* Clicking on Edit should expand the question with all available answers where user can update their choice(s).
* While a question is in this expanded state, other questions should be blocked off from any interactions as seen in the design. 
* For sites with multiple admins, if the User Input Questions were answered by other admin, that information should be displayed as seen in the [design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=910%3A24310&t=hsDHLwJQLWbULVzR-0). 
* The expanded state should have Buttons for saving the updated answer ("Confirm changes") and closing the editor without saving ("Cancel"). 
    * The "Confirm changes" button should be disabled until user has updated the answer. 
    * Clicking on "Confirm changes" will save the updated answer to the server and close the editor.
    * Clicking on "Cancel" should discard changes (if any) and close the editor. 
* The mechanism to go to a specific question in the `user-input` page using the URL parameter should be removed from the code base since it was only being used for the `Edit` answers which will be handled by the inline editors in both User Input Review and Settings page. 

## Implementation Brief

**While writing the IB, make sure to reuse and share as much components and other code with the inline edit of the User Input Review screen to minimize duplicated effort as they are quite similar. See the IB for #5891**

* Once #5891 has been merged.
* Update `assets/js/components/settings/SettingsAdmin.js`,
	* to include a new prop `showIndividualCTAs` which is a boolean indicating whether the "Confirm changes" and "Cancel" buttons should be displayed when editing a question. This prop should be proxied to the `UserInputPreviewGroup` component which will render the buttons accordingly.
	* The "Confirm changes" should be disabled if there are no changes made to the question.
	* To check if settings were changed,
		* Update `assets/js/googlesitekit/datastore/user/user-input-settings.js`,
			* to add a new property `savedInputSettings` which will behave similarly as `inputSettings` which should be updated when the settings are saved `saveUserInputSettings` and initialized when we get the settings initially (`getUserInputSettings`). `fetchStoreReducerCallback` can be updated to set `savedInputSettings` to the same value as `inputSettings`
			* Add a new selector `hasSettingChanged`, which an optional `slug` as parameter.
				* If the slug is present, check if `inputSettings[slug]` is different from `savedInputSettings[slug]` to return `true`
				* If no slug is present, check if `inputSettings` is different from `savedInputSettings`
				* Refer to the `hasSettingChanged` selector in `assets/js/googlesitekit/data/create-settings-store.js` as example.
	* Update `UserInputPreviewGroup` to call the `hasSettingChanged` selector to enable/disable the "Confirm changes" button.
	* The "Confirm changes" button should dispatch the `saveUserInputSettings` action from the `core/user` data store upon clicking.
	* Clicking the "Cancel" button should close the question item by using the same mechanism as the "Edit" button.
	* For sites with multiple admin, if the question is site specific and the answer was given by someone other than who is currently editing the answer, show the UI as seen in the design. 
	    * The logic and component can be borrowed from the similar functionality implemented in #5890 
* Using `assets/js/components/user-input/UserInputQuestionnaire.js`, remove all URL related logic since we are no longer redirecting the user to a specific URL to edit their answers.

### Test Coverage
* Add tests for the new selector.

## QA Brief

- Set up Site Kit.
- Answer user input questions.
- Go to Site Kit -> Settings -> Admin Settings.
- Verify that the `Key Metrics` section shows an inline edit answer interface according to the Figma designs.
- When a question is opened, verify that the other questions are disabled.
- If a question is answered by a different admin, verify that a "This question has been answered by" message shows up according to the design.
- Verify that individual CTAs show up for each question which saves the selected input or cancels (collapses) the question.
- Verify that not saving a modification and closing the question reverts the selected answer to the originally saved answer.

## Changelog entry

* Implement new inline edit answer interface for User Input settings.

**Comment by aaemnnosttv** [comment]
> * Both buttons should always be available, whether user updated the answers or not.
> * Clicking on "Confirm changes" will save the updated answer to the server and close the editor. If there was no update, it should just close the editor.

@kuasha420 from what I recall, the confirm changes button should work consistently with module settings in that it should be disabled unless a change has been made compared to the saved settings.

Also, since there is a dedicated issue for this, we should probably highlight this on other related issues to not implement this part of the design yet.

**Comment by kuasha420** [comment]
Sounds like you're right Evan, I missed the later part of the discussion in [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0?node-id=910:24310#257751808). ACs updated.

**Comment by tofumatt** [comment]
ACs look good here 👍🏻

**Comment by kuasha420** [comment]
@nfmohit It makes sense to tackle this here and I have added a point about it in the ACs, not sure if it's a good idea to edit ACs at this stage but since this has not yet started, I think we can get away with this one. I have also added a point in the IB to address that part of the issue. Should be doable as a 19sp ticket. cc  @FlicHollis

**Comment by mohitwp** [comment]
### QA Update ❌ 

Verified on dev.

1) Font color is different from figma . In Figma font color is #6C726E and implemented color is #5F6561.

<details>

![image](https://user-images.githubusercontent.com/94359491/213973442-a653ca7f-699b-403f-8e2a-cfe8a0500afb.png)

![image](https://user-images.githubusercontent.com/94359491/213973469-70487528-c5d3-402c-847e-0cb84c5a55e0.png)
 
</details>

2) Only Question no 1( What is the main purpose of this site?) is getting share between 2 admins and answer is getting update as per last answered by any site admin. Other questions don't have common answers and answers showing as per selection of logged in admin. Is this correct and expected ?

<details>

Q-1)

![image](https://user-images.githubusercontent.com/94359491/213973845-e054ff27-d12d-449f-833d-722ddefb7676.png)

Q-2) 

![image](https://user-images.githubusercontent.com/94359491/213973902-548f01aa-dfdb-4706-83bc-2c47411aac5b.png)

</details>

**Comment by nfmohit** [comment]
Hi @mohitwp. Thank you for sharing your concerns.

> Font color is different from figma . In Figma font color is #6C726E and implemented color is #5F6561.

The implemented colour is based on the token used in Figma, i.e. `surfaces/on-surface-variant`. Differences like this will be fixed as a part of #6328.

> Only Question no 1( What is the main purpose of this site?) is getting share between 2 admins and answer is getting update as per last answered by any site admin. Other questions don't have common answers and answers showing as per selection of logged in admin. Is this correct and expected ?

This is expected. Only the first one is a site/global scoped question, the others are user scoped questions.

Thanks!

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @nfmohit for quick reply [here](https://github.com/google/site-kit-wp/issues/5897#issuecomment-1399842649)

- Verified on dev.
- Verified the edit answer interface showing and working as per AC.

<details>

![image](https://user-images.githubusercontent.com/94359491/213975793-91ddf55d-67c7-459d-b976-1032ecd44668.png)

![image](https://user-images.githubusercontent.com/94359491/213975850-1579b9cf-dc98-4ea3-83e7-6a10ca37ecd7.png)

![image](https://user-images.githubusercontent.com/94359491/213975879-a06ac6f8-6249-405a-846d-a967e37229cd.png)

</details>
