### ISSUE TITLE
Remove "API Credentials" box in "Admin Settings"

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#590]
## Feature Description

In preparation for the new auth flow, the "API Credentials" box under "Admin Settings" should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the Site Kit "Settings" screen, the "API Credentials" box under "Admin Settings" should be entirely removed including all its client-side functionality.
* In its place, add a smaller box titled "Plugin Status" which shows the green checkmark + "Site Kit is connected", as well as a link to "reset Site Kit". 
![mock](https://user-images.githubusercontent.com/3531426/65945104-835ebd80-e433-11e9-88d8-0c5278b8b480.png)

## Implementation Brief

Repurpose _API Credentials_ section in `<SettingsAdmin>` component
* Change "API Credentials" to "Plugin Status"
* Remove `logo-google-cloud` module icon (or replace with more appropriate, if available)
* Remove layout for displaying client ID and secret
* Move "Site Kit is connected" with green checkmark to be left-aligned below the section heading 
* Keep current reset link/button layout and behavior

## Changelog entry

*

**Comment by felixarntz** [comment]
@marrrmarrr Since the "API Credentials" box currently holds the "Reset Site Kit" button, what should happen to this button? We still need to provide it somewhere else in the "Admin Settings" tab. Can you please augment the ACs with details on that?

**Comment by felixarntz** [comment]
Updating the milestone since this should be in the same release as the proxy.

**Comment by aaemnnosttv** [comment]
> this should also include removing layout for displaying API key

This is removed as part of #511 but good to be slightly redundant just in case that one doesn't make it in for whatever reason.

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅

**Comment by tofumatt** [comment]
QA passes, though the size of this text is quite small:

<img width="416" alt="Screenshot 2019-10-17 19 20 11" src="https://user-images.githubusercontent.com/90871/67036288-3eb17280-f113-11e9-90bd-eed5dee23de6.png">

`14px` looks a lot better:

<img width="408" alt="Screenshot 2019-10-17 at 19 21 11" src="https://user-images.githubusercontent.com/90871/67036310-4a049e00-f113-11e9-9bb8-3490344c0e97.png">

Should I file a follow-up issue for this or should we address it as a follow-up PR for this issue?
