### ISSUE TITLE
Remove automatic redirection to User Input Page 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5901]
## Feature Description

Going forward, the User Input is optional for all users, therefore, there should no longer be any automatic redirection to `user-input` page based on the completion state of User Input Survey.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Users should not automatically be redirected from `dashboard` to `user-input` page when they have not completed the user input questions. 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@kuasha420 I feel like this can probably happen as part of #5900 as it should naturally be removed along with the `User_Input_State::VALUE_REQUIRED` value. It seems quite small to handle separately.

**Comment by kuasha420** [comment]
@aaemnnosttv Makes sense to me. See https://github.com/google/site-kit-wp/issues/5900#issuecomment-1278471410

**Comment by aaemnnosttv** [comment]
Closing in favor of #5900.
