### ISSUE TITLE
Strange UI on User Input form when summary screen loads

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5911]
## Bug Description

Noticed a very minor UI bug while looking at the User Input form during release QA.  After you complete the questions, a summary screen appears. The edit on question 1has a border around it, even though I'm not hovering over the edit link  The page loads and this is the state that it appears in.  Not a huge issue but looks odd. 

![image](https://user-images.githubusercontent.com/73545194/192291388-cc8ac397-9588-4678-a2d4-1d8e554cc619.png)

## Steps to reproduce

1. Enable the `userInput` feature flag
2. Connect Site Kit and the User input form will appear
3. Go through the questions until you see the summary screen
4. Observe UI issue as per above. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@wpdarren This page will now be redesigned before the User Input functionality is released to the public. So I think this issue can be closed as the new UI will be retested?

**Comment by wpdarren** [comment]
@jimmymadon I was actually thinking the same when reading through the v2 user input doc. Closed!
