### ISSUE TITLE
Update GA4 banner with variant for admin without access to the connected UA entity

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5912]
## Feature Description

Similar to https://github.com/google/site-kit-wp/issues/5886, this issue is specific to addressing the case where GA4 is not set up yet and the current admin also doesn't have access to the connected UA entity.

In this situation, we likely still want to surface the importance of connecting GA4 but we shouldn't  prompt the user to setup GA4.

Asana bug bash link: https://app.asana.com/0/1202913874897532/1202933584204510

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When displaying the GA4 Activation Reminder banner, an additional check should be made if the current user has access to the connected UA entity. Render a Progress Bar when performing this check to avoid sudden changes to components / flickering.
* If the current user **has access** to the UA entity, the Reminder banner should be rendered as normal.
* If the current user **does not have access** to the UA entity, then a new variant of the Reminder banner should be shown as follows (all other ReminderBanner variants **must** not be changed):
    * Title: Same as the Reminder banner (based on the time).
    * Description: Initial part of the description should remain the same (based on the time). An additional line should be added below the existing description as follows. {username} should be replaced with the WordPress username of the current module owner of UA.
    > {username} configured Analytics and you don’t have access to its configured property. Contact them to share access or set up Google Analytics 4.
    * Description Icon: Should be the `ErrorIcon` (exclamation mark) that is currently displayed in the last month before UA is retired. In addition to this variant, the description icon should also be changed to this `ErrorIcon` for the Reminder banner variant displayed after the 1st July 2023 cut off date.
    * CTA: Single Primary "Dismiss" CTA without rendering the "Setup" CTA. Dismissal logic should remain the same.
    * The `secondaryPane`  with the bulleted list and the "Learn more" link should be removed, including the divider. (Only for this variant of the component and not for the remaining Reminder Banner component variants).
* As always, a new StoryBook story should be created for the new banner.

## Implementation Brief

* Within `<ReminderBanner>`:
    - Modify the `descriptionIcon` to be the `ErrorIcon` when `referenceDate` > `2023-07-01`. (So the `InfoIcon` should only be rendered when `referenceDate` < `2023-06-01` and the `ErrorIcon` should now be rendered on and after `2023-06-01`).
    - Using the snippet from `assets/js/modules/analytics/components/settings/SettingsEdit.js`, check if the current user `hasAnalyticsAccess`. 
    - Render the `<ProgressBar>` component while the above selectors are not resolved (using the `isLoadingAnalyticsAccess` snippet in `SettingsEdit` above).
    - If the user **does not** have access:
        - Render a new component, say `<ReminderBannerNoAccess>`. Pass the computed `title`, `description`, `descriptionIcon`, `dismissExpires` and `onDismiss` values as props down to the new component.
* Within the new `<ReminderBannerNoAccess>`:
    - Render a `BannerNotification` with the following props:
        - `id`, `className` and `dismiss` should be the same as within the ReminderBanner component.
        - `title`, `descriptionIcon`, `dismissExpires` and `onDismiss` should be passed as is from the props.
        - Append the additional description line from the AC to `description`. The module owner's username can be found using snippets from `assets/js/modules/analytics/components/settings/SettingsControls.js`.
        - Do not pass any `ctaLabel`, `ctaLink`, `onCTAClick` or `secondaryPane` props.

* In `ReminderBanner.stories.js`, 
    - Update the existing variants and add a new variant to mock the module owner not being the logged in user to render the new banner and appropriate description. Refer to `assets/js/modules/analytics/components/settings/SettingsForm.stories.js` for how to provide the owner.

### Test Coverage

* No new tests required.

## QA Brief

* Create an admin, say "Admin1" to setup SiteKit. Also setup Analytics and create a new property or use an existing one that is connected to Admin1's account. Then delete the `google_analytics_4_settings` option from `wp_options` table in the database (to ensure the GA4 Activation Banner is triggered).
* Verify the GA4 Activation Reminder Banner is displayed as before when a user does have access:
  * As Admin1, login to the "Analytics Dashboard" (by clicking on "See full details in Analytics" within the Analytics accordion in SiteKit's Settings). Click on the "Admin" settings cog in the left menu. Under the first "Account" column, click on "Account Access Management". In the popup, click on the + sign to add Admin2's Google Account to this account. Now login to SiteKit as Admin2, go to Analytics Settings and try editing them. Verify the ACs for when user has access. 
   * <img width="3000" alt="Screenshot 2022-06-07 at 10 47 57" src="https://user-images.githubusercontent.com/1721319/172353728-fc7dee89-1f94-4da9-ba9d-5757620ed272.png">

* Verify the new variant for the GA4 Reminder Banner when user does not have access:
  *  In Admin1's "Analytics Dashboard" mentioned above, follow the steps to go to Account Settings. In the "Account Access Management" popup, click on the 3 dots next to Admin2's Google Account and click on remove access. Now login to SiteKit as Admin2, go to Analytics Settings and try editing them again. Verify the ACs for when user does not have access.

* Verify the [new StoryBook story](https://google.github.io/site-kit-wp/storybook/pull/5994/?path=/story/modules-analytics4-reminderbanner--initial-notice-without-access) (there is no Figma mock but the ACs describe the required design).

## Changelog entry

* Fix bug that could cause user without Analytics access to see incorrect Analytics update UI in GA4 activation banner.

**Comment by eclarke1** [comment]
Just a reminder on this one folks, if we want to launch GA4 activation banner in 1.86.0 this launch blocker really needs to get progressed - please can I ask for someone to pick up the AC review here as soon as possible so we can get this issue started in Sprint 86.
cc @FlicHollis

**Comment by aaemnnosttv** [comment]
> * When displaying the GA4 Activation Reminder banner, an additional check should be made if the current user has access to the connect UA entity.

@jimmymadon let's make it clear how the user should experience this, i.e. behind a(n existing?) loading state – there should be no flicker or changing of states later based on the result of this check.

> * The `secondaryPane`  with the bulleted list and the "Learn more" link should be completely removed, including the divider.

Let's revise this to make it clear that this is not being removed from the banner, but that it shouldn't be shown in this case specifically.

> * Description Icon: Should always be the `ErrorIcon` (exclamation mark) that is currently displayed in the last month before UA is retired.

I noticed this changes back to a non-error after the cut-off date which I think was probably a mistake. It would be good to correct this minor detail here as well so that once it changes to the error icon based on the date, that it stays that way.

**Comment by jimmymadon** [comment]
@aaemnnosttv Thanks - updated the ACs. I did realise the description icon was going back to the exclamation mark when coding this and thought it was intentional within Figma.

**Comment by jimmymadon** [comment]
@FlicHollis Have jumped the gun a bit here and added an IB since this is part of this sprint and most of @aaemnnosttv 's comments for the AC review were minor which I have fixed.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon, this is almost good to go.

> * Modify the `descriptionIcon` to be the `ErrorIcon` when `referenceDate` > `2023-07-01`. (So the `InfoIcon` should only be rendered when `referenceDate` < `2023-06-01`).

The conclusion here is correct but then it actually isn't clear what it should be from 2023-06-01 to 2023-07-01 😄 It should be an error from 2023-06-01 and after.

Finally, there are a fair amount of changes/additions here including storybook, so let's bump the estimate a little to account for that.

**Comment by jimmymadon** [comment]
@aaemnnosttv Thanks - I think I didn't mention that because the `ErrorIcon` is currently rendered for that period. But I have clarified this point in the IB and yeah, good to bump up the estimate here.

**Comment by mohitwp** [comment]
### QA Update ❌ 

@jimmymadon 

I noticed flicker before reminder banner appears. On load for few seconds it display zero data notification banner and then load the  GA4 reminder banner.


https://user-images.githubusercontent.com/94359491/196100337-f18c0775-44f5-4fca-8a25-368de103fe0e.mp4

**Question** > I noticed that in AC description text is -

> {username} configured Analytics and you don’t have access to its configured property. Contact them to share access or setup Google Analytics 4.

We implemented this description text with two changes.
1. We replaced -  "configured property" to "analytics property" . 
2. And in second line "Contact them to share access or change the Analytics property.

Are theses changes intentional ?

![image](https://user-images.githubusercontent.com/94359491/196100669-b4fc6912-eb0e-487b-b539-8d6203c235d3.png)

**Comment by mohitwp** [comment]
### QA Update ✅ 

 Verified on dev.
 Verified reminder banner for Admin 2 having access .
Verified reminder banner for Admin 2 who don't have access.
Verified reminder banner for different dates.
Verified reminder banner title and description as per AC.
Issue mentioned [here](https://github.com/google/site-kit-wp/issues/5912#issuecomment-1280335759) are now resolved.
Verified [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-reminderbanner--initial-notice-without-access)

<details>

When user don't have access-

![image](https://user-images.githubusercontent.com/94359491/196644478-5bc716b5-55bc-4b46-9cbe-f5c976324b2d.png)

![image](https://user-images.githubusercontent.com/94359491/196644512-bd960727-23b1-42de-b3aa-5b3af39e7963.png)

![image](https://user-images.githubusercontent.com/94359491/196644565-02b27f79-8d4d-4c2f-a157-e75f5b62925b.png)

![image](https://user-images.githubusercontent.com/94359491/196645959-65d468fa-2587-42f3-b595-5bbdf5a818bc.png)

When user have access -

![image](https://user-images.githubusercontent.com/94359491/196646450-239162ef-6ef9-4018-b2bd-ab52fd77beca.png)

![image](https://user-images.githubusercontent.com/94359491/196646629-51cc52e2-f0e7-4ba7-8229-6991dd73b796.png)



https://user-images.githubusercontent.com/94359491/196645461-899b8063-7f4f-44ca-8ded-691761fd1c46.mp4

</details>

**Comment by aaemnnosttv** [comment]
@felixarntz I noticed that the request may be made to check access even when the current user is the module owner because the module owner ID isn't available right away which causes the selector to be invoked. See https://github.com/google/site-kit-wp/pull/5994/files#diff-51079bbb133e20fa794c0e1fd5fd30b551dda818e0cfe0ba4162502670cf133aR1248-R1250

We should fix this but not sure if it needs to block this issue?
