### ISSUE TITLE
Replace mysql with mariadb for testing environments for compatibility with M1 Macs

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#5920]
## Bug Description

On an M1 Mac, running the `npm run env:start` fails with an error described below.

## Steps to reproduce

1. On an M1 Mac, run `npm run env:start`
2. See the following error:
```
$ npm run env:start

> googlesitekit@ env:start /private/var/www/apps/tenup/sitekit-10uplabs-com/wordpress/wp-content/plugins/google-site-kit
> ./bin/local-env/start.sh

STATUS: Stopping Docker containers...
STATUS: Downloading Docker image updates...

ERROR: for mysql  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

I had to swap the MySQL image to the MariaDB image by modifying `google-site-kit/bin/local-env/docker-compose.yml`:
Replace
```
 mysql:
   image: mysql:5.7
```
with:
```
 mysql:
   image: mariadb:10.3
```

## Additional Context

 - PHP Version: 7.4
 - OS: macOS Monterey 12.6
 - Browser: NA
 - Plugin Version: NA
 - Device: MacBook Pro 14 - 2021 - Apple Silicon M1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The local test environment should use the same MariaDB image as WP Local Docker's global image, which is mariadb:10.3.
* Running the command in `Steps to reproduce` should not throw the error described there and should successfully start the local testing environment on an M1 mac.

## Implementation Brief

- In `bin/local-env/docker-compose.yml`:
    - Change the `image` in the `mysql` service to `mariadb:10.3` from `mysql:5.7`.
- Test `npm run env:start` command:
    - This command should be tested from different environments, e.g. Windows, macOS in Intel and Arm, and Linux.

### Test Coverage

* No tests needed.

## QA Brief

* Can be tested by running e2e-tests locally, and ensuring that there are no changes between using mysql and mariadb. 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs look good to me, let's do it 😄

**Comment by techanvil** [comment]
@nfmohit the IB looks good, please can you add an estimate?

**Comment by nfmohit** [comment]
Oops, my bad. Added an estimate of 7 to account for the testing.

**Comment by techanvil** [comment]
Thanks @nfmohit!

IB :white_check_mark:

**Comment by tofumatt** [comment]
Moving directly to Approval as I QA'd the test run myself on an ARM Mac and it passes CI, so no need for the duplicate QA.
