### ISSUE TITLE
Odd Loading behaviour of the callout tooltip for GA4 in Site Kit Settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5922]
## Bug Description

While testing #5621 I have an observation:

My test site only has a UA property set up.  As you can see from my screencast,  when clicking on the 'Connect Google Analytics 4' button and then editing the Analytics settings, the GA4 callout tooltip initially loads at the side of the property dropdown, and then a second later jumps to the top, and then when I scroll down, it jumps back to the side. 

Not a huge issue but a bit of an odd UX/UI experience I feel.

https://user-images.githubusercontent.com/73545194/192538216-ccfd05db-0697-40cf-87e8-53efde6d3cc3.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Set up Google Analytics" tooltip within Analytics settings should always be displayed to the right when the whole tooltip can fit in the current viewport. Otherwise it should be the top or bottom depending on if there was little space to the bottom or top of the Select field within the viewport.
* The tooltip should not change directions if the window size remains the same. It should only change from top to bottom if the user was scrolling the page downwards or vice versa.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
Can we please add a priority label here
cc @FlicHollis

**Comment by tofumatt** [comment]
ACs look good, moving to IB 👍🏻

**Comment by asvinb** [comment]
@wpdarren Can you check if you can reproduce? I spent some time trying to reproduce the issue you reported but was unable to.
![Oct-13-2022 13-28-34](https://user-images.githubusercontent.com/31818/195559715-da93ac1e-eecb-4d22-899b-77f885ff8035.gif)

**Comment by FlicHollis** [comment]
@mohitwp can you help with this in Darren's absence?

**Comment by wpdarren** [comment]
I'll pick this up and have a re-look at the issue @asvinb

**Comment by wpdarren** [comment]
@asvinb I am unable to recreate this issue.  

Tried it on a few different resolutions and the tooltip loads as expected. I will close this ticket.
