### ISSUE TITLE
Update translators comments for single placeholders

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5924]
## Feature Description

In https://github.com/google/site-kit-wp/issues/5463 we updated translators comments across the codebase to follow core's convention for strings with multiple translators (using integers to refer to numbered placeholders).

However, as an oversight some (perhaps all) translators comments for a _single placeholder_ were also replaced, which should not have been.

See https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#variables for core guidance about i18n.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Translators comments should follow the core guidelines for translation strings with one or multiple placeholders
	* Since multiple placeholders were addressed in #5463, this is primarily about fixing strings with only a single placeholder (usually `%s`)
* Strings with a single positional placeholder should use the placeholder in the translation string. E.g.  
    ```diff
    + /* translators: %s: Name of a city */
      __( 'Your city is %s.', 'my-plugin' ),
    ```
* Strings with multiple numbered placeholders, should use the respective numeric (integer) references to them
    ```diff
    + /* translators: 1: Name of a city 2: ZIP code */
      __( 'Your city is %1$s, and your zip code is %2$s.', 'my-plugin' ),
    ```

## Implementation Brief

- Using your editor, search for implicit translation string placeholders ([JS](https://github.com/alexei/sprintf.js#format-specification) and [PHP](https://www.w3schools.com/php/func_string_sprintf.asp)) with files related to testing excluded (*.test.js, *test.php, tests in VS Code)
- Jump from result to result and update any instances which contain one placeholder and change it as outlined in the AC

### Test Coverage

* N/A.

## QA Brief

* No QA needed as this is only updating the translation strings and the code has been reviewed by two engineers.

## Changelog entry

* Update "translators" placeholder comments when there is only one placeholder in a localization string.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by tofumatt** [comment]
No QA needed here as this has been approved by two engineers and requires no user-facing QA. Moving directly to approval.
