### ISSUE TITLE
Prevent loading if minimum WordPress version isn't met

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5926]
## Feature Description

Since the beginning, Site Kit has had logic in place to prevent loading the rest of the plugin if the minimum version of PHP was not satisfied. https://github.com/google/site-kit-wp/blob/bbe3ba6ff1e035146cc781887befdda9cc7021a5/google-site-kit.php#L110-L112

Similarly, there is a notice shown on activation if this condition isn't met https://github.com/google/site-kit-wp/blob/bbe3ba6ff1e035146cc781887befdda9cc7021a5/google-site-kit.php#L45-L51

With the upcoming work to raise the minimum required version of WordPress, we should apply the same safeguards for the WordPress version as we do for PHP.

Although related, this can and should be introduced independently from the other work to raise the minimum version as it applies even now.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new constant `GOOGLESITEKIT_WP_MINIMUM` should be defined in the plugin root, with a value of `4.7.0` (this will soon be changed but that will happen in another issue)
* A new error should be raised within `googlesitekit_activate_plugin` if the minimum WordPress version isn't met
	* > Site Kit requires WordPress version {min-wp-version} or higher
	* Append the error message for PHP to also say "or higher" for consistency
* The plugin loader should only be loaded if the minimum versions of WP and PHP are met

## Implementation Brief

* Define the new constant in `google-site-kit.php` as defined in the AC
* Add the check for WP version in `googlesitekit_activate_plugin` right after the check for the PHP version
* Update the error message for the PHP notice for consistency as mentioned in AC
* Update the condition to require `includes/loader.php` to include the added condition to meet the current WP version
* Use `get_bloginfo` to get the current version of WP, and PHP's `version_compare` to check the current version is greater than or equal to Site Kit's minimum version in checks, as we do for PHP

### Test Coverage

* No changes

## QA Brief

* Automated tests will ensure SK is still loading for our minimum supported versions and above
* Test activating Site Kit on a version of WordPress below the minimum
	* An error should be seen on activation
	* If already activated, Site Kit should not load or cause any fatal errors related to an insufficient version of WordPress
* It should be possible to deactivate SK when the minimum versions aren't met and it shouldn't leave the rest of WordPress in an unusable state

## Changelog entry

* Prevent loading plugin core if minimum WordPress version is not met.

**Comment by aaemnnosttv** [comment]
@FlicHollis this one is something we can get in now. It's related to the bump but not tied to it. Can we add it to the current sprint?

**Comment by FlicHollis** [comment]
HI @aaemnnosttv yes no problem, I will add this now, thanks!

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv this passes the QAB, but a question.  I am assuming we do not have any users on below 4.7.0, otherwise it would be an odd experience if they cannot suddenly use Site Kit, and since it's connected, no message appears unless they deactivate the plugin and try and activate it again.  Thought I'd double check. 

**Verified:**

- When activating Site Kit on a version of WordPress below the minimum (I used `4.6.24` version for testing) 
   - An error was seen on activation
  - When already activated, Site Kit did load or cause any fatal errors.
  - It was possible to deactivate SK when the minimum versions aren't met and it did not leave the rest of WordPress in an unusable state.  No errors or console errors appeared. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/193206117-202472e7-336e-4be8-8a83-2dd666f28a7b.png)
![image](https://user-images.githubusercontent.com/73545194/193206133-7daee013-5b79-4fd0-b4a6-9b403121eca0.png)
![image](https://user-images.githubusercontent.com/73545194/193206263-4d18b8fb-f8f6-4ebe-8a91-35367a088880.png)

</details>

**Comment by aaemnnosttv** [comment]
> I am assuming we do not have any users on below 4.7.0, otherwise it would be an odd experience if they cannot suddenly use Site Kit, and since it's connected, no message appears unless they deactivate the plugin and try and activate it again. Thought I'd double check.

@wpdarren we _shouldn't_ have any users on WP pre 4.7 as I don't think it would work, this is mostly in preparation for the min version bump. It would probably be a good idea to add a notice in this case as well but that wasn't included in the scope for this issue. I think it's more relevant for the upcoming bump as well. Let's open a new issue about surfacing the messages we have in a persistent way rather than on activation only.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When activating Site Kit on a version of WordPress below the minimum (I used `4.6.24` version for testing) 
   - An error was seen on activation
  - When already activated, Site Kit did load or cause any fatal errors.
  - It was possible to deactivate SK when the minimum versions aren't met and it did not leave the rest of WordPress in an unusable state.  No errors or console errors appeared. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/193206117-202472e7-336e-4be8-8a83-2dd666f28a7b.png)
![image](https://user-images.githubusercontent.com/73545194/193206133-7daee013-5b79-4fd0-b4a6-9b403121eca0.png)
![image](https://user-images.githubusercontent.com/73545194/193206263-4d18b8fb-f8f6-4ebe-8a91-35367a088880.png)

</details>
