### ISSUE TITLE
Site Kit not working properly on our site

### ISSUE THREAD

**Issue by robertjamesm** [google/site-kit-wp#593]
We have set up Site Kit on other sites and it works just fine. On our site it's not working properly data is not being populated. We are able to connect to every service and we can also see the tags on our site.

**Comment by jamesozzie** [comment]
@robertjamesm There could be a plugin, browser extension, firewall, VPN or other software blocking reporting. Can you check from other computer, using your browser's incognito mode and see if the same problem exists?

If the issue arises again please share the following:
- Any [console errors](https://i.imgur.com/f5WfLb3.png) that appear 
- Your [Site Health info](https://i.imgur.com/Rtkmsba.png)

**Comment by RazaGR** [comment]
see if its related https://github.com/google/site-kit-wp/issues/243#issuecomment-535479793

**Comment by jamesozzie** [comment]
@RazaGR Can you share any console errors and we can compare the issue from #243?

**Comment by RazaGR** [comment]
@jamesozzie I have solved the issue by using Nginx rewrite rules ( an mentioned in https://github.com/google/site-kit-wp/issues/243#issuecomment-535479793) , I don't have any more console errors, but it was identical with https://user-images.githubusercontent.com/24247981/64017869-1a3e0e80-cb44-11e9-81a6-d8f0a692b665.png
