### ISSUE TITLE
Stuck on loading when trying to set up GA4 property if REST API for Site Kit is disabled for user role

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5931]
Asana bug bash board: https://app.asana.com/0/1202913874897532/1203027928111306

This is pretty edge case but thought I would raise it in case it could be adjusted. If a users access to the REST API is disabled before setting up a GA4 property via the activation banner then when clicking the set up button it gets stuck on indefinite loading.

Would it be better to at least put in some form of error message here like we have for the dashboard widgets that inform the user that they need access to the REST API? 

I have attached a video of what you see in this situation. Note that the widgets below have the error message but the banner at the top is stuck on loading continuously. 

To do this I disabled the REST API using a plugin before setting up a GA4 property via the banner and then once disabled proceeded to try and set up the GA4 property. 

https://user-images.githubusercontent.com/93320881/192623980-88f5154d-cf77-4da1-bd44-5652800abe38.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@adamdunnage When trying to replicate this, I actually get the error message neatly within the GA4 Activation Banner. So this issue may have been fixed since this was raised - perhaps as part of another issue. Can you try to reproduce this again? Thanks.

https://user-images.githubusercontent.com/1721319/200202390-f3fd7001-068d-4ac3-bcb6-5020d0d500d3.mov

**Comment by adamdunnage** [comment]
@jimmymadon Yes you are right, I am also now getting this message instead of an indefinite load. Looks like this has since been fixed so happy for this to be closed. Thanks for looking at this.

**Comment by jimmymadon** [comment]
@adamdunnage Thanks! (and apologies for the issue assignment before this comment! 😄  I just didn't save the comment - was stuck in preview in my window for a day!)
