### ISSUE TITLE
Change icon for 1 July onwards banner

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5935]
After the 1 July 2023, the user who has not connected GA4 will see a specific banner informing them that UA is no longer reporting.  I feel that this should be a red warning icon like we have on the banner for 1-30 June.  See screenshots below. 

Bug Bash Asana task: https://app.asana.com/0/1202913874897532/1203046746328998

![image (14).png](https://images.zenhubusercontent.com/617a793eaff73620e5cd590d/d078e0af-2619-4106-9f25-a410035f2112)

![image (15).png](https://images.zenhubusercontent.com/617a793eaff73620e5cd590d/d052e92a-0776-4ba0-bf18-b979c96a626c)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@wpdarren This will be addressed as part of https://github.com/google/site-kit-wp/issues/5912 and can be closed.
