### ISSUE TITLE
Tooltip overlapping the header

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#5938]
## Bug Description
Currently tooltips have a very high `z-index` (20000) which results in them being on top of other elements on the page. However we have an issue with sticky elements where there is an overlap. This is the case with the header where on small screens, upon scrolling the page, the tooltip overlaps the header.

## Steps to reproduce

1. Go to the Analytics module setup screen on a mobile device/small viewport.
2. Click on 'Connect Google Analytics 4'
3. The tooltip is displayed.
4. Scroll up the page
5. Notice how the tooltip overlaps the header.

## Screenshots
<img width="434" alt="image" src="https://user-images.githubusercontent.com/31818/192833930-179e7f24-ba04-46f1-84f3-c3aca7f2aaee.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* The tooltip to setup a GA4 property only should not overlap the header upon scrolling on small screens.

## Implementation Brief
* Using `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`,
    * Update `JoyrideTooltip` to include the `styles` prop with the following value:
    ```js
    {
        options: {
            zIndex: 10,
        },
    }
    ```

### Test Coverage
* No new tests to be added.

## QA Brief

* Follow Steps to reproduce - tooltip should be fixed now as per screenshot: 
<img width="484" alt="Screenshot 2023-01-17 at 12 14 01" src="https://user-images.githubusercontent.com/16494321/212897079-da7f6650-1a0f-433e-9b9e-87abf11d1703.png">

## Changelog entry

* Prevent the "Set up Google Analytics 4..." Tooltip from overlapping the header on page scroll.

**Comment by aaemnnosttv** [comment]
@asvinb The tooltip you have shown is really a one-off feature tour (without the backdrop) which should be on a higher plane than pretty much everything else. If we want a different behavior in this case, we should maybe have a more "inline" version of this or perhaps add a class to this instance specifically which reduces its z-index rather than lowering it for all which would break tours that highlight elements of the header/navigation, for example.

**Comment by asvinb** [comment]
@aaemnnosttv Agree with not lowering the tooltip z-index globally but instead changing the z-index only to be lower than the header z-index only for this tour.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@sashadoes I have an observation that I'd like to run by you. 

All looks good on small screen sizes like mobile and tablet, but on desktop when I scroll down, the tooltip shifts placement and now it doesn't overlap the WordPress side menu, and looks a little odd.  

This is 1.92.0 the latest release 
![image](https://user-images.githubusercontent.com/73545194/213211793-0df09a60-3d60-44e0-adb0-212105e4e972.png)

This is how I see it now on the develop branch
![image](https://user-images.githubusercontent.com/73545194/213212192-d1a20902-72ac-4956-a840-f35c5ed8f483.png)

Interested in your thoughts here.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On small screen sizes, the tooltip to setup a GA4 property does not overlap the header upon scrolling.
- I also tested this on desktop to ensure that the behaviour is the same as currently. Found an issue which is now fixed. 
- Tested on various small screen devices like mobile and tablet on our supported browsers. 

**Note:**  I did discover a styling issue on small screen sizes related to the tooltip but it wasn't a regression related to this ticket, so will create a separate ticket for it. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/213397133-fd82fbc2-3d80-473a-8897-2a9a90e61b5d.png)
![image](https://user-images.githubusercontent.com/73545194/213397165-b0251fe0-ff7f-4256-acf8-232544449f3a.png)

</details>
