### ISSUE TITLE
Traffic sources in the Analytics tab

### ISSUE THREAD

**Issue by tamalweb** [google/site-kit-wp#594]
## Feature Description

Hello team, I am a fan of checking the traffic sources and how many people are visiting my site from organic, direct and from other sites. This way I won't have to visit the analytics site to see all these data. Can we implement this in the analytics tab? Thanks 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

* 

<img width="662" alt="Screen Shot 2019-09-25 at 5 27 53 PM" src="https://user-images.githubusercontent.com/41326532/65620521-e37bdc80-dfb9-11e9-9d52-222595a38885.png">

**Comment by aaemnnosttv** [comment]
Thanks for the suggestion @tamalweb ! If you haven't seen it already, we added this as part of the new All Traffic widget for Analytics released in [v1.25.0](https://github.com/google/site-kit-wp/releases/tag/1.25.0)! You can read all about it in [the announcement](https://sitekit.withgoogle.com/news/new-traffic-analytics-stats-site-kit/).

Closing as already addressed by other issues.
