### ISSUE TITLE
Use `require-await` in ESLint

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#5940]
## Feature Description

There are quite a few instances in our codebase where functions are declared as asynchronous with no `await` operator inside them. If not done intentionally, this can be a silly mistake that can be overlooked, especially during copying an existing function and changing its contents while leaving the `async` keyword mistakenly. In such cases, the asynchronous functions would unnecessarily return a Promise that may not be required.

To address this, we can consider introducing the [`require-await`](https://eslint.org/docs/latest/rules/require-await) rule in ESLint, which would warn us in such a case.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Add the [`require-await`](https://eslint.org/docs/latest/rules/require-await) rule in ESLint.
* All existing violations of the above rule should be fixed so that functions that should not necessarily be `async`, are not `async`.
* Ensure that these existing violations are not [instances where this rule should not be used](https://eslint.org/docs/latest/rules/require-await#when-not-to-use-it).

## Implementation Brief

* In `.eslintrc.json`, add the `require-await` rule with the value `error` under the `rules` property.
* Run `npm run lint:js` to see that all existing `Async arrow function has no 'await' expression` errors.
* Fix all the errors (including the test files) by removing the `async` keyword from the function declaration/expression.
* Ensure these existing violations are not [instances where this rule should not be used](https://eslint.org/docs/latest/rules/require-await#when-not-to-use-it). Disable the rule for any such instances.

### Test Coverage

* No new tests are to be added.

## QA Brief

- This doesn't involve any feature/interface changes.
- Ensure there are no regressions due to these changes.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
ACs are good 👍🏻

**Comment by techanvil** [comment]
@hussain-t the IB looks good. I made a small tweak to clarify the last point, adding "Disable the rule for any such instances".

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Ensured there are no regressions due to these changes. Had a chat with Hussain and the focus on this testing is setting up Site Kit and the modules. No issues found.
