### ISSUE TITLE
GA4 Activation Banner: Success Banner no longer displaying.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5945]
## Bug Description

The Success Banner at the end of the GA4 Activation Banner flow is no longer appearing.

This seems to be a regression introduced in 1.84.0, as it works in 1.83.0

## Steps to reproduce

1. Set up Site Kit to display the GA4 Activation Banner.
2. Go through the GA4 Activation Banner flow, clicking on **Set up now** and then **Connect** or **Create property**.
3. Upon success the GA4 Activation Banner will no longer display, instead of showing the "You successfully set up your Google Analytics 4 property" Success Banner.

## Screenshots

This is what should display once the GA4 property has been set up, however the banner no longer displays at this point:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/a5f6a964-16a1-43c7-845e-854c6c047843)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.84.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the GA4 Activation Banner, the Success Banner should be displayed upon successful connection of the GA4 property.

## Implementation Brief

- In `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/index.js`:
    - Remove the condition that renders a banner only if UA is connected but GA4 is not connected.
	- Change the default state of `step` to be `null`.
	- Using the `useEffect` hook, set the `step` state to `ACTIVATION_STEP_REMINDER` when the following conditions meet:
	    - `step` state is `null`.
		- UA is connected.
		- GA4 is not connected.

### Test Coverage

* No tests need to be added/updated.

## QA Brief

- Set up Site Kit to display the GA4 Activation Banner.
- Go through the GA4 Activation Banner flow, clicking on **Set up now** and then **Connect** or **Create property**.
- Ensure upon success, the GA4 Activation (success) Banner is displayed.

## Changelog entry

* Fix bug that could cause GA4 Success banner after activation not to appear.

**Comment by mohitwp** [comment]
QA Update ✅ 

- Verified on dev environment.
- GA4 Activation Banner: Success Banner is now displaying when user set up new property or connect existing property successfully.
- Under settings > Analytics showing connected after successful set up.

<details>


https://user-images.githubusercontent.com/94359491/194876918-bacdc120-4b3f-4fae-b268-4cfe388fa172.mp4


https://user-images.githubusercontent.com/94359491/194876958-4ad59863-1f2f-44f2-8ead-40a43213db7f.mp4

</details>
