### ISSUE TITLE
Refactor TwG color choices with single component

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5948]
## Feature Description

The color choices for the TwG customization interface currently utilize the new custom `ImageRadio` component along with a corresponding SVG graphic for each choice. This works fine but is more complicated than necessary. The only difference between each choice are the two colors, everything else about them should be the same. This lends itself to using a single choice component with props for the colors which can be reused for all the choices. In the future, we could add new choices (should they be supported) without needing any additional components.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All `svg/graphics/twg-*.svg` color choice graphics should be consolidated into a single new React component with props for primary and secondary colors
	* The consuming usage of these graphics should be refactored to use the new component instead, providing the color definitions (which can be sourced from the svg files)
	* The corresponding .svg files should be removed

## Implementation Brief

* Create a new `ColorThemeChoice` component using the contents of one of the svg files (e.g. `assets/svg/graphics/twg-blue.svg`) as the body of the component
	* Accept a `colorPrimary` and `colorSecondary` as props, passing the provided values to the respective `fill` attributes where colors are currently used
	* The primary color should be used in place of the darker/bold color, and the secondary the other 
      <img width="391" alt="image" src="https://user-images.githubusercontent.com/1621608/193324909-d080ec48-b255-4fbf-9af2-00f19cca1701.png">

**assets/js/modules/thank-with-google/util/settings.js**

- Update `getColorThemes` to remove the `svg` prop, and add `colorPrimary` and `colorSecondary`

**assets/js/modules/thank-with-google/components/common/ColorRadio.js**

- Update the use of `getColorThemes` to source the `SVG` element from the new `ColorThemeChoice` component, passing in the color props for each

### Test Coverage

* No changes expected

## QA Brief

* Locate the color choices in the TwG setup settings (radio buttons with two-toned graphics).
* Ensure that there are no visual changes compared to the previous release. 

## Changelog entry

* Refactor Thank with Google color choices to a shared component.

**Comment by tofumatt** [comment]
Good call!

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:

- The colour choices in the TwG setup settings have no visual changes compared to the previous release.
- Tested when setting up TwG for the first time and also editing settings. 
- Checked that the correct colour appeared in the settings and also on the front end for the badge and widget. 

![image](https://user-images.githubusercontent.com/73545194/198428219-6ad9da26-e2b6-438a-96d4-54ff3b4096d0.png)
![image](https://user-images.githubusercontent.com/73545194/198428261-67bf354b-f374-4b0a-84e2-602cccfd117a.png)
