### ISSUE TITLE
Site Kit Get OAuth Credentials not generating snippet

### ISSUE THREAD

**Issue by evelyn** [google/site-kit-wp#595]
Good morning,

I am unable to setup site-kit-wp on my site, the only thing generated by [the site kit client configuration generation page](https://developers.google.com/web/sitekit) is an API key and no snippet.  This API key is not accepted into the client configuration field on the plugins installation page, leading me to believe that there is an outside issue potentially causing this problem.

**Comment by jamesozzie** [comment]
@evelyn We're already tracking this issue in #561 and are working hard on resolving it. In the meantime, a possible workaround has been posted in the same issue.
