### ISSUE TITLE
Update PSI setup flow to remove use of API key

### ISSUE THREAD

**Issue by lilybonney** [google/site-kit-wp#596]
## Feature Description

Currently, the Page Speed Insights module (PSI) requires an API key for authentication, entered into a custom UI (built for this purpose).

This ticket is to cover the engineering work required to update the PSI setup flow to use the same federated authorisation as all other Site Kit APIs.

Work here is thematically linked to issue #590 (although not dependent upon it). Further issues may be required, to cover additional changes to support the new setup flow.

Screenshots for reference:

https://d3k6hi3h4ykoab.cloudfront.net/items/2l1v20410m2g0U0F2G10/Site_Kit_by_Google_Settings_9_Site_Kit_for_WordPress__WordPress_2019-09-25_14-01-17.jpg

https://cl.ly/ed13856bea5b

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
I think there was a misunderstanding in our conversation regarding this, as there is already #511 to cover this change. I think with that one we're covered. :)
