### ISSUE TITLE
TwG terminology changes

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5963]
There have been some terminology changes from the TwG team as commented in this ticket https://github.com/google/site-kit-wp/issues/5755. We are moving these out to be a ticket of their own for clarity. 

The TwG team have let us know that they have changed the terminology from "Publisher ID" to "Thank with Google ID." 

The TwG team also don't want to use the term "Publisher Center" any longer; it should be "Thank with Google profile." So to summarize:

References to "Publisher ID" or "Publication ID" should be changed to "Thank with Google ID"
References to "Publisher center" should be changed to "Thank with Google profile"

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instances of "Publisher ID" in Thank with Google UI should be changed to "Thank with Google ID". _(Note: This doesn't actually apply to Site Kit as we don't use that term for TwG anywhere. But listed here for posterity.)_
* All instances of "Publisher center" in Thank with Google UI should be changed to "Thank with Google profile".
* Other instances of these terms outside the TwG UI should not be changed.

## Implementation Brief

In `assets/js/modules/thank-with-google/components/setup/SetupPublicationPendingVerification.js`,
`assets/js/modules/thank-with-google/components/settings/SettingsView.js`,

* Search for and replace instances of "Publication ID" and "Publisher center" to the new wording, as per the AC

### Test Coverage

* N/A

## QA Brief

* In the settings view `Publication ID` should be changed to `Thank with Google ID`
* In Setup, Pending verification `Publisher Center` should be changed to `Thank with Google profile`
Eg -> 
<img width="1504" alt="Screenshot 2022-10-08 at 23 34 00" src="https://user-images.githubusercontent.com/16494321/194730043-17658032-9a7d-4741-829a-30663b123e7d.png">

## Changelog entry

* Update Thank with Google copy in settings and setup screens.

**Comment by makiost** [comment]
@tofumatt @FlicHollis Didn't manage to find any references to "Publisher ID", other than in AdSense, hence only referencing "Publication ID" in the IB. Should the AC be updated to reflect that?

**Comment by tofumatt** [comment]
@makiost Huh, fair point.

I'll leave the ACs as-is but add a note that this was an instruction from the TwG team and that it doesn't apply to us. Maybe there are other things using that term 😅 

IB ✅

**Comment by tofumatt** [comment]
@mohitwp Those aren't publicly-visible strings; they're developer messages/errors that shouldn't appear in production code.

Internally we still use `publicationID` as a setting/option variable name; this issue is just for user-facing strings, so that's okay. 👍🏻 

I'll move this to approval since the other QA is okay 🙂
