### ISSUE TITLE
Setup Once, Enable for ALL Admin Users or Select Users

### ISSUE THREAD

**Issue by VR51** [google/site-kit-wp#5964]
SiteKit is great in theory but please please please allow the person who configures SiteKit (usually a site admin) to enable all site admins or select user groups or select registered users to view all or select data presented by SiteKit in both the WP dashboard, the pages and the SiteKit admin pages. It is beyond ridiculous that each site admin must authorise SiteKit for themselves and use the same Google account as the person who originally setup SiteKit (or authorisation is lost for the original agent of authorisation) in order that he/she can see Analytics, PageSpeed or Optimize data. What gives with this awkwardness? No other analytics plugin puts users through so many hoops.

When you enable this single setup for all/select users feature, please make it easy for the site administrator to authorise other users to view SiteKit pages and data without making them go through the Google/SiteKit Auth procedure all over again. It's tedious.

For a company that wants to tell others how to build their websites, Google sure is bad at the user experience stuff. I'm not the only one who thinks this.

**Comment by jamesozzie** [comment]
Thanks for your feedback @VR51. 

> It is beyond ridiculous that each site admin must authorise SiteKit for themselves and use the same Google account as the person who originally setup SiteKit 

Site Kit can be set up by one WordPress administrator at present, with other administrators needing to set up the plugin only. They can use their own Google account, not the same Google account used by an administrator who initially set up the plugin and connected the various modules (ie. Google Analytics or AdSense). They can then view existing data within the Site Kit dashboard if the administrator who connected the modules granted them access via their own Google account. 

The reason all administrator roles require their own Google account is for authentication and verification purposes, with Site Kit displaying data from users Google service accounts. 

> When you enable this single setup for all/select users feature, please make it easy for the site administrator to authorise other users to view SiteKit pages and data without making them go through the Google/SiteKit Auth procedure all over again. It's tedious.

We are working on a dashboard sharing feature, which we expect to be ready soon. This will allow for the use case you suggested above, administrators can share a view only version of the Site Kit dashboard with others, including non administrators. This won't require the user who has been granted access to go through the OAuth permissions process. 

As we have an open GitHub issue on this (https://github.com/google/site-kit-wp/issues/6) I'll close this particular issue. I'll also request an update within that issue based on your topic and other users who have asked. Thank you!

**Comment by VR51** [comment]
Thank you for your reply, @jamesozzie. I will follow the other ticket.
