### ISSUE TITLE
Enhance `BannerNotification` to better support an elemental `description`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5972]
## Feature Description

The `BannerNotification` component currently allows for a non-scalar `description` to be provided in the form of a React element. If provided it allows for more control over that part of the output but  currently somewhat enforces that the given element is a valid child of a `p` tag since the entire description is always rendered within one. This undermines the purpose of the prop's flexibility and requires consumers to do odd things (e.g. if multiple paragraphs were desired instead of one) to work around it.

![screenshot](https://user-images.githubusercontent.com/24408261/194105890-739bbe76-b130-48f3-bfb5-d50be71eabb3.png)

https://github.com/google/site-kit-wp/blob/da8f2f9d312a71f0806888968fed60190a6d7bf9/assets/js/components/notifications/BannerNotification/index.js#L287-L292

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `BannerNotification` should be updated such that if a valid element is provided for its `description`, the given description is rendered as-is (without an added wrapper).
	*  The case for when a non-element is provided should be updated to render the `p` tag with inner HTML set as it is now on the span tag
* Consuming use of `BannerNotification` should be updated to preserve the current styling where needed although exceptions can me made on a case-by-case basis.

## Implementation Brief

- In `assets/js/components/notifications/BannerNotification/index.js`:
    - In the `inlineMarkup` variable assignment, locate the `<p>` tag inside the `.googlesitekit-publisher-win__desc` element.
	- Remove this wrapping `<p>` tag preserving all its internal contents.
	- In the condition where the `description` prop is not a valid element, wrap the existing `<span>` tag with a new `<p>` tag.
	- Wrap the adjacent elements, i.e. the "learn more" link and the "page index" in a new `<p>` tag.
- In `assets/js/components/notifications/ThankWithGoogleSupporterWallNotification.js`:
    - In the rendered `<BannerNotification>` component, update the `description` prop so that its contents are wrapped with a `<p>` tag instead of a `<Fragment>`.
- In `assets/js/components/ErrorHandler/index.js`:
    - In the rendered `<BannerNotification>` (imported as `<Notification>`) component, update the `description` prop so that its contents are wrapped with a `<p>` tag instead of a `<Fragment>`.

### Test Coverage

- No tests need to be added/updated. Optionally/time-permitting: add a few tests to cover this behaviour.
- Update VRT references if required.

## QA Brief

* Check notification banners to appear and function correctly on a page and no Warning (from AC) appears on the page. (Eg. `ActivationBanner`, `ThankWithGoogleSupporterWallNotification`, `SetupSuccessBannerNotification`, `AdSenseAlerts` etc...)
* Description part of a banner should always appear inside single `<p>` as per the screenshot below:
<img width="1283" alt="Screenshot 2022-10-18 at 13 47 36" src="https://user-images.githubusercontent.com/16494321/196433854-041f1c86-7c47-42c6-ba5c-a059c57e0680.png">

( This ticket is technical and brings no updates to UI/UX. All functionality should remain the same )

## Changelog entry

* Enhance the BannerNotification component to better support a description which is a React element.

**Comment by nfmohit** [comment]
If we decide to wrap the adjacent elements (e.g. the learn more link) in their own `<p>` tag, this is how the difference would look:

Now:
![image](https://user-images.githubusercontent.com/20284937/194698127-7dd807f0-fe59-46e7-9ec7-9644553f29d7.png)

After change:
![image](https://user-images.githubusercontent.com/20284937/194698148-c2faa259-bca1-47f7-9d37-517b1fcfa67f.png)

I have added the IB with this approach but will change it if required based on the IBR.

**Comment by tofumatt** [comment]
Looks good, but this is probably a 7 estimate, as a fair number of components are affected and should be reviewed/QA'd.

Plus: it'd be good to add a test or two for this new behaviour to make sure it's preserved. I added mention of this to the IB, but otherwise looks good.

IB ✅

**Comment by nfmohit** [comment]
Thank you for the review and updates, @tofumatt!

**Comment by tofumatt** [comment]
@techanvil pointed out that some questions around layout weren't 100% answered here, but we shouldn't change the visual layout of the "Learn more" link in [this example](https://github.com/google/site-kit-wp/issues/5972#issuecomment-1269584251).

It's okay to change the markup here to something a bit more semantic (a `<p>` link @nfmohit proposed, or even a `<div>`), but _visually_ the "Learn more" link or other text that would accompany that content should—by default—be _inline_ and not on a _new line_.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Based on the QAB this has passed my checks.  I went through the various banner notifications. They are displayed and functioned as expected with no warning. (Eg. ActivationBanner, ThankWithGoogleSupporterWallNotification, SetupSuccessBannerNotification, AdSenseAlerts etc...)  Also, the description part of a banner always appear inside single `<p>` as you can see from my screenshots. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/198556361-0b81b19d-3036-428a-b1ef-21428cf18752.png)
![image](https://user-images.githubusercontent.com/73545194/198556380-274b3e3d-8b6e-4337-9db7-9797bfe6bd06.png)
![image](https://user-images.githubusercontent.com/73545194/198556394-db0a0bcc-b795-47a5-a11a-e9af3308fc90.png)
![image](https://user-images.githubusercontent.com/73545194/198556435-38c08643-c3c2-4e02-b360-8078349bdd42.png)

</details>
