### ISSUE TITLE
Loading chunk 33 failed. 

### ISSUE THREAD

**Issue by faizxmohammad** [google/site-kit-wp#5973]
(error: http://kdramatic.live/wp-content/plugins/google-site-kit/dist/assets/js/33-fb84bd62cbb49a617806.js)
    in Unknown
    in LazyContentSVG
    in Suspense
    in ContentSVG
    in div
    in div
    in div
    in Cell
    in div
    in ForwardRef
    in ForwardRef
    in ContentAutoUpdate
    in div
    in ForwardRef
    in section
    in AdSenseConnectCTA
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in AdSenseConnectCTAWidget
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in ForwardRef
    in div
    in div
    in ForwardRef
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root

**Comment by faizxmohammad** [comment]
Please help me resolve this issue , i have done everything but I am still facing the same issue.
I cant access the dashboard of Google SiteKit

**Comment by jamesozzie** [comment]
Hi @faizxmohammad,

Thanks for getting in touch. From reviewing your [public REST endpoints](https://i.imgur.com/5jviKGp.png) it looks like you may have your site defined as insecure (http), despite being fully secure with a valid https certificate active. Can you review your [WordPress general settings](https://drive.google.com/file/d/1Rr1W7Bkj-m-9ywZ_gYEDm3h4Vskr-URX/view?usp=sharing) and ensure your site records reflect your secure status, by changing the `http` prefix to `https`. After doing so, please attempt Site Kit set up once more. 

Note also that I'll close this support topic as we provide initial support queries from the [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit). If you encounter any further errors after making the changes above, please open [an individual support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) and we can assist with your site individually.
