### ISSUE TITLE
Persist TwG supporter wall notification dismissal

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5979]
## Feature Description

In #5538, we added the supporter wall notification. This should be updated so that the dismissal is permanent – currently it is only temporary due being client-side only.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Thank with Google supporter wall reminder notification should be updated so that if dismissed, it is no longer shown again
    * This should be done using a dismissed item (see `IdeaHubPromptBannerNotification` for an example)

## Implementation Brief

- In `assets/js/components/notifications/ThankWithGoogleSupporterWallNotification.js`:
    - We are going to follow the approach in `assets/js/components/notifications/IdeaHubPromptBannerNotification.js`.
    - Create a new constant named `NOTIFICATION_ID` with the value `twg-supporter-wall-prompt`.
	- Replace the value of the `id` prop in the rendered `<BannerNotification>` component with `NOTIFICATION_ID`.
	- Add an `onDismiss` prop to the `<BannerNotification>` component, value of which should be a function that dispatches the `dismissItem` action from the `core/user` store, with `NOTIFICATION_ID` passed to it.
	- Determine if the notification is dismissed using the `isItemDismissed` selector from the `core/user` store, with `NOTIFICATION_ID` passed to it.
	- If the above selector returns a truthy value, return `null` from the component instead of the notification.

### Test Coverage

* No tests need to be added/updated.

## QA Brief

* Make The Thank with Google supporter wall reminder notification banner appear
* Dismiss Thank With Google Supporter Wall Notification by clicking `Maybe later` 
* The Notification should not appear again 

## Changelog entry

* Persist Thank with Google supporter wall notification dismissal.

**Comment by tofumatt** [comment]
IB ✅

**Comment by sashadoes** [comment]
I think there is a typo in IB first line "In `assets/js/components/notifications/IdeaHubPromptBannerNotification.js`" and `ThankWithGoogleSupporterWallNotification` was meant instead ? @tofumatt / @EvanHerman 😇

**Comment by nfmohit** [comment]
@sashadoes You're right. That was a mistake. I have updated the IB.

CC: @tofumatt

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When the Thank with Google supporter wall reminder notification banner appears, and the user clicks on the Dismiss Thank With Google Supporter Wall Notification by clicking Maybe later, the notification does not appear again

https://user-images.githubusercontent.com/73545194/197991148-5a65e892-943a-4205-a497-fb9d8a124d6d.mp4

**QA Note for future reference.** To trigger the supporter wall reminder notification you have to go into the database and look for `wp_options` table, change the value of `_transient_timeout_googlesitekit_thank_with_google_setup ` to the current timestamp. To find the current timestamp go to [Epochconvertor.com]( https://www.epochconverter.com/) and copy paste the current Unix epoch time into the value for the field above.
