### ISSUE TITLE
Close button (hover/focus states) overlapping input border 

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#5980]
## Steps to reproduce

1. Go to the main dashboard
2. Click on the "URL search" button in the header.
3. Hover the "Close" icon
4. Notice how the icon overlaps the input border.

## Screenshots
![Oct-07-2022 18-43-03](https://user-images.githubusercontent.com/31818/194581163-4a3168b9-f824-4854-bdba-313d8d66cf2a.gif)

## Additional Context

 - Browser: Chrome
 - Plugin Version: latest

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The hover/focus state of the header search input's close button should not overlap the input's border

## Implementation Brief

* Inside `google-site-kit/assets/sass/components/global/_googlesitekit-entity-search.scss`:
    * Locate `.googlesitekit-entity-search__close` and `.mdc-button.googlesitekit-entity-search__close`
        * Remove `.mdc-button.googlesitekit-entity-search__close` selector and styles
        * In `.googlesitekit-entity-search__close` remove everything except: `border-radius` equals `50%`, `height` equals `30px`, `width` equals `30px`

### Test Coverage

* No tests are needed 

## QA Brief

* Check that the entity search's close button does not overlap with the search field when hovered/interacted-with

## Changelog entry

* Update styling of entity search close button to not overlap with the input's border.

**Comment by asvinb** [comment]
@sashadoes IB looks good to me, however can you clarify the following point:
> Remove .mdc-button.googlesitekit-entity-search__close styles which does not make sense

So are we removing the selector completely or removing styles which do not make sense? Looking again at the code, not sure why we had to bump the specificity of `googlesitekit-entity-search__close` by adding `.mdc-button`, but if we can remove it, then it's better!

**Comment by asvinb** [comment]
@sashadoes I would also bump the estimate to 7 because QA will need to check in different browsers :)

**Comment by asvinb** [comment]
IB 👍

**Comment by vedant-z** [comment]
@asvinb May I work on this issue please?

**Comment by aaemnnosttv** [comment]
@bethanylang this is a quick fix with a PR from the community so I've added it to the release! 😄

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested on latest versions of Firefox, Edge, Chrome, and Safari Browser.
- Tested on both main and entity dashboard.
- Verified the hover/focus state of the header search input's close button is not overlapping the input's border.


<details>

![image](https://user-images.githubusercontent.com/94359491/228448842-7ad8f838-a16f-4a53-862f-1ef2be2b8995.png)

</details>
