### ISSUE TITLE
Refactor undocumented use of `add_submenu_page` with `null` parent slug to register a hidden admin page. 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5998]
## Bug Description

Currently, we have few instances of `add_submenu_page` call with a `null ` parent slug to register WordPress admin page without showing it to the menu. While it's a well-known hack and works, this raises a few deprecation warnings in PHP8.1. See #5110 

There are other ways to do it without raising the warning and we should explore that. 

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by mohitwp** [comment]
Issue reported [here](https://github.com/google/site-kit-wp/issues/5110#issuecomment-1359289546) will resolve through this ticket.

**Comment by aaemnnosttv** [comment]
This was addressed in #6668.
