### ISSUE TITLE
Implement TwG custom GA events for publication setup

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6012]
GA events for the first part of the TwG setup (prior to customization) should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

For all of the following GA events, the event category should be `{viewContext}_thank-with-google`.
* Based on the TwG "publication state" received (i.e. based on which version of the UI is shown for the first TwG setup step), a custom GA event should be sent:
    * Event name: `receive_publication_state`
    * Event label: One of `NO_ACCOUNT`, `ONBOARDING_ACTION_REQUIRED`, `PENDING_VERIFICATION`, or `ONBOARDING_COMPLETE`
* When the user clicks the button to create a new publication (in the `NO_ACCOUNT` case above), a custom GA event with name `create_publication` should be sent (no event label).
* When the user clicks the button to complete their publication setup (in the `ONBOARDING_ACTION_REQUIRED` case above), a custom GA event with name `complete_publication_setup` should be sent (no event label).
* When the user clicks the button to review their publication status (in the `PENDING_VERIFICATION` case above), a custom GA event with name `review_publication_state` should be sent (no event label).
* When the user clicks the button to proceed to "Customize" after successful publication setup (in the `ONBOARDING_COMPLETE` case above), a custom GA event with name `customize` should be sent (no event label).

#### action: `receive_publication_state`

* Add an effect hook in the TwG `SetupMain` component to track the `receive_publication_state`
	* As soon as `currentPublication.onboardingState` is available, call `trackEvent` with this value as the event label, using the event category, and action (name) from the AC
	* Using the onboarding state as a dependency of the effect will cause it to run every time it changes, so it should only run once under normal conditions, but we'd want to make sure that it runs again when `useRefocus` runs
	* Ensure it doesn't call track event with an empty/undefined onboarding state

#### action: `create_publication`

- Update the cta `Button` in `SetupCreatePublication` with an `onClick` handler to call `await trackEvent` using the attributes in the AC before navigating

#### action: `complete_publication_setup`

- Update the cta `Button` in `SetupPublicationActionRequired` with an `onClick` handler to call `await trackEvent` using the attributes in the AC before navigating

#### action: `review_publication_state`

- Update the cta `Button` in `SetupPublicationPendingVerification` with an `onClick` handler to call `await trackEvent` using the attributes in the AC before navigating

#### action: `customize`

- Update the `onClick` handler in `SetupPublicationActive` with a call to `await trackEvent` using the attributes in the AC before navigating

### Test Coverage

* No changes necessary

## QA Brief

* Install Google Analytics Debugger. 
* Check the mentioned areas of TwG Setup screens and make sure the GA event category, name and labels match with the AC. 

## Changelog entry

* Measure interactions related to publication setup for Thank with Google.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

When the user clicks the button to create a new publication, a GA event with name `create_publication` is sent.
When the user clicks the button to complete publication setup, a GA event with name `complete_publication_setup` is sent.
When the user clicks the button to review their publication status, a GA event with name `review_publication_state` is sent
When the user clicks the button to proceed to "Customize" after successful publication setup, a  GA event with name `customize` is sent.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/196692268-7f93d3c5-53f4-4c57-a935-51a1f5b98b24.png)
![image](https://user-images.githubusercontent.com/73545194/196692258-4234640b-8d23-45a5-bbe9-cab2c22197d5.png)
![image](https://user-images.githubusercontent.com/73545194/196692281-902eb405-a6d1-4adb-973e-358d33961168.png)
![image](https://user-images.githubusercontent.com/73545194/196692297-db33d1b9-4d10-4bd7-a981-5abaac61cf52.png)

</details>
