### ISSUE TITLE
Implement TwG custom GA events for customization

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6013]
GA events for the second part of the TwG setup (customization) and similar settings interactions should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

For all of the following GA events, the event category should be `{viewContext}_thank-with-google`.
* When changing the TwG button/CTA type, a custom GA event should be sent:
    * Event name: `change_cta_type`
    * Event label: either `overlay` or `fixed`, based on what the user selected
* When changing the TwG button/CTA prominence (in case of `overlay`), a custom GA event should be sent:
    * Event name: `change_cta_prominence`
    * Event label: either `low` or `high`, based on what the user selected
* When changing the TwG button/CTA position (in case of `fixed`), a custom GA event should be sent:
    * Event name: `change_cta_position`
    * Event label: either `auto`, `above-content`, `below-content`, or `below-first-paragraph`, based on what the user selected
* When changing the TwG color theme, a custom GA event should be sent:
    * Event name: `change_color_theme`
    * Event label: the color slug/string identifier, based on what the user selected
* When changing the TwG button/CTA post types, a custom GA event should be sent:
    * Event name: `change_cta_post_types`
    * Event label: comma separated list of post type slugs/string identifiers, based on what the user selected
* All of the above events should be fired for the setup customization step and in settings. The only difference there would be the event category (which would be handled automatically via the `viewContext` variable).

#### action: `change_cta_type`

* Update `onChange` handler to `TypeRadio` in `CTAPlacement` to call `trackEvent` with the attributes defined in the AC

#### action: `change_cta_prominence`

* Update `onChange` handler within `ProminenceRadio` to call `trackEvent` with the attributes defined in the AC

#### action: `change_cta_position`

* Update `onChange` handler within `PositionRadio` to call `trackEvent` with the attributes defined in the AC

#### action: `change_color_theme`

* Update `onChange` handler within `ColorRadio` to call `trackEvent` with the attributes defined in the AC

#### action: `change_cta_post_types`

* Update `toggleChip` handler within `PostTypesSelect` to call `trackEvent` with the attributes defined in the AC

### Test Coverage

* No changes necessary

## QA Brief

- Ensure that the `twgModule` feature flag is enabled.
- Ensure that `Tracking` is enabled in Site Kit `Admin Settings`.
- While setting up Thank with Google, reach the step which lets you customise its appearance.
- Using a browser extension like [this](https://chrome.google.com/webstore/detail/jnkmfdileelhofjcijamephohjechhna), verify that all the custom GA events mentioned in the ACs are triggered with appropriate attributes.
- After setup, go to `Settings->Connected Services` and edit the `Thank with Google` module.
- Verify that the events are also triggered during updating the settings.

## Changelog entry

* Measure interactions when changing Thank with Google configuration.

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ 

@nfmohit. An observation: If you use all or any of the defaults when setting up TwG, none of the GA events are tracked.  They only get tracked when you click on the particular individual settings.  Is this expected? I suspect not. 

**Verified:**

The context was `moduleSetup_thank-with-google`

- When changing the TwG button/CTA type, a custom GA event is sent:
  - Event name: `change_cta_type`
  - Event label: either overlay or fixed.

- When changing the TwG button/CTA prominence (in case of overlay), a custom GA event is sent:
  - Event name: `change_cta_prominence`
  - Event label: either low or high.

- When changing the TwG button/CTA position (in case of fixed), a custom GA event is sent:
  - Event name: `change_cta_position`
  - Event label: either auto, above-content, below-content, or below-first-paragraph.

- When changing the TwG color theme, a custom GA event is sent:
  - Event name: `change_color_theme`
  - Event label: the color slug/string identifier.

- When changing the TwG button/CTA post types, a custom GA event should be sent:
  - Event name: `change_cta_post_types`
  - Event label: comma separated list of post type slugs/string identifiers.

I tested all of the events above in the settings but the context was `settings_thank-with-google`

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/196665320-7061d00d-2cad-4611-bc72-af6e9390893e.png)
![image](https://user-images.githubusercontent.com/73545194/196665331-8098ec3c-a081-4065-af95-2bd4c62fab85.png)
![image](https://user-images.githubusercontent.com/73545194/196665348-e07def7b-a21d-4c6d-80d1-2fdcee6f4ae9.png)
![image](https://user-images.githubusercontent.com/73545194/196665369-6fb3c3db-a7bd-4337-9557-eea8db459374.png)
![image](https://user-images.githubusercontent.com/73545194/196665410-9227f0be-e2c9-4cd2-812e-97bda3fe9c08.png)
![image](https://user-images.githubusercontent.com/73545194/196665437-2f32131f-ab3e-40d4-8fae-ce55eea1f45e.png)
![image](https://user-images.githubusercontent.com/73545194/196665486-e4a4d22b-ddfb-4db6-99aa-29bf6f4d7148.png)
![image](https://user-images.githubusercontent.com/73545194/196665521-1db43132-a6fc-4a70-b209-d5317d380d4f.png)
![image](https://user-images.githubusercontent.com/73545194/196665543-1d3bd4f3-31c0-471e-bb62-8d1e2a25ab8f.png)

</details>

**Comment by tofumatt** [comment]
From the ACs here, these should only fire on change, presumably because otherwise it would be the defaults for every user. I assume the intent of the events here is to capture when a user changes to non-default settings (and/or when they change back to the defaults from a non-default setting).

So this is working as intended I think, but worth being checked by @felixarntz or @aaemnnosttv during approval.

I think that's QA ✅  for now 👍🏻
