### ISSUE TITLE
Implement TwG custom GA events for supporter wall banner notification

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6014]
GA events for the TwG supporter wall reminder banner notification should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

For all of the following GA events, the event category should be `{viewContext}_thank-with-google-supporter-wall-notification`.
* When the user sees the TwG supporter wall reminder banner notification, a custom GA event with name `view_notification` should be sent.
* When they click on the primary CTA button in that notification, a custom GA event with name `confirm_notification` should be sent.
* When they dismiss that notification, a custom GA event with name `dismiss_notification` should be sent.

## Implementation Brief

* Update `ThankWithGoogleSupporterWallNotification` as follows

#### action: `view_notification`

* Call `trackEvent` with the attributes in the AC with a `useMount` (see `SetupSuccessBannerNotification`)

#### action: `confirm_notification`

* Add an `onCTAClick` prop to the inner `BannerNotification` passing a function that calls `trackEvent` with the attributes in the AC (see `CoreSiteBannerNotification`)

#### action: `dismiss_notification`

* Add an `onDismiss` prop to the inner `BannerNotification` passing a function that calls `trackEvent` with the attributes in the AC (see `CoreSiteBannerNotification`)

### Test Coverage

* No changes necessary

## QA Brief

- Setup Thank with Google using a VPN connected to the US region.
- Do not add any supporter wall widgets.
- Using the Google Analytics Debugger extension, ensure the `view_notification` GA event isn't triggered for the `mainDashboard_thank-with-google-supporter-wall-notification` category.
- Within the database -> `wp_options` table, change the value of `_transient_timeout_googlesitekit_thank_with_google_setup ` to the current timestamp.
- Clear the session and refresh the Site Kit dashboard and ensure the `view_notification` event is triggered when the banner notification appears.
- Click the `Add Supporter Wall widget` primary CTA and ensure the `confirm_notification` event is triggered.
- Click the `Maybe later` secondary CTA and ensure the `dismiss_notification` event is triggered.

## Changelog entry

* Measure interactions with Thank with Google supporter wall banner notification.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t I'd like to run an observation by you. 

When you set up TwG, the transient timestamp is `1666146812` which is 7 days from the setup. I change the time on my computer to after 7 days (also tried 8 days) in the future and I expect the banner to appear informing me to add a supporter wall widget.  Nothing does appear though. I've also changed the timestamp in the Db and changed my computer time to be past this date and no banner appears. 

Would you expect the banner to appear based on the scenario above?  

When I change the transient to the current timestamp then the banner does appear and this passes the QAB.  

**Verified:**

- When Site Kit and TwG is initially set up the` view_notification` GA event isn't triggered for the `mainDashboard_thank-with-google-supporter-wall-notification` category.
- Change the transient to the current timestamp and on refresh the Site Kit dashboard and ensure the `view_notification` event is triggered when the banner notification appears.
- When I click the Add Supporter Wall widget primary CTA and ensure the `confirm_notification` event is triggered.
- When I click the Maybe later secondary CTA and ensure the `dismiss_notification` event is triggered.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/196585641-3c9c297c-a66c-4529-9a9c-355fe4505d5e.png)
![image](https://user-images.githubusercontent.com/73545194/196585670-a62d500a-4f45-457e-aef4-c83580f63729.png)
![image](https://user-images.githubusercontent.com/73545194/196585708-0b814a27-b4ab-456e-b3a1-2525a62c581e.png)
![image](https://user-images.githubusercontent.com/73545194/196585721-7e1a5507-57d7-4859-8da6-8f3053620998.png)

</details>

**Comment by hussain-t** [comment]
@wpdarren, parts of the QAB to display the banner were copied over from #5538 and modified. Sorry, it was a bit confusing. You will have to change the value of `_transient_timeout_googlesitekit_thank_with_google_setup` to the current timestamp (by default, it will be seven days from the TwG setup). We shouldn't change the value of `_transient_googlesitekit_thank_with_google_setup`. I have updated the QAB.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@hussain-t thanks for updating the QAB. 

**Verified:**

- When Site Kit and TwG is initially set up the` view_notification` GA event isn't triggered for the `mainDashboard_thank-with-google-supporter-wall-notification` category.
- Change the transient to the current timestamp and on refresh the Site Kit dashboard and ensure the `view_notification` event is triggered when the banner notification appears.
- When I click the Add Supporter Wall widget primary CTA and ensure the `confirm_notification` event is triggered.
- When I click the Maybe later secondary CTA and ensure the `dismiss_notification` event is triggered.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/196670891-be04c63b-1301-4d9d-bc86-5b655e99571f.png)
![image](https://user-images.githubusercontent.com/73545194/196670912-079c2788-09a2-4a33-9928-c413bb7f3a98.png)
![image](https://user-images.githubusercontent.com/73545194/196670924-33627552-be16-413e-9dc7-f28bef97993f.png)

</details>
