### ISSUE TITLE
gvjs_cq.call is not a function - Google Chart Library conflict

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6021]
## Bug Description

[One user in the support forums](https://wordpress.org/support/topic/site-kit-encountered-an-error-88/#post-16109751) reported encountering the below dashboard error, with Site Kit having worked as expected previously:
`gvjs_cq.call is not a function
`

![image](https://user-images.githubusercontent.com/41326532/196501927-8b8965c8-3770-457b-a4be-b89670810fbd.png)

Based on the insights they provided we've been able to recreate this on a test site, with [details added to this testing task](https://app.asana.com/0/1200206407034013/1203190878005090), or viewable [via this recording](https://recordit.co/UwA4Xzm88B). 

## Steps to reproduce

In my case to reproduce this I installed the same plugins as the impacted user, and attempted Site Kit setup, with various browser console errors appear. I'll narrow this down with further testing before updating the steps to recreate. 

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/196502473-f5b8b5b5-7aef-4ec3-ac93-d17398f1f104.png)

![image](https://user-images.githubusercontent.com/41326532/196502312-a3174fca-23eb-47cb-974b-e8604fd5b443.png)

## Additional Context

 - Impacted user: [Support topic](https://wordpress.org/support/topic/site-kit-encountered-an-error-88/#post-16109751) | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgFw3pEW8M9DRLvPOyyzlKigM38NMN66MTflDZJPbv9mMhyNyJc7qeIkYhmz-fLsZs) 
- In the users case this started occurring randomly, with the dashboard working as expected previously
- There was [another report of this error previously](https://wordpress.org/support/topic/site-kit-encountered-an-error-51/), a few months back.   
- [Testing task](https://app.asana.com/0/1200206407034013/1203190878005090), where I was able to reproduce this on a support testing site
- We did have Google Chart library conflicts previously, including one with Registration Magic requesting such scripts on all wp-admin URLs (including SK - https://github.com/google/site-kit-wp/issues/4235), and another which was since resolved (https://github.com/google/site-kit-wp/issues/4074)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
During testing today I'm [encountering this error inconsistently](https://recordit.co/XnXasjt0x6) without making plugin changes. I might refresh the page and it doesn't appear. When I clear my session storage it appears once more. Testing ongoing.

**Comment by jamesozzie** [comment]
I've [narrowed this down](https://recordit.co/eCMHb4OE1L) to a possible conflict with the Like dislike counter plugin. This occurs with only Site Kit and this plugin active, and I'm unable recreate this without it active. Further testing ongoing.

**Comment by kuasha420** [comment]
@jamesozzie Sorry for the late reply. I was also able to reproduce the issue with Like dislike counter plugin. It's definitely due to the Google Charts Library being included in all the pages by the aforementioned plugin. 

Unfortunately there's no clean way to fix this without editing the offending plugin. The following MU plugin should work but I haven't extensively tested it. Feel free to reach out to the developer for a proper fix. 

Cheers. 

````php
<?php

/**
 * This registers the like/dislike counter loader on its own page only which fixes the issue. 
 */

function fix_like_dislike_counter_with_sitekit($hook) {
    // bail early if plugin not installed or on plugin page.
    if ( ! function_exists( 'ldcPostLikeDislikeAdminStyle' ) || 'toplevel_page_like_dislike_setting' == $hook ) {
        return;
    }
    // remove action.
    remove_action( 'admin_enqueue_scripts', 'ldcPostLikeDislikeAdminStyle' );
}

// Add with high priority.
add_action( 'admin_enqueue_scripts', 'fix_like_dislike_counter_with_sitekit', 1 );
````

**Comment by jamesozzie** [comment]
Confirmed all looks good. Thank you @kuasha420 

https://user-images.githubusercontent.com/41326532/205988735-042af0d9-b867-433a-a2ac-3048af67536e.mp4

I've also added the above function to [a mini plugin](https://gist.github.com/jamesozzie/34cd2c9045c95aa2b51b74b2c4557128), should other users be impacted. 

Closing this issue.
