### ISSUE TITLE
Trigger the custom GA `view_notification` event only when the banner notifications are visible

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#6023]
## Bug Description

Currently, some banner notifications trigger the custom GA `view_notification` event using the `useMount` hook. However, the `view_notification` event will be triggered even if the banner notification is not displayed due to the respective component returning `null` if the data is unavailable.

The above event should be triggered if the respective banner notification is displayed.

## Steps to reproduce

1. Go to the Site Kit dashboard.
2. Ensure the Google Analytics Debugger is enabled.
3. Open the dev tools->console and filter by `view_notification`.
4. Notice some GA events are triggered even though respective banner notifications aren't displayed. For example, `mainDashboard_wp52-version-notification` is triggered.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- All the banner notifications that trigger the custom GA `view_notification` event should be triggered if the respective banner notification is displayed. The following notification events should be checked to only send when the component actually renders and doesn't `return null`
  - https://github.com/google/site-kit-wp/blob/5841f2b67715762c98a76e644f534ed000b47a03/assets/js/components/activation/activation-app.js#L62
  - https://github.com/google/site-kit-wp/blob/a7a6f45123b24b9c767ac62ae4dcd2c6c5a1bd6a/assets/js/components/notifications/SetupSuccessBannerNotification.js#L99-L102
  - https://github.com/google/site-kit-wp/blob/a7a6f45123b24b9c767ac62ae4dcd2c6c5a1bd6a/assets/js/components/notifications/WPVersionBumpNotification.js#L53

## Implementation Brief

- We should trigger the `trackEvent` call within a `useEffect` instead of the `useMount` hook, conditionally on the same code path that causes the component to actually render. An example of how we have done this is in the `ThankWithGoogleSupporterWallNotification` component.
- This should be done in the following places:
  - https://github.com/google/site-kit-wp/blob/5841f2b67715762c98a76e644f534ed000b47a03/assets/js/components/activation/activation-app.js#L62
    - Change the `useMount` that calls `trackEvent` to be a `useEffect` that only runs when `buttonURL` is truthy.
  - https://github.com/google/site-kit-wp/blob/a7a6f45123b24b9c767ac62ae4dcd2c6c5a1bd6a/assets/js/components/notifications/SetupSuccessBannerNotification.js#L99-L102
    - Change the `useMount` to a `useEffect` here: https://github.com/google/site-kit-wp/blob/5841f2b67715762c98a76e644f534ed000b47a03/assets/js/components/notifications/SetupSuccessBannerNotification.js#L99-L102 so it only runs when the conditions to not `return null` are met (starts with `modules !== undefined && !! notification`, but also includes conditions in this [switch case](https://github.com/google/site-kit-wp/blob/5841f2b67715762c98a76e644f534ed000b47a03/assets/js/components/notifications/SetupSuccessBannerNotification.js#L159)). It might be worth cleaning up the switch case here and returning early in a few places, as the current logic is a bit hard to read.
  - https://github.com/google/site-kit-wp/blob/a7a6f45123b24b9c767ac62ae4dcd2c6c5a1bd6a/assets/js/components/notifications/WPVersionBumpNotification.js#L53
    - Update the `useMount` to a `useEffect` that only calls `trackEvent` when `hasMinimumWPVersion === false && version !== undefined`

### Test Coverage

* No new tests needed.

## QA Brief

- Install Site Kit via the plugin directory and activate it. Ensure the `view_notification` GA event for the `activation` category is triggered only when the `ActivationApp` notification is displayed. (This notification will have the `Congratulations, the Site Kit plugin is now activated.` title).
- Ensure the `view_notification` GA event for the `mainDashboard_wp52-version-notification` event category  is triggered only when the `WPVersionBumpNotification` is displayed.
- Ensure the following events are triggered only when the `SetupSuccessBannerNotification` is displayed:
   * `view_notification` - `mainDashboard_authentication-success-notification`
   * `complete_user_setup` - `mainDashboard_authentication-success-notification`
   * `complete_site_setup` - `mainDashboard_authentication-success-notification`

## Changelog entry

* Fix bug that could cause a notification view event to be sent even when the notification doesn't appear.

**Comment by tofumatt** [comment]
ACs here are largely good, but I wanted to call out which components were actually affected. I'll move this to IB, and I can work on that myself 👍🏻

**Comment by eugene-manuilov** [comment]
Thanks, @tofumatt. Could you please add more information to IB? I think that each components have different circumstances when we can consider them as rendered, right? Let's write them down in IB.

**Comment by eugene-manuilov** [comment]
Thanks, @tofumatt. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t I have a query based on this section of the QAB.

> Install Site Kit via the plugin directory and activate it. Ensure the view_notification GA event for the mainDashboard event category is triggered only when the ActivationApp notification is displayed. (This notification will have the Congratulations, the Site Kit plugin is now activated. title).

When viewing the log the `mainDashboard` event is not showing and I am wondering if this is expected, since the `Congratulations, the Site Kit plugin is now activated. title` takes place on the plugins page.  Please could you confirm this.

This is what I see. 
<img width="1786" alt="events-1" src="https://user-images.githubusercontent.com/73545194/198418042-74a59a47-e40f-4a8b-aab7-1824e2303db7.png">

**Comment by hussain-t** [comment]
@wpdarren, you're correct `mainDashboard` won't be available on the plugins page. However, do you see the `view_notification` event triggered? If that works, that should be good.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `view_notification` GA event for the activation category is triggered only when the ActivationApp notification is displayed. 
- The `view_notification` GA event for the mainDashboard_wp52-version-notification event category is triggered only when the WPVersionBumpNotification is displayed.
The following events are triggered only when the `SetupSuccessBannerNotification` is displayed:
`view_notification` - mainDashboard_authentication-success-notification
  - `complete_user_setup` - mainDashboard_authentication-success-notification
  - `complete_site_setup` - mainDashboard_authentication-success-notification

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/198569379-fadd5b33-e1b0-420d-9f55-3fcec6a94815.png)
![image](https://user-images.githubusercontent.com/73545194/198569397-7427f334-b746-4e93-80de-a5ee987f4733.png)
![image](https://user-images.githubusercontent.com/73545194/198569416-fcb1ee54-2846-4194-820c-8184ba9b86ab.png)
![image](https://user-images.githubusercontent.com/73545194/198569436-abe49a61-2f11-46e7-a115-2f0b4c9411bf.png)
![image](https://user-images.githubusercontent.com/73545194/198569452-1c6cb569-ffdb-4d70-bd88-961014b404b5.png)
![image](https://user-images.githubusercontent.com/73545194/198569467-4ffb5478-5238-4324-aa7d-66cd195a0b7f.png)

</details>

**Comment by techanvil** [comment]
Good spot there @aaemnnosttv. I have looked into this and it's not a regression as I can see the same behaviour in the previous release. I've created a followup issue to address this: https://github.com/google/site-kit-wp/issues/6109
