### ISSUE TITLE
E2E broken for user input in WP 4.x

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6024]
## Bug Description

E2E jobs for WP 4.x started failing with the addition of the WP minimum version banner notice due to the user input tests expecting a user input banner notification instead.

Seeing as the minimum is about to be raised (and these jobs removed) and user input won't be release before then, these are safe to disable.

## Steps to reproduce

1. Review GHA logs for E2E jobs for WP 4.7 and WP 4.9
2. See consistent failures

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The E2E tests for user input should be skipped for jobs that run with WP pre-5.2
	* This is temporary, so we can be specific to jobs with WP 4.x 

## Implementation Brief

* Merge #6025 

### Test Coverage

* Test coverage is technically reduced here, although in an insignificant way as it will be removed in the near future anyways

## QA Brief

* None needed, CR will verify E2E passes

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv Reviewed the PR, mostly LGTM but left one comment.
