### ISSUE TITLE
Reduce code complexity in `DataBlock`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6028]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wp-content/plugins/google-site-kit/assets/js/components/DataBlock.js
  60:8  error  Method 'render' has a complexity of 26. Maximum allowed is 20  complexity
```

[This is the method](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/DataBlock.js#L60-L219) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief

* Inside `google-site-kit/assets/js/components/DataBlock.js`
    * Rewrite `DataBlock` into a functional component
    * Make sure all props are used & remove unused props and connected logic
    * Extract `changeFormatted` definition into a separate util function
    * Reuse props where possible and get rid of useless wrappers: eg. `handleClick`
    * Examine render & classNames and remove unnecessary parts where possible: eg. `title-datapoint-wrapper` & `change-source-wrapper`
    * Rewrite conditional operators in a more optimal way eg: https://github.com/google/site-kit-wp/blob/9ee628e3035bdfbd80099aa14afdb7cf91d73875/assets/js/components/DataBlock.js#L113-L116 could be put in a render and rewritten into: 
````
<div className="googlesitekit-data-block__datapoint">
	{ datapoint && numFmt( datapoint, datapointUnit || undefined ) }
</div>
````

(Note: we could probably change the `datapointUnit` default prop here to be `undefined` instead of `''`, so we don't have to do the awkward `datapointUnit || undefined` as well.)

### Test Coverage

* No new tests are needed 

## QA Brief

* Check the Data Block component across the site (WP Dashboard, Search traffic over the last 28 days widget, Search Console) - all should remain the same 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
> Extern `sparklineComponent` definition into separate functions

Sorry, what does this mean exactly? Do you mean to extract it into a new component?

It actually looks like we don't even use that `invertChangeColor` prop anymore (this is a very old component):

<img width="263" alt="CleanShot 2022-12-22 at 00 04 17" src="https://user-images.githubusercontent.com/90871/209026563-bacda145-ac1f-431c-aa7b-c5198dec352c.png">

We can remove that `sparklineComponent` logic entirely, and the `invertChangeColor` prop as well 🙂 

----

Can you elaborate on "optimize render" here? What specifically in the render function needs changing?

**Comment by sashadoes** [comment]
Hi @tofumatt , thanks for the review and feedback. It all makes sense. I update IB to be more explicit now :)

**Comment by tofumatt** [comment]
Note: we could probably change the `datapointUnit` default prop here to be `undefined` instead of `''`, so we don't have to do the awkward `datapointUnit || undefined` as well.

I've added this to the IB. Otherwise looks good.

Also: please remember to add estimates… for this IB I've added it as a 7, but better to add it when writing the IB.

IB ✅

**Comment by mohitwp** [comment]
### QA Update : PASS

- Tested on dev environment.
- Verified Analytics users widget and Search Console -Search traffic widget and WP Dashboard widgets.
- Verified on both main and entity dashboard.
- Verified for both zero and gathering data state.
- Verified when analytics is in zero and search console is in gathering state and vice versa.
- Verified all data and field of widgets.


<details>

![image](https://user-images.githubusercontent.com/94359491/218663559-b575f8d6-6f4a-4724-abc1-4ed4a40409b5.png)

![image](https://user-images.githubusercontent.com/94359491/218664019-1ce0e9de-5081-4bf1-9f69-2dbc6c37e8f2.png)

![image](https://user-images.githubusercontent.com/94359491/218663632-16ca2a78-df6d-4a3a-98fc-b7c9e807e533.png)

![image](https://user-images.githubusercontent.com/94359491/218663677-38c60703-1c9f-4726-8bb2-dd71c04b9d91.png)

![image](https://user-images.githubusercontent.com/94359491/218664148-1e1c1b09-de47-409e-b37a-1871969e7e02.png)

![image](https://user-images.githubusercontent.com/94359491/218664414-281e5d2a-ee65-40ff-9b47-014a228b739e.png)

![image](https://user-images.githubusercontent.com/94359491/218664470-5b9f63e3-7d0a-4ae2-a191-10b7ebc53529.png)

![image](https://user-images.githubusercontent.com/94359491/218664555-fff79c3f-5a4e-4ef1-a3cb-fc9aa8ab8d89.png)

![image](https://user-images.githubusercontent.com/94359491/218664661-8b2be9d7-fd97-4973-aaec-150c69385d5e.png)

![image](https://user-images.githubusercontent.com/94359491/218664706-f27fe9fb-b98b-4dce-bdbc-c907552e074a.png)

![image](https://user-images.githubusercontent.com/94359491/218664762-21554e68-8ec1-4f0c-81c7-a7cc06955259.png)

</details>
