### ISSUE TITLE
Reduce code complexity in `GoogleChart`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6029]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/components/GoogleChart.js
  53:16  error  Function 'GoogleChart' has a complexity of 22. Maximum allowed is 20  complexity
```

[This is the component](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/GoogleChart.js#L53-L315) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief

* Using `google-site-kit/assets/js/components/GoogleChart.js`,
    * Remove ESLint ignore for `complexity`
    * Extract the logic to set `modifiedData`, `loadingWidthToUse`, `loadingHeightToUse`, `combinedChartEvents`, and `chartOptions` into individual functions
    * Use newly created functions to deliver props to `<Chart />` 

### Test Coverage

* No new tests are needed

## QA Brief

* Check Google Charts appearance across this site - all functionality should remain the same 

## Changelog entry

* Reduce code complexity in `GoogleChart` component.

**Comment by aaemnnosttv** [comment]
@nfmohit it should come up later if this didn't happen, but it's probably a good idea to mention removing the related ESLint ignore rule here as well :)

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked Google Charts appearance across this site to check that all functionality remains the same
  - Tested main and entity dashboard with live data (oi.ie) 
  - Tested main and entity dashboard with gathering and zero data states
  - Tested main and entity view only dashboard
  - Tested the Site Kit widget on WP dashboard 
  - Confirmed that there are no new warnings or errors in the console
