### ISSUE TITLE
Reduce code complexity in `BannerNotification`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6030]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/components/notifications/BannerNotification/index.js
  68:1  error  Function 'BannerNotification' has a complexity of 41. Maximum allowed is 20  complexity
```

[This is the component](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L68-L534) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief

* Remove the `// eslint-disable-next-line complexity` on line `73`.
* Create a new Component `CTA` `assets/js/components/notifications/BannerNotification/CTA.js`
  * Move CTA logic to new CTA component. https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L415-L446
  * Move the `DismissableComponent` logic into this new `CTA` component. https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L349-L351
* Combine the [`inlineMarkup`](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L264-L333) and [layout logic](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L399-L413) into a new `Content` component. `assets/js/components/notifications/BannerNotification/Content.js`  https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L264-L333
https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L399-L413
* Move `dataBlockMarkup` into its own `DataBlock` component. https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L246-L262
* Use early returns instead of nested conditions where possible. e.g. here https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/components/notifications/BannerNotification/index.js#L206-L214
* Migrate the [stories](https://github.com/google/site-kit-wp/blob/878d7fd21a61b6a1110d4dd080a8d7ce2de5a5ec/stories/notifications.stories.js#L22) to the new Component Stories Format (CSF) and move them to `assets/js/components/notifications/BannerNotification/BannerNotification.stories.js`
* Make sure stories for exist for all Component props of `BannerNotification`.
* Enable VRT to the stories as described [here](https://docs.google.com/document/d/1Ny2Tlo1_FxZY6s6dC2-E1TWJYi1rhp0OMEtEfXxwXjY/edit?resourcekey=0-PFLAM17zQVq9Lb05pYlj7A#heading=h.tkj03nf3i5wk).

### Test Coverage

* 

## QA Brief

* Compare existing banners from the latest published version with banners from the develop branch and verify that there are no visual changes.

## Changelog entry

* N/A.

**Comment by derweili** [comment]
Additionally to the AC, I added updates to the component stories for `BannerNotification`.
I noticed many of the component props are not used by any of the stories. E.g. `blockData` is only used by `AdSenseAlerts` for wich also no story exists.
This makes it hard to work on the component. This also means we don't have VRT for these cases.
I think it makes sense to update the stories while doing a refactor of the component.

**Comment by tofumatt** [comment]
IB ✅ 

Good call on adding VRTs here 👍🏻

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- Compared existing banners from the latest version yo develop branch and verify that there are no visual changes.  
  - Went through all the Site Kit set up and module banner notifications
  - Error banner notifications, i.e. when permissions are not given. 
  - Gathering and zero data state banner notifications. 
  - Dashboard Sharing, in particular when 2nd admin disconnects. 
  - UA - GA4 banners for prior to 25 September. 
  - Optimize banner 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/5e016e1f-bc59-44ca-ad73-7cdbdca4511c)
![image](https://github.com/google/site-kit-wp/assets/73545194/14d81104-b570-4cf0-bbc0-c720e0474021)
![image](https://github.com/google/site-kit-wp/assets/73545194/998cee4b-b4c5-4ab6-8d55-85ee877d82a8)
![image](https://github.com/google/site-kit-wp/assets/73545194/cbf675eb-19c1-4eaa-a571-f73094e76a00)
![image](https://github.com/google/site-kit-wp/assets/73545194/f5cab835-4358-44cb-b3cc-667b6a84fda8)
![image](https://github.com/google/site-kit-wp/assets/73545194/3e261900-1c24-4d99-825e-b894e08b8745)
![image](https://github.com/google/site-kit-wp/assets/73545194/904d437a-599d-41bf-93dd-a34f6e768bdb)
![image](https://github.com/google/site-kit-wp/assets/73545194/807be8f1-3941-4de2-a488-9270dde70441)
![image](https://github.com/google/site-kit-wp/assets/73545194/c1d78094-20b2-41b3-abd4-9399ad2de389)
![image](https://github.com/google/site-kit-wp/assets/73545194/835b3ba0-8b7d-4b0a-b4af-58a33b044b77)
![image](https://github.com/google/site-kit-wp/assets/73545194/162ed4c4-a1d5-42fd-9ff1-5c2ef982c592)

</details>
