### ISSUE TITLE
Reduce code complexity in Adsense `SettingsView`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6031]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/modules/adsense/components/settings/SettingsView.js
  59:16  error  Function 'SettingsView' has a complexity of 27. Maximum allowed is 20  complexity
```

[This is the component](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/modules/adsense/components/settings/SettingsView.js#L59-L304) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief
* Using `assets/js/modules/adsense/components/settings/SettingsView.js`,
    * extract the logic to set `accountStatusLabel`, `siteStatusLabel` and `useSnippetLabel` into individual functions and update code to use the newly created functions.

### Test Coverage
* No new tests to be added.

## QA Brief

* Check Adsense settings - all functionality should remain the same

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅ 

I'm not 100% the IB here will reduce the complexity sufficiently, but if not I think it's fine to refactor a bit more 🙂

**Comment by eugene-manuilov** [comment]
@sashadoes could you please add QAB?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked Adsense settings - all functionality remains the same
   - Set up AdSense on a site that has an approved account and site.
   - Set up AdSense on a site that does not have an approved account or site. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/214588531-e76657d1-9a55-4519-bf7d-394c678ac6e0.png)

![image](https://user-images.githubusercontent.com/73545194/214588585-3643604a-9ccc-4d53-8391-43010ea1debd.png)

</details>
