### ISSUE TITLE
Reduce code complexity in Adsense `SetupMain`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6032]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/modules/adsense/components/setup/SetupMain.js
  68:16  error  Function 'SetupMain' has a complexity of 24. Maximum allowed is 20  complexity
```

[This is the component](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/modules/adsense/components/setup/SetupMain.js#L68-L497) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief
* Using `assets/js/modules/adsense/components/setup/SetupMain.js`,
    * extract the logic to assign the `viewComponent` variable for `siteStatus` and `accountStatus` into separate functions, for e.g `getAccountStatusViewComponent` and `getSiteStatusViewComponent` and call the function as needed.

### Test Coverage
* No new tests to be added.

## QA Brief

* Check Adsense settings view - all functionality should remain the same 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified AdSense set up.
- Connected AdSense from SK dashboard.
- Connected AdSense from settings>Connect Services.
- Verified AdSense edit settings.
- Verified AdSense Tester settings.
