### ISSUE TITLE
Reduce code complexity in Analytics `SettingsView`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6033]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/modules/analytics/components/settings/SettingsView.js
  44:16  error  Function 'SettingsView' has a complexity of 24. Maximum allowed is 20  complexity
```

[This is the component](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/modules/analytics/components/settings/SettingsView.js#L44-L359) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief

* Inside `google-site-kit/assets/js/modules/analytics/components/settings/SettingsView.js` 
    * Remove the `// eslint-disable-next-line complexity` ESLint ignore rule
    * Extract the logic dependent on `canUseSnippet`, `useSnippet`, `hasExistingTag`, `useGA4Snippet`, and `anonymizeIP` into individual component and update code to use the newly created component.`

### Test Coverage

* No new tests to be added.

## QA Brief

* Verify the Analytics Settings View (UA & GA4) works as expected. this is a refactor ticket so Analytics Settings should behave as they did before, with no changes to the user.
* In Setting > Connected Services > Analytics > Edit
  * Verify all settings options show up as on current main.
  * Verify changing and saving the settings works.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Analytics Settings View (UA & GA4) works as expected. 
  - In Setting > Connected Services > Analytics > Edit
     - All settings options show up as on current main.
    - Changing and saving the settings works.

There was some additional QA tasks that I completed to check all of this.

- Checked the source code on the front end when the appropriate settings were changed.  
- Made sure that the appropriate tags appeared as expected. 
- Added existing tags to ensure the snippets and toggles appear as expected. 
- Created a new account, UA and GA property + view within the settings to make sure no issues occurred. 
- Checked the settings in Analytics settings view when any changes were made - including refreshing the page. 
- Compared latest release to develop to ensure that all settings appear in the view and edit. 

I could not find any regressions on the `develop` branch. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/216591610-6becc98a-3e33-4578-b5e6-e6f9e0de3188.png)
![image](https://user-images.githubusercontent.com/73545194/216591629-7f543fc4-1d31-4f80-aa52-87a36052435b.png)
![image](https://user-images.githubusercontent.com/73545194/216591645-d73cc336-3beb-44cc-a645-6943a9700a0b.png)

</details>
