### ISSUE TITLE
Reduce code complexity in `SearchFunnelWidget` `Overview`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6034]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js
  68:18  error  Arrow function has a complexity of 33. Maximum allowed is 20  complexity
```

[This is the arrow function](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js#L68-L362) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`,
    * Move code to `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview/index.js`.
    * Create new components in the above folder to render the
        * `ProgressBar`
        * `ActivateAnalyticsCTA`
        * `WidgetReportError`
        * `CreateGoalCTA`
        * `RecoverableModules`
    * Existing logic should be carried over to the above components and shared functionality/code should be abstracted to be reused as far as possible.

### Test Coverage
* No new tests to be added.

## QA Brief

* Smoke test the Search Traffic widget - there should be no changes to it.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Smoke tested the `Search Traffic` widget to ensure no regressions appear.
  - Tested on a site with zero, gathering and live data
  - Tested on main, entity and view only dashboard. 
  - Checked that no issues occur when changing the date period, i.e. 7, 1,4, 28 and 90 days. 
  - Made sure the search console and analytics links worked as expected. 
  - Checked labels on graphs and difference tooltips. 

Did find a few bugs but do not appear to be related to this ticket. Will investigate further. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/213955282-59367781-bc7a-495c-b544-19d47dca424c.png)
![image](https://user-images.githubusercontent.com/73545194/213955290-4a53213a-8d05-4bf3-8ae7-80a78761dd41.png)
![image](https://user-images.githubusercontent.com/73545194/213955299-eac149f9-a1c3-40da-b25d-161abcd95075.png)
![image](https://user-images.githubusercontent.com/73545194/213955305-2ea58b31-a818-40f4-ae6d-a453cb179704.png)
![image](https://user-images.githubusercontent.com/73545194/213955314-6495511b-c2ab-4689-a36c-fefa46069e80.png)
![image](https://user-images.githubusercontent.com/73545194/213955321-7bd4ba8a-2d03-4658-80f7-a3f1563177c2.png)
![image](https://user-images.githubusercontent.com/73545194/213955330-61fd5bac-96bf-45a6-ac49-63c618b16501.png)
![image](https://user-images.githubusercontent.com/73545194/213955339-140aee7e-14df-4647-93c9-7253afd5947d.png)
![image](https://user-images.githubusercontent.com/73545194/213955349-93e3bec5-aa2f-4a64-8960-22e6549af04d.png)

</details>
