### ISSUE TITLE
Reduce code complexity in `SearchFunnelWidget`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6035]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js
  62:28  error  Arrow function has a complexity of 23. Maximum allowed is 20  complexity
```

[This is the arrow function](https://github.com/google/site-kit-wp/blob/045955b1cd40ed0b42b67be0dc5635ee8bef2490/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js#L62-L454) in question.

While the error is currently ignored, the aim of this issue is to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule

## Implementation Brief

In `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js`:
* Consolidate the following analytics loading state logic into a single select that returns a boolean:
    * `analyticsOverviewLoading`
    * `analyticsStatsLoading`
    * `analyticsVisitorsOverviewAndStatsLoading`
    * `analyticsGoalsLoading`
* Consolidate the following analytics error logic into a single select that returns the error object/boolean:
    * `analyticsOverviewError`
    *  `analyticsStatsError`
    *  `analyticsVisitorsOverviewAndStatsError`
    *  `analyticsGoalsError`
* Update the condition that checks for the loading state to use the new select data.
* Pass the consolidated error object to the `Overview` component's `error` prop.

### Test Coverage

* No new tests are to be added.

## QA Brief

* **General Observation**: No user-facing changes should be observed.
  
* **Universal Analytics View**:
   - Open the dashboard and confirm that it displays the Universal Analytics view, not GA4.

* **`SearchFunnelWidget` Functionality**:
   - Ensure the Analytics widget (specifically for Universal Analytics, not GA4) functions as expected.
   - Pay particular attention to the widget's loading and error states.

* **Simulating Error States**:
   - You can simulate error states by aborting the Analytics `getReport` requests.
   - Use an HTTP proxy or request proxy tool like Proxyman.
   - Target URL for simulation: `http://<test-hostname>/wp-json/google-site-kit/v1/modules/analytics-4/data/report`.

### Notes:
Always revert any changes or configurations post-testing to ensure a clean environment for subsequent tests.

## Changelog entry

* N/A.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
Thanks, @hussain-t.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked that the UA dashboard view loaded as expected for main, entity and view only dashboard. 
- Ensured that appropriate widgets and data loaded as expected. 
- Checked SearchFunnelWidget Functionality for 7, 14, 28 and 90 days reports.  Make sure functionality continued to work.
- Ensure the Analytics widget functions as expected.
- Didn't notice anything different with the widget's loading and error states.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/8aab5b3e-f6e0-4e78-a1c9-a66da58f7122)
![image](https://github.com/google/site-kit-wp/assets/73545194/d6a60da0-93e7-456b-9eb6-ebab7d1df504)
![image](https://github.com/google/site-kit-wp/assets/73545194/50047917-b24b-4ea1-80e7-848e0ef6f36f)
![image](https://github.com/google/site-kit-wp/assets/73545194/d831ad2e-ba30-4e46-9056-00593a4c2d00)

</details>
