### ISSUE TITLE
Follow up replacements to consistently use "main dashboard" and "entity dashboard" terminology

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6038]
Follow-up to #4161: During approval of that issue, a few follow-up occurrences of the old terms were found in the codebase that should also be updated.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* CSS classes using `googlesitekit-dashboard-single-url` should have that part replaced with `googlesitekit-entity-dashboard`, in both React and Sass files.
    * The one Sass file with that name should also be renamed accordingly.
* The fixture file and reference names used in `tests/e2e/specs/modules/search-console/dashboard-date-range.test.js` should also be renamed to use `main-dashboard` / `mainDashboard` instead of "dashboard" and `entity-dashboard` / `entityDashboard` instead of "dashboard details".

## Implementation Brief
* Using `assets/js/components/DashboardEntityApp.js` and `assets/sass/components/dashboard/_googlesitekit-dashboard-single-url.scss`,
	* Replace occurrences of `googlesitekit-dashboard-single-url__*` by `googlesitekit-entity-dashboard__*`.
* Rename `assets/sass/components/dashboard/_googlesitekit-dashboard-single-url.scss` to `assets/sass/components/dashboard/_googlesitekit-entity-dashboard.scss`.
* Using `tests/e2e/specs/modules/search-console/dashboard-date-range.test.js`, make the updates as per the second bullet point in the AC.

### Test Coverage
* No new tests to be added.

## QA Brief

* There are no user facing changes here. However, the main and entity dashboards should be smoke tested to verify they work (especially their styling) as before.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified on dev.
Smoke tested -main and entity dashboard.
Verified occurrences of `googlesitekit-dashboard-single-url__*` replaced by `googlesitekit-entity-dashboard__*`

<details>

dev-

![image](https://user-images.githubusercontent.com/94359491/204574987-9d0d955f-0f6a-4bc4-b349-babcf27162cc.png)

latest-

![image](https://user-images.githubusercontent.com/94359491/204575236-a846b25f-39ec-4af1-a605-ba7749496711.png)


</details>
