### ISSUE TITLE
GA4 Activation Banner: Error message is momentarily displayed when creating a new property

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6040]
## Bug Description

When creating a new property from the GA4 Activation Banner, in the case where the edit scope needs to be requested via Google OAuth, upon returning from the OAuth flow and creating the property an error message is briefly shown.

The error message is "Error: Requested entity already exists".

Looking at the network devtools, it appears the `create-webdatastream` endpoint is being requested twice and the error message comes from the duplicate request - see toward the end of the `create-new-property-dropdown-error.mp4` screencast below.

## Steps to reproduce

1. Setup Site Kit with Analytics and show the GA4 Activation Banner with no edit scope.

Enable the `ga4ActivationBanner` feature flag.
To ensure the activation banner displays, delete the `googlesitekit_analytics-4_settings` option. To ensure it displays in the "no edit scope" state, delete the `wp_googlesitekit_additional_auth_scopes` usermeta option. For example in SQL:

```sql
DELETE FROM wp_options WHERE option_name = 'googlesitekit_analytics-4_settings';
DELETE FROM wp_usermeta WHERE user_id = 1 AND meta_key = 'wp_googlesitekit_additional_auth_scopes';
```

2. Either click on **Create property**, or select **Set up a new property** and click **Connect**.
3. Go through the OAuth flow.
4. Upon return watch for the error to be displayed. See screen captures below.

## Screenshots

https://user-images.githubusercontent.com/18395600/197014164-3f2cbb4c-0048-44e7-9c02-27a126479964.mp4

https://user-images.githubusercontent.com/18395600/197014180-7b11d1c2-20da-4ae2-a8c7-40b695cac0cb.mp4

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.86.0 (release testing)
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When creating a new property via the GA4 Activation Banner, `create-property` and `create-webdatastream` requests should only be made once.

## Implementation Brief

* The problem here stems from the `useEffect` in the setup banner which takes the `handleSubmitChanges` function as an effect dependency
* This function depends on the GA4 property ID which changes during the (inner) `submitChanges` call due to the created property
* This change in turn triggers the effect to run again, which does not have a guard in place to check against the given `handleSubmitChanges` function
* The solution here is to use the `getPropertyID` _selector_ within the function rather than the property ID itself as this will not change regardless of the value it returns
* This prevents the effect from running additional invocations every time the function changes due to it's dependency on the property ID
* Merge https://github.com/google/site-kit-wp/pull/6043

### Test Coverage

* No changes

## QA Brief

* Test creating a new GA4 property through the GA4 activation banner
* Pay attention to the network requests made (may want to enable persistent logs)
* Ensure create-property and create-webdatastream requests are made only once during the setup

Note this seems to be particularly sensitive to the case where the edit scope also needs to be granted ahead of time

## Changelog entry

* Fix duplicate request when setting up GA4 via the activation banner.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on main.
- Verified when creating new property.
- Verified when setting up new property.
- Verified when user don't have  edit scope access.
- Verified when user have edit scope access.
- Verified create-property and create-webdatastream requests are made only once during the setup.

<details>


https://user-images.githubusercontent.com/94359491/197187822-58fac3ae-3aa8-4bbd-9a4f-0fd2bb3a9133.mp4


https://user-images.githubusercontent.com/94359491/197187876-a571129a-d5cc-439e-9d47-c1b3b2613fcf.mp4

</details>
