### ISSUE TITLE
Tooltip not appearing on GA4 property within Analytics settings when only UA property connected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6045]
## Bug Description

With `ga4ActivationBanner` feature flag enabled. 

When you click on the Connect Google Analytics 4 button, the tooltip appears for a second and then disappears. 

See screencast below. 

https://user-images.githubusercontent.com/73545194/197425648-8a4e399e-94d4-4259-9fa7-64fe8f347089.mp4

We also noticed that when you click on the Edit link in Analytics settings the tooltip does not appear at all, even when the `ga4ActivationBanner` feature flag is enabled or not. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tooltip pointing to the dropdown in Analytics settings for setting up GA4 should keep showing until the user dismisses it (i.e. not only flash for a split second).

## Implementation Brief

- The general idea here is to display the `Set up your Google Analytics 4 property here` tooltip only when the `Connect Google Analytics 4` CTA is clicked in `SettingsActiveModule -> Header`. We will implement that overruling any other logic, i.e. we will show tooltip when the said CTA is clicked, and close it when the edit screen is closed.
- In `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`:
    - Remove the `useEffect` hook that was added [here](https://github.com/google/site-kit-wp/pull/5999/commits/9c11674e103b7ba3860b6cf2b856d01754757632).
    - Locate the `<JoyrideTooltip />` component and update its display conditions so that besides the current conditions, it only appears if GA4 is not connected. This can be checked using the `isModuleConnected` selector from the `CORE_MODULES` store, passing `analytics-4` as the parameter. This will act as an extra measure to make sure we do not show the tooltip when it is not needed.
- In `assets/js/components/settings/SettingsActiveModule/Footer.js`:
	- Call the `getValue` selector from the `CORE_FORMS` store passing `FORM_SETUP` and `enableGA4PropertyTooltip` as parameters. Assign the selector to a new variable named `enableGA4PropertyTooltip`.
    - Create a new callback function that will dismiss the tooltip when the user closes the edit screen, say `dismissGA4PropertyTooltip`. In this callback function:
	    - Return `null` early if the `slug` prop is not `analytics`, or `enableGA4PropertyTooltip` is false.
		- Dispatch the `setValues` action from the `CORE_FORMS` store with parameters `FORM_SETUP` and an object containing the `enableGA4PropertyTooltip` as key and `false` as value.
	- In the `handleClose` and `handleConfirm` functions, after the `history.push()` function call, check if the `slug` prop is `analytics`, and if so, call the new `dismissGA4PropertyTooltip` function.
- When adding a QA Brief, it should be noted that the outcome of #5921 should be checked as well to make sure the behaviour reported there is still fixed.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Set Up analytics without GA4 property
* Go to settings and expand Analytics 
* Tooltip should appear as per the screenshot 
<img width="1006" alt="Screenshot 2022-10-29 at 19 52 31" src="https://user-images.githubusercontent.com/16494321/198848656-6594695c-0450-4c77-bc65-6a2a75506fc7.png">
* The outcome of #5921 should be checked as well to make sure the behaviour reported there is still fixed.

## Changelog entry

* Fix bug where the GA4 reminder tooltip in Analytics Settings was not appearing properly.

**Comment by aaemnnosttv** [comment]
> We also noticed that when you click on the Edit link in Analytics settings the tooltip does not appear at all, even when the `ga4ActivationBanner` feature flag is enabled or not.

It wasn't designed to do this. The Tooltip is only set to show when the user clicks the "Connect" CTA on the module header.

The behavior we're seeing here is a result of the changes in https://github.com/google/site-kit-wp/issues/5921 which is causing the tooltip to be hidden as soon as the property ID is set.  This happens automatically when there is a matching property found as is shown in your screencast.

I agree it's a little odd - what would you expect in this situation?

**Comment by wpdarren** [comment]
@aaemnnosttv just to add, the issue occurs even when you do not have any property or a non matching property.  It's consistently behaving the same.  I would expect the tooltip to appear in all scenarios.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@sashadoes an observation in a specific scenario.  I set up analytics without GA4 property, but there is a GA4 property on the account.  When the GA4 property is loading, there are a few shifts, and initially the tooltip loads above rather than to the side.  When you scroll down the page slightly the tooltip does jump around to the side, bottom and top.  

It's a weird UX in my opinion, and different to when there isn't a GA property on the account. 

https://user-images.githubusercontent.com/73545194/200595161-c8910247-2259-4846-a8f8-2a329fabf6eb.mp4

**Comment by sashadoes** [comment]
Hi @wpdarren, thank you for the feedback. 
Unfortunately, I am struggling to reproduce this issue. 

https://user-images.githubusercontent.com/16494321/200822563-27310f05-d95f-4853-8959-942f9274fba6.mov


Could you write detailed steps on how to reproduce and specify the environment?
Thank you.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@sashadoes the behaviour reported was due to smaller screen size. When I viewed on full-screen, the issue doesn't occur. It makes sense why it places the tooltip above the GA4 property with the smaller resolution, so I will approve this. 

**Verified:**

- Set Up analytics without GA4 property, and when clicking on the Connect GA4 button in settings, the tooltip appears as per the screenshot in the QAB.  I tested this with and without a GA property on the Google analytics account. 
- The outcome of https://github.com/google/site-kit-wp/issues/5921 was also checked as well and the behaviour reported there is still fixed.

![image](https://user-images.githubusercontent.com/73545194/200846194-081fc84a-deb6-4941-843a-506fc2408b75.png)
