### ISSUE TITLE
Revise the wording on the Supporter Wall settings

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6054]
## Bug Description

Revise the wording of the TwG settings page. Ensure the Supporters Wall Widget title is capitalized as it is when viewing the settings page before editing, and replace the **_page_** mention with **_widget_**, while also capitalizing. 

![image](https://user-images.githubusercontent.com/41326532/197562281-35149950-6b1e-4809-8898-cc605abf16e9.png)

https://user-images.githubusercontent.com/41326532/197562716-28bd5fcf-7cc3-4c22-bb75-ec4292462723.mp4

````diff
+ Supporter Wall Widget
- Supporter wall widget
````

````diff
+ A Supporter Wall Widget shows the list of everyone who has supported your site using...
- A supporter wall page shows the list of everyone who has supported your site using.....
````

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG edit settings form should be modified for the supporter wall widget section:
    * Title: _Supporter Wall Widget_ (Capitalise first letters)
    * Description: _A supporter wall widget shows the list of everyone who has supported your site using Thank with Google. Look for the "Thank with Google Supporter Wall" widget and add it to your site._ (Change the word "page" to "widget").

## Implementation Brief

* Within `assets/js/modules/thank-with-google/components/common/SupporterWall.js`:
    * Edit the `<h4>` to match the title in the ACs
    * Edit the `<p>` which begins with "A supporter wall page..." with the message in the AC.

### Test Coverage

* No new tests required.

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@jamesozzie Thanks! As for the description, we should keep the words "supporter wall widget" lowercase as that is what we have everywhere else.

**Comment by tofumatt** [comment]
ACs look good. 👍🏻

**Comment by eclarke1** [comment]
Closing this issue out now given TwG status
