### ISSUE TITLE
Request to bring back post content suggestions

### ISSUE THREAD

**Issue by bastbra** [google/site-kit-wp#6057]
## Feature Description

Hi, hope you all are doing well.

I really enjoyed the feature for post content suggestions the plugin had a while ago, not really sure when or why you removed it again - at least it's not in the German version any more - but I really liked it, just to get a few ideas that are relevant.

Is there any way you can bring this hub back again, or is this not something that would you set on your list? I guess the code and so on still exists somewhere.

Best regards & keep on the great work!

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi @bastbra thanks for opening this issue. It sounds like you are referring to the Idea Hub module which provides content suggestions for your site from actual questions people asked on Google Search that are similar to your site’s content.

Idea Hub is an experimental feature and is only currently available in the US. You can find out more information on this feature here: https://sitekit.withgoogle.com/documentation/using-site-kit/idea-hub/.

Could you please confirm if this is the feature you are referring to and if so when was the last time you had the feature and were you based in the US at the time? If it's not what you are referring to could you provide a little more information on where this feature was displayed and what it used to do for you.

**Comment by bastbra** [comment]
Thanks for your answer, @adamdunnage! I didn't know the name of it, but Idea Hub sounds familiar, as far as I can remember. I'm not based in the US, which is weird - but it was displayed in Germany a few weeks, maybe months ago, and I really enjoyed the feature, although German is and was the language of my site.

It would of course be great to get it back in English (even better this time in German), but it seems it's right now only available in the US, as you said, but a bit time ago it was also available on my German website.

Best regards,
Bastian

**Comment by adamdunnage** [comment]
@bastbra No problem at all. Unfortunately the availability of Idea Hub is controlled by the service itself and not on the Site Kit side. We hope like you that this is extended to other Countries in the future so that others can make use of the feature.
