### ISSUE TITLE
Update Tooltips styles to match GM2+ designs

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#6059]
## Bug Description

Currently the tooltips look almost like dropdown menus, resulting in an odd user experience.

## Screenshots

Tooltip:
![image](https://user-images.githubusercontent.com/31818/197732905-32683e25-2410-4cf3-bedb-3d801bde1816.png)

Dropdown menu:
![image](https://user-images.githubusercontent.com/31818/197732936-650f4d4c-8a87-429e-9c5f-9e76245eb1b5.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* General Site Kit tooltips (e.g. in SK header bar and dashboard sharing modal) should be styled as per [the designs in Figma](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?node-id=564%3A2006).
<img width="463" alt="image" src="https://user-images.githubusercontent.com/31818/197733414-f7e713cd-4cb1-43cb-b6a8-06c885fa0f24.png">

Note: TourTooltips should not be affected by changes made to the Tooltip component.

## Implementation Brief
* Regression was introduced as part of the changes in #5444
* Using `assets/sass/components/global/_googlesitekit-tooltip.scss`,
	* Remove/update the styles for `.googlesitekit-tooltip.MuiTooltip-tooltip` and `.googlesitekit-tooltip .MuiTooltip-arrow` to match the Tooltip styles we have in the [Figma designs](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?node-id=564%3A2006), i.e more rounded corners, black background color,etc
* All tooltips styles should be consistent which means undoing the work done in #5444

### Test Coverage
* No new tests to be added.

## QA Brief

* Locate a tooltip (SK header, dashboard sharing, etc)
* Compare the styling of the element and ensure it matches the figma design provided in the AC
* If inspecting using the devtools is necessary, you can force the tooltip to stay open by enabling a breakpoint for attributes on the element triggering the tooltip (see screenshots below)

<details>
  <summary>Screenshots</summary>

  Locate an element that has a tooltip, here I'm using the dashboard sharing trigger

![Screenshot 2022-11-02 at 15 46 49](https://user-images.githubusercontent.com/30048523/199521432-2e1758f9-1fc9-451a-ada2-ae57b7c3609e.png)

Right click it and set it to break on attribute modifications

![Screenshot 2022-11-02 at 15 46 44](https://user-images.githubusercontent.com/30048523/199521459-b15ea57e-1716-4e41-a7e4-c6fdf73ec2d4.png)

Click the forward arrow to step through the code, until the tooltip appears. It can now be inspected and wont go away until you remove the breakpoint

![Screenshot 2022-11-02 at 15 51 08](https://user-images.githubusercontent.com/30048523/199522155-73f86fc8-f8c6-4d23-8073-076c10f2c67d.png)

</details>

## Changelog entry

* Update Tooltip styles to match GM2+ designs.

**Comment by tofumatt** [comment]
ACs look good here 👍🏻

**Comment by felixarntz** [comment]
@asvinb Regarding the IB, I'm a bit confused about what the intention of the dashboard sharing tooltip specific changes here is. Could you clarify?

It looks like #5444 also introduced the wrong tooltip style globally. Looks like this was in Figma, but that is still inconsistent. We should consistently go with the styles from the Figma file you linked above (which Victor shared earlier), for all tooltips (except those from the tooltip tours). In other words, the tooltips in the Site Kit header bar should have similar appearance as the tooltips in the dashboard sharing modal. That's why I think we need to remove any "dashboard sharing"-specific tooltip classes here and rather focus on the generic tooltip, which should apply everywhere except for the larger ones used in tooltip tours.

**Comment by asvinb** [comment]
@felixarntz I thought we wanted to keep the styles for the dashboard sharing tooltip to match the Figma designs, hence why we had #5444 However, I see your point of having all tooltips to be consistent and match what we [have in the designs](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?node-id=564%3A2006) for Tooltips. I've updated the IB, let me know what you think.

**Comment by felixarntz** [comment]
@asvinb Thanks, I've clarified that in the ACs as well. IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The styling of the tooltip element matches the figma design provided in the AC.
- Checked the tooltip for SK header, dashboard sharing, including view only menu. 
- Checked that the TourTooltips are not affected by the changes

<details>
 <summary>Details</summary>

![image](https://user-images.githubusercontent.com/73545194/200795794-df4c2934-bc9c-4038-93f8-f30d0173061e.png)

https://user-images.githubusercontent.com/73545194/200795837-67a54b01-e4b3-45a5-9fcb-47b05c4b2338.mp4

</details>

**Comment by sebastianmantel** [comment]
This is the final tooltip design and it should be applied throughout the UI. 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/102580610/203009058-e1edd93c-324a-4fc7-b291-fd775e1bd8eb.png">

**Comment by marrrmarrr** [comment]
@felixarntz @wpdarren overall the tooltips LGTM. 

The only question I have is why we have a tooltip also for the Account (appears at 0:07 in the video Darren had linked). Especially with how we're planning to redesign the menu to include the account (see #5775), it will be repetitive. But we can discuss this separately, this is not a blocker for this particular issue.

**Comment by aaemnnosttv** [comment]
> The only question I have is why we have a tooltip also for the Account (appears at 0:07 in the video Darren had linked). Especially with how we're planning to redesign the menu to include the account (see #5775), it will be repetitive.

@marrrmarrr this is consistent with most other Google web interfaces (e.g. Gmail, Drive, Docs) which have a tooltip for the user menu which also includes the same information. It is redundant but is probably there for accessibility and consistency with other menu buttons. Our implementation is largely mirroring the pattern which is already present across many major Google products 🙂 

Closing this out for the release as you've noted it isn't release blocking. Thank you!
