### ISSUE TITLE
Add jsx-curly-brace-presence ESLint rule to enforce consistent use of braces in JSX

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6060]
## Feature Description

Add the [`react/jsx-curly-brace-presence`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) ESLint rule to disallow unnecessary JSX expressions when literals alone are sufficient.

Examples of incorrect code for this rule, when configured with `{ props: "never", children: "never", "propElementValues": "never" }`:

```jsx
<App>{'Hello world'}</App>;
<App prop={'Hello world'} attr={"foo"} />;
<App prop=<div /> />;
```

They can be fixed to:

```jsx
<App>Hello world</App>;
<App prop="Hello world" attr="foo" />;
<App prop={<div />} />;
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `react/jsx-curly-brace-presence` rule should be added to ESLint with the default configuration.
* Any resulting ESLint errors should be fixed.

## Implementation Brief

* Add the `"react/jsx-curly-brace-presence": [ "error" ]` rule to our `.eslintrc.json`
* Fix the errors (probably with `npm run lint:js -- --fix`)

### Test Coverage

* No new tests are needed.

## QA Brief
* Ensure the PSI widget loads fine.
* Ensure the "Tracking" option works in "Settings -> Admin Settings"

ENG QA Brief
* Ensure all tests pass
* AdSense stories located in `stories/module-adsense-settings.stories.js` work fine

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
ACs were mostly good, but looks like the rule name changed and the supplied config didn't work, so I updated it. (The ACs were basically the IB, so IB added and moving to IBR) 👍🏻

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by hussain-t** [comment]
### QA:Eng Verified ✅ 

- Verified all tests pass.
- verified AdSense stories located in `stories/module-adsense-settings.stories.js` work fine.
