### ISSUE TITLE
Fix SetupSuccessBannerNotification stories.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6061]
## Bug Description

The Authentication Success stories under `SetupSuccessBannerNotification` are currently broken and should be fixed.

## Steps to reproduce

1. Open Storybook and go to `SetupSuccessBannerNotification`.
2. Click through the Authentication Success stories to see them in a non-functional state.

## Screenshots

![image](https://user-images.githubusercontent.com/18395600/197748205-9bb5f1e6-0c8b-4218-a0b8-28a6223984ac.png)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.86.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Authentication Success stories under `SetupSuccessBannerNotification` should be restored to their working state.
* VRT scenarios should be added to avoid this happening again.

## Implementation Brief

- Set the `googlesitekit_manage_options` capability to `true` by dispatching the `receiveGetCapabilities` or `receiveCapabilities` action of the `core/user` store.
- Add VRT scenarios for all the `authentication_success` stories by adding the `scenario` property to the stories.

### Test Coverage

- No new tests are to be added.
- VRT scenarios should be added as mentioned in the IB.

## QA Brief

- Verify that all the Storybook stories under `SetupSuccessBannerNotification` works as expected.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs are good, thanks for adding a VRT requirement 👍🏻

**Comment by hussain-t** [comment]
@techanvil, I cannot reproduce the errors in the `SetupSuccessBannerNotification` stories. Could you confirm it from your side? Thanks!

**Comment by techanvil** [comment]
@hussain-t that is odd. They are not working for me - not only locally but also on the published Storybook for `develop` -https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-setupsuccessbannernotification--site

If you go to that address what do you see?

**Comment by asvinb** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- All the Storybook stories under `SetupSuccessBannerNotification` work as expected.
  - Went through each story and clicked the CTA and links, everything looks good.
  - Checked that no console errors occured.
- Set up a new site and connected all of the modules to ensure that the success banner notifications appeared.

https://user-images.githubusercontent.com/73545194/203735312-c4cb4654-6b03-47cc-aa67-adc6de5d1673.mp4
