### ISSUE TITLE
Avoid using `_n()` for differentiating singular and plural (without number)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6069]
As outlined in e.g. [this article](https://gsm.fjellner.com/hints-about-i18n-let-your-code-to-shine-all-over-the-world/), `_n()` must only be used for strings which include a number to differentiate the different versions of the translation string. It must not be used to _only_ differentiate between singular and plural when there is no number involved.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The usages of `_n()` which do not include any number placeholder in the translation string should be replaced with two individual `__()` strings that are conditionally used based on the number.
    * Concretely, these usages are in the `AdSense` and `Analytics` PHP classes.
* A sentence must never be split across multiple translation strings.
    * Concretely, the TwG message in the `SetupSuccessBannerNotification` JS component needs to be modified to become one string with the link inside it (using `createInterpolateElement`).
* Translation strings should never start or end with a space. Instead such spaces should be included outside of the translation string.
    * Concretely, one occurrence in the `Dialog` JS component needs to be fixed.

## Implementation Brief

- In `includes/Modules/AdSense.php` and `includes/Modules/Analytics.php`:
    - Locate the usages of the `_n()` function.
	- Since the current usages do not include any number placeholders, instead of using the `_n()` function, we will assign the `$message` variable twice conditionally based on the number of invalid items (`metrics` or `dimensions`).
	- After the existing check to see if the number of invalid items (`metrics` or `dimensions`) is more than zero:
	    - Check if it is more than one (i.e. plural), and if so, assign the `$message` variable as it is right now, but replacing `_n()` with `__()`, removing the first and third parameters.
	    - If it is not more than one (i.e. singular), assign the `$message` variable as it is now, but replacing `_n()` with `__()`, removing the second and third parameters. The argument for the placeholder should be changed to the array of invalid items (e.g. `$invalid_metrics`) converted to a string (using `toString()`).
- In `assets/js/components/notifications/SetupSuccessBannerNotification.js`:
    - Locate the `winData` object property assignments for the `slug` variable being `thank-with-google`.
	- In the `description` property assignment, an external link should be added to the end of the current string that says `open the administrator panel` pointing to the `publicationURL` variable. This should be done using `createInterpolateElement`.
- In `assets/js/googlesitekit/components-gm2/Dialog.js`:
    - Locate the `p.mdc-dialog__dependecies` element.
	- Instead of displaying the `Note: ` text and `dependentModules` prop separately, use `createInterpolateElement` containing a `sprintf` function with a translatable string like this: `__( '<strong>Note:</strong> %s' )`. The placeholder value should be `dependentModules`.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

- This issue updates the way how the error message (_Unsupported (metric|dimension)/s requested: SOME_METRIC_) mentioned in the fifth point of [this QAB](https://github.com/google/site-kit-wp/issues/5712) is rendered. Follow [this QAB](https://github.com/google/site-kit-wp/issues/5712) and verify that the error message still appears as expected.
- On a Site Kit installation with _Thank with Google_ active and connected, go to this URL `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=thank-with-google` so that the success banner for connecting _Thank with Google_ shows up. Verify that the success banner shows up correctly as expected with the links working.
- Activate the following services in Site Kit: Analytics, Analytics 4, Optimize. Now, try to disconnect Analytics. In the disconnection confirmation modal, verify that the `Note: these active modules depend on...` text appears correctly.

## Changelog entry

* Avoid using _n() as a shortcut for singular/plural without using a number.

**Comment by tofumatt** [comment]
@nfmohit On the last point, for `components-gm2/Dialog.js`: we shouldn't be using `dangerouslySetInnerHTML`—instead, in that case, we can use `createInterpolatedElement` which is even safer and more idiomatic.

The content passed to that Dialog is always a string, see: https://github.com/google/site-kit-wp/blob/5504c3fef2ee371e6a1152b1729a1750ca57b986/assets/js/components/settings/SettingsActiveModule/ConfirmDisconnect.js#L148-L158

So it should be safe to avoid using `danerouslySetInnerHTML`.

Everything else here looks good.

**Comment by nfmohit** [comment]
Uh oh, my bad. Thank you for pointing that out, @tofumatt! I've updated the IB.

**Comment by tofumatt** [comment]
No worries, looks good now 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@nfmohit @techanvil two observations relating to the  `Note: these active modules depend on...` note when you disconnect Analytics.  It says (Alpha) after Analytics 4, is this expected?  I wonder if that will cause confusion. Also, there isn't a space after the comma between the two modules.  Very minor but feel we need to include a space so it's easy to read. 

![image](https://user-images.githubusercontent.com/73545194/201682777-d97632ec-255a-49c3-8c20-59fea2d96700.png)

**Verified:**

- The unsupported metrics error message appears when the code is run in console. 

![image](https://user-images.githubusercontent.com/73545194/201681915-ef0872a2-e13b-4510-ac04-a557c7854fc2.png)

- The TwG success banner appears as per the QAB. Not sure this applies anymore but checked anyway. 

![image](https://user-images.githubusercontent.com/73545194/201682304-5ccacbb6-bc9f-4da9-983a-aca640ce1505.png)

**Comment by hussain-t** [comment]
@wpdarren, the changes made as part of this ticket don't impact the text; instead, it changes how we translate the text. The above observations are reproducible in the `main` branch (which doesn't have these changes yet). IMO, these should be fixed as a separate issue. Can you create a ticket for it?

![Screenshot 2022-11-14 at 8 07 25 PM](https://user-images.githubusercontent.com/24408261/201690440-c0e7e6fb-3979-4702-a9e2-5fb7fad4c7d2.png)

**Comment by wpdarren** [comment]
QA Update: ✅ 

**Verified:**

- The unsupported metrics error message appears when the code is run in console. 

- The TwG success banner appears as per the QAB. Not sure this applies anymore but checked anyway. 

- The note appears on the modal when you disconnect Analytics.

<details>
 <summary>Details</summary>

![image](https://user-images.githubusercontent.com/73545194/201682304-5ccacbb6-bc9f-4da9-983a-aca640ce1505.png)
![image](https://user-images.githubusercontent.com/73545194/201681915-ef0872a2-e13b-4510-ac04-a557c7854fc2.png)
![image](https://user-images.githubusercontent.com/73545194/201691262-debf4ccd-027e-40d6-b3c5-f2030b8c9f04.png)

</details>

**Comment by felixarntz** [comment]
@wpdarren @hussain-t +1, a quick issue for this would be good, it should indeed not say "(Alpha)".

**Comment by wpdarren** [comment]
@felixarntz @hussain-t created [the ticket](https://github.com/google/site-kit-wp/issues/6148)! 👍
