### ISSUE TITLE
Update wording on TwG connect service screen

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6070]
## Bug Description

The wording on the TwG connect service screen is currently: 

> To get started, create an account. Currently available only in the US. If setup failed because you’re outside the US, disconnect Thank with Google in your Settings.

The second sentence is not a full sentence. This should be changed to:

> To get started, create an account. Thank with Google is currently available only in the US. If setup failed because you’re outside the US, disconnect Thank with Google in your Settings.

## Steps to reproduce

1. Enable TwG using the Tester plugin
2. Go to Settings > Connect More Services > TwG
3. See the TwG connect service screen

## Screenshots

<img width="731" alt="image" src="https://user-images.githubusercontent.com/12189958/198119314-00824182-4354-4f5b-bc0f-97f0a8093adf.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
Closing this out considering TwG status
