### ISSUE TITLE
Update Google API PHP client services library for new Tag Manager endpoints

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6076]
In order to implement support for the new Google Tag, we need to rely on recently added Tag Manager API endpoints for [container lookup](https://developers.google.com/tag-platform/tag-manager/api/v2/reference/accounts/containers/lookup) and [listing destinations](https://developers.google.com/tag-platform/tag-manager/api/v2/reference/accounts/containers/destinations/list).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Google API PHP client services library should be updated to a version that comes with the two endpoints [container lookup](https://developers.google.com/tag-platform/tag-manager/api/v2/reference/accounts/containers/lookup) and [listing destinations](https://developers.google.com/tag-platform/tag-manager/api/v2/reference/accounts/containers/destinations/list) included.
    * As of Wednesday, October 26, the library has been updated with the new code (see https://github.com/googleapis/google-api-php-client-services/tree/main/src/TagManager). So we will simply have to wait for the next release of the library to unblock this issue, which given the commonly weekly cadence should happen in a few days from now.

## Implementation Brief

- In the project folder, run the following command to update the Google API PHP client services library:
`composer require "google/apiclient-services:0.272.*"`
- Verify that the `google/apiclient-services` package has been updated to at least the `0.272.1` version in both `composer.json` and `composer.lock` files.
- To make sure the update doesn't cause any regressions, reset the Site Kit plugin and set it up from scratch, enabling all modules.
- Verify that there are no console errors or `WP_DEBUG` errors introduced.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

- This PR should include no visual regressions.
- Set up Google Site Kit from scratch including all the modules.
- Verify that there are no browser console or `WP_DEBUG` errors.
- Verify that there are no visual regressions.

## Changelog entry

* Update Google API PHP client services library for new Tag Manager endpoints.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Setup Site Kit on a new test site.  Set up all modules with no issues. 
- Disconnected and reset Site Kit and set up all modules again with no issues. 
- There are no browser console or WP_DEBUG errors.
- That there are no visual regressions.
