### ISSUE TITLE
e.keys is null dashboard error

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6084]
## Bug Description

[One user in the support forums](https://wordpress.org/support/topic/site-kit-analytics-failed-and-adsesne-lots-of-errors/#post-16142330) reported the below error on the SK dashboard. This is the third occurrence of this error, although the initial 2 support topics were closed with no response from the users who reported. 

```
e.keys is null

    in SearchConsoleStats
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in SearchFunnelWidget
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in Grid
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root<code></code>
```

The following console error appears on the same page, with object data included:

<details>

<summary>Browser console errors</summary>

```
TypeError: e.keys is null
    v https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-search-console-f6257d9ea65cda637f7b.js:11
    v https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-search-console-f6257d9ea65cda637f7b.js:11
    SearchConsoleStats https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-search-console-f6257d9ea65cda637f7b.js:40
    Ih https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    wi https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    ga https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Zj https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Lj https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Br https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    unstable_runWithPriority https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Mr https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Br https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    zr https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Rg https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Sh https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    n https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
googlesitekit-vendor-13b3f811b13d18cd1a54.js:7:746961
Caught an error: TypeError: e.keys is null
    v https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-search-console-f6257d9ea65cda637f7b.js:11
    v https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-search-console-f6257d9ea65cda637f7b.js:11
    SearchConsoleStats https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-search-console-f6257d9ea65cda637f7b.js:40
    Ih https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    wi https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    ga https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Zj https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Lj https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Br https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    unstable_runWithPriority https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Mr https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Br https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    zr https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Rg https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    Sh https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
    n https://jollytamilchat.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-13b3f811b13d18cd1a54.js:7
 
Object { componentStack: "\n    in SearchConsoleStats\n    in div\n    in div\n    in Widget\n    in WithWidgetSlug(Widget)\n    in SearchFunnelWidget\n    in WidgetRenderer\n    in div\n    in Cell\n    in WidgetCellWrapper\n    in div\n    in Row\n    in div\n    in div\n    in Grid\n    in WidgetAreaRenderer\n    in div\n    in WidgetContextRenderer\n    in DashboardMainApp\n    in DashboardEntryPoint\n    in RestoreSnapshots\n    in ErrorHandler\n    in ThemeProvider\n    in StrictMode\n    in Root" }
googlesitekit-main-dashboard-ed6d795717e4b7d1e1ec.js:15:5670
```

 </details>

<details>

<summary>Users Site Health information</summary>

### wp-core ###

version: 6.0.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/jollytamilchat.com/public_html
wordpress_size: 214.23 MB (224641226 bytes)
uploads_path: /var/www/jollytamilchat.com/public_html/wp-content/uploads
uploads_size: 22.42 MB (23512122 bytes)
themes_path: /var/www/jollytamilchat.com/public_html/wp-content/themes
themes_size: 31.98 MB (33529624 bytes)
plugins_path: /var/www/jollytamilchat.com/public_html/wp-content/plugins
plugins_size: 326.04 MB (341875290 bytes)
database_size: 37.02 MB (38813696 bytes)
total_size: 631.69 MB (662371958 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: JNews (jnews)
version: 10.8.0
author: Jegtheme
author_website: http://jegtheme.com/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, menus, automatic-feed-links, title-tag, post-thumbnails, align-wide, customize-selective-refresh-widgets, post-formats, html5, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, auto-load-next-post, editor-styles, editor-style, widgets
theme_path: /var/www/jollytamilchat.com/public_html/wp-content/themes/jnews
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty: version: 2.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.6, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.2, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.8.0

### wp-plugins-active (52) ###

Advanced Ads: version: 1.37.1, author: Thomas Maier, Advanced Ads GmbH, Auto-updates enabled
AMP: version: 2.3.0, author: AMP Project Contributors, Auto-updates enabled
AnyWhere Elementor Pro (Premium): version: 2.25.3, author: WP Vibes, Auto-updates enabled
Argus | Discord WordPress Plugin: version: 5.0.1, author: Nicolay Petrovich, Auto-updates enabled
Autoptimize: version: 3.1.3, author: Frank Goossens (futtta), Auto-updates enabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates enabled
Code Snippets: version: 3.2.1, author: Code Snippets Pro, Auto-updates enabled
Elementor: version: 3.7.8, author: Elementor.com, Auto-updates enabled
Elementor Pro: version: 3.7.7, author: Elementor.com, Auto-updates enabled
Health Check & Troubleshooting: version: 1.5.0, author: The WordPress.org community, Auto-updates enabled
JetElements For Elementor: version: 2.6.7, author: Crocoblock, Auto-updates enabled
JNews - AMP Extender: version: 10.0.3, author: Jegtheme, Auto-updates enabled
JNews - Auto Load Next Post: version: 10.0.3, author: Jegtheme, Auto-updates enabled
JNews - Bookmark: version: 10.0.1, author: Jegtheme, Auto-updates enabled
JNews - Breadcrumb: version: 10.0.1, author: Jegtheme, Auto-updates enabled
JNews - Detail Category Customizer: version: 10.0.1, author: Jegtheme, Auto-updates enabled
JNews - Essential: version: 10.0.7, author: Jegtheme, Auto-updates enabled
JNews - Food Recipe: version: 10.0.2, author: Jegtheme, Auto-updates enabled
JNews - Frontend Submit: version: 10.0.2, author: Jegtheme, Auto-updates enabled
JNews - Frontend Translation: version: 10.1.1, author: Jegtheme, Auto-updates enabled
JNews - Gallery: version: 10.0.2, author: Jegtheme, Auto-updates enabled
JNews - Gutenberg: version: 10.0.1, author: Jegtheme, Auto-updates enabled
JNews - Instagram Feed: version: 10.0.0, author: Jegtheme, Auto-updates enabled
JNews - JSON-LD: version: 10.0.2, author: Jegtheme (latest version: 10.0.3), Auto-updates enabled
JNews - Like: version: 10.0.0, author: Jegtheme, Auto-updates enabled
JNews - Meta Header: version: 10.0.3, author: Jegtheme, Auto-updates enabled
JNews - Podcast: version: 10.0.3, author: Jegtheme, Auto-updates enabled
JNews - Push Notification: version: 10.0.1, author: Jegtheme, Auto-updates enabled
JNews - Review: version: 10.0.2, author: Jegtheme (latest version: 10.0.3), Auto-updates enabled
JNews - Social Login: version: 10.0.3, author: Jegtheme, Auto-updates enabled
JNews - Social Share: version: 10.0.5, author: Jegtheme, Auto-updates enabled
JNews - Split: version: 10.0.3, author: Jegtheme (latest version: 10.0.4), Auto-updates enabled
JNews - Subscribe to Download: version: 10.0.1, author: Jegtheme, Auto-updates enabled
JNews - Tiktok Feed: version: 10.0.0, author: Jegtheme, Auto-updates enabled
JNews - Video: version: 10.0.6, author: Jegtheme, Auto-updates enabled
JNews - View Counter: version: 10.0.5, author: Jegtheme, Auto-updates enabled
JNews - Weather: version: 10.0.4, author: Jegtheme, Auto-updates enabled
JNews - Webstories: version: 10.0.1, author: Jegtheme, Auto-updates enabled
OneSignal Push Notifications: version: 2.3.2, author: OneSignal, Auto-updates enabled
Premium Addons for Elementor: version: 4.9.36, author: Leap13, Auto-updates enabled
Premium Addons PRO: version: 2.8.12, author: Leap13, Auto-updates enabled
Site Kit by Google: version: 1.86.0, author: Google, Auto-updates enabled
SmartCrawl Pro: version: 3.2.1, author: WPMU DEV, Auto-updates enabled
Ultimate Addons for Elementor: version: 1.36.12, author: Brainstorm Force, Auto-updates enabled
Web Stories: version: 1.25.1, author: Google (latest version: 1.26.0), Auto-updates enabled
weLaunch Framework: version: 1.0.12, author: weLaunch.io, Auto-updates enabled
WordPress Importer: version: 0.8, author: wordpressdotorg, Auto-updates enabled
WordPress TotalDesk: version: 1.7.26.1, author: weLaunch, Auto-updates enabled
WP MAPS PRO: version: 5.3.3, author: flippercode, Auto-updates enabled
WPMU DEV Dashboard: version: 4.11.17, author: WPMU DEV, Auto-updates enabled
WP Rocket: version: 3.12.1, author: WP Media, Auto-updates disabled
wptools: version: 3.41, author: Bill Minozzi, Auto-updates enabled

### code-snippets (5) ###

snippet-1: name: Make upload filenames lowercase, scope: global, modified: 2022-10-27 20:03:08, tags: [sample, media]
snippet-2: name: Disable admin bar, scope: front-end, modified: 2022-10-27 20:03:08, tags: [sample, admin-bar]
snippet-3: name: Allow smilies, scope: global, modified: 2022-10-27 20:03:08, tags: [sample]
snippet-4: name: Current year, scope: content, modified: 2022-10-27 20:03:08, tags: [sample, dates]
snippet-5: name: delay post fix , scope: global, modified: 2022-10-27 20:37:10

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 200M
upload_max_filesize: 200M
max_effective_size: 200 MB
max_file_uploads: 200
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.55.0

### wp-server ###

server_architecture: Linux 5.15.0-52-generic x86_64
httpd_software: nginx/1.23.1
php_version: 7.4.32 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 300
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 200M
php_post_max_size: 200M
curl_version: 7.81.0 OpenSSL/3.0.2
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.6.10-MariaDB-1:10.6.10+maria~ubu2204
client_version: mysqlnd 7.4.32
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/jollytamilchat.com/public_html/wp-content
WP_PLUGIN_DIR: /var/www/jollytamilchat.com/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### google-site-kit ###

version: 1.86.0
php_version: 7.4.32
wp_version: 6.0.3
reference_url: https://jollytamilchat.com
amp_mode: secondary
site_status: connected-site
user_status: authenticated
verification_status: verified-non-site-kit
connected_user_count: 1
active_modules: site-verification, search-console, analytics, analytics-4, pagespeed-insights
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ✅
	googlesitekit_view_wp_dashboard_widget: ✅
	googlesitekit_view_admin_bar_menu: ✅
enabled_features: 
	adsenseSetupV2: ✅
	dashboardSharing: ⭕
	ga4ActivationBanner: ⭕
	ideaHubModule: ⭕
	twgModule: ⭕
	userInput: ⭕
search_console_property: https://jollytamilchat.com/
analytics_account_id: none
analytics_property_id: none
analytics_profile_id: none
analytics_use_snippet: yes
analytics_4_property_id: none
analytics_4_web_data_stream_id: none
analytics_4_measurement_id: none
analytics_4_use_snippet: yes

### amp_wp ###

amp_slug_query_var: amp
amp_slug_defined_late: false
amp_mode_enabled: transitional
amp_reader_theme: legacy
amp_templates_enabled: post, page, is_singular, is_front_page, is_home, is_archive, is_author, is_date, is_search, is_404, is_category, is_tag, is_tax[saved_reply_categories], is_tax[saved_reply_tags], is_tax[faq_topics], is_tax[jnews-series], is_post_type_archive[web-story]
amp_serve_all_templates: true
amp_css_transient_caching_disabled: false
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 133
amp_css_transient_caching_time_series: 
	20221027: 124
	20221028: 133
amp_libxml_version: 2.9.14

### web_stories ###

web_stories_version: 1.25.1
web_stories_db_version: 3.0.14
web_stories_amp_version: 2.3.0
web_stories_cdn_url: https://wp.stories.google/static/19
web_stories_dev_mode: false
web_stories_theme_support: Disabled
web_stories_enabled_experiments: 
	Floating Menu: Enabled
	Layer locking: Enabled
	Layer grouping: Enabled
	Layer naming: Enabled
	Context Pages: Enabled
	Trim media recording: Enabled
	Stickers: Enabled
	Improved Autosaves: Enabled
web_stories_libxml_version: 2.9.14

</details>

Awaiting further insights from impacted user. Issue to be updated. 

## Additional Context

 -  server_architecture: Linux 5.15.0-52-generic x86_64
 - httpd_software: nginx/1.23.1
 - php_version: 7.4.32 64bit
 - SK version: 1.86.0

## Impacted users

- https://wordpress.org/support/topic/site-kit-analytics-failed-and-adsesne-lots-of-errors/ | **SH within topic** | Open
- https://wordpress.org/support/topic/search-console-error-9/ | **No SH info** | Closed - no response from user
- https://wordpress.org/support/topic/e-keys-is-null/ | **No SH info** | Close - no response from user

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
@jamesozzie Looks like we have had 3 reports of this with the last being over 2 months ago and the other 2 over a year ago. Are you happy to close this one out as we have had no further reports? 

We can reopen should we get any new reports and details.

**Comment by jamesozzie** [comment]
Sounds good to me @adamdunnage. Closing.
