### ISSUE TITLE
Adminbar menu should show on homepage  

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#61]
When viewing the site homepage, users should see the adminbar menu. clicking this will show them details for the hompage only (eg not the entire site). Currently in my testing, I do not see the Site Kit menu on the homepage.

This only applies if the homepage already has stats available in Search Console. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* Ensure admin bar menu shows as expected for single posts when on a staging or development environment mirroring real posts, and ensure the menu is shown for the correct single post.

## Acceptance criteria

* For the following tests, either:
  * make sure the posts you test with have actual search console data available
  * or temporarily comment out the logic to make the admin bar menu depend on search console data
* Set up your homepage to show a list of posts.
* Go to the homepage and ensure the admin bar menu does not show up (since it for now only shows for individual posts).
* Set up your homepage to show a static page and also pick a page in the same section for your blog.
* Go to the homepage and ensure the admin bar menu shows up (since the homepage now is an actual post).
* Go to the blog page and ensure the admin bar menu shows up (since the blog page is now an actual post). It should show stats for that blog page, not for any of the posts listed.
* Ensure the More Stats links in the admin bar lead to the dashbaord detail stats for the same page in the backend.

**Comment by ivankristianto** [comment]
QA passed based on the acceptance criteria. Closing this issue as fixed.
