### ISSUE TITLE
Disable "How to improve" CTA on PageSpeed widget while re-running test

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6106]
## Bug Description

On the Page Speed Insights widget, when a user clicks on the `Run test again` link, most of the widget is disabled while the test is running again.  In 1.87.0 we introduced a new layout with `How to improve` CTA button, underneath the results.  While the test is running, the CTA button is not deactivated like the rest of the widget. 

For a better user experience, we should make the CTA deactivated like the rest of the elements within the widget. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/a6d23379-a821-488e-a429-b1839f85ea30)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All buttons, links, and tabs within the PageSpeed widget should be disabled (visually and functionally) while a test is being re-run
    * The only exception to this should be the source link ("View details at PageSpeed Insights")

#### Disabled State Functionality:

In `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js`:
* Pass the `disabled` prop to the "How to improve" `Button` component with the value of `isFetching`.
* Pass the `disabled` prop to the "In the Lab", "In the Field", and "How to improve" `Tab` components with the value of `isFetching`.
* Pass the `disabled` prop to the `DeviceSizeTabBar` component with the value of `isFetching`.
https://github.com/google/site-kit-wp/blob/36045e5aba5a8d3dc94473399dbd262e2c59e50a/assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js#L130-L131

In `assets/js/components/DeviceSizeTabBar.js`:
* Add a new `disabled` prop.
* Pass the `disabled` prop to the `Tab` component.

#### Disabled State Styling:

* To add custom styles to have a visual effect of the disabled state, we need to add similar styles as how it was implemented in the `DimensionTabs` component.
* Extract the following (only the `disabled`) styles from `assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss` and move it to `assets/sass/vendor/_mdc-tab.scss`:
https://github.com/google/site-kit-wp/blob/36045e5aba5a8d3dc94473399dbd262e2c59e50a/assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss#L70-L87
* Ensure the styles are applied correctly and don't break the `DimensionTabs` component disabled state styling.

### Test Coverage

In `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.test.js`:
* Add a new test case for the "How to improve" `Button` that is disabled while the test is running.
* Add a new test case for the "In the Lab", "In the Field", and "How to improve" `Tab` which are disabled while the test is running.
* Add a new test case for the `DeviceSizeTabBar` is disabled while the test is running.

## QA Brief

- Go to the SK PSI widget.
- Click the `Run test again` button.
- Ensure the `How to improve` button is disabled.
- Ensure the `In the Lab`, `In the Field`, and `How to improve`  data source tabs are disabled.
- Ensure the device size tabs are disabled.
- Ensure that none of the tabs are clickable.
- Ensure the newly added [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-pagespeed-insights-widgets-dashboardpagespeedwidget--test-running-disabled) for the disabled state is as expected.

## Changelog entry

* Disable "How to improve" CTA on PageSpeed widget while re-running test.

**Comment by techanvil** [comment]
Hi @hussain-t, the specced IB solves the functional side of things, but adding `disabled` to the `Tab` components doesn't result in any visual difference to the tabs. The AC does specify that they should also be visually disabled, so please can you consider how to address this aspect?

**Comment by techanvil** [comment]
Thanks @hussain-t, I think it's a good idea to bring the disabled styling into the common SCSS.

A couple of points - 

- I'd be a bit cautious about including of the `height/margin/padding` styles - are you sure those are applicable to all the places we're using `Tab`?
- Looks like a typo and `DisabledTabs` should read `DimensionTabs`.

**Comment by techanvil** [comment]
Thanks @hussain-t!

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When the user clicks on the `Run test again` link all of the buttons, links and tabs are disabled and not clickable. 
- When an error appears within the PSI widget, the user clicks the retry button and all of the buttons, links and tabs are disabled and not clickable. 
- Check the [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-pagespeed-insights-widgets-dashboardpagespeedwidget--test-running-disabled) is on the disabled state is as expected.

https://user-images.githubusercontent.com/73545194/210807616-98663b80-7c90-4bfc-9758-8b464905fe3d.mp4
