### ISSUE TITLE
Refactor storage code/Use localForage for offline storage

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#611]
I think we should look into integrating [localForage](https://github.com/localForage/localForage) into SiteKit for our caching layer. As mentioned in https://github.com/google/site-kit-wp/issues/571#issuecomment-535979876 and https://github.com/google/site-kit-wp/issues/572#issuecomment-536494520, we can reduce the amount of code implemented in Site Kit by relying on localForage's implementation of things like `keys()`, `removeItems()`, etc.

localForage provides these methods and extensively tests them, as well as providing a non-block/non-main-thread storage API (using `IndexedDB`/`WebSQL` in modern browsers). It also accommodates users in private browsing modes and other edge cases using storage.

For our caching/offline storage code, integrating localForage would be straightforward, reduce our code, and should improve performance for pieces of the page that set/pull heavily from the cache.

The extra size of the library over the current storage code is `~20kB` uncompressed/un-gzipped. Gzipped I recall localForage adding about 9kB to a bundle, though I am looking to reduce its footprint a bit in the coming months 😉

Filing this at @felixarntz's request, to discuss any other pros/cons using localForage to handle our storage needs.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@tofumatt Can you outline the benefits of doing this over what we currently have a bit further? Are you still maintaining this library? My main concern here is how beneficial is this vs the potential cost it introduces, e.g. regarding having to fix issues upstream, or you no longer maintaining this at some point and then we would need to fork or, more likely, switch back to our current integrated implementation.

**Comment by tofumatt** [comment]
To answer the questions… the benefits are partially around speed, storage size, and flexibility with backends for storage on various browsers. Additionally, localForage probably has more extensive tests than our storage code. Those would be the benefits.

But given our continued "basic" usage of `sessionStorage` and `localStorage` as an HTTP response caching layer mostly, we're probably fine to stick with our current solution. If we were starting over I might propose using localForage—but at this point I think our current solution is fine and probably even has some developer wins, being very easy to interact with using basic browser console tools.

I think we can close this issue for now—it's probably only worth revisiting if we need to start storing more complicated things like images or files offline, or if we ever start to approach using more than a few megabytes of storage (the usual localStorage limit). 🙂 

Come to think of it, the main concern would actually be that `sessionStorage` and `localStorage` are often limited to around 5MB in browsers, whereas localForage uses IndexedDB which has a MUCH larger size limit by default (usually at least 50MB), but can be expanded when full. While _Site Kit itself_ isn't likely to use that much storage, other WordPress plugins might and could cause us issues as the storage is per-domain/subdomain.

Still, we've yet to ever have a user complain of slow loading that seems related to `sessionStorage` getting too big, preventing us from caching HTTP responses, so I think this is still fine to close 🙂
