### ISSUE TITLE
Prefix dependencies to circumvent plugin conflicts

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#612]
## Bug Description

We need to prefix Composer dependencies that we deploy as part of the bundled plugin in order to prevent conflicts with other plugins shipping the same dependencies (potentially in different versions).

This would fix issues #223, #246, #610, and possibly others too.

It is terrible that we need to do this, but since WordPress does not provide any dependency mechanism, this is the only way to work within these constraints.

There are several options out there to accomplish that, and we need to decide on one of these (e.g. https://github.com/coenjacobs/mozart, https://github.com/humbug/php-scoper). Also see https://github.com/ampproject/amp-wp/issues/1867 for the same discussion on the AMP plugin (for which the implications are not _as_ bad because their dependencies are probably less commonly used than the Google API ones).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Third-party PHP code should not be loaded directly from `vendor`, but in a prefixed version from a `third-party` directory.
* The prefix should be `Google\SiteKitDeps\`.
* The plugin should include its own non-Composer-based autoloader which works similar to PSR-4, specifically for the namespaces the plugin uses (`Google\Site_Kit` and `Google\SiteKitDeps`). See https://github.com/wprig/wprig/blob/v2.0/functions.php#L36 for inspiration.
* The `release-zip` task must no longer include anything from the `vendor` directory in the release. Instead it must include the `third-party` directory.

## Implementation Brief

* See #696's relevant technical choices

## Changelog entry

* Prefix all third-party PHP dependencies to resolve various potential incompatibilities with other plugins that bundle similar dependencies.

**Comment by marrrmarrr** [comment]
@aaemnnosttv could you help formulate the ACs for this issue, since Felix is mostly out this week?

**Comment by aaemnnosttv** [comment]
Sure thing @marrrmarrr! I'll put something together today.

**Comment by aaemnnosttv** [comment]
CR ✅

**Comment by felixarntz** [comment]
@aaemnnosttv Correct, these two AC inconsistencies are okay because they make more sense to be as was decided in the meantime.

The `third-party` name is a convention typically required for Google projects, that's the main reason for that name. It was okay to stick with `vendor` before since that is just the Composer default, but now that we can freely decide I therefore chose `third-party`.

**Comment by aaemnnosttv** [comment]
### QA ✅ 

See https://github.com/google/site-kit-wp/issues/612#issuecomment-546265238 for details

Moving to Approval

**Comment by felixarntz** [comment]
We need to also prefix the generated `Composer\Autoload\ClassLoader` files in `includes/vendor` and `third-party/vendor`.

**Comment by marrrmarrr** [comment]
verified

**Comment by archon810** [comment]
Any way to make this work with composer due to requiring guzzle 5.3.3 for those setups that have deps that require 6+?

https://github.com/google/site-kit-wp/blob/1.0.0/composer.json#L18

https://github.com/google/site-kit-wp/issues/223

**Comment by aaemnnosttv** [comment]
@archon810 all dependencies are now prefixed with a Site Kit specific namespace, so there should be nothing preventing you from using a different version of any dependency 😄
