### ISSUE TITLE
Excessive PHP Warnings

### ISSUE THREAD

**Issue by robindevitt** [google/site-kit-wp#6125]
## Bug Description

When running [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) the plugin generates +- 100 warnings that come up.

Example warnings:
```php

FILE: content/plugins/google-site-kit/third-party/google/apiclient/src/Service/Resource.php
----------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------
 31 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_CLASS)
----------------------------------------------------------------------------------------------------------------------------


FILE: content/plugins/google-site-kit/third-party/google/apiclient-services/src/GoogleAnalyticsAdmin/Resource/PropertiesWebDataStreams.php
----------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------
 18 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
----------------------------------------------------------------------------------------------------------------------------


FILE: content/plugins/google-site-kit/third-party/google/apiclient-services/src/GoogleAnalyticsAdmin/Resource/PropertiesDataStreamsMeasurementProtocolSecrets.php
----------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------
 18 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
----------------------------------------------------------------------------------------------------------------------------

```

All the warnings for the plugin are for a similar type warning.

Information for this is listed here - https://www.php.net/manual/en/reserved.other-reserved-words.php

GIST of all warnings - https://gist.github.com/robindevitt/c913b2b8e25be4303aaa0a27b44ff2c1

## Steps to reproduce

1. Install PHP_CodeSniffer - https://github.com/squizlabs/PHP_CodeSniffer#installation
2. I use the following to run PHP_CodeSniffer:
```
./vendor/bin/phpcs -p --standard=PHPCompatibility \
  --runtime-set testVersion 7.4 \
  --extensions=php \
  -d memory_limit=1G \ .
```
3. Observe the errors identified above.

## Additional Context

 - PHP Version: 7.4
 - OS: OSX
 - Browser: N/A
 - Plugin 1.85.0
 - Device: N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi @robindevitt Thanks for flagging this. The team will certainly have a look into this and address anything that needs to be addressed in the plugin. Any updates will be posted here.

**Comment by ntwb** [comment]
p.s The above is for PHP 7.4, we will be running the same check for PHP 8.0 in the very near future:

```
./vendor/bin/phpcs -p --standard=PHPCompatibility \
  --runtime-set testVersion 8.0 \
  --extensions=php \
  -d memory_limit=1G \ .
```

So, if these happen to get fixed before we get to v8, that'd be most welcome and awesome

**Comment by aaemnnosttv** [comment]
Thanks for flagging this @robindevitt. It seems all of the warnings you're seeing are about the use of `resource` as a soft reserved keyword which are all coming from the bundled [`google/apiclient-services`](https://github.com/googleapis/google-api-php-client-services) library. As a generated client library, we can't resolve these warnings on our end.

See https://github.com/googleapis/google-api-php-client-services/issues/577 for a somewhat related issue.

This probably can't be changed without making breaking changes but worth raising [upstream](https://github.com/googleapis/google-api-php-client-services) 👍 

Any changes there will naturally be pulled in here as we update this fairly often.

**Comment by robindevitt** [comment]
Thanks for the update @aaemnnosttv 👍🏼

**Comment by ntwb** [comment]
@aaemnnosttv Thanks for the reply and status update but I would think that the team here in this repo would report and update any dependencies used in this project to ensure the plugin works without issue for the currently supported PHP versions.

Hence, this issue is still valid IMHO and should not be closed until this issue is resolved

**Comment by felixarntz** [comment]
@ntwb Since this issue has now been reported upstream in https://github.com/googleapis/google-api-php-client-services/issues/2107, there isn't really anything else we can do about it, except update to a new version of that library once the change is (hopefully) eventually implemented.

> ensure the plugin works without issue for the currently supported PHP versions

I would like to point out that the warnings shared here occur only in PHPCodeSniffer, so the plugin _does_ work without issue for the currently supported PHP versions. While I acknowledge that it is preferable to avoid the use of these soft reserved keywords, they do not trigger any warnings or even deprecation notices in an actual PHP environment, so I'd argue it is not really an issue that impacts sites in any way.

I agree with you that in the long term it would be good to phase out the usage of them though.
