### ISSUE TITLE
Do not check `dashboardSharing` feature flag (or any additional flags) prior to `Modules::register()` call

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6129]
## Bug Description

For several months now, we've occasionally but consistently noticed errors in the Site Kit Service logs that the `/site-management/features/` request data was missing the `active_modules` key. I just ran into the same bug when doing a local test and figured out the problem, which must be occurring since May this year (#4481). It is not a severe bug from a user perspective, but still critical to address as it can notably delay feature rollout for new sites, plus it is simply causing a regular errors on the service.

As outlined in https://github.com/google/site-kit-wp/blob/1.87.0/includes/Core/Authentication/Authentication.php#L1410-L1414, the `ideaHubModule` and `twgModule` feature flag checks in `Modules::__construct()` are somewhat problematic because they check for a feature flag before `Modules::register()` is called, because then the `/site-management/features/` request would be missing crucial request data. The above comment therefore annotates a workaround where for those specific feature flags no request is made.

However, as part of #4481, the PR #5186 introduced a new feature flag check for `dashboardSharing` in `Modules::register()`, which is just as problematic - however for that one no workaround was added, causing the bug above.

Note that the bug only happens when remote features are requested because no data is yet present on the site. For the more regular Cron job refreshing features the bug fortunately does not apply.

## Steps to reproduce

1. Delete the `googlesitekitpersistent_remote_features` option from the database.
2. Log outgoing PHP API requests in some way.
3. Load e.g. the Site Kit dashboard.
4. See how the Site Kit Service `/site-management/features/` request is sent without the `active_modules` and `connected_modules` fields.

## How to address

Fortunately addressing this bug is quite trivial. It is not actually necessary to even check for the `dashboardSharing` feature flag in `Modules::__construct()`. That check is only used to instantiate the REST controller class property, however it would be more straightforward and simpler to only instantiate it when it's also being registered as a REST route (as part of `Modules::register()`). This also avoids the need for a class property, which other than for the registration isn't used anywhere.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `dashboardSharing` feature flag should not be checked in `Modules::__construct()`. Instead the REST controller class should only be instantiated in `Modules::register()`, just as it's being registered.
* A comment should be added to `Modules::__construct()` to clarify that no feature flag checks should happen here (or any time before `Modules::register()`, i.e. `init`).

## Implementation Brief

* Remove instantiation of `REST_Dashboard_Sharing_Controller` from `Modules::__construct()` and instead move it to `Modules::register()`, right to where that class's `register` method is then called.
* Remove the `$rest_dashboard_sharing_controller` class property from `Modules`, in favor of simply using a local variable (or not even assigning to any variable, as the new class only needs to be registered).
* Add a comment in `Modules::__construct()`, above the checks for `ideaHubModule` and `twgModule`: `Preferably no features should be checked here, or any time prior to Modules::register() being called to add the 'googlesitekit_features_request_data' filter callback. For any feature flags checked in this method, a workaround needs to be added to Authentication::filter_features_via_proxy() so that the remote features request is not triggered too early.`

### Test Coverage

* N/A

## QA Brief

* The code change here surrounds the Dashboard Sharing feature. So a simple smoke test of the plugin (just the dashboard) with and without Dashboard Sharing enabled should suffice. If possible, delete the `googlesitekitpersistent_remote_features` option from the database between page reloads.

### QA Eng
* Go through the Steps to Reproduce and verify that the first request to `/site-management/features/` contains the `active_modules` and `connected_modules` data as per the ACs in the [original issue](https://github.com/google/site-kit-wp/issues/4858).

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Thanks for raising this @felixarntz. Having given this a look, I don't think the issue is so much with the timing of the feature flag check, so much as the timing of the request which can happen synchronously in the feature flag filter. Feature flags were always intended to be checked at any time, which is why we initialized them as early as possible in `Plugin::load`. I worry that solving this from when a feature flag is checked is bound to come up again and we may run into situations where we want to check it earlier.

The definition here implies that we shouldn't check feature flags before a certain point in the request cycle to avoid this timing issue. Instead, I would suggest we decouple the request from the feature flags check as much as possible. I propose that we update the `filter_features_via_proxy` method to only apply/enable features based on the option value – always. Then we can move the fetching of features to a well-known point in the request lifecycle where we can be sure that this always happens at a safe point in time so that all data is included.

The saved value is already refreshed on a cron, so this request in the filter seems to only be relevant for the initial request which will happen as soon as the first feature is checked after a site has credentials. If that timing is critical, how about we move the initial request for features to the setup flow right after we receive the credentials? https://github.com/google/site-kit-wp/blob/d92a77704439ec02ee828929837bc0447c39521d/includes/Core/Authentication/Setup.php#L362-L367

Otherwise we could simply defer the request to `shutdown` similar to how we sync site fields.

This is related to #6015 so if you agree perhaps we can pick this up in the AC there?

**Comment by felixarntz** [comment]
@aaemnnosttv I agree there is room to solve this in a more sustainable and less error-prone manner, however I'd say for now we can add this "quick fix" to solve the bug for next release, while working in a follow up issue on a more holistic solution.

> The saved value is already refreshed on a cron, so this request in the filter seems to only be relevant for the initial request which will happen as soon as the first feature is checked after a site has credentials. If that timing is critical, how about we move the initial request for features to the setup flow right after we receive the credentials?

Exactly, it is only for when there's no data yet, but then it indeed should be checked ASAP. I thought that we already try to get the remote features right after getting the site credentials? If that's not the case, I must have messed that up somehow in my head, we should certainly do that if possible. That would be a good follow up issue to open IMO.

> Otherwise we could simply defer the request to `shutdown` similar to how we sync site fields.

See above, we probably wanna avoid that here.

**Comment by aaemnnosttv** [comment]
SGTM!

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on main branch.
- Verified both main and entity dashboard when dashboard sharing feature flag is disable.
- Verified both main and entity dashboard when dashboard sharing featured flag is enabled.
- Verified view only dashboard.
- Verified dashboard sharing functionality.
- I found one issue related to 'Reset sharing permissions' and it is also exist on latest so will create separate ticket for this. 
- As per 'QAB' tagging QA:eng.

**Comment by techanvil** [comment]
## QA:Eng :white_check_mark: 

- Deletd the `googlesitekitpersistent_remote_features` option and reloaded the Dashboard.
- Verified that the first request to `/site-management/features/` contains the `active_modules` and `connected_modules` data.
- Checked with and without Dashboard Sharing enabled.

_Without Dashboard Sharing enabled:_
![image](https://user-images.githubusercontent.com/18395600/202412562-c02aa6f3-c428-43cc-96f3-577056023065.png)

_With Dashboard Sharing enabled:_
![image](https://user-images.githubusercontent.com/18395600/202413509-09917841-3742-4dc5-ab5f-bfb22ba7eb96.png)

**Comment by felixarntz** [comment]
Great to see: No error logs found on the service with Site Kit version 1.88.0 (while those error logs _do_ show up for older versions), which shows that this is working as expected 🎉
