### ISSUE TITLE
Update the AdSense tag generator to its latest version

### ISSUE THREAD

**Issue by thomasfalezan** [google/site-kit-wp#6132]
## Feature Description

Update the AdSense tag generator to its latest version, as per the AdSense for Platforms documentation: https://developers.google.com/adsense/platforms/direct/ad-tags

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense tag placed by Site Kit should include Site Kit's platform host ID `ca-host-pub-2644536267352236` as outlined in the https://developers.google.com/adsense/platforms/direct/ad-tags#auto_ads docs.

## Implementation Brief

* Complete and merge #6133.

### Test Coverage

* Update test for tags to still pass according to new expected markup.

## QA Brief

* Set up AdSense and go to the frontend to check the tag placed by Site Kit.
* The AdSense tag from Site Kit should include the `host` query parameter.

## Changelog entry

* Update AdSense tag to include Site Kit platform host ID.

**Comment by jamesozzie** [comment]
Thanks for the suggestion @thomasfalezan. As the plugin doesn't include any AdSense for platform configurations at this time I'll categorize this as a plugin enhancement for the team to consider.

**Comment by adamdunnage** [comment]
This is currently not supported by Site Kit with no plans to support in the near future. Users looking to use this can still so so by placing their AdSense code manually and selecting Site Kit not to place the code for them.

Marking this as closed for now but may be reopened at a later date if needed.

**Comment by jamesozzie** [comment]
@adamsilverstein There is a [PR for this](https://github.com/google/site-kit-wp/pull/6133) submitted by the AdSense team. Would you be able to take a look?

**Comment by felixarntz** [comment]
@FlicHollis @eclarke1 This issue's PR #6133 is being worked on by someone from the AdSense team, just a heads up. So shouldn't involve us for more than code review and QA.
