### ISSUE TITLE
Remove TwG

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6134]
## Feature Description

The experimental Thank with Google module is to be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Thank with Google module is to be entirely removed including its feature flag, components, data store, classes, related styles, tests, stories, and assets
	* There should be no references to "twg" or "Thank with Google" other than the changelog

## Implementation Brief

- In `feature-flags.json`:
    - Remove `twgModule` from the returned array.
- In `assets/js/components/notifications/BannerNotifications.js`:
    - Remove `<ThankWithGoogleSupporterWallNotification />`.
- In `assets/js/components/notifications/SetupSuccessBannerNotification.js`:
    - In the switch case `authentication_success` for `notification`, remove the block where `slug` is `thank-with-google`.
- In `assets/js/components/notifications/SetupSuccessBannerNotification.stories.js`:
    - Remove the `ThankWithGoogle` story.
- In `includes/Core/Modules/Modules.php`:
    - Remove the `should_enable_twg()` method.
        - Remove its usages across the codebase.
- In `includes/Core/Authentication/Authentication.php`:
    - In the `filter_features_via_proxy()` method, remove the block where `$feature_name` is `twgModule`.
- Across the codebase:
    - Remove any remaining usages of the `Thank_With_Google` PHP class.
    - Remove any other remaining instances of `twg` and `/thank.with.google/` (case-insensitive).
- Delete the following directories and files:
    - `assets/js/modules/thank-with-google`
    - `assets/sass/components/thank-with-google`
	- `assets/js/googlesitekit-modules-thank-with-google.js`
    - `assets/js/components/notifications/ThankWithGoogleSupporterWallNotification.js`
    - `assets/js/components/notifications/ThankWithGoogleSupporterWallNotification.stories.js`
    - `includes/Modules/Thank_With_Google`
    - `includes/Modules/Thank_With_Google.php`

###  Test Coverage

- In `tests/js/utils.js`:
    - Remove `modulesThankWithGoogle` from the `allCoreModules` array.
- In `tests/phpunit/integration/Core/Modules/ModulesTest.php`:
    - Remove all test cases for `*_should_enable_twg_*`.
    - In the `test_feature_flag_enabled_modules()` test case, remove assignment and un-assignment of `$_SERVER['HTTPS']`.
- In `tests/phpunit/integration/Core/Authentication/AuthenticationTest.php`:
    - Update the test case for the `filter_features_via_proxy()` method to remove all assertions of `twgModule`.
- Delete the following directories and files:
    - `tests/phpunit/integration/Modules/Thank_With_Google`
    - `tests/phpunit/integration/Modules/Thank_With_GoogleTest.php`

## QA Brief

* TwG should no longer have any visible presence in the plugin
* Everything else should continue to work as usual

## Changelog entry

* N/A

**Comment by eclarke1** [comment]
Adding @marrrmarrr to please review, as per Asana task comment

**Comment by techanvil** [comment]
Hey @nfmohit, again this IB looks good, just one small detail that I'd suggest amending. Where you've specified this point:

> - Remove any other remaining instances of `twg`, `thank with google`, and `thank_with_google` (case-insensitive).

I'm sure the implementer would catch this anyway, but you might as well amend this to something like "...instances of `twg` and `/thank.with.google/`", (or `thank*with*google` if you find it clearer), to catch things like `thank-with-google` etc.

**Comment by techanvil** [comment]
Thanks, @nfmohit!

IB :white_check_mark:

**Comment by tofumatt** [comment]
QA ⚠️ 

Just a note that three Thank with Google VRT test files remain:

* `tests/backstop/reference/google-site-kit_Global_SetupSuccessBannerNotification_ThankWithGoogle_0_document_0_small.png`
* `tests/backstop/reference/google-site-kit_Global_SetupSuccessBannerNotification_ThankWithGoogle_0_document_1_medium.png`
* `tests/backstop/reference/google-site-kit_Global_SetupSuccessBannerNotification_ThankWithGoogle_0_document_2_large.png`

I've created a follow-up PR (#6309) to remove them, but this issue shouldn't be moved into approval until it's merged.

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt – merged 👍

**Comment by mohitwp** [comment]
QA Update ❌ 

@asvinb 

- Verified on dev.
- TwG feature flag is still available under tester plugin. User is able to enable TwG feature flag.
- TwG module available under Settings > Connect more services.
- User is able to set up TwG on dev.

<details>

![image](https://user-images.githubusercontent.com/94359491/206999069-69be5e58-81b8-4195-9613-5e957a68b3ac.png)

![image](https://user-images.githubusercontent.com/94359491/206999130-d5eeadae-487c-476d-9b92-fb30262e305b.png)



https://user-images.githubusercontent.com/94359491/206999168-e5e4d35e-032e-49f9-b980-1d46c982cf6c.mp4

</details>

**Comment by mohitwp** [comment]
### QA Update ❌ 

@asvinb 

- Verified on dev.
- Verified now that tester plugin fetching latest pull.
- Verified Thank with Google Feature flag is not available under Feature flag lists.

Issue > I found that feature flag is not listed on dev under Feature flag list but TwG settings are still available under tester plugin and on verifying page source I'm getting 5 references of TwG and 3 references of Thank with Google.


<details>

![image](https://user-images.githubusercontent.com/94359491/207521708-f07b8554-0692-4563-a8ac-51f2d8adf83d.png)


![image](https://user-images.githubusercontent.com/94359491/207521562-64900600-0e72-4ef3-9a95-06ebf609fde6.png)

![image](https://user-images.githubusercontent.com/94359491/207521608-0a630481-b9c8-4d92-920c-a9c086effefa.png)

</details>

**Comment by asvinb** [comment]
@mohitwp The tester plugin does not form part of the plugin and is not part of the repo. I would suggest following up with @felixarntz or @aaemnnosttv to remove TwG from the feature plugin.

**Comment by aaemnnosttv** [comment]
> I found that feature flag is not listed on dev under Feature flag list but TwG feature settings are still available under tester plugin. Would you please remove TwG feature settings from tester plugin ?

@mohitwp This is part of the Tester plugin which will be removed separately. There's no change we can make here to remove that 🙂

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev.
- Verified now that tester plugin fetching latest pull.
- Verified Thank with Google Feature flag is not available under Feature flag lists.
- Verified source code and response. All references of TwG removed successfully.
