### ISSUE TITLE
New Search console property created in wp multisite (subdirectory mood)

### ISSUE THREAD

**Issue by kabirbd89** [google/site-kit-wp#6141]
## Bug Description

In the process of initial activation of the site kit in wp multisite on subdirectory a new search engine console property is created if even the domain is added in the search console Domain property.  i.e. if I activate site kit in "example.com/site1" a property created in the search console with the following name "example.com/site1"

## Steps to reproduce

1. Add domain in search console property as domain property. 
2. Install a wp multisite in subdirectory mood.
3. Create site1 (example.com/site1)
4. activate sit kit on site1.

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi @kabirbd89 thanks for getting in touch. We don't provide support through GitHub but we can certainly help you out with all the issues you are facing through our Site Kit plugin support forum. Please could you [open a new support topic](upport/plugin/google-site-kit/#new-topic-0) and we will certainly look into this for you and help to answer any questions and help with issues you may have.

Thanks.
