### ISSUE TITLE
Cant add only GA4 tag in google analytics service 

### ISSUE THREAD

**Issue by kabirbd89** [google/site-kit-wp#6143]
## Bug Description
If I try to add only GA4 in google analytics service in sit kit ua property is required and vice versa for UA. I can't use only one, it requires two types of codes. 

It's okay to force the user to create a GA4 code when they try to use a UA code but when someone tries to use a GA4 tag there is no point in creating a requirement for UA code. its.

**Comment by adamdunnage** [comment]
Hi @kabirbd89 thanks for getting in touch. We don't provide support through GitHub but we can certainly help you out with all the issues you are facing through our Site Kit plugin support forum. Please could you [open a new support topic](upport/plugin/google-site-kit/#new-topic-0) and we will certainly look into this for you and help to answer any questions and help with issues you may have.

Thanks.
