### ISSUE TITLE
Change text when disconnecting Analytics with GA4 and Optimize connected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6148]
## Bug Description

While testing #6069 I had two observations.

Activate the following services in Site Kit: Analytics UA and GA4 properties, Optimize. Now, try to disconnect Analytics. In the disconnection confirmation modal.  There is text `Note: these active modules depend on...`

The text says (Alpha) after Analytics 4 which it shouldn't, also, there is no space after the comma, between the modules. 

The text should read: 

`Note: these active modules depend on Analytics and will also be disconnected: Analytics 4, Optimize`

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/3b7ccab3-c2cb-4bdb-8688-44cdab8f50c0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The string "Analytics 4 (Alpha)" should not be present anymore. Instead if should simply be "Analytics 4".

## Implementation Brief

* Inside `/includes/Modules/Analytics_4.php` locate `setup_info()` and remove ` (Alpha)` part inside `name` parameter
* Inside `/assets/js/components/settings/SettingsActiveModule/ConfirmDisconnect.js` locate `dependentModulesText` variable and format `dependentModules` using our [listFormat helper](https://github.com/google/site-kit-wp/blob/4e84de5ed5157499d451cbd1f2123affc4feec01/assets/js/util/i18n.js#L395)

### Test Coverage

* No tests needed

## QA Brief

* Connect Analytics, GA4 and Optimize
* Go to Settings -> Connected Services, click "Edit" and then "Disconnect Analytics from Site Kit"
* Verify GA4 ist listed in the dependent modules list without "(Alpha)".
* Verify the dependent modules are correctly listed without comma separator but with localized separator.

## Changelog entry

* Remove "Alpha"/"Beta" from Analytics 4 module name.

**Comment by tofumatt** [comment]
A note on the IB here: we shouldn't be using `join( ', ' )` on user-facing strings, but that isn't translatable and would result in lists that don't make sense in other locales.

We have a utility for this, named `listFormat`, and should rely on that: https://github.com/google/site-kit-wp/blob/4e84de5ed5157499d451cbd1f2123affc4feec01/assets/js/util/i18n.js#L395

I've added this to the IB, but just wanted to call it out for future references @sashadoes 🙂 . It's easy-to-miss 😅 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@derweili I've noticed that when I have Analytics and Optimize connected, and I go to disconnect Analytics, the message now says `(Beta)` instead of `Analytics 4`.   Also, should we have a space between the localized separator and modules?

Please see screenshot below. 

![image](https://user-images.githubusercontent.com/73545194/206713173-948e8152-08a0-44c0-a4ff-7dbf2328e3ca.png)

**Comment by asvinb** [comment]
As per Slack conversation with @wpdarren , sending back to QA to check again.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- GA4 is listed in the dependent modules list without "(Alpha)".
- The dependent modules are correctly listed without comma separator but with localized separator.

![image](https://user-images.githubusercontent.com/73545194/207357370-3f255957-7418-44e7-bd25-83cf6a9a7201.png)
