### ISSUE TITLE
I can't create the client ID

### ISSUE THREAD

**Issue by BiancaDome** [google/site-kit-wp#615]
I get this error: 
field [project_id] has issue [project_id contains invalid characters]

my site is https://www.guiacomprasonline.com
the support email is:   biancadome@gmail.com

**Comment by jamesozzie** [comment]
@BiancaDome Can you please follow the steps below to proceed with your Site Kit setup:  
1. Please check your WordPress site settings under "Settings > General" in your WordPress dashboard. Confirm your WordPress Address (URL) and Site Address (URL) match
2. Restart the Site Kit setup process again from an incognito window. If you see the same error access [this URL](https://developers.google.com/web/site-kit/?sitename=guiacomprasonlinecom&siteurl=https://guiacomprasonline.com)
3. Press the "GET OAUTH CREDENTIALS" button 
4. If using an incognito window you will need to login to your Google account to proceed. 
5. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 

If the instructions above fail to resolve your issue can you please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard?

**Comment by ferocello** [comment]
Hi,

I have exactly the same problem could please help me ?

https://www.23homedesign.com

ferocello@gmail.com

**Comment by jamesozzie** [comment]
@ferocello Have you followed the steps as per the previous message, ensuring your "Site Address" and "WordPress Address" match, including the protocol (https / http?) If they do not match please ensure they do, before opening the following URL:
https://developers.google.com/web/site-kit/?sitename=23homedesign&siteurl=https://23homedesign.com

Another thing to note is from checking your site it is not rendering as fully https. It looks like you have some images and possibly more content loaded without without the https, which could also be impacting setup. Please share your Site Health info from your WordPress dashboard if you are unable to continue with setup.

**Comment by ferocello** [comment]
Hi,

I did follow every step as  above and  Wordpress address and site address matches.`

Here is the site health info;



### wp-core ###

version: 5.2.3
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/l4povkr2fg4j/public_html
wordpress_size: 240.31 MB (251987994 bytes)
uploads_path: /home/l4povkr2fg4j/public_html/wp-content/uploads
uploads_size: 4.10 GB (4405633191 bytes)
themes_path: /home/l4povkr2fg4j/public_html/wp-content/themes
themes_size: 5.15 MB (5402634 bytes)
plugins_path: /home/l4povkr2fg4j/public_html/wp-content/plugins
plugins_size: 96.12 MB (100793938 bytes)
database_size: 16.31 MB (17103582 bytes)
total_size: 4.45 GB (4780921339 bytes)

### wp-active-theme ###

name: Astra
version: 2.1.1
author: Brainstorm Force
author_website: https://wpastra.com/about/
parent_theme: none
theme_features: astra_hooks, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, amp, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets, menus
theme_path: /home/l4povkr2fg4j/public_html/wp-content/themes/astra

### wp-themes (1) ###

Twenty Nineteen: version: 1.4, author: the WordPress team

### wp-plugins-active (26) ###

Astra Starter Sites: version: 1.3.19, author: Brainstorm Force
CartFlows: version: 1.2.6, author: CartFlows Inc
CoBlocks: version: 1.15.0, author: GoDaddy
Contact Form 7: version: 5.1.4, author: Takayuki Miyoshi
Contact Widgets: version: 1.6.2, author: GoDaddy
Easy Updates Manager: version: 8.0.5, author: Easy Updates Manager Team
Elementor: version: 2.7.4, author: Elementor.com
Facebook for WooCommerce: version: 1.9.15, author: Facebook
Limit Login Attempts Reloaded: version: 2.9.0, author: WPChef
Really Simple SSL: version: 3.2.5, author: Rogier Lankhorst, Mark Wolters
Site Kit by Google: version: 1.0.0-beta.1.0.7, author: Google
Smush: version: 3.2.4, author: WPMU DEV
Storefront Product Pagination: version: 1.2.4, author: WooThemes
Storefront Product Sharing: version: 1.0.6, author: WooCommerce
Storefront Sticky Add to Cart: version: 1.1.9, author: WooThemes
Tidio Chat: version: 3.5.0, author: Tidio Ltd.
Weglot Translate: version: 3.1.2, author: Weglot Translate team
WooCommerce: version: 3.7.0, author: Automattic
WooCommerce Admin: version: 0.19.0, author: WooCommerce
WooCommerce Cart Abandonment Recovery: version: 1.1.9, author: CartFlows Inc
WooCommerce PayPal Checkout Gateway: version: 1.6.17, author: WooCommerce
WooCommerce Stripe Gateway: version: 4.2.5, author: WooCommerce
Wordfence Security: version: 7.4.0, author: Wordfence
WP Content Copy Protection & No Right Click: version: 1.7.1, author: wp-buy
WPForms Lite: version: 1.5.5.1, author: WPForms
Yoast SEO: version: 12.2, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1684
imagemagick_version: ImageMagick 6.9.4-10 Q16 x86_64 2017-11-14 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 62 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 62 GB
	imagick::RESOURCETYPE_MEMORY: 31 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.66.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.3.7 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 32M
php_post_max_size: 32M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.44-cll-lve
client_version: 5.6.44

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/l4povkr2fg4j/public_html/wp-content
WP_PLUGIN_DIR: /home/l4povkr2fg4j/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### 0 ###

version: 1.5.5.1
license: undefined
lite: Aug 28, 2019 @ 8:38pm
db_tables: Not found
total_forms: 1
total_entries: undefined

`

**Comment by jamesozzie** [comment]
@ferocello There could be a plugin causing problems with generating your credentials. Can you disable your WooCommerce plugins, Tidio Chat and any caching plugins you have active? I can see references to WP Rocket from inspecting the console errors on your site. You will see another user reported 

After temporarily deactivating those plugins please attempt to setup Site Kit from an incognito window.

**Comment by jamesozzie** [comment]
@ferocello Are you encountering the same issue with Site Kit setup?

**Comment by ferocello** [comment]
i did the resolve the problem thanks to you guys:) Cheers.

**Comment by jamesozzie** [comment]
@BiancaDome Have you been able to successfully setup Site Kit? If issues remain when setting up please try to open the below URL when logged into your Google account in browser. 
[https://developers.google.com/web/site-kit/?sitename=guiacomprasonline&siteurl=https://guiacomprasonline.com](https://developers.google.com/web/site-kit/?sitename=guiacomprasonline&siteurl=https://guiacomprasonline.com)
