### ISSUE TITLE
Fix displaying empty brackets in Analytics 4 property select dropdown if there is no Measurement ID

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#6152]
## Feature Description

As we introduced displaying the measurement ID instead of the property ID in Analytics 4 property select dropdown in #5145, there is a specific case where the measurement ID can be `undefined` due to the `getWebDataStreamsBatch` selector returning an empty object for the given property ID. This results in the dropdown option value within the bracket will be `undefined` like so: `sitekit.10uplabs.com (undefined)`. This was temporarily fixed with an empty string in #5145.

<img width="339" alt="Screenshot 2022-11-15 at 6 12 05 PM" src="https://user-images.githubusercontent.com/24408261/201975873-cbdbfa05-80d9-45ed-8b17-2e769ee92dde.png">

We need a proper fix instead of showing an empty bracket.

**Steps to reproduce:**

- Delete all the GA4 properties from the Analytics console.
- Create a new one from the Analytics console.
- Click the Connect Google Analytics 4 CTA from the settings page

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by hussain-t** [comment]
Hi @marrrmarrr, what would be an appropriate placeholder copy for the GA4 property select if there is no Measurement ID? Thanks!

**Comment by bethanylang** [comment]
Can we add a priority label here, please? Thanks!

**Comment by hussain-t** [comment]
Closing this one as it's already been addressed in https://github.com/google/site-kit-wp/issues/6293
