### ISSUE TITLE
GA4 property dropdown not showing measurement id if number of properties more than 10.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6159]
## Bug Description

With the changes introduced in #5145. Now we replaced property id with measurement id in GA4 property select dropdown. But currently we are showing measurement id's for only initial 10 GA4 property in the dropdown. If account have more than 10 properties then measurement id is not showing for remaining properties in dropdown.

## Steps to reproduce

1. Connect oi.ie site using developer plugin.
2. Go to settings.
3. Open analytics settings in edit mode.
4. Open GA4 property dropdown.
5. Notice that measurement id is appearing only for initial 10 GA4 properties.

## Screenshots

[](https://user-images.githubusercontent.com/94359491/202380605-f4f6a259-6be6-4c37-a537-efddc8179501.mp4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Fixed in #6293
