### ISSUE TITLE
Update `getNotifications` resolver for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6163]
## Feature Description

In #5978 we addressed an issue where an error was being raised in storybook for the CoreNotifications component due to `Array.reduce` not existing on the `{}` notifications that were being received in the store. This is because notifications were attempting to be fetched from the store which was receiving the default fetch-mock response (an empty object) which of course does not have this method.

The root of the problem here is that the notifications resolver is implemented in a way which is inconsistent with our defacto pattern which skips invoking a fetch request if the resolver's selector already has data.
https://github.com/google/site-kit-wp/blob/a86ba4b109defc7d4c89289b2ca0589da870e10b/assets/js/googlesitekit/data/create-notifications-store.js#L184-L186

In the relevant stories, notifications _were_ already being received but due to this unguarded fetch, notifications were being fetched every time regardless which eventually resulted in the error shown in the console.

This resolver hasn't been touched since `createFetchStore` was introduced, which indicates that this omission was probably unintentional. Given the prolific use of the pattern that would solve this, it should be safe to apply here as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The notifications should only be fetched via the `getNotifications` resolver if none have been received in state (including an empty list)
* Fetch mocks for notifications in stories or tests where notifications have been manually received should be removed

## Implementation Brief

- In `assets/js/googlesitekit/data/create-notifications-store.js`:
    - In the `getNotifications()` resolver, only call the `fetchGetNotifications()` function if the `getNotifications()` selector returns a falsey value.
    - In order to call the selector function:
        - The `select` function can be obtained from `Data.commonActions.getRegistry()`.
        - The selector function should be run for the `STORE_NAME` variable which represents the respective data store.
        - Check any other resolver structure for reference.
- In `assets/js/components/notifications/CoreSiteBannerNotifications.stories.js`:
    - Remove the `mockEndpoint` function including all its usages and only rely on the `receiveGetNotifications` action.

### Test Coverage

- No tests need to be added/updated.
- Fix any failing tests.

## QA Brief

* No changes should be introduced for the end user.

## QA:ENG Brief
* Verify REST endpoints for notification are only fetched once.

## Changelog entry

* Only fetch server notifications if none have been received yet.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by asvinb** [comment]
@derweili Can you kindly add an Eng QAB please? Thanks!

**Comment by derweili** [comment]
@asvinb updated QA:Eng
