### ISSUE TITLE
Introduce `ga4Reporting` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6170]
## Feature Description

New GA4 reporting features will be built behind a new feature flag: `ga4Reporting`

This issue is just for adding this new flag to the code base which is necessary to integrate with our tooling for testing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ga4Reporting` feature flag should be added to the list of available features

## Implementation Brief

* Add the feature flag to `feature-flags.json`

### Test Coverage

* No changes necessary

## QA Brief

* The new feature flag should be toggle-able via the tester plugin

## Changelog entry

* N/A.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `ga4Reporting` feature flag is added to the list of available features.
- The `ga4Reporting` feature flag is able to be toggled, and saves with no errors.
- After enabling and saving the `ga4Reporting` feature flag when I refresh the page, the setting still remains.

![image](https://user-images.githubusercontent.com/73545194/203564010-ec5ea7d2-e4dd-4703-9766-11c8274495f2.png)
