### ISSUE TITLE
Add GA4 Data API to bundled client services

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6171]
## Feature Description

Site Kit includes a subset of the Google API client services library for each API that it uses. This is somewhat manually curated and often requires upgrades to the library in the process (especially when adding newly published APIs).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [GA4 Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/rest) should be included in Site Kit's bundled client services in the same way other APIs

## Implementation Brief

* To get the GA4 Data API (`vendor/google/apiclient-services/src/AnalyticsData.php`) to `third-party/google/apiclient-services/src/`, add the following to the `scoper.inc.php` file:
    * Add `AnalyticsData` (string) to the `$google_services` list.
* Note: After adding the above, executing `composer install` will add `AnalyticsData` to the `third-party/google/apiclient-services/src/` directory.

### Test Coverage

* No new tests are to be added.

### QA Eng
- Run `composer install`.
- Verify that the `AnalyticsData.php` file and `AnalyticsData` folder exists in the `third-party/google/apiclient-services/src/` folder.

## Changelog entry

* Add Google Analytics 4 Data API client library to bundled client services.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅
