### ISSUE TITLE
Add `GET:report` datapoint for GA4

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6172]
## Feature Description

This issue is for adding the necessary infrastructure to the GA4 module to request reporting data from the Analytics Data API.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `analytics-4` module should receive a `GET:report` datapoint that implements the equivalent of the same datapoint from the `analytics` module for GA4
    * The implementation should largely mirror what is in place for `analytics` today supporting date ranges, metrics, dimensions, as well as the response format
* The datapoint should use the `properties` resource of the `AnalyticsData` service
* The datapoint should be `shareable`
    * Requested metrics validation for view-only requests should be scaffolded similar to how it is done for Analytics – for now all metrics should be invalid for view-only requests – these will be allow-listed as we start to use them in the dashboard

## Implementation Brief

* Add a new `GET:report` datapoint in `Analytics_4::get_datapoint_definitions` with the following:
    * It should have the value of an array containing `service` with the value `analyticsreporting` and `shareable` with the boolean value based on the `dashboardSharing` feature flag.
* Create a new `validate_report_dimensions` method, the same as `Analytics::validate_report_dimensions`, that will validate view-only requests for dimensions.
* Create a new `validate_report_metrics` method, the same as `Analytics::validate_report_metrics`, that will validate view-only requests for metrics.
* Add a new case for `GET:report` in `Analytics_4::create_data_request` with the following logic:
  * It should essentially mirror the logic in `Analytics::create_data_request` for the `GET:report` datapoint, except that it should use the `AnalyticsData` service instead of the `AnalyticsReporting` service.

[See the JSON representation of the request to generate a report.](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/batchRunReports#runreportrequest)

**property** - It should be the property ID string.
* Use the `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunReportRequest::setProperty` method to set the property ID.

**dimensions (array<Dimension>)** - [API reference](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Dimension)
* Create `validate_report_dimensions` protected method similar to `Analytics::validate_report_metrics`.
* Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\Dimension::*` methods to set the request parameters.
* Use the `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunReportRequest::setDimensions` method to set the dimensions.

**dimensionFilter (DimensionFilter)** - [API reference](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/FilterExpression)
* Use the `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\FilterExpression::setFilter` method to set the filter.

**metrics (array<Metric>)** - [API reference](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Metric)
* Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\Metric::*` methods to set the request parameters.
* Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunReportRequest::setMetrics` to set the metrics.

**dateRanges (array<DateRange>)** - [API reference](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/DateRange)
* Create `create_analytics_site_data_request` protected method similar to `Analytics::create_analytics_site_data_request`.
* Use the methods from `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunReportRequest` and `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\DateRange` to create the request.
* Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\FilterExpressionList::setExpressions` method instead of `AnalyticsReporting\DimensionFilterClause::*` methods.
* Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunReportRequest::setDateRanges` to set the date ranges.
      
**orderBys (array<OrderBy>)** - [API reference](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/OrderBy)
* Create `parse_reporting_orderby` protected method similar to `Analytics::parse_reporting_orderby`.
* Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\OrderBy::*` methods to set the request parameters.
* Use the `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunReportRequest::setOrderBys` method set the `orderBys` list.
* Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\BatchRunReportsRequest::setRequests` to set the requests body.
* Finally, return the response from the `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\Resource\Properties::batchRunReports` method.

### Test Coverage

* Add test cases for the new methods `create_analytics_site_data_request` and `parse_reporting_orderby`.

## QA Brief

Smoke test Analytics and Dashboard Sharing, which should be unchanged.

### QA:Eng

- Enable the `ga4Reporting` feature flag.
- Give the new `GET:report` endpoint a test, exercising all of the allowed input parameters.
- To call the endpoint from the JS console:

```js
// Construct the params object, for example:

reportParams = {
  // Note, metrics is a required parameter. All others are optional. The property ID for the report will be the currently connected GA4 property.
  metrics: [
    {
      name: 'totalUsers',
    },
  ],
  startDate: '2022-11-01',
  endDate: '2022-11-14',
  dimensions: [ 'date' ],
  dimensionFilters: { 'sessionDefaultChannelGrouping': 'Organic Search' },
  orderby: [ { 'fieldName': 'totalUsers', 'sortOrder': 'ASCENDING' } ],
  url: 'https://example.com/some-page/',
  limit: 321
};

// Call the endpoint:
googlesitekit.api.get('modules', 'analytics-4', 'report', reportParams )
```

- Check the response in the network tab, alternatively `await` the return value of `api.get` and examine the result.
- The various input parameter formats can be seen in the PHPUnit test coverage, or by reading the handler source (see [PR](https://github.com/google/site-kit-wp/pull/6379/files) for both).
- Refer to the API documentation for allowable values (see links in IB).
- You may wish to use `mitmproxy` or an equivalent tool to examine the outbound requests made to the Google Analytics API. See configuration instructions in the [engineering workflow doc](https://docs.google.com/document/d/1vYRA-YxxZdufO6piF0gA1k60N3UxbvuqyQr_XfGgvSk/edit#heading=h.faf0umy03arh).

## Changelog entry

* Add `GET:report` datapoint for Google Analytics 4.

**Comment by tofumatt** [comment]
> It should essentially mirror the logic in `Analytics::create_data_request` for the `'GET:report'` datapoint, except that it should use the `AnalyticsData` service instead of the `AnalyticsReporting` service.

This is the only part I'm a bit confused about, because I'm not sure exactly what `AnalyticsReporting` service this is referring to in Analytics and what class/service we'd be using for Analytics 4. Can you point to an example of where we're using `AnalyticsReporting` and what we'd change it to for GA4?

Also, doesn't this mean we'd need to add `AnalyticsData` to https://github.com/google/site-kit-wp/blob/ebc165584eee3fb4aee28461830b658bd589bdf6/scoper.inc.php#L18 so it's available?

**Comment by hussain-t** [comment]
@tofumatt, regarding:
>This is the only part I'm a bit confused about, because I'm not sure exactly what AnalyticsReporting service this is referring to in Analytics and what class/service we'd be using for Analytics 4. Can you point to an example of where we're using AnalyticsReporting and what we'd change it to for GA4?

`AnalyticsReporting` is the third-party API client service and the methods which are used in `Analytics::create_data_request` -> `GET:report`  from that package - `Google\Site_Kit_Dependencies\Google\Service\AnalyticsReporting\*`.

>Also, doesn't this mean we'd need to add `AnalyticsData` to

It's being implemented in #6171

**Comment by tofumatt** [comment]
Oh right, of course! Thanks 😅 

Only one question, I see:

> Use `Google\Site_Kit_Dependencies\Google\Service\AnalyticsReporting\ReportRequest::setMetrics` to set the metrics.

Should that be:

> `Use Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\ReportRequest::setMetrics to set the metrics.`

I'm guessing it's just a typo, but worth clarifying here. Other than that looks good 👍🏻

**Comment by hussain-t** [comment]
Yes, it was a typo. Good catch, thanks, @tofumatt. It should be `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunReportRequest::setMetrics`. I have updated the IB.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
Having completed the implementation of this new endpoint (pending review), I'm recording a couple of notes here on notable changes in usage between this and the to-be-deprecated UA version.

This is generally relevant to the GA4 reporting work, and may impact the in-flight issues #6173 and #6174.

## Input parameters

The following changes should be applied when migrating from our existing UA report parameters to the GA4 version.

- `propertyID`:
  - `propertyID` is a new required parameter. In our usage this should be the currently active GA4 property ID and may be best populated in `getReport` rather than on a per-report basis.
- `metrics`:
  - Use `name` instead of `alias`. The explicit `alias` parameter is not supported by GA4, however `name` can be used to provide the same functionality. Having said that, the [documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Metric) describes `expression` as being "a mathematical expression for derived metrics" so maybe we should simply use `name` and not `expression` when retrieving our reports as we don't have any current requirement for metrics derived from mathematical expressions.
  - The `name` field is required. If `expression` is provided, `name` works as an alias. Otherwise `name` must be a valid metric name.
- `orderby`:
  - `fieldName` should refer to `name`, not `expression`.

To illustrate, here's an example of the relevant GA4 report params with the equivalent for UA. For a real-world example of how these could apply see [here](https://github.com/google/site-kit-wp/blob/afc11b01efdd5c28e34a56c146f5f0a1bdd2a42f/assets/js/components/wp-dashboard/WPDashboardPopularPages.js#L60-L76).

<details>
<summary>GA4 params</summary>

```json
{
	propertyID: '123456789',
	metrics: [
		{
			expression: 'screenPageViews',
			name: 'Pageviews',
		},
	],
	orderby: [
		{
			fieldName: 'Pageviews',
			sortOrder: 'DESCENDING',
		},
	],
};
```

</details>

<details>
<summary>GA4 params without expression</summary>

```json
{
	propertyID: '123456789',
	metrics: [
		{
			name: 'screenPageViews',
		},
	],
	orderby: [
		{
			fieldName: 'screenPageViews',
			sortOrder: 'DESCENDING',
		},
	],
};
```

</details>

<details>
<summary>UA params</summary>

```json
{
	metrics: [
		{
			expression: 'ga:pageviews',
			alias: 'Pageviews',
		},
	],
	orderby: [
		{
			// Note that `fieldName` can refer to the value in `expression`, this is not allowed in GA4:
			fieldName: 'ga:pageviews',
			sortOrder: 'DESCENDING',
		},
	],
};
```

</details>

## Multi-date range responses

The response schema is entirely new, so the whole thing needs to be re-evaluated in use. However there's one aspect I thought worth calling out as it's not so readily obvious from reading the docs.

When using multiple date ranges, it changes the structure of the response in a different way to the UA version:

- The `rows` property will have additional rows for each date range, rather than each row having additional entries per date range.
- Note that aggregate properties (`minimum`, `maximum` and `totals`) will still have an entry per date range although the format of the entries has changed a bit.

To illustrate, here's an example GA4 report with the equivalent for UA:

<details>
<summary>GA4 request</summary>

```json
{
  "requests": [
    {
      "dateRanges": [
        {
          "endDate": "2022-11-04",
          "startDate": "2022-11-02"
        },
        {
          "endDate": "2022-11-02",
          "startDate": "2022-11-01"
        }
      ],
      "dimensionFilter": {
        "andGroup": {
          "expressions": [
            {
              "filter": {
                "fieldName": "hostName",
                "inListFilter": {
                  "values": ["example.com", "www.example.com"]
                }
              }
            },
            {
              "filter": {
                "fieldName": "sessionDefaultChannelGrouping",
                "stringFilter": {
                  "matchType": "EXACT",
                  "value": "Organic Search"
                }
              }
            }
          ]
        }
      },
      "dimensions": [
        {
          "name": "date"
        }
      ],
      "keepEmptyRows": true,
      "metricAggregations": ["TOTAL", "MINIMUM", "MAXIMUM"],
      "metrics": [
        {
          "name": "totalUsers"
        }
      ],
      "property": "properties/285794360"
    }
  ]
}
```

</details>

<details>
<summary>GA4 response</summary>

```json
{
  "kind": "analyticsData#batchRunReports",
  "reports": [
    {
      "dimensionHeaders": [
        {
          "name": "date"
        },
        {
          "name": "dateRange"
        }
      ],
      "kind": "analyticsData#runReport",
      "maximums": [
        {
          "dimensionValues": [
            {
              "value": "RESERVED_MAX"
            },
            {
              "value": "date_range_0"
            }
          ],
          "metricValues": [
            {
              "value": "51"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "RESERVED_MAX"
            },
            {
              "value": "date_range_1"
            }
          ],
          "metricValues": [
            {
              "value": "51"
            }
          ]
        }
      ],
      "metadata": {
        "currencyCode": "USD",
        "timeZone": "America/Los_Angeles"
      },
      "metricHeaders": [
        {
          "name": "totalUsers",
          "type": "TYPE_INTEGER"
        }
      ],
      "minimums": [
        {
          "dimensionValues": [
            {
              "value": "RESERVED_MIN"
            },
            {
              "value": "date_range_0"
            }
          ],
          "metricValues": [
            {
              "value": "4"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "RESERVED_MIN"
            },
            {
              "value": "date_range_1"
            }
          ],
          "metricValues": [
            {
              "value": "42"
            }
          ]
        }
      ],
      "rowCount": 3,
      "rows": [
        {
          "dimensionValues": [
            {
              "value": "20221102"
            },
            {
              "value": "date_range_0"
            }
          ],
          "metricValues": [
            {
              "value": "51"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "20221102"
            },
            {
              "value": "date_range_1"
            }
          ],
          "metricValues": [
            {
              "value": "51"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "20221101"
            },
            {
              "value": "date_range_1"
            }
          ],
          "metricValues": [
            {
              "value": "42"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "20221103"
            },
            {
              "value": "date_range_0"
            }
          ],
          "metricValues": [
            {
              "value": "4"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "20221101"
            },
            {
              "value": "date_range_0"
            }
          ],
          "metricValues": [
            {
              "value": "0"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "20221103"
            },
            {
              "value": "date_range_1"
            }
          ],
          "metricValues": [
            {
              "value": "0"
            }
          ]
        }
      ],
      "totals": [
        {
          "dimensionValues": [
            {
              "value": "RESERVED_TOTAL"
            },
            {
              "value": "date_range_0"
            }
          ],
          "metricValues": [
            {
              "value": "54"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "RESERVED_TOTAL"
            },
            {
              "value": "date_range_1"
            }
          ],
          "metricValues": [
            {
              "value": "93"
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

<details>
<summary>UA request</summary>

```json
{
  "reportRequests": [
    {
      "dateRanges": [
        {
          "endDate": "2022-11-04",
          "startDate": "2022-11-02"
        },
        {
          "endDate": "2022-11-02",
          "startDate": "2022-11-01"
        }
      ],
      "dimensionFilterClauses": [
        {
          "filters": [
            {
              "dimensionName": "ga:hostname",
              "expressions": ["example.com", "www.example.com"],
              "operator": "IN_LIST"
            }
          ]
        },
        {
          "filters": [
            {
              "dimensionName": "ga:channelGrouping",
              "expressions": ["Organic Search"],
              "operator": "EXACT"
            }
          ],
          "operator": "AND"
        }
      ],
      "dimensions": [
        {
          "name": "ga:date"
        }
      ],
      "includeEmptyRows": true,
      "metrics": [
        {
          "alias": "Total Users",
          "expression": "ga:users"
        }
      ],
      "viewId": "204803300"
    }
  ]
}
```

</details>

<details>
<summary>UA response</summary>

```json
{
  "reports": [
    {
      "columnHeader": {
        "dimensions": ["ga:date"],
        "metricHeader": {
          "metricHeaderEntries": [
            {
              "name": "Total Users",
              "type": "INTEGER"
            }
          ]
        }
      },
      "data": {
        "isDataGolden": true,
        "maximums": [
          {
            "values": ["114"]
          },
          {
            "values": ["123"]
          }
        ],
        "minimums": [
          {
            "values": ["0"]
          },
          {
            "values": ["0"]
          }
        ],
        "rowCount": 4,
        "rows": [
          {
            "dimensions": ["20221101"],
            "metrics": [
              {
                "values": ["0"]
              },
              {
                "values": ["123"]
              }
            ]
          },
          {
            "dimensions": ["20221102"],
            "metrics": [
              {
                "values": ["114"]
              },
              {
                "values": ["114"]
              }
            ]
          },
          {
            "dimensions": ["20221103"],
            "metrics": [
              {
                "values": ["27"]
              },
              {
                "values": ["0"]
              }
            ]
          },
          {
            "dimensions": ["20221104"],
            "metrics": [
              {
                "values": ["11"]
              },
              {
                "values": ["0"]
              }
            ]
          }
        ],
        "totals": [
          {
            "values": ["152"]
          },
          {
            "values": ["237"]
          }
        ]
      }
    }
  ]
}
```

</details>

**Comment by aaemnnosttv** [comment]
Thanks @techanvil for the thorough report! A few thoughts

You mention `batchRunReports` in your link there but I think we only need the `runReport` request here. For UA, the API _only supports_ `batchGet` for reports but we only ever request a single report (only sometimes with multiple date ranges). So with UA we were forced to make a batch request whereas that no longer seems to be the case with GA4.

I see you called out the difference in structure with GA4 when using multiple date ranges, I assume that probably still applies when calling `runReport` rather than the batch variant. I don't think that presents any problems for us, but does mean we'll need to rework the way we handle reports that use multiple ranges.

> `propertyID`:
> * `propertyID` is a new required parameter (see [docs](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/batchRunReports)). In our usage this should be the currently active GA4 property ID and may be best populated in `getReport` rather than on a per-report basis.

We should preserve the current scope in keeping the property ID applied on the server side, at least for now. One very practical reason being that in a view-only context, users don't have access to module settings (including the property ID) so it wouldn't work in that case. Historically speaking, module datapoints have always been scoped in this way that they can only request data for the connected entity. Your suggestion implies that we'd be opening up the client to be able to request reports for a property ID other than the one connected which is something we'd want to consider a quite carefully before doing, especially in the case of DS.

Taking a look at the PR now 👍

**Comment by techanvil** [comment]
Hi @aaemnnosttv, thanks for raising these points.

Regarding `batchRunReports`, I had considered using `runReport` but the IB was quite specific about using `batchRunReports`, and I figured that would be appropriate in terms of keeping the response shape more aligned with the existing UA response. That said, I also feel `runReport` would be a more correct implementation so, as you've given the go-ahead, I'm happy to use that instead and have gone ahead and made the change.

Regarding `propertyID` - thanks for pointing that out! I should have realised that myself, in 20/20 hindsight. Anyhow, I have made that change too.

**Comment by asvinb** [comment]
@techanvil Just FYI, I was able to reproduce the same issue on another site.

**Comment by techanvil** [comment]
@asvinb thanks for raising this, I hadn't spotted this during testing but it turns out `pagePathPlusQueryString` which we use for filtering by `url` is not compatible with `sessionDefaultChannelGroup`. I've raised this with @marrrmarrr on Slack and tagged you on the post.

Regarding the QAB, I had initially just pasted the `reportParams` without `url` and `limit`, and then added those two just for the sake of illustrating the various available parameters, without testing the resulting query. I am glad you tested as-is because it caught this issue!

**Comment by techanvil** [comment]
Hi @asvinb, further on the above, I've created a followup PR to change from `pagePathPlusQueryString` to `pagePath` which will resolve this compatibility issue.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb – this is ready for another pass 👍

**Comment by asvinb** [comment]
### QA ⚠️ 
Hey @techanvil , I just checked again and this time there does not seem any data coming from the API. Request and response are below:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/31818/213400933-6cacfc51-14e3-4afa-87ed-7479ecb6081f.png">

I checked within Google Analytics and there is data for this period and I also checked via the API explorer. 

<details>
<summary>Response from API explorer</summary>

```js
{
  "dimensionHeaders": [
    {
      "name": "date"
    }
  ],
  "metricHeaders": [
    {
      "name": "newUsers",
      "type": "TYPE_INTEGER"
    }
  ],
  "rows": [
    {
      "dimensionValues": [
        {
          "value": "20221228"
        }
      ],
      "metricValues": [
        {
          "value": "3"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221206"
        }
      ],
      "metricValues": [
        {
          "value": "2"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221221"
        }
      ],
      "metricValues": [
        {
          "value": "2"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221226"
        }
      ],
      "metricValues": [
        {
          "value": "2"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230102"
        }
      ],
      "metricValues": [
        {
          "value": "2"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230104"
        }
      ],
      "metricValues": [
        {
          "value": "2"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221204"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221207"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221212"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221215"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221218"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221222"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20221227"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230105"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230106"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230109"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230110"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230116"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "20230117"
        }
      ],
      "metricValues": [
        {
          "value": "1"
        }
      ]
    }
  ],
  "rowCount": 19,
  "metadata": {
    "currencyCode": "USD",
    "timeZone": "Etc/UTC"
  },
  "kind": "analyticsData#runReport"
}
```
</details>

**Comment by techanvil** [comment]
Hi @asvinb, I have an idea what's happening here, and it's my fault for not updating the QAB example, when making the change during the review process.

We no longer need to pass in `propertyID` as a report parameter to our API call, as it's populated in the backend from the currently connected GA4 property. So, I have a feeling you may have a different connected GA4 property to the one you're passing in and testing in the explorer. Please take a look and see if your connected GA4 property is different and try using _that_ property in the explorer if so.

I've also updated the QAB example, sorry for any inconvenience caused.

**Comment by asvinb** [comment]
Thanks @techanvil , I'll check it out again! 😁

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Ran through some tests within Dashboard Sharing and Site Kit settings to ensure there's no reference to Analytics 4.  

![image](https://user-images.githubusercontent.com/73545194/214266141-986c6c66-014b-4030-b43e-1df577c5826f.png)

**Comment by asvinb** [comment]
### QA: ✔️ 

* Followed QAB and used different metrics and dimensions ✅
