### ISSUE TITLE
Fix the VRT tests that are failing in CI.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6185]
## Feature Description

Following up from #6151, there will be quite a few VRT tests failing in CI.

- Most of them are failing correctly and simply need to have their reference image updated.
- Two tests have been identified as needing work to fix the related Storybook stories:
  - **WPDashboardWidgets > Ready with Activate Analytics CTA**
  - **SearchConsole > Ready with Activate Analytics CTA**.
  - It appears that some sibling stories to the above also need attention although they do not have VRT scenarios.

We should apply an appropriate fix to all of these failing tests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- All of the VRT tests which are failing correctly in CI should have their reference images updated.
- The VRT tests which need Storybook work to fix should be fixed and any related stories that may be broken should also be fixed. These tests are:
  - **WPDashboardWidgets > Ready with Activate Analytics CTA** - this has a VRT scenario
  - **WPDashboardWidgets > Ready with Activate Module CTA**
  - **WPDashboardWidgets > Ready with Complete Analytics Activation CTA**
  - **SearchConsole > Ready with Activate Analytics CTA**  - this has a VRT scenario
  - **SearchConsole > Ready with Complete Analytics Activation CTA**
- All of the tests should pass in CI. Discrepancies between CI and local test runs can be addressed separately via #5824

## Implementation Brief

Due to stability problems running the suite locally, we can fix the test suite using reference images from a CI run before moving on to address the local run issues in #5824.

* Download the report from a CI run of the VRT workflow.
* Check through the test failures.
* For the tests which are failing correctly, copy the reference images from the report into `tests/backstop/reference/`.
* Fix those tests which need Storybook work.
  * Refer to the AC for the list of stories. Confirm these are valid at the time of implementation.
  * Apply fixes and either run locally to generate the new reference images, or if necessary push to CI and download/update reference images via the report as above.
* Remove the code that allows overriding `misMatchThreshold` configuration for individual scenarios, as this is no longer needed and is currently the cause of some false positives (see [below](https://github.com/google/site-kit-wp/issues/6185#issuecomment-1332440617) for more info).
  * Ensure the related Progress Bar reference images are correctly updated along with the others.

### Test Coverage

* No new tests needed.

## QA Brief

**QA:Eng**

- Create a sample PR and ensure the VRT passes in the CI.
- Alternatively, if you have an existing PR, pull the latest `develop` and push it and ensure the VRT is passing in the CI.
- Ensure there shouldn't any failures.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
ACs and IB look good, but the IB here needs an estimate so assigned to @techanvil to assign one.

After that feel free to move right to the Execution Backlog, as otherwise this is IB ✅ from me 🙂

**Comment by techanvil** [comment]
Thanks @tofumatt! Have added an estimate of 7, moving on over to the EB :+1:

**Comment by aaemnnosttv** [comment]
@techanvil I just noticed this in a [failing VRT run](https://github.com/google/site-kit-wp/actions/runs/3572172055/jobs/6004761010#step:5:4412) (where most are still failing) but in this situation there seem to be tests which _should have failed_ that passed.

E.g. 
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/1621608/204644006-10fe0cff-7664-47ce-b00c-ed338e00f147.png">

Any idea how this could happen?

**Comment by aaemnnosttv** [comment]
I've pulled this forward into this sprint – let's try to resolve this ahead of the release if possible.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, good shout. I have updated the IB accordingly.

**Comment by aaemnnosttv** [comment]
Great, thanks @techanvil 👍 

IB ✅

**Comment by asvinb** [comment]
### QA: ✔️ 
Checked a recent PR and the VRT action is no longer failing:
![image](https://user-images.githubusercontent.com/31818/207323272-0f1b1158-b6a1-40a3-80b0-8434b9405bed.png)

**Comment by aaemnnosttv** [comment]
This is mostly good to go although there are still some tests failing since this was merged.

These will be fixed in https://github.com/google/site-kit-wp/issues/6324.
