### ISSUE TITLE
Update GitHub actions using deprecated runtimes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6188]
## Feature Description

Similar to #6104, this issue is for upgrading actions that are using deprecated runtimes.

Example notice from a recent run:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2
```

As noted above, the warning implicates `actions/checkout@v2` and `actions/cache@v2` which are used across many workflows although there could be others. Workflow run logs should be reviewed for each to see if there are any other actions that are using deprecated runtimes.

Also note that #6104 already calls for upgrading `actions/cache@v2`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All GitHub action workflows should be audited for workflows using deprecated runtimes (this is surfaced in workflow runs as an annotation)
* All actions using deprecated runtimes should be upgraded to a version that is free of deprecations 
    * In the absence of an upgrade that satisfies this criteria, steps should be outlined for each instance to be upgraded or replaced in the future and the relevant deadline that this must happen by

## Implementation Brief

Given this required auditing all of our actions anyway, it seemed a good opportunity to look through any actions we're using that _could_ be upgraded and upgrading them if possible—also pointing out any blockers to upgrading them.

(From my investigation it looks like only `actions/checkout` and possibly `actions/upload-artifact@v1` is using a deprecated runtime.)

* Update all instances of these actions to the new versions:
  * `actions/checkout@v2` to `actions/checkout@v3`
  * `c2corg/browserslist-update-action@v1` to `c2corg/browserslist-update-action@v2`
  * `preactjs/compressed-size-action@v1` to `preactjs/compressed-size-action@v2`
  * `actions/upload-artifact@v1`/`actions/upload-artifact@v2` to `actions/upload-artifact@v3`
  * `actions/download-artifact@v1`/`actions/download-artifact@v2` to `actions/download-artifact@v3`

Many of these updated actions use Node 16, but using a newer version of Node (node `16`) is already an issue (#6026). @aaemnnosttv pointed out it shouldn't need to be upgraded for our code, but if the actions run into issues with Node versions this issue might depend on #6026. For now they can be treated as separate issues.

### Test Coverage

* No new tests needed; existing CI tests should pass.

## QA Brief

* All GH actions should work normally after the upgrades. Verify all CI actions pass.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
> * Update our version of Node to 16 so we can update all of our GitHub Actions to use a newer version of Node (see [Update Node.js version #6026](https://github.com/google/site-kit-wp/issues/6026)).

@tofumatt I don't think #6026 is related to this issue because the version of Node we use (via `actions/setup-node`) is different than the GHA runtime which this is fixing. Unless this is specifically coupled in some way, we shouldn't require/implement #6026 as part of this issue.

**Comment by tofumatt** [comment]
@aaemnnosttv Fair enough—I was a bit concerned that any actions that used Node to then build our code or run our things might experience issues on Node 16 if our package wasn't set up to run with it, but I guess if that does come up we can evaluate. For now I've excluded that bit from the IB.

**Comment by asvinb** [comment]
### QA: ✔️ 

Checked a r[ecent PR](https://github.com/google/site-kit-wp/pull/6381) and GH actions are running fine (Except the usual VRT failure)
![image](https://user-images.githubusercontent.com/31818/211046552-861f63a7-5a3c-4048-828a-ddd610b6b228.png)
