### ISSUE TITLE
Escalation board check | Sprint 89

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#6195]
We are using this ticket as a reminder to check the escalation board within sprint 89. A new ticket will be created for each sprint and closed at the end of each sprint. 

If you are going to check the escalation board, please assign yourself to this ticket, it is encouraged to have multiple assignees / people checking the escalation board.

Please log any time for escalation under escalation and through the ticket on the escalation board and **not this ticket**.

Thanks all!

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
Update for this ticket: I spent most of the time checking out #5852 which seems to be reproducible by many users with a potential fix. I'm still exploring that and I think I'll move it to the Execution board soon. Not much else to report from this triage session.
