### ISSUE TITLE
Analytics Data Displaying the Incorrect Property

### ISSUE THREAD

**Issue by onuro** [google/site-kit-wp#62]
**Describe the bug**
I have 2 properties on an account. I have chosen the second property, however SiteKit Analytics insists on displaying the data for the first property.

**To Reproduce**
1. Go to Settings
2. Connect Analytics with an account you have at least 2 properties on
3. Select an account that's not the first

**Expected behavior**
It should be showing the accurate property

**System Information (please complete the following information):**
 - PHP Version: 7.3
 - OS: Mac OS High Sierra
 - Browser Chrome 75
 - Plugin Version beta 1
 - Device: Desktop Mac

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by jamesozzie** [comment]
Hi @onuro. Can you try and disconnected Sit Kit completely again (Settings > Admin Settings > Reset Site Kit). Then start the process again and if the same issue arises please confirm that the incorrect property ID, the one you didn't select upon setup also appears under Settings > Connected Services > Analytics. We'll have to look further into this and may also ask you to grab the process flow in a gif or video also.

**Comment by jamesozzie** [comment]
@onuro Were you able to recreate the issue? Check also the header.php file of your active theme, or for any other possible implementation methods for Analytics (Theme options, analytics plugin etc).

**Comment by onuro** [comment]
@jamesozzie clearing cache and then disconnecting and re-authenticating resolved the issue.

Thanks!
