### ISSUE TITLE
Revise wording on the "Reset sharing permissions" popup

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6200]
## Bug Description

When resetting Dashboard sharing options there is a popup to confirm a user wishes to reset. Within this form there is a description that mentions that the "_Who can view_" configurations will be reset. It doesn't however mention that the "_Who can manage view access_" configurations will also be reset. 

Consider rewording this description to mention that all configurations will be reset. 

```diff
-Warning: Resetting these permissions will remove view-only access for all users. Are you sure you want to reset all Dashboard Sharing permissions?
+Warning: Resetting these permissions will remove view-only access for all users and reset manage view access configurations. Are you sure you want to reset all Dashboard Sharing permissions?
```
 

![image](https://user-images.githubusercontent.com/41326532/203969088-9c024d96-64a4-4fc9-986c-9a0af1de90a0.png)

## Steps to reproduce

1. Apply "Who can view" and "Who can manage view access" configurations
2. Press the "Reset sharing permissions" link
3. You'll notice that there is only a mention of the "Who can view" settings being reset, and not the "Who can manage view access" settings

You'll see from the recording below that both settings are reset, along with the text that appears

https://user-images.githubusercontent.com/41326532/203968220-2ea26618-f3b1-4a1a-9426-d30cadaeed2e.mp4

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The warning shown before resetting sharing settings should be updated to the following:
> Warning: Resetting these permissions will remove view-only access for all enabled roles as well as any manage view access configurations. Are you sure you want to reset all dashboard sharing permissions?

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@marrrmarrr does the proposed language in the AC read okay to you?

**Comment by aaemnnosttv** [comment]
It's worth noting here that the proposed variant only makes sense in a multi-admin context, otherwise the "who can manage access" settings are not present. We could update the language here conditionally if we wanted, which would probably be a good idea.

**Comment by ivonac4** [comment]
@marrrmarrr  Are you still planning to review this soon? If not, can you please unassign yourself so someone else can pick up? Thank you!

**Comment by ivonac4** [comment]
@marrrmarrr Sorry, I misread the comments here, I realize now it is on you to review it. Do you mind taking a look at it when you have time? Thanks!

**Comment by aaemnnosttv** [comment]
@sigal-teller do you think it's better to be explicit about what will be reset as proposed here or would it be perhaps more clear to say something along the lines of "resetting all sharing settings back to their unshared defaults"? I feel like the latter might be easier to understand.

**Comment by aaemnnosttv** [comment]
Closing for now. We can revisit later if needed.
