### ISSUE TITLE
Replace module store string interpolation with getModuleStoreName selector.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6202]
## Feature Description

We have a case where we're using an inlined interpolated string for a module store name, where we should be using the `getModuleStoreName()` selector.

https://github.com/google/site-kit-wp/blob/0613c22dca7a4486ad40845188a1226be4f7a1dd/assets/js/components/settings/SettingsActiveModule/Footer.js#L102

We should update this to use `getModuleStoreName()`.

Note, this was spotted via https://github.com/google/site-kit-wp/issues/6192.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* This, and indeed all cases where we determine a module store name at runtime should use `getModuleStoreName()` where possible.

## Implementation Brief

* Replace the following interpolated string with the result of a call to `getModuleStoreName()`.

https://github.com/google/site-kit-wp/blob/0613c22dca7a4486ad40845188a1226be4f7a1dd/assets/js/components/settings/SettingsActiveModule/Footer.js#L102

### Test Coverage

* No new tests needed.

## QA Brief

* Go to the settings page and edit any module settings.
* Open your browser dev tools and select the `Offline` mode in the throttling settings on the Network tab.
* Now save module settings and ensure that you see an error that says that you are offline.
* Then update the throttling settings to not throttle at all and save your module settings again. 
* Ensure that when you click on the save settings button, the previous error disappears.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs are good 👍🏻 IB as well. 🙂 

IB ✅

**Comment by techanvil** [comment]
Hey @eugene-manuilov, I am sending this back again because although I did a smoke check on the footer to make sure it still looks OK, I realise I've not actually confirmed that errors are still cleared. This makes me realise this issue should really have a QAB for a regression test to make sure it still works as expected. Would you mind adding one?

**Comment by eugene-manuilov** [comment]
Yeah, no problem, QAB is added, @techanvil.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.

- @eugene-manuilov When I edited settings for Tag manager and set selected the offline mode under network tab then error message appearing with "Retry" button. Updating the settings to not throttle at all and clicking on 'Retry' button not making triggering any process.  Under other module settings this retry button is not showing. Can we remove this 'retry' button if there is no use of this ? or it will work in any other scenario ?

<details>


https://github.com/google/site-kit-wp/assets/94359491/989b08a8-034c-40c5-8a19-b53572726900

</details>

**Comment by eugene-manuilov** [comment]
@mohitwp that is weird... I am not sure what that retry button does, but that is definitely out of scope for this ticket. Can you create a new ticket for it?

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @eugene-manuilov !

- Tested on dev environment.
- Verified that error message appears under all module settings.
- For the issue related to Tag manger module settings reported [above](https://github.com/google/site-kit-wp/issues/6202#issuecomment-1567999797). I created a new ticket #7110 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/075fcb13-2cc1-44be-a5b9-716337048cd8)

![image](https://github.com/google/site-kit-wp/assets/94359491/4514343c-91fd-4fa0-92b4-6b4fe620a500)

</details>
