### ISSUE TITLE
Scaffold Key metrics Setup CTA on Main Dashboard

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6209]
## Feature Description

To create the Key metrics “Widget” with multiple “metric widgets” inside of it, we will treat the entire widget as a new “widget area” assigned to a new “widget context”. Each metric within can then be treated as an individual `widget`. This way we can reuse the existing `core/widgets` datastore, its wrapping `Widgets` API and its associated functionality.

We can register a simple full-width widget component, which will act as a placeholder for the Key Metrics Setup CTA component. This component will be similar in purpose and behaviour to the `<ConnectAdSenseCTAWidget>` component.

Refer to the [relevant section](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit?pli=1#heading=h.uf8oyh8wk1lx) in the design doc for further context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new “widget context” (`CONTEXT_MAIN_DASHBOARD_KEY_METRICS` = `mainDashboardKeyMetrics`) and a new “widget area” (`AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY` = `mainDashboardKeyMetricsPrimary`) should be created.
  * The title of the new widget area (registered as a default within `register-defaults.js`) should be _Key metrics_.
  * The subtitle of the widget area should be: _Track progress towards your goals with tailored metrics_ 
* The new widget context should **only** be rendered at the top of the Main Dashboard. No "Key Metrics" widget context/area should be registered or rendered on the Entity dashboard.
* A new chip should be added to the existing navigation chips and should be selected by default. We need to consider the impact this may have on our in-view select use as it is [partly controlled by the currently selected chip/section](https://github.com/google/site-kit-wp/blob/0d79bcb3dc4fe9406558536b3425dcd7c1ab3bd8/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L118-L119). The result here would be the key metrics being active by default and traffic below it in a loading state. ~~We should treat key metrics separately in that it doesn't affect the `activeContextID`, and doesn't use in-view select.~~ (This is being fixed in #6475).
* A placeholder widget component with dummy text should be registered within `register-defaults.js`. This component will eventually be designed into the Setup CTA component in #6210. It should be rendered only if:
    * The Analytics (`analytics`) module and GA4 (`analytics-4`) are both connected.
    * ~~Search Console and GA4 are not in “Gathering Data”~~ (see [comment](https://github.com/google/site-kit-wp/issues/6209#issuecomment-1435324927)) ~~nor in “Zero Data”~~ states.
    * The logged in user is an authenticated admin.

## Implementation Brief

* In `widgets/default-contexts.js`, add and export the new widget context from the AC.
* In `widgets/default-area.js`, add and export the new widget area from the AC.
* In `widgets/register-defaults.js`, use the `registerWidgetArea()` method to register the area defined above passing the context defined above. The title and subtitle should be as per the AC. Set the `style` to `WIDGET_AREA_STYLES.BOXES` and `priority` to 1.
* In `DashboardMainApp.js`, check if the new `CONTEXT_MAIN_DASHBOARD_KEY_METRICS` context is active similar to the other widget context checks. If it is, then render another `<WidgetContextRenderer>` component passing it a new id (`ANCHOR_ID_KEY_METRICS`) and the newly created context as the `slug`. No `className` should be required at this point.
* In `Navigation.js`, check if the new `CONTEXT_MAIN_DASHBOARD_KEY_METRICS` context is active similar to the other widget context checks. If it is, render a new `<Chip>` as per the [Figma Mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1292%3A34229&t=EuhNKy1WvGCAeTXZ-0).  The current loading of `inView` widgets has a bug which will be fixed in #6475.
* In `assets/js/components/` create a new folder, `KeyMetrics` and a new file within it, `KeyMetricsSetupCTAWidget.js`. Within this file:
    * Export a new functional React component `KeyMetricsSetupCTAWidget` which renders some simple placeholder text.
    * It should render `WidgetNull` if:
        * Either `analytics` or `analytics-4` are not connected (use the `isModuleConnected()` selector from the `core/modules` store).
        * Any one of `search-console`, `analytics` or `analytics-4` is in a gathering data state. Use the `isGatheringData()` selector from each of the respective modules stores.
        * The current dashboard is view only. (Use the `useViewOnly()` hook.)
* In `widgets/register-defaults.js`, use the `registerWidget()`  method from the Widgets API to register the `KeyMetricsSetupCTAWidget` widget as follows:
    ```javascript 
    widgets.registerWidget(
      'keyMetricsSetupCTA',
      {
        Component: KeyMetricsSetupCTAWidget,
        width: [ widgets.WIDGET_WIDTHS.FULL ],
        priority: 1,
        wrapWidget: false,
        modules: [ 'search-console' ],
      },
      [ AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY ]
    );
    ```
* Add a Storybook story which renders the `KeyMetricsSetupCTAWidget` component with its dummy text for now. In #6210, this component will be implemented further. Create a corresponding VRT scenario for this story.

### Test Coverage

* Add tests for the `KeyMetricsSetupCTAWidget` component similar to `AdBlockerWarning.test.js` which tests that it is rendered when the correct conditions in the ACs are met.

## QA Brief

* Verify there are no regressions on the dashboard with the User Input feature switched off. Test with Analytics and GA4 connected.
* With the User Input feature turned on, verify a placeholder component is rendered as shown in the below screenshot.

<img width="3005" alt="Screenshot 2023-03-07 at 14 20 46" src="https://user-images.githubusercontent.com/1721319/223449535-67eb19e3-2d2f-44f9-b07a-d8907ef5fa43.png">

*  NOTE 1: Additional placeholder widgets are rendered at this time but these will eventually be hidden when the Key Metrics are still not defined. This is part of the ACs of the individual KM widget tile issues.
* NOTE 2: The old User Input "Banner Notification" is still being rendered in addition to the new Widget Area. This should be removed in #6210 when we design a similar banner within the new Setup CTA for which we have already created a placeholder.

## Changelog entry

* Scaffold Key Metrics CTA widget area on Site Kit Dashboard.

**Comment by tofumatt** [comment]
> The subtitle of the widget area should be: _______ (Mariya to confirm)

I think this needs to be finalised before we move this to IB. @marrrmarrr: can you confirm the wording here (or @jimmymadon: can you check with @marrrmarrr on Slack about this?)

> We should treat key metrics separately in that it doesn't affect the `activeContextID`, and doesn't use in-view select.

Sorry, I don't quite follow this—do you mean nothing inside the "Key Metrics" widgets should use `useInViewSelect`? If so, why not?

> The logged in user is an authenticated admin.

Would this include an authenticated admin who only has access to the Dashboard via Dashboard Sharing? Also, it doesn't look like these are the only conditions to show the Key Metrics widget context/area in the [design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit?pli=1#heading=h.o4lll9gj1sav). There it mentions:

> If Dashboard Sharing is enabled, the widget should be rendered for non-authenticated users on the view-only dashboard if the following conditions* are met, otherwise the widget should be hidden:
> 1. User Input Questionnaire has been completed by at least one authenticated admin on the site. This means the Key Metrics widget is [automatically selecting](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit?pli=1#heading=h.zc9k0id36g3e) 4 metrics to show. If any admin user of the site has picked their own metrics, they themselves will see their selected metrics while the rest of the site’s users will see metrics based on the [“Neutral / Catch all” segment mapped above](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit?pli=1#heading=h.zc9k0id36g3e).
> 2. At least two of the above 4 metrics are from modules which are shared with the user.

**Comment by jimmymadon** [comment]
@tofumatt Thanks for the helpful reviews as always. Yup - Mariya will get back to me on the wording of that title and other wordings too. 

As for the `inViewSelect`, this section in the design doc explains avoiding the widgets below to be in loading state even if they are in view:

>"A new chip will be added to the existing navigation chips and should be selected by default. We need to consider the impact this may have on our in-view select use as it is [partly controlled by the currently selected chip/section](https://github.com/google/site-kit-wp/blob/0d79bcb3dc4fe9406558536b3425dcd7c1ab3bd8/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L118-L119). The result here would be the key metrics being active by default and traffic below it in a loading state. We should treat key metrics separately in that it doesn't affect the `activeContextID`, and doesn't use in-view select."

As for the DS conditions: The Key Metrics Setup CTA (the one which asks the user to "Tailor their metrics") being scaffolded in this issue will not be rendered for non-authenticated admins. The actual Key Metrics parent component, which will be designed in [another issue](https://github.com/google/site-kit-wp/issues/6242), with the metric tiles within it, will be displayed for them directly based on the conditions you've highlighted.

**Comment by jimmymadon** [comment]
Since this issue is blocking a few others, we could move this and start the IB for it and perhaps modify or update the subtitle later? We can use a generic subtitle from the Figma mock for now. 

@marrrmarrr if you can get to this before next sprint (which is the earliest this will be "executed"), that would be great!

**Comment by jimmymadon** [comment]
@tofumatt After our discussion yesterday, I forgot again that this issue is only creating a dummy of the banner component. The banner itself will not be visible to non-authenticated admins when Dashboard Sharing is enabled. So I think the ACs here seem to be complete for now.

**Comment by marrrmarrr** [comment]
@jimmymadon this subtitle SGTM, I'll ask Sigal as well to update across all screens in Figma.

**Comment by tofumatt** [comment]
ACs are good here 👍🏻 

Moved to IB.

**Comment by techanvil** [comment]
Hey @jimmymadon, this IB is looking good. A few points/questions:

- I don't see a mention of the `useIntersection` hook problem that we spotted, but I think we should address this either as part of this issue or as a dependency in order to avoid introducing a regression in the Dashboard lazy loading.
- It might be worth mentioning adding a VRT scenario for the new story, even though it will just be in a placeholder state, which can then be updated as the widget is developed. Alternatively, we should specify it in a subsequent issue.
- Is the estimate here bumped up by one, i.e. should it have the `Exp: SP` label set?

**Comment by techanvil** [comment]
Thanks @jimmymadon!

Looks good, but I think we should be a little more specific about the new hook. I think it's safe to say "We should create" rather than "We should consider creating" the hook. I'd also suggest specifying the name for the new hook - how about `useLatestIntersection`?

We should also be clear about where the new hook needs to be used i.e. in `WidgetAreaRenderer`.

It will also need tests, and while we can take some inspiration from the `react-use` [tests for `useIntersection`](https://github.com/streamich/react-use/blob/v15.3.4/tests/useIntersection.test.tsx), there are some potential complications (note the use of the mock `intersectionObserver` from `@shopify/jest-dom-mocks`) and it might mean the original estimate would be bumped from 15 to 19, therefore this would go to a 30. Or alternatively it could suggest that the new hook would be better to tackle as a dependency... What do you think?

**Comment by techanvil** [comment]
Nice one @jimmymadon!

IB :white_check_mark:

**Comment by mohitwp** [comment]
@jimmymadon I'm not able to found screenshot mentioned under QAB. Looks like it is not uploaded. Can you please check and add it again ?

Thank you !

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified-**

- Tested on main.

- Tested main and entity dashboard when `userinput` feature flag is not enabled.

- Tested main and entity dashboard when `userinput` feature flag is enabled.

- A new “widget context” and a new “widget area” is creared created.

- The title of the new widget area is  Key metrics.

- The subtitle of the widget area is : Track progress towards your goals with tailored metrics

- The new widget context redndering at the top of the Main Dashboard only. No "Key Metrics" widget context/area shois registered or rendered on the Entity dashboard.

- A new chip  added to the existing navigation chips and  selected by default. 

- A placeholder 'KeyMetricesSetupCTAWidget' appears only if analytics and GA4 is connected.

<details>

Analytics is not connected
![image](https://user-images.githubusercontent.com/94359491/223674399-a3d760c1-b843-449f-9445-f6af8e9352ce.png)

![image](https://user-images.githubusercontent.com/94359491/223675027-d5d6787a-ff78-40bc-89bb-37522b02d532.png)

![image](https://user-images.githubusercontent.com/94359491/223675582-4ece29e5-20f3-4518-bd28-9f40a919e9c7.png)

![image](https://user-images.githubusercontent.com/94359491/223678396-8d3162c5-5809-4423-9072-1bd6a3431c51.png)

![image](https://user-images.githubusercontent.com/94359491/223678634-b3cbf138-4833-44b8-98b3-181fa8c28152.png)

</details>
