### ISSUE TITLE
Create GA4 `WPDashboardSessionDuration`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6213]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `WPDashboardSessionDurationGA4` should be created based on the existing `WPDashboardSessionDuration`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief
* Once #6173 and #6174 have been merged.
* Copy `assets/js/components/wp-dashboard/WPDashboardSessionDuration.js` to `assets/js/components/wp-dashboard/WPDashboardSessionDurationGA4.js` with the following updates:
    * The `WPDashboardSessionDurationGA4` component should be exported.
    * Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`).
    * Replace the metrics and dimensions by their GA4 counterparts [as per the doc here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6) and the [migration guide here](https://developers.google.com/analytics/devguides/migration/api/reporting-ua-to-ga4-dims-mets), including the metric names.
* Stories should be within `assets/js/components/wp-dashboard/WPDashboardSessionDurationGA4.stories.js` and make use of the Analytics 4 response mock data added from #6174
        * Refer to the AC for the different stories to be added.

### Test Coverage
* No new tests to be added.

## QA Brief

* This is currently only testable in Storybook.
* Check the stories under **VIEWS > WPDashboardApp > WPDashboardSessionDurationGA4**. These should be broadly in line with the existing UA version under **VIEWS > WPDashboardApp > WPDashboardSessionDuration**, except with the following additional stories:
	* `Loading`
	* `Error`
* [PR Storybook](https://google.github.io/site-kit-wp/storybook/pull/6640/?path=/story/views-wpdashboardapp-wpdashboardsessiondurationga4--ready) (will be deleted when merged to `develop`).
* [`develop` Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardsessiondurationga4--ready).
* [`main` Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/views-wpdashboardapp-wpdashboardsessiondurationga4--ready).

### Screenshots

<img width="661" alt="Screenshot 2023-02-24 at 5 33 32 PM" src="https://user-images.githubusercontent.com/24408261/221174910-32cc954f-bd2b-42b1-9de9-9e77a5877989.png">
<img width="661" alt="Screenshot 2023-02-24 at 5 33 38 PM" src="https://user-images.githubusercontent.com/24408261/221174906-d6b99716-6e4d-45e0-ac4d-3ca984ea8ded.png">
<img width="661" alt="Screenshot 2023-02-24 at 5 33 45 PM" src="https://user-images.githubusercontent.com/24408261/221174904-44463315-8510-4be7-b76f-7431aa168219.png">
<img width="661" alt="Screenshot 2023-02-24 at 5 33 50 PM" src="https://user-images.githubusercontent.com/24408261/221174897-7e759233-b80f-42c9-80e2-20f96e6f468d.png">
<img width="661" alt="Screenshot 2023-02-24 at 5 33 57 PM" src="https://user-images.githubusercontent.com/24408261/221174886-8be32121-9825-482e-8ff6-e9013b3a1c4b.png">

## Changelog entry

* Create a Google Analytics 4 alternative for the session duration widget on the WordPress dashboard page.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@hussain-t 
I think `WPDashboardSessionDuration`  should not include story with a Current entity set. Also, existing UA4 [story ](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardsessionduration--ready)don't have stories with a current entity set. 
But, it is mentioned in AC - S`torybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready))` so don't want to assume. 

 Is it correct that Storybook will not include examples with current entity URL set for this ticket and for https://github.com/google/site-kit-wp/issues/6217 ?

**Comment by hussain-t** [comment]
@mohitwp, yes, this ticket and [6217](https://github.com/google/site-kit-wp/issues/6217) will not include current entity URL set. It looks like that point was copy pasted in all the GA4 version tickets 6213, 6214, 6215, 6216, and 6217.

**Comment by mohitwp** [comment]
### QA Update ✅ 
 
Thank you @hussain-t !

- Tested [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardsessiondurationga4--ready).

- Compared [WPDashboardSessionDuration](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardsessionduration--ready) with [WPDashboardSessionDurationGA4](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardsessiondurationga4--ready) storybook.

- Storybook added successfully with below listed cases -

1.  Loading
2.  Gathering data ("Data unavailable")
3.  Zero data (data available but metric is 0)
4.  Error
5. Ready (data available and non-zero)


<details>

![image](https://user-images.githubusercontent.com/94359491/222395052-ace73da8-d8f3-48d4-bd4e-bf20f82edbf4.png)

![image](https://user-images.githubusercontent.com/94359491/222395189-7288ea97-ab2f-4e15-9a29-db16a0e13ea2.png)

![image](https://user-images.githubusercontent.com/94359491/222395346-1b104f7a-2f52-4632-9ee0-0a1cbaaaa3ce.png)

![image](https://user-images.githubusercontent.com/94359491/222395403-20ba27cb-c1b5-45d2-8747-39fd99f63de1.png)

![image](https://user-images.githubusercontent.com/94359491/222395459-249c2c15-b6e1-4c68-a497-b43dcff448da.png)

</details>
