### ISSUE TITLE
Create GA4 `AdminBarUniqueVisitors`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6214]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `AdminBarUniqueVisitorsGA4` should be created based on the existing `AdminBarUniqueVisitors`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief
* Once #6173 and #6174 have been merged.
* Create `assets/js/components/adminbar/AdminBarUniqueVisitorsGA4.js` which exports the `AdminBarUniqueVisitorsGA4` functional component.
    * Component should be similar to the one in `assets/js/components/adminbar/AdminBarUniqueVisitors.js` with the following updates:
        * Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`).
        * Replace the metrics and dimensions by their GA4 counterparts [as per the doc here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6), including the metric names.
    * Stories should be within `assets/js/components/adminbar/AdminBarUniqueVisitorsGA4.stories.js` and make use of the Analytics 4 response mock data added from #6174
        * Refer to the AC for the different stories to be added.

### Test Coverage
* No new tests to be added.

## QA Brief

* This is currently only testable in Storybook.
* Check the stories under **VIEWS > AdminBarApp > AdminBarUniqueVisitorsGA4**. These should be broadly in line with the existing UA version under **VIEWS > AdminBarApp > AdminBarUniqueVisitors**, except with the following additional stories:
	* `Loading`
	* `Error`
* [PR Storybook](https://google.github.io/site-kit-wp/storybook/pull/6685/?path=/story/views-adminbarapp-adminbaruniquevisitorsga4--ready) (will be deleted when merged to `develop`).
* [`develop` Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbaruniquevisitorsga4--ready).
* [`main` Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/views-adminbarapp-adminbaruniquevisitorsga4--ready).

### Screenshots

![Screenshot 2023-03-06 at 2 08 08 PM](https://user-images.githubusercontent.com/24408261/223059051-9642d8bc-c3f1-4ddf-9766-3c0757ab5636.png)
![Screenshot 2023-03-06 at 2 08 01 PM](https://user-images.githubusercontent.com/24408261/223059057-8afa3519-6cbe-495f-87a1-229efde292d5.png)
![Screenshot 2023-03-06 at 2 07 55 PM](https://user-images.githubusercontent.com/24408261/223059058-67635882-c70b-407d-aec6-79d648ac4a8a.png)
![Screenshot 2023-03-06 at 2 07 48 PM](https://user-images.githubusercontent.com/24408261/223059060-06ad2488-9e6d-4b7f-a56e-4a64f07ddaa2.png)
![Screenshot 2023-03-06 at 2 07 42 PM](https://user-images.githubusercontent.com/24408261/223059061-9c582461-1be8-4768-a943-bc34c6a3dc9f.png)

## Changelog entry

* Add the Analytics 4 version of the unique visitors tile in the admin bar.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by bethanylang** [comment]
Thanks @derweili, unassigned this from the current sprint and from you for now

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested [StoryBook.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbaruniquevisitorsga4--ready).

- Compared [AdminBarUniqueVisitorsGA4](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbaruniquevisitorsga4--ready) storybook with [AdminBarUniqueVisitors](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbaruniquevisitors--ready).

- [AdminBarUniqueVisitorsGA4](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbaruniquevisitorsga4--ready) storybook have additional below cases-

       *  Loading
       *  Gathering


<details>

![image](https://user-images.githubusercontent.com/94359491/223412902-f49e48f6-1b6c-43ec-a5df-4b53cfafb937.png)

![image](https://user-images.githubusercontent.com/94359491/223412943-f2f872d6-3b57-4879-abb3-eae8da12b2be.png)

![image](https://user-images.githubusercontent.com/94359491/223412976-845a86af-f228-4a0c-bf48-3aa0edeb2859.png)

![image](https://user-images.githubusercontent.com/94359491/223412999-7b9354c8-2a0a-4479-8396-a49fd8df1553.png)

![image](https://user-images.githubusercontent.com/94359491/223413027-07caebdc-d5a0-44d7-b4db-dbfadcaa8383.png)

</details>
