### ISSUE TITLE
Create GA4 `AdminBarSessions`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6215]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `AdminBarSessionsGA4` should be created based on the existing `AdminBarSessions`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief

* Once #6173 and #6174 have been merged.
* Create `assets/js/components/adminbar/AdminBarSessionsGA4.js` which exports the `AdminBarSessionsGA4` functional component. It should be similar to the one in `assets/js/components/adminbar/AdminBarSessions.js` but with the following changes:
    * Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`).
    * Replace the metrics and dimensions by their GA4 counterparts [as per the doc here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6) and the [migration guide here](https://developers.google.com/analytics/devguides/migration/api/reporting-ua-to-ga4-dims-mets), including the metric names.
* Create `assets/js/components/adminbar/AdminBarSessionsGA4.stories.js`, which should have the following stories:
    * Refer to the AC for the different stories to be added.
    * Make use of the Analytics 4 response mock data added from #6174.

### Test Coverage

* No new tests are to be added.

## QA Brief

* This is currently only testable in Storybook.
* Check the stories under **VIEWS > AdminBarApp > AdminBarSessionsGA4**. These should be broadly in line with the existing UA version under **VIEWS > AdminBarApp > AdminBarSessions**, except with the following additional stories:
	* `Loading`
	* `Error`
* [PR Storybook](https://google.github.io/site-kit-wp/storybook/pull/6617/?path=/story/views-adminbarapp-adminbarsessionsga4--ready) (will be deleted when merged to `develop`).
* [`develop` Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbarsessionsga4--ready).
* [`main` Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/views-adminbarapp-adminbarsessionsga4--ready).

### Screenshots

![Screenshot 2023-02-22 at 3 13 01 PM](https://user-images.githubusercontent.com/24408261/220584402-a62056f5-5a33-4483-8252-aa47540f1cef.png)
![Screenshot 2023-02-22 at 3 13 08 PM](https://user-images.githubusercontent.com/24408261/220584440-6ccad238-d517-4a57-911c-8cf5ea6c841d.png)
![Screenshot 2023-02-22 at 3 13 14 PM](https://user-images.githubusercontent.com/24408261/220584505-00f8cbc9-1dfa-4568-bf6e-2de6f4134dc8.png)
![Screenshot 2023-02-22 at 3 13 20 PM](https://user-images.githubusercontent.com/24408261/220584536-fdbd82d0-d427-4715-bff6-c800f566fe9d.png)
![Screenshot 2023-02-22 at 3 13 31 PM](https://user-images.githubusercontent.com/24408261/220584569-2d7d1904-470c-4492-b4b6-f633ec71a214.png)

## Changelog entry

* Create Google Analytics 4 version of the `AdminBarSessions` widget.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@hussain-t In existing UA Story title is "Total Sessions" and for GA4 it is "Sessions" only.  I'm not able to found any related reference in [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6) doc. Did we change title for GA4 `AdminBarSessions` ?

<details>

![image](https://user-images.githubusercontent.com/94359491/222175363-e850f21c-2033-46f3-a3b3-961f5ec1c387.png)

![image](https://user-images.githubusercontent.com/94359491/222175456-e7d1a2c1-b5b3-4d90-a014-c2695f069e94.png)

</details>

**Comment by hussain-t** [comment]
Thanks for raising this, @mohitwp. I changed it to `Sessions` as per the Google migration docs field name:

![Screenshot 2023-03-02 at 2 09 03 PM](https://user-images.githubusercontent.com/24408261/222376143-508fe637-233a-463d-83de-6ab138b4df3c.png)

However, it should be kept the same since it wasn't in the design docs. I will make sure to create a follow-up PR to address it shortly.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested [Storybook.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbarsessionsga4--ready)

- Compared [AdminBarSessionsGA4](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbarsessionsga4--ready) with [AdminBarSessions](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbarsessions--ready).

- Issue reported [above](https://github.com/google/site-kit-wp/issues/6215#issuecomment-1450279004) now resolved.

- Added storybook for below cases.

    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

<details>

![image](https://user-images.githubusercontent.com/94359491/222398647-d4eacacb-802a-4ca3-9bd0-2538a4e35583.png)

![image](https://user-images.githubusercontent.com/94359491/222398703-b4014543-8ad1-4433-8a5c-abed0d2ed2f7.png)

![image](https://user-images.githubusercontent.com/94359491/222398759-ddfaeb4e-4c33-44ab-9954-a0edd58ed45f.png)

![image](https://user-images.githubusercontent.com/94359491/222398815-0ec7321d-0819-4fc3-9a2c-7cb3c10a6c80.png)

![image](https://user-images.githubusercontent.com/94359491/222398875-027ee367-dd4e-4f61-ba20-029835b72721.png)

</details>
