### ISSUE TITLE
Create GA4 `DashboardAllTrafficWidget`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6216]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `DashboardAllTrafficWidgetGA4` should be created based on the existing `DashboardAllTrafficWidget`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief
* Once #6173 and #6174 have been merged.
* Copy `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js` to `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/index.js` with the following changes:
    * The exported component should be updated to `DashboardAllTrafficWidgetGA4`.
    * Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`).
    * Replace the metrics and dimensions by their GA4 counterparts [as per the doc here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6), including the metric names.
    * No need to duplicate child components which do not make use of the Analytics module but instead include them directly from `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/`.
* Update `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js` to check if there is zero data for `MODULES_ANALYTICS_4` data store via the `hasZeroData` selector if the `ga4Reporting` feature flag is enabled.
    * Use the `useFeature` hook to check for the feature flag.
    * Update `showZeroDataChart` in case there is zero data for either Analytics data store or the Analytics 4 data store.
* Stories should be within `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/index.stories.js` and make use of the Analytics 4 response mock data added from #6174
* Enable VRT for the newly added stories.

### Test Coverage
* No new tests to be added.

## QA Brief

* This is currently only testable in Storybook.
* Check the stories under **Analytics > Widgets > All Traffic Widget GA4**. These should be broadly in line with the existing UA version under **Analytics Module > Components > (Dashboard/Entity Dashboard) > All Traffic Widget**, except with slightly different pie chart/channel data.
* [PR Storybook](https://google.github.io/site-kit-wp/storybook/pull/6514/?path=/story/modules-analytics-widgets-all-traffic-widget-ga4-main-dashboard--main-dashboard-loaded) (will be deleted when merged to `develop`).
* [`develop` Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-all-traffic-widget-ga4-main-dashboard--main-dashboard-loaded).
* [`main` Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-analytics-widgets-all-traffic-widget-ga4-main-dashboard--main-dashboard-loaded).

![image](https://user-images.githubusercontent.com/18395600/219040667-b2401d93-2196-45e6-833c-2a81020758f6.png)

![image](https://user-images.githubusercontent.com/18395600/219040776-a73c6a83-1474-4777-b9f6-def22c219780.png)

![image](https://user-images.githubusercontent.com/18395600/219040861-f886c671-769d-46cf-a362-11cdd35de0af.png)

![image](https://user-images.githubusercontent.com/18395600/219101597-eb55d889-5af3-4681-9af4-eb6838632eba.png)

![image](https://user-images.githubusercontent.com/18395600/219041171-df5a7095-0145-4c57-ad10-2205c1d0cb60.png)

![image](https://user-images.githubusercontent.com/18395600/219041261-fc4cbc6d-aa14-4210-9a97-a608d5407a02.png)

## Changelog entry

* Add new widget for "All traffic" using GA4 as a data source.

**Comment by tofumatt** [comment]
Makes sense not to copy the files for now. We'll catch that in any refactors 😄

We should probably include VRTs for these stories though, if that won't be overly complicated to do? Just so changes in the UA versions don't affect the GA4 component unknowingly?

**Comment by asvinb** [comment]
Thanks @tofumatt . IB updated and I've bumped the estimates to include adding VRT scenarios.

**Comment by tofumatt** [comment]
Awesome, thanks! 🙂 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-all-traffic-widget-ga4-entity-dashboard--entity-dashboard-loaded).

- Compared the stories under Analytics > Widgets > All Traffic Widget GA4. and version under Analytics Module > Components > (Dashboard/Entity Dashboard) > All Traffic Widget. Both stories are similar, except slight changes in channel data.

- Tested stories under entity and main dashboard.



<details>

![image](https://user-images.githubusercontent.com/94359491/221168470-95c7b226-315a-4da1-8ee7-afd9a03d4a60.png)

![image](https://user-images.githubusercontent.com/94359491/221168562-98ef805e-4cf1-4480-a052-cd301d8cfaa5.png)

![image](https://user-images.githubusercontent.com/94359491/221168836-ee22cf55-3c1e-4444-910f-c3cca53d9831.png)

![image](https://user-images.githubusercontent.com/94359491/221168915-00af03de-a847-40ef-9451-804332efb4b6.png)

![image](https://user-images.githubusercontent.com/94359491/221169000-44ec6028-2b49-4828-8d7a-31717dd72e31.png)

![image](https://user-images.githubusercontent.com/94359491/221169068-27d61ec4-ba05-49bf-877c-8ae1d6234dd9.png)

![image](https://user-images.githubusercontent.com/94359491/221170403-32e35f2f-455c-45e3-acd2-2b2e93a3db60.png)

![image](https://user-images.githubusercontent.com/94359491/221171082-d4d37d58-93fe-4364-aa3e-57d67cc7d5f7.png)



</details>

**Comment by aaemnnosttv** [comment]
Correcting the release as this was merged to develop after the cutoff for 1.95.0.
