### ISSUE TITLE
Create GA4 `DashboardOverallPageMetricsWidget`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6218]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `DashboardOverallPageMetricsWidgetGA4` should be created based on the existing `DashboardOverallPageMetricsWidget`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief

- Wait until #6173 and #6174 are merged.
- Create `assets/js/modules/analytics-4/components/dashboard/DashboardOverallPageMetricsWidgetGA4.js`. In this file:
    - Copy over everything from `assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidget.js`.
	- Replace all usages of `MODULES_ANALYTICS` with `MODULES_ANALYTICS_4`, except for the `getServiceReportURL` selector call.
    - Replace usages according to the following:
	    - `ga:pageviews` with `screenPageViews`
	    - `Unique Pageviews` with `Sessions`
	    - `ga:uniquePageviews` with `sessions`
	    - `Bounce rate` with `Engaged Sessions`
	    - `ga:bounceRate` with `engagedSessions`
	    - `ga:avgSessionDuration` with `userEngagementDuration`
- Create `assets/js/modules/analytics-4/components/dashboard/DashboardOverallPageMetricsWidgetGA4.stories.js`. In this file:
    - Copy over everything from `assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidget.stories.js`.
	- Replace all usages of `MODULES_ANALYTICS` with `MODULES_ANALYTICS_4`.
	- Replace usages according to the following:
	    - `ga:users` with `totalUsers`
	    - `ga:pageviews` with `screenPageViews`
	    - `Unique Pageviews` with `Sessions`
	    - `ga:uniquePageviews` with `sessions`
	    - `Bounce rate` with `Engaged Sessions`
	    - `ga:bounceRate` with `engagedSessions`
	    - `ga:avgSessionDuration` with `userEngagementDuration`
    - Replace usages of `provideAnalyticsMockReport` with `provideAnalytics4MockReport`, being added as a part of #6174.
    - Replace usages of `getAnalyticsMockResponse` with `getAnalytics4MockResponse`, being added as a part of #6174.

### Test Coverage

- Create `assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidget.test.js` and add test cases covering different scenarios.

## QA Brief

* This is currently only testable in Storybook.
* Check the stories under **Analytics > Widgets > DashboardOverallPageMetricsWidgetGA4**. These should be broadly in line with the existing UA version under **Analytics > Widgets > DashboardOverallPageMetricsWidget**, except with different data. Also, there are no sparklines for the Zero Data stories - this will be addressed as necessary in #6623.
* [PR Storybook](https://google.github.io/site-kit-wp/storybook/pull/6629/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready) (will be deleted when merged to `develop`).
* [`develop` Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready).
* [`main` Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready).

![image](https://user-images.githubusercontent.com/18395600/220984334-33751ac5-de52-422d-a8cf-befde76516ff.png)

![image](https://user-images.githubusercontent.com/18395600/220984443-a41b845f-276b-4f58-a1c3-4e8b409329fb.png)

![image](https://user-images.githubusercontent.com/18395600/220984576-320d107c-aafc-4ea8-a95d-6fdf1a4181c4.png)

![image](https://user-images.githubusercontent.com/18395600/220984657-72dad392-fd54-42c5-8563-a0e0be161c4a.png)

![image](https://user-images.githubusercontent.com/18395600/220984739-ca147eb7-a083-45aa-802a-a74007f5180c.png)

![image](https://user-images.githubusercontent.com/18395600/220985569-29229d00-b4eb-4e4b-a26c-6e3c27f401ab.png)

![image](https://user-images.githubusercontent.com/18395600/220984938-9e7d42ab-905f-4e89-9e2a-3e8a779846f1.png)

![image](https://user-images.githubusercontent.com/18395600/220985039-3ff644f8-9715-4df6-83f1-02bb87aee9b7.png)

![image](https://user-images.githubusercontent.com/18395600/220985164-6fcbc0fc-f903-4ca1-8424-1d5cb57c7cd6.png)

![image](https://user-images.githubusercontent.com/18395600/220985760-2dfd02dc-d040-468f-99be-2ba87e977403.png)

## Changelog entry

* Add a Google Analytics 4 alternative for the overall page metrics widget.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested [Storybook (dev)](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready).
- Compared newly added [GA4 DashboardOverallPageMetricsWidget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready) with [DashboardOverallPageMetricsWidget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready).
- Verified content changes as mentioned, in [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
- Note - As mentioned in QAB - Also, there are no sparklines for the Zero Data stories - this will be addressed as necessary in https://github.com/google/site-kit-wp/issues/6623.

![image](https://user-images.githubusercontent.com/94359491/222170176-9991ab21-63f2-4bce-8d92-82db72514cda.png)


<details>

![image](https://user-images.githubusercontent.com/94359491/222168945-41bdf79b-9598-4cc9-b87d-756ee06f4f2b.png)

![image](https://user-images.githubusercontent.com/94359491/222168985-452a12c3-2504-42c1-b2f1-ae0b1a714d9f.png)

![image](https://user-images.githubusercontent.com/94359491/222169076-25b687e3-a66a-4840-a978-1a1797f8f77a.png)

![image](https://user-images.githubusercontent.com/94359491/222169146-25d4179c-8331-41bf-b789-c9abc2f5e770.png)

![image](https://user-images.githubusercontent.com/94359491/222169605-418aff3a-dc0e-43a9-9a69-1dc8fe323dec.png)

![image](https://user-images.githubusercontent.com/94359491/222169469-1c945707-05d9-4eb1-aca2-faf680f40bb0.png)

![image](https://user-images.githubusercontent.com/94359491/222169713-8a47afbc-732b-441e-8c33-47da079daa52.png)

![image](https://user-images.githubusercontent.com/94359491/222169813-b37e3ca6-bf49-4f0c-88e8-3a52061206bc.png)

![image](https://user-images.githubusercontent.com/94359491/222169857-d469f3c2-ba1a-46d6-92aa-00f10111dba6.png)

</details>

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil 

We raised the PR to use engagement rate instead of engaged sessions.  But under[ StoryBook ](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready)we are still showing title "EngagedSessions" .  I'm wondering raised PR is to just change the metric being queried from `engagedSessions` to `engagementRate` or title should also change ?


![image](https://user-images.githubusercontent.com/94359491/223415669-eb90f3da-95a6-4041-8a29-f4964b2371ae.png)

**Comment by techanvil** [comment]
Thanks @mohitwp - a most valid question. We have been discussing this on Slack and have decided to change to the title "Engagement rate". However, so as to avoid yet more scope creep, we'll be doing so in a subsequent issue, https://github.com/google/site-kit-wp/issues/6693. So, for the purposes of this issue, "Engaged Sessions" is fine.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested [Storybook (dev)](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready).
- Compared newly added [GA4 DashboardOverallPageMetricsWidget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidgetga4--ready) with [DashboardOverallPageMetricsWidget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready).
- Verified content changes as mentioned, in [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
- Note - As mentioned in QAB - Also, there are no sparklines for the Zero Data stories - this will be addressed as necessary in https://github.com/google/site-kit-wp/issues/6623.

![image](https://user-images.githubusercontent.com/94359491/222170176-9991ab21-63f2-4bce-8d92-82db72514cda.png)

- Engaged sessions title will change to engagement rate through this PR - https://github.com/google/site-kit-wp/issues/6693

<details>

![image](https://user-images.githubusercontent.com/94359491/223443944-1273b088-31cc-49b2-88ba-200f93bb57cc.png)

![image](https://user-images.githubusercontent.com/94359491/223444070-0c0c9571-8df8-4143-9e8a-bc21870d1b65.png)

![image](https://user-images.githubusercontent.com/94359491/223444169-4e688d77-80ba-4736-88b1-62041c61175a.png)

![image](https://user-images.githubusercontent.com/94359491/223444291-d9836ea4-7f5a-41e1-a180-581ba045694e.png)

![image](https://user-images.githubusercontent.com/94359491/223444370-a4e063a4-e3a3-41eb-afdb-88e13297bbe2.png)

![image](https://user-images.githubusercontent.com/94359491/223444500-5a307e03-8dc3-405b-9f0b-70ba73ef4bf5.png)

![image](https://user-images.githubusercontent.com/94359491/223444554-68a4ea11-01a2-4611-b483-46113f57ccbb.png)

![image](https://user-images.githubusercontent.com/94359491/223444596-25c0f1f3-bf84-484d-83b2-94c756dd6517.png)

![image](https://user-images.githubusercontent.com/94359491/223444660-e51065aa-596f-4280-b88d-76151e41a7d0.png)

![image](https://user-images.githubusercontent.com/94359491/223444810-11a62426-17e3-4874-880f-0b8373b57020.png)

</details>
