### ISSUE TITLE
Create GA4 `ModulePopularPagesWidget`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6219]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `ModulePopularPagesWidgetGA4` should be created based on the existing `ModulePopularPagesWidget`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief
* Once #6173 and #6174 have been merged.
* Create `assets/js/modules/analytics-4/components/module/ModulePopularPagesWidgetGA4.js` which exports the `ModulePopularPagesWidgetGA4` functional component.
    * Component should be similar to the one in `assets/js/modules/analytics/components/module/ModulePopularPagesWidget` with the following updates:
        * Extract the `Header` and `Footer` if needed as it's done for `ModulePopularPagesWidget`
        * Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`) except for `getServiceReportURL` selector call.
        * Replace the metrics and dimensions by their GA4 counterparts [as per the doc here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6), including the metric names.
    * Stories should be within `assets/js/modules/analytics-4/components/module/ModulePopularPagesWidgetGA4.stories.js` and make use of the Analytics 4 response mock data added from #6174
        * Refer to the AC for the different stories to be added.

### Test Coverage
* Add tests similar to `assets/js/modules/analytics/components/module/ModulePopularPagesWidget/Footer.test.js`

## QA Brief

* This is currently only testable in Storybook.
* Check the stories under **Analytics > Widgets > ModulePopularPagesWidgetGA4**. These should be broadly in line with the existing UA version under **Analytics Module > Components > Module Page > Popular Pages Widget**, except with different data, and with the Engaged Sessions rather than Bounce Rate column.
* [PR Storybook](https://google.github.io/site-kit-wp/storybook/pull/6649/?path=/story/modules-analytics-widgets-modulepopularpageswidgetga4--loaded) (will be deleted when merged to `develop`).
* [`develop` Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-modulepopularpageswidgetga4--loaded).
* [`main` Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-analytics-widgets-modulepopularpageswidgetga4--loaded).

![image](https://user-images.githubusercontent.com/18395600/223215771-432360e5-8eef-44d7-aac4-7f8b585228f7.png)

![image](https://user-images.githubusercontent.com/18395600/221899382-6995f7bb-e379-4cbd-a515-9cc78594ac9d.png)

![image](https://user-images.githubusercontent.com/18395600/221899532-6efcc673-6515-4e0b-9968-60810014fe2a.png)

![image](https://user-images.githubusercontent.com/18395600/221899647-ad25521c-ea64-4329-97a2-76679fbae591.png)

![image](https://user-images.githubusercontent.com/18395600/221899787-5f73571d-6f82-4eb0-8b0a-a5d52797c487.png)

## Changelog entry

* Create the Analytics 4 version of the popular pages widget.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil 
I've noticed that under 'OverAllpagemetricesWidgetGA4" Engaged sessions value is in percentage % where as under "ModulePopularWidfgestStory" value of 'EngagedSessions' is not defined. I'm wondering is the current implementation is correct, or we should show all values in percentage ?

![image](https://user-images.githubusercontent.com/94359491/223114363-31038213-19d4-4527-9523-738222eb818f.png)

![image](https://user-images.githubusercontent.com/94359491/223115219-b3697ef0-e904-47e9-a38b-ec74607388a9.png)

**Comment by techanvil** [comment]
Hmm, thanks for raising this @mohitwp. We have been implementing Engaged Sessions as a regular integer, rather than a percentage, so this suggests the `DashboardOverallPageMetricsWidgetGA4` implementation is inconsistent with our approach so far.

However, referring back to the PRD I've noticed that there's an ambiguity about this and it may be the case we need to revisit and use a different metric instead, `engagementRate`, and display it as a percentage. I've asked @marrrmarrr to clarify this with a [question](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw&pli=1&disco=AAAAsdib7LI) on the PRD.

**Comment by techanvil** [comment]
@mohitwp, as discussed on Slack we need to ensure Engaged Sessions is presented as a percentage, and additionally we need to change the metric being queried from `engagedSessions` to `engagementRate`. I'm moving this issue back to Execution to address this. I'm also raising a following PR for #6218 to address `DashboardOverallPageMetricsWidgetGA4`.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested [Storybook.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-modulepopularpageswidgetga4--loaded).

- Compared [ModulePopularPagesWidgetGA4](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-modulepopularpageswidgetga4--loaded) with [PopularPagesWidget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-components-module-page-popular-pages-widget--loaded) .

- As per [comment](https://github.com/google/site-kit-wp/issues/6219#issuecomment-1456845502) above - Engaged sessions are now presented in percentage.

-  Storybook stories added to cover the following cases 

    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)



<details>

![image](https://user-images.githubusercontent.com/94359491/223409013-4396e89e-5df9-41e4-806c-0badce33ce67.png)

![image](https://user-images.githubusercontent.com/94359491/223409108-f530efb2-266b-4546-8eac-474cff7d451c.png)

![image](https://user-images.githubusercontent.com/94359491/223409563-3ae4f52c-71cf-4acb-ac44-386779993f6f.png)

![image](https://user-images.githubusercontent.com/94359491/223409643-bdf387ce-2339-4154-a9d1-4e710873ed0a.png)

![image](https://user-images.githubusercontent.com/94359491/223409768-0d27595f-56cb-4471-9b5a-e8060409a493.png)

</details>
