### ISSUE TITLE
GA4 Property Select shows the Property ID instead of the Measurement ID when disabled

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#6225]
## Bug Description

We introduced displaying the Measurement ID instead of the property ID in #5145. In the Analytics settings edit page, when the GA4 is not connected and when toggling ON the `Activate Google Analytics 4 and place code on your site.` switch, the GA4 Property Select shows the Property ID instead of the Measurement ID if it is disabled.

## Steps to reproduce

1. Disconnect GA4 if it is already connected.
2. Go to the settings page.
3. Click on the `Connect Google Analytics 4` CTA.
4. Toggle ON the `Activate Google Analytics 4 and place code on your site.` switch (if it is toggled OFF).
5. The property select shows the Property ID instead of the Measurement ID when disabled.

## Screenshots

<img width="360" alt="Screenshot 2022-11-29 at 2 48 22 PM" src="https://user-images.githubusercontent.com/24408261/204489010-b9c0a882-cf23-49d3-aee4-b4f75a01fc03.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 `PropertySelect` component should display the Measurement ID instead of the Property ID when disabled, like how it is displayed (implemented) in the `GA4SettingsControls` component when it is disabled.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eclarke1** [comment]
Please can we add a priority label here?

**Comment by aaemnnosttv** [comment]
@hussain-t the steps to reproduce here are referencing a bug that was fixed in follow-ups to #5886. Can you confirm this is still an issue? If the user can activate GA4, the property select shouldn't be disabled.

**Comment by hussain-t** [comment]
Thanks, @aaemnnosttv. I verified it was fixed. However, this code needs to be updated to show the Measurement ID instead of the Property ID  if the user doesn't have access. WDYT?

https://github.com/google/site-kit-wp/blob/386764cfd12db2fdef9f64229bf8eb136269c938/assets/js/modules/analytics-4/components/common/PropertySelect.js#L129-L144

**Comment by hussain-t** [comment]
SGTM 👍

**Comment by bethanylang** [comment]
@aaemnnosttv @hussain-t Looks like #6293 was included in 1.90.0, so worth taking another look here to determine next steps?

**Comment by hussain-t** [comment]
Closing this one as it's already been addressed in https://github.com/google/site-kit-wp/issues/6293
