### ISSUE TITLE
Update infrastructure to enable proper usage of PHP Attributes 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6231]
## Feature Description

Currently, trying to use a PHP Attribute results in a bunch of `phpcs` errors due to outdated dependencies which requires lots of `phpcs:ignore`'s. See the screenshot below. 

We should take necessary steps to be able to use PHP Attributes freely without any linting errors or workarounds. 

![Screenshot_20221130_162715](https://user-images.githubusercontent.com/6187401/204773167-701514f5-6e0a-4c5e-b06d-3f3dc47ff0cb.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Usage of PHP 8 Attributes should be supported by the installed version of PHP Codesniffer and should not raise any PHPCS errors.
    * `phpcbf` should not incorrectly format `Perl style comments` when it is used for PHP Attributes. 
* All the `phpcs:ignores` around PHP Attributes should be removed. 

## Implementation Brief

* Update currently installed version of `squizlabs/php_codesniffer` to a version that fully supports PHP 8 Attributes and doesn't raise any false positives.  ie. 3.6.x or 3.7.x. 
    * The currently installed version is `3.5.8` with `^3.3` as the version constraint in `composer.json`. 
* Update `includes/Core/REST_API/Data_Request.php` and remove all the `phpcs:ignore`'s.
* Run `composer lint` and fix any other error that comes up due to the codesniffer version change. 
    * `includes/Modules/Analytics.php` 

### Test Coverage

* N/A

## QA Brief

* Nothing really to QA here, it's an infra-related task to update code linting rules.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
Moving directly to Approval since there is nothing to QA here.
