### ISSUE TITLE
Implement Key metrics CTA dismissal

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6232]
## Feature Description

When a user clicks on "Maybe later" in the Key metrics setup CTA, the CTA should be dismissed along with a tooltip, similar to the flow within `<AdSenseConnectCTAWidget>`.

Refer to the [relevant section](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit?pli=1#heading=h.snxtf0ab56zj) in the design doc for further context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Clicking on “Maybe later” in the Key metrics Setup CTA widget should hide the widget, its title and the navigation “chip” completely.
* It should then display an `<AdminMenuTooltip>` which will prompt the user to enable the widget later from the new [Admin settings panel](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit?pli=1#heading=h.9lupra8ydzvh). The same flow and code can be reused from the `<AdSenseConnectCTAWidget>` component's dismissal.

## Implementation Brief

- As the AC suggests, the flow and code can be reused from the [`AdSenseConnectCTAWidget`](https://github.com/google/site-kit-wp/blob/610f6fd2ce5238eb4024d27f0335fc0e1311c381/assets/js/modules/adsense/components/dashboard/AdSenseConnectCTAWidget.js), conditionally rendering `AdminMenuTooltip` and using the `useTooltipState` hook with a new key to handle the tooltip state. 
- The copy for the tooltip should be as seen in [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1152%3A35697&t=Bcf6WXLlIhylKgKZ-0). Don't forget to translate the strings:
  - `title`: _You can always set up goals from Settings later_
  - `content`: _The Key Metrics section will be added back to your dashboard once you set your goals in Settings._
- Pass the new `handleDismissTooltip` function to the click handler for the "Maybe later" button introduced in #6210.

### Test Coverage

* No new tests needed.

## QA Brief

* Verify the KMW Setup widget "Maybe Later" button works as described in AC. 
* The tooltip should appear when the button is pressed.
* The widget should be dismissed when the Tooltip is dismissed. 

## Changelog entry

* Show a tooltip when clicking "Maybe later" on the Key Metrics Setup CTA widget, and allow the widget to be dismissed.

**Comment by tofumatt** [comment]
AC ✅

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Clicking on “Maybe later” in the Key metrics Setup CTA widget hides the widget, its title and the navigation “chip” 
- The user then see's a tooltip which will prompts the user to enable the widget later from the settings. 
   - The copy for the tooltip is as seen in Figma and the IB.
- Tested on various viewports to make sure that the behaviour is consistent with above. 
- Tested on our supported browsers to ensure that the behaviour is consistent with above.
- Checked for no errors or warnings in the browser console when action taken above. 


https://github.com/google/site-kit-wp/assets/73545194/2335302e-e64c-4ff6-accb-df2aa51c22a0
