### ISSUE TITLE
Create data store infrastructure to fetch answer-based metrics

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6234]
## Feature Description

This issue maps the default metrics to show based on an authenticated admin's response to the first user input question.

A partial store within `core/widgets`, say `key-metrics` should have a new selector, say `getAnswerBasedMetrics()` which would check the current user input setting for the response to the first question (using the `user-input-settings` partial store within `core/user`) and return the appropriate 4 core metrics which should be displayed.

Refer to the [relevant section](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.zc9k0id36g3e) in the design doc for further context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new partial store within `core/widgets`, `key-metrics` should have a new selector, `getAnswerBasedMetrics()`.
* The selector should check the response to the first question in the user input questionnaire using `getUserInputSettings` from the `user-input-settings` partial store within `core/user`.
* It should return an object of widget slug strings for the widgets defined in [this table in the design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t).
* The widgets slugs returned should be mapped as follows:
    - If answer is `publish_blog` or `publish_news`:
        - `kmAnalyticsLoyalVisitors` 
        - `kmAnalyticsNewVisitors`
        - `kmAnalyticsTopTrafficSource`
        - `kmAnalyticsEngagedTrafficSource`
    - If answer is `monetize_content`:
        - `kmAnalyticsPopularContent`
        - `kmAnalyticsEngagedTrafficSource`
        - `kmAnalyticsNewVisitors`
        - `kmAnalyticsTopTrafficSource`
    - If answer is `sell_products_or_service`:
        - If the site has a `post_type` defined as "product", then show `kmTopPopularProducts`. Else show `kmAnalyticsPopularContent`.
        - `kmAnalyticsEngagedTrafficSource`
        - `kmSearchConsolePopularKeywords`
        - `kmAnalyticsTopTrafficSource`
    - If answer is `share_portfolio`:
        - `kmAnalyticsNewVisitors`
        - `kmAnalyticsTopTrafficSource`
        - `kmAnalyticsEngagedTrafficSource`
        - `kmSearchConsolePopularKeywords`

## Implementation Brief
* Create `assets/js/googlesitekit/widgets/datastore/key-metrics.js` which only contains the `getAnswerBasedMetrics` selector and only `selectors` should be exported. (Refer to other data store partials for the structure).
* Within `getAnswerBasedMetrics`,
    * Get the filled in user input questionnaire answers by querying the `core/user` data store via the `getUserInputSettings` selector.
    * Grab the answers for the `purpose` question (which is the first question) and return the widget slugs as per the AC.
        * To check whether the site has the "product" post type, query the `core/site` data store via the `getPostTypes` selector and check whether there is a post type with the `slug` set to `product`.

### Test Coverage
* Add tests for the `getAnswerBasedMetrics` selector.

## QA Brief

- Install Site Kit and enable the `userInput` feature flag.
- Set the value of the `purpose` answer by running through the User Input setup flow.
  - Navigate to `/wp-admin/admin.php?page=googlesitekit-user-input&question=purpose` to begin the flow.
- For each of the widget slugs mentioned in the AC:
  - Choose the corresponding answer, and continue through the User Settings setup until they are saved.
  - Call the `getAnswerBasedMetrics()` selector from the JS console as follows.
  - Verify the returned set of Key Metric widget slugs matches the definition in the AC.
  - Note, in order to test `sell_products_or_service`, an easy way to ensure the `product` post type is created is to install the Woo Commerce plugin. It only needs to be activated and not configured.
  - When the `other` slug is chosen, the selector should return an empty array.
```js
googlesitekit.data.select('core/widgets').getAnswerBasedMetrics();
```

## Changelog entry

* Add the  `getAnswerBasedMetrics` selector to the widgets datastore.

**Comment by jimmymadon** [comment]
@aaemnnosttv Can you please quickly review the [widget slugs added in the design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t)? I recommend adding a "km" prefix. It might even be a nice idea to have a "km<ModuleName><WidgetName>" where ModuleName is the main module on which the widget is dependant on. The only little downside is that it increases the length of the names further. We could even drop the word "top" which doesn't add too much meaning to the slugs to make them shorter. Thoughts?

**Comment by aaemnnosttv** [comment]
> I recommend adding a "km" prefix.

SGTM 👍 

> It might even be a nice idea to have a `km<ModuleName><WidgetName>` where ModuleName is the main module on which the widget is dependant on.

That sounds good at first but doesn't quite fit with the multi-module model that applies to all widgets. I.e. what about for the top earning pages widget? Do you put AdSense or Analytics or both? I would suggest we leave off the module part for now as it is today; it's only an internal ID anyways for the most part.

> We could even drop the word "top" which doesn't add too much meaning to the slugs to make them shorter.

I don't think we need to worry too much about 3 characters 🤔 Let's keep it. With the new PSI widgets we'll have "bottom"-ranked content too so it makes sense to keep the distinction 👍

**Comment by jimmymadon** [comment]
@aaemnnosttv  

>  doesn't quite fit with the multi-module model that applies to all widgets. I.e. what about for the top earning pages widget? Do you put AdSense or Analytics or both?

Currently, the Top Earning Pages widget in our plugin is named: `adsenseTopEarningPages`. All our existing widget slugs have a prefix - that's why I thought to maintain consistency. Do you think we should still proceed without module names?

**Comment by aaemnnosttv** [comment]
> Currently, the Top Earning Pages widget in our plugin is named: `adsenseTopEarningPages`. All our existing widget slugs have a prefix - that's why I thought to maintain consistency. Do you think we should still proceed without module names?

@jimmymadon Most have a prefix, but not all (e.g. [`searchFunnel`](https://github.com/google/site-kit-wp/blob/9e3a9db809b7fd521114bf6006a2cc1602118d3f/assets/js/modules/search-console/index.js#L62)). I'm not against having the module in the slug where it makes sense, I just don't think we should force a module into the slug. `adsenseTopEarningPages` makes sense rather than just `topEarningPages` because `adsense` is the source of the earning. If TwG were around, we might also have a widget for top earning pages by that, so that makes sense.

Maybe I misunderstood what you were suggesting. Where a widget is clearly specific to a single module/service, it makes sense to include that. We do have cases where multiple services/modules are present in a single widget then it makes sense to omit them.

**Comment by tofumatt** [comment]
> TODO: Complete map below once slugs are finalized

Is that still the case? This looks good otherwise but always a bit concerned writing flexible ACs like this 😅

**Comment by tofumatt** [comment]
All good, ACs 👍🏻

**Comment by asvinb** [comment]
@jimmymadon I have a few questions about the AC:

1. As per the AC, the new selector should return an object of widget slug strings. Do you have the exact format to be returned or it's just an array of widget slug strings?
2. "If the site has a post_type defined as "product", do you know if this info should be provided at PHP level and then accessed as a localized JS variable?

Thanks!

**Comment by tofumatt** [comment]
@asvinb Why put this selector in the `widgets` datastore? It's related to a user's "User Input" responses, and isn't specific to widgets. There's already a `assets/js/googlesitekit/datastore/user/key-metrics.js` file with other key metrics selectors, so rather than `assets/js/googlesitekit/widgets/datastore/key-metrics.js`, can we put this in that same `assets/js/googlesitekit/datastore/user/key-metrics.js` file?

**Comment by aaemnnosttv** [comment]
> Why put this selector in the `widgets` datastore? It's related to a user's "User Input" responses, and isn't specific to widgets.

@tofumatt the AC calls for it, does it not? Ok to revise that if it makes sense but it seems to be consistent with what the AC calls for. Also I think "metrics" in this sense is synonymous with "widgets". Answer-based metrics are the widgets that correspond to a user's answers to the user input survey. Is that correct?

**Comment by asvinb** [comment]
@tofumatt I agree with you. Sounded weird but I followed the AC, but I would have it within the `user` data store especially since the `getAnswerBasedMetrics` is more user specific. What do you think @jimmymadon @aaemnnosttv ?

**Comment by asvinb** [comment]
Thanks for the info @jimmymadon, maybe `getKeyMetricsWidgets` and `getAnswerBasedMetricsWidgets` might be better names for the selector and let them live in `core/widgets` 🤔 . But happy to have them in `core/widgets` irrespective 😁 

Let me know what you think @tofumatt

**Comment by tofumatt** [comment]
Ahhhh, okay, I admittedly missed the ACs here, though in general always happy to revise them if they don't quite make sense. Seeing this mapped out with an IB makes me think it's more a user thing, but then seeing the discussion/reasoning for it here makes me think widgets is fine too. I guess it's not entirely per-user but also somewhat shared and thus, doesn't _really_ matter.

In that case, I'd say the ACs and IB here are good. Thanks everyone! 👍🏻 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Selected the different purpose answers and Call the getAnswerBasedMetrics() selector from the JS console.
- The widgets slugs returned are mapped as mentioned in AC.

- If answer is publish_blog or publish_news

<details>

![image](https://user-images.githubusercontent.com/94359491/220606868-a16dbdb2-bfbd-4c81-b84e-870a9a1d01a9.png)

![image](https://user-images.githubusercontent.com/94359491/220606906-77c4e17a-5a41-4399-81fb-a6f35a0eeb90.png)

</details>

- If answer is monetize_content:

<details>

![image](https://user-images.githubusercontent.com/94359491/220607254-8c169d66-a746-4775-b17f-2d6f4b97d556.png)

![image](https://user-images.githubusercontent.com/94359491/220607331-b3c24c93-5a21-4863-8daa-9a78ed441e0e.png)

</details>

- If answer is sell_products_or_service
  
`Post type defined as product`

<details>

![image](https://user-images.githubusercontent.com/94359491/220607648-cf894552-0219-4442-a14c-f7272049a03e.png)

</details>

`post type product not defined-`

<details>


![image](https://user-images.githubusercontent.com/94359491/220607777-896de29a-777d-4ef6-88e0-0d22cd32962a.png)

![image](https://user-images.githubusercontent.com/94359491/220607809-c39bff39-06a2-4810-9c00-1d5172d8fc47.png)

</details>

- If answer is share_portfolio

 <details>

![image](https://user-images.githubusercontent.com/94359491/220608059-4e340143-f605-438f-a139-fb6148f51f46.png)

![image](https://user-images.githubusercontent.com/94359491/220608125-bed36630-d792-4426-bd24-2b0d2a85ef96.png)

 </details>

- if answer is other

<details>

![image](https://user-images.githubusercontent.com/94359491/220608280-4a1451c3-9fa8-4e25-852b-603e03f55f57.png)

</details>

**Comment by aaemnnosttv** [comment]
## ❌ Approval

The AC call for 4 metrics to be returned in each case, however this seems to have been misinterpreted in the `sell_products_or_service` scenario where a `product` post type is present. That condition should only change one of the four metrics returned, but it currently only returns a single metric.

**Comment by aaemnnosttv** [comment]
## ✅ Approval

Without a product post type
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/1621608/221038186-48deb2d1-c6a2-4fd9-b018-c4e6356c3db2.png">

With a product post type
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/1621608/221038227-f94baf19-a8b9-4166-b0b9-5be66cbf2243.png">

**Comment by techanvil** [comment]
> ##  Approval
> The AC call for 4 metrics to be returned in each case, however this seems to have been misinterpreted in the `sell_products_or_service` scenario where a `product` post type is present. That condition should only change one of the four metrics returned, but it currently only returns a single metric.

Whoops! An unfortunate mistake, misinterpreting the formatting in the AC. Should have been evident, in 20/20 hindsight. Thanks for spotting!
