### ISSUE TITLE
Remove Idea Hub

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6235]
## Feature Description

The experimental Idea Hub module is to be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub module is to be entirely removed including its feature flag, components, data store, classes, related styles, tests, stories, and assets
	* There should be no remaining references to it other than in the changelog

## Implementation Brief

- In `feature-flags.json`:
    - Remove `ideaHubModule` from the returned array.
- In `scoper.inc.php`:
    - Remove the `Ideahub` service from `$google_services`.
- In `assets/js/components/notifications/BannerNotifications.js`:
    - Remove `<IdeaHubPromptBannerNotification />`.
- In `assets/js/components/notifications/SetupSuccessBannerNotification.js`:
    - In the switch case `authentication_success` for `notification`, remove the block where `slug` is `idea-hub`.
- In `assets/js/components/notifications/SetupSuccessBannerNotification.stories.js`:
    - Remove the `IdeaHub` story.
- In `assets/js/components/wp-dashboard/WPDashboardWidgets.js`:
    - Remove `<WPDashboardIdeaHub />`.
- In `assets/js/feature-tours/index.js`:
    - Remove `ideaHubModule` and `ideaHubPostsTable`.
- In `includes/Core/Modules/Modules.php`:
    - In the class constructor, remove the block of code where `Idea_Hub` is added to `$core_modules`.
- In `includes/Core/Authentication/Authentication.php`:
    - In the `filter_features_via_proxy()` method, remove the block where `$feature_name` is `ideaHubModule`.
- In `webpack.config.js`:
    - Remove all entry points that include `idea-hub`.
    - Remove the Gutenberg entry points and relevant code.
- In `assets/js/components/dashboard-sharing/DashboardSharingSettings/constants.js`:
    - Remove `idea-hub` from `EXPERIMENTAL_MODULES`.
- Across the codebase:
    - Remove any remaining usages of the `Idea_Hub` PHP class.
    - Remove any other remaining instances of `/idea.hub/` (case-insensitive).
- Delete the following directories and files:
    - `assets/js/googlesitekit-idea-hub-notice.js`
    - `assets/js/googlesitekit-idea-hub-post-list.js`
    - `assets/js/googlesitekit-modules-idea-hub.js`
    - `assets/js/components/notifications/IdeaHubPromptBannerNotification.js`
    - `assets/js/components/notifications/IdeaHubPromptBannerNotification.stories.js`
    - `assets/js/components/wp-dashboard/WPDashboardIdeaHub.js`
    - `assets/js/components/wp-dashboard/WPDashboardIdeaHub.stories.js`
    - `assets/js/feature-tours/idea-hub-module.js`
    - `assets/js/feature-tours/idea-hub-module.stories.js`
    - `assets/js/feature-tours/idea-hub-posts-table.js`
    - `assets/js/modules/idea-hub/`
    - `assets/sass/components/idea-hub/`
    - `includes/Modules/Idea_Hub/`
    - `includes/Modules/Idea_Hub.php`

###  Test Coverage

- In `tests/js/utils.js`:
    - Remove `modulesIdeaHub` from the `allCoreModules` array.
- In `tests/phpunit/integration/Core/Modules/ModulesTest.php`:
    - Remove all code blocks involving `ideaHubModule` and `Idea_Hub` class.
- In `tests/phpunit/integration/Core/Authentication/AuthenticationTest.php`:
    - Update the test case for the `filter_features_via_proxy()` method to remove all assertions of `ideaHubModule`.
- Delete the following directories and files:
    - `tests/phpunit/integration/Modules/Idea_Hub/`
    - `tests/phpunit/integration/Modules/Idea_HubTest.php`

## QA Brief

* Check dashboard/settings/widgets/banners - there is no sign of the idea hub module/service should remain
* All other functionality should remain the same 

## Changelog entry

* Remove the Idea Hub experimental feature.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked dashboard/settings/widgets/banners - there is no sign of the idea hub module/service. 
- All other functionality works as expected. 

@techanvil I assuming that the checks in the IB were completed as part of the CR? 

Just wondered if this needed a `QA:Eng` check.

**Comment by techanvil** [comment]
Hey @wpdarren, I can confirm the points in the IB were all checked at CR time.

For the sake of completeness I've taken a quick look at `develop` and can confirm there are no remaining references to "Idea Hub", "idea-hub" etc beyond what is expected.

As the following output shows, we have a handful of matches for "idea*hub" left in `.git`, `readme.txt`, and `vendor` - these are as expected.

![image](https://user-images.githubusercontent.com/18395600/208889845-5d45c24d-2a1c-4e00-bd50-eedbeb46a9a5.png)
