### ISSUE TITLE
Several PHP Deprecated warnings

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#6236]
## Bug Description

Hello,
I have encountered some warnings of PHP Deprecated, below:

- `Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /plugins/google-site-kit/includes/Core/Admin/Standalone.php on line 95`
- `Deprecated: filter_input(): Passing null to parameter #4 ($options) of type array|int is deprecated in /plugins/google-site-kit/includes/Core/Util/Input.php on line 64`
- `Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /plugins/google-site-kit/includes/Core/Authentication/Authentication.php on line 308`
- `Deprecated: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /plugins/google-site-kit/includes/Core/REST_API/REST_Routes.php on line 104`
- `Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /plugins/google-site-kit/includes/Core/Assets/Assets.php on line 909`

Is there a quick solution to these alerts? :-)

Thank you

Best regards

## Additional Context

 - PHP Version:  8.1.12
 - Plugin Version: 1.88.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kuasha420** [comment]
@sviluppomania Thanks for opening the issue. We are already working on this and hopefully will have these fixed in upcoming releases. See #5110 (related PR #5968) and #5998.

**Comment by sviluppomania** [comment]
@kuasha420 When will these errors be fixed?
