### ISSUE TITLE
Selectively clear web storage

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6237]
## Feature Description

Site Kit uses the browser's web storage (local, and primarily session storage) for its client side cache. Several actions then use a common utility to clear the storage, e.g. disconnecting or resetting. The current implementation is a bit overly heavy-handed as it clears these storage backends completely when the intention is really to clear _Site Kit's_ entries only – WP core and values from other plugins/themes, browser extensions, etc should be untouched.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should never clear web storage entries that do not use its naming conventions (i.e. entries it did not create)

## Implementation Brief

* `clearWebStorage` use should be replaced with `clearCache` from `api/cache`
* Remove the no longer used `clearWebStorage` utility in `util/standalone`

### Test Coverage

* No changes needed

## QA Brief

- Site Kit, along its lifecycle, stores different data in the browser storage, e.g. local storage, session storage, cookies, etc. These can be viewed using the `Application` tab in the browser developer tools.
- At different points in the lifecycle, e.g. resetting Site Kit, logging out, etc, the data in these browser storage are cleared.
- Currently, when clearing this data, Site Kit deletes all data stored for the site, even though it wasn't created/stored by Site Kit.
- This issue improves this deletion so that when Site Kit clears the data, it only deletes data added by Site Kit.
- Set up Site Kit.
- Open the `Application` tab in the browser developer tools, and verify that Site Kit has added some storage items to session storage.
- In the browser console, run the following code: `sessionStorage.setItem( 'test', '123456' ) `. Verify that a `test` session storage item has been added.
- Reset the Site Kit plugin.
- Verify that all the storage items added by Site Kit has been removed, but the manually added session storage item including other storage items not added by Site Kit still persists.

## Changelog entry

* Enhance web storage clearing to only remove Site Kit items.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by aaemnnosttv** [comment]
@nfmohit #6250 has been merged so this one can be resumed now 👍

**Comment by nfmohit** [comment]
This is back in CR now. Thank you for the heads-up, @aaemnnosttv!

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@nfmohit I've noticed that manually added storage item not getting remove which is correct but one Site kit storage value still persists.  Is this expected?

![image](https://user-images.githubusercontent.com/94359491/212897503-f4fb42b9-1194-4638-a722-fd7e41687c2d.png)

**Comment by nfmohit** [comment]
Thank you for raising your concern, @mohitwp.

I believe this is expected since in the latest version, this is persisted on reset.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @nfmohit .

- Verified on dev.
- Tested by using steps mentioned under QAB.
- All storage items from SK gets remove when user disconnect or reset site kit except manual entered data and other entries. 
- After reset when user gets redirect to splash screen then one google Sit kit entry gets added which is same as latest.


https://user-images.githubusercontent.com/94359491/212913484-0a1d0906-7b6e-4fa6-84bb-44e9f53b4e4e.mp4

**Comment by aaemnnosttv** [comment]
Thanks for flagging @mohitwp (https://github.com/google/site-kit-wp/issues/6237#issuecomment-1385346198) – we can enhance this in a follow up issue to avoid such leftovers, but as of right now this is expected.
