### ISSUE TITLE
Enhance client storage isolation between users

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6240]
## Feature Description

Site Kit uses a dynamic cache key for client side cache, which is SK version-specific as well and usually includes a hash based on the given arguments for its respective request.

While investigating #6237, one of the only things that kept us from using our existing API for clearing web storage is the [googlesitekit-base.js](https://github.com/google/site-kit-wp/blob/a1327c4f3c572a326d51fc6fe5e7c695e2859f98/assets/js/googlesitekit-base.js) entrypoint which currently only remains to attempt to respond to a logout action which would then clear the web storage.

This is the only thing that separates one user's client-side storage from another's on the same browser – this is a key detail.

Rather than attempting to respond to a logout action on the client, Site Kit should use a more reliable method to isolate the cache so that even if it were not cleared (e.g. due to some alternate logout method), there would be no possibility for cross contamination between users on the same browser.

If we can implement a better solution as described here, then the admin-wide `googlesitekit-base.js` should no longer be needed which would be a nice secondary benefit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All of Site Kit's client-side storage should be stored in a way which is specific to the current user's logged in session, site/blog ID, and current Site Kit version

## Implementation Brief

* Extend `googlesitekit-base-data` with a new `storagePrefix` key
	- The value can be a hash of the following values: 
		- The current user's `username` (`WP_User::$user_login`)
		- The current session `token` via `wp_parse_auth_cookie()` (This comes from `$_COOKIE` so this should be CLI-safe in case this is ever invoked in that context, even if it's not intended to. Tests, etc). The same token is available via the `logged_in` or `auth` cookies, but being specific about the `scheme` avoids touching other globals and `logged_in` should work for both ssl and non-ssl contexts so we can go with that.
		- The current blog ID via `get_current_blog_id`
	- These can be concatenated with a pipe before hashing as a single string (see `wp_generate_auth_cookie` for an example)
	- This would probably be fine as an md5 hash but there's no reason to not use something more secure as is done in `wp_generate_auth_cookie`
* Update the `api/cache` storage key prefix to append the new prefix provided via the addition to the base data object  
e.g. `googlesitekit_{version}_{storagePrefix}_`
	- The SK version is handy to keep separately as it is sometimes useful during development
	- This will produce a cache key like this one for an Analytics report request  
	```
	googlesitekit_1.88.0_9dbcfcbbeee5c6822ca326d550e50ec9d9c18b3e0d0c15ad49cb93001792e4b5_modules::analytics::report::3f5cf8b5b6bba07ba9ad92a255f5e000
	```
* It's worth noting that web storage does not have a limit on key length but an overall limit on the total size (keys + values) which is 5-10MB per origin
* Accumulating a large amount of storage should not be a problem as we primarily use `sessionStorage` which only persists as long as the browser session

### Test Coverage

* PHPUnit test coverage for this will not offer much value as the prefix is web specific and is only used on the front end
	- It's also probably not worth creating a hashing abstraction for testing this
* This should ideally be covered using a simple E2E test
	- "setup Site Kit" as if it were connected to the proxy
	- Use the utility `e2e/core/site/notifications` route to stub a dummy notification
	- Go to the SK dashboard
	- A request will be invoked for `core/site` notifications and cached
	- Use the utility `e2e/core/site/notifications` route to stub a **different** dummy notification
	- Delete all cookies – do not log out "normally" as this will trigger SK to clear web storage
	- Login and go to the SK dashboard again (this will create a new session token)
	- See different dummy notification
	- This same test should fail if run before these changes are made because the notifications will be served from web storage instead of fetching even though 

## QA Brief

* Should not introduce any visual changes.
* Verify everything that's cached locally  works as expected. (e.g. notifications, analytics report).
* Verify cache keys in the local storage, have individual prefixes for each login session.
  e.g. `googlesitekit_1.90.0_50c5363e438044070818e485ead11ed8_*` where the `50c5363e438044070818e485ead11ed8` part scoped to the user session.

## Changelog entry

* Enhance isolation of client-side storage between user sessions.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev.
- Tested by setting up new website.
- Verified all notifications and banner.
- Verified banner caching mechanism.
- Verified cache keys, in the local storage, have individual prefixes for each login session.

![image](https://user-images.githubusercontent.com/94359491/210572876-df934863-3b3c-49ae-b27d-322f18272bde.png)
