### ISSUE TITLE
Create the "Top traffic source" key metric widget tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6245]
## Feature Description

<img width="354" alt="Screenshot 2022-12-19 at 01 28 02" src="https://user-images.githubusercontent.com/1721319/210282971-08f5d246-a369-4fd8-b523-80968c4ed5fe.png">

- Refer to the widget tables in the [design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#bookmark=id.qz6oxctz8fe7) and the [PRD](https://docs.google.com/document/d/1JvJ2gKxaX2PcYOnmA3-xqz4hK_ZHxj8Rd0svq6S8tiU/edit#bookmark=id.w8o73hf5pz1f) explaining the sources of data and other details.
- [Figma mock for all widgets](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=3407%3A73377&t=mxlhDsRNGXcli8tk-0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component should be created for the 'Top traffic source' Key metric widget and should be displayed within the Key Metrics widget area if it is selected (based on #6257 and #6313).
  * The component should reflect the screenshot supplied above, see the Figma link above for more detail.
* The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
    * metric: `totalUsers`
    * dimension: `sessionDefaultChannelGroup`
* Values should be calculated as follows:
    * Display `totalUsers` from the query’s top result as a percentage of the overall `totalUsers`.
* The percentage change figure (with a red for negative or green for positive highlight) should be calculated based on the 'previous' period before the selected date range. 
* Existing GA4 datapoints and datastore infrastructure that is being added as part of the [GA4 Reporting Epic](https://github.com/google/site-kit-wp/issues/6253#workspaces/execution-5e185a810bd7fc358af69885/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTAxNTQyOQ) should be used where available.

## Implementation Brief
* Wait for #6244 to be merged.
* Modify the `assets/js/modules/analytics-4/components/widgets/TopConvertingTrafficSourceWidget.js` file which exports the `TopConvertingTrafficSourceWidget` functional component.
* Most of the styles should already be in place as a result of #6244. Similar to the `MetricTileNumeric` reusable widget component introduced in that issue, create a `MetricTileText` reusable widget which can be used for widgets where the metric value is textual (the change badge is also in a different location). This reusable widget can then be used by #6255 and #6246.
* To get the data for the component, use the following options:
    * metrics: `totalUsers`
    * dimensions: `sessionDefaultChannelGroup`
    * limit: `1`
    * orderBy: `totalUsers` (descending)
* Query the GA4 data store via the `getReport` selector with the metric and dimension as mentioned above.
    * To get the selected date range, query the `core/user` data store via the `getDateRangeDates` with `compare` set to `true`.
* To get the % change, compare the metric values for the current and previous date range and use the `ChangeBadge` component introduced in #6244 to display the percentage increase or decrease.
* To get the % of traffic compared to the total, use the value from `totals` and metric values for the current date range.
* Add stories for `TopConvertingTrafficSourceWidget` in `assets/js/modules/analytics-4/components/widgets/TopConvertingTrafficSourceWidget.stories.js`.

### Test Coverage
* Add tests for `TopConvertingTrafficSourceWidget`

## QA Brief

* With the `userInput` feature flag enabled, answer the questionnaire. For now, all widgets are displayed on the dashboard (which will change with future commits). As part of this issue, test the design and metric values of the `Top Traffic Source` widget rendered in the Key Metrics section.
* Test the generic `Metric Tile Text` and the specific `Top Traffic Source` stories within the Key Metrics widget section in Storybook.
* Note 1: The mobile version currently does not display Key Metric tiles in a single column. A new issue has been created for this.
* Note 2: There is a separate issue for the loading state.
* Note 3: Designing the error state for widget tiles is out of the scope of this issue. A new issue has been created.

## Changelog entry

* Implement the "Top traffic source" key metric widget.

**Comment by tofumatt** [comment]
ACs here look good, moving to IB 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by hussain-t** [comment]
A note for the implementation. The IB mentions creating a `TopConvertingTrafficSourceWidget` component. However, that conflicts with #6255 AC and should be created as part of it. According to the current issue's AC, the new component should be created as `TopTrafficSourceWidget`.

**Comment by marrrmarrr** [comment]
Hey @jimmymadon, sounds like our thinking aligns on this one - essentially, what I had in mind here is to show how this particular traffic source (which also happens to be the top traffic source for the time frame selected) has changed over time - so in the example screenshot it would be "Search brought you the most visitors this month (10%) and it's also growing compared to last month (9.1%)".

**Comment by marrrmarrr** [comment]
@eugene-manuilov absolute growth is much easier to understand for users than relative growth, so let's go with that (I'm assuming that's the case for other KMW metrics as well, for example the ones [here](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=1109-33837&t=4cTEEJ1fXM1ZrKDc-4
)).

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov @jimmymadon just two observations.

1. When a site is in zero data state, the percentage for this tile is in green, where as the other tiles and on Storybook it is grey, which is expected.  Is this something we need to fix? 

![image](https://github.com/google/site-kit-wp/assets/73545194/223fd5f1-5a46-444c-8b58-14a616c90a70)

2. Please see my note re the percentage not appearing to be correct - since we have a ticket to investigate this, I do not feel that this should hold us up approving this.  Thoughts? 

I wanted to highlight that this tile percentage is not calculating as per the Analytics report I created.  

The data below is for 28 days.

![image](https://github.com/google/site-kit-wp/assets/73545194/65ac567a-bd8b-47a4-bb2b-f85958b7255d)

1,845 Organic search / 2,343 Total users x 100 = `78.75%`

As you can see from the screenshot below, they don't match. Site Kit shows, 80.4% 

![image](https://github.com/google/site-kit-wp/assets/73545194/544cade6-1584-4b57-99c5-1a6a29e7ba8b)

**Verified:**

- The 'Top traffic source' Key metric widget and is displayed within the Key Metrics widget area.
  - The tile matches the see the Figma designs.
  - Tested the generic Metric tile text and the specific `Top Traffic Source` stories in Storybook.

**Comment by eugene-manuilov** [comment]
> 1. When a site is in zero data state, the percentage for this tile is in green, where as the other tiles and on Storybook it is grey, which is expected.  Is this something we need to fix?

Yeah, it looks strange. Maybe we should not display the change badge at all if there is no data? @jimmymadon what do you think?

> 2. Please see my note re the percentage not appearing to be correct - since we have a ticket to investigate this, I do not feel that this should hold us up approving this.  Thoughts?

Yes, we probably shouldn't block this task, but if Jimmy can look at it, that would be great.

**Comment by eugene-manuilov** [comment]
@jimmymadon, I approved and merged your PR. Could you please let @wpdarren know which problem your PR solves?
