### ISSUE TITLE
Remove `googlesitekit-base.js`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6250]
## Feature Description

https://github.com/google/site-kit-wp/blob/a1327c4f3c572a326d51fc6fe5e7c695e2859f98/assets/js/googlesitekit-base.js currently only exists to trigger web storage to be cleared when the user chooses to log out via the WP admin bar which will no longer be relevant after #6240 which is a more robust solution.

By removing `googlesitekit-base`, we can lessen Site Kit's footprint across all of wp-admin as this script is currently being enqueued on every admin page as part of `Assets::enqueue_minimal_admin_script`.

Other code that was only used in `googlesitekit-base` can also be removed such as `assets/js/util/standalone.js`. This way we can avoid using different utilities in different places to do the same thing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit-base` asset and its associated `googlesitekit-base.js` should be removed entirely
    * Its similarly-named data asset `googlesitekit-base-data` **should be preserved**
* Site Kit should no longer enqueue any assets across all WP admin

## Implementation Brief

* Delete `assets/js/googlesitekit-base.js`
* Remove `'googlesitekit-base'` from [entry files in webpack.config.js](https://github.com/google/site-kit-wp/blob/9ee628e3035bdfbd80099aa14afdb7cf91d73875/webpack.config.js#L335)
* In `includes/Core/Assets/Assets.php`
  * Delete the `enqueue_minimal_admin_script` function.
  * Remove the the registration of `enqueue_minimal_admin_script` inside the `register()` method.
  * Remove the registration of the `googlesitekit-base` script inside the `get_assets()` method.
  * Remove `googlesitekit-base` from `get_asset_dependencies()` method.

### Test Coverage

* Fix the failing test in `tests/phpunit/integration/Core/Assets/AssetsTest.php`

## QA Brief

* Smoke test the plugin to ensure there are no regressions as this issue does not have an UI changes. No new console errors should appear on the WP Dashboard or the SK plugin.

## Changelog entry

* Remove admin-wide base JS.

**Comment by aaemnnosttv** [comment]
IB ✅ 

This is a rather small change, but it will also likely require some additional general checks in QA so I'll bump this to a 7.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev.
- Done smoking testing of SK plugin.
- Set up Site Kit.
- Set up All Modules.
- Tested main and entity dashboard.
- Tested WP dashboard widgets.
- Tested GA4 activation banner.
- No console error found.
