### ISSUE TITLE
Create the "Top converting traffic source" key metric widget tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6255]
## Feature Description

<img width="379" alt="Screenshot 2022-12-19 at 01 39 05" src="https://user-images.githubusercontent.com/1721319/219649293-934800fa-c36f-4c25-84b8-7ba0abe67273.png">

- Refer to the widget tables in the [design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#bookmark=id.qz6oxctz8fe7) and the [PRD](https://docs.google.com/document/d/1JvJ2gKxaX2PcYOnmA3-xqz4hK_ZHxj8Rd0svq6S8tiU/edit#bookmark=id.w8o73hf5pz1f) explaining the sources of data and other details.
- [Figma mock for all widgets](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=3407%3A73377&t=mxlhDsRNGXcli8tk-0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component should be created for the 'Top converting traffic source' Key metric widget and should be displayed within the Key Metrics widget area if it is selected (based on #6257 and #6313).
  * The component should reflect the screenshot supplied above, see the Figma link above for more detail.
* The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
    * metric: `sessionConversionRate`
    * dimension: `sessionDefaultChannelGroup`
* Values should be calculated as follows:
    * Order by the `sessionConversionRate` metric and display the `sessionDefaultChannelGroup` with the highest conversion rate. Also convert the `sessionConversionRate` from a ratio to a percentage.
* The percentage change figure (with a red for negative or green for positive highlight) should be calculated based on the 'previous' period before the selected date range. 
* Existing GA4 datapoints and datastore infrastructure that is being added as part of the [GA4 Reporting Epic](https://github.com/google/site-kit-wp/issues/6253#workspaces/execution-5e185a810bd7fc358af69885/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTAxNTQyOQ) should be used where available. 

#### Creating the `TopConvertingTrafficSourceWidget` component

* Wait for #6244 and #6245 has been merged.
* Create `assets/js/modules/analytics-4/components/widgets/TopConvertingTrafficSourceWidget.js`, which exports the `TopConvertingTrafficSourceWidget` functional component.
* Most of the styles should already be in place as a result of #6245 - reuse the `MetricTileText` component that will be added in that issue.

#### Fetching the data and displaying it in the Widget

* To get the data for the component, use the following options:
    * metrics: `sessionConversionRate`
    * dimensions: `sessionDefaultChannelGroup`
    * limit: `1`
    * orderBy: `sessionConversionRate` (descending)
* Query the GA4 data store via the `getReport` selector with the metric and dimension as mentioned above.
    * To get the selected date range, query the `core/user` data store via the `getDateRangeDates` with `compare` set to `true`.
* To get the % change, compare the current and previous date range metric values and use the `ChangeBadge` component introduced in #6244 to display the percentage increase or decrease.
* To get the % of converting traffic compared to the total, use the value from `totals` and metric values for the current date range.
* Add stories for `TopConvertingTrafficSourceWidget` in `assets/js/modules/analytics-4/components/widgets/TopConvertingTrafficSourceWidget.stories.js`.

### Test Coverage

* Add basic test coverage for the `TopConvertingTrafficSourceWidget` component.

## QA Brief

* With the `userInput` feature flag enabled, answer the questionnaire. As part of this issue, test the design and metric values of the `Top converting traffic source` widget rendered in the Key Metrics section.
* To render the `Top converting traffic source` widget, run the following code on the browser console:
```js
await googlesitekit.data.dispatch('core/user').setKeyMetricsSetting('widgetSlugs', ['kmAnalyticsTopConvertingTrafficSource'] );
await googlesitekit.data.dispatch('core/user').saveKeyMetricsSettings();
```
* Verify the `Top converting traffic source` stories within the Key Metrics widget section in the Storybook.

## Changelog entry

* Create "Top converting traffic source" key metric widget tile.

**Comment by marrrmarrr** [comment]
@jimmymadon you're right, this should be a different dimension. Since we're talking about visits here, I'd guess "sessions" matches that better than "users", so how about using "[sessionDefaultChannelGroup](https://ga-dev-tools.google/ga4/dimensions-metrics-explorer/#sessionDefaultChannelGroup)", the same dimension that is used in the All Traffic widget? 

Regarding what we're trying to show here: highlight the traffic source which brought in the most conversions. So let's say for the given time period there were: 
- 100 visits from Organic search, 40 led to conversions
- 50 visits from Social, 40 led to conversions 
- 150 visits from Direct, 30 led to conversions 
So in this case we would highlight "Social" as the "Top converting traffic source" because 80% of visits led to conversions.  

Does this help?

**Comment by tofumatt** [comment]
ACs here look good 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

- As per Jimmy's comment above, the `Top converting traffic source` tile does not currently appear in the KMW.

**Comment by marrrmarrr** [comment]
@jimmymadon "top converting traffic source" is something we are not able to calculate yet, as we don't yet have conversions. (this will come eventually with V2 of KMW)
For now I'd suggest to have only "top traffic source" and "most engaged traffic source" in our metrics.

**Comment by bethanylang** [comment]
@jimmymadon Noting the Slack discussion here:

> is this widget ok to be in the User selected metrics list but not in any of the “recommended” sets?

@marrrmarrr:
> definitely, for sites which already have conversions set up this would pull some stats.

> From discussing with the GA team, they shared that under 10% of GA user have set up any events at all, so I’d guess the ones with conversions are an even smaller group

> so it’s not so much about the fact that Site Kit itself doesn’t create conversions yet, but that for most sites there won’t be anything to show

> the event creation and conversion upgrade on KMW will help a lot of users who don’t have the knowledge to set them up on their own to benefit from being able to measure them

**Comment by aaemnnosttv** [comment]
Even if this isn't used currently, it's still behind the feature flag and has already been merged so it need not hold up the release.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- the Top converting traffic source widget rendered in the Key Metrics section.
- checked figma designs to the tile on dashboard. 
- checked values on tile to Analytics (only Organic Social had conversions) 
- the `Top converting traffic source` stories within the Key Metrics widget section in the Storybook.

![image](https://github.com/google/site-kit-wp/assets/73545194/60bb1d60-b5f6-438c-917c-cfcedcd1ee9d)
