### ISSUE TITLE
Improve fetching key metrics based on user selected metrics

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6257]
## Feature Description

Clicking on the “I’ll pick metrics myself” secondary button within the setup banner or the “Change metrics” edit button on the Key metrics widget (after the question flow) will allow an authenticated admin to select their own metrics. In preparation of this functionality, a new selector should first check if the current user has picked their own metrics using the response of #6256. If not, then the answer based metrics from #6234 should be returned.

Refer to the [relevant section](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.vhwfv6130t0d) in the design doc for further context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new partial store (eg. file) within `core/user`, say `key-metrics`, should be created. 
* This store should define a new selector, say `getUserPickedMetrics()`. This selector should use the `core/user/data/key-metrics` REST endpoint to fetch the user's selected metrics, if any. 
* Another selector, `getKeyMetrics()` should be defined in the [~~same partial store~~](https://github.com/google/site-kit-wp/issues/6234#issuecomment-1415618948) `core/widgets` store, `key-metrics` partial. This selector should be defined as follows:
    * If the user has selected their own metrics, then an object with the `widgetSlugs` of those metrics should be returned (result of the `getUserPickedMetrics()` selector). 
    * If the user has not selected their own metrics, then the response from the selector defined in #6234 should be returned.

## Implementation Brief

- In `assets/js/googlesitekit/datastore/user/key-metrics.js` (being implemented in #6314):
    - Create a new variable named `fetchGetUserPickedMetricsStore` which will call the `createFetchStore()` function having an object as the parameter, with the following properties:
	    - `baseName` should be `getUserPickedMetrics`.
		- `controlCallback` should be a function calling the `API.get()` method with the following parameters:
		    - `core`
			- `user`
			- `key-metrics`
			- `undefined`
			- An object containing the `useCache` property with a `false` value.
		- `reducerCallback` should be a function having the parameters `state` and `keyMetrics`, and should return an object that spreads `state` (i.e. `...state`) and includes `keyMetrics`.
	- Create a new selector named `getUserPickedMetrics`. This selector should return the `keyMetrics` property value from the `state`.
	- In a new object named `baseResolvers`, create a new generator function as a resolver named `*getUserPickedMetrics`. This resolver should yield the `fetchGetUserPickedMetricsStore.actions.fetchGetUserPickedMetrics()` function only if the `getUserPickedMetrics()` selector (from the same store) returns a falsey value.
	- Update the `getKeyMetrics` selector (being implemented in #6314) to do the following:
	    - Call the `getUserPickedMetrics()` selector from the same store and assign it to a variable named `userPickedMetrics`.
		- If `userPickedMetrics` is available and its `widgetSlugs` array contains selected widgets, return the `widgetSlugs` array.
		- Otherwise, call the `getAnswerBasedMetrics()` selector being implemented in #6234 and return its response.

### Test Coverage

- In `assets/js/googlesitekit/datastore/user/key-metrics.test.js`:
    - Update test case(s) for the `getKeyMetrics` selector.
	- Add new test cases for the newly added selector and resolver.

## QA Brief

* The selector here should output user-selected key metric widgets, only if they are set. You could manually test this in the console, verifying the output of `googlesitekit.data.select( 'core/user' ).getKeyMetrics()` after:

```js
googlesitekit.data.dispatch('core/user').setKeyMetricSetting('widgetSlugs', ['some-widget-slug']);
googlesitekit.data.dispatch('core/user').setKeyMetricSetting('isWidgetHidden', false);
googlesitekit.data.dispatch('core/user').saveKeyMetrics();
// Output should be `['some-widget-slug']`.
googlesitekit.data.select( 'core/user' ).getKeyMetrics();
```

This should output the widget slugs specified in the first line.

To test the answer-based metrics, try:

```js
googlesitekit.data.dispatch('core/user').setUserInputSetting('purpose', ['publish_blog' ]);
googlesitekit.data.dispatch('core/user').saveUserInputSettings();
googlesitekit.data.dispatch('core/user').setKeyMetricSetting('widgetSlugs', []);
googlesitekit.data.dispatch('core/user').setKeyMetricSetting('isWidgetHidden', false);
googlesitekit.data.dispatch('core/user').saveKeyMetrics();
// Output should be `['kmAnalyticsLoyalVisitors', 'kmAnalyticsNewVisitors', 'kmAnalyticsTopTrafficSource', 'kmAnalyticsEngagedTrafficSource']`
googlesitekit.data.select( 'core/user' ).getKeyMetrics();
```

If `googlesitekit.data.select( 'core/user' ).getKeyMetrics();` is run before either dependencies are available, it should return `undefined`, but because it should trigger their selectors, should resolve afterward _if_ data is set on the server.

## Changelog entry

* Update the `getKeyMetrics()` selector to return the user-selected key metrics if set, otherwise the user input answer-based key metrics.

**Comment by tofumatt** [comment]
ACs look good here 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
#6234 should have been marked as one blocking this issue, so this probably shouldn't have been in the previous (or maybe even this) sprint.

I just noticed at the end of implementing this that the answer-based metrics selector isn't yet available. For now I've implemented the selectors/tests but am waiting on #6234 to be merged first. Once it's ready should just be another hour or less to wrap this one up 👍🏻

**Comment by tofumatt** [comment]
No worries, just wanted to highlight why it would be stalled for a bit! 😅

**Comment by bethanylang** [comment]
@tofumatt As discussed in Slack, I've removed this from Sprint 94 and will _not_ put it into Sprint 95 so that we can complete #6234 in Sprint 95 and pick this one back up, unblocked, in Sprint 96.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The selector outputs user-selected key metric widgets when they are set. 
  - Output is `['some-widget-slug']`.
- The same applies with the answer-based metrics.
  - Output is `['kmAnalyticsLoyalVisitors', 'kmAnalyticsNewVisitors', 'kmAnalyticsTopTrafficSource', 'kmAnalyticsEngagedTrafficSource']`
- If `googlesitekit.data.select( 'core/user' ).getKeyMetrics();` is run before either dependencies are available, it returns `undefined`, but resolves afterward if data is set. 

![image](https://user-images.githubusercontent.com/73545194/223639641-f1585518-7c4d-4382-8cdd-68740937abdb.png)
