### ISSUE TITLE
Can´t  Authenticate with Google

### ISSUE THREAD

**Issue by jmdfernandes** [google/site-kit-wp#626]
After going through the process and allow all the required permissions.it does not connect back to the Google kit  dashboard platform. Instead  sends to the normal wordpress dashboard.
Here I can see the follwing error :
<mark>Unknown Error (code: redirect_uri_mismatch)</mark>
![Google-kit-validation](https://user-images.githubusercontent.com/19510366/66268685-b0e2a700-e837-11e9-881e-aec95700e3bd.png)
![Google-kit-validation-error](https://user-images.githubusercontent.com/19510366/66268686-b17b3d80-e837-11e9-95bb-b801041d1e45.png)

**Comment by jamesozzie** [comment]
@jmdfernandes This could be similar to #338 or  #539. In order to resolve can you please check your WordPress site settings under "Settings > General" in your WordPress dashboard. Confirm your WordPress Address (URL) and Site Address (URL) match, and ensure they have a https prefix if you are using a https website. 

If you have already checked and both addresses match please share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard and we can troubleshoot further.

**Comment by jmdfernandes** [comment]
Hello James,

Thank you for your reply

This is my Site heath info which I have just copied

`

### wp-core ###

 

version: 5.2.3

site_language: en_US

user_language: en_US

permalink: /%postname%/

https_status: true

user_registration: 0

default_comment_status: open

multisite: false

user_count: 2

dotorg_communication: true

 

### wp-paths-sizes ###

 

wordpress_path: /home/holidaysxyz/public_html

wordpress_size: 11.23 GB (12058432999 bytes)

uploads_path: /home/holidaysxyz/public_html/wp-content/uploads

uploads_size: 8.18 GB (8784569254 bytes)

themes_path: /home/holidaysxyz/public_html/wp-content/themes

themes_size: 34.85 MB (36546263 bytes)

plugins_path: /home/holidaysxyz/public_html/wp-content/plugins

plugins_size: 402.62 MB (422177717 bytes)

database_size: 127.88 MB (134096550 bytes)

total_size: 19.96 GB (21435822783 bytes)

 

### wp-dropins (1) ###

 

advanced-cache.php: true

 

### wp-active-theme ###

 

name: Tour Package Child 01

version: 2.06

author: Goodlayers

author_website: (undefined)

parent_theme: Tour Package

theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, woocommerce, widgets, editor-style

theme_path: /home/holidaysxyz/public_html/wp-content/themes/tourpackage

 

### wp-themes (4) ###

 

Tour Package: version: 2.10, author: Goodlayers

Keepon Travel Child 01: version: 1.0.0, author: Phpscriptsmall

Keepon Travel: version: 1.0.0, author: Phpscriptsmall

Twenty Nineteen: version: 1.4, author: the WordPress team

 

### wp-plugins-active (67) ###

 

Archives Calendar Widget: version: 1.0.12, author: Aleksei Polechin (alek´)

Awesome Support: version: 5.8.0, author: Awesome Support Team

Awesome Support: Custom Status: version: 1.1.1, author: Awesome Support

Awesome Support: E-Mail Support: version: 5.7.3, author: The Awesome Support Team

Awesome Weather Widget: version: 2.0, author: Hal Gatewood

Better Search Replace: version: 1.3.3, author: Delicious Brains

BWL Advanced FAQ Manager: version: 1.7.9, author: Md Mahbub Alam Khan

CBX Currency Converter: version: 2.7.3, author: codeboxr

Checklist: version: 1.1.9, author: checklist

Classic Editor: version: 1.5, author: WordPress Contributors

Contact Form 7: version: 5.1.4, author: Takayuki Miyoshi

Contact Form 7 Captcha Pro: version: 0.0.1, author: 247wd

Contact Form 7 Datepicker: version: 2.6.0, author: Aurel Canciu

Currency Converter: version: 2.3.1, author: enclick

Drop-Down Post List: version: 1.33, author: Dagon Design

Duplicate Post: version: 3.2.3, author: Enrico Battocchi

DW Question Answer: version: 1.5.7, author: DesignWall

Easy Theme and Plugin Upgrades: version: 2.0.1, author: Chris Jean

Envato Market: version: 2.0.2, author: Envato

Flamingo: version: 2.1, author: Takayuki Miyoshi

Fullwidth Page Templates: version: 1.0.3, author: Brainstorm Force

Gift Cards Pro (Gift Vouchers and Packages) (WooCommerce Supported): version: 3.2.4, author: codemenschen

Google XML Sitemaps: version: 4.1.0, author: Arne Brachhold

Html Template for Contact Form 7: version: 1.0.0, author: Codeboxr Team

iframe: version: 4.4, author: webvitaly

Interactive Map of the World for WP: version: 2.9.8, author: Fla-shop.com

LayerSlider WP: version: 6.9.2, author: Kreatura Media

Lightbox Plus Colorbox: version: 2.7.2, author: Dan Zappone

List category posts: version: 0.81, author: Fernando Briano

Master Slider: version: 3.5.3, author: averta

MySiteAuditorCustomTemplate: version: 1.0, author: Marvin Russell

Newsletter: version: 6.2.2, author: Stefano Lissa & The Newsletter Team (latest version: 6.3.0)

Newsletter - Addons Manager: version: 1.0.9, author: The Newsletter Team

Peter's Login Redirect: version: 2.9.4, author: Peter Keung

Pinpoint Booking System PRO: version: 2.9.3, author: PINPOINT.WORLD

Popup Anything on Click Pro: version: 1.2.3, author: WP Online Support

Profile Builder: version: 3.0.5, author: Cozmoslabs

Q2W3 Fixed Widget: version: 5.1.9, author: Thomas Maier, Max Bond

Really Simple SSL: version: 3.2.5, author: Rogier Lankhorst, Mark Wolters

Redux Framework: version: 3.6.15, author: Team Redux

Rich Reviews: version: 1.7.3, author: Nuanced Media

Scroll Back to Top: version: 1.1.3, author: Joe Sexton

Simple Custom CSS: version: 4.0.2, author: John Regan, Danny Van Kooten

Simple Maintenance Mode Pro: version: 1.3, author: Jeff Bulllins

Site Kit by Google: version: 1.0.0-beta.1.0.7, author: Google

Spacer: version: 3.0.4, author: Justin Saad

The Events Calendar: version: 4.9.9, author: Modern Tribe, Inc.

The Events Calendar Shortcode & Block: version: 2.2.1, author: Event Calendar Newsletter

TinyMCE Advanced: version: 5.2.1, author: Andrew Ozz

TranslatePress - Automatic User Language Detection Add-on: version: 1.0.3, author: Cozmoslabs, Razvan Mocanu (latest version: 1.0.4)

TranslatePress - Multilingual: version: 1.5.9, author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

Travelpayouts: version: 0.7.13, author: travelpayouts

TripPlan: version: 1.0.10, author: checklist

UpdraftPlus - Backup/Restore: version: 1.16.17, author: UpdraftPlus.Com, DavidAnderson

User Role Editor: version: 4.52, author: Vladimir Garagulya

WordPress GDPR: version: 1.8.11, author: weLaunch

WordPress Importer: version: 0.6.4, author: wordpressdotorg

WP-Optimize - Clean, Compress, Cache: version: 3.0.12, author: David Anderson, Ruhani Rabin, Team Updraft

WP Cloudy: version: 4.4.7, author: Benjamin DENIS

WP Google Map Pro: version: 5.1.4, author: flippercode

WP Hide Title: version: 0.1.1, author: Riyad Arefin

WP Live Chat Support: version: 8.0.37, author: WP-LiveChat

WP Text Slider Widget: version: 1.0, author: Ugur CELIK

WP Travel: version: 3.0.5, author: WEN Solutions

WP Travel Partial Payment: version: 1.0.5, author: WEN Solutions

WP Travel Tour Extras: version: 1.1.2, author: WEN Solutions

WP Travel Utilities: version: 1.3.3, author: WEN Solutions

 

### wp-plugins-inactive (27) ###

 

Advanced Cron Manager: version: 2.3.9, author: BracketSpace

Advanced iFrame: version: 2019.7, author: Michael Dempfle

Advanced iFrame custom folder: version: 1.0, author: Michael Dempfle

BackupBuddy: version: 5.1.0.7, author: iThemes

Blank Slate: version: 1.1.4, author: Aaron Reimann

CBX Bookmark: version: 1.4.8, author: Codeboxr Team

CBX WP Bookmark Pro Addon: version: 1.1.3, author: Codeboxr

Contact Form 7 Captcha: version: 0.0.3, author: 247wd

Duplicator: version: 1.3.22, author: Snap Creek

Easy WP SMTP: version: 1.3.9.1, author: wpecommerce, alexanderfoxc

Link Checker: version: 1.18.0, author: Marco Beierer

malCure Malware Removal & Firewall: version: 4.2.1, author: Shivanand Sharma

Open Currency Converter: version: 1.4.4, author: David Artiss

Orbisius Child Theme Creator: version: 1.5.0, author: Svetoslav Marinov (Slavi)

Pagination by BestWebSoft: version: 1.1.7, author: BestWebSoft

TranslatePress - Browse as other role Add-on: version: 1.0.2, author: Cozmoslabs, Madalin Ungureanu

TranslatePress - Extra Languages Add-on: version: 1.0.1, author: Cozmoslabs, Razvan Mocanu

TranslatePress - Navigation Based on Language Add-on: version: 1.0.0, author: Cozmoslabs, Madalin Ungureanu

TranslatePress - SEO Pack Add-on: version: 1.1.6, author: Cozmoslabs, Razvan Mocanu

TranslatePress - Show Dynamic content before translation: version: 1.0.0, author: Cozmoslabs

TranslatePress - Translator Accounts Add-on: version: 1.0.2, author: Cozmoslabs, Cristian Antohe

Wordfence Security: version: 7.4.0, author: Wordfence

WordPress Post Tabs: version: 1.6.3, author: Internet Techies, Tejaswini Deshpande

WP GDPR Data Protection: version: 1.0.2, author: codemenschen

wp tell a friend popup form: version: 6.5, author: Gopi Ramasamy

WP Word Count: version: 3.1.0, author: Link Software LLC

Zero BS CRM: version: 2.99.9.8, author: Zero BS CRM

 

### wp-media ###

 

image_editor: WP_Image_Editor_GD

imagick_module_version: Not available

imagemagick_version: Not available

gd_version: bundled (2.1.0 compatible)

ghostscript_version: 8.70

 

### wp-server ###

 

server_architecture: Linux 2.6.32-042stab127.2 x86_64

httpd_software: Apache

php_version: 7.1.32 64bit

php_sapi: cgi-fcgi

max_input_variables: 1000

time_limit: 30

memory_limit: 256M

max_input_time: 60

upload_max_size: 6M

php_post_max_size: 8M

curl_version: 7.66.0 OpenSSL/1.0.2t

suhosin: false

imagick_availability: false

htaccess_extra_rules: true

 

### wp-database ###

 

extension: mysqli

server_version: 5.6.45

client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

 

### wp-constants ###

 

WP_HOME: undefined

WP_SITEURL: undefined

WP_CONTENT_DIR: /home/holidaysxyz/public_html/wp-content

WP_PLUGIN_DIR: /home/holidaysxyz/public_html/wp-content/plugins

WP_MAX_MEMORY_LIMIT: 256M

WP_DEBUG: true

WP_DEBUG_DISPLAY: false

WP_DEBUG_LOG: true

SCRIPT_DEBUG: false

WP_CACHE: true

CONCATENATE_SCRIPTS: false

COMPRESS_SCRIPTS: undefined

COMPRESS_CSS: undefined

WP_LOCAL_DEV: undefined

 

### wp-filesystem ###

 

wordpress: writable

wp-content: writable

uploads: writable

plugins: writable

themes: writable

 

`

**Comment by jamesozzie** [comment]
@jmdfernandes Can you temporarily deactivate the following plugins before resetting Site Kit ((Site Kit > Settings > Admin Settings > Reset Site Kit) and then proceeding with setup again?
- Updraft Plus
- The Events Calendar

If you are able to successfully activate Site Kit you can reenable those plugins. If that fails let me know the following:
- Are you encounter the same error (redirecting to dashboard) 
- Any [console errors](https://i.imgur.com/KyLAzgH.png) that appear

**Comment by jmdfernandes** [comment]
HelloJames,

I have deactivated the plugins as you suggested. However I could not activated the Google Kit

See the screenshot of the error

 

Thank you for all the help

Jose

**Comment by jamesozzie** [comment]
@jmdfernandes Can you attached the screenshot again, it wasn't successfully added to the thread. It could well be a dependency issue with one of your plugins which is causing the problem. You will see others reported similar issues at #584. For such issues there is an open issue being worked you can find [here, #620](https://github.com/google/site-kit-wp/issues/612).

**Comment by jmdfernandes** [comment]
Hi James,

 

Hope that it will attach now

Rgds

Jose

**Comment by jamesozzie** [comment]
@jmdfernandes Nothing added unfortunately. If it is an error message you can type it in here, along with copying and pasting and console errors. Or use a service such as https://prnt.sc/ to share yoyr screenshot via a link

**Comment by jmdfernandes** [comment]
Hello James,

 

This is the link

 

 <http://prnt.sc/pfz71m> http://prnt.sc/pfz71m

 

 

Rgds

Jose

**Comment by jmdfernandes** [comment]
Hello James,

 

No problem- But  see below- which other plugin???

**Comment by jamesozzie** [comment]
@jmdfernandes Thanks for the update, in order to troubleshoot further can you also temporarily deactivate the following plugins (along with Updraft Plus & The events calendar). These plugins use a Google PHP Client library, so there maybe be a conflict. 
- WP Cloudy
- WP Google Map Pro
- Pinpoint Booking System PRO

After deactivating please temporarily activate a default WordPress theme (such as Twenty Nineteen which you already have installed but not active). Please then try to activate Site Kit in an incognito window. 

If that fails please share any [console errors](https://i.imgur.com/f5WfLb3.png) you see on the error screen.

**Comment by jmdfernandes** [comment]
I have Deactivated the below plugins and open an incognito window. (http://prnt.sc/pg0sks )

Try to activate  Google Kit -  same Error persists

Unknown Error (code: redirect_uri_mismatch).

 

 

•             WP Cloudy

•             WP Google Map Pro

•             Pinpoint Booking System PRO

•             Updraft Plus

•             The events calendar

 

Rgds

Jose

**Comment by jamesozzie** [comment]
@jmdfernandes Thanks for the update. Can you also share any console errors on the same screen where you see that error?

**Comment by jmdfernandes** [comment]
Console screenshot

 

http://prnt.sc/pg15rl

**Comment by jamesozzie** [comment]
@jmdfernandes Are you encountering the same issue when you have Simple Maintenance Mode pro deactivated?

**Comment by jmdfernandes** [comment]
Hello James,

 

I have now tried to set up the plugin with  Simple Maintenance Mode pro deactivated.

Unfortunately  the error   “Unknown Error (code: redirect_uri_mismatch)”  still persists.

 

I have also created an extra credential at google platform specifically for the plugin ( <https://prntscr.com/plemnp> https://prntscr.com/plemnp  )

Still, no luck.

 

Please note:

This website is hosted by inmotionhosting.com on a VPS-2000HA-S.

I have other websites sharing this VPS.

I HAD NO PROBLEMS INSTALLING THE GOOGLE SITE KIT IN ANOTHER WEBSITE ON THE SAME  WHM panel

https://prntscr.com/plex6w 

 

All this is quite confusing and I do not know how to solve this issue.

Neither the support team at inmotionhosting

Regards

Jose

**Comment by jamesozzie** [comment]
@jmdfernandes Thanks for the update. From further inspection it seems as jQuery is being loaded via http, as opposed to https. That's causing a [mixed content issue](https://i.imgur.com/F4yr9D2.png), which in turn might be impacting your Site KIit setup. There could also be something in your .htaccess file or host setup causing the issue. 

If you can check whether your theme or any plugins request jQuery via http and change that to https then it's worth testing Site Kit setup again. 

Another option is to change the protocall in your WordPress Address (URL) and Site Address (URL) settings to http and then generate your OAuth credentials via accessing the following:
[https://developers.google.com/web/site-kit/?sitename=holidaysxyz&siteurl=http://holidays-xyz.com/](https://developers.google.com/web/site-kit/?sitename=holidaysxyz&siteurl=http://holidays-xyz.com/)

**Comment by jamesozzie** [comment]
Hi all, Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. Where we would be happy to assist from there
