### ISSUE TITLE
Implement settings toggle to show/hide the Key metrics widget

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6261]
## Feature Description

The new Key metrics admin settings area should have a new toggle to show or hide the Key metrics widget.

![Screenshot 2022-12-14 at 11 13 08](https://user-images.githubusercontent.com/1721319/207580718-0b19cc4a-f799-44d7-b0f9-d42aca6e8c78.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new toggle should be added to the Key metrics section on the Admin settings page as per the Figma mock if the Key metrics widget is setup for the current user, i.e.
    * If the user is an authenticated admin, then they would've answered the user input questionnaire.
    * ~~If dashboard sharing is enabled and the user is a view-only user, then at least one authenticated admin on the site has answered the user input questionnaire.~~ (A view-only user will not be able to reach the Admin Settings page and hence this point was unnecessary.)
* The setting value should be stored within the database on change. The action from #6314 can be used to store this value in the database.
* If the toggle value is false, the Key Metrics widgets should not be rendered on the dashboard. (It should be noted that in our existing infrastructure, the widgets "hide" themselves using their own state, and if there are no hidden widgets, the entire Widget Area is hidden. So this point should hide all widgets registered in the Key metrics widget area.)

## Implementation Brief
* Once #6314 and #6313 have been merged.
* Create `assets/js/components/settings/SettingsKeyMetrics.js` which exports the `SettingsKeyMetrics` functional component.
    * It should make sure of the `Switch` component with the label as per the designs in Figma.
    * The above should be rendered only if the user is an authenticated admin or if dashboard sharing is enabled and the user is view only.
        * To check if the user has been authenticated, query the user datastore via the `isAuthenticated` selector.
        * To check if dashboard sharing is enabled, use the `useFeature` hook, with `dashboardSharing` as parameter.
        * To check if it's view only mode, use the `useViewOnly` hook.
    * Toggling the `Switch` should dispatch the action defined in #6314 to save the setting to show/hide the key metrics widget.
* Update `assets/js/components/settings/SettingsAdmin.js` to include `SettingsKeyMetrics` before `UserInputPreview`.
* Update the widgets created in #6313 to render `null` if the settings to display the key metrics widget is `false` via the appropriate selector introduced in #6314.
* Add stories for `SettingsKeyMetrics` in `assets/js/components/settings/SettingsKeyMetrics.stories.js`.
* Style the `SettingsKeyMetrics` component as per the Figma designs.

### Test Coverage
* Add tests for `SettingsKeyMetrics`

## QA Brief

* Enable `userInput` feature flag.
* Don't answer User Input Questions.
* In Admin Settings, verify there is a `Key Metrics` section on top with a CTA to complete User Input questions and nothing else. 

* Case 1: Verifying toggle with User-defined Metrics
    * Without answering the User Input Questions, set user-defined key metrics using the following console code snippet.
    ```js
    (async () => {
    await googlesitekit.data.dispatch('core/user').setKeyMetricsSetting( 'widgetSlugs', ['kmAnalyticsTopTrafficSource', 'kmAnalyticsLoyalVisitors'] );
    await googlesitekit.data.dispatch('core/user').saveKeyMetricsSettings();
    })();
    ```
    * In Admin Settings
        * It should have a `Key Metrics` section on top.
        * There Should be a Key Metrics toggle switch as seen in the design. 
        * The User Input Set up CTA ("Personalize your metrics") should be under the switch. 
    * In Dashboard
        * Key Metrics Widget tile placeholders ("TODO: UI for xxxWidget") should load when the toggle is enabled and not load when the toggle is disabled in aforementioned settings. Note: The Old Banner Notification for User Input and the new Placeholder for the User Input Set up CTA ("TODO: UI for KeyMetricsSetupCTAWidget") will still be displayed which is fine for now.

* Case 2: Verifying toggle with Automated metrics
    * Reset Site Kit and reconnect. Then answer the user input questions. 
    * In Admin Settings, the Key metrics section will have the toggle.
    * In Addition to that, the user input CTA will be replaced by the User Input preview.
    * The Toggle should function as in Case 1 above. 

* Case 3: With User Input questions answered, run the above code snippet to manually set key metrics widgets. 
    * Everything should continue to behave as in the Case 2 section above. 

## Changelog entry

* Implement settings toggle to show/hide the Key metrics widget.

**Comment by tofumatt** [comment]
ACs are good aside from a typo that read:

> If the toggle value is **true**, the Key Metrics widget as whole should not be rendered on the dashboard.

I think that should **false**, so I updated the wording.

**Comment by asvinb** [comment]
@jimmymadon I feel the last point in the AC should be in a separate ticket (correct me if am wrong though) where we display the widgets based on the value of the checkbox. I feel the current issue should tackle only the checkbox and toggling the values in the admin settings. If not, do you have the link to the ticket where we actually create the widget?

**Comment by jimmymadon** [comment]
@asvinb Would this issue become too large if we incorporate the hiding of the widgets based on the value of the toggle? Since the Key metrics widget is not a single widget component, but rather a widget area having multiple widgets, we don't have a specific issue. Some relevant generic issues are: #6209 creates the widget area, #6313 registers all metric widget components and there is another umbrella issue #6242 which was supposed to focus on the layout of metrics within the widget area (which will not be necessary as we aren't making any layout changes to our Widgets API now). Not sure if this will fit into any of these issues - so maybe we can split this issue into two if you think that will be helpful in some way?

**Comment by asvinb** [comment]
I think that's fine @jimmymadon now that you've linked the associated tickets, this helps to get a better idea of all the tickets. Maybe the current ticket should be dependent of #6242

**Comment by asvinb** [comment]
@jimmymadon @aaemnnosttv A few UI related things I noticed:
* On the settings page, we are using checkboxes to toggle values for "Display relevant page stats in the Admin bar" and for tracking. Is there any reason why we are using the "Switch" component to toggle the values for showing the key metrics widget? I prefer to keep things consistent and use checkboxes.
* If we are going to use the Switch component, the label for the [switch should be to the right of the switch](https://google.github.io/site-kit-wp/storybook/main/?path=/story/global--switches). [In the designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1616%3A45227&t=KpVI2mhGxVmKhDJD-4), the label is to the left of the switch. We can use CSS to switch things around but it'll just add some unnecessary extra work and won't be consistent with other areas of the plugin where the Switch component is being used.

Let me know what you think.

**Comment by jimmymadon** [comment]
@asvinb This makes sense. One of the two checkboxes is very similar in purpose - "Display relevant page stats in the Admin bar". 

@marrrmarrr Could I please request your review here as it is a UI change and / or if you would want UX's input for this bit?

**Comment by marrrmarrr** [comment]
thanks @asvinb for pointing this out! 
@jimmymadon indeed it would be good if we align this functionality, let me pick this up with @sebastianmantel and Sigal and come up with a single pattern.

**Comment by sebastianmantel** [comment]
@asvinb Thanks for the feedback. I just changed the component to a checkbox to be consistent with the rest of the options in the UI. Let me know if you need anything else.

**Comment by sebastianmantel** [comment]
@asvinb @jimmymadon We just updated the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=866%3A22969&t=9Tw4RojkQLBSy6xv-1) file having the toggle component for turning on/off elements in the dashboard. Let us know if you have any questions.

**Comment by sebastianmantel** [comment]
@aaemnnosttv For the tracking settings, we will keep the checkbox as this is not turning off/on any component in the dashboard.

**Comment by tofumatt** [comment]
IB ✅

**Comment by kuasha420** [comment]
After a discussion with @jimmymadon, we have realized that the AC/IB needs a slight tweak which depends on the execution of #6257. So, I'll have this issue on hold for now until #6257 is merged and pick it up again afterwards. Keeping it assigned to me since I've worked on it but I'll move it back to EB. cc @bethanylang

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.
- Tested all cases mentioned under QAB.
- Verified toggle button design as per Figma mock.
- Verified case 1 and case 3 using the code snippet mentioned under QAB. 
- Verified when analytics is connected.
- Verified when analytics is not connected.
- Verified toggle button functionality in all 3 cases.
- Verified that when user input are not answered then in Admin Settings, there is a Key Metrics section on top with a CTA to complete User Input questions and nothing else.


@jimmymadon 

Question >  I tested this in both cases when analytics is connected and when it is not. As I remember if Analytics is not connected then we will not show Key metrics widget UI on dashboard and under settings. Let me correct if I'm wrong here. 
So, in the case when analytics module is not connected then we are showing Key metrics UI on dashboard and it is getting show and hide using the toggle button under admin settings. Only difference is that if analytics is not connected then we are not showing `"TODO: UI for KeyMetricsSetupCTAWidget"` . 
Is this case is expected for now ?

<details>

When analytics is connected 

![image](https://github.com/google/site-kit-wp/assets/94359491/1fb007a3-fa3d-4b42-b502-e06e2833ac7d)

When analytics is not connected

![image](https://github.com/google/site-kit-wp/assets/94359491/801774c1-54ab-493d-8a23-38108df31ced)

</details>


<details>

**Case 1 -**

![image](https://github.com/google/site-kit-wp/assets/94359491/7a15f753-b52f-477d-ba3b-ef459e039f07)


https://github.com/google/site-kit-wp/assets/94359491/d6937609-cae6-46ef-8f21-8030ea292d35

**Case 2**


https://github.com/google/site-kit-wp/assets/94359491/d009d354-1a89-48f2-a7d7-237ba0001242

**Case 3-** 


https://github.com/google/site-kit-wp/assets/94359491/9a9229f6-6058-4cfc-974c-d0e8940e9e17

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested all cases mentioned under QAB.
- Verified toggle button design as per Figma mock.
- Verified case 1 and case 3 using the code snippet mentioned under QAB. 
- Verified when analytics is connected.
- Verified when analytics is not connected.
- Verified toggle button functionality in all 3 cases.
- Verified that when user input are not answered then in Admin Settings, there is a Key Metrics section on top with a CTA to complete User Input questions and nothing else.

<details>

**Case 1 -**

![image](https://github.com/google/site-kit-wp/assets/94359491/7a15f753-b52f-477d-ba3b-ef459e039f07)


https://github.com/google/site-kit-wp/assets/94359491/d6937609-cae6-46ef-8f21-8030ea292d35

**Case 2**


https://github.com/google/site-kit-wp/assets/94359491/d009d354-1a89-48f2-a7d7-237ba0001242

**Case 3-** 


https://github.com/google/site-kit-wp/assets/94359491/9a9229f6-6058-4cfc-974c-d0e8940e9e17

</details>
