### ISSUE TITLE
Implement “Set your site goals” CTA button in admin settings when metrics have been picked

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6262]
## Feature Description

If the user has “manually” selected metrics by themselves on the dashboard using the "Select Key Metrics" panel from #6258, a new CTA "link" in the Key metrics settings panel which still encourages the user to answer the User Input questionnaire should be added, similar to the CTA displayed when the user has not set up the widget to begin with.

<img width="1788" alt="Screenshot 2022-12-14 at 13 05 25" src="https://user-images.githubusercontent.com/1721319/207603677-2660beac-050b-4164-ac2a-0ab43eca7522.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If an authenticated admin has **already selected their own metrics** and did not answer the user input questionnaire, then a CTA should be displayed in the Key metrics admin settings section as per this [Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1980%3A63901&t=bwOtTQ7S3Odzwt7u-0).
* The CTA should be a link (or a button with a link style) to the User Input questionnaire with the text "Set your site goals"
* Clicking on the CTA should begin the User Input questionnaire.

## Implementation Brief

* Once https://github.com/google/site-kit-wp/issues/6257 & https://github.com/google/site-kit-wp/issues/6261 have been merged:
* Create `assets/js/components/settings/SetGoalsCTA.js` which exports the `SetGoalsCTA` functional component.
    * Use `assets/js/components/notifications/CTA.js` to create a `Link` with text and style it as per [Figma Design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1980%3A63901&t=sDXoZNXZvPvpfm16-0) 
    * Use `getUserInputState` to check if user has selected goals 
    * Use `getUserPickedMetrics` to check if user has selected key metrics (`getUserPickedMetrics` is part of https://github.com/google/site-kit-wp/issues/6257)
    * Use `select( CORE_SITE ).getAdminURL( 'googlesitekit-user-input' )` to get a link to user goals questionnaire
    * Render `SetGoalsCTA` inside `SettingsKeyMetrics` (`SettingsKeyMetrics ` is part of https://github.com/google/site-kit-wp/issues/6261)
    * Add stories for `SetGoalsCTA` in `assets/js/components/settings/SetGoalsCTA.stories.js`

### Test Coverage

* Add tests for `SetGoalsCTA`

## QA Brief

* Enable the `userInput` feature flag and set up Site Kit.
* Don't answer User Input Questions.
* Go to the Admin settings page and ensure the Key Metrics section has the current CTA text `Personalize your metrics`.
* Set user-defined key metrics using the following code snippet in the browser console:
    ```js
    (async () => {
    await googlesitekit.data.dispatch('core/user').setKeyMetricsSetting( 'widgetSlugs', ['kmAnalyticsTopTrafficSource', 'kmAnalyticsLoyalVisitors'] );
    await googlesitekit.data.dispatch('core/user').saveKeyMetricsSettings();
    })();
    ```
* Refreshing the page may be required.
* Ensure the CTA has changed to `Set your site goals` along with the toggle switch, which was implemented in #6261 

**Follow-up fix**

- Test the settings Admin with `userInput` feature disabled to ensure [the error](https://github.com/google/site-kit-wp/issues/7136#issuecomment-1594519238) (or anything else related to user-input/key-metrics) is not triggered/visible

## Changelog entry

* Update the messaging for site goals in the Site Kit admin setting when user metrics have been selected.

**Comment by tofumatt** [comment]
I'm confused: doesn't clicking on the "Set your site goals" button open the side panel to edit the key metrics widgets that should appear on the dashboard?

Where is the CTA in this screenshot/in the Figma design? I don't see a User Input CTA, just the "Set your site goals" button that I'd expect would open the Key Metrics widget edit screen from #6258.

**Comment by tofumatt** [comment]
Ohhh, wait, I understand, that button IS the CTA but is for opening User Input if the user has already selected metrics. That didn't quite register but now I get it 👍🏻 

I'm just going to tweak the wording or highlight that case here so it's extra-clear, but ACs are good and I'll move this to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t I have a few observations:

I think these are likely not issues but would like confirmation. 

1. When I set up Site Kit, no user input questions appear after set up. Is that correct behaviour?  I am only questioning it because in the QAB it says `Don't answer User Input Questions` and previously when testing UserInput, they were appearing on set up, so want to make sure.  

This might be an expected change because admittedly, I am a little behind with changes on this epic so need to catch up!

2. In the QAB it says that the text should read `Set your site goal` but it reads `Set your site goals` which is matches the AC. I suspect it is just a typo but didn't want to assume. 

3. There difference in the figma design to what I see on my test site.   The text for the `Personalize your metrics` and `Set your site goals` CTA is different.  On Figma it is `Google Sans Display` but on my test site it is `Google Sans Text` 

![image](https://github.com/google/site-kit-wp/assets/73545194/1834849c-a516-42f8-ace6-25e8bf51545c)

**Verified:**

- On the Admin settings page the current CTA text `Personalize your metrics` appears. 
- When the user-defined key metrics are set, the CTA has changed to `Set your site goals` along with the toggle switch.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/5e66a189-a5b5-41af-80f2-0174e1dff1a4)
![image](https://github.com/google/site-kit-wp/assets/73545194/2191cba2-dcb9-419d-befb-616a0a016361)

</details>

**Comment by hussain-t** [comment]
Thanks @wpdarren. Regarding your observations:

>When I set up Site Kit, no user input questions appear after set up. Is that correct behaviour? I am only questioning it because in the QAB it says Don't answer User Input Questions and previously when testing UserInput, they were appearing on set up, so want to make sure.

>This might be an expected change because admittedly, I am a little behind with changes on this epic so need to catch up!

Yes, it was changed as part of #5900.

>In the QAB it says that the text should read Set your site goal but it reads Set your site goals which is matches the AC. I suspect it is just a typo but didn't want to assume.

Yes, that was a typo, my bad. I have updated the QAB.

>There difference in the figma design to what I see on my test site. The text for the Personalize your metrics and Set your site goals CTA is different. On Figma it is Google Sans Display but on my test site it is Google Sans Text

By default, we use the `Google Sans Text` font for all the links. It was not specific for this one.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On the Admin settings page the current CTA text `Personalize your metrics` appears. 
- When the user-defined key metrics are set, the CTA has changed to `Set your site goals` along with the toggle switch.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/5e66a189-a5b5-41af-80f2-0174e1dff1a4)
![image](https://github.com/google/site-kit-wp/assets/73545194/2191cba2-dcb9-419d-befb-616a0a016361)

</details>

**Comment by aaemnnosttv** [comment]
Reopening this one due to the error raised in settings when `userInput` is not enabled. https://github.com/google/site-kit-wp/issues/7136#issuecomment-1594519238

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- No errors appear in the console on admin settings or main/entity dashboard when `userinput` is disabled. 

Checked to make sure that the QAB passes when `userinput` is enabled.
- On the Admin settings page the current CTA text Personalize your metrics appears.
- When the user-defined key metrics are set, the CTA has changed to Set your site goals along with the toggle switch.

![image](https://github.com/google/site-kit-wp/assets/73545194/8ed06b06-31e9-484e-bed3-419dfb518cfb)
![image](https://github.com/google/site-kit-wp/assets/73545194/88f229f4-3fdb-4a16-a00f-ae91f1a6365a)
