### ISSUE TITLE
Remove `node_modules` cache steps in GHA

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6267]
## Feature Description

In #5786 we upgraded our node setup GitHub action to use the latest version which includes built-in support for caching `node_modules`. As part of this, dedicated caching steps were removed but some are still left behind (or were potentially reintroduced).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No GitHub workflows should use the `actions/cache` action directly to cache `node_modules`
    * this should be configured as part of the `setup-node@v3` action instead ([example](https://github.com/google/site-kit-wp/blob/a1327c4f3c572a326d51fc6fe5e7c695e2859f98/.github/workflows/e2e-tests-wp-latest.yml#L95))

## Implementation Brief

* Update all the `*.yml` files in the `.github/workflows` directory to use the `cache` option of the `setup-node@v3` action instead of the `actions/cache@v*` action.
* For example, see:
https://github.com/google/site-kit-wp/blob/a84f8ad455a1e9b099ef3b979e2fd6f1accf6266/.github/workflows/e2e-tests-wp-5-2.yml#L96
* Remove the `actions/cache@v*` action from all the `*.yml` files in the `.github/workflows` directory.

### Test Coverage

* No new tests are to be added.

## QA Brief

* Tech task. All functionality should remain the same. As part of QA:Eng, it should be verified that the Cache node modules are removed from the CI GitHub actions.

## Changelog entry

* N/A.

**Comment by kuasha420** [comment]
@hussain-t @aaemnnosttv Note that the `setup-node` only caches the global package cache and not the `node_modules` folder. However, that should be sufficient and caching `node_module` can be more wasteful in terms of time of the folder is too big. So this issue is definitely step in the right direction.

**Comment by techanvil** [comment]
> @hussain-t @aaemnnosttv Note that the `setup-node` only caches the global package cache and not the `node_modules` folder. However, that should be sufficient and caching `node_module` can be more wasteful in terms of time, if the folder is too big. So this issue is definitely step in the right direction.

Actually to clarify this, if you look at our "Cache node modules" steps they are in fact caching `~/.npm`, i.e. the global NPM cache, rather than `node_modules`.

We also run `npm ci` in our workflows so there would be no point caching the `node_modules` directory anyway.

**Comment by kuasha420** [comment]
@techanvil nice spot. I think part of the confusion came from we having similar steps with different names `name: Cache Node - npm` and `name: Cache node modules` which more or less did the same thing. :smile:

**Comment by techanvil** [comment]
Yep, the name confused me too, it will be good to remove these steps :)

**Comment by tofumatt** [comment]
Changing this to a 3 estimate as it's a pretty straightforward issue, but otherwise looks good.

IB ✅

**Comment by hussain-t** [comment]
Thanks @tofumatt, IMHO, it's better to keep it to 7 since we have to change it in multiple `*.yml` files and to avoid overages of execution time including CR and QA 🤷

**Comment by aaemnnosttv** [comment]
@hussain-t I don't usually advocate for a lower estimate, but in this instance I think 3 should be more than enough here. There's very little to actually change or review and QA should be QA:eng only and is essentially a secondary CR, so I agree with @tofumatt here.

**Comment by jimmymadon** [comment]
- Verified that all Github Actions do not use `actions/cache` for npm. (Currently only used for composer).

<Summary>
Screenshots:

<Details>
<img width="1484" alt="Screenshot 2023-01-06 at 01 09 08" src="https://user-images.githubusercontent.com/1721319/210909487-fd344de0-3209-4ddf-ae73-4a2a2625faa1.png">
<img width="1425" alt="Screenshot 2023-01-06 at 01 07 46" src="https://user-images.githubusercontent.com/1721319/210909490-229eaf94-d468-4a85-8175-8168c0b42193.png">
</Details>

</Summary>
