### ISSUE TITLE
Replace usage of "module" term in the UI with "service", for consistency.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6268]
## Feature Description

At the moment, when a user sets up Site Kit, they do so by connecting "services" in the Settings page.

![image](https://user-images.githubusercontent.com/18395600/205338250-6bf73509-fb00-42c0-87a8-c896327c8ed1.png)

Likewise, settings are edited for a "Connected Service".

![image](https://user-images.githubusercontent.com/18395600/205342111-bc552588-e6ca-42fd-b78f-b63584f75731.png)

However, we then start to refer to "modules" in some other parts of the UI, for example:

![image](https://user-images.githubusercontent.com/18395600/205339104-0c247823-4db9-4883-ad7a-f216b48d7722.png)

It seems unnecessary from a user perspective to use two terms for what appears to be the same thing. It also leads to added  complexity for documentation and support.

This issue is a proposal to simplify the terminology by only referring to "services" throughout the UI.

It should be straightforward to audit and update all usage of "module" in the UI by examining the generated POT translation file - see https://github.com/google/site-kit-wp/issues/5659 for how to generate one.

<details>
<summary>
Here is the current list of unique strings containing "module".
</summary>

```sh
$ egrep -h '^[^#].*module' languages/* | cut -d ' ' -f 2- | sort | uniq

"Analytics module needs to be configured."
"An internal error occurred while trying to activate the module."
"An internal error occurred while trying to deactivate the module."
"By disconnecting the %s module from Site Kit, you will no longer have access to:"
"By recovering the module, you will restore access for other users by sharing access via your Google account. This does not make any changes to external services and can be managed at any time via the dashboard sharing settings."
"By recovering the selected modules, you will restore access for other users by sharing access via your Google account. This does not make any changes to external services and can be managed at any time via the dashboard sharing settings."
"check module page"
"complete module setup"
"Contact %s to change who can manage view access for this module."
"continue module setup"
"Description of the module."
"Identifier for the module."
"Invalid module slug."
"Invalid module slug %s."
"List of slugs of other modules depending on the module."
"List of slugs of other modules that the module depends on."
"Looks like you’re already using Google Analytics within your Google Tag Manager configuration. Activate the Google Analytics module in Site Kit to see relevant insights in your dashboard."
"Name of the module."
"Recoverable modules"
"%s data was previously shared with other users on the site by another admin who no longer has access. To restore access, the module must be recovered by another admin who has access."
"%s data was previously shared with other users on the site by another admin who no longer has access. To restore access, you may recover the module as the new owner."
"Setup incomplete: <a>continue module setup</a>"
"%s module needs to be configured"
"%s module setup needs to be completed"
"The code is controlled by the Tag Manager module"
"The code is controlled by the Tag Manager module."
"The color of the supporter wall is based on the color theme you selected in the Thank with Google module settings."
"The data for the following modules was previously shared by an admin who no longer has access: %s. Please contact another admin to restore it."
"The data for the following modules was previously shared with other users on the site by another admin who no longer has access. To restore access, the module must be recovered by another admin who has access."
"The data for the following modules was previously shared with other users on the site by another admin who no longer has access. To restore access, you may recover the module as the new owner."
"The following modules failed to be recovered:"
"The module homepage."
"these active modules depend on %1$s and will also be disconnected: %2$s"
"The %s module cannot be set up as it has not been activated yet."
"Whether the module is active."
"Whether the module is internal, thus without any UI."
"Whether the module setup has been completed."
```

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
Thanks for this, @techanvil!

To clarify here from the support side, we worked with @marrrmarrr in the past to define the usage of these two terms, which you can see in our [documentation style guide](https://docs.google.com/document/d/1Xy52RYXMCl6DIIAbTR_DXcfIMDxxcb2YIpXLT37r-1s/edit?resourcekey=0-y3kiimSXlUoSJb7EzT-tXg#heading=h.j6brh7phifry). Essentially, "module" is the thing in Site Kit while "service" is the actual Google product that is being connected to.

I'd advocate for continuing to use this approach as it's important in support for us to have a distinction between the two. We find that using the same term for both (what's in SK vs. what's "outside" of SK) can get quite confusing, so having that separation is really helpful.

That said, I agree that there's confusion between the two within the product language that would be great to clean up based upon this distinction. Obviously want to hear @marrrmarrr's thoughts here!

cc @adamdunnage

**Comment by techanvil** [comment]
Thanks for the clarification there @bethanylang. I can certainly appreciate the point about having some distinction between Google services and Site Kit modules. From a user perspective though, I don't think it's so clear at the moment and the term "module" is used without really being explained, not via the UI at least. Interested to hear @marrrmarrr's thoughts on this too.

**Comment by adamdunnage** [comment]
@bethanylang @techanvil @marrrmarrr I'm not sure where exactly in the plugin we could explain this or even if we should but we could perhaps add a section to the documentation on this or even add it to the plugin page [FAQs section](https://wordpress.org/plugins/google-site-kit/#faq)?

**Comment by bethanylang** [comment]
@adamdunnage I don't think this is something that needs to be addressed/resolved in documentation at this point; it's really mainly a product issue, IMHO. Let's await @marrrmarrr's thoughts here and if there's anything to update documentation-wise, we can go from there!

**Comment by marrrmarrr** [comment]
We discussed this at length in an eng sync yesterday -- within the team, the two terms are clearly defined (as @bethanylang mentioned,  "module" is the thing in Site Kit while "service" is the actual Google product) and we use them correctly in the UI. 
Externally, there doesn't seem to be any confusion about this, so adding this to our docs would be basically "here's a question that's not frequently asked and you didn't know you had, but we've answered it" (: So I think we can close this for now, and potentially revisit if users raise this as confusing.
