### ISSUE TITLE
GA4 automatically enabled when editing Analytics settings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6271]
## Bug Description

The current release (1.88.0) introduced a regression in the behavior of the GA4 Analytics settings that affects users with Analytics connected but without GA4 connected.

When going to SK Settings > Analytics > Edit, the GA4 property field is enabled immediately. This should instead be a toggle that says "Activate Google Analytics 4 and place code on your site." that when toggled-on, enables the field. Canceling out of the settings edit view also resets this toggle.

It's worth noting that the correct state can be seen when reloading the page from the Analytics settings edit view.

## Steps to reproduce

1. Connect Analytics and delete GA4 settings
2. Go to Settings > Analytics > Edit
3. See the GA4 property select enabled 

## Screenshots

**Expected state** (perhaps also with a matched property)

<img width="725" alt="image" src="https://user-images.githubusercontent.com/1621608/205421002-7ff99fa4-90ef-4a92-afaf-586e22dbb444.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For users with `analytics` connected but not `analytics-4`, the property select for the GA4 property should only become enabled by one of the following actions (excluding activation banner)
    * Editing the settings and toggling on "Activate Google Analytics 4 and place code on your site."
    * Clicking the button in the settings header "Connect Google Analytics 4"

_Note 1.87.0 can be used for reference as to the proper behavior._

## Implementation Brief

* Remove this call to `setValues` from the `handleEdit` callback in `assets/js/components/settings/SettingsActiveModule/Footer.js`:

https://github.com/google/site-kit-wp/blob/2a24f57fd753b5f14ab7f6394971877409fcc619/assets/js/components/settings/SettingsActiveModule/Footer.js#L170-L175

### Test Coverage

* No new tests needed.

## QA Brief

* Set up Site Kit, including Google Analytics.
* Remove Google Analytics 4 from the site by removing the `googlesitekit_analytics-4_settings` row in the `wp_options` table in the WordPress MySQL database.
* Visit the Site Kit Settings page.
* Open Analytics Settings and click "Edit"
* Google Analytics 4 toggle should not be enabled.
* Enable the Analytics 4 toggle then click "Cancel" to exit edit mode.
* Click "Edit" to enter edit mode again
* Google Analytics 4 toggle should still not be enabled, as clicking "Cancel" should have reset the edit form state.

## Changelog entry

* Fix Google Analytics 4 settings toggle behaviour when GA4 is not connected.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

This passes the QAB, but an observation when you have more than one GA4 property for this account.   When I click on the toggle to enable Google Analytics 4, the other GA4 property is selected by default. At this stage I am unable to create a new GA4 property. When I save then the other GA4 property is set up on my site, as expected 

I am wondering if not being able to create a new GA4 property is correct?  This might be an issue outside of this ticket, but wanted to double check. 

https://user-images.githubusercontent.com/73545194/205669304-80006fd4-5875-44fe-a105-e20939341111.mp4

**Verified:**

- Google Analytics 4 toggle should is not enabled.
- When I enable the Analytics 4 toggle then click "Cancel" to exit edit mode, click "Edit" to enter edit mode again the toggle is still not be enabled, as clicking "Cancel" resets the edit form state.

![image](https://user-images.githubusercontent.com/73545194/205669577-7fa050c8-c13c-44c4-ad08-24c61ab0a821.png)

**Comment by aaemnnosttv** [comment]
> At this stage I am unable to create a new GA4 property because the dropdown is disabled.

@wpdarren This is a known issue and a regression that will be fixed in #5886 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Google Analytics 4 toggle is not enabled.
- When I enable the Analytics 4 toggle then click "Cancel" to exit edit mode, click "Edit" to enter edit mode again,the toggle is still not be enabled, as clicking "Cancel" resets the edit form state.

![image](https://user-images.githubusercontent.com/73545194/205669577-7fa050c8-c13c-44c4-ad08-24c61ab0a821.png)
