### ISSUE TITLE
Fix fatal error when running the E2E (WordPress 5.2, AMP 1.x) workflow.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6277]
## Feature Description

The **Start environment** step in the **E2E (WordPress 5.2, AMP 1.x)** workflow has recently started failing with the following error, causing the test run to fail:

> Fatal error: Array and string offset access syntax with curly braces is no longer supported in /var/www/html/wp-includes/script-loader.php on line 757

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/581b0fa0-ee33-4db9-8079-ae63a2bcb254)

Example run: https://github.com/google/site-kit-wp/actions/runs/3620129691/jobs/6102280425

It looks likely this is related to the curly braces syntax being fully removed in PHP 8.

> Support for deprecated curly braces for offset access has been removed.

See https://www.php.net/manual/en/migration80.incompatible.php

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The **E2E (WordPress 5.2, AMP 1.x)** workflow should run correctly.

## Implementation Brief

- Change the CLI image from `wordpress:cli` to `wordpress:cli-php7.4` in the E2E Docker Compose file:

https://github.com/google/site-kit-wp/blob/88823ba5455c4c94216415167204d06740834007/bin/local-env/docker-compose.yml#L35

### Test Coverage

* No new tests needed.

### QA:Eng
Note for code reviewers: To test this prior to merging, check out the branch, start the E2E environment up and verify it starts up successfully:

```sh
WP_VERSION=5.2.16 AMP_VERSION=1.5.5 npm run env:start
```

* Once merged, check the next run of the **E2E (WordPress 5.2, AMP 1.x)** workflow and verify it gets to the point of running the tests. The test suite will still fail until #6284 has been fixed.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
@aaemnnosttv, we are running the `wordpress:cli` image:

https://github.com/google/site-kit-wp/blob/88823ba5455c4c94216415167204d06740834007/bin/local-env/docker-compose.yml#L35

It's been updated recently, and the Dockerfile builds with PHP 8.0.26:

https://hub.docker.com/layers/library/wordpress/cli/images/sha256-c15c855681dfcd73f9473187b9adb7f946bfb576b38310ba84a221bf9fca8d4b?context=explore

This tallies with what I'm seeing locally:

![image](https://user-images.githubusercontent.com/18395600/205687116-8eb42a6a-8ccc-47db-b2da-af8a1adc0b93.png)

Looks like we should start using the [`wordpress:cli-php7.4`](https://hub.docker.com/layers/library/wordpress/cli-php7.4/images/sha256-9a1bb40df37cfe9c82b3d098a845b05f3586deefb696d1b59abcce3c269fb075?context=explore) docker image...

**Comment by aaemnnosttv** [comment]
Ah thanks. Looks like we still need an estimate here. I think 3 should probably be sufficient to make sure tests have time to run. 1 would probably be enough, but it touches E2E so that's about enough reason we need to bump it higher 😄 

IB ✅

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – looks like this did it. I reran E2E after merging this and the 5.2 job ran the tests, although still failing like the others for a different reason.

https://github.com/google/site-kit-wp/actions/runs/3641673392/jobs/6147887035

Moving to approval.
