### ISSUE TITLE
Styling Issues on Insufficient Permissions Message within Site Kit Admin toolbar 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6283]
## Bug Description

When an admin user does not have access to a module, i.e. Google Analytics, a message appears asking them to request access. On the Site Kit Admin bar, the same message appears but the styling is not providing a good user experience. Font sizes, colours, and CTA buttons are not consistent with the message that appears on the Site Kit Dashboard. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/00ae5284-7b77-4f20-a721-a7be2583bd7f)

## Steps to reproduce

1. Connect Site Kit and Google Analytics with Admin 1 
2. Login with Admin 2 and use a different Google account to connect Site KIt. 
3. Go to the Site Kit admin bar on the front end and observe the issue as per the screenshow.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* CTAs in the admin bar integration should appear consistent with CTAs on Site Kit screens

## Implementation Brief
* Using `assets/sass/components/adminbar/_googlesitekit-adminbar-overrides.scss`,
    * Add styles to `#wpadminbar .googlesitekit-adminbar .googlesitekit-cta--error` so that the widget on the WordPress front end is styled as the widget in the WordPress admin. Refer [to the story](https://google.github.io/site-kit-wp/storybook/main/?path=/story/components-reporterror--default-report-error) to see how the widget should be styled.
        * The padding, spacing, font sizes should be as per the story above.

### Test Coverage

* No tests to be added.

## QA Brief

1. Connect Site Kit and Google Analytics with Admin 1 
2. Login with Admin 2 and use a different Google account to connect Site KIt. 
3. Go to the Site Kit admin bar, the "error" widgets should look like this (eg. have correct styling/spacing):

<img width="419" alt="CleanShot 2022-12-13 at 19 18 21" src="https://user-images.githubusercontent.com/90871/207425042-82185e53-4a6d-45e1-a894-fa7fb4b1f318.png">

## Changelog entry

* Fix styling of some elements in the Site Kit admin bar metrics.

**Comment by aaemnnosttv** [comment]
@tofumatt I think he means WP backend as in wp-admin and FE as in non-wp-admin :)

**Comment by asvinb** [comment]
Sorry for the confusion here @tofumatt , I've updated the IB to avoid any confusion.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The "error" widgets look like the screenshots in the QAB with correct styling/spacing.
- Tested this on desktop and smaller screen sizes like mobile
- Tested this on our supported browsers.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/207571659-7d1b7db5-5be2-4a18-8dcd-c375191d240e.png)
![image](https://user-images.githubusercontent.com/73545194/207571681-dd8e937d-9dd3-449f-b809-edc9b5a2b25f.png)

</details>
