### ISSUE TITLE
Google: "Site Kit has risky access to your account"

### ISSUE THREAD

**Issue by JayHoltslander** [google/site-kit-wp#629]
Google is worried about Site Kit's access to my Google account.

![](http://cdn.holtslander.ca.s3-us-west-1.amazonaws.com/Screen-Shot-2019-10-07-at-8.03.42-PM.jpg)

![](http://cdn.holtslander.ca.s3-us-west-1.amazonaws.com/Screen-Shot-2019-10-07-at-8.01.22-PM.jpg)

**Comment by jamesozzie** [comment]
@JayHoltslander When you use Site Kit a new project is created and hosted on Google Cloud Platform. A Google account is therefore required for authentication and verification. As Site Kit is a WordPress plugin it acts as a third party between a Google account and the different Google products, you therefore need to approve access via that project. 

Looking at your screenshots I can see you have granted other applications third party access, I can see 11 others in total, which may have triggered a notice for you to review all third party applications/projects. You don't need to worry about granting Site Kit access, and you are free to [review the code](https://github.com/google/site-kit-wp) used. At the same time it's always good practice to check and review all applications you have granted access to your Google information.

**Comment by JayHoltslander** [comment]
@jamesozzie I understand all that. I just found it funny that Google is gmailing me about my Google account being at risk from a Google product.
