### ISSUE TITLE
Update bundled WP for tests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6290]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The bundled version of WordPress used for tests locally should be updated to the latest version, including test-related dependencies

## Implementation Brief

* Increase Composer's `platform.php` config to `5.6.20` as required by `roots/wordpress-no-content` (`roots/wordpress` is a metapackage that in turn requires this) – not sure if something in Composer changed regarding this or what because it won't select the package with the current version constraints due to our version using `5.6` which it sees as `5.6.0` rather than `5.6.*` which is not how the platform config works. See https://getcomposer.org/doc/06-config.md#platform
* Run `composer update roots/wordpress wp-phpunit/wp-phpunit --with-all-dependencies` (the flag only updates dependencies of the listed packages)

### Test Coverage

* No changes, this only affects local development
* Ensure `composer test` runs successfully locally

## QA Brief

* This change only really affects tests locally but could potentially cause a different package to be selected so the changes to the lock file should be reviewed as well as ensuring tests run locally via `composer test` (works for me!)

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
I've merged this and successfully run `composer install && composer test` on `develop`, there's nothing further to do from the QAB so I am moving this to Approval.
