### ISSUE TITLE
Lint and validate changes to GHA workflows 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6291]
## Feature Description

Workflows for GitHub Actions are defined with yaml, which can be fragile at times and harder to catch mistakes in others. Luckily there is an action which helps validate GHA syntax as well as other static analysis such as shellcheck for inline scripts for workflows that we can integrate to use to avoid introducing flaws in our configurations.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new GitHub action check should be added for validating GitHub action workflow definitions
* The check should run on pull requests that modify any `yml` files in the `.github` directory

## Implementation Brief

* Create a new `workflow-validation.yml` on `pull_request`, filtered by the same `branch` rules as other checks (main, develop, and feature branches)
    * Use the `paths` key to limit runs to only those that modify `.github/**.yml` files
* Define a job that uses https://github.com/rhysd/actionlint
    * The docs give a complete example using `reviewdog/action-actionlint@v1` which is nice in that it adds GitHub annotations to its runs for contextual feedback  
    See https://github.com/rhysd/actionlint/blob/main/docs/usage.md#reviewdog (this workflow is essentially everything we would add, just with a different name)
* Fix any errors flagged by the action

### Test Coverage

* An additional check will run for PRs that change GitHub action workflow definitions
* No other changes needed

## QA Brief

**This issue does not affect production code at all so only QA:Eng is relevant**

* This issue introduced a new check to ensure changes to GHA workflows are valid as well as some static analysis of inline scripts (uses shellcheck internally)
* Try opening a PR that makes changes to a GHA workflow that would be invalid and see that the check fails as expected

_Note this check only enforces changes on added/changed parts of a workflow in a PR_

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@sashadoes I've added a QA brief here – please keep in mind that just because an issue does not affect production code doesn't mean it shouldn't involve any QA 🙂

**Comment by hussain-t** [comment]
### QA:Eng Verified ✅ 
- Opened a PR that makes changes to a GHA workflow that's invalid and ensured that the check fails as expected
![Screenshot 2022-12-21 at 4 45 39 PM](https://user-images.githubusercontent.com/24408261/208897090-2a360547-b86b-404e-a0cf-56b42c53a876.png)
