### ISSUE TITLE
GA4 property select potentially shows wrong measurement ID for property

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6293]
## Bug Description

The GA4 module's property select component is unique in that it combines the selection of the property ID and measurement ID into a single choice. Since properties can have multiple web data streams (entity associated with the measurement ID), the corresponding web data stream for the current site needs to be identified to include in the list of choices.

We recently changed the property select to include the measurement ID (see #5145) in the choice to select from instead of the numeric property ID as the measurement ID is what the user will be more familiar with, and is somewhat equivalent to the property ID for Universal Analytics as it is what is included in the tag on the front end.

Due to an internal flaw, the measurement ID shown in the choice for a given property may not be the correct web data stream for the current site. While the choice is still applied properly, it makes for a very confusing experience for the end user as they may be attempting to select one measurement ID, only to see another in the settings view.

This only applies to properties with more than one measurement ID, and where the matching web data stream for a site is not the first.

## Steps to reproduce

1. Set up SK on a new site
2. Set up Analytics, and during setup choose an existing GA4 property from the list
3. Finish setup – you should be prompted to grant scopes to create the new web data stream for the chosen property
4. Navigate back to Analytics settings
5. Note the GA4 measurement ID in the **settings view**
6. Edit the settings
7. Note the selected GA4 property includes a different measurement ID than shown previously

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/206006566-cecd201d-8846-4e92-bdea-37929dc2a7c9.png)

<img width="363" alt="image" src="https://user-images.githubusercontent.com/1621608/206006555-d982b7b9-d5aa-4ba0-920a-42c4b0754b65.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The measurement ID shown in the GA4 property select's choices should always match a web data stream that has the same URL as the current site (see `getMatchingWebDataStream`)
	- For properties in the list that do not have a matching web data stream, the measurement ID should be omitted from the option's text, including wrapping characters/parentheses
	- The property select should remain in a loading state until related measurement IDs and matching are completed 

Note: this applies to all placements of the GA4 property select (i.e. in settings, setup, and activation banner)

## Implementation Brief

- In `assets/js/modules/analytics-4/datastore/webdatastreams.js`:
    - Rename the `getMatchingWebDataStream` selector to `getMatchingWebDataStreamByPropertyID`. Update all its usages across the codebase.
	- Create `getMatchingWebDataStream` as a new selector which should accept an array of web data streams and return a web data stream that matches with the current site. This selector:
	    - Should accept parameter named `datastreams` which is an array of web data steams.
		- Return `undefined` if the `datastreams` parameter is invalid (`undefined`, or not an array).
		- Copy over the logic for determining the matching web data stream from the `getMatchingWebDataStreamByPropertyID` selector.
	- In the `getMatchingWebDataStreamByPropertyID`:
	    - To ensure a "DRY" implementation, re-use the new `getMatchingWebDataStream` selector replacing the copied over logic, passing the value of the `datastreams` variable to it.
    - Update the `getMatchedMeasurementIDsByPropertyIDs` selector:
	    - We want to update this selector so that only measurement IDs that correspond to web data streams matching the current site are returned.
		- Before assigning the `measurementID` variable, create a new variable named `matchingDataStream` which should call the `getMatchingWebDataStream` selector from the `modules/analytics-4` store, passing `dataStream[ currentPropertyID ]` to it.
		- Return the accumulator (`acc`) (eg. don't add the measurement ID to the `acc`) if `matchingDataStream` is `false`y.
		- Re-assign `matchingDataStream.webStreamData.measurementId` to the `measurementID` variable.
- In `assets/js/modules/analytics-4/components/common/PropertySelect.js`:
    - In the unconditional `return` statement, inside the `<Option />` component, display `measurementIDs?.[ _id ]` inside parentheses only if `measurementIDs?.[ _id ]` is truthy.
	- Before assigning the `isLoading` variable, create a new variable named `propertyIDs` which should `map` over the `properties` array and create a new array containing each property ID (`property[ '_id' ]`).
	- Update the `isLoading` variable by adding a new condition besides the current condition. The new condition should call the `hasFinishedResolution` selector from the `modules/analytics-4` store, passing `getWebDataStreamsBatch` and an array containing the `propertyIDs` variable as parameters.
- In `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`:
    - Inside the `<Option />` component inside the `<Select />` component shown if `isDisabled` is truthy, display `measurementIDs?.[ matchedProperty._id ]` inside parentheses only if `measurementIDs?.[ matchedProperty._id ]` is truthy.

### Test Coverage

- In `assets/js/modules/analytics-4/datastore/webdatastreams.test.js`:
	- Update test cases for `getMatchingWebDataStreamByPropertyID` to reflect the naming change.
	- Add test cases for the new `getMatchingWebDataStream` selector.
	- Update test cases for `getMatchedMeasurementIDsByPropertyIDs` to reflect the above changes.
- Fix any other failing tests.

## QA Brief

- Follow the `Steps to reproduce` in the bug description and verify that the measurement ID displayed during property selection (in Settings Edit) and after saving (in Settings View) are identical.
- During property selection (in Settings Edit), if a certain GA4 property doesn't have a matching measurement ID, only the property name should be displayed omitting the parentheses.
- At no point should an empty parentheses be shown beside a property name. When the measurement IDs are being loaded, the loading progress bar should be shown.
- Go through the Analytics setup flow and verify that there are no other UI/UX regressions except for the ones mentioned above. Also, verify that there are no console errors.

## Changelog entry

* Fix presentation of measurement ID within options of the Analytics 4 property select.

**Comment by felixarntz** [comment]
@aaemnnosttv ACs mostly LGTM, maybe would be good to clarify that this needs to apply to both GA setup and settings? Also wondering, is it clear where/how exactly that notice should appear?

**Comment by aaemnnosttv** [comment]
> maybe would be good to clarify that this needs to apply to both GA setup and settings?

Good point! Will add.

> Also wondering, is it clear where/how exactly that notice should appear?

I was thinking we could use a similar component as we already have in setup when a UA property will be created but it could be that we need to show both of these which might look odd, but I feel like we should avoid creating multiple variants of that message and simply show multiple notices. What do you think?

**Comment by aaemnnosttv** [comment]
I was referring to this one in the setup:
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-setup-setupformga4--with-ga-4-tag

If the chosen primary property is a GA4 property, we show the notice that "An associated Universal Analytics property will also be created.", but in this situation, the chosen property also might not have a corresponding measurement ID for the site, which would also be created. I wasn't suggesting we add the notice for the create GA4 property scenario.

**Comment by felixarntz** [comment]
Ah okay, thanks for clarifying. Yeah in that case explaining that a web data stream will also be created may be helpful.

On second thought, I'm starting to think we maybe shouldn't make a premature decision as part of this. Arguably the wrong web data stream ID being shown is simply a bug, and we could also decide to keep this simple, as just a fix for the bug (i.e. not have the notice as part of the ACs). Since we need to kickstart a conversation to revise the web data stream behavior overall anyway, I think it may be better to for now only fix the bug itself.

**Comment by aaemnnosttv** [comment]
Sure, that makes sense. So you're suggesting we remove the part of the AC here about the added message and just leave off any non-matching measurement ID?

**Comment by felixarntz** [comment]
> Sure, that makes sense. So you're suggesting we remove the part of the AC here about the added message and just leave off any non-matching measurement ID?

Yes that's what I mean. :)

**Comment by nfmohit** [comment]
@tofumatt Assigning this back to me for a few slight updates to the IB. I'll send it back to you for IBR as soon as I'm done. Thanks!

**Comment by tofumatt** [comment]
@nfmohit Once I looked in the code I got it, but for the IB, I couldn't quite find what this refers to:

> Return the accumulator (`acc`) if `matchingDataStream` is false`-y.

That bit of the IB seems a bit out-of-place/without context. But once I looked at the file it made sense. I updated the IB to just give a bit more context there.

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified** -

- Tested on dev.
- Verified analytics setup.
- Verified GA4 set up through GA4activation banner.
- Measurement id under settings and edit settings view are now matching.
- If GA4 property doesn't have a matching measurement ID then only property name is displaying.
- Empty parentheses are not showing beside a property name.
- When the measurement IDs are being loaded, the loading progress is showing.
- No console errors found.


<details>

![image](https://user-images.githubusercontent.com/94359491/207835535-741d6d2b-6bb8-430b-a327-5260439d1681.png)


https://user-images.githubusercontent.com/94359491/207835588-7e50bc3e-87d1-45ce-8912-88dd3269d29a.mp4


https://user-images.githubusercontent.com/94359491/207835630-28085290-b810-46b8-9516-a4d5eef09b87.mp4


https://user-images.githubusercontent.com/94359491/207835706-ff6799db-e307-421b-9b7f-fcb53d61f8c5.mp4

</details>

**Note** : GA4 Activation banner > If selected property don't have matching measurement ID and user don't have OAuth scopes permission, then on returning from OAuth permission screen when user connects the property id. Then analytics 4 error—displays - `"Requested property already exists".` Same happens on Latest also. I think it is expected, but sharing here.

<details>

![image](https://user-images.githubusercontent.com/94359491/207836964-80f442bc-40c8-4172-96bf-c02664707f89.png)


https://user-images.githubusercontent.com/94359491/207838039-2001dc6e-34b9-4f84-af35-e043b18e360c.mp4

</details>

cc @aaemnnosttv

**Comment by felixarntz** [comment]
@mohitwp Checking on your above feedback: I see there's a ton of entries that are all the same (`oi.ie`). Is that because you have a ton of these properties in Analytics that all have the same name? Or is this a potential bug that causes us to see duplicates?

**Comment by felixarntz** [comment]
Thanks @mohitwp!

@aaemnnosttv The above leads to another concern with the current approach: By showing the measurement ID (which may not exist), we can run into this scenario where a ton of similar entries are present. This is naturally avoidable by displaying the property ID instead, which will always be set.

I believe this will be addressed by what we discussed yesterday for the revised web data stream handling in a separate dropdown anyway, but wanted to flag it as an additional problem that would be resolved by it.

**Comment by aaemnnosttv** [comment]
> The above leads to another concern with the current approach: By showing the measurement ID (which may not exist), we can run into this scenario where a ton of similar entries are present. This is naturally avoidable by displaying the property ID instead, which will always be set.

@felixarntz Yes, that is admittedly not good and would indeed be addressed by https://github.com/google/site-kit-wp/issues/6330. Let's prioritize that one; perhaps we can get it into the next release?

**Comment by bethanylang** [comment]
:wave: @aaemnnosttv @felixarntz I've added #6330 to Sprint 92 (for the 1.92.0 release). Thanks for the heads up!
