### ISSUE TITLE
Add server-side setting sanitization for `googleTagAccountID` and `googleTagContainerID`.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6307]
## Feature Description

As part of https://github.com/google/site-kit-wp/issues/6077, sanitization for the `googleTagID` setting was added to the `Modules::Analytics_4::Settings::get_sanitize_callback` method to default the value to an empty string when invalid. However, the `googleTagAccountID` and `googleTagContainerID` settings were introduced at the same time, but not added to `get_sanitize_callback`. This seems a bit inconsistent and it would be an improvement to ensure all of these settings are sanitized.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics 4 `googleTagAccountID` and `googleTagContainerID` settings should be sanitized on the server-side so they are stored as an empty string when an invalid value is provided.

## Implementation Brief

- In `includes/Modules/Analytics_4/Settings.php`:
    - Update the `get_sanitize_callback()` method. Inside the block of code that checks `$option` is an array, after the existing conditions for other setting fields:
	    - Check if `googleTagAccountID` property in the `$option` array is set. If it is set, check if its value is numeric that is greater than 0. If that is not the case, update its value to be an empty string.
	    - Check if `googleTagContainerID` property in the `$option` array is set. If it is set, check if its value is numeric that is greater than 0. If that is not the case, update its value to be an empty string.

### Test Coverage

- In `tests/phpunit/integration/Modules/Analytics_4/SettingsTest.php`:
    - Add test case(s) to validate `googleTagAccountID` and `googleTagContainerID` according to the above changes, similar to the test case(s) for validating `googleTagID`.

## QA Brief

* Check that implementation satisfy requirements in AC

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@techanvil ACs ✅

**Comment by eugene-manuilov** [comment]
IB ✔️
