### ISSUE TITLE
Translations of dashboard widget content missing

### ISSUE THREAD

**Issue by strarsis** [google/site-kit-wp#6312]
## Bug Description
The translations are missing (`de_DE_formal` with `de_DE` fallback) in the Google Site Kit dashboard widget.
The JSON translation files were downloaded, other translations work correctly in the backend.
The title of the widget itself is translated correctly, but not the widget contents.

## Steps to reproduce

1. Install and enable Google Site Kit plugin.
2. Install plugin translations.
3. Set Google Site Kit up so far that the Google Site Kit dashboard widget becomes available.
4. Show the Google Site Kit Dashboard Widget, note that the translations are missing and the (English) source strings are displayed instead. Only the widget title is translated.

## Screenshots
![c131af6e-e166-4bc5-a38e-f1996302cec4](https://user-images.githubusercontent.com/9271436/206923869-0ec52ece-7b4a-4412-b76d-607e925bc426.png)

## Additional Context

 - PHP Version: `7.4`
 - OS: `Ubuntu LTS`
 - Browser: `Chrome`
 - Plugin Version: `1.89.0`
 - Device: Windows 10 PC

Only the widget title is translated string that is actually stored in a `mo` (Gettext) file, instead of a JSON file.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hello @strarsis thanks for bringing this to our attention. We don't provide support through GitHub but would be happy to help look into this if you could [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) for this.

When creating the topic could you also let us know if translations were working previously for you? We have seen this happen in the past when some users have updated the plugin to the latest release for example.

I will close this issue out here but should we need to reopen after further testing then I will do so.
