### ISSUE TITLE
Register the new key metric widgets

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6313]
## Feature Description

In order to fetch/render the details of all available key metric widgets, we need to register them first. Since all widgets within the key metrics widget area do not depend on a single module, they can be registered within `assets/js/googlesitekit/widgets/register-defaults.js`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Every individual Key Metric widget should be registered within `assets/js/googlesitekit/widgets/register-defaults.js`.
* Every widget should be registered in the newly defined key metrics widget area (`AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY`).
* The slug for each widget should be copied from [this Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t). The same table also denotes the dependant modules that need to be connected in order for that widget to be "available for rendering".
* Create an empty skeleton component for each widget which will be implemented in their respective issues.
* Widths should be set to `widgets.WIDGET_WIDTHS.QUARTER` while `wrapWidget` will always be false.
* The result of this should correctly return the "available widgets" when calling the `getWidgets` selector from `core/widgets`. 
    * For authenticated admins, this should be all widgets whose dependant modules are connected. 
    * If dashboard sharing is enabled, and the logged in user has view-only access only, this should be all widgets that the user has access to. 

(Note: The "Priority" of widgets is not important but we can have a "default" order which will make the order of widgets predictable.)

## Implementation Brief

* In `assets/js/components/KeyMetrics` (`KeyMetrics` folder will be created in #6209. If that's not merged, create the folder), create a new folder `widget-tiles` and create the following components within it:
  * `AnalyticsLoyalVisitorsWidget` for the slug `kmAnalyticsLoyalVisitors`
  * `AnalyticsNewVisitorsWidget` for the slug `kmAnalyticsNewVisitors`
  * `AnalyticsTrafficSourceWidget` for the slug `kmAnalyticsTrafficSource`
  * `AnalyticsEngagedTrafficSourceWidget` for the slug `kmAnalyticsEngagedTrafficSource`
  * `AnalyticsPopularContentWidget` for the slug `kmAnalyticsPopularContent`
  * `AdsenseTopEarningContentWidget` for the slug `kmAdsenseTopEarningContent`
  * `AnalyticsPopularProductsWidget` for the slug `kmAnalyticsPopularProducts`
  * `SearchConsolePopularKeywordsWidget` for the slug `kmSearchConsolePopularKeywords`
  * `AnalyticsTopCitiesWidget` for the slug `kmAnalyticsTopCities`
  * `AnalyticsTopCountriesWidget` for the slug `kmAnalyticsTopCountries`
  * `AnalyticsConversionWidget` for the slug `kmAnalyticsConversion`
  * `TopConvertingTrafficSourceWidget` for the slug `kmTopConvertingTrafficSource`
* Refer to the [Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t) for the slugs as they might change in the future.

#### Register the widgets

* In `assets/js/googlesitekit/widgets/default-areas.js`, add new widget area constant `AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY` with the value `mainDashboardKeyMetricsPrimary`.
* In `assets/js/googlesitekit/widgets/register-defaults.js`, register the following widgets using the `widgetAPI.registerWidget` method:
  * Register a widget for each widget component created above.
  * The `slug` should be the slugs mentioned above.
  * The `settings.Component` should be the components mentioned above.
  * The `settings.width` should be `widgets.WIDGET_WIDTHS.QUARTER`.
  * The `settings.wrapWidget` should be `false`.
  * The `settings.priority` should be `1` for now. This can be changed later.
  * The `settings.modules` should be the dependent modules for each widget. This can be found in the [this Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t).
  * The `widgetAreaSlugs` should be an array containing `AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY`.
* Ensure all the widgets are registered correctly by calling the `getWidgets` selector from `core/widgets` by passing `AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY` as the argument. The result should be an array of all the widgets registered above.

Note: It's also potentially a good idea to register the widget in the `KeyMetrics` directory, similar to other modules. However, this is what is mentioned in the AC.

### Test Coverage

- No new tests are to be added.

## QA Brief

- Execute the `getWidgets` selector from `core/widgets` store from the browser console:
```js
googlesitekit.data.select('core/widgets').getWidgets('mainDashboardKeyMetricsPrimary')
```
- Ensure all the widgets are registered correctly with their slug by comparing [the Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t) with the result of the above selector.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
> (Note: The "Priority" of widgets will not be very helpful since the order of widgets will be different based on the answer to the user input questionnaire's question.)

This makes sense, but what's the plan for changing the order of the widgets on-the-fly? My understanding is `priority` can't really be set/changed after… or at least we don't have the ability to right now.

I didn't see any mention of that in the design—since each widget will be registered individually it'd be good to figure that out, I'd think it belongs here but maybe that logic/figuring out should go elsewhere 😄

**Comment by jimmymadon** [comment]
@tofumatt As discussed in our sync, for now we can ignore the order and iterate on this later in a separate issue if necessary.

@marrrmarrr Is the order in which metric tiles are displayed important? 

c.c. @aaemnnosttv

**Comment by marrrmarrr** [comment]
@jimmymadon As long as the widgets are not empty (an "Add a metric" tile), it doesn't matter in which order they're displayed. Would be strange if the first tile in the row was an empty one.

**Comment by tofumatt** [comment]
> (Note: The "Priority" of widgets will not be very helpful since the order of widgets will be different based on the answer to the user input questionnaire's question.)

Let's remove this part from the ACs because the order can be handled in another place, though for now it's probably fine to specify a default order for each just so they appear in a predictable order for each render. I think they can just appear in the order they'd appear in the select when none are selected, if that works?

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
> The result of this should correctly return the "available widgets" when calling the `getWidgets` selector from `core/widgets`.
> * For authenticated admins, this should be all widgets whose dependant modules are connected.
> * If dashboard sharing is enabled, and the logged in user has view-only access only, this should be all widgets that the user has access to.

@hussain-t we also need to add this to IB. See the design doc regarding dashboard sharing conditions: https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.o4lll9gj1sav

**Comment by hussain-t** [comment]
@eugene-manuilov that will be handled by the `WidgetAreaRenderer` component.

**Comment by eugene-manuilov** [comment]
Ah... okay, thanks, for clarifying that, @hussain-t. IB ✔️

**Comment by eugene-manuilov** [comment]
@hussain-t @jimmymadon left a [comment](https://github.com/google/site-kit-wp/pull/6499#discussion_r1091059223) in the PR. Could you please take a look?

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t this is looking good other than one metric that doesn't appear:

`Top performing keywords (queries with highest CTR)` with a slug of `kmSearchConsolePopularKeywords`

I set up Site Kit so Search Console is connected. 

Please could you confirm if it should appear at this stage? It would seem so based on the IB.

**Comment by hussain-t** [comment]
@wpdarren, it should appear, as you can see in the screenshot. Could you post a screenshot of what you get when you execute the selector?
![Screenshot 2023-02-01 at 11 02 50 PM](https://user-images.githubusercontent.com/24408261/216119361-2ec5bf7b-236f-434b-b6bf-4235b2cdf9ee.png)

**Comment by wpdarren** [comment]
@hussain-t oh, that is very odd.   I just refreshed the dashboard and ran the console code again and it's now appearing. 🤦  Please ignore me. I think we're good here.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When the console code is run:
- All the widgets are registered correctly with their slug from [the Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t) with the result of the selector.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/216121435-ef3b6212-6a22-4499-a06f-06defe33bf5b.png)
![image](https://user-images.githubusercontent.com/73545194/216121462-61870557-ea0f-44f2-b30a-f606d6d223b3.png)

</details>

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

I have moved this ticket back to QA.  When 6519 is merged. I would like to test this again with the `userinput` feature flag enabled and disabled.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

With the `userInput` feature flag enabled:
When the console code is run:
- All the widgets are registered correctly with their slug from [the Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t) with the result of the selector.

With the `userInput` feature flag disabled
When the console code is run, nothing appears in the console. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/216121435-ef3b6212-6a22-4499-a06f-06defe33bf5b.png)
![image](https://user-images.githubusercontent.com/73545194/216121462-61870557-ea0f-44f2-b30a-f606d6d223b3.png)

</details>
