### ISSUE TITLE
Store user selected key metrics and show/hide widget toggle in settings

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6314]
## Feature Description

This issue should create the datastore infrastructure necessary to save the user-selected metrics in persistent storage in the WordPress database, using the POST REST endpoint created in #6256.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Appropriate datastore infrastructure (action/control/reducer, using `createFetchStore`) should be created to call the POST endpoint from #6256 to store an object of user picked metric widget slugs as well as the `isWidgetHidden` setting flag in the database.

## Implementation Brief

- Wait until #6256 is merged.
- In the `assets/js/googlesitekit/datastore/user` folder, create a new file named `key-metrics.js`. In this file:
    - We will create the necessary action & selector to call the `POST` endpoint of the `core/user/data/key-metrics` route (being implemented in #6256). To get an idea of how this will look at the end, we can take a look at `assets/js/googlesitekit/datastore/user/feature-tours.js` or `assets/js/googlesitekit/datastore/user/user-input-settings.js` as examples.
	- Create a new object named `baseInitialState` having the property `keyMetrics` with an `undefined` variable.
	- Create a new variable named `fetchSaveKeyMetricsStore` which will call the `createFetchStore()` function having an object as the parameter, with the following properties:
	    - `baseName` should be `saveKeyMetrics`.
		- `controlCallback` should be a function having a parameter named `settings`, and should call the `API.set()` method with the following parameters:
		    - `core`
			- `user`
			- `key-metrics`
			- An object containing the received `settings` parameter.
		- `reducerCallback` should be a function having the parameters `state` and `keyMetrics`, and should return an object that spreads `state` (i.e. `...state`) and includes `keyMetrics`.
		- `argsToParams` should be a function having the `settings` parameter and should also return the `settings` parameter.
		- `validateParams` should be a function having the `settings` parameter and should use `invariant` to validate that `settings` is a plain object.
	- In a new object named `baseSelectors`, create a new selector named `getKeyMetrics`. This selector should return the `keyMetrics` property value from the `state`. Resolver(s) and additional logic for this will be implemented in #6257.
	- In a new object named `baseActions`, create a new generator function as an action named `*saveKeyMetrics`. This action should do the following:
	    - Yield the `clearError()` function from `create-error-store` having `saveKeyMetrics` and an empty array as parameters.
		- Call the `getKeyMetrics` selector from the same store and assign it to a variable named `keyMetrics`.
		- Yield `fetchSaveKeyMetricsStore.actions.fetchSaveKeyMetrics()` function passing `keyMetrics` as the parameter, and destructure `response` and `error` from it.
		- If `error` is truthy, yield the `receiveError()` function from `create-error-store` having the `error`, `saveKeyMetrics`, and an empty array as parameters.
		- At the end, return an object containing `response` and `error` from the action.
	- Compose the `store` using the `Data.combineStores()` function and export it including the necessary datastore properties. You can follow how it is being done in `assets/js/googlesitekit/datastore/user/user-input-settings.js` as an example.

### Test Coverage

- Create `assets/js/googlesitekit/datastore/user/key-metrics.test.js` and add test cases for the added action & selector.

## QA Brief

* This issue has no UI changes - hence, a simple smoke test of the plugin (and checking for any errors/console errors) should be enough.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs look good, the IB can determine the placement of the file, etc. 👍🏻

**Comment by jimmymadon** [comment]
@tofumatt Based on our conversation yesterday, I've added storing the `isWidgetHidden` flag as part of this same issue as the REST endpoint can save the flag and the user picked metric slugs at once.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

While testing this, I asked a [question in Slack](https://10up.slack.com/archives/CBKKQEBR9/p1675338684606899) to discuss if this should be behind a feature flag, since the code will go into the current release. After some discussion it was decided that we should include it behind the `userinput` feature flag to be safe.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Spent time going through the plugin setup, looking at the main and entity dashboard. Plus looking at the settings. This is with the `userInput` feature flag enabled and disabled. Saw no new warnings or errors in the console.
