### ISSUE TITLE
Plugin Zip Files / Deploy to Wiki github action is failing 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6315]
## Bug Description

The `Plugin Zip Files / Deploy to Wiki` github action has started to fail recently. This makes the Tester plugin unusable as it can't pull in the updated zips for the latest commits and PRs. 

## Steps to reproduce

See: https://github.com/google/site-kit-wp/actions/workflows/zips.yml

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `Plugin Zip Files / Deploy to Wiki` should complete without any errors and zips should be deployed correctly.
    * As a result, the branches and PRs selection on Tester plugin should reflect latest changes. 

## Implementation Brief

* Remove the `token` config lines from `zips.xml`. As the default `GITHUB_TOKEN` [can be used to update the Wiki](https://github.com/orgs/community/discussions/25929#discussioncomment-3249716), we don't need to specify a PAT.

https://github.com/google/site-kit-wp/blob/6cc0c98c9eecba466b7191706f714ed240ccc127/.github/workflows/zips.yml#L125

https://github.com/google/site-kit-wp/blob/6cc0c98c9eecba466b7191706f714ed240ccc127/.github/workflows/zips.yml#L157

### Test Coverage

* No new tests needed.

## QA Brief

* Plugin Zip Files/Deploy to Wiki GitHub Actions should succeed in the `develop` branch.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs look good. IB as well.

IB ✅

**Comment by asvinb** [comment]
**QA: ✔️** 

* Checked the action on a recent PR and it's no longer failing.
![image](https://user-images.githubusercontent.com/31818/207321992-159475d7-56e2-4c0d-89b4-31c589f7f706.png)
