### ISSUE TITLE
GA4 selector value is interpreted as an action

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6326]
## Bug Description

While working on #6293, [we found out](https://github.com/google/site-kit-wp/pull/6320#discussion_r1047642283) that the GA4 datastore selector `getMatchingWebDataStream()` returns a value that is interpreted as an action and is then dispatched, which is unexpected.

This happens because this selector returns a value that is an object containing a `type` property. We need to update this so that it returns a non-action-like value.

More information [here](https://github.com/google/site-kit-wp/pull/6320#discussion_r1047642283).

## Steps to reproduce

1. Set up Site Kit with Analytics (including GA4).
2. Go to the Site Kit->Settings->Connected Services.
3. Click on "Edit" under Analytics.
4. Wait for the GA4 PropertySelect to show up.
5. Using the Redux Developer Tools, see actions for the `modules/analytics-4` store.
6. Observe that there is an action named `WEB_DATA_STREAM`.

## Screenshots

The selector response:

![image](https://user-images.githubusercontent.com/20284937/207554848-bdd9c93d-74ac-41a9-bafa-a5e72b7f64b9.png)

The action:

![image](https://user-images.githubusercontent.com/20284937/207554541-83465f85-49a8-4328-8297-45e5ea3c4f34.png)

## Additional Context

 - PHP Version: 7.4.30
 - OS: Any
 - Browser: Any
 - Plugin Version: 1.89.0
 - Device: Any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `webDataStream` object should be updated in a way that it doesn't get treated as an action object unexpectedly. 
    * This can either happen in API or JS store level. 
    * While the reported issue can be resolved by changing the `type` property name (to something else. ie. `dataStreamType`) of the data steam before returning it from `matchWebDataStream`, updating all the data streams in all places is more future proof and consistent solution. 
* `matchWebDataStream` should no longer unexpectedly dispatch an action named `WEB_DATA_STREAM`. 

## Implementation Brief

* Inside `includes/Modules/Analytics_4.php`: 
    * Locate `filter_webdatastream_with_ids` function
    * Add logic to check if `$obj` has property `type` and if so change it to `dataStreamType`
    * Add a comment 

### Test Coverage

* All tests should pass

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
ACs here are good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
Hm... i can't replicate the problem on `develop`. @nfmohit is it still the case for you?

**Comment by nfmohit** [comment]
Hi @eugene-manuilov!

Thank you for checking. I can't seem to be able to replicate this anymore in the Analytics `SettingsEdit` (using the `Steps to reproduce` mentioned above).

However, the selector response still has the `type` property. Do you think it might be problematic going forward?

![image](https://user-images.githubusercontent.com/20284937/219249578-26b9a6ef-9923-4e63-a160-05f0c2acbf4f.png)

**Comment by eugene-manuilov** [comment]
> Thank you for checking. I can't seem to be able to replicate this anymore in the Analytics `SettingsEdit` (using the `Steps to reproduce` mentioned above).

Thanks, @nfmohit.

> However, the selector response still has the `type` property. Do you think it might be problematic going forward?

No, i don't think that will be a problem. We can close this ticket.
