### ISSUE TITLE
Prune old VRT reference images 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6329]
## Feature Description

There are a number of old unused references images lingering in the https://github.com/google/site-kit-wp/tree/8077cb0a7c9e1b506dd8c9ff2cb5f3958023cd09/tests/backstop/reference directory which should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All Backstop reference images that do not correlate to an existing scenario should be removed

## Implementation Brief

* Empty `tests/backstop/tests`
* Run `test:visualtest` on the latest `develop`
* Delete all the files in `tests/backstop/reference` 
* Copy the files from the last test run (the only directory now in `tests/backstop/tests`) to the `tests/backstop/reference` directory (without the intermediate numeric test directory)
* Discard any reference images which show as unchanged or modified (only those that were deleted should remain)
* Commit the deleted reference images

### Test Coverage

* No changes

## QA Brief

* Nothing really to QA here, it's an infra-related cleanup task

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by eugene-manuilov** [comment]
Moving to Approval since there is nothing to QA.
