### ISSUE TITLE
Setup: ensure anonymous usage tracking is Opt-In

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#633]
## Feature Description

During plugin setup, usage tracking should be _disabled by default_ and users should have to **Opt-In** to tracking by checking the checkbox to enable tracking.

Currently the plugin defaults to tracking being **on** by default set and users must **Opt Out** of tracking if they don't want it enabled.

![image](https://user-images.githubusercontent.com/2676022/66498711-bfb99b80-ea7b-11e9-9bff-eab86ea222b7.png)

### Considerations
Currently tracking is on by default because beta users agree to enabling it when they sign up for the beta.

The WordPress Plugin Guidelines states that "Plugins may not track users without their consent.", and mentions the "Opt-In" approach... details: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#7-plugins-may-not-track-users-without-their-consent

Having tracking be "Opt-In" feels also like a best practice generally. However, it is worth noting that the plugin handbook does make an exception for Software as a Service which Site Kit possibly falls under:

> An exception to this policy is Software as a Service, such as Twitter, an
> Amazon CDN plugin, or Akismet. By installing, activating, registering, and
> configuring plugins that utilize those services, consent is granted for
> those systems.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On new installs, and for each new admin user, when reaching the "Authenticate" screen, the "Allow Tracking" checkbox should be unchecked by default.
* No tracking events or tracking script will be added to the site (for each user) until and unless the user checks the tracking box. 

## Implementation Brief

* Change the default value for the tracking option to `false` On this line, the `true` should be removed, causing the default `false` to kick in: https://github.com/google/site-kit-wp/blob/b42304c5e577eb13fa5934bd9c02f2a0cba1e44b/includes/Core/Util/Tracking.php#L121

## Changelog entry

* N/A

**Comment by marrrmarrr** [comment]
@adamsilverstein heads-up that the location of this Opt-in will change (details in #673 )

**Comment by felixarntz** [comment]
IB ✅

**Comment by adamsilverstein** [comment]
In general this passes QA and I am moving to Approval, however I noted several small unrelated issues during QA that I will create follow up issues for.

### Summary
Ticket passes QA, creating follow up issues for:
* Remove `googlesitekit_tracking_optin` option when resetting plugin.
* Ensure activating/deactivating tracking from plugin screen takes effect immediately.
* Analytics/module screen should show 'insufficient scopes' warning.


### Testing Procedure

#### Oped out test
* Switch UA code to a personal test analytics account, monitoring Real Time tab for plugin events.
* Enable plugin.
* Verify checkbox is unchecking in the tracking opt-in:

![image](https://user-images.githubusercontent.com/2676022/67684160-45808680-f958-11e9-80fb-bed92f1e55ed.png)

On the next step I am using the filter so I see step 1 of the wizard. I see the opt in box again, which I guess makes sense because if I had missed the banner this would be the only change I have to opt in.

![image](https://user-images.githubusercontent.com/2676022/67684382-af009500-f958-11e9-8642-42983a8b1c42.png)

* Complete setup.
* Configure an additional module, note no analytics events are sent.
* Enable tracking in settings->admin
* Enable another module
* Verify tracking events work as expected for second module activation.

![image](https://user-images.githubusercontent.com/2676022/67685494-cf315380-f95a-11e9-83fc-5cddf44623de.png)

* Reset Site Kit to start test over.
**Noted potential issue** in database - reset did NOT clear the opt in option:
![image](https://user-images.githubusercontent.com/2676022/67685146-28e54e00-f95a-11e9-820d-e0640ef767f5.png)

After re-activating the plugin, the banner indicates tracking is off:

![image](https://user-images.githubusercontent.com/2676022/67685215-47e3e000-f95a-11e9-87d5-dd41fdc7de10.png)

However the first screen of the setup flow shows the actual state:

![image](https://user-images.githubusercontent.com/2676022/67685281-68ac3580-f95a-11e9-9c9b-19cb1ef176b3.png)

Tracking is in fact still active: I can see an event triggered in analytics: 

![image](https://user-images.githubusercontent.com/2676022/67685363-8d081200-f95a-11e9-968e-8aae2812d91b.png)

I will open a separate Issue to address this.

* Retested, this time turning tracking on immediately after activation.
* Click "Start Setup" - verify checkbox remains checked on splash screen.
* Note tracking events sent to analytics for site verification during setup flow: 

![image](https://user-images.githubusercontent.com/2676022/67686042-b2e1e680-f95b-11e9-9001-8030edc82c21.png)

* Disable tracking at Settings->Admin
* Test enabling a module

At this point I noticed that the plugin sent one more analytics tracking event, despite the fact that I had just disabled tracking. I'm not certain this is a problem, I will create a follow up issue to investigate.

At this point I clicked cancel and **did not complete the module setup flow** - now I had analytics enabled, however my scopes were not complete. I went to the analytics screen and saw this error:

![image](https://user-images.githubusercontent.com/2676022/67686646-a9a54980-f95c-11e9-9c55-e557255fed83.png)

re-fetching doesn't help. checking the response, I see the issue:

![image](https://user-images.githubusercontent.com/2676022/67686714-bfb30a00-f95c-11e9-881a-6e9ea298f58c.png)

Two problems here:

1. The plugin isn't correctly informing me that I have insufficient scopes (I am expecting an admin notice)
2. The analytics setup module isn't handling the error response correctly.

Visiting other dashboard screens including the Site Kit dashboard I see the correct notices indicating a lack of scopes, but these were missing from the analytics screen itself.

![image](https://user-images.githubusercontent.com/2676022/67690493-99906880-f962-11e9-835d-eaeb882ec99f.png)

![image](https://user-images.githubusercontent.com/2676022/67690514-a1500d00-f962-11e9-92c0-dca1ed0656fa.png)


I will create a follow up issue to cover this.
