### ISSUE TITLE
Decouple GA4 property select from measurement IDs

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6330]
## Feature Description

Since the addition of GA4, we've aimed to keep the experience as simple as possible. In this spirit, the settings for GA4 were largely simplified to not expose the measurement ID as an independent setting. This has in turn introduced some unexpected complexities related to the combination of representing multiple entities in a single choice.

Related issues:
- https://github.com/google/site-kit-wp/issues/5145
- https://github.com/google/site-kit-wp/issues/6293 (plus comments)

Perhaps most importantly, there are limitations of the 1-1 property to measurement ID mapping choices that could prevent a user from being able to configure GA4 from using their desired tag (measurement ID). This is because GA4 does not require web data streams to have a unique base URI within the same property. If a user had multiple web data streams for a property that had the same URL, Site Kit would automatically match the first and there would be no way to specifically choose a different one. Similarly, there is no option to explicitly create a new web data stream, other than by association when creating a new property.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 property select should be updated to be similar to the UA property select in that it only controls the selection of the GA4 property
* A new GA4 web data stream select control should be introduced, which lists all web data streams for the selected property, as well as an option to create a new one: `Set up a new web data stream`
	- The placement and label for this should be `Web Data Stream`
	- It should have a loading state similar to the property select
	- The permissions modal message (when creating a new data stream and `analytics.edit` scope is not granted) should be updated to reference a "web data stream" instead of a "measurement ID"
* The initial pre-selection of the matched property (and corresponding measurement ID) must continue to be the same as today, selecting the first property and measurement ID that match the site's URL
	- It's important that this change does not result in additional steps to complete the Analytics setup, we're simply splitting what was represented in one select into two separate select controls
	- The property select and data stream select should continue to remain in a loading state while the initial matching is in progress (as today)
- The formatting of options to choose from should be as follows:
	- Property select: `{property name} ({propertyID})`
	- Web data stream select: `{stream name} ({measurementID})`
- This change should be reflected in settings with the addition of the new measurement ID select to the right of the current property select, similar to the position of the View select for UA
	- On the settings view, the link to `Edit in Analytics` should remain as today, to the right of the added measurement ID select (to be clear, no edit link should be added for the GA4 property)
		- The label for the value should remain as today as `Measurement ID`
- This change should be reflected in set up with the addition of the new data stream select to the right of the GA4 property select as follows
	- When the selected primary property is a GA4 property, the data stream select should be added to the right of it
	- When the selected primary property is a UA property, the data stream select should be added to the right of the GA4 property select shown in the CTA below it

## Implementation Brief

In `assets/js/modules/analytics-4/datastore/webdatastreams.js`:

- Create selector `getMatchingWebDataStreams`, which is similar to `getMatchingWebDataStream` but returns an array of all matching web data streams rather than the first match.
- Create selector `getMatchingWebDataStreamsByPropertyID`, which is similar to `getMatchingWebDataStreamByPropertyID` but returns the result of `getMatchingWebDataStreams` instead of `getMatchingWebDataStream`.

In the GA4 `PropertySelect` component:

- Change the property `Option` rendering:
  - Remove the check for the measurement ID in the condition for showing `displayName`.
  - Show the property ID (`_id`) rather than the measurement ID.
- As `measurementIDs` is no longer needed, change the call to select `getMatchedMeasurementIDsByPropertyIDs` to select `getWebDataStreamsBatch` for `propertyIDs` instead as this is what's checked to determine the `areMeasurementIDsResolving` value.

Create `assets/js/modules/analytics-4/components/common/MeasurementSelect.js`, exporting the `MeasurementSelect` component.

- The implementation will be similar to the GA4 `PropertySelect` component, which can be copied and modified.
- In addition to returning `null` when the account is invalid, it should return `null` when the current GA4 property is invalid, using the GA4 version of `isValidPropertySelection` (similar to [`ProfileSelect`](https://github.com/google/site-kit-wp/blob/09fa76644363a13acb4f590b29838dbba68065c5/assets/js/modules/analytics/components/common/ProfileSelect.js#L88-L93)).
- Rather than retrieving the list of measurement IDs from `getMatchedMeasurementIDsByPropertyIDs`, retrieve a list of web data streams for the current GA4 property ID via the new `getMatchingWebDataStreamsByPropertyID` selector.
- Use this list of measurement IDs for the `Select` options, using the web data stream properties `displayName` and `_id` for the `Option` text.
- Change the loading logic to check for resolution of the `getWebDataStreams` selector for the current GA4 property, rather than the `getWebDataStreamsBatch` selector.
- Use `setWebDataStreamID` and `setMeasurementID` instead of `selectProperty`.
- Use `isValidWebDataStreamID` instead of `isValidPropertySelection` to determine `isValidSelection`.
- Use the `WEBDATASTREAM_CREATE` constant instead of `PROPERTY_CREATE`.
- Ensure all references to "property" are updated to refer to "measurement" where appropriate.

In the `GA4SettingsControls` component:

- Update the property `Select` that is rendered in the disabled case:
  - Change the property `Option` rendering to show the matched property ID rather than the measurement ID.
- Render a disabled measurement ID `Select` to the right of the disabled property `Select` with similar logic, but showing the matched measurement ID.

In the `SetupFormGA4Transitional` component:
- When `propertyType` is `PROPERTY_TYPE_GA4`, add the new `MeasurementSelect` component to the right of `PropertySelectIncludingGA4`.

Add the new `MeasurementSelect` component to the right of all instances of GA4 `PropertySelect`, which are at present in the following components:
  - `GA4SettingsControls`
  - `SetupFormGA4`
  - `SetupFormGA4Transitional`
  - GA4 `SetupBanner`

### Test Coverage

- Add tests for `MeasurementSelect` along the same lines as the tests for the GA4 `PropertySelect`.
- Add tests for the new `getMatchingWebDataStreams` and `getMatchingWebDataStreamsByPropertyID` selectors.
- Update any failing tests.

## QA Brief

* Create a new site and connect the SK plugin
* Activate the Analytics module and verify that on the setup screen you see that now we haveAnalytics 4 property and measurement dropdowns that let you select property and datastream separately.
* Once Analytics is set up, go to the settings page and edit the Analytics settings. Ensure that you also see the new dropdown for Analytics 4 data streams (it has "Measurement" label) and it let's use select different measurements. 
* Delete Analytics 4 settings from the database to simulate the situation when the user doesn't have GA4 configured yet.
  * Verify that you can select the measurement setting in the Analytics settings
  * Verify that you can select the measurement setting in the setup banner.

## Changelog entry

* Add a dedicated control for the Google Analytics 4 web data stream instead of a single property select.

**Comment by bethanylang** [comment]
Removing from Sprint 92 as this has been in AC for some time. Will add to a future sprint once it's in EB.

**Comment by felixarntz** [comment]
@aaemnnosttv ACs LGTM!

**Comment by tofumatt** [comment]
IB looks good here; it's a big issue but I think it's good 👍🏻 

IB ✅

**Comment by eugene-manuilov** [comment]
@aaemnnosttv could you please review my #6618?

**Comment by aaemnnosttv** [comment]
Apologies for the delay @eugene-manuilov – nice work 👍

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I've updated the AC around the language to be used 👍

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@eugene-manuilov I have a few observations:

1.  A console error and analytics is not successfully set up in a specific scenario:  I have a site that has Site Kit and Analytics already set up with a web data steam. I reset and set up again. Rather than go with the defaulted web data stream, I select from the dropdown to create a new one. When clicking on the configure analytics CTA, I am redirected back to the dashboard and the success notification appears. 

In the console though an error message appears on clicking the CTA. 

`Google Site Kit API Error method:POST datapoint:create-webdatastream type:modules identifier:analytics-4 error:"Requested entity already exists"  POST https://ing-online-voka.instawp.xyz/wp-json/google-site-kit/v1/modules/analytics-4/data/create-webdatastream?_locale=user 409`

When I go to the settings for Analytics, the module isn't connected and when editing the settings the GA4 property and web data stream fields are blank.   You can see it in action on this screencast. 

https://user-images.githubusercontent.com/73545194/227140062-c956843c-8bd5-408c-a6fa-428591a1b892.mp4

2. A similar issue occurs when I go to edit settings. I select a new web data stream, and click on the confirm changes and the settings are saved but no new web data stream is created and the same error above appears. 

https://user-images.githubusercontent.com/73545194/227141021-8ff82f6f-9a28-4f8f-8d20-14e4d59541db.mp4

**Comment by eugene-manuilov** [comment]
@wpdarren that is a known issue and we already have a ticket for it: https://github.com/google/site-kit-wp/issues/6727

**Comment by wpdarren** [comment]
@eugene-manuilov thanks for the information.  I am assuming that the ticket will go out at `1.98.0` like this ticket? Otherwise, we'll have these two bugs highlighted above in the plugin and I am sure it will cause user support tickets.

**Comment by eugene-manuilov** [comment]
@wpdarren looks like we haven't planned that ticket for `1.98.0` which means that your assumption is probably right. I think we need to prioritise that ticket for the next release, but let's keep this conversation in that ticket (thanks for already posting a comment there). Do you have any other concerns regarding this ticket?

**Comment by wpdarren** [comment]
@eugene-manuilov I am just finishing off the ticket now, not found anything else other than the two issues reported above.

**Comment by wpdarren** [comment]
### QA update: ✅ 

**Verified:**

- We have Analytics 4 property and measurement dropdowns that let you select property and datastream separately.
- The settings page and edit the Analytics settings also see the new dropdown for Analytics 4 data streams.
- When the user doesn't have GA4 configured yet you can select the measurement setting in the Analytics settings
and the measurement setting in the setup banner.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/227919320-68861ec4-784f-44bb-9b55-73f39125c8a1.png)
![image](https://user-images.githubusercontent.com/73545194/227919344-a127fc2a-5b88-40d3-8dbd-5caf941e6ec6.png)
![image](https://user-images.githubusercontent.com/73545194/227921538-5fa5c333-04f2-458b-8182-822f84831a92.png)
![image](https://user-images.githubusercontent.com/73545194/227921565-2e17598c-a599-44dc-870c-0c128ae9e79d.png)

</details>
