### ISSUE TITLE
Improve error handling in Google charts to avoid crashing the dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6346]
## Feature Description

The Google Charts library is fundamental to much of the reporting that Site Kit provides and is used both on the Site Kit dashboards as well as the main WP dashboard in the "Site Kit Summary" dashboard widget. As an external library which is commonly loaded by other plugins and themes, it's a common source of conflicts as the library does not support loading different versions on the same page.

When an error is raised within our Google charts, it often results in the dashboard crashing entirely, which is obviously not a good experience and something we want to minimize as much as possible. 

In #5605, we enhanced our error handling around async graphics (essentially lazy loaded chunks) to avoid crashing the dashboard if unable to be loaded. We could take a similar approach to charts so that in the event of an error, we encapsulate the crash to the local component rather than allowing it to bring down the entire dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GoogleChart` component should be updated such that its default export is wrapped with a React error boundary which displays an alternate component when an error is caught
* If an error is caught, the component should render a new, basic error component
    * Title: `Error in Google Chart`
    * Body: `An error prevented this Google chart from being displayed properly. Report the exact contents of the error on the support forum to find out what caused it.`
    * Primary CTA (button): `Copy error contents` (should look and function the same as the button in the current `ErrorHandler` component – clicking it should copy the error to the clipboard with wrapping single backticks)
    * Secondary CTA (link): `Report this error` (should link to the [forum](https://wordpress.org/support/plugin/google-site-kit/) in a new window/tab)
	* Visually, it should look similar to this mock while fulfilling the criteria above
	    <img src="https://user-images.githubusercontent.com/1621608/208964279-6de935b5-d00f-44c8-bb28-aff65d11b67d.png" width=400>
* An error arising within the Google chart component should not trigger an error boundary above it in the component tree (i.e. crash the whole dashboard)

## Implementation Brief

* Create a class based `GoogleChartErrorHandler` component.
    * The component should have the same logic as `assets/js/components/ErrorHandler/index.js` with the following changes:
        * The `trackEvent` call within `componentDidCatch` should be removed.
        * Instead of rendering the `<BannerNotification>` component, use the `assets/js/components/notifications/CTA` component to render the error as show in the AC mock. Use/copy styles for the Primary and Secondary CTA from the `<ReportErrorActions>` component. Be sure to use the text within the AC's for the title, description and CTA button/link instead of the text within the mock image above.
* In `assets/js/components/GoogleChart.js`,
	* Wrap the entire `<div>` being rendered with the new `GoogleChartErrorHandler` component.
* Add stories for `GoogleChartErrorHandler` component.

### Test Coverage
* Add tests for the `GoogleChartErrorHandler` component similar to the tests for the `MediaErrorHandler` component.

## QA Brief

This QA Brief is copied from the steps to reproduce the issue (#6350). Using these steps below alongside running `git revert 5283cfcc3fad561549885584bfc0bb4df5e61751` to enable the charts on the WP Dashboard will work to test this change.

(Because this requires a local/custom build I'm marking this as a QA Engineering task.)

1. Setup a site with SK active (Analytics set up)
2. Install and set up the [Analytics Insights plugin](https://wordpress.org/plugins/analytics-insights/) (so that a WordPress main dashboard widget appears from this plugin)
3. Visit the main WP dashboard. A Google Charts error should appear as shown above that does not crash the entire React app.

## Changelog entry

* Improve error handling in Google charts to avoid crashing the dashboard.

**Comment by adamdunnage** [comment]
@aaemnnosttv Just tagging you here to let you know that we are also seeing a number of people report a separate Google charts error message also affecting the WP dashboard widget. This one seems to be linked to the GAinWP plugin.

Issue logged here: https://github.com/google/site-kit-wp/issues/6350

**Comment by bethanylang** [comment]
Noting that per discussion with @marrrmarrr, @aaemnnosttv, and @jamesozzie, the "Get help" link here should go to the support forum so that the support team can help the user identify which plugin could be causing the conflict.

**Comment by felixarntz** [comment]
@aaemnnosttv A distinct error boundary for this sounds good to me. Separately though, we should continue to explore what is causing these compatibility bugs. Is there any way we can encapsulate our version of Google Charts so that other plugins can't mess it up?

**Comment by aaemnnosttv** [comment]
> Is there any way we can encapsulate our version of Google Charts so that other plugins can't mess it up?

@felixarntz - @tofumatt mentioned he had looked into it in the past and had not found anything, but I think he may have been looking into other libraries, perhaps he can clarify.

The problem with Google charts is that the api is based on globals, so it's not designed to support multiple versions on the same page.

Short of rendering our chart in an iframe, I don't know if we could isolate it.

For the WP dashboard specifically, (or anything outside of SK screens) it may make sense to look into using a different library for this reason.

**Comment by marrrmarrr** [comment]
@aaemnnosttv switched the order of the CTAs and shortened the copy, from the language perspective this is good to go from my side.

**Comment by FlicHollis** [comment]
Thanks @marrrmarrr. @aaemnnosttv @tofumatt what are the next steps here? It looks like there are still decisions to be made, so we may want to remove this from the current sprint? cc @bethanylang

**Comment by tofumatt** [comment]
IB ✅ , but maybe we should file a follow-up issue about handling Google Chart errors specifically. I'll do that later if we decide we want to do it 🙂

**Comment by asvinb** [comment]
### QA: ✔️ 

Followed QAB:
* entire app does not crash.
* Google Charts error is displayed.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/31818/212021174-2f6cbe07-a4ef-4470-ab50-ab9a7c22e37a.png">

**Comment by aaemnnosttv** [comment]
I just noticed this on the main dashboard when changing the date range 

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/1621608/212177746-8cf59339-8f13-42f0-b483-b1ce271db925.png">

**Comment by tofumatt** [comment]
Seems like there's [maybe a workaround](https://github.com/rakannimer/react-google-charts/issues/268#issuecomment-1065805338), I'll investigate it a bit and if it works file an issue 👍🏻
