### ISSUE TITLE
Conditionally register User Input

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6347]
## Feature Description

Currently it seems most of User Input infra is being loaded all the time. This should be conditional based on the feature flag's activation like other features, and to generally not load things unnecessarily.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User Input functionality should not be loaded/registered unless the `userInput` feature flag is enabled  
_E.g. Settings, REST routes, admin screens, etc_
* Any redundant checks can be simplified

## Implementation Brief

* Conditionally add the [user-input Screen](https://github.com/google/site-kit-wp/blob/8beca0415bd1de9465a0719f164a174f2e35f0d1/includes/Core/Admin/Screens.php#L490-L508)
* Conditionally register `user_input` and `user_input_state` (although it should already be removed) in `Authentication::register`
* Remove the `userInput` feature check in `UserInputApp` – this will no longer be rendered and even if it somehow was, the rest routes won't exist so this is redundant.

### Test Coverage

* No changes

## QA Brief

* Check User input screen - all functionality should remain the same

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev.
- User input flow functionality working same as latest.
- User input preview CTA and answer preview not showing if feature flag is disabled.
