### ISSUE TITLE
Implement Analytics 4 conversion events REST data point

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#6348]
## Feature Description
Similar to the Analytics `goals` REST endpoint, a new endpoint should be created for Analytics 4 called `conversion-events` (as goals no longer exists in GA4, but instead has conversion events)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* A new REST data point `GET:conversion-events` should be added to the `Analytics_4` module class.
    * It should return the list of conversion events for a given property.

## Implementation Brief
* Using `includes/Modules/Analytics_4.php`,
    * Add `GET:conversion-events` to the array in `get_datapoint_definitions` and the service should be `analyticsadmin`.
    * In `create_data_request`, add the case for the new datapoint where a list of conversion events is returned for a property.
        * This can be done by using the `listPropertiesConversionEvents` method of `$this->get_service( 'analyticsadmin' )->properties_conversionEvents` passing the property ID as parameter.
    * Add corresponding case in `parse_data_response` to return only the list of conversion events rather than the full response

### Test Coverage

* Add tests for the `conversion-events` REST endpoint. See the existing tests for the GA4 `report` datapoint for a good starting point.

### QA:Eng

- Set up Site Kit with Analytics and GA4.
- In a Site Kit screen, run the following in the browser console (replace `GA4_PROPERTY_ID` with your GA4 property ID):
```
googlesitekit.api.get( 'modules', 'analytics-4', 'conversion-events', { propertyID: GA4_PROPERTY_ID }, { useCache: false } )
```
- Verify that a `GET` request is made to the `/modules/analytics-4/data/conversion-events?propertyID=GA4_PROPERTY_ID`.
- The request should return a `200` response with an array of objects, each object being a conversion event. Example:
<img width="729" alt="1" src="https://user-images.githubusercontent.com/20284937/212856830-6af93a39-8f96-4c80-9af5-14ee58600dac.png">

## Changelog entry

* Add a new endpoint for the Analytics 4 module to list conversion events.

**Comment by aaemnnosttv** [comment]
This LGTM for the most part. The main thing missing is a corresponding addition to `parse_data_response` where we return the subject of the request (i.e. the list of conversion events) rather than all the other top-level bits such as pagination tokens, etc.

As for the tests, this would be good to add although coverage for data points like this has always been very minimal. The work @techanvil is doing on the tests for the `report` datapoint now should serve as a good example to follow here as well.

I'll add this missing detail to the IB and bump the estimate to unblock this, then it should be good to go 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
@nfmohit unless you have any objections, I do not feel that this is a `QA:Eng` ticket. I have removed the label but let me know if you still feel it's worth an engineer looking at it.

**Comment by nfmohit** [comment]
Absolutely no objection from my side, thank you @wpdarren!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A `GET` request is made to the `/modules/analytics-4/data/conversion-events?propertyID=GA4_PROPERTY_ID`.
- The request returns a 200 response with an array of objects, each object being a conversion event. 

![image](https://user-images.githubusercontent.com/73545194/213391954-be1409ac-a168-413f-a943-1ee2bc70df59.png)
