### ISSUE TITLE
Disconnect modal displays underneath section locked dialog on settings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#636]
## Bug Description

The disconnect dialog for a connected Google account displays behind/under "section locked" dialogs that are displayed when editing a module's settings.

## Steps to reproduce

1. Basic setup
1. Connect a module with settings (e.g. Analytics)
1. Navigate to Site Kit settings page
1. Toggle the edit for the connected module to display "Section locked while editing"
1. Click "Disconnect" from the user menu in Site Kit

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/66534156-51a8bf00-eae3-11e9-9708-dc3350e3434f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The disconnect modal for a module should display above any other UI (specifically the "section locked" content).

## Implementation Brief

* Wrap the `<Dialog>` component with a `<Modal>` to render it in a different location in the DOM so that it isn't affected by CSS of its ancestors
* Merge #811 

## Changelog entry

* Fix display of the disconnect modal which could potentially appear below the "section locked" indicator in the plugin settings UI.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Removing this from 1.1.0 as it's not super-critical, and we have enough on our plate for that one. This fix is certainly okay to go into the next point release.

**Comment by cole10up** [comment]
Tested latest develop (attached).

Confirmed edit displays 'Selection Locked While Editing' is shown above editing Analytics for other settings

![image](https://user-images.githubusercontent.com/57115907/69692871-3f311780-1088-11ea-9b99-cf8619311780.png)

Clicking Disconnect retains the locked dialogue behind the disconnect modal properly

![image](https://user-images.githubusercontent.com/57115907/69692892-57089b80-1088-11ea-9bd1-7fda2692e86f.png)

Confirmed disconnection functionality is retained.

![image](https://user-images.githubusercontent.com/57115907/69692914-70114c80-1088-11ea-8cb7-8a532e990703.png)

Zip:
[google-site-kit.zip](https://github.com/google/site-kit-wp/files/3895059/google-site-kit.zip)

Passed QA ✅
