### ISSUE TITLE
GA opt-out added even when no tag is set

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6364]
## Bug Description

Site Kit's opt-out script for GA that is used for role-based tracking exclusions is being output even when there is no tag set up yet.

In #3294 we updated the tracking opt out to use GA's property-specific method which adds a key to the `window` global that has the form `ga-disable-MEASUREMENT-ID`. In this case, the key is being added even though there is no measurement ID provided. This is harmless but is clearly incorrect and should be cleaned up.

## Steps to reproduce

1. Activate Analytics but do not complete the module setup
2. See opt-out script on front-end while logged in with no tag after the `ga-disable-`

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/210390934-000d93c4-0b9d-4043-91c4-1adef67a0923.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA tracking opt-out should only be output when there is a configured property ID

## Implementation Brief

- In `includes/Modules/Analytics.php`:
    - Update the `print_tracking_opt_out()` method:
	    - After the `$property_id` variable is assigned, check if it is empty. If `$property_id` is empty, return early so that the method is terminated immediately.

### Test Coverage

- In `tests/phpunit/integration/Modules/AnalyticsTest.php`:
    - Update test case(s) accordingly.

## QA Brief

* Verify opt-out functionaly works as expected.
* Verify tracking data is sent to Analytics.

**Tag output**

* Enable Analytics but cancel Setup, so Analytics is enabled but not configured.
* Verify the opt-out code from AC screenshot it not added.
* Setup Analytics
* Verify the opt-out code is now added.

## Changelog entry

* Skip outputting measurement ID specific Google Analytics disabling script when no measurement ID is configured.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
@derweili is this still in progress? The PR looked like it might have been ready for review. I left one comment but otherwise LG2G 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified**

- With Analytics cancelled during setup, the opt-out code from AC screenshot it not added.
- With Analytics connected, the opt-out code is now added.
- Opt-out functionality works as expected and tracking data is sent to Analytics.
    - Disabled snippets and opt-out code does not appear. 

<details>
 <summary>Details</summary>

https://user-images.githubusercontent.com/73545194/212895911-56e4eb4c-48ff-459c-807b-32f84203984f.mp4

![image](https://user-images.githubusercontent.com/73545194/212895641-c95d9f68-b8be-4fa2-84df-fd635861c0d3.png)
![image](https://user-images.githubusercontent.com/73545194/212895661-f5be63d4-7f0e-4033-a8af-c24a719d8447.png)

</details>
