### ISSUE TITLE
Change the mentioned AdSense approval timeframe

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6368]
## Bug Description

If a site is in the getting-ready stage awaiting AdSense approval the message we output to users is below:
`This usually takes a few days, but in some cases can take up to 2 weeks. You’ll get an email from AdSense as soon as they have run some checks on your site.`

<kbd> ![image](https://user-images.githubusercontent.com/41326532/210550735-9af44ada-ec81-42d7-9d8d-177908eaad6e.png)

The 2 week mention here leads to the impression that this is the maximum time a site review can take, when this isn't the case. Sometimes it can take as much as 4 - 6 weeks. [Here is one example in the AdSense Help Forums](https://support.google.com/adsense/thread/195354248/getting-ready-status-only-showing-for-long-time-almost-a-month-is-there-anything-i-can-do?hl=en) where a user is correct based on the messaging in Site Kit. 

Consider revising the wording to the below or something similar:

```diff
- This usually takes a few days, but in some cases can take up to 2 weeks. You’ll get an email from AdSense as soon as they have run some checks on your site.
+ This usually takes a few days, but in some cases can take a few weeks. You’ll get an email from AdSense as soon as they have run some checks on your site.
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Adsense GettingReady component, the message shown should be changed to:
```diff
- This usually takes a few days, but in some cases can take up to 2 weeks. You’ll get an email from AdSense as soon as they have run some checks on your site.
+ This usually takes a few days, but in some cases can take a few weeks. You’ll get an email from AdSense as soon as they have run some checks on your site.
```

## Implementation Brief

* Change https://github.com/google/site-kit-wp/blob/c2b47c41c9de4c1d28d41f9fb753492a2038ad02/assets/js/modules/adsense/components/setup/v2/SetupAccountSite/GettingReady.js#L58 to:

```
This usually takes a few days, but in some cases can take a few weeks. You’ll get an email from AdSense as soon as they have run some checks on your site.
```

### Test Coverage

* VRTs should be updated for the new wording.

## QA Brief

* To get the "Getting Ready" status in the Adsense setup, set the `Force AdSense site status` to `getting-ready` using the tester plugin.
* Try connecting the Adsense module.
* Ensure the changed text appears in the Setup screen according to the AC.
* Once merged, it can also be verified from this [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-components-setup-setupmain--setup-account-site-getting-ready).

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
cc @marrrmarrr

**Comment by tofumatt** [comment]
> This AdSense state is not covered in storybook yet, a Storybook story should be created for this view/component.

There isn't one for that _file_, but looks like this state is covered in the AdSense setup stories:

https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-components-setup-v2-setupmain--setup-account-site-getting-ready

So I've removed that part from the ACs.

-----

Other than that, the ACs here are good, given the ACs are basically the IB, I'm going to add the IB for this as well and move it into EB 🙂

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that site is in the getting-ready stage awaiting AdSense approval the message updated as per AC:
- `This usually takes a few days, but in some cases can take a few weeks. You’ll get an email from AdSense as soon as they have run some checks on your site.`
- Also, verified the related [story.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-components-setup-setupmain--setup-account-site-getting-ready)

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/caf99fc1-6820-4daf-aa41-8609e6dfbb0b)

</details>
