### ISSUE TITLE
Add margin to "Continue" button during setup step 4: 'Connect Search Console'

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#637]
## Bug Description

* During plugin setup when the user reaches step 4 "Connect Search Console", the button to continue touches the text "Need Help" and needs some padding or margin on its right edge:

## Steps to reproduce

1. Install the plugin.
2. Go thru setup with a new domain, stopping at step 4.
3. Note spacing issue.

## Screenshots

![image](https://user-images.githubusercontent.com/2676022/66571469-93aa2300-eb2c-11e9-9fe3-df60da0f4cef.png)

## Additional Context

 - PHP Version: 7.2
 - Browser [e.g. chrome, safari] Chrome Version 78.0.3904.50 
 - Plugin Version [e.g. 22] beta 1.0.8-rc1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Increase spacing between the button on this screen to match the spacing between the button and help/action links on all other screens. 

## Implementation Brief

Update classes used for step actions to use the same as other steps

```diff
- <div className="googlesitekit-setup-module__action googlesitekit-setup-module__action--justify">
+ <div className="googlesitekit-wizard-step__action googlesitekit-wizard-step__action--justify">
```

## Changelog entry

* Fix spacing issue in Search Console step for local development setup.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz should this one be closed now that this flow is no longer user-facing? It is a _very_ small change, but perhaps not worth taking time away from other issues.

**Comment by cole10up** [comment]
**Tested**

Adjusted my domain in the developer plugin to one that is not on my properties list in SC and tried setup again. Was able to verify the fix.

![image](https://user-images.githubusercontent.com/57115907/69824815-dfd72280-11c1-11ea-81c4-af2e8b9a32ee.png)

Passed QA ✅
