### ISSUE TITLE
Key metrics banner does not display on Admin Settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6370]
## Bug Description

While testing #5895 I noticed that the banner does not properly appear in the admin settings. 

As you can see from the screencast below, the key metrics banner does flash up but disappears very quickly. 

This is when a user has not completed any of the questions. 

You can find the [conversation here](https://github.com/google/site-kit-wp/issues/5895#issuecomment-1353727580) regarding the issue.

https://user-images.githubusercontent.com/73545194/210577290-50cd7cf5-f3cc-47f7-b090-3eae7dee4955.mp4

## Steps to reproduce

1. Connect Site Kit. 
2. Ensure that `userInput` feature flag is enabled.
3. Go to the Admin settings and observe behaviour. 
4. A banner should appear asking the user to complete the questions. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Key Metrics CTA banner should appear in the Admin Settings when the user has not completed the User Input questionnaire. (Even if the user has answered one or more questions, until they have answered every question the CTA should appear.)

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by hussain-t** [comment]
@wpdarren, according to the AC of https://github.com/google/site-kit-wp/issues/5895, the banner should only be shown when both Search Console and Analytics are connected and not in the gathering data state.

**Comment by wpdarren** [comment]
After conversation with @hussain-t

When the user does have Analytics connected and the dashboard is gathering data state then the `Key metrics` banner flashes as per my original description.   When there's data then the banner displays as expected. 

We did comment that the banner Key metrics does not appear when Analytics is not connected, and I was wondering if that is correct.  As Hussain has mentioned above, the AC on 5895 suggests it shouldn't but I'd like to check.

**Comment by hussain-t** [comment]
@wpdarren, @kuasha420 I do see this in the design docs. However, I would like to know why we want to hide the banner if the Analytics and Search Console are not connected and are in the gathering data state.
>If a user who has not yet taken or completed (ie. clicked cancel on the questions screen) visits Admin Settings, they will be presented with a CTA to complete it. Note that the Key metrics section is subject to the same requirements as the [Dashboard Banner](https://docs.google.com/document/d/14dkWd7Es-5QE_2Wz3GHI0TmlDGEoHqQmr64-qAPrEvY/edit?resourcekey=0-bF_CJ3Nv4YS-9SKKSgcAEQ#heading=h.pnw8jd9mcern) - this section should only be visible when both Search Console and Google Analytics are connected and are not in Gathering Data state.

**Comment by kuasha420** [comment]
It was decided during the design face. The rational was, if we show the banner while the main two modules of Key Metrics widgets are not connected or have no data, the user will do all the things just to see nothing which is overall a negative experience. We decided to have the required modules connected and with data before prompting for User Input questions. @hussain-t

**Comment by hussain-t** [comment]
Thanks, @kuasha420. That makes sense when we allow the user to edit the changes. What if the user still needs to complete the questionnaire? We ask the user to complete it even before setting up the modules.

**Comment by kuasha420** [comment]
@hussain-t Do we? As far as I recall, both dashboard and admin banner should not display at all if the required modules are not connected or doesn't have data.

**Comment by hussain-t** [comment]
@kuasha420, we don’t show the dashboard; however, we do show the Admin settings page.

**Comment by kuasha420** [comment]
@hussain-t as far as I remember from our discussion, the entire section re. User Input settings and Key Metrics CTA should not display if the modules aren't connected or have no data. So, I think only thing we need to fix here is the flicker, which is dependent on #5933.

**Comment by hussain-t** [comment]
Thanks @kuasha420. @wpdarren, do you have any concerns? Otherwise, can we close this issue?

**Comment by wpdarren** [comment]
@kuasha420 @hussain-t thanks for clarifying this.  

Since the only issue is the flicker, and that'll be picked up as part of #5933, I will close this ticket.
