### ISSUE TITLE
Complete implementation of banner notification for a change in Google tag mapping

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6373]
This issue is about actually implementing the contents of the banner notification that was scaffolded in #6083.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The banner notification scaffolded in #6083 should be implemented as follows:
* _If_ the destinations list (already implemented in the component in #6083) includes a result that is another GA4 measurement ID (i.e. starting with "G-"), its parent GA4 property needs to be identified, using the new selector from #6372.
    * Make sure to filter the destinations list passed to the selector so that only those starting in "G-" are passed (there may also be other ones, e.g. starting in "AW-", which should be ignored as they are not for GA4).
    * Since that selector is expensive to call, it is critical that this call _only_ happens when needed (i.e. don't put it as an unconditionally called selector directly into the component). It only must be called when there is at least one "G-" destination ID.
    * If a result is returned from here (i.e. not `null`), it will result in banner notification scenario **A** below.
* _If_ the destinations list does not include any result that is a GA4 measurement ID, or if the Analytics config lookup based on the GA4 measurement IDs above results in no result (`null`), no alternative GA4 config is available. This will result in banner notification scenario **B** below.

### Banner notification scenario A: Alternative GA4 config found

* Title: _Update Site Kit's Analytics configuration to continue seeing Analytics data on the dashboard_
* Description: _The Google Tag on your site is no longer associated with your current Google Analytics 4 property "Current Property (7654321)". It is now recording metrics to another Google Analytics 4 property "Property Name (1234567)". If you want to continue seeing Analytics data in the Site Kit dashboard, we suggest you switch Site Kit's Google Analytics configuration to show data for this property._
    * The "Current Property (7654321)" should be replaced with the name and ID of the GA4 property that is currently set in Site Kit's GA4 settings.
    * The "Property Name (1234567)" should be replaced with the name and ID of the GA4 property that was found using the above lookup.
* Primary CTA: _Use Property Name (1234567)_
    * Replace "Property Name (1234567)" as mentioned above.
    * If the user clicks this CTA, the GA4 settings should be updated with the new configuration identified above via the selector from #6372.
* Secondary CTA: _Update Google tag to keep using Current Property (7654321)_
    * The "Current Property (7654321)" should be replaced with the name and ID of the GA4 property that is currently set in Site Kit's GA4 settings.
    * If the user clicks this CTA, the Google tag settings `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` should be updated with the IDs for the new Google tag that the _current_ GA4 measurement ID points to, which was determined by the logic in #6083.

### Banner notification scenario B: No alternative GA4 config found

* Title: _Your Google tag configuration has changed_
* Description: _The Google tag for your Google Analytics 4 configuration has changed from GT-1234567 to GT-7654321. To keep using your current Google Analytics 4 property "Current Property (7654321)", you need to configure Site Kit to place the new Google tag GT-7654321 instead._
    * The "Current Property (7654321)" should be replaced with the name and ID of the GA4 property that is currently set in Site Kit's GA4 settings.
    * The "GT-1234567" should be replaced with the currently set `googleTagID`.
    * The "GT-7654321" should be replaced with the new `googleTagID` found from the container lookup for the _current_ GA4 measurement ID, which was determined by the logic in #6083.
* Primary CTA: _Update Google tag to GT-7654321_
    * Replace "GT-7654321" as mentioned above.
    * If the user clicks this CTA, the Google tag settings `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` should be updated with the IDs for the new Google tag that the _current_ GA4 measurement ID points to, which was determined by the logic in #6083 (i.e. the one that in the example copy above is "GT-7654321").

## Implementation Brief

Once https://github.com/google/site-kit-wp/issues/6083 have been merged extend the `GoogleTagIDMismatchNotification` banner functionality with the following:
* Filter destinations array using the `isValidMeasurementID` function to leave only valid GA4 measurement IDs
* If no measurement IDs are found, return null
* Otherwise call the `getAnalyticsConfigByMeasurementIDs` selector to find the correct Analytics config for the current measurement IDs
* If a valid Analytics config is returned:
  * Configure `BannerNotification` with a translatable title as per AC
  * Configure `BannerNotification` with a translatable description as per AC
  * By using `ctaComponent` param in `BannerNotification` create the following CTAs (using `SpinnerButton` component):
    * Configure Primary CTA  with a translatable label: *Use Property Name (`1234567`)*
    * Replace "Property Name (`1234567`)" as mentioned above.
    * If the user clicks this CTA, the GA4 settings should be updated with the new configuration identified above:
      * Use `setPropertyID`, `setWebDataStreamID`, `updateSettingsForMeasurementID` (from `dispatch( MODULES_ANALYTICS_4 )`) to update GA4 account settings 
      * Use `submitChanges` to save the above settings
      * Use `isDoingSubmitChanges` together with `saving` to indicate the loading state 
    * Secondary CTA with a translatable label: *Update Google tag to keep using Current Property (`7654321`)*
      * The "Current Property (`7654321`)" should be replaced with the name and ID of the GA4 property that is currently set in Site Kit's GA4 settings
      * If the user clicks this CTA, the Google tag settings `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` should be updated with the IDs for the new Google tag that the current GA4 measurement ID points to
        * Use `updateSettingsForMeasurementID` to set `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` based on `GA4 measurement ID`
        * Use `submitChanges` to save the above settings
        * Use `isDoingSubmitChanges` together with `saving` to indicate the loading state 
* If `getAnalyticsConfigByMeasurementIDs` returns `null`:
  * Configure `BannerNotification` with a translatable title as per AC
  * Configure `BannerNotification` with a translatable description as per AC
    * The "Current Property (`7654321`)" should be replaced with the name and ID of the GA4 property that is currently set in Site Kit's GA4 settings
    * The "`GT-1234567`" should be replaced with the currently set `googleTagID` by using `getGoogleTagID`
    * The "`GT-7654321`" should be replaced with the new googleTagID found from the container lookup for the current GA4 measurement ID, which was determined by the logic in https://github.com/google/site-kit-wp/issues/6083
  * Configure Primary CTA with a translatable label: *Update Google tag to `GT-7654321`*
    * Replace "`GT-7654321`" as mentioned above.
    * If the user clicks this CTA, the Google tag settings `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` should be updated with the IDs for the new Google tag that the current GA4 measurement ID points to, which was determined by the logic above
      * Use `submitChanges` to save the above settings
      * Use `isDoingSubmitChanges` together with `saving` to indicate the loading state 

### Test Coverage

* Extend testing which was previously done for GoogleTagIDMismatchNotification` in https://github.com/google/site-kit-wp/issues/6083
* Write stories for `GoogleTagIDMismatchNotification` that cover all scenarios

## QA Brief

* Setup Site Kit and connect a GA4 Property. For easy testing purposes, go to Site Kit settings and click "Edit in Analytics" next to the Google Analytics 4 Property and rename it to say "GA4 Property 1". Also, in SiteKit settings, note the "Measurement ID" of "GA4 Property 1".
* Go to [Tag Manager admin](https://tagmanager.google.com) and sign in using the same Google Account which has access to the above "GA4 Property 1". On the "Google tags" tab, find the row where one of the Tag IDs is the same as the "Measurement ID" above. The Tag Name would by default be the domain name associated to the GA4 Property. Click on this tag name. On the Tag details pop-up, note down the tag ID beginning with GT (say GT-100000). Delete the destination (GA4 Property 1) from the Destinations list. When asked to attach a tag to the destination, create a new tag and note down its Tag ID (say GT-200000). This will make the original GT-100000 tag not linked to any destination.
* Now go back to the Site Kit plugin and in the browser console, run the following command which forces the Google Tag settings to "sync".
  ```javascript
  googlesitekit.api.set('modules', 'analytics-4', 'settings', {'googleTagLastSyncedAtMs': 0});
  ```
* Reload the plugin and verify the "Banner notification scenario B" is as per the AC.
* Go back to [Tag Manager admin](https://tagmanager.google.com) and once again, locate the row which has a Tag ID the same as the "Measurement ID" from above or the "GT-100000" tag that you noted previously. Click and open up the Tag details and click the "+ Destination" button to add a new destination. Add another GA4 Property from the list of destinations, say "GA4 Property 2". (If there are no destinations in this list, ensure your google account has admin access to another GA4 Property).
* Now go back to the Site Kit plugin and in the browser console, run the above command which forces the Google Tag settings to "sync" again.
* Reload the plugin and verify the "Banner notification scenario A" is as per the AC.
* Also, check the two new Storybook Scenarios created under `GoogleTagMismatchIdNotification`.
* Finally, test other banner notifications in the plugin, especially those that have both, a Primary (CTA Button) and Secondary (CTA Link) since the styles on these have been updated.

## Changelog entry

* Add a notification for users when their Google tag associations change.

**Comment by felixarntz** [comment]
@marrrmarrr I've added preliminary wording to the ACs here, please review and amend as needed.

**Comment by eugene-manuilov** [comment]
> * If the result of `getGoogleTagContainerDestinations` selector (already implemented in the component in [Check GA4 measurement ID mapping from Google Tag periodically #6083](https://github.com/google/site-kit-wp/issues/6083)) includes a result that is another GA4 measurement ID (i.e. starting with "`G-`"):

@sashadoes, #6083 adds another selector `hasGoogleTagIDMismatched` that we need to use in the notification component.

> * Filter and collect all valid GA4 measurement IDs (Only "`G-...`" pattern).

How this should be done?

> * Use `setPropertyID`, `setWebDataStreamID`, `updateSettingsForMeasurementID` (from `dispatch( MODULES_ANALYTICS_4 )`) to update GA4 account settings

Plus, those settings should be saved which means that we need to account for the progress state (show the spinner).

> * If the user clicks this CTA, the Google tag settings `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` should be updated with the IDs for the new Google tag that the current GA4 measurement ID points to, which was determined by the logic in #6083

How should we get the new proper values for these settings? The mentioned ticket doesn't tell anything about that. Also, don't forget that settings should be saved after changing.

**Comment by sashadoes** [comment]
Hi @eugene-manuilov. Thanks for the review and feedback. 
I made a few updates regarding the points that you mentioned, please check.

However, I am not sure about the last one as I took it from the AC:
> * If the user clicks this CTA, the Google tag settings `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` should be updated with the IDs for the new Google tag that the current GA4 measurement ID points to, which was determined by the logic in #6083
I currently don't know how to determine Tag IDs based on Measurement ID...

Should we wait till  #6083 is implemented to proceed with this further or if you know how to write this logic - please share, so I can put it in IB as well. 
Thank you in advance 🙂

**Comment by eugene-manuilov** [comment]
> * I currently don't know how to determine Tag IDs based on Measurement ID...

@sashadoes we have a special selector for it in the `analytics-4` module.

> Secondary CTA with a translatable label: _Update Google tag to keep using Current Property (`7654321`)_
> * The "Current Property (`7654321`)" should be replaced with the name and ID of the GA4 property that is currently set in Site Kit's GA4 settings
> * If the user clicks this CTA, the Google tag settings `googleTagID`, `googleTagAccountID`, and `googleTagContainerID` should be updated with the IDs for the new Google tag that the current GA4 measurement ID points to, which was determined by the logic in [Check GA4 measurement ID mapping from Google Tag periodically #6083](https://github.com/google/site-kit-wp/issues/6083)

Here we also need to save changed settings. The same applies to the second scenario's CTA.

**Comment by eugene-manuilov** [comment]
Adjusted IB a little bit. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

Confirmed issue which Darren reported.
Also, for the case 2 settings showing changed property and measurement id but when user clicks on 'edit' button no property appears under edit mode and tags are not updating in source code.


https://user-images.githubusercontent.com/94359491/226796818-1cedecc4-cc3a-4c2f-997d-47fb2160bcfb.mp4


cc @wpdarren

**Comment by mohitwp** [comment]
### QA Update ❌ 

@jimmymadon 

- Tested on dev.

**Issue 1>** 
For banner B issue still exist-  If the user clicks CTA, the Google tag settings googleTagID, googleTagAccountID, and googleTagContainerID are not getting update 

<details>


https://user-images.githubusercontent.com/94359491/227938805-44454356-4868-4dc7-8b59-f2576911eef8.mp4

</details>

Issue 2>I followed the steps mentioned under QAB. But now Banner A is not showing for this case.

<details>


https://user-images.githubusercontent.com/94359491/227938925-967a4e4d-0da5-4dcd-8636-d447a4bdfc4b.mp4

</details>

**Comment by mohitwp** [comment]
### QA Update ❌ 

@jimmymadon 

- Tested on dev.

**Issue 1>** 
For banner B issue still exist-  If the user clicks CTA, the Google tag settings googleTagID, googleTagAccountID, and googleTagContainerID are not getting update 

<details>


https://user-images.githubusercontent.com/94359491/227938805-44454356-4868-4dc7-8b59-f2576911eef8.mp4

</details>

Issue 2>I followed the steps mentioned under QAB. But now Banner A is not showing for this case.

<details>


https://user-images.githubusercontent.com/94359491/227938925-967a4e4d-0da5-4dcd-8636-d447a4bdfc4b.mp4

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Verified scenarios for both Banner A and Banner B using QAB.
- Verified both banners as per AC.
- Verified both CTA of Banner A.
- Verified CTA of Banner B.
- Issue reported [above](https://github.com/google/site-kit-wp/issues/6373#issuecomment-1478881388) are now resolved.
- **Note** : - For console warning Tom created separate issue - https://github.com/google/site-kit-wp/issues/6784. and for scenario of user selecting different web data streams from different sites, Tom created https://github.com/google/site-kit-wp/issues/6785.
- Also, verified newly added stories - https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-googletagidmismatchnotification--alternative-ga-4-config

<details>

https://user-images.githubusercontent.com/94359491/229424958-dfbf40ae-5168-4da3-af1f-c33539c92281.mp4

**Banner A CTA 1**


https://user-images.githubusercontent.com/94359491/229425119-59923e0e-d92b-4222-b9b9-dabe1014aad6.mp4

**Banner A CTA 2**


https://user-images.githubusercontent.com/94359491/229425277-089aeab2-dee1-479e-8323-213fd78d0e18.mp4

**Banner B**

</details>
