### ISSUE TITLE
Update existing tag handling for Google Tag support

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6374]
Minor adjustments will be needed to support existing tags in combination with the new Google Tag (also called GTE). Site Kit will not support every single edge-case there as that would be a maintenance nightmare for little benefit, particularly it will not cater for the combinations that also take into account Google Tag Manager (if that module is active).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When an existing GA4 tag ("G-") is found during the Analytics setup or settings, the logic to handle it should be slightly adjusted:
    * The `getGoogleTagContainer` selector should be used, passing the existing tag to it (which effectively is the measurement ID).
    * If the Google Tag container returned by that selector includes that same "G-" ID as one of the `tagIds`, then Site Kit should continue to behave as today (if the user chooses the matching property, set the toggle to place the snippet off by default).
    * If the Google Tag container returned by that selector does not include the same "G-" ID as one of the `tagIds`, we are limited by the lack of an API endpoint, which means we can't reasonably determine information on the actual Google Tag with that "G-" tag ID. In other words, in this scenario we should entirely ignore the existing tag and act as if there was none.
* While the additional lookup and logic is running, the relevant parts of the UI should remain in loading state.

For some background context on why the ACs do not include anything around "GT-" tags: We don't need to consider "GT-" tags (the new Google tag ID format) here at all, since any such tags will automatically come with the new Analytics feature to avoid duplicate tracking. Therefore there is no risk in double tagging in such a case, and as such we don't need to look for those tags in the page.

## Implementation Brief

The solution here as discussed with @felixarntz and @aaemnnosttv is to override the GA4 `getExistingTag()` resolver, and encapsulate the described checks for a valid Google Tag within it.

Within `assets/js/modules/analytics-4/datastore/tags.js`:

- If the `gteSupport` feature is enabled, override the `*getExistingTag()` resolver that is in `existingTagStore.resolvers` with a new implementation. This should be copied from the existing implementation in [`createExistingTagStore()`](https://github.com/google/site-kit-wp/blob/80d00b4edff5649105f59aba575a41323de98ccc/assets/js/googlesitekit/data/create-existing-tag-store.js#L163-L174), and modified as follows:
  - Having retrieved `existingTag` via `fetchGetExistingTag()`, retrieve the Google Tag container for the existing tag via the `getGoogleTagContainer()` selector - wait for the selector to resolve via `yield Data.commonActions.await( registry.__experimentalResolveSelect( ...`.
  - If the existing tag is included in the container's `tagIds` array, dispatch the `receiveGetExistingTag()` action with the existing tag.
  - Otherwise, as no valid tag is found, dispatch `receiveGetExistingTag()` with the value `null`.

### Test Coverage

- Add test coverage for the extended behaviour of the GA4 `getExistingTag()` selector and resolver.
- Update any failing tests.

## QA Brief

- Set up Site Kit with the `gteSupport` feature flag enabled.
- Add an existing GA4 tag to the site by adding the gtag snippet to the theme header file.
- Ensure this GA4 tag has a corresponding Google Tag, where the Google Tag has a tag ID and a destination measurement ID that both match the GA4 tag. This is the default configuration for a newly created tag.
  - View the Google Tags on  [tagmanager.google.com](https://tagmanager.google.com/), on the **Google tags** tab.
- Verify the tag is recognised as an existing tag, and Site Kit's existing GA4 tag behaviour continues to work as it does now.
- Repeat the above setup process, but for the following scenarios:
  - Using a GA4 tag which the user doesn't have permission to use.
  - Using a GA4 tag where the measurement ID has been removed as a destination from the container and assigned to another container which doesn't have a matching tag ID.
- In each of these cases, the tag should not be recognised as an existing tag and Site Kit should behave as though no existing tag is present.

## Changelog entry

* Update logic for handling Google Tag detection.

**Comment by bethanylang** [comment]
@hussain-t Checking in on this one as it's a P0 and it looks like it's been assigned to you for some time. Thanks!

**Comment by hussain-t** [comment]
@bethanylang will complete this as soon as possible. Thanks!

**Comment by techanvil** [comment]
Having discussed this with @felixarntz, the IB needs a rework and I've moved the issue back into the IB column to address this.

**Comment by aaemnnosttv** [comment]
@techanvil the IB LGTM, the one thing we might want to add is a resolver for the new `getExistingTag` selector to preserve the "interface" of a selector that is compatible with `resolveSelect`?

**Comment by aaemnnosttv** [comment]
Thanks for expanding on that @techanvil, one more thought –

I wonder if it wouldn't be simpler to override the `getExistingTag` resolver rather than renaming it and reimplementing a new one as the old one would still fetch and receive the `existingTag` state which would be no longer used in this case. The existing resolver follows the standard fetch and receive if not present convention so this seems like it would be perhaps more straightforward?

The overriding of the resolver could be conditional based on the feature flag as well. What do you think?

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, that's a good idea! Have updated the IB again, cheers.

**Comment by aaemnnosttv** [comment]
Great, thanks @techanvil 👍 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 


Verified -

- Tested on dev environment.

- If the Google Tag container returned by that selector includes that same "G-" ID as one of the` tagIds`, then Site Kit behaving as today (if the user chooses the matching property, set the toggle to place the snippet off by default).

- If the Google Tag container returned by that selector does not include the same "G-" ID as one of the tagIds, in this scenario we entirely ignore the existing tag and no notice of existing tag is showing.

- Tested by placing code snippet in Theme header.

- For the below cases – the tag is not recognized as an existing tag and Site Kit behaving as no existing tag is present.

        * Using a GA4 tag which the user doesn't have permission to use.
        * Using a GA4 tag where the measurement ID has been removed as a destination from the container and assigned to another container which doesn't have a matching tag ID.


<details>

![image](https://user-images.githubusercontent.com/94359491/225280327-a2c23429-e9e5-4d55-ae17-f87e3f072fa7.png)

![image](https://user-images.githubusercontent.com/94359491/225281339-5990d441-9c5f-48e1-92aa-0deb6f5d2742.png)

![image](https://user-images.githubusercontent.com/94359491/225280925-0301ea3c-90a1-4b34-a107-0523efcaf755.png)

![image](https://user-images.githubusercontent.com/94359491/225280983-254cb2c5-8662-468a-9f9c-77da3566d4a2.png)

- When Place code toggle option is off -

![image](https://user-images.githubusercontent.com/94359491/225281151-f9a4b425-e805-423f-adc1-fbbe4cd34877.png)

- When Place code toggle option set to ON-

![image](https://user-images.githubusercontent.com/94359491/225281240-e9feb8f2-2057-4988-b440-a4ee688af5d0.png)


- When User don't have permission to use Google tag -

https://user-images.githubusercontent.com/94359491/225281409-4b0cb9ac-3a28-4b01-a802-0c74b8899464.mp4

</details>
