### ISSUE TITLE
Integrate AdSense with AMP Stories

### ISSUE THREAD

**Issue by westonruter** [google/site-kit-wp#639]
## Feature Description

The AMP plugin provides a `amp_story_auto_ads_configuration` filter (https://github.com/ampproject/amp-wp/pull/2492) to allow other plugins to add a configuration for the `amp-story-auto-ads` element. When the AdSense module is active in Site Kit, it should support integrating with this AMP Stories in this way.

See https://github.com/ampproject/amp-wp/issues/2430

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jasti** [comment]
Could we also ensure that Sitekit features like structured data and Google analytics also work similar to AdSense integration?

**Comment by felixarntz** [comment]
@westonruter @jasti This used to not be possible since AdSense itself didn't support AMP Stories. However, that changed in late 2020, and we've since added support for AMP stories (now Web Stories plugin) in#2602 (i.e. this has been part of Site Kit since the 1.27.0 release).
