### ISSUE TITLE
Update use of `setup-php` action to avoid rate limit errors

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6401]
## Feature Description

Some GitHub action runs that involve installing Composer dependencies seem to have failed somewhat randomly when running the dependency prefixing step, in the post-install scripting.

After some investigation, we found that whenever this failure occurred, there was an error during the `setup-php` step which did not cause the action to fail, specifically in the installation of our chosen version of Composer. The error shown is a simple `403: rate limit exceeded`.

See https://github.com/shivammathur/setup-php/issues/679 for context.

TL;DR we need to run the `setup-php` action in an authenticated way so that we do not encounter such rate limits.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The use of the `setup-php` action should be amended to avoid raising rate limit errors

## Implementation Brief

* Update all uses of the `setup-php` action to inherit the current `GITHUB_TOKEN` by passing `${{ secrets.GITHUB_TOKEN }}` through in the step's `env` configuration in each instance where it is used

### Test Coverage

* No change

## QA Brief

* This won't really be possible to QA because the rate limit error is inconsistent – we only exceed it because we're using a shared quota due to the lack of authentication
* We will have to observe this over time to ensure it doesn't happen anymore

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
Moving this ticket to Approval since there is nothing to test.
