### ISSUE TITLE
Remove "Unverified App Screen" interstitial

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#641]
## Feature Description

Remove the "Unverified App Screen" interstitial screen users see when they have added a sensitive scope (by activating Analytics or AdSense for the first time). This screen is no longer required when we enable the new Auth flow.

![image](https://user-images.githubusercontent.com/2676022/66581031-9ad92d00-eb3c-11e9-8257-0740d3e40c76.png)

## Acceptance criteria

* There should no longer be an "Unverified App Warning" screen, in any case. Even if someone is using their own GCP credentials, it is now in their own responsibility, and particularly since this will only used by developers, we don't need to provide this warning anymore.
* The entire functionality for this should be removed from the codebase.

## Implementation Brief

* Remove `\Google\Site_Kit\Core\Authentication\Sensitive_Scopes_Warning`
    - Remove references in `\Google\Site_Kit\Core\Authentication\Authentication`
    - Remove https://github.com/google/site-kit-wp/blob/f0c21c27c2301d83cb172f96e9e13e6b3746f24e/tests/phpunit/integration/Core/Authentication/AuthenticationTest.php#L42-L43

E2E tests should be unaffected by this change as required scopes are granted dynamically by the `Auth` utility plugin.

## Changelog entry

* Remove now unnecessary warning about the Google Cloud Platform app in use being unverified.

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅

**Comment by aaemnnosttv** [comment]
### QA ✅ 

- `Sensitive_Scopes_Warning` class and references removed
- Set up works without displaying any "Unverified app warning"
- No warning displayed before requesting sensitive scopes (Analytics or AdSense)
- Only mentions of the word "unverified" is in regards to site verification
- Word "sensitive" no longer exists in includes or assets

Moving to Approval

**Comment by marrrmarrr** [comment]
LGTM
