### ISSUE TITLE
Simplify in progress state in Analytics activation CTA

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6416]
## Feature Description

Currently the CTA to activate Analytics is replaced by a progress bar after the user clicks the button to "Set up Google Analytics". This results in a minor shift due to the component taking less vertical space which we should avoid.

https://user-images.githubusercontent.com/1621608/212757139-c94d7865-c1f8-4335-87fa-773c0adec1e5.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics activation CTA should not be replaced with a progress bar when the button is clicked. Instead, the primary button should become disabled with an added [spinner appended](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-spinnerbutton--button-with-spinner) as is used in other places (e.g. GA4 activation banner)

## Implementation Brief
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview/OptionalCells.js`,
    * Remove the logic to display the `ProgressBar` and remove the condition to render `ActivateAnalyticsCTA` if `! isNavigatingToReauthURL`.
    * Move the logic to get the value for `isNavigatingToReauthURL` to `assets/js/components/ActivateAnalyticsCTA.js`.
* Using `assets/js/components/ActivateAnalyticsCTA.js`,
    * Replace the `Button` component by the `SpinnerButton` one and adding a new prop `isSaving` with the value set to `isNavigatingToReauthURL`

### Test Coverage
* No new tests to be added.

## QA Brief

* Set up Site Kit on a site, but only activate Search Console, not Analytics.
* Check the CTA to activate Analytics on the dashboard
* After clicking the Spinner Button should appear instead of Progress Bar as per screenshot: 
<img width="881" alt="Screenshot 2023-02-07 at 23 24 14" src="https://user-images.githubusercontent.com/16494321/217390111-07313cad-c62e-4e23-b7e1-f847b606fe51.png">

## Changelog entry

* Show spinner next to Analytics CTA button instead of progress bar in entire widget.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@sashadoes I've noticed that if network is slow and OAuth page takes time to upload then "Set Up Google Analytics" button spinner appears for few seconds and then disappear. After few seconds user gets navigate to OAuth page. 
As per my thoughts "Set up google Analytics" button spinner should appear continuoulsy till than user navigate to OAuth page.  Let me know what are your thougts on this .

**Comment by sashadoes** [comment]
Hi @mohitwp. Could you please write what steps did you take because I struggle to reproduce on my local? 

https://user-images.githubusercontent.com/16494321/218460752-436dd6c6-ae0f-4e0b-83a1-701eb5ed9fba.mov

**Comment by mohitwp** [comment]
@sasha I used mobile internet to test this, not my high speed internet. Is it possible to test this for you on slow speed network ?

**Comment by sashadoes** [comment]
@mohitwp as per the video above, I set the network to `slow 3g` in Chrome same as you but I did not get that behavior 🤔

**Comment by mohitwp** [comment]
@sashadoes I'm able to generate this issue. I'm using Chrome Browser. 

https://user-images.githubusercontent.com/94359491/218469814-f5e26a28-c8a6-4840-aeec-7942dc6e6c83.mp4

My internet speed is -

**Comment by techanvil** [comment]
@mohitwp @sashadoes I was able to reproduce something similar, although in my case the spinner disappeared for a bit and then reappeared. In order to achieve this I set my Chrome throttling to a custom setting of 1kbps down, 1kbps up, and 1000ms latency. @sashadoes, could you see if that also works for you? Admittedly it's not exactly the same behaviour Mohit is seeing, so there's no guarantee fixing this will also fix the behaviour he's seeing, but it's worth a go.

https://user-images.githubusercontent.com/18395600/220595959-e2b7b38c-90b3-41d3-985a-2def0d85306b.mp4

**Comment by mohitwp** [comment]
@aaemnnosttv Please let me know if I need to create a follow-up issue for the observation posted [above.](https://github.com/google/site-kit-wp/issues/6416#issuecomment-1427529307) . Thanks !

cc @sashadoes

**Comment by aaemnnosttv** [comment]
I tested this a number of times with the most throttled being "Slow 3g". The worst experience was that the spinner disappeared briefly before the page started to navigate. IMO this is an acceptable experience and on the whole it is still a good improvement over what it was before.

It's worth noting that the strategy and solution used here is the same that we use in the `ResetButton` so any further enhancement here would also apply there. It's probably worth extracting a common component or reusable hook, etc in another issue where we can further improve the experience and apply that in all instances.

If this is the only observation here, then I think it's okay.

Back to you for any final testing if any @mohitwp !

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main.
- Verified - The Analytics activation CTA replaced with a progress bar when the button is clicked. 

<details>


https://user-images.githubusercontent.com/94359491/220833562-1d349ca3-747b-46fd-9924-566eb7e7acd2.mp4

</details>
