### ISSUE TITLE
Create landing page for setup flow 

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#642]
## Feature Description

In the "canonical" onboarding flow:
- the user clicks "Activate" Site Kit from the plugins page, 
- a banner "Congrats, Site Kit is activated' appears at the top of the page, 
- the user clicks "Start setup" in the banner and is sent to Site Kit Service. 

However, if for some reason the user navigates away from the plugins page and the banner disappears, they lose the entry point to the setup flow. 

Let's create a page that would serve as a starting point in this case. 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The page should appear in the following cases:
1) If the user clicks on the Site Kit menu in the left nav without having completed the setup. 
2) If the user clicks on any of the "Back" links while they're in the Site Kit Service portion of the setup flow. 

The page should contain:
- Heading: "The Site Kit plugin is active but requires setup"
- Text: "Site Kit Service will guide you through 3 simple setup steps." 
- Button: "Start setup"

The regular Site Kit header (with logo and user menu, if user is already connected) should also show on this page as usual.

This screen should not be displayed if the site is not `OAuth_Client::using_proxy()` (see #614), e.g. when direct GCP credentials have been provided via filter.

<img width="474" alt="landing-mock" src="https://user-images.githubusercontent.com/13304791/66747127-0b0ce900-ee84-11e9-9793-ad8a1eafebb8.png">

## Implementation Brief

* Load a new `Setup` component in https://github.com/google/site-kit-wp/blob/f0c21c27c2301d83cb172f96e9e13e6b3746f24e/assets/js/components/dashboard-splash/dashboard-splash-app.js#L151-L157 based on the status of `OAuth_Client::using_proxy()` (see #614). This component should direct the user to the Site Kit proxy install page using `OAuth_Client::get_proxy_setup_url()` when the "Start Setup" link is used.
* Load the existing GCP setup flow if a filter that specifies not to use the proxy is enabled (TBD what that filter is based on #614)

## Changelog entry

* Implement splash screen content pointing the user to the authentication service.

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt I recommend implementing this screen with React components entirely decoupled from the ones of the existing setup flow. However, I think it should continue to be implemented using the existing `googlesitekit-splash` screen because otherwise it would require updating a ton of links and redirects.

Since we'll in the future drop the old setup flow though, the JS implementation should be decoupled (based on `using_proxy()`) in order to make that a quick thing in the future.

**Comment by tofumatt** [comment]
@marrrmarrr A request here on the AC: I think the existing language in the header "The Site Kit plugin is active but requires setup" is a bit technical and could be more instructive. How about "You need to activate the Site Kit plugin" or "Time to set up the Site Kit plugin"… something like that. The first phrase saying that it's "Active" is a bit confusing—it's activated on the WP end, but nowhere else so I find that a bit tougher to parse than just saying what I need to do to move forward.

@felixarntz I'm unclear as to what `using_proxy()` in this context is—I can't find reference to that function (or `usingProxy`) anywhere in the code base. I think it makes sense to leverage the existing setup infra for this and replace the `<Setup />` function in https://github.com/google/site-kit-wp/blob/f0c21c27c2301d83cb172f96e9e13e6b3746f24e/assets/js/components/dashboard-splash/dashboard-splash-app.js#L187 though. What is the `using_proxy()` that you're referring to here?

**Comment by tofumatt** [comment]
Oh, nevermind, I see. It's about the proxy PR that isn't available yet. Sorry about that, I understand.

**Comment by felixarntz** [comment]
Implementation brief ✅

**Comment by tofumatt** [comment]
I'm flagging this an an XS issue because my understanding (from the AC/IB) is that we won't have to support/implement error messaging on this screen if the authenticate flow fails or returns an error.

As long as that's true this one's good to start working on. 😄

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt In the `feature/auth-proxy` branch, there is currently some temporary code to just display the proxy setup link temporarily for testing, from the PHP side: https://github.com/google/site-kit-wp/blob/feature/auth-proxy/includes/Core/Admin/Screens.php#L337-L350

Please remove these lines in the PR for this.

**Comment by tofumatt** [comment]
Awesome, thanks!

To clarify: those lines should be removed from the PR made against the `feature/auth-proxy` branch? I'm a bit confused; I'd think we would have a cleanup branch at the end to remove things like that.

**Comment by aaemnnosttv** [comment]
@felixarntz CR ✅

**Comment by adamsilverstein** [comment]
I QAed this on the `feature/auth-proxy` branch and everything looks good - moving to Approval.

### Testing Procedure
* Build plugin and install on newly spun up `https://jurassic.ninja/` site.
* Activate the plugin.
* Click "Site Kit" in left menu & note the "plugin is active but requires setup"  screen:

![image](https://user-images.githubusercontent.com/2676022/67246538-ee405a80-f41b-11e9-9802-3358689967d9.png)

* Click Start Setup, then click "Cancel" on the next screen
* Note back on the the "plugin is active but requires setup" screen

![image](https://user-images.githubusercontent.com/2676022/67246628-2fd10580-f41c-11e9-820c-64d7f6f9730e.png)

* Click Start Setup again, then click "Sign In with Google" 
* On the "Grant Delegation" screen, click cancel
* Note back on the the "plugin is active but requires setup" screen

![image](https://user-images.githubusercontent.com/2676022/67246745-8c342500-f41c-11e9-8680-962c23cd32e7.png)

**Repeat setup testing steps in Firefox**

Note: to reset site state, do these two things:
* Click the "Manage Site..." link in the user menu dropdown
* Click "Remove Access" next to the correct site
* In Site Kit->Settings click "Disconnect Site Kit"
