### ISSUE TITLE
Enhance experience for existing users to grant new Tag Manager scope for GTE

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6421]
As part of the new `gteSupport` feature, Analytics will start requiring the `https://www.googleapis.com/auth/tagmanager.readonly` scope. Existing users that have Analytics active and don't have Tag Manager active (which is a substantial part of our user base) will be prompted to grant that scope after updating to the version in which the feature is launched (once the feature flag is activated).

The default experience would be the warning about a missing scope, which would be confusing to see since the user was never asked to grant that scope in the first place. So for this particular case we should modify the behavior to make for a smoother experience, most importantly clarify why this scope is now being requested.

In more detail, the default experience today would be:
* User sees admin notice "Site Kit by Google: You need to reauthenticate your Google account." throughout all of WP Admin.
* User sees the below banner notification in the Site Kit dashboard:
<img width="1038" alt="Screen Shot 2023-01-17 at 11 42 08 AM" src="https://user-images.githubusercontent.com/3531426/212878404-e29eabc0-cb63-4f93-b43c-5c5fb11c33fe.png">

See the ACs for what needs to change in the particular scenario.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

_If_ the `gteSupport` feature flag is enabled _and_ the user has Analytics active _and_ the user does not have Tag Manager active _and_ the only scope that the user has not granted is `https://www.googleapis.com/auth/tagmanager.readonly`:
* The PHP-based admin notice "Site Kit by Google: You need to reauthenticate your Google account." should be suppressed / not be shown for this particular situation.
* The copy of the `UnsatisfiedScopesAlert` should be changed _only_ for this particular situation, to explain why the user needs to grant a new scope (for the new Google tag functionality):
    * Notification title: _Site Kit needs additional permissions to detect updates to tags on your site_
    * Notification description: _To continue using Analytics with Site Kit, you need to grant permission to check for any changes in your Google tag's target Analytics property. Recent updates to the Google tag enable changing which Analytics property it’s connected to without editing the code on the site, so Site Kit must regularly check if the tag on your site matches the Analytics property destination. [Learn more](https://support.google.com/tagmanager/answer/11994839)_
    * Notification button: _Grant permission_
    * The button should behave as before: When clicking the user will be brought to OAuth where they will be prompted to grant the scopes, including the new Tag Manager one.

## Implementation Brief

* In `UnsatisfiedScopesAlert.js`
  * Add a new `MESSAGE_` constant to the top for the case mentioned in the AC.
  * Extend the if/else statement to check for the missing `https://www.googleapis.com/auth/tagmanager.readonly` scope and enabled `useFeature( 'dashboardSharing' );`. Set `messageID` to the new constant from above.
  * As already done with `let message;` also add variables for `ctaLabel` and `title`.  By default assign the values that are currently directly assigned to `<BannerNotification />` component. Pass these variables to the `<BannerNotification /> component.
  * Add a new switch statement case for the new `MESSAGE_*` constant and add / change message, title, ctaLink labels as mentioned in the AC.
* In `includes/Core/Authentication/Authentication.php` update the `activate_callback` function https://github.com/google/site-kit-wp/blob/9039f5c3577541b3a92f82f04a45a5858022a170/includes/Core/Authentication/Authentication.php#L1217-L1223
  * Get the unsatisfied scopes with `$this->get_oauth_client()->get_unsatisfied_scopes()`
  * If `dashboardSharing` feature flag ist active and the unsatisfied scopes array includes `https://www.googleapis.com/auth/tagmanager.readonly` as its only item, return false.

### Test Coverage

* Add a new test in `ErrorNotifications.test.js` to test for this error case.

## QA Brief

* Ensure the `gteSupport` feature flag is disabled and setup Site Kit with Analytics. Now enable the `gteSupport` feature flag and verify the `UnsatisfiedScopesAlert` as per the AC.

## Changelog entry

* Enhance experience for existing users who need to grant a new Tag Manager scope for use with Google Tags.

**Comment by felixarntz** [comment]
@bethanylang This is a new GTE issue that we had forgotten to think about prior. Pending only wording from @marrrmarrr, this should be a fairly small one to get through though.

**Comment by marrrmarrr** [comment]
@felixarntz I updated the wording here, let me know if this is accurate to your understanding of how GTE works. 
Am I understanding correctly that this is an undismissable notice?

**Comment by felixarntz** [comment]
Thanks @marrrmarrr. Correct, the notice is not dismissible as it is critical and should be acted upon right away to keep Site Kit functional.

Will move this to IB.

**Comment by eugene-manuilov** [comment]
> * The PHP-based admin notice "Site Kit by Google: You need to reauthenticate your Google account." should be suppressed / not be shown for this particular situation.

@derweili, we also need to add this part of AC to IB ^

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@derweili @felixarntz I have a number of observations that I'd like to share. 

1. When I click on the grant permissions button, for 2-3 seconds the dashboard re-appears and then the oAuth pops up. Feels an odd user experience.  I have fast internet connection but for slower connections it will feel a little longer before the user is asked to give permission.  Is this expected? Screencast below. 

https://user-images.githubusercontent.com/73545194/222022442-81504cee-f190-4e5c-8707-fceb74c8b8b3.mp4

2.  The permissions message appears below the navigation, when in gathering or zero data state. Do you feel that this needs to take priority and appear at the top?

![image](https://user-images.githubusercontent.com/73545194/222021228-66e133cb-b7e4-4465-931c-26bc8d934324.png)

3. I suspect that this is correct but I would like to check.  When you navigate outside of the dashboard, e.g. to the Site Kit settings, the message still appears.  Is this correct? 

![image](https://user-images.githubusercontent.com/73545194/222024339-ec7f698b-bb7b-46c7-92da-54db702e34df.png)

4. A question re the QAB.  Should we check anything in the source code or within the Analytics account related to this change?  If so, what should I look out for?

**Comment by felixarntz** [comment]
Thanks @wpdarren @jimmymadon for the feedback. Some replies:
1. Agreed that this is a general problem and therefore shouldn't be a blocker here specifically. We had this problem with some other banner in the past though, and we should fix it, essentially we have to ensure that the banner remains there for that current page load, even once it's technically been dismissed. Let's open a new issue to fix this for the unsatisfied scopes alert in general indeed. cc @aaemnnosttv 
2. This is a general concern as well, I actually talked about that with @marrrmarrr and @aaemnnosttv  the other day. We'll change that in the near future so that all banners will only appear above the navigation, in which case the alert would take precedence (is there already an issue for that?).
3. This is okay as is, no need to change anything.
4. All good as is.

**Comment by wpdarren** [comment]
Thanks @felixarntz for the clarification here. 

I will create a ticket for point 1 and check to see if we have a ticket for point 2, if not will create one.

### QA Update: ✅ 

**Verified:**

- The `UnsatisfiedScopesAlert` as per the AC.
 - The PHP-based admin notice `Site Kit by Google: You need to reauthenticate your Google account.` is not shown for this particular situation.
 - The copy of the `UnsatisfiedScopesAlert` is changed only for this particular situation.
    - Notification title: Site Kit needs additional permissions to detect updates to tags on your site
    - Notification description: To continue using Analytics with Site Kit, you need to grant permission to check for any changes in your Google tag's target Analytics property. Recent updates to the Google tag enable changing which Analytics property it’s connected to without editing the code on the site, so Site Kit must regularly check if the tag on your site matches the 
    - Analytics property destination. [Learn more](https://support.google.com/tagmanager/answer/11994839)
    - Notification button: Grant permission
    - The button behaves as before: When clicking the user will be brought to OAuth where they will be prompted to grant the scopes, including the new Tag Manager one.
 - I tested this banner on all of our supported browsers
 - I tested this on smaller screen sizes. 
 - I tested to make sure that the admin notice `Site Kit by Google: You need to reauthenticate your Google account.` still does appear for the correct scenario, i.e. when a user does not give permission. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/222417186-142bc435-96d5-4d9a-a6ae-eca6f2d93a70.png)
![image](https://user-images.githubusercontent.com/73545194/222417207-9a36bd3b-4c9d-4aa6-a40e-e87856253475.png)

</details>

**Comment by wpdarren** [comment]
@felixarntz @aaemnnosttv.

I created a ticket for point one #6673 and #6634 was already created for point 2, the banner placement issue. 👍
