### ISSUE TITLE
Update User Input preview edit links when saving questions for consistency

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6427]
## Bug Description

For the user input feature, when you complete the 3 questions the review screen appears. Currently, when you click on the 'save button' the edit links for each question are active while in `in-progress state` (the spinner animation appears). Since we make the cancel link not clickable and appear deactivated, we should do this with the edit links. 

It is worth noting that when you do click on the edit links, the fields are deactivated but it would be a better UX if the edit links were not clickable and appeared deactivated. Discussed this with UX on [Slack here](https://10up.slack.com/archives/C01CA828ZPZ/p1673951642950729). 

https://user-images.githubusercontent.com/73545194/213146806-61e818c6-a249-4e52-951e-d45d207df852.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Edit` links on every question should not be clickable and appear as such (disabled state) when answers are being saved. 

## Implementation Brief

- In `assets/js/components/user-input/UserInputPreviewGroup.js`:
    - We want to update the disabled state (i.e. `isSavingSettings`) here to also consider if the page is navigating, similar to `<UserInputPreview />`.
		- Simiar to `<UserInputPreview />`, create a new variable, say `isScreenLoading`, that returns `true` if either `isSavingSettings` is truthy, or if the user is navigating somewhere else. The navigation can be determined by using the `isNavigating()` selector from the `core/location` store.
		- Replace all usages of `isSavingSettings` in the rendered JSX with `isScreenLoading`.
	- For the `Edit` `<Link />`, remove the requirement for `showIndividualCTAs` to be available for its `disabled` logic to work.
- In `assets/sass/components/user-input/googlesitekit-user-input-preview.scss`:
	- For the `:disabled` state of the `.googlesitekit-user-input__preview-group-title button` element:
    	- Add styles so that it has a `color` of `$c-silver`.
		- Add styles for its expand more icon (arrow/chevron down, i.e. `:after`) so that the SVG is changed to the `$c-silver` color.

### Test Coverage

- No tests need to be added/updated.

## QA Brief
* Go to the user input screens. (wp-admin/admin.php?page=googlesitekit-user-input)
* Fill in the 3 questions and pause at the screen where you review your answers.
* Ensure each "Edit" button toggles its corresponding panel.
* Ensure answers are updated when choosing a different answer after closing a panel.
* Disabled panels should have their corresponding "Edit" button disabled and styled as such.
* Upon clicking "Save", all "Edit" buttons should be disabled.

## Changelog entry

* Update User Input preview edit links when saving questions to be consistent with other disabled elements.

**Comment by tofumatt** [comment]
ACs here are good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that Edit links on every question are clickable and appear as such (disabled state) when answers are being saved.
- Verified each "Edit" button toggles its corresponding panel.
- Verified answers are updated when choosing a different answer after closing a panel.
- Disabled panels shave their corresponding "Edit" button disabled and styled as such.
- Upon clicking "Save", all "Edit" buttons getting disabled.

<details>


https://user-images.githubusercontent.com/94359491/218708954-c4e705ad-e51d-4c50-b46b-f9fa44a09d8f.mp4

</details>
