### ISSUE TITLE
Add link to Site management section of Site Kit service 

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#643]
## Feature Description

Users will be able to see the full list of sites they own which have Site Kit installed and remove access of each site to their (SC|GA|AdSense|PSI) stats. This list will live on Site Kit Service; let's create a link from within the plugin for them to access it. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Google account drop down menu in the top right corner, if the current user is already connected, add a new entry below "Disconnect": "Manage sites...".
* The link should point to Site Kit Service (`https://sitekit.withgoogle.com/site-management/permissions/?token={access_token}&site_id={site_id}`) (see #614: `OAuth_Client::get_proxy_permissions_url()`).

## Implementation Brief

* Only add the menu item if `proxyPermissionsURL` is available.  (`proxyPermissionsURL` is localized in the [proxy PR.](https://github.com/google/site-kit-wp/pull/614/files#diff-ea6eaf1ebe59efbcdb67e69db824537bR605) only when the user access token is available). 
* In the `UserMenu` component (`assets/js/components/user-menu.js`), add a new `Manage sites...` item to the `menuItems` array passed as props to the `Menu` component.
* In the `handleMenuItemSelect` function, add a new switch condition handler which redirects to user to the `proxyPermissionsURL` URL when "Manage sites..." is selected.

## Changelog entry

*

**Comment by felixarntz** [comment]
Implementation brief ✅

**Comment by tofumatt** [comment]
Assuming we'll have access to the needed data from the server (eg `access_token` and `site_id`) already this is a very straightforward task. If it requires hooking things up this is closer to a small size task, so for now I've labelled it XXS but this should be updated if it's more than just the straightforward "conditionally adding a link"-type issue this appears to be. 😄

**Comment by adamsilverstein** [comment]
Confirming this passes QA, moving to Approval.

### Testing procedure
* Build a release zip on the `feature/auth-proxy` branch
* Testing on a live site, verify the dropdown menu shows the "Manage  Sites..." entry and links to the proper URL to show connected accounts.

![image](https://user-images.githubusercontent.com/2676022/67108811-84f6e800-f18c-11e9-85a7-8117245bf2d9.png)


This linked to the page on site kit showing my connected site:

![image](https://user-images.githubusercontent.com/2676022/67108728-58db6700-f18c-11e9-926d-bdfc2fec1c81.png)

One thing I noticed (unrelated to this ticket) on this screen was the formatting seemed odd, my site name appeared above the site URL (I would expect them to appear side by side).
