### ISSUE TITLE
Fix the Connect More Services story in Storybook.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6438]
## Bug Description

At the moment, the Analytics 4 module is showing as a connectable module in the Connect More Services story.

Analytics 4 should not be present on this screen.

## Steps to reproduce

1. Navigate to the story on [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/settings--connect-more-services).
2. View the erroneous story.

## Screenshots

![image](https://user-images.githubusercontent.com/18395600/213500194-f062c9bd-b8e3-4b6c-905f-47818b662d69.png)

## Additional Context

 - PHP Version: N/A
 - OS: any
 - Browser: any
 - Plugin Version: seen in 1.92.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics 4 module should not be displayed as a connectable module in the Connect More Services story.
* As Analytics 4 doesn't show up on the Connect More Services screen on the plugin, this story should be fixed without any change to production code.

## Implementation Brief

- Add an `analytics-4` entry to `assets/js/googlesitekit/modules/datastore/__fixtures__/list.json`.
  - Ensure `internal` is set to `true`, while `active` and `connected` are both `false`.
- Ensure all JS tests still pass. An initial test run indicates they will do.
- Check all Storybook stories that make use of this fixture, which are those using the `withActive`, `withConnected` and `provideModules` helper functions.
  - Ensure the stories are unchanged, other than Connect More Services (and any others which may be discovered to need correcting).
  - Note that an initial test VRT run does not raise any related errors, although all stories will need to be checked, not just the VRT scenarios.

### A note to the IB reviewer:

There is a less impactful solution which is as follows, however it does seem more correct to update the reusable fixture as detailed above, especially considering how we'll be deprecating/removing UA support in the not too distant future. If you are happy to keep the above implementation then please remove this section, however I'm leaving this here for now, for the sake of consideration. The estimate has been made assuming we're taking the first solution.

- Within the `setupRegistry` call for the Connect More Services story in `stories/settings.stories.js`:
  - Update the call to `provideModules` to include a definition for the `analytics-4` module with its `internal` property set to `true`.

### Test Coverage

* Update the VRT reference images for the story (and any others which may be found to need updating).

## QA Brief

- Verify the [`Connect More Services` Storybook story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/settings--connect-more-services) doesn't include the Analytics 4 module.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
I would have normally estimated this a 3. Bumping to a 7 to add the `Exp: SP` label but it really shouldn't need it.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@nfmohit 
I'm not able to see 'analytics 4 module' on main also under storybook. Are changes already pushed to main also ?
[Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/settings--connect-more-services)


- Tested on dev.
- Tested [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/settings--connect-more-services).
- Verified The Analytics 4 module is not displaying as a connectable module in the Connect More Services story.
- 

<details>

![image](https://user-images.githubusercontent.com/94359491/217440621-088f7654-a877-4394-be01-ca66eaa60874.png)

</details>

**Comment by nfmohit** [comment]
Hi @mohitwp! You are right. `main` is now updated for 1.94.0.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Tested [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/settings--connect-more-services).
- Verified The Analytics 4 module is not displaying as a connectable module in the Connect More Services story.

<details>

![image](https://user-images.githubusercontent.com/94359491/217440621-088f7654-a877-4394-be01-ca66eaa60874.png)

</details>
