### ISSUE TITLE
Prevent the Analytics 4 module from being displayed unexpectedly in the UI.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6446]
## Feature Description

Due to the `shareable` flag being set for the GA4 `GET:report` datapoint (introduced in #6172), the Analytics 4 module is now determined to be a shareable module and thus displayed in the Dashboard Sharing modal.

Note: To enable the GA4 `GET:report` datapoint, turn on the `ga4Reporting` feature flag.

![image (3).png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/600546b3-8ea1-485b-b56a-8b9f59242110)

We need to prevent the GA4 module from appearing in the Dashboard Sharing modal, while ensuring the Analytics sharing settings also apply to the GA4 module so that the `GET:report` endpoint can be shared.

We should also ensure that the GA4 module does not appear in any other unexpected places in the UI, for example the Recover Modules modal.

It might be advisable, rather than taking GA4 as a special case, to make the solution generically applicable to all modules which are flagged as `internal` and are also shareable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* With the `ga4Reporting` feature enabled:
  * The GA4 module should not be displayed on the Dashboard Sharing modal, the Recover Modules modal, or anywhere else unexpected in the UI.
  * The Analytics sharing settings should apply to GA4 for the purpose of data sharing (i.e. the GA4 `GET:report` endpoint should be shareable when the Analytics module is shareable).
* This should be implemented in a generic way that is applicable to any module which is flagged as `internal` and is also shareable.

## Implementation Brief

* In `assets/js/googlesitekit/modules/datastore/modules.js`, add a new selector, `getShareableModules` with the following logic:
  * Extract the `shareableModules` logic from the `DashboardSharingSettings` component and omit the `getID` selector. See:
  https://github.com/google/site-kit-wp/blob/fed8b39662bcf31f1866033afa1da409debdb9bd/assets/js/components/dashboard-sharing/DashboardSharingSettings/index.js#L48-L57
  * Add a condition that checks if the module is not `internal` along with the existing `shareable` condition.
  * Return the result of the `filter` function.
* In `assets/js/components/dashboard-sharing/DashboardSharingSettings/index.js`, replace the `shareableModules` logic with the value returned by the new `getShareableModules` selector.
* In `assets/js/googlesitekit/modules/datastore/modules.js`, update the `*getRecoverableModules` resolver to check if the module is not `internal` along with the existing `recoverable` condition.

**Note:** We could work on the logic on the server; however, our current codebase checks whether a module is `shareable` or `recoverable` on the client side. So, it's better to keep the logic on the client side.

### Test Coverage

* Add a test case for the `getRecoverableModules` selector to ensure that the `internal` modules are not returned.
* Add tests for the `getShareableModules` selector.

## QA Brief

* Check the Dashboard sharing with Analytics and GA4 modules enabled
* GA4 should not be displayed anymore 
<img width="1313" alt="Screenshot 2023-02-14 at 16 11 19" src="https://user-images.githubusercontent.com/16494321/218793792-6b1ed1b2-9601-4a3d-839a-3c4ead1f48de.png">

## Changelog entry

* Prevent "Analytics 4" from appearing separate from "Analytics" in Dashboard Sharing settings when `ga4Reporting` is enabled.

**Comment by tofumatt** [comment]
ACs here are good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
@sashadoes 
In AC, it is mentioned that The GA4 module should not be displayed on the Recover Module's modal. Can you please guide how can I access this modal ?

**Comment by sashadoes** [comment]
Hi @mohitwp, I don't know what is the Recover Module's modal, sorry. 
@techanvil could you please jump in here?

**Comment by techanvil** [comment]
As mentioned on Slack, the "Recover Modules modal" refers to the `ModuleRecoveryAlert` component as seen [here]( https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-modulerecoveryalert--multiple-recoverable-module-no-access). It's actually an alert (implemented as a notification) rather than a modal, this was a mistake in the description.

Searching for `ModuleRecoveryAlert` will find related issues which have QABs that can help determine how to test it, for example https://github.com/google/site-kit-wp/issues/5287.

However, these may not specifically cover how to get the Analytics module showing in the alert.

This can be achieved as follows:

- Set up Site Kit, without setting up Analytics.
- Enable the `dashboardSharing` feature flag.
- As a second admin:
  - Set up Site Kit and connect Analytics.
  - Using the Dashboard Sharing modal, enable sharing for Analytics.
  - Disconnect Site Kit.
- Log back in as the first admin, and you should see the `ModuleRecoveryAlert` component in the following state:

![image](https://user-images.githubusercontent.com/18395600/219677495-1c66a2f5-efa5-4847-b643-efcf0b523527.png)

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Tested dashboard sharing modal, Recover Module's modal and other places.
- The GA4 module is not displaying on the Dashboard Sharing modal, the Recover Modules modal, or anywhere else unexpected in the UI.


<details>

![image](https://user-images.githubusercontent.com/94359491/220062492-463bf489-95da-4eca-9242-79903929deb5.png)

![image](https://user-images.githubusercontent.com/94359491/220062576-5a02d5cc-913a-432c-8b94-225ff67e4b77.png)

![image](https://user-images.githubusercontent.com/94359491/220062657-759ce647-937a-4f91-8ccd-a31c133f0168.png)

![image](https://user-images.githubusercontent.com/94359491/220062908-48dcd9b5-7777-40e7-99d8-99245883f2a5.png)

![image](https://user-images.githubusercontent.com/94359491/220064266-200d7c86-9dd9-431e-82c0-8be6c52e1bb3.png)

</details>
