### ISSUE TITLE
Use proper BEM syntax for GM3 Checkbox class name.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6447]
## Feature Description

As discussed in the [GM3 phase 1 one-pager](https://docs.google.com/document/d/1e6ZS1rJzc6IjNQE2crugab7DJ-47hSbiHzem0gFgt48/edit?disco=AAAAnuC9sfc), the use of the double underscore in the `Checkbox` class name `googlesitekit-component-gm3__checkbox` is a slight deviation from correct BEM syntax.

We should update to use a single underscore for consistency with the spec for the other GM3 components, i.e. `googlesitekit-component-gm3_checkbox`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GM3 `Checkbox` should use the class name `googlesitekit-component-gm3_checkbox`.

## Implementation Brief

- Replace all instances of `googlesitekit-component-gm3__checkbox` with `googlesitekit-component-gm3_checkbox`, i.e. replace double underscores with a single underscore, in the following files:
    - `assets/js/googlesitekit/components-gm3/Checkbox.js`
	- `assets/sass/components-gm3/components/_checkbox.scss`
	- `assets/js/googlesitekit/components-gm3/__snapshots__/Checkbox.test.js.snap`

### Test Coverage

- The above replacements take place in one Jest snapshot, among other files.
- No other tests need to be added/updated.

## QA Brief

* Verify the `Components/Material 3/Checkbox` story hasn't changed.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Hey @nfmohit, is this estimate bumped up one, i.e. should it have the `Exp: SP` label applied?

**Comment by nfmohit** [comment]
> Hey @nfmohit, is this estimate bumped up one, i.e. should it have the `Exp: SP` label applied?

Ah, sorry, missed it. Added now, thanks @techanvil!

**Comment by techanvil** [comment]
Thanks, @nfmohit!

IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified Components/Material 3/Checkbox story on dev.
- GM3 checkbox class name changed successfully on dev.
- Change to class name not caused any change to story.


<details>

![image](https://user-images.githubusercontent.com/94359491/216601336-d8affcfb-f285-4d00-a446-fb3d1f7a08f3.png)

</details>
