### ISSUE TITLE
Add support for Site Kit proxy service

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#645]
## Feature Description

In order to make the plugin setup and authorization for accessing Google APIs a more seamless process, the plugin is going to use a proxy service living on sitekit.withgoogle.com. This issue is about integrating the plugin with the proxy.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Unless a developer has filtered in GCP client credentials, the plugin should be using the proxy. A mechanism should exist to easily check whether the plugin is relying on the proxy.
* If the proxy is being used (default):
    * The plugin should send the user to `sitekit.withgoogle.com/site-management/setup/`, with query parameters `nonce`, `name`, `url`, `rest_root`, and `admin_root`.
    * There should be a REST route `google-site-kit/v1/oauth/site` that accepts parameters `nonce`, `site_id` and `site_secret`. The passed nonce should be validated as being the same nonce that was previously passed to the external setup URL. Site ID and secret should be saved.
    * If a site ID is already stored, the setup URL should receive only that as a `site_id` parameter, instead of all the other parameters listed above.
    * Instead of relying on Google's own OAuth URLs, the plugin should rely on the following URLs (for the respective actions):
        * `https://sitekit.withgoogle.com/o/oauth2/auth/`
        * `https://sitekit.withgoogle.com/o/oauth2/token/`
        * `https://sitekit.withgoogle.com/o/oauth2/revoke/`
    * If an error comes back from the OAuth request and it's not one of the ones already handled (i.e. a typical OAuth error), the plugin should check whether there is also a `code` parameter/key present, and if so, send the user back to the setup route, with the available site ID and that `code`. This is so that the user can complete additional requirements that are needed before the site can receive their access token.
* Permissions should be modified so that only administrators can authenticate. While this currently means a restriction so that only administrators can use the plugin by default, it is necessary because of the new verification requirement. Allowing non-administrators to automatically become verified site owners is irresponsible as default behavior - the permission can still be modified by developers so that less privileged users can authenticate again, but this has to be decided with care.
* Additional note: Refresh tokens sent to the plugin will be encrypted so that they are not usable with OAuth directly. This is probably irrelevant for this implementation, but important to know.

## Implementation Brief

* Add method `using_proxy()` to `OAuth_Client` class.
* Add method `get_proxy_setup_url()` to `OAuth_Client` class.
* Add method `get_proxy_permissions_url()` to `OAuth_Client` class.
* Introduce class `Google_Proxy_Client` that extends the external `\Google_Client` and tweaks the behavior to work with the proxy (since it's almost monitoring the exact OAuth behavior).
* Use that `Google_Proxy_Client` in the `OAuth_Client`.
* Introduce `Google_Proxy_Exception` as special exception that also provides a temporary access code for a token not yet delegated to the site (so that that can be specifically caught).
* In `OAuth_Client::authorize_user()`: Catch `Google_Proxy_Exception` and redirect user back to proxy setup URL with the code from the exception.
* In `OAuth_Client::refresh_token()`: Catch `Google_Proxy_Exception` and store both error and code from the exception in a temporary user option.
* In `OAuth_Client::get_error_message()`: If there is a code set (see previous bullet point), include a link in the error message to go back to the proxy setup to fulfill the unmet requirements.
* Modify `Permissions::AUTHENTICATE` permission to map to `manage_options` instead of `edit_posts`.

## Changelog entry

* Add support for authentication proxy, replacing the previous authentication mechanism using individual GCP projects.

**Comment by aaemnnosttv** [comment]
CR Approved ✅ 🎉

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Criteria:
- Filtering `googlesitekit_oauth_secret` with GCP credentials does not invoke the proxy setup flow
- Proxy setup sends the user to `https://sitekit.withgoogle.com/site-management/setup/` with query parameters:  
  - `nonce` a WP nonce
  - `name` URL-encoded site name
  - `url` URL-encoded home URL
  - `rest_root` URL-encoded REST URL root, relative to home URL
  - `admin_root` URL-encoded admin URL root, relative to home URL
  - `scope` URL-encoded space-separated list of requested OAuth scopes
- REST route exists  
![image](https://user-images.githubusercontent.com/1621608/67300088-2025ef80-f4f6-11e9-8677-6a62583f9035.png)
- Returning to Proxy to manage connected sites sends the user to `https://sitekit.withgoogle.com/site-management/permissions/` with query parameters:  
  - `token`
  - `site_id`
- Site Kit interfaces are only available to users with `administrator` role by default

> Additional note: Refresh tokens sent to the plugin will be encrypted so that they are not usable with OAuth directly. This is probably irrelevant for this implementation, but important to know.

Unable to QA this detail

**Moving to Approval**
