### ISSUE TITLE
Make it clearer for users that UA will stop recording data after July 1

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#6453]
## Feature Description

Let's make the notice encouraging users to set up GA4 clearer about the relation between UA/GA4 and the time constraints. 
The current banner explains that very briefly with one sentence below the main heading: 

![image](https://user-images.githubusercontent.com/13304791/214321645-4be50db2-1f3c-4d42-b693-b0db57745414.png)

Josh (tech writer) has reviewed and suggested new wording. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update the current text below the main heading to the following: 
> _Google Analytics 4 is the newest version of Google Analytics. It will replace Universal Analytics on July 1, 2023. After that, Universal Analytics properties will no longer collect new data._

## Implementation Brief

* Update the text/sub-heading of the GA4 activation banner per the AC

### Test Coverage

* No tests needed/VRTs should be updated, if needed.

## QA Brief

* Trigger the GA4 setup banner (one way to do this is to set up a new site, then manually delete the `googlesitekit_analytics-4_settings` row from the `wp_options` table in the site's database) 
* Check that the new text from the ACs appears in the notice.
  * _Note:_ Only check for this text change, don't compare design elements from the screenshot in the issue to the plugin.

## Changelog entry

* Update wording regarding the date Universal Analytics will stop collecting data.

**Comment by wpdarren** [comment]
### QA update: ✅ 

**Verified:**

- The text now reads as per the AC.  `Google Analytics 4 is the newest version of Google Analytics. It will replace Universal Analytics on July 1, 2023. After that, Universal Analytics properties will no longer collect new data.`

<img width="1653" alt="gan" src="https://user-images.githubusercontent.com/73545194/233993923-badc893c-2065-4e14-bbe9-81baa4816294.png">

**Comment by aaemnnosttv** [comment]
LGTM 👍
