### ISSUE TITLE
Remove the &amp between the AdSense publisher ID and the AdSense for platforms ID

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6458]
## Bug Description

When Site Kit is used to insert the AdSense snippet on a users site, it inserts the standard AdSense users publisher ID and also the plugins AdSense for Platforms ID. Between these snippets there is an ampersand (&amp), highlighted below. This isn't required as far as I know. If this is the case , consider removing it. 

`<script async="async" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-346716188968****&amp;host=ca-host-pub-264453626735****" crossorigin="anonymous" data-overlays="{bottom: true}" type="text/javascript"></script>
`

<kbd> ![image](https://user-images.githubusercontent.com/41326532/214651516-2f47e653-3700-43fd-8c55-b64981764b72.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by wpdarren** [comment]
@jamesozzie Do you have any objections if I label this enhancement? It doesn't feel like a bug, but I am happy to be told otherwise if it's causing issues with users!  😄

**Comment by jamesozzie** [comment]
No objections @wpdarren. And no issues with users, and AdSense team rep pointed it out in a call.

**Comment by aaemnnosttv** [comment]
This is standard behavior of `esc_attr` which happens within `wp_sanitize_script_attributes`. We don't add it :)

https://github.com/google/site-kit-wp/blob/58b493e03ea36283ef4184eb3bc3ecf9788b5555/includes/Modules/AdSense/Web_Tag.php#L57

I can confirm that the JS src is requested properly though

![image](https://user-images.githubusercontent.com/1621608/219492087-31c19eef-eb83-4363-bc57-6e4a9f179f03.png)

Closing as a non-issue 👍
