### ISSUE TITLE
Implement update routine to remove old client credentials

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#646]
Addressed by PR #671 

---

## Feature Description

For the update to the new plugin version containing the proxy, an update routine should run that clears the old credentials and all related data.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be an update routine that fires for any update from an older version:
    * If there is an existing client ID and secret stored in the DB which are not for the Site Kit authentication proxy...
        * Remove all user credentials (access tokens, refresh tokens etc., but NOT verification data).
        * Remove the existing client credentials.
        * Set a flag in the DB that this used to be an old version without the proxy.
* If the flag in the DB is set that this used to be an old version without the proxy...
    * Show a regular WP admin notice across the entire admin informing them about the new authentication mechanism.
    * Copy: "We’ve made a lot of improvements to get Site Kit ready for general release! In order to use this new version, you’ll need to go through the updated setup flow to re-generate your credentials. Once you’re done, all your data will still be there."
    * Show a button "Reconnect Site Kit" that links to `get_proxy_setup_url()` (see #614). Clicking it should also remove the above DB flag so that the notice disappears.
    * Show a secondary link-like button "Ignore" that simply removes the DB flag so that the notice disappears. Clicking that should dismiss the notice.

Note that users can still re-connect the plugin by going to the regular Site Kit dashboard (related: #642) after just ignoring the notice.

#### Create single class to handle the majority of migration support between beta (pre-proxy) to stable/proxy

Create a `\Google\Site_Kit\Core\Util\Beta_Migration` class for handling beta upgrade routine and user-facing elements
* Load this via `Plugin::register()`

#### Upgrade
* Hook upgrade to run on `admin_init`
* Run if the current DB version (see below) is less than `1.0.0` or if no DB version exists
* Check for existing client ID (pre-proxy) (e.g. not `*.apps.sitekit.withgoogle.com`)
    - If found, delete both ID and secret and set an option flag to identify this for later  
    E.g. `googlesitekit_pre_proxy_install`
    - If NOT found, update DB version to prevent running again
* When upgrade completes, update `googlesitekit_db_version` option with the new DB version (`1.0.0`)
* Add `googlesitekit_pre_proxy_install` option to `Reset`
* Add `googlesitekit_db_version` option to `Reset`
* Basic PHPUnit coverage

#### User-facing changes & behavior
* Check for `googlesitekit_pre_proxy_install` on `admin_init` (later than upgrade)
    - Add a persistent notice (see copy in AC) if present
    - Notice should have buttons for reconnecting Site Kit and ignoring/dismissing
    - Notice should only display for users who can `Permissions::SETUP`
* Notice button handling for Reconnect / Ignore actions
    - Add `googlesitekit_pre_proxy_action` (`reconnect|dismiss`) and `_wpnonce` query params to the current URL
    - Delete DB flag on submit
    - Redirect user to appropriate URL according to action

## Changelog entry

*

**Comment by felixarntz** [comment]
@marrrmarrr Can you add the exact wording we should use for the admin notice to the ACs?

**Comment by felixarntz** [comment]
IB ✅ 

Two small notes:
> Check for `googlesitekit_pre_proxy_install` on `admin_init` (later than upgrade)

Might be more appropriate to happen in `admin_notices` / `network_admin_notices`.

> Redirect user to appropriate URL according to action

When dismissing, the user should preferably not be redirected, just the notice should go away. However in case this takes considerably more time to implement, then redirecting to the same page (where the notice would no longer appear then) could be an okay compromise.

**Comment by aaemnnosttv** [comment]
> Might be more appropriate to happen in `admin_notices` / `network_admin_notices`.

Checking for the flag and displaying the notice? Yeah, that would likely save an additional hook 👍 

> When dismissing, the user should preferably not be redirected, just the notice should go away. However in case this takes considerably more time to implement, then redirecting to the same page (where the notice would no longer appear then) could be an okay compromise.

I agree. I don't like notifications that trigger a full page reload, however, this is the lower effort solution. If time allows, we could go with a smoother implementation for this part specifically.

**Comment by aaemnnosttv** [comment]
@felixarntz ready for review again.

**Comment by felixarntz** [comment]
@aaemnnosttv Code looks good, but a few e2e tests need to be updated.

**Comment by aaemnnosttv** [comment]
@felixarntz I reduced the number of failing tests by changing the test client credentials to use the proxy format as this branch would cause those to be deleted immediately.

The rest are failing due to other changes in the `feature/auth-proxy` branch I think. Are there any others you want to specifically want to see fixed? We'll need to remove/fix those for the setup flow before we can merge #666 for sure.

**Comment by aaemnnosttv** [comment]
Nevermind, there should be more tests passing.

**Comment by aaemnnosttv** [comment]
Ready for review again 😄

**Comment by tofumatt** [comment]
QA looks good; checked out `develop`, connected the site, then switched to `feature/auth-proxy`, refreshed the page, and saw:

<img width="1148" alt="Screenshot 2019-10-21 19 47 38" src="https://user-images.githubusercontent.com/90871/67233715-acbfa780-f43b-11e9-9626-c494b950c3d0.png">

The button took me to the proxy setup URL. 👍
