### ISSUE TITLE
Ensure both Analytics modules always reference the same owner

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6465]
## Feature Description

From the user's experience, there is only one Analytics in Site Kit. Under the hood however, GA4 is a separate module (`analytics-4`), keeping `analytics` as the initial UA-specific variant.

To keep the two "under one roof" of Analytics, a number of special cases exist in components and elsewhere to handle the two as one, although this will be temporary with the sunset of UA later this year.

One quirk which has existed for a long time, is that the two modules can have different owners. That is, if one admin sets up both, another admin can come along and change the connection for one of them and become the new owner which shouldn't be possible if we consider them to be the same.

With Dashboard Sharing, and the upcoming GA4 reporting, we've seen GA4 start to pop up in places where it shouldn't, but specifically in regards to DS, we shouldn't allow the two to have separate owners as this will cause problems with various DS-related functionality.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Both Analytics modules should always reference the same owner
* Any time the module owner for either Analytics module changes, the other module should be updated to match

## Implementation Brief

* In `Analytics::register()` method, add `pre_update_option_googlesitekit_analytics-4_settings` action hook with a callback containing:
  * Check if the `analytics-4` module's `ownerID` setting has changed in the new value.
  * If it has, check the `ownerID` of the `analytics-4` module and the `ownerID` of the `analytics` module are the same.
  * If they are not the same, update the `ownerID` of the `analytics` module to match the `ownerID` of the `analytics-4` module using the `Analytics\Settings::get_settings()->merge()` method.

* In `Analytics_4::register()` method, add `pre_update_option_googlesitekit_analytics_settings` action hook with a callback containing:
  * Check if the `analytics` module's `ownerID` has changed in the new value.
  * If it has, check the `ownerID` for the `analytics` module and the `ownerID` for the `analytics-4` module are the same.
  * If they are not the same, update the `ownerID` of the `analytics-4` module to match the `ownerID` of the `analytics` module using the `Analytics_4\Settings::get_settings()->merge()` method.

* Here is an example of this approach:
https://github.com/google/site-kit-wp/blob/2dfd0e1971859a4fa216d79fc8e3afa7d1fd889a/includes/Core/Storage/Setting_With_Owned_Keys_Trait.php#L52-L68
**NOTE:** Ensure this doesn't cause an infinite loop, as discussed [here](https://github.com/google/site-kit-wp/issues/6465#issuecomment-1483120333).

### Test Coverage

* Add tests to `AnalyticsTest` and `Analytics_4Test` to cover the above changes.

## QA Brief

**See QAB Update below.**

- Set up Site Kit with the Analytics module.
- In a Site Kit screen, run the following code in the browser console:
  ```js
  googlesitekit.data.select( 'modules/analytics' ).getSettings();
  googlesitekit.data.select( 'modules/analytics-4' ).getSettings();
  ```
- Verify that the `ownerID` property in both the response objects returned is the same, and is your WordPress user ID.
- Now log into the site with another WordPress user and log into Site Kit with the same Google account.
- Go to the Analytics module settings and set the GA4 property select to `Set up a new property`. Click on `Confirm Changes` so that Site Kit creates a new GA4 property (allow permissions if requested in the process).
- Refresh the page (so that the resolvers are invalidated).
- Now, run the above code again and verify that the `ownerID` property in both the response objects returned has changed to your current WordPress user ID.

### QAB Update

Following its reversion the above QAB is no longer applicable. Instead, perform a regression test to ensure that Analytics settings can be saved as a 2nd admin.

## Changelog entry

*

**Comment by felixarntz** [comment]
@aaemnnosttv ACs LGTM! ✅

**Comment by techanvil** [comment]
It's worth tagging https://github.com/google/site-kit-wp/issues/6446 here as it covers some related ground...

**Comment by eugene-manuilov** [comment]
@hussain-t, why not to check if the owner is changed in the REST endpoint that saves sharing options? We can compare owner IDs there and update settings accordingly without using hooks, right?

https://github.com/google/site-kit-wp/blob/d2ac769d1a5b7d2b4b30986e58b45d282d961864/includes/Core/Modules/REST_Dashboard_Sharing_Controller.php#L95-L97

**Comment by hussain-t** [comment]
Thanks for the suggestion, @eugene-manuilov. I thought hooks were the best place to do it. However, I would like to hear from @aaemnnosttv on this.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov while dashboard sharing is one of the important cases here, it isn't the only one. Module access checks also involve ownership conditions, which are relevant for Analytics where changing the connected entity will result an an automatic change of ownership (e.g. creating a new GA4 property can result in the user becoming the owner of GA4 but not for UA).

Since the automatic ownership mechanic is implemented using these hooks, I think it makes sense to use the same strategy to amend it for Analytics. @hussain-t and I spoke about using this approach beforehand, but I'm of course open to using an alternative solution. Let me know what you think 👍

**Comment by eugene-manuilov** [comment]
Ah.. okay, thanks for letting me know guys. Makes sense now.

> * In `Analytics::register()` method, add `pre_update_option_googlesitekit_analytics_settings` action ...
>   * ... check the `ownerID` setting for the `analytics-4` module and the `ownerID` setting for the (current) `analytics` module are the same.

@hussain-t, it should be the other way around. In the Analytics_4 class we need to register a hook to for the Analytics module and if their `ownerID` has changed, then the Analytics_4 has to change its own `ownerID` as well. Same for the Analytics module, it should add a hook for updating Analytics-4 settings and check its `ownerID`. In this case, you will have all information that you need to properly check owners without a need to get an instance of the opposite module.

> * If they are not the same, update the `ownerID` setting for the `analytics-4` module to match the `ownerID` option for the `analytics` module using the `Analytics_4\Settings::get_settings()->merge()` method.

We need to make sure that we don't get into the infinite loop because we update one module settings that triggers a hook in the second module, that updates its settings that triggers the hook in the first module and so on... I am not sure that it will be the case, but just something that we need to pay attention to... Maybe the actual update for the second module settings should happen in a new hook created in-place for the `updated_option` action that gets triggered after the first option has been written to the database.

**Comment by eugene-manuilov** [comment]
Thanks, @hussain-t. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit I have a query on the QAB, because I am not seeing the behaviour highlighted. 

This task here:

```
- Now log into the site with another WordPress user and log into Site Kit with the same Google account.
- Go to the Analytics module settings and set the GA4 property select to Set up a new property.
- Refresh the page (so that the resolvers are invalidated).
```

I don't need to set up a new GA property?  Just select `Set up a new property` and then refresh? 

When I run the code after completing this task, the UserID is still the original admin user, and not the user I am logged in, i.e. User 1 rather than User 2.   Could you clarify this for me?

**Comment by nfmohit** [comment]
Hi @wpdarren!

My bad, yes, you'd need to set up the new GA4 property. I've updated the QAB for clarification. Let me know if you need any additional information.

Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

When following the QAB:
- The ownerID property in both the response objects returned is the same, and is my WordPress user ID.
For another admin user when following the QAB
- The ownerID property in both the response objects returned has changed to your current WordPress user ID.

![image](https://user-images.githubusercontent.com/73545194/229708153-ba7e91b4-25f2-42c1-b144-243d0e691a58.png)
![image](https://user-images.githubusercontent.com/73545194/229708174-dc641e95-e106-4180-a334-357b4e1246e4.png)

**Comment by aaemnnosttv** [comment]
## ❌ Approval

With #6846 being raised, it seems a different approach was needed here. Rather than rushing #6846 into the release, let's revert the changes here and pick this up fresh in that issue.

**Comment by nfmohit** [comment]
> ## ❌ Approval
> With #6846 being raised, it seems a different approach was needed here. Rather than rushing #6846 into the release, let's revert the changes here and pick this up fresh in that issue.

I've opened #6849 to revert its PR. Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:

I have spent some time running through the different scenarios of second admin users and making sure that the second and main admins can change settings; create new accounts, properties and profile views for GA4 and UA.  I couldn't see any errors during my testing.

**Comment by aaemnnosttv** [comment]
Closing in favor of https://github.com/google/site-kit-wp/issues/6846
