### ISSUE TITLE
Add notification about the Optimize sunset 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6467]
## Feature Description

For users that are currently using Optimize, we should inform them within Site Kit about the future removal of the module.

This issue is specifically about adding a notification on the dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new banner notification should be added to the main authenticated Site Kit dashboard:

**Title**
> _Google Optimize will no longer work after 30 September 2023_

**Body**
> _Google Optimize and Optimize 360 will no longer be available after September 30, 2023 and will be removed in future versions of Site Kit after this date._

**Learn More URL**
```
https://support.google.com/optimize/answer/12979939
```

* Dismissing the notification should dismiss the notification permanently using the default "OK, Got it!" primary button
* The notification should only be shown to users who currently have the Optimize module connected
* In terms of priority, the banner should be displayed just above zero data state notifications, but after anything else above that  

#### Create a notification component

* Create a new component, `OptimizeRemovalNotification` in `assets/js/components/notifications` with the following:
  * Check whether the Optimize module is connected using the new `isModuleConnected` selector.
  * Check whether the notification has already been dismissed using the `isItemDismissed` selector of the `core/user` store.
  * Return `null` if the module is not connected OR the notification has already been dismissed.
  * Otherwise, render the `BannerNotification` component with the following props:
    * `id`: `optimize-removal-notification`.
    * `title` and `description`: Translatable strings according to the AC.
    * `ctaLabel`: Translatable string "OK, Got it!".
    * `onCTAClick`: It should dispatch the `dismissItem` action of the `core/user` store and pass the notification ID to it within a callback function.
    * `learnMoreLabel`: Translatable string "Learn more".
    * `learnMoreURL`: Translatable string `https://support.google.com/optimize/answer/12979939`.
* Render the `OptimizeRemovalNotification` component within `BannerNotifications` just above the `ZeroDataStateNotifications` banner. 
* Add storybook stories for the `OptimizeRemovalNotification` notification banner.

### Test Coverage

* Add unit tests for the `OptimizeRemovalNotification` component.

## QA Brief

* Activate the Optimize module
* Go to the dashboard page and ensure that you see the notification as described in AC

## Changelog entry

* Add notice about Google Optimize product sunset.

**Comment by marrrmarrr** [comment]
@aaemnnosttv could you clarify what exactly SK will remove -- just the module in the plugin or also the Optimize snippet that had been placed on the site?

**Comment by marrrmarrr** [comment]
Updated the copy, this is good to go.

**Comment by tofumatt** [comment]
IB ✅

**Comment by bethanylang** [comment]
Planning to schedule for Sprint 99, ending April 21.

**Comment by aaemnnosttv** [comment]
@marrrmarrr shouldn't the title use "September 30, 2023" rather than "30 September 2023" ?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When the Optimize module is activated then a notification appears on the dashboard page as per the AC:
  - Title: Google Optimize will no longer work after 30 September 2023
  - Body: Google Optimize and Optimize 360 will no longer be available after September 30, 2023 and will be removed in future versions of Site Kit after this date.
  - Learn more URL: https://support.google.com/optimize/answer/12979939 

- The notification is permanently dismissed when the default "OK, Got it!" primary button is clicked.
- The notification is only shown to users who currently have the Optimize module connected
- The priority for the banner is displayed just above zero data state notifications, but after anything else above that. i.e. the GA4 activation banner appears before this notification.  

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/b1300c9a-1135-4e57-8971-b339bc73e7ae)
![image](https://github.com/google/site-kit-wp/assets/73545194/6a0aa2a2-15c1-4f8a-9725-dde94ea84999)
![image](https://github.com/google/site-kit-wp/assets/73545194/cf95d23c-b00a-4d51-97a2-80f4e11fb3cc)

</details>

**Comment by bethanylang** [comment]
@wpdarren @aaemnnosttv @marrrmarrr We're using two different date formats inside of one message – should we not be using American date format for both, i.e. September 30, 2023?

**Comment by marrrmarrr** [comment]
@wpdarren @bethanylang agreed we should stick to one format across the whole product, I checked what we've used in other notifications containing dates and it looks to be the month-first format, e.g. here's one for [GA4](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&node-id=223-2502&t=oM41HyeAiBdfV3vt-4).

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@eugene-manuilov I have sent this ticket back to execution due to the date format.  Please see comment above.
