### ISSUE TITLE
Remove Optimize module

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6469]
## Feature Description

Once the Optimize service is sunset, and users have had sufficient notice, the module may safely be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**This must only be included in a release after the Optimize sunset date (September 30, 2023) but should be double-checked with @marrrmarrr to confirm beforehand. It also must be coordinated with #6470 to ensure the two land in the same release.**

* The Optimize module should be entirely removed, including its components, data store, classes, related styles, tests, stories, and assets
* Optimize should also be removed from the list of "SUPPORTED GOOGLE TOOLS" on the readme

## Implementation Brief

* In Readme.md, remove optimize from tags and from `Supported Google tools`.
* Remove optimize from entry points in [`webpack.config.js`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/webpack.config.js#L308-L309).
* Delete the `assets/js/googlesitekit-modules-optimize.js` file.
* Delete the `assets/js/modules/optimize/` directory.
* Remove Optimize from fixtures in [`assets/js/googlesitekit/modules/datastore/__fixtures__/list.json`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/googlesitekit/modules/datastore/__fixtures__/list.json#L91-L112)
* Remove Optimize service-urls from tests in [`assets/js/modules/service-urls.test.js`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/modules/service-urls.test.js#L74-L78).
* Remove from JS unit tests:
  * Remove from `provideModules` array [`assets/js/components/settings/SettingsApp.test.js`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/components/settings/SettingsApp.test.js).
  * Remove permissions Tests [`assets/js/googlesitekit/datastore/user/permissions.test.js`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/googlesitekit/datastore/user/permissions.test.js).
  * Change surveys tests to user other `triggerId` than `optimizeSurves` [`assets/js/googlesitekit/datastore/user/surveys.test.js`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/googlesitekit/datastore/user/surveys.test.js).
  * Replace Optimize with Tag Manager module in [`assets/js/googlesitekit/modules/datastore/modules.test.js`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/googlesitekit/modules/datastore/modules.test.js)
  * Replace all occurences of `optimize` with `tagmanager` in `assets/js/googlesitekit/modules/datastore/sharing-settings.test.js`[
](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/googlesitekit/modules/datastore/sharing-settings.test.js)
* Remove Optimize related styles in `_googlesitekit-setup-module.scss`. https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/sass/components/setup/_googlesitekit-setup-module.scss#L117-L134
* Remove optimize from `$core_modules` in [`includes/Core/Modules/Modules.php`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/includes/Core/Modules/Modules.php). 
* Delete `includes/Modules/Optimize.php`.
* Delete `includes/Modules/Optimize` directory.
* Delete Optimize storys
  * `stories/module-optimize-settings.stories.js`
  * `stories/module-optimize-setup.stories.js`
* Delete E2E tests `tests/e2e/specs/modules/optimize`
* Remove from test utils `tests/js/utils.js`.
* PHP Unit
  * Remove from [`OptionsTestTrait::get_option_keys()`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/tests/phpunit/includes/OptionsTestTrait.php#L24-L39)
  * In `ModulesTest.php`
    * In `test_get_module_dependencies()` replace `optimize` with `analytics-4`.
    * Remove all other occurences of Optimize in `ModulesTest.php`
  * In `/Core/Modules/REST_Modules_ControllerTest.php`
    * Replace optimize with `analytics-4` in `test_activation_rest_endpoint__deactivate_dependant_module()`.
    * Replace optimize with other non-sharable module `tagmanager` in `test_check_access_rest_endpoint__unshareable_module_does_not_have_service_entity()`
    * Replace optimize with tagmanager in `test_activation_rest_endpoint__prevent_inactive_dependencies_activation()`
    * Delete OptimizeModule tests [`tests/phpunit/integration/Modules/OptimizeTest.php`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/tests/phpunit/integration/Modules/OptimizeTest.php)
    * Delete OptimizeSettings tests [`tests/phpunit/integration/Modules/Optimize/SettingsTest.php`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/tests/phpunit/integration/Modules/Optimize/SettingsTest.php#L3)
    * Delete `Tag_GuardTest` [`tests/phpunit/integration/Modules/Optimize/Tag_GuardTest.php`](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/tests/phpunit/integration/Modules/Optimize/Tag_GuardTest.php#L15)

### Test Coverage

* Update VRT reference images
* Delete Optimize VRT reference images

## QA Brief

* Ensure that there is no console error and that everything works fine in site kit dashboard
* Ensure that in Settings -> Connect More Services, `Optimize` module is not on the list anymore
* Perform smoke testing and ensure no regression due to the changes.

## Changelog entry

* Remove Optimize from available Site Kit modules.

**Comment by felixarntz** [comment]
@aaemnnosttv Expanded the note on top of the ACs to also clarify here that this needs to go together with #6470.

**Comment by aaemnnosttv** [comment]
Thanks @felixarntz , I did mention in the AC of #6470 that the two need to go out together but it makes sense to mention that from both sides 👍

**Comment by aaemnnosttv** [comment]
Thanks for the through IB @derweili !

IB ✅ 

I'm going to assign this to @bethanylang to hold on to until we're ready for it to be worked on closer to the sunset date to avoid having a PR sit around for a long time that gets stale and may have merge conflicts – as well as the coordination that's needed with #6470 😄

**Comment by bethanylang** [comment]
Planning to schedule for Sprint 111, ending October 6.

**Comment by bethanylang** [comment]
@aaemnnosttv Reassigning this over to you as we made some decisions in #6470 in June that may affect the AC/IB here. Can you take a look?

**Comment by aaemnnosttv** [comment]
Thanks @bethanylang – the definition here still seems correct. #6470 was going to reintroduce some limited temporary infrastructure for the notice but we won't be doing that in the plugin anymore so this issue is correct that it should be completely removed. Because of this, it is still important that we hold _merging_ this until the sprint that it it is to be released. We could however, start working on it in the previous sprint although that shouldn't be necessary since it should be rather straightforward to implement.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified on main branch after creating new a/c.
- Verified under Settings -> Connect More Services, Optimize module is not on the list anymore.
- Done smoke testing and no console errors found.
- Verified on site on which Optimize module is already connected.
- Verified on switching to main branch. Main dashboard not showing Optimize notice that optimize will not work after sept 30. 
- Verified under Settings -> Connected modules, Optimize module is not on the list anymore.
**Note** : Newly added post sept 30 notice for Optimize is not showing on main dashboard because that notice will appear when plugin version is 1.111.0.

<details>

When optimize module is already connected

https://github.com/google/site-kit-wp/assets/94359491/3a18ac04-1c15-4782-87c5-a030f7c44103

New set up on main branch

https://github.com/google/site-kit-wp/assets/94359491/c3c7e878-7bd2-4dad-9042-e659bb8611f4

</details>
