### ISSUE TITLE
Add client-side cache store with `*setCacheItem()` action.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6472]
## Feature Description

In order to avoid having to write a new control every time we want to set a cache item via the datastore (see [`datastore/user/feature-tours.js`](https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/user/feature-tours.js#L291-L297) and [`datastore/user/user-input-settings.js`](https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/user/user-input-settings.js#L217-L230)), we are going to build out a simple cache utility store that provides an action & control to set a cache item.

We can follow up to refactor `feature-tours.js` and `user-input-settings.js` to use the new action, and potentially add more functionality to this store. So as to avoid having to create a new asset for this store, we'll combine it with the `CORE_SITE` datastore although could consider extracting to its own datastore asset.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- There should be a new `cache` store combined into the `CORE_SITE` datastore. The `cache` store should initially contain one action, `*setCacheItem()`.
- `*setCacheItem()` should (via a control) call `setItem()`, passing its parameters directly through.

## Implementation Brief

Create the file `assets/js/googlesitekit/datastore/site/cache.js`. Within this file, build out a store which provides the following action:

- `*setCacheItem( key, value, args )` - this should yield to a control that calls `setItem( key, value, args )`. See the example in [`feature-tours.js`](https://github.com/google/site-kit-wp/blob/75c82e34f0f19d9a59448aa69099312063424544/assets/js/googlesitekit/datastore/user/feature-tours.js#L291-L297), although `*setCacheItem()` should pass its parameters directly through rather than trying to set its own parameters.

Then, combine the new cache store in `assets/js/googlesitekit/datastore/site/index.js`.

### Test Coverage

- Add tests for `*setCacheItem()`.

## QA Brief

* This ticket involves no modifications that will be visible to end-users.
* The `*setCacheItem()` action implemented in this ticket has not yet been used within the existing codebase; therefore, no testing is necessary.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
Tests for this ticket pass and fulfil ACs, so moving directly to Approval as no QA is needed.

**Comment by aaemnnosttv** [comment]
@techanvil is the plan here to add a selector for retrieving items from the cache at some point as well?

As an aside, I wonder if `core/user` might be more appropriate for this since all cache is currently user-specific – using `core/site` might set the wrong expectation.

**Comment by techanvil** [comment]
Hi @aaemnnosttv, that's an interesting question. On the one hand, it would provide a certain symmetry. However, I wonder if providing a selector to retrieve a cache item could also in its own way be setting the wrong expectation. Because, the expectation is that a selector will be "re-fired" when the corresponding value is updated due to a store update. But, in this particular case, we're not actually using the stateful aspect of Redux, as `*setCacheItem()` is piggybacking directly to `setItem()` with no Redux state and reducer. So, a call to `setCacheItem()` wouldn't result in the selector counterpart from being re-triggered.

This does actually make me wonder if `*setCacheItem()` is maybe a bit too non-idiomatic, although I have seen some discussion about using Redux actions without a corresponding reducer.

It's worth noting that the only place we currently call `getItem()` that would translate to a selector call is in [`*getLastDismissedAt()`](https://github.com/google/site-kit-wp/blob/109791ee1a4e426f73ddfb5ad255d8dcbac7aad3/assets/js/googlesitekit/datastore/user/feature-tours.js#L367-L369), where it's quite straightforwardly wrapping the `setItem()` call in a `yield Data.commonActions.await()`. So it's not that we'd save as much boilerplate here, compared to needing to add a control each time we want to call `setItem()` from an action.

IInterested to know your thoughts here... Noting that we do also have a case where we're using a control as a way of calling `getItem()` from an action (plus another `setItem()` control), in the [snapshot stores](https://github.com/google/site-kit-wp/blob/109791ee1a4e426f73ddfb5ad255d8dcbac7aad3/assets/js/googlesitekit/data/create-snapshot-store.js#L127-L139), I wonder if maybe a mixin pattern for these controls would be more appropriate than the approach as has been defined and implemented here.

As to moving this to `core/user`, that's a good point, I do think that would be appropriate if we do stick with the current approach.
