### ISSUE TITLE
Refactor the Feature Tours `*setLastDismissedAt()` action to use `*setCacheItem()`.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6473]
## Feature Description

Following on from #6472, we should refactor the Feature Tours `*setLastDismissedAt()` action to use the new `*setCacheItem()` action.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Feature Tours `*setLastDismissedAt()` action should be updated to reuse the new `*setCacheItem()` action.
* The `CACHE_LAST_DISMISSED_AT` control that calls `setItem()` should be removed as it will no longer be needed.

## Implementation Brief

* In `assets/js/googlesitekit/datastore/user/feature-tours.js`:
  * Update the `setLastDismissedAt()` action with the following:
    * Instead of calling the `CACHE_LAST_DISMISSED_AT` control, use the `*setCacheItem()` action which is being implemented in #6472.
    * Pass the same arguments to `setCacheItem()` as are passed to `setItem()` in the `CACHE_LAST_DISMISSED_AT` control.
  * Remove the `CACHE_LAST_DISMISSED_AT` control.

### Test Coverage

* Update the `setLastDismissedAt()` action tests to use the `*setCacheItem()` action instead of the `setItem` (`setItemSpy`).

## QA Brief

* Go to tester settings
* Under the `Force initial Site Kit plugin version` option input `1.29.0`
* Go to dashboard, you will see feature tour for help menu
* Click on dismiss
* Verify that on reload of the page tour is not poping up again
* Open chrome dev tools, and in the console tab, add: `console.log(window.googlesitekit.data.select('core/user').getLastDismissedAt())` it should show number, for example `1693995426179`
* Then enter: `console.log(window.googlesitekit.data.select('core/user').areFeatureToursOnCooldown())` it should display `true`

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
> * Update the `setLastDismissedAt()` action with the following:
>   
>   * Instead of calling the `CACHE_LAST_DISMISSED_AT` control, use the `*setCacheItem()` action which is being implemented in [Add client-side cache store with `*setCacheItem()` action. #6472](https://github.com/google/site-kit-wp/issues/6472).
>   * Pass the same arguments to `setCacheItem()` as are passed to `setItem()` in the `CACHE_LAST_DISMISSED_AT` control.
> * Remove the `CACHE_LAST_DISMISSED_AT` control.

@hussain-t, no need to change anything in that action, we can replace it completely with the `setCacheItem` call since it is used only in the `dismissTour` action. So, what we need to do is to delete the `setLastDismissedAt` completely and update the `dismissTour` action to use `setCacheItem` instead.

Also, for the estimates, I think that `11` is way too much for this simple task. Let's reduce it to `7` at least.

**Comment by hussain-t** [comment]
@eugene-manuilov that makes sense, but the AC says to update the `setLastDismissedAt()` action:
>The Feature Tours *setLastDismissedAt() action should be updated to reuse the new *setCacheItem() action.

>Also, for the estimates, I think that 11 is way too much for this simple task. Let's reduce it to 7 at least.

I set it to `11` keeping in mind test changes and the `Exp: SP` label.

**Comment by eugene-manuilov** [comment]
Oups, apologies, @hussain-t, you are right, I checked the codebase and looks like what we need to do is what you mentioned in IB. Sorry, about confusing you 🤦. IB ✔️ + I'll update it to be `11` again since it makes sense to me know.

**Comment by hussain-t** [comment]
No problem. Thanks, @eugene-manuilov 👍

**Comment by tofumatt** [comment]
(Waiting to move to QA because we need a new release to tag this one with.)

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@wpdarren @zutigrm I tried to trigger 'help' feature tour on 2 different sites. But it's not triggered for me. Cleared cache and waited for 2 hours but feature tour not appearing. 
Note : Tested this on both latest and develop environment.
Let me know if you 'help' feature tour appearing for you.

- Tested on plugin version 1.29.0.
- Verified by clearing session and local cache.
- UnifiedDashboard and DashboardSharing Feature tour are appearing but feature tour for help menu is not appearing.
- 

![image](https://github.com/google/site-kit-wp/assets/94359491/def57920-8ea5-4d3d-a935-5855eb207af9)

![image](https://github.com/google/site-kit-wp/assets/94359491/138bbe7e-28ff-4ef3-9eb4-ba1778c34cfa)

**Comment by zutigrm** [comment]
Hi @mohitwp, thank you for checking. Yes, it appears for me on development, locally and on instawp.

https://github.com/google/site-kit-wp/assets/10414808/bbedf9f2-8758-4193-81bb-3161d967396a

Can you try to spin a new instance on instaWP, and then check the 1.29.0 version override?

**Comment by mohitwp** [comment]
### QA Update ❌ 

@zutigrm 

As discussed on huddle. I followed QAB and use the snippet but getting undefined for both the snippets.


https://github.com/google/site-kit-wp/assets/94359491/f404cb8a-3f9c-48b7-b033-0d417e59760c

**Comment by zutigrm** [comment]
@mohitwp  hm, I can't seem to replicate this. I tried locally and on instaWP, here is the video from instaWP:

https://github.com/google/site-kit-wp/assets/10414808/47ee9c2a-8729-432a-977b-2966b232942e

**Comment by techanvil** [comment]
Hey @mohitwp, I think I've realised what's up here. Looking at your screencast, you've got the "errors" filter in the console selected, which means it's only going to display `console.error()` messages and not `console.log()` messages which are at the Info level. Please can you retry with the top "messages" option selected which removes the filter (note the "user messages" and "info" options should also work). Alternatively, you could simply run the QAB snippets without wrapping them in the `console.log()` and their value should be logged directly out.

![image](https://github.com/google/site-kit-wp/assets/18395600/b77eba53-3916-400a-ab5d-1bd48cd4aabf)

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @techanvil @zutigrm ! Apologies ! I completely forgot that filter is active under console.

- Tested on dev environment.
- Verified on version 1.29.
- Followed the QAB and getting the expected output for the snippets.


https://github.com/google/site-kit-wp/assets/94359491/6bd0006c-0db4-4609-956e-a73aebd365c1
