### ISSUE TITLE
Refactor the User Input `*setUserInputSetting()`  action to use `*setCacheItem()`.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6474]
## Feature Description

Following on from #6472, we should refactor the User Input `*setUserInputSetting()` action to use the new *setCacheItem() action.

We can also take this opportunity to correct a mistake whereby the related `SET_CACHED_USER_INPUT_SETTING` control is mutating an object stored in the Redux state (see code snippet below).

https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/googlesitekit/datastore/user/user-input-settings.js#L215-L224

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The User Input `*setUserInputSetting()` action should be updated to reuse the new `*setCacheItem()` action.
* The `SET_CACHED_USER_INPUT_SETTING` control that calls `setItem()` should be removed as it will no longer be needed.
* It must be ensured that the code within the `SET_CACHED_USER_INPUT_SETTING` that mutates the `settings` object returned by `getUserInputSettings()` is not extracted and retained as-is, and is corrected to avoid mutating the object.

## Implementation Brief
* Using `assets/js/googlesitekit/datastore/user/user-input-settings.js`,
    * Update the `setUserInputSetting` action to use the newly added `setCacheItem` action from #6472 using `CACHE_KEY_NAME` as key/
    * Within the `SET_CACHED_USER_INPUT_SETTING` control,
        * Remove the `setItem` call.
        * Update the code so that the `settings` object is not mutated.

### Test Coverage
* No new tests to be added.

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB ✔️, but I think `11` is too much for this simple task. I'll downgrade it to `7` which is more than enough to update one action and controller.

**Comment by techanvil** [comment]
Closing as this is a stale issue, with `setItem()` no longer being used in the user input settings store.

**Comment by techanvil** [comment]
Closing as this is a stale issue, with `setItem()` no longer being used in the user input settings store.
