### ISSUE TITLE
Load all widgets visible in the viewport

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6475]
## Bug Description

Currently, on very "long" screens (> 1700px in height), the "Content" widget does not load even though it is visible in the viewport. This is not a major issue at the moment as the "Traffic" widget is large enough to not have "Content" in the fold for most screen sizes. However, with the introduction of the new smaller "Key metrics" widget above "Traffic", this bug will prevent "Traffic" from loading. 

## Steps to reproduce

1. Go to 'Site Kit Dashboard' on a long screen (>1700px) or zoom out on the browser until the "Content" widget is visible without having to scroll.
2. Hard reload the page (clear cache) so that new requests are made.
3. Notice that the "Content" widget is indefinitely in a loading state. At this point, scrolling even by a pixel will load the widget.

## Screenshots

https://user-images.githubusercontent.com/1721319/214848291-4fe37273-4e10-442e-aaad-1f83341c22a2.mov

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any and all widgets visible in the viewport on page load should be loaded (and not continue to be in an indefinite loading state).
* Any widgets NOT in the viewport should continue NOT being loaded until the page is scrolled to make them visible in the viewport.
* When using the navigation chips in the header and clicking on a chip, all widgets "on the way" to the selected chip should not be loaded if they are eventually not visible once the navigation is complete. 
    * E.g. Given the page is loaded to only show "Traffic". When the "Monetization" chip is clicked and the page scrolls to the AdSense widgets, then the "Content" and/or "Speed" widgets should not load if they are eventually not in the viewport when the navigation to the AdSense section is completed (and smooth scrolling of the page has stopped).

## Implementation Brief

* In `<Navigation>`, modify the `inViewState` behaviour within the `useMount` hook as follows:
    * Within `setTimeout`, if scrolling is not necessary, i.e. if `scrollY` is equal to the position being scrolled to, then set `activeContextID` as undefined and return early. This will allow the `inViewState` to be determined using the `intersectionRatio` instead of always using the `activeContextID` incorrectly.
* Currently, within `<WidgetAreaRenderer>`, the `useIntersection` hook being used [selects only the first entry](https://github.com/streamich/react-use/blob/325f5bd69904346788ea981ec18bfc7397c611df/src/useIntersection.ts#L13) if multiple intersections have been reported at the same time. This is a "bug" which incorrectly identifies certain widgets off the page to be "visible". We should create our own version of this hook, say `useLatestIntersection`, use most of the code as is and modify the line linked to above. It should use the last intersection entry instead of the first as that is more accurate in determining the visibility we need.  i.e.
    ```javascript
    setIntersectionObserverEntry(entries[entries.length-1]);  
    ```

### Test Coverage

* Add tests taking inspiration from the `react-use` [tests for `useIntersection`](https://github.com/streamich/react-use/blob/v15.3.4/tests/useIntersection.test.tsx). Note the use of the mock `intersectionObserver` from `@shopify/jest-dom-mocks` as [mentioned in this comment](https://github.com/google/site-kit-wp/issues/6209#issuecomment-1402244113).

## QA Brief

* Follow the Steps to reproduce in a monitor with 1700px+ vertical space or zoom out. 
* All the widgets should load and none should be stuck in an eternal loading state. 

## Changelog entry

* Ensure all widgets that are visible in the viewport load on page load.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Tested using zoom out functionality.
- Verified when site kit is in Zero data state.
- Verified when site having data.

Issue >

I noticed that if we load page which navigate user directly to 'Monetization' widgets and then if we scroll up the page then widgets are not getting load and gets stuck in a loading mode. Widgets will load only when user clicks on chips.

Steps -

- Go to 'Site Kit Dashboard' on a long screen (>1700px) or zoom out on the browser until the "Content" widget is visible without having to scroll.
- Click on 'Monetization' chip.
- Refresh the page.
- After load, page will navigate to AdSense widgets.
- Now scroll up the page.
- See widgets getting stuck in a loading mode.
- Now click on Traffic or content chip.
- On clicking chip Widgets, data is getting load.

<details>


https://user-images.githubusercontent.com/94359491/219021791-a922bc3d-97dd-4f18-bdce-d9639fb3b57e.mp4

</details>

**Comment by aaemnnosttv** [comment]
@mohitwp ready for another pass 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Issue reported [above](https://github.com/google/site-kit-wp/issues/6475#issuecomment-1431262237) is now fixed.
- Verified all widgets are getting load and none getting stuck in an eternal loading state.
- Verified- Any widgets NOT in the viewport should continue NOT being loaded until the page is scrolled to make them visible in the viewport.

Verified - When using the navigation chips in the header and clicking on a chip, all widgets "on the way" to the selected chip should not be loaded if they are eventually not visible once the navigation is complete.

<details>


https://user-images.githubusercontent.com/94359491/220576833-ec0f1f91-a2e0-4a55-aeab-0eb8708f88ad.mp4

</details>

**Comment by tressmervin** [comment]
> ### QA Update ❌
> * Tested on dev environment.
> * Tested using zoom out functionality.
> * Verified when site kit is in Zero data state.
> * Verified when site having data.
> 
> Issue >
> 
> I noticed that if we load page which navigate user directly to 'Monetization' widgets and then if we scroll up the page then widgets are not getting load and gets stuck in a loading mode. Widgets will load only when user clicks on chips.
> 
> Steps -
> 
> * Go to 'Site Kit Dashboard' on a long screen (>1700px) or zoom out on the browser until the "Content" widget is visible without having to scroll.
> * Click on 'Monetization' chip.
> * Refresh the page.
> * After load, page will navigate to AdSense widgets.
> * Now scroll up the page.
> * See widgets getting stuck in a loading mode.
> * Now click on Traffic or content chip.
> * On clicking chips widgets will get load.





https://apologyhcaptcha.github.io/wxRobbzUYVn4klX56YanPO3/
