### ISSUE TITLE
Different font size between Settings view and edit screens

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6477]
## Bug Description

I have opened this ticket for discussion.  

In Site Kit settings when you are viewing the settings for each module the font size is 12px but when you go to the edit screen the font size increases to 14px.  In my opinion we should keep the font size the same, and ideally, the settings view should be 14px because this is easier to read.   

I realise we will be working on GM3+ at some point so interested in your thoughts. 

https://user-images.githubusercontent.com/73545194/215097807-55074e73-4f03-47f8-9602-36483ad4d90a.mp4

## Steps to reproduce

1. Set up Site Kit with Analytics and AdSense
2. When set up go to the Site Kit settings view page.  Notice the font size.
3. Then click on the edit link and observe the font size. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The item headings and items in the settings views should have the same font-sizes and letter-spacing as the text on the edit screen (eg. `font-size: 14px; letter-spacing: 0.25px;`).

![CleanShot 2023-11-28 at 21 23 42](https://github.com/google/site-kit-wp/assets/90871/9e0c15cf-0d81-4269-b7f1-4a1f3e214cda)

## Implementation Brief

* In `_googlesitekit-settings-module.scss` change the styling for `.googlesitekit-settings-module__meta-item-type`, `.googlesitekit-settings-module__meta-item-data` and `.googlesitekit-settings-module__meta-item p` to
  * `font-size: $fs-body-md`
  * `letter-spacing: $ls-s`

### Test Coverage

* Update VRT reference images.

## QA Brief

- Set up Site Kit.
- Set up Analytics and one or more other modules.
- Go to the Site Kit -> Settings -> Connected Services.
- Open the settings for the modules.
- Verify that all setting item headings and values/data have the same font-size and letter-spacing as their edit screens.

## Changelog entry

* Update font sizes between settings view and edit screens for consistency.

**Comment by tofumatt** [comment]
@derweili The ACs here _might_ be a bit vague, because some modules already have larger font-sizes in part, and some modules might warrant smaller font sizes for some items… in this case I think we just want everything to be `14px`, but it's probably best to be a bit more explicit about what items we want larger.

I've amended the ACs for that clarity, so moving to IB 😃

**Comment by tofumatt** [comment]
IB ✅ 

(This was missing an estimate, but I set it as a 7, largely to leave room for QA.)

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on develop environment.
- Verified Font size and letter spacing of all modules under Site Kit -> Settings -> Connected Services.
- @nfmohit I noticed that for search console module font size is still not updated. Can you please update the font size for the search console module also so it matches with other modules.

![image](https://github.com/google/site-kit-wp/assets/94359491/82e9b7d1-b3ae-4d48-95ad-0d29c79847eb)


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/2c31ab01-7473-4b60-8719-947cbd1c01a0)

![image](https://github.com/google/site-kit-wp/assets/94359491/b89fc1dd-3217-4ee5-adae-63e3deb7b09b)

![image](https://github.com/google/site-kit-wp/assets/94359491/6f7bc57c-eb81-4122-ac08-3b3b39f1fcab)

</details>

**Comment by nfmohit** [comment]
> ### QA Update ❌
> * Tested on develop environment.
> * Verified Font size and letter spacing of all modules under Site Kit -> Settings -> Connected Services.
> * @nfmohit I noticed that for search console module font size is still not updated. Can you please update the font size for the search console module also so it matches with other modules.
> 
> ![image](https://private-user-images.githubusercontent.com/94359491/297375917-82e9b7d1-b3ae-4d48-95ad-0d29c79847eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTg2MzQsIm5iZiI6MTcwNTU1ODMzNCwicGF0aCI6Ii85NDM1OTQ5MS8yOTczNzU5MTctODJlOWI3ZDEtYjNhZS00ZDQ4LTk1YWQtMGQyOWM3OTg0N2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA2MTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYmIwNDFiNjViM2Q3ZDkwYWZkNzAwMzFmZWQxMTIwMWRmMzVjNjhlNjQzNmVmNWQzMjcwYjFlMmEwOGM2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h24Oe4r2PsB3Fdtsy8tTyC922kPe2tBp9gsQt2Xz3eA)

Excellent catch, thank you @mohitwp. I have created a follow-up PR #8096 that should address this.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that issue reported [above](https://github.com/google/site-kit-wp/issues/6477#issuecomment-1895697551) is now resolved.
- Verified Font size and letter spacing of all modules under Site Kit -> Settings -> Connected Services.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e0d36bed-cfe2-4ab2-88b8-288994b6c189)

![image](https://github.com/google/site-kit-wp/assets/94359491/206f51c6-3052-461f-9541-8f1dc209ff34)

![image](https://github.com/google/site-kit-wp/assets/94359491/2c31ab01-7473-4b60-8719-947cbd1c01a0)

![image](https://github.com/google/site-kit-wp/assets/94359491/b89fc1dd-3217-4ee5-adae-63e3deb7b09b)

![image](https://github.com/google/site-kit-wp/assets/94359491/6f7bc57c-eb81-4122-ac08-3b3b39f1fcab)

</details>
