### ISSUE TITLE
Add "Addressed By" to Issue Templates

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#648]
This issue is a request to add the inverse of the lines below from the pull request template, but for issues.

https://github.com/google/site-kit-wp/blob/f0c21c27c2301d83cb172f96e9e13e6b3746f24e/.github/PULL_REQUEST_TEMPLATE.md#L3-L4

The reason for this is because we manage everything with Issues in GitHub and currently the only way to see what the PR is for a given issue is to open the issue directly and scroll down to find the _reference_ to the issue from the PR (added automatically by the lines above).

This is very inefficient and requires you to load the full issue to get to the PR. 

This is also problematic when managing multiple issues, as issue/pr references are not shown from the project board views.

I'd like to propose that we add an "Addressed By" section to the issue templates, to compliment the "Addresses Issue" line in the PR template. This is a small amount of overhead but its benefits far outweigh the cost.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

Add a predefined location to the issue template for linking to the PR that addresses it.  

Ideally, this would be at the top of the issue, to ensure it is visible from the project board  view when highlighting a card, without needing to expand the issue body.

## Changelog entry

* N/A

**Comment by swissspidy** [comment]
I like the idea. We have a similar workflow for the AMP plugin now, and issues can get very noisy. It's hard to scroll down and find the correct references.

**Comment by felixarntz** [comment]
@aaemnnosttv Now that we have ZenHub, I'd prefer to close this. We rely on PRs being connected to an issue via the UI on PRs, and these show up connected to the issue in the project board.

Let me know if you feel strongly about adding this - my concern is it would introduce yet another place (in addition to mentioning issue in the PR description and connecting the PR in ZenHub) to note the connection.

**Comment by aaemnnosttv** [comment]
@felixarntz I agree it's not as necessary now with ZenHub, although I wish it was more prominent on the single issue view. It seems the connection is only really displayed on the PR and in the board view (when enabled – which I usually keep off because it's so noisy and messes up column counts). Agreed this isn't worth the overhead now though 👍
