### ISSUE TITLE
Remove caching related infrastructure from User Input Data store

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6482]
## Feature Description

Since the user input answers are no longer stored in the service and resides on the WordPress database, there is no value in caching them. Therefore, the caching actions selectors should be removed from the data store and their usage refactored. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Caching related actions and resolvers should be removed from `core/user` - user input settings, (`assets/js/googlesitekit/datastore/user/user-input-settings.js`)
* Anything that depends on these removed bits must be refactored to directly get the information from the server/not rely on cached information.

## Implementation Brief

- In `assets/js/googlesitekit/datastore/user/user-input-settings.js`:
    - Remove the `setUserInputSettingsFromCache()` action and its usage within the `getUserInputSettings()` resolver (including surrounding logic).
	- Remove the following action types and all their usages & dispatches (including surrounding logic):
	    - `DELETE_CACHED_USER_INPUT_SETTINGS`
		- `GET_CACHED_USER_INPUT_SETTINGS`
		- `SET_CACHED_USER_INPUT_SETTING`
	- Remove `baseControls` and its inclusion in `store`.
	- Remove any remaining unused code.

### Test Coverage

- No tests need to be added.
- Update any failing tests.

## QA Brief

* There is no specific change to be tested as part of this ticket. However, ensure the user input saving and fetching data works as expected.
* Ensure no item is saved in the session storage with the key `*userInputSettings*`.
* Ensure after every page load when you go to the `/admin-settings` page or run the `googlesitekit.data.select('core/user').getUserInputSettings()` selector from the browser console, it fetches the data from the `user-input-settings` endpoint for the first time and not from the cache.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main.
- Verified user input settings answer and edit settings flow. It is working as expected.
- Answers are getting save.
- Answers are editable from the admin settings.
- Verified, no item is getting saved in the session storage with the key *userInputSettings*.
- Verified after every page load when we go to the `/admin-settings `page or run the `googlesitekit.data.select('core/user').getUserInputSettings()` selector from the browser console, it fetches the data from the user-input-settings endpoint for the first time and not from the cache.


<details>

![image](https://user-images.githubusercontent.com/94359491/220625495-b2054079-3ee2-4557-880c-e59999b29624.png)

https://user-images.githubusercontent.com/94359491/220626146-cfdf0e0b-de9c-4044-ab35-91a26632d371.mp4

</details>
