### ISSUE TITLE
Enhance efficacy of client side cache clearing mechanism

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6487]
## Feature Description

In #6237, we enhanced our heavy-handed approach of clearing web storage (essentially calling [`Storage.clear`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/clear)) with a more selective approach that only deleted items that use our cache prefix. Due to a related issue where we enhanced the isolation between sessions with a more sophisticated cache prefix, this can result in our cache clearing mechanism leaving items behind if they are using an older prefix which could happen by entries added in an older version of Site Kit or WP session.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `API.clearCache` should be updated such that it deletes all cache items added by Site Kit, regardless of the plugin version it relates to, or other differences in the storage prefix
    * The same applies to `API.invalidateCache` which uses the same internal utility

## Implementation Brief

- In `assets/js/googlesitekit/api/cache.js`:
	- Update the `getKeys()` function:
		- Currently, while `getKeys()` is described as a function to return **all** storage keys created by Site Kit, it only returns keys that are created within the current version. We need to update the `getKeys()` function so that it returns **all** storage keys created by Site Kit, regardless of the version it was created in.
		- Also, it returns an array of keys with the prefix removed. This arises a problem when removing keys, as it gets harder to determine the version and hash a certain key was created with.
	    - Instead of checking if `itemKey` starts with `STORAGE_KEY_PREFIX`, we need to check if it starts with `googlesitekit_`.
		- Instead of removing the prefix and including the actual key, we should directly include `itemKey` in the array being returned.
	- Update the `deleteItem()` function:
	    - Currently, this function has the ability to delete storage keys only created in the current version of the plugin. We want to change that in a way so that if the `key` passed to it contains the prefix, we will not add `STORAGE_KEY_PREFIX` to it as the prefix.
		- To determine if the `key` contains the prefix, we can simply check if it starts with `googlesitekit_`.
		- Run `storage.removeItem()` passing `key` to it if it contains the prefix, otherwise add `STORAGE_KEY_PREFIX` as the prefix like it is today.
	- Since there are a lot of usages of the `googlesitekit_` string, a new constant for it could be added, say `STORAGE_KEY_ABSOLUTE_PREFIX`.
- In `assets/js/googlesitekit/api/index.js`:
    - Update the `invalidateCache()` function:
	    - This function checks if the storage keys include the group prefix, assuming that the keys do not include the global prefix. Since `getKeys()` is now updated to return the full key (including prefix), the current logic will not work.
		- We can use a regular expression like this `^googlesitekit_([^_]+_)?${ groupPrefix }` (as @eugene-manuilov kindly described [here](https://github.com/google/site-kit-wp/issues/6487#issuecomment-1408596539)) to determine whether the key matches the group prefix.

### Test Coverage

- In `assets/js/googlesitekit/api/cache.test.js`:
    - Update test cases for the `getKeys()` function addressing the fact that it now returns the full key including prefix.
    - Update test cases for the `deleteKey()` function.
- Update any other failing test.

## QA Brief

- Set up Site Kit using an old version, then switch to the version being tested.
- There should now be cached data for both versions in Session Storage:
![image](https://user-images.githubusercontent.com/18395600/222223038-d7fc9b2f-b41e-4955-9abc-5bb3c3191f88.png)
- Disconnect Site Kit.
- The cached Site Kit data for both versions should be removed, while non-Site Kit data is not deleted. 

## Changelog entry

* Update the cache clearing functionality to remove cache for old versions as well.

**Comment by tofumatt** [comment]
ACs here are good, should be safe and a good idea to clear these out, as `localStorage` and `sessionStorage` enforce limited storage sizes.

Moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
> * Create a new function, say `getKeyPrefix()`:
>   
>   * The purpose of this function is to determine the prefix of the key.
>   * This function will receive a storage key as parameter, say `key`.
>   * This function must ensure that the `key` starts with `googlesitekit_`.
>   * To determine the prefix, we can use `split()` to split the key by an underscore (`_`), `slice()` the resulting array upto the third index, and `join()` the resulting array, i.e. `key.split('_').slice( 0, 3 ).join( '_' )`;
> * Create a new function, say `getKey()`:
>   
>   * The purpose of this function is to remove the prefix and return the actual key.
>   * This function will receive a storage key as parameter, say `key`.
>   * This function must ensure that the `key` starts with `googlesitekit_`.
>   * We can get the prefix using the new `getKeyPrefix()` function passing `key` to it.
>   * To remove the prefix, we can use `substring()` in the `key`, passing the length of the prefix to it.
>   * It should then return the actual key.

@nfmohit I am not sure that we need these functions. I think we can just use a regular expression in the `invalidateCache` function to determine whether the key matches the group prefix or not. Something like this:
```js
const exp = new RegExp( `^googlesitekit_([^_]+_)?${ groupPrefix }`, '' );
const allKeys = await getKeys();

allKeys.forEach( ( key ) => {
	if ( exp.test( key ) ) {
		deleteItem( key );
	}
} );
```
What do you think?

**Comment by nfmohit** [comment]
I have updated the IB addressing your suggestion, thank you @eugene-manuilov!

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@techanvil I'd just like to clarify a point in the QAB:

> The cached Site Kit data for both versions should be removed, while non-Site Kit data is not deleted.

After disconnecting I do see one 1.95.0 entry 

`googlesitekit_1.95.0_108ea866502d081e2a9b4bb2d4ee4223_core::user::tracking`

I suspect that this is because the splash page has loaded, but wanted to check. Everything else was removed. 

![image](https://user-images.githubusercontent.com/73545194/222614888-b9f8226e-b0fc-44e9-83b8-fbf4448ad140.png)

**Comment by techanvil** [comment]
Hi @wpdarren, thanks for raising this. This is indeed to be expected.

I should have been a bit more explicit in the QAB - if you watch the Session Storage tab while disconnecting Site Kit, you should see all of the Site Kit cache entries disappear, which is what we're validating here. Then when returning to the splash page it does populate the cache again with the entry you've highlighted.

**Comment by wpdarren** [comment]
Thank you @techanvil!

I did think this was the case, but you know what's like - you assume something and it ends up another bug or hotfix! 😄 

### QA Update: ✅ 

**Verified:**

When setting up Set up Site Kit using an old version, then switch to the version being tested, there is now cached data for both versions in Session Storage.  When I disconnect Site Kit, the cached Site Kit data for both versions should be removed, while non-Site Kit data is not deleted.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/222709593-82f51460-796c-47dc-9132-10e814d1aced.png)
![image](https://user-images.githubusercontent.com/73545194/222709617-4a5afb75-5bdc-4761-831a-c4534097d23a.png)

</details>
