### ISSUE TITLE
Console error in Admin Settings when `userInput` is enabled and Analytics module is not connected

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6488]
## Bug Description

If the `userInput` is enabled but Analytics module has not been connected yet, visiting the Admin Settings shows an error in the browser console as seen in the following screenshot. 

## Screenshots

![Screenshot_20230128_010840](https://user-images.githubusercontent.com/6187401/215176045-fad41712-4ead-4e62-9bac-c219d961b826.png)

## Steps to reproduce

1. Enable `userInput` feature flag. 
2. Disconnect Analytics if it is connected.
3. Visit Admin Settings
4. Observe the error. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The console error for `Google Site Kit API Error` related to the `report` datapoint should not appear in the Admin Settings when `userInput` is enabled and Analytics is not connected.
* The Analytics `getReport()` call when `userInput` feature flag is enabled that is causing that console error should not be made when Analytics is not connected.

## Implementation Brief
* Using `assets/js/components/settings/SettingsAdmin.js`,
    * Update the condition to render `UserInputSettings` only if `isUserInputCompleted` is `false` and not `undefined`. Currently the component is being rendered when `isUserInputCompleted` is `undefined`.
* Using `assets/js/components/notifications/UserInputSettings.js`,
    * Update `analyticsIsGatheringData` to be `true` if `analyticsModuleConnected` is also `true`.

### Test Coverage
* No new tests to be added.

## QA Brief
* With the `userInput` flag enabled, visit the "Admin Settings" page with Analytics module disconnected.
* Ensure there are not console errors.
* Connect Analytics module and visit the "Admin Settings" page again. There should be a prompt asking you to fill in the user input form.
* Submit the user input form and go to the "Admin Settings". You should see your user input answers.

## Changelog entry

* Fix console error appearing in Admin Settings when User Input feature flag is enabled but Analytics is disconnected.

**Comment by tofumatt** [comment]
ACs are good 👍🏻

**Comment by tofumatt** [comment]
Lovely, IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Verified console error is not showing on Dashboard and on Settings page>Admin settings tab.
- Tested when analytics is not connected.
- Tested when analytics is connected and CTA to answer user input questions showing on both dashboard and Admin settings page without any console errors.
- Submitted the user input form and user input answers showing under admin settings without any console error.

<details>

**Latest -**

![image](https://user-images.githubusercontent.com/94359491/217437703-22b30777-7a3b-44a8-94dc-b37096d99ed2.png)

![image](https://user-images.githubusercontent.com/94359491/217437739-ca3788a8-6619-44a0-b98e-6b3cd638ede0.png)

**Dev-**

![image](https://user-images.githubusercontent.com/94359491/217437827-fe837e09-57a8-424e-a62b-a4882ab17465.png)

![image](https://user-images.githubusercontent.com/94359491/217437854-b0528298-1265-44c2-ab62-723429b9784d.png)

![image](https://user-images.githubusercontent.com/94359491/217437878-0d1023c7-993f-42b6-aa34-3622c408c1ce.png)

![image](https://user-images.githubusercontent.com/94359491/217437893-5e6fd996-dc45-4191-a6c3-de36fdc53bd0.png)

![image](https://user-images.githubusercontent.com/94359491/217437989-7aee8686-3e69-4d46-a642-bad7ae321d61.png)

![image](https://user-images.githubusercontent.com/94359491/217438028-b6d9a69b-6881-4b91-b4c3-f543fea3f631.png)

</details>
