### ISSUE TITLE
Remove `userInput` related flags and code from `Google_Proxy` class

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6505]
## Feature Description

Since the management and storage of `User Input` has been moved from service to plugin, the related flags and code from the `Google\Site_Kit\Core\Authentication\Google_Proxy` class. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User Input related flags and code should be removed from `Google\Site_Kit\Core\Authentication\Google_Proxy`. 

## Implementation Brief

* In `Google\Site_Kit\Core\Authentication\Google_Proxy` class.
    * Remove `user_input_flow` and `user_input_flow_feature` from the `get_supports` method. 
    * Remove the unused `sync_user_input_settings` method. 
    * Remove the `USER_INPUT_SETTINGS_URI` constant. 

### Test Coverage

* Update any failing tests. 

## QA Brief

* Tech task, N/A

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
Moved to Approval since there is nothing to QA
