### ISSUE TITLE
Register the key metric widgets in their own service modules

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#6510]
## Feature Description

In #6313, we introduced the Key Metric widget components in the `assets/js/components/KeyMetrics/widget-tiles` directory. And the registration of the widget components is done in the `assets/js/googlesitekit/widgets/register-defaults.js` file.
It is more appropriate for the widget components to living in their own modules directories and registers them respectively.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All the Key Metric widget components and their test files from `assets/js/components/KeyMetrics/widget-tiles` should be moved to their modules' directories.
  * For example, if a widget depends on `analytics-4`, it should be moved to the `assets/js/modules/analytics-4/components/widgets` directory.
* The `assets/js/components/KeyMetrics/widget-tiles` directory should be removed.
* Similarly, the Key Metric widgets should be registered in their respective modules.
  * For example, if a widget depends on `analytics-4`, it should be registered in the `assets/js/modules/analytics-4/index.js` file.

#### Moving the Widget Components

* Move the following components and their test files from `assets/js/components/KeyMetrics/widget-tiles` to `assets/js/modules/analytics-4/components/widgets`:
  * `AnalyticsLoyalVisitorsWidget`,
  * `AnalyticsLoyalVisitorsWidget`,
  * `AnalyticsNewVisitorsWidget`,
  * `AnalyticsTopTrafficSourceWidget`,
  * `AnalyticsEngagedTrafficSourceWidget`,
  * `AnalyticsPopularContentWidget`,
  * `AnalyticsPopularProductsWidget`,
  * `AnalyticsTopCitiesWidget`,
  * `AnalyticsTopCountriesWidget`,
  * `TopConvertingTrafficSourceWidget`,
* Move the following component and its test file from `assets/js/components/KeyMetrics/widget-tiles` to `assets/js/modules/search-console/components/widgets`:
  * `SearchConsolePopularKeywordsWidget`,
* Remove the `assets/js/components/KeyMetrics/widget-tiles` directory and its files, if any are left.

#### Registering the Widgets

* For each Key Metric widget registration in `assets/js/googlesitekit/widgets/register-defaults.js`:
  * Check the `settings.modules` property.
  * Register the widget in its respective module's directory:
    * Move all the above `analytics_4` widgets' registrations to `assets/js/modules/analytics-4/index.js` file.
    * Move the `search_console` widget registration to `assets/js/modules/search-console/index.js` file.
  * Remove the Key Metric widgets registration from `assets/js/googlesitekit/widgets/register-defaults.js`.

### Test Coverage

* No new tests are to be added.

## QA Brief

- This is a follow-up ticket for #6313. It doesn't involve any UI or feature changes except that it moves the widget components and registration. Additionally, renaming the components (see the PR description for more info).
- Execute the `getWidgets` selector from `core/widgets` store from the browser console:
```js
googlesitekit.data.select('core/widgets').getWidgets('mainDashboardKeyMetricsPrimary')
```
- Ensure all the widgets are registered correctly with their slug by comparing [the Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t) with the result of the above selector.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC and IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When the console code is run:
- All the widgets are registered correctly with their slug from [the Design doc table](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.78crkrvn0m7t) with the result of the selector.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/216121435-ef3b6212-6a22-4499-a06f-06defe33bf5b.png)
![image](https://user-images.githubusercontent.com/73545194/216121462-61870557-ea0f-44f2-b30a-f606d6d223b3.png)

</details>
