### ISSUE TITLE
Update GA4 `GET:report` to allow sorting by dimensions.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6513]
## Feature Description

While UA reports are by default ordered by their dimensions, GA4 reports are not. This is important for reports that rely on the dimension order e.g. those which use the `date` dimension. We need to provide support for sorting by dimensions in the GA4 `GET:report` endpoint.

As discussed on Slack, the Google API request shape has changed, from the UA version, which we mimic for our own `orderby` param:

```js
"orderBys": [
  {
    "fieldName": "ga:date",
    "sortOrder": "ASCENDING"
  },
  {
    "fieldName": "ga:users",
    "sortOrder": "ASCENDING"
  }
]
```

To the GA4 version as follows:

```js
"orderBys": [
  {
    "desc": false,
    "dimension": {
      "dimensionName": "date"
    }
  },
  {
    "desc": false,
    "metric": {
      "metricName": "totalUsers"
    }
  }
]
```

We should update the GA4 `orderby` parameter to be in keeping with the new `orderBys` shape, with corresponding handling on the backend to allow sorting by dimension.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 `GET:report` endpoint should support sorting by dimension.
* The `orderby` parameter for the endpoint should use/take the shape of the new GA4 `orderBys` request parameter as mentioned in the Feature Description and documented [here](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport).

## Implementation Brief

We want to follow the shape of the new GA4 `orderBys` schema, but we only need a subset for now. The schema for our `orderby` parameter will be as follows:

```ts
{
  orderby: [
    {
      // Either dimension or metric should be specified, not both.
      dimension: {
        dimensionName: string
      },
      metric: {
        metricName: string
      },
      desc: boolean // True for descending order, otherwise ascending. Optional, defaulting to `false` on the backend.
    },
    { /* ... as above, repeated */ }
  ]
}
```

Within `includes/Modules/Analytics_4.php`, in the `parse_reporting_orderby` method:
- Update the logic to parse the `orderby` parameter according to the schema above.
- Instantiate a `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\DimensionOrderBy` for each `dimension`.
- Call `$order_by->setDimension` to set the `DimensionOrderBy` instance on the `$order_by` object.

Within `assets/js/modules/analytics-4/utils/data-mock.js`:
- Update the `sortRows` function to handle the new `orderby` shape.

### Test Coverage

* Update the PHPUnit tests for the `Analytics_4` module to provide coverage for the new `orderby` parameter.
* Add test coverage to the `getAnalytics4MockResponse` test suite for the `orderby` parameter.

## QA Brief

* Follow the QAB for https://github.com/google/site-kit-wp/issues/6172, but exercise the new `orderby` parameter including ordering by both metrics and dimensions.

## Changelog entry

* Update the GA4 report endpoint to accept the new ordering properties.

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
@techanvil Looking at the QAB and AC. I'm wondering it should be a `QA:Eng` ticket. What are your thoughts ?

**Comment by techanvil** [comment]
Hi @mohitwp, thanks for raising this. Yes, as the QAB specifies to follow the QAB for #6172, this should indeed be a QA:Eng task, with a bit of regular QA for a smoke test as detailed on #6172.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Verified Dashboard Sharing Functionality.
- Verified Analytics set up with new and existing properties.
- Verified Analytics set up through GA4 activation banner.
- Verified Dashboard sharing functionality for Administrator and view only dashboard.
- Verified there are no references of Analytics 4 under Dashboard Sharing and Analytics setting

**Comment by aaemnnosttv** [comment]
## QA:Eng

LGTM, there was just one inaccuracy in the validation message wording. I've opened a tiny PR to update it.

**Comment by techanvil** [comment]
> ## QA:Eng
> LGTM, there was just one inaccuracy in the validation message wording. I've opened a tiny PR to update it.

Thanks for raising the followup PR @aaemnnosttv!
