### ISSUE TITLE
Wrap existing Key Metrics code within a feature flag

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6519]
## Feature Description

All new Key metrics code already merged to the `develop` branch should be put behind the `userInput` feature flag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* ~~Datastore infrastructure added as part of #6314 should only be loaded if the `userInput` feature flag is enabled.~~
* Widgets added as part of #6313 and #6510 should only be registered if the `userInput` feature flag is enabled.

## Implementation Brief

* In `assets/js/googlesitekit/datastore/user/index.js`
  * Only add `keyMetrics` to the store if `isFeatureEnabled('userInput')` is true.
  * Conditional operator could be used with assigning an empty object as a fallback:
    ```js
    const store = Data.combineStores(
		Data.commonStore,
		...
		featureTours,
		isFeatureEnabled('userInput') ? keyMetrics : {},
		notifications,
		...
    );
    ```
* In `assets/js/modules/analytics-4/index.js`, wrap the key metrics widget registration with a `isFeatureEnabled('userInput')`
* In `assets/js/modules/search-console/index.js` wrap the key metric widget registration with a `isFeatureEnabled('userInput')`
  https://github.com/google/site-kit-wp/blob/b72a4cd3fae06c9c885595dd6235bbcf2bd75029/assets/js/modules/search-console/index.js#L78-L91

### Test Coverage

* If there are failing js unit tests, enable key metrics feature flag inside the tests using
  ```js
  await enableFeature( 'userInput' );
  ```
  

## QA Brief

- This PR wraps the Key Metric widgets registration within the `userInput` feature flag. It doesn't involve any UI or feature changes.
- Enable the `userInput` feature flag.
- Execute the `getWidgets` selector from the `core/widgets` store from the browser console:
```js
googlesitekit.data.select('core/widgets').getWidgets('mainDashboardKeyMetricsPrimary')
```
- Ensure all the widgets are available.
- Disable the `userInput` feature flag and execute the above selector.
- Ensure the KM widgets are unavailable.

## Changelog entry

* Only register the Key Metrics widgets when the userInput feature flag is enabled.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
Thanks for clarifying this, @aaemnnosttv @jimmymadon.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When the `userInput` feature flag is enabled, and the getWidgets selector from the core/widgets store is executed, all the widgets are available.
- When the `userInput` feature flag is disabled and the getWidgets selector from the core/widgets store is executed, the KM widgets are unavailable.

<details>
 <summary>Details</summary>

https://user-images.githubusercontent.com/73545194/216961309-a0f3c525-df3d-46a9-aca4-212750e25181.mp4

![image](https://user-images.githubusercontent.com/73545194/216961314-ea641788-74f6-4f3e-9734-845913bed86d.png)

</details>
