### ISSUE TITLE
`mb_check_encoding` use can raise a fatal error in some environments

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6524]
## Bug Description

In #5868 we implemented a fix which resolves redirect issues on sites using internationalized domain names (IDN). This involves the use of a core PHP multibyte string function which may not exist on some environments. While the `mbstring` module is commonly enabled, [it is not enabled by default](https://www.php.net/manual/en/mbstring.installation.php) so we cannot rely on it to be generally available.

WordPress polyfills a few `mb_*` functions, (e.g. [`mb_substr`](https://github.com/WordPress/WordPress/blob/27529e9deec13aabd4e8f918035e1725982db164/wp-includes/compat.php#L43-L62), and [`mb_strlen`](https://github.com/WordPress/WordPress/blob/27529e9deec13aabd4e8f918035e1725982db164/wp-includes/compat.php#L138-L154)) but not all of them.

## Steps to reproduce

* Reproducing this requires the `mbstring` PHP module to be disabled
* Various actions could raise this error as the hooked function runs during [`wp_validate_redirect`](https://developer.wordpress.org/reference/functions/wp_validate_redirect/) which itself is called by various functions, notably [wp_safe_redirect()](https://developer.wordpress.org/reference/functions/wp_safe_redirect/)
* E.g. disconnect your user in Site Kit and navigate to the splash page
* Change the `googlesitekit-splash` in the URL to `googlesitekit-dashboard` and then attempt to navigate to that URL to invoke the redirect
* See error

## Support topics

* https://wordpress.org/support/topic/fatal-errors-in-the-wordpress-backend-after-latest-site-kit-update/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should not raise fatal errors in environments where the `mbstring` PHP module is not enabled
	* More specifically, Site Kit should not rely on any `mb_*` function to be provided by PHP
* The behavior introduced by #5868 should be preserved

## Implementation Brief

* Remove the `allowed_redirect_hosts` filter callback from `Plugin`
* Reimplement the existing behavior from the `Authentication::allowed_redirect_hosts` method
	- Parse the site's hostname with `URL::parse` instead of `(wp_)parse_url` functions can have problems with multibyte hostnames (see #4776)
		- Note: we probably want to use `admin_url` as the URL to parse here rather than the `home_url` for accuracy. The hosts should be the same because SK does not support them being different but this is more accurate because SK only does redirects within WP admin
	- Replace the use of `mb_check_encoding` with the same `is_ascii` check we use in `Module::permute_site_hosts`

### Test Coverage

* Add test coverage for the behavior in `AuthenticationTest` perhaps by testing a number of redirects using `wp_safe_redirect` with ascii + unicode domains and ensure the destination location is as expected (see `RedirectException` in our tests for examples)

## QA Brief

* Follow the steps to reproduce above, to ensure the error no longer happens
* This issue modifies how the changes in #5868 were implemented but it should continue to work the same as before in a way that is safe for environments that don't have the `mbstring` module/extension enabled

## Changelog entry

* Fix potential errors raised when the `mbstring` PHP extension is not loaded.

**Comment by felixarntz** [comment]
IB ✅

**Comment by jamesozzie** [comment]
Just an update on the impacted site, reported via the WordPress support forums:

- https://wordpress.org/support/topic/error-on-debug-pages/ - **Open** - Awaiting user response -  [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhPLyMBF-hB9DMS9CG8CSTJTZXWkai80n0qtR07GtEHlRGXm1cVXVHX7_iJ4aV3iHI)
- [https://wordpress.org/support/topic/site-stopped-working-after-new-update-of-sitekit/](https://wordpress.org/support/topic/site-stopped-working-after-new-update-of-sitekit/#post-16432409) - **Open** - Awaiting user response - [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgFoN1utEv03hJNFys42ROtJK2HS0kIHtLpLjZJQoIOVaor6_KhOp4LGeKdwAFvPhU)
- https://wordpress.org/support/topic/fatal-errors-in-the-wordpress-backend-after-latest-site-kit-update - [sh info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhqhbp0W7EYjpL7wRxlBO2gUWJleN8LRdjbp3NSbLV2j5YRoO2jBilVARL_pwYw1_c)
- https://wordpress.org/support/topic/_googlesitekituserdata-2/#new-topic-0 - **Open** - Awaiting user response - [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgApZkC1kx_Bhh2odDGv_5U8Qe4wNBdUAEWRdyjSoEIMcmjZ8Nvo29hgkdi-iYbIKA)
- https://wordpress.org/support/topic/fatal-errors-in-the-wordpress-backend-after-latest-site-kit-update/ - **Open** - Awaiting user response - SH info
- https://wordpress.org/support/topic/plugin-causing-error-7/ - **Open** - Awaiting user response - SH info
- https://wordpress.org/support/topic/_googlesitekituserdata-2/#post-16437254 - **Open** - Awaiting user response - SH info

@aaemnnosttv For those who have the ability to configure PHP modules, would enabling `mbstring` be something worth checking?

**Comment by aaemnnosttv** [comment]
> @aaemnnosttv For those who have the ability to configure PHP modules, would enabling `mbstring` be something worth checking?

@jamesozzie sure, that would fix the issue too, although I'm guessing most users wouldn't have that option.

**Comment by jamesozzie** [comment]
Good to know, thanks @aaemnnosttv.

**Comment by jaschawilcox** [comment]
> > @aaemnnosttv For those who have the ability to configure PHP modules, would enabling `mbstring` be something worth checking?
> 
> @jamesozzie sure, that would fix the issue too, although I'm guessing most users wouldn't have that option.

Confirming that installing `php-mbstring` in my Ubuntu 20.04 environment instantly resolved this issue.

`sudo apt install php-mbstring`

**Comment by bamnet** [comment]
Got paged my blog was down, presumably after a plugin auto update, and found this error. If you can't install mbstring quickly, you can bring your site back online by hacking in `wp-content/plugins/google-site-kit/includes/Plugin.php`

Look for `mb_check_encoding` and short-circuit it.  I did this:

```php
if ( true || mb_check_encoding( $wpp['host'], 'ASCII' ) ) {
```

**Comment by wpdarren** [comment]
@aaemnnosttv  I am trying to recreate the issue with the site you gave me access to. When I change the URL to `wp-admin/admin.php?page=googlesitekit-dashboard` and then navigate to that URL, I am redirected to `wp-admin/admin.php?page=googlesitekit-splash` and no error appears in the console or on screen. This is on the latest release (1.93.0)

I would ideally like to recreate it so I can verify that the issue is resolved. 

I am assuming that the `mbstring` PHP module is disabled on this site?

c.c. @tofumatt

**Comment by aaemnnosttv** [comment]
@wpdarren it is disabled but I didn't realize the polyfill plugin was still active which fills the gap there. I've since disabled it so this should be ready to test again 👍

**Comment by wpdarren** [comment]
### QA Update:

**Verified:**

- I was able to recreate the issue when changing the `googlesitekit-splash` in the URL to `googlesitekit-dashboard` and then attempting to navigate to that URL. 
- When I switched to the main branch, and ran through the same steps, no error appeared. The URL redirected to `googlesitekit-splash` successfully.  I also checked console and no new warnings or errors appeared. 
- Used a site with IDNs.
  - When setting up Site Kit without Analytics, I was redirected to Site Kit dashboard.
  - When setting up Site Kit with an Analytics account for the domain, I was redirected to the Site Kit dashboard.
  - When setting up AdSense, Tag Manager and Optimize, I was redirected to the Site Kit dashboard.

Related to the IDN. There were a few bugs discovered during testing #5868 and these are highlighted in https://github.com/google/site-kit-wp/issues/6435. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/217596657-4ebb6b6d-a986-49bd-8f30-3ff94acab07f.png)
![image](https://user-images.githubusercontent.com/73545194/217596718-331fb764-6b4c-4928-b2ac-9da2437941de.png)

</details>
