### ISSUE TITLE
GA4 GET:report endpoint failing to return rows

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6528]
## Bug Description

When testing #6173, I noticed that a network request is made successfully but there is no data returned. 

## Steps to reproduce

1. Setup Site Kit with a GA4 property that has some data (E.g. https://oi.ie).
2. Call the API endpoint using the browser console:
```javascript
reportParams = {
  // Note, metrics is a required parameter. All others are optional. The property ID for the report will be the currently connected GA4 property.
  metrics: [
    {
      name: 'totalUsers',
    },
  ],
  startDate: '2022-11-01',
  endDate: '2022-11-14',
  dimensions: [ 'date' ]
};

// Call the endpoint:
googlesitekit.api.get('modules', 'analytics-4', 'report', reportParams )
```
3. Notice that the `rowCount` in the response is null and no rows are returned for any combination of metric/dimensions.
4. Try the same query [using "Try the method" on the official API docs](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport?apix_params=%7B%22property%22%3A%22properties%2F276451909%22%2C%22resource%22%3A%7B%22dateRanges%22%3A%5B%7B%22startDate%22%3A%222023-01-01%22%2C%22endDate%22%3A%222023-01-31%22%7D%5D%2C%22metrics%22%3A%5B%7B%22name%22%3A%22totalUsers%22%7D%5D%2C%22dimensions%22%3A%5B%7B%22name%22%3A%22date%22%7D%5D%7D%7D). Change the Property ID to the GA4 property ID of the property you are using to test.

## Screenshots

Results via the Plugin endpoint:
<img width="1107" alt="Screenshot 2023-02-03 at 15 34 32" src="https://user-images.githubusercontent.com/1721319/216643408-d5ea5099-5da1-40d7-b423-50b5ec56ee99.png">

Results via the API docs tester:

<img width="327" alt="Screenshot 2023-02-03 at 15 35 53" src="https://user-images.githubusercontent.com/1721319/216643705-7392fae3-bb0f-4dc2-b15a-f9714bf39050.png">

<img width="322" alt="Screenshot 2023-02-03 at 15 36 37" src="https://user-images.githubusercontent.com/1721319/216643848-fa8db3f1-05ee-4d32-8883-be346aefd146.png">

## Additional Context

 - PHP Version: 7.4.32
 - OS: macOS Ventura 13.0.1
 - Browser: Chrome
 - Plugin Version: Latest `develop` branch.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GET:report` datapoint created in #6172 should return data rows when a valid GA4 account with data is connected.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@jimmymadon the endpoint seems to work fine in my local testing on the current develop 5edc568b6aed809e46c606c6a9b6f2f0aafb72bc

![image](https://user-images.githubusercontent.com/1621608/216669914-44960556-79d1-42f7-8701-15d00450a056.png)
