### ISSUE TITLE
Duplicate GA4 property created in some cases via activation banner

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6529]
## Bug Description

The GA4 activation banner prompts users to set up GA4 who have UA Analytics connected but no GA4.

One of the options is to create a new GA4 property (even if the user already has one) although in many cases this is likely the only option.

Since the `analytics.edit` scope is not persisted or even proactively requested when setting up Analytics, in most cases the user will need to grant this scope before the new GA4 property can be created.

In the scenario where the scope must first be granted to create the GA4 property, this results in an extra/duplicate GA4 property being created in the process.

## Steps to reproduce

1. Start with Site Kit set up with Analytics, and without GA4 connected (the ga4 settings can be deleted after initial setup to accomplish this)
2. Ensure any Analytics write scope is cleared out (simply disconnecting via SK and reconnecting will accomplish this)
3. Go to main SK dashboard – you should be prompted to set up GA4 via the activation banner
4. Initiate the setup, choosing to create a new property if given the option
5. After setting up, see that there are two new GA4 properties created

## Screenshots

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1621608/216653356-e9907218-8171-420e-a04b-ebf800b36251.png">

Note the two requests that are made for `create-property` (two `create-webdatastream` requests are correct – one for each property) so the problem is primarily that two properties are created.

## Additional Context

It is not clear exactly when this was introduced, but given there have not been changes to the activation banner recently, it could have been there since its introduction.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When creating a new property via the GA4 activation banner, only a single GA4 property should be created
	* Special attention should be given to the different scenarios where this happens, specifically with and without the necessary edit scope granted
* Test coverage should be extended to include these scenarios 

## Implementation Brief

Having investigated the issue, it turns out the problem occurs because the [`useEffect`](https://github.com/google/site-kit-wp/blob/5ef7abacd409518ad9dfe49f553e9a841e20383e/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js#L251-L255) that calls `handleSubmitChanges` is re-triggered due to the `handleSubmitChanges` instance changing, itself in response to its `useCallback` dependency `variant` changing. There are a number of ways to address this, one could be to include `variant` in the `useEffect` conditions, however a more robust and coherent solution is to make use of the `isSaving` state variable instead. 

Within `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js`:

* Add a check for `! isSaving` to the condition that surrounds the call to `handleSubmitChanges` within the `useEffect` mentioned above.

### Test Coverage

* Add tests for `SetupBanner` that cover the scenarios described in the AC.

## QA Brief

The only observable change here should be the duplicate property created when setting up a new property via the activation banner when the additional scope needs to be granted.

The setup flow of the GA4 activation banner was the only part modified, so the whole GA4 setup banner need not be tested, but various setup scenarios via the activation banner should be tested.

1. Start with Site Kit set up with Analytics, and without GA4 connected (the ga4 settings can be deleted after initial setup to accomplish this)
2. Ensure any Analytics write scope is cleared out (simply disconnecting via SK and reconnecting will accomplish this)
3. Go to main SK dashboard – you should be prompted to set up GA4 via the activation banner
4. Make sure the language at the bottom of the GA4 activation banner shows as before as applicable.
5. Initiate the setup, choosing to create a new property if given the option
6. After setting up, there should only be one new GA4 property created

## Changelog entry

* Fix bug that caused two GA4 properties to be created from the GA4 activation banner on the Site Kit dashboard.

**Comment by wpdarren** [comment]
@aaemnnosttv out of interest, would two GA4 properties have been created within the Analytics account too? Or is this in the background? I'm going to make a note that when we test the activation banner, we should check the network tab. This feels like a bug we should have picked up on during QA.

**Comment by techanvil** [comment]
@wpdarren, I can confirm that two GA4 properties are currently being created in the Analytics account, yup.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main.
- Verified Analytics set up through GA4 activation banner and tested below cases
   

> Setup new property when user don't have additional authentication scope.  
>    Setup new property when user have additional authentication scope.   
>    Created new property when analytics a/c don't have any GA4 property. 

- Also, tested setup of GA4 property from Analytics settings.
- Verified When creating a new property via the GA4 activation banner, only a single GA4 property is getting created.
- Verified analytics setup flow through splash screen and set up new property.

<details>


https://user-images.githubusercontent.com/94359491/220600884-439c33cb-ed48-4a0e-b52b-22c217d84aae.mp4


https://user-images.githubusercontent.com/94359491/220600946-0c05a5e4-eb0f-498a-9ce2-811e6be84bba.mp4

</details>
