### ISSUE TITLE
Update GA4 Activation Reminder Banner

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6538]
## Feature Description

The GA4 Activation - Reminder Banner will need to be updated according to the [Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=221%3A2414&t=5WzRQLKEXfmCKDm6-0). The major updates are:
- Adding `Google Analytics 4 benefits:` as a heading to the column on the right.
- Copy updates to the Reminder Banner variant shown after June 30 2023.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.7grali4q89tj) is the relevant part in the design doc.

Here is a screenshot for visual aid:
![image](https://user-images.githubusercontent.com/20284937/217350645-fbcc3cbd-fbf6-4c6f-8f96-140ab407cb01.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The GA4 Activation - Reminder Banner should be updated to fully match [this Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=221%3A2414&t=hqeaF9O7yieeZNio-0).
- For the column on the left:
    - The warning icon should be removed from the description text.
    - For the Reminder Banner variant shown after June 30 2023, the title and description copy should be updated according to the Figma design.
    - The "Learn more about GA4" string (https://github.com/google/site-kit-wp/blob/97ea125134ce5d2c49540ebb27539db5c78a59cd/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js#L227) should be updated for all versions of the banner to bring it in-line with a similar translation change made in #6539
- For the column on the right showing GA4 features:
    - It should have the `Google Analytics 4 benefits:` heading added.
    - The list style image/icon should be updated to match the design (check inside a circle).
    - The copy of the list items should be updated according to the design.
- The separator in between the columns should be removed, as shown in the design.

## Implementation Brief

Within `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js`:

- To remove the warning icon, remove usage of `ErrorIcon`.
- Update the post-June 30 2023 variant of [`title` and `description`](https://github.com/google/site-kit-wp/blob/51f7b80b3081b0ae653e247b9cacc00e7a160ec5/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js#L190-L197) as per Figma.
  - `title`: _Universal Analytics stopped collecting data on July 1, 2023_
  - `description`: _Set up Google Analytics 4, the new version of Google Analytics, to continue seeing data in Site Kit._
- Remove the "Learn more..." `Link` from the `secondaryPane` JSX and instead implement the learn more link via the `learnMore.*` props to `BannerNotification`, using the updated text as per the AC.
  - `learnMoreLabel`: _Learn more about Google Analytics 4_
- Add the title to the `secondaryPane` JSX, ensuring it's styled as per Figma.
  - Title: _Google Analytics 4 benefits:_
- Update the list item text as per Figma:
  - _Full cross-device and cross-platform reporting_
  - _Advanced conversion tracking, such as when visitors submit a form or add an item to cart_
  - _Detailed insights on how users navigate your site_

Within `assets/sass/components/analytics-4/_googlesitekit-analytics-4-reminder-banner.scss`.

- Make any required updates to the SASS in order to accommodate the above changes.
- For the change to the list style icon, as we're still on GM2+, go to this [GM2+ Figma file](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?node-id=1669%3A15285&t=0Zv5L3D0zabusd2Y-0), search for `check_circle`, and export the icon as an SVG. Set the SVG's `fill` attribute to `currentColor`, and use it to replace the existing icon for `ul` elements.

### Test Coverage

* No new tests needed.

## QA Brief

* Trigger the GA4 Activation Reminder Banner (this can be done by creating a site, connecting Analytics, and removing the GA4 module settings from the database).
* Check that the new banner matches the design below:

<img width="778" alt="CleanShot 2023-03-29 at 12 53 50" src="https://user-images.githubusercontent.com/90871/228527521-bf3196de-0d5a-4bd8-95d7-e275640f2ffe.png">

## Changelog entry

* Update design and text of GA4 Reminder Banner.

**Comment by bethanylang** [comment]
@nfmohit Just to confirm what is probably obvious, but this will need to go launch *on* July 1, 2023, is that correct? cc @aaemnnosttv

**Comment by nfmohit** [comment]
> @nfmohit Just to confirm what is probably obvious, but this will need to go launch _on_ July 1, 2023, is that correct? cc @aaemnnosttv

Hi @bethanylang! Thank you for the question.

This specific one can go to launch earlier, or as soon as it is done. This screen is already present in Site Kit and we only want to update some copy according to updates in the Figma designs.

**Comment by bethanylang** [comment]
@nfmohit Perfect, thank you!

**Comment by tofumatt** [comment]
ACs 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@nfmohit 

1. I've noticed that in Figma design Title "Google Analytics 4 benefits:"  font family is 'Google Sans Text' and implemented font family is 'Google Sans Display'. Is this expected ?

<details>

![image](https://user-images.githubusercontent.com/94359491/229022061-23cc22e1-2179-4bf3-a277-debceb89f7f0.png)

![image](https://user-images.githubusercontent.com/94359491/229022189-6b9efd27-fe83-4191-807f-198760639723.png)

</details>

2. Also, new copy font color is #757575 in Figma where as implemented  font color is #7b807d. Is this expected ?

<details>

![image](https://user-images.githubusercontent.com/94359491/229022650-22a65e70-8e2e-4b6e-b868-4c8b019f42b3.png)

![image](https://user-images.githubusercontent.com/94359491/229022580-132147f3-045d-4618-ac69-1ae1ad67a059.png)

</details>




- Banner showing with updated copy on different dates

<details>


![image](https://user-images.githubusercontent.com/94359491/229022863-d00aa48e-cb55-40b0-8382-f7746bcefa62.png)

![image](https://user-images.githubusercontent.com/94359491/229022926-a9153fdb-60c3-4cde-9790-b82f93266b52.png)

![image](https://user-images.githubusercontent.com/94359491/229022998-0264155e-2b98-46df-b3c6-e4709f892053.png)

</details>

**Comment by sashadoes** [comment]
HI @mohitwp, thanks for your review and feedback. I made updates to fix the font and color.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- The issue reported above related to font family and font color is now resolved.
- Verified GA4 Activation Reminder banner updated as per Figma design.


<details>

![image](https://user-images.githubusercontent.com/94359491/229989339-9af844fc-9817-4308-82a7-608b2e775426.png)

![image](https://user-images.githubusercontent.com/94359491/229989377-3e8081da-1007-467b-803b-932dd2c46f8a.png)

![image](https://user-images.githubusercontent.com/94359491/229022863-d00aa48e-cb55-40b0-8382-f7746bcefa62.png)

![image](https://user-images.githubusercontent.com/94359491/229022926-a9153fdb-60c3-4cde-9790-b82f93266b52.png)

![image](https://user-images.githubusercontent.com/94359491/229022998-0264155e-2b98-46df-b3c6-e4709f892053.png)

</details>
