### ISSUE TITLE
Update GA4 Activation Success Banner

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6539]
## Feature Description

The GA4 Activation - Success Banner will need to be updated according to the [Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1%3A4826&t=SYxmtCZ2IAQjlZAB-0). The major updates are:
- Updating the banner copy.
- Updating the graphic.

Since the GA4 dashboard view isn't available right away, it might be a good idea to keep the update to the banner copy behind the `ga4Reporting` feature flag.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.7grali4q89tj) is the relevant part in the design doc.

Here is a screenshot for visual aid:
![image](https://user-images.githubusercontent.com/20284937/217350784-0d236080-c8ae-4e97-845a-e37a77ab1d78.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Since the description copy mentions switching the Site Kit dashboard, and the GA4 dashboard view isn't available yet, the description should only show the new copy if the `ga4Reporting` feature flag is enabled. Otherwise, it should keep showing the existing copy.
- The GA4 Activation - Success Banner should be updated to match [this Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1%3A4826&t=2CSfrdInSK1Fl12X-0).
- The `WinImage` graphic should be updated according to the design.
- The copy in the description should be updated according to the text in the Figma design linked above. Note the "learn more" link's text should read "Learn more about Google Analytics 4" not "Learn more about GA4"
  - The link text should be changed for _all_ versions of the component, eg. regardless of the `ga4Reporting` feature flag. 
  - The link should continue to go to the same URL defined in the existing component.

## Implementation Brief

Within `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SuccessBanner.js`:

- Check if the `ga4Reporting` feature flag is enabled. If so replace the current `description` with the text as per Figma:
  - `description`: _Google Analytics 4 has started collecting data for your site. As soon there is enough data, you'll be able to switch your Site Kit dashboard to show data from Google Analytics 4._
- Update `learnMoreLabel` as per Figma:
  - `learnMoreLabel`: _Learn more about Google Analytics 4_
- Export the new graphic as an SVG and save it in `assets/svg/graphics/`. Use this new SVG in place of the current `SuccessGreenSVG` component.
  - Navigate to the [Figma](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1%3A4826&t=kJ605HT3kLoGKllr-0) and search for "Group 2609388" to highlight the group to export for the SVG.

### Test Coverage

* No new tests needed.

## QA Brief

* Activate GA4 using the GA4 activation banner with the `ga4Reporting` feature flag enabled.
* Ensure the new description copy is displayed per the AC/Figma design.
* Activate GA4 using the GA4 activation banner with the `ga4Reporting` feature flag disabled.
* Ensure the old description is displayed.
* Ensure the learn more label and the SVG are changed per the new design for both cases.
* Ensure the new story [Modules > Analytics4 SuccessBanner > SuccessBanner with GA4 Reporting Enabled](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-successbanner--with-ga-4-reporting-enabled) is as expected.

## Changelog entry

* Update the graphic and copy on the GA4 Activation Success Banner.

**Comment by tofumatt** [comment]
Looks good, just added a point about the copy text and updating another component with the same translation that's being changed here for consistency.

Moved to IB 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@hussain-t  I've noticed that new graph is not showing in mobile viewports (Width less than 600). Are we not going to show graph in mobile size viewports ?

![image](https://user-images.githubusercontent.com/94359491/226273190-d709247b-bcbd-4287-af24-5f7f7b7857d6.png)

**Comment by hussain-t** [comment]
Thanks for raising this, @mohitwp. IMHO, it looks much better without the graphic SVG on the smaller screens, as the image is more prominent. However, I would like to get @marrrmarrr opinion on this. This is how it looks on a smaller screen:

![Screenshot 2023-03-20 at 3 29 05 PM](https://user-images.githubusercontent.com/24408261/226321981-430c2ca8-e040-4d09-9d86-139aa33204d6.png)

**Comment by marrrmarrr** [comment]
@hussain-t @mohitwp agreed that the mobile version looks better without the graphic. Do we need to apply this in other cases as well?

**Comment by hussain-t** [comment]
Thanks, @marrrmarrr. IMHO, yes, to keep it consistent. However, please note that some banners render the image on the left and some on the right.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- The GA4 Activation - Success Banner should be updated to match [this Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1%3A4826&t=2CSfrdInSK1Fl12X-0).
- Tested GA4activation banner set up when ga4reporting feature flag is enabled.
- Verified banner is appearing with new copy.
- Tested GA4activation banner set up when ga4reporting feature flag is disabled.
- Verified banner is appearing with old description.
- Verifed  the learn more label and the SVG are changed per the new design for both cases.
- Verified the  new story [Modules > Analytics4 SuccessBanner > SuccessBanner with GA4 Reporting Enabled](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-successbanner--with-ga-4-reporting-enabled) is as expected.


<details>

![image](https://user-images.githubusercontent.com/94359491/226907002-f62ba80a-77f2-41f2-9c6c-497fa824be14.png)

![image](https://user-images.githubusercontent.com/94359491/226907039-4d4c3712-6e9f-4372-b259-d0e41a906e2d.png)

</details>
