### ISSUE TITLE
Show PSI performance stats on single page details screen

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#654]
## Feature Description

Currently, we only show performance stats for the Homepage in the dashboard, which was the MVP requirements for the PSI module. Let's show the same widget in the `dashboard-details` screen (stats for a single URL), for that specific URL.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Show the PSI widget from `dashboard` also in `dashboard-details`, if the PSI module is active.
* The widget should also show at the bottom of the screen, similar to `dashboard`.
* The stats for the widget should be for the page's URL, not for the homepage (unless the single page _is_ the homepage, of course :) ).
* In the copy of the widget, the `dashboard-details` version should use "this page" instead of "home page" (in the widget description and the loading state text).

## Implementation Brief

* Update `<PageSpeedInsightsDashboardWidgetHomepageSpeedColumn>` to no longer be homepage specific
    - Should be able to accept title, message, etc as props
    - Already loads the `permaLink` by default, so the requests are already correct on `dashboard-details` view
    - Add to dashboard details view (e.g.)  
    ```diff
    diff --git a/assets/js/modules/pagespeed-insights/index.js b/assets/js/modules/pagespeed-insights/index.js
    index 222bb42..beede3d 100644
    --- a/assets/js/modules/pagespeed-insights/index.js
    +++ b/assets/js/modules/pagespeed-insights/index.js
    @@ -44,6 +44,11 @@ if ( active && setupComplete ) {
        addFilter( 'googlesitekit.DashboardModule',
            'googlesitekit.PageSpeedInsights',
            addDashboardSpeed, 45 );
    +
    +   addFilter( 'googlesitekit.DashboardDetailsModule',
    +       'googlesitekit.PageSpeedInsights',
    +       addDashboardSpeed, 45 );
    +
        addFilter( 'googlesitekit.DashboardSpeed',
            'googlesitekit.PageSpeedInsightsHomepageSpeed',
            addPageSpeedInsightsDashboardWidgetHomepageSpeed );
    ```

## Changelog entry

* Show PageSpeed Insights performance stats for every individual URL in its details view, accessible from Site Kit dashboard and admin bar.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
Prioritizing this after post-launch feedback, also in regards to that this is a small issue.

**Comment by aaemnnosttv** [comment]
## QA

Dashboard (homepage)
![image](https://user-images.githubusercontent.com/1621608/69338373-ba9b5f00-0c6b-11ea-91b8-410a0e7f50e1.png)

Dashboard details (blog page)
![image](https://user-images.githubusercontent.com/1621608/69338401-cdae2f00-0c6b-11ea-86f7-9cd1d57adf62.png)

Cache shows data is page/URL specific 👍 
![image](https://user-images.githubusercontent.com/1621608/69338496-01895480-0c6c-11ea-919c-563c94cbaa6b.png)

**Comment by marrrmarrr** [comment]
LGTM.

**Comment by TheLisaClark** [comment]
Hey SITE KIT Team, You are Doing a good Job. Nice Update, 

I have a problem With my Dashboard.

> Search Funnel
> How your site appeared in search results and how many visitors you got from Search.

This section is not working properly. 

CMS - Wordpress 
Version - 5.3
Theme - GeneratePress
Site - <a href="https://theblackfriday.deals">https://theblackfriday.deals</a>

We are using Site Kit by Google - Version 1.1.0

**Comment by aaemnnosttv** [comment]
Hi @TheLisaClark 👋 (and thank you!)

This issue is specific to an enhancement related to PageSpeed Insights. If you're experiencing an issue and looking for support, please start with the plugin's support forum which is actively supported by our team here: https://wordpress.org/support/plugin/google-site-kit/
