### ISSUE TITLE
New Analytics module setting to store dashboard view

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6540]
## Feature Description

Since the GA4 metrics will roll out alongside existing UA metrics, some concept of an Analytics dashboard view will be needed to determine which variant of Analytics metrics to display: UA (current) or GA4.

For sites with the `ga4Reporting` feature available, we only want to switch to GA4 metrics on the dashboard in response to the user’s choice as switching automatically could be confusing since the metrics are intended to be a drop-in replacement as much as possible. This is particularly relevant if there was a substantial discrepancy between UA + GA4 values for the same metric.

This issue should address adding this as a module setting to the `Analytics` module. Since GA4 would be the only dashboard view at a point, the need for this setting is temporary. The idea behind adding this as an `Analytics` module setting is that it is only relevant as long as UA Analytics is still around. Later when it is removed, it would be removed along with that infrastructure.

This setting can be called `dashboardView`.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.7s9yj14iv0bm) is the relevant part in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `Analytics` module should have a new module setting added, named `dashboardView`.
- The value of this setting should be a string, and can be one of `universal-analytics` or `google-analytics-4`.
- Its default value should be `universal-analytics`.
- The `Analytics` module base datastore should be updated to include this new setting slug.

## Implementation Brief

* In `includes/Modules/Analytics/Settings.php`:
    - In the `get_default()` method, add the `dashboardView` setting with `universal-analytics` as the default value as per the AC.
    - In the `get_sanitize_callback()` method, check if the new `dashboardView` option is set. If it is, ensure it is one of the two valid values as per the AC, otherwise unset this setting from the option to preserve the original value.
* In `assets/js/modules/analytics/datastore/base.js`:
    - Add the new setting key to the `settingSlugs` array.

### Test Coverage

* Update `tests/phpunit/integration/Modules/Analytics/SettingsTest.php` to test the new setting.
* Update `assets/js/modules/analytics/datastore/settings.test.js` to test the new setting.

## QA Brief

* Since there are no user facing changes here, smoke test the plugin setting up analytics. Ensure there are no new errors when fetching analytics reports on the dashboard or viewing/editing Analytics settings.

### QA: Eng

- Verify the new setting is included in the `modules/analytics' datastore. Set and get the new setting value and ensure it is stored correctly in the database. E.g.
```javascript
await googlesitekit.api.get('modules', 'analytics', 'settings');
await googlesitekit.api.set('modules', 'analytics', 'settings', {'dashboardView': 'google-analytics-4'});
```

## Changelog entry

* Add the new setting to the Analytics module to determine the dashboard type.

**Comment by tofumatt** [comment]
ACs 👍🏻 

Thanks so much for all the context in these GA4 Reporting issues 🙌🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Since the QAB did not mention if we should test this with the `ga4Reporting` enabled or not, I have tested setting up Analytics with the feature flag enabled and disabled to make sure there are no issues.  I could not see any errors in the console, or front end.  In both occasions I used a new site, but I also tested on a site with data.  

Labelled this ticket `QA:Eng` for the task in the QAB.

**Comment by kuasha420** [comment]
QA: Eng :heavy_check_mark: 

* On `develop` the newly added `dashboardView` Analytics settings available.
* The value is `universal-analytics` by default. 
* It can be changed to supported `google-analytics-4` and the aforementioned `universal-analytics`.
* Trying to change it to an unsupported value retains the current one. 

One thing I'd like to note is that this setting is added unconditionally and not only for `ga4Reporting` but I don't see it as a problem if we check for the feature flag in addition to the settings while making use of it in the dependent issues. Maybe it could be part of sanitation step to only allow the setting to be `google-analytics-4` if the feature flag was set, just for completeness. cc @nfmohit 

LGTM.

**Comment by nfmohit** [comment]
> One thing I'd like to note is that this setting is added unconditionally and not only for `ga4Reporting` but I don't see it as a problem if we check for the feature flag in addition to the settings while making use of it in the dependent issues. Maybe it could be part of sanitation step to only allow the setting to be `google-analytics-4` if the feature flag was set, just for completeness. cc @nfmohit

Nice catch, thank you for flagging, @kuasha420! I believe it is fine for now since everything user-facing is behind the feature flag, but yes, having this check in the sanitization would be a nice added step.
