### ISSUE TITLE
Add `isGA4DashboardView` selector

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6541]
## Feature Description

An `isGA4DashboardView` selector should be added to the `analytics-4` datastore, which should indicate if a site is using the GA4 dashboard view. It should return true if GA4 is connected and the `dashboardView` module setting (being added in #6540) is set to GA4.

This selector will later be updated to return `true` unconditionally if GA4 is connected in #6549.

The selector response should be behind the `ga4Reporting` feature flag.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.7s9yj14iv0bm) is the relevant part of the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `analytics-4` datastore should have a new selector added, named `isGA4DashboardView()`.
- The selector should do the following:
    - Check if `ga4Reporting` feature flag is enabled, and if not, return `false`.
    - Check if GA4 is active, and if not, return `false`.
    - Check if the Analytics `dashboardView` module setting (being implemented in #6540) is set to `google-analytics-4`, and if so, return `true`.

## Implementation Brief

* Within `assets/js/modules/analytics-4/datastore/settings.js`:
    - Similar to `getCanUseSnippet` in `analytics/datastore/settings.js`, export a new selector using `createRegistrySelector()` named as per the AC.
    - Use `isFeatureEnabled` to check if `ga4Reporting` is enabled, otherwise return false as per the AC.
    - Use `isModuleActive` selector from the `core/modules` store to check if `analytics-4` is active. If not, return false as per the AC.
    - Use the new `getDashboardView()` selector from the `modules/analytics` store and if it returns `google-analytics-4`, then return true as per the AC. Otherwise return false.
* Within `assets/js/modules/analytics-4/datastore/base.js`:
    - Import the `isGA4DashboardView` selector created above and append it to the selectors array within `baseModuleStore` (similar to `getCanUseSnippet` within `analytics/datastore/base.js`)

### Test Coverage

* Add JS tests similar to the `getCanUseSnippet` tests, testing each condition in the ACs.

## QA Brief

* Execute the `googlesitekit.data.select('modules/analytics').isGA4DashboardView()` selector from the browser with following scenarios:
   * When the `ga4Reporting` is disabled - it should return `false`.
   * When the `ga4Reporting` is enabled, but the Analytics-4 module is inactive, it should return `false`.
   * When the above conditions are met but the Analytics settings `dashboardView` is not `google-analytics-4`, i.e., `universal-analytics` - it should return `false`.
   * When the first two conditions are met and the Analytics settings `dashboardView` is `google-analytics-4` - it should return `true`.
* To check the Analytics settings, execute the `googlesitekit.data.select('modules/analytics').getSettings()` selector.
* To set the Analytics settings `dashboardView`, dispatch the following action:
```js
googlesitekit.api.set('modules', 'analytics', 'settings', {'dashboardView': 'google-analytics-4'});
```
**Note:** After dispatching the action, refresh the page to load the settings.

## Changelog entry

* Add the new `isGA4DashboardView` selector to the Analytics module.

**Comment by tofumatt** [comment]
ACs 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️
