### ISSUE TITLE
Update link url on AdSense "Your site isn't ready to show ads yet" set-up landing page

### ISSUE THREAD

**Issue by OisinOConnor** [google/site-kit-wp#655]
## Feature Description

Parse subdomains down to root domains in the deep link to AdSense:
Site Kit currently links to the “Sites” page of AdSense with this link:
https://www.google.com/adsense/new/sites?url={$sitekit-site-url}&source=site-kit
where ($sitekit-site-url) is the full url of the WordPress site.
Change requested: change the value of ($sitekit-site-url) to only display the root domain. Any subdomains or folders will need to be parsed out. e.g. if the WordPress install is on
blog.example.com or example.com/blog
The value inputted into the above link should be example.com so that using Site Kit on blog.example.com will provide a link to users:
https://www.google.com/adsense/new/sites?url=example.com&source=site-kit

Screen 3:
### Your site isn’t ready to show ads yet
You need to fix some things before we can connect Site Kit to your AdSense account.
Go to AdSense to find out how to fix the issue

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This has been fixed by now as part of the AdSense refactoring which happened in early 2020.
