### ISSUE TITLE
Update condition for rendering GA4 metrics

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6550]
## Feature Description

UA metrics are being replaced with GA4 counterparts in issues #6220, #6221, and #6222. Since we are now introducing a setting for dashboard view choice (in #6540), the condition for these replacements needs to be updated so that besides checking the `ga4Reporting` feature flag, the `isGA4DashboardView` selector (being added in #6541) is also checked.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.kqq0o0tmwdv0) is the relevant part in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- All the component replacements made in [#6220](https://github.com/google/site-kit-wp/issues/6220), [#6221](https://github.com/google/site-kit-wp/issues/6221), and [#6222](https://github.com/google/site-kit-wp/issues/6222) depending on the condition of the `ga4Reporting` feature flag being enabled should be updated to depend on the `isGA4DashboardView()` selector (being introduced in #6541) instead.
- In these replacements, the check for the `ga4Reporting` feature flag should be removed and the `isGA4DashboardView()` selector from the `analytics-4` datastore should be used instead.

## Implementation Brief

* Replace the `ga4Reporting` feature flag check with the result of `select(MODULE_ANALYTICS_4).isGA4DashboardView()` in:
  * `assets/js/components/adminbar/AdminBarWidgets.js`
    * `assets/js/components/adminbar/AdminBarWidgets.stories.js` may need updating as this selector must now return true instead of just the feature flag
  * `assets/js/components/wp-dashboard/WPDashboardWidgets.js`
    * `assets/js/components/wp-dashboard/WPDashboardWidgets.stories.js` may also need updating as this selector must now return true instead of just the feature flag
  * For `assets/js/modules/analytics/index.js` and `assets/js/modules/search-console/index.js`, we can't access `useSelect` because they aren't React components, so instead we should create a new component that renders either a UA or GA4 widget based on the dashboard settings, eg:

```js
export default function GA4DashboardWidgetSwitcher( { UA, GA4 } ) {
    const isGA4DashboardView = useSelect( ( select ) => select( ANALYTICS_4 ).isGA4DashboardView() );
    
    return isGA4DashboardView ? <UA /> : <GA4 />;
}
```
  * This component should be used for any widget registration that renders a widget based on GA4 Dashboard settings, eg: `Component: () => <GA4DashboardWidgetSwitcher UA={ DashboardAllTrafficWidget } GA4={ DashboardAllTrafficWidgetGA4 } />,`

See @eugene-manuilov's comment below for more info: https://github.com/google/site-kit-wp/issues/6550#issuecomment-1462453318

### Test Coverage

* Storybook stories mentioned above might need updating.
* Basic Jest tests for the new `GA4DashboardWidgetSwitcher` component

## QA Brief

* Ensure the `ga4Reporting` feature flag is enabled since it is required in the `isGA4DashboardView` selector.
* If the dashboard view is `universal-analytics`, ensure the UA widget components are displayed.
* Set the dashboard view to GA4 by executing the following in the browser console:
```js
googlesitekit.api.set('modules', 'analytics', 'settings', {'dashboardView': 'google-analytics-4'}) 
```
* Refresh the page and ensure the GA4 widget components are displayed.
* To check the current dashboard view:
```js
googlesitekit.data.select( 'modules/analytics' ).getDashboardView()
```

## Changelog entry

* Ensure that Analytics 4 widgets are only displayed when the dashboard view is in Analytics 4 mode.

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
> Replace the `ga4Reporting` feature flag check with the result of `select(MODULE_ANALYTICS_4).isGA4DashboardView()` in:
> * `assets/js/modules/analytics/index.js`
> * `assets/js/modules/search-console/index.js`

@tofumatt this will not work because `registerWidgets` functions in those files are not react components. We need to find another way to implement this. I think we will probably need to create a wrapper component for those widgets that will render either UA or GA4 version based on the setting. Something like this:

```js
export default function GA4DashboardWidgetSwitcher( { UA, GA4 } ) {
    const isGA4DashboardView = useSelect( ( select ) => select( ANALYTICS_4 ).isGA4DashboardView() );
    
    return isGA4DashboardView ? <UA /> : <GA4 />;
}
```
Then in the `registerWidgets` function:
```js
	widgets.registerWidget(
		'analyticsAllTraffic',
		{
			Component: () => <GA4DashboardWidgetSwitcher UA={ DashboardAllTrafficWidget } GA4={ DashboardAllTrafficWidgetGA4 } />,
			width: widgets.WIDGET_WIDTHS.FULL,
			priority: 1,
			wrapWidget: false,
			modules: [ 'analytics' ],
		},
		[
			AREA_MAIN_DASHBOARD_TRAFFIC_PRIMARY,
			AREA_ENTITY_DASHBOARD_TRAFFIC_PRIMARY,
		]
	);
```

**Comment by tofumatt** [comment]
Oh, of course, thanks for that 😅 

I like your suggested approach, it's very clean. I've updated the IB 👍🏻

**Comment by eugene-manuilov** [comment]
Thanks, @tofumatt. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- When GA4 reporting is enabled and dashboard view is 'GA4' then Ga4 components widgets are showing on SK Admin bar, main, entity and WP dashboard, 
- When GA4 reporting is  not enabled and dashboard view is 'UA' then UA components widgets are showing on SK Admin bar, main, entity and WP dashboard, 
- Tested using React Dev extension.

<details>

![image](https://user-images.githubusercontent.com/94359491/227886908-24fa0956-1815-411e-9a72-7c61337304da.png)

![image](https://user-images.githubusercontent.com/94359491/227887176-5eaeb09e-9d4b-4d91-903a-8fc78ce243ce.png)

![image](https://user-images.githubusercontent.com/94359491/227887412-2100dd28-31dc-4fa2-8f23-e36a548db1bc.png)

![image](https://user-images.githubusercontent.com/94359491/227887536-08f2a9b6-2191-4547-8de8-2d2b38f49a47.png)

![image](https://user-images.githubusercontent.com/94359491/227887771-f70188a9-22e4-4897-a634-44bbc7f81595.png)

![image](https://user-images.githubusercontent.com/94359491/227887876-30db149a-8878-4a1e-aabb-d09de0589cad.png)

![image](https://user-images.githubusercontent.com/94359491/227888004-2ce4f4b3-0d50-4a22-a6d6-809ee95e3dee.png)

![image](https://user-images.githubusercontent.com/94359491/227888258-cf158f9e-b95f-4f12-9b0d-6d841536800f.png)

![image](https://user-images.githubusercontent.com/94359491/227888671-1d16c333-5abc-4336-8a42-de6c689b8710.png)

</details>
