### ISSUE TITLE
Update "Create Goals CTA"

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6551]
## Feature Description

As a part of the GA4 dashboard view, the “Goals” metric will be entirely replaced with the new “Conversions” metric. As a part of this replacement, we will also update the CTA to set up “Goals” to instead say “Conversions”.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.ksyo37xwnpqr) is the relevant part in the design doc.

Here is a screenshot for visual aid:
![image](https://user-images.githubusercontent.com/20284937/217496896-47a46aa1-3e24-4540-a3cc-880a4eb3d8eb.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new component should be created replicating Search Console `CreateGoalCTA`, named `CreateConversionCTA`.
- Any references to `goal` in this component should be replaced with `conversion`, except for the analytics events (eg. `trackEvent()` calls).
- Wherever the `CreateGoalCTA` component is used, it should be conditionally replaced with the new `CreateConversionCTA` if the `isGA4DashboardView()` selector in the `analytics-4` datastore (being added in #6541) returns `true`.
- The new `Create a new conversion` CTA should take the user to [this support document](https://support.google.com/analytics/answer/12844695).
- When a new GA4 property is created from Site Kit, it also automatically creates a new "purchase" conversion event by default. Based on the conversation [here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit?disco=AAAApFAo4gA), this CTA should still appear even if this event pre-exists for awareness.

## Implementation Brief

* Create a new file at `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/CreateConversionCTA.js`
* Replace any reference to "goal" with "conversion" in the copy.
  * Replace any class names/code as well, but be mindful this might require CSS updates.
* Update https://github.com/google/site-kit-wp/blob/b5b2d4aec8abacfe8bba8d9dd1aa599a03a09933/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview/OptionalCells.js#L96 to render the new `CreateConversionCTA` component when the `isGA4DashboardView()` selector (#6541) returns `true`. Continue to output `CreateGoalCTA` when `isGA4DashboardView()` returns false.
* The "Create a new conversion" CTA button should link to `https://support.google.com/analytics/answer/12844695`.
* The GA events should keep their name (eg. `*_analytics_goal_cta`). See @marrrmarrr's comment: https://github.com/google/site-kit-wp/issues/6551#issuecomment-1479687763

### Test Coverage

* Stories involving the existing Goal CTA should be replicated with the Conversion CTA (see: https://github.com/google/site-kit-wp/blob/b5b2d4aec8abacfe8bba8d9dd1aa599a03a09933/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.stories.js#L256).
* VRTs should be added for these new stories.

## QA Brief

* Without the GA4 Reporting feature flag, test the Search Console Search Funnel Widget with a UA property that has no goals setup. Verify the original Create Goal CTA is still displayed as before.
* Now enable the GA4 Reporting feature flag. Verify that the above old widget is still correctly displayed (when the dashboard view is set to UA).
* Now in Analytics Settings, switch to the GA4 dashboard view. Use a property that has no conversions setup or that has only the default "purchase" conversion event setup (any newly created GA4 property). Go to dashboard and verify the "Create a Conversion" CTA is displayed correctly as per the AC.
* Now change the GA4 property to one that has multiple conversion events setup, such as "The Remote Hive"'s GA4 Property. Verify that the Conversions data block is displayed with the total number of conversions as per the property's conversion count.

## Changelog entry

* Update conditions for showing the "Create Conversion" CTA, and update the support URL it links to.

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by tofumatt** [comment]
@aaemnnosttv I think we should change the events we track here as well, are these new ones fine to use? Do we need to do anything to add these events someplace or is it fine to just add them like this?

**Comment by aaemnnosttv** [comment]
> I think we should change the events we track here as well, are these new ones fine to use? Do we need to do anything to add these events someplace or is it fine to just add them like this?

@tofumatt we should check with @marrrmarrr about these things as I believe she is the one who defines them, although these changes are probably fine.

---

A few thoughts about the AC:

- I realize the existing component belongs to Search Console but why is that? Goals and Conversions are Analytics things.
- **Most importantly: What should the CTA actually do?** The current component links to a support topic about creating goals which doesn't seem to be addressed here or another issue

**Comment by tofumatt** [comment]
@marrrmarrr For the new "Create a new conversion" button in this GA4 "Create Conversions" CTA, we'd like to use the Analytics events `*_analytics_conversion_cta` instead of the old `*_analytics_goal_cta`.

Is that alright or should be stick to the old events (maybe with a property to signify they're the GA4 type)?

**Comment by tofumatt** [comment]
@marrrmarrr Thanks, that's all really helpful! I've bookmarked that events doc as well—I think I've even seen it before but forgot about it. 👍🏻 

I think leaving the widget insight the Search Console folder isn't a big deal, in fact _until it's used elsewhere_ I think it makes sense to leave it there so it's easier to find/make sense of in the project. If we start using that CTA in other places maybe we can move it then.

I've adjusted the ACs/IB to use the existing goals events as well—I think that's what you mean @marrrmarrr, right? That _we would keep the event names but you would update their descriptions to be for Goals going forward_. I didn't see them updated in the document yet but that's what I understood from your message.

ACs here are good then, and the IB looks good too.

IB ✅

**Comment by nfmohit** [comment]
> On a separate note, in my testing, I noticed that if we created a GA4 property via Site Kit, it automatically creates a "purchase" conversion event.
> 
> <img alt="Screenshot 2023-03-27 at 03 10 07" width="1594" src="https://user-images.githubusercontent.com/1721319/227826301-10693aeb-a6ee-4981-b862-eaf9c02f0621.png">
> 
> So this new 'Conversions CTA' will NOT be rendered in this case. However, if I create a GA4 property (and a new Web datastream) using the Analytics Admin, it does not create any conversion events. Will dig into this a bit more but thought I'd flag this.
> 
> c.c @nfmohit

Hi @jimmymadon! We had actually noticed this while writing the design doc and decided to still show the CTA if this default conversion event exists, based on the conversation [here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit?disco=AAAApFAo4gA). Apologies for not adding about this in the ACs!

**Comment by marrrmarrr** [comment]
@jimmymadon what I meant is to extend the relevant section of the list with GA4 events, I've added the [two new ones now](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307&range=A144:B145). 

Regarding the purchase conversion event, that is indeed the only one that is created by GA4 for websites by default -- this is clarified in their [official docs](https://support.google.com/analytics/answer/13128484) (in the green box within the "Instructions" section). Since it's added by default for everyone, it's also likely that it might not be relevant for a bunch of sites that don't actually sell stuff. So IMO it makes sense to show the Conversions CTA in SK even with the default purchase event existing.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

- With a UA property that has no goals setup the original Create Goal CTA is still displayed as before.
- With the GA4 Reporting feature flag enabled the above old widget is still correctly displayed
- With GA4 dashboard view and a property that has no conversions setup the "Create a Conversion" CTA is displayed
- With GA4 property that has multiple conversion events setup the Conversions data block is displayed with the total number of conversions as per the property's conversion count.
- The URLs for goals and conversions point to the correct URLs.
- When a GA4 property is created the CTA still appears even though it has a new "purchase" conversion event by default. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/229159980-a217b33f-5041-4bee-8d56-eb4c559dda3b.png)
![image](https://user-images.githubusercontent.com/73545194/229160021-5a7b76c8-db27-4747-b98c-fd3873684986.png)
![image](https://user-images.githubusercontent.com/73545194/229160059-9bbf7ea4-ab8e-4fff-950a-7d8d287569ef.png)
![image](https://user-images.githubusercontent.com/73545194/229160113-ff27077b-bea6-4e4e-b7e5-d65c36792253.png)

</details>
