### ISSUE TITLE
Investigate/fix E2E WordPress Nightly test failures.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6555]
## Feature Description

The E2E test suite running on WordPress Nightly has started to fail with the following error(s). For example here's a failing [test run](https://github.com/google/site-kit-wp/actions/runs/4120572716/jobs/7115430602).

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/90e72192-de64-4a5a-9f96-c6565732d88d)

It looks like this is due to the recent WordPress core bump to React 18 as seen in this commit: https://github.com/WordPress/wordpress-develop/commit/07fc9b2d7449314ee658d764ce162e99cef6783b

We need to investigate this, fix the test suite if possible, and address any additional implications the React version update may have.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The WordPress Nightly release (or, for a static target, a recent versioned release which uses React 18, e.g. `6.2 Beta 1` looks like a potential candidate at the time of writing) should be checked with Site Kit to ensure both WordPress and Site Kit are still functional with the WP core bump to React 18.
* If anything is broken, this needs to be assessed.
  * If it looks like a straightforward fix it should be fixed via this issue.
  * Additional followup issues should be created if appropriate.
* If things still work as expected, we should suppress the warning for our CI test runs so they can continue to pass.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
👍

**Comment by derweili** [comment]
From what I found out: this issue is related to AMP, not being compatible with React18. Site Kit itself is compatible with the Wordpress Nightly.

**Comment by techanvil** [comment]
That's good to know, @derweili.

Did you check to see if there's a version of AMP which does support React 18?

If not, it should just be a case of adding the error message to `tests/e2e/config/wordpress-debug-log/log-ignore-list.js`.

I haven't tried it but I'm guessing the version key will be `latest`, looking at the value of `WP_VERSION` in `.github/workflows/php-tests-wp-nightly-php-7-4.yml`.

**Comment by derweili** [comment]
The AMP Plugin just got an update [https://github.com/ampproject/amp-wp/releases/tag/2.4.0](https://github.com/ampproject/amp-wp/releases/tag/2.4.0) which fixes the React 18 incompatibility. Our e2e tests do not fail anymore, since the AMP 2.4.0 update.  
So we can close this issue.
