### ISSUE TITLE
[~June 30] Post UA cut-off warning

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6557]
## Feature Description

UA has a hard cut-off date of 30 June 2023. After this date, since UA will stop collecting data, warnings should be added & updated in Site Kit with GA4 not connected notifying users about this cut-off.

- For widgets affected by the UA cut-off, a warning should be added to them according to the [Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=601%3A8936&t=YRXgmjszEqRSRjFP-0). For these warnings, the same component created in #6556 can be re-purposed.
- Copy of warnings added to the Analytics `SettingsView` and `SettingsEdit` (in #6556) should be updated according to the [Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=410%3A6590&t=ckvN59ELFbj9QQWN-0).

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.c6itfdmrt7r3) is the relevant section in the design doc.

Here are screenshots for visual aid:
![image](https://user-images.githubusercontent.com/20284937/217538338-d8d6cc3a-13d4-4d95-a363-edfed7fb274c.png)

![image](https://user-images.githubusercontent.com/20284937/217538366-893e6158-529b-4bfd-9e88-8b4cd2f9ad39.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* An error banner, using `SettingsNotice`, should appear after 30/06/2023 (June 30, 2023), when the user has Universal Analytics connected and does _not_ have GA4 connected:
  * Above a widget area that has at least one widget that displays content from Universal Analytics
  * In Analytics Settings (both the "View" and "Edit")
* The contents of the banner should match the [Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=601%3A8936&t=YRXgmjszEqRSRjFP-0), with a small adjustment to the copy for the Settings version.
   * As discussed [here](https://github.com/google/site-kit-wp/issues/6557#issuecomment-1473778840) the Dashboard copy should include the year 2023, as follows:
     * _Your data is stale because Universal Analytics stopped collecting data on July 1, 2023._
  * Additionally, as discussed [here](https://github.com/google/site-kit-wp/pull/6716#discussion_r1135675946) the Settings copy should read "Your current Universal Analytics property..." rather than "Your current Universal Analytics...".
    * _Your current Universal Analytics property stopped collecting data on July 1, 2023_
  * The design should not reflect the new, updated banner UI. For now, use the `SettingsNotice` component, the new component will be made as part of #6702.
* The "Learn more" link can use `select( CORE_SITE ).getDocumentationLinkURL( 'ga4' )` for now.
* If the user has connected GA4 or does not have Analytics connected at all, these banners should not appear. They should also never appear before June 30.

## Implementation Brief

- In `assets/js/components/SettingsNotice`:
  - Extend the `<SettingsNotice />` component to accept a new prop named `CTA` similar to the existing `LearnMore` prop, that should be rendered to the far right of the notice.
- In `assets/js/modules/analytics/constants.js`:
  - Add a constant for the UA cut-off date, i.e. June 30 2023, say `UA_CUTOFF_DATE`. This can be used across the codebase to refer to the UA cut-off date, so that if in case this is changed (which is very unlikely), we can simply change it in one place.
- In `assets/js/modules/analytics/components/dashboard` folder, create a new file, say `UACutoffWarning.js`. In this file:
  - Export a new component with the same name.
  - The component should render `null` if the following conditions are not met:
    - The `ga4Reporting` feature flag is enabled.
    - The site has Analytics connected but not GA4 (obtainable using the `isModuleConnected( 'analytics-4' )` selector from the `core/modules` store).
    - The current date is after `UA_CUTOFF_DATE` (the current date is obtainable using the `getReferenceDate()` selector from the `core/user` store. See [example](https://github.com/google/site-kit-wp/blob/5fc5b8e85ad32e4616038b527307d2145dabe4fc/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js#L160-L176)).
  - Otherwise, the component should render a `<SettingsNotice />` with the type of `warning`.
  - The contents of the `<SettingsNotice />` should match the copy of the warnings in the Figma designs linked in the ACs.
  - The `Learn more` link should be placed inline with the notice text. It should navigate the user to the GA4 documentation, obtainable using the `getDocumentationLinkURL()` selector from the `core/site` store, passing `ga4` to it.
  - A `Set up Google Analytics 4` CTA should be placed using the new `CTA` prop in `<SettingsNotice />`. Similar to the mockup shown in the issue description, a `<Button danger />` can be used to compose this, clicking on which should mimic a behaviour similar to [this `handleConnectGA4ButtonClick()` function](https://github.com/google/site-kit-wp/blob/5fc5b8e85ad32e4616038b527307d2145dabe4fc/assets/js/components/settings/SettingsActiveModule/Header.js#L146-L163), and navigate the user to the Site Kit Settings screen with the `SettingsEdit` for Analytics opened.
  - Add a Storybook story for this component.
- The above `<UACutoffWarning />` component should be rendered as the first content on any Site Kit Dashboard (both main and entity) widget that sources all or part of its data from the Analytics (UA, not GA4) module, only if UA is connected but GA4 is not. They are:
  - `DashboardAllTrafficWidget`: `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget`
  - `ModulePopularPagesWidget`: `assets/js/modules/analytics/components/module/ModulePopularPagesWidget`
  - `DashboardOverallPageMetricsWidget`: `assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidget.js`
  - `DashboardTopEarningPagesWidget`: `assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js`
  - `SearchFunnelWidget`: `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget`
- In `assets/js/modules/analytics/components/settings`:
  - Since the two `<SettingsNotice />` components added to Analytics module `SettingsForm` and `SettingsView` as a part of #6556 are identical, in the same folder, create a new file, say `SettingsUACutoffWarning.js`. In this file:
    - Export a component with the same name.
    - Return `null` if the following conditions are not met:
      - The `ga4Reporting` feature flag is enabled.
      - The site has Analytics connected but not GA4 (obtainable using the `isModuleConnected( 'analytics-4' )` selector from the `core/modules` store).
    - Otherwise, render the same `<SettingsNotice />` component added in `SettingsForm` or `SettingsView`.
    - If the current date is after `UA_CUTOFF_DATE` (the current date is obtainable using the `getReferenceDate()` selector from the `core/user` store. See [example](https://github.com/google/site-kit-wp/blob/5fc5b8e85ad32e4616038b527307d2145dabe4fc/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js#L160-L176)), update the copy of the `<SettingsNotice />` to say `Your current Universal Analytics property stopped collecting data on July 1, 2023`.
    - Add a Storybook story for this component.
  - Replace the `<SettingsNotice />` components added to Analytics module `SettingsForm` and `SettingsView` as a part of #6556 with the new `<SettingsUACutoffWarning />` component.

### Test Coverage

- Add  test cases for the new `UACutoffWarning` and `SettingsUACutoffWarning` components.
- Fix any failing test.

## QA Brief

* Note, to check this works on the Dashboard, ensure that the [PR](https://github.com/google/site-kit-wp/pull/6731) for #6550 has been merged first.
* Set up Site Kit with Analytics connected but GA4 not connected, and enable the `ga4Reporting` feature flag.
* Navigate to the Main Dashboard and set the current reference date to be on or after July 1st, 2023:
```js
googlesitekit.data.dispatch('core/user').setReferenceDate('2023-07-01')
```
* Verify the warning notice appears as per the AC, in the following widgets:
  * **All traffic**
  * **Search traffic**
  * **Top content**
* Navigate to the Entity Dashboard, set the date, and verify the warning notice appears as per the AC in the following widgets: 
  * **All traffic**
  * **Search traffic**
  * **Overall page metrics**
* Navigate to the Analytics settings page.
* Verify the warning notice appears as per the AC, in both the view and edit modes.
* Set the current reference date to be on or after July 1st, 2023 in both the view and edit modes, and verify the notice copy is correct as per the AC.
* Note that as specced, the designs are not expected to match Figma yet, this will be taken care of via issue https://github.com/google/site-kit-wp/issues/6702.
* Also note that as per the AC, the copy is slightly tweaked from what's in Figma.
* Verify the components display correctly in the following Storybook stories:
  * **Modules > Analytics > Components > UACutoffWarning > Default**
  * **Modules > Analytics > Components > SettingsUACutoffWarning > Default**
  * **Modules > Analytics > Components > SettingsUACutoffWarning > Post UA Cutoff Date**

## Changelog entry

* Add a new post UA cut-off warning.

**Comment by techanvil** [comment]
Hey @nfmohit, this IB will need to be updated in line with the forthcoming AC changes to make this behaviour date-dependent rather than release-dependent.

I also have a couple of additional comments on the IB:

- We should not use the `LearnMore` prop for the `Set up Google Analytics 4` CTA, that sounds a bit hackish. Instead, I'd suggest augmenting `SettingsNotice` so that it either explicitly supports the concept of a CTA, or so it can be extended in a more generic way.
- Seeing as it's used as a part of the spec without going into detail about it, please provide a permalink to the `handleConnectGA4ButtonClick()` mentioned so we can track what this referred to at the time of writing.

**Comment by nfmohit** [comment]
Thank you so much @techanvil for spotting the mistake here. I didn't update the ACs because it didn't mention being dependent on the release anyway, but I have updated the issue title and description to remove the "time-sensitive" type.

I have also updated the IB accordingly and have addressed your feedback as well. Please let me know if it looks good now.

Thank you!

**Comment by techanvil** [comment]
Thanks @nfmohit! The IB LGTM. Please note, I made a small tweak to the AC + IB to reflect the copy tweak as discussed [here](https://github.com/google/site-kit-wp/pull/6716#discussion_r1135675946).

IB :white_check_mark:

**Comment by techanvil** [comment]
Hi @marrrmarrr, I have another minor copy related question. As per the issue description, we have the following copy specced out for the warning notice that will be displayed in widgets on the Dashboard:

> Your data is stale because Universal Analytics stopped collecting data on July 1.

Whereas, on the Settings page it will be:

> Your current Universal Analytics property stopped collecting data on July 1, 2023

My question is, should we add the year 2023 to the Dashboard version so it reads _"Universal Analytics stopped collecting data on July 1, 2023."_? This would be more consistent (and also ensure the notice makes sense if a user were to update at some point in the distant future, although this would probably be a fairly low number of users). What do you think?

**Comment by marrrmarrr** [comment]
@techanvil good point that it would be more consistent that way, makes sense to have the year in both places. Although I definitely hope that there are no users left without Analytics going into 2024...

**Comment by techanvil** [comment]
Thanks @marrrmarrr, I'll update the copy. Yup, certainly hope we don't find any users in that scenario, although you never know... Maybe somebody returns to their Site Kit admin following a year's sabbatical travelling the world :)

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil I've noticed that notice positions under settings is not same as Figma design. Is the current implementation is correct, or we will update position in https://github.com/google/site-kit-wp/issues/6702. ?

<details>

![image](https://user-images.githubusercontent.com/94359491/229046102-93123c53-75c8-4fc7-957d-4b9c14dae1d4.png)

![image](https://user-images.githubusercontent.com/94359491/229046158-8ded0f16-89e7-400f-9eff-738fb75d6f4b.png)

</details>

<details>

**Main Dashboard -**

![image](https://user-images.githubusercontent.com/94359491/229043603-b0c3bd8d-a943-42b7-bc97-d0c14f9f445b.png)

![image](https://user-images.githubusercontent.com/94359491/229043628-5d325c25-5c7e-4660-9b23-fb2937558290.png)

![image](https://user-images.githubusercontent.com/94359491/229043666-4733a13e-6ca3-45ff-8151-7800d1517ad0.png)

**Entity Dashboard**

![image](https://user-images.githubusercontent.com/94359491/229043896-be70655d-a7f5-45e5-a9c2-d2be3031fcc4.png)

![image](https://user-images.githubusercontent.com/94359491/229043930-40a5edec-5d9f-45c4-95ac-c14793244ad3.png)

![image](https://user-images.githubusercontent.com/94359491/229043979-c2e5ec50-e8b9-4a96-b06a-335964d9cd6d.png)


**Settings Edit mode before 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044127-407cde09-2e63-41df-a21d-404cc7f14d9b.png)

**Settings View mode before 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044375-23b9b140-aff0-455e-a92a-e7e9c7cf0927.png)

**Settings View mode after 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044504-f7d6fb2c-c7ac-420d-9da3-8b84d60d6ea9.png)

**Settings Edit mode after 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044584-f489503a-930d-487f-9a53-1b7b43773c1a.png)

</details>

**Comment by techanvil** [comment]
Hi @mohitwp, thanks for spotting this one. It's something that's been missed in a previous issue, or possibly the unintended result of a merge. We don't have an issue to address this, and it's outside of the scope of this one, so please could you create a new issue for this.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @techanvil !

- Tested on dev.
- Verified banner on main dashboard, entity dashboard and settings under both view and edit mode.
- Verified banner and notices as per Figma design and AC.
- For issue reported [above](https://github.com/google/site-kit-wp/issues/6557#issuecomment-1491406397) related to warning notice positions on settings page not same as Figma. I created a separate ticket -https://github.com/google/site-kit-wp/issues/6809

* Verified the components display correctly in the following Storybook stories:
  * **Modules > Analytics > Components > UACutoffWarning > Default**
  * **Modules > Analytics > Components > SettingsUACutoffWarning > Default**
  * **Modules > Analytics > Components > SettingsUACutoffWarning > Post UA Cutoff Date**
  * 


cc @wpdarren 

<details>

**Main Dashboard -**

![image](https://user-images.githubusercontent.com/94359491/229043603-b0c3bd8d-a943-42b7-bc97-d0c14f9f445b.png)

![image](https://user-images.githubusercontent.com/94359491/229043628-5d325c25-5c7e-4660-9b23-fb2937558290.png)

![image](https://user-images.githubusercontent.com/94359491/229043666-4733a13e-6ca3-45ff-8151-7800d1517ad0.png)

**Entity Dashboard**

![image](https://user-images.githubusercontent.com/94359491/229043896-be70655d-a7f5-45e5-a9c2-d2be3031fcc4.png)

![image](https://user-images.githubusercontent.com/94359491/229043930-40a5edec-5d9f-45c4-95ac-c14793244ad3.png)

![image](https://user-images.githubusercontent.com/94359491/229043979-c2e5ec50-e8b9-4a96-b06a-335964d9cd6d.png)


**Settings Edit mode before 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044127-407cde09-2e63-41df-a21d-404cc7f14d9b.png)

**Settings View mode before 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044375-23b9b140-aff0-455e-a92a-e7e9c7cf0927.png)

**Settings View mode after 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044504-f7d6fb2c-c7ac-420d-9da3-8b84d60d6ea9.png)

**Settings Edit mode after 1st July**

![image](https://user-images.githubusercontent.com/94359491/229044584-f489503a-930d-487f-9a53-1b7b43773c1a.png)

</details>
