### ISSUE TITLE
Add the "Switched to GA4" notification banner

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6558]
## Feature Description

A new `BannerNotification` should be created according to the [Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=428%3A6689&t=ckvN59ELFbj9QQWN-0). Site Kit will automatically switch sites having GA4 connected to the GA4 dashboard view after the UA cut-off, and this `BannerNotification` should notify them about this switch.

This `BannerNotification` should only be rendered to sites having GA4 connected and if the `dashboardView` Analytics module setting (being added in #6540) is still UA, because at this point, these are the sites that hadn't manually switched over.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.qqgy3yr92hiw) is the relevant section in the design doc.

Here is a screenshot for visual aid:
![image](https://user-images.githubusercontent.com/20284937/217543128-c6340e31-6111-4ad2-ac1d-8585fb8dd3e4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new banner notification should be created following [this Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=428%3A6689&t=ckvN59ELFbj9QQWN-0):

**Title**
> Your dashboard now displays data from Google Analytics 4, the new version of Analytics

**Body**
- Before July 1, 2023:
> Universal Analytics, the old version of Google Analytics, will stop collecting data on July 1, 2023.
- On/after July 1, 2023:
> Universal Analytics, the old version of Google Analytics, stopped collecting data on July 1, 2023.

**Learn what's new**

* Clicking the "Learn what's new" button (primary CTA) should activate the GA4 reporting feature tour (added in #6554).
* Clicking the "No, thanks" button (secondary/dismiss CTA) should dismiss the notification permanently. It should also dismiss the feature tour.

_(Note: it might be better to label the "No, thanks" as "Dismiss" or "OK, Got it!", because "No, thanks" reads like it might be a button that reverts the automatic change to GA4 reports.)_

* The notification should only be shown a user under the following conditions:
  * Both Analytics and Analytics 4 are connected.
  * The `isGA4DashboardView()` selector returns `true`.
  * They have not yet dismissed the GA4 reporting feature tour.
  * They have not just enabled the GA4 dashboard via the ["Update dashboard" CTA](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=826-7063&t=wsvpNXFVSYAO2IDc-4), which itself will [trigger the feature tour](https://github.com/google/site-kit-wp/issues/6914).
  * They have not just enabled the GA4 dashboard via the Settings page.
* The notification should be made visible to users (i.e. added to `BannerNotifications`).
  * The banner should follow the `ModuleRecoveryAlert` banner in terms of priority.

## Implementation Brief

- Create `/assets/js/components/notifications/SwitchedToGA4Banner.js`. This file should export a functional component named `SwitchedToGA4Banner`. This component should: 
  - Render `null` if any of the following conditions are not met:
    - Both `analytics` and `analytics-4` are connected (can be checked using the `core/modules` `isModuleConnected` selector).
    - `modules/analytics` `isGA4DashboardView` selector returns `true`.
    - The `ga4Reporting` feature tour isn't dismissed (can be checked using the `core/user` `isTourDismissed` selector).
    - The value of the `showGA4ReportingTour` key in the `core/ui` store is falsey/undefined (obtainable using the `core/ui` `getValue` selector).
  - Otherwise, render a `<BannerNotification />` component with the following props:
    - `id`: `switched-ga4-dashboard-view`
    - `title`: According to the ACs.
    - `description`: According to the ACs, the description should be different before and after the `UA_CUTOFF_DATE` constant. The `UA_CUTOFF_DATE` constant should be compared to the current reference date (obtainable using the `core/user` `getReferenceDate` selector).
    - `ctaLink`: `#`
    - `ctaLabel`: `Learn what's new` (translatable)
    - `onCTAClick`: A function that should do the following:
      - Dispatch the `core/ui` `setValue` action for the `forceInView` key with the value of `true`.
      - Dispatch the `core/ui` `setValue` action for the `showGA4ReportingTour` key with the value of `true`.
    - `dismiss`: `OK, Got it!` (translatable).
    - `WinImageSVG`: A function that returns the `assets/svg/graphics/ga4-success-green.svg` SVG as a component.
- In `assets/js/components/notifications/BannerNotifications.js`:
  - Render the new `<SwitchedToGA4Banner />` component right after `<ModuleRecoveryAlert />` is rendered, if the `ga4Reporting` feature flag is enabled.
- In `assets/js/modules/analytics/datastore/settings.js`, within `submitChanges()`:
  - At the point where the settings are being saved, if the `dashboardView` setting is `DASHBOARD_VIEW_GA4`, call `dismissTour( 'ga4Reporting' )` to dismiss the GA4 feature tour.
    - Only dismiss the tour if it's not already dismissed to avoid unnecessary API calls. Use `isTourDismissed()` to check if the tour has been dismissed.
  - As the Analytics `submitChanges()` action is dispatched during setup and on the settings page, this will ensure the banner & tour will not be shown when changing the setting on the Settings page as per the AC for this issue, and also won't be shown when the user has just setup the plugin, which will avoid a regression for https://github.com/google/site-kit-wp/issues/6914.

### Storybook

- Add a Storybook story for the `SwitchedToGA4Banner` banner notification, with variants for before and after the UA cut-off date.

### Test Coverage

- Add VRT scenarios for the `SwitchedToGA4Banner` banner notification.
- Add/update the tests for the Analytics `submitChanges()` action to cover these changes.

## QA Brief

* Set up a new site and connect both Analytics and Analytics-4 modules.
* Go to the settings and switch the settings to GA4 dashboard view.
* Log in as the second admin and go to the dashboard page
* Verify that you see the banner with the correct description.
* Change the reference date to something in the future, for example to any date in the next year.
* Go back to the dashboard and verify that the banner description has changed.
* Click on the CTA button and ensure that the feature tour has started.

### QA Update:

- For the followup PR, ensure the feature tour does not crash when navigating to the second step, as per https://github.com/google/site-kit-wp/issues/6558#issuecomment-1546065472.

## Changelog entry

* Add the "Switched to GA4" notification banner to inform users that the dashboard has been switched to the GA4 view.

**Comment by techanvil** [comment]
Have moved this back to AC to determine whether to develop this behind a feature flag instead of trying to target a specific release.

**Comment by techanvil** [comment]
Have moved this back to AC to determine whether to develop this behind a feature flag instead of trying to target a specific release.

**Comment by techanvil** [comment]
Have moved this back to AC to determine whether to develop this behind a feature flag instead of trying to target a specific release.

**Comment by nfmohit** [comment]
Thank you for spotting this, @techanvil!

I have made slight changes to the ACs, notably mentioning that this issue is only about "creating" the Banner Notification, but it will actually be made visible in #6549. Hence this isn't a "time-sensitive" issue anymore, and can be worked on async. I have updated the dependencies accordingly. Over to ACR.

CC: @tofumatt

**Comment by tofumatt** [comment]
ACs here look good, moving back to IB. Thanks @techanvil and @nfmohit! 👍🏻

**Comment by bethanylang** [comment]
@sashadoes It looks like this doesn't have an estimate – can you please add?

**Comment by techanvil** [comment]
Thanks for the IB @sashadoes - looks good, I have made a couple of small tweaks to it.

I notice you added the estimate but not the `Exp: SP` label. Could you please add the label, amending the estimate if necessary?

**Comment by techanvil** [comment]
Thanks @sashadoes!

IB :white_check_mark:

**Comment by nfmohit** [comment]
> * To ensure the banner is only shown as per the AC:
>   
>   * Use `isModuleActive` to check if GA4 and GA modules are connected
>   * Use the `getDashboardView()` selector and compare to the `DASHBOARD_VIEW_UA` constant introduced in [Add `dashboardView` toggle in Analytics settings. #6723](https://github.com/google/site-kit-wp/pull/6723) to check if the dashboard view is still set to `'universal-analytics'`.
>   * Return `null` if the above conditions are not met.

Hi @sashadoes! I think we should use the `isModuleConnected()` selector instead of `isModuleActive()` to see if the modules are connected. Let me know what you think. Thanks!

CC: @techanvil

**Comment by techanvil** [comment]
Moving this back to AC to continue the discussion from https://github.com/google/site-kit-wp/issues/6914#issuecomment-1525185133.

**Comment by techanvil** [comment]
Hi @marrrmarrr @aaemnnosttv, I've gone ahead and updated the AC based on the discussion we were having on #6914.

I've updated it to specify the date-related copy, the requirement to dismiss the feature tour upon dismissing the banner, the updated requirements for showing the banner, and the requirement to actually render the banner rather than waiting for #6549 for this.

Please take a look and see what you think.

**Comment by marrrmarrr** [comment]
Thanks @techanvil, the ACs look pretty comprehensive! 
The only clarification I had is what "the banner should be displayed just below the ModuleRecoveryAlert banner" means -- will they be stacked on top of each other?

**Comment by techanvil** [comment]
Thanks @marrrmarrr - I realise the term "displayed" was a bit unclear in the point you've highlighted, and have changed it to "prioritized". These banners should not be stacked on top of one another, rather the usual notification banner behaviour of a single banner being displayed at a time should be in effect.

**Comment by marrrmarrr** [comment]
@techanvil thanks for clarifying, we've had a bunch of occurrences recently where banners showed up simultaneously stacked on the dashboard, so I thought I'd double check to be sure. 
Moved this to IB.

**Comment by eugene-manuilov** [comment]
> * Render `null` if any of the following conditions are not met

@nfmohit, an additional condition that we should check here is the value of the dashboardView setting. If it doesn't equal `universal-analytics`, we also need to return `null` because it means that the site owner switched the dashboard to GA4 manually.

**Comment by techanvil** [comment]
> > * Render `null` if any of the following conditions are not met
> 
> @nfmohit, an additional condition that we should check here is the value of the dashboardView setting. If it doesn't equal `universal-analytics`, we also need to return `null` because it means that the site owner switched the dashboard to GA4 manually.

Hi @eugene-manuilov, this is not actually correct - the previous version of the AC/IB did require and include this, but this banner has now been adjusted to accommodate the scenario where the GA4 dashboard view has been manually switched to by one admin, and a second admin is viewing the dashboard, in which case they should also be alerted to the fact the view has been changed and should be shown this banner and be able to click the CTA to see the feature tour. This was initially discussed on #6914 with a first mention here: https://github.com/google/site-kit-wp/issues/6914#issuecomment-1520780915.

However, you have highlighted a gap in the requirements which is that when an admin switched to the GA4 dashboard view, they should not then be shown this banner. Seeing as we're using the feature tour dismissal state in order to show the banner, I think we should manage this by also dismissing the tour for a user when they toggle the dashboard view via the Settings page.

I've added this to the AC. @nfmohit, please can you update the IB to accommodate this point?

**Comment by eugene-manuilov** [comment]
> I've added this to the AC, and as nfmohit is at Summit this week, I've also updated the IB.

Thanks, @techanvil. Looks like this is going to work. 👍 



> * At the point where the settings are being saved, if the `dashboardView` setting is `DASHBOARD_VIEW_GA4`, call `dismissTour( 'ga4Reporting' )` to dismiss the GA4 feature tour.

Let's probably make it clear that we should dismiss the tour only if it hasn't been dismissed yet to avoid sending unnecessary API requests every time we submit setting changes and the tour is already dismissed.

**Comment by techanvil** [comment]
Thanks @eugene-manuilov, I did wonder about including that, and agree it makes sense to be more explicit. I've added an additional point to the IB about this.

**Comment by eugene-manuilov** [comment]
Thanks, Tom. IB ✔️

**Comment by nfmohit** [comment]
Hi @aaemnnosttv!

Just a quick UX question on this one, do you think we should only show this banner notification to sites which have both UA and GA4 connected?

I ask because sites that will set up Analytics with only GA4 going forward will have the GA4 dashboard view by default, and showing this banner notification may confuse them.

What do you think?

Thanks!

CC: @techanvil @eugene-manuilov

**Comment by aaemnnosttv** [comment]
@nfmohit yes, that makes sense. The banner is about informing the user that the source used for GA reporting has changed but of course nothing would have changed if the user only set up GA4 to begin with 👍

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@eugene-manuilov I found below differences between Figma and actual implementation. 

- In Figma title font color is #131418 and implemented color is #161B18.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/d10e20b3-26ab-4d89-95e9-28db04b9680e)

![image](https://github.com/google/site-kit-wp/assets/94359491/5bb06ffb-b0cf-4199-bac8-12d1d7229c5f)

</details>


- 'Ok,Got it !' button color in Figma is #6C726E.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/bf76cb8c-fe43-42d7-a5d0-f6180e32d31d)

</details>

**Comment by eugene-manuilov** [comment]
Thanks, @mohitwp. I used the standard notification banner that we use for all notifications in the plugin. So, colours are correct there. I am not sure that we should make adjustments in styles just for this specific banner since the difference isn't visible if we don't check actual colour codes. I think that's okay.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Compared notification banner with Figma design.
- Verified copy of banner for Before July 1, 2023.
- Verified copy of banner On/after July 1, 2023.
- Verified Clicking the "Learn what's new" button (primary CTA) activate the GA4 reporting feature tour (added in https://github.com/google/site-kit-wp/issues/6554).
- Verified Clicking the "Ok,Got it !" button  should dismiss the notification permanently. 
- The notification only be shown a user under the following conditions:

  - Both Analytics and Analytics 4 are connected.
 - The isGA4DashboardView() selector returns true.
 - They have not yet dismissed the GA4 reporting feature tour.
 - They have not just enabled the GA4 dashboard via the ["Update dashboard" CTA] 
 -  (https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=826-7063&t=wsvpNXFVSYAO2IDc-4), 
 -   which itself will https://github.com/google/site-kit-wp/issues/6914.
 - They have not just enabled the GA4 dashboard via the Settings page.

- The banner follows the ModuleRecoveryAlert banner in terms of priority.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/72be9ac0-1496-4419-896c-8433da9e5de2)

 ![image](https://github.com/google/site-kit-wp/assets/94359491/5bb06ffb-b0cf-4199-bac8-12d1d7229c5f)

</details>

**Comment by aaemnnosttv** [comment]
## ❌ Approval

As noted on #7031, there is an issue here where the GA4 tour will crash when navigating to the second step because the target does not exist if the cache is cold and the user hasn't scrolled down yet. It seems to be a simple fix by applying the `forceInView` that we have on the same tour when invoked from the other banner. I'll open a quick PR to address it.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@aaemnnosttv @nfmohit 

- Tested on dev environment. 
- Now, ga4 feature tour trigger after few seconds delay if second step target is not loaded. So, we wait till target loads and then trigger the feature tour. This works fine for the Admin 2 sign in with Google a/c have access to analytics or Analytics is shared by Dashboard sharing. 

_**Question** – If Admin 2 sign in with the Google a/c which don't have access to analytics. Then clicking on 'Learn what'new' button just dismissed the banner and feature tour don't get trigger in this case because both targets are not loaded due to insufficient permission error. I'm wondering should we show banner in this case or not ?_



https://github.com/google/site-kit-wp/assets/94359491/c386ac24-6ea0-460e-898e-d6066dcbc64e

<details>

When admin 2 sign in with Google a/c which have access to analytics and user wait till feature tour trigger.


https://github.com/google/site-kit-wp/assets/94359491/791fa6ff-d02d-4f7b-b745-1434d29abcb7


When admin 2 sign in with Google a/c which have access to analytics and user do some activity till the feature tour trigger.


https://github.com/google/site-kit-wp/assets/94359491/0a66b155-53be-4013-a266-9b3f35a1b834


When admin 2 sign in with Google a/c which don't have access to analytics, but analytics is shared by Dashboard sharing.

https://github.com/google/site-kit-wp/assets/94359491/5f9c44ac-29cc-446f-8de8-b902857cd514

</details>

**Comment by mohitwp** [comment]
Thank you @aaemnnosttv !

### QA Update ✅ 

- Tested on dev environment.

- Verified Now, ga4 feature tour trigger after few seconds delay if second step target is not loaded. So, we wait till target loads and then trigger the feature tour. This works fine for the Admin 2 sign in with Google a/c have access to analytics or Analytics is shared by Dashboard sharing.

-  Verified that the feature tour does not crash when navigating to the second step.

- For the concern raised as a question [above](https://github.com/google/site-kit-wp/issues/6558#issuecomment-1547906048) . Evan created a separate ticket #7044. 

- Verified for scenario when admin 2 sign in with Google a/c which have access to analytics and user wait till feature tour trigger.

- Verified for scenario when admin 2 sign in with Google a/c which have access to analytics and user do some activity till the feature tour trigger.

- Verified for scenario when admin 2 sign in with Google a/c which don't have access to analytics, but analytics is shared by Dashboard sharing.


<details>

When admin 2 sign in with Google a/c which have access to analytics and user wait till feature tour trigger.


https://github.com/google/site-kit-wp/assets/94359491/791fa6ff-d02d-4f7b-b745-1434d29abcb7


When admin 2 sign in with Google a/c which have access to analytics and user do some activity till the feature tour trigger.


https://github.com/google/site-kit-wp/assets/94359491/0a66b155-53be-4013-a266-9b3f35a1b834


When admin 2 sign in with Google a/c which don't have access to analytics, but analytics is shared by Dashboard sharing.

https://github.com/google/site-kit-wp/assets/94359491/5f9c44ac-29cc-446f-8de8-b902857cd514

</details>

**Comment by marrrmarrr** [comment]
@aaemnnosttv I think it's ok to close this one since the original goal is met, but let's create a new issue for the corner case mentioned by @mohitwp for Admin2.
Separately, on the video it looks like the highlighted areas for the tooltips are not completely matching the headings of the metrics - IIRC we have a separate issue to address this, right?

**Comment by aaemnnosttv** [comment]
> let's create a new issue for the corner case mentioned by @mohitwp for Admin2

@marrrmarrr This should be addressed by https://github.com/google/site-kit-wp/issues/7044

> Separately, on the video it looks like the highlighted areas for the tooltips are not completely matching the headings of the metrics - IIRC we have a separate issue to address this, right?

I'm not sure, I'll take a look and we'll create one if needed 👍

**Comment by aaemnnosttv** [comment]
Great, thank you @nfmohit 👍 

@marrrmarrr this has already been merged and will be included in the 1.102 release.
