### ISSUE TITLE
Add support for Site Kit Service's playground environment

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6561]
Site Kit supports overriding the Site Kit Service base URL to use via the `GOOGLESITEKIT_PROXY_URL` (only used for internal debugging and testing). However that constant only works with an allowlist of URLs. Since Site Kit Service now has a new "playground" environment called `site-kit-local`, we will need to add support for it as well, in addition to the existing staging environment called `site-kit-dev`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It should be possible to use the value `https://site-kit-local.appspot.com` in the `GOOGLESITEKIT_PROXY_URL` constant.

## Implementation Brief

* Add new `DEVELOPMENT_BASE_URL` constant to `Google_Proxy` class with the URL from the ACs.
* Modify `Google_Proxy::url()` to also allow that value when provided in the `GOOGLESITEKIT_PROXY_URL` constant.

### Test Coverage

* N/A

## QA Brief

* With Site Kit currently not being set up (e.g. after a reset), set the constant `GOOGLESITEKIT_PROXY_URL` to `https://site-kit-local.appspot.com`, e.g. in your `wp-config.php`.
* Verify that when starting the setup flow, you land on a URL that starts with `https://site-kit-local.appspot.com`.
    * It is not necessary for QA of this issue to complete the setup flow. There is a chance that that environment is not fully working yet, which is okay for the scope of this issue.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by mohitwp** [comment]
@eugene-manuilov 

I define constant in WP config file and tried to set up but still set up flow not starting with URL that starts with https://site-kit-local.appspot.com . Let me know if I didn't set up constant correctly in WP config file.

<details>

![image](https://user-images.githubusercontent.com/94359491/220358369-334433d1-9d46-40a4-9038-0f4f10484f7c.png)

![image](https://user-images.githubusercontent.com/94359491/220358496-8db2c03d-cbce-4195-ac51-7e45a804ab9e.png)

</details>

**Comment by eugene-manuilov** [comment]
@mohitwp, you need to remove the trailing slash, it should be exactly like this:

```php
define( 'GOOGLESITEKIT_PROXY_URL', 'https://site-kit-local.appspot.com' );
```

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- It is now possible to use the value https://site-kit-local.appspot.com in the GOOGLESITEKIT_PROXY_URL constant.
- I define constant in WP config file and when tried to set up then set up flow not starting with URL that starts with https://site-kit-local.appspot.com/ .
- Analytics is not getting connect due to insufficient permission. 

<details>


https://user-images.githubusercontent.com/94359491/220532628-f6154e1e-38ee-43da-b843-d1ecb7663be4.mp4


</details>
