### ISSUE TITLE
Deploy plugin builds to cloud storage

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6563]
## Feature Description

Site Kit currently builds dev and production zip file artifacts for multiple branches as well as every open PR on the repo which are used internally for testing. Due to limitations around where these files can be stored where they can have a predictable URL, as well as be publicly accessible along with other organizational constraints, these have been deployed to the repo's wiki for a long time. This has always been less than ideal, particularly because the wiki itself is a git repo, which overly complicates the deployment process. More recently, the sheer size of this repository has become increasingly problematic, adding minutes to deployment jobs for these files.

Moving forward, we'll leverage Google Cloud Storage for these files which will be much faster and scalable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GitHub Actions workflow for building and deployment of plugin zip files should be enhanced as follows
	* Zip files for production and development builds should deploy built zip files to the `site-kit-github-artifacts` Google Cloud storage bucket
	* The files should be uploaded to `/builds/{github.ref}/` (e.g. `/builds/refs/heads/develop` or `/builds/refs/pull/123/merge`)
	* Plugin zip files should no longer be deployed to the Site Kit wiki repo
* A nice to have would be automating a comment on respective PRs when the files have been deployed ([example](https://github.com/ampproject/amp-wp/blob/688fc8d39069195856735a7512c699ffe4a1b705/.github/workflows/build-test-measure.yml#L894)) 

Note: Credentials will be available via a secret named `GCP_CREDENTIALS` which contains the entire service account credentials as a JSON blob. See the [docs](https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment#service-account-key-json) for details. 

## Implementation Brief

**Note: This task requires a user with access to create GCP credentials as outlined the "auth" step below, so should likely be handled by @aaemnnosttv, or @aaemnnosttv should add the secret credentials data to the GitHub Secrets for the repo before execution begins.**

* All following changes happen in the `zips.yml` workflow file.
* Create a new `BUCKET_NAME` `env` in the workflow file. (see [docs](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow))
  * Set the value to the bucket name, according to AC.
  * Set this `env` on workflow level (on top level of the yml file), so multiple all jobs can access it.
* Rename the `deploy-to-wiki` job to `deploy-to-cloud-storage`. Also rename the job name.
* In the `deploy-to-cloud-storage` job, replace the `Commit updates` step with the following changes.
  * Create a new `auth` step
    * Copy over the configuration for the auth step from [these docs](https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment#service-account-key-json) 
      * Ensure the GCP credentials used have the minimal required permissions to create/read/update/delete data in Cloud Storage, but no more permissions.
  * Create a new `Upload to cloud storage` step.
    * Use the `'google-github-actions/upload-cloud-storage@v1'` action to upload to Google Cloud Storage
    * See "uploading folders" [docs](https://github.com/google-github-actions/upload-cloud-storage#for-uploading-a-folder)
    * Use `${{ github.ref }}` as path
    * Use `'${{env.BUCKET_NAME}}/builds'` as destination  

* In the `remove-pr` job, replace the `Prune PR files` step with the following steps:
  * Again add an `auth` step with the same configuration as before.
  * Add a `Set up Cloud SDK` step that uses the `'google-github-actions/setup-gcloud@v1'` action. (see [here](https://github.com/google-github-actions/setup-gcloud))
  * Add a `Prune PR files` files step which uses the `gsutil rm` command to delete the PR files.
    * `gsutil rm gs://${{env.BUCKET_NAME}}/builds/${{ github.event.pull_request.number }}/`
* Create a new `comment-on-pr` job, which adds a comment to the PR after the build is pushed to the cloud storage
  * Use the action used by the AMP plugin as a template. https://github.com/ampproject/amp-wp/blob/688fc8d39069195856735a7512c699ffe4a1b705/.github/workflows/build-test-measure.yml#L894-L938
  * The job should only run on "ready-to-review" PRs.
  * The job should have the `deploy-to-cloud-storage` job as a dependency.
  * The comment add should link to the correct files 
     - `Download [development build](https://storage.googleapis.com/${env.BUCKET_NAME}/builds/${{ github.ref }}/google-site-kit-dev.zip)`
     - `Download [production build](https://storage.googleapis.com/${env.BUCKET_NAME}/builds/${{ github.ref }}/google-site-kit.zip)"`

### Test Coverage

* As this is an infrastructure task, no tests need to be added.
* Verify it the changes as follows:
  * Create a PR (with the new workflow changes)
  * Verify the files get pushed to the storage
  * Close the PR
  * Verify the files get deleted from the storage.

## QA Brief

* Ensure plugin zips are deployed to GCS and updated for PRs created after this is merged.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv ACs LGTM!

**Comment by tofumatt** [comment]
I noticed an instance here where it requested dependence on `deploy-to-wiki` which I updated to `deploy-to-cloud-storage`. Also I added a note about permissions for the GCP credentials.

Part of the IB here should probably note that this task needs to be done by someone with access to the GCP credentials we need to supply—I'd suspect that's most straightforwardly @aaemnnosttv. Because he'll need to add our GCP credentials.

Aside from that it looks good, so I've called that out and move it to EB.

IB ✅

**Comment by derweili** [comment]
@tofumatt the AC mentioned
> Credentials will be available via a secret named GCP_CREDENTIALS which contains the entire service account credentials as a JSON blob. 
I understood that to be the case already.

If not, @aaemnnosttv needs to add the secret first. If the secrets are already added, anyone could work on this.

**Comment by aaemnnosttv** [comment]
@derweili please assign this to me for review when ready as this will need to be coordinated with an update to the tester plugin at the same time 👍

**Comment by derweili** [comment]
Unassigning myself as I have too less hours on Sitekit to work on this,[ see slack](https://10up.slack.com/archives/CBKKQEBR9/p1682516973710199?thread_ts=1682507604.246489&cid=CBKKQEBR9).

**Comment by eugene-manuilov** [comment]
Looks like we won't be able to use the json credentials approach since creation of service account keys are prohibited. What we need to use is the Workflow Identity Federation that should be connected to an OpenID Connect provider to automatically authenticate our workflow steps.

Here is a good article that explains how it should be done: https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions

@aaemnnosttv or @felixarntz, can one of you create required workflow identity pool, service account and bucket on gcp that we can use to test the new changes in the new github action workflow for zip files? Once created, can you add two secrets to this repo: `WORKLOAD_IDENTITY_PROVIDER` and `SERVICE_ACCOUNT`? They should contain corresponding values as shown in the GHA snippet in the article?

**Comment by eugene-manuilov** [comment]
Ah... okay, I tried to create one service account for the development environment to test the deployment workflow and got an error that keys are disabled. Maybe we should use workflow identity pools anyway, since it seems to be a better approach?

Anyway, @felixarntz, can you create one for the development environment that I can use for testing for now?

**Comment by aaemnnosttv** [comment]
> Anyway, @felixarntz, can you create one for the development environment that I can use for testing for now?

@eugene-manuilov I'm guessing probably not since the process for requesting these is not quick. We can however create a new bucket for testing and grant access to the service account to test this. The "production" bucket isn't being used for anything else though currently so we could also simply use that for testing and we can always delete anything that shouldn't be there afterwards. Some files have already been uploaded there from your PR.

Also, did you see Julian had started a PR here in https://github.com/google/site-kit-wp/pull/6893?

**Comment by eugene-manuilov** [comment]
Thanks, @aaemnnosttv. Felix gave me the access to the project and I can test it now.

> Also, did you see Julian had started a PR here in #6893?

No, I didn't notice it.

**Comment by tofumatt** [comment]
QA ✅ 

Google Cloud Storage is now being used for plugin builds as seen in actions/PRs/workflows 👍🏻
