### ISSUE TITLE
Update use of buttons with spinners for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6571]
## Feature Description

We currently have two different implementations of a button with a spinner:

- A button and separate external spinner (using the spinner graphic provided in WP core)
- A button with an internal spinner, using a material circular progress animation

The latter should be used on plugin screens going forward.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instances of a button with a spinner which is displayed while its respective action is in progress should be updated to use the button with the internal material circular progress spinner

## Implementation Brief
* Refactor usage of the `Spinner` component within the `Button` component to use the `SpinnerButton` component instead, which accepts the same props as `Button`.
    * No `Spinner` within `Button` should be used or `Spinner` next to the `Button` element.
* Non exhaustive list of components to be updated:
    * `assets/js/components/dashboard-sharing/DashboardSharingDialog/Footer/index.js`
        * Update the reset button to use `SpinnerButton` and remove usage of `Spinner`.
    * `assets/js/components/notifications/BannerNotification/index.js`
        * Replace `Button` having the class name `googlesitekit-notification__cta` by `SpinnerButton` and remove usage of `Spinner` component.
    * `assets/js/components/settings/SettingsActiveModule/Footer.js`
        * Replace both `Button` by `SpinnerButton`
    * `assets/js/googlesitekit/components-gm2/Dialog.js`
    * `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js`
* For above components review any CSS which were added to position the spinner next to the button when the `Button` and `Spinner` components were side by side or `Spinner` as a child of `Button`.

### Test Coverage
* Tests might need to be updated to cater for above changes.

## QA Brief

* Check and make sure the button with spinner works as expected in the following places:
    * DashboardSharing Settings
    * Module Recovery Alert
    * Module Settings     
    * Notifications 
    * Error Notifications 
    * etc. 

## Changelog entry

* Update all spinner buttons to be consistent across the codebase.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
@mohitwp hope you don't mind but I have assigned you to this ticket so I can focus on the GTE Support test plan/bug bash instructions.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main.

- Tested dashboard sharing modal, settings module. Reset button, GA4 set up activation banner.

- All instances of a button with a spinner which is displayed while its respective action is in progress are updated to use the button with the internal material circular progress spinner.


<details>


https://user-images.githubusercontent.com/94359491/223694533-45039b9f-e066-4c09-a6f6-963df1584979.mp4

</details>
