### ISSUE TITLE
Add survey for GA4 dashboard view

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6574]
## Feature Description

Users using the GA4 dashboard view on their sites should be offered a survey to track the usage of the new GA4 dashboard view, and receive valuable insights and feedback accordingly.

The survey trigger infrastructure is being enhanced in [#6306](https://github.com/google/site-kit-wp/issues/6306).

The trigger ID for this survey can be `view_ga4_dashboard` and it should show up on sites using the GA4 dashboard view.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A survey with the ID `'view_ga4_dashboard'` should be triggered on the main Site Kit Dashboard when GA4 is connected and `isGA4DashboardView()` returns `true`.

## Implementation Brief

(It is probably useful to wait until #6306 is in Approval before writing an IB for this issue, as it would depend on the implementation of #6306.)

* Once the PR for #6306 has been merged, 
    * In `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/index.js`:
        *  render `SurveyViewTrigger` under the `Grid` component with the following props:
            * `triggerID` = `view_ga4_dashboard`
            * `ttl` = `DAY_IN_SECONDS`
        * If `DashboardAllTrafficWidgetGA4` is being rendered, it means GA4 is connected and `isGA4DashboardView` is true as pointed out by @eugene-manuilov [here](https://github.com/google/site-kit-wp/issues/6574#issuecomment-1476065064), so we can unconditionally render the aforementioned `SurveyViewTrigger` here without any checks. 

### Test Coverage

* No new tests are needed, update any failing tests. 

## QA Brief

* Set up a new site, connect the plugin and enable the `ga4reporting` feature flag.
* Go to the site-kit dashboard page and ensure that you see a request to the `/wp-json/google-site-kit/v1/core/user/data/survey-trigger?_locale=user` endpoint that has `{"data":{"triggerID":"view_ga4_dashboard"}}` in payload.

## Changelog entry

* Add trigger for a survey to track the usage of the new GA4 dashboard view.

**Comment by eugene-manuilov** [comment]
> In `assets/js/components/DashboardMainApp.js`:
> * Check whether `ga4reporting` is enabled using `useFeature` hook.
> * Find out whether the current dashboard is GA4 dashboard using `isGA4DashboardView` selector from `ANALYTICS` module.

@kuasha420, I am not sure if it is the right place to trigger that survey. How about we add the `SurveyViewTrigger` component to the `DashboardAllTrafficWidgetGA4` component? In this case, we will not pollute the global component with module specific logic and we won't need to check anything because if that widget is rendered, then both `ga4reporting` and `isGA4DashboardView` are true.

**Comment by kuasha420** [comment]
@eugene-manuilov that's brilliant, I have updated the IB accordingly. Cheers.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ 

@eugene-manuilov just to check.  The QAB says:

> ... endpoint that has {"data":{"triggerID":"view_ga4_dashboard"}} in payload.

I see a request to the `/wp-json/google-site-kit/v1/core/user/data/survey-trigger?_locale=user` with an endpoint `{data: {triggerID: "view_ga4_dashboard"}}` The `data` and `triggerID` do not have " " characters around them.

Is that expected?

![image](https://user-images.githubusercontent.com/73545194/226641873-c36791b0-e8fe-4912-a9e3-b8df392e8fe5.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

A request to the `/wp-json/google-site-kit/v1/core/user/data/survey-trigger?_locale=user` endpoint  has {"data":{"triggerID":"view_ga4_dashboard"}} in payload when on the dashboard. 

![image](https://user-images.githubusercontent.com/73545194/226890746-45f87699-0611-453e-8074-a84297d48956.png)

**Comment by aaemnnosttv** [comment]
## ⚠️ Approval

This is resulting in a duplicate trigger request being made. It doesn't impact the release so we can address this detail in a follow-up issue, but the rest is working as expected. I'll open a new issue for this.
