### ISSUE TITLE
Upgrade Storybook storyshots

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6578]
## Feature Description

Resolves
- https://github.com/google/site-kit-wp/security/dependabot/70
- https://github.com/google/site-kit-wp/security/dependabot/19

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `@storybook/addon-storyshots` should be upgraded to the latest version

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/6580

### Test Coverage

* No changes

## QA Brief

* This issue only involves upgrades to Storybook related dependencies, so as long as existing tests are passing no further QA is needed here. This can be verified at the time of CR.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Giving this a 1 since there doesn't seem to be anything left to do here.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
(Moving directly to Approval as no QA is needed here.)
