### ISSUE TITLE
Potential error in Search Funnel when GA is in a gathering state

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6587]
## Bug Description

The Search Funnel widget includes stats from Search Console and Analytics. When Search Console is in a gathering data state, all of the 4 stats in the Search Funnel widget are showing to be in a gathering state. When Search Console is in a non-gathering state, if GA is in a gathering state, its "Unique Visitors from Search" metric will show as zero, with an empty chart rather than the respective gathering state which shouldn't be selectable. The empty chart shows a chart error with a "Table has no columns." error.

From this state, selecting a different metric within the Search Funnel will trigger a fatal React error that crashes the dashboard. It's not clear why this is not caught within the `GoogleChartErrorHandler` and instead reaches the root error boundary. 

<details>
<summary>Error contents</summary>

```
Cannot read properties of null (reading '__eventTarget')

    in GoogleChart
    in div
    in Cell
    in div
    in Row
    in div
    in Grid
    in AnalyticsStats
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in SearchFunnelWidget
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in Grid
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root
```

</details>

## Steps to reproduce

1. Set up SK with a site that has a **non-gathering** state for Search Console (the tester plugin set to force a "zero" state will also work)
2. Connect Analytics and put it into a **gathering** state (either by creating a fresh property or using the tester plugin)
3. On the dashboard, select the `Unique Visitors from Search` metric – see "Table has no columns." error in chart
4. Select another metric in Search Funnel (e.g. Total Impressions or Total Clicks)
5. See error

## Screenshots

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/1621608/218594187-4e28dd18-8034-4e49-85a2-98aa21ea0946.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1621608/218594205-9e46805e-6859-4306-97df-75f76ba39a6e.png">

## Additional Context

 - Plugin Version: 1.94.0
 - After some additional testing, I found this bug was introduced with the `zeroDataStates` feature flag which was fully released from 1.74.0, so this is not a regression.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No errors should arise from interacting with the selected Search Funnel metrics on the Site Kit dashboard, regardless of the zero or gathering state for either Search Console or Analytics
* The "Unique Visitors from Search" metric should only show in a gathering state according to the respective state of the Analytics module

## Implementation Brief

- Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview/index.js`:
  - Retrieve the gathering data state for the Analytics module.
    - Use the `useInViewSelect()` hook.
    - Only call the `isGatheringData()` selector when `analyticsModuleConnected` is true.
  - Pass the Analytics gathering data state, rather than the Search Console state, to the Analytics Data Blocks for `visitors` and `goals`. 
- Port these changes to the GA4 version of the Search Funnel widget that is being implemented via #6217.

### Test Coverage

- Update any failing tests.

## QA Brief

* Follow the steps to reproduce.
* Ensure the dashboard doesn't crash and the issue is fixed.
* Ensure the `Unique Visitors from Search` tab shows `gathering data…` state.

![Screenshot 2023-02-17 at 10 53 02 PM](https://user-images.githubusercontent.com/24408261/219722119-7cf46c41-1678-4fa2-8504-18e51d9f20b0.png)

## Changelog entry

* Ensure the Analytics metrics in the Search Funnel widget are disabled when Analytics is gathering data.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Able to reproduce issue on latest environment.
- Error not occurring on main.
- Tested main, entity and WP dashboard SK widget when Search console is in zero and analytics in gathering state.
- Tested main, entity and WP dashboard SK widget when Search console is in gathering and analytics in zero state.
- Tested main, entity and WP dashboard SK widget when Search console and analytics in zero data state.
- Tested main, entity and WP dashboard SK widget when Search console and analytics is in gathering state.
- Verified The "Unique Visitors from Search" metric showing in a gathering state according to the respective state of the Analytics module.
- Verified no errors arise from interacting with the selected Search Funnel metrics on the Site Kit dashboard, regardless of the zero or gathering state for either Search Console or Analytics.

<details>


https://user-images.githubusercontent.com/94359491/220549354-e7551b10-0977-439e-965d-0a2d84a6075e.mp4

</details>
