### ISSUE TITLE
test-data-bot faker is not using our random seed, causing potential test failures

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#6593]
## Bug Description

Previously, we noticed tests could fail when `faker` created two IDs that were used for the `key` prop on a component (see #5053). Essentially, our fake data needs a consistently-set seed value so the "fake"/"random" data is consistent on every test run.

Unfortunately, the data we generate in our factories using `@jackfranklin/test-data-bot` uses a different version (and thus, different instance) of `faker`, so our seed value is not used and the random IDs we generate have the potential to cause a test failure due to ID collision, see: https://github.com/google/site-kit-wp/actions/runs/4177639523/jobs/7235466493#step:7:348

This is incredibly rare and can be fixed by re-running tests, but it would be better to fix it to prevent confusing JS test failures in the future.

The easiest way to fix this is actually to upgrade the version of `@jackfranklin/test-data-bot` we use and provide our own instance of `faker` for fake data we want to generate. This new version does not include `faker`, but provides a function to utilise our own instance directly instead (see https://github.com/jackfranklin/test-data-bot/pull/603). Because we have very few instances of `@jackfranklin/test-data-bot`'s `fake()` function, it's easiest to upgrade this package to fix the issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All fake data generated by `faker`, including in `@jackfranklin/test-data-bot`, should be consistent between test runs.
* `@jackfranklin/test-data-bot` should be upgraded to version `2.0.0`.
* Tests using our factory builders should generate the same data across multiple test runs; this should be validated with a snapshot test.

## Implementation Brief

* Upgrade `@jackfranklin/test-data-bot` to version `2.0.0`.
* Change all `fake( ( { lorem } ) => lorem.words() )` calls to `perBuild( () => faker.lorem.words() )` calls.
* Update builder code that uses `Date.now().toString()` to use date strings instead, for snapshot tests.
* Merge #6594.

### Test Coverage

* Add a snapshot test to a builder to ensure the data generated by factories is consistent between test runs.

## QA Brief

* No QA needed; if JS tests pass this issue can be moved directly to approval.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅
