### ISSUE TITLE
error when activating google site kit plugin

### ISSUE THREAD

**Issue by Kiddcurry** [google/site-kit-wp#660]
Newbie here...Error I’m getting when trying to activate (google site kit):
NOTE: this path /vendor/autoload.php doesn’t exist in the directory? how do I resolve issue?

Warning: require_once(/home/rcnainc8/public_html/epicbillbradley.com/wp-content/plugins/site-kit-wp-develop/vendor/autoload.php): failed to open stream: No such file or directory in /home/rcnainc8/public_html/epicbillbradley.com/wp-content/plugins/site-kit-wp-develop/includes/loader.php on line 18

Fatal error: require_once(): Failed opening required '/home/rcnainc8/public_html/epicbillbradley.com/wp-content/plugins/site-kit-wp-develop/vendor/autoload.php' (include_path='.:/usr/local/php71/pear') in /home/rcnainc8/public_html/epicbillbradley.com/wp-content/plugins/site-kit-wp-develop/includes/loader.php on line 18

**Comment by ernee** [comment]
Hi @Kiddcurry ! 

Just to confirm: from where have you obtained the .zip file for the plugin?

Have you tried to download, install and activate the developer beta .zip file from the [Site Kit website](https://sitekit.withgoogle.com/)?

**Comment by Kiddcurry** [comment]
To whom it may concern,

Downloaded from Github depository.

**Comment by ernee** [comment]
@Kiddcurry thanks for confirming. Could you try the download from the website ? Here's a [direct link](https://sitekit.withgoogle.com/service/download/google-site-kit.zip).

Please let me know if that helps!

**Comment by Kiddcurry** [comment]
hi ernee,

That worked! Except now when I got copied and pasted my OAuth credentials into the '"Welcome to Site Kit beta for developers client configuration field and I click on [PROCEED] I get a (The response is not a valid JSON response.)! How do I resolve this issue?
Thanks in advance
Ridgley

**Comment by Kiddcurry** [comment]
sorry didn't mean to comment and close thread!!

**Comment by ernee** [comment]
@Kiddcurry no worries!

Please try the following troubleshooting steps:

1) Check your WordPress site settings under "Settings > General" in your WordPress dashboard. 

2) Confirm your WordPress Address (URL) and Site Address (URL) match, and ensure they have a https prefix if you are using a https website.

3) Restart the Site Kit setup process again (make sure there are no extra spaces before or after the OAuth credentials after pasting them in the field).

If the same error appears: 

1) Close the "Couldn't create project" window
2) In the address bar of your window paste the following in: https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
3) Replace the yourwebsitecom and also http://yourwebsite.com with your own site details.  Include the https or http
4) Press enter, with your cursor in the address bar (as if you are visiting that URL)
5) Press the "GET OAUTH CREDENTIALS" button

The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit.

 If the above fails please share your WordPress[ Site Health](https://i.imgur.com/Rtkmsba.png) information

**Comment by Kiddcurry** [comment]
Hi ernee,

Tried both solution and got the same message as before (The response is not a valid JSON response). I also made sure to use the copy icon for the OAuth credentials. 
So I'm sharing my site health information below. I hope this sheds so light as to whats going on.

### wp-core ###

version: 4.9.12
site_language: en_US
user_language: en_US
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/rcnainc8/public_html/epicbillbradley.com
wordpress_size: 345.73 MB (362525231 bytes)
uploads_path: /home/rcnainc8/public_html/epicbillbradley.com/wp-content/uploads
uploads_size: 289.35 MB (303406051 bytes)
themes_path: /home/rcnainc8/public_html/epicbillbradley.com/wp-content/themes
themes_size: 12.15 MB (12741312 bytes)
plugins_path: /home/rcnainc8/public_html/epicbillbradley.com/wp-content/plugins
plugins_size: 130.04 MB (136352096 bytes)
database_size: 23.63 MB (24772608 bytes)
total_size: 800.89 MB (839797298 bytes)

### wp-active-theme ###

name: OceanWP Child (oceanwp-child-theme-master)
version: 1.0
author: Nick
author_website: https://oceanwp.org/
parent_theme: OceanWP (oceanwp)
theme_features: menus, gutenberg, post-formats, title-tag, automatic-feed-links, post-thumbnails, custom-header, custom-logo, html5, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, editor-style, customize-selective-refresh-widgets, widgets
theme_path: /home/rcnainc8/public_html/epicbillbradley.com/wp-content/themes/oceanwp-child-theme-master

### wp-parent-theme ###

name: OceanWP (oceanwp)
version: 1.5.32 (latest version: 1.7.1)
author: Nick
author_website: https://oceanwp.org/about-me/
theme_path: /home/rcnainc8/public_html/epicbillbradley.com/wp-content/themes/oceanwp

### wp-themes-inactive (3) ###

Twenty Fifteen: version: 2.0, author: the WordPress team (latest version: 2.5)
Twenty Seventeen: version: 1.6, author: the WordPress team (latest version: 2.2)
Twenty Sixteen: version: 1.5, author: the WordPress team (latest version: 2.0)

### wp-plugins-active (21) ###

Advanced Custom Fields PRO: version: 5.7.10, author: Elliot Condon (latest version: 5.8.5)
Antispam Bee: version: 2.9.1, author: pluginkollektiv
Changing Background on hover: author: (undefined), version: (undefined)
Custom Post Type UI: version: 1.6.2, author: WebDevStudios
Duplicator Pro: version: 3.7.9, author: Snap Creek
Easy Theme and Plugin Upgrades: version: 2.0.1, author: Chris Jean
Elementor: version: 2.7.4, author: Elementor.com
Elementor Pro: version: 2.7.2, author: Elementor.com
Granular Controls Elementor: version: 1.0.5, author: Zulfikar Nore
Health Check & Troubleshooting: version: 1.4.2, author: The WordPress.org community
Jet Elements For Elementor: version: 1.15.0, author: Zemez (latest version: 2.1.2)
MailPoet 3 (New): version: 3.38.0, author: MailPoet
Ocean Extra: version: 1.5.16, author: OceanWP
PowerPack Elements: version: 1.3.8.3, author: Team IdeaBox - PowerPack Elements (latest version: 1.4.9.2)
SEOPress: version: 3.7.2, author: Benjamin Denis
SEOPress PRO: version: 3.6.2.1, author: Benjamin Denis
SG Optimizer: version: 5.3.3, author: SiteGround
Site Kit by Google: version: 1.0.0-beta.1.0.8, author: Google
SpreadShop: version: 1.5.0, author: Robert Schulz (sprd.net AG)
Ultimate Addons for Elementor: version: 1.9.0, author: Brainstorm Force (latest version: 1.19.0)
Youtube Playlist Video Player: version: 1.10.0, author: Rik de Vos

### wp-plugins-inactive (1) ###

Changing Background on hover: author: (undefined), version: (undefined)

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.1.30 64bit
php_sapi: cgi-fcgi
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.59.0 OpenSSL/1.0.2r
suhosin: false
imagick_availability: false
server-headers: 
	server: nginx
	date: Fri, 18 Oct 2019 01:23:45 GMT
	content-type: text/html; charset=UTF-8
	content-length: 22320
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	x-cache-enabled: True
	x-ua-compatible: IE=edge
	link: <https://epicbillbradley.com/wp-json/>; rel="https://api.w.org/", <https://epicbillbradley.com/>; rel=shortlink
	set-cookie: wpSGCacheBypass=1; expires=Fri, 18-Oct-2019 03:03:44 GMT; Max-Age=6000; path=/
	vary: Accept-Encoding
	content-encoding: gzip
	host-header: 624d5be7be38418a3e2a818cc8b7029b
	x-proxy-cache: BYPASS
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.40-84.0-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/rcnainc8/public_html/epicbillbradley.com/wp-content
WP_PLUGIN_DIR: /home/rcnainc8/public_html/epicbillbradley.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by ernee** [comment]
Thanks for the info @Kiddcurry !

1) Could you try to the setup process in an incognito and/or alternate browser? Sometimes extensions like ad blockers can interfere.

2) I know you've mentioned using the copy icon before, so that's good. Continue to double check there are no extra spaces before or after the OAuth (JSON format) credentials.  

Please let me know if this helps!

**Comment by Kiddcurry** [comment]
I’ve done everything you’ve suggested! Still no luck…getting the same message (see: attachment)


Best Regards,
Ridgley Curry

Ridgley Curry & Associates, Inc.
921 Athens St.
Altadena ca 91001

**Comment by Kiddcurry** [comment]
![Google Site Kit error](https://user-images.githubusercontent.com/15821896/67413985-11335180-f577-11e9-8cbf-8874cb25ca47.png)

**Comment by ernee** [comment]
Thanks for the update and the screenshot @Kiddcurry ! We released a new version that simplifies this process. It should be available to update on the plugins page of your dashboard. You can also [download it here](https://sitekit.withgoogle.com/service/download/google-site-kit.zip).  

Could you try it and let me know how it goes?

**Comment by ernee** [comment]
@Kiddcurry we had an issue with the recent update version 1.0.0-rc.1, and reverted back to the previous setup flow in version 1.0.0-rc.1.1 

A few options:

1) I can let you know when the new, simplified setup flow is ready, so we can see if that resolves this issue. 

2) The JSON code in your screenshot looks correct. You can try to troubleshoot further to see if a plugin is conflicting. The first I would try is temporarily deactivating SG Optimizer as in some cases caching can have an effect.

**Comment by Kiddcurry** [comment]
Hi Ernee,

Installed new Site Kit plugin and was able to install [Search Console], but when I went to "Connect More Services" [Analytics] and/or [PageSpeed insights] I got the same Internal Server Error message "The response is not a valid JSON response" again! (See attached screenshot)
![Screen Shot 2019-10-24 at 1 13 28 PM](https://user-images.githubusercontent.com/15821896/67521909-a0686400-f660-11e9-811e-2e157771c8cb.png)

**Comment by ernee** [comment]
Hi @Kiddcurry ! Glad you were able to get through the first step. There does seem to be something conflicting. 

1) Did you to try to connect with SG Optimizer deactivated temporarily?
2) Could you also try in an incognito browser and (for good measure) clear the browser cache? 

We'll have the new setup flow out soon, so we can try then too at any rate.

**Comment by ernee** [comment]
Hi @Kiddcurry! The new version 1.0.0-rc.2 of the plugin is available. Could you update the plugin and let me know if you're able to get through the setup process? Thanks again!

**Comment by ernee** [comment]
Hi @Kiddcurry! The new version 1.0.0 of Site Kit is available in the [plugin repository](https://wordpress.org/plugins/google-site-kit/). It includes the new setup flow. Please update at your convenience and if you should have any further questions or concerns open a [support topic in the forums.](https://wordpress.org/support/plugin/google-site-kit/) Thank you!
