### ISSUE TITLE
Mirror WordPress http proxy configuration for Google Client

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#661]
## Feature Description

Some sites use/require an HTTP proxy to make requests. WordPress provides a number of constants for configuring the WP HTTP API to use a proxy.

The HTTP client used by `Google_Client` should mirror the same http proxy configuration for WordPress if its constants are defined: `WP_PROXY_HOST` and `WP_PROXY_PORT`

Proxy credentials should be supported as well if set: `WP_PROXY_USERNAME`, `WP_PROXY_PASSWORD`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Allow users to rely on `WP_PROXY_*` constants to use an HTTP proxy for requests issued by `Google_Client` (now mostly `Google_Site_Kit_Client`).

## Implementation Brief

* Use core's `WP_HTTP_Proxy` class to detect the active state, and retreive values from core constants
    - There is no global object for this (nor does there need to be), we can instantiate and keep this as a instance property on `OAuth_Client` as `$http_proxy`
* In `OAuth_Client::get_client()`, check if `$http_proxy->is_enabled()` - configure the Google client with the proxy configuration
    ```php
    $proxy_host = $this->http_proxy->host() . ':' . $this->http_proxy->port();
    if ( $this->http_proxy->use_authentication() ) {
        $proxy_host = $this->http_proxy->authentication() . '@' . $proxy_host;
    }
    $client->getHttpClient()->setDefaultOption( 'proxy', $proxy_host );
    $ssl_verify = $client->getHttpClient()->getDefaultOption( 'verify' );
    $client->getHttpClient()->setDefaultOption(
        'verify',
        apply_filters( 'https_ssl_verify', $ssl_verify, null )
    );
    ```

## QA Brief

This is documented for testing locally as this might be more difficult to test on a live site

1. Install an HTTP proxy locally, if you don't have one already  
https://docs.mitmproxy.org/stable/overview-installation/
    - Start the proxy by running `mitmproxy` **note the port in the bottom right** (default: `8080`)
1. Configure the proxy host and port in your `wp-config.php`
    ```php
    define( 'WP_PROXY_HOST', 'host.docker.internal' );
    define( 'WP_PROXY_PORT', '8080' );
    ```
    > For me, this is `host.docker.internal` because I'm using Docker locally
    If you're using something else, this may be `localhost`, but you want to target your host machine, where the proxy is listening
1. Install [this plugin to disable SSL verification](https://github.com/google/site-kit-wp/files/4041695/disable-ssl-verification.100.zip)
1. Click around Site Kit, you should start to see lines appearing (see below)
    - If you see errors, your proxy is not configured properly
1. Go to the WordPress _Dashboard > Updates_ page, and click **Check Again** to force a request from WordPress to check for updates. You should see this in mitmproxy.
1. Go to the Site Kit dashboard (setup if necessary).  
A few ways to trigger requests:
    - Set up a new module that makes requests, such as Analytics or Tag Manager
    - Switch the date range on a dashboard page
    - Clear your browser's Session Storage and reload a Site Kit dashboard page
1. You should see requests to `googleapis.com` in mitmproxy to confirm that requests are going through it
1. When done, press `q` to stop mitmproxy, and `y` to confirm from the processes terminal window

**Example of requests seen in mitmproxy**
![image](https://user-images.githubusercontent.com/1621608/72090381-a17f6800-3316-11ea-8fb6-86a22eb9a308.png)

## Changelog entry

* Allow users to rely on `WP_PROXY_*` constants to use an HTTP proxy for requests issued by `Google_Client`.

**Comment by felixarntz** [comment]
IB ✅ 

Let's clarify in a comment, and probably also in naming variables/properties `$http_proxy`, that this is not related to the "Site Kit proxy".

**Comment by cole10up** [comment]
**Tested**
Ran through the proxy setup, confirmed proxy is functional
![image](https://user-images.githubusercontent.com/57115907/72450672-a194c300-376f-11ea-8e92-1b98d7c51226.png)

Ran through some tests setting up and removing GA.
Confirmed googleapi requests are coming through:
![image](https://user-images.githubusercontent.com/57115907/72450940-06e8b400-3770-11ea-93c1-55cde13f1597.png)

Passed QA ✅
