### ISSUE TITLE
Reduce code complexity in `SearchFunnelWidgetGA4`

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#6611]
## Feature Description

This is a follow-up of #4895, which introduces the [`complexity`](https://eslint.org/docs/latest/rules/complexity) rule in ESLint. This resulted in the following lint error:

```
.../wordpress/wp-content/plugins/google-site-kit/assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js
  60:31  error  Arrow function has a complexity of 23. Maximum allowed is 20  complexity
```

The `SearchFunnelWidgetGA4` component is being implemented in #6217. 

While the error is currently ignored, this issue aims to reduce said complexity.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint ignore for `complexity` should be removed from the `SearchFunnelWidgetGA4/index.js` component identified in the title
* The component should be refactored to reduce the complexity to be within the acceptable range set by the current rule
* It should follow the same or similar refactored approach as the UA version `SearchFunnelWidget`, which is being implemented in #6035 

## Implementation Brief

* Once #6217 and #6035 are merged, continue with the following steps:
* Consolidate the following analytics loading state logic into a single select that returns a boolean:
    * `ga4OverviewLoading`
    * `ga4StatsLoading`
    * `ga4VisitorsOverviewAndStatsLoading`
    * `ga4ConversionsLoading`
* Consolidate the following analytics error logic into a single select that returns the error object/boolean:
    * `ga4OverviewError`
    * `ga4StatsError`
    * `ga4VisitorsOverviewAndStatsError`
    * `ga4ConversionsError`
* Update the condition that checks for the loading state to use the new select data.
* Pass the consolidated error object to the `Overview` component's `error` prop.

### Test Coverage

* No new tests are to be added.

## QA Brief

* **General Observation**: No user-facing changes should be observed.
  
* **Google Analytics 4 View**:
   - Open the dashboard and confirm that it displays the Google Analytics 4 view, not UA.

* **`SearchFunnelWidgetGA4` Functionality**:
   - Ensure the GA4 widget (specifically for GA4, not UA) functions as expected.
   - Pay particular attention to the widget's loading and error states.

* **Simulating Error States**:
   - You can simulate error states by aborting the GA4 `getReport` requests.
   - Use an HTTP proxy or request proxy tool like Proxyman.
   - Target URL for simulation: `https://<test-hostname>/wp-json/google-site-kit/v1/modules/analytics-4/data/report`.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
> * Create the following components in the `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4` directory:
>   
>   * `DisplayPreviewBlock` - receives `WidgetFooter` as props and move the `Widget->WidgetReportError` and `Widget->PreviewBlock` components and the associated logic to it.
>   * `DisplayOverview` - move the `Overview` component and the associated logic to it.
>   * `DisplayStats` - move the `SearchConsoleStats`, `Grid->Cell->ActivateAnalyticsCTA` and `AnalyticsStats` components and the associated logic to it.
> * If any logic has to be shared between the components, keep it in the `SearchFunnelWidgetGA4/index.js` file and pass it as props to the new components. For example, `canViewSharedAnalytics`.

@hussain-t, no need to extract anything. What we need to do in that component is to consolidate selects that check whether a certain Analytics report is being loaded into one select that returns true if any of those four reports is still being loaded.

Same should probably be done for error checks for Analytics reports. Just one select that returns an error if any is available for those four reports.

**Comment by hussain-t** [comment]
Thanks, @eugene-manuilov. I have updated the IB and reduced the estimate to `7`.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that analytics a/c don't have UA property then dashboard displays the Google Analytics 4 view, not UA.
- Verified that analytics a/c have UA property and dashboard view set to GA4 then dashboard displays the Google Analytics 4 view, not UA.
- Verified the GA4 widget functions as expected.
- Compared GA4 widgets functionality with latest environment.
- Verified the widget's loading and error states.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e176cdf3-1ea6-4c75-bcc0-3a004d15f4a3)

![image](https://github.com/google/site-kit-wp/assets/94359491/a6e02b85-adc5-416d-872e-8d9a5185e2d3)

![image](https://github.com/google/site-kit-wp/assets/94359491/f3a55753-87a2-4d30-a8c2-1f58626e4b7b)

![image](https://github.com/google/site-kit-wp/assets/94359491/af6efd39-0639-49fc-99f0-cc1cd458b8e6)

</details>
