### ISSUE TITLE
Enforce the GA4 metric name regular expression in our report argument validation.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6615]
## Feature Description

As described on the [GA4 report schema documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Metric), the `name` value for a metric must match the regular expression `^[a-zA-Z0-9_]$`.

However, this regex is not checked, either in our JS or PHP-side validation.

We should update the GA4 JS [`isValidMetrics()`](https://github.com/google/site-kit-wp/blob/f8613b5edcebf0056278c2165c1e92928d7f4d5c/assets/js/modules/analytics-4/utils/report-validation.js#L40) function and PHP [metric parsing code](https://github.com/google/site-kit-wp/blob/f8613b5edcebf0056278c2165c1e92928d7f4d5c/includes/Modules/Analytics_4.php#L1111-L1153) to check this regex for metric names.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The GA4 JS [`isValidMetrics()`](https://github.com/google/site-kit-wp/blob/f8613b5edcebf0056278c2165c1e92928d7f4d5c/assets/js/modules/analytics-4/utils/report-validation.js#L40) function and PHP [metric parsing code](https://github.com/google/site-kit-wp/blob/f8613b5edcebf0056278c2165c1e92928d7f4d5c/includes/Modules/Analytics_4.php#L1111-L1153) should validate metric `name` values with the regular expression `^[a-zA-Z0-9_]+$`.
- The corresponding JS [error message](https://github.com/google/site-kit-wp/blob/f8613b5edcebf0056278c2165c1e92928d7f4d5c/assets/js/modules/analytics-4/datastore/report.js#L87) should be updated to read as follows:
  - _metrics for an Analytics 4 report must be either a string, an array of strings, an object, an array of objects, or a mix of strings and objects. Objects must have a "name" property matching the expression `^[a-zA-Z0-9_]+$`._
- The PHP metric parsing code should be enhanced to return an `invalid_analytics_4_report_metrics` error for metric values which do not parse to a valid metric. The message(s) for this error can be determined in the IB.

## Implementation Brief

* Inside `/assets/js/modules/analytics-4/utils/report-validation.js` locate `isValidMetrics` function and add `metric.name.match( /^[a-zA-Z0-9_]+$/ )` into the `validName` checkup
* Inside `/assets/js/modules/analytics-4/datastore/report.js` locate  place where `isValidMetrics( metrics )` call happens and change the invariant error message to match the one from the AC
* Inside `/plugins/google-site-kit/includes/Modules/Analytics_4.php` locate `validate_report_metrics` and add the following:
    * In the place where `$invalid_metrics` gets assigned withing `array_map` add a new rule to check if `$metric->getName()` mathces `^[a-zA-Z0-9_]+$` by using `preg_match()` func
    * If the above check fails throw an error `Invalid_Report_Metrics_Exception` with the error `'Name property should match the expression ^[a-zA-Z0-9_]+$'` or similar 

In order to match more than one character/require a single character, our regex `^[a-zA-Z0-9_]+$` differs from the one from the Google Developer documentation (`^[a-zA-Z0-9_]$`). It seems that's an oversight, and since the `name` property can be used for operations, an empty one is presumably not intended.

### Test Coverage

* Add tests cases to JS `isValidMetrics` and PHP `validate_report_metrics`

## QA Brief

- Set up Site Kit with Analytics and enable the `ga4Reporting` feature flag.

### Client-side validation

- Call the GA4 `getReport()` selector, with a metric name that does not match the pattern `^[a-zA-Z0-9_]+$` - which in English, specifies that the metric should contain only alphanumeric characters and the underscore character, and should contain at least one character. Verify an error is thrown in the JS console with the expected error message.

```js
await googlesitekit.data.select( 'modules/analytics-4' ).getReport({
    startDate: '2023-01-01',
    endDate: '2023-02-01',
    metrics: [ 'totalUsers!' ],
});

// Test with the different formats for specifying metrics:
    metrics: 'totalUsers!',
    metrics: 'totalUsers,sessions!',
    metrics: [ 'totalUsers!' ],
    metrics: { name: 'totalUsers!' },
    metrics: [ { name: 'totalUsers!' } ],
    metrics: [ { name: 'totalUsers' }, 'session!' ],
```

- Note that the proposed message in the AC is a little inaccurate as it seems to suggest that _only_ object name properties will be validated against the regular expression, whereas _all_ metric names will be, whether passed as a string or an object.
  - _metrics for an Analytics 4 report must be either a string, an array of strings, an object, an array of objects, or a mix of strings and objects. Objects must have a "name" property matching the expression ^[a-zA-Z0-9\_]+$._
- This message has been tweaked to reflect this, and now reads as follows:
  - _metrics for an Analytics 4 report must be either a string, an array of strings, an object, an array of objects, or a mix of strings and objects. Objects must have a "name" property. Metric names must match the expression ^[a-zA-Z0-9\_]+$._

### Server-side validation

- Perform a similar set of tests as for the client-side validation, except calling `googlesitekit.api.get()` to ensure the request is made to the backend. For example:
```js
googlesitekit.api.get( 'modules', 'analytics-4', 'report', {
    startDate: '2023-01-01',
    endDate: '2023-02-01',
    metrics: ['totalUsers!'],
});
```
- Ensure the request returns a 500 error with the expected code and message:
  - `code`: `invalid_analytics_4_report_metrics`
  - `message`: _Metric name should match the expression ^[a-zA-Z0-9\_]+$: totalUsers!_

## Changelog entry

* Add checks for Google Analytics 4 metric names to Analytics report handling.

**Comment by tofumatt** [comment]
ACs are good here, moved to IB 👍🏻

**Comment by tofumatt** [comment]
@sashadoes Why the `._` at the end of the regex? The ACs mention the regex should be `^[a-zA-Z0-9_]$`, but your proposed regex is `/^[a-zA-Z0-9\_]$._/`— I don't know what the wildcard and extra `_` is for.

**Comment by techanvil** [comment]
@tofumatt @sashadoes, I've just realised, despite the regex `^[a-zA-Z0-9_]$` being copied directly from the [API docs](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Metric), presumably it should in fact be `^[a-zA-Z0-9_]+$` in order to match more than one character...

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

_Client side_

- When running the code in browser console the error message appears `metrics for an Analytics 4 report must be either a string, an array of strings, an object, an array of objects, or a mix of strings and objects. Objects must have a "name" property. Metric names must match the expression ^[a-zA-Z0-9_]+$.`
  - I tested this on the different metric names provided in the QAB.  All generated this error message. 

_Server-side validation_

- When running the code in the browser console the error message appears:
  -  500 error with the code and message:
  - code: invalid_analytics_4_report_metrics
  - message: `Metric name should match the expression ^[a-zA-Z0-9_]+$: totalUsers!`
  - I tested this on the different metric names provided in the QAB.  All generated this error message. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/227516201-5e178c28-5b60-47a4-8c55-5a8a54238489.png)
![image](https://user-images.githubusercontent.com/73545194/227516229-cd7b37e9-5438-442a-a410-2e9a24b1c101.png)
![image](https://user-images.githubusercontent.com/73545194/227516255-cc159824-1738-48ab-a191-ad96c524fb0f.png)
![image](https://user-images.githubusercontent.com/73545194/227516278-fb818279-4ee8-43c3-a495-73437b47f366.png)

</details>
