### ISSUE TITLE
Remove bundled `firebase/php-jwt` library

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6619]
## Feature Description

There is a dependabot alert for `firebase/php-jwt` which is a dependency of `google/auth` and `google/apiclient` libraries that we cannot fix by an upgrade due to version limitations.

```
google/apiclient           v2.13.0     requires   firebase/php-jwt (~2.0||~3.0||~4.0||~5.0||~6.0)  
google/auth                v1.18.0     requires   firebase/php-jwt (~2.0|~3.0|~4.0|~5.0)           
roave/security-advisories  dev-latest  conflicts  firebase/php-jwt (<2)  
```

The fix which is present in v6 of `php-jwt` cannot be installed due to the lack of support in the dependency's version constraint of `google/auth` which only supports up to v5.

We are also using an older version of `google/auth`, so upgrading to a newer version of this would fix the problem, however other dependency constraints prevent us from doing so.

The earliest version of `google/auth` which allows for a v6 version of `php-jwt` is [`1.21.0`](https://packagist.org/packages/google/auth#v1.21.0), the problem is that this version requires a minimum PHP version of 7.1 which is of course incompatible with our minimum of 5.6 which all dependencies must meet.

This isn't really a problem for us though because we don't use JWT, only oAuth, so we can safely exclude the library from our distributed bundle altogether to avoid distributing (even if unused) vulnerable code.

See https://github.com/google/site-kit-wp/security/dependabot/91

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `firebase/php-jwt` package should be omitted from the distributable plugin zip.

## Implementation Brief

* Remove the line which includes `firebase` dependencies from prefixing, and in turn, inclusion in our `/third-party` dependencies

```diff
diff --git a/scoper.inc.php b/scoper.inc.php
index ca406652fe..4fbdc7aa97 100644
--- a/scoper.inc.php
+++ b/scoper.inc.php
@@ -46,7 +46,6 @@ return array(
 					'vendor-bin',
 				)
 			)
-			->path( '#^firebase/#' )
 			->path( '#^google/apiclient/#' )
 			->path( '#^google/auth/#' )
 			->path( '#^guzzlehttp/#' )
```
* Merge https://github.com/google/site-kit-wp/pull/6620

### Test Coverage

* No changes

## QA Brief

* Ensure Google authentication (oAuth flows) + report requests continue to work as expected

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv Nice, also one less dependency in our bundle (which apparently we don't even use). IB ✅

**Comment by aaemnnosttv** [comment]
Moving to CR as there's nothing more to do beforehand, and already tested that at least everything isn't hosed with the PR zip 😄 

@bethanylang this isn't particularly time-sensitive but should be a quick/easy win we can squeeze in any time.

**Comment by wpdarren** [comment]
@mohitwp hope you don't mind but I have assigned you to this ticket so I can focus on the GTE Support test plan/bug bash instructions.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Tested that Google authentication (oAuth flows) and report requests continue to work. 
  - No issues found on the dashboard for zero, gathering and live data.
  - oAuth screens appear as expected when setting up the modules. Tested this with Analytics, AdSense.
