### ISSUE TITLE
Implement survey queue backend infrastructure

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6625]
## Feature Description

Originally defined in #6306, this issue is scoped to the backend specific changes.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Surveys should be triggered remotely on-demand as today, and any returned surveys should be added to **a new user-specific persistent queue** in the order they are received as part of the current `survey-trigger` endpoint handler
	* A survey should only be added to the queue if it is not already present
	* The queue should be deleted on reset or disconnect
* A new `GET:core/user/data/survey` endpoint should be created for returning the front-most survey from the queue
	- Note: returning a survey should not dequeue it
* The `survey-event` handler should be enhanced such that a `completion_shown` or `survey_closed` event dequeues its respective survey from the queue

## Implementation Brief

**Survey Queue**
* Create a new `Core\User_Surveys\Survey_Queue` class
	* Takes a `User_Options_Interface` as a constructor dependency
	* Implement a queue interface
		- `enqueue( Survey ) : bool` - adds the given survey to the end of the queue, only if it does not exist in the queue (returns `bool` to indicate if it was enqueued or not)
		- `dequeue( survey_id ) : Survey?` - removes and returns the survey from the queue if present, or `null` if not found in the queue – the dequeued survey should always be the first one but we should use the survey ID to avoid dequing the wrong one inadvertently
		- `front() : Survey?` - returns the survey at the "front" (i.e. element 0) of the queue without removing it, or `null` if the queue is empty
		- `find_by_session( session ) : Survey?` – returns the survey in the queue by its `session` (`Session{session_id, session_token}`) (necessary for use with `survey-event` endpoint below)
	* Set this up in the `Core\User_Surveys\User_Surveys` class, and pass through the instance to the `REST_User_Surveys_Controller` as a new constructor dependency
	* Store the queue in user options using a key like `googlesitekit_surveys` (these will be deleted on disconnect and reset – see [`Authentication::disconnect`](https://github.com/google/site-kit-wp/blob/8e0dc4fb781d32de3880530891b63c43e750ac93/includes/Core/Authentication/Authentication.php#L536) & [`Reset::delete_user_options`](https://github.com/google/site-kit-wp/blob/8e0dc4fb781d32de3880530891b63c43e750ac93/includes/Core/Util/Reset.php#L179-L184))

**Survey Endpoints**

Update `REST_User_Surveys_Controller`
* Implement a new `REST_Route` for `GET:survey`
	* Should require the same permissions as other routes there (user is authenticated + using proxy)
	* Return an object with the shape `{ survey: Survey? }` which uses the `queue->front` method internally
* Update `survey-event` endpoints to include queue changes for specific events
	* `completion_shown` or `survey_closed` events should dequeue the given survey from the queue using `queue->dequeue`
		- Survey events only include the `session_id` and `session_token` – use these with `queue->find_by_session` and `dequeue` the returned survey
	* `survey_shown` should reset the global survey cooldown period for 12 hours – this can use the existing survey timeouts infrastructure, using a special `global` survey ID
* Update `survey-trigger`
	* Update the handling of the `send_survey_trigger` response – if a survey is returned, enqueue it with `queue->enqueue`

### Test Coverage

* Add PHPUnit coverage for the new `Survey_Queue` class
* Update PHPUnit `REST_User_Surveys_ControllerTest`
	- Add tests for `GET:survey`
	- Changes for `survey-event` and `survey-trigger` endpoints

## QA Brief

* Create a new site and connect the plugin
* Ping @eugene-manuilov on slack to help you to configure a real survey for your site on a development environment.
* Then go to the dashboard page and ensure that you see a survey there, but don't interact with the survey yet.
* Check that you see the new survey in the surveys queue in the database using
  * wp-cli command if available: `wp user meta get {user_id} wp_googlesitekit_survey_queue` where `{user_id}` should be replaced with your current user ID.
  * sql query if you have access to the database: `SELECT * FROM wp_usermeta WHERE meta_key LIKE '%googlesitekit_survey_queue%'`
* Now complete the survey and verify that the surveys queue is empty using the same command.
* Finally check `wp_googlesitekit_survey_timeouts` user meta value (using the similar approach) to ensure that you see the `__global` key is added.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv ACs + IB ✅

**Comment by kuasha420** [comment]
@aaemnnosttv I wanted to pick this one up but seeing you've worked on the IB for it and it's quite a bit complicated, do you want to work on execution as well? If not, I will work on this one. Cheers.

**Comment by bethanylang** [comment]
@kuasha420 Noting that this is one that we want to get completed early in the sprint before moving on to #6306. @eugene-manuilov was going to pick that one up but may want to get this one as well. I'll let you two work it out!

**Comment by eugene-manuilov** [comment]
@kuasha420, I'll work on it 👍

**Comment by aaemnnosttv** [comment]
Regarding the QAB

> * Ensure that you see a survey on the dashboard page, but don't interact with the survey yet.

@eugene-manuilov can you be more specific here? I don't think we show any surveys to users who just installed the plugin. Alternatively, can we maybe use the local/playground environment to force a test survey from the service?

> * Check that you see the new survey in the surveys queue in the database using `wp option get googlesitekit_survey_queue` command.

The queue is stored per-user so this wouldn't work, but also I'm not sure if QA has access to WP-CLI in the sites they test with. Perhaps an API request would be easier to check with?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv QAB is updated.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@eugene-manuilov I've 2 questions regarding my observations -

- I've noticed that `wp__googlesitekit_survey_timeouts` is getting added along with googlesitekit_survey_queue and after completing survey `wp__googlesitekit_survey_timeouts` is not getting empty and also it's value is not changing. Is this expected ?

- Survey is showing only on Main Dashboard and and not on entity dashboard. Is this expected ?


![image](https://user-images.githubusercontent.com/94359491/224961585-b15353db-dd14-47d2-95db-6e373ba3af1b.png)


- Tested on dev environment.
- Tested after setting up site on sitekit local. 
- Verified that survey is adding to the  '%googlesitekit_survey_queue%' .
- Verified a survey is not getting added to the queue if it is not already present
- The queue is getting deleted on reset or disconnect.
- Verified `wp_googlesitekit_survey_timeouts` user meta value and the __global key is added to it.

<details>

https://user-images.githubusercontent.com/94359491/224963202-6bd9b426-f608-4297-a7b5-e6668f87cd4e.mp4

</details>

**Comment by eugene-manuilov** [comment]
@mohitwp 

> I've noticed that `wp__googlesitekit_survey_timeouts` is getting added along with googlesitekit_survey_queue and after completing survey `wp__googlesitekit_survey_timeouts` is not getting empty and also it's value is not changing. Is this expected ?

Yes, that's correct.

> Survey is showing only on Main Dashboard and and not on entity dashboard. Is this expected ?

Yes, this is expected because we show surveys only on the main dashboard.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested after setting up site on sitekit local. 
- Verified that survey is adding to the  '%googlesitekit_survey_queue%' .
- Verified a survey is not getting added to the queue if it is not already present
- The queue is getting deleted on reset or disconnect.
- Verified `wp_googlesitekit_survey_timeouts` user meta value and the __global key is added to it.

<details>

https://user-images.githubusercontent.com/94359491/224963202-6bd9b426-f608-4297-a7b5-e6668f87cd4e.mp4

</details>
