### ISSUE TITLE
Account menu could use more context for name/email when using assistive technology (Accessibility)

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#6637]
## Bug Description

The content labelling the “Account” menu could use a “name” and “email” prefix for those values, or even something “Google Account for [NAME] (email: [EMAIL])”.

## Steps to reproduce

1. Enable a screen reader (eg. VoiceOver on macOS, NVDA on Windows)
2. Focus the user account menu button in the top-right of the page
3. Note the text is "Google Account [NAME] [EMAIL]" without any prefixes/labels of the content inside.

## Screenshots

https://user-images.githubusercontent.com/90871/221064216-ea35e870-747e-4b24-bc55-79070206543b.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update the assistive text/label for the user account button to `“Google Account for [NAME] (email: [EMAIL])”`.
  * If the "name" field is not present, the text `"Google Account for email [EMAIL]"` is fine; same goes for if name is the only field available.
  * If neither are available, `"Google Account"` should be used.

## Implementation Brief

- In `assets/js/components/UserMenu/index.js`:
  - Update the `customizedTooltip` prop of the rendered `<Button>` component as follows:
    - Replace the `<Fragment>` with a `<span>` tag.
    - Add an `aria-label` prop to the added `<span>` tag with a translatable value according to the ACs. The text should be variable based on the availability of the user full name and email.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Load the Site Kit dashboard using a Screen reader, for instance macOS's VoiceOver or JAWS on Windows.
* Focus the user account menu button in the top-right of the page
* The text should have more context for the contents, eg. read "Google Account for [NAME] (Email: [EMAIL])"
  * If only a name or email is available, missing data will be omitted from the string, eg it will read "Google Account for [NAME]" or "Google Account (Email: [EMAIL])". Strictly speaking this doesn't need thorough QA, as long as the label is read and isn't read as Google Account [NAME] [EMAIL]" it's good. 🙂 

Note: For macOS VoiceOver utility, you will need to press Control + Option + Command + `/` to get the "more content" to be read aloud.

## Changelog entry

* Improve accessibility for user menu tooltip.

**Comment by derweili** [comment]
@tofumatt I'm can't reproduce the behaviour from you screencast. 
For me it only says "Account" which corresponds to the `aria-label` we defined here:
https://github.com/google/site-kit-wp/blob/cac2239c196261c90d2e9d496e4f54cc151e5763/assets/js/components/UserMenu/index.js#L192-L197

I'm in chrome on mac with voice over activated.

**Comment by nfmohit** [comment]
@derweili It took me a while but I was able to get the "Google Account..." text into the screen reader by opting in to hear "more content".

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Loaded the Site Kit dashboard using a Screen reader, when the user account menu button in the top-right of the page is focused, the text includes more context for the contents, eg. read `Google Account for [NAME] (Email: [EMAIL])`

It was difficult to take a screenshot, but I created a short screencast to see the more context. 

https://github.com/google/site-kit-wp/assets/73545194/da72cd2f-85fb-4621-914e-9d1b4ecf7743
