### ISSUE TITLE
AdSense Settings footer link takes user to 404 page

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6647]
## Bug Description

Identified as part of release testing for #6564 - Clicking on the AdSense settings footer page takes user to the AdSense start page. however this link has been changed from `https://www.google.com/adsense/start` to `https://adsense.google.com/start`. While there's a basic redirect in place for the above change in Google site, this only works for the plain URL. Since our link adds query parameter without adding a trailing slash, this doesn't work for us and users get a 404 page. 

## Steps to reproduce

1. Go to AdSense Settings 
2. Click on See full details in AdSense
3. See the link returns 404. 

## Additional Context
 - Plugin Version: 1.94.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AdSense Settings Footer Link should take user to AdSense home page without resulting in a 404 error. 
    * This can be accomplished by updating the `AdSense` modules homepage URL to `https://adsense.google.com/start`. 

## Implementation Brief

* In `Google\Site_Kit\Modules\AdSense` class:
    * Update the `homepage` with the correct URL from AC in the return array of `setup_info` function. 

### Test Coverage

* Fix any potential failing tests/snapshots. 

## QA Brief

* The AdSense footer link should behave correctly.

## Changelog entry

* Update the AdSense homepage URL, fixing the link in the AdSense Settings footer.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The AdSense link in the settings no longer 404's.  I am redirected to `https://adsense.google.com/start/?source=site-kit&url=https:%2F%2F195-0.instawp.xyz&pli=1&authuser=2`
- Went through all of the other external links on Site Kit settings to make sure they continue to function.
