### ISSUE TITLE
Replace direct usage of components from `@material/react-text-field` with the new `TextField` component.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6651]
## Feature Description

In #6113, we are creating a new `TextField` component that wraps usage of `TextField`, `Input` and `HelperText` from the `@material/react-text-field` package.

Following on from this, existing usage of the `TextField`, `Input` and `HelperText` components from `@material/react-text-field` should be replaced with this new `TextField` component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All usage of the `TextField`, `Input` and `HelperText` components from `@material/react-text-field` should be replaced with the new `TextField` component created via #6113.

## Implementation Brief

- Search for usage of the `TextField`, `HelperText` and `Input` components. A simple search for `<TextField` etc, or a regular expression `<(TextField|HelperText|Input)` is sufficient to find all usage in JSX at the time of writing. Other than this, the only current reference to these components is within `assets/js/material-components/index.js` where they are exported.
- The current resulting list of files is as follows (obviously, search again at execution time to ensure an up-to-date list):
  - `assets/js/components/legacy-setup/search-console.js`
  - `assets/js/components/legacy-setup/site-verification.js`
  - `assets/js/components/surveys/SurveyQuestionMultiSelect.js`
  - `assets/js/components/surveys/SurveyQuestionOpenText.js`
  - `assets/js/components/surveys/SurveyQuestionSingleSelectChoice.js`
  - `assets/js/components/user-input/UserInputKeywords.js`
  - `assets/js/modules/analytics/components/common/AccountCreate/CreateAccountField.js`
  - `assets/js/modules/analytics/components/common/AdsConversionIDTextField.js`
  - `assets/js/modules/analytics/components/common/ProfileNameTextField.js`
  - `assets/js/modules/optimize/components/common/AMPExperimentJSONField.js`
  - `assets/js/modules/optimize/components/common/OptimizeIDField.js`
  - `assets/js/modules/tagmanager/components/common/ContainerNameTextField.js`
  - `stories/accountchooser.stories.js`
  - `stories/text-field.stories.js`
- Go through each file and replace the use of `TextField`, `HelperText` and `Input` with the new `TextField` component introduced via https://github.com/google/site-kit-wp/issues/6113.
- Refer to the IB and subsequent implementation for https://github.com/google/site-kit-wp/issues/6113 for notes on using the new `TextField` component. Notably, we can ignore the following old `TextField` props: `floatingLabelClassName`, `disabled`, and `required`.

### Test Coverage

- Ensure all tests and VRT scenarios still pass.

## QA Brief
Given that changes have been made to a UI element that is utilised in many areas of the code base, we need to ensure that there have been no regressions within the application as a result of said refactoring. The following areas of the application are known to have contained the TextField component - based on changes made within the code - and testing instructions for each are to follow. 

### Google Analytics Module
The fields that follow can be accessed via Site Kite > Settings with the Analytics pane expanded and the "Edit" CTA clicked:

#### Account Creation/Setup
- Validate that the GA _Property_ select field, labelled "Property" continues to accept selections as per prior versions, and that any applicable helper text remains present as per prior versions.
- Validate that the GA _Account_ select field, labelled "Account" continues to accept selections as per prior versions, and that any applicable helper text remains present as per prior versions.
- Validate that the GA _View_ select field (formerly _Profile_), labelled "View" continues to accept selections as per prior versions, and that any applicable helper text remains present as per prior versions. This can be viewed only if the "Universal Analytics" toggle is toggled on.
- Validate that the GA _Web Data Stream_ input field, labelled "Web Data Stream" continues to accept text as per prior versions, and that any applicable helper text remains present as per prior versions.
- Next, from the "Account" select element, select the "Set up a new account" option.
- Validate that the same fields in points 1-4 above appear, and are able to accept text inputs as per prior versions, and that any applicable helper text remains present as per prior versions.

#### Google Ads
- Validate that - within the linked Google Analytics module settings - the input field labelled "Ads Conversion ID" continues to accept text as per prior versions, and that any applicable helper text remains present as per prior versions.

### Google Optimize Module
The fields that follow can be accessed via Site Kite > Settings with the Optimize pane expanded and the "Edit" CTA clicked:

#### Optimize Container ID
- Validate that the text inout field labelled "Your Optimize Container ID" continues to accept text as per prior versions, and that any applicable helper text remains present as per prior versions.

#### AMP Experimental Settings 
- Ensure that the AMP plugin is installed, activated and configured
- Within the Google Optimize settings pane under Site Kit > Settings, validate that - when editing the settings - the textarea input field labelled "Please input your AMP experiment settings in JSON format below" is visible, continues to accept text as per prior versions, and that any applicable helper text remains present as per prior versions, i.e entering non JSON formatted string should render the same HelperText warning as prior, etc.

### Google Tag Manager Module
The fields that follow can be accessed via Site Kite > Settings with the Tag Manager pane expanded and the "Edit" CTA clicked:

#### Container Name
- Select the "Set up a new container" option within the "Web Container" select element.
- Validate that the text input field labelled "Web Container Name" continues to accept text as per prior versions, and that any applicable helper text remains present as per prior versions.
- Select the "Set up a new container" option within the "AMP Container" select element.
- Validate that the text input field labelled "AMP Container Name" continues to accept text as per prior versions, and that any applicable helper text remains present as per prior versions.

#### StoryBook Stories
- View the `Account Chooser` story and validate that text input fields labelled "Google Account Email" and "Destination URL" continued to render as expected.

## Changelog entry

* Replace direct usage of components from `@material/react-text-field` with the new `TextField` component.

**Comment by bethanylang** [comment]
@techanvil I'd like to get this issue into Sprint 103, starting June 5. Could you please work on the definition? TY!

**Comment by techanvil** [comment]
I've estimated this as a 19, because, while I think the coding work of migrating the components should be relatively straightforward, I think there could be some complexity in determining how to test some of the scenarios, during development and for QA.

**Comment by tofumatt** [comment]
IB ✅

**Comment by 10upsimon** [comment]
@techanvil @nfmohit  while refactoring, I came across 3 scenarios that result in invalid PropType passed to the refactored gm2 TextField component:

1. For the `helperText` prop, it was confined to `PropTypes.string`. This caused scenarios to fail where use values chained to bool checks to pass to the component, i.e `<TextField helperText={ condition && { value } }`. 
2. For the `trailingIcon` prop, the same problem applied as above.
3. For the `value` prop, we are constraining this to `PropTypes.string`, which failed one or two tests where a numerical value was passed to the `value` prop.

My solution to the above is as follows:

1. For `helperText` I've updated prop types to be `PropTypes.oneOfType( [ PropTypes.bool, PropTypes.string ] )` to satisfy existing implementations where values are chained to bool checks.
2. For `trailingIcon` I've done the same as the above.
3. For `value` I've updated it to be `PropTypes.oneOfType( [ PropTypes.string, PropTypes.number ] )`. I did not think it was wise to find all existing instances of numerical values (or potential numerical values, including js tests) and cast to string when passing a value to the `value` prop. 

Please let me know if your'e on board with the approaches I've taken.

Thanks!

**Comment by 10upsimon** [comment]
@techanvil (cc @nfmohit ) another issue I noticed was that the IB mentions the following:

> Notably, we can ignore the following old TextField props: `floatingLabelClassName`, `disabled`, and `required`.

While this is true for `floatingLabelClassName` and `required`, it does not appear to be the case for `disabled`, which is still implemented in the gm2 version of `<TextField>` and is used in practice in a few places where we use this component.

**Comment by 10upsimon** [comment]
@techanvil @nfmohit apologies for the slurry of pings. I also noticed, while refactoring, that `<UserInputKeywords>` does not appear to be used in the app at all. 

https://github.com/google/site-kit-wp/blob/develop/assets/js/components/user-input/UserInputKeywords.js

**Comment by techanvil** [comment]
Hi @10upsimon, thanks for highlighting these issues with the proposed PropTypes. Your suggested solution in your [first comment](https://github.com/google/site-kit-wp/issues/6651#issuecomment-1611306914) makes sense and LGTM.

With regard to `disabled`, as can be seen in the [docs](https://github.com/material-components/material-components-web-react/tree/v0.15.0/packages/text-field#props) (and digging in the [source](https://github.com/material-components/material-components-web-react/blob/v0.15.0/packages/text-field/index.tsx) although it's not the most obvious), `disabled` is a prop for the `Input` component rather than `TextField` and as such any usage passing it to `TextField` appears to simply be a mistake in our code with no effect. This was alluded to in the IB for the predecessor issue, https://github.com/google/site-kit-wp/issues/6113.

With regard to `UserInputKeywords`, as discussed on Slack removing this is also a good shout, it's always good to spot and remove dead code, nice one :)

**Comment by 10upsimon** [comment]
I'm investigating 2 failed JS tests before I mark [the PR](https://github.com/google/site-kit-wp/pull/7225) ready for review.

**Comment by 10upsimon** [comment]
Tests are passing (Snapshots needed updating) and issue is ready for CR.

**Comment by 10upsimon** [comment]
Moving this back into execution following an internal conversation with @techanvil where it was noticed (by Tom) that the import for `<TextField>` is incorrect, and that the component should be imported from `googlesitekit-components` as opposed to `googlesitekit-components-gm2` as it currently is.

This was not inherently clear from the IB for this ticket, but is considered a small fix.

**Comment by techanvil** [comment]
Hey @10upsimon, code-wise this is looking good, however I had imagined that we'd do a thorough regression test for QA - which is why the estimate is quite high, as mentioned in this [comment](https://github.com/google/site-kit-wp/issues/6651#issuecomment-1571844739) above.

In order to facilitate this the QAB would need more detail so as to inform the QA team how to view each of the `TextField` instances. I realise this is a bit of an ask with you being relatively new to the plugin, so please let me know your thoughts on this. Maybe you could do a bit of discovery to determine how to view them, but if a particular instance starts taking too long, drop me a line and I can see if I can figure it out...

On the other hand, if you think we should take another tack with regard to the QA for this issue, I'm open to suggestion. We have at times settled for code review without the regression test for wide-ranging refactor-style changes that shouldn't actually change any behaviour, when they simply touched so many places in the code that the prospect of a regression test seemed a bit unrealistic. There's no clear line as to when one or the other applies; this one feels like it should be fully testable, but I could be convinced otherwise. Anyhow, interested to hear your thoughts.

**Comment by 10upsimon** [comment]
Thank you @techanvil , as per out internal comms I will take a stab at updating the QAB with 2x definitions for now and seek feedback following that.

**Comment by 10upsimon** [comment]
@techanvil please see updated "QA Brief" section in the issue description, where I've taken a far more verbose approach to fleshing out testing/regression testing instructions. There are, however 3x TBA/TBC sections that I've explicitly called out as such given that i am unsure how to arrive at screens where those changes will be visible, even though I've tried my best to add instruction without actually seeing them. They are:

1. Legacy Setup Screens > Search Console
2. Legacy Setup Screens > Site Verification
3. Triggering  Surveys for single question select, multi question select and open question(s)

**Comment by techanvil** [comment]
Hi @10upsimon, great work here on digging in and expanding on the QA Brief. Hopefully the discovery process was useful to you in exploring the plugin behaviour as well as the task in hand of drafting the QAB.

As discussed on Slack and in the standup, we can take the direction here of QAing a representative sample of the `TextFields` in situ, and rely on the CR process to give us the assurance that the remaining (and indeed all) `TextField` instances have been updated in a correct and consistent manner. Given that I've already picked this up for CR, when you assign it back over to me I'll be sure to bear this in mind and give it another once-over for the review.

Seeing as you've documented the lower hanging fruit in the QAB, I think we should be fine to leave these as the "representative sample" (possibly going beyond just this sample but there's absolutely no harm in more QA coverage than less), and I'll leave this with you to update the QAB, I think simply removing the "Legacy Setup Screens" and "Surveys" sections would be fine.

**Comment by 10upsimon** [comment]
Thanks @techanvil I will remove them, and state when handing back for code review that we need to take a QA Eng approach via CR for the ones we can not reach. Appreciate your eyes on this.

**Comment by 10upsimon** [comment]
This is ready for code review again (cc @techanvil, not to say it'll specifically be you). 

I've updated the QAB to remove the references to legacy set up screens and survey questions as part of the instructions, so these areas will need to be QA'd via code review, specifically the `<TextField>` components at the following locations within the PR, as they are unreachable (or overly convoluted to become reachable) via QA steps:

- https://github.com/google/site-kit-wp/pull/7225/files#diff-881455ca2c6fa5193ea8599e0b2bd779492e53ddc2b1c6c78df759956d337239
- https://github.com/google/site-kit-wp/pull/7225/files#diff-dd2b1aa12250db223af3d04047074d2e39e53da43e99d0b9ac3f3f1f717b2beb
- https://github.com/google/site-kit-wp/pull/7225/files#diff-64e209e31e05be30452cb1f02af62a100daf52da612d560515ede3f00a95dede
- https://github.com/google/site-kit-wp/pull/7225/files#diff-1e647cdbb1493fc3b31e4e9c035a25a8cf226a04800255bc4f707ea7c03af7db
- https://github.com/google/site-kit-wp/pull/7225/files#diff-328e88e94b385c950be7cbf482219e1998113e4ba5364e6895c6c656e37aa8fc

**Comment by techanvil** [comment]
Thanks @10upsimon! I had already started the CR process with this one, so it does make sense to assign back to me in this case, which I'll do now.

**Comment by techanvil** [comment]
I'm moving this over to QA, having verified the correctness of the `TextField` migration in CR, and giving the instances explicitly mention by @10upsimon [above](https://github.com/google/site-kit-wp/issues/6651#issuecomment-1630509900) an extra once-over. All LGTM.

**Comment by aaemnnosttv** [comment]
### ❌ Approval

There is one remaining instance of direct usage here in Storybook https://github.com/google/site-kit-wp/blob/ca18cf044319a2ff8c0091b1c83b2ffc974acd72/stories/accountchooser.stories.js#L22

This isn't critical and doesn't affect the release but doesn't fulfill the AC.

**Comment by techanvil** [comment]
Good spot @aaemnnosttv! :eagle: :eyes:

**Comment by 10upsimon** [comment]
@aaemnnosttv @techanvil I've [opened a new PR](https://github.com/google/site-kit-wp/pull/7372) against `main` as per @aaemnnosttv 's comms in Slack. I am unsure whether this needs to be instantly reassigned to @aaemnnosttv or not?

**Comment by techanvil** [comment]
Thanks @10upsimon, this doesn't need to go back to @aaemnnosttv, as mentioned on Slack any merge reviewer would do at this point in the sprint - I did the first review so am well placed to tackle the followup.

**Comment by techanvil** [comment]
As the user-facing side of this issue has already been QA'd, having merged the followup which only affects the `AccountChooser` story I can confirm:

- There is no more usage of `@material/react-text-field` in the codebase beyond what's expected:

![image](https://github.com/google/site-kit-wp/assets/18395600/72010e11-ebf1-4fee-b492-8fa94d9a2a9c)

- The `AccountChooser` story works as expected:

![image](https://github.com/google/site-kit-wp/assets/18395600/98129518-5406-4b3f-af87-32ebad2055af)

Therefore, moving this back to Approval.
