### ISSUE TITLE
Move the `Select` component to `googlesitekit-components-gm2` once `@material/web` `Select` component is available.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6653]
## Feature Description

The `@material/web` package has got a `Select` component listed on its [Roadmap](https://github.com/material-components/material-web#roadmap), however at the time of writing it's not yet present to examine in the repo. Hopefully we'll be able to use this `Select` component for the GM3 implementation in place of the [`Select`](https://github.com/google/site-kit-wp/blob/d030a4940d0fa1316a2fd9c0d05139db43d6ee64/assets/js/material-components/index.js#L42) we currently use from `@material/react-select`. As such this `@material/react-select` version of `Select` should be added to `googlesitekit-components-gm2` once it's confirmed we'll be able to use the `@material/web` component.

Otherwise, we'll need to determine what to do about our usage of `Select`, and possibly map it to `Menu` instead.

This issue can be fleshed out once there is more information on the `@material/web` `Select` component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Select` and `Option` components from `@material/react-select` should be moved from `assets/js/material-components.js` into the `googlesitekit-components-gm2` module, and then re-exported from the `googlesitekit-components` module.
* Stubs for the GM3 versions of `Select` and `Option` should be created and exported from the `googlesitekit-components-gm3` module.

## Implementation Brief

* Move the `Select` and `Option` components from where they are exported in `assets/js/material-components/index.js` to export them instead from `assets/js/googlesitekit/components-gm2/index.js`.
* Re-export them from `assets/js/googlesitekit-components-gm2.js`.
* Within the `assets/js/googlesitekit/components-gm3` directory, create stub `Select` and `Option` components that just render `null`.
* Export these components from `assets/js/googlesitekit/components-gm3/index.js`.
* Re-export them from `assets/js/googlesitekit-components-gm3.js`.
* Update all the existing usage of `Select` and `Option` to import them from `googlesitekit-components` instead of `material-components.js`.
  * At the time of writing, they are used in 20 files:
    * `assets/js/components/dashboard-sharing/DashboardSharingSettings/Module.js`
    * `assets/js/components/legacy-setup/search-console.js`
    * `assets/js/modules/adsense/components/common/AccountSelect.js`
    * `assets/js/modules/adsense/components/common/WebStoriesAdUnitSelect.js`
    * `assets/js/modules/analytics-4/components/common/PropertySelect.js`
    * `assets/js/modules/analytics-4/components/common/WebDataStreamSelect.js`
    * `assets/js/modules/analytics/components/common/AccountCreate/CountrySelect.js`
    * `assets/js/modules/analytics/components/common/AccountCreate/TimezoneSelect.js`
    * `assets/js/modules/analytics/components/common/AccountSelect.js`
    * `assets/js/modules/analytics/components/common/ProfileSelect.js`
    * `assets/js/modules/analytics/components/common/PropertySelect.js`
    * `assets/js/modules/analytics/components/common/PropertySelectIncludingGA4.js`
    * `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/DimensionTabs.js`
    * `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/DimensionTabs.js`
    * `assets/js/modules/search-console/components/common/PropertySelect.js`
    * `assets/js/modules/tagmanager/components/common/AccountSelect.js`
    * `assets/js/modules/tagmanager/components/common/AMPContainerSelect.js`
    * `assets/js/modules/tagmanager/components/common/ContainerSelect.js`
    * `assets/js/modules/tagmanager/components/common/WebContainerSelect.js`
    * `stories/select.stories.js`

### Test Coverage

* Existing tests should continue to pass.

## QA Brief

- Perform a regression test of all the different instances of the `Select` component. These should be visually and behaviourally unchanged.
- You can start from the `Global > Selects` Storybook story.
- The `Select` component can be found used in almost all the setup & setting screens for Site Kit modules, for example:
  - Account select
  - Property select
  - Profile Select
  - Analytics account creation flow > Country select & Timezone select
  - Tag Manager container select.
  - Dashboard Sharing Settings Modal > `Who can manage view access` select
  - Site Kit Dashboard All Traffic Widget dimension tabs select in mobile screen
  <details>
    <summary>Screenshot</summary>

    ![image](https://github.com/google/site-kit-wp/assets/20284937/b973ca35-b10e-4da3-b206-bc6cfb133964)

  </details>

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@techanvil the library now has components for `Tab` and `Tabs` (likely the replacement for `TabBar`?). See https://github.com/material-components/material-web/tree/main/tabs

**Comment by techanvil** [comment]
Again, the coding here should be quite straightforward but regression testing for dev & QA could be more time consuming, hence the 15 estimate.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified all instances of Select component. Select component is working as expected.
- Also verified storybook story Global> Select.
