### ISSUE TITLE
Move the `Tab` and `TabBar` components to `googlesitekit-components-gm2` once corresponding `@material/web` components are available.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6654]
## Feature Description

The `@material/web` package has got a `Tabs` component listed on its [Roadmap](https://github.com/material-components/material-web#roadmap), however at the time of writing it's not yet present to examine in the repo. We should be able to use this as the GM3 implementation in place of [`Tab` and `TabBar`](https://github.com/google/site-kit-wp/blob/d030a4940d0fa1316a2fd9c0d05139db43d6ee64/assets/js/components/DeviceSizeTabBar.js#L22-L23) . However it's not clear if there will be a direct mapping from `Tab` / `TabBar` to the `@material/web` `Tabs` component(s). It's expected that we'll need to move `Tab` / `TabBar` to `googlesitekit-components-gm2` although it's possible we may need to create some sort of wrapper component(s) or suchlike.

This issue can be fleshed out once there is more information on the `@material/web` `Tabs` component(s).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* The `Tab` and `TabBar` components from `@material/react-tab` / `@material/react-tab-bar` should be exported from the `googlesitekit-components-gm2` module, and then re-exported from the `googlesitekit-components` module.
* All existing usage of these components should be updated to import them from `googlesitekit-components`.
* Stubs for the GM3 versions of `Tab` and `TabBar` should be created and exported from the `googlesitekit-components-gm3` module.

## Implementation Brief

* Export the `Tab` and `TabBar` components referred to in the AC from `assets/js/googlesitekit/components-gm2/index.js`.
* Re-export them from `assets/js/googlesitekit-components-gm2.js`.
* Within the `assets/js/googlesitekit/components-gm3` directory, create stub `Tab` and `TabBar` components that just render `null`.
* Export these components from `assets/js/googlesitekit/components-gm3/index.js`.
* Re-export them from `assets/js/googlesitekit-components-gm3.js`.
* Update all the existing usage of `Tab` and `TabBar` to import them from `googlesitekit-components` instead of directly from `@material/react-tab` / `@material/react-tab-bar`.
  * At the time of writing, they are used in 6 files:
    * `assets/js/components/DeviceSizeTabBar.js`
    * `assets/js/components/settings/SettingsApp.js`
    * `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetDimensionTabs.js`
    * `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4DimensionTabs.js`
    * `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js`
    * `stories/settings.stories.js`

### Test Coverage

* Existing tests should continue to pass.

## QA Brief

* Perform a smoke test in the following areas of the dashboard where `Tab` and `TabBar` is used. There should be no change in behavior or regression. 
    * PageSpeed Inside report.
    * Analytics All Traffic widget.
    * Site Kit Settings (Main page, with the connected services, connect more services, admin settings).

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@techanvil the library now has components for `Tab` and `Tabs` (likely the replacement for `TabBar`?). See https://github.com/material-components/material-web/tree/main/tabs

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Confirmed that the elements where `Tab` and `TabBar` are used still continues to work as expected. 

Tested on desktop and mobile:

- PageSpeed Inside report.
- Analytics All Traffic widget.
- Site Kit Settings

<details>
 <summary>Screencasts</summary>

https://github.com/google/site-kit-wp/assets/73545194/daacdd9a-8dda-457f-bae3-34373c6e510f

https://github.com/google/site-kit-wp/assets/73545194/5734645b-571b-49a8-acbf-2f3cc7f8b160

</details>
