### ISSUE TITLE
Add contrast to Admin Bar dropdown to distinguish our content from the website design

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6659]
## Bug Description

A minor UX/UI enhancement suggestion.   When a user clicks on the Site Kit icon on the admin bar on the front end, our page stats appear. In some scenarios the  ‘more details’ link looks lost, and from first glance could be part of the website, rather than a Site Kit CTA link.  I feel a simple solution would be to include a shadow or border at the bottom to distinguish between page stats and the actual website.

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/fc9fc223-e05d-4f12-a718-73c0d0aaac88)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The SK admin bar dropdown should have the same shadow as other Site Kit dropdowns (e.g. user menu)

## Implementation Brief

- In `assets/sass/components/adminbar/_googlesitekit-adminbar.scss`:
  - Update the styles for `#wpadminbar .googlesitekit-plugin .googlesitekit-adminbar` to use the `elevation-3` mixin, which applies the shadow.

### Test Coverage

* Update any VRT references if required.

## QA Brief

* Setup Site Kit
* Go to the website homepage, or any other page/post on the Frontend
* Hover over the `Site Kit` in the admin top menu bar
* Verify that dropdown has a shadow at the bottom

## Changelog entry

* Add contrast to the Admin Bar dropdown.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- The Site Kit Admin bar dropdown has a shadow at the bottom. 
- Tested on desktop and smaller viewports. 
- Tested on a few popular themes for any UX/UI issues. 
- Tested with Analytics not connected and also on gathering and zero data states

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/fb399dbe-f13c-4088-82e6-26ba810f8782)
![image](https://github.com/google/site-kit-wp/assets/73545194/69b5c8b4-9104-4994-85c1-0bd8f8ff3268)
![image](https://github.com/google/site-kit-wp/assets/73545194/c59e02b1-5215-4c32-a253-6b16b6f6a6af)
![image](https://github.com/google/site-kit-wp/assets/73545194/a98006eb-fac7-4c37-8f72-29f5d6e02b81)

</details>

**Note:** I did spot an issue with the layout of the admin bar data on mobile, but I will create a ticket for this as its not a regression from this ticket.
