### ISSUE TITLE
Unexpected warning messages appearing in the GA event data

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6660]
## Bug Description

While release testing, I noticed that we had a number of warnings within the GA event data when tracking was enabled. 

I haven't gone through every GA event but when initially setting up Site Kit two warnings appeared consistently through the logs.

`Ignoring create request for duplicate tracking name`
`​Expected a string value for field: "dimension7". but found: "number"`

![image](https://user-images.githubusercontent.com/73545194/222167804-9096d319-d2ee-471a-a3c1-dee81bb95373.png)

## Steps to reproduce

1. Check the tracking field on the splash page to set up Site Kit. 
2. Turn on the GA debugging extension 
3. Within the browser console set for info messages to appear
4. Start to set up Site Kit and observe errors above. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All custom dimension values passed as part of Site Kit's internal event tracking should be strings

## Implementation Brief

* Cast the value of `dimension7` to a string before sending https://github.com/google/site-kit-wp/blob/54c940b252cd03687ad4320667ec66a0dec9769e/assets/js/util/tracking/createTrackEvent.js#L68
* The "Ignoring create request for duplicate tracking name." warning [seems to be normal](https://stackoverflow.com/a/54407839/1037938) but not much information about it 

### Test Coverage

* 

## QA Brief

- Follow the **Steps to reproduce** in issue description.
- Verify that the `​Expected a string value for field: "dimension7". but found: "number"` warning doesn't occur anymore.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
@wpdarren Are you getting reported error on latest environment. I created 2 new sites without enabling any feature flag and I'm not getting reported error under info messages.

**Comment by wpdarren** [comment]
@mohitwp  I see it on the latest environment.   As soon as I click on the `Help us improve Site Kit by sharing anonymous usage data.` checkbox the error message appears in the GA events log.  I checked on a new site and also a reset site that is connected to oi.ie and the same occurs.  Let me know if you'd like to sync. 

![image](https://github.com/google/site-kit-wp/assets/73545194/2888ffd3-a3f9-44a3-96fb-14fb05ac291f)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Able to reproduce issue on latest environment.
- Verified that on dev environment, the `​Expected a string value for field: "dimension7". but found: "number"` warning doesn't occur anymore.
- Tested set up flow site kit with Analytics.

<details>

https://github.com/google/site-kit-wp/assets/94359491/aff637cf-7535-4d02-a9ec-8454155d97ce

</details>
