### ISSUE TITLE
Add padding or an icon to the Update Notification to keep styling consistent

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6661]
## Bug Description

The Auto Update notification (and possibly others) don't have an icon and don't use a grid container as others do (using the `mdc-layout-grid__cell--span-1` class). This results in inconsistency when there is this notice and an error are displayed at the same time, as highlighted below:

<kbd> ![image](https://user-images.githubusercontent.com/41326532/222197763-639403b1-9ffb-4aef-ad11-bd0a721f1964.png)

To keep this consistent with other notices, considering keeping one grid item in place, as is the case with the permissions error seen below, or add an update icon that fills this space:

<kbd> ![image](https://user-images.githubusercontent.com/41326532/222192939-642d77a6-f034-4a28-8323-66c12af6f8fd.png)

Other notices, such as the "Gathering data" notice do have an icon that appears more in line with errors that appear below it. 

<kbd>![image](https://user-images.githubusercontent.com/41326532/222194166-c4b008c9-6d46-4467-8ed2-3c67ea45b31f.png)

## Steps to reproduce

1. Spin up a new site on TasteWP or InstapWP 
2. Install SK and don't apply Auto updates
3. Set up the plugin and press the cancel button during OAuth (don't grant permissions)
4. A notice regarding auto updates appears, as well as the error regarding not granting permissions

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of #5447
