### ISSUE TITLE
Revise wording after not granting permissions

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6662]
## Bug Description

If a user presses the "Cancel" button at the OAuth stage whether setting up Site Kit or when connecting a module, they're directed back to the Site Kit dashboard with the following notice:

```
Error connecting Site Kit
The Site Kit setup was interrupted because you did not grant the necessary permissions. [Get help](https://sitekit.withgoogle.com/support?error_id=access_denied)
```

<kbd> ![image](https://user-images.githubusercontent.com/41326532/222202934-5ccebb19-4cde-4630-b9f4-25c8931aabe4.png)

In the case of setting up Site Kit the above is correct, but in the case of connecting a module, this isn't correct. A user is not "connecting Site Kit", and it's not specifically Site Kit setup that was interrupted. 

Consider changing the wording to account for both possibilities (1. setting up Site Kit 2. connecting a module) or consider changing the wording to the below, to make it more applicable to both scenarios:

~~Error connecting Site Kit~~ **Permissions Error**
~~The Site Kit~~ Setup was interrupted because you did not grant the necessary permissions. [Get help](https://sitekit.withgoogle.com/support?error_id=access_denied)
Redo ~~the plugin~~ setup

## Steps to reproduce

1. Set up Site Kit
2. Connect the Tag Manager module, but press the Cancel button during OAuth
3. You'll land back on the Site Kit dashboard with the notice indicating you need to set up Site Kit once more. This isn't the case, you just need to connect the module once more

## Screenshots

The recording below shows an example of the UX if following the steps to recreate above:

https://user-images.githubusercontent.com/41326532/222202586-cdd8a74f-9699-44be-a0d2-e09b3ed20442.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the user cancels granting additional scopes or scopes required for a module setup, the error notification that that user sees after redirecting back to the dashboard page has the following language:
  * Title: `Permissions Error`
  * Description: `Setup was interrupted because you did not grant the necessary permissions.`
  * CTA button: `Redo setup`

## Implementation Brief

* In the `assets/js/components/notifications/ErrorNotifications.js` file:
  * Create a new variable `title` and assign the current banner notification title to it. If the `setupErrorCode` variable equals to `access_denied`, then change the `title` to `Permissions Error`.
  * Create a new variable `ctaLabel` and assign the current banner notification CTA label to it. If the `setupErrorCode` variable equals to `access_denied`, then change the `ctaLabel` variable to `Redo setup`.
  * Update the `BannerNotification` element to use new `title` and `ctaLabel` for corresponding properties.
* In the `includes/Core/Authentication/Clients/OAuth_Client_Base.php` file:
  * Update the `get_error_message` method to have the language for the `access_denied` case as defined in AC.

### Test Coverage

* N/A

## QA Brief

* Reset the site kit if you already connected
* Connect site kit 
* Go to `Settings -> Connect more services`
* Click connect to google tag service (if you have connected previously, setup sitekit without connecting to analytics first)
* When google permissions dialog appear click cancel (follow the video attached to the ticket above)
* Verify that permission error notice showing in the dashboard after redirection matches the one in AC

## Changelog entry

* Improve wording for permission errors to be consistent while setting up Site Kit or a module.

**Comment by aaemnnosttv** [comment]
@marrrmarrr the AC has used the proposed changes above – what do you think?

**Comment by marrrmarrr** [comment]
@aaemnnosttv @jamesozzie this phrasing SGTM, thanks for catching this and for suggesting alternative copy.

**Comment by zutigrm** [comment]
IB is still valid

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified If the user cancels granting additional scopes or scopes required for a module setup, the error notification that that user sees after redirecting back to the dashboard page has the following language:

```
Title: Permissions Error
Description: Setup was interrupted because you did not grant the necessary permissions.
CTA button: Redo setup
```


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/12668feb-b00f-4c74-896a-6f8a20a0e7f6)


https://github.com/google/site-kit-wp/assets/94359491/89d687c3-35a1-4d92-9608-e94b3b411c9e

</details>
