### ISSUE TITLE
Upgrade ESLint to latest

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6663]
## Feature Description

We currently use ESLint v7 but not the latest version. Because of this, an older version of lodash is installed. See https://github.com/google/site-kit-wp/security/dependabot/34

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* ESLint should be upgraded to the latest 7.x version (currently 7.32.0)

## Implementation Brief

* Upgrade `eslint` to `^7.32.0`

### Test Coverage

* No changes

## QA Brief

* This only affects development tooling, so no additional QA should be necessary. We mainly need to ensure ESLint checks run as expected after upgrading, which should be observable in CR

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
@aaemnnosttv should this be labelled 1.96.0? 🤔
