### ISSUE TITLE
Update Analytics opt-out to use Google tag if set

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6666]
## Feature Description

Both UA and GA4 Analytics leverage the property-specific opt-out mechanism (see #3294) which is primarily controlled by the "Exclude Analytics" settings.

For Analytics 4, this has always used the configured measurement ID, however with the addition of a Google Tag which is preferred over a specific measurement ID (see #6080), the opt out code is currently not consistent with the Google tag used in the snippet.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tag ID used in the Analytics opt-out snippet should always match the tag ID used in the tag snippet

Note: this primarily targets GA4 but overall applies to both

## Implementation Brief

* In `Google\Site_Kit\Modules\Analytics_4` class:
    * Create a private method `get_tag_id`.
        * If the `gteSupport` feature flag is enabled _and_ `$settings['googleTagID']` is non-empty, it should return `$settings['googleTagID']`.
        * Otherwise, it should return `$settings['measurementID']`.
    * In `register_tag` method:
        * pass the value of newly added `get_tag_id()` while constructing the `Web_Tag`. 
    * In `analytics_tracking_opt_out` method:
        * Pass the value of newly added `get_tag_id` to the `wp_print_inline_script_tag` function. 

### Test Coverage

* Add coverage for the newly added function and `gteSupport` related opt out behavior.
* Update any failing tests.

## QA Brief

* Ensure the `gteSupport` feature flag is enabled. 
* Configure GA4 with google tag. 
* While logged in, check the page source for opt out snippet (Find `Google Analytics opt-out snippet added by Site Kit`) and make sure it contains the configured google tag ID.
* With the feature flag still enabled, configure GA4 without GTE and make sure the opt out snippet correctly falls back to measurement ID. 

## Changelog entry

* Update the Analytics 4 module to use Google Tag for tracking if it is available.

**Comment by bethanylang** [comment]
Changed to a P0 per all other GTE Support issues.

**Comment by techanvil** [comment]
@kuasha420 the IB looks good, I have made a small tweak to accommodate the requirements to fall back to the `measurementID` if `googleTagID` is empty as per #6080.

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

_With the `gteSupport` feature flag enabled and configure GA4 with google tag._
- The opt out snippet contains the configured google tag ID.

_With the `gteSupport` feature flag enabled and no GA4 with google tag._
- The opt out snippet correctly falls back to measurement ID.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/223285633-f741f207-7a71-4bd7-b4ee-7595edf0e102.png)
![image](https://user-images.githubusercontent.com/73545194/223285661-c2c738ad-646f-4766-a590-233ab719ca67.png)

</details>
