### ISSUE TITLE
Remove old Cron cleanup

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#667]
## Feature Description

We've had some lines to clean up old Cron jobs in the plugin for a while now. Let's remove them before launch (they're both marked with `TODO`).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There must be no code references to the old Cron jobs in the codebase.

## Implementation Brief

* Remove https://github.com/google/site-kit-wp/blob/510250c6afc2fce73834ae1635f771f4fe2484a6/includes/Core/Util/Deactivation.php#L31-L33
* Remove https://github.com/google/site-kit-wp/blob/510250c6afc2fce73834ae1635f771f4fe2484a6/includes/Plugin.php#L127-L129

I'm unclear if we also want to remove some tests that _seem_ like they're related, but they might not be and aren't marked with `// TODO`:

https://github.com/google/site-kit-wp/blob/510250c6afc2fce73834ae1635f771f4fe2484a6/tests/phpunit/integration/Core/Util/DeactivationTest.php#L25-L26

and

https://github.com/google/site-kit-wp/blob/510250c6afc2fce73834ae1635f771f4fe2484a6/tests/phpunit/integration/PluginTest.php#L71-L73

I can't tell if those last two relate to newer code or not. I suppose if they are they'd fail when the code is removed, so if they fail they should be removed as well.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@tofumatt IB ✅ 
Yes, those tests should be removed as well.

**Comment by aaemnnosttv** [comment]
@felixarntz there's a question for you regarding whether or not we should keep the `Deactivation` class around now that it's not registering/doing anything.

See https://github.com/google/site-kit-wp/pull/681#pullrequestreview-305111114

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt Let's remove the class then 👍

**Comment by aaemnnosttv** [comment]
### QA ✅ 

AC
> There must be no code references to the old Cron jobs in the codebase.

There is no longer any reference to any Site Kit cron events 👍 

Moving to Approval
