### ISSUE TITLE
Provide CallBack to Show PageView in Frontend

### ISSUE THREAD

**Issue by ghost** [google/site-kit-wp#6670]
## Feature Description

Can we have a js callback that can show pageview on the front end on the User, Like a widget?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Hi there and thanks for the request! This has been requested previously and is currently out of scope for the plugin. See #1093
