### ISSUE TITLE
Make the banners for the unsatisfied scopes alerts remain there until oAuth appears

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6673]
## Bug Description

While testing #6421 I had an observation.

> When I click on the grant permissions button, for 2-3 seconds the dashboard re-appears and then the oAuth pops up. Feels an odd user experience. I have fast internet connection but for slower connections it will feel a little longer before the user is asked to give permission. Is this expected? Screencast below.
> 
> https://user-images.githubusercontent.com/73545194/222022442-81504cee-f190-4e5c-8707-fceb74c8b8b3.mp4

Felix responded:

> Agreed that this is a general problem and therefore shouldn't be a blocker here specifically. We had this problem with some other banner in the past though, and we should fix it, essentially we have to ensure that the banner remains there for that current page load, even once it's technically been dismissed. Let's open a new issue to fix this for the unsatisfied scopes alert in general indeed. 

Hopefully this provides enough information for the issue, but in short, for the unsatisfied scopes alerts, we should make sure that the banner remains there until the oAuth appears. 

## Steps to reproduce

1. Ensure the `gteSupport` feature flag is disabled and setup Site Kit with Analytics. 
2. Now enable the gteSupport feature flag and verify the UnsatisfiedScopesAlert appears.
3. Click on the grant permission CTA button and see behaviour detailed above.  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Clicking on the CTA of a `UnsatisfiedScopesAlert` should not immediately dismiss the banner.
* Instead the banner should remain there while the user is taken to the oAuth flow. 
* To convey to the user that they're being navigated away, the CTA button should be disabled once clicked and a loading spinner should appear besides it. 

## Implementation Brief

- In `assets/js/components/notifications/UnsatisfiedScopesAlert.js`:
  - Among the conditions that make the component return `null`, remove the `isNavigating` condition.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Follow the steps to reproduce 
* Check the banner does not disappear now

### QA Update

- For the followup PR, ensure the Unsatisfied Scopes banner does not appear when clicking on the link to setup a module from the Settings page, as described here: https://github.com/google/site-kit-wp/issues/6673#issuecomment-1551241196.

## Changelog entry

* Ensure the Unsatisfied Scopes banner remains visible until the OAuth page appears when pressing the banner CTA.

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Clicking on the CTA of a `UnsatisfiedScopesAlert` does not immediately dismiss the banner, instead the banner remains there while the user is taken to the oAuth flow.  The CTA button is disabled once clicked and a loading spinner appears 

I tested this with `GA4Reporting` feature flag enabled and disabled. 

Wanted to reference that the permission popup does appear when GA4 is enabled but #6977 will fix this issue. 

https://user-images.githubusercontent.com/73545194/236208334-8f686192-92b0-4a4a-8800-9fbe73b14ed6.mp4

**Comment by wpdarren** [comment]
### QA Update: ❌ 

I’ve just been “playing around” with my live site and looking to set up AdSense on it.   I am on the `main` branch, and I am seeing a banner appear saying “Site Kit can’t access necessary data” and after 4-5 seconds it redirects me to the oAuth.  I wasn’t expecting to see the banner there when I am setting it up like any other module.   

After some digging it appears to be an issue when you have a Google account that has an approved AdSense account, but the site isn't set up or approved yet. 

**Update:** Tom mentioned in Slack that it appears to be an issue for Analytics and Tag Manager too, so a general issue and not specific to AdSense. 

[Conversation on Slack with @techanvil for reference.](https://10up.slack.com/archives/CBKKQEBR9/p1684318615337199) 

Here’s a screencast.

https://github.com/google/site-kit-wp/assets/73545194/b55078eb-cb5f-44d3-8b42-04d49fd6babe

**Comment by aaemnnosttv** [comment]
@techanvil I've opened a PR for an alternate solution in https://github.com/google/site-kit-wp/pull/7058 which seems to cover all the bases while remaining contained within the `UnsatisfiedScopesAlert*` components. Would you please have a look?

**Comment by techanvil** [comment]
> @techanvil I've opened a PR for an alternate solution in #7058 which seems to cover all the bases while remaining contained within the `UnsatisfiedScopesAlert*` components. Would you please have a look?

Thanks @aaemnnosttv. I had considered something like this, the aspect I don't like so much is that it seems a bit strange when reading the code for the banner, it's not so clear why it's doing the navigation check while ignoring it for its own navigation, and there's no clear relationship between it and the related external code. The approach I had suggested does provide a bit of a clearer link to the scenario where we want to suppress the banner which makes for slightly easier maintenance in one respect.

However, the clear benefit to the approach you have suggested is that it should prevent any other similar regressions. I think the encapsulation angle has both pros and cons to it as alluded to above.

I've made a couple of tweaks - the Promises turned out not to be needed as a result of the `isNavigatingToCTALink` variable in the relevant [condition](https://github.com/google/site-kit-wp/blob/5668847a1c8f6accd85500b9deda7587552bc3d2/assets/js/components/notifications/BannerNotification/index.js#L515-L518) in `BannerNotification`, and updated the comment to provide a bit more context.

I'll merge this now, with it being a release issue, so we can get it back into QA sooner rather than later.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main branch.
- Tested when 'ga4Reporting' feature flag is enabled.
- Tested when both 'ga4Reporting' and 'gteSupport' feature flag is enabled.
- Tested when 'ga4Reporting' feature flag is not enabled.
- Verified that issue reported [above](https://github.com/google/site-kit-wp/issues/6673#issuecomment-1551241196) is resolved now.
- Verified that analytics and AdSense set up is working fine.

<details>


https://github.com/google/site-kit-wp/assets/94359491/260295c0-f176-4a8f-a613-09e0f5eede7e

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
