### ISSUE TITLE
Make `getHeaderHeightWithoutNav()` more robust to avoid errors seen in the wild.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6674]
## Feature Description

Since the release of version 1.95.0 a handful of errors have been reported from installed sites (four at the time of writing).

![sitekit-1-95-0-prod-errors.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/80a0d74d-a36c-4da2-ba15-02929db17c9d)

These evidently relate to the work done via #6109 which was included in this release.

Although it's not been possible to recreate these issues in our testing we should add some defensive logic to `getHeaderHeightWithoutNav()` to prevent these errors.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `getHeaderHeightWithoutNav()` function should be updated so that it doesn't return anything other than a positive number or zero.
* It should make a best-effort attempt to calculate the correct height for the sticky Site Kit header & WordPress admin bar combination based on the information available.
* It should return zero for any unexpected results.
* Going forward, we should not see any more of these errors in the production logs.

## Implementation Brief

- Improve the [check for header stickiness](https://github.com/google/site-kit-wp/blob/bcb0f4806589faaa2bf2e4c7ccf4849d8db879f7/assets/js/util/scroll.js#L80-L82) by checking the header's `position` style property via `getComputedStyle()`.
- Add some checks to ensure `getHeaderHeightWithoutNav()` cannot return anything but a finite positive integer or `0`.
- Refactor `getHeaderHeightWithoutNav()` to be more readable.
- Add a guard at the point of using the return value of `getHeaderHeightWithoutNav()` as a failsafe - use `Math.abs()`, similar to how it's used in [`WidgetAreaRenderer`](https://github.com/google/site-kit-wp/blob/101ec7c8ed6a136fb3c15309790428a93aaba23e/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L71).
- Rename `getHeaderHeightWithoutNav()` and `getHeaderHeight()` to `getStickyHeaderHeightWithoutNav()` and `getStickyHeaderHeight()` to be more explicit.
- Finish off the PR https://github.com/google/site-kit-wp/pull/6672 which implements the above.

### Test Coverage

- Add some tests for `getStickyHeaderHeightWithoutNav()` and backfill test coverage for `getStickyHeaderHeight()`.

## QA Brief

- The bug described [here](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463652670) should no longer occur.

> I am running through the dashboard navigation tooltip tour and if you click 'back' on the final tip, a fatal error appears.

- Run through the smoke/regression tests described under **Additional QA for followup PR(s)** in https://github.com/google/site-kit-wp/issues/6109.

## Changelog entry

* Fix potential `IntersectionObserver` error in banner notifications.

**Comment by aaemnnosttv** [comment]
IB ✅  Moving forward to CR

**Comment by aaemnnosttv** [comment]
@techanvil I left a review on the PR that I reopened as a draft. Let's use that to inform a new IB, which could involve keeping the same PR (which is now against `develop`) if you'd like. Depending on what direction we take, it might make more sense to start fresh but I'm curious to get your thoughts.

**Comment by techanvil** [comment]
> @techanvil I left a review on the PR that I reopened as a draft. Let's use that to inform a new IB, which could involve keeping the same PR (which is now against `develop`) if you'd like. Depending on what direction we take, it might make more sense to start fresh but I'm curious to get your thoughts.

Thanks @aaemnnosttv, you raised some good points there. I've replied on the PR, and also made the discussed changes. I've also updated the IB - I think it makes sense to continue using this branch considering the amount of detailed discussion that has already taken place on it.

**Comment by aaemnnosttv** [comment]
@techanvil there's a duplicate conflicting section for test coverage – I'll remove the older one.

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Verified errors related to feature tour bug described https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463652670 not appearing now.
- Done additional smoke/regression tests as described under Additional QA for followup PR(s) in https://github.com/google/site-kit-wp/issues/6109.

<details>

https://user-images.githubusercontent.com/94359491/228550375-166164db-10b9-4006-876c-8e3b9ec7fc8c.mp4

</details>
