### ISSUE TITLE
Ensure GA4 widgets can display data on the Shared Dashboard.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6687]
## Feature Description

At present when trying to view a GA4 widget on the Shared Dashboard, the report request returns a permissions error.

This needs to be fixed so the Analytics 4 module is correctly shared along with Analytics.

Having shared Analytics through the Dashboard Sharing Settings modal, and then viewing the Shared Dashboard, this is the result:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/52673546-e62f-4a3e-8d7d-f973840fafb6)
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Analytics module is shared via the Dashboard Sharing Settings modal, the Analytics 4 module should also be shared.
* When Analytics is shared, and viewing a GA4 widget on the Shared Dashboard, the widget should retrieve and display its data correctly.

## Implementation Brief

- The primary problem here for which the missing scope errors is that when an authenticated user shares the Analytics module, only the `analytics` module is set as a shared module in module sharing settings, completely disregarding `analytics-4`. ~~In `includes/Core/Modules/Module_Sharing_Settings.php`:~~
  - ~~Update the `get()` method in such a way so that when returning the module sharing settings, if it has any settings available for the `analytics` module, it should replicate and return the same for `analytics-4`.~~
  - The sharing settings replication is being handled in #6745.
- While the above fixes the missing scopes error, a secondary problem arises where the `Analytics_4` `validate_shared_report_metrics()` and `validate_shared_report_dimensions()` methods do not yet include the allow-listed metrics and dimensions, thus the report request still fails, but this time with an unsupported metric/dimension error. In `includes/Modules/Analytics_4.php`:
  - Update the `validate_shared_report_metrics()` method so that the `$valid_metrics` array is filled with all the metrics that are used with the `GET:report` datapoint in the view-only dashboard.
  - Update the `validate_shared_report_dimensions()` method so that the `$valid_dimensions` array is filled with all the dimensions that are used with the `GET:report` datapoint in the view-only dashboard.

### Test Coverage

- No tests need to be added/updated.
- Fix any failing test.

## QA Brief

* Follow the QAB within 6824 to thoroughly test GA4 widgets for a view-only user using the shared dashboard.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by nfmohit** [comment]
Hi folks!

Even though this issue synchronises the settings between `analytics` and `analytics-4`, the replication is one-way, i.e. `analytics` to `analytics-4`. As a part of #6745, we have a requirement of a two-way replication based on the current dashboard view, i.e. if the site is on GA4 dashboard view, `analytics-4` should be replicated to `analytics`, and vice-versa if the current dashboard view is UA.

In the IB for #6745, I have instructed to remove the replication being introduced here.

Should we skip the replication part in this issue altogether by letting #6745 handle that and set it as a blocker for this issue?

CC: @tofumatt @eugene-manuilov @jimmymadon

**Comment by nfmohit** [comment]
> @nfmohit Thanks - lets handle the replication in one issue. So I'll put this issue on hold if the IB in #6745 is approved and wait till it is merged.

Thank you, @jimmymadon! I've updated the issue dependencies and the IBs for clarification.

**Comment by nfmohit** [comment]
Just a note that `validate_shared_report_metrics()` and `validate_shared_report_dimensions()` in `Analytics_4` were moved to `Modules\Analytics_4\Report\Request` as `validate_shared_metrics()` and `validate_shared_dimensions()` respectively.

CC: @jimmymadon

**Comment by mohitwp** [comment]
### QA Update ❌ 

@jimmymadon 

Issues mentioned on   https://github.com/google/site-kit-wp/issues/6824#issuecomment-1509060061 are more related to this ticket connected PR. As this ticket is related to 6824. Sending this ticket back to execution.
