### ISSUE TITLE
GA4 Widgets: Update "Engaged Sessions" metric name title to read "Engagement rate".

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6693]
## Feature Description

As discussed on Slack, having switched from the `engagedSessions` metric to `engagementRate`, we should also update the relevant titles on the GA4 widgets that use it, from "Engaged Sessions" to "Engagement rate".

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All GA4 widgets that present the `engagementRate` metric should use "Engagement Rate" for the corresponding metric name/column title.

## Implementation Brief

* Using `ModulePopularPagesWidgetGA4`, `extract-dashboard-data.js`, `overall-page-metrics.js`, `SearchFunnelWidgetGA4`:
    * Locate `'Engaged Sessions'` and change it to `'Engagement Rate'`
* In the case of `ModulePopularPagesWidgetGA4` and `SearchFunnelWidgetGA4`, also change the ID from `engaged-sessions` to `engagement-rate`. This isn't part of the ACs but helps with consistency.

### Test Coverage

* No new tests are needed; VRTs might need updating for the new metric title.

## QA Brief

* Enable `ga4Reporting` and check the Widgets mentioned in the AC for the change from `'Engaged Sessions'` to `'Engagement Rate'`.

## Changelog entry

* Update the "Engaged Sessions" metric title to read "Engagement Rate" in the new GA4 widgets.

**Comment by tofumatt** [comment]
All of the existing metrics, as well as metrics in the GA4 Figma mock, use Title Case for their names:

<img width="735" alt="CleanShot 2023-03-07 at 23 39 29" src="https://user-images.githubusercontent.com/90871/223580564-3dffd54f-3bb1-4b00-b0ef-0cc0e9aefcc2.png">
<img width="815" alt="CleanShot 2023-03-07 at 23 39 22" src="https://user-images.githubusercontent.com/90871/223580565-1d051937-c3de-436d-a00e-776f0cd6ca45.png">

I'm guessing "Engagement rate" here was an oversight and not something deliberate; if it wasn't and we want to change the case of these metrics it might be better to do that all at once—it will be confusing having them be inconsistent.

I've adjusted the case in the ACs and IB, and pinged @techanvil just to make sure it wasn't intentional.

IB ✅

**Comment by techanvil** [comment]
Thanks @tofumatt - good spot, it should indeed be "Engagement Rate".

**Comment by techanvil** [comment]
Note that while reviewing the PR for this issue I noticed the `SearchFunnelWidgetGA4` component is still using `engagedSessions` rather than `engagementRate` for the underlying report, and is not displaying Engagement Rate as a percentage in the UI. I have created https://github.com/google/site-kit-wp/issues/6724 to address this.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested widgets on both main and entity dashboard.
- Verified  `ModulePopularPagesWidgetGA4` , `SearchFunnelWidgetGA4` and `DashboardOverallPageMetricesWidgetGA4`.
- Verified- All GA4 widgets that present the engagementRate metric should use "Engagement Rate" for the corresponding metric name/column title.
- Also, tested GA4 components using react developer tool.

**Note -**
1. I've found that on entity dashboard when user clicks on engagement rate and unique visitors from search data then it creates fatal error. I will create a separate issue for this.

<details>

![image](https://user-images.githubusercontent.com/94359491/225286459-98e8d0fc-6f13-4fa2-a3c4-f04bf9508b1e.png)

</details>

2. The Engagement Rate metric is currently shown in the SearchFunnelWidgetGA4 component without the percentage sign. This will resolve in a separate issue - https://github.com/google/site-kit-wp/issues/6724



<details>

![image](https://user-images.githubusercontent.com/94359491/225282763-87bc7f22-b9ef-477d-8a24-db9637994e80.png)

![image](https://user-images.githubusercontent.com/94359491/225282941-f29e4a37-f27d-4218-9bbf-ff10339c3536.png)

![image](https://user-images.githubusercontent.com/94359491/225284251-d2e6a7ce-60ed-4368-a5b4-19043b798eeb.png)

![image](https://user-images.githubusercontent.com/94359491/225283130-342778a7-514a-49d7-9d43-30253671fff1.png)

![image](https://user-images.githubusercontent.com/94359491/225283278-ea250ffb-b58e-4480-af12-ef57675dd894.png)

![image](https://user-images.githubusercontent.com/94359491/225283924-f65eb5ad-dd4b-4488-bbf9-f3c372982cf9.png)

</details>
