### ISSUE TITLE
Update design of notices shown in Site Kit

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6702]
## Feature Description

Currently, the [notices (warning, error, info) shown in the Site Kit](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-notices--settings-info-notice-with-a-long-notice) should have their UI updated to follow [this Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=410-6399&t=B6zsxa6pTMQuCdVc-0).

## Steps to reproduce

1. Set up Site Kit with Analytics connected but GA4 not connected, and enable the ga4Reporting feature flag.
2. Navigate to the Main Dashboard and set the current reference date to be on or after July 1st, 2023:
`googlesitekit.data.dispatch('core/user').setReferenceDate('2023-07-01')`
3. Navigate to the Analytics settings page.
4. Verify the warning notice appears, in both the view and edit modes.

Here is a screenshot for visual aid:
![image](https://user-images.githubusercontent.com/20284937/223939184-f282b852-4e6f-4bf8-8aff-44a2bbc93e43.png)

---------------

![image](https://user-images.githubusercontent.com/94359491/229046102-93123c53-75c8-4fc7-957d-4b9c14dae1d4.png)

**Current Implementation**

![image](https://user-images.githubusercontent.com/94359491/229046158-8ded0f16-89e7-400f-9eff-738fb75d6f4b.png)

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@nfmohit There seems to be some context missing here. Surely we don't want to update all warning, error, and info notifications to all look the same? Should this maybe be specific to notices about the UA sunset specifically?

**Comment by nfmohit** [comment]
Hi @aaemnnosttv!

Based on the conversation in Figma [here](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd?node-id=410:6399#384727041), and in Slack [here](https://10up.slack.com/archives/CBKKQEBR9/p1678293367182229), I was under the assumption that we'd be applying the design update to all notices, i.e. the `<SettingsNotice />` component (which we also want to rename to `Notice` as @jimmymadon pointed out [above](https://github.com/google/site-kit-wp/issues/6702#issuecomment-1477688407) as it is also being used outside Site Kit Settings).

Do you think we should apply this to notices specific to the UA sunset, e.g. introduce a new CSS class for them to use and apply the styles to that class?

Let me know what you think. Thanks!

**Comment by aaemnnosttv** [comment]
@nfmohit thanks for those references. The conversation on the design indicates that this would only apply to error notifications (as an alternative to the filled-red elements we have now).

So I think there may be some mixing of terms because the notifications that these are intended to target seem to be more about those like `ReportError` than the inline notices we have.

The idea of renaming `SettingsNotice` to `Notice` is more of a semantic one so I'm less concerned about that.

Let's pick this up with Sigal when she's back to clarify. This doesn't block the work we have in progress but we should make sure we're on the same page regarding changes of such potentially large scope.

**Comment by mohitwp** [comment]
Putting note to make sure that connected PR resolve all the design issue related to AdSense Notice. Posted [here](https://github.com/google/site-kit-wp/issues/6573#issuecomment-1500325105) cc @wpdarren

**Comment by bethanylang** [comment]
Closing as we've decided not to make these updates right now to avoid having multiple versions of notifications across the product.
