### ISSUE TITLE
Improve inline error notice and retry UX

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6707]
Reboot of #6162 :

---

Follow up to #5494 and #6055: Both the approach using a Retry button and the approach using a Retry link for inline error notices are not right. They both look confusing in the greater UI they're part of, and we need to revise this in a more holistic way. There are two key concerns here:

* If an error happens while rendering the initial UI (e.g. failed requesting necessary data, such as accounts, properties etc.), the entire UI should be replaced with the error message, since in that case it'll either be a broken UI or the wrong UI anyways. In that case, the Retry button should be shown similar to how it is today. Since then there would not be any other UI, it would be clear to the user that they need to click the single primary CTA, the "Retry" button.
* If the error happens while processing a user action (e.g. failed saving data or creating an entity, such as an account, property etc.), the error message should still be displayed inline similar to today. In that case, it **must not** have any Retry button or link though, and rather just be followed by a text like "Please try again". Since the primary CTA that the user originally clicked would still be present in the UI, clicking that is basically the "Retry" anyway.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Retry" button in Inline error notices (mostly via the `ErrorNotice` component) should be handled differently depending on context:
    * If the `ErrorNotice` is displayed within a UI where there is no primary CTA button present, it can be displayed as it is today (primary button). An example would be when something goes wrong in rendering the overall UI so the error notice replaces that entire UI.
    * If the `ErrorNotice` is displayed within a UI where there is already a primary CTA button present, the Retry button should not be displayed. Instead the main error text should just be followed by a "Please try again." text (no link or button). This is because for those situations the error most likely occurred during logic triggered by the user clicking the existing primary CTA button, so that CTA button is already sufficient as a de-facto retry mechanism.
    * Since the `ErrorNotice` component does not have that context itself, this likely should be controlled by a prop and set accordingly anywhere that an `ErrorNotice` (or the `ErrorNotices` wrapper) is used.

## Implementation Brief

* [x] Update `assets/js/components/ErrorNotice.js`
  * Introduce a new prop `hasButton`
  * In the current conditional check for rendering the button, in `shouldDisplayRetry` add AND condition if `hasButton` is present as well
* [x] Update `StoreErrorNotices` component, and include the same `hasButton` prop and pass it down to the wrapped `ErrorNotice` component. Although at the time of writing this component does not seem to be replacing any other visually/rendering in component with no primary button, potentially it can be skipped if it is verified during execution as well that no component is affected.
* [x] Update `ErrorNotices` component, and include the same `hasButton` prop and pass it down to the wrapped `StoreErrorNotices` component. 
* [x] Apply the new prop `hasButton` to the `ErrorNotices` component in the `assets/js/modules/adsense/components/setup/SetupMain.js`. Which seems to be the only place error is replacing the component at the time of writing.
  * Search for the usage of `<ErrorNotice` (also `<StoreErrorNotices`) and if it is rendered conditionally instead of the other component - occupying the whole space like the components above, and/or there is no primary button - include this prop as well. In case some other place was missed initially when IB was drafted
* [ ] In other places where `ErrorNotice` is used, implement additional `Please try again.` text at the end of the current `message` prop

### Test Coverage

* Update any failing jest test/VRT

## QA Brief

It is safest to check as many error renderings as we can across the code base. For this matter, it is recommended to use the Tweak browser add-on and define 2 rules, 1 for GET requests and 1 for POST requests, to capture _all_ requests and error them, this will give us the greatest exposure to error notices across the code base.

**The following Tweak rule should be created and enabled for GET requests:**

- URL: `^(.*)\/wp-json\/google-site-kit\/v1\/(.*)$`
- Regex: Enabled (via regex icon)
- HTTP Method: `GET`
- Status Code: `403`
- Delay: `0`
- Request Payload:
```
{
  "code": 403,
  "message": "Foo Error",
  "data": {
    "status": 403,
    "reason": "foo"
  }
}
```

**The following Tweak rule should be created and enabled for GET requests:**

- URL: `^(.*)\/wp-json\/google-site-kit\/v1\/(.*)$`
- Regex: Enabled (via regex icon)
- HTTP Method: `POST`
- Status Code: `403`
- Delay: `0`
- Request Payload:
```
{
  "code": 403,
  "message": "Foo Error",
  "data": {
    "status": 403,
    "reason": "foo"
  }
}
```

- Once said Tweak rules are active and enabled, navigate the Site Kit application, througought the dashboard and settings, saving settings where possible. 
- Validate that errors that contain CTA buttons do not contain "Please try again." text.
- Validate that inline messages (such as that produced when trying to save Key Metric Widgets from the selection panel) that do not contain retry buttons, do show the Please try again." text.

## Changelog entry

* Improve error notice when no "Retry" button is present.

**Comment by ivonac4** [comment]
@techanvil  Are you still planning to work on this soon? If not, could you please unassign yourself so someone else can pick it up? Thank you!

**Comment by techanvil** [comment]
Thanks @ivonac4 - happy to unassign this one and let someone else take a look.

**Comment by tofumatt** [comment]
The ACs here seem complete; I looked through what more would be needed here but I don't see anything, so I'm moving this to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by 10upsimon** [comment]
Note that during internal comms it became clear that the IB also needed an item in relation to updating `<ErrorNotices />` as that needs to pass down `hasButton` to `<StoreErrorNotices />`. Updating IB accordingly.

**Comment by 10upsimon** [comment]
Adding further updates here following the addition of `"Please try again."` text appended to notices that do not have a retry button. It was discovered that `ErrorItem` was being used as a means of basic inline error text rendering, such as was the case in `assets/js/components/SelectionPanel/SelectionPanelFooter.js`.

I've replaced the usage of `<ErrorItem>` in this case with `ErrorText`. This did, however, result in a font size that was now smaller (12px as opposed to 14px). Looking at the error text output if `SaveError` is present, that text was `14px`.

I've added some SASS rules to match the 14px on any inline error text within the `SelectionPanelFooter` component to be consistent with other error styling within said component.

The below screenshot shows the usage of `ErrorText`, the error notice was too small (12px):
![image](https://github.com/user-attachments/assets/037aa473-fdc2-43db-badb-4761b641e8b6)

The below screenshot shows the usage of `ErrorText` with updated SASS rules applied:
<img width="536" alt="image" src="https://github.com/user-attachments/assets/9c7ba74d-2069-4c7c-9819-4dd8a7cad0c8">

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested using tweak extension
- Verified that errors that contain CTA buttons do not contain "Please try again." text.
- Verified that inline messages (such as that produced when trying to save Key Metric Widgets from the selection panel) that do not contain retry buttons, do show the Please try again." text.

<details>

![image](https://github.com/user-attachments/assets/dffc8cd2-76fc-40c7-bcca-3dffc5121b9d)

![image](https://github.com/user-attachments/assets/0efe57e5-6e78-4c9d-a719-539dc785ff18)

![image](https://github.com/user-attachments/assets/6d755a7f-e1d0-4ba1-94b4-0a0a697efebf)


 **_errors that contain CTA buttons do not contain "Please try again." text._**

![image](https://github.com/user-attachments/assets/8cf4f374-d327-4f0e-993b-69930b29a451)

![image](https://github.com/user-attachments/assets/1e124eea-d430-4ae0-82c9-b84cadb89ac7)

![image](https://github.com/user-attachments/assets/a1e76aad-c607-42d5-b231-526398da2ff6)

**_inline messages (such as that produced when trying to save Key Metric Widgets from the selection panel) that do not contain retry buttons, do show the Please try again." text._**


![image](https://github.com/user-attachments/assets/57f0a0b5-e4a2-4671-a01f-783f5d50cc5f)

</details>
