### ISSUE TITLE
The `Set up Google Analytics` CTA on SK WP Dashboard Widget results in error

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6710]
## Bug Description

When Analytics module is not active, clicking the `Set up Google Analytics` CTA present on the SK Widget for WP Dashboard does not take user to oAuth flow and instead results in a console error. 

Initially reported as part of release testing (#6655) by @wpdarren 

## Steps to reproduce

1. Set Up Site Kit but don't setup Analytics yet.
2. Place the SK Widget on WordPress dashboard. 
3. Click on the `Set up Google Analytics` CTA. 
4. See that the user is not navigated to oAuth page and console having an error. 

## Screenshots

https://user-images.githubusercontent.com/73545194/224236002-01ba948d-51bf-4d96-a819-e8129b958711.mp4

## Additional Context

This seems to be happening due to `getConnectURL` not being resolved when the CTA is clicked, which is used by `getAdminReauthURL` in the CTA callback function. See relevant [slack](https://10up.slack.com/archives/CBKKQEBR9/p1678428467393629) thread for more info. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Set up Google Analytics` CTA in Site Kit widget on WP dashboard should always and consistently work and not produce any console errors.

## Implementation Brief

* Add a resolver for `getAdminReauthURL` within `createInfoStore`
* Use resolve-select to "prefetch" the underlying resolver-having selector of each inner selector used within the `getAdminReauthURL` selector
* Update the `SELECT_MODULE_REAUTH_URL` control to resolve-select underlying values in the same way for the given module (before selecting `getModuleStoreName`), as well as `getAdminReauthURL` when used
* Merge #7177 
	* Needs fixing a few tests which are failing due to the need for `connectURL`

### Test Coverage

* Extend the existing coverage for the `activateModule` action to include a new case for when reauthentication is needed (which is missing, and directly related to this issue)

## QA Brief

1. Set Up Site Kit but don't setup Analytics yet.
2. Place the Site Kit Widget on WordPress dashboard. 
3. Click on the `Set up Google Analytics` CTA on the WordPress (not Site Kit) Dashboard. 
4. There should be no console error and the user should be navigated to the OAuth screen to authorise Analytics. 

QA Context:

* This change touches the internals of module activation which is shared by all modules
* There is a difference in how things work when activating a module requires authentication (new scopes granted) or not (already granted, or just not needed).
	* The bug here was specific to the case where additional scopes are needed but we should test the other cases too
* There are a number of places where module activation CTAs exist and this same error was reported to happen in the admin bar CTAs as well, but it's worth checking those on the SK dashboard too

## Changelog entry

* Fix the "Set up Google Analytics" CTA on Site Kit's WordPress Dashboard widget, ensuring it correctly navigates to the setup page.

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by aaemnnosttv** [comment]
Noting that in my testing this is not a critical bug because simply retrying the action will work. We should be able to get it into the next release, but doesn't seem like a P0 IMO.

https://user-images.githubusercontent.com/1621608/226696691-d39d8d39-23d6-4184-b2f3-bc8b3e8ae8cc.mp4

**Comment by aaemnnosttv** [comment]
The issue here is specific to when additional scopes are needed to be granted in response to the module activation. There is a somewhat long chain of events that happen when activating a module and it is the underlying `connectURL` we use for navigating to oAuth that isn't immediately available when this is called, and the internal selecting that is happening isn't entirely async-friendly. My guess is that this stopped working when we upgraded WP data which made a number of select calls that were previously synchronous to be async.

I'll add an IB here which should fix it.

**Comment by eugene-manuilov** [comment]
IB ✔️
