### ISSUE TITLE
Address inconsistencies with punctuation in copy

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6720]
## Feature Description

There is a bit of inconsistency with the way punctuation is applied in the plugin. For a specific example, see the Analytics settings view:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/da65033e-4e2a-4d00-8b4e-8c8aa3bdf42b)

We should audit the plugin for any such inconsistencies, and fix them.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All strings within the plugin should be reviewed for punctuation to follow our style guide as mentioned below:

**_"Skip periods and unnecessary punctuation_**

_To help readers scan text, avoid using periods and other unnecessary punctuation._ 

_Avoid using periods to end single sentences, particularly in:_
_- Labels_
_- Tooltip text_
_- Bulleted lists_
_- Dialog body text_
_- Hyperlinked text_

_Use periods on:_
_- Multiple sentences_
_- Long or complex sentences, if it suits the context_
_- Any sentence followed by a link"_

## Implementation Brief

* At the time of writing, some locations have period on the end of the sentence that should be removed:
  * When editing `Tag Manager` settings, for code placement description
  * On connect more services tab, when all modules are connected, for the description `We’re working on adding new services to Site Kit by Google all the time, so please check back in the future.` 
* Screenshot attached in AC is no longer relevant, UA is not present any more, and GA4 placement text doesn't have a dot at the end of label any more.
* Following the style guide added in AC, check the overall plugin components text content if there is any other place that needs edit.

### Test Coverage

* No test update is needed
* Update any failing VRT reference images

## QA Brief

* Ensure the periods are used consistently across the plugin UI. Specially - Site Kit Setup screen, settings screen, module setup, settings view and settings edit screen, various banner notifications, SK Widgets, WP Dashboard Widgets, Admin Bar widgets, AdSense Setup CTA, Ad Blocking Recovery Setup CTA and flow, User Input and Key Metrics setup and edit flows, Sharing settings. 

## Changelog entry

* Address inconsistencies with punctuation in copy throughout the plugin.

**Comment by marrrmarrr** [comment]
@jimmymadon according to the style guide, single-sentence phrases like the ones in the screenshot above should have no full stop. If there is more than one sentence, then it's necessary to separate them with full stops. 

Here is the full guidance for reference: 
**_"Skip periods and unnecessary punctuation_**

_To help readers scan text, avoid using periods and other unnecessary punctuation._ 

_Avoid using periods to end single sentences, particularly in:_
_- Labels_
_- Tooltip text_
_- Bulleted lists_
_- Dialog body text_
_- Hyperlinked text_

_Use periods on:_
_- Multiple sentences_
_- Long or complex sentences, if it suits the context_
_- Any sentence followed by a link"_

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@kuasha420 Other than the first issue highlighted, I am not 100% sure about the others. 

Would appreciate your opinion since these aren't multiple sentences.

1.  We have a period in the Ad Blocking Recovery screen. 

![image](https://github.com/google/site-kit-wp/assets/73545194/49d18f47-e1ee-46d0-a161-704f83545606)

2. For the user input survey questions, we have a description. Should the description have a period when there is a comma within the text? 

![image](https://github.com/google/site-kit-wp/assets/73545194/b901f353-ecf5-4fa6-a8b8-a223222f0b73)

3. The same question above. I noticed a period in a few other places.  Maybe if there's a comma, then it should have a period.

![image](https://github.com/google/site-kit-wp/assets/73545194/13ff2ada-9221-4fad-9656-bed0729d179f)
![image](https://github.com/google/site-kit-wp/assets/73545194/dbcff6ea-44d2-4b1a-aa34-be3ed5e374a0)

4. I found this period on the Dashboard Sharing view-only panel. 

![image](https://github.com/google/site-kit-wp/assets/73545194/de2a50fc-8c06-4a41-8b59-e2219128e7cd)

**Comment by kuasha420** [comment]
@wpdarren Thank you for the detailed testing and observation. As mentioned by @bethanylang on Slack, the the periods removed from the lines with commas are fine. I've opened an additional PR to remove the other periods you've found. Cheers.

**Comment by techanvil** [comment]
Back to you for another pass, @wpdarren.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 Just two observations, and I think we are done. 

1. The user input descriptions still have a period.  I think we said that they shouldn't. Am I correct? 

![image](https://github.com/google/site-kit-wp/assets/73545194/07d3a052-a049-45d9-945d-96edd7464593)

2. Apologies, I didn't notice this in my first round of testing. 

The AdSense 'ready' status screen needs the period removing. 

![image](https://github.com/google/site-kit-wp/assets/73545194/6ff6d115-76e4-4df8-a9d2-bac2edc08d36)

**Verified:**

- Periods are used consistently across the plugin UI. 
- Especially - Site Kit Setup screen, settings screen, module setup, settings view and settings edit screen, various banner notifications, SK Widgets, WP Dashboard Widgets, Admin Bar widgets, AdSense Setup CTA, Ad Blocking Recovery Setup CTA, and flow, User Input and Key Metrics setup and edit flows, Sharing settings.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/47837c99-fe13-4d9f-94e4-162ff2b1bdc8)
![image](https://github.com/google/site-kit-wp/assets/73545194/80ba08e9-57b2-4696-bf90-d92a11e54e41)
![image](https://github.com/google/site-kit-wp/assets/73545194/766dd6a1-dc32-4b6c-a6b5-d78c4c359d5d)
![image](https://github.com/google/site-kit-wp/assets/73545194/c69d7dba-3283-44eb-a7d5-06f2db845a10)
![image](https://github.com/google/site-kit-wp/assets/73545194/8c2ad19f-fbeb-47a1-9aba-7ae0266a134f)
![image](https://github.com/google/site-kit-wp/assets/73545194/6763c561-a0b8-4e1c-8ba0-feaa2e910f0e)
![image](https://github.com/google/site-kit-wp/assets/73545194/f4723a64-d313-4bd3-a4d0-9c169666bfbc)
![image](https://github.com/google/site-kit-wp/assets/73545194/928d1978-4372-42bf-b587-3a795de36ac9)
![image](https://github.com/google/site-kit-wp/assets/73545194/867253a9-2452-4e88-90d8-63aead793f47)
![image](https://github.com/google/site-kit-wp/assets/73545194/4dd7197f-38c2-4760-a1c1-edd3aec6dc9d)
![image](https://github.com/google/site-kit-wp/assets/73545194/0356cd79-62b6-4b7e-9b97-58b52b94bd71)
![image](https://github.com/google/site-kit-wp/assets/73545194/f149f623-7315-405f-ab9c-70680fd2e418)
![image](https://github.com/google/site-kit-wp/assets/73545194/54444806-3169-4b7b-8c13-f560f43cc475)
![image](https://github.com/google/site-kit-wp/assets/73545194/88644375-4add-4118-a54b-12f32235c627)

</details>

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Periods are used consistently across the plugin UI. 
- Especially - Site Kit Setup screen, settings screen, module setup, settings view and settings edit screen, various banner notifications, SK Widgets, WP Dashboard Widgets, Admin Bar widgets, AdSense Setup CTA, Ad Blocking Recovery Setup CTA, and flow, User Input and Key Metrics setup and edit flows, Sharing settings.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/053fab5d-4601-4502-b831-62ace5795373)
![image](https://github.com/google/site-kit-wp/assets/73545194/d53469cf-627e-419b-8243-e703ae63acc6)
![image](https://github.com/google/site-kit-wp/assets/73545194/47837c99-fe13-4d9f-94e4-162ff2b1bdc8)
![image](https://github.com/google/site-kit-wp/assets/73545194/80ba08e9-57b2-4696-bf90-d92a11e54e41)
![image](https://github.com/google/site-kit-wp/assets/73545194/766dd6a1-dc32-4b6c-a6b5-d78c4c359d5d)
![image](https://github.com/google/site-kit-wp/assets/73545194/c69d7dba-3283-44eb-a7d5-06f2db845a10)
![image](https://github.com/google/site-kit-wp/assets/73545194/8c2ad19f-fbeb-47a1-9aba-7ae0266a134f)
![image](https://github.com/google/site-kit-wp/assets/73545194/6763c561-a0b8-4e1c-8ba0-feaa2e910f0e)
![image](https://github.com/google/site-kit-wp/assets/73545194/f4723a64-d313-4bd3-a4d0-9c169666bfbc)
![image](https://github.com/google/site-kit-wp/assets/73545194/928d1978-4372-42bf-b587-3a795de36ac9)
![image](https://github.com/google/site-kit-wp/assets/73545194/867253a9-2452-4e88-90d8-63aead793f47)
![image](https://github.com/google/site-kit-wp/assets/73545194/4dd7197f-38c2-4760-a1c1-edd3aec6dc9d)
![image](https://github.com/google/site-kit-wp/assets/73545194/0356cd79-62b6-4b7e-9b97-58b52b94bd71)
![image](https://github.com/google/site-kit-wp/assets/73545194/f149f623-7315-405f-ab9c-70680fd2e418)
![image](https://github.com/google/site-kit-wp/assets/73545194/54444806-3169-4b7b-8c13-f560f43cc475)
![image](https://github.com/google/site-kit-wp/assets/73545194/88644375-4add-4118-a54b-12f32235c627)

</details>
