### ISSUE TITLE
Cannot read properties of undefined (reading ‘MutationObserver’)

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6722]
## Bug Description

As reported by [a user in the support forums](https://wordpress.org/support/topic/cannot-read-properties-of-undefined-reading-mutationobserver/#post-16557604), the below error appears on the Site Kit dashboard if the [Enterprise – Apaczka.pl plugin](https://wordpress.org/plugins/apaczka-pl/) is activated. 

`Cannot read properties of undefined (reading ‘MutationObserver’)`

![image](https://user-images.githubusercontent.com/41326532/224973087-057fc3be-00ca-48b7-bdb9-81ae7ebca3ee.png)

Testing is ongoing. The plugin does load it's own scripts on Site Kit dashboard URLs. 

<details>
<summary>Console Errors</summary>

```
googlesitekit-vendor…5d17559d7f7544.js:7 TypeError: Cannot read properties of undefined (reading 'MutationObserver')
    at h (googlesitekit-vendor…d7f7544.js:7:416773)
    at Header (googlesitekit-splash…d39ecbfbf.js:7:3525)
    at Fo (googlesitekit-vendor…d7f7544.js:7:710546)
    at Ti (googlesitekit-vendor…d7f7544.js:7:756796)
    at Qj (googlesitekit-vendor…d7f7544.js:7:749344)
    at Kj (googlesitekit-vendor…d7f7544.js:7:749269)
    at wa (googlesitekit-vendor…d7f7544.js:7:746299)
    at googlesitekit-vendor…d7f7544.js:7:697943
    at t.unstable_runWithPriority (googlesitekit-vendor…d7f7544.js:7:773193)
    at Hr (googlesitekit-vendor…d7f7544.js:7:697652)
googlesitekit-splash…56c3fd39ecbfbf.js:1 Caught an error: TypeError: Cannot read properties of undefined (reading 'MutationObserver')
    at h (googlesitekit-vendor…d7f7544.js:7:416773)
    at Header (googlesitekit-splash…d39ecbfbf.js:7:3525)
    at Fo (googlesitekit-vendor…d7f7544.js:7:710546)
    at Ti (googlesitekit-vendor…d7f7544.js:7:756796)
    at Qj (googlesitekit-vendor…d7f7544.js:7:749344)
    at Kj (googlesitekit-vendor…d7f7544.js:7:749269)
    at wa (googlesitekit-vendor…d7f7544.js:7:746299)
    at googlesitekit-vendor…d7f7544.js:7:697943
    at t.unstable_runWithPriority (googlesitekit-vendor…d7f7544.js:7:773193)
    at Hr (googlesitekit-vendor…d7f7544.js:7:697652) 
{componentStack: '\n    in Header\n    in SetupUsingProxyWithSignIn\n  …   in ThemeProvider\n    in StrictMode\n    in Root'}
componentStack
: 
"\n    in Header\n    in SetupUsingProxyWithSignIn\n    in DashboardSplashApp\n    in RestoreSnapshots\n    in ErrorHandler\n    in ThemeProvider\n    in StrictMode\n    in Root"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()
```

</details>

## Steps to reproduce

1. Setup a site with Site Kit active and WooCommerce already installed and activated (without WooCommerce installed and active you may [encounter additional fatal errors](https://user-images.githubusercontent.com/41326532/224972684-6af22d9a-f45f-49d8-8698-e56ee46e88db.png).
2. Install and activate the [Enterprize apaczka-pl](https://wordpress.org/plugins/apaczka-pl/) plugin
3. Check the Site Kit dashboard, the error appears

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/224975209-6b2ede11-d975-47c3-b9d8-82ac757d0085.png)
_Above: A script that seems to be requested from the plugin - on the Site Kit dashboard page. The contents of this file can be found [here](https://plugins.trac.wordpress.org/browser/apaczka-pl/trunk/assets/js/admin.js)._

![image](https://user-images.githubusercontent.com/41326532/224976970-a59afc63-6a23-41e5-a8a4-bce15c8c0776.png)

_Above: The header requests on the Site Kit dashboard_

![image](https://user-images.githubusercontent.com/41326532/224977233-cd87fb6d-1524-45b3-8909-908791e68388.png)

Above: The plugin does require API details to be input. I didn't do this on the test site where I could create this. 

## Additional Context

 - [Support topic](https://wordpress.org/support/topic/cannot-read-properties-of-undefined-reading-mutationobserver/#post-16557604) | [Site Health information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgRNmEvjI9Ka2mYxZ87qwU1xH787domu1SWOqmqDFRwUUwMCH10BDvpDIh23v5Ka_8)
 - Reproducible in support on a test site
 - The plugin does require API details
 - [Asana task - internal testing](https://app.asana.com/0/1185360131189553/1204319807483453)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ashishneupane030** [comment]
Hello,
I downgraded my PHP to 7.4 and this is what I am getting

" Unknown Error (code: The cURL request was retried 3 times and did no succeed. cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information.) " 

And Before downgrading the PHP to 7.4,
I was able to click every option in WordPress, even though I was able to access the site kit setting option, but I was unable to access both the WordPress and site kit dashboard. Now, I am able to access any options but the above error is out there.

**Comment by tofumatt** [comment]
We might want to look at https://github.com/Horat1us/react-hooks/blob/master/src/use-mutation-observer.ts

**Comment by jamesozzie** [comment]
Closing this with no response from impacted user. 

In addition, after further testing the issue seems to be that a script based on the [Enterprise – Apaczka.pl plugin](https://wordpress.org/plugins/apaczka-pl/) is [requested on the Site Kit dashboard](https://i.imgur.com/BaW7mtL.png), and not just on their own endpoints. The script (https://mapa.apaczka.pl/client/apaczka.map.js) when requested is also redirected, see below.

![image](https://github.com/google/site-kit-wp/assets/41326532/83791fee-4ac4-42da-915f-f46bc6fbaf79)

I left some comments to the impacted user regarding reaching out to the support team of the Apaczka plugin, enquiring whether the below script should be requested on all wp-admin URLs:

`wp_enqueue_script( self::APP_PREFIX . '_apaczka.map.js',`
