### ISSUE TITLE
Fix Engagement Rate in the `SearchFunnelWidgetGA4` component.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6724]
## Feature Description

The Engagement Rate metric is currently shown in the `SearchFunnelWidgetGA4` component without the percentage sign. This should be updated so it's displayed as a percentage value.

Furthermore the widget is still using the `engagedSessions` metric in its report - this should be updated to be `engagementRate`.

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/da37a0ab-d807-441b-a91d-5511f952a640)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The relevant report used in the `SearchFunnelWidgetGA4` widget should use `engagementRate` rather than `engagedSessions`.
* The Engagement Rate metric in the `SearchFunnelWidgetGA4` component should be displayed as a percentage value.

## Implementation Brief

Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js`:

- Replace the metric [`engagedSessions`](https://github.com/google/site-kit-wp/blob/e3a23a645be3e7925d9534358078e35f3ebf9a74/assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js#L166) with `engagementRate`.
- Add a percent sign to the [`Engagement Rate` data label](https://github.com/google/site-kit-wp/blob/e3a23a645be3e7925d9534358078e35f3ebf9a74/assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js#L466) so it reads `Engagement Rate %`.
- Add the percentage to the graph tooltip, using the code that was removed in https://github.com/google/site-kit-wp/commit/b57f64adb2c57a854076de47f604aa5f5a721d02, but _without_ dividing the value by 100, as `engagementRate` is a float between 0-1.

Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/index.js`:

- Add the property `datapointUnit: '%'` to the [datablock config for Engagement Rate](https://github.com/google/site-kit-wp/blob/e3a23a645be3e7925d9534358078e35f3ebf9a74/assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/index.js#L244-L251).
- Update all variables named `.*EngagedSessions.*` to replace `EngagedSessions` with `EngagementRate`.

Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.stories.js`:

- Replace the metric `engagedSessions` with `engagementRate`.

### Test Coverage

- Update the relevant VRT reference images.

## QA Brief

* Check the Engagement Rate metric  on a single-page dashboard 
* The metric should be updated to display an `engagementRate` together with a % sign 

## Changelog entry

* Update the Analytics 4 Search Funnel component to use the "Engagement Rate" metric instead of "Engaged Sessions".

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@sashadoes the `Engagement Rate` metric appears with a percentage but when I started to change the reporting period on the single page dashboard, the graph disappeared for 7 and 90 days.  It appears fine for 14, 28 days.  I did notice that the `Unique visitors from search` behaved the same so this could be a GA4 Reporting issue, rather than a particular problem with this change.  Please could you confirm if this is the case?  I will then see if we have a ticket that will fix this or if we need to create a new one. 

https://user-images.githubusercontent.com/73545194/227818727-ed7f53b3-7bba-4196-8cbd-dadf4175c630.mp4

**Comment by techanvil** [comment]
@wpdarren, as discussed on Slack, it looks like this should be fixed via https://github.com/google/site-kit-wp/issues/6623. Specifically, the [code to determine the chart data](https://github.com/google/site-kit-wp/blob/019189df9848eae3ff4b5fa66886d5d5c9a35152/assets/js/modules/analytics-4/utils/extract-dashboard-data.js#L194-L216) will not give the desired result when there are missing rows where we expect there to be zero-data rows. Looks like we can move this issue through QA and keep an eye on the described behaviour when implementing #6623.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `Engagement Rate` metric appears on the entity dashboard.
- The metric display `Engagement Rate` together with a % sign.
- I tested that the metric appeared on different reporting periods, 7, 14, 28 and 90 days. 
- I also checked to make sure that the data appeared within the correct GA4 component. 

![image](https://user-images.githubusercontent.com/73545194/227939859-987baf93-69f2-40b5-ac11-d3bf0a31d6d7.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `Engagement Rate` metric appears on the entity dashboard.
- The metric display `Engagement Rate` together with a % sign.
- I tested that the metric appeared on different reporting periods, 7, 14, 28 and 90 days. 
- I also checked to make sure that the data appeared within the correct GA4 component. 

![image](https://user-images.githubusercontent.com/73545194/227939859-987baf93-69f2-40b5-ac11-d3bf0a31d6d7.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `Engagement Rate` metric appears on the entity dashboard.
- The metric display `Engagement Rate` together with a % sign.
- I tested that the metric appeared on different reporting periods, 7, 14, 28 and 90 days. 
- I also checked to make sure that the data appeared within the correct GA4 component. 

![image](https://user-images.githubusercontent.com/73545194/227939859-987baf93-69f2-40b5-ac11-d3bf0a31d6d7.png)
