### ISSUE TITLE
GA4 attempts duplicate creation requests in the event of an error

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6728]
## Bug Description

The Analytics data store was intentionally designed to save GA4 settings in more than one point in its `submitChanges` action to avoid making changes in one module and not in the other due to an error. Not just hard errors like failed requests but soft errors like an insufficient scopes error where the user first needs to go through oAuth again to grant additional scopes before attempting what would otherwise be a request that is guaranteed to fail.

For more context, refer to the original discussion here: https://github.com/google/site-kit-wp/pull/4046#issuecomment-928923148

Currently, if an error is returned from the GA4 submit action, it only "counts" as an error if it's related to permissions, otherwise it's silently ignored. This could be related to legacy stability-related conditions – removed in #5575. Due to the above mechanic, this has the effect of attempting entity creation requests more than once if they failed the first time.

Perhaps more significantly, it means that errors from the GA4 submit action are not being handled properly. 

## Steps to reproduce

1. Configure the browser to block requests matching/containing `analytics-4/data/create-`
2. Configure GA4 to create a new property during setup or from settings
3. Submit
4. Observe duplicate failed requests to the create endpoints
	- Also, no error message is shown in the settings edit or view panels, nor is there any other visible indication of an error

## Screenshots

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1621608/225506384-b314fa9e-6f78-404f-b3a0-0aa05ec16df0.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
It's worth noting here that all our use of `StoreErrorNotices` within Analytics components only uses it with the `analytics` slug, so any errors raised for `analytics-4` calls are not being displayed...

**Comment by aaemnnosttv** [comment]
Thanks for raising @techanvil – I think that was intentional before #5575 where errors from GA4 were never surfaced to users, and even caused the module's interface to disappear (really intended not to appear in the first place more than anything). We should probably be showing the error notices from both modules in all of the relevant components.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, that makes sense. How do you want to address this - do you think we should handle it as part of this issue, or shall I create a new issue to capture and flesh it out?

**Comment by aaemnnosttv** [comment]
@techanvil fixing the error display should be simple and is less important for this specific issue. IIRC, I think this may even be fixed in #6763 otherwise we could fix this specifically in a separate issue.

**Comment by aaemnnosttv** [comment]
This should no longer be possible now as of https://github.com/google/site-kit-wp/pull/6980/commits/2c396b2b8cbc941832db18126c391158bd0a8e77

**Comment by aaemnnosttv** [comment]
Closing as this is no longer an issue 👍
