### ISSUE TITLE
Add tracking of anonymous usage stats consent to initial setup step

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#673]
## Feature Description

With most of the setup flow moving to the Site Kit Service, the page where users currently decide whether they want to opt in to anonymous usage tracking will disappear. 

Let's add the checkbox and necessary text to the two relevant locations in the plugin:
1) Congratulations banner after the user clicks "Activate" on the plugins page
2) Landing page for users who did not immediately proceed with the onboarding flow and the banner disappeared (issue #642 ) 

Note that the checkbox should be unchecked by default, users need to actively opt in (issue #633) 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the user clicks "Activate" for Site Kit, in the banner that appears at the top of the page, display an unchecked checkbox below the "start setup" button. 
* The text next to the checkbox: "Help us improve the Site Kit plugin by allowing tracking of anonymous usage stats. All data are treated in accordance with Google Privacy Policy."
* "Google Privacy Policy" should link to https://policies.google.com/privacy
* The same checkbox and text should appear below the "start setup" button on the landing page from #642 

## Implementation Brief

![image](https://user-images.githubusercontent.com/1621608/67110307-19883700-f1db-11e9-8d2c-ad194112c4f5.png)

* Add the `Optin` to the proxy setup  
```diff
diff --git a/assets/js/components/setup/setup-proxy.js b/assets/js/components/setup/setup-proxy.js
index 2e5c814..514065b 100644
--- a/assets/js/components/setup/setup-proxy.js
+++ b/assets/js/components/setup/setup-proxy.js
@@ -22,6 +22,7 @@
 import Header from 'GoogleComponents/header';
 import Button from 'GoogleComponents/button';
 import Layout from 'GoogleComponents/layout/layout';
+import Optin from 'GoogleComponents/optin';
 import { sendAnalyticsTrackingEvent } from 'GoogleUtil';
 import { getSiteKitAdminURL } from 'SiteKitCore/util';
 
@@ -103,6 +104,10 @@ class SetupUsingProxy extends Component {
                                                        >
                                                            { __( 'Start setup', 'google-site-kit' ) }
                                                        </Button>
+                                                       <Optin
+                                                           id="opt-in"
+                                                           name="optin"
+                                                       />
                                                    </div>
                                                </div>
                                            </div>
```

* Add styles to add spacing between the start button and the optin

## Changelog entry

* Modify plugin activation banner for consistent UI with the plugin setup screen.

**Comment by aaemnnosttv** [comment]
What about the Help link?
![image](https://user-images.githubusercontent.com/1621608/67112692-7c300180-f1e0-11e9-9538-1cc4274e49c9.png)
https://sitekit.withgoogle.com/documentation/

**Comment by felixarntz** [comment]
IB ✅ 

@aaemnnosttv Which help link are you referring to? Note that the proxy contains a help link, and since that now contains all the setup steps, it might be sufficient.

**Comment by aaemnnosttv** [comment]
@felixarntz this one on the right side

![image](https://user-images.githubusercontent.com/1621608/67227192-6e2bec00-f43f-11e9-83c5-258e727a4762.png)

**Comment by tofumatt** [comment]
Ah, just working on this issue now, thinking about the AC specifying the opt-in checkbox appearing in the activation banner: what’s the thinking for showing that checkbox right after activation?

I think it’s a bit of a sub-optimal UX (the “next” screen would have the checkbox available and is a more obvious place to opt-in). Placing it in the already large activation banner (I think the header size could be reduced) distracts from the _real_ call-to-action there: to click the "Start Setup" button.

It's also more effort than an XXS task to implement as it's not part of the React app. The button and its styles/logic/UX need to be implemented in vanilla JS, outside React, for the banner to have that checkbox.

I have the non-banner section complete and ready in #691. How do you feel about removing the activation banner checkbox from the AC?

**Comment by tofumatt** [comment]
Oh wait, I almost never setup the plugin that way. 😅 I’m realising now that users who setup right from the activation screen never see that page.

I'm adjusting the estimate on this issue as it involves adding a fair bit of new UI to the activation banner. I'll continue onward 👍

**Comment by tofumatt** [comment]
Reading the description here it states:

> Note that the checkbox should be unchecked by default, users need to actively opt in (issue #633)

But issue #633 is slated for 1.0.0, not an RC version. I've already set the box to be opt-in rather than opt-out in this PR, and I'm of the opinion that it's okay to make that change pre-1.0.0.

If we don't want this to be opt-in until later I can change that, but currently it is opt-in.

**Comment by felixarntz** [comment]
As a follow-up, I added a (likely small) issue #713 - would be great if you could tackle that afterwards @tofumatt

**Comment by felixarntz** [comment]
QA ✅

**Comment by marrrmarrr** [comment]
LGTM.
