### ISSUE TITLE
Create backend infrastructure for new GA account provisioning endpoint

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6732]
## Feature Description

Currently GA account provisioning is only available via the original (UA) Analytics module. This uses the invite-only [Analytics Provisioning API](https://developers.google.com/analytics/devguides/config/provisioning/v3) which is (aside from the created account) specific to UA entities.

This issue is about introducing a new provisioning endpoint powered by the [Google Analytics Admin API V1](https://developers.google.com/analytics/devguides/config/admin/v1#account_provisioning) which only creates an account. It also only requires the standard `analytics.edit` scope, unlike the previous which required a different dedicated scope.

Due to restrictions regarding its redirect URI, this will continue to require and be limited to sites using the SK service.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics 4 module should receive a new `POST:create-account-ticket` datapoint
	- Should use the https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1beta/accounts/provisionAccountTicket endpoint internally
		- This must be made using the Google proxy as the base URL, [similar to how it is done today](https://github.com/google/site-kit-wp/blob/f04ed052ce6b654378eb1e41cfdbe76f774b7692/includes/Modules/Analytics.php#L1064)  
		_Note: the previous implmementation used a separate `Service` since it was a separate API, however this endpoint is a resource of the Admin API_
	- Requires a `displayName` for the account
	- Requires a `regionCode` (a Unicode CLDR region code) for the account
	- Requires a `propertyName` as the display name for the initial property
	- Requires a `timezone` as the time zone to use for the initial property
	- Requires a `dataStreamName` as the display name for its initial web data stream
	- The resulting account ticket ID should be stored in a user-specific transient as today **with the additional parameters that are needed post-account creation for the property and data stream**
* The `gatoscallback` handler should be updated to receive the new account ID, without expecting/handling UA IDs which won't be present (this part should only happen if the `ga4Reporting` feature flag is enabled)
	* the initial GA4 property should be created using the given `propertyName` and `timezone`
	* the initial web data stream should be created using the given `dataStreamName`
* The legacy Analytics version of the same datapoint should not be registered when the `ga4Reporting` feature flag is enabled

## Implementation Brief

* The implementation of the `analyticsprovisioning` service for the `analytics` module can be followed for most of what is needed for the new version in the `analytics-4` module
	- Create a new `GoogleAnalyticsAdmin_AccountProvisioning` service similar to the legacy `Google_Service_AnalyticsProvisioning`, extending `Google\Site_Kit_Dependencies\Google\Service\GoogleAnalyticsAdmin`
	- Create a new `Proxy_AccountTicket` in the `Modules\Analytics_4` namespace, extending the `GoogleAnalyticsAdminV1betaProvisionAccountTicketRequest`
	- Create a new `Proxy_Provisioning` in the `Modules\Analytics_4` namespace, extending the base `Google_Service_Resource` class, which only implements the `GoogleAnalyticsAdmin\Resource\Accounts::provisionAccountTicket` method
* Update the `Analytics_4::setup_services` to set up the new `analyticsprovisioning`, just like in the current implementation, passing the `google_proxy->url` as the `rootUrl` of the `GoogleAnalyticsAdmin_AccountProvisioning` service
* Add the `POST:create-account-ticket` datapoint to `analytics-4`
	- to `get_datapoint_definitions`, note the `scope` here is `Analytics::EDIT_SCOPE`
	- `create_data_request`
		- validate all required parameters, noted in AC
		- `analyticsprovisioning->accounts->provisionAccountTicket` setting the `GoogleAnalyticsAdminV1betaAccount`, and `redirectUri` (see `Analytics::get_provisioning_redirect_uri`), and proxy site id+secret credentials
	- `parse_data_response` - store the returned account ticket ID along with the `propertyName`, `timezone`, and `dataStreamName`
* Update `Analytics_4::create_property` to accept an optional second parameter `options.displayName` and `options.timezone` using the current implementation as the default values
* Update `Analytics_4::create_webdatastream` to accept an optional second parameter `options.displayName` using the current implementation as the default value
* Update `Analytics::handle_provisioning_callback`
	- if the `ga4Reporting` flag is not enabled, everything should work as today
	- if the `ga4Reporting` flag is enabled, `analytics` settings should only get the `accountID` added, no actions should happen for a property or view
	- will need to be updated to handle the variable type of the account ticket data from the transient which could be just the string ID (as today), or an array
* Update the signature of `googlesitekit_analytics_handle_provisioning_callback` to pass an associative array of arguments for the parameters that follow after the first (`$account_id`); i.e.
	- for legacy account tickets, this is unused and can be an empty array (GA4 currently only uses the account ID)
	- for new account tickets, this would include the `propertyName`, `timezone`, and `dataStreamName` from the transient
* Update `Analytics_4::handle_provisioning_callback`
	- pass through the property's `displayName` and `timezone` if provided when creating
	- pass through the data stream's `displayName` if provided when creating

### Test Coverage

* Add coverage for the new GA4 `create-account-ticket` datapoint

## QA Brief

* Current UA account provisioning should continue to work when `ga4Reporting` flag is not enabled
* The SK interfaces do not yet provide a way to test this as as a user, but it can be tested using the API
* This can currently only be tested when connected via the `site-kit-local` environment (must reset before connecting to a new service env)
	- Use `define( 'GOOGLESITEKIT_PROXY_URL','https://site-kit-local.appspot.com' );`

```js
let params = { displayName: 'test account name', regionCode: 'US', propertyName: 'test account provisioning property name', dataStreamName: 'test account provisioning data stream name', timezone: 'UTC' };

await googlesitekit.api.set( 'modules', 'analytics-4', 'create-account-ticket', params );
```
This will return an object with an `accountTicketId`.

* Open the `Account Chooser` utility story ({storybook URL}/?path=/story/accountchooser--account-chooser)

* Use the following URL with the above `accountTicketId` used in the given placeholder, and providing your same Google account email:
	```
	https://analytics.google.com/analytics/web/?provisioningSignup=false#/termsofservice/{accountTicketId}
	```
* Following the URL should take you to the Analytics Terms of Service page. After accepting the terms, the account should be created.
* After being redirected back to Site Kit:
	* A GA4 property should be created using the given name and timezone
	* A web data stream should be created using the given name for the created property

## Changelog entry

* Create backend infrastructure to support the new Google Analytics account provisioning endpoint.

**Comment by wpdarren** [comment]
QA Update: ✅ 

Oh, I had so much fun with this ticket, it was the highlight of my week so far!  

**QA Note:** If your Google account has hit the limit of Analytics accounts, the URL will not load.  I had to run through this a few times before realising, and when I deleted some old Analytics accounts, it worked. 

**Verified:**

- Following the URL takes you to the Analytics Terms of Service page. After accepting the terms, the account is created.
- After being redirected back to Site Kit:
  - A GA4 property is created using the given name and timezone
  - A web data stream is created using the given name for the created property

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/229985163-5b1bc96d-9350-4901-a77f-f368add0e5a0.png)
![image](https://user-images.githubusercontent.com/73545194/229985189-8e664e4a-d2bb-4251-9fc7-6f5b82596116.png)
![image](https://user-images.githubusercontent.com/73545194/229985372-116ef470-3520-4003-a4a5-e39eca0149b2.png)

</details>
