### ISSUE TITLE
Fix long CTAs in Banner Notifications

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6734]
## Bug Description

In #6373, we [realised an issue](https://github.com/google/site-kit-wp/issues/6373#issuecomment-1469128271) with long CTAs in Banner Notifications.

## Steps to reproduce

1. To avoid the complicated setup that #6373 requires to show the `BannerNotification`, simply check the [Storybook story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-googletagidmismatchnotification--alternative-ga-4-config) in mobile view.
2. The buttons are currently side by side but contain multiple lines.

 
## Screenshots

<img width="776" alt="Screenshot 2023-03-15 at 01 24 09" src="https://user-images.githubusercontent.com/1721319/225180383-dc830607-45c7-48b8-bcdd-d662e764ebc1.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The banner notification text and it's associated CTA button text within the ` <GoogleTagIDMismatchNotification>` component (shown when a Google Tag ID mismatch is observed) should reflect the following textual changes:

#### Banner text
```
The Google Tag on your site is no longer associated with your current Google Analytics 4 property "%1$s (%2$s)". It is now recording metrics to another Google Analytics 4 property "%3$s (%4$s)". If you want to continue seeing Analytics data in the Site Kit dashboard, we suggest you update Site Kit's Google Analytics configuration to show data for the property used in your Google Tag.
```

Note the text placeholders such as `%1$s`, `%2$s`. These will be swapped out with Analytics property values at the time of render.

#### CTA Button 1 (Left)
```
Use new property
```

#### CTA Button 2 (Right)
```
Keep existing property
```

#### Screenshot Depicting Final Result
![image](https://github.com/google/site-kit-wp/assets/72872375/bbd392ec-a446-481a-a806-c4d4ac21c7ec)

## Implementation Brief

* In `assets/sass/components/global/_googlesitekit-publisher-wins.scss`:
    * Modify the properties of the `.googlesitekit-publisher-win__actions` class as follows:
    ```css
    {
        align-items: center;
        display: flex;
        flex-direction: column;
        gap: $grid-gap-phone;

        @media (min-width: $bp-desktop) {
            display: block;
        }
    }
    ```
    * Add the following to the `.googlesitekit-button-icon--spinner + .googlesitekit-cta-link` class:
        `margin-left: $grid-gap-desktop;`
        * Add more styles here to modify the design of the Secondary CTA link to match the Figma mocks (for all states as per the AC).

### Test Coverage

* No new tests required.

## QA Brief

* Setup Site Kit and connect a GA4 Property. 
  * Note the "Measurement ID" of this property ("GA4 Property 1")
  * Go to [Tag Manager admin](https://tagmanager.google.com) and sign in using the same Google Account which has access to the above "GA4 Property 1". On the "Google tags" tab, find the row where one of the Tag IDs is the same as the "Measurement ID" above. (The Tag Name would by default be the domain name associated to the GA4 Property.)
  * Click on this tag name.
  * Note the tag ID beginning with GT (for example `GT-100000`).
  * Delete the destination ("GA4 Property 1") from the Destinations list.
  * When asked to attach a tag to the destination, create a new tag and note down its Tag ID (eg `GT-200000`). This will make the original tag (eg. `GT-100000`) not linked to any destination.
* Go back to the Site Kit plugin and in the browser console, run the following command:

```javascript
  googlesitekit.api.set('modules', 'analytics-4', 'settings', {'googleTagLastSyncedAtMs': 0});
```

* Refresh the page and verify the a  Google tag configuration change banner displays.
* Go back to [Tag Manager admin](https://tagmanager.google.com).
  * Find the row which has a Tag ID the same as the "Measurement ID" from above or the "GT-100000" tag that you noted previously.
  * Open the Tag details for this tag and click the "+ Destination" button to add a new destination. Add another GA4 Property from the list of destinations, (eg. "GA4 Property 2"). (If there are no destinations in this list, ensure your Google Account has admin access to another GA4 Property).
* Go back to the Site Kit plugin and in the browser console, run the following command:

```javascript
  googlesitekit.api.set('modules', 'analytics-4', 'settings', {'googleTagLastSyncedAtMs': 0});
```

* Refresh the page and verify that the Google Tag ID mismatch banner displays, and that the banner renders as per the AC, with updated notification and notification CTA buttons text.

## Changelog entry

* Improve the text in the buttons of the Analytics and Google Tag mismatch notification.

**Comment by bethanylang** [comment]
@jimmymadon Can you please add a priority and type label on this one? Thanks!

**Comment by tofumatt** [comment]
> If the CTAs in a `BannerNotification` do not fit side by side in a particular viewport, they should be placed one above the other and centred.

This makes sense _conceptually_, but what does it mean to "not fit"? Part of the issue here is the very long CTA text being used for the buttons, but what if the CTAs were "Enable Analytics" and "Dismiss"? They might "fit" just fine, so I'm not sure what the criteria for "not fitting side-by-side" is—even in the screenshot, they do fit next to each other width-wise, it's just that they span multiple lines.

I'd guess what we're looking to avoid is a button whose texts wraps more than one line, though I'm not sure that would be straightforward to implement in CSS.

Can you clarify this a bit before we move this to IB?

**Comment by tofumatt** [comment]
ACs here look good, and I think the IB is good as well, so moving right to EB 👍🏻

**Comment by tofumatt** [comment]
We discussed this on the engineering stand-up and realised it would be best solved with a copy update, as these are sort of bad CTA buttons anyway 😄 

New copy string there could be:

```
The Google Tag on your site is no longer associated with your current Google Analytics 4 property "%1$s (%2$s)". It is now recording metrics to another Google Analytics 4 property "%3$s (%4$s)". If you want to continue seeing Analytics data in the Site Kit dashboard, we suggest you update Site Kit’s Google Analytics configuration to show data for the property used in your Google Tag.

**Use new property** | _Keep existing property_
```

It's a bit less complete in what it's telling users is happening, but I think that makes it easier to understand anyway.

@marrrmarrr Is this new copy okay? If so this is an easy issue to fix without a much more complicated technical solution involved 🙂

**Comment by tofumatt** [comment]
Updated ACs here are good 👍🏻
