### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by ahlamkotb** [google/site-kit-wp#6736]
![Screenshot 2023-03-17 130700](https://user-images.githubusercontent.com/128148457/225898423-7638e163-7e18-40c7-9d2d-7e5e17eda863.png)

**Comment by adamdunnage** [comment]
Hi @ahlamkotb thanks for getting in touch. We don't provide support through GitHub but as mentioned by James on your comment [here](https://github.com/google/site-kit-wp/issues/5175#issuecomment-1473736275), you can use the [plugin support forums](https://wordpress.org/support/plugin/google-site-kit/#new-post) for any queries or assistance with errors you encounter within the plugin.

We also have a [guide on the plugin website](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#amp-cdn-restricted) in relation to this. I will mark this out as closed but we may see you in the support forum.

**Comment by ahlamkotb** [comment]
I'm having trouble registering on plugin support forums
I received an email containing a link to set the password, and when I click on the link, this message appears
![Uploading Screenshot 2023-03-17 144307.png…]()
