### ISSUE TITLE
Allow deselecting UA property and profile

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6748]
## Feature Description

As a part of this epic, going forward, Site Kit will no longer require UA to be connected, i.e. it will be optional. In this scenario, we need to provide a way for users to deselect a UA property/profile in order to effectively not connect/disconnect it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Update the `analytics` `PropertySelect` and `ProfileSelect` components to allow deselecting a choice, and allow submitting with these settings being blank, if the `ga4Reporting` feature flag is enabled.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
Manually selecting a "blank" property/profile seems like a strange UX to me. Instead, wouldn't it be better to have a toggle for "Enable Universal Analytics" that would hide these `<Select>` components entirely?

Sure, in the settings infrastructure we'll want to be able to set them as blank so the user can save their settings without those UA values being required, but in terms of the UI I think it would make more sense to hide these entirely with a checkbox, but require them when the "Use Universal Analytics" option is checked.

What sort of design—if any—do we have for this? In the past we had a checkbox to show/hide GA4 I think, and that seems a better UX (plus: for new users we can hide all the UA stuff except for that one checkbox for a cleaner settings screen.)

**Comment by tofumatt** [comment]
@nfmohit and I chatted about this and he pointed out that this can really be part of #6744… that's a bit better and should avoid some of the UX oddities implementing these ACs on their own would introduce.

I've moved the ACs from here over to #6744 so I'll close this issue. 🙂
