### ISSUE TITLE
Revise wording when editing Analytics settings

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6756]
## Bug Description

There is an "Excluded from Analytics" option within Site Kit that allows users to apply non tracking for logged in users. The title of this setting differs when the view and from the edit screen. 

- View Screen: Excluded from Analytics ✔
- Edit Screen: Exclude Analytics ❌

As an improvement, ensure both match, ideally using the "Excluded from Analytics" text. See an example of the differences below. 

https://user-images.githubusercontent.com/41326532/226591745-d4d64bc4-f962-4b32-9370-c0f1eb8288c6.mp4

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is intentional I believe. The edit view uses a tense that is more consistent with what you are doing there "excluding or not", where as the non-edit view reads more as a status – "excluded: all logged in users". So yes, not 1-1 the same but reads intuitively IMO. Closing for now :)
