### ISSUE TITLE
Fix unstable `time`-based PHPUnit tests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6758]
## Bug Description

We have a few tests which have the potential to fail due to time-related conditions at runtime.

E.g.

```diff
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'foo' => 0
-    'baz' => 1696540077
+    'baz' => 1696540076
 )
```

https://github.com/google/site-kit-wp/blob/9c5f9dc6714c657488ae99a9d193d12bfba8fa4c/tests/phpunit/integration/Core/Dismissals/Dismissed_ItemsTest.php

These should be updated to avoid such failures.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No PHPUnit tests should make assertions that a value should equal the result of a time function (e.g. `time()`) or an expression that uses it in a way that could fail if the value changed between statements during the test
	* Examples already exist in the code base for a reliable strategy, which involves asserting that a time is within a given range that is captured within the test rather than equaling a specific value

## Implementation Brief

* Within `tests/phpunit/integration/Core/Dismissals/Dismissed_ItemsTest.php`, the `test_add()` and `test_remove()` methods and within `tests/phpunit/integration/Core/User_Surveys/Survey_TimeoutsTest.php`, the `test_add()` method should be improved as follows:
    * All `assertEquals` calls which invoke `time()` should be modified to `assertEqualsWithDelta()` with a delta of 2 seconds.

### Test Coverage

* No new tests required.

## QA Brief

* Test should all pass.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Sounds like this should tie in with https://github.com/google/site-kit-wp/issues/6407.

**Comment by bethanylang** [comment]
@jimmymadon Are you planning to work on this soon? If not, can you please unassign yourself so someone else can pick up? Thank you!

**Comment by eugene-manuilov** [comment]
@jimmymadon, how about doing it a bit more precise that just using the "less than" approach. We have the `Date` class in `Core` that is supposed to be used for date time related stuff, but currently it contains only one static method. We can do something like this:

* Update the `Date` class to have a non static method `now()` that returns the current timestamp.
* Add a new interface that declares the `now()` method.
* Update constructors of `Dismissed_Items` and `Survey_Timeouts` classes to accept an instance of the new interface and then instead of calling `time()` they need to call `$this->date->now()` method.
* Create a new class in the `tests/phpunit/includes/Core/Util/` folder that implements the new interface and has an additional method that sets the time we want to get from the `now()` method of that class.
* Finally, update tests to use the new fake date class to pre-set the expected `now()` value and then compare results for the exact match. 

What do you think?

**Comment by eugene-manuilov** [comment]
Ah.. thanks for pointing me to that ticket, @jimmymadon. I'll defer to it to Evan for the final approval, but looks like the approach in IB is what we are going to go with.

**Comment by aaemnnosttv** [comment]
I'm not against building abstractions around dates/times, but there are some instances where this is being used (e.g. in WP core) where it's out of our hands. This issue is about fixing the instability we currently have by updating the tests only. If we want to make a change to how we're using dates internally, I think that would be a bit out of scope here and would ideally be done in a separate issue and applied throughout all at once.

Looking at the current IB, only checking less than would be too loose I think but check greater than as well. That way we're allowing for the smallest variance possible without making the test expect a specific value which is where the fragility is coming from now.

Here's an example of what we're doing now in another test which demonstrates what I'm referring to https://github.com/google/site-kit-wp/blob/a39ca71b6bf69e3f3b07646bc016fec54c8909c7/tests/phpunit/integration/Core/Authentication/Clients/OAuth_ClientTest.php#L267-L274

**Comment by eugene-manuilov** [comment]
Ok, let's go with what we have right now, @jimmymadon, but instead of using lessThanOrEqual, let's use `assertEqualsWithDelta` to ensure that timestamps equal within the certain delta (one or two seconds).

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by benbowler** [comment]
I'm picking this up because I recently wrote a new test like this in #6758 and will update that PR along with addressing this ticket in a new PR.

**Comment by tofumatt** [comment]
All tests pass here so no further QA is needed; moving directly to Approval.

**Comment by zutigrm** [comment]
### QA:Eng Verified

Did not see any remaining spot using assertion without delta on `time()`. PHP tests did not fail, did several runs.

LGTM
