### ISSUE TITLE
Display Google Tag ID in Analytics Settings view

### ISSUE THREAD

**Issue by mxbclang** [google/site-kit-wp#6769]
## Feature Description

Considering the Google tag ID is printed in a sites source code, consider adding this in the view only screen. It doesn't necessarily need to be a configurable option but I do think users will ask about this, unsure of what exactly is printed given it's not their GA4 measurement ID. 

![image](https://user-images.githubusercontent.com/12189958/227267156-cb645a94-1124-4f7d-bbf8-af587ab1d156.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Google Tag ID for GA4 should be exposed on the Analytics settings view
* The tag should be added on the same row as the GA4 property settings, after the measurement ID, and before the link to edit
* Heading `Google Tag ID`
* This should conditionally take effect if the `gteSupport` feature flag is enabled (if it still exists: see #7137)

## Implementation Brief

- In `assets/js/modules/analytics/components/settings/GA4SettingsView.js`:
  - Locate the `div.googlesitekit-settings-module__meta-item` element containing `Measurement ID`. Duplicate it.
  - Only show the duplicated `div.googlesitekit-settings-module__meta-item` if a Google Tag ID exists (which can be obtained by using the `getGoogleTagID` selector from the `modules/analytics-4` selector) and  the `gteSupport` feature flag is enabled (if it still exists: see #7137).
  - Set the title of the meta item to be `Google Tag ID` (translatable).
  - Set the value of the `DisplaySetting` to be the Google Tag ID.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Go to the Analytics settings and ensure that you see Google Tag ID setting if the your site has Google Tag ID.
  * Verify that if your site doesn't have that setting, you don't see the corresponding section on the settings view.

## Changelog entry

* Display Google Tag ID in Analytics Settings view.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Analytics settings includes the Google Tag ID setting if the site has Google Tag ID.
- If the site doesn't have the setting, you don't see the corresponding section on the settings view.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/53196e78-b7fa-48eb-bb79-a3b50d740852)
![image](https://github.com/google/site-kit-wp/assets/73545194/5208cdae-e8be-471a-b965-b4de3e8eae9d)

</details>
