### ISSUE TITLE
Proxy setup URL must contain all required scopes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#677]
## Bug Description

Currently the proxy requests all scopes that have been granted by your Google account, regardless of which site you're using it on.

To solve this, we need to ensure that all require OAuth scopes are passed along in a query parameter in the setup URL for the proxy.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The proxy setup URL must always contain a `scope` parameter which includes the currently required scopes as a space-separated string.

## Implementation Brief

* In `OAuth_Client::get_proxy_setup_url()`, use `$this->get_required_scopes()` to add a `scope` query parameter to the URL (regardless of condition).

## Changelog entry

* Fix authentication service requesting partially incorrect scopes.

**Comment by aaemnnosttv** [comment]
IBR ✅

**Comment by aaemnnosttv** [comment]
CR ✅

**Comment by felixarntz** [comment]
@aaemnnosttv Would be great if you could QA this since it is related to the issue you were describing earlier today.

**Comment by aaemnnosttv** [comment]
## QA: ✅ 

#### Steps taken

1. Start with Google account which has used the Site Kit proxy before, which has already granted scopes for different services (particularly Analytics)  
![image](https://user-images.githubusercontent.com/1621608/67271008-6cefd300-f4c2-11e9-8248-8f2517b2cf70.png)
1. Create a new public site which has never been connected to the proxy service before (using jurassic.ninja)
1. Install Site Kit and initiate set up on proxy
1. Sign in with Google on proxy  
_only scopes required by initial set up were requested_  
![image](https://user-images.githubusercontent.com/1621608/67271440-2f3f7a00-f4c3-11e9-806b-b97f3feb0fce.png)
_did **not** see an unverified app warning_
1. Completed setup on proxy
1. Connect/activate PageSpeed Insights module and verify it works as expected

**Comment by marrrmarrr** [comment]
Verified with two separate sites -- see parameter 
`&scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters`
