### ISSUE TITLE
Removal of permissions to a shared destination should be highlighted to the user

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6770]
## Feature Description

To recreate this scenario, setup a Google tag which points to a shared destination (a property owned by another Google user that has been shared with the current Google user), and use this tag in Site Kit (select that property in Analytics settings).

Then, remove the permission for that property.

When the check for a change in Google tag mapping occurs, no notification is shown to the user, although an error is displayed in the JS console.

![image](https://user-images.githubusercontent.com/12189958/227267630-befc64a5-17f8-49d2-a1e4-db0e243d4a13.png)

Furthermore, the GA4 dropdowns are blank on the Settings page, with no error or other message displayed to the user, but another error in the console:

![image](https://user-images.githubusercontent.com/12189958/227267688-23fe825e-c5ce-424c-98fc-4c3e530d2ac2.png)

The tag setting itself is unchanged, with the gtag still added to the source code with the same tag ID.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
I believe this has been somewhat addressed and there is now inline feedback. See https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-settings-settingsedit--property-not-available

Anything more to address here?
