### ISSUE TITLE
Inconsistent application of capabilities for roles

### ISSUE THREAD

**Issue by curtismchale** [google/site-kit-wp#6771]
## Bug Description

When a site admin gives any role the ability to see the Analytics dashboard via the share settings role doesn't get access to the menu bar dropdown on the frontend of the site. This is true even if you add the custom capability `googlesitekit_view_admin_bar_menu` to the role.

If the role is given access to the analytics dashboard they should get access to the dropdown as well.

In theory the admin bar checks for `Permissions::VIEW_ADMIN_BAR` [here](https://github.com/google/site-kit-wp/blob/cc32591f93df3e29a8ea9d1066ccd61b8a2e729e/includes/Core/Admin_Bar/Admin_Bar.php#L190). This is mapped to the `manage_options` capability in [Permissions.php line 152](https://github.com/google/site-kit-wp/blob/cc32591f93df3e29a8ea9d1066ccd61b8a2e729e/includes/Core/Permissions/Permissions.php#L152). But if you enable sharing in the WP admin [Permissions.php line 154](https://github.com/google/site-kit-wp/blob/cc32591f93df3e29a8ea9d1066ccd61b8a2e729e/includes/Core/Permissions/Permissions.php#L154) says it now maps the `VIEW_ADMIN_BAR_MENU` capability to `edit_posts`  see [Permissions line 171](https://github.com/google/site-kit-wp/blob/cc32591f93df3e29a8ea9d1066ccd61b8a2e729e/includes/Core/Permissions/Permissions.php#L171) and line [155](https://github.com/google/site-kit-wp/blob/cc32591f93df3e29a8ea9d1066ccd61b8a2e729e/includes/Core/Permissions/Permissions.php#L155)

So it reads like roles with the `edit_posts` capability should pass the `current_user_can` check in [Admin_Bar.php line 190](https://github.com/google/site-kit-wp/blob/cc32591f93df3e29a8ea9d1066ccd61b8a2e729e/includes/Core/Admin_Bar/Admin_Bar.php#L190) but they don't.

This can be verified by giving editors permissions to view the dashboard and then visiting the frontend where you don't see the dropdown. Then return `true` in Admin_Bar.php line 190 and they can see the dropdown menu again.

A fix would either be to allow this to show to any role given permissions in the admin, or allow any role given the `googlesitekit_view_admin_bar_menu` capability to view the admin bar.

## Additional Context

 - PHP Version: 8.0
 - Plugin Version: 1.96.0
- WP Version: 6.1.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Hi @curtismchale, thanks for raising this issue. It's a valid point and we do intend to make both the Admin Bar dropdown and the Site Kit Summary widget on the WordPress Dashboard visible to view-only users, in the case where at least one of the Search Console and Analytics modules has been shared with them.

We do have a separate [issue](https://github.com/google/site-kit-wp/issues/7344) to cover that, which I've now added AC and moved forward in our work stream. As a result I'll close this issue, please feel free to monitor https://github.com/google/site-kit-wp/issues/7344 for progress on this feature area.
