### ISSUE TITLE
Feature Proposal: Shortcodes for Showing Custom Google Analytics Statistics in User Account Metaboxes (Front-End)

### ISSUE THREAD

**Issue by alugo** [google/site-kit-wp#6772]
Many websites expand their functionalities thanks to CPTs (Custom Post Types), and users often create these CPTs for various purposes. It would be a great addition to the Site Kit plugin to allow website owners to display customized Google Analytics statistics on the front end of their CPTs. This would provide an easy way for users to obtain valuable information about the performance of their CPTs, such as the number of visitors, visits, cities, countries, and devices, among many other useful statistics that Site Kit already offers to website owners. The ability to use shortcodes to display these statistics on the front end would be an excellent way to help users make informed decisions about the optimization and development of their CPTs.

**Comment by aaemnnosttv** [comment]
Hi @alugo – thanks for the suggestion! Just to clarify, is your idea about surfacing page-specific stats for a logged in admin/editor of that content or about generally exposing these stats on the front end of the website publicly? The former is already possible via the SK integration in the admin bar on the front end, but also from the page-specific dashboard (which is also linked from the admin bar integration).

**Comment by aaemnnosttv** [comment]
Thanks again for the suggestion here. As mentioned before, it's already possible to see page-specific stats through the Site Kit dashboard and admin bar integration. If this is instead about exposing reporting data publicly, this is currently out of scope for the plugin. See #1093

Cheers!
