### ISSUE TITLE
Update the GDPR FAQ question text on the Site Kit WordPress plugin page

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#6773]
## Feature Description

Due to an update to our [GDPR compliance and privacy documentation](https://sitekit.withgoogle.com/documentation/using-site-kit/gdpr-compliance-and-privacy/), we would like to update the answer for our [GDPR FAQ question](https://wordpress.org/plugins/google-site-kit/#is%20site%20kit%20gdpr%20compliant%3F) on the Site Kit WordPress plugin page.

Please update the answer text to the following:

> Is Site Kit GDPR compliant?
> 
> When using Site Kit, site owners are responsible for managing notice and consent requirements – including GDPR requirements – as described in [Google’s Terms of Service](https://policies.google.com/terms?hl=en).
> 
> By default, Site Kit does anonymize IP addresses upon activation of the Google Analytics module. This setting can be turned off in **Site Kit > Settings > Analytics > Anonymize IP addresses**.
> 
> There are a number of third-party plugins that allow you to block Google Analytics, Tag Manager, or AdSense from capturing data until a visitor to the site consents. Some of these work natively with Site Kit by providing plugin-specific configurations. You can find out more about these by visiting our [GDPR compliance and privacy page](https://sitekit.withgoogle.com/documentation/using-site-kit/gdpr-compliance-and-privacy/).

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The answer to the `Is Site Kit GDPR compliant?` question in the plugin's `readme.txt` should be updated as follows

> When using Site Kit, site owners are responsible for managing notice and consent requirements – including GDPR requirements – as described in [Google’s Terms of Service](https://policies.google.com/terms?hl=en).
> 
> By default, Site Kit does anonymize IP addresses upon activation of the Google Analytics module. This setting can be turned off in **Site Kit > Settings > Analytics > Anonymize IP addresses**.
> 
> There are a number of third-party plugins that allow you to block Google Analytics, Tag Manager, or AdSense from capturing data until a visitor to the site consents. Some of these work natively with Site Kit by providing plugin-specific configurations. You can find out more about these by visiting our [GDPR compliance and privacy page](https://sitekit.withgoogle.com/documentation/using-site-kit/gdpr-compliance-and-privacy/).

## Implementation Brief

* Update the relevant section of the readme per the AC

https://github.com/google/site-kit-wp/blob/019189df9848eae3ff4b5fa66886d5d5c9a35152/readme.txt#L99-L103

* Note, WordPress plugin readme markdown syntax is different in some cases, but bold and linked text should work as usual. See https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

### Test Coverage

* No changes

## QA Brief

* Check the readme with the [official validator](https://wordpress.org/plugins/developers/readme-validator/) using the "Raw URL" to the file on the repository

## Changelog entry

* N/A

**Comment by mohitwp** [comment]
### QA Updated ✅ 

- Tested RAW URL with [official validator](https://wordpress.org/plugins/developers/readme-validator/).
- Verified preview with [wpreadme.com](https://wpreadme.com/).
- Verified The answer to the Is Site Kit GDPR-compliant? Question in the plugin's readme.txt updated as per AC.

<details>

![image](https://user-images.githubusercontent.com/94359491/229996238-f657c798-34b9-4af1-b6c8-9e69257254b8.png)

![image](https://user-images.githubusercontent.com/94359491/229996761-c9b00693-3bef-4069-bfc3-45080689a693.png)

</details>
