### ISSUE TITLE
Update unstable `isGatheringData` and `hasZeroData` Jest tests to pass consistently 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6778]
## Bug Description

Recently, jest tests related to the `isGatheringData` and `hasZeroData` selector tests for Analytics and Search Console modules have started randomly failing, especially in CI as seen [here](https://github.com/google/site-kit-wp/actions/runs/4524118857), [here](https://github.com/google/site-kit-wp/actions/runs/4522746056), [here](https://github.com/google/site-kit-wp/actions/runs/4492213908) and [here](https://github.com/google/site-kit-wp/actions/runs/4467688128). The cause of failings are generally unmatched fetch mock for `GET:report` and `POST:data-available` endpoints. These are random and rerunning the test usually passes. 

From my understanding, this is due to the async nature of the resolvers that lose fetch mock contexts. We introduced `waitForDefaultTimeouts` for this when we upgraded to the version of `@wordpress/data` that made the resolves async. My guess is the default timeout is not sufficient for these selectors anymore after they've started depending on the `gathering-data-store` introduced in #5933. 

We should do something to make these tests stable again. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* JS Tests should not randomly fail for the `isGatheringData` and `hasZeroData` selectors of Analytics, Analytics 4 and Search Console modules. 

## Implementation Brief

* The rests fail due to the async nature of the underlying resolvers that sometimes do not get resolved in the currently implemented `5ms` default timeout.
* To fix this, we need to increase the timeout for these specific tests to at least `15ms`.
    * This was determined by trial and error during investigation. See the relevant [slack thread](https://10up.slack.com/archives/CBKKQEBR9/p1684143811549589?thread_ts=1683897831.741209&cid=CBKKQEBR9) for details. 
* In `tests/js/utils.js`:
    * export a new function called `waitForTimeouts`, similar to `waitForDefaultTimeouts`.
        * It will take a timeout (in ms) and wait for the specified time. 
* Update all `isGatheringData` and `hasZeroData` tests in the following files to replace use of `waitForDefaultTimeouts` with the newly created `waitForTimeouts` with `15`. 
    * `assets/js/modules/analytics/datastore/report.test.js`
    * `assets/js/modules/search-console/datastore/report.test.js`
    * `assets/js/modules/analytics-4/datastore/report.test.js`

### Test Coverage

* N/A, ensure the tests pass consistently and reliably in CI and local.

## QA Brief

* This PR fixes the random test failures in the CI; hence it doesn't require any UI/UX testing.

#### QA Eng

* Ensure the `isGatheringData` and `hasZeroData` tests pass and don't randomly fail in CI as well as in the local.

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
Based on the [slack discussion](https://10up.slack.com/archives/CBKKQEBR9/p1684143811549589?thread_ts=1683897831.741209&cid=CBKKQEBR9) and nods, I've added AC and IB here. Cheers.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by tofumatt** [comment]
Moving directly to Approval since no QA is needed here; tests are passing 🎉

**Comment by aaemnnosttv** [comment]
### ❌ Approval

This still has stability issues 😢 

<img width="1173" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/1f60df41-ba7f-4a8a-aa3d-526154828171">

From current develop: https://github.com/google/site-kit-wp/actions/runs/5078419310/jobs/9122898239

**Comment by hussain-t** [comment]
That's weird. Should we increase the timeout to 20 or 25 ms?

**Comment by hussain-t** [comment]
@aaemnnosttv I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/7093) that increases the timeout by 30 ms. I ran the tests multiple times and it is passing. Please LMK if this looks good. Thanks!
