### ISSUE TITLE
Setup of new site fails with "missing parameter: 'nonce'"

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#678]
## Bug Description

When using a ZIP built from `feature/auth-proxy` branch (`npm run release-zip`), I get an error when verifying site ownership using the Google Proxy service.

## Steps to reproduce

1. Go to https://jurassic.ninja/
2. Create a new site
3. Build a release of the plugin from the branch `feature/auth-proxy` (`npm run release-zip`)
4. Upload and activate the plugin
5. Start setup
6. Use a Google Account (note: account in use has previously used the Proxy/Site Kit but this site is brand new)
7. Keep navigating through the screens until you're met with an error: "missing parameter: 'nonce'"

If you go "back" with your browser after encountering the error, then continue as normal: everything works. It seems the plugin-side of the code is not redirecting to a page that includes a proper `nonce` on first request, but does so afterward.

## Screenshots

![2019-10-21 16 08 52](https://user-images.githubusercontent.com/90871/67218047-a02c5680-f41d-11e9-959d-506a66e40636.gif)

## Additional Context

 - PHP Version: N/A
 - OS: MacOS Catalina
 - Browser: Firefox Developer Edition
 - Plugin Version: 29bc78ea6c509af7fb369c55439b69b9fde42d1e
 - Device: Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Fixed on the proxy side.
