### ISSUE TITLE
New Measurement dropdown is hidden by tooltip when no GA4 connected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6780]
## Bug Description

Spotted this while working on testing #6330

Now that we have added the measurement dropdown alongside the property in the Analytics settings, when no GA4 property is set up then the tooltip appears when editing settings. This hides the measurement dropdown until you close down the tooltip.  While all users will be on GA4 in the future, and this tooltip will likely be removed, I thought I would create a ticket in case we wanted to improve the UX/UI here.

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/960d9eac-a244-4d59-b93d-148317a29f61)

## Steps to reproduce

1. Set up Site Kit and Analytics.
2. Remove the GA4 property (run D`ELETE FROM wp_options WHERE option_name = 'googlesitekit_analytics-4_settings';` in the database. 
3. Go to Site Kit settings for Analytics. 
6. Click on the Connect GA4 CTA.
7. See tooltip appear. Close it to reveal the measurement dropdown. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren – I think this should be fine since the property needs to be set first anyways. In this state, the measurement ID select would be disabled with nothing in it anyways.

Closing for now, but let me know if there's anything else I may be missing here.
