### ISSUE TITLE
Warn user about a mismatched data stream URL on the Google Tag ID Mismatch Notification.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6785]
## Feature Description

It's possible to reconfigure the current Google tag to point to a destination data stream that does not match the current site URL. In this situation, the user is not currently alerted to this in the notification banner, but upon updating the measurement ID, it won't work as intended and it won't show up in settings.

We have deliberately not tried to cover all the various edge cases to start with, but we should consider how to address this one.

Note that once https://github.com/google/site-kit-wp/issues/6763 is implemented an error message may be displayed on the settings screen in this scenario.

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/af9d7c4b-91dc-425b-a5ef-57118ca22dbc)

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/12b0f972-2c89-4ee5-970f-6095ea2c265d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is related to #7052 – it's possible we may want to remove the restriction to only surface web datastreams that have a default uri that matches the site's.

**Comment by aaemnnosttv** [comment]
Closing this one as we have decided to remove the limitation around web data streams that are available to see/select in #7052.
