### ISSUE TITLE
Remove UA counterparts after SK no longer shows UA data beginning September 25

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6786]
## Feature Description

Around 90 days after the UA cut-off, Site Kit will no longer show any UA data anymore naturally. At this point, it will not be relevant to keep elements related to UA in Site Kit. Hence, they should be removed.

- Since we will automatically switch sites to GA4 dashboard view, we will no longer need to prompt users to switch over. Hence, the “Switch to GA4 Dashboard View” `BannerNotification` (being added in #6544) should be removed, along with the `shouldPromptGA4DashboardView` selector in the `analytics-4` datastore.
- Since at this point there will be no way to switch back to the UA dashboard view, the dashboard view toggle in Analytics settings (being added in #6547) should be removed.

[Here](https://docs.google.com/document/d/14pCNmdPBqAJ-RfPhbHXfaMhGaPK-n-7F-6Sgujd0XCQ/edit#heading=h.ocr7bivzb5b2) is the relevant part in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* This should only be included v1.110.0, to be released on September 25, 2023. Before merging, please check with @aaemnnosttv and @marrrmarrr.
* The "Switch to GA4 Dashboard View" `BannerNotification` added in #6544 should be removed.
* The `shouldPromptGA4DashboardView()` selector in the `analytics-4` datastore should be removed.
* The "Universal or GA4 toggle" implemented in #6547 should be removed, including the underlying `dashboardView` module setting in the Analytics module.
* The "New" badges added to GA4 metrics in #6552 should be removed. Since the badges are being added with the help of a reusable component, the component shouldn't be removed. Rather, only their consumption to indicate GA4 metrics should be removed. 
* The `Enable Universal Analytics` toggle and the associated UA property and profile dropdowns added in the `SetupFormGA4` component (in #6738) and Analytics `SettingsEdit` (in #6744) should be removed.
* The Dashboard View Indicator added in #6938 should be removed from both Main and Entity dashboards.
  * This AC was added later on 3 August 2023 as the Dashboard View Indicator wasn't available when this issue was specced. It was added mid-flight during the epic exection.

## Implementation Brief

- In `assets/js/components/notifications/BannerNotifications.js`:
  - Remove the usage of the `<SwitchGA4DashboardViewNotification />` component.
- In `assets/js/modules/analytics/datastore/base.js`:
  - Remove usages of the `shouldPromptGA4DashboardView` function.
- In `assets/js/modules/analytics/datastore/settings.js`:
  - Remove the `shouldPromptGA4DashboardView` function.
- Remove the `Dashboard view` setting display and toggle added to the Analytics module settings.
  - To do so, revert all the changes made in PR #6723 to files in the `assets/js/modules/analytics/components/settings` folder.
  - In `assets/sass/components/settings/_googlesitekit-settings-module.scss`:
    - Remove styles for the `.googlesitekit-settings-module__meta-item--dashboard-view` class.
- Remove the `New` badges added to indicate new GA4 metrics.
  - To do so, revert changes made in PR #6776 for the following files:
    - `assets/js/modules/analytics/components/module/ModulePopularPagesWidgetGA4.js`
    - `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/index.js`
- Remove all usages of the `EnableUniversalAnalytics` component in the following files:
  - `assets/js/modules/analytics/components/setup/SetupFormGA4.js`
  - `assets/js/modules/analytics/components/settings/SettingsForm.js`
- The Analytics module `SettingsView` should be restructured following [this Figma screen](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=562-8638&t=BPBoEvLnYHLMIYxY-0).
  - In `assets/js/modules/analytics/components/settings/SettingsView.js`:
    - Add a new setting meta item at the first position before all other settings, labelled `Account`, which should display the account ID. This can be copied over from `assets/js/modules/analytics/components/settings/GA4SettingsView.js`.
    - Remove the usage of the `<UASettingsView />` component.
  - In `assets/js/modules/analytics/components/settings/GA4SettingsView.js`:
    - Remove the `Account` setting meta item.
- Remove the following files:
  - `assets/js/components/notifications/SwitchGA4DashboardViewNotification.js`
  - `assets/js/components/notifications/SwitchGA4DashboardViewNotification.stories.js`
  - `assets/js/modules/analytics/components/common/EnableUniversalAnalytics.js`

### Test Coverage

- In `assets/js/modules/analytics/datastore/settings.test.js`:
  - Remove test cases for the `shouldPromptGA4DashboardView` selector.
- Remove all VRT references added in PR #6723.
- Revert changes to the pre-existing VRT references made in PR #6776 (only revert change to the updated VRT references. Leave the newly added ones intact).
- Update any other failing VRT scenarios.
- No tests need to be added.
- Fix any failing tests.

## QA Brief

* Go through the Site Kit set up flows both with Analytics and without. For the version without, set up Analytics after testing without.
* View and edit Analytics settings. Ensure no errors occur.
* Set up Dashboard sharing for Analytics. Ensure a second user can view the shared dashboard.

In all of these scenarios, no UA/GA4 Dashboard View switcher should appear and UA components should not appear in the dashboard view, settings view, or settings edit.

It would also be preferable to upgrade an existing site that had UA Analytics enabled and the UA dashboard enabled. It should show the GA4 dashboard after upgrading to the latest version of Site Kit in `develop`.

## Changelog entry

* Remove option to connect Universal Analytics and update dashboard to show GA4 only.

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit – this looks like a good start. Of course there is a lot more to do about UA than is encompassed here, but I think it makes sense to have this issue dedicated to the GA4-reporting-specific transitional related bits. We'll probably need several more issues to migrate Analytics back to a single module going forward.

> * This should only be included in the Site Kit update/release that goes on/right after September 1, 2023.

While correct, since everything here is about removing code that is no longer used, the timing can be flexible and should probably be worded to be more like "after" a certain date, but also to check with @marrrmarrr and/or myself first before merging. As such it is not particularly time-sensitive, but more that we want to ensure it is not merged before we're ready. That is, doing this later would be fine, but not early :)  

> * The "Universal or GA4 toggle" implemented in [Add `dashboardView` toggle in Analytics settings #6547](https://github.com/google/site-kit-wp/issues/6547) should be removed.

I assume we'd also want to remove the corresponding setting itself as well?

> * The "New" badges added to GA4 metrics in [Add "NEW" badge for GA4 metrics #6552](https://github.com/google/site-kit-wp/issues/6552) should be removed.

We probably want to keep the component itself (since it's no longer metric-specific) – we'll probably be using it somewhere else anyways, but we should make it clear that this is only about the use of the badges for GA4 metrics, not the component itself 👍 

> * The `Enable Universal Analytics` toggle and the associated UA `PropertySelect` and `ProfileSelect` components added in the `SetupFormGA4` component (in [Create new `SetupFormGA4` component #6738](https://github.com/google/site-kit-wp/issues/6738)) and Analytics `SettingsEdit` (in [Update Analytics SettingsEdit and SettingsView to work without UA #6744](https://github.com/google/site-kit-wp/issues/6744)) should be removed.

Similar to above, any related persistent settings/values should also be removed, not just the component.

**Comment by nfmohit** [comment]
> Thanks @nfmohit – this looks like a good start. Of course there is a lot more to do about UA than is encompassed here, but I think it makes sense to have this issue dedicated to the GA4-reporting-specific transitional related bits. We'll probably need several more issues to migrate Analytics back to a single module going forward.

Understood and agreed, thank you!


> > * This should only be included in the Site Kit update/release that goes on/right after September 1, 2023.
> 
> While correct, since everything here is about removing code that is no longer used, the timing can be flexible and should probably be worded to be more like "after" a certain date, but also to check with @marrrmarrr and/or myself first before merging. As such it is not particularly time-sensitive, but more that we want to ensure it is not merged before we're ready. That is, doing this later would be fine, but not early :)

Updated, thanks!

> > * The "Universal or GA4 toggle" implemented in [Add `dashboardView` toggle in Analytics settings #6547](https://github.com/google/site-kit-wp/issues/6547) should be removed.
> 
> I assume we'd also want to remove the corresponding setting itself as well?

Correct, updated, thank you!

> > * The "New" badges added to GA4 metrics in [Add "NEW" badge for GA4 metrics #6552](https://github.com/google/site-kit-wp/issues/6552) should be removed.
> 
> We probably want to keep the component itself (since it's no longer metric-specific) – we'll probably be using it somewhere else anyways, but we should make it clear that this is only about the use of the badges for GA4 metrics, not the component itself 👍

Agreed. Updated to clarify, thanks!

> > * The `Enable Universal Analytics` toggle and the associated UA `PropertySelect` and `ProfileSelect` components added in the `SetupFormGA4` component (in [Create new `SetupFormGA4` component #6738](https://github.com/google/site-kit-wp/issues/6738)) and Analytics `SettingsEdit` (in [Update Analytics SettingsEdit and SettingsView to work without UA #6744](https://github.com/google/site-kit-wp/issues/6744)) should be removed.
> 
> Similar to above, any related persistent settings/values should also be removed, not just the component.

I re-checked and discussed it internally. There aren't any other settings/values to remove at this point, thank you!

Thank you, @aaemnnosttv!

**Comment by aaemnnosttv** [comment]
Made a few tweaks to the wording but this should be good to go now 👍 On to IB 🚀

**Comment by tofumatt** [comment]
I think this IB covers it—if anything else is found in Execution that's fine, IBs like this are good baseline guidelines but it can be tough to spot everything in advance.

IB ✅

**Comment by nfmohit** [comment]
I have just added a new AC to this issue:

> The Dashboard View Indicator added in [Add visual indicator for GA4 vs. UA dashboard #6938](https://github.com/google/site-kit-wp/issues/6938) should be removed from both Main and Entity dashboards.
> * This AC was added later on 3 August 2023 as the Dashboard View Indicator wasn't available when this issue was specced. It was added mid-flight during the epic execution.

Apologies for adding it at this stage. I only added it since it needs to be removed alongside other elements mentioned in this issue and is a relatively small change. Thanks!

CC: @hussain-t @aaemnnosttv @tofumatt @bethanylang

**Comment by bethanylang** [comment]
Noting that per discussion with @marrrmarrr in Slack, this issue will be scheduled for Sprint 110 so that it will be included in v.1.110.0, releasing September 25.

**Comment by techanvil** [comment]
Mariya has given the signal, this is getting merged! :tada:

**Comment by wpdarren** [comment]
QA Update:  ✅ 

**Verified:**

_Tested with a new Analytics account that just has a GA4 property_

- Set up a new site with and without SC and Analytics. 
  - No errors on front end or in the console when setting up
  - No errors in the console on the main dashboard. 
  - Changed date period for reporting, 7, 14, 28 and 90 days to ensure no errors occur on the main dashboard. 
  - Made sure the widgets were GA4 components. 
  -  No errors in the console on the entity dashboard. 
  -  Changed date period for reporting, 7, 14, 28 and 90 days to ensure no errors occur on the entity dashboard. 
  - Made sure the widgets were GA4 components. 

- Checked Analytics settings and no reference to the dashboard view or UA can be found here. 
  - No errors in the console within view or edit settings. 
  - Created new GA account, property, etc. from within settings. 

_Tested with an Analytics account that has a UA and GA4 property._

- Used oi.ie as my test site: with SC and Analytics.  No toggle appears when setting up Analytics  
  - No errors on front end or in the console when setting up
  - No errors in the console on the main dashboard. 
  - Changed date period for reporting, 7, 14, 28 and 90 days to ensure no errors occur on the main dashboard. 
  - Made sure the widgets were GA4 components. 
  -  No errors in the console on the entity dashboard. 
  -  Changed date period for reporting, 7, 14, 28 and 90 days to ensure no errors occur on the entity dashboard. 
  - Made sure the widgets were GA4 components. 

- Checked Analytics settings and no reference to the dashboard view or UA can be found here. 
  - No errors in the console within view or edit settings. 
  - Created new GA account, property, etc. from within settings. 

- Setup Dashboard Sharing for Analytics  
  -  No errors in the console on the main view only dashboard. 
  - Changed date period for reporting, 7, 14, 28 and 90 days to ensure no errors occur on the  main view only dashboard. 
  - Made sure the widgets were GA4 components. 
  -  No errors in the console on the view only entity dashboard. 
  -  Changed date period for reporting, 7, 14, 28 and 90 days to ensure no errors occur on the view only entity dashboard. 
  - Made sure the widgets were GA4 components. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/4280823f-d58c-4ee3-8647-d41a556e9abd)
![image](https://github.com/google/site-kit-wp/assets/73545194/6776f03e-e4ed-44b5-bf6a-c599d4f5042a)
![image](https://github.com/google/site-kit-wp/assets/73545194/bcf032d6-bea1-466f-9a7d-5e3fd7ec8bdd)
![image](https://github.com/google/site-kit-wp/assets/73545194/319846b4-ca7a-4037-a951-8fc0e5827b11)
![image](https://github.com/google/site-kit-wp/assets/73545194/4fc58037-ecf9-4ed3-9c1f-4be2b5a50e32)
![image](https://github.com/google/site-kit-wp/assets/73545194/23991876-16cd-46d6-92d1-8b9cd84678f4)
![image](https://github.com/google/site-kit-wp/assets/73545194/42dd7f57-b85e-42ab-921f-261d5576593c)
![image](https://github.com/google/site-kit-wp/assets/73545194/887be467-40dc-4622-a162-46d729d82619)

</details>
