### ISSUE TITLE
Page Speed Insights - Data Error on Subdomains

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#68]
**Describe the bug**
Tested on site hosted within subdomain and subpath (demo.***.io/sample).
Newly setup site, Site Kit just added, API key is correct and no restrictions, copied as per setup process. PageSpeed services/module is appearing as "Connected" under 'connected services' tab in Site Kit Admin.

**To Reproduce**
Install Site Kit on subdomain & subpath. 

<img width="1467" alt="Screen Shot 2019-06-26 at 2 23 58 PM" src="https://user-images.githubusercontent.com/41326532/60183371-13caa800-981e-11e9-80fc-dae98368edc3.png">

<img width="1488" alt="Screen Shot 2019-06-26 at 2 25 09 PM" src="https://user-images.githubusercontent.com/41326532/60183462-4aa0be00-981e-11e9-9e86-3fd4b8d1328d.png">

pagespeed-insights::site-pagespeed-desktop::last-28-days::d41d8cd98f00b204e9800998ecf8427e: {errors: {400: ["Bad Request"]}, error_data: {400: {status: 500, reason: "keyInvalid"}}}
error_data: {400: {status: 500, reason: "keyInvalid"}}
errors: {400: ["Bad Request"]}
pagespeed-insights::site-pagespeed-mobile::last-28-days::d41d8cd98f00b204e9800998ecf8427e: {errors: {400: ["Bad Request"]}, error_data: {400: {status: 500, reason: "keyInvalid"}}}
error_data: {400: {status: 500, reason: "keyInvalid"}}
errors: {400: ["Bad Request"]}

Response: 
{"pagespeed-insights::site-pagespeed-mobile::last-28-days::d41d8cd98f00b204e9800998ecf8427e":{"errors":{"400":["Bad Request"]},"error_data":{"400":{"status":500,"reason":"keyInvalid"}}},"pagespeed-insights::site-pagespeed-desktop::last-28-days::d41d8cd98f00b204e9800998ecf8427e":{"errors":{"400":["Bad Request"]},"error_data":{"400":{"status":500,"reason":"keyInvalid"}}}}

**System Information (please complete the following information):**
WordPress Version: 5.2.2
Web Host OS: Linux
Site Kit Plugin version: 1.0.0-beta.1
Browser: Chrome
Operating System: Macos 10.13.6
PHP Version: 7.2

**Comment by ivankristianto** [comment]
@jamesozzie 
from the error response I see it's because the `keyinvalid`.
Can you please try reset site kit, and try to activate PSI module again, and ensure you copy the correct API Key?

**Comment by jamesozzie** [comment]
Thanks @ivankristianto. Thanks for the update. It's working fine when I reset, I never made any changes or set restrictions on that project in GCP. I copied and pasted the API directly. But if it arises again I will report.

**Comment by jamesozzie** [comment]
@ivankristianto. I have a video [here](http://recordit.co/Xc27hNwHAP 
) where you can see the issue again, not just on a subdomain. Would there be something else causing this? Even after resetting Site Kit and repeating the process using incognito mode:

**Comment by ivankristianto** [comment]
@jamesozzie can you check for excess spaces in the api key?
related to this issue #81

**Comment by jamesozzie** [comment]
@ivankristianto While there appears to be an additional space in the generated API key this is not the cause of the problem, as the copied API key does not include this space (copied directly via the copy button or copied via selecting the text, copying & pasting). This is not the root cause of this issue.

![ZrqUCVFviS](https://user-images.githubusercontent.com/41326532/60528323-1df01900-9cec-11e9-887a-970764b08a84.gif)

**Comment by ivankristianto** [comment]
@jamesozzie 
If it is a correct API key, the other possible way is you might have API restriction set for your API.
Can you check it in GCP dashboard?
What do you have in that key setting? You can check it with this link: https://console.cloud.google.com/apis/credentials

ANd here is the screenshot look like
![Screen Shot 2019-07-03 at 15 16 55](https://user-images.githubusercontent.com/656006/60581520-2f4f2900-9db1-11e9-89fa-a44d192ad7a2.png)

**Comment by jamesozzie** [comment]
@ivankristianto There are no restrictions set, see below:

<img width="897" alt="Screen Shot 2019-07-03 at 11 42 13 AM" src="https://user-images.githubusercontent.com/41326532/60585435-aa034e80-9d87-11e9-9622-0d2799ac07bf.png">

**Comment by marrrmarrr** [comment]
Let's re-test this after #81 is fixed.
