### ISSUE TITLE
Post UA cut off warning notice positions under settings view is not same as Figma Design.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6809]
## Bug Description

 Post UA cut off warning notice positions under settings is not same as Figma design.
## Steps to reproduce

1. Set up Site Kit with Analytics connected but GA4 not connected, and enable the ga4Reporting feature flag.
2. Navigate to the Main Dashboard and set the current reference date to be on or after July 1st, 2023:
`googlesitekit.data.dispatch('core/user').setReferenceDate('2023-07-01')`
3. Navigate to the Analytics settings page.
4. Verify the warning notice appears, in both the view and edit modes.

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/229046102-93123c53-75c8-4fc7-957d-4b9c14dae1d4.png)

![image](https://user-images.githubusercontent.com/94359491/229046158-8ded0f16-89e7-400f-9eff-738fb75d6f4b.png)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- In Analytics `SettingsEdit` and `SettingsView`, the `SettingsUACutoffWarning` should be repositioned to appear after the dashboard view setting.

## Implementation Brief

- In `assets/js/modules/analytics/components/settings/SettingsForm.js`:
  - Relocate the `<SettingsUACutoffWarning>` component to appear after the `Dashboard View` setting (`<GA4DashboardViewToggle>`).
- In `assets/js/modules/analytics/components/settings/SettingsView.js`:
  - Relocate the `<SettingsUACutoffWarning>` component to appear after the `Dashboard View` setting.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Install and activate the Site Kit plugin.
* Connect Google Analytics, but do not connect a GA4 account, only a UA account.
* If forced to connect a GA4 account, or if the environment already contains a GA4 account, it can be manually removed by deleting said reference from the WordPress database manually. To do so, run the following command agains your test WordPress sites database:

```
DELETE FROM wp_options WHERE option_name = 'googlesitekit_analytics-4_settings';
```

* Ensure that the `ga4Reporting` feature flag is enabled via the tester settings plugin.
* Navigate to the Site Kit settings page via `Site Kit > Settings` in the left WP admin menu.
* Note the "Analytics" section, it should visually display a notice on the right of the pane stating that GA4 is disconnected via a "Connect Google Analytics 4" CTA button, this is a visual indicator that GA4 is not connected and we can proceed to test the notice placement.
* Expand the "Analytics" settings pane.
* Validate that the UA cutoff notice renders in the expected position, directly below the "Universal Analytics" label.
* Proceed to edit the settings via the "Edit" CTA near the bottom of the settings pane.
* Once in settings edit view, validate that the UA cutoff notice renders in the expected position, directly below the "Universal Analytics" label.

Following are 2x screenshots indicating what correct placement should look like for settings view and settings edit screens when GA4 is not connected.

**Settings View**
<img width="1286" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/96927580-7f3a-43b0-befb-dcca0b09d8a3">

**Settings Edit**
<img width="1288" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/dde20f76-9908-4fe3-a128-c811728b76a7">

## Changelog entry

* Move Universal Analytics notice in settings page.

**Comment by mohitwp** [comment]
cc @wpdarren

**Comment by aaemnnosttv** [comment]
Thanks @mohitwp – this will be addressed by the following issue:
- #6702

**Comment by bethanylang** [comment]
Per [discussion in Slack](https://10up.slack.com/archives/CBKKQEBR9/p1682340113933369), reopening this issue.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by 10upsimon** [comment]
Flagging that this issue lacked VRT change coverage. VRT references needed to be updated following position updates on said UA notice/warning.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When in Analytics settings view and edit, the UA cutoff notice renders in the expected position, directly below the "Universal Analytics" label. 
- Also checked the UI/UX on smaller view ports to make sure the notices render correctly. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/765899f5-c87e-4202-9607-a9fada6a47c1)
![image](https://github.com/google/site-kit-wp/assets/73545194/9eb9b8d2-4ad6-4603-86d7-31e42df273c8)

</details>
