### ISSUE TITLE
Improve "Your Google tag configuration has changed" banner UX.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6819]
## Bug Description

If zero data banner exist then before loading the "Your Google tag configured has changed" banner for few seconds Zero or gathering state banner appears before loader.

When we refresh the page, "Your Google tag configured has changed" banner is hidden. This can be a case because I'm using `googlesitekit.api.set('modules', 'analytics-4', 'settings', {'googleTagLastSyncedAtMs': 0});` to display it. But, make sure banner do not get hide if we want to show it until user complete any action. 

## Steps to reproduce

Follow steps to reproduce listed under https://github.com/google/site-kit-wp/issues/6766

## Screenshots

https://user-images.githubusercontent.com/94359491/229474273-fa580016-c3ce-40d3-8d94-d99092f019ee.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Once the condition are met for the `GoogleTagIDMismatchNotification` banner to appear, it should continue to appear until the user interacts with it using the CTA.

## Implementation Brief

* [ ] Update `includes/Modules/Analytics_4.php`
  * [ ] Add new method `inline_tag_id_mismatch`, it should include the `hasMismatchedTag` property, and retrieve the value from the transient, say `googlesitekit_inline_tag_id_mismatch`. You can mimic the `inline_custom_dimensions_data` method. Although it should be modified to take into account that `analytics-4` key might already exist vs setting it here, or change the hook order so new method adds data after the custom dimensions sets it first.
  * [ ] Update `get_datapoint_definitions` method
    * Include new datapoint, say `POST:set-google-tag-id-mismatch`
    * You can use the same definition array as here https://github.com/google/site-kit-wp/blob/39347c0732af356a099d9e81811835da929b7f2b/includes/Modules/Analytics_4.php#L516-L518
  * [ ] Update `create_data_request` method
     * Add callback for datapoint included above
     * Include `hasMismatchedTag` as required param and handle `missing_required_param` error if not present
     * Check if the value is `false` to delete the `googlesitekit_inline_tag_id_mismatch` transient ( you can invoke `$this->transients->delete` ), so we do not store unnecessary transient data, as we will return false anyway if transient does not exist.
     * Otherwise set the transient with the received value
* [ ] In `assets/js/modules/analytics-4/datastore/properties.js`
  * [ ] Create new fetch store, say `fetchSetGoogleTagIDMismatch`. Target the new datapoint, and update `hasMismatchedTag` in reducer callback.
  * [ ] Update `setHasMismatchedGoogleTagID` action to invoke the new fetch store action
  * [ ] Update `baseInitialState` - add `hasMismatchedTag` property and set initial value as false
  * [ ] Add new action `receiveHasMismatchGoogleTagID`
    * It should receive one parameter `hasMismatchedTag` and yield the value to the reducer
  * [ ] Add resolver `hasMismatchedGoogleTagID`
    * If `hasMismatchedTag` is `undefined` It should get the value from the inline data property e.q `global._googlesitekitModulesData?.[ 'analytics-4' ]?.hasMismatchedTag` and pass it to the `receiveHasMismatchGoogleTagID`
  * [ ] Edit the reducer to update `hasMismatchedTag` once action to set is fired

### Test Coverage

* Update/fix the the tests in `assets/js/modules/analytics-4/datastore/properties.test.js`. Include tests for new actions
* Update Analytics 4 test to include new datapoint in the existing tests

## QA Brief

* Follow steps to reproduce listed under https://github.com/google/site-kit-wp/issues/6766
* Verify that banner remains visible on page reload, until CTA is clicked

## Changelog entry

*  Update the Google Tag Mismatch notification to persist until a user dismisses it.

**Comment by tofumatt** [comment]
ACs make sense here, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
> If zero data banner exist then before loading the "Your Google tag configured has changed" banner for few seconds Zero or gathering state banner appears before loader.

This is probably not perfect but unfortunately unavoidable because it takes some time to load information from Google API to detect whether the tag configuration is mismatched. 

> When we refresh the page, "Your Google tag configured has changed" banner is hidden. This can be a case because I'm using `googlesitekit.api.set('modules', 'analytics-4', 'settings', {'googleTagLastSyncedAtMs': 0});` to display it. But, make sure banner do not get hide if we want to show it until user complete any action.

So, I believe this is the main cause for this ticket, right @mohitwp? If so, then this ticket is probably no-go because that was done on purpose to make sure that we don't send excessive Google API requests on each page load. cc @aaemnnosttv

**Comment by hussain-t** [comment]
>So, I believe this is the main cause for this ticket, right @mohitwp? If so, then this ticket is probably no-go because that was done on purpose to make sure that we don't send excessive Google API requests on each page load. cc @aaemnnosttv

Thanks, @eugene-manuilov, I get your point. However, according to the AC, don't we need to show the banner until the user interacts with it?

>Once the condition are met for the `GoogleTagIDMismatchNotification` banner to appear, it should continue to appear until the user interacts with it using the CTA.

**Comment by eugene-manuilov** [comment]
@hussain-t, AC changes the current behaviour of the user interface. We need to coordinate it with @aaemnnosttv before making such decisions.

**Comment by aaemnnosttv** [comment]
The current IB isn't viable as it would cause the tag settings to be fetched on every load of the dashboard as the action is currently hooked into the `DashboardEntryPoint` mount. We'll need to find another way to achieve this (without requiring excessive changes), or leave it as-is.

**Comment by bethanylang** [comment]
@eugene-manuilov Are you still planning to work on this soon? If not, can you please unassign yourself so someone else can pick up? Thank you!

**Comment by eugene-manuilov** [comment]
Yes, will look at it this week.

**Comment by eugene-manuilov** [comment]
Ok, assigning this ticket back to @hussain-t to rework IB. The main point here is that we need to figure out a way how to preserve that notification between page refreshes if we detect that the Google tag configuration has changed.

I think we can implement something similar as we use for data availability logic. So whenever we see that we need to show that banner, we save a flag in WordPress that indicates that Google tag has changed and when the user visits the dashboard page next time we pre-load that flag and show that banner to them.

> Fixing the "Zero or gathering state" banner's visibility before the loader is problematic.

No need to worry about this. It is not the problem. Let's remove this part from IB.

**Comment by benbowler** [comment]
@hussain-t happy for me to have a go at this IB?

**Comment by hussain-t** [comment]
@benbowler, sure, go ahead 👍

**Comment by benbowler** [comment]
Removing myself from this one as I'm not familiar enough with the data availability logic yet to create a timely IB.

**Comment by zutigrm** [comment]
@eugene-manuilov I updated the IB to be something similar with the data available approach as you suggested in your last comment above. 

Let me know what you think

Thanks

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm.

> * Update `baseInitialState` - add `hasMismatchedTag` property and get value from the inline data property e.q `global._googlesitekitModulesData?.[ 'analytics-4' ]?.hasMismatchedTag`

We need to create a resolver for the `hasMismatchedGoogleTagID` selector and set `hasMismatchedTag` there using the `setHasMismatchedGoogleTagID` action if it hasn't been set yet.  The only problem is that if we do it this way it will trigger your new fetch store, which is not good. So, we need to figure out how to resolve this problem.

**Comment by zutigrm** [comment]
@eugene-manuilov I though initially to get value from global directly in `initialState`, but your point makes more sense, event it is inline data it might not be loaded at point we set the store. 

Since we do not need to explicitly use `setHasMismatchedGoogleTagID` in resolver, as this action should handle saving of new data in transient, I introduced `receiveHasMismatchGoogleTagID` action which would handle updating the `hasMismatchedTag` value in the state through reducer. 

Let me know what you think of this approach

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Testing using steps to reproduce.
- Verified that flicker issue is not reproducing now.
- Verified that once the condition are met for the `GoogleTagIDMismatchNotification` banner to appear, it continue to appear until the user interacts with it using the CTA.

<details>


https://github.com/google/site-kit-wp/assets/94359491/c7042685-9fc3-455f-aafc-b5a6e8184dea

</details>
