### ISSUE TITLE
Pagespeed Insights cannot be deactivated once activated.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#682]
## Bug Description

Pagespeed Insights cannot be deactivated once activated.

Discovered during QA of new PSI setup flow, see https://github.com/google/site-kit-wp/issues/511#issuecomment-544691379

## Steps to reproduce

1. Activate Pagespeed Insights from Site Kit -> Settings -> Connect More Services
2. Go back to Site Kit -> Settings -> Connected Services
3. Note no edit button, no way to disconnect Pagespeed Insights service.

### Expected behavior
I should be able to deactivate Pagespeed Insights.

## Screenshots

No edit button for PSI:
![image](https://user-images.githubusercontent.com/2676022/67240872-90a61100-f40f-11e9-98ef-7f5d1659812c.png)

For Analytics for example, I have an edit button:
![image](https://user-images.githubusercontent.com/2676022/67240981-ca771780-f40f-11e9-8b65-89453fb403bb.png)
![image](https://user-images.githubusercontent.com/2676022/67241083-001c0080-f410-11e9-8475-a1d1f7d544bf.png)

Once I click that there is an option to Disconnect Analytics:
![image](https://user-images.githubusercontent.com/2676022/67241117-1033e000-f410-11e9-9e31-a5ec4f8b556b.png)

## Additional Context

 - PHP Version: 7.2
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome Dev
 - Plugin Version Testing on `feature/auth-proxy`  branch
 - Device: [e.g. iPhone6] Mac

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PageSpeed Insights should display an "Edit" link in Settings that, when clicked, exposes the expected UI to deactivate the module.
* It must remain impossible to deactivate the Search Console module.
* All modules should expose their settings info (if there is any) as before.

## Implementation Brief

* Allow all settings modules to be edited and disconnected using the admin settings page
* Remove PageSpeed Insights from the list in https://github.com/google/site-kit-wp/blob/be8569481d31a3a1d31bbaa42be4ebbac5b02bae/includes/Core/Modules/Module.php#L205. This will allow it to be edited and deleted.

## Changelog entry

* Ensure that PageSpeed Insights module can be deactivated again once activated.

**Comment by felixarntz** [comment]
@tofumatt Have you ensured that removing the `hasSettings` does not have any other side effects? (e.g. there are modules, like PSI, that we should be able to disconnect but that shouldn't display any settings UI)

I'm 100% behind removing `hasSettings`, that's something I've been wanting to do for a while. One thing we need to make sure is that the Search Console module (and Site Verification, which is invisible anyways) cannot be disconnected (that must be the only one like that). For that you should be able to rely on the `force_active` value (`autoActivate` in JS).

**Comment by tofumatt** [comment]
It looks like the only component to behave oddly when entirely removing `hasSettings` is Search Console:

![2019-11-19 22 53 14](https://user-images.githubusercontent.com/90871/69193754-6b481800-0b1f-11ea-910a-f391104b6465.gif)

I think it makes sense to hide the "edit" functionality of Search Console as it's linked with Site Kit setup, but other components seem to behave alright:

![2019-11-19 23 33 29](https://user-images.githubusercontent.com/90871/69196233-c5e47280-0b25-11ea-943c-ada5373bcef3.gif)

So it looks like we should prevent the search console from showing the "edit" button, but everything else is okay...

**Comment by felixarntz** [comment]
@tofumatt IB looks good, however I think we should keep the content empty and not add wording as part of the IB. I agree it's a bit weird to have an empty content, but this issue is only about fixing the problem of not being able to disconnect.

**Comment by tofumatt** [comment]
That sounds like the right eventual approach, but if we just want to hook up the component to be disconnected it's best to delay that until later; admittedly this will only affect PageSpeed for now and I think that refactor will likely need to happen again after JSR and isn't worth the additional effort/time for now. I've amended the IB to simply allow the user to disconnect for now.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

After activation, Pagespeed Insights module shows an edit button in its module settings
![image](https://user-images.githubusercontent.com/1621608/71968626-f7b4b400-320d-11ea-84c5-221c58b2aa54.png)

Clicking the edit button reveals the disconnect action link
![image](https://user-images.githubusercontent.com/1621608/71968613-f4b9c380-320d-11ea-9857-bbbc081c32dc.png)

The disconnect confirmation modal appears just like other modules
![image](https://user-images.githubusercontent.com/1621608/71968603-f2f00000-320d-11ea-9148-374dafa14a9d.png)

After confirming, the Pagespeed Insights module displays the CTA component as it is now inactive
![image](https://user-images.githubusercontent.com/1621608/71968599-f08da600-320d-11ea-81b1-38ff6f7eb768.png)

Moving to Approval

**Comment by marrrmarrr** [comment]
LGTM
