### ISSUE TITLE
Update URL for dev settings plugin

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6823]
## Feature Description

When setting up Site Kit, a number of health checks are performed to flag potential issues that can be detected which may block or otherwise hamper the ability to use Site Kit.

In some situations, we surface the Site Kit Developer Settings plugin which is externally managed (i.e. not on wp.org). This is being migrated to GCS instead of part of the Site Kit service. This updates its "updates URL" accordingly.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The URL for the Developer Settings plugin info should be updated to:
```
https://storage.googleapis.com/site-kit-dev-plugins/google-site-kit-dev-settings/updates.json
```

## Implementation Brief

* Update the following URL to the one in the AC https://github.com/google/site-kit-wp/blob/216103df16fe39ae25f85573bcaa6cd93addbc13/includes/Core/Util/Developer_Plugin_Installer.php#L188

### Test Coverage

* No changes necessary

## QA Brief

* N/A

## Changelog entry

* Update the dev settings plugin update URL.

**Comment by tofumatt** [comment]
Moving directly to Approval as no QA is needed for this issue.
