### ISSUE TITLE
Analytics widgets not displaying in view-only dashboard without UA connected

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6824]
## Bug Description

When the Analytics module is connected in Site Kit ~~with only GA4 without UA~~, we've encountered issues with Dashboard Sharing not working as expected. #6745 aims to solve the module sharing settings synchronisation for the module owners, but there's another issue where the Analytics widgets do not show up in the view-only dashboard at all ~~if UA is not connected~~.

## Steps to reproduce

1. Set up Analytics in Site Kit with only GA4 entities, not connecting UA (or connecting it!).
2. Using the Dashboard Sharing settings modal, share the Analytics 4 module with other admins.
3. Log into the site as another admin user. Access the Site Kit view-only dashboard.
4. Notice that no Analytics widgets show up.

## Screenshots

![image](https://user-images.githubusercontent.com/20284937/230222277-c0d057f0-fdd8-47c6-9197-2a03ed7bc981.png)

## Additional Context

This happens because the widgets registered for Analytics are specified to the `analytics` module. Example:

https://github.com/google/site-kit-wp/blob/ed6c98117ef13314cb190083ddee547fb45d3a3d/assets/js/modules/analytics/index.js#L65-L84

Without UA connected, the `analytics` module doesn't come up as a shareable and a viewable module. We need to update the `modules` array so that it conditionally sets `analytics` or `analytics-4` based on the current dashboard view.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Analytics widgets should show up correctly in the view-only dashboard, regardless of how they're set up (with or without UA & GA4).

#### Update client-side settings to allow initial values to be passed in.

Within `assets/js/googlesitekit/data/create-settings-store.js`:

- Update `createSettingsStore()` to support an additional optional `settings` property passed in `options`.
- `settings` should be an object of setting keys to values, and it should be used as the value of `settings` in `initialState`.

Within `assets/js/googlesitekit/modules/create-module-store.js`:

- Extend `createModuleStore()` to allow `settings` to optionally be passed in, and pass this through to `createSettingsStore()`.

#### Add the current `dashboardView` setting to the `_googlesitekitDashboardSharingData` global.

Within `includes/Modules/Analytics.php`:

- Add a filter hook for `googlesitekit_dashboard_sharing_data`.
- Within the filter hook callback, check if the current mode is view-only, by checking `$this->authentication->is_authenticated()` - if it returns false, the mode is view-only.
- If the mode is view-only, add a `dashboardView` key to the data object with the value of the current `dashboardView` setting.

#### Provide the `dashboardView` setting to client-side Analytics settings when in view-only mode.

Within `assets/js/modules/analytics/datastore/base.js`:

- Check to see if `dashboardView` is defined on the global `_googlesitekitDashboardSharingData` object.
- If so, pass a `settings` object with `dashboardView` as the only property to the `createModuleStore()` call.

#### Allow widget definitions to include an optional `isActive()` callback which is passed a registry `select` function.

Within `assets/js/googlesitekit/widgets/datastore/widgets.js`:

- Update `registerWidget()` to allow an optional `isActive()` callback to be passed as part of `settings`.
  - Ensure this is passed through as part of the payload.
- Update `getWidgets()` to use `createRegistrySelector()`, and update the filtering of the widgets to include a check for `widget.isActive( select )` if the `isActive()` callback is defined.

### Remove `GA4DashboardWidgetSwitcher` and instead create two definitions for each of the widgets, only one of which will be active based on the value of `isGA4DashboardView()`.

For each widget that currently uses `GA4DashboardWidgetSwitcher`:

- Revert the definition passed to `registerWidget()` to directly use the UA version of the widget component instead of using `GA4DashboardWidgetSwitcher`.
- Add an `isActive( select )` callback to the definition that returns the result of `! isGA4DashboardView()`.
- Duplicate the `registerWidget()` call and modify it to make a GA4 version:
  - Append `GA4` to the widget slug.
  - Use the GA4 version of the widget component.
  - Change `analytics` to `analytics-4` in the module list.
  - Invert the returned value of the `isActive()` callback.

Remove `GA4DashboardWidgetSwitcher`.

### Update GA4 widget shared module checks

Within each of the relevant GA4 widgets, update the call to `canViewSharedModule( 'analytics' )` to instead check the `analytics-4` module. These calls can be found in the following files:

- `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/index.js`
- `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js`
- `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/index.js`

### Test Coverage

- Add test coverage for all of the changes apart from the widget definition updates and the shared module checks in the components.

## QA Brief

* Set up Site Kit and Analytics with the `ga4Reporting` feature flag _disabled_.
* Keeping the `ga4Reporting` feature flag _disabled_, test the "Module Sharing Settings" for Analytics within the Dashboard Sharing Settings modal. Verify that the usual Universal Analytics widgets are rendered for both, the logged in admin as well as the view-only user with who the settings have been shared with (via their role).
* With the `ga4Reporting` feature flag _enabled_, ensure the 'Dashboard View' setting toggle is "off" so that Universal Analytics data is still shown on the dashboard. For a new site, this should be the default case anyways. Verify the Universal Analytics widgets are rendered for the admin and view-only user as usual.
* Switch the 'Dashboard View' setting toggle in Analytics settings to "on" to enable GA4 data on the dashboard. Verify the new GA4 widgets are rendered for both, the admin and view-only user.
* Switch off the 'Enable Universal Analytics' setting toggle in Analytics settings. Verify that the new GA4 widgets are still rendered for both, the admin and view-only user.

## Changelog entry

* Fix bug that caused Analytics 4 widgets not to appear in shared dashboard.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – this one is ready to go if you'd like to write the IB for it. I've removed the blocker that was assigned here since it's in QA now anyways.

**Comment by nfmohit** [comment]
> @nfmohit On the latest develop, in my testing, this behaviour happens even when UA **_is_** connected.

Thank you for sharing your findings, @jimmymadon. However, in my tests, it seems widgets do show up when UA is connected. Here is a screencast:

https://user-images.githubusercontent.com/20284937/230685879-f3beb47b-072c-4f83-8266-6d4473d32e34.mp4

<br>
However, I completely agree that it hasn't occurred as a result of #6745. I just discovered this issue while testing #6745.

For now, I have removed  #6687 as a blocker for this issue. However, the dependency can be adjusted after further testing.

Thanks!

CC: @techanvil @aaemnnosttv

**Comment by mohitwp** [comment]
### QA Update ❌ 

@jimmymadon 

- Tested on dev. 
- I've notice below issues in widget when 'ga4Reporting' is enabled and Dashboard view is Ga4 and analytics and search console is in gathering data state.
- **Note** : If site is not in gathering state then widgets are showing correctly for all scenarios mentioned under QAB.


**Issue 1 :**
For Admin 1 All traffic widget showing in gathering state but on view only dashboard and for 2nd logged in admin it is showing in zero data state.

<details>

Admin 1

![image](https://user-images.githubusercontent.com/94359491/232126269-2b047db4-632c-4ac5-a797-d03acb9d23c6.png)

Admin 2:

![image](https://user-images.githubusercontent.com/94359491/232126807-783df905-265d-49e4-a7f4-9c8564faa101.png)

View only dashboard 

![image](https://user-images.githubusercontent.com/94359491/232126937-3c26bb57-61d8-4592-a0c4-6ff061f9ab77.png)

</details>

**Issue 2 :** Top content over the last 28 days widget not loading for 2nd logged in admin and on view only dashboard.
Note : It is happening with search console widgets also, which are in gathering state.

<details>

![image](https://user-images.githubusercontent.com/94359491/232127294-6a154f68-cb96-45dd-aeca-611f187864db.png)

![image](https://user-images.githubusercontent.com/94359491/232127338-c69df18b-92eb-4935-ba79-08156fd94e43.png)

![image](https://user-images.githubusercontent.com/94359491/232127385-34226d23-3408-4327-9739-484dd23c87e8.png)

</details>

**Comment by aaemnnosttv** [comment]
I opened a follow-up PR which should address some of the issues here.

Regarding the gathering state vs zero state for a view-only user, this may be something that we won't be able to have exactly consistent because the gathering state uses data from the property itself which is not available in a shared context.

Top content over the last 28 days is showing for me on both view-only and non-viewonly dashboards in GA4 mode.

**Comment by mohitwp** [comment]
### QA Update ✅ 

@jimmymadon @aaemnnosttv 

- Tested on dev.
- Tested for all cases mentioned under QAB and done some additional testing.
- When analytics is in gathering state then 'Top content over the last 28 days' widget is still not loading for me when I tested it for 2nd logged in admin and on view only dashboard. So, I created a new issue for this https://github.com/google/site-kit-wp/issues/6897 .
- Also, I've notice that Search console DashboardPopularKeywordWidget is not showing on main and entity dashboard when Dashboard view is GA4 for all users. As per @nfmohit this is because of changes introduced in related PR [here](https://github.com/google/site-kit-wp/commit/25acb704b31fcdec48f9055358c5c6482ac04ed6#diff-343a666cea1754ae7bbb52e2595d3631fe02237583ac91ae220c1daaa388f065R62) . So, I created a separate ticket for this also https://github.com/google/site-kit-wp/issues/6896
- Verified Analytics widgets are displaying in view only dashboard and for another logged in admin.
