### ISSUE TITLE
Dashboard View Toggle and UA settings are not being saved

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6828]
## Bug Description

Editing the new Dashboard View toggle and Universal Analytics settings does not work as expected.

## Steps to reproduce

1. With the `ga4Reporting` feature flag enabled, setup Site Kit (after reset) along with Universal Analytics and GA4.
2. Now go to Analytics Settings and toggle the `Dashboard view` setting to UA. Do not change anything else. 
3. Click "Confirm Changes". 
4. The `Dashboard View` toggle remains at GA4 and the UA Property and Profile settings are deleted.
5. Try to edit and re-add the UA Property and Profile settings. However, they will not be saved.

## Screenshots

https://user-images.githubusercontent.com/1721319/230508861-9ef7c8c4-596a-45ce-9a7d-d88f0ba3bdf6.mov

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: main (pre-release 1.98.0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Dashboard View` toggle as well as UA Settings within Analytics Settings should always be saved correctly.

## Implementation Brief

**Before working on this ticket, check #6744 because that ticket may already fix this issue.**

- The UA settings within Analytics settings not being saved correctly will be fixed by #6744, hence I have added that as a dependency for this issue.
- In `assets/js/modules/analytics/datastore/settings.js`:
  - Update the `submitChanges()` function:
    - Locate the `setDashboardView()` dispatch setting the dashboard view to GA4 if the `ga4Reporting` feature flag is enabled and the dashboard view is set to UA.
    - Update the above conditions so that it dispatches `setDashboardView()` only if the `ga4Reporting` feature flag is enabled and UA is not enabled (`! isUAEnabled`).

### Test Coverage

- In `assets/js/modules/analytics/datastore/settings.test.js`:
  - Add test case(s) for `submitChanges()` to reflect the above changes.

## QA Brief

1. With the `ga4Reporting` feature flag enabled, setup Site Kit (after reset) along with Universal Analytics and GA4.
2. Go to Analytics Settings and toggle the `Dashboard view` setting to UA and select a Property. Change nothing else.
3. Click "Confirm Changes". 
4. The Dashboard View should still be GA4 and the Universal Analytics settings (the property connected in step 2) should be saved.
5. Try to edit the "Dashboard View" setting to change it to Universal Analytics and click "Confirm Changes". It should be saved after confirming, even after a page refresh.

## Changelog entry

* Ensure UA settings and Dashboard View toggle settings are saved in Analytics Settings.

**Comment by nfmohit** [comment]
Hi @jimmymadon!
Thank you for the observations here.

I did some investigation and feel that this will be resolved as soon as #6744 is merged.
The problem here is that we introduced this new Enable Universal Analytics toggle as a part of #6738. With that, we also updated the settings validation & storage logic to only save UA entities when this toggle is enabled. Also, this toggle is disabled by default.

Since `SettingsEdit` doesn’t have this toggle yet (as #6744 is not yet merged), the toggle value stays disabled and thus the UA entities are removed as a result under the hood.

As the UA entities are removed, there remains no way to switch between the two dashboard views.

**Comment by nfmohit** [comment]
### Note to AC Reviewer

Since the ACs look well to me and we have a time constraint with GA4 Reporting, I have added an IB to it as well so that it can be moved to EB directly if everything looks good.

**Comment by tofumatt** [comment]
ACs here are correct. 👍🏻 

I think the IB is good too… though when testing the PR for #6744 saving the setting seemed to work for me 🤔 

If it turns out this isn't need it though, just flag it in execution. For now I'll move it to the backlog 👍🏻 

IB ✅

**Comment by eclarke1** [comment]
@eugene-manuilov I saw you assigned this, but an FYI that if #6744 is merged, my understanding from @nfmohit is that this can be closed.

**Comment by eugene-manuilov** [comment]
Ah... okay, i didn't notice it @eclarke1. I'll set it back to EB and add a note regarding that ticket.

**Comment by tofumatt** [comment]
This issue was closed by the PR for #6744 (eg. #6817). so moving this to QA to verify.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- The Dashboard View is still GA4 and the Universal Analytics settings are saved.
- Changed it to Universal Analytics and the settings are saved after confirming, even after a page refresh.

https://user-images.githubusercontent.com/73545194/231441186-747718ab-196d-4a5e-85b4-310369476883.mp4
