### ISSUE TITLE
Update copy of the pop-up screen for disconnecting AdSense in Settings

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#683]
## Feature Description

Update the copy Site Kit displays when the user clicks "Disconnect AdSense from Site Kit" in Settings. 

For reference, a screenshot of the pop-up: 
![tPxHaQiFhnx](https://user-images.githubusercontent.com/6488453/66765277-7ade9c00-eea3-11e9-9824-7e5f1a31bcd6.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The pop-up window should display the following updated copy (in the same format as current pop-up): 

_**Disconnect AdSense?**_
_By disconnecting the %s module from Site Kit, you will no longer have access to:_
_Intelligent, automatic ad placement_
_Revenue from ads placed on your site_
_AdSense insights through Site Kit_ 
_Disconnect    Cancel_

## Implementation Brief

* Inside the `registerModule` call in `assets/js/modules/adsense/index.js`, update the `features` property so that it contains the following items:
  * `Intelligent, automatic ad placement`
  * `Revenue from ads placed on your site`
  * `AdSense insights through Site Kit`

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* Images from the modal may need updating to show the content change.

## QA Brief

* Be on a site with AdSense set up and working in Site Kit
* Navigate to Settings -> AdSense Settings -> Edit :pencil2: 
* Click button to `Disconnect AdSense from Site Kit` :wastebasket: 
* Observe the text on the modal has been updated

## Changelog entry

* Update copy in AdSense disconnect modal.

**Comment by aaemnnosttv** [comment]
@marrrmarrr the disconnect dialog is currently standardized for all modules in that it only lists the items that the AdSense module provides:

![image](https://user-images.githubusercontent.com/1621608/67944465-32361b00-fbe5-11e9-9dd0-5d27d7273adb.png)

Is it possible to rework the AC in a way which fits into this kind of a list or we need to develop a way for modules to have a way to override the output here with a more customized message?

**Comment by marrrmarrr** [comment]
> the disconnect dialog is currently standardized for all modules in that it only lists the items that the AdSense module provides

To make sure I understand completely: when you say "the AdSense module provides" -- the two items in the list come from an external source? 
Or do you mean we can change the content of each item, as long as the list format is preserved? 

If the latter, let's go with:
_"by disconnecting ... you will no longer:_
_- have code on your site to monetize content via AdSense_  
_- have access to AdSense insights through Site Kit"_

**Comment by aaemnnosttv** [comment]
Yes. Most of the content of the dialog there is generic and uses a placeholder for the module name.

https://github.com/google/site-kit-wp/blob/19d0f36d41df843ef835ca306f8ffb9f49f3b810/assets/js/components/settings/settings-module.js#L193

In this case, the list items come from this place in the AdSense module.
https://github.com/google/site-kit-wp/blob/b524540702ed1302c8910b627e27a43128cfd0fd/includes/Modules/AdSense.php#L142-L145

I'm not saying we couldn't make this more flexible or module specific - just wondering if that's the intended outcome here. Do we want to keep things consistent or should we allow for more deviation between modules?

The latter would require more effort, so just providing a bit more context for you to decide.

The easiest change would be to update the list of features that AdSense provides (referenced above), which show when disconnecting the module. Not sure if this change fits into the current limitations though as far as what you're looking to communicate. I think this is the only place those features are displayed, but I don't think we should think of them purely in terms of disconnection messaging either.

**Comment by marrrmarrr** [comment]
It seems that it would be easier here to keep the "you will no longer have access to" phrasing, since that is standard across modules and change the other two strings (`"Monetize your website"` and `"Intelligent, automatic ad placement"`). 

Let's keep "Intelligent, automatic ad placement" and change the other one to "Revenue from ads placed on your site".

**Comment by danielgent** [comment]
This ticket is done, PR is linked https://github.com/google/site-kit-wp/issues/683 , and ready to move to Code Review

**Comment by cole10up** [comment]
### **QA ✅**

Confirmed the copy change:
![image](https://user-images.githubusercontent.com/57115907/126285277-de4fc554-e3f3-4fc9-85c9-a5f08dd92dd4.png)

Confirmed the modal functions properly disconnecting and canceling on multiple browsers and window sizes.
