### ISSUE TITLE
Analytics setup + settings views don't surface GA4 errors

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6831]
## Bug Description

Currently, errors are not properly being surfaced from the GA4 module.

This was initially done intentionally when the GA4 APIs were using the lowest stability (alpha) versions, but has since been updated to use the latest beta versions and stability fallbacks were removed.

## Steps to reproduce

1. With `ga4Reporting` enabled, attempt to create an account using the production service
2. See errors in console, and no indication in the interface

## Screenshots

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/1621608/230628714-9c4fae6e-a73f-456a-9104-f843de8a740a.png">

Related https://github.com/google/site-kit-wp/issues/6728

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All errors from the Analytics 4 module should be surfaced in the setup and settings interfaces, in the same places as the legacy Analytics module
	* One exception is on the settings edit view, where module-specific errors should be co-located with their relevant fields ([example](https://user-images.githubusercontent.com/18395600/228200837-886b515e-2e7f-46e8-8ff4-abfecb54801a.png))

## Implementation Brief

- In `assets/js/modules/analytics/components/common/AccountCreate/index.js` and `assets/js/modules/analytics/components/setup/SetupForm.js`:
  - Duplicate the existing `<StoreErrorNotices />` component but having a `moduleSlug` of `analytics-4` and `storeName` of `MODULES_ANALYTICS_4`.
- In `assets/js/modules/analytics/components/common/EnableUniversalAnalytics.js`:
  - Extend the component to accept a boolean `showErrors` prop, which if true, should render a  `<StoreErrorNotices />` component having a `moduleSlug` of `analytics` and `storeName` of `MODULES_ANALYTICS` before any UA setting fields. This new prop should be `false` by default.
- In `assets/js/modules/analytics/components/settings/SettingsForm.js`:
  - Display the `<StoreErrorNotices />` component only if the `ga4Reporting` feature flag is not enabled.
  - In the rendered `<EnableUniversalAnalytics />` component, pass the new `showErrors` prop with a value of `true`.
- In `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`:
  - Right underneath the `Google Analytics 4` title, place a `<StoreErrorNotices />` component having a `moduleSlug` of `analytics-4` and `storeName` of `MODULES_ANALYTICS_4`.
- In `assets/js/modules/analytics/components/settings/SettingsView.js`:
  - Duplicate the existing `<StoreErrorNotices />` component but having a `moduleSlug` of `analytics-4` and `storeName` of `MODULES_ANALYTICS_4`.

### Test Coverage

- Update VRT references if required.

## QA Brief

- For the purposes of testing this issue we can limit ourselves to verifying the error messages appear in the correct locations, by programmatically triggering errors. This is more practical than a slightly more in-depth approach where we examine the network traffic on a given page and use a tool like the Tweak Chrome extension to intercept `analytics` / `analytics-4` requests and provide error responses, although by all means take this approach instead/as well.
- In order to trigger errors run the following snippets in the JS console:

```js
// These use the `getSettings` argument to associate the error with the `getSettings()` selector. Errors associated with a selector will have the Retry button displayed.
// Dispatch an Analytics error which will show the Retry button:
googlesitekit.data.dispatch( 'modules/analytics' ).receiveError( {
    code: 'some-code',
    message: 'This is a retryable Analytics error.',
    data: {}
}, 'getSettings', [] );

// Dispatch an Analytics 4 error which will show the Retry button:
googlesitekit.data.dispatch( 'modules/analytics-4' ).receiveError( {
    code: 'some-code',
    message: 'This is a retryable Analytics 4 error.',
    data: {}
}, 'getSettings', [] );

// These use the `setSettings` argument to associate the error with the `setSettings()` action. Errors associated with an action will not have the Retry button displayed.
// Dispatch an Analytics error which will not show the Retry button:
googlesitekit.data.dispatch( 'modules/analytics' ).receiveError( {
    code: 'some-code',
    message: 'This is a non-retryable Analytics error.',
    data: {}
}, 'setSettings', [] );

// Dispatch an Analytics 4 error which will not show the Retry button:
googlesitekit.data.dispatch( 'modules/analytics-4' ).receiveError( {
    code: 'some-code',
    message: 'This is a non-retryable Analytics 4 error.',
    data: {}
}, 'setSettings', [] );
```

- The following scenarios should be verified. All of these assume the `ga4Reporting` feature flag is enabled.
- Navigate to the Analytics "Create account" screen (both the Setup and Settings version) and verify the Analytics 4 errors appear at the same point the Analytics errors do, for example:
![image](https://user-images.githubusercontent.com/18395600/234533443-a7628a06-3eba-4fce-9dcc-c9d4317952e3.png)
- Navigate to the Analytics Setup screen and verify the Analytics 4 errors appear at the same point as the Analytics errors:
![image](https://user-images.githubusercontent.com/18395600/234535358-cedb118a-8b00-409f-a841-d45c78adf541.png)
- Navigate to the Analytics Settings view screen and verify the Analytics 4 errors appear at the same point as the Analytics errors:
![image](https://user-images.githubusercontent.com/18395600/234540568-2184a8a3-b9d2-4c97-bd8d-3c9bfb774d36.png)
- Navigate to the Analytics Settings edit screen, this time verifying the Analytics and Analytics 4 errors are co-located with their corresponding settings:
![image](https://user-images.githubusercontent.com/18395600/234541142-4a387487-da0c-4f19-b503-c1cdd8d226ac.png)

## Changelog entry

* Expose errors from GA4 in settings and setup interfaces.

**Comment by techanvil** [comment]
Hey @nfmohit, nice work so far on the IB. There are a couple of aspects that need updating:

- The `StoreErrorNotices` component needs to be conditionally rendered in `EnableUniversalAnalytics`, because this component is rendered in the `SetupFormGA4` component, which in turn is rendered by the Analytics `SetupForm` component, which already has a `StoreErrorNotices` for the `analytics` module, so the error messages would be duplicated in this case.
  - So to be explicit, `StoreErrorNotices` should only be rendered in `EnableUniversalAnalytics` in the case where `EnableUniversalAnalytics` is rendered in the Analytics `SettingsForm` component.
- It doesn't look like the specified changes to `GA4SettingsView`, `UASettingsView` and `SettingsView` are required in order to meet the AC. Note the AC says the errors should be surfaced in the same places as the legacy Analytics module, except for on the settings _edit_ view. As these components are part of the "read" view, the AC can be met by simply adding an `analytics-4` version of `StoreErrorNotices` at the same point as the existing `analytics` one in `SettingsView`.

**Comment by techanvil** [comment]
Hey @nfmohit, nice work so far on the IB. There are a few aspects that need an update or could use a bit of clarification:

- The `StoreErrorNotices` component needs to be conditionally rendered in `EnableUniversalAnalytics`, because this component is rendered in the `SetupFormGA4` component, which in turn is rendered by the Analytics `SetupForm` component, which already has a `StoreErrorNotices` for the `analytics` module, so the error messages would be duplicated in this case.
  - So to be explicit, `StoreErrorNotices` should only be rendered in `EnableUniversalAnalytics` in the case where `EnableUniversalAnalytics` is rendered in the Analytics `SettingsForm` component.
- It doesn't look like the specified changes to `GA4SettingsView`, `UASettingsView` and `SettingsView` are required in order to meet the AC. Note the AC says the errors should be surfaced in the same places as the legacy Analytics module, except for on the settings _edit_ view. As these components are part of the "read" view, the AC can be met by simply adding an `analytics-4` version of `StoreErrorNotices` at the same point as the existing `analytics` one in `SettingsView`.
- I'm a bit unclear about the specified change to `settings.test.js`, as the IB hasn't specced any change to the `submitChanges()` logic, or indeed any logic that modifies any state or function calls etc. Would you mind clarifying why these changes to the test would be needed?

**Comment by nfmohit** [comment]
Thank you @techanvil! I've updated the IB accordingly.

> The `StoreErrorNotices` component needs to be conditionally rendered in `EnableUniversalAnalytics`, because this component is rendered in the `SetupFormGA4` component, which in turn is rendered by the Analytics `SetupForm` component, which already has a `StoreErrorNotices` for the `analytics` module, so the error messages would be duplicated in this case.
> * So to be explicit, `StoreErrorNotices` should only be rendered in `EnableUniversalAnalytics` in the case where `EnableUniversalAnalytics` is rendered in the Analytics `SettingsForm` component.

I have set the `StoreErrorNotices` component for the `analytics` module in the `SetupForm` component to only show up if `ga4Reporting` is not enabled.

> * It doesn't look like the specified changes to `GA4SettingsView`, `UASettingsView` and `SettingsView` are required in order to meet the AC. Note the AC says the errors should be surfaced in the same places as the legacy Analytics module, except for on the settings _edit_ view. As these components are part of the "read" view, the AC can be met by simply adding an `analytics-4` version of `StoreErrorNotices` at the same point as the existing `analytics` one in `SettingsView`.

Updated accordingly.

> * I'm a bit unclear about the specified change to `settings.test.js`, as the IB hasn't specced any change to the `submitChanges()` logic, or indeed any logic that modifies any state or function calls etc (well, barring retrying errors, but that shouldn't affect `submitChanges()` AFAICT). Would you mind clarifying why these changes to the test would be needed?

Removed this change, thanks!

**Comment by techanvil** [comment]
Hi @nfmohit, thanks for the update, however I'm not sure the first of your changes is the right approach:

> I have set the `StoreErrorNotices` component for the `analytics` module in the `SetupForm` component to only show up if `ga4Reporting` is not enabled.

- With regard to `SetupForm`, by making this change you're actually changing the location of the `analytics` error messages in the Setup view, which is not part of the AC.
- As for `AccountCreate`, given that for example the list of `accounts` still comes from `analytics`, it doesn't seem correct to make the `analytics` version of `StoreErrorNotices` conditional here.

**Comment by nfmohit** [comment]
Excellent points, thank you @techanvil. Back to you for another pass.

**Comment by techanvil** [comment]
Thanks @nfmohit, that looks great.

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Ran through the scenarios in the QAB, and made sure that the errors appeared in the correct places based on the code.
  - Navigated to the Analytics "Create account" screen (both the Setup and Settings version) and the Analytics 4 errors appear at the same point the Analytics errors do.
  - Navigated to the Analytics Setup screen and the Analytics 4 errors appear at the same point as the Analytics errors.
- Navigated to the Analytics Settings view screen and the Analytics 4 errors appear at the same point as the Analytics errors.
- Navigated to the Analytics Settings edit screen, this time verifying the Analytics and Analytics 4 errors are co-located with their corresponding settings. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/235447158-6cb13a67-42ad-49b1-a66e-c8f6db684da1.png)
![image](https://user-images.githubusercontent.com/73545194/235447174-97832665-0821-41e1-acaf-98a0d613885e.png)
![image](https://user-images.githubusercontent.com/73545194/235447180-fa344dc9-f61c-4bc7-b643-d25fd89bc320.png)
![image](https://user-images.githubusercontent.com/73545194/235447197-4ccf1e61-9a2b-4be9-93a2-ee176c6bdd74.png)
![image](https://user-images.githubusercontent.com/73545194/235447204-b4dff801-972b-4f83-aa3e-22e2127a2bd8.png)
![image](https://user-images.githubusercontent.com/73545194/235447211-a02393f1-f9ab-4133-9fae-bc5e725306a3.png)
![image](https://user-images.githubusercontent.com/73545194/235447231-8c356b53-cd09-4bc7-857d-c4ffb89ac358.png)
![image](https://user-images.githubusercontent.com/73545194/235447238-9fae189f-a417-422b-8788-8ba702e06bf7.png)
![image](https://user-images.githubusercontent.com/73545194/235447250-a1bfb7bb-76ef-4877-be39-1c747b8a7064.png)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
