### ISSUE TITLE
Update styling of secondary CTAs in notifications

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6833]
## Feature Description

Secondary CTA links in banner notifications currently use a primary green color, but they should be using a different color according to designs. This also avoids using different colors for text links in the same component, as text links in the description use the normal link color.

[See example here](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=221-2414&t=BYBhTp0W4c9TMxaF-4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by sumitshinde-84** [comment]
I would like to work on this issue please assign it to me @aaemnnosttv  sir.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – sounds good, let's make sure that issue addresses all instances not only those in "long CTAs" 👍 

Closing in favor of #6734 !
