### ISSUE TITLE
Remove unused code from Analytics_4 class.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6834]
## Feature Description

In the PR https://github.com/google/site-kit-wp/pull/6790, the `GET:report` handling was extracted from the `Analytics_4` class. However in a subsequent merge, the `validate_shared_report_metrics()` and `validate_shared_report_dimensions()` methods have been restored to the class. These are unused and should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The unused `validate_shared_report_metrics()` and `validate_shared_report_dimensions()` methods should be removed from the `Analytics_4` class.
* It looks like this is all that's needed but the `Analytics_4` class should be reviewed for any other accidental merge results.

## Implementation Brief

* Merge #6864

### Test Coverage

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by eugene-manuilov** [comment]
Looks like those methods have already been deleted in other PRs. There is nothing else to do in this ticket. Moving it to Approval.

**Comment by aaemnnosttv** [comment]
Closing as nothing was needed or done here 👍
