### ISSUE TITLE
Update the GA4 `isZeroReport()` function to handle an empty `totals` object.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6835]
## Feature Description

If a GA4 report has no data for a given date range, the corresponding entry in the aggregate fields `totals`, `minimums` and `maximums` will be an empty object. For example:
```
    "totals": [
        {},
        {
            "dimensionValues": [
                {
                    "value": "RESERVED_TOTAL"
                },
                {
                    "value": "date_range_1"
                }
            ],
            "metricValues": [
                {
                    "value": "1"
                }
            ]
        }
    ],
```

At present the GA4 [`isZeroReport()`](https://github.com/google/site-kit-wp/blob/054ffd4664328ff675e6231bca140bbdfe6e4c90/assets/js/modules/analytics-4/utils/is-zero-report.js#L32) function does not handle this scenario and will throw an error.

The function should be updated to gracefully handle empty objects in `totals`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 `isZeroReport()` function should be updated to handle empty objects in `totals`, where an empty object represents zero data for that particular entry.

## Implementation Brief

- In `assets/js/modules/analytics-4/utils/is-zero-report.js`:
  - Inside the returned `report.totals.some()` function, before running the `totals.metricValues.some()` function, check if `metricValues` exist in the `totals` object, and if not, return `false` early. Example:
    ```js
    // false means there _is_ some report data
    return ! report.totals.some( ( totals ) => {
      if ( ! totals.metricValues ) {
	    return false;
  	  }

	  return totals.metricValues.some( ( { value } ) => value > 0 );
    } );
    ```

### Test Coverage

- In `assets/js/modules/analytics-4/utils/is-zero-report.test.js`:
  - Add test cases for the `totals` array containing empty objects to cover the issue described here.

## QA Brief

* Setup Site Kit with the `ga4Reporting` feature flag enabled and connect an Analytics account to Site Kit has data for the current period (some data in the past 28 days).
* Visit the Site Kit Dashboard.
* Run the following JS code in the console:

```js
const referenceDate = new Date();
referenceDate.setDate(referenceDate.getDate() + 28);
const referenceDateString = [
    referenceDate.getFullYear(),
    `${referenceDate.getMonth() + 1}`.length < 2
      ? `0${referenceDate.getMonth() + 1}`
      : referenceDate.getMonth() + 1,
    referenceDate.getDate().length < 2 ? `0${referenceDate.getDate()}` : referenceDate.getDate(),
  ].join("-");
googlesitekit.data.dispatch( 'core/user' ).setReferenceDate( referenceDateString );
```

* There should be no errors thrown, the charts should load without errors, but they will have zero data.

The code needed to test this is because otherwise the scenario for this bug to appear requires as very specific set of data to recreate, so it's better to use the JS console code.

## Changelog entry

* Improve handling for Google Analytics 4 reports which have no data for one of the requested date ranges.

**Comment by techanvil** [comment]
Hey @tofumatt, the PR here is good, but the QAB as it stands is not quite enough to ensure that the previously failing scenario is fully replicated.

Following the QAB it's likely that the resulting reports will be ones which simply have no data at all. So, for those with multiple date ranges, the `totals` property in the response will look like this:

![image](https://user-images.githubusercontent.com/18395600/231512553-b5a75266-a41b-4720-838f-f1cd92a72138.png)

This case is already handled prior to this PR being merged, by the following condition:

https://github.com/google/site-kit-wp/blob/ce3938d94f4e809d6f81ed6b939112e4a7dbea16/assets/js/modules/analytics-4/utils/is-zero-report.js#L38-L44

In order to property test this fix, we need to replicate the scenario where there is data for one of the date ranges, but not for the other, with the resulting `totals` having a mixture of empty and populated objects. In other words it should look something like this:

![image](https://user-images.githubusercontent.com/18395600/231513194-1eac203f-a1e3-4c23-83d2-83cedf212b56.png)

This response would result in a fatal error prior to this PR being merged.

The easiest way to get a response like this in a predictable manner that I know of, although it's not something that reflects normal usage of the plugin, is to connect a GA4 property which _does_ have data, and then in the JS console, set the current reference date to 1x the current date period in the future. That will ensure the "current" period will be empty, while the "previous" period has data.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt two observations which are probably expected but didn't want to assume. 

1. The Search console data is appear in the chart and isn't zero.  I suspect this is just looking at Analytics. 
2. On the `Top search queries for your site` widget which is based on search console data; pages are appearing but not the top searched. 
3. Should we run this code on the entity and view only dashboard too, to check the same behaviour? 

https://user-images.githubusercontent.com/73545194/231645533-828e4c86-d6b0-4f89-9539-c2347e8536d8.mp4

**Verified:**

When the code is run on a site with data that meets the QAB criteria, there are no errors thrown, and the charts load without errors, but they have zero data.

**Comment by tofumatt** [comment]
> 1. The Search console data is appear in the chart and isn't zero.  I suspect this is just looking at Analytics. 
Correct, I assumed a site with zero data on GA4 would likely be zero data on Search Console, but I probably shouldn't have mentioned it. Zero Analytics data is good 👍🏻 

> 2. On the `Top search queries for your site` widget which is based on search console data; pages are appearing but not the top searched. Is that expected?

Yes, that's Search Console data so it's fine to appear.

> 3. Should we run this code on the entity and view only dashboard too, to check the same behaviour?

Sure thing! The code paths are the same but makes sense to run it there as well.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Ran the code on the main and entity dashboard using the code in the QAB and there are no errors on the front end or in the console, the charts have zero data.  

**Note:** I was unable to test this on view only dashboard as Analytics widgets aren't appearing there but I have made a note to check this when testing all of the dashboard sharing with GA4 dashboard view. 

https://user-images.githubusercontent.com/73545194/231726184-eedaf2ac-e15e-49b3-b84d-5363243bf0f8.mp4
