### ISSUE TITLE
Ensure the GA4 Search Funnel widget can retrieve conversions data on the view-only dashboard.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6836]
## Feature Description

At present the GA4 Search Funnel widget retrieves the current property via GA4 settings in order to pass it to `getConversionEvents()` to retrieve the conversions data.

However, as module settings are not available on the view-only Dashboard, this won't work in this scenario.

Therefore we should update the `GET:conversion-events` endpoint to use the currently set property ID, rather than expecting the property ID to be passed in, thus eliminating the need to look up the module settings in the GA4 Search Funnel widget.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 Search Funnel widget should be able to retrieve and display conversions data on the view-only Dashboard.

## Implementation Brief

**Note, the approach here should be to update the `GET:conversion-events` endpoint so the property ID doesn't need to be passed in, as discussed in the Feature Description.**

In `Analytics_4::create_data_request()`, make the following changes in the `GET:conversion-events` case:
* Remove the condition that checks for missing `propertyID` param from the API request as we no longer require the request param.
* Instead, get the `propertyID` from `Module_With_Settings_Trait::get_settings()->get()` method.

In `assets/js/modules/analytics-4/datastore/conversion-events.js`:
* In the `fetchGetConversionEventsStore`:
  * Remove the `propertyID` param from `controlCallback` and `reducerCallback`.
  * Instead of setting the API response to the named property `state.conversionEvents[ propertyID ]`, just set it to `state.conversionEvents`.
  * Remove `argsToParams`, and `validateParams` as we don't need them.
* In the `*getConversionEvents()` resolver:
  * Remove the `propertyID` param.
  * Remove the condition that checks for `propertyID` is `undefined`.
  * Remove passing `propertyID` to the action and the selector.
* In the `getConversionEvents()` selector:
  * Remove `propertyID` param.
  * Return the `conversionEvents` from the state.
* Set the `conversionEvents` initial state to `undefined` instead of an empty object.

In `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js`:
* Remove the `ga4PropertyID` being passed to `getConversionEvents`, `hasFinishedResolution` and `getErrorForSelector` for `getConversionEvents` as we don't need to pass the property ID anymore.

* Update the stories conversion events mocks in `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.stories.js`.

### Test Coverage

* Update the tests for the `getConversionEvents` selector.

## QA Brief

* Set up a site using GA4 account that has conversions.
* Share dashboard with other users.
* Go to dashboard in the view-only mode and verify that you see conversions information.

Selecting conversion events on the view-only dashboard with the following selector should return a list of events
```js
googlesitekit.data.select('modules/analytics-4').getConversionEvents()
```

## Changelog entry

* Update conversion events to always be requested for the connected GA4 property.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

Currently, we cannot test this because the GA4 dashboard view is not working for view only users, ie. an Editor. 

This should be testable once 6824 is merged.

**Comment by aaemnnosttv** [comment]
## QA ❌ 

After more testing, I realized that the AC are not met here because `GET:conversion-events` has not been made `shareable` which is necessary to be able to request it in a view-only context. https://github.com/google/site-kit-wp/blob/e8c988c71af9d0a2c12f0e4f872b6c37f26236d8/includes/Modules/Analytics_4.php#L265

I'll open a quick follow-up to address this.

**Comment by wpdarren** [comment]
### QA Update: 

**Verified:**

- On the dashboard in the view-only mode I see conversions information. 
- On the view-only dashboard with the selector in the QAB, it returns a list of events.
- Selected different reporting periods, i.e. 7, 14, 28 and 90 days. 

![image](https://user-images.githubusercontent.com/73545194/232056665-f9fdd32b-fe12-4421-affc-aadac5089e02.png)
![image](https://user-images.githubusercontent.com/73545194/232056041-b80b3e5d-4a3a-48dd-99ff-a7b8f155ab87.png)
