### ISSUE TITLE
GA4 dashboard survey invokes duplicate trigger

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6839]
## Bug Description

The `view_ga4_dashboard` trigger added in #6574 is resulting in a duplicate trigger request being made, which (as can be seen in the screencast below) also results in a duplicate survey timeout being sent.

## Steps to reproduce

* Clear timeout for `view_ga4_dashboard` survey if present
* View GA4 dashboard
* See duplicate request made

## Screenshots

https://user-images.githubusercontent.com/1621608/230683485-d0a70868-242d-43d4-9fe2-ece0c942e88f.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When GA4 Reporting is enabled and the Site Kit dashboard is viewed, the survey trigger request for `view_ga4_dashboard` should only be made 1 time, not 2 (or more) times.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by zutigrm** [comment]
@aaemnnosttv This doesn't seem to be an issue, the survey requests that are sent are actually having different data.
* `data: {triggerID: "view_dashboard"}`
* `data: {triggerID: "view_ga4_dashboard"}`

Same goes for the timeout request. So in the curent state there is no duplicate request, **view_ga4_dashboard** survey is actually called only once.

**Comment by tofumatt** [comment]
(See discussion in Slack about this one: https://10up.slack.com/archives/CBKKQEBR9/p1693918024612529?thread_ts=1693907454.790689&cid=CBKKQEBR9)

@aaemnnosttv I think this can be closed as it's fine to have both surveys trigger, given they're for different things, right? It seems we [don't even have a `view_ga4_dashboard` trigger](https://10up.slack.com/archives/CBKKQEBR9/p1693911889129829?thread_ts=1693907454.790689&cid=CBKKQEBR9), but we might want one for the future.

Just confirming with you @aaemnnosttv that it's okay to have both triggers request? If so I think we can close this.

**Comment by aaemnnosttv** [comment]
Sounds good. These are indeed separate and fine to keep. Thanks all!
