### ISSUE TITLE
Clicking on Button 'Use Property name ID' generates error. 

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6843]
## Bug Description
Clicking on Button 'Use Property name ID' generates error.
**Note** : I'm not able to generate this error each time. Out of 10 – 3 times I'm able to generate this error on newly created site having new analytics a/c.

## Steps to reproduce

1. Set up new website when 'ga4reporting' and 'gteSupport' feature flag is enabled.
 2. Follow QAB of https://github.com/google/site-kit-wp/issues/6373.
2. When "Banner notification scenario A"  display.
3. Click on button 'Use property name id'.
4. See error.

```
An error occurred while running 'mapSelect': Cannot assign to read only property '0' of object '[object Array]'
The error may be correlated with this previous error:
TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at xe.getAnalyticsConfigByMeasurementIDs (https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-analytics-4-ff1513ffdff3c6408b45.js:22:33791)
    at t (https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-a53c3f47c347a0bbf1a7.js:7:75315)
    at https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-a53c3f47c347a0bbf1a7.js:7:503255
    at Object.n [as getAnalyticsConfigByMeasurementIDs] (https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-a53c3f47c347a0bbf1a7.js:7:502821)
    at Object.current (https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-main-dashboard-fc854b2188a19e7e3211.js:80:9133)
    at e (https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-a53c3f47c347a0bbf1a7.js:7:415212)
    at https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-a53c3f47c347a0bbf1a7.js:7:415374
    at https://raging-eel-vano.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-a53c3f47c347a0bbf1a7.js:7:507557
    at Array.forEach (<anonymous>)

Original stack trace:

    in GoogleTagIDMismatchNotification
    in BannerNotifications
    in div
    in Header
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root
```

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/230887218-41e4dc2a-206e-4c28-9092-f9b47dd4f8fd.png)

![image](https://user-images.githubusercontent.com/94359491/230887276-d96dfb83-303d-41a4-858d-e2a756cb3a20.png)

https://user-images.githubusercontent.com/94359491/230887385-2d3379b6-ac75-4428-8f07-1385e57b66bc.mp4

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@mohitwp can you confirm this is still an issue?

**Comment by wpdarren** [comment]
@mohitwp, could you please see if this can be recreated? Just wondering, with the GA4 changes, it is still an issue.  Thanks!

**Comment by jimmymadon** [comment]
@mohitwp I've had a look at the code here which has been ported over from Analytics to Analytics-4. Can you please check if this is still reproducible?

**Comment by mohitwp** [comment]
### QA Update ✅ 

I tested multiple times and confirm that I'm not able to reproduce this issue anymore. Thanks !

**Comment by jimmymadon** [comment]
Closing this as not reproducible anymore. Thanks @mohitwp.
