### ISSUE TITLE
Display Entity Ownership Changed Notice for Analytics 4.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6851]
## Feature Description

At present, the `EntityOwnershipChangeNotice` component is only being shown for the `analytics` module. It should also be shown for the `analytics-4` module so the corresponding message is displayed when Analytics 4 owned settings are changed on the Settings page.

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/62cb84e0-2dbf-423b-a982-89743d4154da)

https://github.com/google/site-kit-wp/blob/ce5f364c64efb7499b4f3ced349cc0ef8a795b6f/assets/js/modules/analytics/components/settings/SettingsForm.js#L128-L130

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Entity Ownership Changed Notice should be displayed on the Settings edit page for the Analytics 4 module when owned GA4 settings are changed.

## Implementation Brief

Update the [`EntityOwnershipChangeNotice`](https://github.com/google/site-kit-wp/blob/cac2239c196261c90d2e9d496e4f54cc151e5763/assets/js/components/settings/EntityOwnershipChangeNotice.js) component to support multiple modules at once.
- Add `propTypes` to the `EntityOwnershipChangeNotice` component and define the `slug` prop accept a string or an array of strings and set it to `isRequired`.
- Create a `slugs` const
  - If `slug` is an array, directly pass it over to `slug`
  - If `slug` is a string, pass it as an array to slugs
  - `const slugs = Array.isArray( slug ) ? slug : [ slug ]`
- Change the `storeName` const to `storeNames`.
  - Refactor the `useSelect` so the `storeNames` const is an object with the slugs as the keys and the storeName as a value.
  - Update the `useSelect` function to loop over the slugs and get the `getModuleStoreName` for each slug.
- Refactor the `haveOwnedSettingsChanged` function to an object with the slug names a the keys and the `select( storeName )?.haveSettingsChanged()` as a value.
  - Inside the `useSelect` loop over the slugs using `slugs.reduce()`
  - Only include modules/slugs in the `haveOwnedSettingsChanged` if the current user is the module owner.
    - Therefore get the module owner within the `.reduce()` loop with `const moduleOwnerID = select( storeName )?.getOwnerID();`
- Rename the `module` const to `modules` and refactor to an object with the slug as the key and the module as the value.
- Create a new `haveModulesChanged` const, which is `true` if at least one of the items in the `haveOwnedSettingsChanged` object is `true`.
- Refactor the early return, to return `null` if `isDashboardSharingEnabled` or `haveModulesChanged` is `false`.
- Refactor the current notice to pass in the names of all changes modules
  https://github.com/google/site-kit-wp/blob/cac2239c196261c90d2e9d496e4f54cc151e5763/assets/js/components/settings/EntityOwnershipChangeNotice.js#L71-L77
  - Use [`listFormat`](https://github.com/google/site-kit-wp/blob/cac2239c196261c90d2e9d496e4f54cc151e5763/assets/js/util/i18n.js#L395-L396) to concatenate the module names.
- Remove all unsused code from the component.

- In the `SettingsForm`, change the slug prop of the `EntityOwnershipChangeNotice` to slugs and pass `['analytics', 'analytis-4']` as a value.
  https://github.com/google/site-kit-wp/blob/ce5f364c64efb7499b4f3ced349cc0ef8a795b6f/assets/js/modules/analytics/components/settings/SettingsForm.js#L128-L130

## QA Brief

* Verify that the ga4Reporting feature flag is enabled and the dashboard view is set to GA4.
* Navigate to the Analytics settings edit page.
* Modify the GA4 settings (e.g., property) and confirm that the notice for Analytics 4 appears.
* Enable Universal Analytics, choose a property, and make sure that both Analytics and Analytics 4 notices are visible if both settings have been modified.
* Alter only the UA settings and verify that the notice for Analytics is displayed.

**Both the modules have changed**

<img width="1592" alt="Screenshot 2023-04-17 at 3 16 34 PM" src="https://user-images.githubusercontent.com/24408261/232476894-c558b0ad-ecba-475a-a906-18d53ab727c9.png">

**Only Analytics 4 has changed**

<img width="1592" alt="Screenshot 2023-04-17 at 5 25 26 PM" src="https://user-images.githubusercontent.com/24408261/232477345-c927d397-181d-4032-9f33-353ac2756dc5.png">

**Only Analytics has changed**

<img width="1592" alt="Screenshot 2023-04-17 at 5 25 41 PM" src="https://user-images.githubusercontent.com/24408261/232477366-1b92dd45-ddee-45de-adea-042cf90b7e56.png">

## Changelog entry

* Add entity ownership notice when using GA4.

**Comment by eugene-manuilov** [comment]
> * Duplicate the `EntityOwnershipChangeNotice` and change the `slug` to `analytics-4` so there are 2 separate Notices, one for UA and one for GA4

@derweili I think we should do it this way because it will be bad user experience and kind of confusing to see two similar notifications when both Analytics and Analytics 4 owned settings are changed. Instead of adding an additional notice, I think we should modify the `EntityOwnershipChangeNotice` component itself to be able to accept multiple slugs and display a single message if any of modules have owned settings changed.

**Comment by derweili** [comment]
@eugene-manuilov makes sense. I updated the IB to refactor the `EntityOwnershipChangeNotice` notice to support multiple slugs as an array.

**Comment by eugene-manuilov** [comment]
> I updated the IB to refactor the `EntityOwnershipChangeNotice` notice to support multiple slugs as an array.

Thanks, @derweili. IB is better now. Have one more comment. Maybe let's not rename the `slug` property to `slugs` and just update the propType for it to accept either string or an array of strings? In this case we won't need to change the usage of this component in other modules.

**Comment by derweili** [comment]
@eugene-manuilov updated the IB to not rename the `slug` prop.

**Comment by eugene-manuilov** [comment]
Thanks, @derweili. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Verified for both cases when 'ga4Reporting' feature flag is enabled and when it's disabled.
- Just for more clarity this messages not display to the actual admin. 
- Verified different notices are showing when user tries to modify property of Analytics, Analytics 4 or both UA and GA4.

<details>

Analytics 4

![image](https://user-images.githubusercontent.com/94359491/234604102-8c55392c-7be5-43f1-b747-d6c7248e9504.png)

Only UA 

![image](https://user-images.githubusercontent.com/94359491/234604210-36bc909c-d1ee-4359-a612-5a29ae807367.png)

Both UA and analytics 4

![image](https://user-images.githubusercontent.com/94359491/234604298-e683a96b-f3a7-4b0d-bf66-8bf58dc349eb.png)

</details>

**Comment by bethanylang** [comment]
@techanvil Should this be assigned to the 1.101.0 release? Thanks!

**Comment by techanvil** [comment]
Hey @bethanylang, good catch, this should indeed be in the 1.101.0 release. I've tagged it with said release. Cheers!

**Comment by aaemnnosttv** [comment]
LGTM 👍
