### ISSUE TITLE
Dashboard potentially shows stale data after Analytics account creation

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6852]
## Bug Description

After creating a new GA account, the user will land back on the dashboard, however if data had already been requested and cached before provisioning, it could be that the dashboard shows the old/stale data.

## Steps to reproduce

1. Set up GA and view dashboard once
2. Go to Analytics settings and create a new account
3. Back on the dashboard, see same data as before
	- Changing the date range will trigger fresh requests and show the proper gathering state that would be expected post-account creation

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any cached Site Kit reporting data should be cleared/invalidated after creating an account, similar to how cache is cleared after updating the module settings
* In user-facing terms: after completing the account provisioning process for GA, when returning to the dashboard for the first time, GA widgets should always be in a gathering state

## Implementation Brief

This happens because creating an account does not call `submitChanges` as other setup/settings changes do which calls this internally https://github.com/google/site-kit-wp/blob/9dae54ab7ca20dcdcb36216311d043b4a1ef8163/assets/js/googlesitekit/data/create-settings-store.js#L460

* Update the effect which navigates to the GA TOS URL to invalidate the Analytics cache before navigating
https://github.com/google/site-kit-wp/blob/9dae54ab7ca20dcdcb36216311d043b4a1ef8163/assets/js/modules/analytics/components/common/AccountCreate/index.js#L144-L149
    - The `slug` can be conditional based on `ga4Reporting` if the feature flag is still present, otherwise it should be `analytics-4`

### Test Coverage

* This would be easiest to test with a component test in Jest but there isn't currently a test for `AccountCreate`, and creating this just for this case probably isn't worth it – this would be a nice to have if possible in a reasonable amount of time, otherwise it's easily testable manually

## QA Brief

* Follow the **Steps to reproduce**, but upon returning to the Dashboard, the Analytics widgets should be in the gathering data state.
* This should be the case with/without the `ga4Reporting` feature flag enabled.

## Changelog entry

* Fix bug that caused cached Analytics data not to refresh when a new account is created.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified now after creating new a/c when user redirects to dashboard, then Analytics widgets should be in the gathering data state.


<details>

https://github.com/google/site-kit-wp/assets/94359491/80e066b3-bbeb-4d3e-b9e5-d3e60a366327

</details>
