### ISSUE TITLE
Cannot recover Analytics module when UA is not connected.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6861]
## Bug Description

When Analytics is connected without UA, and then put into a recoverable state, the Module Recovery Alert becomes stuck on the loading state.

## Steps to reproduce

Once #6825 and #6846 are implemented:

1. With the `ga4Reporting` and `dashboardSharing` feature flags enabled, setup Site Kit.
2. Connect Analytics without enabling Universal Analytics.
3. Share the Analytics module via the Dashboard Sharing modal.
4. Login as a second admin and navigate to Analytics settings.
5. Change one of the GA4 settings and save the changes, this will ensure that Analytics is now owned by the second admin.
6. Disconnect the second admin.
7. Login again as the first admin.
8. See the Module Recovery Alert stuck on the loading state.

## Screenshots

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/1499fd66-f1a9-483e-9c64-aa078fa96e3a)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.98.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Analytics is connected without UA, and then put into a recoverable state, the Module Recovery Alert should not become stuck on the loading state, and the Analytics module should be recoverable as usual.
* In this scenario the Analytics module can be listed as "Analytics 4" rather than "Analytics" on the recovery alert.

### Update `getRecoverableModules()` to return `analytics-4` instead of `analytics` when the GA4 Dashboard View is enabled.

Within `assets/js/googlesitekit/modules/datastore/modules.js`, in the `*getRecoverableModules()` resolver:

- Check if the list of modules contains a recoverable `analytics` module.
- If so, yield an await for the Analytics `getSettings()` selector to resolve, in order for the `dashboardView` setting to be immediately available.
- At the point where the module slug is being pushed to `moduleList`:
  - Check if the module slug is `analytics` and if `isGA4DashboardView()` is true.
  - If so, push `analytics-4` instead of `analytics` to `moduleList`.

Within `assets/js/components/notifications/ZeroDataStateNotifications/index.js`:
- Update the check for `analytics` in the list of recoverable modules to instead check for `analytics-4` when `isGA4DashboardView()` is true.
https://github.com/google/site-kit-wp/blob/ce3938d94f4e809d6f81ed6b939112e4a7dbea16/assets/js/components/notifications/ZeroDataStateNotifications/index.js#L78

Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js`:
- Update the check for `analytics` in the list of recoverable modules to instead check for `analytics-4`.
https://github.com/google/site-kit-wp/blob/ce3938d94f4e809d6f81ed6b939112e4a7dbea16/assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js#L122

### Test Coverage

* Extend the `getRecoverableModules()` test coverage to cover this new behaviour.

## QA Brief

- Follow the `Steps to reproduce` mentioned in the issue description.
- Verify that the modules needed to be recovered shows up as expected after the progress bar.
- Verify that the modules can be recovered as expected.
- Verify that there are no relevant console errors or network request failures.
- Verify that there are no errors in the WP `debug.log`.
- Verify this process with multiple recoverable modules.
- Verify this process with both UA and GA4 connected, and also only GA4 (no UA) connected.

## Changelog entry

* Ensure Analytics module can be recovered when only GA4 is connected.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit I have a few observations. 

1. As the second admin user, I went to the Analytics settings and changed the GA4 property and disconnected Page Speed Insights. When I logged in as the first admin user, I saw the notice about Analytics 4 being disconnected but no mention of the second module, PSI that was disconnected. Is that expected?  I did have PSI as a shared module from first admin. 

![image](https://user-images.githubusercontent.com/73545194/232157364-7bda168c-80fd-49c6-bbb5-0e172673733b.png)

You can see that PSI is not activated when I am logging in as the first admin.

![image](https://user-images.githubusercontent.com/73545194/232157443-327e4dc2-3286-4cdb-860a-674823fff907.png)

3. As the second admin user, I went to the settings and console API error appears. Module is not connected. This was without going into any settings, so is just the overview of the settings.  This does not occur for the first admin user.

![image](https://user-images.githubusercontent.com/73545194/232157319-e23ddbe6-9387-4cb6-877a-b36ea4302f2d.png)

Thoughts, should this ticket be sent back to execution?

**Comment by nfmohit** [comment]
> 1. As the second admin user, I went to the Analytics settings and changed the GA4 property and disconnected Page Speed Insights.

Hi @wpdarren. When you say you "disconnected" PSI, may I know how you did it? If the module is entire disconnected from Site Kit, it won't be recoverable anymore and any other admin should be able to set it up from Site Kit again.

In order to test if PSI can be recovered, I think you need to disconnect the admin from Site Kit who set up PSI. That way, it will lose its owner ID and another admin will be able to recover it.

> 3. As the second admin user, I went to the settings and console API error appears. Module is not connected. This was without going into any settings, so is just the overview of the settings.  This does not occur for the first admin user.

I added some context behind this [here](https://github.com/google/site-kit-wp/pull/6847#discussion_r1168306071). I'd recommend adding this to the bug bash board and creating a new issue for it.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

The modules can be recovered as expected.
There are no relevant console errors or network request failures.
There are no errors in the WP debug.log.
This process works with multiple recoverable modules.
This process with both UA and GA4 connected, and also only GA4 (no UA) connected.

![image](https://user-images.githubusercontent.com/73545194/232462375-0440057a-51e9-4128-a8d4-b3ef84a70f5b.png)
![image](https://user-images.githubusercontent.com/73545194/232462419-10973653-68f5-4431-a565-78eb21a4afcb.png)

_Please see [2nd note above](https://github.com/google/site-kit-wp/issues/6861#issuecomment-1509291791) regarding an API error seen in the settings when logged in as the second admin user. I will be creating a ticket for this and adding it to the known issues board._
