### ISSUE TITLE
Both Analytics modules appearing in shared services under view only menu

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6862]
## Bug Description

Google Analytics 4 is appearing in list of modules in Dashboard Sharing view only menu

![image](https://user-images.githubusercontent.com/73545194/231449795-dab9c1ea-f89d-4bb5-a1bb-8ce5312869c5.png)

## Steps to reproduce

1. Set up Site Kit with Google Analytics.
2. Make sure GA4Reporting flag is enabled. 
3. Set your dashboard view to GA4. 
4. Set up Dashboard sharing as Admin
5. Login to the site with a view only role, i.e. Editor
6. Go to the Site Kit dashboard and click on the view only menu in the top right. 
7. See Google Analytics 4 appearing. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- If the `ga4Reporting` feature flag is enabled:
  - The list of shared services in the `ViewOnlyMenu` should only display either `Analytics` or `Analytics 4`.
  - If both Analytics modules are viewable by the view-only user, `Analytics 4` should only be shown if the `analytics` `isGA4DashboardView()` selector returns `true`, otherwise, the `Analytics` module should be shown in the list of shared services in the `ViewOnlyMenu`.

## Implementation Brief

- In `assets/js/googlesitekit/datastore/user/permissions.js`:
  - Update the `getViewableModules` selector to do the following:
    - We want to make a similar change made to the `core/modules` `getShareableModules` selector in #6745.
    - Do not immediately return the result of the `modules` `reduce` function.
    - Check if the resulting array contains both `analytics` and `analytics-4`.
    - If so, check if the `isGA4DashboardView` selector from the `analytics` data store returns `true`.
    - If so, remove `analytics` from the array and return the new array.
    - If not, remove `analytics-4` from the array and return the new array.
- Verify that all parts of Site Kit still function as expected with the change above, as this selector is used by a lot of widget functionalities.

### Test Coverage

- In `assets/js/googlesitekit/datastore/user/permissions.test.js`:
  - Update the test case(s) for `getViewableModules` to reflect the above changes.

## QA Brief

* Follow the steps to reproduce.
* Verify that **Analytics** and **Analytics 4** aren't duplicated based on the dashboard view.

## Changelog entry

* Fix bug that caused Analytics and Analytics 4 to appear in Dashboard Sharing modules when GA4 Reporting is enabled.

**Comment by bethanylang** [comment]
@aaemnnosttv I would consider this a pretty high priority as it will definitely be confusing for users and (hopefully) should be easy to hide. WDYT?

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by nfmohit** [comment]
### Note to IB Reviewer

Set a slightly higher estimate to this one as this approach would need some additional checks to the wider dashboard to make sure everything functions as expected.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified when 'ga4Reporting' feature flag is enabled and dashboard view is 'ga4'.
- Verified when 'ga4Reporting' feature flag is enabled and dashboard view is 'UA'.
- Also, verified when 'ga4Reporting' feature flag is not enabled for regression.


<details>

- Verified when 'ga4Reporting' feature flag is enabled and dashboard view is 'ga4'.

![image](https://github.com/google/site-kit-wp/assets/94359491/be289116-257c-4f81-bf8b-002ae70483df)


- Verified when 'ga4Reporting' feature flag is enabled and dashboard view is 'UA'.
- 
![image](https://github.com/google/site-kit-wp/assets/94359491/90ee107d-eb66-4739-a0c9-33664b9059aa)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
