### ISSUE TITLE
Ad Blocking Recovery

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#6866]
Epic for the engineering of Ad Blocking Recovery.

* [Asana Epic](https://app.asana.com/0/1202340018867629/overview)
* [Design Doc](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit?usp=sharing) 
* [Figma Design](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?node-id=20-3563)

**Comment by yogeshbeniwal** [comment]
@eclarke1 Will it also work with Ad blocking recovery in Ad Manager also, If not pls consider.

**Comment by bethanylang** [comment]
Complete, closing.
