### ISSUE TITLE
GA4 remains disconnected after setting up Analytics - setup loop

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6867]
## Bug Description

If connecting Analytics to a GA property that doesn't have an existing GA4 property some users may encounter a set up loop, where the Analytics status remains as not connected. This I suspect may be hosting related, and requires further testing. 

https://user-images.githubusercontent.com/41326532/231504044-237aafce-e833-4b46-b56d-5970b79832e4.mp4

Note that for those impacted, Site Kit will place the UA snippet despite the loop, and the dashboard will populate with UA traffic. 

## Workaround

A workaround may be to create a GA4 property from analytics.google.com, before then selecting that property within the Site Kit settings. 

## Steps to reproduce

1. Set up Site Kit (without Analytics) on a Taste WP site - [shortcut](https://tastewp.org/plugins/google-site-kit/)
2. Connect the Analytics module. Use an Analytics account that doesn't have an existing GA4 property
3. Select the option for SK to create a new GA4 property
4. After setup completes, the status for Google Analytics will remain as "Not connected", with the GA4 property appearing blank when editing the setting. Attempting to setup once more and the same issue remains

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/231503706-d4a3ef8f-5bbd-46bf-a466-2b6518bc4990.png)

![image](https://user-images.githubusercontent.com/41326532/231503908-5d4f6773-0879-475b-82a9-cdd438b75f6a.png)

## Additional Context

 - SK version 1.98.0
 - [Another user](https://wordpress.org/support/topic/i-cant-save-my-google-analytics-4-setup/#post-16644326) reported this earlier this week. In this case I wasn't able to recreate the same based on the users environment (a multi site setup - [internal testing](https://app.asana.com/0/1185360131189553/1204371434826549/f))
 - 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This should be fixed as of #6831 and #7168 👍
