### ISSUE TITLE
Create GA4 `WPDashboardPopularPages`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6868]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `WPDashboardPopularPagesGA4` should be created based on the existing `WPDashboardPopularPages`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* The component should be rendered on the WP dashboard based on the result of `isGA4DashboardView`
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief

- Create `assets/js/components/wp-dashboard/WPDashboardPopularPagesGA4.js` which exports the `WPDashboardPopularPagesGA4` functional component.
  - The component should be similar to the one in `assets/js/components/wp-dashboard/WPDashboardPopularPages.js` with the following updates:
    - Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`).
    - Replace the metrics and dimensions by their GA4 counterparts as per this doc [here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6), including the metric names.
- Stories should be within `assets/js/components/wp-dashboard/WPDashboardPopularPagesGA4.stories.js` and make use of the Analytics 4 response mock data added from #6174, similar to other `WPDashboard*GA4.stories.js` files.
  - Refer to the AC for the different stories to be added.
- In `assets/js/components/wp-dashboard/WPDashboardWidgets.js`:
  - Check the `isGA4DashboardView()` selector from the `modules/analytics` store.
  - If the above returns `true`, render:
      - `WPDashboardPopularPagesGA4` instead of `WPDashboardPopularPages`.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Enable `ga4Reporting`
* Set up SK with GA using only GA4 (more obvious to see the problem before on develop)
* View WP dashboard
* See `WPDashboardPopularPagesGA4` component in Site Kit summary widget
* See only report requests for `analytics-4` being made 

## Changelog entry

* Add the Analytics 4 version of the Popular Pages widget on the WordPress dashboard.

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit – IB LGTM. Would you please add an estimate?

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Verify on WP dashboard using react tool.
- WPDashboardPopularPagesGA4 widget is showing on WP dashboard.
- Also verified added stories - https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardpopularpagesga4--ready

<details>

![image](https://user-images.githubusercontent.com/94359491/232130341-120abe6a-f770-4961-ad22-a27aa6c3ff24.png)


![image](https://user-images.githubusercontent.com/94359491/232130018-ab4205c7-277e-445b-a3cb-a72312017751.png)

![image](https://user-images.githubusercontent.com/94359491/232130082-4f49fecd-03cb-4cfb-af1c-621c69648f0f.png)

![image](https://user-images.githubusercontent.com/94359491/232130135-ff98beb9-3f00-4450-b3e3-18257b88ea85.png)

![image](https://user-images.githubusercontent.com/94359491/232130202-6aafedb5-6ec1-49b7-9ebb-3a82806e3c31.png)

</details>
