### ISSUE TITLE
Update source links in GA4 Popular Pages widget

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6871]
## Feature Description

The GA4 variant of the popular pages widget on the dashboard still uses a UA service URL for its source links:

https://github.com/google/site-kit-wp/blob/cac2239c196261c90d2e9d496e4f54cc151e5763/assets/js/modules/analytics/components/module/ModulePopularPagesWidgetGA4.js#L163-L170

This needs to be updated to use the proper equivalent for GA4. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ModulePopularPagesWidgetGA4` component should link its external `serviceURL` deep link to the following screen:
* Lifecycle > Engagement > Pages and screens
	* Page path and screen class
	* Filtering the page path by the page path from the Analytics report data

## Implementation Brief

* Update [`getServiceReportURL`](https://github.com/google/site-kit-wp/blob/6217eab78e16832f2c742e8a031a27d045825e9b/assets/js/modules/analytics/components/module/ModulePopularPagesWidgetGA4.js#L163) in `ModulePopularPagesWidgetGA4` to select from the `analytics-4` store
	* `type`: `all-pages-and-screens`
	* `filters`: `{ unifiedPagePathScreen: PATH_FROM_GA }`
	* `dates`: use `generateDateRangeArgs` using the current date range dates as today

### Test Coverage

* No changes necessary

## QA Brief

* Enable the `GA4Reporting` feature flag and set up Site Kit with a property that has Analytics data.
* Load the main dashboard and scroll down to the "Top content over the last 28 days" section
* The link to the Analytics property (pictured below) should take you to a GA4 page for that page in that row and use the active date range selected in the dashboard (so try this with "Last 28 days", "Last 7 days", etc.)

![CleanShot 2023-04-17 at 21 10 52](https://user-images.githubusercontent.com/90871/232599296-c31a3dfe-90da-4784-8f3d-0464b0db0e17.png)

## Changelog entry

* Update source links in the Popular Pages widget for the Analytics 4 version.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 


@tofumatt 

- Tested on main branch.
- **Issue :** The link is not navigating as per selected date range. For all date range we select on dashboardlicking on navigated link showing result for only last 28 days. 

<details>


https://user-images.githubusercontent.com/94359491/233007837-9f7a80af-bd60-4096-9ce5-f30d5976749d.mp4

</details>

**Comment by aaemnnosttv** [comment]
Back to you for another pass @mohitwp 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main.
- Issue reported [above](https://github.com/google/site-kit-wp/issues/6871#issuecomment-1514299409) is now resolved.
- The link navigating as per AC. 
- The link destination shows data as per selected date range.

<details>

28 days

![image](https://user-images.githubusercontent.com/94359491/233293608-1a9a54cc-8b23-476b-90a5-ea80110092fe.png)

90 days

![image](https://user-images.githubusercontent.com/94359491/233293754-6be27511-afea-4307-bab5-686f19885393.png)

14 days

![image](https://user-images.githubusercontent.com/94359491/233293836-61ea71a4-b8f6-4e74-924d-66db2fb51f00.png)

7 days

![image](https://user-images.githubusercontent.com/94359491/233293949-f0415b7b-5741-4dd1-b785-9284a9185268.png)

</details>
