### ISSUE TITLE
Surveys raise console error on view only dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6874]
## Bug Description

With the recent changes to survey infrastructure in #6306, a minor flaw was missed which results in survey timeouts attempting to be fetched (and failing) on the view only dashboard.

The good part is that because the request fails, no survey will ever be shown so this is harmless but shouldn't happen in the first place.

## Steps to reproduce

* View shared dashboard
* See error in console from `survey-timeouts` request

## Screenshots

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/1621608/231641393-9e7308f5-1d8e-465a-a161-d0ad52ee3b99.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User surveys and their supporting requests should not be invoked on the view only dashboard

## Implementation Brief

* In the [`DashboardMainApp.js`](https://github.com/google/site-kit-wp/blob/ce3938d94f4e809d6f81ed6b939112e4a7dbea16/assets/js/components/DashboardMainApp.js)
  * Update the existing conditional rendering for the `CurrentSurveyPortal` to only render the `CurrentSurveyPortal` if `viewOnlyDashboard` is false.

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
IB ✅

**Comment by zutigrm** [comment]
@aaemnnosttv This seems to be resolved by you 4months ago https://github.com/google/site-kit-wp/blob/d051e2e241bba7ba77e1ec1f536bfe0b380a7b86/assets/js/components/DashboardMainApp.js#L76

This is seems to be a duplicate issue?

**Comment by tofumatt** [comment]
Indeed, this was fixed in #6895 so can be closed as a duplicate.
