### ISSUE TITLE
Update Analytics gathering state time under Analytics gathering state banner text when dashboard view set to GA4.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6877]
## Bug Description

As we updated, time for GA4 analytics gathering state to 3 days. It requires updating time mentioned under Analytics gathering state banner from 48 to 72 hours for GA4.

## Steps to reproduce

1. Set up site kit with analytics with 'ga4Reporting' feature flag enabled.
2. Create new analytics account.
3. Check site kit main dashboard (Dashboard view should be GA4)
4. See Analytics 4 gathering state banner on main dashboard.
5. Check text on banner - 'It can take up to 48 hours.......... ".

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/231753554-91742fd7-467b-4b29-8bc6-87291499b811.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the current dashboard view is set to GA4, the time within the Gathering Data notice should be updated to 72 hours.
* If the dashboard view is set to UA (with or without the GA4 reporting feature flag enabled), the time on the notice should still be 48 hours as before.

## Implementation Brief

* Within `GatheringDataNotification`, use the `isGA4DashboardView` selector and update the time to 72 hours if the dashboard view is set to GA4. 

(Have already created and attached a PR #7010 to this issue since this change is very minor.)

### Test Coverage

* Fix any failing tests / stories or snapshots.

## QA Brief

* Verify the banner is updated to mention 72 hours when following the steps to reproduce. 
* Verify the banner still mentions 48 hours when the GA4 reporting feature flag is disabled or the dashboard view is set to UA with the feature flag enabled.

## Changelog entry

* Update the "gathering data" time for GA4 properties.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Verified banner when ga4 reporting feature flag is enabled. Banner showing 72 hours.
- Verified banner when ga4 reporting feature flag is disabled. Banner showing 48 hours.
- Also, verified when ga4 reporting feature flag is enabled, but dashboard view is set to 'ga4'. In this case, banner is showing 72 hours.
- When ga4 reporting feature flag is enabled, but dashboard view set to 'UA'. In this case banner is showing 48 hours.


@jimmymadon 

**Question** - If analytics is not set up then for search console we are showing 48 hours. Is it correct and time to show stats for search console is still 48 hours ?

![image](https://github.com/google/site-kit-wp/assets/94359491/37b635a4-3032-49d5-90fc-133f0e85cf99)





<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/97af1279-55cf-4358-be55-3eb35982f40a)

![image](https://github.com/google/site-kit-wp/assets/94359491/a975d70f-9862-4c3e-9bcb-60410fcc10d3)


When 'ga4 reporting' feature flag is enabled, but dashboard view is not set to 'ga4'.

![image](https://github.com/google/site-kit-wp/assets/94359491/56cc6687-1dc5-4016-97c9-377e4ce1d4a8)

When 'ga4 reporting' feature flag is enabled, and dashboard view is set to 'ga4'.

![image](https://github.com/google/site-kit-wp/assets/94359491/5da23a63-0e76-43c2-910a-3e76bcf1590c)

Only analytics is in gathering state.

![image](https://github.com/google/site-kit-wp/assets/94359491/cd5a154b-1344-411c-8e28-6a0791a04319)

![image](https://github.com/google/site-kit-wp/assets/94359491/a923fd1b-b29e-44c9-a1b9-1688d9801121)

</details>

**Comment by mohitwp** [comment]
Thanks @jimmymadon 

### QA Update ✅ 

- Tested on dev environment.
- Verified banner when ga4 reporting feature flag is enabled. Banner showing 72 hours.
- Verified banner when ga4 reporting feature flag is disabled. Banner showing 48 hours.
- Also, verified when ga4 reporting feature flag is enabled, but dashboard view is set to 'ga4'. In this case, banner is showing 72 hours.
- When ga4 reporting feature flag is enabled, but dashboard view set to 'UA'. In this case banner is showing 48 hours.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/97af1279-55cf-4358-be55-3eb35982f40a)

![image](https://github.com/google/site-kit-wp/assets/94359491/a975d70f-9862-4c3e-9bcb-60410fcc10d3)


When 'ga4 reporting' feature flag is enabled, but dashboard view is not set to 'ga4'.

![image](https://github.com/google/site-kit-wp/assets/94359491/56cc6687-1dc5-4016-97c9-377e4ce1d4a8)

When 'ga4 reporting' feature flag is enabled, and dashboard view is set to 'ga4'.

![image](https://github.com/google/site-kit-wp/assets/94359491/5da23a63-0e76-43c2-910a-3e76bcf1590c)

Only analytics is in gathering state.

![image](https://github.com/google/site-kit-wp/assets/94359491/cd5a154b-1344-411c-8e28-6a0791a04319)

![image](https://github.com/google/site-kit-wp/assets/94359491/a923fd1b-b29e-44c9-a1b9-1688d9801121)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
