### ISSUE TITLE
Remove `dashboardSharing` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6884]
## Feature Description

Now that Dashboard Sharing has been made available to all sites, the feature flag can be removed, along with related code paths that are no longer reachable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `dashboardSharing` feature flag should be removed such that conditions that use it should keep the code path where the flag is `true`
* Any other references to the flag should be removed, except the changelog

## Implementation Brief

* Remove `dashboardSharing` from [`feature-flags.json`](https://github.com/google/site-kit-wp/blob/fa1d07f81ec790176f84fba3e88275f73a1e64b7/feature-flags.json)
* Remove all ocurrences of `useFeature( 'dashboardSharing' );`. Remove the feature flag from all corresponding conditions.
* Search for all `features: [ 'dashboardSharing' ],` occurences in storybook stories and remove them.
* Search for all `*.test.js` that enable the `dashboardSharing` feature flag using `features: [ 'dashboardSharing' ],`
* Search `.php` files for `Feature_Flags::enabled( 'dashboardSharing' )` and remove it for corresponding conditions.
* Search all `*Test.php` test files for `$this->enable_feature( 'dashboardSharing' );` and it.

### Test Coverage

* Verify all unit tests, VRT tests and php tests run as expected.

## QA Brief

* Verify that there's no `dashboardSharing` feature flag in the Tester plugin.
* Run a general smoke test of the plugin, focusing on Dashboard Sharing related features, including module sharing, module recovery and view only dashboard. Ensure everything is working correctly and there's no regression. 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
Removing a feature flag can often raise new failures in tests (particularly E2E but others too). While the changes themselves to remove the flag are often very simple, it can often take much more time than expected for this reason. I'm going to bump the estimate to add some additional time to account for this.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified `dashboardSharing ` feature flag is removed successfully from tester plugin.
- Verified `dashboardSharing ` functionality working as expected.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/2a054909-cd00-484e-bd66-8b0f29ee2455)

</details>
