### ISSUE TITLE
Google Site Kit API Error on GA4 Dashboard view when in zero data state

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6886]
## Bug Description

While testing #6838 I noticed an error message on the GA4 dashboard view.  This is for a site, where I have set up a GA4 but no UA property. The GA4 property is on zero data state.  The error message that appears in the console is: 
`Googlesitekit-api-a605e8ce718042ee5433.js:1 Google Site Kit API Error method:GET datapoint:report type:modules identifier:analytics error:"Parameter viewId must be set."`

After a conversation with Jimmy, he recommended that I created a ticket because it's difficult to know which ticket is causing this error.  

**Update:**  the same error appears when you have a site with data. 

https://user-images.githubusercontent.com/73545194/232044121-4f1a2b20-7ff0-42e5-a8d9-d97f96049239.mp4

## Steps to reproduce

1. Make sure GA4Reporting flag enabled. 
2. Setup Site Kit with Analytics 
3. Select a GA4 property but do not select the toggle to set up UA. 
4. You will get the success notification banner.
5. Look at the console for the error reported above. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren is this still reproducible? I believe this issue has been fixed elsewhere but please let me know if not.
