### ISSUE TITLE
Potential fatal error when autoloading non-existent Composer class

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6887]
## Bug Description

There have been a few reports of fatal errors since the last release 1.98.0

```
PHP Warning:  require_once(/var/www/html/web/wp-content/plugins/google-site-kit/third-party/vendor/composer/InstalledVersions.php): Failed to open stream: No such file or directory in /var/www/html/web/wp-content/plugins/google-site-kit/includes/loader.php on line 34
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/web/wp-content/plugins/google-site-kit/third-party/vendor/composer/InstalledVersions.php' (include_path='.:/usr/share/php') in /var/www/html/web/wp-content/plugins/google-site-kit/includes/loader.php:34
```

- https://wordpress.org/support/topic/version-4-4-3-causes-fatal-error-with-google-site-kit-1-98-0/

This dates back to [a change made in #3830](https://github.com/google/site-kit-wp/issues/3830#issuecomment-897028747) which was later undone in #1146.

The initial guard which prevented this from happening used the required class name to only load Site Kit classes by checking the full class name. This had to be removed in #1146 when certain vendor-provided polyfill classes also needed to be autoloaded. Ultimately, the problem is that a non-existent class is attempted to be required.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit autoloader should not throw any errors due to non-existent files or classes

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/6888

### Test Coverage

* No changes

## QA Brief

* Add the following snippet to a plugin or theme to reproduce the error on 1.98.0

```php
add_action( 'plugins_loaded', array( '\Composer\InstalledVersions', 'getInstalledPackages' ) );
```

* Once merged, the error should no longer happen on `develop`

## Changelog entry

* Fix a potential error when attempting to autoload a class from a non-existent file.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified**

On 1.98.0 the PHP error message appeared in my logs.

![image](https://user-images.githubusercontent.com/73545194/233063769-d0a53543-07ef-458f-806d-2477f5e24596.png)

I switched to the main branch and navigated around Site Kit and left it for 10 minutes and no further errors appeared.
