### ISSUE TITLE
'Target not mounted' warnings in console on a site setting up Site Kit for the first time

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6892]
## Bug Description

While testing earlier I saw warnings in the console.  `Target not mounted` when visiting the dashboard. 

This was with a new site and new Analytics account / GA4 Property.  

Everything looks to be set up as expected but thought I would log these as an issue to investigate.

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/5bb00ca0-7fc6-4831-9b5b-7225784d8906)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This was happening before when the dashboard was showing the CTA for conversions (rather than the metric), but this has been fixed so that it works in either case.
