### ISSUE TITLE
Top content over the last 28 days widget not loading for 2nd logged in admin and on view only dashboard.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6897]
## Bug Description

When analytics is in gathering state and Dashboard view is GA4 then 'Top content over the last 28 days' widget not loading for 2nd logged in admin and on view only dashboard.

## Steps to reproduce

1. Enable 'ga4Reporting' feature flag.
2. Set up new site kit with analytics. Analytics should be in gathering mode.
3. Shared analytics with other users.
4. Sign in Site kit with 2nd admin.
5. Notice on dashboard "Top content over the last 28 days' widget is showing continuously in loading state.
6. Now, sign in with another user who have view only access.
7. Go to 'view only shared dashboard;.
8. Notice "Top content over the last 28 days' widget is showing continuously in loading state.

## Screenshots

<details>

![image](https://user-images.githubusercontent.com/94359491/232127294-6a154f68-cb96-45dd-aeca-611f187864db.png)

![image](https://user-images.githubusercontent.com/94359491/232127338-c69df18b-92eb-4935-ba79-08156fd94e43.png)

![image](https://user-images.githubusercontent.com/94359491/232127385-34226d23-3408-4327-9739-484dd23c87e8.png)

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For unauthenticated user, if data-availability of `analytics-4` module is not available on page load and the module has zero data, assume that the site is still in gathering data state.

## Implementation Brief

* In `assets/js/modules/analytics-4/datastore/report.js`:
    * In the `selectDataAvailability` selector passed to the `createGatheringDataStore` function:
        * Before  trying to get the `propertyID` with `getPropertyID` selector, check whether the current user is authenticated with the `isAuthenticated` selector of `CORE_USER` store.
        * If user is NOT authenticated, return early with the value `false` to indicate that data is not available. 

### Test Coverage

* Add test coverage for the new scenario in tests for `isGatheringData` selector of `analytics-4` module. 

## QA Brief

* Verify that all Analytics widgets with the GA4 dashboard switched on show the "gathering data" state correctly on a site in gathering data state - with authenticated users as well as non-authenticated admins/users. (view-only dashboard).
* Also verify the GA4 widgets work correctly when the site is not in Gathering data state.

## Changelog entry

* Ensure that GA4 widgets correctly display the gathering data state on the view-only dashboard.

**Comment by mohitwp** [comment]
@wpdarren Let me know if you are also getting this issue when site is in gathering state. For @aaemnnosttv  this widget is showing.

**Comment by bethanylang** [comment]
@mohitwp I was able to replicate this on my test site, as well.

**Comment by wpdarren** [comment]
Good spot @mohitwp yes, I was able to recreate this too.

**Comment by kuasha420** [comment]
@aaemnnosttv I've added AC and IB for this one based on our discussion yesterday. Please have a look.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@jimmymadon  the Dashboard does not load when I view the dashboard as a second admin user.   I connected Site Kit for a new site, with the first admin user, everything looks fine on the main and entity dashboard.  When I login as a view only user, all good, the dashboard loads as expected.  When I login as a second admin user, and connect using my Google account, all is fine until I am redirected back to the dashboard.  An error message appears `Google Site Kit API Error method:GET datapoint:property type:modules identifier:analytics-4 error:"The caller does not have permission"` This message has appeared before but I thought it was fixed. 

As the first admin, I have permission to all modules.  This is for a site that only has a GA4 property. 

I left the dashboard for a little while and nothing loads.   See screen cast below. 

https://user-images.githubusercontent.com/73545194/235662549-bd4f60ca-f38b-4d01-b4a9-5c0b38f23b78.mp4

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- All Analytics widgets with the GA4 dashboard feature flag enabled for a site in "gathering data" state correctly  - with authenticated users as well as non-authenticated admins/users. (view-only dashboard). 
- The GA4 widgets work correctly when the site is not in Gathering data state.

We currently have an issue with a second admin user and dashboard sharing.  See my [comment above](https://github.com/google/site-kit-wp/issues/6897#issuecomment-1531363307) about this. Jimmy has created #7006 to fix the issue

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/236202693-53209fd5-1004-4757-a4fd-5a5e5fd70975.png)
![image](https://user-images.githubusercontent.com/73545194/235663724-8c91ed7e-3098-4741-b583-0a7226584977.png)
![image](https://user-images.githubusercontent.com/73545194/235663768-dbad9ced-a3a8-4df7-9920-84fca8d51031.png)
![image](https://user-images.githubusercontent.com/73545194/235663818-bd8bb43d-6546-4dde-bc43-cccbb47ed3f2.png)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
