### ISSUE TITLE
Introduce `adBlockerDetection` feature flag

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6900]
## Feature Description

Development of Site Kit's integration with the Ad Blocking Recovery tag, available in the Privacy and messaging section of AdSense is referred as Ad Blocker Detection in Site Kit engineering. This feature must be developed behind the `adBlockerDetection` feature flag.

This issue is about introducing the feature flag. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `adBlockerDetection` feature flag should be added to the list of available features

## Implementation Brief

* Add the feature flag to `feature-flags.json`

### Test Coverage

* Not needed.

## QA Brief

* Make sure the feature flag is available in the Site Kit tester plugin. 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by bethanylang** [comment]
@kuasha420 Assigning to you and moving to Execution!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Made sure the `adBlockerDetection`  feature flag is available in the Site Kit tester plugin.
  - Checked that the selection of the feature flag saved successfully. 
  - Refreshed the screen and made sure it was still enabled. 
  - When enabling the `adBlockerDetection` I don't see any errors or warnings in the console. 

Tested this on 1.92/0 and 1.93.0-dev version of the tester plugin.

**Comment by aaemnnosttv** [comment]
LGTM 👍
