### ISSUE TITLE
Introduce infrastructure for obtaining Ad blocking recovery tags from the AdSense API and storing them in the database

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6902]
## Feature Description

Historically, Site Kit has always constructed various tags (ie. AdSense and Analytics tags) by interpolating various account and property related information on the hard coded tags available in the source code of the plugin. Due to the undocumented and unpredictable nature nature of the Ad blocking recovery and error protection tag, it has been decided to use the AdSense API to get the tags. See the [relevant](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#heading=h.gr1wo64k81zt) [sections](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#bookmark=id.5one7r51hhz2) in the design doc. 

This issue is about obtaining the tags from the [AdSense API](https://developers.google.com/adsense/management/reference/rest/v2/accounts/getAdBlockingRecoveryTag) and storing them securely in the websites database. 

The API was added to the `google/apiclient-services` in the [v0.263.0](https://github.com/googleapis/google-api-php-client-services/compare/v0.262.0...v0.263.0) release back in August. We are currently using `v0.277.*` so no library update is needed here as well. :tada: 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense Recovery and AdSense Error protection tags should be fetched via the [AdSense API](https://developers.google.com/adsense/management/reference/rest/v2/accounts/getAdBlockingRecoveryTag) and stored in the AdSense settings using distinct `option_name` values: `'googlesitekit_adsense_recovery-tag-HTML'` and `'googlesitekit_adsense_error-protection-HTML'` respectively—these values can be unset by default.
  * After they're fetched, the tags should immediately be saved in the AdSense module settings.
  * These tags should be saved base64-encoded so their contents as HTML are not immediately apparent and cannot be changed by another, poorly-coded plugin that modifies HTML data in the database. The values should be returned decoded.
  * Two new methods should be added to the AdSense module: `getRecoveryTagHTML` and `getErrorProtectionHTML` that return the decoded contents of these tags, if available. An empty string or `null` can be returned if not found.
* An action in the datastore of AdSense module should be added to fetch the tags. 
    *  This action will be used to fetch the tags in the Ad Blocking Recovery screen in #6966.

## Implementation Brief

* In `Google\Site_Kit\Modules\AdSense` class:
    * Add `GET:ad-blocking-recovery-tag` route to `get_datapoint_definitions` method.
    * In `create_data_request` method, add a case for the aforementioned route.
        * Make sure that the `accountID` is provided.
        * Return `$service->accounts->getAdBlockingRecoveryTag( self::normalize_account_id( $data['accountID'] ) );`
    * In `parse_data_response` method, add a case for the aforementioned route.
        * Get the `adBlockingRecoveryTag` and `errorProtectionTag` from the response using `getTag` and `getErrorProtectionCode` methods respectively. 
        * Base64 encode both of them and store them in separate options defined in the AC.
        * Return with a simple `{ success: true }` to indicate success as we do not need the tags in the Admin panel. 
    * Create two public methods `getAdBlockingRecoveryTag` and `getErrorProtectionTag`:
        * Get the appropriate tag from the DB using the options defined in the AC.
        * If they exist/are not empty, base64 decode them. 
        * If decoded successfully, return the decoded string. 
        * Return null in all other case. 
* In `modules/adsense` datastore:
    * Create an action `fetchAdBlockingRecoveryTags` using the previously created API and `createFetchStore`.
    * This action will be used to fetch Ad Blocking Recovery Tags in the first step of `ad-blocking-recovery` screen in #6966. 

### Test Coverage

* Add test coverage for the above changes and additions. 

## QA Brief

* Complete AdSense setup.
* Sync the ABD tags on the server using the following console command, 
    * `await googlesitekit.data.dispatch('modules/adsense').syncAdBlockingRecoveryTags()`
* Ensure the response is `{ "success": true }`.
* Check the `googlesitekit_adsense_recovery-tag` and `googlesitekit_adsense_error-protection-tag` options from the DATABASE. They should be populated with long base64 string. 

## Changelog entry

* Add infrastructure for fetching and storing the Ad Blocking Recovery tag.

**Comment by tofumatt** [comment]
It should be noted that we discussed originally (and outlined in the design doc) that the HTML content would be hashed and the output compared before rendering to ensure it hadn't been modified.

This was largely to prevent accidental modification of the script tag, because any bad actor with database access could change both the source HTML and the hash in order to "trick" Site Kit into outputting arbitrary HTML. But it occurs to me that any change in the length of the string without altering the PHP curried string lengths would also break things.

So I think the hash solution winds up being over-engineered for an unlikely issue that would possibly break before the hash check anyway.

In this case I've omitted it from the ACs. We could always add it later before the feature sees real-world use, but I think it's actually entirely unneeded.

**Comment by kuasha420** [comment]
@tofumatt After some discussion with Evan on this, we'd like to avoid storing the tags in the module settings if possible. Since the tags will only be placed in the front end, we can stop bloating the API responses for AdSense settings with this data. 

Also as @aaemnnosttv pointed out, we still want the tags to be encoded, so maybe it should be mentioned in the ACs. 

Thank you!

**Comment by tofumatt** [comment]
Hmmm, fair enough. If we aren't hashing the values, then we can't actually detect that anything is broken, and it does complicate the code paths for a yet-to-be-encountered, edge case caused by a poorly-coded third-party 😆  But fair enough, we can encode them.

Storing them outside serialised settings actually makes sense though, especially as they'll be used a lot on the frontend. I guess we'll want new option values for that 👍🏻

**Comment by kuasha420** [comment]
@tofumatt Thanks for updating the AC's accordingly. I made a slight tweak to one point to replace encryption with base64-encoding since that's what we agreed on in the call. Everything else LGTM. :+1:

**Comment by kuasha420** [comment]
@tofumatt Hi, I have made a slight change in the AC to not mention the (not yet available) ad blocking recovery onboarding screen. Instead, I added a point about adding an action in the datastore that we can use to fetch the tags. That way, we can start on this, and use the action in the future to actually fetch the tags in the appropriate issue when the on boarding screen will be finalized (#6966). Since you've initially worked on the AC, I'm assigning this to you for a lookover on the AC and IB review at once!  

Cheers!

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Noting here that there are some elements of the definition that should have been modified before moving forward that will result in some extra time (and potentially a follow-up issue) to address. See https://github.com/google/site-kit-wp/pull/7134#pullrequestreview-1468200848

**Comment by bethanylang** [comment]
@aaemnnosttv @kuasha420 Actually, will keep #6963 in this sprint as I see there are revisions to take care of there.

**Comment by mohitwp** [comment]
@wpdarren As discussed on slack I'm getting error when I'm running mentioned code snippet in QAB. Also, verified after setting the status under tester plugin 'ready' as you mentioned. Can you please look into this ? 

- Tested on main environment.
- Tested on UA dashboard. 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/1f700ce7-887e-43cd-83cf-96ac67a5dcd7)

![image](https://github.com/google/site-kit-wp/assets/94359491/1df33304-e3cf-4a64-a4a9-ee426c1608db)

</details>

**Comment by wpdarren** [comment]
@mohitwp I would check the code and QAB with @kuasha420 because I am seeing the same error message. I see the ABD CTA on the dashboard, so everything seems to be set up as expected.  I tested this with UA and GA4 dashboard view, and same error occurs. I also made sure that AdSense status for account and site is 'Ready'

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that the response is { "success": true } for the code.
- Verified  `the googlesitekit_adsense_recovery-tag` and `googlesitekit_adsense_error-protection-tag` options from the DATABASE. They populated with long base64 string.
- Verified for both UA and GA4 Dashboard.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/1ff56c0c-e8cf-432d-a8b0-bcb8c79e5894)

![image](https://github.com/google/site-kit-wp/assets/94359491/4c70e55f-5a91-49e6-888a-3d1cb7abcae2)

![image](https://github.com/google/site-kit-wp/assets/94359491/66883cf6-53e5-4a5b-875c-00b089a782fe)


</details>
