### ISSUE TITLE
Update positioning of `New` badges in table headings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6904]
## Feature Description

The "New" badges which are currently only added to the GA4 version of the dashboard in a few places to highlight the differences appear a bit awkwardly, especially in smaller viewports. After some review, we've put together an alternate layout that should work better at various sizes.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The positioning of "New" badges in tables should be updated to match [this design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1575-7834&t=D2Wz4NT6H2Cr00ro-4)
	* Badges should be on their own line aligned above all column headings
	* Column heading text should be aligned-top and to the right
* The new layout should be used in all viewports

## Implementation Brief

* In the `ReportTable` component
  * Add a new boolean const `showBadges` next to the exising `mobileColumns` const.
    * `showBadges` should be true, if at least one column has a badge `column.badge`.
  * Inside the `<thead className="googlesitekit-table__head">` verify if `showBadges` is true. If so render an additional table row `<tr>` inside the table header.
  * Render this new row above the existing row.
  * Inside this new table row, loop over the `columns` (like in the existing table header row) and add a `<th>` for each column.
  * Inside the `<th>` render the badge `column.badge`.
  * Copy over the classes from the existing `<th>` to the new `<th>`
  * Remove the `{badge}` from the existing table head.
* Verify it the spacing of the badges corresponds to the figma design from the AC. You can use the `ModulePopularPagesWidgetGA4` Storybook story for this.
  * If the spacing differs, add an additional `googlesitekit-table__head-item--badge` class to the new `<th>` and assign it appropriate styling in the `_googlesitekit-table.scss` file.
* In `_googlesitekit-table.scss`
  * For the existing `.googlesitekit-table__head-item` selector, set vertical-align to top.

Following the implementation, checkout [this comment](https://github.com/google/site-kit-wp/issues/6904#issuecomment-1516436819) and verify if we need to create a followup issue for the callout tour.

### Test Coverage

* Update the VRT images for the `ModulePopularPagesWidgetGA4.js` story.
* Verify the VRT scenarios for other tables are not affected (except if they include Badges)

## QA Brief

* Set up a new site and connect the Analytics module.
* Enable the GA4 dashboard view
* Go to the dashboard page
* Ensure that badges are positioned correctly as per the Figma design

## Changelog entry

* Update the positioning of the `New` metric badges in table headings.

**Comment by eugene-manuilov** [comment]
@derweili, I think if we implement it as you described it in IB, it will update only column headers with badges. Other columns that have no badges will have their titles at the top which will make it look odd like this:
![4myFNKBXvHn9b8y](https://user-images.githubusercontent.com/873049/233682874-abd87b8d-2ba5-4145-9d46-d22ee8dc4f73.png)

But it should be like this:
![4myFNKBXvHn9b8y](https://user-images.githubusercontent.com/873049/233682980-5c4d9614-8e54-47f5-967f-6b9b6c3c5d9d.png)

We need to figure out another approach how to align all titles when some of them have badges.

**Comment by derweili** [comment]
@eugene-manuilov the `vertical-align:bottom` in the IB should fix this.

**Comment by eugene-manuilov** [comment]
Ah... thanks, @derweili, I misread it as to be `top` instead of `bottom`. Anyway it won't work as well when the column header has multiple lines like on the following image, right?

![4myFNKBXvHn9b8y](https://user-images.githubusercontent.com/873049/233686668-ec64ddf2-97bf-4dcb-8edc-d077fb83efef.png)

**Comment by aaemnnosttv** [comment]
Maybe we can put placeholder "new" badges in all of the column headers and hide them with `visibility: hidden` to fill the space?

**Comment by eugene-manuilov** [comment]
It's a bit "dirty" approach 😄. I think what we can do is just render an additional row in the header for badges only if we have at least one column with a badge. In this case everything should be correctly aligned.

**Comment by derweili** [comment]
@eugene-manuilov updated the IB following you recommendation of using a separate table row.

**Comment by eugene-manuilov** [comment]
Thanks, @derweili. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@techanvil interested in your thoughts on the two observations found while testing. 

1. Now that we have made the changes to the badge placement, we've created a UI issue with the tooltip tour.  As you can see from the screenshots below, the tooltip slightly overlaps the text.  Is it possible to fix this within this ticket, or, do we have another ticket that it can be fixed in?  I can create a new ticket, just conscious this would likely be a new P0. 

![image](https://user-images.githubusercontent.com/73545194/235893732-1f2b32a7-fed9-411b-810c-4fdcf6e6c85d.png)
![image](https://user-images.githubusercontent.com/73545194/235893778-5c40dd06-8a03-4f36-bf1e-0e63a1c6b91c.png)

2. I'm not sure there's anything we can do about this but when going through all the different viewports, I noticed one issue at 601 pixels to 685 pixels wide. Basically at small tablet size to just about before moving to mobile viewport.  All of the titles start to become difficult to read.  Interested in your thoughts on this. 

![image](https://user-images.githubusercontent.com/73545194/235895304-9f0be4f5-e6c0-44bb-ab80-920510e30c53.png)

**Comment by eugene-manuilov** [comment]
@wpdarren 

> 1. do we have another ticket that it can be fixed in?

#6973

> I noticed one issue at 601 pixels to 685 pixels wide.

This is out of scope for this ticket, so we probably should create a new one to fix this issue.

**Comment by techanvil** [comment]
We've also got https://github.com/google/site-kit-wp/issues/7001 in the pipeline which will affect the Conversions feature tour highlight, so should add that as a dependency for #6973 as well.

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- The badges are positioned correctly as per the Figma design. 
  - Tested this on a few different viewports, and other than the issues highlighted above this looks good. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/235897268-e6316d2f-f662-487d-bcac-584190c3e559.png)
![image](https://user-images.githubusercontent.com/73545194/235897291-769fbbcd-d276-4a4b-b0dc-0748162996d9.png)
![image](https://user-images.githubusercontent.com/73545194/235897317-41ea824a-7b8b-497e-90bb-ce5e432aa5c5.png)
![image](https://user-images.githubusercontent.com/73545194/235897352-2175a258-7d30-4de2-a510-12617712e985.png)

</details>

**Comment by aaemnnosttv** [comment]
> > I noticed one issue at 601 pixels to 685 pixels wide.
> 
> This is out of scope for this ticket, so we probably should create a new one to fix this issue.

The issue of the table headers overlapping in certain viewport sizes is a long-standing known issue – see https://github.com/google/site-kit-wp/issues/5561

**Comment by aaemnnosttv** [comment]
LGTM 👍
