### ISSUE TITLE
Remove extra whitespace in PSI widget on entity and primary dashboard

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6905]
## Description

On the primary and entity dashboards for both GA4 and UA, there is a large whitespace that displays between the Total Blocking Time row and the How to improve button:

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/12189958/232856145-e95777a1-f0d1-4472-87b6-f40fe3b7daac.png">

It looks like this is occurring because there's an empty row in the table after Total Blocking Time. There's some hidden content there that says this is for "provid[ing] a consistent height for the widget," but when I remove it, I don't see any issues in multiple viewports.

1920x1080:
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/12189958/232856766-60dfcf6e-39d1-432f-81dc-c612e44e37d9.png">

iPhone 12:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/12189958/232856841-bb93937f-411c-4a6a-83bf-9c9ddaa584f8.png">

## Steps to reproduce

1. Go to Site Kit main dashboard and scroll down to PSI section
2. See empty space at bottom of widget

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
@bethanylang, this filler content was introduced by way of https://github.com/google/site-kit-wp/issues/4878, and is needed to ensure that both the "In the Lab" and "In the Field" tabs have the same height, IIRC, so the height is predictable and the skeleton loader can have the right size for both tabs, reducing the layout shift when loaded.

**Comment by bethanylang** [comment]
Thanks for the context, @techanvil! Closing.
