### ISSUE TITLE
"New" badges not present on entity dashboard

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6908]
## Bug Description

As reported by @aaemnnosttv in Bug Bash, "New" badges for GA4 metrics are not displaying at all/are displaying inconsistently on the entity dashboard.

![image](https://user-images.githubusercontent.com/12189958/233059639-e3d008f8-8b4b-4041-931c-c170567d43a4.png)

![image](https://user-images.githubusercontent.com/12189958/233059668-9abe536f-bf1d-48ac-902e-027976937e3e.png)

## Steps to reproduce

1. Activate the GA4 dashboard
2. Search for a URL or page to access the entity dashboard

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The "Search traffic" and "Overall page metrics" widgets on the Entity Dashboard should have a "New" badge displayed for the "Engagement Rate" and "Sessions" metrics.
- This should follow the same design as seen on the Main Dashboard.
- The tooltip copy should be the same as seen on the "Top content" widget on the Main Dashboard:

![image](https://user-images.githubusercontent.com/18395600/233068595-85e9f671-cd7a-40f3-900f-4366dff19c4c.png)

![image](https://user-images.githubusercontent.com/18395600/233068712-4070f85d-15e5-4d22-9e83-ead0e737e680.png)

## Implementation Brief

**Add "New" Badge to Search Traffic**

In `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/index.js`:
* Locate the `dataBlocks` array and find the object with the `id` of `engagement-rate`, where `showGA4 && dashboardType === DASHBOARD_TYPE_ENTITY`.
* Add a `badge` property to the object, with the value set to the `NewBadge` component. This should be similar to the `conversions` implementation for the main dashboard.
* Set the `tooltipTitle` prop to: "Sessions which lasted 10 seconds or longer, had 1 or more conversion events, or 2 or more page views."
* Retrieve the `learnMoreLink` value from the `getGoogleSupportURL` selector by passing an object with the `path` set to `/analytics/answer/12195621`.
* Use the same implementation as the `ModulePopularPagesWidgetGA4` component. Reference the code at:
https://github.com/google/site-kit-wp/blob/a3fa8f3dd0e23c49b34e7ed64b11441637e27a3e/assets/js/modules/analytics/components/module/ModulePopularPagesWidgetGA4.js#L214-L222

**Add "New" Badge to Overall Page Metrics**

In `assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidgetGA4.js`:
* Pass the `badge` prop to the rendered `DataBlock` elements for the `sessions` and `engagementRate` metrics. The `badge` value should be a `NewBadge` element.
* Use the same implementation as the ModulePopularPagesWidgetGA4 component for the `tooltipTitle` and `learnMoreLink` props for the `sessions` and `engagementRate` metrics. Reference the code at:
https://github.com/google/site-kit-wp/blob/a3fa8f3dd0e23c49b34e7ed64b11441637e27a3e/assets/js/modules/analytics/components/module/ModulePopularPagesWidgetGA4.js#L195-L203
https://github.com/google/site-kit-wp/blob/a3fa8f3dd0e23c49b34e7ed64b11441637e27a3e/assets/js/modules/analytics/components/module/ModulePopularPagesWidgetGA4.js#L214-L222

* Ensure the `SearchFunnelWidgetGA4` and `DashboardOverallPageMetricsWidgetGA4` stories reflect the changes.

### Test Coverage

* No new tests are to be added.

## QA Brief

* Go the entity dashboard page and ensure that you see badges mentioned in AC.

## Changelog entry

* Add "New" badges for the new GA4 metrics to widgets on the Entity Dashboard.

**Comment by bethanylang** [comment]
NOTE: The design for these badges will likely change in #6904 based on an updated design from UX.

**Comment by techanvil** [comment]
Hey @hussain-t, the IB looks good, I've made a small tweak to be a bit less specific about the first point for `DashboardOverallPageMetricsWidgetGA4`, as we might, for example, want to make a lookup table instead of looping through `data`. I think this detail can be left to the implementing engineer.

IB :white_check_mark:

**Comment by aaemnnosttv** [comment]
LGTM 👍
