### ISSUE TITLE
Chart key date indicator/line appears over the tooltip on the All Traffic widget chart

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6911]
## Bug Description

As reported by @techanvil in Bug Bash:

The key date indicator appears on top of the tooltip on the All Traffic widget chart:

![image](https://user-images.githubusercontent.com/12189958/233061237-6a2b91e7-4aab-4e66-b6eb-c7eb856ae2be.png)

This is not the case for the Search Funnel chart, which uses an HTML tooltip:

![image](https://user-images.githubusercontent.com/12189958/233061261-baa5b34c-0517-4a51-92f8-860bdffce4bc.png)

See https://github.com/google/site-kit-wp/pull/6822#issuecomment-1501584437 for more details.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The dotted line that marks the date of a UA cutoff/GA4 property creation date (created in #6572) should not appear "higher"/above any chart tooltip.
  * All chart tooltips should appear above the dotted/dashed line drawn by the date indicator. They should also appear above the "i" icon at the top of the dotted line

## Implementation Brief

* The GA4 User Count Graph component (`assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js`) should be updated to use `tooltip: { isHtml: true }`.
* The contents of the tooltip should be created similar to other HTML tooltips (see https://github.com/google/site-kit-wp/blob/0319a737626d47d68e9d38f08782e07887d72fe7/assets/js/modules/adsense/util/site-stats-data.js#L93-L149 for an example). Note that the tooltips must be pure HTML and not React components.
* The contents of the tooltip should mirror the previous contents, eg. show the date for the datapoint and the metric (users):
<img width="156" alt="CleanShot 2023-04-21 at 20 22 44" src="https://user-images.githubusercontent.com/90871/233718167-ef8b05a5-fff6-450f-8650-a375ed4e6049.png">

### Test Coverage

* No new tests needed; existing tests should pass.

## QA Brief

* Set up Site Kit with GA4 Reporting enabled and a site that has data.
* Load the All Traffic Widget with GA4 enabled.
  * Ensure the Date Marker appears. You can do this by setting the reference date near the creation date of your GA4 property, eg enter this JS code in the browser's JS console:

```js
const propertyID = googlesitekit.data.select("modules/analytics-4").getPropertyID();

const property = googlesitekit.data.select("modules/analytics-4").getProperty(propertyID);

const referenceDate = new Date(property?.createTime);
referenceDate.setDate(referenceDate.getDate() + 10);
const referenceDateString = [referenceDate.getFullYear(),`${referenceDate.getMonth() + 1}`.length < 2? `0${referenceDate.getMonth() + 1}`: referenceDate.getMonth() + 1,referenceDate.getDate().length < 2? `0${referenceDate.getDate()}`: referenceDate.getDate()].join("-");
googlesitekit.data.dispatch("core/user").setReferenceDate(referenceDateString);
```

* The All Traffic Widget's line graph chart's tooltip should appear above the dashed line in the chart:
<img width="248" alt="CleanShot 2023-04-28 at 00 56 20" src="https://user-images.githubusercontent.com/90871/235014549-44873774-576e-4a99-9319-9576a67f0bc0.png">

* In Site Kit settings, change Analytics to show UA data instead of GA4 data.
* Visit the Site Kit dashboard and set the reference date to be near the GA4 cutoff using the browser console with: `googlesitekit.data.dispatch("core/user").setReferenceDate('2023-07-10');`
* The All Traffic Widget's line graph chart's tooltip should appear above the dashed line in the chart.

## Changelog entry

* Prevent chart key date markers on the All Traffic Widget chart tooltips from overlaying the chart tooltips.

**Comment by tofumatt** [comment]
Marking as an 11 just because this is a Google Charts issue and they can often be a bit tricky, but there's prior art here so hopefully it's more straightforward than that. 🙂

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

For GA4 and UA

- The Date Marker appears and on the All Traffic Widget's line graph chart's tooltip, above the dashed line in the chart.  The tooltip appears as expected for GA4 and UA.  I checked this on the main, entity and view only dashboards. 
- I also checked the other charts where the key date date marker and tooltip appear. 
- Checked on all viewports including mobile. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/236216902-b757f0e5-1fa5-4fa5-963d-4c5af8eb0575.png)
![image](https://user-images.githubusercontent.com/73545194/236214076-619237e0-ef31-4a62-a589-4f3f169f3a47.png)
![image](https://user-images.githubusercontent.com/73545194/236214094-9b263d1e-a61f-49ef-804b-80e8c48ccc93.png)
![image](https://user-images.githubusercontent.com/73545194/236214115-6f7e6cf6-b00b-4d83-bb34-f79a00b0924e.png)
![image](https://user-images.githubusercontent.com/73545194/236214139-c5efab69-2ae9-4dc9-81c1-e78b913de29c.png)
![image](https://user-images.githubusercontent.com/73545194/236214168-3cb2059d-25be-4e84-87bc-bfa33b0e6e38.png)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
