### ISSUE TITLE
GA4 creation date marker not appearing on Search Funnel widget charts

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6912]
## Bug Description

As reported by @techanvil in Bug Bash:

When on the GA4 Dashboard View, the GA4 creation date marker is present on the All Traffic widget chart, but not on the Search Funnel widget charts for GA4 metrics.

![image](https://user-images.githubusercontent.com/12189958/233061631-1f1c21b3-6e98-4fda-9997-c5bed7c40fe4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When on the GA4 Dashboard View, and the GA4 creation date is within the current date range, the GA4 creation date marker should be present on the Search Funnel widget charts for GA4 metrics.
* These metrics are:
  * Main Dashboard: **Unique Visitors from Search** and **Conversions**.
  * Entity Dashboard: **Unique Visitors from Search** and **Engagement Rate**. 

## Implementation Brief

* Update the condition in the AnalyticsStats component to return early if it is **not** GA4 dashboard view: https://github.com/google/site-kit-wp/blob/dfb3bcbb7d773c6a90dc6b49890a340cf029def9/assets/js/modules/search-console/components/common/AnalyticsStats.js#L118-L120

### Test Coverage

* N/A

## QA Brief

* Setup Site Kit with `ga4Reporting` enabled and connect a GA4 property.
* Ensure the Dashboard View is set to Google Analytics 4.
* Navigate to both the Main and Entity Dashboard and verify the GA4 creation date marker is present on the Search Funnel widget charts as per the AC.
* In order to make sure the GA4 creation date is within the current date range so it will be visible on the chart, run the following snippet from the Bug Bash instructions in the JS console:

```js
const propertyID = googlesitekit.data
  .select("modules/analytics-4")
  .getPropertyID();
const property = googlesitekit.data
  .select("modules/analytics-4")
  .getProperty(propertyID);
const referenceDate = new Date(property?.createTime);

referenceDate.setDate(referenceDate.getDate() + 10);

const referenceDateString = [
  referenceDate.getFullYear(),
  `${referenceDate.getMonth() + 1}`.length < 2
    ? `0${referenceDate.getMonth() + 1}`
    : referenceDate.getMonth() + 1,
  referenceDate.getDate().length < 2
    ? `0${referenceDate.getDate()}`
    : referenceDate.getDate(),
].join("-");

googlesitekit.data.dispatch("core/user").setReferenceDate(referenceDateString);
```

## Changelog entry

* Fix appearance of the date marker on Search Funnel widget charts.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When on the GA4 Dashboard View, and the GA4 creation date is within the current date range, the GA4 creation date marker is present on the Search Funnel widget charts for GA4 metrics.
  - Main Dashboard: Unique Visitors from Search and Conversions.
  - Entity Dashboard: Unique Visitors from Search and Engagement Rate.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/234011160-c13a30d9-4fef-4df2-b3ee-61789e9eee2a.png)
![image](https://user-images.githubusercontent.com/73545194/234011280-49debebf-e8b7-4493-a615-8f214492c471.png)
![image](https://user-images.githubusercontent.com/73545194/234011306-498173e4-e7fb-4861-9d3c-55412f0bbd60.png)
![image](https://user-images.githubusercontent.com/73545194/234011330-ca784356-d24f-4dc6-bc8a-34f863b8c9e0.png)

</details>
