### ISSUE TITLE
On a new site the dashboard initially loads zero data, and then a few seconds later changes to Gathering

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6913]
## Bug Description

As reported by @wpdarren in Bug Bash:

When Site Kit and Analytics is set up for the first time, when the dashboard loads, it initially flashes zero data within the All Traffic widget (and possibly over areas too but difficult to know) and then 1-2 seconds later it changes to gathering state which is expected. 

You will need to change your network to Slow 3G to be able to see the change. 

Screencast below. 

https://user-images.githubusercontent.com/12189958/233062029-62f60534-1c85-4707-a4f0-c8903cff2c83.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the connected GA4 property is in a gathering data state, the GA4 version of the All Traffic widget should be shown in the gathering data state immediately after loading. It should not momentarily show the zero data state.
* This should be the case regardless of the connection speed, and should be verifiable on a connection throttled to Slow 3G and below.

## Implementation Brief

In `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4`:

* Target the `loaded` prop for each of the `DimensionTabs`, `TotalUserCount`, `UserDimensionsPieChart`, and `UserCountGraph` components at the point where they are rendered within the `DashboardAllTrafficWidgetGA4` component.
* Add a check for `isGatheringData !== undefined` to the `loaded` prop for each of these components. This will help control the loading state without having to change each child component individually, keeping their logic simpler.

### Test Coverage

* No new tests are to be added.

## QA Brief

* Set up Site Kit and Analytics 4 on a new site with the enabled `ga4Reporting` feature flag.
* Throttle your network connection to Slow 3G.
* Load the Site Kit dashboard.
* Observe the All Traffic widget and ensure it doesn't flash the zero data state before showing the gathering data state.
* Test on various connection speeds, including Slow 3G, to ensure the issue is resolved.

## Changelog entry

* Prevent the GA4 All Traffic widget from momentarily displaying in the zero data state while it's waiting to determine the gathering data state.

**Comment by techanvil** [comment]
Hey @hussain-t, the IB looks good, I would however suggest a small change to the approach.

What I'd suggest is that we instead target the `loaded` prop for each of the `DimensionTabs`, `TotalUserCount`, `UserDimensionsPieChart` and also `UserCountGraph` to keep that in sync too, at the point where they are rendered within the `DashboardAllTrafficWidgetGA4` component. We'd just need to add a check for `isGatheringData !== undefined` to each of them. That would avoid having to change each child component individually and keep their logic simpler - I think it's nice if the `loaded` prop is enough to control the loading state. It also keeps these related values next to each other which makes for easier management of them.

How does that sound to you?

**Comment by hussain-t** [comment]
Thanks, @techanvil. I have updated the IB. This is a cleaner approach 👍

**Comment by hussain-t** [comment]
Thanks, @techanvil. I have updated the IB. This is a cleaner approach 👍

**Comment by techanvil** [comment]
Thanks @hussain-t. LGTM!

IB :white_check_mark:

**Comment by mohitwp** [comment]
###QA Update ✅ 

- Tested on develop.
- Verified When the connected GA4 property is in a gathering data state, the GA4 version of the All Traffic widget showing in the gathering data state immediately after loading. It is not momentarily showing the zero data state.


<details>


https://user-images.githubusercontent.com/94359491/234012730-70bf58ac-d6c7-4bbd-8ea1-0b021fbb0c71.mp4

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
