### ISSUE TITLE
Duplicate URLs on Site Kit widget on WP Dashboard

### ISSUE THREAD

**Issue by mxbclang** [google/site-kit-wp#6918]
## Bug Description

As reported by @wpdarren in Bug Bash:

Only occurs when GA4Reporting flag is enabled.  
The URLs are duplicated as you can see from the screenshot. 

![image](https://user-images.githubusercontent.com/12189958/233104802-ebee2592-5feb-4561-a2a9-a3312ebf356c.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- When the `ga4Reporting` feature flag is enabled, the `WPDashboardPopularPagesGA4.js` component should not display duplicated pages.

## Implementation Brief

- In `assets/js/components/wp-dashboard/WPDashboardPopularPagesGA4.js`:
  - In the `dateRangeDates` variable assignment, remove the `compare` property from the object passed to the `getDateRangeDates()` selector of the `core/user` store.
- In `assets/js/components/wp-dashboard/common-GA4.stories.js`:
  - Update the mock options for the "Popular pages" report's response to not include the `compareStartDate` and `compareEndDate` properties.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Enable the GA4 dashboard view
* Go to the WordPress dashboard
* Ensure that you don't see duplicate URLs in the Popular Pages widget.

## Changelog entry

* Fix bug that could cause duplicate entries in the WP dashboard Popular Pages widget when using GA4.

**Comment by nfmohit** [comment]
### Note to AC Reviewer:

While writing the ACs, I also added the IB to it just to try and move quicker. Thanks!

**Comment by tofumatt** [comment]
ACs here are good, as is the IB 

Moving right to the backlog 👍🏻

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on GA4.
- Verified when both GA4 and UA properties are connected and Dashboard view is GA4.
- Verified when only GA4 is connected.
- Verified Duplicate URL's are not showing on WP dashboard widget when Dashboard view is GA4.

**Note** : But I've noticed that when Dashboard view is UA then Duplicate URL's are appearing. I will create separate issue for this as this is an existing issue.

<details>

When Dashboard view is GA4

![image](https://user-images.githubusercontent.com/94359491/234006803-d1963892-85d0-4b0e-8dba-8398c8688211.png)

</details>

**Comment by mohitwp** [comment]
Created separate ticket here : https://github.com/google/site-kit-wp/issues/6972

**Comment by aaemnnosttv** [comment]
LGTM 👍
