### ISSUE TITLE
Analytics account change is not detected in the settings edit page

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6919]
## Bug Description

As reported by @hussain-t in Bug Bash:

When we go to the Analytics settings edit page and change to an account that doesn't have UA properties, it isn't detected as settings changed. Therefore, the Confirm Changes button is still disabled.

https://user-images.githubusercontent.com/12189958/233110573-5134eca0-de42-4805-bd5f-026267a39b6f.mov

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* With `ga4Reporting` enabled, when on the Analytics settings page, upon changing to an account that only has GA4 properties, the **Confirm Changes** button should be enabled and the settings should be able to be successfully saved.

#### Background for Context

* This issue occurs because of the changes made in this [commit](https://github.com/google/site-kit-wp/pull/6817/commits/7bbcfa8e1793faaaa84307c2c0b36dce3ccd140c). Code:
https://github.com/google/site-kit-wp/blob/ab914a707914017ffcc0c4080099ad48b16fd831/assets/js/modules/analytics/components/common/EnableUniversalAnalytics.js#L97-L101
* Once the `enableUA` is set to `true` in the state, it is never set to `false` again during the account select/change. So, when a GA4 only account is selected, the `enableUA` state is still `true` and fails in the `validateCanSubmitChanges` function. See:
https://github.com/google/site-kit-wp/blob/ab914a707914017ffcc0c4080099ad48b16fd831/assets/js/modules/analytics/datastore/settings.js#L221-L223

In `assets/js/modules/analytics/components/common/EnableUniversalAnalytics.js`:

* Change the condition within the `useMount` hook to check if the account has UA properties, i.e., more than 0 UA properties, instead of checking the current property ID. 

**Note:** This is to fix the issue where the `enableUA` state is set to `false` when the account is changed to a GA4 only account. Because the UA property is not auto-selected when the account changes, the property ID will be unavailable. Due to that, the "Enable Universal Analytics" toggle will not the selected. Reference for UA property auto selection disabled  #6820.

In `assets/js/modules/analytics/components/common/AccountSelect.js`:

* Using the `useEffect` hook, set the `enableUA` state to `false` if it is already `true` and the account has no UA properties.

### Test Coverage

* No new tests are to be added.

## QA Brief

* Make sure the `ga4Reporting` feature flag is enabled.
* Set up Analytics with both GA4 and UA properties connected.
* Go to the Analytics settings page and change the account to one with only GA4 properties. Refer to this [comment](https://github.com/google/site-kit-wp/issues/6919#issuecomment-1519851437).
* Confirm that the **Confirm Changes** button is enabled.
* **Note:** When you change the account back to the previous one, which had the "Enable Universal Analytics" option enabled, the toggle will be disabled at this point. This issue will be fixed in #6921.

## Changelog entry

* Ensure that changing to an Analytics account which doesn't have Universal Analytics properties is detected as a change to the settings in the Analytics Settings edit page.

**Comment by bethanylang** [comment]
@techanvil and @hussain-t have been unable to replicate, so closing this as not planned.

**Comment by hussain-t** [comment]
@bethanylang, this issue is still open. Could you please close it? Thanks!

**Comment by hussain-t** [comment]
@bethanylang @techanvil Finally, I could reproduce this issue. It occurs when you have UA and GA4 connected and tries to change the account with only GA4 properties. @mohitwp reproduced it too.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- I set up Analytics with both `GA4` and `UA` properties connected. I then went to Analytics settings page and changed the account to one with only GA4 property.  The Confirm Changes button is enabled.
- Confirmed also that when you select a GA4 only account, the Universal Analytics section is removed. 
- In addition to the details in the QAB. I made sure that when clicking the confirmed changes button that the GA4 property was set up and no issues occurred in the console. 

https://user-images.githubusercontent.com/73545194/235138503-4d410a61-63da-4715-9526-1f8b3c64be6c.mp4

**Comment by aaemnnosttv** [comment]
LGTM 👍
