### ISSUE TITLE
Sidekick image very small on GA4 dashboard prompt banner

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6920]
## Description

As reported by @bethanylang and @hussain-t in Bug Bash:

The sidekick image on the GA4 dashboard prompt banner is very small on multiple screen sizes:

![image](https://user-images.githubusercontent.com/12189958/233124847-3eb8b3c5-88e4-4c9c-bb67-e090da581e24.png)

1280x1040

![image](https://user-images.githubusercontent.com/12189958/233124877-ccf0da90-739a-49d8-bb53-bab7c16b57a2.png)

1920x1080

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `WinImageSVG` (`ga4-success-green`) image on the `SwitchGA4DashboardViewNotification` component should be displayed larger to match the [Figma](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1-4826&t=FPaHhLze70B1Njma-0) design.
* It should be hidden on smaller (mobile) screens.
* The image display and hiding behavior should be implemented similarly to the GA4 `SuccessBanner` component.

## Implementation Brief

In `assets/js/components/notifications/SwitchGA4DashboardViewNotification.js`:
* Pass the `GA4SuccessGreenSVG` as a functional (component) reference to the `WinImageSVG` prop like, `() => <GA4SuccessGreenSVG />`.

### Test Coverage

* No new tests are to be added.

## QA Brief

- Set up Site Kit.
- Without the `ga4Reporting` feature flag enabled, set up the Analytics module with both UA and GA4.
- Enable the `ga4Reporting` feature flag.
- Go to the Site Kit dashboard and observe the "Switch to GA4 Dashboard View" banner notification.
- Verify that the sidekick image is larger according to the Figma designs mentioned in the ACs.

## Changelog entry

* Fix the svg image size issue on the "Switch to GA4 Dashboard View" banner.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

I have a few questions:

1. For mobile the decision was to hide the Sidekick image, but on tablet it is still appearing and is small.   Do you think we should hide the image on tablets as well? 

![image](https://user-images.githubusercontent.com/73545194/235441834-7741bc9a-5d27-43c0-a230-e2cc25d2d3f1.png)

2. On the figma design there seems to be larger space between the image and the end of the banner.  I think it's aligned too far to the right side of the banner.  Thoughts welcome on this, but it does look odd alignment on my test site. 

**My test site:**
![image](https://user-images.githubusercontent.com/73545194/235442027-ecbb701f-459d-40e9-9c73-b6008f724cf0.png)

**Figma design**
![image](https://user-images.githubusercontent.com/73545194/235442080-950ec5bf-3020-486b-a936-33b3246fc0a9.png)

**Comment by tofumatt** [comment]
@wpdarren I think for tablets the image is fine; we shouldn't be extending the text out that far on tablets anyway for readability, so I think it's fine to add the image there.

What resolution are you using/what is the size of your browser in that screenshot?

Honestly right-aligning it is probably more flexible as the screen grows and I _personally_ prefer it slightly, as otherwise the image feels like it's "floating" in the center a bit to me. But I don't have a strong opinion one way or the other.

I'd probably say this is fine—I think most other images are right-aligned. It also aligns with the right-aligned menu as well.

I think we should leave it as-is for now 🙂

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The WinImageSVG image on the SwitchGA4DashboardViewNotification component is displayed larger.
- It is hidden smaller screens but does appear small on tablets. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/235471451-a7d1c275-4dc1-4a71-995f-24d717373d90.png)
![image](https://user-images.githubusercontent.com/73545194/235471541-4f037c35-6dde-4512-a4e3-720c6fc2a32c.png)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
