### ISSUE TITLE
The UA property dropdown is no longer auto-selecting when UA is enabled

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6921]
## Bug Description

As reported by @techanvil in Bug Bash:

The UA property dropdown has stopped auto-selecting a property when UA is enabled in Settings.

This is both when the "Enable Universal Analytics" toggle is first enabled, and when changing to a new Account with the toggle already enabled.

![image](https://user-images.githubusercontent.com/12189958/233125735-07e21e4c-d0d4-4a7a-937f-b0e42ec13b4b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the UA toggle is enabled, if there is a matching property for the site, it should be automatically selected after enabling UA in Analytics Settings.

## Implementation Brief

* In the `assets/js/modules/analytics/components/common/EnableUniversalAnalytics.js` file:
  * Update the `onChange` callback to find the matching property using the `findMatchedProperty` action if the `enableUA` value becomes true and current propertyID and profileID are empty. If the action returns a property, select it using the `selectProperty` action.
  * Display small progress bars instead of `PropertySelect` and `ProfileSelect` while looking for a matched property.

### Test Coverage

* N/A

## QA Brief

* Ensure the `ga4Reporting` feature flag is enabled.
* Verify that when the "Enable Universal Analytics" toggle is enabled, the matched property for the selected account is automatically selected.
* Confirm this behavior in both the setup and settings edit forms.
* **Note:** The account setup URL and the site URL should be the same to auto-select the property for the selected account. If the account is setup using a different URL, the property won't be auto-selected.

## Changelog entry

* Ensure Universal Analytics property is automatically selected when GA4 Reporting is enabled.

**Comment by nfmohit** [comment]
Just a note that this was intentionally done initially as a UA property was being unconditionally auto-selected even though the user didn't opt-in to enable UA, as reported in #6820.

This was added as a part of the PR (https://github.com/google/site-kit-wp/pull/6817) for https://github.com/google/site-kit-wp/issues/6744 ([commit](https://github.com/google/site-kit-wp/pull/6817/commits/0a7218874e136ab203b435e377c43e35eab59ed7)).

A good enhancement here could be auto-selecting a UA property only when the `Enable Universal Analytics` toggle is on.

**Comment by techanvil** [comment]
Thanks for the added context, @nfmohit. We'll need to figure out what the UX should be here - your suggestion sounds good to me.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested when 'ga4Reporting' feature flag is enabled.
- Verified UA property dropdown auto selection under set up as well as under settings.
- Verified if there is a matching site, then enabling the toggle button auto selects the property.

<details>


https://github.com/google/site-kit-wp/assets/94359491/f7e701e1-c83c-4504-986f-f31855d48cba



</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
