### ISSUE TITLE
GA4 Activation Banner content alignment looks a bit off in some viewports

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6922]
## Description

As reported by @techanvil in Bug Bash:

The "Google Analytics 4 benefits" section in the GA4 Activation Banner might be better left-aligned instead of centred in medium width viewports (between ~384 - 600px).

It also looks like the same content could be better aligned in wider viewports (600px+), at the moment it's left-aligned to a line a bit to the right of the centre, but it would probably look better left-aligned to the centre line.

To illustrate here's the banner at 384px:

![image](https://user-images.githubusercontent.com/12189958/233126047-6e8683a1-d11b-4d70-b7c4-4168d71637b0.png)

500px, where the centre-alignment is in effect:

![image](https://user-images.githubusercontent.com/12189958/233126076-650ff4be-a8f3-4ad7-a636-b44a0a6259d2.png)

More pronounced, at 599px:

![image](https://user-images.githubusercontent.com/12189958/233126115-7dfa5a9d-5e1c-4072-b617-c8ac2d5fa8a4.png)

600px, note the right-hand content is left-aligned slightly off the centre line:

![image](https://user-images.githubusercontent.com/12189958/233126163-8b916a9e-773a-4cd9-aad2-531ca9bbb8ed.png)

1400px:

![image](https://user-images.githubusercontent.com/12189958/233126198-afd6bc3d-200d-4e68-ae28-4c6e45ba6533.png)

1400px, this time with Flexbox outlining enabled to further illustrate the alignment:

![image](https://user-images.githubusercontent.com/12189958/233126240-b9fdbd68-7601-42ec-875d-95edeec07cc1.png)

Here's how it could look at 500px if left-aligned:

![image](https://user-images.githubusercontent.com/12189958/233126279-7075dcf6-9b4c-46b5-bba5-265201d59d32.png)

Here's how it could look at 1400px if left-aligned to the centre (Flexbox outlining enabled):

![image](https://user-images.githubusercontent.com/12189958/233126312-d18d1b2b-e1d3-4ecb-83e9-1a7651c6732e.png)

Here's the same thing without the Flexbox outline:

![image](https://user-images.githubusercontent.com/12189958/233126361-0e6f1a45-e1c2-4488-82b4-3b47e6d8bd74.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The secondary pane of the GA4 Activation Banner notification should have its horizontal auto margin removed so that it is not centred.

## Implementation Brief

* Find the `.googlesitekit-publisher-win__secondary-pane` class in the `assets/sass/components/analytics-4/_googlesitekit-analytics-4-reminder-banner.scss` file and add `margin: 0` property to it.
* Merge #7000

### Test Coverage

* N/A

## QA Brief

* Since this is a small UI issue, we can verify it using the storybook story: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-reminderbanner--initial-notice
* Set different viewports for the aforementioned story and ensure that the benefits block is aligned correctly on all viewports.
* View https://google.github.io/site-kit-wp/storybook/develop/iframe.html?id=modules-analytics4-reminderbanner--initial-notice&viewMode=story and adjust the sizes in responsive browser tools to ensure the alignment is good in many mobile sizes. The secondary content (eg. the list) should never be center-aligned:

https://user-images.githubusercontent.com/90871/236526160-5c4147e1-0f99-4e4f-943c-7b2816c420bd.mp4

## Changelog entry

* Enhance the responsive layout of the GA4 Activation Banner.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
IB ✅ 

I'll move this one right to CR since it has a PR ready 👍🏻

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on https://google.github.io/site-kit-wp/storybook/develop/iframe.html?id=modules-analytics4-reminderbanner--initial-notice&viewMode=story
- Verified The secondary content (eg. the list) is not center-aligned.

<details>


https://github.com/google/site-kit-wp/assets/94359491/59f7e1fb-5389-411d-89af-26cb698687f0

![image](https://github.com/google/site-kit-wp/assets/94359491/ea346674-26e5-4356-9309-799c9bf73595)

![image](https://github.com/google/site-kit-wp/assets/94359491/6bddbe1d-ad02-4cba-9ec2-06d86c218da1)

![image](https://github.com/google/site-kit-wp/assets/94359491/3097e40e-b701-42ef-b2ad-d13acb54e2f9)

![image](https://github.com/google/site-kit-wp/assets/94359491/148b6643-f402-475b-b791-8969cb7ecc00)

![image](https://github.com/google/site-kit-wp/assets/94359491/03474d7a-f24c-4871-8180-36bbc1fedec4)

![image](https://github.com/google/site-kit-wp/assets/94359491/469a0a27-3381-4960-b5c9-924acc4c78f5)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
