### ISSUE TITLE
Improve the consistency between configuration notices in Analytics Settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6923]
## Description

As reported by @jamesozzie in Bug Bash:

![image](https://user-images.githubusercontent.com/12189958/233127309-adb450ec-0a7e-4dd2-81e5-3cf09617e5ac.png)

For some of the Analytics settings, the message below the setting in some cases uses a full stop, in others it's not the case. While not specific to GA4, either include a period at the end of each setting description, or remove all periods. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- In Analytics `SettingsEdit`, remove any period after setting descriptions. There shouldn't be any period after any setting description, similar to the GA4 Dashboard View Toggle, and the Enable Universal Analytics toggle.
    - The exception is when the description is followed by a link, in which case there should be a full stop after the description before the link
    - See https://github.com/google/site-kit-wp/issues/2597 (AC) for guidance

#### Files to Update

* `assets/js/modules/analytics/components/settings/SettingsUseSnippetSwitch.js`
* `assets/js/modules/analytics-4/components/settings/SettingsUseSnippetSwitch.js`

* **Locate and Edit Description Values**: Open the above-mentioned files, locate the `description` values within the `SettingsUseSnippetSwitch` components, and edit the text strings to remove the periods.

### Test Coverage

* Update any VRT images that may be affected by the changes.

## QA Brief

* Setup analytics
* Go to settings and expand Analytics module
* Click on edit link, and verify that all one paragraph option descriptions do not include period at the end of the sentence

## Changelog entry

* Improve copy consistency on the Analytics Settings view.

**Comment by eugene-manuilov** [comment]
> * In Analytics `SettingsEdit`, include a period after each setting description, since these are meant to be descriptive full-sentences.

@nfmohit, it should be other way around. I don't remember in which ticket we discussed and implemented it originally, but sentences like that should not have periods at the end.

cc @aaemnnosttv in case you remember the original ticket.

**Comment by nfmohit** [comment]
> @nfmohit, it should be other way around. I don't remember in which ticket we discussed and implemented it originally, but sentences like that should not have periods at the end.

I see, thank you for pointing that out. I have updated the ACs accordingly. Please take a look, thank you!

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by aaemnnosttv** [comment]
> @nfmohit, it should be other way around. I don't remember in which ticket we discussed and implemented it originally, but sentences like that should not have periods at the end.

It was #2597 issue which we initially standardized things according to Google's guidelines for language, so the AC there should still be relevant going forward 👍 
* https://github.com/google/site-kit-wp/issues/2597

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Clicked on edit link, and all one paragraph option descriptions do not include period at the end of the sentence.
- I enabled/disabled all of the toggles and made sure that the descriptions did not include a period at the end. 

https://github.com/google/site-kit-wp/assets/73545194/b2c57745-3274-48c4-bd0c-8081b1f7392d
