### ISSUE TITLE
Change language for "You only have 0 days left" on GA4 setup prompt banner

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6925]
## Description

As reported by @aaemnnosttv in Bug Bash:

When setting the reference date to June 30, we see the above in the activation banner.

![image](https://user-images.githubusercontent.com/12189958/233128941-f11909d6-5748-43fb-a785-6fefe3322e31.png)

It would ideally read "You have 0 days left [...]" but not sure it's worth making the last day a special case.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The heading of the reminder banner for a post-June 1 date should be updated as follows (using [proper i18n for pluralization](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#basic-pluralization)):
	* For days > 1 or 0:  
	> You have {n} more days to set up Google Analytics 4
	* For 1 day:  
	> You have {n} more day to set up Google Analytics 4

## Implementation Brief

In `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js`:

* Locate the code block that assigns the `title` variable with the string, `You only have %d more days to set up Google Analytics 4`.
* Update the code to incorporate pluralization logic using the `_n()` function to determine the correct plural form as follows:
    * For 1 day as the first (singular) argument:  
    > You have %d more day to set up Google Analytics 4
    * For days > 1 or 0 as the second (plural) argument:
    > `You have %d more days to set up Google Analytics 4` 
    * count - The number of days remaining until the deadline as the third argument.
    * `google-site-kit` - The text domain as the fourth argument.
* Add stories for 0 days and 1 day remaining to the `ReminderBanner` storybook.

### Test Coverage

* No new tests are required for this change.

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@marrrmarrr I've suggested removing the "only" from the text to avoid an added special case. Is that okay with you?

**Comment by marrrmarrr** [comment]
@aaemnnosttv 👍

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
IB ✅

**Comment by bethanylang** [comment]
@aaemnnosttv Given that tomorrow is 0 days left, should this issue be closed?

**Comment by aaemnnosttv** [comment]
@bethanylang yes, there's no point in doing it any more since this release is already going out after the cutoff. Closing 👍
