### ISSUE TITLE
Update language on GA4 Reporting tooltip tour

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6927]
## Description

As reported by @bethanylang in Bug Bash:

![image](https://user-images.githubusercontent.com/12189958/233129926-282b36b6-4567-43c3-acde-0b940f092f7e.png)

On Slide 1: In American English, comma should go inside the quotes, so: _"Conversions have replaced "Goals," since "Goals" no longer exist in GA4._

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The first slide of GA4 Reporting feature tour should have its copy updated, such that the comma (,) after the quotation mark is moved inside the quotation marks.
- It should be the following to be precise: `"Conversions" have replaced "Goals," since "Goals" no longer exist in GA4.`

## Implementation Brief

- In `assets/js/feature-tours/ga4-reporting.js`:
  - Locate the text mentioned in the ACs. It is located in `ga4Reporting.steps[ 0 ].content`.
  - Update the text to match the amendment in the ACs.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Trigger the GA4 Reporting Tour. To do so, perform the following steps:
    * _Without_ the _ga4Reporting_ feature flag enabled, set up a new site and connect the Analytics module with GA4.
    * Enable the _ga4Reporting_ feature flag.
    * Go to the dashboard and note the banner that suggests you switch to the GA4 dashboard view.
    * Click on the CTA button to switch said GA4 dashboard view, after which - following a short period of time - the dashboard should switch to GA4 and the GA4 Reporting feature tour should commence.
* Validate that the text on slide 01 reads as follows: `"Conversions" have replaced "Goals," since "Goals" no longer exist in GA4. Learn how to set up Conversions` where "Learn how to set up Conversions" is a link.
    * Importantly, the main change is around including the comma within the double quotes of `"Goals,"` as opposed to the comma being outside of the double quotes prior.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by techanvil** [comment]
Hey @10upsimon, code-wise, obviously this is just a one-liner copy change and your PR is spot on.

However, on the QAB front, this does conceptually merit the same [comment](https://github.com/google/site-kit-wp/issues/6926#issuecomment-1620186588) I made on another issue recently:

> ... could you please add a bit more info to the QA Brief about how to trigger the GA4 Reporting feature tour? This would be helpful to save time during testing for both CR and QA.

Of course as we now have the linked issue as a reference, feel free to either copy the steps from its QAB. or simply link to the issue from this one.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified language on GA4 updated as per AC. ` "Conversions" have replaced "Goals," since "Goals" no longer exist in GA4.`

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/7e72012e-803e-4d0c-b216-f4b7f4a2e078)

</details>
