### ISSUE TITLE
Update Learn what's new link on GA4 dashboard prompt banner

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6928]
## Description

As reported by @bethanylang in Bug Bash:

Right now the "Learn what's new" link on the GA4 dashboard prompt banner goes to the general GA4 guide: https://sitekit.withgoogle.com/documentation/using-site-kit/ga4/.

This should change to https://sitekit.withgoogle.com/documentation/using-site-kit/using-the-site-kit-dashboard/#ga4.

Note that while the main URL (Using the Site Kit Dashboard guide) is live, the anchor link to #ga4 will not go live until feature launch day.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The "Learn what's new" link in the "Switch to GA4 Dashboard View" banner should be updated to use the following URL:
  - https://sitekit.withgoogle.com/documentation/using-site-kit/using-the-site-kit-dashboard/#ga4

![image](https://user-images.githubusercontent.com/18395600/233141700-32c3ffe1-15fc-423b-83d3-5926f2342f80.png)

## Implementation Brief

<del>In `assets/js/googlesitekit/datastore/site/urls.js`:</del>

* <del>Modify the `getDocumentationLinkURL` selector to include an additional parameter, `hash`. This optional parameter allows for a hash anchor in the generated URL.</del>
* <del>Modify the return statement to append the `hash` value if provided; otherwise, keep the existing behavior.</del>

In `assets/js/components/notifications/SwitchGA4DashboardViewNotification.js`:

* Locate to the `getDocumentationLinkURL` selector call and pass `using-the-site-kit-dashboard-with-ga4` as the `slug` parameter <del>and `#ga4` as the `hash` parameter</del>.

### Test Coverage

* <del>Add test coverage for the new `getDocumentationLinkURL` selector for the above changes.</del>

## QA Brief

* Ensure that the "learn what's new" link leads to the `https://sitekit.withgoogle.com/support/?doc=using-the-site-kit-dashboard-with-ga4` URL.
* Verify that once you click on that link you get redirected to the `https://sitekit.withgoogle.com/documentation/using-site-kit/using-the-site-kit-dashboard/#ga4` page.

## Changelog entry

* Update the URL for the "Learn what's new" link on the "Switch to GA4 Dashboard View" banner.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
Actually, IB is ❌. The problem is that that hash will be ignored on the service side and redirect to the correct documentation page won't happen until we add the correct redirect mapping to the redirects mapping document and upload it to production.

@bethanylang, I am going to adjust IB to change the slug of the documentation redirect url to be `using-the-site-kit-dashboard-with-ga4`. Can we add the corresponding redirect to the spreadsheet? cc @adamdunnage @jamesozzie

**Comment by bethanylang** [comment]
Thanks @eugene-manuilov! I've created an Asana task and tagged you, James, and Adam in to get this updated and answer any further questions.

**Comment by jamesozzie** [comment]
Notes left regarding this in the related Asana task, with the URL and message added to the MVP mapping document @eugene-manuilov

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified**

- Tested on dev.
- Verified that the "learn what's new" link leads to the https://sitekit.withgoogle.com/support/?doc=using-the-site-kit-dashboard-with-ga4 URL.
- Verified that clicking on that link redirects to the https://sitekit.withgoogle.com/documentation/using-site-kit/using-the-site-kit-dashboard/#ga4 page.

![image](https://user-images.githubusercontent.com/94359491/234883623-93dad5fa-321a-4637-9181-2e66e5f26f1c.png)

**Comment by aaemnnosttv** [comment]
LGTM 👍
