### ISSUE TITLE
Create the Ad blocking recovery main notification component 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6929]
## Feature Description

A new component that displays the main notification of Ad Blocker Detection should be created according to the [Figma](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?node-id=368-3000&t=HK4JuCJm5yz0GuUu-0) design. This component will later be rendered when appropriate using the Widgets API in the Monetization section of Site Kit's main dashboard. 

![Screenshot_20230421_173752](https://user-images.githubusercontent.com/6187401/233628028-9ce6b986-3cf8-4abb-83fc-ca88433898b9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component that displays the main notification of Ad Blocking Recovery should be created based on the [Figma](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?node-id=368-3000&t=URvzCDoL2mN1oWmj-0) design.
* The layout, graphics, typography and CTA buttons should match the design. 
* Clicking on the primary CTA should navigate user to the `googlesitekit-ad-blocking-recovery` page. 
* Clicking on secondary CTA should permanently dismiss it.
* Note that this issue is only about creating the component, it will be placed on the dashboard in #6953 

## Implementation Brief

* Create `AdBlockingRecoveryNotification` component in `assets/js/modules/adsense/components/dashboard`.
    * Create the layout defined in the design using the `Grid`, `Row`. and `Column` layout components. 
    * Save the graphics from Figma in `assets/svg` folder and use it. 
    * Use `SpinnerButton` for the primary CTA.
        * Use `navigateTo` selector from `CORE_LOCATION` to navigate user to the defined page in the AC.
    * Use a regular text `Button` for the secondary CTA.
        * Use `dismissed-items` to permanently dismiss the notification component when pressed. 
    * Create `assets/sass/components/dashboard/googlesitekit-ad-blocking-recovery-notification.scss` and add any component style here based on Figma.
        * Styles include but not limited to: margin, padding, typography etc.
        *  Include it in the `assets/sass/admin.scss`
* Since there is no design available for mobile view, follow the prior arts on Success Notification and elsewhere. Namely, 
    * Hide the graphics. 
    * Put the disclaimer text under the CTA buttons. 
* Add story for the component. 

### Test Coverage

* Not needed. 

## QA Brief

* Set up the site and enable the `adBlockerDetection` feature flag.
* Activate the adsense module.
* Go to the dashboard and scroll down to the monetization section.
* Ensure that you see the widget with the Ad Blocker Recovery notification.
* Click on the `Set up now` button and verify that you get redirected to the new ad blocker recovery page.
* Go back to the dashboard and find the widget again.
* Now click on the `Maybe later` link and ensure that the widget is dismissed now.

## Changelog entry

* Add Ad Blocking Recovery set up CTA to the Monetization section of the dashboard.

**Comment by tofumatt** [comment]
ACs here are good 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
@marrrmarrr @aaemnnosttv the banner contains the `Learn More` link in the description. Which URL should we use for that link?

**Comment by kuasha420** [comment]
@eugene-manuilov It should point `https://support.google.com/adsense/answer/11576589` with correct locale as seen in Figma. Cheers.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov  I have noticed a few differences between the figma designs and test site. 

1. Space between the asterix and text.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/7b582238-6360-4735-8115-85c56892ae6e)
![image](https://github.com/google/site-kit-wp/assets/73545194/085edf06-3585-4391-bfb7-08bd31b56b04)

</details>

2. Font colour difference.  

<details>
 <summary>Screenshot</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/9f2fc214-3287-4f5d-8ddc-36ca1f9732b8)

</details>

Figma says it should be `#6C726E` admittedly, the colour on the plugin is easier to read, but thought I'd flag it. 

4. In the IB it mentions:

> Use `SpinnerButton` for the primary CTA

I didn't see any spinning animation on the button when I clicked it. 

https://github.com/google/site-kit-wp/assets/73545194/2b9e0e18-415c-4a54-a9ec-4c36bed539c9

5. I know it doesn't mention dimensions should be the same as figma in the AC, but I noticed a few differences.

The height of the notification component. 

<details>
 <summary>Screenshot</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/95d04f10-aa35-4f4f-8a77-0a4dd13477fe)

</details>

The width/height of the SVG.

<details>
 <summary>Screenshot</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/beb49156-065c-4fa1-abfd-9ad33f1dd42d)

</details>

Interested in your thoughts. 

**Verified:**

- With the adBlockerDetection feature flag enabled and AdSense setup. 
   - The widget with the Ad Blocker Recovery notification appears.
   - When clicking on the Set up now button and you are redirected to the new ad blocker recovery page.
   - When clicking on the Maybe later link the widget is dismissed.

**Comment by eugene-manuilov** [comment]
Thanks, @wpdarren. I have created a new PR that adjusts issues 1, 2 and partially 5. The 4th is not an issue because the spinner button isn't really needed there because that button is just a link. Once my PR is reviewed, I'll assign this ticket back to you.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- With the adBlockerDetection feature flag enabled and AdSense setup. 
   - The widget with the Ad Blocker Recovery notification appears.
   - When clicking on the Set up now button and you are redirected to the new ad blocker recovery page.
   - When clicking on the Maybe later link the widget is dismissed. 

The issues reported above are all fixed. 

![image](https://github.com/google/site-kit-wp/assets/73545194/7e4528e1-0b0b-463d-acc0-cb99a3750174)
