### ISSUE TITLE
"Dashboard view" title should be capitalized to "Dashboard View" in Settings > Connected Services > Analytics

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6931]
## Bug Description

As reported by @bethanylang in Bug Bash:

We capitalize every other phrase in the settings headers so this should be capitalized as "Dashboard View," too.

![image](https://user-images.githubusercontent.com/12189958/233134675-67b37992-e1b9-48c1-bd40-9159f9d83b95.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Dashboard view" string in Analytics Settings (view and edit) should be updated to "Dashboard View".

## Implementation Brief

* The `"Dashboard view"` translation string should be updated throughout the app to `"Dashboard View"`
* Merge #7012. (PR is ready, this issue was easy to fix during IB and can be moved directly to CR.)

### Test Coverage

* No new tests needed; existing tests should pass.
* VRTs will likely require updating.

## QA Brief

* Set up Site Kit with both a UA and GA4 Analytics account
* View the Analytics Setting with the GA4 Reporting feature flag enabled.
* Note that the "Dashboard View" string should be capitalised, not with a lowercase "v" in "view".

## Changelog entry

* N/A

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Tested when 'ga4Reporting' feature flag enabled and both UA and GA4 are connected.
- Verified The "Dashboard view" string in Analytics Settings (view and edit) updated to "Dashboard View".

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/8e7e0e14-e2a9-4c19-afe7-aae3bd8afda8)

![image](https://github.com/google/site-kit-wp/assets/94359491/5e903ce0-ebd7-454a-b3ca-419c44c8efd8)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
