### ISSUE TITLE
The `googlesitekit_allow_tracking_disabled` hook in Tag Manager should be added with `add_filter` rather than `add_action`.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6937]
## Feature Description

Although it still works, this `add_action` call should in fact be `add_filter` as that would be more semantically correct.

https://github.com/google/site-kit-wp/blob/dfb3bcbb7d773c6a90dc6b49890a340cf029def9/includes/Modules/Tag_Manager.php#L102

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The highlighted call to `add_action` should be replaced by `add_filter`.

## Implementation Brief

* Replace the `add_action` highlighted in the Feature Description with `add_filter`.

### Test Coverage

* No new tests needed.

## QA Brief

* No QA is needed, once PR is approved and merged we can consider changes as `QA:eng`-ed.

## Changelog entry

* Update `googlesitekit_allow_tracking_disabled` hook call to use `add_filter` instead of `add_action`.

**Comment by tofumatt** [comment]
Moving directly to approval as QA here is part of CR and trivial; tests are still passing for this hook and it still worked in my testing 🙂
