### ISSUE TITLE
Remove "close" hover for X in callout tour

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6943]
## Description

Remove "close" that displays when hovering on "X" in callout tour:

![image](https://user-images.githubusercontent.com/12189958/233398458-40af5572-603c-42d6-9694-37e3e08ddcb4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In any feature tour, when selecting/hovering the "X" button, the "Close" text "tooltip" should not be displayed.
  * The "Close" text should still be visible to any screenreader/assistive technology so they know what this button does.

## Implementation Brief

* In `assets/js/googlesitekit/components-gm2/Button.js` 
  * Introduce new prop, say `hideTitle` which will be a boolean. This prop will control whether or not the tooltip title is displayed.
  * In [the check](https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/assets/js/googlesitekit/components-gm2/Button.js#L117), update the logic for selecting the `tooltipTitle` value to account for the `hideTitle` prop. If `hideTitle` is true, the tooltip title should not be displayed
* `assets/js/components/TourTooltip.js`
  * In the [close button](https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/assets/js/components/TourTooltip.js#L98) add `hideTitle` prop

### Test Coverage

* No test update needed

## QA Brief

* Verify that the "Close" tooltip is not displayed when hovering on the "X" button in any feature tour.
* This can be tested by dismissing the Key Metrics setup CTA.
* Ensure that the tooltip is still visible to other places (which already have it), such as the one in the Search Bar and its close button.

## Changelog entry

* Remove tooltip for the feature tour callout's Close button.

**Comment by marrrmarrr** [comment]
@jimmymadon indeed I think this is one for Sigal, but I don't think this should be blocking in any way, I'd suggest finishing this issue as-is and opening up a new one to think through the colour changes when tabbing through the keyboard. 

@bethanylang looks like Sigal is not on GH (or at least I don't find her username), so maybe we can raise this in Slack instead?

**Comment by techanvil** [comment]
Tagging https://github.com/google/site-kit-wp/issues/6926 which will relate to the new issue when it's raised (or could be repurposed for it).

**Comment by tofumatt** [comment]
ACs here are good 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `Close` tooltip is not displayed when hovering on the `X` button in a feature tour.
- I tested this on a few different tours. The behavior was the same on all of them; the tooltip for close is removed. 
- The tooltip is still visible in other places, such as the one in the Search Bar and its close button.

<details>
 <summary>Screencast</summary>

https://github.com/google/site-kit-wp/assets/73545194/8904682e-2b8c-45c6-95f3-46fed33dbf97

![image](https://github.com/google/site-kit-wp/assets/73545194/1a6198c8-49c4-4f75-88c4-ba61baf09c06)

</details>
