### ISSUE TITLE
Console error on view only dashboard when GA4 is in gathering state

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6944]
## Bug Description

As reported by @aaemnnosttv in Bug Bash:

GA4 determines its gathering state based on data from the property itself (i.e. creation date) when it isn't already known to be in a non-gathering state.

![image](https://user-images.githubusercontent.com/12189958/233398974-a3d48648-90ea-4805-957a-0068141eba5e.png)

https://github.com/google/site-kit-wp/blob/a3fa8f3dd0e23c49b34e7ed64b11441637e27a3e/assets/js/modules/analytics-4/datastore/report.js#L133-L140

This won't work in a view-only context which doesn't have access to module settings (propertyID) and also the request that fulfills getProperty is not shareable, so it is bound to fail as well (it just fails before it reaches this point).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kuasha420** [comment]
This can be closed as the fix for this and #6897 are the same and the later is already defined. cc @aaemnnosttv @bethanylang

**Comment by tofumatt** [comment]
It's also possibly related to #6830, since that selector should probably check for these things and not call selectors that shouldn't be called 🤔

**Comment by bethanylang** [comment]
Closing as this will be fixed in #6897.

**Comment by aaemnnosttv** [comment]
> It's also possibly related to #6830, since that selector should probably check for these things and not call selectors that shouldn't be called 🤔

@tofumatt unless that new selector didn't rely on the same settings and endpoints internally then it would still raise the same error in a view-only context.
