### ISSUE TITLE
Change content of Top Earnings Pages widget and all other widgets of this type to be full-width with limited width text

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6945]
## Description

From @aaemnnosttv:

Basically there is somewhat of an inconsistency with the design and what the component would look like on a full-width desktop window. The notice has a limited width for readability, just as it does in settings which is actually very close to the width used in the design.

![image](https://user-images.githubusercontent.com/12189958/233400160-ec4def9f-b1a7-48e5-ae22-51e166e6c9ab.png)

![image](https://user-images.githubusercontent.com/12189958/233400190-584adabb-60ad-4d3b-9f3a-5256f5fd30bd.png)

![image](https://user-images.githubusercontent.com/12189958/233400208-8b74db9b-335c-451e-adb9-cbed5dee5b97.png)

From Sigal:

Considering the alternatives I would go with full width notifications and a CTA to the right as it is currently in the design (while the text itself can have a limited width).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any component using `.googlesitekit-settings-notice` class should span the full width of the container its in, and should be span the width of the full page on a large screen, instead of having a [maximum width of `1098px`](https://github.com/google/site-kit-wp/blob/6d5ae3ec6761c021bf5823e99a1d5123ee3dface/assets/sass/components/settings/_googlesitekit-settings-notice.scss#L28)
  * The _contents_/text of the notice should have a maximum width (of `1098px`, or probably even a bit less) to keep the contents of the notice readable, but the "action"/CTA button inside the component should still be right-aligned as in the design.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
> * Any component using `.googlesitekit-settings-notice` class should span the full width of the container its in, and should be span the width of the full page on a large screen, instead of having a [maximum width of `1098px`](https://github.com/google/site-kit-wp/blob/6d5ae3ec6761c021bf5823e99a1d5123ee3dface/assets/sass/components/settings/_googlesitekit-settings-notice.scss#L28)

@tofumatt I think we want to keep this change limited to use on the dashboards, so that it doesn't affect the existing placements in settings.

**Comment by bethanylang** [comment]
Closing as we've decided to make #6956 a high-priority "nice to have," so that would encompass these changes, as well.
