### ISSUE TITLE
Add `ad-blocking-recovery` screen and load it with placeholder content

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6946]
## Feature Description

The Ad Blocking Recovery on boarding will take place in a separate (hidden) page. This issue is about adding the necessary infrastructure (ie. `Screen`, JS assets etc) for the page. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following points in the AC should be implemented to they are only accessible when the `adBlockerDetection` feature flag is enabled.
* A new `Screen` should be created for the Ad Blocking Recovery setup that is only accessible directly, not via the WordPress menu like the Site Kit Dashboard or Site Kit Settings.
* A new JS entrypoint for this screen should be created (eg. `googlesitekit-ad-blocking-recovery`)
  * This screen should load/enqueue the JS entrypoint created above
  * The JS entrypoint should be scaffolded with JS code that will render a component, similar to https://github.com/google/site-kit-wp/blob/0d009991b2f5be3d2f63fe9c004aedf9918746fe/assets/js/googlesitekit-user-input.js#L33
* A new component named `AdBlockingRecoveryApp` should be created and used as the component to render in the entrypoint above. It can contain a simple placeholder for now as it will be implemented in other issues.

## Implementation Brief

* Create a new `Screen` in `/includes/Core/Admin/Screens.php` named `ad-blocking-recovery`, only when the `adBlockerDetection` feature flag is enabled.
  * It should be similar to the `user-input` screen in setup and creation (eg. behind a feature flag) https://github.com/google/site-kit-wp/blob/b5177d3f1c1b486dc695a61ed26a9a7ea8ea4b8f/includes/Core/Admin/Screens.php#L490, eg:

```php
if ( Feature_Flags::enabled( 'adBlockerDetection' ) ) {
	$screens[] = new Screen(
		self::PREFIX . 'ad-blocking-recovery',
		array(
			'title'            => __( 'Ad Blocking Recovery', 'google-site-kit' ),
			'capability'       => Permissions::MANAGE_OPTIONS,
			'parent_slug'      => null,
			'enqueue_callback' => function( Assets $assets ) {
				$assets->enqueue_asset( 'googlesitekit-ad-blocking-recovery' );
			},
			'render_callback'  => function( Context $context ) {
				?>

				<div id="js-googlesitekit-ad-blocking-recovery" class="googlesitekit-page"></div>

				<?php
			},

		)
	);
}
```

* Create a new JS entrypoint at `assets/js/googlesitekit-ad-blocking-recovery.js` with code similar to `assets/js/googlesitekit-user-input.js`. It should render an `AdBlockingRecoveryApp` as outlined below.
* Create a new component in the AdSense module: `AdBlockingRecoveryApp` in `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp`
  * I figured placing this in `settings` was fine since it's arguably configuring AdSense settings. It's a bit odd as we haven't had this type of flow yet in Site Kit, but I think it's fine.
  * `AdBlockingRecoveryApp` can render basic placeholder contents for now, eg:

```js
<Fragment>
	<Header>
		<HelpMenu />
	</Header>
	<div className="googlesitekit-ad-blocking-recovery">Ad Blocking Recovery</div>
</Fragment>
```

### Test Coverage

* No new tests needed

## QA Brief

* Set up a new site and enable the `adBlockerDetection` feature flag.
* Go to the `/wp-admin/admin.php?page=googlesitekit-ad-blocking-recovery` page and ensure that you see the `Ad Blocking Recovery` text.

## Changelog entry

* Scaffold new screen for ad blocking recovery set up.

**Comment by eugene-manuilov** [comment]
IB ✔️

@tofumatt why is it `15`? Feels like `7` should be more than enough for this task, no?

**Comment by tofumatt** [comment]
@eugene-manuilov Oops, I totally selected the wrong estimate. 7 might be a bit low but I meant to select 11. Adjusted 😄

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested after enabling `'adBlockerDetection'` feature flag.
- Verified that user able to access   /wp-admin/admin.php?page=googlesitekit-ad-blocking-recovery page and see the Ad Blocking Recovery text.
- Verified A new Screen  created for the Ad Blocking Recovery setup that is only accessible directly, not via the WordPress menu like the Site Kit Dashboard or Site Kit Settings.
- Verified that a new component named `AdBlockingRecoveryApp` is created.
- Verified a new JS entry point for this screen created i.e `googlesitekit-ad-blocking-recovery` .



<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/bfe37ec9-d5b8-43f7-a1ff-c83cf8a04dfe)

![image](https://github.com/google/site-kit-wp/assets/94359491/8bfff37b-bd34-4361-9980-4c01434e7d4d)

![image](https://github.com/google/site-kit-wp/assets/94359491/87199d41-c573-4862-9063-a2c90ca8fa35)

</details>

**Comment by aaemnnosttv** [comment]
LGTM 👍
