### ISSUE TITLE
Display Ad Blocking Recovery Notification in the dashboard when all the conditions are met

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6953]
## Feature Description

The Ad Blocking Recovery notification component (being developed in #6929) should be placed in the **Monetization** section of the Main Site Kit dashboard using the Widgets API similar to the AdSense Setup CTA. This will only be visible when the 3 weeks after the user had a fully `ready` AdSense setup. Once dismissed, there should be a tooltip informing the user that they can setup the feature from the Settings and point them to the Settings menu of Site Kit. 

See the [relevant section](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#heading=h.z4sdrj6ojzw8) on the design doc for more details on it. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Ad Blocking Recovery is not set up, the Ad Blocking Recovery Main Notification should be displayed in the `Monetization` section of the main Site Kit Dashboard.
    * This should be the first widget in the section.
    * This should only be displayed on a `ready` site (both account and site status ready).
    * This should only be displayed 3 weeks after the AdSense setup was fully completed.
        * This requirement should be skipped for existing sites that doesn't have this "completion time" information. ie. should be displayed right away if all the other conditions are met. 
* Once the notification has been dismissed, a tooltip should point to the Settings menu of site kit, as seen in the [Figma](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?type=design&node-id=20-3376&t=KvvvOYK38pD63mgb-0) design. 
    * The copy and design should follow the design. 

## Implementation Brief

* Rename the `AdBlockerRecoveryWidget` component in the `assets/js/modules/adsense/components/dashboard/AdBlockerRecoveryWidget.js` file to be `AdBlockingRecoveryWidget`. 
    * Find all cases where the term "ad blocker recovery" being used and update them to read "ad blocking recovery".
    * This includes both code and filenames.
* In the `AdBlockerRecoveryWidget` component:
    * Get the adsense `setupCompletedTimestamp` using the `getSetupCompletedTimestamp` selector of `adsense` data store.
    * Get the `adBlockingRecoverySetupStatus` using the `getAdBlockingRecoverySetupStatus` selector of `adsense` data store.
    * Get whether the ad blocking recovery tooltip is visible using the `useTooltipState` hook.
    * Get the module connection status, account status and site status using the `isModuleConnected`, `getAccountStatus` and `getSiteStatus`. 
    * Update the condition that returns `WidgetNull` to return it with or without the admin menu tooltip (see sub-point below) if AdSense module is not connected or account/site status is not `ready` or `setupCompletedTimestamp` is less than 3 weeks in the past in addition to the existing dismissal check. https://github.com/google/site-kit-wp/blob/b4abae2fd85ff81d4cdbb20f02d210d93b6f783f/assets/js/modules/adsense/components/dashboard/AdBlockerRecoveryWidget.js#L66-L68
        * If the widget is dismissed but the ad blocking recovery tooltip is visible (it should be made visible using the `useShowTooltip` hook), render  `Fragment` that includes the `WidgetNull` element and a `AdminMenuTooltip` element with the `title`, `content` and `dismissLabel` as defined in the AC/Figma design. 
            * `onDismiss` should dismiss the tooltip using `dismissItem` action from `CORE_USER` store.

### Test Coverage

* Add VRT image and story for the widget where either the Notification or the tooltip shows up. See the story for `AdSenseConnectCTAWidget` for inspiration. 

## QA Brief

* Ensure the Ad Blocking Recovery Widget is displayed if the following conditions are met:
    * The `adBlockerDetection` feature flag is enabled AND
    * Not view-only dashboard AND
    * AdSense module is connected AND
    * The notification is not dismissed AND
    * Ad Blocking Recovery status is not empty AND
    * AdSense account status is `ready` AND
    * AdSense site status is `ready` AND
    * AdSense setup was completed more than 3 weeks ago OR for the existing sites that don't have this "completion time" information.
* To simulate the above conditions, you can use the following code snippet in the browser console:
    ```js
    googlesitekit.data.dispatch('modules/adsense').setAdBlockingRecoverySetupStatus('setup-confirmed')
    googlesitekit.data.dispatch('modules/adsense').setAccountStatus('ready')
    googlesitekit.data.dispatch('modules/adsense').setSiteStatus('ready')
    googlesitekit.data.dispatch('modules/adsense').saveSettings()
    ```
* To simulate the 3 weeks completion time, you can run the following action in the browser console with the UNIX timestamp of 3 weeks ago:
    ```js
    googlesitekit.data.dispatch('modules/adsense').setSetupCompletedTimestamp(1684145866)
    ```
* Ensure by clicking the `Maybe later` button, the widget is dismissed, and the tooltip is displayed.
* Once the widget is dismissed, it should not be displayed again.
* It can be displayed again by deleting the `wp_googlesitekitpersistent_dismissed_items` item from the `wp_usermeta` table in the database.
* Ensure the widget is not displayed in the view-only dashboard.

## Changelog entry

* Show the Ad Blocking Recovery Notification on the Dashboard.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by techanvil** [comment]
IB Update: :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 


Tested on dev environment.
Verified the Ad Blocking Recovery Widget is displayed if the following conditions are met:

 - - The adBlockerDetection feature flag is enabled AND
 - -  Not view-only dashboard AND
 - - AdSense module is connected AND
 - - The notification is not dismissed AND
 - - Ad Blocking Recovery status is not empty AND
 - -  AdSense account status is ready AND
 - -  AdSense site status is ready AND
 - -  AdSense setup was completed more than 3 weeks ago OR for the existing sites that don't have this "completion time" 
    information.

- Verified by clicking the Maybe later button, the widget is dismissed, and the tooltip is displayed.
- Once the widget is dismissed, it not display again.
- It can be display again by deleting the wp_googlesitekitpersistent_dismissed_items item from the wp_usermeta table in the database.
- Verified the widget is not displayed in the view-only dashboard.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e34de429-0822-42ac-8cfe-9e07d6efe3d5)

![image](https://github.com/google/site-kit-wp/assets/94359491/fa6fb9d7-b38d-45fa-9d13-b6c6db90a58a)


</details>

**Comment by kuasha420** [comment]
# Approval :x: 

We should use `getReferenceDate()` instead of `Date.now()` when calculating the three week [here](https://github.com/google/site-kit-wp/blob/5e499765b5e207328265d07752c159697f95146f/assets/js/modules/adsense/components/dashboard/AdBlockingRecoveryWidget.js#L132), so it can be overridden in testing. 

cc @wpdarren @aaemnnosttv

**Comment by hussain-t** [comment]
Thanks @kuasha420. To fix it, I created a follow-up [PR](https://github.com/google/site-kit-wp/pull/7216).

**Comment by mohitwp** [comment]
### QA Update ✅ 


Tested on main environment.
Verified the Ad Blocking Recovery Widget is displayed if the following conditions are met:

 - - The adBlockerDetection feature flag is enabled AND
 - -  Not view-only dashboard AND
 - - AdSense module is connected AND
 - - The notification is not dismissed AND
 - - Ad Blocking Recovery status is not empty AND
 - -  AdSense account status is ready AND
 - -  AdSense site status is ready AND
 - -  AdSense setup was completed more than 3 weeks ago OR for the existing sites that don't have this "completion time" 
    information.

- Verified by clicking the Maybe later button, the widget is dismissed, and the tooltip is displayed.
- Once the widget is dismissed, it not display again.
- It can be display again by deleting the wp_googlesitekitpersistent_dismissed_items item from the wp_usermeta table in the database.
- Verified the widget is not displayed in the view-only dashboard.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e34de429-0822-42ac-8cfe-9e07d6efe3d5)

![image](https://github.com/google/site-kit-wp/assets/94359491/fa6fb9d7-b38d-45fa-9d13-b6c6db90a58a)


</details>
