### ISSUE TITLE
Add "learn more" link to second slide of GA4 Reporting feature tour

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6955]
## Description

Add a "Learn more" link to the second slide of the GA4 dashboard feature tour:

![image](https://user-images.githubusercontent.com/12189958/233696066-3b920f06-d58d-42c5-8256-429aa71fa58b.png)

The link should match the look and feel of the Learn more links on the other tooltip tour slides, and should go to https://support.google.com/analytics/answer/9191807.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- In the GA4 Reporting feature tour, a "Learn more" link should be added to the tour step for "Sessions", similar to the other steps.
- The "Learn more" link should open https://support.google.com/analytics/answer/9191807 in a new tab.

## Implementation Brief

- In `assets/js/feature-tours/ga4-reporting.js`:
  - Update the second array item about Analytics Sessions of the `steps` array property of the `ga4Reporting` object:
    - Update the `content` property to have a `Learn more` `<SupportLink />` component similar to the other steps, but linking to `/analytics/answer/9191807`.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Set up the plugin and connect sign in using your existing account.
* Connect the Analytics module and select the GA4 dashboard view.
* Go to the dashboard page and ensure that you see the GA4 reporting feature tour.
* Go to the second step and verify that it contains the new "Learn More" link with the correct URL as mentioned in AC.
  * If the feature tour doesn't appear, you may need to reset the feature tour cooldown by cleaning up the session storage in your browser.

## Changelog entry

* Add "learn more" link to the Sessions slide of the GA4 Reporting feature tour.

**Comment by nfmohit** [comment]
### Note to AC Reviewer:

While writing the ACs, I also added the IB to it just to try and move quicker. Thanks!

**Comment by eugene-manuilov** [comment]
AC and IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

Tested on main.
Verified 'Learn more' link added to the second slide of GA4 reporting feature tour.
Clicking on 'Learn more ' link open https://support.google.com/analytics/answer/9191807?hl=en in a new tab.

![image](https://user-images.githubusercontent.com/94359491/235143943-b91c67c8-fc2f-4fbe-861e-a01a151ec9eb.png)

**Comment by aaemnnosttv** [comment]
LGTM 👍
