### ISSUE TITLE
Introduce Ad Blocker Detection related settings in AdSense module

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6960]
## Feature Description

To support various aspects of Ad Blocker Detection, a few additional settings needs to be stored as part of AdSense module settings. Namely, the toggle for Ad Blocking Recovery tags, setup state, tag availability etc. See the [relevant section](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#heading=h.vpcg8d5cjhhe) of the design doc for more information. 

Th additional settings should be stored as part of AdSense module settings when the `adBlockerDetection` feature flag is enabled. These should be exposed in the respective data store as well.

Note that this issue is only about adding the settings in PHP code and JS datastore, the Settings UI will be updated in follow up issues.  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AdSense Settings in PHP should be extended with the following settings:
  * `useAdBlockerDetectionSnippet` (`boolean` that is `false` by default)
  * `useAdBlockerDetectionErrorSnippet` (`boolean` that is `false` by default)
  * `adBlockingRecoverySetupStatus` (`string` that is `''` (empty) by default, but can be one of the steps: `'tag-placed'`, `'setup-confirmed'`)
* These settings should be available in JS AdSense settings.
* These settings should only be added/stored when the `adBlockerDetection` feature flag is enabled, unless that proves excessively complex, given exposing the settings themselves in code isn't a big deal.

### PHP Changes

In the `AdSense\Settings` class, update the `get_default()` method to include the following new settings only when the `adBlockerDetection` feature flag is enabled:

* `useAdBlockerDetectionSnippet` (boolean, set to `false` by default).
* `useAdBlockerDetectionErrorSnippet` (boolean, set to `false` by default).
* `adBlockingRecoverySetupStatus` (string, set to an empty string `''` by default).

Update the `get_sanitize_callback()` method to include proper sanitization for the new settings only when the `adBlockerDetection` feature flag is enabled:

* Cast `useAdBlockerDetectionSnippet` and `useAdBlockerDetectionErrorSnippet` to boolean values.
* Sanitize `adBlockingRecoverySetupStatus` by ensuring it is one of the allowed values (`'tag-placed'`, `'setup-confirmed'`).

### JS Changes

In `assets/js/modules/adsense/datastore/base.js`:

* Add `useAdBlockerDetectionSnippet`, `useAdBlockerDetectionErrorSnippet` and `adBlockingRecoverySetupStatus` to the `baseModuleStore.settingSlugs` object.

### Test Coverage

* Add the new settings options to the `test_get_default()` method in `tests/phpunit/integration/Modules/AdSense/SettingsTest.php`.

### QA:Eng

- Enable the `adBlockerDetection` feature flag.
- Using the Redux developer tools, verify that the `settings` object in the `modules/adsense` store state includes the settings mentioned in the ACs, with their respective default values.
- Verify that they no longer exist with the `adBlockerDetection` feature flag disabled.
- Test the sanitization of the added settings by dispatching `set*` actions from the `modules/adsense` datastore. Verify that running `modules/adsense` `saveSettings()` action with invalid values for the added settings doesn't let you update them.

## Changelog entry

* Add the new settings for Ad Blocker Detection to the AdSense module.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
## QA :white_check_mark: 

### QA:Eng:

- Verified the Ad Blocker Detection settings are present in AdSense settings (note, this is no longer feature-flag dependant since #7050):

![image](https://github.com/google/site-kit-wp/assets/18395600/e757f0e4-6c94-433f-bbb8-8fb012a8d797)

- Verified the sanitization of the settings via the setter/save actions:

![image](https://github.com/google/site-kit-wp/assets/18395600/b9c214a2-76f5-4873-9648-9f652498934f)

![image](https://github.com/google/site-kit-wp/assets/18395600/0e8603aa-ee0c-4192-967d-8d2cb9d186e6)

![image](https://github.com/google/site-kit-wp/assets/18395600/22fad3f4-c59c-4e3e-926e-5d0232784aba)
