### ISSUE TITLE
Place Ad blocking recovery and Error protection tag in the website based on settings

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6963]
## Feature Description

The Ad blocking recovery and error protection tag should be placed on the front end of the website once the feature is setup and the respective setting toggles are turned on. See the ["Placing the tags" section of the design doc](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#heading=h.ltsdrmmcirt7) for more context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Using the tag data stored in #6902, the AdSense module should output the AdSense Recovery tag HTML and the Error Recovery HTML tag on the WordPress frontend, if they are available (eg. the tags are not `null` or empty string) AND the relevant AdSense settings are enabled:
  * The settings created in #6962 should be checked to see if the AdSense recovery tag should be output.
  * The settings created in #6962 should be checked to see if the AdSense error recovery tag should be output.
  * This tag should be output on the "frontend" of any WordPress page that outputs the AdSense tag. If the AdSense tag itself is not output by Site Kit, we should not output either of the Ad Blocker Detection tags.
  * If any setting is disabled, do not show that tag.
  * If Site Kit is not outputting an AdSense tag, both Ad Blocker Detection tags should NOT be output
  * If Site Kit is not outputting an AdSense Recovery tag, the Error Recovery tag should NOT be output

## Implementation Brief

Seeing as the ABD tags will only be inserted when the current AdSense tag is being included, and we're [not trying to target AMP with this first release](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#bookmark=id.2xuv1bkf49ud), we can take the approach of outputting the ABD tags from the existing AdSense `Web_Tag` class.

Within `includes/Modules/AdSense/Web_Tag.php`:

- Add instance variables and setter methods for the following fields:
  - `useAdBlockerDetectionSnippet`
  - `useAdBlockerDetectionErrorSnippet`
  - `recoveryTagHTML`
  - `errorProtectionHTML`
- In the `render()` method, if `useAdBlockerDetectionSnippet` is true:
  - Print `recoveryTagHTML`, similarly to how the current tag is printed.
  - Check if `useAdBlockerDetectionErrorSnippet` is true and if so, print `errorProtectionHTML`.

Within `includes/Modules/AdSense.php`:

- Before registering the Web Tag, set the above fields with the appropriate values from the AdSense module and its settings objects (`Settings`, `Ad_Blocking_Recovery_Tag`)
  - AdSense settings:
    - `useAdBlockerDetectionSnippet`
    - `useAdBlockerDetectionErrorSnippet`

### Test Coverage

- Add coverage for these changes to the PHPUnit tests for the AdSense module.

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Pulling this back for potential revision in light of feedback on the initial infrastructure in https://github.com/google/site-kit-wp/issues/6902#issuecomment-1581261051

**Comment by kuasha420** [comment]
@aaemnnosttv I think we can keep this one moving and address the changes in the follow up issue. It should be an easy change and there's no need to hold this one up. 

I've filled the [follow up issue](https://github.com/google/site-kit-wp/issues/7156) and added the context. Let me know what you think. 

Cheers.

**Comment by kuasha420** [comment]
Closing in favor of #7186. cc @nfmohit @bethanylang @aaemnnosttv
