### ISSUE TITLE
Remove `adBlockerDetection` feature flag and unused code

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6969]
## Feature Description

Once the the Ad blocking recovery has been rolled out to 100% of Site Kit users, the `adBlockerDetection` feature flag should be removed from the code base and its usage refactored.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The usage of `adBlockerDetection` feature flag in PHP and JS code should be refactored to not use the feature flag, assuming the feature is always enabled. 
* Any unused code that results from the refactor should be removed from the codebase since they will no longer be relevant (ie. code that only runs when the feature is disabled).
* The `adBlockerDetection` feature flag should be removed from the plugin. 

## Implementation Brief
* Remove the `adBlockerDetection` feature flag from `feature-flags.json`.
* Remove the usage `adBlockerDetection` feature flag in the following files and refactor the related logic to treat the feature as always enabled. In most cases, the feature flag is used as a guard to run some code or render components, so removing the guard is sufficient. Additional details are added whenever necessary. 
    * `assets/js/components/notifications/BannerNotifications.js`
    * `assets/js/modules/adsense/index.js`
    * `assets/js/modules/adsense/components/settings/SettingsForm.js`
    * `assets/js/modules/adsense/components/settings/SettingsView.js`
    * `includes/Core/Admin/Screens.php`
        * Register the `ad-blocking-recovery` screen unconditionally.
    * `includes/Modules/AdSense.php`
        * In `get_debug_fields` method, merge the debug fields with return.
        * In `register_tag` method, register the ABR related stuff in non-amp context.  
    * `includes/Modules/AdSense/Settings.php`
    * `stories/module-adsense-settings.stories.js`
    * `tests/e2e/specs/wp-admin/screens.test.js`
    * `tests/phpunit/integration/Modules/AdSenseTest.php`
        * Merge the test fields from `test_get_debug_fields__adBlockerDetection` into the `test_get_debug_fields` test and remove the `test_get_debug_fields__adBlockerDetection` test. 
* Remove any unused imports (ie. `useFeature`).

### Test Coverage

* All tests should continue to pass.

## QA Brief

* Verify that there's no `adBlockerDetection` feature flag in the Tester plugin.
* Perform a general smoke test of the plugin.
* Smoke test the Ad Blocking Recovery feature - refer to the [Bug Bash](https://app.asana.com/0/1204478087069244/1204478029951044) instructions, although it's not necessarily required to run through it in full.

## Changelog entry

* Remove `adBlockerDetection` feature flag and unused code.

**Comment by tofumatt** [comment]
I don't think this feature flag affects any E2E tests so this is actually a safe estimate for a feature flag removal issue 😆 

IB ✅

**Comment by smamun19** [comment]
I have created a pr #7500 that addresses this issue. I'd appreciate it if you could take some time to review it.
Thanks!

**Comment by aaemnnosttv** [comment]
Thanks @smamun19 !

**Comment by bethanylang** [comment]
Moved to CR per discussion with @aaemnnosttv. Will plan to review in our next sprint, beginning Monday, September 11.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `adBlockerDetectio`n feature flag no longer appears in the tester plugin.
- Smoke tested the Ad Blocking Recovery feature:
   - Made sure that the CTA appears on Dashboard
   - Made sure CTA appeared in Site Kit AdSense settings
   - Set up ABR and made sure all screens appeared. 
   - Set up message and completed the setup 
   - Checked that in AdSense settings the settings appeared in view and edit. 
   - Checked source code to make sure that the snippets appeared
   - Tested AdSense settings toggles to enable and disable the appropriate tags

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/f03bd3b1-e92c-424a-9d64-5a01c75759c1)
![image](https://github.com/google/site-kit-wp/assets/73545194/7f063c43-1866-43e4-936d-5d2b9561d6df)
![image](https://github.com/google/site-kit-wp/assets/73545194/edb26dd7-dff4-46e3-a561-4625b24e3f09)
![image](https://github.com/google/site-kit-wp/assets/73545194/5938db71-14db-42a2-9f0e-e9f6fbc649dc)
![image](https://github.com/google/site-kit-wp/assets/73545194/d223f86f-80fe-4490-bb3f-b148e23df797)
![image](https://github.com/google/site-kit-wp/assets/73545194/f1847dde-d625-4c02-a686-5d3c5f848978)
![image](https://github.com/google/site-kit-wp/assets/73545194/ec5a9674-11f8-4f05-9e8a-94347cb08ec5)
![image](https://github.com/google/site-kit-wp/assets/73545194/48dbd7f1-e612-491f-a938-337a2a2f33bb)

</details>
