### ISSUE TITLE
Duplicate URLs on Site Kit widget on WP Dashboard.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6972]
## Bug Description

Duplicate URLs are showing under Site Kit widget on WP Dashboard when the dashboard view is 'UA'. This issue is existing on latest environment and also occur when GA4 reporting feature flag is not enabled.

## Steps to reproduce

1. Set up Site kit and do not enable GA4 reporting feature flag.
2. Go to WP Dashboard.
3. Note that duplicate URLs/entries appear in the WP Dashboard widget.

## Screenshots

Duplicate URLs on Site Kit widget on WP Dashboard.

![image](https://user-images.githubusercontent.com/94359491/234025632-3a8cd1d0-501a-48b3-83da-1017cea939eb.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the GA4 Reporting feature flag is not enabled, entries on the Site Kit widget that appears on the WP Admin Dashboard should not contain duplicate entries/URLs. Each entry should be unique.

## Implementation Brief

* Remove the `compare: true` param of the `getDateRangeDates` selector in the  `assets/js/components/wp-dashboard/WPDashboardPopularPages.js` file.
* Remove `compareStartDate` and `compareEndDate` in options for the popular pages report request in the `assets/js/components/wp-dashboard/common.stories.js` file.
* Add stories for the `WPDashboardPopularPages` component similarly as it is done for the `WPDashboardSessionDuration` component.
* Merge #6975

### Test Coverage

* N/A

## QA Brief

* Set up the plugin and select the UA dashboard view.
* Go to the WordPress dashboard.
* Verify that you don't see duplicate URLs in the popular pages widget.

## Changelog entry

* Fix duplicate URLs in UA popular pages list within WP dashboard widget.

**Comment by aaemnnosttv** [comment]
IB ✅ 

Moving to CR 👍

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

Tested on dev. 
Verified WP dashboard site kit widget when dashboard view is UA and 'ga4Reporting' feature flag is not enabled. 

@eugene-manuilov I've noticed that 1–4 posts have same title but if we notice URL then we can see 2 posts are amp pages. Just wants to confirm we will get separate listing of post amp page, and it is not considered as duplicate, correct ?

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @eugene-manuilov. 

- Tested on dev. 
- Verified WP dashboard site kit widget when dashboard view is UA and 'ga4Reporting' feature flag is not enabled. 

<details>

![image](https://user-images.githubusercontent.com/94359491/234876350-f129826e-459f-441d-a0cd-3a662aad14be.png)

</details>
