### ISSUE TITLE
Plugin creating long URLs and page errors

### ISSUE THREAD

**Issue by User2617** [google/site-kit-wp#6976]
## Steps to reproduce

1. Download and activate SiteKit 
2. Click on website url 
3. Click on one of the pages in the menu
4. Link leads to a page error #404, link appears https://website.fr/home/page2/?_ga=2.61445676.1057858474.1682348644-463742050.1682348644&_gl=1*1v63ixj*_ga*NDYzNzQyMDUwLjE2ODIzNDg2NDQ.*_ga_5YPEZ7J2JW*MTY4MjQxMTk3Ni40LjEuMTY4MjQxMTk4MC4wLjAuMA..
Before downloading and activating the plugin : page works and after desactivating : page works.
Important to notice : error doesn't occur with all the pages in the menu, just only some.
Other bug :
1. Download and activate SiteKit 
2. Click on website url 
3. Click on one of the pages in the menu
4. Scroll down in the page that appears, 
5. Link leads to a page error #404, link appears https://website.fr/home/page2/?_ga=2.61445676.1057858474.1682348644-463742050.1682348644&_gl=1*1v63ixj*_ga*NDYzNzQyMDUwLjE2ODIzNDg2NDQ.*_ga_5YPEZ7J2JW*MTY4MjQxMTk3Ni40LjEuMTY4MjQxMTk4MC4wLjAuMA..
Before downloading and activating the plugin : page works and after desactivating : page works.
## Additional Context

 - Browser: [chrome]
 - Plugin Version: [Tried 1.96.0 1.98.0 and 1.99.0]
 - Device: [Computer]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
@User2617 We don't provide support via GitHub but we'd be happy to help you with this issue via our Site Kit support forum. Please could you open a support topic [here](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) and we will continue to troubleshoot this issue for you.

Thanks.
