### ISSUE TITLE
Cannot sign in to verify rc1

### ISSUE THREAD

**Issue by Jack-ongithub** [google/site-kit-wp#698]
## Bug Description

After updating plugin, cannot verify or get new API key. 
## Steps to reproduce

1. Update the plugin
2. Get banners indicating that it has to be re-verified.
3. Click on banner link.
4. Taken to screen asking to log in with Google account.  Select account
5. Next screen says that Google login has not been enabled for this program.
6. Revert the update of the plugin. 

## Additional Context

 - PHP Version: 7.1.14 
 - OS: Win7 Pro
 - Browser Chrome Portable
 - Plugin Version version 1.0.0-beta.1.0.8 installed. Update to 1.0.0-rc.1. 
 - Device: desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
Thanks for your report @Jack-ongithub ! This sounds similar to #697. Please follow that issue for updates.
