### ISSUE TITLE
Uncaught Type Error in JavaScript across admin

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#699]
## Bug Description

When I updated my personal site to RC1, I received this:
<img width="1368" alt="Bildschirmfoto 2019-10-23 um 20 28 06" src="https://user-images.githubusercontent.com/3531426/67423244-2db1a700-f5d4-11e9-8597-5d2ff7b081da.png">

This console error shows now on every page across the admin, and it prevents the Site Kit splash screen from showing up entirely.

Apparently, once I am on the dashboard, I don't run into this error anymore. On my development sites, where I filtered in custom OAuth credentials, I was able to bypass using the splash screen, and now I only get the error everywhere _but_ on Site Kit's screens.

I'm not sure where this is coming from, might need to dig in a bit more.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by christiaangieles** [comment]
Hello, Here to confirm this bug and provide more information. 

I did a FRESH 1RC install just not on a site that has not had SiteKit installed before, and I get the same errors. In regular Chrome or in incognito. 

![image](https://user-images.githubusercontent.com/7935694/67469225-2b8b2f00-f64c-11e9-9619-d3e20340000e.png)

**Comment by ernee** [comment]
@christiaangieles those errors are similar to the ones we're troubleshooting in #705 

Could you try the troubleshooting steps in the issue and provide an update there?

**Comment by christiaangieles** [comment]
Mine just resolved itself after waiting over the weekend. No changes where done on my side. I'm assuming some Google services were having hickups, probably due to the new auth sequence for Site Kit

**Comment by felixarntz** [comment]
This was an issue with my setup (I had removed the `?ver=...` suffixes from scripts and stylesheets at some point, which was messing up the necessary cache busting).
