### ISSUE TITLE
Remove scheduled events upon deactivation or uninstall

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6992]
## Bug Description

As suggested by a [user in the forums](https://wordpress.org/support/topic/wp-cron-googlesitekit_cron_update_remote_features-not-being-removed/), consider allowing users to remove any cron events upon via a hook, or an option to remove such events upon uninstall or deactivation. 

The cron event highlighted by the user is `googlesitekit_cron_update_remote_features`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All Site Kit cron events and schedules should be cleared on:
	* Site Kit Reset
	* Plugin deactivation
	* Plugin uninstall

## Implementation Brief

* [x] Following events need to be cleared (these are present at the time of writing, check if there are new ones during execution): 
  * `OAuth_Client::CRON_REFRESH_PROFILE_DATA`
  * `Remote_Features_Cron:CRON_ACTION`
  * `Synchronize_AdSenseLinked::CRON_SYNCHRONIZE_ADSENSE_LINKED`
  * `Synchronize_AdsLinked:CRON_SYNCHRONIZE_ADS_LINKED`
  * `Synchronize_Property:CRON_SYNCHRONIZE_PROPERTY`
* [x] Update `includes/Core/Util/Uninstallation.php`
  * In `register` method,  hook into `googlesitekit_deactivation` and `googlesitekit_reset` and remove all listed CRON events. You can use `wp_clear_scheduled_hook`. 
  * Extract the CRON cleanup logic in a new method and call it as callback in both hooks. And invoke it in the existing `googlesitekit_uninstallation` hook as well

### Test Coverage

* No updates needed

## QA Brief

1. Turn on the `conversionReporting` feature flag (as that includes one of the cron events).
2. Set up Site Kit with the Analytics, Ads, and AdSense modules.
3. Install & activate the [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) plugin.
4. Go to "_WordPress Dashboard -> Tools -> Cron Events_" and search for "_googlesitekit_".
5. You should be able to see some events from the Site Kit plugin here.
6. Now, try deactivating, deleting, or resetting Site Kit.
7. Perform step 4 again and verify that there are no Site Kit events.

## Changelog entry

* Remove scheduled events upon deactivation, reset or uninstall.

**Comment by jamesozzie** [comment]
@aaemnnosttv tagging you here for visibility.

**Comment by ivonac4** [comment]
@aaemnnosttv Are you still planning to work on this soon? If not, could you please unassign yourself so someone else can pick it up? Thank you!

**Comment by aaemnnosttv** [comment]
Closing in favor of #8988

**Comment by webd-uk** [comment]
I will comment on #8988 as well but I do not agree that this should be closed in favour of that issue.

As per [WordPress WP Cron recommendations](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/#unscheduling-tasks), tasks should be unscheduled when they are no-longer required and doing so on a deactivation hook (as recommended by WordPress) cannot have a detrimental effect because the plugin is no longer active!

Should the plugin be re-activated, the missing / required tasks will be added again by the plugin anyway.

**Comment by aaemnnosttv** [comment]
Thanks @webd-uk, I agree, this issue is still valid 👍

**Comment by eugene-manuilov** [comment]
> Update `google-site-kit.php`
> * Include `register_uninstall_hook` function,  and re-use the `googlesitekit_deactivate_plugin` as callback. You can invoke this function bellow the `register_deactivation_hook`, since uninstalling and deactivating can share the same cleanup logic.

@zutigrm it should be done in the `includes/Core/Util/Uninstallation.php` file.

> Update `Google\Site_Kit\Plugin::register`:
> * Hook into `googlesitekit_deactivation` and `googlesitekit_reset` and remove all listed CRON events.

The same here, we should do it in the `Uninstallation` class.

**Comment by zutigrm** [comment]
@eugene-manuilov Thanks! Didn't see we have that file. IB Updated

**Comment by eugene-manuilov** [comment]
Thanks. IB ✔️

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @nfmohit , when I tested for the reset scenario (regardless if it's through the SK Admin Settings or the Tools > Available Tools menu), there is still one googlesitekit event left. ⚠️ 
Is that expected?

Screenshot and video attached below.
<Details>
<img width="1181" alt="Screenshot 2024-09-12 at 13 14 57" src="https://github.com/user-attachments/assets/febfa06e-1d8f-45c9-9a50-018f73231ba0">

https://github.com/user-attachments/assets/627d254d-cd47-4c43-8ca9-93dafb6ac11e

</Details>

_____________________________________________

Other than that, deactivation and deletion scenarios are working as expected. ✅ 

<Details>

https://github.com/user-attachments/assets/ea12dc5e-1e7b-4a05-ab02-9ef91f2ca3ef



https://github.com/user-attachments/assets/dda4b6b4-0e91-42a3-9d5f-636cecf90597



</Details>

**Comment by nfmohit** [comment]
Hi @kelvinballoo. This is expected because the `googlesitekit_cron_update_remote_features` event is cleared as expected, but as the Site Kit plugin is active, it re-schedules this event again. Thanks!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks for the confirmation @nfmohit. 
This is good to be moved to approval in that case.

- Resetting, deactivation and deletion scenarios are working as expected. ✅ 

Note that for 'Reset' scenario, there will be one event left and that is expected.
<Details>
Reset (tested reset from SK admin settings and also Tools > Available Tools):

https://github.com/user-attachments/assets/5cc29296-5fda-46fa-9b4c-1ca6e0b7f72b


Deactivation:

https://github.com/user-attachments/assets/ea12dc5e-1e7b-4a05-ab02-9ef91f2ca3ef

Deletion:

https://github.com/user-attachments/assets/dda4b6b4-0e91-42a3-9d5f-636cecf90597



</Details>
