### ISSUE TITLE
Investigate usage of the `Alert` component

### ISSUE THREAD

**Issue by derweili** [google/site-kit-wp#6993]
## Feature Description

I noticed the [Alert component](https://github.com/google/site-kit-wp/blob/da42314a27e20b76a6dcf296778b47e795990de7/assets/js/components/Alert.js) seams to not being used anywhere.
There is also no kind of documentation, tests or stories for this component.

When deleting the `Alert.js` all tests (unit tests, VRT and e2e) as well as the built process complete without errors.

We should investigate if the component ist still useful or not, as we should not have unused, undocumented code in our codebase. As a result we should either add documentation or delete the component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

*  The (unused) `Alert` component should be removed along with any supporting parts (eg. styles, stories, etc) that are **only used by this component** and thus also safe to remove

## Implementation Brief

* Remove `assets/js/components/Alert.js`.
* Nothing else needs to be removed or updated, as the component is completely unused and doesn't have any specific styles. ie. in `BannerNotification`.

### Test Coverage

* N/A

## QA Brief

* Confirm there is no error, during build, tests, visiting Dashboard and Settings pages.

## Changelog entry

* N/A.

**Comment by aaemnnosttv** [comment]
Looks like it's indeed not used. This component was intended to show module notifications, but the only module which implements the endpoint (has notifications/alerts) is AdSense, which has its own component.

This component is rather old and doesn't use the datastore so it should be removed.
https://github.com/google/site-kit-wp/blob/79c8f4757a5405befd64edc41f12da51725f9233/assets/js/components/Alert.js#L57-L58

**Comment by aaemnnosttv** [comment]
@kuasha420 please add an estimate, otherwise IB LGTM.

**Comment by kuasha420** [comment]
Thank you, added the estimate. :smile_cat:

**Comment by nfmohit** [comment]
## QA:Eng ✅ 

Confirmed that the removal of the Alert component causes no errors during build, tests, and visiting Dashboard & Settings pages.
