### ISSUE TITLE
`postcss-import-url: postcss.plugin was deprecated`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6997]
## Feature Description

The following deprecation notice is currently being raised when running a build

```
postcss-import-url: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The use of postcss should be updated such that it no longer raises a deprecation notice when building

## Implementation Brief

* The notice is coming from current `postcss-import-url` package version. There was a fix added in `6.0.0`, but `^7.0.0` seems safe to use, as it has most of active downloads and additional fixes. Once this package is update, `postcss-loader` will also require an update to `^4.0.0` as in this version compatability issue were resolved, otherwise with current version builds will fail.
* So in the `package.json` update the mentioned 2 packages to:
```json
"postcss-import-url": "^7.0.0",
"postcss-loader": "^4.0.0",
```
* Do a quick check that all the built styles are still present and their @import styles as well.

### Test Coverage

* no tests needed

## QA Brief

* No qa is needed, as this change is only updating the package versions. For eng, after running the install to update packages locally, verify that build is working, as well as storybook and all tests.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Hi @zutigrm, this IB is looking good. There's just one small point - we should always fill in the **Test Coverage** section when writing an IB, even if it's just to say that there are no tests needed.

**Comment by zutigrm** [comment]
@techanvil Updated it. Sorry forgot to add it

**Comment by techanvil** [comment]
No worries, thanks @zutigrm! IB LGTM :white_check_mark:

**Comment by tofumatt** [comment]
Moving directly to Approval as no QA is needed here.

**Comment by aaemnnosttv** [comment]
LGTM! I no longer see the deprecation notice and instead see [this](https://github.com/google/site-kit-wp/actions/runs/6260361889/job/16998251527#step:5:30)
```
info => Using PostCSS preset with postcss@7.0.39
```
