### ISSUE TITLE
Single page stats: don't show 'top pages' table

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#70]
## Bug Description

The table below doesn't make sense on the single page detail page since we have already drilled down. We can remove it here.

## Screenshots

![54bd0191e11bb2be1d3fafa1aa730a81](https://user-images.githubusercontent.com/28811945/60205922-0dd1c880-9818-11e9-9001-3d49d9a303d2.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* Fix incorrect label for Top Pages table when viewing insights for a single post.

## Acceptance criteria

* Ensure the title for the Top Pages table on the overall dashboard refers to the "site".
* Ensure the title for the Top Pages table on a single post dashboard view refers to the "page".

**Comment by ivankristianto** [comment]
@lucymtc & @bjackson27 
After a second thought, I prefer to keep this but change the title to "Top search queries for your page".
Since the search queries shown here is specific to that post/page.

**Comment by felixarntz** [comment]
@marrrmarrr Can you chime in on that please?

Should we remove the box on the single page view entirely or should we just relabel it appropriately to use "Top search queries for your page" in that scenario?

**Comment by marrrmarrr** [comment]
Showing queries for which the specific page is very valuable information for users. 
@ivankristianto can you confirm these are queries scoped to the page (and not the site)? If yes, let's change the title and keep the table. 
We need to also address the case when there is not enough information for that page to show specific queries (e.g. queries below privacy threshold). In that case, what will currently appear here? Does the table disappear completely, or do we display an error message?

**Comment by ivankristianto** [comment]
@marrrmarrr Yes I can confirm that the data in that table is scoped to that specific page.

And regarding if there is not enough information, that table currently show empty table.
Screenshot:
![Screen Shot 2019-07-04 at 16 18 38](https://user-images.githubusercontent.com/656006/60655179-861f3600-9e77-11e9-9c8c-9fbdd4cfed6d.png)

Which could be improved by showing a CTA like other Search Console component when there is not enough data.

**Comment by circlecube** [comment]
QA looks good! Verified the title for the page search query table is specific to the page and the site search query table is not specific to any page.

**Comment by marrrmarrr** [comment]
LGTM.
