### ISSUE TITLE
Add event analytics for Ad blocker detection

### ISSUE THREAD

**Issue by yogeshbeniwal** [google/site-kit-wp#7007]
## Feature Description

Add event analytics to proposed Ad Blocker Detection https://github.com/google/site-kit-wp/issues/6866

- [ ] Implement NTG event analytics as per instructions [here](https://developers.google.com/funding-choices/samples#track_events_associated_with_allow-ads_and_ad_blocking_users_in_google_analytics_with_the_news_tagging_guide_ntg). eventAction: 'allow-ads' need to be updated to eventAction: 'whitelisted'
- [ ] Track events in Google Analytics to determine users' ad blocking usage as per instructions [here](https://developers.google.com/funding-choices/samples#track_events_in_google_analytics_to_determine_users_ad_blocking_usage).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
Hi @yogeshbeniwal, thanks for the suggestion! At this time, the team is not considering adding these events; the less savvy users can see some of this information in AdSense, and savvier users can implement this in other ways.
