### ISSUE TITLE
Upgrading to Version: 1.0.0-rc.1.1 - Impossible to Verify Again

### ISSUE THREAD

**Issue by Yakadanda** [google/site-kit-wp#701]
## Bug Description

'Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.'

## Steps to reproduce

1. Go to 'Upgrade'
2. Click on 'You need to reauthenticate your Google account. Click here'
3. 'Unverified App Screen (Clicks to proceed) '
4. Choose an account to continue to sitekit.withgoogle.com
5. 'Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.'

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by christiaangieles** [comment]
I had that step 5, happen to those sites I upgraded yesterday. I had to stop upgrading, hopefully this gets resolved soon. 

I do like the new verification process, it looks alot more cleaner and better - but the client is now kinda broken. Either only GS gets verified, or only GA.

**Comment by jamesozzie** [comment]
@Yakadanda We have an open issue in relation to this issue, you can keep track of it at #697
