### ISSUE TITLE
Google Site Kit API error when clicking on the Site Kit icon in the Admin Bar 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7011]
## Bug Description

This is a brand new site in gathering state.  `GA4Reporting` feature flag is enabled so only has GA4 property set up for it.  When I go to the front end and click on the Site Kit icon in admin bar, an error message appears: `Google Site Kit API Error method:GET datapoint:report type:modules identifier:analytics error:"Parameter viewId must be set.`"  I have included a screencast to show the issue in action. 

It's worth adding that the data appears and everything seems to function on the front end. 

https://user-images.githubusercontent.com/73545194/236259884-330b4241-eb77-44d9-969a-b90df3181a79.mp4

**Update:**  I also tested this with a site that is in zero data state and another with data, and the same error appears in the console.  This message has a appeared for me in a few different scenarios, as you can see by the reference to this error message in the [tickets here](https://github.com/google/site-kit-wp/issues?q=is%3Aissue+Parameter+viewId+must+be+set+is%3Aclosed) on Github.  

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The admin bar widgets should only request Analytics report data for the currently selected dashboard view – either GA4 or UA, never both 

## Implementation Brief

* The problem appears to be from this line https://github.com/google/site-kit-wp/blob/b5177d3f1c1b486dc695a61ed26a9a7ea8ea4b8f/assets/js/components/adminbar/AdminBarWidgets.js#L93
* This should be changed to a strict comparison to `=== false` instead to avoid a false positive condition when the `dashboardView` setting is not resolved yet, making the value `undefined` temporarily which can be seen by logging `{ isGA4DashboardView }` within `AdminBarWidgets`
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1621608/236890970-463f6559-5d21-43db-a3d4-5e60fd9588a5.png">
* Merge #7019 

### Test Coverage

* Add coverage for testing `AdminBarWidgets` with `ga4Reporting` when `dashboardView` is still `undefined` to make sure no reports are requested

## QA Brief

* This issue makes a simple change to ensure only UA or GA4 widgets are rendered in the admin bar without changing mid-pageload

## Changelog entry

* Ensure correct widgets for Analytics are rendered on page load.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
Moving directly to approval as there's no QA steps here.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

While this has been identified as having no QA steps, I feel we should test to make sure that the console error is no longer appearing in the scenario highlighted in the ticket description.  Will run through a quick test.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Ran through the scenarios in the ticket description and no error appears in the console anymore. 

![image](https://github.com/google/site-kit-wp/assets/73545194/18105576-7e1c-4464-a00b-6ef40e5b73af)

**Comment by aaemnnosttv** [comment]
LGTM 👍
