### ISSUE TITLE
Search Console matching does not work for domain properties

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#702]
## Bug Description

Search Console domain properties do not have an actual URL in `siteUrl`, but instead a `sc-domain:$host`. This breaks Site Kit's `matched-sites` datapoint for such properties, since parsing the host out of these strings fails. This furthermore results in a PHP notice (note these are typically suppressed in the REST API) that the needle used in `strpos()` afterwards is empty.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Search Console matching should work also with domain properties.
* No PHP warning should be triggered in the `matched-sites` datapoint.

## Implementation Brief

* Replace `sc-domain:` with `https://` to make sure the domain looks like a real URL, so then parsing the host works.
* Despite that we expect that to be a domain (without any path), we should still parse the host just to be sure. I've seen SC append a trailing-slash sometimes.

## Changelog entry

* Fix bug where lookup for a matching existing Search Console property did not work for domain properties.

**Comment by aaemnnosttv** [comment]
### QA ✅ 

Tested setting up Site Kit using a user that is a verified owner using a `INET_DOMAIN` type verification.

![image](https://user-images.githubusercontent.com/1621608/67554667-838f6780-f718-11e9-823e-89f69c29f70c.png)

Setup was successful and the `matched-sites` datapoint returned the proper expected response.

![image](https://user-images.githubusercontent.com/1621608/67554718-9ace5500-f718-11e9-851a-61166d680262.png)

Moving to Approval.
