### ISSUE TITLE
"Total Unique Visitors" value different than "Total Users" with GA4

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7027]
## Bug Description

From reviewing the Total Unique Visitors metric on the main WP dashboard widget, the number is higher than total users (on the SK dashboard). There may be an inconsistency on how we're gathering this information. 

Note that the above was checked from one of our testing sites, with GA4 reporting active. 

https://github.com/google/site-kit-wp/assets/41326532/f71b3116-31cf-4f12-ba81-fbbb841e37e6

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `All Users` metric on the main dashboard should match the `Total Unique Visitors` metric shown on the Site Kit Summary widget when the dashboard is configured to source Analytics data from GA4

## Implementation Brief

* The problem is due to using the wrong index (`1`) from the report in the `WPDashboardUniqueVisitorsGA4` widget, so it's currently showing the user count from the previous/comparison date range rather than the current https://github.com/google/site-kit-wp/blob/2b475344795c5c98ce5bee6ff73991f82958a7aa/assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsGA4.js#L83-L84
* Update the component to destructure the `current` and `previous` values from the report totals similar to other instances before getting the metric value `metricValues?.[ 0 ]?.value` for each – see https://github.com/google/site-kit-wp/blob/2b475344795c5c98ce5bee6ff73991f82958a7aa/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/TotalUserCount.js#L90-L91

### Test Coverage

* No changes needed, although VRT will likely need regenerating if there are reference images for this component

## QA Brief

* Review the Total Unique Visitors metric on the main WP dashboard widget, verify the figure is correct and consistent with the All Users total on the Main Dashboard.

## Changelog entry

* Update GA4 user count on WP dashboard to use proper date range.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified when 'ga4Reporting' feature flag is enabled.
- Verified for both 'GA4' and 'UA' dashboard view.
- Verified the All Users metric on the main dashboard matching the Total Unique Visitors metric shown on the Site Kit Summary widget when the dashboard is configured to source Analytics data from GA4.

<details>


https://github.com/google/site-kit-wp/assets/94359491/9308a962-3b71-4075-83cb-848d9ef6d1fb

</details>

**Comment by aaemnnosttv** [comment]
@bethanylang correct, I've assigned it now and double-checked it for approval; this is good to go 👍
