### ISSUE TITLE
UA settings hidden from an Admin with no access

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7028]
## Bug Description

With the `ga4Reporting` feature flag enabled, when an authenticated admin does not have access to the connected UA property, then they are not shown the UA settings in the Settings Edit Form. These should be visible but "disabled" as they currently are with the feature flag disabled.

## Steps to reproduce

1. Enable the `ga4Reporting` feature flag.
2. Setup Site Kit and connect a UA property.
3. Now login as another Admin whose Google Account does not have access to the connected UA property.
4. Go to Analytics Settings and try editing the settings. The settings fields and toggle to enable/disable UA are completely hidden instead of being displayed but disabled.

## Screenshots

https://github.com/google/site-kit-wp/assets/1721319/730b3de0-36e4-4329-9438-1973749e82ba

## Additional Context

While working on #7004, I realised there are a few places in the code which completely hide the "Universal Analytics" toggle and settings if there are no properties available. I believe we would still want to show the toggle and the settings but they should be disabled like the rest of the settings. We simply have to differentiate between when the properties aren't available due to no access or because there really aren't any properties available for the selected account. Some small tweaks will be required below:

https://github.com/google/site-kit-wp/blob/b5177d3f1c1b486dc695a61ed26a9a7ea8ea4b8f/assets/js/modules/analytics/components/common/AccountSelect.js#L72-L76

https://github.com/google/site-kit-wp/blob/b5177d3f1c1b486dc695a61ed26a9a7ea8ea4b8f/assets/js/modules/analytics/components/settings/SettingsForm.js#L142-L154

https://github.com/google/site-kit-wp/blob/b5177d3f1c1b486dc695a61ed26a9a7ea8ea4b8f/assets/js/modules/analytics/components/common/EnableUniversalAnalytics.js#L115-L117

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* With the `ga4Reporting` feature flag enabled, the functionality introduced for Analytics settings in #4825 should work as before. 
    * An authenticated admin who does not have access to the connected Universal Analytics property should be able to view the UA settings fields when editing Analytics settings. As per #4825, these fields should only contain the 'raw' settings values such as Property ID instead of the 'rich' values like Property ID + Property Name. 

## Implementation Brief

* As the "Additional context" above mentioned, differentiating between when properties are unavailable due to no access and when they really aren't available solves this issue. This has been tried and tested in a new simple PR - #7041 which can be reviewed and merged.
* The failing VRT scenario needs to be fixed - "Universal Analytics" title should be moved into the `EnableUniversalAnalytics` component so that it is only rendered when the settings should be rendered.

### Test Coverage

* No new tests required.

## QA Brief

* Follow the steps to reproduce and verify the UA settings with disabled raw values are shown as per the AC.
* Follow the steps to reproduce while logging in as an admin with access to the UA property to ensure they can still see, edit and save UA/GA4 settings.
* Follow the steps to reproduce with the feature flag disabled and ensure the "old" UA/GA4 Edit Settings form works as before.
* Test UA and GA4 setup from scratch with and without the `ga4Reporting` feature flag.

## Changelog entry

* Update Universal Analytics settings UX for consistency with previous interface when GA4 is the primary version and current admin lacks access.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified an authenticated admin who does not have access to the connected Universal Analytics property is now able to view the UA settings fields when editing Analytics settings.
- Tested when 'ga4Reporting' Feature flag is enabled and Dashboard view is UA.
- Tested when 'ga4Reporting' Feature flag is enabled and Dashboard view is Ga4.
- Verified analytics setup when 'ga4Reporting' feature flag is enabled.
- Verified analytics setup when 'ga4Reporting' feature flag is not enabled.

<details>

ga4Reporting enabled - only ga4 connected

![image](https://github.com/google/site-kit-wp/assets/94359491/39455208-cf30-470b-9c04-df194b775d2f)

ga4 reporting enabled - UA connected and view is ga4

![image](https://github.com/google/site-kit-wp/assets/94359491/8c7892a8-9e96-45cc-acc2-a62ca2a74bfc)

ga4 reporting enabled - UA connected and view is UA

![image](https://github.com/google/site-kit-wp/assets/94359491/f8c811fc-11af-4840-a26a-c14a8cf8fd1e)

</details>
