### ISSUE TITLE
Feature tours are dismissed on crash

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7036]
## Bug Description

As noted in #7031, feature tours can be automatically dismissed due to finishing unexpectedly when a tour step's target is not found. This is most likely due to some data that didn't finish loading which the step target depends on before it will be present.

We should adjust our core tour infrastructure so that tours are only (permanently) dismissed when completed or dismissed by the user.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Feature tours should only be dismissed by the following user interactions:
	* when completing the tour by clicking "Got it" on the last step
	* closing the tour by clicking the "X"
	* pressing the Esc key while the tour is active
* Specifically, a tour that ends without completing, due to a missing element for a step should not cause the tour to be dismissed automatically

## Implementation Brief

- In `assets/js/components/TourTooltips.js`:
  - Add a local state that logs if the tour has ended due to a missing element for a step, e.g. `hasMissingTargetError` that defaults to `false`.
  - In the `handleJoyrideCallback` function:
    - Set the `hasMissingTargetError` state to `true` if the following conditions are met:
      - `type` of the callback data is `EVENTS.TARGET_NOT_FOUND`.
      - `index` of the callback data is the last step of the tour (the last step can be determined by using the `size` property of the callback data).
  - In the `endTour` function:
    - Dispatch the `dismissTour` action only if `hasMissingTargetError` state is falsey.

### Test Coverage

- In `assets/js/components/TourTooltips.test.js`:
  - Add a test case to reflect the above changes.
  - Update any failing test.

### QA:Eng

- In order to test this, you need to make Site Kit assume that there's a missing step in one of the feature tours.
- Let's use the GA4 Reporting feature tour for this test.
- In `assets/js/feature-tours/ga4-reporting.js`, for the second step's `target`, change the selector to be something non-existent, e.g. '.googlesitekit-table__head-item--sessions:not(.googlesitekit-table__head-item--badge) .non-existent'.
- Now, trigger the GA4 Reporting feature tour. See instructions in QAB of #6926 if needed.
- Go through the steps and wait until the feature tour crashes due to the missing step.
- Now, verify that the feature tour isn't dismissed. To do so, run the `getDismissedItems()` selector of the `core/user` store in the browser console and verify that `ga4Reporting` isn't included in the resulting array.

## Changelog entry

*

**Comment by tofumatt** [comment]
IB ✅

**Comment by nfmohit** [comment]
Just looking out for a little advice here. How does it sound if we skip dismissing a feature tour if any of the step's target is missing?

At the time of writing the IB, the feature tour would only get dismissed if the last step was missing. If a step in between was missing, it would skip to the next available step.

As I test it out now, if a feature tour step is missing, it moves back to the previous step, crashes, and dismisses the tour.

CC: @aaemnnosttv

**Comment by techanvil** [comment]
Hey @nfmohit, what you've suggested is essentially what's required by the AC, so if the current IB doesn't fully meet the requirements and you have an alternative working solution, I'd say go for it, and make a note of it in the PR e.g. under "Relevant technical choices".

Alternatively if your new solution is a bit complex or you have any questions about it and you feel it would merit fleshing out in a new IB then that would also be a reasonable approach to take here.

**Comment by techanvil** [comment]
Closing this issue in favour of https://github.com/google/site-kit-wp/issues/7281.
