### ISSUE TITLE
Add GA events for GA4 reporting

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7045]
## Feature Description

A number of custom events are to be instrumented in the plugin interfaces related to GA4 reporting for users who have opted-in to reporting anonymous usage stats.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following internal custom events should be tracked

* `SwitchGA4DashboardViewNotification`
  category: `{viewContext}_ga4-display-notification`
	| Event name | Trigger |
	| --- | --- |
	| `view_notification` | visibility |
	| `confirm_notification` | click CTA |
	| `dismiss_notification` | dismiss CTA |
	| `click_learn_more_link` | click learn more |
* GA4 feature tour  
  category: `{viewContext}_ga4-metrics`  
  label: number of current step
	| Event name | Trigger |
	| --- | --- |
	| `feature_tooltip_view` | visibility |
	| `feature_tooltip_dismiss` | close |
	| `feature_tooltip_advance` | click next |
	| `feature_tooltip_return` | click back |
	| `feature_tooltip_complete` | click "Got it" |
* "New" badge tooltip learn more  
	category: `{viewContext}_ga4-new-badge`  
	action: `click_learn_more_link`  
	on: click
* `ReminderBanner` (when displaying **"Universal Analytics stopped collecting data on July 1, 2023"** – the [current category](https://github.com/google/site-kit-wp/blob/c690d2cacd381a6347356769d790aa16569c2a38/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js#L88) should still be used until this point)
category: `{viewContext}_ua-stale-notification`
	| Event name | Trigger |
	| --- | --- |
	| `view_notification` | visibility |
	| `confirm_notification` | click CTA |
	| `dismiss_notification` | dismiss CTA |
	| `click_learn_more_link` | click learn more |
* `UACutoffWarning`
	category: `{viewContext}_widget-ua-stale-warning`  
	| Event name | Trigger |
	| --- | --- |
	| `view_notification` | visibility |
	| `confirm_notification` | click CTA |
	| `click_learn_more_link` | click learn more |
* **Set up your Google Analytics 4 property here** tooltip in GA set up  
	category: `{viewContext}_ga4-setup`
	| Event name | Trigger |
	| --- | --- |
	| `feature_tooltip_view` | visibility |
	| `feature_tooltip_dismiss` | dismiss CTA |
* `SwitchedToGA4Banner`  
	category: `{viewContext}_ga4-display-success-notification`
	| Event name | Trigger |
	| --- | --- |
	| `view_notification` | visibility |
	| `confirm_notification` | click CTA |
	| `dismiss_notification` | dismiss CTA |
* `SettingsUACutoffWarning` (future)  
	category: `{viewContext}_ua-future-warning`
	| Event name | Trigger |
	| --- | --- |
	| `view_notification` | visibility |
	| `click_learn_more_link` | click |
* `SettingsUACutoffWarning` (past)  
	category: `{viewContext}_ua-stale-warning`
	| Event name | Trigger |
	| --- | --- |
	| `view_notification` | visibility |
	| `click_learn_more_link` | click |
* Google chart lines (collection ended, or ga4 property created) are visible on the chart – i.e. chart is visible and line is in range  
	category: `{viewContext}_ga4-data-collection-line`
	action: `chart_line_view`  
	on: visibility
	* Additionally, when the respective tooltip is shown  
		category: {same}  
		action: `chart_tooltip_view`  

## Implementation Brief

- Use `useViewContext()` to retrieve the current view context to use in the event category.
- use [`trackEvent()`](https://github.com/google/site-kit-wp/blob/5668847a1c8f6accd85500b9deda7587552bc3d2/assets/js/util/tracking/createTrackEvent.js#L38) to dispatch the GA events.
- Consider using `useInView()` where appropriate to provide additional determination of a component's in-view status.
- For components that use `BannerNotification`, the following pattern can generally be followed:
  - Use the `onView()` prop for a callback to track the `view_notification` event.
  - Use the `onCTAClick()` prop to track the `confirm_notification` event.
  - Use the `onDismiss()` prop to track the `dismiss_notification` event.
  - Use the `onLearnMoreClick()` prop to track the `click_learn_more_link` event.
- For each case, refer to the AC for the event category to use and the specific set of events to track.

#### `SwitchGA4DashboardViewNotification`

- File: `assets/js/components/notifications/SwitchGA4DashboardViewNotification.js`
- This is a notification component that uses `BannerNotification`, and the general pattern listed above can be followed.

#### GA4 feature tour

- File: `assets/js/feature-tours/ga4-reporting.js`
- Feature tours already track the required events, all that needs to be done here is to update `gaEventCategory()` to return the correct category as per the AC.

#### "New" badge tooltip learn more link

- File: `assets/js/components/NewBadge.js`
- Track `click_learn_more_link` in a click handler for the `Link`.

#### `ReminderBanner`

- File: `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js`
- This already implements the required events. All that's needed is to make the category dependent on the date as per the AC.

#### `UACutoffWarning`

- File: `assets/js/modules/analytics/components/common/UACutoffWarning.js`
- This already tracks an event on CTA click, this should be updated to use the correct category and event name as per the AC.
- Use a `useEffect()` hook to track `view_notification` when the warning is visible (i.e. `shouldDisplayWarning` is true).
- Track `click_learn_more_link` in a click handler for the `Link`.

#### _Set up your Google Analytics 4 property here_ tooltip in GA set up

For this case, it's necessary to augment the `JoyrideTooltip` component to accept an `onView()` prop and invoke it when the tooltip is viewed.

- File: `assets/js/components/JoyrideTooltip.js`
- Add the `onView()` prop.
- It looks like adding a case in `callback()` to invoke `onView()` when `type === EVENTS.TOOLTIP` should work here, but this should be thoroughly vetted during implementation.
- See `react-joyride` [documentation](https://docs.react-joyride.com/callback) (and source) for further information.

Once `JoyrideTooltip` is updated, the `GA4SettingsControls` component can be updated to track the events.

- File: `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`
- Track the events as per the AC by using the `JoyrideTooltip` component's `onView()` and `onDismiss()` props.

#### `SwitchedToGA4Banner`

- File: `assets/js/components/notifications/SwitchedToGA4Banner.js`
- This is a notification component that uses `BannerNotification`, and the general pattern listed above can be followed (note there's no "Learn more" link/event).

#### `SettingsUACutoffWarning`

- File: `assets/js/modules/analytics/components/settings/SettingsUACutoffWarning.js`
- Ensure the category is as defined in the AC depending on the date (see future/past AC definitions for this component).
- Use a `useEffect()` hook to track `view_notification` when the warning is visible (i.e. `shouldDisplayWarning` is true).
- Track `click_learn_more_link` in a click handler for the `Link`.

#### Google chart lines (collection ended, or GA4 property created) are visible on the chart – i.e. chart is visible and line is in range

- File: `assets/js/components/GoogleChart/index.js`
- Extract the JSX that maps over `dateMarkersInRange` into a new component, `DateMarkers` in the same directory.
- Within `DateMarkers`:
  - Use a `useEffect()` hook to track the `chart_line_view` event.
  - Add an [`onOpen()`](https://v4.mui.com/components/tooltips/#controlled-tooltips) prop to `Tooltip` to track the tooltip event with category and event name as per the AC.

### Test Coverage

- Aim to add JS test coverage for all of the event tracking added here.
- If any events prove unrealistic to cover with our current test stack they can be omitted.
- Note that the feature tour code already has generic test coverage for its events (see tests for `TourTooltips`) and doesn't need tests added for this specific tour.

## QA Brief

- Using the [`Google Analytics Debugger` Chrome extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna), verify that the appropriate events are tracked in Site Kit as described in the ACs.
- Since components are mentioned in the ACs, here is a non-technical description of components:
  - `SwitchGA4DashboardViewNotification`: `Display data from Google Analytics 4 on your dashboard` banner notification.
  - `ReminderBanner`: `Set up Google Analytics 4 now to join the future of Analytics` banner notification.
  - `UACutoffWarning`: In-widget warnings that are supposed to show up after UA cut-off if GA4 is not connected, saying `Your data is stale because Universal Analytics stopped collecting data on July 1, 2023`.
  - `Set up your Google Analytics 4 property here tooltip`: The tooltip that appears in the Analytics Settings Edit view when you click the `Connect Google Analytics 4` button.
  - `SwitchedToGA4Banner`: `Your dashboard now displays data from Google Analytics 4, the new version of Analytics` banner notification.
  - `SettingsUACutoffWarning`: The warning that shows up in Analytics settings if GA4 is not connected.

## Changelog entry

* Add internal GA tracking on GA4 reporting events for those who have opted-in.

**Comment by techanvil** [comment]
@aaemnnosttv, while drafting the IB I've determined it will be possible to track an event when the chart key date tooltip is shown.

Could you please update the AC with the required event category and name for this case?

**Comment by aaemnnosttv** [comment]
Thanks @techanvil 

IB ✅ 

> * Use a `useEffect()` hook to track `view_notification` when the warning is visible (i.e. `shouldDisplayWarning` is true).

While reviewing, I noticed that we should probably update this line to use `=== false` instead of `!` to avoid a false positive while resolving the connected state, but perhaps this is so quick that it's never visible.
https://github.com/google/site-kit-wp/blob/9eb3122c62e63de3aab4c26168a03ec266932024/assets/js/modules/analytics/components/common/UACutoffWarning.js#L85

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Using the Google Analytics Debugger Chrome extension the appropriate events are tracked in Site Kit as described in the ACs.  I am not going to list them all here but you can find screenshots of all of the GE Events below. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/48ec594d-a8e7-4ccc-b638-d5c0d8679f46)
![image](https://github.com/google/site-kit-wp/assets/73545194/354b9e3e-4c5b-4126-9b55-4430578f1d6d)
![image](https://github.com/google/site-kit-wp/assets/73545194/9ab7acf6-7a73-4e90-aa69-5f69b4ee1fdc)
![image](https://github.com/google/site-kit-wp/assets/73545194/84a26536-108f-47b4-8fe3-ef29bbea8952)
![image](https://github.com/google/site-kit-wp/assets/73545194/07d4a1c0-1010-47a9-9169-74c6be1c126d)
![image](https://github.com/google/site-kit-wp/assets/73545194/2a2e704b-6a46-4ee9-977f-c52e6518496a)
![image](https://github.com/google/site-kit-wp/assets/73545194/76542a90-17f8-4470-99fe-c21d5748b5a9)
![image](https://github.com/google/site-kit-wp/assets/73545194/c424525b-3950-420b-92fd-6d308a66e410)
![image](https://github.com/google/site-kit-wp/assets/73545194/93c4bfa1-ccf0-4015-9250-2794ac1b62f0)
![image](https://github.com/google/site-kit-wp/assets/73545194/3bd3bdac-3929-4d7c-9935-968578a5f220)
![image](https://github.com/google/site-kit-wp/assets/73545194/218a71d7-a289-4f90-9d8a-414f7d7d7ce5)
![image](https://github.com/google/site-kit-wp/assets/73545194/135e6ab3-adc5-4226-8d3d-862d9f797bf0)
![image](https://github.com/google/site-kit-wp/assets/73545194/364df44d-4074-4b58-902d-3178551d0808)
![image](https://github.com/google/site-kit-wp/assets/73545194/be253ff0-8ffe-40f7-b06e-925d440e3323)
![image](https://github.com/google/site-kit-wp/assets/73545194/e16b3b13-fd5f-43c7-b13e-dcb5d05ac329)
![image](https://github.com/google/site-kit-wp/assets/73545194/c80295ef-792d-4b02-a5ef-ea04c7b341f2)
![image](https://github.com/google/site-kit-wp/assets/73545194/415afc20-d6b7-4892-a31c-2f32f4816b52)
![image](https://github.com/google/site-kit-wp/assets/73545194/930a8f0c-4519-4a18-b241-701d333f8364)
![image](https://github.com/google/site-kit-wp/assets/73545194/3bdb63f5-2d3c-4761-a365-5136c4b2db9d)
![image](https://github.com/google/site-kit-wp/assets/73545194/d75e6c93-a5b7-495c-853f-7f6f6e0acb6a)
![image](https://github.com/google/site-kit-wp/assets/73545194/2afe8068-d22f-4035-9e97-90a4b75f3510)

</details>

**Comment by aaemnnosttv** [comment]
#### ❌ Approval

The chart line hover event looks like it was missed in QA and is emitting too many events. I'm using a local change to log the events because GA debugger outputs so much that it is difficult to see more than one event at a time.

https://github.com/google/site-kit-wp/assets/1621608/5d3bc29b-260c-4e77-932b-6d00ad8b6362

**Comment by nfmohit** [comment]
@aaemnnosttv I have opened #7122 as a follow-up PR for the above issue, thanks!

**Comment by aaemnnosttv** [comment]
This is good now, thanks all!

**Comment by wpdarren** [comment]
@aaemnnosttv oops, apologies, I did test the chart line hover event, but must have missed the additional events, will keep a look out for that in the future.

**Comment by aaemnnosttv** [comment]
The GA Debugger extension makes it difficult to see multiple events at a time.
