### ISSUE TITLE
Site Kit won't make web data streams available for selection if the site URL doesn't match

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7052]
## Bug Description

When selecting a web data stream within Site Kit, the only streams that will be available within Site Kit are those that have a matching site URL (defined within Analytics). Given that a site URL can change, display all web data streams for selection. 

![image](https://github.com/google/site-kit-wp/assets/41326532/1a8f8d53-5c30-4fb4-9f2a-72622aabc82a)

Recording of experience with some highlighted points below:
- 0.11: Site Kit has been successfully set up and the Analytics settings page is open, ready to edit 
- 0.25: A new web data stream is created, with the site URL matching the website which SK is set up on
- 0.53: The data stream is available for selection within Site Kit
- 1.22: A new web data stream is created, with the site URL not matching the website which SK is set up on
- 1.46: The new web data stream is not available for selection within SK, unlike the other one with a valid site URL

https://github.com/google/site-kit-wp/assets/41326532/419b7a2f-c6cd-4a9e-95cb-2a346c98f83b

## Steps to reproduce

1. Setup Sit Kit with Analytics on a new site
2. Visit the Analytics settings within Site Kit and open the Analytics edit page
3. Visit analytics.google.com and navigate to the connected GA4 property
4. Create 2 new web data streams. When adding the site URLs make one match the site URL where SK is set up on, the other should be an invalid site URL or even a site URL that includes a subdirectory of the site where SK is set up on
5. Visit the SK Analytics settings page and check for the new web data steams. Only the web data stream that matches the site URL exactly is available

## Additional context

- Even data streams with site URLs that include a subdirectory that may be based off the correct site URL where Site Kit is set up on don't appear for selection within Site Kit. 
- Tested on SK 1.99.0 without the tester plugin
- I noticed this when checking for issues as highlighted by [one user in the forums](https://wordpress.org/support/topic/cant-connect-ga4-on-multisite/#post-16732269) (whereby they are setting up SK on a multisite - [Asana task for this testing](https://app.asana.com/0/1185360131189553/1204590058856466/f))
- Further testing ongoing to check does Site Kit report issues if Analytics is already connected, but a user then changes the site URL from within the Analytics platform (without changing the Site URL on the site where Site Kit is connected - ie. The site URL defined within the web data stream is invalid)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The web data stream select control should always include all web data streams of the currently selected GA4 property (i.e. no longer limited based on the stream's URL)
* The behavior of the select to pre-select a stream based on a matching URL should remain as today

## Implementation Brief

* In `assets/js/modules/analytics-4/components/common/WebDataStreamSelect.js`:
   * Get the `webDataStreams` using the `getWebDataStreams` selector instead of `getMatchingWebDataStreamsByPropertyID` selector.
* In `assets/js/modules/analytics/components/settings/PropertyOrWebDataStreamNotAvailableError.js`:
    * Get the `webDataStreams` using the `getWebDataStreams` selector instead of `getMatchingWebDataStreamsByPropertyID` selector. 
* In `assets/js/modules/analytics-4/datastore/webdatastreams.js`:
    * Remove `getMatchingWebDataStreamsByPropertyID` selector as it will no longer be used in the code base. 
* In `assets/js/modules/analytics-4/datastore/properties.js`:
    * Update the `selectProperty` action to account for the above change. Namely,
            * Near the end of the action (after the `waitForWebDataStreams` call):
                * First, it should try and match the `webdatastream` with the URL matching using the `getMatchingWebDataStreamByPropertyID` selector as is done currently. 
                * But, if a `webdatastream` is not found using the above selector: 
                    * Get all the `webdatastreams` of the property using `getWebDataStreams`.
                    * If more than zero `webdatastreams` are available, set the first one as the selected web data stream. ie. `webdatastreams[0]._id`.

### Test Coverage

* Add/update coverage for the above changes in the following test files.
    * `assets/js/modules/analytics-4/datastore/properties.test.js`
    * `assets/js/modules/analytics-4/datastore/webdatastreams.test.js`
    * `assets/js/modules/analytics/components/settings/PropertyOrWebDataStreamNotAvailableError.test.js`
* Update any failing tests/stories due to the above changes. 

## QA Brief

* Replicate the scenario outlined in the steps to reproduce.
* Validate that all the web data streams associated with the selected property are present in the dropdown list, irrespective of whether the URL matches.
* Confirm that when no matching data stream is present, it defaults to selecting the first available data stream from the list.

## Changelog entry

* Remove the requirement for a web data stream's URL to match the current site URL for it to be selectable.

**Comment by aaemnnosttv** [comment]
This is relevant because reporting is done using the property where we already filter based on the hostname but not by the data stream, which means any data stream for a property that records data for the site should work just fine.

Limiting the choices by the URL can also create a situation where the user would be blocked from setting up GA4 with a chosen property (in theory, although unlikely) if an existing GA4 property already had a web data stream with a different URL than the current site but had the same stream name that Site Kit would otherwise create. This would fail because the stream names must be unique, so the user wouldn't be able to create or select the existing data stream. In this case, the user would need to either use a different property, or rename the existing data stream.

There doesn't seem to be an obvious reason to restrict the choices for data streams though.

**Comment by techanvil** [comment]
Hey @kuasha420, this IB is looking good. I have noticed a couple of additional aspects that we should consider:

- It looks like we should also update `PropertyOrWebDataStreamNotAvailableError` to replace `getMatchingWebDataStreamsByPropertyID()` with `getWebDataStreams()`, otherwise the component can return null when it should display an error.
- This being the case, `getMatchingWebDataStreamsByPropertyID()` would no longer be used and can be removed.

Please take a look and see what you think.

**Comment by kuasha420** [comment]
Hi, good catch, I have updated the IB accordingly. Cheers.

**Comment by techanvil** [comment]
Thanks @kuasha420!

IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested by creating non-matching and invalid URL's web streams.
- Verified all non matching and invalid URL's are listed under web streams drop down list.
- Verified that when no matching data stream is present, it defaults to selecting the first available data stream from the list.

<details>


https://github.com/google/site-kit-wp/assets/94359491/f7fa33d8-a20b-483f-ad6e-12b8ffbbf798

Dev

![image](https://github.com/google/site-kit-wp/assets/94359491/ba807c06-ba89-4e1b-a79f-d24d6b781cf6)


Latest env - No matching web stream showing

![image](https://github.com/google/site-kit-wp/assets/94359491/3c374492-ba59-4ad5-a046-7d50f8f8db2b)

</details>
