### ISSUE TITLE
Analytics changing its state immediately from gathering to zero when Admin 2 signs in into SK.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7054]
## Bug Description

If Admin 2 sign in into Site kit with Google a/c that don't have access to connected Analytics a/c.  Then Analytics state immediately changes from gathering to zero. It happens for both Admin 1 and Admin 2. 

## Steps to reproduce

- Create new site.
- When 'ga4Reporting' is enabled, create a/c using only ga4 from Admin A a/c. (or we can use existing a/c having both UA and GA property).
- Analytics and Search console will appear in gathering state.
- Make sure dashboard view set to GA4.
- Now sign in with Admin 2 who don't have access to analytics account and set up site kit.
- Access main dashboard.
- Notice analytics showing in zero state.
- Search console is in gathering state banner is showing with 72 hours time which is not correct. It should be 48 hours in this case.

## Screenshots

Admin 2 main dashboard after Sign-in.

![image](https://github.com/google/site-kit-wp/assets/94359491/3b4046a5-9aa7-401e-a299-66265063364a)

Admin 1 main dashboard after Admin 2 Sign-in.

![image](https://github.com/google/site-kit-wp/assets/94359491/a8ff25bf-d977-4164-8891-47af8380fd6c)

https://github.com/google/site-kit-wp/assets/94359491/9545e03f-a4fb-4e69-a382-a52864ed9f0b

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Note that I've added https://github.com/google/site-kit-wp/issues/7876 as a separate issue to handle the 48/72 hour figure in the notification.

**Comment by techanvil** [comment]
Hi @mohitwp, I've tried to reproduce this but am unable to. Please can you retest this - if you are no longer able to reproduce then we can close this issue (please note that I've created a separate issue to update the hours figure on the notification as per my previous comment).

**Comment by wpdarren** [comment]
I cannot recreate this, so I am proposing we close it.  I see the gathering state on the dashboard, and the correct gathering state banner appears.
