### ISSUE TITLE
The link you followed has expired: Setup redirect to 403 page from subdirectory to root site

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7055]
## Bug Description

As initially reported by [one user in the forums](https://wordpress.org/support/topic/site-kit-redirects-to-old-site-on-setup-2/#post-16745422), if Site Kit is set up successfully on a parent domain, and the user then tries to set up the plugin on a subdirectory site, they'll land back on a 403 error page on the root directory site. 

Check to ensure that on a clean WP install from a subdirectory, no invalid site records existing on the service (referencing the WP install on root). 

_Recording below of the issue. Notice SK is being set up on a first time WP install on a subdirectory, only to be redirected to an invalid page. No callback referencing the root site appears in the address bar._

https://github.com/google/site-kit-wp/assets/41326532/6f5aea34-149e-4307-9db2-f03b2e07068a

Recording below of the same reproduced on completely different site (and subdirectory). In this case I get past the OAuth sign in on the subdirectory site, but only if I select a different Google account to that previously used (see the third attempt, from 1.08 onwards). 

https://github.com/google/site-kit-wp/assets/41326532/8e523dc9-01fd-40bb-95b9-2e0ffa123df2

## Steps to reproduce

1. Setup SK on the root directory of a site (No need to include Analytics)
2. Create a new subdirectory (that wasn't used before) and install WP on this subdirectory  
3. Attempt SK set up on the subdirectory site
4. After clicking on the "Continue" button when signing in with Google you're directory to a 403 page on the main root site, not on the subdirectory site

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/41326532/1253faa9-21f9-4ed8-b8fb-6f5a2c5448aa)

## Troubleshoot checks performed when this occurs

- Check from another browser: Same occurs
- Check using another Google account: Same occurs
- Check renaming the site title: Same occurs
- Defining SK constants: Same occurs
- Resetting SK on both the root and subdirectory sites and connecting once more
- Resetting SK on both the root and subdirectory sites, changing the site title on both and connecting once more

## Additional Context

 - SK 1.99.0
 - Tested and reproduced on 2 sites (although from the same hosting provider). In one case the error I did manage to get passed the "Sign in with Google OAuth page" only to land back on an invalid 403 error page on the root site once more. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
@jamesozzie I am able to reproduce this. You can see the outcome of my test in the recording below: 

https://www.loom.com/share/a3b1682d14a14560b1cce9ea621c204b

I agree that this is definitely one to flag to the team.  Let me know if there's anything else I can help with on this.

**Comment by jamesozzie** [comment]
Thanks @adamdunnage. I'm going to test the same with a subdomain setup, while also checking for potential workarounds.

**Comment by eugene-manuilov** [comment]
Ok, after reviewing this issue, I found a small issue on the service side. It has been fixed and going to be deployed to production soon. Once deployed, I'll update this ticket.

**Comment by eugene-manuilov** [comment]
@jamesozzie, the fix has been deployed to production. This issue should be fixed now. Can you verify it on your end?

**Comment by adamdunnage** [comment]
@eugene-manuilov I can confirm that from the site I used to test, this is now working and I am no longer getting the issue. Over to you @jamesozzie to confirm from your side.

**Comment by jamesozzie** [comment]
All good from my side also. Awaiting feedback from one impacted user I reached out to to confirm before closing.

**Comment by jamesozzie** [comment]
Closing this with the impacted user confirming the issue no longer occurs.
