### ISSUE TITLE
`An error occurred while running 'mapSelect': Cannot read properties of null (reading 'isUsingProxy')

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7056]
## Bug Description

One user in the support forums reported the following errors:

- On the plugins.php page and the SK “Settings” tab ([recording](https://youtu.be/0ebYXCqXK9E?t=75)): `An error occurred while running ‘mapSelect’: Cannot read properties of undefined (reading ‘getAdminURL’)`
- On the Site Kit dashboard ([recording](https://youtu.be/0ebYXCqXK9E?t=78)): `An error occurred while running ‘mapSelect’: Cannot read properties of undefined (reading isUsingProxy)`
- On the WordPress Dashboard page: `An error occurred while running ‘mapSelect’: Cannot read properties of undefined (reading ‘enableAutoUpdate’)`

One of the users provided a recording of their experience, which can be viewed below. In their case the same occurs with only Site Kit active (via the Health Check & Troubleshooting plugin) while using a Chrome browser incognito window. 
https://www.youtube.com/watch?v=cJWw0yfy78E&t=7s

**Console error:**
```
failed to load resource: the server responded with a status of 403 ()
index.min.js?ver=1678500846:1 Uncaught TypeError: Cannot read properties of null (reading 'id')
```

## Steps to reproduce

This has not been reproducible so far by the support team. 

## Impacted Users
- https://wordpress.org/support/topic/g-site-kit-cant-working-and-cant-reset  | SH info within topic | **Open** - awaiting response

The same user reported the same previously: 
- https://wordpress.org/support/topic/site-kit-encountered-an-error-101/ | SH info within topic  

## Screenshots

_The error as it appears on the SK dashboard (with only SK active)_

![image](https://github.com/google/site-kit-wp/assets/41326532/6c161b99-c739-4efc-86df-c47d48addc8b)

_The error as it appears on the SK settings tab and the plugins.php page_

![image](https://github.com/google/site-kit-wp/assets/41326532/ac85aa52-4859-4b04-90cb-0377cb987abe)

_The error as it appears on the SK settings tab and the plugins.php page_

## Additional Context

 - SK 1.99.0
 - This only started to occur recently, both since SK 1.99.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by Gambo100** [comment]
I have similar issues starting today where i cannot reset nor work with sit kit plugin. Error occurred and I hope to see it resolved.

**Comment by adamdunnage** [comment]
@Gambo100 We don't provide support through GitHub but if you would be willing to [open a new support topic ](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0)for your issue then we can gather some further information from you that may prove useful to finding the cause of this issue. Thanks.

**Comment by jamesozzie** [comment]
Closing this with the impacted user now able to proceed after updating to the latest version of Site Kit. No other reports and unable to recreate the same issue with the same environment ([Asana task](https://app.asana.com/0/1185360131189553/1204622347552681/f)).
