### ISSUE TITLE
Info/Learn More Link for "Most Popular Products" widget tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7060]
## Feature Description

The "Most Popular Products" key metric widget tile will check if the current site has a "product" post type. It will then figure out the URL format used for this post-type and filter GA path URLs to figure out the most popular products. Based on this [comment](https://github.com/google/site-kit-wp/issues/6249#issuecomment-1442354919), we need a way of communicating this to users, i.e. how we define / determine posts to be products for this widget tile. 

An info icon with text on hover should be implemented as per the Figma mock screenshot below:

<img width="542" alt="PopularProductsInfoIcon" src="https://github.com/google/site-kit-wp/assets/1721319/c1f6a1ba-62a5-42a2-82ee-840ee62a2148">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Popular Products Key Metric widget tile should have an Info Icon as per [this Figma Design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=4581%3A80161&t=Cpa9UfXNDT3GRu83-1) mock.
* On hovering the info icon, the message as shown in the Figma mock text should appear in a popup. 
* The word "replace" is a link to the same target as the "Change Metrics" link that allows the user to pick their own metrics from the slider that slides out from the side.

## Implementation Brief

- In `assets/js/components/KeyMetrics/MetricTileTable.js`:
  - Introduce a new prop that will include content for the information tooltip, say `infoTooltip`.
  - If the `infoTooltip` prop is truthy:
    - Render a `Tooltip` component to the right end of `div.googlesitekit-km-widget-tile__title`.
    - Since they need to be in the same row, both `div.googlesitekit-km-widget-tile__title` and the `Tooltip` can be inside a new flex container.
  - The `Tooltip` component:
    - should have the `infoTooltip` prop contents passed to its `title` prop.
    - should have a placement of `top`.
    - use the `assets/svg/icons/info.svg` SVG as child.
    - can use `Tooltip` rendered in `assets/js/components/NewBadge.js` as inspiration.
  - All required styles should be added to `assets/sass/components/key-metrics/_googlesitekit-km-widget-tile.scss`.
- In `assets/js/modules/analytics-4/components/widgets/AnalyticsMostPopularProductsByPageviewWidget.js` (being created in #6249):
  - Pass the `infoIcon` prop to the `MetricTileTable` component, with its value being the text according to the Figma design.
  - Use a `Link` component to render the `replace` link, clicking on which should slide out the Metrics Selection Panel (being implemented in #6258).
- In `assets/js/components/KeyMetrics/MetricTileTable.stories.js`:
  - Add a Storybook story variant with `infoTooltip`.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Set up Key Metrics by selecting "Sell products or services" for the first question "What is the main purpose of this site?" to view the "Most popular products" widget.
* Verify that the info icon appears on the widget per the Figma design.
* Verify that a tooltip is displayed as per the Figma design by hovering the info icon.
* Verify by clicking the `replace` link in the tooltip info opens the Metrics Selection Panel.

**Update**
* Verify both the issues reported in the [comment](https://github.com/google/site-kit-wp/issues/7060#issuecomment-1664827831) are fixed.

## Changelog entry

* Add a learn more tooltip to the most popular products KM widget.

**Comment by bethanylang** [comment]
@jimmymadon @sigal-teller has put together a design here: https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=4581%3A80161&t=Cpa9UfXNDT3GRu83-1. Reassigning over to you for review. If you have any follow-up questions, you can update [this Slack thread](https://10up.slack.com/archives/CFFRMC5DE/p1684584783652569). Thanks!

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
I like this UI, very slick 🙂

IB ✅

**Comment by aaemnnosttv** [comment]
Back to you @wpdarren for another pass 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The "Most popular products" tile has the tooltip icon as per the Figma design.
- A tooltip is displayed as per the Figma design by hovering the info icon.
- By clicking the replace link in the tooltip info opens the Metrics Selection Panel.

https://github.com/google/site-kit-wp/assets/73545194/00338a8a-de9c-4cfe-9b1b-e19f9b7379b0
