### ISSUE TITLE
Show the UA controls in the case where the connected property belongs to another Google account and permission has been removed.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7063]
## Feature Description

At present, in the scenario where an admin has connected a UA property that belongs to another Google account, and then the permission to that property is removed, in the case where there are no other properties available to select in that account, the UA controls are removed from the page.

This is in contrast to the behaviour for GA4 which continues to show the controls when permission to the connected property is removed.

For example, given the following setup, where the current user has permission to and has connected these Analytics properties:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/d6d9af8f-3107-4f83-a4bc-1886eeaf8875)

If the permission to the UA property is then removed, the UA controls disappear entirely:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/918a5b4a-525b-4e78-a17d-e5588c9a9ea9)

Whereas, if the permission to the GA4 property is removed, the controls are still present, with the option to create a new property available in the dropdown:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/2a39b3eb-d5e0-4a19-8fd6-f1c295da4b8f)

We should ensure that we continue to display the UA controls in the above UA scenario in a manner that is consistent with the GA4 controls.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `EnableUniversalAnalytics` component should not return `null` if no UA properties exist if there is a UA property already connected.

## Implementation Brief

- In `assets/js/modules/analytics/components/common/EnableUniversalAnalytics.js`:
  - Update the condition that checks if there are no UA properties and returns `null` if so, such that this condition is omitted if there is a UA property already selected (can be done by checking if `MODULES_ANALYTICS` `getPropertyID()` is a valid property ID.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* With the `ga4Reporting` feature flag enabled.
* Connect Analytics with UA enabled with a property belonging to another Google account.
* Remove the current user access for that account/property from the Analytics console.
* Go to the Analytics edit page and ensure the `Enable Universal Analytics` toggle is displayed.
* Ensure the UA controls are displayed when the `Enable Universal Analytics` toggle is enabled.
* Change the account to a different one.
* Verify that the UA toggle and controls are displayed or not based on the properties' availability as it work today.
* Change back to the initial account.
* Verify that the UA toggle and controls aren't displayed because there's nothing to select when returning to the initial account since we have already shown the error message and the empty dropdowns.

## Changelog entry

* Ensure the Universal Analytics controls are shown in the case where the connected property belongs to another Google account and permission has been removed.

**Comment by nfmohit** [comment]
### Note to AC Reviewer:

I have also added an IB while working on its ACs. If the ACs look good, please move this forward to IBR.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified all conditions mentioned under AC.
- Verified that the Enable Universal Analytics toggle is displayed when current user don't have access to it analytics a/c.
- Verified that the UA controls are displaying when the Enable Universal Analytics toggle is enabled.
- Verified that the UA toggle and controls are displaying or not based on the properties' availability.

<details>


https://github.com/google/site-kit-wp/assets/94359491/a7f9f3b7-4ed9-430c-af5f-4c114aca5c6c

</details>
