### ISSUE TITLE
Promote INP to non-experimental status

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7065]
## Feature Description

The Chrome team [recently announced](https://web.dev/inp-cwv/) that the _Interaction to Next Paint_ (INP) web vital metric is no longer experimental.

Site Kit added support for surfacing INP in #5207 as a field data metric of the PageSpeed Insights widget. Practically speaking, the announcement means that [the `experimental_interaction_to_next_paint` field is now deprecated](https://web.dev/inp-cwv/#evolving-inp).

We should update the presentation of the metric to no longer be labelled as "experimental" and update our consumption of it from the API to use the new, non-experimental field. Technically the field is now considered "Pending", with the roadmap of becoming "Stable" in May 2024.

![image](https://github.com/google/site-kit-wp/assets/1621608/faef3bc0-c82a-42c1-a221-7a036bfdb846)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The INP field metric of the PSI pagespeed widget should no longer be labeled as "Experimental"
* The metric should no longer be conditionally displayed; it should always be shown with other field metrics

### Visual presentation of the field:
* Go to `assets/js/modules/pagespeed-insights/components/common/FieldReportMetrics.js`
    * Under the `ReportMetric` component with title `Interaction to Next Paint`:
        * Remove `experimental` prop.
        * Remove `isHidden`
        * Leave `isLast` prop without conditional, it should be always true.
     * Under the `ReportMetric` component just above, with title `First Input Delay`:
         * Remove `isLast` prop
         
### Non-experimental field changes
* In following files `assets/js/modules/pagespeed-insights/components/common/FieldReportMetrics.js`, `assets/js/modules/pagespeed-insights/datastore/__fixtures__/pagespeed--desktop.json`, and `assets/js/modules/pagespeed-insights/datastore/__fixtures__/pagespeed--mobile.json`, replace: 
    * `EXPERIMENTAL_INTERACTION_TO_NEXT_PAINT` with `INTERACTION_TO_NEXT_PAINT`.

### Test Coverage

* not needed

## QA Brief

* Go to `Find out how visitors experience your site` Module in the Site Kit dashboard
* Switch to `In the field` tab
* Verify that `Interaction to Next Paint` section is showing without `experimental` label

## Changelog entry

* Remove experimental status/label from "Interaction to Next Paint" in PageSpeed Insights.

**Comment by techanvil** [comment]
IB :white_check_mark:, nice one @zutigrm!

**Comment by tofumatt** [comment]
(Waiting to move to QA because we need a new release to tag this one with.)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The INP field metric of the PSI pagespeed widget is no longer be labeled as "Experimental"
- The metric is always shown with other field metrics
- Ran PageSpeed test again to ensure that the above still applies. 
- Tested main and entity dashboard for PSI
- Tested view only dashboard for PSI 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/e23f1cb1-3615-492a-bc65-cc39795c8a14)
![image](https://github.com/google/site-kit-wp/assets/73545194/304536c9-220a-4c59-950d-218a68537319)
![image](https://github.com/google/site-kit-wp/assets/73545194/82c1fb48-62e2-4cdd-ab4f-88ec9ef125aa)

</details>
