### ISSUE TITLE
Legacy AdSense status migration check raises console error on view-only dashboard

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7074]
## Bug Description

In https://github.com/google/site-kit-wp/issues/5628 we added a migration routine to update legacy AdSense statuses to the new, more meaningful statuses made possible by updates to the API.

This was added to the AdSense module's main widget on the dashboard which is also rendered on the view-only dashboard. Since site and account statuses are stored in module settings which aren't available to non-admin view-only users, this will raise an error.

Fundamentally, this routine should not be invoked for users who cannot manage module settings as they would be unable to persist the new statuses.

## Steps to reproduce

1. Connect AdSense
2. Share AdSense with the Editor role
3. Log in as an Editor and go to the view-only dashboard
4. See console error due to failing adsense settings API request

Note: nothing is broken in terms of user-experience, this is about preventing the action from happening when it shouldn't

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The routine for migrating legacy AdSense statuses should not be invoked for users who cannot manage module settings, including checks using module settings which are the source of the error in this issue

## Implementation Brief

The module settings API request is currently made in the status migration and the `SiteSteps` component within the `DashboardZeroData` component when there is a Zero Data state in the report. To optimize the implementation, follow these steps:

In `assets/js/modules/adsense/components/module/ModuleOverviewWidget/index.js`:

* Update the code to call the `getAccountStatus` and `getSiteStatus` selectors only if it's not a view-only dashboard.
* Modify the code to render the `StatusMigration` component only if it's not a view-only dashboard.

In `assets/js/modules/adsense/components/dashboard/DashboardZeroData.js`:

* Adjust the code to render the `SiteSteps` component only if it's not a view-only dashboard.

### Test Coverage

* No new tests need to be added for this change.

## QA Brief

* Share AdSense Module with view only role.
* Access the view only dashboard.
* No console error should appear regarding `adsense/data/settings` endpoint not being accesible. 

## Changelog entry

* Fix console error from appearing when AdSense is shared with certain user roles.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that on view only dashboard, no console error is appearing.

<details>


https://github.com/google/site-kit-wp/assets/94359491/6c34bbfe-2b43-4ce3-b07c-4c7af339e74b

</details>
