### ISSUE TITLE
Remove `ga4ActivationBanner` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7076]
## Feature Description

Now that the GA4 Activation Banner has been made available to all sites, the feature flag can be removed, along with related code paths that would no longer be reachable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ga4ActivationBanner` feature flag should be removed such that conditions that use it should keep the code path where the flag is `true`
* Any other references to the flag should be removed, except the changelog

## Implementation Brief

* **Removal from Feature Flags**: Remove the `ga4ActivationBanner` from the `feature-flags.json` file.
* **Code Search and Review**: Conduct a thorough search throughout the code base for the `ga4ActivationBanner` string. Examine each instance where it is used.
    * For any logic or component that was rendered conditionally based on the `ga4ActivationBanner` feature flag, adjust the code to ensure these are rendered unconditionally.
    * Any code segments that were executed only when the feature flag was disabled should now be completely removed.
* **Removal of Hook Usage**: Search for and remove any instances where the `useFeature` hook is utilized with `ga4ActivationBanner` as an argument.
* **Story Parameters Update**: Scrutinize the story parameters in which the `ga4ActivationBanner` feature is activated. Here, it is necessary to remove this particular parameter.

### Test Coverage
* **Visual Regression Test (VRT) and End-To-End (E2E) Tests**: Review and update the VRT images and E2E tests as required to ensure they align with the new changes.

## QA Brief

* Verify the GA4 Activation Banner still appears on both the Main and Entity Dashboard.
* The easiest way to trigger the banner is to setup Site Kit and connect both GA4 and UA. Then, delete `googlesitekit_analytics-4_settings` from the options table in the database.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The GA4 Activation Banner still appears on both the Main and Entity Dashboard.

**Additional testing:**

- Checked the tester plugin to ensure that the feature flag no longer appears. 
- Checked that the GA4 Activation Banner continues to work as expected:
   - Created a new GA4 property and web stream
   - Selected a previously created GA4 property.
- Checked to make sure that the GA4 Activation Banner does not appear on the view only dashboard.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/530208a6-c277-4f94-85f1-b5258b2d1be3)
![image](https://github.com/google/site-kit-wp/assets/73545194/b818f4f9-50ca-4589-9567-d8d79e3f0a02)
![image](https://github.com/google/site-kit-wp/assets/73545194/3752698d-4f0a-40f3-b630-768ebf98c0a2)

</details>
