### ISSUE TITLE
Missing `$item` properties within `auto_update_plugin` filter

### ISSUE THREAD

**Issue by DaWolfey** [google/site-kit-wp#7086]
## Bug Description

This is related to https://github.com/google/site-kit-wp/issues/6624 where I have identified that a plugin called wp fail2ban (https://wordpress.org/plugins/wp-fail2ban/) throws errors when this plugin is enabled. It appears related to issue 6624 in that it is related to the object that is passed into the hook.

It appears that the object that is passed in is missing the "slug" parameter.

## Steps to reproduce

Install both google sitekit and wp-fail2ban in Wordpress. In wp-admin, errors appear at the top of the page which are:
```
Warning: Undefined property: stdClass::$slug in /wp-content/plugins/wp-fail2ban/lib/update.php on line 28
```

The line of code referenced there is a comparison with $item->slug

## Additional Context

 - PHP Version:  8.1
 - Wordpress: 6.2.2

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The plugin data (`$item`) passed to `wp_is_auto_update_forced_for_item` should be an object including all of the keys that are expected to be present in core. See examples: [plugins page](https://github.com/WordPress/WordPress/blob/d4c39df30839133f3b9a46b01a229233d8f99f10/wp-admin/includes/class-wp-plugins-list-table.php#L203-L234), [site health](https://github.com/WordPress/WordPress/blob/d4c39df30839133f3b9a46b01a229233d8f99f10/wp-admin/includes/class-wp-debug-data.php#L1010-L1032)
	* Essentially, this is plugin data (from headers) combined with update data from API, but all keys should be present

<details>
<summary>Example object from plugins page</summary>

```
stdClass Object
(
    [id] => w.org/plugins/google-site-kit
    [slug] => google-site-kit
    [plugin] => google-site-kit/google-site-kit.php
    [new_version] => 1.101.0
    [url] => https://wordpress.org/plugins/google-site-kit/
    [package] => https://downloads.wordpress.org/plugin/google-site-kit.1.101.0.zip
    [icons] => Array
        (
            [2x] => https://ps.w.org/google-site-kit/assets/icon-256x256.png?rev=2181376
            [1x] => https://ps.w.org/google-site-kit/assets/icon-128x128.png?rev=2181376
        )

    [banners] => Array
        (
            [2x] => https://ps.w.org/google-site-kit/assets/banner-1544x500.png?rev=2513620
            [1x] => https://ps.w.org/google-site-kit/assets/banner-772x250.png?rev=2513620
        )

    [banners_rtl] => Array
        (
        )

    [tested] => 
    [requires_php] => 
    [compatibility] => stdClass Object
        (
        )

    [requires] => 5.2
    [update-supported] => 1
    [Name] => Site Kit by Google
    [PluginURI] => https://sitekit.withgoogle.com
    [Version] => 1.101.0
    [Description] => Site Kit is a one-stop solution for WordPress users to use everything Google has to offer to make them successful on the web.
    [Author] => Google
    [AuthorURI] => https://opensource.google.com
    [TextDomain] => google-site-kit
    [DomainPath] => 
    [Network] => 
    [RequiresWP] => 5.2
    [RequiresPHP] => 5.6
    [UpdateURI] => 
    [Title] => Site Kit by Google
    [AuthorName] => Google
)
```

</details>

## Implementation Brief

* To provide comprehensive data, merge plugin API data with the existing header data in `includes/Core/Util/Auto_Updates.php`
* Implement a new method, `get_sitekit_update_data`, to fetch data from site transient or resort to fallback data when transient data is unavailable:
    * Set a default data fallback by initializing a variable, say `$sitekit_update_data`
      * You can get the list of defaults from [here](https://github.com/WordPress/WordPress/blob/d4c39df30839133f3b9a46b01a229233d8f99f10/wp-admin/includes/class-wp-plugins-list-table.php#L217-L230)
      * For the `slug` and `plugin` keys utilize `dirname( GOOGLESITEKIT_PLUGIN_BASENAME )`
      * Use `'w.org/plugins/' . $slug` for the `id` key
    * Retrieve transient data with `$plugin_updates = get_site_transient('update_plugins');`
    * Identify the location of plugin data within transient data:
      * Check `$plugin_updates->response[GOOGLESITEKIT_PLUGIN_BASENAME]` and `$plugin_updates->no_update[GOOGLESITEKIT_PLUGIN_BASENAME]` for data.
      * If plugin data is located, return it (ensure it's cast to an `array`). Otherwise, use the fallback data from `$sitekit_update_data`
* Within the `sitekit_forced_autoupdates_status` method
  * Obtain the plugin update details using the `get_sitekit_update_data` method 
  * Merge this data with `$sitekit_plugin_data` prior to it being included as param in the `wp_is_auto_update_forced_for_item` function

### Test Coverage

* No test updates needed

## QA Brief

* Follow the Steps to reproduce and ensure that the error messages no longer appear.
* Additionally, follow the QAB for #5853 for any regressions as these code changes could affect this functionality.
* Finally, install an older version of the Site Kit plugin from the bottom of the page using this [link](https://wordpress.org/plugins/google-site-kit/advanced/). Refresh the WP Admin Dashboard and ensure that there are no errors and the Site Kit plugin shows that it has an update available.
  * Update the plugin manually and verify everything works without any errors.
  * Repeat the above step, ie. install an older version of the plugin. Now enable plugin auto-updates for Site Kit on your site and verify that the plugin is auto updated. This will take up to half a day to trigger. Alternatively, try manually triggering the WP cron job which triggers the auto update script. Append `/wp-cron.php?doing_wp_cron` to the end of your test site URL in the address bar of the browser. E.g. `http://sitekit.10uplabs.com/wp-cron.php?doing_wp_cron`

## Changelog entry

* Fix a potential PHP warning due to missing properties in plugin update data.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The error messages appear using the `fail2ban` plugin on latest release. 
- Error messages no longer appear on the develop branch. Issue fixed. 
- Went through the QAB on the ticket identified.  Can confirm that the `Keep Site Kit up-to-date` banner appears. Went through all the scenarios as a smoke test and found no issues. 
- Went through the QAB steps using an older version of the plugin. Made sure that the notification appears in the plugins informing of an update.  Ran cron job and Site Kit was automatically updated. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/2ee6c9ff-fcae-433c-ba91-8b2f8f6a4789)
![image](https://github.com/google/site-kit-wp/assets/73545194/656e4591-7055-4c0e-bce1-ae16cb6b7fe7)

</details>
