### ISSUE TITLE
Four steps showing for secondary admin if only GA4 is connected

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7106]
## Bug Description

If Primary admin already connected, the analytics and analytics have only Ga4 property. Then in this case when secondary admin who don't have access to analytics a/c when tries to set up Analytics then set up shows 4 steps instead of 3. 
**Note:** This issue not appears on existing sites having UA + GA property. It appears for only new site having only ga4 property. If we removed existing UA properties then also this not appears for existing site.

## Steps to reproduce

1. Create new site.
2. Make sure 'ga4Reporting' feature flag is enabled.
3. Set up Analytics without UA through primary Admin.
4. Now login as Secondary admin.
5. Set up Site Kit with google a/c which doesn't have access to analytics.
6. Notice set up screen showing 4 steps instead of 3

## Screenshots

https://github.com/google/site-kit-wp/assets/94359491/04f6d29e-27a9-4d43-9e14-4f17e6fcfecc

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
I did spent some time looking into this, but ultimately realised I don't have enough visibility on what the service is doing behind the scenes in these stages to provide a well informed opinion on what's possible and desirable here.

It does seem that, although we might want to keep all of the stages, it could be appropriate to at least update the wording when a secondary admin is setting up.

I'd image that @eugene-manuilov or @aaemnnosttv should have a bit more insight on this one.

**Comment by eugene-manuilov** [comment]
@techanvil @mohitwp, the problem here is that, on the service side, we don't know whether the site is still connected or not. We can't check it there and have to display the same steps for the first user that connects the same and for all other users that just want to sign in.

I think what we can do here, is to introduce a new query parameter that we will use when we redirect users to the service sign-in pages to indicate whether the site is already connected or not. Then based on that information, we will be able to adjust steps or wording there. 

@aaemnnosttv, what do you think?

**Comment by jimmymadon** [comment]
@mohitwp Tried to reproduce this again locally and on a completely new site following the Steps to reproduce, ie. logging into a new site with another admin who does not have permission to the original admin / site's Analytics account. We do correctly get 3 steps now. So closing this issue.

<Details>
<Summary>Screenshots and recordings:</Summary>

<img width="1800" alt="Admin1Login" src="https://github.com/google/site-kit-wp/assets/1721319/8d83b845-b407-458a-8d04-44337bebdf23">

https://github.com/google/site-kit-wp/assets/1721319/ae79b335-cb97-4433-b25a-bc4b9dacc21a

</Details>

c.c. @techanvil @eugene-manuilov
