### ISSUE TITLE
Retry button appears under offline mode while editing settings for tag manager.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7110]
## Bug Description

When I edited settings for Tag manager and set selected the offline mode under network tab then error message appearing with "Retry" button. Updating the settings to not throttle at all and clicking on 'Retry' button do not trigger any process. Under other module settings, this retry button is not showing. 

## Steps to reproduce

1. Go to the settings page and edit tag manager module settings.
2. Open your browser dev tools and select the Offline mode in the throttling settings on the Network tab.
3. Now save module settings and ensure that you see an error that says that you are offline.
4. Along with error message 'Retry; button will appear under Tag manager settings.
5. Then update the throttling settings to not throttle at all and save your module settings again.
6. Click on 'Retry' button. It will not trigger any event. 

## Screenshots

https://github.com/google/site-kit-wp/assets/94359491/989b08a8-034c-40c5-8a19-b53572726900

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for raising this @mohitwp. I can see how this may seem inconsistent but it's actually correct. The retry button should appear for actions which don't already have a dedicated button to invoke them (e.g. saving settings – when this request fails, no retry is shown as you said).

For GTM, when you select an account, or a container, an additional request is made (either to get the containers for an account, or to check the tags within it, respectively) so the retry is about this action which failed, which does not have an existing dedicated button to retry, so it's correct.
