### ISSUE TITLE
Add which dashboard is in use to Site Health Information

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#7119]
## Feature Description

As discussed previously with @aaemnnosttv it would be useful for the support team to be able to see which version of the dashboard users have activated via the users Site Health Information after GA4 reporting rollout. 

This is currently displayed with a label on the dashboard to users but would be even more helpful for troubleshooting and save some time to have this information in Site Health. 

Add a dashboard section to the Site Health Info specifying if the user is using the UA or GA4 dashboard. 

## Acceptance criteria

* The Analytics dashboard view setting should be exposed in the module's debug data
    * The display values should be translatable strings, that match those shown in the `DashboardViewIndicator`
    * The debug value should be the raw setting value
* The field should only be present if `ga4Reporting` is enabled
* The field should be the first for the module, matching the order on the settings views

## Implementation Brief

- In `includes/Modules/Analytics.php`:
  - Update the `get_debug_fields()` method:
    - Instead of returning the array, assign it to a new variable, say `$fields`. Return `$fields` at the end.
    - Add a new key to the first of the array named `analytics_dashboard_view`. Similar to other items, its value should also be an array with the following items:
      - `label`: `Analytics dashboard view` (translatable).
      - `value`: If `$settings['dashboardView']` is `google-analytics-4`, it should be `Google Analytics 4 view`. Otherwise, it should be `Universal Analytics view`. The string should be translatable.
      - `debug`: It should use the raw value of `$settings['dashboardView']`.
  - Before returning the `$fields` variable, check if the `ga4Reporting` feature flag is enabled (using `Feature_Flags::enabled()`). If not, `unset` the `analytics_dashboard_view` key from the `$fields` array.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

- Site up Site Kit with Analytics, but without the `ga4Reporting` feature flag.
- Go to WordPress Dashboard -> Tools -> Site Health -> Info. Verify that there is no information labelled `Analytics dashboard view`.
- Activate the `ga4Reporting` feature flag.
- Go to Site Health info again and verify that `Analytics dashboard view` exists and its value is `Universal Analytics view`.
- From Analytics module settings or dashboard notification prompt, change the dashboard view to GA4.
- Go to Site Health info again and verify that `Analytics dashboard view` exists and its value is `Google Analytics 4 view`.
- For each of the above tests, verify that clicking `Copy site info to clipboard` copies the raw dashboard view value for the `Analytics dashboard view` setting, e.g. `universal-analytics` or `google-analytics-4`.

## Changelog entry

* Add the Analytics dashboard type to Site Health information.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When the GA4Reporting feature flag is disabled, the dashboard view does not appear in the Site Health info. 
- When the GA4Reporting feature flag is anbled:
   - In Site Health info Analytics dashboard view exists and its value is Universal Analytics view.
   - Change the dashboard view to GA4 and its value is Google Analytics 4 view.
- For each of the above tests, when clicking Copy site info to clipboard copies the raw dashboard view value for the Analytics dashboard view setting, e.g. universal-analytics or google-analytics-4.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/66bc6d2f-af1e-40b9-97b5-ea622a7de961)
![image](https://github.com/google/site-kit-wp/assets/73545194/c4dc775f-4f6b-439e-807a-7a0fcabaf2c4)
![image](https://github.com/google/site-kit-wp/assets/73545194/bc34ea6f-f40a-45d1-a473-d39039c2852b)
![image](https://github.com/google/site-kit-wp/assets/73545194/d8b7ff92-fe53-4cb5-900e-8ac90e4f715a)

</details>
