### ISSUE TITLE
Fix console error thrown while using GTranslate widget and logged into website as admin.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7121]
## Bug Description

This is a followup to fix the support issue captured in https://github.com/google/site-kit-wp/issues/5969.

## Steps to reproduce

See the steps to reproduce on https://github.com/google/site-kit-wp/issues/5969, although note that I had to install an older version of the theme to get the **Show in menu** option to show anything (I switched to the Twenty Twenty-One theme).

## Screenshots

This is the snippet of code provided via GTranslate that throws the error.

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/ab16a746-690b-401e-a7c1-de057c5a82b2)

The argument it's invoked with can be seen here:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/3e24b326-fe57-4313-88d4-3ecadee886e6)

And, the contemporaneous state of `window.google` can be seen here:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/2f01919d-0a52-4bda-8ee1-93200bd881f6)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: historical, but verified on 1.101.0
 - Device: any

As can be seen in the screenshots above, the code is throwing an error because it's trying to deeply reference an object on `window.google`, but `window.google` is `undefined`.

It appears that this conflict is occurring as a result of Site Kit's code where it intentionally initializes `window.google` to `undefined`:

https://github.com/google/site-kit-wp/blob/61a99f5ce7f0291e0095687dbda2ee0cd34223c7/assets/js/util/initialize-google-global.js#L19-L21

This itself was deliberately introduced as a result of https://github.com/google/site-kit-wp/issues/4074, so care needs to be taken not to reintroduce a problem with regard to this issue.

Preliminary investigation suggests a fix could be to initialize `window.google` to an empty object, rather that `undefined` - this appears to work both with GTranslate and with Site Kit's own Google Charts. However, this needs to be thoroughly investigated for viability.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should not prevent Google Translate from functioning
* This includes integrations via the official browser extension, and the GTranslate plugin

Note: there are known stability issues with Google Translate related to React crashing due to DOM changes made by Google Translate – this is a separate issue which is out of scope here. This issue is specific to allowing Google Translate to function at all on the page when SK is present/active

## Implementation Brief

* Locate the file at `assets/js/util/initialize-google-global.js`
* Update the value of `global.google` within the condition to be `{}` as opposed to `undefined`
* The final block of code should look as follows:
```
if ( ! Object.prototype.hasOwnProperty.call( global, 'google' ) ) {
	global.google = {};
}
``` 

### Test Coverage
* No additional tests required.

## QA Brief

* Install GTranslate chrome extension and WordPress plugin - https://en-gb.wordpress.org/plugins/gtranslate/
* Open dashboard, verify gtranslate extension works
* Open website, and some page on frontend, and verify that gtranslate extension is translating page (working)
* To test gtranslate plugin, you can add shortcode `[gtranslate]` into any page, and verify the gtranslate widget shows on that page and translation works
* It would be also worth giving this a test with the Google Translate extension as well as GTranslate.
* Lastly, it would also be worthwhile doing a regression test on the behaviour fixed in https://github.com/google/site-kit-wp/issues/4074 as mentioned in the bug description.

## Changelog entry

* Fix console error thrown while using Site Kit in conjunction with Google Translate.

**Comment by aaemnnosttv** [comment]
Note: after further investigation, this error also happens with the Google Translate browser extension which is likely more widely used than the GTranslate plugin.

**Comment by aaemnnosttv** [comment]
@bethanylang this one is ready to start moving as soon as we have the capacity.

**Comment by aaemnnosttv** [comment]
@bethanylang can we prioritize this one in the near future?

**Comment by bethanylang** [comment]
@aaemnnosttv Sure, I can ask someone to pick this up for IB so I can try to get it into the next sprint – will depend on what kind of launch blockers we have from the KMW Bug Bash, though. Thanks!

**Comment by 10upsimon** [comment]
I've not identified a need for any Test Coverage additions herein, please let me know if anyone is in disagreement with this. Existing tests should fail (unit and/or visual) should the change have any negative side effects.

**Comment by bethanylang** [comment]
@10upsimon Can you please add an estimate here? Thanks much!

**Comment by techanvil** [comment]
Hi @10upsimon, thanks for your further investigation on this one.

As discussed on Slack, it does sound likely that the case whereby you manually construct a chart via the JS console is not really representative of a real-world scenario, particularly as you've noted that copying the same code into the page body does not result in an error. That said, if you do have those snippets to hand and can paste them here, I'd be interested to see the code just for a clearer picture of things.

I'm also interested to know if you've verified the proposed fix works when using the Google Translate extension in addition to G Translate, it would be good to have this assurance that it's a general purpose fix.

With regard to your question about testing, I'd agree, this isn't a case that we need to add any additional test coverage for. Our existing tests should provide coverage for general chart rendering, and it's probably not worth adding an E2E test for the integrated case with Google Translate.

**Comment by 10upsimon** [comment]
@techanvil I can confirm that using the Google Translate Extension is a success as well as using the GTranslate plugin. Both work when the default/fallback value is updated to `{}`;

As for the snippet I was inserting, here it is:

```
const script = document.createElement('script');
script.src = 'https://www.gstatic.com/charts/loader.js';
document.body.appendChild( script );

function drawChart() {

        // Create the data table.
        var data = new window.google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['Mushrooms', 3],
          ['Onions', 1],
          ['Olives', 1],
          ['Zucchini', 1],
          ['Pepperoni', 2]
        ]);

        // Set chart options
        var options = {'title':'How Much Pizza I Ate Last Night',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new window.google.visualization.PieChart(document.getElementById('wpbody'));
        chart.draw(data, options);
      }

script.onload = () => {
    console.log('Script loaded successfuly');
    // Load the Visualization API and the corechart package.
    google.charts.load('current', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);
};
```

Here are the console errors that arise (in the SK dashboard) as a result:

<img width="705" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/b1af9a50-0211-4a57-91fe-485279cb7de1">

It is an odd error given that `new` is clearly used in the code, but I also suspect this is somewhat totally disconnected to the SK app and somewhat irrelevant, it was merely an observation while testing.

**Comment by 10upsimon** [comment]
I've update the issue with estimate of 3, given that the change itself is minimal, as would be the QAB.

**Comment by 10upsimon** [comment]
Thank you @techanvil , I've updated to state that no additional tests are required, as IMO they do not seem warranted. Handing this over for IBR.

**Comment by techanvil** [comment]
Thanks @10upsimon! IB LGTM :white_check_mark:

**Comment by techanvil** [comment]
Hey @zutigrm, this looks good and I've merged the PR. I've also added a couple of additional points to the QAB myself, in order to spare a round trip and move this along to the QA column.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Installed GTranslate chrome extension and WordPress plugin verified the  extension works.
- Visited a page on frontend, and the gtranslate extension is translating page.
- Tested gtranslate plugin, you can add shortcode [gtranslate] into any page, and the gtranslate widget shows and translation works.
- Tested with the Google Translate extension as well as GTranslate.
- No console or front end error messages.
- Completed a regression test on the behaviour fixed in https://github.com/google/site-kit-wp/issues/4074

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/9d51dbda-8446-4ae6-b76e-e933e9f75e97)
![image](https://github.com/google/site-kit-wp/assets/73545194/3bd17ced-3e24-4020-b2e0-bb5d24f18073)
![image](https://github.com/google/site-kit-wp/assets/73545194/db433842-7603-49a2-a7d4-92291017fee3)
![image](https://github.com/google/site-kit-wp/assets/73545194/98bdb18f-7fce-442d-af93-1d1c35344a2c)
![image](https://github.com/google/site-kit-wp/assets/73545194/1eeae06d-bfd8-47d1-8f1b-d2bc0cab4373)

</details>
