### ISSUE TITLE
“Unsupported dimension” API error on view only dashboard and when secondary admin having access to Ga4 clicks on Locations and Devices tab a

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7132]
## Bug Description

"Unsupported dimension" API error on view only dashboard and when secondary admin having access to Ga4 clicks on Locations and Devices tab.
## Steps to reproduce

1. Enable Ga4Reporting.
2. Set up analytics with primary admin using google a/c A.
3. Log in as secondary admin.
4. Set up SK using google a/c A.
5. Go to Main dashboard.
6. Click on Devices or Locations tab.
7. See error.

or 

1. Go to view only dashboard.
2. Click on Devices or Locations tab.
3. See error.

## Screenshots

https://github.com/google/site-kit-wp/assets/94359491/809042b4-46a3-4cb1-8aef-00028c22d584

![image](https://github.com/google/site-kit-wp/assets/94359491/a8c5ee75-0ca0-4024-973a-0f3e642ccf28)

![image](https://github.com/google/site-kit-wp/assets/94359491/00dae8ba-365d-4762-91c2-e0f5458a4b7d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* View only users with access to GA should be able to view all tabs of the All Traffic widget's  Pie chart

## Implementation Brief

* Add `country` and `deviceCategory` allow-list of shared dimensions
* Merge https://github.com/google/site-kit-wp/pull/7135

### Test Coverage

* No changes necessary

## QA Brief

* This is very easy to test by following steps to reproduce above
* As a view-only user, make sure each tab of the all traffic pie chart can be activated

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
QA'd this during code review, since it's a small QA job and this is for the release in a very short period of time, marking this as QA ✅

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt & @mohitwp 👍 
cc: @wpdarren
