### ISSUE TITLE
Remove `gteSupport` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7137]
## Feature Description

Now that `gteSupport` is available to all sites and the flag is no longer needed, it should be removed entirely.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `gteSupport` feature flag should be removed such that conditions that use it should keep the code path where the flag is `true`
* Any other references to the flag should be removed, except the changelog

## Implementation Brief

- Search the codebase for `gteSupport` and strip out all usage of the feature flag, retaining only the code paths that would be taken if it were `true`.
- As can be seen in this exploratory [commit](https://github.com/google/site-kit-wp/pull/7174/commits/9519247f9abd72a6aed6dd6d2922a22a7b8dcfe8) this is pretty straightforward and involves updating about 13 files.
- Tidy up related code - follow up on this TODO comment in `tags.test.js`: https://github.com/google/site-kit-wp/blob/0cb10a8cbaa744f3da31d7662cc13314f82eb5f0/assets/js/modules/analytics-4/datastore/tags.test.js#L27-L28
- Apply [this fix](https://github.com/google/site-kit-wp/pull/7174/commits/4ff8cef29fc81ff651ecfa6ebd7ca9e8d145ac86) to allow the E2E tests to run. This short-circuits a recursive loop that would otherwise blow up the PHP stack in E2E test runs, due to the now-unconditionally applied `googlesitekit_auth_scopes` filter hook in `includes/Modules/Analytics_4.php` and its indirect relationship to the `get_user_option_googlesitekit_auth_scopes` filter hook in `tests/e2e/plugins/gcp-auth.php` and `tests/e2e/plugins/proxy-auth.php`.
  - More specifically, the recursive loop is as follows: The `get_user_option_googlesitekit_auth_scopes` hook calls `get_required_scopes()`, which calls the `googlesitekit_auth_scopes` filter hook, which calls `has_sufficient_scopes()`, which calls `get_granted_scopes()`, which results in a call to the `get_user_option_googlesitekit_auth_scopes` filter hook, and so on.
  - The fix, applied to both `get_user_option_googlesitekit_auth_scopes` filter hooks, is to check the global `$wp_current_filter` array to see if it contains more than 1 instance of the string `'get_user_option_googlesitekit_auth_scopes'`. If so, it means the filter hook has been re-entered in a recursive call, in which case we return `null` rather than calling `get_required_scopes()` again in order to prevent further recursion.
    - Note that `null` is not a magic value here, any falsy value should suffice and be handled appropriately by the [caller](https://github.com/google/site-kit-wp/blob/4ff8cef29fc81ff651ecfa6ebd7ca9e8d145ac86/includes/Core/Authentication/Clients/OAuth_Client_Base.php#L211-L213).
- The lion's share of the work will be in fixing up the various tests that will start to fail as a result of the above steps.
  - As can be seen from the CI checks for the exploratory [PR](https://github.com/google/site-kit-wp/pull/7174), there will be on the order of:
    - 40 failing JS tests across 8 suites.
      - It looks like there are 4 common sets of error messages/failure reasons for these failing tests.
    - 1 failing PHP test.
    - 7 E2E tests failing across 4 suites.
      - It looks like there are 2-3 different errors depending on how one interprets them.
  - Although there are common errors which suggest common fixes can be applied to many tests, the individual tests still need to be evaluated on a case-by-case basis to determine whether they remain correct tests to be fixed, or may need to be merged with another test or simply removed.

### Test Coverage

* Tests should be fixed/merged/removed as described above.

## QA Brief

- Perform a regression test of the plugin. This could include a general smoke test, a more in-depth focus on Analytics-related features, and a run through of the [GTE Bug Bash instructions](https://app.asana.com/0/1203993135029815/1204174775213831) (except where there's a reliance on toggling the `gteSupport` feature flag, of course).

## Changelog entry

* N/A

**Comment by bethanylang** [comment]
Heads up that I'm going to remove this from this sprint since it's quite large and would put us over capacity when we have other more critical issues that are still waiting for estimates. Will include in an upcoming sprint!

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Ran GTE bug bash instructions.
- Verified analytics functionality.
- Verified that additional permissions to detect updates to tags on site is not showing now on dev environment.
- Analytics set up working as expected.
