### ISSUE TITLE
Optimize sunset banner re-appears on Dashboard after dismissal 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7138]
## Bug Description

The Optimize sunset banner appears on the dashboard even though it has been dismissed.  

It only appears for a split second, and it is difficult to see even with slow 3G. Thought it was worth raising.  I was able to recreate it with `GA4Reporting` enabled and disabled.  

https://github.com/google/site-kit-wp/assets/73545194/68edc564-0cf3-42ac-8ac5-b6f2c4abe83f

## Steps to reproduce

1. Set up Analytics and Optimize 
2. Go to the main dashboard and notice the Optimize sunset banner
3. Dismiss the banner notification.
4. Refresh the dashboard.  When I initially tested this the banner didn't appear, so you might want to leave the dashboard (go to settings) and then come back and you'll see the banner very quickly load as per screencast above. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Optimize removal banner should not appear if it has been dismissed

## Implementation Brief

* Update the condition to return early in the `OptimizeRemovalNotification` to return if `isDismissed` is not strictly `false` as this can be `undefined` while dismissed items have not been resolved yet which is why the banner shows briefly (this is only observable when the client-side dismissed item is not present in session storage – i.e. the non-persistent dismissal)
https://github.com/google/site-kit-wp/blob/394732a0df9f4ad9c1524a318ece3257224ac9f9/assets/js/components/notifications/OptimizeRemovalNotification.js#L54

### Test Coverage

* No changes needed

## QA Brief

* Ensure that the Google Optimize module is enabled, on a fresh setup of Google Site Kit.
    * If using an existing install where the banner has already been dismissed, the tester may remove the user meta key named `wp_googlesitekitpersistent_dismissed_items` inside of the `wp_usermeta` table of the WordPress database, applicable to their user ID. Although this is the least preferred method, it will clear any item dismissal states to date and unlock testing of this fix.
* Validate that once Optimize is enabled, the Optimize sunset banner appears within the Site Kit dashboard.
* Validate that, once dismissed, the Optimize sunset banner no longer appears.
    * This can be validated using slow network simulation within Google Chrome as well, i.e fast 3G or slow 3G

## Changelog entry

* Fix the Optimize sunset banner re-appearing issue.

**Comment by chirag1718** [comment]
Hello I find this interesting and I would like to resolve this issue.

**Comment by bethanylang** [comment]
Hi @chirag1718! Someone on our internal team has already picked this up, but please do feel free to take a look at other issues if you'd like.  :)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Once Optimize is enabled, the Optimize sunset banner appears within the Site Kit dashboard.
- Once dismissed, the Optimize sunset banner no longer appears.
   - I validated by refreshing the Site Kit dashboard and the banner does not appear. 
   - I also validated by navigating away from the dashboard, ie. going to settings and revisiting the dashboard.
