### ISSUE TITLE
Link colour difference on Site Kit Widget to other widgets on WP Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7139]
## Bug Description

The links on the Site Kit widget on WP Dashboard are different than other widgets. 

I do remember that the links were blue until fairly recently, and remember a conversation back when we were working on GM2+ that the styles should remain the same as the other widgets.  When completing the release testing, it jumped out at me, and it doesn't seem to be a regression so could have existed for a while. 

I do feel we should change the link colour from `#108080` to `#2271b1`

From a conversation with Tom it does look like a CSS change in 1.89.0 that could have impacted the links here. 

![image](https://github.com/google/site-kit-wp/assets/73545194/938495d3-e3ba-4bc9-968d-6f6cc880ace1)

## Steps to reproduce

1. Set up Site Kit with a site that has traffic and real data. 
2. Go to the WP Dashboard and observe font colour differences between Site Kit Widget and others. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Links in WordPress dashboard widgets added by Site Kit should use the same text colour as links in core dashboard widgets.
* The link colour also should change based on the admin colour scheme chosen by the WordPress user in their profile.

## Implementation Brief

* Since there is no available CSS variable [yet](https://core.trac.wordpress.org/ticket/49930), for applying the WP core admin color, and it can change based on the user selected color palette - a small tweak for the link CTA should be done in CSS.
* [x] Update `assets/sass/components/global/_googlesitekit-cta-link.scss`
  * Under `.googlesitekit-cta-link`, move the `color` property and `hover` [styles](https://github.com/google/site-kit-wp/blob/e05000d07f7b838701a99422b49ece9236dd3387/assets/sass/components/global/_googlesitekit-cta-link.scss#L35-L42), under new selector `.googlesitekit-page &`. So that color is applied only on Site Kit pages, and dashboard widgets will adapt the proper WP core link color

### Test Coverage

* Update any failing VRT reference images

## QA Brief

* Ensure the GA Module is enabled
* Navigate to the WordPress dashboard, you will see the links in the widget here match the WP admin theme link color.

## Changelog entry

* Link colour difference on Site Kit Widget to other widgets on WP Dashboard.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The WordPress dashboard, you will see the links in the widget match the WP admin theme link color.
- Tested different Admin Color Schemes to make sure links in the widget match the WP admin theme link color.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/cc5f1b62-46a0-4fef-b36a-9fe992168fc2)
![image](https://github.com/google/site-kit-wp/assets/73545194/c43ff8af-5415-4bb7-a1e1-18324e0f3734)

</details>
