### ISSUE TITLE
Restore notice max-width in setup and settings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7140]
## Bug Description

In #6956 we made a change to the styling of `SettingsNotice` to address an inconsistency with the design when used on the dashboard, but this introduced an unintended change in the other usages in setup and settings contexts where the notice streches full-width where it should be constrained as before.

## Screenshots

**Before**
<img width="1724" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/78bb6d4c-0f7c-472d-a2b7-e658b71c235e">

**Currently**
<img width="1713" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/28b02c39-a7f4-4038-81a8-2d9ac321388f">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The max-width of inline notices (as seen above) that are not used on the SK dashboard should be consistent with their pre 1.102.0 styling and a max-width of `1098px`

## Implementation Brief

* Restore `max-width` to `.googlesitekit-settings-notice` https://github.com/google/site-kit-wp/pull/7029/files#diff-27e3b435235c488b77baee4a111d58b139b417c5923015e3fcdd8f53a386ecd7L28 using `$max-width-settings-notice-content`, but scoped only to settings notices that are children of the Settings/Setup views, eg: `.googlesitekit-setup-module .googlesitekit-settings-notice` and  `.googlesitekit-setup .googlesitekit-settings-notice`

### Test Coverage

* No new tests needed, but VRTs may need updating.

## QA Brief

- Verify that the notices shown in the Site Kit settings and setup screens are not full-width, they should have a max-width of 1098 pixels.
- Verify that notices shown in the Site Kit dashboard, e.g. Adsense Top Earning Pages widget with Analytics setup with GA4 only and `ga4Reporting` feature flag are full-width and do not have a max-width.

## Changelog entry

* Restore notice width in setup and settings views.

**Comment by tofumatt** [comment]
This should be a quick one to implement and QA, so marking it as a 3 estimate.

**Comment by aaemnnosttv** [comment]
@tofumatt would this style be scoped to settings & setup views only? We wouldn't want to impose the same limitation on the dashboard or we'd be undoing the intentional change we made there :)

**Comment by tofumatt** [comment]
@aaemnnosttv Argh, yes, you're totally right. I even did that when testing locally but forgot to include it in the IB. I think the provided selectors make sense, they're what I used when I tried it locally.

**Comment by techanvil** [comment]
I just want to comment to say, I personally feel like this is something we'd be estimating as a 3 _before_ the points experiment, as we had agreed a 1 would only be for super trivial things - this seems a bit more with multiple component instances to check and possible VRT updates etc.

Just chipping in because I think we need to be careful not to slip back toward our old estimations having put the experimental phase behind us...

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – SGTM, I would think this one should be doable as estimated even with VRT, but I agree that it doesn't leave much room for potential complications; 7 it is!

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The notices shown in the settings and setup screens are not full-width, and have a max-width of 1098 pixels.
- Notices shown in the dashboard, e.g. Adsense Top Earning Pages widget with Analytics setup are full-width.
- Tested to make sure there are no UI/UX issues with the notices mentioned above on mobile devices. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/d5f75a78-d8bd-4ee9-a28c-bfb2306759e4)
![image](https://github.com/google/site-kit-wp/assets/73545194/412f8986-fe8d-47c3-bccd-b8c7f6096902)
![image](https://github.com/google/site-kit-wp/assets/73545194/c247cc71-9e47-4a5e-a23f-7e69b782a28c)
![image](https://github.com/google/site-kit-wp/assets/73545194/2014fdc6-9ab1-48b7-8baf-9e5cb04f4ac4)
![image](https://github.com/google/site-kit-wp/assets/73545194/9350a8ee-d6ba-4a51-af3d-4ef11e863668)
![image](https://github.com/google/site-kit-wp/assets/73545194/885b8a8c-270e-44b6-a0f7-09d138d961e6)
![image](https://github.com/google/site-kit-wp/assets/73545194/b9fcead7-cf40-487a-82e7-1e9eac1cfd11)
![image](https://github.com/google/site-kit-wp/assets/73545194/2094c1d8-4188-41e3-a6f3-e5db8f2beb25)
![image](https://github.com/google/site-kit-wp/assets/73545194/b1d8a187-6857-4395-beef-d97498560b96)

</details>
