### ISSUE TITLE
Remove `keyMetrics` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7144]
## Feature Description

Once available to all sites, the `keyMetrics` feature flag should be removed, replacing the conditional functionality it controlled with the guarded code unconditionally.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `keyMetrics` feature flag should be removed such that conditions that use it should keep the code path where the flag is `true`
* Any other references to the flag should be removed, except the changelog
* **Before merging a PR for this, please confirm with @aaemnnosttv**

## Implementation Brief

* **Removal from Feature Flags**: Remove the `keyMetrics` from the `feature-flags.json` file.
* **Code Search and Review**: Conduct a thorough search throughout the code base for the `keyMetrics` string. Examine each instance where it is used.
    * For any logic or component rendered conditionally based on the `keyMetrics` feature flag, adjust the code to ensure these are rendered unconditionally.
    * Search for and remove any instances where the `isFeatureEnabled( 'keyMetrics' )` utility function is used.
    * Any code segments executed only when the feature flag was disabled should now be completely removed.
* **Removal of Hook Usage**: Search for and remove any instances where the `useFeature` hook is utilized with `'keyMetrics'` as an argument.
* **Removal from Server Logic**:
    * Search for and remove any instances where the `Feature_Flags::enabled( 'keyMetrics' )` method is used in server logic.
    * Search for and remove any instances where the `enable_feature( 'keyMetrics' )` method is used in PHP test files.
* **Story Parameters Update**: Scrutinize the story parameters in which the `keyMetrics` feature is activated. Here, it is necessary to remove this particular parameter. If there are stories that output content only when `'keyMetrics'` feature is _not_ enabled, they should be removed.

### Test Coverage

* Review and update the VRT images and E2E tests as required to ensure they align with removing the `keyMetrics` feature flag.

## QA Brief

* Ensure all Key metrics logic is still working as it was with feature flag. All key metrics are present and working, and setup key metrics banner shows without feature flag. User input settings, etc. As well as overall plugin functionality

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@bethanylang this is more/less ready, just waiting until we're ready to start the removal to avoid stale definition.

**Comment by tofumatt** [comment]
Looks good, but just for safety around E2E tests and stories I'll bump this to a 19 for planning purposes. I think 15 is probably right but just for some wiggle room 😄

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Smoke tested Key metrics functionality.
- Verified Key metrics functionality for view only dashboard.
- Verified user input flow.
- Verified Key metrics admin settings flow.
- Verified key metrics widget panel and related functionality.
