### ISSUE TITLE
Update Advanced Tracking to work with GA4

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7145]
## Feature Description

In #1728 we introduced an extensible API for registering custom events to track through the connected Google Analytics property. Since then, the infrastructure has not been touched as it was intended for 3rd parties to use.

The API should be compatible with GA4 because the tagging and `gtag` configuration that it extends has not changed with GA4, however the API itself is currently coupled to the UA Analytics tags. If the UA tag/snippet is not enabled/output, then the advanced tracking configuration will not be output. This means that a site with only GA4 tagging or one that has both, but UA toggled off will not get the event configuration it may have had before.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Advanced_Tracking` class is modified to use the `analytics-4` module slug for the init tag actions: https://github.com/google/site-kit-wp/blob/b9c61b60102122e6a661c014bfd9fdb8312af64a/includes/Modules/Analytics/Advanced_Tracking.php#L72 https://github.com/google/site-kit-wp/blob/b9c61b60102122e6a661c014bfd9fdb8312af64a/includes/Modules/Analytics/Advanced_Tracking.php#L84
* The instantiation of the `Advanced_Tracking` class in the `Analytics` module is removed.
* The new initialization and registration of the `Advanced_Tracking` class is added to the `Analytics_4` module.

## Implementation Brief

* In `includes/Modules/Analytics/Advanced_Tracking.php`
  * Replace `analytics` with `analytics_4` in the actions names pointed out in AC 
* In `Google\Site_Kit\Modules\Analytics`
  * Remove instantiation and registration of `Advanced_Tracking`
* In `Google\Site_Kit\Modules\Analytics_4`
  * Include `Advanced_Tracking` instantiation and registration to the `register` method

### Test Coverage

* Update `tests/phpunit/integration/Modules/Analytics/Advanced_TrackingTest.php`

## QA Brief

* Since this is mostly added so third party plugins can use it, there is no specific way to QA on user facing level. So ensure that Advanced Tracking php tests are passing, as they mimic the external usage via the hooks.

## Changelog entry

* Update extensible Advanced Tracking API to work with GA4.

**Comment by tofumatt** [comment]
ACs here sound good, moving to IB 👍🏻

**Comment by techanvil** [comment]
Hi @zutigrm, bearing in mind UA is no longer in use and we're actively removing the Analytics module, we don't need to retain support for the `analytics` module slug. We should take the simpler approach of changing `analytics` to `analytics-4` in the action hook names, and don't need to pass the module slug into the hook callback.

It's also worth bearing in mind the `Advanced_Tracking` class will be moved to `includes/Modules/Analytics-4/Advanced_Tracking.php` via #7926, which I've made a dependency of this issue.

Cc @eugene-manuilov @tofumatt

**Comment by zutigrm** [comment]
@techanvil Thank you for the feedback. Let's verify with @eugene-manuilov if `analytics-4` can be hardcoded in the hooks, as AC is mentioning dynamic names, maybe there is a plan to use this with another module in the future?

**Comment by eugene-manuilov** [comment]
Fair point, @techanvil. I updated AC accordingly. Does it look good to you now?

**Comment by techanvil** [comment]
Thanks @eugene-manuilov! AC LGTM :white_check_mark: 

Back to you in IB @zutigrm :)

**Comment by zutigrm** [comment]
Thank you @techanvil @eugene-manuilov 

IB updated

**Comment by techanvil** [comment]
Thanks @zutigrm, IB LGTM :white_check_mark:

**Comment by bethanylang** [comment]
@zutigrm Ah shucks, I just realized this is blocked by #7926. If you can't move on this one, let me know and I can rustle something else up for you!

**Comment by techanvil** [comment]
Hey @zutigrm, just a heads up that when it comes to writing the QA Brief, in the scenario described here where there are no user facing changes and the only `QA:Eng` task would be to check the tests are passing, we can simply skip QA. The fact of the tests passing should be verified at CR time, plus obviously being automated in CI once the issue is merged. Adding N/A with an explanatory note for the QAB would be sufficient for this issue.

With that in mind, having verified the tests do indeed pass at CR time, I'll move this one straight to Approved.

**Comment by aaemnnosttv** [comment]
## ❌ Approval

The implementation (+ IB) does not satisfy the AC, specifically regarding the value used for the module slug. This was specified in the AC but somehow missed. It should be quick to fix with a follow up.

I also left a comment on the original PR https://github.com/google/site-kit-wp/pull/8007#pullrequestreview-1816744264

**Comment by aaemnnosttv** [comment]
This is good now following the merge of #8074 👍
