### ISSUE TITLE
Fix non-functional `getAnswerBasedMetrics` jest test 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7154]
## Bug Description

Spotted [this](https://github.com/google/site-kit-wp/blob/8fe4cfb0510912af79ff7604b1bd11f717cc5703/assets/js/googlesitekit/datastore/user/key-metrics.test.js#L176-L187) while working on #7153, the linked `it.each` is not behaving correctly as the first parameter is being passed to the function which is a string (the test name). This can be easily verified by logging the value of `userInputSettings` inside the test. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `should return an empty array if user input settings are %s` test of `getAnswerBasedMetrics` should actually be functional - currently, it's passing the `testName` (first parameter) as the user input settings. 
    * The `[ 'undefined', undefined ]` case should be removed, as `receiveGet**` action will [reject](https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/assets/js/googlesitekit/data/create-fetch-store.js#L205) `undefined` as value. 

## Implementation Brief

* In `assets/js/googlesitekit/datastore/user/key-metrics.test.js`:
    * In `getAnswerBasedMetrics` selector test:
        * Remove the `[ 'undefined', undefined ]` from the `it.each` of `should return an empty array if user input settings are %s` test case. 
        * Make the test function `async`. 
        * Take the second parameter of the function as `userInputSettings`. ie. `async ( _, userInputSettings ) => { ... }`.
        * Add a `fetchMute` call for the `coreUserInputSettingsEndpointRegExp` endpoint to the start of the test.
        * Wait for default timeouts using `await waitForDefaultTimeouts()` to suppress any potential fetchMock error on the next tick. 

### Test Coverage

* Ensure that the updated tests are correct and passing. 

### This Requires QA:ENG
- Run the test at `assets/js/googlesitekit/datastore/user/key-metrics.test.js` using the following command:
    - `npm run test:js -- assets/js/googlesitekit/datastore/user/key-metrics.test.js`
    - Validate that all test cases pass.

## Changelog entry

* N/A

**Comment by bethanylang** [comment]
@kuasha420 Can you please add a priority label here? Thanks!

**Comment by tofumatt** [comment]
Yet another reason I loathe `it.` in tests 🤣

ACs and IB here both look good 👍🏻 

IB ✅

**Comment by tofumatt** [comment]
Tests are QA'd as part of CI and run locally by me during code review, so no further QA needed. Moving directly to Approval.
