### ISSUE TITLE
Loading State for Key Metric Widget Tiles

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7158]
## Feature Description

Loading state for existing Key Metric Widget tiles should be updated to match this [Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=5409-80974&mode=design&t=D1fpE0r18blVhVn1-0).

<img width="1200" alt="Screenshot 2023-07-11 at 17 59 49" src="https://github.com/google/site-kit-wp/assets/1721319/d89edc34-29dc-4323-b14e-2f761b1c0902">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The loading state for all implemented Key Metric Widget tiles should be designed to follow this [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=5409-80974&mode=design&t=D1fpE0r18blVhVn1-0).
* All stories for the above components should be updated to have this new loading style.

## Implementation Brief

- In `assets/js/components/KeyMetrics`:
  - Update the `MetricTileNumeric.js`, `MetricTileText.js`, and `MetricTileTable.js` files as the following:
    - Locate the `<PreviewBlock>` component usage.
    - Replace the current usage with two distinct sibling `<PreviewBlock>` components according to the Figma designs.
    - They should have a width of 100%, but their height should be according to the Figma designs (as of now 14px for the first `<PreviewBlock>`, 53px for the second `<PreviewBlock>`).
    - They should be contained in a `div` with a new classname, e.g. `googlesitekit-km-widget-tile__loading`. Use this class to apply a vertical spacing between the two `<PreviewBlock>` components according to the Figma designs.
- In `assets/sass/components/key-metrics/_googlesitekit-km-widget-tile.scss`:
  - Add all necessary styles here.

### Test Coverage

- Update the relevant VRT test scenarios for the loading state.

## QA Brief

* The stories should have the correct margins between the two preview blocks, matching the Figma mocks:
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-widgettiles-metrictilenumeric--loading
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-widgettiles-metrictiletable--loading
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-widgettiles-metrictiletext--loading
* Enable User Input feature flag and answer the User Input questions so the Key Metric widgets appear on the Site Kit dashboard. While they are loading, they should match the Figma designs mentioned in the ACs.

## Changelog entry

* Update loading state for Key Metric widget tiles.

**Comment by eugene-manuilov** [comment]
@jimmymadon @aaemnnosttv @marrrmarrr do we really need to show a placeholder for titles in the KMW widgets? We don't load titles, so we can show them right away like we do now for [New Visitors](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-newvisitors--loading) and [Loyal Visitors](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-loyalvisitors--loading). The more elements we show at the beginning is better for user experience, right? 

![image](https://github.com/google/site-kit-wp/assets/873049/91bd99dc-d25d-4588-8c18-9944a102eb08)

**Comment by eugene-manuilov** [comment]
@jimmymadon I am going to send this ticket back to you because this is not clear how the loading state should be displayed on mobile viewports. Let's make it clear to avoid any confusions.

**Comment by aaemnnosttv** [comment]
> do we really need to show a placeholder for titles in the KMW widgets? We don't load titles, so we can show them right away like we do now for [New Visitors](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-newvisitors--loading) and [Loyal Visitors](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-loyalvisitors--loading). The more elements we show at the beginning is better for user experience, right?

Good question. It's not entirely clear for me if the requirement here is for all tiles to show in a loading state until everything is loaded, or if the loading state remains per-tile (as now) and is essentially modified to include a separate preview block for the heading. The latter is something we've gotten a bit inconsistent about (regarding the preview – we are consistent about all widgets loading independently), but so long as the title stays consistent, that seems fine to show during the loading state. We may want to avoid introducing a kind of flicker in the event of an error though where the title could be there very briefly and then the whole tile is replaced by the error variant.

I also know there are some variants in the layout depending on some various conditions like module connection, etc that may also be a factor here. 

I'm curious to hear what @sigal-teller thinks.

**Comment by sigal-teller** [comment]
@jimmymadon  Not sure I understand if all tiles are loading together and if we can apply the same loading state to all of them. Also, I'm not sure I understand  why in the error state we need to have the flicker state as it usually only appears in loading states. Can you please clarify this issue a bit more?

**Comment by sigal-teller** [comment]
@jimmymadon Ok, now I understand what you mean, for the loading state switching to error state. Let me try and create something. The reason why I took it off was that the tile is quite small and we needed to add the CTA. I'll update you with the result.

**Comment by sigal-teller** [comment]
@jimmymadon I added the updated loading state along with the error state, both with metric name titles.
https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=5409%3A80974&mode=design&t=G3itcDz0Gka47h8z-1

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The loading state for all implemented Key Metric Widget tiles is designed to follow this [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=5409-80974&mode=design&t=D1fpE0r18blVhVn1-0)
- All stories in the QAB are updated to have this new loading style
- Tested this on all supported browsers
- Tested this on desktop and small view ports, i.e. mobile and tablet

https://github.com/google/site-kit-wp/assets/73545194/1ea843db-5306-41fc-aea0-6024894efbc5
