### ISSUE TITLE
Key Metric Widget Tiles on Mobile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7159]
## Feature Description

Currently, our widget layout mechanism renders "quarter" sized widgets as two widgets per row. We need to adapt this system to cater for the new Key Metrics design which renders one widget per row as per this [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=2089%3A63840).

Actual (Current):
<img width="505" alt="Screenshot 2023-06-22 at 13 27 20" src="https://github.com/google/site-kit-wp/assets/1721319/075d78d0-92aa-459c-9498-4e1e8ef33741">

Expected (Figma):
<img width="630" alt="Screenshot 2023-06-22 at 13 34 02" src="https://github.com/google/site-kit-wp/assets/1721319/6f87c209-9208-4c80-a673-a9e00e4b4272">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Key Metric widgets should follow the design in the corresponding [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=2089%3A63840) on mobile viewports.

## Implementation Brief

- Having discussed a few potential approaches with @aaemnnosttv, we've settled on taking an approach where we override the layout via CSS for the Key Metrics widgets at mobile viewports.
  - The alternative approaches all involved specifying the new size via the widget renderer in JS and would be a much more involved and complex matter. Taking this CSS-based approach, although arguably a little bit hacky, is a pretty simple and isolated fix, which we can easily strip out and replace at a later point if we determine additional requirements that would support the case for augmenting the widget rendering in JS.
- We can target the `.mdc-layout-grid__cell--span-2-phone` for the KM widgets (via the widget area class) and override the styles with the `span-4` variant.
- We should make use of the mixins provided by `@material/layout-grid`, with the [usage in `.mdc-layout-grid__cell`](https://github.com/material-components/material-components-web/blob/3cc4c6aa48ae8c1a307df542911e28a7808de41f/packages/mdc-layout-grid/mdc-layout-grid.scss#L54-L74) serving as a reference. This will ensure we have consistent styles with minimal explicit duplication.
- This has been fleshed out in a draft [PR](https://github.com/google/site-kit-wp/pull/7261) which may be continued.

### Test Coverage

- No new tests needed.

## QA Brief

* Setup Site Kit with GA4 connected, enable the `userInput` feature flag and setup Key Metrics.
* Navigate to the Dashboard and verify that the Key Metric widgets display in the correct number of columns: 1 on mobile, 2 on tablet and 4 on desktop.
* Verify that the widgets are laid out correctly as per the mobile layouts on [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=2089%3A63840&mode=dev), with the title and content each taking up 50% of the width, apart from table layout widgets ("Most popular/Top earning content") which retain their columnar layout.
  * An easy way to see a numeric, text and table layout widget on the same page is to select "Monetize content" under "What is the main purpose of this site?" in the Key Metrics setup.

## Changelog entry

* Update key metric tiles to be full-width on mobile viewports.

**Comment by sigal-teller** [comment]
@jimmymadon When I created the mobile view for the KMW I explored several layouts. the reason why I used one column is font size (in 2 columns the font gets smaller) and more important, the cards that contains page names cut the text really short which is really missing the point. one column allows page names to get full width, like [here](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=1764%3A46178&t=ilF1a9sEgbDYitxg-1)

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
IB sounds good to me (I haven't looked at the draft PR yet, but IB looks good).

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on staging environment.
- Tested Key metrics widgets titles on mobile, Tablet and Desktop viewports.
- Verified that Key Metric widgets display in the correct number of columns: 1 on mobile, 2 on tablet and 4 on desktop.
- Verified that Key Metric widgets in mobile display with the title and content each taking up 50% of the width, apart from table layout widgets ("Most popular/Top earning content") which retain their columnar layout.

<details>


https://github.com/google/site-kit-wp/assets/94359491/0d12bbfe-3323-47dd-9d76-3c997f926277

![image](https://github.com/google/site-kit-wp/assets/94359491/62f49191-bb98-4cd9-b16d-085a48a4c641)

![image](https://github.com/google/site-kit-wp/assets/94359491/7d1c757d-cd12-4149-b1f1-e28302c5fb15)

![image](https://github.com/google/site-kit-wp/assets/94359491/d2d2ee9a-fa7f-46f3-92f3-0f68c5a8e260)

</details>
