### ISSUE TITLE
Potential infinite loop during Analytics set up

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7168]
## Bug Description

When setting up Analytics, Site Kit initially only requests read-only scopes. If afterwards, the user chooses to create a new property, the edit scope will be required first before that will be possible to request. In order to save the user from submitting the form again, after granting the scope, we added an auto-submit mechanism to automatically submit the form when the user lands back in the set up once the scope has been granted.

There is currently a flaw in this behavior where the auto-submit will continue to make the create request if the user's Google account does not have sufficient permissions to create the entity (e.g. they only have the Viewer role on the account) until eventually the user hits the quota limit is exceeded. 

## Steps to reproduce

1. Start set up for Analytics without having granted the edit scope
2. Choose an account that the user only has Viewer-level permissions for
3. Choose "Set up a new property"
4. Submit the form
5. When prompted, grant the additional scope to create the property
6. On returning to the site, see repetitive failing requests to `create-property`
7. The set up never completes and the user is blocked

## Screenshots

https://github.com/google/site-kit-wp/assets/1621608/113f8c50-6005-4a58-976a-bbea62c4f916

## Additional Context

This has likely been possible for a long time, and is not a regression.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics set up flow should only attempt to auto-submit the form once per oAuth flow, when a scope needs to be granted to complete the set up 

## Implementation Brief

Note, there is already a PR for this including test coverage: https://github.com/google/site-kit-wp/pull/7201.

* Update `submitForm` handler in GA `SetupForm` to disable `autoSubmit` before calling `submitChanges`
	* The problem is that currently this only happens after `submitChanges` if there is no error which doesn't make sense

### Test Coverage

* Add test coverage for `SetupForm` (none currently), including the auto-submit behavior when there is an error

## QA Brief

* Steps to reproduce above should be sufficient to verify the current problem and the fix

## Changelog entry

* Fix bug that could cause infinite loop in Analytics setup flow if user had view-only permissions for an Analytics property.

**Comment by aaemnnosttv** [comment]
@bethanylang I've added this to the sprint as there should be little left to do here, and it's also an important fix we want to include sooner than later.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested with the a/c which have only 'View' access.
- I'm able to reproduce error on latest environment.
- On dev environment, the issue is fixed and user is not getting stuck in a loading state.

<details>

https://github.com/google/site-kit-wp/assets/94359491/4308917f-0034-46ac-9a45-a209db58caed

</details>

**Comment by mohitwp** [comment]
@aaemnnosttv I did not able to found any existing issue ticket for the duplicate errors. So, I created a new issue #7276 to make sure we address this issue.
