### ISSUE TITLE
Ensure that `calculateChange()` returns zero when both current and previous values are zero.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7172]
## Feature Description

At the moment, the `calculateChange()` function returns `null` when the `previous` value is zero, as seen here:

https://github.com/google/site-kit-wp/blob/100ca9436b00ffba317bcffb2ae33e3a67a37308/assets/js/util/index.js#L87-L91

However, this is incorrect in the scenario where `current` is also zero, in which case the change should be returned as `0` rather than `null`.

This was identified as a fix for a point raised in QA for #6244 (see "Question 2" [here](https://github.com/google/site-kit-wp/issues/6244#issuecomment-1588379268)), but appears to be a valid fix to make across the board for `calculateChange()`. However, with this function being used widely in the codebase, due diligence must be applied to confirm this is the case and validate with a good round of testing.

_Note: There is a closed [PR](https://github.com/google/site-kit-wp/pull/7169) which can be recreated as the fix for this assuming it's confirmed as above._

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ChangeBadge` rendered in Key Metric Widgets should show 0% where both, the previous and current values are 0. 
* "Change" badges on other existing components such as the Admin Bar, WPDashboard Widget and DataBlocks on the Main and Entity dashboards should NOT be affected by this change.

## Implementation Brief

* There is a closed [PR](https://github.com/google/site-kit-wp/pull/7169) which can be recreated as the fix for this assuming it's confirmed as above. The `calculateChange()` function should return 0 when both the `previous` and `current` values are zero.

### Test Coverage

* No new tests required.

## QA Brief

* Verify the ACs using a site with Zero data, since such a site will have "zero" values for the previous and current periods.

## Changelog entry

* Fix bug that could cause zero percent in key metric widgets not to appear.

**Comment by wpdarren** [comment]
### QA Update: 

**Verified:**

- The `ChangeBadge` rendered in Key Metric Widgets shows 0% where both, the previous and current values are 0.
- The `ChangeBadge` on other existing components such as the Admin Bar, WPDashboard Widget and DataBlocks on the Main and Entity dashboards are not affected by this change.
- Checked the `ChangeBadge` on a site that is not zero data to make sure that they continue to appear on the Key metrics widget and other areas of the plugin. 

![image](https://github.com/google/site-kit-wp/assets/73545194/6327f43e-905d-45f8-8964-d5b7b5042cdc)
![image](https://github.com/google/site-kit-wp/assets/73545194/19dec2be-3592-44a6-8c56-584d2adeadb4)
