### ISSUE TITLE
"New visitors" key metric widget tile Abbreviation looking bigger than number.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7185]
## Bug Description

Abbreviation is looking bigger as compare to number. Can we fix it font size so both number and abbreviation appears same ? I realize that if we change it to small case, then it will not look consistent with our current style.

- Test with site having data.
- Enabled the `userInput `feature flag.
- Check "New visitors" tile.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/94359491/51870cdd-c268-411d-a7d3-6d35492cdeeb)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @mohitwp – after looking into this it seems to be specific to certain numbers/characters of Google Sans.

Looking at the same numbers within the Analytics dashboard, we can see the same there.

**`5K` – the K appears slightly taller**
<img width="112" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/cfa70255-0b7c-44f7-9d4e-98ed2d5b6040">
<img width="161" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/b8c2994f-ea28-4074-9351-fc4dc239f223">


**`6K`** the two appear to be the same height**
<img width="87" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/44651372-dc45-40c3-92e5-b0f5e30d3039">
<img width="158" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/c8bd55aa-e425-4026-9a42-2f116bd54e60">
