### ISSUE TITLE
Format numbers in Key Metric Widget tiles

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7190]
## Feature Description

Larger numbers for total figures in all currently implemented KMW tiles should be formatted as per the Figma mock below.

Expected:
![image](https://github.com/google/site-kit-wp/assets/1721319/9aef1b65-79f9-4326-983b-e259c5ddd23e)

Actual:
![image](https://github.com/google/site-kit-wp/assets/1721319/592e6b6f-c5ad-42d5-80e8-31ab0c667e61)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All secondary numbers in Key Metrics Widget tiles should be formatted with the appropriate locale-based format (e.g. `1234` in `en-US`: `1,234`)
	* The style should not use the default `metric` type and generally use the appropriate formatting options to match the design (e.g. integers shouldn't end in `.0`, etc)  
* This includes (but is not limited to) the "total visitors" figure in both, the "New Visitors" and "Loyal Visitors" KM widgets

## Implementation Brief

* Merge [this PR](https://github.com/google/site-kit-wp/pull/7223) which uses `numFmt` with the decimal style to format totals in both the widgets mentioned in the AC.

### Test Coverage

* No new tests required.

## QA Brief

* Verify that both, the `New Visitors` and `Loyal Visitors` widgets, show the formatted number strings. Storybook stories don't have high enough numbers to test this formatting.

## Changelog entry

* Improve formatting of larger numbers in Key Metric Widget tiles.

**Comment by aaemnnosttv** [comment]
@jimmymadon the format specified by the AC is locale-specific. The number should simply be properly formatted according to the locale, just like any other number.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – are there any other widget tiles that are in process which could need the same fix here or does it only affect these two? Also are there any that are in the EB that could use a note added to avoid missing this again?

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – for the AC I think we can word them in a way that is not specific to these two tiles. This essentially applies to all "secondary" numbers in KMW tiles (those aside from metric and change).

> * like other numbers in the plugin

Most other numbers in the plugin are formatted using `numFmt` which defaults to the "metric" style. If applied here, we'd end up with a number like `1.6K` instead of `1,681`, so we'll want to make sure that we want to use this alternate style, and that we're a little more explicit about this requirement.

I'll update this to move it forward for the sake of time 👍

**Comment by tofumatt** [comment]
IB ✅ 

Since this has a PR ready I'll review it as well, so moving this right to CR 🙂

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified under "new Visitor' and "Loyal Visitors" KMW tiles as other tiles don't have that much data or not implmented yet.
- Verified total visitors numbers are showing  formatted number strings.
- 

![image](https://github.com/google/site-kit-wp/assets/94359491/9d2903f9-6a06-4046-b7c6-24cc27097d1c)
