### ISSUE TITLE
Clean up deprecated dynamic property declarations

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7202]
## Bug Description

PHP 8.2 has deprecated dynamic property declarations for classes that do not explicitly declare this with the [`AllowDynamicProperties` attribute](https://www.php.net/manual/en/class.allowdynamicproperties.php).

We currently have a few of these lingering in the codebase that need to be cleaned up.

## Steps to reproduce

N/A – this can be found using IDE inspections

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All dynamic property declarations should be fixed by declaring the missing properties as appropriate (preferring protected)

## Implementation Brief

The following properties should be declared

- `\Google\Site_Kit\Core\Authentication\Exception\Google_Proxy_Code_Exception->access_code`
- `\Google\Site_Kit\Core\Modules\Tags\Module_Tag->module_slug` (rename the current
 `$slug` property to be `$module_slug`)
- `\Google\Site_Kit\Core\Authentication\Setup->proxy_support_link_url`

These can all be `protected` because getters already exist where needed

### Test Coverage

* No changes necessary

## QA Brief

* If E2E tests pass successfully, this can be moved directly to approval without additional QA.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
> * `\Google\Site_Kit\Core\Modules\Tags\Module_Tag->module_slug`

Hm... looks like we just need to rename the `$slug` property to be `$module_slug` in the `Module_Tag` class. No need to add a new property there. @aaemnnosttv, could you please update IB to say this? Everything else seems to be right in IB.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by matejmosko** [comment]
I confirm this issue with following warning using PHP 8.2:

_PHP Deprecated:  Creation of dynamic property Google\Site_Kit\Core\Authentication\Setup::$proxy_support_link_url is deprecated wp-content/plugins/google-site-kit/includes/Core/Authentication/Setup.php on line 94_

**Comment by bethanylang** [comment]
@aaemnnosttv Would it be possible to bump this to a P1? Even though it doesn't affect actual plugin performance, it's generating a lot of support topics (1-2/day) and seems to be really frustrating users.

**Comment by aaemnnosttv** [comment]
@bethanylang updated 👍

**Comment by tofumatt** [comment]
Moving directly to Approval as no QA is needed here.
