### ISSUE TITLE
Add PHP version to requests for features

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7209]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The metadata sent in `Google_Proxy::get_features` should be updated to include a new `php_version` key, with the value equal to the current PHP version 

## Implementation Brief

* Implement add the field as defined in the AC

### Test Coverage

* Update test coverage for the `get_features` method

## QA Brief

* This can be tested using the a plugin like Log HTTP Requests installed/active before setting up SK on a new site
* After connecting, review requests made to the service `/site-management/features/`, in the body `php_version` should be present

## Changelog entry

* Add PHP version to requests for features

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

After connecting Site Kit, review requests made to the service the `php_version` should is present

![image](https://github.com/google/site-kit-wp/assets/73545194/bb24dba4-d99a-4842-91c9-72794f4550e0)
