### ISSUE TITLE
Google Tag Manager snippet is in the wrong location

### ISSUE THREAD

**Issue by kaelhoel** [google/site-kit-wp#721]
## Bug Description

 I have Tag Manager set up by Google Site Kit. When trying to confirm ownership of my website for Google Merchant Center, and choosing Tag Manager to verify, it fails. Error message says "GTM snippet is in the wrong location."

## Steps to reproduce

1. Attempt to confirm ownership of website for Google Merchant Center with Google Tag Manager.

## Screenshots

![image](https://user-images.githubusercontent.com/48452614/67663763-8384a700-f966-11e9-8470-aa7920699c80.png)

## Additional Context

 - 7.3
 - OS: Windows 10
 - Chrome
 - 1.0.0-rc.1.1
 - Windows PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@kaelhoel Thanks for raising this issue. Do you mind informing me of the following:
- Can you confirm that you can continue with ownership by using the "I have a Google Analytics account" option? Using Tag Manager with Site Kit is dependent on having Analytics setup, it would be interesting to know if it allows you to proceed. 
- Can you check the source code of your website and share the location of the Google Tag Manager reference? You will see a reference as below, or alternatively or share your URL:
`<!-- Google Tag Manager added by Site Kit -->`

**Comment by jamesozzie** [comment]
@kaelhoel I can see also you are using version 1.0.0-rc.1.1 of the Site Kit plugin. Can you download the latest version [here](https://sitekit.withgoogle.com/service/download/google-site-kit.zip) before following the steps below: 

- Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit) 
- Add Google Tag Manager to your site manually
- Add the Google Merchant Center container 
- Verify on Google Merchant Center

Alternatively you can attempt Google Merchant Center verification after disabling the Tag Manager module with the latest version of the Site Kit plugin.

**Comment by jamesozzie** [comment]
Hi all, Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. Where we would be happy to assist from there
