### ISSUE TITLE
Incorrect Ad Blocking Recovery tag placement status displayed on AdSense module settings

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7213]
## Bug Description

As spotted by @aaemnnosttv [here](https://github.com/google/site-kit-wp/pull/7203#issuecomment-1608456301), the Ad Blocking Recovery Tag Placement status on the Settings View or AdSense is incorrectly based on the `adBlockingRecoverySetupStatus` instead of the `useAdBlockerDetectionSnippet`. This likely happened due to the unfortunate wording on the AC of [6961](https://github.com/google/site-kit-wp/issues/6961) which stated, "If the **tag is placed**, the accompanying text and link underneath the setting should appear as seen in the design" - which was interpreted as the `tag-placed` state of `adBlockingRecoverySetupStatus` setting, which is obviously incorrect.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Whether the Ad Blocking recovery tag is placed should be based on the value of `useAdBlockerDetectionSnippet` only. 
    * If the value is `true`, then the tag is placed.
    * If the value is `false`, then the tag is not placed
* The `Ad blocking recovery` section on AdSense Settings View should only be displayed when the `adBlockerDetection` feature flag is enabled and the value of `adBlockingRecoverySetupStatus` is **NOT** an empty string. 
    * If the feature flag is enabled but the value of `adBlockingRecoverySetupStatus` is an empty string, the Setup Ad Blocking Recovery Settings CTA should be displayed instead.

## Implementation Brief

* In `assets/js/modules/adsense/components/settings/SettingsView.js`:
    * Get the value of `useAdBlockerDetectionSnippet` using the `getUseAdBlockerDetectionSnippet` selector.
    * Refactor the parts in the bottom as par AC. Namely, update the logic around "Ad blocking recovery tag is placed" and "Ad blocking recovery tag is not placed" place to be rendered based on the `useAdBlockerDetectionSnippet`.
    * Only render the `AdBlockingRecoveryCTA` when `adBlockerDetection` is enabled and the value of `adBlockingRecoverySetupStatus` is an empty string. 
        * Remove the now redundant `adBlockingRecoverySetupStatus` check inside `assets/js/modules/adsense/components/common/AdBlockingRecoveryCTA.js`.

### Test Coverage

* Fix any failing test. 

## QA Brief

* The same as for #6961:

> This can't be tested on a live site yet because the feature cannot be fully set up. Instead, test the UI in storybook.
> 
> * View the Storybook story for "View, open with Ad Blocking Recovery tag not placed")
>   * You should see a section marked "Ad blocking recovery" and the text "Ad blocking recovery tag is not placed".
> * View the Storybook story for "View, open with Ad Blocking Recovery tag placed")
>  * You should see a section marked "Ad blocking recovery" and the text "Ad blocking recovery tag is placed", along with a section beneath explaining the Ad Blocking tag and a link. **Note: The "Ad blocking recovery tag is placed" should not be bold, unlike in the Figma mocks where it is bold.**

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
AC 👍

**Comment by aaemnnosttv** [comment]
Thanks @kuasha420 – the IB looks good for the most part but let's be sure to mention the setup CTA as I feel that could be missed otherwise. We don't need to duplicate what the AC says but it should be mentioned.

**Comment by kuasha420** [comment]
Good point, The CTA should behave as is but it's not immediately obvious why. I think I can make it a little more readable and reduce mental overhead here. I've updated the IB accordingly.

**Comment by aaemnnosttv** [comment]
Great, thanks @kuasha420 👍 

IB ✅

**Comment by aaemnnosttv** [comment]
@eugene-manuilov would you please add a QAB?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv, could you please review #7229?

**Comment by mohitwp** [comment]
### QA Update ❌ 

@eugene-manuilov 

Tested on dev environment.

**Issue >**

**1>** I verified storybook story for [View, open with Ad Blocking Recovery tag placed](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module-settings--view-open-with-ad-blocking-recovery-tag-placed) .Under "Ad blocking recovery" section  text is "Ad blocking recovery tag is not placed" instead of it text should be  "Ad blocking recovery tag is placed". 

**2>**  A section beneath explaining the Ad Blocking tag and a link is also not present.

![image](https://github.com/google/site-kit-wp/assets/94359491/1372f286-1e93-45f8-ab16-ef28c7a362a8)

![image](https://github.com/google/site-kit-wp/assets/94359491/c0117933-6497-4a4b-a4d4-28dfe7ba0725)

**Comment by techanvil** [comment]
Back over to you for another pass, @mohitwp.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified storybook story for [View, open with Ad Blocking Recovery tag placed](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module-settings--view-open-with-ad-blocking-recovery-tag-placed).
- Also, verified status on Live website.
- Verified The Ad blocking recovery section on AdSense Settings View display only when the adBlockerDetection feature flag is enabled and the value of adBlockingRecoverySetupStatus is NOT an empty string.
- Verified if feature flag is enabled but the value of adBlockingRecoverySetupStatus is an empty string, the Setup Ad Blocking Recovery Settings CTA is display.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/2f340908-0946-4cbe-9511-aca115dc79fc)

![image](https://github.com/google/site-kit-wp/assets/94359491/5bd00acd-7029-4054-a36c-dfafb02392d7)

</details>
