### ISSUE TITLE
Avoid mutating Redux state in Analytics ProfileSelect and PropertySelect components.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7220]
## Feature Description

When implementing https://github.com/google/site-kit-wp/issues/6740, we inadvertently introduced code that potentially mutates Redux state, which is obviously an anti-pattern.

It's not clear that this currently presents itself as a user-facing bug, although it did surface itself when writing a JS test, with a resulting React key collision error.

### `ProfileSelect`

Note the mutation on line 124.

https://github.com/google/site-kit-wp/blob/bab8d44cdc4041c79ff11bf152aa97ca5bba32b5/assets/js/modules/analytics/components/common/ProfileSelect.js#L51-L60

https://github.com/google/site-kit-wp/blob/bab8d44cdc4041c79ff11bf152aa97ca5bba32b5/assets/js/modules/analytics/components/common/ProfileSelect.js#L120-L128

### `PropertySelect`

The mutation here is on line 118.

https://github.com/google/site-kit-wp/blob/bab8d44cdc4041c79ff11bf152aa97ca5bba32b5/assets/js/modules/analytics/components/common/PropertySelect.js#L45-L55

https://github.com/google/site-kit-wp/blob/bab8d44cdc4041c79ff11bf152aa97ca5bba32b5/assets/js/modules/analytics/components/common/PropertySelect.js#L114-L122

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics `ProfileSelect` and `PropertySelect` components should be updated to avoid mutating Redux state as per the feature description.

#### ProfileSelect

* Update the `ProfileSelect` component to clone / make a copy of the `profiles` array before adding the new object.
* Use the cloned array instead of the original array in the subsequent code.

#### PropertySelect

* Similarly, update the `PropertySelect` component to clone / make a copy of the `properties` array before adding the new object.
* Use the cloned array instead of the original array in the subsequent code.

### Test Coverage

* Fix any failing tests.

## QA Brief

* Note: There are no user-facing changes involved.
* Verify that the Analytics `ProfileSelect` and `PropertySelect` dropdowns continue functioning as expected in the setup and settings forms.

## Changelog entry

* N/A.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified profile select and property select dropdown under Analytics set up and under settings.
- Drop-downs are working as expected.
