### ISSUE TITLE
AMP: Add support for tagging with GA4

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7221]
## Feature Description

Until now, AMP's Analytics integration has not supported GA4. Now that it does, Site Kit should be updated accordingly.

See https://developers.google.com/analytics/devguides/collection/amp-analytics/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* GA4 should add/extend the `amp-analytics` tag with its configured measurement ID as per [the spec](https://developers.google.com/analytics/devguides/collection/amp-analytics/) 

## Implementation Brief

* Extend UA AMP tag to include GA4 tag ID (when UA tag is going to render)
* Otherwise, use existing AMP tag with GA4 tag ID (similar to approach taken with GA4 web tag)
* Finish and merge #7224

### Test Coverage

* Tag classes are currently without tests; given the urgency here we can follow this convention and follow-up with added coverage

## QA Brief

* This issue changes the way AMP tags are rendered, integrating the GA4 tag with the UA tag when present, otherwise placing the same `amp-analytics` tag with only the GA4 ID if UA is not connected or snippet is not enabled
* This should only affect GA in AMP and support only UA, only GA4, or both enabled.
* The realtime report in GA can be used to see data come in (there is some delay but you should see hits come through within 30-60s)

## Changelog entry

* Add support for tagging with Google Analytics 4 in AMP mode

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `amp-analytics tag` is rendered with a site that as GA4 only, UA only, and GA4 and UA. 
- Checked to make sure that ?amp visits to the website were tracked in Analytics using the realtime reports. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/14fd9764-9d7f-44de-b2ff-4238a4307178)
![image](https://github.com/google/site-kit-wp/assets/73545194/4614fc19-8617-4e46-9541-999d65d8666a)
![image](https://github.com/google/site-kit-wp/assets/73545194/d1bc2f94-90ea-495c-9c5f-27ed91d723a2)
![image](https://github.com/google/site-kit-wp/assets/73545194/59e03069-51f3-406e-af31-b7e9d15d7fef)
![image](https://github.com/google/site-kit-wp/assets/73545194/25d9f3d1-149a-4575-878d-a941831a0cde)
![image](https://github.com/google/site-kit-wp/assets/73545194/0265027b-313a-4ba5-a4c5-45d4f4768af5)
![image](https://github.com/google/site-kit-wp/assets/73545194/6646c41f-e7f9-46bf-8885-e429230e2239)
![image](https://github.com/google/site-kit-wp/assets/73545194/40cd5264-70e0-445d-ab71-2cd2f98ef85f)

</details>
