### ISSUE TITLE
Failing JS lint for `AdBlockingRecoveryWidget.test.js`

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#7226]
It was noticed during execution of an unrelated issue that the lint for `assets/js/modules/adsense/components/dashboard/AdBlockingRecoveryWidget.test.js` was failing with the following error:

```
149:5  error  'timestampThreeWeeksAgo' is not defined  no-undef
```

Further investigation validated said cli error, and it was clear that `timestampThreeWeeksAgo` was not defined. Upon further investigation, it was concluded that a recent Pull Request into `main` was responsible for renaming the `timestampThreeWeeksAgo` variable to `timestampThreeWeeksPrior`. This can be observed at the following link: https://github.com/google/site-kit-wp/pull/7216/files#diff-416e2ab624776daf1cf3c93b74cd00a2b3ca772d2832d6c3579b9f6049425c76R50

Following said change, a recent PR into `develop` reinstated usage of the old name, in certain areas of the test code:

https://github.com/google/site-kit-wp/pull/7208/files#diff-416e2ab624776daf1cf3c93b74cd00a2b3ca772d2832d6c3579b9f6049425c76

This PR incorrectly used the old `timestampThreeWeeksAgo` variable as opposed to the new `timestampThreeWeeksPrior` one from the `main` branch PR.

## Steps to reproduce:

1. Check out the `develop` branch
2. Pull the latest `develop` branch from the remote
3. Run `npm install`
4. Run `npm run lint:js`
5. Observe the failed lint at `assets/js/modules/adsense/components/dashboard/AdBlockingRecoveryWidget.test.js`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The JavaScript lint test for `assets/js/modules/adsense/components/dashboard/AdBlockingRecoveryWidget.test.js` should pass with no errors.
    * This can be validated via a successful execution of the command `npm run lint:js` where no failing lints should be observed.

## Implementation Brief

 * Merge PR at https://github.com/google/site-kit-wp/pull/7227

### Test Coverage

* 

## QA Brief

- Ensure the [Code Linting and JS Tests workflow](https://github.com/google/site-kit-wp/actions/workflows/js-css-lint-test.yml) passes once this is merged.

## Changelog entry

* N/A.

**Comment by aaemnnosttv** [comment]
AC ✅
