### ISSUE TITLE
Dashboard stuck in loading state when user lacks access to GA4 property

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7244]
## Steps to reproduce

1. Set up GA4
2. Sign in with a different Google user that does not have access to the configured GA4 property
3. View dashboard
4. See loading state

## Screenshots

<img width="1920" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/c1bd9a70-c91f-494e-b804-d9ed1c4aedf6">

## Additional Context

Present on 1.103.0, 1.102.0

The request seems to be coming from here https://github.com/google/site-kit-wp/blob/cf7cf58ef43dcbb8b56152896e1e6b034f6428c0/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js#L112

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The dashboard should not be stuck in a loading state if the user's Google account does not have access to the configured GA property
* This experience should be consistent with the same scenario on the UA version of the dashboard as seen here  
    <img width="892" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/05e292ac-8e6c-4f2c-b5bc-f34b01cbc11e">

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by nfmohit** [comment]
Hi @aaemnnosttv!

As discussed on our 1:1, I've co-assigned you on this since we've failed to reproduce this ([internal discussion](https://10up.slack.com/archives/CBKKQEBR9/p1688210390408749?thread_ts=1688151718.987379&cid=CBKKQEBR9)). Please let me know if you're able to reproduce this consistently. If so, is there a pattern that could help us reproduce this?

Thank you!

**Comment by aaemnnosttv** [comment]
Just tested this again and wasn't able to reproduce. Closing!
