### ISSUE TITLE
VRTs fail for GA4 notice after July 1 

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7248]
## Bug Description

Our VRTs are failing since there is a change in the language used in the UA Cutoff warning message after the 1st July UA cutoff date.

## Steps to reproduce

1. Run the VRTs on the latest develop branch.
2. See 6 failing tests all due to the language that has changed (correctly so) after 1st July.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics `SettingsEdit` and `UACutOff` Warning VRTs should pass.

## Implementation Brief

* This [PR](https://github.com/google/site-kit-wp/pull/7249) has the new VRTs updated and the "default" scenario for the old message before the cut off date has been amended to have a "fixed" reference date in the past.

### Test Coverage

* N.A.

### QA: Eng Only
* Check the VRTs are passing on the latest develop build.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by techanvil** [comment]
## QA :white_check_mark: 

Verified that the VRT tests pass on `develop`.

![image](https://github.com/google/site-kit-wp/assets/18395600/d7a557d2-0124-4a04-a83d-4074175b9ecf)
