### ISSUE TITLE
Make the number of items shown in reports filterable.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#7250]
## Feature Description

Currently, when we request results for different reports we use hardcoded limits. The default limits are usually sufficient for the majority of sites, but sometimes there is a need to adjust those numbers to display more items in reports. For example, some may want to display more than 10 items in the top search queries widget.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
Site Kit aims to give a high-level overview of how the site is doing and send users to the other Google products when they want to dig deeper, so having a shorter list on the dashboard aligns with that. If people ask for more details, we can show them where to get them in Search Console, Analytics, AdSense etc.
