### ISSUE TITLE
The "Ad blocker detected; please disable it to set up AdSense" text is not legible due to color/contrast 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7251]
## Bug Description

When an ad blocker is installed, the AdSense module is disabled in the "connect more modules" list and a message appears explaining the reason. However, the explanation text is also in a "disabled" state and the font is very low contrast and almost illegible on the white background. 

## Steps to reproduce

1. Install AdBlock Plus on browser.
2. Visit the "Connect more modules" page. 
3. See the text.

## Screenshots

![Screenshot_20230703_164502](https://github.com/google/site-kit-wp/assets/6187401/6e428549-196f-48da-8544-76062a375adc)

## Additional Context

 - Browser: Chrome
 - Plugin Version: 1.03.0

Note that this is a general bug and not related to the ongoing Ad Blocking Recovery epic. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The disabled state for modules in "Connect mode services" tab in Settings screen should be updated to follow the new [Figma](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1377%3A3428&mode=design&t=8Tuc1efS2Nb3Gy8B-1) design. Namely-
    * Only the CTA button should be disabled. 
    * The `Ad Blocker Detected` notice should be updated to follow the new appearance and should be positioned below the disabled CTA button. 

## Implementation Brief

* [x] In `assets/js/components/settings/SetupModule.js`:
    * [x] Move the `<ModulesSettingsWarning>` below the `<Link>`.
    * [x] Update the styling so that `googlesitekit-settings-connect-module--disabled` is removed.
* [x] Update any other relevant styles in `googlesitekit-settings-connect-module`.

### Test Coverage

* Add a VRT snapshot for the Connect Module in disabled state.

## QA Brief

* Install AdBlock Plus and navigate to a set up Site Kit site/install.
* Verify the AdBlockerWarning message for the Ads and AdSense modules should match the screenshot below:
![Screenshot 2024-05-27 at 14 51 13](https://github.com/google/site-kit-wp/assets/90871/52aefa14-b70d-434c-8f83-c89df27fd789)

This message should appear in:

* The **Connect More Services tab** - which is what the ACs of this issue cover.
* The **Connected Services tab** accordion in the "Incomplete Setup" state. Go through the entire QAB of #8634 to verify the modules list accordion on the Connected Services tab, including all settings view and edit forms.
* The **AdSense dashboard widget**.

## Changelog entry

* Update Ad Blocker warning message in Ads and AdSense modules.

**Comment by jimmymadon** [comment]
@sigal-teller We could perhaps redesign this element to only disable the button (CTA) and not the entire element? But will leave this to your design eye!

**Comment by tofumatt** [comment]
ACs look good, this is a massive improvement 👍🏻 

Moving to IB 🙂

**Comment by jimmymadon** [comment]
>When the disabled button is hovered over in collapsed state, a Tooltip should be displayed explaining the reason why the setup is disabled

@kuasha420 I feel this might be overkill here. Clicking on this disabled button (or on the Exclamation mark or anywhere on the Module title) would simply open up the accordion panel and the newly designed `AdBlockerWarning` message is displayed. Also, having read the [Figma discussion](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x?type=design&node-id=1341-3122&mode=design#793463114), this won't be a great solution for mobile as @sigal-teller suggests. 

I feel we can just skip this point for now from the AC and just focus on the Connect module not being in a disabled state. #8634 does implement everything else already and it LGTM. Let me know what you think?

**Comment by jimmymadon** [comment]
As discussed internally [here in slack](https://10up.slack.com/archives/CBKKQEBR9/p1716306543653229), we've decided to not add a tooltip to the disabled "Complete Setup" button on the module header. Clicking on it will open the accordion which does display the error, i.e. the AdBlockerWarning component.

c.c. @tofumatt @kuasha420 @sigal-teller

**Comment by tofumatt** [comment]
Works for me 🙂 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified the Adblocker detection notice design is updated and showing under 'Connect more services' and on main dashboard under AdSense widget as per AC.
- Also, verified and compare design with [Figma.](https://www.figma.com/design/THG1FJw5SaUxmiq38Mkf1x/Ads?node-id=1377-3467&m=dev)

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/5d7ce520-cd42-4e39-bb43-435103dda582)

![image](https://github.com/google/site-kit-wp/assets/94359491/6e276293-2fa0-4ad0-a2fb-da1c9414ade4)

</details>
