### ISSUE TITLE
Enhance AdSense Existing Tag detection to detect AdSense Auto Ads snippet

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7259]
## Feature Description

Currently AdSense existing tag detection only detects old style AdSense tags. But it does not detect new Auto Ad Snippets. We should enhance the detection to detect both snippets as existing AdSense tag. 

Old tag example:
```html
<script data-ad-client="ca-pub-xxxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
```
Auto ads tag example:
```html
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxxxxx"
     crossorigin="anonymous"></script>
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing tag selectors (`getExistingTag` and `hasExistingTag`) of `AdSense` module should be updated to detect both the old style and auto ad AdSense snippets. 

## Implementation Brief

In `assets/js/modules/adsense/util/tag-matchers.js`:

* Modify the tag matcher array to include one of the following regex patterns that detect the new auto ad snippet:
    * A general pattern that matches the client ID:
    ```js
    /<(?:script|amp-auto-ads)[^>]*src="[^"]*\?client=([^"]+)"[^>]*>/,
    ```
    * A more specific pattern that looks for the `ca-pub` prefix:
    ```js
    /<(?:script|amp-auto-ads)[^>]*src="[^"]*\?client=(ca-pub-[^"]+)"[^>]*>/
    ```
* Both the patterns work in my testing.

### Test Coverage

* In `assets/js/util/test/extractExistingTag.js`, add a new test case to detect the new Auto Ad Snippet script tag similar to other test cases.

## QA Brief
In order to test this functionality, a custom AdSense script of the new version  format must be added to the page by a means other than site kit. This can be done via the active themes `functions.php` file, or via a custom mu-plugin.

- Edit the active themes `functions.php` file (or create one if not present), OR
- Create a new mu-plugin at `[...]/wp-content/mu-plugins/00-adsense-testing.php`
    - You can create the mu-plugins folder if it does not yet exist
- Whether using the `functions.php` file or `mu-plugin` method, add the following snippet of code to either of the above locations:

```
add_action( 'wp_head', 'sk_add_adsense', 0, 15 );

function sk_add_adsense() {
?>
<!-- Added by QA (#7259) -->
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3467161889682403" crossorigin="anonymous"></script>
<?php
}
```

- **IMPORTANT**: Be sure to replace the pub ID in the example above (`3467161889682403`) with the pub ID of the AdSense account attached to your test environment.
- In wp-admin, navigate to `Google Site Kit > Settings > AdSense`
- Click the `Edit` CTA link for said module
- Validate that the correct "tag already present" message shows, as per the below screenshot:

<img width="1285" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/381c47bb-fc39-4a8b-a858-40efcab8a8f5">

- Remove the `mu-plugin` or the code from the `functions.php` file of said theme and validate that the "tag already present" message disappears.

## Changelog entry

* Enhance AdSense existing tag detection to detect AdSense Auto Ads snippets.

**Comment by jamesozzie** [comment]
I can confirm the same. Site Kit is placing the plugin inserted AdSense snippet despite an existing AdSense snippet already manually placed. [Recording](https://www.loom.com/share/0f6f3ecc54b44d77aaf8049c29b85ed1).

**Comment by tofumatt** [comment]
ACs are good 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The correct `tag already present` message shows when my mu-plugin is installed.  
- When my mu-plugin is removed, the `tag already present` message does not appear. 
- Also tested this when setting up AdSense with the mu-plugin installed just to make sure the message appears there too. 

![image](https://github.com/google/site-kit-wp/assets/73545194/a7a26dd4-1fb7-41f2-873e-a881cff5029a)
![image](https://github.com/google/site-kit-wp/assets/73545194/c323d4b3-0b0d-4c88-bb19-5935b5d72e2a)
