### ISSUE TITLE
Opt In/out should take effect immediately

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#727]
## Bug Description

Follow up for issues discovered during QA of https://github.com/google/site-kit-wp/issues/633.

* Checking or unchecking the opt in to tracking checkbox, then immediately performing an action (without a page refresh) doesn't work correctly during setup flow or on settings screen.

## Steps to reproduce

I see the same issue in two locations.

### Setup flow
![image](https://user-images.githubusercontent.com/2676022/67696032-bed5a480-f96b-11e9-8b54-fdd4a05dab43.png)

* During the plugin setup I am given the option to opt in to tracking (or opt out if I opted in from the plugin activation banner).
* If I opt in to tracking, then click on "Sign In With Google" the first tracking event is not sent correctly. `gtag` is undefined and `googlesitekit.admin.trackingOptin` is still false
* Similarly if I arrive with tracking enabled having enabled it on the plugin activation screen, then try to opt out, the first tracking event is still sent because `googlesitekit.admin.trackingOptin` is still true.

### Settings screen

![image](https://user-images.githubusercontent.com/2676022/67696264-2ab80d00-f96c-11e9-985a-840743b3aae5.png)

* Arriving at the settings screen with tracking disabled, I go to settings->admin and enable tracking. I then go to "Connect More Services (without refreshing) and activate Analytics. the first activation tracking event is not sent correctly. `gtag` is undefined and `googlesitekit.admin.trackingOptin` is still false.
* Similarly if I arrive with tracking enabled , then try to opt out, the first tracking event is still sent because `googlesitekit.admin.trackingOptin` is still true.

## Screenshots

Screenshots above.

## Additional Context

 - PHP Version: 7.3
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome Dev
 - Plugin Version [e.g. 22] develop branch also tested fix/633-opt-in-window
 - Device: [e.g. iPhone6] Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Opting in to tracking or opting out of it should immediately take effect, with the following event being fired or not fired accordingly.
* Let's consistently rely on one specific global variable `window.googlesitekitTrackingEnabled` for whether tracking is enabled or not, and remove the other one(s).

## Implementation Brief

* Change all references to `googlesitekit.admin.trackingOptin` to use `window.googlesitekitTrackingEnabled`
* Update `sendAnalyticsTrackingEvent` to only read/use `window.googlesitekitTrackingEnabled` instead of the current `googlesitekit.admin.trackingOptin` (this will require updating its E2E test as well).

## Changelog entry

* Ensure that opting in or out of tracking takes effect immediately.

**Comment by felixarntz** [comment]
In the non-React version, this relies on `window.googlesitekitTrackingEnabled` instead of `googlesitekit.admin.trackingOptin`. Maybe we should consistently decide on one of the two and use that value throughout (I'd vote for the first since that doesn't rely on an extra `admin` object to exist).

**Comment by tofumatt** [comment]
Agreed, let's use the same value everywhere; it's a bit confusing to have to handle two different values. (Leading to this bug/confusion!)

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Confirmed during setup that opt in takes effect immediately and the setting is retained in the admin section
![image](https://user-images.githubusercontent.com/57115907/69782947-4c710380-1167-11ea-9d08-03695ef23c9a.png)

![image](https://user-images.githubusercontent.com/57115907/69782983-64e11e00-1167-11ea-9a6c-2ebc289dac26.png)

Confirmed opt out functions the same during setup and into admin

![image](https://user-images.githubusercontent.com/57115907/69783126-b1c4f480-1167-11ea-8bc7-385cc5896a1f.png)

![image](https://user-images.githubusercontent.com/57115907/69783167-c99c7880-1167-11ea-91a4-6bd3c399c668.png)

**ONE THING TO NOTE**
Opting out isn't sticky on the same page.
Steps:

1. Have user opted in and navigate to the admin page
![image](https://user-images.githubusercontent.com/57115907/69783513-90183d00-1168-11ea-8bc6-375e0cc74069.png)

2. Click opt out by unchecking the box
![image](https://user-images.githubusercontent.com/57115907/69783559-a625fd80-1168-11ea-8929-2c9dda050beb.png)

3. Navigate to one of the other settings tabs in the admin
![image](https://user-images.githubusercontent.com/57115907/69783302-1d0ec680-1168-11ea-8cc5-5d3c2d141729.png)

4. Navigate back to the admin tab

Notice box is still checked
![image](https://user-images.githubusercontent.com/57115907/69783608-b5a54680-1168-11ea-8a56-bb6c81fa8efb.png)

If user refreshes the page the check is gone and the admin shows opted out
![image](https://user-images.githubusercontent.com/57115907/69783662-d2417e80-1168-11ea-9fe8-26a6cf552dc0.png)

Please review if this is acceptable.

**Comment by tofumatt** [comment]
It being opted-in after the user opts-out isn't good; I'll take a look at that and try to push a fix now…

**Comment by cole10up** [comment]
**Tested**

Setup while selecting opt-in and navigated to the admin page to confirm it took effect
![image](https://user-images.githubusercontent.com/57115907/70027333-c2ee7680-1556-11ea-9ed7-7452a122fa47.png)

Unchecked box to opt out
![image](https://user-images.githubusercontent.com/57115907/70027356-d3065600-1556-11ea-9e01-1f9fea481d61.png)

Navigated to a different tab within the window
![image](https://user-images.githubusercontent.com/57115907/70027390-e31e3580-1556-11ea-9ec5-7a5227d8f1c7.png)

Navigated back to Admin tab
![image](https://user-images.githubusercontent.com/57115907/70027412-efa28e00-1556-11ea-8220-e6acc565087f.png)

Checked general functionality with opting out, refreshing page, navigating around and back to the admin. All looks good.

Passed QA ✅
