### ISSUE TITLE
Alphabetically sort imports

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7275]
## Feature Description

As discussed [here](https://github.com/google/site-kit-wp/pull/7271#discussion_r1257551337), all imports should be alphabetically ordered. We can use a config like [eslint-sort-imports](https://eslint.org/docs/latest/rules/sort-imports) to enforce this project-wide.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All imports in the JS part of the code base should be alphabetically sorted within their respective groups. (The groups being External, WordPress and Internal).
* This rule should be enforced using the ESLint [sort-imports](https://eslint.org/docs/latest/rules/sort-imports) rule.
    * The [`allowSeparatedGroups`](https://eslint.org/docs/latest/rules/sort-imports#allowseparatedgroups) option should be enabled to make sure it works with the aforementioned grouped imports. 

## Implementation Brief

* Modify `.eslintrc.json`:
  * add `sort-imports` to the `rules` list
    * It should be having `error` as the first argument, you can follow [this one](https://github.com/google/site-kit-wp/blob/fb17d0d53afe7d3a1ae9fdf52a0fae77eb23df5f/.eslintrc.json#L58-L65) for the format
    * Include `allowSeparatedGroups` in the options object, which should be set to `true`
  * Fix all rule violations, hopefully to with `npm run lint:js -- --fix`

### Test Coverage

* No changes needed

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit – this is a good idea, although I'm not sure this will work with the grouped imports that we use. [There is an eslint rule for this too](https://github.com/WordPress/gutenberg/blob/d233bc219a45883380bf2c72fa614f13079ceb7e/packages/eslint-plugin/docs/rules/dependency-group.md) which we had used in the past but it became problematic due to our use of aliases for internal packages that it was unable to understand as such (it thought they were external) so we eventually removed that. It seems this is still an issue, but also wouldn't solve the sorting either 😄

**Comment by nfmohit** [comment]
Ah, I see, that makes sense. I wish [this rule](https://github.com/WordPress/gutenberg/blob/d233bc219a45883380bf2c72fa614f13079ceb7e/packages/eslint-plugin/docs/rules/dependency-group.md) could allow marking certain packages as internal (will try and see if I can send in a PR this weekend). Thanks!

**Comment by aaemnnosttv** [comment]
> I wish [this rule](https://github.com/WordPress/gutenberg/blob/d233bc219a45883380bf2c72fa614f13079ceb7e/packages/eslint-plugin/docs/rules/dependency-group.md) could allow marking certain packages as internal (will try and see if I can send in a PR this weekend). Thanks!

That would be great! Regarding this issue, we'd also need to find a way to allow alpha sorting by group, correct?

**Comment by kuasha420** [comment]
@aaemnnosttv @nfmohit Noting here that [allowseparatedgroups](https://eslint.org/docs/latest/rules/sort-imports#allowseparatedgroups) solves our requirement for grouped imports.

**Comment by aaemnnosttv** [comment]
Nice! That sounds perfect. Thanks @kuasha420 👍

**Comment by tofumatt** [comment]
ACs here are 👍🏻

**Comment by tofumatt** [comment]
Added a note to the IB that the rule violations should be fixed, which was implied but worth spelling out. 🙂 

IB ✅

**Comment by 10upsimon** [comment]
While `sort-imports` does work, and correctly flags incorrect entries, it does not offer the ability to fix multi line errors via the `--fix` flag. This unfortunately results in the need to manually edit 100's and 100's of lines of imports. As per the official plugin page, only grouped imports can be automatically fixed:

> The --fix option on the command line automatically fixes some problems reported by this rule: multiple members on a single line are automatically sorted (e.g. import { b, a } from 'foo.js' is corrected to import { a, b } from 'foo.js'), but multiple lines are not reordered.

Failing this, it was recommended that we look into the eslint plugin [eslint-plugin-perfectionist](https://eslint-plugin-perfectionist.azat.io/). This, however, appears to require node 16.x, or at least a subset of package upgrades that are limited by our current node 14.x usage. Using the default "out the box" configuration for the plugin, the following eslint runtime error is observed:

```
SyntaxError: Failed to load plugin 'perfectionist' declared in '--config': Unexpected token '||='
Referenced from: /Users/simondowdles/wp-local-docker-sites/sitekit-10uplabs-com/wordpress/wp-content/plugins/google-site-kit/.eslintrc.json

/Users/simondowdles/wp-local-docker-sites/sitekit-10uplabs-com/wordpress/wp-content/plugins/google-site-kit/node_modules/@typescript-eslint/scope-manager/dist/referencer/ClassVisitor.js:123
        withMethodDecorators ||=
                             ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/simondowdles/wp-local-docker-sites/sitekit-10uplabs-com/wordpress/wp-content/plugins/google-site-kit/node_modules/@typescript-eslint/scope-manager/dist/referencer/Referencer.js:20:24)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
Process finished with exit code -1
```

Downgrading to older version of the plugin, however, rear further issues such as:

```
SyntaxError: Failed to load plugin 'perfectionist': t.options is not a function
```

At this point, it is not worth sinking more hours into this, as multiple versions combinations of the plugin and eslint are leading to further unrelated package or dependency errors. 

Closing this out as `wontfix`, but this should be explored in a new issue where we can full investigate whether it is possible to get the sort-imports to work on staged files only, as opposed to a global eslint config.
