### ISSUE TITLE
Prevent error duplication in Analytics setup & settings

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7276]
## Bug Description

Duplicate errors appearing on Analytics setup & settings page when user a/c which have only 'View' access try to set up analytics.

## Steps to reproduce

- Start set up for Analytics without having granted the edit scope
- Choose an account that the user only has Viewer-level permissions for
- Choose "Set up a new property".
- Submit the form
- When prompted, grant the additional scope to create the property
- See duplicate errors on settings page.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/94359491/a704af82-b144-4c89-8576-caf8e7525aaf)

https://github.com/google/site-kit-wp/assets/94359491/4308917f-0034-46ac-9a45-a209db58caed

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Since Universal Analytics has been removed from Site Kit's UI, when creating a new GA4 Property, the UA Insufficient Permissions error should not be rendered.

## Implementation Brief

* In `assets/js/modules/analytics/components/setup/SetupForm.js`:
    * Remove rendering the `StoreErrorNotices` component for the `analytics` data store. This should be a safe fix since we do not allow creating or editing UA properties anymore.

### Test Coverage

* No new tests required.

## QA Brief

* Follow the steps to reproduce.
* Verify that the error notices for UA are not displayed.

## Changelog entry

* Update Analytics setup and settings to make sure we don't show duplicate errors.

**Comment by nfmohit** [comment]
Just a heads-up that this happens in both Analytics setup & settings screens, and the solution would be quite similar I believe. As a result, I have slightly updated the title and description to refer that.

**Comment by techanvil** [comment]
AC :white_check_mark: 
IB :white_check_mark: 

Nice one @jimmymadon :)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that on dev branch error duplication error is now resolved.
- Verified that on dev branch UA error is not showing.

<details>

https://github.com/google/site-kit-wp/assets/94359491/0d8e6690-899e-431b-865e-ff61e4cc74e0


![image](https://github.com/google/site-kit-wp/assets/94359491/5298aa51-1688-4004-8f4e-05ea6efc9235)

</details>
