### ISSUE TITLE
Remove `googlesitekit_tracking_optin` option when resetting plugin

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#728]
## Bug Description

Noted in QA on https://github.com/google/site-kit-wp/issues/633.

Resetting the plugin using the 'Reset Site Kit' link on the settings screen, using the CLI or deleting the plugin should remove the `googlesitekit_tracking_optin` option. Each of these events should reset tracking to the default opted out state.

## Steps to reproduce

1. Enable the plugin.
2. Note that tracking is opted out by default (unchecked). leave unchecked and complete setup. 
3. Go to Site Kit->Settings->Admin Settings, Check to Op In to tracking box to enable tracking, then click "Reset Site Kit" and confirm.
4. You are now back at the setup step 1, note that tracking is **incorrectly** opted in (checked)

Expected result: after resetting site kit, tracking opt in should return to default, opted out (unchecked). The database option `googlesitekit_tracking_optin` should be removed.

## Screenshots

![image](https://user-images.githubusercontent.com/2676022/67697316-f5142380-f96d-11e9-9cb3-e1ec6f5ff4bd.png)

![image](https://user-images.githubusercontent.com/2676022/67697526-4d4b2580-f96e-11e9-9713-6a918ef17559.png)

## Additional Context

 - PHP Version: 7.3
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome Dev
 - Plugin Version [e.g. 22] develop branch  
 - Device: [e.g. iPhone6] Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@felixarntz this issue is a subset of #351

**Comment by felixarntz** [comment]
Covered now via #809.
