### ISSUE TITLE
Increase Banner Notification space between Title and Description

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7280]
## Feature Description

When testing the Ad Blocking Recovery epic, we noticed that the space between the title and description in our Banner Notification is too low compared to the Figma mocks and looks cramped.

<img width="1075" alt="ABR_SuccessBannerNotification" src="https://github.com/google/site-kit-wp/assets/1721319/fa949209-a9a7-4573-9e81-6f453893cb75">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The space between the title and description in all Banner Notifications should be as per the [Figma Mock](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?node-id=766%3A3583&mode=dev).
* The Image Illustration should be vertically centred with the Text and Button [(comment)](https://github.com/google/site-kit-wp/issues/7280#issuecomment-1881181648). 

## Implementation Brief

* Update `assets/sass/components/global/_googlesitekit-publisher-wins.scss` adding the following CSS:
```
.googlesitekit-publisher-win__desc > p {
    margin: 5px 0 26px;
}
```
* Update the `.googlesitekit-publisher-win__image-small` class in `assets/sass/components/adsense/_googlesitekit-adsense-ad-blocking-recovery.scss`, removing the existing `text-align` attribute, replacing it with:
```
display: flex;
align-items: center;
justify-content: center;
``` 
* Add a new story to the `BannerNotification` in story book called `With Win Image` that shows the component when a WinImageSVG is set such as `WinImageSVG={ () => <SuccessSVG /> }`

### Test Coverage

* Add a new VRT for the `BannerNotification` when a `WinImageSVG` is set.

## QA Brief

* Test the Ad Blocking Recovery success banner for both the ACs.
    * Connect AdSense (use the tester plugin to mock site and account status to ready if required). Then activate Ad Blocking recovery by going to Settings -> AdSense and going through the Ad Blocking recovery steps. Once successful, the banner will appear.
* Smoke test other plugin module setups to ensure other banner notification messages (success notifications) are displayed correctly (the right side image, if exists, will now be vertically centred instead of aligned to the top).
* Smoke test the plugin in general by clearing all browser cache and site data so that other notification banners (gathering data, zero data, etc) are rendered correctly.

## Changelog entry

* Update banner notifications to have more space between title and description.

**Comment by bethanylang** [comment]
@sigal-teller @marrrmarrr Curious for your thoughts here – we pulled this out of the ABR Bug Bash because it's the case for all notification banners, not just the one for that feature. Thanks!

**Comment by bethanylang** [comment]
@jimmymadon Yes, just to be extra safe!

@sigal-teller @marrrmarrr Could I ask you to please confirm that you're okay with updating the spacing on the banner notifications based upon the [Figma mock](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?node-id=766%3A3583&mode=dev)? Thanks!

**Comment by sigal-teller** [comment]
@bethanylang @jimmymadon Yes let's update the banner based on the Figma mocks. In addition to spaces, note that the illustration should be vertically centered with the text+button. Currently the illustration is aligned to the top I think.

**Comment by benbowler** [comment]
Completed IB and added an estimate of 7 to allow for QA/UX review.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that ABR set up notification updated as per AC's.
- Done smoke testing and verified that all notifications are showing and updated as per AC.

<details>


![image](https://github.com/google/site-kit-wp/assets/94359491/9ace3c57-b884-45b7-9447-8b81f5c981a8)

![image](https://github.com/google/site-kit-wp/assets/94359491/8854a069-d10f-4b1d-9975-17cad6dcafde)

![image](https://github.com/google/site-kit-wp/assets/94359491/1bf91064-e7a9-4507-99b7-ccc8ed51e69d)

![image](https://github.com/google/site-kit-wp/assets/94359491/35802546-6b76-4aab-863f-c3678e399411)

![image](https://github.com/google/site-kit-wp/assets/94359491/0ea534c9-1523-4645-abdc-bddcf95f50b2)

![image](https://github.com/google/site-kit-wp/assets/94359491/af11664d-0f07-4964-994d-909b33ea9189)

![image](https://github.com/google/site-kit-wp/assets/94359491/c04fac04-7d15-4e67-910f-a1b72c3fc160)

![image](https://github.com/google/site-kit-wp/assets/94359491/260765a1-c75d-4967-b714-fccebddb51fb)

![image](https://github.com/google/site-kit-wp/assets/94359491/12538f82-674c-4fcd-a33e-12f5f71d72b0)

![image](https://github.com/google/site-kit-wp/assets/94359491/5439db99-526a-4927-ab34-84a249ab690c)

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified Analytics set up on new site using new and old analytics a/c. 
- Verified on a site which connected through UA property.
- Verified analytics settings view and edit mode.
- Verified analytics setup on old site using old analytics a/c.
- Ensure that setup new property drop down and related functionality are working.
- Verified that analytics snippet is showing correctly under page source.
- Verified that UA tags are not showing on updating to dev environment.
- Verified that if GA4  property have custom dimensions then they are appearing under Analytics snippet.
- Verified that ad conversion id showing under Analytics snippet.

![image](https://github.com/google/site-kit-wp/assets/94359491/db0b3543-8946-4388-8c08-5f051dd7e932)
