### ISSUE TITLE
Improve Behaviour of 'Maybe Later' link on Connect GA CTA for Key Metrics Widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7285]
## Bug Description

While testing #6265 I discovered that if you click on the 'Maybe later' link on the new Key Metrics Connect Google Analytics CTA, it does disappear, but when you connect Analytics again, and then disconnect later, the CTA no longer appears. There was a discussion on the best way to implement this [in the comments](https://github.com/google/site-kit-wp/issues/6265#issuecomment-1627860092) but due to its complexity it was decided that we should create a ticket. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The 'Connect Google Analytics CTA' banner within the Key Metrics widget area should reappear in the below scenario even when GA4 is connected and disconnected again, after dismissing the banner on the first disconnection.
	* In other words, any existing dismissal of this CTA should be invalidated when GA4 is connected
* As per the AC of #6265, the banner should continue to be rendered only if more than 2 of the selected metrics are dependent on GA4 and GA4 was disconnected after the widget's setup.

#### Implementing the `remove` Method

In `includes/Core/Dismissals/Dismissed_Items.php`:

* Introduce a new method `remove`, which receives an argument `$item` (string). This method is responsible for removing the provided `$item` from the `dismissed_items` option.
    * Retrieve the currently dismissed items via the `Dismissed_Items::get` method, resulting in an array of dismissed items.
    * Remove the provided `$item` from the array of dismissed items.
    * Persist the updated array of dismissed items using the `User_Setting::set` method.

#### Invocation of the `remove` Method During Module Activation

In `includes/Modules/Analytics_4.php`:

* Implement the `Module_With_Activation` interface in the `Analytics_4` class.
* Implement a new method `on_activation`. This method should invoke the `Dismissed_Items::remove` method, passing `key-metrics-connect-ga4-cta-widget` as the item to remove.

### Test Coverage

* In `tests/phpunit/integration/Core/Dismissals/Dismissed_ItemsTest.php`, add a new test `test_remove`, that tests the `remove` method.
* In `tests/phpunit/integration/Modules/Analytics_4Test.php`, add a new test `test_on_activation` that tests the `on_activation` method.

## QA Brief

* Click on the "Maybe later" CTA on the GA Disconnected widget introduced on #6265.
* Reconnect and disconnect the Analytics module.
* The widget should correctly reappear. 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – I added a sub-point to clarify the first – is that correct?

Regarding the second point, is this a change or only here to ensure that this behavior is preserved?

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 I have tried this on two sites and when I disconnect and reconnect Analytics after clicking on the 'Maybe later' link, the CTA still does not appear asking me to complete the user survey.  I tested this on the `develop` branch.

**Comment by kuasha420** [comment]
@wpdarren, sorry for the confusion, but this issue is about the [Connect GA full Width CTA](https://github.com/google/site-kit-wp/issues/6265), not the Key metrics CTA. Thank you.

**Comment by wpdarren** [comment]
@kuasha420 apologies too for not spotting this, bit slack on my part.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@kuasha420 On the Connect GA CTA, the `maybe later` no longer appears.  See screenshot. 

![image](https://github.com/google/site-kit-wp/assets/73545194/6c2f7666-5230-4372-95ab-229bde04f148)

I connected Site Kit with Analytics. Went through user input survey, could see the KMW tiles on the widget. I then disconnected Analytics and the CTA appeared above.  I did notice this ticket in QA, and wonder if that's overwriting this ticket, and this no longer applies.  A little confused here. c.c. @jimmymadon into this too.

**Comment by wpdarren** [comment]
@jimmymadon the issue is, this ticket is merged and part of 1.107.0. 🤔

**Comment by wpdarren** [comment]
### QA Update: ✅ 

As per conversation with @jimmymadon on Slack. We need to move this to approved. Unable to test until #7278 is in QA. I have added a comment to ensure that we test this scenario in that ticket which will be post-bug bash.

**Comment by aaemnnosttv** [comment]
Will revisit in #7278
