### ISSUE TITLE
Tag options are not removed when AdSense is deactivated

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7286]
## Bug Description

As reported by @aaemnnosttv in Bug Bash:

When a user deactivates the AdSense after using the Ad Blocking Recovery feature, the tag options are not removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Ad Blocking Recovery tags stored in the database should be deleted when the AdSense module is deactivated

## Implementation Brief

- In `includes/Modules/AdSense.php`:
  - Update the `on_deactivation` method:
    - Check if Ad Blocking Recovery tags are saved in the database. To do so, call the `Ad_Blocking_Recovery_Tag::has()` method.
    - If they are saved in the database, call `Ad_Blocking_Recovery_Tag::delete()` method to remove the option from the database.
    - The `Ad_Blocking_Recovery_Tag` class is instantiated to the `$ad_blocking_recovery_tag` property.

### Test Coverage

- In `tests/phpunit/integration/Modules/AdSenseTest.php`:
  - Update the `test_on_deactivation` test case to verify that the option is removed after deactivation.

## QA Brief

- Setup the Ad Blocking Recovery tag placement:
  - Setup Site Kit with the `adBlockerDetection` feature flag enabled, with Analyics (GA4) and AdSense connected.
  - Use the Tester plugin to set the reference date 3+ weeks in advance.
  - Navigate to the Monetization section on the Dashboard, click "Set up now" on the Ad Blocking Recovery CTA, and complete the first stage of the setup to place the tag.
- Verify the tag exists in the database by querying the `googlesitekit_adsense_ad_blocking_recovery_tag` option.
- Disconnect the AdSense module.
- Verify the tag has been removed from the database - the `googlesitekit_adsense_ad_blocking_recovery_tag` option should no longer exists

## Changelog entry

* Fix AdSense options cleanup issues.

**Comment by kuasha420** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that Ad Blocking Recovery tags stored in the database gets delete when the AdSense module is deactivated.
- Tested for both UA and Ga4 Dashboard.
- Verified that ABR set up CTA appears on main dashboard and in under settings after user disconnect AdSense.
- Tested after connecting and disconnecting AdSense few times.

<details

https://github.com/google/site-kit-wp/assets/94359491/d78ca8c4-5806-4b81-b72f-daae560b7867

</details>
