### ISSUE TITLE
Add ABR setup information to Site Health

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7290]
## Feature Description

Add output in Site Health that indicates that Ad Blocking Recovery feature is set up.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following debug fields should be exposed in the AdSense modules debug data unconditionally:
    * `adsense_setup_completed_timestamp`
        * Label: `AdSense setup completed at`
        * Debug: `$settings['setupCompletedTimestamp']`
        * Value: date formatted according to the site's locale. If the setting is empty, it should be `Not available`
* The following Ad Blocking Recovery related debug fields should only be exposed in the AdSense modules debug data when `adBlockerDetection` feature flag is enabled.
    * `adsense_abr_use_snippet`
        * Label: `Ad Blocking Recovery snippet placed`
        * Debug:  `yes` if `$settings['useAdBlockingRecoverySnippet']` is true, `no` otherwise.
        * Value:  `Yes` if `$settings['useAdBlockingRecoverySnippet']` is true, `No` otherwise.
    * `adsense_abr_use_error_protection_snippet`
        * Label: `Ad Blocking Recovery error protection snippet placed`
        * Debug:  `yes` if `$settings['useAdBlockingRecoveryErrorSnippet']` is true, `no` otherwise.
        * Value:  `Yes` if `$settings['useAdBlockingRecoveryErrorSnippet']` is true, `No` otherwise.
    * `adsense_abr_setup_status`
        * Label: `Ad Blocking Recovery setup status`
        * Debug: `$settings['adBlockingRecoverySetupStatus']` 
        * Value:  one of the following depending on the value of `adBlockingRecoverySetupStatus`
            * `""` (empty string) -> `Not set up`.
            * `AdSense\Setting::AD_BLOCKING_RECOVERY_SETUP_STATUS_TAG_PLACED` -> `Snippet is placed`
            * `AdSense\Setting::AD_BLOCKING_RECOVERY_SETUP_STATUS_SETUP_CONFIRMED` -> `Setup complete`
* The debug fields should be ordered according to their order in `AdSense\Setting::get_default` class. 
* All debug values should be non-translated
* All "value" values should be translated

## Implementation Brief

- In `includes/Modules/AdSense.php`, update the `AdSense::get_debug_fields` method:
  - Instead of directly returning the array, contain it in a variable, such as `$fields`.
  - After the existing items in the `$fields` array, add the `adsense_setup_completed_timestamp` field.
    - For its `value` property, we need to format the AdSense setup completed timestamp according to the site locale. To do this, we can use the [`date_i18n` function](https://developer.wordpress.org/reference/functions/date_i18n/). It would be easier to use [`wp_date`](https://developer.wordpress.org/reference/functions/wp_date/), but it seems to have been introduced in WP 5.3 (SK supports WP 5.2).
  - Now, check if the `adBlockerDetection` feature flag is enabled. If so:
  	- Add the ABR specific settings to the `$fields` array.
  - The items should be added similar to how it is done for the existing fields, with `label`, `debug`, and `value` properties as described in the ACs. The value of the `value` property should be translated.
  - Verify that the order of the added items matches the order of the respective settings in `AdSense\Setting::get_default` method.
  - Finally, return the `$fields` array.

### Test Coverage

- In `tests/phpunit/integration/Modules/AdSenseTest.php`:
  - Add test cases for the `AdSense::get_debug_fields` method (similar to test cases for `Analytics::get_debug_fields` added in `tests/phpunit/integration/Modules/AnalyticsTest.php`) to verify the difference of debug fields present with or without the `adBlockerDetection` feature flag.

## QA Brief

- Set up Site Kit and complete AdSense connection.
- Go to SK Site Health information.
- Verify that you see `AdSense setup completed at` info with the date on which AdSense was set up.
- Turn on the `adBlockerDetection` feature flag (do not set up ABR yet).
- Verify that the following additional info show up:
  - `Ad Blocking Recovery snippet placed` with `No`
  - `Ad Blocking Recovery error protection snippet placed` with `No`
  - `Ad Blocking Recovery setup status` with `Not set up`
- Start setting up ABR and as you go through each step (e.g. place ABR and error protection snippets), check back Site Health to verify this information has been updated accordingly.

## Changelog entry

* Add Ad Blocking Recovery information to Site Health.

**Comment by aaemnnosttv** [comment]
Thanks @kuasha420 – I made a few small tweaks but otherwise LGTM with one question:

> * The debug fields should be sorted according to their order in `Setting` class. 

Would you please clarify what you mean by this?

**Comment by kuasha420** [comment]
@aaemnnosttv I have added clarification on that. It's not a big deal but wanted to make sure that their ordering is consistent. Thank you.

**Comment by aaemnnosttv** [comment]
Thanks @kuasha420 – AC ✅

**Comment by kuasha420** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified ABR set up information to Site health as per AC.
- Verified Site health of ABR is getting update as per ABR set up status.
- Also, tested by changing settings in AdSense Settings.
- If `Ad Blocking Recovery error protection snippet placed` then Status is 'Yes' otherwise 'No'.
- If 'Ad Blocking Recovery snippet placed' the Status is 'Yes' otherwise 'No'.
- If ABR is not set up then `Ad Blocking Recovery setup status`  is not set up and if setup is complete then status is 'Setup Complete'. 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/77a75401-5f09-466a-80f4-12d3a8f62547)


https://github.com/google/site-kit-wp/assets/94359491/f9e49dd1-a685-4533-bea3-b2f62b468db5


</details>
