### ISSUE TITLE
Show a loading state for the AdSense Settings View page until all required states have loaded

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7291]
## Bug Description

As reported by @kuasha420 in Bug Bash: A layout shift occurs in AdSense Settings View after ABR CTA is loaded.

---

Update from @techanvil: It's not possible to avoid a layout shift with the settings view structured as it stands. This is because the **Ad blocking recovery** section and the CTA are both conditionally rendered, and in fact it's possible that neither will be rendered. To illustrate, each of these three versions of the Settings view can be expected once all the state has loaded (as well as additional permutations - the **Web Stories Ad Unit** section is also optional, but its state is known immediately without waiting for things to load):

_No **Ad blocking recovery** section or CTA:_
![image](https://github.com/google/site-kit-wp/assets/18395600/8c539f62-b842-492a-ab70-27f63771eaab)

_With the **Ad blocking recovery** section present:_
![image](https://github.com/google/site-kit-wp/assets/18395600/1c2844bf-e2a7-4d05-8df3-f23a3fdee79d)

_With the CTA present:_
![image](https://github.com/google/site-kit-wp/assets/18395600/1a69ded0-7c43-44bd-8426-5dace3309472)

The appropriate solution, consistent with approach taken for https://github.com/google/site-kit-wp/issues/7747, is to show the static parts of the page in a loading state while the rest of the state is being resolved, at which point the whole AdSense Settings view can be rendered in its loaded state.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The static sections of the AdSense settings view (as seen in the first screenshot in the Bug Description) should be displayed in a loading state until all of the required state to show the view is available.
  - The loading state should use preview blocks for any loading areas to minimize layout shifts on load.
  - A layout shift is still to be expected when the loading state resolves if the **Ad blocking recovery** section or the CTA is rendered.

## Implementation Brief
        
* Edit `assets/js/modules/adsense/components/settings/SettingsView.js`
  * Introduce new variable `loading`, and for value use a check if - `getSettings()` selector on `MODULES_ADSENSE` is `undefined`
  * Conditionally render [this block](https://github.com/google/site-kit-wp/blob/38cefdc217ba13cff913a2918947014eb2d34a18/assets/js/modules/adsense/components/settings/SettingsView.js#L115-L151), if  it is not `loading`
    * Otherwise render  2 `PreviewBlock` components. Adjust the width, spacing and height to match the width of these three fields in first row, and height of the text
  * Do the same for remaining `googlesitekit-settings-module__meta-items` sections
    * The one holding `AdSense Code`, and `Excluded from ads`
    * For [`webStoriesAdUnit`](https://github.com/google/site-kit-wp/blob/706c4a9e45b072b3a174d57defe3b169ab5519bc/assets/js/modules/adsense/components/settings/SettingsView.js#L175)
      * Update the component to include a conditional rendering logic that first checks if `webStoriesActive` is true
      * Inside the webStoriesActive check, add a secondary conditional rendering:
        * If `loading`, render the `PreviewBlock` component
        * Otherwise render the existing markup 
  * For `adBlockingRecoverySetupStatus` 
    * Above this [line](https://github.com/google/site-kit-wp/blob/38cefdc217ba13cff913a2918947014eb2d34a18/assets/js/modules/adsense/components/settings/SettingsView.js#L193)
      * Include check for `loading` to render `PreviewBlock` component. Adjust the width and height of `PreviewBlock` to approximately match the `AdBlockingRecoverySetupCTANotice` component. Since `adBlockingRecoverySetupStatus` value depends on settings being loaded to determine which component to render, or should it be shown at all, it has been [agreed](https://github.com/google/site-kit-wp/issues/7291#issuecomment-1843082078) to always display a loading block here.

### Test Coverage

* Update any failing test, or VRT reference image

## QA Brief

* Navigate to the Adsense settings view page.
* Ensure the loader (`ProgressBar`) remains visible until the Ad Blocking Recovery status is loaded.
* Verify there is no layout shift due to the delay in loading the Adblocking Recovery CTA / status.
* The AC states to use the preview blocks; however, it was decided to use the progress bar with the small width only for the ABR area. Please take a look at this [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1704989615878909) conversation.
* Note: Comprehensive coverage for all screen sizes is not feasible due to the responsive nature of the Adblocking Recovery CTA / status.

## Changelog entry

* Update the AdSense settings view to show the progress bar while AdSense information is being loaded.

**Comment by tofumatt** [comment]
ACs sound good here 👍🏻

**Comment by zutigrm** [comment]
@tofumatt Thanks for the feedback,

> The IB here mentions adding more data to the inline JS base data, but the ACs are about showing loading indicators really. As @techanvil mentioned, we won't always be able to prevent layout shifts with unknown data.
> But I'd prefer not to add stuff to the base JS data. The more data we assume is "pre-loaded" on a page the harder it will be to ever migrate to a true single-page app. So let's avoid doing that where possible, and instead show loading indicators when we don't have the data instead of preloading it from PHP on page-load.

Since we should avoid inline data part, we have 2 options for `adBlockingRecoverySetupStatus` section then:
* Include loader for that section, which after the loading of settings is done - this section will either be shown, or not and spacing reduced to accommodate the empty space
* Not show the loader, so in case this data is available it will either appear after other parts have loaded, or no change will happen

Which out of these two is more acceptable?

> Also, please use "Back end" and "Front end" over "BE" and "FE" 😄 . It's harder to read/scan the abbreviations and it's worth being as clear-as-possible in the IB, especially for text headings

Noted, thanks for the info 😄 

> I'm not quite sure what this is saying, could you clarify/rephrase that bit? 😅

I will re-visit this part, basically I meant that additional check should be done only if existing `webStoriesActive` condition is met

**Comment by tofumatt** [comment]
Let's go with the first option: _"Include loader for that section, which after the loading of settings is done - this section will either be shown, or not and spacing reduced to accommodate the empty space"_ 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t I'd like to highlight a UX/UI observation.  When Ad Blocking Recovery is set up, and I go to the AdSense settings view, the progress bar appears, but when the settings load, they shift slightly.  The progress bar doesn't appear in the same location where the settings are displayed.  You can see it in action in the screenshot below. 

https://github.com/google/site-kit-wp/assets/73545194/2d9efe8a-cbd6-4bfd-b1cb-e0d98f0f53b8

The progress bar appears in the correct location when the ABR setup banner appears.

Interested in your thoughts.

**Comment by hussain-t** [comment]
@wpdarren, the height comes from the progress bar. Previously, I set a single progress bar, which was common for both the ABR setup CTA and the status. Please check the following screencasts, where I have two separate progress bars. LMK, if that's good, I will create a follow-up PR. Please note that there will be some slight layout shifts for the smaller screens.

**ABR Setup CTA**

https://github.com/google/site-kit-wp/assets/24408261/d887fa06-fb8b-4c07-8ddd-8bc4b32d8026

----

**ABR Status**

https://github.com/google/site-kit-wp/assets/24408261/c2dc423b-d811-4df4-b9c5-6a428dad63b3

**Comment by wpdarren** [comment]
@hussain-t Personally, I think that looks much better on Desktop.  The mobile layout shift, I guess, is less of a problem because the user has to scroll down to that section anyway, so it'll likely be loaded by the time they scroll.  I don't know the usual process when moving slightly away from the AC/IB, so I wondered if we should get @zutigrm thoughts.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

I have sent this ticket back to Execution for the conversation that [started here](https://github.com/google/site-kit-wp/issues/7291#issuecomment-1893505574) about the UX/UI of the loading state.

**Comment by hussain-t** [comment]
@wpdarren, we have diverged the implementation from the IB. The IB states to use the preview blocks for other settings and ABR status. However, it was decided to use the progress bar with a small width **_only_** for the ABR area. Please take a look at this [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1704989615878909) conversation.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@hussain-t, thank you for making the change; it looks great now! 

**Verified:**

- The progress bar remains visible until the Ad Blocking Recovery CTA and status is loaded.
- There is no layout shift due to the delay in loading the Adblocking Recovery CTA / status.
- I completed checks on different viewports to ensure no UX/UI issues occurred. 

<details>
 <summary>Screencasts</summary>

https://github.com/google/site-kit-wp/assets/73545194/8959362e-0d5b-4f10-a921-93b7cf945a76
https://github.com/google/site-kit-wp/assets/73545194/2e843676-cb17-4326-b5b2-0e885120a972

</details>
