### ISSUE TITLE
Add step transition animation in ABR setup

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7292]
## Feature Description

As reported by @kuasha420 in Bug Bash:

There should be a "subtle" transition animation when the step is changed from 1 to 2, currently it feels abrupt. 

See https://mui.com/material-ui/react-stepper/#vertical-stepper for an example of it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Stepper` component should have a transitional animation when changing the current step. This should be modelled on the MUI vertical stepper linked in the description - the new step should slide up into view, replacing the previous step.
* This animation should be evident on the Ad Blocking Recovery setup page, which is currently the only usage of the `Stepper` component in the plugin.

## Implementation Brief

As discussed [here](https://stackoverflow.com/questions/3508605/how-can-i-transition-height-0-to-height-auto-using-css) it doesn't seem to be possible to transition an HTML element from zero height to the height of its content using CSS only. Therefore we take an approach using JS to set the height to transition to when setting a step to be active. Furthermore as discussed [here](https://stackoverflow.com/a/56914733), we take the approach of setting the height to `0` for a non-active step, which means we can determine its content height by using its `scrollHeight` property.

- Update the `Step` component so it unconditionally renders its content, adding a CSS class to the content div for the `active` status.
- Use the principles outlined above to implement the transition.
- Additionally, apply `visibility: hidden` to the non-active steps' content in order to hide their hidden content from screen readers and prevent it from being tabbed into.
- Refer to/finish off this draft [PR](https://github.com/google/site-kit-wp/pull/7541/files).

### Test Coverage

- Update the `Stepper` tests to accommodate these changes.

## QA Brief

- Set up Site Kit with the AdSense module.
- Go to the Ad Blocking Recovery setup.
- When going through the steps, verify that there is an animation as described in the ACs in between each step.
- Verify the Storybook story for Stepper and ensure that has the animation as well.

## Changelog entry

* Add a step transition animation to the Ad Blocking Recovery setup widget.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@nfmohit I have two observations to highlight. 

1. When I click on the `Set up now` button, there's no animation on the button, the AdBlocking Recovery CTA disappears, and the dashboard loads.  Then a few seconds later I am taken to the first step of the setup.  

2. On the first step of the set up there are no CTAs or content in between the two sections. When I click on the cancel link though they flash for a few seconds and then I am taken back to the dashboard as expected. 

The screencast below showcases both issues. 

https://github.com/google/site-kit-wp/assets/73545194/8408bafd-ae20-4a9d-b84c-59885217f2e8

**Comment by nfmohit** [comment]
Thank you @wpdarren. I've added a follow-up PR #7910 that aims to address the second issue.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified issue reported [above](https://github.com/google/site-kit-wp/issues/7292#issuecomment-1824279743) is now resolved.
- Verified transition animation is implemented successfully ABR set up steps.

<details>


https://github.com/google/site-kit-wp/assets/94359491/b2aba25d-f5f5-4d18-b209-578e53cc3619


https://github.com/google/site-kit-wp/assets/94359491/2a164b6d-5be4-4df4-b133-f459e1c88fdd

</details>
