### ISSUE TITLE
CTAs on main dashboard reappear if user selects "Maybe later" but does not interact with resulting tooltip

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7294]
## Bug Description

As reported by @kuasha420 in Bug Bash:

If a user selects "Maybe later" on the ABR CTA on the main dashboard but does not interact with the resulting left admin tooltip before refreshing the page, the CTA returns. See https://app.asana.com/0/1204478087069244/1204955754125349/f for additional discussion.

The same applies to the AdSense Connect and Key Metrics Setup CTAs which we also need to address in the same manner.

## Steps to reproduce

1. On the main dashboard, select "Maybe later" on the ABR CTA
2. Do _not_ interact the left admin tooltip about how to retrieve the CTA later
3. Refresh the dashboard
4. ABR CTA reappears

Repeat the above for the AdSense Connect and Key Metrics Setup CTAs to see the same behaviour in effect for those widgets.

## Screenshots

[screen-capture (2).webm](https://github.com/google/site-kit-wp/assets/12189958/7821c94d-37f0-42c1-88c5-1026727fc0c5)

https://github.com/google/site-kit-wp/assets/18395600/b5f01d04-eee2-4110-acb1-7767afdc87fc

https://github.com/google/site-kit-wp/assets/18395600/0023ba48-ddc5-4a78-bde7-8aa22a2387b8

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For each of the Ad Blocking Recovery, AdSense Connect, and Key Metrics Setup CTAs:
  * The CTA should be dismissed when the "Maybe later" button is pressed, rather than when the tooltip is dismissed.
  * The tooltip should still be displayed as usual.

#### Ad Blocking Recovery

In `assets/js/modules/adsense/components/dashboard/AdBlockingRecoveryWidget.js`:

* Remove the `onDismiss` prop currently passed to `AdminMenuTooltip`.
* Modify the `dismissCallback` passed to `BannerActions` to include a call to the `dismissItem` action. 

#### AdSense Connect

In `assets/js/modules/adsense/components/dashboard/AdSenseConnectCTAWidget.js`:

* Remove the `onDismiss` prop currently passed to `AdminMenuTooltip`.
* Remove the `handleDismissTooltip` callback function, as it is no longer need it here.

In `assets/js/modules/adsense/components/common/AdSenseConnectCTA/index.js`:

* Modify the `handleDismissModule` callback function passed to the `onClick` prop of `Link` to include a call to the `dismissItem` action.

#### Key Metrics Setup

In `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`:

* As with the other CTAs, remove the `onDismiss` prop currently passed to `AdminMenuTooltip`.
* Modify the `dismissCallback` function, which currently dispatches the `dismissItem` action, also to call the `showTooltip` function.
* Pass the `dismissCallback` function (now responsible for dismissing the CTA and showing the tooltip) to the `onActionClick` prop of `KeyMetricsCTAFooter`.

### Test Coverage

* No new tests are required for this change.
* Fix any failing tests.

## QA Brief

* Verify that the Ad Blocking Recovery Widget, AdSense Connect, and Key Metrics Setup CTAs can be dismissed by clicking "Maybe later".
* Verify that the CTA is dismissed when "Maybe later" is clicked rather than when the tooltip is dismissed.
* Verify that when the page is refreshed, the CTA is not displayed after being dismissed.
* Verify that the tooltip is still displayed as usual.

## Changelog entry

* Ensure AdSense CTA appears again if tooltip is ignored after dismissing the CTA widget.

**Comment by aaemnnosttv** [comment]
@kuasha420 @marrrmarrr this is the same behavior we have right now for the AdSense setup CTA as well which was probably inherited here. I think this can still be done, but doesn't seem launch-blocking considering this is how it is for the module today.

**Comment by aaemnnosttv** [comment]
Downgrading this until we've clarified the above – we should make the same change for both or leave as-is.

**Comment by bethanylang** [comment]
@aaemnnosttv Per @marrrmarrr's [comment in Asana here](https://app.asana.com/0/0/1204955754125349/1205056789015076/f), we can keep this is a P1 but should it get it taken care of sooner than later. Should we update this issue to make this change for both ABR _and_ AdSense setup, or open a separate issue for AdSense only? Thanks!

**Comment by techanvil** [comment]
As discussed with @bethanylang on Slack, we're going to update this to take care of both the ABR and AdSense setup CTAs, as the same small fix should be applied to both of these so we may as well take care of them together.

**Comment by aaemnnosttv** [comment]
> * Pass the `dismissCallback` function that dispatches the `dismissItem` action to the `onClick` prop of `Link`.

@hussain-t for `KeyMetricsSetupCTAWidget`, there is a bit of ambiguity with this case since there is both a secondary CTA "I’ll pick metrics myself" and the "Maybe later" (dismiss) which calls `showTooltip` currently. I think we only mean to integrate this with the latter while also preserving the call to `showTooltip`, correct?

**Comment by hussain-t** [comment]
Thanks, @aaemnnosttv. That's a good call. I have updated the IB to dismiss the CTA and invoke the `showTooltip` upon clicking "Maybe later".

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@hussain-t I would just like to clarify these points in the QAB:

> Verify that when the page is refreshed, the CTA is not displayed after being dismissed, while the tooltip is still shown as mentioned in the reproduction steps. Verify that the tooltip is still displayed as usual.

As you can see from the screencast, the tooltip does not reappear on refresh, but according to the QAB, it appears like it should have.  I haven't dismissed the tooltip, so it does make sense that it reappears.  Interested in your thoughts. 

https://github.com/google/site-kit-wp/assets/73545194/7483b8f9-97a3-4c37-bee5-ef3c273d18b4

**Comment by hussain-t** [comment]
@wpdarren, apologies for the confusion in the QAB. When you refresh the page, the tooltip won't reappear. The CTA should have already been dismissed.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Ad Blocking Recovery Widget, AdSense Connect, and Key Metrics Setup CTAs can be dismissed by clicking "Maybe later" and the CTA is dismissed when "Maybe later" is clicked rather than when the tooltip is dismissed.
- When the page is refreshed, the CTA is not displayed after being dismissed.
- Tested all of the "Maybe later" links as per the QAB. 

https://github.com/google/site-kit-wp/assets/73545194/82934b05-f192-459a-8b4f-bd01dc7dae47
