### ISSUE TITLE
Add a "learn more" link after the "Place error protection tag"  option in setup flow and settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7295]
## Feature Description

As reported by @jamesozzie in Bug Bash:

Add a "learn more" external hyperlink to https://sitekit.withgoogle.com/documentation/using-site-kit/ad-blocking-recovery [NOTE: link will not be active until day of feature release] next to the "Place error protection tag" toggle in the ABR setup flow and ABR Settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following ad blocking recovery references to the error protection tag's description should be updated to append a "Learn more" link (more details below)
	* The setup step 1, following the description below the "Place the error protection tag (optional)"
	* The description for the "Place error protection tag" in the settings edit view
* The learn more link should be an external link, automatically opening a new window or tab
	* document slug: `ad-blocking-recovery`  
	(see `getDocumentationLinkURL`)

## Implementation Brief

In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp/steps/PlaceTagsStep.js`:

* Get the URL for the "Learn more" link from the `getDocumentationLinkURL` selector by passing in the document slug `ad-blocking-recovery` to it.
* Update the description text of the "Place the error protection tag (optional)" checkbox using `createInterpolateElement`.
* Use the `Link` component to create the "Learn more" link as an external link that opens in a new tab or window.

In `assets/js/modules/adsense/components/common/AdBlockingRecoveryToggle.js`:

* Get the URL for the "Learn more" link from the `getDocumentationLinkURL` selector by passing in the document slug `ad-blocking-recovery` to it.
* Update the description text of the "Place error protection tag" toggle using `createInterpolateElement`.
* Use the `Link` component to create the "Learn more" link as an external link that opens in a new tab or window.

### Test Coverage

* No new tests are required for this change.

## QA Brief

* Verify that the "Learn more" link is present in the following locations:
    * The Ad Blocking Recovery setup step 1, following the description below the "Place the error protection tag (optional)" checkbox.
    * The description for the "Place error protection tag" toggle in the settings edit view.
* Note that the link will not be active until the day of the feature release.

## Changelog entry

* Add a "Learn more" link after the "Place error protection tag" option in the AdSense setup flow and settings.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Ad blocking recovery references to the error protection tag's description are updated to append a `Learn more` link:
  - The setup step 1, following the description below the `Place the error protection tag (optional)`
  - The description for the `Place error protection tag` in the settings edit view

- The learn more link is an external link, automatically opening a new window or tab
  `[Learn more](https://sitekit.withgoogle.com/support?doc=ad-blocking-recovery)`

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/a4e8f5c2-57f5-42f0-8b0b-2b542edf4025)
![image](https://github.com/google/site-kit-wp/assets/73545194/d63e9875-2613-410f-86d0-6778ef9a199c)

</details>
