### ISSUE TITLE
Change ABR setup flow and Settings language

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7296]
## Feature Description

Make the following changes to language in the ABR feature:

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

#### Settings CTA

1. Change description text of the Ad blocking recovery CTA
```diff
- Start recovering revenue lost from ad blockers by deploying the ad blocking tag through Site Kit.
+ Start recovering revenue lost from ad blockers by deploying an ad blocking recovery message through Site Kit.
```

#### Setup Flow

```diff
- Place the standard ad blocking recovery tag (required)
+ Enable ad blocking recovery message (required)
```

```diff
- Place the error protection tag (optional)
+ Enable error protection code (optional)
```
Change language under this setting
```diff
- If a site visitor’s ad blocker browser extension also blocks the standard ad blocking recovery tag, the error protection tag will show a non-customizable ad blocking recovery message to visitors when enabled.
+ If a site visitor’s ad blocker browser extension blocks the message you create in AdSense, a default, non-customizable ad blocking recovery message will display instead.
```

#### Settings Edit (post-ABR-setup)

```diff
- Place ad blocking recovery tag
+ Enable ad blocking recovery message
```
When toggled off, change the description of this toggle to the following and remove the related info notice ("The ad blocking recovery message won’t be displayed to visitors unless the tag is placed")
> The ad blocking recovery message will not be displayed to your site's visitors.

```diff
- Ad blocking recovery only works if you’ve also created and published a recovery message in AdSense
+ Identify site visitors that have an ad blocker browser extension installed. These site visitors will see the ad blocking recovery message created in AdSense.
```
(keep the Configure your message external link) – note that this will align this language with what is in the setup flow

```diff
- Place error protection tag
+ Place error protection code
```

The settings view will be updated in https://github.com/google/site-kit-wp/issues/7287

## Implementation Brief

- For existing copy `Start recovering revenue lost from ad blockers by deploying the ad blocking tag through Site Kit.`:
  - In `assets/js/modules/adsense/components/common/AdBlockingRecoveryCTA.js`:
    - Replace the `<SettingsNotice>` child text according to the ACs.
- For existing copy `Place the standard ad blocking recovery tag (required)`:
  - In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp/SetupMain.js`:
    - Update the `title` of the first `<Step>` according to the ACs.
- For existing copy `Place the error protection tag (optional)`:
  - In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp/steps/PlaceTagsStep.js`:
    - Update the `<Checkbox>` child copy according to the ACs.
- For existing copy `If a site visitor’s ad blocker browser extension also blocks the standard ad blocking recovery tag, the error protection tag will show a non-customizable ad blocking recovery message to visitors when enabled.`:
  - In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp/steps/PlaceTagsStep.js`:
    - Update the paragraph text underneath the `<Checkbox>` according to the ACs.
  - In `assets/js/modules/adsense/components/common/AdBlockingRecoveryToggle.js`:
    - Update the paragraph text underneath the `Place error protection tag` `<Switch>` according to the ACs.
- For existing copy `Place ad blocking recovery tag`:
  - In `assets/js/modules/adsense/components/common/AdBlockingRecoveryToggle.js`:
    - Update the `Switch` `label` with the above copy according to the ACs.
- For existing copy `Ad blocking recovery only works if you’ve also created and published a recovery message in AdSense`:
  - In `assets/js/modules/adsense/components/common/AdBlockingRecoveryToggle.js`:
    - If `adBlockingRecoveryErrorToggle` is falsy, i.e. the `Enable add blocking recovery message` toggle is turned off:
      - Update the paragraph text underneath the `Enable add blocking recovery message` `<Switch>` according to the ACs, i.e. `The ad blocking recovery message will not be displayed to your site's visitors.`
    - If `adBlockingRecoveryErrorToggle` is truthy, i.e. the `Enable add blocking recovery message` toggle is turned on:
      - Update the paragraph text underneath the `Enable add blocking recovery message` `<Switch>` according to the ACs, i.e. `Identify site visitors that have an ad blocker browser extension installed. These site visitors will see the ad blocking recovery message created in AdSense.`. Leave the `Configure your message` suffix link as it is.
    - Remove the `The ad blocking recovery message won’t be displayed to visitors unless the tag is placed` `<SettingsNotice>` entirely.
- For existing copy `Place error protection tag`:
  - In `assets/js/modules/adsense/components/common/AdBlockingRecoveryToggle.js`:
    - Update the `Switch` `label` with the above copy according to the ACs.

### Test Coverage

- In `assets/js/modules/adsense/components/common/AdBlockingRecoveryCTA.test.js`:
  - Reflect the copy change in the test case.
- In `assets/js/modules/adsense/components/common/AdBlockingRecoveryToggle.test.js`:
  - Replace instances of `Place ad blocking recovery tag` according to the ACs.
  - Replace instances of `Place error protection tag` according to the ACs.
- Fix any other failing tests due to the change in the copy.
- Update any VRT references failing due to the change in the copy.

## QA Brief

* Enable Ad Blocking Recovery feature flag.
* Set up AdSense on your site and view the settings to view the Ad Blocking Recovery CTA. The text should contain the updated copy in the ACs.
* Set up Ad Blocking Recovery—the copy in the setup should match the ACs.
* View Ad Blocking Recovery settings in Site Kit settings—the copy in the setup should match the copy in the ACs.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Hey @nfmohit, this IB is looking good. I think it could just use a little more detail to ensure the nuance of this AC point is touched upon, as with the AC having the same structure for all of the points, most of which are straight copy changes, the additional aspects of this one could get overlooked:

> - When toggled off, change the description of this toggle to the following and remove the related info notice ("The ad blocking recovery message won’t be displayed to visitors unless the tag is placed")

**Comment by nfmohit** [comment]
Excellent catch, updated the IB, thank you @techanvil!

**Comment by techanvil** [comment]
Thanks @nfmohit, that's great.

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:

- Set up AdSense and Ad Blocking Recovery CTA. The text contains the updated copy in the ACs.
- View Ad Blocking Recovery settings in Site Kit settings—the copy in the setup matches the copy in the ACs.


<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/51db9ed1-9127-4606-a5df-f613fc20277d)
![image](https://github.com/google/site-kit-wp/assets/73545194/3cfac1d4-a7d3-447a-bc90-1f56a7c59026)
![image](https://github.com/google/site-kit-wp/assets/73545194/8b3b5321-d19e-49a0-a9d2-fcb150e1f97b)
![image](https://github.com/google/site-kit-wp/assets/73545194/a75ab283-3da9-45ee-b43a-4f5689fd0efb)
![image](https://github.com/google/site-kit-wp/assets/73545194/e2f8f029-f29c-4d53-8151-f270f3c17c0a)
![image](https://github.com/google/site-kit-wp/assets/73545194/3e63c203-97c4-4c03-ae2a-d5db40ec6284)
![image](https://github.com/google/site-kit-wp/assets/73545194/23937164-3dd1-4c24-95c8-335c40068c5e)

</details>
