### ISSUE TITLE
Setup CTA widget bottom text should be left-aligned

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7297]
## Feature Description

As reported by @sigal-teller in Bug Bash:

If all the content is left aligned than the small gray text in the bottom should be left aligned as well:

![image](https://github.com/google/site-kit-wp/assets/12189958/338f618e-dbc7-46cc-880b-eeee687d3ecf)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The footnote about ad blocking recovery messages in the setup CTA should be left-aligned when wrapped below the CTA actions 

## Implementation Brief

Within `assets/sass/components/adsense/_googlesitekit-adsense-ad-blocking-recovery.scss`:

- Update the `.googlesitekit-widget--adBlockingRecovery__graphics` class to include a media query with max-width 600px (`$bp-tablet`). Within this media block, update the content to be left-aligned and remove the paragraph margin.

### Test Coverage

* Fix any failing VRT tests.

## QA Brief

* Enable viewing of the AdSense Ad Blocking Recovery banner. To do so, perform the following steps:
    * Set up Site Kit accordingly
    * Enable the Ad Sense module and configure it so that it shows data via the "Monetization" area of the dashboard
    * Via the tester plugin: Enable the `adBlockerDetection` feature flag.
    * Via the tester plugin: Set the reference date to be 3 weeks + 1 day in the future.
* Return to the Site Kit Dashboard and scroll to the "Monetization" section.
* Note the appearance of the Ad Blocking Recovery banner that is titled "Recover revenue lost to ad blockers".
* Re-size your viewport to a tablet viewport, maximum width `600px`.
* Validate that the small grey texted paragraph starting with `*Average for publishers showing...` is left aligned, is beneath the "Set Up Now" and "Maybe Later" CTA elements, and contains no margin.

Following is a visual reference of the desired state:

![Site Kit by Google Dashboard ‹ sitekit 10uplabs com — WordPress 2023-07-18 at 4 47 24 PM](https://github.com/google/site-kit-wp/assets/72872375/1cb706b0-75d0-4d53-ba14-44d6873ec3db)

## Changelog entry

* N/A

**Comment by bethanylang** [comment]
Noting that there's a some discussion on this one in a different, [Nice to Have Asana task](https://app.asana.com/0/1204478087069244/1204954653769556) that would result in different alignments. Let's hold on this one until we have a decision there; will update!

**Comment by bethanylang** [comment]
Confirming per @sigal-teller's comment in [Asana here](https://app.asana.com/0/1204478087069244/1204954653769556/f) that we should proceed on this issue and make the text left aligned.

**Comment by kuasha420** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that if viewport width is 600px or less than CTA widget bottom text appear left aligned.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/55413000-7111-4aee-8d0b-870d97eee1e9)

https://github.com/google/site-kit-wp/assets/94359491/027832e3-fc18-41f5-9f41-e83478675fcd

</details>
