### ISSUE TITLE
Ad Blocking Recovery setup flow illustration size needs adjustments

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7299]
## Feature Description

As reported by @sigal-teller in Bug Bash:

The illustration image should have limited scaling - in large resolutions is too large and creates a lot of white space. Also. in tablet view the image is too small to understand what it is

![image](https://github.com/google/site-kit-wp/assets/12189958/57d86ce0-4715-4181-aa13-58f0ed2ee3fb)

![image](https://github.com/google/site-kit-wp/assets/12189958/42529182-454c-400d-937d-f45c3c278b65)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The illustration on the [AdBlockingRecoveryApp](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-components-setup-adblockingrecoveryapp--step-one) component should not scale infinite, but have a max width. 400px seams to look good.
* On mobile, the illustration should be hidden. The (text) content should use 100% of the width of the containing element.

## Implementation Brief

* In [`assets/js/modules/adsense/components/setup/AdBlockingRecoveryApp/Content.js`](https://github.com/google/site-kit-wp/blob/bad5cfe97e08b19b9e52aa750d81a52c0f674d44/assets/js/modules/adsense/components/setup/AdBlockingRecoveryApp/Content.js):
 * Rename `isTabletWidthOrLarger` to `isDesktopWidthOrLarger`, and update the logic to be true if breakpoint is neither `BREAKPOINT_TABLET` nor `BREAKPOINT_SMALL`
  ```
   const isDesktopWidthOrLarger = ! [
		BREAKPOINT_TABLET,
		BREAKPOINT_SMALL,
	].includes( breakpoint );
  ```
 * Change the value for the `mdSize` of the first `<Cell>` to `8`, so it takes the full width.
 * Remove the `mdSize={ 2 }` of the second `<Cell>`, as this is not used anymore.

### Test Coverage

* Upate VRT Reference images.

## QA Brief

- Set up Site Kit with the AdSense module.
- Go to the Ad Blocking Recovery setup screen.
- Verify that the graphic in the setup panel acts according to the ACs.
- The SVG illustration should be hidden on mobile and tablet screens. Please refer to this [comment](https://github.com/google/site-kit-wp/issues/7299#issuecomment-1838419342).

## Changelog entry

* Remove the Ad Blocking Recovery setup graphic on mobile viewports.

**Comment by derweili** [comment]
For mobile, to be consistend with other component like the [Analytics4 success banner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-successbanner--default) I would recommend to hide it on mobile.

**Comment by tofumatt** [comment]
Agreed, let's hide it on mobile 👍🏻 

Moving to IB 👍🏻

**Comment by derweili** [comment]
The graphic was already hidden on mobile, we just have to change the brekpoint.

**Comment by techanvil** [comment]
IB :white_check_mark:

Note, I tweaked it slightly to specify renaming `isTabletWidthOrLarger` -> `isDesktopWidthOrLarger`.

**Comment by techanvil** [comment]
Hey @derweili, I can't remember if you were here for the discussion around estimates and are aware of our "bumping it up to the next value" approach to help us avoid underestimating on average.

To me, this looks like it's a "legitimate" estimate of a 3 which means we should bump to the next one up i.e. a 7. Please let me know if you're aware of this system or could use a bit more explanation around it if not.

**Comment by derweili** [comment]
@nfmohit I don't think that is needed. The Graphic is already hidden on mobile, we are only changing the breakpoint, to hide it not only on small screen sizes but on medium sizes as well.

**Comment by techanvil** [comment]
Both phone and tablet sized viewports should be considered "mobile", really - as our breakpoint definitions suggest:

https://github.com/google/site-kit-wp/blob/8fa1ff53e1213e7d222b4bcca34d7400a56e5d42/assets/sass/config/_variables.scss#L271-L274

**Comment by nfmohit** [comment]
Understood, thanks!

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit On a tablet, when in portrait, the illustration does not appear, but when I switch it to landscape, it does. I'm not sure if there's anything we can do about that. What do you think? 

![image](https://github.com/google/site-kit-wp/assets/73545194/c7105e84-8932-4378-ab19-e2da02b41089)

**Comment by nfmohit** [comment]
> @nfmohit On a tablet, when in portrait, the illustration does not appear, but when I switch it to landscape, it does. I'm not sure if there's anything we can do about that. What do you think?

Hi @wpdarren. There isn't much we can do here since the breakpoints are based on the screen width, so I'd say this is expected. Thanks for checking!
