### ISSUE TITLE
Components hovered state is not releasing after pressing

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7301]
## Feature Description

As reported by @sigal-teller in Bug Bash:

After checking the checkbox in the setup flow, the hovered state is not releasing, It also happens with the toggles in the settings (edit mode). It also happens with the toggles in the setting screens (edit mode).

![image](https://github.com/google/site-kit-wp/assets/12189958/85da3ca5-6ba8-464a-aee7-8c2fdb546f5b)

![image](https://github.com/google/site-kit-wp/assets/12189958/aa720dca-3f01-4324-8717-1cb39848bb5d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kuasha420** [comment]
I thought hover state not releasing was an intentional accessibility feature and it's a plugin wide behavior? Am I completely wrong on this? @tofumatt can you confirm or debunk my assumption here? Cheers
