### ISSUE TITLE
Settings edit mode - locked services are covered with the wrong gray color

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7302]
## Feature Description

In the edit mode, while other services are locked for editing they are covered with gray color. The current color is too bright and blends with the background. The right color is in Figma, like [here](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?type=design&node-id=160%3A3613&mode=design&t=ImaSYAzcyaNBYJoO-1)

<img width="569" alt="CleanShot 2023-08-10 at 23 15 23" src="https://github.com/google/site-kit-wp/assets/90871/9b4a10d8-810b-4815-991b-84a65a99ef99">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The colour appearing over the modules/services that are "locked" while another module is being edited should be updated to match the colour in the [Figma designs](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?type=design&node-id=160-3613&mode=design&t=LorWPpO8HUpx9Mzh-0)
* VRTs should be updated to match this new colour

## Implementation Brief

* In `assets/sass/components/settings/_googlesitekit-settings-module.scss`:
    * Add a `.googlesitekit-settings-module--active` class inside `.googlesitekit-plugin`.
        * Inside it, override the `background` of `.googlesitekit-overlay`.
            * `background` : `rgba($c-surfaces-surface-2, 0.75)`.

### Test Coverage

* VRT images may need to be updated. 

## QA Brief

* Go to Site Kit settings page.
* Under first tab `Connected Services` expand one of the services.
* Click edit link.
* Verify that other services that are locked, have proper gray color as in design.

## Changelog entry

* Change gray color used in settings screen when locking modules during editing.

**Comment by techanvil** [comment]
Hi @kuasha420, thanks for writing this IB. Took me a few minutes to figure out where the relevant opacity was in Figma :)

Anyhow, this certainly works, however as a general rule I think it's fair to say that we override the global component styles in the files that relate to the components where they need to be customised, rather than maintaining the various customisations in the global component's SCSS file.

That is to say, I think we should move the fix from `assets/sass/components/global/_googlesitekit-overlay.scss` to `assets/sass/components/settings/_googlesitekit-settings-module.scss`.

**Comment by kuasha420** [comment]
Thank you for the suggestion @techanvil, I've updated the IB accordingly. :+1:

**Comment by techanvil** [comment]
Thanks @kuasha420!

IB LGTM :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@zutigrm I am not an expert on Hex and RGB so this might be expected, but I would like to check.  😄  The colour appearing over the modules/services that are "locked" while another module is`#cbd0d3bf` I am assuming that the `bf` is for the 0.75 opacity?  When I look at the RGB it is `rgb(203 208 211 / 75%` so it looks to be correct. Would you agree? 

![image](https://github.com/google/site-kit-wp/assets/73545194/4a669e75-d415-4fe4-b724-ce4c91b9c6ba)

**Comment by zutigrm** [comment]
@wpdarren Yes, that's correct.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The colour appearing over the modules/services that are "locked" while another module is being edited is updated to match the colour in the [Figma designs](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?type=design&node-id=160-3613&mode=design&t=LorWPpO8HUpx9Mzh-0)

![image](https://github.com/google/site-kit-wp/assets/73545194/4a669e75-d415-4fe4-b724-ce4c91b9c6ba)
