### ISSUE TITLE
Setup flow step 1 text styles mismatches

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7303]
## Feature Description

- “Place the standard…” title should be bolder than the “Identify site visitors…” text, check that text styles are aligned with Figma
- Cancel CTA is in the wrong color, and also the strip that includes the cancel CTA is too high
- In mobile view - align the numbered circle to the top of the text and not center

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `font-weight` of the active and completed step title of the Stepper component should be `500`, as seen in [Figma](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?node-id=130%3A3229&mode=dev) design. 
* The `Cancel` button in Ad Blocking Recovery App should match the design. Namely:
    * The color should be `surfaces-on-background-variant`/`$c-surfaces-on-background-variant`.
    * The gap between the button and the top decider should be reduced to match the design (14px).
* In Mobile view, the circle containing the step number should be placed on top of the step title, and the line that connects the step circles should not be visible to ensure the circle, title and contents are left aligned and making maximum use of limited horizontal space on mobile view ports. This is similar to how [SettingsNotice](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-widgets-dashboardtopearningpageswidgetga4--ready) work on mobile views.

## Implementation Brief

- In `assets/sass/components/global/_googlesitekit-stepper.scss`:
  - Update styles for `.googlesitekit-stepper__step-title` to add a `font-weight` of `$fw-medium`;
  - Update styles for `.googlesitekit-stepper__step` to have `display` `block` by default, changing to `flex` on viewports above mobile.
  - Update styles for `.googlesitekit-stepper__step-progress-line` to not be visible by default (`display: none`), but visible on viewports above mobile.
  - Update styles for `.googlesitekit-plugin .googlesitekit-stepper__step-title` to have `margin: 0` only on viewports above mobile.
- In `assets/sass/components/adsense/_googlesitekit-adsense-ad-blocking-recovery.scss`:
  - Add styles for `.googlesitekit-ad-blocking-recovery__footer-cancel button` to add a `color` of `$c-surfaces-on-background-variant`.
  - Remove any added `padding` from `.googlesitekit-ad-blocking-recovery__footer-cancel` (for any viewport).
  - Update the `padding` for `.googlesitekit-ad-blocking-recovery__footer` to be `14px $grid-gap-desktop`,

### Test Coverage

- Update VRT references if required.

## QA Brief

* On a site with AdSense and Ad Blocking Recovery feature flag enabled, set up Ad Blocking recovery and view the setup component/"stepper" (screenshot below) on mobile, tablet, and desktop viewports.

<img width="1170" alt="CleanShot 2023-08-17 at 23 38 22" src="https://github.com/google/site-kit-wp/assets/90871/74265341-4f19-4448-8589-27d1b13b654a">

* The desktop UI should match the Figma mocks.
* The mobile/tablet viewports should have no visual errors.
* On mobile viewports, the stepper number should appear ABOVE the title of the step, eg:

<img width="527" alt="CleanShot 2023-08-17 at 23 38 54" src="https://github.com/google/site-kit-wp/assets/90871/a0eb056c-c801-49c2-98ea-ba55d8456813">

* On tablet and larger viewports the number should be next to the title, not above it.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs sound good, moving to IB 👍🏻

**Comment by kuasha420** [comment]
Thank you @nfmohit ! One point of confusion here, shouldn't the `googlesitekit-stepper__step-progress-line` be `display: none;` on mobile instead of `googlesitekit-stepper__step-number` to meet the AC? The number should be visible (on top of the title on mobile, current behavior otherwise), but the line should not be visible in Mobile. 

Cheers.

**Comment by nfmohit** [comment]
> Thank you @nfmohit ! One point of confusion here, shouldn't the `googlesitekit-stepper__step-progress-line` be `display: none;` on mobile instead of `googlesitekit-stepper__step-number` to meet the AC? The number should be visible (on top of the title on mobile, current behavior otherwise), but the line should not be visible in Mobile.

That is absolutely correct, my mistake. Excellent catch! I've updated it. Thank you!

**Comment by kuasha420** [comment]
No worries. LGTM :+1: 

IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

On a site with AdSense and Ad Blocking Recovery feature flag enabled, set up Ad Blocking recovery and view the setup component/"stepper" (screenshot below) on mobile, tablet, and desktop viewports:

- The desktop UI matches the Figma mocks.
- The mobile/tablet viewports have no visual errors.
- On mobile viewports, the stepper number appears above the title of the step
- On tablet and larger viewports the number are next to the title, not above it

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/5165aea6-c4d2-469d-9bc1-962023be92f6)
![image](https://github.com/google/site-kit-wp/assets/73545194/139a8e19-44f8-4d6f-b5b9-bc71ec7db48b)
![image](https://github.com/google/site-kit-wp/assets/73545194/49f66ec2-b6c6-470b-9e55-c4f32627567f)
![image](https://github.com/google/site-kit-wp/assets/73545194/94b7174f-c6ce-4ccd-99a3-5dd3c6efa492)

</details>
