### ISSUE TITLE
WP dashboard widget invokes requests for UA reports in GA4 mode

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7306]
## Bug Description

The WP dashboard widget ("Site Kit Summary"), like the SK dashboard conditionally shows GA4 versions of its Analytics widgets based on the configured dashboard view.

1.104.0 included changes to the way one a relevant selector worked which causes this issue.

If UA is connected, this results in some extra requests being made which aren't really being used. If UA is not connected, these result in extra requests that all fail and because of this are made on every navigation to the WP dashboard, which is not great.

## Steps to reproduce

1. Connect GA4, with no UA
2. Visit WP dashboard
3. See errors in console

## Screenshots

<img width="955" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/26a8b9b3-2050-45ed-940d-416c96231deb">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The WP dashboard widget should only request Analytics data based on the configured dashboard view
	* If the dashboard view is UA, no requests should be made for GA4 reports
	* If the dashboard view is GA4, no requests should be made for UA reports

## Implementation Brief

* Update conditions for rendering UA components based on the dashboard view to use a strict comparison, rather than a loose one which can return a momentary false positive while loading
* Merge #7307 

### Test Coverage

* No changes necessary

## QA Brief

* The changes described above are isolated to the WP dashboard widget
* The PR above also corrects the same kind of change with the date marker for indicating when UA stopped collecting data, although this is almost not worth mentioning

## Changelog entry

* Fix bug that additionally requested UA Analytics reports on the WP dashboard when dashboard view was set to GA4.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
@wpdarren I'm not able to reproduce issue on latest environment. Not getting console errors on WP dashboard.

- Tested using new site having only Ga4 property. 
- Also, tested using Oi.ie site by connecting only GA4 property.
- Tested after enabling and disabling UA property.
- Tested on 7.4 and 8.1 PHP versions.


https://github.com/google/site-kit-wp/assets/94359491/b0834e53-70cd-4ae1-8bf3-8d7c94537035


https://github.com/google/site-kit-wp/assets/94359491/6e1853de-1ede-4c66-aa91-3849033d5773

**Comment by wpdarren** [comment]
@mohitwp I do see the errors but I have to say that they do not appear all the time for me.  I had to refresh a few times for them to appear.  I also had to wait for 30-60 seconds for them to appear and for the Site Kit widget to fully load.  I used oi.ie and made sure that the UA property was not enabled.  Just GA4. 

![image](https://github.com/google/site-kit-wp/assets/73545194/d9473e2c-fe27-4af7-bdae-4183fa8095fb)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

The errors no longer appear in the console when you only have a GA4 property connected.  As you see from the screencast below, the error messages initially appeared on 1.104.0 and when I switched to the main branch they no longer appear. 

https://github.com/google/site-kit-wp/assets/73545194/5ea72675-6ab1-41b7-9c62-7c06174e1e5a

**Comment by aaemnnosttv** [comment]
> @wpdarren I'm not able to reproduce issue on latest environment. Not getting console errors on WP dashboard.

@mohitwp thanks for sharing this. I found that the error only happens when the dashboard widget is in view on page load. In your screencast it's below the fold and in Darren's it's above it. The reports are only requested when the widget is in view, so when it's delayed like this the data that's not available yet (and the cause for the UA version to be invoked) becomes available before the widget is rendered.

If you move the widget to the top of the dashboard so that its in view and reload, you'll should see the errors.

Thanks for the collaboration on this one all!
