### ISSUE TITLE
Combined error state when ALL Key Metric Widget Tiles throw an error

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7311]
## Feature Description

Key Metric widget tiles are much smaller than our usual widgets and hence require new error components to be designed as per the [Figma mocks](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=5409-80974&mode=design&t=D1fpE0r18blVhVn1-0).

This issue was split out from https://github.com/google/site-kit-wp/issues/7149 since point 2 in that issue's AC was making things quite complicated. 

This issue (#7311) focuses on the rather complicated and possibly rare error "combined" error state when all widget tiles throw an error:
<img width="1015" alt="Screenshot 2023-06-09 at 13 06 57" src="https://github.com/google/site-kit-wp/assets/1721319/18f6c762-a4a5-45cd-b5ea-ed35c467e5db">

#7310 focuses on the simpler error state for individual Key Metric widget tiles:
<img width="1200" alt="Screenshot 2023-07-11 at 17 59 49" src="https://github.com/google/site-kit-wp/assets/1721319/1e0f02f5-b4c8-4527-bc5d-3248987bed24">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If all the Key Metric Widget tiles are throwing an error, then a single larger component should be rendered as per this [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=3328-73177&t=j95x7XWNlCMtf68F-0) instead of multiple smaller tile errors.
    * Clicking on the "Retry" button should behave like our existing `ReportErrorActions` component invalidating the resolution of the selectors that threw an error thereby attempting to resolve those selectors again.
    * Clicking on the "Get Help" link should also behave like our existing `ReportErrorActions` component and use the `getErrorTroubleshootingLinkURL` selector.
* Any Key Metric widget tiles implemented already should have this functionality added to them. Tiles implemented after this feature is executed will reuse the components created as part of this issue.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Please note, as this issue needs a bit of further consideration, when discussing this from a UX perspective we should consider the points that @10upsimon raised in his [comment](https://github.com/google/site-kit-wp/issues/7149#issuecomment-1631559953) on the original issue:

> - I have some concerns around the UX/UI implications of the "all widgets erroring" scenario, it would be quite visually jarring to go form 1, 2 or maybe even 3 rows of key metrics widget components to all of a sudden having a single error component that occupies considerably less UI space, do you think this needs to be raised with UX?
> - Given that loading states can be resolved at differing times, this too could be a UX consideration, having multiple widgets enter into individual error states, only to then be replaced with the single one as above.

cc @sigal-teller
