### ISSUE TITLE
After latest update cannot activate analytics

### ISSUE THREAD

**Issue by coolhandluke1234** [google/site-kit-wp#732]
## Bug Description

I get the following after I updated:  We've detected there's already an existing Analytics tag on your site (ID AW-748864641), but your account doesn't seem to have access to this Analytics property. You can either remove the existing tag and connect to a different account, or request access to this property from your team.
<img width="1624" alt="Screen Shot 2019-10-28 at 8 24 56 PM" src="https://user-images.githubusercontent.com/50368339/67727780-16522f80-f9c1-11e9-8f00-6afd0877e527.png">

## Steps to reproduce

Update to the latest

## Additional Context

 - PHP Version: 7.3.7
 - OS: Mac OS 10.15
 - Browser Safari
 - Plugin Version Version 1.0.0-rc.2

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
Hi @coolhandluke1234! Could you confirm a few things for me:

1) Are you logged into a Google account that has administrative access to the property in Google Analytics and other connected services? It looks like the tracking ID referenced is for Google Ads [conversion tracking](https://support.google.com/google-ads/answer/7548399). 

2) How are you adding the snippet to the site?

**Comment by coolhandluke1234** [comment]
1. Yes, and everything was working before the update

2. I put the snippet in my theme so it is in the <head> section on all pages throughout the website
[cid:clip_image001.png]
Lucas Marshall
CEO & Co-Founder | Podcast Producer
(757) 410-4678 | lucas@themoneyadvantage.com<mailto:lucas@themoneyadvantage.com> | LinkedIn<https://www.linkedin.com/in/lucasmarshall/> | themoneyadvantage.com<https://themoneyadvantage.com/>
[cid:clip_image002.png]
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information or otherwise protected by law. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Oct 28, 2019, at 9:38 PM, Renee Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @coolhandluke1234<https://github.com/coolhandluke1234>! Could you confirm a few things for me:

  1.  Are you logged into a Google account that has administrative access to the property in Google Analytics and other connected services? It looks like the tracking ID referenced is for Google Ads conversion tracking<https://support.google.com/google-ads/answer/7548399>.

  2.  How are you adding the snippet to the site?

**Comment by ernee** [comment]
Thanks for the info @coolhandluke1234 ! 

Could you try the following and let me know if either resolves the issue:

1) Disconnecting and reconnecting the Google Analytics Module

2) I notice that the snippet on the site is missing the gtag command for the Google Analytics tracking ID:

<script async src="https://www.googletagmanager.com/gtag/js?id=AW-748864641"></script> <script>window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-748864641');</script>

It would be included like this for example:  gtag('config', 'GA_TRACKING_ID');
 
a. Could you add it before the Google Ads conversion tracking ID gtag
b. then disconnect and reconnect the Google Analytics module in Site Kit

Example snippets can be found in the [Google Ads documentation](https://support.google.com/google-ads/answer/7548399?hl=en&ref_topic=3165803#).

**Comment by coolhandluke1234** [comment]
I only wanted to add the AdWords tracking in the theme.

I thought this plugin would add the analytics tag?

Also,  what do you mean by:

  1.  Disconnecting and reconnecting the Google Analytics Module

Sent from my iPhone

On Oct 29, 2019, at 2:45 PM, Renee Johnson <notifications@github.com> wrote:

﻿

Thanks for the info @coolhandluke1234<https://github.com/coolhandluke1234> !

Could you try the following and let me know if either resolves the issue:

  1.  Disconnecting and reconnecting the Google Analytics Module

  2.  I notice that the snippet on the site is missing the gtag command for the Google Analytics tracking ID:

<script async src="https://www.googletagmanager.com/gtag/js?id=AW-748864641"></script> <script>window.dataLayer = window.dataLayer || [];

function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'AW-748864641');</script>

It would be included like this for example: gtag('config', 'GA_TRACKING_ID');

a. Could you add it before the Google Ads conversion tracking ID gtag
b. then disconnect and reconnect the Google Analytics module in Site Kit

Example snippets can be found in the Google Ads documentation<https://support.google.com/google-ads/answer/7548399?hl=en&ref_topic=3165803#>.

**Comment by ernee** [comment]
Thanks for info @coolhandluke1234.  Site Kit normally would add its own Google Analytics snippet, but it's detecting your manually inserted snippet from Google Ads and that's preventing it from doing so. I believe you mentioned it worked before the update? Before I escalate this issue, let's check a few things: 

1) Disconnect Google Analytics: Navigate to _Site Kit > Settings > Google Analytics > Edit > Disconnect Analytics from Site Kit_

![Disconnect Analytics from Site Kit](https://user-images.githubusercontent.com/8108643/67890798-9b972a80-fb0e-11e9-9a1f-0ab18c95c5c2.png)

2) Reconnect Google Analytics: Go to _Connect More Services_ and _Set up Analytics_

![Set up Google Analytics](https://user-images.githubusercontent.com/8108643/67892220-7ce66300-fb11-11e9-84e7-a86adac8aba6.png)

Could you try this _with_ and _without_ your manually added snippet and let me know if you are able to proceed with setting up Google Analytics in Site Kit?

**Comment by coolhandluke1234** [comment]
I temporarily removed the adwords snippet and then the analytics portion setup worked.

Then I added the snippet back in the theme.

Not sure about what your suggestion.
[cid:clip_image001.png]
Lucas Marshall
CEO & Co-Founder | Podcast Producer
(757) 410-4678 | lucas@themoneyadvantage.com<mailto:lucas@themoneyadvantage.com> | LinkedIn<https://www.linkedin.com/in/lucasmarshall/> | themoneyadvantage.com<https://themoneyadvantage.com/>
[cid:clip_image002.png]
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information or otherwise protected by law. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Oct 30, 2019, at 3:43 PM, Renee Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for info @coolhandluke1234<https://github.com/coolhandluke1234>. Site Kit normally would add its own Google Analytics snippet, but it's detecting your manually inserted snippet from Google Ads and that's preventing it from doing so. I believe you mentioned it worked before the update? Before I escalate this issue, let's check a few things:

  1.  Disconnect Google Analytics: Navigate to Site Kit > Settings > Google Analytics > Edit > Disconnect Analytics from Site Kit

[Disconnect Analytics from Site Kit]<https://user-images.githubusercontent.com/8108643/67890798-9b972a80-fb0e-11e9-9a1f-0ab18c95c5c2.png>

  1.  Reconnect Google Analytics: Go to Connect More Services and Set up Analytics

[Set up Google Analytics]<https://user-images.githubusercontent.com/8108643/67892220-7ce66300-fb11-11e9-84e7-a86adac8aba6.png>

Could you try this with and without your manually added snippet and let me know if you are able to proceed with setting up Google Analytics in Site Kit?

**Comment by coolhandluke1234** [comment]
Now analytics is not working again
[cid:clip_image001.png]
Lucas Marshall
CEO & Co-Founder | Podcast Producer
(757) 410-4678 | lucas@themoneyadvantage.com<mailto:lucas@themoneyadvantage.com> | LinkedIn<https://www.linkedin.com/in/lucasmarshall/> | themoneyadvantage.com<https://themoneyadvantage.com/>
[cid:clip_image002.png]
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information or otherwise protected by law. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Oct 30, 2019, at 3:43 PM, Renee Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for info @coolhandluke1234<https://github.com/coolhandluke1234>. Site Kit normally would add its own Google Analytics snippet, but it's detecting your manually inserted snippet from Google Ads and that's preventing it from doing so. I believe you mentioned it worked before the update? Before I escalate this issue, let's check a few things:

  1.  Disconnect Google Analytics: Navigate to Site Kit > Settings > Google Analytics > Edit > Disconnect Analytics from Site Kit

[Disconnect Analytics from Site Kit]<https://user-images.githubusercontent.com/8108643/67890798-9b972a80-fb0e-11e9-9a1f-0ab18c95c5c2.png>

  1.  Reconnect Google Analytics: Go to Connect More Services and Set up Analytics

[Set up Google Analytics]<https://user-images.githubusercontent.com/8108643/67892220-7ce66300-fb11-11e9-84e7-a86adac8aba6.png>

Could you try this with and without your manually added snippet and let me know if you are able to proceed with setting up Google Analytics in Site Kit?

**Comment by ernee** [comment]
Thanks for the update @coolhandluke1234 ! Are you getting the same notice had before?

**Comment by ernee** [comment]
@coolhandluke1234 we're working on a fix for this in #793. Please follow the issue for updates. Thanks for reporting!
