### ISSUE TITLE
Existing GA4 tags placed via GTM not recognized, with no notice that an existing property was found

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7335]
## Bug Description

When testing for the plugin behavior with existing tags placed via GTM, Site Kit is not recognizing GA4 tags as it does with UA tags (and possibly previously with GA4 tags). 

![image](https://github.com/google/site-kit-wp/assets/41326532/8197e739-ee94-4313-9dae-06c07cbdf667)

## Steps to reproduce

1. Connect Site Kit on a new site (without Analytics)
2. Create a new web container at tagmanager.google.com. The container should have a [GA4 tag added](https://i.imgur.com/96H38ML.png), with a valid GA4 measurement ID tracking all page views. This will need to be published, with page views firing.  
3. Connect the Tag Manager module within Site Kit, choosing this newly created container. There is no notice that an existing Analytics tag was found. 
4. Connect the Analytics module within Site Kit. There is also no notice that an existing Analytics tag was found. If you select the same measurement ID selected when configuring the GA4 tag in GTM, double tracking may apply. 

## Screenshots

Without a notice and detection, Site Kit will also insert a GA4 snippet. This can lead to double tracking, as per the image below:

![image](https://github.com/google/site-kit-wp/assets/41326532/ecce947d-8bf9-43b6-b065-4889926b6234)

![image](https://github.com/google/site-kit-wp/assets/41326532/3b7d356e-e08a-4e44-b8ff-93f7cafde36f)

## Additional Context

 - Site Kit 1.105.0
 - Tested and reproducible on a couple of sites
 - If we changed how detection is performed has changed, or something changed at GTM level, we may also consider checking for an existing GA4 snippet placed via GTM but not the GTM module within Site Kit (https://github.com/google/site-kit-wp/issues/4103)
 - Recording of experience: https://www.loom.com/share/0a8fb4a75d8a4cebacf5b76a68485e54 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @jamesozzie – I'm aware of this lack of parity with UA (I believe we have at least one other issue about it). The main question is does this result in duplicate measurement? This will ultimately determine how important this is. It could be that it's "firing" from both, but only counted once.

**Comment by jamesozzie** [comment]
@aaemnnosttv I tested this today and this is a fair point. From testing, it seems that despite two Analytics hits (one via GA, the other GTM), only one site visit is registered in Analytics ([example recording](https://www.loom.com/share/260bbb023dcf4c17ac351bff59631eb4)). I didn't check any event tracking, only site visits. Let me know if you want me to do more testing on this. 

> I believe we have at least one other issue about it

The only other issue I could find related to not recognizing GTM placed Analytics tags is #4103

**Comment by jimmymadon** [comment]
Closing this issue based on the mini GA4 GTM Integration epic and [this comment](https://github.com/google/site-kit-wp/issues/7989#issuecomment-1915654586) which highlights the decision to remove the duplicate tag detection/rendering functionality and simplifying the existing Google Tag detection when setting up GTM.

c.c. @jamesozzie @aaemnnosttv
