### ISSUE TITLE
Expose WP dashboard widget and Admin Bar for view-only users

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7344]
## Feature Description

Dashboard sharing introduced the ability to make the Site Kit dashboard available to non-admins on the site as well as admins who don't have a Google account or who may not have access to the various connected entities on the Google services.

The initial feature set explicitly limited the elements available to view-only users to the main and entity dashboards only. The other areas of the site that Site Kit enhances with reporting data such as the WP dashboard (Site Kit Summary widget) and the admin bar integration would also be valuable for view-only users. These areas are handled differently than the main SK dashboards which requires more care and potentially additional UX considerations in making them available in this context which they have not before. For this reason it makes sense to add this separately. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- If a view-only user has a shared role for at least one of the Search Console and Analytics modules:
  - The user should see the Site Kit Summary widget on the WP Dashboard.
  - The user should see the Site Kit Admin Bar when viewing a publicly facing WordPress page.

#### Site Kit Summary widget in view-only mode

- If the user has shared roles for both modules, the Site Kit Summary widget should be displayed as normal.
- If the user has a shared role for Search Console but not Analytics:
  - The Analytics widgets in the composite Site Kit Summary widget ("Total Unique Visitors", "Avg. Time on Page", "Unique visitors over the last 28 days", and "Top content over the last 28 days") should _not_ be displayed.
  - The Search Console widgets in the composite Site Kit Summary widget ("Total Impressions" and "Total Clicks") should be displayed.
- If the user has a shared role for Analytics but not Search Console, the above scenario should be reversed, with only the Analytics widgets being displayed.

#### Site Kit Admin Bar in view-only mode

- If the user has shared roles for both modules, the Admin Bar should be displayed as normal.
- If the user has a shared role for Search Console but not Analytics:
  - The Analytics widgets in the Admin Bar ("Total Users" and "Total Sessions") should _not_ be displayed.
  - The Search Console widgets in the Admin Bar ("Total Impressions" and "Total Clicks") should be displayed at twice their usual width to take up the space that would otherwise be occupied by the Analytics widgets.
- If the user has a shared role for Analytics but not Search Console, the above scenario should be reversed, with only the Analytics widgets being displayed and at twice their usual width.

#### Insufficient permissions

- If _any_ of the widgets listed above receive an insufficient permissions error, the [view-only error variant](https://github.com/google/site-kit-wp/blob/3452e9e902665eb370eea433aaeb25a9b43d6c3e/assets/js/components/ReportError.js#L60-L75) should be displayed. In other words:

_This notice variant should be displayed:_  
![image](https://github.com/google/site-kit-wp/assets/18395600/49a03d82-c91e-49f1-a813-45d02dd5c18f)

_Instead of this one:_  
![image](https://github.com/google/site-kit-wp/assets/18395600/e57a2318-70e6-4e8b-aaa6-88dcfa2f8ec7)

#### Adding `data-view-only` attribute to WP Dashboard and Admin Bar elements

In `includes/Core/Admin/Dashboard.php`:

* Modify the `render_googlesitekit_wp_dashboard` method to add the `data-view-only` attribute to the `js-googlesitekit-wp-dashboard` element if the user is in view-only mode using the `Authentication::is_authenticated` method.
* This will require a new `authentication` private instance and `Authentication` instantiation in the `__construct` method.

In `includes/Core/Admin_Bar/Admin_Bar.php`:

* Modify the `menu_markup` method to add the `data-view-only` attribute to the `js-googlesitekit-adminbar` element if the user is in view-only mode using the `Authentication::is_authenticated` method.
* This will require a new `authentication` private instance and `Authentication` instantiation in the `__construct` method.

In `assets/js/googlesitekit/constants.js`:

* Add `VIEW_CONTEXT_WP_DASHBOARD_VIEW_ONLY` and `VIEW_CONTEXT_ADMIN_BAR_VIEW_ONLY` constants.

In `assets/js/googlesitekit-wp-dashboard.js` and `assets/js/googlesitekit-adminbar.js`:

* Conditionally pass the view context to the `Root` component as we've done for the main dashboard and entity dashboard. See:
https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/googlesitekit-entity-dashboard.js#L42-L50

In `assets/js/hooks/useViewOnly.js`:

* Update the logic to check for the `VIEW_CONTEXT_WP_DASHBOARD_VIEW_ONLY` and `VIEW_CONTEXT_ADMIN_BAR_VIEW_ONLY` constants.

#### Enabling WP Dashboard and Admin Bar widgets on the server

In `includes/Core/Permissions/Permissions.php`:

* Modify the `map_meta_capabilities` method with the following:
  * Update the condition that checks whether the current capability `$cap` is not one of the specified capabilies (`AUTHENTICATE`, `SETUP`, `VIEW_DASHBOARD`, `VIEW_POSTS_INSIGHTS`) to include `VIEW_WP_DASHBOARD_WIDGET` and `VIEW_ADMIN_BAR_MENU`.
  * Revise the switch statement within the method to handle `VIEW_WP_DASHBOARD_WIDGET` and `VIEW_ADMIN_BAR_MENU` capabilities separately. These should be directed to use a new method, `check_view_wp_dashboard_widget_and_admin_bar_capability`.
* Create the `check_view_wp_dashboard_widget_and_admin_bar_capability` (or any appropriate name) method to check if the user can view the WP Dashboard Widget and Admin Bar Menu using the following:
  * Initially call `check_view_dashboard_capability()`. If this method returns an array containing either `self::AUTHENTICATE` or `do_not_allow`, then immediately return the same result, indicating that the user is authenticated or does not have the necessary permissions.
  * If `check_view_dashboard_capability()` does not return `do_not_allow`, proceed to check whether the user has a shared role for either the 'analytics' or 'search-console' modules. This can be done using `user_has_shared_role_for_module( $user_id, 'analytics' )` OR `user_has_shared_role_for_module( $user_id, 'search-console' )`.
  * If the user does not have a shared role for either 'analytics' or 'search-console', return an array containing `do_not_allow`. Otherwise, return an empty array, indicating permission is granted.

In `assets/js/googlesitekit/datastore/user/permissions.js`:

* Create a new selector `hasAccessToShareableModule` to check if the user has access to any of the shareable modules with the following:
    * Receives the `moduleSlug` as a parameter.
    * Check if the module is available using the `isModuleAvailable` selector.
    * Return `false` if the module is not available.
    * Check if the user is in view-only mode (not authenticated) using the `isAuthenticated` selector.
    * Return `false` if the user is not authenticated.
    * Check if the can view the shared module using the `canViewSharedModule` selector.

#### Handling WP Dashboard widgets for Shared Analytics and Search Console

In `assets/js/components/wp-dashboard/WPDashboardWidgets.js`:

* Render the following widgets if the user can view the shared `analytics-4` module using the new `hasAccessToShareableModule` selector:
    * `WPDashboardUniqueVisitorsGA4Widget`
    * `WPDashboardUniqueVisitorsChartGA4Widget`
    * `WPDashboardSessionDurationGA4Widget`
    * `WPDashboardPopularPagesGA4Widget`
* Render the following widgets if the user can view the shared `search-console` module using the new `hasAccessToShareableModule` selector:
    * `WPDashboardImpressionsWidget`
    * `WPDashboardClicksWidget`

#### Handling Admin Bar widgets for Shared Analytics and Search Console

In `assets/js/components/adminbar/AdminBarWidgets.js`:

* Render the following widgets if the user can view the shared `analytics-4` module using the new `hasAccessToShareableModule` selector:
    * `AdminBarUniqueVisitorsGA4Widget`
    * `AdminBarSessionsGA4Widget`
* Render the following widgets if the user can view the shared `search-console` module using the new `hasAccessToShareableModule` selector:
    * `AdminBarImpressionsWidget`
    * `AdminBarClicksWidget`
* Adjust the `Cell` component's `lgSize` or `mdSize` based on the availability of shared modules for the view-only user to occupy the space that the unavailable widgets would otherwise occupy.

#### Updating Track Event View Context

In `assets/js/googlesitekit-adminbar.js`:

* Conditionally update the `trackEvent` view context to `VIEW_CONTEXT_ADMIN_BAR_VIEW_ONLY` if the user is in view-only mode.
* As for `assets/js/components/adminbar/AdminBarApp.js`, it already uses the `useViewContext` hook to get the view context, so it should be updated automatically.

### Test Coverage

* Add PHPUnit test coverage for the logic introduced in `check_view_wp_dashboard_widget_and_admin_bar_capability` (e.g. see `PermissionsTest::verify_view_shared_dashboard_capability`).
* Add tests for the new `hasAccessToShareableModule` selector.
* Add tests for the `useViewOnly` hook.
* In `assets/js/components/adminbar/AdminBarWidgets.test.js`, add tests to check the widgets' availability based on the shared modules for the view-only user.
* In `assets/js/components/adminbar/AdminBarApp.stories.js` and `assets/js/components/adminbar/AdminBarWidgets.stories.js` stories, add stories to check the availability of the widget based on the shared modules for the view-only user.
* Fix any failing tests.
* Fix any broken storybook stories for the WP Dashboard and Admin Bar widgets.
* Update VRT images if necessary.

## QA Brief

**Note:** Clear the session storage before testing each scenario since we cache the report data in the session storage.

* Set up a site with Site Kit and connect Analytics and Search Console.
* Share the Analytics and Search Console modules with a view-only user.
* Log in as the view-only user and check the WP Dashboard widgets.
* Verify that the WP Dashboard widgets are displayed as expected based on the shared modules.
* Verify that the WP Dashboard widgets are not displayed if the user cannot access any of the shared modules as per the AC.
* Verify that the Admin Bar widgets are displayed as expected based on the shared modules.
* Verify that the Admin Bar widgets are not displayed if the user cannot access any of the shared modules as per the AC.
* Verify that the Admin Bar widgets take twice the width if the user can access only one shared module.
* Simulate the insufficient permissions error using the [Tweak for Chrome](https://chrome.google.com/webstore/detail/tweak-mock-and-modify-htt/feahianecghpnipmhphmfgmpdodhcapi) extension and add the following values to the fields:
    * URL: `^(.*)\/wp-json\/google-site-kit\/v1\/modules\/(.*)$` (Enable Regex matching via the `.*` button to the right of the field)
    * HTTP Method: `GET`
    * Status Code: `403`
    * Delay By: `0s`
    * Response Payload:
```
{
  "code": 403,
  "message": "Insufficient Permissions Test Error",
  "data": {
    "status": 403,
    "reason": "insufficientPermissions"
  }
}
```
* Ensure that the extension and rule are both enabled.
* To simulate the error response only for Analytics, use the following Regex for the URL field: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/report?.*`

![Screenshot 2024-01-24 at 7 13 17 PM](https://github.com/google/site-kit-wp/assets/24408261/f1780b6b-9eb7-4031-a61b-47fefd06e047)

![Screenshot 2024-01-24 at 7 14 42 PM](https://github.com/google/site-kit-wp/assets/24408261/43d561a3-8342-43c3-b84d-65934d16cdc0)

## Changelog entry

* Create a shared version of the Admin Bar and certain dashboard widgets for users of Dashboard Sharing.

**Comment by techanvil** [comment]
Reviewing the [issue](https://github.com/google/site-kit-wp/issues/5202) where we introduced the `VIEW_WP_DASHBOARD_WIDGET` and `VIEW_ADMIN_BAR_MENU` capabilities, it would suggest that the way forward here is to re-enable the WP Dashboard widget and Admin Bar for view-only users who have a shared role for at least one of the Search Console and Analytics modules. I've therefore added AC to cover these use cases and have moved this out of Stalled to ACR.

**Comment by tofumatt** [comment]
ACs look good to me 👍🏻

**Comment by bethanylang** [comment]
@hussain-t Are you planning to work on this soon? If not, can you please unassign yourself so someone else can pick up? Thank you!

**Comment by hussain-t** [comment]
Yes, @bethanylang. I'll work on it today. Thanks!

**Comment by techanvil** [comment]
Hey @hussain-t, good work on the IB so far. I have a few comments:

- I'd suggest extending/modifying the permissions logic to only allow the capabilities if `check_view_dashboard_capability()` allows it and _only_ Analytics or SC is shared, so we avoid rendering the dashboard widget/admin bar if some other module is shared.
- We should specify the creation a reusable selector for the described logic for checking if a module can be viewed.
- We should also reuse this selector in `AdminBarWidgets` rather than `canViewSharedModule()` which returns false if the module is not explicitly shared.
- It seems like the aforementioned logic should be available at page load time, this being the case we should be able to use it to avoid rendering the widgets entirely rather than checking it within the widgets. Does that look correct to you?
- Rather than updating `ReportError` to check for `isAuthenticated()`, I think we should take the more robust step of making `useViewOnly()` work for the dashboard widget and admin bar. We can do this by applying the same approach as the dashboard, rendering a [`data-view-only` attribute](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/includes/Core/Admin/Screens.php#L398) in the root elements for the [dashboard widget](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/includes/Core/Admin/Dashboard.php#L121) and the [admin bar](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/includes/Core/Admin_Bar/Admin_Bar.php#L282), then adding new view contexts in the same way we've got the dashboard view-only variants, passing them to `Root`'s `viewContext` prop (e.g. as seen in [`googlesitekit-entity-dashboard.js`](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/googlesitekit-entity-dashboard.js#L42-L50), updating in [`googlesitekit-adminbar.js`](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/googlesitekit-adminbar.js#L46) and [`googlesitekit-wp-dashboard.js`](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/googlesitekit-wp-dashboard.js#L41)) and checking for them in `useViewOnly()`.
  - This will have the benefit of ensuring components can be reusable by using the `useViewOnly()` hook instead of the less clear approach of checking for authentication.
  - It will also have the benefit of allowing the admin bar [events](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307&range=93:94) to be tracked (i.e. [`view_urlsummary`](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/googlesitekit-adminbar.js#L52) and [`open_urldetails`](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/components/adminbar/AdminBarApp.js#L57)) with the new view context as the category. Please you can confirm these with Mariya before proceeding.

**Comment by hussain-t** [comment]
Thanks, @techanvil. I've updated the IB and increased the estimate as it requires more changes. LMK if that looks good.

**Comment by techanvil** [comment]
Thanks @hussain, this is looking good. A last few points:

- You can remove the change to `ReportError` as it's no longer needed.
- Please can you revisit the following point from my previous review, it would be good to entirely avoid rendering the widgets if possible, rather than having to render `null` within them.

> It seems like the aforementioned logic should be available at page load time, this being the case we should be able to use it to avoid rendering the widgets entirely rather than checking it within the widgets. Does that look correct to you?

- Lastly, as per the last point in my previous review, have you confirmed the new events with Mariya? I imagine she will want to add them to the events sheet if we are proceeding with them.

**Comment by hussain** [comment]
> Thanks @hussain, this is looking good. A last few points:
> 
> * You can remove the change to `ReportError` as it's no longer needed.
> * Please can you revisit the following point from my previous review, it would be good to entirely avoid rendering the widgets if possible, rather than having to render `null` within them.
> 
> > It seems like the aforementioned logic should be available at page load time, this being the case we should be able to use it to avoid rendering the widgets entirely rather than checking it within the widgets. Does that look correct to you?
> 
> * Lastly, as per the last point in my previous review, have you confirmed the new events with Mariya? I imagine she will want to add them to the events sheet if we are proceeding with them.

Probably you meant @hussain-t

**Comment by techanvil** [comment]
Sorry @hussain! I did indeed mean @hussain-t, thanks.

**Comment by hussain-t** [comment]
Hi @marrrmarrr, I'm following up on a suggestion from @techanvil regarding implementing a view-only context for the Admin Bar menu `adminBarViewOnly`. 

As Tom mentioned, this approach could offer the benefits of enabling event tracking within the admin bar for view-only mode:

>It will also have the benefit of allowing the admin bar [events](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307&range=93:94) to be tracked (i.e. [view_urlsummary](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/googlesitekit-adminbar.js#L52) and [open_urldetails](https://github.com/google/site-kit-wp/blob/690f83f17718bd53f4678fd3da2417e2dc39e1af/assets/js/components/adminbar/AdminBarApp.js#L57)) with the new view context as the category. Please you can confirm these with @marrrmarrr before proceeding.

**Comment by marrrmarrr** [comment]
@hussain-t that sounds good, as long as the view context is there so it's possible to distinguish where these events originated.

**Comment by hussain-t** [comment]
Thanks, @marrrmarrr.

@techanvil, back to you for another review.

**Comment by techanvil** [comment]
Thanks @hussain-t! This IB LGTM. :white_check_mark: 

Note that I made a small tweak to the first point under Test Coverage, as we should create a new test case rather than modify `verify_view_shared_dashboard_capability`.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified on view only dashboard.
- Verified on site with data.
- Verified on site having gathering and zero data state. 
- Verified that on WP dashboard and Site kit Admin bar under view only dashboard Analytics and Search console data is showing under view only dashboard.
- Verified the insufficient permission error state.
- Verified that Analytics 4 and Search console data is showing as per AC.


<details>


**1) Both Search Console and Analytics 4 shared.**

![image](https://github.com/google/site-kit-wp/assets/94359491/2ecf099d-4dfa-46cf-bca1-f0f173fa76b7)

![image](https://github.com/google/site-kit-wp/assets/94359491/b618c5e1-6bd9-481c-a651-09930920f6ed)

![image](https://github.com/google/site-kit-wp/assets/94359491/16f22280-b428-4e01-961b-57e2801916ae)

</details>

<details>

**2) Only Search Console is shared**

![image](https://github.com/google/site-kit-wp/assets/94359491/fac8d981-87c2-4e22-ae7a-895248cc0716)

![image](https://github.com/google/site-kit-wp/assets/94359491/1edfe2d0-47d5-49df-bdfa-aa4b1069adef)

</details>

<details>

**3) Only Analytics 4 is shared**

![image](https://github.com/google/site-kit-wp/assets/94359491/40e89df0-8464-4110-af6e-67065c18317d)

![image](https://github.com/google/site-kit-wp/assets/94359491/86ff40a2-2c02-4937-80b5-aef3c9cb83f5)

</details>

<details>

**4) No Search console and Analytics 4 shared**

![image](https://github.com/google/site-kit-wp/assets/94359491/39fc6daa-9f4f-474e-8774-cd0975f6b7c8)

![image](https://github.com/google/site-kit-wp/assets/94359491/1bbabc3c-a7c4-4b7b-9d59-117b8159605d)

</details>

<details>

**5) Insufficient Permission error**

![image](https://github.com/google/site-kit-wp/assets/94359491/a5f51b15-e6c0-4502-8c1a-e97e4470b632)

![image](https://github.com/google/site-kit-wp/assets/94359491/ab133a5d-1efe-41dc-a210-a0a917592701)

![image](https://github.com/google/site-kit-wp/assets/94359491/05647f98-6c3c-4a13-bfaf-43df17a0320a)

![image](https://github.com/google/site-kit-wp/assets/94359491/c1d0e1f1-f612-4c02-b85a-440ec4fac8eb)

</details>

<details>

**6) Gathering state - When only Analytics 4 is shared**

![image](https://github.com/google/site-kit-wp/assets/94359491/08a2dc8c-ea2f-4abb-99ef-f85159562ea3)

![image](https://github.com/google/site-kit-wp/assets/94359491/12c33d2b-7ea7-4099-a25e-399856c5c1dc)

</details>

<details>

**7) Gathering state -  When Only SC is shared**

![image](https://github.com/google/site-kit-wp/assets/94359491/1969b603-3f42-4c72-927c-26f282dc0a91)

![image](https://github.com/google/site-kit-wp/assets/94359491/d1e6d225-a49d-4302-9fd9-3dc9d5c8462b)

</details>

<details>

**8) Gathering state - When both Analytics 4 and SC shared**

![image](https://github.com/google/site-kit-wp/assets/94359491/2336228d-d85f-4372-bc1f-7ce79364637e)

![image](https://github.com/google/site-kit-wp/assets/94359491/e275053e-9aba-4363-9cfa-8a04e6fa814b)

</details>
