### ISSUE TITLE
Fix Key Metric Navigation chip icon

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7347]
## Bug Description

The Key Metrics Navigation chip icon should be updated to match the [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1949%3A49590&mode=dev).

## Steps to reproduce

1. Enable the `userInputv2` feature flag to show the Key Metrics navigation chip on the Site Kit dashboard.
2. The icon is incorrect and should be updated to match the [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1949%3A49590&mode=dev).

## Screenshots

Incorrect:
<img width="724" alt="Screenshot 2023-07-21 at 11 43 01" src="https://github.com/google/site-kit-wp/assets/1721319/e2c7e9fb-e4c5-4fb3-9651-28a8d2309d69">

Correct:
<img width="706" alt="Screenshot 2023-07-21 at 11 44 25" src="https://github.com/google/site-kit-wp/assets/1721319/81471950-cf09-4c3b-93a0-aab7a37430b4">

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Key Metrics Navigation chip icon should be updated to match the [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1949%3A49590&mode=dev).

## Implementation Brief

* Being a minor straightforward change which creates a new SVG and imports it into the Navigation component, there is a [PR](https://github.com/google/site-kit-wp/pull/7446) created for this issue which can be reviewed directly.

### Test Coverage

* No new tests required.

## QA Brief

* Verify the Key Metrics navigation chip icon is as per the Figma mock, changes colour correctly based on being the active chip or not and works well on all view-ports.

## Changelog entry

* Update key metrics nav icon to match design.

**Comment by aaemnnosttv** [comment]
@jimmymadon does this icon use a particular icon from the [material icons set](https://fonts.google.com/icons)? If so, let's reference that as the source of truth to use for the vector.

**Comment by aaemnnosttv** [comment]
IB ✅ 

Moving to CR

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- When the navigation chip is active for Key Metrics, the colour of the icon and title is `#3C7251` and when it is not active, the colour changes to  `#161b18`
- The icon design and placement is as per the figma designs. 
- No icon appears when viewing the dashboard on a smaller viewport, i.e. mobile. 
- The `key-metrics` part of the URL appears when the navigation chip is clicked. 
- Navigation chip continues to work as expected. 


<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/f2dcf339-5d37-43f1-9057-3f49a348bfc8)
![image](https://github.com/google/site-kit-wp/assets/73545194/1e016fc6-804d-431a-943f-6562490bb547)
![image](https://github.com/google/site-kit-wp/assets/73545194/cd019ce4-8db5-4726-b905-aa686e2b15d8)

</details>
