### ISSUE TITLE
Hide KMW Setup CTA Banner on View Only Dashboard and Implement widget set up when user picks their own metrics

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7349]
## Feature Description

If an admin (or multiple admins) selects their own metrics from the start, the non-authenticated admins / view-only users will see an automated set of metrics based on the [“Neutral / Catch all” segment](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.zc9k0id36g3e). This will be the case until at least one authenticated admin answers the questionnaire. These users will still see the button to change their own metrics allowing them to edit their own metrics as well. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If an admin does not answer the questionnaire and chooses to 'Pick their own metrics':
    * When the admin clicks "Apply Changes" in the metrics selection panel, the "Set up Banner CTA" should be hidden.
    * When another admin or non-authenticated user logs in and loads the dashboard, the "Set up Banner CTA" should be hidden for them as well. They should see the set of key metrics which would be shown if an admin had selected the `share_portfolio` answer:
        - `kmSearchConsolePopularKeywords` (Top performing keywords)
        - `kmAnalyticsNewVisitors` (New Visitors)
        - `kmAnalyticsTopTrafficSource` (Top Traffic Source)
        - `kmAnalyticsEngagedTrafficSource` (Most engaged traffic source)
* The Key Metric's Setup CTA Banner should be hidden for all users once the Key Metrics widget has been successfully set up. This is regardless of whether any admin has answered the questionnaire or not, i.e. the metrics could have been "user-picked" by an admin without answering the questionnaire.
* The Key Metrics Setup Banner CTA should not be displayed for non-authenticated admins (i.e. on the View Only dashboard. The Banner should never be shown regardless if the KM widget has been set up or not.

## Implementation Brief

* Within `includes/Core/Key_Metrics` folder, create a new class called `Is_Key_Metrics_Setup_Complete` which extends `Setting`. It should deal with storing a "boolean" type `OPTION` named `googlesitekit_is_key_metrics_setup_complete` in the options table in the database. The default value of this option should be false.
* Within the `REST_Key_Metrics_Controller` -> `POST:core/user/data/key-metrics` and `REST_User_Input_Controller` -> `POST:core/user/data/user-input-settings` routes:
    * Set the `Is_Key_Metrics_Setup_Complete` options setting created above (using the `set()` method) to `true`.
* Within `Key_Metrics.php`:
  * Register the `Is_Key_Metrics_Setup_Complete` class in the register method. 
  * Use the `googlesitekit_inline_base_data` filter to expose the `Is_Key_Metrics_Setup_Complete` option to an inline JS `isKeyMetricsSetupComplete` data variable.
* Within `assets/js/googlesitekit/datastore/user/key-metrics.js`:
    * Create a selector named `isKeyMetricsSetupComplete` which returns the value of the `isKeyMetricsSetupComplete` variable exposed above.
    * In the `getKeyMetrics` selector, if there are no metrics returned from `getAnswerBasedMetrics`, use the selector above to check if the Key metrics widget is setup. If yes, return the metric slugs as per the AC, otherwise an empty array.
* Within `register-defaults.js`, when registering `KeyMetricsSetupCTAWidget.js` component:
  * Wrap the registration with the `userInputv2` Feature flag check. 
  * Use the `isActive()` callback passing a function that calls the `isAuthenticated()` selector and the `isKeyMetricsSetupComplete` selector created above (both from the `CORE_USER` store). This should prevent the registration if the user is not authenticated OR if the key metrics widget is set up.
* Within the `KeyMetricsSetupCTAWidget.js` component:
  * Wrap this component with the `whenActive` HOC passing { moduleName: 'analytics-4' } to ensure the banner is displayed only if GA4 is connected.
  * Remove the following conditions to render `<WidgetNull>` which are now already covered:
    * `userInputEnabled` feature flag check
    * `isUserInputCompleted` check
    * `analyticsModuleConnected` check

### Test Coverage

* Update the tests for the `getKeyMetrics` selector.

## QA Brief

* The AC covers the changes quite well
* The setup CTA for KMW should only show now if the user is authenticated and:
    * User input has not been completed AND
    * No user has already picked their own metrics
* Note the above conditions only affect this going forward – older test sites with user input or already chosen metrics should not be expected to bypass the CTA
* As above due to the authentication requirement, the CTA should not be shown in any view-only context (regardless of role).

## Changelog entry

* Fix the conditions for showing the Key Metrics Setup CTA banner, ensuring that it does not display when the user has setup their choice of metrics, or when viewing the shared dashboard.

**Comment by tofumatt** [comment]
Looks good, moved to IB 👍🏻

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon!

IIRC we had aligned on the concept of generally storing that KMW setup had been completed rather than specifically that a user had chosen their own metrics? 🤔 I think this would be more valuable as a setting flag since we could infer that a user had picked their own if the setup was complete but user input had not been answered/provided.

Regarding the API, I think we shouldn't need to add a new route for this either, as this setting can be set by one of the existing classes or endpoints where the setup is completed. I'm not sure if we need to reflect this change in the store right away yet, since completing the survey since this is will likely be relevant for other users rather than the one completing the setup. For that reason, I think the state can be passed through a script data object and exposed via a dedicated selector.

Then we could use this selector to control the availability of the `KeyMetricsSetupCTAWidget` via `isActive` at registration.

WDYT?

**Comment by aaemnnosttv** [comment]
LGTM, thanks @jimmymadon!

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- If an admin does not answer the questionnaire and chooses to 'Pick their own metrics':
   - When the admin clicks "Apply Changes" in the metrics selection panel, the "Set up Banner CTA" is hidden.
  - When another admin or non-authenticated user logs in and loads the dashboard, the "Set up Banner CTA" is hidden for them as well. 
  - They see the set of key metrics shown if an admin had selected the `share_portfolio` answer:
- The Key Metric's Setup CTA Banner is hidden for all users once the Key Metrics widget has been successfully set up. This is regardless of whether any admin has answered the questionnaire or not.
- The Key Metrics Setup Banner CTA is not be displayed for non-authenticated admins. The Banner is not shown regardless if the KM widget has been set up or not.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/9e2d8af1-9ef2-4ee5-ad61-64f60a3c828a)
![image](https://github.com/google/site-kit-wp/assets/73545194/1833cda9-882e-41ca-9097-e42cea12c547)
![image](https://github.com/google/site-kit-wp/assets/73545194/f0fa1460-7997-4891-a1af-25430df993f5)

</details>
