### ISSUE TITLE
Reorganize ABR components for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7353]
## Feature Description

There are a few inconsistencies that have been introduced with the components for ad blocking recovery regarding component location in the repo and naming.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `AdBlockingRecoveryWidget` component should be **renamed** to `AdBlockingRecoverySetupCTAWidget`
* The `AdBlockingRecoveryApp` component should be **moved** under the `components/setup` directory
* The `AdBlockingRecoveryToggle` component should be **moved** under the `components/settings` directory
* The `AdBlockingRecoveryCTA` component should be **moved** under the `components/settings` directory and **renamed** to `AdBlockingRecoverySetupCTANotice`
* The `AdBlockingRecoveryNotification` component should be renamed to `AdBlockingRecoverySetupSuccessBannerNotification`
* All relocated components should include their complementary co-located stories and tests
* Stories and related VRT scenarios should be renamed accordingly

## Implementation Brief

* Just following the AC should be sufficient here.
    * Most of the effort is fixing imports and regenerating VRT. There should not be any surprises. 
    * If `npm run build`, `npm run test:{js|storybook|visualtest}`, run correctly, then everything is fine. 

### Test Coverage

* N/A

## QA Brief

* The Ad Blocking Recovery Setup Widget on the monetization section of dashboard, the Setup CTA Notice on Adsense view and edit settings, Ad Blocking Recovery toggle and the Ad Blocking Recovery setup flow should all render and work as expected and there should be no regression. 

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
The AC here serves as IB for the most part, so I've added a couple of guidance in IB and an estimate. Should be good to go.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified components name change as per AC.
- Verified AdBlocking recovery setup CTA is showing on main dashboard and under settings.
- Tested AdBlocking recovery setup flow through CTA banner on dashboard and also through CTA showing under AdSense Settings.
- Verified AdBlocking Recovery setup and other functionality working as expected.

<details>


https://github.com/google/site-kit-wp/assets/94359491/3c3c7bb8-d560-42c3-8124-f7de77819b34

</detail>
