### ISSUE TITLE
Update language on ABR dashboard CTA

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7357]
## Feature Description

![image](https://github.com/google/site-kit-wp/assets/12189958/7b559551-bf85-4e13-9a43-4a8a4d889944)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Make the following language change on the ABR dashboard CTA:

```diff
- Display a message to give site visitors with an ad blocker the option to allow ads on your site. Site Kit will place an ad blocking recovery tag on your site.
+ Display a message to give site visitors with an ad blocker the option to allow ads on your site.
```

## Implementation Brief

* Update the language per the AC
* Merge https://github.com/google/site-kit-wp/pull/7359

### Test Coverage

* No changes necessary; VRT may need updating

## QA Brief

* Review the VRTs and/or Ad Blocking Recovery Dashboard CTA (by enabling Ad Blocking Recovery feature flag, setting up AdSense, and visiting the Dashboard).
* The copy should reflect the ACs.

## Changelog entry

* Update the Ad Blocking Recovery CTA text.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:

- The copy change is as per the AC.  
- Checked that the `Learn more` link continues to function as expected.
- Quick check on smaller viewports to make sure there are no issues with UI. 

![image](https://github.com/google/site-kit-wp/assets/73545194/d8335a9e-4dbe-4c81-a8e1-76aca09696b5)
