### ISSUE TITLE
Refactor encoded SVG in CSS with components

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7363]
## Feature Description

We have a few instances of encoded SVGs being used in CSS. For example:

https://github.com/google/site-kit-wp/blob/54565cc15efa628dd400ed13aa5e012058a47a31/assets/sass/components/global/_googlesitekit-accordion.scss#L46-L47

Such encoded usages make it harder to make changes to the usage, for example, color updates. This issue has been opened with an aim to evaluate these usages and to see if they can be replaced with icon SVGs/components.

First reported [here](https://github.com/google/site-kit-wp/pull/7326#discussion_r1272695318).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All instances of inline SVGs embedded in SCSS should be replaced with a SVG icon in React component. 
* This includes:
    * ~Google Logo on WP Admin Bar.~ (Cannot be replaced due to WordPress API limitations, see IB below.)
    * The expand more icon on [Accordions](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global--accordion). 
    * The connection status icons on plugin [page header](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-header--plugin-header). 
    * The warning icon on [TextField](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-text-fields--default) component. 
    * The module connection status icons and the expand more in [Module settings](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module-settings--view-closed) pages. 
    * The warning icon on plugin [setup](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/setup-using-proxy-with-sign-in--start-with-error) screen. 
* Once replaced, all the icons and the related (no longer needed) CSS bits should be removed from the SCSS files.

## Implementation Brief

* Google icon in admin bar can't be replaced with svg due to WordPress API limitation for adding menu items, icon needs to be base64 encoded svg
* Modify `assets/js/components/settings/SettingsActiveModule/Header.js` and `assets/js/components/settings/SettingsAdmin.js`
  * Edit span with class `googlesitekit-settings-module__status-icon--connected`, to include SVG icon as child element
  * Style it to have proper circle background and containing checkmark SVG icon should be white
  * Apply styles in `assets/sass/components/global/_googlesitekit-modules-list.scss` and `assets/sass/components/settings/_googlesitekit-settings-module.scss`
  * Remove current inline icon added in `:before` pseudo element
  * Here is the converted SVG code for checkmark that is used as URL encoded icon now:
```html
<svg width="16" height="12" viewBox="0 0 16 12" xmlns="http://www.w3.org/2000/svg">
    <g fill="#FFF" fill-rule="evenodd">
        <path d="M0 6.414L1.415 5l5.292 5.292-1.414 1.415z"/>
        <path d="M14.146.146l1.415 1.414L5.414 11.707 4 10.292z"/>
    </g>
</svg>
```
* Modify following files:
  * `assets/js/modules/analytics/components/common/AdsConversionIDTextField.js`
  * `assets/js/modules/tagmanager/components/common/ContainerNameTextField.js`
    * Add SVG icon within span with class `googlesitekit-text-field-icon--error`
    * Apply styling so that span can have proper circular red background, and icon white colour in `assets/sass/components/global/_googlesitekit-text-field-icon.scss`
    * Remove the usage of `:before` that adds the icon as inline SVG
    * This is the extracted SVG code:
```html
<svg width='22' height='19' xmlns='http://www.w3.org/2000/svg'>
    <path d='M0 19h22L11 0 0 19zm12-3h-2v-2h2v2zm0-4h-2V8h2v4z' fill='#FFF'/>
</svg>
```
* Modify `assets/js/components/Accordion.js`
  * Add SVG icon after [the title](https://github.com/google/site-kit-wp/blob/532e7e5dff8ddf03f1c9b7dbfe500e0e81cc57e3/assets/js/components/Accordion.js#L87)
  * Apply proper styling to it - color, size, etc in `assets/sass/components/global/_googlesitekit-accordion.scss`
  * Remove inline icon from it's usage in `:after` and styles that are not needed
```html
<svg width="12" height="8" viewBox="0 0 12 8" xmlns="http://www.w3.org/2000/svg">
    <path d="M10.6.6L12 2 6 8 0 2 1.4.6 6 5.2z" fill="#030E07" fill-opacity="0.32" fill-rule="evenodd"/>
</svg>
```
* In `assets/sass/components/global/_googlesitekit-text-field-icon.scss`
  * This [code](https://github.com/google/site-kit-wp/blob/532e7e5dff8ddf03f1c9b7dbfe500e0e81cc57e3/assets/sass/components/global/_googlesitekit-text-field-icon.scss#L20-L37) should be removed, and color applied to svg selector if applicable. 
* In `assets/sass/components/setup/_googlesitekit-setup.scss`
  * Remove `::before` inline svg added under `.googlesitekit-setup__notice-warning-icon`, it seems icon is already replaced with SVG icon, and this is leftover that is unused now.

### Test Coverage

* Update stories to include SVG icon, for edited files, as removing `:before` inline svg will leave some places without icons
* Update VRT reference images

## QA Brief

* Do a general check of the plugin in general and ensure all icons are showing properly, especially in settings, connect services, like chevron for accordion, connected/not connected icons on the modules, in admin settings, warning icon when editing Analytics settings (try inputing `-` in Ads conversion ID field), etc. 

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Yes! 👍🏻👍🏻👍🏻 

Moving to IB 🙂

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- @zutigrm I found that icons are not aligned on dev branch under "Connect More Services". 

![image](https://github.com/google/site-kit-wp/assets/94359491/7f9039db-c088-4ac7-bfbb-408ac3ca6b95)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- As discussed in slack [above](https://github.com/google/site-kit-wp/issues/7363#issuecomment-1850013000) reported will be address through https://github.com/google/site-kit-wp/issues/7542#issuecomment-1849909783. 
- Tested on dev environment.
- Verified all SVG icons as per AC and QAB.
- All SVGs icons are appearing correctly and alignment issue will be address in #7542.

**Comment by aaemnnosttv** [comment]
## Approval

@zutigrm I found a few instances of this which are still in the SCSS, although we can address these in a follow-up, if needed.

https://github.com/google/site-kit-wp/blob/8af3f7e8a0dcaf18b5ddd3e42b4e9b7252ccf4e8/assets/sass/components/adminbar/_googlesitekit-wp-adminbar.scss#L39-L40

While the IB mentions that this cannot be replaced, I'm not sure if this is entirely correct. The WP admin _menu_ has a similar limitation and where we use `Google_Icon` to provide the svg.

https://github.com/google/site-kit-wp/blob/8af3f7e8a0dcaf18b5ddd3e42b4e9b7252ccf4e8/assets/sass/vendor/_mdc-button.scss#L59-L60

This one may have been skipped since it is "vendor" although it may have been missed.
