### ISSUE TITLE
Address inconsistencies in the Loyal Visitors, New Visitors, and "Most popular content" Key Metrics widgets.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7366]
## Bug Description

_Note, this issue has been split out from #7214 to unblock those aspects that can be worked on while we wait for a response from GA._

There are inconsistencies in the data displayed on the Loyal Visitors, New Visitors, and "Most popular content by pageviews" Key Metrics widgets.

- The values for "total visitors" on the Loyal Visitors and New Visitors widgets is incorrect and doesn't reflect the total active user count.
- The values on the "Most popular content by pageviews" are incorrect and don't match what's displayed on the main "Top content..." widget.

### Loyal/New Visitors

1. Setup Site Kit with the `userInput` feature flag enabled and connect GA4.
2. Click on "Get tailored metrics" on the Key Metrics CTA, answer "Publish a blog" for the first question and continue to finish the questionnaire.
3. Back on the Dashboard you should now see the Loyal Visitors and New Visitors widgets.
4. Click on the Analytics source link in the All Traffic widget to open the Analytics site with the current date range selected.
5. Compare the "total visitors" values with the top "Users" value as per the screenshots below.
6. These should match, but are currently different.

### Most popular content by pageviews

7. Now, run the following snippet to view the "Most popular content by pageviews" widget:

```js
googlesitekit.data.dispatch("core/user").receiveGetKeyMetricsSettings({
  widgetSlugs: ["kmAnalyticsPopularContent"],
});
```

8. Scroll down to the main "Top content..." widget and check the sites and figures, which should match, but currently don't.
9. On the Analytics site, navigate to the Pages and Screens report to verify the correct figures.

### Loyal/New Visitors

Here are the "total visitors" values for Loyal Visitors and New Visitors widgets on an example site.

![image](https://github.com/google/site-kit-wp/assets/18395600/a284a66d-5f1e-43bd-ba83-abab8848893a)

While here is the value it should display, as seen on a corresponding report on the Analytics site.

![image](https://github.com/google/site-kit-wp/assets/18395600/79d27d6b-de00-4e74-8f93-c27a47bd6247)

### "Most popular content by pageviews"

Here is the "Most popular content by pageviews" widget on an example site.

![image](https://github.com/google/site-kit-wp/assets/18395600/dba7c62f-f63b-46ee-8808-759802522625)

As can be seen the data doesn't match with the main "Top content..." widget, which has the correct values.

![image](https://github.com/google/site-kit-wp/assets/18395600/eeab3719-c56c-4335-acf1-4e94e8da5987)

These can be validated by looking at the Pages and Screens report on the Analytics site.

![image](https://github.com/google/site-kit-wp/assets/18395600/45e6ef0c-9099-415b-a324-330bff73509e)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The "total visitors" values for the Loyal Visitors and New Visitors Key Metrics widgets should match the user count for a corresponding report on the Analytics site.
  - Note, it's _not_ necessary to match the All Users value on Site Kit's All Traffic widget at this point, because this uses the `totalUsers` metric while Loyal Visitors and New Visitors use the `activeUsers` metric.
- The values on the "Most popular content by pageviews" should match the top three values on the main "Top content..." widget, as well as the top three values on a corresponding report on the Analytics site.
- These should be the case for all properties, across all of Site Kit's available date ranges.

## Implementation Brief

- In both the `LoyalVisitorsWidget` and `NewVisitorsWidget` components:
  - Rather than calculate it ourselves, retrieve the "total visitors" values from the `totals` aggregate field in the response, i.e. `report.totals[ index ].metricValues[ 0 ].value`, where `index` is `0` for the current date range and `1` for the previous. This will ensure the total figure matches that used for "All Users" - at the moment it appears we are double-counting some users by adding all of the values, presumably some "new" users also return and get counted as "returning" users as well within the same report.
- In the `PopularContentWidget` component:
  - Rather than retrieving both `pageTitle` and `pagePath` in the same report, take the approach used in [`ModulePopularContentWidgetGA4`](https://github.com/google/site-kit-wp/blob/238155defac64b722f93bca74f45e5461adb1559/assets/js/modules/analytics/components/module/ModulePopularPagesWidgetGA4.js), removing `pageTitle` from the report and adding a separate call to retrieve the titles via `getPageTitles()`.

### Test Coverage

- No new tests needed.

## QA Brief

* Follow the steps to reproduce.
* Verify the data displayed in the "Loyal Visitors", "New Visitors", and "Most popular content" Key Metrics widgets are accurate.
* Note: There may still some very minor discrepancies in the numbers (up to low double digits in testing to date) that simply can't be explained. As suggested [here](https://support.google.com/analytics/thread/180423862/different-report-results-between-google-analytics-4-ui-and-google-data-api-data?hl=en) there may simply be some glitches in the reporting UI. However the figures should either be a direct match or very close.

## Changelog entry

- Address data inconsistencies in the "Loyal visitors", "New visitors", and "Most popular content" Key Metrics widgets.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The "total visitors" values for the Loyal Visitors and New Visitors Key Metrics widgets match the user count for a corresponding report on the Analytics site.
- The values on the "Most popular content by pageviews" match the top three values on the main "Top content..." widget, as well as the top three values on a corresponding report on the Analytics site.
- Checked the values across all of Site Kit's available date ranges.

**Note:**  I did notice a slightly difference on the Loyal Visitors and New Visitors tiles, but it was much closer than the data that we were seeing before. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/df0be85d-36d0-45ad-acea-c432c19855f3)
![image](https://github.com/google/site-kit-wp/assets/73545194/bc047ee3-5a94-4314-8c3f-367f0092a2c1)
![image](https://github.com/google/site-kit-wp/assets/73545194/8c4e2ca2-a8ff-4fe6-9713-df408055511e)
![image](https://github.com/google/site-kit-wp/assets/73545194/135de5c5-d775-4ba7-a652-e57c661dd886)
![image](https://github.com/google/site-kit-wp/assets/73545194/e4359ee5-8997-4492-abd1-4ca8863d9db5)

</details>
