### ISSUE TITLE
Add GA event tracking for Ad Blocking Recovery

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7368]
## Feature Description

This issue is about adding various GA events to the Ad Blocking Recovery interface of Site Kit plugin interface for the users who have opted in to the anonymous usage data reporting. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following GA events should be tracked for various Ad Blocking Recovery actions.
* `AdBlockingRecoveryWidget`
    * Event Category: `{viewContext}_adsense-abr-cta-widget`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `view_notification` | When the component becomes visible. Should only be triggered when the component is visible on the screen (user has scrolled to the monetization section) and not returning `null`. |
        | `confirm_notification` | When the primary CTA `Set up now` button is clicked | 
        | `dismiss_notification` | When the secondary CTA `Maybe later` button is clicked | 
        | `click_learn_more_link` | When the `Learn more` link is clicked |
    * Event Category: `{viewContext}_adsense-abr`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `view_tooltip` | When the `AdminMenuTooltip` on this component is visible|
        | `dismiss_tooltip` | When the `X` is clicked to dismiss the tooltip | 
* `AdBlockingRecoveryCTA`
    * Event Category: `{viewContext}_adsense-abr-cta-widget`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `view_notification` | When the component becomes visible. Should only be triggered when the component is not returning `null`. |
        | `confirm_notification` | When the CTA `Set up now` button is clicked | 
        | `click_learn_more_link` | When the `Learn more` link is clicked |
* `AdBlockingRecoveryApp` -> `SetupMain`
    * Event Category: `{viewContext}_adsense-abr`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `cancel_setup` | When the "Cancel" button is clicked. This should also have a label based on the stage in which the button was clicked. Values are: `on_place_tag_step`, `on_create_message_step` and `on_final_step`. | 
* `AdBlockingRecoveryApp` -> `SetupMain` -> `PlaceTagsStep`
    * Event Category: `{viewContext}_adsense-abr`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `setup_place_tag` | When the `PlaceTagsStep` becomes visible |
        | `setup_enable_tag` | When the `Enable message` CTA is clicked | 
        | `uncheck_box` | When the `Enable error protection code (optional)` checkbox is unchecked | 
        | `check_box` | When the `Enable error protection code (optional)` checkbox is checked | 
* `AdBlockingRecoveryApp` -> `SetupMain` -> `CreateMessageStep`
    * Event Category: `{viewContext}_adsense-abr`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `setup_create_message` | When the `CreateMessageStep` becomes visible |
        | `create_message` | When the `Create message` CTA is clicked. It will also have a label describing whether the primary or secondary version of this button is clicked. Values are `primary_cta` and `secondary_cta` | 
        | `setup_final_step` | When the `My message is ready` button becomes visible on Step 2 | 
        | `confirm_message_ready` | When the `My message is ready` button is clicked | 
* `AdBlockingRecoveryNotification`
    * Event Category: `{viewContext}_adsense-abr-success-notification`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `view_notification` | When the notification becomes visible |
        | `confirm_notification` | When the `OK, Got it!` button is clicked | 
* `AdBlockingRecoveryToggle`
    * Event Category: `{viewContext}_adsense-abr`
        | Event Name | Trigger condition | 
        |--------|--------|
        | `enable_tag` |  When the ABR or Error Protection tag switch is enabled. Should use `abr_tag` or `error_protection_tag` label depending on which toggle is being enabled | 
        | `disable_tag` | When the ABR or Error Protection tag switch is disabled. Should use `abr_tag` or `error_protection_tag` label depending on which toggle is being disabled | 

## Implementation Brief

* Get the `viewContext` for the dynamic part of the event category using the `useViewContext()` hook. 
* Dispatch the event tracking using the `trackEvent()` function from `assets/js/util/index.js`.
    * Remember to `await` this when there is chance of it not finishing. ie. action that causes navigation. 
* Use `useInView()` hook to determine when a component is in view to track "component visible" type of events.
* Refer to AC for exact event category, names and values. The value in IB is only for easier reference and may not be perfectly synced with AC. 
* In `assets/js/modules/adsense/components/dashboard/AdBlockingRecoveryWidget.js`.
    * dispatch the `view_notification` event from an `effect` based on the `inView` state and `shouldShowWidget`. 
    * Pass a `ctaCallback` to the `BannerActions` component to track `confirm_notification` event.
    * Update the `dismissCallback` function with the `trackEvent` call in the beginning to track `dismiss_notification` event. 
    * Add a callback to the `onClick` prop of `<Link href={ learnMoreURL } external />` element to track the `click_learn_more_link` event. 
    * Add an effect to fire the `view_tooltip` event when `isTooltipVisible` is true. 
    * Add a callback to the `onDismiss` prop of `AdminMenuTooltip` to track the `dismiss_tooltip` event. 
* In `assets/js/modules/adsense/components/common/AdBlockingRecoveryCTA.js`.
    * Dispatch the `view_notification` event from an effect when the component is not returning `null`
        * store the logic that determines whether the component is being rendered in a variable for the effect and render logic. ie. `shouldShowCTA`. 
    * Add a `onClick` handler the "Set up now" button to track the `confirm_notification` event. 
    * Add a `onClick` handler to the interpolated `SupportLink` to track the `click_learn_more_link` event. 
* In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp/SetupMain.js`.
    * To track the `cancel_setup` event, update the `onCancel` callback.
        * If ` activeStep === 0 `, give it the `on_place_tag_step` label. 
        * If `createMessageCTAClicked === true`, the event label should be `on_final_step`.
        * Otherwise, the label is `on_create_message_step`.
* In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp/steps/PlaceTagsStep.js`.
    * Track the `setup_place_tag` event using a `useEffect` that fires only on mount. 
    * Track the `setup_enable_tag` by updating `onCTAClick` callback to call `trackEvent` just before changing the active step. 
    * Track the `check_box` and `uncheck_box` events by updating `onErrorProtectionTagOptionChange` callback.
* In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp/steps/CreateMessageStep.js`.
    * Track the `setup_create_message` event using a `useEffect` that fires only on mount. 
    * Add an effect to track the `setup_final_step` event when `createMessageCTAClicked === true`.
    * Update `onCTAClick` function to track `create_message` event with `primary_cta` label, and `confirm_message_ready` events.
        * if `createMessageCTAClicked === false`, track the `create_message` event.
        * Otherwise, track the `confirm_message_ready` event.
    * Add `onClick` handler to the `<Link href={ privacyMessagingURL } target="_blank">` to track the  `create_message` event with `secondary_cta` label.
* In `assets/js/components/notifications/AdBlockingRecoveryNotification.js`.
    * Add a `onView` prop the `BannerNotification` to track the `view_notification` event. 
    * Update the `handleDismiss` callback to track the `confirm_notification` event. 

### Test Coverage

* N/A

## QA Brief

* Go through the Ad Blocking Recovery interface and verify the GA events are fired as par AC using Google Analytics Debugger.
* Ensure that no regression has been introduced.
    * Give special attentions to the CTA click events, ensure they function as before while the GA events are firing correctly.

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
@aaemnnosttv @marrrmarrr  I have added the ACs as described on the Google Sheet. However, I have a few suggestion.
* Slightly less confusing event category for `{viewContext}_adsense-abr-cta-widget`. ie. `{viewContext}_adsense-abr-setup-cta-dashboard-widget`
* Separate the events for Setup Dashboard Widget and Settings Notice by using a different event category for settings. ie. `{viewContext}_adsense-abr-setup-cta-settings-notice`
* `view_tooltip` and `dismiss_tooltip` instead of `feature_tooltip_view` and `feature_tooltip_dismiss` as these are not feature tooltip. My suggested name will also be consistent with event present on `AdSenseConnectCTAWidget`.
* Adding label on `cancel_setup` event to track on which step the setup is cancelled. ie. `on_place_tag_step`, `on_create_message_step` and `on_final_step`
* Either separate event or label for the `Create message` CTA to distinguish which version (primary or secondary CTA) is clicked. 

Let me know what you think. 

Cheers. 

cc @bethanylang

**Comment by aaemnnosttv** [comment]
Thanks @kuasha420 ! 

> * Slightly less confusing event category for `{viewContext}_adsense-abr-cta-widget`. ie. `{viewContext}_adsense-abr-setup-cta-dashboard-widget`

The format used is largely based on the existing event for the AdSense setup CTA. Widgets are also only on the dashboard, and this is also included in the `viewContext` as `mainDashboard` or `entityDashboard` which is why that part is omitted from the non-dynamic part of the category for all events.

> * Separate the events for Setup Dashboard Widget and Settings Notice by using a different event category for settings. ie. `{viewContext}_adsense-abr-setup-cta-settings-notice`

I think this is covered by the above as well?

> * `view_tooltip` and `dismiss_tooltip` instead of `feature_tooltip_view` and `feature_tooltip_dismiss` as these are not feature tooltips. My suggested name will also be consistent with event present on `AdSenseConnectCTAWidget`.

Good point – looks like we don't have events for this tracked at all yet?

> * Adding label on `cancel_setup` event to track on which step the setup is cancelled. ie. `on_place_tag_step`, `on_create_message_step` and `on_final_step`

Sounds like a great idea but let's leave this as-is for now until we hear from @marrrmarrr 

> * Either separate event or label for the `Create message` CTA to distinguish which version (primary or secondary CTA) is clicked.

Good idea here as well 👍 

---

Most of the implementation isn't concerned with the specific values but wiring up the tracking infra. Let's keep things defined as in the sheet for now and move forward with some extra time allocated for adjusting the final values during execution if we decide to. We should be able to have this finalized on Monday though.

AC ✅

**Comment by kuasha420** [comment]
@aaemnnosttv Thank you for the reply, yep the `viewContext` effectively solves the problems I described. Admittedly it completely skipped my mind. Thanks.

**Comment by marrrmarrr** [comment]
@kuasha420 SG on adding new events for the non-feature-tour tooltips and adding extra labels on the cancel_setup event. 
Thanks for making our tracking even more detailed!

**Comment by kuasha420** [comment]
@marrrmarrr Thank you for the confirmation, I've updated the AC accordingly. 

@aaemnnosttv 
> Good point – looks like we don't have events for this tracked at all yet?

We have `dismiss_tooltip` for `AdSenseConnectCTAWidget` but no `view_tooltip`.

Cheers.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The GA events are fired as per AC using Google Analytics Debugger.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/4506602b-b1b7-436e-911d-6b0adefaee76)
![image](https://github.com/google/site-kit-wp/assets/73545194/d239f482-76d8-42db-bbc1-a36a7631d6aa)
![image](https://github.com/google/site-kit-wp/assets/73545194/e77a3ebb-f271-4f0e-87f3-addb11ff0792)
![image](https://github.com/google/site-kit-wp/assets/73545194/24f51e91-7e3d-4be2-99be-9221c815227a)
![image](https://github.com/google/site-kit-wp/assets/73545194/80818b95-069a-4af6-8143-69f33e76ec23)
![image](https://github.com/google/site-kit-wp/assets/73545194/b5ebd01a-6ed1-44b8-902e-62e38ac51002)
![image](https://github.com/google/site-kit-wp/assets/73545194/0b1c8249-5265-4e8a-9711-ce0c5a3efbbd)
![image](https://github.com/google/site-kit-wp/assets/73545194/a41dce82-cf44-4be8-9d91-8b86df0a2cb6)
![image](https://github.com/google/site-kit-wp/assets/73545194/5e4ecf4a-2efe-462a-9e3b-dc68224f830a)
![image](https://github.com/google/site-kit-wp/assets/73545194/1936018b-d1c1-4ccf-8f90-108f2181a288)
![image](https://github.com/google/site-kit-wp/assets/73545194/1952c579-081b-4538-8bf9-8bfe53168e84)
![image](https://github.com/google/site-kit-wp/assets/73545194/74da5003-62b9-4cf9-9160-a2d7ba190954)
![image](https://github.com/google/site-kit-wp/assets/73545194/e3eb2f14-6858-4968-aa1c-352cb087a9a4)
![image](https://github.com/google/site-kit-wp/assets/73545194/c483fe93-d3e5-4223-b0a4-cae91450b650)
![image](https://github.com/google/site-kit-wp/assets/73545194/a626ca2c-9efe-4e59-b4a8-07e46a4b96f4)
![image](https://github.com/google/site-kit-wp/assets/73545194/5c3afd96-7b4b-45f4-a69d-9db3b56f7bfd)
![image](https://github.com/google/site-kit-wp/assets/73545194/7c2cfabf-a6e1-4322-8658-4f151e6f1f47)
![image](https://github.com/google/site-kit-wp/assets/73545194/58c20da3-f86d-40fe-ad0f-2ffa7307b0f6)
![image](https://github.com/google/site-kit-wp/assets/73545194/aa3f5edc-117b-41ee-9759-abad712f2535)
![image](https://github.com/google/site-kit-wp/assets/73545194/18804e4d-e339-46ce-a197-b7289888e7cf)
![image](https://github.com/google/site-kit-wp/assets/73545194/dc1bb861-dfee-45a2-a559-5d3edf8988d1)
![image](https://github.com/google/site-kit-wp/assets/73545194/82172a84-5b4f-478a-8188-171ab439461f)
![image](https://github.com/google/site-kit-wp/assets/73545194/12b273b3-a862-4ea6-aae2-1733a228b44f)
![image](https://github.com/google/site-kit-wp/assets/73545194/e53dfcc2-74cc-441c-97cf-2d5baaffbb1c)
![image](https://github.com/google/site-kit-wp/assets/73545194/2789e921-cc37-4401-bcb7-18fa35e31cb1)
![image](https://github.com/google/site-kit-wp/assets/73545194/088c4aaf-9da7-4c49-8220-b15bb1b6db84)


</details>
