### ISSUE TITLE
Google Site Kit Incompatibility with WordPress Installed in a Custom Directory

### ISSUE THREAD

**Issue by rafaucau** [google/site-kit-wp#7373]
## Bug Description

I am experiencing an issue with the Google Site Kit plugin during configuration. After logging into my Google account and providing consent, I am redirected to a 404 page at `/wp-admin`. This happens because  I am using [roots/bedrock](https://roots.io/bedrock/), which installs WordPress in the `/wp` directory, hence the admin panel is accessed via `/wp/wp-admin`. Google Site Kit appears to not support this type of installation setup.

## Steps to reproduce

1. Install WordPress in a subdirectory, you can use boilerplate like [roots/bedrock](https://github.com/roots/bedrock) (`composer create-project roots/bedrock`).
2. Install and activate Google Site Kit plugin (run `composer require wpackagist-plugin/google-site-kit` if using [Bedrock](https://roots.io/bedrock/)).
3. Navigate to the Google Site Kit configuration page in the WordPress dashboard.
4. Click on the "Login with Google" button.
5. Log in to your Google account and provide consent.
6. Experience redirection to /wp-admin instead of the expected /wp/wp-admin, resulting in a 404 error.

## Additional Context

 - PHP Version: 8.2
 - Browser: Chrome
 - Plugin Version: 1.105.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi @rafaucau I am just dropping a final update here for you. After performing some further testing on this internally it appears that this can happen when a site that has been moved to a roots/bedrock structure after it was already registered with the Site Kit service. Meaning that you had Site Kit setup previously with this site before moving it over to roots/bedrock. 

This can also happen if you change your site path to wp-admin without roots/bedrock. If you do still have any further questions or issues with this then please do feel free to [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) with us and we can take a look at this with you.
