### ISSUE TITLE
Implement New badge for Key Metrics Widget

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7376]
## Feature Description

A "New" badge should appear next to the title of the new Key Metrics Widget as per the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=3407%3A97998&mode=dev) mock.

<img width="955" alt="Screenshot 2023-07-31 at 06 08 30" src="https://github.com/google/site-kit-wp/assets/1721319/0159c79d-a9f0-4b4e-9bcf-bb316865de0c">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A "New" badge should appear next to the title of the new Key Metrics Widget as per the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=3407%3A97998&mode=dev) mock.

## Implementation Brief

- In `assets/js/googlesitekit/widgets/register-defaults.js`:
  - Locate the widget area registration for `AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY`.
  - Update its `title` property to wrap it inside a `<Fragment>`, and add a `<Badge>` component after the text.
  - The `<Badge>` component should have the `googlesitekit-new-badge` CSS class, and a `label` prop with value of string `New` (translatable).
- In `assets/sass/components/key-metrics/_googlesitekit-key-metrics-widgets.scss`:
  - Add styles for `.googlesitekit-widget-area--mainDashboardKeyMetricsPrimary .googlesitekit-widget-area-header__title` so that the text and the badge are vertically aligned, and they have appropriate spacing between them. It should be according to the Figma designs.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Ensure the `userInput` feature flag is enabled so you can view Key Metrics widgets.
* Set up Site Kit with Analytics enabled and answer the Key Metrics questions in settings so the Key Metrics widgets appear on the Site Kit Dashboard.
* Note the "New" badge next to "Key Metrics" on the Site Kit Dashboard. It should match the Figma Mocks/screeenshot below:

<img width="1207" alt="CleanShot 2023-08-24 at 01 29 51" src="https://github.com/google/site-kit-wp/assets/90871/1523678c-7ba8-4154-badd-674e5e5c450a">

## Changelog entry

* Display a "New" badge on the Key Metrics widget.

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The "New" badge appears next to "Key Metrics" on the Site Kit Dashboard. 
- It match the Figma designs
- Tested when user survey questions are not answered
- Tested when user survey questions are answered to ensure 'Change metrics' link didn't have an impact on the UI.
- Tested on supported browsers 
- Tested on desktop and small viewports like mobile and tablet.  Also went through different responsive viewports. 

**Note:** In the QAB, it refers to the "New" badge when you complete the questions, but wanted to highlight that the badge also appears above the user input CTA, which I would expect to be correct. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/e0a80c52-efd9-4219-80f5-1f646ea26798)
![image](https://github.com/google/site-kit-wp/assets/73545194/78d5c248-fc60-4157-aee8-a02745a0c49c)
![image](https://github.com/google/site-kit-wp/assets/73545194/f33d29ba-55d7-4419-9f4c-ac24e1d8f5e1)
![image](https://github.com/google/site-kit-wp/assets/73545194/dbf7be36-9336-42cb-a6ad-8f5ba0894260)
![image](https://github.com/google/site-kit-wp/assets/73545194/3c9f7fb6-bffd-43fd-9e79-310a2b052860)
![image](https://github.com/google/site-kit-wp/assets/73545194/e2c27082-d03f-490c-9969-099e362f888d)
![image](https://github.com/google/site-kit-wp/assets/73545194/6734e221-15b3-4096-8c4f-6eb3e1ac18ba)

</details>
