### ISSUE TITLE
"Most popular products" should fall back to "Most popular content" when WooCommerce is disabled

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7377]
## Bug Description

When WooCommerce is disabled, the site ceases to have a "product post-type". In this scenario, the "Most popular products" widget tile should be replaced with the "Most popular content" widget tile. As mentioned in the [comment](https://github.com/google/site-kit-wp/issues/6249#issuecomment-1655314396) on #6249, when the site has products this worked as expected, but when the site doesn't have any products the tile still appears when you disable WooCommerce.

## Steps to reproduce

1. Enable the `userInput` feature flag on a site with an active WooCommerce installation. 
2. Do not create any products on the site.
3. Disable WooCommerce.

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by wpdarren** [comment]
@jimmymadon When WooCommerce is disabled, and no products exist then the `Most popular content by page views` tile appears. So, this does not appear to be an issue anymore and can be closed.
