### ISSUE TITLE
Update AdSense connect CTA widget for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7385]
## Feature Description

The button to "Connect now" on the dashboard's AdSense connect CTA does not have a spinner while in progress like other similar buttons.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The primary CTA of the `AdSenseConnectCTA` component should be a primary button with a spinner that spins while the underlying request is in progress, or the page is navigating to the appropriate URL to setup/complete-setup.

## Implementation Brief

- In `assets/js/modules/adsense/components/common/AdSenseConnectCTA/index.js`:
  - Create a new variable that checks if the component is in the process of connecting AdSense, e.g. `isConnectingAdSense`. It should use the `useSelect` hook and return `true` if any of the following conditions are met:
    - `CORE_MODULES` `isFetchingSetModuleActivation` selector call returns `true` with `adsense` & `true` as parameters.
    - `CORE_LOCATION` `isNavigatingTo` selector call returns `true` with `adminReauthURL` as the parameter.
  - Replace the usage of `Button` components with `SpinnerButton`. Add an `isSaving` prop to both the `SpinnerButton` component usages and pass the new `isConnectingAdSense` variable as value.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

1. Disconnect AdSense
2. Go to Site Kit Dashboard and scroll to the "Connect service AdSense" section.
3. Click on the "Connect now" button and verify it transitions into a loading state with the loading spinner.
4. Don't complete the AdSense setup, but go back to the Site Kit dashboard and again scroll down to the "Connected service "AdSense" section.
5. Click on the "Complete Setup" button and verify it transitions into a loading state with the loading spinner.
6. Verify the AdSense setup works as expected.

## Changelog entry

* Add a loading state to the AdSense Connect CTA buttons.

**Comment by parthrc** [comment]
hey @aaemnnosttv can I work on this?

**Comment by bethanylang** [comment]
Hi @parthrc, we always welcome contributions! Please see our [engineering guidelines here](https://github.com/google/site-kit-wp/wiki/Engineering) for more details. Feel free to submit a PR and we can take a look. Thanks!

**Comment by tofumatt** [comment]
I've added an estimate (I think this one is a "7"), but otherwise looks good. 🙂 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified spinning loader is now showing when user click on  "Connect now" button and on  "Complete Setup" button. 
- Verified AdSense setup is working fine.

<details>


https://github.com/google/site-kit-wp/assets/94359491/d33a3ba5-8cf7-4aa8-b93e-5c3e53a966cf

</details>
