### ISSUE TITLE
Hide Key Metrics Setup CTA banner when widget is setup by another Admin or on View Only Dashboard

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7386]
## Bug Description

If Admin1 answers the User Input questionnaire, the Key Metrics widget is considered set-up “site wide” for all other users of the site. The answer to the first question is stored “site-wide”. However, we decided in the design doc that “any other authenticated admin, who has not taken the User Input questionnaire, will be shown the [Setup CTA](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.kgse0j7btyc2) to take the questionnaire. If they dismiss it, the same [Dismissal flow](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.snxtf0ab56zj) will apply.” This means that if Admin2 logs in, they will see both, the Setup Banner CTA and the Key Metric widget tiles as in the attached screenshot which is not good UX! I understand the idea was to get all authenticated admins of the site to answer the questionnaire and we did conclude that if another admin changes the answer to question 1, the Key Metric tiles will change for all users of the site who have not picked their own metrics. But we probably want to think more about the UX/UI here and the flow. We would have to change the banner to say something like “Another admin has already answered questions on your site goals but you can review them…etc”

## Steps to reproduce

1. Login as admin1 and setup the Key Metrics widget by answering the user input questionnaire.
2. Verify that the Key Metric widget is showing some key metric widget tiles for admin1.
3. Now login as admin2. Both the Setup Banner CTA and the widget tiles are displayed.

## Screenshots

<img width="1389" alt="Screenshot 2023-07-21 at 11 05 15" src="https://github.com/google/site-kit-wp/assets/1721319/54d3ac81-368a-4356-8dae-037823fe8ab3">

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Note: This issue was split out as an easier fix from #7346 which plans to further implement an additional tooltip to the "Change Metrics" link.

* The Key Metric's Setup CTA Banner should be hidden for all users once the Key Metrics widget has been successfully set up. This is regardless of whether any admin has answered the questionnaire or not, i.e. the metrics could have been "user-picked" by an admin without answering the questionnaire.
* The Key Metrics Setup Banner CTA should not be displayed for non-authenticated admins (i.e. on the View Only dashboard. The Banner should never be shown regardless if the KM widget has been set up or not.

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by aaemnnosttv** [comment]
Closing in favor of #7349 which has been updated to address the AC here as well.
