### ISSUE TITLE
1.106.0 conflict with WPML

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7389]
## Bug Description

As [reported in the support forums](https://wordpress.org/support/topic/after-upgrade-issue-with-wpml/page/2/), some WPML users are unable to access their WP admin or encounter fatal errors after upgrading to Site Kit 1.106.0.  

One workaround that seemed to work for [one user](https://wordpress.org/support/topic/woocommerce-logs-fatal-errors/) was the following:
1. Navigate to "WPML > Settings > Post Types” and then set the post type Products to “_Translatable – only show translated items_“. 
2. Save this update 
3. Update to Site Kit 1.106.0 once more

For impacted users who may be severely impacted with the above workaround not resolving this issue, you can install [Site Kit 1.105.0](https://downloads.wordpress.org/plugin/google-site-kit.1.105.0.zip) where this should no longer occur. If you're having trouble deactivating and deleting Site Kit 1.106.0 please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post). 

```
Error Details
=============
An error of type E_ERROR was caused in line 3937 of the file /srv/htdocs/wp-content/plugins/sitepress-multilingual-cms/sitepress.class.php. Error message: Uncaught TypeError: Illegal offset type in isset or empty in /srv/htdocs/wp-content/plugins/sitepress-multilingual-cms/sitepress.class.php:3937
Stack trace:
#0 /srv/htdocs/wp-content/plugins/sitepress-multilingual-cms/classes/translations/class-wpml-post-element.php(54): SitePress->is_display_as_translated_post_type(Object(WP_Error))
#1 /srv/htdocs/wp-content/plugins/sitepress-multilingual-cms/classes/url-handling/wpml-url-filters.class.php(445): WPML_Post_Element->is_display_as_translated()
#2 /srv/htdocs/wp-content/plugins/sitepress-multilingual-cms/classes/url-handling/wpml-url-filters.class.php(238): WPML_URL_Filters->is_display_as_translated_mode(Object(WPML_Post_Element))
#3 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(310): WPML_URL_Filters->permalink_filter('https://XXX...', Object(WP_Post))
#4 /wordpress/core/6.2.2/wp-includes/plugin.php(205): WP_Hook->apply_filters('https://XXX...', Array)
#5 /wordpress/core/6.2.2/wp-includes/link-template.php(371): apply_filters('post_type_link', 'https://XXX...', Object(WP_Post), false, false)
#6 /wordpress/core/6.2.2/wp-includes/link-template.php(201): get_post_permalink(Object(WP_Post), false, false)
#7 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1099): get_permalink(Object(WP_Post))
#8 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(728): Google\Site_Kit\Core\Assets\Assets->get_product_base_paths()
#9 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(357): Google\Site_Kit\Core\Assets\Assets->get_inline_base_data()
#10 [internal function]: Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}('googlesitekit-b...')
#11 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Script_Data.php(51): call_user_func(Object(Closure), 'googlesitekit-b...')
#12 [internal function]: Google\Site_Kit\Core\Assets\Script_Data->Google\Site_Kit\Core\Assets\{closure}('googlesitekit-b...')
#13 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Asset.php(129): call_user_func(Object(Closure), 'googlesitekit-b...')
#14 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1017): Google\Site_Kit\Core\Assets\Asset->before_print()
#15 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#16 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#17 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#18 /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(156): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks(Object(WP_Scripts), Array)
#19 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}('')
#20 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#21 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#22 /wordpress/core/6.2.2/wp-admin/admin-header.php(146): do_action('admin_print_scr...')
#23 /wordpress/core/6.2.2/wp-admin/index.php(137): require_once('/wordpress/core...')
#24 {main}

  thrown
```

We [performed some internal testing](https://app.asana.com/0/1185360131189553/1205084891871251/f) on this and we were able to initially encounter errors, which required some database changes. After doing so we didn't encounter any errors specifically between Site Kit and WPML although we do see some PHP warnings relating to WPML (only with PHP 8.2.8 and not older versions)

<details><summary>Console errors with error reporting (and display) enabled, with only WPML active and SK disabled</summary>

```
Deprecated: Creation of dynamic property Whip_RequirementsChecker::$configuration is deprecated in /var/www/vhosts/plastiskip.com/httpdocs/wp-content/plugins/sitepress-multilingual-cms/vendor/yoast/whip/src/Whip_RequirementsChecker.php on line 37

Deprecated: Creation of dynamic property Whip_RequirementsChecker::$messageManager is deprecated in /var/www/vhosts/plastiskip.com/httpdocs/wp-content/plugins/sitepress-multilingual-cms/vendor/yoast/whip/src/Whip_RequirementsChecker.php on line 38
```
![image](https://github.com/google/site-kit-wp/assets/41326532/f3cbbad4-da38-40a9-9d6d-7df90219fc07)

</details>

<details><summary>Notes from team discussion</summary>

> Currently, we create a fake product and try to get a permalink for it. It works fine on sites where there is nothing else that tries to modify the permalink.
> In the reported site, WPLM tries to create a localised version of the permalink for non existing product and fails.
> What we can do on our side:
> Remove the current approach of finding the base path for products
> Implement the new approach that will query one random product from the database and use it to detect the product base path
> Found path will be cached for X minutes (probably something between 1-5 mins) to avoid querying the database for every request.
> 

</details>

<details><summary>Second stack trace</summary>

```
Stack trace:
#0 /opt/bitnami/wordpress/wp-content/plugins/sitepress-multilingual-cms/classes/translations/class-wpml-post-element.php(54): SitePress->is_display_as_translated_post_type()
#1 /opt/bitnami/wordpress/wp-content/plugins/sitepress-multilingual-cms/classes/url-handling/wpml-url-filters.class.php(445): WPML_Post_Element->is_display_as_translated()
#2 /opt/bitnami/wordpress/wp-content/plugins/sitepress-multilingual-cms/classes/url-handling/wpml-url-filters.class.php(238): WPML_URL_Filters->is_display_as_translated_mode()
#3 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(310): WPML_URL_Filters->permalink_filter()
#4 /opt/bitnami/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 /opt/bitnami/wordpress/wp-includes/link-template.php(371): apply_filters()
#6 /opt/bitnami/wordpress/wp-includes/link-template.php(201): get_post_permalink()
#7 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1099): get_permalink()
#8 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(728): Google\Site_Kit\Core\Assets\Assets->get_product_base_paths()
#9 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(357): Google\Site_Kit\Core\Assets\Assets->get_inline_base_data()
#10 [internal function]: Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}()
#11 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Script_Data.php(51): call_user_func()
#12 [internal function]: Google\Site_Kit\Core\Assets\Script_Data->Google\Site_Kit\Core\Assets\{closure}()
#13 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Asset.php(129): call_user_func()
#14 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1017): Google\Site_Kit\Core\Assets\Asset->before_print()
#15 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#16 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#17 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#18 /opt/bitnami/wordpress/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(156): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#19 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(308): Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}()
#20 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#21 /opt/bitnami/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#22 /opt/bitnami/wordpress/wp-admin/admin-header.php(146): do_action()
#23 /opt/bitnami/wordpress/wp-admin/index.php(137): require_once('...')
#24 {main}
 thrown in /opt/bitnami/wordpress/wp-content/plugins/sitepress-multilingual-cms/sitepress.class.php on line 3937
```

</details>

## Steps to reproduce

1. Install Site Kit 1.105.0
2. Install, set up and configure WPML
3. Update Site Kit to version 1.106.0

_(note that during testing I couldn't consistently reproduce this on different sites)_

## Related support topics
- https://wordpress.org/support/topic/woocommerce-logs-fatal-errors/ | **Resolved** - workaround as suggested above | No SH info
- https://wordpress.org/support/topic/after-upgrade-issue-with-wpml/ | **Open** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNit6GZmNgn_hv3dd9rbtBidLHferPM7cLJw97P10VpQpzhRqnCEhTaEfZ-SFZ4ATnc)
 
## Additional Context

 - PHP 8.2.8
 - One user [in a topic](https://wordpress.org/support/topic/after-upgrade-issue-with-wpml/) stated they can't login to wp-admin due to this error
- There are similar errors reported of this in the WPML support forums (independently of SK). [Example query](https://wpml.org/forums/topic/illegal-offset-type-in-isset-or-empty-in-wp-content-plugins-sitepres/)
- WPML [do mention they are also investigating](https://wpml.org/errata/site-kit-by-google-uncaught-typeerror-illegal-offset-type-in-isset-or-empty-in/)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The computation of product base paths should only happen when the `userInput` feature is enabled
	* If not enabled, this should be an empty array and no further processing should be done

## Implementation Brief

* Return early with an empty array from `Assets::get_product_base_paths` if `userInput` is not enabled as the first check

### Test Coverage

* Update tests for product base paths in `AssetsTest` accordingly

## QA Brief

* The underlying behavior which raised this error should no longer happen (with or without) `userInput` enabled
* The error can be observed with the latest version of WPML (4.6.4) with minimal configuration, so long as SK is connected and WooCommerce is also installed
	* I noticed it in Query Monitor just by visiting a single post

## Changelog entry

* Fix a potential PHP error in WPML introduced in `1.106.0` on a site with a `product` post type.

**Comment by bethanylang** [comment]
@aaemnnosttv Here was @eugene-manuilov's suggestion on a fix via Slack:

> What we can do on our side:
> Remove the current approach of finding the base path for products
> Implement the new approach that will query one random product from the database and use it to detect the product base path
> Found path will be cached for X minutes (probably something between 1-5 mins) to avoid querying the database for every request.

**Comment by bethanylang** [comment]
Thanks, @robertstaddon! As you can see, we're working to address this on our side, but WPML has also notified us that they're planning to release a fix in their own update next week. You can follow along with them here: https://wpml.org/errata/site-kit-by-google-uncaught-typeerror-illegal-offset-type-in-isset-or-empty-in/.

**Comment by aaemnnosttv** [comment]
Thanks @strategio, that's great to hear 👍 We'll use this issue to fix the problem people are experiencing now and we'll iterate on our implementation to be more robust in another as this is part of a future feature that isn't available yet.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- I was able to recreate the issue on PHP 8.2 and unable to setup Site Kit or access the dashboard with WPML, WooCommerce and Site Kit 1.106.0 installed and setup. 
- When I switched to the develop branch the issues no longer exist.  I was able to setup Site Kit and also access the dashboard. I tested this with the `Userinput` feature flag enabled and disabled.  There are some PHP errors on 8.2 but not linked to this issue. We have reported these [here](https://github.com/google/site-kit-wp/issues/7147).  I also ran through on PHP 7.4 just for peace of mind.

**Comment by robertstaddon** [comment]
Nice work! Thank you all.
