### ISSUE TITLE
Enhance accuracy of product path-based reports

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7390]
## Feature Description

In #6249 we introduced the "Most popular products by pageviews" key metrics widget, which required the addition of providing a list of "product base paths" to the client which is essentially a list of URL prefixes that products have in common in order to identify products by URL for reporting.

The current implementation works but has room for improvement to allow for more flexibility and ultimately accuracy. In particular, the prefixes should support placeholders which effectively become wildcards where there could be an unknown number of possibilities filling a segment of the base path. E.g. `shop/%product_cat%/product/`.

This also implies that it is not practical to rely on a single permalink to get the base path for individual products in general as the concrete URL can vary from product to product based on dynamic components as shown above.

Allowing for wildcards in the base paths also means that we'd need to be able to use more flexible filtering. String filter expressions support [full and partial regular expression matching](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/FilterExpression#matchtype) so this should be doable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Product base paths should be based on permalink structure, including any dynamic placeholders
* Any placeholders (aka "rewrite tags") should be replaced with their respective regular expressions
	* i.e. `%year%` -> `([0-9]{4})`. See `WP_Rewrite` (particularly https://github.com/WordPress/WordPress/blob/50274fbc2b1c5e6e0a43ea68d2f767ec2f0b86e8/wp-includes/class-wp-rewrite.php#L962-L963)
* Product base paths should then be a list of regular expressions which should be used when querying by product paths, that the page path in Analytics should match one of the given expression(s)
* The Popular Products widget should be updated to use `PARTIAL_REGEXP` in the dimension filter for product base paths in the report.

## Implementation Brief

* Update the `get_product_base_paths` method of the `Assets` class:
  * Replace rewrite tags with actual regular expressions in the product base path for the `product` post type.
    * In order to do it, use the `str_replace` function with `$wp_rewrite->rewritecode` as the search parameter and `$wp_rewrite->rewritereplace` as the replace parameter.
  * Also add the caret character (`^`) at the beginning of the rewrite rule if it doesn't exist there yet, to ensure that that regular expression matches URLs from the beginning.
* Update the `PopularProductsWidget` component to use `PARTIAL_REGEXP` as the match type for the dimension filter.

### Test Coverage

* Update existing tests if any is failing.

## QA Brief

- Setup Site Kit on a site with WooCommerce enabled and some product page view events in Analytics.
- Enable the `userInput` feature flag and setup Key Metrics, answering "Sell products or services" for the first question.
- Perform a regression test: Verify that the "Most popular products by pageviews" widget appears with the expected data.
- Now, update the product permalink structure to include some permalink variables, e.g.:
![image](https://github.com/google/site-kit-wp/assets/18395600/29d7785f-3677-44aa-8fb8-3962b73ac3a9)
- Visit some product pages and wait for the next day so the data will appear in Site Kit.
- Verify that the new data appears "Most popular products by pageviews" widget.

## Changelog entry

* Improve accuracy of "Most popular products by pageviews" widget

**Comment by eugene-manuilov** [comment]
Added one point to AC to update the Popular Products widget to use the new match type for the filter. AC ✔️

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov , just a few questions

- Do we need to worry about escaping regex characters in the parts of the permalink structure that aren't tags?
- In using `PARTIAL_REGEXP`, should we update the paths to include a leading `^` to ensure that it only matches from the beginning of the string?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv 

> * Do we need to worry about escaping regex characters in the parts of the permalink structure that aren't tags?

As far as I see it, we don't need to escape regex characters, but we will know for sure when we work on implementation.

> * In using `PARTIAL_REGEXP`, should we update the paths to include a leading `^` to ensure that it only matches from the beginning of the string?

It's a good concern, but unfortunately, i don't think it is right to manually add `^` to the beginning of the regex. Even more, I think that we should remove adding the home URL to the permalink structure because it may not work in some circumstances as expected.

https://github.com/google/site-kit-wp/blob/bbb3e1fbbf1083cd65d9e8b39b695704fe3369a4/includes/Core/Assets/Assets.php#L1093-L1094

Updated IB to remove these lines ^

**Comment by aaemnnosttv** [comment]
> It's a good concern, but unfortunately, i don't think it is right to manually add `^` to the beginning of the regex. Even more, I think that we should remove adding the home URL to the permalink structure because it may not work in some circumstances as expected.

Thanks @eugene-manuilov – would you please elaborate on your reasoning? Permalink structures should always be relative to the home URL but in GA the page path will always be relative to the root of the domain. Given the ability for these patterns to be quite greedy already, I think we should at least make sure they always match at the beginning.

There will probably always be some degree of inaccuracy with this method, but we should aim to get the best accuracy for the majority of cases. Loosening the matching could potentially reduce the accuracy in a substantial way.

In the future, I think using a custom dimension for post type would be more appropriate than using matching, but that isn't an option just yet.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv, looks like my assumptions were incorrect. WordPress does add `^` at the beginning of each rewrite rule: https://github.com/WordPress/wordpress-develop/blob/6e4364e49ecd95dcbca5185d55a9c5050d088490/src/wp-includes/class-wp.php#L233-L234. I updated IB, thanks for your help.

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov – I've bumped the estimate to account for some extra testing/QA time but otherwise LGTM!

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

**Verified:**

- Performed a regression test: the `Most popular products by pageviews` widget appears with the expected data. I tested this with no products to make sure the notification appears saying that there is no product data.  I also included the permalink used for previous testing on this tile `/en/why-%product%/` 

- Created a new product and sent some traffic to it and will see if the metrics appear in the tile. Included the permalink `/product/%year%/%monthnum%/%category%/`

Test URL https://ng-echidna-foli.instawp.xyz/product/2023/08/uncategorized/test-product/

Will report back in 24 hours. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/2a4da16e-fc3a-4a1b-850c-c3b7b4d3cf18)
![image](https://github.com/google/site-kit-wp/assets/73545194/4f5b1058-5dd1-4a14-9bbd-f41f9376e1ba)

</details>
