### ISSUE TITLE
Improve co-location of Dashboard View Indicator & widget area CTA

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7392]
## Feature Description

As a part of #6259, we're adding a `Change Metrics` CTA link in the widget area for Key Metrics. We also have a Dashboard View Indicator added as a part of the `GA4 Reporting` feature epic which is shown towards the right-end of the first widget area in the SK dashboard. With both of the elements in a similar location, there occurs a slight overlap between the two.

![image](https://github.com/google/site-kit-wp/assets/20284937/7c54322e-6667-4954-b762-80ebfd3bce9c)

This issue is opened with the aim to improve this co-location so that they do not overlap.

This issue can also be used to address [the question](https://10up.slack.com/archives/C01CA828ZPZ/p1689625655098549) @aaemnnosttv raised internally about showing the Dashboard View Indicator unless both UA & GA4 are connected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by nfmohit** [comment]
Hi @sigal-teller! 👋 We'd love to have your feedback here regarding the two concerns mentioned in this issue. Thank you!

**Comment by bethanylang** [comment]
Per [discussion in Slack](https://10up.slack.com/archives/C01CA828ZPZ/p1691044160625359), UA will be removed from Site Kit by the time that KMW is released, which means this indicator will also no longer display, so the overlap shouldn't be an issue. Closing this ticket.
