### ISSUE TITLE
Unable to receive access token because of an empty authorization code.

### ISSUE THREAD

**Issue by canoas** [google/site-kit-wp#74]
**Describe the bug**
I'm using a WordPress network installation and deployed the Google SiteKit plugin in a single site. OAuth app was configured for both URLs (wordpress.network.com/site and blog.site.com) and the first step of authentication and consent is almost complete but the final postback just presents this message: "Unable to receive access token because of an empty authorization code."

**To Reproduce**
Steps to reproduce the behaviour (in my case):
1. Go to Dashboard
2. Click on Left Menu "Site Kit"
3. Click on Left Menu "Sign in with Google"
4. Select user, ok
5. Consent permissions
6. Allow

**Expected behavior**
Would like to see the Site Kit Dashboard

**System Information (please complete the following information):**
 - PHP Version: 7.2.7
 - WordPress: 5.2.2 - Network Install
 - OS: Windows Server 2016
 - Browser chrome
 - Plugin Version 1.0.0-beta.1
 - Device: Windows 10

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by jamesozzie** [comment]
@canoas Thanks for raising the issue. The plugin does not provide multi site network installation at this point. You can however use Site Kit on the site level (if you have enabled plugin installs on site level). You would have to create separate OAuth configurations for each site. Let me know if that works for you.

**Comment by canoas** [comment]
@jamesozzie We did install site only.
also deleted the first Oauth app from google console and recreated a new one using only the dashboard url. We still face the same error.
can we find more "debug" info from the current process/plugin?
thank you

**Comment by jamesozzie** [comment]
@canoas I will try and replicate the same issue. In the meantime you can open Chrome dev tools and under the network tab click on the XHR option and start recording. If you can share the responses from there, along with and console errors.

**Comment by canoas** [comment]
GET /dvsblog?oauth2callback=1&code=4/dQE2n9B3IH-UKwS-kQTnIqVlkP-auKUVE8Zlfm7z3piCxg05Paw1-zENDq7UYdp1YTQzztDTP_SSndlJPceCAkE&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/webmasters%20https://www.googleapis.com/auth/siteverification&authuser=0&session_state=928661e4c2d336132837f45411b028d5d800f5ea..1911&prompt=consent HTTP/1.1
Host: wordpress.cloud.facilit.us
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Referer: https://accounts.google.com/signin/oauth/consentsummary?authuser=0&part=AJi8hAMJ8CE7NB1Hui94nbNoFH1AUfpdhAfj5qM5NDRSzV4FXKn-fgB7ZNAz-2G3VRfxlr1Hfq0EXrZULNLuIXnv14wFYg3lbMdsNimsWWzAj32GReORqPLeA3ZZDN0xzyav3vFID9Y7Pt7nP8YpLUwz9Pk0eeSIHpfCV9tGuZ6Qqbuv_NeLSwy40F9-Mzw4Om_7ZHgJjfHMsflScUD_ZiLpVF1Ezzr68WUl7nFLKPIc9Mac9Pj1HdFQgcbccFOK8QZaqscZSwUAabNC6n0H6BvH_WtvrHU8yloZX1yW41vVJzW_jhjJKGGQXrYWtODqSjmf1tG1-yeydNbruA9TAJq5sgFe1Afq61ngMim9iTOAN7L2NHbBGsWJeS47eGID4eAMgudNpN3fOkbIqtHThZ9c5IGDG43CY_jUK_94eHiYh3fD6E2LYgWJGUat8pJa1XPtQcxBj_R9nyoQdRSKxoJmiDDps7n8cbxX4AtkCBvASJlPEXfY9CUZUZT0HsKvULDN3sxTV9KNTwqCTu1VnDxsSMy3oEZLp2pKb6riQgj5OfAIDb3CZMKx1cApMoZWLE0zI35zeUn-CFZVMcc_WEv4Znk39OY5ldANblfSynS6oMTy8F6vlVwhGaKvkm_ZRGViHK1rXxM_utluLe8_Gux_9mkrtJWPBZCHcikAxR965Yo3B--lEEBOUpG7Lm5uQXOwdd3gpUM__XU-JlX77_1rrAhrdliv1pUXPom5hU2evUaq32h1EiqT_7rYSFT0ZTkSL-Fn2u-IDiPVwa1HwhU9L-c-139SdndSMIDYMohn8BGvv0YJ1Lqo8gzJJtFCLmKit3luxAjyssZHC3Xaqy-Ig0BCwOWq0lDpEIbSFyuRIpSefGQkGpy4_mVYiU_ZZ5DAdhI1Zt3BGIsOUPKRbIiOsXyeJ61JtcrfcU5MuoT4U8C8Ry7XlCVsiXRRh_POPlaCTOQH4a7BBIe8WGXhMozaQPu92AJZyn4YTeda1L8MalpkKIq7aCuWDb4h59nVfU7P7Oc-8a7WoOFmNtp8luTg9h8PEII9ww&as=VtJ7HthXScZKjFq9HHz8mQ&rapt=AEjHL4N7qoGZkPrbrFh1pGoYXkBKay_QcqL18_mhU0ILHAuWsY6ziQsJUZDR3Ku04Jn6jRF7-ZnIt7eFX2_K-rIWMOewqRw__A&approvedScope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,pt-PT;q=0.8,pt;q=0.7,en-GB;q=0.6,es;q=0.5,ca;q=0.4,fr;q=0.3
Cookie: wordpress_test_cookie=WP+Cookie+check; wordpress_sec_0a082ac10d5e9c72572c80dd922b44e2=canoas%7C..b1; wordpress_0a082ac10d5e9c72572c80dd922b44e2=canoas%7C...b9; wordpress_logged_in_0a082ac10d5e9c72572c80dd922b44e2=canoas%7C...18c; wp-health-check-disable-plugins=a221abfd35bbd6ac73cc400503a184a3; wp-settings-1=mfold%3Do%26libraryContent%3Dbrowse; wp-settings-time-1=1561574912; _ga=GA1.2.560926.1561626739; _gid=GA1.2.341714612.1561626739; _gat_gtag_UA_130569087_3=1

**Comment by jamesozzie** [comment]
@canoas Thanks for the update. I am trying to replicate the same issue but it's working for me when setting up on individual sites within a multisite. 

Are you following OAuth process step from within the main site or by logging into one of the subdomain sites (via the standard plugin dashboard on that individual sites)?

**Comment by jamesozzie** [comment]
@canoas Did you manage to setup Site Kit using the individual site install as opposed to admin install from the main site?

**Comment by jamesozzie** [comment]
@canoas I will close this issue now, but feel free to reopen if you are unable to install on individual sites. Multi site network installs are on the roadmap for future releases, so hopefully you won't have to wait too long.

**Comment by official-tisao** [comment]
Upgrade/downgrade your php version from 7.2 to 7.1 or 7.0 to fix the issue
