### ISSUE TITLE
Impossible to sign in since the last update Version 1.0.0-rc.2

### ISSUE THREAD

**Issue by Nzaime** [google/site-kit-wp#740]
## Bug Description

I did the last update today (Version 1.0.0-rc.2) and my Google site kit plugin went off, it disconnected my Google account (eveything has disapeared, google analytics, search console etc...). The dashboard is blank, nothing showing. 
I received this error report : https://ibb.co/mhXDYWt
I tried to disable the plugin and reactivate it, and now if i try to link my Google account
i have this error : https://ibb.co/6YrVdf3

Screenshots : 
#1 error : https://ibb.co/mhXDYWt
#2 error : https://ibb.co/6YrVdf3

Additional Context : 
Wordpress 5.2.4 
Google site kit Version 1.0.0-rc.2 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@Nzaime Can you please attempt the steps below in order to get Site Kit connected:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)

If the above fails to resolve your issue can you please share the following:
- Any [console errors](https://i.imgur.com/KyLAzgH.png) that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by SiwelKe** [comment]
Installing the plugin in incognito worked for me

**Comment by Nzaime** [comment]
@jamesozzie Dashboard is showing in incognito mode, but the next step failed again. 
i still have this error : https://ibb.co/sFGNg3p

- Console errors : https://ibb.co/rQRvXL5
- Wordpress Site Health Information :  3 screenshots 
1. https://ibb.co/KXPyCWc
2. https://ibb.co/Czy8Rzc
3. https://ibb.co/6HrRTL0
- My security plugin is HideMyWP, and i have several lines in my code to protect this website (hiding him from scan tool like CMSeeK)

**Comment by antoniomanco** [comment]
Hello, the latest Google Site-Kit WP update has a serious compatibility issue with the WP-Optimize 3.0.13 plugin that is widely used to optimize high traffic sites. Not only is it about installing or updating Google Site Kit, but both plugins can't work well together. Is there any way to fix this? Thank you

**Comment by jamesozzie** [comment]
@Nzaime It's possible that your hosting provider is blocking incoming REST API requests, which is resulting in the error message you are encountering. You can check with your hosting provider?  

@antoniomanco Can you share any console errors, or raise a new issue with additional context and we can hopefully assist. I'll check the WP Optimize plugin from my side also.

**Comment by Nzaime** [comment]
@jamesozzie Thanks James, it wasn't about my Hosting provider, but when you wrote "Rest API" i remembered that i had put this in my child theme's "functions.php"  to hide my Wordpress : 
// ******************** Crunchify Tips - Clean up WordPress Header START ********************** //
function crunchify_remove_version() {
	return '';
}
add_filter('the_generator', 'crunchify_remove_version');
 
remove_action('wp_head', 'rest_output_link_wp_head', 10);
remove_action('wp_head', 'wp_oembed_add_discovery_links', 10);
remove_action('template_redirect', 'rest_output_link_header', 11, 0);
 
remove_action ('wp_head', 'rsd_link');
remove_action( 'wp_head', 'wlwmanifest_link');
remove_action( 'wp_head', 'wp_shortlink_wp_head');
 
function crunchify_cleanup_query_string( $src ){ 
	$parts = explode( '?', $src ); 
	return $parts[0]; 
} 
add_filter( 'script_loader_src', 'crunchify_cleanup_query_string', 15, 1 ); 
add_filter( 'style_loader_src', 'crunchify_cleanup_query_string', 15, 1 );
// ******************** Clean up WordPress Header END ********************** //

When i removed this part, everything went fine.  Thanks for your help ! :)

**Comment by jamesozzie** [comment]
@Nzaime Very useful to know, thanks for the update @Nzaime, glad you were able to resolve.
