### ISSUE TITLE
1.106.0 breaks compatibility with WPML

### ISSUE THREAD

**Issue by yescit** [google/site-kit-wp#7408]
The new version breaks compatibility with WPML for me, and causes a sitewide crash, previous version (1.105.0) worked just fine
here is my error log:

[07-Aug-2023 10:13:19 UTC] PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /home/musch815/public_html/wp-content/plugins/sitepress-multilingual-cms/sitepress.class.php:3937
Stack trace:
#0 /home/musch815/public_html/wp-content/plugins/sitepress-multilingual-cms/classes/translations/class-wpml-post-element.php(54): SitePress->is_display_as_translated_post_type()
#1 /home/musch815/public_html/wp-content/plugins/sitepress-multilingual-cms/classes/url-handling/wpml-url-filters.class.php(445): WPML_Post_Element->is_display_as_translated()
#2 /home/musch815/public_html/wp-content/plugins/sitepress-multilingual-cms/classes/url-handling/wpml-url-filters.class.php(238): WPML_URL_Filters->is_display_as_translated_mode()
#3 /home/musch815/public_html/wp-includes/class-wp-hook.php(310): WPML_URL_Filters->permalink_filter()
#4 /home/musch815/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 /home/musch815/public_html/wp-includes/link-template.php(371): apply_filters()
#6 /home/musch815/public_html/wp-includes/link-template.php(201): get_post_permalink()
#7 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1099): get_permalink()
#8 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(728): Google\Site_Kit\Core\Assets\Assets->get_product_base_paths()
#9 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(357): Google\Site_Kit\Core\Assets\Assets->get_inline_base_data()
#10 [internal function]: Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}()
#11 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Script_Data.php(51): call_user_func()
#12 [internal function]: Google\Site_Kit\Core\Assets\Script_Data->Google\Site_Kit\Core\Assets\{closure}()
#13 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Asset.php(129): call_user_func()
#14 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1017): Google\Site_Kit\Core\Assets\Asset->before_print()
#15 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#16 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#17 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(1026): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#18 /home/musch815/public_html/wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(156): Google\Site_Kit\Core\Assets\Assets->run_before_print_callbacks()
#19 /home/musch815/public_html/wp-includes/class-wp-hook.php(308): Google\Site_Kit\Core\Assets\Assets->Google\Site_Kit\Core\Assets\{closure}()
#20 /home/musch815/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#21 /home/musch815/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#22 /home/musch815/public_html/wp-includes/script-loader.php(2146): do_action()
#23 /home/musch815/public_html/wp-includes/class-wp-hook.php(308): wp_print_head_scripts()
#24 /home/musch815/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#25 /home/musch815/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#26 /home/musch815/public_html/wp-includes/general-template.php(3049): do_action()
#27 /home/musch815/public_html/wp-content/themes/valeska/header.php(8): wp_head()
#28 /home/musch815/public_html/wp-includes/template.php(783): require_once('/home/musch815/...')
#29 /home/musch815/public_html/wp-includes/template.php(718): load_template()
#30 /home/musch815/public_html/wp-includes/general-template.php(48): locate_template()
#31 /home/musch815/public_html/wp-content/themes/valeska/page.php(3): get_header()
#32 /home/musch815/public_html/wp-includes/template-loader.php(106): include('/home/musch815/...')
#33 /home/musch815/public_html/wp-blog-header.php(19): require_once('/home/musch815/...')
#34 /home/musch815/public_html/index.php(17): require('/home/musch815/...')
#35 {main}
  thrown in /home/musch815/public_html/wp-content/plugins/sitepress-multilingual-cms/sitepress.class.php on line 3937

**Comment by jamesozzie** [comment]
Thanks for reaching out @yescit. We're aware of this error and we're working on an update to ensure these errors no longer occur (see https://github.com/google/site-kit-wp/issues/7389). WPML have also released an update to their plugin as per [this post on their website](https://wpml.org/errata/site-kit-by-google-uncaught-typeerror-illegal-offset-type-in-isset-or-empty-in/). If you're not using WPML 4.6.5, please upgrade to this latest version.  

Great that you managed to install Site Kit 1.105.0 in order to ensure normal functionality. You'll find out more on this by [visiting this post](https://wordpress.org/support/topic/conflict-between-wpml-4-6-4-and-site-kit-1-106-0/) over on the plugin support forums. 

I'll close this GitHub issue given https://github.com/google/site-kit-wp/issues/7389 is already being actioned.
