### ISSUE TITLE
Connect Analytics CTA widget shifts up when user clicks on 'Connect CTA' button. 

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7416]
## Steps to reproduce

1. Pick or tailor KMW metrics. 
2. Disconnect Analytics.
3. See Connect GA CTA on dashboard. 
4. Either "Scroll the page" further down OR reload the page with a Dashboard notification by appending the following link in the URL to your site: 
```/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=adsense```

5. Click on the Connect Analytics button within the Connect GA Key Metric CTA tile.
6. Observe that the page jumps to the beginning of the Key Metrics widget or the to the top of the page if there is a notification before it then redirects to the Analytics Setup page.

## Screenshots

https://github.com/google/site-kit-wp/assets/94359491/9542c6a6-78c9-45ea-ade9-73cd2178889f

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Clicking on the "Connect Analytics" link within the Key Metrics tile CTA should not cause movement on the page before loading the Analytics settings setup page. 
* The link should behave exactly like the "Complete Setup" CTA button in the GA4 All Traffic dashboard widget when GA4 is disconnected.

## Implementation Brief

In `assets/js/components/KeyMetrics/ConnectModuleCTATile.js`:

* Locate the `Link` component used for the "Connect %s" (Connect Analytics) link. This component should have an `href` prop with a value of `#`, which causes the page to jump to the top upon click.
* Remove the `href` prop with the value of `#`. This will prevent the default behavior of jumping to the top of the page.

### Test Coverage

* No new tests are required for this change.

## QA Brief

* Follow the steps to reproduce, and verify that clicking the CTA does not cause the page to scroll as per the AC.

## Changelog entry

* Improve behavior of Key Metrics "Connect Analytics" CTA.

**Comment by mohitwp** [comment]
Issue is not reproducible on latest develop branch. Closing this issue.

**Comment by mohitwp** [comment]
@jimmymadon 

I'm able to reproduce this issue on dev. It is happening in two cases-

1) If any dashboard is appearing on main dashboard.
2) If a portion of KMW banner is hidden then on clicking on 'Connect Analytics' button banner position will shift to display the whole banner.

See attached screencast and let me know if you require a huddle. 

https://github.com/google/site-kit-wp/assets/94359491/9542c6a6-78c9-45ea-ade9-73cd2178889f

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that on on the "Connect Analytics" link within the Key Metrics tile CTA should not cause movement on the page before loading the Analytics settings setup page.
- Verified that behave exactly like the "Complete Setup" CTA button in the GA4 All Traffic dashboard widget when GA4 is disconnected.

<details>


Uploading Recording #641.mp4…

</details>
