### ISSUE TITLE
Settings page component rerendering makes for poor UX and performance

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#742]
## Bug Description

The current React app rendered on the Settings page is currently highly-sensitive to rerendering the component's settings modules. This causes modules to dispatch API requests for data when mounted which happens just about anything changes on the page such as the active tab, or open state of any settings module on the Connected Services tab.

This contributes to poor UX (why should a module go into a loading state when another module opens?) and performance (each active module making repetitive API requests on unrelated changes) issues.

## Steps to reproduce

1. Set up Site Kit
1. Connect Analytics
1. Go to Settings
1. Expand Analytics settings
1. Expand Search Console settings
1. Notice Analytics goes into a loading state when any other tab is toggled

The issue is compounded the more active modules there are. E.g. if Analytics and Tag Manager are active, both of them will reload accounts anytime anything on the screen changes - even if they're not expanded.

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/67799577-487d9300-fa8e-11e9-9b0e-3bd8b22dd0fc.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Settings modules should not make any requests unless they are expanded (open)
* Only a single module to should be expanded at any given time (accordion)

## Implementation Brief

* Update `assets/js/components/settings/settings-module.js` to pass the `isOpen` state to the inner `FilteredModuleSettingsDetails`
* Update `assets/js/components/settings/settings-modules.js` `handleAccordion` to only allow for a single open module (only `...prevState.openModules` need be removed)
* Update modules that make data requests when mounted to only do so if they are:
  - `onSettingsPage && isOpen`
  - or `! onSettingsPage` (in setup context)

## Changelog entry

* Improve UX and fix performance issues with excessive re-rendering in the module settings screen.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> Update modules that make data requests when mounted to only do so if they are

Will that not cause issues with modules when they aren't open when they get mounted? When will they run that logic that is now no longer run?

**Comment by aaemnnosttv** [comment]
It should not because they are being remounted on every state change in the parent components (e.g. `openModules` in `SettingsModules`) which is the main reason these requests are happening so often in the first place.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

Tested with multiple settings and nothing (re-)rendered when it should not have. Only the relevant, open module rendered.

Additionally, only the open/active module made data requests, so analytics requests were not made in the background. Looks good! 👍

**Comment by marrrmarrr** [comment]
verified, lgtm
