### ISSUE TITLE
Unclickable links in KMW tiles on the view only dashboard

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7421]
## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
Closing in favor of taking care of this in #7400.
