### ISSUE TITLE
Render all widgets in the metrics selection list

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7425]
## Feature Description

We originally decided to not display metrics in the "Metrics selection panel" for tiles where the module is disconnected. There are some edge cases that were raised when testing this behaviour as described in [Q1 of this comment](https://github.com/google/site-kit-wp/issues/6258#issuecomment-1669236255). 

The exact case mentioned in the comment above would not occur since the Key Metrics Setup CTA Banner would not be displayed allowing users to pick their own metrics if GA4 is not connected. However, once the Key Metrics widget has been set up, then disconnecting GA4 will show the "Connect GA4" CTA tiles in the widget area. At this point, if a user decides to click on "Change Metrics", the list would only contain a single "Search Console" widget title and all widget titles for GA4 dependant tiles would be hidden. The user is not directly told why the list is "empty" all of a sudden (they could guess from the CTAs to connect GA4).

So it would be nice to still show users all the "possible" widget titles in the list, even those that they have already selected. But we should somehow convey that selecting these would not give you data in the tiles since the dependent module is disconnected.

The new metrics selection panel design from @sigal-teller (which includes direction on this issue) is [available in Figma here](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6116-12251&mode=design&t=WGzk8dhNYk8r603q-0).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Key Metrics selection panel, metrics whose modules are disconnected after the Key Metrics widget has been setup should not be hidden.
    * Note: For now, this only applies to GA4 metrics. SC cannot be disconnected for the dashboard to work and the AdSense related "Top Earning Content" widget will not be part of the initial KMW feature release.
* Such metrics should have some additional error text added to the list item as per this [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6127-32574&mode=design&t=L0N2qei8YwPHdhy8-0).
    * The message text should be: `Analytics is disconnected, no data to show` where Analytics is the name of the module.

## Implementation Brief

* Within `assets/js/googlesitekit/datastore/user/key-metrics.js`
    * Alter the `isKeyMetricAvailable` function:
        * Remove the conditional check based on whether the module is connected, i.e the line starting with `if ( ! module || ! module.connected ) {`, as the module connection logic will be moved into the `<Metrics>` component.
* Within the `<Metrics>` component at `assets/js/components/KeyMetrics/MetricsSelectionPanel/Metrics.js`
    * Within the return`.reduce`'er:
        * Add an additional check to ascertain whether the metric in questions module is connected.
        * If it is not, append a property of `isModuleConnected` (with a value of `false`) to the metric object, i,.e `KEY_METRICS_WIDGETS[ metric ].isModuleConnected = false;`
        * At the same time, forward the metrics module name to the metric object, something along the lines of `KEY_METRICS_WIDGETS[ metric ].moduleName = module.name;` (Where `module` is the module object relative to the metric within the reducer pointer.
    * Within the main `return` function of the `<Metrics>` component:
        * Expand the `isModuleConnected` and `moduleName` prop names within the current reference to `availableMetrics[ slug ];` and pass them as props to the final `<MetricItem>` component render.
* Within the `<MetricItem>` component at `assets/js/components/KeyMetrics/MetricsSelectionPanel/MetricItem.js`
    * Add the `isModuleConnected` and `moduleName` props to the current list of props, and add their PropTypes as `bool` and `string` respectively.
    * Within the `return` statement of the `<MetricItem>` component:
        * Check whether the module for said item is not connected using the `isModuleConnected` prop
        * If it is not (i.e `! isModuleConnected`) then render the applicable message (along with module name) as an element within the <MetricItem>` component.
* Within the SASS file at `assets/sass/components/key-metrics/_googlesitekit-km-selection-panel.scss`
    * Update the styles as necessary to correctly reference the Figma mocks. 

### Test Coverage

* Update the test at `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js`
    * Alter the `should only list metrics dependent on connected modules` scenario and instead ensure that all metric items render, regardless of whether the associated module is connected or not.
* Update VRT references if necessary 

## QA Brief

* Set up Key Metrics, ensuring that there is a mix of GA4 and other service metrics, i.e `Top performing keywords`, `Loyal visitors`, `New visitors` and `Top traffic source`.
* Ensure that all 4 metrics are displaying correctly
* Ensure that metrics can be changed within the metric selection panel
* Next, disconnect the Analytics 4 module entirely via `SK > Settings > Connected Services`
* Once disconnected, visit the SK main dashboard once again
* The KMW's attached to services other than GA4 should show, and the GA4 KMW's should be replaced by a single tile indicating that Analytics has been disconnected
* The metric selection panel (triggered via the `Change Metrics` CTA) should still trigger
* Within said selection panel, GA4 metrics should still be visible and selectable
* GA4 metric items in the list should have a clear notice text within them stating that the GA4 module is disconnected and that there is no data to show, as per the Figma attached to the issue
* Said GA4 metrics should still be selectable and should show (if chosen) once the GA4 service is reconnected

## Changelog entry

* Change behaviour/visibility of Key Metric Widgets when their modules are disconnected.

**Comment by bethanylang** [comment]
Since Sigal is OOO for the next few weeks and this is a launch blocker, asking @marrrmarrr to please take a look at this instead.

**Comment by bethanylang** [comment]
Thanks @jimmymadon! I have an Asana task for Sigal for when she returns to do this redesign. I'll add this requirement to the task.

**Comment by marrrmarrr** [comment]
+1 to what @jimmymadon mentioned. We do need some sort of notice in the metrics panel.

**Comment by aaemnnosttv** [comment]
One thought here for @sigal-teller is that we should group all the disabled/unavailable tiles below the available ones to avoid hiding available tiles below the fold. I.e. the grouping would always be: `selected`, `available`, `unavailable` (based on the current _saved_ state from answers or selections).

**Comment by marrrmarrr** [comment]
@jimmymadon the notice added to the tile and the copy look good, just wanted to check what is the functionality of the checkbox? Can it be unchecked/checked?

**Comment by marrrmarrr** [comment]
thanks for the extra details, @jimmymadon. this sounds good for now, or at least better than blocking people from selecting anything at all and leaving them with one metric only. if for some reason they won't or can't reconnect GA, then they could disable the whole feature from Settings as well.

**Comment by tofumatt** [comment]
ACs are good 👍🏻

**Comment by tofumatt** [comment]
IB looks good here ✅

**Comment by 10upsimon** [comment]
**Update:** 

Following a meeting with @jimmymadon last week, we discussed that it made more sense to feed an array of disconnected modules to the `<Metrics>` component, rather than set a boolean value within a loop. This came about as a result of a quirk in the story, where multiple modules attached to a metric (albeit not the case in production _yet_) would cause the boolean to be incorrectly set if the last module in the loop was connected but prior ones were not.

By feeding an array of disconnected modules, we are better able to ascertain whether we need to render the notice, and can easily word singular and multiple module disconnections.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@10upsimon @jimmymadon An observation: I selected the search console metric and a few GA4 metrics.  I then disconnected Analytics and on the view only dashboard, the key metrics area is not appearing.  I have a feeling this is expected but not 100% sure so I wanted to check.  I know we've had a few changes with the view only dashboard and KMWs so please could you confirm if this behaviour is correct? 

![image](https://github.com/google/site-kit-wp/assets/73545194/207e3116-3921-4259-b6ce-bbeb0da18ae8)

**Verified:**

- All 4 metrics are displaying correctly
- Metrics can be changed within the metric selection panel
- When GA4 is disconnected, the KMW for search console appears, but the GA4 KMW's are replaced by a single tile indicating that Analytics has been disconnected. 
- The metric selection panel can still be open and GA4 metrics are visible and selectable.
- GA4 metric items in the list have a clear notice text within them stating that the GA4 module is disconnected and that there is no data to show.
- GA4 metrics arestill be selectable and show once the GA4 service is reconnected.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/6d2ff337-7d4d-4b8a-ae3e-1c091014fa3a)
![image](https://github.com/google/site-kit-wp/assets/73545194/316f7ea8-497e-4a11-99d7-3f3716cfc9e5)
![image](https://github.com/google/site-kit-wp/assets/73545194/a51b22b2-515d-4746-a43e-b31207a42be3)
![image](https://github.com/google/site-kit-wp/assets/73545194/aec8aa95-386f-42cf-bdfe-8387f07d1394)
![image](https://github.com/google/site-kit-wp/assets/73545194/bafc15de-d1fc-4a12-9df0-c61449e9c90a)

</details>

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- All 4 metrics are displaying correctly
- Metrics can be changed within the metric selection panel
- When GA4 is disconnected, the KMW for search console appears, but the GA4 KMW's are replaced by a single tile indicating that Analytics has been disconnected. 
- The metric selection panel can still be open and GA4 metrics are visible and selectable.
- GA4 metric items in the list have a clear notice text within them stating that the GA4 module is disconnected and that there is no data to show.
- GA4 metrics are still be selectable and show once the GA4 service is reconnected.

While view only dashboard wasn't mentioned in the QAB, I did complete some testing due to the fatal error that initially occured from this ticket and all looks good. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/6d2ff337-7d4d-4b8a-ae3e-1c091014fa3a)
![image](https://github.com/google/site-kit-wp/assets/73545194/316f7ea8-497e-4a11-99d7-3f3716cfc9e5)
![image](https://github.com/google/site-kit-wp/assets/73545194/a51b22b2-515d-4746-a43e-b31207a42be3)
![image](https://github.com/google/site-kit-wp/assets/73545194/aec8aa95-386f-42cf-bdfe-8387f07d1394)
![image](https://github.com/google/site-kit-wp/assets/73545194/bafc15de-d1fc-4a12-9df0-c61449e9c90a)

</details>
