### ISSUE TITLE
Visual Regression Testing has started to time out in CI

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7426]
## Bug Description

Due to our VRT suite expending in size, the `20` minute timeout set for CI is no longer sufficient and the VRT's are failing. 

On the short term, we need to increase the timeout to mitigate this issue, while on longer term, we should explore ways to reduce the time required for the suite to run.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Visual Regression Testing` GitHub Action should have its timeout increased to 30 minutes.

## Implementation Brief

* In `.github/workflows/visual-regression.yml`:
    * Update the `timeout-minutes` from `20` to `30`.

### Test Coverage

* N/A

## QA Brief

* Nothing to QA here. Should be sent directly to approval as long as the VRT passes in the PR and merge commit. 

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Hey @kuasha420, thanks for raising this - we do have an existing issue that covers it though, https://github.com/google/site-kit-wp/issues/7388; also, @aaemnnosttv [suggested](https://10up.slack.com/archives/CBKKQEBR9/p1690828033287699?thread_ts=1690827179.557259&cid=CBKKQEBR9) we could increase the number of tests that run in parallel as an alternative, which is included as a point in that issue...

**Comment by techanvil** [comment]
As discussed on Slack, we're going ahead with this issue for the quick win, and repurposing #7388 for a future improvement.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by tofumatt** [comment]
Nothing to QA here, so moving directly to approval.
