### ISSUE TITLE
Remove Success Banner notification

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7429]
## Feature Description

The old Success Banner notification from User Input ("Congrats! You set your site goals.") should be removed.

<img width="1925" alt="Screenshot 2023-08-18 at 19 39 20" src="https://github.com/google/site-kit-wp/assets/1721319/7c2deb1a-9a42-4af6-925a-fc72c5c7eec0">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Success Banner notification which is displayed on the dashboard after the user answers the User Input questionnaire ("Congrats! You set your site goals.") should be removed.
    * The Banner appears when the questionnaire is triggered from either the Key Metrics Setup Banner CTA on the main dashboard and even from the Admin -> Settings page.

## Implementation Brief

* Remove `UserInputSuccessBannerNotification` component.
    * Delete `assets/js/components/notifications/UserInputSuccessBannerNotification.js`.
    * Delete `assets/js/components/notifications/UserInputSuccessBannerNotification.stories.js`
* Remove usage of `UserInputSuccessBannerNotification` component. 
    * In `assets/js/components/Header.stories.js`:
        * Use something else (ie. `OptimizeRemovalNotification`) as `subHeader` instead of `UserInputSuccessBannerNotification`.
    * In `assets/js/components/user-input/UserInputQuestionnaire.js`:
        * Remove the User Input Banner related logic from `submitChanges` callback.
        * https://github.com/google/site-kit-wp/blob/7a07e33138901e629198c172d82902f910b0afed/assets/js/components/user-input/UserInputQuestionnaire.js#L111-L119
    * In `asets/js/components/notifications/BannerNotifications.js`:
        * Remove the logic related to User Input banner.
        * https://github.com/google/site-kit-wp/blob/7a07e33138901e629198c172d82902f910b0afed/assets/js/components/notifications/BannerNotifications.js#L103
    * In `assets/js/components/notifications/SetupSuccessBannerNotification.js`. 
        * Remove the switch statement that matches `notification`. and just keep the code in the case inside `authentication_success`.

### Test Coverage

* Fix failing tests and VRT images.

## QA Brief

* Setup Site Kit with the `userInput` feature flag enabled and GA4 connected.
* Run through the User Input questionnaire and verify that the success banner no longer appears.
* Check this when triggering the questionnaire from both the Key Metrics CTA on the Dashboard, and from the **Settings > Admin Settings** page.

## Changelog entry

* Remove old User Input banner notification.

**Comment by techanvil** [comment]
Hey @kuasha420! This IB is looking good, I think we'll want to remove a couple more snippets of code though:

Essentially, this block:

https://github.com/google/site-kit-wp/blob/7a07e33138901e629198c172d82902f910b0afed/assets/js/components/user-input/UserInputQuestionnaire.js#L111-L119

And the `user_input_success` condition from `BannerNotifications`:

https://github.com/google/site-kit-wp/blob/7a07e33138901e629198c172d82902f910b0afed/assets/js/components/notifications/BannerNotifications.js#L103

We can then presumably remove the switch statement from `SetupSuccessBannerNotification` as `notification` will only have the value `'authentication_success'`:

https://github.com/google/site-kit-wp/blob/7a07e33138901e629198c172d82902f910b0afed/assets/js/components/notifications/SetupSuccessBannerNotification.js#L189-L190

**Comment by kuasha420** [comment]
@techanvil Thank you for the review and finding couple more instances of code that can be removed. I have updated the IB accordingly. Cheers.

**Comment by techanvil** [comment]
Thanks @kuasha420! IB LGTM :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Success Banner notification is no longer appearing after the user answers the User Input questionnaire.  Checked this when the questionnaire is triggered from the KM Setup Banner on the main dashboard and the Admin Settings page. 
- Navigated away from the dashboard and refreshed to make sure the banner didn't reappear as we've had this issue sometimes when removing banners. 
- Tested on a slow 3G connection and 4G.

<details>
 <summary>Screencasts</summary>

https://github.com/google/site-kit-wp/assets/73545194/3d1d0144-d1f5-48f6-b288-998625023141

https://github.com/google/site-kit-wp/assets/73545194/dfa63bf9-1e8f-45b3-8022-43b6d0299394


</details>
