### ISSUE TITLE
Jetpack says 😲"Threat Found"🤨 in SiteKit 

### ISSUE THREAD

**Issue by BurlesonBrad** [google/site-kit-wp#743]
## Bug Description
_possible false flag thrown in Jetpack_

## Please describe clearly and concisely what the bug is. -->
https://prnt.sc/ppscf8
![image](https://user-images.githubusercontent.com/6208757/67798877-57deeb00-fa52-11e9-877e-699e4978e18b.png)

`The threat known as PHP.Generic.BadPattern.5 has been found in /htdocs/wp-content/plugins/google-site-kit/third-party/react/promise/src/Promise.php around lines 95 - 97`

## Steps to reproduce

1. Go to '...' **_My laptop 💻 with a bowl of cereal 🥣_**
2. Click on '....' **_ With non-spoon 🥄 hand, open my Email 🖱_**
3. Scroll down to '....' **_Email which states, "Jetpack has detected a security threat...." 😣_**
4. See error `The threat known as PHP.Generic.BadPattern.5 has been found in /htdocs/wp-content/plugins/google-site-kit/third-party/react/promise/src/Promise.php around lines 95 - 97`

## Screenshots
![image](https://user-images.githubusercontent.com/6208757/67800565-6f6ba300-fa55-11e9-94f4-957b9021be5b.png)

![image](https://user-images.githubusercontent.com/6208757/67799526-827d7380-fa53-11e9-9c01-b191786ddbe4.png)

## Additional Context

 - PHP Version: **_7.3_**
 - OS: [e.g. iOS]  **_Whatever b.s. update Microsoft came up with recently_**  _(not applicable)_
 - Browser [e.g. chrome, safari] **_Google Chrome Version 78.0.3904.70 (Official Build) (64-bit)_**
 - Plugin Version [e.g. 22]  **_Site Kit by Google 1.0.0-rc.2_**
 - Device: [e.g. iPhone6] **_Rusty but seasoned & still working old laptop_**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by bikedorkjon** [comment]
Hey it's Jon from the Jetpack/VaultPress team just commenting here that this is actually a false positive for a coding pattern we look for and nothing to worry about here.

**Comment by jamesozzie** [comment]
@bikedorkjon Good to know, thanks Jon. @BurlesonBrad I will close this issue now, but feel free to share any other potential bugs to investigate.
