### ISSUE TITLE
Hide KMW if 3 or 4 tiles rely on unshared modules

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7435]
## Feature Description

On the view-only dashboard, if Search Console is shared but Analytics is not, then the single "Top Performing Keywords" metric tile is displayed as in the below screenshot.
<img width="3007" alt="Screenshot 2023-08-15 at 13 30 56" src="https://github.com/google/site-kit-wp/assets/1721319/d567ad2e-ca30-42ad-acb0-d3002ac74a49">

The design doc suggested to hide the entire KMW if there were was just a single tile, like in the case above. However, this is in line with our Widgets API and does not require additional widget specific conditional logic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Given a non-authenticated admin views the "View-only dashboard", when 2 or more tiles rely on modules which are not shared, i.e. when only a single tile is from a module that is shareable, then the KMW area should be hidden completely.
    * Note: This scenario is currently only possible if Search Console is shared but GA4 is not shared.

## Implementation Brief

In `assets/js/googlesitekit/widgets/datastore/areas.js`:

#### Update Widget Area Registration Action

* Extend the `registerWidgetArea` action to include an optional `filterActiveWidgets` callback function.
* Pass the `filterActiveWidgets` callback function to the `settings` object within the `payload` object.

#### Update the `isWidgetAreaActive` selector

* Retrieve the widget area using the `getWidgetArea` selector.
* Retrieve All Widgets in the Widget Area:
    * Get all widgets in the widget area identified by `widgetAreaSlug`.
    * Store the returned widget list in a variable called `areaWidgets`.
    * Pass the `widgetAreaSlug` and `modules` option to the `getWidgets` selector.
* Apply `filterActiveWidgets` Function If Provided:
    * Check if the `widgetArea` object contains a `filterActiveWidgets` function.
    * If it does, call this function with the `select` function and `areaWidgets` as arguments.
    * Update the `areaWidgets` variable with the returned value.
* Determine If the Widget Area Is Active:
    * Finally, check if any widgets in the updated `areaWidgets` list are active using the `isWidgetActive` selector.
    * Return `true` if at least one widget is active; otherwise, return `false`.

#### Register Widget Area with Filtering Function

In `assets/js/googlesitekit/widgets/register-defaults.js`:

* Locate the `CONTEXT_MAIN_DASHBOARD_KEY_METRICS` widget area registration.
* Add a `filterActiveWidgets` callback function to the `settings` object.
* The `filterActiveWidgets` function should accept the `select` function and `areaWidgets` array as parameters.
* Remove all the widgets if there is only one widget in the `areaWidgets` array by returning an empty array.
* Otherwise, return the `areaWidgets` array as is.

### Test Coverage

* Add test cases for the `registerWidgetArea` action to confirm that `filterActiveWidgets` is correctly set.
* Add test cases for the `isWidgetAreaActive` selector to ensure it correctly uses `filterActiveWidgets` if provided.

## QA Brief

* Set up Site Kit with Search Console and GA4.
* Set up Key Metrics Widgets.
* Share Search Console and Analytics 4 with a view-only user.
* Login as the view-only user and verify that the Key Metric Widgets are visible.
* If the `Top performing keywords` tile is displayed, select it to display by changing the metrics from the Metrics Selection panel.
* Unshare GA4 with the view-only user.
* Verify that the KMW area is entirely hidden as `Top performing keywords` is the only tile available for Search Console.

## Changelog entry

* Hide Key Metrics widget area when only one widget is present on the Shared Dashboard.

**Comment by bethanylang** [comment]
@marrrmarrr Noting that this was one that we had as a Nice to Have from Bug Bash; just let me know if it should be closed instead. Thanks!

**Comment by bethanylang** [comment]
Thanks, @jimmymadon! Also just flagged this for Mariya in Slack.

**Comment by techanvil** [comment]
Hmm. @jimmymadon @aaemnnosttv, noting the comment above this one, I'm not sure how best to proceed here. The AC could work, but do we want to close this one off as unplanned?

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

> Verify that the KMW area is entirely hidden as `Top performing keywords` is the only tile available for Search Console.

@hussain-t  I have followed the QAB, and when I remove access to Analytics 4 to the view only user (Editor role) and go back to the View only dashboard, the only tile that appears is Search Console.  According to the QAB, the KMW area shouldn't appear at all.   I cleared session storage and also cleared my cookies and the same applies.   

I ran another test where I removed Search Console for view only user and only the GA4 widgets appeared, and the Search Console widget didn't, which is expected I assume.   Interested in your thoughts here. 

![image](https://github.com/google/site-kit-wp/assets/73545194/d2863efe-5df6-43d5-a6c6-e27538e98247)

**Comment by hussain-t** [comment]
@wpdarren, it appears the `develop` branch wasn't updated due to a build issue in the GitHub actions. Please perform another round of testing.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The KMW area is hidden as `Top performing keywords` is the only tile available for Search Console when GA4 is not permitted. As per the QAB and AC. 
- The KMW area **does** appear when the `Top performing keywords` is selected but SC is **not** permitted. The tile **does not** appear though, only 3 GA4 titles appear in the widget. 
- Tested that the `Top performing keywords` tile and KMW widget area appears when SC and GA4 is permitted.
- Tested that if the view only user does not select the `Top performing keywords` tile but GA4 is not permitted then the KMW widget area does not appear. 
  
<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/05b548ab-7e73-4216-be4b-e99823b54b0d)
![image](https://github.com/google/site-kit-wp/assets/73545194/83b80bef-7d19-4a93-b359-27f2648944d8)
![image](https://github.com/google/site-kit-wp/assets/73545194/7b1529a6-f136-4966-bf1b-459ffe93710e)

</details>
