### ISSUE TITLE
Remove/update links on "Most popular content" KMW tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7436]
## Bug Description

When on the view-only dashboard, if the site does not have any products, the `Most popular content by pageviews` have active links, which send the user to the actual page.  These links should be removed similar to how they were removed for the `Most popular products by pageviews`. Furthermore, on the main dashboard these should point to Analytics, rather than to the actual page.

## Steps to reproduce

1. Set up the Key Metrics widget and ensure the `Most popular content by pageviews` is part of the selected metrics.
2. When logged in as an authenticated admin, the `Most popular content by pageviews` links point to the actual page on the website. This should be modified to point to the GA4 admin's "Pages and screens: Page path and screen class" for the page that was clicked exactly the same as the links in the titles of the "Top content over the last x days" Dashboard widget.
3. Share the GA4 module using the Dashboard Sharing popup.
4. Now log in as a non-authenticated user. The `Most popular content by pageviews` should still be visible with links. These links should be removed instead of taking the user to the website page itself.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the main dashboard (for authenticated admins), the links within the `Most popular content by pageviews` widget tile should be updated to point to the GA4 Admin's "Pages and screens: Page path and screen class" for the page that was clicked. This behaviour should be exactly the same as when the links in the titles of the "Top content over the last x days" Dashboard widget are clicked.
* On the view-only dashboard, the links for pages within the `Most popular content by pageviews` widget tile should be removed.

## Implementation Brief

In `assets/js/modules/analytics-4/components/widgets/PopularContentWidget.js`:

#### Updating URLs for Authenticated Admins on Main Dashboard

* Locate the `columns` array where the `url` is set.
* Use the `getServiceReportURL` selector from the `modules/analytics-4` store to get the GA4 service URL.
* Prepare URL Parameters with the following:
    * Pass `all-pages-and-screens` as the first argument.
    * Pass an object with the following properties for the second argument:
        * `filters`: Create an object with a key called `unifiedPagePathScreen` and set its value to `url`.
        * `dates`: Obtain these values from the `getDateRangeDates` selector.
* Pass the above GA4 service URL to the `Link` component's `href` prop.

#### Remove URLs for View-Only Dashboard

* If the user has a view-only dashboard, render the title as non-interactive plain text using the `MetricTileTablePlainText` component.

In `assets/js/modules/analytics-4/components/widgets/PopularContentWidget.stories.js`:

* Create a new story to represent the view-only dashboard scenario.

* Ensure that the main dashboard and the view-only dashboard views are implemented in a manner consistent with the [PopularProductsWidget](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/modules/analytics-4/components/widgets/PopularProductsWidget.js#L146-L162) component.

### Test Coverage

* Add a VRT scenario for the newly added view-only dashboard story.

## QA Brief

* Follow the steps to reproduce above, but in the last step, "Most popular content by pageviews" should no longer have links.

## Changelog entry

* Hide inaccessible links in Key Metrics tiles when using the view-only dashboard.

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@jimmymadon I noticed that on the view only dashboard for `Most popular content by pageviews` and `Most popular products by pageviews` there isn't an ellipsis when the title is too long.  One does appear on the main dashboard so I feel we should be consistent. Would you agree?  

This is possibly out of scope and I can create a new ticket if that helps? It's not a big issue. 
 
View only - text only
![image](https://github.com/google/site-kit-wp/assets/73545194/dd116557-358d-45ec-84aa-a18e031b0335)

Main dashboard - links
![image](https://github.com/google/site-kit-wp/assets/73545194/70051443-1be7-4ae6-9b9e-259ce944dfa7)

**Verified:**

- On the main dashboard, the links within the `Most popular content by pageviews` widget tile are updated to point to the GA4 Admin's `Pages and screens: Page path and screen class` for the page that was clicked. 
  - Tested on 7, 14, 28 and 90 days reporting periods.
  - Tested on desktop, and small viewports like mobile. 
  - Tested on view only with admin and editor
  - Tested with 2nd admin user.
- On the view-only dashboard, the links for pages within the `Most popular content by pageviews` widget tile are removed.

<details>
 <summary>Screencast</summary>

https://github.com/google/site-kit-wp/assets/73545194/b874385d-e7a9-4da9-93ed-62a6f5f87163

![image](https://github.com/google/site-kit-wp/assets/73545194/24da8aae-64e8-4c9a-a9b4-ffc0495cdcee)
![image](https://github.com/google/site-kit-wp/assets/73545194/dc05cf0d-4450-42f5-81a2-8ed0923d5743)

</details>

**Comment by hussain-t** [comment]
@wpdarren, IMHO, it's a valid issue to be addressed in a separate ticket. Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@hussain-t thank you, I shall create a new ticket! 

**Verified:**

- On the main dashboard, the links within the `Most popular content by pageviews` widget tile are updated to point to the GA4 Admin's `Pages and screens: Page path and screen class` for the page that was clicked. 
  - Tested on 7, 14, 28 and 90 days reporting periods.
  - Tested on desktop, and small viewports like mobile. 
  - Tested on view only with admin and editor
  - Tested with 2nd admin user.
- On the view-only dashboard, the links for pages within the `Most popular content by pageviews` widget tile are removed.

<details>
 <summary>Screencast</summary>

https://github.com/google/site-kit-wp/assets/73545194/b874385d-e7a9-4da9-93ed-62a6f5f87163

![image](https://github.com/google/site-kit-wp/assets/73545194/24da8aae-64e8-4c9a-a9b4-ffc0495cdcee)
![image](https://github.com/google/site-kit-wp/assets/73545194/dc05cf0d-4450-42f5-81a2-8ed0923d5743)
![image](https://github.com/google/site-kit-wp/assets/73545194/75d76d34-c162-4814-a45a-7193dc1d135a)

</details>
