### ISSUE TITLE
GA4 Activation banner triggers GA settings request without GA

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7438]
## Bug Description

The GA4 activation banner currently renders unconditionally with other banners. Due to internal use of GA settings, this results in an unnecessary fetch that is made on the dashboard when GA isn't connected. The activation banner is only relevant for sites with UA connected but have not set up GA4 yet. This component is slated to be removed soon as UA is being phased out but this is a simple fix that we should be able to address easily

## Steps to reproduce

1. Set up SK without GA
2. See request to `analytics/data/settings` in the console

The request happens because module settings are only preloaded for active modules, but the banner shouldn't be rendered at all if `analytics` isn't connected.

Source

https://github.com/google/site-kit-wp/blob/189e2510dd983fcf5de71677daa2d4afbd390e6c/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/index.js#L77C1-L79

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics settings should not be requested when viewing the SK dashboard

## Implementation Brief

* Update the `ActivationBanner` component export to be wrapped with `whenActive` so that it only renders when `analytics` (UA) is connected
* Update the inner conditions of the component to assume that `analytics` is connected. E.g. this value would be unnecessary because it would always be `true` https://github.com/google/site-kit-wp/blob/189e2510dd983fcf5de71677daa2d4afbd390e6c/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/index.js#L61-L63

### Test Coverage

* No additional coverage needed

## QA Brief

* Connect SK without Analytics.
* Observe the networks tab on developer tools while visiting SK. There should not be a fetch to the `analytics/data/settings` route.  

## Changelog entry

* Fix a bug that caused an unneeded network request when viewing the Analytics activation banner.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On latest version (1.107.0) I am able to see the network `analytics/data/settings` route as per the ticket.  When I switch to the main branch. the route no longer appears when setting up Site Kit without Analytics. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/8627d5a9-304a-4b19-adf9-030bb8a42801)
![image](https://github.com/google/site-kit-wp/assets/73545194/bacc4adc-2ccf-4d94-984b-63359b1f9ffa)

</details>
