### ISSUE TITLE
Analytics snippet inserted by Analytify plugin not detected

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#744]
The Analytics snippet inserted by [Google Analytics Dashboard Plugin for WordPress by Analytify ](https://wordpress.org/plugins/wp-analytify/)is not detected by Site Kit. Both snippets are inserted, and the notices in the UI about additional snippets on the site are missing. 

## Steps to reproduce

1. Install, activate and configure the [Analytify plugin](https://wordpress.org/plugins/wp-analytify/)
2. Connect the Google Analytics module in Site Kit
3. Go to _Site Kit > Settings> Google Analytics > [Edit]_ to see the notices are missing for the additional snippet

## Screenshots

Source code:

![Analytify snippet not detected](https://user-images.githubusercontent.com/8108643/67804542-5ca0a080-fa4c-11e9-93ed-e0267812d9e4.png)

## Additional Context

 - PHP Version: 7.1.30
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version:  1.0.0-rc.2
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The plugin should detect when there's an Analytics snippet already present in the source code, including those in the format that the Analytify plugin generates.
* In such cases, the user should be blocked from proceeding if they don't have access, or it should be force-selected in the dropdown, as expected for any existing snippet.

## Implementation Brief

Add a new regex definition for matching the Analytics script added by Analytify  
```js
/<script[^>]*>[^<]+google-analytics\.com\/analytics\.js[^<]+(UA-\d+-\d+)/
```  
![image](https://user-images.githubusercontent.com/1621608/68188121-25347580-ffb1-11e9-97b4-ae752c8ac865.png)

Note this pattern is fairly generic and could also match others that our current patterns may be missing.

Any existing pattern that this also matches can be removed.

## Changelog entry

* Improve detection of existing Analytics snippet by covering a further variant that is used e.g. by the Analytify plugin.

**Comment by aaemnnosttv** [comment]
@felixarntz this issue should be addressed by #795.

**Comment by felixarntz** [comment]
IB ✅ 

(PR is already merged, so moving this to QA)

**Comment by adamsilverstein** [comment]
This passes QA, moving to Approval. 

I did notice an issue that appears unrelated to the changes here during my testing. I will open a follow up issue. Notes below.

#### Testing Procedure

* Install the `wp-analytify` plugin.
* Configure the wp-analytify plugin, letting it insert the tag by default for unauthenticated users only
* Set up analytics in site kit, verify tag is detected correctly during setup:

![image](https://user-images.githubusercontent.com/2676022/68333646-24c1da80-0096-11ea-98b7-4b067003b403.png)

I noticed a separate issue with tag detection when testing this on Jurassic Ninja - the issue did not occur when I tested this locally:

**Tag detection doesn't show until you select an account**

In my analytics account I have several "Accounts" set up - on Jurassic Ninja, when I first load the Analytics setup flow with a tag detected, I don't see the tag detected message:

![image](https://user-images.githubusercontent.com/2676022/68333819-8e41e900-0096-11ea-891d-de139972e674.png)

Then, once I select an account, the message shows:

![image](https://user-images.githubusercontent.com/2676022/68333902-b7627980-0096-11ea-8577-0e34882e9a1d.png)

Testing this in my local with a domain i have access to, the tag detection works as expected, I see the notice immediately.

**Comment by marrrmarrr** [comment]
Verified, lgtm
