### ISSUE TITLE
Can't toggle "Display key metrics in dashboard" when user-defined key metrics are not set.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7441]
## Bug Description

_This is an issue raised in the KM bug bash, see https://app.asana.com/0/1204713925711993/1205270012034069/f._

The "Display key metrics in dashboard" toggle doesn't work unless the user has defined their own set of widgets via "I'll pick metrics myself", or "Change Metrics".

This is a result of a [change](https://github.com/google/site-kit-wp/pull/7431/files#r1293692067) in the PR for https://github.com/google/site-kit-wp/issues/7349.

## Steps to reproduce

1. Setup Site Kit with the `userInput` feature flag enabled and GA4 connected.
2. Answer the questionnaire by selecting "Get tailored metrics", but don't customize the KM selection.
3. Navigate to **Admin > Admin Settings**, and open devtools.
4. Toggle the "Display key metrics in dashboard" switch to the _off_ position.
5. Notice the request to `/wp-json/google-site-kit/v1/core/user/data/key-metrics` will have failed with a `400` status code and "Selected metrics cannot be empty" error message.
6. Refresh the page to see that the "Display key metrics in dashboard" switch reverts to the the _on_ position.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/18395600/497789c0-c020-419d-a1c4-b0a1bb2bd6d9)

https://github.com/google/site-kit-wp/assets/18395600/bb75c36b-9597-4ce0-a1b4-e65c809398cb

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Display key metrics in dashboard" switch on the Key Metrics admin page should toggle and persist its corresponding value regardless of whether the Key Metrics selection has been customized by the user or not.
* The `/wp-json/google-site-kit/v1/core/user/data/key-metrics` endpoint should continue to validate that there is at least one key metric slug defined, but _only_ in the case where the user has customized the selection.

## Implementation Brief

* In `includes/Core/Key_Metrics/REST_Key_Metrics_Controller.php`:
   * For the `POST:core/user/data/key-metrics` route:
       * Make the `widgetSlugs` arg optional by changing the `'required' => true` to `'required' => false`.
       * Inside the route callback, 
           * Only run the logic related to `$num_widgets` when `widgetSlugs` is set in `$data['settings']`.
           * Only set the `$this->key_metrics_setup_completed` to `true` when `widgetSlugs` is set in `$data['settings']`.
* In `assets/js/googlesitekit/datastore/user/key-metrics.js`:
    * In the `saveKeyMetricsSettings` action:
        * At the very end of this action, only dispatch the `setKeyMetricsSetupCompleted` when `settings.widgetSlugs` is not falsey. 
* In `assets/js/components/settings/SettingsKeyMetrics.js`: 
    * In the `handleKeyMetricsToggle` callback:
        * Pass `{ widgetSlugs: undefined }` parameter to the `saveKeyMetricsSettings` call.

### Test Coverage

* Add test coverage for above changes. 

## QA Brief

* On a fully reset site (KM not set up yet), complete the user input question. 
* Answer based KM tiles should be visible. 
* Visit SK settings and turn off Key Metrics toggle.
* The KM tiles should be hidden .
* Enable the widget again from Settings 
* Tiles should get re-enabled. 
* Customize Key Metrics tiles. 
* The customization should be saved correctly. 
* Verify the above display behavior of the Key Metrics Widgets for a secondary admin user who has not yet completed the user input questionnaire.

## Changelog entry

* Fix bug that caused the "Display key metrics in dashboard" toggle not to work when no user-defined metrics were saved.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

- When I turn off Key Metrics toggle, the KM tiles are hidden .
- When I enable the widget again from settings, the tiles are re-enabled.
- When I customize Key Metrics tiles, the customization is saved correctly.
- The above behavior of the Key Metrics Widgets is the same for a secondary admin user who has not yet completed the user input questionnaire.

**Additional QA:**

- Checked the network table in browser when the toggle is enabled and disabled to ensure that no Error 400 appears as per the issue description.   Also did the same when changing the metrics and testing with a 2nd admin user. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/5da14831-e9d8-4e6f-a998-4a836213a407)
![image](https://github.com/google/site-kit-wp/assets/73545194/46596537-8476-464d-bd68-42291e77bb11)
![image](https://github.com/google/site-kit-wp/assets/73545194/3bd3c03d-ab1c-471d-8727-63e56da8574e)
![image](https://github.com/google/site-kit-wp/assets/73545194/65e60d35-acb8-4f79-b6f8-a213f8a7eaad)

</details>
