### ISSUE TITLE
Site kit error after updating

### ISSUE THREAD

**Issue by artkitecto** [google/site-kit-wp#745]
hi there.
i got the developer beta plugin and when i updated the plugins and authorize it i see the Errors when getting OAuth credentials.
Error: Bad Request -> missing parameter: 'name'
![updated-site-kit-error](https://user-images.githubusercontent.com/42272625/67826500-487f9200-fa92-11e9-9013-126cedae8933.jpg)

**Comment by jamesozzie** [comment]
@artkitecto Thanks for reporting, I'm not familiar with this issue so it would be good to troubleshoot. Are you seeing any [console errors](https://i.imgur.com/KyLAzgH.png) using Chrome dev tools? You can attempt the following to try and get Site Kit setup:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png).

If the above fails to resolve your issue can you please share the following:
- Any that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by alimohammadafshar** [comment]
I have this problem too.
Although I've done all the things that said above, the problem still exists!
What else should I do?

**Comment by alimohammadafshar** [comment]
> I have this problem too.
> Although I've done all the things that said above, the problem still exists!
> What else should I do?

solved!
There is some limitation regards to the country that the site has been hosted.

**Comment by jamesozzie** [comment]
@alimohammadafshar Thanks for the update, really useful to know. What were the limitations, were you using a VPN/security plugin or other?

**Comment by alimohammadafshar** [comment]
In my case, I found this problem with .ir . ( ccTLD)
But I have no problem with .com .ca  .au .
