### ISSUE TITLE
Update the survey rendering component to skip questions when trigger conditions have non-existing answers.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#7450]
## Feature Description

Currently, our component that is responsible for rendering surveys takes into account only those trigger conditions that refer to existing questions only (see the code reference below). That is the correct behaviour and that is how it should be done, but for our next survey we need an ability to force certain questions to be skipped. 

When we prepare that survey on the service side, we add a trigger condition to that question that refer to a non existing answer if we see that that question should be skipped. We need to update the `CurrentSurvey` component to not ignore trigger conditions that refer to non-existing questions.

https://github.com/google/site-kit-wp/blob/08bddd4bf55b929f25e8c5a0c17eb1081012c5db/assets/js/components/surveys/CurrentSurvey.js#L119-L121

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The survey rendering component should skip questions if they have trigger conditions that don't refer to an existing answer.

## Implementation Brief

* The following condition should be updated to return false not only when the expected answer is present in the allowed answers map but also when the `anwser` variable can't be found: https://github.com/google/site-kit-wp/blob/08bddd4bf55b929f25e8c5a0c17eb1081012c5db/assets/js/components/surveys/CurrentSurvey.js#L121
  * In other words the condition should be changed to `! answer || ! allowedAnswers.includes( answer )`.

### Test Coverage

* N/A

## QA Brief

This change can be tested using the new HaTS survey for user input answers:
* Create a new site and connect it to staging
* Enable the userInput feature flag and connect the GA4 module
* Answer user input questions using the following answers:
  * `What is the main purpose of this site?` - select something except "Other"
  * `How often do you create new content for this site?` and `What are your top goals for this site?` - select "Other"
* Save the user input settings and go to the dashboard.
* If you don't see the survey, you need to reset the survey timeout by running the following code in your browser console: 
   ```js
   googlesitekit.data.dispatch('core/user').setSurveyTimeout('__global', 1)
   ```
* Wait a few more seconds and refresh the page. You should see the survey and the first question should start from the question that you answered as "Other" in the user input questions. Questions that you answer as non-Other should not be asked in the survey.

## Changelog entry

* Update surveys to skip rendering when no answers are found.

**Comment by aaemnnosttv** [comment]
SGTM, thanks @eugene-manuilov 👍

**Comment by mohitwp** [comment]
@wpdarren Are you able to generate survey following QAB ? I tried 2–3 times but did not get success. 
I'm using staging environment for service and develop environment for plugin.

**Comment by eugene-manuilov** [comment]
@mohitwp did you reset your survey timeouts? Probably you also need to clear your browser session storage.

If it doesn't help, try to see in the database that you have not empty `wp_googlesitekit_survey_queue` metadata for your user. Also if you see `wp_googlesitekit_survey_timeouts` there as well, you can just delete that row to make sure that survey timeouts are reset.

**Comment by mohitwp** [comment]
Thanks @eugene-manuilov !
Survey triggered successfully.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@eugene-manuilov me and @wpdarren both tried to trigger survey on new sites but didn't get success. I created 4 sites, but the survey did not trigger on all 4 sites. It was getting trigger till yesterday. Can you please check why it is not getting trigger?

**Comment by wpdarren** [comment]
@eugene-manuilov just to add to Mohit's comment.  I tried this on `develop` and `main` and this survey isn't being generated.  I did use the tester plugin to generate another survey successfully.

![image](https://github.com/google/site-kit-wp/assets/73545194/c1f5d965-cb89-4c66-8c02-cc08d48ea27c)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.

**Verified** -
- Tested scenario when all answers for user input questions are selected as 'OTHER'.
- Tested scenario when all answers for user input questions are not selected as 'OTHER'.
- Tested scenario when 1 ans or 2 ans are selected as 'OTHER'.
- Verified Questions that answer as non-Other are not asked in the survey.
- Verified if user change answers from settings and if survey is not completed then survey shows updated questions.


<details>

When answers for all 3 User Input questions are non-others and later user change answer to 'OTHER' under admin settings.

https://github.com/google/site-kit-wp/assets/94359491/bf2401d7-139e-4a86-b60f-ca1800dd5ad1

When user change answer from admin settings.

https://github.com/google/site-kit-wp/assets/94359491/862c05ec-27f5-4a33-86ff-f104bfd8850d


</details>
