### ISSUE TITLE
Titles of some KMW tiles are inconsistent between dashboard and selection panel

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7451]
## Feature Description

As reported by @aaemnnosttv in Bug Bash:

Some of the titles of the KMW tiles are different in the metrics selection panel vs. how on the dashboard.

@marrrmarrr Assigning this over you to confirm how you'd like us to align these. Here's the current mapping:

| Selection Panel | Dashboard |
| --- | --- |
| Audience growth | New visitors |
| Top converting traffic source | Top converting traffic source |
| Loyal visitors | Loyal visitors |
| Top traffic source | Top traffic source |
| Most engaged traffic source | Most engaged traffic source |
| Most popular content | Most popular content by pageviews |
| Most popular products | Most popular products by pageviews |
| Top cities by traffic | Top cities driving traffic |
| Top countries by traffic | Top countries driving traffic |

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The titles of the metrics in the selection panel should be updated to match the corresponding titles in the dashboard.
* The title of the Top Traffic Source KMW tile should be updated to `Top traffic source`.

## Implementation Brief
* In `assets/js/components/KeyMetrics/key-metrics-widgets.js`:
    * Update the `title` for the following widgets:
        * `KM_ANALYTICS_NEW_VISITORS` : `New visitors`
        * `KM_ANALYTICS_POPULAR_CONTENT` : `Most popular content by pageviews`
        * `KM_ANALYTICS_POPULAR_PRODUCTS` : `Most popular products by pageviews`
        * `KM_ANALYTICS_TOP_CITIES` : `Top cities driving traffic`
        * `KM_ANALYTICS_TOP_COUNTRIES` : `Top countries driving traffic`
* In `assets/js/modules/analytics-4/components/widgets/TopTrafficSourceWidget.js`:
    * Update `title` prop of `MetricTileText` element to be `Top traffic source`

### Test Coverage

* Update failing tests.
* Update VRT images.

## QA Brief

* Set up SK with the `userInput` feature flag enabled.
* Setup Key Metrics.
* Compare the KM widget tiles' title text with the Metrics Selection Panel titles.
* Verify that all the title text in the dashboard widget tiles and the selection panel match.
* Verify that the Metrics Selection Panel title text doesn't overlap with the accordion's chevron icon when the text extends too long, as observed in this [comment](https://github.com/google/site-kit-wp/issues/7451#issuecomment-1691370600).

**Update**
Verify that the Metrics Selection Panel displays `Top performing keywords` text instead of `How people find your site` as observed in QA. Please refer to this [comment](https://github.com/google/site-kit-wp/issues/7451#issuecomment-1697150174).

## Changelog entry

* Update text used in metrics slide-out panels to match widget names.

**Comment by marrrmarrr** [comment]
Let's keep the naming that currently appears on the dashboard.

**Comment by bethanylang** [comment]
Thanks @marrrmarrr! One minor thing: it looks like only one of the dashboard metrics titles, Top Traffic Source, is capitalized, while all others aren't. Should we change that one so to "Top traffic source" in the dashboard so that only the first word is capitalized on all metrics? Thanks!

**Comment by techanvil** [comment]
AC :white_check_mark: (nb, I updated it to read a bit more like AC than instructions).

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by hussain-t** [comment]
@jimmymadon @bethanylang, while working on the execution, I noticed a UI problem: the title text in the Metrics Selection Panel overlaps with the accordion's chevron icon when the text extends too long. I will address this issue as part of the current task rather than creating a separate ticket, which would save us some time.

<img width="404" alt="Screenshot 2023-08-24 at 3 14 08 PM" src="https://github.com/google/site-kit-wp/assets/24408261/5acc74cc-c199-4aaf-9bf6-676a512e9a1f">

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t I have noticed that `Top performing keywords` dashboard tile is showing up as `How people find your site` in the metrics panel. I am assuming that's not correct? 

![image](https://github.com/google/site-kit-wp/assets/73545194/582f2487-1a93-4cf9-9161-f7c97a06280a)

**Verified:**

The Metrics Selection Panel title text doesn't overlap with the accordion's chevron icon when the text extends too long, as observed in this https://github.com/google/site-kit-wp/issues/7451#issuecomment-1691370600.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/65f9aeb7-e6cb-4e13-bb34-b60125930f24)
![image](https://github.com/google/site-kit-wp/assets/73545194/4e910841-a725-4046-9048-159faeed9adf)
![image](https://github.com/google/site-kit-wp/assets/73545194/b80f12f0-3ce3-48e6-b2cc-b3ca49cea772)
![image](https://github.com/google/site-kit-wp/assets/73545194/ef04d638-8cc8-4ad0-a3be-448d9310b90d)

</details>

**Comment by hussain-t** [comment]
Thanks for spotting this, @wpdarren. It was missed in the description and the IB. I will create a follow-up PR to fix it.

**Comment by aaemnnosttv** [comment]
Back to you for another pass @wpdarren !

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Compared the KM widget tiles' title text with the Metrics Selection Panel titles: 
  - All the title text in the dashboard widget tiles and the selection panel match.
  - The Metrics Selection Panel title text doesn't overlap with the accordion's chevron icon when the text extends too long, as observed in this https://github.com/google/site-kit-wp/issues/7451#issuecomment-1691370600.
  - The title of the Top Traffic Source KMW tile is updated to Top traffic source.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/b97d7ddf-52bf-4866-a9e0-c195573d448a)
![image](https://github.com/google/site-kit-wp/assets/73545194/5b50cafc-5912-49da-9b2a-adad9756f1b8)
![image](https://github.com/google/site-kit-wp/assets/73545194/3c6b6fc8-bf35-494e-932d-91b7bb9a3c6b)
![image](https://github.com/google/site-kit-wp/assets/73545194/eb173612-e17b-499c-868e-757ba17622ed)
![image](https://github.com/google/site-kit-wp/assets/73545194/136284bf-a40f-4445-b5e4-a985952354cf)
![image](https://github.com/google/site-kit-wp/assets/73545194/0bd24c99-7a71-4476-8a8d-9eed1ec43e60)

</details>
