### ISSUE TITLE
On Question 2, hover state for radio buttons is not working

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7452]
## Bug Description

As reported by @sigal-teller in Bug Bash:

On Question 2 for the KMW user input, the hover state on Question 2 is not working.

## Steps to reproduce

1. Enable `userInputv2` feature flag and setup site kit with GA4.
2. Click on the "Get tailored metrics" CTA in the Key Metrics Setup Banner CTA.
3. On Question 1 of the survey, notice that you can "tab" through all the options via keyboard and hovering with the mouse highlights each option. Select any option and click "Next".
4. On Question 2, it is no longer possible to select a Radio option via the keyboard and hovering over the options with the mouse does not highlight any of the radio buttons.

## Screenshots

https://github.com/google/site-kit-wp/assets/1721319/e40d69e4-04e4-49b5-9dfc-bda37df19987

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Given the user is answering Question 2 of the User Input Questionnaire:
    * When the user hovers over the Radio options, these should be highlighted as per the Figma Mocks.
    * When the user presses the Tab key to navigate through the options, the Radio options should be highlighted and selectable via keyboard.

## Implementation Brief

* In `assets/js/components/user-input/UserInputQuestionnaire.js`:
    * Render each `UserInputQuestionWrapper` and the `UserInputSelectOptions` within it only when the `activeSlugIndex` is exactly equal to their step index instead of being `<=`.
* In `assets/js/components/user-input/UserInputQuestionWrapper.js`: 
    * Remove the `isActive` prop as the component will be rendered only when active. 
    * Remove `googlesitekit-user-input__question--next` and `googlesitekit-user-input__question--active` class from the rendered `div`. Refactor their usage in styles and tests to use the base `googlesitekit-user-input__question`.
* In `assets/js/components/user-input/UserInputSelectOptions.js`:
    * Remove the `isActive` prop for the same reason and refactor it's usage assuming `isActive = true`.
* Remove the usage of `isActive` prop in `UserInputQuestionnaire` and `UserInputPreviewGroup`.
* In `assets/sass/components/user-input/googlesitekit-user-input-questions.scss`:
    * Remove unneeded CSS rules from this file.

### Test Coverage

* Update any failing tests. 

## QA Brief

* The bug should no longer occur following the reproduce steps.
* Since there's been underlying changes, a regression testing of User Input questions and editing the answers in settings to make sure no regression happened would be useful. 

## Changelog entry

* Fix hover state and keyboard navigation for User Input radio buttons.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by kuasha420** [comment]
@techanvil Thank you for the review. All sorted. Please have a look. Cheers.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit since Arafat is OoO could I flag this observation with you. 

> On Question 1 of the survey, notice that you can "tab" through all the options via keyboard and hovering with the mouse highlights each option. Select any option and click "Next".

I am looking at the steps to reproduce but when question 1 loads, I am unable to tab through the options. I can if I use the arrow keys. If I do tab on load I am taken away from the survey and even when I continue to tab, the options are never highlighted to be selected.  It's a weird experience using the keyboard. 

I had a look at the latest version of the plugin (1.108.0) and also develop branch and the behaviour was the same. 

Am I missing something here? 

https://github.com/google/site-kit-wp/assets/73545194/31194ab7-2148-4096-8056-9bd6d9369ba4

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The bug no longer occurs following the reproduce steps.
- Completed regression testing of User Input questions and editing the answers in settings using keyboard and mouse.

![image](https://github.com/google/site-kit-wp/assets/73545194/92121172-a91b-44e3-b0a1-5af03fe2ac48)

**Comment by nfmohit** [comment]
Just to add to @wpdarren's question above, for future context, this is the correct behaviour according to w3.org. The Tab key lets you navigate between the radio group and other form groups. While on a radio group, up and down arrow keys let you navigate between the radio buttons for that group. More information [here](https://www.w3.org/wiki/RadioButton#:~:text=When%20focus%20moves%20to%20the,radio%20buttons%20in%20the%20group.).
