### ISSUE TITLE
Add "Enable enhanced measurement" toggle to Analytics Setup and Settings pages.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7459]
## Feature Description

Create the "Enable enhanced measurement" toggle, and replace the "Enable Universal Analytics" toggle with this new component on the Analytics Setup and Settings pages, as illustrated here on the Setup page. Note that this is an early mockup, please refer to the AC for the correct copy:

![image](https://github.com/google/site-kit-wp/assets/18395600/172d6b84-ea76-46ec-b243-25e9bb65c749)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The following changes should be behind the new `enhancedMeasurement` feature flag added via https://github.com/google/site-kit-wp/issues/7470.
- The "Enable Universal Analytics" toggle on the Analytics Setup and Settings pages should be replaced with a new "Enable enhanced measurement" toggle.
- The "Enable enhanced measurement" toggle's copy and "Learn more" link should be as follows:
  - Label: _Enable enhanced measurement_
  - Description: _Automatically measure interactions with your content (e.g. file downloads, form completions, video views). No extra code required._
  - "Learn more" link target: https://support.google.com/analytics/answer/9216061
- The layout and styling should be consistent with the existing "Enable Universal Analytics" toggle.

### Setup page

- The toggle should default to _on_, and should reset to _on_ any time an account/property/web data stream option is selected from one of the dropdowns, including the options to create a new property or data stream.
  - Note, the case where a new account is created will be handled in a separate issue (see #7460).
- When the **Configure Analytics** CTA is clicked, the selected (or newly created) web data stream should have enhanced measurement enabled/disabled according to the toggle value, via a call to the relevant API (see #7458).
- In the case where the user is redirected to the OAuth flow, it must be ensured that the "Enable enhanced measurement" toggle retains its state upon return to Site Kit.

### Settings page

- When the page is first displayed, or when a web data stream is selected via the dropdowns, the toggle state should default/reset to the enhanced measurement state of the selected data stream as it's currently set on the GA4 service. I.e. it should reset to be _on_ if enhanced measurement is enabled for the data stream, _off_ if not.
- The toggle should show a loading state while the selected web data stream's enhanced measurement settings are retrieved via the relevant API call.
  - This should only be needed the first time a given data stream is selected.
  - The loading state should take the form of a small progress bar replacing the toggle and label, while the description remains visible.
- When one of the dropdown options to create a property or web data stream is selected, the toggle should reset to _on_.
  - Note, the case where a new account is created will be handled in a separate issue (see #7460).
- The **Confirm Changes** CTA's disabled state should reflect the "changed" state of the toggle. I.e., if no changes are made to any of the controls, the **Confirm Changes** CTA should remain disabled. If the user then switches the toggle, the **Confirm Changes** CTA should become enabled.
- When the **Confirm Changes** CTA is clicked, the selected (or newly created) web data stream should have enhanced measurement enabled/disabled according to the toggle value, via a call to the relevant API.
- In the case where the user is redirected to the OAuth flow, it must be ensured that the "Enable enhanced measurement" toggle retains its state upon return to Site Kit.

#### Create the toggle component

- In `assets/js/modules/analytics-4/datastore/constants.js`:
  - Create a new constant to use with the `CORE_FORMS` datastore in order to keep track if the user chooses to enable enhanced measurement for the current data stream, say `ANALYTICS_ENHANCED_MEASUREMENT` with a value like `analytics-enhanced-measurement`.

- Create `assets/js/modules/analytics-4/components/common/EnhancedMeasurementSwitch.js`. In this file:
  - Export a component with the same name.
  - It should be similar to the GA4 `UseSnippetSwitch` component (located in `assets/js/modules/analytics-4/components/common/UseSnippetSwitch.js`).
  - It should accept a boolean `loading` prop which defaults to `false`.
  - It should render a `Switch` component with label as mentioned in the ACs.
    - Its `checked` prop should depend on the value of `ANALYTICS_ENHANCED_MEASUREMENT` form's `enabled` key. It can be obtained using the `CORE_FORMS` `getValue` selector, passing the form name `ANALYTICS_ENHANCED_MEASUREMENT` and form data key `enabled` as parameters respectively.
    - `onClick`:
      - Dispatch the `CORE_FORMS` `setValues` action, with `ANALYTICS_ENHANCED_MEASUREMENT` as the form name. As the form data, pass the `enabled` key with a boolean value based on the checked state of the `Switch`.
    - The `Switch` component should be replaced with a small `ProgressBar` ([example](https://github.com/google/site-kit-wp/blob/5925421c9eda03d262f6b6037d38b4cc68d41c1a/assets/js/modules/analytics-4/components/common/PropertySelect.js#L125)) if the `loading` prop supplies `true`.
  - Unlike the GA4 `UseSnippetSwitch` using a `description` prop, it should render a `<p>` tag with the description.
    - The description should be suffixed by a learn more link as mentioned in the ACs using the `SupportLink` component.

#### Use it in Analytics setup

- Create `assets/js/modules/analytics-4/components/setup/SetupEnhancedMeasurementSwitch.js`. In this file:
  - Export a component with the same name.
  - Render the new `EnhancedMeasurementSwitch` component.
  - Using a `useEffect` hook, fire a function that runs whenever an account/property/web data stream is selected, even for initial (auto) selection. The function should dispatch the `CORE_FORMS` `setValues` action with `ANALYTICS_ENHANCED_MEASUREMENT` as the form name. As the form data, pass the `enabled` key with a value of `true` so that enhanced measurements is turned on.
- In `assets/js/modules/analytics/components/setup/SetupFormGA4.js`:
  - If the `enhancedMeasurement` feature flag is enabled:
    - Place the new `SetupEnhancedMeasurementSwitch` component right after the snippet switch.
    - Do not render the `EnableUniversalAnalytics` component.

#### Use it in Analytics settings

- Create `assets/js/modules/analytics-4/components/settings/SettingsEnhancedMeasurementSwitch.js`. In this file:
  - Export a component with the same name.
  - Render the new `EnhancedMeasurementSwitch` component.
    - Pass a `loading` prop to it with the value of `true` if `MODULES_ANALYTICS_4` `getEnhancedMeasurementStreamSettings` selector is being resolved, with the current property and web data stream IDs as arguments.
  - Using a `useEffect` hook, fire a function that runs whenever the selected property/web data stream is changed. The function should do the following:
    - If the user chooses to create a new property/web data stream (this can be observed by checking if `MODULES_ANALYTICS_4` `getPropertyID` or `getWebDataStreamID` equals to constants `PROPERTY_CREATE` or `WEBDATASTREAM_CREATE` respectively), dispatch the `CORE_FORMS` `setValues` action with `ANALYTICS_ENHANCED_MEASUREMENT` as the form name. As the form data, pass the `enabled` key with a value of `true` so that enhanced measurements is turned on.
    - Otherwise, if the user chooses any other valid property/web data stream, dispatch the `CORE_FORMS` `setValues` action with `ANALYTICS_ENHANCED_MEASUREMENT` as the form name. As the form data, pass the `enabled` key. The value of the `enabled` key can be obtained by using the `MODULES_ANALYTICS_4` `isEnhancedMeasurementStreamEnabled` selector, passing the current property ID and web data stream ID as parameters respectively.
- In `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`:
  - If the `enhancedMeasurement` feature flag is enabled, place the new `SettingsEnhancedMeasurementSwitch` component right after the snippet switch.
- In `assets/js/modules/analytics/components/settings/SettingsForm.js`:
  - If the `enhancedMeasurement` feature flag is enabled, do not render the `EnableUniversalAnalytics` component.

#### Save the setting

- In `assets/js/modules/analytics-4/datastore/settings.js`:
  - All changes here should be made if the `enhancedMeasurement` feature flag is enabled.
  - Update the `submitChanges` function:
    - Towards the end of the function, dispatch the `MODULES_ANALYTICS_4` `setEnhancedMeasurementStreamEnabled` action with the current property ID, web data steam ID, and value of `ANALYTICS_ENHANCED_MEASUREMENT` form's `enabled` key respectively as parameters.
    - Afterwards, check if the enhanced measurements settings have changed using the `MODULES_ANALYTICS_4` `haveEnhancedMeasurementSettingsChanged` selector, passing the current property and web data stream IDs as parameters respectively.
    - If `true`, dispatch the `MODULES_ANALYTICS_4` `updateEnhancedMeasurementSettings` action, passing the current property and web data stream IDs as parameters respectively.
  - Update the `validateCanSubmitChanges` function to throw an `invariant` exception if enhanced measurement settings have not changed, using the `MODULES_ANALYTICS_4` `haveEnhancedMeasurementSettingsChanged` selector as above (passing the current property and web data stream IDs).
  - Update the `rollbackChanges` function:
    - Towards the end of the function, dispatch the `MODULES_ANALYTICS_4` `resetEnhancedMeasurementSettings` action.

### Storybook

- Add a Storybook story for the new `EnhancedMeasurementSwitch` component.

### Test Coverage

- Add test case(s) for the `EnhancedMeasurementSwitch` component.
- Add test case(s) for the `SetupEnhancedMeasurementSwitch` component to verify the `useEffect` behavior.
- Add test case(s) for the `SettingsEnhancedMeasurementSwitch` component to verify the `useEffect` behavior and the loading state.
- In `assets/js/modules/analytics-4/datastore/settings.test.js`:
  - Update relevant test cases to updated settings functions.
- Update VRT scenarios for available Analytics setup & setting screens now containing the `EnhancedMeasurementSwitch` component.

## QA Brief

- Setup Site Kit with the `enhancedMeasurement` feature flag enabled and connect GA4.
- Ensure that the "Enable enhanced measurement" toggle appears on both the Analytics Setup and Settings screens.
  - Bear in mind that the "Create Account" case will be handled in a separate issue, https://github.com/google/site-kit-wp/issues/7460 so the EM toggle will only appear on the Setup/Settings screens with the dropdowns for now.
- Verify that it works as expected and described in the ACs.
- Check that it works as expected in scenarios where the user doesn't have permission to the property. Try saving the settings in these scenarios where the UI allows it. Scenarios include but need not be limited to:
  - Connecting a property that the user has been granted access to in Analytics and then removing the permission. The expected behaviour, upon refreshing the page, is that the toggle is still active here although it won't have any particular effect.
  - Connecting a property as one admin, then logging in as a second admin who doesn't have access to it. The expected behaviour here is that the toggle is disabled, as are the dropdowns. The toggle will be in the off state, and won't necessarily reflect the state of the connected data stream as the user doesn't have access to the property to retrieve it.
- Model error states for the `GET/POST enhanced-measurement-settings` endpoint, for example by using the Chrome devtools to block the requests, or by using the Tweak Chrome extension to mock more explicit error states.
  - The path for the requests is `/wp-json/google-site-kit/v1/modules/analytics-4/data/enhanced-measurement-settings`
  - In the case of an error, we may expect to see the error message displayed on the screen while the toggle is still interactive, but changing it doesn't enable the "Confirm Changes" CTA. This is as expected because we have been unable to retrieve the current setting so can't reasonably determine whether a change has been made locally.
  - See [this issue](https://github.com/google/site-kit-wp/issues/7453) for a bit of detail about using Tweak in the QAB.
- Check that the OAuth flow is correctly triggered for both the Setup and Settings flows.
  - Note that the "Additional permissions required" modal is expected to appear as usual.
  - When testing the Settings flow, an easy way to remove the edit scope is to disconnect and reconnect the plugin.
- While testing, check that the setting has been correctly saved by viewing the "Web stream details" on Analytics for the selected data stream.
![image](https://github.com/google/site-kit-wp/assets/18395600/c658b0ec-282a-4a58-af04-232546796321)

## Changelog entry

- Add the "Enable enhanced measurement" toggle to Analytics.

**Comment by techanvil** [comment]
Hi @nfmohit, thanks for drafting this IB, it's definitely off to a good start.

However, and sorry for not recognising this during our conversation earlier, but I've realised there's a potential issue with `EnhancedMeasurementSwitch` as specced.

Essentially, we need to consider the behaviour when `getPropertyID()`/`getWebDataStreamID()` return `PROPERTY_CREATE`/`WEBDATASTREAM_CREATE`, as don't want to then invoke `isEnhancedMeasurementStreamEnabled()` with these args _without_ having already called `setEnhancedMeasurementStreamEnabled()`, as this will result in a call to the GA4 `getEnhancedMeasurementSettings` endpoint with those strings, which will obviously return an error.

Actually, this reminds me of an approach I had in mind for the IB while writing up the AC - whereby we create say `EnhancedMeasurementSwitch` which has a simple `checked` boolean prop and `onChange` callback prop, and then create a `SetupEnhancedMeasurementSwitch` and `SettingsEnhancedMeasurementSwitch` each of which encapsulates the appropriate logic for handling `PROPERTY_CREATE`/`WEBDATASTREAM_CREATE` vs real IDs, so that we don't end up calling `getEnhancedMeasurementSettings()` with the `CREATE` strings as args.

As mentioned above, although we _can_ use `isEnhancedMeasurementStreamEnabled()` with the `CREATE` strings, we need to make sure that's only _after_ we've called `setEnhancedMeasurementStreamEnabled()` with those strings, otherwise the resolver will see the state as not being populated and will hit the backend. Alternatively, it could be cleaner to instead introduce a new action/selector pair & state for this special case to make things more explicit and avoid potentially falling into a trap in a future update.

Aside from the above, it's a small detail but as these are all GA4 specific components we should really create the components under `assets/js/modules/analytics-4/`.

**Comment by nfmohit** [comment]
Thank you for the kind review, @techanvil. As discussed on our sync today, I have updated the IB to use a `CORE_FORMS` datastore form to store if the user has chosen to enable enhanced measurement, and use that value within `submitChanges` to update the setting. Please let me know if this looks good.

Thank you!

**Comment by techanvil** [comment]
Thanks @nfmohit! This is looking great. I do have a few further suggestions:

- I still think that even with this new approach it would benefit from having separate `SetupEnhancedMeasurementSwitch` and `SettingsEnhancedMeasurementSwitch` components. That way, there can be a single feature flag check to determine whether the component is actually rendered, and all the additional selectors, `useEffect()` conditions etc will automatically be behind the flag.
- When checking for the loading state, we'll actually need to check for the `getEnhancedMeasurementStreamSettings()` selector being resolved, as that's what `isEnhancedMeasurementStreamEnabled()` will call behind the scenes.
- We shouldn't need to manually call `snapshotAllStores()` in `submitChanges()`, that should be taken care of for us by the ['AuthenticatedPermissionsModal'](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js#L62) that will appear when the API call fails due to insufficient scopes.
- I think we should unconditionally call `resetEnhancedMeasurementSettings()` in `rollbackChanges()` rather than checking `haveEnhancedMeasurementSettingsChanged()`, just as a bit of a catchall.

**Comment by nfmohit** [comment]
I have taken your kind suggestions into consideration and updated the IB accordingly. Please let me know if it looks good now. Thank you for the help and patience on this, @techanvil!

**Comment by mohitwp** [comment]
### QA Update ❌ 

@techanvil 

- Tested on dev environment.
- Verified `enhancedMeasurement` toggle as per AC.

**Issue** > On Settings page - "Confirm Changes" button if gets enabled once then not change it's state again as per `enhancedMeasurement` toggle selection.

<details>


https://github.com/google/site-kit-wp/assets/94359491/26a45116-83ae-4de5-868e-046f94329813

</details>

**Issue 2**> As per QAB - `_In the case of an error, we may expect to see the error message displayed on the screen while the toggle is still interactive, but changing it doesn't enable the "Confirm Changes" CTA. This is as expected because we have been unable to retrieve the current setting so can't reasonably determine whether a change has been made locally._`

In above case 'Confirm Changes" CTA remains active.

<details>



https://github.com/google/site-kit-wp/assets/94359491/96b4ff81-1969-495d-b1d9-dee08dcc859d

</details>

Screencast for pass cases-

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/3aeb7c85-b3da-47d3-ad88-b25a7e9bcc31)


https://github.com/google/site-kit-wp/assets/94359491/6ff0e692-c3dc-4c52-a9e3-3334331c5303


https://github.com/google/site-kit-wp/assets/94359491/531483fa-a7c3-4ed4-9498-3a72f43e396f


https://github.com/google/site-kit-wp/assets/94359491/3ad0231e-f82b-4d74-81cb-be4e67f1f2cd


https://github.com/google/site-kit-wp/assets/94359491/3b8d40ae-0698-4c6d-b7ad-596156da59e0

</details>

**Comment by techanvil** [comment]
Thanks @mohitwp!

> **Issue** > On Settings page - "Confirm Changes" button if gets enabled once then not change it's state again as per `enhancedMeasurement` toggle selection.

Great catch here - I've created a followup PR to address this.

> **Issue 2**> As per QAB - `_In the case of an error, we may expect to see the error message displayed on the screen while the toggle is still interactive, but changing it doesn't enable the "Confirm Changes" CTA. This is as expected because we have been unable to retrieve the current setting so can't reasonably determine whether a change has been made locally._`
> 
> In above case 'Confirm Changes" CTA remains active.

From your screencast, it looks like you're modelling the error for the `POST` response. I should have been clearer in the QAB, but the described behaviour is what should happen if the `GET` fails, where the setting can't be initially determined. Please can you retry, but changing the `POST` to `GET` in your Tweak settings and see how you get on.

**Comment by aaemnnosttv** [comment]
Back to you for another pass @mohitwp 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @techanvil !

- Tested on main environment.
- Verified `enhancedMeasurement `toggle as per AC.
- Verified all condition mentioned under AC for both setup and settings page.
- Verified issues reported [above](https://github.com/google/site-kit-wp/issues/7459#issuecomment-1743014030) are resolved.
- Issue 1 : - Fixed.
- Issue 2 :- Not appearing when Http request is 'Get'.

<details>


https://github.com/google/site-kit-wp/assets/94359491/b58b7686-b943-4c26-9f71-01265dde9b94


https://github.com/google/site-kit-wp/assets/94359491/810adb3a-e563-4c90-aec3-011e538b5bdb

</details>

Screencast for pass cases-

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/3aeb7c85-b3da-47d3-ad88-b25a7e9bcc31)


https://github.com/google/site-kit-wp/assets/94359491/6ff0e692-c3dc-4c52-a9e3-3334331c5303


https://github.com/google/site-kit-wp/assets/94359491/531483fa-a7c3-4ed4-9498-3a72f43e396f


https://github.com/google/site-kit-wp/assets/94359491/3ad0231e-f82b-4d74-81cb-be4e67f1f2cd


https://github.com/google/site-kit-wp/assets/94359491/3b8d40ae-0698-4c6d-b7ad-596156da59e0

</details>
