### ISSUE TITLE
Apparent token error with "Start Setup" and a domain that does not belong to me

### ISSUE THREAD

**Issue by antoniomanco** [google/site-kit-wp#746]
## Bug Description

Apparently there is a strange confusion of tokens every time I try to start "Start Setup" of Google Site Kit. Suddenly the application takes me to other domains and not to my website.

## Steps to reproduce

1. Go to 'Site Kit Dashboard'
2. Click on '.Start Setup'
3. I see "Welcome to Site Kit! Let's get you set up".
4. But I see another domain that is not mine (attached below two screenshots)

## Screenshots

![image](https://user-images.githubusercontent.com/56943123/67832214-eb460980-faae-11e9-883f-c5ece2f3edcd.png)

![image](https://user-images.githubusercontent.com/56943123/67832247-09136e80-faaf-11e9-82d9-ffaec901008a.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by denisciumbargi** [comment]
Same here, random domain when trying to generate token to connect site

**Comment by jamesozzie** [comment]
@antoniomanco @denisciumbargi There may be browser caching (or plugins) interfering with setup. Can you attempt the following steps to get it working:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)

If the above fails to resolve your issue can you please share the following:
- Any [console errors](https://i.imgur.com/KyLAzgH.png) that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by antoniomanco** [comment]
Hello 

I followed his instructions deactivating plugins and clearing cache, then everything was working fine and a few hours later I received "Unable to receive access token because of an invalid authorization code or refresh token", and Google Adsense is no longer connected. When I try to connect I receive "Data error in AdSense
AdSense account ID not set ". Should I deactivate the cache plugins again and repeat everything again? I am using UpdraftPlus and Wp Fastest Cache.

![image](https://user-images.githubusercontent.com/56943123/67871571-916d3000-fafe-11e9-828d-caadbe48cefe.png)

**Comment by jamesozzie** [comment]
@antoniomanco Can you disconnect the AdSense module before attempting to connect again? If you want to share your site I can see if I can spot anything from my side.

**Comment by Kevin-Abrams** [comment]
I am having this same issue. It is happening on more than one site. Specifically sites that where already running sitekit then were updated. The update asks me to revalidate and the domain is not mine.

**Comment by jamesozzie** [comment]
@antoniomanco @Kevin-Abrams Can you share the following in order to troubleshoot further?
- Your [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any [console errors](https://i.imgur.com/KyLAzgH.png) you see once directed back to your Site Kit dashboard
- [XHR Response](https://i.imgur.com/jLBwBdH.png) on the same page where you see any error message

**Comment by ernee** [comment]
@antoniomanco @denisciumbargi @Kevin-Abrams thanks for your reports thus far. We're investigating the issue. 

Additionally, would it be possible for you to send a screencast of the setup process when you get the issue (you could use something like [Recordit](https://recordit.co/) to share it with us)? What we're looking for is the URLs at each step in the address bar. You can also provide the URLs at each step leading to the incorrect domain name showing.

**Comment by antoniomanco** [comment]
Hello Renee. The latest Version 1.0.0 of the Google Site Kit has now solved these problems, now everything is stable and my Analytics, Adsense, Page Speed, Search Console and Optimize services work fine.

**Comment by ernee** [comment]
Thanks for the update @antoniomanco! Happy to hear things are on track. @denisciumbargi and @Kevin-Abrams if you could update to version 1.0.0 now available in the [plugin repository](https://wordpress.org/plugins/google-site-kit/), it should resolve this issue. Feel free to open a [support topic in the forums](https://wordpress.org/support/plugin/google-site-kit/) if you have any further questions or concerns . Thanks again!
