### ISSUE TITLE
Add "Enable enhanced measurement" toggle to Analytics "Create Account" pages.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7460]
## Feature Description

Add the "Enable enhanced measurement" toggle to the Analytics Create Account page.

![image](https://github.com/google/site-kit-wp/assets/18395600/91c6d76a-f4c3-49b6-bf7c-9c6205e75abf)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The following changes should be behind the `enhancedMeasurement` feature flag.
- The "Enable enhanced measurement" toggle created in #7459) should be added to the Create Account page for both the Analytics Setup and Settings flows.
- The toggle should default to _on_.
- It should be positioned below all of the dropdowns as per the mockup above.
- When the **Create Account** CTA is clicked and the user goes through the Terms of Service flow and accepts the ToS, upon returning to Site Kit, when the account is provisioned on the backend, the newly created web data stream's enhanced measurement should be enabled/disabled as per the toggle on the Create Account page.

## Implementation Brief

Ensure these changes are behind the `enhancedMeasurement` feature flag.

- Within `assets/js/modules/analytics/components/common/AccountCreate/index.js`:
  - Render the `EnhancedMeasurementSwitch` component created via #7459.
  - In a `useMount()` callback, dispatch the `CORE_FORMS` `setValues()` action to set `enabled` to `true` for the `ANALYTICS_ENHANCED_MEASUREMENT` form as described in #7459, in order to default the toggle to _on_.
- Make any styling adjustments necessary to ensure the component is laid out well on the page with consistent vertical margins between it and the surrounding elements.

- Within the GA4 [`*createAccount()`](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/modules/analytics-4/datastore/accounts.js#L98) action:
  - Retrieve the `ANALYTICS_ENHANCED_MEASUREMENT` `enabled` value and set it as a property named `enableEnhancedMeasurement` in the `data` object passed to `fetchCreateAccount()`.

- Within `includes/Modules/Analytics_4.php`:
  - Update the `parse_data_response()` method's case for `POST:create-account-ticket` to set an additional transient to track the provided `enableEnhancedMeasurement` value for the current user. This should be implemented in the same way as the existing [`PROVISION_ACCOUNT_TICKET_ID`](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/includes/Modules/Analytics_4.php#L814-L818) transient, with the user ID as part of the transient name and an expiry time of 15 minutes.
  - In the `handle_provisioning_callback()` method, retrieve the `enableEnhancedMeasurement` value from the above transient.
  - If it's true, then set the `streamEnabled` enhanced measurement setting for the created web data stream to `true` via the `getEnhancedMeasurementSettings()` method provided via the `PropertiesEnhancedMeasurementResource` instance of the `analyticsenhancedmeasurement` service as defined in #7458.

### Test Coverage

- All of the modified areas have existing test coverage which should be added to/updated.

## QA Brief

- This issue adds the enhanced measurement toggle switch to the Account Creation view for GA
- It should be fairly straight-forward to test according to the AC

## Changelog entry

- Add the "Enable Enhanced Measurement" option to Analytics when creating an account.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
Note that during execution we may need to take the same approach as seen here in `SetupEnhancedMeasurementSwitch` to ensure the switch isn't reverted to `true` on mount when returning from the OAuth flow.

https://github.com/google/site-kit-wp/blob/afe3e4f3e642375b5f69cc2ac42474a5b9038bc0/assets/js/modules/analytics-4/components/setup/SetupEnhancedMeasurementSwitch.js#L60-L69

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified Add "Enable enhanced measurement" toggle to Analytics appearing on "Create Account" pages.
- Verified when the Create Account CTA is clicked and the user goes through the Terms of Service flow and accepts the ToS, upon returning to Site Kit, when the account is provisioned on the backend, the newly created web data stream's enhanced measurement is enabled/disabled as per the toggle on the Create Account page.
- Verified "Enable enhanced measurement" toggle working as per AC.
- Tested for both condition when "Enable enhanced measurement" toggle is enabled and when it's disabled.


<details>


https://github.com/google/site-kit-wp/assets/94359491/e6e01231-a6cb-4902-b3c7-04c808cce61e


https://github.com/google/site-kit-wp/assets/94359491/c7593cb3-13b9-4adf-b0f4-d90f51e05485

</details>
