### ISSUE TITLE
Create and display the  "Enable enhanced measurement" notification banner.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7461]
## Feature Description

Create and show the "Enable enhanced measurement" banner, prompting users to enable enhanced measurement for their currently configured web data stream.

Note: These are mockups only, please refer to the AC for the correct copy.

![image](https://github.com/google/site-kit-wp/assets/18395600/be8442e3-85f9-4e06-b32e-90e2f20dbc4b)

The banner should have a second step, shown when the **Enable now** CTA is clicked and enhanced measurement is successfully enabled.

![image](https://github.com/google/site-kit-wp/assets/18395600/4a17bfc7-1c3f-4302-818a-d6b0660a91dc)

Clicking "Maybe later" on the first step should dismiss the banner and show a Settings tooltip:

![image](https://github.com/google/site-kit-wp/assets/18395600/cf380a38-4cc1-47a8-9567-444425c5bfb5)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new "Enable enhanced measurement" banner should be created, and displayed under the conditions defined below.
- The banner's copy and "Learn more" link should be as follows (all to-be-confirmed (<abbr title="To be confirmed">TBC</abbr>), cc @marrrmarrr):
  - Label: _Understand how visitors interact with your content_
  - Description: _Enable enhanced measurement in Analytics to automatically track metrics like file downloads, video plays, form interactions, etc. No extra code required._
  - Primary CTA: _Enable now_
  - Dismiss button: _Maybe later_
  - "Learn more" link target: https://support.google.com/analytics/answer/9216061
- The layout and styling should be consistent with the existing ["Switch to GA4 Dashboard View"](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-switchga4dashboardviewnotification--switch-ga-4-dashboard-view-notification-default) banner.
- The same graphic can be used as the "Switch to GA4 Dashboard View" banner, as illustrated in the mockup above.
- The banner should be shown when all of the following conditions are true:
  - The `enhancedMeasurement` feature flag is enabled (see https://github.com/google/site-kit-wp/issues/7470).
  - There is a currently configured web data stream.
  - The web data stream doesn't have enhanced measurement enabled.
  - The user has _not_ already interacted with the "Enable enhanced measurement" toggle on the Analytics Setup or Settings pages.
  - The banner has not already been dismissed.
- Clicking the **Enable now** CTA will enable enhanced measurement for the current web data stream and save the enhanced measurement settings, without taking the user to the Settings page.
  - A spinner will be shown in the button while the settings are being saved.
  - If there is an error due to a missing scope, the user will be redirected to the OAuth flow without showing the "Additional Permissions Required" modal, following the behaviour of the GA4 Activation Banner. Upon returning from the flow, the submission will continue automatically.
  - If there is another type of error, it will be shown in the usual error style, below the description and above the buttons.
  - Otherwise, the banner show the second stage, with a single CTA and copy as follows (all <abbr title="To be confirmed">TBC</abbr>, cc @marrrmarrr):
    - Label: _You successfully enabled enhanced measurement for your site_
    - Description: _Your configured Analytics web data stream will now automatically measure interactions on your site in addition to standard page views measurement._
    - Primary CTA: _OK, Got it_
    - "Learn more" link target: https://support.google.com/analytics/answer/9216061banner
  - Clicking the **OK, Got it** CTA will permanently dismiss the banner.
- Clicking the **Maybe later** button will dismiss the banner for a month, and show a tooltip pointing to the Settings menu item in the WP menu.
  - The tooltip's copy should be as follows (all <abbr title="To be confirmed">TBC</abbr>, cc @marrrmarrr):
    - Title: _Enable enhanced measurement later here_
    - Description: _You can always turn on enhanced measurement later in Site Kit Settings._
    - Dismiss button: _Got it_
  - Clicking "Got it" will close the tooltip.

## Implementation Brief

Structurally, this will take an approach similar to the [GA4 Activation Banner](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/index.js), with subcomponents for each of the two steps. It will also have similar logic for setting the current step, for handling the missing scope/OAuth flow, and for showing the Settings tooltip. However, the logic will be simpler as there are no separate Reminder and Setup steps.

- Three new components should be created in the new folder `assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/`:
  - `EnhancedMeasurementActivationBanner` in `index.js`.
  - `SetupBanner` and `SuccessBanner` in files named after the components.

### `EnhancedMeasurementActivationBanner`

- As the container/parent component, this should:
  - Determine whether to render the banner at all, according to the conditions defined in the AC and whether the tooltip is showing.
  - Keep track of the current step.
  - Conditionally render the tooltip or the current step subcomponent.

#### Conditionally render the banner

- Check if the conditions as defined in the AC are present, or whether the tooltip is showing.
  - Note that the feature flag condition can be checked outside of this component at the point where it's rendered.
  - Also, the check for the user not having interacted with the "Enable enhanced measurement" toggle can be managed by setting the banner to dismissed at the point that a toggle value is saved.
    - Take a similar approach to [`SwitchGA4DashboardViewNotification`](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/components/notifications/SwitchGA4DashboardViewNotification.js#L93-L97), using a separate dismissable item to track the dismissed state.
    - Permanently dismiss the item in `submitChanges()` when the call to `updateEnhancedMeasurementSettings()` is successfully made (see #7459).
- So, if _any_ of the following are _not_ true, then render `null`.
  - There's a current, valid web data stream ID, check via `getWebDataStreamID()` / `isValidWebDataStreamID()`.
  - The enhanced measurement state for the web data stream is resolved, and it isn't enabled _when its first resolved_; we need to keep track of the state of `streamEnabled` when it's first resolved, in order that we can continue to show the Success step once EM _has_ been enabled. Use a ref to keep track of the first-resolved state.
  - The tooltip is visible - check `isTooltipVisible` from `useTooltipState()` (see below).
  - The banner's dismiss item has not already been dismissed.

#### Render the tooltip.

- Use the `useTooltipState()` and `useShowTooltip()` hooks to manage the tooltip state.
- Retrieve `isTooltipVisible` from `useTooltipState()`, and if it's true, render the `AdminMenuTooltip` component with the copy as defined in the AC.
- See [`ReminderBanner`](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js#L76-L82) for an working example of the above.

#### Render the current step

- Create a state variable for the current step, defaulting to the Setup step.
- If `isTooltipVisible` is false:
  - Render either the `SetupBanner` or `SuccessBanner` component depending on the step state variable.
  - Pass an `onSuccess` callback prop to `SetupBanner` which sets the current step to Success.
  - Pass an `onDismiss` callback prop to `SetupBanner` which calls the `showTooltip()` handler returned by `useShowTooltip()`, and dismisses the dismissable item described under **Conditionally render the banner** above, with the expiry time of `getTimeInSeconds( 'month' )`.

#### Render the banner itself

- If the `enhancedMeasurement` feature flag is enabled, render the `EnhancedMeasurementActivationBanner` immediately below the `ActivationBanner` in [`BannerNotifications`](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/components/notifications/BannerNotifications.js#L116).

### `SetupBanner`

- Render a `BannerNotification` with the content as defined in the AC.
- Use a `SpinnerButton` as the [CTA component](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js#L372-L379).
- In the CTA click handler, first check if the user has the Analytics _edit_ scope.
  - If so:
    - Dispatch the `setEnhancedMeasurementStreamEnabled()` action to set the `streamEnabled` value, and then `updateEnhancedMeasurementSettings()` to save the settings.
    - Invoke the `onSuccess` callback prop.
  - If not:
    - Set the `FORM_SETUP` `autoSubmit` value to `true` and set a permission scope error with `skipModal: true` in order to trigger the OAuth flow. Make sure the redirect URL is correctly set and that the banner will display upon return to Site Kit.
    - Refer the GA4 Activation Banner [`SetupBanner`](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js#L180-L261) component for a working example of the above.
- Pass the `SetupBanner`'s `onDismiss` prop through to `BannerNotification`.

### `SuccessBanner`

- Render a `BannerNotification` with the content as defined in the AC.
- In the CTA click handler, permanently dismiss the dismissable item.

### Test Coverage

- Add stories with VRT scenarios for the `SetupBanner` and `SuccessBanner` components.
- Add JS test coverage for the `EnhancedMeasurementActivationBanner` component to verify it renders the correct steps under the relevant conditions.
- Add some JS test coverage for the form submission aspect of `SetupBanner` (see the GA4 Activaton Banner [`SetupBanner.test.js`](https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.test.js#L0-L1)).

## QA Brief

- Setup Site Kit with the `enhancedMeasurement` feature flag enabled and connect GA4.
- Verify that the banner appears and behaves as described in the AC, with the following amendments:
  - As discussed on [Slack](https://10up.slack.com/archives/CFFRMC5DE/p1696002454202519) the first stage of the banner has a copy variant in the case where the edit scope is not yet granted, in which case it should read as follows:
    - _Enable enhanced measurement in Analytics to automatically track metrics like file downloads, video plays, form interactions, etc. No extra code required — you’ll be redirected to give permission for Site Kit to enable it on your behalf._
  - It should also include the following text below the CTA button: _You can always add/edit this in the Site Kit Settings_
![image](https://github.com/google/site-kit-wp/assets/18395600/5b98539a-d94e-4d73-a49b-203f4789c3fd)
- Note that if an error occurs when retrieving the EM settings via the `GET enhanced-measurement-settings` endpoint, we can't determine whether the setting is enabled and the banner will not be shown. However if an error is returned by the `POST` request, the error should appear as per the AC. The error state for the `POST enhanced-measurement-settings` endpoint can be modelled, for example by using the Chrome devtools to block the requests, or by using the Tweak Chrome extension to mock more explicit error states. The path for the request is `/wp-json/google-site-kit/v1/modules/analytics-4/data/enhanced-measurement-settings`.
![image](https://github.com/google/site-kit-wp/assets/18395600/5108432d-dfe7-4267-a0b6-067345aab0f8)
- To verify the dismissal expiry time has been set correctly, check the `googlesitekitpersistent_dismissed_items` user meta option in the DB, _and_ the `notification::dismissed::googlesitekit-enhanced-measurement-activation-banner` value in the browser's session storage, as both are in play due to a quirk of the `BannerNotification` component. They should both have a unix timestamp of a month in the future for the "Mayber later" case, or zero for the permanent dismissal case. For the non-zero value, it's acceptable for the two values to be out by a few seconds.

## Changelog entry

- Add notification banners for Analytics Enhanced Measurement feature.

**Comment by techanvil** [comment]
It's just occurred to me, this either needs some sort of "success" message rather than simply dismissing the banner, or alternatively the CTA could navigate to the Settings page, with a tooltip pointing to the toggle...

**Comment by techanvil** [comment]
Update: I've added a second step with a "success" message, similar to the GA4 Activation Banner...

**Comment by techanvil** [comment]
I've further updated the AC to specify the behaviour relating to a missing scope and the OAuth flow.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
@techanvil @marrrmarrr  I am testing this ticket but have a quick observation - the learn more link on the banner points to a [support page](https://support.google.com/analytics/answer/9216061?hl=en) on how to set up enhanced measurement within Analytics. I wonder if this will confuse the user?  Do you think we should link to a support page on the Site Kit as part of the documentation to avoid any confusion?  I am assuming Adam or James will be writing documentation for this epic.

**Comment by bethanylang** [comment]
@wpdarren :wave: Can confirm that the support team is working on documentation for this. That said, it will be very brief as all they can do within SK is toggle it on or off, and our plan is to point our guide out to the same URL in the plugin since that provides more detailed information. So personally, I think it makes sense to keep this link as is.

BTW, please always feel free to tag me in on questions around documentation as I maintain my role as support lead alongside being the SK PM, so I'm aware of what plans are for that kind of thing. Thanks!

**Comment by techanvil** [comment]
Thanks for flagging this @wpdarren, and for your reply @bethanylang! That being the case, keeping the link as-is SGTM too.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@techanvil I have an observation to share:

AC says:
> If there is an error due to a missing scope, the user will be redirected to the OAuth flow without showing the "Additional Permissions Required" modal, following the behaviour of the GA4 Activation Banner. Upon returning from the flow, the submission will continue automatically.

I have set up Site Kit and Analytics with a user that only as 'view only' access on the account.  The correct banner appears with the additional text as per the QAB. 

![image](https://github.com/google/site-kit-wp/assets/73545194/f7d3d581-5907-44d2-86da-8ff474f32cc0)

When I click on the `Enable now` CTA, I am redirected to give oAuth permissions and no popup modal appears. I give permission, and the flow looks fine, until when I get back to the Site Kit dashboard and a message appears: `Error: The caller does not have permission` and I am unable to continue to enable enhanced measurement.  

![image](https://github.com/google/site-kit-wp/assets/73545194/981b9525-dcb5-4970-a0f0-e501509e8624)

Whenever I click the CTA, the same error occurs. 

From reading the AC, this shouldn't occur, and I should now ave permission to edit so I can enable enhanced measurements.

Interested in your thoughts here.

**Comment by techanvil** [comment]
Hi @wpdarren, thanks for testing this and raising these observations. The behaviour you've described does appear to be as expected in all cases, I'll go into a bit more detail on each point.

1. The AC describes what should happen when the user doesn't have the `https://www.googleapis.com/auth/analytics.edit` [OAuth2 scope](https://developers.google.com/identity/protocols/oauth2/scopes) granted for their access token, which is a requirement to simply _call_ the endpoint for updating enhanced measurement settings. This is not the same thing as the user's Access Management permission to the specific Analytics account or property - it's possible to call the endpoint and then be denied access due to these permissions, in which case the resulting error will be displayed as you've seen. It's worth noting this is the same sort of behaviour as can be seen on the Settings Edit screen, for example when trying to create a property in an account for which the user doesn't have edit permission. If the edit _scope_ is not yet granted, they'll still go through the OAuth flow, but be unable to create the property upon their return and the corresponding error will be displayed.

2. From what I can see in the screencast, the spinner is showing when saving the settings, as per the AC, but it's not when redirecting to OAuth. This behaviour is as expected, and is the same as the GA4 Activation Banner which this new banner borrowed a bit of functionality from. We _could_ show the spinner when redirecting to OAuth, but it's not really in scope here and we should arguably do the same thing for the GA4 Activation Banner too if so. Please feel free to create a followup issue to address this if you wish, but I don't think it needs to hold up this particular issue.

3. It's necessary to show the first stage of the banner notification upon return from OAuth because the request to update the EM settings still needs to take place, and the initial banner is where the CTA with its spinner is displayed, which should still be shown in this scenario to indicate the save is occurring. Additionally, any error message from this request should be displayed on the first banner and prevent the second, "success" stage being shown.

**Comment by wpdarren** [comment]
### QA Update:

**Verified:**

- A new "Enable enhanced measurement" banner is displayed under the conditions defined in the AC.
  - Label: Understand how visitors interact with your content
  - Description: Enable enhanced measurement in Analytics to automatically track metrics like file downloads, video plays, form interactions, etc. No extra code required.
  - Primary CTA: Enable now
  - Dismiss button: Maybe later
  - "Learn more" link target: https://support.google.com/analytics/answer/9216061
- The layout and styling are consistent with the existing `Switch to GA4 Dashboard View` banner.

- The banner is shown when all of the following conditions are true:
  - The enhancedMeasurement feature flag is enabled
  - There is a currently configured web data stream.
  - The web data stream doesn't have enhanced measurement enabled.
  - The user has not already interacted with the "Enable enhanced measurement" toggle.
  - The banner has not already been dismissed.

- Clicking the `Enable now` CTA enabled enhanced measurement for the current web data stream and save the enhanced measurement settings, without taking the user to the Settings page.
- A spinner is shown in the button while the settings are being saved.
- Once the setup is completed, the user is redirected back to the dashboard, and another banner appears for the second stage, with a single CTA and copy as follows:
  - Label: You successfully enabled enhanced measurement for your site
  - Description: Your configured Analytics web data stream will now automatically measure interactions on your site in addition to standard page views measurement.
  - Primary CTA: OK, Got it
  - "Learn more" link target: https://support.google.com/analytics/answer/9216061banner
  - Clicking the OK, Got it CTA permanently dismisses the banner.
  - Clicking the Maybe later button dismisses the banner for a month, and show a tooltip pointing to the Settings menu item in the WP menu.  The tooltip's copy should is as per the AC. 

- When there is an error due to a missing scope, the use ris redirected to the OAuth flow without showing the "Additional Permissions Required" modal, following the behaviour of the GA4 Activation Banner. 
- Upon returning from the flow, the submission has submitted automatically.
- If there is another type of error, an error message is shown below the description and above the buttons.

In addition to the above, I also tested the additional steps in the QAB. Screenshots below for all tests. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/ba898094-7305-48db-9c09-9236b8a5339e)
![image](https://github.com/google/site-kit-wp/assets/73545194/f101dcd8-36f4-477f-8876-d240a0a1d94c)
![image](https://github.com/google/site-kit-wp/assets/73545194/79db0e2c-5361-4c0b-a29f-5cd0dd8541ac)
![image](https://github.com/google/site-kit-wp/assets/73545194/14d2e814-5b29-48c5-9254-70848a15eaf2)
![image](https://github.com/google/site-kit-wp/assets/73545194/3bf4590c-46c4-4685-9e18-a7a4c2986a92)
![image](https://github.com/google/site-kit-wp/assets/73545194/0d8825be-a18c-4394-b393-70ae6ed23df3)
![image](https://github.com/google/site-kit-wp/assets/73545194/58fd9fb9-1533-4f69-abe3-fe6ef41b7fd4)
![image](https://github.com/google/site-kit-wp/assets/73545194/7d437db1-c40b-4e04-bd35-7ab5808121c8)

</details>
