### ISSUE TITLE
Update metrics selection panel design

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7464]
## Feature Description

Per Bug Bash, we've decided to remove the accordion functionality from the metrics selection panel in Key Metrics Widget and instead display the tile title and description by default. The new design from @sigal-teller is [available in Figma here](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6116-12251&mode=design&t=WGzk8dhNYk8r603q-0).

Note that #7425 is also dependent on this redesign.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Key Metrics Selection Panel should be redesigned as per the new [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6116-12251&mode=design&t=WGzk8dhNYk8r603q-0):
    * Remove the accordion functionality but maintain general styling (border, spacing etc).
    * Use a smaller font for the metric description (size: 14px -> 12px, line height: 20px -> 16px).
    * Move the description closer to the title with no divider line.
* Note: This issue solely focuses on the metrics panel redesign. The [order of metrics in the panel](https://github.com/google/site-kit-wp/issues/7547) and [hiding metrics for disconnected modules](https://github.com/google/site-kit-wp/issues/7425) will be dealt in separate issues.

## Implementation Brief

* Copy `assets/js/components/Accordion.js` component and name it `ContentBox` for example
  * Remove `initialOpen`, `onOpen`, and `onClose` props, but keep `disabled` prop
  * Clean `useEffect` hooks, and `toggleAccordion` function
  * Rename `googlesitekit-accordion` class to `googlesitekit-content-box`
  * Remove `is-active` class and other removed props usage, from `propTypes` as well, except for `disabled` prop usage and it's class
* Go to `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.js` and in `SideSheet` component under `initialFocus` rename `.googlesitekit-accordion__header` selector part to `.googlesitekit-content-box__header`, or even better focus the checkbox inside the component directly, if present/possible.
* Copy `assets/sass/components/global/_googlesitekit-accordion.scss` and rename it to the `_googlesitekit-content-box.scs`
  * Rename classes to match new component class names
  * Remove unused classes like`.is-active`, etc
  * Set description `font-size: 12px` and `line-height: 16px`
  * Remove divider line, and lessen the space between description and title, as per design
* Go to `assets/sass/components/key-metrics/_googlesitekit-km-selection-panel.scss`, and under `.googlesitekit-km-selection-panel-metrics__metric-item` selector, copy the accordion related styles (that are in use in new component) and transfer them to the new `ContentBox` stylesheet `_googlesitekit-content-box.scs`, we don't need to override styles anymore, since new component can have this styles by default
* Import new file to the `assets/sass/admin.scss` - `@import "components/global/googlesitekit-content-box.scs";` under `Global` comment section
* Ensure that styles match the figma design
* In `assets/js/components/KeyMetrics/MetricsSelectionPanel/MetricItem.js`, replace `Accordion` component with newly created `ContentBox` and remove unused props. Make sure to keep `disabled` prop
* In new design, the description is in line vertically with the title. Two match this either:
  * Not so optimal - use padding on description to align it with title
  * Optimal - copy `Checkbox` component `assets/js/googlesitekit/components-gm2/Checkbox.js` and you can call it `CheckoxWithDesc` for example
    * Introduce new prop `description`
    * Render it bellow `<label>` and wrap both elements with new `div`
    * Add additional class to the main wrapper `mdc-form-field`, like `mdc-form-field mdc-form-flex-field`
    * Add `flex` style to the new wrapper class `mdc-form-flex-field`, and a `gap: 18px`
    * This way it is split into 2 column layout for easier manipulation
    * Then in `assets/js/components/KeyMetrics/MetricsSelectionPanel/MetricItem.js` replace usage of `Checkbox` with `CheckoxWithDesc` and move `description` prop from `ContentBox` component into new `CheckoxWithDesc`

### Test Coverage

* Create new component stories in the `stories` folder
* Update VRT images
* Check `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js` if it needs updating, and update any failing tests

## QA Brief

- Set up Site Kit.
- Using the tester plugin, enable the `userInput` feature flag.
- View the Key Metrics Selection Panel:
  - If KMW is not yet set up and the KMW CTA appears, click on `I'll pick metrics myself`.
  - If KMW is already set up, click on the adjacent `Change metrics` action.
- Verify that the panel has been updated according to the linked Figma designs.
- Verify that the accordion functionality has been removed, and the styling is aligned with Figma.

## Changelog entry

* Remove accordion functionality the Key Metrics Selection Panel and update its design.

**Comment by marrrmarrr** [comment]
ACs here 👀 👍

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified new metrics selection panel design.
- Verified font for the metric description (size: 14px -> 12px, line height: 20px -> 16px).
- Verified the description moved closer to the title with no divider line.

@nfmohit 

**Issue** : In Figma design under selected focus state check box have dark circle around it. This dark circle around check box is missing in actual implementation.

<details>

**Figma -**

![image](https://github.com/google/site-kit-wp/assets/94359491/6736fa5e-683f-4b21-b7a6-06917c27e7c8)

![image](https://github.com/google/site-kit-wp/assets/94359491/bc77ac35-761c-4f74-b35a-d0254bd4bb41)


**Actual Implementation -**

![image](https://github.com/google/site-kit-wp/assets/94359491/2b498c06-cb49-4ee0-89cb-b06bab65a990)

![image](https://github.com/google/site-kit-wp/assets/94359491/6687e30a-a2e6-4b7d-8940-f8607eb9ec3c)

</details>

**Comment by nfmohit** [comment]
Hi @mohitwp, thank you for sharing your observation.

> **Issue** : In Figma design under selected focus state check box have dark circle around it. This dark circle around check box is missing in actual implementation.

This focus state actually originally existed in the design when we first implemented the metrics selection panel in #6258, however, we had decided not to implement it as that would deviate from our usual re-used Checkbox styles everywhere else.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @nfmohit for clarification. In this case I'm moving it to approval.

- Tested on dev environment.
- Verified new metrics selection panel design.
- Verified font for the metric description (size: 14px -> 12px, line height: 20px -> 16px).
- Verified the description moved closer to the title with no divider line.


<details>


https://github.com/google/site-kit-wp/assets/94359491/08319933-fc78-4c27-acff-47b5fc6b3ba6


![image](https://github.com/google/site-kit-wp/assets/94359491/6fc0ce35-fcdf-4b25-bc05-81bb5f138ace)


</details>
