### ISSUE TITLE
Add tooltips with metrics details to KMW tiles

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7472]
## Feature Description

Per [this Bug Bash issue](https://app.asana.com/0/1204713925711993/1205100104876449/f), add tooltips to the KMW tiles that display the details for how the data is computed.

* Top traffic source – "Top session by `sessionDefaultChannelGroup` and its percentage of users by `totalUsers`"
* Most popular content – "Top content based on `screenPageViews`"
* Top countries by traffic – "Top `totalUsers` by country dimension"
* Top converting traffic source – "Top `sessionConversionRate` by `firstUserDefaultChannelGroup`"
* Loyal visitors – "% of returning visitors from `newVsReturning` dimension divided by `activeUsers`"
* New visitors (aka Audience growth) – "% of new visitors from `newVsReturning` dimension divided by `activeUsers`"
* Most engaged traffic source – "Top `engagementRate` by `sessionSource` dimension"
* Most popular products (aka Top performing products) – "Top `screenPageViews` for pages with the product post type"
* How people find your site (aka Top performing keywords) – "The top search queries for your site by highest clickthrough rate"
* Top cities by traffic – "Highest `totalUsers` by city dimension"

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Every Key Metric Widget tile should have a tooltip as per this [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=4581-79986&mode=design&t=EjPaeLhKpDqS7sCS-0). UPDATE: Ensure that tooltips are also added to any of the new News Key Metric widget tiles that have already been merged. Their tooltip's text is given in their respective issues.
* Rename the title of the "Loyal visitors" KMW tile to "Returning visitors"
* The content for each of the tooltips is as follows:
  - Top traffic source – "Channel (e.g. social, paid, search) that brought in the most visitors to your site"
  - Most popular content by pageviews – "Pages your visitors read the most"
  - Top countries by traffic – "The countries where most of your visitors came from"
  - Top converting traffic source – "Channel (e.g. social, paid, search) that brought in visitors who generated the most conversions"
  - *Returning* visitors (prev Loyal visitors) – "Portion of your site's visitors that returned at least once in this timeframe"
  - New visitors – "Portion of visitors who visited your site for the first time in this timeframe"
  - Most engaged traffic source – "Channel (e.g. social, paid, search) that brought in the most visitors who had a meaningful engagement with your site"
  - Most popular products by pageviews – "Products on your site which visitors viewed the most"
  - Top performing keywords – "The top search queries for your site by highest clickthrough rate"
  - Top cities driving traffic – "The cities where most of your visitors came from"

## Implementation Brief

* In `<MetricTileText>` and `<MetricTileNumeric>`:
  * Add the `infoToolTip` prop and implement/render the `<ToolTip>` component in exactly the same way it has been implemented in `<MetricTileTable>`.
* Within each of the Key Metric widget components mentioned in the ACs, pass the `infoToolTip` prop with a translatable string. The content of the string should be as per the AC.
  * Note: For the `PopularProductsWidget` component, prepend the content in the AC to the already existing tooltip content as suggested in this [comment](https://github.com/google/site-kit-wp/issues/7472#issuecomment-1725305189).
* Within the `<LoyalVisitorsWidget>` component, udpate the title of this widget to match the AC, i.e. `Loyal visitors` => `Returning visitors`

### Test Coverage

* No new tests are required, but multiple VRT reference images will have to be updated along with snapshots of any failing Jest unit tests. 

## QA Brief

* Select each of the Key Metric Widgets from the metrics selection panel and verify that the tooltip for each metric matches the text in the AC and displays correctly in different viewports. 

## Changelog entry

* Add tooltips with extra info to each Key Metrics tile.

**Comment by bethanylang** [comment]
@marrrmarrr @jimmymadon @sigal-teller Assigning this over to you – Mariya noted that this is our highest priority P1, so it would be great to get it done prior to launch. I took a try at defining the text for the tooltips based on the [design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit); feel free to edit! 

Sigal, assigning to you here because we need some direction on UX – is there a pattern we can use for these tooltips? Thanks!

**Comment by wpdarren** [comment]
@jimmymadon I feel this makes the metric tiles much more user-friendly and reading through the AC the tooltip copy makes sense to me!

**Comment by marrrmarrr** [comment]
@jimmymadon Sigal had actually [already done a design](https://www.figma.com/file/S2CNc1toIzC7UrGMgs79S6/Conversions?type=design&node-id=1182-9802&mode=design&t=UmxidJzhoextIIQL-4) for this as part of the Event tracking feature. 

Regarding the tooltip contents, I'd like to understand how exactly the variables listed will appear in the actual tooltip. For example, what would be displayed for "Top `sessionConversionRate` by `firstUserDefaultChannelGroup`"?

**Comment by bethanylang** [comment]
Thanks, @jimmymadon!

@marrrmarrr Definitely would love to hear your thoughts on here on how/if there's a way to make these more user-friendly. This idea came up because @wpdarren had (I think correctly!) noted that users may have trouble understanding how each of these metrics is calculated. My idea here was that the tooltips could state that very clearly using the language that's in GA so that the user could easily click over to GA and "match" the data. We know that it's pretty common that users try to do this with dashboard metrics, anyway, so this would give them a good place to start and if they're confused about a particular term, they can dig further into SK/GA documentation.

**Comment by marrrmarrr** [comment]
Here's a stab at making this more "human sounding", @bethanylang @jimmymadon LMKWYT as you're the native speakers (: 
Note I also updated "loyal" to "returning" visitors, as we're seeing that publishers and site owners' interpretation of what "loyal" can mean vary widely. 

- Top traffic source – "Channel (e.g. social, paid, search) that brought in the most visitors to your site"
- Most popular content – "Pages your visitors read the most"
- Top countries by traffic – "The countries where most of your visitors came from"
- Top converting traffic source – "Channel (e.g. social, paid, search) that brought in visitors who generated the most conversions"
- *Returning* visitors – "Portion of your site's visitors that returned at least once in this timeframe"
- New visitors (aka Audience growth) – "Portion of visitors who visited your site for the first time in this timeframe"
- Most engaged traffic source – "Channel (e.g. social, paid, search) that brought in the most visitors who had a meaningful engagement with your site"
- Most popular products (aka Top performing products) – "Products on your site which visitors viewed the most"
- How people find your site (aka Top performing keywords) – "The top search queries for your site by highest clickthrough rate"
- Top cities by traffic – "The cities where most of your visitors came from"

**Comment by bethanylang** [comment]
@marrrmarrr This is perfect from my perspective! @jimmymadon If all looks good to you feel free to update the ACs here.  :D

**Comment by marrrmarrr** [comment]
@jimmymadon @bethanylang do we need a separate issue for the tooltips on the news tiles?

**Comment by wpdarren** [comment]
@jimmymadon thank you, these all make sense to me and makes it more user-friendly for non Analytics experts. 👍

**Comment by bethanylang** [comment]
@marrrmarrr Yep, we'll add that when we add all the new issues for News Key Metrics Tiles; I'll be sure to flag this with @nfmohit!

**Comment by bethanylang** [comment]
@jimmymadon Thanks! So just to be clear, your intention is that we create the tooltip "pattern" in this issue as well as add them to the Key Metrics Widget tiles, and then we'll add the tooltips directly to the News Key Metrics Tiles tiles as part of each issue for tile creation (example: #7576)? cc @nfmohit

**Comment by techanvil** [comment]
Hey @jimmymadon, this IB looks good, the only thing I'm not so sure about is the "Most popular products" widget. As specced, the resulting tooltip will have the following content, which doesn't read particularly well to me. Even if we were to include an empty line to make it two paragraphs as discussed below, I don't think the new content fits so well _after_ the current text.

> Site Kit detected these are your product pages. If this is inaccurate, you can [replace]() this with another metric. Products on your site which visitors viewed the most

I think a small but clear improvement would be to adjust it to prepend the text and include an empty line to make it two paragraphs/distinct phrases:

> Products on your site which visitors viewed the most
> 
> Site Kit detected these are your product pages. If this is inaccurate, you can [replace]() this with another metric

I'm certainly open to suggestion, but this seems like an easy adjustment to make here. What do you think?

**Comment by bethanylang** [comment]
+1 to that suggestion @techanvil, reads much cleaner to me!

**Comment by techanvil** [comment]
Thanks @jimmymadon! IB LGTM :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Every Key Metric Widget tile has a tooltip as per the Figma mock.
- Confirmed the rename the title of the "Loyal visitors" KMW tile to "Returning visitors"
- The content for each of the tooltips as per the AC. 

**Note:**  I did notice that the tooltips are underneath the titles on some of the tiles which made it look a bit ugly, but I saw that @jimmymadon confirmed [in this comment](https://github.com/google/site-kit-wp/issues/7472#issuecomment-1726077948) that is expected because it looks worse on long titles.
