### ISSUE TITLE
Inconsistent Metrics Selection Panel Rendering at 600px Viewport

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7474]
## Bug Description

As reported by @hussain-t in Bug Bash:

At a 600px viewport width, the Metrics Selection Panel displays in tablet view, deviating from the intended mobile layout. This issue mirrors a previous inconsistency we observed with the key metrics widgets in #7395.

https://github.com/google/site-kit-wp/assets/12189958/88895d40-0116-4119-9d7d-aba00b073f47

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the viewport width is set to 600px, the Metrics Selection Panel should adhere to the mobile layout design.
* The Metrics Selection Panel's appearance and behavior at 600px width should be consistent with how it displays at 599px and below.
* Specifically, the panel should span the full width of the viewport.

## Implementation Brief

In `assets/sass/components/global/_googlesitekit-side-sheet.scss`:

* Locate the media query where the `min-width` is set to the `$bp-tablet` (600px) variable.
* Replace `$bp-tablet` with `$bp-nonMobile` (601px) to adjust the breakpoint.
* By doing so, the mobile layout styling will be applied to screen widths of 600px and below.

### Test Coverage

* Update any failing VRT images.

## QA Brief

* Set up SK with the userInput feature flag enabled.
* Setup Key Metrics.
* Set viewport to 599px, and click on change metrics button.
* Verify that metrics selection panel opens in full width.
* Set viewport to 600px, and click on change metrics button. 
* Verify that metrics selection panel also opens in full width.
* Set viewport to 601px (and over), and click on change metrics button.
* Verify that metrics selection panel opens in tablet mode - fixed width.

## Changelog entry

* Fix Key Metrics Selection Panel layout at 600px viewport.

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified Metrics selection panel on 600px, 509px and 601px.
- Verified that on 599px metrics, selection panel opens in full width.
- Verified that on 600px metrics, selection panel opens in full width.
- Verified that viewport to 601px (and over)  metrics selection panel opens in tablet mode - fixed width.

<details>

https://github.com/google/site-kit-wp/assets/94359491/f30ae3a0-4daf-4fa1-87b5-99ff1bdb5f41

</details>
