### ISSUE TITLE
Show a warning notice when enabling enhanced measurement with no events enabled.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7475]
## Feature Description

If there are _no_  enhanced measurement events enabled for the currently selected data stream, enabling enhanced measurement for the stream will have no tangible effect. This is a rare edge case as it requires the user to have explicitly taken the steps to disable all of the events.

With this being such an unlikely edge case, it doesn't seem worthwhile trying to engineer an overly complex solution that involves Site Kit enabling some or all of the events. Rather, we should simply show a warning notice when enabling enhanced measurement with no events enabled.

Therefore, we should add a warning notice to the "Enable enhanced measurements" [toggle](https://github.com/google/site-kit-wp/issues/7459) and [banner](https://github.com/google/site-kit-wp/issues/7461) when there are no events enabled for the selected web data stream. The notice should include a link to the selected web data stream's settings page on the Analytics site.

Toggle:

![image](https://github.com/google/site-kit-wp/assets/18395600/f6d0fb2b-cdf7-41a1-91d8-db8f7981293c)

Banner:

![image](https://github.com/google/site-kit-wp/assets/18395600/1c56cd1c-8f1f-40c6-9f7a-2975eabafa14)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- 

## Implementation Brief

- 

### Test Coverage

- 

## QA Brief

- 

## Changelog entry

-

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – after reviewing, we've decided to handle this as part of #7476 and #7477 rather than a separate issue with a focus on the specific settings that are important for us rather than treating "all" as a special case.
