### ISSUE TITLE
Blank dashboard until AdSense or Analytics module reset

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#748]
## Bug Description

Blank Site Kit admin dashboard. Remains blank with pulsating screen. 
Plugin V1.0.4

Workaround: Usually [disconnecting](https://i.imgur.com/6ppIDwZ.png) the Analytics or AdSense module and reconnecting again resolves the issue. (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit)

[Video of issue - with workaround fix](https://recordit.co/Ay8v3ejipH)

Additional information below:
- Occurs intermittently
- PHP Version 7.2.15
- No security plugin active 
- Host no blocking REST API access
- Other sites on same server work fine
- ModSecurity is enabled at host level

![WhudRa6hFwd](https://user-images.githubusercontent.com/41326532/67853293-2162a800-fb06-11e9-9f31-1700f89fb84c.png)

![Screen Shot 2019-10-30 at 10 49 56 AM](https://user-images.githubusercontent.com/41326532/67851779-10646780-fb03-11e9-9267-2c90699b0d6b.png)

![Screen Shot 2019-10-30 at 10 52 58 AM](https://user-images.githubusercontent.com/41326532/67851953-751fc200-fb03-11e9-9660-91f51767c268.png)

```
Request URL: https://oi.ie/wp-json/google-site-kit/v1/modules/adsense/notifications/?_locale=user
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-headers: Authorization, Content-Type
access-control-expose-headers: X-WP-Total, X-WP-TotalPages
allow: GET
cache-control: no-cache, must-revalidate, max-age=0
content-type: application/json; charset=UTF-8
date: Tue, 29 Oct 2019 19:07:59 GMT
expires: Wed, 11 Jan 1984 05:00:00 GMT
link: <https://oi.ie/wp-json/>; rel="https://api.w.org/"
server: nginx
status: 200
x-content-type-options: nosniff
x-powered-by: PHP/7.2.15
x-powered-by: PleskLin
x-robots-tag: noindex
x-wp-nonce: d52e564db8
```

`Request URL: https://oi.ie/wp-json/google-site-kit/v1/data/?request=%5B%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22dimensions%22%3A%22ga%3Amedium%22%2C%22metrics%22%3A%5B%7B%22expression%22%3A%22ga%3Asessions%22%2C%22alias%22%3A%22Sessions%22%7D%2C%7B%22expression%22%3A%22ga%3Ausers%22%2C%22alias%22%3A%22Users%22%7D%2C%7B%22expression%22%3A%22ga%3AnewUsers%22%2C%22alias%22%3A%22New%20Users%22%7D%5D%2C%22orderby%22%3A%5B%7B%22fieldName%22%3A%22ga%3Asessions%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D%5D%2C%22limit%22%3A10%2C%22url%22%3Afalse%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22analytics%22%2C%22datapoint%22%3A%22report%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%5B%22Dashboard%22%2C%22Single%22%5D%2C%22key%22%3A%22modules%3A%3Aanalytics%3A%3Areport%3A%3A1cc2cfc3218eab9aa0d167f96fe944ea%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22dimensions%22%3A%22ga%3Amedium%22%2C%22metrics%22%3A%5B%7B%22expression%22%3A%22ga%3Asessions%22%2C%22alias%22%3A%22Sessions%22%7D%2C%7B%22expression%22%3A%22ga%3Ausers%22%2C%22alias%22%3A%22Users%22%7D%2C%7B%22expression%22%3A%22ga%3AnewUsers%22%2C%22alias%22%3A%22New%20Users%22%7D%5D%2C%22orderby%22%3A%5B%7B%22fieldName%22%3A%22ga%3Asessions%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D%5D%2C%22limit%22%3A10%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22analytics%22%2C%22datapoint%22%3A%22report%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%22Dashboard%22%2C%22key%22%3A%22modules%3A%3Aanalytics%3A%3Areport%3A%3Ae54ff2cbd79c08e767fbf3260cc933bb%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22url%22%3Afalse%2C%22dimensions%22%3A%22date%22%2C%22compareDateRanges%22%3Atrue%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22search-console%22%2C%22datapoint%22%3A%22searchanalytics%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%5B%22Single%22%2C%22Dashboard%22%5D%2C%22key%22%3A%22modules%3A%3Asearch-console%3A%3Asearchanalytics%3A%3A6892af84f7b8398712c112e420a28141%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22multiDateRange%22%3A1%2C%22dimensions%22%3A%22ga%3Adate%22%2C%22metrics%22%3A%5B%7B%22expression%22%3A%22ga%3Ausers%22%2C%22alias%22%3A%22Users%22%7D%2C%7B%22expression%22%3A%22ga%3Asessions%22%2C%22alias%22%3A%22Sessions%22%7D%2C%7B%22expression%22%3A%22ga%3AbounceRate%22%2C%22alias%22%3A%22Bounce%20Rate%22%7D%2C%7B%22expression%22%3A%22ga%3AavgSessionDuration%22%2C%22alias%22%3A%22Average%20Session%20Duration%22%7D%2C%7B%22expression%22%3A%22ga%3AgoalCompletionsAll%22%2C%22alias%22%3A%22Goal%20Completions%22%7D%2C%7B%22expression%22%3A%22ga%3Apageviews%22%2C%22alias%22%3A%22Pageviews%22%7D%5D%2C%22limit%22%3A10%2C%22url%22%3Afalse%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22analytics%22%2C%22datapoint%22%3A%22report%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%22Dashboard%22%2C%22key%22%3A%22modules%3A%3Aanalytics%3A%3Areport%3A%3Aab522b830a0f488c2585f21b935d1798%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22compareDateRanges%22%3A1%2C%22dimensions%22%3A%22ga%3Adate%22%2C%22metrics%22%3A%5B%7B%22expression%22%3A%22ga%3Ausers%22%2C%22alias%22%3A%22Users%22%7D%2C%7B%22expression%22%3A%22ga%3Asessions%22%2C%22alias%22%3A%22Sessions%22%7D%2C%7B%22expression%22%3A%22ga%3AbounceRate%22%2C%22alias%22%3A%22Bounce%20Rate%22%7D%2C%7B%22expression%22%3A%22ga%3AavgSessionDuration%22%2C%22alias%22%3A%22Average%20Session%20Duration%22%7D%2C%7B%22expression%22%3A%22ga%3AgoalCompletionsAll%22%2C%22alias%22%3A%22Goal%20Completions%22%7D%5D%2C%22limit%22%3A180%2C%22url%22%3Afalse%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22analytics%22%2C%22datapoint%22%3A%22report%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%22Dashboard%22%2C%22key%22%3A%22modules%3A%3Aanalytics%3A%3Areport%3A%3A743969d0dab246e5788b60b01f73ea7e%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22url%22%3Afalse%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22analytics%22%2C%22datapoint%22%3A%22goals%22%2C%22priority%22%3A1%2C%22maxAge%22%3A3600%2C%22context%22%3A%22Dashboard%22%2C%22key%22%3A%22modules%3A%3Aanalytics%3A%3Agoals%3A%3Aa096c9c425bdbc7e6487d28f65a7bdf5%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22dimensions%22%3A%22query%22%2C%22limit%22%3A10%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22search-console%22%2C%22datapoint%22%3A%22searchanalytics%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%5B%22Dashboard%22%5D%2C%22key%22%3A%22modules%3A%3Asearch-console%3A%3Asearchanalytics%3A%3Ad5590576de7dfd3412f70ad0ee9bdfc8%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%2C%22dimensions%22%3A%22ga%3ApageTitle%2Cga%3ApagePath%22%2C%22metrics%22%3A%5B%7B%22expression%22%3A%22ga%3Apageviews%22%2C%22alias%22%3A%22Pageviews%22%7D%2C%7B%22expression%22%3A%22ga%3AuniquePageviews%22%2C%22alias%22%3A%22Unique%20Pageviews%22%7D%2C%7B%22expression%22%3A%22ga%3AbounceRate%22%2C%22alias%22%3A%22Bounce%20rate%22%7D%5D%2C%22orderby%22%3A%5B%7B%22fieldName%22%3A%22ga%3Apageviews%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D%5D%2C%22limit%22%3A10%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22analytics%22%2C%22datapoint%22%3A%22report%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%5B%22Single%22%2C%22Dashboard%22%5D%2C%22key%22%3A%22modules%3A%3Aanalytics%3A%3Areport%3A%3Ab9d29b5a688b67a72c16f5cd56b71aae%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22today%22%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22adsense%22%2C%22datapoint%22%3A%22earnings%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%22Dashboard%22%2C%22key%22%3A%22modules%3A%3Aadsense%3A%3Aearnings%3A%3A8175ae9350cc6768e8d5a610a9c7cd36%22%7D%2C%7B%22data%22%3A%7B%22dateRange%22%3A%22last-28-days%22%7D%2C%22type%22%3A%22modules%22%2C%22identifier%22%3A%22adsense%22%2C%22datapoint%22%3A%22earnings%22%2C%22priority%22%3A1%2C%22maxAge%22%3A86400%2C%22context%22%3A%22Dashboard%22%2C%22key%22%3A%22modules%3A%3Aadsense%3A%3Aearnings%3A%3Ac1eab9442155f86e675000938e194c26%22%7D%5D&_locale=user`

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

Keeping issue open to check for repeating issue on other sites

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This is likely no longer valid at this point, given all the refactoring we have done around these areas. Please reopen if it still proves to be an issue.
