### ISSUE TITLE
Update Key metrics title in Admin settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7480]
## Bug Description

As reported by @wpdarren in Bug Bash:

The Key metrics title on Site Kit Admin Settings should be in title case ("Key Metrics") like the rest of the headers on this screen

![image](https://github.com/google/site-kit-wp/assets/12189958/10cb1083-3eee-4eff-976f-3d2550b8006d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Key metrics" heading in Site Kit settings should be changed to "Key Metrics".
  * No other "Key metrics" localisation should be changed; the "Key metrics" heading on the Dashboard should stay in sentence case.

## Implementation Brief

* Change https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/components/settings/SettingsCardKeyMetrics.js#L82 to be `__( 'Key Metrics' )`.

### Test Coverage

* Update VRTs/snapshot tests as-needed.

## QA Brief

* Visit the Site Kit settings on a site with Key Metrics enabled and filled out.
* The "Key Metrics" heading should have a capital "M" in English.

## Changelog entry

* Update Key Metrics heading in settings.

**Comment by tofumatt** [comment]
Oddly, we seem to use _non_ title case on the dashboard, so eventually we should probably make this consistent plugin-wide, but for now this one is the odd one out and we should update it 😄

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The "Key Metrics" heading should have a capital "M" in English.

![image](https://github.com/google/site-kit-wp/assets/73545194/dd765451-d794-45b1-b926-bbc1f501853f)
