### ISSUE TITLE
Clean up apostrophes throughout KMW feature

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7481]
## Feature Description

As reported by @bethanylang in Bug Bash:

These aren't backticks, but they look like it for some reason. Not sure if this is a styling or other issue? You can see in the screenshots below how the apostrophes are angled left and not straight.

Dashboard CTA: 

![image](https://github.com/google/site-kit-wp/assets/12189958/4c942595-4be2-4b33-a815-29a65fbbe699)

First step of setup:

![image](https://github.com/google/site-kit-wp/assets/12189958/3145ec6b-e900-4328-a3d1-af776019739e)

See also #7440 for fixing similar issues in other places in the plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
I left a response with some context in https://github.com/google/site-kit-wp/issues/7440#issuecomment-1692426397, but I think we should close both of these as won't fix issues as they're behaving as-intended 🙂
