### ISSUE TITLE
Numeric & table KM widget tiles flash their zero state before showing the loading state

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7482]
## Bug Description

As reported by @techanvil in Bug Bash:

On page load, the numeric KM tiles (Loyal/New Visitors) can briefly show their zero state before their loading state appears.

I've also seen the same thing happening for table KM widget tiles (e.g. Top performing keywords, Most popular content by pageviews) although these have proven elusive when trying to capture a screencast.

This doesn't appear to be an issue for the "text" widget tile type.

Note that the video was captured without needing to clear the cache or throttle the bandwidth.

https://github.com/google/site-kit-wp/assets/12189958/66ec71df-7723-44b9-b532-968b0d13dde9

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Key Metrics widgets with numeric data (eg. at least Loyal/New Visitors) should not flash a zero data state before the "loading" state—they should be in "Loading" state and then change over to the data for the tile.

## Implementation Brief

* The issue here is the usage of `useInViewSelect` for `hasFinishedResolution` which returns `undefined` for a short period of time before returning `true` (and then eventually `false` once the reports have loaded). Both, the `MetricTileNumeric` and `MetricTileTable` components use the condition `! loading && <RenderTheTile>` which causes the zero data state to show first and then eventually display the loader components.
* So we simply need to replace all usages of `useInViewSelect` with `useSelect` like we do when figuring out the loading / error states in all other Dashboard widget / KMW tile components. The following files need to be updated:
    * `LoyalVisitorsWidget.js`
    * `NewVisitorsWidget.js`
    * `PopularContentWidget.js`
    * `PopularProductsWidget.js`
    * `PopularKeywordsWidget.js`

The [attached PR](https://github.com/google/site-kit-wp/pull/7505) makes this minor change and can be code/merge reviewed if the IB is successfully reviewed.

### Test Coverage

* No new tests required.

## QA Brief

* From the metrics selection panel, select the following widgets:
    * `Loyal visitors`
    * `New visitors`
    * `Top performing keywords`
    * `Most popular content by pageviews`

* In chrome / browser devtools, please `Clear site data`. Then refresh the dashboard (which will ask you to login again) and ensure that for numeric widgets, there are no 0s and for table widgets, there is no "Zero data message" that appears before the loader is shown.

* Test the `Most popular products by pageviews` for the above behaviour using the QAB from #6249.  

## Changelog entry

* Fix bug that caused some Key Metric tiles to briefly show zero data while loading.

**Comment by techanvil** [comment]
IB :white_check_mark:
