### ISSUE TITLE
Copy changes for KMW

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7484]
## Feature Description

As reported by Brandon Kenig in Bug Bash, please make the following copy changes.

### On step 1 of KMW customization ("What is the main purpose of this site?")
```diff
- Based on your answer, Site Kit will tailor the metrics you see on your dashboard to help you track how close you're getting to your specific goals.
+ Based on your answer, Site Kit will tailor the metrics you see on your dashboard to help you track progress towards your specific goals.
```

### On step 3 of KMW customization ("What are you top goals for this site?")
```diff
- Based on your answers, Site Kit will tailor the metrics and advice you see on your dashboard to help you make progress in these areas.
+ Based on your answers, Site Kit will tailor the metrics and recommendations you see on your dashboard to help you make progress in these areas.
```

For the "Encouragement to post more frequently" answer:
```diff
- Encouragement to post more frequently
+ Tips for generating and posting engaging content updates
```

### On the Key Metrics CTA

```diff
- Get metrics and suggestions tailored to your specific goals
+ Get metrics and suggestions tailored to your specific site goals
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The description of `purpose` user input question should be changed to: `Based on your answer, Site Kit will tailor the metrics you see on your dashboard to help you track progress towards your specific goals.`
* The description of `goals` user input question should be changed to: `Based on your answers, Site Kit will tailor the metrics and recommendations you see on your dashboard to help you make progress in these areas.`
* The text of `encourage_to_post` answer of `goals` user input question should be changed to `Tips for generating and posting engaging content updates`
* The title of Key Metrics Setup CTA widget should be changed to `Get metrics and suggestions tailored to your specific site goals`
* All texts should be translatable.

## Implementation Brief

* In `assets/js/components/user-input/UserInputQuestionnaire.js`:
    * Update the `description` prop of `UserInputQuestionWrapper` with `USER_INPUT_QUESTIONS_PURPOSE` slug to match the description defined in the AC for `purpose` user input question.
    *  Update the `description` prop of `UserInputQuestionWrapper` with `USER_INPUT_QUESTIONS_GOALS` slug to match the description defined in the AC for `goals` user input question.
* In `assets/js/components/user-input/util/constants.js`:
    * Update the text for `encourage_to_post` property to the one defined in AC.
* In `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`:
    * Update the `title` prop of `KeyMetricsCTAContent` to match the title defined for Key Metrics Setup CTA widget in AC.

### Test Coverage

* Fix any failing tests.
* Update VRT images. 

## QA Brief

* Set up Site Kit, including Google Analytics
* Enable `ga4Reporting` and `userInput` flags
* In the Key Metrics widget
  * Verify that title of Key Metrics Setup CTA is same as in ACs
  * Click on the "Get tailored metrics" button
  * For the step 1, verify that description text on the left, matches the copy provided for `purpose` of AC
  * For the step 3, verify that description text on the left, matches the copy provided for `goals` of AC
  * Still for the step 3, verify that in the answers on the right, there is a checkbox with label matching the copy of `encourage_to_post` in AC

## Changelog entry

* Update copy text in Key Metrics tailored metrics screen.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The description of purpose user input question is changed to: `Based on your answer, Site Kit will tailor the metrics you see on your dashboard to help you track progress towards your specific goals.`
- The description of goals user input question is changed to: `Based on your answers, Site Kit will tailor the metrics and recommendations you see on your dashboard to help you make progress in these areas.`
- The text of `encourage_to_post` answer of goals user input question is changed to `Tips for generating and posting engaging content updates`
- The title of Key Metrics Setup CTA widget is changed to `Get metrics and suggestions tailored to your specific site goals`

**Additional testing:**

- Made sure that the copy changes didn't have any impact on UI on smaller viewports. 
- Checked that the text `Tips for generating and posting engaging content updates` appears on the user input overview screen and also within Admin Settings when the questions are submitted. 

**Note:** In the AC, it mentions: `All texts should be translatable.` I am unable to check if all of the copy changes are translated successfully until 1.109.0 is released.  I have created [an Asana ticket](https://app.asana.com/0/1185360131189553/1205384679842989/f) to test this. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/1f8a783b-4a09-4f5b-ad0b-9b46959856b0)
![image](https://github.com/google/site-kit-wp/assets/73545194/3feb6df8-e69c-48d1-9126-7224b50acdb8)
![image](https://github.com/google/site-kit-wp/assets/73545194/45166791-0bba-447c-8790-88ebdc1a0ab6)
![image](https://github.com/google/site-kit-wp/assets/73545194/b18ce44e-100b-4405-ac02-7cb6dc72f321)
![image](https://github.com/google/site-kit-wp/assets/73545194/8646403a-8f29-4c44-b3f1-c1644ef58d1d)
![image](https://github.com/google/site-kit-wp/assets/73545194/3bf64a07-c055-4418-a573-9630776b170b)

</details>
