### ISSUE TITLE
When the "Change metrics" panel opens, the first item should be focused, not the "Close" button in the panel

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7485]
## Bug Description

Bug bash issue: https://app.asana.com/0/1204713925711993/1205261415065323/f

We should show/maintain a visible focus state when the "Change Metrics" slide-over panel is opened, but the focused element should be the first selectable metric, not the "close" button.

## Steps to reproduce

1. Ensure Key Metrics is enabled
2. Open the Key metrics "Change metrics" slide-over from the Dashboard
3. Observer the "Close" button is the first item focused

## Screenshots

https://github.com/google/site-kit-wp/assets/90871/8016ae50-5caf-4467-853c-6da10b9f3799

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the "Change Metrics" slideover panel is opened, the first key metric (shown in the screencast above underneath the mouse cursor at the end of the video) should be focused and have focus styles showing, not the "close" button.

## Implementation Brief

* To arbitrarily focus any focusable item inside the `FocusTrap` instead of the default (first focusable item), we need to pass `initialFocus` to the `focusTrapOptions` in the underlying `FocusTrap` component. See [here](https://github.com/focus-trap/focus-trap#createoptions) for details. 
* In `assets/js/components/SideSheet.js`:
    * Expose the `focusTrapOptions` as a prop, with a default value of `{}` and spread it inside the `focusTrapOptions` object passed in the `FocusTrap` element after the currently used properties. 
* In `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.js`:
    * Use the newly added `focusTrapOptions` prop to the `SideSheet` element, and pass the `initialFocus` property with selector of accordion item `.googlesitekit-accordion__header` as value. 
```js
focusTrapOptions={ {
    initialFocus: '.googlesitekit-accordion__header',
} }
```

### Test Coverage

* JSDom support for `focus-trap` is not very reliable, so we can't realistically test the behavior in Jest.
* VRT's may need to be updated.

## QA Brief

- Follow the `Steps to reproduce` in the issue description.
- Verify that the first metric is focused, instead of the close icon.
![image](https://github.com/google/site-kit-wp/assets/20284937/9ff33869-3b61-44a0-91a9-06beb4aca741)

## Changelog entry

* Improve Key metrics selection panel initial focus behavior by selecting the first item.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The first metric is focused, instead of the close icon.
- Tested on Desktop and smaller viewports like mobile and tablet. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/94ff7f28-f963-4cb7-8ef4-c939ed6d9052)
![image](https://github.com/google/site-kit-wp/assets/73545194/5dbace8a-ad9c-4942-b400-ac14b02924e7)

</details>

**Note:** did notice a potential accessibility issue, but have left a note for Matthew to look at it.  Will create separate ticket if it is indeed an issue we need to fix for users with screen readers.
