### ISSUE TITLE
Request Access button missing when only GA4 is enabled

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7492]
## Bug Description

The Request Access button on the Insufficient Permissions error notice is missing when UA is not enabled and only GA4 is enabled / setup.

## Steps to reproduce

1. Using admin1, set up Site Kit and connect a GA4 property only (do not enable UA).
2. Login using admin2 who does not have access to the above GA4 property. 
3. The Insufficient Permissions error will not have the Request Access button.
4. Now login as admin1 and enable/connect a UA property. There is no need to change the "Dashboard View" to UA - keep this as GA4.
5. Login as admin2 who should not have access to the above UA and GA4 properties. 
6. However, now notice that the "Request Access" button is being displayed in the Insufficient Permissions error for Analytics.

## Screenshots

https://github.com/google/site-kit-wp/assets/1721319/d42a63f6-4596-4caf-9178-2e6da2eb836e

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If an admin does not have access to a GA4 property, when they view the dashboard and get an "Insufficient Permissions error" in every non-Key Metric widget on the dashboard, they should see the "Request Access" CTA implemented in #5308 in every non-Key Metric widget on the dashboard.
  * Clicking on the Request Access CTA should take the user to the same popup within the GA4 Admin console which allows the user to "Request Access" to the owner of the property.

## Implementation Brief

**Preliminary Note**

Simply adding the `getServiceEntityAccessURL` selector won't fully address the issue. This is because the GA4 dashboard widgets pass the incorrect `analytics` module slug instead of `analytics-4`.

### Create a New Selector in Analytics-4 Datastore

In `assets/js/modules/analytics-4/datastore/service.js`:

* Implement a new selector, `getServiceEntityAccessURL` which leverages the existing `getServiceURL` selector of `analytics` store.
* Formulate the `path` property by combining the `accountID`, GA4 `propertyID`, and `webDataStreamID`. Then pass this `path` as part of an object argument to the `getServiceURL` selector.
* This should mirror the `Edit in Analytics` URL logic of the `GA4SettingsView`. See:
https://github.com/google/site-kit-wp/blob/3e4b803f2d6a77f2892efdafad2af6d472096a78/assets/js/modules/analytics/components/settings/GA4SettingsView.js#L58-L62
* Replace the above `getServiceURL` call in `GA4SettingsView` with a call to the new `getServiceEntityAccessURL` selector.

### Correct the Module Slug in GA4 Components

Update the following files to ensure the correct `analytics-4` module slug is passed to the `WidgetReportError` / `ReportError` component:

* `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/index.js`,
* `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/OptionalCells.js`,
* `assets/js/components/adminbar/AdminBarSessionsGA4.js`,
* `assets/js/components/adminbar/AdminBarUniqueVisitorsGA4.js`,
* `assets/js/components/wp-dashboard/WPDashboardSessionDurationGA4.js`,
* `assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsGA4.js`,
* `assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidgetGA4.js`,
* `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/TotalUserCount.js`,
* `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js`,

For each file:

* Locate the section of code that renders the `WidgetReportError` / `ReportError` component.
* Update the `moduleSlug` prop to `analytics-4` from `analytics`.
* Update any related Error state stories for these components if necessary.

### Test Coverage

- Add unit tests for the new `getServiceEntityAccessURL` selector.
- Update any failing tests related to error states to align with these modifications.

## QA Brief

* **Issue Reproduction**: Follow the provided steps to reproduce the issue.  
* **CTA in Dashboard**: Confirm that the "Request Access" CTA is prominently displayed in all GA4 widgets within the dashboard.
* Note that the Key Metrics widgets will be fixed in #7465.
* **CTA in WP Admin & Dashboard Widgets**: Additionally, ascertain that the "Request Access" CTA is also visible in both the WordPress Admin Bar and the WordPress Dashboard widgets specifically for GA4. Note that these were previously not displaying this CTA.
* **Error Title Verification**: Ensure that the title of the error block reads "Insufficient permissions in Analytics 4" instead of "Insufficient permissions in Analytics."
* **CTA Redirection**: Validate that clicking on the "Request Access" CTA redirects the user to the same popup within the GA4 Admin console that appears when clicking the "Edit in Analytics" link on the Settings page.
* **Error Code Redirect**: Note that an `analytics-4_insufficient_permissions` error code will be introduced to redirect to [the relevant documentation](https://sitekit.withgoogle.com/documentation/troubleshooting/dashboard/#insufficientpermissionsanalytics), although this hasn't been implemented yet. Therefore, this part of the AC can't be fully tested now. Please refer to this [comment](https://github.com/google/site-kit-wp/issues/7465#issuecomment-1705082295).
* **Settings Page Integrity**: Confirm that these changes have not adversely affected the existing "Edit in Analytics" link within the Settings page.

## Changelog entry

* Ensure that Google Analytics 4 widgets display a "Request access" button when they are showing an "Insufficient permissions" error.

**Comment by tofumatt** [comment]
> they should see the "Request Access" CTA implemented in https://github.com/google/site-kit-wp/issues/5308.

Where should they see this CTA? I assume you mean in the Key Metrics widget area, instead of seeing the 4 "data loading error" widgets, but we should be explicit in the ACs 😄

**Comment by tofumatt** [comment]
Sounds good then 🙂 Moving over to IB 👍🏻

**Comment by hussain-t** [comment]
As @jimmymadon pointed out in the [comment](https://github.com/google/site-kit-wp/issues/7465#issuecomment-1693186409), we currently don't have a support link for the `analytics-4_insufficient_permissions` error. If we change the module slug to `analytics-4`, we will need to create a new support link.

cc: @bethanylang @jamesozzie

**Comment by bethanylang** [comment]
Thanks, @hussain-t! We do have a guide for this (https://sitekit.withgoogle.com/documentation/troubleshooting/dashboard/#insufficientpermissionsanalytics), so we should just need to update the [error MVP mapping doc](https://docs.google.com/spreadsheets/d/12x39d7j0GNqha0m7s4-Y3P5SwK9wwgxxxDnWp3svSKg/edit?resourcekey=0-IngulwDvPmI4SEq2g-f4rA#gid=0). I can get an Asana task set up for @jamesozzie and @eugene-manuilov to work on this update.

**Comment by techanvil** [comment]
Hey @hussain-t, this IB is looking good. I think it would be worth adding a note to refactor `GA4SettingsView` to use the new `getServiceEntityAccessURL()` selector (although this should be obvious enough during implementation). Other than that, this looks good to go!

**Comment by techanvil** [comment]
Hi @hussain-t, I've assigned this to you in QA in order to update the QAB as discussed in https://github.com/google/site-kit-wp/issues/7465#issuecomment-1705082295.

**Comment by hussain-t** [comment]
Thanks, @techanvil. I've updated the QAB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that "Request Access" button is now showing when a/c only have GA4 property.
- Tested when only GA4 property is enabled.
- Tested when both GA4 and UA properties are enabled, and dashboard view is GA4.
- Verified  that the title of the error block reads "Insufficient permissions in Analytics 4" instead of "Insufficient permissions in Analytics."
- Verified that clicking on the "Request Access" CTA redirects the user to the same popup within the GA4 Admin console that appears when clicking the "Edit in Analytics" link on the Settings page.
- Verified that the "Request Access" CTA is also visible in both the WordPress Admin Bar and the WordPress Dashboard widgets specifically for GA4. 
- Verified that these changes have not adversely affected the existing "Edit in Analytics" link within the Settings page.
- Verified that "Request Access" button is now showing under key metrics tile. https://github.com/google/site-kit-wp/issues/7465.


**Note :** Note that an analytics-4_insufficient_permissions error code will be introduced to redirect to [the relevant documentation](https://sitekit.withgoogle.com/documentation/troubleshooting/dashboard/#insufficientpermissionsanalytics), although this hasn't been implemented yet. Therefore, this part of the AC can't be fully tested now. Please refer to this https://github.com/google/site-kit-wp/issues/7465#issuecomment-1705082295.

<details>

**When only GA4 is connected**

https://github.com/google/site-kit-wp/assets/94359491/403e16b4-f4df-410e-8e82-52a36aa80f02

**Edit in analytics link:**

https://github.com/google/site-kit-wp/assets/94359491/17453ada-b2e1-41f0-9b5c-d70b47b2315b

When both GA4 and UA properties are **enabled**


https://github.com/google/site-kit-wp/assets/94359491/7c834ddd-68fe-44ca-855b-bc0396402e06

</details>
