### ISSUE TITLE
User Input question page loses the previous answers if page is reloaded after answering one or more questions

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7494]
## Bug Description

This is an odd behavior I noticed, when one or more question is answered but the page is reloaded for some reason (accidental refresh or reopening closed tab), the page remains on the correct (second or third) question and answering them takes user to review screen, but the answers given before the reload is missing. Also, the save button is not disabled in this state but it does nothing. See the screencast below

## Steps to reproduce
1. Answer one or two user input question. 
2. Refresh the page
3. Finish answering remaining questions 
4. See the issue in Review screen. 

## Screenshots

[screen-capture (3).webm](https://github.com/google/site-kit-wp/assets/6187401/731e807d-bb35-4181-a036-1c45d848b230)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Save` button on the User Input `preview` screen should be disabled unless all questions have  been answered. 
* The error message that is displayed when a question doesn't have answer (ie. `Please select an answer`) should no longer be visible when user answers them using `Edit` panel before the inline editor is collapsed. 
* This should be sufficient to handle the edge case of reloading, and no further actions regarding the reload behavior is needed at the moment as it is an edge case. 

## Implementation Brief

* In `assets/js/components/user-input/UserInputPreview.js`:
    * Determine if any question is not answered (ie. `hasError`) by using `hasErrorForAnswer`.
    * If any of the question has error. disable the `Save` button. 
    * As the button will be disabled if any question is not answered, we no longer need to check for the error in `onSaveClick`. This function should therefore be removed and the `submitChanges` should be directly passed as the `onClick` handler of `Save` button. 

### Test Coverage

* No changes needed. 

## QA Brief

- Set up Site Kit with the Analytics module.
- In the KMW setup CTA, choose to get tailored metrics.
- Answer through the questions and reach the review screen.
- At the review screen, reload your page.
- You should see that you've lost your answers.
- Verify that the "Save" button is disabled.
- Try answering the questions again in the review screen by using the "Edit" actions.
- Verify that the "Save" button is enabled back after all the questions have been answered.
- Verify that the "Please select an answer" error message disappears as soon as an answer is selected.

## Changelog entry

* Improve Key Metrics questionnaire so that its submission requires all questions to be answered.

**Comment by aaemnnosttv** [comment]
@kuasha420 this seems like a minor edge case but something we should address. I suppose we could either use some kind of temporary storage on the client until the questions are submitted, or perhaps the best option would be to reset the URL and current question based on the answers provided on load. That is – when navigating to a specific question, the current question would be reset to the first unanswered question. Temporary answer storage on the client wouldn't solve the root issue here if the browser were closed or the page were navigated to directly later as the stored data may not exist anymore which would result in the same problem we're trying to solve here. Any other ideas?

**Comment by kuasha420** [comment]
@aaemnnosttv I have added 2 points on the AC based on our discussion today. Feel free to have a look and refine them as needed. Cheers!

**Comment by kuasha420** [comment]
@techanvil Thank you, I have added a 3rd clarifying point in AC to say that no change is needed at the moment for the reload behavior.

**Comment by techanvil** [comment]
Thanks @kuasha420! I think that's enough to clear things up. That being the case, these AC LGTM. :white_check_mark:

**Comment by nfmohit** [comment]
Hi folks! 👋 

I started taking a look at this and it appears that the ACs have already been met, most likely as a part of #7543. Here's a screencast:

https://github.com/google/site-kit-wp/assets/20284937/a7e125d2-0c52-47d8-ae75-094b7775857f

What do you think?

CC: @kuasha420 @techanvil @tofumatt @jimmymadon

**Comment by kuasha420** [comment]
@nfmohit Thank you for having a look here, if this is already fixed, we can certainly close it as complete. Can we send this over to QA team with a QAB and a changelog, just to absolutely make sure that the ACs are met, before closing? Cheers!

**Comment by nfmohit** [comment]
> @nfmohit Thank you for having a look here, if this is already fixed, we can certainly close it as complete. Can we send this over to QA team with a QAB and a changelog, just to absolutely make sure that the ACs are met, before closing? Cheers!

Good thought, thank you @kuasha420. I have added a QAB and changelog and moved it to QA directly, as it doesn't require any execution.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Can confirm that the ACs are covered and this works as expected.
  - On reload, the "Save" button is disabled and `Please select an answer` message appears
  - When answering the questions the "Save" button is enabled back after all the questions have been answered.
  - The `Please select an answer` error message disappears as soon as an answer is selected.
  - When I click on the save button, I am redirected to the dashboard and the metric tiles load. 
 - I completed additional testing in the Admin settings for the questions just to make sure this continues to function. 

![image](https://github.com/google/site-kit-wp/assets/73545194/a13f68b1-0ccf-48e1-94c2-d48c51546ad3)
![image](https://github.com/google/site-kit-wp/assets/73545194/d3666072-e09e-46df-950d-4488e61acc6b)
