### ISSUE TITLE
Incorrect Website

### ISSUE THREAD

**Issue by millionstrust** [google/site-kit-wp#750]
When I follow the instructions to reconnect with the latest up-date I'm asked to verify a site that I don't own and have no connection with.
This is happening on more than 1 occasion.
Murray
See screenshot attached.
![Screenshot_2019-10-31 Setup - Site Kit by Google](https://user-images.githubusercontent.com/57199036/67902849-fee89180-fbce-11e9-83ea-c8977c32d6e5.png)

**Comment by ernee** [comment]
@millionstrust thanks for your report! This sounds similar to #746 

Could you run through the troubleshooting steps below to rule out any conflicts:

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Install Site Kit in a new [incognito window](https://imgur.com/ALzgiHp)

If the incorrect domain name still appears, can you please share the following:

1. Any [console errors](https://imgur.com/KyLAzgH) that appear
2. Your WordPress [Site Health information](https://imgur.com/Rtkmsba)
3. Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by shaneedwardtaylor** [comment]
this just started happening on my site regarding a domain called silimports.com out of China...

I have never heard of that domain until today...

**Comment by ernee** [comment]
Thanks for the additional report @shaneedwardtaylor ! We're investigating the issue. 

Would it be possible for you to send a screencast of the setup process when you get the issue (you could use something like [Recordit](https://recordit.co/) to share it with us)? What we're looking for is the URLs at each step in the address bar. You can also provide the URLs at each step leading to the incorrect domain name showing. 

@millionstrust if you're able to provide that as well that would be helpful.

**Comment by ernee** [comment]
@millionstrust and @shaneedwardtaylor we were able to resolve the issue and it's available in the new release version 1.0.0 now in the [WordPress Plugin repository](https://wordpress.org/support/plugin/google-site-kit/). Please update, and go through the setup process. If you have any further questions or concerns please post in the [support forums](https://wordpress.org/support/plugin/google-site-kit/). Thanks again!
