### ISSUE TITLE
Site Kit thinks I'm a different domain?

### ISSUE THREAD

**Issue by shaneedwardtaylor** [google/site-kit-wp#751]
So I already installed the plugin and verified everything with the oauth keys... been working fine

this is a fairly fresh install of WP btw..

then a few days later, the plugin puts this error at the top of wp admin:

Setup Error (code: missing_verification). Re-authenticate with Google

So I click the link, go through the steps, and then google thinks that I'm from the following domain when ive never heard of silimports.com ....

Verify site ownership
Let's verify your ownership of www.silimports.com. We'll need to add a verification token to your site HTML code.

Proceed
Cancel
2
Allow www.silimports.com to access Google Account data
3
Set up Search Console

Did I get hacked or something? I only have 5 plugins on my site, 4 are definitely verified but one is an under construction plugin, and im guessing they are doing something sneaky?  Anyways, has anyone else encountered a problem like this?

**Comment by shaneedwardtaylor** [comment]
and to be clear, im not using a caching plugin and the other 4 plugins im using are by 2 authors that I know and pay for...

**Comment by shaneedwardtaylor** [comment]
![Screenshot from 2019-10-30 19-19-55](https://user-images.githubusercontent.com/8797609/67910970-5b559d80-fb4a-11e9-88cc-08305d111609.png)

**Comment by jamesozzie** [comment]
@shaneedwardtaylor Thanks for reporting, very useful to know it's occurring on a clean install also. A similar issue was reporting in #746 and #750. Are you directed back to the Site Kit dashboard, and if so are you able to see any information or add other modules?

If possible can you also share as much of the below as possible, so we can investigate further?
- Your [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any [console errors](https://i.imgur.com/KyLAzgH.png) you see once directed back to your Site Kit dashboard
- [XHR Response](https://i.imgur.com/jLBwBdH.png) on any page where you see an error if any

**Comment by CCOSTAN** [comment]
I am also having this issue.  It is pointing me to another domain.

**Comment by shaneedwardtaylor** [comment]
im using a linux machine and my screencast is a .mp4 format, and it wont upload here. can i email it to someone?

this time its going to a different domain...

**Comment by swissspidy** [comment]
Hi all!

Thanks for your report. There was a temporary issue that since has been resolved.

In the meantime, we've also released version 1.0.0 stable of Site Kit by Google. We'd love for you all to download it from WordPress.org: https://wordpress.org/plugins/google-site-kit/

Since this marks sort of a fresh start for the plugin, it means you'd need to re-add your site.
