### ISSUE TITLE
No Ellipsis on Tiles for Long Content and Product Titles on View Only Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7527]
## Bug Description

I noticed that on the view only dashboard for `Most popular content by pageviews` and `Most popular products by pageviews` Key Metric tiles, there isn't an ellipsis when the title is too long. 

One does appear on each title on KMW tiles on the main dashboard so I feel we should be consistent.

View only - text only
<image src="https://github.com/google/site-kit-wp/assets/1721319/f03a822a-467b-417c-8741-b21256707738">

Main dashboard - links
<image src="https://github.com/google/site-kit-wp/assets/1721319/03bffb28-b8bc-4ae6-a986-bbdb8bda37f1">

## Steps to reproduce

1. Set up Site Kit with Analytics. (Use a site that has GA4 data like oi.ie) 
2. Install WooCommerce 
2. On the User Input CTA, click on the `I’ll pick metrics myself`link
3. In the metrics panel select `Most popular content by pageviews` and `Most popular products by pageviews` 
4. Set up Dashboard sharing for Analytics
5. Login as a non admin user, i.e. Editor
6. See the content and products do not have an an ellipsis

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the view only dashboard (logged in as a non-authenticated user), the "Most popular content by pageviews" and "Most popular products by pageviews" tiles should shorten long page titles with an ellipsis (`…`) at the end, similar to viewing them as an authenticated admin on the main dashboard.

## Implementation Brief

* Within `_googlesitekit-km-widget-tile.scss`:
    * Add the following properties to the `.googlesitekit-km-widget-tile__table-plain-text`  class:
    ```css
    overflow: hidden;
    text-overflow: ellipsis;
    ```

### Test Coverage

* No new tests required.

## QA Brief

* Follow the steps from `Steps to reproduce` from above in the bug description
* Verify that long content tiles have Elipsis present now

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by zutigrm** [comment]
Leaving it for the future sprint in which it will be included.

**Comment by wpdarren** [comment]
@zutigrm @jimmymadon just leaving a note here that `Top pages by returning visitors` also doesn't have any ellipsis for view only dashboard.  We might want to ensure that this is fixed for all news key metric tiles too.

**Comment by bethanylang** [comment]
Thanks @wpdarren! I'm going to earmark this for Sprint 112 so we can take care of this as we wrap up NKMT and KMW.

**Comment by zutigrm** [comment]
@wpdarren thanks for pointing that out. Fix introduced here is targeting the table view tiles component, which is used in different metrics widgets, including the ones you mentioned.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The ellipsis is now appearing on all long titles within the tiles.  
- Checked KMW and NKMW tiles including the ones highlighted in the product and new ones added recently.
- Tested on small viewports too. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/3b23e7c5-97fc-4715-ae2a-3f2c12190182)
![image](https://github.com/google/site-kit-wp/assets/73545194/984a5804-f21a-483b-850a-0d9a61024d64)
![image](https://github.com/google/site-kit-wp/assets/73545194/afe18c4f-6d8a-4f99-9084-13e3f867df15)

</details>
