### ISSUE TITLE
Add reset button to the setup flow

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#753]
## Feature Description

Currently, the only way to reset the plugin if the setup flow not completed is to delete and re-install the plugin. This is painful when something goes wrong with the setup flow which leads users to a dead end. I suggest to add a reset button in the setup flow which would wipe what ever value was set to the DB.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the landing page shown to users who haven't completed the setup flow, add a "Reset Site Kit" link next to the "Start setup" button. 
* Clicking this link would have the same effect as clicking the "Reset" link in Admin settings (deleting any credentials and preferences)

![reset](https://user-images.githubusercontent.com/13304791/67972398-e304e000-fc0e-11e9-940d-db32b7e2aaea.png)

## Implementation Brief

* Extract new `ResetButton` component from existing button in `SettingsAdmin`
* Add `ResetButton` next to the _Start Setup_ button in `assets/js/components/setup/setup-proxy.js`

## Changelog entry

* Display a reset button alongside the setup button so that the plugin can also be reset before completing the initial flow.

**Comment by felixarntz** [comment]
IB ✅

**Comment by adamsilverstein** [comment]
This passed QA in my testing, moving to Approval.

### Testing Procedure
* Install plugin and activate, don't complete setup.
* Visit Dashboard screen showing setup CTA, note reset button:
![image](https://user-images.githubusercontent.com/2676022/67987745-33267700-fbfc-11e9-8355-781901fe592d.png)

* Go thru setup flow
* Use manage sites link to revoke site access
* Return to site & revoked access modal, note reset link:

![image](https://user-images.githubusercontent.com/2676022/67987877-83053e00-fbfc-11e9-9f36-9eacb496374b.png)

* Test clicking the "Reset Site Kit" link: I verified this did actually reset my settings (after activating again, previous configuration was cleared).

One possible issue I noticed: there is no confirmation that the reset completed, and the same screen shows after resetting, with the reset link still available - potentially confusing users. 

This issue passes QA in that it adds the required reset link, however it would be worth following up with a separate issue to ensure:

* A confirmation message is shown to users when they reset Site Kit and
* Ideally, the "Reset Site Kit" link should not be available when the site is already in a reset state, eg when first setting up or immediately after a reset.
