### ISSUE TITLE
Replace FID with INP

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7530]
## Feature Description

As noted in #7065, the Chrome team [recently announced](https://web.dev/inp-cwv/) that the _Interaction to Next Paint_ (INP) web vital metric is no longer experimental and will replace _First Input Delay_ (FID) when it becomes stable in March 2024.

![image](https://github.com/google/site-kit-wp/assets/1621608/faef3bc0-c82a-42c1-a221-7a036bfdb846)

While #7065 relates to the second phase in the graphic above, this issue is about the third/final phase.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* FID should be removed as a metric from the PageSpeed widget
* Any adaptations related to differing numbers of metrics between lab and field metrics should be removed now that both tabs will consistently have 3 metrics each
* The tooltip added to INP in #7685 should be updated to the following **(TBC)**  
	> INP is a new Core Web Vital that replaced FID in March 2024.
* **This change must be merged at a time so that it is included in a Site Kit release as closely as possible to March 12, 2024.** See https://web.dev/blog/inp-cwv-march-12 for background.

## Implementation Brief

- In `assets/js/modules/pagespeed-insights/components/common/FieldReportMetrics.js`
    - [ ] Update the first object following the component function opener and remove the `FIRST_INPUT_DELAY_MS` line
    - [ ] In the first conditional check for the presence of the current 4 field metrics, remove the `! firstInputDelay`, leaving only `! largestContentfulPaint && ! cumulativeLayoutShift && ! interactionToNextPaint` checks, retain correct formatting
    - [ ] In the returned list of `<ReportMetric>` components, remove the `<ReportMetric>` component with the title `First Input Delay`
    - [ ] In the `<ReportMetric>` component with title `Interaction to Next Paint`, change the `hintText` textual value preceding the `<LearnMoreLink>` component to read as follows: `INP is a new Core Web Vital that replaced FID in March 2024.` and retain the existing `<LearnMoreLink>` component
- In `assets/js/modules/pagespeed-insights/components/common/LabReportMetrics.js` 
    - [ ] In the return statement containing the list of `<ReportMetric>` components, find and remove the placeholder `<ReportMetric>` component with the title `Filler Content`
    - [ ] Update the (now last) `<ReportMetric>` component (previously the one before the filler one), add a `hintText` prop with a component value of `<br />`, i.e `hintText=<br />`, this retains the correct and matching container heights for the "In the Lab" and "In the Field" views
- Update VRT tests as necessary 
 
### Test Coverage

* Update VRT reference images as required given the removal of FID and subsequent height changes to both "In the Lab" and "In the Field" views, as well as textual changes within `hintText`.

## QA Brief

* Ensure that GA4 is connected
* Visiting the dashboard, navigate to the "Speed" section:
    * Validate that First Input Delay (FID) is no longer a valid metric displayed in the list in the "In the Field" tab
    * Validate that Interaction to Next Paint (INP) is still present in the list in the "In the Field" tab
    * Validate that the INP hint text now reads "INP is a new Core Web Vital that replaced FID in March 2024."
        * Validate that the Learn More link remains as prior
    * Validate that the tab container height does not shift and remains equal for content within the "In the Lab" and "In the Field" content container

## Changelog entry

* Replace First Input Delay core web vital with Interaction to Next Paint in PageSpeed Insights module.

**Comment by bethanylang** [comment]
@aaemnnosttv I see this is assigned to Mariya – is this for her to review the AC or is there something else that needs to be done here? Thanks!

**Comment by felixarntz** [comment]
@aaemnnosttv Checking in here, partially regarding the above question.

While we still shouldn't launch this anytime soon, it may be good to open a PR with these changes soon. You could put in a "request changes" to block it from accidentally getting merged.

It's probably still _very_ early at this point, but maybe we should start moving this issue through the pipeline some time before the end of the month (and then keep it at "code review" even when technically approved). This will allow us to ship this even short-term as soon as we have the go-ahead.

**Comment by felixarntz** [comment]
cc @adamsilverstein for awareness

**Comment by bethanylang** [comment]
Thanks @felixarntz! I chatted with @aaemnnosttv on this and we're going to work on #7685 in our next sprint, which begins a week from today. Evan is going to look into the approach on this issue (#7530) to ensure that we're ready to release this once the switchover has been made.

**Comment by felixarntz** [comment]
@aaemnnosttv @bethanylang Can this be added to the upcoming release for March 11 please? See https://web.dev/blog/inp-cwv-march-12: March 12 is the cutoff date where the change will be rolled out. I've also updated the ACs accordingly.

If at all possible and reasonable from your perspective, could the release potentially be delayed to the day after so that it's exactly on March 12? It's not a must-have, but if it's not a big deal, then let's do it then.

In any case, let's get this done for the upcoming release.

**Comment by bethanylang** [comment]
Thanks @felixarntz! While it's usually not an issue to delay the release by a day, we've promised a time-sensitive feature (adding Consent Mode for compliance with the Digital Markets Act) for Monday, March 11 and I think we may be locked into that date. I'll check with Mariya and get back to you here!

@aaemnnosttv I'll move this over to IB; are you able to work on that ASAP so that we can work on this in the current sprint? cc @ivonac4

**Comment by felixarntz** [comment]
Thanks @bethanylang. In that case, as mentioned, sticking with the original date is fine.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- First Input Delay (FID) is no longer a valid metric displayed in the list in the "In the Field" tab
- Next Paint (INP) is still present in the list in the "In the Field" tab
- The INP hint text now reads "INP is a new Core Web Vital that replaced FID in March 2024."
- The Learn More link remains as prior
- The tab container height does not shift and remains equal for content within the "In the Lab" and "In the Field" content 

- Tested this for mobile and desktop PSI tests.  
- Tested this on main, entity and view only dashboard. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/a21582f2-9119-4c28-a3c7-55e9692b32a3)
![image](https://github.com/google/site-kit-wp/assets/73545194/c438c266-4a75-4180-bc94-3287a02b03ae)
![speed](https://github.com/google/site-kit-wp/assets/73545194/45562d91-6dcf-421b-9295-7ede97b30c41)

</details>
