### ISSUE TITLE
Fix the `AdminBarSessionsGA4` and `AdminBarUniqueVisitorsGA4` stories.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7535]
## Feature Description

The Storybook stories for the `AdminBarSessionsGA4` and `AdminBarUniqueVisitorsGA4` components are no longer displaying correctly, with the loading state being displayed for all stories.

E.g.:

![image](https://github.com/google/site-kit-wp/assets/18395600/67acb2ab-2e99-42e3-8366-e3aae6e8e54f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Storybook stories for the `AdminBarSessionsGA4` and `AdminBarUniqueVisitorsGA4` components should be restored to their correctly working states.

## Implementation Brief

* In both `assets/js/components/adminbar/AdminBarSessionsGA4.stories.js` & `assets/js/components/adminbar/AdminBarUniqueVisitorsGA4.stories.js`:
  * In the `setupRegistry` argument function for each story variant, dispatch the`MODULES_ANALYTICS_4` `receiveIsGatheringData` action. Except for the "gathering data" story variant, the action parameter should be `false`. For the "gathering data" story variant, it should be `true`.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
IB ✅
