### ISSUE TITLE
User Input errors should be updated when answers change, not when the panels collapse

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7543]
## Bug Description

When User Input questions are edited in the Admin settings and answers that would cause an error upon saving are given—and the "Confirm changes" button is greyed out, the error messages are not updated until the panel is closed and the answers reset, as seen here:

https://github.com/google/site-kit-wp/assets/90871/0be682d3-fe6d-4bd2-9a23-8dccd99eede7

We should update the error messages to be recalculated when answers are updated, given it can be done offline. Or we should reset the messages when the panel is opened/answers are reset, to avoid a scenario like above where an error appears without an error in the answers.

## Steps to reproduce

1. Enable `ga4Reporting` and `userInput` flags.
2. Setup Analytics and Key Metrics.
3. Go to settings, and click on `Admin Settings` tab.
4. Under `Key Metrics` edit `What are your top goals for this site?` option.
5. Remove all checked items, then click "Cancel"
6. Click "edit" on `What are your top goals for this site?` option again.
7. Note the "Please select at least 1 answer" error message despite an answer being selected

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* An error message should not appear for previous answers given that have been reset (eg. errors should not appear if answers were reset and the current selection is valid)
* Error messages for user input questions in the Settings > Admin panel should be updated when the answer changes or should be reset when the panel is open, not only when it is collapsed. Either option is fine, but the result is that in either case when the steps to reproduce above are used, no errors should appear at step 7.

## Implementation Brief

* In `assets/js/components/user-input/UserInputPreview.js`:
    * Do not pass `errorMessage` and `onCollapse` props to the `<UserInputPreviewGroup />` elements. 
    * Remove any unused variables and imports.
* In `assets/js/components/user-input/UserInputPreviewGroup.js`:
    * Remove  `errorMessage` and `onCollapse` props. 
    * Remove the call to `onCollapse` function from `toggleEditMode` callback. 
    * Use the `error` (rename the variable to `errorMessage` for clarity) that's obtained from `getErrorMessageForAnswer` for the error message in both `p.googlesitekit-error-text`. 
    * Finish and merge #7649. 

### Test Coverage

* Fix failing tests. 

## QA Brief

- Use the "Steps to reproduce as above and verify that the error message does not appear when an answer is selected.
- The associated PR introduces some refactoring surrounding the user input review/settings code. Please perform a smoke test on the user input functionality to ensure it works as expected and reports errors correctly.

## Changelog entry

* Fix a bug that caused an error message for the User Input questions not to appear until after it is closed.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that An error message is not appearing for previous answers given that have been reset .
- No error appearing at step 7.
- Done smoke testing around user input settings and it's functionality working as expected.

<details>


https://github.com/google/site-kit-wp/assets/94359491/c026900e-4c56-46c3-b0e7-8efd5161a474

</details>
