### ISSUE TITLE
Add GA event tracking for Key Metrics (Dashboard).

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7544]
## Feature Description

The purpose of this issue is to add various GA events to the Key Metrics feature for users who have opted in to the anonymous usage data reporting.

The scope of the issue is the Key Metrics widgets and selection panel that appear on the Dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given Key Metrics related actions. Note, none of these events need a label.

### Key Metrics Setup CTA Widget

These events should be tracked in response to actions on Key Metrics Setup CTA notification widget that appears on the Dashboard.

| Event Name                   | Category                            | Trigger            | Condition                                                                |
| ---------------------------- | ----------------------------------- | ------------------ | ------------------------------------------------------------------------ |
| view_notification            | {viewContext}\_kmw-cta-notification | Element visibility | User views "KMW setup CTA" notification on the dashboard                 |
| confirm_get_tailored_metrics | {viewContext}\_kmw-cta-notification | Click              | User clicks "Get tailored metrics" CTA in the notification               |
| confirm_pick_own_metrics     | {viewContext}\_kmw-cta-notification | Click              | User clicks "I'll pick metrics myself" secondary CTA in the notification |
| dismiss_notification         | {viewContext}\_kmw-cta-notification | Click              | User clicks "Maybe later" below the notification                         |
| tooltip_view                 | {viewContext}\_kmw                  | Element visibility | The tooltip is rendered                                                  |
| tooltip_dismiss              | {viewContext}\_kmw                  | Click              | User clicks "X" to close the tooltip                                     |

### Key Metrics tiles and selection panel

These events should be tracked in response to actions on the Key Metrics tiles and selection panel.

| Event Name             | Category                   | Trigger            | Condition                                                        |
| ---------------------- | -------------------------- | ------------------ | ---------------------------------------------------------------- |
| change_metrics         | {viewContext}\_kmw         | Click              | User clicks "change metrics" CTA above the KMW tiles             |
| add_metric_view        | {viewContext}\_kmw         | Element visibility | An "add metric" tile appears in the KMW section of the dashboard |
| add_metric_click       | {viewContext}\_kmw         | Click              | User clicks "add metric" tile within the KMW section             |
| metrics_sidebar_view   | {viewContext}\_kmw-sidebar | Element visibility | The KMW sidebar appears                                          |
| metrics_sidebar_save   | {viewContext}\_kmw-sidebar | Click              | User clicks "save selection" CTA                                 |
| metrics_sidebar_cancel | {viewContext}\_kmw-sidebar | Click              | User clicks "cancel" CTA                                         |

#### view_notification
* In `assets/js/components/KeyMetrics/KeyMetricsCTAContent.js` component, ensure that GA4 module is connected using a variable like `ga4Connected`. This will be needed to distinguish if Key metrics setup widget is shown first time for setup, or due to analytics being disconnected.
  * Call ``trackEvent( `${viewContext}_kmw-cta-notification`, 'view_notification' )`` when the widget is in-view and `ga4Connected` is true.
 
#### confirm_get_tailored_metrics
* In `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js` file, edit the button:
  * Include `onClick` that should fire callback function. In that function include `trackEvent`:
 ```js
  const onButtonClick = useCallback(
	async ( event ) => {
		event.preventDefault();
		await trackEvent( `${viewContext}_kmw-cta-notification`, 'confirm_get_tailored_metrics' );
	},
	[ viewContext ]
  );
```
#### confirm_pick_own_metrics
* In the previous file `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`
  * Modify the existing callback function that is called on `onClick` in `Link` component - `openMetricsSelectionPanel`, by  Including tracking - ``trackEvent( `${viewContext}_kmw-cta-notification`, 'confirm_pick_own_metrics' );``
 
#### dismiss_notification
* In the same file `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`
  * Locate `dismissCallback` function, and include the tracking function - ``await trackEvent( `${viewContext}_kmw-cta-notification`, 'dismiss_notification' );``
 
#### tooltip_view
* In the same file `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js` include the new (bool) variable for `hasBeenInView` that should be updated once the tooltip appears for the first time, eq `const [ hasBeenInView, setHasBeenInView ] = useState(false);` 
* Include new `useEffect` block that should check if `! hasBeenInView && isTooltipVisible`, to send tracking - ``trackEvent( `${viewContext}_kmw`, 'tooltip_view' );`` and update `setHasBeenInView( true )`

#### tooltip_dismiss
* In the same file `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js` 
  * Under `AdminMenuTooltip` pass a new prop `onDismiss` and create a new callback function for tooltip dismiss, which will send tracking - ``trackEvent( `${viewContext}_kmw`, 'tooltip_dismiss' );``

#### change_metrics
* Go to `assets/js/components/KeyMetrics/ChangeMetricsLink.js` file
  * Locate `openMetricsSelectionPanel` function and include tracking function - ``trackEvent( `${viewContext}_kmw`, 'change_metrics' );``

#### add_metric_view
* Go to `assets/js/components/KeyMetrics/AddMetricCTATile.js`
  * Include `inView` and `hasBeenInView` logic like for `view_notification` event section above
  * Attach ref to div wrapper `<div className="googlesitekit-km-add-metric-cta-tile">`
  * When ref is in `inView && ! hasBeenInView` send tracking event ``trackEvent( `${viewContext}_kmw`, 'add_metric_view' );``
 
#### add_metric_click
* In the same file `assets/js/components/KeyMetrics/AddMetricCTATile.js`
  * Go to `openMetricsSelectionPanel` function 
  * Add event tracking - ``trackEvent( `${viewContext}_kmw`, 'add_metric_click' );``

#### metrics_sidebar_view
* Go to `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.js` file
  * Locate `onSideSheetOpen` function, include a tracking call there - ``trackEvent( `${viewContext}_kmw-sidebar`, 'metrics_sidebar_view' );``
 
#### metrics_sidebar_save
* Go to `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`
  * Locate `onSaveClick` function, and in `if ( ! error )` condition, add ``await trackEvent( `${viewContext}_kmw-sidebar`, 'metrics_sidebar_save' );``
 
#### metrics_sidebar_cancel
* In the same file `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`
  * Locate function - `onCancelClick`, and add ``trackEvent( `${viewContext}_kmw-sidebar`, 'metrics_sidebar_cancel' );`` 

### Test Coverage

* No changes needed

## QA Brief

* Enable tracking, by checking `Help us improve Site Kit by sharing anonymous usage data.` either in Admin settings, or during Site kit setup
* Ensure all the events defined in AC are being fired using Google Analytics debugger chrome extension.

## Changelog entry

* N/A

**Comment by zutigrm** [comment]
Thanks for the feedback @tofumatt For the first point:
* The notification is a widget rendered in `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`, which has different checks before proper component is choose, which includes the notification - `KeyMetricsCTAContent`. That component holds the content displayed if key metrics is not setup, for which we want to trigger event. And we want to include proposed prop since this widget can be shown also once analytics is disconnected, so that way we are triggering only event when setup metrics notification is shown. The IB proposes the usage of in view checks (and useIntersection, etc) by referencing to the mentioned file `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js` where inView logic can be reused from. This does not cover only CTA, but the whole notification/widget when it is viewed
* For the second point - yes, thanks, you are correct, I edited IB to include track event on click separately

**Comment by tofumatt** [comment]
Ah, makes sense! I've clarified the wording a bit on that point but looks good. 🙂 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm For `tooltip_view` event I'm getting multiple entries in the log and all have event category maindashboard_kmw. Is this expected to have multiple entries for this event ?

![image](https://github.com/google/site-kit-wp/assets/94359491/492282f5-f2f0-4b5f-9a4d-49e12f58675f)

**Comment by zutigrm** [comment]
@mohitwp Thanks for checking. Hm, should be only one event. Will check what's going on

**Comment by mohitwp** [comment]
### QA Update ❌ 

@zutigrm 

- Tested this on dev environment.
- Verified this events are getting trigger as per defined action in AC.
- Verified that events name and Category name is same as per AC.

**Issue**
**1)** As mentioned [above](https://github.com/google/site-kit-wp/issues/7544#issuecomment-1729242610). For `tooltip_view` event I'm getting multiple entries in the log and all have event category maindashboard_kmw. So, please check this.

![image](https://github.com/google/site-kit-wp/assets/94359491/492282f5-f2f0-4b5f-9a4d-49e12f58675f)

**2)** Apart from that, all other events are appearing 2 times. Kindly confirm if this is also correct or not ?

<details>

**View_notification**

![image](https://github.com/google/site-kit-wp/assets/94359491/129c0e5d-b46f-4992-b31e-46b1e15a7a43)

**confirm_get_tailored_metrics**

![image](https://github.com/google/site-kit-wp/assets/94359491/70acb87e-7873-4c8a-a70f-a2b903bbf506)

**confirm_pick_own_metrics**

![image](https://github.com/google/site-kit-wp/assets/94359491/96275d9d-7f0c-498a-a630-046a638583aa)

**dismiss_notification**

![image](https://github.com/google/site-kit-wp/assets/94359491/f50f4079-b2fc-4ba4-91fa-472d433c0bf1)

**tooltip_dismiss**

![image](https://github.com/google/site-kit-wp/assets/94359491/d7774682-1c2a-4e56-979a-f874d7bd8ca1)

**change_metrics**

![image](https://github.com/google/site-kit-wp/assets/94359491/cde19a6a-07cc-4a44-9511-587d568a66fb)

**add_metric_view**

![image](https://github.com/google/site-kit-wp/assets/94359491/942f0558-b710-4319-8bc5-e97647034212)

**add_metric_click**

![image](https://github.com/google/site-kit-wp/assets/94359491/5fceb7c1-cc43-4915-ab3a-9883e2738044)

**metrics_sidebar_view**

![image](https://github.com/google/site-kit-wp/assets/94359491/4f11e51d-60d1-4a30-b173-bd25c396c1bd)

**metrics_sidebar_save**

![image](https://github.com/google/site-kit-wp/assets/94359491/54cf66d2-0b80-4293-8cdb-688e2d5153a3)

**metrics_sidebar_cancel**

![image](https://github.com/google/site-kit-wp/assets/94359491/18f7fab2-9739-44f3-bae8-0ba16e21a4cb)


</details>

**Comment by zutigrm** [comment]
@mohitwp 
1) I am looking into this one now
2) Yes, this is ok, as event is sent once but to 2 different properties, UA-x one and G-xx one, for example:
<img width="586" alt="image" src="https://github.com/google/site-kit-wp/assets/10414808/599ce745-638e-417c-b650-ad4e893fa747">

**Comment by kuasha420** [comment]
@mohitwp Back to you to check and confirm that the number 1 observation from your previous comment is fixed. Cheers.

**Comment by mohitwp** [comment]
QA Update ⚠️ 

@zutigrm Issue 1 reported [above](https://github.com/google/site-kit-wp/issues/7544#issuecomment-1729325349) is resolved on Develop environment. But fix is not merged into the main branch. Can you please merge it in merge ?

cc @EvanHerman 

Tested on both main and dev environment.

Main Branch -

![image](https://github.com/google/site-kit-wp/assets/94359491/05c753c8-ef8b-45a2-b624-11e70225f1c0)

**Comment by zutigrm** [comment]
@mohitwp Thanks for letting me know. Per [conversation](https://10up.slack.com/archives/CBKKQEBR9/p1695328003444369?thread_ts=1695326826.987809&cid=CBKKQEBR9), seems it should be on the main. @kuasha420 Can you confirm this? Should I create a new PR to main, or maybe this is something build related?

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Issue 1 reported [above](https://github.com/google/site-kit-wp/issues/7544#issuecomment-1729325349) is resolved on main environment. 
- Verified all events as per AC.
- Verified this events are getting trigger as per defined action in AC.
- Verified that events name and Category name is same as per AC.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/3d7bb216-df28-4b80-a25d-8f01e06a1dd1)

![image](https://github.com/google/site-kit-wp/assets/94359491/a59301c9-c9d7-45c2-aa02-8bce282a3757)

**View_notification**

![image](https://github.com/google/site-kit-wp/assets/94359491/129c0e5d-b46f-4992-b31e-46b1e15a7a43)

**confirm_get_tailored_metrics**

![image](https://github.com/google/site-kit-wp/assets/94359491/70acb87e-7873-4c8a-a70f-a2b903bbf506)

**confirm_pick_own_metrics**

![image](https://github.com/google/site-kit-wp/assets/94359491/96275d9d-7f0c-498a-a630-046a638583aa)

**dismiss_notification**

![image](https://github.com/google/site-kit-wp/assets/94359491/f50f4079-b2fc-4ba4-91fa-472d433c0bf1)

**tooltip_dismiss**

![image](https://github.com/google/site-kit-wp/assets/94359491/d7774682-1c2a-4e56-979a-f874d7bd8ca1)

**change_metrics**

![image](https://github.com/google/site-kit-wp/assets/94359491/cde19a6a-07cc-4a44-9511-587d568a66fb)

**add_metric_view**

![image](https://github.com/google/site-kit-wp/assets/94359491/942f0558-b710-4319-8bc5-e97647034212)

**add_metric_click**

![image](https://github.com/google/site-kit-wp/assets/94359491/5fceb7c1-cc43-4915-ab3a-9883e2738044)

**metrics_sidebar_view**

![image](https://github.com/google/site-kit-wp/assets/94359491/4f11e51d-60d1-4a30-b173-bd25c396c1bd)

**metrics_sidebar_save**

![image](https://github.com/google/site-kit-wp/assets/94359491/54cf66d2-0b80-4293-8cdb-688e2d5153a3)

**metrics_sidebar_cancel**

![image](https://github.com/google/site-kit-wp/assets/94359491/18f7fab2-9739-44f3-bae8-0ba16e21a4cb)


</details>
