### ISSUE TITLE
Add GA event tracking for Key Metrics (Questionnaire & Admin screens).

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7545]
## Feature Description

The purpose of this issue is to add various GA events to the Key Metrics feature for users who have opted in to the anonymous usage data reporting.

The scope of the issue is the Key Metrics questionnaire screen and the KM section on the Admin screen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given Key Metrics related actions.

### Questionnaire

These events should be tracked in response to actions on the questionnaire that appears when clicking "Get tailored metrics" on the Key Metrics Setup CTA Widget, or "Personalize your metrics" on the Key Metrics section in the Admin screen.

| Event Name                      | Category           | Label                              | Trigger            | Condition                                              |
| ------------------------------- | ------------------ | ---------------------------------- | ------------------ | ------------------------------------------------------ |
| site_purpose_question_view      | {viewContext}\_kmw |                                    | Element visibility | The site purpose question screen appears               |
| content_frequency_question_view | {viewContext}\_kmw |                                    | Element visibility | The content frequency question appears                 |
| site_goals_question_view        | {viewContext}\_kmw |                                    | Element visibility | The site goals question appears                        |
| question_advance                | {viewContext}\_kmw | Identifier of the current question | Click              | Click "next" button on a question                      |
| question_return                 | {viewContext}\_kmw | Identifier of the current question | Click              | Click "back" button on a question                      |
| summary_submit                  | {viewContext}\_kmw |                                    | Click              | User clicks on "Save" in the summary (only in preview) |

### Questionnaire and Admin screen

These events should be tracked in response to the corresponding actions both in the questionnaire and when editing the answers on the Admin screen.

| Event Name                        | Category           | Label                                                                                                                                                                      | Trigger            | Condition                                                      |
| --------------------------------- | ------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | -------------------------------------------------------------- |
| site_purpose_question_answer      | {viewContext}\_kmw | One of: sell_products_or_service, monetize_content, publish_blog, publish_news, share_portfolio, other                                                                                  | Click              | User picks responses to the site purpose question              |
| content_frequency_question_answer | {viewContext}\_kmw | One of: daily, weekly, monthly, never, other                                                                                                                               | Click              | User picks responses to the content frequency question         |
| site_goals_question_answer        | {viewContext}\_kmw | One or more of: retaining_visitors, improving_performance, finding_new_topics, growing_audience, expanding_business, generating_revenue, help_better_rank, understanding_content_performance, encourage_to_post, other | Click              | User picks responses to the site goals question                |
| summary_view                      | {viewContext}\_kmw |                                                                                                                                                                            | Element visibility | Summary appears (as preview or in settings panel)              |
| question_edit                     | {viewContext}\_kmw | Identifier of the question to edit the answer for                                                                                                                          | Click              | User clicks on "edit" for a question                           |
| question_update                   | {viewContext}\_kmw | Identifier of the question to edit the answer for                                                                                                                          | Click              | User clicks on "update" / "submit" for a question when editing |

## Implementation Brief

* In the `assets/js/components/user-input/UserInputQuestionnaire.js`: 
  * Modify this existing `useEffect` hook - https://github.com/google/site-kit-wp/blob/develop/assets/js/components/user-input/UserInputQuestionnaire.js#L75-L79, by including additional `activeSlug` checks with switch or if statements. Depending on the question group which slug is active, send event names:`site_purpose_question_view`, `content_frequency_question_view` or `site_goals_question_view`, with category `{viewContext}_kmw`. When `activeSlug` is equal:
    * `USER_INPUT_ANSWERS_PURPOSE` - event name is `site_purpose_question_view` 
    * `USER_INPUT_ANSWERS_GOALS` - event name is `site_goals_question_view`
    * `USER_INPUT_ANSWERS_POST_FREQUENCY` - event name is `content_frequency_question_view`
  * To track events, import and use `trackEvent` function from `assets/js/util/index.js`, eq. ``trackEvent( `${viewContext}_kmw`, 'site_purpose_question_view' )`` and so on for remaining 2 question groups.
* `question_advance`, `question_return`, and `summary_submit` events are already implemented - https://github.com/google/site-kit-wp/blob/develop/assets/js/components/user-input/UserInputQuestionnaire.js#L89-L108, what should be edited is the category, instead of  `trackEvent( viewContext, 'question_return', steps[ activeSlugIndex ] );` change to ``trackEvent( `${viewContext}_kmw`, 'question_return', steps[ activeSlugIndex ] );`` and same for `question_advance` and `summary_submit`
* Then in `assets/js/components/user-input/UserInputPreview.js`
  * Add new variable that will check for current question that is being edited:
```js
const currentlyEditingSlug = useSelect( ( select ) =>
	select( CORE_UI ).getValue( USER_INPUT_CURRENTLY_EDITING_KEY )
);
```  
  *  Then use it to check against `slug` and determine which event to send:
```js
useEffect( () => {
	if ( currentlyEditingSlug === USER_INPUT_ANSWERS_POST_FREQUENCY ) {
		trackEvent(
			`${ viewContext }_kmw`,
			'content_frequency_question_view'
		);
	} else if (
		currentlyEditingSlug === USER_INPUT_ANSWERS_PURPOSE ||
		currentlyEditingSlug === USER_INPUT_ANSWERS_GOALS
	) {
		trackEvent(
			`${ viewContext }_kmw`,
			`content_${ currentlyEditingSlug }_question_view`
		);
	}
}, [ currentlyEditingSlug ] );
```

### Questionnaire and Admin Screen
* In `assets/js/components/user-input/UserInputSelectOptions.js` file
  * import `USER_INPUT_QUESTION_POST_FREQUENCY` constant from `assets/js/components/user-input/util/constants.js` since it is the only one not matching the naming, (it is `postFrequency` but event name should be `frequency`), and it will be used to dynamically match the event name `content_${slug}_question_answer`.
  * Then in `onClick` function using the `useCallback` create new variables for dynamic slug and for event name that will be dynamically built using the first variable:
```jsx
const eventSlug = USER_INPUT_QUESTION_POST_FREQUENCY === slug ? 'frequency' : slug;
const eventName = `content_${eventSlug}_question_answer`;
```
  * Then refactor a bit `setUserInputSetting` used in that block (`onClick`) - https://github.com/google/site-kit-wp/blob/develop/assets/js/components/user-input/UserInputSelectOptions.js#L99-L102, take the value out into variable so it can be shared with `trackEvent` function that should be imported and the `setUserInputSetting`, so it looks something like this:
```jsx
const eventSlug = USER_INPUT_QUESTION_POST_FREQUENCY === slug ? 'frequency' : slug;
const eventName = `content_${eventSlug}_question_answer`;
const checkedValue = Array.from( newValues ).slice( 0, max );

trackEvent( `${viewContext}_kmw`, eventName, JSON.stringify( checkedValue ) ); // 3rd param is expected to be string, and in case of site_goals_question_answer it can be an array with up to 3 items.

setUserInputSetting(
	slug,
	checkedValue
);
```
  * This will take care of both admin and dashboard side tracking, as this component is shared between these screens.
* `summary_view`, `question_edit`, and `question_update` events are already implemented, just the category needs to be adjusted to `{viewContext}_kmw` from `viewContext`.
### Test Coverage

* No changes needed.

## QA Brief

* Ensure all the events defined in AC are being fired using Google Analytics debugger.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Do we need to be passing refs/etc. around and doing in-view type checks for these questions?

The questions are "full-screen" and as soon as they're the "active" question (can be checked in `UserInputQuestionnaire` using `activeSlug`/`activeSlugIndex`), so we can probably send each of the `trackEvent` calls for the question being _seen_ in the `UserInputQuestionnaire` component using a `useEffect`.

Similarly for `UserInputPreview`—I don't think we need to be passing things down to the child components when the parent knows about which step is active and can send the track event calls directly.

**Comment by zutigrm** [comment]
@tofumatt you are correct, indeed. Thank you, IB is updated.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 I found a number of issues with the GA Events that I have listed below:

These are all for editing the survey in Admin settings:

1.  `What is the main purpose of this site?`

When I select `Share a business card or portfolio to represent me or my company online` the event label is  `share_portfolio` which is different than the AC. 

![image](https://github.com/google/site-kit-wp/assets/73545194/b177adaa-e345-4b76-93a1-2823f934e218)

When I select `Sell products or services` the event label is `sell_products_or_service` which is different than the AC. 

![image](https://github.com/google/site-kit-wp/assets/73545194/91fffabc-0fde-4da1-aa7b-c36466b2e5a8)

2. `What are your top goals for this site?`

None of the event labels match the AC.  e.g. When I select `Retain visitors, turn them into loyal readers or customers` the event label is `retaining_visitors` which is different than the AC.  Or `Improve speed and performance` the event label is 
`Improve speed and performance ` I found differences for all answers. 

![image](https://github.com/google/site-kit-wp/assets/73545194/202792c5-5acc-448d-988e-9a38475af431)

3. For the `summary_view` GA event, the `eventCategory` is `settings` but according to the AC, it should be `settings_kmw`

![image](https://github.com/google/site-kit-wp/assets/73545194/4eeb15eb-6336-4fdf-aedd-f1b900e6cd52)

5. When I edit a question and then click on the Confirm changes button, no GE event is getting fired. According to the AC, I should see `question_update` GA event. 

![image](https://github.com/google/site-kit-wp/assets/73545194/8af12601-f161-4eb2-af1a-4c0f62eec1ce)


**Verified:**

- The `Questionnaire` GA events are fired as per the AC.  Screenshots below. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/363d205c-7b6a-4062-9962-11d654370a4e)
![image](https://github.com/google/site-kit-wp/assets/73545194/e5b5e291-087e-4e0f-b3e5-c41d1116933a)
![image](https://github.com/google/site-kit-wp/assets/73545194/09c436f0-e250-4c23-b7f7-cc0bee8e4999)
![image](https://github.com/google/site-kit-wp/assets/73545194/6e05169c-3179-4f32-a158-46e3f18d8459)
![image](https://github.com/google/site-kit-wp/assets/73545194/5b961ac6-9491-46a9-9dc4-5e11133f746d)
![image](https://github.com/google/site-kit-wp/assets/73545194/21ed9f05-fd11-4a60-8056-5b307fff806d)

</details>

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `Questionnaire` and `Questionnaire and Admin screen` GA events are fired as per the AC.  Screenshots below. 

The issues highlighted above have been fixed either within the PR or updated AC. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/363d205c-7b6a-4062-9962-11d654370a4e)
![image](https://github.com/google/site-kit-wp/assets/73545194/e5b5e291-087e-4e0f-b3e5-c41d1116933a)
![image](https://github.com/google/site-kit-wp/assets/73545194/09c436f0-e250-4c23-b7f7-cc0bee8e4999)
![image](https://github.com/google/site-kit-wp/assets/73545194/6e05169c-3179-4f32-a158-46e3f18d8459)
![image](https://github.com/google/site-kit-wp/assets/73545194/5b961ac6-9491-46a9-9dc4-5e11133f746d)
![image](https://github.com/google/site-kit-wp/assets/73545194/21ed9f05-fd11-4a60-8056-5b307fff806d)
![image](https://github.com/google/site-kit-wp/assets/73545194/bdacea8a-a7a9-4b5a-a2a9-a4c66672156a)
![image](https://github.com/google/site-kit-wp/assets/73545194/6354f01b-bb39-4ac0-9e5c-21e0ba975874)

</details>
