### ISSUE TITLE
Odd UX when editing User Input questions on review screen

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7546]
## Feature Description

Bug bash issue created by @wpdarren: https://app.asana.com/0/1204713925711993/1205134946142641/f
When a user clicks on the edit link to open up the answers to the question, there's nothing obvious that tells them that they should click edit again to close the answers and edit another question.  I feel we should have something like in dashboard sharing that they have to click on an icon to close the question.  Not sure what others feel like, but its a little confusing. 

I will add that when you go to Admin settings and edit the questions there, the experience is much more what I would have expected here. You have to click on a button to save the changes.

![image](https://github.com/google/site-kit-wp/assets/1721319/4ca66f0e-5b75-494a-8506-77fa60b505b2)

@sigal-teller's comments:
Is it possible after the user clicks on edit and the question is opened  to replace it with "Close"?
Also there is a "confirm changes" button that is disabled until the user perform any changes. Per my discussion with @jimmymadon on slack, I think we should apply here the same behavior we're planning for the metrics selection panel.
That means that there will be a "Save" button and when the user changes his answer then the button text will be replaced with "Apply changes" (let's keep the same wording for consistency).

Here's the link for the discussion: https://10up.slack.com/archives/C01CA828ZPZ/p1693821394393229

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In both the User Input Preview accordions, i.e. when answering the questionnaire the first time via the CTA or when [editing the answers via Admin Settings](https://github.com/google/site-kit-wp/assets/1721319/f6083b4c-9bd8-41db-abab-e565bf68890e), the "Edit" button in the accordion should turn to "Close" when the accordion panel is opened for a particular question.
* When editing the User Input answers via Admin Settings (after they have already been completed), [the "Confirm changes" button](https://github.com/google/site-kit-wp/assets/1721319/f6083b4c-9bd8-41db-abab-e565bf68890e) should be renamed to "Save" and should always be enabled, even if the answers to a question have not been changed.
    * If the answer to a question has changed, this button should be renamed to "Apply changes".

## Implementation Brief

* In `assets/js/components/user-input/UserInputPreviewGroup.js`:
  * Within the `Link` component that renders the Edit link, check if `isEditing` is true. If it is, render the string `Close`, otherwise, keep the string `Edit`.
  * Within the `settingsView` block, modify the string to be `Save` instead of `Confirm Changes`. However, check the value of `hasSettingsChanged`. If it is true, modify the string to be `Apply Changes`.

### Test Coverage

* No new tests required.

## QA Brief

* Setup Site Kit with Analytics connected.
* Click on "Get tailored metrics" to answer the Key Metrics questionnaire.
* Verify the buttons are labelled as per the AC on the "Review your answers" page.
* Save the answers, and navigate to **Settings** > **Admin Settings**.
* Verify the buttons are labelled and behave as per the AC in the Key Metrics section.

Update: Ensure that one of the questions is answered with "Other" in order to verify the bug described [here](https://github.com/google/site-kit-wp/issues/7546#issuecomment-1880564186) no longer occurs.

## Changelog entry

* Update labels for buttons in the User Input questions to have better UX.

**Comment by tofumatt** [comment]
ACs 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ❌  

Tested on dev environment.
@techanvil I noticed that under Admin settings when user changes answer and click on "Apply changes" button then for a few seconds button title gets change to 'Save'. See attached screencast.


https://github.com/google/site-kit-wp/assets/94359491/3641e957-318d-42b9-b4a9-e2797f81e864

**Comment by techanvil** [comment]
> Tested on dev environment. @techanvil I noticed that under Admin settings when user changes answer and click on "Apply changes" button then for a few seconds button title gets change to 'Save'. See attached screencast.

Hi @mohitwp, thanks for raising this. It's a funny one though, I can't reproduce it:

https://github.com/google/site-kit-wp/assets/18395600/36ec7f45-fd7a-43e2-895c-cae6583b6f5e

Please can you retest on a fresh site, and if you can still reproduce the issue, can you send me the login details for your test site?

**Comment by mohitwp** [comment]
@techanvil 

I'm still able to reproduce this issue. Shared site details with you in Slack.


https://github.com/google/site-kit-wp/assets/94359491/dc881505-7b0b-4d6e-8920-ef20a2b24f7b

**Comment by techanvil** [comment]
Thanks @mohitwp! I've identified the problem and raised a PR to fix it. The issue only occurs when one of the questions has been answered with "Other", I should have checked this scenario the first time around :)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified issue reported [above](https://github.com/google/site-kit-wp/issues/7546#issuecomment-1880564186) is now resolved.
- Verified the buttons are labelled as per the AC on the "Review your answers" page.
- Verified the buttons are labelled and behave as per the AC in the Key Metrics section.

<details>


https://github.com/google/site-kit-wp/assets/94359491/7610b204-64bb-40ba-b610-bce28f79cb3a


https://github.com/google/site-kit-wp/assets/94359491/19a531f2-972e-498f-b323-060bbcdeaa4c

</details>
