### ISSUE TITLE
1.0 Migration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#755]
## Summary

As part of the update to version 1.0 - any installation with existing proxy-based authentication need to re-authenticate after upgrading to 1.0 or subsequent release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A site upgrading to version 1.0 which has previously authenticated with the Site Kit proxy must require reauthentication by all users before it can be used
* All users for such a site should be disconnected from Site Kit

## Implementation Brief

* Add a new option for storing the Site Kit database version, starting with `1.0.0`
* If this option does not exist, check the stored Credentials
* If the credentials are for the Site Kit proxy, delete the credentials and trigger a disconnect every user with an access token
* If disconnect is triggered, set the Beta Migration flag in the DB to trigger its notice notifying the user to reauthenticate

## Changelog entry

* N/A

**Comment by ThierryA** [comment]
LGTM! Just to clarify, the `site_id` and `site_secret` needs to be removed as well in addition to disconnecting.

**Comment by aaemnnosttv** [comment]
@ThierryA I've updated the IB to reflect that the credentials should also be deleted 👍
