### ISSUE TITLE
Add a survey trigger to the "Enable enhanced measurement" banner.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7558]
## Feature Description

As discussed on [Slack](https://10up.slack.com/archives/CFFRMC5DE/p1694181167919609?thread_ts=1694171305.910659&cid=CFFRMC5DE), we should add a survey trigger to the banner created via https://github.com/google/site-kit-wp/issues/7461.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the "Enable enhanced measurement" banner is viewed, a survey should be triggered.
* The survey `triggerID` should be: `view_enhanced_measurement_cta`.

Note that we'll also want to ensure there's a corresponding survey on the backend, and this will require collaboration with the SKS engineering team. Cc @eugene-manuilov.

## Implementation Brief

Within the file `assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js`, which will be created in #7461:
- Add a call to the `useMount()` hook.
- Within the hook's callback, conditionally dispatch a call to `triggerSurvey()`, passing the trigger ID `view_enhanced_measurement_cta`.
- The conditions for dispatching `triggerSurvey()` should ensure that the banner is visible, and not dismissed.
- As the implementation of `EnhancedMeasurementActivationBanner` will be using the GA4 Activation Banner as a guide, refer to the way the `view_notification` event is [dispatched in `ReminderBanner`](https://github.com/google/site-kit-wp/blob/3e720e23bb56ffef0ff8e3363ab7c0c001c83913/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/ReminderBanner.js#L93-L100) as a potential guide here.

### Test Coverage

- No new tests needed.
- Ensure existing tests still pass.

## QA Brief

- Setup Site Kit with the `enhancedMeasurement` feature flag enabled and connect GA4.
- Follow the QA steps in #7461 to ensure the "Enable Enhanced Measurement" notification banner appears.
- Using the Chrome devtools network inspector or an HTTP proxy like Proxyman, ensure an HTTP `POST` request is made to `/wp-json/google-site-kit/v1/core/user/data/survey-trigger` with the body:

```
{
  "data": {
    "triggerID": "view_enhanced_measurement_cta"
  }
}
```

The request should be made when this banner appears:
![CleanShot 2023-10-04 at 23 48 53](https://github.com/google/site-kit-wp/assets/90871/cc0dd490-7b68-49fc-9b10-e3e138b0c621)
- Ensure the HTTP request is not made if the notification banner is dismissed and the page is reloaded.

## Changelog entry

* Add a survey trigger to the "Enable enhanced measurement" banner.

**Comment by tofumatt** [comment]
ACs here are good, moving to IB 👍🏻

Might be good to clear the IB with @eugene-manuilov or coordinate with him to make sure the survey is set up on the service during/before execution.

**Comment by eugene-manuilov** [comment]
I have no special information/notes for this trigger in the plugin. The actual survey will be implemented using another task in Asana. So IB for this one can be picked up by anyone who knows how to trigger surveys in the plugin.

**Comment by techanvil** [comment]
Thanks @eugene-manuilov, good to know. Do we have an Asana task for this already, or does one need to be created?

**Comment by bethanylang** [comment]
@techanvil I can create one, but I need a little more info here. Can you tell me how where and how this survey should appear and what data we're intending to collect?

**Comment by techanvil** [comment]
Thanks @bethanylang. As discussed on the linked [Slack](https://10up.slack.com/archives/CFFRMC5DE/p1694181167919609?thread_ts=1694171305.910659&cid=CFFRMC5DE) thread, this will initially just be a stub survey that will help us track use of this banner, although it can be useful later on to collect some additional information. So initially this task should just be to ensure the service can handle the survey request being made to it, it doesn't need to have any additional data collection responsibilities just yet.

**Comment by bethanylang** [comment]
Perfect, thanks much @techanvil! I've created an [Asana task for the creation of the stub survey on the service](https://app.asana.com/0/1204918034934784/1205556422867103/f). cc @eugene-manuilov

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
![CleanShot 2023-10-10 at 20 55 52](https://github.com/google/site-kit-wp/assets/90871/bc65dbbf-8af9-4b41-ba44-e9fafafd2909)

Is it possible you refreshed the page and then triggered that banner again? You'll only see the survey trigger sent at most once a day. I can see it in my above screenshot.

Here's a screencast showing it appearing on an InstaWP site. You can reset the site to reset the survey trigger timeout, and then should be able to see it:

https://github.com/google/site-kit-wp/assets/90871/675265e5-c967-4d91-aa66-573fbdb9c2c8

Note that it won't appear on the refresh/second page load because the survey has already been triggered and won't be triggered again for another 24 hours.

**Comment by wpdarren** [comment]
@tofumatt  I am pretty sure that I didn't refresh the page. As soon as Site Kit was set up with Analytics, the dashboard loaded. I saw a survey network entry appear, and it was pending until I dismissed the Analytics setup and then the Enhanced measurement banner appeared.   I will set up a test again and let you know how I get on.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@tofumatt I think what happened is i clicked on the Analytics setup success notification, but this time the correct survey trigger did appear. Apologies about wasting your time there. 

**Verified:**

- Using the Chrome devtools network inspector an HTTP POST request is made to `/wp-json/google-site-kit/v1/core/user/data/survey-trigger` with the body in thee QAB. 
- The HTTP request is not made if the notification banner is dismissed and the page is reloaded.

![image](https://github.com/google/site-kit-wp/assets/73545194/42397ec8-6d6e-4e54-bdf5-41e9698cb3b8)
