### ISSUE TITLE
Issues with All Traffic module responsiveness on 599px width viewport

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7562]
## Bug Description

While doing site audit on different breakpoints. I found few issues .

1) On 599px width under google site kit all traffic widget both mobile and desktop view options are showing for tabs selection.
Expected - Mobile view tab selection should appear on 599px width
## Steps to reproduce

1. Set up site kit with Analytics.
2. Go to main dashboard.
3. Set viewport width to 599px using dev tool.
4. See issue.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/94359491/79153c5c-cbc1-464f-bcca-f37ca7471b19)

![image](https://github.com/google/site-kit-wp/assets/94359491/0ae9de7b-c489-4bef-88c5-13b9059ba3b2)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Only the mobile view dropdown should be visible for the All Traffic widget at 599px or below.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@mohitwp This bug now seems to be fixed. Can you verify this one more time?

<img width="690" alt="599px" src="https://github.com/google/site-kit-wp/assets/1721319/644d40fc-e83a-4aa2-a6b1-a7c0e070fd87">

<img width="668" alt="600px" src="https://github.com/google/site-kit-wp/assets/1721319/296a1260-6f07-481a-9962-faf5ab2a1ea3">

**Comment by jimmymadon** [comment]
Closing this based on my tests above.
