### ISSUE TITLE
Fix layout shift when showing the Key Metrics section on the Admin Settings screen.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7570]
## Feature Description

When Key Metrics has not yet been set up, there is a brief layout shift on the Admin Settings screen where the Key Metrics section is initially not displayed and the Plugin Status section is at the top, with Key Metrics then appearing and pushing Plugin Status down the screen. It's briefly evident in the attached screencast.

https://github.com/google/site-kit-wp/assets/18395600/327f4741-bb55-4e3d-83fe-66a7b3a15660

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Key Metrics has not yet been setup, there should not be a layout shift as described above on the Admin Settings page when showing the Key Metrics section.

## Implementation Brief
* Using `assets/js/components/settings/SettingsCardKeyMetrics.js`,
	* Check if the `isUserInputCompleted` selector has finished resolving via the `hasFinishedResolution` hook.
	* If it's still resolving, show the `PreviewBlock` component with the height props set as the following:
		* `smallHeigh`: `100`
		* `tabletHeight`: `100`
		* `desktopHeight`: `117`

### Test Coverage
* No tests to be added/updated

## QA Brief

- Set up Site Kit without Key Metrics.
- Go to Site Kit Settings -> Admin Settings.
- Verify that such a layout shift does not exist.
- Test the same with Key Metrics set up.
- Test the same with the Analytics module connected and disconnected.
- Test the same with the Search Console and Analytics module in a gathering data state and not in a gathering data state.

## Changelog entry

* Fix bug that caused a layout shift during loading of Key Metrics data in Site Kit Settings.

**Comment by bethanylang** [comment]
@jimmymadon Are you planning to work on this soon? If not, can you please unassign yourself so someone else can pick up? Thank you!

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- No layout shift exists in the admin settings:
  - Tested with Key Metrics set up.
  - Tested with the Analytics module connected and disconnected.
  - Tested with the Search Console and Analytics module in a gathering data state and not in a gathering data state.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

When the site is in gathering state on search console and analytics, the Admin settings does not load as you can see on the screenshot below.  I wasn't able to recreate this when only search console was connected.  I also was able to load admin settings with a site with data and had KMW set up or not set up. 

![image](https://github.com/google/site-kit-wp/assets/73545194/dec89503-3932-42a4-8d5f-91554a19ad0a)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- No layout shift exists on the admin settings screen. 
  - Tested the same with Key Metrics set up.
  - Tested the same with the Analytics module connected and disconnected.
  - Tested the same with the Search Console and Analytics module in a gathering data state
  - Tested the same with the Search Console and Analytics module in not in a gathering data state.
  - Tested with Analytics disabled but Search Console enabled.
