### ISSUE TITLE
Add `newsKeyMetrics` feature flag

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7572]
## Feature Description

The `newsKeyMetrics` feature flag should be added to Site Kit as a prerequisite for the News Key Metrics Tiles feature development.

[See relevant section in the design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.2w7xzmit4qg4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `newsKeyMetrics` feature flag should be added to Site Kit.
* The `newsKeyMetrics` feature flag should appear in the tester plugin.

## Implementation Brief

* Add a `newsKeyMetrics` feature flag to `feature-flags.json`.

### Test Coverage

* No tests needed.

## QA Brief

* The `newsKeyMetrics` feature flag should appear in the tester plugin.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm I tested this on dev environment using latest version of tester plugin. `newsKeyMetrics` feature flag is not appearing under tester plugin.

![image](https://github.com/google/site-kit-wp/assets/94359491/2c561a09-7fc4-4ffc-880c-209b30e23e2a)

![image](https://github.com/google/site-kit-wp/assets/94359491/af4bcd5b-c68c-4155-a728-05e002b20da1)

![image](https://github.com/google/site-kit-wp/assets/94359491/26ab019c-28f6-430f-adce-7dac5c2d2378)

**Comment by tofumatt** [comment]
That's very strange, I see that too when testing on InstaWP. 🤔 

Strangely it works fine in `develop`:

<img width="213" alt="CleanShot 2023-09-15 at 17 27 11" src="https://github.com/google/site-kit-wp/assets/90871/c7953dff-7b49-4b0b-baaa-2ae40f29d068">

I'm honestly 100% baffled as to why that would fail, I'm not familiar with the tester plugin's code/approach but seems it should be working 🤔. The builds are being uploaded: https://github.com/google/site-kit-wp/actions/runs/6186084648/job/16793293976

**Comment by aaemnnosttv** [comment]
This is good now, there was a hiccup in the build which prevented the updated zips from being uploaded, so the installed SK zip wasn't the latest version that included the flag.

Ready to try again @mohitwp 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

  - Tested on develop environment using tester plugin.
  - Verified newsKeyMetrics feature flag is appearing under tester plugin.

![image](https://github.com/google/site-kit-wp/assets/94359491/10e5c021-6ccb-4581-9990-a784d3d3c0b1)
