### ISSUE TITLE
Add datapoints for Analytics custom dimensions

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7573]
## Feature Description

Datapoints & REST endpoints should be added to the `Analytics_4` class to interact with the Google Analytics Admin service and create/list custom dimensions.

[See relevant section in the design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.u7gmzlh6c8lv).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `Analytics_4` class should receive the following new datapoints if the `newsKeyMetrics` feature flag is enabled:
  - `POST:create-custom-dimension` that will compose a [CustomDimension](https://github.com/googleapis/google-api-php-client-services/blob/main/src/GoogleAnalyticsAdmin/GoogleAnalyticsAdminV1betaCustomDimension.php) and use the [GoogleAnalyticsAdmin/Resource/PropertiesCustomDimensions::create](https://github.com/googleapis/google-api-php-client-services/blob/72e0eacbd51131c954da05edf110d9774f0f5af0/src/GoogleAnalyticsAdmin/Resource/PropertiesCustomDimensions.php#L50-L63) infrastructure to create a custom dimension. Also, see GA Admin API method [properties.customDimensions.create](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1beta/properties.customDimensions/create).

## Implementation Brief

In `includes/Modules/Analytics_4.php`:

#### Update Datapoint Definitions:

* In the `get_datapoint_definitions()` method:
    * If the `newsKeyMetrics` feature flag is enabled, add a new `POST` datapoint called `create-custom-dimension`.
    * The datapoint should require the `https://www.googleapis.com/auth/analytics.edit` scope.

#### Handle the New Datapoint:

* In the `create_data_request()` method:
    * Add a case for the new `create-custom-dimension` `POST` datapoint.
    * Validate the `propertyID` and the `CustomDimension` object passed in the request body. Ensure all required properties are present and valid. See [CustomDimension](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1beta/properties.customDimensions#CustomDimension).
    * Reference the `EnhancedMeasurementSettings` validation logic for a similar implementation. See:
    https://github.com/google/site-kit-wp/blob/f159ac60f1e3104d374c247b9015824a472e00a7/includes/Modules/Analytics_4.php#L717-L731
    * Use the `Google\Site_Kit_Dependencies\Google\Service\GoogleAnalyticsAdmin\Resource\PropertiesCustomDimensions::create` method to create the custom dimension.
    * Return the created custom dimension.

### Test Coverage

* Add PHPUnit test coverage for the new datapoint in `tests/phpunit/integration/Modules/Analytics_4Test.php`.

## QA Brief

* There are no user-facing changes involved in this ticket.
* Set up Site Kit with Analytics 4.
* Enable the `newsKeyMetrics` feature flag.
* To request the `create-custom-dimension` endpoint, use a fetch request snippet like the one below. The following steps explain how to get the snippet.
```js
fetch("http://sitekit.10uplabs.com/wp-json/google-site-kit/v1/modules/analytics-4/data/create-custom-dimension?_locale=user", {
  "headers": {
    "accept": "application/json, */*;q=0.1",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
    "content-type": "application/json",
    "x-wp-nonce": "[REPLACE WITH NONCE]",
    "cookie": "[REPLACE WITH COOKIE]",
    "Referer": "http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-settings",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": JSON.stringify({
    "data": {
      "propertyID": "12345678",
      "customDimension": {
        "description": "New Custom Dimension Description",
        "disallowAdsPersonalization": false,
        "displayName": "New Dimension",
        "parameterName": "googlesitekit_post_author",
        "scope": "EVENT"
      }
    }
  }),
  "method": "POST"
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));
```
* To get a fetch request snippet, perform a POST action from the Site Kit UI. For example, create a web data stream and copy the request from the Network tab in the browser dev tools. 
* Replace the `/create-webdatastream` endpoint with the `/create-custom-dimension` endpoint at the end of the URL.
* Replace the `body` with the one above in the snippet.
* Refer to the screenshot below for copying a request from the network tab.
![Screenshot 2023-09-25 at 12 20 05 PM](https://github.com/google/site-kit-wp/assets/24408261/9d4e68ff-ff80-4067-8951-c3580cd650c3)
* Execute the modified snippet in the browser console.
* Ensure that a network request is made to the `create-custom-dimension` endpoint and the custom dimension is created in the Google Analytics Admin UI.
* Note that the `parameterName` should be unique for each GA4 property. The API will return an error if the same `parameterName` is used.
* Disable the `newsKeyMetrics` feature flag.
* Repeat the above steps and ensure the `create-custom-dimension` endpoint is unavailable and the network request fails.
* Optionally, testing this feature can be simplified with the `createCustomDimension` action once #7574 is merged.

## Changelog entry

* Add datapoint for creating an Analytics custom dimension.

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by nfmohit** [comment]
@techanvil Thank you for reviewing the ACs. I have just added a minor point about the `[properties.customDimensions.list](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1beta/properties.customDimensions/list)` API method that its response should not be cached, based on a recent feedback from Evan in the design doc. I'm moving this back to ACR for you to review. Thanks!

**Comment by techanvil** [comment]
Thanks @nfmohit, it's good to make this point clear. AC LGTM! :white_check_mark:

**Comment by nfmohit** [comment]
One more minor update to the ACs but I'll not send this back to ACR as this is very minor. We no longer need to make `GET:custom-dimensions` shareable as we have decided to use a module setting to persistently store a list of available custom dimensions in the DB, which will be exposed to view-only users. Hence, view-only users don't need to interact with this endpoint.

CC: @techanvil @hussain-t @aaemnnosttv

**Comment by nfmohit** [comment]
Hi folks 👋 

I apologise for the multiple changes here, but with the recent decisions in the design doc about storing the available custom dimensions in a module setting, we no longer need the `GET:custom-dimensions` datapoint. Hence, I've removed that from the ACs. More details [here](https://github.com/google/site-kit-wp/issues/7598#issuecomment-1730716731).

Not sending this back to ACR again as this reduces the scope of the issue instead of adding any overhead.

Thank you for the patience with this one.

CC: @techanvil @hussain-t @aaemnnosttv for visibility.

**Comment by hussain-t** [comment]
I'm sorry, that was a mistake. Thanks for catching it, @aaemnnosttv. I've updated the IB.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Followed the QAB to test this.
- Tested for both cases - when `newsKeyMetrics` feature flag is enabled and when disabled.
- Verified when `newsKeyMetrics `feature flag is enabled  network request is made to the create-custom-dimension endpoint and the custom dimension is created in the Google Analytics Admin UI.
- Verified when `newsKeyMetrics `feature flag is disabled and the create-custom-dimension endpoint is unavailable and the network request fails.

<details>

When `newsKeyMetrics `feature flag is disabled


https://github.com/google/site-kit-wp/assets/94359491/13fe6201-f1ef-4bfb-881f-cba566e3de86


When `newsKeyMetrics `feature flag is enabled


https://github.com/google/site-kit-wp/assets/94359491/ea0e96a8-1a6d-4633-bcac-bc7db129d63e

</details>
