### ISSUE TITLE
Implement datastore infrastructure for Analytics custom dimensions

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7574]
## Feature Description

Infrastructure should be added to the `analytics-4` datastore to interact with the REST endpoints for custom dimensions (being implemented in [#7573](https://github.com/google/site-kit-wp/issues/7573)) to create/list/get them.

[See relevant section in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.riguoayjf5ai).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `modules/analytics-4` datastore should receive a `createCustomDimension` action that will interact with the `POST:create-custom-dimension` datapoint (being implemented in [#7573](https://github.com/google/site-kit-wp/issues/7573)) to create the provided custom dimension.

#### File Structure & Data Shape

* Create a new file named `custom-dimensions.js` within the `assets/js/modules/analytics-4/datastore/` directory.
    * Integrate this new store definition with the existing `analytics-4` main store in `assets/js/modules/analytics-4/datastore/index.js`.
    * Initialize the `customDimensions` state shape to be `undefined`.

* The `customDimensions` state will eventually hold an array of custom dimension objects. See [`CustomDimensions`](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1beta/properties.customDimensions#CustomDimension).

```js
{
    // 12345 = property ID, 678910 = custom dimension ID.
    [
        {
            "name": "properties/12345/customDimensions/678910"
            "parameterName": "googlesitekit_post_author",
            "displayName": "Dimension Name",
            "description": "Dimension description",
            "scope": "EVENT", // It will always be EVENT.
            "disallowAdsPersonalization": false,
        }
    ]
}
```

#### Fetch Stores

* Create a new fetch store for the new `POST` endpoint using `createFetchStore`, with the basename `createCustomDimension`.
* Note that the Google client API requires the property ID to be provided. It will be obtained from the server within the `custom-dimensions` endpoint. It will be implemented in #7573.
* Use the `createReducer` function from the `Immer` library to create the reducer for this fetch store.

#### Action: `createCustomDimension( propertyID: string, customDimensions Type<CustomDimensions> )`

* Create a validation to ensure the `customDimensions` argument adheres to the `CustomDimensions` object schema. Reference the `EnhancedMeasurementSettings` validation logic for a similar implementation.
https://github.com/google/site-kit-wp/blob/2df15abb1078725f186d11fc93254f25caaeab8a/assets/js/modules/analytics-4/datastore/enhanced-measurement.js#L36-L61
* Integrate this validation into the `createCustomDimension` fetch store action.
* Invoke the fetch store’s action using the provided `propertyID` and `customDimensions` parameters.
* Note: Always set the `scope` field to `EVENT` within custom dimensions.

### Test Coverage

* Create a new test suite within `assets/js/modules/analytics-4/datastore/custom-dimensions.test.js`.
* Implement tests to validate the `createCustomDimension` action.

## QA Brief

* There are no user-facing changes involved in this ticket.
* Set up Site Kit with Analytics 4.
* Enable the `newsKeyMetrics` feature flag.
* Run the following action to create a custom dimension in the browser console:
```js
googlesitekit.data.dispatch('modules/analytics-4').fetchCreateCustomDimension("123456789",
  {
    "description": "Custom Dimension Description",
    "disallowAdsPersonalization": false,
    "displayName": "Custom Dimension",
    "parameterName": "googlesitekit_post_author",
    "scope": "EVENT"
  })
```
* Replace `123456789` with your GA4 property ID.
* Ensure that a network request is made to the `create-custom-dimension` endpoint and the custom dimension is created in the Google Analytics Admin UI.
* Note that the `parameterName` should be unique for each GA4 property. The API will return an error if the same `parameterName` is used.
* Disable the `newsKeyMetrics` feature flag.
* Repeat the above steps and ensure the `create-custom-dimension` endpoint is unavailable and the network request fails.

## Changelog entry

* Add datastore infrastructure for creating custom dimensions in GA4.

**Comment by tofumatt** [comment]
ACs here are good 👍🏻

**Comment by tofumatt** [comment]
IB ✅

**Comment by nfmohit** [comment]
Hi folks! 👋 

I apologise for the very late change here, but with the recent decisions in the design doc about storing the available custom dimensions in a module setting, we no longer need the `getCustomDimensions` & `getCustomDimension` selectors. Hence, I've removed that from the ACs. More details [here](https://github.com/google/site-kit-wp/issues/7598#issuecomment-1730716731).

I'm sending this back to you @hussain-t for removing the relevant details from the IB and reducing the estimate for the issue.

Thank you for the patience with this one.

CC: @tofumatt @hussain-t @aaemnnosttv for visibility.

**Comment by hussain-t** [comment]
@nfmohit, I have updated the IB accordingly. 

@tofumatt, I have sent it back to you in IBR to review the changes.

**Comment by tofumatt** [comment]
Looks good to me! 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t I have two observations that I would like to share:

1. When enabling the `newsKeyMetrics` feature flag and returning to the dashboard, the errors below appears

`GET https://attractive-anaconda-jg8ki.instawp.xyz/wp-json/google-site-kit/v1/core/user/data/key-metrics?_locale=user 404 (Not Found)` and `Google Site Kit API Error method:GET datapoint:key-metrics type:core identifier:user error:"No route was found matching the URL and request method."`

![image](https://github.com/google/site-kit-wp/assets/73545194/297f9d80-a424-4552-bf39-3de2115c88e7)

2. I followed the QAB instructions and when the code was run in console (with the GA4 property changed) a permissions popup appeared and additional errors appeared in the console.   I also checked the network tab and while `create-custom-dimension` endpoint appears, it does have an error too. 

`POST https://attractive-anaconda-jg8ki.instawp.xyz/wp-json/google-site-kit/v1/modules/analytics-4/data/create-custom-dimension?_locale=user 403 (Forbidden)` and `googlesitekit-api-02a3763dfaa2e498b7ae.js:1 Google Site Kit API Error method:POST datapoint:create-custom-dimension type:modules identifier:analytics-4 error:"You’ll need to grant Site Kit permission to create a new Analytics 4 custom dimension on your behalf."`

I noted in the QAB it says:

> Note that the parameterName should be unique for each GA4 property. The API will return an error if the same parameterName is used.

I did try adding in another parameterName but the same issue occured.  Does it have to be a specific parameter name? 

Right now I am unable to pass the QAB, but wondered if you could check the instructions, and see if anything is missed that's important for us to be able to test this.   By the way, I am using oi.ie. as my GA4 property, and I tested this with the the `userInput` feature flag enabled and disabled just in case. 

![image](https://github.com/google/site-kit-wp/assets/73545194/a736e874-2cef-4fad-8219-6c0f31a6c818)

![image](https://github.com/google/site-kit-wp/assets/73545194/e15e97dc-7158-42bc-b7f7-23c990beb2ad)

**Comment by hussain-t** [comment]
Thanks, @wpdarren. Note that testing this issue should be performed similarly to #7573; however, the only difference is using the new `createCustomDimension` action.

>1. When enabling the newsKeyMetrics feature flag and returning to the dashboard, the errors below appears

This error isn't related to this issue. Perhaps you should enable the `userInput` feature flag as well.

>2. I followed the QAB instructions and when the code was run in console (with the GA4 property changed) a permissions popup appeared and additional errors appeared in the console. I also checked the network tab and while create-custom-dimension endpoint appears, it does have an error too.

This is expected if the user doesn't have the **EDIT** scope permissions. However, once granted you should be able to make the API call. If you're unable to make the call or grant permissions, I think the user doesn't have access to the given property.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@hussain-t thank you. I was using oi.ie GA4 property, which is view only. 

**Verified:**

The newsKeyMetrics feature flag is enabled:
- A network request is made to the create-custom-dimension endpoint
- The custom dimension is created in the Google Analytics Admin UI.

The newsKeyMetrics feature flag is disabled:
- The create-custom-dimension endpoint is unavailable and the network request fails.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/31f462e2-975a-4c5e-a7b4-f973f92b3880)
![image](https://github.com/google/site-kit-wp/assets/73545194/55929b68-c592-4e9f-aefd-722e6a3348b2)
![image](https://github.com/google/site-kit-wp/assets/73545194/29fd1870-f337-46a9-88f8-080db02b7adb)
![image](https://github.com/google/site-kit-wp/assets/73545194/188e22d5-30f9-4098-ab3b-b9bdff73dbb9)
![image](https://github.com/google/site-kit-wp/assets/73545194/b2917542-abaf-4849-8d70-acde6096ec28)

</details>
