### ISSUE TITLE
Create "Most engaging pages" key metric widget tile

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7578]
## Feature Description

![image](https://github.com/google/site-kit-wp/assets/20284937/345627f3-a840-4e8e-bf72-e179e69ffe7a)
(screenshot for reference - see Figma for latest version)

A new key metric widget tile should be added for "Most engaging pages".

See:
1. [Table of metrics in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.5u6oy5c2u65e).
2. [List of metrics in PRD](https://docs.google.com/document/d/1UZ2VXOxpsY3GiHgQncZIb73Uy-xVf15MWJi46QkK_X0/edit?resourcekey=0-dB9ROp2h3ZYhqoyYBMTzvw#bookmark=id.usf86uc2bsda).
3. [Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60062&mode=design&t=nUObjDPmn7ra177i-4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new component should be created for the "Most engaging pages" key metric widget tile and should be displayed within the Key Metrics Widget area if its widget slug is added to the `widgetSlugs` array of key metrics settings.
  - The component should look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60062&mode=design&t=nUObjDPmn7ra177i-4).
  - Its widget slug should be `kmAnalyticsMostEngagingPages` (so that it is consistent with the design doc).
  - The metric tile title should be `Most engaging pages`.
  - Its description tooltip should say `Pages with the highest engagement rate`.
  - This metric should be dependent on the `analytics-4` module, so it should only be rendered in the key metrics widget area if GA4 is connected, otherwise, `ConnectGA4CTATileWidget` should be rendered (similar to existing GA4-dependent metric tiles). It should also not be shown to view-only users who do not have shared access to GA4.
- The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
  - Metrics: `engagementRate` and `screenPageViews`
  - Dimensions: ~`unifiedPagePathScreen` and `pageTitle`~ UPDATE: `pagePath` should be sufficient here. See this [comment](https://github.com/google/site-kit-wp/issues/7584#issuecomment-1731209171).
  - Order by metric: `engagementRate` descending, then by `screenPageViews` descending
  - Filter by: `screenPageViews` >= "Average number of `screenPageViews`" (average screen page views can be calculated as part of a separate report).
- Values:
  - It should be a table pattern metric tile, with the `pageTitle` showing up as the first column, and `engagementRate` showing up as the second column (with percentage).
- The metrics & dimensions used in the reports for this tile should be allow-listed for view-only users.
- This metric should be available for selection in the key metrics selection panel only if the `newsKeyMetrics` feature flag is enabled.

## Implementation Brief

* In `assets/js/modules/analytics-4/components/widgets/`, create a new `MostEngagingPagesWidget.js` component.
  * Use the `PopularContentWidget.js` file as a starting point, then make the following changes:
    * To calculate the `averagePageViews` needed for the filter, create a new `pageViewsReport` with the following options:
    ```javascript
    const pageViewsReportOptions = {
      ...dates,
      dimensions: [ 'pagePath' ],
      metrics: [ { name: 'screenPageViews' } ],
    };
    ```
    * Calculate the average by dividing the total number of page views (`screenPageViews` metric totals) by the number of pages (`rowCount`) returned from the report:
    ```javascript
    const averagePageViews =
      Math.round(
        pageViewsReport?.totals?.[ 0 ]?.metricValues[ 0 ].value /
          pageViewsReport?.rowCount
      ) || 0;
    ```
    * Update `reportOptions` to include the metrics and dimensions as per the AC and filter the metrics by the `averagePageViews`:
    ```javascript
    const reportOptions = {
      ...dates,
      dimensions: [ 'pagePath' ],
      metrics: [  'engagementRate', 'screenPageViews'  ],
      orderby: [
        {
          metric: { metricName: 'engagementRate' },
          desc: true,
        },
        {
          metric: { metricName: 'screenPageViews' },
          desc: true,
        },
      ],
      metricFilters: {
        screenPageViews: {
          filterType: 'numericFilter',
          operation: 'GREATER_THAN_OR_EQUAL',
          value: { int64Value: averagePageViews },
        },
      },
      limit: 3,
    };
    ```
    * When computing the `columns`, ensure the `engagementRate` is displayed as a percentage (1 = 100%, 0.89 = 89%). Since this is the first in the list of metrics, the `field` paths within the columns calculation should be the same.
    * Update the `loading` and `error` states to check for the resolution of the additional `pageViewsReport`.
    * Update the `title` and `infoTooltip` props of the `<MetricTileTable>` component as per the AC.
* In `assets/js/googlesitekit/datastore/user/constants.js`:
  * Export a new constant for defining the new widget's slug: `KM_ANALYTICS_MOST_ENGAGING_PAGES = 'kmAnalyticsMostEngagingPages'`
  * Add this constant to the `keyMetricsGA4Widgets` array.
* In `assets/js/modules/analytics-4/index.js`:
  * Register the new key metric widget exactly the same as other key metric widgets. However, wrap the registration using the new `newsKeyMetrics` feature flag.

### Test Coverage

* Add storybook stories using `PopularContentWidget.stories.js` as a starting point and create stories for the Ready, Zero, Loading and Error states. 
    * Add VRT snapshots for the Ready and Zero states.

## QA Brief

* Ensure the new `newsKeyMetrics` feature flag is enabled / turned on in the Site Kit Tester plugin settings.
* Verify that the "Most engaging pages" widget appears in the Metrics selection panel. Select this metric and verify the ACs. 
* Ensure this metric does not appear in the metrics panel if the feature flag above is not enabled.
* Verify the metric works on both the view-only as well as authenticated dashboards.
* Verify the correct metric values by searching for applicable report views in GA4 itself.
* Verify/test the stories, they will appear under `Key Metrics > MostEngagingPagesWidget`
* We've made a minor modification to the loading of the Least engaging pages KMW tile report - so please give that KMW tile a quick smoke test. 

## Changelog entry

* Implement the "Most engaging pages" key metric widget tile.

**Comment by tofumatt** [comment]
ACs 👍🏻

**Comment by marrrmarrr** [comment]
@jimmymadon thanks for doing this research. Looks like using average for page views gives a more balanced distribution than using the median, so I'd suggest going with that calculation for the purposes of KMW:
Order by engagementRate (desc), then by screenPageViews but filter by screenPageViews >= 10 (Average page views):

For "least engaging" pages, I think from the user perspective is slightly different, as it would help them to see which pages are doing absolutely terribly, so bounceRate of 100% is more interesting than bounceRate of 70%. (It's also likely that the high bounce rate and the low traffic are correlated -- probably some people see e.g. the title and don't even bother, while others check the page out and then quickly leave). 
Having this information, the site owner can look at the pages where visitors leave the quickest and determine how to alter their content strategy. It does look like median in this case allows to show the lower engagement rates.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by 10upsimon** [comment]
Note to reviewer: The 2x failing e2e tests appear to be as a result of current known test issues.

**Comment by nfmohit** [comment]
Sending this to MR as I'd appreciate a second pair of eyes just to confirm that the report request parameters are accurate, thank you!

**Comment by nfmohit** [comment]
Hi folks 👋 

It looks like as soon you select this key metric tile to show up in the dashboard, the SK dashboard crashes.

Here is a screenshot:
![image](https://github.com/google/site-kit-wp/assets/20284937/7988a17f-f3bd-4e51-b513-003ab8830584)

Also discussed internally [here](https://10up.slack.com/archives/CBKKQEBR9/p1697134629913199).

Thank you!

**Comment by mohitwp** [comment]
### QA Udpate ⚠️ 


@10upsimon I've using oi.ie site for testing and noticed that that the pages are sorted first by their engagement rate, and then, in the event of a tie in engagement rate, they are further sorted based on the highest number of views. 
**For ex**: If 5 pages have same engagement rate 100% then we are selecting top 3 pages on the basis of highest number of views among 5. 
**Q)** Am I understanding this logic correctly? Because there are many pages with a low engagement rate but a high number of views. Let me know if my understanding is not correct ?

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/40514cfb-85f9-4c4f-b596-8a06a60e44cd)

![image](https://github.com/google/site-kit-wp/assets/94359491/3a690936-f922-44fd-b4ba-6492cdbd7495)

![image](https://github.com/google/site-kit-wp/assets/94359491/9d970f76-8b15-440c-b7b8-a687bb64fe69)

![image](https://github.com/google/site-kit-wp/assets/94359491/82109df7-8aec-40b3-a74c-ec04bfe0cc34)


</details>

**Screenshots for Pass cases-** 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/acc9e68f-3ce8-44d9-bfdb-e03230d20266)

![image](https://github.com/google/site-kit-wp/assets/94359491/8bd52f4a-6da6-45f9-aacd-aa8589359a46)

If Analytics is not connected

![image](https://github.com/google/site-kit-wp/assets/94359491/1a99fbd9-9704-4ac6-8d9b-1f4165248c12)

If GA4 is not shared widgets are not showing on 'View Only Dashboard'

![image](https://github.com/google/site-kit-wp/assets/94359491/9ec33f75-1b71-4d18-bcfc-5c45236fa671)

If GA4 module is shared

![image](https://github.com/google/site-kit-wp/assets/94359491/b889c6e6-ba2f-4448-8f39-d4f08a0037ea)

Verified widget data is showing pages with highest views and 

![image](https://github.com/google/site-kit-wp/assets/94359491/50b54358-b754-4746-90b5-1bc127281111)

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev enviroment.
- [Above](https://github.com/google/site-kit-wp/issues/7578#issuecomment-1764217070) reported issue is resolved now.
- Verified when analytics is in zero data state.
- Verified that the "Most engaging pages" widget appears in the Metrics selection panel. 
- Verified that this metric does not appear in the metrics panel if the feature flag above is not enabled.
- Verified  the metric works on both the view-only as well as authenticated dashboards.
- Verified that widget is showing correct data.
- Verified the stories, under Key Metrics > 'MostEngagingPagesWidget' . 


<details>


When analytics is in zero data state -

![image](https://github.com/google/site-kit-wp/assets/94359491/73c64577-7d2a-467a-bb6b-6cb367c2ca7e)


![image](https://github.com/google/site-kit-wp/assets/94359491/acc9e68f-3ce8-44d9-bfdb-e03230d20266)

![image](https://github.com/google/site-kit-wp/assets/94359491/8bd52f4a-6da6-45f9-aacd-aa8589359a46)

If Analytics is not connected

![image](https://github.com/google/site-kit-wp/assets/94359491/1a99fbd9-9704-4ac6-8d9b-1f4165248c12)

If GA4 is not shared widgets are not showing on 'View Only Dashboard'

![image](https://github.com/google/site-kit-wp/assets/94359491/9ec33f75-1b71-4d18-bcfc-5c45236fa671)

If GA4 module is shared

![image](https://github.com/google/site-kit-wp/assets/94359491/b889c6e6-ba2f-4448-8f39-d4f08a0037ea)

Verified widget data is showing pages with highest views and 

![image](https://github.com/google/site-kit-wp/assets/94359491/50b54358-b754-4746-90b5-1bc127281111)

</details>
