### ISSUE TITLE
Update answer-based metrics for news publishers

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7580]
## Feature Description

The tailored metrics display logic will need to be updated so that if a user selects “**_Publish news content_**” for the “**_What is the main purpose of this site?_**” question in the Key Metrics Widget questionnaire, the following metrics will be displayed in the Key Metrics Widget:

1. Pages per visit
2. Visit length
3. Visits per visitor
4. Most engaging pages

[See relevant section in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.2qxkyl4ng96v).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- When the user answers the Key Metrics questionnaire, Site Kit automatically selects a pre-defined list of metrics to display in the Key Metrics Widget area. If the `newsKeyMetrics` feature flag is enabled, this pre-defined list should be updated so that if the user selects “**_Publish news content_**” for the “**_What is the main purpose of this site?_**” question in the Key Metrics Widget questionnaire, the following metrics will be displayed in the Key Metrics Widget area:
  1. Pages per visit
  2. Visit length
  3. Visits per visitor
  4. Most engaging pages

## Implementation Brief

* Within `key-metrics.js`:
    * In the `switch` statement, return the widget slugs of the widgets within the ACs (using their existing constants) for the `publish_news` case if the `newsKeyMetrics` feature is enabled (use the `useFeature` custom hook to determine this).

### Test Coverage

* Update `key-metrics.test.js` to cater for the above change.

## QA Brief

* With the `userInput` feature flag enabled and `newsKeyMetrics` flag disabled, test that answering the User Input questionnaire with "Publish news content" as the answer to the first questions will continue to show the original key metrics widgets: New visitors, Returning visitors, Top traffic source, Engaged traffic source.
* Now with both the above feature flags enabled, ensure answering the same answer to the user input questionnaire now loads the metrics in the ACs.

## Changelog entry

* Update the predefined selection of Key Metrics for for news publishers.

**Comment by techanvil** [comment]
Hey @nfmohit, these AC look good - however, one small aspect to consider is that it _could_ be interpreted to be referring exclusively to the flow that's triggered from the Key Metrics Widget Setup CTA, whereas the questionnaire can also be entered from the Admin Settings screen, via the "Personalize your metrics" CTA.

Maybe it would be better to either omit the mention of the Key Metrics Widget Setup CTA and simply say, "When the user answers the Key Metrics questionnaire...", or alternatively it could mention both the Key Metrics Widget Setup CTA and the Admin Settings screen as entry points... What do you think?

**Comment by nfmohit** [comment]
Very good point, updated, thank you @techanvil!

**Comment by techanvil** [comment]
Thanks @nfmohit! IB LGTM :white_check_mark:

**Comment by tofumatt** [comment]
@jimmymadon Can we easily test this one? If not, can you fill in the test section at least so it isn't empty? 🙂 I think we can add tests for it thought 🤔 

Looks good otherwise.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Verified when both `userinput` and `newkeymetrics` feature flags are enabled below listed widgets are showing -

-    1. Pages per visit
-    2. Visit length
-    3. Visits per visitor
-    4. Most engaging pages

- When only `userinput` feature flag is enabled below listed widgets are showing -

   1.    New visitors
   2.    Returning visitors
   3.    Top traffic source
   4.    Engaged traffic source.

<details>

**When both `userinput` and `newkeymetrics` feature flags are enabled**

![image](https://github.com/google/site-kit-wp/assets/94359491/b3ff069b-dc6b-40cb-8da4-b82c648bd820)

**When only `userinput` feature flag is enabled**

![image](https://github.com/google/site-kit-wp/assets/94359491/f7b4f180-0db5-47ef-afac-262fe48960f2)


https://github.com/google/site-kit-wp/assets/94359491/585877b0-d4c9-4436-a596-b269051b9bac

<details>
