### ISSUE TITLE
Create “Most popular authors by pageviews” key metric widget tile

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7605]
## Feature Description

![image](https://github.com/google/site-kit-wp/assets/20284937/dc85e436-14d6-44d8-bc52-06c266b7c569)
(screenshot for reference - see Figma for latest version)

A new key metric widget tile should be added for "Most popular authors by pageviews".

See:

1. [Table of metrics in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.5u6oy5c2u65e).
2. [List of metrics in PRD](https://docs.google.com/document/d/1UZ2VXOxpsY3GiHgQncZIb73Uy-xVf15MWJi46QkK_X0/edit?resourcekey=0-dB9ROp2h3ZYhqoyYBMTzvw#bookmark=id.usf86uc2bsda).
3. [Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60076&mode=design&t=jVtKY6g6XWmpvybS-4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new component should be created for the "Most popular authors by pageviews" key metric widget tile and should be displayed within the Key Metrics Widget area if it is selected in the key metrics selection panel.
  - This metric tile should use the wrapper for tiles dependent on custom dimensions (being implemented in [#7601](https://github.com/google/site-kit-wp/issues/7601)).
  - When defining this metric tile in the `KEY_METRICS_WIDGETS` constant (located in `assets/js/components/KeyMetrics/key-metrics-widgets.js` at the time of writing), a new `requiredCustomDimensions` array property should be added to its definition. This array property will contain names of custom dimensions that the tile depends on. In this case, it should only be `googlesitekit_post_author`.
  - The component should look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60076&mode=design&t=jVtKY6g6XWmpvybS-4).
  - Its widget slug should be `kmAnalyticsPopularAuthors` (so that it is consistent with the design doc).
  - The metric tile title should be `Most popular authors by pageviews`.
  - Its description tooltip should say `Authors whose posts got the most visits`.
  - This metric should be dependent on the `analytics-4` module, so it should only be rendered in the key metrics widget area if GA4 is connected, otherwise, `ConnectGA4CTATileWidget` should be rendered (similar to existing GA4-dependent metric tiles). It should also not be shown to view-only users who do not have shared access to GA4.
- The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
  - Metrics: `screenPageViews`
  - Dimensions: `customEvent:googlesitekit_post_author`
  - The metric should be aggregated so that all pageviews for each author is returned.
  - Order by:  `screenPageViews` descending
- Values:
  - It should be a table pattern metric tile, with the author display name showing up as the first column, and `screenPageViews` showing up as the second column.
- The metrics & dimensions used in the reports for this tile should be allow-listed for view-only users.
- This metric should be available for selection in the key metrics selection panel only if the following conditions are met:
  - `newsKeyMetrics` feature flag is enabled.
  - It is not a view-only user.
  - If it is a view-only user, the custom dimension that this metric tile depends on should be available for the connected GA property.

#### Component Creation

* Create a new component, `MostPopularAuthorsByPageviewsWidget.js` in <del>`assets/js/components/KeyMetrics/`</del> `assets/js/modules/analytics-4/components/widgets/`.
* Implement the following functionality in the new component:
    * Get the popular authors by pageviews report data using the `getReport` selector.
    * To fetch the required data, create a new `reportOptions` object with the following options:
    ```javascript
    const reportOptions = {
        ...dates,
        dimensions: [ 'customEvent:googlesitekit_post_author' ],
        metrics: [ { name: 'screenPageViews' } ],
        orderby: [
            {
                metric: { metricName: 'screenPageViews' },
                desc: true,
            }
        ],
    };
    ```
    * Get the loading and error states from the `hasFinishedResolution` and `getErrorForSelector` selectors, respectively.
    * Calculate the `total` number of pageviews from the `totals` array of the metrics returned from the report.
    * Construct the `columns` array for the `<MetricTileTable>` component with the following:
        * Render the author display name using the `MetricTileTablePlainText` component.
    * Render the custom dimensions wrapper component being implemented in [#7601](https://github.com/google/site-kit-wp/issues/7601).
    * Render the `<MetricTileTable>` component as the child of the custom dimensions wrapper component.
    * The `title` should be `Most popular authors by pageviews`.
    * The `infoTooltip` should be `Authors whose posts got the most visits`.
    * Pass other required props to the `<MetricTileTable>` component.
* Ensure the component's design matches the [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60076&mode=design&t=jVtKY6g6XWmpvybS-4).
* Note that the Figma designs display the author display name as a link. However, the author display name should be plain text and not a link.
* The availability of the tile in the metrics selection panel is being implemented in [#7599](https://github.com/google/site-kit-wp/issues/7599).
* Add storybook stories for the Ready, Loading, and Error states like other key metric widgets.

#### Widget Registration

* In `assets/js/googlesitekit/datastore/user/constants.js`:
    * Export a new constant for defining the new widget's slug: `KM_ANALYTICS_MOST_POPULAR_AUTHORS = 'kmAnalyticsMostPopularAuthors'`
    * Add this constant to the `keyMetricsGA4Widgets` array.
* In the `assets/js/components/KeyMetrics/key-metrics-widgets.js`:
    * Locate the condition that checks for the `newsKeyMetrics` feature flag.
    * Add `KM_ANALYTICS_MOST_POPULAR_AUTHORS` widget tile slug to the `KEY_METRICS_WIDGETS` object with the following properties:
        * title: `Most popular authors by pageviews`
        * description: `Authors whose posts got the most visits`
        * requiredCustomDimensions: [ `googlesitekit_post_author` ]
* In `assets/js/modules/analytics-4/index.js`:
    * Locate the condition that checks for the `newsKeyMetrics` feature flag and register the `KM_ANALYTICS_MOST_POPULAR_AUTHORS` widget tile the same as other key metric widgets.
    * Use the `MostPopularAuthorsByPageviewsWidget` component as the `Component` prop.

### Test Coverage

* Add basic tests for the `MostPopularAuthorsByPageviewsWidget` component.
* Add VRT scenarios similar to other key metric widgets.

## QA Brief

* Ensure `newsKeyMetrics` and `userInput` feature flags are enabled.
* Select the most popular authors widget to display in your Key Metric Widgets.
* Have a content on your site generated by multiple authors or import test data from [WordPress Theme Unit tests](https://codex.wordpress.org/Theme_Unit_Test#Test_Environment_Setup)
* Visit some posts from your sites using multiple browser
* Wait till the next day and go to the dashboard.
* Verify that you see most popular authors information in the widget.

## Changelog entry

* Add a "Most popular authors" Key Metric tile.

**Comment by techanvil** [comment]
Hey @nfmohit! This is very similar to #6703 and the first part of my [comment](https://github.com/google/site-kit-wp/issues/7603#issuecomment-1738801959) there applies here too.

AC :white_check_mark:

**Comment by bethanylang** [comment]
@nfmohit is checking with Sigal and Mariya on this:

> For “Most popular authors”, it is possible to link the author names to their archive pages. However, that’d be a little complex as we’d also have to obtain their username from the backend (we’re currently only obtaining the display name).

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
Hi @eugene-manuilov, I've just spotted that the error state stories for this widget have the same problem that was [flagged](https://github.com/google/site-kit-wp/issues/7603#issuecomment-1768932255) for "Top recent trending pages", with them all currently displaying the loading state.

Assigning back to you in Execution, hopefully it's just a case of applying the same change that @aaemnnosttv made in his followup [PR](https://github.com/google/site-kit-wp/pull/7718).

**Comment by techanvil** [comment]
Update: I've also noticed that `customEvent:googlesitekit_post_author` needs to be added to the [list of allowed dimensions](https://github.com/google/site-kit-wp/blob/c7fd4d3d9d0a115236119660aa5f4b1d7820e9ce/includes/Modules/Analytics_4/Report/Request.php#L273-L288) in order for the widget to work in view-only mode.

**Comment by yogeshbeniwal** [comment]
Will it also cover guest authors created using [Co Authors Plus]( https://github.com/Automattic/Co-Authors-Plus)

**Comment by bethanylang** [comment]
Hi @yogeshbeniwal! No, this initial version only detects authors via the standard WP code, not from other plugins. However, this addition is something we can consider for the future!

**Comment by yogeshbeniwal** [comment]
Thank you @bethanylang, can we please track it via a new issue?

**Comment by bethanylang** [comment]
@yogeshbeniwal Feel free to create a [new feature request issue here](https://github.com/google/site-kit-wp/issues/new?assignees=&labels=&projects=&template=feature_request.md) and we can consider it for a future iteration. Thanks!

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ 

@jimmymadon @nfmohit an observation. On the tile, I am seeing the same data as Analytics for my two authors based on posts. When I look in the Analytics report though its saying `(not set)` as 303 page views.  I suspect that these are pages rather than posts. I wonder if this might create user queries and should the custom dimension be tracking pages?

Interested in your thoughts. 

![image](https://github.com/google/site-kit-wp/assets/73545194/67c9c36d-8dfa-4a9e-a62b-e32c520c1640)

**Verified:**

- A new component is created for the `Most popular authors by pageviews` key metric widget tile and is displayed within the Key Metrics Widget area if it is selected in the key metrics selection panel.
- The component looks as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60076&mode=design&t=jVtKY6g6XWmpvybS-4).
- Its widget slug is `kmAnalyticsPopularAuthors` 
- The metric tile title is `Most popular authors by pageviews`.
- Its description tooltip says `Authors whose posts got the most visits`.
- This metric is dependent on the analytics-4 module. 
- It is a table pattern metric tile, with the `author display name` showing up as the first column, and `screenPageViews` showing up as the second column.
- The metrics & dimensions are available for view-only users.
- This metric is available for selection in the key metrics selection panel only when `newsKeyMetrics` feature flag is enabled.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/afe81323-6d1b-4775-9828-784827a6b133)
![image](https://github.com/google/site-kit-wp/assets/73545194/10ec15e7-c7af-44a0-8253-3dcf3db413b5)
![image](https://github.com/google/site-kit-wp/assets/73545194/203788a7-3c4d-4644-9576-2b7de292163a)
![image](https://github.com/google/site-kit-wp/assets/73545194/243de527-e944-4012-81bd-833a76a19fc4)

</details>
