### ISSUE TITLE
Create “Top categories by pageviews” key metric widget tile

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7607]
## Feature Description

![image](https://github.com/google/site-kit-wp/assets/20284937/f7e39472-098e-4bd8-b5d1-7c7dcfdca277)
(screenshot for reference - see Figma for latest version)

A new key metric widget tile should be added for "Top categories by pageviews".

See:

1. [Table of metrics in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.5u6oy5c2u65e).
2. [List of metrics in PRD](https://docs.google.com/document/d/1UZ2VXOxpsY3GiHgQncZIb73Uy-xVf15MWJi46QkK_X0/edit?resourcekey=0-dB9ROp2h3ZYhqoyYBMTzvw#bookmark=id.usf86uc2bsda).
3. [Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60077&mode=design&t=jVtKY6g6XWmpvybS-4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new component should be created for the "Top categories by pageviews" key metric widget tile and should be displayed within the Key Metrics Widget area if it is selected in the key metrics selection panel.
  - This metric tile should use the wrapper for tiles dependent on custom dimensions (being implemented in [#7601](https://github.com/google/site-kit-wp/issues/7601)).
  - When defining this metric tile in the `KEY_METRICS_WIDGETS` constant (located in `assets/js/components/KeyMetrics/key-metrics-widgets.js` at the time of writing), a new `requiredCustomDimensions` array property should be added to its definition. This array property will contain names of custom dimensions that the tile depends on. In this case, it should only be `googlesitekit_post_categories`.
  - The component should look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60077&mode=design&t=jVtKY6g6XWmpvybS-4).
  - Its widget slug should be `kmAnalyticsTopCategories` (so that it is consistent with the design doc).
  - The metric tile title should be `Top categories by pageviews`.
  - Its description tooltip should say `Categories that your site visitors viewed the most`.
  - This metric should be dependent on the `analytics-4` module, so it should only be rendered in the key metrics widget area if GA4 is connected, otherwise, `ConnectGA4CTATileWidget` should be rendered (similar to existing GA4-dependent metric tiles). It should also not be shown to view-only users who do not have shared access to GA4.
- The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
  - Metrics: `screenPageViews`
  - Dimensions: `customEvent:googlesitekit_post_categories`
  - The metric should be aggregated so that all pageviews for each category (or set of comma-separated categories) is returned.
  - Order by:  `screenPageViews` descending
- Values:
  - It should be a table pattern metric tile, with the category name(s) showing up as the first column, and `screenPageViews` showing up as the second column.
- The metrics & dimensions used in the reports for this tile should be allow-listed for view-only users.
- This metric should be available for selection in the key metrics selection panel only if the following conditions are met:
  - `newsKeyMetrics` feature flag is enabled.
  - It is not a view-only user.
  - If it is a view-only user, the custom dimension that this metric tile depends on should be available for the connected GA property.

## Implementation Brief

- In `assets/js/googlesitekit/datastore/user/constants.js`:
  - Export a new constant for defining the new widget's slug: `KM_ANALYTICS_TOP_CATEGORIES = 'kmAnalyticsTopCategories'`.
  - Add this constant to the `keyMetricsGA4Widgets` array.
- In `assets/js/components/KeyMetrics/key-metrics-widgets.js`:
  - Add a new item for the new widget to the `KEY_METRICS_WIDGETS` object if the `newsKeyMetrics` feature flag is enabled similar to existing widgets.
  - Its `title` & `description` should be according to the ACs.
  - Add a `requiredCustomDimensions` property that should be an array containing the `googlesitekit_post_categories` string.
- In `assets/js/modules/analytics-4/components/widgets/`, create a new `TopCategories.js` component. In this component, use `TopCitiesWidget` as a starting point, then make the following changes:
  - It should use the wrapper component introduced in [#7601](https://github.com/google/site-kit-wp/issues/7601) so that it can handle the custom dimensions creation and relevant error & loading states.
  - Change relevant variable names accordingly.
  - Use the `customEvent:googlesitekit_post_categories` dimension instead of `city`.
  - Use the `screenPageViews` metric instead of `totalUsers`.
  - The second column of the tile table should render the `screenPageViews` metric value (instead of the `TopCitiesWidget` `totalUsers` percentage).
  - The `title` and `infoTooltip` should be according to the ACs.
- In `assets/js/modules/analytics-4/index.js`:
  - Register the new key metric widget the same as other key metric widgets. However, wrap the registration using the new `newsKeyMetrics` feature flag.
- In `includes/Modules/Analytics_4/Report/Request.php`:
  - Update the `validate_shared_dimensions` method and add `customEvent:googlesitekit_post_categories` to the list of valid dimensions.

### Storybook

- Add Storybook stories for the new widget for ready, zero, loading, and error states.

### Test Coverage

- Add VRT scenarios.

### Setup

* **Site Kit Configuration**: Configure Site Kit using `https://news-key-metrics.instawp.xyz` as the proxy URL. Connect it to the “News Key Metrics” Analytics account. If you don't have access to this domain's GA4 account/property/web datastream, please request access from @nfmohit or @jimmymadon.
* **WordPress Categories**:
   - Create some WordPress categories.
   - Ensure that these categories have the same `term_id` as the `customEvent:googlesitekit_post_categories` custom dimensions.
   - To ascertain the category IDs used for this custom dimension, refer to [GA4 Query Explorer](https://ga-dev-tools.google/ga4/query-explorer/).

### Verification

* Enable the `newsKeyMetrics` feature flag and then configure key metrics.
* Select the "Top categories by pageviews" key metric widget tile from the Metrics selection panel.
* Ensure that the widget tile displays data corresponding to the `customEvent:googlesitekit_post_categories` custom dimension categories.
* Follow the QAB instructions from issue #7601 to confirm the creation of custom dimensions and observe any related errors.

## Changelog entry

* Add “Top categories by pageviews” key metric widget tile.

**Comment by techanvil** [comment]
Hey @nfmohit! This is also similar to #6703 and the first part of my [comment](https://github.com/google/site-kit-wp/issues/7603#issuecomment-1738801959) there applies here too.

That aside, there's a small detail to address here - it looks like the metric tile title should be "Top categories by pageviews", but it's defined in the AC as "Most popular categories by pageviews". Can you please confirm which is correct and update as necessary?

**Comment by nfmohit** [comment]
Thank you @techanvil!

> This is also similar to #6703 and the first part of my [comment](https://github.com/google/site-kit-wp/issues/7603#issuecomment-1738801959) there applies here too.

Understood. I've updated the ACs to be a little higher-level.

> That aside, there's a small detail to address here - it looks like the metric tile title should be "Top categories by pageviews", but it's defined in the AC as "Most popular categories by pageviews". Can you please confirm which is correct and update as necessary?

Excellent catch. Updated. Thank you!

**Comment by techanvil** [comment]
Thanks @nfmohit! AC :white_check_mark:

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by nfmohit** [comment]
Hi @hussain-t & @aaemnnosttv.

It looks like the merged PR #7708 doesn't pass the tile's report options to the HOC. The tile still works without this, but if just in case the required custom dimension gets removed from the property in any way, the HOC will not catch the problem and will not update the list of available custom dimensions.

What do you think?

**Comment by aaemnnosttv** [comment]
Picking this back up to fix something I broke during CR 🤦

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A new component is created for the `Top categories by pageviews` key metric widget tile and is displayed within the Key Metrics Widget area if it is selected in the key metrics selection panel.
- The component looks as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60076&mode=design&t=jVtKY6g6XWmpvybS-4).
- Its widget slug is `kmAnalyticsTopCategories`
- The metric tile title is `Top categories by pageviews`
- Its description tooltip says `Categories that your site visitors viewed the most.
- This metric is dependent on the analytics-4 module.
- The component  is a table pattern metric tile, with the category name(s) showing up as the first column, and `screenPageViews` showing up as the second column.
- The metrics & dimensions are available for view-only users.
- Checked the data compared with Analytics and everything matches.  

Note: we do have a known issue around the [not set] data appearing in the tile and this will be investigated and discussed.

<details>
 <summary>Screenshot</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/bfd51fe3-0805-4c2a-a4ec-1aa1f90e369b)
![image](https://github.com/google/site-kit-wp/assets/73545194/38f960ce-e225-4628-8ae6-838f7b5bd237)
![image](https://github.com/google/site-kit-wp/assets/73545194/8f09bf77-01ff-448f-9d2c-cc8adf33fdd2)
![image](https://github.com/google/site-kit-wp/assets/73545194/be2192ee-95d6-40b0-9d51-a01d22e0ee11)
![image](https://github.com/google/site-kit-wp/assets/73545194/7d20e6ba-266f-4fb1-933c-03e462dba4dc)

</details>
