### ISSUE TITLE
Remove unused and legacy functionalities from User Input App

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#7610]
## Feature Description

The `UserInputApp` (ie. `/wp-admin/admin.php?page=googlesitekit-user-input`) has a few bits of legacy functionalities still in the code, such as an way to edit a single question using url query arg `single` which was being used previously. Due to using inline Editing in both preview and settings, this is no longer being used so should be removed along with any other similar bits of code.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The currently unused "single question editing" functionality present in User Input App should be removed.

## Implementation Brief

* In `assets/js/components/user-input/UserInputQuestionnaire.js`:
    * Remove the calls to `useQueryArg` that gets `single` and `redirect_url` parameters that were solely  being used for the single question editing flow as it is no longer relevant. 
    * Remove the `isSettings` variable and and the related logic from `submitChanges` callback. 
    * Rename `next` and `back` to `nextCallback` and `backCallback` and remove their dynamic assignment based on the `single` query param.
    * Remove the `nextLabel` and their passing in `UserInputQuestionWrapper` elements. 
* In `assets/js/components/user-input/UserInputQuestionWrapper.js`:
    * Remove the unused `nextLabel` and `backLabel` props and refactor the component to remove their usage. 

### Test Coverage

* Update any failing tests. 

## QA Brief

* Setup Site Kit
* Enable `keyMetrics` and `ga4Reporting` feature flags
* Click on `Get Tailored Metrics` CTA on key metrics setup banner
* Go through steps, verify everything is working properly and there is no any error while going through steps, and there is no console log error
* Upon saving the settings, you should be redirected to dashboard with metric tiles appearing properly

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested complete set up flow of KeyMetrics.
- Verified 'Get tailored metrics' CTA and set up flow.
- Verified 'I'll pick my metrics' set up flow.
- Verified edit functionality under admin settings.
- Verified panel settings and CTA.

<details>


https://github.com/google/site-kit-wp/assets/94359491/dedc29cc-27ca-4f14-b33a-e2d9f3a80009


https://github.com/google/site-kit-wp/assets/94359491/001d6193-db48-4e58-b5ce-615fa2094445

</details>
