### ISSUE TITLE
Add ESLint rule to flag improper dispatching of actions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7616]
## Feature Description

There are essentially 2 ways to dispatch an action properly such that it behaves as expected:

- Using `registry.dispatch`
- Using `yield`

The latter is of course only possible in a generator function, but calling the registry's `dispatch` is also possible in the same context but will not be processed in the same way and should be avoided.

This is fairly easy to identify statically, so we should introduce an ESLint rule to flag it

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new ESLint rule `no-yield-dispatch` should be added to our bundled `eslint-plugin-sitekit`
* The rule should error if `yield registry.dispatch` or `yield dispatch` is detected in a generator function with the following message:
	> Only plain objects should be yielded from action generator functions. `dispatch` always returns a Promise.  

## Implementation Brief

* Add new rule `packages/eslint-plugin/rules/no-yield-dispatch.js`
  * Target `yield registry.dispatch` with this AST structure `YieldExpression > CallExpression > MemberExpression > CallExpression > MemberExpression[object.name="registry"][property.name="dispatch"]`
  * Target `yield dispatch` with this AST structure `YieldExpression > CallExpression > MemberExpression[object.callee.name="dispatch"]`
  * Return the message from AC if these cases match
* Add new rule `no-yield-dispatch` to the list in `packages/eslint-plugin/rules/index.js`
* Include `sitekit/no-yield-dispatch` rule to the list in `packages/eslint-plugin/configs/main.js`

### Test Coverage

* Add `valid` and `invalid` cases for `no-yield-dispatch.test.js`

## QA Brief

* No QA needed as this is infrastructure only.

## ENG QA

* Add `registry.dispatch()` and `dispatch()` to a generator function and verify linting fails.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kuasha420** [comment]
## QA:Eng :heavy_check_mark: 

* The ESLint rule is active and working - actively flagging incorrect code when `dispatch/registry.dispatch` is call is `yield`-ed inside a generator function. 
* The tests included for the rule is adequate and passing.
