### ISSUE TITLE
Update report titles logic in the Popular Products KMW tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7619]
## Feature Description

As mentioned in this [comment](https://github.com/google/site-kit-wp/issues/7584#issuecomment-1731209171) and the original issue #3070, titles for page URLs in websites can change over time and report data could become inaccurate. So, we should always first fetch report data using page URLs and then fetch their titles. This approach has been taken within the `<PopularContentWidget>` KMW tile component and should be replicated in the `<PopularProductsWidget>` KMW tile to maintain consistency.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `<PopularProductsWidget>` component should replicate fetching the pagePath first and then the pageTitle as per the `<PopularContentWidget>` component:
    * Do not fetch the `pageTitle` when making the original report query.
    * Use the `getPageTitles` selector from the `modules/analytics-4` to fetch page titles as a separate query.

## Implementation Brief

* Within `<PopularProductsWidget>`, using the `<PopularContentWidget>` as a reference:
    * Modify `reportOptions` to fetch only the `pagePath` dimension and not the `pageTitle` dimension.
    * Use the `getPageTitles` selector as mentioned in the AC.
    * Update the variable paths in the `columns` constant to correctly compute the `<Component>` that will be rendered.

### Test Coverage

* No new tests required.

## QA Brief

* Setup Site Kit
* Enable `ga4reporting` and `userInput` feature flags
* Setup key metrics and add `Most popular products by pageviews` metric
* Verify product titles are properly shown
* _One note: oi.ie does not have products so this metric will not be available for it. You can use some other site to test this, locally I used storybook. In case you need another website, best to check with someone with access to the one_

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC and IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified the product titles are properly shown
  - Tested on main and view only dashboard. 

**Note:** to test this I added the permalink `/how-%product%/` for my site in the products permalinks.  We used something similar with `oi.ie` when testing the tiles initially as we don't have any test sites with actual live products. 

![image](https://github.com/google/site-kit-wp/assets/73545194/164a28d3-b231-45a9-84ef-ddbe448bb6dd)
