### ISSUE TITLE
Выдаёт ошибку(Error)

### ISSUE THREAD

**Issue by Grokstr** [google/site-kit-wp#762]
![Скриншот 2019-11-01 18_50_56](https://user-images.githubusercontent.com/57225497/68037379-05ffc480-fce1-11e9-957d-14b755921bb5.png)

**Comment by aaemnnosttv** [comment]
The error returned translates to "No route was found matching the URL and request method" which is a `rest_no_route` (REST API 404).

**Comment by jamesozzie** [comment]
@Grokstr Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there
