### ISSUE TITLE
Add Enhanced Measurement Toggle in Analytics Settings View

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7631]
## Bug Description

While looking through the tickets for Enhanced Measurement, I noticed on ticket #7459 that the toggle setting was not appearing on the Analytics settings view screen.  It would be better UX to be able to see if the Enhanced Measurement is enabled or disabled without having to edit the settings. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0xoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a1756fbbd5547222ecb7a464ed7845b409def0e5/image.png)

## Steps to reproduce

1. Enable the enhancedMeasurement feature flag
2. Connect a GA4 property
3. Go to Analytics settings 
4. Enable Enhanced Measurement
5. Save settings and go to settings view. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the `enhancedMeasurement` feature flag is enabled, the Analytics Settings View screen should contain an extra section that shows the current enhanced measurement status.
* This new section should appear below the **Google Analytics 4 Code Snippet** section (following the flow of the Edit screen where the EM switch is below the snippet switch).
* The title of the section should be **Enhanced Measurement**, and the value should be either "Enabled" or "Disabled".
* The value, but not the title, should be replaced with a small progress bar while the EM state is being loaded.
* The new section should be styled consistently with the rest of the page - see the mockup below.

![image](https://github.com/google/site-kit-wp/assets/18395600/7b4d5a1e-9852-4cc0-b936-0dd6542180be)

## Implementation Brief

In `assets/js/modules/analytics/components/settings/GA4SettingsView.js`:

* Get the Enhanced Measurement `streamEnabled` state using the `isEnhancedMeasurementStreamEnabled` selector. This selector requires valid `propertyID` and `webDataStreamID` as arguments. See `SettingsEnhancedMeasurementSwitch` for example:
https://github.com/google/site-kit-wp/blob/92729ddeb26de9920525eca84868d4749b3bf61a/assets/js/modules/analytics-4/components/settings/SettingsEnhancedMeasurementSwitch.js#L80-L96
* Check if the `enhancedMeasurement` feature flag is enabled. If yes:
    * Right after the **Google Analytics 4 Code Snippet** section, insert a new section for **Enhanced Measurement**.
    * Use a similar markup structure as the **Google Analytics 4 Code Snippet** section, but update the title (`h5`) to **Enhanced Measurement**.
    * Display the `ProgressBar` component with `className` set to `googlesitekit-analytics-enable-enhanced-measurement__progress` when the `streamEnabled` state is `undefined`.
    * Display "Enabled" if the `streamEnabled` state is `true`, and "Disabled" if it's `false`.
    * For the display status, use a `<p>` element with the class `googlesitekit-settings-module__meta-item-data`.

In `stories/module-analytics-settings.stories.js`:

* Modify the `View, open with all settings w/ GA4` story to reflect the new section.

### Test Coverage

* No new tests are required for this change.
* Fix any broken tests.

## QA Brief

1. Enable the `enhancedMeasurement` feature flag
2. Connect a GA4 property
3. Go to Analytics settings 
4. Enhanced Measurement should appear and show "Disabled" in Analytics Settings view.
5. Enable Enhanced Measurement
6. Save settings and go to settings view.
7. Enhanced Measurement should appear and show "Enabled" in Analytics Settings view.

## Changelog entry

* Add Enhanced Measurement setting to Analytics in Site Kit admin settings.

**Comment by aaemnnosttv** [comment]
@techanvil is the plan here that we would fetch the EM settings every time someone views the settings? If so, this isn't something we've done before as we've avoided Google API requests as side effects of this view which has been a way to see various setting values only.

**Comment by techanvil** [comment]
> @techanvil is the plan here that we would fetch the EM settings every time someone views the settings? If so, this isn't something we've done before as we've avoided Google API requests as side effects of this view which has been a way to see various setting values only.

Hey @aaemnnosttv - yes, we would be fetching the EM settings every time someone views the settings. I did highlight these points in the initial Slack conversations - see [here](https://10up.slack.com/archives/CBKKQEBR9/p1695812420600109?thread_ts=1695811129.752549&cid=CBKKQEBR9) and [here](https://10up.slack.com/archives/CFFRMC5DE/p1695813907700109). The decision was made to proceed anyway as specced...
 
> It's also worth noting that we've had some quota issues with the admin API recently and this would result in a substantial increase of that usage if we're requesting it in response to viewing here.

However, this is an interesting point - do you mean that our users have been hitting the admin quota limits when using the plugin? If so are they hitting the read or write limits or both?

Tbh - it's a valid point and we might want to reconsider adding this to the Settings View page. I think more pressingly though, it's reminded me of a reorg I wanted to make in the Enhanced Measurement Banner which at the moment can potentially make a request for the EM settings on every page load (see [here](https://github.com/google/site-kit-wp/blob/a5be2c656ae506e7333cb1d94967daa9b5166673/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/index.js#L77-L92)). I want to update it so it doesn't retrieve the settings if the banner is dismissed or is showing the tooltip.

**Comment by techanvil** [comment]
Update to the above: As discussed on the standup just now, having clarified the quota impact here, whereby the quota issues we've been seeing most likely relate to usage via the SKS, whereas the quota that these EM requests will impact is the user's own [1,200 requests per minute](https://developers.google.com/analytics/devguides/config/admin/v1/quotas), this shouldn't present such a significant risk in terms of the quota usage.

**Comment by aaemnnosttv** [comment]
Thanks @techanvil. AC LGTM, although I think we should move the added row below the first to group it with the other values which are more about the connection. The other rows for the snippet and tracking exclusions make more sense to be kept together.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv. I do see the logic to your suggestion, but at the same time, when viewing the Edit page and seeing how the View page essentially follows the flow, I do think it's a bit more coherent as a UI to maintain the same structure. It's also worth noting that Mariya has given the AC as it stands her approval on [Slack](https://10up.slack.com/archives/CFFRMC5DE/p1696429255389489?thread_ts=1696428361.096299&cid=CFFRMC5DE), so it might be worth running by her before changing it, although she is of course away for the next couple of weeks or so. What do you think?

![image](https://github.com/google/site-kit-wp/assets/18395600/1d32a3c4-320e-43ab-a102-dbb8858d8a70)

![image](https://user-images.githubusercontent.com/18395600/272600161-7b4d5a1e-9852-4cc0-b936-0dd6542180be.png)

**Comment by aaemnnosttv** [comment]
Ah thanks for pointing that out @techanvil – I agree it makes sense for the placement to be consistent in both, so if we were to move it, it should be updated in both. Let's keep it as you have for now and we can see about potentially reordering in both places later once Mariya is back.

AC ✅

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Enhanced Measurement appears and shows `Disabled` in Analytics Settings view.
- Enhanced Measurement appears and shows `Enabled` in Analytics Settings view.
- Checked on desktop and small viewports to ensure no UX/UI issues. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/aad20569-6e65-4a71-9aed-9045a1ca5120)
![image](https://github.com/google/site-kit-wp/assets/73545194/76708c5a-d638-4513-9cbe-dc92f271392c)

</details>
