### ISSUE TITLE
WP Nightly E2E/PHP Unit tests are failing because of deprecation notice

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7632]
## Bug Description

WP Nightly PHP Unit tests and E2E tests are failing because of this message:

```
Function print_emoji_styles is deprecated since version 6.4.0! Use wp_enqueue_emoji_styles instead.
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHP Unit tests should not fail on WordPress Nightly (due to the `print_emoji_styles` issue).
* E2E tests should not fail because of a deprecation notice being surfaced.

## Implementation Brief

Part of this is straightforward: we need to remove a few lines in our PHP Unit tests that remove all actions in `'wp_enqueue_scripts'`. It seems there used to be issues with these actions running in CI but it's now fine after running them multiple times, and it prevents the PHP Unit issues in WP 6.4.

For the E2E tests, the issue is upstream in the AMP plugin, which is what is causing WP Nightly to fail: https://github.com/ampproject/amp-wp/issues/7619. The plugin calls `_admin_bar_bump_cb` which triggers a deprecation notice in WordPress 6.4. I've filed the upstream bug, but we need to wait for them to fix it I think so for now we should ignore the warning with a note about it needing the upstream fix.

* Remove this code from `tests/phpunit/integration/Modules/AnalyticsTest.php`.
```php
remove_all_actions( 'wp_enqueue_scripts' );
```
* Add an entry to the E2E test ignore log for the deprecated callback the AMP plugin triggers, only for `nightly` versions.

See PR at #7646.

Note to IB Reviewer: feel free to move this directly to Code Review as the execution is already complete at #7646, and assign to me (@tofumatt) if you need any PR tweaks 🙂 

### Test Coverage

* Update the above tests and ensure they pass.

## QA Brief

* No QA is needed; PHP Unit and E2E tests using WP Nightly should pass, except the User Input test that is known to fail (ee: #7630.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅ 
Moving to CR 👍

**Comment by aaemnnosttv** [comment]
## ❌ Approval

This test is failing again because the line it is being triggered on has changed. The ignore matching we have in place is fragile due to the specific lines.
