### ISSUE TITLE
Improve the amount of Analytics properties that are available from the selection drop down

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#7635]
## Feature Description

Currently when selecting an Analytics property from the Analytics module, users can select up to 50 properties per account. The first 50 created properties created in the selected account will be displayed. Any properties created thereafter will not be displayed in the drop down to select.

This cap can be increased to allow for more properties to be displayed to users. As we have seen recent reports of users not able to select newly created properties, it would be good to get this increased to the maximum amount possible.

An example support topic of this happening to a user can be found here: 
https://wordpress.org/support/topic/sitekit-analytics-ga4-property-not-showing-in-the-list/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When fetching Analytics properties via the API, [the maximum number per-page](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1beta/properties/list) should be requested (currently `200`)

## Implementation Brief

* Update the call to `properties.list` within `GET:properties` to specify a `pageSize` of `200` https://github.com/google/site-kit-wp/blob/340055a5601b088a8a985a3afcb0b942e7596404/includes/Modules/Analytics_4.php#L623-L627

### Test Coverage

* No changes necessary

## QA Brief

* To QA this you would need to create an Analytics account with over 50 properties, then load it in Site Kit to test.

This might be kind of ridiculous to QA in a reasonable amount of time. If QA already have an account they can test this with please do, but otherwise I think it can be safely moved to Approval given the implementation is straightforward.

## Changelog entry

* Increase the number of Analytics properties that appear in Analytics setup/settings screens.

**Comment by aaemnnosttv** [comment]
I've also opened https://github.com/google/site-kit-wp/issues/7637 as a more appropriate (but higher-effort) change that we should make anyways, but should also further improve the limitation here. cc @nfmohit

**Comment by bethanylang** [comment]
Thanks, @aaemnnosttv! Could you please add an estimate here?

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

I am going to move this to approval since I don't have an account that has more than 50 properties, but @adamdunnage if we have a user who could test this - we could give them the develop version of the plugin, and ask them to test that all of the properties appear.  Do you think that would be possible?  

It will be quicker than me creating 50+ properties for an account.  Let me know what you think. 😄

**Comment by adamdunnage** [comment]
> ### QA Update: ✅
> I am going to move this to approval since I don't have an account that has more than 50 properties, but @adamdunnage if we have a user who could test this - we could give them the develop version of the plugin, and ask them to test that all of the properties appear. Do you think that would be possible?
> 
> It will be quicker than me creating 50+ properties for an account. Let me know what you think. 😄

@wpdarren Apologies, not sure how I missed your comment here! Yes I agree that this would be the best way to check this. I have updated the support topic asking the two impacted users if they could check this on the development plugin and confirm they can now see up to 200 Analytics properties per account. 

Once I hear back from the users I will update here.

**Comment by timnolte** [comment]
FYI, my computer had a catastrophe and I'm rebuilding it. As soon as I get back to a working development environment I can pull the latest version from here and test it out.

**Comment by adamdunnage** [comment]
@wpdarren [One user](https://wordpress.org/support/topic/sitekit-analytics-ga4-property-not-showing-in-the-list/page/2/#post-17112625) has tried testing this with the development plugin but is saying that they can still only see a maximum of 50 Analytics properties for their account. 

@timnolte Thanks, it would be good to get your feedback also on this when you get back to a working environment.

**Comment by wpdarren** [comment]
@adamdunnage thank you for checking with a user.  I am going to put this ticket back into QA queue.  Would it be possible to make sure that they have disconnected and reconnected Site Kit (if possible) and also cleared browser cache, cookie and session storage in the Chrome browser.   If they still only see maximum of 50 properties, I can send this back to Execution for Matthew to investigate.  Thank you!

**Comment by adamdunnage** [comment]
@wpdarren The [user has come back](https://wordpress.org/support/topic/sitekit-analytics-ga4-property-not-showing-in-the-list/page/2/#post-17113046) once more confirming that they can still only see a maximum of 50 properties after resetting Site Kit and from a different device. 

Could we send this one back to execution to investigate further, thanks!

**Comment by wpdarren** [comment]
QA Update: ❌ 

@tofumatt I am sending this back to execution based on the feedback here from the user.  They still see only a maximum of 50 properties.   Please reach out to @adamdunnage if you need more information from the user.

**Comment by tofumatt** [comment]
How many properties does the user in question have? I just tested using the `TestBulk` account and was able to fetch 52 properties when using the new, increased page size value of `200`. Which is correct, because TestBulk has 52 properties:

![CleanShot 2023-10-13 at 12 21 11](https://github.com/google/site-kit-wp/assets/90871/f58bee61-48c7-4eee-8205-80c8efdeaa13)

50 is the default, so we are getting more than before.

And the page size value is definitely being used for the requests, as can be seen here when we change it to smaller amounts and it restricts the count (as well as fetching all 52 items when `200` is used):

https://github.com/google/site-kit-wp/assets/90871/c4af5925-d51b-44a2-8406-7c7cf5a94f47

It's possible the end user had a config error? Or maybe has so close to 50 items it wasn't clear the update worked? But this certainly seems solved from my end 🤔

**Comment by bethanylang** [comment]
Tagging @adamdunnage here to look at @tofumatt's update, thanks!

**Comment by adamdunnage** [comment]
@tofumatt Okay I have tested this once more and can confirm that when using the tester plugin with the development branch that I can see all 52 properties from that account. I tested once more from the downloaded development plugin and it didn't work so that's why I couldn't verify this last time.

As I can see this is working with the tester plugin, I am happy to confirm all looks good from my end and will not need to get the user confirmation. 

@wpdarren Do you want to confirm this is working with the tester plugin?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@tofumatt @adamdunnage I can confirm that I see 52 properties in the dropdown so this looks fine.  

This is using the tester plugin and on `develop` branch.   

When we are completing our release testing for 1.113.0, I have made a note to check this again. 

I do have an observation about the ordering of the properties, but feel that's a separate that I will create a ticket for. 

https://github.com/google/site-kit-wp/assets/73545194/9b8a661d-586a-42e5-a4e5-a0ab03ea6d4e
