### ISSUE TITLE
Add Site Health info for GA4 `availableCustomDimensions`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7639]
## Feature Description

[#7598](https://github.com/google/site-kit-wp/issues/7598) adds a new setting `availableCustomDimensions` to the `analytics-4` module. The Site Health information for Site Kit should be updated to show the value of this setting.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- If the `newsKeyMetrics` feature flag is on, a new information item should be added to the Site Kit Site Health table following the existing information items for Analytics 4 as the following:
  - Label: `Analytics 4 available custom dimensions`
  - Value: A comma-separated list of custom dimension names consisting in the `availableCustomDimensions` module setting array. `None` if the module setting is `null`/unset or is an empty array.
  - Debug value: A comma-separated list of custom dimension names consisting in the `availableCustomDimensions` module setting array. `none` if the module setting is `null`/unset or is an empty array.

## Implementation Brief

- In `includes/Modules/Analytics_4.php`:
  - Update the `get_debug_fields` method so that if the `newsKeyMetrics` feature flag is enabled, a new item is included in the array being returned as follows:
    - Key: `analytics_4_available_custom_dimensions`.
      - `label`: `Analytics 4 available custom dimensions`
      - `debug`: `none` if `$settings['availableCustomDimensions']` is `null`/unset or is an empty array. Otherwise, it should show a comma-separated string of the array in `$settings['availableCustomDimensions']`.
      - `value`: `None` if `$settings['availableCustomDimensions']` is `null`/unset or is an empty array. Otherwise, it should show a comma-separated string of the array in `$settings['availableCustomDimensions']`.

### Test Coverage

- In `tests/phpunit/integration/Modules/Analytics_4Test.php`:
  - Add test cases for the `Analytics_4::get_debug_fields` method (similar to test cases for `Analytics::get_debug_fields` added in `tests/phpunit/integration/Modules/AnalyticsTest.php`) to verify the difference of debug fields present with or without the `newsKeyMetrics` feature flag.

## QA Brief

* Enable the `newsKeyMetrics` feature flag.
* Set up a site with Analytics
* Visit the "Site Health" page in WordPress admin and go to the Site Kit section.
* Check for `Analytics 4 available custom dimensions` in the list of values
  * If custom dimensions are enabled, they should appear
  * If no custom dimensions are enabled, it should say "none"

## Changelog entry

* Add Site Health info to display the available custom dimensions.

**Comment by tofumatt** [comment]
ACs here are good, moving to IB 👍🏻

**Comment by wpdarren** [comment]
QA Update: ✅ 

**Verified:**

- Checked for Analytics 4 available custom dimensions in the list of values
  - If custom dimensions are enabled, they appear
  - If no custom dimensions are enabled, it says "None"

<details>
 <summary>Screenshots</summary>
 
![image](https://github.com/google/site-kit-wp/assets/73545194/a5df30ac-8a36-416d-983e-0248f1f155de)
![image](https://github.com/google/site-kit-wp/assets/73545194/380253bf-c6a4-44b4-aa15-c6e939e328ed)

</details>

**Comment by aaemnnosttv** [comment]
## ⚠️ Approval

The implementation fulfills the AC but both the display and debug values are inconsistent with the way other lists are formatted (the closest parallel is active modules), mostly that there is a space missing in the comma separated formatting and that the separator itself should be translatable.  e.g. https://github.com/google/site-kit-wp/blob/2346864cf290442530674c9b5a2f2e2d7f6bed2d/includes/Core/Util/Debug_Data.php#L366-L372

This causes the value to be treated as one long string which distorts the sizing of the columns when many dimensions are present.

**Current**
<img width="836" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/158bdcc6-ab09-4c1b-b67c-34a5bd19a0d1">
Note the squished row heading.

**Correct formatting**
<img width="838" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/83531223-7807-4e8e-8a42-1a184a02da81">


I'll open a follow-up issue for this change.
