### ISSUE TITLE
Typo in readme.md "set up Sit Kit locally" vs "set up Site Kit locally"

### ISSUE THREAD

**Issue by nciske** [google/site-kit-wp#764]
## Bug Description

Typo in readme.md - "set up Sit Kit locally" vs "set up Site Kit locally"

## Steps to reproduce

Read readme, notice typo.

## Screenshots

N/A

## Additional Context

N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@nciske Thanks for flagging this! Fixed via https://github.com/google/site-kit-wp/commit/24fc7aadbd9d21b1201e451813587c7a581d3266
