### ISSUE TITLE
Change "All Users" to "All Visitors" in "All Traffic" widget

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7640]
## Feature Description

In order to improve the language in Site Kit to be more humanly understandable, the Site Kit dashboard analytics "All Traffic" widget should be updated to say `All Visitors` instead of `All Users`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- `All Users` should be changed to `All Visitors` in the Site Kit dashboard analytics "All Traffic" widget.

## Implementation Brief

* `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/TotalUserCount.js`:
* `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/TotalUserCount.js`:
   * Replace `All Users` occurrences to be `All Visitors` instead.

### Test Coverage

* N/A

## QA Brief

* Set up Site Kit and connect Analytics.
* Navigate to the dashboard. 
* Ensure the "Dashboard All Traffic Widget" now shows the term "All Visitors" in place of "All Users".
* Additionally, navigate to the entity dashboard. Verify the same change - "All Visitors" should be displayed instead of "All Users".
* Confirm this change in both scenarios: with the GA4 feature flag enabled and disabled.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@nfmohit this needs a priority :)

**Comment by bethanylang** [comment]
@aaemnnosttv @nfmohit I think we need to get this rolled out prior to News Key Metrics Tiles/KMW, so I'd say a P1?

**Comment by nfmohit** [comment]
> @aaemnnosttv @nfmohit I think we need to get this rolled out prior to News Key Metrics Tiles/KMW, so I'd say a P1?

Sounds good! Added, thanks!

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified All Users changed to All Visitors in the Site Kit dashboard analytics "All Traffic" widget.
- Tested when ga4 disabled and when it's enabled.
- Tested on both main and entity dashboard.
- Tested when site is in gathering and zero data state.
- Tested when site have live data.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/a8584df0-7adb-436e-ab1d-bd961f12b964)

![image](https://github.com/google/site-kit-wp/assets/94359491/4e34462c-91dc-4edc-b7e4-b64b35ca3f48)

![image](https://github.com/google/site-kit-wp/assets/94359491/630978ac-75e0-48a1-846f-f3b0e1bda3f5)

![image](https://github.com/google/site-kit-wp/assets/94359491/30823181-b9fd-4687-a096-28f14834e26f)

![image](https://github.com/google/site-kit-wp/assets/94359491/ac52db2f-ce87-4f14-93d9-980ab8ac096b)


Tested with GA4 disabled.

![image](https://github.com/google/site-kit-wp/assets/94359491/0eb7a590-97f1-4b5d-9f70-1019152f9050)

![image](https://github.com/google/site-kit-wp/assets/94359491/db4924e7-4266-42d8-993d-de478b866764)

</details>

**Comment by aaemnnosttv** [comment]
@marrrmarrr the AC about this issue seems to be specific to the title of the widget rather than changing all references to "users" -> "visitors" in the widget. Should we do the latter instead?

I think only the chart tooltips (main & pie charts) would need updating in All Traffic.

The only other reference I found to "users" is in the admin bar app.

**Comment by marrrmarrr** [comment]
@aaemnnosttv yes, it would make sense to update this everywhere, not just in the title of the widget.
