### ISSUE TITLE
Improve UX/UI on AdSense notifications

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7642]
## Bug Description

While testing the AdSense alerts in #7559 I spotted two UX/UI improvements that we should fix.

1. The AdSense logo and text is rather small and not consistant with other notifications. 
2. The SVG does not align very well with the text and CTA. 

Would be good to tidy up these when we can. 

## Steps to reproduce

1. Set up AdSense using an account that has a server alert (oi.ie has two which you can use to test this) 
2. Go to the Dashboard.  
3. The AdSense alert will appear (you might have to close other notifications that appear first) 
4. See UX/UI observations above. 

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/73545194/f9266e56-686f-48c5-b0c5-2c880344db2b)

## Additional Context

This issue appears on all supported browsers. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The SVG Icon that appears in the AdSense alert should be reduced in size to align with the text and CTA on its left, and have the unnecessary white spaces around it reduced. 

## Implementation Brief

* Update `assets/js/components/notifications/AdSenseAlerts.js` passing the class `googlesitekit-adsense-alert` to the `BannerNotification` component.
* Create a new scss file `assets/sass/components/adsense/_googlesitekit-adsense-alerts.scss` overiding the following notification styles for the AdSense notifications:
```
	.googlesitekit-adsense-alert {

		&.googlesitekit-publisher-win .googlesitekit-publisher-win__module-name {
			font-size: $fs-title-md;
		}

		.googlesitekit-publisher-win__image-small svg {
			width: 68px;
		}
	}
```

### Test Coverage

* Update VRTs. No further testing required.

## QA Brief

* Follow the steps to reproduce the issue and verify that the AdSense alert now appears with the updated styles.

## Changelog entry

* Improve UI/UX on AdSense alerts.

**Comment by eugene-manuilov** [comment]
AC 🌶️

**Comment by benbowler** [comment]
@eugene-manuilov @wpdarren I've been looking at this between other tickets and reviewing other banners in storybook and Figma. I don't think the AC matches the original ticket description which talks about increasing the font size of the banner title not reducing the icon size. To make it fully consistent with other site banners I think the AdSense logo should be removed completely and the banner be rephrased a little, this is what I think it should look like to match other banners using the `BannerNotification` component:

<img width="722" alt="Screenshot 2024-03-05 at 09 35 01" src="https://github.com/google/site-kit-wp/assets/119352/4ad6980f-6048-4684-85b9-c3e5ee0ea263">

Alternatively the AdSense logo could be included as the `BannerNotification` image.

What do you think?

**Comment by eugene-manuilov** [comment]
@benbowler i think the original idea for this task is not to make that banner look like other banners, but to fix style issues of that banner. But I can't say that what you suggest is wrong or bad. We need to ask @aaemnnosttv if we want to make those changes.

**Comment by benbowler** [comment]
The key point that is in ticket description but not covered in the AC is:

> 1. The AdSense logo and text is rather small and not consistant with other notifications.

**Comment by kuasha420** [comment]
@benbowler we discussed this in one of our ac sync. the plan here is to get a quick win by ensuring this is not ao ugly anymore. Feel free to file a follow up issue to suggest improvement.

**Comment by wpdarren** [comment]
@benbowler There are two issues with this notification.  1) The AdSense title, i.e logo, and text are small.  2) the SVG you highlighted above must be smaller and more aligned with the copy and CTA.  Generally, it needs tidying up because it looks a bit all over the place at the moment 😄

**Comment by benbowler** [comment]
@wpdarren do you have a storybook story or Figma design for another similar banner that I could use as the basis for choosing a font size/style for the title?

**Comment by wpdarren** [comment]
@benbowler  These notifications appear from the AdSense API and are a little different than normal notifications, so I am not sure we have anything to compare with. My thoughts are that we should chat with Sigal about this in the UX/UI channel and get her opinion on how she would like it to look.

**Comment by benbowler** [comment]
I started a low priority thread in Slack about refactoring these in future, which we can add new tickets for in future. In the short term I've created an IB that updates notifications to look like this:

<img width="806" alt="Screenshot 2024-03-18 at 13 51 04" src="https://github.com/google/site-kit-wp/assets/119352/c031419f-4abc-4351-b51d-359aff540fb9">

Which address the AC and original issue. Moving to IBR.

**Comment by eugene-manuilov** [comment]
Thanks, @benbowler. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠ 

@hussain-t I think this notice needs further improvement. We should increase the size of the AdSense logo and title, as well as the description. I will create a separate ticket for that. I’m currently focused on this ticket (AC).

Right now, the SVG icon size has decreased, and it looks misaligned with the left content. We aligned it with the description and CTAs, but I think we should center-align it with the left content. Let me know your thoughts. I’ve attached an example of the AdSense success notice.

<details>

![Image](https://github.com/user-attachments/assets/189a4832-add3-4951-9971-80ce139c67ca)

![Image](https://github.com/user-attachments/assets/f757205b-a477-4d88-a489-03ca1c842ead)


</details>

**Comment by hussain-t** [comment]
Thanks, @mohitwp. As we discussed over the call. Let's create a separate ticket to address the issue and move this to Approval.
