### ISSUE TITLE
Verification process leads to a 404 response on WordPress site

### ISSUE THREAD

**Issue by theeducatedbarfly** [google/site-kit-wp#765]
Trying to confirm and setup site kit in wordpress after installation.

This is the final step, and when I click proceed
[image](https://user-images.githubusercontent.com/57280839/68066735-f5a81380-fcf9-11e9-9bb8-156d3e5518f7.png)

I arrive at my website with the message something went wrong (page doesn't exist)

this is the url at the time

https://www.theeducatedbarfly.com/wp-admin/?googlesitekit_verification_token=%3cmeta%20name%3d%22google-site-verification%22%20content%3d%22WU7Sw8ca_Vz5ONIFIjv1kstQ5GWc__eaSTwWPX76kO4%22%20%2f%3e&googlesitekit_verification_nonce=93f53bc76b&googlesitekit_code=sitekit-5n3bcnsfypc16ari

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Sending the site verification token to the WordPress site should work as expected (storing the token and then redirecting back to the authentication service).

## Implementation Brief

* The problem is that in some environments, the HTML tag in the URL cannot be parsed correctly or is stripped for security purposes.
* On the authentication service, only the actual token value should be sent to the WordPress site, not the entire meta tag.
* In the plugin, the output should then be compatible with both variants (entire tag vs only the token) so that it works for full tags already being sent as well. It should add the `<meta name="google-site-verification"...` markup if it is the raw token.
* To make the authentication service still support the current plugin behavior, the plugin should send its currently active version to the proxy as a `version` URL parameter.

## Changelog entry

* Fix bug where the verification tag sent from the service to the plugin would result in a 404 response, preventing the verification from being completed.

**Comment by quangbahoa** [comment]
Me too after upgrade to 1.0

**Comment by felixarntz** [comment]
@theeducatedbarfly @quangbahoa Thanks for reporting this issue. We've investigated it and found a solution. It should be fixed in the coming release that we'll make available as soon as possible.

**Comment by theeducatedbarfly** [comment]
Thank you. Assume I have to reinstall the plugin once the update comes?

**Comment by felixarntz** [comment]
QA ✅ 

@ernee and I tested this on a Bluehost and Hostgator site that had this issue before, and it works as expected.

@theeducatedbarfly We're about to push version 1.0.1. After updating that, you should be able to reset and restart the setup flow.
