### ISSUE TITLE
Update "Enable enhanced measurement" banner to reduce the amount of times it hits the GA4 API.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7663]
## Feature Description

As mentioned [here](https://github.com/google/site-kit-wp/issues/7631#issuecomment-1747047108), the EM banner is currently hitting the GA4 API more often than it needs to, and this should be reduced to in turn reduce the load on users' GA4 quotas.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the Dashboard is loaded and the EM banner has already been dismissed, the banner should not make a request to the GA4 API for the EM settings.

## Implementation Brief

* Update the condition for bailing early in the following `useSelect()` to include a check for `! isBannerDismissed`:

https://github.com/google/site-kit-wp/blob/a5be2c656ae506e7333cb1d94967daa9b5166673/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/index.js#L78-L86

### Test Coverage

* Fix any failing tests.

## QA Brief

* Enable `enhancedMeasurement` feature flag.
* Set up Site Kit with Analytics so that the "Enhanced Measurement" notification banner appears on the dashboard. (Follow the QA steps in https://github.com/google/site-kit-wp/issues/7461 to ensure the "Enable Enhanced Measurement" notification banner appears.)
* Ensure an API request is made to `/wp-json/google-site-kit/v1/modules/analytics-4/data/enhanced-measurement-settings`
* Dismiss the notification banner for Enhanced Site Measurement
* Reload the page
* The API request to `/wp-json/google-site-kit/v1/modules/analytics-4/data/enhanced-measurement-settings` should NOT be made after the banner is dismissed.

## Changelog entry

* Update "Enable enhanced measurement" banner to reduce the amount of times it hits the GA4 API.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Only one API request is made to:
 `/wp-json/google-site-kit/v1/modules/analytics-4/data/enhanced-measurement-settings`
  - When page is loaded the Enhanced Site Measurement the request is made. 
 -  When dismissing the notification banner and reloading the page no API request is made. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/30389bf0-b3f6-4468-aa9d-02841203f149)
![image](https://github.com/google/site-kit-wp/assets/73545194/fafdc245-5f5a-4148-8501-77ab1352d260)

</details>
