### ISSUE TITLE
Implement HaTS survey triggers for ABR

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7686]
## Feature Description

Two new survey triggers should be implemented to support additional surveys for the Ad Blocking Recovery feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New survey triggers should be fired as follows:
	* `abr_setup_completed`: triggered when the ABR setup success banner is shown
	* `view_abr_setup_cta`: triggered when the ABR setup CTA widget is viewed (this is shown in the monetization section so it should consider whether or not it is in view as a condition)
		* As a view trigger, it should only be triggered at most once per day

### ABR setup success banner
* Render `<SurveyViewTrigger />` with trigger id `abr_setup_completed` and `DAY_IN_SECONDS` for `ttl` in https://github.com/google/site-kit-wp/blob/b80ce4ea163e041e4ae54c2b1d20bb07e369e10e/assets/js/components/notifications/AdBlockingRecoverySetupSuccessBannerNotification.js

### ABR setup CTA widget
* Render `<SurveyViewTrigger />` with trigger id `view_abr_setup_cta` and `DAY_IN_SECONDS` for `ttl` in https://github.com/google/site-kit-wp/blob/b80ce4ea163e041e4ae54c2b1d20bb07e369e10e/assets/js/modules/adsense/components/dashboard/AdBlockingRecoverySetupCTAWidget.js when `inView && shouldShowWidget` are true.

### Test Coverage

* Update `assets/js/modules/adsense/components/dashboard/AdBlockingRecoverySetupCTAWidget.test.js` and `assets/js/components/notifications/AdBlockingRecoverySetupSuccessBannerNotification.test.js` to test if survey triggered, you can see example in `assets/js/googlesitekit/datastore/user/user-input-settings.test.js`

## QA Brief

* Set up a site with AdSense and visit the main dashboard. Scroll down to the "Monetization" section and view the banner that prompts you to set up ABR on the Site Kit dashboard. (eg. "Recover revenue lost to ad blockers"). Note: this CTA is only present after 3 weeks from the initial AdSense setup. This can be bypassed using the custom date in the tester plugin.
  * Confirm that when you see this banner, there should be an HTTP `POST` request is made to `/wp-json/google-site-kit/v1/core/user/data/survey-trigger` with the body:

```
{
  "data": {
    "triggerID": "view_abr_setup_cta"
  }
}
```

The same trigger should be invoked from the CTA shown in the AdSense settings view. Since it's the same ID as the trigger on the dashboard, only the first will be observable per-user for 1 day. To see the other trigger, try using another user on the site (or separate sites).

(Use Chrome devtools or an HTTP proxy like Proxyman to view this.)

* Go through the usual QA steps to trigger the **Ad-Blocking Recovery setup success banner** (eg. set up AdSense and set up Ad Blocking Recovery).
  * Confirm that when you visit the Site Kit dashboard and see the Ad Blocking Recovery notification banner for ABR setup being completed successfully, there should be an HTTP `POST` request is made to `/wp-json/google-site-kit/v1/core/user/data/survey-trigger` with the body:

```
{
  "data": {
    "triggerID": "abr_setup_completed"
  }
}
```

(Use Chrome devtools or an HTTP proxy like Proxyman to view this.)

  * Refresh the page, and note that when viewing the banner after the first time, the survey is not triggered (because it will only be triggered once every 24 hours)

(In both instances you _should_ see a survey appear as well, as I (@tofumatt) was able to trigger one of the surveys, though now that I've triggered them I can't get them to appear again 😅 )

## Changelog entry

* Add happiness tracking surveys for the Ad Blocking Recovery feature.

**Comment by aaemnnosttv** [comment]
@wpdarren @mohitwp note this should be tested on `main`, thanks!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Tested with service staging and production environment.
- **Verified** 
- `abr_setup_completed: `triggered when the ABR setup success banner is shown
- `view_abr_setup_cta:` triggered when the ABR setup CTA widget is viewed on main dashboard or under in settings. 
- Verified  a view trigger, it triggered at most once per day
- Verified different surveys are appearing on main dashboard for user who completed setup of ABR and different for who is not completed ABR set up yet. 
- Verified with service staging and production environment.

<details>

**ABR set up complete survey on Production**


https://github.com/google/site-kit-wp/assets/94359491/1b38dc96-00b8-4e89-8d1c-0347d6b18760

**AdSense set up complete survey on Staging environment**


https://github.com/google/site-kit-wp/assets/94359491/9a6931b3-1db1-433c-85c4-0dda4da7e754


**ABR view CTA s on Staging environment**

![image](https://github.com/google/site-kit-wp/assets/94359491/097b291a-9324-4ba2-9389-61516e38f160)



![image](https://github.com/google/site-kit-wp/assets/94359491/268d6167-b056-4bfb-a1d9-c99472e9a985)

![image](https://github.com/google/site-kit-wp/assets/94359491/34a62657-6a9d-4906-971b-9b59e6f7ff8b)


![image](https://github.com/google/site-kit-wp/assets/94359491/99c28174-e78f-4b47-b55e-31e9443e1fa4)

![image](https://github.com/google/site-kit-wp/assets/94359491/1183dfdc-a612-4060-aebb-150774011d09)


https://github.com/google/site-kit-wp/assets/94359491/9de394dd-816e-4f44-86c7-a8f27e75ed80

</details>
