### ISSUE TITLE
Users Forced to Give Extra Permissions After Site Kit Plugin Update

### ISSUE THREAD

**Issue by VR51** [google/site-kit-wp#7688]
## Bug Description

This happens in most sites I manage. When the Site Kit plugin is updated to a new version the plugin requests additional permissions to interface with Google services.

## Steps to reproduce

1. Update the plugin

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/5859901/50cb315e-4b3f-4f35-92a5-b54647a121bc)

This is not a one-off occurrence. Every time a Site Kit plugin update is installed into multiple sites we are asked to 'Request Access'. Different sites. Different users.

In account owner shown in the above screenshot is also shown the same message.

The connection process is a bit of a mess, isn't it?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
@VR51 Thanks for getting in touch and sorry to hear you're having these issues. We don't provide support through GitHub but we'd be happy to help look into this for you further if you could please [open a new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) on the Site Kit support forum. 

When opening the support topic, could you please share the details of your issue as well as Your[ Site Health information](https://i.imgur.com/Rtkmsba.png). You can[ use this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) to share privately if preferred.

I will close this GitHub issue and hope to see you in the support forum, thanks!
