### ISSUE TITLE
Consolidate feature flags for key metrics

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7693]
## Feature Description

Initially the Key Metrics feature was developed behind the `userInput` feature flag, which has been around for a very long time and was initially a separate independent feature. User input will now be launched with Key Metrics, but so will the new News Key Metrics features which was originally planned to launch separately. Since these will all be launching together, it makes sense to unify them under a single feature flag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All use of the `userInput` and `newsKeyMetrics` feature flags should be updated to use a single `keyMetrics` feature flag
	* Care should be taken to only update references to feature flags

## Implementation Brief

* In `feature-flags.json`:
    * Remove `userInput` and `newsKeyMetrics` feature flags.
    * Add the new `keyMetrics` feature flag.
    * Ensure alphabetical order for consistency. 
* In some cases, The check for `newsKeyMetrics` feature flag is redundant and will be true because it is guarded by the `userInput` feature flag. This instances can be removed and can be assumed `true`. Refactor the following files with the aforementioned assumption.
    * `assets/js/components/KeyMetrics/key-metrics-widgets.js`
        * Usage in `displayInList` functions. 
    * `assets/js/googlesitekit/datastore/user/key-metrics.js`
        * The `publish_news` case of `getAnswerBasedMetrics` selector. 
    * `assets/js/googlesitekit/datastore/user/key-metrics.test.js`.
        * Remove `should return the correct metrics for the publish_news purpose when the newsKeyMetrics feature is enabled` test case and update the other test. 
* Across the code base, replace the usage of both  `userInput` and  the remaining instances of `newsKeyMetrics` feature flags with the newly introduced `keyMetrics` feature flag.
* Replace the corresponding variable names as well. ie. 
````diff
-    const userInputEnabled = useFeature( 'userInput' );
+    const keyMetricsEnabled = useFeature( 'keyMetrics' );
````
* Update any comments reference to reflect the changes. ie. 
````diff
-        The userInputEnabled check can be removed once the User Input feature is fully launched
+        The keyMetricsEnabled check can be removed once the User Input feature is fully launched
         and we remove this feature flag.
````

### Test Coverage

* Update any failing tests. 

## QA Brief

* The tester plugin should have `keyMetrics` feature flag. Turning this on would work same as the previous `userInput` and `newsKeyMetrics` feature flag enabled together. 
* The  `userInput` and `newsKeyMetrics` feature flags should no longer exist in tester plugin .
* Perform general smoke testing of User Input and Key Metrics (+News Key Metrics) features to ensure no regression were introduced. 

## Changelog entry

* Consolidate feature flags used for Key Metrics.

**Comment by tofumatt** [comment]
IB ✅

**Comment by bethanylang** [comment]
Noting that we need to hold on this one until _after_ we've completed NKMT engineering (est. Oct 20) as well as Bug Bashing (Oct 23-25). This means we can work on it later in week 1 of Sprint 113.

Please do not work on this issue without confirming with me and @aaemnnosttv first. Thank you!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Checked to make sure that the Key Metrics widget does not appear when `keyMetrics` is disabled.
- Checked to make sure that the Key Metrics widget does appear when `keyMetrics` is enabled.
- Went through the user input survey steps. Confirmed works as expected. 
- Confirmed that the tiles for non news selection appear as expected. 
- Confirmed that the tiles for news selection appear as expected.
- Tested to make sure new metrics can be chosen from the metrics selection panel. 
- Tested on view only dashboard to ensure that the Key Metrics widget behaves as expected.
- Made sure that CTA link in the SK settings appears when user input survey not completed. 
- MAde sure the responses to questions appears in SK settings when questions are completed. 

We will continue to keep an eye out on things as we continue to test the Key Metrics widget, but all looks fine from my smoke testing carried out today. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/7781029c-4d23-4b8d-ac89-01b772c64ddf)
![image](https://github.com/google/site-kit-wp/assets/73545194/0bf6592d-279c-46b8-aaa7-db0d78833e2e)
![image](https://github.com/google/site-kit-wp/assets/73545194/7b1a65b3-b8c5-4872-add5-cc5a6bc9683a)
![image](https://github.com/google/site-kit-wp/assets/73545194/4bf25c1d-5c4f-49da-96b6-8fa022765292)
![image](https://github.com/google/site-kit-wp/assets/73545194/0535ae28-a147-4bdd-94b5-3326d58b4c8b)
![image](https://github.com/google/site-kit-wp/assets/73545194/7f7329b5-dcaf-4012-a1cb-93828e9b8607)
![image](https://github.com/google/site-kit-wp/assets/73545194/e245780e-a3bd-4a61-b4fb-935fedcd066b)

</details>
