### ISSUE TITLE
Implement new design updates to Metrics Selection Panel

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7704]
## Feature Description

The Figma design for KMW introduced a new iteration for the Metrics Selection Panel with the following notable changes:
1. Increased width in larger viewports.
2. Header and footer changes.

These new changes should be implemented in the application.

<details>
<summary>Here's a screenshot for reference (from Figma)</summary>

![image](https://github.com/google/site-kit-wp/assets/20284937/cab5ff15-5986-4f67-86d7-9a6ad13122c4)

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The width of the Key Metrics Selection Panel should be changed to 530 pixels for larger viewports (in viewports smaller than 601px, it should automatically take the full-width like it does today).
- Footer changes:
  - The footer subtext `Set your personalized goals or deactivate this widget in Settings` should be removed.
  - The CTA buttons should be pushed to the right, and the metric count should be relocated from the header to the footer left (according to designs).
  - A new notification option should be added that sticks to the footer like the designs. The custom dimensions notification added in #7599 should be displayed according to the designs using this option.
- Header changes
  - Subtext should be added to the header under the heading that should say `Edit your personalized goals or deactivate this widget in <link>Settings</link>`. The link should navigate the user to the Site Kit Admin Settings.
 

## Implementation Brief

- In `assets/sass/components/global/_googlesitekit-side-sheet.scss`:
  - Set the width of `.googlesitekit-side-sheet` to `530px` for non-mobile viewports.
- In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`:
  - Create a 2-column layout accommodating the actions to the right.
  - In the left column, render the selected metric count which can be found in `assets/js/components/KeyMetrics/MetricsSelectionPanel/Header.js`.
  - Move the footer note to the `assets/js/components/KeyMetrics/MetricsSelectionPanel/Header.js` component.
  - Add a new `div` for the optional notification that should be fixed to the footer. Relocate the custom dimension notification introduced in #7599 to this new `div`.
  - Style the footer and attached notification according to the Figma designs.
- In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Header.js`:
  - Replace the selected metric count with the footer note, but change the class name to something like `googlesitekit-km-selection-panel-header__note`. Change font styles accordingly.
- In `assets/sass/components/key-metrics/_googlesitekit-km-selection-panel.scss`:
  - Add any new necessary styles.
  - Remove any styles that get redundant due to the changes here.

### Test Coverage

- Update tests to change DOM location of targetted elements.
- Update VRT references.

## QA Brief

- Set up Site Kit.
- Enable the `userInput` and `newsKeyMetrics` feature flag.
- In the KMW setup CTA, choose to select your own metrics.
- Verify the metric selection panel appears according to the Figma designs with the AC satisfied.
- Check a metric tile that depends on custom dimensions, e.g. `Top categories by pageviews`. Verify that the notice appears according to the Figma designs.
- Verify that the flicker reported [here](https://github.com/google/site-kit-wp/issues/7704#issuecomment-1779021331) is fixed.
- Verify that the metric titles in the selection panel are perfectly aligned (center) with the checkboxes.

## Changelog entry

* Update Key Metrics selection panel design.

**Comment by nfmohit** [comment]
Note to AC reviewer: I've also added IB, if everything looks good, please move to EB. Feel free to assign it to me, thanks!

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit – LGTM!

AC + IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

@nfmohit 
- Tested on dev environment
- Notifications under footer getting flicker and gets hide immediately after appearing.
- Expected - Notification should not disappear. It should display continuously under footer.


https://github.com/google/site-kit-wp/assets/94359491/00902de5-3fc2-475c-8b9a-6d1a2cda89ae


https://github.com/google/site-kit-wp/assets/94359491/1b932d7d-18e3-48a8-8338-025ed221d832

**Comment by techanvil** [comment]
Back with you for another pass, @mohitwp.
