### ISSUE TITLE
Update Enhanced Measurement switch to be enable-only.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7706]
## Feature Description

As discussed on [Asana](https://app.asana.com/0/1205698727526075/1205707964043436/f), we are changing how Enhanced Measurement works to make the switch an "enable-only" control, and not provide the functionality within Site Kit to disable EM.

This will involve replacing the Enhanced Measurement switch with a piece of static text in the cases where Enhanced Measurement is already enabled for the selected web data stream, and updating the submission process to avoid making a request to disable EM in any scenario.

---------------

## Acceptance Criteria

- On both the Setup and Settings screens, when a web data stream is selected which does have EM enabled, the EM switch and label should be replaced with the following text:
  - _Enhanced measurement is enabled for this web data stream._
- The description below the switch/text should be updated in all cases to read as follows:
  - _This allows you to measure interactions with your content (e.g. file downloads, form completions, video views). Learn more_
    - The "Learn more" link should continue to point to the same support URL i.e. https://support.google.com/analytics/answer/9216061.
- The behaviour of the switch should remain the same in all other cases.
- However, when it comes to submitting the changes, it should be ensured that if the switch is off, we don't make a request to GA4 to _disable_ EM under any circumstances.

## Implementation Brief

In `assets/js/modules/analytics-4/datastore/enhanced-measurement.js`:

* **New Selector for `savedSettings.streamEnabled`**:
    * Introduce a new selector called `isEnhancedMeasurementStreamAlreadyEnabled`.
    * This selector should receive the `propertyID` and `webDataStreamID` as arguments.
    * Return the boolean state of `savedSettings.streamEnabled` for the selected data stream.

In `assets/js/modules/analytics-4/components/common/EnhancedMeasurementSwitch.js`:

* **Introduce the `isEnhancedMeasurementAlreadyEnabled` Prop**:
    * Add a new prop called `isEnhancedMeasurementAlreadyEnabled` with the default value of `false`.
* **Text Replacement for Enabled Web Data Streams**:
    * Conditionally render the text "_Enhanced measurement is enabled for this web data stream._" if `isEnhancedMeasurementAlreadyEnabled` prop is `true`.
    * If `isEnhancedMeasurementAlreadyEnabled` is `false`, the switch behavior remains unchanged, and the switch component should be rendered.
* **Description Text Update**:
    * Update the description text per the AC regardless of the rendered switch or text.
    * The "Learn more" link should continue pointing to the same support URL as the AC.
* **Refactoring**:
   * Consider refactoring the component for better readability given the new conditional rendering.
* The text "Enhanced measurement is enabled for this web data stream" should not appear when the `loading` prop is active. Instead, display the progress bar.

In `assets/js/modules/analytics-4/components/settings/SettingsEnhancedMeasurementSwitch.js` and `assets/js/modules/analytics-4/components/setup/SetupEnhancedMeasurementSwitch.js`:

* Use the `isEnhancedMeasurementStreamAlreadyEnabled` selector to get the current saved state of the Enhanced Measurement.
* Ensure the conditions for invoking the `isEnhancedMeasurementStreamAlreadyEnabled` selector match those of the `isEnhancedMeasurementStreamEnabled()` selector call, specifically checking:
    - Properties and web data streams are not loading.
    - Both `propertyID` and `webDataStreamID` are valid and not placeholders (`PROPERTY_CREATE` / `WEBDATASTREAM_CREATE`).
* Pass this value to the `isEnhancedMeasurementAlreadyEnabled` prop of the `EnhancedMeasurementSwitch` component.
* There's no need to pass the `isEnhancedMeasurementAlreadyEnabled` prop to the `EnhancedMeasurementSwitch` component from the `AccountCreate` component. Keep the toggle switch available during the account creation process.

Additionally, In `assets/js/modules/analytics-4/components/setup/SetupEnhancedMeasurementSwitch.js`:
    * Determine the loading state and supply the `loading` prop to `EnhancedMeasurementSwitch`. Similarly it is done in `SettingsEnhancedMeasurementSwitch`.

In `assets/js/modules/analytics-4/datastore/settings.js`:

* **Preventing Disable Request**:
    * In the `submitChanges` function, locate the condition checking if `isEnhancedMeasurementEnabled` is not undefined. See:
    https://github.com/google/site-kit-wp/blob/30c4a0eafcf8aa8107400143a0e28bceae7c40f0/assets/js/modules/analytics-4/datastore/settings.js#L115
    * Change this condition to check if `isEnhancedMeasurementEnabled` is true. This ensures we only send requests to GA4 to enable Enhanced Measurement and not to disable it.

* **Storybook Stories**:
   * Add new stories to include scenarios for when the web data stream has EM enabled, ensuring the switch is replaced with the static text.

### Test Coverage

* Add test coverage for the new selector in `enhanced-measurement.test.js`.
* Add unit tests for the new scenarios in `EnhancedMeasurementSwitch.test.js`.
* Fix any broken tests.
* Add VRT scenarios for the new changes.

## QA Brief

* Set up Site Kit with GA4 with the enabled `enhancedMeasurement` feature flag.
* Go to the Analytics settings edit screen.
* Verify the switch is replaced with the static text as per the AC when the web data stream has EM (already) enabled.
* Go to the Analytics console for the selected property and web data stream and disable EM.
* Go back to the Analytics settings edit screen.
* Verify the text is replaced with the switch in the "off" position.
* Changing the account, property, or web data stream should work as it does currently.
* Go to the Analytics setup screen.
* Verify the switch is replaced with the static text as per the AC when the web data stream has EM (already) enabled.
* Select a property that doesn't have EM enabled.
* Verify the switch is rendered with the "on" position.
* Changing the account, property, or web data stream should work as it does currently.
* Ensure if the switch is in the "off" position, the request to disable the EM setting is not sent when submitting the changes from the settings and setup screens. In other words, the request should only be sent to enable the EM setting not to disable it.
* Ensure the loading state is handled correctly in the settings and setup screens as per the AC.

## Changelog entry

* Update Enhanced Measurement switch to be enable-only.

**Comment by techanvil** [comment]
Hi @hussain-t, thanks for drafting this IB, however it does needs some adjustment.

As specced, the switch would be unusable in the cases where we still need to be able to toggle it from off to on.

Specifically, on the Create Account page the toggle still needs to remain as it is now. Also, in cases where EM is _disabled_ for the web data stream, the user needs to be able to toggle the switch on, and for it to remain a switch so they can toggle it off if they change their mind.

This will likely revolve around the usage of `isEnhancedMeasurementStreamEnabled()` rather than the form value `isEnhancedMeasurementEnabled`.

With regard to the AC point about ensuring we don't make a request to GA4 to _disable_ EM under any circumstances, this likely means changing the check for `isEnhancedMeasurementEnabled !== undefined` here to `isEnhancedMeasurementEnabled === true` (or just a truthy check):

https://github.com/google/site-kit-wp/blob/30c4a0eafcf8aa8107400143a0e28bceae7c40f0/assets/js/modules/analytics-4/datastore/settings.js#L115

**Comment by hussain-t** [comment]
Thanks, @techanvil. I've updated the IB based on your clarification.

**Comment by techanvil** [comment]
Hey @hussain-t, this is looking better. A few further points to consider:

- How about we name the selector `isEnhancedMeasurementStreamAlreadyEnabled()` instead of `isEnhancedMeasurementSavedEnabled`?
- It's worth mentioning that the conditions for calling the `isEnhancedMeasurementStreamAlreadyEnabled()` selector in the `SettingsEnhancedMeasurementSwitch` and `SetupEnhancedMeasurementSwitch` component should be the same as for calling the `isEnhancedMeasurementStreamEnabled()` selector in `SettingsEnhancedMeasurementSwitch`, i.e. only when the properties and web data streams are not loading, and we have a valid `propertyID` and `webDataStreamID` (valid meaning they are actual IDs and not `PROPERTY_CREATE` / `WEBDATASTREAM_CREATE`).
https://github.com/google/site-kit-wp/blob/434621f91ad2a606035b9927f7fa3510a8d15cad/assets/js/modules/analytics-4/components/settings/SettingsEnhancedMeasurementSwitch.js#L81-L90
- We'll want to determine the loading state in `SetupEnhancedMeasurementSwitch` and pass the `loading` prop to `EnhancedMeasurementSwitch`.
- This is probably obvious enough when implementing but it might be worth clarifying that the "Enhanced measurement is enabled for this web data stream" should not be rendered when the `loading` prop is passed, and the progress bar should be rendered as usual in this case.

**Comment by hussain-t** [comment]
Thanks, @techanvil. It's back to you for another review.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t I have a few observations on this change. 

1. EM is enabled and I go to Analytics Settings, in edit.  The CTA is active and displaying as `Save` on load even though I have not made any changes to the settings. Previously the CTA was inactive and grey until I made any changes.  I am assuming this is not expected? 

![image](https://github.com/google/site-kit-wp/assets/73545194/188291a9-790c-461e-a3b3-4d8b8bb14a29)

2. I ran through some additional testing, and noticed with the `enhancedMeasurement` feature flag enabled on a new site that does not have any Analytics account associated with it, the EM loading animation continues and doesn't stop until you either select an account or, create a new one.  It's an odd user experience.  I know we're planning to remove this from the setup flow in #7784 but thought I would raise here since this ticket might not be ready for launch. 

3. This is minor, but do we usually include a period after a one line sentence. `Enhanced measurement is enabled for this web data stream.` Other similar messages in settings don't have a period. Thought I would mention for consistency. 

**Verified:**

- On both the Setup and Settings screens, when a web data stream is selected which does have EM enabled, the EM switch and label is replaced with the following text: `Enhanced measurement is enabled for this web data stream.`
  - The description below the switch/text is updated in all cases to read as follows:  `This allows you to measure interactions with your content (e.g. file downloads, form completions, video views). Learn more.`
  - The "Learn more" link continues to point to the support URL 
  - The behaviour of the switch remains the same in all other cases.
- When it comes to submitting the changes, and the switch is off, we don't make a request to GA4 to disable EM.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/2f741825-92da-4488-8f71-81139d05e6f2)
![image](https://github.com/google/site-kit-wp/assets/73545194/1f749126-875a-42f6-8ef6-0c8958a5c7e0)
![image](https://github.com/google/site-kit-wp/assets/73545194/8880fa1f-0baa-4a1e-995f-d114815aa61f)
![image](https://github.com/google/site-kit-wp/assets/73545194/289a03a0-e3db-42f9-89fd-745ad8a1d613)
https://github.com/google/site-kit-wp/assets/73545194/49cce5ca-47a6-4bfe-8613-b33ecb1e0c51
https://github.com/google/site-kit-wp/assets/73545194/30acaf60-a0e2-4587-ac7c-1d97018cdcb2

</details>

**Comment by hussain-t** [comment]
Thanks, @wpdarren. Regarding your observations:

>EM is enabled and I go to Analytics Settings, in edit. The CTA is active and displaying as Save on load even though I have not made any changes to the settings. Previously the CTA was inactive and grey until I made any changes. I am assuming this is not expected?

We did change the behaviour of the submit button in [7533](https://github.com/google/site-kit-wp/issues/7533). Please take a look at it.

>This is minor, but do we usually include a period after a one line sentence. Enhanced measurement is enabled for this web data stream. Other similar messages in settings don't have a period. Thought I would mention for consistency.

Yes, that's a good catch. I will fix it in a follow-up PR.

>I ran through some additional testing, and noticed with the enhancedMeasurement feature flag enabled on a new site that does not have any Analytics account associated with it, the EM loading animation continues and doesn't stop until you either select an account or, create a new one. It's an odd user experience. I know we're planning to remove this from the setup flow in https://github.com/google/site-kit-wp/issues/7784 but thought I would raise here since this ticket might not be ready for launch.

@techanvil, do you have any thoughts on the above?

**Comment by techanvil** [comment]
Re. the outstanding question about the loading state, as discussed in the standup we've raised the priority of https://github.com/google/site-kit-wp/issues/7784 as this issue will remove the described scenario making it a non-issue.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On both the Setup and Settings screens, when a web data stream is selected which does have EM enabled, the EM switch and label is replaced with the following text: `Enhanced measurement is enabled for this web data stream.`
  - The description below the switch/text is updated in all cases to read as follows:  `This allows you to measure interactions with your content (e.g. file downloads, form completions, video views). Learn more.`
  - The "Learn more" link continues to point to the support URL 
  - The behaviour of the switch remains the same in all other cases.
- When it comes to submitting the changes, and the switch is off, we don't make a request to GA4 to disable EM.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/2f741825-92da-4488-8f71-81139d05e6f2)
![image](https://github.com/google/site-kit-wp/assets/73545194/1f749126-875a-42f6-8ef6-0c8958a5c7e0)
![image](https://github.com/google/site-kit-wp/assets/73545194/8880fa1f-0baa-4a1e-995f-d114815aa61f)
![image](https://github.com/google/site-kit-wp/assets/73545194/289a03a0-e3db-42f9-89fd-745ad8a1d613)
https://github.com/google/site-kit-wp/assets/73545194/49cce5ca-47a6-4bfe-8613-b33ecb1e0c51
https://github.com/google/site-kit-wp/assets/73545194/30acaf60-a0e2-4587-ac7c-1d97018cdcb2

</details>
