### ISSUE TITLE
Show placeholder text when author or category is not found in WordPress

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7720]
## Feature Description

In some rare cases, the display name for an author or category ID that has been tracked in Analytics could "not be found" in the WordPress database. This could be because the Author or Category was deleted since it was tracked. 

<img width="755" alt="Screenshot 2023-10-24 at 16 07 30" src="https://github.com/google/site-kit-wp/assets/1721319/ca1a7934-d431-453b-9eec-60f342105ed1">

Note: This is for the authors and categories where an ID number is being displayed. We are able to differentiate between a category or ID that is an actual integer and an integer ID.

-- Updates until 8 Nov 2023 -- 

The news team suggested we don't use IDs only since this data is not very useful outside of Site Kit - a consideration we never had to make before. 

After a lot of discussion in Slack ([thread](https://10up.slack.com/archives/CBKKQEBR9/p1699459744783679), [thread](https://10up.slack.com/archives/CBKKQEBR9/p1699366615655859), [thread](https://10up.slack.com/archives/CFFRMC5DE/p1699353032785939)) we decided to use `usernames` for Authors since they are immutable and slug-names for categories which would change less often than their display names. The downside here is that if any of these are modified, we won't be able to decipher the modifications e.g. categoryA is changed to categoryZ, we will track and display page views for both categories separately.

An improvement here could be to track IDs as well - however, having them in the existing custom dimensions would mean having two pieces of data in a single custom dimension. This would be hard to report on. 

We could potentially track IDs of authors and categories as separate custom dimensions. However, currently, if a page URL changes, we don't go to extreme lengths to preserve the GA metrics across all versions of a pages's URL that it may have tracked data for. So we find no real need to track IDs for such edge cases.

-- Update: 9th Nov 2023 --

In the end, tracking author's `usernames` could not be very user friendly within the Analytics Admin Dashboard (and within Site Kit) as journalists might not use their full names within their username which is usually what is displayed to the public on a post and is user friendly to see in a report. So we will stick to tracking and displaying author's display names.

Similarly, instead of tracking slug names, we decided to track the proper Category names.

We have intentionally decided not to worry about the edge case where an author or category name is modified since it was tracked. Firstly, these are edge cases. The user can still create an aggregate report knowing what they've modified. And also, for a specific report duration (i.e. 28 days), the difference between the tracked name and the modified name will rarely be an issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For the `googlesitekit_post_author` custom dimension, track the post author's `display_name` when sending data to GA and when displaying authors in the `Top Authors` KMW tile instead of the author ID.
    * If the display name is not set, we should fall back to using the username (if WP does not do this by default).
* For the `googlesitekit_post_categories` custom dimension, track a list of category `name` when sending data to GA and when displaying them in the `Top Categories` KMW tile instead of the list of category IDs.
    * Each category should be split using `; `. E.g. `Oranges, Pears, and others; Vegetables; Gardening`

## Implementation Brief

* In `includes/Modules/Analytics_4.php`, modify the `get_custom_dimensions_data() method`:
  * For the `googlesitekit_post_author` case:
    * Pass the `$post->post_author` to the `get_userdata()` function to fetch the `$user` object.
    * Set `$data[ $custom_dimension ]` to be `$user->display_name`. If the `$user->display_name` is empty, fall back on `$user->user_login`.
    * Similar to the recent fix for blank categories, if there is no post author ID or user found for the author ID (some manual database corruption), then do not set this custom dimension.
  * For the `googlesitekit_post_categories` case:
    * Using wp_list_pluck(), pluck the `name` property within `$categories`.
    * Set `$data[ $custom_dimension ]` to use implode - however, use `; ` (semicolon with a space) as the separator.

* In `includes/Modules/Analytics_4/Report/Response.php`:
  * Remove the lines in `parse_response` which uses the `Custom_Dimensions_Response_Parser` class to modify the `$response` object.

* Remove the `Custom_Dimensions_Response_Parser` class and its associated tests.

* In `assets/js/modules/analytics-4/components/widgets/PopularAuthorsWidget.js`:
  * Modify the `dimensionFilters` as per the IB of #7737 to create a not expression that matches exactly `(not set)` rather than digits only.

### Test Coverage

* Update `Analytics_4Test::test_get_custom_dimensions_data()` to match the above.

## QA Brief

* On a test site, connect Site Kit to GA4 with a property that has no old custom dimensions data.
* Check the Google Analytics snippet added by Site Kit on the front end, i.e. the Post pages which have an author and some categories. Verify the gtag JS config has names now as per the AC for the above custom dimensions instead of IDs.
* Using the same test site which now tracks authors and categories with names (instead of IDs), wait a day and check again the next day to ensure the categories and authors still display names in their respective TopCategories and PopularAuthors KMW tiles as before despite the change in the tracking format. 
* Verify that there are no `(not set)` records appearing for the Popular Authors widget tile. (As is the case already - but ensure a regression isn't added here.) Also test the same for the Popular Categories widget tile.

#### Additional QAB for the followup PR:

- Connect Site Kit to a GA4 property that doesn't have the custom dimensions setup.
- Create the custom dimensions via the Key Metrics tiles.
- Verify the custom dimension descriptions are created in Analytics as follows:
  - `googlesitekit_post_date`: _Created by Site Kit: Date when a post was created_
  - `googlesitekit_post_author`: _Created by Site Kit: WordPress name of the post author_
  - `googlesitekit_post_categories`: _Created by Site Kit: Names of categories assigned to posts_
  - `googlesitekit_post_type`: _Created by Site Kit: Content type of posts_
- Verify the custom dimension names and descriptions are created in English regardless of the language settings in WordPress.

## Changelog entry

* Track author and category names rather than IDs for the relevant custom dimensions, and display as they are in their corresponding Key Metrics widgets.

**Comment by sigal-teller** [comment]
@jimmymadon  I think we should wait for @marrrmarrr on this one. I'm wondering how helpful it is for the user to see data for an unknown author. I don't think there's any benefit in that number if he can't see which author is this, which is the purpose of this tile. If there's a way to work around it that would be great.

**Comment by marrrmarrr** [comment]
Ok, so how about the following: 
- send both ID and display names to GA4
- if a display name is not set, in Site Kit UI show something like "author name not set (ID 123)" or "category name not set (ID 123)"?

Regarding the exact wording, what could have happened here? Which of "not found", "deleted", "not set" most accurately reflects the possible cause?

**Comment by marrrmarrr** [comment]
@jimmymadon "name not found" followed by the numeric ID sounds like a good approach. 
Regarding modified/deleted names -- I think for deleted names this should work, e.g. even if a particular author is no longer writing at a publication, it's ok to show their previous articles' pageviews with their names. How would this work if e.g. an author's name has been modified for whatever reason? Would then we keep attributing the pageviews for the modified name to the previous name?

**Comment by marrrmarrr** [comment]
Thanks @jimmymadon! I actually haven't heard anything from them on this topic, so let me have a quick chat and will get back to you on this one.

**Comment by aaemnnosttv** [comment]
AC ✅ 

This change will make the ID parsing of the report for these dimensions unnecessary (no longer used) so we might want to open a follow-up to remove this but we could also include it in the IB for this one as it's probably quite straightforward. Later if we decide to do this again for whatever reason we can always pull code back from the history rather than keep it around as unused.

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – overall LGTM

> * Modify the `dimensionFilters` as per the IB of [Handle '(not set)' in GA4 report data #7737](https://github.com/google/site-kit-wp/issues/7737) to create a not expression that matches exactly `(not set)` rather than digits only.

Do we not also need to modify the `dimensionFilters` of `TopCategoriesWidget` then as well? Or is this being handled in a separate issue?

Regarding the author dimension data, I don't see the fallback accounted for which is mentioned in the AC:

> * If the display name is not set, we should fall back to using the username (if WP does not do this by default).

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon – one thing that comes to mind about the author specifically is that it's possible that the user no longer exists on the site in which case no data will be returned for the user. This shouldn't be possible under normal circumstances since WP makes you choose between transferring ownership of their content to another user or deleting a user's content when deleting the user. In order to avoid a potential error, we should not set the author dimension at all (since they don't exist).

Regarding the filtering of `(not set)` does this issue need to depend on another if it is going to rely on functionality added elsewhere?

**Comment by aaemnnosttv** [comment]
Thanks @jimmymadon !

IB ✅

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ 

**Verified:**

- Checked the Google Analytics snippet added by Site Kit on the front end, i.e., the Post pages with an author and some categories. The gtag JS config has names now as per the AC for the above custom dimensions instead of IDs.

On hold, waiting 24 hours for data to appear in the tiles.


<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/6fd525d5-e9c1-4b74-9f8c-9827e9d2acc1)
![image](https://github.com/google/site-kit-wp/assets/73545194/aad83f6c-56d4-4901-959f-f74d4cd999c2)
![image](https://github.com/google/site-kit-wp/assets/73545194/bbac7504-acb4-4db2-a749-e3be51e656da)
![image](https://github.com/google/site-kit-wp/assets/73545194/a9789012-fc3e-40ac-bd5d-943f194b5bf5)

</details>

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@jimmymadon I am still seeing gathering data state on the category and author tiles.  When I tested this prior to this change, the data came through within 24 hours.   When I run the report in Analytics, I do see the data as you can see from my screenshots below. 

![image](https://github.com/google/site-kit-wp/assets/73545194/80ad69b8-2600-4513-857f-83a91f34276e)

![image](https://github.com/google/site-kit-wp/assets/73545194/c03def93-b96f-4eb0-ab08-d4f71b07423e)

![image](https://github.com/google/site-kit-wp/assets/73545194/9006e746-c40f-4ca8-bdf7-bba8623cb5de)

Any ideas why this could be? I will continue to check the site .

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The gtag JS config has names now as per the AC for the above custom dimensions instead of IDs.
- The categories and authors still display names in their respective `TopCategories` and `PopularAuthors` KMW tiles as before despite the change in the tracking format.
-There are no `(not set)` records appearing for the Popular Authors and Categories widget tiles. 

![image](https://github.com/google/site-kit-wp/assets/73545194/0d22ba35-776d-47af-9389-f651232fe15e)
![image](https://github.com/google/site-kit-wp/assets/73545194/734cf60a-09c9-4062-9742-77702edbbd28)

**Comment by aaemnnosttv** [comment]
## ❌ Approval

While the data is being tracked properly, the descriptions of the respective custom dimensions still reference the old value form, which is confusing and something we should correct

https://github.com/google/site-kit-wp/blob/87ca64284f21c63ac59bf3496c444a85aa854da2/assets/js/modules/analytics-4/datastore/constants.js#L54-L57

https://github.com/google/site-kit-wp/blob/87ca64284f21c63ac59bf3496c444a85aa854da2/assets/js/modules/analytics-4/datastore/constants.js#L63-L66

**Comment by aaemnnosttv** [comment]
This is all good now 👍
