### ISSUE TITLE
Add GA event tracking for Enhanced Measurement.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7723]
## Feature Description

GA events should be added to keep track of Enhanced Meaurement interaction for users who have opted into the anonymous usage data reporting.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given Enhanced Measurement actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307&range=190:197).

Event Name | Category | Trigger | Condition
-- | -- | -- | --
activate_enhanced_measurement | {viewContext}_analytics |	click | User activates toggle to enable Enhanced Measurement 									
deactivate_enhanced_measurement | {viewContext}_analytics |	click | User deactivates toggle to disable Enhanced Measurement 									
view_notification | {viewContext}_enhanced-measurement-notification |	element visibility | Enhanced Measurement activation notification appears on the SK dashboard									
confirm_notification | {viewContext}_enhanced-measurement-notification | click | User clicks "Enable now" CTA in the dashboard banner 									
dismiss_notification | {viewContext}_enhanced-measurement-notification | click | User clicks "Maybe later" on the banner									
click_learn_more_link | {viewContext}_enhanced-measurement-notification |	click | User clicks "Learn more" on the banner									
view_notification | {viewContext}_enhanced-measurement-success | element visibility | Enhanced Measurement success banner appears on the SK dashboard									
confirm_notification | {viewContext}_enhanced-measurement-success | click | User clicks "OK Got it" CTA in the dashboard banner 									

## Implementation Brief

* In `assets/js/modules/analytics-4/components/common/EnhancedMeasurementSwitch.js`
  * Inside [`handleClick`](https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/assets/js/modules/analytics-4/components/common/EnhancedMeasurementSwitch.js#L58) callback function, depending if `isEnhancedMeasurementEnabled` is true or false, send `trackEvent` with event `activate_enhanced_measurement` or `deactivate_enhanced_measurement` with category from AC
* In `assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/index.js`
  * Add `useMount` hook, since banner will be always be visible on top of the page (in view), when available
    * Check if `! isTooltipVisible` to send `trackEvent` for `view_notification` with category `{viewContext}_enhanced-measurement-notification`
  * In `handleDismiss` callback, add `trackEvent` for `dismiss_notification` with category from AC
* In `assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js`
  * Add `trackEvent` for `confirm_notification` and category `{viewContext}_enhanced-measurement-notification`, to the `handleSubmitChanges` callback
  * Add `onLearnMoreClick` prop to the `BannerNotification` component, and create callback function that will send `trackEvent` for `click_learn_more_link ` with category from AC
* In `assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SuccessBanner.js`
  * Add `useMount` hook, since this notification will mount only when setup is successful, and be in view (top of the page)
    * add `trackEvent` for `view_notification` with category `{viewContext}_enhanced-measurement-success`
  * In the [`onDismiss`](https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SuccessBanner.js#L58-L62) callback block, send `trackEvent` for `confirm_notification` and category `{viewContext}_enhanced-measurement-success`

### Test Coverage

* No test updates needed

## QA Brief

* Follow QA briefs from #7459 and #7461 to get the "Enable enhanced measurement" toggle and the "Enable enhanced measurement" notification banner for your site.
* Ensure your Site Kit settings have "Send Analytics to Google" enabled (either during setup or in the Site Kit Settings).
* Using the Google Analytics Debugger plugin, verify that correct events are tracked as defined in AC.

## Changelog entry

* Add Analytics events for Enhanced Measurement features.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov on the success notification, there is a learn more link there too.  No GA event is triggered for this and while it's not covered in the AC, do we feel it should be? 

![image](https://github.com/google/site-kit-wp/assets/73545194/949fd8f1-64bd-4c49-94b0-b390cc778f28)

**Verified:**

- The correct events are tracked as defined in AC.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/f4d7a7b4-ea44-4ebc-85ce-b061f5ef6ce0)
![image](https://github.com/google/site-kit-wp/assets/73545194/30bc3663-5a9c-4cb7-8b7c-9c84454f41bb)
![image](https://github.com/google/site-kit-wp/assets/73545194/ba261509-1ad6-404c-9512-46895fbb7048)
![image](https://github.com/google/site-kit-wp/assets/73545194/978f6aa4-44e6-473e-8e91-ab376d10d9b2)
![image](https://github.com/google/site-kit-wp/assets/73545194/a42efb02-d565-4b86-b88f-c44fce15db95)
![image](https://github.com/google/site-kit-wp/assets/73545194/f6d9c1ea-e03e-42c7-b676-995991c2ae4a)
![image](https://github.com/google/site-kit-wp/assets/73545194/974cd29a-bca8-4f88-8179-6e3ac865fb72)
![image](https://github.com/google/site-kit-wp/assets/73545194/22af41d4-faec-4617-8081-c5274c0790e6)

</details>

**Comment by eugene-manuilov** [comment]
Looks like I forgot to add it, @wpdarren. I'll create a follow up PR.

**Comment by eugene-manuilov** [comment]
@wpdarren, actually, after checking it one more time, there should be no GA event tracked for that "Learn more" link on the success banner. We need to track the "Learn more" link on the setup banner, but not on the success one.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The correct events are tracked as defined in AC.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/f4d7a7b4-ea44-4ebc-85ce-b061f5ef6ce0)
![image](https://github.com/google/site-kit-wp/assets/73545194/30bc3663-5a9c-4cb7-8b7c-9c84454f41bb)
![image](https://github.com/google/site-kit-wp/assets/73545194/ba261509-1ad6-404c-9512-46895fbb7048)
![image](https://github.com/google/site-kit-wp/assets/73545194/978f6aa4-44e6-473e-8e91-ab376d10d9b2)
![image](https://github.com/google/site-kit-wp/assets/73545194/a42efb02-d565-4b86-b88f-c44fce15db95)
![image](https://github.com/google/site-kit-wp/assets/73545194/f6d9c1ea-e03e-42c7-b676-995991c2ae4a)
![image](https://github.com/google/site-kit-wp/assets/73545194/974cd29a-bca8-4f88-8179-6e3ac865fb72)
![image](https://github.com/google/site-kit-wp/assets/73545194/22af41d4-faec-4617-8081-c5274c0790e6)

</details>
