### ISSUE TITLE
Create single source of truth for Key Metrics titles, descriptions and tooltips

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7726]
## Bug Description

The `Returning visitors` Key Metrics tile is still named `Loyal visitors` within the Metrics Selection panel.

## Steps to reproduce

1. Enable and display the Key metrics widget and select the `Loyal visitors` tile from the Metrics selection panel.
2. The tile is correctly displayed as `Returning visitors` in the widget but the title in the Metrics selection panel should match this as well.

## Screenshots

![Anomaly](https://github.com/google/site-kit-wp/assets/1721319/d629deab-5de9-437b-9c2f-dcf29ed892ad)

## Additional Context

Slack discussion: https://10up.slack.com/archives/C01CA828ZPZ/p1696606229758509

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All titles, descriptions and tooltip text content should be defined in a single file, viz. `assets/js/components/KeyMetrics/key-metrics-widgets.js`.
* Titles of Key Metric widget tiles should exactly match those in the Metrics Selection panel.
* Descriptions and tooltip content for tiles, even though similar, should be defined individually in the above file as these can continue to differ in the future.
* The `Loyal visitors` title in the Metrics selection panel should be renamed to `Returning visitors`.

## Implementation Brief

* In the `key-metrics-widgets.js` file mentioned in the AC:
    * Rename `Loyal visitors` to `Returning visitors`.
    * Go through every key metric widget tile component in the plugin and move the content of the `infoTooltip` prop into a new `infoTooltip ` property within each object in the `KEY_METRICS_WIDGET` array.
* In each of the Key Metric Tile component files, remove the `title` and `infoTooltip` props passed to either `<MetricTileNumeric>`, `<MetricTileTable>` or `<MetricTileText>`. Instead, pass the `widgetSlug` prop importing the correct constant from `assets/js/googlesitekit/datastore/user/constants.js`. This will allow the `<MetricTileWrapper>` that is eventually used by all of the three tile components to set a default `title` and `tooltip` based on the definitions within `key-metrics-widgets.js`.

### Test Coverage

* No new tests required.

## QA Brief

* Set up Site Kit with Key Metrics.
* Confirm that the title previously known as "Loyal visitors" has been correctly renamed to "Returning visitors".
* Open the Metrics Selection panel.
* Compare each title in the panel with the titles on the widget tiles on the dashboard.
* Ensure that every title on the widget tiles matches exactly with those in the Metrics Selection panel.
* As part of this update, the widget slug for "Returning visitors" has been transitioned to `kmAnalyticsReturningVisitors`. We should reset Site Kit to ensure the previous widget slug `kmAnalyticsLoyalVisitors` is purged from the database, paving the way for the new slug to be stored effectively.
* Ensure no regressions have been introduced due to the slug change.

## Changelog entry

* N/A

**Comment by nfmohit** [comment]
Hi @jimmymadon 👋 

I understand this is still in the ACR stage, but I took a look at the proposed IB and I would like to request an amendment/update.

Recently with #7601, we introduced `MetricTileWrapper`, that accepts `title` and `infoTooltip` props. If these props are not supplied, this component is wired to use the `title` from `KEY_METRICS_WIDGETS`, and for the tooltip, it falls back to `infoTooltip` and if that's not present, `description` from `KEY_METRICS_WIDGETS`. See:

https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/assets/js/components/KeyMetrics/MetricTileWrapper.js#L42-L52

Could this IB be updated to add `infoTooltip` instead of `tooltip` in `KEY_METRICS_WIDGETS`, OR, update `MetricTileWrapper` to refer to `tooltip` instead of `infoTooltip`?

Thanks!

**Comment by bethanylang** [comment]
Thanks @jimmymadon! Earmarking this one for Sprint 114 to be done alongside the launch blockers.

I think we need to hold on #7727 for now since that one will require Mariya's input.

**Comment by tofumatt** [comment]
IB ✅

**Comment by hussain-t** [comment]
@aaemnnosttv, as we're updating the title from "Loyal Visitors" to "Returning Visitors", I'm contemplating renaming the `kmAnalyticsLoyalVisitors` widget slug to `kmAnalyticsReturningVisitors` to maintain consistency in our codebase. 

However, a caveat is that if we make this change, we'll need to reset Site Kit on our existing test sites to get the new widget to display correctly. This might cause some inconvenience. Also, we'd need to update the design doc accordingly.

Could you provide your thoughts on this? cc: @nfmohit @jimmymadon

**Comment by aaemnnosttv** [comment]
@hussain-t makes sense to me. Better to change it now then post-launch 👍 Thanks

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Confirmed that the title previously known as `Loyal visitors` has been correctly renamed to `Returning visitors`.
- Compared each title in the panel with the titles on the widget tiles on the dashboard.
- Every title on the widget tiles matches exactly with those in the Metrics Selection panel.
- The widget slug for `Returning visitors` has been transitioned to `kmAnalyticsReturningVisitors`. 
- Went through all the tiles and ensured that the slugs were correct based on spreadsheet. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/f6ef90bb-da56-4f5b-9cab-3bfb1af6e9f9)
![image](https://github.com/google/site-kit-wp/assets/73545194/fd2b8a18-42a8-4b0a-8b9f-2ba2918cb6a4)
![image](https://github.com/google/site-kit-wp/assets/73545194/86260e4f-1ea2-4d5b-a356-4b76dce81977)
![image](https://github.com/google/site-kit-wp/assets/73545194/a8a1b81a-cfa4-4b81-8153-892116471889)
![image](https://github.com/google/site-kit-wp/assets/73545194/16126510-df6e-4ad9-9551-132e41e77445)
![image](https://github.com/google/site-kit-wp/assets/73545194/9b9e9dcd-6b5a-48a6-9f34-1e221e775a27)
![image](https://github.com/google/site-kit-wp/assets/73545194/85258f6f-3610-44a6-9f5a-fc72e42146f9)
![image](https://github.com/google/site-kit-wp/assets/73545194/1fc6d550-099d-42b9-a479-c215c9449926)
![image](https://github.com/google/site-kit-wp/assets/73545194/5020fbb7-47c5-418c-9455-1a3e83a6524a)

</details>
