### ISSUE TITLE
Top content and audience widget not working - trying to load data from old GA and not GA4

### ISSUE THREAD

**Issue by Shwele** [google/site-kit-wp#7731]
## Bug Description

Accessing dashboard results in no top content in last 28 days.

## Steps to reproduce

1. Go to 'Site kit'
2. Click on 'Dashboard'
3. Scroll down to 'Top content over the last 28 days'
4. See no data because it is connected to old GA and not GA4

## Screenshots
[https://imgur.com/a/mlgoXOY](https://imgur.com/a/mlgoXOY)

## Additional Context

 - PHP Version: 7.4.33
 - OS: Ubuntu 20.04
 - Browser: Firefox/Chrome
 - Plugin Version: 1.111.1
 - Device: PC laptop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
@Shwele Thanks for getting in touch. We don't provide support via GitHub but we'd be happy to assist you with this further if you could [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) with us. 

Please could you include all information you have shared here along with Your [Site Health information](https://i.imgur.com/Rtkmsba.png). You can[ use this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) to share privately if preferred.

See you in the forum!
