### ISSUE TITLE
Pushing to feature branch does not build zips

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7732]
## Bug Description

Pushing to a new feature branch should cause zip files to be (re)built automatically, just like we do for `main` and `develop`, however this is not working currently.

https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/.github/workflows/zips.yml#L3-L9

## Steps to reproduce

1. Create a new branch prefixed with `feature/` from `develop`
2. See plugin zip files are not generated for the branch

## Additional Context

It could be related to a flaw in the `if` condition. See https://github.com/google/site-kit-wp/commit/4cd72649c3597c19351476e71dda0f3428417f95 which was never merged back

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Pushing to a `feature/**` or `release/**` branch should trigger the plugin zips job to run

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
Just checked this issue and looks like everything works as expected. I do see build zips are created and uploaded to GCS for a `feature/**` branch: https://github.com/google/site-kit-wp/actions/runs/7210831000

Links to zip files: 
- https://storage.googleapis.com/site-kit-github-artifacts/builds/refs/heads/feature/test-build-zips/google-site-kit-dev.zip
- https://storage.googleapis.com/site-kit-github-artifacts/builds/refs/heads/feature/test-build-zips/google-site-kit.zip

Closing this ticket as there is nothing to fix.
