### ISSUE TITLE
GA4 property requested on every dashboard view

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7734]
## Feature Description

The dashboard is currently requesting the GA4 property on every page load via the `getProperty` selector, only to get the `createTime` of the property (a value that will never change). This is wasteful and there is plenty of room for improvement.

As mentioned, this is currently done to populate the marker on the `UserCountGraph` component of the GA4 All Traffic widget.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `createTime` of the connected GA4 property should be persisted in the `analytics-4` module settings as `propertyCreateTime` as it is returned from the GA API
	* It should be set automatically whenever the connected property is set/changed
	* If a property is already connected and the `createTime` is not set yet, the value should be queried and stored on-demand in the background (this should only need to happen for existing connections)
	* The value should be saved as a UNIX timestamp in milliseconds (`ms`) rather than the ISO time string format returned from the API, [see discussion below](https://github.com/google/site-kit-wp/issues/7734#issuecomment-1775964180)
* The current usage of `createTime` via `getProperty` should be updated to use the new value via settings instead

#### New class `Synchronize_Property`
* Add new class `includes/Modules/Analytics_4/Synchronize_Property`
  * define variable `analytics_4` which will hold the instance of `Analytics_4`, and set it in `constructor`
  * Add new const, say `CRON_SYNCHRONIZE_PROPERTY` following the example like the one for [profile cron](https://github.com/google/site-kit-wp/blob/f37f704c0c39a48984ae274c9df27d73ce8f98a9/includes/Core/Authentication/Clients/OAuth_Client.php#L43)
  * Create new method `schedule_synchronize_property`
    * Obtain the settings, like `$this->analytics_4->get_settings()->get()` and check for following in order to schedule cron:
      * If `propertyCreateTime` setting has no value or is not set
      * If `GA4` is connected eg `$this->analytics_4->is_connected()` and
      * If `CRON_SYNCHRONIZE_PROPERTY` cron is not already scheduled (you can use `! wp_next_scheduled`)
    * If conditions are met, schedule single event so this can be updated in the background
      * Use `wp_schedule_single_event`, you can see example [here](https://github.com/google/site-kit-wp/blob/f37f704c0c39a48984ae274c9df27d73ce8f98a9/includes/Core/Authentication/Clients/OAuth_Client.php#L558-L562)
      * For timestamp, you can use `time()`
      * For hook, use  `CRON_SYNCHRONIZE_PROPERTY`
      * No arguments are needed
  * Add new method - `register`
      * Hook into `CRON_SYNCHRONIZE_PROPERTY` with inline function:
        * switch the user context (in `analytics_4` instance) to the module owner, and check if owner is authenticated (access the instance from `$this->analytics_4->authentication`), you can follow this example [here](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/includes/Core/Authentication/Authentication.php#L648-L650)
          * For `user_id` you can get the owner id with `$this->analytics_4->get_owner_id()`
        * If user is authenticated 
          * Get `$settings` like before, and assign the `propertyID` value from the settings to the new variable
          * Obtain `property` object with `get_data` method of `Anlytics_4` instance, eq `$this->analytics_4->get_data( 'GET:property', array( 'propertyID' => $settings['propertyID'] ) )`. And assign it to `$property` variable
          * Return early in case of error
          * Retrieve the creation time, using `$property->getCreateTime()`
          * Update the `propertyCreateTime` setting with obtained value, e.g `$this->analytics_4->get_settings()->merge( array( 'propertyCreateTime' => $property->getCreateTime() ) )` 
        * Switch the [user](https://github.com/google/site-kit-wp/blob/1cdec41919ad3ba76a3a04c42d8cd98c7fb7e50c/includes/Core/Authentication/Authentication.php#L654) context back

#### `Analytics_4` updates
* In `includes/Modules/Analytics_4/Settings.php`
  * Extend the `get_default` method to include a new setting named `propertyCreateTime`
* In `includes/Modules/Analytics_4.php`
  * In the `pre_update_option_googlesitekit_analytics-4_settings` filter, whenever the property changes, reset the option. This can be extended in the current approach found [here](https://github.com/google/site-kit-wp/blob/9bdabbcc1b9c305597c2edf2189a000e5fa20026/includes/Modules/Analytics_4.php#L182-L184) if feature flag is removed at the time of execution, otherwise, mimic the approach above that block, without any feature flag
  * In `handle_provisioning_callback` method
    * Update [current array](https://github.com/google/site-kit-wp/blob/6670e1fe79a1cc4392e7a2b7f1ff65298fdb43a4/includes/Modules/Analytics_4.php#L574) where id is added to include `propertyCreateTime`, you can obtain value with `$property->createTime`
  *  In `register` metod
     * Instantiate `Synchronize_Property` class
     * Hook into `init` and invoke `schedule_synchronize_property` method of `Synchronize_Property` instance

### Data Store Changes
* In `assets/js/modules/analytics-4/datastore/base.js`
  * Integrate `propertyCreateTime` into the `settingSlugs` settings list
* In `assets/js/modules/analytics-4/datastore/settings.js` within the `submitChanges` function:
  * Under the `PROPERTY_CREATE` [check](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/analytics-4/datastore/settings.js#L65)
    * After property has been created, 
      * Check if `property.createTime` has value, and in that case use the `setPropertyCreateTime` dispatch on the `MODULES_ANALYTICS_4` store and pass in the `property.createTime` value
  * After this block, add another conditional check to verify if `propertyID` has a value, not `undefined`
    * If `propertyID` has a value, use the `getProperty( propertyID )` selector on the `MODULES_ANALYTICS_4` store to retrieve the related property.
    * Then like in the previous step, obtain the `property.createTime` value and apply it to the `setPropertyCreateTime`
* In `assets/js/modules/analytics-4/datastore/properties.js`
  * Under the `selectProperty` [action](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/analytics-4/datastore/properties.js#L207)
    * Like previous steps, obtain the `property` object and apply it's `createTime` property value
  * Add new resolver (under `baseResolvers`) named `getPropertyCreateTime`
    * Check if the `getPropertyCreateTime` selector has a value, and not `undefined`
      * If it has a value, return it but converted to UNIX timestamp in ms (e.g. `new Date(propertyCreateTime).getTime()`)
      * If it doesn't, and `propertyID` exists in the state:
        * Dispatch the `getProperty` action to retrieve the property object.
        * Obtain the `property.createTime` value.
        * Convert the obtained value to a UNIX timestamp in milliseconds like earlier when there is a value, and then use it.
* If `property.createTime` has no value, pass `undefined` to the `setPropertyCreateTime`

### Replace current way of obtaining `createTime` with `getPropertyCreateTime`
* In `assets/js/modules/analytics-4/datastore/report.js` replace [the snippet](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/analytics-4/datastore/report.js#L201-L214) with new `getPropertyCreateTime` selector
* In `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js` replace [this snippet](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js#L101-L117), note that [`inView`](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js#L102-L104) check should be kept
* In `assets/js/modules/analytics-4/datastore/custom-dimensions-gathering-data.js`, replace [this snippet](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/analytics-4/datastore/custom-dimensions-gathering-data.js#L159-L165)
* In `assets/js/modules/search-console/components/common/AnalyticsStats.js`, replace [this snippet](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/search-console/components/common/AnalyticsStats.js#L117-L133), but use [this check](https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/search-console/components/common/AnalyticsStats.js#L118-L120), in case #6856 is merged before execution of this task, `isGA4DashboardView` can be excluded
* Search for usage of `createTime`  across the files and if found replace it with `getPropertyCreateTime`

### Test Coverage

* Add js tests for new resolver in `assets/js/modules/analytics-4/datastore/properties.test.js`
* Add js tests for `propertyCreateTime`  in `assets/js/modules/analytics-4/datastore/settings.test.js`
* Add tests for new `Synchronize_Property` class

## QA Brief

* Setup Site Kit, and ensure that all Analytics 4 modules and widgets are working properly. There should be no console log errors (related to the plugin, exception is notifications service error which is known issue), ensure gathering state for analytics and key metrics is still functioning properly. On existing setup, and when Site Kit is reset and setup again.
* Verify property endpoint is not requested on every page load

## Changelog entry

* Update Analytics to avoid frequently requesting connected property on the dashboard.

**Comment by aaemnnosttv** [comment]
@tofumatt @eugene-manuilov @techanvil thoughts on this one, particularly around how the timestamp is stored? We currently store timestamps in a few different formats in different places (sec vs ms) so I'm hesitant to introduce another, but it also makes sense to use what we get from the API. WDYT?

**Comment by techanvil** [comment]
@aaemnnosttv, although we do store timestamps in different formats, I _think_ that when it comes to the format we're using in the WP options/usermeta tables, it's basically UNIX timestamps but some are in seconds and some milliseconds. So, I'd be inclined to stick with a UNIX timestamp for the property creation time, rather than add the ISO string format into the mix. This of course is accurate to the millisecond so a UNIX timestamp in ms seems appropriate to me.

Something else I'd suggest is that we include the property ID in the option key or value as a sanity check, to help avoid potentially getting out of sync in case something goes wrong. We should still clean up the old value when the property changes of course.

**Comment by tofumatt** [comment]
Agreed, I think storing as a MS timestamp is best here. We could maybe audit our usage in the plugin and do an update migration in a future version to make them consistent (`ms` seems best as its the most precise), but for now let's use `ms`. I've added that to the ACs and will move this to IB 👍🏻

**Comment by eugene-manuilov** [comment]
@tofumatt, UNIX timestamp is measured in seconds, not in milliseconds 😄

**Comment by techanvil** [comment]
@eugene-manuilov actually, I was wondering about this and refreshed my understanding - the UNIX time, or Epoch time is the number of seconds since the UNIX Epoch - so this can in fact be represented as a timestamp to any degree of accuracy. See:

https://en.wikipedia.org/wiki/Unix_time

> In modern computing, values are sometimes stored with higher [granularity](https://en.wikipedia.org/wiki/Data_granularity), such as [microseconds](https://en.wikipedia.org/wiki/Microseconds) or [nanoseconds](https://en.wikipedia.org/wiki/Nanoseconds).

https://www.unixtimestamp.com/

**Comment by aaemnnosttv** [comment]
Thanks @zutigrm! A few points to revise but overall looking good 👍 

> * Extend `get_owned_keys` method array to include `propertyCreateTime` key

This shouldn't be an owned key because when such settings change it will update the module owner to the current user. Since this setting won't exist for all current connected properties, we'd have to limit the setting of this to be only by the module owner, which diminishes it's usefulness. Owned keys are generally those that define the connected entity like the account or property ID. This one is simply a cached value about the connected entity so it's fine if a non-module owner updates it.

> * In `includes/Modules/Analytics_4.php`

We also need to make sure this is set when creating a new account since this also creates a new property + datastream. See `handle_provisioning_callback`

> * Convert the obtained value to a UNIX timestamp in milliseconds like in previous steps and then use it.

We should be explicit about setting this in state since it could be used for other things in the resolver.

---

The only thing which I think which is missing here is defining how the new setting will be set in the database if it isn't currently set (i.e. populating and persisting the value for existing connections) which we want to happen in the background. This could be done with a once-off WP scheduled event and we do something similar for profile data (see `Authentication::cron_refresh_profile_data`), where we could use the module owner as the user ID, so that wouldn't need to be baked into the args for the event.

**Comment by zutigrm** [comment]
@aaemnnosttv Thanks for the valuable feedback. I updated the IB.

> - Convert the obtained value to a UNIX timestamp in milliseconds like in previous steps and then use it.
>
> We should be explicit about setting this in state since it could be used for other things in the resolver.

I updated this to be handled in a more centralised manner. Mainly the value will only be converted to timestamp within resolver, and it will be updated/set in raw value.

> The only thing which I think which is missing here is defining how the new setting will be set in the database if it isn't currently set (i.e. populating and persisting the value for existing connections) which we want to happen in the background. This could be done with a once-off WP scheduled event and we do something similar for profile data (see Authentication::cron_refresh_profile_data), where we could use the module owner as the user ID, so that wouldn't need to be baked into the args for the event.

Thanks for pointing this out. Since in this case setting is saved/retrieved in `Option`, and not in `User_Option`, I didn't include user_id context switch. 
Also, I was checking at which point to spawn event, I think it will be useful on load/init hook, which would check if value is present, and add event to be executed in the background if it doesn't. Alternatively, in `GET:report`, or in both places. So I included that suggestion. Let me know what you think

**Comment by aaemnnosttv** [comment]
Thanks @zutigrm – just a few last points to refine, then this should be good to go 👍 

> * Obtain `property` object [from service](https://github.com/google/site-kit-wp/blob/f37f704c0c39a48984ae274c9df27d73ce8f98a9/includes/Modules/Analytics_4.php#L741), use `propertyID` from the settings as argument. And assign it to `$property` variable

We should use `get_data` to call `GET:property` as we do in a number of places rather than using the service directly. This ensures any errors are handled safely and keeps our usage consistent.

> * Call `refresh_property_create_time` after the hooks/or hook into `init` and call it from there, so it can be checked on page load. You can also call this method from `GET:property` [route](https://github.com/google/site-kit-wp/blob/f37f704c0c39a48984ae274c9df27d73ce8f98a9/includes/Modules/Analytics_4.php#L731)

We should schedule this if:

- The event is not already scheduled
- GA4 is connected
- GA4 does not have the `propertyCreateTime` set

In contrast to the profile cron, it does not need to reschedule the event in the event of a failure, as this would happen automatically due to the above. We shouldn't schedule it from `GET:property` as it's not specific to the connected property, but it's a good idea from the point of view of being on-demand and async.

One other thought: it's reasonable to think that we might want to store additional property values like this in the future so it might be a good idea to decouple the synchronization from the `createTime` specifically. Of course we only care about that value right now but as for the task, we could think of it in terms of a property synchronization task. Just an idea.

One more idea is that we should be able to do everything using public methods on the GA4 class, so we could delegate this behavior to a new class to avoid bloating the module. The new class could take the GA4 module instance as a dependency. This kind of thing should help keep the overall size of our classes from growing forever and make things easier to find + test.

**Comment by zutigrm** [comment]
@aaemnnosttv Thank you for the feedback. 

I proposed creating a new class `Synchronize_Property`. It is decoupled in a way, and it accepts `Analytics_4` as dependency. But since its functionality - syncing the analytics 4 property, is closely tied to the analytics, I suggested instantiating it from within the `Analytics_4` class and passing it's instance `$this`, vs for example fully decoupling by calling it from `Plugin` where `Analytics_4` is instantiated, and then checking in active modules and extracting the instance from there.

This way it is not contributing to the growth of the main class, as logic is handled in decoupled class, but still instantiated within `Analytics_4` for better grouping and accessibility. 

P.S When this goes to EB, can you please assign it to me, would love to work on this when it gets the sprint number :)

**Comment by aaemnnosttv** [comment]
LGTM, thanks @zutigrm !

IB ✅

**Comment by aaemnnosttv** [comment]
@zutigrm I see you assigned this back to me, but there are no new changes since my last commit. I think you missed the feedback in my previous review (I posted 2 in the last round). See https://github.com/google/site-kit-wp/pull/7894#pullrequestreview-1758496997

**Comment by zutigrm** [comment]
@aaemnnosttv Oh indeed I didn't see that one. Updated

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Set up Site Kit and ensured all Analytics 4 modules and widgets worked properly. 
- There are no console log errors.
- Gathering state for analytics and key metrics is still functioning properly. 
- On existing setup, and when Site Kit is reset and set up again.
- The property endpoint is not requested on every page load.
- I also tested Dashboard Sharing to ensure an editor and 2nd admin work as expected.
