### ISSUE TITLE
Handle '(not set)' in GA4 report data

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7737]
## Feature Description

As identified by @techanvil in the [comment](https://github.com/google/site-kit-wp/issues/7737#issuecomment-1801643796) below, in the `TopCategoriesWidget`, we are retrieving the `googlesitekit_post_categories` dimension across all events, however it's only [tracked](https://github.com/google/site-kit-wp/blob/3b88ad1d410150d552b5f8f8dbbdeb9a1d1edb06/includes/Modules/Analytics_4.php#L1406-L1427) for individual post page impressions. So, we are presumably reporting `(not set)` for page impressions, non-singular pages, and so forth. 

We already filtering out  `(not set)` and empty records in the `PopularAuthorsWidget`. We should do the same for the `TopCategoriesWidget` since we now understand the cause of `(not set)` in our reports. This understanding was originally [not clear](https://github.com/google/site-kit-wp/issues/7737#issuecomment-1801550091) and hence we were planning to still show (not set) in our reports with a link to some useful documentation.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Filter out `(not set)` records in the `TopCategoriesWidget` key metric tile.

## Implementation Brief

* In `TopCountriesWidget`, create `dimensionFilters` which filter out `(not set)` records. ~This can be a similar regex as the `PopularAuthorsWidget` taking into account that categories are a comma-separated list of IDs.~ This can now be an exact string match with a `notExpression` since we plan to use string slugs and not IDs (digits) for categories.
* Potential dimension filter that would work: 
  ```javascript 
  dimensionFilter: {
    notExpression: {
      filter: {
        fieldName: 'customEvent:googlesitekit_post_categories',
        stringFilter: {
          matchType: 'EXACT',
          value: '(not set)',
        },
      },
    },
  },
  ```

### Test Coverage

* No changes expected

## QA Brief

* Use various analytics accounts which would have `(not set)` records for the Top Categories KMWT. You can use `https://custom-dimensions.instawp.xyz` (using our InstaWP test account) on the current main branch. Then ensure `(not set)` is not a record displayed when you switch to the develop branch on such a site using the tester plugin.

## Changelog entry

* Exclude `(not set)` rows from the "Top categories by pageviews" key metric tile.

**Comment by mohitwp** [comment]
@jimmymadon Top categories widget> Site only have uncategorized default category. 

Top categories widget> showing (not set) under tiles and showing numbers in different row 9 and 1. If site have only 1 category then it should display data for 1 uncategorized category and only in 1 row.

![image](https://github.com/google/site-kit-wp/assets/94359491/7988a3b1-a3ec-450e-885e-d3c04423355f)

**Comment by techanvil** [comment]
Hey @jimmymadon, reviewing the report that we're retrieving in the "Top categories" widget, it's evidently retrieving the `googlesitekit_post_categories` dimension across _all_ events, however it's only [tracked](https://github.com/google/site-kit-wp/blob/3b88ad1d410150d552b5f8f8dbbdeb9a1d1edb06/includes/Modules/Analytics_4.php#L1406-L1427) for individual `post` page impressions. So, we are presumably reporting `(not set)` for `page` impressions, non-singular pages, and so forth.

It would be nice if we tracked some additional custom dimension(s) to indicate that we are on a singular `post`, which we could then filter by, but as things stand I think we should address this by simply filtering out events where `googlesitekit_post_categories` is `(not set)`.

https://github.com/google/site-kit-wp/blob/3b88ad1d410150d552b5f8f8dbbdeb9a1d1edb06/assets/js/modules/analytics-4/components/widgets/TopCategoriesWidget.js#L57-L70

**Comment by eugene-manuilov** [comment]
> * ... since we plan to use string slugs and not IDs (digits) for categories.

@jimmymadon the problem here is that if someone renames the slug of a category then they will loose page views associated with the previous slug. The same problem with multilingual sites that translate [taxonomy slugs](https://wpml.org/faq/translate-taxonomy-slugs-wpml/) into different languages for better SEO - we will track only a portion of page views for those categories. We should not change IDs to slugs for categories. cc @aaemnnosttv 

What we can do to exclude `(not set)` value from the results is to use the same dimension filter that we use for the popular authors widget:

https://github.com/google/site-kit-wp/blob/27ba31b22719b5c0e0a1f9e8bc3bce6bb8d55b32/assets/js/modules/analytics-4/components/widgets/PopularAuthorsWidget.js#L61-L66

**Comment by eugene-manuilov** [comment]
Thanks, @jimmymadon. IB ✔️

**Comment by aaemnnosttv** [comment]
@jimmymadon please add a QAB, thanks 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Confirmed that the `(not set)` records are filtered out in the `TopCategoriesWidget` key metric tile.

I tested this on a few sites with `(not set)` on the tile.  When I switched to develop, it is filtered out. 


https://github.com/google/site-kit-wp/assets/73545194/7622c97e-5280-4907-a892-e8e1b9d2c5ad
