### ISSUE TITLE
Can't log into AdSense account after installing Site Kit

### ISSUE THREAD

**Issue by theeducatedbarfly** [google/site-kit-wp#774]
Managed to install Site Kit with the new 1.0.1 version but when setting up AdSense it finds the account but I am unable to select it. The options are CREATE ADSENSE ACCOUNT, and when trying to do that I am told I already have an AdSense Account. Or Switch Google Account, although I am logged into the correct account. Logging into the correct account again doesn't fix the problem

WordPress on BlueHost

## Steps to reproduce

Go to Site Kit
Click AdSense

![image](https://user-images.githubusercontent.com/57280839/68078252-8d0b7600-fd8f-11e9-9b77-f0d79e3894e2.png)

URL https://www.theeducatedbarfly.com/wp-admin/admin.php?page=googlesitekit-module-adsense&slug=adsense&reAuth=true

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by kadai** [comment]
I am experiencing this same issue.

In my case, I have tried to remove and add the account again. But the problem persist. Console at least does nor show any data that might hint a problem.

**Comment by kadai** [comment]
More information

I was inspecting this issue more deeply and then noticed an increase of 500 errors at my logs.

All of them coming from the next url:
/wp-json/google-site-kit/v1/modules/adsense/data/accounts?_locale=user

When I did checked its response, I got this (removed id's) :
`{"code":403,"message":{"error":{"errors":[{"domain":"usageLimits","reason":"dailyLimitExceeded","message":"Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https:\/\/console.developers.google.com\/apis\/api\/adsense.googleapis.com\/quotas?project=XXXXXXXXXXXX","extendedHelp":"https:\/\/console.developers.google.com\/apis\/api\/adsense.googleapis.com\/quotas?project=XXXXXXXXXXXX"}],"code":403,"message":"Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https:\/\/console.developers.google.com\/apis\/api\/adsense.googleapis.com\/quotas?project=XXXXXXXXXXXX"}},"data":{"status":500}}`

**Comment by antoniomanco** [comment]
The same problem here, I even reset the Google Site Kit after the last update, but I'm still having problems connecting Google Adsense.

**Comment by theeducatedbarfly** [comment]
To confirm, I have tried resetting multiple times but cannot get it to connect.

**Comment by jamesozzie** [comment]
@theeducatedbarfly @kadai Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
