### ISSUE TITLE
Remove Change Metrics link from above Key Metrics Setup CTA

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7740]
## Feature Description

From @wpdarren in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205767360235581/f)):

Not specific to NKMW, but noticed this issue on the CTA setup.

Mohit and I feel we have fixed this before, but the change metrics link is appearing on the key metrics CTA. The user hasn't gone through the survey or selected metric tiles via the panel so it shouldn't appear on the setup CTA.

![image](https://github.com/google/site-kit-wp/assets/12189958/12ee901d-2c7c-475a-ab2e-11f1d5f6c7e8)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Key Metrics `Change metrics` link should not be displayed when the Key Metrics Setup CTA is visible, i.e. it should only be displayed when there are visible metric tiles in the Key Metrics widget area.

## Implementation Brief

- In `assets/js/components/KeyMetrics/ChangeMetricsLink.js`:
  - Update the `renderChangeMetricLink` variable definition so that it returns true if `keyMetrics` is an array **_AND_** its length is greater than zero (currently it is set to OR).

### Test Coverage

- In `assets/js/components/KeyMetrics/ChangeMetricsLink.test.js`:
  - Fix the `should not render if no key metrics are selected` test case to simulate `getKeyMetrics()` returning an empty array. Currently, this selector returns `undefined` in the test case. See [this comment](https://github.com/google/site-kit-wp/issues/7740#issuecomment-1778952122).
    - This can be fixed by passing an unacceptable value to the user input settings for the `purpose` slug, e.g.:
    ```js
    registry
	    .dispatch( 'core/user' )
	    .setUserInputSetting( 'purpose', [ 'test-purpose' ] );

    ```
## QA Brief

* Set up Site Kit with the `keyMetrics` feature flag enabled.
* Ensure the `Change Metrics` link is not displayed when the Key Metrics Setup CTA is visible.
* Set up Key Metrics and ensure the `Change Metrics` link is displayed when the Key Metrics Setup CTA is not visible.

## Changelog entry

* Hide "Change Metrics" when Key Metrics CTA appears on dashboard.

**Comment by nfmohit** [comment]
Note to AC Reviewer: I have also added an IB as I was able to locate the problem. Please send directly to EB if it looks good.

**Comment by kuasha420** [comment]
Hi @nfmohit, the AC :heavy_check_mark: 

The IB looks fine as well, however, as of right now, the `should not render if no key metrics are selected` is not working as expected, as the `keyMetrics` is `undefined` here instead of empty array which would've caught the issue in testing. This is due to the inner workings of `getKeyMetrics` selector. 

Could you invistigate a little bit more on how to properly feed the registry so `getKeyMetrics` returns empty array and the test case is actually functional? 

Cheers!

**Comment by nfmohit** [comment]
Hi @kuasha420.
Thank you for the kind review.

That is actually a very valid point. I've added that in the IB, please let me know if it looks good, thank you!

**Comment by kuasha420** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Change Metrics link is not displayed when the Key Metrics Setup CTA is visible.
- The Change Metrics link is displayed when the Key Metrics Setup CTA is not visible.
- Tested using the user input survey and also selecting my own metrics. 
- Tested on desktop and mobile. 


<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/11be53b6-83ec-4f5f-af5d-c37c5ae85db2)
![image](https://github.com/google/site-kit-wp/assets/73545194/13c95109-22b6-488d-9f63-10cd46e2a3b1)
![image](https://github.com/google/site-kit-wp/assets/73545194/1d0989f8-1412-48c1-8f4c-e2642ada2a8f)

</details>
