### ISSUE TITLE
Flicker when saving custom dimension tiles

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7742]
## Bug Description

From @wpdarren in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205749590868652/f)):

i’ve just noticed that when you select any of the tiles that has custom dimensions, and click on the save/apply selection, I am taken back to the dashboard briefly, the tiles are in loading state, and then oAuth kicks in as expected.  The screencast is on slow 3G so is exaggerated a little but even on fast internet there’s still some time because the button click and oAuth appearing.

https://github.com/google/site-kit-wp/assets/12189958/f2e537c0-497e-4d90-98e8-b5d3fad071d1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- In the Metrics Selection Panel, if the `Save selection`/`Apply changes` CTA is supposed to direct the user to the OAuth flow to grant the necessary scope to create custom dimensions:
  - The selection panel shouldn't close on submit – it should stay open as the user is directed to the OAuth flow.
  - The CTA should be in a spinning state as the user is directed to the OAuth flow.

## Implementation Brief

- In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`:
  - Update the `onSaveClick` function so that:
    - The value of the `KEY_METRICS_SELECTION_PANEL_OPENED_KEY` UI key is only set to `false` after all the custom dimensions creation logic.
    - If the user doesn't have the Analytics edit scope and the `setPermissionScopeError` action is dispatched to redirect them to grant it, return the function early after the dispatch so that the function is not executed any further.
  - The rendered `<SpinnerButton>`'s `isSaving` prop should be `true` if the user is being navigated to the authentication URL.
    - The authentication URL can be determined using the `CORE_USER` `getConnectURL` selector, similar to how it is done in `assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js`.
    - The `CORE_LOCATION` `isNavigating` selector can be used to determine if the user is being navigated.
  - The rendered `<Link>` and `<SpinnerButton>` should both be in a disabled state if the user is being navigated to the authentication URL.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

- Set up Site Kit with Analytics and enable the `keyMetrics` feature flag.
- In the KMW CTA, choose to select your own metrics.
- Select one or more metric tiles that depend on custom dimensions.
- Click on the save action.
- Verify that the metrics selection panel isn't closed after saving and the save action shows a loading state - as you're being redirected to the OAuth flow.

## Changelog entry

* Fixed the flickering issue when the user is saving custom dimension tiles that require redirecting to the OAuth screen.

**Comment by nfmohit** [comment]
@bethanylang Just to confirm, is this intentionally in "Triage" as Evan wasn't able to replicate, or is this supposed to be in AC? Thanks!

**Comment by bethanylang** [comment]
@nfmohit Thanks for catching! This should be in AC; I just hadn't flagged it in the list in Slack since it's not a launch blocker. Feel free to add an AC though and hopefully we can get to it in the next sprint prior to launch.  :)

**Comment by aaemnnosttv** [comment]
@nfmohit AC LGTM, the only tweak I'd make is that the change is specific to when the button is clicked, it could be a bit more clear about that specifically. I'll tweak that now and then send it forward 👍

**Comment by aaemnnosttv** [comment]
AC ✅

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that the metrics selection panel isn't closed after saving and the save action shows a loading state - as you're being redirected to the OAuth flow.

<details>


https://github.com/google/site-kit-wp/assets/94359491/03ed25c1-327d-4e59-8dd1-8af832a4d76c

</details>
