### ISSUE TITLE
Show Guest authors in "Most popular authors by pageviews” key metric widget tile

### ISSUE THREAD

**Issue by yogeshbeniwal** [google/site-kit-wp#7743]
## Feature Description

Further to https://github.com/google/site-kit-wp/issues/7605, scope should be broaden to also cover guest authors created using plugins like [Co Authors Plus](https://github.com/Automattic/Co-Authors-Plus).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
Dear @yogeshbeniwal, thank you for this suggestion. 

Site Kit uses GA4 Custom Dimensions to track author usernames. Having a single field track multiple authors via a comma might not be a good solution for many users as this will consider "Author A" to be completely different from say a combined scenario such as "Author A, Author B". So a lot more thought would have to go into this.

Having discussed this internally, we have decided that supporting authors stored in "non-standard" ways by different plugins is not something that we will be able to prioritise at this moment.

However, if there are more requests for this feature, we may reconsider looking at this again in the future.

c.c. @aaemnnosttv @andreylipattsev
