### ISSUE TITLE
Key Metrics admin settings content flickers when loading on demand

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7747]
## Bug Description

As reported by @aaemnnosttv in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205799691845823/f)):

The admin settings card contents for Key Metrics shows differently when the settings are not accessed immediately on load (i.e. preloaded data is not used). This causes a flicker of different content when the user has not answered the survey yet.

Initial state

![image](https://github.com/google/site-kit-wp/assets/12189958/97e9a0eb-65fa-4e39-a622-0940221c7414)

Loaded

![image](https://github.com/google/site-kit-wp/assets/12189958/918b83c0-f88b-4c47-86f2-56cbd6d24c4e)

When the user has already completed the survey, the same steps show a progress bar while the state is loading

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Key Metrics settings card should remain in a loading state until all of its state is available (it should not be assumed to be available immediately)
	* The loading state should use preview blocks for any loading areas to minimize layout shifts on load

## Implementation Brief

* Edit `assets/js/components/settings/SettingsCardKeyMetrics.js`
   * Define new variable `settings` and get value from `getUserInputSettings` selector on `CORE_USER`. You can take it from [here](https://github.com/google/site-kit-wp/blob/80e2a734a9e5ba44f2f337c6db7a912f2e653842/assets/js/components/user-input/UserInputPreview.js#L60-L62)
   * Define new variable, `loading` which should hold boolean value based on `settings === undefined`
   * Add new prop `loading` to `SettingsKeyMetrics` and `UserInputPreview` components, passing the  `loading` value
   * In this [check](https://github.com/google/site-kit-wp/blob/80e2a734a9e5ba44f2f337c6db7a912f2e653842/assets/js/components/settings/SettingsCardKeyMetrics.js#L78) include *AND* condition for `! loading` 
   * Then bellow include check if `loading` and render 2 `PreviewBlock` components, you can use class, e.q. `googlesitekit-km-input-settings__loading`. 
     * Wrap these components with `Row` and `Cell` with `googlesitekit-user-input__notification` class to mimic the layout 
 * Modify `assets/js/components/settings/SettingsKeyMetrics.js`:
   * Add `loading` prop and conditionally render the [`switch`](https://github.com/google/site-kit-wp/blob/80e2a734a9e5ba44f2f337c6db7a912f2e653842/assets/js/components/settings/SettingsKeyMetrics.js#L69-L77) by checking if `loading`, to render `PreviewBlock` component, otherwise render `Switch`
 * Modify `assets/js/components/user-input/UserInputPreview.js`:
   * Add `loading` to the list of props
   * Conditionally render [this markup](https://github.com/google/site-kit-wp/blob/80e2a734a9e5ba44f2f337c6db7a912f2e653842/assets/js/components/user-input/UserInputPreview.js#L132-L137) based on the `loading` value
     * If it is loading, render `PreviewBlock`
   * Do the same for all `UserInputPreviewGroup` [components](https://github.com/google/site-kit-wp/blob/80e2a734a9e5ba44f2f337c6db7a912f2e653842/assets/js/components/user-input/UserInputPreview.js#L141-L172)
     * Wrapping the loading state around whole component will be less messy then including it in each group individually around title and link markup.
 * In `assets/js/components/user-input/UserInputQuestionnaire.js`
   * Pass the `loading` prop to the [`UserInputPreview
`](https://github.com/google/site-kit-wp/blob/80e2a734a9e5ba44f2f337c6db7a912f2e653842/assets/js/components/user-input/UserInputQuestionnaire.js#L248), with value `false`
 * Adjust the proper height and width for `PreviewBlock` components to match the replaced field when in loading state. Use the `PreviewBlock` class to add margin of `14px` so there is proper spacing between them, replicating the content spacing. 
   * You can use this file to add class and margin `assets/sass/components/settings/_googlesitekit-settings-user-input.scss`
 * Since there are few `UserInputPreviewGroup` components to be wrapped with `PreviewBlock`, I would suggest making new component, say `LoadingWrapper`, which would accept direct props - for `loading`, and `PreviewBlock` props, and component as `children`, and then render either preview block or component.
 
<details><summary>For example</summary>
<p>

```js
export default function LoadingWrapper( { loading, children, ...loaderProps } ) {
    if ( loading ) {
        return <PreviewBlock { ...loaderProps } />;
    }
    return children;
}
```

</p>
</details> 

<details><summary>Then it can be used like this</summary>
<p>

```js
<LoadingWrapper
       loading={loading}
       className=“…”
       width= “…”
       height=“…”
>
     <SomeComponent />
</LoadingWrapper>
```

</p>
</details> 

### Test Coverage

* Update any failing VRT reference images

## QA Brief

- Navigate to the **Settings** page with the **Connected Services** tab highlighted, and then click on the **Admin Settings** tab. This order of events will prevent preloaded data being used and ensure the loading state is shown for longer.
- Verify that the **Key Metrics** area is displayed in its loading state.
- There are three scenarios that should be checked:

1) Key Metrics has not been setup at all.

_Loading:_
![image](https://github.com/google/site-kit-wp/assets/18395600/096198e8-7d8a-4cfe-b554-f5220c6590fd)

_Loaded:_
![image](https://github.com/google/site-kit-wp/assets/18395600/a191f042-d5a7-498c-928b-f04374d67a41)

2) Key Metrics has been setup via the "I’ll pick metrics myself" CTA.  
  Note there _will_ be a layout shift for this scenario, because we don't know if the switch will be present until we've resolved the loading state.

_Loading:_
![image](https://github.com/google/site-kit-wp/assets/18395600/096198e8-7d8a-4cfe-b554-f5220c6590fd)

_Loaded:_
![image](https://github.com/google/site-kit-wp/assets/18395600/c32ab2b8-e53a-40ab-8e62-20463b5a09c9)

3) Key Metrics has been setup by answering the questionnaire.

_Loading:_
![image](https://github.com/google/site-kit-wp/assets/18395600/a14b8006-1dac-4c70-911c-52662c0b01c6)

_Loaded:_
![image](https://github.com/google/site-kit-wp/assets/18395600/47673425-ed6d-4c27-aca4-db6a6fa39f40)

- Exercise these scenarios at various viewport widths. They should generally hold up without the layout shifting, however it should not be expected that we cover absolutely all cases without a shift. For example, when lines start to wrap at narrower viewport widths as below, it's expected there will be a layout shift when resolving the loaded state:

![image](https://github.com/google/site-kit-wp/assets/18395600/122f6f30-90a9-417b-be3a-516647ad368f)

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
The `<LoadingWrapper>` idea is nice, but let's just use props directly for it rather than placing all props into a `loaderProps` prop 🙂

After that should be good-to-go 👍🏻

**Comment by zutigrm** [comment]
@tofumatt Thank you for the feedback, that's a good idea. Updated IB

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
![image](https://github.com/google/site-kit-wp/assets/18395600/096198e8-7d8a-4cfe-b554-f5220c6590fd)

![image](https://github.com/google/site-kit-wp/assets/18395600/a191f042-d5a7-498c-928b-f04374d67a41)

![image](https://github.com/google/site-kit-wp/assets/18395600/c32ab2b8-e53a-40ab-8e62-20463b5a09c9)

![image](https://github.com/google/site-kit-wp/assets/18395600/a14b8006-1dac-4c70-911c-52662c0b01c6)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified all 3 scenarios mentioned under QAB and confirm that flicker is not showing and all Key metrics data loads together.

<details>

1. Key Metrics has not been setup at all.


https://github.com/google/site-kit-wp/assets/94359491/297161a9-6938-423b-a593-aa56540d4845

2. Key Metrics has been setup via the "I’ll pick metrics myself" CTA.


https://github.com/google/site-kit-wp/assets/94359491/b36ee180-a4bb-4e16-99ee-52a6ed2b6591

3. Key Metrics has been setup by answering the questionnaire.


https://github.com/google/site-kit-wp/assets/94359491/f6d1f16e-d968-4d70-9c6a-d50aa90f8185
