### ISSUE TITLE
Update minimum metrics selection notification

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7749]
## Feature Description

As reported by @sigal-teller in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205794052980171/f)):

When selecting less then 1 metric in the metrics panel, the notification should be displayed _instead_ of the selected metrics count, replacing it per [this Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6678%3A86360&mode=design&t=2EcvH4yOJroCY6cI-1). 

Current:
![image](https://github.com/google/site-kit-wp/assets/12189958/c7176ee4-8772-4a3a-a905-695e5553bc13)

New:

![image](https://github.com/google/site-kit-wp/assets/12189958/c13ab968-5b4c-404b-aad8-d2b61686b39e)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When less than 2 metrics tiles are selected, the error message (`Select at least 2 metrics`) should be displayed on the lower left corner of the panel, replacing the selected metrics count. 
    * The font size, color and style should follow the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6678%3A86360&mode=design&t=2EcvH4yOJroCY6cI-1) design. 
* As soon as 2 or more tiles are selected the error should disappear and the selected metrics count should come back. 

## Implementation Brief

In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`:

* Render the metric count `p` tag with the class `googlesitekit-km-selection-panel-footer__metric-count` only if no errors are using the `saveError` variable.
* Move the `ErrorNotice` inside the `div` with the class `googlesitekit-km-selection-panel-footer__content` just below the metric count `p` tag and render it only if there are errors.
* Ensure the design matches the Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6678%3A86360&mode=design&t=2EcvH4yOJroCY6cI-1) design.

### Test Coverage

* In `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js`, add a test case for the error message to be displayed when there are less than 2 metrics selected.
* Fix any existing tests that are failing due to the changes.
* Update VRT images if necessary.

## QA Brief

* Setup Site Kit 
* In key metrics section, open the selection panel
* Select less then 2 metrics - verify the error message is shown like in the second screenshot added in feature description section

## Changelog entry

* When showing the "Select at least 2 metrics" notification on the Key Metrics selection panel, display it in place of the current selection count.

**Comment by aaemnnosttv** [comment]
AC ✅

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When less than 2 metrics tiles are selected, the error message `Select at least 2 metrics` is displayed on the lower left corner of the panel, replacing the selected metrics count. 
- The font size, color and style follow the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6678%3A86360&mode=design&t=2EcvH4yOJroCY6cI-1) design.
- As soon as 2 or more tiles are selected the error disappears and the selected metrics count should come back.
- Made sure that when no metrics were selected the error does not appear and the 0/4 counter appears on screen. 
- I did additional testing on desktop, responsive and mobile viewports to ensure no UX?UI issues occur. 


<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/a3776385-1dd0-47f5-9144-4a9785703458)
![image](https://github.com/google/site-kit-wp/assets/73545194/6363e420-2bac-48b9-a9c6-4add9bdcdced)
![metrics-panel](https://github.com/google/site-kit-wp/assets/73545194/b056578f-f8b9-4472-a1eb-ac6fb6234ea7)

</details>
