### ISSUE TITLE
Buffering All the Time

### ISSUE THREAD

**Issue by zai17** [google/site-kit-wp#775]
Hai, I've installed Site Kit in my wordpress blog for 2-3 days now, but I still can't see my data either through wordpress dashbord or Site Kit Dashboard. It just keeps buffering no matter what, even when I had clear the cache and change the browser. 

Please fix the issue. Greetings from Indonesia.

![buffer-4](https://user-images.githubusercontent.com/57032232/68082138-0b315080-fe54-11e9-8d89-95de35f09f74.png)
![buffer-3](https://user-images.githubusercontent.com/57032232/68082139-0b315080-fe54-11e9-9da1-0a7e81eb5aab.png)
![buffer-2](https://user-images.githubusercontent.com/57032232/68082140-0bc9e700-fe54-11e9-828e-106d21c739e1.png)
![buffer-1](https://user-images.githubusercontent.com/57032232/68082141-0bc9e700-fe54-11e9-9775-c337d88a6bf3.png)

**Comment by jamesozzie** [comment]
@zai17 Thanks for reporting Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
