### ISSUE TITLE
User input questions screens should not auto-scroll on load

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7750]
## Bug Description

As reported by @sigal-teller in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205794052980167/f)):

When the questions screen load they scroll down a little to a fixed position (if not scrolling back up they will remain in the same scrolled position when switching between screen)

https://github.com/google/site-kit-wp/assets/12189958/6ccfcd46-0d9d-41c2-84b8-d837cf34956e

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The legacy behavior to scroll to a specific user input question should be modified as follows:
	* It should no longer scroll on page load
	* It should no longer scroll down – only up, if needed – to the top of the questionnaire as today 

## Implementation Brief

* Remove the code and related state which scrolls to the active question https://github.com/google/site-kit-wp/blob/b56dd65c3721d4124d9774202374ec81334b7e58/assets/js/components/user-input/UserInputQuestionnaire.js#L130-L139

### Test Coverage

* No changes needed or anticipated

## QA Brief

* Setup site kit
* On key metric setup banner, choose `Get tailored metrics`
* Verify that on questionnaire load, there is no scroll. But switching between the steps should still trigger the scrolling to the header

## Changelog entry

* Improve the scrolling behavior of User Input questions.

**Comment by tofumatt** [comment]
IB ✅

**Comment by bethanylang** [comment]
@tofumatt Did you mean to keep this one assigned to yourself in EB? Just checking!

**Comment by tofumatt** [comment]
@bethanylang Nope, looks like I closed the tab before GitHub updated. Unassigned! 🙂

**Comment by aaemnnosttv** [comment]
@kuasha420 @zutigrm I've updated the AC as we've discussed 👍 If we feel the change is going to significantly change the estimate, let's bring it to IB for a quick iteration and update the estimate to be (initial estimate + remaining work to be done).

**Comment by kuasha420** [comment]
Hi, @zutigrm, I''m moving it back to Ex and assigning you, if the change for updated AC seems significant enough to go through IB again, feel free to move it back, otherwise update the PR and I can review it. Cheers!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On the questionnaire load, there is no scroll. 
- When switching between the steps, the scrolling triggers to the header.
- Tested this on various viewports, including desktop, responsive, tablet, and mobile. 

https://github.com/google/site-kit-wp/assets/73545194/04d13f2b-ded4-46d6-aaab-66e2bd0cae63
