### ISSUE TITLE
Tooltip tour UX issue when on zero data state

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7751]
## Bug Description

As reported by @wpdarren:

I noticed this on the view only dashboard but when the change metrics tour loads and you have a zero data banner, the placement of the tour is off.  

![image](https://github.com/google/site-kit-wp/assets/12189958/cb83cd90-61ab-4f7b-a2f2-77ca7fc611e9)

From @aaemnnosttv:

> I think this case is only possible when the site has "zero data" but not gathering (otherwise KMW wouldn't be surfaced to begin with).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The highlighted area of `Personalize your key metrics` tooltip should be displayed correctly when Key Metrics area is pushed down due to a banner notification being displayed, including the reported Zero Data banner notification. 

## Implementation Brief

* No implementation should be needed here, this will be addressed as a general fix in the dependency #7751.

### Test Coverage

* N/A.

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
The AC here is good, but it's worth noting that this is a specific case of the more general issue reported in https://github.com/google/site-kit-wp/issues/5701, so we should implement the general fix in 5701 and then retest this issue.

I've taken a look into 5701, updated it with an AC and IB, and moved it to IBR, as well as making it a dependency of this issue.

**Comment by techanvil** [comment]
Although no implementation is needed, I've added an estimate to account for retesting this issue. Alternatively, we could simply close this one and ensure it's tested as part of the QA for #5701.

**Comment by eugene-manuilov** [comment]
Yes, closing this one in favor of #5701. No need for this ticket.
