### ISSUE TITLE
Update Least engaging pages tile tooltip

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7753]
## Feature Description

As reported by @bethanylang in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205786558404746/f)):

Change the text of the Least engaging pages tile tooltip:

```diff

- Pages with the highest bounce rate (visitors who left without any meaningful engagement with your site)

+ Percentage of visitors that left without engagement with your site
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Key Metrics widgets are enabled, the "Least engaging pages" tile's tooltip should be changed to `Percentage of visitors that left without engagement with your site` (it was previously `Pages with the highest bounce rate (visitors who left without any meaningful engagement with your site)`)
* We should update the language in the description of this tile to match as well, and be a bit easier to read, changing it from `Pages with the highest bounce rate (visitors who left without any meaningful engagement with your site)` to `Pages with the highest percentage of visitors that left without engagement with your site`

## Implementation Brief

* Update the `infoTooltip` prop/tooltip text at https://github.com/google/site-kit-wp/blob/7735ac0b99aa6b9569e61418a173ddd2c42d768a/assets/js/modules/analytics-4/components/widgets/LeastEngagingPagesWidget.js#L228-L231 to `Percentage of visitors that left without engagement with your site`
* Update the `description` attribute at https://github.com/google/site-kit-wp/blob/7735ac0b99aa6b9569e61418a173ddd2c42d768a/assets/js/components/KeyMetrics/key-metrics-widgets.js#L169 to `'Pages with the highest percentage of visitors that left without engagement with your site'`

### Test Coverage

* Update any VRTs/snapshots to match new text; no new tests needed.

## QA Brief

* Enable Key Metrics widgets and go to "Change Metrics" on the Site Kit Dashboard.
* Find "Least engaging pages" and ensure its description text matches the ACs (eg. `Pages with the highest percentage of visitors that left without engagement with your site`)
* Enable the "Least engaging pages" widget and activate its tooltip.
* Ensure the tooltip text is `Percentage of visitors that left without engagement with your site`

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
I noticed this confusing text is also in the description of the widget in the list of widgets, so I've proposed a nearly-identical but slightly more fitting text change for there as well. 🙂

**Comment by techanvil** [comment]
SGTM, IB :white_check_mark: :)

**Comment by techanvil** [comment]
Hmm... Reviewing this has raised a question for me about the copy we're using here.

When viewing "Most engaging pages" and "Least engaging pages" side by side the inconsistency in the tooltip phrasing seems a bit off. Maybe the tooltip for "Least engaging pages" should simply read "Pages with the lowest engagement rate", or we should update the "Most engaging pages" copy as well? They are both very similar looking widgets, both of which display a percentage value so I'd have thought their descriptions should be more closely aligned.

![image](https://github.com/google/site-kit-wp/assets/18395600/8ad41dc8-9944-44c5-8cd4-8937ca8c3af1)

![image](https://github.com/google/site-kit-wp/assets/18395600/90e85247-c36c-4523-b1df-b8acbeb3cbc3)

The same applies to these metrics when viewed in the Selection Panel:

![image](https://github.com/google/site-kit-wp/assets/18395600/64322cd0-8520-4de7-a8a8-74bf562d0447)

@bethanylang, what do you think?

**Comment by bethanylang** [comment]
@techanvil That makes sense to me, but I'm concerned that as we continue to change these tooltips and descriptions, we're getting into territory where they're becoming misaligned as a whole again and we need to do another full pass at them. :|  @aaemnnosttv @nfmohit Curious for your thoughts here.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The"Least engaging pages" metric description text is `Pages with the highest percentage of visitors that left without engagement with your site`
- The tooltip text is `Percentage of visitors that left without engagement with your site`

![image](https://github.com/google/site-kit-wp/assets/73545194/0e696f04-14c8-49b7-b729-00316e8b9032)
![image](https://github.com/google/site-kit-wp/assets/73545194/3888ffd3-ce0c-4f79-a004-34042d38303d)
