### ISSUE TITLE
Prevent custom dimension related side-effects after Analytics is disconnected

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7754]
## Bug Description

As reported by @zutigrm in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205783722571524/f)):

If there were custom dimension metrics previously selected, and then Analytics is disconnected. Going back to dashboard and trying to save metrics selection in selection panel, will behave same way as if these metric tiles were still available and redirect user to grant EDIT scope. Unless user manually de-checks all metric tiles, redirection will happen on each update/selection saving. It might be worthwhile to update state and automatically remove custom dimension tiles from saved one during the Analytics disconnecting action.

https://github.com/google/site-kit-wp/assets/12189958/c362308f-62cb-4867-8eb2-7dc472f63979

From @aaemnnosttv:

> We should probably filter out selected tiles from modules that are no longer connected. It's less practical to go and update saved preferences for each user who has them in response to deactivating Analytics.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Metrics in the selection panel that depend on one or more unconnected modules should have the following additional adaptations:
	* The metric should be disabled unless it is in the set of currently saved key metrics (i.e. it can only be removed or kept as a selected metric, other metrics dependent on such modules cannot be selected)
	* Any side-effects from selecting such metrics should be skipped (as if the metrics were not selected) – this is currently only relevant for GA4 metrics. The effects to skip include navigating to OAuth to grant edit scope, showing the related notice at the bottom, or any other state/behavior related to creating custom dimensions 

## Implementation Brief

- In `assets/js/components/KeyMetrics/MetricsSelectionPanel/MetricItem.js`:
  - Accept a `savedMetrics` array prop.
  - Update the `isMetricDisabled` variable definition so that besides the current conditions, it also returns `true` if the `savedMetrics` array prop does not include the current metric slug **AND** the `disconnectedModules` array prop has a length greater than zero.
- In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Metrics.js`:
  - Pass the `savedMetrics` prop as a prop to the rendered `MetricItem` component.
- In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`:
  - Update the `onSaveClick` callback function so that before doing any side-effect regarding creation of custom dimensions, besides checking the feature flag, it also ensures that the `analytics-4` module is connected.
- In `assets/js/components/DashboardMainApp.js`:
  - Update the `useEffect` that initiates the creation of custom dimensions such that besides the existing conditions, it also ensures that the `analytics-4` module is connected.

### Test Coverage

- In `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js`:
  - Add test case(s) that verify the new disabled condition for metric items.
  - Add test case(s) that verify the behaviour to change the form state value upon clicking on the save action.

## QA Brief

* Set up a site with Analytics connected.
* Set up Key Metrics and choose some metrics that depend on custom dimensions.
* Disconnect Analytics from the site.
* Ensure that in the selection panel:
    * Metrics reliant on Analytics are disabled.
    * Metrics already chosen before disconnection remain checked and selectable.
    * The checkbox for metrics dependent on Analytics cannot be checked unless they were previously selected.
* Upon saving your metric selection:
    * Confirm no unintended behaviors arise connected to the custom dimensions creation. For instance, redirection for OAuth permission or any other behavior tied to custom dimension creation.
    * Ensure that the notice at the base of the selection panel remains visible for metrics that had been selected before.
* Uncheck a few of the previously selected metrics and save the changes.
* Confirm that the unselected metrics, which were once chosen, are now disabled and cannot be re-selected.

## Changelog entry

* Fix bug that caused Key Metrics tiles for disconnected modules to still request OAuth scopes.

**Comment by techanvil** [comment]
Hi @nfmohit, this IB is looking good. I do wonder if we need to add a new `disabled` prop to `MetricItem`, though... Seeing as it's already determining its own `disabled` state, and also considering the fact it's already aware of the `selectedMetrics` state (i.e. it's already making a determination based on the state of other metrics), as well as having the `disconnectedModules` prop available, it might be a bit easier to manage to keep this `disabled` logic entirely encapsulated within `MetricItem` by retrieving `savedMetrics` within the component as well.

What do you think?

**Comment by nfmohit** [comment]
> Hi @nfmohit, this IB is looking good. I do wonder if we need to add a new `disabled` prop to `MetricItem`, though... Seeing as it's already determining its own `disabled` state, and also considering the fact it's already aware of the `selectedMetrics` state (i.e. it's already making a determination based on the state of other metrics), as well as having the `disconnectedModules` prop available, it might be a bit easier to manage to keep this `disabled` logic entirely encapsulated within `MetricItem` by retrieving `savedMetrics` within the component as well.
> 
> What do you think?

That is absolutely valid and I have updated the IB accordingly. Thank you @techanvil !

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified The metric is disabled unless it is in the set of currently saved key metrics (i.e. it can only be removed or kept as a selected metric, other metrics dependent on such modules cannot be selected).
- Verified if Analytics disconnected -

-        Metrics reliant on Analytics are disabled.
-        Metrics already chosen before disconnection remain checked and selectable.
-        The checkbox for metrics dependent on Analytics cannot be checked unless they were previously selected.

- Upon saving your metric selection:

-        Confirmed no unintended behaviors arise connected to the custom dimensions creation. For instance, redirection for OAuth 
          permission or any other behavior tied to custom dimension creation.
-        Ensured that the notice at the base of the selection panel remains visible for metrics that had been selected before.


Verified OAuth Functionality.
Verified custom dimension setup.


<details>


https://github.com/google/site-kit-wp/assets/94359491/9cf28a0e-7973-49a1-b289-52e16115727a


https://github.com/google/site-kit-wp/assets/94359491/f5ead5ef-9dca-4773-b069-1bd2fedbb3a4


https://github.com/google/site-kit-wp/assets/94359491/e95dd5f3-6501-44b6-be05-e79036785b69

</details>
