### ISSUE TITLE
Tile loading state should include both tile title and tooltip

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7757]
## Bug Description

As reported by @jimmymadon in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205775064472776/f)):

When the tiles are loading, the tooltips are already visible without any title. And the loading bars appear below. This does look a bit odd / incomplete. It would be better if the titles did show instantly alongside the tooltips or we show a loading bar in place of the title so as to not have the tooltip on its own as the only loaded element.

https://github.com/google/site-kit-wp/assets/1621608/866edf43-b1b4-45d1-beda-63c689bec23d

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tooltip icons for key metric tiles should be visually hidden while the tile is in a loading state (that is, they should still be rendered and occupy space, only not visible)

## Implementation Brief

In `assets/js/components/KeyMetrics/MetricTileHeader.js`:

* Update the `MetricTileHeader` component to accept a new boolean prop named `loading`, which will indicate the loading state of the tile.
* Adjust the rendering of the `InfoTooltip` component based on the `loading` prop:
    * If `loading` is `true`, wrap the `InfoTooltip` inside the `VisuallyHidden` component. This ensures the tooltip remains in the DOM but is visually hidden.
      * See comment below about using `VisuallyHidden`: https://github.com/google/site-kit-wp/issues/7757#issuecomment-1787101131
    * If `loading` is `false`, display the `InfoTooltip` component as is, without the `VisuallyHidden` wrapper.

In `assets/js/components/KeyMetrics/MetricTileWrapper.js`:

* Pass the `loading` prop from the `MetricTileWrapper` component down to the `MetricTileHeader` component.

### Test Coverage

* No additional tests are necessary for this change.
* Ensure to update VRT images if required.

## QA Brief

* Set up Site Kit and Key Metrics.
* Verify that the tooltip icon is not visible while the tile is in a loading state.
* Verify that the tooltip icon is visible once the tile has loaded.

## Changelog entry

* Hide tooltips in Key Metrics widget while data is loading.

**Comment by aaemnnosttv** [comment]
This issue does not appear to be localized to key metrics, but affects the whole dashboard. It's simply more noticeable with the tiles since the tooltips are kind of in the middle of the tiles. Here's a quick screencast showing the broader issue though

https://github.com/google/site-kit-wp/assets/1621608/7e7a1082-d451-450e-865c-5c218741782a

Notice all text in the dashboard navigation, header, modules, – everywhere – is invisible and appears at the same time (around the 3-4 sec mark). This appears to potentially be due to the use of a web font.

**Comment by tofumatt** [comment]
@hussain-t The ACs here mention wanting the tooltip to still occupy space… I assume that's to ensure the tooltip layout is consistent. 🤔 

The IB makes sense to me, but worth noting here to the person implementing this: `VisuallyHidden` is the recommended approach, but make sure it doesn't cause layout issues 😄 

I'll make that change and then move this to the execution backlog 🙂

**Comment by tofumatt** [comment]
IB ✅

**Comment by hussain-t** [comment]
Thanks, @tofumatt. I tested it while working on the IB. It didn't have layout issues but works fine 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The tooltip icon is not visible while the tile is in a loading state.
- The tooltip icon is visible once the tile has loaded.
- Hovered over the tooltip icon to ensure that the text appears. 
- Tested on desktop and small screensizes
- Tested on Safari, Chrome and Firefox. 

![image](https://github.com/google/site-kit-wp/assets/73545194/02274f6e-ba7e-4f97-b4b0-c795d496da8a)
