### ISSUE TITLE
Success notification should not display upon completion of custom dimension setup

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7758]
## Bug Description

As reported by @adamdunnage in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205793333312329/f)):

The 'Congrats on completing setup for Site Kit' message is displaying when granting custom dimensions permissions via the update button on metrics tile.

This is after initially clicking the cancel button when asked to grant additional permissions for metrics requiring custom dimensions. I have also seen this happen when grant permissions flow times out and permissions are granted afterwards. 

You also get this banner message if you click the redo setup button but that may be expected. The issue in this instance is when this happens after clicking the update button on the metrics tile.

https://www.loom.com/share/be0fba2a16f84e2c911b257d6e7589ac

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When completing OAuth successfully after granting the edit scope for creating one or more custom dimensions, the standard _"Congrats on completing setup for Site Kit"_ notification banner should not appear
	* In the future, we'll likely have a dedicated banner for this, but implementing this is out of scope for now

## Implementation Brief

* Edit `assets/js/modules/analytics-4/utils/withCustomDimensions.js`:
  * Define new variable named `redirectURL`. [Re-use this](https://github.com/google/site-kit-wp/blob/73868dca2ffdb31d3525780d96c669bfe8ba28e6/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js#L208-L210) for its assignment
    * Set value `custom_dimensions` for example, or something similar for the notification query arg. Its primary purpose is to ensure that `authentication_success` isn't appended upon returning from OAuth. It should be an arbitrary value to prevent matches with any existing notification in `BannerNotifications`.
    * For clarity, it would be beneficial to note this in an inline comment above the variable
  * Include `redirectURL` as param under `data` in [`setPermissionError`](https://github.com/google/site-kit-wp/blob/73868dca2ffdb31d3525780d96c669bfe8ba28e6/assets/js/modules/analytics-4/utils/withCustomDimensions.js#L237-L248)
  * Also, incorporate it [here](https://github.com/google/site-kit-wp/blob/73868dca2ffdb31d3525780d96c669bfe8ba28e6/assets/js/modules/analytics-4/utils/withCustomDimensions.js#L157) to ensure `isNavigatingToOAuthURL` matches correctly

### Test Coverage

* You can add new jest test, to cover this scenario when included `notification` query arg is present, it should not render banner notification. You can render `BannerNotifications` component for the check. It would be beneficial to also include test case for `notification=ga4_setup` query arg in that test file, as both test cases would use same logic.
* Update `assets/js/modules/analytics-4/utils/withCustomDimensions.test.js`. For example confirm presence of proper `redirectURL` in permission error object. 

## QA Brief

* Setup Site Kit
* Enable `keyMetrics` `ga4Reporting` feature flag
* Setup the key metrics, by choosing the ones that require custom dimensions (should be the website that does not have custom dimensions created or some testing instance where dimensions are deleted from analytics)
* After being redirected back to the dashboard from OAuth, verify that setup completed notification is not showing

## Changelog entry

* Avoid showing the default success notification when returning from the OAuth flow for custom dimension setup.

**Comment by techanvil** [comment]
Hey @zutigrm, thanks for drafting this IB. It's a good bit of discovery, but I would suggest we can take a simpler approach following an existing pattern.

If you take a look at the call to `setPermissionScopeError()` in `ActivationBanner/SetupBanner.js`, you'll see that we specify `notification=ga4_setup` in the redirect URL. Although it's a bit obscure and would benefit from a comment to explain it, this is basically there to ensure that the default `authentication_success` notification is not appended on the way back from the OAuth service. The value `ga4_setup` is arbitrary and simply serves to ensure that `notification` is not matched in `BannerNotifications`. This ensures that the success notification isn't rendered in place of the `ActivationBanner` upon returning from OAuth.

https://github.com/google/site-kit-wp/blob/73868dca2ffdb31d3525780d96c669bfe8ba28e6/assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js#L208-L224

So, we can essentially do the same thing here - choose some arbitrary value for `notification` and append it to the current URL, setting the value as `redirectURL` in the call to `setPermissionScopeError()` in `withCustomDimensions()`:

https://github.com/google/site-kit-wp/blob/73868dca2ffdb31d3525780d96c669bfe8ba28e6/assets/js/modules/analytics-4/utils/withCustomDimensions.js#L237-L248

**Comment by zutigrm** [comment]
@techanvil Thank you very much for that suggestion, didn't know about that trick. I update the IB

**Comment by techanvil** [comment]
Thanks @zutigrm! The main body of the IB is LGTM, but the Test Coverage section could also do with an update.

**Comment by zutigrm** [comment]
@techanvil Oh yes, sorry about that. Updated

**Comment by techanvil** [comment]
Thanks @zutigrm!

Sorry for not raising this in the last round, but on reflection, I think we should avoid re-using the `ga4_setup` value and choose a new one instead. The existing usage of it and this new case are different scenarios and I think it could be a little confusing reusing `ga4_setup`, as a search across the codebase for it might suggest a relationship that isn't there.

With regard to the Test Coverage, it's probably worth mentioning `BannerNotifications` because it's not explicitly mentioned elsewhere in the IB. I must admit, the thought of adding these tests feels a little bit odd because there are none yet for this component and we'd be adding some test coverage for values which aren't actually referenced in the component at all. However, it would add an element of self-documentation to the code and provide an initial set of tests which we could further expand as time goes on. So, on balance that SGTM.

It might be worth also speccing a bit of test coverage for the changes to `withCustomDimensions()`, this does already have a test file which we could add to...

**Comment by zutigrm** [comment]
@techanvil Thanks for the suggestions.

> I think we should avoid re-using the ga4_setup value and choose a new one instead. The existing usage of it and this new case are different scenarios and I think it could be a little confusing reusing ga4_setup, as a search across the codebase for it might suggest a relationship that isn't there.

That make sense.

> With regard to the Test Coverage, it's probably worth mentioning BannerNotifications

I included it for clarity in both IB and Test Coverage

> It might be worth also speccing a bit of test coverage for the changes to withCustomDimensions(), this does already have a test file which we could add to

Good point

**Comment by techanvil** [comment]
Nice one @zutigrm, that LGTM. IB :white_check_mark:

**Comment by nfmohit** [comment]
Hi @zutigrm.

I was just looking into the code for this, and I think this tweak should also be implemented to the logic where the redirect to  OAuth happens from the Metrics Selection Panel. See:

https://github.com/google/site-kit-wp/blob/ddbc12a5f33a76d6feaae8451d72a91d958e89ac/assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js#L156-L168

Let me know what you think, thanks!

CC: @techanvil

**Comment by techanvil** [comment]
Good catch there @nfmohit. @zutigrm, would you mind creating a followup PR with the addition to `MetricsSelectionPanel/Footer` that Nahid has described?

I'll move this back to Execution in the meantime, cc @wpdarren.

**Comment by zutigrm** [comment]
@nfmohit Thanks for spotting that. I will create a follow up PR.

cc: @techanvil @wpdarren

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- After being redirected back to the dashboard from OAuth, the setup completed notification is not showing.

![image](https://github.com/google/site-kit-wp/assets/73545194/64d16737-6bbf-487c-b17d-c751d1b92295)
