### ISSUE TITLE
Google My Business Integration

### ISSUE THREAD

**Issue by Josimarcsilva** [google/site-kit-wp#776]
## Feature Description

An integration with Google My Business to make and track publications. When you post to WordPress this post would also be published automatically to Google My Business.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
This feature request is already captured in issue #20. We'll keep that issue to track progress if/when we add GMB integration.
