### ISSUE TITLE
Update user input survey language

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7766]
## Feature Description

As reported by @jimmymadon in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205772786573835/f)):

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The language on the user input survey for site-wide questions should be updated as follows:  
    ``` diff
    - Your answers will apply to the entire WordPress site: any other admins with access to Site Kit can see them and edit them.
    + Your answer to this question will apply to all Site Kit users. Any other admins with access to Site Kit can see and edit this response.
    ```

## Implementation Brief

* Update this line to match the AC https://github.com/google/site-kit-wp/blob/9054bd58aead576ebf25b1863260753277528b59/assets/js/components/user-input/UserInputQuestionInfo.js#L100

### Test Coverage

* Update any affected VRT reference images if necessary

## QA Brief

- Set up Site Kit with an Analytics property that is not in a gathering data state (e.g. oi.ie).
- In the appearing KMW CTA, choose to get tailored metrics.
- In the first question (purpose), verify that the sub-text matches the change proposed in the ACs.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
cc: @marrrmarrr as a language change

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The sub-text matches the change proposed in the ACs. `Your answer to this question will apply to all Site Kit users. Any other admins with access to Site Kit can see and edit this response.`
- Checked that the sub-text only appears when the site has more than one admin user, and does not appear when the site only has one admin user. 

![image](https://github.com/google/site-kit-wp/assets/73545194/e00900ba-6d55-40ed-b023-46de87dbd927)


**QA note:** It doesn't mention this in the QAB, but you need to have a second admin user for the message to appear on the user input survey question.
