### ISSUE TITLE
Re-organize the metrics selection panel

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7767]
## Feature Description

As discussed in the News Key Metrics Tiles Bug Bash, we should review the tiles in the metrics selection panel and see if we can group them in some useful way. cc @sigal-teller @marrrmarrr 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Metrics Selection Panel list re-ordering
* In the metrics selection panel, if there are any metrics that are in the currently saved selection, they should now be under a new heading: "Current selection" and all the other metrics should be under "Additional metrics". This should be designed as per the new [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7341-62149&mode=design&t=mRd2hOtzTb1RlmWB-4).
* All the other metrics will be displayed in the order defined in the Key Metrics [master spreadsheet](https://docs.google.com/spreadsheets/d/1bXTc1rZHZEvXZ2jp-30ylHTqpzntEh9fLGc4IiOZCWM/edit#gid=0). 
    * Metric tiles with Custom dimensions will always be displayed first. This will include the Most popular products tile now too. See [comment](https://github.com/google/site-kit-wp/issues/7767#issuecomment-1825779732) below.
    * Then the other News Key Metric tiles.
    * Finally the original Key Metric tiles.
    * The "Top performing keywords" tile is moved to the bottom now as the only search console reliant tile. This is to still keep all analytics reliant tiles together.

### Key Metric Widget tiles re-ordering
* Metrics being displayed in the Key Metrics widget area should follow the same order defined in the [master spreadsheet](https://docs.google.com/spreadsheets/d/1bXTc1rZHZEvXZ2jp-30ylHTqpzntEh9fLGc4IiOZCWM/edit#gid=0) above.

### Metrics Selection Panel Design improvements
* The metrics selection panel should be redesigned as per the new [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7341-62149&mode=design&t=mRd2hOtzTb1RlmWB-4).
    * Remove metrics frames and add dividers instead.
    * Change the amount selected text to “X selected (up to 4)” instead of “4 of 4 selected” which makes it clearer that 4 metrics aren't mandatory.
* Modify the selection / saving of metrics as follows:
    * If more than 4 metrics are selected (max amount), then all metrics should not be "disabled" (as is the case now). Only the "Save selection" button should disabled. Once the user selects 4 or less than 4 metrics, the "Save selection" button should be re-enabled. This allows user to select more metrics and deselect others "later" in their journey.

### Re-ordering the metrics selection panel and kmw tiles in the widget area

* In `assets/js/components/KeyMetrics/key-metrics-widgets.js`:
  * Order the elements within the KEY_METRICS_WIDGETS object to be as per the AC.
* In `assets/js/modules/analytics-4/index.js`:
  * Register the Key Metric widgets in the same order that is set above.
* In `assets/js/modules/search-console/index.js`:
  * Modify the priority of the `Top performing keywords` widget to 2.

### Metrics panel design improvements

* In `assets/sass/components/key-metrics/_googlesitekit-km-selection-panel.scss`:
  * Modify the styles to cover the design changes.
* In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Metrics.js`:
  * Instead of building a single list of `availableMetrics`, create a separate list of `selectedMetrics` based on the `savedMetrics` prop.
  * `availableMetrics` should now contain all metrics within the `KEY_METRICS_WIDGETS` but with the above `selectedMetrics` filtered out. This list does not have to be sorted anymore.
  * Wrap the logic of a metric being visible (i.e. isKeyMetricAvailable, displayInList and disconnectedModule) into a function that is mapped for every element of both the lists above.
  * If `savedMetrics` is not empty, show two headings as per the AC and each list should be rendered in a loop below their respective headings. Otherwise, render `availableMetrics` without any headings.

* In `assets/js/components/KeyMetrics/MetricsSelectionPanel/MetricItem.js`:
  * Remove logic from `isMetricDisabled` that disables items when `selectedMetrics?.length > 3`.

* In `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`:
  * Update the string for the number of selected metrics.

### Test Coverage

* No new tests required but VRT and JS tests will need to be updated.

## QA Brief

* Test the Key Metrics selection panel when no settings are saved and when settings are saved. Verify the design matches the new Figma mock in the ACs.
* Verify the save behaviour is as per the AC.
* Verify the order of the metrics is as per the AC, both in the actual widget area and in the metrics selection panel.

## Changelog entry

* Re-organize the Key Metrics selection panel.

**Comment by techanvil** [comment]
AC :white_check_mark: 

Note that I made a minor tweak to help clarify that the display order should be based on the currently saved selection.

**Comment by techanvil** [comment]
IB :white_check_mark:
