### ISSUE TITLE
Update Visit length metric tile display

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7768]
## Feature Description

As reported by @zutigrm in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205783722571498/f)):

The Visit length tile display should be updated to match the [Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60022&mode=design&t=fNTHCss6p5xnrP0d-4): 

![image](https://github.com/google/site-kit-wp/assets/12189958/fea5521a-4457-4bb5-9c72-8bf8391609ff)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Visit length` metric tile's duration number should be changed to use a more readable format indicating the number of hours, minutes and seconds with their abbreviated units included, e.g. `1h 10m 20s`.

## Implementation Brief

* Update the `metricValueFormat` to use the `s` shorthand option which is used for formatting durations elsewhere in the format called for in the AC

### Test Coverage

* Update VRT images for affected scenarios

## QA Brief

* Setup Site Kit
* Enable `keyMetrics` and `ga4Reporting` feature flags
* Add `Visit Length` key metric
* Verify that format matches the one from design

## Changelog entry

* Update the "Visit length" Key Metric widget tile to use a more readable format for the duration value.

**Comment by aaemnnosttv** [comment]
@nfmohit I replaced "initials" with "abbreviated units" otherwise all good!

AC ✅

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified on different viewports.
- Verified after adding hour data through dev console.
- Verified The Visit length metric tile's duration number  changed to use a more readable format indicating the number of hours, minutes and seconds with their abbreviated units included, e.g. 1h 10m 20s.
- Verified tile is same as Figma design.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/269daebd-9e94-4809-9b6c-631e1f257ec3)

![image](https://github.com/google/site-kit-wp/assets/94359491/18ef4682-9142-49f7-850e-923d68822a97)

![image](https://github.com/google/site-kit-wp/assets/94359491/0f3fb404-b4a2-4818-a4bd-f133f0eef32f)

</details>
