### ISSUE TITLE
Unknown Error (code: Invalid JSON response) (1.0.1)

### ISSUE THREAD

**Issue by quangbahoa** [google/site-kit-wp#777]
## Bug Description

1. Error after redirect back from Google `Unknown Error (code: Invalid JSON response).`
2. Error on sitekit dashboard
`
googlesitekit-dashboard-splash.js:1
Uncaught TypeError: Cannot read property 'call' of undefined
    at s (googlesitekit-dashboard-splash.js:1)
    at Object.<anonymous> (vendor.js:43)
    at Object.<anonymous> (vendor.js:43)
    at s (googlesitekit-dashboard-splash.js:1)
    at Object.19 (commons.js:1)
    at s (googlesitekit-dashboard-splash.js:1)
    at Object.24 (commons.js:1)
    at s (googlesitekit-dashboard-splash.js:1)
    at Object.23 (commons.js:1)
    at s (googlesitekit-dashboard-splash.js:1)
`

## Additional Context

 - PHP Version: 7.3
 - OS: Ubuntu
 - Browser Chrome
 - Plugin Version 1.0.1
 - Device: Windows 10

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by quangbahoa** [comment]
Update: Error 2.(Error on sitekit dashboard) cause by my theme.

**Comment by felixarntz** [comment]
@quangbahoa Thanks for the report. Does this error persistently occur for you? Or does it only happen sometimes?

**Comment by quangbahoa** [comment]
@felixarntz this happen after upgrade to 1.0.1

**Comment by coolhandluke1234** [comment]
I am getting this as well

**Comment by quangbahoa** [comment]
Fixed this by remove function below:

`
function remove_cssjs_ver( $src ) {
    if ( strpos( $src, '?ver=' ) )
        $src = remove_query_arg( 'ver', $src );
    return $src;
}
add_filter( 'style_loader_src', 'remove_cssjs_ver', 10, 2 );
add_filter( 'script_loader_src', 'remove_cssjs_ver', 10, 2 );
`
@felixarntz Can you double check to make sitekit work when remove query string?

**Comment by jamesozzie** [comment]
@quangbahoa Just following up with you to check whether you the same issue you reported remains?

**Comment by coolhandluke1234** [comment]
Seems to be fixed.

Thanks

Sent from my iPhone

On Jan 29, 2020, at 10:57 AM, James G <notifications@github.com> wrote:

﻿

@quangbahoa<https://github.com/quangbahoa> Just following up with you to check whether you the same issue you reported remains?

**Comment by jamesozzie** [comment]
Thanks for the update @coolhandluke1234 

@quangbahoa If you continue to encounter the same issue feel free to reopen
