### ISSUE TITLE
Update collapse arrows on user input summary

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7771]
## Feature Description

As reported by @sigal-teller in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205794052980177/f)), the Edit arrows in the user input summary (both in the initial setup flow and in Settings) are incorrect:

![image](https://github.com/google/site-kit-wp/assets/12189958/2e22a138-6fa2-43f7-bd22-3606505b282d)

![image](https://github.com/google/site-kit-wp/assets/12189958/57a6d042-95e6-4eb4-8df7-d78544409ee5)

These should be updated to match the [Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-63498&mode=design&t=fNTHCss6p5xnrP0d-4):

![image](https://github.com/google/site-kit-wp/assets/12189958/5b18bf16-dffc-454f-b660-c559a6b8f20a)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user input preview group accordions should use a thin caret icon according to [the Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-63498&mode=design&t=fNTHCss6p5xnrP0d-4) instead of the currently used filled chevron icon.

## Implementation Brief

The problem is due to CSS applied to all `svg` within CTA links which sets the `fill: currentColor`. This is applying the color we want to remove, so setting this to `none` _specifically for these Edit links_ resolves the issue. This seems to be needed in CSS specifically as setting the attribute in the svg is being overridden by CSS.

Don't remove `fill: currentColor` from all links, see @tofumatt's comment below: https://github.com/google/site-kit-wp/issues/7771#issuecomment-1787232934

### Test Coverage

* No additions necessary
* VRT reference images may need updating

## QA Brief

* Ensure the Edit button arrow in the AC has the correct shape (without fill) on hover, focus and click.

## Changelog entry

* Fix bug that caused the "Edit" buttons in Key Metrics Admin Settings to render incorrectly.

**Comment by aaemnnosttv** [comment]
@nfmohit the icon is actually correct, it's a stylistic bug. AC LGTM, I'll add an IB 👍

**Comment by tofumatt** [comment]
To be clear, that `currentColor` is what allows some CTA links with icons to have the icon colour match the text colour, so we shouldn't remove it wholesale. It's odd that this SVG's fill affects that part of the arrow I guess, but we should specifically remove that `fill` only for these edit links 🤔 

I've clarified that in the IB, but seems a fine approach otherwise 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified:

- The user input preview group accordions use a thin caret icon according to [the Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-63498&mode=design&t=fNTHCss6p5xnrP0d-4).
- Tested on desktop and smaller viewports like mobile. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/e0e86bce-82f3-4206-b800-1371fc83d418)
![image](https://github.com/google/site-kit-wp/assets/73545194/47ac7859-c5e3-419a-a9ea-0f8a10bfd0dd)
![image](https://github.com/google/site-kit-wp/assets/73545194/aaaaa196-36c7-46fb-a6eb-2b65f4069802)
![image](https://github.com/google/site-kit-wp/assets/73545194/1027c4b2-402a-4a34-b905-a3c1484d0510)

</details>
