### ISSUE TITLE
First page reload after connecting Analytics causes page to scroll to #traffic instead of #key-metrics

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7775]
## Feature Description

As reported by @jimmymadon in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205772786573844/f)):

1. Reset Site Kit.
2. Set up Site Kit and connect a GA4 account that has data available.
3. This will redirect you to the dashboard with the #traffic section selected in the URL.
4. Refreshing the page now loads the new #key-metrics section, however the page scrolls back down to the #traffic section thus hiding the #key-metrics "Setup Banner CTA".

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
This does still occur. However, I feel this is a very tiny edge case. Secondly, on any subsequent navigation to the dashboard by clicking on any SK dashboard link within wp-admin, the banner will show eventually for key metrics. So I don't think this is worth fixing.

c.c. @aaemnnosttv
