### ISSUE TITLE
how can i fix this error

### ISSUE THREAD

**Issue by amrnaga84** [google/site-kit-wp#778]
this message appear after click on"sign in with google"
Method not allowed
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/57328400/68090528-74798980-fe7d-11e9-9abd-021f824ac379.png">

**Comment by jamesozzie** [comment]
@amrnaga84 Thanks for submitting a request. Site Kit support is provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your question on there, where we would be happy to assist.
