### ISSUE TITLE
Don't show the "Enable enhanced measurement" switch until an account has been selected in the setup flow.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7784]
## Feature Description

As discussed on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1698390004666189): In the setup flow, the "Enable enhanced measurement" switch and description should not appear until an account has been selected from the dropdown.

In other words, when the setup flow is in this state the switch shouldn't appear:

![image](https://github.com/google/site-kit-wp/assets/18395600/e1a8f592-9d01-4d41-8941-8189b98b0574)

This is to avoid the confusing UX as seen here whereby the toggle state changes when returning from the Create Account screen. It will also be consistent with the other controls on the page i.e. the property and data stream dropdowns which only appear when the account is selected.

https://github.com/google/site-kit-wp/assets/18395600/6a3f6566-3843-43b6-8d5f-d6b94412383c

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the setup flow, the "Enable enhanced measurement" switch and description should not appear until an account has been selected from the dropdown.

## Implementation Brief

Within `assets/js/modules/analytics-4/components/setup/SetupEnhancedMeasurementSwitch.js`:

- Check if the account ID is valid and return `null` if so, similar to the logic in `PropertySelect`:
https://github.com/google/site-kit-wp/blob/7e36531c945151f051d44ae37186fa685090ad85/assets/js/modules/analytics-4/components/common/PropertySelect.js#L110-L111

### Test Coverage

* Add a test case covering the above to the tests for `SetupEnhancedMeasurementSwitch`.

## QA Brief

* Go to the Analytics setup process and ensure that you don't see the enhanced measurement switch when the account is not selected yet.

## Changelog entry

* Don't show the "Enable enhanced measurement" switch until an account has been selected in the setup flow.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The enhanced measurement switch does not appear when the account is not selected yet. When the account is selected or a new account selected, the switch appears as expected and is enabled by default. 
- Ran through some additional testing: tested with a site that did not have an Analytics account assigned to the URL and when setting up Site Kit with Analytics, the switch did not appear.  I also tested with a site that does have an account assigned to it and when connecting Analytics, the account was automatically selected and the switch appeared.  
- Also completed some additional testing around the Analytics settings in edit view to ensure it continued to appear. 

https://github.com/google/site-kit-wp/assets/73545194/eabc48b9-c229-429d-ba61-c997d3af7ef0
