### ISSUE TITLE
Remove "Google" prefix from the "Connect GA CTA" banner button

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7787]
## Feature Description

To maintain consistency between the Connect GA CTA Banner and the Individual Connect Module CTA tile, we should remove the prefix "Google" from the "Connect Google Analytics" button on the banner. This is based on this [comment](https://github.com/google/site-kit-wp/issues/7278#issuecomment-1744772315) and @marrrmarrr 's response to it.

![image](https://github.com/google/site-kit-wp/assets/1721319/7e404243-b2bb-464a-8777-ac21f0bca9d9)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Remove the word "Google" from the "Connect Google Analytics" title, description and CTA button in the `ConnectGA4CTAWidget` component.

## Implementation Brief

* In `ConnectGA4BannerCTAWidget`, remove the word "Google" as per the AC.

### Test Coverage

* No new tests required.

## QA Brief

* Ensure all metrics selected depend on GA4. Now disconnect Analytics and verify the word Google is removed from the title, description and CTA button.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs here are good; IB looks good as well 😄 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- All metrics selected depend on GA4. 
- The word Google is removed from the title, description and CTA button.
- Checked accessibility settings to ensure that Google is removed from there too. 
- Tested the Analytics CTA when we have a Search Console metric tile available, just to make sure there are no issues.
- Had a quick check on smaller viewports to ensure no UX issues with the change. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/0d055ed4-0b43-4333-bb89-f2a74679e2ae)
![image](https://github.com/google/site-kit-wp/assets/73545194/457d21f3-4e6f-472e-92ec-0340eefc35d7)
![image](https://github.com/google/site-kit-wp/assets/73545194/eff85e83-23c4-4d25-be7f-e9ea604e9abc)
![image](https://github.com/google/site-kit-wp/assets/73545194/9255d8f3-a2b6-46dc-9a8c-4cc9ce18ab33)

</details>
