### ISSUE TITLE
Remove "CTR" from Most engaging pages tile

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7793]
## Feature Description

As noted by the News team, the "CTR" label should be removed from the Most engaging pages tile as it is not accurate. See [Asana task](https://app.asana.com/0/1205508124049666/1205786559204401/f) for more details.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `CTR` text should be removed from the formatting of the value for rows of the `MostEngagingPagesWidget`

## Implementation Brief

* Remove the use of [`createInterpolateElement` in the table's `Component`](https://github.com/google/site-kit-wp/blob/43fc08fdc0f437652210c6906a4ec4ef9bbef54b/assets/js/modules/analytics-4/components/widgets/MostEngagingPagesWidget.js#L205-L214) for displaying the metric value
* Preserve the `format` used for the percentage number, using `LeastEngagingPagesWidget` as an example

### Test Coverage

* Some VRT reference images will likely need updating

## QA Brief

* Verify that the `CTR` text is no longer displayed in the `Most engaging pages` widget.
* Verify the `CTR` text is no longer displayed in the view-only dashboard.

## Changelog entry

* Remove "CTR" suffic from "Most engaging pages" widget.

**Comment by marrrmarrr** [comment]
This change makes sense and is relatively low effort to make (just removing 2 words), so marking as P0.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The CTR text is no longer displayed in the `Most engaging pages` widget.
- The CTR text is no longer displayed in the `Most engaging pages` widget on the view-only dashboard.
- Checked the tile on smaller viewports to ensure no UX issues. 

![image](https://github.com/google/site-kit-wp/assets/73545194/96e304ec-6c92-4f48-b779-75e99c27278c)
![image](https://github.com/google/site-kit-wp/assets/73545194/3462e446-2617-41d2-8f5a-d1471f8cae18)
