### ISSUE TITLE
Error for report requests with custom dimensions

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7794]
## Bug Description

Sometimes, report requests containing custom dimensions that are made immediately after creating the said custom dimensions fail. While the UI/UX doesn't seem to be affected, it does cause console errors, screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/4807c4cc-6ba3-4465-afe0-8a0ae479362f)

This looks similar to the issue that @aaemnnosttv reported in a [bug bash Asana task comment](https://app.asana.com/0/0/1205784257171326/1205788136098459/f).

Please note that this doesn't happen all the times, but multiple folks have been able to reproduce it.

## Steps to reproduce

1. Set up Site Kit with Analytics.
2. On the Key Metrics setup CTA, choose one or more metric tiles that depend on custom dimensions, e.g. `Top recent trending pages`, `Most popular authors by pageviews`, or `Top categories by pageviews`.
3. Save your selection and let SK return to the dashboard.
4. Verify that the said metric tiles go to a gathering data state but notice the console errors.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A metric tile that depends on custom dimensions should not make its report request immediately after the required custom dimensions are created.
* As soon as the required custom dimensions are created successfully, the gathering data state should be shown immediately (without making a report request).
* The report request should be made as usual starting from the next page load.

## Implementation Brief

* The report is sent right after the creation and syncing of custom dimensions, due to the check for `(not set)` value in `checkCustomDimensionDataAvailability` in gathering data store.
* Modify `assets/js/modules/analytics-4/datastore/custom-dimensions.js`:
  * After custom dimension [is created](https://github.com/google/site-kit-wp/blob/3562521f16a9d331c559185c002a7195286a2a45/assets/js/modules/analytics-4/datastore/custom-dimensions.js#L169-L172)
    * Dispatch `receiveIsCustomDimensionGatheringData` on `MODULES_ANALYTICS_4`, passing the parameters `dimension`, and `true`
      * e.g `.receiveIsCustomDimensionGatheringData( dimension, true )`

### Test Coverage

* Update `assets/js/modules/analytics-4/datastore/custom-dimensions.test.js`, to include check for custom dimension gathering data after dimension is created in `creates a custom dimension for the provided property with valid parameters` test case

## QA Brief

- Set up Site Kit with an Analytics property that doesn't have custom dimensions created.
- Enable the `keyMetrics` feature flag.
- In the KMW CTA, choose to select your own metrics.
- In the Metrics Selection Panel, select one or more tiles that depend on custom dimensions.
- As you return from the OAuth flow, observe the network tab as the custom dimensions are being created.
- Verify that while `POST` requests to `create-custom-dimension` & `sync-custom-dimensions` are made, no `report` requests are made containing the newly created custom dimensions.
- Verify that an error as described with the steps to reproduce in the issue description cannot be reproduced anymore.
- Upon reloading the page, verify that `report` requests are made containing the newly created custom dimensions and they succeed without errors as described in the issue description.

## Changelog entry

* Avoid report errors immediately after creating a custom dimension.

**Comment by aaemnnosttv** [comment]
AC ✅

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- While POST requests to `create-custom-dimension` & `sync-custom-dimensions` are made, no report requests are made containing the newly created custom dimensions.
- An error as described with the steps to reproduce in the issue description cannot be reproduced anymore.
- Upon reloading the page, the report requests are made containing the newly created custom dimensions and they appear without errors as described in the issue description.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/ba477cfa-d7c0-4cd1-8c8b-0777d40cc411)
![image](https://github.com/google/site-kit-wp/assets/73545194/4ea47848-a361-4a90-9f44-93a191e777b1)
![image](https://github.com/google/site-kit-wp/assets/73545194/b8a9a9b0-9f5a-40d6-bcca-31f454b5151a)
![image](https://github.com/google/site-kit-wp/assets/73545194/4f980508-004c-4cb6-b313-b642f6d08003)

</details>
