### ISSUE TITLE
Ensure consistent styling of secondary CTAs across the plugin.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7797]
## Feature Description

As raised by @sigal-teller on [Slack](https://10up.slack.com/archives/C01CA828ZPZ/p1698654652206699), we have some inconsistencies and incorrect styles for our secondary CTAs which need to be addressed prior to updating their focus states in a subsequent issue (focus styling is currently TBD).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- All cases where there are two CTAs next to each other need to be reviewed for inconsistencies or incorrect styles applied to the secondary CTA.
- In all cases, the secondary CTA should be rendered using the `Button` component in its tertiary state, as defined in [Figma](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?type=design&node-id=409%3A2253&mode=design&t=PhT81xcY8IdYEqK8-1).
- It should be ensured the correct colour token `surfaces/on-surface-variant` is used for the text, and there is no underline on hover.

## Implementation Brief

* Edit `assets/sass/components/global/_googlesitekit-entity-header.scss`
  * Under `.googlesitekit-entity-header__back` selector, for `.mdc-button` nested selector add `hover` state and ensure  is `text-decoration` is `none`
* It seems most of the buttons are already fixed since this issue is created, couldn't locate any other place. Other places 2 buttons are located in, and have the issue already fixed:
  * Get tailored metrics screen
  * Key metrics setup banner
  * Dashboard sharing dialog
  * AdSense Setup Banner (BannerNotification/BannerActions component in general, sets the tertiary button correctly)
  * Key Metrics selection panel
  * Modules settings edit (save | cancel)
  * Additional permissions popup
* Do an overall check if you can spot any other place that second button does not have tertiary style and does not fullfil AC criteria. 

### Test Coverage

* No updates should be needed

## QA Brief

* Setup Site Kit and Analytics module
* Check a single page statistics
* Verify that back to dashboard button is behaving properly and have styles as tertiary button

## Changelog entry

* Update secondary CTAs across the plugin to have consistent styling.

**Comment by bethanylang** [comment]
@hussain-t Are you planning to work on this soon? If not, can you please unassign yourself so someone else can pick up? Thank you!

**Comment by hussain-t** [comment]
@bethanylang, I'll work on it this week.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified all secondary CTA's.
- Verified single page "Back to dashboard" CTA. It's styled now as  tertiary button.
- Verified CTA's on other pages also and they are already updated through another ticket. 
- Few issues will be address through #8072 

<details>


![image](https://github.com/google/site-kit-wp/assets/94359491/16b9a64e-dbde-4e42-95f1-6fd0cbffa415)

![image](https://github.com/google/site-kit-wp/assets/94359491/275a78f2-c2e7-4cc2-b8cc-ac584ae83dfa)

![image](https://github.com/google/site-kit-wp/assets/94359491/b9c15806-3560-4716-b8a9-d86c7490ff5b)

![image](https://github.com/google/site-kit-wp/assets/94359491/9cc3b155-6f6b-4785-9675-3a453712cc65)

![image](https://github.com/google/site-kit-wp/assets/94359491/b829663c-f21b-458a-8722-7093917f58cb)

![image](https://github.com/google/site-kit-wp/assets/94359491/16099bbf-d407-457a-b7d0-d4e3c9e87e3b)

![image](https://github.com/google/site-kit-wp/assets/94359491/4529e48e-508f-42db-a8f4-4e8d0a45229a)

![image](https://github.com/google/site-kit-wp/assets/94359491/e3bfb59b-6987-41d2-94e5-d00187574a79)

![image](https://github.com/google/site-kit-wp/assets/94359491/0399d3de-4992-4892-b6f3-8e58f7b17125)

![image](https://github.com/google/site-kit-wp/assets/94359491/361f8d0d-1990-4289-9763-4671a2d5ef5a)

![image](https://github.com/google/site-kit-wp/assets/94359491/30a773e1-048c-49d9-8545-dc128929ac33)

![image](https://github.com/google/site-kit-wp/assets/94359491/6e2fa4d0-b1f9-4092-923c-db73bdf30432)


</details>
