### ISSUE TITLE
Can not reconnect apps after a wordpress reset...

### ISSUE THREAD

**Issue by Stef65lp** [google/site-kit-wp#78]
### **## Bug Description**

Can not reconnect apps after a wordpress reset...

----------------------------------------------------------------------------------------------------------

### **## Steps to reproduce**

- I have installed the plugin and start to develop my site.
- After an error I've reset my website.
- I've install again the application and configure it with my same account but for
   - Adsense is in loading without stop
   - Analytic when I do create an account and I do it but it sends me to the page where is the button "Create an account" and the link "Re-fetch My Account" and when I do "Re-fetch My Account" this is a short upload and after then still displays again the button and the link

----------------------------------------------------------------------------------------------------------

### **## Videos**

[https://www.youtube.com/watch?v=s8HGCkIP6qE](https://www.youtube.com/watch?v=s8HGCkIP6qE
)
----------------------------------------------------------------------------------------------------------

### ## Additional Context

 - PHP Version : 7.2.19
 - Wordpress : 3.6.4

----------------------------------------------------------------------------------------------------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by ivankristianto** [comment]
@Stef65lp 
Thank you for reporting this issue.
First I would like to know what do you mean by "reset my website"?
Second, is your WordPress version is 3.6.4? Can you please reconfirm?

**Comment by jamesozzie** [comment]
@Stef65lp From looking at the site URL in your video I can see you are using WordPress 5.2.2. 

Can you try deactivate Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit). Then open your browser in [Incognito mode](https://support.google.com/chrome/answer/95464?co=GENIE.Platform%3DDesktop&hl=en) before starting the Site Kit setup process again? If there are any console errors please check report them here also and we can hopefully assist.

**Comment by Stef65lp** [comment]
> @Stef65lp
> Thank you for reporting this issue.
> First I would like to know what do you mean by "reset my website"?
> Second, is your WordPress version is 3.6.4? Can you please reconfirm?

I've reset my website & database with this plugin : https://wordpress.org/plugins/advanced-wp-reset/

My wordpress version is : 5.2.2

**Comment by Stef65lp** [comment]
> @Stef65lp From looking at the site URL in your video I can see you are using WordPress 5.2.2.
> 
> Can you try deactivate Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit). Then open your browser in [Incognito mode](https://support.google.com/chrome/answer/95464?co=GENIE.Platform%3DDesktop&hl=en) before starting the Site Kit setup process again? If there are any console errors please check report them here also and we can hopefully assist.

I don't have an Settings option on my dashbord : http://prntscr.com/oasln8

**Comment by Stef65lp** [comment]
But @ivankristianto & @jamesozzie  I've reset my website again and I've re-install the  Site Kit but when I go on the link to configure my client (http://prntscr.com/oasm5w) I've this screen (http://prntscr.com/oasmai) it's okay but when I click on "GET OAUTH CREDENTIALS" I've an error (http://prntscr.com/oasmf9)

**Comment by jamesozzie** [comment]
@Stef65lp Thanks for the information. We will have to troubleshoot further. It would be great if you could try the following, before trying to install again:
- Check your [site settings](https://www.diigo.com/item/t/N3tyQLwMypycf5PHe17BzA6vLOPTjG3ucEsl3M0IXPsQhtRGMN5Ixg1RcPKX%0ADTv7%0A), ensure they both have your full site URL (including https). 
- Delete the [existing project ](https://www.diigo.com/file/image/bbdsarqezobeaespdezdrrbborp/Google+Cloud+Platform+-+Delete+Project.jpg)which was created from your [Google Cloud Console](https://console.cloud.google.com/cloud-resource-manager). 
- Ensure there are no [API key restrictions](https://www.diigo.com/item/t/N3tyQLwMypwwYkB2%2Bn950HiJbe0dA%2Brz0KjxYeta6ngbwDKkJB1qPWnziqnu%0Ak7A2%0A)

Before also trying to install and activate again please try the following (temporarily, during the install and setup process)
- Deactivating the social login plugin you have active
- Deactivate any Firewall/Ad Blocker active

Please let me know after you check

**Comment by Stef65lp** [comment]
> @Stef65lp Thanks for the information. We will have to troubleshoot further. It would be great if you could try the following, before trying to install again:
> 
> * Check your [site settings](https://s3.amazonaws.com/diigo/11390874_514047907_38811486?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1562327888&Signature=zMG74ayXdfVR5WRUgtv9mMsaZCI%3D), ensure they both have your full site URL (including https).
> * Delete the [existing project ](https://s3.amazonaws.com/diigo/11390874_514049634_38811586?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1562327853&Signature=Lc1m5pxRxH3iFPGydwz%2B3Mrr3f8%3D)which was created from your [Google Cloud Console](https://console.cloud.google.com/cloud-resource-manager).
> * Ensure there are no [API key restrictions](https://s3.amazonaws.com/diigo/11390874_514051089_38811735?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1562327819&Signature=aJWwN4xKybCFDZ5EzytcVcXmvUw%3D)
> 
> Before also trying to install and activate again please try the following (temporarily, during the install and setup process)
> 
> * Deactivating the social login plugin you have active
> * Deactivate any Firewall/Ad Blocker active
> 
> Please let me know after you check

My site settings : http://prntscr.com/oazg9j

I've delete my existing project, his name was "codedefille" : http://prntscr.com/oazgsy

How to check there are no API key restrictions ?

I've desactivate all plugin : http://prntscr.com/oazhni

**--- All of those above did not work ---**

> I thinks the solution is to desactivate adblocker on my site & on google : http://prntscr.com/oazinb - http://prntscr.com/oazj0i


Because when I do that, it's work ! 

Thanks you so much @jamesozzie & you too @ivankristianto**

**Comment by Stef65lp** [comment]
And the connection with Adsense & Analytic work again, everythings is good !

**Comment by jamesozzie** [comment]
@Stef65lp Great news, and thanks for letting us know. What AdBlocker software do you use?

**Comment by Stef65lp** [comment]
@jamesozzie I use this extension on Chrome : https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb?hl=fr
