### ISSUE TITLE
Google* (GoogleUtil, GoogleComponents, etc.) are not treated as Internal dependencies

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#780]
## Bug Description

See: https://github.com/google/site-kit-wp/pull/437#discussion_r341506915

Imports for https://github.com/google/site-kit-wp/blob/22c4aabb0bfdb310ab2da6d6ffbe66adfa7219d4/webpack.config.js#L94-L101 are not recognised by `eslint` as internal dependencies, and are allowed to be stored in any dependency section.

We should tweak the ESLint config around this, though personally I'd advocate for simply getting rid of these module aliases entirely (I find them quite confusing, especially when new to the project) and using file paths directly.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
It's not a global ESLint config issue, but a current limitation in the `@wordpress/dependency-group` rule. I've been wanting to fix this for a while, see https://github.com/WordPress/gutenberg/issues/16789.

However, I tend to agree with just getting rid of these aliases, they don't seem very useful to me.

**Comment by swissspidy** [comment]
Fixed by #1337 (leet!)
