### ISSUE TITLE
Remove `Build_Mode`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7808]
## Feature Description

`Build_Mode` is something that was intended to make conditional logic based on Webpack's build `mode` possible in PHP. It hasn't proved useful though and so we should remove it as it's essentially unused.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `Build_Mode` and its underlying value in `dist/config.php` should be removed

## Implementation Brief

* Remove the `Google\Site_Kit\Core\Util\Build_Mode` class and its test by removing the following files:
    * `includes/Core/Util/Build_Mode.php`
    * `tests/phpunit/integration/Core/Util/Build_ModeTest.php`
* Remove the usage of `Build_Mode` in the following places:
    * `Google\Site_Kit\Plugin`
        * Remove the call that sets build mode in the `load` method. 
    * `tests/phpunit/includes/TestCase.php`
        * Remove the `reset_build_mode` method.
        * Remove the `self::reset_build_mode` call from `tear_down_after_class` method. 
* Remove the unused `Build_Mode` import from the following files:
    * `includes/Core/Modules/Modules.php`
* Remove the related infrastructure from `webpack.config.js`
    * Remove the `buildMode` from `configTemplate` php template. 
    * Remove the `.replace( '{{buildMode}}', `'${ flagMode }'` )` operation done on `configTemplate` in the `CreateFileWebpack` plugin.
    * Remove the `flagMode` constant that is destructured from the `argv` of `webpackConfig` generator function. 

### Test Coverage

* Existing tests should continue to pass. 

## QA Brief

* Ensure all tests are passing, and everything still works without errors

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kuasha420** [comment]
I've tested regular and production builds, and stories on local. They are successfully passing on local as well as CI. Moving directly to approval as no additional QA is needed for the removed code that were not being used in the first place. :1st_place_medal:
