### ISSUE TITLE
Locales are no longer appearing/loading in plugin

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7819]
## Bug Description

While triaging/filing issues related to RTL support (#1156), I was't actually able to load Arabic translations in the plugin while testing, despite setting my `navigator.language` to `'ar'` and changing the WordPress to Arabic. Here's a screencast showing me going through the login flow—Google's OAuth recognises me as an Arabic user, as does WordPress, but Site Kit always shows me English text:

https://github.com/google/site-kit-wp/assets/90871/2b694b3c-e5e2-46dd-aeab-68542e98eb53

I wondered if maaaaybe we were missing Arabic translations, but I picked standard French and (European) Portuguese with the same results:

![CleanShot 2023-11-02 at 22 30 35](https://github.com/google/site-kit-wp/assets/90871/5a84afa6-33eb-4996-982a-5283349c213d)

![CleanShot 2023-11-02 at 22 31 13](https://github.com/google/site-kit-wp/assets/90871/5e87c953-b19b-4976-9b69-da59e6382f38)

It certainly seems like our locales are not loading. This was using the latest release (`1.12.0`) on WordPress `6.3.2`.

It turns out we don't actually support any RTL languages right now that I could see:

![CleanShot 2023-11-02 at 22 38 40](https://github.com/google/site-kit-wp/assets/90871/00f0aceb-7149-4c42-9f15-37b8f949a68d)

But I did change to Brazilian Portuguese just to make sure my European Portuguese wasn't being flagged incorrectly. Still nothing loads:

https://github.com/google/site-kit-wp/assets/90871/b7f82f72-0461-48af-aca8-7f09518f6503

## Steps to reproduce

1. Set your WordPress locale to a language other than English that Site Kit supports. (See list above, or at https://wordpress.org/plugins/google-site-kit/#developers by clicking on "See all 25" under "Languages").
2. Install Site Kit.
3. Observe that no strings are translated; everything is in English.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Existing locales should be loaded based on the WordPress install and/or the user's browser language.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This may happen if you forgot to update the translations after switching the language. This is necessary to see them right away with an existing plugin installed.

<img width="721" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/c9ef767d-3424-48f8-a7e2-2bade01ed0ee">


I tested the latest release with German and it loaded as expected for me after I updated the translations (last choice at the bottom of `wp-admin/update-core.php`).

<img width="1271" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/69ed0484-94c1-45fa-b905-18386215fcde">

Aside from that, translations are filename specific for JS so it will only work when using the builds published to wp.org. It looks like you were doing that in this case, but worth noting.

Closing this out as there does not appear to be a critical bug with our localization 🎉

**Comment by tofumatt** [comment]
@aaemnnosttv Odd, I even tried this when installing a new plugin, so I would've expected the translations to be available on install. I suppose maybe because it was once-installed in English it failed to fetch them? 🤔

I guess that's the standard experience, and more of a WordPress bug, but it was super-jarring 😢 

Thanks! 👍🏻
