### ISSUE TITLE
JS translation strings are broken on .org

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#782]
## Bug Description

`google-site-kit` JS translation strings are not being picked by .org translation tool, this is most likely due to the translation function being renamed upon JS minification.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Prevent JS minification from renaming (minifying) JS translation functions.
* Preserve translation comments.
* Have all `google-site-kit` JS translation strings picked up by .org translation tool.

## Implementation Brief

* Add `terser-webpack-plugin` and relevant `TerserPlugin` bits to `webpack.config.js` to prevent `// translators:` comments from being removed in JS output
* Integrate the Jest branch (#437) to use `@wordpress/*` packages allowing us to preserve function names
* Add `keep_fnames` to `terserOption`

## Changelog entry

* Ensure that `google-site-kit` translation strings in JavaScript files are maintained after minification so that they can be translated on wordpress.org.

**Comment by tofumatt** [comment]
This IB is ready and as discussed on the call today: this branch requires using webpack packages for `@wordpress/i18n` instead of `wp.i18n`. This is ready in the Jest branch.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

### Procedure
1. Built plugin zip using `npm run release-zip`
1. Extract zip
1. Generate POT file from plugin files similar to how wp.org does:  
    ```
    wp i18n make-pot google-site-kit --ignore-domain --skip-audit
    ```
1. Count number of translation references in POT file for PHP  
    ```
    grep .php google-site-kit.pot | wc -l
    197
    ```
1. Count number of translation references in POT file for JS
    ```
    grep .php google-site-kit.pot | wc -l
    574
    ```
    <summary>
    Snippet of JS references
    <details>

    ```
    #: dist/assets/js/allmodules.js:1
    #: dist/assets/js/commons.js:1
    #: dist/assets/js/googlesitekit-settings.js:1
    #: dist/assets/js/commons.js:1
    #: dist/assets/js/allmodules.js:7
    #: dist/assets/js/commons.js:1
    #: dist/assets/js/allmodules.js:11
    #: dist/assets/js/googlesitekit-dashboard-splash.js:1
    #: dist/assets/js/chunk-googlesitekit-setup-wizard-proxy.js:3
    #: dist/assets/js/chunk-googlesitekit-setup-wizard.js:3
    #: dist/assets/js/chunk-googlesitekit-setup-wrapper.js:1
    #: dist/assets/js/commons.js:1
    #: dist/assets/js/chunk-googlesitekit-setup-wizard-proxy.js:3
    #: dist/assets/js/chunk-googlesitekit-setup-wizard.js:3
    #: dist/assets/js/chunk-googlesitekit-setup-wrapper.js:1
    #: dist/assets/js/commons.js:1
    #: dist/assets/js/chunk-googlesitekit-setup-wizard-proxy.js:3
    #: dist/assets/js/chunk-googlesitekit-setup-wizard.js:3
    #: dist/assets/js/chunk-googlesitekit-setup-wrapper.js:1
    #: dist/assets/js/commons.js:1
    ```
    </details>
    </summary>
1. Ensure generated POT includes `translators:` comments for JS entries  

    ```
    #. translators: %s: Error message
    #: dist/assets/js/allmodules.js:9
    #: dist/assets/js/allmodules.js:11
    msgid "Error: %s"
    msgstr ""
    ```
    ```
    #. translators: %s is the site's hostname. (e.g. example.com)
    #: dist/assets/js/chunk-googlesitekit-setup-wizard-proxy.js:3
    msgid "You revoked access to Site Kit for %s"
    msgstr ""

    #. translators: %s is the site's hostname. (e.g. example.com)
    #: dist/assets/js/chunk-googlesitekit-setup-wizard-proxy.js:3
    msgid "Site Kit will no longer have access to your account. If you’d like to reconnect Site Kit, click \"Start Setup\" below to generate new credentials."
    msgstr ""
    ```
    ✅

---

Moving to Approval

**Comment by felixarntz** [comment]
Wow, that is a ton of translation strings :/

Which might be needed, but let's see. There might be something we can consolidate at some point.

**Comment by aaemnnosttv** [comment]
> Wow, that is a ton of translation strings :/

That's not a count of unique strings, that's how many references/usages there are. Each string in the pot file has comments for it as to each place it is referenced in the code.

Also, I just realized that these counts include the strings included from `@wordpress/components`.

There are now only `487` references in JS, but there are `521` unique translation strings (including PHP) - still a lot? I'll include the file here for you to see for yourself.

[google-site-kit.pot.txt](https://github.com/google/site-kit-wp/files/3821126/google-site-kit.pot.txt)
(Had to add `.txt` here for GitHub to allow me to upload it)
