### ISSUE TITLE
Unable to receive access token because of an invalid authorization code or refresh token.

### ISSUE THREAD

**Issue by Wegerich** [google/site-kit-wp#783]
## Bug Description

I regularly see an error message in my admin backend. There is no indication of which plugin the error belongs to inside the error message but I found an exact match for this text through web search.

> Unable to receive access token because of an invalid authorization code or refresh token.

It goes away on refresh.

I have been running v1.01 for 2 days, the issue emerged today. 

## Steps to reproduce

Browse admin backend.

## Screenshots

![image](https://user-images.githubusercontent.com/23041237/68130404-33cc4f80-ff13-11e9-9d7c-da146fbee24a.png)

## Additional Context

 - PHP Version: 7.3.11
 - OS: Win 10
 - Browser Chrome
 - Plugin Version 1.01
 - Device: PC

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@Wegerich Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
