### ISSUE TITLE
Remove `enhancedMeasurement` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7833]
## Feature Description

Once available to all sites, the `enhancedMeasurement` feature flag should be removed, replacing the conditional functionality it controlled with the guarded code unconditionally.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `enhancedMeasurement` feature flag should be removed such that conditions that use it should keep the code path where the flag is `true`
* Any other references to the flag should be removed, except the changelog
* **Before merging a PR for this, please confirm with @aaemnnosttv**

## Implementation Brief

- Remove all usage of the `enhancedMeasurement` feature flag from the code, keeping the code path there the flag would be `true`.
- At the time of writing there are currently 9 conditions that use the flag across the following 8 files in the production code:
```
includes/Modules/Analytics_4.php
assets/js/modules/analytics/components/common/AccountCreate/index.js
assets/js/modules/analytics/components/settings/GA4SettingsView.js
assets/js/modules/analytics/components/settings/GA4SettingsControls.js
assets/js/modules/analytics/components/setup/SetupFormGA4.js
assets/js/modules/analytics-4/datastore/settings.js
assets/js/modules/analytics-4/datastore/enhanced-measurement.js
assets/js/components/notifications/BannerNotifications.js
```
- 4 stories with the flag enabled across the following 3 story files:
```
assets/js/modules/analytics/components/settings/SettingsForm.stories.js
assets/js/modules/analytics/components/settings/SettingsView.stories.js
assets/js/modules/analytics/components/setup/SetupFormGA4.stories.js
```
- 9 tests that enable the flag across the following 5 test files:
```
tests/phpunit/integration/Modules/Analytics_4Test.php
assets/js/modules/analytics/datastore/settings.test.js
assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.test.js
assets/js/modules/analytics-4/datastore/settings.test.js
assets/js/modules/analytics-4/datastore/enhanced-measurement.test.js
```
- Remove the flag from `feature-flags.json`.
- Remove any tests and stories that are no longer needed.
- Fix any broken tests.

### Test Coverage

- N/A.

## QA Brief

- Verify that the `enhancedMeasurement` feature flag has been removed from the Tester plugin.
- The Enhanced Measurement feature should be active, and there should be no changes to Site Kit's behaviour.
- Perform a general smoke test of the plugin.
- Perform a full regression test of the Enhanced Measurement feature (i.e. the controls in the Settings page, and the "Enable enhanced measurement" banner).

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by 10upsimon** [comment]
Passing over to @zutigrm for e2e tests analysis as I am struggling to fix the 3x failing E2E tests myself.
