### ISSUE TITLE
Remove Storybook stories related to UA

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#7842]
## Feature Description

Some Stories and their VRT reference images should probably be removed. Here is the list of currently spotted ones in the linked comments:
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385262912
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385276597
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385277517
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385284455
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385301355
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385304579
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385307312
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385310716
https://github.com/google/site-kit-wp/pull/7582#discussion_r1385313234

Also stories from `common.stories.js` and it's usage across other stories, as only `common-gGA4.stories.js` should be used.

`common-gGA4.stories.js` should also need some refactoring especially around how dates are used, for more info see this [comment](https://github.com/google/site-kit-wp/pull/7839#discussion_r1394827691), and [this one](https://github.com/google/site-kit-wp/pull/7839#discussion_r1394844581)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* As a part of removing the `analytics` module in [#7843](https://github.com/google/site-kit-wp/issues/7843), most of the UA-relevant Storybook stories should have also been removed. However, the remaining Storybook stories in Site Kit should be reviewed to ensure that no other UA-relevant stories exist.

## Implementation Brief

* Wait until [#7843](https://github.com/google/site-kit-wp/issues/7843) is merged.
* Remove the following UA Storybook stories if they still exist:
  * `stories/module-analytics.stories.js`
  * `stories/module-analytics-setup.stories.js`
  * `stories/module-analytics-settings.stories.js`
  * `stories/module-analytics-components.stories.js`
  * `assets/js/components/wp-dashboard/common.stories.js`
  * `assets/js/components/adminbar/common.stories.js`
  * `assets/js/components/adminbar/AdminBarSessions.stories.js`
  * `assets/js/components/adminbar/AdminBarUniqueVisitors.stories.js`
  * `assets/js/components/wp-dashboard/WPDashboardPopularPages.stories.js`
  * `assets/js/components/wp-dashboard/WPDashboardSessionDuration.stories.js`
  * `assets/js/components/wp-dashboard/WPDashboardUniqueVisitors.stories.js`
  * `assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChart.stories.js`
  * `assets/js/modules/analytics/components/common/UACutoffWarning.stories.js`
  * `assets/js/modules/analytics/components/settings/SettingsUACutoffWarning.stories.js`
  * `assets/js/modules/analytics/components/dashboard/DashboardOverallPageMetricsWidget.stories.js`
  * `assets/js/modules/analytics/components/setup/SetupFormUA.stories.js`
  * `assets/js/modules/analytics/components/settings/SettingsView.stories.js`
  * `assets/js/modules/analytics/components/settings/SettingsForm.stories.js`
* Look for the `[Story].scenario` in the above files and remove the relevant VRT images from `tests/backstop/reference`.

### Test Coverage

* No new tests are required for this change.
* Ensure the Visual Regression Tests pass after removing the stories and their VRT images.

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@nfmohit this should be coordinated with the other SAM work.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by benbowler** [comment]
I checked in develop and none of these files exist, so I think this ticket can be closed.

**Comment by benbowler** [comment]
After discussing in Slack, this ticket has already been addressed in other tickets.
