### ISSUE TITLE
Remove `analytics` module from the codebase

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#7843]
## Feature Description

Some things will not be needed since feature flag is removed. For example [provisioning scope](https://github.com/google/site-kit-wp/pull/7582#discussion_r1384841197), [UAProperty](https://github.com/google/site-kit-wp/pull/7582#discussion_r1385171905), and some [test cases](https://github.com/google/site-kit-wp/pull/7582#discussion_r1385194114) in `assets/js/modules/analytics/datastore/accounts.test.js`

Existing jest tests should be revisited as well.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `analytics` module which has by now become obsolete and replaced by `analytics-4` should be entirely removed from the Site Kit plugin. This should include but may not be limited to:
  * The `Modules\Analytics` module class and all other classes in this namespace in PHP.
  * The `modules/analytics` datastore.
  * The `analytics` module on the client-side.
  
## Implementation Brief

* [7932](https://github.com/google/site-kit-wp/issues/7932) will remove most of the Analytics module related code, after it is merged, follow the AC to check if anything remained
* Remove the pieces linked in the description
* Check if any analytics components/modules/widgets counterpart are still present and remove them. Example  `AdminBarSessions` should be replaced with `AdminBarSessionsGA4`, etc
* Search for any remaining usage of `MODULES_ANALYTICS` store selector and replace it with `MODULES_ANALYTICS_4`
* Remove `assets/js/components/adminbar/common.stories.js` and `assets/js/components/wp-dashboard/common.stories.js`
* Search for `modules/analytics/data/` through the codebase to identify presence of old Analytics route usage and update/remove the code accordingly

### Test Coverage

* In e2e plugin `tests/e2e/plugins/module-setup-analytics-no-account.php`, rename `e2e/setup/analytics/account-created` endpoint to `e2e/setup/analytics-4/account-created`. And replace its usage in e2e tests where applicable.
* In `tests/e2e/plugins/module-setup-analytics.php`
  * Cleanup the remaining analytics routes, like `properties-profiles`, and `profiles`, but leave `accounts-properties-profiles` unless it was completely replaced by `account-summaries`, as at the time of writing we still use `accounts` from that response. If this is completely replaced, we can remove that endpoint too.
  * Remove the usage of these routes if they are still present. At the time of writing they are still used only in jest tests for accounts and account select.
* Remove the usage of `analytics/data/goals` route from e2e tests, as it was used only by old analytics, GA4 does not have goals.
* Remove `analytics/data/report` route from the e2e tests if still present
* In `.storybook/fetch-mocks.js`, replace [`analytics`](https://github.com/google/site-kit-wp/blob/c6630ca488f8531d245f53a8f4fd49ead0713f60/.storybook/fetch-mocks.js#L75) with `analytics-4` 
* Replace any outstanding usage of `MODULES_ANALYTICS` store with `MODULES_ANALYTICS_4` in stories and jest tests. Some of the files at the time of writing:
  * `assets/js/components/ReportError.test.js` 
  * `assets/js/components/ReportError.stories.js`
  * `assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.stories.js`
  * `assets/js/components/dashboard-sharing/DashboardSharingSettings/index.stories.js`
  * `assets/js/components/notifications/GoogleTagIDMismatchNotification.stories.js`
  * `assets/js/components/notifications/WebDataStreamNotAvailableNotification.stories.js`
  * `assets/js/components/notifications/ZeroDataStateNotifications/index.stories.js`
   

## QA Brief

- This PR removes the legacy `analytics` module. No specific checks are needed here. The SAM E2E testing should cover testing this.

## Changelog entry

* Remove the legacy `analytics` module (UA) from Site Kit.

**Comment by tofumatt** [comment]
I think the ACs here are good, it's tough to be exhaustive when writing these but this should cover it 😄 

ACs 👍🏻

**Comment by techanvil** [comment]
Hey @zutigrm, this IB is looking good. A few points:

- It could be worth specifying a search for `modules/analytics/data/` to identify any potentially remaining places where the old Analytics paths are being referenced and update/remove the code accordingly.
- This should be somewhat implicit, but it would be worth making explicit that when replacing `analytics` with `analytics-4`, we should check that the code is also still in use. For example `assets/js/modules/analytics/hooks/useExistingTagEffect.js` can be completely removed rather than migrated, as it's superceded by `assets/js/modules/analytics-4/hooks/useExistingTagEffect.js`.
- It's a minor point, but there doesn't really seem to be a need to single out `assets/js/modules/analytics/datastore/goals.test.js` in the IB, as all tests under `assets/js/modules/analytics/datastore/` should be removed anyway by following the AC point to remove the `modules/analytics` datastore.

**Comment by zutigrm** [comment]
@techanvil Thanks for the feedback.

> It could be worth specifying a search for modules/analytics/data/ to identify any potentially remaining places...

Thanks, that a good idea!

> This should be somewhat implicit, but it would be worth making explicit that when replacing analytics with analytics-4, we should check that the code is also still in use. For example assets/js/modules/analytics/hooks/useExistingTagEffect.js can be completely removed rather than migrated, as it's superceded by assets/js/modules/analytics-4/hooks/useExistingTagEffect.js.

I actually didn't mention that, because it will be taken care of in #7932, it removes the entire analytics module (IB mentions moving over needed parts and removing `assets/js/modules/analytics/`, `assets/js/googlesitekit-modules-analytics.js`, etc), so functions/datastore, etc will be transferred by the time this issue is executed, in this issue, I just tried to cover some remaining pieces outside the module folders.

> It's a minor point, but there doesn't really seem to be a need to single out assets/js/modules/analytics/datastore/goals.test.js in the IB, as all tests under...

Thanks, good catch! Removed

**Comment by techanvil** [comment]
Great, thanks for updating/clarifying, @zutigrm. This IB LGTM :white_check_mark:

**Comment by hussain-t** [comment]
Hi @jimmymadon, when you take over this, please make sure to replace `adsenseLinked` with `adSenseLinked` and `adsenseLinkedLastSyncedAt` with `adSenseLinkedLastSyncedAt` throughout the plugin. Thanks!

**Comment by aaemnnosttv** [comment]
This LGTM although I did notice we're still bundling the legacy client services which should no longer be needed. 

https://github.com/google/site-kit-wp/blob/8f5a6b08c4a0409f86e37d9c7db438d637a1a983/scoper.inc.php#L18

We can clean this up in a follow-up. cc: @nfmohit

**Comment by nfmohit** [comment]
> This LGTM although I did notice we're still bundling the legacy client services which should no longer be needed.
> 
> https://github.com/google/site-kit-wp/blob/8f5a6b08c4a0409f86e37d9c7db438d637a1a983/scoper.inc.php#L18
> 
> We can clean this up in a follow-up. cc: @nfmohit

Thank you for pointing this out, @aaemnnosttv. I've opened #8459 to address this.
