### ISSUE TITLE
Sync Custom Dimensions Error When Analytics Module is Disconnected

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#7852]
## Bug Description

When analytics module is disconnected, and you navigate to dashboard there is a console log error for `sync-custom-dimensions` request.

Sync custom dimensions should check if `analytics-4` module is active before sending the request.

## Steps to reproduce

1. Setup Site Kit with `keyMetrics` feature flag
2. Setup Analytics module
3. Go to settings and disconnect Analytics module
4. Go back to dashboard, check the console log

## Screenshots

<img width="752" alt="Screenshot 2023-11-10 at 09 22 05" src="https://github.com/google/site-kit-wp/assets/10414808/d5401658-d740-459c-a6f5-2a7615e86e57">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The request to `sync-custom-dimensions` should only be attempted when GA4 is connected

## Implementation Brief

* Update the resolver for `getAvailableCustomDimensions` to return early if `analytics-4` is not connected as the first guard
* Update the Key Metrics `Notice` to only render when `analytics-4` is connected
* Finish https://github.com/google/site-kit-wp/pull/7855

### Test Coverage

* Update `assets/js/modules/analytics-4/datastore/custom-dimensions.test.js` with added coverage related to GA4 activation, but also GA4 will need enabling now for existing tests to work as before

## QA Brief

- Follow the "Steps to reproduce" in the issue description and verify that the reported error no longer occurs.

## Changelog entry

* Prevent console warning when disconnecting Analytics when Key Metrics feature flag is enabled.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv this same error message appears when logged in as a 2nd admin user, but when you go to the Site Kit settings page. I mentioned this in Slack a week or so ago and got the impression that this issue would fix that.  If not, it's possibly out of scope and needs another ticket but thought I would check. 

![image](https://github.com/google/site-kit-wp/assets/73545194/e95013fa-da54-4047-a3d5-5e8a5ebe7f1f)

**Verified:**

- I was able to recreate the issue as reported on the latest release. 
- When I switched to the develop branch, the reported error no longer occurs.
- Tested on main (and entity to double check) dashboard. 
- Tested it with a 2nd admin user to make sure the error no longer appears. 


<details>
 <summary>Screencast</summary>

https://github.com/google/site-kit-wp/assets/73545194/1a32ec7c-ffab-4f15-bf5d-e63170700907

</details>

**Comment by nfmohit** [comment]
> @aaemnnosttv this same error message appears when logged in as a 2nd admin user, but when you go to the Site Kit settings page. I mentioned this in Slack a week or so ago and got the impression that this issue would fix that. If not, it's possibly out of scope and needs another ticket but thought I would check.

Hi @wpdarren. While the error message is the same, it actually occurs for a different endpoint, not the `sync-custom-dimensions` one. So yes, this will indeed need a new issue for investigation.

**Comment by wpdarren** [comment]
@nfmohit thank you - in that case, I will get this moved into approval and create a new ticket!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- I was able to recreate the issue as reported on the latest release. 
- When I switched to the develop branch, the reported error no longer occurs.
- Tested on main (and entity to double check) dashboard. 
- Tested it with a 2nd admin user to make sure the error no longer appears. 


<details>
 <summary>Screencast</summary>

https://github.com/google/site-kit-wp/assets/73545194/1a32ec7c-ffab-4f15-bf5d-e63170700907

</details>
