### ISSUE TITLE
Metric tile design improvements

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7860]
## Feature Description

In an effort to retain consistency between metric tiles and improve responsiveness across multiple devices, the design of the metric tiles has been updated in Figma, which should be implemented in the application. Here is a summary of the changes:

1. The info tooltip icon should be aligned to the right in all viewports. Screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/728a9f2a-ed8d-453b-ae7b-c700154bfd8f)

2. Tiles with the "text" & "numeric" types should have a change in their layout in smaller viewports, i.e. instead of aligning the tile content to the right, it should be placed under the title as in larger viewports, but the "tile change percentage" should be aligned to the right. [Figma link](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7478-15011&mode=design&t=gkRgYUzruph8frY0-4). Screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/636f8021-e4a0-4c87-8525-493498a5dc86)

3. The text content in zero data/gathering data states of tiles should have a font-size of `body/medium`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The following updates should be made to an individual key metric widget tile:
  1. The info tooltip icon should be aligned to the right.
  2. In mobile viewports, "Numeric" & "Text" type tiles should have their tile content placed under the title and the metric change percentage should be aligned to the right, according to [this Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7478-15011&mode=design&t=gkRgYUzruph8frY0-4).
  4. The text content in zero data/gathering data states should have a font-size of `body/medium`.

## Implementation Brief

To address the AC points in order:

> 1. The info tooltip icon should be aligned to the right.

- Remove the `flex-direction` property where it has been added to `.googlesitekit-km-widget-tile__title-container` for the numeric and text tile types.  
- Add `flex: 1` to `.googlesitekit-km-widget-tile__title`.

> 2. In mobile viewports, "Numeric" & "Text" type tiles should have their tile content placed under the title and the metric change percentage should be aligned to the right, according to [this Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7478-15011&mode=design&t=gkRgYUzruph8frY0-4).

- Add `flex-direction: column` to `.googlesitekit-km-widget-tile`.  
- Fix the `margin-top` of `.googlesitekit-km-widget-tile__metric` for the mobile viewport - it should be `4px` (i.e. the current value of `-8px` plus the `margin-top` value of `.googlesitekit-km-widget-tile__table` which is `12px`).
- Add a `div` around the metric and subtext elements in the `MetricTileNumeric` and `MetricTileText` components.
- Add `display: flex` to `.googlesitekit-km-widget-tile__body` for the numeric and text tile types, and use Flexbox properties to implement the layout.

> 3. The text content in zero data/gathering data states should have a font-size of `body/medium`.

- Set the `font-size` and `line-height` properties for `.googlesitekit-table__body-zero-data` to `$fs-body-md` and `$lh-body-md` respectively.

Additionally, remove any redundant styling e.g. `flex-direction: column` can be removed from	`.googlesitekit-km-widget-tile--table`.

### Test Coverage

* Update VRT reference images as necessary.

## QA Brief

- Set up Site Kit and the Key Metrics widgets.
- Observe the widgets of various types and ensure the ACs are met.
- Cross-check their layouts with the linked Figma designs and verify that they are correct in both desktop and mobile viewports.
- Verify the Storybook stories for the widgets.

## Changelog entry

* Improve the layout of Key Metric numeric and text tiles.

**Comment by nfmohit** [comment]
**Note:** It would be good to verify with Sigal after adding the ACs to confirm if there is any improvement we've missed.

**Comment by nfmohit** [comment]
Note: There are a few other improvements that aren't a part of this issue, such as:

1. The tile title should take a height same as a tile with the highest title in the KMW area, e.g. if a tile's title is 2 lines long, all the tiles' titles should be 2 lines long. This will be implemented as a part of [#7761](https://github.com/google/site-kit-wp/issues/7761). Screenshot:
![image](https://github.com/google/site-kit-wp/assets/20284937/265a49ae-9fc9-4e4b-8161-6e2d8a3fd004)
2. In tile error states, the CTA height should be reduced to 32px. This should be implemented as a part of [#7763](https://github.com/google/site-kit-wp/issues/7763#issuecomment-1795476709). Screenshot:
![image](https://github.com/google/site-kit-wp/assets/20284937/1de09063-5cf4-45c1-8f93-f2f619bbb8da)
3. In tile error states for smaller viewports, the CTA should be aligned to the right. This should be implemented as a part of [#7763](https://github.com/google/site-kit-wp/issues/7763#issuecomment-1795476709). Screenshot:
![image](https://github.com/google/site-kit-wp/assets/20284937/5d14d2e5-b34e-470e-b260-f542435a8e5e)

**Comment by nfmohit** [comment]
@sigal-teller Co-assigning this to you just to ensure that the current ACs cover all the improvements made to the individual metric tiles that have been applied in Figma to date.

**Comment by nfmohit** [comment]
For the record, Sigal and I discussed this [internally](https://10up.slack.com/archives/C01CA828ZPZ/p1700257420053579) and this should cover all the improvements needed. Moving to ACR.

**Comment by tofumatt** [comment]
@nfmohit Strangely, it looks like all of the screenshots here aren't appearing 🤔 

Not sure what's happening there, but it makes it tough to review the issue in full 😅 

![CleanShot 2023-12-28 at 23 29 31](https://github.com/google/site-kit-wp/assets/90871/cfc48722-7306-46a5-9b78-0da9265d5de1)

![CleanShot 2023-12-28 at 23 29 37](https://github.com/google/site-kit-wp/assets/90871/62e09f6c-210e-43b9-b4c9-5e47c3c2d742)

The Figma link seems off too, can you double-check that stuff to make sure it references what the ACs refer to?

**Comment by nfmohit** [comment]
Thank you for the review, @tofumatt. I have updated the Figma links to correctly point to the appropriate screen. However, the screenshots in the issue does load for me. I have also checked from different browsers and devices.

![image](https://github.com/google/site-kit-wp/assets/20284937/1c8fe5c8-1335-46b4-9d4e-d41792424d97)

Could you give it another look? Thank you!

**Comment by tofumatt** [comment]
Weird, now they're all fine! 😅 

I guess it was a CDN thing or something 🤔

**Comment by tofumatt** [comment]
ACs look good, moving to IB 👍🏻

**Comment by tofumatt** [comment]
Looks good to me 👍🏻 

IB ✅
