### ISSUE TITLE
Fix failing User Input E2E tests.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7862]
## Feature Description

The User Input tests in the spec file `tests/e2e/specs/user-input-questions.test.js` have started failing in `develop`.

As mentioned [here](https://github.com/google/site-kit-wp/issues/7738#issuecomment-1806521694), this has started occurring since upgrading our version of Puppeteer. It would be good to revisit the upgrade to see if any NPM dependencies also needed an update and were missed. Alternatively we could see about updating to a more recent version of Puppeteer, or, if needs be we could revert to the previously used version, as we ended up [skipping the failing test](https://github.com/google/site-kit-wp/pull/7812) that we'd upgraded Puppeteer for anyway.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The User Input E2E tests in `tests/e2e/specs/user-input-questions.test.js` should pass.

## Implementation Brief

* Roll back `puppeteer` to the previous `^10.4.0`
* Merge https://github.com/google/site-kit-wp/pull/7873

### Test Coverage

* No changes

## QA Brief

* See E2E tests passing (WP nightly may still have some stability issues)

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅ 

I'll review the PR here as well 🙂

**Comment by tofumatt** [comment]
QA passes as part of the review, so moving this directly to Approval.
