### ISSUE TITLE
Update the GM2 circular progress indicator to use the correct color.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7863]
## Feature Description

The GM2 version of the circular progress indicator should be updated to use the same Content Primary color as the horizontal progress indicator.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GM2 circular progress indicator should be updated to use the [Content Primary](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-tokens--default-token) color, `#3c7251`.

## Implementation Brief

* Create a new stylesheet: `assets/sass/vendor/_mui-circular-progress.scss`
    * inside `.googlesitekit-plugin `
        * Override the styles for the following classes as follows:
            * `.MuiCircularProgress-colorPrimary`:
                * `color`: `$c-content-primary`
            * `.MuiCircularProgress-colorSecondary`:
                * `color`: `$c-content-secondary`
* Import the newly created file in `assets/sass/admin.scss`, `assets/sass/adminbar.scss` and `assets/sass/wpdashboard.scss`.
### Test Coverage

* Create stories for `CircularProgress` in `assets/js/googlesitekit/components-gm2/CircularProgress.stories.js`, preferably with primary, secondary and some size variants. 

## QA Brief

- Open the `CircularProgress` Storybook story and verify that it uses the correct SK primary and secondary colours.

## Changelog entry

* Update CircularProgress component to use correct material design colors.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

Tested on dev environment.
Verified `CircularProgress`[ Storybook story ](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-circularprogress--color-primary)it uses the correct SK primary and secondary colours.
