### ISSUE TITLE
Allow hostnames to be resolved to specific IP versions for SK requests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7864]
## Feature Description

Some environments have trouble using Site Kit due to rare complications with default IP resolution. Allowing this to use a specific version can help in some situations.

For more information, see the related functionality in cURL https://daniel.haxx.se/blog/2020/04/20/curl-ootw-ipv4/

Also https://docs.guzzlephp.org/en/6.5/request-options.html#force-ip-resolve

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `googlesitekit_force_ip_resolve` filter should be implemented
	- Default `null`
	- The only values allowed/recognized from it other than the default should be the strings `v4` and `v6`
* The filter should control the IP resolution of requests made by the `Google_Site_Kit_Client`

## Implementation Brief

* Finish and merge https://github.com/google/site-kit-wp/pull/7867

### Test Coverage

* Update coverage in `Client_FactoryTest`

## QA Brief

* No QA is needed here. Changes in hte http config are tested using phpunit tests.

## Changelog entry

* Allow the IP version to be specified for server-side requests.

**Comment by techanvil** [comment]
Hey @aaemnnosttv, this IB looks good. One small point, regarding the test coverage - I notice the more substantial tests for the client config are in `Client_FactoryTest`, this could be a more appropriate place to add tests - did you already consider this option?

**Comment by aaemnnosttv** [comment]
Thanks @techanvil, let's test it there instead 👍

**Comment by techanvil** [comment]
Nice one @aaemnnosttv. IB LGTM :white_check_mark:
