### ISSUE TITLE
Do not show Enhanced Measurement banner when KMW setup CTA is visible

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7865]
## Feature Description

To prevent showing the user multiple setup CTAs with Enhanced Measurement and Key Metrics launching in a short interval, the Enhanced Measurement banner notification should not be rendered when the Key Metrics setup CTA is visible.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Enhanced Measurement activation banner notification should not be rendered when the Key Metrics setup CTA will be shown on the Site Kit dashboard.
	* The banner should not appear in response to dismissing the KM CTA (on the same page load) 

## Implementation Brief

In `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`:

* Within a new `useEffect` hook, set a global state of the `core/ui` store with the `HIDE_ENHANCED_MEASUREMENT_ACTIVATION_BANNER` (or an appropriate) key if the following conditions are met:
    * If the `KEY_METRICS_SETUP_CTA_WIDGET_SLUG` item is not dismissed (specifically check for the `false` value) AND
    * If `analyticsIsDataAvailableOnLoad` is `true` AND
    * If `searchConsoleIsDataAvailableOnLoad` is `true`

In `assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/index.js`:

* Update the conditions that return `null` to check for the `HIDE_ENHANCED_MEASUREMENT_ACTIVATION_BANNER` key in the `core/ui` store and return `null` if the value is set to `true`.
* This will prevent the banner from being rendered when the KM CTA is present, and it will stay hidden when the KM CTA is dismissed (on the same page load). The state will be reset on the next page load, and the banner will be displayed if the conditions are met.

### Test Coverage

* In `EnhancedMeasurementActivationBanner/index.test.js`:
    * Add a test case to ensure that the banner is not rendered when the `HIDE_ENHANCED_MEASUREMENT_ACTIVATION_BANNER` key is set to `true` in the `core/ui` store.
* In `KeyMetricsSetupCTAWidget.test.js`:
    * Add a test case to ensure that the `HIDE_ENHANCED_MEASUREMENT_ACTIVATION_BANNER` key is set to `true` when the KM setup CTA is displayed.
    * Add a test case to ensure that the `HIDE_ENHANCED_MEASUREMENT_ACTIVATION_BANNER` key is still set to `true` when the KM setup CTA is dismissed.
* Fix any failing tests.

## QA Brief

* Test conditions for showing the KM Setup CTA on the dashboard (GA + SC connected with data)
* With a GA4 property that does not have EM enabled, the EM CTA should not display on the dashboard at the same time as the KM set up CTA

## Changelog entry

* Prevent Enhanced Measurement banner from appearing when Key Metrics CTAs are visible.

**Comment by techanvil** [comment]
Hi @hussain-t, thanks for drafting this IB. There are a few points to address:

> If the `KEY_METRICS_SETUP_CTA_WIDGET_SLUG` item is dismissed (with the `false` value) AND

It's correct that we should check for `isDismissed === false`, but the wording of the point is wrong because this indicates the item has _not_ been dismissed, this had me confused for a bit until I worked through it. So, please update the point along these lines:

> If the `KEY_METRICS_SETUP_CTA_WIDGET_SLUG` item is not dismissed (specifically check for the `false` value) AND

I also found the following point a bit confusing, because it can suggest that the IB is only covering the dismissal of the banner:

> This will prevent the banner from being rendered in response to dismissing the KM CTA (on the same page load).

I'd suggest updating this along these lines:

> This will prevent the banner from being rendered when the KM CTA is present, and it will stay hidden when the KM CTA is dismissed (on the same page load).

Lastly, regarding the test coverage, `KeyMetricsSetupCTAWidget` also has some existing coverage so we could add a test there as well. This being the case, we might want to bump the estimate up too.

**Comment by hussain-t** [comment]
Thanks for your kind review, @techanvil. I have updated the iB.

**Comment by techanvil** [comment]
Thanks @hussain-t! The IB LGTM. :white_check_mark:

**Comment by aaemnnosttv** [comment]
@techanvil @hussain-t I've opened a PR for a simpler alternative approach that minimizes changes to existing components.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that With a GA4 property that does not have EM enabled, the EM CTA is not displaying on the dashboard at the same time as the KM set up CTA.
- Verified that the banner not appear in response to dismissing the KM CTA (on the same page load)

<details>


https://github.com/google/site-kit-wp/assets/94359491/f685c914-9db6-4695-8578-9848dcc385e4

</details>
