### ISSUE TITLE
Host .js files locally

### ISSUE THREAD

**Issue by jonathansoltero** [google/site-kit-wp#787]
## Feature Description

It would be amazing if you can give us the option to host: analytics.js/gtag.js/ga.js locally, this will give us the ability to speed up our site by freeing some DNS lookups & by using our expire & cache rules. A plugin like this exists, it’s called CAOS but it does not support Site Kit, either way, adding this option to this plugin itself will help reduce the use of other plugins which is what this plugin is meant to help with!

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Closing as we already have #1132 open in relation to this request.
