### ISSUE TITLE
Revert the "Search Console is gathering data" notification to show 48 hours.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7876]
## Feature Description

The "Search Console is gathering data" notification was inadvertently updated to state that it "can take up to 72 hours before stats show up for your site" via https://github.com/google/site-kit-wp/issues/6877.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeERZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c3b1649e70a652f99333f05cf285d8a28d7e169/image.png)

The gathering data notification should be updated to show the figure of 48 hours for the Search Console module alone.

Please note that in the case where both Search Console and Analytics are gathering data, it's valid to display the figure of 72 hours, so this is correct:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e299e6539aeeb65ce41692cb22125a3ba2412733/image.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Search Console is gathering data" notification should be updated to display the figure of 48 hours, i.e. its description should read as follows:
  * _It can take up to 48 hours before stats show up for your site. While you’re waiting, connect more services to get more stats._
* In the case where either Analytics alone is, or both Search Console and Analytics are gathering data, the figure should remain at 72 hours.

## Implementation Brief

* In the `GatheringDataNotification` component, add a new `gatheringDataWaitTime` prop. 
* Move the logic of computing this `gatheringDataWaitTime` to the `assets/js/components/notifications/ZeroDataStateNotifications/index.js` component.
* Compute the `gatheringDataWaitTime` as per the AC using the values of `analyticsGatheringData` and `searchConsoleGatheringData` within the `index` component above. Pass the `gatheringDataWaitTime` computed as the new prop to `GatheringDataNotification`.

### Test Coverage

* No new tests required.

## QA Brief

* Navigate to the Google Site Kit Dashboard.
* Paste the following code into the browser Dev Tools Console to remove any current GA4 or SC gathering data states:
```
googlesitekit.data.dispatch( 'modules/analytics-4' ).receiveIsGatheringData( false );
googlesitekit.data.dispatch( 'modules/search-console' ).receiveIsGatheringData( false );
```
* To validate that `72 hours` shows for "only GA4 gathering data state", paste the following snippet into the browser Dev Tools Console:
```
googlesitekit.data.dispatch( 'modules/analytics-4' ).receiveIsGatheringData( true );
```
* Validate that only the GA gathering state notification is present, with a correct value of `72 hours`.
* Clear the state once more using by pasting the following code into the browser Dev Tools Console:
```
googlesitekit.data.dispatch( 'modules/analytics-4' ).receiveIsGatheringData( false );
googlesitekit.data.dispatch( 'modules/search-console' ).receiveIsGatheringData( false );
```

* To validate that `48 hours` shows for "only SC gathering data state", paste the following snippet into the browser Dev Tools Console:
```
googlesitekit.data.dispatch( 'modules/search-console' ).receiveIsGatheringData( true );
```

* Validate that only the SC gathering state notification is present, with a correct value of `48 hours`.
* Clear the state once more using by pasting the following code into the browser Dev Tools Console:
```
googlesitekit.data.dispatch( 'modules/analytics-4' ).receiveIsGatheringData( false );
googlesitekit.data.dispatch( 'modules/search-console' ).receiveIsGatheringData( false );
```

* To validate that `72 hours` shows for "GA4 and SC gathering data states", paste the following snippet into the browser Dev Tools Console:
```
googlesitekit.data.dispatch( 'modules/analytics-4' ).receiveIsGatheringData( true );
googlesitekit.data.dispatch( 'modules/search-console' ).receiveIsGatheringData( true );
```

* Validate that both the GA4 and SC gathering states are visible in the notification, with a correct value of `72 hours`.

## Changelog entry

* Improve the "Gathering data" notifications to show the correct time based on the connected modules.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified all scenarios mentioned under QAB.
- Verified that the "Search Console is gathering data" notification  updated to display the figure of 48 hours. _"It can take up to 48 hours before stats show up for your site. While you’re waiting, connect more services to get more stats."_ .
- Verified that if only Analytics is in gathering data state then the figure remain at 72 hours.
- Verified that if both Analytics and SC is in gathering data state then also figure remains at 72 hours.

<details>

Analytics is in gathering data state.

![image](https://github.com/google/site-kit-wp/assets/94359491/1fa25fd5-dcd7-4ed5-b3af-40a800b4bf73)

Only Search console is in gathering data state.

![image](https://github.com/google/site-kit-wp/assets/94359491/a847c400-e22c-46a3-ab6a-4e1af070c242)

Both Analytics and SC is in gathering data state.

![image](https://github.com/google/site-kit-wp/assets/94359491/d281dc5b-ea69-449f-b107-49cf7ea18fbe)

Zero data state 

![image](https://github.com/google/site-kit-wp/assets/94359491/e63bffd3-5d5a-41fe-bdfc-1a2e10b479de)

</details>
