### ISSUE TITLE
Update definition of GA4 Reporting feature tour

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7879]
## Feature Description

The feature tour for `ga4Reporting` is currently implemented as an on-demand tour, but has a `version` partially defined which is only used for automatic tours. It currently references a version placeholder though which is incorrect, but also not hurting anything.

https://github.com/google/site-kit-wp/blob/bfd82b9dac98d7c91769c5f84dd5c70ac54b2981/assets/js/feature-tours/ga4-reporting.js#L46

We can set the version in case the tour ever moves to be implemented as an automatic tour, although it isn't strictly needed for now.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 reporting tour version should be set to `1.103.0`
* Any leftover related `TODO` comments for feature tours should be cleaned up ([example](https://github.com/google/site-kit-wp/blob/bfd82b9dac98d7c91769c5f84dd5c70ac54b2981/assets/js/feature-tours/dashboard-sharing.js#L39-L41))

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/7880

### Test Coverage

* No changes expected

## QA Brief

* The GA4 reporting feature tour should continue to be triggered as before 

## Changelog entry

* Update version used for GA4 feature tour.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
@aaemnnosttv I included `1.103.0` on the tester plugin under `Force initial Site Kit plugin version` but no tooltip tour was triggered. Since we've removed the `GA4Reporting` feature flag, I am unsure how I could test this. Any ideas? 🤔

**Comment by aaemnnosttv** [comment]
@wpdarren this issue doesn't change the way the tour works as it is still triggered on-demand as before. It essentially just cleans up a few references in our tour definitions. It should be testable in the same way as before.

**Comment by wpdarren** [comment]
@techanvil thank you. I did use the tester plugin for 1.103.0 but that didn't work.  I will do some more digging into this tomorrow and see if I can get it to work with upgrading.

**Comment by techanvil** [comment]
Thanks @wpdarren - you should set the version to an _earlier_ version than 1.103.0 though, so that could be worth checking again.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Verified that the GA4 feature tour still functions. 

https://github.com/google/site-kit-wp/assets/73545194/baf21703-6f07-4040-a876-6b5d8f6facb9
