### ISSUE TITLE
Move metrics tracking opt-in box above the Start Setup button 

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#788]
## Feature Description

Move the Tracking opt-in box above the "Start setup" button to help more users installing the plugin to notice it. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The opt-in tracking box should be displayed above the "start setup" button on the banner which appears after the user has clicked "activate" for the plugin in wp-admin. 
* The text size and checkbox remain exactly the same as described in #673 
* They should also appear immediately above the "start setup" button on the landing page (as described in #642 )

## Implementation Brief

![image](https://user-images.githubusercontent.com/1621608/68390173-62ddfd80-016d-11ea-9851-fd0663c7d573.png)

![image](https://user-images.githubusercontent.com/1621608/68389939-da5f5d00-016c-11ea-93a4-59b71dac85e9.png)

See #815 

## Changelog entry

* Move checkbox above submit button in setup screen and banner for better accessibility.

**Comment by swissspidy** [comment]
Yay for this accessibility improvement 👍

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested** 

Confirmed on setup the metrics tracking opt in box and copy are present and resizing browser width maintains copy, check box and padding
![image](https://user-images.githubusercontent.com/57115907/68833802-36444d00-0669-11ea-80dc-e55a848e928c.png)

Noticed on disconnected/reconnect page the padding between the start setup button and the metrics copy is a bit too close.
![image](https://user-images.githubusercontent.com/57115907/68833991-9affa780-0669-11ea-9a85-024432006301.png)

Bringing this up to the team and will file a bug if we decide this is worth the effort to adjust.

Ticket still passes QA ✅

**Comment by marrrmarrr** [comment]
The checkbox positioning LGTM. 
It should be unchecked by default on all relevant screens, in my tests with two sites I see it pre-checked on the screen which says "Site Kit is active, but requires setup"

<img width="1079" alt="Screenshot 2019-11-21 at 14 24 51" src="https://user-images.githubusercontent.com/13304791/69342259-6db78880-0c6b-11ea-9a5b-7a2679075b10.png">

**Comment by marrrmarrr** [comment]
on further investigation, this works on fresh sites.

**Comment by aaemnnosttv** [comment]
> It should be unchecked by default on all relevant screens, in my tests with two sites I see it pre-checked on the screen which says "Site Kit is active, but requires setup"

This is likely related to https://github.com/google/site-kit-wp/issues/728
