### ISSUE TITLE
Remove old feature tours.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7886]
## Feature Description

As discussed on [Slack](https://10up.slack.com/archives/C01CA828ZPZ/p1700499418758799?thread_ts=1700492190.872399&cid=C01CA828ZPZ), we can prune some of the old feature tours that are no longer likely to be triggered.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following feature tours should be removed:
  * All Traffic widget.
  * Help Visibility.
  * Unified Dashboard.

## Implementation Brief

* In `assets/js/feature-tours/index.js` remove imports for:
  * `helpVisibility`
  * `unifiedDashboard`
  * `allTrafficWidget`
* Remove their files

### Test Coverage

* There should't be any update needed as we do not have feature tours test coverage

## QA Brief

* Set up Site Kit and connect GA4.
* Ensure the following old feature tours aren't triggered:
  * All Traffic widget.
  * Help Visibility.
  * Unified Dashboard.

## Changelog entry

* Remove feature tours for old features.

**Comment by tofumatt** [comment]
IB ✅
