### ISSUE TITLE
Method not allowed / unable to send credentials to your WordPress site.

### ISSUE THREAD

**Issue by grzegorz-janoszka** [google/site-kit-wp#789]
## Bug Description

Every update of this plugin disconnects my site. Then I have troubles to connect again. Now sitekit.google.com displays "Method not allowed" or on the dashboard of the plugin I see "An error occurred: We were unable to send credentials to your WordPress site. Please go back to your site and restart the setup. The following error was returned: Only authenticated users can access the REST API."

I am logged in to my WP site and to my Google account. Clearing the process takes ages and doesn't help.

## Steps to reproduce

Upgrade the plugin.

 - PHP Version: 7.3 
 - OS: [e.g. iOS]: Debian Linux
 - Browser [e.g. chrome, safari]: Firefox
 - Plugin Version [e.g. 22]: latest
 - Device: [e.g. iPhone6]: Windows 7 and Windows 10.

It is very annoying.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@grzegorz-janoszka Thanks for reporting. Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
