### ISSUE TITLE
wp admin login "It appears you don't have permission to access this page. 403 Error. Forbidden."

### ISSUE THREAD

**Issue by Majharul6969** [google/site-kit-wp#7890]
I think my site seo spem
some days ago i can login and couldn't access and plugin access. I think my site has been hacked and is now being used for SEO spam. Some days ago, I was unable to login to my site and could not access any of my plugins. I believe that this is because the hacker has changed the login credentials and has disabled all of my plugins. I am currently working on restoring my site to its previous state.
site:domain.con
メンズ トップス パーカー 
![image](https://github.com/google/site-kit-wp/assets/116448472/2b1529a5-e9fa-4857-8225-561b0ec8b5cc)

**Comment by adamdunnage** [comment]
Hi @Majharul6969 Thanks for getting in touch and sorry to hear about the issue you are facing. We don't provide Site Kit support through GitHub so if you have an issue with the Site Kit plugin specifically, please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) with us and we will be happy to help!
