### ISSUE TITLE
Requests made for recoverable modules

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7891]
## Bug Description

When a module is in a recoverable state, this is something we know at the time the page is loaded so no components that depend on recoverable modules should be rendered or invoke report requests.

## Steps to reproduce

1. Set up analytics and share it with editors
2. With a different admin, set the Analytics module owner's user to be a non-admin role
3. Sign in with an editor and proceed to SK dashboard
4. See recoverable module state (correct)
5. See failed requests in console for GA4 reports (should not happen)

## Screenshots

<img width="1534" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/36097cdc-1bcb-4402-9f8c-cba36912d866">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Report requests in a view-only context should never be made for recoverable modules

## Implementation Brief

In `assets/js/googlesitekit/widgets/components/WidgetRenderer.js`:

* Modify the condition for returning `<WidgetNull />` to include an additional check. The updated condition should return `<WidgetNull />` if either the widget is not present (`! widget`) OR `widgetRecoverableModules` is `undefined`. This change ensures that the widget does not render until the status of recoverable modules is loaded.

### Test Coverage

* No new tests are required for this change.

## QA Brief

- Log in as admin and set up analytics and configure shared dashboard view with "editor" roles.
- Sign in with a different admin user.
- Via WordPress > Users, find the admin used in point 1 and change the role to "editor". 
- Log in in as an editor and proceed to SK dashboard.
- The GA4 widgets should be in a recoverable state as per the screenshot below:
<img width="1512" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/50c03db2-5a5d-45f1-81fd-8d38f3110cbc">
- There should be no failed requests to GA4 report endpoints. The below screenshot indicates the type of report request that should NOT be present within the dashboard:
<img width="1512" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/8019b148-1138-4563-b917-a5c0b7ed4dd1">

## Changelog entry

* Fix bug that caused console warnings to appear and requests to fail in certain module recovery scenarios.

**Comment by aaemnnosttv** [comment]
Looking at the relevant guard in `WidgetRenderer`, it seems that there are several renders where the list of `widgetRecoverableModules` is `undefined` which causes the underlying widgets to render and invoke their reports.

https://github.com/google/site-kit-wp/blob/87ca64284f21c63ac59bf3496c444a85aa854da2/assets/js/googlesitekit/widgets/components/WidgetRenderer.js#L76

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Able to reproduce on latest environment.
- Verified that on dev environment Report requests in a view-only context never made for recoverable modules


<details>

Latest-

![image](https://github.com/google/site-kit-wp/assets/94359491/be0e2f76-207a-4c66-a903-0d63e28e54a9)

Dev-

![image](https://github.com/google/site-kit-wp/assets/94359491/c5b966f9-8423-4abd-8c23-cd53ce25c571)


https://github.com/google/site-kit-wp/assets/94359491/33c86204-a61d-4ae4-8c42-eef2bbe2f77f

</detail>
