### ISSUE TITLE
Building VRT docker image fails when `ROOT_DIR` contains a space

### ISSUE THREAD

**Issue by derweili** [google/site-kit-wp#7898]
## Bug Description

When using a local environment like [Local](https://localwp.com/), WordPress lives in a `Local Sites` folder that has a space in it's name.

This space in the path name causes `bin/backstop` to fail building the docker image with following error:
```
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.
```

## Steps to reproduce

1. Clone the Site Kit repo in a folder with a space in its path and install the dependencies.
2. Verify the `googlesitekit/vrt:*` image does not exist on your machine.
3. Run `test:visualtest`
4. See the above error

## Additional Context

 - OS: macOS 14.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `bin/backstop` script (also callable via the `backstopjs` npm script) should run consistently regardless of the presence of whitespace in its absolute path to the file

## Implementation Brief

* Update `bin/backstop` to address all [ShellCheck](https://www.shellcheck.net/) errors and warnings, particularly https://www.shellcheck.net/wiki/SC2086

### Test Coverage

* No changes

## QA Brief

* Check out the Site Kit repo into a folder that contains a space "` `" character
* Run `docker rmi googlesitekit/vrt:6.1.1` to remove the VRT image from your system's Docker images
* Run `npm install`, then `npm run backstopjs` from the command line to build the docker image
* It should build without issue

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by 10upsimon** [comment]
### ENG:QA Update - Pass ✅

- ✅ Checked out into folder with space, `/Users/[REDACTED]/Downloads/sk test`
- ✅ Removed existing Backstop image
- ✅ Ran `npm install`
- ✅ Ran `npm run backstopjs`
- ✅ Image built with no problems and Backstop CLI welcome message was visible

<details>
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/4dabc146-a92e-4f23-a566-254a8bb858a2">
</details>
