### ISSUE TITLE
Plugin Site Not Loading - When Baqend Site Kit Installed (Cache / CDN) 

### ISSUE THREAD

**Issue by nerds-de** [google/site-kit-wp#790]
Plugins Site In Admin - Not Loading, when; 
- SiteKit by Baqend | CDN / Cache / Plugin Installed! 

Maybe other CachePlugins, Also?  JS. Files!

**Comment by nerds-de** [comment]
@https://github.com/Baqend

**Comment by jamesozzie** [comment]
@nerds-de Thanks for reporting. Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
