### ISSUE TITLE
Unknown Error (code: checking requirements failed).

### ISSUE THREAD

**Issue by alextovey** [google/site-kit-wp#791]
## Bug Description

when trying to connect to site kit for authentication we get this error.

Unknown Error (code: checking requirements failed).

## Steps to reproduce

1. Go to 'plugins type site kit and click on install'
2. Click on 'activate then click on start setup'
3. Scroll down to 'give authorisation then it redirects and then errors'

## Screenshots

https://ibb.co/Vv5n9QB

## Additional Context

 - PHP Version: 7.3
 - OS: Cloud Linux
 - Browser Chrome, Edge, Opera, I.e 8, Firefox
 - Plugin Version 1.0.1
 - Device: windows 10 laptop, Samsung tab a 10.1

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@alextovey Thanks for reporting Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
