### ISSUE TITLE
Add tertiary `Button` and replace use of `Link` for secondary CTAs.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7912]
## Feature Description

At present, we are using the `Link` component in secondary CTA contexts. For example, "I'll pick metrics myself" below is a secondary CTA. However it's rendered as a `Link`, and the styling is incorrect as a result.

![image](https://github.com/google/site-kit-wp/assets/18395600/e240ed00-53eb-46ec-8d0d-d75ce2011766)

To illustrate, here's the link in its hovered and focused states:

![image](https://github.com/google/site-kit-wp/assets/18395600/52d8781d-f6a0-4430-bb92-35283e3a8efa)

![image](https://github.com/google/site-kit-wp/assets/18395600/8bdfe3fb-2496-469a-9290-5f9540eec329)

This secondary CTA, and those like it should be in fact be rendered as a tertiary Button, as seen here in [Figma](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?type=design&node-id=409-2253&mode=design&t=wQuE6Q7zrmvkKUQs-0):

![image](https://github.com/google/site-kit-wp/assets/18395600/2e1c4c03-f1f8-4698-9515-38de8a5ff76a)

We should add this tertiary variant to our `Button` component, and replace all usage of `Link` in a secondary CTA context with a tertiary `Button`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The tertiary variant should be added to our `Button` component.
- It should follow the [Figma](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?type=design&node-id=409-2253&mode=design&t=wQuE6Q7zrmvkKUQs-0) design, with the exception of the black focus state outline. Seeing as the other `Button` variants don't yet implement this focus outline, it would be inconsistent to include it with the tertiary variant at this point. This will instead be addressed in a followup issue to further align the button styling with that in Figma.
- All use of `Link` in a secondary CTA context should be replaced with the tertiary `Button`.

#### Add tertiary Button

Within `assets/js/googlesitekit/components-gm2/Button.js`:
- Add a `tertiary` boolean prop to the `Button` component, defaulting to `false`.
- Conditionally add the class `mdc-button--tertiary` to the `Button`.

Within `assets/sass/vendor/_mdc-button.scss`:
- Implement the styling for `.mdc-button--tertiary`.
- Use the `mdc-button` [Sass Mixins](https://github.com/material-components/material-components-web/tree/v2.3.0/packages/mdc-button#sass-mixins), and further tweak the CSS as necessary to implement the button as per the AC.

Add the new Button variant to Storybook.

#### Replace usage of `Link` with tertiary `Button`

Replace the use of `Link` with the tertiary `Button` in the following locations. Additionally, do a diff from the commit 00aa54ff148d37648ff6c7cf3189a8dbafefbf6f to the current `HEAD` of `develop` to check for any relevant changes since this IB was authored:
- [`ModalDialog` Cancel](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/ModalDialog.js#L114)
- [`DashboardSharingDialog > Footer` Cancel](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/dashboard-sharing/DashboardSharingDialog/Footer/index.js#L148)
- [`KeyMetricsSetupCTAWidget` "I’ll pick metrics myself"](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js#L186)
- [`MetricsSelectionPanel > Footer` Cancel](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js#L272)
- [`WizardStepAuthentication` Back](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/legacy-setup/wizard-step-authentication.js#L84)
- [`GoogleTagIDMismatchNotification` "Keep existing property"](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/notifications/GoogleTagIDMismatchNotification.js#L197)
- [`BannerNotification > BannerActions` dismissal CTA](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/notifications/BannerNotification/BannerActions.js#L71)
- [`SettingsActiveModule > Footer` Cancel](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/settings/SettingsActiveModule/Footer.js#L228)
- [`SetupUsingProxyWithSignIn` "Skip sign-in and view limited dashboard"](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L401)
- [`CancelUserInputButton` Cancel](https://github.com/google/site-kit-wp/blob/a92636957ce393be24a10a7b03da7973e83e4df6/assets/js/components/user-input/CancelUserInputButton.js#L46)
- [`UserInputPreview` Back](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/user-input/UserInputPreview.js#L204)
- [`UserInputPreviewGroup` Cancel](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/user-input/UserInputPreviewGroup.js#L267)
- [`UserInputQuestionWrapper` Back](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/components/user-input/UserInputQuestionWrapper.js#L93)
- [`AdSenseConnectCTA` "Maybe later"](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/modules/adsense/components/common/AdSenseConnectCTA/index.js#L146)
- [`adsense > SetupAccountSiteUI` secondary CTA](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/modules/adsense/components/setup/v2/common/SetupAccountSiteUI.js#L64)
- [`analytics > AccountCreateLegacy` "Re-fetch My Account"](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/modules/analytics/components/common/AccountCreateLegacy.js#L118)
- [`analytics - AccountCreate` Back](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/modules/analytics/components/common/AccountCreate/index.js#L292)
- [`tagmanager > AccountCreate` "Re-fetch My Account"](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/modules/tagmanager/components/common/AccountCreate.js#L95)
- [`tagmanager > SetupForm` "Complete setup without Analytics"](https://github.com/google/site-kit-wp/blob/5570bf7cce5c35e3d4fe4d71947cbacd17563ffa/assets/js/modules/tagmanager/components/setup/SetupForm.js#L211)

### Test Coverage

* Update any failing tests.

## QA Brief

- Set up Site Kit.
- Observe the `Components` -> `Button` Storybook stories and verify that a tertiary variant is added. Verify that the tertiary variant meets the ACs and the FIgma designs.
- Run a smoke test and observe any areas of Site Kit that have a secondary CTA that appears as a link, e.g. banner notifications, CTA widgets, settings & setup screens, splash screen, etc. (you can use the list in the IB for some general directions). Verify that all the secondary CTAs now use the tertiary button variant.

## Changelog entry

* Improve appearance of secondary CTAs across the plugin.

**Comment by techanvil** [comment]
Note, see this [Slack thread](https://10up.slack.com/archives/C01CA828ZPZ/p1700743125754009) for potential additions to the in-progress IB.

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
Thanks for spotting @bethanylang! Have added an estimate.

**Comment by mohitwp** [comment]
<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/f7b16fae-387a-4e79-939e-c383509782b8)

![image](https://github.com/google/site-kit-wp/assets/94359491/43db5717-7321-4eb9-992f-4c5e263ddb97)

![image](https://github.com/google/site-kit-wp/assets/94359491/18c1a161-6dac-4c72-a36a-bc8a4f949090)

![image](https://github.com/google/site-kit-wp/assets/94359491/bb490d84-f473-4d9e-8ebc-046c8a570e43)

![image](https://github.com/google/site-kit-wp/assets/94359491/3454fa12-bff7-4e10-88bb-3cb6a7fc9a16)

![image](https://github.com/google/site-kit-wp/assets/94359491/37aaa5c0-2b9c-4a10-8dcc-12c6ba0278ca)

![image](https://github.com/google/site-kit-wp/assets/94359491/37f32f16-06de-4e82-a560-9a756e2d42e1)

![image](https://github.com/google/site-kit-wp/assets/94359491/cb045d8a-1925-45cd-9625-03bce5ba93d7)

![image](https://github.com/google/site-kit-wp/assets/94359491/e4e41fbc-5fef-49a3-a42b-bc826131cd07)

![image](https://github.com/google/site-kit-wp/assets/94359491/06c3a0f1-2e2d-48b1-bdbe-03605d63090f)

![image](https://github.com/google/site-kit-wp/assets/94359491/1e493caf-4d06-4cf9-bcee-66e0b4df8ace)

![image](https://github.com/google/site-kit-wp/assets/94359491/5c42b67e-5950-48a9-bcff-a33332e6b43a)

![image](https://github.com/google/site-kit-wp/assets/94359491/c5d7efe4-07db-4a52-8cec-9e6f0ac32ae0)


</details>

**Comment by nfmohit** [comment]
Hi @mohitwp!
Thank you for sharing your observation.

I have opened a [follow-up PR](https://github.com/google/site-kit-wp/pull/8067) that uses the tertiary button in the Key Metrics CTA widgets.

I have adjusted the vertical padding so that the CTA widget footer has the same height when using the button instead of the link, however, I'm a little confused about the spacing on the left of the button. Screenshots:

![image](https://github.com/google/site-kit-wp/assets/20284937/b7340780-6f05-4ab2-9ef6-e1cdd9e2fa15)

The horizontal padding in the footer is kept the same. The spacing just looks a bit big when the button is not hovered. It is more prominent on smaller devices. Screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/a7482383-7b72-4443-bffe-bfd14d2cf083)

@techanvil (as you had authored the ACs and IB), do you think it is necessary to reduce the left spacing of the button? If so, to what extent do you think would be a good spacing?

Thank you!

**Comment by techanvil** [comment]
Hey @nfmohit, please can you check with @sigal-teller on this one?

For reference, here's the [Slack thread](https://10up.slack.com/archives/C01CA828ZPZ/p1700743125754009) where we originally started talking about these buttons, and [here's](https://github.com/google/site-kit-wp/issues/7951) a related upcoming issue with some useful links e.g. this [document](https://docs.google.com/document/d/1s5R0dkPWUysUDuor0Plvr9zhcs1Xh2K6N1YojsXqFYI/edit#heading=h.myt9ggzhxa9o) mapping links/buttons to their types. This "Maybe later" link isn't explicitly mentioned but it looks like it should indeed be a tertiary button as it has the same sort of layout as the Ad Blocking Recovery setup's Cancel button which is mentioned. Anyhow, Sigal can confirm whether this should indeed be a tertiary button, and advise on how it should be presented in the mobile view.

**Comment by mohitwp** [comment]
@nfmohit Sharing few more screenshots for the buttons which are not mentioned under IB for your review to confirm if they require change or not. Thanks !
cc @tofumatt 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/50d4e624-bcbe-49bc-afb4-b0136423e56c)

![image](https://github.com/google/site-kit-wp/assets/94359491/d4b1f339-2482-4ebf-b39f-6c8215ec689a)

![image](https://github.com/google/site-kit-wp/assets/94359491/5134a4bb-25dd-46b8-8ccc-9484d28bcafe)

![image](https://github.com/google/site-kit-wp/assets/94359491/5aa1d5be-42bc-40bb-947e-44e5d4c93e37)

</details>

**Comment by aaemnnosttv** [comment]
The follow-up here shouldn't block the release – I believe @nfmohit has opened an issue for the remaining instances. Moving back to QA for the changes made here. @mohitwp

**Comment by nfmohit** [comment]
Hi @mohitwp!

I just opened a new issue #8072 that captures the observations and concerns that you've raised here. If you agree that the extent of implementation as part of #7912 doesn't block the release and #8072 covers all the additional instances where this refactor could potentially also happen, could we move this forward if there are no other concerns?

Thank you!

**Comment by mohitwp** [comment]
Thanks @nfmohit !

### QA Update ✅ 

- Tested on dev environment.
- Verified all areas for tertiary button update as per IB.
- Verified tertiary button on few more places.
- **Note** : For reported observations [above](https://github.com/google/site-kit-wp/issues/7912#issuecomment-1884573997) we have separate ticket https://github.com/google/site-kit-wp/issues/8072

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/f7b16fae-387a-4e79-939e-c383509782b8)

![image](https://github.com/google/site-kit-wp/assets/94359491/43db5717-7321-4eb9-992f-4c5e263ddb97)

![image](https://github.com/google/site-kit-wp/assets/94359491/18c1a161-6dac-4c72-a36a-bc8a4f949090)

![image](https://github.com/google/site-kit-wp/assets/94359491/bb490d84-f473-4d9e-8ebc-046c8a570e43)

![image](https://github.com/google/site-kit-wp/assets/94359491/3454fa12-bff7-4e10-88bb-3cb6a7fc9a16)

![image](https://github.com/google/site-kit-wp/assets/94359491/37aaa5c0-2b9c-4a10-8dcc-12c6ba0278ca)

![image](https://github.com/google/site-kit-wp/assets/94359491/37f32f16-06de-4e82-a560-9a756e2d42e1)

![image](https://github.com/google/site-kit-wp/assets/94359491/cb045d8a-1925-45cd-9625-03bce5ba93d7)

![image](https://github.com/google/site-kit-wp/assets/94359491/e4e41fbc-5fef-49a3-a42b-bc826131cd07)

![image](https://github.com/google/site-kit-wp/assets/94359491/06c3a0f1-2e2d-48b1-bdbe-03605d63090f)

![image](https://github.com/google/site-kit-wp/assets/94359491/1e493caf-4d06-4cf9-bcee-66e0b4df8ace)

![image](https://github.com/google/site-kit-wp/assets/94359491/5c42b67e-5950-48a9-bcff-a33332e6b43a)

![image](https://github.com/google/site-kit-wp/assets/94359491/c5d7efe4-07db-4a52-8cec-9e6f0ac32ae0)

![image](https://github.com/google/site-kit-wp/assets/94359491/204ff772-a76a-4701-a4df-d70731df92b5)

![image](https://github.com/google/site-kit-wp/assets/94359491/80dffe0d-9f78-479a-a477-7b6631d3c8b2)

![image](https://github.com/google/site-kit-wp/assets/94359491/0e385e1d-1ff0-4625-917d-35d29f6ea5c0)

![image](https://github.com/google/site-kit-wp/assets/94359491/c4a0cdaa-086e-410c-945d-4a16d1607b4c)

![image](https://github.com/google/site-kit-wp/assets/94359491/276829c3-8454-4bb3-b2dc-691db7f3d7a1)

![image](https://github.com/google/site-kit-wp/assets/94359491/72e399c1-7e79-482f-8300-8d39f2679055)

![image](https://github.com/google/site-kit-wp/assets/94359491/e3edcd51-fb4b-409f-bd25-aee95788de04)

![image](https://github.com/google/site-kit-wp/assets/94359491/54abcaaf-7aed-4628-86f9-04d2e6d11683)

![image](https://github.com/google/site-kit-wp/assets/94359491/26184ce7-a2a5-45a7-b2ba-00f5ab3cb6dd)


</details>
