### ISSUE TITLE
Option to use existing Search Console property for subdomains

### ISSUE THREAD

**Issue by ThomasKujawa** [google/site-kit-wp#792]
https://wordpress.org/support/topic/installation-in-subdirectory-2/#post-12087453
## Bug Description

Although there is a GSC property for the domain, a new property is created with the subdirectory.

I wouldn’t want that.

I want to use the data within the domain property.

Also, the links in the widget become erroneous after I have connected Analytics.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@ThomasKujawa Closing this as a duplicate of #325.
