### ISSUE TITLE
Add tests for User Input answers

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7922]
## Feature Description

A bug with the saving of User Input answers was discovered in #7892.

The fix involves changes to the PHP logic, but because it's a bug worth fixing quickly and there are [no tests for that file yet](https://10up.slack.com/archives/CBKKQEBR9/p1701156471687129), we decided to add the tests for the behaviour in #7892 separately.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tests for the fix added in #7892 should be added.
* Specifically, PHP unit tests should be added that ensure:
  *  Attribution for which user answered a site-wide question in the User Input questionnaire should only be updated when the chosen answer is changed upon saving (eg. the user who answered the question should be updated when the answer to that question is _changed_)
  * If the chosen answer is not changed when answers are updated, the previous user attribution should be preserved.

## Implementation Brief

* Update `tests/phpunit/integration/Core/User_Input/User_InputTest.php`
  * Add test case, say `test_set_answers__preserves_purpose_answer_user_attribution`, which will handle following scenario:
    * Create 2 admin users, and set 1st admin user as current user. See [this example](https://github.com/google/site-kit-wp/blob/88c7b617ecba970f0ac0e3763205e7f8dc3be7c5/tests/phpunit/integration/Core/Assets/AssetsTest.php#L178-L179)
    * Save initial answer settings. 
      * You can see the [example](https://github.com/google/site-kit-wp/blob/0c95ea52bf9a5690c29051b66bc547bf25ce8235/tests/phpunit/integration/Core/User_Input/REST_User_Input_ControllerTest.php#L101-L107) for setting the answers array
    * Use the `get_answers` method and extract `purpose` key.  
      * Confirm that `answeredBy` from extracted array is equal to created admin that is set as current user
    * Set 2nd admin as a current user
    * Use `set_answers` again with the same `purpose` value
    * Assert that `['purpose']['answeredBy']` is still attributed to the 1st admin
  * Add test case, say `test_set_answers__assigns_correct_user_attribution_on_purpose_answer_change`
     * Create 2 admin users like in previous test case
     * Set initial answers settings with 1st admin
     * Confirm that `answeredBy` is correctly attributed to the 1st admin 
     * Change current user to 2nd admin
     * Then set answers again, this time with different value for `purpose`, while 2nd admin is still set as current user
     * Assert that `purpose` `answeredBy` is now attributed to the 2nd admin

### Test Coverage

* No changes, IB is for the test

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
IB ✅

**Comment by bethanylang** [comment]
Noting that @zutigrm plans to include the fix for this in #7892. As discussed on stand-up, Aleksej, please close this out as as not planned once the PR on #7892 that includes this fix is ready. Thanks! cc @aaemnnosttv
