### ISSUE TITLE
Update `Analytics_4\Web_Tag` class to function independently

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7924]
## Feature Description

The `Analytics_4\Web_Tag` class extends the `Analytics\Web_Tag` class. The `Analytics_4\Web_Tag` class should be able to function and output tags independently without extending its `Analytics` counterpart.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Analytics_4\Web_Tag` class should no longer extend the `Analytics\Web_Tag` class.
* The `Analytics_4\Web_Tag` class should be able to function independently and output GA4 tags on its own.

## Implementation Brief

* Edit the existing GA4 `Web_Tag` class at `includes/Modules/Analytics_4/Web_Tag.php`
    * Alter the class definition to extend `Module_Web_Tag` and implement `Tag_Interface`, i,e `class Web_Tag extends Module_Web_Tag implements Tag_Interface`
    * Add a `use` statement for the applicable `Module_Web_Tag` class, i.e `use Google\Site_Kit\Core\Modules\Tags\Module_Web_Tag;`
    * Ass a `use` statement for the applicable `Tag_With_DNS_Prefetch_Trait` class, i.e `use Google\Site_Kit\Core\Tags\Tag_With_DNS_Prefetch_Trait;`
    * Add the `$home_domain;` property as a private property of the class, i.e `private $home_domain;`.
    * Add the `$anonymize_ip` property as a private property of the class, i.e `private $anonymize_ip;`.
    * Add the `$ads_conversion_id` property as a private property of the class, i.e `private $ads_conversion_id;`.
    * Copy the `set_home_domain()` method from the previously extended `Analytics/Web_Tag` class and add it as a newly defined method in this now standalone class.
    * Copy the `set_anonymize_ip()` method from the previously extended `Analytics/Web_Tag` class and add it as a newly defined method in this now standalone class.
    * Copy the `set_ads_conversion_id()` method from the previously extended `Analytics/Web_Tag` class and add it as a newly defined method in this now standalone class.
    * In the `register()` method:
        * Move over the filter for `wp_resource_hints` as this will no longer be called from a parent class.
    * Implement the required `render()` method (required by the interface) as this is no longer rendered in a parent class. The method should be a noop method and do nothing.
    * Update the `enqueue_gtag_script()` method:
        * Remove the conditional `did_action` check entirely and replace the contents of the method with the contents from the method in the previously extended Analytics/Web_Tag class (non GA4 one).
    * Add the `add_inline_config()` method from the `Analytics/Web_Tag` class to this class as we no longer want to call a parent implemented of it.
    * Update the `get_tag_config()` method:
        * Remove the call to `parent::get_tag_config()` 
        * Implement the logic of the previously extended/parent method `get_tag_config()` in `Analytics/Web_Tag`, i.e copy the contents from the once extended classes method into this method.
   * Validate that the GA4 tag output before and after the above changes are identical. This can be done by diffing the contents from the HTML comment starting at `<!-- Google Analytics snippet added by Site Kit -->` and ending at `<!-- End Google Analytics snippet added by Site Kit -->`.

### Test Coverage

* N/A - There appear to be no existing PHPUnit tests related to validation of GA4 (or UA) Web_Tag classes.

## QA Brief

* Configure GA4 within Site Kit
* Using a branch or version prior to this change, note the contents of the GA4 tag in the web site source, this would be the script tag contents between the HTML comments `<!-- Google Analytics snippet added by Site Kit -->` and `<!-- End Google Analytics snippet added by Site Kit -->`. 
* Using the branch/version containing the changes in said ticket, note the same script tag contents as in the prior step.
* Validate that the script contents are identical.
* Validate that GA4 tracking is functioning correctly, i.e realtime dashboard reporting is working. Note that you may need to be logged out to avoid the opt-out snippe taking effect (if logged in as WordPress admin).

### Additional QAB

1. Verify that the GA4 tag contains custom dimensions in singular pages if relevant key metrics are selected.
2. Verify that the GA4 tag contains ads conversion ID if set from the GA settings.
3. Use a site that had Analytics module set up with UA property. Verify that no UA tags (or duplicate GA tags) are output.

## Changelog entry

* Update the `Analytics_4\Web_Tag` class to function independently from the original Analytics `Web_Tag` class.

**Comment by tofumatt** [comment]
ACs 👍🏻

**Comment by eugene-manuilov** [comment]
Thanks, @10upsimon. IB mostly looks good to me. Could you please add test coverage information and set the estimate for this task?

**Comment by eugene-manuilov** [comment]
Thanks, @10upsimon. IB ✔️

**Comment by mohitwp** [comment]
@10upsimon As per QAB - "Using the branch/version containing the changes in said ticket, note the same script tag contents as in the prior step." As related PR is already merge in develop. Just wanted to confirm that I need to compare latest and dev branch in this case. Correct ?

**Comment by 10upsimon** [comment]
> @10upsimon As per QAB - "Using the branch/version containing the changes in said ticket, note the same script tag contents as in the prior step." As related PR is already merge in develop. Just wanted to confirm that I need to compare latest and dev branch in this case. Correct ?

That is correct @mohitwp

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified  that GA4 tracking is functioning correctly, i.e realtime dashboard reporting is working. 
- Verified that the contents of the GA4 tag in the web site source, i.e. the script tag contents between the HTML comments  and .are identical on latest and dev environment.
- Also, verified the script as website user. ( Non WP admin)

<details>

develop:

![image](https://github.com/google/site-kit-wp/assets/94359491/7643c495-0bf2-432f-b0e1-70617d0b9dfd)


Latest: 

![image](https://github.com/google/site-kit-wp/assets/94359491/611b7b0b-994a-4c2e-b722-32f964d62ed7)

</details>

**Comment by aaemnnosttv** [comment]
## ❌ Approval

After some testing and review, we've found a few regressions introduced by this issue, particularly for the case where UA settings are still present. See #8078.

Additionally, the ads conversion ID is no longer output if the UA tag is not being output.

We'll address this in a follow-up PR which will also remove any UA property tagging since this is no longer possible to manage or connect.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

As per QAB -
`Verify that the GA4 tag contains custom dimensions in singular pages if relevant key metrics are selected.`

- Connected GA4 property have custom dimensions. I have not completed user input questions or selected any key metrics widget but GA4 showing custom dimensions. Is this expected or CD should display only when key metrics widgets are selected ?


![image](https://github.com/google/site-kit-wp/assets/94359491/1432218e-9025-4eed-a66c-416d4101cdac)


![image](https://github.com/google/site-kit-wp/assets/94359491/3cfbb429-2db7-45ce-81b9-5b86f994b1c4)

**Comment by nfmohit** [comment]
> ### QA Update ⚠️
> As per QAB - `Verify that the GA4 tag contains custom dimensions in singular pages if relevant key metrics are selected.`
> 
> * Connected GA4 property have custom dimensions. I have not completed user input questions or selected any key metrics widget but GA4 showing custom dimensions. Is this expected or CD should display only when key metrics widgets are selected ?
> 
> ![image](https://private-user-images.githubusercontent.com/94359491/296709058-1432218e-9025-4eed-a66c-416d4101cdac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTA3ODYsIm5iZiI6MTcwNTMxMDQ4NiwicGF0aCI6Ii85NDM1OTQ5MS8yOTY3MDkwNTgtMTQzMjIxOGUtOTAyNS00ZWVkLWE2NmMtNDE2ZDQxMDFjZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4N2RjZDQ0MTY5OWIzODY1ODhmMjRjYTBkYjgyZGNmOWE0NWU1NjEyYjRhMTgzYWM4Y2Y0NzUzNTZmMzdiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI8Zf_tmVMK1Yu8s93tXPyGjV1Dx6yz4qBGTSsczUF0)
> 
> ![image](https://private-user-images.githubusercontent.com/94359491/296708052-3cfbb429-2db7-45ce-81b9-5b86f994b1c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTA3ODYsIm5iZiI6MTcwNTMxMDQ4NiwicGF0aCI6Ii85NDM1OTQ5MS8yOTY3MDgwNTItM2NmYmI0MjktMmRiNy00NWNlLTgxYjktNWI4NmY5OTRiMWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZTNkYjczNzA0MmNhOTIyMzJhZDNiNjEzOTY0OWFlNmQ1NDFlNGM4ZWQ0ZDBhZDgyYTgxOTM3MWRhNzA1NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3s2OoURoZQAmOxmM_3_nd3vZJTHPOjV_qSUW0rjE2-o)

Hi @mohitwp, that is expected when your GA4 property already has custom dimensions. Sorry, I probably shoul've clarified that in the QAB. Thanks for checking!
