### ISSUE TITLE
Update `Analytics_4\AMP_Tag` class to function independently

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7925]
## Feature Description

The `Analytics_4\AMP_Tag` class extends the `Analytics\AMP_Tag` class. The `Analytics_4\AMP_Tag` class should be able to function and output tags independently without extending its `Analytics` counterpart.

The `Analytics_4\AMP_Tag` class is currently only able to extend the UA AMP tag. It doesn’t output its own tag because there wasn’t any support for AMP with GA4 at the time of its addition.

However, [support for AMP has been introduced to GA4 recently](https://support.google.com/analytics/answer/13707678?hl=en), hence, the `Analytics_4\AMP_Tag` class should be updated to remove the dependency on UA, and output its own tag according to the [integration specification](https://developers.google.com/analytics/devguides/collection/amp-analytics/).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Analytics_4\AMP_Tag` class should no longer extend the `Analytics\AMP_Tag` class.
* The `Analytics_4\AMP_Tag` class should be able to function independently and output tags on its own.
* The `Analytics_4\AMP_Tag` class should no longer depend on the UA AMP tag. It should output the [GA4 AMP tag](https://support.google.com/analytics/answer/13707678?hl=en) according to the [GA4 & AMP integration specifications](https://developers.google.com/analytics/devguides/collection/amp-analytics/).

## Implementation Brief

* Modify `Google\Site_Kit\Modules\Analytics_4\AMP_Tag`
  * Currently it extends `Analytics_AMP_Tag`, replace it with `Module_AMP_Tag`
  * Include methods needed by `Tag_Interface`, you can leave them empty as they are not used with GA4, but keep [`set_home_domain`](https://github.com/google/site-kit-wp/blob/8d2b96bc0748a2d26446a5b4e86b8428d7a85970/includes/Modules/Analytics/AMP_Tag.php#L43-L52) implementation
  * Update `register` method
    * Replace current method body with the one from `Google\Site_Kit\Modules\Analytics\AMP_Tag::register`
  * Update `render` method
    * Use `Google\Site_Kit\Modules\Analytics\AMP_Tag::register` as starting point:
      * Remove `ads_conversion_id` logic, as it is not supported for GA4
      * Edit [`$gtag_amp_opt`](https://github.com/google/site-kit-wp/blob/8d2b96bc0748a2d26446a5b4e86b8428d7a85970/includes/Modules/Analytics/AMP_Tag.php#L117), remove `optoutElementId`
      * Rest can be kept, as it is the same for GA4
  * Update `get_tag_config` method
    * Move the code from `Google\Site_Kit\Modules\Analytics\AMP_Tag::get_tag_config` before current custom dimensions check
  * Remove `extend_gtag_opt` method as that approach is not used for sending data to multiple destinations in GA4
* In `includes/Modules/Analytics_4.php`
  * Edit `register_tag` method
    * Keep only `AMP_Tag` instance
    * Remove `$ua_settings` and it's usage

### Test Coverage

* Doesn't seem that update to the tests will be needed. 

## QA Brief

* This does not add, change or remove any featured, but refactors GA4 Tag placement for AMP. So it's worth checking the AMP tag still gets placed for AMP.

### Additional QAB

1. Verify that the GA4 AMP tag contains custom dimensions in singular pages if relevant key metrics are selected.
2. Verify that the GA4 AMP tag contains ads conversion ID if set from the GA settings.
3. Use a site that had Analytics module set up with UA property. Verify that no UA tags (or duplicate GA tags) are output.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Looks good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- I completed testing to ensure that the AMP tag appeared for GA4.   I ran this test with a new site with a new Analytics account. In addition, I tested this with a GA4 property with live data.  The correct AMP tag was generated in both scenarios, as shown in the example below. 

`<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json">{"vars":{"gtag_id":"G-XXXXXXXXXX","config":{"G-XXXXXXXXXX":{"groups":"default","linker":{"domains":["undresscrib.s4-tastewp.com"]}}}}}</script></amp-analytics>`
 
- I also tested Key Metrics with custom dimensions to ensure that the fields for the author, category, post date, and type appeared within the AMP tag as per below.

`<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json" data-ampdevmode="">{"vars":{"gtag_id":"G-XXXXXXXXXX","config":{"G-XXXXXXXXXX":{"groups":"default","linker":{"domains":["undresscrib.s4-tastewp.com"]},"googlesitekit_post_type":"post","googlesitekit_post_author":"dcronian","googlesitekit_post_date":"20200805","googlesitekit_post_categories":"Uncategorized"}}}}</script></amp-analytics>`

**Comment by aaemnnosttv** [comment]
## ❌ Approval

Similar to #7924, this issue introduces duplicate tagging for sites with UA still connected in the settings.

Also, the AMP tag no longer outputs the ads conversion ID which I see was removed intentionally from the IB, but this is inconsistent with the documentation https://developers.google.com/google-ads/amp/conversion-measurement#option_1_google_tag

Essentially, the AW ID is independent from GA4, but is only related here because of where the setting is exposed and the amp element that the config is provided in.

Finally, this issue removed the `optoutElementId` which should be kept for now.

**Comment by wpdarren** [comment]
### QA update: ✅ 

**Verified:**

- The AMP tag still gets placed for AMP.
- The GA4 AMP tag contains custom dimensions in singular pages if relevant key metrics are selected.
- The GA4 AMP tag contains ads conversion ID if set from the GA settings.
- No UA tags (or duplicate GA tags) are output.

AMP with GA4
`<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json">{"optoutElementId":"__gaOptOutExtension","vars":{"gtag_id":"G-XXXXXXXXXX","config":{"G-XXXXXXXXXX":{"groups":"default","linker":{"domains":["grubbyreading.s2-tastewp.com"]}}}}}</script></amp-analytics>`

AMP with GA4 and Ad Conversion ID
`<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json">{"optoutElementId":"__gaOptOutExtension","vars":{"gtag_id":"G-XXXXXXXXXX","config":{"G-XXXXXXXXXX":{"groups":"default","linker":{"domains":["grubbyreading.s2-tastewp.com"]}},"AW-3243":{"groups":"default"}}}}</script></amp-analytics>`
  
AMP with GA4 and custom dimensions
`<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json" data-ampdevmode="">{"optoutElementId":"__gaOptOutExtension","vars":{"gtag_id":"G-XXXXXXXXXX","config":{"G-XXXXXXXXXX":{"groups":"default","linker":{"domains":["grubbyreading.s2-tastewp.com"]},"googlesitekit_post_type":"post","googlesitekit_post_author":"dcronian","googlesitekit_post_date":"20200805","googlesitekit_post_categories":"Uncategorized"}}}}</script></amp-analytics>`
