### ISSUE TITLE
Update `analytics-4` `AccountSelect` component to save `accountID` for `analytics-4`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7927]
## Feature Description

[#7637](https://github.com/google/site-kit-wp/issues/7637) introduces a GA4 version of the Analytics `AccountSelect` component. It will select an Analytics account and save it for the `analytics` module's `accountID` setting.

[#7923](https://github.com/google/site-kit-wp/issues/7923) plans to introduce the `accountID` setting for the `analytics-4` module.

The GA4 version of the Analytics `AccountSelect` component should be updated to select an Analytics account and save it for the `analytics-4` module's `accountID` setting. This may also require extending the `analytics-4` datastore infrastructure (e.g. a `selectAccount` action).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `analytics-4` `AccountSelect` component should be updated to use datastore infrastructure only from the `analytics-4` datastore.
- It should allow selecting an Analytics account and store the account ID in the relevant module setting (`accountID`) in the `analytics-4` datastore.

## Implementation Brief

* In `assets/js/modules/analytics-4/datastore/accounts.js`
  * Update Reducer to include `START_SELECTING_ACCOUNT` and `FINISH_SELECTING_ACCOUNT`, move them from `MODULES_ANALYTICS` store reducer
  * Add `selectAccount` action. Adapt it from `MODULES_ANALYTICS` `selectAccount` action, with following changes:
    * `setSettings` should be dispatched from `MODULES_ANALYTICS_4` store, and keep only setting `accountID` as other properties are not used anymore, and `propertyID` is reset as part of `matchAndSelectProperty` action
    * Remove `uaProperty` related code
    * Keep the dispatch of `matchAndSelectProperty` as it is used for setting the matched property. But instead of assigning the value to the `ga4Property` variable, just await for action to complete
    * Remove `setPrimaryPropertyType`, as this is always going to be GA4
* Remove the `getPrimaryPropertyType` selector, and it's usage, from `assets/js/modules/analytics/components/common/PropertySelectIncludingGA4.js`
* In `assets/js/modules/analytics-4/components/common/AccountSelect.js` Update `selectAccount` action to be used from `MODULES_ANALYTICS_4` store

### Test Coverage

* Add `selectAccount` test to the `assets/js/modules/analytics-4/datastore/accounts.test.js`
* Update tests for `AccountSelect` component
* Remove `getPrimaryPropertyType` related tests/usage from `assets/js/modules/analytics/components/common/PropertySelectIncludingGA4.test.js`

## QA Brief

* Ensure that setting up Analytics module, and editing the settings still work properly
* Do overall smoke testing of the plugin to ensure everything works as expected

### QA:Eng

* Verify that when setting up Analytics, and editing its settings, the `AccountSelect` component also sets the `accountID` module setting for `analytics-4`.

## Changelog entry

* Update the Analytics module to save the user's account ID in the new Analytics 4 module settings.

**Comment by tofumatt** [comment]
ACs here are good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
@zutigrm, when a user select a new account and when the `selectAccount` action is called, we should automatically pre-select everything else if we can find matching property. Currently, this is implemented when we call the `matchAndSelectProperty` action from the `analytics-4` module. But since in the new action we don't need to set the property type anymore, we can just call the `matchAndSelectProperty` action and ignore returning results.

**Comment by zutigrm** [comment]
@eugene-manuilov Ah I see what you mean, I initially thought to leave it to `getAccounts` to handle pre-selection, but we need `matchAndSelectProperty` as well. Thank you, I updated the IB

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. IB ✔️

**Comment by zutigrm** [comment]
Waiting on #7637 to be merged to update `AccountSelect` component and apply/add changed to the component tests

**Comment by hussain-t** [comment]
### QA Eng Verified ✅ 

* Verified that during the setup process of Analytics, the `AccountSelect` component successfully sets the `accountID` for `analytics-4`.
* Verified that the `AccountSelect` component appropriately sets the `accountID` for `analytics-4` when editing Analytics settings.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified Analytics set up on new site using new and old analytics a/c. 
- Verified on a site which connected through UA property.
- Verified analytics settings view and edit mode.
- Verified analytics setup on old site using old analytics a/c.
- Ensure that setup new property drop down and related functionality are working.
- Verified that analytics snippet is showing correctly under page source.
- Verified that UA tags are not showing on updating to dev environment.
- Verified that if GA4  property have custom dimensions then they are appearing under Analytics snippet.
- Verified that ad conversion id showing under Analytics snippet.

![image](https://github.com/google/site-kit-wp/assets/94359491/db0b3543-8946-4388-8c08-5f051dd7e932)
