### ISSUE TITLE
Create a GA4 version of `AccountCreate`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7928]
## Feature Description

A GA4 version of the `AccountCreate` component should be created based on the existing `AccountCreate` component, that creates an Analytics account (saved to `accountID` setting in `analytics-4` module), property, and web data stream using data store infrastructure from `analytics-4`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `AccountCreate` component should be created within `assets/js/modules/analytics-4/components/common/AccountCreate/`.
* This new component should achieve the same functionality as the current `assets/js/modules/analytics/components/common/AccountCreate/` component and its child components but should solely rely on the `analytics-4` datastore.
    * The `getAccounts` selector for the `modules/analytics` datastore will have to be copied to the `modules/analytics-4` datastore.
* All components, child components or associated code used solely for the `analytics` (Universal Analytics) module should NOT be copied over, e.g. the `<ProfileField>` component.
* While the usage of this component should not be updated as part of this issue, it may be tested by replacing the existing `AccountCreate` component used within the `SetupMain` and the `SettingsEdit` components which themselves will be copied over in issues #7929 and #7930.
* A new Storybook story should be added.

## Implementation Brief

* Copy over the original `AccountCreate` component from the analytics module into the analytics-4 module with the following changes:
  * Remove the `StoreErrorNotices` element for the analytics module.
  * Don't copy the `ProfileField.js` file as it is not needed.
  * Use the GA4 version of the `getAccounts` selector to get accounts.
  * Use the GA4 version of the `rollbackSettings` action to revert changes in the `handleBack` callback.
  * Copy over any constant that exists in the analytics module but doesn't in analytics-4 and used in the `AccountCreate` component.
* Add new storybook stories for the new component.

### Test Coverage

* Copy existing tests for the original `AccountCreate` component adopting it to the new version.

## QA Brief

* Regression test: The code from this issue will not technically be "used" until #7929 or #7930 are merged. However, ensure GA4 can still be setup and connected from scratch and a new Account can be created from within the plugin.
* Check the new Storybook story within Modules -> Analytics4 -> Components -> AccountCreate.

### QA Eng

* Within `assets/js/modules/analytics/components/setup/SetupMain.js` and `assets/js/modules/analytics/components/settings/SettingsEdit.js`, modify the import for the `AccountCreate` component and verify that a new Account can be created. 

## Changelog entry

* Add the Analytics 4 version of the Analytics new account creation form component.

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by nfmohit** [comment]
@jimmymadon @techanvil @eugene-manuilov I think it would also be nice to create a GA4 version of `AccountCreateLegacy` while we're at it, as we plan to completely erase the `analytics` module soon and we'll likely need this component. What do you think?

**Comment by techanvil** [comment]
@nfmohit that SGTM, please can you create an issue for it?

**Comment by tofumatt** [comment]
I thought the `AccountCreateLegacy` was for creating an account without our APIs/flows to automatically guide the user through account creation.

I'm not sure we need that going forward, since we automatically create an account for the user if needed, right? 🤔

**Comment by hussain-t** [comment]
@jimmymadon, we are not creating the GA4 version of the `getAccounts` selector, as it has many side effects. We are using the existing `getAccountSummaries` to get the accounts and properties and introduced a new action, `findMatchedAccount`, to find the matched account and property. Please refer to this [comment](https://github.com/google/site-kit-wp/pull/7966#discussion_r1432862162) for more details.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Tested on dev environment.
Verified GA4 setup. 
Verified setup of all modules.
Verified that user is able to create new GA4 account.
Verified that user is able to create new GA4 property. 
Verified that user is able to connect/disconnect analytics.
Verified  Storybook story within Modules -> Analytics4 -> Components -> AccountCreate.

**Note** :  This ticket is ready for `QA:Eng` review.

<details>


https://github.com/google/site-kit-wp/assets/94359491/3a00453d-181d-41ca-b1ad-12c8b824ae1e

</details>

**Comment by hussain-t** [comment]
### QA Eng Verified ✅ 

* Verified creating accounts using the new GA4 `AccountCreate` component from the **Setup** screen.
* Verified creating accounts using the new GA4 `AccountCreate` component from the **Settings Edit** screen.
* Verified that the accounts and properties created through this process are appropriately listed and accessible in the Analytics console.
