### ISSUE TITLE
Create setup component for `analytics-4`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7929]
## Feature Description

A setup component should be created for `analytics-4` based on `analytics` `SetupMain`. It should set up the `analytics-4` module with datastore infrastructure and module settings from `analytics-4`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `SetupMain` component should be created within `assets/js/modules/analytics-4/components/setup/`.
* This new component should achieve the same functionality as the current `assets/js/modules/analytics/components/setup/SetupMain` component and its child components but should solely rely on the `analytics-4` datastore.
    * The `getAccounts` selector for the `modules/analytics` datastore should now use the same selector within the `modules/analytics-4` datastore (it should have been copied over in Issue #7928).
* The new component should use the new `AccountCreate` component migrated in Issue #7928.
* All components, child components or associated code used solely for the `analytics` (Universal Analytics) module should NOT be copied over. Where there are two versions of a component, the GA4 version should be the sole version copied over with all GA4 suffixes dropped, e.g. only the `<SetupFormGA4>` component should be copied over and used appropriately but renamed to `<SetupForm>`.
* Modify the registration of the Analytics 4 module to use this component as the `SetupComponent` (within `assets/js/modules/analytics-4/index.js`).
* A new Storybook story should be added.

## Implementation Brief

- Create a copy of the `analytics` `hasFinishedLoadingGTMContainers` selector in the `analytics-4` datastore, preferably in a new partial, e.g. `tagmanager.js`.
- Copy over the following files from `assets/js/modules/analytics/components/setup` to `assets/js/modules/analytics-4/components/setup`:
	- `SetupMain.js`
	- `SetupForm.js`
	- `SetupForm.test.js`
	- `SetupFormGA4.stories.js` renamed to `SetupForm.stories.js`.
- In `assets/js/modules/analytics-4/components/setup/SetupMain.js`:
	- Replace all imports from the `analytics` module with their `analytics-4` counterparts.
	- Replace all usages of selectors from the `analytics` datastore with their `analytics-4` counterparts.
	- Remove usage of the `analytics` `getSetupFlowMode` selector.
	- Remove usage of the `useExistingTagEffectUA` hook.
- In `assets/js/modules/analytics-4/components/setup/SetupForm.js`:
	- Replace all imports from the `analytics` module with their `analytics-4` counterparts.
	- Replace all usages of selectors from the `analytics` datastore with their `analytics-4` counterparts.
	- Remove usages of the `analytics` `canSubmitChanges` and `getSetupFlowMode` selectors.
	- Remove the definition and usages of the `isUAEnabled` variable.
	- Use the `submitChanges` action from the `analytics-4` datastore instead of `analytics`.
	- Rename `canSubmitGA4Changes` to `canSubmitChanges`.
	- Remove the `<StoreErrorNotices>` component for the `analytics` module.
	- In the rendered component, replace the `<SetupFormUA>`/`<SetupFormGA4>` components with contents of the `<SetupFormGA4>` component located in `assets/js/modules/analytics/components/setup/SetupFormGA4`.
		- In the code being copied, replace all usages of selectors from the `analytics` datastore with their `analytics-4` counterparts.
		- It is no longer necessary to use aliases for the GA4 components, e.g. `GA4PropertySelect` can just be `PropertySelect`.
- In `assets/js/modules/analytics-4/index.js`:
	- Update the module registration for `analytics-4` to use the new `analytics-4` `SetupMain` component as the `SetupComponent` (see `assets/js/modules/analytics/index.js` for example).
- In `assets/js/modules/analytics-4/components/setup/SetupForm.stories.js`:
	- Replace all mentions of `SetupFormGA4` with `SetupForm`.
	- Remove any UA-relevant stories.
	- Replace any usages of the `analytics` datastore with `analytics-4`.
	- Fix any broken stories.

### Test Coverage

- In `assets/js/modules/analytics-4/components/setup/SetupForm.test.js`:
	- Update the test cases in light of the above changes.
	- Remove any UA-relevant tests.
	- Fix any failing tests.

## QA Brief

In this instance only `QA:Eng` can be done.  New `SetupForm` story can't be tested, as it needs some legacy store data that is not present purely in `analytics-4` datastore.

#### QA:Eng

* In `assets/js/modules/analytics/index.js` update the import for `SetupMain ` component to be imported from `../../../analytics-4/components/setup'`
* On Setup Analytics module page
  * If reference URL is set in tester plugin, put `googlesitekit.data.select('modules/analytics-4').getSettings()` in console, verify that `accountID`, `propertyID`, and `WebDataStreamID` are pre-populated in the datastore
* Change between account, property, web data streams, and verify that `analytics-4` datastore data is properly updated
* Setup the analytics with existing account/property and verify that `analytics-4` datastore data is preserved/saved. 
* Choose to create a new property/web data stream, and verify that `analytics-4` datastore data is preserved/saved. 
* Note: After completing the setup for analytics going to Analytics settings will not work, Account ID will be blank, and error will be shown if settings are edited. This is expected as there is no fallback saving the `accountID` to the old `analytics` store, only to `analytics-4` and `check-access` is connected to the old store, so errors of this type across the dashboard if present are expected.
* Also when on the setup analytics screen account/property options will not get preselected as matched property is still relying on old analytics datastore as well as select components. To test this, update `PropertySelect` and `WebDataStreamSelect` components to use `accountID` from `MODULES_ANALYTICS_4`. This will come together in final issue [7932](https://github.com/google/site-kit-wp/issues/7932) which will make the switch to GA4 components to be used instead of the ones from old module, including the remaining datastore update.

## Changelog entry

* Create module setup component for Analytics 4.

**Comment by techanvil** [comment]
Hey @jimmymadon, this AC is looking good. One point, do you think it's worth mentioning that we should use the new version of `AccountCreate`, just to be clear?

**Comment by techanvil** [comment]
Thanks @jimmymadon! AC :white_check_mark:

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by nfmohit** [comment]
@zutigrm @jimmymadon Co-assigned you folks as I need a little feedback in the PR [here](https://github.com/google/site-kit-wp/pull/8090#discussion_r1470808484). Thanks!

**Comment by hussain-t** [comment]
Hi @zutigrm,

I've noticed that the property and web data stream dropdowns aren't loaded on the initial setup page. This issue seems to be because the `PropertySelect` and `WebDataStreamSelect` components currently reference the UA `accountID`. To resolve this, could you please update the QAB to use the `accountID` from `MODULES_ANALYTICS_4` instead?

Additionally, please note in the QAB that this adjustment aligns with the changes planned in [#7932](https://github.com/google/site-kit-wp/issues/7932). 

![Screenshot 2024-02-01 at 6 23 07 PM](https://github.com/google/site-kit-wp/assets/24408261/44767d77-26d3-449e-ae7c-ac22cfd32ff2)

Thanks!

cc: @nfmohit @wpdarren

**Comment by wpdarren** [comment]
Thanks for testing this @hussain-t 👍 

I have moved this to approval due to the notice on the QAB:

> In this instance only QA:Eng can be done. New SetupForm story can't be tested, as it needs some legacy store data that is not present purely in analytics-4 datastore.
