### ISSUE TITLE
Create settings view component for `analytics-4`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7931]
## Feature Description

A settings view component should be created for `analytics-4` based on `analytics` `SettingsView`. It should allow viewing settings for the `analytics-4` module with datastore infrastructure and module settings from `analytics-4`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `SettingsView` component should be created within `assets/js/modules/analytics-4/components/settings/`.
* This new component should achieve the same functionality as the current `assets/js/modules/analytics/components/settings/SettingsView` component and its child components but should solely rely on the `analytics-4` datastore.
* All components, child components or associated code used solely for the `analytics` (Universal Analytics) module should NOT be copied over. 
* Modify the registration of the Analytics 4 module to use this component as the `SettingsViewComponent` (`within assets/js/modules/analytics-4/index.js`).
* A new Storybook story should be added.

## Implementation Brief

- Copy over the following files from `assets/js/modules/analytics/components/settings` to `assets/js/modules/analytics-4/components/settings`:
	- `SettingsView.js`
	- `OptionalSettingsView.js`
	- `SettingsView.stories.js`
- In `assets/js/modules/analytics-4/components/settings/SettingsView.js`:
	- Remove the `<StoreErrorNotices>` component for the `analytics` module.
	- Replace the rendered `<GA4SettingsView>` component with actual contents of the component copied over from `assets/js/modules/analytics/components/settings/GA4SettingsView.js`.
		- In the code being copied, replace all usages of selectors from the `analytics` datastore with their `analytics-4` counterparts.
		- It is no longer necessary to use `ga4` as a prefix/identifier for variables, e.g. `ga4PropertyID`, `ga4MeasurementID`, and `useGA4Snippet` can just be `propertyID`, `measurementID`, and `useSnippet` respectively.
		- The setting labels and screen reader text no longer need `Google Analytics 4` to indicate GA4 settings, as GA4 is the only version of Analytics Site Kit currently supports, e.g. `Google Analytics 4 Property` can just be `Property`.
- In `assets/js/modules/analytics-4/components/settings/OptionalSettingsView.js`:
	- The `getCanUseSnippet` selector should be used from the `analytics-4` datastore instead of `analytics`.
	- The following variable definitions and their usages should be removed:
		- `useSnippet`
		- `propertyID`
		- `isUAConnected`
		- `anonymizeIP`
		- `ampMode`
		- `showIPAnonymizationSettings`
	- Any code rendered based on the `showIPAnonymizationSettings` condition should be removed.
	- Replace any other usages of selectors from the `analytics` datastore with their `analytics-4` counterparts.
	- The `useGA4Snippet` variable can be renamed to `useSnippet`.
- In `assets/js/modules/analytics-4/components/settings/SettingsView.stories.js`
	- Remove any UA-relevant stories.
	- Replace any usages of the `analytics` datastore with `analytics-4`.
	- Fix any broken stories.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Regression test: The code from this issue will not technically be "used" until #7932 is merged. This is because the Analytics 4 module does not have its own settings row within Admin Settings. However, ensure GA4 can still be setup and connected from scratch. Verify that viewing the settings now does work correctly.
* Check the new Storybook story within Modules -> Analytics4 -> Settings -> SettingsView.

### QA Eng

* Within `includes/Modules/Analytics_4.php`, within the `setup_info()` method, set `internal` to `false`. Now go to the Settings Admin screen and you will see a row for Analytics 4. Ensure the SettingsView component is rendered correctly.  
* Note: The `accountID` is still being set for the `analytics` datastore instead of `analytics-4`. So this field will be blank until we finish issues #7929 and #7930 which deal with migrating the `Setup` and `SettingsEdit` components. These issues should save the `accountID` for the analytics-4 datastore.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
ACs here look good, moving to IB 👍🏻

**Comment by techanvil** [comment]
IB LGTM :white_check_mark: 

@nfmohit, please can you add an estimate?

**Comment by nfmohit** [comment]
> @nfmohit, please can you add an estimate?

Added, thank you @techanvil !

**Comment by techanvil** [comment]
Thanks @nfmohit! Over to the EB it goes.

**Comment by hussain-t** [comment]
## QA Eng Verified ✅ 

* Verified that the Analytics 4 settings view is correctly rendered when `Analytics_4::setup_info()->internal` is set to `false`.
* Verified that the Account (ID) field within the settings view is currently unpopulated, aligning with the ongoing implementation.

![Screenshot 2024-01-19 at 5 37 09 PM](https://github.com/google/site-kit-wp/assets/24408261/00fe1e66-9ef1-4e05-8e3f-b12d1eef905d)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- GA4 can still be setup and connected for a new site and Analytics account. 
- Checked Analytics settings view and found now issues:
  - Checked that I could create a new account, property and web data stream in settings edit. 
  - Checked that the Analytics still functioned on settings view. 
 - After setting up Site Kit and GA4 for the first time I reset Site Kit made sure that I could connect the same account, and that it defaulted on the connect service screen. 
 - I reset Site Kit again and made sure that I could set up Site Kit and a create a different account and property. 
- Checked the new Storybook story within Modules -> Analytics4 -> Settings -> SettingsView.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/1041c2cc-c3f7-4dae-b53c-28f1cd9ed3c1)
![image](https://github.com/google/site-kit-wp/assets/73545194/643a7452-924d-4a8f-97f1-45865677620c)
![image](https://github.com/google/site-kit-wp/assets/73545194/a65ef217-61e0-4731-ba5b-644fba3a4ed0)

</details>
