### ISSUE TITLE
Replace the `analytics` module with `analytics-4`

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7932]
## Feature Description

The `analytics` module should be replaced with `analytics-4` completely. This should notably include:

1. For components and datastore infrastructure still retrieving settings from the `analytics` module, update them so that they retrieve such module settings from the `analytics-4` module instead.
2. Replace all references to any user-facing string `Analytics 4` with `Analytics`.
3. Remove any special handling for the `analytics-4` module.
4. Remove module and datastore registration for `analytics`.
5. Turn off the `internal` flag for the `analytics-4` module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any remaining usage of the `analytics` datastore infrastructure should be used with their respective counterpart from `analytics-4`.
* Any user-facing reference to `Analytics 4` should be replaced with `Analytics`.
* Any special handling for the `analytics-4` module should be removed (notably in regards to module activation/connection logic & dashboard sharing).
* Module & datastore registration for the `analytics` module should be removed.
* The `internal` flag should be removed for the `analytics-4` module.

#### Datastore and frontend changes

* Replace selectors using `MODULES_ANALYTICS` store to use `MODULES_ANALYTICS_4` store in relevant components. You can run a search for `( MODULES_ANALYTICS )` in your IDE
* In `assets/js/modules/analytics/components/settings/OptionalSettingsView.js`:
  * Remove `isUAConnected` and `anonymizeIP` variables and their usage.
  * Remove current `useSnippet` selector and rename `useGA4Snippet` to `useSnippet`
  * Update current selectors using `MODULES_ANALYTICS` to use Analytics 4 store
  * Remove `showIPAnonymizationSettings` variable and it's usage
* Move `getServiceURL` selector from `assets/js/modules/analytics/datastore/service.js` to the `assets/js/modules/analytics-4/datastore/service.js` and update the usage, so it is selected from Analytics 4 store
* Copy any remaining files (not already migrated) to the analytics-4 counterpart folder: 
  * `assets/js/modules/analytics/components/settings/`.
  * `assets/js/modules/analytics/components/common/`
  * `assets/js/modules/analytics/components/setup/`
  * `assets/js/modules/analytics/components/dashboard`
  * `assets/js/modules/analytics/components/module`
* Move the `assets/js/modules/analytics/util/countries-data.js` and `assets/js/modules/analytics/util/countries-timezones.js` in case it is not migrated as part of [#7928](https://github.com/google/site-kit-wp/issues/7928)
* Also move `assets/js/modules/analytics/util/parseDimensionStringToDate.js` and it's test to the analytics 4 module utils folder
* Move `assets/js/modules/analytics/datastore/__factories__` to the analytics 4 module datastore, and update it's imports
* Rename, by excluding `GA4` from their name - `isGA4Connected`, `ga4Connected`, `ga4SnippetEnabled` and `useGA4Snippet` selectors and re-visit their usage
* Search through the codebase for `Analytics 4` string, and replace it with `Analytics` in relevant user facing places
* Search for filename in IDE, and look for files ending in `GA4.js`, remove old analytics widget that have analytics 4 counterpart and remove `GA4` from analytics 4 widgets name
* Remove usage, of old analytics, or replace it with `analytics-4`, where it is not needed across the remaining files. You can search for `slug: 'analytics'`, `moduleSlug="analytics"`, `isModuleConnected( 'analytics' )`, `moduleName: 'analytics'`, `modules: [ 'analytics' ]` and lastly `analytics`.
* From `assets/js/modules/analytics/index.js`, move the `GA4` widgets registration to the `assets/js/modules/analytics-4/index.js`
* Remove `assets/js/googlesitekit-modules-analytics.js` file and remove it's use from webpack `entry`
* Remove `assets/js/modules/analytics/`

#### Backend changes

* In `includes/Modules/Tag_Manager.php`
  * Remove conditional [dependency](https://github.com/google/site-kit-wp/blob/091807c96ac7c8b4ca1949cfd9b5e9477fbf2330/includes/Modules/Tag_Manager.php#L526-L530) for `analytics`
* In `includes/Core/Modules/Modules.php`
  * Replace `Analytics` with `Analytics_4` in [`$core_modules`](https://github.com/google/site-kit-wp/blob/1ce01bdfff9e0808e262eb83127d584a45387f03/includes/Core/Modules/Modules.php#L150) variable, and remove it from `construct`
  * Replace the use of `Analytics` class with `Analytics_4` throughout the file
    * And in `is_module_connected`, `activate_module`, `set_active_modules_option` methods
      * Remove the inline to-do comments where applicable and modify condition to account for `Analytics_4` being the only module
* Edit `includes/Core/Modules/REST_Modules_Controller.php`
  * In `get_rest_routes` method
    * Remove this [`Analytics_4`](https://github.com/google/site-kit-wp/blob/1ce01bdfff9e0808e262eb83127d584a45387f03/includes/Core/Modules/REST_Modules_Controller.php#L708-L727) check, as owner settings are transferred to analytics 4 in [#7923](https://github.com/google/site-kit-wp/issues/7923)
* In `includes/Modules/Analytics_4.php`
  * Update `setup_info` method:
    * Set `internal` to `false`
    * Remove `depends_on`
  * In `replicate_analytics_sharing_settings` method
    * Replace `Analytics` class with `Analytics_4`
  * Search throughout the file for `Analytics::` and replace with `Analytics_4`
  * Modify `is_connected` method
    * Uncomment `accountID`, and remove comment and  `adsConversionID` property
* Remove `includes/Modules/Analytics.php`
* Remove `includes/Modules/Analytics/`

### Test Coverage

* Remove any remaining irrelevant UA related stories and tests that have `GA4` counterpart
* Replace `analytics` module slug with `analytics-4` in tests and stories e.g. in `provideModules`
* Replace `analytics` with `analytics-4` in fixtures for module slug, where applicable, and set `internal` to true in `assets/js/googlesitekit/modules/datastore/__fixtures__/list.json`
* Migrate any remaining relevant php tests revolving around old `Analytics` class to the `Analytics_4Test` and update `Analytics_4Test` - replace `Analytics::` usage, etc
* Fix any failing tests

## QA Brief

* Go through the whole Analytics flow, and verify everything is still working as intended

## Changelog entry

* Replace the legacy `analytics` module with `analytics-4`.

**Comment by tofumatt** [comment]
ACs look good here 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
Hi @zutigrm,

I've noticed that the property and web data stream dropdowns aren't loaded on the initial setup page. This issue seems to be because the `PropertySelect` and `WebDataStreamSelect` components currently reference the UA `accountID`. To resolve this, could you please update the QAB to use the `accountID` from `MODULES_ANALYTICS_4` instead?

Additionally, please note in the QAB that this adjustment aligns with the changes planned in [#7932](https://github.com/google/site-kit-wp/issues/7932). 

![Screenshot 2024-02-01 at 6 23 07 PM](https://github.com/google/site-kit-wp/assets/24408261/44767d77-26d3-449e-ae7c-ac22cfd32ff2)

Thanks!

cc: @nfmohit @wpdarren

**Comment by nfmohit** [comment]
I have reviewed [the PR](https://github.com/google/site-kit-wp/pull/8234) for this issue and have left my CR feedback. The feedback is quite extensive, which I think is understandable provided it is a massive refactoring PR. Most of my points are small, with some moderate.

However, I have a couple of other concerns that have come up after observing the upcoming outcome of #7932 that doesn't directly relate to #7932 itself, but the entire SAM initiative overall.

1. The `googlesitekit_active_modules` option (that holds a list of currently active modules) never included `analytics-4`. `analytics-4` was only considered active based on a "hacky" logic conditionally if the `analytics` module was active. [See method](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Core/Modules/Modules.php#L845-L871).
&nbsp;
Now that we're removing all similar "hacks" with an intention to simplify logic and reduce future technical debt, when the `analytics` module is removed, the `analytics-4` module doesn't appear active anymore.
&nbsp;
To replicate, in the current version of the plugin, set up Analytics. Now, switch to the PR branch for [#7932](https://github.com/google/site-kit-wp/issues/7932) (that removes the registration of the `analytics` module). You'll see that the Analytics module (now `analytics-4`) appears disconnected.
&nbsp;
There are two potential solutions for this problem:

    1. Keep using [the hack](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Core/Modules/Modules.php#L845-L871).
    2. (I recommend) Adding an additional database migration that updates the `googlesitekit_active_modules` option to add `analytics-4` in it if `analytics` is already there. This can be done as part of the database migration we already have in our pipeline, [#8082](https://github.com/google/site-kit-wp/issues/8082), or as part of a new issue. It might be worth including this in [#8082](https://github.com/google/site-kit-wp/issues/8082) as it will need to return to Execution anyway as its targeted version number will need to be updated.
2. We will have a couple problems with users who still haven't configured GA4. It is possible for a certain amount of users to be using Site Kit where they still haven't configured GA4.
    1. Currently, they should be seeing the [GA4 Activation Banner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-reminderbanner--post-cutoff) in the SK dashboard and the [UA Cut-off Warning](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-components-uacutoffwarning--post-ga-4-auto-switch) in Analytics widgets. However, as an outcome of [#7932](https://github.com/google/site-kit-wp/issues/7932), since the `analytics` module will be removed (i.e. replaced with `analytics-4`):
        1. The GA4 Activation Banner will not show up, as it won't have a way to compare the connection status of the two Analytics modules, as there will be only one Analytics module now.
        2. The UA Cut-off Warning currently only shows up in the version of the Analytics widgets. Since after SAM, there will no longer be any UA-version of the Analytics widgets, the UA Cut-off Warning will also not appear.
        
        For these users, once they update to the newer versions of Site Kit with SAM launched, the Analytics module will simply appear disconnected, and they will need to re-connect it with a GA4 configuration.
        
        A solution here could be updating the GA4 Activation Banner (as part of a new SAM issue) so that it can work without the legacy `analytics` module being present, i.e. by directly referencing the `googlesitekit_analytics_settings` option to determine if UA is set up but GA4 is not.
    2. What if such a user has used dashboard sharing to share the Analytics module? Now that we are removing the backwards-compatible sharing settings replication between `analytics` & `analytics-4` ([see method](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Modules/Analytics_4.php#L2047-L2066)), we will need some sort of a way to ensure this segment of users are covered in the migration.
    
    Similarly, there are two potential solutions for this problem:
        1. Keep using [the hack](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Modules/Analytics_4.php#L2047-L2066).
        2. (I recommend) Adding an additional migration that migrates module sharing settings from `analytics` to `analytics-4` if they are not already set for `analytics-4`, either as part of #8082, or a new issue.

The above concerns can be considered launch blockers for SAM, and will need to be addressed before it is launched.

@aaemnnosttv It'd be great if we could get your thoughts on the concerns above, with a

**Comment by nfmohit** [comment]
I have reviewed [the PR](https://github.com/google/site-kit-wp/pull/8234) for this issue and have left my CR feedback. The feedback is quite extensive, which I think is understandable provided it is a massive refactoring PR. Most of my points are small, with some moderate.

However, I have a couple of other concerns that have come up after observing the upcoming outcome of #7932 that doesn't directly relate to #7932 itself, but the entire SAM initiative overall.

1. The `googlesitekit_active_modules` option (that holds a list of currently active modules) never included `analytics-4`. `analytics-4` was only considered active based on a "hacky" logic conditionally if the `analytics` module was active. [See method](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Core/Modules/Modules.php#L845-L871).
&nbsp;
Now that we're removing all similar "hacks" with an intention to simplify logic and reduce future technical debt, when the `analytics` module is removed, the `analytics-4` module doesn't appear active anymore.
&nbsp;
To replicate, in the current version of the plugin, set up Analytics. Now, switch to the PR branch for [#7932](https://github.com/google/site-kit-wp/issues/7932) (that removes the registration of the `analytics` module). You'll see that the Analytics module (now `analytics-4`) appears disconnected.
&nbsp;
There are two potential solutions for this problem:

    1. Keep using [the hack](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Core/Modules/Modules.php#L845-L871).
    2. (I recommend) Adding an additional database migration that updates the `googlesitekit_active_modules` option to add `analytics-4` in it if `analytics` is already there. This can be done as part of the database migration we already have in our pipeline, [#8082](https://github.com/google/site-kit-wp/issues/8082), or as part of a new issue. It might be worth including this in [#8082](https://github.com/google/site-kit-wp/issues/8082) as it will need to return to Execution anyway as its targeted version number will need to be updated.
2. We will have a couple problems with users who still haven't configured GA4. It is possible for a certain amount of users to be using Site Kit where they still haven't configured GA4.
    1. Currently, they should be seeing the [GA4 Activation Banner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-reminderbanner--post-cutoff) in the SK dashboard and the [UA Cut-off Warning](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-components-uacutoffwarning--post-ga-4-auto-switch) in Analytics widgets. However, as an outcome of [#7932](https://github.com/google/site-kit-wp/issues/7932), since the `analytics` module will be removed (i.e. replaced with `analytics-4`):
        1. The GA4 Activation Banner will not show up, as it won't have a way to compare the connection status of the two Analytics modules, as there will be only one Analytics module now.
        2. The UA Cut-off Warning currently only shows up in the version of the Analytics widgets. Since after SAM, there will no longer be any UA-version of the Analytics widgets, the UA Cut-off Warning will also not appear.
        
        For these users, once they update to the newer versions of Site Kit with SAM launched, the Analytics module will simply appear disconnected, and they will need to re-connect it with a GA4 configuration.
        
        A solution here could be updating the GA4 Activation Banner (as part of a new SAM issue) so that it can work without the legacy `analytics` module being present, i.e. by directly referencing the `googlesitekit_analytics_settings` option to determine if UA is set up but GA4 is not.
    2. What if such a user has used dashboard sharing to share the Analytics module? Now that we are removing the backwards-compatible sharing settings replication between `analytics` & `analytics-4` ([see method](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Modules/Analytics_4.php#L2047-L2066)), we will need some sort of a way to ensure this segment of users are covered in the migration.
&nbsp;
    Similarly, there are two potential solutions for this problem:
        1. Keep using [the hack](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Modules/Analytics_4.php#L2047-L2066).
        2. (I recommend) Adding an additional migration that migrates module sharing settings from `analytics` to `analytics-4` if they are not already set for `analytics-4`, either as part of [#8082](https://github.com/google/site-kit-wp/issues/8082), or a new issue.

The above concerns can be considered launch blockers for SAM, and will need to be addressed before it is launched.

@aaemnnosttv It'd be great if we could get your thoughts on the concerns above, with a suggestion on the direction forward, thanks so much!

CC: @bethanylang @jimmymadon @hussain-t @zutigrm @ivonac4

**Comment by nfmohit** [comment]
Update on the above: Evan, Mariya, and I spoke internally about this and I've summarised the resolutions below:

> The `googlesitekit_active_modules` option (that holds a list of currently active modules) never included `analytics-4`. `analytics-4` was only considered active based on a "hacky" logic conditionally if the `analytics` module was active. [See method](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Core/Modules/Modules.php#L845-L871).   Now that we're removing all similar "hacks" with an intention to simplify logic and reduce future technical debt, when the `analytics` module is removed, the `analytics-4` module doesn't appear active anymore.   To replicate, in the current version of the plugin, set up Analytics. Now, switch to the PR branch for [#7932](https://github.com/google/site-kit-wp/issues/7932) (that removes the registration of the `analytics` module). You'll see that the Analytics module (now `analytics-4`) appears disconnected.   There are two potential solutions for this problem:
> 
> 1. Keep using [the hack](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Core/Modules/Modules.php#L845-L871).
> 2. (I recommend) Adding an additional database migration that updates the `googlesitekit_active_modules` option to add `analytics-4` in it if `analytics` is already there. This can be done as part of the database migration we already have in our pipeline, [#8082](https://github.com/google/site-kit-wp/issues/8082), or as part of a new issue. It might be worth including this in [#8082](https://github.com/google/site-kit-wp/issues/8082) as it will need to return to Execution anyway as its targeted version number will need to be updated.

In order to address this, we've decided to extend the database migration in #8082.

> We will have a couple problems with users who still haven't configured GA4. It is possible for a certain amount of users to be using Site Kit where they still haven't configured GA4.
> 
> 1. Currently, they should be seeing the [GA4 Activation Banner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-reminderbanner--post-cutoff) in the SK dashboard and the [UA Cut-off Warning](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-components-uacutoffwarning--post-ga-4-auto-switch) in Analytics widgets. However, as an outcome of [#7932](https://github.com/google/site-kit-wp/issues/7932), since the `analytics` module will be removed (i.e. replaced with `analytics-4`):
>    
>    1. The GA4 Activation Banner will not show up, as it won't have a way to compare the connection status of the two Analytics modules, as there will be only one Analytics module now.
>    2. The UA Cut-off Warning currently only shows up in the version of the Analytics widgets. Since after SAM, there will no longer be any UA-version of the Analytics widgets, the UA Cut-off Warning will also not appear.
>    
>    For these users, once they update to the newer versions of Site Kit with SAM launched, the Analytics module will simply appear disconnected, and they will need to re-connect it with a GA4 configuration.
>    A solution here could be updating the GA4 Activation Banner (as part of a new SAM issue) so that it can work without the legacy `analytics` module being present, i.e. by directly referencing the `googlesitekit_analytics_settings` option to determine if UA is set up but GA4 is not.

Based on [this internal conversation](https://10up.slack.com/archives/C01CA828ZPZ/p1709577424281699), we've decided to not adapt the GA4 Activation Banner and let the Analytics module appear disconnected for such cases, as UA is completely non-functional at this point.

> We will have a couple problems with users who still haven't configured GA4. It is possible for a certain amount of users to be using Site Kit where they still haven't configured GA4.
> 
> 2. What if such a user has used dashboard sharing to share the Analytics module? Now that we are removing the backwards-compatible sharing settings replication between `analytics` & `analytics-4` ([see method](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Modules/Analytics_4.php#L2047-L2066)), we will need some sort of a way to ensure this segment of users are covered in the migration.
>     
>    Similarly, there are two potential solutions for this problem:
>    
>    1. Keep using [the hack](https://github.com/google/site-kit-wp/blob/04a3759c817f1c1a6b81427c24d9ca62f29286b8/includes/Modules/Analytics_4.php#L2047-L2066).
>    2. (I recommend) Adding an additional migration that migrates module sharing settings from `analytics` to `analytics-4` if they are not already set for `analytics-4`, either as part of [#8082](https://github.com/google/site-kit-wp/issues/8082), or a new issue.

In order to address this, we've decided to extend the database migration in #8082.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on feature branch.
- Verified analytics functionality as part of E2E testing of SAM module.
