### ISSUE TITLE
(Re)Connecting Analytics hangs in loading state when Tag Manager Is connected

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#7937]
## Bug Description

When Tag Manager module is connected, and Analytics disconnected and then, trying to connect again it hangs in the loading state.

There is no console error. When working on IB, check this [comment](https://github.com/google/site-kit-wp/issues/7937#issuecomment-1833692253) as potential direction

## Steps to reproduce

1. Setup Site Kit
2. Connect `Analytics` and `Tag Manager` modules
3. Disconnect `Analytics` module
4. Try to connect it again
5. See setup being stuck in loading state

## Screenshots

https://github.com/google/site-kit-wp/assets/10414808/abf09e08-20f9-42fe-a23b-040b8f312556

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A user should be able to connect or reconnect Analytics after Tag Manager has been set up.

## Implementation Brief

* So the issue is that we don't load `getLiveContainerVersion` anymore and so the loading checks for `hasFinishedResolution` for this selector returns false because the resolution never started (I confirmed this by calling `hasStartedResolution`). This is because  we do not output the `ExistingGTMPropertyNotice` anymore, since we removed UA settings which did a property ID check, etc. So removing this check, as done in [this PR](https://github.com/google/site-kit-wp/pull/7849/files) on the `SettingsEdit` form is correct. 
    * This should also be done on the new `analytics-4` component that will be used soon too.
* Since this is a very minor PR, I have gone ahead and [attached it here](https://github.com/google/site-kit-wp/pull/8250) with a QAB.

### Test Coverage

* No new tests required.

## QA Brief

* Setup Site Kit and connect GTM without connecting Analytics. 
    * Verify that connecting Analytics works. 
    * Verify that creating a new account works.
    * Verify that editing settings still works.

## Changelog entry

* Fix bug preventing Analytics from being setup when Tag Manager is connected.

**Comment by zutigrm** [comment]
This is just a guess, but this might be regression from removing the `ga4Reporting` feature flag. We had similar [issue](https://github.com/google/site-kit-wp/issues/6856#issuecomment-1803753995), when editing Analytics settings with Tag Manager connected, edit settings would also hang in loading state. This was related to the `gtmContainersResolved` and it's `hasFinishedLoadingGTMContainers` check which was not used in GA4, you can check this [PR](https://github.com/google/site-kit-wp/pull/7849/files), this might be similarly relating to this as well.

**Comment by techanvil** [comment]
Hi @jimmymadon, this IB good. One thing, though - with `hasFinishedLoadingGTMContainers()` no longer in use, we should remove that too (both versions of it).

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- On latest environment able to reproduce the issue.
- On dev environment issue is not reproducible and analytics is not getting stuck on reconnecting.

<details>



https://github.com/google/site-kit-wp/assets/94359491/8554cc2c-6958-4251-b308-9aa2fb8e8b7d

</details>
