### ISSUE TITLE
Add temporary New badge after setting up KMW

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7940]
## Feature Description

This is a follow up to #7376 which added the (static) new badge to KMW but was later removed in #6786. As part of restoring this, we also want to make it temporary.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When first setting up the Key Metrics widget, a "New" badge should be shown in the widget area's header, as in the designs
* The badge's display should be temporary and the badge should only be visible for two weeks

## Implementation Brief

* When setting the `Key_Metrics_Setup_Completed_By` value upon successful setup of KMW, set a transient (e.g. `googlesitekit_key_metrics_setup_new`) to a boolean `true`, using an expiration of `WEEK_IN_SECONDS`
* Pass this value to the client unconditionally, along side `keyMetricsSetupCompletedBy` as `keyMetricsSetupCompletedNew`
* Use this value on the client to **conditionally render** the New badge in the widget area as we did before (https://github.com/google/site-kit-wp/pull/7493/files#diff-8684c16fe68eb0a2acb0bd8f481711922ed5b9e2a97b5ac6666718933e84d6fa)

### Test Coverage

* Minimal coverage is fine given the time constraints; this should also be easy to verify in QA

## QA Brief

* If using an existing test site, do a reset first
* Check that the new badge appears after setting up KMW both ways (tailored metrics + choosing own)
* To simulate the expiration of time that the badge is shown, use a plugin like [Transients Manager](https://wordpress.org/plugins/transients-manager/) to clear all transients
* ~~While viewing KMW tiles, the new badge can also be toggled on/off temporarily in the browser (not a replacement for the above)~~

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
Noting that, upon discussion with @marrrmarrr we decided to make the time two weeks instead of one for now, and will also factor in number of logins since setup in a follow up enhancement to this.

**Comment by wpdarren** [comment]
### QA update: ❌ 

@kuasha420 I noticed that when I select metrics and save them, the dashboard loads with the widget and the appropriate tiles, but the badge does not load.  When I refresh the dashboard, the badge then appears. 

Screencast below.

https://github.com/google/site-kit-wp/assets/73545194/a8311f33-2596-4672-8ddc-151875b9fee1

I also want to note, more for @aaemnnosttv  to get his opinion, but we don't have the new badge on the widget when only the CTA appears, which feels like an odd user experience.  I would expect it to appear.

**Comment by aaemnnosttv** [comment]
@wpdarren the follow-up which addresses your point above has been merged

**Comment by aaemnnosttv** [comment]
## QA + Approval ✅ 

Tested this a number of ways, and this looks good to go 🚀 

- Setting up when choosing Tailored metrics
- Setting up when choosing own metrics
- New badge is shown right after set up is completed and on subsequent page refreshes
- Shows as expected in a view-only context (i.e. set up by another user)
- Disappears after transient expires (set to 2 weeks)

It's worth noting that the New badge does not show on the header of the CTA before the feature is set up, but this is a bit out of scope with the AC as defined and something we can consider as a future enhancement.

Thanks all!
