### ISSUE TITLE
Double Pageviews, Double Pages/Session, Greatly Reduced Bounce Rate

### ISSUE THREAD

**Issue by JPPhoto** [google/site-kit-wp#796]
## Bug Description

Since installing this plugin, the site I administer shows double the number of pageviews that it should (consequently pages/session has doubled) in Google Analytics. Installing the plugin has also dramatically altered the bounce rate for the site as well. It seems that detection of the existing tracking code needs to be more robust. The site has a custom theme that inserts the tracking code in the page's &lt;head&gt; section.

## Steps to reproduce

1. Install the plugin.
2. Examine traffic.
3. Notice that traffic has doubled, along with pages/session.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
@JPPhoto Thanks for your report! Would you mind sharing the exact markup of the tracking code added by the theme? This will help us improve the tag detection.

**Comment by ThierryA** [comment]
Potentially fixed by #793 (cross-referencing)

**Comment by JPPhoto** [comment]
> @JPPhoto Thanks for your report! Would you mind sharing the exact markup of the tracking code added by the theme? This will help us improve the tag detection.

I had to disable the plugin because getting accurate Analytics data is pretty important for the site in question. I saw that it was invoking gtag('config', ...) a second time in the output HTML.

The theme outputs the following:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX-X"></script>
<script>window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-XXXXXXX-X', {
      'cookie_domain': 'www.mydomain.com'
    });</script>
```

**Comment by felixarntz** [comment]
This should no longer be relevant now that Site Kit offers more reliable tag detection (for Analytics, AdSense, Tag Manager). I'll close this for now, but please reopen if it proves to still be a problem.
