### ISSUE TITLE
Update PHP test matrix

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7964]
## Feature Description

From time to time we need to revise the matrix of variables we use for producing test jobs for various supported versions of PHP, WP, etc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The current job for PHP tests running on PHP 8.0 should be updated to PHP 8.2 

## Implementation Brief

* [x] Update the version reference in the workflow's matrix https://github.com/google/site-kit-wp/blob/c892ea9620b9f60328bfe8a7bd9f40c563a33296/.github/workflows/php-lint-tests.yml#L80

### Test Coverage

* No changes

## QA Brief

* 

## Changelog entry

* N/A

**Comment by zutigrm** [comment]
CI fails for missing class `Client` in Guzzle library. It is not present in classmap for third-party for some reason. Prefixing works, compoeser install works, but class is not present.

Tried updating the `yoast/phpunit-polyfills` to 1.1, scoper and Guzzle, but nothing helps. Also tested by adding php version from matrix in cache key in workflow file, to verify if it might be a caching issue. Verified with step that outputs php version that composer install is properly run in 8.1.x environment in CI.

Locally when attempting `composer install` or running the test, neither work, as it needs updating and edits to scoper config, and test configugation, etc. But somehow it works in CI, although with this weird missing class issue

**Comment by bethanylang** [comment]
@aaemnnosttv Reassigning this over to you per discussion in stand-up, and removed from sprints.

**Comment by aaemnnosttv** [comment]
Closing for now. We'll revisit this once we raise our minimum version of PHP in #8030. It isn't worth trying to address the problems we're running into until then.
