### ISSUE TITLE
missing parameter: ‘verification_nonce’

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#797]
## Bug Description

Sometimes the authentication service returns an error about a missing verification nonce (see https://wordpress.org/support/topic/missing-parameter-verification_nonce/).

This happens whenever site verification has failed for some reason, because when that happens, the user can try to re-do the step again (for which the verification nonce _would_ be required again).

Therefore we need to also send the `verification_nonce` parameter in the handler where we send `verify=true`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When redirecting the user back to the proxy to check site verification, a `verification_nonce` parameter should be sent.
* Failing site verification on the proxy should not result in a `missing parameter: 'verification_nonce'` error.

## Implementation Brief

In https://github.com/google/site-kit-wp/blob/9219d9c79432e44a3109cc08d76743667f3ea176/includes/Core/Authentication/Authentication.php#L435  
pass a `missing_verification` string as second parameter to `get_proxy_setup_url()`, so that it is correctly added by the logic in https://github.com/google/site-kit-wp/blob/9219d9c79432e44a3109cc08d76743667f3ea176/includes/Core/Authentication/Clients/OAuth_Client.php#L650-L652.

## Changelog entry

* Fix bug where the site verification nonce was not sent to the authentication service.

**Comment by aaemnnosttv** [comment]
IB ✅ 

This is a bit confusing when you look at it that you would hard code an error code passed to the setup URL. We should be sure to leave a comment to explain why this is necessary, since I think it is likely not very obvious.

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds good, let's add a comment to clarify.

**Comment by adamsilverstein** [comment]
This passes QA in my testing, moving to Approval.

### Testing Procedure

* Spin up a new live site using the `jurassic.ninja` service
* Install plugin built from develop
* Run thru setup process, stopping right before site verification happens.

![image](https://user-images.githubusercontent.com/2676022/68324449-a1e45400-0084-11ea-972c-866e66843208.png)


* in another window, edit the theme's header file, commenting out the call to `wp_head()` - this prevents the plugin from properly inserting the verification tag

![image](https://user-images.githubusercontent.com/2676022/68324466-a872cb80-0084-11ea-94f3-02cade302474.png)


* try to verify the site, note an error is shown and you can retry

![image](https://user-images.githubusercontent.com/2676022/68324483-af99d980-0084-11ea-8ade-c5494d0f8307.png)

* retry - note same error same error
* in second tab, remove commenting of `wp_head()` so verification meta tag insertion works
* retry again - note it works, proceeds to next step:

![image](https://user-images.githubusercontent.com/2676022/68324559-d8ba6a00-0084-11ea-98b6-c48e64916e4f.png)
