### ISSUE TITLE
Ensure the `confirm_notification` GA event is tracked when returning from OAuth to the "Enable enhanced measurement" banner.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7974]
## Feature Description

At present, the GA event with category `{ viewContext }_enhanced-measurement-notification` and action `confirm_notification` is only being [tracked](https://github.com/google/site-kit-wp/blob/091807c96ac7c8b4ca1949cfd9b5e9477fbf2330/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js#L137-L140) when the user clicks the "Enable enhanced measurement" banner's CTA in the case where the user already has the _edit_ scope.

We're missing the event tracking for cases where the CTA redirects the user to the OAuth flow and the submission is then auto-resumed upon return. We need to track the event in this scenario too.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Given the user clicks the "Enable enhanced measurement" banner CTA and it results in a redirection to the OAuth flow:
  - Upon return from OAuth, the following GA event should be tracked:
    - Category: `{ viewContext }_enhanced-measurement-notification`
    - Action: `confirm_notification`

## Implementation Brief

* Modify `assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js`
  * Move the currently present [`trackEvent`](https://github.com/google/site-kit-wp/blob/1ce01bdfff9e0808e262eb83127d584a45387f03/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js#L137-L140) to the [commonSubmitChanges](https://github.com/google/site-kit-wp/blob/091807c96ac7c8b4ca1949cfd9b5e9477fbf2330/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js#L87) callback

### Test Coverage

* No test updates needed

## QA Brief

- Set up Site Kit with anonymous usage data tracking.
- Set up the Analytics module without Enhanced Measurement enabled.
- Go to the SK dashboard.
- In the Enhanced Measurement activation banner that appears, click on the CTA and go through the OAuth process.
- Upon returning from the OAuth process and successfully enabling EM, verify that the GA event with category `{ viewContext }_enhanced-measurement-notification` and action `confirm_notification` was tracked.
- From SK settings, change the Analytics property to a different one, again with EM disabled.
- Go to the SK dashboard and in the EM activation banner, click the CTA. This time, you shouldn't be redirected to OAuth and it should be activated immediately. Verify that the same event is tracked again.

## Changelog entry

* Ensure the `confirm_notification` GA event is tracked when returning from OAuth to the "Enable enhanced measurement" banner.

**Comment by techanvil** [comment]
Hey @zutigrm, for the IB, can't we simply move the current call to `trackEvent()` to [`commonSubmitChanges()`](https://github.com/google/site-kit-wp/blob/091807c96ac7c8b4ca1949cfd9b5e9477fbf2330/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js#L87)?

**Comment by zutigrm** [comment]
@techanvil thanks for the review. Since AC mentions that this should happen `Upon return from OAuth` I included it that way. Technically we could track it there since afterwards redirection will happen, but I am feeling like it would deviate from AC, what do you think?

**Comment by techanvil** [comment]
Hey @zutigrm, I'm not sure what you mean by "_afterwards_ redirection will happen" - the call to `commonSubmitChanges()` is invoked having returned from OAuth, not before the redirect, so it should be fine to make the simpler change of moving `trackEvent()` there...

Note how `autoSubmit` is being checked to be true here:
https://github.com/google/site-kit-wp/blob/1ce01bdfff9e0808e262eb83127d584a45387f03/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js#L174-L185

And it's actually set to true here, prior to the redirect:
https://github.com/google/site-kit-wp/blob/1ce01bdfff9e0808e262eb83127d584a45387f03/assets/js/modules/analytics-4/components/dashboard/EnhancedMeasurementActivationBanner/SetupBanner.js#L108-L135

**Comment by zutigrm** [comment]
@techanvil ah I see what you mean, I missed that it is also called from there, was tracking it from `handleSubmitChanges` but it is not calling it from there in case of permission scope error.

**Comment by techanvil** [comment]
Thanks @zutigrm. One last thing, let's specify that we move the existing `trackEvent()`, just to be on the safe side.

**Comment by zutigrm** [comment]
@techanvil Makes sens, IB updated

**Comment by techanvil** [comment]
Thanks @zutigrm! IB LGTM. :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- In the Enhanced Measurement activation banner, when I click on the CTA and go through the OAuth process, upon returning from the OAuth process and successfully enabling EM,  the GA event with category `{ viewContext }_enhanced-measurement-notification` and action `confirm_notification` was tracked.
- From SK settings, I change the Analytics property to a different one, again with EM disabled. When I go to the SK dashboard and in the EM activation banner, click the CTA. This time, I am not redirected to OAuth and it is activated immediately. The same event is tracked again.

![image](https://github.com/google/site-kit-wp/assets/73545194/abc5686c-d527-4170-b574-eb2a2d928fee)
