### ISSUE TITLE
Track a GA event when setting up Analytics with the Enhanced Measurement switch enabled.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#7975]
## Feature Description

We should track a GA event when setting up Analytics with Enhanced Measurement enabled so we can measure the user's engagement with the feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Given the user sets up Analytics with Enhanced Measurement enabled, the following event should be tracked:
  - Category: `{viewContext}_analytics`
  - Action: `ga4_setup_enhanced_measurement_enabled`

## Implementation Brief

* [ ] In `assets/js/modules/analytics/components/setup/SetupForm.js`, get the Enhanced Measurement status (eg. `const isEnhancedMeasurementEnabled = useSelect( ( select ) => select( CORE_FORMS ).getValue( ENHANCED_MEASUREMENT_FORM, ENHANCED_MEASUREMENT_ENABLED ) );`) then inside `submitForm` add:

```js
if ( isEnhancedMeasurementEnabled === true ) {
	trackEvent(
		`${ viewContext }_analytics`,
		'ga4_setup_enhanced_measurement_enabled'
	);
}
```

### Test Coverage

* No new tests needed, but existing tests should all pass.

## QA Brief

1. Install the Google Analytics debugger extension to test Analytics events.
2. Set up a new site with Site Kit, and opt-in to send Site Kit Analytics data.
3. Set up Analytics on this site and enable Enhanced Measurement.
4. Note that when finishing Analytics set up, an event with `moduleSetup_analytics` and action `ga4_setup_enhanced_measurement_enabled` is sent.

On a different site:

1. Install the Google Analytics debugger extension to test Analytics events.
2. Set up a new site with Site Kit, and opt-in to send Site Kit Analytics data.
3. Set up Analytics on this site but **do not enable Enhanced Measurement**.
4. Note that no Analytics is sent.

## Changelog entry

* Update the opt-in anonymous usage data tracking to track an event when the Analytics module is set up with Enhanced Measurement.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt at what point should the GA event trigger?   I followed the QAB, and when Analytics was set up on a new site, the GA Event `ga4_setup_enhanced_measurement_enabled` wasn't triggered when returning to the dashboard. 

![image](https://github.com/google/site-kit-wp/assets/73545194/67d6ba32-03b5-4457-a881-0105b5bac678)

As you can see from the screenshot below, it is enabled as part of the setup. 

![image](https://github.com/google/site-kit-wp/assets/73545194/2e9a81b6-200a-4f8a-a093-0c090c6fb3d1)
 
As an additional test, I also set up Enhanced Measurement via the settings too, and it wasn't triggered there either.

**Comment by tofumatt** [comment]
@wpdarren It should be triggered when clicking "Configure Analytics" during set up.

Do you have your browser console set to "clear" after page navigation? Because the track event call is made and then the user navigates away from the setup page.

That said, in other places we do `await trackEvent`, so I've created a small, follow-up PR (#8010) to do that.

Still, the request would be made before a page navigation, for what it's worth 😄

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Set up Analytics and enable Enhanced Measurement.
When finishing the Analytics setup, an event with `moduleSetup_analytics` and action `ga4_setup_enhanced_measurement_enabled` is sent.

On a different site:
- Set up Analytics on this site but did not enable Enhanced Measurement and no GA event was sent.

![image](https://github.com/google/site-kit-wp/assets/73545194/069a0c95-7da8-4987-b2c6-ddb06f0df440)
