### ISSUE TITLE
Existing official AdSense snippet not detected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#798]
## Bug Description

Site Kit's existing tag detection for AdSense does not detect the snippet provided by AdSense for users to put on their site.

```html
<script data-ad-client="ca-pub-1234567890" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
```

## Steps to reproduce

1. Manually place the html snippet provided by AdSense on the homepage
1. Set up AdSense module
1. Existing tag is not found, setup completes as usual

#### Expected (or similar)
![image](https://user-images.githubusercontent.com/1621608/68227411-4f5f5500-fffc-11e9-947f-a812f121f66e.png)
The above is using a dummy publisher ID

#### Saw
![image](https://user-images.githubusercontent.com/1621608/68227886-1ffd1800-fffd-11e9-94f3-257cb6a26667.png) 

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/68226685-1f638200-fffb-11e9-9b24-63d510a629fd.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following type of AdSense snippet should be detected when it exists on the frontend:
    ```html
    <script data-ad-client="ca-pub-1234567890" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    ```

## Implementation Brief

* Update AdSense regex to check for `script` tags as well  
    ```js
    /<(?:script|amp-auto-ads) [^>]*data-ad-client="([^"]+)"/gm
    ```

## Changelog entry

* Improve detection of existing AdSense snippets to cover more variants of snippets.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

I adjusted the code for Adsense to trigger the above copy using a dummy ID.
![image](https://user-images.githubusercontent.com/57115907/69262319-1e446000-0b78-11ea-9f37-6019f5d09575.png)

Adjusted the code for Adsense to find my domain as a positive test.

Adsense code:
![image](https://user-images.githubusercontent.com/57115907/69267011-25bc3700-0b81-11ea-8d0b-4451391f6416.png)

Adsense Google user:
Username: gk0910up@gmail.com
Password: gpev8D1DiVq9X8g

Adsense account:
![image](https://user-images.githubusercontent.com/57115907/69267503-24d7d500-0b82-11ea-96ae-1876e6467360.png)


Code on my host:
![image](https://user-images.githubusercontent.com/57115907/69267066-3ff61500-0b81-11ea-8550-9e586387e068.png)

Setup prompt
![image](https://user-images.githubusercontent.com/57115907/69266732-94e55b80-0b80-11ea-8285-d14a1e974dee.png)

One thing to note the Continue link pops a new tab and refreshes the Adsense connection setup

Need some insight as to what I should adjust to be able to have Adsense see the code. This isn't a pass for me.

**Comment by cole10up** [comment]
Confirmed with @aaemnnosttv that this is expected behavior via SK chat. Passed QA ✅
