### ISSUE TITLE
`undefined is not an object in DashboardMainApp`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7981]
## Bug Description

This error has shown up in recent error reporting in a few different forms.

## Additional Context

https://github.com/google/site-kit-wp/blob/fd747deb1dc8873d01025f457039739e881efff6/assets/js/components/DashboardMainApp.js#L106-L118

This can happen if `temporaryPersistedPermissionsError` is an array, but `grantedScopes` is not resolved yet.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing preconditions for the `undefined is not an object in DashboardMainApp` (also `undefined is not an object (evaluating 'q.includes') in DashboardMainApp` should be updated so that the error above is no longer possible
* The AC of #7597 should still be satisfied

## Implementation Brief

* [x] Update the code above to use a fallback for `grantedScopes` so that it is always an array but will still "not includes" any value if it hasn't been loaded yet (preserving the logic)
* [x] Extract the related functionality for `hasReceivedGrantedScopes` within the `useMount` to a new `useEffect` – since `useMount` only runs once, it might not be accurate depending on the available state of its dependent data. i.e. use a `useEffect` that only clears the `permissionsError` if `grantedScopes` and `temporaryPersistedPermissionsError` are not `undefined` as a precondition for the [`hasReceivedGrantedScopes ? setValues` call](https://github.com/google/site-kit-wp/blob/fd747deb1dc8873d01025f457039739e881efff6/assets/js/components/DashboardMainApp.js#L126-L130) 

### Test Coverage

* No added coverage is necessary

## QA Brief

* There's no clear steps to reproduce here from the issue, but loading the Site Kit dashboard after site setup, then after setup of a new module, then refreshing the page, would do the trick. No errors should be seen when loading the main Site Kit dashboard, essentially.

## Changelog entry

* Prevent accessing `undefined` as an object following OAuth permissions flow.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Followed steps under QAB.
- Verified that `'undefined is not an object in DashboardMainApp"` error is not showing on main dashboard.
