### ISSUE TITLE
Add a "Get Help" link or link within the existing text for users who encounter the google_api_connection_fail error

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7994]
## Bug Description

For users who encounter the `google_api_connection_fail` error, there is no immediate "Get Help" link as there are for other compatibility check errors ([example](https://private-user-images.githubusercontent.com/41326532/290620181-8bbb135d-2b20-492c-9b43-098258c42db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDQxODcsIm5iZiI6MTcwMjY0Mzg4NywicGF0aCI6Ii80MTMyNjUzMi8yOTA2MjAxODEtOGJiYjEzNWQtMmIyMC00OTJjLTliNDMtMDk4MjU4YzQyZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEyMzgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMWI4MDgxNzA3NGEzMmJiOTNjOWY3ZDdkZDZlZjkwNzIxMjIxNjU0OGFiZjI1MmRjODExMjhlY2U3OTFhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIMaRu3r5E9cpfHQfavwRrAtq8Ud-07bBT4GVnjsIAM)). 

![image](https://github.com/google/site-kit-wp/assets/41326532/96220c58-aad3-4297-b617-c335c059c5da)

As we have new documentation making it's way through to the website, and an infrastructure change (https://github.com/google/site-kit-wp/issues/7864) with mini plugin that will allow users who are stuck based on IPv6 blocks, consider changing the following or similar:

[Reference in codebase 
](https://github.com/google/site-kit-wp/blob/7b715060ca674fdbdb0f1d753b8306af59498613/assets/js/components/setup/CompatibilityChecks/CompatibilityErrorNotice.js#L173C10-L174C27)

```diff
- To get more help, ask a question on our [support forum](https://wordpress.org/support/plugin/google-site-kit/) and include the text of the original error message:
+ [Click here](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#google_api_connection_fail) for more information, or o get more help, ask a question on our [support forum](https://wordpress.org/support/plugin/google-site-kit/) and include the text of the original error message:
```

An alternate to the above would be have a standard "Get help' button with the `google_api_connection_fail` error code, as we have for the AMP or REST API compatibility checks. ([AMP Get Help button](https://private-user-images.githubusercontent.com/41326532/290620181-8bbb135d-2b20-492c-9b43-098258c42db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDQxODcsIm5iZiI6MTcwMjY0Mzg4NywicGF0aCI6Ii80MTMyNjUzMi8yOTA2MjAxODEtOGJiYjEzNWQtMmIyMC00OTJjLTliNDMtMDk4MjU4YzQyZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEyMzgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMWI4MDgxNzA3NGEzMmJiOTNjOWY3ZDdkZDZlZjkwNzIxMjIxNjU0OGFiZjI1MmRjODExMjhlY2U3OTFhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIMaRu3r5E9cpfHQfavwRrAtq8Ud-07bBT4GVnjsIAM) | [REST related Get Help button](https://private-user-images.githubusercontent.com/41326532/290618455-036a8f52-a56f-4f13-84ef-46a064b1eb6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDUzODEsIm5iZiI6MTcwMjY0NTA4MSwicGF0aCI6Ii80MTMyNjUzMi8yOTA2MTg0NTUtMDM2YThmNTItYTU2Zi00ZjEzLTg0ZWYtNDZhMDY0YjFlYjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEyNTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MmUwMDhkNDk5ODI4MmQ5MmM2YTMwZTRlZjg3NDQzMjdmMjA4Nzg2ZTQwZTY1NGFkMjhkMmU2ZDI2NzJlN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-cydqMlewc92okF_lm8G1c5168t98JNS5MArwBjBqLA))

Note: There is a [placeholder error code for this in our MVP error mapping sheet](https://docs.google.com/spreadsheets/d/12x39d7j0GNqha0m7s4-Y3P5SwK9wwgxxxDnWp3svSKg/edit?resourcekey=0-IngulwDvPmI4SEq2g-f4rA#gid=0&range=A12). This will be updated to point to the new guide making it's way through documentation. 

@aaemnnosttv  @adamdunnage @bethanylang 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A "Get Help" link should appear when the `google_api_connection_fail` error case is encountered in the Compatibility Errors. See the component for similar links.
* The "Get Help" link should go to https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#google_api_connection_fail

## Implementation Brief

* [ ] Add a `<GetHelpLink errorCode={ error } />` to the `google_api_connection_fail` error case in `assets/js/components/setup/CompatibilityChecks/CompatibilityErrorNotice.js` (using `createInterpolateElement`, similar to other cases in that file).
* [ ] Update the Proxy support link URL service to point the Proxy Support Link URL output by https://github.com/google/site-kit-wp/blob/72bf3652661d7ac9fdf1221bcd9bdbfde35b9fd1/assets/js/googlesitekit/datastore/site/urls.js#L141-L163 `error=google_api_connection_fail` to `https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#google_api_connection_fail` (Will require a Service Engineering task.)

### Test Coverage

* No new tests needed.

## QA Brief

- Install Site Kit on a fresh installation.
- In the Site Kit setup screen, open the "Network" tab of your Chrome browser developer tools.
- Right click on the request made to `/wp-json/google-site-kit/v1/core/site/data/health-checks` and select `Override content`.
- Follow [this guide](https://developer.chrome.com/docs/devtools/overrides) to override the response of this endpoint. The response should be updated to:
```js
{
    "checks": {
        "googleAPI": {
            "pass": false,
            "errorMsg": ""
        },
        "skService": {
            "pass": true,
            "errorMsg": ""
        }
    }
}
```
- Now, reload the page and notice that the error message described in the issue appears.
- Verify that the "Get help" link points to this URL: `https://sitekit.withgoogle.com/support?error_id=google_api_connection_fail`

## Changelog entry

* Add a "Get Help" link  when `google_api_connection_fail` error occurs in Site Kit compatibility check.

**Comment by bethanylang** [comment]
Noting that the longer-term goal would be to implement #7986 to block users from proceeding with setup in this case. This would be a shorter-term solution prompting them to get help in order to proceed.

**Comment by bethanylang** [comment]
Per discussion with @aaemnnosttv, this should be a small change to update this specific case, and we'll need to determine if this error ID needs to be added to the related sheet. Moving to AC.

**Comment by techanvil** [comment]
IB :white_check_mark: 

@eugene-manuilov, tagging you as a heads up re. the IB point about this needing a Service Engineering task.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit I have two observations that I'd like to raise. 

1. I see the message highlighted in the initial ticket description on the latest release.  When I switch to the develop branch, though, a different message appears.  `Looks like your site is having a technical issue with requesting data from Google services` The AC doesn't refer to a change in the message so wanted to check. 

![image](https://github.com/google/site-kit-wp/assets/73545194/2415f216-fccc-4a79-9467-0549d7802476)

2. The URL on the "Get Help" link points to the URL in the AC,  but when I click the link, I am redirected to the support forum.  Is that expected right now?

**Comment by nfmohit** [comment]
Hi @wpdarren, thank you for sharing your observations.

> 1. I see the message highlighted in the initial ticket description on the latest release.  When I switch to the develop branch, though, a different message appears.  `Looks like your site is having a technical issue with requesting data from Google services` The AC doesn't refer to a change in the message so wanted to check.

The part that I removed ("To get more help, ask a question on our support forum and include the text of the original error message: google_api_connection_fail") is already covered in the linked documentation, so I don't think there's much point in including that again in the message. Also, this follows the pattern of other similar error messages in this context which also have a "Get help" link.

@tofumatt As you had authored the ACs here, just to confirm, do you think it is still necessary to include this part in the error message?

Thank you!

**Comment by tofumatt** [comment]
As mentioned in Slack: let's keep that message in there 😄

**Comment by nfmohit** [comment]
Thank you folks! I've opened a follow-up PR #8028 that restores this text. Thanks!

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@nfmohit I apologize in advance for being picky, but as QA, it is what I do.  😄 

Could we have the `google_api_connection_fail` text on the same line above, next to `message:`

It just looks a bit odd underneath.

![image](https://github.com/google/site-kit-wp/assets/73545194/2838ac02-c883-4bcc-bbb0-b8f726506f95)

Also, I noticed a difference in the URLs. 

On the AC.  `https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#google_api_connection_fail`
On my test site: `https://sitekit.withgoogle.com/support?error_id=google_api_connection_fail`
It's worth noting the QAB states `https://sitekit.withgoogle.com/support?error_id=google_api_connection_fail`

Have I missed something here?

**Comment by nfmohit** [comment]
Hi @wpdarren.
Thank you for sharing your observation.

> Could we have the `google_api_connection_fail` text on the same line above, next to `message:`
> 
> It just looks a bit odd underneath.

I understand, however, this is the pre-existing structure of error messages like these. This issue doesn't change the structure of the message but adds to it. Here is a similar error message:

![image](https://github.com/google/site-kit-wp/assets/20284937/32afdec4-fba8-4fd3-8a3c-b3d0b20734de)

For consistency, do you think it would be nicer to change all of them in a different issue?

> Also, I noticed a difference in the URLs.
> 
> On the AC. `https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#google_api_connection_fail` On my test site: `https://sitekit.withgoogle.com/support?error_id=google_api_connection_fail` It's worth noting the QAB states `https://sitekit.withgoogle.com/support?error_id=google_api_connection_fail`

`https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#google_api_connection_fail` is the actual URL for the documentation.

`https://sitekit.withgoogle.com/support?error_id=google_api_connection_fail` is our proxy URL which will ultimately redirect the user to the actual documentation once the updates in the service side are pushed to production (see point #2 of [this comment](https://github.com/google/site-kit-wp/issues/7994#issuecomment-1875250153)).

Please let me know what you think, thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Thanks, @nfmohit, that all makes sense. 

> For consistency, do you think it would be nicer to change all of them in a different issue?

Yes, I will create a new ticket for all of these messages. 

Your example has bad formatting, so we should look to tidy it up, but it is a low priority in the scheme of things! 

**Verified:**

- The error message described in the issue appears.
- The "Get help" link points to this URL: `https://sitekit.withgoogle.com/support?error_id=google_api_connection_fail`

![image](https://github.com/google/site-kit-wp/assets/73545194/fa0bddbf-07ed-428a-9b84-5222bb594b5a)
