### ISSUE TITLE
Clean up `V2` references in AdSense stories

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7999]
## Feature Description

Follow-up to #4765 to update the story hierarchy.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AdSense stories should no longer contain a `V2` segment in the hierarchy ([example](https://github.com/google/site-kit-wp/blob/8af3f7e8a0dcaf18b5ddd3e42b4e9b7252ccf4e8/assets/js/modules/adsense/components/setup/SetupMain.stories.js#L248))

## Implementation Brief

* Remove `V2` from stories title, currently at the time of writing:
  * `assets/js/modules/adsense/components/setup/SetupUseSnippetSwitch.stories.js`
  * `assets/js/modules/adsense/components/setup/SetupMain.stories.js`
  * Search for any other AdSense story containing "V2" and remove the "V2" from their names

### Test Coverage

* No update needed, since IB is about stories

## QA Brief

* Go to storybook and verify that there is no more `V2` stories in the AdSense module.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov I don't feel this relates to this ticket, but I noticed a few odd elements in the stories. 

e.g., this one where the AdSense code placement toggle appears on the status 'pending task'. 

![image](https://github.com/google/site-kit-wp/assets/73545194/be4edfb0-38d5-42c8-83b8-1cb58244bfac)

Shall I create a separate ticket with the stories that have additional elements?

**Comment by eugene-manuilov** [comment]
@wpdarren, yes, let's create new tickets for all issues that you see with those stories. Those bugs are out of scope for this ticket.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- In storybook, there are no more V2 stories in the AdSense module.

I did notice a few screens that had incorrect elements, so will create a ticket for these.
