### ISSUE TITLE
Hardcoded (German) language strings

### ISSUE THREAD

**Issue by jphorn** [google/site-kit-wp#8]
**Describe the bug**
Some errors are hardcoded to return in German language

**To Reproduce**
https://github.com/google/site-kit-wp/blame/9a262cd18c33995ce5ec81bc300ff055dff2a153/includes/Core/Storage/Data_Encryption.php#L123
https://github.com/google/site-kit-wp/blame/9a262cd18c33995ce5ec81bc300ff055dff2a153/includes/Core/Storage/Data_Encryption.php#L143

There may be more. I found these while referencing #7 

**Expected behavior**
Errors and/or code should preferably be English to enhance collaboration

**Comment by jamesozzie** [comment]
@jphorn Thanks for the heads up on this.

**Comment by felixarntz** [comment]
Thanks for opening this issue @jphorn! As mentioned in https://github.com/google/site-kit-wp/pull/9#issuecomment-504078134, this line of code is pretty much irrelevant, and not a user-facing string. It's an easter egg, and, if anything, changing this would break backward-compatibility for those sites that use this value as encryption key (and thus would be entirely insecure).
