### ISSUE TITLE
Unable to receive access token because of an invalid authorization code or refresh token.

### ISSUE THREAD

**Issue by shaneedwardtaylor** [google/site-kit-wp#800]
Getting that error from time to time after 1.0.1 update. when i refresh it goes away.

**Comment by jamesozzie** [comment]
Thanks for reporting. Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
