### ISSUE TITLE
Disable front end code

### ISSUE THREAD

**Issue by jamesstcrice** [google/site-kit-wp#801]
## Feature Description

Site Kit seems like a great way to get a snapshot of google data into the WP dashboard. However, it's often the case that the required google code is already present in the site via another method that is inefficient to change.

It would be great if the front end code appending could be disabled and Site Kit used for the dashboard screens only.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for raising this issue @jamesstcrice!

Front end code snippets are all possible to disable via module settings for all modules that output code snippets.  
E.g. from Analytics settings: 
![image](https://user-images.githubusercontent.com/1621608/112983928-eb947980-9166-11eb-866d-adaa38b3f910.png)

For more technical users, we also make this possible to suppress output via a module-specific filter: `googlesitekit_{module_slug}_tag_blocked` which will prevent rendering the module's snippet/tag if this filter returns `true`.

---

Closing as already addressed by other issues. cc: @felixarntz
