### ISSUE TITLE
Navbar Item Integration And Intigration Site Kit Get Overlapped 

### ISSUE THREAD

**Issue by Chetax** [google/site-kit-wp#8014]
## Bug Description

Navbar Item Integration And Intigration Site Kit Get Overlapped When Size Of Screen Reduce To Mobile Screen
## Steps to reproduce

1. Go to 'https://sitekit.withgoogle.com/'
2. Open Developer  tool kit ''ctrl +shift+i"
3. Decrease Screen Upto ''613 px"

## Screenshots
![Screenshot 2023-12-25 172559](https://github.com/google/site-kit-wp/assets/99749401/73613605-f4c0-4bbf-9692-6e45cb08c80f)

## Additional Context

 - OS: Window
 - Browser: chrome 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by Chetax** [comment]
@asvinb i Want to work on this issue can you please assign it to me

**Comment by jamesozzie** [comment]
Thanks for reaching out @Chetax. I can confirm the same. 

![image](https://github.com/google/site-kit-wp/assets/41326532/2ee819da-bcb0-499a-92cd-811df819f129)

As this relates to the plugin website, as opposed to the plugin itself, we will any necessary adjustments based on your findings using our standard website update procedures, not from the plugins GitHub repository. While I'll close this issue, I am happy to tag you here with any such updates we may make. Many thanks for reporting, and happy new year.
