### ISSUE TITLE
Analytics appearing in zero data state for new analytics property.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#8023]
## Bug Description

I set up site kit with analytics a/c property which have data. After that I created new property for the same account. As per QAB when I create new property then Analytics should appear in gathering data state. But, in my test I created 3 new properties but for all of them Analytics appearing in zero data state on main dashboard.

## Steps to reproduce

1. Connect Analytics with property having data.
2. Go to Analytics settings.
3. Create new property.
4. Go to Main Dashboard.
5. See that analytics is appearing in zero data state.
6. Expected: Analytics should appear in gathering data state.

## Screenshots

https://github.com/google/site-kit-wp/assets/94359491/5ed23c4e-072d-4c9c-b8b8-c13ab8aa28e6

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a new Analytics property is created and connected (with no data) after a previous property with data was connected, it should appear in a gathering data state, not a zero data state.

## Implementation Brief

* [x] In `assets/js/modules/analytics-4/datastore/report.js`, after this check: https://github.com/google/site-kit-wp/blob/ff60aeaa8e2109293104fde7a2972c662978718e/assets/js/modules/analytics-4/datastore/report.js#L204-L206 Add a new check if `propertyCreateTime` is `0` and return `false`

### Test Coverage

* Update `assets/js/modules/analytics-4/datastore/report.test.js`, add a new test case under `isGatheringData` to cover that it should return `false` if `propertyCreateTime` is `0` - not set yet

## QA Brief

* Follow the "Steps to reproduce" above. 

## Changelog entry

* Fix bug that caused new Analytics properties to appear as "zero data" instead of "gathering data".

**Comment by bethanylang** [comment]
@nfmohit Just checking in to see if you're able to do some testing on this as discussed in stand-up? Thanks! cc @ivonac4

**Comment by nfmohit** [comment]
Just co-assigned myself and I will look into this later today, thank you @bethanylang !

**Comment by techanvil** [comment]
Hi @zutigrm, thanks for drafting the IB. One thing - we generally return `undefined` from a selector to indicate the state is still loading. In the case where `propertyCreateTime` is `0` the implication is that is _has_ loaded with its default value.

That being the case it would be preferable to return a defined value e.g. `false`. However, I do also recognise that we might need to treat this as a special case if we do explicitly need it.

If you've already explored the option of using `false`, and returning `undefined` in this scenario is the only viable fix without a more extensive refactor, so be it. I just want to confirm that's the case one way or the other.

**Comment by zutigrm** [comment]
Hi @techanvil 

Basically both are working, idea behind returning undefined was to simulate loading, as when `0` default value is returned, it should wait for the value to be retrieved, instead of returning definitive state.

What do you think?

**Comment by techanvil** [comment]
Hmmm...

I think that I'd go with returning `false` if that's an option, because the additional loading of the property is outside of the scope of `selectDataAvailability()` - all this knows is that the current state is loaded or not, so if the external logic changes we might end up in a perpetual "loading" state even if the data is actually loaded. If there's a clear advantage to taking the "simulated loading" approach then we should go with it, but all things being equal I'd stick with returning a defined value to adhere to our conventions and avoid the potential for an incorrect loading state. If that makes sense?

**Comment by techanvil** [comment]
Great, thanks @zutigrm. IB LGTM. :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When a new Analytics property is created and connected (with no data) after a previous property with data was connected, the dashboard appears in a gathering data state, not a zero data state.
- I completed additional testing around the scenario with 2nd admin user to ensure gathering state appeared. 
- Also checked that the entity and view only dashboards appeared as gathering state. 

![image](https://github.com/google/site-kit-wp/assets/73545194/98545327-98e7-4981-968b-ccbcf116329e)
