### ISSUE TITLE
Search queries appear as links on View only dashboard 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8025]
## Bug Description

When logged in as a user with view-only access to the Site Kit Dashboard, if you scroll down to the `Top search queries for your site` widget, the search terms are styled as links. When you click on the links, nothing happens, which is expected since the user will not have access to the search console account. 

I feel the user experience could be enhanced by not listing the search terms as clickable links. 

![image](https://github.com/google/site-kit-wp/assets/73545194/825d5a73-39af-42b5-86ff-6140393c443b)

## Steps to reproduce

1. Set up Dashboard Sharing on a site with data 
2. Give access to Search Console for the Editor role.
3. Log in as the editor
4. Go to the Site Kit dashboard and see the abovementioned behavior. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The dashboard popular keywords widget display should be updated in a view-only context, similar to the related [KM widget](https://github.com/google/site-kit-wp/blob/af6b0b65e0727e139f4e3c67c1d8aeff0ff1df6b/assets/js/modules/search-console/components/widgets/PopularKeywordsWidget.js) such that the row values are displayed as plain text rather than links

## Implementation Brief

* [ ] Update `assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js`, before `Link` component is returned https://github.com/google/site-kit-wp/blob/e05000d07f7b838701a99422b49ece9236dd3387/assets/js/modules/search-console/components/dashboard/DashboardPopularKeywordsWidget.js#L162-L170 Check if it is view only dashboard to return early with simple markup - `fieldValue` wrapped in `span`

### Test Coverage

* Currently there is no story that covers View only, so optionally you can add them:
  * Update `stories/module-search-console-components.stories.js`
    * Clone one of the 2 existing stories generators, and rename it for `View Only Dashboard`, and pass new property `viewContext: VIEW_CONTEXT_MAIN_DASHBOARD_VIEW_ONLY` after `wrapWidget`
  * Update `stories/module-search-console-components.stories.js`
    * Add `viewContext` to the list of extracted variables from `args`
    * Within `WithTestRegistry` component, wrap `widgetElement` child with `ViewContextProvider` component and pass the prop: `value={ viewContext || VIEW_CONTEXT_MAIN_DASHBOARD }`

## QA Brief

* Follow `steps to reproduce` section of the issue description
* Verify that pages are not showing as links, but plain text

## Changelog entry

* Fix top search queries results to not use links in the view only mode.

**Comment by harith-hacky03** [comment]
I am eager to fix it . If the user is view-only i will make just as a string else i will give access to the console. Please assign this to me.

**Comment by bethanylang** [comment]
@harith-hacky03 Thanks for your interest in contributing! Please see our [Engineering wiki](https://github.com/google/site-kit-wp/wiki/Engineering) to get started.

**Comment by harith-hacky03** [comment]
Sure

**Comment by harith-hacky03** [comment]
I solved the issue but the cla is blocking me from test.Can you assign me ?

**Comment by bethanylang** [comment]
@harith-hacky03 More information about the CLA check failing is available here: https://github.com/google/site-kit-wp/pull/8027/checks?check_run_id=20128431790.

**Comment by harith-hacky03** [comment]
@bethanylang  Can you help me why my request stays like this .
![Screenshot_2024-01-04-07-34-50-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/google/site-kit-wp/assets/108193091/25878d5e-b474-451f-897a-1ce58a201a93)

**Comment by bethanylang** [comment]
@harith-hacky03 As the message here indicates, a maintainer of our repo needs to approve the run of these workflows in order to review and merge your PR. We'll take a look when we have a moment. Thanks!

**Comment by harith-hacky03** [comment]
I am always here to help you guys . Hope you accepts my PR. Thank you.

**Comment by harith-hacky03** [comment]
@wpdarren Can you please evaluate by PR.

**Comment by wpdarren** [comment]
@harith-hacky03 Hi there. I'm on the QA team, so I cannot complete that action.  One of our engineers will look at the PR as soon as possible. This ticket isn't included in the upcoming release so it might take a little time. Please bear with us. Thank you.

**Comment by tofumatt** [comment]
IB ✅

**Comment by harith-hacky03** [comment]
@zutigrm i already fixed the issue how come someone assign to that now .

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

 - The search terms are styled in plain text on the `Top search queries for your site` widget.  The links are no longer clickable.  Tested on desktop and mobile.  **Note:** There are some styling issues on mobile within this widget, but this is a known issue and not a regression from this change.  Also tested on all reporting periods, 7, 14, 28, and 90 days. 
 - Tested with an Editor view only user and a second admin user who views the view-only dashboard. 

![image](https://github.com/google/site-kit-wp/assets/73545194/143615b9-8944-4147-a38e-98340a460d47)
