### ISSUE TITLE
Tag detection during Analytics setup flow does not display until an account is selected.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#803]
## Bug Description

When testing in `jurassic ninja`, tag detection results during Analytics setup flow does not display until an account is selected from the dropdown.

Originally reported in QA: https://github.com/google/site-kit-wp/issues/744#issuecomment-550500357

## Steps to reproduce

1. Create a new test site using `http://jurassic.ninja/`
2. Install the site kit plugin zip from develop (`npm run release-zip`)
3. Install an analytics plugin - tested with `Analytify - Google Analytics Dashboard` and `GA Google Analytics` and use it to add an analytics tag to the site  
4. Configure Site Kit Analytics, notice that the tag does not appear to be detected, no message is shown (initially):

![image](https://user-images.githubusercontent.com/2676022/68340366-8a689380-00a3-11ea-9397-f48d33e33130.png)

5. Select an account from the first dropdown, note the tag detection message appears:

![image](https://user-images.githubusercontent.com/2676022/68341038-d405ae00-00a4-11ea-8258-882a6340770a.png)

### Expected Results
The tag detected message should appear immediately. 

Although broken in jurassic ninja, this doesn't happen to me locally so I'm not certain the source of the issue. Here is what I see in my local:

![image](https://user-images.githubusercontent.com/2676022/68340981-b3d5ef00-00a4-11ea-905b-3ddc22ba24c2.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tag detection for an existing Analytics tag should run immediately in the module setup screen, and display its results without requiring user interaction.

## Implementation Brief

* Change https://github.com/google/site-kit-wp/blob/66f7cda16defc27758629e6ae7d8577420050891/assets/js/modules/analytics/setup.js#L692-L702 to not require `selectedProfile` be truthy.
* In fact, the above method is inappropriately named from what I can tell—it's just about ensuring there is a tag on the page, and it's only used in this component to check that. A property is often pre-selected locally (that's what I was seeing), I believe because the site's URL matches existing ones in your GA account. So the check is already being ran but the fact that we found an existing tag is being ignored until a property is selected, either by the user or automatically. So we could really just change https://github.com/google/site-kit-wp/blob/66f7cda16defc27758629e6ae7d8577420050891/assets/js/modules/analytics/setup.js#L949-L951 to check for `existingTag && existingTag !== googlesitekit.admin.trackingID`

(In fact, I did the above and it worked for me locally and on a Jurassic Ninja site, so setting the time estimate here as well.)

## Changelog entry

* Fix bug in Analytics module setup where the user would not be informed about an existing tag before selecting a property.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
I've created a PR for the Analytics change, but the AC also mentions AdSense. After digging into this for a bit, I found that there appears to be a bug with existing tag detection and how it affects the behavior.

It appears that an existing tag for AdSense only appears to be presented to the user if the authenticated Google account does not have (or have access to) to any AdSense accounts. The existing tag is detected, but if the user has access to an AdSense account Site Kit appears to continue with setup as usual. Due to the high degree of complexity around the `getAdSenseAccountStatus` function, I think it makes more sense to address these separately as even the discovery done here has caused this to grow well over the initially estimated size.

**Comment by felixarntz** [comment]
@aaemnnosttv That makes sense. Can you open a separate issue for the AdSense part and add your findings to the issue description? Let's move forward with this one only focused on Analytics.

**Comment by cole10up** [comment]
**Tested**
Started a new Jurassic Ninja site, installed and activated Analytify adding the tag to my site
![image](https://user-images.githubusercontent.com/57115907/70664983-65c28700-1c20-11ea-85ce-c2d15b73de28.png)

installed and activated GA adding the tag to my site
![image](https://user-images.githubusercontent.com/57115907/70665031-82f75580-1c20-11ea-8de5-7173bb565b2d.png)

Placed the tag on my site:
![image](https://user-images.githubusercontent.com/57115907/70666645-ec2c9800-1c23-11ea-92ee-6febba43fe55.png)

Verified during the Analytics setup that the tag was found immediately. See test below

https://drive.google.com/file/d/1UN3l1CGl8e6XtS-2AFyibxkDxS4_6a9B/view

Passed QA ✅

**Comment by marrrmarrr** [comment]
👁👍
