### ISSUE TITLE
Can't finish site kit setup

### ISSUE THREAD

**Issue by Soul27** [google/site-kit-wp#804]
Steps to reproduce 
1. install plugin and activate it
2. Go to "Start Setup"
3. On Google's page select "Sign in with Google"
4. Allow access to data
5. It redirects me to website home page

with these in the url bar : ' https://varsityxchange.com/?oauth2callback=1&authuser=1&code=4%2FswE4lLFhTziWrTmHiaeKJUd6Rknuh2Bs4hV81smsfBl_VoidO68ppzX4QTxbgwYVwoXcsgQDpoaXYBWlT2oOrRg&prompt=consent&scope=email%20profile%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification&session_state=457a94cddd5c821d43b27346b36ff956c06153e9..3bb1 '

**Comment by jamesozzie** [comment]
@Soul27 Thanks for submitting a request. Site Kit support is provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your question on there, where we would be happy to assist.
