### ISSUE TITLE
Generate `GoogleAnalyticsAdminV1alphaAdSenseLink` for Google API Client Library

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8045]
## Feature Description

We need to replicate the Google API Client library's `GoogleAnalyticsAdminV1alphaAdSenseLink` for the REST Route we'll need to get linked accounts. See: https://docs.google.com/document/d/1-JenwPTAkw0eTkmESzjTOfgphs9qpRYH0h3xk_s3a4o/edit#heading=h.mjj6lw6stv0x

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`properties.adSenseLinks.list`](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.adSenseLinks/list) AdSense API method should be callable from PHP code in a similar manner to the existing API methods.

## Implementation Brief

* [x] Generate the `Google_GoogleAnalyticsAdminV1alphaAdSenseLink` class, and any related dependencies that are missing from our installed version of the [Google API Client library](https://github.com/googleapis/google-api-php-client-services/tree/v0.277.0).
  * Note that as it's an alpha API it's not in a more recent version so there's no need to upgrade the client library.
  * Use the [google-apis-client-generator](https://github.com/google/apis-client-generator) to generate the code - note that @aaemnnosttv has already generated a [Gist](https://gist.github.com/aaemnnosttv/ede786f6caa7679cac981669c2f90cb5) of it, which can be used.
* [x] Create and require the new local Composer package `packages/apiclient-services-adsenselinks`. 
  * Copy the necessary generated files into the package.
  * Tweak PHP Scoper rules as needed to ensure the namespaced version of the package works correctly.
  * Add the package as a dependency to the main `composer.json` file.
  * See this [PR](https://github.com/google/site-kit-wp/pull/5651/files) for the previously created `packages/apiclient-services-subscribewithgoogle` for an example.
* [x] Create the class `Google\Site_Kit\Modules\Analytics_4\GoogleAnalyticsAdmin\AdSenseLinksService` This can follow the example of an existing service, say [`PropertiesEnhancedMeasurementService`](https://github.com/google/site-kit-wp/blob/b37184b37044b673b21d4f9011d7784bc7609bc2/includes/Modules/Analytics_4/GoogleAnalyticsAdmin/PropertiesEnhancedMeasurementService.php).
* [x] Copy the [usage of `Google_GoogleAnalyticsAdminV1alphaAdSenseLink`](https://gist.github.com/aaemnnosttv/ede786f6caa7679cac981669c2f90cb5#file-googleanalyticsadmin-php-L753-L810) from the generated `Google_Service_GoogleAnalyticsAdmin` class into the  `AdSenseLinksService` class.

### Test Coverage

* No test coverage needed here; these can be tested in an integrated test when used in a subsequent issue. However, please do verify the code does indeed work as expected.

## QA Brief

* This does not introduce any user facing changes and only adds infrastructure for subsequent works. No QA needed here. 

## Changelog entry

* Add PHP client library for Analytics AdSense links.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by bethanylang** [comment]
Unassigned from @10upsimon as he's been ill and we need him focusing on some other work, so anyone else can feel free to pick up, please!

**Comment by wpdarren** [comment]
Moved to approval as per [Slack conversation](https://10up.slack.com/archives/CBKKQEBR9/p1705922762480529).
