### ISSUE TITLE
Add `adSenseLinked ` and `adSenseLinkedLastSyncedAt` settings to `modules/analytics-4` data store

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8048]
## Feature Description

The new settings added in #8047 should be available in the Analytics 4 datastore in JS.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `adSenseLinked ` and `adSenseLinkedLastSyncedAt` settings from #8047 should be available in the `MODULES_ANALYTICS_4` data store.

## Implementation Brief

* [x] Add the settings from the ACs to https://github.com/google/site-kit-wp/blob/83b609ec0663e5b4f0bb1278249848f0e4b90ce1/assets/js/modules/analytics-4/datastore/base.js#L31-L63

### Test Coverage

* Account for these new settings in tests (eg. ensure they exist in relevant fixtures with valid data).

## QA Brief

* Go to the Site Kit dashboard and execute the following code snippets to ensure the necessary selectors and actions have been added.
* Verify the `getAdSenseLinked` selector. By default, the value is set to `false`:
```js
googlesitekit.data.select('modules/analytics-4').getAdSenseLinked()
``` 
* Verify the `getAdSenseLinkedLastSyncedAt` selector. By default, the value is set to `0`:
```js
googlesitekit.data.select('modules/analytics-4').getAdSenseLinkedLastSyncedAt()
``` 
* Verify the `setAdSenseLinked` action by setting it with `true`:
```js
googlesitekit.data.dispatch('modules/analytics-4').setAdSenseLinked('true')
``` 
* Verify the `setAdSenseLinkedLastSyncedAt` action by setting it with the current date:
```js
googlesitekit.data.dispatch('modules/analytics-4').setAdSenseLinkedLastSyncedAt(new Date())
``` 
* Again execute the `getAdSenseLinked` and `getAdSenseLinkedLastSyncedAt` selectors and verify the new values are set.
* Note that setting the values will be set only on the client but not on the server. Hence, it won't persist when you reload the page. Page reload will be set to default values.

## Changelog entry

* Add AdSense link module settings to the Analytics data store.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by hussain-t** [comment]
Hi @tofumatt,

Could you give me some clarifications regarding the implementation details outlined in this ticket? There seems to be a discrepancy between the Feature Description and the AC, alongside some naming conventions and testing requirements:

1. **Discrepancy Between Feature Description and AC:**

**Feature Description**:

>We should fetch the AdSense linked accounts retrieved with the REST API route created in https://github.com/google/site-kit-wp/issues/8046 and save them to the new settings added in https://github.com/google/site-kit-wp/issues/8047 using a new action in the Analytics 4 datastore in JS.

**Acceptance Criteria**: 

>The adsenseLinked and adSenseLinkedLastSyncedAt settings from https://github.com/google/site-kit-wp/issues/8047 should be available in the MODULES_ANALYTICS_4 data store.
   
This raises a question: Should we implement a fetch resolver, a selector, and an action to save the settings, as indicated in the Feature Description, or follow the AC and IB, which suggest adding the settings in the base datastore? Based on #8046, I think we should update the AC according to the description.

2. **Naming Convention for `adsenseLinked`**: Should this be renamed `adSenseLinked` with a capital ‘S’?

3. **Inclusion of Test Coverage in the IB**:
IB proposes adding test coverage, which seems unnecessary given the current implementation strategy. If we include a fetch resolver and an action according to the Feature Description, adding tests would then be relevant and beneficial.

Thanks!

cc: @aaemnnosttv @nfmohit

**Comment by tofumatt** [comment]
1. I've clarified things, but all we need is to add the settings to the JS datastore 😄 
2. Yes, it should be `adSenseLinked`.
3. I've clarified the tests changes here, thanks 😄

**Comment by hussain-t** [comment]
Thanks, @tofumatt

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Verified all code snippets mentioned under QAB.
- Verified that the getAdSenseLinked selector. By default, the value is set to false:.
- Verified that the getAdSenseLinkedLastSyncedAt selector. By default, the value is set to 0:
- Verified the setAdSenseLinked action by setting it with true:
- Verified the setAdSenseLinkedLastSyncedAt action by setting it with the current date:
- Executed the getAdSenseLinked and getAdSenseLinkedLastSyncedAt selectors and verified the new values are set.
- Verified that on reloading the page `getAdSenseLinked` and` getAdSenseLinkedLastSyncedAt` value set to default.

![image](https://github.com/google/site-kit-wp/assets/94359491/bda8086c-05d6-449c-9196-635c9e5ac0b2)

![image](https://github.com/google/site-kit-wp/assets/94359491/ea19232e-c544-4bb4-b2f5-84cb2596c03c)
