### ISSUE TITLE
Display Top Earning Pages Widget with a CTA  to ask users to link their AdSense and Analytics when both modules are connected

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8050]
## Feature Description

We'll want a version of the "Top Earning Pages Widget" (#6248) that shows a CTA to link the user's AdSense and Analytics accounts when they are not linked (or we don't detect that they are linked).

See: https://docs.google.com/document/d/1-JenwPTAkw0eTkmESzjTOfgphs9qpRYH0h3xk_s3a4o/edit#heading=h.ykym38w7pngs

**NOTE:** This issue must be deployed in the same release as #6248 and #8051.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DashboardTopEarningPagesWidgetGA4`  component should return the `AdSenseLinkCTA` component when Analytics and AdSense are not connected (eg. when the `adsenseLinked` Analytics setting from #8048 is `false`), [similar to how the existing `DashboardTopEarningPagesWidget` component behaves](https://github.com/google/site-kit-wp/blob/8612fe95e03b6029aab6cd32c9df6afd1d860225/assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js#L164-L172).
  * Similar to the `DashboardTopEarningPagesWidget` component, this should only happen on the "regular" dashboard, not the view-only dashboard (eg. shared dashboard), because users in view-only mode likely won't have permissions to link these accounts.

## Implementation Brief

* [ ] Update `DashboardTopEarningPagesWidgetGA4` to check for `select( MODULES_ANALYTICS_4 ).getAdsenseLinked()` and whether the context is view-only dashboard. If the context is not view-only and `adsenseLinked` is `false`, output `<AdSenseLinkCTA />`, the same as https://github.com/google/site-kit-wp/blob/8612fe95e03b6029aab6cd32c9df6afd1d860225/assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js#L166-L172
* [ ] It would be worth adding some of the other content/logic from the non-GA4 version of this widget, specifically the lines here: https://github.com/google/site-kit-wp/blob/8612fe95e03b6029aab6cd32c9df6afd1d860225/assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js#L133-L162
  * [ ] Copy the `isAdblockerActive` logic that returns an Ad Blocker warning.
  * [ ] Copy the `! isAdSenseLinked && viewOnlyDashboard` logic that does not output the widget when AdSense is not linked and the user is on the view-only dashboard.

### Test Coverage

* Update the stories for this component to include the different scenarios above. 

## QA Brief

- Set up Site Kit.
- Enable the `ga4AdSenseIntegration` feature flag
- Connect the Analytics & AdSense modules (do not link Analytics & AdSense yet).
- In the SK dashboard, scroll down to the "Top Earning Pages widget".
- Verify that you see a prompt to link Analytics & AdSense.
- Set up an ad blocker in your browser.
- In the Top Earning Pages widget, verify that you see an ad blocker warning.
- Log in with the view-only dashboard and verify that you don't see the widget at all.
- Now, link AdSense & Analytics.
- Verify that you no longer see the prompt to link AdSense & Analytics.

When the `ga4AdSenseIntegration` feature flag is disabled, this KMW tile should not appear.

## Changelog entry

* Display CTA for users with AdSense and Analytics connected to link their accounts.

**Comment by techanvil** [comment]
Hey @tofumatt, I think it would be worth being more specific about what other content/logic we should include, as it looks like some of this should be covered by https://github.com/google/site-kit-wp/issues/8059.

It's also worth noting that the AC for this issue seems to be partially duplicated in #8059 - cc @hussain-t who's working on the IB for that issue which can probably refer in part to this one.

**Comment by tofumatt** [comment]
Thanks @techanvil. I referenced the lines in the IB, but I've added some notes to the IB here.

I've also referenced this IB in #8059 as well 👍🏻

**Comment by bethanylang** [comment]
@tofumatt Just noting that this is one that we can get started on at any time, so would be great to get these IB updates taken care of so we can start on it ASAP. Thanks!

**Comment by techanvil** [comment]
Thanks @tofumatt, IB :white_check_mark:

**Comment by nfmohit** [comment]
Hi folks!

I've set this issue as blocked by #8048 as the new setting `adSenseLinked` (see https://github.com/google/site-kit-wp/issues/8047#issuecomment-1903498239) is not yet available in the `analytics-4` datastore.

Thanks!

CC: @tofumatt @techanvil

**Comment by nfmohit** [comment]
Hi folks!

I've set this issue as blocked by #8048 as the new setting `adSenseLinked` (see https://github.com/google/site-kit-wp/issues/8047#issuecomment-1903498239) is not yet available in the `analytics-4` datastore.

Thanks!

CC: @tofumatt @techanvil @bethanylang @ivonac4

**Comment by ivonac4** [comment]
@tofumatt I can see you removed this issue from the AdSense GA4 Integration epic. Was that on purpose? If so, can you loop me in please? Thankss

**Comment by bethanylang** [comment]
@ivonac4 I'm guessing that was an error, as it happened at the same time this was removed from the release. Adding it back!

**Comment by tofumatt** [comment]
(Indeed, that looks to be a Zenhub bug! 😅 Thanks @ivonac4 for catching it and @bethanylang for restoring it!)

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified that on connecting analytics and AdSense module  prompt to link Analytics & AdSense is showing.
- Verified that on activating Ad blocker In the Top Earning Pages widget,  an ad blocker warning is showing.

**_Issue :_**  **_If AdSense module is shared then On View only dashboard error is showing._**

![image](https://github.com/google/site-kit-wp/assets/94359491/bc230fe9-f8b8-4cdb-90d4-51cd2563803f)

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/9e87f167-53a1-42c0-9674-75e739e01523)

![image](https://github.com/google/site-kit-wp/assets/94359491/d11d83ec-b791-45be-be37-e652071d505a)

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

@zutigrm 

- Tested on dev environment.
- Above mentioned issue is resolved now.
- Verified that if AdSense or Analytics and AdSense both are shared then on view only dashboard error is not showing for Analytics widgets.

**_Issue_** : As reported in slack earlier and in #6248 . I used oi.ie site for testing. Analytics and AdSense are already linked for this site but still on main dashboard under Monetization section prompt to link AdSense and Analytics is showing. 

![image](https://github.com/google/site-kit-wp/assets/94359491/24f986a9-db77-481b-9d48-d5832bf9d6df)

**Comment by zutigrm** [comment]
The real `adSenseLinked` setting value is not pulled yet, so we only default value is present, which is `false`, so it will always show connect section. The value will be fetched in other issue, see this [comment](https://10up.slack.com/archives/CBKKQEBR9/p1708076028509849?thread_ts=1708008350.641049&cid=CBKKQEBR9)

cc: @mohitwp @tofumatt

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that on view only dashboard both KM widget and Prompt are not showing.
- Verified that when `ga4AdSenseIntegration` feature flag is active then and only promot is showing.
- Verfied that when when `ga4AdSenseIntegration` feature flag is not active then promot is not showing.
- Verified that when Ad Blocker is active then warning message is appearing.
- Verified dashboard widget as well as KM Top earning pages widget.

**_Note : Putting note here to test again when #8019 get merge._**


<details>

**Main Dashboard -**

![image](https://github.com/google/site-kit-wp/assets/94359491/82a89048-159c-470c-b059-1fab69a5a2aa)

![image](https://github.com/google/site-kit-wp/assets/94359491/45f06b59-bc36-4736-9ac9-928a8bfe2e1e)


**View only dashboard -**

![image](https://github.com/google/site-kit-wp/assets/94359491/0bb70e2a-cae3-457b-87e4-f5940894cfeb)

![image](https://github.com/google/site-kit-wp/assets/94359491/c6fb0c26-9b10-4328-ac8c-c8d38cde9be6)

**Ad Blocker active**

![image](https://github.com/google/site-kit-wp/assets/94359491/4137a7c6-47b8-4b05-b37e-9ba43a0d7a24)

**Link both AdSense+GA4 via code **snippet****

**Main Dashboard -**

![image](https://github.com/google/site-kit-wp/assets/94359491/3e9b78d0-2613-4bda-9d82-b5a3430a40c9)

![image](https://github.com/google/site-kit-wp/assets/94359491/153eb684-bd44-4b93-a338-eacee0a4f8e2)



**View only dashboard -**

![image](https://github.com/google/site-kit-wp/assets/94359491/0f5cc689-4c3a-49b8-8449-8caff91b96b6)

![image](https://github.com/google/site-kit-wp/assets/94359491/eb860777-e82c-4c2f-96f7-8455bbc1accc)


</details>
