### ISSUE TITLE
Add `adSenseLinked` to Site Health information

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8051]
## Feature Description

The status of AdSense/Analytics linked accounts (eg. the value of the Analytics setting `adsenseLinked`, added in #8047) should be output in the Site Health information for Site Kit.

**NOTE:** This issue must be deployed in the same release as #6248 and #8050.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `adsenseLinked` setting should be output in the Site Health settings when both Analytics 4 and AdSense modules are connected.
  * If the setting is false, the output can be "Not connected"
  * If the setting is set, it can output "Connected".
* The `adSenseLinkedLastSyncedAt` value should be output.
  * If the `adSenseLinkedLastSyncedAt` setting is empty, output "Never synced"
  * If `adSenseLinkedLastSyncedAt` is not empty, output the time it was last synced, either as a UNIX timestamp or UTC value.

## Implementation Brief

* In `Google\Site_Kit\Modules\Analytics_4::get_debug_fields`:
  * [x] Add `AdSense Linked` field to the debug fields array. For value check for `adsenseLinked` settings and render the content from AC. For `debug` key, wrap the setting with `redact_debug_value` method
  * [x] Add `AdSense Linked Last Synced At` field to the debug fields array, like previously and output the content described in AC

### Test Coverage

* Update `tests/phpunit/integration/Modules/Analytics_4Test.php`, add 2 newly added keys to the list in `test_get_datapoints__news_key_metrics`

## QA Brief

* Connect and link the AdSense and Analytics modules
* Check the Site Heath information and see the two new fields:
   * AdSense Linked
   * AdSense Linked Last Synced At

## Changelog entry

* Add `adSenseLinked` to Site Health information.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by nfmohit** [comment]
The PR for this issue looks good and is approved. However, I'm keeping this stalled in MR as I can't merge it yet. According to the issue description, this should go out with the same release as #6248 and #8050.

**Comment by mohitwp** [comment]
QA Update :

Blocked due to issue mentioned under #6248 and #8050 .

cc @wpdarren @bethanylang

**Comment by mohitwp** [comment]
**QA Update**

- This issue is blocked due to #8049.
- Forcing linked status through this code `googlesitekit.data.dispatch('modules/analytics-4').setAdSenseLinked(true)` not changes infor under site heath info.
