### ISSUE TITLE
Setup fails for sites that have WordPress installed in a subdirectory

### ISSUE THREAD

**Issue by benoitchantre** [google/site-kit-wp#8058]
## Steps to reproduce

1. Setup a site where WordPress files are installed in a sub-directory (siteurl), but site URL (home) points to the main directory
2. Start the Google Site Kit configuration
3. See that you get a 404 when you are redirected to your site

## Additional Context

 - PHP Version: 8.1
 - OS: [e.g. iOS] : macOS 13.6.1
 - Browser: [e.g. chrome, safari] Firefox
 - Plugin Version: [e.g. 22] : 1.116
 - Device: [e.g. iPhone6] : Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi @benoitchantre thanks for opening this issue. There shouldn't be any issues when setting up Site Kit with WordPress installed in a subdirectory. This 404 error could be the result of an invalid record.

We don't provide support via GitHub but we will be happy to help you further with this if you could please [open a new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0). We look forward to assisting you there, thanks!
