### ISSUE TITLE
Test API data improperly cased

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#806]
## Bug Description

As part of our case/capitalization updates to the codebase in #694 a few places were changed which should not have been, particularly API responses used for tests.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Data mocking external API response data should follow that API's naming pattern, not our own.

## Implementation Brief

* See #807.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Discussed during morning touchbase that this isn't that QAable. I ran through a series of regression to ensure nothing was obviously broken.

Setup via proxy functioned properly
Setting up Analytics functioned properly
Setting up Adsense functioned properly
Disconnecting and reconnecting SK functioned properly
Activating an deactivating plugin functioned properly

Passed QA ✅
