### ISSUE TITLE
Increased calls to `GetProperty` of Admin API 

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8062]
## Bug Description

In #7734, we updated the way the `createTime` is retrieved from the connected GA4 property on the dashboard by storing it in a setting to avoid requesting the property on every page load. This has resulted in an increased number of calls to the `GetProperty` endpoint of the Analytics Admin API, a large percentage of which are failing due to lack of access.

## Additional Context

- [Internal](https://app.asana.com/0/0/1206264017095935/1206301873467362/f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* ~~Requests to `GetProperty` via the dashboard should be qualified before calling to ensure the current user first has access to the connected property~~  
_This may be skipped for now due to time constraints_
* A successful request of `GetProperty` on the dashboard should be cached for 1 hour
* The background job for synchronizing the property should not be retried more often than once every 30 min, similar to profile data

## Implementation Brief

* Update `assets/js/googlesitekit/datastore/site/cache.js`:
  * Add `getCacheItem` action, and `CACHE_GET_ITEM` controller, you can see how `setCacheItem` is implemented. It should retrieve cache by passed cache key using the `getItem` function.
* In `assets/js/modules/analytics-4/datastore/properties.js`  
  * Edit `getPropertyCreateTime` resolver, so that before `getProperty` request is made:
    * Check if user has access to the `analytics-4` module, using `hasModuleAccess` selector on `CORE_MODULES` store, to return early. This will verify if user has access to the connected property.
    * If user has access to the module, use the cache mechanism to determine if `getProperty` should be fetched, you can use cache key `analytics::property-{propertyID}::get` for example. It should be cached for 1 hour in case of successful response, and data should be retrieved from cache instead when present.
    * You can refer to this [example](https://github.com/google/site-kit-wp/blob/83b609ec0663e5b4f0bb1278249848f0e4b90ce1/assets/js/googlesitekit/datastore/user/feature-tours.js#L168-L172) for `setCacheItem` usage. And [here](https://github.com/google/site-kit-wp/blob/83b609ec0663e5b4f0bb1278249848f0e4b90ce1/assets/js/googlesitekit/api/index.js#L128-L180) for cache mechanism example, as well as timestamp constant.
* In `includes/Modules/Analytics_4/Synchronize_Property.php`
  * Update single event [schedule](https://github.com/google/site-kit-wp/blob/f73d32ad3b2fbc682b0b9ac4cb10838d135cb9ad/includes/Modules/Analytics_4/Synchronize_Property.php#L104) timestamp to be `30 * MINUTE_IN_SECONDS`

### Test Coverage

* Update `properties` and `cache` datastore tests to reflect the changes

## QA Brief

1. Set up Site Kit, including connecting a valid, existing Analytics 4 account with data.
2. Visit the Site Kit dashboard run the following scripts in the browser console one by one:
  i. `sessionStorage.clear()`
  ii. `localStorage.clear()`
  iii. `googlesitekit.data.dispatch( 'modules/analytics-4' ).setPropertyCreateTime( 0 )`
  iv. `googlesitekit.data.dispatch( 'modules/analytics-4' ).saveSettings()`
3. Refresh the Site Kit dashboard and ensure a request to `google-site-kit/v1/modules/analytics-4/data/property` is made.
4. Refresh the Site Kit dashboard again, ensuring this time a request to `google-site-kit/v1/modules/analytics-4/data/property` is NOT made.
    * In the same session, run the following script in the browser console and verify that it returns a positive integer: `googlesitekit.data.select( 'modules/analytics-4' ).getPropertyCreateTime()`.

Additionally:

* Go to Analytics Settings > Edit or Analytics setup. Observe the list of properties. Make a change to the list (eg. a property name, or add/remove a property to the account). Refresh the list of properties in Site Kit (by refreshing the Settings edit/setup page). The list should be immediately updated.

## Changelog entry

* Reduce frequency of requests made to GA4 Admin API on Site Kit dashboard.

**Comment by aaemnnosttv** [comment]
> In `assets/js/modules/analytics-4/datastore/properties.js`
> * Edit `getProperty` resolver, so that before property request is made:
>   
>   * Check if user has access to the `analytics-4` module, using `hasModuleAccess` selector on `CORE_MODULES` store, to return early. This will verify if user has access to the connected property
> * Update `fetchGetPropertyStore`, set [`useCache`](https://github.com/google/site-kit-wp/blob/f73d32ad3b2fbc682b0b9ac4cb10838d135cb9ad/assets/js/modules/analytics-4/datastore/properties.js#L61) to `true`. By default caching will be set to 1 hour, so no further edits are needed.

@zutigrm we don't want to modify all calls to `GetProperty`, only those that are used on the dashboard since these get called the most. Admin API calls are generally not cached since they're primarily used for module set up where we always want to fetch from the API.

One option would be to introduce a new selector for getting the property which uses caching. Alternatively we could potentially introduce cache into the resolver before calling `getProperty`, and handle the caching manually. Maybe something else. We also use `getProperty` in the GTE mismatch notification I believe but this is less of a concern than the `getPropertyCreateTime` resolver since this will be called every time.

> In `includes/Modules/Analytics_4/Synchronize_Property.php`
> * Update single event [schedule](https://github.com/google/site-kit-wp/blob/f73d32ad3b2fbc682b0b9ac4cb10838d135cb9ad/includes/Modules/Analytics_4/Synchronize_Property.php#L104) timestamp to be `30 * MINUTE_IN_SECONDS`

Ideally this would still invoke the first job immediately as today and then retries would run on the longer schedule.

> * Last requirement listed in AC is already [implemented](https://github.com/google/site-kit-wp/blob/f73d32ad3b2fbc682b0b9ac4cb10838d135cb9ad/includes/Modules/Analytics_4/Synchronize_Property.php#L82)

The problem with the current implementation is that it will try again right away if the sync fails. This is partially mitigated by the capability check, especially since the module owner should always have access, but it's of course possible that this could be lost. I suppose this is less of an issue with the increased timestamp in the interval. I'll update the AC to remove this point for now and we can re-evaluate once we see the difference this makes.

**Comment by zutigrm** [comment]
@aaemnnosttv Thank you for the feedback and clarfications.

> we don't want to modify all calls to GetProperty, only those that are used on the dashboard since these get called the most. Admin API calls are generally not cached since they're primarily used for module set up where we always want to fetch from the API.

> One option would be to introduce a new selector for getting the property which uses caching. Alternatively we could potentially introduce cache into the resolver before calling getProperty, and handle the caching manually. Maybe something else. We also use getProperty in the GTE mismatch notification I believe but this is less of a concern than the getPropertyCreateTime resolver since this will be called every time.

I updated this to modify `getPropertyCreateTime` resolver instead, and suggested using the manual cache, and also cache the module check as well, since it will make a request to check for access to the connected property, so was thinking about optimising it as well, by caching it also for 1h if it user has no access

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
I've adjusted the AC to allow for a smaller change to be made at this point given the proximity to the release. I've opened #8071 accordingly based on @tofumatt 's original PR.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Successfully ran the scripts in the QAB in console:
  - A request to `google-site-kit/v1/modules/analytics-4/data/property` is made.
  - I refreshed the Site Kit dashboard, and no request to `google-site-kit/v1/modules/analytics-4/data/property` was made.
  - A positive integer appears when `googlesitekit.data.select( 'modules/analytics-4' ).getPropertyCreateTime().` is run.
  - In Analytics Settings > Edit, when a change to the list (e.g., a property name is changed in Analytics) and the list of properties in Site Kit is refreshed, the change is immediately updated.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/4f4cc372-d133-4f80-bfde-0f0a5d76688e)
![image](https://github.com/google/site-kit-wp/assets/73545194/58053305-d100-4cb7-9304-d7b6d81b25d1)
![image](https://github.com/google/site-kit-wp/assets/73545194/304493f6-b324-40bb-8ca0-a9c57afff790)
![image](https://github.com/google/site-kit-wp/assets/73545194/fd2de1fe-4b01-42a5-bd12-1a030f6d464c)

</details>
