### ISSUE TITLE
Clean up unnecessary filter

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8073]
## Feature Description

When the `dashboardView` setting was removed, it ended up leaving behind a filter for dashboard sharing settings data which is now essentially unused and can be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The filter on `googlesitekit_dashboard_sharing_data` within the `Analytics` module class should be removed as it no longer modifies the filtered data.

## Implementation Brief

* [ ] Remove the [unused filter](https://github.com/google/site-kit-wp/blob/bd5892c89112179b54a8f9eda69f18564bac767f/includes/Modules/Analytics.php#L141-L150)

### Test Coverage

* No changes expected, but could be a test which asserts the filter is set may need removing

## QA Brief

* This is a simple cleanup of code that doesn't do anything, no QA necessary

## Changelog entry

* N/A

**Comment by techanvil** [comment]
No QA needed, moving straight to Approved.
