### ISSUE TITLE
Potential fatal error when previewing Customizer drafts

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8077]
## Bug Description

The theme customizer provides the ability to preview drafts using a special URL. While previewing, it is possible for Site Kit to raise an error such as the one below

```
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Google\\Site_Kit\\Core\\Util\\get_plugin_data() in /.../google-site-kit/includes/Core/Util/Auto_Updates.php:105
Stack trace:
#0 /.../google-site-kit/includes/Core/Util/Auto_Updates.php(56): Google\\Site_Kit\\Core\\Util\\Auto_Updates::sitekit_forced_autoupdates_status()
#1 /.../google-site-kit/includes/Core/Authentication/Authentication.php(902): Google\\Site_Kit\\Core\\Util\\Auto_Updates::is_plugin_autoupdates_enabled()
#2 /.../google-site-kit/includes/Core/Util/Method_Proxy_Trait.php(25): Google\\Site_Kit\\Core\\Authentication\\Authentication->inline_js_base_data()
#3 /.../example.com/public_html/...', referer: https://example.com/wp-admin/customize.php?return=%2Fwp-admin%2Fthemes.php
```

This is because the WP core function `get_plugin_data` is not loaded in this specific scenario.

## Steps to reproduce

1. Set up Site Kit
2. Enable a theme that supports the customizer, e.g. Twenty Twenty
3. Go into the customizer and make any change
4. Click the cog next to Publish and choose **Save Draft**
5. Follow the URL given to preview the draft
6. See error

## Screenshots

<img width="638" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/5da9aa41-6e35-4292-baca-a435b2add483">

<img width="731" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/49279dc8-95eb-4fdb-8bbd-98686c5eda57">

## Additional Context

Related support request
https://wordpress.org/support/topic/i-get-a-critical-error-but-only-through-customizer/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No errors should be raised by Site Kit while previewing a customizer draft

## Implementation Brief

* [ ] Update `Auto_Updates::sitekit_forced_autoupdates_status` to conditionally load `wp-admin/includes/plugin.php` if the `get_plugin_data` does not exist prior to calling

### Test Coverage

* No changes necessary

## QA Brief

* Follow the "Steps to reproduce" in the issue description.
* Verify that the reported error no longer occurs.

## Changelog entry

* Fix bug that occurs when previewing Customizer drafts.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Tested to ensure I could recreate the error message in the issue description on the latest release. 
- On the develop branch, I followed the steps to reproduce and the reported error no longer occurs.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/a2ce71b3-0d64-4f84-ad27-6da8efc52698)

![image](https://github.com/google/site-kit-wp/assets/73545194/d21b121e-4582-46b0-a04d-1f4880f2638c)

</details>
