### ISSUE TITLE
Prevent outputting UA tags

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8078]
## Bug Description

Issues #7924 & #7925 make the `analytics-4` module independent in terms of outputting GA4 tags. However, this has resulted in an issue where if a site had UA configured in Site Kit, many aspects of the tags are duplicated as now both `analytics` & `analytics-4` modules start outputting tags independently.

Since UA is now retired and there is no way to control its settings and behaviour in Site Kit, we can prevent Site Kit from outputting any UA-specific tags at this point.

## Steps to reproduce

1. Log into a site that has Site Kit set up with pre-existing UA property connected.
2. In the front-end, check the page source and observe that the Google Analytics tag is duplicated for both UA and GA4.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/20284937/f555b1b9-1598-433d-814b-aeef36505e81)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics module in Site Kit should no longer output any UA-specific tags.

## Implementation Brief

* [ ] In `includes/Modules/Analytics.php`:
  * [ ] Update the `register` method:
    * [ ] No longer hook the `register_tag` method to the `template_redirect` action.

### Test Coverage

* Fix any failing tests.

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing as an issue we'll address in follow-ups to #7924 and #7925.
