### ISSUE TITLE
Fix release automation workflow

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8092]
## Bug Description

In #603 we enhanced our GitHub actions workflows to include additional automation for publishing the release to wordpress.org. This was mostly completed but needs an additional fix before it can be used.

## Additional Context

See https://github.com/google/site-kit-wp/actions/runs/7546698648/job/20545191738

![image](https://github.com/google/site-kit-wp/assets/18395600/9086cab2-f6a3-4c06-b155-6144c2ffcba4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The workflow for publishing to wordpress.org should complete successfully using a dry-run

## Implementation Brief

* In the `.github/workflows/zips.yml` file:
  * Update `upload-to-cloud-storage` to run only when `github.event_name != 'workflow_dispatch'`.
  * Update `publish-to-wporg`:
    * Use `/tmp` as the `path` value in the download artifacts step
    * Update the extract step to use `unzip -d` to extract files from the archive into the current folder instead of using unzip and rm commands.

### Test Coverage

* N/A

## QA Brief

* Run the [Plugin Zip Files GitHub workflow](https://github.com/google/site-kit-wp/actions/workflows/zips.yml) **checking the "Run the publishing process without committing." box which runs the workflow as a dry run.

## Changelog entry

* N/A.

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov 

> * Update `upload-to-cloud-storage` to run only when `github.event_name != 'workflow_dispatch'`

Just to clarify, is this needed for the fix or just an optimization? I ask because this trigger was added before the publish job was added (I think mostly to address actions being cancelled, later addressed in 7806).

> * Update the `Extract` step in `build-zips`

How about we simplify it by downloading the artifact into another directory, like `/tmp` and then extract it with `unzip -d` into the working directory we're going to use to avoid deleting any files?

**Comment by eugene-manuilov** [comment]
> > * Update `upload-to-cloud-storage` to run only when `github.event_name != 'workflow_dispatch'`
> 
> Just to clarify, is this needed for the fix or just an optimization? I ask because this trigger was added before the publish job was added (I think mostly to address actions being cancelled, later addressed in 7806).

@aaemnnosttv it is an optimization to make sure that we don't upload archives to the cloud storage since it is not needed for publishing.

> > * Update the `Extract` step in `build-zips`
> 
> How about we simplify it by downloading the artifact into another directory, like `/tmp` and then extract it with `unzip -d` into the working directory we're going to use to avoid deleting any files?

Yes, I think this can work. Updated IB.

**Comment by aaemnnosttv** [comment]
> it is an optimization to make sure that we don't upload archives to the cloud storage since it is not needed for publishing.

@eugene-manuilov gotcha, thanks. I think this is where it would be more appropriate to upload the zips to the release upon a successful publish to wp.org https://github.com/google/site-kit-wp/issues/865 – let's see about doing that one next 👍 

IB ✅

**Comment by aaemnnosttv** [comment]
@techanvil @benbowler I took a quick look at this one and it looks like there is a small tweak still required here due to some confusion around the IB. I left a review on the PR to explain https://github.com/google/site-kit-wp/pull/8127#pullrequestreview-1846750775
