### ISSUE TITLE
Update usage of abandoned package

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8094]
## Feature Description

The [`true/punycode`](https://packagist.org/packages/true/punycode) package is no longer maintained and should be replaced.

Its repository suggests using [`symfony/polyfill-intl-idn`](https://packagist.org/packages/symfony/polyfill-intl-idn) as the recommended maintained replacement which is already installed as a dependency of `guzzlehttp/guzzle`. We should update our usage of the old package to use the proper PHP internals where safely polyfilled by the Symfony package.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `true/punycode` package should be removed as a dependency
	* Its use internally should be replaced by core PHP functions `idn_to_ascii` and `idn_to_utf8`
* The `symfony/polyfill-intl-idn` package should be required

## Implementation Brief

* [x] Add `symfony/polyfill-intl-idn` v1.19.0 as a direct PHP dependency (`require`) in `composer.json`.
    * [x] The version is important, as later version requires PHP7.
* [x] in `includes/Core/Util/URL.php`, refactor the class to replace the usage of `Google\Site_Kit_Dependencies\TrueBV\Punycode` with the native alternatives. which will be safely polyfilled by the aforementioned package. 
    * [x] Save the value of `Punycode::PREFIX`, `xn--` as a const field `Punycode_PREFIX` in the class.
    * [x] Replace the usage of `$punycode->decode` with `idn_to_utf8`.
    * [x] Replace the usage of `$punycode->decode` with `idn_to_ascii`.
* [x] Remove the `true/punycode` package from `composer.json`

### Test Coverage

* All tests should continue to pass. 

## QA Brief

* QA:Eng: Confirm the `permute_site_hosts` behaviour has not changed.

## Changelog entry

* Replace use of the abandoned `true/punycode` package with `symfony/polyfill-intl-idn`.

**Comment by tofumatt** [comment]
IB ✅

**Comment by zutigrm** [comment]
QA:Eng verified ✅ 

* `idn_to_utf8` and `idn_to_ascii` are tested in `URLTest::test_permute_site_hosts`
* Also did smoke test by connecting AdSense module

**Comment by aaemnnosttv** [comment]
I did a bit of extra testing here just because this has bitten us before when used in an environment without the `intl` extension just to make sure the polyfill is working as expected.

Confirmed that `idn_to_ascii` didn't exist from PHP
```
server:~/example.com$ php -r 'var_dump(function_exists("idn_to_ascii"));'
bool(false)
```

Confirmed `idn_to_ascii` was defined by the SK-loaded polyfill 👍
```
server:~/example.com$ wp shell
wp> $rf = new ReflectionFunction('idn_to_ascii')
=> object(ReflectionFunction)#2939 (1) {
  ["name"]=>
  string(12) "idn_to_ascii"
}
wp> $rf->isUserDefined()
=> bool(true)
wp> $rf->getFileName()
=> string(127) "/.../public/wp-content/plugins/google-site-kit/third-party/symfony/polyfill-intl-idn/bootstrap.php"
wp> 
```
