### ISSUE TITLE
`Cannot read properties of null (reading 'syncGoogleTagSettings')`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8102]
## Bug Description

The following error is being reported in our error logging.

```
Cannot read properties of null (reading 'syncGoogleTagSettings') in DashboardEntryPoint in RestoreSnapshots in ErrorHandler in ThemeProvider
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `syncGoogleTagSettings` action should be removed from the `DashboardEntryPoint` and re-introduced on the main dashboard in a way that should not be possible for the action not to exist (i.e. it should only be invoked when GA is connected)  
Note: this is probably only possible due to a race condition or the case where Analytics is disabled as an available module (see `googlesitekit_available_modules`)

## Implementation Brief

* [x] Remove `syncGoogleTagSettings` from `assets/js/components/DashboardEntryPoint.js`
* [x] In `assets/js/components/DashboardMainApp.js`
  * Introduce `syncGoogleTagSettings` action and in `useMount`, use existing variable `isGA4Connected` to check if module is connected, and if it is call the `syncGoogleTagSettings` action
 

### Test Coverage

* No update needed.

## QA Brief

* Follow the QAB within #6373 as a regression test for this issue since the Google Tag settings sync code is being moved.

### QA Eng (for service side engineers?)
* Verify that the `syncGoogleTagSettings` action is still dispatched and there are no errors being logged.

## Changelog entry

* Fix the Google Tag settings syncing problem.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@jimmymadon as per our conversation on Slack. 

On develop branch the notification is not appearing when I run the QAB tasks to delete the destination.  I run the code in console, refresh the dashboard, and the notification does appear on the latest release.  Sending this back for investigation.

This is what I see on the latest release
![image](https://github.com/google/site-kit-wp/assets/73545194/eb329250-541c-49a6-a0eb-38c1bf57ed09)

**Comment by aaemnnosttv** [comment]
I've opened an alternative PR #8150 which reverts the original and applies an alternative workaround. It doesn't entirely meet the AC but we'll follow up on this with a new issue to more properly address the root cause.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Followed the QAB within https://github.com/google/site-kit-wp/issues/6373 as a regression test for this issue since the Google Tag settings sync code is being moved.   Both banners appeared based on the scenarios covered. I also checked that the google tags changed when the CTA was clicked in all scenarios. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/32342378-e24e-4c5e-8541-3353dfb625d4)
![image](https://github.com/google/site-kit-wp/assets/73545194/ed5699f0-4f87-45c7-ab1d-6d5e0882c317)

</details>
