### ISSUE TITLE
Add `audienceSegmentation` feature flag

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8107]
## Feature Description

The `audienceSegmentation` feature flag should be added to Site Kit as a prerequisite for the Audience Segmentation feature development.

See [relevant section in design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?tab=t.0#heading=h.u26gj5vc0mo9).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `audienceSegmentation` feature flag should be added to Site Kit.
- The `audienceSegmentation` feature flag should appear in the tester plugin.

## Implementation Brief

- Add an `audienceSegmentation` feature flag to `feature-flags.json`.

### Test Coverage

* No new tests required.

## QA Brief

- The `audienceSegmentation` feature flag should appear in the tester plugin.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Thanks for adding this @bethanylang! The QA Brief should technically be added by the implementer, but it's such a trivial issue it's clear what it's going to be so no issue there. AC and IB both :white_check_mark: :)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified `'audiencesegmentation'` feature flag is added into tester plugin.

![image](https://github.com/google/site-kit-wp/assets/94359491/95ad317a-610a-40d8-88ba-4bfda24d7f89)
