### ISSUE TITLE
Add REST and datastore APIs for creating and retrieving audiences

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8108]
## Feature Description

Add the appropriate REST and datastore APIs for the Audience Segmentation feature. See [REST infrastructure](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?tab=t.0#heading=h.k5zlop41dsbg) and [Datastore configuration](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?tab=t.0#heading=h.g92nyr44l65o) in design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following REST endpoints should be implemented to create and retrieve audiences:
    * `GET:audiences`: Fetch the list of audiences from the [properties.audiences.list](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.audiences/list) endpoint. The Analytics API response should be directly returned.
    * `POST:create-audience`: Create an audience via the [properties.audiences.create](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.audiences/create) endpoint. The payload should be an [Audience](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.audiences) as defined by the Analytics API.
* An `audiences` datastore partial should be created to create and retrieve audiences using the above REST endpoints:
    * `getAudiences()`: Retrieve the list of audiences via `GET:audiences`.
    * `createAudience( audience )`: Create an audience via `POST:create-audience`.

## Implementation Brief

* [x] Create support for `PropertiesAudiences` which is missing in our `google-client-services` library. See point 3 of this [section](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.xzdztnujuhmm) in the design doc for more information.
    * [x] Within `includes/Modules/Analytics_4/GoogleAnalyticsAdmin/`, create a new class called `PropertiesAudiencesService.php`. This class should be similar to the `includes/Modules/Analytics_4/GoogleAnalyticsAdmin/PropertiesEnhancedMeasurementService.php` class. 
    * [x] The `construct` method should initialise the `properties_audiences` property as in the [older version of the client-services api](https://github.com/googleapis/google-api-php-client-services/blob/9a0bab5e4472d46bf979e06208da4bd03a5e6103/src/GoogleAnalyticsAdmin.php#L479-L483). Copy code that registers the `create` and `list` methods.
* [x] Within `includes/Modules/Analytics_4.php`, follow the pattern set by `enhanced-measurement-settings`:
    * [x] Define a new service `analyticsaudiences` in the `setup_services()` method that instantiates the service class created above. 
    * [x] Add the GET and POST endpoints to the `get_datapoint_definitions()` method using the newly defined service. The `request_scopes_message` should be 'You’ll need to grant Site Kit permission to create new audiences for your Analytics 4 property on your behalf.'
    * [x] Add the relevant endpoint cases within the `create_data_request()` method. Similar to the `GET:conversion-events` endpoint, for the `GET:audiences` endpoint, get the `propertyID` from settings and use it for the `parent` param (`properties/<propertyID>`) when calling `listPropertiesAudiences()`. Use the same for the `POST:create-audience` endpoint. The `$post_body` should be a new instance of the `GoogleAnalyticsAdminV1alphaAudience` class. First validate the fields within `$data['audience']` similar to how this is done within `POST:enhanced-measurement-settings` comparing fields within `$data['audience']` to valid [`audience` fields](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.audiences#Audience). Then pass the sanitized fields directly within `GoogleAnalyticsAdminV1alphaAudience` class's constructor.
    * [x] The responses do not need to be parsed (i.e. no changes should be needed within `parse_data_response`)
* [x] Within `assets/js/modules/analytics-4/datastore`, create `audiences.js`:
    * [x] Use `createFetchStore` to create:
        * `baseInitialState` should be an object with an `audiences` object inside.
        * [x] `fetchGetAudiencesStore`: Since the `propertyID` is fetched from settings within the back-end, we don't need to pass any params within the `controlCallback API.get` call to the `audiences` endpoint.
        * [x] `fetchCreateAudienceStore`: Similar to the `enhanced-measurement` partial store, create a `validateAudience( audience )` function that loops through a valid set of keys. Call the post endpoint created above within the `controlCallback => API.set` passing the audience object.

### Test Coverage

* [x] Add PHPUnit tests:
    * [x] Testing the GET endpoint for audiences can be similar to `test_get_conversion_events()`
    * [x] Testing the POST endpoint can be similar to `test_create_custom_dimension_*()` methods.
* [x] Add JSTests:
    * [x] Use `assets/js/modules/analytics-4/datastore/enhanced-measurement.test.js` as a guide for adding tests that cover the fetch stores created above.

## QA Brief

* Setup site kit and analytics
* On dashboard, without setting the feature flag, open a console and paste: `googlesitekit.data.select('modules/analytics-4').getAudiences()`
  * You should receive an error that route does not exists
* Enable `audienceSegmentation` feature flag, and paste `googlesitekit.data.select('modules/analytics-4').getAudiences()` in the console
  * It will make a network request. Paste the snippet again, it will output current audiences, by default you should see 2 items in the array, these are created by analytics by default
* Paste this snippet in the console:
```js
googlesitekit.data.dispatch('modules/analytics-4').createAudience({
        "description": "Description",
        "displayName": "Test Audience",
        "membershipDurationDays": -1,
        "filterClauses": [
            {
				"clauseType": "INCLUDE",
				"simpleFilter": {
					"scope": "AUDIENCE_FILTER_SCOPE_ACROSS_ALL_SESSIONS",
					"filterExpression": {
                        "andGroup": {
                            "filterExpressions": [
                                {
                                    "orGroup": {
                                        "filterExpressions": [
                                            {
                                                "dimensionOrMetricFilter": {
                                                    "atAnyPointInTime": null,
                                                    "fieldName": "newVsReturning",
                                                    "inAnyNDayPeriod": null,
                                                    "stringFilter": {
                                                        "caseSensitive": null,
                                                        "matchType": "EXACT",
                                                        "value": "new"
                                                    }
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    }
				}
			}
        ]
    })
```
* It will open `Additional Permissions Required` modal. Grant the permission, and after returning to the dashboard, paste that snippet again. It will make a new network request
* Paste again `googlesitekit.data.select('modules/analytics-4').getAudiences()` snippet in the console, it should output an array with newly created audience in it. note since we did not previously collected audiences we should see only new one in the datastore
* Go to `Analytics -> Admin -> Audiences`.  Verify that new Test audience is present. Then arhcive it
* Go to dashboard (refreshing the page so state is reset), and paste `googlesitekit.data.select('modules/analytics-4').getAudiences()` again. You should see the existing audiences populated in an array
* Then paste the snippet from above to create a new audience. Since `EDIT` scope is previously granted, this will create an audience straight away
* Paste the `getAudience` snippet in console again, you should see original array with newly created audience added to it

## Changelog entry

* Add infrastructure to read and create audiences.

**Comment by techanvil** [comment]
AC :white_check_mark:, over to you for the rest of the IB @jimmymadon :)

**Comment by techanvil** [comment]
IB :white_check_mark:

LGTM, nice one @jimmymadon. I've bumped the estimate to a 30 based on your note in the IB (which I have removed).

**Comment by zutigrm** [comment]
Grabbed it so I can have something to work on tomorrow, as my other issue will be wrapped

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.
- Verified the flow as per QAB.
- Verified this by creating new site and Setup site kit and analytics on it.
- Verified when `audienceSegmentation` feature flag was disabled.
- Also, verified when `audienceSegmentation` feature flag was enabled.
- Verified that network request was made as per QAB and AC.

@zutigrm I got expected output for all steps expect for one. 
In QAB it is mentioned that - `It will open Additional Permissions Required modal. Grant the permission, and after returning to the dashboard, paste that snippet again. It will make a new network request` But, while doing testing no Additional permission modal appeared and audience created without granting any permission during first attempt as well. 

Below is the screencast of complete flow.


https://github.com/google/site-kit-wp/assets/94359491/5702307b-a0a3-453c-899c-a82a809e5159

**Comment by zutigrm** [comment]
Hey @mohitwp, thank you for your observation. If permission modal is not poping, it means you already granted `EDIT` permission beforehand. Since this error is returned by the Google endpoint, and if permission is not present audience couldn't be created.

To simulate additional permission modal, you can reset the site kit and re-connect again. And then paste the snippet

**Comment by mohitwp** [comment]
Thanks @zutigrm !


### QA Update ✅ 

- Tested on dev environment.
- Verified the flow as per QAB.
- Verified this by creating new site and Setup site kit and analytics on it.
- Verified when `audienceSegmentation` feature flag was disabled.
- Also, verified when `audienceSegmentation` feature flag was enabled.
- Verified that network request was made as per QAB and AC.
- Verified that Additional permission modal is appearing if edit permission are not granted.

<details>

https://github.com/google/site-kit-wp/assets/94359491/5702307b-a0a3-453c-899c-a82a809e5159


https://github.com/google/site-kit-wp/assets/94359491/a3291d4a-331a-4441-8d09-b10205cd89d0



</details>

**Comment by aaemnnosttv** [comment]
## Approval

> * `GET:audiences`: Fetch the list of audiences from the [properties.audiences.list](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.audiences/list) endpoint. The Analytics API response should be directly returned.

@jimmymadon this isn't broken but it deviates from our convention to return the primary resource from the response (the list of audiences) rather than the full response directly.

Essentially, this means we should return `$response->getAudiences()` from `parse_data_response`. Would you please open a follow-up issue to address this? We'd need to update the datastore handling as a result as well.
