### ISSUE TITLE
Add the Setup CTA Banner initial view (Storybook)

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8109]
## Feature Description

Create the Setup CTA banner component, implementing its initial view, and add it to Storybook. See [Setup CTA Banner](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?tab=t.0#heading=h.f4g2vm7vw0r0) in design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new Storybook story should be added for the Setup CTA Banner component as per this [Figma mock](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1956-17850&mode=design&t=BC2ulhGciyTHhPhE-0).
    * The title, description, primary and secondary CTA buttons as well as the SVG should all be taken from the above Figma mock.
    * `isSaving` state: Clicking on the Primary CTA button should change the text of the button along with the loading spinner icon added as per this [Figma mock.](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1415-20091&mode=design&t=BC2ulhGciyTHhPhE-0)
* The Setup CTA Banner should follow the relevant Figma designs at mobile breakpoints (see the [phone](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1655-35687&mode=design&t=jLnCVzeKPyiRlUts-0) and [tablet](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1834-31500&mode=design&t=jLnCVzeKPyiRlUts-0) designs).

## Implementation Brief

 
**Component**
 - [ ] Create the new component file: `assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceSegmentationSetupCTAWidget.js` based on the component structure of`assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js` and `assets/js/components/KeyMetrics/KeyMetricsCTAContent.js` *without splitting the content into a separate sub-component as this components contents do not need to be shared.*
    - [ ] Create a new boolean `isSaving` local component state with `useState`, default to false.
    - [ ] Wrap the body in the `Widget` component adding the `noPadding` in order to correctly layout the SVGs later.
    - [ ] Lay out the Widget body out using a `Grid`.
    - [ ] Create component title as a `h3`
    - [ ] Create the description as a `p`
    - [ ] Use a `SpinnerButton` for the primary CTA, use `isSaving` component state for the `isSaving` prop.
    - [ ] Use a tertiary `Button` for the secondary CTA.
    - [ ] Export the three distinct SVGs from Figma for [desktop](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1415-20091&mode=design&t=BC2ulhGciyTHhPhE-0), [mobile](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1655-35687&mode=design&t=lWNyO6hFRhIKumb8-0) and [tablet](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1834-31500&mode=design&t=xBwlRZp9gSoPIW3G-0), adding them to the SVG folder `assets/svg/graphics/`.
    - [ ] Import the new SVGs to render them within this component.

**Styles and Responsiveness**
 - [ ] Create a new scss file: `assets/sass/analytics-4/components/audience-segmentation/_googlesitekit-audience-segmentation-setup-cta.scss` and use consistent class names for each styled Cell.
 - [ ] Apply font, and padding styles to each element of the widget to match [Figma mock](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1415-20091&mode=design&t=BC2ulhGciyTHhPhE-0) for desktop.
 - [ ] Import the mobile and tablet breakpoints in to the component:
```
const isMobileBreakpoint = breakpoint === BREAKPOINT_SMALL;
const isTabletBreakpoint = breakpoint === BREAKPOINT_TABLET;
```
 - For the mobile breakpoint:
    - [ ] Update the SCSS to adjust the title and description; font-size and margin differences using the `$bp-mobileOnly` breakpoint
    - [ ] Using `isMobileBreakpoint`, prevent rendering the SVG from the right of the widget and render the mobile only SVG below the widget text - *ensure this SVG has no margin and renders to the edge of the widget as in the mobile [Figma mock](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1655-35687&mode=design&t=lWNyO6hFRhIKumb8-0)
 - For the tablet breakpoint:
    - [ ] Update the SCSS to adjust the title and description; font-size and margin differences using the `$bp-tablet` breakpoint.
    - [ ] Using `isTabletBreakpoint`, prevent rendering the SVG from the right of the widget and render the tablet specitic SVG below the widget text - *ensure this SVG has no bottom margin and is centred along the bottom of the Widget as in the table [Figma mock](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1834-31500&mode=design&t=tPezNtITGaLYBf6I-0)

**Storybook**
 - [ ] Create a new story file `assets/js/analytics-4/components/AudienceSegmentation/AudienceSegmentationSetupCTAWidget.stories.js` using the base story boilerplate loading the new `AudienceSegmentationSetupCTAWidget` component in it's default (not `isSaving` state).

**VRT**
 - [ ] Add a VRT scenario for the above story.

### Test Coverage

* 

## QA Brief

* Visit Storybook at https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencesegmentationsetupctatile--default
* Ensure that the banner matches the design as per the FIgma mocks referenced in the issue description and AC
    * Checks to be done against Desktop, Tablet and Mobile viewpoints
* Click on the `Enable groups` CTA spinner button component
    * Ensure that it enters an `isSaving` state, i.e the spinner appears

## Changelog entry

* N/A

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by benbowler** [comment]
IB ready for IBR.

**Comment by bethanylang** [comment]
@benbowler Can you please add an estimate here? Just a reminder that estimates should be added at the IB stage before issues are moved to IBR. Thanks!

**Comment by techanvil** [comment]
Hi @benbowler, thanks for drafting this IB. Apologies, though, as the AC should have been clearer - the IB here should include the responsive design and not just the desktop view which is linked to in the first point. I've added an additional point to the AC to make this clear. (I should have spotted this while reviewing the AC; cc @jimmymadon).

So, on to the IB as specced. Using the `BannerNotification` is an understandable first choice here; however, I actually think we could potentially be better off _not_ attempting to reuse it here. Primarily this is due to the aforementioned responsive layout. It's a bit at odds with the current `BannerNotification` responsive behaviour, where the image tends to be at the top for mobile viewports.

You can see this for yourself, e.g. in [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-switchedtoga4banner--switched-to-ga-4-banner-after) for the `SwitchedToGA4Banner` component - add the following props and view it on your local Storybook: 

```diff
diff --git a/assets/js/components/notifications/SwitchedToGA4Banner.js b/assets/js/components/notifications/SwitchedToGA4Banner.js
index 3b1b7281f8..ccaec30aa7 100644
--- a/assets/js/components/notifications/SwitchedToGA4Banner.js
+++ b/assets/js/components/notifications/SwitchedToGA4Banner.js
@@ -140,6 +140,8 @@ export default function SwitchedToGA4Banner() {
 					? __( 'OK, Got it!', 'google-site-kit' )
 					: undefined
 			}
+			showSmallWinImage={ false }
+			format="larger"
 			WinImageSVG={ () => <GA4SuccessGreenSVG /> }
 		/>
 	);
```

Here `showSmallWinImage={ false }` ensures the graphic is displayed at mobile viewports; `format="larger"` that the graphic is displayed at the top and not the right-hand side for the tablet viewport.

If we _do_ want to reuse `BannerNotification` I think the cleanest way would be to add another `format` value that results in the cell order being reversed (see the use of `getImageCellOrderProperties()` and `getContentCellOrderProperties()`, and the related `getImageCellSizeProperties()` and `getContentCellSizeProperties()`).

We also have the issue of how the graphic spans the bottom margin in the design, i.e. there's no bottom margin for the graphic itself; this could potentially be a bit fiddly with `BannerNotification`. It's worth considering how we'd achieve this.

There are a few additional points to consider:
- How to achieve the rounded corners - sounds pretty basic but we might want to wrap it in `Widget`, seeing as it's got the general look and placement of other widgets.
- Another minor one, the title font in the Figma design uses the `headline/small` typography which is a bit smaller than the `BannerNotification` title, it's worth a mention if we are reusing it.
- Just a general comment on using `ctaComponent` to pass in a dismissal CTA; having to work around the `BannerNotification`'s stock dismissal handling is another aspect that makes me feel it's not such a good fit and a standalone component would be cleaner.

Anyhow, please take another look with these points in mind. Drop me a line if you have any questions; I'm interested to see what you think.

**Comment by benbowler** [comment]
@techanvil (c.c. @jimmymadon) I've reviewed the IB and updated it substantially based on the comments above. 

Key note: I've suggested the creation of a new `AudienceSegmentation` folder for the component and `audience-segmentation` folder for the SCSS. I know this is not a module but I expect there will be many components/SCSS files for this epic that will need to be created in a central location so these folders, if not already created in other IBs, will be created here for use in other elements of this feature in future.

Also I have not gone into detail in terms of the SCSS to write or the exact structure of the body of the widget. I'm assuming this level of detail is sufficient but I'm happy to add more if required.

**Comment by benbowler** [comment]
Thanks @techanvil, updated as per your points.

**Comment by techanvil** [comment]
Thanks @benbowler! This LGTM. I have made a small tweak - I had essentially meant you should replace the point starting "Creating the story file will create a new VRT" with one about creating a VRT scenario, so I have removed that line, I think the brief "Add a VRT scenario for the above story" stands well enough on its own.

IB :white_check_mark:

**Comment by techanvil** [comment]
Note, as discussed on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1707132930927679) I've tweaked the folders for the components and SASS for consistency with the new [code organization](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.mlj74m7pz9gr) section in the design doc.

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencesegmentationsetupctatile--default
- Verified and compared the title, description, primary and secondary CTA buttons as well as the SVG with Figma Design.
- Verfied the story in desktop, tablets and mobile viewports.

@10upsimon 

**_Issue 1_** > Verified Clicking on the Primary CTA button is not changing the text of the button along with the loading spinner icon added as per this [Figma mock.](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1415-20091&mode=design&t=BC2ulhGciyTHhPhE-0)

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/0659a588-8d88-4166-997f-078fb7c18713)

</details>

**_Issue 2_** > In mobile devices CTA Banner title size is 16px in Figma where as under actual implementation it is 22px.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/bacb68ec-886a-4fb6-88c0-ae6fa2305bae)

![image](https://github.com/google/site-kit-wp/assets/94359491/25b3fce0-2ed4-4980-91e4-e93ef198ebe2)

</details>

**Comment by 10upsimon** [comment]
@mohitwp I have corrected the 2 identified issues, back to you for QA again, thank you.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencesegmentationsetupctatile--default
- Verified and compared the title, description, primary and secondary CTA buttons as well as the SVG with Figma Design.
- Verfied the story in desktop, tablets and mobile viewports.
- Verified that issues reported [above](https://github.com/google/site-kit-wp/issues/8109#issuecomment-1980559695) are now resolved.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c01893b2-2903-4aa7-980d-8773a8fd4312)

![image](https://github.com/google/site-kit-wp/assets/94359491/336b8bb1-bbe0-4ee2-a506-df63e5fba901)

![image](https://github.com/google/site-kit-wp/assets/94359491/215059f1-1ea4-48be-828a-788f4bb50671)

![image](https://github.com/google/site-kit-wp/assets/94359491/6e951f9e-22bc-492a-9cc7-5559f1753c97)

![image](https://github.com/google/site-kit-wp/assets/94359491/b722d4c0-b1bc-4b78-8945-292091bab022)

</details>
