### ISSUE TITLE
Update the Modal Dialog component for error and confirmation actions (Storybook)

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8110]
## Feature Description

Add the Error Modal to Storybook. See [Error modal](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?tab=t.0#heading=h.z7d0ca9d4zpj) in design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing [`<ModalDialog>` component](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-modal-dialog--default) should be modified to look as per the new Audience Segmentation Modals [(Figma Mock)](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23073&mode=design&t=Mweov3vTn79xTlRi-0).
* When on mobile viewport, the corresponding [mobile design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1893-25309&mode=design&t=Mweov3vTn79xTlRi-0) should be followed.
* All existing uses of the `<ModalDialog>` component  mentioned below should be updated:
    * The [Disconnect](https://github.com/google/site-kit-wp/assets/1721319/3f411b4a-be4a-4673-b46c-07e04c6fbbdd) and [Reset Site Kit](https://github.com/google/site-kit-wp/assets/1721319/87302d3d-4dc1-4086-a3e0-98239f7e4f53) Modals with the `danger` property should be styled exactly as per the new [Error Modals](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23073&mode=design&t=Mweov3vTn79xTlRi-0).
    * The [Additional Permissions Required](https://github.com/google/site-kit-wp/assets/1721319/7e8c3a1f-6e21-42f4-85af-554a21ea0f1b) modal should be updated as per this [Figma mock](https://www.figma.com/file/nHnGFJizcJCyTVNZwLE8Vz/Site-Kit-Misc?type=design&node-id=0-2111&mode=design&t=ZAaEfm00jWpMjwiQ-0).
      *  Note however that the primary CTA text should remain as it is, i.e. _Proceed_.
    * The [Confirm Disconnect module](https://github.com/google/site-kit-wp/assets/1721319/9e30e89e-bf1f-4dfb-a24a-b9d1d067da80) modal which has multiple feature lines should be designed as per this [Figma mock](https://www.figma.com/file/nHnGFJizcJCyTVNZwLE8Vz/Site-Kit-Misc?type=design&node-id=0-1842&mode=design&t=ZAaEfm00jWpMjwiQ-0).
* All Storybook stories for each of the above components should be updated. Any old v5 format stories should be migrated to Storybook v6 stories.

## Implementation Brief

* [x] As defined in AC, update the `assets/js/components/ModalDialog.js` to match the new design. Some of the points to apply:
  * Text alignment is on the left for title and content
  * Buttons are grouped with the right alignment and new spacing between them
  * Buttons order is reversed - `handleConfirm` comes after `handleDialog`
  * Modal title can include SVG icon
* [x] Update the modal in components listed in AC, which can be edited respectively in:
  *  `assets/js/components/UserMenu/index.js` and `assets/js/components/ResetButton.js`
  * `assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js`
  * `assets/js/components/settings/SettingsActiveModule/ConfirmDisconnect.js`

### Test Coverage

* Update the edited components stories as defined in AC
  * `Additional Permissions Required` doesn't seem to have a story, it can be handy to use this issue to add it
  * `stories/reset-button.stories.js` uses the old storybook API. Move it to the `assets/js/components/ResetButton.stories.js` and adapt to the v6 API

## QA Brief

* Setup Site Kit
* Verify that modals mentioned in AC are matching the new Figma designs now, on desktop and mobile
* Note: font weight `500` in figma is slightly different how it is rendered in the browser, so slight difference might be noticeable
* To trigger `Disconnect` modal:
  * Click on the google account menu item in the top right user menu. From the drop down, select `Disconnect`
* To trigger `Reset site kit` modal:
  * Go to `settings -> admin settings -> reset site kit link` 
* To trigger `Additional Permissions Required` modal
  * Setup analytics, go to settings and change property to a - `setup a new property` option and click apply. It will trigger the modal
* To trigger `Confirm Disconnect module` modal:
  * Go to `settings -> connected services` and edit any of the modules. Click on CTA to disconnect the module
* Note, the default width of the modal in figma is `478px`, but after [discussion](https://10up.slack.com/archives/C01CA828ZPZ/p1707129589297719) with Sigal regarding the icon alignment, it is agreed that it will `590px`

## Changelog entry

* Implement refreshed UI for the modal dialog component.

**Comment by techanvil** [comment]
AC LGTM. I had initially envisaged that we'd create the presentational versions of the modal in its three variants as part of this issue, but with the existing Modal Dialog styled appropriately via this issue, it should be straightforward to implement the error modal variants as part of https://github.com/google/site-kit-wp/issues/8134.

AC :white_check_mark:

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
@zutigrm Can you please update the link to specific figma mock for [Additional Permissions Required](https://github.com/google/site-kit-wp/assets/1721319/7e8c3a1f-6e21-42f4-85af-554a21ea0f1b) and [Confirm Disconnect module](https://github.com/google/site-kit-wp/assets/1721319/9e30e89e-bf1f-4dfb-a24a-b9d1d067da80) ?

Current link in AC is not correct and when I selection iterations from the side menu then under it Figma mock for modal is not exist.

**Comment by zutigrm** [comment]
Hi @mohitwp , weirdly AC links lead to different design. The audience figma is [here](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1046-39085&mode=design&t=fF2ENKixdDj1VK1J-0), but I cannot see these two modals anymore. @techanvil do you know where these 2 modals went?

**Comment by techanvil** [comment]
Hi @zutigrm, those designs were in the [GA4-Updates](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&mode=design&t=8r7JcuhAmeEtweBu-0) Figma file, but I don't see them there any more either.

We had better check with @sigal-teller on this.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm In figma design CTA titles font is 'Google Sans Display' where as under Actual implementation font is 'Google Sans Text'. Is this expected ?

![image](https://github.com/google/site-kit-wp/assets/94359491/10bf5398-bc43-4e45-865b-a87400130e69)

![image](https://github.com/google/site-kit-wp/assets/94359491/3023a689-cfbb-4a9e-af7a-29fac4547df8)

**Suggestion** Q-2) Under disconnect module modal listed items font is 12px which is small and difficult to read. Can we increase it's size to 14px to make it more readable ?

![image](https://github.com/google/site-kit-wp/assets/94359491/a05a10ca-0ad5-47d0-a5e2-31b47dacd079)


- Tested on dev environment.
- Verified Disconnect modal.
- Verified Reset site kit modal.
- Verified Additional Permission Required modal.
- Verified Disconnect module modal.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/845e4cf3-4889-4eda-952e-a9378b117d8a)

![image](https://github.com/google/site-kit-wp/assets/94359491/c6ef4225-6094-4316-ba58-0516f069613e)

![image](https://github.com/google/site-kit-wp/assets/94359491/19d0bfb0-64bf-477f-b96a-64e5f1ce24ed)

![image](https://github.com/google/site-kit-wp/assets/94359491/f6d88d23-4173-45a0-80c5-33d5184dc854)

![image](https://github.com/google/site-kit-wp/assets/94359491/faa31c68-d3dd-4e02-94b3-b428ab34b017)

![image](https://github.com/google/site-kit-wp/assets/94359491/b2fa7b0d-1537-4235-bc8b-475271332fc8)

![image](https://github.com/google/site-kit-wp/assets/94359491/a40fb894-91e6-43e2-8286-3e5c6169c36f)

![image](https://github.com/google/site-kit-wp/assets/94359491/8af3bde5-db21-433c-a6b1-65cb4823da39)

![image](https://github.com/google/site-kit-wp/assets/94359491/a222237a-1643-4b73-b2ba-fff9baad8978)

![image](https://github.com/google/site-kit-wp/assets/94359491/9bf9c378-ff84-4145-afa9-b25912379e65)

![image](https://github.com/google/site-kit-wp/assets/94359491/6157a444-2a24-4bfb-82db-fdf737b17307)

![image](https://github.com/google/site-kit-wp/assets/94359491/0fa8827f-3dc7-4897-8b6f-51b8010322cc)

![image](https://github.com/google/site-kit-wp/assets/94359491/bfb74e21-ce73-4387-9015-89623386ed2e)

![image](https://github.com/google/site-kit-wp/assets/94359491/67aeaa65-533b-40b2-9c41-710e31c7cedf)

</details>

**Comment by zutigrm** [comment]
@mohitwp thank you for flagging this. 

> In figma design CTA titles font is 'Google Sans Display' where as under Actual implementation font is 'Google Sans Text'. Is this expected ?

It is not, I just realised we actually use 2 fonts. Thanks, I should create a follow-up issue for this.

> Under disconnect module modal listed items font is 12px which is small and difficult to read. Can we increase it's size to 14px to make it more readable ?

I will need to run this through SIgal, to see if it can be changed

**Comment by mohitwp** [comment]
@zutigrm Just a heads up, I noticed that on the latest environment, we're also using the 'Google Sans Text' font. Additionally, for the call-to-action (CTA) buttons under other notifications, the same font is being used.  It's important to note that this adjustment will impact the font for CTAs throughout the entire plugin.

cc @techanvil 

![image](https://github.com/google/site-kit-wp/assets/94359491/9d3528a6-6244-4c43-b762-96a933b3ed95)

![image](https://github.com/google/site-kit-wp/assets/94359491/a033b5b3-0ee3-4690-85d3-0b8ac88a31d8)

**Comment by zutigrm** [comment]
@mohitwp Since the font is changed globally we should open a new issue in that case, instead of making a change here, as global edit will fix all CTA's, and it is a different scope. 

Can you please open an issue for this? Thanks. I will wait for Sigal's reply regarding your suggestion to increase the features font to 14px, that we can do as a follow up to this issue, if Sigal approves it

**Comment by zutigrm** [comment]
@mohitwp Sigal approved the change - 14px for listed items. I sent follow up PR for that

**Comment by techanvil** [comment]
Back to you for another pass, @nfmohit.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that Disconnect module modal listing font size increase to 14px.
- Verified Disconnect modal.
- Verified Reset site kit modal.
- Verified Additional Permission Required modal.
- Verified Disconnect module modal.

**Note** : I will create separate ticket for the font issue as it will change CTA font globally.

![image](https://github.com/google/site-kit-wp/assets/94359491/b4bd386d-6724-4368-b6d4-2a98b7b42222)


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/42d05ee3-82b9-4a33-aa89-b451cc07c65d)

![image](https://github.com/google/site-kit-wp/assets/94359491/f8426ff9-6ec1-4d1a-85f5-ee8e2481da29)

![image](https://github.com/google/site-kit-wp/assets/94359491/845e4cf3-4889-4eda-952e-a9378b117d8a)

![image](https://github.com/google/site-kit-wp/assets/94359491/c6ef4225-6094-4316-ba58-0516f069613e)

![image](https://github.com/google/site-kit-wp/assets/94359491/19d0bfb0-64bf-477f-b96a-64e5f1ce24ed)

![image](https://github.com/google/site-kit-wp/assets/94359491/f6d88d23-4173-45a0-80c5-33d5184dc854)

![image](https://github.com/google/site-kit-wp/assets/94359491/faa31c68-d3dd-4e02-94b3-b428ab34b017)

![image](https://github.com/google/site-kit-wp/assets/94359491/b2fa7b0d-1537-4235-bc8b-475271332fc8)

![image](https://github.com/google/site-kit-wp/assets/94359491/a40fb894-91e6-43e2-8286-3e5c6169c36f)

![image](https://github.com/google/site-kit-wp/assets/94359491/8af3bde5-db21-433c-a6b1-65cb4823da39)

![image](https://github.com/google/site-kit-wp/assets/94359491/a222237a-1643-4b73-b2ba-fff9baad8978)

![image](https://github.com/google/site-kit-wp/assets/94359491/9bf9c378-ff84-4145-afa9-b25912379e65)

![image](https://github.com/google/site-kit-wp/assets/94359491/6157a444-2a24-4bfb-82db-fdf737b17307)

![image](https://github.com/google/site-kit-wp/assets/94359491/0fa8827f-3dc7-4897-8b6f-51b8010322cc)

![image](https://github.com/google/site-kit-wp/assets/94359491/bfb74e21-ce73-4387-9015-89623386ed2e)

![image](https://github.com/google/site-kit-wp/assets/94359491/67aeaa65-533b-40b2-9c41-710e31c7cedf)

</details>
