### ISSUE TITLE
React error breaking default setup flow

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#812]
## Bug Description

The default setup screen is blank

## Steps to reproduce

1. Attempt to set up Site Kit
1. Splash screen shows no interface

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/68388308-0082fe00-0169-11ea-8188-275f32e82d54.png)

## Additional Context

`develop` as of 2a701f7e824607c5fcb7aba6e4aebc3a9c03fe62

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Setup screens (old GCP & new default proxy versions) should render without error
* Both auth flows should be covered by E2E tests

## Implementation Brief

* Correct module import to fix error
* Add E2E test for new auth flow

## Changelog entry

*

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Tested on my Local using WP Version 5.2.4

**Pre-condition:**
Ran the following:
npm install
composer install
npm run release-zip

**Deactivate developer plugin with no other plugins loaded
Deleted my prior local instance of SK
Cleared Session storage**

Test steps:

1. Installed fresh zip that was created in the precondition
![image](https://user-images.githubusercontent.com/57115907/68409493-031b2e80-013c-11ea-9995-0a93fa98efbb.png)

2. Activated the plugin
![image](https://user-images.githubusercontent.com/57115907/68409551-1f1ed000-013c-11ea-8226-d0e3310327ef.png)

3. Clicked start setup
![image](https://user-images.githubusercontent.com/57115907/68409581-2fcf4600-013c-11ea-8790-daa7cab25622.png)

4. Checked conditions on the page for resetting SK
![image](https://user-images.githubusercontent.com/57115907/68410648-ec75d700-013d-11ea-9de0-b846f6a8e587.png)

5. Confirmed check box for helping SK usage is functional
![image](https://user-images.githubusercontent.com/57115907/68410717-0d3e2c80-013e-11ea-971f-247dc106f83a.png)

Confirmed 
Setup screens (old GCP & new default proxy versions) should render without error

Confirmed E2E flow functions via Jurassic Ninja
![image](https://user-images.githubusercontent.com/57115907/68412399-006f0800-0141-11ea-99f4-884cd9e7c3ee.png)

![image](https://user-images.githubusercontent.com/57115907/68413458-22698a00-0143-11ea-8903-d3e32ee1cd1d.png)

I noticed a few errors (below) during the setup confirming domain ownership. After a 3rd time I was able to successfully setup SK.

Errors:
![image](https://user-images.githubusercontent.com/57115907/68413524-488f2a00-0143-11ea-9b0b-8f9f062c2ace.png)
![image](https://user-images.githubusercontent.com/57115907/68413535-4fb63800-0143-11ea-96f2-eddbaa283d07.png)

Confirmed with the team that this is a known issue with the rate limit per our call this morning. 

Passing this ticket in QA! ✅
