### ISSUE TITLE
Improve the behavior within Site Kit for users creating a new AdSense account with a subdomain

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#8124]
## Bug Description

As raised by [a user in the Site Kit forums](https://wordpress.org/support/topic/cant-press-start-using-adense-button-on-sign-up-google-adsense/#post-17366399), AdSense is not allow users to proceed with a new account setup via Site Kit if a subdomain is used as a site URL. Unfortunately there is no notice from the AdSense side, or no warning, it's just the blue "Start using AdSense" button is unresponsive as per the screenshot below:

<kbd> ![image](https://github.com/google/site-kit-wp/assets/41326532/1b22d44d-3eb9-4112-9b9f-f8fe0c4dc7eb)

A recording of the user experience can be found below. 
https://www.loom.com/share/c6e828e1f3954af883425069363a941f

While this could be addressed on the AdSense side, to improve the experience for Site Kit users, consider one of the following improvements within Site Kit:
1. **Don't allow users to proceed to AdSense account creation if it's a subdomain being added**: If AdSense determines the Google account isn't associated with an AdSense account, don't allow them to proceed to the AdSense platform provisioning page.
3. **Change the URL being added to the parent domain**: There is a caveat with this suggestion, as users may not be in ownership of the parent domain. Site Kit also can't place AdSense code on the parent domain. Regardless, we could including a notice that the parent domain will be added as opposed to a subdomain, and that they will need to add AdSense code to their parent domain.

The URL passed to the AdSense provisioning page is below (with dummy URLs):
`https://adsense.google.com/adsense/signup/create?source=site-kit&utm_source=site-kit&utm_medium=wordpress_signup&url=https://subdomain.mysite.com/&referer=https://subdomain.mysite.com/`

The above won't allow the user to proceed making an AdSense account, but modifying the above URL to reflect the parent domain will. 

## Steps to reproduce

1. On a tastewp, instawp or another subdomain site, set up Site Kit using a Google account that isn't connected with AdSense
2. Connect the AdSense module
3. The blue button to "Start using AdSense" is unresponsive

## Additional notes

- All SK versions
- Occurs only for subdomains
- The AdSense platform could introduce a warning or popup notice to alert users
- This only occurs for subdomains, as is due to a subdomain being added. In AdSense, as of last year, as parent domain must be added. Any subdomain based off this parent domain can then be automatically approved. 

<details>
<summary>Console errors when clicking on the blue button
</summary>

 ![image](https://github.com/google/site-kit-wp/assets/41326532/715ca2f9-a70e-49cb-9d40-e2d3c7b98b49)

```
Uncaught Bad state: Future already completed
    at Object.b (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:694:19)
    at aY.b2 (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:17196:25)
    at P2.$0 (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:35611:13)
    at a2n.$10 (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:26047:40)
    at a2n.$2 (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:26053:13)
    at Object.arN (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:646:112)
    at Object.a47 (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:3373:19)
    at aw5 (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:4883:19)
    at https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:4879:42
    at Function.$2 (https://ssl.gstatic.com/display-ads-frontend-publisher-center/display-ads-frontend.publisher-center_20240121.02_p0/signup/signup_app.dart.js:57810:48)
```

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The URL Site Kit generates when sending users to create an AdSense account should be updated such that the `url` parameter refers to the top-level domain (i.e. no subdomains)
	* The implementation needs to be TLD-aware – this is already used somewhat in the module, see use of `parseDomain`

## Implementation Brief

* [x] Update `assets/js/modules/adsense/datastore/service.js` `getServiceCreateAccountURL` selector:
   * [x] Import `parseDomain` from `assets/js/modules/adsense/util/url.js`
   * [x] Change `query.url = siteURL;` to `query.url = parseDomain(siteURL);` - *parseDomain returns the domain without the protocol - I have tested this and you do not need to pass the protocol in the AdSense `url` GET attribute for the signup flow to detect and show the correct website in the account setup form.* 

### Test Coverage

* 

## QA Brief

* Test the "Steps to reproduce", confirm that, when setting up AdSense on a sub-domain site, the root domain is sent to the AdSense setup flow.

## Changelog entry

* Update the `url` parameter used in creating a new AdSense account not to contain subdomain information.

**Comment by aaemnnosttv** [comment]
We'll want to update the deep link on our end to modify the `url` to be the top level domain only if the site is on a subdomain.

**Comment by bethanylang** [comment]
@benbowler Can you please add an estimate here? Thanks!

**Comment by eugene-manuilov** [comment]
> The URL Site Kit generates when sending users to create an AdSense account should be updated such that the `url` parameter refers to the top-level domain (i.e. no subdomains)
> * The implementation needs to be TLD-aware – this is already used somewhat in the module, see use of `parseDomain`

@aaemnnosttv, i have two questions for your AC:

1. How do you envision this will work for multi-site sites where users can create their own subsites with unique sub domain names? The first one who create an adsense account, will have it for TLD and other users won't be able to set up their own accounts, right?
2. If I remember correctly, when we create an AdSense account, we need to verify it by placing a verification code on the site, right? Let's say we change SiteKit to use the top level domain for new accounts, but how will we place the site verification code on the master site from a sub site (especially if the SK plugin is not activated on the master site)?

**Comment by jamesozzie** [comment]
I'm happy to chime in here @eugene-manuilov 

> 1. How do you envision this will work for multi-site sites where users can create their own subsites with unique sub domain names? The first one who create an adsense account, will have it for TLD and other users won't be able to set up their own accounts, right?

Users can add a site to their AdSense account even if the site has been added to another users AdSense account. There's nothing stopping me from adding a domain I don't even own. It may fail the manual approval process, but the user would get an email to let them know why, including a possible email that verification failed. At the same time, there's also a chance that the site could be approved (but ads won't appear until my AdSense publisher ID is added to a snippet on that site).

I suspect that not having the snippet placed is also not a reason for not approving a site. [Here are the reasons](https://support.google.com/adsense/answer/81904?hl=en#:~:text=Insufficient%20content,-Your%20site%20was&text=Make%20sure%20that%20your%20site,code%20won't%20be%20approved.) why a site may not be approved. 

This probably requires more clarity from the AdSense side. 

> 2. If I remember correctly, when we create an AdSense account, we need to verify it by placing a verification code on the site, right? Let's say we change SiteKit to use the top level domain for new accounts, but how will we place the site verification code on the master site from a sub site (especially if the SK plugin is not activated on the master site)?

I believe this is a blocker on this. Maybe we could add a notice when adding a subdomain to let users know that their TLD must be approved for ads first.

**Comment by aaemnnosttv** [comment]
> * How do you envision this will work for multi-site sites where users can create their own subsites with unique sub domain names? The first one who create an adsense account, will have it for TLD and other users won't be able to set up their own accounts, right?

@eugene-manuilov As James mentioned above, it's not actually allowed to add a site with a subdomain anymore but this experience isn't handled well when we send folks to the AdSense FE to create an account.

When creating an account using the URL that SK provides, it makes the URL read-only and gives it a disabled style. This makes it hard to see the validation message that appears when attempting to create an account:

<img width="778" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/8d1d3737-35ea-4059-8757-192196cac5f7">


**The same message shown when signing up "manually" without `source=site-kit` and `url` parameters SK includes**

<img width="768" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/3e174551-9706-4801-95a5-7e60649e3c6f">

> * If I remember correctly, when we create an AdSense account, we need to verify it by placing a verification code on the site, right? Let's say we change SiteKit to use the top level domain for new accounts, but how will we place the site verification code on the master site from a sub site (especially if the SK plugin is not activated on the master site)?

When creating a new AdSense account, the AdSense tag needs to be placed on the page as a requirement for the account to be approved, but there is no separate code specifically for verification as there is for site verification which happens during initial SK connection. Again, since subdomain accounts/sites are not possible to add, this also would not be a concern.

**Comment by eugene-manuilov** [comment]
Ok, thanks @aaemnnosttv and @jamesozzie. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️  

@benbowler I get past the `Start using AdSense` button, and my AdSense account is created, but I am unable to verify my website.  The code is appearing in the source code. 

![image](https://github.com/google/site-kit-wp/assets/73545194/168bf0d8-9b44-47ac-b976-f2a01f61276f)

Admittedly, it has been a while since I created an AdSense account via Site Kit, but I am sure we don't usually have to manually verify it, and because we connected it via Site Kit this is set off automatically. 

I am wondering if this is an issue as a result of this change, or possibly not.   Maybe @jamesozzie could confirm what his expected behaviour is as I am starting to doubt myself as I write this!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When setting up AdSense on a sub-domain site, the root domain is sent to the AdSense setup flow. I clicked on the `Start using AdSense` button, and my AdSense account is created. 

![image](https://github.com/google/site-kit-wp/assets/73545194/b6a78caa-6563-4f81-927b-a31cf52cabcf)

**Note:** the experience for subdomains when setting up a new AdSense account could be improved to be more user-friendly.  I discussed this with @benbowler and @jamesozzie [on Slack here](https://10up.slack.com/archives/C0788NZMLF2/p1719258997449749) and we decided to create a new ticket to further improve the AdSense setup process for subdomains.
