### ISSUE TITLE
Add the Audience Tiles widget (Storybook)

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8136]
## Feature Description

Create the Audience Tiles widget component and add it to Storybook, showing the happy path audience tiles.

Note that this widget is displayed in a tabbed view for the mobile viewport while the desktop view is displayed as a list of tiles, and as a scrollable list at narrower desktop viewports when there are three tiles.

See [audiences tiles](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.h70ipgal0brg) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* A new component along with its Storybook story should be added for audience tiles widget.
* The UI should be similar to the [Figma designs](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1047-54324&mode=design&t=2z1vAdt3Izn46IIc-0) and necessary props should be added to the component to achieve it.
* The component should follow the relevant Figma designs at mobile breakpoints (see the phone and tablet designs).
	* On phones and tablets, the title is part of a tabbed component.
	* The component should be able to render one or more tiles title on phones/tablets.

## Implementation Brief

* [x] Add `Add assets/js/modules/analytics-4/components/widgets/AudienceSegmentation/AudienceTiles.js`
  * [x] It should accept `Widget` prop
  * [x] Add local state for managing the currently active tile, eg. `activeTile, setActiveTile`. This will be used to mobile view to determine the visible tile.
  * [x] Use `getConfiguredAudiences()` selector to retrieve configured audiences and save it in a variable, say `configuredAudiences`, which is implemented together with selector above in [8176](https://github.com/google/site-kit-wp/issues/8176)
  * [x] Make a report request using `getReport` action on `MODULES_ANALYTICS_4` datastore. You can see an example in any of the key metrics widgets on how to format `reportOptions` and handle `getReport`. The `reportOptions` object should:
    * [x] Include `audienceResourceName` in dimensions
    * [x] Add `dimensionFilters` for `audienceResourceName` dimension, with `inListFilter` type, and pass the `configuredAudiences` array which will hold the audiences name fields, which translate to `audienceResourceName` dimension. For an example on how to use this filter you can refer to this code https://github.com/google/site-kit-wp/blob/ab9d76bebe8a3368eaf73b194edf941fd42f2ec5/assets/js/modules/analytics-4/components/widgets/TopRecentTrendingPagesWidget.js#L121-L130
    * [x] Include the metrics and dimensions from the list, defined under `Metric definitions` in the [design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?pli=1#heading=h.lsud3imhtyov)
    * [x] Note that as pointed out in the design doc - `Pageviews` should be acquired in separate report request without `audienceResourceName` dimension included. And although not mentioned in design doc, potentially `Top content by pageviews` might need separate handling due to the `pagePaths` dimension which will need `getPageTitles` action to match the titles with paths, and also usage of custom dimensions. Refer to the `PopularContentWidget` component for usage example on titles.
  * Loading and errors are handled in separate issues, as well as placeholder tile
  * [x] Wrap the rendered output with `Widget` component, and add a class `googlesitekit-widget__audience-tiles` to it.
  * [x] Use `useBreakpoint` hook to extract the current device size
    * [x] In case of `BREAKPOINT_SMALL`, use `getAudiences()` selector to retrieve audiences, filtered to match only the ones in `configuredAudiences`. 
      * [x] You can use the `name` property of `getAudiences` for filtering. 
      * [x] Use `displayName` from results to collect the tiles titles and rendered them in separate `div` wrapper above the tiles. 
      * [x] Make use of `activeTile` to switch between tiles and conditionally render equivalent tile. 
      * [x] They should be styled as tabs, per [figma designs](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1644-30950&mode=design&t=ndvRgSeWLg7Q1PO4-0)
  * [x] Loop through `configuredAudiences` :
    * [x] Filter the report response data for `audienceResourceName` dimension, and prepare the values to match the required/expected props in `AudienceTile` implemented in [8135](https://github.com/google/site-kit-wp/issues/8135)
    * [x] Render `AudienceTile` component
* [x] Add `assets/sass/components/analytics-4/audience-segmentation/audience-tiles.scss` and apply the styles to match the figma designs linked in AC for desktop and mobile.
  * [x] Responsive breakpoints should follow the guidelines under `Responsive behavior` section of the [design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?pli=1#heading=h.b94t66x67hmv)

### Test Coverage

* Add stories and jest tests for `AudienceTiles` component

## QA Brief

* View the storybook story for the [AudienceTiles component](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencetiles--default), confirming that it meets the AC and matches the figma mocks.

## Changelog entry

* Add the Audience Tiles widget as a component in Storybook.

**Comment by eugene-manuilov** [comment]
> * A new Storybook story should be added for the audience tiles component as per the [design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.h70ipgal0brg).

@asvinb, this one is similar to #8135. We need to re-purpose AC to focus on the widget component creation as it is the main goal here. A new storybook story is just an addition to the new component to be able to see how it works since it won't be connected to the codebase yet.

**Comment by asvinb** [comment]
Thanks @eugene-manuilov . Let me know if it's clearer now. Thanks!

**Comment by eugene-manuilov** [comment]
Yes, thanks! AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by benbowler** [comment]
@techanvil I have an implementation in the attached PR, I've added details into the PR technical description. One thing I noted is that the report structure didn't really match the prop structure defined in the AudienceTile component which leads to a lot of [restructuring here in the AudienceTiles component](https://github.com/google/site-kit-wp/pull/8497/files#diff-b98ae699655ed97018f998b507c32bed7516182ee5675a84871b2972020283beR279-R399). We will have to do some form of restructuring however I think we could simplify this somewhat by adjusting the prop structure of the AudienceTile.

---

> Note: As https://github.com/google/site-kit-wp/pull/8395#discussion_r1530308111 on https://github.com/google/site-kit-wp/issues/8135, when implementing this issue we should consider updating the AudienceTile story to use generated mock report data to replace the hardwired data that it was initially implemented with.

As the AudienceTile component doesn't itself contain the selectors for the data, when looking into this, I ended up reimplementing AudienceTiles structure inside of the AudieceTile stories which was super messy IMO. Perhaps there is a middle ground or the boilerplate is worth it here to keep the stories setup consistent across stories?

**Comment by techanvil** [comment]
> @techanvil I have an implementation in the attached PR, I've added details into the PR technical description. One thing I noted is that the report structure didn't really match the prop structure defined in the AudienceTile component which leads to a lot of [restructuring here in the AudienceTiles component](https://github.com/google/site-kit-wp/pull/8497/files#diff-b98ae699655ed97018f998b507c32bed7516182ee5675a84871b2972020283beR279-R399). We will have to do some form of restructuring however I think we could simplify this somewhat by adjusting the prop structure of the AudienceTile.
> 
> > Note: As [#8395 (comment)](https://github.com/google/site-kit-wp/pull/8395#discussion_r1530308111) on #8135, when implementing this issue we should consider updating the AudienceTile story to use generated mock report data to replace the hardwired data that it was initially implemented with.
> 
> As the AudienceTile component doesn't itself contain the selectors for the data, when looking into this, I ended up reimplementing AudienceTiles structure inside of the AudieceTile stories which was super messy IMO. Perhaps there is a middle ground or the boilerplate is worth it here to keep the stories setup consistent across stories?

Thanks @benbowler. I'd agree that things can be simplified by modifying the prop structure of the `AudienceTile` component. I think it's a bit of an unnecessary abstraction the way it stands and it would make more sense to simply pass the reports directly in as props.

I realise it was a bit hard to figure this out in advance hence the current implementation, but I feel it could well be appropriate to add a followup issue to refactor the props as per the above. This should also allow us to make the stories more consistent as we'd simply need to provide the same sort of reports in both cases without much or any additional data manipulation.

I realise @zutigrm has made some suggestions for refactoring the data extraction which could improve things in this iteration, so let's take a look once you've addressed these and proceed with creating a followup issue for a refactor if it still seems appropriate; also, it might be worth simply not making these updates with the proposed refactor in mind.

**Comment by techanvil** [comment]
Thanks @benbowler. Good shout, #8484 looks like an appropriate issue to tackle this in. Please do go ahead as you have suggested. Cheers!

**Comment by benbowler** [comment]
Thanks @techanvil, I've [added a comment to #8484](https://github.com/google/site-kit-wp/issues/8484#issuecomment-2059400367), as well as inline comments, and moved this ticket back into review.

**Comment by techanvil** [comment]
Thanks @benbowler. As mentioned on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1713281583711679?thread_ts=1713277869.383479&cid=CBKKQEBR9) this should go back to @zutigrm to finish his review, so I've assigned it back to him. Although, if he's off tomorrow I'd be happy to pick it up myself.

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Hi @kuasha420 , this is looking good overall.
I need some clarification/guidance and raised a few points below for you to review if fixes are required:

**ITEM 1:**
The icons for the last two sections are currently not vertically centred.
They look closer to the top of the section. Per figma, they should be centred vertically.
<Details>

**Figma:** The arrows are the same size, which indicates equal distances top and bottom. On the last section, there is an extra space because of the margin of the entire card.
<img width="549" alt="Screenshot 2024-04-24 at 14 42 17" src="https://github.com/google/site-kit-wp/assets/125576926/4d80351d-6b84-461e-b65c-c342d865cc0e">


**Implementation:** The icons are closer to the top
<img width="258" alt="Screenshot 2024-04-24 at 14 41 54" src="https://github.com/google/site-kit-wp/assets/125576926/40b04d38-58e5-4d40-8719-35da5fe1e54c">

</details>
________________________________________________________________________

**ITEM 2:**
The 'U' is 'All Users' should be small caps, to keep it similar and consistent with other tabs.

<Details>
<img width="518" alt="Screenshot 2024-04-24 at 14 48 08" src="https://github.com/google/site-kit-wp/assets/125576926/2da1a22a-39f1-47ef-ab5f-80d61c5c856c">

</details>
________________________________________________________________________

**ITEM 3:**
Do we have to implement the 'Partial Data' under this ticket or another one? If another it's fine. (Refer to screenshots below)
Also, can we add a sample data to ensure we have captured the ellipsis for long content?  Screenshot below.
<Details>
Ellipsis and partial data highlighted:
<img width="618" alt="Screenshot 2024-04-24 at 14 50 09" src="https://github.com/google/site-kit-wp/assets/125576926/49bd7d06-0521-43ec-8234-7ce8e1a0b44f">

</details>
________________________________________________________________________

**ITEM 4:**
Is the section 'Understand how different visitor groups interact with your site' supposed to be part of the widget/component?
<Details>
<img width="701" alt="Screenshot 2024-04-24 at 14 58 49" src="https://github.com/google/site-kit-wp/assets/125576926/cc52a6c4-44f1-4aa9-8cf6-9c51cfd97ff3">

</Details>
________________________________________________________________________

**ITEM 5:**
Do we have a variation for 1 tile or 2 tiles? 
I just wanted to review the following parts from the PRD:
`At 961px and above, if there are two tiles they will be displayed in a list, each taking 50% of the available space.`
` Where only one audience tile is present, a placeholder tile will also be displayed, as we don’t want the single tile to expand to the full page width; note that this is only applicable to the desktop view,`
If those are outside of the scope for this ticket, we can ignore that for now.
________________________________________________________________________

**ITEM 6:**
Currently the last 2 sections of all 3 tabs point to the same data.
Any chance we could update each data for each tab differently so that we know it's dynamic? 
Again if this lies out of scope whereby these are just sample data without any real backend implication, then let's ignore.

<Details>
<img width="753" alt="Screenshot 2024-04-24 at 15 06 29" src="https://github.com/google/site-kit-wp/assets/125576926/b40138a7-2b60-4f00-a3d0-a4e315e664b1">

</Details>

**Comment by techanvil** [comment]
Hi @kelvinballoo, thanks for raising these points. I'm going to answer these as I've got more context on the issue and epic as a whole. I'll then let @kuasha420 create a followup PR to address what does need addressing here.

> **ITEM 1:** The icons for the last two sections are currently not vertically centred. They look closer to the top of the section. Per figma, they should be centred vertically.

Good spot - this should indeed be updated to vertically centre the icons as per Figma.

> **ITEM 2:** The 'U' is 'All Users' should be small caps, to keep it similar and consistent with other tabs.

This doesn't need addressing here. For a bit of context - we'll mostly simply be displaying the audiences names as they are set in Analytics - the capitalisation will therefore be up to the user's preferences for the most part.

That said, "All Users" is a special case as one of the default audiences. Because we _are_ going to be creating "New visitors" and "Returning visitors" with this capitalisation we do actually want to change the way we display the "All Users" audience for consistency, so your point is still valid.

However, we are going to be addressing this in a separate issue where we map "All Users" to "All visitors" - see https://github.com/google/site-kit-wp/issues/8487.

> **ITEM 3:** Do we have to implement the 'Partial Data' under this ticket or another one? If another it's fine. (Refer to screenshots below) Also, can we add a sample data to ensure we have captured the ellipsis for long content? Screenshot below.

The "partial data" badges will be implemented via a separate issue, see https://github.com/google/site-kit-wp/issues/8142.

Good shout about ensuring we capture the ellipses in Storybook though, this is worth an update here.

> **ITEM 4:** Is the section 'Understand how different visitor groups interact with your site' supposed to be part of the widget/component?

No, this will be addressed via https://github.com/google/site-kit-wp/issues/8138.

> **ITEM 5:** Do we have a variation for 1 tile or 2 tiles? I just wanted to review the following parts from the PRD: `At 961px and above, if there are two tiles they will be displayed in a list, each taking 50% of the available space.` ` Where only one audience tile is present, a placeholder tile will also be displayed, as we don’t want the single tile to expand to the full page width; note that this is only applicable to the desktop view,` If those are outside of the scope for this ticket, we can ignore that for now.

Adding a two-tile story is a good shout and can be addressed here.

However please note that the placeholder tiles will be covered in a separate issue, see https://github.com/google/site-kit-wp/issues/8146.

> **ITEM 6:** Currently the last 2 sections of all 3 tabs point to the same data. Any chance we could update each data for each tab differently so that we know it's dynamic? Again if this lies out of scope whereby these are just sample data without any real backend implication, then let's ignore.

This doesn't really need addressing as it's just sample data; that said it could be worth showing different data to help illustrate the fact that they are indeed using separate reports. If it's not too much effort I'd say it's worth addressing this here too.

Ok, over to you @kuasha420, please send it back to me for the followup CR :)

**Comment by kuasha420** [comment]
Thank you @kelvinballoo & @techanvil ! 

Based on your feedback, I've filed a [follow up PR](https://github.com/google/site-kit-wp/pull/8625) that fixes ITEM 1 and 5. 

Item 3 will be fixed via #8626 and ITEM 6 will be fixed by #8627 

Thank you.

**Comment by techanvil** [comment]
That's great, thanks @kuasha420.

Back to you for another pass, @kelvinballoo!

**Comment by kelvinballoo** [comment]
### QA Update :warning:

Thanks @kuasha420 , @techanvil 

Retested good for items 1 and 5.

**ITEM 1 RETEST**
The icons are not vertically centred.
<Details>
<img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bc40960784d29de9b06b36f8a23da372f37de02/Screenshot%202024-04-27%20at%2000.02.19.png" alt="Screenshot 2024-04-27 at 00.02.19.png" />

</Details>
____________________________________________________________

**ITEM 5 RETEST:**
There is now a 2 card layout and the cards expand 50:50 as we move from 961px wide and beyond.
<Details>
<img width="1383" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebdc283c3d2f7594a348db039a3e6dd1588858e1/Screenshot%202024-04-27%20at%2000.06.23.png" alt="Screenshot 2024-04-27 at 00.06.23.png" />

</Details>
____________________________________________________________


Understand that item 2, 3, 4 and 6 will be addressed in other tickets.

That said, I understood that the **_Ellipsis_** part under item 3 would be captured in this ticket.
Do we want to include it or address it in another ticket as well?

**Comment by techanvil** [comment]
Thanks @kelvinballoo. The ellipses will be covered in the followup issue https://github.com/google/site-kit-wp/issues/8626.

**Comment by kelvinballoo** [comment]
### QA Update ✅

Sounds good @techanvil .
Since there is no other outstanding item, I am moving this ticket to Approval.

**Comment by kelvinballoo** [comment]
### QA Update ✅

Sounds good @techanvil .
Since there is no other outstanding item, I am moving this ticket to Approval.
