### ISSUE TITLE
Implement the Info Notice message sequence

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8139]
## Feature Description

Implement the sequence of messages displayed in the Info Notice. This includes the dismissal of the messages and showing the next in the sequence after the specified delay.

See [info notice](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.8f364rk7fiu0) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Info Notice should display a sequence of messages.
- Each message should be shown individually until dismissed. On the next page load after 14 days have passed since the previous dismissal, the notice will be shown again displaying the subsequent message.
- A message is dismissed by clicking the **Got it** button. It will be permanently dismissed for the current user.
- The message sequence is as follows:
1. _The higher the portion of new visitors you have, the more your audience is growing. Looking at what content brings them to your site may give you insights on how to reach even more people._
2. _Select up to three visitor groups to display on the dashboard and easily compare metrics between them._
3. _Configure your own custom audiences in Analytics to gain deeper insights into visitor behavior, for example consider creating a “Existing customers” or “Subscribers” segment, depending on what goals you have for your site._
4. _Select the Purchasers visitor group to gain insights into which visitors bring the most revenue to your site._
5. _The more returning visitors your site has, the stronger and more loyal an audience you’re building. Check which content brings people back to your site - it might help you create a strategy to build a community._
6. _Compare the ratio of “new” to “returning” visitors – this can give you insights on whether you have more people stopping by as a one-off, or more loyal visitors._
7. _Check the cities which bring you more new vs more returning visitors – there might be new audiences you could engage with in locations you hadn’t thought about._

## Implementation Brief

* [x] We can use the `Prompts` infrastructure for the notices with "cooldown". 
* [x] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNoticeWidget/constant.js`:
    * [x] Create a new const `AUDIENCE_INFO_NOTICE_KEY` for the prompt slug. 
    * [x] Define another constant `AUDIENCE_INFO_NOTICES` which should be an array and have the messages stored as defined in the AC in sequence. 
* [x] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNoticeWidget/index.js`:
    * [x] Get whether the info notice is dismissed using `isPromptDismissed` selector.
    * [x] Get the dismissed count using the `getPromptDismissCount` selector. 
    * [x] Using the dismissed count, dynamically assign the value of `content` prop of the `InfoNotice` from the previously defined `AUDIENCE_INFO_NOTICES` array. ie. `content={ AUDIENCE_INFO_NOTICES[ dismissCount ] }`
    * [x] Render the `InfoNotice` when the notice is not dismissed. ie. `isDismissed === false`, otherwise render `null`. 
    * [x] For the `onDismiss` callback, dismiss the info notice using the `dismissPrompt` action, passing in two weeks in seconds when the `dismissCount` is less than the length of the `AUDIENCE_INFO_NOTICES` array, otherwise dismiss permanently by omitting the `expiresInSeconds` parameter. 

### Test Coverage

* Add stories for all states of the widget in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNoticeWidget/index.stories.js`
* Add component test coverage in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNoticeWidget/index.test.js`

## QA Brief

1. Enable the audience segmentation feature.

2. Visit the dashboard there should be the notice and the first message in the given list should be visible.

```plaintext
The higher the portion of new visitors you have, the more your audience is growing. Looking at what content brings them to your site may give you insights on how to reach even more people.
```

3. Click "Got it" button, it should trigger a request to `core/user/data/dismiss-prompt` and hide the prompt.

4. Refresh the page and the info notice widget should not be visible again.

5. Run the following command in browser console.

```js
googlesitekit.data.select('core/user').getDismissedPrompts()
```

It should give `audience-segmentation-info-notice` in the list of dismissed prompts.

6. Run the following command in browser console, it should give `1` as the dismissed count.

```js
googlesitekit.data.select('core/user').getPromptDismissCount('audience-segmentation-info-notice');
```

7. Run following command in browser console to further dismiss the item (programatically).

```js
googlesitekit.data.dispatch('core/user').dismissPrompt(
    'audience-segmentation-info-notice',
    {
        expiresInSeconds: 1209600
    }
);
```

8. Again check the count for dismissed prompt, it should be incremented to `2`.
9. Once a notice is dismissed, it takes two weeks for the next notice to appear. To be able to see any notice immediately, try the following script in the browser console:
```js
googlesitekit.data.dispatch('core/user').receiveGetDismissedPrompts( {
    'audience-segmentation-info-notice': {
        expires: Math.floor( Date.now() / 1000 ) - 10,
        count: 0 // Change this to any number of notice that you intend to see (0 - 6).
    }
} );
```

## Changelog entry

* Update audiences widget area to show multiple notices in sequence.

**Comment by nfmohit** [comment]
Nice work on the IB, thank you, @kuasha420! I just have a couple of minor suggestions:

1. > * Using the dismisssed count, dynamically assign the value of `content` prop of the `InfoNotice` according to the ACs. A switch statement seems appropriate here for implementation.
    - Instead of a switch statement, I think it might be more efficient to create an object with keys being the appropriate dismiss counts and values being their subsequent notice messages. However, we can leave this to be decided during execution, but this could be a nice additional proposal.
2. Do you think it might be worth adding some test coverage for the component to verify that the notice sequence works? This is also somewhere the object suggested above could be useful as a constant for example.

Let me know what you think, thank you!

**Comment by kuasha420** [comment]
Thank you @nfmohit, that's some great suggestion that will improve the implementation. I've updated my IB to use an array to store the messages and use the array index in conjunction with the `dismissCount` to select the correct message. Let me know what you think. Cheers.

**Comment by nfmohit** [comment]
Thanks, @kuasha420! IB ✅

**Comment by ankitrox** [comment]
Thank you @nfmohit for reviewing the PR and adding your valuable feedback there.

I have addressed the feedback added to the PR and tested again.

Assigning this to you for re-review.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Tested this and it's looking good.

- A message is dismissed by clicking the Got it button. 
- The messages are displayed in sequence accordingly.
- Clicking on "Got it" button triggers a request to core/user/data/dismiss-prompt and hide the prompt.
- After dismissing the message and refreshing the page, the info notice widget is not visible again.
- After dismissing the message programmatically and getting the dismiss count, it's incremented by 1.

⚠️  2 items to highlight:
**ITEM 1**
I spotted a possible mistake in the copy of the 3rd message:
`Configure your own custom audiences in Analytics to gain deeper insights into visitor behavior, for example consider creating **a** “Existing customers” or “Subscribers” segment, depending on what goals you have for your site.`

By right, 'a' should actually be 'an' as the next word is 'Existing' which starts with a vowel.
Assigning this to @wpdarren to review.

**ITEM 2:**
Also @wpdarren , it's worth noting that we are only testing the 14 days based on programme here and not based on real life time measurement. Do you have any concern for that? Tastewp sites that I create also wouldn't last until 14 days.


<Details>
Message 1:
<img width="1076" alt="Screenshot 2024-06-18 at 17 51 09" src="https://github.com/google/site-kit-wp/assets/125576926/0c863c59-8633-4577-94c7-76a7bbf4ee48">

Message 2:
<img width="1108" alt="Screenshot 2024-06-18 at 17 31 21" src="https://github.com/google/site-kit-wp/assets/125576926/65d5c594-2b5b-4f27-a243-4521d665d554">

Message 3:
<img width="1068" alt="Screenshot 2024-06-18 at 17 31 53" src="https://github.com/google/site-kit-wp/assets/125576926/4bc511d4-6d2a-4bae-946e-3ac3deee3834">

Message 4:
<img width="1095" alt="Screenshot 2024-06-18 at 17 54 17" src="https://github.com/google/site-kit-wp/assets/125576926/defa3dd5-d90c-4f50-be62-7b97aff2d1b0">

Message 5:
<img width="1092" alt="Screenshot 2024-06-18 at 17 44 36" src="https://github.com/google/site-kit-wp/assets/125576926/042d6d94-11a3-4872-bcdb-660125ca9a02">

Message 6:
<img width="1094" alt="Screenshot 2024-06-18 at 17 45 30" src="https://github.com/google/site-kit-wp/assets/125576926/c0d44167-cd05-4b2a-866c-42599eadb711">

Message 7:
<img width="1062" alt="Screenshot 2024-06-18 at 17 45 43" src="https://github.com/google/site-kit-wp/assets/125576926/cc41d2c6-000d-43ba-8115-768e3fd4191c">

Clicking 'Got it' triggers a request to core/user/data/dismiss-prompt and hide the prompt.
<img width="1217" alt="Screenshot 2024-06-17 at 18 14 09" src="https://github.com/google/site-kit-wp/assets/125576926/3bd9fcc5-aa98-494b-9b30-89700aae8790">

</Details>

**Comment by wpdarren** [comment]
@kelvinballoo responses to your questions. 

> By right, 'a' should actually be 'an' as the next word is 'Existing' which starts with a vowel.
Assigning this to @wpdarren to review.

I agree that this should be `an` rather than `a` - I am unsure who agreed the copy, but we should ask @ankitrox to change. 

> Also @wpdarren , it's worth noting that we are only testing the 14 days based on programme here and not based on real life time measurement. Do you have any concern for that? Tastewp sites that I create also wouldn't last until 14 days.

I don't think this needs to hold us from moving this ticket forward (when the copy change is made) but, you could create an InstaWP site using our paid account as these sites last for 30 days.  Then put a note in your calendar to check in 14 days time. That might be the better way to make 100% sure its behaving as expected.

**Comment by kelvinballoo** [comment]
Thanks @wpdarren .

Assigning ticket to @ankitrox to change the copy.
@ankitrox , this is a very simple change for the 3rd message. Refer to item 1 from : https://github.com/google/site-kit-wp/issues/8139#issuecomment-2176185210

**Comment by ankitrox** [comment]
Created a [fix PR](https://github.com/google/site-kit-wp/pull/8899) for typo fix. 
Moving it to CR.

**Comment by techanvil** [comment]
Back to you for another pass, @kelvinballoo!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested the copy change and it's looking good.
As for the real life testing of the message reapparance after 14 days, I've set it in my calendar to test it.
As for now, I'm moving this ticket to approval.

- A message is dismissed by clicking the Got it button. 
- The messages are displayed in sequence accordingly.
- Clicking on "Got it" button triggers a request to core/user/data/dismiss-prompt and hide the prompt.
- After dismissing the message and refreshing the page, the info notice widget is not visible again.
- After dismissing the message programmatically and getting the dismiss count, it's incremented by 1.


<Details>
Message 1:
<img width="1076" alt="Screenshot 2024-06-18 at 17 51 09" src="https://github.com/google/site-kit-wp/assets/125576926/0c863c59-8633-4577-94c7-76a7bbf4ee48">

Message 2:
<img width="1108" alt="Screenshot 2024-06-18 at 17 31 21" src="https://github.com/google/site-kit-wp/assets/125576926/65d5c594-2b5b-4f27-a243-4521d665d554">

Message 3:
<img width="1145" alt="Screenshot 2024-06-20 at 20 14 21" src="https://github.com/google/site-kit-wp/assets/125576926/520d4ae9-4750-4cc7-a5bb-4f9f8923e2cb">

Message 4:
<img width="1095" alt="Screenshot 2024-06-18 at 17 54 17" src="https://github.com/google/site-kit-wp/assets/125576926/defa3dd5-d90c-4f50-be62-7b97aff2d1b0">

Message 5:
<img width="1092" alt="Screenshot 2024-06-18 at 17 44 36" src="https://github.com/google/site-kit-wp/assets/125576926/042d6d94-11a3-4872-bcdb-660125ca9a02">

Message 6:
<img width="1094" alt="Screenshot 2024-06-18 at 17 45 30" src="https://github.com/google/site-kit-wp/assets/125576926/c0d44167-cd05-4b2a-866c-42599eadb711">

Message 7:
<img width="1062" alt="Screenshot 2024-06-18 at 17 45 43" src="https://github.com/google/site-kit-wp/assets/125576926/cc41d2c6-000d-43ba-8115-768e3fd4191c">

Clicking 'Got it' triggers a request to core/user/data/dismiss-prompt and hide the prompt.
<img width="1217" alt="Screenshot 2024-06-17 at 18 14 09" src="https://github.com/google/site-kit-wp/assets/125576926/3bd9fcc5-aa98-494b-9b30-89700aae8790">

</Details>
