### ISSUE TITLE
Implement the zero data state of an Audience Tile

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8143]
## Feature Description

Implement the zero data state of an audience. This includes the “temporarily hide” behavior.

See [audience tiles > zero data](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.9bk1qeu15e70) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Given that a selected audience is in the "partial data" state, and it has zero data for the current date range:
  - Its Audience Tile should be displayed in the "zero data" variant.
  - It should be implemented as per the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1046-43397&mode=design&t=1kQrHiaGkz5GbkrD-0).
  - If there is only one audience in the audience selection, the copy for the descriptive text should be:
      - _Site Kit is collecting data for this group_
  - If there are multiple audiences in the audience selection:
    - The copy for the descriptive text should be:
      - _Site Kit is collecting data for this group. You can hide this group until data is available._
    - The tile should have a **Temporarily hide** CTA.
    - Clicking on **Temporarily hide** will hide the tile, until the audience is determined to be in a non-zero data state on a subsequent page load.

## Implementation Brief

- [x] Create two new components `AudienceTileCollectingData` and `AudienceTileCollectingDataHideable`.
  - [x] As per the [Figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1046-43397&t=5lcdY6YTTnP9hXdz-0):
    - [x] `AudienceTileCollectingData` will display the SVG icon and the text "Site Kit is collecting data for this group.".
    - [x] `AudienceTileCollectingDataHideable` will display the SVG icon, the text "Site Kit is collecting data for this group. You can hide this group until data is available." and the "Temporarily hide" link.
      - [x] Clicking the `Temporarily hide` CTA should dispatch a `dismissItem` action with `audience-tile-${audienceResourceName}` for the slug and `0` for the expiration.
- [x] In the `AudienceTiles` component:
  - [x] Refer to the main [report](https://github.com/google/site-kit-wp/blob/a28dafd61dcd489f3962ec88345774b9a8983f55/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTiles.js#L76-L90) for the configured audiences:
    - [x] Create a function `hasZeroDataForAudience` inside the component to check if the slice of the report that relates to the specific audience has zero data.
    - [x] `hasZeroDataForAudience` should accept `audienceResourceName` as the parameter.
    - [x] `hasZeroDataForAudience` should check for a row where the `audienceResourceName` dimension matches the audience's name, and verify that it has a non-zero count for the `totalUsers` metric.
  - [x] To check if an audience is in the partial state, use the `isAudiencePartialData` [selector](https://github.com/google/site-kit-wp/blob/5d1b1b7de7c52b230b8d3746ac81848f615ca140/assets/js/modules/analytics-4/datastore/partial-data.js#L446-L452) of the `analytics-4` module.
  - [x] To check if an audience has zero data, use the function `hasZeroDataForAudience` created previously.
  - [x] Create a new `visibleAudiences` array - it should initially be created from `configuredAudiences`.
    - [x] Iterate over the audiences in reverse order (this is so we end up with the _first_ audience remaining in the list in the edge case where all of the `configuredAudiences` have been temporarily dismissed).
    - [x] If an audience has been temporarily hidden:
      - [x] If the audience has zero data, and `visibleAudiences` still has a length greater than 1, remove the audience from `visibleAudiences`.
      - [x] If the audience has non-zero data, clear the item from dismissed items. To clear the dismissed item, we do not have an explicit API, but it can be achieved by re-dismissing the item via the `dismissItem` selector with a very short expiry time (for example, 1 second).
  - [x] Map over `visibleAudiences` and do the following:
    - [x] If the audience is in the partial data state and has zero data:
      - [x] If the length of `visibleAudiences` is only 1, display the `AudienceTileCollectingData` component.
      - [x] If the length of `visibleAudiences` is greater than 1, display the `AudienceTileCollectingDataHideable` component.
    - [x] Otherwise, render the `AudienceTile` component as it is doing in the current implementation.

### Test Coverage

1. Add stories for the `AudienceTileCollectingData` and `AudienceTileCollectingDataHideable` components.
2. Add a story and VRT scenario for the `AudienceTiles` component which shows both of the above components.

## QA Brief

- Set up Analytics and configure audiences to test the zero data state for audience tiles.
- To properly test the flow, ensure you have at least two or three audience tiles set up:
   - One tile with data.
   - One tile without data (zero data) for the audience.
   - Optionally, a third tile to test the multi-audience scenario.

1. **Verify Zero Data State for Audience Tile**
   - Ensure the audience tile widgets correctly displays the zero data variant for an audience in the "partial data" state with zero data for the given date range.
   - Test scenarios:
     - **Single Audience**: Ensure the text reads "Site Kit is collecting data for this group." and does not include the "Temporarily hide" CTA.
     - **Multiple Audiences**: Ensure the text reads "Site Kit is collecting data for this group. You can hide this group until data is available." and includes the "Temporarily hide" CTA.

2. **Temporarily Hide Audience Tile**
   - Verify the functionality of the "Temporarily hide" CTA:
     - Clicking the "Temporarily hide" CTA should hide the corresponding audience tile.
     - Open the network tab and ensure an API request is made to `dismiss-item` endpoint with the correct parameters: `audience-tile-${audienceResourceName}` for the slug and `0` for the `expiration`.
     - Check that the tile remains hidden until the audience has non-zero data for the total users metric.

3. **Reappearing the Temporarily Hidden Tile**
   - To test the reappearance of a temporarily hidden tile, delete the `wp_googlesitekitpersistent_dismissed_items` item from the `wp_usermeta` table in the database. This will reset the dismissed state and allow the tile to reappear.
   - Ensure the tile reappears correctly after the item is deleted from the database.
   - To actually test the reappearing tile, you may need to wait for report data to be available for the audience.

5. **Component Stories**
   - Verify the following stories in the Storybook:
     - [AudienceTile->ZeroDataHideable](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencetile--zero-data-hideable).
     - [AudienceTile->ZeroDataNonHideable](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencetile--zero-data-non-hideable).
     - [AudienceTilesWidget->DefaultWithZeroTile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencetileswidget--default-with-zero-tile).
     - [AudienceTilesWidget->TwoTilesWithZeroTile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencetileswidget--two-tiles-with-zero-tile).
     - [AudienceTilesWidget->SingleZeroTile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencetileswidget--single-zero-tile).

## Changelog entry

* Show an Audience Tile in a zero-data state, and allow it to be temporarily hidden.

**Comment by ankitrox** [comment]
Hi @techanvil ,

Thank you for reviewing the IB and adding the feedback. I have addressed the points you mentioned and revised the IB description.

Assigning this to you for re-review.

Thank you.

**Comment by techanvil** [comment]
Hey @ankitrox, thanks for updating the IB. I've actually updated it further myself; I had started a minor update to correct some grammatical points and a couple of minor errors, however, it ended up being more of a rewrite than I'd initially intended.

Please can you review the changes, again if you are happy then feel free to move it to the EB.

I'll give this an IB :white_check_mark: for now but if you want to discuss any of it just let me know :)

**Comment by ankitrox** [comment]
Thank you @techanvil . I have reviewed the changes and those are looking good to me, so moving this to EB.

Thanks again!

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

I tested this but some parts are not working out as they should.

**ITEM 1:** ❌ 
When I clicked on 'Temporarily hide' there is nothing happening and the tile remains there.
An API request is made to dismiss-item endpoint with the parameter of expiration being zero but I did not see the 'audience-tile-${audienceResourceName}'
The resourcename doesn't tally.
Tested URL: https://qaaudiencesegmentationtest.instawp.xyz/wp-admin/admin.php?page=googlesitekit-dashboard&notification=audience_segmentation#traffic 
(Do let me know in case you want to access the page and I can share credentials)

I think this might only happen when the tile is in position 2.

Video is attached below for reference:
<Details>
https://github.com/google/site-kit-wp/assets/125576926/02228bed-194d-4906-8de8-93a2b0a9c01a

</Details>

____________________________________________________________________

**ITEM 2:**  ❌
The 2nd tile doesn't come with value at all. It is always 0, even if it actually should have data.
Refer to the images where I swapped the positions of an audience where there was a tile with numbers.

<Details>
When 'All Visitors' is in position 1, there is data for the first 4 lines with 5.9K visitors, etc...:
<img width="1306" alt="Screenshot 2024-06-20 at 19 18 23" src="https://github.com/google/site-kit-wp/assets/125576926/dd229b79-7c72-46cc-bc21-4b66a4905e20">

When the same tile is swapped in position 2, there is no data. It's worth noting that the analytics figures at the bottom are showing accordingly.
<img width="1304" alt="Screenshot 2024-06-20 at 19 23 34" src="https://github.com/google/site-kit-wp/assets/125576926/7ef2dd51-de73-45c5-a77b-59f66c1515e8">

</Details>

____________________________________________________________________

**ITEM 3:**  ⚠️ 
Do we have any figma whereby we have the zero data state for Single Tile?
SO far from Figma, it's always having a few tiles scenario and not a single tile.

____________________________________________________________________

**ITEM 4:**  ⚠️ 
At 100% zoom, when we have 3 tiles, there will be scrollbar appearing.
Is that expected or we have to re-adjust to make it show without scrollbar?
<Details>
<img width="1298" alt="Screenshot 2024-06-21 at 13 42 04" src="https://github.com/google/site-kit-wp/assets/125576926/46744d7c-9ea6-4325-ac88-d1dc0c3f2894">

</Details>

**Comment by hussain-t** [comment]
Hi @kelvinballoo, thanks for raising your observations.

>ITEM 1: ❌
When I clicked on 'Temporarily hide' there is nothing happening and the tile remains there.

That's a good catch. The logic changed while working on the CR feedback, which caused it. I have fixed it in this follow-up [PR](https://github.com/google/site-kit-wp/pull/8920).

>An API request is made to dismiss-item endpoint with the parameter of expiration being zero but I did not see the 'audience-tile-${audienceResourceName}'

You're referring to the display name, not the `audienceResourceName`. I could confirm from your screencast that the `audienceResourceName` is correctly being passed in the payload.

>ITEM 2: ❌
The 2nd tile doesn't come with value at all. It is always 0, even if it actually should have data.

That's a good catch. However, it is an existing issue, not part of the changes made to this ticket. I confirmed it by reverting all the changes made in this [PR](https://github.com/google/site-kit-wp/pull/8851). Could you please create a separate ticket? cc: @techanvil 

>ITEM 3: ⚠️
Do we have any figma whereby we have the zero data state for Single Tile?

Unfortunately, we don't have a Figma design for the zero data state single tile.

>ITEM 4: ⚠️
At 100% zoom, when we have 3 tiles, there will be scrollbar appearing.

That's expected, not an issue.

**Comment by kelvinballoo** [comment]
Thanks @hussain-t ! 
Item 2 raised under : https://github.com/google/site-kit-wp/issues/8921

**Comment by techanvil** [comment]
Back to you for another pass @kelvinballoo!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this and it's looking good

- Clicking on 'Temporarily hide' will actually hide the tile with the proper dismiss request with the proper expiration and audience resource name.
   <Details>
   <img width="1205" alt="Screenshot 2024-06-25 at 10 42 09" src="https://github.com/google/site-kit-wp/assets/125576926/d8a8a72f-0f0d-4763-ad51-7c4aa14144aa">

   </Details>

- The tile reappears after deleting it from the wp_usermeta table in the database. Also tested with 3 tiles and 2 tiles behaviour
   <Details>
   <img width="1079" alt="Screenshot 2024-06-25 at 11 04 08" src="https://github.com/google/site-kit-wp/assets/125576926/200870fd-f8b0-49ca-97a1-bbf5fc24e249">

   </Details>

- Verified the following stories in the Storybook and they are looking good. There was no detailed visual tests done as this was done from another ticket. We don't have figma for single tile but it's looking good:
   - AudienceTile->ZeroDataHideable.
   - AudienceTile->ZeroDataNonHideable.
   - AudienceTilesWidget->DefaultWithZeroTile.
   - AudienceTilesWidget->TwoTilesWithZeroTile.
   - AudienceTilesWidget->SingleZeroTile.

Moving this ticket to approval.
