### ISSUE TITLE
Handle the special case for “new visitors” and “returning visitors” to avoid the “partial data” state in the Audience Tile

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8144]
## Feature Description

Implement the special case for “new visitors” and “returning visitors” on the Audience Tile whereby their metrics are retrieved using the `newVsReturning` dimension instead of via the audience until the corresponding audiences are out of the "partial data" state.

See [special case to avoid "partial data" state](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.kkn0j5f77ui9) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If either of the “new visitors” and “returning visitors” audiences are determined to be in the "partial data" state (see #8141):
  * The Audience Tile metrics for “new visitors” and “returning visitors” should be retrieved via a report that uses the `newVsReturning` dimension rather than `audienceResourceName`.
  * These metrics should reflect the full data available for the property over the current date range rather than the limited data available for the corresponding audiences.
  * The "partial data" badge at the top of these Audience Tiles should not be displayed.

## Implementation Brief

Inside `AudienceTilesWidget` component `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js`.

- [x] Use the `getConfiguredSiteKitAndOtherAudiences` selector added in #8923 which should return `[ otherAudiences, siteKitAudiences ]` in response.
- [x] Check if `siteKitAudiences` are in partial data state using `hasAudiencePartialData( audiences )` selector added in #8923. Assign the result to a constant `isSiteKitAudiencePartialData`.
- [x] If `isSiteKitAudiencePartialData` is true:
  - [ ] Create a new report for `siteKitAudiencesReport` which should be fetched with same `reportOptions`, but using the `newVsReturning` dimension instead of `audienceResourceName`, and filtering for the values `'new'` or `'returning'` for this dimension (i.e. to exclude `'(not set)'`).
  - [ ] Fetch the top cities, top content and top content titles for `siteKitAudienceResourceNames` separately with `dimensionFilters` set to `newVsReturning`.
  - [ ] Create a function `getAudienceTileMetrics` inside `AudienceTilesWidget` which should be called when we are iterating over the `visibleAudiences` to return `AudienceTile` component. It should return [these metrics](https://github.com/google/site-kit-wp/blob/de09a10c23b15d090ed2207693f6ac9e1bb67f7e/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js#L278-L329) so that those can be passed to `AudienceTile` component.
    - [ ] This function should accept `audienceResourceName` as argument. It should check if `isSiteKitAudiencePartialData` is true.
      - [ ] If `isSiteKitAudiencePartialData` is `true` and the `audienceResourceName` belongs to a Site Kit audience (use the `isSiteKitAudience` selector), return the data from the report fetched for Site Kit audiences which used `newVsReturning` dimension.
      - [ ] Otherwise, return the metrics from the main, existing report that uses the `audienceResourceName` dimension.
- [ ] In `AudienceTile` component inside `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/index.js`
  - [ ] While determining `isAudiencePartialData`, use the `isSiteKitAudience` selector to check if the `audienceResourceName` Site Kit audience.
  - [ ] If property is not in partial state and audience belongs to one of the above, return `false`.
  - [ ] If property is not in partial state or audience is non Site-Kit audience, and in partial state, then return `true`.

### Test Coverage

* Add the test coverage for the scenario where "new visitors" and "returning visitors" are in partial data states.

### Prerequisites

* Set up Analytics and enable the `audienceSegmentation` feature flag.
* Ensure the audiences are enabled and available in the Audience widget area.
* Ensure "new visitors" and "returning visitors" audiences are visible in the Audience widget area.
* Ensure "new visitors" and "returning visitors" audiences are in a partial data state.

### Data Verification

* Visit the Audience widget area.
* Verify that the Audience Tiles for "new visitors" and "returning visitors" display the data from the `newVsReturning` dimension rather than the `audienceResourceName` dimension.
* Verify that the Audience Tiles for "new visitors" and "returning visitors" are not displaying the "partial data" badge for the main report metrics.
* The "Top content by pageviews" sections will have the "partial data" badge displayed if the corresponding audiences are in partial data state.

### Testing the Error State

* Follow the QAB steps in #8147 to reproduce all the tiles' error states.
* After simulating the error, confirm that a full-width error widget is displayed in place of the Audience Tiles.

## Changelog entry

* Handle the “new visitors” and “returning visitors” audiences as a special case to avoid the "partial data" state for them on the Audience Tiles.

**Comment by techanvil** [comment]
Note that I've moved this to the Backlog as we have an open [discussion](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABEVx_moU) on the "collecting data" terminology in the design doc.

**Comment by techanvil** [comment]
The aforementioned discussion has been resolved, and this is ready for AC.

**Comment by techanvil** [comment]
Hi @ankitrox, thanks for drafting this IB.


You raise an interesting concern as to how this issue relates to #8726. On balance, I think it would in fact be preferable to wait for #8726 to be implemented before tackling this issue, as #8726 will result in some significant refactoring of the `AudienceTilesWidget` and `AudienceTile` components, which I think would further impact this issue (for example I don't think the specced `getMetric()` would be relevant any more, and the data extraction aspect this addresses would need to be tackled in `AudienceTile` instead).

It's also the case that if we implement this issue _before_ #8726, then #8726 itself will be impacted and require additional work that we haven't accounted for in its IB.

In terms of execution efficiency I think the refactor specced in #8726 would be better done first because it will simplify the data extraction, and lead to a fairly straightforward implementation for this issue, whereas if we implement this issue first we'll add complexity to the data extraction side of things which will be a bit harder to subsequently refactor in #8726.

So, as a result I've added #8726 as a blocker to this issue, and would suggest revisiting the IB here with this in mind.

Here are a few additional points on the current IB:

- A minor one, I'd suggest a couple of renames:
  - `isSiteKitAudiencePartial` -> `isSiteKitAudiencePartialData`
  - `siteKitAudiencesResourceNames` -> `siteKitAudienceResourceNames`, _if_ we keep the variable. It's not entirely clear what this variable will be used for, so please can you either clarify or remove this from the spec?

---

>   - [ ] While determining `isAudiencePartialData`, check if the `audienceResourceName` belongs to "new visitors" or "returning visitors".

- This is OK, but it could be worth a mention of the `isSiteKitAudience()` selector which we can use for an easy check here.

---

>   - [ ] If property is not in partial state or audience is non Site-Kit audience, and in partial state, then return `true`.

- It looks like the "or" here should be an "and", i.e. "If property is not in partial state and the audience is non Site-Kit audience"...

**Comment by ankitrox** [comment]
Thank you @techanvil .

As we have pretty much implemented #8484 and #8726 is also in CR, I've written the IB for this one. Requesting you to kindly review the same.

Thanks

**Comment by techanvil** [comment]
Thanks @ankitrox! The IB is most of the way there. A couple of smallish points:

- The `audienceResourceName` property is the `name` of an audience and looks something like `properties/433726123/audiences/8044127456`. The IB has it mixed up with `audienceSlug` which will have the values `new-visitors`, `returning-visitors` etc.
  - This means that in `AudienceTilesWidget` we'll need to do an extra lookup to retrieve the `audienceSlug` for an audience rather than comparing `audienceResourceName` directly as specified.
  - In `AudienceTiles` we can use the `isSiteKitAudience()` selector which accepts an `audienceResourceName` argument.
- Please update `AudienceTiles` to be `AudienceTilesWidget` which is the name of the component.

**Comment by ankitrox** [comment]
Thank you @techanvil . I have updated the IB for the points mentioned. 

Assigning to you for review.

**Comment by techanvil** [comment]
Thanks @ankitrox! One more thing -

> Inside the function call the `getAvailableAudiences` selector and map the `audienceResourceName` to `audienceSlug` to form a new list to lookup in the next step mentioned.

I would suggest we can lift this out the function so we create a map of `audienceResourceName` to `audienceSlug` within the body of the render function. Then we can avoid iterating over `availableAudiences` multiple times, and we can then potentially also use this map to identify the audiences when removing them from `configuredAudiences` instead of having to call `isSiteKitAudience()` for each audience.

**Comment by techanvil** [comment]
Thank for the update, @ankitrox! The IB LGTM. :white_check_mark:

**Comment by techanvil** [comment]
Hi @ankitrox, in light of the fact we're reverting the change for this issue's dependency https://github.com/google/site-kit-wp/issues/8726, please can you review the IB for this issue and adjust it as necessary?

**Comment by ankitrox** [comment]
Hi @techanvil ,

Thanks for the heads up regarding revert of #8726 . I've adjusted the IB according to the current state of `AudienceTilesWidget` and `AudienceTile` component.

Assigning over to you for review.

Thanks.

**Comment by techanvil** [comment]
Thanks @ankitrox. The IB was mostly looking good - I've given it a bit of a tweak, fixing a couple of plural names and some minor grammatical errors, and making the logic more explicit in a couple of places. I've also bumped the estimate to a 19 to make some allowances for testing.

Please review the amended IB and if you're happy this can go straight to the EB.

In the meantime I'll give this the old IB :white_check_mark:.

**Comment by techanvil** [comment]
Hey @ankitrox, I've sent this back to you in IB for an update to reuse the selectors we are defining in https://github.com/google/site-kit-wp/issues/8923.

**Comment by ankitrox** [comment]
Thanks @techanvil 

Once #8923 IB is approved, I will update the IB for this one.

**Comment by techanvil** [comment]
Thanks @ankitrox! The IB for #8923 has now been approved, so this should be good for an update.

**Comment by techanvil** [comment]
Thanks @ankitrox, that's great; note that I also made a couple of minor tweaks to the IB.

Once again, this IB LGTM. :white_check_mark:

**Comment by ivonac4** [comment]
Hussain flagged this will go over the estimate a bit due to increased complexity.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Audience Tiles for `new visitors` and `returning visitors` display the data from the `newVsReturning` dimension. I ran through the report in GA4 and compared this with data for 7, 14, 28 and 90 days. 
- Audience Tiles for `new visitors` and `returning visitors` are not displaying the `partial data` badge for the  report.
- The `Top content by pageviews` sections has the `partial data` badge displayed if in partial data state.
- The two errors (full and single) appeared as expected.. I tested this on another live site, and also checked to make sure that new and returning visitors functioned the same with different setup in Tweak extension. See screenshots.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/3e6547ab-83f8-4c31-a3ef-f060706d04ac)
![image](https://github.com/user-attachments/assets/454a7a14-25dc-4589-8c33-0098c0872f4b)
![image](https://github.com/user-attachments/assets/7dd9bac4-1be8-44ea-87b0-4271dc13b1fd)
![image](https://github.com/user-attachments/assets/ef4d9b06-4f39-43ce-bf5c-2bc47830a49f)
![image](https://github.com/user-attachments/assets/08e508e1-efce-4553-8dc4-d320f3e38e53)

</details>
