### ISSUE TITLE
Implement the “Top content” metric handling OAuth flow

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8154]
## Feature Description

Implement the redirection to OAuth to grant the _edit_ scope for creating the custom dimension from the "Top content" metric section. This includes both the happy and unhappy path.

See [audience tiles > "Top content" states](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.il6bzjf82qau) and [OAuth errors](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.tfz9l0v91tcy) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Given that the **Update** CTA is displayed in the "Top content" section of an Audience Tile (see https://github.com/google/site-kit-wp/issues/8153), and the user does not have the Analytics _edit_ scope:
  - Clicking on **Update** should trigger the standard OAuth flow used in the plugin.
  - On successful completion, the user should be redirected back to the dashboard where the rest of the flow implemented in https://github.com/google/site-kit-wp/issues/8153 should be continued.
  - If an error is returned from the OAuth flow:
    - The OAuth error variant of the Error Modal should be displayed (see https://github.com/google/site-kit-wp/issues/8134).
    - It should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23488&mode=design&t=rPamL7stYGR0AGkR-0), with the following copy:
      - Title: _Analytics update failed_
      - Description: _Setup was interrupted because you did not grant the necessary permissions. [Get help]()_
    - The _Get help_ link should open the Analytics support page in a new tab, scrolled to the [insufficient permissions](https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/#insufficient-permissions) section.
    - The **Retry** button should take the user back to the OAuth flow to retry the flow from that point.
    - The **Cancel** button should close the modal.
    - The default OAuth error notice that Site Kit usually displays when the OAuth flow returns an error should not be shown.

## Implementation Brief

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js`:

* [x] Get the `autoSubmit` value for the `AUDIENCE_TILE_CUSTOM_DIMENSION_CREATE` key using the `getValue` selector of the `CORE_FORMS` store.
* [x] Get the error setup code using the `getSetupErrorCode` selector of the `CORE_SITE` store.
* [x] Create a boolean variable `hasOAuthError` that checks if `autoSubmit` is true and the setup error code equals `'access_denied'`.
* [x] Modify the logic that determines whether the `AudienceErrorModal` component should be rendered.
* [x] Include the `hasOAuthError` variable as part of the condition to render the `AudienceErrorModal` component.
* [x] Pass the `hasOAuthError` variable to the `hasOAuthError` prop of the `AudienceErrorModal` component.
* For example, review the implementation in `AudienceSegmentationSetupCTAWidget`:
https://github.com/google/site-kit-wp/blob/29bb9eac962db685d8629571dd9a3a78a265df5d/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L160
https://github.com/google/site-kit-wp/blob/29bb9eac962db685d8629571dd9a3a78a265df5d/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L296-L298

### Test Coverage

* Create an `AudienceTile/index.test.js` file and add `AudienceErrorModal` error variants tests similar to the ones in [AudienceSegmentationSetupCTAWidget.test.js](https://github.com/google/site-kit-wp/blob/50fe706eb86838a31af62cb113978c3233ce91c5/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js#L597).
* Fix any failing tests.

## QA Brief

To simulate the OAuth error:

1. **Prepare the Environment:**
   - Setup the Analytics module and enable the Audience Segmentation.
   - Delete the `wp_googlesitekit_additional_auth_scopes` entry from the `wp_usermeta` table if it exists. This entry contains the `https://www.googleapis.com/auth/analytics.edit` scope.
   - Delete the `googlesitekit_post_type` custom dimension from the Analytics console if it exists.
   - Run the following command in the browser console to sync the custom dimensions:
     ```js
     googlesitekit.data.dispatch( 'modules/analytics-4' ).fetchSyncAvailableCustomDimensions()
     ```
    - Refresh the page if necessary.
   
3. **Trigger the OAuth Error:**
   - Click on the **Update** button in the Audience Segmentation widget tile.
   - In the OAuth flow, cancel the flow when prompted to grant permissions.
   - Ensure the OAuth error variant of the Error Modal is displayed.
   - Click the **Retry** button to trigger the OAuth flow again.
   - Complete the OAuth flow and grant permissions.
   - Ensure the custom dimension creation continues successfully after granting permissions.

## Changelog entry

* Redirect to OAuth as needed to grant the scope for creating the required custom dimension from the "Top content" metric section.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @hussain-t , in general the flow is working as described.
<Details>

https://github.com/user-attachments/assets/c8b5d44b-ae96-4c60-99dc-25a90988f35c

</Details>

But I have some UX concerns. ⚠️ 

**ITEM 1:**
After I click cancel, the OAuth error variant of the Error Modal does not display straightaway. It will not load until I scroll down to the tiles section. 
Refer to as from 1 minute mark in the video.

I think we possibly need to anchor the scroll to that tile section so that the error modal appears straightaway.

<Details>

https://github.com/user-attachments/assets/f4fccad1-406d-4c92-aae4-5750091c134e


</Details>

**ITEM 2:**
This is linked to number 1. When I cancelled the flow, I go to the page where I see a 'Success' message. Again, you can refer to the 1 minute mark in the video above. 
This is due to the success message initially but it just feels weird but maybe this will not be a concern if we auto scroll to the tiles section, if we decide to fix it that way for item 1.

**Comment by hussain-t** [comment]
Hi @kelvinballoo, those are valid UX concerns. However, they are out of the scope of the issue. Can you create a new issue to address them? Thanks!

**Comment by kelvinballoo** [comment]
### QA Update ⚠️  

Thanks @hussain-t . New ticket raised here : https://github.com/google/site-kit-wp/issues/9350

One thing to clarify from the AC: 
`The default OAuth error notice that Site Kit usually displays when the OAuth flow returns an error should not be shown.`
Do you have a link to a reference of that default OAuth error notice?  ⚠️ 
We are pretty much good, I just need a reference point to properly validate this.

_______________________________________________

Other than that, the following were verified good ✅ 

Given that the user does not have the Analytics edit scope:

- Clicking on Update triggers the standard OAuth flow used in the plugin. On successful completion, the user is redirected back to the dashboard 
   <Details>
   

   https://github.com/user-attachments/assets/ffb9172b-adb6-4054-8e52-e9714823879e


   </Details>

- If an error is returned from the OAuth flow:
   - The OAuth error variant of the Error Modal is displayed. It follows the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23488&mode=design&t=rPamL7stYGR0AGkR-0) with the following copy:

       Title: Analytics update failed
       Description: Setup was interrupted because you did not grant the necessary permissions. Get help.

   - The Get help link opens the Analytics support page in a new tab, scrolled to the insufficient permissions section. The Cancel button should close the modal.
   
      <Details>
      

      https://github.com/user-attachments/assets/fb92d8bd-c6c9-4efa-a341-e3145dcce236


      </Details>

     - The Retry button takes the user back to the OAuth flow to retry the flow.
        <Details>

        https://github.com/user-attachments/assets/00f40f02-c634-484f-b42c-d55ff429af77

        </Details>

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks for confirming @hussain-t . I can confirm, based on the AC, that the ErrorNotifications banner does not appear if there is an error. 

The following were verified good and it's good to be moved to Approval.

Given that the user does not have the Analytics edit scope:

- Clicking on Update triggers the standard OAuth flow used in the plugin. On successful completion, the user is redirected back to the dashboard  ✅ 
   <Details>
   

   https://github.com/user-attachments/assets/ffb9172b-adb6-4054-8e52-e9714823879e


   </Details>

- If an error is returned from the OAuth flow:
   - The OAuth error variant of the Error Modal is displayed. It follows the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23488&mode=design&t=rPamL7stYGR0AGkR-0) with the following copy: ✅ 

       Title: Analytics update failed
       Description: Setup was interrupted because you did not grant the necessary permissions. Get help.

   - The Get help link opens the Analytics support page in a new tab, scrolled to the insufficient permissions section. The Cancel button should close the modal. ✅ 
   
      <Details>
      

      https://github.com/user-attachments/assets/fb92d8bd-c6c9-4efa-a341-e3145dcce236


      </Details>

     - The Retry button takes the user back to the OAuth flow to retry the flow. The default OAuth error notice that Site Kit usually displays when the OAuth flow returns an error does not appear. ✅ 
        <Details>

        https://github.com/user-attachments/assets/00f40f02-c634-484f-b42c-d55ff429af77

        </Details>
