### ISSUE TITLE
Implement the Connect Analytics CTA banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8156]
## Feature Description

Implement the banner shown when Analytics has been disconnected after the Audience Segmentation feature has been set up.

See [connect Analytics CTA banner](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.i6wyryc1eo89) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new banner should be displayed whenever Analytics is disconnected from Site Kit ~after the Audience Segmentation feature has been set up~. This banner should be prominently visible to alert users about the disconnection.
    * Note that the "after the Audience Segmentation feature has been set up" part of this requirement will be implemented in [#8810](https://github.com/google/site-kit-wp/issues/8810) once we do the necessary refactoring of the audience settings. 
* The banner should match the design specifications outlined in the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1398-26857&mode=design&t=EZzdmlTzrXWraiCr-0).
* The banner must include a "Connect Google Analytics" CTA link button.
* Clicking on the "Connect Google Analytics" link button should navigate the user to the Setup flow for Analytics.

## Implementation Brief

* [ ] Add `assets/js/components/AudienceSegmentation/ConnectAnalyticsCTATile.js`
  * Use `assets/js/components/KeyMetrics/ConnectModuleCTATile.js` as a starting point
  * Instead of `moduleSlug` prop, which can be removed, use `analytics-4` module slug directly where needed, as this banner works only with Analytics module
  * Also replace usage of `module` data and it's `module.name` property, and use `Analytics` string directly in translations 
  * Adapt the copy and SVGs (there are only 2 in the design), per figma design linked in AC. 
  * Apply styling which can be added in new file `assets/sass/components/key-metrics/_googlesitekit-audience-connect-analytics-cta-tile.scss` to match the provided design
* [ ] In `assets/js/googlesitekit/widgets/register-defaults.js`
  * Register new widget, using slug say `audienceSegmentationConnectAnalytics`, and place it in the audience segmentation widget area added in [8138](https://github.com/google/site-kit-wp/issues/8138)
  * Use `ConnectAnalyticsCTATile` for component
  * It should be full width
  * For `isActive` in the callback, check if Analytics module is connected to return early. Otherwise check if Audience feature is setup using `isAudienceSegmentationWidgetHidden` selector, implemented in [7176](https://github.com/google/site-kit-wp/issues/8176). If not return `false`, otherwise return `true`

### Test Coverage

* Add stories and js tests for the new component

## QA Brief

* Enable `audienceSegmentation` feature flag and ensure Analytics module is disconnected. 
* Visit Dashboard, the Widget should show up in the Audience area. 
* Ensure the design matches with Figma. [Desktop](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1398-26857&t=nQyGRZCOVXe3fpYq-0), [mobile](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1668-39988&t=nQyGRZCOVXe3fpYq-0), [tablet](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1956-18245&t=nQyGRZCOVXe3fpYq-0). 

## Changelog entry

* Add a CTA banner in the audiences widget area to reconnect Analytics if disconnected.

**Comment by hussain-t** [comment]
Hi @techanvil, I noticed a discrepancy between the SVG illustrations for the "Connect Google Analytics" CTA in the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1398-26857&mode=design&t=GFhw3OjZXTM9EQbE-0) and what's presented in the [design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.i6wyryc1eo89). Could you please clarify if the Figma design reflects the most current version we should follow for implementation? 

#### Figma Design CTA

![Screenshot 2024-01-30 at 12 01 23 AM](https://github.com/google/site-kit-wp/assets/24408261/bec481d3-a1c6-4dda-9e97-2e3a789b5f87)

#### Design Doc CTA

![Screenshot 2024-01-29 at 11 59 48 PM](https://github.com/google/site-kit-wp/assets/24408261/36c73df7-f1aa-4cc4-88b8-ccdf7c96f09b)


cc: @bethanylang @ivonac4

**Comment by techanvil** [comment]
Hey @hussain-t, please refer to Figma as the source of truth for designs unless explicitly stated otherwise in the design doc. As mention in the design doc under [**UI components**](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.r0ayq07z5cr0):

> Screenshots are provided for the sake of illustration; **please refer to [Figma](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1046-39085&mode=design&t=Tutm5Nfpoih8612j-0) for the most up-to-date UX design and copy, including mobile viewport designs, unless stated otherwise**

**Comment by tofumatt** [comment]
ACs here look good 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Tested this and here are my observations:

**ITEM 1:**
The image background colour is different from figma.
The implemented design looks more greenish and you can clearly see an outline.
The figma is more white-ish with no outline.

<Details>
Implementation:
<img width="1186" alt="Greenish" src="https://github.com/google/site-kit-wp/assets/125576926/9f3a867a-b5d5-4b77-91e4-634d5839303b">

Figma:
<img width="672" alt="Screenshot 2024-06-21 at 15 45 15" src="https://github.com/google/site-kit-wp/assets/125576926/170b41cf-b883-4454-a0a3-425cb13ee0c1">

</Details>
_______________________________________________________

**ITEM 2:** 
The font weight for those text on figma is 500. On implementation, it's 400.
However, I do feel this is an inconsistency on the figma and it's better the way we implemented

<Details>
Implementation:
<img width="832" alt="Screenshot 2024-06-21 at 15 08 52" src="https://github.com/google/site-kit-wp/assets/125576926/744dcd42-5c14-4840-9d5f-dea195fda4c1">


Figma:
<img width="965" alt="Screenshot 2024-06-21 at 15 48 42" src="https://github.com/google/site-kit-wp/assets/125576926/42dddcc1-f034-4ae2-b9c0-13a75fb1943f">

</Details>

_______________________________________________________

**ITEM 3:** 
Analytics icon is supposed to be 31px based on figma but it's 32px. 
Not sure if it's to maintain consistency but anyway, it's not a huge gap.

<Details>
Implemented icon is 32px:
<img width="491" alt="Screenshot 2024-06-21 at 15 13 49" src="https://github.com/google/site-kit-wp/assets/125576926/b133ca46-9541-478b-aeef-f91a734bf891">

Figma icon is 31px:
<img width="618" alt="Screenshot 2024-06-21 at 16 26 21" src="https://github.com/google/site-kit-wp/assets/125576926/b1397de6-3651-40da-a5bd-873748f2259e">
</Details>

_______________________________________________________

**ITEM 4:** 
The big icon is282.56 x 193.4 px but in figma it's 295 x 202.11.

<Details>
Implemented:
<img width="626" alt="Screenshot 2024-06-21 at 15 10 27" src="https://github.com/google/site-kit-wp/assets/125576926/99eaba08-0471-4be5-959f-98a6cb4a471a">

Figma:
<img width="388" alt="Screenshot 2024-06-21 at 15 11 16" src="https://github.com/google/site-kit-wp/assets/125576926/6b43d9c5-2eec-4c50-be74-ad57f8a11379">

</Details>
_______________________________________________________

**ITEM 5:**
The mobile tests I did was on Chrome Developer console but when viewed on an actual mobile (iPhone 15Pro Max), the image doesn't appear.
Also tested on Browserstack. There is similar feedback for Tablet. The sizes are different.
 
<Details>
<img width="474" alt="Screenshot 2024-06-21 at 15 32 19" src="https://github.com/google/site-kit-wp/assets/125576926/6e8c9296-5d33-43c5-9b3c-433f1fd89832">
</Details>

**Comment by kuasha420** [comment]
Hi @kelvinballoo! Thanks for the detailed report. 

1. That is odd. I've exported  the image SVG straight from Figma. I'll create a follow up PR to address this. 
2. The font weight is consistent with other CTA links in our codebase and therefore correct as you've said. 
3. This is also fine as the actual icon asset we use is 32px everywhere. 
4. The SVG will change size  dynamically depending on screen size to best use the available space and give away for text. So this is fine  as well as long as it maintains the aspect ratio. 
5. Super odd. I've just tested  on  both android and IOS. And indeed, it renders on Android fine (both Chrome and Firefox) but the graphics does not render on IOS. I'll try to investigate further and see if I can fix it in the follow up PR. 

Cheers.

**Comment by kuasha420** [comment]
Opened a [PR](https://github.com/google/site-kit-wp/pull/8925) to fix the ITEM 1. ITEM 5 will be fixed in [#8926. ](https://github.com/google/site-kit-wp/issues/8926)

**Comment by techanvil** [comment]
Thanks @kuasha420! Back to you for another pass, @kelvinballoo.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @techanvil , @kuasha420 .

Reviewed item 1 and the background colour is now white. LGTM!
While some items as we've found are not 100% matching figma, these are to maintain consistency with other areas of the plugin.


<Details>
<img width="1075" alt="Screenshot 2024-06-25 at 11 43 36" src="https://github.com/google/site-kit-wp/assets/125576926/686e0fa2-3b6e-4de6-93b9-e44a950d404c">
</Details>
