### ISSUE TITLE
Implement the loading state for the Selection Panel

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8162]
## Feature Description

Implement the loading state for the Selection Panel.

See [selection panel > loading state](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.sfjh1lb444) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The cached audiences should be resynced the first time the Selection Panel is opened on a given page load.
* While the cached audiences are being resynced and the user counts for audiences are loading, the Selection Panel should be displayed in its loading state, with preview blocks in place of the listed audiences.
* Assuming that an audience selection exists, this should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1512-32299&mode=design&t=QuEtYYOSGZ9uz3zY-0) as it stands.
* However, if the audience selection has been cleared (this could happen as a side effect of clearing an invalid selection via https://github.com/google/site-kit-wp/issues/8155), the audience preview blocks should be displayed in a flat list, without the "Current selection" and "Additional groups" titles.

## Implementation Brief

**Core Loading State**
* [x] Update `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceItems.js`;
   * [ ] Use `withIntersectionObserver` HOC to detect when the component is in view, wrapping `SelectionPanelItems` as `SelectionPanelItemsWithIntersectionObserver`.
   * [ ] Create a new callback to pass to the `onInView` prop of the `SelectionPanelItemsWithIntersectionObserver`. Call it `onInView`;
       * [ ] Use `useState` to track `firstView`, defaults to `true`, and return early if `firstView` is `false`.
       * [ ] Trigger the `syncAvailableAudiences` action.
       * [ ] Update `firstView` to `false`.
 * [ ] Use the `hasFinishedResolution` selector for the `getAvailableAudiences` selector, and each audience total `getReport` selector to get a single, boolean, `isLoading` value.
 https://github.com/google/site-kit-wp/blob/e12d144418423b637879d8dd0f0d181acaa89b1b/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceItems.js#L96-L117
 * [ ] Create a new component `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceItemPreviewBlock.js` which uses multiple `PreviewBlock` components and relevant CSS to create a preview element for a single AudienceItem which matches the [FIGMA designs](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1512-32299&t=ICAHI0UQCn7y5hbL-0).
 * [ ] If `isLoading` is true, pass `AudienceItemPreviewBlock` instead of `AudienceItem` to `SelectionPanelItemsWithIntersectionObserver`, `ItemComponent` prop. 

**Cleared Audience Selection Case**
 * [ ] Continue to update `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceItems.js`;
    * [ ] Get the configured audiences, using the `getConfiguredAudiences` selector.
    * [ ] Within the new `onInView` callback, if none of the configured audiences are present in the available audiences (using the existing audiences const), set a `useState` called `noAudiencesAvailable` to true.
    * [ ] If `noAudiencesAvailable` is `true`, on the returned `SelectionPanelItemsWithIntersectionObserver ` component;
       * [ ] Do pass the `savedItemSlugs` prop - this will cause all `AudienceItemPreviewBlock`'s to be rendered in a single list.
       * [ ] Pass all audiences to `availableUnsavedItems`.

### Test Coverage

* Add these two new loading states to `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.stories.js`

## QA Brief

* Setup Site Kit with `audienceSegmentation` feature flag enabled
* Setup Analytics module
* Open the audience segmentation panel, verify that it is loading for a second, and loader matches the figma designs referenced in AC
* Select one, or more audience groups, and refresh the page
* Open the panel again, verify that loader is properly showing within the sections, and looks as in figma designs

## Changelog entry

* Implement the loading state for the audience selection panel.

**Comment by techanvil** [comment]
I've moved this back to Backlog as the final [in-progress changes to the design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABJiKQwSo), relating to audience caching, will probably affect the AC for this one

**Comment by techanvil** [comment]
The audience caching aspect of the design doc has been sufficiently finalised, I've updated the AC and moved this back to IB.

**Comment by tofumatt** [comment]
@benbowler Looks good, but can you add an estimate here? 🙂

**Comment by eugene-manuilov** [comment]
Looks like @tofumatt has already approved the IB, so moving it to EB.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.
- @zutigrm I noticed that in the current implementation, the number of selected groups loads immediately, whereas according to the Figma design, a loader should appear for this information. It should load simultaneously with the listing of the groups in the panel.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/13e4fe7b-88d8-483a-889c-04390079a284)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/cb8ba7f4-48b3-4d7f-ba91-7208e6444f36)


https://github.com/google/site-kit-wp/assets/94359491/60477c8f-fc33-4ed0-8089-09d724876982

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that loading state of selection panel implemented successfully.
- Verified that loading state of selection panel matches figma and issue reported above is resolve now.
- Verified that user is able to select or change groups in panel.
- Verified that if the audience selection has been cleared, the audience preview blocks displayed in a flat list, without the "Current selection" and "Additional groups" titles.

<details>


https://github.com/user-attachments/assets/f18392dc-3618-4f7d-887f-af62c679df3b


https://github.com/user-attachments/assets/e08d4e06-1f9a-4988-97a1-b3a06e6fc65a

</details>
