### ISSUE TITLE
Add the “New” badge PHP API

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8167]
## Feature Description

Add the “New” badge PHP API. This does not include the REST and datastore APIs which will be implemented separately via https://github.com/google/site-kit-wp/issues/8168.

See ["New" badges](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.7rc9fqmf26a) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* A new badge will have a unique identifier (string), and can be activated for an individual user. 
* Once activated, the badge is considered active for the user until 28 days has been passed after the badge has been viewed. Note that view is different than activation. 
* Infrastructure for "new" badges should be introduced at a new PHP class `Google\Site_Kit\Core\NewBadge\NewBadge`. 
* This class will facilitate activation and management of new badges for individual and all users.
* The class should implement methods for:
    * Activating a new badge for a given user. A badge can only be activated once per user, and the subsequent activation calls for the same user should be ignored. 
    * Tracking view for a new badge by a given user. This should also track the date of the view, so the information can be used to expire a new badge when the aforementioned condition is met. 
    * Expiring a new badge for a given user. 
    * Listing all active new badges for a given user. 
    * Marking a new badge as "known" for all users, so it can not be activated in the future. 
* A list of all active new badges for the current user should be exposed to client on page load. 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by techanvil** [comment]
Update: I've moved this to the Backlog instead to make it clearer which issues are waiting for a change or approval to the design doc (see [this comment](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABJM1aJTE) on the doc).

**Comment by techanvil** [comment]
Note that this issue may be closed if we are going to implement the "expirable items" infrastructure fully in #8168. TBD, will close this issue if so.

**Comment by techanvil** [comment]
Closing, as per the above.
