### ISSUE TITLE
Add the “New” badge to the Audience Widget Area

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8169]
## Feature Description

Add the "New" badge to the Audience Widget Area.

See [audiences widget area](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.6riep7s01sry) and ["New" badges](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.7rc9fqmf26a) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Audiences Widget Area is added to the dashboard, it should have a “New” badge shown next to the title.
* The badge should be shown to a user for 28 days from the first time the badge is viewed.
* The badge should be displayed as per the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1047-54324&mode=design&t=oNpX5iudkf6gZoSp-0).

## Implementation Brief

_Note: This should make use of the "expirable items" API introduced via #8168._

 * [x] Add a new boolean prop to the `registerWidgetArea` function, in `assets/js/googlesitekit/widgets/datastore/areas.js`, called `hasNewBadge`.
 * [x] Update `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js`, based on the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1047-54324&mode=design&t=oNpX5iudkf6gZoSp-0) to conditionally render a `NewBadge` component based on the `hasNewBadge` prop:
    * [x] When `hasNewBadge` is false, there should be no changes to the layout.
    * [x] When `hasNewBadge` is true:
       * [x] Check if the badge has been seen by the user yet using the `hasExpirableItem` selector, passing the `widget-area-expirable-new-badge-${slug}` as the expirable item slug.
       * [x] Check if the new badge has expired using `isExpirableItemActive` selector, passing the `widget-area-expirable-new-badge-${slug}` as the expirable item slug.
       * [x] Render a `NewBadge` component in the widget header if the badge has not been seen by the user before, or it has not yet expired.
       * [x] Create a `useEffect` in this component which calls the `setExpirableItemTimers` action, *only if the user has never seen New badge before*, with the following object:
          ```
          {
             `widget-area-expirable-new-badge-${slug}`: WEEK_IN_SECONDS * 4
          }
         ```
         *Importing `WEEK_IN_SECONDS` from `assets/js/util/index.js`*
 * [x] Update the Audience Segmentation widget area registration, in `assets/js/googlesitekit/widgets/register-defaults.js`, setting the `hasNewBadge` prop to true.

### Test Coverage

* Update the Widget Area stories, adding a story to show the new badge state.
* Update the `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.test.js` tests to confirm the new badge is rendered when the `hasNewBadge` testing the first and subsequent view as well as viewing after the timeout has expired.
* Update/fix any other failing tests and VRTs.

## QA Brief

* Make sure the `audienceSegmentation` feature flag is enabled.
* View the Audience Segmentation widget on the dashboard and you will see the New badge.
* In the database, update the `wp_googlesitekitpersistent_expirable_items` row in the `wp_usermeta` table for your user, setting the timestamp for the `widget-area-expirable-new-badge-mainDashboardTrafficAudienceSegmentation` key to a timestamp in the past. You can use a site like [unixtimestamp.com](https://www.unixtimestamp.com/) to generate a timestamp in the past.
* You will now see that the new badge goes away.
* Reseting Site Kit will **not** show the New badge again as these settings are persistent.

## Changelog entry

* Add the “New” badge to the Audience Widget Area.

**Comment by benbowler** [comment]
As this IB is blocked, and I am away for a couple of weeks, I will un-assign myself but happy to pick it up again if it's not beed addressed when I'm back. I already had a comment in the IB section to explain the blocking tickets.

**Comment by benbowler** [comment]
Back from vacation and I've updated this IB now that all of the blockers are further along.

**Comment by techanvil** [comment]
Hi @benbowler, nice work so far on the IB. A couple of points:

Providing a `Header` property does make sense at first glance, particularly as we've recently introduced the `Footer` property. However, it occurs to me that by taking this approach it would be tricky/impossible to make use of the `CTA` property to render the "Change groups" CTA for the widget area (see https://github.com/google/site-kit-wp/issues/8158, although this aspect is not yet mentioned in the WIP IB there).

It would be nice to _not_ have to reproduce the markup for the subtitle and CTA within a `Header` component, which makes me think it would instead be appropriate to have the ability to display a "New" badge baked into the `WidgetAreaRenderer`. We could simply pass a `newBadgeID` property in  via `registerWidgetArea()`, and implement the badge rendering and associated logic directly in the `WidgetAreaRenderer` if this property is provided. It strikes me that it's pretty likely we'll want to show a "New" badge for new widget areas in future so having this being an explicit part of the API/renderer seems a reasonable way to go here. WDYT?

Secondly, a minor point but the date provided to `setExpirableItemTimers()` should be the expiry date, i.e. 28 days in the future rather than `Date.now()`.

**Comment by benbowler** [comment]
Thanks @techanvil, good idea for the New badge, I've updated the brief based on your comments.

---

Based on #8168, the `setExpirableItemTimers` item objects `expiredInSeconds` prop should be:

> the number of seconds after which this item should be expired

So I've updated it to be `WEEK_IN_SECONDS * 2`.

**Comment by benbowler** [comment]
Hey @techanvil, yes I think the newBadge prop is a pretty nice idea and makes is super clean/easy to add this to widget areas in future. IB updated.

**Comment by techanvil** [comment]
Great, thanks @benbowler! IB LGTM :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified new badge expiry date set in db 28 days from the first time the badge is viewed.
- Verified setting up past date "new" badge do not display.
- Verified Reseting Site Kit will not show the New badge again.
- Verified on setting up upcoming date "new" badge continuously display.
- Verified the badge displaying as per the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1047-54324&mode=design&t=oNpX5iudkf6gZoSp-0).

<details>



![image](https://github.com/google/site-kit-wp/assets/94359491/de73863b-df19-4f6c-afda-2702c054985f)


Past and resetting site kit


https://github.com/google/site-kit-wp/assets/94359491/6553057c-c5af-4902-9899-f39e3bceb24c

Future date


https://github.com/google/site-kit-wp/assets/94359491/6906a0e4-ca59-49c0-9edc-83d705368d14

</details>
