### ISSUE TITLE
Ensure CTAs don’t appear for view-only users

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8174]
## Feature Description

Ensure CTAs for setting the feature up and creating resources, and the link to the Settings section in the Selection Panel don’t appear for view-only users.

See [dashboard sharing](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.w0br3nfp3mbe) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- When on the view-only dashboard, no Audience Segmentation CTAs should be displayed as the user won’t have permission to action them:
  - The Setup CTA Banner should not be displayed.
  - The Audience Creation Notice in the Selection Panel should not be displayed.
  - The link to the Settings section in the Selection Panel should not be displayed.

## Implementation Brief

* [x] Update `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.js`, use the `useViewOnly` hook to only render the `AudienceCreationNotice` outside of the view only context.
* *[Note: `AudienceSegmentationSetupCTAWidget.js` is already hidden in the view only context](https://github.com/google/site-kit-wp/blob/3b6c7d8d1829c77304bca8cc3f863f7a8e9547d9/assets/js/components/DashboardMainApp.js#L258-L265).*
* *[Note: the settings link is already hidden in the view only context](https://github.com/google/site-kit-wp/blob/ef83c39ccdc79115791a604cf2a2d5aee069c2c4/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Header.js#L63).*

### Test Coverage

* Update VRTs. No additional tests required.

## QA Brief

* Connect/create a property that requires the Site Kit audiences to be created.
* Switch to a view only user.
* The Audience Creation notice should not show in this context.
* Ensure that the other CTAs mentioned in the ACs do not appear in the view only dashboard as well. 

## Changelog entry

* Enhance Audience Segmentation CTAs to not appear on shared dashboard.

**Comment by techanvil** [comment]
Hi @hussain-t, just a heads up that I've tweaked the requirement for this issue to include removing the link to the settings section in the selection panel for view-only users.

**Comment by kuasha420** [comment]
Thank you @benbowler for working on this IB. A couple of points. 

1. Looks like `AudienceSegmentationSetupCTAWidget` is not being rendered on shared dashboard anyways as it's guarded in `assets/js/components/DashboardMainApp.js`.
2. We also should follow similar pattern for `AddGroupNotice`, by preventing it from rendering in shared dashboard in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.js`.

Thanks.

**Comment by benbowler** [comment]
Thanks @kuasha420, updated!

**Comment by kuasha420** [comment]
IB :heavy_check_mark:

**Comment by hussain-t** [comment]
We don’t have an easy way to view the Audience Segmentation widgets until [#8130](https://github.com/google/site-kit-wp/issues/8130) is implemented. Therefore, I’ve updated the dependency. This task should be worked on once [#8130](https://github.com/google/site-kit-wp/issues/8130) is completed.

cc: @techanvil @ivonac4

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Under the view mode, I was not able to see the tiles.
I can't access the selection panel to verify that the notice doesn't appear.
Am I missing any steps here? 

Video is below for reference.

<Details>

https://github.com/user-attachments/assets/664dc9fa-fca1-4f6a-86e8-1a595c463685


</Details>

**Comment by benbowler** [comment]
Hey @kelvinballoo, as this ticket is waiting on #8130, it won't be testable until that ticket is merged.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @benbowler for the clarification.
Since this is behind a feature flag, I am marking this ticket as Pass and I added a note here for the QAB of #8130  to be updated to include the testing of #8174.

Moving ticket to Approval.
