### ISSUE TITLE
Ensure the “Top content” metric doesn’t appear for view-only users if the custom dimension doesn’t exist

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8175]
## Feature Description

Ensure the “Top content” metric doesn’t appear for view-only users if the required custom dimension doesn’t exist.

See [dashboard sharing](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.w0br3nfp3mbe) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the view-only dashboard:
  * If the `googlesitekit_post_type` custom dimension doesn't exist, the "Top content" metric should not be shown at all in the Audience Tiles.
    * This is because the view-only user is unable to create the custom dimension, so we show a simplified view in this scenario.
  * In the edge case where the custom dimension does exist, but the available custom dimensions haven't been synced, the "Top content" metric should also not be shown. This is because the view-only user doesn't have permission to sync the available custom dimensions.

## Implementation Brief

- [x] In `AudienceTile` component present in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/index.js`
  - [x] Check if the dashboard is view only dashboard using `useViewOnly` hook.
  - [x] Check if the custom dimension `googlesitekit_post_type` is created and is available using the selector [hasCustomDimensions](https://github.com/google/site-kit-wp/blob/de09a10c23b15d090ed2207693f6ac9e1bb67f7e/assets/js/modules/analytics-4/datastore/custom-dimensions.js#L339-L361).
  - [x] Update the component to conditionally render `AudienceTilePagesMetric` component for top content if the custom dimension exists and dashboard is view only. For example:
  ```js
   { ( ( postTypeDimensionExists && viewOnly ) || ! viewOnly ) && ( <AudienceTilePagesMetric ... /> ) }
  ```

### Test Coverage

1. Add a story for `AudienceTile` where the `googlesitekit_post_type` dimension is not present and is in view only context.

2. Fix any other failing VR tests.

## QA Brief

1. Make sure audience segmentation is enabled and audiences tiles are visible in tiles.

2. Use a GA4 property with the edit access to it. Archive the custom dimension `googlesitekit_post_type` in the GA4 property.

3. Use the following snippet in the JS console to resync the available custom dimensions:
```js
googlesitekit.data.dispatch( 'modules/analytics-4' ).fetchSyncAvailableCustomDimensions();
```

4. Login with the view only user and check the tile, you should not see the `Top content by pageviews` metric.

5. Login with admin user and you should be able to see the `Update` button with the text

```
No data to show
Update Analytics to track metric
```

clicking on update will attempt to create the custom dimension, provided that the user has necessary permission for the property in GA.

## Changelog entry

* Fix a bug that could cause the "Top content" metric not to appear on the view-only dashboard.

**Comment by ivonac4** [comment]
@ankitrox can you add the estimate to this task? Thanks!

**Comment by techanvil** [comment]
Thanks @ankitrox, the IB LGTM. :white_check_mark:

**Comment by ankitrox** [comment]
This is ready for CR, but as it depends on #8130 , this will be moved to CR once 8130 is merged. 

Actions to take before moving to CR.

1. Merge develop into feature, push the changes.
2. Make sure all tests and VRTs are passing.
3. Make sure QA brief is up to date.

**Comment by techanvil** [comment]
Hi @ankitrox, I've merged the PR for this issue, but the QAB could use an update so I've assigned it to you in QA to make the amendment.

It's not necessary to use the mu-plugin you've provided to test this, and it's preferable to test things using a real-world user flow where possible, unless there's an exceptional reason not to.

In this case, we can test the issue by setting up Audience Segmentation using a property we've got edit access to and then archiving the custom dimension once it's created.

The property does need to be out of the gathering data state in order to set up the feature; it's reasonable to expect we should all have a property to hand that we can use for this sort of thing, but if needs be we can create a new property and then use the Tester plugin to provide mock report data in order to get the property out of the gathering data state.

![image](https://github.com/user-attachments/assets/57b7271f-de48-4a4f-b3f5-d5dc9f7d8d29)

I would expect QA engineers to have numerous existing properties to hand, though, so I wouldn't think this point is necessary to include in the QAB.

Please can you update the QAB accordingly?

**Comment by ankitrox** [comment]
Thank you @techanvil .

I have updated the QAB as per your instructions. It makes sense to use the GA4 property in real time. In the previous QAB I was expecting it to be tested with oi.ie analytics account.

Thanks for your feedback.

**Comment by techanvil** [comment]
Thanks @ankitrox! I added a point to the QAB as we need to resync the custom dimensions in order to test the scenarios.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

@ankitrox can you add the steps for testing this AC point when the custom dimension exists but haven't been synced:
`In the edge case where the custom dimension does exist, but the available custom dimensions haven't been synced, the "Top content" metric should also not be shown. This is because the view-only user doesn't have permission to sync the available custom dimensions.`


Items tested good: ✅ 
- When googlesitekit_post_type is archived, the 'Top Content' doesn't show on view-only dashbaord.
   <Details>
   When googlesitekit_post_type is archived, in the admin section, the update button will show and clicking on 
   it would re-created the googlesitekit_post_type dimension.

   <img width="1206" alt="Screenshot 2024-09-10 at 11 52 30" src="https://github.com/user-attachments/assets/ca129f9f-7af2-4513-ad7c-68a8922fdeb8">



   View-only audience when googlesitekit_post_type is archived, the 'Top Content' doesn't show:
   <img width="1208" alt="Screenshot 2024-09-10 at 12 10 47" src="https://github.com/user-attachments/assets/6e301f67-10a0-486e-9caf-99c296fea2ec">

   </Details>

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Per latest conversion in [slack](https://fueled10up.slack.com/archives/C077DB69US2/p1725981040132819?thread_ts=1725957323.328869&cid=C077DB69US2), the edge case can be tested through the following steps:

- Set up SK and enable visitor groups.
- Run the following snippet to clear the cached custom dimensions:
```
   await googlesitekit.data.dispatch( 'modules/analytics-4' ).setAvailableCustomDimensions([]);
   googlesitekit.data.dispatch( 'modules/analytics-4' ).saveSettings();
```
- Share Analytics and login as a view-only user.
- You should see the audience tiles w/out the "Top content metric".

Did as per the steps and the 'Top content metric' did not appear for the view-only user. ✅ 
<Details>
<img width="1084" alt="Screenshot 2024-09-11 at 13 34 04" src="https://github.com/user-attachments/assets/e7cef9e4-5cb7-410a-9bad-f0da97c3ba44">

</Details>


________________________________

The main use-case was also verified good: ✅ 
 - When googlesitekit_post_type is archived, the 'Top Content' doesn't show on view-only dashbaord.
   <Details>
   When googlesitekit_post_type is archived, in the admin section, the update button will show and clicking on 
   it would re-created the googlesitekit_post_type dimension.

   <img width="1206" alt="Screenshot 2024-09-10 at 11 52 30" src="https://github.com/user-attachments/assets/ca129f9f-7af2-4513-ad7c-68a8922fdeb8">



   View-only audience when googlesitekit_post_type is archived, the 'Top Content' doesn't show:
   <img width="1208" alt="Screenshot 2024-09-10 at 12 10 47" src="https://github.com/user-attachments/assets/6e301f67-10a0-486e-9caf-99c296fea2ec">

   </Details>
