### ISSUE TITLE
Add the Settings Section toggle switch variant and hook up the setting to toggle the Audiences Widget Area on/off

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8177]
## Feature Description

Add the Settings Section toggle switch variant and hook up the setting to toggle the Audiences Widget Area on/off.

See [Settings section](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.dv11b27p35s5) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A toggle switch is implemented in the Settings Section under the Admin Settings tab, below the Key Metrics section.
* The toggle switch controls the visibility of the Audiences Widget Area.
* The setting is persistent through the `POST audience-settings` endpoint and reflects the current state of the Audiences Widget Area visibility.
* The feature aligns with the guidelines in the [design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.dv11b27p35s5) and the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1512-32992&mode=design&t=n6n9UqDiQdHeAVag-0).

## Implementation Brief

* [x] Add `assets/js/modules/analytics-4/components/settings/AudienceSegmentation/SettingsVisitorGroups.js`
  * Use `assets/js/components/settings/SettingsPlugin.js` as a starting point
  * Replace `Checkbox` component with `Switch` component
  * Apply styling and text as outlined in design doc and figma linked in AC
  * In the `onChange` callback, save the settings using the `setAudienceSegmentationWidgetHidden` action and check for the value using `isAudienceSegmentationWidgetHidden` action, implemented in [7176](https://github.com/google/site-kit-wp/issues/8176), 
* [x] Update `assets/js/components/settings/SettingsAdmin.js` 
  * After https://github.com/google/site-kit-wp/blob/c173f6c206ce0b7f2eb0777b0acfe3bfe649c385/assets/js/components/settings/SettingsAdmin.js#L50-L54 Check if `analytics-4` module is active, using `isModuleActive` selector on `CORE_MODULES` datastore, and if `audienceSegmentation` feature flag is enabled to render `SettingsVisitorGroups` component  wrapped with  `<Cell size={ 12 }>` component

### Test Coverage

* Add tests for `SettingsVisitorGroups` component, ensuring the switch's actions send the events mentioned in the description/ACs

## QA Brief

* Ensure the Analytics module is connected.
* Ensure the Audience Segmentation feature flag is enabled via the tester plugin.
* Navigate to the Settings page -> Admin Settings and verify the `Visitor groups` section with the toggle switch is displayed under the `Key Metrics` section.
* Verify the toggle switch is functional and toggles the visibility of the Audiences Widget Area.
* Verify the setting is persistent through the POST `audience-settings` endpoint.
* Go to the browser's Network tab and check the POST request for `audience-settings` when toggling the switch.
* Once merged, verify this [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-settingscardvisitorgroups--default).

## Changelog entry

* Add a settings toggle for Audience Segmentation.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
IB ✅

**Comment by techanvil** [comment]
Hey @zutigrm, as mentioned on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1707132930927679) I've added a [code organization](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.mlj74m7pz9gr) section to the design doc to help keep us aligned.

The upshot is that we should create this new `SettingsVisitorGroups` in the `assets/js/modules/analytics-4/components/settings/AudienceSegmentation/` folder.

It's also worth noting that the audience settings will only be available if `analytics-4` is active so we should make that a condition for displaying the settings section.

Please can you update the IB accordingly?

**Comment by techanvil** [comment]
Thanks for the update @zutigrm, IB LGTM! :white_check_mark:

**Comment by aaemnnosttv** [comment]
⚠️ I noticed a misspelling which should be fixed but can happen in a follow-up https://github.com/google/site-kit-wp/pull/8424#pullrequestreview-1983969282
