### ISSUE TITLE
Don't disconnect user on login if refresh token is invalid

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#818]
## Bug Description

When logging in, we currently try to refresh the user's access token if they already have one. Whenever that fails with the error `invalid_grant`, we disconnect the user, which makes sense in this scenario. However, since we've migrated to the proxy, this can fail for various other reasons than only the refresh token being invalid (`invalid_grant`).

It has been a common support issue that users had to re-authenticate after logging in. Most likely, this is due to the refresh request failing because of the known rate limit issues and being interpreted as `invalid_grant`, although it may be something different (and now in many cases is).

Furthermore, no error message is shown to the user at all in case of `invalid_grant`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* We should rely on the actual error being returned from the proxy and not simply assume `invalid_grant`.
* The user must only be disconnected on login if the refresh token failed with the specific error `invalid_grant`.
* When an error happens during refreshing a token, the user should see that error in the admin notice as expected on next page load, specifically also when the error was `invalid_grant`.

## Implementation Brief

* If proxy is being used, rely on the actual `Exception::getMessage()` (like we already do in `OAuth_Client::authorize_user()`.
* If user is being disconnected during login because of `invalid_grant` error, re-set that error in the user's options so that they still see that error message on next pageload.
* See #819.

## Changelog entry

* Do not disconnect user when refreshing an access token randomly fails, and ensure the user sees an error message about any errors during the process.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by adamsilverstein** [comment]
Code change looks good, I am unsure how to reproduce the conditions that create the error in the first place - any tips?

**Comment by felixarntz** [comment]
@adamsilverstein I think the only way to enforce this would be to make a code change to trigger a `invalid_grant` exception in `refresh_token()`'s `try` clause, test whether then you get disconnected and see a message, then change that to trigger some other random exception (e.g. `checking requirements failed`) and then test whether you _not_ get disconnected.

Otherwise, the situation is not consistently reproducible unfortunately.

**Comment by adamsilverstein** [comment]
This issue is very difficult to test without making direct code changes to simulate the error scenario. Testing this way doesn't completely test the code is going to work.

Since the code changes in https://github.com/google/site-kit-wp/pull/819 are limited to error message handling I think its safe to deploy these changes and continue monitoring reports of the `invalid_grant` error.
