### ISSUE TITLE
Add Site Health section

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8181]
## Feature Description

Add the new “Analytics 4 site created audiences” section to Site Health.

See [Site Health](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.hppr5cex19dy) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the `audienceSegmentation` feature flag is enabled, the Site Health section for Site Kit should contain a new section.
* The title for the section should be: _Analytics site created audiences_.
* The value of the section should a list of the audiences that Site Kit has created, i.e. the "new visitors" and "returning visitors" audiences, if they exist.
* The names of these audiences should be displayed as they are in Analytics (i.e. their display names should be presented in the list).

## Implementation Brief

- [ ] In `includes/Modules/Analytics_4.php`, inside the `get_debug_fields` method:
  - [ ] Check if the `audienceSegmentation` feature flag is enabled.
  - [ ] If it is enabled, add a new entry in `$debug_fields` with following:
    - [ ] `label` as `Analytics site created audiences`.
    - [ ] `value` as comma separated string, containing the `displayName` fields from the audiences stored in the `availableAudiences` setting whose `audienceType` is `'SITE_KIT_AUDIENCE'`. Feel free to add an additional method to retrieve these, or it can be inlined.
    - [ ] `debug` should be the same value.
  - [ ] An example of adding a debug field conditionally can be seen [here](https://github.com/google/site-kit-wp/blob/8b33773dd1457d710d2bbcc8d2a744c502055e8b/includes/Modules/Analytics_4.php#L504-L516).

### Test Coverage

* In `tests/phpunit/integration/Modules/Analytics_4Test.php` fix the `test_get_debug_fieldss` test.
* Fix any other failing tests.

## QA Brief

* Ensure that you have access to analytics 4 property where you can create the audiences. This will require write permission. Connect such a property in Google analytics in site kit.

* Run the following command in browser console.

```js
const newAudience = {
    "description": "People who visited the site for the first time",
    "displayName": "New visitors",
    "exclusionDurationMode": null,
    "membershipDurationDays": 30,
    "filterClauses": [
        {
            "clauseType": "INCLUDE",
            "simpleFilter": {
                "scope": "AUDIENCE_FILTER_SCOPE_ACROSS_ALL_SESSIONS",
                "filterExpression": {
                    "andGroup": {
                        "filterExpressions": [
                            {
                                "orGroup": {
                                    "filterExpressions": [
                                        {
                                            "dimensionOrMetricFilter": {
                                                "atAnyPointInTime": null,
                                                "fieldName": "newVsReturning",
                                                "inAnyNDayPeriod": null,
                                                "stringFilter": {
                                                    "caseSensitive": null,
                                                    "matchType": "EXACT",
                                                    "value": "new"
                                                }
                                            }
                                        }
                                    ]
                                }
                            },
                            {
                                "orGroup": {
                                    "filterExpressions": [
                                        {
                                            "notExpression": {
                                                "dimensionOrMetricFilter": {
                                                    "fieldName": "groupId",
                                                    "stringFilter": {
                                                        "matchType": "EXACT",
                                                        "value": "created_by_googlesitekit:new_visitors"
                                                    }
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            }
        }
    ]
};

const returningAudience = {
    "description": "People who have visited your site at least once before",
    "displayName": "Returning visitors",
    "exclusionDurationMode": null,
    "membershipDurationDays": 30,
    "filterClauses": [
        {
            "clauseType": "INCLUDE",
            "simpleFilter": {
                "scope": "AUDIENCE_FILTER_SCOPE_ACROSS_ALL_SESSIONS",
                "filterExpression": {
                    "andGroup": {
                        "filterExpressions": [
                            {
                                "orGroup": {
                                    "filterExpressions": [
                                        {
                                            "dimensionOrMetricFilter": {
                                                "atAnyPointInTime": null,
                                                "fieldName": "newVsReturning",
                                                "inAnyNDayPeriod": null,
                                                "stringFilter": {
                                                    "caseSensitive": null,
                                                    "matchType": "EXACT",
                                                    "value": "returning"
                                                }
                                            }
                                        }
                                    ]
                                }
                            },
                            {
                                "orGroup": {
                                    "filterExpressions": [
                                        {
                                            "notExpression": {
                                                "dimensionOrMetricFilter": {
                                                    "fieldName": "groupId",
                                                    "stringFilter": {
                                                        "matchType": "EXACT",
                                                        "value": "created_by_googlesitekit:returning_visitors"
                                                    }
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            }
        }
    ]
}

googlesitekit.data.dispatch('modules/analytics-4').createAudience(newAudience);
googlesitekit.data.dispatch('modules/analytics-4').createAudience(returningAudience);
```

This will trigger two requests to `modules/analytics-4/data/create-audience` in the browser which should create two new audiences `New visitors` and `Returning visitors` in Google Analytics.

* Once above requests are executed successfully with 200 response code, run following command in browser console.

```js
googlesitekit.data.dispatch('modules/analytics-4').syncAvailableAudiences();
```

It will sync audiences from Google Analytics to Site Kit.

* Go to `Tools > Site Health > Info > Site Kit by Google`, you must see the section `Analytics site created audiences` with value `New visitors, Returning visitors`. 

## Changelog entry

* Add a Site Health section which lists the Site Kit-created audiences.

**Comment by techanvil** [comment]
Hi @ankitrox, thanks for drafting this IB. However, the approach you've suggested is not really necessary - we can add to the `Analytics_4::get_debug_fields()` method instead, where the other Analytics related Site Health fields are defined.

For example, see the "available custom dimensions" entry:

https://github.com/google/site-kit-wp/blob/e023adfaabad7ba4ebc2fb46a761e87cd05b8021/includes/Modules/Analytics_4.php#L428-L440

![image](https://github.com/google/site-kit-wp/assets/18395600/d98f78ef-6025-43e6-af6e-fad3e6bd3194)

**Comment by ankitrox** [comment]
Thank you @techanvil for reviewing the IB.

I agree that adding the literal code block is not good idea as the execution should be at the engineer's discretion.

As per your suggestion, I have removed the code block and added the list wide pointers for the implementation. 

Assigning it to you for the review again.

Thank you.

**Comment by techanvil** [comment]
Thanks @ankitrox!

I've made some additional changes to the IB. Notably I've removed the explicit definition for the new method and left this optional, and also removed the point about calling `redact_debug_value()` for the `debug` field, this is not needed here as the names are not personal data, rather they are standard names that all Site Kit users may see. I've also made a few minor grammatical tweaks.

Please review the changes and if you are happy feel free to move this to the EB.

IB :white_check_mark:

**Comment by ankitrox** [comment]
Looking everything good. Thanks @techanvil 

Moving this to EB.

**Comment by techanvil** [comment]
Hi @ankitrox, please can you update the QAB for this issue as follows:

- Rather than providing an audience configuration for "SiteKit Audience", provide instructions for creating audiences with the configuration for the "new visitors" and "returning visitors" audiences. This will be more representative of the real world expectations, and also allow testing the comma separated list rather than a single audience.
- Ensure that names are correctly formatted with uppercase initials. In this case "Analytics" (referring to Google Analytics) and "Site Kit" are lowercased where they should be name-cased.

**Comment by ankitrox** [comment]
Hi @techanvil ,

Thank you for the review. 

I have addressed your feedback on the PR and also updated QAB so that we create `New visitors` and `Returning visitors` audiences in Google Analytics.

Assigning this to you for the re-review.

Thank you.

**Comment by techanvil** [comment]
Thanks @ankitrox! I've left a few further comments on the PR, please take a look.

I've also tweaked the code example in the QAB slightly to follow our usual naming conventions (not essential, but might as well!), and to be slightly more verbose - we don't need to aim for DRY code in QABs, it's generally better if it's slightly more straightforward.

**Comment by ankitrox** [comment]
Thank you @techanvil for reviewing the PR.

I have addressed the comments in the PR and QAB code is looking good. 

Assigning this back to you for review.

Thanks.

**Comment by ankitrox** [comment]
Thank you @techanvil for reviewing the PR.

I've made the suggested change and assigning this to you for the review.

Thanks.

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Hi @ankitrox , tested this and I was able to do all the steps but in the end, there was not section with the values 'New visitors' and 'Returning visitors' in the Tools > Info section. The details are below:

- I created the 2 audiences successfully.
   <Details>
   <img width="1159" alt="Screenshot 2024-06-05 at 14 45 21" src="https://github.com/google/site-kit-wp/assets/125576926/93044bd7-e746-42dc-a9d3-542c3cff4d24">
   
   All requests were with 200 status:
   <img width="1119" alt="Screenshot 2024-06-05 at 14 40 31" src="https://github.com/google/site-kit-wp/assets/125576926/bf3062a6-aae3-459c-94d0-93c56a987077">


   </Details>

- I synced the audiences accordingly with status 200:
   <Details>
   <img width="1312" alt="Screenshot 2024-06-05 at 14 45 15" src="https://github.com/google/site-kit-wp/assets/125576926/4a2f4120-c666-457f-b6c9-3725f68449c4">

   </Details>

- However, I could not see the expected values in the Tools > Site Health > Info > Site Kit by Google section
   <Details>
   <img width="622" alt="Screenshot 2024-06-05 at 14 47 05" src="https://github.com/google/site-kit-wp/assets/125576926/7a8119b8-5b11-450e-86f2-eb53b5de3d57">

   <img width="703" alt="Screenshot 2024-06-05 at 14 47 20" src="https://github.com/google/site-kit-wp/assets/125576926/03d66c5d-dfb1-41a1-b939-9f543edcfe2c">

   </Details>

Assigning ticket to you for further check.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

After reviewing together with @ankitrox , it seems like my branch was not properly connected to Develop.
I re-set it to 'Develop' and it worked fine then.

- All the scripts are successfully executed
- Going to Tools > Site Health > Info > Site Kit by Google, I can see the section **Analytics site created audiences** with value **New visitors, Returning visitors**.

Moving this ticket to Approval

<Details>
Scripts are successful:
<img width="1119" alt="Screenshot 2024-06-05 at 14 40 31" src="https://github.com/google/site-kit-wp/assets/125576926/8ddd63d2-157f-4881-9a0d-16881ee693c0">

Audiences created successfully:
<img width="1159" alt="Screenshot 2024-06-05 at 14 45 21" src="https://github.com/google/site-kit-wp/assets/125576926/82b42fc3-d966-4b0f-a6c2-c9716c9f5dd6">

Values appear at Tools > Site Health > Info > Site Kit by Google
<img width="819" alt="Screenshot 2024-06-05 at 15 14 56" src="https://github.com/google/site-kit-wp/assets/125576926/a78c9367-d657-462f-b1d1-71934f6a60c1">

</Details>
