### ISSUE TITLE
Analytics data inconsistent for Arabic language pages in Site Kit

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#8184]
## Bug Description

As flagged by a [user in the support forum](https://wordpress.org/support/topic/arabic-language-didnt-support/), Analytics data for Arabic language pages/URLs is inconsistent across Site Kit displaying 0 data in some sections and the accurate data in others.

The Site Kit admin bar will display 0 data across the board for these pages which is also the case when selecting **More details** to view the specific page stats page.  However, when checking the Site Kit Dashboard top content section you can see data for this page. Data can also be seen from the Analytics platform.

When viewing the data for the page, you can see that the URL is encoded due to the Arabic language characters. This is probably related to the way we are this in Site Kit.

All screenshots of this when testing are supplied below. 

## Steps to reproduce

1. Create a page with Arabic characters
2. Accumulate data for that page
3. Check the data for that page in the admin bar, stats page, dashboard and Analytics platform to compare

## Screenshots

SK dashboard top content: https://imgur.com/a/kiaZn1g 
Page stats in SK: https://imgur.com/a/zZvVcCY 
Admin bar stats: https://imgur.com/a/2HjXWB8 
Data in Analytics: https://imgur.com/a/SVeNh4p

## Additional Context

The test site to see this is https://plastiskip.com/ (Access to the site and Analytics account can be granted by @jamesozzie )

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Stats should show correctly for pages/URLs with slugs with special characters such as Arabic, with special attention on the Admin bar and entity dashboards
* URLs with special characters should be displayed in their decoded forms

## Implementation Brief

The problem is due to Entity URLs for single posts as WP encodes the slug when storing the post which is not automatically decoded by `get_permalink`.

- Ensure entity URLs are decoded properly.
- Finish and merge https://github.com/google/site-kit-wp/compare/fix/8745

### Test Coverage

* The above branch adds some missing coverage for `Entity_Factory::create_entity_for_post` 

## QA Brief

* Setup Site Kit and connect Analytics module, on existing website or on a new one
* Add a page with an Arabic title, example, copy this "عنوان صفحة الاختبار"
* Make a few visits on it, so some views can be tracked
* Tomorrow, verify that page is showing data in main dashboard, under `Top content over the last 28 days`, Site Kit admin bar dropdown on that page, and on single entity page view, and any other place/widget

## Changelog entry

* Fix Analytics data inconsistency for Arabic language pages.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

Waiting for data to appear in Site Kit in 24 hours. 

- Setup Site Kit and connect Analytics module.
- Added a page with an Arabic title.
- Made a few visits on it, so some views can be tracked

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The page is showing data in main dashboard, under `Top content over the last 28 days`, Site Kit admin bar dropdown on that page, and on single entity page view, and any other place/widget.  I compared this with Google Analytics too. 

<details>
 <summary>Screenshots</summary>

 ![image](https://github.com/google/site-kit-wp/assets/73545194/f19da624-4d2d-4b67-b57c-3d49e0cf70a4)
![image](https://github.com/google/site-kit-wp/assets/73545194/5a95bce2-1d8c-4f2a-a434-b4adc81a239d)
![image](https://github.com/google/site-kit-wp/assets/73545194/9af47fc0-49b9-4172-b6ac-ddf21b58d574)
![image](https://github.com/google/site-kit-wp/assets/73545194/7c50d8d4-35cf-4742-badf-ccb2e3e55c13)

</details>
