### ISSUE TITLE
Implement the “no audiences” banner error state

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8190]
## Feature Description

Implement the error handling for the "no audiences" banner, showing the [Full Width Error Banner](https://github.com/google/site-kit-wp/issues/8230) when there is an error.

See [no audiences banner > error state](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.xfl89g3zosvd) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Given that the Audience Segmentation feature has already been set up:
  - If an error occurs when syncing the list of available audiences (which should occur for an authenticated user, either when viewing the Audience Widget Area and an hour or more has passed since the last sync, _or_ when opening the Audience Selection Panel the first time for a given page load):
    - The Full Width Error Banner should be displayed in the appropriate variant.
      - If a permission error is returned by the API call, the "insufficient permissions" variant of the error banner will be shown (see the AC for https://github.com/google/site-kit-wp/issues/8230).
      - Otherwise, the catch-all variant will be shown. Clicking the **Retry** button will retry syncing the list of available audiences.
    - The Audience Tiles and Info Notice should not be displayed.

## Implementation Brief

_Note that we should ensure this IB is drafted after that of its dependency, https://github.com/google/site-kit-wp/issues/8147._

- [x] Within `AudienceTilesWidget`, retrieve the `syncAvailableAudiences` error via `getErrorForAction()`.
  - [x] If the error is set:
    - [x] Render `AudienceSegmentationErrorWidget`, passing the error via the `errors` prop.
    - [ ] If the error is _not_ an insufficient permission error:
      - Pass the `showRetryButton` and `onRetry()` props.
      - In the `onRetry()` callback, clear the `syncAvailableAudiences` error and dispatch the `syncAvailableAudiences()` action.
-  Refer to [`AudienceSelectionPanel/ErrorNotice`](https://github.com/google/site-kit-wp/blob/b35f9e40ca1f792597551254a11c2d8afa0a601f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/ErrorNotice.js#L37-L42) for similar logic regarding the `syncAvailableAudiences` error.

### Test Coverage

* Add JS test coverage for the changes to `AudienceTilesWidget`.

## QA Brief

1. Enable audience segmentation and enable audience groups so that audiences are visible in audience tile area.

2. Install [Time Travel](https://chromewebstore.google.com/detail/time-travel/jfdbpgcmmenmelcghpbbkldkcfiejcjg?hl=en) extension in chrome.

3. Using the [Tweak](https://chromewebstore.google.com/detail/tweak-mock-and-modify-htt/feahianecghpnipmhphmfgmpdodhcapi?hl=en) Chrome extension, create a rule as follows.

* URL: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/sync-audiences.*`
* Enable the use of regular expressions (.*)
* HTTP Method: `POST`
* Status code: 400
* Response payload.

```js
{
    "code": 400,
    "message": "Some Error",
    "data": {
        "status": 400,
        "reason": "Some Reason"
    }
}
```

4. Set the time in Time travel extension to couple of hours later in the future. Reload the page.

5. There should be a the error banner visible in audience tile area with retry button.

6. Change the payload in tweak to following and refresh the page. This time, there should be no retry button, but banner should be visible.

```js
{
  "code": 400,
  "message": "Some Error",
  "data": {
    "status": 400,
    "reason": "insufficientPermissions"
  }
}
```

## Changelog entry

* Add handling for audience sync errors in the audiences widget area.

**Comment by ivonac4** [comment]
@techanvil it looks like this should be added to the design doc, right?

**Comment by techanvil** [comment]
@ivonac4 yup this has been added to the design doc, I've created an additional issue in for the component and added that as a dependency here. This issue is now ready for AC.

**Comment by techanvil** [comment]
I've moved this back to Backlog as the final [in-progress changes to the design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABJiKQwSo), relating to audience caching, will probably affect the AC for this one.

I've also unassigned @jimmymadon from this one due to his break.

**Comment by techanvil** [comment]
The audience caching aspect of the design doc has been sufficiently finalised, and I've moved this back to AC.

**Comment by techanvil** [comment]
Hey @kuasha420, just letting you know I've picked this one up to add the AC.

**Comment by kuasha420** [comment]
Hi @techanvil, the IB looks good overall. 

However, in #8130 (related PR #9219) we added a `onRetry` prop to `AudienceSegmentationErrorWidget` [here](https://github.com/google/site-kit-wp/blob/6e48eacb8fe74493f90bc7d99779a87ac77d7a76/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationErrorWidget.js#L49). Maybe we can use that instead of creating the new `errorActions` prop. What do you think? 

Cheers.

**Comment by techanvil** [comment]
Thanks @kuasha420, that's a good point. #8130 has some related feedback, so I'll hold off until it's been merged and update the IB for this issue accordingly.

**Comment by techanvil** [comment]
With 8130 merged, I've updated the IB for this issue. Back to you for another pass, @kuasha420.

**Comment by kuasha420** [comment]
Thanks @techanvil! That simplifies a lot :smile: 

IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested using Tweak and Time Travel extension.
- _Verified that -_
-  If a permission error is returned by the API call, the "insufficient permissions" variant of the error banner appear.
- Otherwise, the catch-all variant appears. Clicking the Retry button retry syncing the list of available audiences.
- The Audience Tiles and Info Notice not display.

_**Insufficient Permission error banner**_

<details>

https://github.com/user-attachments/assets/9ef95245-9702-4f03-ae97-8f5cbeef91f4

</details>

**_Error banner with Retry Button_**

<details>

https://github.com/user-attachments/assets/77f43f85-3a53-4a08-83ef-ac8fc67a7fce

</details>
