### ISSUE TITLE
Remove functionality preventing GA4 from outputting tags when GTM takes over 

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8196]
## Feature Description

Originally, when GA was already connected, and the selected Tag Manager container had a tag that was a valid UA `trackingId` which matched the existing `propertyId` saved in Analytics settings, we would prevent the Analytics module from outputting the snippet. This was mainly to prevent UA from tracking duplicate events. This screen is highlighted in point 2 of this [comment](https://github.com/google/site-kit-wp/issues/7989#issuecomment-1915654586). This issue does not arise as having multiple snippets for the same GA4 data stream does not duplicate events in GA4.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Code and infrastructure solely in place to prevent the Analytics module from outputting the tag snippet when a GTM container had a UA tag within it with the same property ID (or now, a Google Tag after #7990 is merged) should be removed.

## Implementation Brief

Note: Removing code from the old `Analytics` module is unnecessary since this will be removed in a couple of sprints. However, for completeness of this PR/issue and since SAM might not launch at the same time as this issue being merged, we should remove these pieces anyways.

* [x] Remove the `gaPropertyID` setting and all of its usage from the Tag Manager module:
  * [x] In `includes/Modules/Tag_Manager/Settings.php`:
    * [x] Remove the `gaPropertyID` setting.
  * [x] In `includes/Modules/Tag_Manager.php`:
    * [x] Remove the `googlesitekit_analytics_can_use_snippet` filter and its implementation in `can_analytics_use_snippet`.
  * [x] In `assets/js/modules/tagmanager/datastore/base.js`:
    * [x] Remove the `gaPropertyID` setting field.
  * [x] Remove `assets/js/modules/tagmanager/hooks/useGAPropertyIDEffect.js` and all of its usage from:
    * [x] `assets/js/modules/tagmanager/components/settings/SettingsEdit.js`
    * [x] `assets/js/modules/tagmanager/components/setup/SetupMain.js`

* [x] Remove the `canUseSnippet` setting and all of its usage from the `Analytics` and `Analytics-4` modules:
  * [x] Remove the backend setting and its usage from:
    * `includes/Modules/Analytics/Settings.php`
    * `includes/Modules/Analytics_4/Settings.php`
  * [x] Remove the entire tag guard: `includes/Modules/Analytics/Tag_Guard.php`
  * [x] In `assets/js/modules/analytics/datastore/base.js`:
    * Remove the `canUseSnippet` setting.
  * [x] In `assets/js/modules/analytics/datastore/settings.js`:
    * [x] Remove the `getCanUseSnippet` selector.
  * [x] Remove usage from:
    * [x] `assets/js/modules/analytics/components/common/AdsConversionIDTextField.js`
    * [x] `assets/js/modules/analytics/components/common/UseSnippetSwitch.js`
    * [x] `assets/js/modules/analytics/components/settings/OptionalSettingsView.js`
    * [x] `assets/js/modules/analytics/components/settings/SettingsUseSnippetSwitch.js`
    * [x] `assets/js/modules/analytics/components/setup/SetupUseSnippetSwitch.js`

### Test Coverage

* [x] No new tests required.
* [x] Remove all tests related to the `googlesitekit_analytics_can_use_snippet` from `tests/phpunit/integration/Modules/Tag_ManagerTest.php` and `tests/phpunit/integration/Modules/Analytics/SettingsTest.php`.
* [x] Remove the `getCanUseSnippet` selector tests from `assets/js/modules/analytics/datastore/settings.test.js`.
* [x] Remove all references to `canUseSnippet` and `gaPropertyID` that have been removed above from stories, tests and fixtures.

## QA Brief

* Connect GTM module and select a container that includes GA4 property. 
* The GTM snippet should be placed in the Website. 
* Now connect GA4 and configure the same property as GTM. 
* There will be two snippets in the front end. One from GA4 module and the other from GTM. 

## Changelog entry

* Allow multiple snippets when using Google Analytics 4 and Google Tag Manager.

**Comment by ivonac4** [comment]
@jimmymadon is it possible to add Type and Priority label to this ticket at this moment?

**Comment by tofumatt** [comment]
IB ✅

**Comment by zutigrm** [comment]
Unnasigning myself as it will take me more time to go through whole PR, in order to focus on priority issue I need to finalize till EOD before the vacation

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@tofumatt I was wondering if you could help here in Jimmy's absence.   I am not seeing the GA4 snippet.  Here are the steps I undertook.  I created an account on GTM and added a GA4 measurement Id (and Google tag) to the new container. Submitted the container with tag. I connected GTM and selected that I didn't want to set up Analytics and instead set up with GTM, but no GA4 snippet appears as per the QAB. 

I don't feel like I missed any steps, but I wondered if you could review the QAB and provide additional details.

**Comment by tofumatt** [comment]
I just ran through the QA steps as you did and saw both tags:

![Screenshot 2024-03-01 at 12 37 56](https://github.com/google/site-kit-wp/assets/90871/cc5f03f6-bf10-46ea-9119-96674f81a8d6)

The QA Brief omits this bit of info, but did you remember to check the website in a private browsing window/another browser where you _aren't logged in to WordPress_? Otherwise a tag/tags might be missing because they don't appear for signed-in users.

But I was able to see both after testing, as long as I viewed the site as an "anonymous" user on the front-end. 🤔

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt I am not sure if its me being stupid (possible) but I cannot get this to pass.  I am looking at the QAB:

```
Connect GTM module and select a container that includes GA4 property.
The GA4 snippet should be placed in the Website.
```
When setting up GTM, I selected `Complete setup without Analytics` because Analytics is not connected I looked at the site in incognito and did not see the GA4 snippet in the source code.  

![image](https://github.com/google/site-kit-wp/assets/73545194/658de161-fc61-4275-84ac-d0b57df01532)

Within GTM, I added a GA4 measurement ID and Google tag. 

Here's my GTM setup.  I clicked on submit and published the tag within the container. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/dd782a64-ec9a-4e4d-9598-25550d7e2260)
![image](https://github.com/google/site-kit-wp/assets/73545194/3ae3410e-7c32-4dd9-a931-0196b8aa35c8)
![image](https://github.com/google/site-kit-wp/assets/73545194/756fbf83-ac42-40c9-8345-d1fabed604a5)

</details>

Any ideas why I cannot see the GA4 code like in your screenshot?

**Comment by wpdarren** [comment]
@tofumatt No, as I said in my comment, I have not set up Analytics, just Google Tag Manager with a GA4/Google Tag against a container.  I think we need to sync about this because I have spent much time trying to get this to work as per the QAB.  I will reach out to you when I am online.

**Comment by tofumatt** [comment]
https://github.com/google/site-kit-wp/assets/90871/4f9aef38-6214-409a-a8aa-cb2d23aeea00

I've attached a screenshot showing the QA steps I took to get both. Seems like the QA Brief was misunderstood, thinking GA shouldn't be connected, but it should 😄

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- The GTM snippet is placed in the Website.
- There are two snippets in the front end. One from GA4 module and the other from GTM.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/aabc4367-2498-473d-b264-b529e803ff34)
![image](https://github.com/google/site-kit-wp/assets/73545194/dc937ce2-efca-4cdc-a556-af2ec2f94929)

</details>
