### ISSUE TITLE
Add `adsModule` Feature Flag

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8197]
## Feature Description

The `adsModule` feature flag should be added to Site Kit as a prerequisite for the Ads module feature development.

See [relevant section in design doc](https://docs.google.com/document/d/1APuSv95bf62uhzlaFlW6jPrzPKy1avpRYd9W1MSAAJo/edit?resourcekey=0-UuynlcUz9CoubgldR6Z5sg#heading=h.u26gj5vc0mo9).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `adsModule` feature flag should be added to Site Kit.
- The `adsModule` feature flag should appear in the tester plugin.

## Implementation Brief

- Add an `adsModule` feature flag to `feature-flags.json`.

### Test Coverage

* No new tests required.

## QA Brief

- Ensure the `adsModule` feature flag appears in the Site Kit Tester plugins' list of feature flags.

## Changelog entry

* N/A

**Comment by 10upsimon** [comment]
Noting that this is in ACR, but is ready for IBR as well, given the simplicity of the issue.

**Comment by ivonac4** [comment]
@10upsimon is it possible to add Type and Priority to this ticket at this moment?

**Comment by 10upsimon** [comment]
@ivonac4 I added a type and priority, but I have never added a priority myself to be honest, so I am guessing a little that it'll be a P1 as we need to get cracking with this work soonest, cc @bethanylang

**Comment by 10upsimon** [comment]
@ivonac4 @bethanylang for transparency sake, I added a new `Module: Ads` label.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that `adsModule` feature flag appears in the Site Kit Tester plugins' list of feature flags.

![image](https://github.com/google/site-kit-wp/assets/94359491/5d1be6f8-f838-4df8-8d8b-8e47fe06b3bc)
