### ISSUE TITLE
Remove the link to Settings in the Key Metrics selection panel for view-only users

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8202]
## Feature Description

View-only users don't have permission to access the Settings page, so we should remove the link to Settings from the Key Metrics selection panel for these users.

![image](https://github.com/google/site-kit-wp/assets/18395600/cbec055f-b16b-441c-854b-de11c0f21a8a)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Key Metrics selection panel should not display the highlighted text and link to the Settings page for view-only users.

## Implementation Brief
* Using `assets/js/components/KeyMetrics/MetricsSelectionPanel/Header.js`,
	* check if the user is "view-only" via the `useViewOnly` hook.
	* Do not render the 'Edit your personalized...' paragraph if the above value is `true`.
* Update `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.stories.js` to add a new story for the "view-only" mode.

### Test Coverage
* Update `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js` to include test to not displaying the paragraph when the user is in view only mode.

## QA Brief

- Set up Site Kit and KM widgets.
- Open the Key Metrics selection panel.
- Verify the link to Settings "Edit your personalized goals or deactivate this widget in 
Settings" exist.
- Log in with a view-only user.
- Verify that this text doesn't exist anymore.

## Changelog entry

* Update the Key Metrics selection panel not to display the link to Settings in the view-only mode.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The link to Settings "Edit your personalized goals or deactivate this widget in Settings" exists for an admin.
- With a view-only user, this text doesn't appear anymore
- Tested this on desktop and smaller viewports like mobile. 
- Tested with a 2nd admin who visits the dashboard as view only to confirm the text does not appear. 
- Tested this with a 2nd admin user who connects their Google account and the text does appear. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/0257b3d2-551c-40f3-95ec-efcf1954fc84)
![image](https://github.com/google/site-kit-wp/assets/73545194/9d68ee8a-2c01-4ae1-816e-b1e0a6420260)
![image](https://github.com/google/site-kit-wp/assets/73545194/a098e998-a3ed-4e49-bdc5-78e485f37be7)
![image](https://github.com/google/site-kit-wp/assets/73545194/5fad04cf-36b0-42da-8401-7d1abee9b535)

</details>
