### ISSUE TITLE
Remove Analytics 'New' badges on the Entity Dashboard 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8203]
## Bug Description

On the Entity dashboard the ‘new’ badges are still appearing, we removed them from the main dashboard.  THe badges appear on the `Sessions` and `Engagement Rate` fields.  The new badges include useful information for the users, so we might want to look at keeping this in a tooltip so we should discuss this with Mariya when creating the AC's. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85ad03fe14a6b94f19d169e01f33cc007d36002e/new-1.png" alt="new-1.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50c80fc38dccdeb568f060758bd0505fba67aa88/new-2.png" alt="new-2.png" />

## Steps to reproduce

1. Search for a page on the main dashboard. 
2. Go to the Entity dashboard screen for that page
3. Scroll down to the session and engagement rate fields and see new badge with tooltip. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There is no `New` badges on the entity dashboard for Analytics metrics.

## Implementation Brief

* [ ] In `assets/js/modules/analytics-4/components/dashboard/DashboardOverallPageMetricsWidgetGA4.js`
  * Remove the badges object and it's usage https://github.com/google/site-kit-wp/blob/8e4cfd5ae257a47dd2eea2dfaeb400f25c9bd280/assets/js/modules/analytics-4/components/dashboard/DashboardOverallPageMetricsWidgetGA4.js#L204
* [ ] Update `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/index.js`
  * Remove the badge prop https://github.com/google/site-kit-wp/blob/8e4cfd5ae257a47dd2eea2dfaeb400f25c9bd280/assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/Overview/index.js#L299  

### Test Coverage

* Update any failing VRT images

## QA Brief

* Follow the `Steps to reproduce` points and ensure that there is no `New` badge on the entity dashboard for Analytics metrics.

## Changelog entry

* Remove "New" badges from Analytics widgets in the entity dashboard.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
Just noticed it is for Team M, picked it by miskate
