### ISSUE TITLE
Creating new container during Tag Manager setup is not saved

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#821]
Addressed by PR #824 

## Bug Description

When setting up Tag Manager, if you choose "Create a new container" from the dropdown and continue with setup, you see the setup success page. However, when going to the settings and viewing Tag Manager, it shows "continue module setup".

When continuing setup, you see the newly created container. At this point you can select it and save to complete the setup.

## Steps to reproduce

1. Set up Tag Manager
1. Choose "Set up a new container" from the container dropdown
1. Click continue
1. Go to settings > Tag Manager
1. See "continue module setup" (created container was not saved)

## Additional Context

This is due to old logic in the `POST settings` datapoint which tries to assign the created container ID to the request `$data` object before assigning to the option. This fails since this variable is no longer an array but an immutable data object.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A newly created Tag Manager container should be properly saved.
* Afterwards, the module setup should show as completed when going to settings, and the GTM snippet be placed in the frontend.

## Implementation Brief

* This issue is fixed in #470 where it was discovered

## Changelog entry

* Ensure that a newly created Tag Manager container is properly saved so that the module setup is completed.

**Comment by cole10up** [comment]
**Tested**

Confirmed selecting 'Set up a new container' creates a container using your site's name as the container name.
![image](https://user-images.githubusercontent.com/57115907/69195499-ad9e3480-0ae0-11ea-8973-ccb75c8c28d4.png)

One thing to note - if you try to use the same link again it will error as I'm assuming it is trying to create another container with the same name.
![image](https://user-images.githubusercontent.com/57115907/69195547-cc9cc680-0ae0-11ea-98e5-78e9f327ba43.png)

Passed QA ✅
