### ISSUE TITLE
Recommendations are no longer appearing on the Pagespeed Insights widget

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8217]
## Bug Description

Recommendations are no longer appearing on the Pagespeed Insights widget.

This is due to a change to the relevant Lighthouse audits returned by the PSI API. The audits have had their `scoreDisplayMode` value updated to the newly introduced `metricSavings` scoring mode.

Additionally, the audits' `score` value has changed as follows:

> - Set score to 1 if the provided audit product score is passing (>= 0.9)
> - Else Set score to 0 if the provided audit product had nonzero savings for any metric
> - Else set score to 0.5 for the case of a failing audit that does not have any savings

These changes were introduced via this PR to the `lighthouse` repo: https://github.com/GoogleChrome/lighthouse/pull/15447.

As discussed in the PR, audits with a score of `0` have a higher impact so we should consider displaying these above the audits with a score of `0.5`.

Note that I've verified that all of the audit types in the [`wordpress` stack pack](https://github.com/GoogleChrome/lighthouse-stack-packs/blob/a01caf73e0e2d492706385af00f34df77c08eaa7/packs/wordpress.js) have been updated to the new scoring mode.

## Steps to reproduce

1. Open the dashboard on a site where recommendations are expected to be displayed on the Pagespeed Insights widget.
2. Scroll to the Pagespeed Insights widget and click on **How to improve**.
3. See the "No recommendations" message in the widget.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/18395600/7594a5dd-30eb-4a52-9200-3cf5a50d620e)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: Spotted on 1.119.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Relevant recommendations should be displayed in the Pagespeed Insights widget.
  * Specifically that means the `audit` objects in the PSI API response that are in the `wordpress` stack pack and have a score less than `1`.
* Additionally, the recommendations should be ordered according to their `score`:
  * Audits with a higher impact should be displayed first.
  * Specifically that means audits with the score `0` should be displayed above audits with the score `0.5`.
  * The secondary order should be the order returned by the API.

## Implementation Brief

* [ ] Update the conditions for including an `audit` as follows:
  * `scoreDisplayMode` should be `'metricSavings'` (we can remove the references to `'numeric'` and `'binary'`).
  * `score` should be less than `1` (or `!==` should also be fine).
https://github.com/google/site-kit-wp/blob/5913a7fde140271d2ad64b02a5c34505d97e59a2/assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js#L240-L242
* [ ] Additionally, sort the audits by `score` in ascending order.

### Test Coverage

* Fix any failing tests.

## QA Brief

- Follow the "Steps to reproduce" in the issue description and verify that you can now see recommendations ("How to improve" tab content) in the PSI widget.
- Run the following script in the browser console:
```js
const referenceURL = googlesitekit.data.select( 'core/site' ).getCurrentReferenceURL();
const strategy = googlesitekit.data.select( 'core/ui' ).getValue( 'dashboardPageSpeedWidgetStrategy' ) || 'mobile';
googlesitekit.data.select( 'modules/pagespeed-insights' ).getAuditsWithStackPack( referenceURL, strategy, 'wordpress' );
```
- This should print an object of all the audits for your site. Compare this list of audits with the recommendations appearing in your PSI widget's "How to improve" tab. Verify that:
  - Recommendations only show audits that have a `scoreDisplayMode` of `metricSavings`.
  - Recommendations only show audits that have a `score` of less than 1.
  - Recommendations are in ascending order, i.e. lower scores (e.g. `0`) appear before higher scores (e.g. `0.5`).
  - For same scores, the recommendations appear in an alphabetic order of the audit `id`.

## Changelog entry

* Ensure that recommendations display correctly on the Pagespeed Insights widget.

**Comment by aaemnnosttv** [comment]
✅ AC + IB

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit I have an observation but I am unsure if its user error 😄 

The descriptions in the objects don't match what I see as a description in the audit. 

i.e. for `Serve images in next-gen formats` this appears as the description "Image formats like WebP and AVIF often provide better compression than PNG or JPEG, which means faster downloads and less data consumption. [Learn more about modern image formats](https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images/)." but I see `Consider using the [Performance Lab](https://wordpress.org/plugins/performance-lab/) plugin to automatically convert your uploaded JPEG images into WebP, wherever supported.`

![image](https://github.com/google/site-kit-wp/assets/73545194/1438f2fb-2c81-4610-8051-b7ee88cb1ffc)

**Comment by nfmohit** [comment]
Hi @wpdarren. This is expected because the description inside the audit isn't sourced from the description in this object. The description inside the object is a generic description for the audit, however, the PSI API also provide "stack" specific descriptions, and stack in our case is "WordPress".

If you run the following in your browser console for a specific audit ID, you will receive the stack specific description:

```js
const referenceURL = googlesitekit.data.select( 'core/site' ).getCurrentReferenceURL();
const strategy = googlesitekit.data.select( 'core/ui' ).getValue( 'dashboardPageSpeedWidgetStrategy' ) || 'mobile';
googlesitekit.data.select( 'modules/pagespeed-insights' ).getStackPackDescription( referenceURL, strategy, 'modern-image-formats', 'wordpress' );
```

You can also try changing `modern-image-formats` in the last line of the script to any other audit ID from the original object in the QAB.

I hope that is clear. Back to you, thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified that I can now see recommendations ("How to improve" tab content) in the PSI widget.
- Verified that:
  - Recommendations only show audits that have a scoreDisplayMode of metricSavings.
  - Recommendations only show audits that have a score of less than 1.
  - Recommendations are in ascending order, i.e. lower scores (e.g. 0) appear before higher scores (e.g. 0.5).
  - For same scores, the recommendations appear in an alphabetic order of the audit id.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/dc651d5c-4b27-49a0-8d88-e6cb1466bfab)
![image](https://github.com/google/site-kit-wp/assets/73545194/3f4a635e-896b-4aba-83f0-0a6f394f5510)
![image](https://github.com/google/site-kit-wp/assets/73545194/e29cddcc-9f90-41a9-90ee-e1862e276652)
![image](https://github.com/google/site-kit-wp/assets/73545194/fc864fc2-999b-42d2-b3b7-fc2b35fe6718)
![image](https://github.com/google/site-kit-wp/assets/73545194/1c644698-a71b-46ab-9e39-55410c98aeb1)

</details>
