### ISSUE TITLE
Improve setup flow reliability by eliminating the REST API callback

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#822]
## Feature Description

Improve setup flow reliability by eliminating the REST API callback made by the proxy to provide the authorization token.

#### Description
During the current setup flow for a website when installing Site Kit, the proxy service makes a nonce-authorized REST API request back to the site to pass back the OAuth credentials (ref: https://github.com/google/site-kit-wp/blob/develop/includes/Core/REST_API/REST_Routes.php#L468-L510). This may fail if the user or host has blocked external REST API requests. In addition, the credentials may be transmitted over an insecure connection.

#### Current Flow
1. User starts OAuth flow as usual.
2. User is redirected to proxy.
3. Proxy makes authorized REST API (POST) request to send the OAuth credentials.

#### Current Issues
* The REST API may be closed or blocked from external requests by hosts or security plugins.
* REST request may not work over `https`, proxy will fall back to `http`, meaning keys are communicated insecurely.

### New Flow
1. User starts OAuth flow as usual.
2. User is redirected to proxy.
3. Proxy stores domain plus credentials and a short lived proxy verification key, redirecting back to plugin with key as query variable.
3. Plugin adds proxy verification key to site header as a meta tag, using same approach as Search Console site verification tag.
4. Plugin makes secure request to proxy for credentials.
5. Proxy loads site over normal web request, verifying that the proxy verification key is present on site/domain.
6. If successful, proxy returns the OAuth credentials to plugin's request. 
7. Proxy verification key can be discarded, it is only used to verify the site requesting the credentials.

#### Additional details
* Very short life: the `short lived proxy verification key` is only valid for a short period, maybe 5 or 15 seconds.
* Meta tag also time limited: the plugin would only display the meta verification tag for a short period as well, maybe 15-30 seconds: we can add a timestamp data point and after that the key would not be added (and we would clean up any stored data).

#### Advantages
* No longer requires authorized REST API request back to site, only regular web access. Associated REST route can also be removed.
* More resilient to being blocked, response only vs. relying on REST API request.
* Ensures OAuth credentials are transmitted via https.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Thanks @adamsilverstein for opening this. I've thought about an alternative to the REST API request too for quite a while, but with every path I've though through so far, I've ended up in a place where there was a security flaw.

Something like what you're describing was among those ideas, but the potential issue I see here is the following:
> Plugin makes secure request to proxy for credentials.
While the verification code exists on the site, any other site could make the same request to get that site's credentials, unless I'm missing something in your description.

The time window for this would be short, but at the same time, if any error occurs and the token is not removed from the site, it would lead to a bigger problem.

Let's continue thinking and discussing about an alternative approach to the REST request here. For now we'll try to resolve as many issues as we can in the existing setup (just got one more thing fixed today) - but whatever we do, sites blocking incoming REST requests or external POST requests in general would still be unable to succeed with this model. We just need to be 100% sure to not threaten security with a potential alternative.

**Comment by adamsilverstein** [comment]
Good points, and maybe this is a small enough problem that we don't need to change anything. Can we tell how frequently this happens (or would adding a tracking event for opted in users help)?  I absolutely would want careful security review of this proposed change! Given the points about https its possible this could be a security improvement.

In regards to failed request, my idea to mitigate vulnerabilities here are:
* Very short life: the `short lived proxy verification key` is only valid for a short period, maybe 5 or 15 seconds.
* Meta tag also time limited: the plugin would only display the meta verification tag for a short period as well, maybe 15-30 seconds: we can add a timestamp data point and after that the key would not be added (and we would clean up any stored data).

Adding these points to the description above.

**Comment by felixarntz** [comment]
We came to a solution that is somewhat along these lines, but ties in with the Site Verification API. #905 is the issue to track the plugin changes required.
