### ISSUE TITLE
Create new `Ads` module PHP base class

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8222]
## Feature Description

The Ads module requires the addition of applicable PHP classes to the current codebase, within a new ads namespace. The first of this PHP class creation involves creation of the base `Ads` class within `includes/Modules`. This should follow the same design pattern as all other module base classes. 

The base Ads class should be registered as a module within `includes/Core/Modules/Modules.php` only if the `adsModule` feature flag is present and enabled.

See relevant section in design doc: https://docs.google.com/document/d/1APuSv95bf62uhzlaFlW6jPrzPKy1avpRYd9W1MSAAJo/edit?resourcekey=0-UuynlcUz9CoubgldR6Z5sg#heading=h.8bapw1nwueej 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Definition of a new Ads.php module entrypoint file at includes/Modules/Ads.php. See the design doc:  https://docs.google.com/document/d/1APuSv95bf62uhzlaFlW6jPrzPKy1avpRYd9W1MSAAJo/edit?resourcekey=0-UuynlcUz9CoubgldR6Z5sg#heading=h.8bapw1nwueej 

- Class should be referenced as class `Ads` in an applicable namespace
- Class should be extend the `Module` parent class
- Class should implement abstract methods from the `Module` parent class
- The `setup_info` method should be implemented as a protected method and contain setup information applicable to the module, such key value pairs may be as follows:
    - slug: ads
    - name: Ads
    - description: Track conversions for your existing Google Ads campaigns.
    - order: 1
    - homepage: https://google.com/ads 
- The class/module is to be registered within the Modules class at `includes/Core/Modules/Modules.php`, and only if the `adsModule` feature flag is present and enabled.

## Implementation Brief

* [ ] Add `Google\Site_Kit\Modules\Ads` class
  * You can borrow the logic from `Search_Console` module
  * Follow the guidelines outlined in AC
  * Use details from AC for `setup_info` method
  * Use `ads` for `MODULE_SLUG`
  * We won't need scope related methods and logic, or data availability, etc.
* [ ] Update `Google\Site_Kit\Core\Modules/Modules::construct`
  * Include `Ads` module, hidden behind the `adsModule` feature flag, to the `$core_modules` array, like this: https://github.com/google/site-kit-wp/blob/74ca48ba71eb8bd91af1a2d957d8d11c0d4f7696/includes/Core/Modules/Modules.php#L181
    * It might be out of scope, but it is a tiny edit, we can move the `Analytics_4` module from referenced line directly to the the class property `$core_modules` array above

### Test Coverage

* Add tests for `Ads` class

### QA:Eng
* Verify that module necessary code is there, and tests are passing

## Changelog entry

* Add a new module class for the Ads module.

**Comment by eugene-manuilov** [comment]
@10upsimon we also need to register the new module. It should be added as a new core module in the `includes/Core/Modules/Modules.php` file if the feature flag is enabled.

**Comment by 10upsimon** [comment]
@eugene-manuilov I updated this to reflect the registration in the base Modules class, only if and when the adsModule feature flag is present, back to you for re-review.

**Comment by eugene-manuilov** [comment]
> I updated this to reflect the registration in the base Modules class, only if and when the adsModule feature flag is present, back to you for re-review.

Thanks, @10upsimon. That looks good to me.

> * The logic surrounding the base class and its settings equivalent can largely be borrowed and implemented from a simpler module class, such as those defined within the `Search_Console` module base and settings classes as found at `includes/Modules/Search_Console.php`.

This one is probably not needed. Or if it is needed can you explain what exactly we should borrow from that class? My understanding is that just creating a new module class (implementing abstract methods from the parent class) and registering it in Modules is already sufficient for the current ticket. Everything else will be added in further tasks.

If you agree with this, then let's remove this point then.

**Comment by eugene-manuilov** [comment]
Thanks, @10upsimon. AC ✔️

**Comment by zutigrm** [comment]
Hi @10upsimon , in the design doc, under `Site Health` it is mentioned that this module will include:

> An indication of whether the Ads Conversion ID script is being rendered/output on the site

I haven't seen a separate issue that is planned for this, but since we included infrastructure for this in #5695, it can be implemented with some additional scope, like adding `Tag_Matchers`, implementing proper trait, and listing this module to the active modules with tags, etc. Should I include that as part of this issue, or is it out of scope for it, and we should create a separate issue for this?

**Comment by 10upsimon** [comment]
Good callout @zutigrm, I need to add this as an issue in the design doc. A separate issue is fine for this, I'll define it once I've added it to the design doc.

**Comment by zutigrm** [comment]
Waiting for `description` text to be added, to continue with IB

**Comment by 10upsimon** [comment]
@zutigrm I've updated the `description` key in the issue description as well as in the design doc.

```
Track conversions for your existing Google Ads campaigns.
```

**Comment by eugene-manuilov** [comment]
> * Include `get_debug_fields` which should output `adsConversionID` if present

@zutigrm, it will be implemented as part of the #8245 task. No need to add it here.

> It will need `is_connected` and `on_deactivation` methods, they can be borrowed from Analytics module, for example.
> * To check connection status, use `adsConversionID` setting
> * On deactivation delete the option name `googlesitekit_ads_settings`

This relies on the module settings that will be implemented in #8223. So, these methods are not needed in this ticket.

**Comment by zutigrm** [comment]
Thanks @eugene-manuilov . IB updated

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
Getting this one, as it is needed for the #8222, will get this one in, in order to wrap #8222
cc: @bethanylang @ivonac4

**Comment by tofumatt** [comment]
Note for @zutigrm @hussain-t in the future: QA: Eng briefs that request another inspection of the code aren't necessary, it's okay to mark an issue like this as not needing any explicit QA and one that can be moved directly to Approval. Especially when it's going through merge review as well, it's fine to just say "No QA needed." 😄 

Unless there was a particular aspect of the code/behaviour that warrants inspection, but then it should be highlighted 🙂

Moving this to Approval since no QA is needed 👍🏻
