### ISSUE TITLE
Create new `Ads` module codebase structure in `assets/js/modules`

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8225]
## Feature Description

A new standalone module is required to be introduced to the Google Site Kit plugin. This module should follow the design patterns of existing modules that can currently be found in the `assets/js/modules` directory within the existing code base. Said new module should be named `ads`, and should reside within a newly created directory at `assets/js/modules/ads`. Where applicable, the `adsModule` feature flag should be used to gate module functionality and presence/visibility. See issue #8197 for more context.

Initially, during this phase, this module will not have any dashboard facing views.

See the applicable section(s) within the Ads Module design document: https://docs.google.com/document/d/1APuSv95bf62uhzlaFlW6jPrzPKy1avpRYd9W1MSAAJo/edit?resourcekey=0-UuynlcUz9CoubgldR6Z5sg#heading=h.9pk2w04qgbdj 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Ads` module should be present within the Site Kit application, gated by way of the recently added `adsModule` feature flag see issue #8197.
* Implementation of a module entrypoint file (`index.js`) at `assets/js/modules/ads/index.js` is to be implemented, and is to follow necessary logical patterns relative to module data store(s), settings views/components etc. This module should follow the same pattern as other simpler modules, such as the `search-console` module, which can be used as a guideline for basic base implementation.
* An applicable `ads` module store should be associated with the `Ads` module. **_Ads store creation is a separate GH issue, see (TBA)._**
* An applicable component for settings editing within the plugin settings area of said ads module should be defined, i.e a `SettingsEditComponent`, and should follow the design patterns of existing modules.
* An applicable component for module settings viewing within the plugin settings area of said ads module should be defined, i.e `SettingsViewComponent`, and should follow the design patterns of existing modules.
* An applicable form component required to edit settings should be defined, ie `SettingsFormComponent`, and should follow the design patterns of existing modules.
* An applicable `Ads` icon should be created (see [Figma](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=0-1&mode=design&t=FYdC262kiBVZDYWV-0)) for use within the module scaffolding, as and where needed.
* Module assets should be defined in the applicable `Ads` module class by way of a `setup_assets()` method, for reference see other areas of the codebase, such as:

https://github.com/google/site-kit-wp/blob/74ca48ba71eb8bd91af1a2d957d8d11c0d4f7696/includes/Modules/Tag_Manager.php#L517-L546

* The base `Ads` module PHP class should be updated (if not already) to implement the `Module_With_Assets` interface
* The base `Ads` module PHP class should be updated (if not already) to use the `Module_With_Assets_Trait` trait
    * See base module PHP issue at #8222 to ascertain if interface and trait have been implemented, or add if necessary
* A module entry point file at `assets/js/googlesitekit-modules-ads.js` should be created, following the same pattern as existing modules
    * Said entry point file should be included in the Webpack config file at `./webpack.config.js` via the module config file at `./webpack/modules.config.js`

## Implementation Brief

* [x] Add `assets/js/modules/ads/datastore/constants`
  * [x] Include a new datastore constant `MODULES_ADS`
* [x] Add `assets/js/modules/ads/index.js`:
  * Use `assets/js/modules/search-console/index.js` as a starting point to borrow the core logic from
  * [x] Register `Ads` module, wrapped under `adsModule` feature flag. 
  * [x] You can extract the icon from [figma](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1-100&mode=design&t=6sliKpUV5bpP1KWp-0)
  * [x] You can omit widget registration logic, as module does not include a widget area/widgets
* [x] Add `assets/js/modules/ads/datastore/index.js`
  * [x] Use `assets/js/modules/search-console/datastore/index.js` as starting point
  * [x] For `store` use initially a placeholder object, with properties like `initialState: {}, actions: {}` etc. These will be handled/added in other issue
* [x] Add `assets/js/modules/ads/components/settings/SettingsEdit.js`
  * Use `assets/js/modules/search-console/components/settings/SettingsEdit.js` as starting point
  * [x] Keep `hasSearchConsoleAccess`, `isDoingSubmitChanges` and `viewComponent` component rendering logic
  * [x] Render the main `div` wrapper with class `googlesitekit-setup-module googlesitekit-setup-module--ads`
* [x] Add `assets/js/modules/ads/components/settings/SettingsForm.js`
  * Use `assets/js/modules/search-console/components/settings/SettingsForm.js` as a starting point to get the basic logic from
  * [x] Use the `getModule` selector on `CORE_MODULES` to retrieve `ads` module
  * [x] Render main div wrapper with class `googlesitekit-ads-settings-fields`
  * [x] Include the `StoreErrorNotices` component
* [x] Update `Google\Site_Kit\Modules\Ads` class:
  * [x] Follow the guidelines from AC, regarding the `setup_assets` method, interfaces, etc
* [x] Add `assets/js/googlesitekit-modules-ads.js` file
  * [x] Adapt it from `assets/js/googlesitekit-modules-search-console.js`
* [x] Update `webpack/modules.config.js`:
  * [ ] Add `googlesitekit-modules-ads` to the list pointing to the previously added file `assets/js/googlesitekit-modules-ads.js`. You can follow an example here https://github.com/google/site-kit-wp/blob/ab9d76bebe8a3368eaf73b194edf941fd42f2ec5/webpack/modules.config.js#L77-L78

### Test Coverage

* Since datastore is not implemented yet, no tests are applicable to be added. Update any failing test, if any - like the one in `assets/js/modules/index.test.js`

## QA Brief

* Setup site kit without any feature flag
* Go to Settings -> Connect more services
* Verify that `Ads` module is not on the list
* Enable `adsModule` feature flag
* Go back to the Connect more services
* Verify `Ads` module is present with proper icon and description
* NOTE: There is no other functionality integrated with this module yet

## Changelog entry

* Scaffold foundational client-side infrastructure for the Ads module.

**Comment by eugene-manuilov** [comment]
@10upsimon one thing that is missing in AC is that we need to create the `assets/js/googlesitekit-modules-ads.js` file similarly to other module files and include it into the webpack config.

**Comment by 10upsimon** [comment]
@eugene-manuilov I've updated AC to include mention of a new `assets/js/googlesitekit-modules-ads.js` and inclusion into the `./webpack.config.js` file via the existing `./webpack/modules.config.js` module config file.

**Comment by eugene-manuilov** [comment]
Thanks, @10upsimon. This almost looks good to me. The only thing that I forgot about in my original comment is that we need to update the Ads module class to set up assets the same way how we do it in other modules. For example: https://github.com/google/site-kit-wp/blob/74ca48ba71eb8bd91af1a2d957d8d11c0d4f7696/includes/Modules/Tag_Manager.php#L517-L546

It also means that we need to update the Ads module class to implement the `Module_With_Assets` interface and to use the https://github.com/google/site-kit-wp/blob/74ca48ba71eb8bd91af1a2d957d8d11c0d4f7696/includes/Modules/Tag_Manager.php#L60-L61
https://github.com/google/site-kit-wp/blob/74ca48ba71eb8bd91af1a2d957d8d11c0d4f7696/includes/Modules/Tag_Manager.php#L63-L63

**Comment by 10upsimon** [comment]
@eugene-manuilov back to you for ACR, thank you

**Comment by eugene-manuilov** [comment]
Thanks, @10upsimon. AC ✔️

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@zutigrm When I enable the `adsModule` feature flag, the Ads module appears in settings but without a logo. 

![image](https://github.com/google/site-kit-wp/assets/73545194/7b0689fd-6fc4-4d0f-83d3-e0667d0c388e)

I tested this on a fresh new site.  

Also, since the description is a single sentence, then, we shouldn't have a period in the end like the other modules, i.e. Tag Manager.  I realize it has one on the Figma designs though,

**Comment by zutigrm** [comment]
@wpdarren Thank you for your observations. It seems the assets trait got lost in one of the previous conflict syncs. I sent the follow up. Also removed the dot from description

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Ads module is not on the list when the `adsModule` feature flag is not enabled. 
- The Ads module has the icon and description when enabled by the `adsModule` feature flag. 
- When I tried to set up the Ads module, and went to the Connected tab, the icon appears as expected. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/d2411868-076e-48b2-b018-8f7e00414073)
![image](https://github.com/google/site-kit-wp/assets/73545194/07c372c5-ae19-46a3-bf4f-29e5ad6ee0de)
![image](https://github.com/google/site-kit-wp/assets/73545194/ef2fa1df-dfda-4d43-a940-3aeb67117c8f)

</details>
