### ISSUE TITLE
Create new `Ads` datastore within `Ads` module

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8226]
## Feature Description

Implementation of the necessary datastore elements related to the new `Ads` module will be required in order for data to be saved and retrieved from a store relative to the `Ads` module. Issue #8225, which carries out the bulk of the `Ads` module scaffolding, should set the groundwork for the `Ads` datastore to be completed and integrated into the `Ads` module.

See the applicable section within the Ads Module design document: https://docs.google.com/document/d/1APuSv95bf62uhzlaFlW6jPrzPKy1avpRYd9W1MSAAJo/edit?resourcekey=0-UuynlcUz9CoubgldR6Z5sg#heading=h.8mg2nq9g5v51

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Ads datastore should be created in `assets/js/modules/ads/datastore/`, following our standard conventions and as outlined in the design doc.
- The store should provide the `adsConversionID` setting, along with the standard actions and selectors that are generated by the settings store creator.
- `adsConversionID` should be defined as an owned setting.

## Implementation Brief

* [x] Add `assets/js/modules/ads/datastore/base.js`
  * Use `assets/js/modules/search-console/datastore/base.js` as starting point
  * Add `adsConversionID` under `ownedSettingsSlugs` and `settingSlugs`
* [x] Add `assets/js/modules/ads/datastore/settings.js`
  * Use `assets/js/modules/search-console/datastore/settings.js` as starting point
  *  Since `adsConversionID` can be saved as empty value, no specific validation is defined, so `validateCanSubmitChanges` can just return true always
* [x] Update `assets/js/modules/ads/datastore/index.js`
  * Import the `baseModuleStore` and add it to the datastore partial
  *  You can see an example in `assets/js/modules/search-console/datastore/index.js`

### Test Coverage

* Add `base`, `index` and `settings` store js tests

## QA Brief

There is no additional testable UI since #8225.
* Setup Site Kit and enable `adsModule` feature flag
* Go back to the "Connect more services" section of the settings
* Verify `Ads` module is present with proper icon and description

## Changelog entry

* Add the initial datastore implementation for the Ads module.

**Comment by techanvil** [comment]
Hey @10upsimon, I think the AC here goes into a bit more detail than needed in some areas and not quite enough in others. It's currently a bit IB-like, although it is missing a bit of detail around the initial shape of the datastore API (settings/actions/selectors). I think in terms of the AC it would be good to define what sort of interface we expect to come out of this.

Maybe I'm missing something but I don't see another issue specifying that the `adsConversionID` setting is to be added on the client-side, so it seems like this would be the place to do that. With that in mind, I'd keep it short and sweet, along these lines (maybe going into a little more detail on the actions and selectors, although I don't think it's essential).

- The Ads datastore should be created in `assets/js/modules/ads/datastore/`, following our standard conventions and as outlined in the design doc.
- The store should provide the `adsConversionID` setting, along with the standard actions and selectors that are generated by the settings store creator.
- `adsConversionID` should be defined as an owned setting.

How does that sound to you?

**Comment by 10upsimon** [comment]
Thanks @techanvil, I think I went a little off course with how I implement the AC portion based on some of the prior issues being more IB like in this regard, you are indeed correct. Updating now.

**Comment by 10upsimon** [comment]
@techanvil I believe your summary covers it all in a very simplified manner, thank you, back with you for ACR.

**Comment by techanvil** [comment]
Top stuff, thanks @10upsimon. If you're happy with the AC then it LGTM. :white_check_mark:

**Comment by tofumatt** [comment]
IB ✅

**Comment by benbowler** [comment]
Note, this ticket will need to be rebased onto develop [once the missing icon has been added](https://github.com/google/site-kit-wp/issues/8225#issuecomment-1972155750) in ticket #8225 .

**Comment by wpdarren** [comment]
@benbowler since I have already tested 8225 and there is no additional testing on this ticket according to the QAB, are you happy for me to put this into approval, or, should I add the `QA:Eng` label on to check the AC's?

**Comment by benbowler** [comment]
Hey @wpdarren, yes you can put this through to approval thanks.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

The QAB details the same tests as completed on 8225 so I have moved this to approval.

**Comment by aaemnnosttv** [comment]
@zutigrm @tofumatt this issue [added a test suite for the datastore index](https://github.com/google/site-kit-wp/blob/0c6c86498887ce4c8834982c9af70dd7661bb1ca/assets/js/modules/ads/datastore/index.test.js) which is redundant and not something that we do in other modules AFAIK. This is because the way that we test the partial stores (and really anywhere we use `createTestRegistry`) involves registering the full store, so if it wasn't being registered all the other tests for it would fail. It's a minor addition, but just wanted to note and we can probably remove it in a future PR.

We have several examples to follow for foundational module infrastructure so let's make sure to scrutinize deviations from those existing conventions and try to keep things consistent across all when we do want to make changes there.

**Comment by benbowler** [comment]
@aaemnnosttv this test suite for the datastore index was modelled on the search console module so, if removed, the search console datastore index test should also be removed.
