### ISSUE TITLE
Add the Audience Tile Error (Storybook)

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8228]
## Feature Description

Create the Audience Tile Error component and add it to Storybook.

See [audience tiles > error states](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.b9x8clic313y) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Audience Tile Error component should be created and stories for it added to Storybook.
* It should be implemented according to the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1396-25492&mode=design&t=pZb8rxvl8TTJRpD6-0).
* The component should accept a list of errors as a prop.
  * If any of the errors is a permissions error, the "insufficient permissions" variant of the error notice will be shown (as mentioned in the [design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.b9x8clic313y), including a _Get help_ link and a **Request access** buttons.
    * Its _Get help_ link will open the [Analytics insufficient permissions support document](https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/#insufficient-permissions).
    * The **Request access** button will open the URL for the connected web data stream in the Analytics UI, allowing the user to request access.
  * Otherwise, the catch-all variant will be shown which just includes the **Retry** button.
    * Clicking the **Retry** button will retry whatever triggered the errors (i.e. it will invalidate the resolution for the selector associated with the errors).

## Implementation Brief

* [x] Add a new component `/assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceTile/AudienceTileError.js` with the prop `errors`, an array of errors.
    * [x] Add a function to check if any of the errors are insufficient permissions errors, `hasInsufficientPermissionsError`, as implemented for widget errors:
    * https://github.com/google/site-kit-wp/blob/6f01a837c2e815989235b1aabb0101f5b5ae3bb3/assets/js/components/ReportError.js#L103-L105
    * [x] If `hasInsufficientPermissionsError` is true:
       * [x] Render a *Get help* link linking to `https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/#insufficient-permissions`
       * [x] Render a *Request access* button, which links to the `serviceEntityAccessURL`, resolved using the `getServiceEntityAccessURL` selector:
       * https://github.com/google/site-kit-wp/blob/6f01a837c2e815989235b1aabb0101f5b5ae3bb3/assets/js/components/ReportErrorActions.js#L57-L61
    * [x] If `hasInsufficientPermissionsError` is false, render a single *Retry* button which, when clicked, calls a retryErrors function as implemented for widget errors:
    * https://github.com/google/site-kit-wp/blob/6f01a837c2e815989235b1aabb0101f5b5ae3bb3/assets/js/components/ReportErrorActions.js#L103-L113

 * [x] Add `assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-audience-segmentation-tile-error.scss` and apply the styles to match the Figma designs in the AC.

### Test Coverage

* Add `AudienceTileError` tests and stories.

## QA Brief

* [View the storybooks for AudienceTileError](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencetileerror--default), confirm they match designs and AC. *Note: the Get Help link on the insufficient permissions story does not link to the full URL in the AC within the storybooks but will in use in the dashboard.*

## Changelog entry

* Add an error state for the Audience tile component.

**Comment by tofumatt** [comment]
Looks good to me 👍🏻 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

Tested on [Storybook Story.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencetileerror--default)

@benbowler In Figma text font family is 'Google Sans Text' and under Storybook Font Family is 'Google Sans Display'. 


<details>

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/e1ddf0e4-914c-46d1-ade7-4a8e8a3795dd)

Storybook-

![image](https://github.com/google/site-kit-wp/assets/94359491/d4c046a1-83fd-4b97-830b-65ef6ef8693a)

![image](https://github.com/google/site-kit-wp/assets/94359491/3e0b486b-6665-4224-b7f1-ddc525395eeb)

![image](https://github.com/google/site-kit-wp/assets/94359491/939cf584-39e0-47a5-ba07-d05d71da16ba)

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on [Storybook Story.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencetileerror--default)
- Verified that text font family is now updated to 'Google Sans Text' as per Figma.
- Verified storybook story with Figma design.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/de0c56c7-0c74-44d7-9600-607ef792508a)

![image](https://github.com/google/site-kit-wp/assets/94359491/910ebcf8-62c8-4b1d-bf82-db35d9b0fbb7)

![image](https://github.com/google/site-kit-wp/assets/94359491/579c6f86-f29c-427f-941f-4530335daef6)

![image](https://github.com/google/site-kit-wp/assets/94359491/d3b5352d-a5f9-4d11-bc07-69984e363941)

![image](https://github.com/google/site-kit-wp/assets/94359491/a8275c85-3885-4b86-8793-123f0fddb27b)

![image](https://github.com/google/site-kit-wp/assets/94359491/51a38e11-f0e2-47bb-bf32-8fceb405372d)

</details>
