### ISSUE TITLE
The Enable Auto Updates banner can momentarily flash on page load.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8235]
## Bug Description

The Enable Auto Updates banner can momentarily flash on page load. See video below.

Note that this might be a glitch that only occurs for a local development environment, and needs some further investigation.

## Steps to reproduce

This was reproducible following these steps. However, it only occurred on my local development environment, I tried on a TasteWP site and the Enable Auto Updates banner stayed visible. Therefore, it would be useful to check if this occurs for other developers and whether it points to an issue that is exclusive to the local environment, or a wider issue.

1. Site up Site Kit and connect Analytics.
2. Disconnect Analytics.
3. See the Enable Auto Updates banner momentarily flash on loading the desktop.

Update: As per @jimmymadon's [comment](https://github.com/google/site-kit-wp/issues/8235#issuecomment-1934639529) below this is reproducible, at least on a local development environment. Note Jimmy's additional requirement to reproduce this: deleting the `auto_update_plugins` field from the database.

## Screenshots

https://github.com/google/site-kit-wp/assets/18395600/89fb6695-d850-4da9-a984-bac7a334f423

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: any
 - Device: Spotted on 1.119.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Enable Auto Updates banner should not momentarily flash on page load.

## Implementation Brief

* [ ] Update this condition in `EnableAutoUpdateBannerNotification` to check for `isDismissed !== false`, ensuring that the widget will render `null` while `isDismissed` is still loading (i.e. while it's `undefined`).

https://github.com/google/site-kit-wp/blob/cc9f305aa736d7509e303ead63c37f089b21b221/assets/js/components/notifications/EnableAutoUpdateBannerNotification/index.js#L144-L146

### Test Coverage

* Update any failing tests.

## QA Brief

This task is a bit hard to test as the issue is caused by a race condition and only happens if the API endpoints load super fast, which is only the case on local.

* Ensure you have autoupdate disables
* With admin role, go to dashboard
* Verify the auto update banner shows up.
* Dismiss the auto update banner.
* Reload the page multiple times and verify the auto update banner does not flash up. Compare to this video https://github.com/google/site-kit-wp/issues/8235#issuecomment-1934671119
* Verify the 

## Changelog entry

* Fix bug that could cause the "Enable automatic updates" banner to appear then disappear briefly when the user has a slow internet connection.

**Comment by techanvil** [comment]
Cool, thanks for checking this @jimmymadon! With this being reproducible, I've updated the issue with AC and moved it to IB.

**Comment by zutigrm** [comment]
Unassigning myself, in order not to hold it, as I didn't get a chance to explore it yet, and in favour of another `P0` issue with higher priority so I can move that one faster

**Comment by techanvil** [comment]
Hi @zutigrm, I just gave it a try and am still able to reproduce it on my local dev environment. Tested and reproduced in Chrome on both Mac and Linux.

**Comment by zutigrm** [comment]
I am unassigning myself so someone else who can reproduce it can debug it. I can't replicate it on my end

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by derweili** [comment]
This issue is caused by a race condition.
This happens only if the `isDismissed` is still loading while `hasUpdatePluginCapacity`, `hasChangePluginAutoUpdatesCapacity` and `siteKitAutoUpdatesEnabled` are resolved.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev and main environment.
- I'm able to reproduce issue on latest environment.
- Verified on dev and main environment flicker issue is now not reproducible.

<details>

Latest -


https://github.com/google/site-kit-wp/assets/94359491/5f375bf0-9c25-48fb-bc14-507c2133ccc7

Dev -


https://github.com/google/site-kit-wp/assets/94359491/92a4f01f-4ffe-49e6-90bc-e5e86cdf961c

</details.
