### ISSUE TITLE
Add external link Icon to Ad Blocking Recovery CTA in AdSense settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8246]
## Bug Description

On the `Learn more` link for the Ad Blocking Recovery CTA within AdSense settings, the external link icon does not appear. After discussing this with Sigal, we should add this icon since the link opens up in a new window to an external page. 

![image](https://github.com/google/site-kit-wp/assets/73545194/d95712a1-251b-4c29-bdaf-1b6e75561e8f)

As you can see the icon does appear on the external link when Ad Blocking Recovery is set up. 

![image](https://github.com/google/site-kit-wp/assets/73545194/67c2573e-9d10-4e42-8927-adac193a7d33)

## Steps to reproduce

1. Setup Site with AdSense connected.  
2. Go to AdSense settings and observe the banner in the screenshot above
3. Notice the learn more link does not have the external link icon. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Learn more" link in the Ad Blocking Recovery CTA within AdSense should have an external link icon.

## Implementation Brief

* [x] Remove the `hideExternalIndicator` prop from the `SupportLink` in the file assets/js/modules/adsense/components/settings/AdBlockingRecoverySetupCTANotice.js:

https://github.com/google/site-kit-wp/blob/dcfb6b508c13be416384f92601235995040e2ab8/assets/js/modules/adsense/components/settings/AdBlockingRecoverySetupCTANotice.js#L123-L138

### Test Coverage

* No new tests needed. Snapshots/VRTs may need updating.

## QA Brief

* Confirm the link icon is shows using the instructions in the Bug Description.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by eclarke1** [comment]
@benbowler @tofumatt please could you add a Priority label to this one? I presume P1 but please can you check

**Comment by benbowler** [comment]
@eclarke1 I would say P2 as it's a minor visual consistency fix.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that Ad Blocking Recovery CTA in AdSense settings now have external link icon.
- Verified the "Learn more" link in the Ad Blocking Recovery CTA within AdSense now have an external link icon.
- Also, verified ad blocker banner on main dashboard. 

<details>

**Latest :**

![image](https://github.com/google/site-kit-wp/assets/94359491/09434bc5-7d45-4715-8e0e-6e7ddeacd917)

**Develop :**

![image](https://github.com/google/site-kit-wp/assets/94359491/49bc21ec-0bd6-45c2-8b5f-b603bfd43c93)

![image](https://github.com/google/site-kit-wp/assets/94359491/a0ebe396-3510-4121-9e32-46ea9450adf7)

https://github.com/google/site-kit-wp/assets/94359491/61af9736-af32-41c3-9a0d-127635fe2b80


</details>
