### ISSUE TITLE
Change graph line colors on Search Traffic widget 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8247]
## Bug Description

I discussed this UX/Ui issue with Sigal.  The previous period line on the search traffic widget graph for `total clicks` is hard to see and she agreed.  It was also highlighted the other graphs within this widget aren't exactly aligned with our color scheme.  SigaI created a version with 4 colors that should all be visible, including the brighter shades for previous period. 

The colors for these graphs within the search traffic widget can be [found here](https://www.figma.com/file/nHnGFJizcJCyTVNZwLE8Vz/Site-Kit-Misc?type=design&node-id=1-6288&mode=design&t=aUyD2NC6iTXyUJ5r-0) in Figma. 

![image](https://github.com/google/site-kit-wp/assets/73545194/28d345a2-b72e-4e43-9ac2-c4778e67b0bb)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The colours used for the line charts in the Search Funnel (`SearchFunnelWidgetGA4`) widget should be updated to match the [Figma design](https://www.figma.com/design/nHnGFJizcJCyTVNZwLE8Vz/Site-Kit-Misc?node-id=1-6288&t=GsjKdbx6QQYGhQpA-0).

## Implementation Brief

* [ ] Update the graph line colours in https://github.com/google/site-kit-wp/blob/b820762bce3614d91bb7cb5c361b604d4b3f8213/assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js#L431-L464 to match the new colour values in Figma.

### Test Coverage

* Snapshots/VRTs may need updating, but otherwise no changes needed.

## QA Brief

* Setup Site Kit with the Analytics modules connected
* Navigate to the Search Traffic Widget
* Validate that the graph colours for the 4x metrics match [those in the Figma design](https://www.figma.com/design/nHnGFJizcJCyTVNZwLE8Vz/Site-Kit-Misc?node-id=1-3067&t=YEcnjUCyJmNcrgQ7-0)
* Open up an Entity dashboard and navigate to the same Search Traffic Widget
    * Validate the the graph colour for Engagement Rate matches that of the Conversions colour as per the Figma design (Engagement Rate is not explicitly shown in Figma but it's old colour was equal to that of the old Conversions colour and thus should be updated the match). This is the right most purple shade listed in the [colour chart in Figma](https://www.figma.com/design/nHnGFJizcJCyTVNZwLE8Vz/Site-Kit-Misc?node-id=1-5371&t=YEcnjUCyJmNcrgQ7-0).

## Changelog entry

* N/A

**Comment by eclarke1** [comment]
@zutigrm @tofumatt please could we add a priority label to this one?

**Comment by binnieshah** [comment]
@tofumatt @zutigrm please could we add a priority level to this one? Trying to see what can fall into sprint 131. Thanks

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by binnieshah** [comment]
@eugene-manuilov please could we add a priority level to this one?

**Comment by eugene-manuilov** [comment]
@binnieshah, added.

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified color for all metrics of the search widget with Figma on ,main dashboard.
- Verified `enragement rate ` which is available on entity dashboard graph color matches with conversion graph color.

@10upsimon I've noticed that graph color of 1 metrix i.e **Unique Visitors from Search** have different color from figma.

**Unique Visitors from Search** Different color

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/dcadf5ac-1128-4dce-9961-654ca2da0e73)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/3875ed6b-510e-40f2-8a19-961e96f830ba)

</details>


**PASS CASES**

**Total Impressions** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/bb0dd01d-21bc-4576-8ec5-ced42e65e5e5)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/75e6aa04-b279-40de-afef-81250a22f243)

</details>


**Total clicks** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/0d425e1c-fa5c-46e5-90d5-9e51bc4418d6)

Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/b0be2037-8c1d-45b9-aa3f-4975a6cf88df)

</details>



**Conversions** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/1d69a4d0-1c52-4226-a3a7-28893bc93d6b)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/d887a87f-0110-4571-a401-1124a6291e4b)

</details>

**Engagement Rate - entity dashboard** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/82a1693a-9d55-4235-967a-cd00388fde8b)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/37238e37-1caf-447d-9421-581ae3a45433)

</details>

**Comment by 10upsimon** [comment]
@mitogh after chatting to @sigal-teller about this, the correct colour is that used in the colour palette to the top left of the designs:

![Site Kit Misc – Figma 2024-07-10 at 11 24 04 AM](https://github.com/google/site-kit-wp/assets/72872375/33e140a2-c8f3-4625-b892-5b1555d002e0)

@sigal-teller has since updated the main graph design to match this colour, so this should now pass QA, back to you.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified color for all metrics of the search widget with Figma on ,main dashboard.
- Verified `enragement rate ` which is available on entity dashboard graph color matches with conversion graph color.

**Unique Visitors from Search** - current implemented color  is correct as per palette - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/dcadf5ac-1128-4dce-9961-654ca2da0e73)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/d3e2bb8c-937b-4b56-954e-aaf283e746e7)

</details>


**PASS CASES**

**Total Impressions** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/bb0dd01d-21bc-4576-8ec5-ced42e65e5e5)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/75e6aa04-b279-40de-afef-81250a22f243)

</details>


**Total clicks** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/0d425e1c-fa5c-46e5-90d5-9e51bc4418d6)

Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/b0be2037-8c1d-45b9-aa3f-4975a6cf88df)

</details>



**Conversions** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/1d69a4d0-1c52-4226-a3a7-28893bc93d6b)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/d887a87f-0110-4571-a401-1124a6291e4b)

</details>

**Engagement Rate - entity dashboard** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/82a1693a-9d55-4235-967a-cd00388fde8b)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/37238e37-1caf-447d-9421-581ae3a45433)

</details>

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on main environment.
- @10upsimon I noticed that the AdSense widget "Performance over the last X days" has updated tile color for the 'Page RPM' metrics, but the graph color has not been updated yet.

![image](https://github.com/google/site-kit-wp/assets/94359491/602a12d9-470d-48c7-b828-7f9e89ea6c69)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified color for all metrics of the search widget with Figma on ,main dashboard.
- Verified `enragement rate ` which is available on entity dashboard graph color matches with conversion graph color.
- Verified "Performance over that last X Days" widget all metrics graph color is now matches with Figma.
- Verified both "Search widget" and "Performance over that last X Days" widget have same graph color.

**_"Search Widget"_**

**Unique Visitors from Search** - current implemented color  is correct as per palette - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/dcadf5ac-1128-4dce-9961-654ca2da0e73)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/d3e2bb8c-937b-4b56-954e-aaf283e746e7)

</details>


**Total Impressions** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/bb0dd01d-21bc-4576-8ec5-ced42e65e5e5)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/75e6aa04-b279-40de-afef-81250a22f243)

</details>


**Total clicks** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/0d425e1c-fa5c-46e5-90d5-9e51bc4418d6)

Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/b0be2037-8c1d-45b9-aa3f-4975a6cf88df)

</details>



**Conversions** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/1d69a4d0-1c52-4226-a3a7-28893bc93d6b)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/d887a87f-0110-4571-a401-1124a6291e4b)

</details>

**Engagement Rate - entity dashboard** - PASS

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/82a1693a-9d55-4235-967a-cd00388fde8b)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/37238e37-1caf-447d-9421-581ae3a45433)

</details>

**_"Performance over the last X days" widget_**


**Earnings - PASS**

<details>

![image](https://github.com/user-attachments/assets/42905945-c597-4cab-af7a-1156a8ca06fa)


Figma-

![image](https://github.com/user-attachments/assets/1814f430-ec93-4a6a-91bd-695765516c25)

</details>

**Page RPM - PASS**

<details>

![image](https://github.com/user-attachments/assets/44b7f183-2924-4af7-8f7e-16e77bd7ab6a)

Figma -

![image](https://github.com/user-attachments/assets/ef60fb02-5aa4-4acb-9d39-9271dbd02251)

</details>

**Impressions - PASS**

<details>

![image](https://github.com/user-attachments/assets/ca81bccb-4200-4dd4-9368-e38889b01124)

Figma -

![image](https://github.com/google/site-kit-wp/assets/94359491/d3e2bb8c-937b-4b56-954e-aaf283e746e7)

</details>

**Page CTR - PASS**

<details>

![image](https://github.com/user-attachments/assets/0f43f1b0-8bf8-4062-b37b-8f20ba96e47b)

Figma -

![image](https://github.com/user-attachments/assets/18ac97be-1bbf-418f-b6de-19a56c78b2cc)

</details>
