### ISSUE TITLE
Google Analytics does not save "Snippet is not inserted"

### ISSUE THREAD

**Issue by rodneyjoyce** [google/site-kit-wp#825]
I am using Google Site Kit 1.0.2 on the latest version of Wordpress (5.2.4).

I got to Settings -> Analytics and click on edit, which pulls in my GA account settings.
https://i.imgur.com/dEDdUVD.png

I click on "Insert Snippet" and Confirm Changes and it now says "Snippet is inserted"
https://i.imgur.com/9VD3Luc.png

I go back to the dashboard and then back to Settings -> Analytics
https://i.imgur.com/XzI4z03.png

It now says it is NOT inserted. I cannot get it to save and stay, so it does not work.

When viewing source I can see GTM was inserted by Site Kit but no GA code.

**Comment by ernee** [comment]
@rodneyjoyce please note that Site Kit support has moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Please submit a new topic there and we'd be happy to assist you.

**Comment by rodneyjoyce** [comment]
Thanks, I have done that - https://wordpress.org/support/topic/google-analytics-does-not-save-snippet-is-not-inserted/
