### ISSUE TITLE
Use a proper user agent for site verification

### ISSUE THREAD

**Issue by archon810** [google/site-kit-wp#826]
Hi,

I couldn't figure out why Site Kit verification was getting blocked until I found that `Go-http-client` is blocked at the server level to avoid scrapers. Can you please use a proper unique user agent for these requests to avoid such issues?

```
"POST /wp-json/google-site-kit/v1/oauth/site/ HTTP/1.0" 403 7 "-" "Go-http-client/2.0 X-Middleton/1"
"POST /?rest_root=/google-site-kit/v1/oauth/site/ HTTP/1.0" 403 7 "-" "Go-http-client/2.0 X-Middleton/1"
```

Thanks.

**Comment by ThierryA** [comment]
Thanks for reporting this @archon810. We are now setting the `user-agent` to `Site Kit by Google/1.0`.
