### ISSUE TITLE
Add `consentMode` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8261]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new feature flag for `consentMode` should be added to the list of available features

## Implementation Brief

* [x] Add new feature flag
* [x] Merge https://github.com/google/site-kit-wp/pull/8262

### Test Coverage

* No changes necessary

## QA Brief

* New flag should be visible in Tester plugin

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅ 

Just gonna merge this one as well 🙂

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A new feature flag for `consentMode` appears on the tester plugin.
  - Tested to ensure the feature flag can be enabled and disabled. 
  - Tested to ensure that the feature flag can be saved.
  - No console errors appear when the feature flag is enabled and disabled. 

![image](https://github.com/google/site-kit-wp/assets/73545194/13a031b0-daec-4d9c-b109-dde6eae633ae)
