### ISSUE TITLE
Blank dashboard: d.join is not a function

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#8266]
## Bug Description

There have been reports recently of a blank Site Kit dashboard, and settings tab, with the following console errors:
` Uncaught TypeError: d.join is not a function`

The below error occurs also for impacted users:
`Uncaught (in promise) TypeError: Object(...) is not a function`

Full console errors from one impacts user below:

<details><summary>Full browser console errors</summary>

```
load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.4.3:5 JQMIGRATE: Migrate is installed, version 3.4.1
googlesitekit-api-97cb26e934224ff68748.js:1 Uncaught TypeError: d.join is not a function
at googlesitekit-api-97cb26e934224ff68748.js:1:3747
at Object. (googlesitekit-api-97cb26e934224ff68748.js:1:7716)
at 34 (googlesitekit-api-97cb26e934224ff68748.js:1:7722)
at webpack_require (runtime-2c21c52e9bf2a70b9e0b.js:1:615)
at Object. (googlesitekit-api-97cb26e934224ff68748.js:14:1812)
at 8 (googlesitekit-api-97cb26e934224ff68748.js:14:3518)
at webpack_require (runtime-2c21c52e9bf2a70b9e0b.js:1:615)
at Object. (googlesitekit-api-97cb26e934224ff68748.js:1:8196)
at 39 (googlesitekit-api-97cb26e934224ff68748.js:1:13819)
at webpack_require (runtime-2c21c52e9bf2a70b9e0b.js:1:615)
googlesitekit-datastore-site-2d9520db4e0ec9f11ebe.js:1 Uncaught (in promise) TypeError: Object(…) is not a function
at reducer (googlesitekit-datastore-site-2d9520db4e0ec9f11ebe.js:1:38051)
at googlesitekit-data-8b471e1589740986681d.js:1:3665
at Array.reduce ()
at googlesitekit-data-8b471e1589740986681d.js:1:3636
at googlesitekit-data-8b471e1589740986681d.js:1:3665
at Array.reduce ()
at Object.root (googlesitekit-data-8b471e1589740986681d.js:1:3636)
at eval (eval at (googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:520290), :3:67)
at googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:520378
at p (googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:471090)
googlesitekit-datastore-forms-a36a42c00708bd13a033.js:14 Uncaught (in promise) TypeError: Object(…) is not a function
at googlesitekit-datastore-forms-a36a42c00708bd13a033.js:14:5305
at googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:472623
at googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:763713
at Array.some ()
at n (googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:763688)
at googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:763641
at a (googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:763743)
at e (googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:763998)
at googlesitekit-vendor-f37a2c73051f9cbec9b3.js:7:472807
at new Promise ()
```
</details>

Occurrences include the below, and note that there are many recently "blank dashboard" reports, although lacking in information. All the below have the same browser console errors:
- https://wordpress.org/support/topic/site-kit-is-blank-2 | [SH information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNi2QdWHlEEG7h5BrgU9MgWoZ1ZtNuhxTL5siHKJ01Zc5Y2bD1mC3DNC0aVahE-vwsw) | **Open**
- https://wordpress.org/support/topic/blank-3-errors-in-console/ | No SH information | **Open**
- https://wordpress.org/support/topic/uncaught-typeerror-d-join-is-not-a-function/#new-topic-0 | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiUeLWhSD6n_aLd3WMdTxCFr_SXDfVG3iGj6PjIk595cTCmOPp7EGEXw3q6doSu1ks) | **Open**
- https://wordpress.org/support/topic/site-kit-dashboard-not-loading-showing-blank-screen-with-console-errors/ | No SH info | **Resolved** - No response from user
- https://wordpress.org/support/topic/google-site-kit-dashboard-displays-blank-screen/ | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiXqPoqtUPjAt0dHDUzHZo0Ig1TxLDo0Xw-PDUk87Qg9iVpX0wsMGaXCqRA3eM1lAM) | **Open**
- https://wordpress.org/support/topic/typeerror-d-join-is-not-a-function | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNinPYBa68BP5Vb71wYiHReIr4fvQk6enIeFRCWnsQozecitMUEc_oihvCkqJSOwLcI) | **Resolved** by resetting
- https://wordpress.org/support/topic/site-kit-dashboard-page-not-loading/ | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNj1zfsL-gBPyURT2otOl3RJqstuAmj2--PODLY8ylz0E8gfXuE-PHk-2GoqEapUnX8) | **Resolved** by resetting, although there is no evidence this user had the same browser console errors

For this impacted, resetting the plugin may allow you to proceed [(Tools > Available Tools > Reset Site Kit](https://i.imgur.com/P6al3e7.png)). Note that this will result in all previously connected users being disconnected. Analytics or any other modules previously connected, will also need to be connected once more. 

## Steps to reproduce

1. Enable tracking opt-in
2. Add this code to simulate an unexpected value for user roles  
```php
add_filter( 'googlesitekit_inline_tracking_data', function ( $data ) {
	$data['userRoles'] = new \stdClass();

	return $data;
}, 99 );
```
3. Visit SK dashboard or settings screen

## Screenshots

<img width="1274" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/235d9033-38a9-471b-9b2f-0a12e4299e31">
The above is using an unminified build so the errors are more verbose.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* SK screens should not be broken by invalid user role data passed from the backend 

## Implementation Brief

* [ ] Update https://github.com/google/site-kit-wp/blob/28780f2a4a3502573d513eb1a82a931284b874fd/assets/js/util/tracking/createInitializeSnippet.js#L56 and this line https://github.com/google/site-kit-wp/blob/28780f2a4a3502573d513eb1a82a931284b874fd/assets/js/util/tracking/createInitializeSnippet.js#L72 to conditionally use `join()` function, only if they are array value
* To move this faster, I already attached a PR and updated QAB

### Test Coverage

* No test update needed

## QA Brief

* Follow the `Steps to reproduce` section
* Verify there is no error

## Changelog entry

* Fix issue that could cause a dashboard error when the current user's roles return an unexpected result.

**Comment by jamesozzie** [comment]
[One user currently impacted](https://wordpress.org/support/topic/site-kit-is-blank-2) has tried the following, with the same occurring:

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check - The same occurs, incognito
- [x] Front end check (mixed content, minified content, combined JS) - No issues
- [x] Incognito mode - Same occurs
- [x] Checked users Site Health info, no identified causes - No obvious causes, no CDN in use
- [x] Additional .htaccess rules applied - Yes, `htaccess_extra_rules: true`
- [x] Uninstalled and reinstalled plugin
- [ ] User confirmed no ""Critical errors"" in their Site Health status
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Checked viewing dashboards from another WordPress administrator account
- [ ] Reviewed error logs 
- [ ] Reviewed XHR requests

**Comment by aaemnnosttv** [comment]
The line in the console error shown above `googlesitekit-api-97cb26e934224ff68748.js:1:3747` indicates this line in the source of 1.119.0

https://github.com/google/site-kit-wp/blob/8dfe7bd7369b9662ff72eba428f39aa4358eadc4/assets/js/util/tracking/createInitializeSnippet.js#L56

We should be able to prevent this from happening.

**Comment by tofumatt** [comment]
The IB here is roughly correct, though we can guard even further against it being `undefined` or something like that by doing `userRoles?.join(',') ?? ''`. But I'll comment on the PR 😄 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Recreated the console error and blank dashboard by inserting the code into a mu-plugin on the latest release. When I switched to the develop branch, the dashboard loaded, and no console errors appeared. 

<details>
 <summary>Screenshots</summary>

Latest release:
![image](https://github.com/google/site-kit-wp/assets/73545194/40a10f97-9d6b-45d8-981a-4b08b3d742ca)

Develop branch
![image](https://github.com/google/site-kit-wp/assets/73545194/329f3388-0fd6-4003-b838-d534e0ea928d)

</details>
