### ISSUE TITLE
Support sharing of Site Kit information with other site users

### ISSUE THREAD

**Issue by archon810** [google/site-kit-wp#827]
One of the most confusing concepts about Site Kit that I couldn't figure out before installing it and trying myself was whether the info from the connected accounts (Analytics, AdSense, etc.) was visible to other users of the site.

Specifically, whether other admins could see it, or other lower level users, such as Editors, Authors, Contributors, etc.

I had to create a test user and test it out myself on our dev site to get these answers. The answers seem to be:

* Only admins see Site Kit data or any menu items. Editors, etc. don't see anything at all.
* Other admins are prompted to set up Site Kit from scratch, as if it'd never been set up before, meaning each Site Kit configuration is per-user. This was not obvious at all to me, so I'm glad I confirmed it. Other

With this in mind:

1. Please update the site docs to make this more clear. An entry somewhere on these pages seems fitting https://sitekit.withgoogle.com/documentation/who-is-site-kit-for/.
1. It'd be great to be able to share specific data with other users. For example, I'd love it if my writers could view Analytics data for posts, but not the more sensitive AdSense data.

What do you think, team?

**Comment by jamesozzie** [comment]
@archon810 Thanks for the input, there is an open feature request for this issue, which you can find [here, #6](https://github.com/google/site-kit-wp/issues/6). As we have that issue open, and set with a priority I will close this issue. But feel free to add any additional to that master issue.

**Comment by archon810** [comment]
@jamesozzie Sorry for not finding that issue, thanks for pointing it out.

However, while the main issue is indeed a duplicate, the documentation update request is unique to this ticket. So can we turn this ticket into that?

**Comment by jamesozzie** [comment]
@archon810 Good point, once #6 is delivered there may be no need for documentation, with other admin users being able to view dashboard, but I will speak to the team about it as there is no ETA for this issue just yet

**Comment by snapey** [comment]
Disagree that there is no need for documentation.  As the installer of the Site Kit plugin, it needs to be obvious what the other roles in the system will see and can do.  Take my own example. I have multiple customers with their sites registered in analytics and search console. My client requested access to site kit. They have admin access but generally stay away from the theme and plugins.  It was with some trepidation that I installed Site Kit given that I had to give access to my google account - where there are lots of other client site analytics accessible.
Coming at it from the perspective that all WordPress sites are managed by the owner seems somewhat naive. I have to now message the client but don't know if they will see anything, or as others have suggested, will be prompted to setup Site Kit from scratch using their own google account.

**Comment by jamesozzie** [comment]
@snapey @archon810 I can confirm we are working on updated documentation. You can also follow [this](https://github.com/google/site-kit-wp/issues/881) GitHub issue, which relates to a custom setup screen for other admin users.

**Comment by aaemnnosttv** [comment]
[Dashboard sharing is now available!](https://github.com/google/site-kit-wp/issues/6#issuecomment-1352320275) For more information, see the announcement post 🎉 
https://sitekit.withgoogle.com/news/share-the-site-kit-dashboard-with-your-team/
