### ISSUE TITLE
Create REST infrastructure for Consent Mode

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8271]
## Feature Description

This issue is for adding REST endpoint registration, preloading, etc to read and update consent mode settings added in #8270.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New REST endpoints should be added for reading and updating the Consent Mode settings.
* The endpoint routes should be as follows:
  * `GET core/site/data/consent-mode`
  * `POST core/site/data/consent-mode`
* The shape of the response and the `POST` payload should be that of the settings as defined in #8270.
* The `GET` request should be preloaded at page load.

## Implementation Brief

* [ ] Follow the `REST_Consent_Mode_Controller` class from the branch [hack/como](https://github.com/google/site-kit-wp/compare/hack/como).
* [ ] Register an instance of the `REST_Consent_Mode_Controller` class in `Consent_Mode`.

### Test Coverage

* Provide PHPUnit test coverage for the above changes.

## QA Brief

* Use the following snippet to test the POST endpoint.
* Ensure at least one of `enabled` or `regions` is set.
* `enabled` should be a boolean, `regions` an array of strings conforming to the [ISO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) region code pattern (i.e. case insensitive `[A-Z]{2}` or `[A-Z]{2}-[A-Z]{2}`).
```js
googlesitekit.api.set(
  'core', 'site', 'consent-mode',
  {
    settings: {
      enabled: true,
      regions: ['AB','AC']
    }
  }
)
```

* Use the following snippet to test the GET endpoint.
```js
googlesitekit.api.get(
  'core', 'site', 'consent-mode',
  {},
  {
    useCache: false
  }
)
```

## Changelog entry

* Add REST endpoints for consent mode.

**Comment by techanvil** [comment]
This seems pretty uncontentious, so I am going to move it to Execution and start work on the implementation.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified both snippet when site kit is not set up.
- Verified both snippets when site kit setup without analytics.
- Verifed both snippets when site kit setup with analytics.
- Verified snippets with or without setting enabled or regions value.


<details>

**POST Endpoint :** 

![image](https://github.com/google/site-kit-wp/assets/94359491/0e83fcc7-ada9-4e4a-9665-6384266409c6)

![image](https://github.com/google/site-kit-wp/assets/94359491/b6e08e0a-2e2a-40a4-8a96-8f451042b6cc)

_Wrong enabled value:_

![image](https://github.com/google/site-kit-wp/assets/94359491/32490f90-7695-43b7-a3fb-6d629b0254d0)

_Wrong regions value:_

![image](https://github.com/google/site-kit-wp/assets/94359491/6fde27f2-8b91-4afb-90dc-c8d5db844a7d)

_Without region and enabled is set._

![image](https://github.com/google/site-kit-wp/assets/94359491/df973b4b-eb48-4cce-8007-d839ad30cc44)

![image](https://github.com/google/site-kit-wp/assets/94359491/ac095458-e3e3-4954-b964-ff70196199e2)


_When Regions values are  not set then default 32 regions will be auto set_

![image](https://github.com/google/site-kit-wp/assets/94359491/1e906af4-3117-4920-bfce-b31825c9c6c8)

_When Region value is set -_

![image](https://github.com/google/site-kit-wp/assets/94359491/46a19d93-a65e-428a-9030-8f5bef0b8aa2)

![image](https://github.com/google/site-kit-wp/assets/94359491/6358d264-2ced-42c9-bf15-97b261e448a8)
 
**GET endpoint**

![image](https://github.com/google/site-kit-wp/assets/94359491/94b2a7b5-65f6-40c8-994d-e1d749b68d86)

_Get endpoint with default values -_

![image](https://github.com/google/site-kit-wp/assets/94359491/a156a870-3687-40ec-981f-cd3aa75a4d54)

</details>
