### ISSUE TITLE
Create datastore infrastructure for Consent Mode

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8272]
## Feature Description

Once the fundamental infrastructure for consent mode settings and REST interface is in place, datastore infrastructure can be extended with selectors and actions for working with the state.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Extend the `site` datastore with the following set of selectors and actions:
  * `getConsentModeSettings()`
  * `isConsentModeEnabled()`
  * `saveConsentModeSettings()`
  * `setConsentModeEnabled()`

## Implementation Brief

* [ ] Follow the `site/consent-mode.js` implementation from the branch [`hack/como`](https://github.com/google/site-kit-wp/compare/hack/como).
* [ ] However, omit `setConsentModeRegions()`, this can be added later. Do add `isConsentModeEnabled()`.
* [ ] Combine the resulting store with the site store.

### Test Coverage

* Provide JS test coverage for the above changes

## QA Brief

* Exercise the selectors and actions listed in the AC via the JS console, e.g.

```js
// Retrieve the initial settings.
// Note that the first time it's run it will return `undefined`; run it a second time to see the loaded value.
googlesitekit.data.select('core/site').getConsentModeSettings();

// Get the current value of `enabled`:
const enabled = googlesitekit.data.select('core/site').isConsentModeEnabled();

// Toggle `enabled` locally:
googlesitekit.data.dispatch('core/site').setConsentModeEnabled( ! enabled );

// Persist the settings:
await googlesitekit.data.dispatch('core/site').saveConsentModeSettings();
```

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
AC + IB ✅

**Comment by techanvil** [comment]
Hey @aaemnnosttv, just a heads up that I have renamed `getConsentModeEnabled()` to `isConsentModeEnabled()` in the AC/IB.

**Comment by tofumatt** [comment]
Moving directly to Approval as QA is just the code run as part of the PR, nothing user-facing here 🙂
