### ISSUE TITLE
Print consent default gtag config if consent mode is enabled

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8274]
## Feature Description

With the new gtag infrastructure in place, the default consent preferences should be set before the tag is loaded based on consent mode settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GTag `consent` command should be rendered above the `gtag.js` script tag when the Consent Mode `enabled` setting is `true`.
* The call should be structured as follows, with `denied` hardwired as the default.
```js
gtag(
  "consent",
  "default",
  {
    "analytics_storage":  "denied",
    "ad_storage":         "denied",
    "ad_user_data":       "denied",
    "ad_personalization": "denied",
    "region":             [ "AT, "BE, "BG", ... ]
  }
);
```

## Implementation Brief

* [ ] Add the `Consent_Mode` class, following the version in the branch [`trh/decouple-gtag`](https://github.com/google/site-kit-wp/compare/trh/decouple-gtag) to render the GTag `consent` command to set the default values in `<head>`.
* [ ] Update the `Consent_Mode` class, using the version in the branch [`hack/como`](https://github.com/google/site-kit-wp/compare/hack/como) as a guide for setting the default values according to the Consent Mode settings.

### Test Coverage

* Provide appropriate test coverage for the above changes.

## QA Brief

* Enable the `consentMode` feature flag.
* Use the following snippet to toggle the Consent Mode enabled setting in the JS console:
```js
googlesitekit.api.set(
  'core', 'site', 'consent-mode',
  {
    settings: {
      enabled: true, // or `false`
    }
  }
);
```
* Look for the following snippet in `<head>` to confirm the GTag consent defaults are set for the EEA region:
```html
<!-- Google tag (gtag.js) Consent Mode snippet added by Site Kit -->
<script id='google_gtagjs-js-consent-mode'>
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag("consent","default", {"ad_personalization":"denied","ad_storage":"denied","ad_user_data":"denied","analytics_storage":"denied","regions":["AT","BE","BG","CH","CY","CZ","DE","DK","EE","ES","FI","FR","GR","HR","HU","IE","IS","IT","LI","LT","LU","LV","MT","NL","NO","PL","PT","RO","SE","SI","SK","UK"]});
</script>
<!-- End Google tag (gtag.js) Consent Mode snippet added by Site Kit -->
```
* Verify this is present on front-end WP pages, not admin, both when logged in and as an anonymous user.

## Changelog entry

* Print gtag configuration for consent mode when enabled.

**Comment by techanvil** [comment]
@aaemnnosttv, having discussed this on our sync on Friday I'm moving this ahead to execution.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@techanvil On the develop branch, with `consentMode` enabled OR disabled, the errors below appear on front-end pages. 

`Deprecated:  Function Google\Site_Kit\Modules\Analytics_4\Web_Tag::set_consent_mode_enabled is deprecated since version n.e.x.t with no alternative available. in /s3-drumtrouble/wordpress/wp-includes/functions.php on line 6031
`

`Deprecated:  Function Google\Site_Kit\Modules\Analytics_4\Web_Tag::add_legacy_block_on_consent_attributes is deprecated since version n.e.x.t with no alternative available. in /s3-drumtrouble/wordpress/wp-includes/functions.php on line 6031`

It's concerning that the error appears with the feature flag disabled.  This appears before the snippet in the QAB is run.  

![image](https://github.com/google/site-kit-wp/assets/73545194/6703f9a8-d1e5-4253-9ac7-13b2faa231ff)

When the code is run in console, this does pass the QAB.  Interested in your thoughts.

**Comment by techanvil** [comment]
Hi @wpdarren, this indicates you have `WP_DEBUG` and `WP_DEBUG_LOG` enabled, which is not something that we'd expect to see on a production site.

As mentioned [here](https://wpadvancedads.com/finding-errors-with-wp_debug/#3_Insert_WP_DEBUG_codes it's possible to keep the debug log enabled but prevent errors being printed to the page by setting `WP_DEBUG_DISPLAY` to `false`.

Anyhow, the bottom line is that it's not an issue we need to address, as it's up to users to choose how they want warnings like this to be displayed.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@techanvil I noticed that the code does not appear on AMP pages.  Is that expected?  I read the one-pager, which mentions that the consent is already covered, but I wasn't sure if this was included via Site Kit.  The WP Debug error messages reported previously are no longer displaying now, so thank you for your work on that. 

**Verified:**

- The code below is generated on WP front-end pages, posts, archives, etc. 
- The code below is not generated in the WP dashboard. 
- Tested that the code below gets generated when logged in and as an anonymous user.

```
<!-- Google tag (gtag.js) Consent Mode snippet added by Site Kit -->
 <script id='google_gtagjs-js-consent-mode'>
 window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
  gtag("consent","default", {"ad_personalization":"denied","ad_storage":"denied","ad_user_data":"denied","analytics_storage":"denied","regions":["AT","BE","BG","CH","CY","CZ","DE","DK","EE","ES","FI","FR","GR","HR","HU","IE","IS","IT","LI","LT","LU","LV","MT","NL","NO","PL","PT","RO","SE","SI","SK","UK"]});
  </script>
<!-- End Google tag (gtag.js) Consent Mode snippet added by Site Kit -->
```

![image](https://github.com/google/site-kit-wp/assets/73545194/8c15324c-1761-4869-a2fc-b94c8fab0b58)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The code below is generated on WP front-end pages, posts, archives, etc. 
- The code below is not generated in the WP dashboard. 
- Tested that the code below gets generated when logged in and as an anonymous user.

```
<!-- Google tag (gtag.js) Consent Mode snippet added by Site Kit -->
 <script id='google_gtagjs-js-consent-mode'>
 window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
  gtag("consent","default", {"ad_personalization":"denied","ad_storage":"denied","ad_user_data":"denied","analytics_storage":"denied","regions":["AT","BE","BG","CH","CY","CZ","DE","DK","EE","ES","FI","FR","GR","HR","HU","IE","IS","IT","LI","LT","LU","LV","MT","NL","NO","PL","PT","RO","SE","SI","SK","UK"]});
  </script>
<!-- End Google tag (gtag.js) Consent Mode snippet added by Site Kit -->
```

![image](https://github.com/google/site-kit-wp/assets/73545194/8c15324c-1761-4869-a2fc-b94c8fab0b58)
