### ISSUE TITLE
Create infrastructure for detecting & installing WP Consent API

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8276]
## Feature Description

Consent mode is primarily responsible for setting the default preferences for consent. Updates to consent can happen from a number of sources, so we will be integrating with the WP Consent API which other Consent Management Platforms (CMP) will integrate with. This way, we can listen for state update events via the API rather than coupling to specific CMPs.

This issue is about adding some basic infrastructure to detect the presence of the API, and if not available, facilitate installation and/or activation of the plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existence of the WP Consent API should be exposed to the front-end via a new REST endpoint.
* ~~If the API is present, determine whether any plugin has registered itself with the WP Consent API and expose that via an additional field.~~
* If the API is not present, additional state should be exposed to facilitate the installation and activation of the WP Consent API.
* The endpoint route should be `GET core/site/data/consent-api-info`.
* The response should always contain the following field:
```php
  'hasConsentAPI' => boolean,
```
* When the API is _not_ present, the following data should be added to the response:
```php
'wpConsentPlugin' => array(
  'active'       => boolean,
  'installed'    => boolean,
  'activateURL'  => boolean,
  'installURL'   => boolean
)
```
* Datastore infrastructure should be created to wrap the endpoint, i.e. a `getConsentAPIInfo()` selector should be added.

## Implementation Brief

* [ ] Implement the endpoint as per the AC, following the [`Developer_Plugin_Installer`](https://github.com/google/site-kit-wp/blob/9c912c6d513a722fa8f42aa002bcb239a41e03a5/includes/Core/Util/Developer_Plugin_Installer.php#L115) class by way of example.
  * It should also be ensured that our standard REST controller pattern is followed here.
* [ ] Use `function_exists()` to check for the presence of the [`wp_set_consent`](https://plugins.trac.wordpress.org/browser/wp-consent-api/tags/1.0.7/api.php#L199) function to determine whether the API exists.
* [ ] Preload the endpoint, but ensure it's only registered on the Settings screen.
* [ ] Add datastore infrastructure to wrap the new endpoint, following the `site/developer-plugin` store by way of example.

### Test Coverage

* Provide a pragmatic level of test coverage for the above changes.

## QA Brief

**Note: The endpoint will _not_ return the `wpConsentPlugin.active` field, it was determined during execution this is not needed, the `hasConsentAPI` value effectively indicates whether the plugin is active.**

* Exercise the new endpoint via the datastore selector in the JS console:
```js
// Retrieve the WP Consent API info.
// Note that the first time it's run it will return `undefined`; run it a second time to see the loaded value.
googlesitekit.data.select('core/site').getConsentAPIInfo();
```
* Test it with the WP Consent API plugin _not_ installed, installed but not active, and installed _and_ active (reload the page between tests).

## Changelog entry

* Add functionality for detecting & installing the WP Consent API.

**Comment by aaemnnosttv** [comment]
> * If the API is present, determine whether any plugin has registered itself with the WP Consent API and expose that via an additional field.

I'm not sure this will be useful for us since this is just about plugins declaring that they adhere to the API, not specifically for a CMP or plugin that will handle the actual consent side of things. This is what I thought originally so I'm guessing you may have thought the same. For example, you can find a few plugins that implement this on GH including WooCommerce (not a CMP 😄) https://github.com/search?q=wp_consent_api_registered_&type=code

I.e. SK itself should declare this support.

Otherwise AC LGTM.

As far as IB goes, it's high level of course, but with reference to the `Developer_Plugin_Installer`, we should follow our REST controller pattern (which is mostly what that class is) but just wanted to point that out. Also, as per the comment above, we can probably omit the part about [consent_api_registered()](https://plugins.trac.wordpress.org/browser/wp-consent-api/tags/1.0.7/api.php#L220)

**Comment by techanvil** [comment]
> > * If the API is present, determine whether any plugin has registered itself with the WP Consent API and expose that via an additional field.
> 
> I'm not sure this will be useful for us since this is just about plugins declaring that they adhere to the API, not specifically for a CMP or plugin that will handle the actual consent side of things. This is what I thought originally so I'm guessing you may have thought the same. For example, you can find a few plugins that implement this on GH including WooCommerce (not a CMP 😄) https://github.com/search?q=wp_consent_api_registered_&type=code
> 
> I.e. SK itself should declare this support.

Thanks for clarifying that. I've removed the point from this AC, and specified that SK should register itself with the WP Consent API in https://github.com/google/site-kit-wp/issues/8277.

> As far as IB goes, it's high level of course, but with reference to the `Developer_Plugin_Installer`, we should follow our REST controller pattern (which is mostly what that class is) but just wanted to point that out. Also, as per the comment above, we can probably omit the part about [consent_api_registered()](https://plugins.trac.wordpress.org/browser/wp-consent-api/tags/1.0.7/api.php#L220)

Thanks, I've also removed this point and added one about following our standard REST controller patterm.
