### ISSUE TITLE
Add Consent Mode section to settings screen

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8278]
## Feature Description

A new settings section will be added to the SK settings screen for Consent Mode. To begin with, it will only allow toggling the enabled state of consent mode, but will also provide feedback about the availability of the WP Consent API and the ability to install/activate it if needed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new Consent Mode section should be added to the Admin Settings tab on the Settings screen.
* This should include all aspects relating to the Settings screen from the [first iteration](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?type=design&node-id=1-14&mode=design&t=yIrMyTmdPhK0aEJ5-0) of the Figma design, including:
  * The switch to toggle Consent Mode on/off.
  * The different designs for Ads and non-Ads users (criteria for determining an "Ads user" is specified under [**When does this apply**](https://docs.google.com/document/d/1KSTPqXNlGcN-krK5pxzdP2a-sHaVO9RYzIEU7qIF9qA/edit?tab=t.0#heading=h.t6jfalui4jsi) in the one-pager).
  * The WP Consent API and Content Management Platform related panels.
  * The confirmation modal for turning Consent Mode off.
* The **Install** CTA should open the WP Consent API plugin installation page in the same window (in keeping with how we link to the Developer Plugin installation page, and thus encouraging the user to refresh Site Kit rather than leaving it open with the CTA still showing).
* If the WP Consent API plugin is present but not activated, "Install" should be replaced with "Activate", and the **Activate** CTA should open the WP Consent API plugin activation page in the same window (as discussed above).
* Note that as discussed on [Asana](https://app.asana.com/0/0/1206634841828797/1206725971597795/f), we are going to update the `Badge` component so that badges no longer display the text in uppercase. We will also update the "Recommended" badge colour. This means the "Recommended" badge seen [here](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module-settings--edit-open-with-existing-tag-same-account) will be updated to match the style in the Consent Mode Figma design.

## Implementation Brief

* [ ] Start of with the Settings components in the branch [`hack/como`](https://github.com/google/site-kit-wp/compare/hack/como).
* [ ] Build out the remainder of the AC following standard Site Kit patterns, reusing existing components where possible, and making use of the Consent Mode infrastructure built to date.

### Test Coverage

* Add to Storybook with VRT scenarios.

## QA Brief

* Enable the `consentMode` feature flag, navigate to the **Admin Settings** tab on the **Settings** screen.
* Verify the Consent Mode Settings section is implemented and works correctly.
  * This covers all aspects on the Settings screen including the confirmation modal.
  * Ensure toggling the switch updates the Consent Mode `enabled` setting.
* Refer to:
  * The [Figma design](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=1%3A14&mode=dev) - please be pragmatic, it has to follow the design but doesn't have to be absolutely pixel perfect.
  * The [testing instructions](https://docs.google.com/document/d/1-kNcEPgrJO5NJUbULOsi6_i0UcaB0qsQqQbnkfou074/edit).
  * Test with the Ads Conversion ID set/not set, and with the WP Consent API plugin not installed, installed but not activated, and fully installed.
* Note that a loading state has also been implemented, which is similar to the loading state for the Key Metrics Settings section.
* For the last AC point:
  * Verify the "Recommended" badge has been updated on the AdSense module settings, this can be viewed in Storybook:
    * PR: https://google.github.io/site-kit-wp/storybook/pull/8339/?path=/story/adsense-module-settings--edit-open-with-existing-tag-same-account
    * `develop`: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module-settings--edit-open-with-existing-tag-same-account

## Changelog entry

* Add settings in the Site Kit admin for Consent Mode.

**Comment by techanvil** [comment]
I'm moving this to execution to keep things moving!

**Comment by techanvil** [comment]
This was moved directly to execution so as not to block the progress toward our hard delivery target.

**Comment by techanvil** [comment]
This was moved directly to execution so as not to block the progress toward our hard delivery target for Consent Mode.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@techanvil I found a few observations while testing: 

1. When you enable consent mode, the toggle text doesn't change to disable. From the figma designs this is expected but it feels a weird UX/UI having the label as enable when it is enabled. I don't believe other toggles work this way? 

![image](https://github.com/google/site-kit-wp/assets/73545194/4f4aa812-55a0-4f5b-80bb-6a19b54ca1be)

2.  When the WP Consent API is installed, and an Ads Conversion ID is entered in Analytics settings, this message appears even when Consent mode is enabled.  Should it? I felt it should only appear when consent mode is disabled.  `If you have Google Ads campaigns for this site, it’s highly recommended to enable Consent mode - otherwise you won’t be able to collect any metrics on the effectiveness of your campaigns in regions like the European Economic Area.`

3. Minor: in the text above, should there be a comma after `otherwise`? 

![image](https://github.com/google/site-kit-wp/assets/73545194/812351a3-9309-471a-9e72-5742805e0cff)

4. I am confused with the scenario where WP Consent API is installed, Consent mode is activated.  This is what I see:

![image](https://github.com/google/site-kit-wp/assets/73545194/bd764f7a-5ed1-40ac-a141-d1b713aa1956)

This is what is appearing on Figma designs.  I expected to see the check mark icon in the API plugin section. 

Am I missing something here? 

![image](https://github.com/google/site-kit-wp/assets/73545194/7b74e623-9a09-43a6-8e14-264fda7dd4f0)

**Comment by techanvil** [comment]
Thanks for raising these @wpdarren.

> 1. When you enable consent mode, the toggle text doesn't change to disable. From the figma designs this is expected but it feels a weird UX/UI having the label as enable when it is enabled. I don't believe other toggles work this way? 

I'm not sure that we have any switches where the label changes - it doesn't for these ones on the Analytics settings page for example, so I think it's consistent as it stands.

_Toggled on:_
![image](https://github.com/google/site-kit-wp/assets/18395600/64935715-2174-409f-9a93-7382af1c8956)

_Toggled off:_
![image](https://github.com/google/site-kit-wp/assets/18395600/5d4ede37-3b9f-4130-aecd-e5da1582d0a9)

> 2.  When the WP Consent API is installed, and an Ads Conversion ID is entered in Analytics settings, this message appears even when Consent mode is enabled.  Should it? I felt it should only appear when consent mode is disabled.  `If you have Google Ads campaigns for this site, it’s highly recommended to enable Consent mode - otherwise you won’t be able to collect any metrics on the effectiveness of your campaigns in regions like the European Economic Area.`

Thanks for spotting this - you're right, it should only appear when CoMo is disabled. I've created a [PR](https://github.com/google/site-kit-wp/pull/8349) which includes a fix for this.

> 3. Minor: in the text above, should there be a comma after `otherwise`? 

![image](https://github.com/google/site-kit-wp/assets/73545194/812351a3-9309-471a-9e72-5742805e0cff)

I agree, I think it would be marginally better with the comma. I have raised the question with @marrrmarrr. Given how minor it is I'll make the change now, it will be quick to revert if needs be.

> 4. I am confused with the scenario where WP Consent API is installed, Consent mode is activated.  This is what I see:
> 
> ![image](https://github.com/google/site-kit-wp/assets/73545194/bd764f7a-5ed1-40ac-a141-d1b713aa1956)
> 
> This is what is appearing on Figma designs.  I expected to see the check mark icon in the API plugin section. 
> 
> Am I missing something here? 
> 
> ![image](https://github.com/google/site-kit-wp/assets/73545194/7b74e623-9a09-43a6-8e14-264fda7dd4f0)

Thanks, another good spot! This section including the check mark should be visible in this scenario. I've included a fix for this in the aforementioned PR.
