### ISSUE TITLE
Create conditional dashboard CTA for Consent Mode

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8279]
## Feature Description

A new dashboard notification should be created to surface awareness of Consent Mode for users who are configuring Site Kit to place an Ads conversion ID. This notification should only be shown if consent mode is not enabled.

The primary CTA should enable consent mode and navigate to the Admin Settings tab of the settings screen in case the user needs to take further action.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A Consent Mode setup CTA banner should be shown on the main and entity dashboard.
* This should follow the [first iteration](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?type=design&node-id=1-14&mode=design&t=yIrMyTmdPhK0aEJ5-0) of the Figma design.
* It should appear while Consent Mode is disabled and the user hasn't dismissed the banner.
* The primary CTA should enable Consent Mode, dismiss the banner and navigate to the Settings screen.
* The dismissal CTA should dismiss the banner. It should then be shown again after two weeks, for a maximum of three dismissals. The final showing of the banner will have the dismissal CTA text updated to "Don't show again". Actioning the CTA again will dismiss the banner permanently.

## Implementation Brief

* [ ] The design is similar to the Audience Segmentation setup CTA banner, and the implementation can borrow from its PR: https://github.com/google/site-kit-wp/pull/8292
  * We can potentially follow up later to refactor these components to share code as appropriate.
* [ ] Make use of the prompts infrastructure to implement the multiple dismissal behaviour, as seen in [`AdBlockingRecoverySetupCTAWidget`](https://github.com/google/site-kit-wp/blob/fda3ef7e55d6bef501a4c6a4e71cff6e5017adc7/assets/js/modules/adsense/components/dashboard/AdBlockingRecoverySetupCTAWidget.js#L284-L286).

### Test Coverage

* Add to Storybook with a VRT scenario.

## QA Brief

* Enable the `consentMode` feature flag, ensure that the Consent Mode `enabled` setting is `false` and the Ads Conversion ID is set.
* Verify that the Consent Mode setup banner is implemented and works correctly as per the AC.
* Refer to:
  * The [Figma design](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=1%3A14&mode=dev) - please be pragmatic, it has to follow the design but doesn't have to be absolutely pixel perfect.
  * The [testing instructions](https://docs.google.com/document/d/1-kNcEPgrJO5NJUbULOsi6_i0UcaB0qsQqQbnkfou074/edit).
* Note that when the primary CTA is clicked, a spinner will be shown in the button while Consent Mode is enabled, after which the browser will navigate to the **Admin Settings** tab on the **Settings** screen.
* ~In order to test the multiple dismissals, please refer to the QAB for https://github.com/google/site-kit-wp/issues/7316.~ Upon review, it turns out the PR to make prompts work with the reference date was not merged, so the non-QA:Eng part of the QAB is not accurate.

**Please note that this change does introduce a slight glitch - when refreshing the dashboard, the page will not always scroll to the widget context that was previously scrolled into view. This is a known issue that doesn't need to block the release.** Update: Actually, I, @techanvil, have since tested this on InstaWP and TasteWP sites and the glitch isn't occurring. Seems only to be happening on my local dev environment, so maybe a non-issue, but one I will keep an eye on.

### QA:Eng:

* In order to test the multiple dismissals, please refer to the QA:Eng part of the QAB for https://github.com/google/site-kit-wp/issues/7316.

## Changelog entry

* Create conditional dashboard CTA for Consent Mode.

**Comment by techanvil** [comment]
This was moved directly to execution so as not to block the progress toward our hard delivery target for Consent Mode.

**Comment by techanvil** [comment]
This was moved directly to execution so as not to block the progress toward our hard delivery target for Consent Mode.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified CTA for consent mode banner.
- Verified A Consent Mode setup CTA banner shown on the main and entity dashboard.
- Verfied this  follow the [first iteration](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?type=design&node-id=1-14&mode=design&t=yIrMyTmdPhK0aEJ5-0) of the Figma design.
- Verified appear while Consent Mode is disabled and the user hasn't dismissed the banner.
- Verified primary CTA should enable Consent Mode, dismiss the banner and navigate to the Settings screen.
- Verified 'Learn more' link navigates user to Site kit [documentation](https://sitekit.withgoogle.com/documentation/) page.
- Verified when thhe Maybe later link is clicked then the CTA banner s disappear and a tooltip display. 


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e288ab02-c26c-4a56-be7c-1dae6455bc0e)

View Only Dashboard 

![image](https://github.com/google/site-kit-wp/assets/94359491/d0ca0c16-253f-456c-9df5-c0f5d18276b4)

Entity Dashboard

![image](https://github.com/google/site-kit-wp/assets/94359491/7fed0c90-a0a8-438d-9a4d-20a43f1a1f3b)

Other Admin

![image](https://github.com/google/site-kit-wp/assets/94359491/d85c9832-e19c-4f7e-b73b-288b3ec8624f)

Larger Desktop View

![image](https://github.com/google/site-kit-wp/assets/94359491/e01d3640-4fa1-43dc-80e4-04618de893fd)

Mobile View :

![image](https://github.com/google/site-kit-wp/assets/94359491/bfef97dd-f200-4b13-8deb-ad2e88228bdc)

Tablet View 


![image](https://github.com/google/site-kit-wp/assets/94359491/9be8226f-4c76-456f-87c0-091a3af52c9f)

Primary CTA 

https://github.com/google/site-kit-wp/assets/94359491/de9beda3-cbb1-4538-8f3c-6b1233f830c7

Maybe later CTA

https://github.com/google/site-kit-wp/assets/94359491/9cd950e7-cbeb-42d2-aab1-498c1dec7847

</details>

**Comment by mohitwp** [comment]
This is now ready for` QA:Eng` review to test the multiple dismissals

**Comment by tofumatt** [comment]
QA ✅ from me as well 👍🏻
