### ISSUE TITLE
Remove `consentMode` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8280]
## Feature Description

Unlike many other features, consent mode will be rolled out all at once by removing the feature flag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `consentMode` feature flag should be removed, along with all code execution paths where the flag is `false`.
* As a result the Consent Mode feature will be permanently active.

## Implementation Brief

* [ ] Remove the `consentMode` feature flag and associated negative-path code as per the AC.

### Test Coverage

* Fix any broken tests.
* Remove any unneeded tests.

## QA Brief

* Verify the `consentMode` feature flag has been removed, and the Consent Mode feature is unconditionally available.

## Changelog entry

* N/A

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verify the consentMode feature flag has been removed, and the Consent Mode feature is unconditionally available.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/71374d38-ba8c-4c88-8f6f-c90b6bdb5fc0)

![image](https://github.com/google/site-kit-wp/assets/94359491/3aaa30ad-a611-4632-a894-b8ebff56472e)

![image](https://github.com/google/site-kit-wp/assets/94359491/3deaa68c-fe1f-4eb3-9535-af5c3110ce64)

</details>
