### ISSUE TITLE
Introduce `conversionInfra` feature flag for Initial Conversion Events Infrastructure 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#8282]
## Feature Description

The work for initial conversion events infrastructure should be behind `conversionInfra` feature flag. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new feature flag `conversionInfra` should be added to Site Kit for the upcoming work on Initial Conversion Event Infrastructure. 

## Implementation Brief

* [ ] Add a `"conversionInfra"` entry to the `feature-flags.json` file, keeping the order of the feature flags alphabetical.

### Test Coverage

* No tests needed.

## QA Brief

* A `conversionInfra` feature flag should appear in the tester plugin.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
This one can safely be moved right to EB 🙂

**Comment by kuasha420** [comment]
Note for QA: we decided to shorten the feature flag to `conversionInfra`. Just noting here. Cheers!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that `"conversionInfra"` feature flag is appearing under feature flag list of tester plugin.


![image](https://github.com/google/site-kit-wp/assets/94359491/5cb64fdb-dffd-462c-8e75-a12f9aef68c3)
