### ISSUE TITLE
Add `ga4AdSenseIntegration` feature flag

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8288]
## Feature Description

We originally planned on releasing the GA4 + AdSense integration in this release (`1.121.0`) or the next (`1.122.0`). But because of the prioritisation of the `consentMode` feature, we'll be waiting a bit to release GA4 + AdSense integration.

To prevent users getting the prompt to connect their accounts (#8050), without it actually updating when their accounts _are_ linked (#8049), we should add a feature flag to prevent the Widget CTA (#8050) and the overlay CTA (#8236) from appearing when the feature flag is disabled.

We should also prevent #8050 and #8236 from rendering unless the feature flag is present.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A feature flag for GA4 AdSense Integration (`ga4AdSenseIntegration`) should be added to `feature-flags.json`
* The feature flag should appear in the Tester Plugin.
* The CTA widget to connect AdSense + Analytics accounts that appears when a user has both AdSense and Analytics enabled should not appear when the `ga4AdSenseIntegration` feature flag is disabled. It _should_ only appear when the feature flag is enabled.
* The "Top Earning Pages" Key Metric Tile should only appear when the feature flag is enabled.

## Implementation Brief

* [x] Add `ga4AdSenseIntegration` to `feature-flags.json`
* [x] Ensure widgets and KMW tiles are not registered when the feature flag is disabled.
* [x] Update #8236/#8237/#8238's ACs to ensure the overlay CTA only appears when the `ga4AdSenseIntegration` feature flag is enabled.
* [ ] Merge #8289

### Test Coverage

* None needed.

## QA Brief

* The `'ga4AdSenseIntegration'` feature flag should appear in the Tester Plugin.
* Follow the steps to QA #8050—with the feature flag enabled and disabled. When enabled, the prompt should appear (though note: it will still not update to the "linked" state until #8049 is merged). When the feature flag is disabled, the widget should **not** appear.
* Ensure the "Top Earning Pages" Key Metric Tile only appears when the `ga4AdSenseIntegration` feature flag is enabled with both AdSense and Analytics modules connected.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB + CR ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt I have tested 8288 for the `ga4AdSenseIntegration` feature flag. All looks good, but just one observation.  When the feature flag is disabled, the users will not see the Top Earning Pages widget, and the CTA to disable the widget no longer appears. See the screenshot of what appears on the latest branch.  I assume this is not an issue?

![image](https://github.com/google/site-kit-wp/assets/73545194/9f8e9526-256c-4175-8a25-bad4cc21bba4)

**Verified:**

- The `ga4AdSenseIntegration` feature flag appears in the Tester Plugin.
- With the feature flag enabled and disabled. When enabled, the prompt appears. When the feature flag is disabled, the widget does not appear.
- The `Top Earning Pages` Key Metric Tile only appears when the `ga4AdSenseIntegration` feature flag is enabled with both AdSense and Analytics modules connected.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/3ab7eeae-eb37-41d4-bcfe-c6e99fe566a2)
![image](https://github.com/google/site-kit-wp/assets/73545194/244b59b8-7a0d-4588-b86d-1fd4539bcb39)
![image](https://github.com/google/site-kit-wp/assets/73545194/bcf1333d-6ef9-47fb-b8cc-b12d3a393347)
![image](https://github.com/google/site-kit-wp/assets/73545194/23f4fccb-0d98-4b13-9064-7fe490ac5037)
![image](https://github.com/google/site-kit-wp/assets/73545194/6ee10cf1-215b-490c-901f-aa3fe67a6a8e)

</details>

**Comment by tofumatt** [comment]
@wpdarren That makes sense, it's what would have appeared before. All good 👍🏻

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `ga4AdSenseIntegration` feature flag appears in the Tester Plugin.
- With the feature flag enabled and disabled. When enabled, the prompt appears. When the feature flag is disabled, the widget does not appear.
- The `Top Earning Pages` Key Metric Tile only appears when the `ga4AdSenseIntegration` feature flag is enabled with both AdSense and Analytics modules connected.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/3ab7eeae-eb37-41d4-bcfe-c6e99fe566a2)
![image](https://github.com/google/site-kit-wp/assets/73545194/244b59b8-7a0d-4588-b86d-1fd4539bcb39)
![image](https://github.com/google/site-kit-wp/assets/73545194/bcf1333d-6ef9-47fb-b8cc-b12d3a393347)
![image](https://github.com/google/site-kit-wp/assets/73545194/23f4fccb-0d98-4b13-9064-7fe490ac5037)
![image](https://github.com/google/site-kit-wp/assets/73545194/6ee10cf1-215b-490c-901f-aa3fe67a6a8e)

</details>
