### ISSUE TITLE
Remove `ga4AdSenseIntegration` feature flag to launch GA4 + AdSense integration feature

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8290]
## Feature Description

We should remove the `ga4AdSenseIntegration` feature flag to deploy that feature fully to users in the `1.124.0` release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ga4AdSenseIntegration` feature flag should be removed from the plugin.
* With the feature flag removed, code should be updated where needed so that it functions as-if the feature flag were enabled. Essentially, `ga4AdSenseIntegration` should act like it's always on.
* Any tests that rely on `ga4AdSenseIntegration` should continue to pass.
* Any code/tests that rely on `ga4AdSenseIntegration` being _disabled_ can be removed.

## Implementation Brief

* [ ] **Removal from Feature Flags**: Remove the `ga4AdSenseIntegration` from the `feature-flags.json` file.
* [ ] **Code Search and Review**: Conduct a thorough search throughout the code base for the `ga4AdSenseIntegration` string. Examine each instance where it is used.
    * [ ] For any logic or component/widget rendered conditionally based on the `ga4AdSenseIntegration` feature flag, adjust the code to ensure these are rendered unconditionally.
    * [ ] Search for and remove any instances where the `isFeatureEnabled( 'ga4AdSenseIntegration' )` utility function is used.
    * [ ] Any code segments that were executed only when the feature flag was disabled should now be removed entirely.
* [ ] **Removal of Hook Usage**: Search for and remove any instances where the `useFeature` hook is utilized with `ga4AdSenseIntegration` as an argument.
* [ ] **Removal from Server Logic**:
    * [ ] Search for and remove any instances where the `Feature_Flags::enabled( 'ga4AdSenseIntegration' )` method is used in server logic.
    * [ ] Search for and remove any instances where the `enable_feature( 'ga4AdSenseIntegration' )` method is used in PHP test files.
    * [ ] Note: I couldn't find any server logic that uses the `ga4AdSenseIntegration` feature flag. However, it is better to double-check this.
* [ ] **Story Parameters Update**: Scrutinize the story parameters in which the `ga4AdSenseIntegration` feature is activated. Here, it is necessary to remove this particular parameter.

### Test Coverage

* [ ] Review and update the VRT images as required to ensure they align with removing the `ga4AdSenseIntegration` feature flag.

## QA Brief

* The `ga4AdSenseIntegration` feature flag should not appear in the list of feature flags when using the tester plugin.
* Testing this issue realistically involves going through all flows for GA4 + AdSense integration, see this doc: https://docs.google.com/document/d/1FtdDt1_AMe9sE-sEkA_ZjWSEhhthkOJi_aLRdr5vHD0/edit?usp=sharing

Essentially: test that GA4 + AdSense features appear _without_ the `ga4AdSenseIntegration` being enabled.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
(I realised today this is actually due for the next sprint, but leaving it assigned to me as I've nearly completed the issue already 😅)

**Comment by kuasha420** [comment]
@tofumatt Can you add a QAB here - as you have more context about the whole thing and may want to get some specific stuff QA'd. Feel free to unassign yourself afterwards. Cheers.

**Comment by tofumatt** [comment]
@kuasha420 Oh my, I just totally forgot, yes! Thanks 😅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The ga4AdSenseIntegration feature flag should not appear in the list of feature flags when using the tester plugin.
- I reviewed the testing notes and ensured all functionality was working as expected.  I did spot a few issues, but these were fixed as part of the 1.124.0 release or are post-launch. 

<details>
 <summary>Screenshots</summary>
 ...collapsible content...
</details>
