### ISSUE TITLE
Error : Getting token failed when setting up Site Kit

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#8299]
## Bug Description

After going through OAuth as part of the Site Kit plugin setup, you will encounter one of the following errors:

- Error : Getting token failed
- Error : Getting credentials failed

This stops all users from being able to set up the plugin at this time. A console error also accompanies the on screen error message:

![image](https://github.com/google/site-kit-wp/assets/91896826/fb19d205-d58c-4573-ae54-6a35a1b956ad)

Errors may also be found on the Site Kit dashboard for sites that have it already set up as can be seen here:

![image](https://github.com/google/site-kit-wp/assets/91896826/bf4b1254-f3ae-4bea-89f5-b6f7a0b426df)

We have already received multiple reports of this in the support forum with some examples below:

1. https://wordpress.org/support/topic/getting-token-failed/
2. https://wordpress.org/support/topic/error-getting-token-failed-3/
3. https://wordpress.org/support/topic/error-getting-token-failed/

This is reproducible on all sites that I have tried to set up Site Kit on. 

## Steps to reproduce

1. With a fresh website, install Site Kit
2. Attempt set up of the plugin

## Screenshots

Screenshots shared above

## Additional Context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
@adamdunnage, i am going to close this issue in favor of an asana task.
