### ISSUE TITLE
Add GA event tracking for Consent Mode on the dashboard

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8303]
## Feature Description

GA events should be added to keep track of Consent Mode interaction on the dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given Consent Mode actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307&range=347:349).

Event Name | Category | Trigger | Condition
-- | -- | -- | --
view_notification	| {viewContext}_CoMo-ads-setup-notification	| Element visibility | User views the setup CTA for advertisers 
confirm_notification | {viewContext}_CoMo-ads-setup-notification	| Click	| User clicks "Enable consent mode" CTA
dismiss_notification|	{viewContext}_CoMo-ads-setup-notification	| Click	| User clicks "Maybe later" CTA

## Implementation Brief

* [ ] Update the setup CTA introduced in https://github.com/google/site-kit-wp/issues/8279 to dispatch tracking events as per the AC.

### Test Coverage

* No additional tests needed.

## QA Brief

* Enable the `consentMode` feature flag, ensure that the Consent Mode `enabled` setting is `false` and the Ads Conversion ID is set.
* Verify that GA events are tracked for the Consent Mode setup banner as per the AC.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
AC + IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that all events are appearing as per AC.
- Verified event name, category and Trigger.

**_View_notification_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/82e8c1c9-dfc6-44e0-b45d-c89256c7474a)

![image](https://github.com/google/site-kit-wp/assets/94359491/27642af5-89b8-4b1e-944f-18cd911885e3)

![image](https://github.com/google/site-kit-wp/assets/94359491/ae21a473-6474-49f4-9cb3-319efd0a353f)

![image](https://github.com/google/site-kit-wp/assets/94359491/c2cbd349-ade4-490c-890a-f6026df39307)

</details>

**_confirm_notification_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/f98d76db-3b36-496e-a0c1-657c4220bc6c)

![image](https://github.com/google/site-kit-wp/assets/94359491/3d522d42-f8a1-40fc-aa4f-317ad1861508)

![image](https://github.com/google/site-kit-wp/assets/94359491/7198d803-a673-49b5-9835-0150cab4956c)

![image](https://github.com/google/site-kit-wp/assets/94359491/9380e9be-4335-4101-b4c8-9a27e1d4e74d)

</details>

**_dismiss_notification_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/b82e95c0-e609-4dd0-86e4-ec04c641ae6b)

![image](https://github.com/google/site-kit-wp/assets/94359491/01e37271-2bf8-45b0-8e0f-d14ad6a3871d)

![image](https://github.com/google/site-kit-wp/assets/94359491/69a39062-4c66-4a8c-b6ba-661892e89496)

</details>
