### ISSUE TITLE
Add GA event tracking for Consent Mode on the Settings page

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8304]
## Feature Description

GA events should be added to keep track of Consent Mode interaction on the Settings page.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given Consent Mode actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307&range=350:359).

Event Name | Category | Trigger | Condition
-- | -- | -- | --
view_requirements | {viewContext}_CoMo | Element visibility |	User views the Settings screen									
wp_consent_api_install | {viewContext}_CoMo | Click |	User clicks "Install" CTA for the WP Consent API 	
wp_consent_api_activate | {viewContext}_CoMo | Click |	User clicks "Activate" CTA for the WP Consent API 									
wp_consent_api_active | {viewContext}_CoMo | Element visibility |	User views screen where SK sucessfully detected WP consent API 									
como_learn_more | {viewContext}_CoMo | Click | User clicks the "Learn more" link in the CoMo settings screen. 									
wp_consent_api_learn_more | {viewContext}_CoMo | Click | User clicks the "Learn more" link for the WP consent API									
consent_mgmt_plugin_learn_more | {viewContext}_CoMo | Click |	User clicks the "See suggested plugins" link for the Consent management Plugin									
como_disable | {viewContext}_CoMo | Click |	User clicks the toggle to disable consent mode 									
view_modal | {viewContext}_CoMo | Element visibility | User views the modal to disconnect consent mode									
confirm_disconnect | {viewContext}_CoMo | Click |	User clicks "Disable" CTA confirming they want to disconnect concent mode									
cancel_disconnect | {viewContext}_CoMo | Click | User clicks "cancel" and returns to settings 									

## Implementation Brief

* [ ] Update the Settings section introduced in https://github.com/google/site-kit-wp/issues/8278 to dispatch tracking events as per the AC.

### Test Coverage

* No additional tests needed.

## QA Brief

* Set up Site Kit and enable the "Consent Mode" feature flag
* Ensure you have the Google Analytics Debugger Chrome Extension installed and have Site Kit set up to track Analytics events in "Settings > Tracking".
* All events should be sent using the category `'settings_CoMo'` and the following actions:
  * View Site Kit Settings > Admin to see the Consent Mode settings: `'view_requirements'`
  * Click the "Install" button under the "Install WP Consent API": `'wp_consent_api_install'`
  * View Consent Mode settings after the WP Consent API plugin is installed and detected: `'wp_consent_api_active'`
  * Clicking "Learn more" here should trigger `'como_learn_more'`:
![Screenshot 2024-03-05 at 21 35 30](https://github.com/google/site-kit-wp/assets/90871/cb2bccb3-1bbd-4d40-8b2f-752d5ef0165c)
  * Clicking "Learn more" here should trigger `'wp_consent_api_learn_more'`:
![Screenshot 2024-03-05 at 21 36 33](https://github.com/google/site-kit-wp/assets/90871/42bdf08c-b6fe-4363-b807-7aa7ac5643e6)
  * Clicking "See suggested plugins" link should trigger `'consent_mgmt_plugin_learn_more'`
* Enable Consent Mode
  * After enabling Consent Mode, click the toggle again to disable it. You should trigger `'como_disable'`, then `'view_modal'`
  * Cancel the modal that appears so you don't disable Consent Mode. You should trigger `'cancel_disconnect'`
  * Disable Consent Mode again, but this time select "Disable" when the modal appears. You should trigger `'confirm_disconnect'`
* Enable Consent Mode again
  * After installing and activating the WP Consent Mode API Plugin, deactivate the plugin in WP Plugin settings then return to Site Kit Settings > Admin > Consent Mode. Click thte "Activate" button under the "Activate WP Consent API": `'wp_consent_api_activate'`

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
AC + IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

I went through all of the GA Events in the AC and can confirm that they are all triggered. See screenshots. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/356f38bc-1763-47b8-a589-dee806a383d0)
![image](https://github.com/google/site-kit-wp/assets/73545194/736e6a63-3f98-47b0-a76a-6d2047f974d8)
![image](https://github.com/google/site-kit-wp/assets/73545194/90d5f4ed-0af4-4897-a989-c43181538aa5)
![image](https://github.com/google/site-kit-wp/assets/73545194/2ade29f3-f404-4be1-9dd7-cb64995ea4fe)
![image](https://github.com/google/site-kit-wp/assets/73545194/47991ec4-d85e-409c-88a8-2b24cacf4b23)
![image](https://github.com/google/site-kit-wp/assets/73545194/0fc35fa4-2e18-4220-bef4-3069981004bc)
![image](https://github.com/google/site-kit-wp/assets/73545194/49687b86-e9d1-4c62-94ce-5b3bff8c7744)
![image](https://github.com/google/site-kit-wp/assets/73545194/bebadde8-b9e8-4386-8378-8cd253ad60d4)
![image](https://github.com/google/site-kit-wp/assets/73545194/67f3512c-286f-4343-a559-8fe9fb2ea6f7)
![image](https://github.com/google/site-kit-wp/assets/73545194/5162786d-d1dd-4af7-beac-beac732f0141)
![image](https://github.com/google/site-kit-wp/assets/73545194/48754b04-1fee-4b28-a5cd-27d665fb0969)
![image](https://github.com/google/site-kit-wp/assets/73545194/8399e832-a2e1-48a0-bafe-45ca6c45b292)

</details>
