### ISSUE TITLE
Launch the Single Analytics Module

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8306]
## Feature Description

This issue will track the progress of the newly created [feature branch](https://github.com/google/site-kit-wp/tree/feature/singular-analytics-module) for the final SAM issues (#7932, #8082 and  #7843). Since the PRs of these individual issues should be merged into develop/main at the same time, we have decided to merge them into the feature branch instead. Also, the individual PRs are very large and the code within them is not wrapped with any feature flag. So the feature branch and this issue will help us to thoroughly QA the feature branch that will effectively be merged into develop and "launch" SAM in Release 1.123.0.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Successfully remove and replace the old Analytics module with the Analytics-4 module (SAM epic). As such, the ACs of the following 3 issues should be met:
  * #7932 
  * #8082
  * #7843 

## Implementation Brief

* [ ] Thoroughly QA and merge the [feature branch](https://github.com/google/site-kit-wp/tree/feature/singular-analytics-module) once all the PRs of the issues within the AC have been merged.

### Test Coverage

* No new tests required.

## QA Brief

* Refer to the QAB of the individual issues in the ACs. A test plan is also being created to thoroughly test the Google Analytics module within the Site Kit plugin. Any specific scenarios or test cases can be added here but should be included in that test plan for the QA team to go through.

## Changelog entry

* Refactor Site Kit to use a singular Analytics module.

**Comment by bethanylang** [comment]
Noting that this does not have an estimate as there's no engineering work required here; this is for QA to complete final E2E testing for the remaining Singular Analytics Module issues on the feature branch. cc @aaemnnosttv @wpdarren @ivonac4 @mohitwp

**Comment by nfmohit** [comment]
As very kindly pointed out by @kuasha420 internally, I've added a changelog entry to this issue as otherwise, it may cause the release script to break while preparing the release. Thanks!
