### ISSUE TITLE
Update WP Consent API plugin detection to account for non-standard location

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8307]
## Feature Description

As mentioned in this https://github.com/google/site-kit-wp/pull/8305#discussion_r1499937157, it's possible for the WP Consent API plugin entry point to reside in a location other than `wp-consent-api/wp-consent-api.php`.

https://github.com/google/site-kit-wp/blob/b19bdd5bf6c3e0b53d3a157022927672c9df88b3/includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php#L143-L144

We should update the above code to account for alternative locations for the plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Consent Mode controller should detect that the Consent API plugin is installed, even if it was installed via Composer or into a custom WordPress plugin folder and use the correct path to the plugin file.

## Implementation Brief

* [ ] Update the `core/site/data/consent-mode` REST route `includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php`:
   * [ ] Replace the `$slug` and `$plugin` variables with a single new variable called `$plugin_uri` with the value of `https://wordpress.org/plugins/wp-consent-api`. *This is the URI of the plugin which won't change even if the plugin folder or main file changes.*
   https://github.com/google/site-kit-wp/blob/cc356a6a97916db3f2eac54987e886917cee916e/includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php#L155-L156
   * [ ] Create the `$slug` and `$plugin` variables as empty strings to set later based on dynamic plugin values.
   * [ ] Update the install check block:
   https://github.com/google/site-kit-wp/blob/cc356a6a97916db3f2eac54987e886917cee916e/includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php#L166-L171
      * [ ] Get the key and value in the foreach `get_plugins() as $plugin_file => $installed_plugin`.
      * [ ] Remove the `array_keys` function so that the loop gets the full plugin objects.
      * [ ] Update the check condition to `$installed_plugin["PluginURI"] === $plugin_uri`.
         * [ ] Set the `$slug` variable using `$installed_plugin["TextDomain"]`.
         * [ ] Set the `$plugin` variable using `$plugin_file`.
   * The response block will now use the `$slug` and `$plugin` variables set based on the WordPress plugin data above, no changes required:
   https://github.com/google/site-kit-wp/blob/cc356a6a97916db3f2eac54987e886917cee916e/includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php#L177-L184

### Test Coverage

* Confirm existing phpunit tests pass.

## QA Brief

* Setup and configure a basic Site Kit installation
* Manually download the WP Consent API plugin from https://wordpress.org/plugins/wp-consent-api/
* Extract it to your plugins folder in a randomly named folder, i.e `wp-content/plugins/test-consent-plugin`
* Navigate to `Site Kit > Settings > Admin Settings`
* Under `Consent Mode`, enable said feature
* Validate that the `Activate` CTA button shows as per the screenshot below:

<img width="613" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/ccf5e927-f9fd-4f93-9025-4dc0af1d01d1">

* Validate that, upon clicking said CTA, the WP Consent API plugin is successfully activated
* Validate that, upon returning to `Site Kit > Settings > Admin Settings`, the Consent mode notice indicates the successful presence of the plugin as per the screenshot below:

<img width="612" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/1c9c6b0f-f338-4e09-9ad2-a2c7a354d611">

* Deactivate and delete the plugin
* Ensure that the installation and activations steps for the plugin can be performed in `Site Kit > Settings > Admin Settings`

## Changelog entry

* Detect WP Consent API plugin even when it's installed in a non-standard folder name.

**Comment by eugene-manuilov** [comment]
AC ✔️, I have adjusted it a bit to add a note that the controller should use the right path to the plugin.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested using File manager plugin.
- Tested by creating custom folder as mentioned in QAB.
- Verified that the Consent Mode controller detect that the Consent API plugin is installed, even if it was installed via Composer or into a custom WordPress plugin folder and use the correct path to the plugin file.
- Verified that plugin installation and activation is working as expected in case of installation through custom folder or directly through `Site Kit > Settings > Admin Settings.`

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/63c098c0-4b79-491a-8c14-43f85e4eec00)

![image](https://github.com/google/site-kit-wp/assets/94359491/c0014908-9200-41ce-b4d7-b888ae600ef9)


![image](https://github.com/google/site-kit-wp/assets/94359491/85c7d9fe-4fd3-447a-bf40-800b8a8b7212)


https://github.com/google/site-kit-wp/assets/94359491/c5afaa8f-1a33-4306-95e7-d9e930ad1436

</details>

**Comment by wpdarren** [comment]
@mohitwp as per my conversation on Slack.  I am a little paranoid with this feature due to past issues 😄 so could you test the sceario in the QAB, but also check that the snippet still appears in the source code and ensure that tracking is working as expected for EU and Non EU traffic.  More info on the snippet can be found in the [testing instructions](https://docs.google.com/document/d/1-kNcEPgrJO5NJUbULOsi6_i0UcaB0qsQqQbnkfou074/edit#heading=h.mxpfv9srreyb). Let me know if you have any questions.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- - Tested on dev environment.
- - Tested using File manager plugin.
- - Tested by creating custom folder as mentioned in QAB.
- - Verified that the Consent Mode controller detect that the Consent API plugin is installed, even if it was installed via Composer or into a custom WordPress plugin folder and use the correct path to the plugin file.
- - Verified that plugin installation and activation is working as expected in case of installation through custom folder or directly through `Site Kit > Settings > Admin Settings.`
- Verified that tracking is working as expected for Non EU and EU members including UK.



<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/63c098c0-4b79-491a-8c14-43f85e4eec00)

![image](https://github.com/google/site-kit-wp/assets/94359491/c0014908-9200-41ce-b4d7-b888ae600ef9)


![image](https://github.com/google/site-kit-wp/assets/94359491/85c7d9fe-4fd3-447a-bf40-800b8a8b7212)


https://github.com/google/site-kit-wp/assets/94359491/c5afaa8f-1a33-4306-95e7-d9e930ad1436

</details>

- Verified that if consent mode is enabled snippet is showing under source code.

<details>

https://github.com/google/site-kit-wp/assets/94359491/f58c36a7-6421-4d60-b39c-630adcdc51f5

![image](https://github.com/google/site-kit-wp/assets/94359491/5f201302-0ce5-457e-aedc-c26016eb4642)

</details>

- Verified that consent mode snippet is not showing if consent mode is not enabled.

<details>


https://github.com/google/site-kit-wp/assets/94359491/f1b1e21f-be10-4990-836c-4e8c8e8c90cd

</details>

- Verified GA events related to WP constant API plugin activation and other Consent mode GA events listed under testing instructions.

<details>


![image](https://github.com/google/site-kit-wp/assets/94359491/6536d582-095f-4495-be70-e674cb3c6bb9)

![image](https://github.com/google/site-kit-wp/assets/94359491/cfa8ca0f-43d8-46f6-9490-617b658a9ee0)

![image](https://github.com/google/site-kit-wp/assets/94359491/beb23e5a-c20f-482e-9d7e-b3f3f7415dff)

![image](https://github.com/google/site-kit-wp/assets/94359491/019f75c0-bf47-4943-a772-8622fe99f9a4)

![image](https://github.com/google/site-kit-wp/assets/94359491/97f652fc-2be8-42a4-b294-c65ea59df476)

![image](https://github.com/google/site-kit-wp/assets/94359491/1c709f0f-6138-481d-8eda-19857622fe99)

![image](https://github.com/google/site-kit-wp/assets/94359491/9ed2f55c-50c8-4762-8363-45a1da77fa3a)

![image](https://github.com/google/site-kit-wp/assets/94359491/3e7db2bb-7ba3-4614-ac44-19b9746e6a9a)

![image](https://github.com/google/site-kit-wp/assets/94359491/18adbc8e-1afb-4977-bf3f-78adb33be8d1)


</details>

**Comment by aaemnnosttv** [comment]
## ⚠️ Approval

There is a small change we should make to the implementation here. See https://github.com/google/site-kit-wp/pull/8959#pullrequestreview-2175494399

I can raise a quick follow up here if needed.

**Comment by nfmohit** [comment]
> ## ⚠️ Approval
> There is a small change we should make to the implementation here. See [#8959 (review)](https://github.com/google/site-kit-wp/pull/8959#pullrequestreview-2175494399)
> 
> I can raise a quick follow up here if needed.

I've created a [follow-up PR](https://github.com/google/site-kit-wp/pull/9010).

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit, this has been merged and tested so this is good to go 👍 

It's worth noting that this issue's changes were somehow reverted (no longer in main or develop) in https://github.com/google/site-kit-wp/commit/9ab0412a6047e43781a011d06293adfedea7001e after it had gone through QA, so the follow-up PR actually re-introduced the change while addressing the points I raised.
