### ISSUE TITLE
Tracking opt-out snippet outputs even when `Exclude Analytics` setting is off

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8309]
## Bug Description

When the "Exclude Analytics" setting switches are both turned off, the tracking opt-out snippet still renders in the connected site's source code.

## Steps to reproduce

1. Go to Analytics Settings and disable both switches under the "Exclude Analytics" setting.
2. Go to the site on which Site Kit is installed and view source on any page.
3. The Google Site Kit opt-out code snippet is appearing when it should not.

## Screenshots

https://github.com/google/site-kit-wp/assets/73545194/572592b9-647d-4c5a-a13c-f1336b97f7b6

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the "Exclude Analytics" settings switches are turned off in Analytics Settings, the Analytics opt-out code snippet should not be inserted in the site's source code.

## Implementation Brief

* [ ] Within `includes/Modules/Analytics_4.php`:
    * [ ] In the `is_tracking_disabled()` method, we are currently using the `trackingDisabled` setting from the `analytics-4` module but when saving the setting in the `SettingsEdit` form, we save it to the original `analytics` module. So as a temporary fix, fetch the setting from the original Analytics class until 7932 is fully merged.

This [PR](https://github.com/google/site-kit-wp/pull/8310) implements the above fix. Please CR it at the same time if the IB looks good.

### Test Coverage

* No new tests required.

## QA Brief

* Follow the steps to reproduce and verify that the opt-out tag is not rendered when both switches are off and is rendered for either all logged in users or editors only. 
* Perform a regression test for this "Excluded Analytics" setting when connecting GA from scratch after a SK reset and editing existing GA settings as well.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB here makes sense I think, as pointed out by @jimmymadon this is temporary until the `1.123.0` release with Singular Analytics Modular, so this is probably the best fix for now/so close to the release 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

Excluded from Analytics:
- When set to `Analytics is currently enabled for all visitors` the opt-out snippet does not appear as expected. 
- When set to `Users that can write posts` the opt-out snippet does appear as expected. 
- When set to `All logged-in users` the opt-out snippet does appear as expected. 
- Performed a regression test for this "Excluded Analytics" setting when connecting GA from scratch after an SK reset and editing existing GA settings.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/f5c34cb4-a716-4240-af21-26417f90362b)
![image](https://github.com/google/site-kit-wp/assets/73545194/78e2f148-194e-493c-b397-b26c5ac455b6)
![image](https://github.com/google/site-kit-wp/assets/73545194/aedb5aad-b64e-4a9c-8270-48342e09f7c0)

</details>
