### ISSUE TITLE
Consistently clear user credentials if refreshing a token fails

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#831]
## Bug Description

Whenever refreshing a token fails because of the token being invalid or expired (response error: `invalid_grant`), we need to delete the user credentials because they're invalid. We currently do that in parts, but there are two major flaws:

1. We only do that when refreshing a token on user login, but not on other regular refresh requests which happen when the token has expired. If the user has an invalid refresh token, this causes new (unsuccessful) refresh attempts basically on every admin pageload.
2. We try to revoke the token without catching exceptions. In most cases, revoking such a token will fail (because it is invalid). While the `Google_Client` doesn't throw any exceptions during that process, the underlying HTTP request handler from guzzle might - and if that happened, the credentials wouldn't be deleted because of the uncaught exception.

While we're at it, we can also ensure that only the user credentials are wiped at that stage, we don't need to remove the other data for the user (e.g. their site verification token).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User credentials should be revoked and deleted from the DB in every situation where the request to refresh the access token fails with `invalid_grant` error or `refresh_token_not_exist` error.
* When revoking a token, exceptions should be caught so that the user credentials can be wiped afterwards.

## Implementation Brief

* Merge #830

## Changelog entry

* Fix critical issue where an invalid refresh token would not revoke the current token, resulting in recurring requests with further attempts.

**Comment by ThierryA** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
CR ✅ 
Back to you @felixarntz

**Comment by felixarntz** [comment]
In order to QA this issue, please do the following:
1. Set up the plugin as usual.
2. Manually go to your database to the `wp_usermeta` table and change your `wp_googlesitekit_access_token_expires_in` meta value to something like 0 (so that it is considered expired in combination with the existing `...created` value). Take note of the current access token stored there.
3. Go to some page of Site Kit.
4. Check that there's now another access token stored for that user and the expiry value is changed to something new (should typically be something <= 3600).

Then, perform the above steps again, but before step 2, log out of WordPress, and instead of step 3, log back in.

Then, manually edit the codebase of Site Kit in `OAuth_Client::refresh_token()` so that the `try` clause throws a `new \Exception( 'invalid_grant' )`, and perform the original steps again. Instead of a new token, your next page load (of a non Site Kit screen) should show an admin notice that refreshing the token failed. The database should no longer have any credentials stored.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

1. ☑️ Set up the plugin as usual.
1. ☑️ Manually go to your database to the `wp_usermeta` table and change your `wp_googlesitekit_access_token_expires_in` meta value to something like 0 (so that it is considered expired in combination with the existing ...created value). Take note of the current access token stored there.
1. ☑️ Go to some page of Site Kit.
1. ☑️ Check that there's now another access token stored for that user and the expiry value is changed to something new (should typically be something <= 3600).
1. ☑️ Then, perform the above steps again, but before step 2, log out of WordPress, and instead of step 3, log back in.
1. ☑️ Then, manually edit the codebase of Site Kit in `OAuth_Client::refresh_token()` so that the try clause throws a `new \Exception( 'invalid_grant' )`, and perform the original steps again.   
Instead of a new token, your next page load (of a non Site Kit screen) should show an admin notice that refreshing the token failed. The database should no longer have any credentials stored.

**Comment by tofumatt** [comment]
QA failed for me, on the last step.

After installing the plugin I saw this error:

<img width="339" alt="Screenshot 2019-11-12 14 04 44" src="https://user-images.githubusercontent.com/90871/68679196-51269c80-0557-11ea-8877-2481c060c2fa.png">

After completing the steps and navigating to another page I didn't see a specific error about the auth token, but instead saw this error:

<img width="1151" alt="Screenshot 2019-11-12 14 17 38" src="https://user-images.githubusercontent.com/90871/68679254-6bf91100-0557-11ea-888e-bd9bdcbc883e.png">

I could still access the dashboard, but accessing the search console page showed me this error:

<img width="819" alt="Screenshot 2019-11-12 14 18 00" src="https://user-images.githubusercontent.com/90871/68679284-79ae9680-0557-11ea-87c2-486275de447b.png">

**Comment by tofumatt** [comment]
Oddly enough, after I went to the plugins list page I saw the intended message:

<img width="859" alt="Screenshot 2019-11-12 at 14 21 56" src="https://user-images.githubusercontent.com/90871/68679449-ca25f400-0557-11ea-8cc8-536959a65b5c.png">

🤔

**Comment by tofumatt** [comment]
I'm going to try QAing this again on a new site, maybe something unrelated was wrong? 🤷‍♂

**Comment by tofumatt** [comment]
Huh, I think something might've been up with that Jurassic Ninja install, because I just tried it on a new one and:

* I didn't receive the weird "code" error.
* All QA steps worked as @aaemnnosttv described.

So QA ✅ from me as well.
