### ISSUE TITLE
Tagmanager error:"Not found or permission denied." console error showing when user selects different tag manager a/c.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#8316]
## Bug Description

On selecting different tag manager a/c from drop down during Tag manager set up or after set up under settings throw console error. 
`googlesitekit-api-6b06a5c9b165bf7e28a4.js:3 Google Site Kit API Error method:GET datapoint:live-container-version type:modules identifier:tagmanager error:"Not found or permission denied."`

It is confusing because when I selected one a/c as you can see in below screenshots. No console error appear. After selecting another a/c when I selected that a/c again then console error appeared for the same a/c.
## Steps to reproduce

1. Set up tag  manger. 
2. Open console and during set up change tag manager a/c.
3. See error. 

OR

1. Set up tag manger. 
2. After set up open tag manager settings in edit mode.
3. Select different tag manager a/c from drop down. 
4. See error. 
5. Clear console while switching a/c.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/94359491/50966090-4549-43a8-ad14-e54ea8939c97)

![image](https://github.com/google/site-kit-wp/assets/94359491/fb9fd9f2-457c-4552-8d6f-a9111d0ce4fb)

https://github.com/google/site-kit-wp/assets/94359491/0734bba9-edd1-4b8c-8b26-28f87c403c6d

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No console errors should be raised when switching selected accounts in the setup or settings screens for Tag Manager

## Implementation Brief

The problem seems to be that the request for the live container version is triggered as soon as the new `accountID` is set, but the old `internalContainerID` is still set. 

See

- https://github.com/google/site-kit-wp/issues/6818
- https://github.com/google/site-kit-wp/blob/6ea9e6935ab149a576e9ee4c90414e0aa5fc3b4b/assets/js/modules/analytics-4/datastore/properties.js#L500-L505

* [ ] Update `selectAccount` to set the `accountID` and reset other IDs all at once using `setSettings` instead of individual setters
* [ ] Finish (if necessary) and merge https://github.com/google/site-kit-wp/pull/8318

### Test Coverage

* No changes expected

## QA Brief

* Open the Browser Console.
* Select a Tag Manager account, then select a different account during setup or on the settings edit screen.
* There should be no "Not found or permission denied." console error.

## Changelog entry

* Fix bug that caused browser console error to appear when changing Tag Manager account in Tag Manager setup/settings.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This is verified good as follows:

- Tested on MacOS Ventura Chrome on WP 6.4.3 and both PHP 8.0 and PHP 7.4
- Tested on MacOS Ventura Firefox, Safari and also Windows 11 Edge on WP 6.4.3 and PHP 8.0
- Results are as expected with no console errors when updating the different Gtags
- Saving a new tag also doesn't result in any error.
- Video is attached for reference

Moving this ticket to 'Approval' column.

<Details>
<summary>Video Reference</summary>

https://github.com/google/site-kit-wp/assets/125576926/3178aedf-2c7d-468b-9320-1e74ddbe1e4a

</details>
