### ISSUE TITLE
Move `tail` warning out of the WP debug log ignore list.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8319]
## Feature Description

During the development of https://github.com/google/site-kit-wp/issues/8275, it was observed that the [`tail command`](https://github.com/google/site-kit-wp/blob/a78b815847560882112d237e8decc3e915399881/bin/local-env/docker-compose.yml#L32) used for tailing the WP debug log has started outputting a warning to the debug log.

In the interests of expediency this was added to [`logIgnoreList`](https://github.com/google/site-kit-wp/blob/5287307382d7c0d16dff1344836157991f953b31/tests/e2e/config/wordpress-debug-log/log-ignore-list.js#L25-L37), however this is not the idea place to ignore the warning as it's a test infrastructure rather than WP-side warning.

We should either prevent this warning from being emitted, or ignore it outside of this list e.g. in `tests/e2e/config/wordpress-debug-log/index.js`.

See https://github.com/google/site-kit-wp/pull/8308#discussion_r1500891111

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@techanvil I know you've been busy with CoMo, but noticed that this is a P0 – @aaemnnosttv @ivonac4 should we try to move this forward for Sprint 123?

**Comment by techanvil** [comment]
Hey @bethanylang, thanks for flagging this. Not sure what happened, user or Zenhub error, but I didn't actually mean to tag it a P0. This is not such a high priority issue, P1 or even a P2 would suffice. I will change it to a P1 for now.

**Comment by bethanylang** [comment]
@techanvil That works too, thank you!
