### ISSUE TITLE
sign-in with google [ERROR]

### ISSUE THREAD

**Issue by godoffunk** [google/site-kit-wp#832]
Hi, I’ve installed the Site Kit plugin from the WordPress Plugin repository, I have the latest version of WP, PHP7.3 and the plugin and when i click on Sign in with Google, I get the following error:

An error occurred: We are unable to send credentials to your WordPress site. This is likely due to your hosting provider blocking incoming REST API requests. Please check with them if that is the case.
https://imgur.com/a/xdHxBcg

**Comment by ernee** [comment]
Hi @godoffunk please note that Site Kit support has moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Please submit a new topic there and we'd be happy to assist you.
