### ISSUE TITLE
Analytics Activation: 'redirect_uri' mismatch

### ISSUE THREAD

**Issue by reubenjlau** [google/site-kit-wp#833]
I'm having some problems with activating Analytics.  

When clicking on Analytics -> Connect Service I see:
'redirect_uri' mismatch

I'm using HTTPS for this site, and can confirm within WordPress settings, both the WordPress Address, and Site Address are showing HTTPS.

**Comment by ernee** [comment]
Hi @reubenjlau please note that Site Kit support has moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Please submit a new topic there and we'd be happy to assist you.
