### ISSUE TITLE
Do not show `SubtleNotification` when Overlay Notification is showing

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8335]
## Feature Description

#8236 implements the mechanism which handles overlay notifications status (showing/not showing), and ensuring that only one is showing at the time, using `isShowingOverlayNotification` value from `CORE_UI` datastore. #8238 subtle notification should not be showing if overlay notification is showing. This can be implemented with `isShowingOverlayNotification` selector, and issue should include proper test coverage for updated subtle notification conditional check.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
Closing as this is part of the ACs in #8236.
