### ISSUE TITLE
interfears with commerce7. When active commerce7 intergration stops working,

### ISSUE THREAD

**Issue by thelittlewineguy** [google/site-kit-wp#834]
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by thelittlewineguy** [comment]
I have not investigated fully, but as soon as plugin was installed and activated, eCommerce stopped working.

**Comment by ernee** [comment]
@thelittlewineguy thanks for your report! Support has moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). We're very interested in investigating this issue. If you could provide any known details about your experience (configurations in the Site Kit and commerce7, steps you took to identify the issue, etc.) in a new topic there that would be great. Thanks again!
