### ISSUE TITLE
Always require reconnecting

### ISSUE THREAD

**Issue by phpbits** [google/site-kit-wp#835]
## Bug Description
I have the beta version on all my websites and upon updating or reinstallation of the wordpress.org version it always requires me to Reconnect and Setup again. Is this a bug or intentional?

**Comment by ernee** [comment]
hi @phpbits  please note that Site Kit support has moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Please submit a new topic there and we'd be happy to assist you.
