### ISSUE TITLE
Implement HaTS survey triggers for Consent Mode

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8353]
## Feature Description

With the rollout of Consent Mode, we want to be able to collect feedback from users who use it, so we'll be adding a few triggers for surveys related to the feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New survey triggers should be fired as follows:
	* `enable_como`: triggered when the Consent Mode is enabled
		* Dashboard CTA
		* Toggle on Admin Settings tab
	* `view_como_setup_cta`: triggered when a Consent Mode setup CTA is viewed
		* Dashboard CTA
		* Toggle on Admin Settings tab **(only when "recommended" and the toggle is in the _off_ position)**
* View triggers should only be triggered at most once per day and ensure the target is in the viewport, not just rendered

## Implementation Brief

* [ ] Make use of `SurveyViewTrigger` or `triggerSurvey()` as appropriate in the components `ConsentModeSetupCTAWidget` and `SettingsCardConsentMode` to trigger the surveys as per the AC.
* [ ] Use a survey `ttl` of `DAY_IN_SECONDS` to ensure the surveys are triggered at most once per day.
* [ ] Make use of `useIntersection()` to ensure the target is in the viewport, not just rendered.

### Test Coverage

* No new tests needed.

## QA Brief

- Ensure that the Consent Mode `enabled` setting is `false` and an Ads Conversion ID is set to show the banner and trigger the `enable_como` survey, as well as to ensure the `enable_como` survey is triggered on the Settings page when the Consent Mode section is in view.
- Verify that the surveys are triggered as per the AC.
- To verify that a survey has been triggered, using the Chrome devtools network inspector or an HTTP proxy like Proxyman, ensure an HTTP `POST` request is made to `/wp-json/google-site-kit/v1/core/user/data/survey-trigger` with the body:

```
{
  "data": {
    "triggerID": "enable_como" // Or "view_como_setup_cta".
  }
}
```
- As surveys are only triggered once per day, you may need to clear the survey timeouts from the DB in order to verify the triggers on both the dashboard and Settings page.
  - Using the WP CLI, where `1` is the current user ID:
    - `wp user meta patch delete 1 wp_googlesitekit_survey_timeouts view_como_setup_cta`
    - `wp user meta patch delete 1 wp_googlesitekit_survey_timeouts enable_como`
  - Using SQL (clearing the whole field):
    - `DELETE FROM wp_usermeta WHERE meta_key = 'wp_googlesitekitpersistent_dismissed_prompts' AND user_id = 1`
## Changelog entry

* Add happiness survey triggers for the Consent Mode feature.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil I'm not able to trigger suvery using Proxyman or Tweak. Getting the 404 error on proxyman and on tweak request is not getting sent.

As per AC-
1) My understanding is that when a Consent Mode setup CTA is viewed on Dashboard and Toggle on Admin Settings tab (only when "recommended" and the toggle is in the off position) then `view_como_setup_cta` survey will trigger. 

![image](https://github.com/google/site-kit-wp/assets/94359491/95a2d7d8-235d-40c4-85fa-9f0cc40124c4)

2) When the Consent Mode is enabled via Dashboard CTA or Toggle on Admin Settings tab then `enable_como` survey will trigger.

![image](https://github.com/google/site-kit-wp/assets/94359491/ee2d1ce2-d098-4e77-bc39-5c3221aa5204)

Tweak Screenshots-

![image](https://github.com/google/site-kit-wp/assets/94359491/ed72bc89-e302-4e5d-97e1-0a098e99cbc7)

![image](https://github.com/google/site-kit-wp/assets/94359491/d4d7c9d6-9952-42e7-907e-02cfe786f01e)

**Comment by techanvil** [comment]
Hi @mohitwp, there's no need to try to trigger the survey yourself using Tweak. You just need to verify that the request has been made. If you're using Chrome then the devtools network tab is all that's needed:

![image](https://github.com/google/site-kit-wp/assets/18395600/5bb835b1-3486-4262-8a8a-8f47e67288da)
