### ISSUE TITLE
Add a Site Health section for consent mode

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#8356]
Add a section to the Site Kit Site Health to show if a user has enabled consent mode on their site. If possible, we could also display if Site Kit has detected the WP Consent API. 

Sections to add:
1. **Consent mode:** enabled/disabled
2. **WP Consent API:** Detected/Not detected

## Acceptance criteria

* Site Kit Site Health should show a new field labelled "Consent Mode", with the text "Enabled" or "Disabled" based on whether or not the site has Consent Mode enabled.
* Site Kit Site Health should show a new field labelled "WP Consent API", with the text "Detected" or "Not detected" based on whether or not the WP Consent API functionality is available on this site.

## Implementation Brief

- [ ] In `includes/Core/Consent_Mode/Consent_Mode.php`:
    - [ ] Update the `register` method to add a new `googlesitekit_consent_mode_status ` filter (using `add_filter`). In its callback function, return string `enabled` if `$this->consent_mode_settings->is_consent_mode_enabled()` is truthy, otherwise, return `disabled`.
- [ ] In `includes/Core/Site_Health/Debug_Data.php`:
	- [ ] Add a new `get_consent_mode_fields` method. In this method:
		- [ ] It should return an associative multidimensional array with the named keys: `consent_mode` array `consent_api`. Each key should have another associative array assigned as its value which should have the named keys: `label`, `value`, and `debug`. The structure should follow as described below:
			- [ ] `consent_mode` =>
				- [ ] `label` => `Consent Mode` (translatable).
				- [ ] `value` => This should either be `Enabled` or `Disabled` (translatable) based on the `googlesitekit_consent_mode_status` filter.
				- [ ] `debug` => This should apply the `googlesitekit_consent_mode_status` filter and default to `disabled`.
			- [ ] `consent_api` =>
				- [ ] `label` => `WP Consent API` (translatable).
				- [ ] `value` => This should either be `Detected` or `Not detected` (translatable) based on whether WP Consent API functionality is available on the site.
				- [ ] `debug` => This should either be `detected` or `not-detected` based on whether WP Consent API functionality is available on the site.
		- [ ] In order to determine if WP Consent API functionality is available on the site, check if the `wp_set_consent` function exists (using `function_exists`).
	- [ ] Update the `get_fields` method:
		- [ ] Right after the definition of the `$fields` array, update it by merging the array returned by the `get_consent_mode_fields` method to it.

### Test Coverage

- [ ] In `tests/phpunit/integration/Core/Site_Health/Debug_DataTest.php`:
	- [ ] Add a new test case verifying that the debug fields include the new Consent Mode keys with appropriate values.

## QA Brief

* Set up Site Kit.
* Go to Tools -> Site Health -> Info.
* Verify that Consent Mode fields appear in the list.
* Try turning on and off Consent Mode and verify that the status changes.
* Try activating and deactivating the WP Consent API plugin and verify that the API status changes.

## Changelog entry

* Add Site Health entries for the current Consent Mode status, and the presence of the WP Consent API.

**Comment by nfmohit** [comment]
> > * In order to determine if Site Kit has Consent Mode enabled, instantiate a new instance of the `Core\Consent_Mode\Consent_Mode_Settings` class passing `$this->options` to its constructor, and call its `is_consent_mode_enabled` method.
> 
> @nfmohit this is not really how it should be done. Instead of creating a new instance, we need to either add a new filter that will allow us to add new fields in the consent class or add a filter that will indicate wether needed settings are enabled.

I've updated the IB to add a new `googlesitekit_is_consent_mode_enabled` filter. Please let me know if it looks good now, thanks @eugene-manuilov!

**Comment by eugene-manuilov** [comment]
> I've updated the IB to add a new `googlesitekit_is_consent_mode_enabled` filter. Please let me know if it looks good now,

Yes, that is better, thanks, @nfmohit. But let's rename it to be `googlesitekit_consent_mode_state` or `googlesitekit_consent_mode_status` and make it return either `enabled` or `disabled` values that we can use for the `debug` property.

**Comment by nfmohit** [comment]
> > I've updated the IB to add a new `googlesitekit_is_consent_mode_enabled` filter. Please let me know if it looks good now,
> 
> Yes, that is better, thanks, @nfmohit. But let's rename it to be `googlesitekit_consent_mode_state` or `googlesitekit_consent_mode_status` and make it return either `enabled` or `disabled` values that we can use for the `debug` property.

Updated, thanks @eugene-manuilov!

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Consent Mode fields appear in the Site health info list.
  - Tested turning on and off Consent Mode and the status changes.
  - Tested activating and deactivating the WP Consent API plugin and the API status changes.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/b2b6fba9-eac6-448e-88cd-f47547b49259)
![image](https://github.com/google/site-kit-wp/assets/73545194/59c10b45-66a0-4fa5-8064-9482d33b23b4)
![image](https://github.com/google/site-kit-wp/assets/73545194/c9c0daed-5959-4205-9c2c-4477a4c2d9e4)
![image](https://github.com/google/site-kit-wp/assets/73545194/aa627613-af01-4aa9-b456-d4870d67d017)

</details>
