### ISSUE TITLE
Improve the deprecation warning for the `googlesitekit_analytics-4_tag_block_on_consent` filter

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8362]
## Feature Description

At present, the deprecation warning for the `googlesitekit_analytics-4_tag_block_on_consent` filter that was introduced in https://github.com/google/site-kit-wp/issues/8275 reads as follows:

> PHP Deprecated: Hook googlesitekit_analytics-4_tag_block_on_consent is deprecated since version 1.122.0 with no alternative available.

We should improve the message to help steer users toward the Consent Mode feature as an alternative, for example:

> PHP Deprecated: Hook googlesitekit_analytics-4_tag_block_on_consent is deprecated since version 1.122.0 with no alternative available. Please use the Consent Mode feature instead.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The deprecation warning for the `googlesitekit_analytics-4_tag_block_on_consent` should read as follows:
> PHP Deprecated: Hook googlesitekit_analytics-4_tag_block_on_consent is deprecated since version 1.122.0 with no alternative available. Please use the Consent Mode feature instead.
* The additional message, "Please use the Consent Mode feature instead.", should be translated as usual.

## Implementation Brief

* [ ] Amend the arguments returned by `Analytics_4\Web_Tag::get_tag_blocked_on_consent_deprecated_args()` to include the translated additional message as per the AC. The second argument should be an empty string.

https://github.com/google/site-kit-wp/blob/9a5b02e1c4df25bdddba091bf745937d683ceeca/includes/Modules/Analytics_4/Web_Tag.php#L92-L96

### Test Coverage

* 

## QA Brief

* Setup Site Kit and connect Analytics.
* Create a php file inside wp-content/mu-plugins/ directory and add following code to it
```php
<?php
add_filter( 'googlesitekit_analytics-4_tag_block_on_consent', '__return_true' );
```
* Make sure you have `WP_DEBUG` and `WP_DEBUG_DISPLAY` set to `true` in `wp-config.php` file so that we can see the warning on the page.
* Visit the home page, there must be the following warning displayed on the page.
```
Deprecated: Hook googlesitekit_analytics-4_tag_block_on_consent is deprecated since version 1.122.0 with no alternative available. Please use the Consent Mode feature instead. in /var/www/html/wp-includes/functions.php on line ----
```

<img width="1901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWgrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbb87ccd4d74e13db6ca826c00bc440b96391327/Screenshot%202024-04-22%20at%203.42.34%E2%80%AFPM.png" alt="Screenshot 2024-04-22 at 3.42.34 PM.png" />

## Changelog entry

* Improve the deprecation warning for the `googlesitekit_analytics-4_tag_block_on_consent` filter.

**Comment by aaemnnosttv** [comment]
I looked at this as well and core wasn't using the message at all from what I found. There is no alternative filter though (as noted in the IB), so I think this is a worthwhile enhancement.

AC + IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@ankitrox in the AC it mentions the text should read: 

> PHP Deprecated: Hook googlesitekit_analytics-4_tag_block_on_consent is deprecated since version 1.122.0 with no alternative available. Please use the Consent Mode feature instead.

I do not see any reference to `PHP` in warning notice, is this correct? 

`Deprecated:  Hook googlesitekit_analytics-4_tag_block_on_consent is deprecated since version 1.122.0 with no alternative available. Please use the Consent Mode feature instead`

Also, the message reads a little odd because after `instead` theres a period and then `in`, So in its entirety it reads `Deprecated:  Hook googlesitekit_analytics-4_tag_block_on_consent is deprecated since version 1.122.0 with no alternative available. Please use the Consent Mode feature instead. in /s2-sitekit-125/wordpress/wp-includes/functions.php on line 6078`

Is that expected?

![image](https://github.com/google/site-kit-wp/assets/73545194/5bc647fc-3b43-4ae7-bd7d-7c6168a6632c)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Followed instructions in the QAB and depreciation warning notice appears. 

![image](https://github.com/google/site-kit-wp/assets/73545194/5bc647fc-3b43-4ae7-bd7d-7c6168a6632c)
