### ISSUE TITLE
Update Consent Mode once the Ads Conversion ID setting has been migrated to the Ads module.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8365]
## Feature Description

Ensure that the relevant parts of Consent Mode are updated once the Ads Conversion ID setting has been migrated to the Ads module.

Some of this will almost certainly be updated as part of the Ads Module work, this issue is to ensure nothing is missed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Once the Ads Conversion ID has been migrated to the Ads Module:
  * All references to it in the Consent Mode feature should be updated to use the value from the Ads Module.
  * The confirmation dialog shown when disabling Consent Mode on the Settings screen should be updated to include the Ads module when it's connected.

## Implementation Brief

_An initial IB has been drafted, to be completed._

* [ ] Ensure the following code snippets are updated to get the `adsConversionID` from the `ads` module:

https://github.com/google/site-kit-wp/blob/26e6a4318b09e47796fa5c02adf263ab756cb383/assets/js/components/consent-mode/ConsentModeSetupCTAWidget.js#L72-L75

https://github.com/google/site-kit-wp/blob/26e6a4318b09e47796fa5c02adf263ab756cb383/assets/js/components/settings/SettingsCardConsentMode.js#L50-L53

https://github.com/google/site-kit-wp/blob/26e6a4318b09e47796fa5c02adf263ab756cb383/assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.js#L45-L47

### Test Coverage

* Update the `assets/js/components/consent-mode/ConsentModeSetupCTAWidget.stories.js` story to use the ads store.

## QA Brief

* Setup the Site Kit, enable `adsModule` feature flag, and connect Analytics and Ads modules
* Go to the Site Kit settings -> Admin Settings, enable the `Consent Mode`. Then try to disable it, the popup should mention Ads module in the Note section, together with Analytics `"Note: these active modules depend on consent mode and will be affected: Analytics and Ads"`
* Then disconnect the `Ads` module, and repeat the step above, note section should mention only `Analytics` as affected module (Ads should be in the list only when active)
* Verify that Consent mode [banner](8279) is still appearing when Ads module is active, and not showing when Ads module is not connected
* Verify that `recommended` [badge](8278) is showing in admin settings when Ads module is connected

## Changelog entry

* Ensure that the check for a conversion tracking ID is maintained for the Consent Mode feature with the conversion ID having been migrated to the Ads module.

**Comment by benbowler** [comment]
I have reviewed the current consent mode for any use of the `adsConversionID` and all cases are covered in the IB.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by nfmohit** [comment]
Hi @zutigrm & @techanvil.

It looks like [this change in the PR](https://github.com/google/site-kit-wp/commit/a55783baa4e37cbe31f468a630751f247aeb80ed) has stopped the consent mode banner from appearing if the Ads module is not connected.

The above change implies that the consent mode banner should only show up if both the Analytics & Ads modules are connected. However, it is possible for Google Ads to be connected even without one of the modules disconnected. Examples:

1. Analytics module is not connected, but Ads module is connected with an Ads conversion tracking ID.
2. Ads module is not connected, but Analytics module is connected and:
	1. It is linked with Google Ads (`adsLinked`) and/or
	2. The connected Google Tag has an Ads conversion ID as one of its destinations.

However, with the above linked change, the banner will only appear if both Ads and Analytics modules are connected, which I think is not right. Thoughts?

**Comment by techanvil** [comment]
Thanks @nfmohit, great spot. That one totally slipped by me.

@zutigrm, please can you file a followup PR to update the condition that Nahid's highlighted? It should be returning false if _neither_ of the modules are connected, e.g. along these lines:

```js
if (
  ! (
    isModuleConnected( 'analytics-4' ) || isModuleConnected( 'ads' )
  )
) {
  return false;
}
```

With this being a release issue we should address this as a priority. Thanks!

@mohitwp, I've moved this back from QA to Execution and assigned it back to Aleksej to address the above.

**Comment by techanvil** [comment]
Apologies I hadn't spotted @zutigrm is off today. @nfmohit has kindly offered to raise a PR to address this.

**Comment by nfmohit** [comment]
> Thanks @nfmohit, great spot. That one totally slipped by me.
> 
> @zutigrm, please can you file a followup PR to update the condition that Nahid's highlighted? It should be returning false if _neither_ of the modules are connected, e.g. along these lines:
> 
> ```js
> if (
>   ! (
>     isModuleConnected( 'analytics-4' ) || isModuleConnected( 'ads' )
>   )
> ) {
>   return false;
> }
> ```
> 
> With this being a release issue we should address this as a priority. Thanks!
> 
> @mohitwp, I've moved this back from QA to Execution and assigned it back to Aleksej to address the above.

Thank you @techanvil . This is in CR now with a follow-up PR.

**Comment by nfmohit** [comment]
> * Hey @nfmohit , according to the QAB Consent mode, the banner only appears if the Ads module is connected, regardless of whether analytics is connected or not. I just want to confirm if this information is correct, especially if the QAB hasn't been updated after recent changes. Could you please review and confirm?

Hi @mohitwp. That is correct. If the Ads module is connected, we don't need the Analytics module to also be connected in this context. Thanks!

**Comment by mohitwp** [comment]
### QA Update ✅  

- Tested on main environment.
- Verified according to the QAB Consent mode, the banner only appears if the Ads module is connected, regardless of whether analytics is connected or not.
- Verified Recommended badge is appearing only if Ads module is connected.
- Verified Copy under disconnect modal is getting update as per which module is active.

<details>

**If only Analytics is connected** 

![image](https://github.com/google/site-kit-wp/assets/94359491/e36cee69-cb23-470d-abd8-f6c3f55a8ae9)

![image](https://github.com/google/site-kit-wp/assets/94359491/989090a1-cf7f-421f-acd6-14fb04d5530c)

**Both Analytics and Ads Module connected-**

![image](https://github.com/google/site-kit-wp/assets/94359491/8dd5da61-53ac-4e3f-9061-d31e2bda9fda)

**Only Ads module is connected -**

![image](https://github.com/google/site-kit-wp/assets/94359491/826206df-6459-4680-a806-0d1f604cfeca)


**Ads Module connected with Analytics** 

![image](https://github.com/google/site-kit-wp/assets/94359491/bd071562-acb5-4d31-8a7b-f7f4216b86f0)

**Ads Module connected without Analytics**

![image](https://github.com/google/site-kit-wp/assets/94359491/86b200e6-cd1f-42e4-864c-000b9f1f5118)

**Recommended  badge -**

![image](https://github.com/google/site-kit-wp/assets/94359491/66f04068-25bc-4776-b323-05b4aace090a)

**Recommended badge not showing if analytics is not connected-**

![image](https://github.com/google/site-kit-wp/assets/94359491/f6a3a574-9eec-4ced-89dc-d00a5cfb3752)


</details>
