### ISSUE TITLE
Remove lingering feature flag reference to `dashboardSharing`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8367]
## Feature Description

The `dashboardSharing` feature flag was removed in #6884 , however there is still a reference left behind https://github.com/google/site-kit-wp/blob/0c6c86498887ce4c8834982c9af70dd7661bb1ca/assets/js/components/settings/EntityOwnershipChangeNotice.js#L42

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure all references to the `dashboardSharing` feature flag are removed

## Implementation Brief

* [x] Remove the [one instance](https://github.com/google/site-kit-wp/blob/0c6c86498887ce4c8834982c9af70dd7661bb1ca/assets/js/components/settings/EntityOwnershipChangeNotice.js#L42) currently present and any others if found

### Test Coverage

* No changes expected but it could require fixing some tests (hence a bit more time to do this one)

## QA Brief

* No QA required for this change, we're just removing a lingering feature flag.

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
As par QAB, no additional QA is needed here. Moving to Approval.
