### ISSUE TITLE
Analytics displays wrong property when tag from other plugin is detected

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#837]
A recent[ report in the forums](https://wordpress.org/support/topic/ga-detecting-right-property-but-showing-wrong-property/) as well as issues #62 and #396 appear to point to the Analytics module detecting the correct tag/ property inserted by another plugin or theme, but ultimately selecting and displaying data for the wrong property (the first one ). I was able to recreate this on my test site (see below).  

## Steps to reproduce

1. Use another plugin to insert the Analytics tag of a second property on the account. 
2. Connect the Google Analytics Module in Site Kit
3. In the Analytics settings, see correct property detected and incorrect property selected. In the dashboard, see incorrect property data.  

## Screenshots

<img width="1069" alt="Analytics chooses wrong property from other plugin's tag" src="https://user-images.githubusercontent.com/8108643/68629273-10b41980-0498-11ea-852c-76e743a1661a.png">

## Additional Context

 - PHP Version: 7.1.33
 - OS: MacOS
 - Browser: chrome
 - Plugin Version 1.0.2
 - Device: MacBook Air

  
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

When there is an existing GA tag on the site:
* match against the properties the user has access to by property ID only
* if a match, force-select that property
* if no match, prevent proceeding
(both of these should already be the case)

When a user has a GA account with more than one property matching the same URL:
* keep pre-selecting the first property by default
* give the user the option to select the correct property from the drop-down menu (i.e. don't force it, don't disable the dropdown)

## Implementation Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
Upon further investigation, it appears when both properties share the same default URL (which is also the URL of the site), the first property will be chosen automatically. Also note, there is no way to select the right property in this scenario because the ability to edit the property is locked:


![Cannot edit incorrect property](https://user-images.githubusercontent.com/8108643/70845073-3453e200-1dff-11ea-9dd4-ac17e349e8d9.png)

**Comment by dhuyck** [comment]
I have the same issue - we are using one ID for the site (inserted without using Site Kit), but GA is defaulting to a different ID, so the analytics data are not aligning.

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr I think the better approach here is to keep the same behavior (pre select and disable property dropdown) but that the selected property should be matched by property ID rather than URL. Is there any reason why we wouldn't want to do that instead?

**Comment by felixarntz** [comment]
@aaemnnosttv Yes, an existing tag should only ever be matched via its property ID. If we match by URL (unrelated to existing tag, should only be happen if there is no existing tag), the property pre-selected from there should never be force-selected (_because_ there may be multiple, and URL-based matching is just a helpful assumption).

**Comment by aaemnnosttv** [comment]
@felixarntz would you please update the AC to reflect that? 🙂

**Comment by felixarntz** [comment]
@aaemnnosttv I've updated the ACs. What I don't actually understand completely is what is broken here specifically. Everything that is in the ACs IMO should already have been working like that for a while.

**Comment by aaemnnosttv** [comment]
I think what's happening in @ernee 's screenshot above is that the error shows the existing tag that was found (obviously), and the portion below shows what is saved in the settings, which is what it _should_ show IMO (even in the case of an existing tag). Settings components which are not in "edit mode" should always reflect the saved values.

The module will always use the property that is saved in the settings for its data shown in WP admin. If an existing tag is detected later, it won't automatically change the property in the settings (nor should it I don't think). On the other hand, if you edit the settings, you will likely be blocked from saving the changes if you don't have access to the property. If you do, then you shouldn't have the choice to select any other property and the module will use the detected property going forward once settings are saved.

Looking at the code, it looks like there could be a problem with matched property handling as this is only used in the case that there is no selected account, which seems fragile.

Would be great if we could reproduce this with the current release to confirm it is still an issue. 
cc: @cole10up

**Comment by ernee** [comment]
Looks to be resolved with version 1.2.0, after testing and reports back from two users who had the issue previously. Closing.

**Comment by aaemnnosttv** [comment]
Thanks @ernee 👍 
Removing this from the board for now. Feel free to re-add if this comes up again!
