### ISSUE TITLE
Improve the layout of the graphic on the Consent Mode Setup CTA Banner at narrow desktop viewports.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8376]
## Feature Description

The layout of the graphic on the Consent Mode Setup CTA Banner at narrow desktop viewports could be improved. As can be seen here at 961px the white and grey window in the middle of the graphic is slightly clipped:

![image](https://github.com/google/site-kit-wp/assets/18395600/9abfdab1-50b2-4292-9a79-81117811437b)

It would be good to avoid this clipping and retain some of the green background around it as can be seen here at a wider viewport:

![image](https://github.com/google/site-kit-wp/assets/18395600/d110744c-6203-4331-a704-a074392d5143)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Consent Mode Setup CTA Banner's layout should be vertically stacked, with the text and CTAs on one row and the graphic displayed on a row beneath it, for the following viewports, as per the linked Figma designs:
  * Mobile (viewport width <= 600px): [Figma](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=514-8426&t=pTycSCYgTciKZ2Rz-0)
  * Tablet (viewport width <= 960px): [Figma](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=630-6302&t=pTycSCYgTciKZ2Rz-0)
  * "Narrow" desktop (viewport width <= 1280px): [Figma](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=631-7973&t=pTycSCYgTciKZ2Rz-0)
* For the "wide" desktop viewport (width >= 1281px), the layout should flow horizontally, with text/CTAs and the graphic on a single row, with the graphic to the right, as per the [Figma](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=660-3344&t=pTycSCYgTciKZ2Rz-0) design.

Please refer to the actual Figma designs as the source of truth, but for the sake of illustration here are screenshots of the layouts from Figma:

_Mobile:_
![image](https://github.com/google/site-kit-wp/assets/18395600/ff117716-bce1-484e-90f1-a49f9141414e)

_Tablet:_
![image](https://github.com/google/site-kit-wp/assets/18395600/9a82acdb-5a5c-4cb1-8803-c1b7469f4479)

_Narrow desktop:_
![image](https://github.com/google/site-kit-wp/assets/18395600/97cab149-e7b7-4a31-850e-07e66534f3a0)

_Wide desktop:_
![image](https://github.com/google/site-kit-wp/assets/18395600/dc9bee6d-a6b0-4ab1-921b-b218b0a121d3)

## Implementation Brief

* [ ] Update `assets/js/components/consent-mode/ConsentModeSetupCTAWidget.js`:
   * [ ] Refactor the component to use divs with classes rather than `Grid`, `Row` and `Cell` components, because these components don't support the wide desktop breakpoint we need.
 * [ ] Update the layout of the CTA  based on the AC in `assets/sass/components/ads/_googlesitekit-ads-setup-banner.scss`, use a mobile first approach and update the layout using flexbox, switching the flex direction to position the svg beside or below the widget text depending on the breakpoint.

### Test Coverage

* Update VRTs based on the new UI changes.

## QA Brief

* Setup Site Kit
* Verify that the consent mode banner looks like on referenced figma designs in AC

## Changelog entry

* Update the layout of the graphic on the Consent Mode Setup CTA banner.

**Comment by sigal-teller** [comment]
I'll create a design for narrow/tablet viewport

**Comment by sigal-teller** [comment]
@techanvil I added the tablet/narrow viewport [design](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=615-3225&t=q9lAQF9p0cWQI5ge-1) for the banner. LMK if there's anything else required.

**Comment by techanvil** [comment]
That's great, thanks @sigal-teller!

**Comment by techanvil** [comment]
Thanks @sigal-teller, that's great for the tablet view. However, what's still not entirely clear is how the graphic should display at the narrower desktop viewports.

Currently the desktop layout has the graphic on the right hand side but it crops at narrower desktop widths as seen in the images above. I wouldn't imagine we want to have the graphic displaying at the bottom for _some_ of the desktop viewports, would we?

What would be great is if you could provide a design at the narrow desktop viewport of 901px to help clarify this further...

**Comment by sigal-teller** [comment]
@techanvil Well actually in the narrow desktop viewport I would use the tablet design. There's too much content in this banner to fit in the same layout as wider viewports. The texts breaks into too many lines and the banner looks unbalanced. I think that in this case in narrow viewports we should adapt the design to look batter rather then match the wider viewports design. I added a design for it [here](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=631-7973&t=LIwugF21wdYIYr1m-1).

**Comment by techanvil** [comment]
Thanks @sigal-teller. In that case, would you like to specify the breakpoint at which we transition from the tablet/narrow desktop layout to the full width desktop layout? Or, we could simply specify that we should break at the point where the graphic isn't horizontally cropped in the full width layout (maybe also specifying some minimum padding at the horizontal edges too). WDYT?

**Comment by sigal-teller** [comment]
@techanvil If that's easier to implement then yes, we can define that we're using the wide desktop viewport as long as the graphics isn't cropped. If it's easier to set a fixed breakpoint that's we can do that as well, we might be able to use one of our existing breakpoints, depending if they are close enough.

**Comment by techanvil** [comment]
Hey @sigal-teller, thanks for your reply.

I've been looking into this one a bit more, and, actually I am thinking we should reconsider the approach here. Sorry I didn't think of this earlier when asking my question about the breakpoints.

We _can_ take the approach of breaking at a different breakpoint - but, it would be preferable not to. Bearing in mind we already have multiple banners with a similar design, as seen below (and no doubt more to come), it would be good to use a single generic component for all of these - this is a refactor we can make in the forthcoming Banner Notifications epic.

_Ads:_
![image](https://github.com/google/site-kit-wp/assets/18395600/4f6e2632-a417-41c1-a02c-02fc1855bcda)

_Consent Mode:_
![image](https://github.com/google/site-kit-wp/assets/18395600/8e6d048b-fca1-4c0b-9a93-cbbb78505eb9)

_RRM:_
![image](https://github.com/google/site-kit-wp/assets/18395600/b2aa45a9-036a-4ed6-98b8-e9c20742424e)

For the sake of UI consistency and code simplicity, it would be preferable if these all had the same responsive behaviour when it comes to their breakpoints.

What if we take another look at how the graphic is used within the breakpoint? I realise it arguably looks a bit off with it being cropped in the middle of the banner. However, we're already cropped at the top and bottom in desktop viewports. What if we adjusted the size and position of the graphic to avoid cropping on the left, but allow the right to be cropped, where it looks more natural as it aligns with the end of the banner?

Admittedly it's not perfect, but here's how it could look at 961px. As a compromise, for the sake of consistency and using standard breakpoints I think it could be OK.

![image](https://github.com/google/site-kit-wp/assets/18395600/370b98f4-b672-496a-8c4d-f476585ab111)

Alternatively - personally, I don't actually think the left hand crop is so bad as long as the foreground graphic elements are not cropped and are well positioned within the banner. We could specify that the main "window" graphic should be centered within the right hand of the pane and only the green background can be cropped within this area, for example:

![image](https://github.com/google/site-kit-wp/assets/18395600/f3c9d426-0618-4fe6-886b-e4dab8295432)

We can of course still take the approach of a different breakpoint if needs be - I don't want to suggest overly compromising the aesthetic integrity. But, as discussed above it would be nice to avoid it if we reasonably can.

What do you think?

**Comment by sigal-teller** [comment]
Hey @techanvil I think you're right and we should strive for consistency in all setup banners, since they so use the same layout. i think there are 2 main issues here:

the 1st issue is to avoid cropping the visual, unless it's on the right edge of the banner. I think that this can be solved by creating a shape that can be displayed uncut when it's scaled down to fit the remaining space. I can do that for each green shape that I'm using, and then it will only get cut in wider viewports that will allow more space for the text.

The 2nd issue is switching to tablet layout in narrow viewports. The reason why I preferred [this design](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=631-7973&t=wQHZQiLRBdABPg1Z-1) in narrow viewports is to avoid an unbalanced layout, where the text is stacking on the left while increasing banner height significantly, and as a result we have a small illustration on the right side of the banner. It looks unbalanced. I think that maybe we should use this design for all banners in narrow viewports (I assume we can do that while refactoring all banner).

WDYT?

**Comment by techanvil** [comment]
Thanks @sigal-teller. Adjusting the graphics as you've described SGTM.

With regard to 2nd issue - if we decide to use the vertically stacked layout for narrow desktop viewports as per your design, it does raise the question of what viewport width this layout should be applied up to. Our standard desktop breakpoints are 961px and 1281px. Here's a mockup of how it could look at the top end of this range, 1280px. It's OK, but the horizontal layout is probably better. Do you think this would be an acceptable layout at this width (presumably with a tweak to the graphics as per your updated design)?

![image](https://github.com/google/site-kit-wp/assets/18395600/9fe9f25a-d417-4a92-a89b-9edb684acd7d)

It's also worth considering that if we are going to make changes to all of these banners, it might be better to undertake the work as part of the Banner Notification Refactoring epic that @jimmymadon has picked up the lead on...

**Comment by binnieshah** [comment]
Thanks @techanvil this may make sense if we are going to make changes to the banners. @sigal-teller let us know what you think on what Tom has said above. I can then revise the sprint plan accordingly. Thanks

**Comment by sigal-teller** [comment]
@techanvil I don't think it will be a good idea to use this design for all desktop viewports, including the wider viewports. Stacking the text above the illustration creates unbalanced layout and the banner height gets extended more then it needs. 

We can use the breakpoints you mentioned, so from 1281px (net 1121 for the SK view without WP nav bar) we can use the wider desktop viewport design as it is [here](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=660-3344&t=9PDbYTn5llswwK3u-1), meaning the text will be placed to the left of the illustration.

Tablet and narrow desktop viewports will have the vertical stacking like [here](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=631-7973&t=9PDbYTn5llswwK3u-1).

Does that make sense?

**Comment by jimmymadon** [comment]
@techanvil @binnieshah Just a quick note that as part of the first 2 phases of the Banner Notifications Refactoring epic, we don't intend to work on "inline" banners, i.e. banners which appear within the dashboard widget areas rather than within the `Header` component. We also don't intend to specifically consolidate the design or make any design changes unless it specifically makes the refactored code much simpler in a case here and there. But we will get to these eventually once the actual "notifications" are all refactored.

c.c. @aaemnnosttv

**Comment by binnieshah** [comment]
OK, so sounds like it would be good to get this one done within an upcoming sprint. @techanvil please could you review Sigal's note above and confirm this is OK? I can then assign it within the team. Thanks

**Comment by techanvil** [comment]
Thanks @binnieshah.

@sigal-teller, that makes sense, and it's great you have created the designs for the different viewports for the Consent Mode banner.

I think, for the sake of moving this issue along we can address the CoMo banner in isolation, and I've added AC.

We can then follow up with a separate issue to apply the same responsive layout to the Ads and RRM banners. It would be great to flesh these out with per-viewport designs as well, to get a visual check on how they would look prior to committing to implementation, and in case the graphics might need a tweak. @sigal-teller, would you be able to provide designs for these?

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm Layout for the tablet is not matching with Figma design. As per AC Tablet (viewport width <= 600px): [Figma](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=630-6302&t=pTycSCYgTciKZ2Rz-0) 
Can you please check if AC is correct ?


Tablet viewport

![image](https://github.com/user-attachments/assets/22cdca72-8d8f-4630-b5fc-87203b0db506)


<details>

Wide Dashboard

![image](https://github.com/user-attachments/assets/db69b9cb-5dea-4eef-945e-483b0bd7b00d)

Narrow Dashboard

![image](https://github.com/user-attachments/assets/4fcd3903-79ce-46b8-ae4b-1433eab4366d)

Mobile Dashboard

![image](https://github.com/user-attachments/assets/e303d7ef-4d81-445b-b69c-256907f8f1b0)


</details>

**Comment by zutigrm** [comment]
Thanks for raising it @mohitwp . It is most likely written by mistake during AC, as we usually consider tablets starting _from_ 600px not bellow, it is already mobile bellow that width. Let me confirm this with @techanvil since he wrote the AC

**Comment by techanvil** [comment]
Thanks @mohitwp and @zutigrm - this was a mistake in the AC as Aleksej has pointed out. I have now corrected it, sorry for the inconvenience!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified Consent Mode setup CTA banner appearing at per Figma files.

<details>


**Tablet view**

![image](https://github.com/user-attachments/assets/9e2e72d4-77e6-44b9-b882-69ab0e5738d7)

![image](https://github.com/user-attachments/assets/3a0c6f25-c6e0-4d74-884d-9bd8a4bef83b)

**Mobile View**

![image](https://github.com/user-attachments/assets/0bb554ed-8fa4-4f72-9f13-a4626cf61a72)

**Wide Dashboard**

![image](https://github.com/user-attachments/assets/db69b9cb-5dea-4eef-945e-483b0bd7b00d)

**Narrow Dashboard**

![image](https://github.com/user-attachments/assets/4fcd3903-79ce-46b8-ae4b-1433eab4366d)

</details>
