### ISSUE TITLE
I18n - Wrong usage of variables in strings with time period

### ISSUE THREAD

**Issue by pedro-mendonca** [google/site-kit-wp#838]
## Bug Description

First, here is a list of 3 patterns of strings that exist in the plugin:
1) `Last 28 days` (Used standalone in dropdown and as variable for string 2)
2) `Audience overview for the last %s`
3) `Audience overview for the last 28 days`

### The problem

Wrong concatenation of variables for time periods in the below strings:

`Audience overview for the last %s` ([source](https://github.com/google/site-kit-wp/blob/2a701f7e824607c5fcb7aba6e4aebc3a9c03fe62/assets/js/modules/analytics/dashboard/dashboard-widget.js#L184))
`Top content over the last %s` ([source](https://github.com/google/site-kit-wp/blob/2a701f7e824607c5fcb7aba6e4aebc3a9c03fe62/assets/js/modules/analytics/dashboard/dashboard-widget.js#L210))
`Overview for the last %s` ([source](https://github.com/google/site-kit-wp/blob/2a701f7e824607c5fcb7aba6e4aebc3a9c03fe62/assets/js/modules/search-console/dashboard/dashboard-widget.js#L182))
`Top search queries over the last %s` ([source](https://github.com/google/site-kit-wp/blob/2a701f7e824607c5fcb7aba6e4aebc3a9c03fe62/assets/js/modules/search-console/dashboard/dashboard-widget.js#L201))
`Top acquisition sources over the last %s` ([source](https://github.com/google/site-kit-wp/blob/2a701f7e824607c5fcb7aba6e4aebc3a9c03fe62/assets/js/modules/analytics/dashboard/dashboard-widget.js#L227))

The variables are a time period formated as **_Last XX days_**.

This makes all the above strings look bad, as this:
**Overview for the last _Last 28 days_**
(This is happening only in the translated version of the plugin, check the screenshots below.)

### Also...
Since these strings need some fix, it should be merged with the use of a variable with some very similar existing strings with an hardcoded amount of days:
2) `Audience overview for the last %s`
3) `Audience overview for the last 28 days`
(This similarity exist in most of the above strings.)

## Steps to reproduce

To see these errors, go to the below pages:
1. Go to `../wp-admin/admin.php?page=googlesitekit-module-analytics`
2. Go to `../wp-admin/admin.php?page=googlesitekit-module-search-console`
3. The issue is not showing in the english version.

#### Search Console in English (en_US)
![imagem](https://user-images.githubusercontent.com/7371591/68679280-77e4d300-0557-11ea-86dc-d4c109c45146.png)

#### Search Console in Portuguese (pt_PT)
![imagem](https://user-images.githubusercontent.com/7371591/68679303-84692b80-0557-11ea-99c2-e527439e6a9e.png)

## Solution

Considering that the time period will always be an amount of X days, the sentences should have this pattern:
`Audience overview for the last %d days`
Being the variable an INT value for the amount of days.

Format strings with the below patterns:
1) `Audience overview for the last %d days`
2) `Last %d days`

### Summary of proposed strings changes

```diff
- Last 7 days
- Last 14 days
- Last 28 days
- Last 90 days
- Audience overview for the last %s
- Audience overview for the last 28 days
- Top content over the last %s
- Top content over the last 28 days
- Overview for the last %s
- Overview for the last 28 days
- Top search queries over the last %s
- Top acquisition sources over the last %s
- Top acquisition sources over the last 28 days

+ Last %d days
+ Audience overview for the last %d days
+ Top content over the last %d days
+ Overview for the last %d days
+ Top search queries over the last %d days
+ Top acquisition sources over the last %d days
```

### Related
#447 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
As a fellow translator, I second these proposed changes :-)

**Comment by aaemnnosttv** [comment]
Closing as already addressed by other issues.

```
26 results - 9 files

assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidget.js:
  174: 									_n( 'Performance over the last %s day', 'Performance over the last %s days', currentDayCount, 'google-site-kit' ),

assets/js/modules/adsense/components/module/ModuleOverviewWidget/Header.js:
  48: 					_n( 'Performance over the last %s day', 'Performance over the last %s days', currentDayCount, 'google-site-kit' ),

assets/js/modules/analytics/components/dashboard/AnalyticsAdSenseDashboardWidgetLayout.js:
  51: 				_n( 'Performance by page over the last %s day', 'Performance by page over the last %s days', currentDayCount, 'google-site-kit', ),

assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidget.js:
  170: 									_n( 'Audience overview for the last %s day', 'Audience overview for the last %s days', currentDayCount, 'google-site-kit', ),
  204: 									_n( 'Top content over the last %s day', 'Top content over the last %s days', currentDayCount, 'google-site-kit', ),
  229: 									_n( 'Top acquisition channels over the last %s day', 'Top acquisition channels over the last %s days', currentDayCount, 'google-site-kit', ),

assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopAcquisitionSources.js:
  71: 				_n( 'Number of new users to visit your page over last %s day', 'Number of new users to visit your page over last %s days', currentDayCount, 'google-site-kit', ),
  79: 				_n( 'Number of sessions users had on your website over last %s day', 'Number of sessions users had on your website over last %s days', currentDayCount, 'google-site-kit', ),

assets/js/modules/analytics/components/module/ModuleOverviewWidget/Header.js:
  41: 		_n( 'Audience overview for the last %s day', 'Audience overview for the last %s days', currentDayCount, 'google-site-kit', ),

assets/js/modules/analytics/components/module/ModulePopularPagesWidget/Header.js:
  43: 		_n( 'Top content over the last %s day', 'Top content over the last %s days', currentDayCount, 'google-site-kit', ),

assets/js/modules/search-console/components/dashboard/GoogleSitekitSearchConsoleDashboardWidget.js:
  208: 									_n( 'Overview for the last %s day', 'Overview for the last %s days', currentDayCount, 'google-site-kit', ),
  236: 									_n( 'Top search queries over the last %s day', 'Top search queries over last %s days', currentDayCount, 'google-site-kit', ),

assets/js/util/date-range.js:
  53: 		_n( 'Last %s day', 'Last %s days', days, 'google-site-kit', ),
```
