### ISSUE TITLE
Remove Ads bullet point from Consent Mode modal when Ads is not connected.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8381]
## Feature Description

When an Ads Conversion ID has not been set up, we should not show the "Performance of your Ad campaigns" bullet point in the disable modal (screenshots taken from [Figma](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=59%3A16582&mode=dev)):

![image](https://github.com/google/site-kit-wp/assets/18395600/27f50972-dfc7-4fe7-964a-05d7e2a61bd4)

As a result the copy above the bullet points should also be updated, so the modal description and bullet point list should read as follows:

![image](https://github.com/google/site-kit-wp/assets/18395600/1d71a6ac-2554-4c50-b92a-9b1309f0824d)

See also the related issue https://github.com/google/site-kit-wp/issues/8389.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When Ads is not considered "connected" for the purpose of the Consent Mode feature:
  * The Consent Mode disable modal should have its description copy updated as per the latest iteration of the [Figma design](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?type=design&node-id=514-6738&mode=design&t=t6GGBaO325kA8mJS-0):
    * _Disabling consent mode may affect your ability in the European Economic Area and the United Kingdom to:_
  * The bullet point relating to Ads should be removed.
  * The remaining bullet point's copy should be updated to: _Track how visitors interact with your site_
* Note that for Ads to be considered connected within this context, at least of one of the following should be true:
  * An Ads Conversion Tracking ID has been configured.
  * An Ads link has been created for the current GA4 property.
  * The Google tag for the current GA4 property has an Ads tag as a destination.

## Implementation Brief

* [x] Update `assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.js`:
* [x] Get the adsConversionID from the `MODULE_ADS` store using the `getAdsConversionID` selector.
* [x] Add a new variable that uses `useMemo` to return a new `provides` array based on the Ads Conversion ID's presence:
```
	const provides = useMemo( () => {
		let providesArray = [
			__(
				'How visitors interact with your site via Analytics',
				'google-site-kit'
			),
		];

		if ( adsConversionID !== undefined && adsConversionID !== '' ) {
			providesArray = [
				...providesArray,
				__( 'Performance of your Ad campaigns', 'google-site-kit' ),
			];
		}

		return providesArray;
	}, [ adsConversionID ] );
```
 - [x] Update the `provides` prop on the `ModalDialog` to take the new `provides` array: `provides={ provides }`

### Test Coverage

* No additional test coverage is required.

#### Ads Module Connected
* Ensure the Ads module is connected.
* Navigate to `Settings->Admin Settings` page.
* Disable the "Enable consent mode" toggle switch.
* Verify that the modal's description remains unchanged from the current version.
* Confirm that the list of bullet points remains unchanged from the current version.

#### Ads Module Disconnected
* Disconnect the Ads module.
* Navigate back to the `Settings -> Admin Settings` page.
* Again, disable the "Enable Consent Mode" toggle switch.
* Verify that the modal's description is updated to match the specific text provided in the AC.
* Ensure that the bullet point related to the Ads module is removed. Confirm that the remaining bullet point is updated as specified in the AC.

## Changelog entry

* Remove warning about Ad campaigns in the Consent Mode deactivation modal if Google Ads is not connected.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
Hi @techanvil, we have updated the description copy to include "and the United Kingdom" as part of [#8389](https://github.com/google/site-kit-wp/issues/8389). Could you confirm if, in the absence of the Ads conversion ID, the description should now read: "_Disabling consent mode may affect your ability in the European Economic Area and the United Kingdom to_"? Also, should the bullet point be revised to "_Track how visitors interact with your site_"?

**Comment by techanvil** [comment]
Hi @hussain-t, thanks for raising this. The copy should indeed be updated as you've pointed out.

I've also realised the AC had become a bit out of date with regard to the conditions for determining if Ads is connected, and have updated it accordingly. Please can you ensure the implementation follows the AC? If you want to send it back to IB to ensure the IB is also aligned, please feel free to do so, but if you prefer to simply address this during execution that seems fine to me too.

**Comment by hussain-t** [comment]
Thanks for the clarification, @techanvil. We don't need to move it to IB. I will address the changes in my PR.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

_Ads Module Connected_
- The modal's description remains unchanged from the current version.
- The list of bullet points remains unchanged from the current version.

![image](https://github.com/google/site-kit-wp/assets/73545194/fb3a0b8c-cb97-4318-9f96-3f770ef4165d)

_Ads Module Disconnected_
- The modal's description is updated to match the specific text provided in the AC.
- The bullet point related to the Ads module is removed. 
- The remaining bullet point is updated as specified in the AC.

![image](https://github.com/google/site-kit-wp/assets/73545194/8591cede-9dda-45c9-8888-8e200324de75)

I tested this when:
- An Ads Conversion Tracking ID was configured.
- An Ads link was created for the current GA4 property. (oi.ie)
- The Google tag for the current GA4 property has an Ads tag as a destination.
