### ISSUE TITLE
Add filter to allow customisation of Consent Mode defaults.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8383]
## Feature Description

At present, we provide the `googlesitekit_consent_category_map` filter to allow the mapping of CMP consent categories to Consent Mode parameters.

However, we don't provide a filter to allow customising the default consent values that are set. It would be useful to provide a filter so as to allow these defaults to be modified, thus allowing users complete control over the consent mode parameters.

https://github.com/google/site-kit-wp/blob/fe57e172dcdaa556fdfc7e010cb5577b6a605b91/includes/Core/Consent_Mode/Consent_Mode.php#L86-L101

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A filter named `googlesitekit_consent_defaults` should be added which allows the default consent parameters to be customised.

## Implementation Brief

* [ ] Add `googlesitekit_consent_defaults` filter for the default settings and pass current array as default value https://github.com/google/site-kit-wp/blob/fe57e172dcdaa556fdfc7e010cb5577b6a605b91/includes/Core/Consent_Mode/Consent_Mode.php#L86-L93
  * `$consent_defaults = apply_filters( 'googlesitekit_consent_defaults', array(...) );`

### Test Coverage

* No updates needed

## QA Brief

**1. When no filter is added**

* This issue modifies the internal code which which provides the default values for consent mode.
* Visit the homepage (or any front end page), there should be following snippet available on the page.

```js
gtag( 
  'consent', 
  'default',
  {
    "ad_personalization": "denied",
    "ad_storage": "denied",
    "ad_user_data": "denied",
    "analytics_storage": "denied",
    "region": [
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "HR",
      "HU",
      "IE",
      "IS",
      "IT",
      "LI",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK"
    ],
    "wait_for_update": 500
  }
);
```

**2. When filter is added**

* Create a file named `consent-mode-defaults-filter.php` inside `wp-content/mu-plugins/` directory.
* Add following code in file and save.
```
<?php
/**
 * Consent mode filtering.
 */

add_filter( 
    'googlesitekit_consent_defaults', 
    function( $defaults ) {
        $filtered['wait_for_update'] = 700;
        $filtered['ad_storage']      = 'granted';
        $filtered['ad_user_data']    = 'granted';

        return array_merge( $defaults, $filtered );
    }
);
```
* Visit the homepage (or any front end page), there should be following snippet available on the page. Notice `ad_storage`, `ad_user_data` and `wait_for_update`.

```js
gtag( 
  'consent', 
  'default',
  {
    "ad_personalization": "denied",
    "ad_storage": "granted",
    "ad_user_data": "granted",
    "analytics_storage": "denied",
    "region": [
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "HR",
      "HU",
      "IE",
      "IS",
      "IT",
      "LI",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK"
    ],
    "wait_for_update": 700
  }
);
```

## Changelog entry

* Add the `googlesitekit_consent_defaults` filter to allow customisation of Consent Mode defaults.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA  Update: ⚠️ 

@ankitrox @techanvil  this passes the QAB, but I have two questions:

1. When the tiler is added I am assuming it should function with the `WP Consent API` plugin activated and disabled?  I am sure it should but I do not want to assume. 
2. Should we do any testing with the third-party consent plugins, e.g. `Complianz` activated? i suspect these plugins should override the filter we've added?

**Comment by techanvil** [comment]
Hi @wpdarren, this filter is essentially independent of the WP Consent API plugin status and any existing third-party plugins.

It's purely there to allow modification of the default consent parameters that Site Kit sets when the Consent Mode feature is enabled. It's conceivable that some third party plugin may decide to integrate with it in future, although probably not very likely, but in order to do so the plugin would need to write code to explicitly make use of the filter, which has obviously just been added and is not in a SK release yet so nobody outside of our team will have actually seen and used it as of yet.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@techanvil thank you for the clarification there.  I did think that would be the case, but wanted to double check. 

**Verified:**

_When no filter is added_

- There is the snippet available on the page as per QAB.

![image](https://github.com/google/site-kit-wp/assets/73545194/e12cb7a8-88f0-4fab-962b-56c16f82dc9b)

_When filter is added_

- There is the snippet available on the page as per QAB for `Notice ad_storage`, `ad_user_data` and `wait_for_update` based on the filter used in the MU plugin. 

![image](https://github.com/google/site-kit-wp/assets/73545194/46703e50-d940-43fa-9e44-83c922462261)
