### ISSUE TITLE
Extract and rewrite Consent Mode JS snippet.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8384]
## Feature Description

We may want to extract some or all of the Consent Mode JS snippet, in order that we can do some or all of the following:

- Minify it.
- Lint it.
- Rewrite to use modern language features.
- Cover it with JS unit tests.
- Include it via a separate script asset rather than inline.

https://github.com/google/site-kit-wp/blob/fe57e172dcdaa556fdfc7e010cb5577b6a605b91/includes/Core/Consent_Mode/Consent_Mode.php#L102-L169

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Extract the inline Consent Mode JS script to be included through Webpack in order to:
   * Minify it
   * Lint it
   * Rewrite to use modern language features.
   * Cover it with JS unit tests.
   * Include it via a separate script asset rather than inline.

## Implementation Brief

* [x] Create a new file `assets/js/consent-mode/consent-mode.js` and move all js code that does not include a `<?php` print block into this file.
   * [x] Rewrite the copied code as appropriate, see comment below.
* [x] Update `includes/Core/Consent_Mode/Consent_Mode.php`:
   * [x] Create a new method `enqueue_script`:
      * [x] Use `Script` to register and enqueue the new `consent-mode.js` asset.
   * [x] Create a new action in the `register` method, which uses the `wp_enqueue_scripts` to run the new method `enqueue_script`.
 * [x] Add the new `consent-mode.js` file to the basic modules webpack config:
 https://github.com/google/site-kit-wp/blob/fe57e172dcdaa556fdfc7e010cb5577b6a605b91/webpack/basicModules.config.js#L37-L42

**PR here to use as the base of this work #8893**, although this uses a separate webpack config so make sure to update fully based on the approved IB.

### Test Coverage

* Create new tests for the new `assets/js/consent-mode/consent-mode.js` file at a minimum:
   * Testing events `wp_consent_type_defined` and `DOMContentLoaded`
   * ~~Once #8387 is implemented, test that the gtag consent update event **is not called** if the consent state has not been changed.~~ Moved this test coverage addition to the IB of #8387 as that ticket will be implemented later.

## QA Brief

* This work refactors the Consent Mode script, so the full Consent Mode functionality should be tested to confirm there are no regressions. At a basic level the steps are:
   1. Enable [Consent Mode in the plugin admin settings](http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-settings#/admin-settings).
   2. Install and activate the WP Consent API plugin and the Complianz plugins, setting up a cookie consent banner.
   3. Use and extension like GA Debug to confirm that the `"consent", "update"` gtag event is sent both:
      a. On first page load.
      b. On change of preferences in the Complianz consent banner.

## Changelog entry

* Extract inline consent mode JS to external script.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
@benbowler, please, avoid using the PR as IB approach because it is strongly discouraged. Write IB without coding it beforehand. If you have troubles and not sure which approach to use, the it is better to leave that task for someone else because otherwise you spend time on actual implementation that we are going to include in the next sprint and our next sprint estimates will be inaccurate. Plus, another problem is that the time you have logged for this task is logged as definition time, but in fact it is execution time and it makes our reporting incorrect.

For the current task, please, add full IB anyway mentioning your PR at the end.

**Comment by benbowler** [comment]
@eugene-manuilov make sense, I usually do as you have said and will avoid this in future.

**Comment by eugene-manuilov** [comment]
Thanks, @benbowler. I didn't mean that you need to close your PR though. I have re-opened it. Could you please mention that it can be used as starting point since you have already done some job there.

> * Create a new file `webpack/consentMode.config.js`, modelled on the existing `webpack/conversionEventProviders.config.js`, which compiles the new `consent-mode.js` asset.
> * [ ]  Update `webpack.config.js` to yeild the new config.

No need to create a new config for the consent mode snippet. We should add it to the basic modules config: https://github.com/google/site-kit-wp/blob/fe57e172dcdaa556fdfc7e010cb5577b6a605b91/webpack/basicModules.config.js#L37-L42

> * Create a new action in the `__construct` method, which uses the `wp_enqueue_scripts` to run the new method `enqueue_script`.

It should be added in the `register` method, not in `__construct`.

**Comment by techanvil** [comment]
Just peeking in here. @benbowler, please don't forget this point of the AC:

> - Rewrite to use modern language features.

E.g. we can drop the use of `var`, and we can use the more functional array APIs rather than the current loops if we want. I'd suggest adding a high level point to the IB to rewrite the copied code as appropriate, so this doesn't get missed.

**Comment by benbowler** [comment]
Thanks @eugene-manuilov @techanvil, updated.

**Comment by eugene-manuilov** [comment]
Thanks, @benbowler. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified consent mode plugin admin settings.
- Install and activate the WP Consent API plugin and the Complianz plugins, setting up a cookie consent banner.
- Verified GA event on page load and On change of preferences in the Complianz consent banner.
- Verified data in Analytics.


<details>

![image](https://github.com/user-attachments/assets/deebfe7e-a34f-47a7-99cc-5771e8d70f64)

![image](https://github.com/user-attachments/assets/42eb739c-8545-48bb-9777-aeb21eca1657)

https://github.com/user-attachments/assets/dcf580fd-c123-43ab-bb45-50f18bb4a320

</details>
