### ISSUE TITLE
Prevent Consent Mode Setup CTA Banner from being shown if the user toggles Consent Mode via Settings.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8386]
## Feature Description

At present, if the user doesn't engage with the Consent Mode Setup CTA Banner, and instead navigates directly to Settings and enables Consent Mode, then disables it again, when they return to the dashboard the Setup CTA Banner will be displayed.

We should probably ensure the banner is effectively dismissed if the user interacts with the Consent Mode toggle on the Settings screen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Consent Mode Setup CTA banner, should not show again if the user has interacted with the Consent Mode toggle switch in the settings screen.

## Implementation Brief

* [ ] Update `assets/js/components/consent-mode/ConsentModeSwitch.js`:
   * [ ] Get the Consent Mode Setup CTA Banner dismissed state using the `isPromptDismissed` selector with the `CONSENT_MODE_SETUP_CTA_WIDGET_SLUG` slug.
   * [ ] In the `saveSettings` function, if the Consent Mode Setup CTA Banner has not been dismissed, dispatch the `dismissPrompt` actions with the `CONSENT_MODE_SETUP_CTA_WIDGET_SLUG` slug.

### Test Coverage

* None needed.

## QA Brief

* Set up a new site with Site Kit, including the Analytics module. Ensure that Consent Mode banner appears on the Site Kit dashboard, but don't interact with the banner.
* Navigate to Site Kit settings.
* Enable Consent Mode using the toggle switch from Site Kit settings.
* Visit the Site Kit dashboard; the Consent Mode banner should no longer appear.

## Changelog entry

* Update the Consent Mode Setup CTA banner not to be shown if the user toggles the consent mode via settings.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️, but the estimate is too high, I'll change it to 3.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified consent mode banner don't appear if the user toggles consent mode via settings.

<details>



https://github.com/user-attachments/assets/4c53c605-b5bd-4b6b-9244-69a4be6acb06



</details>
