### ISSUE TITLE
Avoid enqueuing duplicate `consent` `update` commands on page load.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8387]
## Feature Description

At present, when using Complianz for the cookie banner, two duplicate `consent` `update` commands are enqueued on page load:

![image](https://github.com/google/site-kit-wp/assets/18395600/f1d20178-d7ac-4cb3-ad9c-86b2f20e9817)

This is because we enqueue the `update` command in response to the `wp_consent_type_defined` event as well as conditionally on page load via `DOMContentLoaded` _if_ `window.waitfor_consent_hook` is _not_ set. This approach roughly follows the example of the [WP Consent API integration example plugin](https://github.com/Really-Simple-Plugins/consent-api-example-plugin/blob/d3efafc4a6b1980e6fb80451d0304d824500434e/main.js#L26-L46).

https://github.com/google/site-kit-wp/blob/fe57e172dcdaa556fdfc7e010cb5577b6a605b91/includes/Core/Consent_Mode/Consent_Mode.php#L157-L165

Complianz [always fires the `wp_consent_type_defined` event](https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/8557e571ce0224509a7bfd80390992cfd6fbe0b2/cookiebanner/js/complianz.js#L938-L939), but it [only defines `waitfor_consent_hook` when Geo IP is enabled](https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/8557e571ce0224509a7bfd80390992cfd6fbe0b2/integrations/wordpress/wordpress.php#L13-L18) (which is only available in the paid version).

![image](https://github.com/google/site-kit-wp/assets/18395600/0088c9c8-db4a-45c4-bed7-a86d7ccda164)

It's possible the same could apply to other CMPs too, although Complianz is the only one we've seen so far which dispatches the `wp_consent_type_defined` event.

We should consider whether to avoid allowing duplicate `consent` `update` commands to be queued in this manner; it's essentially harmless, but it would be nice to reduce clutter in the `dataLayer` array.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Only one `consent` `update` command should be queued regardless of if the `wp_consent_type_defined` event is called.

## Implementation Brief

The goal here is to only trigger the consent update if any of the consent settings have changed.

* [ ] Update `includes/Core/Consent_Mode/Consent_Mode.php`:
   * [ ] Create a new window variable `window._googlesitekitConsents`.
   * [ ] Update `updateGrantedConsent` function:
      * [ ] Before the [gtag call](https://github.com/google/site-kit-wp/blob/73cf3e5dab4e701b5eaf2cde247536fe65f01413/includes/Core/Consent_Mode/Consent_Mode.php#L187), use `Object.find` to compare `window._googlesitekitConsents` with `consentParameters`, if any keys are found to mismatch, then continue to call gtag, if all keys match, do not call gtag.
      * [ ] After the [gtag update consent is called](https://github.com/google/site-kit-wp/blob/73cf3e5dab4e701b5eaf2cde247536fe65f01413/includes/Core/Consent_Mode/Consent_Mode.php#L187), set `window._googlesitekitConsents` to the value of `consentParameters`.

### Test Coverage

* Add test coverage to `assets/js/consent-mode/consent-mode.test.js` to confirm the update command will not be send twice in the above case.

## QA Brief

* Enable Consent Mode in the plugin Admin settings.
* Install and Activate the WP Consent API plugin.
* Install and Activate the Complianz plugin.
* Setup a plugin like GA Debug so you can see events that are triggered.
* Load a page in an incognito window to simulate a new user visiting the site.
* Accept permissions in the consent banner.
* Refresh the page - when the page loads this time, the page should only trigger consent update once.

## Changelog entry

* Update Consent Mode to prevent enqueuing duplicate consent commands on page load.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️,  but the estimate is too high, i'll update it to 3.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that on latest environment duplicate `consent update` commands loads on page load and on dev environment now only one command gets load.
- Tested using complianz plygin.
- Tested for both Accept and deny actions.
- Verified only one consent update command queued regardless of if the `wp_consent_type_defined` event is called.


<details>

**Latest environment -**

![image](https://github.com/user-attachments/assets/e25d1afc-999b-49b0-8fdf-981b2e585ea7)

**Dev environment -**

![image](https://github.com/user-attachments/assets/03c17dfb-6fa2-4272-984d-9a0733678047)


![image](https://github.com/user-attachments/assets/6e6dfa39-a5a9-4b48-a792-674049c13b75)


**When user accept the permissions**

https://github.com/user-attachments/assets/895b05f3-3097-4872-967f-55e69e4ed842

**When user deny the permissions**


https://github.com/user-attachments/assets/8ac6583b-b6ef-4f5c-bede-74aa5b01dfbc

</details>
