### ISSUE TITLE
Update the description copy in the Consent Mode modal.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8389]
## Feature Description

The description copy in the Consent Mode modal currently reads as follows:
- _Disabling consent mode will remove the additional tag from your website. In the European Economic Area, you will no longer be able to track:_

![image](https://github.com/google/site-kit-wp/assets/18395600/74c78bc0-8866-423d-bf0a-75948a7f7f55)

This copy should be updated to follow the current [Figma design](https://www.figma.com/file/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?type=design&node-id=18-7217&mode=design&t=ALUBQ8QQpbygr3Pk-0):

![image](https://github.com/google/site-kit-wp/assets/18395600/3bf0078a-16d4-446a-bbcc-83db6105dfa8)

However the text "and the United Kingdom" should be appended in line with the changes made in https://github.com/google/site-kit-wp/issues/8443.

See also the related issue https://github.com/google/site-kit-wp/issues/8381.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Consent Mode disable modal should have its description copy updated as follows:
  - _Disabling consent mode may affect your ability to track these in the European Economic Area and the United Kingdom:_

## Implementation Brief

* [x] Update the `subtitle` prop of the `ModalDialog` component to the new copy in `assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.js`
https://github.com/google/site-kit-wp/blob/cc9f305aa736d7509e303ead63c37f089b21b221/assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.js#L78-L81

### Test Coverage

* No new tests required.

## QA Brief

* Navigate to `Settings->Admin Settings` page.
* Disable the `Enable consent mode` toggle switch.
* Ensure the modal description is updated according to the AC.

## Changelog entry

* Update the description copy in the Consent Mode modal, simplifying the text and making it clear that measurement from visitors from the UK may also be affected by disabling Consent Mode.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by bethanylang** [comment]
@techanvil Do we want to update the language here to "European Economic Area and the United Kingdom" to align with the other updates? cc @aaemnnosttv

**Comment by techanvil** [comment]
Thanks @bethanylang, good spot. Yes, we should include the UK as part of the copy here, I've amended the description + AC accordingly.
