### ISSUE TITLE
Readme raises new validation warnings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8390]
## Feature Description

The plugin's readme.txt recently started raising the following new validation warnings:

> One or more tags were ignored. Please limit your plugin to 5 tags.
> The Changelog section is too long and was truncated. A maximum of 5,000 words is supported.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The plugin readme should be updated to remove the tags for `site-kit` and `tag-manager` from its `Tags` header line
* The plugin readme's changelog section should be truncated to the latest release only, followed by a link to `[See changelog for all versions](https://raw.githubusercontent.com/google/site-kit-wp/main/changelog.txt).` – this link is expected to 404 until the release is prepared
	*  The current changelog (including all versions) should be copied to a new `/changelog.txt` file (including the `== Changelog ==` heading)

## Implementation Brief

* [x] Remove the tags in the AC
* [x] Create the new `changelog.txt` file as described in AC
* [x] Truncate Changelog section of `readme.txt` to latest version only
* [ ] Merge https://github.com/google/site-kit-wp/pull/8391

### Test Coverage

* No changes

## QA Brief

* Test the readme using the [official validator](https://wordpress.org/plugins/developers/readme-validator/) to ensure no warnings are raised ("Notes" are okay)
* Check link at bottom of `readme.txt` (if 404, update `main` to `develop` to test if branches have not split yet)

## Changelog entry

* N/A

**Comment by techanvil** [comment]
## QA :white_check_mark: 

- Validated `readme.txt` with the WordPress readme validator:

![image](https://github.com/google/site-kit-wp/assets/18395600/cdd1f7f2-4cfc-41cd-ad32-16cb286d376a)

- Confirmed the link at the bottom of the readme works (replacing `main` with `develop` as per the QAB):

![image](https://github.com/google/site-kit-wp/assets/18395600/e46a944b-6216-4b6c-b757-3c6c926ef6fb)
