### ISSUE TITLE
"Set up Google Analytics" step not appearing in SK setup flow

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8397]
## Bug Description

In the Singular Analytics Module feature branch, when setting up Site Kit with the option to set up Google Analytics, the fourth step "Set up Google Analytics" isn't appearing.

[Asana Task](https://app.asana.com/0/1206822627583085/1206832148100121/f)

Reported by @wpdarren in the Asana Task:

> Usually, when you select Analytics in the Site Kit setup flow, there's a step 4 to set up Analytics. I noticed that on the feature branch, this is not appearing.  Here's what I see.
> ![image](https://github.com/google/site-kit-wp/assets/20284937/078dd118-0adf-4908-a3a7-1ce0435a1494)
> This is what I see on the latest release. 
> ![image](https://github.com/google/site-kit-wp/assets/20284937/110d88ae-641d-44da-b800-843f51705315)
> I am redirected to set up Analytics as expected, but the setup screens are confusing because the CTA appears saying go to dashboard and then it sets up Analytics

## Steps to reproduce

1. Use the SAM feature branch.
2. In the SK setup splash screen, choose to connect Analytics, and start setup.
3. In the setup flow, observe that there are only three steps, instead of four.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- When setting up Site Kit with the option to set up Analytics chosen, the fourth "Set up Google Analytics" step should appear in the setup flow in the SAM feature branch, as it does in the `develop` branch.

## Implementation Brief

* [ ] Add the following missing filter usage to the `Modules\Analytics_4::register` method:
https://github.com/google/site-kit-wp/blob/cc9f305aa736d7509e303ead63c37f089b21b221/includes/Modules/Analytics.php#L113-L120
  * [ ] Add an explanatory comment explaining what this filter is used for here.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

- Follow the above-mentioned "Steps to reproduce".
- Verify that the fourth "Set up Google Analytics" step appears.

## Changelog entry

* Fix a bug that prevented "Set up Google Analytics" step from appearing in Site Kit setup flow.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB also looks good. ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The fourth "Set up Google Analytics" step appears:
  - Tested setting up the Site Kit on a new site and Analytics account. 
  - Tested setting up Site Kit and Analytics on a reset site. Made sure account/property, etc., was defaulted. 
  - Tested setting up Site Kit without Analytics.  Made sure 3 steps continued to appear. 
  - Tested when permissions were not given. Ensure the user is redirected to the dashboard with a permissions error. Then, I set up Site Kit again and, this time, gave permission. 4 steps appeared.

![image](https://github.com/google/site-kit-wp/assets/73545194/57a58791-5711-4cc9-8930-2eda1e0ecde3)
