### ISSUE TITLE
Consent Mode related console error on View only Dashboard 

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8408]
## Bug Description

While testing Dashboard Sharing, I encountered a console error message on the view only, main and entity dashboard.  `Google Site Kit API Error method:GET datapoint:consent-mode type:core identifier:site error:"Sorry, you are not allowed to do that."` Chatting to @techanvil on Slack and he confirmed that we should avoid making the call on the view-only dashboard for the new Consent Mode CTA banner notification. 

## Screenshots

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d96ca24ff8296c00db3df8ee643291683391feb7/image.png" alt="image.png" />

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Consent mode API (`GET:consent-mode`) should not be called in shared dashboard, thus preventing any permission related console errors. 

## Implementation Brief

* [x] Do not render `<ConsentModeSetupCTAWidget` that calls the aforementioned API in `DashboardMainApp` and `DashboardEntityApp` in view-only dashboard. ie. `{ ! viewOnlyDashboard && <ConsentModeSetupCTAWidget /> }`

### Test Coverage

* No changes needed. 

## QA Brief

* Set up Site Kit and share the Analytics module with a view-only user.
* Login as a view-only user.
* Open the Network tab and ensure no calls were made to the `GET:consent-mode` API.
* Ensure that no network error occurs for the above API endpoint.
* Verify the above in the Main and the Entity dashboard.

## Changelog entry

* Prevent a Consent Mode related console error on the view-only dashboard.

**Comment by kuasha420** [comment]
I've been able to reproduce this easily on shared dashboard. Moving forward straight to IBR. :tada:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- On the Network tab no calls were made to the `GET:consent-mode` API.
- Ensured that no network error occurs for the above API endpoint.
- Verified the above in the Main and the Entity dashboard.
- No console errors occured as per ticket description. 

![image](https://github.com/google/site-kit-wp/assets/73545194/3e80cdae-dc30-4c8e-99d0-463e8885605b)
![image](https://github.com/google/site-kit-wp/assets/73545194/3544e2b9-02b5-414b-b637-d276974975e6)
