### ISSUE TITLE
Search queries in the "Top search queries" widget are overflowing on the shared dashboard at narrow viewports

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8417]
## Bug Description

When viewing the "Top search queries" widget on the shared dashboard at narrow viewports, long search queries can currently overflow the clicks and impressions metrics.

## Steps to reproduce

1. Login to Site Kit as an admin and share Search Console.
2. Login as a second user with shared access to Search Console and scroll down to the "Top search queries" widget.
3. Ensure the viewport is set to a relatively narrow width.
4. See that long search queries overflow the clicks and impressions metrics.
5. Note that this is of course dependent on having some long search queries appear in the list for the connected Analytics property. I discovered this using the `oi.ie` property. Alternatively, it can be verified using Storybook by making the search results a bit longer for the [view-only story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/search-console-module-components-view-only-dashboard-popular-keywords-widget--loaded).

## Screenshots

_Search queries overflow in the "Top search queries" widget:_
![image](https://github.com/google/site-kit-wp/assets/18395600/e4684a78-4ad0-48bb-be32-1d11a6d720ac)

_They should show ellipses similarly to the "Top performing keywords" Key Metrics widget:_
![image](https://github.com/google/site-kit-wp/assets/18395600/282f41e8-4051-4f3d-840e-d11e79998acb)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any with a narrow enough viewport
 - Plugin Version: noticed on 1.122.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When viewing the "Top search queries" widget on the shared dashboard at narrow viewports, long search queries should not overflow the clicks and impressions metrics, and should instead be truncated with ellipses (similarly to the "Top performing keywords" Key Metrics widget).

## Implementation Brief

* [x] In `assets/sass/components/global/_googlesitekit-table.scss`:
  * [x] Add styling for `.googlesitekit-table .googlesitekit-table__body-item-content span` for a max viewport width of `$bp-tablet` to the following:
  
    ```
    display: block;
    overflow: hidden;
    text-overflow: ellipsis;
    ```
    * [x] This is similar to what is set for `.googlesitekit-table .googlesitekit-table__body-item-content .googlesitekit-cta-link`.

### Test Coverage

* No tests need to be added/updated.
* Update any failing VRT references if required.

## QA Brief

* Follow aforementioned steps to reproduce and verify that queries don't overflow the table column. 

## Changelog entry

* Fix bug that caused "Top search queries" widget to overflow on small screens.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
QA Update ✅ 

- Tested on dev environment.
- Verified when viewing the "Top search queries" widget on the shared dashboard at narrow viewports, long search queries  not overflow the clicks and impressions metrics, and  instead be truncated with ellipses (similarly to the "Top performing keywords" Key Metrics widget).

<details>

Latest:

![image](https://github.com/google/site-kit-wp/assets/94359491/0acb3835-90c7-48ce-ba53-728ba32e55fc)

Develop :

![image](https://github.com/google/site-kit-wp/assets/94359491/40d3ec73-5861-47e2-a2ec-f4608bffb659)

![image](https://github.com/google/site-kit-wp/assets/94359491/0aef7d13-15ea-4c4c-ba7f-fe75cc1f5561)

</details>
