### ISSUE TITLE
Update GitHub actions using deprecated runtimes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8428]
## Feature Description

Some GitHub actions that we use have started to raise deprecation warnings.

E.g.
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/setup-node@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

This is not an exhaustive list, but an example that references several actions that we use across many workflows.

See also https://github.com/google/site-kit-wp/issues/6188

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All GitHub action workflows should be audited for workflows using deprecated runtimes (this is surfaced in workflow runs as an annotation ([example](https://github.com/google/site-kit-wp/actions/runs/8424485346)))
* All actions using deprecated runtimes should be upgraded to a version that is free of deprecations
    * In the absence of an upgrade that satisfies this criteria, steps should be outlined for each instance to be upgraded or replaced in the future and the relevant deadline that this must happen by

_Note: this has no effect on the Node runtime used in our jobs (i.e. controlled by nvmrc) it's specific to the [runtime used by actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions)_

## Implementation Brief

* [ ] Update all usage of `actions/checkout@v3`/`actions/checkout` to `actions/checkout@v4`
* [ ] Update all usage of `actions/setup-node@v3`/`actions/setup-node` to `actions/setup-node@v4`
* [ ] Update [`google-github-actions/auth@v1`](https://github.com/google/site-kit-wp/blob/d6c58d6d644209b60469061c1b04a3008afc5b7c/.github/workflows/zips.yml#L197) to use `google-github-actions/auth@v2`. From the [changelog for `google-github-actions/auth`](https://github.com/google-github-actions/auth/releases/tag/v2.0.0) it does not look like there are any obvious breaking changes that would prevent us from upgrading.
* [ ] Update `peter-evans/find-comment@v2` to `v3`
* [ ] Update `peter-evans/create-or-update-comment@v2` to `v4`

Note: the [compressed size action](https://github.com/google/site-kit-wp/blob/d6c58d6d644209b60469061c1b04a3008afc5b7c/.github/workflows/compressed-size.yml#L42) (see: https://github.com/google/site-kit-wp/actions/runs/8467166896) uses Node 12 and has no upgrade path, so it won't be updated.

### Test Coverage

* No test updates needed, but check all actions to ensure no deprecation notices appear for Node 16 usage from our actions.

## QA Brief

* No QA needed; CI tests passing is all that's needed. Once merged, this can be moved directly to approval. 🙂 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
Moved straight to Approval since there is nothing to QA.

**Comment by aaemnnosttv** [comment]
## ❌ Approval

There are still a number of instances of actions that need updating as can be seen in the annotations of action runs such as this one https://github.com/google/site-kit-wp/actions/runs/9513898534

<img width="1383" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/ebd16216-ab14-4737-a51f-c9968cdc7286">

Please open a follow up issue to address the remaining instances.
