### ISSUE TITLE
Update Consent Mode messaging to reflect the inclusion of non-EEA members in the EU user consent policy

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8443]
## Feature Description

The initial messaging in the Consent Mode feature only mentions the EEA region, but in fact it's necessary to enable Consent Mode for the UK as well, in line with Google's EU user consent policy: https://www.google.com/about/company/user-consent-policy/

We should update the messaging to be more clear and accurate.

Note that some of the existing copy is a bit vague, so not essential to change but it would still be good to improve it:

![image](https://github.com/google/site-kit-wp/assets/18395600/e8be9c3c-ed4e-4935-ab10-f25601e402bc)

Whereas the copy in the disconnection modal is quite explicit and definitely needs to be updated:

![image](https://github.com/google/site-kit-wp/assets/18395600/5355097a-a42d-4d09-a5f8-893c0f74932f)

We should also update the related support page which again only mentions the EEA: https://sitekit.withgoogle.com/documentation/using-site-kit/consent-mode/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Change "European Economic Area" to "European Economic Area and United Kingdom" in https://github.com/google/site-kit-wp/blob/e0232dd614844f7b3f3bd11a539e91821403bdb6/assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.js#L78-L81

## Implementation Brief

* [ ] Add "and the United Kingdom" to the string at https://github.com/google/site-kit-wp/blob/e0232dd614844f7b3f3bd11a539e91821403bdb6/assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.js#L78-L81

Note: the content in the support pages is external to the repo so I've followed-up in Slack to get that change sorted.

The description here mentions some other text that is "vague", but seems worded that way deliberately as an example rather than an exhaustive list, so I think it's best to leave as-is 🙂 

### Test Coverage

* Update VRTs if needed.

## QA Brief

* Disable the consent mode and ensure that the dialog contains `and the United Kingdom` text as mentioned in AC.

## Changelog entry

* Update Consent Mode messaging to mention the UK as well as the EEA.

**Comment by bethanylang** [comment]
Pedantic grammar recommendation: I'd say we should use "_the_ United Kingdom" consistently here; looks like right now in the ACs we have "United Kingdom" in one place and "the United Kingdom" in another. We're using "the United Kingdom" in the documentation.  :)

**Comment by eugene-manuilov** [comment]
IB ✔️
