### ISSUE TITLE
Add "New" Badge Next To The Ads module

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8448]
## Feature Description

Per [figma](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=850-905&mode=design&t=RIArPNYwngrkNBnm-0) design the Ads module should have a "new" badge showing next to it in `connect more services` and `connected services`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Include the "new" badge next to the Ads module name
* It should match the [figma](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=850-905&mode=design&t=RIArPNYwngrkNBnm-0) design and appear in both `Connect more services` and `Connected services` settings tabs

## Implementation Brief

* [x] Update `assets/js/components/settings/SetupModule.js`
  * In `div.googlesitekit-settings-connect-module__badges` wrapper conditionally render `Badge` component with label `new`
  * Ensure that style matches the figma design linked in AC. You can use `assets/sass/components/settings/_googlesitekit-settings-module.scss` for adding styles if needed
* [x] In `assets/js/components/settings/SettingsActiveModule/Header.js`
  * Do the same, as it also has the same wrapper `div.googlesitekit-settings-module__heading-badges` 

### Test Coverage

* No updates needed

## QA Brief

* Enable `adsModule` feature flag
* Verify that Ads module is showing with `new` badge matching the figma design in connected services, and connect more services

## Changelog entry

* Add a "New" badge to the Ads module in Site Kit settings.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Ads module is showing with a new badge in `connected services` and `connect more services`
- Tested on desktop and smaller viewports. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/abdcba8a-d6fe-43ae-81c8-6b3c163ef3fe)
![image](https://github.com/google/site-kit-wp/assets/73545194/eecc94a2-1141-4edd-8519-6f158a152df1)
![image](https://github.com/google/site-kit-wp/assets/73545194/c95bc05b-bd38-4824-b25e-5b267a681f90)

</details>
