### ISSUE TITLE
include `Module_With_Deactivation` Interface To the Ads module

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8449]
## Feature Description

Ads module is missing the implementation of `Module_With_Deactivation` interface.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ads module should implement `Module_With_Deactivation` interface and include `on_deactivation` method which should delete the module settings

## Implementation Brief

* [x] Update `Google\Site_Kit\Modules\Ads` class
  * Implement the interface and method mentioned in AC
    * Delete the settings in `on_deactivation` method, eq `$this->get_settings()->delete();`

### Test Coverage

* Include test case for `test_on_deactivation` method to the `tests/phpunit/integration/Modules/AdsTest.php`

## QA Brief

* Enable `adsModule` feature flag
* Connect Ads module, then disconnect it
* Try to connect it again, verify that old value is not pre-filled

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tests where done as follows:

- Connected Ads module, then disconnected it successfully. Ensured that old value is not pre-filled for a new setup.
- Test done on Dev branch on WP 6.4.2 PHP 8.0 mainly on these platforms:
   - Cross browsers MacOS Ventura (Firefox, Chrome, Safari) 
   - Windows 11 Edge
   - Mobile (iOS,iPhone 15 Safari)
   - Mobile (ANdroid Samsung S23 Chrome)
   - Tablet (iOS, iPad 10 Safari)
   - Tablet (Android, Galaxy Tab S7 )
- Did one test on MacOS Ventura (Chrome) for WP 6.4.2 and PHP 7.4

Moving ticket to Approved column.
