### ISSUE TITLE
Do not show hyperlinks on post tiles in Top Earning Pages widget on shared dashboard

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#8451]
## Bug Description

As discovered by @wpdarren, currently in the GA4 version of Top Earning Pages widget, the post titles links to analytics report pages on the shared dashboard. This should be replaced with normal text titles as it's done on the Top Earning Contents Key Metrics tile.  

## Screenshots

![image (6)](https://github.com/google/site-kit-wp/assets/6187401/1f9ead6d-1272-4aa2-b64e-d94feea56ae1)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In Top Earning Pages widget, the post titles with hyperlinks should be replaced with text post titles in shared (view-only) dashboard. 

## Implementation Brief

* [ ] In `assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidgetGA4.js`:
    * [ ] In the first column definition in `tableColumns` variable, 
    * [ ] From the inline function passed to `Component`, return the `title` wrapped with a simple `span` when `viewOnlyDashboard` true, instead of the `Link`. 

### Test Coverage

* Add a storybook story and corresponding VRT scenario for view only dashboard. 

## QA Brief

* Enable the Top Earning Pages widget by setting up GA4 + AdSense and linking the accounts.
* Enable dashboard sharing and sign into the shared dashboard with another user who does not have access to the GA4 + AdSense accounts directly.
* View the Top Earning Pages widget in the Monetization section. It should not have hyperlinks to each page; they should be plain text.

## Changelog entry

* Fix bug that caused Top Earning Pages widget to show links in shared dashboard.

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@tofumatt we have a dedicated component for plain output that we use for Key Metrics https://github.com/google/site-kit-wp/blob/266daf0a43cc6747e2bf9176c44f2ed06a863a74/assets/js/components/KeyMetrics/MetricTileTablePlainText.js#L24

Should we not use a similar approach for these kinds of tables in other widgets?

**Comment by kuasha420** [comment]
@aaemnnosttv It makes sense, I can file another issue to introduce the component and refactor this and all our existing widgets to use it. 

There's also another point I raised in the Linked PR about the view only footer - if we decide to remove the empty footer on view only dashboard, we should probably do the same in all other widgets as well.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When signing into the shared dashboard with another user who does not have direct access to the GA4 + AdSense accounts, the Top Earning Pages widget in the Monetization section does have hyperlinks to each page; they are plain text.

![image](https://github.com/google/site-kit-wp/assets/73545194/8ffc5ade-5b01-445d-95df-a380cd5c8724)
