### ISSUE TITLE
Add GA Events for Ads notification

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8458]
## Feature Description

GA Events outlined in our Analytics Events document should be added to the notification for Ads Conversion ID moving to the Ads setting. See the Figma component for context: https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=653-1792&mode=design&t=RocpFoQ8j3kCcpre-0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the notification is rendered, the following `trackEvent` calls should be made:
  * <code>trackEvent( \`{viewContext}_GA_Ads_redirect\`, 'view_notification' )</code> when the notification is rendered/shown to the user. (Because it should only be rendered when the Analytics Settings are visible rendering this notification—eg. the component's `useMount`—is possibly fine, we may not _need_ to check for visibility in the viewport.)
  * <code>trackEvent( \`{viewContext}_GA_Ads_redirect\`, 'confirm_notification' )</code> when the user clicks the link to "Ads Settings" inside the content of the notification and is redirected to Ads Settings
  * <code>trackEvent( \`{viewContext}_GA_Ads_redirect\`, 'dismiss_notification' )</code> when the user clicks the "Got it" button that dismisses the notification but doesn't redirect them

## Implementation Brief

* [ ] Update `assets/js/components/SettingsNotice/SettingsNotice.js`
  * Introduce a new prop, say `dismissCallback` which should be invoked  on button click when present https://github.com/google/site-kit-wp/blob/06b1aacd9001f22803c8b6eae7a484ca186b41aa/assets/js/components/SettingsNotice/SettingsNotice.js#L93-L95
* [ ] Update `assets/js/modules/analytics-4/components/settings/AdsConversionIDSettingsNotice.js`
  * Include `useMount` hook and trigger the `view_notification` event with details from AC
  * Add `onClick` callback to the `Link` component https://github.com/google/site-kit-wp/blob/06b1aacd9001f22803c8b6eae7a484ca186b41aa/assets/js/modules/analytics-4/components/settings/AdsConversionIDSettingsNotice.js#L77-L79 and send `confirm_notification` event with details fro m AC
  * Pass a `dismissCallback` prop to the `SettingsNotice` component and include a callback function to send `dismiss_notification` event with details from AC

### Test Coverage

* Add test coverage for the `dismissCallback` functionality in `SettingsNotice`.

## QA Brief

* Set up a new instance of Site Kit
* Enable internal event tracking support
* Enable `adsModule` feature flag
* Set up the GA4 and Ads modules
* Preferably you should have Ads conversion ID field saved, otherwise if you already visited GA4 settings and saw notification, your Ads Conversion ID is migrated and this field will be empty. So to mitigate this, once Analytics 4 is set up, open a console and paste this snippet: `googlesitekit.api.set( 'modules', 'analytics-4', 'settings', {adsConversionID
: 'AW-12345'})` to set the field
* Ensure that you have a means to monitor GA4 events, such as Tag Assistant or similar
    * Navigate to the GA4 settings component in Site Kit > Settings, and click "edit" 
    * Validate that, upon doing so, a `view_notification` GA4 event is triggered with a `settings_GA_Ads_redirect` event category
    * Follow the link within the notice (to the new Ads Module location) and validate that, upon doing so, a `confirm_notification` GA4 event is triggered with a `settings_GA_Ads_redirect` event category
    * Dismiss the notice via the "Got it" button and validate that, upon doing so, a `dismiss_notification` GA4 event is triggered with a `settings_GA_Ads_redirect` event category

## Changelog entry

* Track GA events for the lifecycle of the Ads Conversion ID migration notification.

**Comment by tofumatt** [comment]
Added a note about test coverage here but otherwise looks good. 👍🏻

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When navigating to the GA4 settings component and clicking `edit`  a `view_notification` GA4 event is triggered with a `settings_GA_Ads_redirect` event category.
- Following the link within the notice (to the new Ads Module location) and validate that, upon doing so, a `confirm_notification` GA4 event is triggered with a `settings_GA_Ads_redirect` event category.
- When dismissing the notice via the `Got it` button and upon doing so, a `dismiss_notification` GA4 event is triggered with a `settings_GA_Ads_redirect` event category.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/1c5d7171-89f9-4c4f-85c6-eb3e62195dcd)
![image](https://github.com/google/site-kit-wp/assets/73545194/798edcb4-2871-4010-8417-724c0f8a7e68)
![image](https://github.com/google/site-kit-wp/assets/73545194/03692c7a-df2d-42ae-bfdb-7dbce80ad7fc)

</details>
