### ISSUE TITLE
Do not bundle client services that are no longer necessary

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8459]
## Feature Description

We recently removed the legacy `Analytics` module (UA) from Site Kit as part of the Singular Analytics Module epic. @aaemnnosttv kindly pointed out [here](https://github.com/google/site-kit-wp/issues/7843#issuecomment-2018207705) that we're still bundling the legacy client services which should no longer be needed.

https://github.com/google/site-kit-wp/blob/06b1aacd9001f22803c8b6eae7a484ca186b41aa/scoper.inc.php#L18

The above, including any other client services that we no longer need should not be bundled.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Legacy Analytics services are not bundled anymore in the php scoper.

## Implementation Brief

* [ ] Remove these lines from the `scoper.inc.php`:
https://github.com/google/site-kit-wp/blob/06b1aacd9001f22803c8b6eae7a484ca186b41aa/scoper.inc.php#L18
https://github.com/google/site-kit-wp/blob/06b1aacd9001f22803c8b6eae7a484ca186b41aa/scoper.inc.php#L20

### Test Coverage

* No changes required.

## QA Brief

* Set up the plugin and activate the Analytics module.
* Do a quick smoke testing to ensure that everything looks as usual in Analytics widgets, settings and setup flow.

## Changelog entry

* Remove legacy Analytics client services from the bundle, as they are no longer necessary following the removal of the UA module.

**Comment by bethanylang** [comment]
@nfmohit Cann you please add a priority label here? TY!

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by benbowler** [comment]
@eugene-manuilov good catch, updated the IB.

**Comment by aaemnnosttv** [comment]
@benbowler @eugene-manuilov I touched on this in my work on the latest hackathon, and found we can greatly simplify our scoper config with a single `Finder` instance that automatically sources all non-dev dependencies via Composer. The implementation is quite minimal too, so I'll propose this in a PR since it's basically already done.

**Comment by eugene-manuilov** [comment]
Thanks, @benbowler. IB ✔️. I'll adjust the estimate to be `3` instead of `1` to make sure we have enough time for code review and testing.

**Comment by hussain-t** [comment]
Hi @eugene-manuilov, I’ve merged the PR. However, I noticed the QAB is missing. Could you please update it, even if it just states, “No testing required for these changes”? Thanks!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Done smoke testing of analytics setup, settings and widgets.
- Verified analytics setup flow, settings and widgets working same as latest environment.

<details>


Uploading Recording #1442 (2).mp4…

</details>
