### ISSUE TITLE
Unable to Set up Ads Module with Ads Blocker Enabled

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8461]
## Bug Description

When the user has an AdBlocker enabled (either installed locally or on a browser extension) they are unable to set up Ads Module.  When it's enabled a message appears when the Complete setup CTA is enabled.  The error is not user-friendly: `Error: You are probably offline.` and additional errors appear in the console. 

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
googlesitekit-api-1f086b18588694520d28.js:3 Google Site Kit API Error method:POST datapoint:settings type:modules identifier:ads error:"You are probably offline." (anonymous) @ googlesitekit-api-1f086b18588694520d28.js:3
```

https://github.com/google/site-kit-wp/assets/73545194/bd56b44e-97e3-4ea2-84c1-5a90e9ccb1bd

## Steps to reproduce

1. Enable an AdBlocker (e.g. AdBlock chrome extension) 
2. Make sure `adsModule` feature flag is enabled.
3. Go to `Connect More Services` tab in Site Kit Settings
4. Setup the Ads Module.  
5. Enter a `Conversion Tracking ID` and click the `Complete setup` CTA button.
6. See error on screen and in console.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Just adding here that this also breaks the migration of the conversion ID to the new Ads module. You can see this in the [recording](https://www.loom.com/share/45627dbe1ccc4ecdb17c371408f4d622) (see at 1:15) I captured with an Ad Blocker active in my browser. When using a site that hasn't yet had the **adsModule** feature flag switched on, follow these steps:

1. Ensure there is an Ads conversion ID entered via the Analytics module field.
2. Switch on the adsModule feature flag and select the tester plugin develop branch.
3. Navigate to Site Kit > Settings but DO NOT open the Analytics settings.
4. Go to Connect More Services to check that the Ads module is available to connect but again DO NOT select this.
5. Navigate back to Connected Services and open the Analytics settings.

**Comment by bethanylang** [comment]
As noted in [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1712677575542269?thread_ts=1712662884.667669&cid=CBKKQEBR9), closing this as `wontfix` because we unfortunately cannot do anything to make setup work while an ad blocker is present. However, we can mitigate by blocking users from starting Ads setup if an ad blocker is detected (similar to the AdSense setup), which we will create a separate issue for.
