### ISSUE TITLE
UX/UI enhancement when AdSense and Analytics are already linked for new GA4 integration

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8463]
## Bug Description

I noticed while testing `AdSense+GA4 integration` that when a site has AdSense and Analytics linked when you set up Site Kit and AdSense and Analytics modules, the `Link Analytics and AdSense` CTA and overlay appears.  We do have a cron job running after 24 hours, but at the time of testing, I had not realised this was also for sites already linked. 

I feel we should look at improving the UX/UI here so that the user does not have to wait 24 hours for the data to appear in the `Top Earning Pages` widget If the modules are already linked. 

@tofumatt suggested some solutions in this [Slack thread](https://10up.slack.com/archives/CBKKQEBR9/p1712062254017059) on how we might want to enhance the experience. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b90f9d311643ea7cbca105718c4d5e8091e4d6d/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8650b5164d400d37c7d6f317e1dcaecfb5def313/image.png" alt="image.png" />

## Steps to reproduce

1. Connect Site Kit with Analytics and AdSense
2. User a Google that has an AdSense account that is linked for the two modules.
3. Go to the Monetization section of the dashboard, and observe that the dashboard widget shows that Analytics and AdSense are not yet connected. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the Analytics module is already connected, and then AdSense module is successfully connected/considered setup, the check to see if Analytics and AdSense are linked (usually run as a cron task every 24 hours) should be **run immediately**—or at least scheduled to run immediately in the background such that the user does not need to wait 24 hours to see data that requires linked Analytics + AdSense accounts.
* In short: if a user's Analytics + AdSense accounts are already linked, they should be detected as linked immediately (or, at minimum, scheduled to be detected in a cron job in X minutes) after the AdSense module is connected.

## Implementation Brief
 
* [ ] Update `includes/Modules/Analytics_4/Synchronize_AdSenseLinked.php`
  * Add new cron constant, say `CRON_INITIAL_SYNCHRONIZE_ADSENSE_LINKED` 
  * Add new method, using the `maybe_schedule_synchronize_adsense_linked` logic, but instead it should use `CRON_INITIAL_SYNCHRONIZE_ADSENSE_LINKED` for cron slug, and use `time()` only for timestamp so it is executed without a future delay. Rest can be cloned from referenced method. You can name method, like `maybe_run_synchronize_adsense_linked` for example
* [ ] Update `includes/Modules/Analytics_4.php` 
  * In `register` method
    * If AdSense is connected, instantiate AdSense settings instance, and subscribe to `on_change` method. You can see an example here https://github.com/google/site-kit-wp/blob/90205bbe48900b386b18984ec68bd8940a9962c8/includes/Modules/AdSense.php#L154-L156
    * Like in the example above, check if the `accountID` setting changed, and if `accountStatus` is `ready`
    * If conditions are met, invoke `maybe_run_synchronize_adsense_linked` method of `Synchronize_AdSenseLinked` class, which is instantiated already to the `$synchronize_adsense_linked`

### Test Coverage

* Update `tests/phpunit/integration/Modules/Analytics_4Test.php`, to include additional test to cover the case when AdSense `accountID` setting changes value, and `accountStatus` is `ready`. Verify that cron `CRON_INITIAL_SYNCHRONIZE_ADSENSE_LINKED` is scheduled to run immediately.

## QA Brief

* Setup Site Kit and connect Analytics and AdSense modules 
  * Use a property that have AdSense linked, for example `oi.ie`
* After AdSense is connected verify that linked status is detected and right notification appears
  * Also vice-versa - When AdSense is firstly connected, and then the Analytics module gets connected

## Changelog entry

* Update Analytics and AdSense modules to check the linked status as soon as one of these modules is connected.

**Comment by tofumatt** [comment]
@zutigrm Why involve the client-side for this logic? It can be done entirely in PHP I'd think, using the `on_change` handler for AdSense settings: https://github.com/google/site-kit-wp/blob/6ba5f3dea4238b672980cde14a87694a6f28f2a5/includes/Modules/AdSense.php#L153-L160

We already _reset_ the AdSense "linked" settings in Analytics when the user's account ID in AdSense changes. Arguably, we could also check there to make sure there's a valid Account ID being set and queue the AdSense update to run immediately. That way, if the user sets the Account ID from previously not having had one, or sets the Account ID to something new, we check immediately.

After that we'll still check every 24 hours, but that way anytime an AdSense account is added we check to make sure it's linked. We shouldn't need any JS to do this.

(We might also want to check if the AdSense account is ready to use before we bother making the "immediate" request, but otherwise what I've outlined is less code and doesn't involve the client at all 🙂 )

**Comment by zutigrm** [comment]
@tofumatt Thanks, for a moment I though maybe it will be more handy to have an action to be able to trigger it on demand from client side. It's a good point, better to attach it to `on_change` from the backend

**Comment by zutigrm** [comment]
@tofumatt Took another look, actually we do need to this from client side, just recalled why I also didn't take that route, is  that `Synchronize_AdSenseLinked` is under Analytics 4 module, and it uses `Analytics_4` module instance to handle the settings and API. To handle this from on change filter in `AdSense` module, it would need to include `Analytics_4` instance, which is not belonging there, and it doesn't fit our design pattern

**Comment by tofumatt** [comment]
We do instantiate other modules when appropriate in parts of the codebase, like in this migration file: https://github.com/google/site-kit-wp/blob/7c7147922de6d89a77b192329830ec719aa18909/includes/Core/Util/Migration_Conversion_ID.php#L84-L85

In fact, the AdSense module itself has a migration that does that very thing: https://github.com/google/site-kit-wp/blob/7c7147922de6d89a77b192329830ec719aa18909/includes/Modules/AdSense.php#L1115-L1133

So I think it's appropriate to do entirely in PHP; we've done it in the past and it's much more straightforward conceptually. 🙂

**Comment by tofumatt** [comment]
@eclarke1 Yes, shouldn't take too long to work through this for the next sprint 🙂 

@zutigrm I would say that subscribing to the AdSense settings change from the Analytics module makes sense here. Conceptually that's exactly what we're doing, so I don't see an issue with that implementation. It is logically straightforward and doesn't involve the amount of code/effort compared to the JS one. The logic/intent is the same, and the idea that a module subscribes to another's settings changes seems fine to me.

I would add code to Analytics that checks if the AdSense module is enabled and then listen for changes to its settings that would trigger a resync. Doing any of this client-side just seems forced to me.

**Comment by zutigrm** [comment]
@tofumatt Got it. IB updated

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested using oi.ie site which analytics property is already linked with AdSense.
- Verified when analytics is already setup and AdSense module connected later.
- Verified when AdSense module is already setup and analytics connected later.
- Verified for the GA4 property which is not linked with AdSense.
- Also, verified linked status under site health information.
- Verified if a user's Analytics + AdSense accounts are already linked, they detected as linked immediately after the AdSense module is connected. 
- Verified pop up banner do not appear and Top Earning pages widget display under Monetization section.

<details>

**When Analytics is already connected**


https://github.com/google/site-kit-wp/assets/94359491/e6f63c7e-7859-4c8d-a6c3-62dfc7b0365b



**When Analytics is connected later**


https://github.com/google/site-kit-wp/assets/94359491/e95e25cb-6946-46ee-8024-8bc179a55229



**When Analytics is not linked with AdSense.**


https://github.com/google/site-kit-wp/assets/94359491/e93fc625-a4ed-4211-8e85-040781a5cf38

</details>
