### ISSUE TITLE
Disable module settings submit button for invalid settings

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#8467]
## Bug Description

The module settings edit screen (`SettingsEdit`) lets the user submit the form even if there are invalid setting values set.

Currently, if there is an invalid setting value, the button simply says "Save", whereas, it should keep saying "Confirm Changes" but just be _disabled_, so that the user cannot submit the form.

## Steps to reproduce

1. Connect the Analytics and Tag Manager modules.
2. Go to Analytics module settings edit screen.
	1. Notice that even though you've not changed any settings, the submit button is active, which should be disabled. It also says "Save", which I think is incorrect and should instead say "Confirm Changes".
	2. Choose to create a new web data stream.
	3. Enter a web data stream name that already exists, or keep it empty.
	4. Notice that even though there is an invalid field value, the the submit button is active, which should be disabled. It also says "Save", which I think is incorrect and should instead say "Confirm Changes".
2. Go to Tag Manager module settings edit screen.
	1. Notice that even though you've not changed any settings, the submit button is active, which should be disabled. It also says "Save", which I think is incorrect and should instead say "Confirm Changes".
	2. Choose to create a new container.
	3. Keep the container name empty.
	4. Notice that even though there is an invalid field value, the the submit button is active, which should be disabled. It also says "Save", which I think is incorrect and should instead say "Confirm Changes".

## Screenshots

https://github.com/google/site-kit-wp/assets/94359491/edcb36d0-4db6-4702-b350-159c87ee79bd

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the module settings edit form, if the settings have changed and there is a validation error, the submit button should stay disabled.

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by mohitwp** [comment]
I noticed that when user save analytics settings after giving invalid web data stream name or without providing web data stream name then settings gets save and analytics setup status set to incomplete. Now when again user trying to complete setup then user is not able to complete setup even after providing unique web data stream name. In this case complete setup button remains inactive until user selects already exists web data stream. So, in this case user will not able to create new web data stream. Can you implement fix for this or this scenario will be address (most likely not occur) through https://github.com/google/site-kit-wp/issues/8467 which I created to address settings allow saving of invalid web data stream name.


See @nfmohit [comment](https://github.com/google/site-kit-wp/issues/6727#issuecomment-2034108343) on this ticket.

**Comment by nfmohit** [comment]
I have added some ACs to this issue as I have some context. However, as I am not authorised to add ACs to issues for epics that I do not own, I'm leaving this in AC for a suitable person to pick, amend (if needed), and send it to ACR. Thanks!

**Comment by bethanylang** [comment]
@nfmohit Can you please add a priority label here? TY!

**Comment by aaemnnosttv** [comment]
Closing in favor of #8508
