### ISSUE TITLE
AdSense Top Earning Pages Dashboard widget text overlapping design is breaking under mobile viewports on view only dashboard.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#8472]
## Bug Description

AdSense Top Earning Pages Dashboard widget design is breaking under mobile viewports on view only dashboard.

## Steps to reproduce

1. Connect Analytics and AdSense.
2. Link Analytics and AdSense.
3. Share AdSense with non admin users.
4. Login with non admin users.
5. Check AdSense Top Earning Pages Dashboard widget in mobile viewports.

### View only Dashboard

![image](https://github.com/google/site-kit-wp/assets/94359491/55b87ddf-1421-4157-8fa3-f26ba90ca390)

### Admin main Dashboard

![image](https://github.com/google/site-kit-wp/assets/94359491/206f7f62-20af-4b4b-a27a-a998abb57906)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the title of a page is too long to fit into the container/screen size and would overflow, it should stop before the "earnings" section and use an ellipsis to indicate there is more text that is not visible.
* A `title` attribute should be added to the title so users can hover/use assistive technologies to access the rest of the (potentially hidden) text.

## Implementation Brief

*See comment below*

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by mohitwp** [comment]
@benbowler  I verified this again on latest and dev environment using BrowserStack and Chrome dev mode.  Seems like this issue is resolved. I'm not able to reproduce this issue.

![image](https://github.com/google/site-kit-wp/assets/94359491/37a62242-3a39-4804-ac15-ef14da4ef52a)

**Comment by tofumatt** [comment]
Oh, cool, looks like it was a duplicate, as I do recognise the bug. Awesome, closed as fixed! 👍🏻
