### ISSUE TITLE
Error style isn't cleared when submitting changes in settings edit

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8481]
## Bug Description

The settings edit interface for a module has additional styling applied when an error is raised in response to saving the settings.

https://github.com/google/site-kit-wp/blob/c04724c4dceae289affe66424690673691f6cb74/assets/js/components/settings/SettingsActiveModule/Footer.js#L106-L110

https://github.com/google/site-kit-wp/blob/c04724c4dceae289affe66424690673691f6cb74/assets/js/components/settings/SettingsActiveModule/index.js#L63-L66

However, this state is never cleared which can leave a lingering error appearance after the error has been addressed or is otherwise no longer relevant.

## Steps to reproduce

1. Set up SK with no additions
2. Connect GA with an existing property
3. Edit GA settings and choose to create a new property or datastream and submit  
	- Note this is technically an error
5. Follow the prompt to grant additional scope
6. Back in settings once granted, see the interface shows with the red error border, even after completing the property creation (click edit again)

## Screenshots

<img width="377" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/3e5ab303-4b7e-4eed-962d-95026acf98eb">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The settings error appearance should be removed as soon as the settings submission completes successfully

## Implementation Brief

* [ ] Update the `else` block of the `handleConfirm` to clear the value for `errorKey` since the submission was successful

### Test Coverage

* No changes necessary

## QA Brief

* Follow the "Steps to reproduce".
* Ensure "Confirm changes" has been clicked and the settings have saved successfully.
* Click edit again, the red border should now be removed.

## Changelog entry

* Ensure the error style for the Settings edit screen is cleared when settings are saved successfully.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

Tested on dev environment.
 Verified that issue is resolved and the red border is removed once the setting is saved, and when the user clicks the edit button again.

<details>


https://github.com/user-attachments/assets/d1643059-06dd-482b-a481-a522f17b949e

</details>
