### ISSUE TITLE
Add ESLint rule to warn about direct use of `Date`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8483]
## Feature Description

There are several cases where we have needed to have conditional behavior based on time. For short periods of time this is usually fine. However, in cases that involve periods of time of one or more days, we have a core abstraction for called the "reference date" (which is a proxy to the current date). This is usually what we want to use for such things as it is easy for us to override for the purposes of QA and other testing. In an effort to encourage this to be used consistently, we should introduce an ESLint rule to warn about using `Date` directly.

Example https://github.com/google/site-kit-wp/issues/8248#issuecomment-2038299364

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new ESLint rule should be created that warns about usage of `new Date()` and `Date.now()`.
* Existing usage of `new Date()` and `Date.now()` should be audited and either:
  * Ignored with a comment explaining why they are not using the reference date
  * Updated to use `select( CORE_USER ).getReferenceDate()` where appropriate

## Implementation Brief

* [ ] Begin with this [draft PR with base rule and test](https://github.com/google/site-kit-wp/pull/8749) confirm this matches the AC and update an needed ready for release.
* [ ] Update each reference of `new Date()` and `Date.now()`:

**These uses _should_ be updated to use `select( CORE_USER ).getReferenceDate()`:**

 * assets/js/components/notifications/BannerNotification/index.js 109:31 and 224:22 
 * assets/js/components/notifications/CoreSiteBannerNotifications.js 38:28 and 65:6
 * assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartGA4.js 139:27 
 * assets/js/googlesitekit/datastore/user/expirable-items.js 168:42
 * assets/js/googlesitekit/datastore/user/feature-tours.js 116:38 and 490:10
 * assets/js/googlesitekit/datastore/user/prompts.js 131:44
 * assets/js/modules/analytics-4/components/settings/AdsConversionIDSettingsNotice.js 62:3 
 * assets/js/modules/analytics-4/datastore/properties.js 643:4  and 686:29
 * plugins/google-site-kit/assets/js/modules/analytics-4/datastore/report.js 186:29  
 * assets/js/modules/analytics-4/hooks/useMigrateAdsConversionID.js 95:42 (Although this will be removed in #8484)

**These uses _should be left as is_ and should use some form of `eslint-disable...` comment to prevent the rule from being triggered:**
*Add more to the description as to why the rule has been ignored, I've included a basic description below.*

 * assets/js/components/consent-mode/ConsentModeSetupCTAWidget.stories.js  96:18 - Mock date value for testing only
 * assets/js/components/notifications/GA4AdSenseLinkedNotification.stories.js 34:15 - Mock date value for testing only
 * assets/js/googlesitekit/api/cache.js 194:18 and 232:27 and assets/js/googlesitekit/api/cache.test.js
  88:30 - Caching should not be dependent on datastore reference date
 * assets/js/googlesitekit/api/index.test.js 782:56 - Date used for tests
 * assets/js/googlesitekit/datastore/site/cache.test.js - Date used for tests
 * assets/js/googlesitekit/datastore/site/html.js 56:15 and assets/js/googlesitekit/datastore/user/adblocker.js 75:19  - Cachebust does not need to be dependent on selector
 * assets/js/googlesitekit/datastore/user/date-range.js 38:32 and assets/js/googlesitekit/datastore/user/date-range.test.js
  331:31 - This is the reference date's own initialisation and it's test
 * assets/js/googlesitekit/datastore/user/expirable-items.test.js - Date used for tests
 * assets/js/googlesitekit/datastore/user/feature-tours.test.js - Date used for multiple test
 * assets/js/googlesitekit/datastore/user/prompts.test.js 135:46 - Date used for tests
 * assets/js/modules/analytics-4/components/settings/AdsConversionIDSettingsNotice.test.js - Date used for multiple tests
 * assets/js/modules/analytics-4/datastore/properties.test.js - Date used for multiple tests
 * assets/js/modules/analytics-4/utils/extract-dashboard-data.js 109:16 - Cannot use selector here without refactoring to hook
 * assets/js/modules/tagmanager/datastore/__factories__/builders.js - Multiple uses in factory
 * assets/js/util/convert-time.test.js 90:4 and 91:4 and assets/js/util/date-range/is-valid-date-instance.test.js 29:4 - Time specific tests
 * assets/js/util/errors.test.js and assets/js/util/tracking/createInitializeSnippet.js 59:24 - Date used for tests
 * plugins/google-site-kit/webpack/common.js 62:18 and 77:18 - Date used to generate document comments

### Test Coverage

* As this touches many files in the app it's important to fix any issues causing tests to fail.
* Where functions have been updated to use reference date, where their tests are expecting Date.now, they should not break by default as the referenceDate defaults to Date.now, however this datastore may need to be setup for the tests to be able to access it.

## QA Brief

* No QA needed since changes are only related to ESLint rules. It can be moved to approval after MR

## Changelog entry

* N/A

**Comment by benbowler** [comment]
I created a [draft PR](https://github.com/google/site-kit-wp/pull/8749) as I explored options for this rule. I've added a pretty big estimate to this ticket because of the number of files that need to be updated, the effect of each change needs to be considered as well as the update for each test related to the changed files to set up the reference date store.

I skipped a lot of test usages of Date, we may want to update these also to setup and use the reference date resolver, however my thinking was that the tests themselves don't need the reference date as they cannot be effected by the tester plugin and this added additional elements to these tests which is not their core purpose. Happy to discuss more with IB reviewer if you have another opinion.

**Comment by tofumatt** [comment]
IB ✅

**Comment by benbowler** [comment]
Adding a note here to make a suggestion, as we're skipping in all Stories and most tests, we could use a `rule` in the `.eslintrc.json` to disable this rule on these files.

**Comment by tofumatt** [comment]
Moved directly to Approval as no QA is needed.

**Comment by eugene-manuilov** [comment]
Taken this ticket back to create a follow up PR with a few minor improvements.

**Comment by eugene-manuilov** [comment]
Moving back to Approval. We will use a new issue for the follow up PR.
