### ISSUE TITLE
Add support for GA4 pivot reports

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8484]
## Feature Description

As discussed on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1712306329670989), while we are initially implementing the Audience Tiles to use separate, per-audience reports to retrieve the cities and "top content" metrics (one report per audience per metric), we can reduce the number of reports needed by using [pivot reports](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runPivotReport). This will allow us to retrieve metric data for all of the audiences in a single report (i.e., one report per metric).

We should add support for running pivot reports, and refactor the Audience Tiles to use them.

This is not critical to the release and can be done post-launch, hence the P2 priority.

Please also note this comment relating to the `AudienceTile` and `AudienceTiles` refactoring: https://github.com/google/site-kit-wp/issues/8484#issuecomment-2059400367

**Because of the amount of work involved, this ticket has been split, only the GA4 pivot report infrastructure should be worked on in this ticket. Updating the Audience Tiles should be completed in #8726.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* REST and datastore APIs should be added to Site Kit to provide support for retrieving Analytics [pivot reports](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runPivotReport).
  * On the REST front, a new route: `GET /google-site-kit/v1/modules/analytics-4/data/pivot-report`.
  * On the datastore side, a new selector/resolver pair: `getPivotReport()`.
* Update the mock data generator to generate valid responses to pivot reports.

## Implementation Brief

**Pivot Report Infrastructure**
 * [x] Create a new class, `SharedReportParsers`, and move `parse_dimensions`, `parse_dateranges` and `parse_orderby` methods from `includes/Modules/Analytics_4/Report.php` into this class so that they can be shared by `Report` and `PivotReport` classes. Update both of these classes to use these methods from the new `SharedReportParsers` class.

 * [x] Create a new class, `PivotReport`, in `includes/Modules/Analytics_4/PivotReport.php`, based on the existing `includes/Modules/Analytics_4/Report.php` class with these differences:
    * [x] Import the class `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\Pivot` as `Google_Service_AnalyticsData_Pivot`.
    * [x] Create a new protected method `parse_pivots`, which takes `Data_Request` and returns `Google_Service_AnalyticsData_Pivot[]`, modelled on the [parse_orderby method](https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics_4/Report.php#L143-L175).
       * [x] In the `array_map`, create a new `Google_Service_AnalyticsData_Pivot` and use `setFieldNames`, `setLimit` and `setOrderBys` to build each pivot request value.
 * [x] Create a new class. `Request`, in  `includes/Modules/Analytics_4/PivotReport/Request.php`, based on `includes/Modules/Analytics_4/Report/Request.php`, which extends PivotReport:
    * [x] Import the class `Google\Site_Kit_Dependencies\Google\Service\AnalyticsData\RunPivotReportRequest` as `Google_Service_AnalyticsData_RunPivotReportRequest`.
    * [x] In the `create_request` method:
       * [x] The definition of `$request` should create a new `Google_Service_AnalyticsData_RunPivotReportRequest`.
       * [x] Set keep empty rows on the request using `$request->setKeepEmptyRows( true );`
       * [x] Parse and add, dimensions, dimensionFilters and metrics to the pivot report in the [same way as the standard report request](https://github.com/google/site-kit-wp/blob/6ca073088558c78062e8152627dd8796c6ffa3b0/includes/Modules/Analytics_4/Report/Request.php#L57-L137).
          * [x] After parsing but before settings the dimensions to the request, add the `hostName` dimension using `$dimensions[] = array('name' => 'hostName');`.
          *This is needed because of the [hostname dimension filter we add to all requests here](https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics_4/Report/Request.php#L341-L342) to filter out domains other than the WordPress sites domain.*
       * [x] Parse the request pivots with `$pivots = $this->parse_pivots( $data );` and add them to the request using `$request->setPivots( $pivots )`.
       * [x] Return the `Google_Service_AnalyticsData_RunPivotReportRequest` `$request`.
    * [x] Create a new `SharedCreateRequest` class and extract common logic from the `Request` and `PivotRequest` classes' `create_request` methods, into this class.

**REST Endpoint**
 * [x] Create a new REST endpoint `GET:pivot-report`, modelled on `GET:report`, with the following differences:
    * [x] Return a `missing_required_param` `WP_Error` if the `pivots` param is missing from the request.
    * [x] The return statement should call `runPivotReport` GA API method.
* [x] Add the new REST endpoint to the `$datapoints` array in `get_datapoint_definitions`, setting `service` to `analyticsdata` and `sharable` to `true`.

**Pivot Reports store and getPivotReport selector**
 * [x] Create a new `isValidPivots` util in the file `assets/js/modules/analytics-4/utils/pivots-validation.js`, based on `assets/js/modules/analytics-4/utils/report-validation.js`. A valid pivots object must:
    * [x] Be an array of object.
    * [x] Each object in the array must be `isPlainObject`
    * [x] Must have a `fieldNames` prop which must contain and array of strings.
    * [x] If a limit prop is present, it must be a number.
    * [x] If a `orderBys` prop is passed it must validate using the existing `isValidOrders` helper.

 * [x] Create a new file `assets/js/modules/analytics-4/datastore/pivot-report.js`, based on the existing `assets/js/modules/analytics-4/datastore/report.js` file, which creates a new pivot reports datastore:
    * [x] Create a new `createFetchStore` with the following keys:
       * [x] `baseName`: `getPivotReport`
       * [x] `controlCallback` returns `API.get` to the new `pivot-report` endpoint, passing the options, passed to `normalizeReportOptions`.
       * [x] `reducerCallback` should update the `pivotReports` key within the state object with `[ stringifyObject( options ) ]: report,` to save reports to a unique caching key based on their options.
       * [x] `argsToParams` should return `{ options }`
       * [x] `validateParams` should validate params similarly to the [existing `reports.js` file](https://github.com/google/site-kit-wp/blob/ad4eabe6db1e998fcdb7cd44ff48ee032f99b928/assets/js/modules/analytics-4/datastore/report.js#L76-L130) with these key changes/additions:
          * [ ] `pivots.length` invariant violation: pivots must contain at least one value to be a valid pivot report request
          * [x] `isValidPivots(pivots)` invariant violation: must validate a given pivots array using the `isValidPivots` util created above.
          * [x] `! orderby.length` invariant violation: orderbys may not be set at the parent level for pivot reports, if passed this must cause an invariant violation.
       * [x] The `baseInitialState` should contain a single `pivotReports` key with an empty object by default `pivotReports: {}`.
       * [x] `baseResolvers` should contain a single resolver called `getPivotReport`, which uses the `getPivotReport` selector to get the report from the store if present.
          * [x] If this report does not already exist in the store, yield the actions `fetchGetPivotReport` passing through the options.
       * [x] The `baseSelectors` should contain a single selector, `getPivotReport` which returns the report for the stringified key of the request options using `pivotReports[ stringifyObject( options ) ]` 
    * [x] Combine `fetchGetReportStore` with the `initialState`, `selectors`, and `resolvers` created in the last few steps and export the store and it's core components from this file.

 * [x] Import the new pivot-report store as `pivotReport` in `assets/js/modules/analytics-4/datastore/index.js` and include it in the main `combineStores` call to make the store available within the app.

**Data Mock Updates**
 * [x] Update `getAnalytics4MockResponse` in `assets/js/modules/analytics-4/utils/data-mock.js` to generate valid data when given a valid pivot report object.
 * [x] Update the tests to cover new pivot report cases in `assets/js/modules/analytics-4/utils/data-mock.test.js`

### Test Coverage

* [x] Create a new tests file `assets/js/modules/analytics-4/datastore/pivot-report.test.js` which tests the new store and the `getPivotsReport` selector.
* [x] Update `tests/phpunit/integration/Modules/Analytics_4Test.php` adding comprehensive new tests of the new REST endpoint, and the pivot report functions including limits and ordering. *Note: when making a pivot report you cannot pass limit or orderbys to the top level, they must be included for each pivot instead.*
 * [x] Confirm these changes to not cause and regressions in non pivot reports.

## QA Brief

* As there are no new user facing changes in this work, the QA time to should focus on confirming the changes to the reporting infrastructure does not cause any regression to Analytics reporting across the app.
* In order to test the new report selector, `getPivotReport`, you can call the selector in a component or console. [There are some example pivot report options we will use in the Audience Tile refactor ticket #8726](https://github.com/google/site-kit-wp/issues/8726).
eg. pivot report request:
```
		await googlesitekit.data.select( 'modules/analytics-4' ).getPivotReport( {
			startDate: '2024-04-18',
			endDate: '2024-05-15',
			dimensions: [ 'city', 'operatingSystem' ],
			dimensionFilters: {
				operatingSystem: [ 'Windows', 'Macintosh' ],
			},
			metrics: [ { name: 'totalUsers' } ],
			pivots: [
				{
					fieldNames: [ 'operatingSystem' ],
					limit: 3,
				},
				{
					fieldNames: [ 'city' ],
					limit: 3,
					orderby: [
						{
							metric: {
								metricName: 'totalUsers',
							},
							desc: true,
						},
					],
				},
			],
		});
```

## Changelog entry

* Add support for pivot reports from Analytics to improve report request efficiency.

**Comment by benbowler** [comment]
[As discussed here in 8136](https://github.com/google/site-kit-wp/issues/8136) there are a number of refactors required to the AudienceTiles and AudienceTile components which are best worked on here:

1. Once the pivot reports are implemented, [this data restructuring code](https://github.com/google/site-kit-wp/blob/5dcc66aa50bf8847936476c792e8df28cfd49993/assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceTiles.js#L211-L271) should be removed and only the filtered pivot report rows for this audience segment should be passed, without restructuring, to the `AudienceTile` component.

https://github.com/google/site-kit-wp/blob/5dcc66aa50bf8847936476c792e8df28cfd49993/assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceTiles.js#L211-L271

2. [The `AudienceTile` component props](https://github.com/google/site-kit-wp/blob/5dcc66aa50bf8847936476c792e8df28cfd49993/assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceTile/index.js#L50-L63) and internals should be updated to expect the raw report rows instead of the current data structure.

https://github.com/google/site-kit-wp/blob/5dcc66aa50bf8847936476c792e8df28cfd49993/assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceTile/index.js#L50-L63

3. [The `AudienceTile` stories](https://github.com/google/site-kit-wp/blob/5dcc66aa50bf8847936476c792e8df28cfd49993/assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceTile/index.js#L50-L63) can then be updated to use the `data-mock` function instead of the hard coded props:

https://github.com/google/site-kit-wp/blob/5dcc66aa50bf8847936476c792e8df28cfd49993/assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/AudienceTile/index.js#L50-L63

**Comment by benbowler** [comment]
For reference, here is an example pivot report and it's response based on my testing:

<details open>
<summary>Report Options</summary>
<br>

```
	const reportOptions = {
		startDate: '2024-04-18',
		endDate: '2024-05-15',
		compareStartDate: '2024-03-21',
		compareEndDate: '2024-04-17',
		dimensions: [ { name: 'operatingSystem' } ],
		dimensionFilters: {
			operatingSystem: [ 'Windows', 'Macintosh' ],
		},
		metrics: [
			{ name: 'totalUsers' },
			{ name: 'sessionsPerUser' },
			{ name: 'screenPageViewsPerSession' },
			{ name: 'screenPageViews' },
		],
		pivots: [
			{
				fieldNames: [ 'operatingSystem' ],
				limit: 3,
			},
		],
	};
```

</details>

<details open>
<summary>Report Response</summary>
<br>

```
{
  "kind": "analyticsData#runPivotReport",
  "pivotHeaders": [
    {
      "rowCount": 2,
      "pivotDimensionHeaders": [
        {
          "dimensionValues": [
            {
              "value": "Windows"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "Macintosh"
            }
          ]
        }
      ]
    },
    {
      "rowCount": 2,
      "pivotDimensionHeaders": [
        {
          "dimensionValues": [
            {
              "value": "date_range_0"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "date_range_1"
            }
          ]
        }
      ]
    }
  ],
  "dimensionHeaders": [
    {
      "name": "operatingSystem"
    },
    {
      "name": "dateRange"
    }
  ],
  "metricHeaders": [
    {
      "name": "totalUsers",
      "type": "TYPE_INTEGER"
    },
    {
      "name": "sessionsPerUser",
      "type": "TYPE_FLOAT"
    },
    {
      "name": "screenPageViewsPerSession",
      "type": "TYPE_FLOAT"
    },
    {
      "name": "screenPageViews",
      "type": "TYPE_INTEGER"
    }
  ],
  "rows": [
    {
      "dimensionValues": [
        {
          "value": "Windows"
        },
        {
          "value": "date_range_0"
        }
      ],
      "metricValues": [
        {
          "value": "102"
        },
        {
          "value": "1.0392156862745099"
        },
        {
          "value": "1.5"
        },
        {
          "value": "159"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "Macintosh"
        },
        {
          "value": "date_range_1"
        }
      ],
      "metricValues": [
        {
          "value": "51"
        },
        {
          "value": "1.0588235294117647"
        },
        {
          "value": "1.6666666666666667"
        },
        {
          "value": "90"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "Windows"
        },
        {
          "value": "date_range_1"
        }
      ],
      "metricValues": [
        {
          "value": "46"
        },
        {
          "value": "1.0434782608695652"
        },
        {
          "value": "1.75"
        },
        {
          "value": "84"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "Macintosh"
        },
        {
          "value": "date_range_0"
        }
      ],
      "metricValues": [
        {
          "value": "41"
        },
        {
          "value": "1.0487804878048781"
        },
        {
          "value": "1.3953488372093024"
        },
        {
          "value": "60"
        }
      ]
    }
  ],
  "aggregates": [
    {
      "dimensionValues": [
        {
          "value": "RESERVED_TOTAL"
        },
        {
          "value": "date_range_0"
        }
      ],
      "metricValues": [
        {
          "value": "143"
        },
        {
          "value": "1.0419580419580419"
        },
        {
          "value": "1.4697986577181208"
        },
        {
          "value": "219"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "RESERVED_MAX"
        },
        {
          "value": "date_range_0"
        }
      ],
      "metricValues": [
        {
          "value": "102"
        },
        {
          "value": "1.0487804878048781"
        },
        {
          "value": "1.5"
        },
        {
          "value": "159"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "RESERVED_TOTAL"
        },
        {
          "value": "date_range_1"
        }
      ],
      "metricValues": [
        {
          "value": "97"
        },
        {
          "value": "1.0515463917525774"
        },
        {
          "value": "1.7058823529411764"
        },
        {
          "value": "174"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "RESERVED_MAX"
        },
        {
          "value": "date_range_1"
        }
      ],
      "metricValues": [
        {
          "value": "51"
        },
        {
          "value": "1.0588235294117647"
        },
        {
          "value": "1.75"
        },
        {
          "value": "90"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "RESERVED_MIN"
        },
        {
          "value": "date_range_1"
        }
      ],
      "metricValues": [
        {
          "value": "46"
        },
        {
          "value": "1.0434782608695652"
        },
        {
          "value": "1.6666666666666667"
        },
        {
          "value": "84"
        }
      ]
    },
    {
      "dimensionValues": [
        {
          "value": "RESERVED_MIN"
        },
        {
          "value": "date_range_0"
        }
      ],
      "metricValues": [
        {
          "value": "41"
        },
        {
          "value": "1.0392156862745099"
        },
        {
          "value": "1.3953488372093024"
        },
        {
          "value": "60"
        }
      ]
    }
  ],
  "metadata": {
    "currencyCode": "USD",
    "dataLossFromOtherRow": null,
    "emptyReason": null,
    "subjectToThresholding": null,
    "timeZone": "Etc/GMT"
  }
}
```

</details>

**Comment by techanvil** [comment]
Thanks @benbowler, that sounds sensible!

Regarding the IB, it's a good first take. However with the `runReport` and `runPivotReport` GA4 endpoints being two distinct entities, with similar yet crucially different payloads, I would rather see Site Kit provide a similar separation for handling pivot reports, providing a new `GET:pivot-report` datapoint and `runPivotReport()` selector/resolver.

The commonalities between the two can be shared either via existing helpers or extracting new ones where appropriate.

This approach should be cleaner and easier to maintain going forward, and we won't have to maintain a mental model of the differences between the two GA4 endpoints to make sense of a single SK endpoint.

I realise the AC was a bit open to interpretation, so I've updated it AC to be a bit more explicit. Please can you iterate on the IB, taking this into consideration?

**Comment by benbowler** [comment]
Thanks @techanvil, I did consider this split originally, however I thought it would lead to lots of duplicated code as the report structures are so similar, also our report infra already does not directly map to the GA Data API structure. That's not a reason not to improve things though.

I've updated the IB to have distinct pivot selector and REST endpoint and pivot-reports store. I've increased the estimate as there will be lots of additional changes and requirements for additional tests to complete this work.

**Comment by techanvil** [comment]
Hey @benbowler! Indeed, I imagine it will result in a bit of duplicate boilerplate, but I'd hope we can avoid too much duplication of logic. Thanks for updating the IB, here a few further points:

- The update is heading in the right direction, but I would still like to see more separation of the logic. Essentially this has pushed a chunk of the conditional parsing back to `Request::create_request()`, which still has a mix of `runReport` and `runPivotReport` logic. Really what I would prefer is to avoid having to do any conditional logic based on the presence of `$data['pivots']`, and instead have say `RunReportRequest` and `RunPivotReportRequest` classes each of which has their own `create_request()` method (maintaining the single responsibility principle, one endpoint per class). Common logic could be extracted to a utility class (or a shared base class, although I'd personally prefer not to add too much depth to the class heirarchy if we can avoid it). I realise this is a bit more of a refactor but it should give a cleaner end result where each class only contains the logic relevant to it.
- As per the above I'd also like to keep the common logic cleaner and avoid pivot-based conditionality. This applies to `parse_dimensions()` too - I think we can avoid the conditional change you've proposed by instead appending `hostName` to the list of dimensions we pass to `parse_dimensions()` from the pivot-specific `create_request()` method. We might want to refactor `parse_dimensions()` a bit to facilitate this but I would rather keep the common method as simple as it can be, with the pivot-specific stuff in the caller.
- It's commendable you've done the research on how to handle multiple date ranges, but it's not actually clear we're going to need to support them for pivot reports. The initial reports we'll use pivots for that are in `AudienceTiles` don't have multiple date ranges so I would suggest we leave that part out for now to keep things simpler and drop support for the `compare.*Date` args in `getPivotReport()`.

**Comment by benbowler** [comment]
> It's commendable you've done the research on how to handle multiple date ranges, but it's not actually clear we're going to need to support them for pivot reports. The initial reports we'll use pivots for that are in AudienceTiles don't have multiple date ranges so I would suggest we leave that part out for now to keep things simpler and drop support for the compare.*Date args in getPivotReport().

@techanvil to this point, I think we *do* need the data range comparisons to be able to show the % change metrics in the Audience Tiles, we need to be able to get the aggregate totals from the previous period.

---

I'll work through your other key points ASAP, thanks so much for taking a detailed look at this and working through this with me.

**Comment by benbowler** [comment]
Sounds good, added that line.

**Comment by tofumatt** [comment]
QA Brief run as part of the code review, and since it's very straightforward moving directly to Approval, since there isn't much to QA. 😄
