### ISSUE TITLE
Fix unstable `time` based PHPUnit tests

### ISSUE THREAD

**Issue by benbowler** [google/site-kit-wp#8488]
## Bug Description

Despite #6758 and [this comment](https://github.com/google/site-kit-wp/pull/8199#issuecomment-1928991156) a couple of time based tests were missed and remain in the codebase causing instability:

https://github.com/google/site-kit-wp/blob/4f1d3fb446329ff3022fe3085633763cdd02cc94/tests/phpunit/integration/Core/Prompts/REST_Prompts_ControllerTest.php#L79-L91

https://github.com/google/site-kit-wp/blob/4f1d3fb446329ff3022fe3085633763cdd02cc94/tests/phpunit/integration/Core/Prompts/REST_Prompts_ControllerTest.php#L134-L142

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure that the tests listed above use the `assertEqualsWithDelta` assertion for time related keys to ensure better test stability when run on CI.

## Implementation Brief

* [x] Split out the use of `assertEqualSets` in the tests above to separate uses of `assertEquals` and `assertEqualsWithDelta`.

### Test Coverage

* Ensure tests still cover the original cases and pass.

## QA Brief

* QA:Eng to confirm tests cover existing use cases.

## Changelog entry

* Fix unstable time based PHPUnit tests.

**Comment by benbowler** [comment]
I created a candidate PR as this is such a small change.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
#### QA:eng Verified

* Did not find other occurrence in the code that uses `assertEqualSets` with `time()`
* No tests failed, run it few times
