### ISSUE TITLE
Fix the typo in the "Display visitor groups" Settings switch label.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8496]
## Feature Description

As mentioned on https://github.com/google/site-kit-wp/pull/8424#discussion_r1554154612, there was initially a typo in the copy for the "Display visitor groups" Settings switch label (it read "Display visitors groups").

The copy should be updated, in line with the updated [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1512-32992&mode=design&t=eUF56r1jUKFEas9y-0), to read "Display visitor groups in dashboard".

While updating this copy we should also address a minor code organisation issue introduced by the same issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy for the "Display visitor groups" Settings switch label should read: _Display visitor groups in dashboard_
* Non-functional, but the `SettingsCardVisitorGroups` component should be moved to either `assets/js/modules/analytics-4/components/settings/AudienceSegmentation/`, in line with the initial [code organization](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.mlj74m7pz9gr) section in the design doc, or, to `assets/js/modules/analytics-4/components/audience-segmentation/settings/` if [8495](https://github.com/google/site-kit-wp/issues/8495) has been implemented before this issue.

## Implementation Brief

* [x] In `assets/js/components/settings/SettingsCardVisitorGroups.js`:  
    * [x] Update the `label` of the only `Switch` element to a translatable `Display visitor groups in dashboard` string. 
    * [x] Also update the string in the test file `SettingsCardVisitorGroups.test.js`. 
* [x] Move the ``SettingsCardVisitorGroups.js`` and its associated story and test files to `assets/js/modules/analytics-4/components/settings/AudienceSegmentation` or `assets/js/modules/analytics-4/components/audience-segmentation/settings/` if 8495 has been already merged. 

### Test Coverage

* Tests should be updated as described above. 

## QA Brief

* Go to `Site Kit > Settings > Admin Settings`. There should be `Visitor groups` panel with a toggle setting.
* Label for toggle should read `Display visitor groups in dashboard`
* Open the browser console and in network tab, notice that when we change the state of the toggle, it should send a request to `google-site-kit/v1/modules/analytics-4/data/audience-settings`. Request should be successful with 200 status code.

## Changelog entry

* Fix typo in the "Visitor groups" admin setting.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this on develop on WP 6.5.2  PHP 8.0 and it's looking good:

- Copy has been updated: There is no plural for the word 'visitor'
  <Details>
  <img width="528" alt="Screenshot 2024-05-06 at 14 18 32" src="https://github.com/google/site-kit-wp/assets/125576926/83d66da7-46f5-429c-ad91-e4ef085b31a9">
  </Details>
- Toggling the setting on and off will trigger the required request with 200 status to:
   `google-site-kit/v1/modules/analytics-4/data/audience-settings. `
   <Details>
   <img width="1312" alt="Screenshot 2024-05-06 at 14 20 33" src="https://github.com/google/site-kit-wp/assets/125576926/d099498f-8acf-43ad-a79b-82647bd4a1fb">
   </Details>


Moving ticket to Approved.
