### ISSUE TITLE
site verification step failing on retry after granting user with permissions

### ISSUE THREAD

**Issue by lucymtc** [google/site-kit-wp#85]
## Bug Description

When going through the setup flow and authenticate with account that hasn't been added to the Users & Permissions settings in Search Console user will see a Continue button. After granting the user permissions in Search Console, clicking on the Continue button will throw error "The necessary verification token could not be found on your site." and it will only re-verify successfully when refreshing the page.

## Steps to reproduce

1. Start Site Kit setup flow, enter credentials.
2. Authenticate with account that has no access to search console.
3. Input with Website Address is displayed with button "Continue".
4. In other tab go to search console, under Settings > Users and permissions add the user used to authenticate.
5. Go back to Site Kit URL verification step and click "Continue".
6. Error message shows "The necessary verification token could not be found on your site."
7. Refresh the page, re-verifies the site URL successfully.

## Expected behavior

Once the user has been granted with permissions in search console clicking on Continue button should verify url and continue to next step.

## Screenshots

<img width="802" alt="Screen Shot 2019-06-29 at 16 43 42" src="https://user-images.githubusercontent.com/1204359/60386091-34e6ff00-9a91-11e9-973b-c6758287ae38.png">

## Additional Context

 - PHP Version: 7.1
 - OS: mac
 - Browser: chrome (all)
 - Plugin Version: Developer Beta
 - Device: macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by adamsilverstein** [comment]
@lucymtc  Closing this as resolved, please feel free to re-open if this is still an issue.
