### ISSUE TITLE
Fix typo on Ads module setup screen

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8501]
## Bug Description

Per @bethanylang in Bug Bash ([Asana task](https://app.asana.com/0/1206715995671666/1207009966970180/f)):

On the initial Ads setup screen, there is a typo. Change "Ad your conversion ID below." to "Add your conversion ID below."

![image](https://github.com/google/site-kit-wp/assets/12189958/a0a5c67d-ec31-45db-ab27-823e3dfbacbb)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The content above the setup form on the `Ads` module setup screen should have the following label: 
  * "Add your conversion ID below. Site Kit will place it on your site so you can track the performance of your Google Ads campaigns."

## Implementation Brief

* [ ] Update `assets/js/modules/ads/components/setup/SetupMain.js`
  * Edit the content in `div.googlesitekit-setup-module__description` to match the one in AC

### Test Coverage

* Update any failing VRT reference images

## QA Brief

* Setup Site Kit with `adsModule` feature flag enabled
* Go to `Connect more services` and trigger `Ads` module setup
* Verify that typo from screenshot added in the issue description is fixed

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs and IB here are good 👍🏻

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that typo is fixed now. 

![image](https://github.com/google/site-kit-wp/assets/94359491/adf0c137-83c4-4fc8-b6dc-abb30f0841ef)
