### ISSUE TITLE
Conditionally Enqueue Admin Scripts and Styles for Enhanced Authorize Application Screen Visibility

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8504]
## Feature Description

Implement custom logic to conditionally load admin scripts and styles to enhance the WordPress Authorize Application screen based on the domain name within the `success_url` parameter, ensuring that enhancements are only applied for users with Site Kit for Google services.

For more information, refer to the [Custom Style Application](https://docs.google.com/document/d/1AXgDbfk8oMINl3fQZV41rp1r4krA1545MFfLAY7Yt1o/edit?resourcekey=0-yBMc-IpM33SZiT1GIMvgTQ#heading=h.urcavrmd3n1i) and [Identification Strategy](https://docs.google.com/document/d/1AXgDbfk8oMINl3fQZV41rp1r4krA1545MFfLAY7Yt1o/edit?resourcekey=0-yBMc-IpM33SZiT1GIMvgTQ#heading=h.ucrit6wl264u) sections in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **Class Implementation**: A new class named `Authorize_Application` must be successfully implemented within the `Google\Site_Kit\Core\Admin` namespace. This class will encapsulate all conditional logic for loading scripts and styles on the Authorize Applications screen.
* **Functionality of Authorize_Application Class**: The `Authorize_Application` class must control the conditional enqueuing of scripts and styles based on two key criteria: the domain name in the `success_url` parameter and confirmation that the current page is the `authorize-application` page.
* **Specific Page Detection**: The `Authorize_Application` class must confirm that the current page is the `authorize-application` page before enqueueing any scripts or styles. This ensures that enhancements are targeted and do not affect other areas of the admin dashboard.
* **Path Detection**: The class should validate that the `success_url` parameter contains the specific path `/settings/authorization/wordpress`, indicating that the user interaction is related to the intended integration.
* **Conditional Script and Style Enqueueing**: Scripts and styles should only be enqueued when both conditions are met: the page is `authorize-application` and the `success_url` domain is correctly identified as a `*.google.com` domain.

## Implementation Brief

In the `includes/Core/Admin` directory:

* [x] Create a new `Authorize_Application` class within the `Google\Site_Kit\Core\Admin` namespace.

#### Constructor Method

* [x] Implement a `__construct` method within the `Authorize_Application` class that receives Context `$context` and Assets `$assets` as parameters.

#### Methods

* [x] `register()`:
    * [x] Register the `enqueue_assets` method to the WordPress `admin_enqueue_scripts` action, ensuring the Authorize Application styles are conditionally loaded.
* [x] `is_authorize_application_screen`: 
    * [x] Checks if the current admin screen is the `authorize-application` page. Utilize `get_current_screen()->id` to determine the screen identity.
    * [x] Return: Boolean. True if on the correct screen, false otherwise.
* [x] `is_google_service`:
    * [x] Validate the path part of the `success_url` parameter to ensure it matches the specified path `/settings/authorization/wordpress`.
    * [x] Extract the domain using `parse_url()` and check it against a regex pattern.
    * [x] Return: Boolean. True if the domain is valid, false otherwise.
* [x] `enqueue_assets()`:
    * [x] Utilize the `Assets::enqueue_asset` method to enqueue the stylesheet.
    * [x] Conditionally enqueue the `googlesitekit-authorize-application` stylesheet if both `is_authorize_application_screen` and `is_google_service` return true.

#### Add the Stylesheet to the Assets Class

In `includes/Core/Assets/Assets.php`:

* [x] Modify the `Assets::get_assets` method to include the `googlesitekit-authorize-application` stylesheet using the `Stylesheet` constructor.

#### Register the Authorize_Application Class

In `includes/Plugin.php`:

* [x] Register the `Authorize_Application` class within the `Plugin::register` method.
* [x] Ensure it is registered after the `Assets` class.

### Test Coverage

* [x] Add basic test coverage for the `Authorize_Application` class.

## QA Brief

* Ensure that Site Kit is installed and activated on your WordPress installation.
#### Testing with Site Kit Activated and Google Domain:
* Navigate to the following URL on your WordPress site, replacing `example.com` with your actual site domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Confirm that the `Yes, I approve of this connection` button displays with the color `#0B57D0`.

#### Testing with Non-Google Domain:
* Modify the `success_url` Domain: Change the `success_url` to a non-Google domain and access the same URL:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Ensure that the `Yes, I approve of this connection` button reverts to the default WordPress button color.
* Confirm that no custom styles are applied.

#### Testing with Site Kit Deactivated:
* Deactivate Site Kit.
* Access the URL again with the original `success_url` pointing to a Google domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the `Yes, I approve of this connection` button displays the default WordPress styles, showing that Site Kit enhancements are not applied without the plugin activated.

## Changelog entry

* Enqueue stylesheet specific to the Authorize Application screen.

**Comment by hussain-t** [comment]
I've added the AC and IB and have moved directly to IBR.

**Comment by techanvil** [comment]
Hi @hussain-t, please can you take a look at this https://github.com/google/site-kit-wp/issues/8503#issuecomment-2052075187, and make appropriate changes to this issue too?

**Comment by hussain-t** [comment]
Thanks for bringing this up, @techanvil. "Authorize Application" sounds good to me. I've updated the AC and IB accordingly.

**Comment by techanvil** [comment]
IB LGTM, nice one @hussain-t! :white_check_mark:

**Comment by hussain-t** [comment]
@techanvil, I have updated the AC and IB to align with the latest confirmation regarding the `success_url`. As Gilad mentioned:

>so you should expect the domain to be different, but the path to be the same: /settings/authorization/wordpress.

Based on this, our checks are now focused on the specific static path rather than the domain.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested on develop branch on WP 6.5.2 and PHP 8.0 and results are as expected:

- **Testing with Site Kit Activated and Google Domain:**
Reviewed this[ link ](https://8524test.s2-tastewp.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2F8524test.s2-tastewp.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true)and I can confirm the button colour is  #0B57D0.
   <Details>
   <img width="806" alt="SK active + Google dom" src="https://github.com/google/site-kit-wp/assets/125576926/bb18162b-5fe5-4541-b61b-2c14a6dc2e3c">
</Details>


- **Testing with Non-Google Domain:**
Reviewed this [link](https://8524test.s2-tastewp.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2F8524test.s2-tastewp.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true) and I can confirm the button 'Yes, I approve of this connection button' is following the default WordPress button colour: #3858E9
This is the same as what is used on the Prod version.
      <Details>
   <img width="857" alt="Screenshot 2024-04-23 at 15 33 26" src="https://github.com/google/site-kit-wp/assets/125576926/06367608-f7db-4bd9-bb98-05645e7979f8">
</Details>

- **Testing with Site Kit Deactivated:**
Reviewed [this link](https://8524test.s2-tastewp.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2F8524test.s2-tastewp.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true) and  I can confirm the button 'Yes, I approve of this connection button' is following the default WordPress button colour: #3858E9   
      <Details>
      <img width="871" alt="Screenshot 2024-04-23 at 15 37 10" src="https://github.com/google/site-kit-wp/assets/125576926/2ef03733-6bae-4d10-9b4b-ced86891e8ae">

</Details>

This is working well @hussain-t . I am moving this ticket to Approval column.
