### ISSUE TITLE
Enhance the Authorize Application Screen for Site Kit Users

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8505]
## Feature Description

Enhance the Authorize Application screen based on the provided design specs for Site Kit users to improve the user interface and experience. Focus on UI components such as form fields, buttons, and the background color.

[Figma Design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3304&mode=design&t=D8of1w8H4pmBsdvC-4)

For more information, refer to the [Enhanced Elements](https://docs.google.com/document/d/1AXgDbfk8oMINl3fQZV41rp1r4krA1545MFfLAY7Yt1o/edit?resourcekey=0-yBMc-IpM33SZiT1GIMvgTQ#heading=h.nf2fne4tgkgy) section in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **Background Color Adjustment**:
    * The background color of the Authorize Application screen must match the color specified in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3305&mode=design&t=fcQQGveqGj9WwSji-4).
* **Application Title Field Styling**:
    * The text field for the application title should reflect the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3418&mode=design&t=fcQQGveqGj9WwSji-4), including border-radius, padding, and font styling.
    * **Note:** Confirmation of the focus color specification is pending from the design team. It will be implemented in #8584.
* **Primary Approval Button**:
    * The primary approval button should be styled to match the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3419&mode=design&t=fcQQGveqGj9WwSji-4).
    * **Note:** The hover and focus effects for this button is pending confirmation from the design team. It will be implemented in #8584.
* **Secondary Reject Button**:
    * The secondary reject button should be styled to match the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3408&mode=design&t=fcQQGveqGj9WwSji-4).
    * **Note:** The hover and focus effects for this button is pending confirmation from the design team. It will be implemented in #8584.
* **Improved Spacing for Form Elements**:
    * Spacing around labels and their corresponding input fields should be enhanced to improve readability and visual appeal.
    * The spacing adjustments should match the specifications outlined in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3402&mode=design&t=fcQQGveqGj9WwSji-4).
* **Responsiveness**:
    * The enhancements must maintain responsiveness, adhering to the core WordPress Authorize Application screen's behavior on mobile, tablet, and desktop views.
* **Stylesheet Implementation**:
    * All the above styling enhancements should be implemented within the newly created  `_googlesitekit-authorize-application.scss` stylesheet as part of #8503.
    * The enhancements should be applied only when the user is on the Authorize Application screen, and the `success_url` query parameter includes the `.google.com` domain.

## Implementation Brief

In `assets/sass/authorize-application/_googlesitekit-authorize-application.scss`:

* **Background Color Adjustment**:
    * Target the `authorize-application-php` class and set the background color to `#FFFFFF`.
* **Font Styling**:
    * Target the `#wpbody` and `#wpfooter` classes and set the `font-family` to `Google Sans Text` (`$f-primary`).
* **Application Title Field Styling**:
    * Style the application title field to reflect the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3418&mode=design&t=fcQQGveqGj9WwSji-4), including specific border-radius, padding, and font styling.
* **Primary Approval Button**:
    * Background color: `#0B57D0`
    * Text color: `#FFFFFF`
    * Border color: `#0B57D0`
* **Secondary Reject Button**:
    * Background color: `#FFFFFF`
    * Text color: `#0B57D0`
    * Border color: `#747775`
* Note: The hover effect for the action buttons is pending confirmation from the design team, which will be implemented in #8584.
* **Spacing for Form Elements**:
    * Adjust the spacing around labels and their corresponding input fields according to the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3402&mode=design&t=fcQQGveqGj9WwSji-4).
* **Responsiveness**:
    * The enhancements must maintain responsiveness, adhering to the core WordPress Authorize Application screen's behavior on mobile, tablet, and desktop views.
* Ensure the design enhancements should match the specifications outlined in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3402&mode=design&t=fcQQGveqGj9WwSji-4).
* Ensure SCSS variables are used for colors and font sizes where applicable.

### Test Coverage

* No new tests are required for this change.

## QA Brief

- To view the Authorize Application screen with the customized styling applied, use the following URL, replacing `example.com` with the hostname of your WP site.
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fpublishers.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
- Ensure the screen is styled correctly as per the AC.
- Verify that the Authorize Application screen displays using the stock styling when the `success_url` query parameter is a URL which doesn't include a `google.com` domain.

## Changelog entry

* Update WordPress Authorize Application Screen with enhanced design for Site Kit users.

**Comment by techanvil** [comment]
Hi @hussain-t, thanks for drafting this IB.

I'd note that by targeting `.authorize-application-php` to set the font family, the font will be changed for essentially the entire page including the WP menu and admin bar. This would be quite inconsistent with the experience on the rest of the site, and corresponding quite jarring; I wouldn't have thought this is the intention here. I'd imagine we want to avoid updating the menu and admin bar, and should instead consider targeting say `#wpbody` and `#wpfooter` for the font changes. WDYT?

**Comment by hussain-t** [comment]
That's a good catch; thanks, @techanvil. Only the background should target `.authorize-application-php`, not the font. I've updated the IB.

**Comment by hussain-t** [comment]
@kelvinballoo, I've assigned it to @techanvil as he worked on the execution.

**Comment by hussain-t** [comment]
@kelvinballoo, regarding your observations:

>ITEM 1:
The copy is not accurate.
It should be 'News Publishing Tool' instead of 'GoogleServiceIntegration'. Both for the label and placeholder in the text field.

This is from the string provided to the `app_name` param in the URL.

**Comment by techanvil** [comment]
@hussain-t, thanks for clarifying those points!

@kelvinballoo, to your remaining points:

> **ITEM 2:**
> Placeholder colour not accurate.
> On Figma it's #1F1F1F.
> Implemented is : #2c3338

This is a good spot, I will create a followup PR to fix it.

> **ITEM 4:**
> For mobile, I feel the text are too close to the edge.
> We don't have mobile design for that screen but if we counter check with the stock styling, the margin is 26px around

Hmm, I wonder if this is theme related. When I create a fresh WP 6.5.2 site on InstaWP, I'm seeing a stock margin (well, padding) of 10px:

![image](https://github.com/google/site-kit-wp/assets/18395600/9dd20b08-56b8-4bd5-acd1-c6da9bbad702)

This is using the Twenty Twenty Four theme. Can you confirm what theme your test site is using?

I've got a potential fix that does allow the stock padding to be used for my test site, but I'm not sure how to reproduce the layout you are seeing so unsure if the solution works in that scenario too.

Please can you take a look - lmk what theme you're using, and you can also directly test the solution by switching to the SK version for PR https://github.com/google/site-kit-wp/pull/8640.

**Comment by kelvinballoo** [comment]
Hi @techanvil 

Sorry for the confusion.
I don't think it's theme-related. I used the 2023 theme and I also have the 10px padding actually.
But there is also an extra 26px white space before the text starts.

This is subjective but visually, having only 10px padding looks a bit off to me. 

<Details>
10px green padding + 26px white gap
<img width="828" alt="Screenshot 2024-04-30 at 17 24 49" src="https://github.com/google/site-kit-wp/assets/125576926/342b4298-6a0b-48d1-a093-f11a2d5e9ace">

</Details>

**Comment by techanvil** [comment]
Hi @kelvinballoo, thanks for clarifying that - apologies for missing the point the first time around.

As discussed on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1714476965132659?thread_ts=1714441488.143689&cid=CBKKQEBR9), I've applied padding of 26px at mobile viewports. Moving this back to CR for the fix now.

**Comment by kuasha420** [comment]
@kelvinballoo Back to you for another passed. Issue 2 and 4 has been fixed and the others either does not need fixing or will be implemented in separate issue. Cheers.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @kuasha420 , @techanvil . Noted on items 1 and 3.

Tested items 2 and 4 and it's looking good.

**ITEM 2:**
Placeholder text colour is now #1F1F1F
<Details>
<img width="1200" alt="Screenshot 2024-05-01 at 01 39 28" src="https://github.com/google/site-kit-wp/assets/125576926/32aabcea-c9be-42fe-9599-aa48e771cc52">

</Details>
______________________________________________________

**ITEM 4:**
There is a 26px margin on the sides now on mobile breakpoints and looks much better.
Scaled the breakpoints and everything adjusts sensibly.

<Details>
<img width="912" alt="Screenshot 2024-05-01 at 01 44 27" src="https://github.com/google/site-kit-wp/assets/125576926/2d84211d-7c02-432e-93f7-0c5017d04c6e">

</Details>

Moving this ticket to Approval.

**Comment by hussain-t** [comment]
Hi @kelvinballoo, there was an inconsistency padding on the default footer. I've fixed it in this follow-up [PR](https://github.com/google/site-kit-wp/pull/8646). @techanvil will assign it back to you once it's merged. Thanks!

![Screenshot 2024-05-01 at 3 23 28 PM](https://github.com/google/site-kit-wp/assets/24408261/9c7f3d56-f977-4c88-b2c6-830cb98e7609)

**Comment by techanvil** [comment]
Thanks for spotting that @hussain-t!

**Comment by techanvil** [comment]
Back over to you @kelvinballoo to confirm the padding fix as per Hussain's post above.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Reviewed this and I can confirm the regression issue is resolved.
The footer is now aligned with the rest of the content.

<Details>
<img width="836" alt="Screenshot 2024-05-01 at 20 37 24" src="https://github.com/google/site-kit-wp/assets/125576926/9825f018-4637-40ff-9b2b-bc414d23cbd1">

</Details>

Moving ticket to 'Approval'
