### ISSUE TITLE
Update copy on Ads success notification

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8507]
## Bug Description

On the Ads module success notification, the period should be removed from the sentence ending "track conversions for your Ads campaigns."

In addition, the phrase "Ads conversion ID" should be changed to "Conversion tracking ID" to match the field name in settings.

![image](https://github.com/google/site-kit-wp/assets/12189958/2198cc09-38f7-46d6-a4b0-fc68f5353a5e)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* https://github.com/google/site-kit-wp/blob/e8a0ae8c7b7e0827676cf2360cba158bcc9593b6/assets/js/components/notifications/SetupSuccessSubtleNotification.js#L67 should have its period removed.
* https://github.com/google/site-kit-wp/blob/e8a0ae8c7b7e0827676cf2360cba158bcc9593b6/assets/js/components/notifications/SetupSuccessSubtleNotification.js#L61 should be changed from "Ads conversion ID" to "Conversion Tracking ID"

## Implementation Brief

* [ ] Follow the two points in the ACs; change the text as required and any tests/VRTs.

### Test Coverage

* No new tests needed; change VRTs/snapshots as needed.

## QA Brief

* Setup Site Kit with `adsModule` feature flag enabled
* Connect Ads module
* Verify that after redirection to the dashboard the success notification has the changes from AC

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

I noticed while updating my testing plan that the `Conversion tracking ID` copy should  be in title case to ensure it's consistent across the plugin.  `Conversion Tracking ID`
