### ISSUE TITLE
Incorporate Custom Footer Text on the Authorize Application Screen

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8510]
## Feature Description

Custom footer text should be implemented for the enhanced Authorize Application screen. The custom footer should include a "Powered by Site Kit" message and be styled according to the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3406&mode=design&t=fcQQGveqGj9WwSji-4).

Refer to the [Adding Custom Footer Text](https://docs.google.com/document/d/1AXgDbfk8oMINl3fQZV41rp1r4krA1545MFfLAY7Yt1o/edit?resourcekey=0-yBMc-IpM33SZiT1GIMvgTQ#heading=h.5zkx9zahvbjg) section in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **Conditional Display Based on `success_url` Domain:**
    * The custom footer text "Powered by Site Kit" should be implemented only when the user is on the Authorize Application screen, and the `success_url` query parameter includes the `.google.com` domain.
* **Implementation and Styling:**
    * The footer text must be implemented using the `admin_footer` action hook, ensuring it is added just below the default WordPress footer text.
    * The text "Powered by Site Kit" should match the font size, color, and alignment specified in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3406&mode=design&t=fcQQGveqGj9WwSji-4).

## Implementation Brief

In `includes/Core/Admin/Authorize_Application.php`:

* **Create `render_footer_text` Method**:
    * [x] Check that the current screen is the `authorize_application` using the `is_authorize_application_screen` method.
    * [x] Check that the `success_url` query parameter contains a `.google.com` domain using the `is_google_service` method.
    * [x] If both conditions are met, echo the footer text "Powered by Site Kit". Wrap this text in a `<div>` with a `<p>` tag styled via custom selectors.
* **Hook Registration**:
    * [x] Locate the `Authorize_ApplicationTest::register` method.
    * [x] Register the `render_footer_text` method to the `admin_footer` action.

In `assets/sass/authorize-application/_googlesitekit-authorize-application.scss`:

* **Custom Styles Application**:
    * [x] Apply the custom styles for the "Powered by Site Kit" footer text.
    * [x] The footer text should match the font size, color, and alignment specified in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3406&mode=design&t=fcQQGveqGj9WwSji-4).

### Test Coverage

In `tests/phpunit/integration/Core/Admin/Authorize_ApplicationTest.php`:

* [x] Add a test case to verify the custom footer text is rendered on the Authorize Application screen when the `success_url` query parameter includes the `.google.com` domain.
* [x] Add a test case to verify the custom footer text is not rendered on the Authorize Application screen when the `success_url` query parameter does not include the `.google.com` domain.
* [x] Add a test case to verify that the custom footer text is not rendered on screens other than the Authorize Application screen.

## QA Brief

* Ensure that Site Kit is installed and activated on your WordPress installation.
* Navigate to the following URL on your WordPress site, replacing `example.com` with your actual site domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the custom footer text "Powered by Site Kit" is displayed below the default footer text on the Authorize Application screen.
* Modify the `success_url` Domain: Change the `success_url` to a non-Google domain and access the same URL:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the custom footer text is not displayed on the Authorize Application screen.
* Deactivate Site Kit.
* Access the URL again with the original `success_url` pointing to a Google domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the custom footer text is not displayed on the Authorize Application screen.
* Note: The footer content was placed just below the form content in the Figma design. However, the current implementation places it at the bottom of the page to maintain the existing footer structure.

## Changelog entry

* Add "Powered by Site Kit" to the Authorize Application screen footer when authorizing a Google application.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ❌  

This is tested good overall.
- The text 'Powered by Site Kit' appears accordingly when the Site Kit plugin is active and there is a google domain ✅
   The text also follows figma accordingly. 
   <Details>
   <img width="1133" alt="Screenshot 2024-04-30 at 16 13 37" src="https://github.com/google/site-kit-wp/assets/125576926/e78e6562-3497-4a57-b479-ca9539b6b60e">

   </Details>
- When plugin is deactivated or it's active and using a non-google domain, the text doesn't appear. ✅ 
   <Details>
   <img width="1144" alt="Screenshot 2024-04-30 at 16 13 24" src="https://github.com/google/site-kit-wp/assets/125576926/570b650f-1e7c-42ac-91f1-762be801d62d">
   </Details>

- One minor point of clarification:  ⚠️ 
   I understand that we are preserving the footer structure as much as possible.
   I only noticed the gap from the bottom to the text on figma as 60px.
   I am thinking if we kept it at 20px also to preserve the footer structure?
   <Details>
   Figma:
   <img width="768" alt="Screenshot 2024-04-30 at 16 17 31" src="https://github.com/google/site-kit-wp/assets/125576926/f4775f09-343d-43fe-b058-d7eb83443049">

   Implementation: 20px
   <img width="1121" alt="Screenshot 2024-04-30 at 16 17 46" src="https://github.com/google/site-kit-wp/assets/125576926/e916f71b-05c4-4659-be1d-1c3a772c5e6a">

   </Details>

- On breakpoints below 783 px, the text doesn't appear. Neither do the other wordings like the WordPress version and 'Thank you for creating with WordPress' ❌ 

   <Details>
   <img width="940" alt="Screenshot 2024-04-30 at 16 21 16" src="https://github.com/google/site-kit-wp/assets/125576926/33d0958c-f36a-44a1-a6c1-b3a6c4de0a3c">

   </Details>

**Comment by hussain-t** [comment]
Hi @kelvinballoo. Regarding your observations:

>One minor point of clarification: ⚠️
I understand that we are preserving the footer structure as much as possible.
I only noticed the gap from the bottom to the text on figma as 60px.
I am thinking if we kept it at 20px also to preserve the footer structure?

Yes, that's to maintain the default footer structure. If you see the default one, it has only 10px padding. However, with the slightly larger custom footer, it is better to increase it slightly. Hence, I set it to 20px, which is fine.

>On breakpoints below 783 px, the text doesn't appear. Neither do the other wordings like the WordPress version and 'Thank you for creating with WordPress' ❌
Is there any special requirements for those breakpoints?

That's the default functionality. We only display the custom footer only when the default one is shown. Please check the default one for clarity.

**Comment by kelvinballoo** [comment]
Noted on that @hussain-t .

All good.
Moving this ticket to Approval.
