### ISSUE TITLE
Improve the TextField component for prefixed use

### ISSUE THREAD

**Issue by benbowler** [google/site-kit-wp#8512]
## Feature Description

As part of the Ads Module epic, we came across some limitations in the `TextField` component which didn't allow us to use it in the way we wanted, specifically for fields that have a prefix such as the Ads Conversion Tracking ID:

<img width="393" alt="Screenshot 2024-03-06 at 14 25 36" src="https://github.com/google/site-kit-wp/assets/119352/fb43bd3a-d1f7-4d72-8d1a-98efc07ca7fc">

The following limitations prevent the best UX for prefixed fields:

1. Currently the label has to be the same as the placeholder.
2. You cannot set the true placeholder prop on the input inside the Material TextArea component.
3. You cannot "fix" the label so that it always shows as a label, in the outlined view.

Once these changes have been implemented we can revisit the Ads Module, updating the input to the original designs @sigal-teller created with the fixed label and different placeholder and label.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For the outlined variant, allow the label to be fixed to the top border of the component (Prevent the label from animating to the placeholder position when the field is empty).
* Allow a placeholder prop to be passed to the underlaying `input` within the `TextArea` component.

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by benbowler** [comment]
This ticket can be closed as I created this ticket outside of the correct procedure + the prefixed field in the Ads module has been updated in the designs to respect the limitations of the TextField component that we have.

**Comment by eugene-manuilov** [comment]
Yes, let's close this as the one that we are not going to work on.
