### ISSUE TITLE
Post Ads module setup success banner notification has incorrect "Got it" CTA link color

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8514]
## Bug Description

As reported by @10upsimon in [Ads Module Bug Bash](https://app.asana.com/0/1206715995671666/1207022520302395/f):

The link color in the product is gray vs. green in the Figma designs:

![image](https://github.com/google/site-kit-wp/assets/12189958/824b02d5-005f-4250-bc55-f47873d33724)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Link/Button colour for "Subtle Notifications" CTA button should match the one in [figma design](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=653-3264&mode=design&t=j76iYrvSZuPLrJ8q-0)

## Implementation Brief

* [x] Update `assets/sass/components/dashboard/_googlesitekit-subtle-notification.scss`
  * For `.mdc-button` selector, apply the color of `$c-site-kit-sk-600` 

### Test Coverage

* Update any failing VRT

## QA Brief

* Reset and set up the Ads module from scratch.
* When the setup is complete you will see the subtle notification on the dashboard, confirm the Got It CTA text is green not grey.

## Changelog entry

* Update the CTA link color in the post Ads module setup success banner.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that Link/Button colour for "Subtle Notifications" CTA button matches the one in [figma design](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=653-3264&mode=design&t=j76iYrvSZuPLrJ8q-0)


<details>

_Latest:_

![image](https://github.com/google/site-kit-wp/assets/94359491/0dcb27cf-06bb-4e5f-98dc-0648aac214d8)

![image](https://github.com/google/site-kit-wp/assets/94359491/7396b871-83ab-4a17-a1ff-33965fbb6067)

_develop:_

![image](https://github.com/google/site-kit-wp/assets/94359491/60c2853d-433a-4548-8ce9-82e92a0b2e6a)

![image](https://github.com/google/site-kit-wp/assets/94359491/539c6799-80c1-4f4f-9258-f60089e34509)

</details>

**Comment by aaemnnosttv** [comment]
@zutigrm @tofumatt @benbowler 

> * For `.mdc-button` selector, apply the color of `$c-site-kit-sk-600`

While this technically the correct concrete value, we should reference the correct _token_ that is used in the design rather than its underlying value. The design calls for `content/on-primary-container` which maps to the same color, but we should always reference tokens wherever possible rather than color values.
https://github.com/google/site-kit-wp/blob/5d1b1b7de7c52b230b8d3746ac81848f615ca140/assets/sass/config/_variables-mui3.scss#L152

We can address this in a follow up, as there is another such instance to correct as well.

**Comment by aaemnnosttv** [comment]
- Opened https://github.com/google/site-kit-wp/issues/8728
