### ISSUE TITLE
Block module setup on Connect More Services screen if ad blocker is detected

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8515]
## Feature Description

As reported by @bethanylang in [Ads Module Bug Bash](https://app.asana.com/0/1206715995671666/1207038070388367/f):

As noted in [Unable to setup Ads Module with AdBlocker enabled](https://app.asana.com/0/0/1206980400473730), users who attempt to set up the Ads module from the Settings > Connect More Services screen while an ad blocker is turned on will receive an Error: You are probably offline error, because the ad blocker is blocking the connection to the ads endpoint.

![image](https://github.com/google/site-kit-wp/assets/12189958/a8665016-98a6-4a39-b9eb-285e81e8a738)

To address this, we should check for an ad blocker first and not allow users to complete setup when one is detected, similar to the functionality for the AdSense module:

![image](https://github.com/google/site-kit-wp/assets/12189958/b297ea62-30d3-4bea-b9fe-29665eb06d98)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When `Ad blocker` is detected `Ads` module should behave like `AdSense` module is currently:
  * in connect more services tab - the module box should be greyed out and notice about `Ad blocker` detection should be shown
  * In setup module screen - if `Ad blocker` is detected a warning should be shown instead of the setup form

## Implementation Brief

* [x] Move `assets/js/modules/ads/components/common/AdBlockerWarning.js` to the `assets/js/components/AdBlockerWarning.js`
  * Introduce new props: `helpURL` to be used instead `getDocumentationLinkURL` selector, so link will be passed directly and conditionally included if present. And `warningMessage` prop which will replace the current implementation of sourcing it from module using `getAdBlockerWarningMessage`. So message can be passed directly
  * Update `AdBlockerWarning` usage in AdSense module to implement the new import path and props.
* [x] Add `assets/js/googlesitekit/datastore/user/adblocker.js`
  * Move the common actions/selectors from `assets/js/modules/adsense/datastore/adblocker.js` here. Keep only `getAdBlockerWarningMessage` in the AdSense datastore.
  * Update the references to implement actions/selectors from user datastore. Except for usage of `getAdBlockerWarningMessage`
* [x] Add `assets/js/modules/ads/datastore/adblocker.js`  
  * Implement the `getAdBlockerWarningMessage` from `assets/js/modules/adsense/datastore/adblocker.js` modifying the copy to mention `Ads` module  and check for it in `isModuleConnected`
* [x] In `assets/js/modules/ads/index.js`
  * Update the setup to include `checkRequirements` property, you can copy it over from `AdSense` module https://github.com/google/site-kit-wp/blob/7170f8ec269b26e48db909c0100f1d1ceab7b2b1/assets/js/modules/adsense/index.js#L71-L89  just adapt the  `getAdBlockerWarningMessage` to be sourced from the `Ads` datastore
* [x] Update `assets/js/modules/ads/components/setup/SetupMain.js`
  *  Conditionally render the `SetupForm` based on `isAdBlockerActive` and render the `AdBlockerWarning` component (added earlier in the Ads folder structure) above the setup form. You can replicate how it is done in `assets/js/modules/adsense/components/setup/SetupMain.js`
* Slug for Ads module documentation url should be `ads-ad-blocker-detected` and for the AdSense `adsense-ad-blocker-detected` 

### Test Coverage

* Add tests and stories for new components. You can adapt them from Adsense counterparts

## QA Brief

* This PR touches and refactors both, AdSense and Ads module components. Thus, ensure to test the following scenarios for regressions in addition to verifying the ACs:
  * Setup flow for AdSense with and without an AdBlocker.
  * Setup flow for Ads with and and without an AdBlocker.
  * Editing AdSense settings with and without an AdBlocker.
  * Editing Ads settings with and without and AdBlocker.
  * Monetisation / AdSense widgets on the main dashboard with and without an AdBlocker.

## Changelog entry

* Block Ads module setup when ad blocker is detected.

**Comment by zutigrm** [comment]
@jamesozzie @adamdunnage  Tagging you here so you can include the support link once it is online.Here is the [slack chat](https://10up.slack.com/archives/CBKKQEBR9/p1712842176514179) for reference. Thanks

cc: @bethanylang

**Comment by eugene-manuilov** [comment]
@zutigrm 

> * Add `assets/js/modules/ads/components/common/AdBlockerWarning.js`
>   * You can reuse the `assets/js/modules/adsense/components/common/AdBlockerWarning.js` and adapt the module store and `getHelpLink` to work for Ads module. Slug for get help link will be provided by the support once it is online.

Instead of creating a new duplicate, we need to move the existing component to the `components` folder and make it module agnostic to be able to use it in both Ads and Adsense modules.

> * Add `assets/js/modules/ads/datastore/adblocker.js`
>   * Implement the `getAdBlockerWarningMessage` from `assets/js/modules/adsense/datastore/adblocker.js` modifying the copy to mention `Ads` module  and check for it in `isModuleConnected`

The same here. We need to extract the common logic and move it to the `code/user` datastore. In modules we need to leave only `getAdBlockerWarningMessage` selectors.

**Comment by zutigrm** [comment]
@eugene-manuilov THanks for the feedback. Updated

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. A few more comments:

> * Introduce new props: `documentationUrlSlug` to be used with `getDocumentationLinkURL` selector, ...

This is not needed because the documentation URL will be always the same for all modules.

> ... and `moduleStore` which will replace the current `MODULES_ADSENSE`.

Instead of passing module slug, we should pass a message itself that should be used in the component.

**Comment by zutigrm** [comment]
Thanks @eugene-manuilov 

> Introduce new props: documentationUrlSlug to be used with getDocumentationLinkURL selector, ...
> This is not needed because the documentation URL will be always the same for all modules

The current documentation slug is for AdSense, we will have a new one for Ads module which is being prepared by the support team. We need to pass the slug for that reason, as it will differ per module

> ... and moduleStore which will replace the current MODULES_ADSENSE.
> Instead of passing module slug, we should pass a message itself that should be used in the component.
Makes sense, updated

**Comment by eugene-manuilov** [comment]
> > Introduce new props: documentationUrlSlug to be used with getDocumentationLinkURL selector, ...
> > This is not needed because the documentation URL will be always the same for all modules
> 
> The current documentation slug is for AdSense, we will have a new one for Ads module which is being prepared by the support team. We need to pass the slug for that reason, as it will differ per module

@zutigrm, the current help link URL is completely module agnostic, it leads to the ad blocker detected article on the documentation site and doesn't belong to the AdSense module. It will be the same for the Ads module as well. https://github.com/google/site-kit-wp/blob/ae463cb0af9efd8afeab5b615139f3af06e8ea59/assets/js/modules/adsense/components/common/AdBlockerWarning.js#L47

**Comment by zutigrm** [comment]
@eugene-manuilov The slug is named module agnostic, true, but the link it leads to https://sitekit.withgoogle.com/documentation/troubleshooting/adsense/#ad-blocker-detected is all about AdSense. This is the tread about new article for [Ads module](https://10up.slack.com/archives/CBKKQEBR9/p1712842176514179), that support is working on

**Comment by adamdunnage** [comment]
@zutigrm The URL for this will be: https://sitekit.withgoogle.com/documentation/troubleshooting/ads/#ad-blocker-detected

**Comment by eugene-manuilov** [comment]
> @zutigrm The URL for this will be: https://sitekit.withgoogle.com/documentation/troubleshooting/ads/#ad-blocker-detected

@adamdunnage can you provide a slug for the redirect rule that we will need to use to get to that page?

**Comment by adamdunnage** [comment]
@eugene-manuilov  As we already have 'ad-blocker-detected' for the AdSense version of this should we therefor use the slug 'ad-blocker-detected-ads-module'?

CC  @jamesozzie @bethanylang

**Comment by eugene-manuilov** [comment]
> ... should we therefor use the slug 'ad-blocker-detected-ads-module'?

@adamdunnage it looks a bit cumbersome in my opinion, but that is probably fine. Do you want to leave the original slug as is or change it to `ad-blocker-detected-adsense-module`? If so, let's probably add a new record with the new slug for the adsense module to the documentation redirects to make sure that redirects get updated on prod.

PS: maybe we should something like `ads-ad-blocker-detected` and `adsense-ad-blocker-detected`? 🤔

**Comment by bethanylang** [comment]
Yeah, @eugene-manuilov 's suggestion makes sense to me: `ads-ad-blocker-detected` and `adsense-ad-blocker-detected`.

**Comment by adamdunnage** [comment]
@eugene-manuilov Actually yes I like your idea more. Let's go with `ads-ad-blocker-detected` and `adsense-ad-blocker-detected`. That makes more sense. In which case as you say we will need to update the current entry for AdSense and create a new entry for the Ads module entry.

Would you like me to make these updates in the sheet?

**Comment by eugene-manuilov** [comment]
> Would you like me to make these updates in the sheet?

@adamdunnage, yes, please, but don't delete the existing one, just add new redirects with new slugs. We actually shouldn't delete any redirects from the sheet that have been added and used in the plugin because if we do so, it will stop working in older versions of the plugin. cc @jamesozzie

**Comment by eugene-manuilov** [comment]
> The slug is named module agnostic, true, but the link it leads to https://sitekit.withgoogle.com/documentation/troubleshooting/adsense/#ad-blocker-detected is all about AdSense. This is the tread about new article for [Ads module](https://10up.slack.com/archives/CBKKQEBR9/p1712842176514179), that support is working on

Thanks, @zutigrm. I didn't notice it from the beginning. Now since we have figured out that we will need to different slugs, let's update IB to reflect these changes.

One more suggestion, maybe let's have the new property `helpURL` instead of `documentationSlugURL` and pass actual URL to that property? In this case, if a module needs a help link, we will pass the URL to the documentation page, otherwise the new component won't render the help link if the helpURL value is empty. WDYT? If you still think we should use the slug property, that's fine too and i'll approve it.

**Comment by adamdunnage** [comment]
The new entries have been added to the support redirects sheet.

**Comment by zutigrm** [comment]
@eugene-manuilov thanks, added new slug in the IB

> One more suggestion, maybe let's have the new property helpURL instead of documentationSlugURL and pass actual URL to that property? In this case, if a module needs a help link, we will pass the URL to the documentation page, otherwise the new component won't render the help link if the helpURL value is empty. WDYT?

Yes that's a good pint, it will make componnet more flexible. Updated IB to include that suggestion

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. Almost looks good. The final piece is to mention that we need to use the new slug for the Adsense module: `adsense-ad-blocker-detected`. Everything else is great.

**Comment by zutigrm** [comment]
@eugene-manuilov Ah yes forgot to include it. Last point updated to provide slugs for both modules

**Comment by eugene-manuilov** [comment]
Thanks. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@tofumatt, this change doesn’t seem to be in the main branch. I can see the change in develop branch, though.  These are new sites I have tested on. Looking at the actions for the PR, I do not see any issues.  Please could you take a look at this for me?

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@jimmymadon I have three observations to share with you:

1. I set up the Ads module and then enabled my AdBlocker. The message appears as expected on the setup screen; when I click on the learn more link, I am redirected to https://sitekit.withgoogle.com/support?doc=ads-ad-blocker-detected, and the page does not exist. This could be because Adam or James haven't published this yet, but I wanted to confirm. 

https://github.com/google/site-kit-wp/assets/73545194/f03f1402-0a53-4eea-8fd2-994df0dce7a2

2. When the Ads module is not connected due to the AdBlocker, and you go to Site Kit settings, there isn't a `Learn more` link. For consistency, we should have one because when you go to the AdSense settings, a link does appear.

Ads module
![image](https://github.com/google/site-kit-wp/assets/73545194/881b563c-aaba-41c9-9471-bd53d2a88d36)

AdSense
![image](https://github.com/google/site-kit-wp/assets/73545194/160f5e35-c383-4c76-b28a-7eec6e59dc7d)

3. When the Ads module is connected, and you go to the Site Kit settings with AdBlocker enabled, the `Conversion Tracking ID` appears as `none.` When you edit the settings, the loading animation appears continuously. The module settings screen does not open. See the screencast below. 

https://github.com/google/site-kit-wp/assets/73545194/3b49877a-d5cb-4962-8881-4d04c7376204

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- There are no regressions in addition to verifying the ACs:
  - Checked setup flow for AdSense with and without an AdBlocker.
  - Checked setup flow for Ads with and and without an AdBlocker.
  - Checked when editing AdSense settings with and without an AdBlocker.
  - Checked when editing Ads settings with and without an AdBlocker.
  - Checked the Monetisation / AdSense widgets on the main dashboard with and without an AdBlocker.

**Note:** The 3 issues [reported above:](https://github.com/google/site-kit-wp/issues/8515#issuecomment-2061489654) Issue 1 is expected.  Issue 2 I will create a ticket for this.  Issue 3, has been fixed and was tested as part of the verification above. The Ads module settings no longer appear on view or edit when AdBlocker is enabled; this was to fix the issue quickly. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/9cf2063b-de39-417b-a574-8d421d46b4e6)
![image](https://github.com/google/site-kit-wp/assets/73545194/99b25a03-a8d5-45e7-93ea-76e8fed026e3)
![image](https://github.com/google/site-kit-wp/assets/73545194/8b894606-9b22-4cec-8d9a-a3c81f6a07e8)
![image](https://github.com/google/site-kit-wp/assets/73545194/a27b3c1e-4440-4ddc-91cb-9dd6d6477451)
![image](https://github.com/google/site-kit-wp/assets/73545194/cf520055-e781-4a83-887d-92938bc7e4f4)
![image](https://github.com/google/site-kit-wp/assets/73545194/c0e2374c-ef2d-4007-b319-afde0407ec39)
![image](https://github.com/google/site-kit-wp/assets/73545194/356637dc-4da6-4d5a-abdf-2b7ae6010fea)
![image](https://github.com/google/site-kit-wp/assets/73545194/e0de207c-bcee-46b4-8bd7-7f63645b318b)
![image](https://github.com/google/site-kit-wp/assets/73545194/c39afffb-5919-4451-b42c-ad1d31a9189c)
![image](https://github.com/google/site-kit-wp/assets/73545194/416b12f1-715c-4110-b63b-937275343e64)
![image](https://github.com/google/site-kit-wp/assets/73545194/861173f5-d712-4e3e-b74d-1fed3027b2a7)
![image](https://github.com/google/site-kit-wp/assets/73545194/4da95c8c-9f77-4c16-be4a-47c2b70a4b27)
![image](https://github.com/google/site-kit-wp/assets/73545194/ffba9e2c-35fc-4781-a9b2-6c86d722c615)

</details>
