### ISSUE TITLE
Update pre-loaded state of Ads settings view for consistency

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8516]
## Feature Description

As reported by @wpdarren and @10upsimon in Ads Module Bug Bash:

This is more noticeable if you view the ads module settings with a slow 3G internet connection.  When the settings load, initially the conversion tracking ID appears as 'None' and then a few seconds later, the correct tracking ID loads.  See Screencast below.  Maybe we could have a loading animation like we have for enhanced measurement until the data loads. 

https://github.com/google/site-kit-wp/assets/12189958/31df5954-860d-4d00-9bb2-2279a976b354

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update the Conversion ID view setting field to be empty (default behaviour for other settings), if the setting has not loaded.
* Show "None" if and only if the setting has loaded and is not set within the plugin.

## Implementation Brief

* [x] Within `assets/js/modules/ads/components/settings/SettingsView.js`
  * [x] Remove the ternary operator being used.
  * [x] If the `conversionIDValue` is equal to an empty string, render a `DisplaySetting` with value as "None".
  * [x] If the `conversionIDValue` is `undefined` or has a value, then render a `DisplaySetting` with value as `conversionIDValue`.
  * [x] Do the same for the `extCustomerID` field as well to maintain consistency.

### Test Coverage

* No new tests required.

## QA Brief

* Setup Site Kit with `adsModule` feature flag
* Setup the Ads module and follow the steps from the video added in description
* Verify that issue is not present 

## Changelog entry

* Update the settings view for Ads to display "None" in conversion tracking and external customer ID only when those settings are actually empty.

**Comment by jimmymadon** [comment]
@aaemnnosttv Thanks for the correction - makes sense! IB updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Verified that the issue reported is now fixed.  The conversion tracking ID appears.

https://github.com/google/site-kit-wp/assets/73545194/01e43f0d-0c7a-4549-826a-0ad4b601ae0c
