### ISSUE TITLE
Ensure that audiences are listed in the correct order.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8519]
## Feature Description

As discussed on [Figma](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH?type=design&node-id=1046-39085&mode=dev#764018255), we should ensure that audiences are displayed in the correct order, both on the Selection Panel and in the list of Audience Tiles.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Within the Selection Panel, audiences should be listed in the following order:
  - Primary order: User defined audiences, Site Kit-created audiences, default audiences.
  - Secondary order: The order the audiences are listed in the Analytics UI/API.
  - Note that this ordering is applicable to the lists of audiences as they sit within the "current selection" and "available groups" groups. In other words this top-level grouping is effectively the true primary order when there is a current selection.
- The list of Audience Tiles should be ordered by the same criteria, i.e. the Audience Tiles order should match that of the "current selection" group in the Selection Panel.

## Implementation Brief

* [x] In `assets/js/modules/analytics-4/constants.js`, add a new constant to define the sort order of each audience type:
  ```
  export const AUDIENCE_TYPE_SORT_ORDER = {
	  USER_AUDIENCE: 0,
	  SITE_KIT_AUDIENCE: 1,
	  DEFAULT_AUDIENCE: 2,
  };
  ```
* [ ] In `assets/js/modules/analytics-4/datastore/audiences.js`:
  * [ ] Sort the audiences in `getAvailableAudiences()` based on the constant defined above (using the `audienceType` already available within the state.
  * [ ] Create a new selector `getAudienceType(audienceResourceName)` which fetches the type of the audience using `getAvailableAudiences()`, similar to the `isUserAudience`/`isSiteKitAudience`/`isDefaultAudience` selectors.

* [ ] In `assets/js/modules/analytics-4/datastore/audience-settings.js`:
  * [ ] Within the `getConfiguredAudiences` selector, sort the `audienceResourceNames` using the `getAudienceType` selector and constant defined above.

### Test Coverage

* Add tests for the new selector as well as the `getAvailableAudiences` and `getConfiguredAudiences` selectors to confirm they return audiences in the expected order.

## QA Brief

* Reset Site Kit or test this on a new site since old data might affect the ordering of audiences. Clear browser storage (session/cache).
* Ensure the audienceSegmentation feature flag is enabled. Set up Site Kit and connect Analytics. 
* Refresh the dashboard once analytics is connected to show the Audience Segmentation setup CTA banner. Click on Enable groups and setup the feature. Verify that the 2 site kit audiences are correctly created. 
* Now, within Analytics Admin -> Property Settings -> Data Display -> Audiences, create 1 or 2 additional audiences.
* Now open the Audiences side panel by clicking on "Change groups" in the Audience Segmentation widget. Verify the ordering is as per the AC.
* Try selecting different audiences from the panel in different orders. Verify that the ordering is as per the AC.
* Now refresh the page or go to another site kit page and come back to the dashboard and perform the above test.

## Changelog entry

* Ensure that Audiences are listed in the correct order, both in the Audience Tiles Widget and the Selection Panel.

**Comment by techanvil** [comment]
Hey @benbowler, thanks for drafting this IB. A few points:

- As per the dependency #8487, `getAudiences()` will be replaced with `getAvailableAudiences()` by the time this issue is implemented, so it should accordingly refer to `getAvailableAudiences()`.
- Even still, I'm not sure the proposed change will cover the sorting in all cases. We need to ensure the selected list of audiences is sorted (both in the Selection Panel and the list in `AudienceTiles`), as well as the remaining available audiences. So it might be the case that we need to apply the sort in `getConfiguredAudiences()` as well. To be honest, though, it's not clear if the Selection Panel will need any additional modification to ensure the audiences are sorted properly considering how the audiences are grouped within the panel. It might actually be worth holding off on drafting this IB until the dependency #8157 is implemented.
- Lastly, it's worth mentioning we do try to avoid explicit code blocks in IBs, I think this one could be written to avoid the code blocks.

**Comment by benbowler** [comment]
As this IB is blocked, and I am away for a couple of weeks, I will un-assign myself but happy to pick it up again if it's not beed addressed when I'm back.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by techanvil** [comment]
Hi @jimmymadon, thanks for drafting the IB here which LGTM.

However, while we do need to allow a good amount of time for testing - the estimate still seems a bit on the high side. Did you mean to increase it from an 11 to a 15?

**Comment by jimmymadon** [comment]
@techanvil Yeah was just worried about some uncertainty in it all "coming together" when we test the order out in the widget area and the side panel. But 11 should be fine.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

- When SK just creates the 'New visitors' and Returning visitors', they are both appearing in the same order as in the Analytics page. ie. New first and then returning. The order matches the tiles and also the selection panel. In the latter, the default 'All visitors' appears at the very bottom.
   <Details>
   <img width="1229" alt="Screenshot 2024-06-25 at 14 51 23" src="https://github.com/google/site-kit-wp/assets/125576926/711dd5ac-bafd-465e-9df5-a29ee2b8469a">

   </Details>

- After creating new audiences in analytics, these won't appear straightaway. After disconnecting and reconnecting the analytics module, the new audiences appeared and they are following the order:
   - User defined audiences
   - Site Kit-created audiences
   - Default audiences
   <Details>
   <img width="1238" alt="Screenshot 2024-06-26 at 15 33 39" src="https://github.com/google/site-kit-wp/assets/125576926/5fa16ef5-d306-4ce4-81ed-f4c71b6fbf71">
   </Details>

- The secondary order is respected as per listed in the Analytics UI/API.
   <Details>
   <img width="894" alt="Screenshot 2024-06-26 at 15 42 26" src="https://github.com/google/site-kit-wp/assets/125576926/58b165a2-12c0-482a-bbd1-aca5abc1a268">
   
   <img width="1234" alt="Screenshot 2024-06-26 at 15 23 14" src="https://github.com/google/site-kit-wp/assets/125576926/c39952d3-445e-401f-9894-13311a6f1162">

   </Details>

- Did different permutations and combinations at the 'Current selection' and at the 'Additional groups' and every time, the primary and secondary order would the one defined in the AC. Also, the tiles would also follow the order as per the current selection.

This is all looking good. Moving this ticket to approval.

**Comment by techanvil** [comment]
Note that I made a small amendment to the AC to reflect the change introduced in https://github.com/google/site-kit-wp/issues/9168 which ensures the Site Kit-created audiences are always listed in the order "new visitors", "returning visitors". This ensures the AC for this issue can be used as a source of truth for the audience ordering.
