### ISSUE TITLE
Update the Link Color in the Default WordPress Footer on the Authorize Application Screen

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8524]
## Feature Description

The color of the "WordPress" link within the footer text "Thank you for creating with WordPress" on the Authorize Application screen needs to be updated to ensure consistency with the Figma design specifications.

Refer to the [Link Color Update in Footer](https://docs.google.com/document/d/1AXgDbfk8oMINl3fQZV41rp1r4krA1545MFfLAY7Yt1o/edit?resourcekey=0-yBMc-IpM33SZiT1GIMvgTQ#heading=h.avpx791nq9wd) section in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The color of the "WordPress" link within the default footer text "Thank you for creating with WordPress." on the Authorize Application screen must be updated to the color `#1A73E8` specified in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3406&mode=design&t=gIG3aDuMKIToCNtb-4).
* It should be implemented within the newly created  `_googlesitekit-authorize-application.scss` stylesheet as part of #8503.
* The enhanced styles should be applied only when the user is on the Authorize Application screen and the `success_url` query parameter includes the `.google.com` domain.

## Implementation Brief

In `assets/sass/authorize-application/_googlesitekit-authorize-application.scss`:

* [x] Target the `#footer-thankyou a` within the `#wpfooter` element to ensure that the color change is applied specifically and only to the "Thank you for creating with WordPress." link on the Authorize Application screen.
* [x] Use the predefined `$c-deep-blue` variable for the color value set to `#1A73E8`.

### Test Coverage

* No new tests are required for this change.

## QA Brief

* Ensure that Site Kit is installed and activated on your WordPress installation.
* Navigate to the following URL on your WordPress site, replacing `example.com` with your actual site domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the color of the "WordPress" link within the default footer text "Thank you for creating with WordPress." on the Authorize Application screen is updated to the color `#1A73E8` specified in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3406&mode=design&t=gIG3aDuMKIToCNtb-4).
* Modify the `success_url` Domain: Change the `success_url` to a non-Google domain and access the same URL:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the color of the "WordPress" link within the default footer text "Thank you for creating with WordPress." remains unchanged.
* Deactivate Site Kit.
* Access the URL again with the original `success_url` pointing to a Google domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the color of the "WordPress" link within the default footer text "Thank you for creating with WordPress." remains unchanged.

## Changelog entry

* Use a Google brand color for the WordPress link in the footer of the Authorize Application screen when authorizing a Google application.

**Comment by techanvil** [comment]
Hey @hussain-t, reviewing this IB and taking a look at the page on my WP install, it occurs to me that there can be additional links in the footer - for example the "Get Version" link here:

![image](https://github.com/google/site-kit-wp/assets/18395600/3532d437-d063-429f-92cf-74fc79aec5f7)

It's possible that other links may exist too via plugins or user customisation.

Has this been taken into consideration? Maybe we should be a bit more targeted in our selectors e.g. we could target `#footer-thankyou a` for this specific link.

Also, thinking about the extra links for updating the WP version - do you think these will look OK with the rest of the page customised or should we consider updating these too? Maybe this could be a post-launch issue to tackle. WDYT?

**Comment by techanvil** [comment]
Thanks @hussain-t! The IB LGTM :white_check_mark:.

Just popping it back your way to get your thoughts on this question. Maybe it's worth adding an issue to Triage to consider this later...

> Also, thinking about the extra links for updating the WP version - do you think these will look OK with the rest of the page customised or should we consider updating these too? Maybe this could be a post-launch issue to tackle. WDYT?

**Comment by hussain-t** [comment]
Thanks, @techanvil.

>Also, thinking about the extra links for updating the WP version - do you think these will look OK with the rest of the page customised or should we consider updating these too? Maybe this could be a post-launch issue to tackle. WDYT?

IMO, it should be updated with the enhanced color for consistency. However, we need to confirm with the Google design team. Let me check with them.

>Maybe this could be a post-launch issue to tackle. WDYT?

The designer is OOO this week. I will check with them and see if we can get a response next week. Otherwise, we can tackle it post-launch. cc: @sigal-teller

**Comment by techanvil** [comment]
Sounds good, thanks @hussain-t! I'll move this over to the EB in the meantime. Cheers!

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

I tested according to the brief and it's looking fine.
That said @hussain-t ,  the only confusing part for me is the colour check.
The brief says:
`Verify that the color of the "WordPress" link within the default footer text "Thank you for creating with WordPress." on the Authorize Application screen is updated to the primary color #0b57d0 specified in the [Figma design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3406&mode=design&t=gIG3aDuMKIToCNtb-4).`

The brief states the colour needs to be #0b57d0 specified in the [Figma design].
However, when I review the Figma, the colour I see is #1A73E8.

Let me know if I missed something.

<Detail>
<img width="914" alt="Screenshot 2024-04-23 at 14 48 35" src="https://github.com/google/site-kit-wp/assets/125576926/9bf4cba1-a161-41c6-ab04-03a09ecb4d9a">

</details>

**Comment by hussain-t** [comment]
Thanks, @kelvinballoo. I'll create a follow-up PR to fix it.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @techanvil , @kuasha420 

Re-tested this and results are looking as expected:

- The scenario for Site kit being active and using a google domain has the colour matched with figma now: #1A73E8.
   <Details>
   <img width="890" alt="Screenshot 2024-04-25 at 16 38 22" src="https://github.com/google/site-kit-wp/assets/125576926/096e790f-d67b-492c-b063-bdc7c9de4437">

</Details>

- For the other scenarios, the colour is #3858E9, which is the default colour as Prod.
   <Details>
   <img width="500" alt="Screenshot 2024-04-25 at 16 45 51" src="https://github.com/google/site-kit-wp/assets/125576926/0ae0da10-1935-48a0-ba64-82742a9f86b9">

</Details>

Moving this ticket to approval.
