### ISSUE TITLE
Track a GA event when enabling Consent Mode on the Settings screen

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8526]
## Feature Description

The `como_enable` GA event should be tracked when enabling Consent Mode on the Settings screen.

See the related [Slack thread](https://10up.slack.com/archives/CFFRMC5DE/p1712760177369269) for additional context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA event should be tracked for the given Consent Mode action. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307&range=347:361).

Event Name | Category | Trigger | Condition
-- | -- | -- | --
como_enable | {viewContext}_CoMo | Click |	User clicks the toggle to enable consent mode

## Implementation Brief

* [ ] Update the onClick function of the `"Enable consent mode"` switch:
https://github.com/google/site-kit-wp/blob/7170f8ec269b26e48db909c0100f1d1ceab7b2b1/assets/js/components/consent-mode/ConsentModeSwitch.js#L103-L119
  Inside of the `else` statement, track the new `como_enable` event:
   ```
   trackEvent(
	`${ viewContext }_CoMo`,
	'como_enable'
   );
   ```

### Test Coverage

* No additional test coverage is required.

## QA Brief

* Ensure you have the Google Analytics Debugger Chrome Extension installed and have Site Kit set up to track Analytics events in "Settings > Tracking".
* If `Enable Consent Mode` switch is already enabled, disable it.
* Enable the consent mode again.
  * You should trigger `'como_enable'` event in GA with event category `'settings_CoMo'`.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
Reduced the estimate to 3 since this is more than enough for this task.

**Comment by wpdarren** [comment]
@kelvinballoo this would be a good ticket to sync on as you've yet to test any GA Events.  I will assign it to you and let me know when you're free to huddle on Slack.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested under 6.5.2 WP and PHP 8.0 on develop branch.
Upon toggling the 'Enable consent mode' to ON, the event 'como_enable' with event category 'settings_CoMo' is successfully triggered.

<Details>
<img width="1285" alt="Screenshot 2024-04-24 at 19 05 43" src="https://github.com/google/site-kit-wp/assets/125576926/30b6654d-2a9a-402b-adc9-dd2908b4da79">

</Details>

Moving this ticket to 'Approval'
