### ISSUE TITLE
Add validation to Conversion Tracking ID field for numbers only

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8527]
## Feature Description

As requested by the Ads team, users should only be able to enter numbers into the Conversion Tracking ID field in the Ads module. Currently, any characters may be entered.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update `Conversion Tracking ID` field in the Ads module settings and setup screens to accept only number input

## Implementation Brief

* [ ] Update `assets/js/modules/ads/components/common/AdsConversionIDTextField.js`
  * In the `onChange` callback, include additional validation/regex that checks if any non number value is added. 

### Test Coverage

* Currently we do not have tests added for this field, perhaps one can be added testing for valid input for now

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by jimmymadon** [comment]
@bethanylang @sigal-teller When testing a rough implementation here, I just realised that it might be a bit annoying to the end user to type something on a keyboard (or paste an invalid ID) and then not get any "feedback" as to why the field is not accepting characters. Currently, when an invalid letter is entered, we do get a styled error message, which, in my opinion, is better UX. 

I can discuss this quickly in today's AC sync.

**Comment by aaemnnosttv** [comment]
After further review of the initial report, this seems to have been raised as a byproduct of #8508 which was the bug where module settings could be saved with invalid settings. The conversion tracking ID field already has validation which is more useful and consistent with the rest of the plugin by providing visual feedback in response to invalid input rather than ignoring it.

**Comment by sigal-teller** [comment]
@jimmymadon Just to clarify, you mean that when the user tries to type any non-numeric character we should show him an error notification in [this format](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=653%3A2850&mode=design&t=hXzO39ssdpDGOVoD-1) with the text explaining that only numbers can be entered? If so then yes, I agree, This is a better UX

**Comment by jimmymadon** [comment]
@sigal-teller Thanks - we discussed the history of this issue as per Evan's [previous comment](https://github.com/google/site-kit-wp/issues/8527#issuecomment-2083185816) and have closed this issue now.
