### ISSUE TITLE
Add `Conversion_Events_Provider` Interface

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8529]
## Feature Description

Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface. See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new interface `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` should be created
* It should define following methods:
  * `is_active`
  * `get_event_names`
  * `register_script`

## Implementation Brief

* [x] Add new file `includes/Core/Conversion_Tracking/Conversion_Events_Provider.php` for the `Conversion_Events_Provider` interface
  * Define the methods listed in AC 

### Test Coverage

* No changes needed

## QA Brief

* QA:Eng to confirm changes have no wider effect on the application.

## Changelog entry

* Add the `Conversion_Events_Provider` Interface.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
### QA:Eng verified

* Interface is correctly added
* Things are working fine
