### ISSUE TITLE
Include Conversion Event Providers And Their Events in Debug Data

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8530]
## Feature Description

Update `Google\Site_Kit\Core\Site_Health\Debug_Data` class to include active conversion event providers and their events that are tracked by Site Kit.
See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Health information displays active conversion event providers and their events that are tracked by Site Kit.

## Implementation Brief

* [x] Update `Google\Site_Kit\Core\Site_Health\Debug_Data` class
  * Include `get_active_conversion_event_provider_fields` method
    * It should retrieve event names from active conversion event providers as a mapped array with their names/slugs as keys and event names as values.
      * Use the `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Tracking::get_active_conversion_event_providers` method, implemented in [#8528](https://github.com/google/site-kit-wp/issues/8528) to retrieve active coversion event providers
      * Then you can iterate through them and source the event names using `get_event_names` method from each individual `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider`.
  * In `get_fields` method
    * Include them with other fields. You can see an example here https://github.com/google/site-kit-wp/blob/8953c3475a1a22c98c9dea9bc4d3a7a115bfd112/includes/Core/Site_Health/Debug_Data.php#L194

### Test Coverage

* Update `tests/phpunit/integration/Core/Site_Health/Debug_DataTest.php` to include new fields in the tests

## QA Brief

* Setup SiteKit normally.
* Go to Site Health and under Google Site Kit, check that a new field is added for "Active conversion event providers". There will be no value for this field (i.e. None).
* Download, install and simply activate the [OptinMonster plugin](https://en-gb.wordpress.org/plugins/optinmonster/).
* Go to Site Health again and check that a value does appear showing the event name for this plugin, i.e. `submit_lead_form`.

## Changelog entry

* Add conversion event providers information to the site debug data.

**Comment by eugene-manuilov** [comment]
@zutigrm, in analogy to what we discussed in another ticket, it would be nice to make AC be implementation agnostic. Basically, when we write AC it should always answer `What we will get?` question, whilst IB will answer for the `How we will do it?` question.

> `Debug_Data` class should be updated to include new `get_active_conversion_event_provider_fields` method which would retrieve

This tells what we need to do to get the final result, which is more IB-ish information and shouldn't be in the AC section. Much better would be if we write AC that has the following:

```
* Site Health information displays active conversion event providers and their events that are tracked by Site Kit.
```

This is the ideal AC for this task and it will be the responsibility of the IB writer to figure out which class to update. In order to help them figure out it, we can add a note in the IB section pointing to the correct section of the design doc, so they can find which class to update and which method name to create.

Could you please adjust your AC? Thanks in advance.

**Comment by zutigrm** [comment]
@eugene-manuilov Thanks, that's pretty helpful. Since it is about infrastructure I though I should still include a minimal description. I will follow the `What will we get?` as a guideline

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. AC ✔️

**Comment by eugene-manuilov** [comment]
@zutigrm 

> * It should retrieve event names from active conversion event providers as a mapped array with their names/slugs as keys and event names as values.

How? What do we need to do to get that information?

**Comment by zutigrm** [comment]
@eugene-manuilov sorry about that. Expanded on the specifics.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified when OptinMonster plugin is active.
- Verified when OptinMonster Plugin is not activate.
- Verified that a value does appear showing the event name for this plugin, i.e. submit_lead_form.
- Verified that when OptinMonster Plugin is not activate new field is added for "Active conversion event providers" appears with no value (i.e. None).

@jimmymadon Just want to confirm currently new added field "Active conversion event providers" also appears when 'conversionInfra:' feature flag is not enabled. No instructions are provided under QAB related to it but just want to reconfirm that changes introuduced under this tickets are not behind feature flag.




![image](https://github.com/google/site-kit-wp/assets/94359491/439129f9-4bde-49f0-819e-3ea04fe7cc8b)



<details>

_Verified that when OptinMonster Plugin is not activate new field is added for "Active conversion event providers" appears with no value (i.e. None)._

![image](https://github.com/google/site-kit-wp/assets/94359491/7b5bd731-3ac7-4fc8-8742-cd8d9b96a5f6)

_Verified that when OptinMonster plugin is active. a value does appear showing the event name for this plugin, i.e. submit_lead_form._

![image](https://github.com/google/site-kit-wp/assets/94359491/c0c20377-ad15-400b-9efb-1117c9aa5eb4)

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Verified when `conversionInfra` feature flag is disabled then new field is added for "Active conversion event providers" do not appear under site heath.
- Verified when `conversionInfra` feature flag is enabled.
- Verified when OptinMonster plugin is active.
- Verified when OptinMonster Plugin is not activate.
- Verified that a value does appear showing the event name for this plugin, i.e. submit_lead_form.
- Verified that when OptinMonster Plugin is not activate new field is added for "Active conversion event providers" appears with no value (i.e. None).


<details>

_Verified that when OptinMonster plugin is active. a value does appear showing the event name for this plugin, i.e. submit_lead_form._

![image](https://github.com/google/site-kit-wp/assets/94359491/5fd8496e-a773-4688-ad22-277fd88d235b)

_Verified that when OptinMonster Plugin is not activate new field is added for "Active conversion event providers" appears with no value (i.e. None)._

![image](https://github.com/google/site-kit-wp/assets/94359491/4bb0a9a4-7a11-4864-818b-266508eaa6f2)


https://github.com/google/site-kit-wp/assets/94359491/3beb0792-e97f-4ddd-8bdf-5e484c1ca883


</details>
