### ISSUE TITLE
Add Webpack Partial That Will Build Conversion Providers Specific JS Files

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8531]
## Feature Description

Add webpack config partial - `conversionEventProviders.config.js` that will build conversion event providers specific JS files. It can include minimal setup, like what we currently have for advanced tracking in `webpack/basicModules.config.js` .

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All scripts of event providers are compiled and minimised into their respective bundles when all our assets are built with webpack.

## Implementation Brief

* Add `./webpack/conversionEventProviders.config.js` partial and include it to the main `webpack.config.js` file
  * It should list all conversion event providers specific JS files from `assets/js/event-providers/{event-provider-name}.js` as entry points. And output them in `dist/assets/js`
    * You can check `basicModules.config.js`  for inspiration
    * For now just the implementation can be done with one test script (to verify that setup is working as intended), and then each plugin integration will add it's script to the entry point during the implementation in separate issues 
  * Scripts should be only compiled and minimised / regular build process. You can also take a look at `basicModules.config.js` as a guide.

### Test Coverage

* No updates needed

#### QA:Eng
* Run `npm run dev` - 
  * Verify that `assets/js/event-providers/test-plugin-integration.js` is built and compiled file is placed in `dist/assets/js/test-plugin-integration.js`
  * Verify it is built with proper preset and compiled code is not containing ECMA6 code
  * You can play around with this file
* Run `npm run build` -
  * Verify that file is correctly minified and has hashtag added in the file name like rest of the files
* Delete `test-plugin-integration.js` file after finishing with testing

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
hey @zutigrm, let's also adjust AC for this ticket to have information about the final result only. It can be something like this:
```
* All scripts of event providers are compiled and minimized into their respective bundles when all our assets are built with webpack.
```
All other information is implementation details that can be moved to IB as a hint for the IB writer.\

Thanks in advance.

**Comment by zutigrm** [comment]
@eugene-manuilov Thanks, AC is updated

**Comment by eugene-manuilov** [comment]
Thanks. AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
QA steps here were done as part of Code Review and needed to be done before merging, so moving this one directly to approval, see: https://github.com/google/site-kit-wp/pull/8609#issuecomment-2077263578
