### ISSUE TITLE
Add Learn more link on Ads module setup screen

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8532]
## Feature Description

On the Ads module setup screen, add a external `Learn more` link after the sentence ending "...Google Ads campaigns." to https://support.google.com/google-ads/thread/108976144/where-i-can-find-google-conversion-id-begins-with-aw?hl=en.

![image](https://github.com/google/site-kit-wp/assets/12189958/98699775-1800-45c6-bb36-8c2c97f4592d)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On Ads module setup screen, Add `Learn more` external link, so that first line of the description shows: "Add your conversion ID below. Site Kit will place it on your site so you can track the performance of your Google Ads campaigns. `Learn more`"
  * Link should go to https://support.google.com/google-ads/thread/108976144/where-i-can-find-google-conversion-id-begins-with-aw?hl=en

## Implementation Brief

* [x] Update `assets/js/modules/ads/components/setup/SetupMain.js`
  * Include the `Link` component  with `external` prop. You can see the example of implementation here https://github.com/google/site-kit-wp/blob/ae463cb0af9efd8afeab5b615139f3af06e8ea59/assets/js/modules/adsense/components/settings/AdBlockingRecoverySetupCTANotice.js#L123-L138 `href` can be added once Link is provided

### Test Coverage

* No update is needed

## QA Brief

* Set up the Ads module, confirm the copy has been updated and the link is correct.

## Changelog entry

* Add "Learn more" link in the Ads Module setup screen.

**Comment by bethanylang** [comment]
Noting here that I'm still verifying the link with the Ads team; should have an update on this today!

**Comment by eugene-manuilov** [comment]
IB ✔️, but I am going to reduce the estimate from 7 to 3 since the task here is just to add one element to the setup form component which is a couple of minutes job.

**Comment by bethanylang** [comment]
@benbowler Link updated!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested on develop branch:

- WP 6.5.2, PHP 8.0
- Learn more string appears as per the screenshot
- Clicking on it will open the required link in a new tab : https://support.google.com/google-ads/thread/108976144/where-i-can-find-google-conversion-id-begins-with-aw?hl=en 
- Tested on Firefox, Chrome, Safari and edge
- Tested on other viewports on Chrome emulator for mobile and tablet

Moving this ticket over to Approval column.

<Details>
<img width="1029" alt="Screenshot 2024-04-16 at 13 30 06" src="https://github.com/google/site-kit-wp/assets/125576926/6b41b837-fa4e-4f6e-8822-9e97d0e03b3c">

</details>
