### ISSUE TITLE
Remove `adsModule` Feature Flag

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8541]
## Feature Description

As we gear toward a release of the `Ads Module` within Site Kit, the `adsModule` feature flag needs to be removed, and conditionals updated so that the feature flag no longer gates access to the module and its features.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

All `Ads Module` functionality (JS, PHP, Test Suites) should continue to function without the conditional satisfaction of the `adsModule` feature flag being present. This is to say that when the feature flag is removed, all logic should continue to function identically as it currently does _with_ the `adsModule` feature flag enabled.

## Implementation Brief

* [x] Remove the `adsModule` feature flag entry from the array within `feature-flags.json`
* [x] Update the hook at `assets/js/modules/analytics-4/hooks/useMigrateAdsConversionID.js`
    * [x] Remove the `adsModuleEnabled` conditional const and associated checks against it
    * [x] Remove the `useFeature` import
    * [x] Action `@TODO` item to "Destructure actions here when the `adsModule` feature flag is removed"
* [x] Update the component at `assets/js/modules/analytics-4/components/settings/SettingsForm.js`
    * [x] Remove the `adsModuleEnabled` const and remove it from associated conditional checks
    * [x] Remove the output of `<AdsConversionIDTextField />` entirely
    * [x] Remove the import of `AdsConversionIDTextField`
    * [x] Remove the import of `useFeature`
* [x] Update `assets/js/modules/ads/index.js` 
    * [x] Remove the `isFeatureEnabled( 'adsModule' )` conditional entirely from the `modules.registerModule` call
    * [x] Remove the import of `isFeatureEnabled`
* [x] Update `assets/js/modules/analytics-4/components/settings/OptionalSettingsView.js`
    * [x] Remove the `adsModuleEnabled` const and remove it from conditional checks it appears in, or dictates
    * [x] Remove the import of `useFeature`
* [x] Update the test suite at `assets/js/modules/analytics-4/hooks/useMigrateAdsConversionID.test.js`
    * [x] Remove all references to the `adsModule` entry in `features` key of `renderHook` calls, if it's the only item then remove the `features` key entirely
* [x] Update the story at `assets/js/modules/ads/components/settings/SettingsForm.stories.js`
    * [x]   Remove all references to the `adsModule` entry in `features` key of  the default export, if it's the only item then remove the `features` key entirely
* [x] Update the story at `assets/js/modules/ads/components/setup/SetupForm.stories.js`
    * [x]  Remove all references to the `adsModule` entry in `features` key of  the default export, if it's the only item then remove the `features` key entirely
* [x] Update the E2E test suite at `tests/e2e/specs/modules/ads/setup-with-previous-ads-cenversion-id.test.js`
    * [x] Remove the `beforeEach` action item of `await enableFeature( 'adsModule' );`
    * [x] Remove the import of `enableFeature`
* [x] Update the E2E test suite at `tests/e2e/specs/modules/ads/setup-no-previous-ads-cenversion-id.test.js`
    * [x] Remove the `beforeEach` action item of `enableFeature( 'adsModule' );`
    * [x] Remove the import of `enableFeature`
* [x]  Update the main Modules entry point file at `includes/Core/Modules/Modules.php`
    * [x] Remove the `Feature_Flags::enabled( 'adsModule' )` conditional wrapper around `$this->core_modules[ Ads::MODULE_SLUG ] = Ads::class;`
    * [x] Remove the `use Google\Site_Kit\Core\Util\Feature_Flags;` line near the beginning of the file

### Test Coverage

* Validate that all existing JS, Storybook, PHP and E2E tests continue to pass after the removal of the `adsModule` feature flag and associated conditional logic across the codebase.

## QA Brief

* Retest the entire Ads module using the [Ads Module Bug Bash Instructions](https://docs.google.com/document/d/1D2zd0-HFfVU0Rx5Nq5MbEx_hwU-_sMxeSFkwx8HSgws/edit)
   * You will no longer have to enable the `adsModule` feature flag.
   * In order to test the migration of an existing adsConversionID from the Analytics module I added the value directly to the database, you may also be able to start with an older version of SK: setting your Conversion ID in the Analytics module in this previous version, before upgrading to test this version.
   * **Also remember that the notice dismissal state is persistent**, even after plugin reset, if you have dismissed the migration notice you won't see it again. To see this again you must remove the `ads-conversion-id-notice-dismissed-item` key from the `wp_usermeta` table, `wp_googlesitekitpersistent_dismissed_items` key. Or you can start with a fresh database.

## Changelog entry

* Remove the `adsModule` feature flag.

**Comment by tofumatt** [comment]
Looks good to me. This one was missing an estimate but I think 15 is probably good for this one, because it involves some E2E tests. But looks like the tests themselves won't need any changes aside from removing the feature flag 🤞🏻 

IB ✅

**Comment by benbowler** [comment]
Consider deleting `assets/js/modules/analytics-4/components/common/AdsConversionIDTextField.js` also while we're here.

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified migration and Ads module set up.
- Also, running Ads module bug bash instructions.

@benbowler Please find my observation below-

_Issue > I found that on dev environment under Analytics settings view 'Ads conversion ID' with value NONE is appearing. Ads module is connected. and No other feature flag is enabled._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/ee593e24-310b-495e-868f-41c503d5cf20)

![image](https://github.com/google/site-kit-wp/assets/94359491/6cea5161-6fb1-4977-8909-cbcebd24df27)

![image](https://github.com/google/site-kit-wp/assets/94359491/1daf0b95-54c7-4a49-a1df-fc11a4d2ee48)

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified migration and Ads module set up.
- Also, running Ads module bug bash instructions.
- Verified both issues reported above are resolve now.

cc @wpdarren @kelvinballoo 

<details>

_2) After successful migration, I clicked on 'Got it' which dismiss the notice under analytics settings view. Disconnected and reconnected the analytics module> Ad conversion id= NONE started appearing under analytics settings view mode._ **_(PASS)_**


https://github.com/google/site-kit-wp/assets/94359491/b7f323a5-116c-44b3-b33d-cba4706ae3af


_1) Created new site on dev/main environment. Set up site kit with analytics. Go to Analytics settings view> Ad conversion id= NONE exist. - **(PASS)**_


https://github.com/google/site-kit-wp/assets/94359491/68bc31a0-7215-4dcd-9361-555e9a403c71

</details>
