### ISSUE TITLE
Remove unneeded, legacy module widget area constants.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8544]
## Feature Description

The constants `AREA_MODULE_ADSENSE_MAIN` and `AREA_MODULE_SEARCH_CONSOLE_MAIN` are remnants of the old module screens, are no longer needed and should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The constants `AREA_MODULE_ADSENSE_MAIN` and `AREA_MODULE_SEARCH_CONSOLE_MAIN` and remaining redundant usage of them should be removed.

## Implementation Brief

* [ ] Remove the constants `AREA_MODULE_ADSENSE_MAIN` and `AREA_MODULE_SEARCH_CONSOLE_MAIN` constants and the remaining, unnecessary usage of them. See:

https://github.com/google/site-kit-wp/blob/ace6a1f96345db052da8004b70e60d11d016aa40/assets/js/modules/adsense/constants.js#L20

https://github.com/google/site-kit-wp/blob/ace6a1f96345db052da8004b70e60d11d016aa40/assets/js/modules/search-console/constants.js#L19
### Test Coverage

* No changes should be needed.

## QA Brief

* Do a quick smoke test to ensure that the removal of the constants does not cause any issues.
* Verify that the dashboard loads as expected and that the AdSense and Search Console module widgets are displayed correctly.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Done smoke testing of plugin functionality.
- Verified Dashboard widgets, AdSense setup, main and entity dashboard.

<details>


https://github.com/user-attachments/assets/014b8029-1867-400c-a7ff-31e373510994

</details>
