### ISSUE TITLE
Add plugin integration for OptinMonster

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8554]
## Feature Description

OptinMonster conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.pkhe2y37uvhr) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from OptinMonster should be tracked and supported by our infrastructure
* When a new lead is submitted through OptinMonster form, a `submit_lead_form` conversion event should be tracked

## Implementation Brief
* [x] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\OptinMonster`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `optin-monster`
  * It should have following methods:
    * `is_active` - check if `OMAPI_FILE` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain one string `submit_lead_form`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * Include `'execution' => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance
* [x] Add `assets/js/event-providers/optin-monster.js`
  * Include the OptinMonster specific event listener that will trigger the event once document is loaded. This is taken from the official documentation:
```js
document.addEventListener('om.Analytics.track', function(event) {
	if ( 'conversion' === event.detail.Analytics.type ) {
		console.log(event.detail.Campaign.id + '-' + event.detail.Campaign.type + ' successfully tracked a conversion.');
	}
} );
```
* [x] Include JS file path in the `conversionEventProviders.config.js` webpack partial added in #8531
* [x] Ensure `yield conversionEventProviders( mode );` is run in the main `webpack.config.js` config (it is commented out while there are no entry points)
* [x] Include the plugin name and class path to the array of main `Conversion_Events` class property added in #8528

### Test Coverage

* You can add basic test coverage for OptinMonster class, testing that `get_event_names` method returns correct event names, and `register_script` returns script instance with proper handle. Also `is_active` method can be confirmed by defining the plugin constant

## QA Brief

* Install an extension for your browser that lets you track Analytics events
* Enable the `conversionInfra` feature flag for your site
* Install and activate the optinmonster plugin
* Create a new form and open it on the frontend
* Submit the form and ensure that the appropriate event is tracked.

## Changelog entry

* Add conversion infrastructure for OptinMonster.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by zutigrm** [comment]
@benbowler Added event name we should track in the AC

**Comment by benbowler** [comment]
Thanks @zutigrm I didn't get as much time as I hoped to work on this ticket today so have un-assigned while I'm out for others to work on.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.
- Installed OptionMonster plugin.
- Activated Free plan.
- Created a form and submitted it.

@eugene-manuilov On submitting form `'form-submit' `event tracked instead of `submit_lead_form`. Is this expected or I used different form?


![image](https://github.com/google/site-kit-wp/assets/94359491/635e26b9-fa0e-48c9-ad92-33499f2e5f33)


https://github.com/google/site-kit-wp/assets/94359491/1d6da4c8-ad00-4334-9756-7bfe74f459e7

**Comment by eugene-manuilov** [comment]
Looks like it is a bug. I'll work on it.

**Comment by eugene-manuilov** [comment]
@mohitwp, after looking into it more it seems that you had a broken version of the plugin on that site. I upgraded it to the latest `develop` version and now I see the right event is tracked:

![Screenshot from 2024-05-08 16-42-18](https://github.com/google/site-kit-wp/assets/873049/659fc68b-a03d-46ec-be4b-af8d9d8ce944)

The first two (`form_start` and `form_submit`) are triggered by the OptinMonster, and the last one (`submit_lead_form`) is triggered by the SK plugin.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment plugin zip file provided by Eugene.
- Verified when `conversionInfra` feature flag is disabled.
- Verified when `conversionInfra `feature flag is enabled.
- Verified when Analytics is connected.
- Verified when both Analytics and ads module are connected.
- Verified when only Ads module is connected.
- Verified when both Analytics and ads module are disconnected but `conversionInfra` feature flag is enabled.

<details>

**Submit lead event**

![image](https://github.com/google/site-kit-wp/assets/94359491/3bcd2ed7-63dc-4ba2-b944-ce7013151f15)

**When  `conversionInfra `feature flag is enabled and Analytics is connected**

https://github.com/google/site-kit-wp/assets/94359491/6bbc3dd7-5bde-4b11-92ef-d35c687513ca

** When  `conversionInfra` `feature flag is not enabled .Event not tracked.**

https://github.com/google/site-kit-wp/assets/94359491/f72de0a8-f9d8-4dd0-b58b-1de47c447fe5

`</details>
