### ISSUE TITLE
Add `adsPax` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8555]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new feature flag for `adsPax` should be added to the list of available features

## Implementation Brief

* [x] Add the new feature flag to `feature-flags.json`

### Test Coverage

* No changes

## QA Brief

* Verify that `adsPax` is appearing in the feature flags list.

## Changelog entry

* N/A

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that new feature flag `adsPax` appearing in the feature list.

![image](https://github.com/google/site-kit-wp/assets/94359491/762d8ab8-12bd-4fd8-9068-ba0286ee1092)
