### ISSUE TITLE
Create `PAX` component

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8557]
## Feature Description

When it comes to rendering the PAX app, we'll leverage a dedicated component to render the target element, launch the app, and expose its services.

The component should also handle loading (pre + during launch) and error states (should launch fail).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component named `PAXEmbeddedApp` should be created in the Ads module. It should be responsible for rendering the target element, launching the PAX app, and exposing its services.
* The component should:
    * Show a loading state while the PAX app is being loaded/launching. (Eg. the PAX script's global variables are not available.)
		* Nice to have: adapt the loading state for the `displayMode` (see below)
    * Render the target element and launch the PAX app once the PAX script is available.
    * Display an error if the user is using an Ad Blocker
    * If the PAX app will output error codes/functions, the `PAXEmbeddedApp` component should display an error if the PAX app fails to launch. (Optional.)
* The component should be able to be rendered multiple times on the same page/same React app, meaning any IDs it creates to render the PAX app in should include an instance ID to avoid conflicts.
* The component should load required PAX config values by default without all of them needing them to be supplied as props (#8556).
* The component should be able to accept the following props:
    * `displayMode` - The display mode of the PAX app. (allowable options for now: `setup`, `reporting`, `default`)
	* `onLaunch(func)` - accepts a function that is called on successful launch of the app, passing the app as the only parameter
* The component should pass the retrieved PAX config values and partner services to the PAX app (#8556).
* The component should not re-render its HTML after rendering the PAX app, so that it isn't removed from the DOM with updates to the props. Any updates to props should not trigger a re-render of the DOM/HTML. (This is to prevent the PAX app from being reloaded.)
    * Props can trigger hooks to run in order to interact with the PAX app, though none are needed yet.

## Implementation Brief

* [ ] Create `PAXEmbeddedApp` in the Ads module components directory, eg. `assets/js/modules/ads/components/PAXEmbeddedApp.js`.
* [ ] The component should use `const instanceID = useInstanceId( PAXEmbeddedApp, 'PAXEmbeddedApp' );` to create a unique instance ID for each component.
* [ ] The component should include that instance ID in its output for the PAX div's ID (eg </code>id={`sitekit-pax-embedded-app-${instanceID}`}</code>). This will be used when triggering the PAX code to embed its app, eg. <code>clientConfig: { contentContainer: `#${`sitekit-pax-embedded-app-${instanceID}`}` }</code>.
* [ ] The component should use a `useInterval` hook to check if the PAX script is available by ensuring `google.ads.integration.integrator.launchGoogleAds` exists, and if not, show a loading state. (It can also check on mount and cancel the timeout re-render if the script is already available.)
* [ ] The component should check to see if an AdBlocker is enabled and show a warning message if it is.
* [ ] The component should call `google.ads.integration.integrator.launchGoogleAds` with the appropriate config values from [#8556](https://github.com/google/site-kit-wp/issues/8556), as well as the `clientConfig.contentContainer` from the component.
* [ ] The component should handle any errors that occur during the launch of the PAX app, such as if the PAX app fails to launch. This can be done by launching the PAX app in a `try` block and catching any errors that occur:
	```js
	try {
		const paxApp = await google.ads.integration.integrator.launchGoogleAds(paxConfig, paxServices);
	} catch (error) {
		console.error('Failed to launch PAX app', error);
		// Handle the error here
	}
	```
* If an `onLaunch` prop is present, call it with the app instance following a successful launch

### Test Coverage

* It won't be possible (or it will likely be difficult) to test the PAX app's actual `launchGoogleAds` code in JSDOM/Jest, but it should be possible to test the component's behavior when the PAX script is not available, when the PAX script is available, and when the PAX app fails to launch in Jest.
	* We should however be able to make assertions about the values the app is launched with by using a `jest.fn` in place of `launchGoogleAds` in a Jest environment

## QA Brief

Should be done as part of Code Review, but no explicit QA step is needed after these steps are done by a Code Reviewer (eg. this can be moved directly to approval after code review).

* You could QA this by adding the `<PAXEmbeddedApp />` to `assets/js/modules/ads/components/settings/SettingsView.js`, which is what I did to test it. But I don't think there's much QA to do in this issue, since it's just about creating the component. 🤔 

## Changelog entry

* Implement the PAX component to display the embedded app.

**Comment by tofumatt** [comment]
@aaemnnosttv @10upsimon Happy for either of you to take a look, just want to make sure I didn't miss anything here on the ACs 😅

**Comment by tofumatt** [comment]
I've added an IB here as well, so if the ACs look good feel free to move this right to IBR 👍🏻

**Comment by tofumatt** [comment]
Oh, side note: I have a good sense on how I'll implement this one so it'll be most efficient to assign this to me if you move it to the Execution Backlog, and I'll start on it Monday.

**Comment by zutigrm** [comment]
One note here, it seems we have duplicate AC requirement in two issues, it is mentioned here that config and services should be obtained. But same point is also mentioned in #8558. I will skip that part in #8558 as it makes sense for config to be obtained here, as it was not planned for this component to accept these as props.
cc: @tofumatt @10upsimon

**Comment by aaemnnosttv** [comment]
This looks good for the most part, I just added a prop for `onLaunch` and tweaked a few other minor details, but this should be good to go now.

AC + IB ✅

**Comment by aaemnnosttv** [comment]
@tofumatt I had a quick look here and [found a few things that need addressing](https://github.com/google/site-kit-wp/pull/8624#pullrequestreview-2034438138) so I'm sending this back for what should be a quick followup 👍

**Comment by tofumatt** [comment]
Assigning this to @aaemnnosttv since he reviewed this and requested updates 🙂

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt – moving to approval as there isn't much to QA here yet as noted above.
