### ISSUE TITLE
Extend Ads settings view for PAX

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8563]
## Feature Description

Once new settings are added (see #8562), the Ads module's settings view should be extended to display them.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The current Ads module `<SettingsView>` component should include read-only views of the settings obtained from the PAX app as part of #8562, namely:
    * `paxConversionID`
        * The conversion tracking ID obtained from the PAX application following successful setup
        * Label to read "Conversion Tracking ID"
        * Value to be obtained using the applicable datastore selector
        * Show "None" when value is an empty string
    * `extCustomerID`
        * The external customer ID obtained from the PAX application following successful setup
        * Label to read "Customer ID"
        * Value to be obtained using the applicable datastore selector
        * Show "None" when value is an empty string
    * The above two settings values are to render within the existing `<SettingsView>` component of the Ads module, example below:
    
![Site Kit by Google Settings ‹ sitekit 10uplabs com — WordPress 2024-04-18 at 11 29 52 AM](https://github.com/google/site-kit-wp/assets/72872375/7b2aed13-7e53-4612-99b0-296370925c84)

## Implementation Brief

* [ ] Update the file at `assets/js/modules/ads/components/settings/SettingsView.js`
    * [ ] Define the necessary constants to obtain the PAX Conversion ID and External Customer ID settings values:
    ```
    	const paxConversionID = useSelect( ( select ) =>
		select( MODULES_ADS ).getPaxConversionID()
	);

	const extCustomerID = useSelect( ( select ) =>
		select( MODULES_ADS ).getExtCustomerID()
	);
    ```
    * [ ] Within the main `return` body of the component:
        * [ ] Update the conditional check that outputs the current `Conversion Tracking ID` value to only show if the PAX values are not present, given that the PAX setup dictates the values if the PAX path was used:
        ```
        { ! isAdBlockerActive && ! paxConversionID && ! extCustomerID && ( ...
        ```
        * [ ] Render the appropriate markup (div's, h5's, p's, <DisplaySetting> etc) for each of the 2 fields:
            * [ ] `paxConversionID` to have a label of `Conversion Tracking ID` and a default value of `'None'`
            * [ ] `extCustomerID` to have a label of `Customer ID` and a default value of `'None'`
* [ ] The settings view for Ads should look like this if PAX settings values are present:
<img width="1350" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/65c36738-0754-4671-a024-0c28490707a7">
 

### Test Coverage

* Update the applicable StoryBook tests to include rendering of PAX fields.

## QA Brief

* Enable the `adsPax` feature flag if the feature is not available for you
* Setup and connect the Ads module
* Navigate to Site `Kit > Settings` and expand the `Ads` module settings view
* Validate that only the existing Conversion ID value is shown as set during module setup, i.e

<img width="1351" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/f2921fef-dc07-4b7f-b951-fc5f49b83d7c">

* Manually remove existing Conversion ID value and set the PAX Conversion ID and External Customer ID values using the snippet below in console:

```
googlesitekit.data.dispatch( 'modules/ads' ).setConversionID('');
googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('AW-98765');
googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('C-98765');
```

* Validate that the PAX fields now render in the settings view as below:

<img width="1355" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/4a3ef42c-5506-4e53-b476-916d6dab99da">

## Changelog entry

* Add PAX settings to Ads settings.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@10upsimon 

**Question >** I noticed that 'None' appears only when I pass empty string for both `.setExtCustomerID`  and `setPaxConversionID `

> `googlesitekit.data.dispatch( 'modules/ads' ).setConversionID('');
googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('');
googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('');`

If I pass empty string for one value then Settings view shows nothing. Is this expected ?

`
googlesitekit.data.dispatch( 'modules/ads' ).setConversionID('');
googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('AW-98765');
googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('');`

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/2c17e04e-fffe-4040-9708-8d09bfd6db4b)

![image](https://github.com/google/site-kit-wp/assets/94359491/af75177c-3e71-4cce-887d-c1fb9541a3aa)

</details>



- Tested on dev environment.
- Verified the Ads Settings view for PAX when Analytics is not connected.
- Verified the Ads Settings view for PAX when Analytics is connected.
- Verified that Ads Settings view for PAX is appearing as per AC.
- Verified that the PAX fields render in the settings after using snippet as per AC.
- Verified that  "None" appears when value is an empty string.

PASS CASES:

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/763668a4-44f7-4aa2-b705-de2d396c068f)

![image](https://github.com/google/site-kit-wp/assets/94359491/4c4a43df-929f-4ce1-a5e8-ca8e6c359f29)


https://github.com/google/site-kit-wp/assets/94359491/4c4d51d2-3bdd-4c60-87d9-1ea2a3915af2

</details>

**Comment by 10upsimon** [comment]
@mohitwp I used the extCustomerID as the main checker, as we'd never have a PAX conversion ID without an external customer ID, and vice versa. The PAX app will only send a completion signal once the campaign is successfully set up, and this is when we will grab the ext customer ID as well, so in theory there should never be a case where one is present and the other is not. We'd also not consider the PAX onboarding complete if both of these values are not present.

@aaemnnosttv let me know if you agree here, or if you feel we should cater for one value setting being empty and the other not (of the PAX settings that is).

**Comment by 10upsimon** [comment]
@wpdarren @mohitwp I've updated the logic so that the settings for PAX render even if one value is only present of the two. @mohitwp 's observations above should be satisfied by the time this gets to QA.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @10upsimon 

- Tested on main environment.
- Verified the Ads Settings view for PAX when Analytics is not connected.
- Verified the Ads Settings view for PAX when Analytics is connected.
- Verified that Ads Settings view for PAX is appearing as per AC.
- Verified that the PAX fields render in the settings after using snippet as per AC.
- Verified that "None" appears when value is an empty string.
- Verified that if `adsPax `feature flag is not enabled then running console snippet do not display PaxConversionID and CustomerID under Ads module settings.

<details>

**_When `adsPax `feature flag is not enabled_**

![image](https://github.com/google/site-kit-wp/assets/94359491/0096bddd-dbc3-416d-9cc6-3fcb7166cadd)


https://github.com/google/site-kit-wp/assets/94359491/00b4c195-89b0-46cc-9506-c20087f4bcf6


**_When `adsPax `feature flag is enabled_**

![image](https://github.com/google/site-kit-wp/assets/94359491/3bc0694a-c646-4871-b6cd-eabe7ac307a0)


_**Changed Value :**_

![image](https://github.com/google/site-kit-wp/assets/94359491/9a1dbd7d-67b9-4769-a26a-e13754c3ca49)

**_When single value PaxConversionID value is pass_**

![image](https://github.com/google/site-kit-wp/assets/94359491/42497d50-f848-4dce-88c4-cc449aa91e54)

**_When single value CustomerID  is pass_**

![image](https://github.com/google/site-kit-wp/assets/94359491/704cade4-fa3d-4009-84bb-82c87ba32f0a)

**_When PaxConversionID value is empty string_**

![image](https://github.com/google/site-kit-wp/assets/94359491/a3629608-8eb5-46f9-816e-5eaad0378d6a)

**_When CustomerID value is empty string_**

![image](https://github.com/google/site-kit-wp/assets/94359491/be5ef996-0e2b-4f49-8b6e-e59ad8231e47)

**_When both PaxConversionID and CustomerID value is empty string_**

![image](https://github.com/google/site-kit-wp/assets/94359491/2e9e2db6-e8e0-4d51-8d8c-5ed4cf3148a7)


</details>
