### ISSUE TITLE
Update Ads module to conditionally require adwords scope

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8565]
## Feature Description

The PAX application requires an OAuth token with the Adwords scope (`https://www.googleapis.com/auth/adwords`) granted.

Since this is only relevant to request + keep when using PAX, it should be requested on-demand and then treated as a required scope so long as Ads is connected via PAX.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `https://www.googleapis.com/auth/adwords` scope should be conditionally required by the Ads module when the `adsPax` feature is enabled
- Once the scope has been granted, it should continue to be required for the current user
- Once the `extCustomerID` is set, it should be generally required by the module

## Implementation Brief

- [ ] Update the Ads module to include the `Module_With_Scopes` interface + use the `Module_With_Scopes_Trait` trait
  - Add the `register_scopes_hook` to `register`
  - Implement the `get_scopes` method as follows:
  - By default it should not require any, and return an empty list
  - If the `adsPax` feature is enabled, conditionally return the adwords scope if the scope is already granted, or `extCustomerID` is set/valid

### Test Coverage

- Add test coverage for the conditional behavior using `googlesitekit_auth_scopes` filter for assertions

## QA Brief

* Setup Site Kit with proxy plugin
* Enable `adsPax` feature flag
* Force the adwords permission popup with following JS snippet: 
```js
googlesitekit.data.dispatch("core/user").setPermissionScopeError({
  code: "missing_required_scopes",
  message: "Additional permissions are required.",
  data: {
    status: 403,
    scopes: ["https://www.googleapis.com/auth/adwords"],
    skipModal: false,
    redirectURL:
      "/wp-admin/admin.php?page=googlesitekit-dashboard",
  },
});
```
* After OAuth redirection, go back to Site Kit dashbaord and paste this JS snippet: `googlesitekit.data.select('core/user').getGrantedScopes()`, verify you see adwords scope in the outputted list

## Changelog entry

- Add feature that requests AdsWords scope when required.

**Comment by tofumatt** [comment]
ACs here look good, moving to IB 👍🏻

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment using service staging proxy plugin.
- Verified that Additional scrope permission modal appeared successfully.
- Verified that user is able to complete OAuth Flow.
- Verified that after completing OAuth flow user redirects to main dashboard.
- Verified that when we paste  this JS snippet:` googlesitekit.data.select('core/user').getGrantedScopes(), ` then adwords scope in the outputted list.
- I ran code snippet multiple times and verified that  Once the scope has been granted, it should continue to be required for the current user.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/ce185c8a-2621-4632-9b08-0f70420cc95e)

![image](https://github.com/google/site-kit-wp/assets/94359491/42a39b03-a68b-4a99-b0d3-524112e7af75)


https://github.com/google/site-kit-wp/assets/94359491/6d409041-7598-46c9-99e7-f7e5d53d84e2

</details>
