### ISSUE TITLE
Can't Install, Redirect Problem

### ISSUE THREAD

**Issue by xcrap** [google/site-kit-wp#857]
After installing the plugin, I start the setup process, access and set permissions in the account but when I've redirected back to the website I've got redirected here:

https://www.mydomainname.com/?oauth2callback=1&authuser=0&(...)...

And this page does not exists...
Help?

**Comment by Rahulkr88** [comment]
I have the issue

**Comment by joanpaae** [comment]
I have the same issue

https://www.mysitexxx.cl/wp-admin/admin.php?page=googlesitekit-splash

https://sitekit.withgoogle.com/site-management/setup/?site_id=9uXANRWMJjftHuv87sbL8APR-fn9PsJRudPjZES5zKFEsjY.apps.sitekit.withgoogle.com&code&version=1.0.4&scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters



https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=609348718642389-m7lo0cb9po1sjldsvbtlqkf0orgbgtci2p.apps.googleusercontent.com&as=NphDMe4sGGIitxbsWffscQ&destination=https%3A%2F%2Fsitekit.withgoogle.com&approval_state=!ChRtS2lVaHZxbURfVVhDacjZJQ2ZZehIfSXhjSms4N0MtR0FlRUZvSEdUZHlJLTFkN2lqMDVoWQ%E2%88%99AJDr988AAAAAXc_6F1-FS20PwcXYMrWh3_zwVR-Y24UC&oauthgdpr=1&xsrfsig=ChkAeAh8T1CZayafd0mX8l7WHOtJyhHbUTXmX-Eg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWdN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow


https://accounts.google.com/signin/oauth/consentsummary?authuser=1&part=AJif8hAPmisQLC-AtqlxUScrE9KqZ97TSX9KFSKs3h78GzQq4CfV5aZZLwsMAQlAgqQpsLRtw8W3DdYYGdoaYDUxCv9ryUDyrDjfVtxxbdb1QhJfbr3x4RPM4AANccyYMQf2V3Ry0x0oNaDkwaFQw46uFa8M-axeNnYSFPYrZ6eSnAk58EidnE5dtV9_FguK2i2r9nRtOrbsXvKypU0Zmn30A8IFhKaZd-OraiwJQaHM35VwqSJfymCWyiY7jmEWOvbZvIvqCe-U9JWTzMrnR6wLbhh2-v8JpwvKju_JC-MenmBRxi-0QIUIZGT-RSUttPmwAHREf5cdCVFeeT6hdqh7qRZJ9hOfm_isY9EcsTHLz-dCAqjQ-EZFsorvl4q8EG4k7iUZq_G8BytMBxv5eVn-1zsDoACTokWpgRl_4JLgfC7MRWz7xMVmkVKOWjVIbgKeKLgJVC1BVu5X&as=NsphDMe4sGGIitxbsWffscQ&pli=1&rapt=AEjHL4NQgv3dyKo5tvLV33j8IJqfRLswQ505dy4s9JCOmqZyretvAY5jtEgbR_56ocHjIvuuUvfbzd1pT2PdODWst17bJRj4mrw

https://www.mysitexxx.cl/?oauth2callback=1&authuser=1&code=4%2FtQEVdTZBjiFkqf8yJJeGnIN_OdtrxbTSJMfWHsXz4HJ86PPbHGwbrQo8k6h6Canu2IiSgYjHcfbOt6jCruqt4KdBg&prompt=consent&scope=email%20profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&session_state=35ce49bab16240af38ab469113653a5aa608ef744..2fd3

**Comment by ernee** [comment]
@xcrap @joanpaae @Rahulkr88 thanks for reaching out. Site Kit support has moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Please post a brand new topic there so we can help with your issue.
