### ISSUE TITLE
Add Plugin Integration for Popup Maker

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8570]
## Feature Description

Popup Maker conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.pkhe2y37uvhr) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from Popup Maker should be tracked and supported by our infrastructure
* When form created with Popup Maker is submitted, conversion event `submit_lead_form` should be tracked.

## Implementation Brief

* [ ] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\Popup_Maker`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `popup-maker`
  * It should have following methods:
    * `is_active` - check if `POPMAKE_VERSION` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain one string `submit_lead_form`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * Use `popup-maker-site` script as dependency
      * Include `'execution' => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance 
* [ ] Add `assets/js/event-providers/popup-maker.js`
  * Include the Popup Maker specific event listener that will trigger the event once document is loaded. Popup Maker uses custom event handling, so this is the way to attach event listener, as they do it in [their codebase](https://github.com/PopupMaker/Popup-Maker/blob/cb5b1b2ee44c584162fafd9fcf842651f1d2fdbb/assets/js/src/site/plugins/pum-analytics.js#L95-L128)
* [ ] Include JS file path in the `conversionEventProviders.config.js` webpack partial added in #8531
* [ ] Ensure `yield conversionEventProviders( mode );` is run in the main `webpack.config.js` config (it is commented out while there are no entry points)
* [ ] Include the plugin name and class path to the array of main `Conversion_Events` class property added in #8528

### Test Coverage

* You can add basic test coverage for `Popup_Maker` class, testing that `get_event_names` method returns correct event names, and `register_script` returns script instance with proper handle. Also `is_active` method can be confirmed by defining the plugin constant

## QA Brief

* Install a plugin to monitor Google Analytics events, eg. Google Analytics Debugger from the Chrome Web Store
* Setup Site Kit with `adsModule` and `conversionInfra` feature flags
* Connect `Ads` or `Analytics` module
* Install and activate `Popup Maker` plugin
* Using the example popup provided by the plugin, create a subscription form using the `/wp-admin/post-new.php?post_type=popup` URL: <img width="1412" alt="image" src="https://github.com/google/site-kit-wp/assets/10414808/4a147082-afb6-4ed5-8f64-357de2aa058b">
* Ensure the popup has a trigger to open:
![Screenshot 2024-05-14 at 16 26 10](https://github.com/google/site-kit-wp/assets/90871/7c526f15-8326-412a-9270-b5883e827a35)
* Using a private browsing window (or signing out of Site Kit):
  * Open any page on frontend
  * Submit the popup form that appears
  * Verify that `submit_lead_form` event is tracked

## Changelog entry

* Add conversion infrastructure for Popup Maker.

**Comment by eugene-manuilov** [comment]
@zutigrm, similarly to the CF7 integration, we need to specify exact events that we expect to be triggered after this integration is implemented.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment plugin zip file link provided by Eugene.
- Verified when `conversionInfra` feature flag is disabled.
- Verified when `conversionInfra` feature flag is enabled.
- Verified when Analytics is connected.
- Verified when both Analytics and ads module are connected.
- Verified when only Ads module is connected.
- Verified when both Analytics and ads module are disconnected but `conversionInfra` feature flag is enabled.
- Verified Submit lead form event tracked as per AC.

<details>

**Submit lead form event**

![image](https://github.com/google/site-kit-wp/assets/94359491/1696358d-5926-4973-8275-05a83278be7a)

**When conversionInfra feature flag is enabled**

_Only Ads module connected_


https://github.com/google/site-kit-wp/assets/94359491/d0028c52-3d43-4266-bfef-e75b4e7a87ae


_Both Analytics and Ads module connected_


https://github.com/google/site-kit-wp/assets/94359491/4fcc90ef-3c0e-421f-b045-702d8b5aea81


Only Analytics connected


https://github.com/google/site-kit-wp/assets/94359491/569cdbf7-27e2-417d-bf98-23f176259264

_Both Analytics and Ads module are not connected_


https://github.com/google/site-kit-wp/assets/94359491/23bd5598-98fc-4ff8-aae3-9964216c0604



**When conversionInfra feature flag is disabled**


https://github.com/google/site-kit-wp/assets/94359491/b2455ab7-04a4-4c2d-bef9-9962272a198c


</details>
