### ISSUE TITLE
Add Plugin Integration for Mailchimp

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8571]
## Feature Description

Mailchimp conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.pkhe2y37uvhr) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from Mailchimp should be tracked and supported by our infrastructure. 
* When Mailchimp form is submitted, a conversion event - `submit_lead_form` should be tracked.

## Implementation Brief

* [x] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\Mailchimp`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `mailchimp`
  * It should have following methods:
    * `is_active` - check if `MC4WP_VERSION` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain one string `submit_lead_form`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * Use `mc4wp-forms-api` script as dependency
      * Include `'execution' => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance
* [x] Add `assets/js/event-providers/mailchimp.js`
  * Include the Mailchimp specific event listener that will trigger the event once document is loaded. Mailchimp uses custom event handling, so this is the way to attach event listener:
```js
mc4wp.forms.on('subscribed', function(form) {
  // gtag.js
  gtag('event', 'submit_lead_form', {'event_category': 'Mailchimp', 'event_label': 'Name: ' + form.name + ' ID: ' + form.id});
});
```
* [x] Include JS file path in the `conversionEventProviders.config.js` webpack partial added in #8531
* [x] Ensure `yield conversionEventProviders( mode );` is run in the main `webpack.config.js` config (it is commented out while there are no entry points)
* [x] Include the plugin name and class path to the array of main `Conversion_Events` class property added in #8528

### Test Coverage

* You can add basic test coverage for Mailchimp class, testing that `get_event_names` method returns correct event names, and `register_script` returns script instance with proper handle. Also `is_active` method can be confirmed by defining the plugin constant

## QA Brief

* Install an extension for your browser that lets you track Analytics events (Eg. Google Analytics Debugger)
* Enable the `conversionInfra` feature flag for your site
* Setup Analytics, or Ads module, or both
* Install and activate the mailchimp for wp plugin
* Copy the shortcode for the mailchimp form, add it to a page and open that page on the frontend
* Submit the form and ensure that the appropriate event is tracked

## Changelog entry

* Add conversion infrastructure for Mailchimp.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment plugin zip file link provided by Eugene.
- Verified when `conversionInfra` feature flag is disabled.
- Verified when `conversionInfra` feature flag is enabled.
- Verified when Analytics is connected.
- Verified when both Analytics and ads module are connected.
- Verified when only Ads module is connected.
- Verified when both Analytics and ads module are disconnected but `conversionInfra` feature flag is enabled.
- Verified Submit lead form event tracked as per AC.


<details>

Submit lead form event

![image](https://github.com/google/site-kit-wp/assets/94359491/b4dbf80f-876e-4b37-a102-a34f4bd115bb)

![image](https://github.com/google/site-kit-wp/assets/94359491/404300c7-faba-4319-b3fc-9d337d19db64)

**When conversionInfra feature flag is enabled**

_Only Ads module connected_


https://github.com/google/site-kit-wp/assets/94359491/f127a457-0576-4513-99b3-f5c5cd833dd3


_Both Analytics and Ads module connected_


https://github.com/google/site-kit-wp/assets/94359491/d18e9150-1b87-4968-8a3b-5a1926a88731

_Only Analytics connected_


https://github.com/google/site-kit-wp/assets/94359491/b4ef5a9e-6c97-4c8d-8e6e-c9a17a22f4bf

_Both Analytics and Ads module are not connected_


https://github.com/google/site-kit-wp/assets/94359491/3f4e10bc-7042-4926-b111-35fedbc12a84


**When conversionInfra feature flag is disabled**


https://github.com/google/site-kit-wp/assets/94359491/4bbe91db-0985-43d3-b77c-f234f535c0d9

</details>
