### ISSUE TITLE
Add Plugin Integration for WPForms

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8572]
## Feature Description

WPForms conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.pkhe2y37uvhr) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from WPForms should be tracked and supported by our infrastructure. 
* When a form built by WPForms is submitted, `submit_lead_form` conversion event should be tracked.

## Implementation Brief

* [x] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\WPForms`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `wpforms`
  * It should have following methods:
    * `is_active` - check if `WPFORMS_VERSION` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain one string `submit_lead_form`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * Use `wpforms` script as dependency
      * Include `'execution' => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance 
* [x] Add `assets/js/event-providers/wpforms.js`
  * Include the WPForms specific event listener that will trigger the event once document is loaded. Events are handled with jQuery so `.on()` listener should be used, example from their codebase:
```js
$( '.wpforms-form' ).on( 'wpformsBeforeFormSubmit', function() {
    // send submit_lead_form event to the gtag(...)
} );
```
* [x] Include JS file path in the `conversionEventProviders.config.js` webpack partial added in #8531
* [x] Ensure `yield conversionEventProviders( mode );` is run in the main `webpack.config.js` config (it is commented out while there are no entry points)
* [x] Include the plugin name and class path to the array of main `Conversion_Events` class property added in #8528

### Test Coverage

* You can add basic test coverage for `WPForms` class, testing that `get_event_names method `returns correct event names, and `register_script` returns script instance with proper handle. ALso `is_active` can be confirmed by defining the plugin constant

## QA Brief

* Install an extension for your browser that lets you track Analytics events
* Enable the `conversionInfra` feature flag for your site
* Setup Analytics, or Ads module, or both
* Install and activate the wpforms plugin
* Create a new form, add it to a page and open that page on the frontend
* Submit the form and ensure that the appropriate event is tracked

## Changelog entry

* Add conversion infrastructure for WPForms.

**Comment by eugene-manuilov** [comment]
@zutigrm, similarly to the CF7 integration, we need to specify exact events that we expect to be triggered after this integration is implemented.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.
- Tested after enabling `conversionInfra` feature flag.
- Tested after enabling GA debug extension.
- Installed WP Forms lite plugin and created a new form.
- Verified for both scenarios when only Ads module is setup or when both  Analytics and Ads module is setup.
- In my testing when a form built by WPForms is submitted, `submit_lead_form` conversion event is not tracked.

@eugene-manuilov I'm using WP forms free version. Can you please confirm if changes introduced in this ticket support the WP forms lite version? 
 cc @wpdarren 

<details>


![image](https://github.com/google/site-kit-wp/assets/94359491/64fc829b-178d-4fe2-bc96-e8ffe30e73f1)

![image](https://github.com/google/site-kit-wp/assets/94359491/5807b920-b0d3-4b27-b093-d734323fa267)


https://github.com/google/site-kit-wp/assets/94359491/e3f9a25d-d05e-41e7-8a3d-0cba9cd77c39


https://github.com/google/site-kit-wp/assets/94359491/d0478f19-2d92-4a14-91eb-7caa7825938b



</details>

**Comment by mohitwp** [comment]
### QA Update  ✅ 


- Tested on dev environment.
- Tested after enabling conversionInfra feature flag.
- Tested after enabling GA debug extension.
- Installed WP Forms lite plugin and created a new form.
- Verified when Analytics is connected.
- Verified when both Analytics and ads module are connected.
- Verified when only Ads module is connected.
- Verified when both Analytics and ads module are disconnected but `conversionInfra ` feature flag is enabled.
- Verified when `conversionInfra` feature flag is disabled

Note : To test this I used dev environment zip file provided by Eugene.


<details>.

**_Analytics is connected_**

![image](https://github.com/google/site-kit-wp/assets/94359491/e902475d-a68d-4998-801d-f2aca931cd14)


https://github.com/google/site-kit-wp/assets/94359491/2b838e7d-8c8a-48eb-87db-e5a4e3940880

 **_Ads Module is connected_**

![image](https://github.com/google/site-kit-wp/assets/94359491/59a6cfba-d104-4ee0-8f02-1ed0b6787b9c)


https://github.com/google/site-kit-wp/assets/94359491/7827bad9-73f0-4e13-8ce7-31c57eb595b1

Both Analytics and Ads module are connected

![image](https://github.com/google/site-kit-wp/assets/94359491/455b4bd1-5a3f-458d-b24b-48197bd7bbbe)


https://github.com/google/site-kit-wp/assets/94359491/510c5188-9fd8-4ddc-8992-7831198bc3f1

Both Analytics and Ads module are disconnected but 'ConversionInfra' feature flag is enabled. No event tracked.


</details>
