### ISSUE TITLE
Add Plugin integration for Contact Form 7

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8574]
## Feature Description

Contact Form 7 conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.pkhe2y37uvhr) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from Contact Form 7 should be tracked and supported by our infrastructure.
* When form built by Contact For 7 is submitted, a `contact` conversion event should be tracked.

## Implementation Brief

* [x] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\Contact_Form_7`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `contact-form-7`
  * It should have following methods:
    * `is_active` - check if `WPCF7_VERSION` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain one string `contact`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * You can use `contact-form-7` script as dependency, although since we are only attaching an event, there is no specific reason for dependency
      * Include `'execution'    => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance
* [x] Add `assets/js/event-providers/contact-form-7.js`
  * Include the CF7 specific event listener that will trigger the event once document is loaded, example from plugin documentation:
```js
document.addEventListener( 'wpcf7mailsent', function ( event ) {
    gtag( 'event', 'contact', {
        'event_category': event.detail.contactFormId,
        'event_label': event.detail.unitTag
    } );
}, false );
```
* [x] Include JS file path in the `conversionEventProviders.config.js` webpack partial added in #8531
* [x] Ensure `yield conversionEventProviders( mode );` is run in the main `webpack.config.js` config (it is commented out while there are no entry points)
* [x] Include the plugin name and class path to the array of main `Conversion_Events` class property added in #8528

### Test Coverage

* You can add basic test coverage for CF7 class, testing that `get_event_names` method returns correct event names, and `register_script` returns script instance with proper handle. Also `is_active` method can be confirmed by defining the plugin constant

## QA Brief

* Install an extension for your browser that lets you track Analytics events
* Enable the `conversionInfra` feature flag for your site
* Setup `Analytics` or `Ads` module, or both
* Install and activate the contact form 7 plugin
* Create a new form, add it to a page and open that page on the frontend
* Submit the form and ensure that the appropriate event is tracked

## Changelog entry

* Add conversion infrastructure for Contact Form 7.

**Comment by eugene-manuilov** [comment]
@zutigrm, here we need to use more specific AC. Instead of just using a generic text, we need to say which events we expect to be tracked. We can use something like this:
```
* Conversion events from Contact Form 7 should be tracked and supported by our infrastructure:
  * A new event "contact" is tracked when a user submits the CF7 form.
```

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
@wpdarren I tried to test this but I'm getting error when trying to send messages through contact form 7. I searched for the error and find out that this is related to SMTP configuration. I tried to fix this using WP SMTP plugin but it did not work for me. Also, reached out to InstaWP support and they also don't have any solution for it. I think Contact Form 7 will work fine on your live sites. So, can you please check and verify this ticket if Contact Form 7 works fine on your live site. 

Assigning this ticket to your for now.

**Comment by wpdarren** [comment]
@mohitwp do you see the same issue with TasteWP?

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Conversion events from Contact Form 7 are tracked and supported by our infrastructure. When form built by Contact For 7 is submitted, a `contact `conversion event should be tracked.

![image](https://github.com/google/site-kit-wp/assets/73545194/d30a86db-896e-4e37-b68b-709dd57ea798)
