### ISSUE TITLE
Implement the secondary user variants of the "no audiences" banner.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8577]
## Feature Description

Show the secondary user variants of the "no audiences" banner.

~~See [secondary user setup > no audiences](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.rgbjg9iot5sc) in the design doc.~~  
See [Changes during engineering](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.u1t2vz880apz), 6 Sept 2024 in the design doc.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Given that a view-only user is on the dashboard, the Audience Segmentation feature has been set up by an authenticated user, and the secondary user setup (see #8130) has run for the view-only user:
  - If the view-only user has an empty audience selection:
    - The "no audiences" banner (see https://github.com/google/site-kit-wp/issues/8155) should be displayed with the following copy:
      - _You don't have any visitor groups selected. [Select groups]()._
    - The _select groups_ link button should open the Selection Panel.
  - If the view-only user has a populated audience selection, but none of their selected audiences are present in the list of available audiences:
    - The "no audiences" banner should be displayed with the following copy:
      - _It looks like your visitor groups aren’t available anymore. [Select other groups]()._
    - The _select other groups_ link button should open the Selection Panel.
- Given that an authenticated user is on the dashboard, the Audience Segmentation feature has already been set up by another user, and the secondary user setup has run for the current user:
  - If the current user has an empty audience selection, and has _never_ had any audiences selected, the "no audiences" banner should be displayed in the following variant:
    - The variant should follow this [Figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2638-32739&t=pPU3ADnVg66YVvWO-0) with the following copy:
      - _You don't have any visitor groups selected. [Select groups]()._
      - _You can deactivate this widget in [Settings]()._
- The banner variants should follow this [Figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1399-11796&node-type=TEXT&m=dev), with different versions of the copy as specified above.
- The second banner variant specced in https://github.com/google/site-kit-wp/issues/8155 should be removed, as the scenario where there are no audiences available to select is not expected to be reachable. This is because it's not possible to archive the "All Users" default audience, so there should always be at least one item in the list of available audiences.

## Implementation Brief

- [ ] In `includes/Core/User/Audience_Settings.php`, add a setting `didSetAudiences` and default it to `false`.
  - [ ] In `merge` method when the `configuredAudiences` is set to array with at least one audience in it and `didSetAudiences` is false, set `didSetAudiences` to true. The value of `didSetAudiences` should never change once it is set to `true`.
- [ ] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/NoAudienceBannerWidget/NoAudienceBanner.js`.
  - [ ] This component already has the examples for _Analytics_ and _Select other groups_ links.
  - [ ] Set `isViewOnly` from the `useViewOnly()` hook.
  - [ ] Set `hasAudienceSelection` using `getConfiguredAudiences` selector. `true` if `getConfiguredAudiences().length > 0` else `false`.
  - [ ] Set `hasAvailableAudiences` using `getAvailableAudiences` selector. `true` if `getAvailableAudiences().length > 0` else `false`.
  - [ ] If `isViewOnly && ! hasAudienceSelection && ! hasAvailableAudiences`, show the following variant:  
  _There are no visitor groups available. Learn more about how to group site visitors in [Analytics]()._  
  _You can [temporarily hide]() this feature until groups are available._  
  - [ ] If `isViewOnly && hasAudienceSelection`:
    - [ ] If `hasAvailableAudiences`, show the following variant:  
      _It looks like your visitor groups aren’t available anymore. [Select other groups]()._  
    - [ ] If `! hasAvailableAudiences`, show the following variant:  
      _There are no visitor groups available. Learn more about how to group site visitors in [Analytics]()._  
      _You can [temporarily hide]() this feature until groups are available._  
  - [ ] If `! isViewOnly && ! hasAvailableAudiences && ! didSetAudiences`, show the following variant:  
    _There are no visitor groups available. Learn more about how to group site visitors in [Analytics]()._  
    _You can deactivate this widget in [Settings]()._  
- [ ] Refer to existing banner variants in `NoAudienceBanner` for examples of the _Analytics_, _Select other groups_ and _Settings_ links.
- [ ] The _Temporarily hide_ link should use the dismiss item infrastructure to hide the banner, with an item key of `audience-segmentation-no-audiences-banner`. (Refer to the `dismissItem` action [here](https://github.com/google/site-kit-wp/blob/2a6f107c6e6069a0499c30e12d5b640ffaa82a97/assets/js/googlesitekit/datastore/user/dismissed-items.js#L88-L104)).
- [ ] When [registering the widget area](https://github.com/google/site-kit-wp/blob/1b4b812cffff622ccc0e98c14887418580568d23/assets/js/googlesitekit/widgets/register-defaults.js#L148-L162) provide [`filterActiveWidgets()` callback](https://github.com/google/site-kit-wp/blob/1b4b812cffff622ccc0e98c14887418580568d23/assets/js/googlesitekit/widgets/datastore/areas.js#L95).
  - [ ] The callback should check if the banner is dismissed.
  - [ ] If available audiences are available, clear the dismissed item because we would show the banner.
  - [ ] If banner is dismissed and there are no available audiences, return an empty array to hide the widget area.

### Test coverage

- Update tests for `NoAudienceBannerWidget` with empty available audiences, available audiences and based on combination of values for `didSetAudiences` setting.

### View-only user with an empty audience selection

- Set up Site Kit with the `audienceSegmentation` feature flag enabled, and click on **Enable groups** to set the feature up.
- In the Analytics UI, archive all of the audiences for the connected property barring "All Users", which can't be archived.
- Refresh the page and open the Audience Selection Panel, this will trigger a resync of the available audiences.
- Share Analytics via the Dashboard Sharing modal.
- Login as an unauthenticated user who has view-only access to Analytics.
- The banner should appear as per the AC.

### View-only user with an populated audience selection

- Set up Site Kit with the `audienceSegmentation` feature flag enabled, and click on **Enable groups** to set the feature up.
- Share Analytics via the Dashboard Sharing modal.
- Login as an unauthenticated user who has view-only access to Analytics and verify that they have an audience selection. You might want to do this in a separate/incognito browser window for convenience.
- Archive all of the audiences for the connected property barring "All Users".
- As the initial admin user, refresh the page and open the Audience Selection Panel to trigger a resync of the available audiences.
- As the unauthenticated user, refresh the page. The banner should appear as per the AC.

### Secondary admin who's never had audiences selected

- Set up Site Kit with the `audienceSegmentation` feature flag enabled, and click on **Enable groups** to set the feature up.
- Archive all of the audiences for the connected property barring "All Users".
- Login as a second admin user and connect Site Kit. The second admin should have view access or higher for the connected property.
- The banner should appear as per the AC.

## Changelog entry

* Implement the Audience Segmentation "no audiences" banner variants for secondary authenticated and shared dashboard users.

**Comment by techanvil** [comment]
Hey @kuasha420, just letting you know I've picked this one up to add the AC.

**Comment by techanvil** [comment]
Hi @ankitrox, thanks for drafting this IB.

However, while reading it I realise that the AC were a bit misleading, this is my mistake and I do apologise for the confusion.

The AC used phrases like "if the view-only user _has not yet set up the feature_", which I was using as a bit of a shorthand for having not _fully_ set up the feature to the point of having an audience selection. I realise though it was a bit confusing because really, we do want the secondary user setup to have completed before determining which variant of the banner to display.

It looks like this has manifested in your IB where for example you specify checking for `configuredAudiences` to be `null`, which is a condition that should only be true _before_ the secondary user setup has run.

I've modified the AC to be more clear on these points. Please can you take a look at the changes and update the IB accordingly?

**Comment by techanvil** [comment]
Hi @ankitrox, thanks for updating the IB. However, there are a few issues with it. One of which is the `secondaryUserSetupRan` flag, I know we discussed setting a flag in the secondary user setup, however the flag we need should be an indicator of whether the user has had a populated audience selection rather than simply whether the secondary setup has run. In fact, we should set this independently of the secondary user setup, and setting it can instead be encapsulated within `Audience_Settings`.

Furthermore, we don't need to bail out of the `NoAudienceBanner` if `secondaryUserSetupRan` is `false` because we still need to show the no audience banner variants for the primary admin. Anyhow as mentioned we don't actually need `secondaryUserSetupRan` and should create a different flag which we can name `hasSeenAudience` (or something along those lines).

Essentially the conditions for showing the specced banner variants should boil down to the following:

- Add a new setting to `Audience_Settings` called `hasSeenAudience`. Set this to `true` the first time the `configuredAudiences` setting is populated with at least one audience.
- In `NoAudienceBanner`:
  - Set `isViewOnly` from the `useViewOnly()` hook.
  - Set `hasAudienceSelection` = `getConfiguredAudiences().length > 0`.
  - Set `hasAvailableAudiences` = `getAvailableAudiences().length > 0`.
  - If `isViewOnly && ! hasAudienceSelection && ! hasAvailableAudiences`, show the following variant:
    - _There are no visitor groups available. Learn more about how to group site visitors in [Analytics]()._  
      _You can [temporarily hide]() this feature until groups are available._
  - If `isViewOnly && hasAudienceSelection`:
    - If `hasAvailableAudiences`, show the following variant:
      - _It looks like your visitor groups aren’t available anymore. [Select other groups]()._
    - If `! hasAvailableAudiences`, show the following variant:
      - _It looks like your visitor groups aren’t available anymore. Learn more about how to group site visitors in [Analytics]()._  
        _You can [temporarily hide]() this feature until groups are available._
  - If `! isViewOnly && ! hasAvailableAudiences && ! hasSeenAudience`, show the following variant:
    - _There are no visitor groups available. Learn more about how to group site visitors in [Analytics]()._  
      _You can [temporarily hide]() this feature until groups are available._

Obviously, with the "temporarily hide" behaviour to be fleshed out.

One more thing, we try to avoid including code blocks in IBs, the IB should be a higher level description describing the approach to implementation rather than including blocks of code. Of course there are always exceptions to be made, but I don't think this case requires the code blocks.

Please can you update the IB again taking the above into account?

**Comment by ankitrox** [comment]
Thank you @techanvil .

I've updated the IB. I kept the setting name as `didSetAudiences` as it sounds more relevant. Rest of the points updated as per your comment and AC conditions.

**Comment by techanvil** [comment]
Thanks @ankitrox. There are a few things that still need to be addressed.

- It would be worth mentioning that the existing banner variants in `NoAudienceBanner` have examples to follow for the _Analytics_ and _Select other groups_ links.
- The "temporarily hide" behaviour still needs to be covered in the IB.
- Also, the formatting for the IB is a bit off, please take a look at that.

**Comment by ankitrox** [comment]
@techanvil Thank you for spotting these points. I've updated them and sending it your way for one more review.

Thanks.

**Comment by techanvil** [comment]
Thanks @ankitrox. A few more points on this:

- A couple of minor ones - `includes/Modules/Analytics_4/Audience_Settings.php` has now moved to `includes/Core/User/Audience_Settings.php`, and although the formatting is improved there are oddities with a `\` at the end of some lines. Maybe you were looking for the trailing double space or `<br />` for a line break?
- More substantially, the "temporarily hide" behaviour needs a bit more thought. The AC specifies that the Audiences Widget Area should remain hidden until the audiences have been resynced, but the IB specifies the _banner_ should be hidden and then reshown. The implication is that we should check for the dismissed state at a higher level than the banner, as it should apply to the whole widget area. We'll also need to resync the audiences in the background (throttled at the usual rate) if the item is dismissed. I think we can achieve this by providing a [`filterActiveWidgets()` callback](https://github.com/google/site-kit-wp/blob/1b4b812cffff622ccc0e98c14887418580568d23/assets/js/googlesitekit/widgets/datastore/areas.js#L95) when [registering the widget area](https://github.com/google/site-kit-wp/blob/1b4b812cffff622ccc0e98c14887418580568d23/assets/js/googlesitekit/widgets/register-defaults.js#L148-L162). The callback can check for the dismissed item, and clear it if there are audiences available. If it's set and there are no audiences available then dispatch `maybeSyncAvailableAudiences()` and return an empty array to hide the widget area. Please review this, see what you think and update the IB accordingly. Of course, let me know if this needs any further clarification, I'd be happy to jump on a call to discuss it further.

**Comment by ankitrox** [comment]
Thank you @techanvil , those points looks very thoughtful. I've made the changes in IB so that we can use `filterActiveWidgets` callback.

**Comment by techanvil** [comment]
Thanks @ankitrox! That's looking good. Please note, I've added one point to the IB that was previously missed from this feedback point:

> It would be worth mentioning that the existing banner variants in `NoAudienceBanner` have examples to follow for the _Analytics_ and _Select other groups links_.

IB :white_check_mark:

**Comment by techanvil** [comment]
Hey @ankitrox, I realised there was another AC issue whereby the authenticated user variant was incorrectly specced to have the _temporarily hide_ button, whereas in fact it should show a _Settings_ link as per this [version in Figma](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2638-32739&t=pPU3ADnVg66YVvWO-0).

I've updated the AC and also restored the criteria for temporarily hidden audiences to remain hidden until an _authenticated_ user has resynced the audiences. This will align this issue with forthcoming changes to remove the ability to sync audiences from view-only users. I've also tweaked the IB accordingly.

**Comment by techanvil** [comment]
Whooops, I picked this one up for execution without realising it's not in the current sprint.

I've hardly spent any time on it, will leave it assigned in the EB to continue but someone else can pick it up if needs be.

**Comment by techanvil** [comment]
While working on the execution for this issue, I realised that part of the AC as it stood didn't match up with the GA4 Audiences behaviour. The scenarios where the list of available audiences is empty are not expected to be reachable, due to the fact that the "All Users" default audience cannot be archived, so there will always be at least one audience which the user can select.

This is something that came up previously, as discussed here: https://github.com/google/site-kit-wp/issues/8155#issuecomment-2242787429. At the time we decided to keep a minor edge case to support the unexpected scenario.

However, reviewing this again and re-verifying the Analytics behaviour w/re the "All Users" audience, it doesn't seem worth including support for this scenario which we cannot replicate through any expected behaviour. It would add unnecessary complexity to the code and to testing in various forms.

I have therefore amended the AC to remove the proposed banner variants for the "no available audience" scenarios, including the ability to temporarily hide the banner until audiences are available which is obviously no longer relevant.

There are still possible variants where the user has not previously had a populated audience selection and I've updated the copy for these as follows: _You don't have any visitor groups selected. [Select groups](https://github.com/google/site-kit-wp/issues/8577)._ This should suffice to move this issue forward, but I'll check in with @sigal-teller to get her thoughts on this copy amendment, if we want to change it we can in a small followup issue.

**Comment by techanvil** [comment]
Update: I've asked Sigal for her thoughts in a [comment on Figma](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH?node-id=1509-26878&m=dev#939929619).

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

@techanvil , referring to the third section of the QAB:
```
Secondary admin who's never had audiences selected
   - Set up Site Kit with the audienceSegmentation feature flag enabled, and click on Enable groups to set the feature up.
   - Archive all of the audiences for the connected property barring "All Users".
   - Login as a second admin user and connect Site Kit.
   - The banner should appear as per the AC.
```
- I followed the steps but at the last step, I get the 'Insufficient permissions' banner instead. ⚠️ 
- Or I am thinking maybe the second admin should be granted access the analytics property for this testing? Can you confirm?

Video attached below for reference:
<Details>

https://github.com/user-attachments/assets/fd786e12-affa-40b1-850e-9c9c242f811c


</Details>

_______________________

Other than that, the first 2 scenarios were tested good: 
- **View-only user with an empty audience selection** ✅ 
   <Details>
   

   https://github.com/user-attachments/assets/3b1a4251-1396-4511-9932-cba86b0e4ad4


   </Details>
   
- **View-only user with an populated audience selection** ✅ 
   <Details>
   

   https://github.com/user-attachments/assets/8b0a08c6-bd81-4550-aeff-e2e06b981e80



   </Details>

**Comment by techanvil** [comment]
Hi @kelvinballoo, yes, sorry for not being more explicit but the second admin should indeed be able to see the connected property. I've updated the AC to make that clear.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Thanks for confirming @techanvil 

After granting the analytics property access, the correct banner is showing up as per below details ✅ 
   <Details>
   
   <img width="988" alt="Screenshot 2024-09-17 at 13 57 15" src="https://github.com/user-attachments/assets/7562ecd5-cd7a-4102-9167-35fe6d13bb8c">
   
   

   https://github.com/user-attachments/assets/7c0c51af-72ba-4efd-aed3-4c1ec46edc5f

   
   </Details>

- ⚠️  My only flag (and this is understandably out of scope for this task but worth raising if it's being tackled under another ticket or it needs one), is that when we click on 'Settings' to deactivate this widget, it brings up the 'Enable groups' button. By right, I would expect the toggle only at this point so that it can be turned on and off.  You may refer to the 1m40 mark on the video above.

**Comment by techanvil** [comment]
Hi @kelvinballoo, thanks for spotting that. As you've surmised, it's out of scope for this issue, but is not addressed by another issue so please can you raise one for it?

**Comment by techanvil** [comment]
Thanks @kelvinballoo!
