### ISSUE TITLE
Site Kit Creates Blog Issue

### ISSUE THREAD

**Issue by dgoodenstandard** [google/site-kit-wp#858]
## Steps to reproduce

1. activate site kit
2. Add new post to begin writing a blog
3. Scroll down to seo section

## Additional Context

 - PHP Version: 
 - OS: [windows 10]
 - Browser [chrome]
 - Plugin Version [e.g. 22]
 - Device: [HP Laptop]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ernee** [comment]
@dgoodenstandard thanks for reaching out. Site Kit support has moved to the [WordPress Support Forums](https://wordpress.org/support/plugin/google-site-kit/). Please post a new topic there so we can help you further. Thanks!
