### ISSUE TITLE
Implement Hover States for Action Buttons on the Authorize Application Screen

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8584]
## Feature Description

As part of enhancing the Authorize Application screen, this issue focuses on implementing the hover states for the primary and secondary action buttons.

* **Primary Action Button:** This button will have a hover effect, which aligns with the Google service design theme and clearly indicates interactivity.
* **Secondary Action Button:** The secondary button will also feature a hover state, subtly distinct from its normal appearance to enhance user interaction.

**Note:** We are awaiting the finalized hover state designs from the design team. Once provided, these designs will guide the specific CSS implementations needed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **Primary Action Button Hover State:**
   * The hover state background color for the primary action button should match the [Figma design](https://www.figma.com/design/ntKPstnmguKI70A6xUJQVi/Application-Passwords?node-id=413-18549&m=dev).
   * The hover effect should use a semi-transparent overlay color with 8% opacity as indicated in the Figma design.
* **Primary Action Button Focus State:**
   * The focus state background color for the primary action button should match the design specified in the [Figma link](https://www.figma.com/design/ntKPstnmguKI70A6xUJQVi/Application-Passwords?node-id=413-18565&m=dev).
   * The focus effect should use a semi-transparent overlay color with 12% opacity as indicated in the Figma design.
* **Secondary Action Button Hover State:**
   * The hover state background color for the secondary action button should match the design specified in the [Figma link](https://www.figma.com/design/ntKPstnmguKI70A6xUJQVi/Application-Passwords?node-id=413-18485&m=dev).
   * The hover effect should use a semi-transparent overlay color with 8% opacity as indicated in the Figma design.
* **Secondary Action Button Focus State:**
   * The focus state background color for the secondary action button should match the design specified in the [Figma link](https://www.figma.com/design/ntKPstnmguKI70A6xUJQVi/Application-Passwords?node-id=413-18497&m=dev).
   * The focus effect should use a semi-transparent overlay color with 12% opacity as indicated in the Figma design.
   * The border color should change to `#0B57D0`.

## Implementation Brief

In `assets/sass/authorize-application/_googlesitekit-authorize-application.scss`:

* **Primary Action Button Hover State (`#approve:hover`):**
   * Apply a box shadow with an 8% opacity white overlay: `box-shadow: 0 0 0 1000px rgba(255, 255, 255, 0.08) inset`
* **Primary Action Button Focus State (`#approve:focus`):**
   * Apply a box shadow with a 12% opacity white overlay: `box-shadow: 0 0 0 1000px rgba(255, 255, 255, 0.12) inset`
* **Secondary Action Button Hover State (`#reject:hover`):**
   * Apply a box shadow with an 8% opacity primary color overlay: `box-shadow: 0 0 0 1000px rgba(11, 87, 208, 0.08) inset`
* **Secondary Action Button Focus State (`#reject:focus`):**
   * Change the border color to the primary outline color.
   * Apply a box shadow with a 12% opacity primary color overlay: `box-shadow: 0 0 0 1000px rgba(11, 87, 208, 0.12) inset`

### Test Coverage

* No new tests are required for this change.

## QA Brief

* Navigate to the following URL on your WordPress site, replacing `example.com` with your actual site domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify the hover and focus styles defined in AC and IB.

## Changelog entry

* Improve Authorize Application screen action button styling.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Tested this and most of the items are good except the border colour for the 2nd button in focus state.
It's documented further down.

- **Primary Action Button Hover State (#approve:hover):**
A box shadow with an 8% opacity white overlay: box-shadow: 0 0 0 1000px rgba(255, 255, 255, 0.08) inset is applied
   <Details>
   <img width="1116" alt="Screenshot 2024-07-16 at 17 07 16" src="https://github.com/user-attachments/assets/e420c0fe-2e7d-40ff-80cd-d6e612e5317c">
   </Details>

- **Primary Action Button Focus State (#approve:focus):**
A box shadow with a 12% opacity white overlay: box-shadow: 0 0 0 1000px rgba(255, 255, 255, 0.12) inset is applied

   <Details> 
   <img width="1106" alt="Screenshot 2024-07-16 at 17 07 55" src="https://github.com/user-attachments/assets/93e3215f-1422-4d39-8093-ce4a01693500">

   </Details>

- **Secondary Action Button Hover State (#reject:hover):**
A box shadow with an 8% opacity primary color overlay: box-shadow: 0 0 0 1000px rgba(11, 87, 208, 0.08) inset is applied
   <Details>
   
   <img width="1261" alt="Screenshot 2024-07-16 at 17 11 23" src="https://github.com/user-attachments/assets/f2a6026b-8a66-4e70-b44e-45399fa554b3">

   </Details>

- Secondary Action Button Focus State (#reject:focus):
   A box shadow with a 12% opacity primary color overlay: box-shadow: 0 0 0 1000px rgba(11, 87, 208, 0.12) inset is applied.
   <Details>
   <img width="1263" alt="Screenshot 2024-07-16 at 17 12 37" src="https://github.com/user-attachments/assets/8ca2342b-d8ee-435c-9de7-0e67459ca359">

   </Details>
   
   However, the border color did not change. It remains as grey (#747775;). I am expecting it to be blue under focus state. ⚠️ 
   <Details>
   <img width="1106" alt="Screenshot 2024-07-16 at 17 13 24" src="https://github.com/user-attachments/assets/7e13702d-ef77-4cad-8eb2-8cae9c477b94">

   </Details>

**Comment by hussain-t** [comment]
Hi @kuasha420, applying the following CSS styles to `#reject:focus` will resolve the reported issue:

```scss
border: 1px solid $c-authorize-application-sys-light-primary;
```

**Comment by techanvil** [comment]
Back to you for another pass, @kelvinballoo!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this and it's looking good.

- **Primary Action Button Hover State (#approve:hover):** ✅ 
A box shadow with an 8% opacity white overlay: box-shadow: 0 0 0 1000px rgba(255, 255, 255, 0.08) inset is applied
   <Details>
   <img width="1116" alt="Screenshot 2024-07-16 at 17 07 16" src="https://github.com/user-attachments/assets/e420c0fe-2e7d-40ff-80cd-d6e612e5317c">
   </Details>

- **Primary Action Button Focus State (#approve:focus):** ✅ 
A box shadow with a 12% opacity white overlay: box-shadow: 0 0 0 1000px rgba(255, 255, 255, 0.12) inset is applied

   <Details> 
   <img width="1106" alt="Screenshot 2024-07-16 at 17 07 55" src="https://github.com/user-attachments/assets/93e3215f-1422-4d39-8093-ce4a01693500">

   </Details>

- **Secondary Action Button Hover State (#reject:hover):** ✅ 
A box shadow with an 8% opacity primary color overlay: box-shadow: 0 0 0 1000px rgba(11, 87, 208, 0.08) inset is applied
   <Details>
   
   <img width="1261" alt="Screenshot 2024-07-16 at 17 11 23" src="https://github.com/user-attachments/assets/f2a6026b-8a66-4e70-b44e-45399fa554b3">

   </Details>

- **Secondary Action Button Focus State (#reject:focus):** ✅ 
   A box shadow with a 12% opacity primary color overlay: box-shadow: 0 0 0 1000px rgba(11, 87, 208, 0.12) inset is applied.
   The border colour changed as well to #0B57D0.
   <Details>
   <img width="1056" alt="Screenshot 2024-07-22 at 20 48 40" src="https://github.com/user-attachments/assets/6aa02739-1a41-42ab-b811-58bbb70c5644">

   </Details>
   

Moving ticket to approval.
