### ISSUE TITLE
Update Link Colors in the Authorize Application Screen for Consistency

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8585]
## Feature Description

This issue focuses on updating the link colors on the Authorize Application screen to ensure visual consistency.  Special attention must be paid to all hyperlinks, including conditional links such as the "Get Version x.x.x" link in the footer when a WordPress update is available. For more context, refer to @techanvil's [comment](https://github.com/google/site-kit-wp/issues/8524#issuecomment-2063477002).

![Screenshot 2024-04-18 at 8 02 34 PM](https://github.com/google/site-kit-wp/assets/24408261/0cf780dd-cded-4c4e-94c6-24eb3e7313df)

**Note:** Approval for these color updates is still pending from the design team. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **Link Color Update**:
    * All hyperlinks within `#wpcontent` and `#wpfooter` on the Authorize Application screen must be updated to `#1A73E8` (vivid-blue) to ensure visual consistency.
    * This update should be applied to all the links within the Authorize Application content area. For example, the "Get Version x.x.x" link in the footer when a WordPress update is available and the standard WordPress update notice: "WordPress x.x.x is available! Please update now."

## Implementation Brief

In `assets/sass/authorize-application/_googlesitekit-authorize-application.scss`:

* [x] Apply the `$c-authorize-application-vivid-blue` variable (`#1A73E8`) to the `color` property of all `a` elements within the `#wpbody-content` and `#wpfooter` areas.

### Test Coverage

* No new tests are required for this change.

## QA Brief

* Enable the application password for the site. If it is a local site, it can be enabled by setting `WP_ENVIRONMENT_TYPE` variable in wp-config.php file as 

```php
define( 'WP_ENVIRONMENT_TYPE', 'local' );
```

* Visit the authorize application page using this path

```
wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fpublishers.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```

* All the links on the page should have the color `#1a73e8`

## Changelog entry

* Improve link color consistency in the Authorize Application screen.

**Comment by ivonac4** [comment]
@hussain-t this issue is missing a priority. Since it is just a color change, should it be P2?
Usually we would assign the same priority as epic (P0), but after the main 5 issues for this epic, all other issues can be treated as "enhancement" issues. Changing color wouldn't be a P0, so we want to avoid that confusion.

**Comment by hussain-t** [comment]
@ivonac4, `p2` should be good.

**Comment by aaemnnosttv** [comment]
@hussain-t I'm not sure we should really style all the notices on the page, as this would really require going farther than just links to look consistent as there are other colors such as the various accent colors for each type.

Let's connect with @sigal-teller about what to do here. We don't have these notices on normal SK screens, but this isn't a core screen so we definitely shouldn't hide/remove them the way we do.

**Comment by hussain-t** [comment]
Hi @aaemnnosttv, to clarify, this is not about styling any specific notices. I've provided an example of that notice, which contains links. The fix should apply to links within the `#wpcontent` and `#wpfooter` sections. I'll update the AC if it's not clear.

**Comment by aaemnnosttv** [comment]
Thanks @hussain-t – given the simplicity of the change here, I think we can reduce this to a 3 which should still be more than enough for everything 👍 

IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

- All the hyperlinks in #wpcontent and #wpfooter on the Authorize Application screen have the color #1a73e8
- Other sections of the BE would maintain the default colour of #3858E9

Moving this ticket to Approval

<Details>

**Authorize Application Screen have colour #1a73e8:**

<img width="892" alt="Screenshot 2024-06-05 at 15 25 34" src="https://github.com/google/site-kit-wp/assets/125576926/cb59eeea-c3ce-49cf-bc82-4d862cf64dab">
<img width="821" alt="Screenshot 2024-06-05 at 15 25 43" src="https://github.com/google/site-kit-wp/assets/125576926/5d5c8f63-a1e9-42cc-a7bb-53100e563116">
<img width="636" alt="Screenshot 2024-06-05 at 15 26 12" src="https://github.com/google/site-kit-wp/assets/125576926/d4b8f89b-573e-43ea-bc67-1f234bf3b850">
<img width="364" alt="Screenshot 2024-06-05 at 15 26 17" src="https://github.com/google/site-kit-wp/assets/125576926/0113edc9-4fe8-4f20-a2b5-bd2143ba3818">

**Other sections would have colour of #3858E9:**
<img width="588" alt="Screenshot 2024-06-05 at 15 30 39" src="https://github.com/google/site-kit-wp/assets/125576926/50a8cc6e-65a6-453c-bcdf-65e49cbe59ae">
<img width="1156" alt="Screenshot 2024-06-05 at 15 30 47" src="https://github.com/google/site-kit-wp/assets/125576926/c937e1db-4176-49c4-8ad9-0cb85fff3905">


</Details>
