### ISSUE TITLE
Modules fixtures out of sync

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8586]
## Feature Description

Since recently adding a new module, I realized our main internal fixture for testing is out of sync with what is expected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `modules/datastore/__fixtures__/list.json` should be updated to return the default state of our `core/modules/data/list` endpoint, for an unconfigured site

## Implementation Brief

* [ ] Starting with #8587, update the modules fixtures so it passes unit tests and reflects the default state of the `core/modules/data/list` REST endpoint in use

### Test Coverage

* No changes in coverage expected

## QA Brief

* I added a QA:Eng label since there is nothing for QA to do. But there is nothing much for QA:Eng to do either, so it can be tested (verifying JS tests are passing) during CR/MR and moved straight to the approval I guess

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Bumping this estimate to cover unknowns in the fixes as some tests need adjusting because the fixture data is wrong.

IB ✅

**Comment by eugene-manuilov** [comment]
Moved to Approval since there is nothing to test.
