### ISSUE TITLE
GTM edit screen stuck in a continuous loading screen if the admin doesn't have access to the connected property

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#8596]
## Bug Description

If the administrator who initially sets up Site Kit doesn't have access to the GTM property that another admin connected, the edit screen continuously loads

![image](https://github.com/google/site-kit-wp/assets/41326532/5ff3b658-f868-4589-9d5f-74969f3da642)

## Steps to reproduce

1. Set up SK on a site (admin1)
2. Logout of wp-admin
3. Login to wp-admin using another administrator account (admin2)
4. Connect Tag Manager but use a different Google account. Be sure to select a GTM account or property that other admins don't have access to
5. Logout of wp-admin 
6. Login back into wp-admin, this time using the original admin account that set up the plugin (admin1)
7. Try to edit the GTM module (Settings > Connected Services > GTM > Edit)
8. The screen continuously loads

## Additional Context

 - SK 1.125.0
 - See also #8597 (related)
 - There were some similar reports of this continuous loading screen for GTM before (see https://github.com/google/site-kit-wp/issues/6464)

The relevant infra was added in #5144 and seems as though it may never have been tested with the secondary admin case (user without access) but only with access. See https://github.com/google/site-kit-wp/issues/5144#issuecomment-1148461101

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A non-owner admin should be able to see the settings edit view of the Tag Manager module regardless of their access to the connected container(s). If the user does not have access however, they should see the read-only state as shown below
<img width="1137" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/00398c38-60c6-4109-b50d-b0f200574fa0">

## Implementation Brief

* [x] Update the error code for the condition in `Tag_Manager::check_service_entity_access` to use `404` instead of `403` which is the error code returned for `listAccountsContainers( "accounts/{account_id}" )` with an account the user does not have access to. This error is returned unless the user has access to at least one container in the account. Remaining logic which compares the container IDs should handle the rest

### Test Coverage

* Update `Tag_ManagerTest` accordingly

## QA Brief

* In addition to testing the Steps to reproduce, test the entire set up of GTM, including creating a new account/container, editing and saving settings and connecting/disconnecting the module.

## Changelog entry

* Fix the GTM edit screen stuck issue when the user doesn't have access to the connected property.

**Comment by tofumatt** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
@jimmymadon could you please add QAB?

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that issue is resolve now and a non-owner admin is able to see the settings edit view of the Tag Manager module regardless of their access to the connected container(s). If the user does not have access however, they see the read-only state.
- Also, verified complete setup, creation of a/c , container, disconnect module and edit settings flow of the tag manager.


<details>

Read only state

![image](https://github.com/google/site-kit-wp/assets/94359491/d753b26d-2600-4b45-9a9a-7210931a4e96)


https://github.com/google/site-kit-wp/assets/94359491/659b8372-1ab2-406e-a9cc-47de12d773c5

</details>
