### ISSUE TITLE
Switching tabs in settings should cancel current editing in Connected Services

### ISSUE THREAD

**Issue by lucymtc** [google/site-kit-wp#86]
## Bug Description

When user is editing settings of a module in Settings > Connected Services sections are blocked. When switching to "Connect More Services" the section in this tab is also locked. 
User needs to go back to "Connected Services" and cancel the editing. This does not happen when switching to "Admin Settings", current editing is canceled automatically.

## Steps to reproduce

1. Go to Settings > Connected Services. 
2. Click on any module that has Edit link (i.e  Analytics)
3. Without clicking "Cancel", switch tab to "Connect More Services"
4. See "Section locked while editing"
5. Go back to "Connected Services" to cancel editing.
6. Does not happen when switching from "Connected Services" tab to "Admin Settings" tab.

## Expected behavior

When user switches from  "Connected Services" to "Connect More Services" in settings page, the editing happening in "Connected Services" should be canceled and section in Connect mode services shouldn't be locked.

Possibly as an enhancement, while switching to any other tab when Editing is happening and user has made changes without saving, user should be warned that any changes made will be lost.

## Screenshots

<img width="1469" alt="Screen Shot 2019-06-30 at 08 14 17" src="https://user-images.githubusercontent.com/1204359/60393030-1c1d2e80-9b0f-11e9-9eda-65a6de4e6ed9.png">

## Additional Context

 - PHP Version: 7.1
 - OS: mac
 - Browser: chrome (all)
 - Plugin Version: Developer beta
 - Device: macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by felixarntz** [comment]
This has been already addressed as part of refactoring the settings screen and should no longer be an issue.
