### ISSUE TITLE
Add `Conversion_Tracking_Settings` class

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8612]
## Feature Description

As part of the Initial Conversion Events infrastructure work involving the introduction of an "Enable Conversion Tracking" toggle comes the need to define a decentralised (core/top level) setting that will hold settings values for Conversion Tracking settings, not inherently attached to a single module. This will take the form of a new `Converison_Tracking_Settings` class.

The existing Conversion Tracking infrastructure (located at `includes/Core/Conversion_Tracking/`) must be extended to cater for the settings definition. 

The existing `Conversion_Events` class will be used to register and instantiate this new  `Converison_Tracking_Settings` class.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A settings class is registered within the `Conversion_Tracking` folder
* Said settings class will register a new standalone option against which to store conversion settings
* Said settings class will register said setting type as an object, so multiple settings can be defined for conversion tracking as and when needed
* Said settings class will register a single setting within the settings object that will hold the state of conversion tracking being enabled or not
* Said settings class will make available a simple function to check whether conversion tracking is enabled by checking the existing settings value(s) saved against said settings object

## Implementation Brief

* [x] Add `includes/Core/Conversion_Tracking/Settings.php`
  * Extend `Google\Site_Kit\Core\Storage\Setting` base class
  * You can use `googlesitekit_conversion_tracking` as a setting name
  * Override `get_type` method and return 'object`
  * Override `get_default` method and return an array, with `enabled` key. You can use `false` for a default value
  * Override `get_sanitize_callback` method, and ensure that `enabled` is boolean
  * Add `is_conversion_tracking_enabled` method, and return the `enabled` value from the setting array
  * You can check `includes/Core/Consent_Mode/Consent_Mode_Settings.php` as an idea for implementation
* [x] Update `includes/Core/Conversion_Tracking/Conversion_Tracking.php`
  * Instantiate `Google\Site_Kit\Core\Conversion_Tracking\Settings` in the `__construct`
  * Update `register` method, invoke `register` method on the settings instance

### Test Coverage

* Add basic test coverage for the class. You can see some examples in `tests/phpunit/integration/Core/Consent_Mode/Consent_Mode_SettingsTest.php`

## QA Brief

* Perform a normal regression / smoke test of the plugin as the code here does not currently make any user facing changes. 

## Changelog entry

* Add settings infrastructure for conversion tracking.

**Comment by tofumatt** [comment]
ACs here are good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

Tested on main environment.
Done smoke testing of whole plugin.
Verified setup of all modules.
No issues found in smoke testing.
