### ISSUE TITLE
Add `REST_Conversion_Tracking_Controller` Class

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8613]
## Feature Description

As part of the Initial Conversion Events infrastructure work involving the introduction of an "Enable Conversion Tracking" toggle comes the need to define a new REST controller (in the form of a `REST_Conversion_Tracking_Controller` class) that will define READABLE and UPDATABLE endpoints that in turn will be used to retrieve, create and update Conversion Tracking settings as defined in #8612. These REST routes will also aid in the creation of the necessary datastore on the Javascript side, making it possible to define actions and selectors to handle said settings data from within the main Site Kit application.

The existing Conversion Tracking infrastructure (located at `includes/Core/Conversion_Tracking/`) should be extended to cater for the REST controller class definition. 

The existing `Conversion_Events` class will be used to register and instantiate this new  `REST_Conversion_Tracking_Controller` class.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New REST controller should be added 
* It should handle fetching/saving/updating the Conversion Tracking settings

## Implementation Brief

* [ ] Add `Google\Site_Kit\Core\Conversion_Tracking\REST_Conversion_Tracking_Controller.php`
  * You can use `includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php` as a starting point
  *  Use `includes\Core\Conversion_Tracking\Settings` for setting and getting the options
  * Include `register` method and hook into `googlesitekit_rest_routes` to register new routes and `googlesitekit_apifetch_preload_paths` for retrieving the setting.
  * Define `get_rest_routes` method
    * Add `core/site/data/conversion-tracking` endpoint
      * Add a `READABLE` method that retrieves the settings
      * Add  an `EDITABLE` method that saves the settings, since we only have one setting currently, it is fine to use the settings data from request and invoke `set` method of settings instance directly, overwriting the settings array on both saving and updating.
* [ ] Update main `Conversion_Tracking` class
  * Define new class property that will hold `REST_Conversion_Tracking_Controller` instance and instantiate it in constructor
  *  Update `register` method - invoke `register` method on REST controller instance

### Test Coverage

* Add test coverage for the REST controller class, you can see some examples in `tests/phpunit/integration/Core/Consent_Mode/REST_Consent_Mode_ControllerTest.php`

## QA Brief

* Set up Site Kit and enable the `conversionInfra` feature flag
* While in the Site Kit dashboard or settings screen in admin, perform the following calls in the browser console:
    * `await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );`
        * The result should be the default false enabled state: `{enabled: false}`
    * `await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: true } } );`
        * This should update the enabled setting to be `true`
    * Get the value again using `await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );`
        * It should be `{enabled: true}`
    * Validate that a non boolean value can not be set: `await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: 'foo' } } );`
        * Should result in an error with a 400 bad request status
    * Set the boolean value using integers: `await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: 0 } } );`
        * Call the value again using `await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );`
            * It should again be `false` as 0 is the boolean equivalent: `{enabled: false}`
        * Perform the same using `1`: `await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: 1 } } );`
            * Call the value again using `await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );`
             * It should again be `false` as 0 is the boolean equivalent: `{enabled: false}`

## Changelog entry

* Add REST API routes to the Conversion Tracking class.

**Comment by 10upsimon** [comment]
AC ✅  Moving to IB

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified when `conversionInfra` feature flag is disabled.
- Verified when `conversionInfra` feature flag is enabled.
- Verified calls response are as per QAB.


<details>

> When 'ConversionInfra' feature flag is not enabled.

![image](https://github.com/google/site-kit-wp/assets/94359491/cccf8580-4d7a-4b8e-b273-f4c09ab9af86)


> await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );
> The result should be the default false enabled state: {enabled: false}

![image](https://github.com/google/site-kit-wp/assets/94359491/b72a767e-fb0a-4568-866e-271ece0ef570)

> await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: true } } );
> This should update the enabled setting to be true

![image](https://github.com/google/site-kit-wp/assets/94359491/f43fd7ce-4568-4f8d-aa88-013089cede97)

> Get the value again using await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );
> It should be {enabled: true}

![image](https://github.com/google/site-kit-wp/assets/94359491/f624f957-c173-433a-9235-6a760e5657b6)

> Validate that a non boolean value can not be set: await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: 'foo' } } );
> Should result in an error with a 400 bad request status

![image](https://github.com/google/site-kit-wp/assets/94359491/c3f7da60-338c-41fa-b7b2-d9886b1848af)

> Set the boolean value using integers: await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: 0 } } );

![image](https://github.com/google/site-kit-wp/assets/94359491/05cbad2e-5044-4844-bf31-40ae0862bf2d)

> 
> Call the value again using await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );
> It should again be false as 0 is the boolean equivalent: {enabled: false}

![image](https://github.com/google/site-kit-wp/assets/94359491/8c638e51-e1a1-4c4a-b8d0-15233a186695)

> Perform the same using 1: await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: 1 } } );

![image](https://github.com/google/site-kit-wp/assets/94359491/07c09485-90d6-48b6-917e-e3602cde82bf)


> Call the value again using await googlesitekit.api.get( 'core', 'site', 'conversion-tracking' );
> It should again be true  as 1 is the boolean equivalent: {enabled: true}

![image](https://github.com/google/site-kit-wp/assets/94359491/5a0a63e9-b4c3-4615-9b02-7a2e10c44a64)

</details>

**Comment by aaemnnosttv** [comment]
@10upsimon @tofumatt I left a comment on the PR with a question about the capabilities chosen here which seem off. See https://github.com/google/site-kit-wp/pull/8692/files#r1605582663

Closing this out as working, but let's follow up with an update if needed.
