### ISSUE TITLE
Update `Conversion_Tracking` to register `Conversion_Tracking_Settings` and `REST_Conversion_Tracking_Controller`

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8614]
## Feature Description

Given the completion of the Conversion Tracking settings class (see #8612) and REST controller class (see #8613), the base `Conversion_Tracking` class should be updated to register/instantiate said settings and REST controller classes.

Eg. we should update the existing `Conversion_Tracking` base class to register/instantiate the `Conversion_Tracking_Settings` and `REST_Conversion_Tracking_Controller` classes.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The base Conversion_Tracking class at `includes/core/conversion_tracking/Conversion_Tracking.php` should register/initialise  `Conversion_Tracking_Settings` and `REST_Conversion_Tracking_Controller` instances

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@10upsimon The length of this issue title is making things wonky on the Execution board. 😅 Could we change it to something a bit shorter?

**Comment by tofumatt** [comment]
@bethanylang I've shorted it down a fair bit, let me know if that's okay or if it needs further trimming 😅

**Comment by tofumatt** [comment]
@10upsimon Where should these classes be registered/initiated? Inside the `Conversion_Tracking` instance? It's just not clear from the ACs, and I'd think that part is relevant.

If it isn't, maybe just saw so. I know it's sort of implementation, but I'm not clear on where they belong from the ACs 😅

**Comment by 10upsimon** [comment]
@tofumatt as raised internally, I am a little unclear of what changes you're expecting as the first AC point states clearly where these classes need to be instantiated, within the base `Conversion_Tracking` class at `includes/core/conversion_tracking/Conversion_Tracking.php`

**Comment by zutigrm** [comment]
@10upsimon @tofumatt I don't think we need this issue, since both issues for implementing these two classes already include their instantiation in the main `Conversion_Tracking` class

**Comment by 10upsimon** [comment]
> @10upsimon @tofumatt I don't think we need this issue, since both issues for implementing these two classes already include their instantiation in the main `Conversion_Tracking` class

@zutigrm if that is the case then we can probably close this one out :) cc @tofumatt agreed?

**Comment by tofumatt** [comment]
Actually, I'm reviewing that PR, so I'll revisit this after I review it, should be fine 👍🏻

**Comment by tofumatt** [comment]
These have been added in other issues and are now present in the controller, so this issue can be closed (see: https://github.com/google/site-kit-wp/blob/dc2700ce02cf60d3e2709c1a6e499a1730860b2c/includes/Core/Conversion_Tracking/Conversion_Tracking.php#L77-L78).

👍🏻
