### ISSUE TITLE
Integrate `<ConversionTrackingToggle />` Component Into Ads and GA4 Module `<SettingsView />` Components

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8617]
## Feature Description

With the Conversion Tracking UI toggle component and associated settings/datastore now complete (see #8616), the toggle is ready to be integrated into both the settings area of the Ads module, as well as the GA4 module.

This issue focusses on the read only / view settings area of said modules, i.e the `<SettingsView />` component of each module.

The enabled/disabled status for Conversion Tracking should be displayed in read-only form based on the state of the toggle (i.e if conversion tracking enabled (`true`) via the applicable datastore selector).

Please reference the _"Conversion Event Tracking Toggle & Settings"_ area of the design doc for more detailed information.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SettingsView` component of `Ads` and `Analytics` modules should display the `Conversion tracking` label and value
* Value should be sourced from Conversion Tracking datastore and displayed as `Enabled` or `Disabled` text
* It should match [figma designs](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1181-6385&mode=design&t=cl4K4V42NL8ZlkGi-0) for both modules

## Implementation Brief

* [ ] Update `assets/js/modules/ads/components/settings/SettingsView.js`:
  * Use the selector added in #8615 to pull the conversion tracking enabled setting value
  * Use `DisplaySetting` component to render `Enabled` or `Disabled` text when `adsPax` feature flag is enabled
  * Use `Enhanced conversion tracking` for label
  * Follow the [figma design](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1181-6385&mode=design&t=4wI79a5K8Xe3cFNU-0)
* [ ] Update `assets/js/modules/analytics-4/components/settings/SettingsView.js`
  * Do the same as in Ads module settings view component
  * Follow the [figma design](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1183-7170&mode=design&t=4wI79a5K8Xe3cFNU-0)

### Test Coverage

* Update VRT images

## QA Brief

* Setup Site Kit with `conversionInfra` feature flag
* Configure Ads and GA4
* Go to the Ads setting screen (Site Kit > Settings > Ads) and paste the following snippet into the browser console to enable Conversion tracking: 
    * `await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: true } } );` 
* Reload the page
* Validate that the Enhanced conversion tracking setting label is present with a value of "Enabled" as per the screenshot below:

<img width="398" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/bfea273d-8518-49c8-ba16-e53bf121f6fa">

* Change the setting to be disabled using the following snippet in console: `await googlesitekit.api.set( 'core', 'site', 'conversion-tracking', { settings: { enabled: false } } );`
* Reload the page
* Validate that the Enhanced conversion tracking setting label is present with a value of "Enabled" as per the screenshot below:

<img width="334" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/71a8df38-393d-4b2c-81aa-179066607488">

* Perform the same steps for the GA4 settings view

## Changelog entry

* Add "Enhanced Conversion Tracking" to settings views for Ads and GA4.

**Comment by 10upsimon** [comment]
AC ✅

**Comment by 10upsimon** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Note for QA: I've made a few changes which don't match the designs above but, these were already inconsistent relative to the current state there (mostly for GA). I've left a note in Figma too, so we should mostly be reviewing this visually for consistency with the rest of the settings.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Figma have different design and current is more aligned with existing styles.
- Verified toggled settings for both Analytics and Ads module.
- Verified the `SettingsView` component of Ads and Analytics modules  display the Conversion tracking label and value.
- Verified value are sourced from Conversion Tracking datastore and displayed as Enabled or Disabled text.

<details>

**Ads module**

https://github.com/google/site-kit-wp/assets/94359491/ad8b8f77-a880-4d63-ab84-4d2cbd35a108

https://github.com/google/site-kit-wp/assets/94359491/2020b2fa-ad9d-47f3-9e30-2bbc54036dec

**Analytics module**


https://github.com/google/site-kit-wp/assets/94359491/02b4ae7f-a35d-40e1-b02d-282664b45106

</details>
