### ISSUE TITLE
Create Resolver in Ads Module Datastore to Access Global Ads Module Data for `supportedConversionEvents` Key

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8619]
## Feature Description

As part of the PAX conversion tracking partner service implementation (see GitHub issue #8561), there is a need to retrieve a unique list of event names supported by applicable plugins (if any) to be passed to the PAX application. 

These events are already exposed as global module data as part of the work executed in #8556. An example of this data exposed can be seen [here](https://github.com/google/site-kit-wp/pull/8595/files#diff-cc290e48b5fafffe11bea5a4b66d4a25d4e0a356d78d9a7e92628ef174271eacR153-R155).

A new resolver within the ads module datastore should be created in order to access this data.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new resolver is created within the Ads Module datastore 
    * Said resolver retrieves/resolves it's data via the global module data exposed in #8556 
    * Said data exposure can be seen in more detail [here](https://github.com/google/site-kit-wp/pull/8595/files#diff-cc290e48b5fafffe11bea5a4b66d4a25d4e0a356d78d9a7e92628ef174271eacR153-R155)

## Implementation Brief

* [ ] Add `assets/js/modules/ads/datastore/moduleData.js` datastore partial
  * Include initial state, with property say `supportedConversionEvents` and value of `undefined`
  * [ ] Add resolver - `getModuleData`
    * It should retrieve values from `global._googlesitekitModulesData.?['ads']`
    * Extract `supportedConversionEvents` property and pass it to the `receiveModuleData` action, as a property of an object argument
  * [ ] Include a receiver action, say `receiveModuleData`, which should pass the payload to the reducer. It should accept module data object as an argument. You can refer to the `receiveSiteInfo` for an example.
  * [ ] Add reducer that will handle the passed value and update the state
    * It should accept object as an argument representing the extracted properties from modules data object. Currently we only have `supportedConversionEvents`, but we might add more in the future so it might be good idea to resolve ads module data in one place.
  * [ ] Implement the general helper function for retrieving the state property values, using the passed prop for the property selector, eg. `getModuleDataProperty`, you can use `getSiteInfoProperty` as a guide. And add individual selector for `supportedConversionEvents` state value that will use the `getModuleDataProperty` helper.

### Test Coverage

* Add tests for the `moduleData` data partial and new resolver

## QA Brief (QA:ENG)
- In the PHP logic that defines the supported conversion events in `includes/Modules/Ads.php`:
    - Within the `inline_modules_data` method:
        - Add dummy events to the array, i.e `array('add-to-cart', 'submit-form')`
- In the Ads module `<SettingsView />` component, log some output to the console to ensure that the correct values are being set in the ads moduleData store, i,e:
 ```
 	const testAdsModuleDataStore = useSelect( ( select ) =>
		select( MODULES_ADS ).getSupportedConversionEvents()
	);

	console.log( testAdsModuleDataStore );
 ``` 
- Ensure that the logged events is an array equalling that set in the PHP side
- Inspect the ads moduleData store data and validate that it contains the following property structure:
    - `{ supportedConversionEvents: [ 'add-to-cart', 'submit-form' ] }`
    - This can be achieved with `googlesitekit.data.select('modules/ads').getModuleData();`
- Altering the array in the PHP file above should be reflected in all tests above

## Changelog entry

* Add support for `supportedConversionEvents` in Ads datastore.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by zutigrm** [comment]
#### QA:Eng Verified

Data is correctly resolved from inline data, and stored in state. LGTM ✅
