### ISSUE TITLE
Update Existing `ConversionTrackingService` PAX Partner Service Implementation and Retrieve Event Names Using New Resolver, Pass to PAX Application 

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8620]
## Feature Description

As part of the PAX conversion tracking partner service implementation (see GitHub issue #8561), there is a need to retrieve a unique list of event names supported by applicable plugins (if any) to be passed to the PAX application. 

These events are already exposed as global module data as part of the work executed in #8556. An example of this data exposed can be seen [here](https://github.com/google/site-kit-wp/pull/8595/files#diff-cc290e48b5fafffe11bea5a4b66d4a25d4e0a356d78d9a7e92628ef174271eacR153-R155).

The conversion tracking partner service implementation (#8561) should be expanded upon to access this data (specifically the key `supportedConversionEvents`) via the new resolver added in #8619. This data should be passed to the PAX conversion tracking partner service accordingly.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing implementation of the `ConversionTrackingService` PAX partner service as executed on in #8561 should be extended to utilise the new resolver added in #8619 in order to retrieve event names
* The retrieved event names should be formatted accordingly and passed to the PAX application via existing `ConversionTrackingService` logic

## Implementation Brief

* [ ] Update `createPaxServices` function
  *  Under `getSupportedConversionLabels` async callback, use `__experimentalResolveSelect` to call main resolver implemented in [8619](https://github.com/google/site-kit-wp/issues/8619, so data can be properly resolved, and then source data from `getModuleDataProperty` selector from `MODULE_ADS` datastore, and pass string: `supportedConversionEvents` as an argument
  * `supportedConversionEvents` will already have properly formatted array of event names, but do a quick sanity check to confirm it is an array, to either use it's value or an empty array for `conversionLabels` property 

### Test Coverage

* Update `createPaxServices` tests, to include new dataset in existing checks for `conversionLabels` value.

## QA Brief (QA:ENG)

* Mock some supported events by manually adding entries to the array returned by the `inline_modules_data()` method in `includes/Modules/Ads.php`, i.e `'supportedConversionEvents' => array( 'add-to-cart' ),`
* In Ads module `<SettingsView />` component:
    * Define a `registry` const and assign a value of `useRegistry()`
    * Define a `paxService` const and assign a value of `createPaxServices( registry );`
    * Console log the result of `paxService.conversionTrackingService.getSupportedConversionLabels()`
    * You should see the promise being fulfilled with a return object matching the shape of the mocked events in step 1, i.e

<img width="358" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/300e3505-58d7-4203-ae73-512d42b7234e">
    
* Changing the mocked values in step 1 should result in the same changes being mirrored in the step above

## Changelog entry

* Add `ConversionTrackingService` to PAX resolver/selectors.

**Comment by tofumatt** [comment]
ACs here look good 👍🏻

**Comment by 10upsimon** [comment]
IB LGTM ✅

**Comment by zutigrm** [comment]
#### QA:Eng Verified

Resolver/service is returning expected data. LGTM ✅
