### ISSUE TITLE
Enhance Analytics mock report generation function to support generating unique report based on dimension filters

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#8627]
## Feature Description

Noted while working on #8136, our current implementation of `getAnalytics4MockResponse` doesn't take `dimensionFilters` of report options into account, so even with different `dimensionFilters` passed, the same report is generated. This should be enhanced and for a test run, used to update the `AudienceTiles` stories so that different tabs (for different audience) show different data in storybook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `AudienceTiles` Storybook stories should be updated to show differing data across the audiences for the "Cities with most visitors" and "Top content by pageviews" metrics.
* I.e. the highlighted areas should have different data for each audience:
![image](https://github.com/google/site-kit-wp/assets/18395600/163dbc89-c444-499a-b0af-2430a8488d03)

## Implementation Brief

* [ ] Update the `getAnalytics4MockResponse` function in the following way:
    * [ ] Since the function generates totally random data based on the seed, and correctness of data regarding the actual `dimensionFilters` is not a concern (in reality, filtering by dimension would reduce the value, but this is not really needed and hard to achieve in generated report), this function should be updated to consider `dimensionFilters` if passed in args. 
    * [ ] If no `dimensionFilters` is passed, proceed to as it is done today for generating hash using the `args.url`. 
    * [ ] However, if the `args.dimensionFilters` is passed and valid (verify using the [`isValidDimensionFilters`](https://github.com/google/site-kit-wp/blob/0af42c685df9e4e05e3ddf3445bfacf5d3d1b170/assets/js/modules/analytics-4/utils/report-validation.js#L103) function), stringify the `dimensionFilters` object using `stringifyObject`, add the string to the url and generate the seed based of off that. 
    * [ ] This will introduce some changes in VRTs for stories where `dimensionFilters` is present in report args, so those needs to be updated. 

### Test Coverage

* Approve VRTs for changed stories. 

## QA Brief

* Check the `AudienceTiles` Storybook stories 
    * should  show differing data across the audiences for the "Cities with most visitors" and "Top content by pageviews" metrics.

## Changelog entry

* N/A

**Comment by techanvil** [comment]
Hi @kuasha420, this IB is looking good.

One small point, seeing as we won't need to parse `dimensionFilters` in `getAnalytics4MockResponse()`, we might as well make it explicit that we should validate it via [`isValidDimensionFilters()`](https://github.com/google/site-kit-wp/blob/0af42c685df9e4e05e3ddf3445bfacf5d3d1b170/assets/js/modules/analytics-4/utils/report-validation.js#L103) to ensure we do at least perform some level of validation on the passed value.

**Comment by kuasha420** [comment]
Great point, @techanvil. I've updated the IB accordingly!

**Comment by techanvil** [comment]
That's great, thanks @kuasha420!

IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This is was tested [here](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencetiles--default)
It was verified good: Tiles now have differing values for each tab.

Moving ticket to Approval.

<Details>
<img width="1312" alt="Screenshot 2024-05-09 at 23 08 02" src="https://github.com/google/site-kit-wp/assets/125576926/29ecfb5f-5e0f-4d03-8fcf-58c27d632f64">

</Details>
