### ISSUE TITLE
Standardise "Incomplete Setup" list in Settings for Ads and AdSense modules when AdBlocker is detected

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8634]
## Feature Description

1. As per point 2 of this [comment](https://github.com/google/site-kit-wp/issues/8515#issuecomment-2061489654), when an Ad Blocker is detected, a "Learn more" link should be displayed similar to the equivalent component for AdSense. 

2. Furthermore, these two components have different font sizes and should be standardised. The Ads module uses the `DefaultSettingsSetupIncomplete` component which uses the generic `ModuleSettingsWarning` component. This has a smaller font for any `requirementsError` messages. The AdSense module uses a custom `SettingsSetupIncomplete` component which then wraps the `AdBlockerWarning` component that contains the `Get Help` link as well.

Ads Incomplete Setup AdBlocker requirements error message:
![Screenshot 2024-04-17 at 15 13 15](https://github.com/google/site-kit-wp/assets/1721319/6c8c598e-38de-49d1-a0f0-f6e3652e4b5b)

AdSense Incomplete Setup AdBlocker Warning:
![Screenshot 2024-04-17 at 15 13 26](https://github.com/google/site-kit-wp/assets/1721319/00a3f973-8b26-4d7c-81d1-cce7bfb23888)

3. Finally, as per this [comment](https://github.com/google/site-kit-wp/pull/8566#discussion_r1567926190), there is a header separator for the Ads and AdSense modules' settings list that make the settings accordion look "better" when the AdBlocker Warning message is shown. This separator does not exist on other modules.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the "Connected Services" modules list, the following changes should be made as per this [Figma mock](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1341-3122&mode=design&t=43gLrefozZLS5ZCt-0):
  <img width="995" alt="ConnectedServices" src="https://github.com/google/site-kit-wp/assets/1721319/76632b8d-677d-4bc6-b3f7-403269ab6403">
* The colour of the "Complete setup for X" should be updated (black instead of grey). 
* Within the Ads and AdSense module sections, the horizontal rule (line) should be removed during setup (i.e. when connecting the modules). 
* The horizontal rule (divider) should also be removed for all modules in the modules list when opening the accordion and viewing/editing settings ([Figma](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1341-3122&mode=design&t=Kd5J2GEu89MFvbro-0)).
* Within the Ads and AdSense module sections, the Ad Blocker detected warning should be redesigned as per our new warning message pattern. All other generic warning / error messages other than Ad Blocker detection should also follow the same design.
* The Get help link should be added to the Ads section's Ad Blocker warning message, the same way we do for the AdSense module.
* When the AdBlocker error warning is rendered, the "Complete setup for X" button and "continue module setup" link should be in the disabled state (grey instead of black / green).
* The Ads, AdSense, Tag Manager and Analytics Setup screens should all have standardized logo, heading and spacing as per the new [Ads Figma mock](https://www.figma.com/design/THG1FJw5SaUxmiq38Mkf1x/Ads?node-id=653-3906&m=dev).

## Implementation Brief

* [x] [This branch](https://github.com/google/site-kit-wp/tree/enhancement/8634-ads-module-list-design-inconsistencies) implements the following points and can be used as a good starting point:
  * [x] `assets/sass/components/settings/_googlesitekit-settings-module.scss`, update the colour of the "Complete setup of module x" button (`mdc-button` within `googlesitekit-settings-module__header`).
  * [x] In `assets/js/modules/ads/components/setup/SetupMainPAX.js`, `assets/js/modules/ads/components/setup/SetupMain.js`, remove the `div` with class `googlesitekit-setup-module__step`. This removes the header divider.

#### Removing the divider
* [ ] In `assets/js/modules/adsense/components/setup/SetupMain.js`, remove the `googlesitekit-setup-module__step` as above, however, add necessary margins or padding for the content based on different setup components that the AdSense setup form can contain.
* [x] In `assets/sass/components/settings/_googlesitekit-settings-module.scss`, for the `googlesitekit-settings-module__content--open` class, add `border: none;` to remove the divider when the accordion is opened.

#### Restyling the Ad Blocker warning message (and other warnings in the list)
* [x] In `assets/js/components`, create a new reusable component, `WarningNotice`, which is similar in desing to the `SettingsNotice` component with `type=warning`. However, the colour of the font should be `$c-utility-on-warning-container`. This component also will not have any icon. Ensure that any links within this component are in bold and have the same colour as the text.
* [x] In `assets/js/components/AdBlockerWarningMessage.js`, use the above new `WarningMessage` component to render the message. Remove the additional `ErrorIcon`. Ensure that this warning is displayed correctly on the dashboard, in the "Connect more services" modules list, in the "Incomplete setup" modules list accordion as well as during module setup.
* [x] In `assets/js/components/notifications/ModuleSettingsWarning.js`, use the above `WarningMessage` component and remove the `ErrorIcon`. Remove any unused styles related to this component and ensure it is rendered correctly within the "Connect more services" modules list as well as the "Incomplete setup" list in "Connected services".

#### Adding Get help link to the Ads module
* [x] Similar to AdSense module, create a `SettingsSetupIncomplete` component in `assets/js/modules/ads/components/settings/`, which simply renders the `AdBlockerWarning` component.

#### Disabling the "Complete module setup" link
* [x] In both the `SettingsSetupIncomplete` components for Ads and AdSense, use the `getCheckRequirementsError` selector again to check if there is an error. If there is, then pass the disabled prop to the `Link` component for the "Complete module setup" link.

#### Disabling the "Complete setup for <module>" button
* [x] In `assets/js/components/settings/SettingsActiveModule/Header.js`, use the `getCheckRequirementsError` selector from the `core/modules` store. If there is an error, then in the `moduleStatus` button, pass the `disabled` prop to be `true`. 
* [ ] In `assets/sass/components/settings/_googlesitekit-settings-module.scss`, style this button as per the figma mock for the disabled state. 

### Test Coverage

* No new tests required.

## QA Brief

* In addition to verifying the ACs, test the entire Connected Services page thoroughly:
    * Verify that the modules list is now closer in appearance to this new Figma mock. (Perhaps not every aspect is still exact as this is out of the scope of this issue.)
    * Verify that the accordion works, including all the Connected and Not connected / Incomplete Setup buttons.
    * Verify that every settings edit and view for every module still looks fine and is not broken.
    * Verify the AdBlocker warning on both, the Ads and Adsense modules.

## Changelog entry

* Improve Ad Blocker warning messages for Ads and AdSense modules.

**Comment by jimmymadon** [comment]
@sigal-teller Based on the feature description of this issue, could you please advise on:
1. Point 2: Which font / design to use for the AdBlocker Warning component between the two existing screenshots.
2. Point 3: Should we keep the "header separator" for the modules settings view in Ads / AdSense and add it to the other modules? Or should we remove it from everywhere?

**Comment by bethanylang** [comment]
@jimmymadon The support team will need to work on creating a guide for the Learn more link and getting it uploaded to the service. @adamdunnage @jamesozzie Can you please coordinate with Jimmy here? Thanks!

**Comment by jamesozzie** [comment]
@jimmymadon @bethanylang The Get Help link already exists (with an `ads-ad-blocker-detected` error code). This is present in the [Support Redirects sheet](https://docs.google.com/spreadsheets/d/12x39d7j0GNqha0m7s4-Y3P5SwK9wwgxxxDnWp3svSKg/edit?resourcekey=0-IngulwDvPmI4SEq2g-f4rA#gid=1590434109). 

The link as per the sheet above directs users to https://sitekit.withgoogle.com/documentation/troubleshooting/ads/#ad-blocker-detected, as expected. I don't see the "Get Help" link at present when testing on a site, instead I see the below greyed out module setup screen when an Ad Blocker is detected. 
![image](https://github.com/google/site-kit-wp/assets/41326532/089c6585-7e25-476f-9952-77aadfcbfea2)

Happy to test once this is ready, or to answer any questions on the comments above.

**Comment by jimmymadon** [comment]
@bethanylang Actually, the 'Learn more' link is missing only on the component mentioned in the screenshots of this issue's feature description. It is already present in other places where it should be, viz. on the setup and settings forms where the AdBlocker warning is displayed. As @jamesozzie has mentioned, it is live and working from these places.

E.g. of the Setup form:
<img width="1010" alt="Screenshot 2024-04-29 at 18 10 05" src="https://github.com/google/site-kit-wp/assets/1721319/02bb1a66-5221-480d-ab06-44290359508d">

**Comment by sigal-teller** [comment]
Hey @jimmymadon  I reviewed this issue. Since this was never actually properly designed but was assembled from various components the result can be improved. I’m listing the changes that I think we need to implement, with a link to the relevant Figma design I created for it.
1. The complete setup for AdSense button shouldn’t be gray. We don’t use gray buttons anywhere else, only primary green or black. The gray one looks like a disabled state. I already updated it while working on Ads module, you can find it [here](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1341%3A2965&mode=design&t=hXzO39ssdpDGOVoD-1). 
2. We shouldn’t have a divider below the title, because it’s the same one that is being used as a divider between the modules. It makes it harder to understand that the settings below are a part of the module and relates to the title above. You can see that I didn’t add a divider in my designs too wherever I designed something for settings.
3. As for the warning text, I think that this is not a good UI, and maybe we can use here the same pattern that we’re using in other warning notifications to create consistency. We also don’t need to user the warning icon again if it shows at the top of the module to the right. I created a Figma design for it [here](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1341%3A3122&mode=design&t=hXzO39ssdpDGOVoD-1)
I know that this is an additional effort but it will unify these type of warning notifications.

**Comment by 10upsimon** [comment]
AC ✅

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified all the points mentioned under AC and QAB.
- Also, compared new design with the [Figma.](https://www.figma.com/design/THG1FJw5SaUxmiq38Mkf1x/Ads?node-id=1342-3371&m=dev)

@jimmymadon Please find my observations below :

_1) 'Complete setup for X' button text color in disable state is different from figma._

<details>

Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/6502a611-706a-4588-93ed-5ae54e7f8498)

![image](https://github.com/google/site-kit-wp/assets/94359491/82b8c14d-ed61-4a7f-a145-3412ea759909)

</details>

_2)  'Complete setup for X' button background color in disable state is different from figma._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/39f67ccd-5538-4491-9e0e-5993e5e65243)

Figma

![image](https://github.com/google/site-kit-wp/assets/94359491/a0b417f2-161b-455d-893d-277909319ed1)

</details>

_3) 'Complete setup for X' button text color in enabled state is different from figma._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/30bc2f0f-7a20-4369-b30e-986c6b2aaaf9)

Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/cd4bab55-fcf2-4f79-9c9a-ba14331857e6)

</details>

_4) 'Setup Complete' text Font weight is not same as Figma._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/462d9845-4447-47fc-b740-9dff1f1fd1a3)

Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/6a0511dd-328c-4f0a-bd49-b8d1ed6f434d)

</details>

_5) 'Get help" SVG icon looks little misalign and have different size than the figma._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/703584bf-1e59-49ad-9c7f-35a23f198339)

![image](https://github.com/google/site-kit-wp/assets/94359491/9abf3985-6725-4460-bef8-c80b8063b16d)

Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/3c6c94e4-4e3f-4add-99d2-e5133bcc2a93)

</details>

_6)  Icons, button and text alignment between accordions is not same as Figma._

<details>

Actual Implementation

![image](https://github.com/google/site-kit-wp/assets/94359491/18b878f2-1fc5-47e5-a318-b745c2468dcc)


Figma 

![image](https://github.com/google/site-kit-wp/assets/94359491/f46371af-45ee-4ad6-adcd-e8e198f50686)

</details>

**Comment by jimmymadon** [comment]
@mohitwp 

>Question When both the Ads and AdSense modules are connected and an AdBlocker is detected, we show a notice when the user tries to access the Ads module settings. However, the same notice does not appear when the user tries to access the AdSense module settings.

In #8515, we stopped showing settings for Ads as that needed a request that was being blocked by AdBlockers and the settings view and edit pages would throw errors. However, the same does not happen on the AdSense settings pages for now - so we continue to show these without any warning. This is a conscious decision so I suppose this is fine as is for now.

All other points have been addressed in the attached [follow up PR](https://github.com/google/site-kit-wp/pull/8768).

c.c. @tofumatt

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified all the points mentioned under AC and QAB.
- Also, compared new design with the [Figma.](https://www.figma.com/design/THG1FJw5SaUxmiq38Mkf1x/Ads?node-id=1342-3371&m=dev)
- Verified all issues reported above are now resolved


_1) 'Complete setup for X' button text color in disable state is different from figma._ (**_PASS)_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/8df7d69f-74f6-4fd1-90ab-e8e6bea5cf8d)

</details>

_2) 'Complete setup for X' button background color in disable state is different from figma._ **_(PASS)_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/9682672c-2f36-492f-8840-ef5f0f48d920)

</details>

_3) 'Complete setup for X' button text color in enabled state is different from figma._ **_(PASS)_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/d1fbf4c6-0563-472a-bbf8-a646ca1a4c31)

</details>

_4) 'Setup Complete' text Font weight is not same as Figma._ **_(PASS)_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/7532cbc5-4280-4852-8d18-7221877b5778)

</details>


_5) 'Get help" SVG icon looks little misalign and have different size than the figma._ **_(PASS)_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c0cdacf0-3766-45a7-9419-d69f94287ffc)


</details>

_6) Icons, button and text alignment between accordions is not same as Figma._ **_(PASS)_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/48c7f3ab-55d6-41f9-8dd0-ca6ea480f4ed)

</details>

**Comment by aaemnnosttv** [comment]
Nice improvement 👍
