### ISSUE TITLE
Implement PAX Config Support for `contentConfig.partnerAdsExperienceConfig.reportingStyle` Property 

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8637]
## Feature Description

As an extension to the PAX main component and scaffolding work done in #8556 and #8557, there is a need to implement the newly added PAX config property `contentConfig.partnerAdsExperienceConfig.reportingStyle`, which will be abstracted by the PAX component `displayMode` prop. 

Applicable values of this config property are:

- `REPORTING_STYLE_FULL` - Will render the full PAX experience, and should be the default mode
- `REPORTING_STYLE_MINI` - Will render the reporting widget only

As indicated in #8556 and #8557, support for this display mode was made available via a `displayMode` prop on the main PAX component, but it was not clear at the time what config value(s) these properties would interface with.

Component and config work implemented thus far should be extended so that values passed to `displayMode` prop are forwarded and abstracted as PAX config properties applicable to `contentConfig.partnerAdsExperienceConfig.reportingStyle`. The following values were earmaked for use as values passed to the `displayMode` prop:

- `'setup'` - Indicates the full PAX experience is desired, and should result in the `contentConfig.partnerAdsExperienceConfig.reportingStyle` config prop having a value of `REPORTING_STYLE_FULL`
- `'reporting'` - Indicates the widget reporting view for PAX, and should result in the `contentConfig.partnerAdsExperienceConfig.reportingStyle` config prop having a value of `REPORTING_STYLE_MINI`
- `'default' (or null/omitted)` - Indicates the full PAX experience is desired, and should result in the `contentConfig.partnerAdsExperienceConfig.reportingStyle` config prop having a value of `REPORTING_STYLE_FULL`

Implementation of the existing PAX config logic should be extended to cater for the above scenario.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The existing PAX Component as defined in #8557 should be extended/enhanced to support the PAX config property `contentConfig.partnerAdsExperienceConfig.reportingStyle`
* The 3 values passed to the PAX component `displayMode` prop should be abstracted to result in the applicable `contentConfig.partnerAdsExperienceConfig.reportingStyle` values of `REPORTING_STYLE_FULL` when the value of the `displayMode` prop is `'setup'` or `'default'`, or `REPORTING_STYLE_MINI` when the value of the `displayMode` prop is `'reporting'`

## Implementation Brief

* [x] Update `assets/js/modules/ads/components/PAXEmbeddedApp.js`
  * Expand existing `paxConfig` constant value, by including new property in the object: `contentConfig.partnerAdsExperienceConfig.reportingStyle` (dots annotate nesting)
    * For value, check if passed prop - `displayMode` has value of `reporting` to use `REPORTING_STYLE_MINI`
    * Otherwise assign it a value of `REPORTING_STYLE_FULL` by default

### Test Coverage

* No updates needed

## QA Brief

* As the PAX component is currently not surfaced to users, this must be tested by an engineer hence the QA:Eng tag - Confirm the AC is correctly implemented and the config passed to the PAX config is updated correctly based on the `displayMode`.

## Changelog entry

* Add support for the Partner Ads Experience `reportingStyle` config.

**Comment by tofumatt** [comment]
I think this sounds good, moving to IB 👍🏻 

Might be easier to do the IB after #8624 is merged, but not required 🙂

**Comment by 10upsimon** [comment]
IB ✅

**Comment by tofumatt** [comment]
There are no QA steps needed for this issue, moving directly to Approval.
