### ISSUE TITLE
Incorrect dimension filter applied in various components that uses `adSourceName` dimension 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#8658]
## Bug Description

In the following components, the `dimensionFilters` is applied in the report args incorrectly, resulting them to be no-op. 

* `AnalyticsAndAdSenseAccountsDetectedAsLinkedOverlayNotification`
* `DashboardTopEarningPagesWidgetGA4`
* `TopEarningContentWidget`

The dimension filters should be placed inside the `dimensionFilters` property in the report args object. Also for a little bit of simplification, the logic can be rewritten to be the following shorthand syntax, since the filter is a exact match string filter covered by `Google\Site_Kit\Modules\Analytics_4\Report\Request::parse_dimension_filter`:

```js
		dimensionFilters: {
			adSourceName: `Google AdSense account (${ adSenseAccountID })`,
		},
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Dimension filter for the Analytics reports in `AnalyticsAndAdSenseAccountsDetectedAsLinkedOverlayNotification`, `DashboardTopEarningPagesWidgetGA4` and `TopEarningContentWidget` should be applied correctly. 

## Implementation Brief

* [ ] Update the report args in `assets/js/components/OverlayNotification/AnalyticsAndAdSenseAccountsDetectedAsLinkedOverlayNotification.js`, `assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidgetGA4.js` and `assets/js/modules/adsense/components/widgets/TopEarningContentWidget.js` file: 
    * [ ] Remove the `filter` property from the report options. 
    * [ ] Add the `dimensionFilters` object to the report option, and add the `adSourceName` property with ``Google AdSense account (${ adSenseAccountID })`` value inside the `dimensionFilters` object. 

### Test Coverage

* Update all the relevant test and stories for the aforementioned components. 

## QA Brief

QAing the changes here specifically would require a site that would render the Top Earning Pages Widget and Top Earning Content Widget on the Site Kit dashboard, then testing the output before/after this change. That's probably not realistic, but checking for the filters being correct is enough really, so best to just test that the components are still rendering correctly without errors, and the new filters are working without issue.

* Set up Site Kit on a site with existing Analytics and AdSense data.
* Visit the main Site Kit dashboard.
* Ensure the Top Earning Pages Widget and Top Earning Content Widget render without errors.

## Changelog entry

* Update reports that use the `adSourceName` dimension to use the correct dimension filter.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified `DashboardTopEarningPagesWidgetGA4` and  `TopEarningContentWidget` on main dashboard.
- Verified `DashboardTopEarningPagesWidgetGA4` and  `TopEarningContentWidget` on entity dashboard.
- Verified both widgets are getting render without any error.
- Verified both widgets content is same on latest and dev environment.
- Verified all links under both widgets.


<details>

**Develop :**

_Top Earning pages widget_

![image](https://github.com/google/site-kit-wp/assets/94359491/8c0b0f1c-c07d-403f-99cb-4bb20e4868bf)

_Top Earning Content widget_

![image](https://github.com/google/site-kit-wp/assets/94359491/05d12529-bfeb-45d5-bc88-2eab7e9ba704)


**Latest :**

_Top Earning pages widget_


![image](https://github.com/google/site-kit-wp/assets/94359491/892b4859-f749-485f-b36e-11d9684e8939)



_Top Earning Content widget_

![image](https://github.com/google/site-kit-wp/assets/94359491/70f1d2cd-76d6-4cad-8495-5451abce12d7)


**View Only Dash board**

![image](https://github.com/google/site-kit-wp/assets/94359491/30e3937e-7954-4a4c-a3a8-71d859486f4b)

![image](https://github.com/google/site-kit-wp/assets/94359491/0b01492c-52f6-41a2-8abe-86651936c86e)

</details>

**Comment by hussain-t** [comment]
@10upsimon, @tofumatt, as discussed on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1717057383178479), the changes in the associated [PR](https://github.com/google/site-kit-wp/pull/8756) have caused VRT failures. Therefore, I’m moving this ticket back in execution to update the VRT images accordingly.

**Comment by techanvil** [comment]
As this was previously in Approval and the only change in the followup was to update the VRT images, and with CI confirmed passing for the update, I'm moving this back to Approval.
