### ISSUE TITLE
Continuous loading screen if trying to edit the Tag manager  module that another user connected

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#8659]
## Bug Description

If an admin tries to edit the Tag manager module (connected by a different admin who used a different Google account), they'll face a continuous loading screen as per the below screenshot.

![image](https://github.com/google/site-kit-wp/assets/94359491/bcb0c665-a971-4442-af6e-24c4de823031)

![image](https://github.com/google/site-kit-wp/assets/94359491/2fdfd82b-73af-4664-bb69-eb8fde0b7c12)

## Steps to reproduce

1. Set up SK on a site (admin1)
2. Connect the Tag manager module
3. Logout of wp-admin
4. Login back into wp-admin, this time using a different admin account (admin2)
5. Try to edit the Tag manager module (Settings > Connected Services > Tag manager > Edit)
6. The screen continuously loads

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
Closing as this was fixed in https://github.com/google/site-kit-wp/issues/8596.
