### ISSUE TITLE
Support unified App + Web properties

### ISSUE THREAD

**Issue by jangrewe** [google/site-kit-wp#866]
## Feature Description

I'd like to see support for those shiny new App + Web properties in Analytics. I recently created a new App + Web property for my app & website (surprise!) migrated my app's Firebase stats to Analytics, migrated my website's tracking to the new property (while still tagging the old property as a data stream), and now i tried out Site Kit - and was disappointed to see that i can only pick the old property's view, not the new App + Web property.

So i've removed the old property's snippet, enabled GTM and put both the old and new properties' tags into there, so that i get all tracking info in the new A+W property, but also in the old one which i can then use in Site Kit. Not optimal...

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for raising this @jangrewe ! This is something we're actively working on and tracking in #2220. Please follow this issue for updates 👍
