### ISSUE TITLE
Create Ads PAX Setup Success Notification Banner

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8661]
## Feature Description

When a PAX setup flow for Ads has been completely successfully, the user should be redirected to the main Site Kit dashboard and a campaign setup success notification banner should be displayed. This banner should contain a CTA that takes the user to the applicable reporting widget on the dashboard, and also be dismissible.

The Figma design can be viewed [here](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=850-1268&mode=design&t=yJXtn5iSKSufAdcP-0). Following is a screenshot of the success banner design:

<img width="1716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjIzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--955e1ea0a0279ff5af99140ec7dc11018f5babb2/image.png" alt="image.png" />

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Upon successfully completing the Ads PAX onboarding and creating a campaign, the user should be redirected to the main Site Kit dashboard and be presented with a success banner notification as per the [Figma design](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=850-1268&mode=design&t=yJXtn5iSKSufAdcP-0).
* This banner should contain two CTA's:
    * A main/primary CTA button labelled "Show Me" which should direct the user to the applicable Ads reporting widget on the main Site Kit dashboard and dismiss the notification.
    * A secondary CTA labelled "Got it" which should only dismiss the success banner notification.
* Upon dismissing the notification, said banner should not be displayed to the user again

## Implementation Brief

**Subtle Notification Component**
* [x] Create a new component  `assets/js/modules/ads/components/notifications/PAXSetupSuccessSubtleNotification.js` based on the existing `assets/js/components/notifications/SetupSuccessSubtleNotification.js` component updating the copy based on the [FIGMA designs](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=850-1268&mode=design&t=yJXtn5iSKSufAdcP-0).
* [x] While working on this ticket, move the `assets/js/components/notifications/SetupSuccessSubtleNotification.js` component to `assets/js/modules/ads/components/notifications/SetupSuccessSubtleNotification.js` as this notification is currently specific to the Ads module.
   * [x] Export a new constant `PAX_SETUP_SUCCESS_NOTIFICATION` within `assets/js/modules/ads/components/notifications/PAXSetupSuccessSubtleNotification.js` with the value `pax_setup_success_notification` which will be used to reference this notification in this component and in the redirect from the PAX service function.
   * [x] This component should use `useQueryArg` to check if the `notification` does not equal `PAX_SETUP_SUCCESS_NOTIFICATION` and return `null` in this case.
   * [x] Implement the "Got it" CTA just like it is in `assets/js/components/notifications/SetupSuccessSubtleNotification.js`, however we don't need to update the slug query arg, only remove the notification query arg when the `onDismiss` function is called.
   * [x] Implement the "Show me" CTA as a primary `Button` component, adding relevant CSS to confirm it matches the [FIGMA designs](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=850-1268&mode=design&t=yJXtn5iSKSufAdcP-0), and creating an onClick function called `onShowMe`:
      * [ ] Within the `onShowMe` function use the `getContextScrollTop` util to get the y offset of the PAX by passing the `.googlesitekit-pax-embedded-app` selector in the first argument and the current breakpoint in the second argument.
      * [ ] Use `global.scrollTo`, with `top` set to the value returned by `getContextScrollTop`, with `behaviour` set to `smooth`.

* [ ] Import and render the new `PAXSetupSuccessSubtleNotification` component within `assets/js/components/notifications/SubtleNotifications.js`

**PAX Setup Complete Redirect**
* [ ] Update the `onSetupComplete` function in `assets/js/modules/ads/components/setup/SetupMainPAX.js`, passing a custom redirectURL to the [`finishSetup` function](https://github.com/google/site-kit-wp/blob/86e19a2c92708bf2e3b310412d02bb170bd11c2a/assets/js/modules/ads/components/setup/SetupMainPAX.js#L112).
   * [ ] The redirect URL can be retrieved using `getAdminURL( 'googlesitekit-dashboard', { notification: PAX_SETUP_SUCCESS_NOTIFICATION } )`.

### Test Coverage

* Create stories for `PAXSetupSuccessSubtleNotification` and `SetupSuccessSubtleNotification` ~~[and add them to VRTs](https://github.com/google/site-kit-wp/issues/8661#issuecomment-2111082797)~~.

## QA Brief

* Setup SIte Kit with `adsPax` feature flag enabled
* Setup the Ads module using `create an account` button, and finalize the flow in the PAX app
* After completing the steps, you will be redirected to the dashboard - verify that success subtle notification is showing and it matches the figma design
* Clicking the "Got it" CTA button/link should dismiss the notification banner. It should not appear again on page refresh after this.
* Clicking on the "Show me" CTA button/link should dismiss the notification banner and scroll the page down to the ads section of the page. It should not appear again on page refresh after this.

## Changelog entry

* Add PAX notification banner when PAX setup is completed successfully.

**Comment by tofumatt** [comment]
ACs are good, moving to IB 👍🏻

**Comment by aaemnnosttv** [comment]
@benbowler IB looks good overall, just a few points to revise I think.

> * Update `assets/js/modules/ads/pax/services.js`, adding a new service function

This is being done in https://github.com/google/site-kit-wp/issues/8560, so it's out of scope here.

The change to which notification to trigger in the URL should be done in the `SetupMainPAX` via `finishSetup`.

As an aside, the `SetupSuccessSubtleNotification` (+ PAX variant added here) should be relocated within the Ads module structure rather than in our top-level components. Otherwise it seems like a generic component, but is Ads-specific. This is somewhat unrelated, but small enough to include here 👍

**Comment by benbowler** [comment]
Thank @aaemnnosttv, I've addressed your comments.

**Comment by benbowler** [comment]
@aaemnnosttv sounds good, yes it definitely makes sense to generalise the `SubtleNotification` in future.

**Comment by tofumatt** [comment]
@aaemnnosttv @benbowler I have it on my todo list to create issues for the subtle notification component to standardise it. The reason we didn't from the outset was I wanted a few instances in real-world use to extract the component from rather than prescriptively creating the component not knowing how we'd use it 🙂 

But now that we have a few examples of it I think we can generalise it. I'll create that issue(s) soon, it's just been a bit lower priority 😅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that if Ads Pax feature flag is enabled then Ads Pax Setup success notification banner is showing on main dashboard.
- Verified functionality of 'Got it' and 'Show me' CTA. Both are working as per AC.
- Verified notification banner design with the Figma.
- Verified notification banner responsiveness.
- 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/7b2fc9b7-aefb-4346-8a69-6fc4cb494f4f)

'Show me' CTA

https://github.com/google/site-kit-wp/assets/94359491/3d78023a-fba7-43ec-b447-8c77943cf27a

'Got it' CTA

https://github.com/google/site-kit-wp/assets/94359491/7ad84301-fc99-4b2a-8894-7303b90d4165

</details>
