### ISSUE TITLE
NPT Mobile Viewport issue on horizontal scroll

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#8663]
## Bug Description

Testing on this section of the Testing instruction doc: https://docs.google.com/document/d/1PThnH5ZgpYksgOAW2xHI6ONeIaHk74mj9qm65dlE_1w/edit#heading=h.ufyp724raw20

Figma: https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Application-Passwords?type=design&node-id=1-3267&mode=design&t=imRPtKsRHOwS6qSl-0

## Steps to reproduce

- Issue happens on mobile. I tested on iPhone 15Pro Max Safari.
- To view the Authorize Application screen with the customized styling applied, use the following URL with the hostname of your WP site.
`wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fpublishers.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true`
- I don't know it's because the URL is too long but the viewport is scrollable horizontally. I would assume we would wrap the URLs.
- And this is how it looked like after scrolling horizontally

## Screenshots

![IMG_5867](https://github.com/google/site-kit-wp/assets/125576926/802be46e-7e34-4290-a9ae-335dd6e3339d)

## Additional Context

 - WP 5.6.13
 - PHP Version: 8.0
 - OS: 17.4.1
 - Browser: Safari
 - Plugin Version: 1.126.0
 - Device: iPhone 15Pro max

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Authorize Application screen should not allow horizontal scrolling on mobile devices.
* Long URLs in any part of the screen, particularly in the "You will be sent to" description in the approve and reject sections, should be wrapped to prevent overflow.

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by hussain-t** [comment]
Hi @kelvinballoo, I tested it on the iPhone 15 Pro Max device using Safari and Chrome. However, I couldn't reproduce the issue. The gray boxes are already wrapped. Please refer to the following screenshots.

### Safari:

![IMG_5931](https://github.com/google/site-kit-wp/assets/24408261/293dfce3-c3aa-4bad-ba0d-c8f928261742)

![IMG_5929](https://github.com/google/site-kit-wp/assets/24408261/55ea7c43-3d6a-45df-b244-cd59964f870e)

### Chrome:

![IMG_5932](https://github.com/google/site-kit-wp/assets/24408261/4ed53efd-7de2-40e9-9dcd-54eed902d5e5)

![IMG_5930](https://github.com/google/site-kit-wp/assets/24408261/989cd9ab-f75e-4653-959b-58abe118ab6b)

**Comment by kelvinballoo** [comment]
The issue is actually happening on WP 5.6.13, not the latest versions.
Since it's an old version, it does not make sense to fix it.  
According to WordPress stats only 0.9% of WordPress users are on 5.6.  

As such, we are closing this ticket.
