### ISSUE TITLE
RTL languages translation for NPT

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#8664]
## Bug Description

When testing in RTL language, the 'Powered by Site Kit' is not properly aligned.

## Steps to reproduce

1. Set up the site language with one that is RTL, e.g. Persian, Arabic
2. To view the Authorize Application screen with the customized styling applied, use the following URL with the hostname of your WP site.
`wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fpublishers.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true`
3. See error

## Screenshots

Currently, the 'Powered by Site Kit' string is here and I think this should be moved to the left to mirror the WordPress version alignment:
<img width="1306" alt="Screenshot 2024-05-06 at 17 00 31" src="https://github.com/google/site-kit-wp/assets/125576926/ae4c6a33-7f73-46aa-ac23-98a5030b15ba">

For reference, stock styling looks like this:
<Details>
<img width="1312" alt="Screenshot 2024-05-06 at 17 02 24" src="https://github.com/google/site-kit-wp/assets/125576926/71ec29bd-5b79-4b1c-a88b-521bfd57ea7d">

</Details>

## Additional Context
 - PHP Version: 8.0
 - OS: MacOS Sonoma
 - Browser: Chrome
 - Plugin Version: 1.126.0
 - Device: Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure the 'Powered by Site Kit' text aligns correctly when viewed in an RTL (Right-to-Left) language context.
* The alignment of the 'Powered by Site Kit' custom footer text should mirror the alignment observed in the default WordPress footer when the website is set to an RTL language.

## Implementation Brief

In `assets/sass/authorize-application/_googlesitekit-authorize-application.scss`:

* [x] Add RTL specific styles for the `.googlesitekit-authorize-application__footer` within the `html[dir="rtl"]` selector:
    * [x] Set `left: auto` to remove the left positioning.
    * [x] Set `right: 0` to align the text to the right.
    * [x] Set `margin-right: 36px` to reverse the margin applied to the left side in LTR for the smaller screen sizes.
    * [x] For the larger screen sizes (`$width-desktop + 1 + px`), set `margin-right: 160px` to reverse the margin applied to the left side in LTR.

### Test Coverage

* No new tests are required for this change.

## QA Brief

* Follow the steps to reproduce the issue.
* Ensure the 'Powered by Site Kit' text is aligned correctly when viewed in an RTL language context.
* Ensure the alignment of the 'Powered by Site Kit' custom footer text mirrors the alignment observed in the default WordPress footer when the website is set to an RTL language.

## Changelog entry

* Ensure the "Powered by Site Kit" footer text on the Authorize Application screen is correctly aligned for RTL languages.

**Comment by techanvil** [comment]
IB :white_check_mark:
