### ISSUE TITLE
Refine Paragraph Styles Scope in the Authorize Application Screen

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8673]
## Feature Description

The current implementation of paragraph styles on the Authorize Application screen applies too broadly, affecting all paragraphs, including those outside the intended `.auth-app-card` area. This issue aims to refine the scope of these styles to ensure they only affect the relevant sections of the screen, improving overall style specificity and reducing potential style conflicts.

![image (1)](https://github.com/google/site-kit-wp/assets/24408261/19e7cee0-b30b-4784-9a88-7abeaecd713c)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **Paragraph Style Scope**: The paragraph styles currently applied globally under `.authorize-application-php` should be restricted to only affect elements within the `.auth-app-card` section.
* **Custom Footer Paragraph Styling**: The paragraph styling specifics should also be applied appropriately to the paragraph within the custom footer section.

## Implementation Brief

In `assets/sass/authorize-application/_googlesitekit-authorize-application.scss`:

* [x] Move the existing paragraph style rules under `.authorize-application-php` to ensure they only affect elements within the `.auth-app-card` section. See:
https://github.com/google/site-kit-wp/blob/b0c0c60a0224bc68ad64cf3a6d0459ce1ee0f219/assets/sass/authorize-application/_googlesitekit-authorize-application.scss#L45-L50
* [x] Apply the following specific paragraph styles to the `.googlesitekit-authorize-application__footer p` element:
    * [x] `line-height: $lh-authorize-application-label-lg`
    * [x] `margin: 19px 0 20px`

### Test Coverage

* No new tests are required for this change.

## QA Brief

* Navigate to the following URL on your WordPress site, replacing `example.com` with your actual site domain:
```
https://example.com/wp-admin/authorize-application.php?app_name=GoogleServiceIntegration&app_id=123e4567-e89b-12d3-a456-426614174000&success_url=https%3A%2F%2Fexample.google.com%2Fsettings%2Fauthorization%2Fwordpress&sitekit=true
```
* Verify that the paragraph styles are only applied to elements within the `.auth-app-card` section.
* Verify that the custom footer paragraph styling is correctly applied to the paragraph within the custom footer section.
* Verify that the paragraph styles are not applied to any other screen sections.

## Changelog entry

* Improve style specificity in the Authorize Application screen.

**Comment by techanvil** [comment]
IB :white_check_mark:, thanks @hussain-t!

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @hussain-t , did a test on this and it's looking good overall. I do have some clarifications to be confirmed.

Observations are as follows:

- Most of the Paragraph elements are within the ` .auth-app-card `section. ✅ 
   <Details>
   <img width="1141" alt="Screenshot 2024-05-28 at 18 08 36" src="https://github.com/google/site-kit-wp/assets/125576926/cb402ee6-69d2-4cf6-b032-63eeac20fe9a">
   </Details>

- The other footer paragraph are under `wpfooter` and `googlesitekit-authorize-application__footer` respectively. I believe that's as expected but can you confirm.  ⚠️ 
   <Details>
   <img width="757" alt="Screenshot 2024-05-28 at 18 23 13" src="https://github.com/google/site-kit-wp/assets/125576926/a7bd962a-f7fa-403b-a66c-d912b6a508a1">
   </Details>

- I noticed other paragraph elements on the page under different sections `wp-auth-fallback` , even though those are not visible. Any concern for those? ⚠️ 
   <Details>
   <img width="966" alt="Screenshot 2024-05-28 at 18 27 56" src="https://github.com/google/site-kit-wp/assets/125576926/489c91f4-8d4d-4f0b-922e-9d93f7413299">
   </Details>
