### ISSUE TITLE
Redirect_uri mismatch

### ISSUE THREAD

**Issue by jwdegeus** [google/site-kit-wp#868]
When trying to connect with the Google services, the browser returns a redirect_uri mismatch. Any idea how I can solve this?

**Comment by jamesozzie** [comment]
@jwdegeus Thanks for submitting a request. Site Kit support is provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your question on there, where we would be happy to assist. 

You can also check your "WordPress Address" and "Site Address" from your WordPress general settings to see if that allows you to proceed.
