### ISSUE TITLE
Implement partner authentication service

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8686]
## Feature Description

The partner services provided to the PAX app should be extended to include a new implementation for the authentication service.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `authenticationService` of the PAX partner services should be implemented similar to others such that it is automatically provided to all PAX app instances

## Implementation Brief

* [x] Update `createPaxServices` to define a new top-level `authenticationService` with its methods
	- `get` returning a `GetResponse`, specifically just the `{ accessToken: string }` (`authUser` not needed)  
	Return the same token used in the config for now
	- `fix` returning a `FixResponse`; this can be the same as `fixBusinessInfo` for now

### Test Coverage

* Add relevant coverage as for other services

#### QA:Eng
* Verify that tests are passing and nothing else is affected. Basically this can be verified in CR/MR and probably go to approval afterwards since there is nothing much to test

## Changelog entry

* Add the partner authentication service to the PAX app.

**Comment by benbowler** [comment]
### QA:Eng Passed ✅
