### ISSUE TITLE
Too loud and aggressive layout

### ISSUE THREAD

**Issue by TomMuc1** [google/site-kit-wp#869]
-> remove too big headline ‘G Site Kit’ on sidemenu, dashboard and screenoptions
-> add ‘speed’ and ‘popularity’ boxes to dashboard
-> remove the promotion banners for analytics on dashboerd boxes
<img width="138" alt="Bildschirmfoto 2019-11-16 um 18 52 00" src="https://user-images.githubusercontent.com/31601862/68997065-76dadb00-08a2-11ea-894d-3d61f4dee19d.png">
<img width="248" alt="Bildschirmfoto 2019-11-16 um 18 52 19" src="https://user-images.githubusercontent.com/31601862/68997066-76dadb00-08a2-11ea-84ed-c95ac6375b55.png">
<img width="175" alt="Bildschirmfoto 2019-11-16 um 18 52 53" src="https://user-images.githubusercontent.com/31601862/68997067-77737180-08a2-11ea-8220-26ce4c688c23.png">

**Comment by ThierryA** [comment]
Thanks for your feedback. Some valid points about the G Site Kit logo IMO. [I opened an issue](https://github.com/google/site-kit-wp/issues/877) to address that.

Regarding your other too points, improving the layout, specifically call to actions like setting up analytics is on the roadmap but no ETA at this stage. Note that we are committed to improve the product, a ton of work is happening on a daily basis as you can see in the projects which is publicly accessible.

**Comment by aaemnnosttv** [comment]
Closing this out in favor of dedicated issues:

- https://github.com/google/site-kit-wp/issues/877 (fixed)
- https://github.com/google/site-kit-wp/issues/1147
