### ISSUE TITLE
Update PAX conversion tracking service for compatibility with v1

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8693]
## Feature Description

When we added the initial implementation of the `conversionTrackingService`, it was using a pre v1 definition which has since changed and needs some minor revisions.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PAX `conversionTrackingService` should be updated for compatibility with the current definition as defined in [its type definition](https://github.com/google/partner-ads-experience/blob/0a585179487fb373f67745a540cce47c577b8b21/sdk/service/partner/conversion-tracking-service.d.ts#L105-L129)

## Implementation Brief

* [ ] Add the `getSupportedConversionTrackingTypes` method returning `GetSupportedConversionTrackingTypesResponse` (`{ conversionTrackingTypes: string[] }`)
	- For now, this should only be a list with `TYPE_PAGE_VIEW`
- [ ] Update the response for `getPageViewConversionSetting` to conform to the current `GetPageViewConversionSettingResponse` type by removing `enablePageViewConversion` from the response

### Test Coverage

* Update coverage for the service

## QA Brief

The changes here should allow for the PAX campaign creation flow to complete successfully. At the same time, we should now see the page view conversion behavior for all conversion goal choices.

* Set up the Ads module using the PAX app setup by enabling `adsModule` and `adsPax` feature flags.
* Set up Site Kit and set up the Ads module.
* There should be no errors during setup.
* Conversion goal choices should show "page view conversions".

## Changelog entry

* Update PAX conversion tracking service code to improve compatibility with the new PAX version 1 API.

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified Ads module set up when 'adspax' feature flag enabled.
- Verified Ads module set up through pax app.

@aaemnnosttv Please find my observations below with couple of questions.

Q-1) QAB says - `'Conversion goal choices should show "page view conversions".` Can you please tell me where this info will display? I found conversion goals under Ads dashboard and for me status is showing inactive.

![image](https://github.com/google/site-kit-wp/assets/94359491/622e477c-cea5-4b79-9bf1-0a92dc638188)


Q-2) I haven't tested the design, responsiveness, and validation for the Pax campaign creation. Neither QAB nor AC mentions anything about design QA. Can you confirm if I don't need to test responsive and design issues as part of this ticket?


_Issue 1> On Pax app campaign creation 1st step console error is appearing._ 

</details>

![image](https://github.com/google/site-kit-wp/assets/94359491/a436b99e-ea85-4eff-b7e7-4cef914ad718)


https://github.com/google/site-kit-wp/assets/94359491/e3ff4bb0-fdbd-490e-abcd-74a0cdfb4794

</details>

_Issue 2> At 'What goal should your campaign be optimized to deliver?" step console error appears with red box if we remove single word from the selected page slug. This may be related to validation._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/ad9bab38-0958-44ca-a61e-f66569160643)

![image](https://github.com/google/site-kit-wp/assets/94359491/8a6eaf80-327f-419c-ac6d-c8a35a6d3342)


https://github.com/google/site-kit-wp/assets/94359491/833233d8-63a5-4f18-a87e-e831268d21ba

</details>

_Issue 3> If 'adspax' feature flag is enabled and Ads module is already set up then console error with red box appears on Dashboard after completing analytics setup._

<details>

https://github.com/google/site-kit-wp/assets/94359491/ea41ede3-5d7b-4a8f-884c-584a1c1cf1e5

![image](https://github.com/google/site-kit-wp/assets/94359491/dc4833bf-1260-4a84-8fa7-b30bfaca0a03)

![image](https://github.com/google/site-kit-wp/assets/94359491/7dc8633f-ca9f-468b-906b-bfd67088ebc1)

![image](https://github.com/google/site-kit-wp/assets/94359491/58b19998-07b5-4130-9bc3-ffd05043802e)

</details>

**Comment by zutigrm** [comment]
@mohitwp Thanks for your observations.

All error related questions are as I recall due to the proxy, it is coming from PAX app itself. Nothing that prevents PAX from working in current setup.

The last one - error on dashboard is missing dates service which is addressed in #8687 , you can ignore it for now until that issue is merged.

Regarding:
> Q-1) QAB says - 'Conversion goal choices should show "page view conversions". Can you please tell me where this info will display? I found conversion goals under Ads dashboard and for me status is showing inactive.

I am not having enough info regarding this point maybe @10upsimon has more insights into this one

**Comment by aaemnnosttv** [comment]
> **Q-1)** QAB says - `'Conversion goal choices should show "page view conversions".` Can you please tell me where this info will display? I found conversion goals under Ads dashboard and for me status is showing inactive.

@mohitwp Conversion Goal choices are what you are prompted for on the step "What goal should your campaign be optimized to deliver?" i.e. what goal should your campaign be optimized for.

You should see the page view option for each choice but only when selected. This is shown by the page path select. This is then configured as a page view conversion – page views for the given URL are considered a conversion for the selected goal. 
<img width="555" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/4d683654-5ff4-46cb-8d99-9698d6472c8d">


> **Q-2)** I haven't tested the design, responsiveness, and validation for the Pax campaign creation. Neither QAB nor AC mentions anything about design QA. Can you confirm if I don't need to test responsive and design issues as part of this ticket?

Correct. This issue does not affect the UI but addresses some changes on our end to work with PAX. Regarding the UI though, it's important to understand what part is SK and what is PAX. Basically everything below the line and above the button here is PAX 
<img width="493" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/48070e78-1cfc-452a-b10d-c1ea723eb753">

We should still flag issues we find but we don't need to be testing this on issues that don't call for it.

> **Issue 1** On Pax app campaign creation 1st step console error is appearing.

This is a known issue that we've reported and it can be ignored for now.


> **Issue 3** If 'adspax' feature flag is enabled and Ads module is already set up then console error with red box appears on Dashboard after completing analytics setup.

I think this is related to the work in #8559.

Back to you @mohitwp !

**Comment by mohitwp** [comment]
Blocked by the #8687. cc @wpdarren

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Set up Ads module and successfully created a campaign.  See note. 
- Each conversion goal choice shows the page view option, but only when selected. 

**Note:** There are a number of errors in the PAX application that we will feed back to the Ads team.  These are not related to Site Kit but the application itself. 

![image](https://github.com/google/site-kit-wp/assets/73545194/99a473a7-b5b4-4aa3-b1c7-ae07a35e6b4d)
