### ISSUE TITLE
Difference between Search Console metrics percentage

### ISSUE THREAD

**Issue by fellyph** [google/site-kit-wp#870]
## Bug Description

At the Search Funnel Session the percentage of impressions and clicks change between screens 

## Steps to reproduce

1. Go to Dashboard the percentage is -2.3% for impressions and +39% for Clicks.

2. Click on 'Source: Search Console' the percentage change to +39% foro clicks and -2.3% for impressions.

## Screenshots

Dashboard
<img width="541" alt="Screen Shot 2019-11-17 at 08 52 55" src="https://user-images.githubusercontent.com/330792/69005380-5e59d780-0919-11ea-83dd-e5253c727996.png">

Search Console panel:
<img width="632" alt="Screen Shot 2019-11-17 at 08 52 46" src="https://user-images.githubusercontent.com/330792/69005396-a4af3680-0919-11ea-942e-0aad5b84c55b.png">

## Additional Context

 - PHP Version: 7.3.11
 - Browser: chrome
 - Plugin Version: 1.0.4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@fellyph Thanks for reporting, I can confirm the same from my side. The comparisons on previous months are switched. ("Clicks" comparison is displaying the "impressions" comparison and vice versa)

![gcKcElRcZH](https://user-images.githubusercontent.com/41326532/69043737-844fac80-09eb-11ea-988c-98e5662ffb11.gif)

**Comment by aaemnnosttv** [comment]
The current UI appears to be correct; it must have been fixed in other issues.

**Dashboard**
![image](https://user-images.githubusercontent.com/1621608/113566587-a3b59c80-9615-11eb-9d04-84b51041125f.png)

**Search Console dashboard**
![image](https://user-images.githubusercontent.com/1621608/113566610-b5973f80-9615-11eb-80b5-ec5575c0eb68.png)
