### ISSUE TITLE
Avoid layout shift when showing the Setup CTA Banner.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8707]
## Feature Description

The initial integration of the Setup CTA Banner (see https://github.com/google/site-kit-wp/issues/8131) results in a layout shift when showing the banner, as the conditions for showing it are not known immediately upon page load.

We should investigate and implement a mechanism for avoiding this layout shift where possible.

A useful side effect of this would be to reduce the number of times we need to [request a report](https://github.com/google/site-kit-wp/blob/1bcffda7ff222e467dd0929db50f4cdf74bcc06c/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L74-L89) for determining the conditions for showing the banner.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The condition for showing the Setup CTA Banner should only require the current GA4 property to be out of the "gathering data" state, and for the page to be reloaded once availability of data for the gathering data state has been determined. It should _not_ require data to be present over the past 90 days.
* There should not be a layout shift when showing the Setup CTA Banner, it should appear straight away on page load.
* If necessary we can determine the state on a given page load, but show the banner on a subsequent page load (similar to the approach taken for the Key Metrics Setup CTA).

## Implementation Brief

- [ ] There are two requests which because of which banner has to wait for gathering the data and causes the layout shift.
    1. Audience settings.
    2. Analytics Report.

#### 1. Audience settings

- [x] Preload the audience settings with the route `/modules/analytics-4/data/audience-settings` in `includes/Modules/Analytics_4.php` inside register method using `googlesitekit_apifetch_preload_paths` hook. This would make the audience settings data readily available on the page.

#### 2. Analytics Report

- Within the `AudienceSegmentationSetupCTAWidget` component:
  - [x] On page load, check if the data is available for the `analytics-4` module. This can be achieved by doing the same thing as that of the `KeyMetricsSetupCTAWidget` component [here](https://github.com/google/site-kit-wp/blob/305bcbefbd6ec42b90050744d44d6e99225fb52e/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js#L73-L75).
  - [x] Remove the `hasDataWithinPast90Days` check as we no longer need it.
  - [x] Return `null` if `configuredAudiences` is truthy or `undefined`, or the `isDataAvailableOnLoad` selector returns `false`.

### Test Coverage

* Add test coverage for the `AudienceSegmentationSetupCTAWidget` component:
  * Add tests for the cases where `configuredAudiences` returns a truthy or `undefined` value. In such cases, the component should not render anything.
  * Add test for the component where `isDataAvailableOnLoad` selector returns `false`. In such case, the component should not render anything.
  * Add a test for the component where `configuredAudiences` is `null` and `isDataAvailableOnLoad` returns `true`. In such case, the component should render the setup CTA banner.

## QA Brief

1. Go to https://myaccount.google.com/connections and remove permissions for "Site Kit".

2. Disconnect Site Kit from in wp-admin and re-connect the Site Kit. This will effectively reset the Google analytics settings so that banner should be visible.

3. Go to the Site Kit dashboard page. Check in browser console under "Network" tab, there should be no request for `audience-settings` for `/modules/analytics-4/data/audience-settings` path, as this path is preloaded. This behaviour can also be verified by running following command in browser console. The results should be immediately available, without `undefined`.

```js
googlesitekit.data.select('modules/analytics-4').getAvailableAudiences();
```

4. Run, the following command. If the return value is `true`, banner should be visible, else hidden. 

```js
googlesitekit.data.select('modules/analytics-4').isDataAvailableOnLoad();
```

5. Running following command in browser console should remove the banner from the page.

```js
googlesitekit.data.dispatch('modules/analytics-4').receiveIsDataAvailableOnLoad( false );
```

## Changelog entry

* Fix layout shift that appears when the audience groups setup CTA banner is displayed.

**Comment by techanvil** [comment]
Hey @ankitrox, this IB is looking good. A few points:

- Let's mention the `AudienceSegmentationSetupCTAWidget` in the IB for the sake of clarity.
- Let's also be specific about the REST route we want to preload, which is `/modules/analytics-4/data/audience-settings`.
- I made a couple of trivial tweaks which you can see in the edit history.
- Last but not least, I'd suggest increasing the estimate to an 11. With the tests, and also taking QA into account, I think this would weigh in a bit over a legitimate 3, which would take it to a 7. Our estimate bump would therefore take it to an 11.

**Comment by ankitrox** [comment]
Hi @techanvil ,

Thank you for reviewing IB. I have made the suggested changes in IB and updated the estimate to 11 points as I agree with what you mentioned regarding the time which we have to spend across the workflow.

Assigning this to you for IB review again.

Thank you.

**Comment by techanvil** [comment]
Thanks @ankitrox. The IB was mostly LGTM, however I have tweaked it for brevity and to correct a minor mistake. Please review the changes and feel free to move it to the EB if you are happy with it.

**Comment by ankitrox** [comment]
Thank you @techanvil . Moving this to EB as everything seems fine to me.

**Comment by ankitrox** [comment]
Thank you @nfmohit for reviewing the PR and adding the feedback.

I have addressed your comments and moving this again to CR.

Assigning this over to you for re-review.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

I have tested this and I just need a confirmation that the behaviour is as what we expect.

- In browser console under "Network" tab, there was no request for audience-settings for /modules/analytics-4/data/audience-settings path ✅ 
   <Details>
   <img width="1223" alt="Screenshot 2024-06-05 at 19 17 14" src="https://github.com/google/site-kit-wp/assets/125576926/2862e8a9-67ee-46ae-aa2b-c79a41554abf">
   </Details>

- When running `googlesitekit.data.select('modules/analytics-4').getAvailableAudiences();` , sometimes it will return null and sometimes the data. Checked with @ankitrox and this is as expected. ✅ 
   <Details>
   <img width="1305" alt="Screenshot 2024-06-05 at 17 25 28" src="https://github.com/google/site-kit-wp/assets/125576926/3532a106-6182-48ff-92fe-2064476931f1">
   
   <img width="1200" alt="Screenshot 2024-06-05 at 19 16 16" src="https://github.com/google/site-kit-wp/assets/125576926/ce3fae86-5825-46b3-adfe-6df5d17fa088">

   </Details>

- When googlesitekit.data.select('modules/analytics-4').isDataAvailableOnLoad(); is true, the banner will appear ✅ 

- When googlesitekit.data.select('modules/analytics-4').isDataAvailableOnLoad(); is false, the banner will disappear ✅ 

- It's worth noting that the banner will not automatically appear on the first page load. Refer to the below screenshot where there was multiple request which was false even though there was audience values

   <Details>
   <img width="1200" alt="Screenshot 2024-06-05 at 19 16 16" src="https://github.com/google/site-kit-wp/assets/125576926/10c3ec82-51b7-4f6a-9031-3f0181c2e774">

   </Details>
   
   It was only when I reloaded the page that the banner would appear. Is that the correct behaviour @ankitrox  ? ⚠️

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks for the confirmation @ankitrox .
This ticket is good to go to Approval queue.

- In browser console under "Network" tab, there was no request for audience-settings for /modules/analytics-4/data/audience-settings path ✅ 
   <Details>
   <img width="1223" alt="Screenshot 2024-06-05 at 19 17 14" src="https://github.com/google/site-kit-wp/assets/125576926/2862e8a9-67ee-46ae-aa2b-c79a41554abf">
   </Details>

- When running `googlesitekit.data.select('modules/analytics-4').getAvailableAudiences();` , sometimes it will return null on the first round and then later on, there would be data. Checked with @ankitrox and this is as expected. ✅ 
   <Details>
   <img width="1305" alt="Screenshot 2024-06-05 at 17 25 28" src="https://github.com/google/site-kit-wp/assets/125576926/3532a106-6182-48ff-92fe-2064476931f1">
   
   <img width="1200" alt="Screenshot 2024-06-05 at 19 16 16" src="https://github.com/google/site-kit-wp/assets/125576926/ce3fae86-5825-46b3-adfe-6df5d17fa088">

   </Details>

- When googlesitekit.data.select('modules/analytics-4').isDataAvailableOnLoad(); is true, the banner will appear ✅ 

- When googlesitekit.data.select('modules/analytics-4').isDataAvailableOnLoad(); is false, the banner will disappear ✅ 

- It's worth noting that the banner will not automatically appear on the first page load. It is only when we reload the page that the banner would appear. This is the expected behaviour ✅
