### ISSUE TITLE
Don't load analytics script when user is logged-in as administrator

### ISSUE THREAD

**Issue by mehul0810** [google/site-kit-wp#872]
## Bug Description

As a user, I don't want to load the analytics script when I'm logged in as an administrator as this has more chances to mess up with the analytics data. There are many chances that admin has to check the frontend which should add him as a visitor in Google Analytics.

## Steps to reproduce
1. Login the WP site as the administrator
2. Connect Google Analytics account with SiteKit
3. Go to frontend of the site in the same browser and check the page source
4. You will notice that the analytics JS is still loaded
4. Also, notice that the same is updated in the Google Analytics dashboard.

## Additional Context

 - PHP Version: 7.3
 - OS: macOS 
 - Browser: Chrome (can be replicated with any browser)
 - Plugin Version: 1.0.4
 - Device: Not tried with device

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@mehul0810 We have an open issue for this at the moment, you can add your input into that issue at #88. 

You can also setup a view and [filter](https://support.google.com/analytics/topic/1032939?hl=en&ref_topic=1726911) from within your Analytics property to ensure admin users are not tracked. Using the "wp-login.php" filter pattern should do the trick. I will close this issue but feel free to contribute to the open issue.
