### ISSUE TITLE
[Post July 31st, 2024] Remove the conditionality for including Switzerland in the list of regions for the EU user consent policy.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8720]
## Feature Description

**This shouldn't be merged until a release that's after July 31st, 2024.**

Once July 31st, 2024 has passed, the EU user consent policy will apply to Switzerland and the conditionality for including it introduced via #8643 should be removed (i.e. the date / feature flag check).

See the PR for the issue, https://github.com/google/site-kit-wp/pull/8704, for code-level details. Any code relating to the change which is no longer needed should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Switzerland (country code `CH`) should always be included in the list of "consent mode regions" in Site Kit, without a feature flag or date condition.
* The `consentModeSwitzerland` feature flag should be removed.

## Implementation Brief

* [x] Remove the `consentModeSwitzerland` feature flag from `feature-flags.json`.
* [x] In `includes/Core/Consent_Mode/Regions.php`, add `'CH'` to the array `EU_USER_CONSENT_POLICY` and remove the condition completely in `get_regions`:- this function should now simply return `EU_USER_CONSENT_POLICY`.
* [x] Update `assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.js`, removing the two conditions on `'CH'` being included in the list of regions. The copy for both the Ads connected and not connected states should mention Switzerland:
   * [x] When the Ads module is **not** connected the subtitle copy should be: `Disabling consent mode may affect your ability in the European Economic Area, the UK and Switzerland to:`
   * [x] When the Ads module is connected the subtitle copy should be: `Disabling consent mode may affect your ability to track these in the European Economic Area, the UK and Switzerland:`

### Test Coverage

* [x] Remove use requirement of the feature flag in `assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.test.js`, in the `should display appropriate subtitle with Ads connected and Switzerland included in list of consent mode regions` test.
* [x] Update the tests `assets/js/components/consent-mode/ConfirmDisableConsentModeDialog.test.js`. Only two tests should be required:
   * [x] `should display appropriate subtitle with Ads not connected`
   * [x] `should display appropriate subtitle with Ads connected`
   * [x] Switzerland should always be included in the subtitle copy.
   * [x] Also remove the requirement for the feature flag in these tests.
* [x] In `tests/e2e/specs/front-end/consent-mode.test.js`, remove the test `includes Switzerland (CH) in the list of regions when the consentModeSwitzerland feature flag is enabled`.

## QA Brief

* Test disabling consent mode with both the Ads module enabled and disabled:
   * When the Ads module is **not** connected the subtitle copy should be: `Disabling consent mode may affect your ability in the European Economic Area, the UK and Switzerland to:`
   * When the Ads module is connected the subtitle copy should be: `Disabling consent mode may affect your ability to track these in the European Economic Area, the UK and Switzerland:`
 * The `consentModeSwitzerland` feature flag should not appear in the list of feature flags in the tester plugin.

## Changelog entry

* Update Consent Mode to always include Switzerland in its list of relevant areas.

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
This shouldn't be merged until a release that's after July 31st, 2024. I've added a note to the issue, but it's not worth reviewing this in case it will have merge conflicts in a few months.

For now this can stay in CR, but it will might need a bit more time in execution to clear up potential merge conflicts that come up over the next few months 😅

**Comment by mohitwp** [comment]
### QA Update ❌ 


@benbowler 

- Tested on dev environment.

_**Issue - `consentModeSwitzerland` feature flag is still showing on dev environment.**_

![image](https://github.com/user-attachments/assets/4f61049f-01ae-42bc-936a-c410ed11be9e)

**Comment by tofumatt** [comment]
Indeed, the feature flag should be removed. That should have been added to the QA brief as well, so I've updated the QA brief and added a new PR to remove the feature flag. Thanks @mohitwp 👍🏻

**Comment by mohitwp** [comment]
![image](https://github.com/user-attachments/assets/c38caa87-ad15-4349-b341-f3f86ec984fa)

![image](https://github.com/user-attachments/assets/080748f1-b4b4-4fce-821f-e3bf42dbabf6)

![image](https://github.com/user-attachments/assets/7a781832-a8ec-457c-92b5-d8d444661965)

Disable CM when Ads module connected and 


https://github.com/user-attachments/assets/b7822e9e-6caf-4bb5-b636-3493db63b5b8

Disable CM when Ads module is not connected
