### ISSUE TITLE
Add `whenInViewContext` higher-order component (HOC) to allow simplification of code that should only run inside some view contexts

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8723]
## Feature Description

There are places in the codebase where we don't want to render a component or want to render a fallback in certain view contexts. Mostly, this is when we don't want a component to render on a view-only dashboard. Example: https://github.com/google/site-kit-wp/blob/4cce042da8831b2ec8663e4d9767bc0610ae4e5a/assets/js/components/notifications/GA4AdSenseLinkedNotification.js#L115-L121

Because some selectors will actually error on view-only dashboards (because a view-only user doesn't have access to the API routes/etc.), we have to guard every selector call, which is wasteful.

Similar to our [`whenActive` higher-order component](https://github.com/google/site-kit-wp/blob/9853b1984767c4e4680be0f1fa61297e74f8a486/assets/js/util/when-active.js), we should create a `whenInViewContext` HOC that allows us to only render a component in certain view contexts, and use that component to refactor existing components like `GA4AdSenseLinkedNotification`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `whenInViewContext` HOC should be created that behaves similarly to the `whenActive` and `whenScopesGranted` HOCs, except it should render/not render based on arguments supplied:
  * `allViewOnly`, which when `true` should render the component when `useViewOnly()` returns `true`
  * `allNonViewOnly` which when `true` should render the component when `useViewOnly()` returns `false`
  * `includeList` which is an array of view contexts that the component should render when present
  * `excludeList` which is an array of view contexts that the component should render when _not present_
  * Supplying any mutually exclusive arguments (eg. `includeList` and `excludeList`) should throw an error
* The [`GA4AdSenseLinkedNotification.js`](https://github.com/google/site-kit-wp/blob/4cce042da8831b2ec8663e4d9767bc0610ae4e5a/assets/js/components/notifications/GA4AdSenseLinkedNotification.js#L115-L121) component should be refactored to use this new HOC and remove any (now-redundant) checks from its `useSelect` calls (example: https://github.com/google/site-kit-wp/blob/de09a10c23b15d090ed2207693f6ac9e1bb67f7e/assets/js/components/notifications/GA4AdSenseLinkedNotification.js#L62-L64)

## Implementation Brief

**whenInViewContext HOC**
* [ ] Create a new component, `whenInViewContext`, in the file `assets/js/util/whenInViewContext.js`:
   * [ ] The HOC should accept the four props specified in the AC.
      * [ ] Add `invariant` call, with the props: `!(!! includeList && !! excludeList)` and the message: 'include and exclude lists cannot both be provided'.
      * [ ] Add `invariant` call, with the props: `!(!! allViewOnly && !! allNonViewOnly)` and the message: 'view only and non view only lists cannot both be true'.
   * [ ] The HOC should return `( WrappedComponent ) => {`:
      * [ ] This should define a function: `function WhenInViewContext( props ) {`
         * [ ] Get the viewOnly value using `const isViewOnly = useViewOnly();`
            * [ ] If `props.allViewOnly` is `true` and `isViewOnly` is `false`, return `null`.
            * [ ] If `props.allNonViewOnly` is `true` and `isViewOnly` is `true`, return `null`.
         * [ ] Get the current view context using `const viewContext = useViewContext();`
            * [ ] If `!! includeList` and `! includeList.includes( viewContext )`, return `null`.
            * [ ] If `!! excludeList` and `includeList.includes( viewContext )`, return `null`.
          * [ ] At the end of the function return `<WrappedComponent { ...props } />;`

**Update GA4AdSenseLinkedNotification**
 - [ ] Update `assets/js/components/notifications/GA4AdSenseLinkedNotification.js`, wrapping the export of the component with the new `whenInViewContext` HOC, passing the props: `{ allViewOnly: true }`.
    - [ ] Remove all uses of the viewOnly hook within the component and test to confirm that the component is not rendered and selectors are not called in the view only context as expected.

### Test Coverage

* Create a new file, `assets/js/util/whenInViewContext.test.js`, to test each case in the AC + the invariant conditions.

## QA Brief

* Setup Site Kit with AdSense and Analytics modules
  * Use website that has AdSense linked with Analytics
* The subtle notification informing you that AdSense and Analytics are linked should appear as before
  * The notification should not appear on the Settings screen

## Changelog entry

* N/A

**Comment by benbowler** [comment]
Created the IB. Some possible additions/questions:

- We could add something like `invariant` if the user passes invalid prop combinations like both and include and exclude list or both view only and non view only?
- I assumed we weren't using this new HOC yet in this ticket? Otherwise we could add a case/some cases to refactor as part of this work.

**Comment by tofumatt** [comment]
@benbowler Adding `invariant` checks makes sense, let's do that too 👍🏻 

Also, while it wasn't in the ACs, let's add it to at least one component so we can QA it properly 👍🏻 I've added refactoring `[GA4AdSenseLinkedNotification.js](https://github.com/google/site-kit-wp/blob/4cce042da8831b2ec8663e4d9767bc0610ae4e5a/assets/js/components/notifications/GA4AdSenseLinkedNotification.js#L115-L121)` to the ACs 🙂

**Comment by tofumatt** [comment]
Looks good to me 👍🏻 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified AdSense set up  for the website that has AdSense linked with Analytics.
- Verified AdSense set up  for the website that has AdSense not linked with Analytics.
- Verified the notice when AdSense linked with analytics and when it's not linked.
- Verified that no notification related to it appearing under settings.

<details>

**When AdSense linked with Analytics**


https://github.com/user-attachments/assets/8c058ba0-c307-4ee3-a4a7-5093f8ad828d



**When AdSense not linked with Analytics**


https://github.com/user-attachments/assets/c049edc6-5f68-41ac-b6db-5f9217975eee

![image](https://github.com/user-attachments/assets/022e9460-edf2-4611-9137-494d5126272e)


</details>
