### ISSUE TITLE
Update component styles to reference tokens

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8728]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Stylesheets should always use [design tokens](https://github.com/google/site-kit-wp/blob/5d1b1b7de7c52b230b8d3746ac81848f615ca140/assets/sass/config/_variables-mui3.scss#L139) whenever possible consistent with those used in design files

## Implementation Brief

* [x] Search style files (other than variable definitions) using color variables (e.g. `$c-violet-v-500`, `$c-site-kit-*`, `$c-neutral-`, etc) directly instead of tokens (eg. `$c-surfaces-on-background`) and update with the correct color design token.

### Test Coverage

* No changes in coverage necessary. This issue should be a refactoring - no visual changes should occur unless something was styled improperly

## QA Brief

* No QA needed; VRTs passing is sufficient for these changes.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by 10upsimon** [comment]
@aaemnnosttv during replacement of color variables with tokens, I noticed that some of the variables have tokens associate with them, and some not, while others are only defined in `_variables.scss` but not in `_variables-mui3.scss`. Here are said findings:

```
$c-neutral-n-400 // Has no color token equivalent.
$c-neutral-n-700 // Has no color token equivalent.
$c-neutral-n-66 // Has no color token equivalent.
$c-green-g-50 // Has no color token equivalent.
$c-red-600 // Only defined in assets/sass/config/_variables.scss and not in assets/sass/config/_variables-mui3.scss
$c-blue-b-500 // Has no color token equivalent.
$c-blue-b-50 // Has no color token equivalent.
$c-blue-b-600 // Has no color token equivalent.
$c-blue-b-400 // Has no color token equivalent.
$c-yellow-y-100 // Has no color token equivalent.
$c-yellow-y-600 // Has no color token equivalent.
$c-yellow-900 // Only defined in assets/sass/config/_variables.scss and not in assets/sass/config/_variables-mui3.scss
$c-violet-v-0 // Has no color token equivalent.
$c-violet-v-500 // Has no color token equivalent.
``` 

Those that had token equivalents were replaced throughout the codebase.

**Comment by tofumatt** [comment]
Moving directly to Approval as no QA is needed here.
