### ISSUE TITLE
Ads PAX Setup Flow Not Proceeding Past Billing Screen Due to `termsAndConditionsService.notify` Function Body Being Empty

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8735]
## Bug Description

The Ads PAX setup flow remains on the billing setup screen even after successful billing configuration on Ads. This is due to the `termsAndConditionsService.notify` callback function body being empty. It appears as though it needs to return _something_, i.e an empty object `{}`.

## Steps to reproduce

1. Set up Ads using PAX
2. Proceed to set up a campaign until the billing screen
3. Using the CTA in PAX, navigate to a new Ads window and proceed to set up a valid Ads billing method, i.e CC
4. Upon successful completion of billing configuration on Ads, return to PAX app on Site Kit
5. Notice that the screen remains on the billing screen and does not advance, thus the `notifyNewCampaignCreated` signal is never called

## Screenshots
N/A

## Additional Context
N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PAX Ads flow should function successfully from initial step to post billing setup, allowing the use of the Complete Setup CTA on the final step to set and save the PAX Conversion ID and External Customer ID settings.

## Implementation Brief

* [ ] Update the PAX `termsAndConditionsService` partner service at `assets/js/modules/ads/pax/services.js`
    * [ ] Edit the async function attached to the `notify` property and update the body to `return {};`
```
		termsAndConditionsService: {
			notify: async () => {
				return {};
			},
		},
```

### Test Coverage

* Update the existing test suite at `assets/js/modules/ads/pax/services.test.js`
    * Update the `termsAndConditionsService.notify` assertion and expect a return value of `{}`, not just any function.

## QA Brief

1. Set up Ads using PAX
2. Proceed to set up a campaign until the billing screen
3. Using the CTA in PAX, navigate to a new Ads window and proceed to set up a valid Ads billing method, i.e CC
4. Upon successful completion of billing configuration on Ads, return to PAX app on Site Kit
5. Validate that the billing screen disappears after a short while and that you are able to complete set up using the "Complete set up" CTA button
6. Validate that the PAX Conversion ID and External Customer ID fields are set within Settings > Ads

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Using the CTA in PAX, I navigated to a new Ads window and I proceeded to set up a valid Ads billing method. Upon successful completion of billing configuration on Ads, I return to PAX app on Site Kit and the billing screen disappears after a few seconds and I am able to complete set up using the "Complete set up" CTA button.
- The PAX Conversion ID and External Customer ID fields are set within Settings > Ads.

https://github.com/google/site-kit-wp/assets/73545194/0755e99b-eb5f-43f7-aeea-fbe7161c7d13
