### ISSUE TITLE
Address copy/formatting inconsistencies in "subtle" notifications?

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8747]
## Feature Description

At present the copy/formatting in the existent "subtle" notifications is a little inconsistent.

[`SetupSuccessSubtleNotification`](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-ads-notifications-setupsuccesssubtlenotification--ads):

![image](https://github.com/google/site-kit-wp/assets/18395600/1ee3de5d-f99e-4578-9f24-a79ea4d69026)

[`GA4AdSenseLinkedNotification`](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-notifications-subtle-ga4adsenselinkednotification--default):

![image](https://github.com/google/site-kit-wp/assets/18395600/6a98ad20-3c82-4c65-9083-797f48929fd1)

[`AudienceSegmentationSetupSuccessSubtleNotification`](
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default) ([PR Storybook instance for pre-merge access](https://google.github.io/site-kit-wp/storybook/pull/8694/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default)):

![image](https://github.com/google/site-kit-wp/assets/18395600/a1ad7dcc-ce30-4413-bc66-70406bc0a2a4)

It's not entirely clear what the outcome here should be as there's a bit of room for interpretation based on the style guide for punctuation (see below).

- We should probably adjust the `GA4AdSenseLinkedNotification` notification to remove the periods from both sentences, and use the lighter font weight for the second sentence.
- We _might_ also want to remove the period from the second sentence of the `AudienceSegmentationSetupSuccessSubtleNotification` notification, although this is arguably a "long or complex sentence" and the closing period is pretty well aligned with other sentences of a similar length elsewhere in the plugin,

### Style guide:

**_"Skip periods and unnecessary punctuation_**

_To help readers scan text, avoid using periods and other unnecessary punctuation._ 

_Avoid using periods to end single sentences, particularly in:_
_- Labels_
_- Tooltip text_
_- Bulleted lists_
_- Dialog body text_
_- Hyperlinked text_

_Use periods on:_
_- Multiple sentences_
_- Long or complex sentences, if it suits the context_
_- Any sentence followed by a link"_

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The periods within the `GA4AdSenseLinkedNotification` notification should be removed from both the sentences, and the lighter font weight should be used for the second sentence.

## Implementation Brief

* [x] Remove the periods from both sentences in the `GA4AdSenseLinkedNotification` notification.
* [ ] Update `GA4AdSenseLinkedNotification`, adding the class `className="googlesitekit-subtle-notification__secondary_description"` to the second paragraph in the notification body.

### Test Coverage

* Update VRTs to reflect the copy and style changes of the `GA4AdSenseLinkedNotification` notification.

## QA Brief

* Review each of the following subtle notifications in storybook, check the sentences don't end with full stops and the description is light font weight.
   * [`SetupSuccessSubtleNotification`](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-ads-notifications-setupsuccesssubtlenotification--ads)
   * [`GA4AdSenseLinkedNotification`](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-notifications-subtle-ga4adsenselinkednotification--default)
   * [`AudienceSegmentationSetupSuccessSubtleNotification`](
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default)

## Changelog entry

* Address formatting inconsistencies in subtle notifications by removing periods from `GA4AdSenseLinkedNotification` and `AudienceSegmentationSetupSuccessSubtleNotification`.

**Comment by jimmymadon** [comment]
@techanvil I agree with your suggestions. The period in the last`AudienceSegmentationSetupSuccessSubtleNotification` seems to be fine.

**Comment by benbowler** [comment]
It's worth considering #8725, as this will help introduce consistency is styles across SubtleNotifications (although not the copy).

**Comment by nfmohit** [comment]
AC ✅

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by hussain-t** [comment]
Hi @benbowler, the storybook stories links are broken in the QAB. Could you fix them?

**Comment by benbowler** [comment]
@hussain-t @mohitwp fixed the links.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested the below storybooks-
   [SetupSuccessSubtleNotification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-ads-notifications-setupsuccesssubtlenotification--ads)
   [GA4AdSenseLinkedNotification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-notifications-subtle-ga4adsenselinkednotification--default)
 [AudienceSegmentationSetupSuccessSubtleNotification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationsetupsuccesssubtlenotification--default)

- Verified that the sentences don't end with full stops and the description is light font weight.


<details>

![image](https://github.com/user-attachments/assets/8bc303f3-451a-40b5-8474-8c66395a7fca)

![image](https://github.com/user-attachments/assets/81ec0a7f-09a6-429c-9e78-b3897cae7bbb)

![image](https://github.com/user-attachments/assets/d2e7e2b9-0713-4233-9417-7f369d2c7aa5)

</details>
