### ISSUE TITLE
Allow PAX env to be configurable

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8754]
## Feature Description

Similar to how the SK service can be configured to use different environments, PAX has a similar configuration.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [PAX `debuggingConfig.env`](https://github.com/google/partner-ads-experience/blob/a71f7bc4339168cf254dddaaf12dfd2c90dc4729/sdk/config/config.d.ts#L62-L66) value should be configurable using a new `GOOGLESITEKIT_PAX_ENV` constant
	* If present, the value should be used if the value is one of the [allowed values](https://github.com/google/partner-ads-experience/blob/a71f7bc4339168cf254dddaaf12dfd2c90dc4729/sdk/config/config.d.ts#L114-L120), otherwise the effective value should be `PROD`

## Implementation Brief

* [ ] Update the data callback for `googlesitekit-ads-pax-config` to determine the value to pass for `env` as defined in AC

### Test Coverage

* No added coverage necessary

## QA Brief

* This issue makes it so that the environment PAX is configured to use can be configured programmatically using a new `GOOGLESITEKIT_PAX_ENV` constant
	* If set, it should control the environment set in the PAX config
	* It should only allow the two values that PAX accepts: `PROD`, or `QA_PROD`
	* If not set, or any other value given, it should use `PROD`
* The effective value can be inspected in the console when PAX is available via `_googlesitekitPAXConfig.debuggingConfig.env`

## Changelog entry

* N/A

**Comment by jimmymadon** [comment]
QA:Eng ✅ 

- Verified that when `wp-config.php` sets the env variable as per the AC, the appropriate value appears in the console.
- Verified this for all types of values: 'PROD', 'QA_PROD', a random value, FALSE and when the config var is not set.

<img width="317" alt="Screenshot 2024-05-28 at 12 34 59" src="https://github.com/google/site-kit-wp/assets/1721319/b003e95b-53ba-467d-abc8-748b865097a1">
<img width="329" alt="Screenshot 2024-05-28 at 12 35 59" src="https://github.com/google/site-kit-wp/assets/1721319/c47f4781-4392-4d7e-8a70-4072decef305">
