### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by yah0130** [google/site-kit-wp#876]
## Bug Description

after i installed the plugin i got the error on console
## Steps to reproduce

1. install plugin
2. complete the setting
3. open my site

## Screenshots

![image](https://user-images.githubusercontent.com/25168830/69116143-38be0100-0ac6-11ea-8155-402a68d2e7d8.png)

## Additional Context

 - PHP Version: 7.2.24
 - OS: MacOs
 - Browser chrome
 - Plugin Version 1.0.4
 - Device:Mac Pro 2019

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@yah0130 That script reference seems to be based on your theme. While it may appear after the Site Kit meta generator tag it's as a result of Site Kit being active on your site. For support issues going forward you can submit them on the plugins [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/).
