### ISSUE TITLE
Implement partner `userActionService` to handle new `finishAndCloseSignUpFlow` action

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8771]
## Feature Description

v1.0.8 of the PAX SDK added a new service and callback implementation to provide to fit into the latest update of its congratulations.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`userActionService`](https://github.com/google/partner-ads-experience/blob/a71f7bc4339168cf254dddaaf12dfd2c90dc4729/sdk/service/partner/user-action-service.d.ts) should be added to the services provided to PAX on launch, with the ability to provide an optional function to be called by the `finishAndCloseSignUpFlow` implementation
* The PAX setup should be updated to provide call its `finishSetup` as this function to handle the setup-complete navigation
* PAX should no longer be hidden once the campaign creation is completed as the user will see the congrats screen now instead of the PAX dashboard

## Implementation Brief

* [ ] Using https://github.com/google/site-kit-wp/pull/8750 as a starting point, cherry pick or otherwise start a new PR against develop
* [ ] Additionally, update/move the `submitChanges` call to happen in the `onCampaignCreated` callback – navigation to the dashboard should only happen in response to the `finishAndCloseSignUpFlow` call though
* [ ] Fix the `invariant` error (`url must be a valid URI`) which is likely due to an unresolved value passed to `navigateTo` by `finishSetup`

### Test Coverage

* Update coverage for `services` respectively

## QA Brief

* This primarily integrates new behavior in PAX where the final "congrats" screen is shown with a "Close" button. Clicking this should navigate to the related success screen on the SK dashboard.
* There are some substantial other changes made here so generally checking for regressions in PAX is good
* Currently, the module may not be connected on finishing the setup as we're waiting a related change on the PAX side that will fire the campaign creation callback consistently (currently it only happens once for new accounts rather than all new campaigns). This change is expected to land on 5/31 so check with PAX team to confirm
* Be sure to test using the QA_PROD env or you will not see the expected result

## Changelog entry

* Improve Partner Ads Experience onboarding flow.

**Comment by eclarke1** [comment]
This relates to the following bug bash issue https://app.asana.com/0/1207337163922896/1207399942380331

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The final review/congrats screen is shown with a "Close" button. 
- Clicking this navigates to the SK dashboard with the successful notification. 
- I also checked and the modue was successfully connected. 
- Tested on the QA_PROD env. 

https://github.com/google/site-kit-wp/assets/73545194/1c53ecc5-9bb9-49e2-b24d-1c47eb8eccbd

![image](https://github.com/google/site-kit-wp/assets/73545194/7ab85a23-54c6-4ee3-81eb-46e9b7bc00c3)
