### ISSUE TITLE
Fix Failing Jest Tests

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8775]
## Bug Description

- Currently the Jest tests are failing for all PR's into `develop` and `main` with the following error:

```
FAIL assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js (9.753 s)
  ● MetricsSelectionPanel › Header › should display a settings link to edit personalized goals
    expect(jest.fn()).not.toHaveErrored(expected)
    Expected mock function not to be called but it was called with:
    ["Warning: An update to %s inside a test was not wrapped in act(...).·
    When testing, code that causes React state updates should be wrapped into act(...):·
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */·
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act%s", "MetricItems", "
        in MetricItems (created by MetricsSelectionPanel)
        in section (created by FocusTrap)
        in FocusTrap (created by SideSheet)
        in Portal (created by SideSheet)
        in SideSheet (created by SelectionPanel)
        in SelectionPanel (created by MetricsSelectionPanel)
        in MetricsSelectionPanel
        in Router (created by Wrapper)
        in Wrapper"],["Warning: An update to %s inside a test was not wrapped in act(...).·
    When testing, code that causes React state updates should be wrapped into act(...):·
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */·
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act%s", "MetricItems", "
        in MetricItems (created by MetricsSelectionPanel)
        in section (created by FocusTrap)
        in FocusTrap (created by SideSheet)
        in Portal (created by SideSheet)
        in SideSheet (created by SelectionPanel)
        in SelectionPanel (created by MetricsSelectionPanel)
        in MetricsSelectionPanel
        in Router (created by Wrapper)
        in Wrapper"]
      at Object.assertExpectedCalls (node_modules/@wordpress/jest-preset-default/node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:36:4)
```

A fix should be applied to said test to prevent this error.

## Steps to reproduce

1. Run tests locally or trigger tests via a PR
2. You can choose to target just the erroring test: `npm run test:js -- 
 ssets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js`
3. Observe the Jest error as reported in the bug description

## Additional Context

N/A, affects all current and new PR's

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Jest tests should have a 100% pass rate

## Implementation Brief

**NOTE TO REVIEWER:** There is already a PR linked to this issue, if IB is approved this can go straight to CR and be QA:ENG'd as well

* [ ] Update `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js`
    * [ ] Targeting the test at `npm run test:js -- assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js`, apply the following changes:
        * [ ] Add the following line below the existing `await waitForRegistry();` call:
```
await act( waitForDefaultTimeouts );
```

### Test Coverage

* Update the failing test at `assets/js/components/KeyMetrics/MetricsSelectionPanel/index.test.js`

## QA Brief (QA:ENG)

* Validate that all Jest tests pass.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
All looks good. IB approved, PR is approved and merged. Moving to Approval.
