### ISSUE TITLE
Prevent Tracking of Conversion Events if Enhanced Conversion Tracking Toggle State is False

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8777]
## Feature Description

With the inclusion of the physical conversion tracking toggle introduced to the codebase (within Ads and GA4 settings edit areas), some additional logic needs to be introduced to the `Conversion_Tracking` class that prevents the event providers from being registered (and firing events) if the state of Conversion Tracking is `false`. 

This check already exists within the `Conversion_Tracking_Settings` class and should be a simple conditional check prior to event providers script enqueue in the main `Conversion_Tracking` class.
 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the "Enable enhanced conversion tracking" toggle is toggled _off_, conversion events should not be fired by their respective event providers within the `Conversion_Tracking` folder/namespace.

## Implementation Brief

* [ ] Update the `Conversion_Tracking` class at `includes/Core/Conversion_Tracking/Conversion_Tracking.php`
    * [ ] Add a new conditional check within the `register()` method immediately before the `wp_enqueue_scripts` `add_action` call:
```
        if ( ! $this->conversion_tracking_settings->is_conversion_tracking_enabled() ) {
            return;
        }
```

### Test Coverage

* Update the existing test coverage in `tests/phpunit/integration/Core/Conversion_Tracking/Conversion_TrackingTest.php` to include a test case that asserts that event provider scripts are not enqueued if tracking is disabled.

## QA Brief

* Set up Site Kit with the Ads module 
* Enable the `conversionInfra` feature flag in the tester plugin
* Navigate to Site Kit > Settings > Ads and enable Enhanced conversion tracking via the toggle
* Install 1 of the 6 plugins identified for conversion event tracking, i.e Contact Form 7
* Follow the steps to fire a conversion event for said chosen plugin 
* Validate that the event is fired to the Ads (and any/all other) gtag on the page
* Disable Enhanced conversion tracking via Ads settings
* Repeat the steps to test if the conversion event fires, it should not

## Changelog entry

* Update conversion tracking JS to be controlled by new setting.

**Comment by zutigrm** [comment]
Thanks @10upsimon IB LGTM ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that the event is fired to the Ads (and any/all other) gtag on the page when toggle is enabled.
- Verified that event is not getting fired to the Ads (and any/all other) gtag on the page when toggle is enabled.
- Verified when only Ads module is connected one event is getting track.
- Verified when both Ads and Analytics module are connected then 2 events are getting track
- Verified when only Analytics module is connected one event is getting track


<details>

**Ads module**

**_Enabled Toggle_**

![image](https://github.com/google/site-kit-wp/assets/94359491/fe18c0b6-a883-4a93-8be7-55f26e6bdd3e)

![image](https://github.com/google/site-kit-wp/assets/94359491/61e6e227-7cc4-4024-8077-8a0f76c98dc2)


https://github.com/google/site-kit-wp/assets/94359491/97ecaf8b-a264-40f6-a91f-78fd240b86f1


_Both Ads and Analytics module are connected_

![image](https://github.com/google/site-kit-wp/assets/94359491/693920f3-00ba-4877-a8ad-e1faa233dffd)

![image](https://github.com/google/site-kit-wp/assets/94359491/4649b9ef-b844-42e8-bf5e-ac44c323e518)

https://github.com/google/site-kit-wp/assets/94359491/144c5af3-9d08-4145-9ca1-c610b352732e


_When only analytics module is connected_

![image](https://github.com/google/site-kit-wp/assets/94359491/4f865daf-a48a-4e10-b550-93766e7c3384)


https://github.com/google/site-kit-wp/assets/94359491/9076f957-e45f-4f47-a220-78d3bbaad5d0



**_Disable Toggle_**

![image](https://github.com/google/site-kit-wp/assets/94359491/a2bd5857-9ff6-434c-a8f6-3a20d453a919)


https://github.com/google/site-kit-wp/assets/94359491/a320cc0f-9959-4395-be44-14e6aac06325


_Both Ads and Analytics module are connected_

https://github.com/google/site-kit-wp/assets/94359491/ecc1b0c1-0a23-4b02-b518-b6d61912d59b


</details>
