### ISSUE TITLE
Add `rrmModule` feature flag

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8782]
## Feature Description

The `rrmModule` feature flag should be added to Site Kit as a prerequisite for the Reader Revenue Manager feature development.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The `rrmModule` feature flag should be added to Site Kit.

## Implementation Brief

* [x] Add the `'rrmModule'` feature flag to `feature-flags.json`

### Test Coverage

* No new tests needed.

## QA Brief

1. Make sure "Site Kit by Google Tester" plugin is installed and activated.
2. Go to "Site Kit > Tester Settings", make sure `rrmModule` flag is available under "Enabled feature flags".

The `rrmModule` feature flag should appear in the list of enabled features.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Looks good; moving this right to the backlog since it's straightforward 🙂

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Reviewed this and results are as expected.
The rrmModule feature flag appears in the list of enabled features.

- Tested on the site kit tester page (tested also saving with checkbox checked and unchecked)
- Tested on the admin bar dropdown
- Tested at Site health section

Moving this ticket to approval.

<Details>
<img width="1117" alt="Screenshot 2024-06-06 at 12 21 04" src="https://github.com/google/site-kit-wp/assets/125576926/4f5df1c0-9efe-4995-9ee8-6ff50e0937f7">
<img width="1128" alt="Screenshot 2024-06-06 at 12 21 48" src="https://github.com/google/site-kit-wp/assets/125576926/bf9afabe-fa7a-4cee-852e-6bc754b10bd7">
<img width="371" alt="Screenshot 2024-06-06 at 12 21 53" src="https://github.com/google/site-kit-wp/assets/125576926/c3eb869d-3933-49d6-a6bf-355074b65b23">
<img width="1115" alt="Screenshot 2024-06-06 at 12 22 16" src="https://github.com/google/site-kit-wp/assets/125576926/b7b37ce6-6525-4d51-b267-e73413567fa7">

</Details>
