### ISSUE TITLE
Install the SwG client API library

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8783]
## Feature Description

The client library for the `subscribewithgoogle` API that is needed by Reader Revenue Manager is not available via the [googleapis/google-api-php-client-services](https://github.com/googleapis/google-api-php-client-services) package. As a temporary workaround, this client library bindings should be generated and installed for PHP which we can later remove once available in the official client services.

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.ty4ti1aiqef1).
- See [#5650](https://github.com/google/site-kit-wp/issues/5650) which was a similar effort for the former Thank with Google epic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PHP client library files for the `subscribewithgoogle` v1 API should be generated and added as a new Composer package under `/packages/apiclient-services-subscribewithgoogle`.
	* A single `SubscribewithGoogle.php` will be generated which can live in the root.
	* The package name should be `google/apiclient-services-subscribewithgoogle`.
* The plugin should be updated to require the new package as non-dev Composer dependency.
* The added client library files should be prefixed just like any other client service, with the production code using the generated prefixed versions under `/third-party/google/`.

## Implementation Brief

- [x] Generate client library file `SubscribewithGoogle.php` under the path in the AC and create the necessary `composer.json` in the same directory. Refer to the generator [readme](https://github.com/googleapis/google-api-php-client-services/tree/main/generator).
- [x] Add a new definition under the main `composer.json` for the plugin to define a new `path` type Composer repository for the new package. This can go next to the current `packages/apiclient-services-adsenselinks` definition.
- [x] Update PHP Scoper configuration to include the added package.

**Note:** Refer [this PR](https://github.com/google/site-kit-wp/pull/5651) from "Thank with Google" which has similar implementation.

### Test coverage

* Add a basic test ensuring the new prefixed dependencies are present

## QA Brief

* N/A – automated tests should be sufficient for this

## Changelog entry

* Add the Subscribe with Google PHP client library.

**Comment by kuasha420** [comment]
AC :white_check_mark:

**Comment by ankitrox** [comment]
As per my conversation with @aaemnnosttv , the generator is part of the same (maintained) client services repo, thus this is what we should use for the generation.

@aaemnnosttv I am assigning this to you for your confirmation. Once you get a chance to look into this, please confirm if we can move this ticket to CR.

Thanks

**Comment by techanvil** [comment]
As discussed on Slack the approach has been confirmed to be correct. I've given the PR another once-over with this in mind, and it's back with @ankitrox with a few more comments.

**Comment by ankitrox** [comment]
Thank you @techanvil .

I've made the requested changes. Assigning this to you for re-review.

**Comment by techanvil** [comment]
As per the QAB, there's no need for a QA stage for this. It's been CR'd, merged and moved straight to Approval.
