### ISSUE TITLE
Add JS entry point for RRM

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8786]
## Feature Description

A JavaScript entry point for Reader Revenue Manager should be added which should include its module and datastore registration. The data store will be named `modules/reader-revenue-manager`. This should also include adding the `submitChanges` & `validateCanSubmitChanges` actions. The module registration should also include a `checkRequirements` property to ensure the site is on HTTPS as a requirement for module activation.

This issue should also be responsible for enqueuing the JS asset to the `Modules\Reader_Revenue_Manager` class using the `setup_assets` method.

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.8rm6e1wjm4im).
- See [#5365](https://github.com/google/site-kit-wp/issues/5365) which was a similar effort for the former Thank with Google epic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Module and datastore registration should be implemented for the Reader Revenue Manager module in a new JavaScript entry point.
* The name of the datastore should be `modules/reader-revenue-manager`.
* The module icon should be exported from [the Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=2-2385&t=uh0IlFQoKec578C6-4).
* The module should have placeholder empty components added for setup and settings, such as `SettingsEdit`, `SettingsView`, and `SetupMain`.
* The data store should have basic actions implemented, such as `submitChanges`, `rollbackChanges`, and `validateCanSubmitChanges`.
* It should be ensured that the module can be activated only if the site is on HTTPS.
	* The message when the activation is disabled should be: "The site should use HTTPS to set up Reader Revenue Manager".
* The new JS asset should be enqueued in the module class for Reader Revenue Manager (being implemented in [#8785](https://github.com/google/site-kit-wp/issues/8785)).
* A "_New_" badge should be added for the module in Site Kit Settings.

**Note:** It is not necessary to define module features (that show up in the module disconnection dialog) as part of this issue. Those will be implemented as part of [#8845](https://github.com/google/site-kit-wp/issues/8845).

## Implementation Brief

- [x] Create a new module `reader-revenue-manager` inside `assets/js/module/`.
  - [x] Create `assets/js/module/reader-revenue-manager/datastore/base.js`. This will be a base store.
    - [ ] Create placeholder components in
    - [x] Call the `Modules.createModuleStore`.
      - [x] Slug should be `reader-revenue-manager`.
      - [x] Store name must be `reader-revenue-manager`.
      - [x] Make sure to pass `validateCanSubmitChanges` described below.
    - [x] Create placeholder components `SettingsEdit` and `SettingsView` inside `assets/js/module/reader-revenue-manager/components/settings/`
    - [x] Create placeholder components `SetupMain` inside `assets/js/module/reader-revenue-manager/components/setup/`
  - [x] Create `assets/js/module/reader-revenue-manager/index.js`. Use `registerModule` to register the module. Take [this reference](https://github.com/google/site-kit-wp/blob/cefbb45445ad99a548d7ab555d2665d588b911eb/assets/js/modules/tagmanager/index.js#L34-L44) on how it can be registered.
    - [x] Pass `checkRequirements` function to `registerModule`. In `checkRequirements` function verify that site is using SSL which can be done by using `getHomeURL` selector from `CORE_SITE` store.
    - [x] Throw from  `checkRequirements` with `NON_HTTPS_SITE` error code and the message defined in the ACs as message when site is not https.
      - [x] This will ensure that the setup is disabled and the correct message is shown when site is not HTTPS. 
  - [x] Create `assets/js/module/reader-revenue-manager/datastore/settings.js`
    - [x] Create a function `validateCanSubmitChanges` and validate the following.
      - [x] Publication ID is not empty and is string.
      - [x] Publication ID belongs to one of the publication IDs that we received from `getPublications` selector.
      - [x] Use `Invariant` in case of error.
    - [x] As of now, we won't need separate `submitChanges` and `rollbackChanges` action as those will automatically be created by `create-settings-store` via `Modules.createModuleStore`.
- [x] In `webpack/modules.config.js`, add following config. We need 
```js
    'googlesitekit-modules-reader-revenue-manager':
        './assets/js/googlesitekit-modules-reader-revenue-manager.js',
```
  - [x] The bundled file (generated assets) needs to be enqueued from within `Modules\Reader_Revenue_Manager` class using `setup_assets` function. The class is being implemented in #8785.

- [x] In a new file `assets/js/components/settings/constants.js`, create a new constant `NEW_MODULES` which should be array `[ 'ads', 'reader-revenue-manager' ]`
  - [x] In `assets/js/components/settings/SetupModule.js`, update [this check](https://github.com/google/site-kit-wp/blob/3b3ebf91cdb01a0670e30a5cfd2afba0778a9a11/assets/js/components/settings/SetupModule.js#L118) to check if module slug is present in `NEW_MODULES` constant created above, in order to display "New" badge.
  - [x] Do the same step as above in `assets/js/components/settings/SettingsActiveModule/Header.js`.

### Test Coverage

1. Add tests for the data store modules.
2. Add tests for the main module file.
3. Add test for non-HTTPS scheme and ensure that it adds warning.

## QA Brief

* Most of the changes can be verified during the code review process.
* Enable the `rrmModule` feature flag via the tester plugin.
* Go to the Site Kit Settings page -> connect-more-services tab and ensure the "Reader Revenue Manager" module is available in the modules grid.
* Note that there is no Figma design for the above. We just need to ensure it's available in the Connect More Services.
* Verify in an `HTTPS` protocol-enabled site that `Set up Reader Revenue Manager` is clickable.
* Go through the setup flow.
* Click the `Cancel` button as we haven't implemented the setup form. It will take us to the "Connected Services" screen.
* Verify the RRM module is available in the "Connected Services".
* Verify in an `HTTP` site that `Set up Reader Revenue Manager` is disabled and shouldn't be able to setup.
* Verify the `The site should use HTTPS to set up Reader Revenue Manager` warning should be displayed.
* Disable the `rrmModule` feature flag and verify the "Reader Revenue Manager" module is unavailable in the Connect More Services.
* Go to the Storybook and verify the following stories are available:
   * `Modules > ReaderRevenueManager > Setup > SetupMain`
   * `Modules > ReaderRevenueManager > Settings > SettingsEdit`
   * `Modules > ReaderRevenueManager > Settings > SettingsView`
* The structure and styles are yet to be implemented for the above stories in the upcoming tickets.

## Changelog entry

* Add Reader Revenue Module setup and settings view foundations.

**Comment by kuasha420** [comment]
Hi @nfmohit, AC LGTM, just one part I'm not sure about. In TwG case, we didn't surface the module at all when the site was not HTTPS, but here we're only blocking the user from activating the module. Is this correct? If yes, I'm assuming it will look like the Ads/AdSense module when Ad Blocker is active, and we'll need a warning message to display. 

Let me know what you think! Cheers.

**Comment by nfmohit** [comment]
Hi @kuasha420. That is the correct behaviour according to the design doc. I've added a warning message.

**Comment by kuasha420** [comment]
@nfmohit Perfect. AC :white_check_mark:

**Comment by kuasha420** [comment]
Hi @ankitrox, IB is looking good. Couple of points. 

1. The new module asset needs to be added to the bundling infra. ie. WebPack in `webpack/modules.config.js`. 
2. The Asset needs to be enqueued from the `Modules\Reader_Revenue_Manager` class using `setup_assets` function. 

Cheers.

**Comment by ankitrox** [comment]
Thank you @kuasha420 . I've included those two points along with the missing "New Badge" pointer.

Over to you for re-review.

Thanks again!

**Comment by kuasha420** [comment]
Thanks  @ankitrox. 

Great point about the `New` badge. Looks like we need to do the same check in `assets/js/components/settings/SettingsActiveModule/Header.js` as well. Also, I think instead of checking for the new slugs one by one, we should do something similar for how it's done for the `EXPERIMENTAL_MODULES`, by defining a new constant `NEW_MODULES` and using that. 

Cheers.

**Comment by ankitrox** [comment]
Thank you @kuasha420 . I've updated the IB.

**Comment by kuasha420** [comment]
@ankitrox Thanks. I made a small change to the path where the  `NEW_MODULES` constant should be stored,  otherwise this is LGTM. 

IB :white_check_mark:

**Comment by ankitrox** [comment]
Thanks @kuasha420 . I've updated the IB.

**Comment by kuasha420** [comment]
Thank you @ankitrox for all the work here. I've made some slight edits regarding `receiveCheckRequirementsError`, turns out we can just throw from the `checkRequirements` function with the correct message, and it will be rendered in the right place. :tada: Everything else is :+1: 

IB :green_apple:

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @hussain-t , I've tested this and here's my main feedback:

QAB: 
`Click the Cancel button as we haven't implemented the setup form. It will take us to the "Connected Services" screen.`

It says after cancel, it would take us back to "Connected Services" but currently we go back to the SK Dashboard with an error message.
Also, if I then go to the "Connected Services" page, there will be an error there as well.

<Details>
Error after clicking 'Cancel'
<img width="1237" alt="Screenshot 2024-07-04 at 17 42 59" src="https://github.com/google/site-kit-wp/assets/125576926/79d3592c-2fcd-4917-b2a9-433c167af38f">

Error showing when we are at the "Connected Services' page.
<img width="1241" alt="Screenshot 2024-07-04 at 17 44 53" src="https://github.com/google/site-kit-wp/assets/125576926/e8128175-4d83-49a7-a72e-aec5429a221e">

</Details>

**Comment by hussain-t** [comment]
@kelvinballoo, you have canceled the OAuth flow (clicked the OAuth flow cancel button). You should click the setup flow cancel button after completing the OAuth flow. Please refer to the screenshot below:

![Screenshot 2024-07-04 at 10 02 37 PM](https://github.com/google/site-kit-wp/assets/24408261/c3607269-3b30-4100-91f7-fb8f4184f4ca)

**Comment by kelvinballoo** [comment]
### QA ✅ 

Thanks @hussain-t . This ticket has been tested good as follows.

- Under Site Kit Settings page -> connect-more-services tab and ensure the "Reader Revenue Manager" module is available in the modules grid with a 'New' badge.  Under HTTPS protocol-enabled site , the Set up Reader Revenue Manager is clickable.
   <Details>
   <img width="1061" alt="Screenshot 2024-07-04 at 20 51 52" src="https://github.com/google/site-kit-wp/assets/125576926/e1e2ad0c-ee97-4627-8957-9eb1225ec45e">
   </Details>
   
- Clicking the Cancel button after the auth setup flow, will take us to the "Connected Services" screen. The RRM module is available in the "Connected Services".
   <Details>
   <img width="1163" alt="Screenshot 2024-07-04 at 20 43 30" src="https://github.com/google/site-kit-wp/assets/125576926/ce73c0e2-5593-436f-b59a-4b9b68a44fa4">

   </Details>

- With an HTTP site, the Set up Reader Revenue Manager is disabled and cannot be set up. It would display a warning : "**The site should use HTTPS to set up Reader Revenue Manager**"
   <Details>
   <img width="1185" alt="Screenshot 2024-07-04 at 20 20 29" src="https://github.com/google/site-kit-wp/assets/125576926/5daba79a-6355-48a1-8b5a-c74c140c4ddd">

   </Details>

- Once the rrmModule feature flag is disabled, the "Reader Revenue Manager" module is unavailable in the Connect More Services.

- Under [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-setup-setupmain--default), the following stories are available:
   Modules > ReaderRevenueManager > Setup > SetupMain
   Modules > ReaderRevenueManager > Settings > SettingsEdit
   Modules > ReaderRevenueManager > Settings > SettingsView"
   <Details>
   <img width="404" alt="Screenshot 2024-07-04 at 18 07 06" src="https://github.com/google/site-kit-wp/assets/125576926/52fbfb89-23b8-4582-bfbe-c65612bcd3d7">

   </Details>

Moving ticket to Approval.

**Comment by aaemnnosttv** [comment]
> The site should use HTTPS to set up Reader Revenue Manager

@nfmohit is this defined somewhere? I think we should be more specific that it is a requirement since the module is also prevented from being activated in this scenario. Not a blocking detail yet, but just thought I'd ask.

**Comment by nfmohit** [comment]
> > The site should use HTTPS to set up Reader Revenue Manager
> 
> @nfmohit is this defined somewhere? I think we should be more specific that it is a requirement since the module is also prevented from being activated in this scenario. Not a blocking detail yet, but just thought I'd ask.

This is something I added while defining the ACs for this issue with an assumption that this may change later as part of a final language/copy check during the bug bash. I now realise that I should've confirmed this with you and/or Andrey, sorry! Would you like to propose an alternative copy here for which I can make a quick follow-up PR or issue?

**Comment by nfmohit** [comment]
> > The site should use HTTPS to set up Reader Revenue Manager
> 
> @nfmohit is this defined somewhere? I think we should be more specific that it is a requirement since the module is also prevented from being activated in this scenario. Not a blocking detail yet, but just thought I'd ask.

Hi @aaemnnosttv ! This is something I added while defining the ACs for this issue with an assumption that this may change later as part of a final language/copy check during the bug bash. I now realise that I should've confirmed this with you and/or Andrey, sorry! Would you like to propose an alternative copy here for which I can make a quick follow-up PR or issue?
