### ISSUE TITLE
Optimize `useInViewSelect`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8789]
## Feature Description

In #4096 we added `useInViewSelect`, a decorated version of the `useSelect` hook we use liberally throughout our components.

There are a few details which were missed in the initial implementation which should be revisited to avoid unnecessary performance hits.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `mapSelect` should be removed from the dependency array of `mapSelectCallback`. This function is expected to be defined inline (i.e. new every render) so including it undoes the optimization provided by `useCallback` and `useSelect` internally (see next point) https://github.com/google/site-kit-wp/blob/0ea003eb33a2bfd79846ac0c227432429532f4c5/assets/js/hooks/useInViewSelect.js#L44
* The not-in-view variant of `mapSelectCallback` should be extracted to a stable definition outside of the hook (as originally defined). This avoids calling it unnecessarily as this function will be new on every render, thus will always be called here https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/components/use-select/index.js#L93C8-L93C23

## Implementation Brief

* [x] Update `mapSelectCallback`'s dependency array to use the provided `deps`. The necessary `eslint-disable-next-line` [is explained in the latest version of `useSelect`](https://github.com/WordPress/gutenberg/blob/e5d2a5ab47d8985b2d4a3439c2dcc8836c4c60bb/packages/data/src/components/use-select/index.js#L224-L227) which we could copy here as well
* [x] Replace the `() => undefined` function to a stable named function outside of the component

### Test Coverage

* Adding a test to cover the expected number of invocations of the given `mapSelect` function across renders in and out of view

## QA Brief

* Setup Site Kit and all modules
* Do overall smoke testing to verify that all widgets work as expected/before - Site Kit dashboard and entity dashboard, and widgets on WP dashboard

## Changelog entry

* Update the `useInViewSelect` hook to use dependencies.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified all widgets on main and entity dashboard.
- Verified WP dashboard widgets.
- Verified site kit bar in front end.
- Verified all widgets are working as expected.

**Comment by aaemnnosttv** [comment]
I've opened a very small follow up here to address one detail missed which resulted in a larger change here.

**Comment by nfmohit** [comment]
Update: The [follow-up PR](https://github.com/google/site-kit-wp/pull/9009) has been merged.

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit!
