### ISSUE TITLE
Release automation uses incorrect destination

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8790]
## Bug Description

The release automation we have in place currently sits within our `zips` workflow which builds zip files for PRs and the latest builds for our main branches. The zip file is structured the way WP expects: including the plugin's directory, however the release does not account for this so it ends up adding the files in the wrong (nested) destination.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `publish-to-wporg` GHA job should be updated so that it sources the contents to deploy from the unzipped built plugin, without including the root `google-site-kit` directory

## Implementation Brief

* [ ] Update the `action-wordpress-plugin-deploy` step to include the [`BUILD_DIR`](https://github.com/10up/action-wordpress-plugin-deploy/tree/2.2.2/?tab=readme-ov-file#optional-environment-variables) env variable, defined to target `./google-site-kit` (the root directory). This should set the [source that is synchronized into trunk](https://github.com/10up/action-wordpress-plugin-deploy/blob/abb939a0d0bfd01063e8d1933833209201557381/deploy.sh#L147-L150) to use the contents rather than the [more complicated logic based on `.distignore` or `.gitattributes`](https://github.com/10up/action-wordpress-plugin-deploy/blob/abb939a0d0bfd01063e8d1933833209201557381/deploy.sh#L92-L146)
* [ ] The line to create a `.distignore` in the Extract step can then be removed

### Test Coverage

* No changes as actions don't have tests

## QA Brief

* N/A

This will need to be tested by running the release automation task, I don't see another way it can be tested 🤔 

## Changelog entry

* N/A

**Comment by binnieshah** [comment]
@aaemnnosttv could we get an estimate for this one, I am trying to see if we can get this into the next sprint. Thanks

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
Moving to Approval since there is nothing to test.

**Comment by aaemnnosttv** [comment]
[Tested with a dry run here](https://github.com/google/site-kit-wp/actions/runs/10100015862/job/27930675161) and looks great 🎉
