### ISSUE TITLE
Implement RRM `GET:publications` REST endpoint

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8791]
## Feature Description

The Reader Revenue Manager module should include a `GET:publications` endpoint that will return all available publications which are available for the current site using the “https://subscribewithgoogle.googleapis.com/v1/publications” SwG API endpoint.

This issue should also be responsible for implementing the `Module_With_Service_Entity` interface and the `check_service_entity_access` method in the `Modules\Reader_Revenue_Manager` class to ensure that the current user has access to the `subscribewithgoogle` Google service, thus preventing non-owner admins not having access to the publication make any potential changes to the module.

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.e35fxncujtip).
- See [#5671](https://github.com/google/site-kit-wp/issues/5671) which was a related effort for the former Thank with Google epic.
- This endpoint will be quite similar (if not the same) to the [TwG `GET:publications` endpoint](https://github.com/google/site-kit-wp/blob/1.89.0/includes/Modules/Thank_With_Google.php).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `GET:publications` endpoint should be implemented in the Reader Revenue Manager module which should return all available publications which are available for the current site.
* The endpoint should call the “https://subscribewithgoogle.googleapis.com/v1/publications” SwG API endpoint to get publication information.
* It should use the `filter` parameter of the SwG API endpoint to return publications relevant to the current site only, based on the following criteria:
	* The current Search Console property ID should be used, with the relevant permutations (`http` and `https` for URLs, `www` and `non-www` in any case).
		* The `Core\Util\URL::permute_site_url()` & `Core\Util\URL::permute_site_hosts()` methods should be used to include permutations for Punycode and Unicode variations.
	* If it is a domain property (`sc-domain:…`), the filter parameter should use permutations of the domain following `sc-domain:` and be either:
		* `domain = "example.com"` OR
		* `domain = "www.example.com”`
	* If it is a URL property (`http://…` or `https://…`), the filter parameter should use permutations of the full URL and be either:
		* `site_url = "https://example.com/"` OR
		* `site_url = "http://example.com/"` OR
		* `site_url = "https://www.example.com/"` OR
		* `site_url = "http://www.example.com/"`
* The Reader Revenue Manager module class (being implemented in [#8785](https://github.com/google/site-kit-wp/issues/8785)) should implement the `Module_With_Service_Entity` interface and the `check_service_entity_access` method to ensure that the current user has access to the `subscribewithgoogle` Google service, thus preventing non-owner admins not having access to the publication make any potential changes to the module.

## Implementation Brief

_Note: This is the same REST endpoint that was implemented in the former Thank with Google module, which can be looked at by going back into Git history [here](https://github.com/google/site-kit-wp/blob/1.89.0/includes/Modules/Thank_With_Google.php)._

Make the following additions to the `Modules/Reader_Revenue_Manager` class introduced via https://github.com/google/site-kit-wp/issues/8785.

* [x] Implement the `setup_services()` method, the returned array should include a `subscribewithgoogle` service which is an instance of the `Google_Service_SubscribewithGoogle` class introduced via #8783.
* [x] Ensure the class implements the `Module_With_Service_Entity` interface.
  * In the `check_service_entity_access()` implementation, make a `$subscribewithgoogle->publications->listPublications()` request with a `pageSize` of `1`.
  * If this succeeds, return `true`.
  * Follow the example of [`Analytics_4::check_service_entity_access()`](https://github.com/google/site-kit-wp/blob/cefbb45445ad99a548d7ab555d2665d588b911eb/includes/Modules/Analytics_4.php#L2147-L2165) to ensure the method returns `false` if a `403` is returned, and maps any other exception to an error.
* [x] Implement `get_datapoint_definitions()` to return an array containing the definition of `GET:publications`, which should depend on the `subscribewithgoogle` service.
* [x] Implement `create_data_request()`. This should make a `$subscribewithgoogle->publications->listPublications()` request with the `filter` option set as per the AC. See the old [`Thank_With_Google` implementation](https://github.com/google/site-kit-wp/blob/14ffc0259c770b43de3079cabd14d203f6459550/includes/Modules/Thank_With_Google.php#L379C21-L417) for how to do this.
* [x] Implement `parse_data_response()` to return `$response->getPublications()` as an indexed array.

### Test Coverage

* Add PHPUnit test coverage for the service entity access and the new endpoint.

**Create account in publisher center**

* Go to https://publishercenter.google.com/ login/register using google account.
* It will open a the new modal to add publication details as below.

<img width="632" alt="Screenshot 2024-07-05 at 5 26 39 PM" src="https://github.com/google/site-kit-wp/assets/1442637/1f0bf989-b872-4f4b-8ffc-e09612995156">

* Once successfully created, it will create an publication ID, which should be seen in the URL as query parameter. Example `https://publishercenter.google.com/?publication=CAow6J6vDA`

## QA Brief

* Turn on the `rrmModule` feature flag.
* Go to Site Kit settings and activate the Reader Revenue Manager module.
* In the Site Kit dashboard, run the following command in browser console. Make sure that request succeeds with 200 response and returns an array of publications that your Google account has at the publisher center (https://publishercenter.google.com/) that are associated with the current site URL.
	* You may create new publication(s) with the current site URL to see this array populated.

```js
googlesitekit.api.get( 'modules', 'reader-revenue-manager', 'publications', undefined, {
    useCache: false,
} )
```

## Changelog entry

* Add Reader Revenue Manager API functionality to retrieve publications.

**Comment by kuasha420** [comment]
AC :white_check_mark:

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @ankitrox , 
I've activated the rrm flag and module and ran the script.
I hit an error when I ran the script in Browser console. The details section shows the error. 
I am sending you the credentials to my test site as well for your verification.
```
googlesitekit.api.get( 'modules', 'reader-revenue-manager', 'publications', undefined, {
    useCache: false,
} )
```

<Details>
<img width="1254" alt="Screenshot 2024-07-08 at 17 55 34" src="https://github.com/google/site-kit-wp/assets/125576926/374b4ff2-0eac-410f-b604-75e9f3d6e22c">

</Details>

**Comment by ankitrox** [comment]
@kelvinballoo As per this thread and conversation on [slack](https://10up.slack.com/archives/C077DB69US2/p1720445926166999), you will have to run this code to provide the necessary permission for endpoint to work.

```js
googlesitekit.data.dispatch( 'core/user' ).setPermissionScopeError( {
    code: 'missing_required_scopes',
    data: {
        status: 403,
        scopes: [ 'https://www.googleapis.com/auth/subscribewithgoogle.publications.readonly' ],
        skipModal: true,
        skipDefaultErrorNotifications: true,
        redirectURL: location.href,
    },
} );
```

Please run this code in browser console and then the given snippet in QAB.

Can you please test this and let me know if it works?

Thanks

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @ankitrox , I did the above and here are the outcomes:

- I executed the script you mentioned and I would routed to grant some access. After that, I executed the QAB script. It executed fine with status 200 but there was no details returned about the publication. The array was [0]
   <Details>
   Array is [0]
      <img width="1252" alt="Screenshot 2024-07-09 at 13 41 56" src="https://github.com/google/site-kit-wp/assets/125576926/e23a3f36-9757-4307-8d49-7f202f994e93">

   Status is 200 (though the response tab is blank:
      <img width="1248" alt="Screenshot 2024-07-09 at 13 42 32" src="https://github.com/google/site-kit-wp/assets/125576926/d9948548-204c-4354-a601-140e0e730c48">
      <img width="1248" alt="Screenshot 2024-07-09 at 13 42 40" src="https://github.com/google/site-kit-wp/assets/125576926/ff43a6c5-df69-4b34-b403-bad6ea07108d">

</Details>

- Checking on publisher central, I do have the publication with the correct URL and it's verified as well
   <Details>
   <img width="1236" alt="Screenshot 2024-07-09 at 13 42 15" src="https://github.com/google/site-kit-wp/assets/125576926/cf0729e7-9356-4f6e-a13b-91fa32c9b390">

   </Details>

Let me know if I missed any step. Happy to jump on a call to clarify anything if that's faster.

**Comment by ankitrox** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d633a03fe5d1fdf6a568860e831c18e31ddc707/Screenshot%202024-07-09%20at%205.59.55%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 5.59.55 PM.png" />
<img width="1844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25GQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cc813e66c446f50a6ab284c306b48c1f20c75d0/Screenshot%202024-07-09%20at%206.01.08%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 6.01.08 PM.png" />

@kelvinballoo As per our conversation over slack DM, you are getting some error during Site Kit setup.

However; when I request the API, I am getting the response as shown in screenshot attached. can you please make sure these steps are completed in RRM in publisher centre?

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this and it's looking good:

- After running the QAB script in browser console, the publication request succeeds with 200 response and returns an array of publications that my Google account has at the publisher center (https://publishercenter.google.com/) that are associated with the current site URL.   

   <Details>
   <img width="1206" alt="Screenshot 2024-07-10 at 12 47 47" src="https://github.com/google/site-kit-wp/assets/125576926/5ab02a11-f2fc-449e-919c-61d7eda9a09c">
   </Details>

- The publications returned matched the ones in Publisher Central
- I've created 3 publications and all of the 3 are pulled in as long as the URL matches with my site URL
- I've created 1 publication with a wrong URL to ensure it's not being picked up and it was as expected

Moving this ticket to Approval.

**Note:** It's important to check done for 'Add code to your site' in Publisher central for the publications to be pulled in.
   <Details>
   <img width="1097" alt="Screenshot 2024-07-10 at 12 56 06" src="https://github.com/google/site-kit-wp/assets/125576926/ce7bb414-75ca-4fb7-ae7b-64f4ff328eb3">
   </Details>
