### ISSUE TITLE
Request additional scope when connecting Ads via PAX

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8792]
## Feature Description

The Ads module requires a new OAuth scope when connecting via PAX for the purpose of providing in-product support/feedback.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Ads module should request an additional OAuth scope under the same conditions that it requests the `adwords` scope:  
    ```
    https://www.googleapis.com/auth/supportcontent
    ```

## Implementation Brief

* [x] Update `\Google\Site_Kit\Modules\Ads::get_scopes` to include the additional scope

### Test Coverage

* Update coverage for the method

## QA Brief

* Ensure the `paxAds` feature flag is enabled.
* Reset Site Kit or set up a new site and proceed to connect the Ads module. Check that the additional scope (Support Content) is requested within the Google Auth screen.

## Changelog entry

* Add new OAuth scope to Ads module.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The additional scope (Support data) is requested within the Google Auth screen.
- The error reported previously for the scenario when the Ads scope is first requested does not occur. I am able to complete the oAuth and no errors appear on the setup screen. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/82391108-75c6-4bac-b427-c8e467d998d5)
![image](https://github.com/google/site-kit-wp/assets/73545194/1d945cbf-b00f-42ce-ba51-d0ce94d5fe7e)

</details>
