### ISSUE TITLE
Implement RRM `maybeSyncPublicationOnboardingState()` action

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8797]
## Feature Description

The `maybeSyncPublicationOnboardingState()` action should be implemented for the Reader Revenue Manager module that periodically dispatches the `syncPublicationOnboardingState()` action (once every hour) to sync the value of the `publicationOnboardingState` module setting.

- The `maybeSyncPublicationOnboardingState()` action should be dispatched in the Site Kit dashboard on load, similar to how it is done for `syncGoogleTagSettings()`.
- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.s3z8pde34tcm).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `maybeSyncPublicationOnboardingState()` action should be implemented for the `modules/reader-revenue-manager` data store.
* This action should check the value of the `publicationOnboardingStateLastSyncedAtMs` module setting and determine if it has been more than an hour since the last sync. If so, the `syncPublicationOnboardingState()` action should be dispatched.
* The `maybeSyncPublicationOnboardingState()` action should be dispatched in the Site Kit dashboard on load, similar to how it is done for `syncGoogleTagSettings()`.

## Implementation Brief

- [ ] In `assets/js/components/DashboardEntryPoint.js`, collect actions object of RRM module using `useDispatch`
  ```js
      const rrmActions = useDispatch( READER_REVENUE_MANAGER );
  ```
  - [ ] Call `rrmActions?.maybeSyncPublicationOnboardingState()` inside `useMount` hook.
- [x] Create a new generator action `maybeSyncPublicationOnboardingState` inside `assets/js/module/reader-revenue-manager/datastore/publications.js`
  - [ ] Wait for `getModules` to resolved.
  - [ ] Return `null` if module is not connected.
  - [ ] Call the `getSettings` selector on module and wait for it to be resolved so that settings are available before we make another check. Refer [this](https://github.com/google/site-kit-wp/blob/8240ccf423e84ab53dc7fcea36833feae1736235/assets/js/modules/analytics-4/datastore/properties.js#L667-L670) for similar approach.
  - [ ] Call the `getPublicationOnboardingStateLastSyncedAtMs` selector on module. If the value is present and an hour has not passed since last sync, return from the action and do nothing. Refer [here](https://github.com/google/site-kit-wp/blob/8240ccf423e84ab53dc7fcea36833feae1736235/assets/js/modules/analytics-4/datastore/properties.js#L688-L695).
	- [ ] Otherwise, dispatch an action `syncPublicationOnboardingState` which would update the settings on server as well as in the local state for the module based on following.
	  - [ ] If more than an hour has passed since last sync.
	  - [ ] If the value of `getPublicationOnboardingStateLastSyncedAtMs` is zero.

### Test Coverage

Add tests for `maybeSyncPublicationOnboardingState` action with different values for `publicationOnboardingStateLastSyncedAtMs` setting.

## QA Brief

* Follow the QAB of [8796](https://github.com/google/site-kit-wp/issues/8796) to setup RRM module and and verify that the onboarding state is `ONBOARDING_STATE_UNSPECIFIED` and `publicationOnboardingStateLastSyncedAtMs` is zero. This can be verified by using `googlesitekit.data.select('modules/reader-revenue-manager').getSettings()`.
* Visit Site Kit Dashboard. 
* In the network tab, there should be a request to `GET:modules/reader-revenue-manager/data/publications` and the `publicationOnboardingStateLastSyncedAtMs` should be updated. Use the above snippet to verify the timestamp. 
* For subsequent refreshes in the next 1 hour, there should be no request to the above endpoint and timestamp should remain unchanged.
* Once 1 hour has passed, revisiting the dashboard should do the sync again using the endpoint and update the timestamp accordingly. 

## Changelog entry

* Add a mechanism to synchronize the onboarding state of a publication once every hour in the Reader Revenue Manager module.

**Comment by nfmohit** [comment]
Thank you for the IB, @ankitrox ! Please take a look at my comments below:

> * Return if module is not connected.

Let's also wait for `getModules` to resolve before we check for the module's connection status.

> * If more than an hour has passed since last sync, dispatch an action `syncPublicationOnboardingState` which would update the settings on server as well as in the local state for the module.

It would also be beneficial to mention that this should also run if `getPublicationOnboardingStateLastSyncedAtMs` is not set, i.e. `0` as well.

-------------------

Please let me know if you have any questions, thank you!

**Comment by ankitrox** [comment]
Thank you @nfmohit . 

I have updated the couple of points mentioned in the feedback.

**Comment by nfmohit** [comment]
Thank you @ankitrox ! I have made some small improvements to the IB, namely:

* We do not need to return `undefined` if `getModules` has not resolved, simply using `resolveSelect` should be sufficient.

The IB LGTM 👍 ✅

**Comment by aaemnnosttv** [comment]
@kuasha420 has addressed this correctly in his PR but I just wanted to note how we should not be introducing any module-specific effects/coupling into core components like `DashboardEntryPoint` or `DashboardMainApp`. See #8211

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Not sure if we need to update the QAB but I tried to set it up but I can't get the '**GET:modules/reader-revenue-manager/data/publications**' request.

Video is attached for reference:

<Details>


https://github.com/user-attachments/assets/22c91d45-2bbf-4c1f-ad67-6216106095b7


</Details>

**Comment by kuasha420** [comment]
Hi @kelvinballoo, I just tested develop and the endpoint is correct and is getting hit. Can you try again? I'm not sure why it didn't work for you, maybe the zip on develop didn't update correctly. 
![Uploading Screenshot_20240803_085143.png…]()

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @kuasha420 , thanks.
I've been able to get the request now:
<img width="1248" alt="Screenshot 2024-08-05 at 15 57 57" src="https://github.com/user-attachments/assets/c57b3dcd-74bc-40f3-8c8d-72a0006f1586">

From where do I actually find the time stamp though? ⚠️ 
I ran the snippet `googlesitekit.data.select('modules/reader-revenue-manager').getSettings()` but I don't see anything related to timestamp from there:
<img width="1108" alt="Screenshot 2024-08-05 at 15 58 33" src="https://github.com/user-attachments/assets/61c0c4fc-7363-46ca-a455-1cb01ed660f9">

**Comment by kuasha420** [comment]
Hi @kelvinballoo Sorry for the confusion. The timestamp is stored as `publicationOnboardingStateLastSyncedAtMs` which is `0` in your screenshot. Hope that clears it up.

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Hi @kuasha420 , as per our sync, I'm always getting the `publicationOnboardingStateLastSyncedAtMs` as 0, even the first round or after 1 hour+. 

Assigning to you for investigation.

<Details>
<img width="1230" alt="Screenshot 2024-08-07 at 11 34 11" src="https://github.com/user-attachments/assets/15d12c37-ad63-4fab-a38b-73177dae64bb">

</Details>

**Comment by aaemnnosttv** [comment]
@kelvinballoo Moving this back to QA now that #9163 has been merged, as @kuasha420 mentioned that it should address the issue here https://github.com/google/site-kit-wp/pull/9163#pullrequestreview-2225486186

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this and it's looking good now.
Moving ticket to Approval.

- In the network tab, there is a request to GET:modules/reader-revenue-manager/data/publications and the publicationOnboardingStateLastSyncedAtMs was updated to the time the request was triggered. ✅  
   <Details>
   
   <img width="1207" alt="Screenshot 2024-08-08 at 11 07 49" src="https://github.com/user-attachments/assets/59f70c0a-7be9-42af-a183-10ab7e2e55da">
   <img width="1208" alt="Screenshot 2024-08-08 at 11 09 23" src="https://github.com/user-attachments/assets/3f59ac6f-eafc-4c48-8a6a-8ce160d257af">

   Verified that the epoch time corresponded to the trigger time.
   <img width="1206" alt="Screenshot 2024-08-08 at 11 10 30" src="https://github.com/user-attachments/assets/559b9a0d-8fb6-4947-896e-fd1355b672bc">

   
   </Details>

- For subsequent refreshes in the next 1 hour, there was no request to the above endpoint and timestamp remain unchanged. ✅ 
   <Details>
   There was no publication request again after refreshing within the next hour
   <img width="1195" alt="Screenshot 2024-08-08 at 11 14 38" src="https://github.com/user-attachments/assets/2d32ce1f-87c1-499b-8004-99daea86609b">
   
   publicationOnboardingStateLastSyncedAtMs remained unchanged (Note: This one was for another timeframe, the requests were made 5 mins after the other and the values were the same)
   
   <img width="1028" alt="Screenshot 2024-08-08 at 13 16 50" src="https://github.com/user-attachments/assets/f3bfeba1-48de-407b-a182-4b2e23bc601c">


   </Details>

- Once 1 hour has passed, revisiting the dashboard does the sync again using the endpoint and updates the timestamp accordingly. ✅ 
   <Details>
   After 1hour plus, publications request was made when refreshing SK dashboard.
   <img width="1217" alt="Screenshot 2024-08-08 at 12 55 05" src="https://github.com/user-attachments/assets/6247fed4-622c-4d4f-bce8-fbde6b4319e7">
   
   New timestamp was made:
   
   <img width="1223" alt="Screenshot 2024-08-08 at 12 55 21" src="https://github.com/user-attachments/assets/d47999f7-392c-49ac-b7cc-b09bcd847e4a">

   <img width="1203" alt="Screenshot 2024-08-08 at 12 55 37" src="https://github.com/user-attachments/assets/b6ec609e-be02-4885-9a9e-e4f86128d29e">


   </Details>
