### ISSUE TITLE
Add Plugin integration for Ninja Forms

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8799]
## Feature Description

Ninja Forms conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes - phase 2](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.cg91vzdui6m6) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from Ninja Forms should be tracked and supported by our infrastructure.
* When form built by Ninja Forms is submitted, a `submit_lead_form` conversion event should be tracked.

## Implementation Brief

* [x] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\Ninja_Forms`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `ninja-forms`
  * It should have following methods:
    * `is_active` - check if `NF_PLUGIN_URL` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain one string `submit_lead_form`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * You can use `nf-front-end-deps` script as dependency
      * Include `'execution'    => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance
* [x] Add `assets/js/event-providers/ninja-forms.js`
  * Include the Ninja Forms specific event listener that will trigger the event once document is loaded, adapt from the [example](https://developer.ninjaforms.com/codex/listening-to-submit-response/) they provided in the documentation
  * Use `global._googlesitekit.gtagEvent()` for tracking the event. You can see an example in `assets/js/event-providers/contact-form-7.js`
* [x] Include JS file path in the `conversionEventProviders.config.js` webpack partial
* [x] Include the plugin name and class path to the array of main `Conversion_Events` class property

### Test Coverage

* Add basic test coverage for `Ninja_Forms` class, testing that `get_event_names` method returns correct event names, and `register_script` returns script instance with proper handle. Also `is_active` method can be confirmed by defining the plugin constant

## QA Brief

- Install an extension for your browser that lets you track Analytics events
- Enable the `conversionInfra` feature flag for your site
- Setup Analytics or Ads module, or both
- Install and activate the Ninja Forms plugin
- Create a new form, add it to a page and open that page on the frontend
- Submit the form and ensure that the appropriate event is tracked

## Changelog entry

* Add conversion events tracking for the Ninja Forms plugin.

**Comment by 10upsimon** [comment]
AC and IB look good to me here @zutigrm but let's add a point noting that the event should be tracked using the existing internal `global._googlesitekit.trackEvent()` function, and reference an existing event provider JS script as an example.

**Comment by zutigrm** [comment]
@10upsimon Thanks, IB updated

**Comment by 10upsimon** [comment]
Thank you @zutigrm moving to EB.

**Comment by 10upsimon** [comment]
@zutigrm sending this back to IBR for a quick review from you after I updated the reference to `trackEvent` to now reference `gtagEvent` in the IB section.

**Comment by zutigrm** [comment]
Thanks @10upsimon LGTM

**Comment by mohitwp** [comment]
### QA Update ⚠️ 


- Tested on dev environment after downloading plugin zip file.
- Tested event tracking for Ninja forms.
- Tested when only Analytics module connected and verified only 1 event is getting track.
- Tested when both analytics and ads module connected and verified 2 events are getting track.
- Tested when only Ads module connected and verified only 1 event is getting track.
- Tested when both Ads and Analytics module connected and verified no events is getting track.
- Verified `submit_lead_form` event is getting track when Ads or Analytics module connected.
- 

@zutigrm @10upsimon I've noticed that in Ninja forms event command includes `event category` parameter where as other event do not have this parameter. Is this expected?

`

> ["event", "submit_lead_form", {event_category: "1", event_source: "site-kit"}]

`


**When only Analytics connected**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/098d9b11-2142-493b-bf7a-b9e6fb2def15)


https://github.com/google/site-kit-wp/assets/94359491/f0f2c3d5-1aa9-4c5e-a860-027674c204d5

</details>

**When both Ads module and analytics connected**

<details>

Analytics event

![image](https://github.com/google/site-kit-wp/assets/94359491/40b51949-82df-4b13-b570-15ac28e732f1)

Ads module event

![image](https://github.com/google/site-kit-wp/assets/94359491/e130f096-aeeb-4f4a-989e-fa4ee1c03081)


https://github.com/google/site-kit-wp/assets/94359491/b264467a-8c91-4d34-b2d8-c3bc50c0cc9c


</details>

**When only Ads module connected**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e908bf33-689b-457c-9a4b-bc8dfef5f698)


https://github.com/google/site-kit-wp/assets/94359491/53702fda-febd-44a3-b0cb-e596d0d466d6

</details>

**Comment by zutigrm** [comment]
@mohitwp Basically, beside sending an event name, we do not have preference over other parameters, they are optional and can be included or excluded. @10upsimon what do you think, should we keep this or exclude it? Form ID doesn't look much informative

**Comment by 10upsimon** [comment]
@mohitwp @zutigrm this is fine. We wanted to forward as many event parameters as possible for each of the event integrations. Not all instances of plugin actions will have parameters for us to forward, but the idea is that these could be useful for potential future reporting scenarios where we can use such values to display category or form labels etc. 

So I think it's okay to mark the presence of this category parameter as acceptable behavior.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @10upsimon @zutigrm !

- Tested on dev environment after downloading plugin zip file.
- Tested event tracking for Ninja forms.
- Tested when only Analytics module connected and verified only 1 event is getting track.
- Tested when both analytics and ads module connected and verified 2 events are getting track.
- Tested when only Ads module connected and verified only 1 event is getting track.
- Tested when both Ads and Analytics module connected and verified no events is getting track.
- Verified `submit_lead_form` event is getting track when Ads or Analytics module connected.



**When only Analytics connected**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/098d9b11-2142-493b-bf7a-b9e6fb2def15)


https://github.com/google/site-kit-wp/assets/94359491/f0f2c3d5-1aa9-4c5e-a860-027674c204d5

</details>

**When both Ads module and analytics connected**

<details>

Analytics event

![image](https://github.com/google/site-kit-wp/assets/94359491/40b51949-82df-4b13-b570-15ac28e732f1)

Ads module event

![image](https://github.com/google/site-kit-wp/assets/94359491/e130f096-aeeb-4f4a-989e-fa4ee1c03081)


https://github.com/google/site-kit-wp/assets/94359491/b264467a-8c91-4d34-b2d8-c3bc50c0cc9c


</details>

**When only Ads module connected**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e908bf33-689b-457c-9a4b-bc8dfef5f698)


https://github.com/google/site-kit-wp/assets/94359491/53702fda-febd-44a3-b0cb-e596d0d466d6

</details>
