### ISSUE TITLE
Add Plugin Integration for Easy Digital Downloads

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8801]
## Feature Description

Easy Digital Downloads conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes - phase 2](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.cg91vzdui6m6) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from Easy Digital Downloads should be tracked and supported by our infrastructure.
* When product is added to the cart, `add_to_cart` conversion event should be tracked

## Implementation Brief

* [x] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\Easy_Digital_Downloads`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `easy-digital-downloads`
  * It should have following methods:
    * `is_active` - check if `EDD_VERSION` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain one string `add_to_cart`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * You can use `edd-ajax` script as dependency
      * Include `'execution'    => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance
* [x] Add `assets/js/event-providers/easy-digital-downloads.js`
  * Include the Easy Digital Downloads specific event listener that will trigger the event once document is loaded. Events are handled with jQuery so `.on()` listener should be used, example:
```js
$( 'body' ).on( 'edd_cart_item_added', function() {
   global._googlesitekit?.gtagEvent?.( 'add_to_cart' );
} );
```
* [x] Include JS file path in the `conversionEventProviders.config.js` webpack partial
* [x] Include the plugin name and class path to the array of main `Conversion_Events` class property
* You can follow the examples of already included providers, for example `Contact_Form_7`

### Test Coverage

* Add basic test coverage for `Easy_Digital_Downloads` class, testing that `get_event_names` method returns correct event names, and `register_script` returns script instance with proper handle. Also `is_active` method can be confirmed by defining the plugin constant

## QA Brief

- Install an extension for your browser that lets you track Analytics events
- Enable the `conversionInfra` feature flag for your site
- Setup Analytics or Ads module, or both
- Install and activate the Easy Digital Downloads plugin
- Create a new download product (it can be a free products)
- Click on the Purchase button on the download product page and confirm the event is correctly tracked

## Changelog entry

* Add support for Easy Digital Downloads "add to cart" event in Analytics enhanced tracking.

**Comment by 10upsimon** [comment]
@zutigrm let's be sure to instruct usage of `global._googlesitekit.trackEvent()` event, not vanilla `gtag()` call.

**Comment by zutigrm** [comment]
@10upsimon makes sense, thanks. IB updated

**Comment by 10upsimon** [comment]
Thank you @zutigrm moving to EB

**Comment by 10upsimon** [comment]
@zutigrm sending this back to IBR for a quick review from you after I updated the reference to `trackEvent` to now reference `gtagEvent` in the IB section.

**Comment by zutigrm** [comment]
Thanks @10upsimon LGTM

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment after downloading plugin zip file.
- Tested event tracking for Easy Digital Downloads plugin
- Tested when only Analytics module connected and verified only 1 event is getting track.
- Tested when both analytics and ads module connected and verified 2 events are getting track.
- Tested when only Ads module connected and verified only 1 event is getting track.
- Tested when both Ads and Analytics module connected and verified no events is getting track.
- Verified` 'add_to_cart'` event is getting track as per AC.


**When only Analytics is connected**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/22865f6b-b16e-45d1-a375-c258f8828724)

https://github.com/google/site-kit-wp/assets/94359491/45389cc1-232c-4263-854b-17ff1ec4f6b1

</details>

**When both Analytics and Ads modules are connected**

<details>

Analytics event

![image](https://github.com/google/site-kit-wp/assets/94359491/5d7f4f13-68a0-4a0d-bc06-f45568a9c4ca)

Ads module event

![image](https://github.com/google/site-kit-wp/assets/94359491/bf47d744-3aff-483e-beb6-228a78635a8b)


https://github.com/google/site-kit-wp/assets/94359491/5c389eee-c142-418b-91c1-e8c7323293e5


</details>

**When only Ads module connected**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/6de817eb-f16c-4244-8a44-1f2f902388a6)


https://github.com/google/site-kit-wp/assets/94359491/9dc2793f-9d32-4c5f-9c56-3a93850dacfa

</details>
