### ISSUE TITLE
PAX OAuth Token Short Expiry Time - Requires Token Refresh

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8802]
## Bug Description

When onboarding to Ads via the PAX flow, an OAuth flow is entered into in order for the `adwords` scope to be granted. However, when the user is idle for some time (at this point the time is unknown), such as during PAX onboarding, the PAX embedded application errors in the following state:

![image](https://github.com/google/site-kit-wp/assets/1621608/b7ddafe3-2d72-4725-994f-b5e1220dffff)

This occurs when the [PAX authentication service](https://github.com/google/partner-ads-experience/blob/main/sdk/service/partner/authentication-service.d.ts) attempts a retry on the expired token on the 3rd attempt, this is according to the PAX team themselves.

The response from the PAX team is as following:

> The reason is that, OAuth token expires in a defined duration, and then PAX will re-try OAuth token retrieval from SK by calling authentication-service, and SK needs to RE-fetch OAuth token with access token, otherwise, after 3 re-try, PAX will throw this error.

In order for this to be resolved, Site Kit should implement the necessary [AuthenticationService](https://github.com/google/partner-ads-experience/blob/main/sdk/service/partner/authentication-service.d.ts#L95) `get` and `fix` implementations accordingly to both inform PAX that a retry of the token is ready, and to handle retrieval of this refreshed token.

When PAX encounters the expired token scenario, it will call the `fix` implementation of the `AuthenticationService` to determine if a retry is ready. If the resolve on this `fix` is `true`, PAX will call the `get` implementation of the `AuthenticationService`. It is herein that PAX expects to receive the new token, i.e the async callback attached to `get` should resolve the new token.
 
## Steps to reproduce

1. With the PAX feature flag enabled, set up Site Kit with the Ads module enabled 
2. Initiate the PAX flow via the "Create new account" CTA within Ads module setup
3. Proceed to the OAuth flow and grant the necessary permissions for the token
4. Initialise the PAX application setup flow
5. Leave the flow idle for quite some time (at the moment, this time is unknown)
6. Proceed with the set up
7. The error as indicated in the above screenshot should eventually appear

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PAX application should not produce authentication related to an invalid token should be refreshed accordingly when an expiration is detected
    * The PAX `AuthenticationService` partner service implementation in Site Kit should be updated to support the expected behaviour of the `get` and `fix` implementations of the `AuthenticationService` partner service. 
    * The `get` implementation should be updated to call a newly created API endpoint that will fetch a new token and return it
    * The `fix` implementation should remain unchanged
* The new API endpoint should only exist when the `adsPax` feature is enabled

## Implementation Brief

* [ ] Create a new `POST:core/user/data/refresh-token` REST endpoint that returns a refreshed access token
    * [ ] Add REST endpoint registration logic within the `Authentication` class if feature flag is enabled
        * [ ] require the same `VIEW_AUTHENTICATED_DASHBOARD` capability in the `permission_callback` used by the current pax config
        * [ ] the endpoint's `callback` should trigger a refresh of the current token via its `OAuth_Client` i.e `$this->get_oauth_client()->refresh_token()`
        * [ ] Return the new access token as part of the REST response as `{ token: String }` via `OAuth_Client->get_access_token`.
* [ ] Update the partner services implementation in `createPaxServices`
    * [ ] Update the async function attached to the `authenticationService.get` property to make a call via `API.set` to the newly created authentication REST endpoint above and resolve the updated/refreshed token returned by said REST endpoint as `accessToken`

### Test Coverage

* Add coverage for the new endpoint in `AuthenticationTest` see (`*_ControllerTest`s for examples of testing endpoints)
* Update coverage for `authenticationService.get` in the respective tests for `createPaxServices`

## QA Brief

* Set up Site Kit with `adsPax` feature flag enabled 
* Set up ads using PAX setup flow
* Proceed to set up PAX until the image upload step
    * Confirm no application or console errors are triggered during image upload process (image selection, upload, confirm etc)
* Proceed past the image step
* Remain idle for longer than 60min, 61min is fine (continue with other tasks while the PAX app idles)
    * This is to let the access token passed to PAX expire
* When resuming testing within PAX, navigate back to the image step
    * Validate that no application or console errors appear
* Proceed to remove and re-upload images
    * Confirm no application or console errors are triggered during image upload process (image selection, upload, confirm etc)

## Changelog entry

* Update PAX integration to avoid intermittent authentication errors.

**Comment by aaemnnosttv** [comment]
Thanks @10upsimon I tweaked the AC and IB a bit and this should be good to go now 👍 
✅ ✅

**Comment by 10upsimon** [comment]
@wpdarren to give you some updates before this likely gets passed back to QA in it's current state:

- The image upload error you reported where it states to clear cache and try again. This issue is known to the PAX team, and at the time of writing is out of their control. We have been instructed to ignore this error.
- You can ignore the console based errors you reported, so long as they are not preventing usage of the PAX app, which they do not appear to. I got the same errors, and was able to continue.
- If you let the token expire on the image upload step (and sometimes other steps) and you proceed to step back a s step (or forward) you are likely to encounter a full on fatal error as per the screenshot below. This too is a known issue, and we have been instructed that we can ignore it for now. All of this will be addressed in relevant instructional documentation where necessary, until it can be addressed in future iterations of the PAX integrator script.

![image](https://github.com/google/site-kit-wp/assets/72872375/56d9b549-1ee8-49b4-816f-e109d71e2e7f)

cc @aaemnnosttv

**Comment by aaemnnosttv** [comment]
Following on what @10upsimon said, this issue is really only about implementing the ability to get a new token when the initial token the page was loaded with expires. This seems to be working as expected on every step except the image upload due to the unique nature of this specific step.

So long as the original error reported isn't occurring  "no valid OAuth token provided" after the token expires, this should be good to go.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Note issues [reported above](https://github.com/google/site-kit-wp/issues/8802#issuecomment-2154812285) and highlighted in [Simon's comment](https://github.com/google/site-kit-wp/issues/8802#issuecomment-2159211229). 

When remaining idle for longer than 60min, and the access token passed to PAX expire: when resuming testing within PAX, and navigating back to the image step or any other screen, the `no valid OAuth token provided` error does not appear. 

I did observe though the message that Simon mentioned when I went from the location screen to choosing the terms. Since this is a known issue and needs to be addressed by the ads team, I will move this ticket to approval.
