### ISSUE TITLE
Ensure all version numbers in plugin match each other

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8804]
## Feature Description

Last release I forgot to update the constant value for `GOOGLESITEKIT_VERSION`, which @aaemnnosttv kindly caught before the release 😅

![image](https://github.com/google/site-kit-wp/assets/90871/da0056da-72de-449e-99c0-3ab7936ecac1)

We should set up a PHP unit test that ensures all of these versions values are synced, so when we bump version values they aren't out-of-sync, like they were in a6fe45c8030b97476653f4e3c6360de6684e786a.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new PHP test should be introduced that ensures the version numbers in the following places are the same:
  * https://github.com/google/site-kit-wp/blob/0ea003eb33a2bfd79846ac0c227432429532f4c5/google-site-kit.php#L29
  * https://github.com/google/site-kit-wp/blob/0ea003eb33a2bfd79846ac0c227432429532f4c5/google-site-kit.php#L14
  * https://github.com/google/site-kit-wp/blob/0ea003eb33a2bfd79846ac0c227432429532f4c5/readme.txt#L7
  * First version value in: https://github.com/google/site-kit-wp/blob/0ea003eb33a2bfd79846ac0c227432429532f4c5/changelog.txt#L1-L3
  * Version number used at https://github.com/google/site-kit-wp/blob/0ea003eb33a2bfd79846ac0c227432429532f4c5/readme.txt#L110-L112

## Implementation Brief

**Check my draft PR for this ticket #8864**

* [ ] Create a new phpunit test `tests/phpunit/integration/VersionTest.php` with a single test `test_consistent_plugin_versions`:
   * [ ] Use use REGEX with `preg_match`, to extract the first occurrence of the version number based on each pattern in the AC.
   * [ ] Compare all of these version values, if any of them are different, fail the test.

### Test Coverage

* Tests outlined in implementation brief.

## QA Brief

* No QA needed for this issue; if tests are passing then it can be moved to Approval.

## Changelog entry

* N/A.

**Comment by tofumatt** [comment]
@benbowler Yeah, the point release wasn't merged back into `main`/`develop` as standard, I think this point release was a bit unorthodox 😅 

Good chance to test things out I guess 😆

IB looks good to me. IB ✅

**Comment by ankitrox** [comment]
**Note for reviewer**

If the changes looks good, we can move this ticket to Approved.

**Comment by techanvil** [comment]
The PR has been merged and the changes verified during CR. I've also verified the PHPUnit tests are passing post-merge in CI on `develop`. This issue has therefore been moved directly to Approval.

![Image](https://github.com/user-attachments/assets/6c2d428d-ca4b-4c98-96f6-c69699b4b76c)
