### ISSUE TITLE
Initial Conversion Event Infrastructure - WooCommerce `purchase` Event Not Being Tracked

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8814]
## Bug Description

As part of the Initial Conversion Event infrastructure work, WooCommerce was identified as one of the initial plugins to support the tracking of conversion events against Ads and/or GA4 tags, specifically the `add_to_cart` and `purchase` events. 

The initial work was carried out in #8553, however a bug has been identified where the `purchase` event is not being tracked.

An identified solution is to fire the `purchase` event at a page view level when the `transaction_id` URL parameter is present on the front end, as this indicates a successful purchase operation.

## Steps to reproduce

1. Use the latest develop build of Site Kit
2. Enabled the `conversionInfra` feature flag via tester plugin
3. Set up the Ads or GA4 module (or both)
4. Enabled Enhanced Conversion tracking in Ads or GA4 modules (it's a shared state)
5. Install WooCommerce and create dummy products and payment methods, i.e EFT
6. Ensure you have a suitable means of monitoring gtag events, such as [Google Tag Assistant](https://tagassistant.google.com/)
6. Proceed to purchase a product right up until the transaction / order confirmation screen
7. Note that no `purchase` event was triggered against any of the gtag's present

## Screenshots

N/A

## Additional Context

N/A, affects all platforms and devices.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `purchase` event should be fired against Ads and/or GA4 gtag's when conversion tracking is enabled and a WooCommerce purchase is successfully carried out 

## Implementation Brief

* [x] In the `includes/Core/Conversion_Tracking/Conversion_Event_Providers/WooCommerce.php` file:
  * Add a new hook for the `woocommerce_thankyou` action that should do the similar job as in the WooCommerce Google Analytics Integration plugin: https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/trunk/includes/class-wc-abstract-google-analytics-js.php#L99-L117.
    * Instead of calling `$this->set_script_data` as in the aforementioned example, our class should add an inline script that tracks the purchase event on page load using the `window._googlesitekit.gtagEvent` function.

### Test Coverage

* No additional test coverage required.

## QA Brief

1. Enable the `conversionInfra` feature flag via the Site Kit Tester plugin
2. Enable Analytics
3. Enabled Enhanced Conversion tracking Analytics settings
4. Install WooCommerce and create dummy products and payment methods, i.e EFT/Cash-on-delivery/etc.
5. Ensure you have a suitable means of monitoring `gtag` events, such as [GA Event Debugger](https://chromewebstore.google.com/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) or [Google Tag Assistant](https://tagassistant.google.com/)
6. Add a product to your cart and check out, until you see a screen similar to:

![Screenshot 2024-06-12 at 00 24 03](https://github.com/google/site-kit-wp/assets/90871/8796c98e-2410-4989-9d8f-42fa41ccd591)

7. Check your Analytics debugging output and ensure there is a `'purchase'` event sent to Analytics with the event source listed as `'site-kit'`
8. Refresh the page and ensure the event is not sent again (it should only be sent once per order)

## Changelog entry

* Add the `purchase` event tracking for the WooCommerce provider.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by binnieshah** [comment]
Hi all, no rush but would be good to keep this one moving as we would like to get it into sprint 130 if possible.

**Comment by eclarke1** [comment]
Sorry this is my mistake, this ticket needs to be complete in Sprint 129. I have updated the sprint label to reflect this - @benbowler can you jump on this urgently tomorrow please.

**Comment by eugene-manuilov** [comment]
Thanks, @benbowler, but we need to use a similar approach as used in the WooCommerce Google Analytics plugin: https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/trunk/includes/class-wc-abstract-google-analytics-js.php#L99-L117. Instead of trying to catch the purchase event on the frontend, we need to catch it on the backend and add an inline script that will track event.

**Comment by benbowler** [comment]
Thanks @eugene-manuilov, I'll update this.

**Comment by benbowler** [comment]
@eugene-manuilov back to IBR

**Comment by aaemnnosttv** [comment]
We can avoid the need for providing an inline script manually by using our GTag infrastructure on `googlesitekit_setup_gtag`, and then adding the `event` call on via `add_command`. See `\Google\Site_Kit\Core\Tags\GTag::add_command`

**Comment by aaemnnosttv** [comment]
@eugene-manuilov we can't simply hook into `woocommerce_thankyou` as the `add_command` method is only available on the `GTag` instance that is passed from `googlesitekit_setup_gtag`. Also, the `woocommerce_thankyou` action happens in the template of the page whereas the gtag JS will be in the head already. So we'd have to check if we're on the thank you page another way, i.e. by checking if we're on the `order-received` endpoint. See https://developer.woocommerce.com/docs/woocommerce-endpoints/#0-checkout-endpoints

There are functions for `is_order_received_page` or `is_wc_endpoint_url` that would be useful here but we probably need to make sure they exist first.

**Comment by eugene-manuilov** [comment]
> So we'd have to check if we're on the thank you page another way, i.e. by checking if we're on the `order-received` endpoint. See https://developer.woocommerce.com/docs/woocommerce-endpoints/#0-checkout-endpoints
> 
> There are functions for `is_order_received_page` or `is_wc_endpoint_url` that would be useful here but we probably need to make sure they exist first.

@aaemnnosttv this is overkill. We can simply render an inline script and that will be more than sufficient, won't it? I have updated IB not to mention the `GTag::add_command` method.

**Comment by aaemnnosttv** [comment]
SGTM. IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Tested by downloading zip file instead of using the tester plugin.
- Tested after enabling 'conversionInfra' feature flag.
- Enabled Enhanced Conversion tracking Analytics settings
- Tested on WooCommerce using payment method ' COD' and 'Check payments'.
- Verified on Theme - Storefront and Deli.
- Verified 'Add to cart' events is getting tack.

@tofumatt 

**Issue > 'Add to cart' event is getting track but 'Purchase' events is still not getting track on both the templates.** 

_Deli theme_

<details>


https://github.com/google/site-kit-wp/assets/94359491/2263fe86-6dec-42ff-95da-343eaeab77c6

Add to cart event


https://github.com/google/site-kit-wp/assets/94359491/9359d2af-7cd9-4445-9d2b-34ce3800f6ec

</details>

_Storefront Theme_

<details>

https://github.com/google/site-kit-wp/assets/94359491/bcd161da-2990-48dc-b87e-17d783948222

</details>

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment after downloading dev env zip file.
- Both 'add_to_cart' and 'purchase' event getting track when tested on dev env downloaded zip file.
- Verified on refreshing the page the event is not sent again .
- Verified when only one module (either Ads or Analytics ) is set up then one instance of every event is getting track.
- Verified when both module ( Ads and Analytics ) are set up then 2 instances of every event are getting track.

@tofumatt 

But, when I tested on main environment using tester plugin then 'add_to_cart' event is not getting track.


**When only Analytics module is set up**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/37bf9812-5c1e-49c6-9776-cca642e27db2)

![image](https://github.com/google/site-kit-wp/assets/94359491/dd778789-11bb-42ef-a97a-6deaf5ec7564)


https://github.com/google/site-kit-wp/assets/94359491/9fcc39da-496e-47fb-b8e1-6530354cd352


</details>

**When both Ads module and Analytics module are set up**

<details>

Add to cart event

![image](https://github.com/google/site-kit-wp/assets/94359491/60ec7700-bb5e-49a4-889d-d3a0f6f4bff6)

![image](https://github.com/google/site-kit-wp/assets/94359491/6e6f7b64-8db0-4802-b0da-139b6e498d07)

Purchase event

![image](https://github.com/google/site-kit-wp/assets/94359491/e5a322a8-8e24-4db2-b763-bfd56538b786)

![image](https://github.com/google/site-kit-wp/assets/94359491/5e16b81b-3d3c-4f96-a068-5ba5732dbb7b)

https://github.com/google/site-kit-wp/assets/94359491/c5f3745c-7983-439e-b269-a109bf1d2435

</details>

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment after downloading main env zip file.
- Both 'add_to_cart' and 'purchase' event getting track when tested on main and dev env downloaded zip file.
- Verified on refreshing the page the event is not sent again .
- Verified when only one module (either Ads or Analytics ) is set up then one instance of every event is getting track.
- Verified when both module ( Ads and Analytics ) are set up then 2 instances of every event are getting track.
- Theme - Storefront


**_When only analytics module is connected_**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/b2460069-2a4a-4908-a80f-99ae6943c323)

![image](https://github.com/google/site-kit-wp/assets/94359491/7a1fbe0d-f836-4c77-a22e-e170a29ec133)


https://github.com/google/site-kit-wp/assets/94359491/29ea5133-e969-470f-ab65-89e909b29ca4


</details>

**_When both Analytics and ads module are connected_**

<details>

_add to cart event_

![image](https://github.com/google/site-kit-wp/assets/94359491/4d00d184-ed9c-4926-8bc5-9a628f265cba)

![image](https://github.com/google/site-kit-wp/assets/94359491/7e4650e3-f772-40b2-9fb3-90924ff7d09f)

_Purchase event_

![image](https://github.com/google/site-kit-wp/assets/94359491/b991e937-601c-4641-9a52-8dc928b51f2d)

![image](https://github.com/google/site-kit-wp/assets/94359491/4f3a46ad-eb82-4219-9cdc-17ce505bb4ab)


https://github.com/google/site-kit-wp/assets/94359491/156c6139-83b4-422b-9040-d34afd5a9111


</details>

**_When only Ads module connected_**


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c05e0379-2aa1-40ca-a6f3-d5866328f659)

![image](https://github.com/google/site-kit-wp/assets/94359491/077c82f9-b5aa-473f-8adf-b3cccbeedba7)


https://github.com/google/site-kit-wp/assets/94359491/7928dca3-5aa3-406f-be05-860db65bb5fe

</details>
