### ISSUE TITLE
Toggle does not function when user clicks outside of the modal

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8818]
## Bug Description

Reported by @kelvinballoo on the [Asana bug bash board](https://app.asana.com/0/1207432565654530/1207468781621156/f). 

When the user clicks on the toggle to disable the Enhanced conversion tracking. Rather than clicking on 'Disable' nor 'Cancel' the user clicks outside the modal, the toggle gets stuck and you are not able to toggle on and off.

Video of the issue can be found here

https://github.com/google/site-kit-wp/assets/73545194/87fc5375-6282-42f9-9f33-7c676610bea7

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After clicking on the Enhanced conversion tracking toggle, then clicking outside the modal to close it, it should behave the same as clicking on `cancel` button - toggle should trigger the modal again after clicking on it
## Implementation Brief

* [x] Update `assets/js/components/ModalDialog.js`
  * Add `onClose` prop to the `Dialog` component and pass it `handleDialog` callback (already passed as a prop to the main `ModalDialog` component) 

### Test Coverage

* No updates needed

## QA Brief

* Setup Site Kit
* Connect and setup Ads module. Then go to edit settings of Ads module
* Enable the enhanced conversion tracking and save it
* Then click on it to disable it, after modal pops up, click outside of it
* Once it is closed, click on the toggle again, it should trigger the popup again

## Changelog entry

* Fix the toggle issue that happened when the user closed the popup dialog for enhanced conversion tracking by clicking somewhere outside of the popup.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that issue is resolve now and toggle functional now when user clicks outside of the modal.

<details>



https://github.com/google/site-kit-wp/assets/94359491/b4bcd1f0-40bc-4c73-bb19-e4d62f7503c3



</details>
