### ISSUE TITLE
`ModalDialog`'s `subtitle` prop does not match the Figma design (should be larger/bolder)

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8819]
## Bug Description

Reported by @mohitwp on the [Asana Bug bash board](https://app.asana.com/0/1207432565654530/1207493613085759/f). 

The text size under the Ads module 'Disable Enhanced Conversion Tracking' modal does not match the Figma design and the text under the Analytics 'Disable Enhanced Conversion Tracking' modal. In Figma, the font size for the highlighted text is 14px, but the implemented size in the Ads module disable modal is 12px for the highlighted text.

**Figma designs**

![image](https://github.com/google/site-kit-wp/assets/73545194/16ee978b-bf9b-4c1f-8d0b-1ca97f285bde)

**Analytics Disable enhancing conversion tracking modal text**

![image](https://github.com/google/site-kit-wp/assets/73545194/5aea9826-4c83-43e0-9945-191891530f62)

**Analytics Disable enhancing conversion tracking modal text**

![image](https://github.com/google/site-kit-wp/assets/73545194/73e0db4c-768b-4a10-a8a5-9d493bfb18a8)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The rendered `subtitle` prop for the `ModalDialog` component should be updated (eg. `.mdc-dialog__lead` at https://github.com/google/site-kit-wp/blob/4245339ddc727f006e6b33deb7c1a5f2ccae2f09/assets/js/components/ModalDialog.js#L82
  * The font size should be `14px`
  * The font weight should be `500`

## Implementation Brief

* [ ] Update https://github.com/google/site-kit-wp/blob/4245339ddc727f006e6b33deb7c1a5f2ccae2f09/assets/js/components/ModalDialog.js#L82/`.mdc-dialog__lead`'s `font-size` to `14px` and `font-weight` to `500`.

### Test Coverage

* No new tests needed.

## QA Brief

* Setup Site Kit and connect Ads and Analytics modules
* Go to settings edit for both Ads an Analytics
* Enable enhanced conversion tracking toggle, then try to disable it
* Verify that main modal paragraph is having font size of 14px and font weight 500

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
Hi @mohitwp is this still reproducible on your end? I can see the highlighted text as being `14px` and font weight of `500` on develop

<img width="948" alt="image" src="https://github.com/google/site-kit-wp/assets/10414808/964cb429-7549-42b1-b0c4-0028f3266cae">

**Comment by mohitwp** [comment]
@zutigrm cc @wpdarren 

You are checking under wrong modal. Issue is exist under 'Disable enhanced conversion tracking' modal which appears when user try to disable enhance conversion tracking by clicking on toggle button.

![image](https://github.com/google/site-kit-wp/assets/94359491/8d747bf9-2e2b-49fe-af93-d6ee65df18e5)

![image](https://github.com/google/site-kit-wp/assets/94359491/1a5e49fc-2464-4f03-9ffc-fc03fe5d967e)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that main modal paragraph is having font size of 14px and font weight 500

<details>

Ads module


![image](https://github.com/google/site-kit-wp/assets/94359491/ffcbfba1-6c7a-4b73-b37f-b5087ff53617)


Analytics module

![image](https://github.com/google/site-kit-wp/assets/94359491/7e1a7ced-9730-4574-bdfd-b2f25c1571ee)


</details>
