### ISSUE TITLE
Difference in Font size for Enhance toggle description

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8820]
## Bug Description

As reported by @kelvinballoo on the [Asana bug bash board](https://app.asana.com/0/1207432565654530/1207468781621148/f)

The font size for the Enhance Toggle description is 12px, it should be 14px, similar to all the other text in that expanded module.

![image](https://github.com/google/site-kit-wp/assets/73545194/20e27400-c50f-4328-b2ac-e60e83eb938f)

Figma says it's 14px anyway:

![image](https://github.com/google/site-kit-wp/assets/73545194/fe693b53-0cde-41ca-8abc-7e193199efb5)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `font-size` for `.googlesitekit-settings-module__fields-group-helper-text` should be `14px`, not `12px`.

## Implementation Brief

* [ ] Add `font-size: 14px` to https://github.com/google/site-kit-wp/blob/4245339ddc727f006e6b33deb7c1a5f2ccae2f09/assets/sass/components/ads/_googlesitekit-ads-settings.scss#L27

### Test Coverage

* No new tests are needed.

## QA Brief

* Setup Site Kit and connect Ads and Analytics modules
* Confirm the font size and color for the Enhanced conversion tracking Toggle description (in Analytics and Ads module settings edit view) match the Figma designs.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @benbowler for the confirmation ! Yes, I have same thought that for consistency current implementation is correct. I will create separate ticket to implement consistency under settings page.

- Tested on dev environment.
- Verified the font size and for the Enhanced conversion tracking Toggle description (in Analytics and Ads module settings edit view) match the Figma designs which is 14px.


<details>
Ads module-

![image](https://github.com/google/site-kit-wp/assets/94359491/dfa836fc-94dc-4503-982b-ac2501575d53)

Analytics module -

![image](https://github.com/google/site-kit-wp/assets/94359491/6fac92d9-7b18-4444-ba3d-6fe8e8ccccf8)

</details>
