### ISSUE TITLE
Read-only and edit order of conversion tracking setting differs in Analytics settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8822]
## Bug Description

Reported by @10upsimon on the [Asana bug bash board](https://app.asana.com/0/1207432565654530/1207467647013089/f). 

In read-only/view mode of GA4 settings, the conversion tracking setting is second last, however when editing settings, the conversion tracking setting is last. The read-only view should be changed so that the setting is last in both read-only and edit views. Images to follow:

![image](https://github.com/google/site-kit-wp/assets/73545194/d83c579a-d5e7-4502-9393-e71938203e28)

![image](https://github.com/google/site-kit-wp/assets/73545194/3df7c19d-824c-41e9-893f-2a051f64bcec)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The view mode (also used by the read-only mode) order for GA4 settings should match the edit mode settings, eg the last three items should be in this order:

1. Enhanced Measurement
2. Excluded from Analytics
3. Enhanced Conversion Tracking

## Implementation Brief

* [ ] Re-order the settings in https://github.com/google/site-kit-wp/blob/4245339ddc727f006e6b33deb7c1a5f2ccae2f09/assets/js/modules/analytics-4/components/settings/SettingsView.js#L46 to match the ACs' order.

### Test Coverage

* No new tests needed. VRTs will need updating.

## QA Brief

* Setup Site Kit with Analytics module
* Go to settings, and expand view only dropdown. Verify that order portrayed in AC matched the one you se

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that read only and edit order of conversion tracking setting is same and as per AC.

1. Enhanced Measurement
2. Excluded from Analytics
3. Enhanced Conversion Tracking

<details>

Read only mode:

![image](https://github.com/google/site-kit-wp/assets/94359491/5f2e83dd-f160-44fa-b5e2-6224ec50c8c8)

Edit mode:

![image](https://github.com/google/site-kit-wp/assets/94359491/447f3b21-c210-4c1e-8837-ff2d9f1e0c4e)

</details>
