### ISSUE TITLE
adsbygoogle.push() error: No slot size for availableWidth=0

### ISSUE THREAD

**Issue by yah0130** [google/site-kit-wp#883]
## Steps to reproduce

1. open chrome and open my wordpress site
2. press f12 show console 
3. See error and the ads not show on the page ,but it show ads on safari,how can i solve this problem

## Screenshots

![image](https://user-images.githubusercontent.com/25168830/69200884-89416700-0b77-11ea-82ed-d3e609a064d5.png)

## Additional Context

 - PHP Version: 7.2.24
 - OS: MacOS
 - Browser chrome
 - Plugin Version 1.0.4
 - Device: Mac Pro

i can't see ads on my site with chrome,it show the error,but it is ok on safari

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@yah0130 Thanks for reporting. Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there. Please also include your site URL and when you implemented the AdSense module.
