### ISSUE TITLE
Implement `<PublicationCreate>` component

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8836]
## Feature Description

A `<PublicationCreate>` component should be added to the Reader Revenue Manager module that encapsulates the publication creation flow.

<details>
<summary>Screenshots for reference</summary>

![image](https://github.com/google/site-kit-wp/assets/20284937/57f1baf5-daa0-4415-a751-c8ffb9cafb14)
![image](https://github.com/google/site-kit-wp/assets/20284937/90bf798e-20d8-46ab-956e-a112887c51cd)

</details>

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.gu9swwrm6min).
- [See Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=171-2291&t=44sz1QCJ3moErPIh-4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `PublicationCreate` component should be created for the Reader Revenue Manager module to facilitate the creation of a new publication matching [the Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=171-2291&t=ZADB0omHh8dp1c1w-4).
	* Note: The component should only include account creation content, i.e. the text and the CTA. The rest of the content (e.g. module name, footer, "_Cancel_" button, etc.) will be a part of the container component, e.g. `SetupMain`/`SettingsEdit`. See screenshot for reference:
	![image](https://github.com/google/site-kit-wp/assets/20284937/d6f460b9-7667-4eeb-b5f5-10b2fe7d3954)
* The component should have two steps:
	* First step:
		* Text: "_To complete your Reader Revenue Manager account setup you will need to create a publication._"
		* Sub-text: "_Once you have created your publication, it is submitted for review._"
		* CTA: "_Create publication_" (with external link icon). This should open the publisher center in a new browser tab, using the `getServiceURL()` selector (being implemented in [#8848](https://github.com/google/site-kit-wp/issues/8848)).
	* If at any point in the component's lifecycle, it is detected that a publication is available for the user, that should be set as the connected publication and the second step should be shown:
		* Text: "_You have successfully created your publication and it is now awaiting review.
This might take up to 2 weeks._"
		* CTA: "_Complete setup_". This should pass a callback to its parent component asking it to complete module setup.

### `PublicationCreate` component

In the `assets/js/module/reader-revenue-manager/components/common` directory, create a new component, `PublicationCreate.js`:

* Create a function component, `PublicationCreate` that renders the publication creation flow.
* It should receive a `onCompleteSetup` prop, a callback function to be called when the user clicks the CTA to complete the setup.
* Retrieve the publication list from the `getPublications` selector.
* Get the service URL to create a publication using the `getServiceURL` selector.
* If there is no publication in the list, render the first step of the component with the following:
    * Text: "_To complete your Reader Revenue Manager account setup you will need to create a publication._"
    * Sub-text: "_Once you have created your publication, it is submitted for review._"
    * CTA button with the label "_Create publication_" and an external link icon.
    * Pass the service URL to the CTA button's `onClick` handler.
* If a publication is available, render the second step of the component with the following:
    * Text: "_You have successfully created your publication and it is now awaiting review.
 This might take up to 2 weeks._"
    * CTA button with the label "_Complete setup_".
    * Pass the `onCompleteSetup` prop to the CTA button's `onClick` handler.
* The styles should match the [Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=171-2291&t=44sz1QCJ3moErPIh-4)

### Test Coverage

* Add storybook stories for the `PublicationCreate` component in `assets/js/module/reader-revenue-manager/components/common/PublicationCreate.stories.js`.
* Add test coverage for the `PublicationCreate` component in `assets/js/module/reader-revenue-manager/components/common/PublicationCreate.test.js`.

## QA Brief

* As of now, the `PublicationCreate` component cannot be tested individually. It should be tested as part of the Reader Revenue Manager module setup flow in #8800. However, the text and the CTA should be verified with the stories in the Storybook.
* Verify the first step of the [PublicationCreate component story](https://google.github.io/site-kit-wp/storybook/pull/9088/?path=/story/modules-readerrevenuemanager-setup-publicationcreate--without-publication) in Storybook.
* Verify the second step of the [PublicationCreate component story](https://google.github.io/site-kit-wp/storybook/pull/9088/?path=/story/modules-readerrevenuemanager-setup-publicationcreate--with-publications) in Storybook.

## Changelog entry

* Add the `PublicationCreate` component that encapsulates the publication creation flow for the Reader Revenue Manager module, presented in Storybook.

**Comment by nfmohit** [comment]
Nice work, @hussain-t ! IB LGTM 👍 ✅

**Comment by techanvil** [comment]
Hey @hussain-t, the Storybook links in the QAB were pointing to the wrong PR, so I've fixed them.

However - once the PR is merged, the Storybook deployment for the PR will be deleted, so the QAB won't be so useful when it actually comes to QA. I'm not sure if you meant to link to the `develop` Storybook, or to both the PR and `develop` versions. Anyhow, please can you update the QAB accordingly?

**Comment by hussain-t** [comment]
Thanks for pointing it out, @techanvil. I meant to point the links to `develop`.

**Comment by hussain-t** [comment]
Hi @kelvinballoo, sorry about it. Yes, you have spotted the correct URL.

As for the CTA font size, we should keep it consistent with all the buttons. Please take a look at this [comment](https://github.com/google/site-kit-wp/pull/9088#discussion_r1697036826). And the [Figma discussions](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=171-2291&t=yAXHdEfeZBlRGSWo-0#893264858).

**Comment by kelvinballoo** [comment]
### QA Update :

Thanks @hussain-t . Looks like it will be fixed under https://github.com/google/site-kit-wp/issues/8856

This ticket can be moved to approval then as the following have been verified as good:
- The text and the CTA were verified with the following stories from the Storybook:
   https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-setup-publicationcreate--without-publication 
   https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-setup-publicationcreate--with-publications
- Font size, font family, text colours are consistent with figma
- The buttons have a hover effect


   <Details>
   
   <img width="798" alt="Screenshot 2024-08-01 at 18 56 00" src="https://github.com/user-attachments/assets/3677e985-638e-40a0-be8e-2abf610bbfbd">
   
   <img width="758" alt="Screenshot 2024-08-01 at 17 58 20" src="https://github.com/user-attachments/assets/1cde6c3f-bc19-4a99-89e9-52d18b333f8f">

   </Details>
