### ISSUE TITLE
Implement `<PublicationSelect>` component

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8837]
## Feature Description

A `<PublicationSelect>` component should be added for the Reader Revenue Manager module that presents the user with a list of available publications and allows them to select one of them. The selected publication should be stored in the data store within the `publicationID` module setting, with its onboarding state stored within the `publicationOnboardingState` module setting.

<details>
<summary>Screenshot for reference</summary>

![image](https://github.com/google/site-kit-wp/assets/20284937/26726198-52c8-4bf7-90c6-5e55e790cd85)

</details>

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.cv1a01lbe7bb).
- [See Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=167-7257&t=44sz1QCJ3moErPIh-4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `PublicationSelect` component should be added for the Reader Revenue Manager module that presents the user with a dropdown of all available publications, according to [the Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=167-7257&t=44sz1QCJ3moErPIh-4).
* Its label should be "_Publication_".
* Upon selecting a publication from the dropdown, data store values of three module settings should be updated:
  * `publicationID`: Should contain the publication ID of the selected publication.
  * `publicationOnboardingState`: Should contain the onboarding state of the selected publication.
  * `publicationOnboardingStateLastSyncedAtMs`: Should contain the current time, in the form of the number of milliseconds elapsed since the epoch.

## Implementation Brief

- [x] The `analytics-4` `ProperySelect` component can be used as a reference point here.
- [x] Create a new component in `assets/js/module/reader-revenue-manager/components/common/PublicationSelect.js`. It should accept the following props.
  - [x] `isDisabled` - Flag whether Publication select should be in disabled/enable state.
  - [x] `classNames` - Class names for `Select` component from `googlesitekit-components`.
  - [x] `onChange` - Function to call when value in dropdown changes.
  - [x] `hasModuleAccess` - Flag to tell if the user has current module access.
- [x] Use the `getPublications` selector implemented in #8794 to get the list of publications. `getPublications` selector will only be called when `hasModuleAccess` is not `false` and `isDisabled` is not falsy.
    ```js
      hasModuleAccess !== false && ! isDisabled
    ```
  - [x] Add a new function `isValidPublicationID` in `assets/js/modules/analytics-4/utils/validation.js` which should check if publication ID is valid. A publication ID should be string of only alphabets and digits. This should be similar to `isValidMeasurementID` function [here](https://github.com/google/site-kit-wp/blob/9d806a503437b3a1118e249872e5fa27bba1841a/assets/js/modules/analytics-4/utils/validation.js#L150-L155).
  - [x] Add the `onPublicationChange` using `useCallback` which would be passed to `onEnhancedChange` prop of `Select` component from `googlesitekit-components`.
  - [x] `onPublicationChange` should set the `publicationID`, `publicationOnboardingState` using set method from the `create-settings-store` i.e. `setPublicationID` and `setPublicationOnboardingState`. These values should be received from `getPublications` selector.
  - [ ] Also set `publicationOnboardingStateLastSyncedAtMs` using same method, it should contain the current time, in the form of the number of milliseconds elapsed since the epoch.
  - [x] Pass the label as `Publication` to `Select` component.
  - [x] Render a `Select` component with no publications (other than if one is already selected) if `hasModuleAccess` is explicitly `false`, similar to the Analytics `PropertySelect` [component](https://github.com/google/site-kit-wp/blob/9d806a503437b3a1118e249872e5fa27bba1841a/assets/js/modules/analytics-4/components/common/PropertySelect.js#L117-L133).
  - [x] We should display a loading `ProgressBar` component if the publications are loading. Take the reference of `PropertySelect` component [here](https://github.com/google/site-kit-wp/blob/9d806a503437b3a1118e249872e5fa27bba1841a/assets/js/modules/analytics-4/components/common/PropertySelect.js#L106-L110) which does the same.
    - [x] We can use the `isResolving` selector to check if the resolver for `getPublications` is still running.

### Test Coverage

- [x] Add tests for the component with different props and combinations.

## QA Brief

**Note 1**: Ensure that you have publications setup in publisher center. Refer QAB of [this issue](https://github.com/google/site-kit-wp/issues/8791) on how to setup publications. Also, there should be atleast two publications setup for testing this.

**Note 2**: Ensure that "Custom Site URL" is NOT set in "Tester Settings" (Site Kit by Google Tester plugin).

1. Go to `Site Kit > Settings > Connecte More Services > Reader Revenue Manager`, click `Set up Reader Revenue Manager` CTA.

2. This will take you to the setup screen where initially there must be a loading progress bar till publications are getting fetched.

3. Once publications are fetched, select component will be visible.

4. Run the following command in browser console.

```js
  googlesitekit.data.select('modules/reader-revenue-manager').getSettings();
```

which should produce the following output.

```json
    {
      "publicationID": "",
      "publicationOnboardingState": "",
      "publicationOnboardingStateLastSyncedAtMs": 0
    }
```

5. Select any publication from the list and run the same command. This time there must be `publicationID` and `publicationOnboardingState` set in the response. 

6. Repeat step 5 by selecting other publications, note that every time the publication ID needs to be different.

## Changelog entry

* Provide the Settings UI to allow a user to select a publication in the Reader Revenue Manager module.

**Comment by nfmohit** [comment]
Thank you for the IB, @ankitrox ! Please take a look at my comments below:

> * Update the `getPublications` selector to also retrieve `onboardingState` in publication object. This should already be received from `GET:publications` endpoint.

Let's remove this requirement as this property should already be a part of the `getPublications` selector. See [this comment](https://github.com/google/site-kit-wp/issues/8794#issuecomment-2192576482).

---------------

I think it might be beneficial to use the Analytics `PropertySelect` component as a starting point. See points below:

1. Let's mention the usage of the `isDisabled` and `hasModuleAccess` props. The `getPublications` selector should only be called if `hasModuleAccess` isn't explicitly `false`, and `isDisabled` isn't falsy, similar to the Analytics `PropertySelect` component.
2. Let's add validation for the publication ID, i.e. `isValidPublicationID` function. This should be similar to the Analytics `isValidMeasurementID` function which checks that the value is a string which only contains alphabets and numbers.
3. Let's mention that we want to render a `Select` component with no publications (other than if one is already selected) if `hasModuleAccess` is explicitly `false`, similar to the Analytics `PropertySelect` component.
4. Let's mention that we want to display a loading progress bar when the publications are being resolved, again, similar to the Analytics `PropertySelect` component.

---------------

For Storybook stories, I don't think it'll be very valuable to add a Storybook story for this component alone. This will likely be included in the Storybook stories for the module setup and settings screens, so an individual story may seem redundant.

--------------

Let me know what you think and if you have any questions, thank you!

**Comment by ankitrox** [comment]
Thanks @nfmohit for reviewing the IB.

I have updated the IB as per the suggested points. Re-assigning to you for review.

Thanks again!

**Comment by nfmohit** [comment]
Thank you for the updates, @ankitrox ! I've made a few changes to the IB to reduce the back and forth, namely:

1. I've mentioned using Analytics `PropertySelect` as a reference point.
2. I've removed the proposal to update the `getPublications` selector for onboarding state, as that should be no longer required.
3. I made the criteria for `isValidPublicationID` a little more specific and mentioned that it should only accept alphabets and digits (no symbols).
4. I've mentioned that we can use the `isResolving` selector for `getPublications` to determine the loading state, instead of proposing to create a new selector. Working on a new selector unless necessary also includes adding test coverage for it, thus requiring more time and effort.

Please let me know if you have any questions. IB LGTM 👍 ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Few items to raise:
**ITEM 1: Copy**
The text description is currently 'This is just added as a placeholder component to assist with testing.'
Based on figma, it should be 'Select your preferred publication to connect with Site Kit'.
Is this going to be tackled under a different issue?
<Details>
Implementation:
<img width="1045" alt="Screenshot 2024-07-24 at 11 14 48" src="https://github.com/user-attachments/assets/078eeec0-fe30-4318-8fc9-ce473ba91152">

Figma:
<img width="879" alt="Screenshot 2024-07-24 at 14 31 52" src="https://github.com/user-attachments/assets/072d171a-40eb-47a6-8031-75a3fc97f13c">
</Details>

________________________________________________

**ITEM 2: Publication ID Missing and dropdown size** 
The dropdown should have included the Publication ID as well.
Currently, it doesn't.
Moreover, the size of the dropdown should be 300px wide, not 200px.

<Details>
Implementation: Dropdown is 200px wide
<img width="1040" alt="Screenshot 2024-07-24 at 14 32 13" src="https://github.com/user-attachments/assets/3916f3f7-fec7-45d3-8748-68c5899e3b0e">


Figma size is 300px:
<img width="879" alt="Screenshot 2024-07-24 at 14 31 52" src="https://github.com/user-attachments/assets/93a67245-c19c-41f8-b3ac-64a56462b16e">

</Details>

________________________________________________

**ITEM 3: Value for publicationOnboardingStateLastSyncedAtMs** 
The  "publicationOnboardingStateLastSyncedAtMs" is always 0 regardless of the publication selected.
It's also 0 after some time that I've selected the publication at the dropdown.
Are we expecting any values besides 0?

<Details>
<img width="1199" alt="Screenshot 2024-07-24 at 14 29 19" src="https://github.com/user-attachments/assets/bb6fd51a-561e-4417-9f19-d10672f3a756">
</Details>

________________________________________________

**ITEM 4: Spacing**
From the icon to the description text, it's supposed to be around 45px.
Currently, it's just 14px.

<Details>
Figma:
<img width="607" alt="Screenshot 2024-07-24 at 14 20 55" src="https://github.com/user-attachments/assets/f5acca82-c99c-4fca-9dcf-88c1710ad5fb">

Implementation:
<img width="1032" alt="Screenshot 2024-07-24 at 14 55 25" src="https://github.com/user-attachments/assets/2da4a3f1-b0f5-498d-b37a-df9fa463c16e">


</Details>

**Comment by ankitrox** [comment]
> ITEM 1: Copy

As you can see from the [discussion](https://github.com/google/site-kit-wp/pull/9006#pullrequestreview-2177046961) on previous PR, we just added the component along with the message so that it is convenience to test. We will test it thoroughly in #8800 

> ITEM 2: Publication ID Missing and dropdown size

Sorry for not including this. It looks like this was missed during our previous round. I have created a new PR #9073 to address the issue. Also, addressed the width issue in same PR, although I believe that we could have kept the width as is to maintain consistency along with other select components. We can check if there is any feedback in CR for the same.

> ITEM 3: Value for publicationOnboardingStateLastSyncedAtMs

This is will be handled in #8796 [here](https://github.com/google/site-kit-wp/pull/9017/files#diff-f7f1f0cd3d1b931b8b324172f70c4a9c90329d3f17819656e1b810a441c746b3R121) . The reason, it can't be seen in action as of now is because we are yet to integrate everything in setup screen. We can test this in #8800 

> ITEM 4: Spacing

As per the [discussion](https://github.com/google/site-kit-wp/pull/9006#pullrequestreview-2177046961) mentioned previously, we can test all the styling things in #8800

**Comment by techanvil** [comment]
Back to you for another pass, @kelvinballoo.

Please note that with regard to Item 2, the dropdown size is derived from content. As per this https://github.com/google/site-kit-wp/pull/9073#discussion_r1691287607 (which you may have already seen):

> ... the `Select` dropdown takes its width from its content, and this should be understood to be reflected in the Figma design rather than a fixed minimum width.

**Comment by kelvinballoo** [comment]
### QA update ✅ 

Noted on Item 1, 3 and 4.
Tested item 2 and the dropdown is now reflecting the Publication ID accordingly, similar to the Publisher Central.
<Details>
<img width="795" alt="Screenshot 2024-07-26 at 11 33 52" src="https://github.com/user-attachments/assets/d03c373e-ce9d-4ad9-ba49-0e52aa966fed">
</Details>

Also tested the following:

- New dropdown's label is "Publication".
- Running   `googlesitekit.data.select('modules/reader-revenue-manager').getSettings();` will give 0 if nothing is selected at the dropdown. 
   <Details>
   <img width="1114" alt="Screenshot 2024-07-26 at 11 41 01" src="https://github.com/user-attachments/assets/75a10d7e-be9b-479a-b30d-6ee40ec94557">

   </Details>

- If there a publication is selected, the details related to that publication will appear when running the script.
   <Details>
   <img width="1241" alt="Screenshot 2024-07-26 at 11 40 13" src="https://github.com/user-attachments/assets/67eb2999-37b8-47bb-a2ff-cd026dec1c55">  
   </Details>

Moving ticket to Approval.

**Comment by techanvil** [comment]
Moving this back to execution to fix the RRM `SetupMain` story that developed an error as a result of its first PR.

**Comment by aaemnnosttv** [comment]
Thanks @techanvil , merged 👍
