### ISSUE TITLE
Implement automatic refresh for RRM module setup flow

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8839]
## Feature Description

The Reader Revenue Manager module setup should support automatic refresh behaviour similar to the AdSense module's setup flow: If you navigate away for a certain amount of time and then return to the tab, it should automatically re-run the relevant API requests, to see if maybe something on the SwG API side has changed. This is crucial since all write actions happen within the Publisher Center UI and are therefore unknown to Site Kit.

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.2tl2oawlmr9o).
- This is similar to [#5532](https://github.com/google/site-kit-wp/issues/5532) from the Thank with Google epic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Similar to the AdSense module's setup flow, the fetched publications from the API should be reset and re-fetched when a user returns to the Reader Revenue Manager setup browser tab from elsewhere after 15 seconds.
- This reset and re-fetch should only happen as long as the `publicationID` module setting is not set.

## Implementation Brief

- [x] Create a generator action `resetPublications` in `assets/js/module/reader-revenue-manager/datastore/publications.js` added in #8794.
  - [x] This should clear all the errors for `getPublications` selector.
  - [x] Invalidate the resolution cache for `getPublications` using `invalidateResolutionForStoreSelector` on `modules/reader-revenue-manager` store. Refer the similar [implementation](https://github.com/google/site-kit-wp/blob/9d806a503437b3a1118e249872e5fa27bba1841a/assets/js/modules/adsense/datastore/accounts.js#L51-L65) in adsense module.
- [x] In `SetupMain` component for the module, create a function `reset`.
  - [x] It should return and do nothing if `publicationID` is set in the module settings. It can be checked using `getPublicationID` selector.
  - [x] If `publicationID` is not set, `resetPublications` action should be called.
  - [x] `useReFocus` hook should be used to call `reset` function mentioned above every 15 seconds.

### Test Coverage

Add tests for `resetPublications` action.

#### Scenario i. Publication ID is not set.

1. Activate the module. This will redirect to the setup screen.

2. There should be a progress bar which shows the publications are loading.

3. Once publications dropdown is visible, navigate away from the current tab in browser. You can open a different tab and stay there for 15+ seconds. Come back to the setup tab again and you should see that publications are loading again (a progress bar to load publications).

#### Scenario ii. Populating publications when synced.

1. Activate the module. This will redirect to the setup screen. Wait till publication dropdown appears.

2. Run the following command in browser.

```js
googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).receiveGetPublications([]);
```

This will clear all publications from dropdown.

3. Once publications dropdown is visible, navigate away from the current tab in browser. You can open a different tab and stay there for 15+ seconds. Come back to the setup tab again and you should see that publications are loading again (a progress bar to load publications). Once publication dropdown appears, you must see all publications available again.

#### Scenario iii. Publication ID is set, publications should not get loaded again.

1. Activate the module. This will redirect to the setup screen. Wait till publication dropdown appears.

2. Run the following command in browser.

```js
  const settings = {
      publicationID: "CAow6J6vDA",
      publicationOnboardingState: "ONBOARDING_ACTION_REQUIRED",
      publicationOnboardingStateLastSyncedAtMs: 0
    };

    googlesitekit.data.dispatch('modules/reader-revenue-manager').setSettings( settings );
    googlesitekit.data.dispatch('modules/reader-revenue-manager').saveSettings();
```

3. Navigate away from the current tab in browser. You can open a different tab and stay there for 15+ seconds. Come back to the setup tab again and you should see that publications are **NOT** loading again (a progress bar to load publications).

## Changelog entry

* Add periodic automatic refresh behaviour in the Reader Revenue Manager setup form.

**Comment by nfmohit** [comment]
Nice work, @ankitrox ! IB LGTM 👍 ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

One flag is that whenever the publications have already been retrieved and I click on the dropdown, there is a console error. Refer to the video attached. ⚠️ 
However, it's worth noting that after I did Scenario 3, I could not replicate this issue anymore.

<Details>

https://github.com/user-attachments/assets/52bd7082-4a9b-4e9a-ada6-19784298df77


</Details>

Other items successfully verified are as follows: ✅ 

- Scenario i. Publication ID is not set.
   <Details>
  
   https://github.com/user-attachments/assets/8bbc9af3-ec10-4d6c-9901-15d55b7f39a9
   
   </Details>

- Scenario ii. Populating publications when synced.
  The scenario is verified good overall as per the first video attached in this comment. 
   
- Scenario iii. Publication ID is set, publications should not get loaded again.
   <Details>
   
   https://github.com/user-attachments/assets/e5d6978f-7350-48bf-bb9a-2222db3b755e

   </Details>

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

After a round of review, this aria hidden console error actually happens on other SK module dropdowns as well.
Hence, this will be tackled in a separate issue, logged here: https://github.com/google/site-kit-wp/issues/9142

This ticket is good to be moved to approval.

The 3 scenarios were verified good: ✅ 

- Scenario i. Publication ID is not set.
   Reloading happens as expected.
   <Details>
  
   https://github.com/user-attachments/assets/8bbc9af3-ec10-4d6c-9901-15d55b7f39a9
   
   </Details>

- Scenario ii. Populating publications when synced.
   Reloading happens as expected.
   <Details>
  
   https://github.com/user-attachments/assets/52bd7082-4a9b-4e9a-ada6-19784298df77
  
   </Details>
   
- Scenario iii. Publication ID is set, publications should not get loaded again.
   Reloading does not happen, as expected.
   <Details>
   
   https://github.com/user-attachments/assets/e5d6978f-7350-48bf-bb9a-2222db3b755e

   </Details>
