### ISSUE TITLE
iThemes Security compatibility: 414 errors on ongoing fetch requests

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#884]
While we advise users to disable the _Long URLs Strings > Filter Long URLs_ option during the setup process to avoid 414 errors at this point, it also appears from[ a recent report](https://wordpress.org/support/topic/error-414-on-callback/) and also in testing that it can disrupt ongoing fetch requests and prevent data from displaying on the dashboard. Disabling the option appears to restore dashboard data. 

1) Enable iThemes Security option: _Settings > System Tweaks > Configure Settings> Long URL Strings > Filter Long URL Strings_
2) Go to the Site Kit Dashboard and observe missing data on the dashboard, console errors in the browser. 

## Screenshots

[Video recording](https://recordit.co/mRbicnB7Lc)

[Browser console error](https://jumpshare.com/v/UgEC8JMZzzzT195XwFRz) 

## Additional Context

 - PHP Version: 7.1.33
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.0.4
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ThierryA** [comment]
Closing this one as the cause of this bug is the same as #917

**Comment by aaemnnosttv** [comment]
This should be fixed by #779 which would no longer require users to disable long URL filtering.
