### ISSUE TITLE
Implement RRM module setup success banner

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8840]
## Feature Description

A subtle notification component should be used to implement the setup success banner for the Reader Revenue Manager module. The copy of the banner will vary depending on the onboarding state of the connected publication.

<details>
<summary>Screenshots for reference</summary>

Publication is awaiting review:
![image](https://github.com/google/site-kit-wp/assets/20284937/38940ecb-848a-4c8d-b4ee-e799dfca00ac)

User needs to perform additional steps to complete publication setup:
![image](https://github.com/google/site-kit-wp/assets/20284937/7ab65018-ced3-41db-aeff-ed56fecafc82)

Publication setup is complete:
![image](https://github.com/google/site-kit-wp/assets/20284937/791fac64-2015-4814-b5c2-7858ffebcca7)

</details>

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.pcu7c9yrp3ii).
- [See Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=177-1698&t=44sz1QCJ3moErPIh-4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The module setup success banner should be implemented for the Reader Revenue Manager with the aid of a subtle notification according to [the Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=177-1698&m=dev).
* The contents of the success notification will vary based on the onboarding status of the connected publication.
	* If the publication has completed setup and is ready for use:
		* The notification should be in the success variant.
		* Text: "_Your Reader Revenue Manager account was successfully set up!_"
		* Sub-text: "_Unlock your full reader opportunity by enabling features like subscriptions, contributions and newsletter sign ups in the Reader Revenue Manager settings._"
		* CTA: "_Customize settings_" (with an external link icon). This should open the publication in Reader Revenue Manager on a new browser tab.
		* Dismissal: "_Maybe later_". This should persistently dismiss the notification.
	* Publication is awaiting review:
		* The notification should be in the success variant.
		* Text: "_Your Reader Revenue Manager account was successfully set up!_"
		* Sub-text: "_Your publication is still awaiting review, you can check its status in Reader Revenue Manager._"
		* CTA: "_Check publication status_" (with an external link icon). This should open the publication in Reader Revenue Manager on a new browser tab.
		* Dismissal: "_Got it_". This should persistently dismiss the notification.
	* Publication needs additional steps from the user:
		* 	The notification should be in the warning variant.
		* Text: "_Your Reader Revenue Manager account was successfully set up, but your publication still requires further setup in Reader Revenue Manager._"
		* CTA: "_Complete publication setup_" (with an external link icon). This should open the publication in Reader Revenue Manager on a new browser tab.
		* Dismissal: "_Got it_". This should persistently dismiss the notification.
* It should adhere to the mobile designs in Figma [here](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=545-5470&m=dev).

### Reusable `SubtleNotification` component

In the `assets/js/components/notifications` directory, create a new component, `SubtleNotification.js`:

* [ ] Create a function component, `SubtleNotification` that renders a notification with the following props:
    * [ ] `title`: The title of the notification.
    * [ ] `description`: The description of the notification.
    * [ ] `icon`: The icon for the notification (optional).
    * [ ] `ctaLabel`: The label for the CTA button.
    * [ ] `ctaLink`: The URL for the CTA button.
    * [ ] `onCTAClick`: A callback function to handle the CTA button click.
    * [ ] `ctaLinkExternal`: A boolean to indicate if the CTA link should open in a new tab and show an external link icon.
    * [ ] `dismissLabel`: The label for the dismiss button.
    * [ ] `onDismiss`: A callback function to dismiss the notification.
    * [ ] `variant`: The variant of the notification (success or warning). By default, it should be `success`.
    * [ ] Add more props as needed.
* [ ] The component should render a similar structure like other SubtleNotification components. For example, see, [SetupSuccessSubtleNotification](https://github.com/google/site-kit-wp/blob/9e1a4c20d446b2998562b72cc58fb86a0ea5bce0/assets/js/modules/ads/components/notifications/SetupSuccessSubtleNotification.js) and [AudienceSegmentationSetupSuccessSubtleNotification](https://github.com/google/site-kit-wp/blob/341d89341bb3f708ae8217e305068fc64522fa70/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupSuccessSubtleNotification.js).
* [ ] Conditionally apply the `googlesitekit-subtle-notification--warning` class to the notification container if the variant is `warning`.
* [ ] Render the success `check-fill.svg` icon if the variant is `success`.
* [ ] Render the warning `warning.svg` icon if the variant is `warning`.
* [ ] If the `icon` prop is provided, render the provided icon.
* [ ] Add the `googlesitekit-subtle-notification--warning` class styles and any other necessary styles for the component in `assets/sass/components/dashboard/_googlesitekit-subtle-notification.scss`.

### RRMSetupSuccessSubtleNotification component

In `assets/js/modules/reader-revenue-manager/components`, add a new `dashboard` directory and create a new component, `RRMSetupSuccessSubtleNotification.js`:

* [ ] Create a function component `RRMSetupSuccessSubtleNotification` that renders the setup success notification for the Reader Revenue Manager module.
* [ ] Create a constant `READER_REVENUE_MANAGER_SETUP_SUCCESS_NOTIFICATION` OR `RRM_SETUP_SUCCESS_NOTIFICATION`.
* [ ] Check if the notification has been dismissed using the `isItemDismissed` selector.
* [ ] If it has been dismissed, return `null`.
* [ ] Retrieve the publication onboarding status using the `getPublicationOnboardingState` selector.
* [ ] Retrieve the publication ID using the `getPublicationID` selector.
* [ ] Retrieve the service URL for the current publication ID using the `getServiceURL` selector and pass the publication ID as an argument.
* [ ] If the publication onboarding status is `ONBOARDING_COMPLETE`, return the `SubtleNotification` component with the following props:
    * `title`: As per the AC.
    * `description`: As per the AC.
    * `ctaLabel`: As per the AC.
    * `ctaLink`: The retrieved service URL.
    * `dismissLabel`: As per the AC.
    * `onDismiss`: A callback function that dispatches the `dismissItem` action.
    * `ctaLinkExternal`: `true`
    * `variant`: `success` (optional).
* [ ] If the publication onboarding status is `PENDING_VERIFICATION`, return the `SubtleNotification` component with the following props:
    * `title`: As per the AC.
    * `description`: As per the AC.
    * `ctaLabel`: As per the AC.
    * `ctaLink`: The retrieved service URL.
    * `dismissLabel`: As per the AC.
    * `onDismiss`: A callback function that dispatches the `dismissItem` action.
    * `ctaLinkExternal`: `true`
    * `variant`: `success` (optional).
* [ ] If the publication onboarding status is `ONBOARDING_ACTION_REQUIRED`, return the `SubtleNotification` component with the following props:
    * `title`: As per the AC.
    * `ctaLabel`: As per the AC.
    * `ctaLink`: The retrieved service URL.
    * `dismissLabel`: As per the AC.
    * `onDismiss`: A callback function that dispatches the `dismissItem` action.
    * `ctaLinkExternal`: `true`
    * `variant`: `warning`.
* [ ] It should match the mobile designs in Figma [here](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=545-5470&m=dev).
* **Note**: The source of truth for the copies should be the [Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=177-1698&t=44sz1QCJ3moErPIh-4).

### Add the notification to the Dashboard

In `assets/js/components/notifications/SubtleNotifications.js`:

* [ ] Render the `RRMSetupSuccessSubtleNotification` component only if the `rrmModule` feature flag is enabled.

### Test Coverage

* Add storybook stories for the `SubtleNotification` component in `assets/js/components/notifications/SubtleNotification.stories.js`.
* Add storybook stories for the `RRMSetupSuccessSubtleNotification` component in `assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.stories.js`.
* Add unit tests for the `SubtleNotification` component in `assets/js/components/notifications/SubtleNotification.test.js`.

#### Prerequisite
* Use the latest version of the Tester plugin to change the publication onboarding state and verify the different banner notifications.
* Disconnect the RRM module and reconnect whenever you change the publication onboarding state from the tester plugin.
---
* Since #8800 has been merged, it is now possible to setup RRM without any snippets using normal flows. 
* To fully test all variations of the success notice, we will need 3 publications with different states as described in AC. 
* After enabling `rrmModule` feature flag, go through the RRM setup flow. Once complete, the success notification should show up based on the status of the connected publication. 
* Ensure the secondary CTA dismisses the notification.

## Changelog entry

* Add the Reader Revenue Manager module success setup banner notification.

**Comment by nfmohit** [comment]
Thank you for the brilliant IB, @hussain-t ! Please take a look at my comments below:

1. What do you think of changing the `external` prop for `SubtleNotification` to `ctaLinkExternal`? That way, the prop is a little more meaningful.
2. The copy to use within the banner shouldn't be re-written in the IB, instead, the AC should be used as the source of truth. What do you think about updating them to reference the ACs?

Please let me know what you think, thank you!

**Comment by hussain-t** [comment]
Thanks, @nfmohit. I initially included the copies in the IB to accommodate reviewers who prefer to have the text repeated for clarity. However, as suggested, I have updated the IB to reference the ACs directly. The source of truth for the copies should be the Figma design.

**Comment by nfmohit** [comment]
Thanks @hussain-t ! IB LGTM 👍 ✅

**Comment by hussain-t** [comment]
Hi @nfmohit, just a heads-up: we have another issue (#8725) in progress to implement a reusable `SubtleNotification` component. cc: @ivonac4.

**Comment by nfmohit** [comment]
@kuasha420 Just wanted to share a few observations that I noticed while reviewing [another issue](https://github.com/google/site-kit-wp/issues/8838) that uses the `SubtleNotification` component extracted here:

1. The color of the info icon in the warning state is not correct.
Figma:
![image](https://github.com/user-attachments/assets/a2a17021-b80f-4aca-b42e-ddc97bffc0b6)
Implementation:
![image](https://github.com/user-attachments/assets/21d99759-9181-4c06-b8e2-8f5d7922c1ae)
2. The state icon disappears in smaller viewports.
Figma:
![image](https://github.com/user-attachments/assets/eaf01080-814e-49db-bca3-5c752f96e8c7)
Implementation:
![image](https://github.com/user-attachments/assets/41040689-80f8-4d13-9303-4f486dbf4196)

CC: @hussain-t

**Comment by hussain-t** [comment]
Thanks for spotting this, @nfmohit. 

>The state icon disappears in smaller viewports.

That’s the default behavior of the Subtle Notification implementation. We should review the other Subtle Notification designs in Figma to check if the icon is visible in smaller viewports. I think we should ensure consistency across all notifications, whether the icon is visible or not.

**Comment by nfmohit** [comment]
Sounds good, thank you @hussain-t !

@kuasha420 - One additional observation (as @wpdarren pointed out [here](https://docs.google.com/document/d/15q0J74SLS10jCtSx_FWbSGxoFhOhNSZFQ58uz_kmBDQ/edit#bookmark=id.c0uf2behiqa3)):

This setup success banner should also prevent the display of the original module setup success banner. I think this could've been mentioned explicitly in the ACs.

**Comment by nfmohit** [comment]
> Thanks for spotting this, @nfmohit.
> 
> > The state icon disappears in smaller viewports.
> 
> That’s the default behavior of the Subtle Notification implementation. We should review the other Subtle Notification designs in Figma to check if the icon is visible in smaller viewports. I think we should ensure consistency across all notifications, whether the icon is visible or not.

@hussain-t On this topic, I also checked [the Figma designs](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1711-17131&m=dev) for the Subtle Notification in Audience Segmentation, and that does seem to include the icon in smaller viewports. See:

![image](https://github.com/user-attachments/assets/cbe45bb9-5633-4b9a-9691-cd6d690bbe23)

It looks like we do not have mobile designs for `GA4AdSenseLinkedNotification`, `PAXSetupSuccessSubtleNotification`, or Ads `SetupSuccessSubtleNotification`.

Based on my observation, it looks like we should be keeping the icon for the smaller viewports. What do you think?

**Comment by hussain-t** [comment]
Thanks for confirming, @nfmohit. SGTM 👍

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

I've tested this and I will document down additional ITEMS here, starting to number it as from 3 and leave item 1 and 2 as what @nfmohit has highlighted in [this comment](https://github.com/google/site-kit-wp/issues/8840#issuecomment-2282733037).

I am assigning this to @kuasha420 for fixes.

Meanwhile, I am also tagging @nfmohit and @wpdarren in this because we did refer to @wpdarren 's observations under [this document](https://docs.google.com/document/d/15q0J74SLS10jCtSx_FWbSGxoFhOhNSZFQ58uz_kmBDQ/edit#heading=h.ws0r7rk3hw0d). I am not sure if we want to create additional tickets for those or which ones should sit within this issue as items 7 onwards. Would be great if you can review this so that we can track the issues better.

**ITEM 3:**
This is more of a clarification. 
What is the expectation for the disappearance of the banners? Currently if we reload the page, the banner remains but if we go to another page (e.g. settings) and come back to the dashboard, it will be gone.

More context in the video below.

<Details>

https://github.com/user-attachments/assets/5e32de70-db15-49de-93b9-b237ccc50a1b

</Details>
_______________________________________________________________

**ITEM 4:**
It's been highlighted in @nfmohit 's comment about the icon not being there on mobile.
I wanted to highlight the warning variant banner on mobile at 375px. Based on the figma at 375px, everything will appear correctly. However, in the actual implementation, the buttons are wrapping on 2 lines.

<Details>
Figma:
<img width="408" alt="Screenshot 2024-08-14 at 14 50 45" src="https://github.com/user-attachments/assets/a832dba6-eff0-4272-92a3-58f116305753">

Implementation:
<img width="423" alt="Screenshot 2024-08-14 at 14 51 11" src="https://github.com/user-attachments/assets/264b1e11-0f39-418c-812e-a66e05fac621">

</Details>

_______________________________________________________________

**ITEM 5:**
On tablet, the banners just look weird in my opinion.
Refer to the picture attached. There is a very dense block of text and the buttons sections have a lot of space. This feels unbalanced. I'm wondering if it might be best to move the buttons below and let the text sit along the width of the banner.

<Details>
<img width="585" alt="Screenshot 2024-08-13 at 18 04 07" src="https://github.com/user-attachments/assets/158be016-d1a0-4017-8173-b2622b3d1bc9">

</Details>

_______________________________________________________________

**ITEM 6:**
There is this part of the QAB which states : "Ensure both the primary and secondary CTAs dismiss the notification."
I understand that even clicking the CTAs would dismiss the notification.
I wanted us to review this because I felt like it was a bad experience personally.
My suggestion would be if we click on CTAs like 'Check publication status', it's not necessary to dismiss the notification?

More context in the video below:
<Details>

https://github.com/user-attachments/assets/7b99cfbe-e71a-44e5-9b28-afe5f9bd50da


</Details>

**Comment by kuasha420** [comment]
Thank you @hussain-t @nfmohit and @kelvinballoo !

I've filed a follow up [PR](https://github.com/google/site-kit-wp/pull/9207) to fix most of the points raised. In addition- 

**ITEM 3** - This is consistent with the Setup Success Notifications of other modules. So this can move ahead as is. However, I think we need to show a similar notification if the publication needs further attention, once this notification is no longer displayed. Is there a issue filed for that, @nfmohit?

**ITEM 5** - That's a good point, however, I couldn't find a design for tablet for Subtle Notification. Feel free to create a separate issue for this, and we can ask Sigal for a tablet design. 

**ITEM 6** - This was decided during CR [here](https://github.com/google/site-kit-wp/pull/9117#discussion_r1705359357). I think it makes sense to dismiss the notifications on both CTA, but doesn't have a strong opinion either way. Any thoughts @nfmohit @hussain-t @techanvil ? 

Thanks all!

**Comment by techanvil** [comment]
Hmm, actually I am not sure it's such a good idea to dismiss the notifications when the CTA is an external link.

There's no way of knowing for sure if the user successfully navigated to the link when clicking on the CTA, so it would be useful to keep the notification open in case they need to click on it again. That's my 2p on the issue, anyway.

**Comment by nfmohit** [comment]
> Hmm, actually I am not sure it's such a good idea to dismiss a notification when the CTA is an external link.
> 
> There's no way of knowing for sure if the user successfully navigated to the link when clicking on the CTA, so it would be useful to keep the notification open in case they need to click on it again. That's my 2p on the issue, anyway.

@techanvil I agree. In the follow-up PR, we've removed the dismissal from the primary CTA. Thank you!

**Comment by techanvil** [comment]
Top stuff, thanks @nfmohit.

**Comment by nfmohit** [comment]
Hi @kelvinballoo ! This is now back with you as we've addressed your observations with a follow-up PR:


> Meanwhile, I am also tagging @nfmohit and @wpdarren in this because we did refer to @wpdarren 's observations under [this document](https://docs.google.com/document/d/15q0J74SLS10jCtSx_FWbSGxoFhOhNSZFQ58uz_kmBDQ/edit#heading=h.ws0r7rk3hw0d). I am not sure if we want to create additional tickets for those or which ones should sit within this issue as items 7 onwards. Would be great if you can review this so that we can track the issues better.

I think most of these concerns have been addressed, or Asana tasks have been created for them. Please let me know otherwise.

> **ITEM 3:**
> @kelvinballoo - This is more of a clarification.
> What is the expectation for the disappearance of the banners? Currently if we reload the page, the banner remains but if we go to another page (e.g. settings) and come back to the dashboard, it will be gone.
>
> @kuasha420 - This is consistent with the Setup Success Notifications of other modules. So this can move ahead as is. However, I think we need to show a similar notification if the publication needs further attention, once this notification is no longer displayed. Is there a issue filed for that, @nfmohit?

This is how the UX was defined. We will have notices in the module settings screens if the publication requires further setup/is pending verification. If you think it would be better to persist this notification *until dismissed*, could you please add this as a "Nice to Have" in the [bug bash board](https://app.asana.com/0/1207894970935603/list)? Thank you!

> **ITEM 4:**
> It's been highlighted in @nfmohit 's comment about the icon not being there on mobile.
> I wanted to highlight the warning variant banner on mobile at 375px. Based on the figma at 375px, everything will appear correctly. However, in the actual implementation, the buttons are wrapping on 2 lines.

This has been addressed in a way such that if there is not enough space for the buttons (in extremely shrunk viewports), we'll stack the buttons so that one appears on top of another.

> **ITEM 5:**
> @kelvinballoo - On tablet, the banners just look weird in my opinion.
> Refer to the picture attached. There is a very dense block of text and the buttons sections have a lot of space. This feels unbalanced. I'm wondering if it might be best to move the buttons below and let the text sit along the width of the banner.
>
> @kuasha420 - That's a good point, however, I couldn't find a design for tablet for Subtle Notification. Feel free to create a separate issue for this, and we can ask Sigal for a tablet design.

@kelvinballoo If you do open an issue about this, please let it be a general enhancement issue for all subtle notifications, not specific to RRM. Thanks!

> **ITEM 6:**
> There is this part of the QAB which states : "Ensure both the primary and secondary CTAs dismiss the notification."
> I understand that even clicking the CTAs would dismiss the notification.
> I wanted us to review this because I felt like it was a bad experience personally.
> My suggestion would be if we click on CTAs like 'Check publication status', it's not necessary to dismiss the notification?

We have changed this so that the banner is not dismissed anymore as part of the primary CTA.

Please let me know if you have any other concerns, thank you!

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @nfmohit , @kuasha420 , this is tested good overall.
I have one item to highlight which is ITEM 4. The remaining were reviewed as good.

**ITEM 4** ⚠️ 
Stacking is working great.
That said, personally, it will look better if the primary CTA (e.g. customize CTA) is at the top and 'Maybe later' CTA is at the bottom. It would be consistent with how the RRM dashboard banner is. Details are below.

I agree this is subjective and possibly it doesn't need to be done under this ticket. Maybe we can have a conversation with Sigal on this. 

<Details>
Current implementation is like this.
<img width="579" alt="Screenshot 2024-08-20 at 21 06 51" src="https://github.com/user-attachments/assets/5c9752ee-3298-4c53-8a1a-47c2d62e9473">

Compared to the RRM dashboard banner, the '**Maybe later**' button is at the bottom:
<img width="401" alt="Screenshot 2024-08-20 at 21 07 31" src="https://github.com/user-attachments/assets/7632f868-5e13-4ebf-bb39-09ce39dd8152">

</Details>
_______________________________________

**ITEM 1** ✅ 
Colour of the icon is now correct at rgb(78, 51, 0) which is #4e3300

<Details>
<img width="802" alt="Screenshot 2024-08-20 at 20 54 51" src="https://github.com/user-attachments/assets/332fe898-86a6-4c3c-86e8-b2545f2ae7c3">

</Details>

______________________________________________________

**ITEM 2** ✅ 
The state icon now appears on smaller viewports.

<Details>
<img width="543" alt="Screenshot 2024-08-20 at 20 57 22" src="https://github.com/user-attachments/assets/703889a6-1d4b-477d-8337-4c93bd9e4d69">

</Details>

______________________________________________________

**ITEM 3** ✅ 
Noted on this.
Added a ticket here : https://app.asana.com/0/1207894970935603/1208105264866854

______________________________________________________

**ITEM 5** ✅ 

Agreed. New ticket raised here: https://github.com/google/site-kit-wp/issues/9215

______________________________________________________

**ITEM 6** ✅ 
Clicking the primary CTA will not dismiss the banner. Tested across all three variants.
'Maybe later' and 'Got it' buttons would dismiss the banner as expected.

<Details>

https://github.com/user-attachments/assets/9d4d4b3c-e7cd-4645-b86d-696121e1e919


</Details>

**Comment by nfmohit** [comment]
> ITEM 4 ⚠️
> Stacking is working great.
> That said, personally, it will look better if the primary CTA (e.g. customize CTA) is at the top and 'Maybe later' CTA is at the bottom. It would be consistent with how the RRM dashboard banner is. Details are below.
> 
> I agree this is subjective and possibly it doesn't need to be done under this ticket. Maybe we can have a conversation with Sigal on this.

Thank you @kelvinballoo. I would suggest creating a new general improvement issue for this so that we can put this suggestion for all subtle notifications. Thank you.

**Comment by kelvinballoo** [comment]
### QA Update ✅  

Thanks for checking @nfmohit . This is good to go.
Moving to approval

**ITEM 1** ✅ 
Colour of the icon is now correct at rgb(78, 51, 0) which is #4e3300

<Details>
<img width="802" alt="Screenshot 2024-08-20 at 20 54 51" src="https://github.com/user-attachments/assets/332fe898-86a6-4c3c-86e8-b2545f2ae7c3">

</Details>

______________________________________________________

**ITEM 2** ✅ 
The state icon now appears on smaller viewports.

<Details>
<img width="543" alt="Screenshot 2024-08-20 at 20 57 22" src="https://github.com/user-attachments/assets/703889a6-1d4b-477d-8337-4c93bd9e4d69">

</Details>

______________________________________________________

**ITEM 3** ✅ 
Noted on this.
Added a ticket here : https://app.asana.com/0/1207894970935603/1208105264866854

______________________________________________________

**ITEM 4** ✅  
Raised a new enhancement ticket under https://github.com/google/site-kit-wp/issues/9216

_______________________________________

**ITEM 5** ✅ 

Agreed. New ticket raised here: https://github.com/google/site-kit-wp/issues/9215

______________________________________________________

**ITEM 6** ✅ 
Clicking the primary CTA will not dismiss the banner. Tested across all three variants.
'Maybe later' and 'Got it' buttons would dismiss the banner as expected.

<Details>

https://github.com/user-attachments/assets/9d4d4b3c-e7cd-4645-b86d-696121e1e919


</Details>
