### ISSUE TITLE
Implement settings view screen for RRM

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8842]
## Feature Description

The module settings view screen should be added for the Reader Revenue Manager module. The screen should simply show the ID of the connected publication.

<details>
<summary>Screenshot for reference</summary>

![image](https://github.com/google/site-kit-wp/assets/20284937/9046525b-8af0-41f3-8ba8-eded310d9b87)

</details>

- [See relevant section in design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.z2ekvg8ebd6).
- [See Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=5-2621&t=Ak0pmctRhN9T0mT2-4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The module settings view screen should be implemented for the Reader Revenue Manager module according to [the Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=192-2702&m=dev).
* The screen should display the ID of the connected publication (labelled as "_Publication_"), followed by a notice that conveys the publication onboarding state (via the `<PublicationOnboardingStateNotice>` component being implemented by [#8838](https://github.com/google/site-kit-wp/issues/8838)).

## Implementation Brief

- [x] In `assets/js/modules/reader-revenue-manager/components/settings/SettingsView.js` component added in #8786, retrieve the publication ID with `useSelect` using `getPublicationID` selector.
- [x] Return a `div` container with `googlesitekit-setup-module` class name which should wrap the following element with the mentioned structure as below.
  - [x] A wrapper `div` with the class name `googlesitekit-settings-module__meta-items` and inside it another `div`with class `googlesitekit-settings-module__meta-item`.
  - [x] The setting label should be an `h5` with the class name `googlesitekit-settings-module__meta-item-type` and the setting value should be a `p` with the class name `googlesitekit-settings-module__meta-item-data`, that renders a `DisplaySetting` component with the value as publication ID.
  - [ ] A [reference](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/components/settings/SettingsView.js#L79-L87) of `assets/js/modules/analytics-4/components/settings/SettingsView.js`  can be taken to build in similar way.
- [x] Add the `PublicationOnboardingStateNotice` component to the main wrapper div.

### Test coverage

- Add story for the component.

#### Prerequisite

* Use the latest version of the Tester plugin to change the publication onboarding state and verify the different notices.
* Disconnect the RRM module and reconnect whenever you change the publication onboarding state from the tester plugin.
---
* Ensure that you have publications set up in the publisher center.
* Enable the `rrmModule` feature flag in the tester plugin.
* Activate the Reader Revenue Manager module.
* Go to `Site Kit > Settings > Reader Revenue Manager`.
* Verify that the publication ID is displayed in the settings view screen.
* Verify that the publication onboarding state notice is displayed below the publication ID for the `ONBOARDING_ACTION_REQUIRED` and `PENDING_VERIFICATION` onboarding states.
* Note that the `Publication` label and the publication ID value font styles differ in the current implementation. The current implementation adheres to the other modules' settings view screen styles.

## Changelog entry

* Implement the settings view screen for the Reader Revenue Manager module.

**Comment by nfmohit** [comment]
Thank you for the IB, @ankitrox ! Please take a look at my comments below:

> * Return a `div` container with `googlesitekit-setup-module` class name which should wrap following element.

An additional class name specific to the module would be nice to add, i.e. `googlesitekit-setup-module--reader-revenue-manager`.

> * A heading `Publication` and text which should be the publication ID. Note that the heading is smaller than the ID text. Please refer to the [figma design](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=5-2621&t=EfgkG9osYjAvVip8-0). These both elements should be wrapped within a single `div`.

Using the appropriate class names and components in crucial here. Let's mention using the wrapper `div` to use the `googlesitekit-settings-module__meta-item` class, which should also have another wrapper `div` with the class `googlesitekit-settings-module__meta-items`.

The setting label should be an `h5` with the class name `googlesitekit-settings-module__meta-item-type` and the setting value should be a `p` with the class name `googlesitekit-settings-module__meta-item-data`, that renders a `DisplaySetting` component with the publication ID.

It may also be beneficial to reference another module's `SettingsView` component to get an idea of the structure, e.g. `assets/js/modules/analytics-4/components/settings/SettingsView.js`. Using the appropriate markup is crucial to ensure a consistent structure.

---------------

Please let me know if you have any questions, thank you!

**Comment by ankitrox** [comment]
Thank you @nfmohit . I've updated the IB as per mentioned points.

**Comment by nfmohit** [comment]
Thank you @ankitrox . I've made some minor linguistic improvements to the IB, it looks good to me 👍 

IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

This is good overall. I was able to run the script and the settings view screen looks like Figma with the correct styling to align with existing styling.
<Details>
<img width="1109" alt="Screenshot 2024-08-06 at 11 37 20" src="https://github.com/user-attachments/assets/5e46305d-d407-42e9-9d14-76d7ee054f9c">
</Details>
__________________________________________________________________


I have 2 clarifications though:
**CLARIFICATION 1:** ⚠️ 
There are 3 variations of the settings view screen:

1. Without the notice
2. With the notice 'Your publication is still awaiting review. you can check its status in Reader Revenue Manager.'
3. With the notice 'Your publication requires further setup in Reader Revenue Manager'

Currently, I can only get the 3rd variation.
Could you guide me on how to setup and review the 1st and 2nd variations please?

**CLARIFICATION 2:** ⚠️ 
This is out of scope for this ticket but checking in case we need to create another ticket or it's being handled in an existing ticket. 
When I click on the '[**See full details in Reader Revenue Manager**]' link, I get routed to a page hitting 400 error.
The error page is attached.

<Details>
<img width="1065" alt="Screenshot 2024-08-06 at 11 36 55" src="https://github.com/user-attachments/assets/d9d16e4d-5620-43b5-9c47-61d1ef66ffbf">

</Details>

**Comment by hussain-t** [comment]
Hi @kelvinballoo,

>There are 3 variations of the settings view screen:

Please use the tester plugin to change the publication onboarding state. I have updated the QAB.

>CLARIFICATION 2: ⚠️
This is out of scope for this ticket but checking in case we need to create another ticket or it's being handled in an existing ticket.
When I click on the '[See full details in Reader Revenue Manager]' link, I get routed to a page hitting 400 error.
The error page is attached.

This is a bug. However, as you said, it's out of the scope. Feel free to create a new ticket.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @hussain-t .

All 3 variations were verified and they are appearing accordingly:
- Without the notice ✅ 
   <Details>
   
   <img width="1143" alt="Screenshot 2024-08-06 at 13 50 32" src="https://github.com/user-attachments/assets/f8d9f62b-031f-42b4-a189-aef21de4233a">

   </Details>

- With the notice 'Your publication is still awaiting review. You can check its status in Reader Revenue Manager.' ✅ 
   <Details> 
   
   <img width="1140" alt="Screenshot 2024-08-06 at 13 58 02" src="https://github.com/user-attachments/assets/977f0701-1738-400e-b48d-3468cedf1200">

   </Details>   

- With the notice 'Your publication requires further setup in Reader Revenue Manager' ✅ 
   <Details>
   
   <img width="1109" alt="Screenshot 2024-08-06 at 11 37 20" src="https://github.com/user-attachments/assets/81265f76-b005-4576-b81f-a5aa5b48973c">

   </Details>
   
As for the Clarification 2, I've raised another ticket separately here: https://github.com/google/site-kit-wp/issues/9144

As for this ticket, it's good to move to Approval.
