### ISSUE TITLE
Implement `Web_Tag` for RRM

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8844]
## Feature Description

A `Web_Tag` class should be added for the Reader Revenue Manager module that implements the RRM snippet output logic.

- [See the relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.828fgfgqt012).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Reader Revenue Manager module, when connected, should enqueue the `swg-basic.js` external JavaScript file, as well as output a snippet in the website front-end.
* The URL of the external JavaScript file is: `https://news.google.com/swg/js/v1/swg-basic.js`.
* The snippet, which is mostly static with a couple of dynamic inputs, is as follows:
```js
<script>
  (self.SWG_BASIC = self.SWG_BASIC || []).push( basicSubscriptions => {
    basicSubscriptions.init({
      type: "NewsArticle",
      isPartOfType: ["Product"],
      isPartOfProductId: "PUBLICATION-ID-PLACEHOLDER:openaccess",
      clientOptions: { theme: "light", lang: "en-GB" },
    });
  });
</script>
```
* The `PUBLICATION-ID-PLACEHOLDER` should be replaced with the connected publication ID.
* The language should be obtained from WordPress, e.g. by using the [`get_locale` WordPress function](https://developer.wordpress.org/reference/functions/get_locale/), but replacing the underscore (e.g. `en_US`) with a dash (e.g. `en-US`) as shown in the above snippet.
* The up-to-date instructions for placing the snippet can be found here: `https://publishercenter.google.com/reader-revenue-manager/cms-sync?publication=PUBLICATION-ID` (input your publication ID in the URL).

## Implementation Brief

* [ ] **Create the `Web_Tag` class for RRM:**
    * [ ] Create a new file `includes/Modules/Reader_Revenue_Manager/Web_Tag.php`.
    * [ ] This class should extend `Module_Web_Tag` and use the `Method_Proxy_Trait` & `Tag_With_DNS_Prefetch_Trait` traits.
* [ ] **Implement the `Web_Tag` class:**
    * [ ] Add a public `register` method:
        * [ ] Hook into the `wp_enqueue_scripts` action using `get_method_proxy` to call `enqueue_swg_basic_js` method to enqueue the external JavaScript file (`swg-basic.js`) from the URL `https://news.google.com/swg/js/v1/swg-basic.js` and output the dynamic inline script.
        * [ ] Add a `wp_resource_hints` filter to add DNS prefetch hints for `//news.google.com`.
        * [ ] Invoke the `do_init_tag_action` method to initialize the tag.
* [ ] **Enqueue scripts:**
    * [ ] Add a protected `enqueue_swg_basic_js` method:
        * [ ] Retrieve the publication ID from the `tag_id` class property, i.e. `$this->tag_id`.
        * [ ] Retrieve the site locale using the `get_locale()` function and format it by replacing the underscore with a dash as shown in the snippet above in the AC.
        * [ ] Register the `swg-basic.js` script using `wp_register_script( 'google_swgjs', 'https://news.google.com/swg/js/v1/swg-basic.js', array(), null, true )`.
        * [ ] Add the dynamic inline script using `wp_add_inline_script( 'google_swgjs', $inline_script, 'before' )`.
        * [ ] Enqueue the registered `google_swgjs` script.
* For example, see how it's implemented in Thank with Google module in the `Web_Tag` class [here](https://github.com/google/site-kit-wp/blob/1.89.0/includes/Modules/Thank_With_Google/Web_Tag.php?rgh-link-date=2024-07-09T21%3A43%3A19Z).
* [ ] **Update the RRM Module Class:**
    * [ ] Edit the `Google\Site_Kit\Modules\Reader_Revenue_Manager` class.
    * [ ] In the `register` method, hook into `template_redirect` action and invoke a new method `register_tag` only if the module is connected.
    * [ ] Implement the `register_tag` method:
        * [ ] Get the module settings.
        * [ ] Instantiate the `Web_Tag` class and pass it the `publicationID` setting.
        * [ ] If the tag is not blocked (`is_tag_blocked`), include `Tag_Environment_Type_Guard` and `Tag_Verify_Guard` in the `use_guard` method. If the tag `can_register`, invoke the `register` method on it.

### Test Coverage

* Add test coverage for the `Web_Tag` class.

## QA Brief

- Set up Site Kit.
- Turn on the `rrmModule` feature flag.
- Go to Site Kit _Settings -> Connect More Services_ and activate the Reader Revenue Manager module.
- Run the following script in the browser console to connect the RRM module:
	```js
	const settings = {
		publicationID: "CAow6J6vDA",
		publicationOnboardingState: "ONBOARDING_STATE_UNSPECIFIED",
		publicationOnboardingStateLastSyncedAtMs: Date.now()
	};
		
	googlesitekit.data.dispatch('modules/reader-revenue-manager').setSettings( settings );
	googlesitekit.data.dispatch('modules/reader-revenue-manager').saveSettings();
	```
- Go to the site's front-end and open the page source.
- Verify that you see the script as mentioned in the ACs, see the following screenshot for reference:
![image](https://github.com/user-attachments/assets/f435a72b-e54a-4f6d-9027-cccf05d86f44)
	- Verify that the script includes the publication ID set during connection with the script, and your site locale as described in the ACs.
- Go to _WordPress Dashboard -> Tools -> Site Health -> Status -> Passed tests_. Wait for "Tag Placement" accordion to appear from Site Kit. Verify that it includes "_Reader Revenue Manager: Tag detected and placed by Site Kit_".
- Go to _WordPress Dashboard -> Tools -> Site Health -> Info_. Open the "Site Kit by Google" accordion. Verify that you see the following items:
	- "Reader Revenue Manager publication ID" with a publication ID set during connection with the script.
	- "Reader Revenue Manager publication onboarding state" with a publication state set during connection with the script.
	- "Reader Revenue Manager publication onboarding state last synced at" with a time set during connection with the script.

## Changelog entry

* Include the Subscribe with Google external JavaScript file and configure it for the Reader Revenue Manager service.

**Comment by nfmohit** [comment]
Thank you for the excellent IB, @hussain-t ! Please take a look at my comments below:

> * Add the `register` method:
>   
>   * [ ]  Hook into the `googlesitekit_setup_gtag` action, and invoke a callback method, `setup_gtag`.
> * [ ]  Add the `setup_gtag` method:
>   
>   * [ ]  It should accept one parameter `$gtag`.
>   * [ ]  Hook into the `wp_enqueue_scripts` action to enqueue the external JavaScript file (`swg-basic.js`) from the URL `https://news.google.com/swg/js/v1/swg-basic.js`.
>   * [ ]  Output the dynamic inline script by hooking into the `wp_footer` action.
> * [ ]  Add the `set_publication_id` method:
>   
>   * [ ]  Accept one parameter `$publication_id` and set it as the publication ID property.

I believe we shouldn't use the `googlesitekit_setup_gtag` hook here, as the script here is not technically a gtag. We should instead follow the approach we had used for TwG, see [here](https://github.com/google/site-kit-wp/blob/1.89.0/includes/Modules/Thank_With_Google/Web_Tag.php). Please note that it contains a lot of additional pieces for customization which we can disregard here.

> * If the tag is not blocked (`is_tag_blocked`), include `Tag_Environment_Type_Guard` in the `use_guard` method. If the tag `can_register`, invoke the `register` method on it.

I believe we should also use the `Tag_Verify_Guard` guard here.

> * In the `register` method, hook into `template_redirect` action and invoke a new method `register_tag`.

This should only be done if the module is connected.

------------------------

Please let me know if you have any questions, thank you!

**Comment by hussain-t** [comment]
Thanks for the thoughtful review, @nfmohit. I've updated the IB with the necessary changes.

**Comment by nfmohit** [comment]
Thank you for updating the IB, @hussain-t ! Please take a look at the additional points below:

> **Implement the `Web_Tag` class:**
> * [ ]  Add a private property for the publication ID.
> * [ ]  Add a public method `set_publication_id`:
>   
>   * [ ]  This method should accept one parameter `$publication_id` and set it as the publication ID property.

> Implement the `register_tag` method:
> * [ ]  ...
> * [ ]  Instantiate the `Web_Tag` class and pass it the `publicationID` setting.

If we're passing the publication ID as a parameter to the `Web_Tag` class, i.e. `new Web_Tag( $settings['publicationID'] )`, we do not really need the private property for the publication ID, or the `set_publication_id` method. We can simply access the passed publication ID using the `tag_id` property, i.e. `$this->tag_id`.

> Add a public `register` method:
> * [ ]  Hook into the `wp_enqueue_scripts` action to enqueue the external JavaScript file (`swg-basic.js`) from the URL `https://news.google.com/swg/js/v1/swg-basic.js`.
> * [ ]  Hook into the `wp_footer` action to output the dynamic inline script.

Ideally, we should not use `wp_footer` to output the inline script. Rather, we should use the same `wp_enqueue_scripts` hook for both the external and inline scripts. In the hook callback, we should register the external script (i.e. `wp_register_script( 'google_swgjs' )`), add the inline script to the same handle of the external script (i.e. `wp_add_inline_script( 'google_swgjs' )`), and finally enqueue the external script (i.e. wp_enqueue_script( 'google_swgjs' )`). This is the same approach we had used for TwG, see [here](https://github.com/google/site-kit-wp/blob/1.89.0/includes/Modules/Thank_With_Google/Web_Tag.php?rgh-link-date=2024-07-09T21%3A43%3A19Z). It would also be nice to add a reference to the old approach in the IB.

Please let me know if you have any questions, thank you!

**Comment by nfmohit** [comment]
Thank you for making the updates, @hussain-t ! I have made some minor amendments based on my last comment that you can see in the edit history. Feel free to let me know if you have any questions, thanks!

IB LGTM 👍 ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Mostly, this is good. 
I only want to flag that there are differences between the script at the up-to-date link in the AC (https://publishercenter.google.com/reader-revenue-manager/cms-sync?publication=CAow6J6vDA) and the Snippet on the FE. 
I've put both side by side for comparison and flagged the differences. 
Can we confirm if we need to do any fixes on those differences? ⚠️ 
<Details>
<img width="1291" alt="Screenshot 2024-07-22 at 15 36 13" src="https://github.com/user-attachments/assets/3fe926b4-5c62-4e4d-9620-e6ae490e911b">

</Details>

The following were tested good however : ✅ 
- Verified that the script as mentioned in the ACs is available from the page source of the FE, including the publication ID
   <Details>
   <img width="1299" alt="Screenshot 2024-07-22 at 15 15 18" src="https://github.com/user-attachments/assets/d38a0b98-11a6-4450-8ee1-4b31d6db0633">
   
   Full script:
   ```
   <!-- Google Reader Revenue Manager snippet added by Site Kit -->
   <script src="https://news.google.com/swg/js/v1/swg-basic.js" id="google_swgjs-js"></script>
   <script id="google_swgjs-js-after">
   (self.SWG_BASIC=self.SWG_BASIC||[]).push(basicSubscriptions=>. 
   {basicSubscriptions.init({"type":"NewsArticle","isPartOfType": 
   ["Product"],"isPartOfProductId":"CAow6J6vDA:openaccess","clientOptions":{"theme":"light","lang":"en-US"}});});
   </script>

   <!-- End Google Reader Revenue Manager snippet added by Site Kit -->
   ```
   </Details>

- Under WordPress Dashboard -> Tools -> Site Health -> Status -> Passed tests, it was verified that under "Tag Placement" accordion, it includes "Reader Revenue Manager: Tag detected and placed by Site Kit".
   <Details>
   <img width="987" alt="Screenshot 2024-07-22 at 15 19 54" src="https://github.com/user-attachments/assets/3d0a5ac1-cb95-4158-b790-c0b9e5539658">

   </Details>

- Under WordPress Dashboard -> Tools -> Site Health -> Info, under the "Site Kit by Google" accordion, the 3 items as per the QAB are appearing accordingly.

   <Details>
   <img width="941" alt="Screenshot 2024-07-22 at 15 24 19" src="https://github.com/user-attachments/assets/d047f547-abfe-485b-84b1-0958905fdb87">

   </Details>

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @techanvil 
This is good to go.

The following were tested good: ✅ 
- Verified that the script as mentioned in the ACs is available from the page source of the FE, including the publication ID
   <Details>
   <img width="1299" alt="Screenshot 2024-07-22 at 15 15 18" src="https://github.com/user-attachments/assets/d38a0b98-11a6-4450-8ee1-4b31d6db0633">
   
   Full script:
   ```
   <!-- Google Reader Revenue Manager snippet added by Site Kit -->
   <script src="https://news.google.com/swg/js/v1/swg-basic.js" id="google_swgjs-js"></script>
   <script id="google_swgjs-js-after">
   (self.SWG_BASIC=self.SWG_BASIC||[]).push(basicSubscriptions=>. 
   {basicSubscriptions.init({"type":"NewsArticle","isPartOfType": 
   ["Product"],"isPartOfProductId":"CAow6J6vDA:openaccess","clientOptions":{"theme":"light","lang":"en-US"}});});
   </script>

   <!-- End Google Reader Revenue Manager snippet added by Site Kit -->
   ```
   </Details>

- Under WordPress Dashboard -> Tools -> Site Health -> Status -> Passed tests, it was verified that under "Tag Placement" accordion, it includes "Reader Revenue Manager: Tag detected and placed by Site Kit".
   <Details>
   <img width="987" alt="Screenshot 2024-07-22 at 15 19 54" src="https://github.com/user-attachments/assets/3d0a5ac1-cb95-4158-b790-c0b9e5539658">

   </Details>

- Under WordPress Dashboard -> Tools -> Site Health -> Info, under the "Site Kit by Google" accordion, the 3 items as per the QAB are appearing accordingly.

   <Details>
   <img width="941" alt="Screenshot 2024-07-22 at 15 24 19" src="https://github.com/user-attachments/assets/d047f547-abfe-485b-84b1-0958905fdb87">

   </Details>

Moving ticket to Approval.
