### ISSUE TITLE
Implement RRM `getServiceURL()` selector

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8848]
## Feature Description

The `getServiceURL()` selector should be implemented for the Reader Revenue Manager module that should return a prepared link to the Reader Revenue Manager platform that meets [this criteria](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.vpojnvcj98k).

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.u0bvihe1zrkk).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `getServiceURL()` selector should be added to the Reader Revenue Manager module data store.
* This selector should return a link to the Reader Revenue Manager platform based on the following structure:
	* Link to the Reader Revenue Manager platform, i.e. publisher center should look like: `https://publishercenter.google.com/`.
	* Link to a specific publication in the Reader Revenue Manager platform should look like: `https://publishercenter.google.com/reader-revenue-manager?publication=PUBLICATION_ID`.
	* All links to the Reader Revenue Manager platform should be wrapped with the Google account chooser URL.
	* All links should include a query parameter to indicate Site Kit as a source, i.e. `utm_source=sitekit`.

## Implementation Brief

* [x] Create a new store definition in `assets/js/modules/reader-revenue-manager/datastore/service.js`.
* [x] The store definition only needs to provide the `selectors` object, which in turn contains the `getServiceURL()` selector.
* [x] `getServiceURL()` should accept an optional `publicationId` parameter and implement the logic as defined in the AC to determine the link.
* [x] Use `getAccountChooserURL()` to wrap the link with the Google account chooser URL.
* [x] See the [Analytics `getServiceURL()` implementation](https://github.com/google/site-kit-wp/blob/cefbb45445ad99a548d7ab555d2665d588b911eb/assets/js/modules/analytics-4/datastore/service.js#L56-L79) for some pointers.
* [x] Merge the store with the main RRM datastore introduced via #8786.

### Test Coverage

* Add JS test coverage for the new selector.

## QA Brief

1. Activate the Reader Revenue Manager module.
2. Run following command in browser console.

```js
    googlesitekit.data.select('modules/reader-revenue-manager').getServiceURL( { publicationID: 'ABCDEFGH' } );
```
You must get the URL like following

```
https://accounts.google.com/accountchooser?continue=https://publishercenter.google.com/reader-revenue-manager?publication=ABCDEFGH&utm_source=sitekit&Email=your-email@get10up.com
```

Notice that email will be replaced with your account email.

3. Clicking on the above link should take you to the publisher center, but page will open in publisher center only if the publication ID is valid (in this case `ABCDEFGH` which is invalid). You can create a publication in https://publishercenter.google.com/ to get the publication ID.

4. Again, in the browser console, run the following script:

```js
googlesitekit.data.select( 'modules/reader-revenue-manager' ).getServiceURL()
```

5. The link that will receive should take you to the publisher center homepage, i.e. https://publishercenter.google.com/

## Changelog entry

* Add Reader Revenue Manager data store functionality to get service URL.

**Comment by nfmohit** [comment]
> * Create a new store definition in `assets/js/modules/analytics-4/datastore/service.js`.

Hi @techanvil, just to confirm, shouldn't this be `assets/js/modules/reader-revenue-manager/datastore/service.js` instead?

**Comment by nfmohit** [comment]
Brilliant, thanks @techanvil! IB ✅

**Comment by ankitrox** [comment]
I've created the PR: https://github.com/google/site-kit-wp/pull/8953 for this issue, but keeping this issue in Execution because its dependencies #8786 is yet to be merged. 

Once merged, the base branch for this PR needs to be changed to `develop` and test everything and move this to CR.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

I did some tests and results and queries are as follows:

- Executed with the following scenarios:
   - Invalid publication ID - Link will go the the publisher page but would not open. It's expected ✅ 
   - Valid publication ID - Link will go to the correct Publisher publication page. ✅ 
   - Only getserviceURL() - While the link goes to the Publisher central page initially, it goes directly to the publication afterwards.  ⚠️ 
      Refer to the attached video :
      https://github.com/user-attachments/assets/0c9a4552-0b3b-4216-aa49-1eddf24219e1
- It's worth noting that the URLs have a lot of symbols with %, etc.. 
   In the AC, there is no mention of those symbols and add ons. The link works but are we expecting these?  ⚠️ 
   
   e.g. https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%3Futm_source%3Dsitekit%26publication%3DCAownMayDA&Email=kelvin.balloo%40get10up.com
   
  It's not @get10up.com but %40get10up.com

**Comment by ankitrox** [comment]
Hi @kelvinballoo ,

Thank you for testing this issue.

> Only getserviceURL() - While the link goes to the Publisher central page initially, it goes directly to the publication afterwards. ⚠️
Refer to the attached video :

the publication ID query parameter is added by publisher centre automatically and we do not have the control over it. As you demonstrated in your video, even if we simply visit https://publishercenter.google.com/, that query parameter is getting appended in the URL.

> It's worth noting that the URLs have a lot of symbols with %, etc..
In the AC, there is no mention of those symbols and add ons. The link works but are we expecting these? ⚠️

This is fine as the `getServiceURL` selector will encode the URL so that all the parameters and values can be passed safely.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks for the update @ankitrox 

- Executed with the following scenarios:
   - Invalid publication ID - Link will go the the publisher page but would not open. It's expected ✅ 
   - Valid publication ID - Link will go to the correct Publisher publication page. ✅ 
   - Only getserviceURL() - Link goes to the Publisher central page initially and goes directly to the publication afterwards but this is fine as that's the way the RRM works.  ✅ 
      Video for reference:
      https://github.com/user-attachments/assets/0c9a4552-0b3b-4216-aa49-1eddf24219e1

   - Link to the RRM platform includes the following: ✅ 
      - https://publishercenter.google.com/.
      - Publication portion: https://publishercenter.google.com/reader-revenue-manager?publication=PUBLICATION_ID.
      - Links wrapped with the Google account chooser URL.
      - Query  parameter includes Site Kit as a source,utm_source=sitekit. 
      - URL tested: https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%3Futm_source%3Dsitekit%26publication%3DCAownMayDA&Email=kelvin.balloo%40get10up.com
      
      Symbols with the URL encoding is fine as clarified.

Moving this ticket to approval.
      
   
<Details>
<img width="1092" alt="Screenshot 2024-07-15 at 19 58 55" src="https://github.com/user-attachments/assets/07eee733-be99-4499-9b3e-056a5b459dda">

</Details>
