### ISSUE TITLE
Update PAX integrator

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8852]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The PAX integrator script + types should be updated to `1.0.9`

## Implementation Brief

* [x] Update the src of the `googlesitekit-ads-pax-integrator` Script within `Ads::setup_assets`
* [x] Update the `google-pax-sdk` version in package.json to match, and update

### Test Coverage

* No changes expected

## QA Brief

* On a site with PAX already set up, the PAX integration should continue to work without issue. No specific QA is needed.

## Changelog entry

* Update PAX integration library to latest version.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified on a site with PAX already set up, the PAX integration continue to work without issue. 
- Setup Ads module in PAX manner on latest environment.
- Successfully completed PAX setup.
- Switched to dev environment.
- Verified Ads module not disconnected.
- Disconnected ads module.
- Reconnected Ads module.
- Verified PAX setup shows completed and ads module reconnected successfully with already created conversion ID.

<details>



https://github.com/google/site-kit-wp/assets/94359491/05b9f795-9e9e-4795-a35c-590fefcc8f2e

</details.
