### ISSUE TITLE
Blank audience tile title when changing GA property

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#8860]
## Bug Description

The audience tile title will turn blank after changing a GA property

## Steps to reproduce
- I set up an audience tile
- I go to analytics and connect another property
- I go back to my audience tile on the dashboard and the tile is still showing with the title being blank

## Screenshots

<img width="998" alt="Screenshot 2024-06-11 at 19 13 42" src="https://github.com/google/site-kit-wp/assets/125576926/79a99b2b-77b2-480e-930b-5a6c7b4e1689">

## Additional Context

 - PHP Version: 8.0
 - Browser: Chrome
 - Plugin Version: 1.129.0
 - Device: MacOS Sonoma on MacbookPro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Closing this issue, as it will be handled via https://github.com/google/site-kit-wp/issues/8180.
