### ISSUE TITLE
Distance between New badge and text should be 14px instead of 6px.

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#8861]
## Bug Description

Distance between New badge and text should be 14px instead of 6px.

## Steps to reproduce

1. Turn on audience segmentation featured flag
2. Review the 'New' badge at the 'CTA Groups' CTA.

## Screenshots

Details
Implementation: 6px
<img width="1003" alt="Screenshot 2024-06-11 at 22 05 59" src="https://github.com/google/site-kit-wp/assets/125576926/85f59fda-18bb-41e4-a9b3-726ea34d2c2c">

Figma: 14px
<img width="598" alt="Screenshot 2024-06-11 at 22 05 10" src="https://github.com/google/site-kit-wp/assets/125576926/99ba7492-0512-4739-8e06-b9e01b654c02">

## Additional Context

 - PHP Version: 8.0
 - Browser: Chrome
 - Plugin Version: 1.129.0
 - Device: MacOS Sonoma on MacbookPro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a 14px gap between the title of a widget area and its "New" badge.
* In concrete terms, this should apply to the Audiences Widget Area as the first widget area with a "New" badge, as well as any subsequently added widget areas with a badge

## Implementation Brief

* [x] Update `assets/sass/widgets/_widget-area.scss`, add a new block targeting `.googlesitekit-widget-area-header .googlesitekit-new-badge`, set the `margin-left` to `14px`.

### Test Coverage

* Update any failing VRTs.

## QA Brief

* 

## Changelog entry

* Improve margins between "New" badge and text.

**Comment by nfmohit** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified the gap between the title of a widget area and its "New" badge is 14px.

![image](https://github.com/google/site-kit-wp/assets/94359491/2f0029b1-a295-4486-af90-9e376091bc83)
