### ISSUE TITLE
Scroll to the Audiences Widget Area from the Setup Success Notice

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8874]
## Feature Description

Clicking on the Setup Success Notice's "Show me" CTA should scroll to the Audiences Widget Area.

![image](https://github.com/google/site-kit-wp/assets/18395600/7c450342-d52e-47d4-88e3-233f184b8b0f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Upon clicking the "Show me" CTA on the Setup Success Notice, the page should scroll to the Audiences Widget Area, and the notice should be dismissed for the current user.

## Implementation Brief

_Note: see the IB for #8172, we may be able to refactor/reuse the corresponding code._

* [ ] Update the `scrollToWidgetArea` function in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupSuccessSubtleNotification.js`:
https://github.com/google/site-kit-wp/blob/e12d144418423b637879d8dd0f0d181acaa89b1b/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupSuccessSubtleNotification.js#L65-L70
   * [ ] Use `getContextScrollTop` to get the y offset for the class `.googlesitekit-widget-area--mainDashboardTrafficAudienceSegmentation`.
   * [ ] Use `global.scrollTo` with `top` set to the value of `getContextScrollTop` and the `behaviour` set to `smooth`.
   * [ ] Account for any layout shift due to the notification being dismissed with `dismissNotificationForUser` in this function.

### Test Coverage

* No additional test coverage required.

## QA Brief

* Turn on the `audienceSegmentation` feature flag from the tester plugin.
* Set up Site Kit with the Analytics module.
* In the Site Kit dashboard, click on "_Enable groups_" CTA in the Audience Segmentation setup CTA widget.
* Upon success, click on the "_Show me_" CTA in the setup success notification.
* Verify that you are scrolled to the audience widget area, and that the setup success notification is dismissed.

## Changelog entry

* Scroll to the Audiences Widget Area when clicking the "Show me" CTA on the Setup Success Notice that is shown when the Audience Segmentation feature has been set up.

**Comment by benbowler** [comment]
I created an IB, should we consider dismissing the notification after the user clicks "Show Me"?

**Comment by techanvil** [comment]
Thanks @benbowler, yes, the intention is to dismiss the notification as well (i.e. maintain the current behaviour). I've updated the AC to make it clearer.

IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Upon clicking the "Show me" CTA on the Setup Success Notice, the page scrolls to the Audiences Widget Area, and the notice is dismissed for the current user.

Moving ticket to Approval.

<Details>
Desktop test:

https://github.com/user-attachments/assets/75fc988e-8ca0-4fdd-b33c-3c1c6607d19e


Mobile test:

https://github.com/user-attachments/assets/bac64cff-cf22-4742-b9d2-6fbaca06204e


</Details>
