### ISSUE TITLE
Clear the "temporarily hidden" state for an audience when it's removed from the audience selection

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8877]
## Feature Description

If an audience has zero data and has been temporarily hidden, and the audience is subsequently removed from the audience selection, the "temporarily hidden" state should be cleared.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Given an audience has zero data and has been temporarily hidden:
  * When the audience is removed from the audience selection via the Selection Panel and the selection is saved via clicking on the **Save selection** CTA, the "temporarily hidden" state of the audience should be cleared.
  * This in turn means next time the audience is added to the selection its tile will be shown as usual.

## Implementation Brief

**Updates to Dismissed Item Infra**
* [ ] Update `includes/Core/Dismissals/REST_Dismissals_Controller.php`, create a new rest endpoint:
   * [ ] The endpoint should be `'core/user/data/dismissed-items'`
   * [ ] The method should be `WP_REST_Server::DELETABLE`
   * [ ] In the callback function, use the existing `remove` method on `Dismissed_Items` to remove the dismissed items by slug. [Use slug parameter validation and return the updated dismissed items (use the existing create route for reference)](https://github.com/google/site-kit-wp/blob/e89e704e1268b4ad559c0c3fbc0e8a592cdcba9c/includes/Core/Dismissals/REST_Dismissals_Controller.php#L103-L121).
 * [ ] Update `assets/js/googlesitekit/datastore/user/dismissed-items.js`:
   * [ ] Create a new action called `removeDismissedItems`, which takes an array of slugs and resolves using a new fetch store, which uses `API.set` using the `DELETE` method, within it's `controllerCallback` to delete the requested dismissed items.
   https://github.com/google/site-kit-wp/blob/b67e9a1ea124dc8d233def811d9adfb99c995544/assets/js/googlesitekit/modules/datastore/sharing-settings.js#L90-L98

**Audience Selection Updates**
 - [ ] Update `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Footer.js`, within the [`saveSettings` callback](https://github.com/google/site-kit-wp/blob/e89e704e1268b4ad559c0c3fbc0e8a592cdcba9c/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Footer.js#L95-L104)
    - If there in **not** an error:
    - [ ] Get all dismissed items with `getDismissedItems` selector.
    - [ ] Use `.filter` to find any dismissed items where the slug starts with `audience-tile-`
    - [ ] For each of these (if any are found), collect the slugs in an array, and dispatch the new `removeDismissedItems` action.

### Test Coverage

* Add new test coverage for the new remove functionality in both `tests/phpunit/integration/Core/Dismissals/REST_Dismissals_ControllerTest.php` and `assets/js/googlesitekit/datastore/user/dismissed-items.test.js`

### Happy path

1. Setup the Audience Segmentation feature with at least two audiences selected, one or more of which should be in the "partial data" state with zero data, thus showing the zero data tile variant with the **Temporarily hide** CTA. Refer to the QAB for https://github.com/google/site-kit-wp/issues/8143 for more details on this setup.
2. Click on **Temporarily hide** to hide the audiences.
3. Open the Selection Panel, and remove one or more of the hidden audiences from the selection.
4. Save the selection, then re-add the audiences to the selection and save it again.
5. The previously hidden audiences which were removed and re-added should reappear in the list of Audience Tiles.

### Unhappy path

- Follow steps 1-3 above.
- Using the [Tweak](https://chromewebstore.google.com/detail/tweak-mock-and-modify-htt/feahianecghpnipmhphmfgmpdodhcapi?hl=en) Chrome extension, create a rule as follows (feel free to test with different error types):  
  - URL: `.*/wp-json/google-site-kit/v1/core/user/data/dismissed-items.*`
  - Enable the use of regular expressions `(.*)`
  - HTTP Method: `POST`
  - Status code: `500`
  - Response payload:
    ```json
    {
      "code": "internal_server_error",
      "message": "Internal server error",
      "data": {
        "status": 500
      }
    }
    ```
- Save the selection. The error message should appear in the footer of the Selection Panel:
![image](https://github.com/user-attachments/assets/dd269032-698d-43b5-82f2-d7097762cff5)
- Disable the Tweak rule and re-save the selection. The error message should disappear.

## Changelog entry

* Ensure the “temporarily hidden” state of an audience with zero data is cleared when the audience is removed from the selection.

**Comment by techanvil** [comment]
Hi @benbowler, thanks for drafting this IB. A couple of points:

>    * [ ] Create a new action called `removeDismissedItem`, which takes a slug and resolves using a new fetch store, which uses `API.delete` within it's `controllerCallback` to delete the requested dismissed item key.

We don't actually have an `API.delete()` function at present. We could add one, but the only current use of the HTTP `DELETE` method is implemented using `API.set()` as follows:

https://github.com/google/site-kit-wp/blob/b67e9a1ea124dc8d233def811d9adfb99c995544/assets/js/googlesitekit/modules/datastore/sharing-settings.js#L90-L98

>    - [ ] For each of these (if any are found), dispatch the new `removeDismissedItem` action.

This point makes me think that, seeing as we're adding a new REST endpoint for the deletion, we might as well allow that endpoint to handle multiple items so we can batch these into a single request. WDYT?

**Comment by benbowler** [comment]
Thanks @techanvil, I've updated this to use `API.set` and to accept and array of slugs and delete them all to reduce the number of REST requests.

**Comment by techanvil** [comment]
Thanks @benbowler! IB LGTM. I've bumped the estimate up a level to allow for extra time modelling the scenarios in testing, and because we've generally been underestimating Audience Segmentation issues.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

The tests on desktop are fine. I did one round of testing on mobile and there are 2 issues to flag:

**ITEM 1:**  
After I hide the temporarily hide for one tile, all the tiles vanish or rather are collapsed I would say.
When I click on the group that is there, it will appear.
Question would then be, once I hide one of the tiles, should we auto-reselect the existing audience rather than having to click on it? ⚠️

<Details>
Refer around 5th second.

https://github.com/user-attachments/assets/174fcedf-838d-4bfe-8650-267d4c97586d

</Details>


**ITEM 2:**

I had 3 tiles setup and somehow hit an error on mobile when I clicked on one of the tabs. ❌ 

<Details>
Refer around the 17th second thereon:

https://github.com/user-attachments/assets/4c9f0bf2-7cd8-4216-bf78-dc20ce0ccf6e


</Details>

______________________________________________________

Other than that, I the happy and unhappy scenarios on desktop and it's working as expected. ✅ 

**Happy path:**
The previously hidden audiences which were removed and re-added reappeared in the list of Audience Tiles.
<Details>

https://github.com/user-attachments/assets/1e1aa34f-57b4-4df5-b5ce-e3e8e736d29a


</Details>

**Unhappy path:**
The error will be showing up when the tweak extension is activated and once disabled, it works as expected too.

<Details>
<img width="738" alt="Screenshot 2024-08-07 at 14 28 39" src="https://github.com/user-attachments/assets/34ce49f2-b6a0-4dc5-9e20-cd10c1423384">
</Details>

**Comment by techanvil** [comment]
Hey @kelvinballoo! Thanks for flagging these defects. They are both valid concerns, but are outside the scope of this issue. Please can you raise issues for them?

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks for checking @techanvil .
New issue raised under :  https://github.com/google/site-kit-wp/issues/9168

As for this issue, it's good to go to Approval.
I tested the happy and unhappy scenarios on desktop and it's working as expected. 

**Happy path:**
The previously hidden audiences which were removed and re-added reappeared in the list of Audience Tiles. ✅  
<Details>

https://github.com/user-attachments/assets/1e1aa34f-57b4-4df5-b5ce-e3e8e736d29a


</Details>

**Unhappy path:**
The error will be showing up when the tweak extension is activated and once disabled, it works as expected too. ✅ 

<Details>
<img width="738" alt="Screenshot 2024-08-07 at 14 28 39" src="https://github.com/user-attachments/assets/34ce49f2-b6a0-4dc5-9e20-cd10c1423384">
</Details>
