### ISSUE TITLE
Inconsistent Admin Bar module styling between themes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#888]
## Bug Description

The content displayed in Site Kit's admin bar varies in appearance when different themes are activated:

### Twenty Nineteen
![image](https://user-images.githubusercontent.com/1621608/69320983-e9550d80-0c4a-11ea-90c9-90175f3453df.png)

### Twenty Twenty
![image](https://user-images.githubusercontent.com/1621608/69321003-efe38500-0c4a-11ea-83e5-01198968dda3.png)

This appears to be due to different relative font-size values applied to the `<html>` element by each theme. This value should be fixed on the admin bar app's element so that it doesn't inherit this relative sizing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Ensure that font sizing in the Site Kit admin bar menu content with the stats is consistent regardless of the theme currently used.

## Implementation Brief

The problem is that the styles use `rem` units which are specifically relative to the value defined on the `<html>` element which often varies from theme to theme.

[![image](https://user-images.githubusercontent.com/1621608/69408824-60a0a500-0d10-11ea-9d2c-205a11db4b8c.png)](https://developer.mozilla.org/en-US/docs/Web/CSS/length#rem)

These are generally the right unit to use, but in our case we need our components to remain consistent between wp-admin and the admin bar displayed on the front end.

* Update units used for font-sizing to use `px` units instead of `rem`
* Adjust values if needed for consistency between wp-admin and front end rendering

## Changelog entry

*

**Comment by felixarntz** [comment]
Noticed this just earlier as well too. Let's fix it for next release.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz after digging into this a bit, I'm realizing that using `em` as mentioned in the IB is going to work as well as I thought. Apparently `em` units are only relative to the parent element's font-size, it isn't inherited from ancestors like other rules ([source](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#ems_and_rems)).

After reaching out to a few of my colleagues, it seems that it's best to use absolute units instead, such as `px`. There are a few cases it seems where this should have been used anyways, such as other elements in the component (such as an arrow) where the size is fixed using `px` dimensions as well. For other cases where a component's style is shared with other areas and should remain more responsive (such as a datapoint), these can use fixed overrides for the admin bar specifically (`assets/sass/components/adminbar/_googlesitekit-adminbar-overrides.scss`).

Let me know if this is okay and I'll update the IB before continuing. Moving to blocked for now.

**Comment by felixarntz** [comment]
@aaemnnosttv Using `px` sounds reasonable here. 👍

**Comment by cole10up** [comment]
**Tested**

Checked Swedish Museum:
![image](https://user-images.githubusercontent.com/57115907/71014403-bfa2d100-20a6-11ea-91ab-3fda2b893573.png)

Twenty Seventeen:
![image](https://user-images.githubusercontent.com/57115907/71014533-eeb94280-20a6-11ea-8a07-0adf0956cfb4.png)

Twenty Nineteen
![image](https://user-images.githubusercontent.com/57115907/71014587-0395d600-20a7-11ea-8263-708cde349e69.png)

Twenty Sixteen
![image](https://user-images.githubusercontent.com/57115907/71014646-1d371d80-20a7-11ea-81eb-1b2efaad3d05.png)

Astra:
![image](https://user-images.githubusercontent.com/57115907/71014720-3d66dc80-20a7-11ea-99e1-d368efc928d7.png)

Hello:
![image](https://user-images.githubusercontent.com/57115907/71014760-5079ac80-20a7-11ea-8c93-6fe01b2f65ad.png)

OceanWP:
![image](https://user-images.githubusercontent.com/57115907/71014810-625b4f80-20a7-11ea-9ea1-4b0604489e76.png)

Looks good!

Passed QA ✅

**Comment by marrrmarrr** [comment]
👁👍
