### ISSUE TITLE
PageSpeed Insights shows different data within the Sitekit dashboard

### ISSUE THREAD

**Issue by mAnN14** [google/site-kit-wp#889]
## Bug Description

My PageSpeed Insights metrics for both desktop & mobile platforms differ from what I see on the official PageSpeed Insights site.  

## Steps to reproduce

1. I logged into my WordPress site. URL: 'https://whereispillmythoughts.com/'
2. Click on Sitekit >> Dashboard
3. Scroll down to 'PageSpeed Insights report'
4. The data (for desktop + mobile) shown is different from what I see on the following official PageSpeed Insights URL:  https://developers.google.com/speed/pagespeed/insights/

![Site Kit Plugin - PageSpeed Error](https://user-images.githubusercontent.com/10899599/69325013-7d38d080-0c6f-11ea-9a12-be5aa862f2d0.PNG)
![Site Kit Plugin - PageSpeed Error  Desktop Platform](https://user-images.githubusercontent.com/10899599/69325235-d86ac300-0c6f-11ea-8f89-45f14f09ec97.PNG)
![Site Kit Plugin - PageSpeed Error  Mobile platform](https://user-images.githubusercontent.com/10899599/69325237-d86ac300-0c6f-11ea-8e9c-297c0b148946.PNG)

## Additional Context

 - PHP Version: 7.1.33
 - OS: [e.g. iOS] - Windows 10 [Home] 
 - Browser [e.g. chrome, safari] - Firefox and Chrome
 - Plugin Version [e.g. 22]: v1.0.4
 - Device: [e.g. iPhone6]: Dell Inspiron 15 [7000 series]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is likely due to normal variations in performance between responses. When testing on my site I found a difference of 1 point/percent compared with the same test on the web interface.

PageSpeed Insights doesn't require me to have any access to your property to run this so I was able to test this using your URL. Initially I saw more of a difference (~5-7) pts between what is shown in Site Kit and what is on the web interface. A few minutes later I tested again and saw almost identical numbers. 

Can you try this again and see if you can confirm?

**Comment by aaemnnosttv** [comment]
That's a good observation and something worth a bit more testing to rule out anything on our end.

I would expect the two to be very close if tested within a close time frame. Both Site Kit and the PageSpeed Insights web tool use the same API behind the scenes which uses [Lighthouse](https://developers.google.com/web/tools/lighthouse/) to perform the actual audit.

Thanks for bringing this to our attention!

**Comment by mAnN14** [comment]
@aaemnnosttv - Glad my insights could help you understand the issue in a better way.

**Comment by jamesozzie** [comment]
Closing as the PageSpeed Insights module has since been modified with a different set of insights, not including performance score within the plugin.
