### ISSUE TITLE
Update the design of the Key Metrics setup CTA banner.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8895]
## Feature Description

The current Key Metrics setup CTA banner looks like this:

![Screenshot 2024-07-25 at 19 20 32](https://github.com/user-attachments/assets/65f8c7ef-05a9-48ce-824e-276e384b682f)

But the dismiss CTA is in the bottom of the banner, which isn’t consistent with our new banners.

We have a new [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1773-21199&node-type=frame&t=RmQbGiQX6NXDmOVT-0) for the Key Metrics setup CTA banner:

<img width="806" alt="image" src="https://github.com/user-attachments/assets/7f2fdf9e-4ed1-4681-acb8-f2ced55d0adc">

This design should be applied to the banner in the plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The https://github.com/google/site-kit-wp/blob/dc89f6c19d3d1103e5be3387c2739fe2955324bc/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js#L57 should be updated to match the new design in the Figma mockups for [mobile](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2221-24522&node-type=frame&t=wnKLwplBBLZt95bD-0), [tablet](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2221-24102&node-type=frame&t=wnKLwplBBLZt95bD-0), 960 specific screen [design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2575-26221&node-type=frame&t=wnKLwplBBLZt95bD-0) and [desktop](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1773-21199&node-type=frame&t=RmQbGiQX6NXDmOVT-0) views.
* Note that the "I'll pick metrics myself" secondary CTA should be moved to the footer of the new CTA, and renamed to the "Choose your own metrics", and the "Maybe later" in the current CTA should be moved to the secondary CTA next to "Get tailored metrics".

## Implementation Brief

* [x] Edit `assets/js/components/KeyMetrics/KeyMetricsCTAContent.js` and `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`
  * Adapt the markup for new design - swapping the CTA's, adding new text in the footer, replacing the SVG image with the one in figma, etc. 
  * Note that mobile version has different SVG, which should be rendered conditionally based on the breakpoint , instead of the main one
  * New footer layout might need some tweaks in layout
* [x] Update `assets/sass/components/key-metrics/_googlesitekit-key-metrics-setup-cta.scss`
  * Adjust the styling to match new design - areas like font size, new footer section, position of the graphic, etc

### Test Coverage

* Update VRT's

## QA Brief

* Setup Site Kit with Analytics module
* Verify that setup key metrics widget is showing as per new figma designs across the screens
* Select 2 key metrics, then disconnect Analytics module
* Verify that small connect GA4 CTA is showing correctly (there is no new design for this, it should look correctly across the screens)
* Setup Analytics module and select 4 GA4 key metrics
* Disconnect the module
* Verify that big `Analytics disconnected` CTA is showing correctly across the screens - it follows same layout as default setup CTA just with different content, and footer CTA should be `maybe later` instead of `select your own metrics`

## Changelog entry

* Update the design of the Key Metrics setup CTA banner.

**Comment by tofumatt** [comment]
As [mentioned in Slack](https://fueled10up.slack.com/archives/C01CA828ZPZ/p1721749417857439), this needs mobile designs/guidance before we can move it to IB, so leaving it in AC for now.

**Comment by tofumatt** [comment]
Mobile designs are ready so moved this to IB 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
Parking it in the meantime until it gets a sprint number, since I picked it up by mistake

**Comment by zutigrm** [comment]
Hi @sigal-teller , since this banner has a bit longer content, and we aim to cover desktop layout for screens starting at 960px and over, currently it's existing desktop sizes are too crowded, causing the  banner to grow in height, and hence the Graphic to look out of place as it doesn't fit correctly in that crowded space. At the moment it is showing tablet layout on these screens. Would it be possible to add new screen with adjusted desktop layout for 960px screen width? 

Current desktop layout works fine for screens starting at 1280px and over so that style will remain for these screens, new adjustment would be only for specific screen sizes between 960px to bellow 1280px.

**Comment by sigal-teller** [comment]
Hi @zutigrm I assume you meant a total screen width of 960px, which means that when deducting the WP bar, there is a net width of 800px for the dashboard. It is possible to have a version of the desktop design like [here](https://www.figma.com/design/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=8593-13666&t=sE0vlyvTiOZ51AMq-1).
In this width it looks better then the tablet design.
By the way, why aren't we implementing the banner design that I created for ACR already? It is very similar only includes a slightly different illustration and additional explanatory text, which can actually fit for KMW as well. This new design for KMW was created before, but it was a long time ago, so Im wondering if we're implementing it now why not use the ACR banner which will replace it?

**Comment by zutigrm** [comment]
@sigal-teller Yes perfect, that's nice solution. 

> By the way, why aren't we implementing the banner design that I created for ACR already? It is very similar only includes a slightly different illustration and additional explanatory text

That's a good point, thanks. Since the text is not mentioning directly the ACR - because this banner will be shown to all users, not hidden behind feature flag, I will adjust the current implementation to include new graphic and text from the ACR figma file.

**Comment by sigal-teller** [comment]
@zutigrm ok great, so I'll create the design for this this width in the ACR Figma file as well

**Comment by zutigrm** [comment]
@sigal-teller awesome, thank you!

**Comment by sigal-teller** [comment]
@zutigrm Done.

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified updated design of Key metrics Setup CTA and compared it with figma.
- Verified Key metrics Setup CTA widget design across different viewports.
- Verified Analytics disconnected design across different viewports.

@zutigrm 

**Issues -**

1. Additional space showing below CTA  under viewports from 601px  to 959px.
2. Both KMW CTA and Analytics CTA are not showing correctly under tablets and mobile viewports.
3. CTA's are not loading correctly. 

**_Loading issue -_**

<details>

https://github.com/user-attachments/assets/d21c2285-f8e2-4bb2-902d-e7c4f094b77e

https://github.com/user-attachments/assets/1ad52373-10be-4d21-ae19-f8609ff636fc

</details>

**_Design issues_**

<details>

![Image](https://github.com/user-attachments/assets/21dbfee2-ede8-4296-b18b-22ca665280bc)


![Image](https://github.com/user-attachments/assets/e8a4d2a7-c0ef-4efe-9239-c5a1ea45055b)


![Image](https://github.com/user-attachments/assets/75ba7d43-af3d-4407-ab45-37459af12bc0)


![Image](https://github.com/user-attachments/assets/bf91f186-704e-4e2d-b892-080821e626c6)


![Image](https://github.com/user-attachments/assets/b5cc8dd2-0b0f-4ffb-8203-368991e88aab)


![Image](https://github.com/user-attachments/assets/5f2f0a3a-9bdf-4ffa-9e69-783f9197809e)


![Image](https://github.com/user-attachments/assets/66b48d14-500e-471a-a1bb-1866ea24b709)


</details>

**Comment by mohitwp** [comment]
### QA Update ❌ 

@zutigrmI tested this on BrowserStack and found that the CTA banner image appears misaligned on Mac and iOS devices. However, it looks good on Windows and Android devices. The issue exists only on macOS and iPads across all browsers.


<details>
**Mac and iOS devices**

![Image](https://github.com/user-attachments/assets/c9aaa397-8c1d-49d6-b7ee-587d1e576155)

![Image](https://github.com/user-attachments/assets/e9694424-6732-4207-934b-8f00c5c01d84)

![Image](https://github.com/user-attachments/assets/0b1dd6dd-24a1-4cee-9494-9111b5680fad)

![Image](https://github.com/user-attachments/assets/8ba49c8b-288e-4d39-b585-79067755a48b)

</details>

**Comment by zutigrm** [comment]
@mohitwp Thanks, graphic has been fixed for mac OS and iOS

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that  CTA banner image  misaligned issue on Mac and iOS devices is resolved now.
- Tested on Mac and iOS devices using BrowserStack.
- Verified updated design of Key metrics Setup CTA and compared it with figma.
- Verified Key metrics Setup CTA widget design across different viewports.
- Verified Analytics disconnected design across different viewports.

<details>

![Image](https://github.com/user-attachments/assets/374af761-cc11-4d6f-9717-cfeee383cf6c)

![Image](https://github.com/user-attachments/assets/22afa2ed-a846-4f77-9f50-b73f2918ca48)

![Image](https://github.com/user-attachments/assets/a37523d8-9830-4797-81a3-6246ee0c6da8)

![Image](https://github.com/user-attachments/assets/0ca3c878-3a3a-4450-a5fb-c547cc6f2687)

![Image](https://github.com/user-attachments/assets/53d9f5da-71e1-47ec-a441-9b03c7eefc95)

</details>

**_When 4 metrics  are selected and analytics gets disconnect_**

<details>

![Image](https://github.com/user-attachments/assets/ca9d57b5-a508-41c0-bfee-179cd47265ac)

![Image](https://github.com/user-attachments/assets/1a40aca2-014b-434a-898e-49627d16e4cd)

![Image](https://github.com/user-attachments/assets/9732c2ca-03ad-4ab3-bd39-a2091ab5f8c1)

![Image](https://github.com/user-attachments/assets/ebc33627-9f61-457f-acaa-f8180ec4ff4a)

</details>

**_When 2 metrics selected and analytics gets disconnect_**

<details>

![Image](https://github.com/user-attachments/assets/233c5640-450d-4613-8ab3-dc281624bfae)

![Image](https://github.com/user-attachments/assets/493f571d-57f6-4918-af04-eb3ff62ea938)

</details>
