### ISSUE TITLE
Use the correct title font for the Consent Mode Setup CTA Banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8898]
## Feature Description

The Consent Mode Setup CTA Banner has been implemented with a title font of Google Sans Text. However, as per the [Figma design](https://www.figma.com/design/mdQi9qajirgoMHKy4DiVa8/Consent-Mode?node-id=514-7198&t=6VbPO4aN6JBrLf0A-0), it should be Google Sans Display.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The title font for the Consent Mode Setup CTA Banner should be Google Sans Display.

## Implementation Brief

* [ ] Change the `font-family` value for the main `.googlesitekit-setup-cta-banner__title` class definition to `$f-secondary`.
https://github.com/google/site-kit-wp/blob/721401ea2fac18fad433bf2e066aaa486aa83e79/assets/sass/components/dashboard/_googlesitekit-setup-cta-banner.scss#L29-L30

* [ ] The override for the Ads banner can be removed:
https://github.com/google/site-kit-wp/blob/721401ea2fac18fad433bf2e066aaa486aa83e79/assets/sass/components/ads/_googlesitekit-ads-setup-banner.scss#L30-L31

### Test Coverage

* Update VRT reference images as needed.

## QA Brief

* Enable a VPN so your request is coming from an EU country (for instance, Germany)
* Set up Site Kit on a new site
* The Consent Mode title (_"Enable Consent Mode to preserve…"_) should be using Google Sans Display

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified title font for the Consent Mode Setup CTA Banner is now Google Sans Display.

![image](https://github.com/google/site-kit-wp/assets/94359491/19a65ada-bede-49af-b4e5-6ca64066180a)
