### ISSUE TITLE
PageSpeed insights widget does not show loading state when date range changes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#890]
## Bug Description

Currently the PSI widget components refetch data when the date range changes on the page (not sure if this should happen?). It does not go back into a loading state when this happens, inner widgets just disappear temporarily.

Expected (assuming this data is date-range specific and needs to be refetched)
![image](https://user-images.githubusercontent.com/1621608/69326411-6b95ff80-0c54-11ea-8ea0-3c3439401fc4.png)

Actual
![image](https://user-images.githubusercontent.com/1621608/69326419-6f298680-0c54-11ea-8eb6-3a60289badcb.png)

Note, this varies how long it stays in this state; sometimes it is fairly quick, others it takes about as long as the initial load.

## Steps to reproduce

1. Go to dashboard
1. Activate PageSpeed Insights
1. After initial loading completes, change the date range
1. See inner PSI widgets have disappeared with no loading state

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

PSI stats are not connected to a specific time-frame. 
If a user changes the date range for the rest of the dashboard:
* PSI module should remain as-is, no need to re-fetch the data. 

## Implementation Brief

* Specify a static `dateRange` for pagespeed requests  
This will prevent the date range changes from inheriting the `dateRange` from the page/dropdown
* Merge #1047

## Changelog entry

* Do not refetch PageSpeed Insights data when the date range selector is changed, as its data its date-agnostic.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**
Page speed insights is confirmed functional and agnostic regardless of date range and is able to be disconnected and reconnected without issue.

![Site Kit by Google Dashboard ‹ googlekitlocal 10uplabs com — WordPress (2)](https://user-images.githubusercontent.com/57115907/72875143-844c8100-3ca8-11ea-9c0b-2e9ae25be32e.gif)

Passed QA ✅
