### ISSUE TITLE
E2E failing on WP Nightly (6.6)

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8901]
## Bug Description

E2E tests are currently failing consistently for WP nightly due to an unexpected console error with the following message

```
Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".
```

[Example run](https://github.com/google/site-kit-wp/actions/runs/9513898544/job/26224939066#step:11:355)

This happens when loading the block editor in the following spec

- Site Kit admin bar component display › loads when editing a post with data in Search Console

This is present without Site Kit active, but only appears when `SCRIPT_DEBUG` is enabled (as when we are running E2E). This instance can safely be ignored since it is unrelated to SK.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E nightly tests should no longer fail due to the above console error

## Implementation Brief

* [x] Update `tests/e2e/config/bootstrap.js` - in `observeConsoleLogging` function add new conditional check for an error starting with `Warning: You are importing createRoot from` and return early if the condition is met

### Test Coverage

* No updates needed

## QA Brief

* No QA needed, it can be verified during MR, if E2E Nightly is passing in CI and moved straight to approval.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
No QA needed. Moving to Approval.
