### ISSUE TITLE
Ads setup CTA appears immediately after connecting SK

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8902]
## Bug Description

The CTA to setup the Ads module appears immediately after connecting SK. This isn't how other banners work, particularly those for module activation that have a presence on the dashboard. We should modify this potentially depending on if PAX is available or not. If available, we could move the CTA to be inline on the dashboard (similar to others). If not, we could keep the banner but only surface it after a period of time.

## Steps to reproduce

1. Connect SK for the first time
2. See Ads setup CTA banner

## Screenshots

<img width="985" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/aca133fe-e9f5-4a18-b550-4ac454efd1af">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Ads module setup CTA banner should not be shown to any users yet

## Implementation Brief

* [ ] Remove the component from being rendered https://github.com/google/site-kit-wp/blob/90b6eed18af86b436aeda7f2b499d54a561e724d/assets/js/components/DashboardMainApp.js#L266
* Do not remove the component itself or its stories, etc

### Test Coverage

* No changes expected

## QA Brief

* Set up Site Kit on a new site.
* The Ads module setup CTA (pictured above) should not appear.

## Changelog entry

* Remove Ads module setup CTA banner from SK dashboard.

**Comment by tofumatt** [comment]
Because this is relatively urgent (for a hot-fix) this is just about removal—normally we'd change how/when we render this notification as part of this issue, but because there’s a few ways we’d want to determine how to show it and that'll take more time, this looks good 👍🏻 

IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

The banner is no longer present after setting up SK and the only remaining references to it in the code base are in Storybook only.

:shipit:
