### ISSUE TITLE
Upgrade remaining GitHub Actions to Node 20

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8903]
## Bug Description

Some GitHub actions (eg. `actions/cache`) are still using older versions of the Node runtime and should be upgraded to newer versions that use supported versions of Node.

See: https://github.com/google/site-kit-wp/issues/8428#issuecomment-2176499826

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All `actions/cache` actions should not warn about outdated Node versions (eg. should use Node 20)
* All `actions/download-artifact` actions should not warn about outdated Node versions (eg. should use Node 20)
* All `actions/upload-artifact` actions should not warn about outdated Node versions (eg. should use Node 20)
* All `google-github-actions/upload-cloud-storage` actions should not warn about outdated Node versions (eg. should use Node 20)

## Implementation Brief

* [ ] Update cache actions to `v4` at:
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/e2e-tests.yml#L119
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/php-lint-tests.yml#L59
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/php-lint-tests.yml#L127
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/zips.yml#L98
* [ ] Update Download Artifact actions to `v4` at:
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/storybook.yml#L87
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/storybook.yml#L153
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/zips.yml#L138
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/zips.yml#L233
* [ ] Update Upload Artifact actions to `v4` at:
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/e2e-tests.yml#L135
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/storybook.yml#L72
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/visual-regression.yml#L53
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/zips.yml#L127
* [ ] Update Cloud Storage actions to `v2` at:
  * [ ] https://github.com/google/site-kit-wp/blob/e46b360a0f353f0d41e263e6c4989b0f5e4433f2/.github/workflows/zips.yml#L146

### Test Coverage

* All tests should continue to pass.

## QA Brief

* No explicit QA is needed; as long as GitHub Actions still run successfully all is good 👍🏻 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
Moving directly to Approval since no QA is needed here.
