### ISSUE TITLE
Rename the `Migration_Conversion_ID` migration to `Migration_1_129_0` for consistency

### ISSUE THREAD

**Issue by benbowler** [google/site-kit-wp#8905]
## Feature Description

We should rename the `Migration_Conversion_ID` migration to `Migration_1_129_0` for consistency [RE this comment](https://github.com/google/site-kit-wp/issues/8455#issuecomment-2176470518) @aaemnnosttv

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Migration_Conversion_ID` class should be renamed to `Migration_1_129_0` for consistency with migration naming conventions

## Implementation Brief

* [ ] Rename the class as per the AC and update its related tests

### Test Coverage

* No change in coverage

## QA Brief

* Do a quick smoke testing to ensure that the plugin still works as previously.

## Changelog entry

* Rename the `Migration_Conversion_ID` class to `Migration_1_129_0` for consistency with migration naming conventions.

**Comment by hussain-t** [comment]
Hi @eugene-manuilov, could you update the QAB even if it just states, “No testing required for these changes”? Thanks!

**Comment by eugene-manuilov** [comment]
@hussain-t, added.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified plugin setup with and without analytics.
- Verified all modules setup flow.
- Verified main and entity dashboard.
- Verified settings page.
- Verified plugin functionality working same as latest environment.
