### ISSUE TITLE
Prevent Selection Panel Info Notice from disappearing until two audiences are selected

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8909]
## Feature Description

In its initial implementation, the Selection Panel Info Notice will disappear when the user opens the Selection Panel with a single selected audience, and unchecks that audience.

This is not ideal, as the notice is intended to encourage the user to add a second audience to the selection, so it would be better to keep the notice visible until they have at least two audiences selected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Selection Panel Info Notice should only appear when the Selection Panel is opened with a single saved audience in the selection (this is as per the initial implementation).
* The notice should remain visible until at least two audiences are selected. It should not reappear if the user reduces the selection to a single audience while the selection panel remains open.
* Once two audiences are selected the notice should disappear.

## Implementation Brief

* [ ] Within `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AddGroupNotice.js`:
  * [ ] Replace the `selectionChanges` const, instead use the `getValue` selector to get the selected audiences passing `AUDIENCE_SELECTION_FORM, AUDIENCE_SELECTED` - this will return the list of currently selected audiences - call this `selectedAudiences`.
  * [ ] Create a new `useState` called `twoOrMoreAudiencesSelected` defaulting to `false`.
  * [ ] Create a `useEffect` watching changes on `selectedAudiences`:
     * [ ] If `selectedAudiences` is *not* an array, return early.
     * [ ] If `selectedAudiences.length > 1`, set  `twoOrMoreAudiencesSelected` = true
  * [ ] Update the if statement that returns null to be: `isDismissed || twoOrMoreAudiencesSelected`.
* [ ] Remove the now unused `AUDIENCE_SELECTION_CHANGED` form key and everywhere it's used/updated.

### Test Coverage

* No additional test are required.

## QA Brief

* Setup Site Kit with Analytics module
* Enable groups
* Open selection panel - by default when enabled, groupd will come with 2 audiences selected - verify that notice is not showing when 2 audiences are selected
* Deselect one - verify that notice is not showing in this scenario
* Save one audiences, and re-open the selection panel - verify that notice is showing until 2 are selected
* If one is deselected again - notice should not appear immediately, but only on the next opening

## Changelog entry

* Update the audience segmentation notice that is displayed in selection panel to not disappear until two audiences are selected.

**Comment by nfmohit** [comment]
@techanvil Just to quickly confirm, what happens if the user unselects one of the audiences after they've selected two? Should the notice reappear? If not, the IB will need to be updated to address that behaviour. I'll write my IBR feedback based on your response, thank you!

**Comment by techanvil** [comment]
Thanks @nfmohit - I should have been more explicit in the AC. The not should indeed not reappear - I've updated the AC accordingly.

**Comment by nfmohit** [comment]
Thank you for the update, @benbowler . I think 3 as an estimate is quite steep here just in case an unexpected side-effect comes up. Do you think it might be worth increasing it by a notch just so we're safe?

**Comment by benbowler** [comment]
Good point, updated @nfmohit

**Comment by nfmohit** [comment]
Thanks @benbowler ! IB LGTM 👍 ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified The Selection Panel Info Notice s appear only when the Selection Panel is opened with a single saved audience in the selection (this is as per the initial implementation).
- The notice remain visible until at least two audiences are selected. It not reappear if the user reduces the selection to a single audience while the selection panel remains open.
- Verified Once two audiences are selected the notice gets disappear.
- Verified If one is deselected again - notice not appear immediately, but only on the next opening.

<details>


https://github.com/user-attachments/assets/0d82ea4b-6ec5-452c-8fd8-b6cbdd503b40

</details>
