### ISSUE TITLE
Tiles layout on mobile and tablet is broken

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#8930]
## Bug Description

The layout on mobile and tablet is broken.
2 things to highlight here:
- The 'Top content by pageviews' section goes beyond the screen viewport. I suspect it's due to the long title names which are not truncated on those breakpoints.
- The tile is a single tile but you will see that there is a mark under 'All visitors' denoting as if there are other tabs but this is false. If it's a single tab, there should be no mark underneath.

## Steps to reproduce

1. Set up audience tile under the audience segmentation flag for 3 tiles
2. View it on mobile and tablet.

## Screenshots

<img width="339" alt="342345957-2863d851-5e9f-41a8-8a77-e75692ea45ad" src="https://github.com/google/site-kit-wp/assets/125576926/89754b0c-9d93-41da-8f22-0613a00470f2">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Audience segmentation is displayed correctly on all devices.

## Implementation Brief

* [ ] Layout is expanded by the page links, which can have very long text, and stretch the flex container nested within a grid. To contain the long page text, in https://github.com/google/site-kit-wp/blob/3cce2fa8ddf862ae58adf177380f66258316d0dc/assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-audience-tiles.scss#L94
  * Add `overflow: hidden`, this will contain the flex wrapper and long text within so it does not overflow across different screens.

### Test Coverage

* No updates needed

## QA Brief

* Enable the `audienceSegmentation` feature flag and set up Analytics + Audience Segmentation
* Set up Site Kit using `oi.ie`
* View the audience tile on the Site Kit dashboard
* No scrolling/widget being too wide should occur

## Changelog entry

* Fix the broken layout issue in the audience segmentation widget on mobile and tablet devices.

**Comment by mohitwp** [comment]
### QA update ✅ 

- Tested on main environment.
- Tested layout on mobile and tablet when only 1 audience widget is selected.
- Tested layout on mobile and tablet when 2 audience widget are selected.
- Tested layout on mobile and tablet when 3 audience widget are selected.
- Verified issue is resolved and widgets appears correctly in all devices.

<details>

![image](https://github.com/user-attachments/assets/b98d5d4f-bff4-4f30-8853-b6004a822003)

![image](https://github.com/user-attachments/assets/796570b1-bc54-4cc0-bda6-03bf3801e2e8)

![image](https://github.com/user-attachments/assets/c9044c03-0e38-402c-b2fc-1086df1b5509)

![image](https://github.com/user-attachments/assets/55da71a6-7886-4f04-836a-8557deda28e0)

_Two Audience Widget_

![image](https://github.com/user-attachments/assets/a5da17d6-525c-48d4-bf50-028a550dcf41)

![image](https://github.com/user-attachments/assets/644de2d6-0f61-4135-ac3e-093326757dd8)

![image](https://github.com/user-attachments/assets/5bc36391-0b22-4473-9d85-63f67ffd4496)

_Three Audience _Widget__

![image](https://github.com/user-attachments/assets/aa6c55ac-5b65-4588-9f47-1bbd1b3e4235)

![image](https://github.com/user-attachments/assets/58c58092-97c2-4a61-9c45-e8f9a8e1dc44)

![image](https://github.com/user-attachments/assets/4f91987b-85e6-416c-9fcb-79c1812e2221)

_Video -_


https://github.com/user-attachments/assets/f76b560f-20bd-4bbd-9eb2-c908574ec047

</details>
