### ISSUE TITLE
Four events are being tracked when we submit WP Forms with the Popup Maker plugin active.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#8944]
## Bug Description

I've noticed an edge case while testing WP Forms conversion tracking alongside the Popup Maker plugin. After closing the popup from Popup Maker and submitting the form, four 'Submit_lead_form' events are being tracked. Ideally, it should track only two events: one for analytics and one for Ads. When I deactivated Popup Maker, only two events were tracked, which is as expected.
Note: Tracking for Popup Maker alongside the WP Forms plugin is working fine.

## Steps to reproduce

1. Set up Site Kit with Analytics.
2. Set up Ads module.
3. Install WP Forms and Pop up maker plugin.
4. Set up both plugins.
5. In front end close pop up. (Pop up Maker)
6. Submit WP form.
7. See four events are getting tracked.
8. Disable Popup maker plugin.
9. Submit WP form.
10. Now, 2 events are getting track 1 for analytics and 1 for ads module which is expected.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/94359491/82b2c954-310d-4d42-83ef-d15dceb2f396)

![image](https://github.com/google/site-kit-wp/assets/94359491/0b7f0e45-f63f-4a87-bd41-052273639cf6)

https://github.com/google/site-kit-wp/assets/94359491/490870ef-4c1a-4cb5-879a-74558a0007a5

When popup maker is disabled

![image](https://github.com/google/site-kit-wp/assets/94359491/cb53d47e-31a7-4a65-91c5-361a755bd6f6)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A single GTag event should be fired per supported Event Conversion Provider action (per tag), especially when said provider (i.e WPForms) is also supported by Popup Maker.

## Implementation Brief
* [ ] Update the `window._googlesitekit.gtagEvent` inline JS function at `includes/Core/Conversion_Tracking/Conversion_Tracking.php`
    * [ ] Update the logic of the `gtagEvent` function to include a new `key` const that is defined as a JSON string of an object containing the `name` and `data` parameters of the `gtagEvent` function as said object keys.
        * [ ] Said key should be added to a newly defined `window._googlesitekit.throttledEvents` object or similarly appropriately named 
        * [ ] If the key for the current event passed to the `gtagEvent` function is present in the above object, return early, the event should not be fired
        * [ ] If it is not present, continue to add the key to the newly defined object above, with a value of `true`
            * [ ] At the same time, set a timeout of `500` ms to remove/delete the key entirely from the object above
            * [ ] Lastly, continue to call the `gtag` function and track the event accordingly
* [ ] An internal thread discussing the above solution can be found [here](https://10up.slack.com/archives/C0788NZMLF2/p1720529319156019).

### Test Coverage

* No test updates are required as a result of EX against this issue

## QA Brief

* Setup Site Kit and follow steps to reproduce from the issue description
  * Note that `Enhanced conversion tracking` toggle should be enabled to track the events, this step is omitted from steps to reproduce
* Verify no double event is tracked
* Popup Maker also supports integration with 2 other plugins, beside WP Forms, so it can be tested with Contact Form 7, and Ninja Popup as well. 

## Changelog entry

* Ensure WP Forms events are only sent once when Popup Maker plugin is installed.

**Comment by 10upsimon** [comment]
This required some investigation, and the reason we are seeing the duplicate events is because form plugins that popup maker supports are tracker for submissions _regardless of whether they are in a popup or not_. Ultimately, they are converted to `pum.integration.form.success` actions that we alrady listen to as part of our `assets/js/event-providers/popup-maker.js` provider script, hence the duplicate tracking.

This will likely happen for all forms that we support individually via event provider scripts that are equally supported by the Popup Maker plugin.

The discussed solution in Slack is to throttle the inline `gtagEvent` function so that duplicate events are not fired. This has been described in the IB.

**Comment by zutigrm** [comment]
Thanks @10upsimon , almost there. The approach can be clarified just a bit

> Change the logic so that the tracking of events is throttled by a key which is the JSON string equivalent of the name and data params passed to the function

I would mention that `gtagEvent` function logic should be updated to expand on including JSON string of the object which should consist of `name` and `data` parameters

> At the same time, set a timeout of 500ms to clear the key from the object above

Just for better clarification, maybe we can say `remove` the key, instead of `clear` the key, which can mean empty the value, etc. Delete or remove, might be more appropriate.

Maybe it can be also useful to include the link to the thread reply from Eugene as an example to take a look at as the last point

**Comment by zutigrm** [comment]
@10upsimon thanks, IB LGTM

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Tested Popup maker integration with WP Forms and Ninja Forms plugin.
- Verified only 2 events are now tracking when user submit WP Form.


@zutigrm If pop up maker plugin is active and if user submits Ninja Forms then 4 conversion events are getting tracking 2 for Ninja forms and 2 for popup maker.

@wpdarren Can you please test popup maker integration with Contact Form 7. 

**_Ninja Forms conversion tracking with Popup Maker_**

</details>

![image](https://github.com/user-attachments/assets/07a35dc6-668b-4f37-991c-bb5082b4b8c1)


https://github.com/user-attachments/assets/622e091b-7813-4cc5-b2c2-392d03a2a402

</details>

**PASS SCENARIOS**

**_WP Forms conversion tracking with Popup Maker Plugin_**

<details>


https://github.com/user-attachments/assets/9a913beb-78df-42b1-8a5a-dc59b0808a10



![image](https://github.com/user-attachments/assets/0e512cca-01ab-4b71-99ef-26b50d5e7471)

</details>

**_Pop up Maker Conversion event tracking with WP forms_** 

<details>


https://github.com/user-attachments/assets/f314e519-0d92-4a62-93a4-39bcfc89dd03



![image](https://github.com/user-attachments/assets/2aa7f6f5-3cc6-4ee5-86e2-95557eade406)

</details>

**Comment by wpdarren** [comment]
@zutigrm @mohitwp for Contact 7: 

With only Ads module connected.  I see 2 events for `contact` and 2 events for `submit_lead_form`

![1](https://github.com/user-attachments/assets/4d4fe071-9fb9-4d88-b3de-3d97214933b7)

With Ads and Analytics connected.  For the Google tag I see 1 event for `contact` and 1 for `submit_lead_form` and for the Ads tag I see 2 events for `contact` and 2 events for `submit_lead_form`

![2](https://github.com/user-attachments/assets/ad425c03-884d-4dd6-b9ce-4b252dfae922)

With only Analytics connected.  I see 1 event for `contact` and 1 for `submit_lead_form`

![3](https://github.com/user-attachments/assets/e341e50e-9596-436b-bae8-affef4305ab8)

For me the double tracking systems to be when Ads is connected either with or without Analytics connected.

**Comment by eugene-manuilov** [comment]
@mohitwp just fyi that it is fine if both events are triggered when a CF form is used in the popup because those are two different events (otherwise they would have the same name). cc @wpdarren

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm 
I noticed that when I submit a Contact Form 7, the `"contact" `event is tracked as expected. However, when the Popup Maker plugin is active, along with the "contact" event, the `"Submit_lead_form"` event is also tracked. This is a different event. Is it correct for the `"Submit_lead_form"` event, which belongs to Popup Maker, to be tracked when submitting Contact Form 7? As per my understanding if I'm submitting contact form 7 then event associated with it which is `'Contact'` event should get track. 


<details>

Contact Form 7 with popup maker

![image](https://github.com/user-attachments/assets/a6f94bab-1ca4-4c77-9664-06df8722b0fa)


https://github.com/user-attachments/assets/4fc12359-1dfd-4e6c-9a2d-5497861e93be

Contact Form 7 without Popup maker

![image](https://github.com/user-attachments/assets/1f213b40-1f37-46ae-a899-720e4b9429b9)

</details>


**PASS CASES**

**Ninja forms conversion tracking when Popup Maker plugin enabled**

<details>

![image](https://github.com/user-attachments/assets/67248b25-d849-4bee-86cf-99159609a923)

![image](https://github.com/user-attachments/assets/a7e892fe-314f-4edf-a7b1-8279b431f059)

https://github.com/user-attachments/assets/bb7e1e69-29c3-4d23-9afe-c03e4381f1fb

</details>

`WP Forms conversion tracking when Popup Maker plugin enabled`

<details>

![image](https://github.com/user-attachments/assets/31ec7314-eaa8-4a9b-9a9c-890fd78307c3)

![image](https://github.com/user-attachments/assets/3ca5d546-c412-4304-bdbe-f96780ef108c)

https://github.com/user-attachments/assets/6a642e9b-a7b1-4ad2-bee7-2de4eab9c170

</details>

**Comment by zutigrm** [comment]
@mohitwp Yes it is correct, that is what's @eugene-manuilov [comment](https://github.com/google/site-kit-wp/issues/8944#issuecomment-2242946416) above is about

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @zutigrm !

- Tested on dev environment.
- Tested popup maker integration with WP forms plugin.
- Tested popup maker integration with Ninja Forms plugin.
- Tested popup maker integration with Contact Form 7 plugin.
- Verified A single GTag event gets fired per supported Event Conversion Provider action (per tag), 


**Contact Form 7 form conversion tracking when Popup Maker plugin enabled***

<details>

_Contact Form 7 with popup maker_

![image](https://github.com/user-attachments/assets/a6f94bab-1ca4-4c77-9664-06df8722b0fa)


https://github.com/user-attachments/assets/4fc12359-1dfd-4e6c-9a2d-5497861e93be

_Contact Form 7 without Popup maker_

![image](https://github.com/user-attachments/assets/1f213b40-1f37-46ae-a899-720e4b9429b9)

</details>



**Ninja forms conversion tracking when Popup Maker plugin enabled**

<details>

![image](https://github.com/user-attachments/assets/67248b25-d849-4bee-86cf-99159609a923)

![image](https://github.com/user-attachments/assets/a7e892fe-314f-4edf-a7b1-8279b431f059)

https://github.com/user-attachments/assets/bb7e1e69-29c3-4d23-9afe-c03e4381f1fb

</details>

`WP Forms conversion tracking when Popup Maker plugin enabled`

<details>

![image](https://github.com/user-attachments/assets/31ec7314-eaa8-4a9b-9a9c-890fd78307c3)

![image](https://github.com/user-attachments/assets/3ca5d546-c412-4304-bdbe-f96780ef108c)

https://github.com/user-attachments/assets/6a642e9b-a7b1-4ad2-bee7-2de4eab9c170

</details>
