### ISSUE TITLE
Update the getReferenceDate selector not to return a date object

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#8946]
## Feature Description

See this comment: https://github.com/google/site-kit-wp/pull/8749#discussion_r1661058584

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `getReferenceDate` selector should return a string.

## Implementation Brief

* [ ] Review and merge #8945

### Test Coverage

* Update existing tests where needed.

## QA Brief

* Do a quick smoke test of the plugin. Everything should remain as it was before.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
@aaemnnosttv could you please review this?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv, i'll assign this ticket back to myself. Found one thing to improve in my pr.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified plugin setup.
- Verified main and entity dashboard.
- Verified data according to date range.
- Verified zero and gathering data state.
- Verified all modules setup.
- Verified all functionalities working same as latest environment and as expected.

<details>

https://github.com/user-attachments/assets/deb5c932-b57e-4c4f-8efe-88254c64ed0d

https://github.com/user-attachments/assets/de6de8c3-8e64-4f5f-a20d-7bffd5495352

https://github.com/user-attachments/assets/e181f86b-84c8-477f-897b-3b9c4b126fcd

https://github.com/user-attachments/assets/99410148-edb4-45fa-a380-fcd6a39485c9

</details>
