### ISSUE TITLE
Add real-time data from Google Analytics in Dashboard

### ISSUE THREAD

**Issue by ridmdsakil** [google/site-kit-wp#895]
Please add real-time data from Google Analytics in Dashboard. It will be great.

<img width="1355" alt="Screen Shot 2019-11-22 at 8 29 35 AM" src="https://user-images.githubusercontent.com/41326532/69410114-3d6ef900-0d02-11ea-9bbd-04a734765a98.png">

**Comment by Tobias-Conrad** [comment]
I like it too.
A good example for a speedy and general information containing dashboard is "Google Analytics Dashboard for WP (GADWP)". I do not use them because the Plugin was sold and not developed anymore and only maintained.

**Comment by marrrmarrr** [comment]
Something interesting look into this when we're scoping the product requirements for GA4 reporting capabilities.

**Comment by tofumatt** [comment]
Real-time Analytics would be a large undertaking/new feature to add; it might not fit well into the current dashboard, especially where most of the data is cached and not available for real-time consumption.

I'm going to close this for now but we can always re-open this issue or a new one if we decide to take on support for real-time Analytics reports in the future 🙂
