### ISSUE TITLE
Refactor the ZeroDataNotification to use the new Notifications datastore

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8977]
## Feature Description

This issue will "use" the new datastore infrastructure to queue the `ZeroDataNotification` using the new datastore infrastructure.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ZeroDataNotification` should be refactored and rendered (queued) using the new `core/notifications` datastore. This means that the component should not be called directly but via the generic `getQueuedNotifications` selector.
* The refactored component should be its own standalone component without any business logic that prevents it from rendering. This component should be passed through when registering the new notification.

## Implementation Brief

* [x] Wait for the dependency issues to be merged.
* [x] In `assets/js/googlesitekit/notifications/register-defaults.js`:
  * [x] Add the registration of the `ZeroDataNotification` notification similar to the `GatheringDataNotification` component. 
  * [x] Priority should be 10 more than the `GatheringDataNotification`.
  * [x] The check requirements call back function should be similar to `GatheringDataNotification`. However, return `false` if either `hasSearchConsoleGatheringData` or `hasAnalyticsGatheringData` params are true. This is so that, either the `GatheringDataNotification` and the `ZeroDataNnotification` NEVER get queued together.
  * [x] Within `BannerNotifications` and `EntityBannerNotifications`, remove the call to `ZeroDataNotification`.

### Test Coverage

* No new tests required.

## QA Brief

Ideally - WAIT for this issue to be merged and then QA both #8976 and this issue together as they are exactly the same pattern in code.

* Thoroughly smoke test the GatheringData and ZeroData notifications:
  * Test when only Search Console is gathering data (and analytics is disconnected).
  * Test when both, Search Console and Analytics is Gathering Data.
  * Test when Search Console has finished gathering data but Analytics is still Gathering Data.
  * Test when either and both, SC and Analytics are in Zero data state.
  * Test all of the above for the Entity Dashboard as well.
* Test when any other notification, say any other `SetupSuccessBannerNotification` is active - they should take precedence over the Gathering and Zero Data notifications.
* Smoke test the remaining notifications to ensure they still work normally.
* Test the new Storybook stories in Components -> Notifications.

## Changelog entry

* Refactor the ZeroDataNotification to use the new Notifications approach.

**Comment by eugene-manuilov** [comment]
AC and IB ✔️

**Comment by jimmymadon** [comment]
@mohitwp This issue is now merged, so I have assigned you this one as you were assigned to #8976. Both these issues can be QAed now together as per their QAB. c.c. @wpdarren

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified zero data notifications on main, entity and view only dashboard.
- Smoke tested plugin notification and verified that other notifiations - take precedence over the Gathering and Zero Data notifications.
- Tested storybook component >notifications stories.

@jimmymadon 
**Issue >** On View only dashboard zero and gathering data notifications are not showing. On latest environment zero and gathering data state notifications are showing.


<details>


https://github.com/user-attachments/assets/102d3b92-bfcb-411b-8693-4738bc237066

</details>

**Question** > The "AdSense - Earnings at risk" notice reappears when we open the dashboard in a new tab, even after clicking "OK, Got It!" This occurs in both the latest and development environments. Is this expected?

<details>

![image](https://github.com/user-attachments/assets/759c7db0-87d0-42db-942d-24f52d130d97)


https://github.com/user-attachments/assets/109bd5c5-52cd-4853-a579-c167be7cc2fe

</details>



**PASS CASES**

<details>


SC gathering Data

![image](https://github.com/user-attachments/assets/55c19487-e61d-4a69-8657-3ac49b40127e)


SC and Analytics gathering data

![image](https://github.com/user-attachments/assets/425e7116-b8d5-4831-a791-12821d294847)

Entity Dashboard (SC and Analytics gathering data)

![image](https://github.com/user-attachments/assets/1b76bc61-4e22-4b12-938d-bff344f00664)

SC is in gathering data state and Analytics is in zero data state.

![image](https://github.com/user-attachments/assets/00cc73b1-8045-4475-8042-adf3d7dc86da)

Entity Dashboard ( SC is in gathering data state and Analytics is in zero data state.)

![image](https://github.com/user-attachments/assets/83c7f0c0-57a5-45cf-9d7c-2e02a240d321)

Both SC and analytics are in zero data state

![image](https://github.com/user-attachments/assets/30d113e7-6706-446c-b5a9-9bb4f2ff645c)

Entity Dashboard ( Both SC and analytics are in zero data state)

![image](https://github.com/user-attachments/assets/7cc4b68d-3084-4002-ab23-3339ee4ae5de)

Only Analytics is in gathering data state

![image](https://github.com/user-attachments/assets/1c3f78da-a48c-4fd0-8453-e320565077de)

Entity dashboard (Only Analytics is in gathering data state)

![image](https://github.com/user-attachments/assets/9d0ec303-6b96-4717-8795-0696b9089009)



Other notifications- Another Admin

![image](https://github.com/user-attachments/assets/b2910d07-700c-40ed-a549-8e6bb6668a59)

![image](https://github.com/user-attachments/assets/5ccf5f07-e9f6-4342-a64d-48439b12da01)

</details>

**Comment by jimmymadon** [comment]
Holding this issue in CR with me until #8976 has its follow up PR merged as it fixes this issue too. Then will move this straight to QA.

**Comment by jimmymadon** [comment]
@mohitwp Thanks - back to you for another pass!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified zero data notifications and gathering data notifications on main, entity and view only dashboard.
- Smoke tested plugin notification and verified that other notifications - take precedence over the Gathering and Zero Data notifications.
- Tested storybook component >notifications stories.
- Verified that view only dashboard related issue is resolve now. Zero and gathering data notifications are now showing on View only dashboard.
- **Note** - There are a few additional issues, but these are due to changes introduced in #9184 and #9071. They will be addressed in a follow-up pull request



<details>

![image](https://github.com/user-attachments/assets/7a381813-375a-4e0c-bc3f-35ec1810b057)

![image](https://github.com/user-attachments/assets/48879d8e-8b6a-40b0-849a-8ea25ec1e779)

![image](https://github.com/user-attachments/assets/ecc683f2-0bf1-4724-8b09-d978a9a1d796)

![image](https://github.com/user-attachments/assets/1ee255c6-73e9-4a08-9111-397a615039e9)


https://github.com/user-attachments/assets/f430fbd7-dd3e-4dc7-9017-370310bbef05

https://github.com/user-attachments/assets/9404f92c-af2c-4cee-9f0a-dcf740778804

</details>
