### ISSUE TITLE
Refactor the UnsatisfiedScopesAlert to use the new Notifications datastore and layout components

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8978]
## Feature Description

This issue is the first issue to refactor an "Error" notification in Site Kit. It should refactor the `UnsatisfiedScopesAlert` so that it uses the new datastore infrastructure to register and queue the notification. It should also use newer lighter "layout" and "common" components that replace the bloated `BannerNotification` component as per the pattern introduced in #9071.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `UnsatisfiedScopesAlert` component should be refactored so that it is registered and rendered (queued) using the new `core/notifications` datastore. 
* This notification component should not be called directly (i.e. in `ErrorNotifications`) but only via the generic `getQueuedNotifications` selector.
* The refactored component should not contain any business logic that hides it / prevents it from rendering. This logic should be contained in a callback function defined during registration.
* The component should not use the bloated `BannerNotification` component. Instead, it should be rendered using the new `Notification` component wrapper and a simpler "layout" component that solely encapsulates its structure and design.

## Implementation Brief

* [x] Update `assets/js/components/notifications/UnsatisfiedScopesAlert.js`
  * Check the `assets/js/components/notifications/GatheringDataNotification.js` for the example 
  * Remove usage of `BannerNotification` component
  * Include 2 new props - `id` and `Notification`
  * Wrap the component with `Notification` component passed as the prop 
  * Use new components from `assets/js/googlesitekit/notifications/components/common/` to assemble the notification using the existing props used to for `BannerNotification`
  * You can refactor a bit the `assets/js/googlesitekit/notifications/components/common/ActionsCTALinkDismiss.js` to accept `isDismissal` prop which would conditionally render dismiss button, so it can be used as part of this notification which is not dismissible.
  * Perhaps, you can also include a new layout type in `assets/js/googlesitekit/notifications/components/layout/` so other simple layout notification can use it. It can be called `NotificationWithNoSVG` for example
* [x] Update `assets/js/googlesitekit/notifications/register-defaults.js`
  * Register the notification, following the existing patterns already added
  * For `checkRequirements` transfer the existing checks in `assets/js/components/notifications/ErrorNotifications.js` 
  * For priority, I would suggest using `400` as base number, starting from this one. So all error style notifications can use it, by incrementing on this base number for later higher priority ones.
* [x] Remove `UnsatisfiedScopesAlert` from the `assets/js/components/notifications/ErrorNotifications.js` 

### Test Coverage

* Add stories for new notification. You can use `assets/js/components/notifications/GatheringDataNotification.stories.js` as an example

## QA Brief

* Test the Gathering and Zero Data notifications - mainly the CTA action buttons as this issue modifies that code.
* Test the `UnsatisfiedScopesAlert` by reducing the number of satisfied scopes.
  * To do this, you can modify the `wp-usermeta` table's `wp_googlesitekit_auth_scopes` meta-key row. Set meta value where the webmasters scope has been deleted:
  ```
  a:4:{i:0;s:46:"https://www.googleapis.com/auth/userinfo.email";i:1;s:48:"https://www.googleapis.com/auth/siteverification";i:2;s:6:"openid";i:3;s:48:"https://www.googleapis.com/auth/userinfo.profile";}
  ```

## Changelog entry

* Update banner notification code for the "Unsatisfied Scopes Alert" banner notification.

**Comment by tofumatt** [comment]
Moving this to the backlog until #8976, which is marked as blocking this issue, is completed. That way we can mirror the approach used in #8976 for other migrations/refactoring.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
@jimmymadon Thanks, makes sense

**Comment by jimmymadon** [comment]
Since these issues combine the registration and design, I will bump up the estimate to 15 here in line with our points experiment as this would unlikely be a 7 in "normal" scenarios. As seen in other issues, these issues do require proper CR and QA + any time for fixes in case the issue fails QA.

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.

@jimmymadon Please find my observations below
- **Issue 1:** Zero and data-gathering notifications are appearing below the success notification and other notifications, such as the 'Enable Enhanced Measurement' banner notice.


<details>

![image](https://github.com/user-attachments/assets/80ecc760-b11c-4d21-a7b4-fecf9f5f414b)

![image](https://github.com/user-attachments/assets/bb4c996e-7138-4d8f-bf3e-8a74db2181dc)

![image](https://github.com/user-attachments/assets/69aa1cd6-b2d5-446e-ac9d-381af2ff8725)

![image](https://github.com/user-attachments/assets/f7c5fbac-f0b3-431f-8450-4f224bd986e4)

</details>

- **Issue 2:** Zero data notifications appear only once and do not reappear after reloading the page or opening the dashboard in a new tab. 

<details>


https://github.com/user-attachments/assets/868d0c92-6f2e-4703-a35b-b2c1f066ddc1

</details>

**Comment by jimmymadon** [comment]
> ### QA Update ❌
> * Tested on dev environment.
> 
> @jimmymadon Please find my observations below
> 
> * **Issue 1:** Zero and data-gathering notifications are appearing below the success notification and other notifications, such as the 'Enable Enhanced Measurement' banner notice.

This should now be fixed.

> * **Issue 2:** Zero data notifications appear only once and do not reappear after reloading the page or opening the dashboard in a new tab.


For me, the `ZeroDataNotification` does appear on page reload. However, it does not appear when we open the dashboard in a new tab. I will add this to the ACs of #9227 as the cause of the inconsistent behaviour is the same here.


> **Issue 3** : Alignment of unsatisfied scope alert is not correct on dev environment.

This should now be fixed as well.
