### ISSUE TITLE
Implement the Audience Creation Notice as a presentational component (Storybook)

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8986]
## Feature Description

Create the Audience Creation Notice, as a presentational component (i.e. implement the visual design but not the business logic), and add it to Storybook.

See [audience creation](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.pda4nwxa57g0) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Audience Creation Notice should be created as a presentational component, implementing the visual design but not the business logic.
- Stories for it should be added to Storybook.
- The notice should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1821-25183&mode=design&t=UNIUYXEPBuLKdrGJ-0).
- It should have a title with the following copy: _Create groups suggested by Site Kit_
- It should have an "X" icon in the top right corner.
- It should show a row for each of the "new visitors" and "returning visitors" audiences, displaying their names and descriptions as follows (in line with the values specified in [audience configuration](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.c3935058ied6) in the design doc):
  - Name: _New visitors_
    - Description: _People who visited the site for the first time_
  - Name: _Returning visitors_
    - Description: _People who have visited your site at least once before_
- Each audience should have a **Create** CTA button.

## Implementation Brief

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/constants.js`:

* [x] Add a new constant `AUDIENCE_CREATION_NOTICE_SLUG` with the value `audience-segmentation-creation-notice` (or an appropriate key value).

### `AudienceCreationNotice` component

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel` directory, create a new file `AudienceCreationNotice.js`:

* [x] Create a new functional component, `AudienceCreationNotice`, that will be used to render the Audience Creation Notice.
* [x] Retrieve the Site Kit created audiences from the `getConfigurableAudiences` selector. For example, see how this is being filtered `AudienceItems` component:
https://github.com/google/site-kit-wp/blob/8240ccf423e84ab53dc7fcea36833feae1736235/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceItems.js#L60-L70
* [x] Descriptions for the audiences should be retrieved from [`SITE_KIT_AUDIENCE_DEFINITIONS`](https://github.com/google/site-kit-wp/blob/b67e9a1ea124dc8d233def811d9adfb99c995544/assets/js/modules/analytics-4/datastore/constants.js#L108).
* [x] Render the notice with the following structure:
  * [ ] Reuse the container styles from the `AddGroupNotice` component.
  * [ ] Reuse the styles to align the audience name and description from the `SelectionPanel` component.
  * [x] Render the close button with the [X](https://github.com/google/site-kit-wp/blob/001d6128da62b59ad599b834a440ebc3b9f5d205/assets/svg/icons/close.svg) icon. See how it's being implemented in the `SelectionPanelHeader` component:
  https://github.com/google/site-kit-wp/blob/7ea3bb35dd70112f679f6336b6d0f5d0b327aa3e/assets/js/components/SelectionPanel/SelectionPanelHeader.js#L39-L45
  * [x] Pass a callback function that dispatches the `dismissItem` action with the `AUDIENCE_CREATION_NOTICE_SLUG` constant to the `onClick` event of the close button.
  * [x] Render the `SpinnerButton` component with the following props:
    * [x] `children`: `Create`
    * [x] `spinnerPosition`: `SPINNER_POSITION.BEFORE` (`before`).
    * The `onClick` handler will be implemented in [#8164](https://github.com/google/site-kit-wp/issues/8164).
* [x] The notice and the CTA buttons should be styled according to the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1821-25183&mode=design&t=UNIUYXEPBuLKdrGJ-0).
* [x] Add the custom styles in `assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-audience-selection-panel.scss`.
* [ ] **Note**: The business logic to conditionally render the notice and create an audience will be implemented in [#8164](https://github.com/google/site-kit-wp/issues/8164).

### Test Coverage

* [x] Add storybook stories in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationNotice.stories.js`.
* [x] Add test coverage for the `AudienceCreationNotice` component in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationNotice.test.js`.

## QA Brief

* Inspect the new [AudienceCreationNotice](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencecreationnotice--default) storybook story and confirm it matches designs.

## Changelog entry

* Implement the Audience Creation Notice as a component which is visible in Storybook.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA update ⚠️ 

There were some figma discrepancies found but these can be ignored for now since they are minor.
The only thing I want to flag is that we need to remove the period from the copy: 'Create groups suggested by Site Kit'

<Details>
Figma copy without period:
<img width="913" alt="Screenshot 2024-07-26 at 11 57 14" src="https://github.com/user-attachments/assets/873f6864-8a96-4697-96a8-cb61c9e417a2">

Implemented copy with period:
<img width="915" alt="Screenshot 2024-07-26 at 11 58 40" src="https://github.com/user-attachments/assets/c4d537de-e21a-4a83-96e7-424ecdbce27b">

</Details>

**Comment by hussain-t** [comment]
Hi @kelvinballoo, I can remove the period as part of [8164](https://github.com/google/site-kit-wp/issues/8164) which I just move to CR.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Reviewed the text and the period has been removed now.
<Details>
<img width="972" alt="Screenshot 2024-07-31 at 19 24 18" src="https://github.com/user-attachments/assets/489309d3-6ef7-4259-a878-927492a6cc4e">
</Details>

This is ready to go. Moving ticket to approval

Other items reviewed as part of this ticket are:
- The notice should follow the Figma design.
- It has a title with the following copy: Create groups suggested by Site Kit
- It has an "X" icon in the top right corner.
- It shows a row for each of the "new visitors" and "returning visitors" audiences, displaying their names and descriptions as follows:
   - Name: New visitors
   - Description: People who visited the site for the first time
   - Name: Returning visitors
   - Description: People who have visited your site at least once before
- Each audience has a Create CTA button
