### ISSUE TITLE
Implement the Audience Creation Success Notice as a presentational component (Storybook)

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8987]
## Feature Description

Create the Audience Creation Success Notice, as a presentational component (i.e. implement the visual design but not the business logic), and add it to Storybook.

See [audience creation](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.pda4nwxa57g0) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Audience Creation Success Notice should be created as a presentational component, implementing the visual design but not the business logic.
- Stories for it should be added to Storybook.
- The notice should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1822-27536&mode=design&t=UNIUYXEPBuLKdrGJ-0).
- This notice should have the following copy: _Visitor group created successfully!_
- It should have a _Got it_ dismissal button.

### `AudienceCreationSuccessNotice` component

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel` directory, create a new file `AudienceCreationSuccessNotice.js`:

* [ ] Create a new functional component, `AudienceCreationSuccessNotice`, that will be used to render the Audience Creation Success Notice.
* [ ] It should be similar to the [ErrorNotice](https://github.com/google/site-kit-wp/blob/07d33a0bc20d31e46a1b6337d011ed8f7b8215c0/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/ErrorNotice.js) component.
* [ ] Render the notice with the following structure:
    * [ ] Render the [CheckFill](https://github.com/google/site-kit-wp/blob/5fd4e88d0832ff99c65d093b11ae64332c2c04fb/assets/svg/icons/check-fill.svg) icon on the left side of the notice.
    * [ ] The notice should have the following copy: `Visitor group created successfully!`.
    * [ ] The background color should be `#B8E5CA`.
    * [ ] Render the `Got it` button on the right with the following props:
    * [ ] `children`: `Got it`.
    * [ ] `tertiary`: `true`.
    * The `onClick` handler will be implemented in [#8164](https://github.com/google/site-kit-wp/issues/8164).
    * [ ] The color of the button should be `#265C3B`.
* [ ] The notice should be styled according to the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1822-27536&mode=design&t=UNIUYXEPBuLKdrGJ-0).
* [ ] Add the custom styles in `assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-audience-selection-panel.scss`.
* [ ] **Note**: The business logic to set the global state and render the notice will be implemented in [#8164](https://github.com/google/site-kit-wp/issues/8164).

### Test Coverage

* [ ] Add storybook stories in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationSuccessNotice.stories.js`.
* [ ] Add basic test coverage for the `AudienceCreationSuccessNotice` component in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationSuccessNotice.test.js`.

## QA Brief

- Open the component in Storybook and compare it to the Figma design.
- Storybook links:
  - [`develop`](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencecreationsuccessnotice--default).

## Changelog entry

* N/A

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
QA Update ✅ 

This is verified good.
- The notice follows the Figma design with the copy: Visitor group created successfully!
- There is a **Got it** dismissal button.
- Following were verified:
   - Icon size
   - Font size, weight and family for copy and button
   - Button size
   - Overall layout and paddings/margins
   - Hover effect
- Viewed on mobile and tablet breakpoints.
- Checked across main desktop browsers (Chrome, Firefox, Safari and Edge)

<Details>
<img width="746" alt="Screenshot 2024-07-25 at 18 21 07" src="https://github.com/user-attachments/assets/11cbb7d6-9df4-4725-a6e5-4d6b88d63a59">
</Details>
