### ISSUE TITLE
Setup Analytics need better instruction when there is no matched property

### ISSUE THREAD

**Issue by ivankristianto** [google/site-kit-wp#90]
## Bug Description

During the Analytics setup process, my Analytics account only has 1 account and property, which is not a matched property with the current Site Kit siteURL.
and it does show a button and a not working refetch link.

## Steps to reproduce

1. Have 1 GA account and ensure it doesn't has matched property
![Image 2019-07-01 at 20 19 39](https://user-images.githubusercontent.com/656006/60439837-b2e80900-9c3d-11e9-9566-df297937ed1d.png)

2. Setup Site Kit and add Analytics service.
3. Setup screen doesn't do anything:
![Screen Shot 2019-07-01 at 20 16 55](https://user-images.githubusercontent.com/656006/60439883-cd21e700-9c3d-11e9-96d0-046ff0efe085.png)

## Expected behavior

Add an instruction what the user should do next. And also have auto refetch when user leave the screen and comeback.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by felixarntz** [comment]
This appears to no longer be relevant. Feel free to reopen if it shows to still be an issue.
