### ISSUE TITLE
WordPress VIP Compatibility

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#901]
## Feature Description

Sites hosted on WordPress VIP currently are unable to use Site Kit due to a few violations of their code standards which are a bit more strict than those currently used in some cases.

This currently prevents some of the largest WordPress sites from using Site Kit.

Site Kit needs only to include the `WordPressVIPMinimum` ruleset for PHPCS and make a few minor changes to be VIP-compatible.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit PHP codebase should satisfy minimum WordPress VIP requirements.

## Implementation Brief

* Amend #900 so that it also includes the necessary setup parts (in `composer.json` and `phpcs.xml`).

## Changelog entry

* Improve compatibility with WordPress VIP environment.

**Comment by aaemnnosttv** [comment]
Holding on this one for now pending the merging of #886 (included in upcoming release) which should address most (if not all) remaining violations. Moving to blocked for now.

**Comment by moraleida** [comment]
The changes in #900 were approved by VIP last week, thanks everyone!

**Comment by aaemnnosttv** [comment]
## QA ✅ 

In addition to confirmation from @moraleida, I tested that the VIP ruleset for VIP is working properly.

Removing `// phpcs:ignore WordPress.VIP.DirectDatabaseQuery` for a wpdb call produces the expected warning from the VIP ruleset.

```
> phpcs 'includes/Core/Authentication/Authentication.php'

FILE: .../google-site-kit/includes/Core/Authentication/Authentication.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 334 | WARNING | Usage of a direct database call is discouraged.
     |         | (WordPress.VIP.DirectDatabaseQuery.DirectQuery)
----------------------------------------------------------------------

Time: 1.32 secs; Memory: 20MB
```
