### ISSUE TITLE
Speed Kit plugin conflict: Blank Site Kit Dashboard and Admin Pages

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#902]
When the[ plugin Speed Kit](https://wordpress.org/plugins/baqend/) is activated, Site Kit's dashboard and admin pages are blank. There are also [these react errors](http://snippi.com/s/7urw8s3) in the console (un-minified). Reported [here](https://wordpress.org/support/topic/plugin-incompatibility-with-site-speed/) in forums. 

## Steps to reproduce

1. Install and activate [Speed Kit plugin](https://wordpress.org/plugins/baqend/)
2. Go to Site Kit dashboard and other admin pages

## Screenshots
<img width="1272" alt="Speed Kit with Site Kit blank dashboard with react errors" src="https://user-images.githubusercontent.com/8108643/69472084-c285fc80-0d5a-11ea-8948-1927dec5b07d.png">

## Additional Context

 - PHP Version: 7.1.33
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.1.0
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by cole10up** [comment]
I was able to reproduce this one with the following steps.

**Steps:**

Navigate here: http://mediatemple.cmsdevrel.com/wp-admin/admin.php?page=googlesitekit-splash
UN: 10upCH06
PW: aYlvC362C^NE%LA$

Click dashboard, expand browser console.

I reproduced this after I hit a 500 during the setup process **after clicking the verify domain step**

**Comment by ernee** [comment]
Closing since testing with the current versions of Site Kit and Speed Kit no longer presents this issue. Thanks!
