### ISSUE TITLE
Add "Privacy Sandbox" (`privacySandboxModule`) feature flag

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9025]
## Feature Description

For work on the new Privacy Sandbox feature, let's add a new feature flag for the feature.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `privacySandboxModule` feature flag should be added to the plugin and appear in the list of features in the Tester plugin.

## Implementation Brief

* [ ] Add `privacySandboxModule` to `feature-flags.json`

### Test Coverage

* No tests needed.

## QA Brief

* The `privacySandboxModule` should appear in the list of feature flags in the Tester plugin.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `privacySandboxModule` appears in the list of feature flags in the Tester plugin.
- Made sure that the feature flag can be enabled and saved.
- Refreshed the tester plugin screen to ensure that the feature flag is still enabled. 
- Checked that the Site Health info for Site Kit included the feature flag and the correct status appeared. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/9ca0c832-acea-4a9c-8f26-1dff35cb59cb)
![image](https://github.com/user-attachments/assets/7e946ae5-f79c-4d3c-882d-6d01e5d84d39)

</details>
