### ISSUE TITLE
Don't refresh access token on wp_login action

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#903]
## Feature Description

We currently have a callback which runs `Authentication->refresh_auth_token_on_login()` method. This should not be necessary as the token should always be refreshed when needed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Remove `wp_login` callback in the `Authentication` class.
* Ensure that access token still gets refreshed once it expires (1 hour after obtaining it).
    * for proxy usage
    * for local sites without proxy

## Implementation Brief

* Remove `Authentication::refresh_auth_token_on_login` and unhook in `Authentication::register`

## Changelog entry

* Remove unnecessary logic to refresh an access token on login, since the Google API client already accounts for that.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Ensured setup via the proxy functioned properly.

Ran a series of tests around leaving online and local sites idle during setup (login), not during setup, refreshing after an hour to ensure access tokens still functioned.

Passed QA ✅
