### ISSUE TITLE
Enhance `no-direct-date` ESLint rule

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9032]
## Feature Description

In #8483 we introduced a new ESLint rule to avoid the use of `Date` directly, to encourage developers to use the reference date where relevant, but also to use our various date utility functions avoid introducing unexpected behavior related to the quirks of using `Date` directly.

In the initial implementation, the rule was made specific to a new `Date` with no arguments, however this misses instances which could be created using our date string format `YYYY-MM-DD` which will be misinterpreted based on the current timezone.

eg.
<img width="545" alt="image" src="https://github.com/user-attachments/assets/302c17b4-0ef4-418a-b9c2-3ce49b041c60">

 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `no-direct-date` rule should be updated to flag all uses of `new Date` with less than 3 arguments (or if problematic, any number of arguments)
* Existing flagged usage of `new Date( arg [, arg1...] )` (i.e. 1 or more args) should be audited and either:
    * Ignored with a comment explaining why they are not using the reference date or SK date utility
	* Updated to use the reference date or relevant date utility where appropriate
	* The report message should also be updated to suggest the use of our date utility functions (not only the reference date)
* The [`ignoreFiles` configuration in the eslint plugin](https://github.com/google/site-kit-wp/blob/293a2938a984323e4c98de81dcf17f7876086480/packages/eslint-plugin/configs/main.js#L32-L39) config for the rule should be moved to the `.eslintrc.json`

## Implementation Brief

* [x] Update `packages/eslint-plugin/rules/no-direct-date.js`:
   * [x] To catch `new Date( arg [, arg1...] )`, update `NewExpression` callback to report a rule violation if the `node.callee` is `Date` and the `node.arguments.length` is `> 0` and `< 3`.
   * [x] To catch `Date( arg [, arg1...] )`, update `CallExpression` callback to report a rule violation if the `node.callee` is `Date` and the `node.arguments.length` is `> 0` and `< 3`.
* [x] Move the [`ignoreFiles` configuration in the eslint plugin](https://github.com/google/site-kit-wp/blob/293a2938a984323e4c98de81dcf17f7876086480/packages/eslint-plugin/configs/main.js#L32-L39) to the `overrides` block of the `.eslintrc.json` file. 

 * [x] Update all new lint errors to use the plugin reference date or ingnore the rule.

### Test Coverage

* [x] Update `packages/eslint-plugin/rules/no-direct-date.test.js`, adding invalid usages of `new Date( arg [, arg1...] )` and `Date( arg [, arg1...] )`  with one or two args and a valid case with three or more arguments.

## QA Brief

* No QA necessary.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
No QA needed here; sending to Approval 👍
