### ISSUE TITLE
Add Google Authenticator Support

### ISSUE THREAD

**Issue by LGACode** [google/site-kit-wp#904]
## Feature Description

Please add Google Authenticator support so I don't have to use plugins such as miniOrange Google Authenticator. This would help consolidate and re-enforce a relationship between my G Suite services and my self-hosted WordPress site.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
There are [ongoing efforts](https://wordpress.org/plugins/two-factor/) to bring 2FA directly to  WordPress core, without the need for any additional plugin. These efforts will allow anyone to use 2FA irregardless of method - be it Google Authenticator, a text message, or a hardware key.
