### ISSUE TITLE
Allow for incremental style changes with ESLint

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9043]
## Feature Description

Sometimes we want to introduce a new stylistic rule but applying it all at once (especially if automatic fixes aren't supported) can be a large effort that may not be particularly necessary at the time. In this case, it would be useful to have a way to allow for certain changes to only be enforced when making changes to allow for incremental enhancement, after which, at some point, can be merged into the main config/ruleset that is enforced all the time.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update ESLint to allow for a certain set of rules/configuration to be additionally included/applied when checking changes during pre-commit checks

## Implementation Brief

* [ ] Add `.eslintrc.staged.json` to the directory root
  *  It should extend `./.eslintrc.json` (`"extends": [ "./.eslintrc.json" ],`)
  * Leave `rules` as an empty array for now 
* [ ]  Update `package.json`
  * Under `lint-staged`, for all JS files (`*.js`), update the `eslint` command to use the `.eslintrc.staged.json` config (`eslint --config .eslintrc.staged.json`)

### Test Coverage

*  No tests update needed

## QA Brief

* Nothing really to QA here; the Code Reviewer can test the linting with an added rule that fails when committing with husky.

This issue can realistically be moved directly to Approval after CR.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
> * For `plugins`, include a path to the new folder in the directory root `staged-eslint-rules` (`"plugins": ["./staged-eslint-rules"]`)

> Add `./staged-eslint-rules`
> * Replicate sub directory structure we have in `packages/eslint-plugin`
> * `rules` and `config` will return empty object and an empty `rules` object for now
>   
>   * the `config/main.js` file will return empty `rules` object. In the future if we need to add a custom rule it can be referenced as `'staged-eslint-rules/rule-name': [ 'error' ],` for example

@zutigrm why do we need this? I am not sure we do need it. Let's remove it. Creating the new staged config is sufficient itself.

**Comment by zutigrm** [comment]
@eugene-manuilov In case we want to add custom rules, like we do for the main, so I though could be usefull to prepare the structure. But I guess we can do that when/if need arrises as well. IB updated

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. IB ✔️

**Comment by eugene-manuilov** [comment]
Moving to Approval.
