### ISSUE TITLE
Acronym case rules should not flag `GA4AdSenseLinkedNotification`

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9048]
## Bug Description

The component wrapped by the `whenInViewContext` HOC at https://github.com/google/site-kit-wp/blob/c92f822d765eb09952b1b497b6b11220f028d847/assets/js/components/notifications/GA4AdSenseLinkedNotification.js#L221 should not trigger an ESLint error for `sitekit/acronym-case`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `// eslint-disable-next-line sitekit/acronym-case` at https://github.com/google/site-kit-wp/blob/c92f822d765eb09952b1b497b6b11220f028d847/assets/js/components/notifications/GA4AdSenseLinkedNotification.js#L221 should be removed without an error.
* It's possible that ESLint rules should allow _any_ variables whose first letter is a capital letter to skip rule checks, if needed. But if the variables can be checked for type by AST/ESLint and it only be applied to functions, that would be better 😄 

## Implementation Brief

* [ ] Update `packages/eslint-plugin/rules/acronym-case.js`
  * Somewhere under https://github.com/google/site-kit-wp/blob/3cce2fa8ddf862ae58adf177380f66258316d0dc/packages/eslint-plugin/rules/acronym-case.js#L72 check for `node.parent.type === 'CallExpression'`  and return early if it is true.
  * This will skip the check on functions, while it will continue checking agains variables for acronym name violations 
* [ ] Remove the disabled rule https://github.com/google/site-kit-wp/blob/c92f822d765eb09952b1b497b6b11220f028d847/assets/js/components/notifications/GA4AdSenseLinkedNotification.js#L221
  * Verify linter is not throwing name violation when comment is removed 

### Test Coverage

* No updates needed

### QA:Eng

* The `GA4AdSenseLinkedNotification` code linked in the definition of the issue is not longer present. Add a function which calls a the component to verify the `acronym-case` lint rule is no longer applied to a function call argument.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
> * check for `node.parent.type === 'CallExpression'`  and return early if it is true.
> * This will skip the check on functions, while it will continue checking agains variables for acronym name violations

@zutigrm, actually, i am not sure that this is going to work for what we want. If I understand this correctly, then it will skip the check for a variable when it is passed to a function, right? So if we have `foo( bar )` then that rule will ignore `bar` check because its parent node is a call expression, isn't it? I think the goal here is to detect the type of the `bar` variable and skip checking it if we know that it is a function name.

**Comment by zutigrm** [comment]
@eugene-manuilov Correct, it will skip the `bar` check. I have been digging again but, `Identifier` node only provides the context in which it is called, when `foo(bar)` is encountered, all we can know is that `bar` is passed in the function, but there is no data to identify the `Identifier` type itself, whether it is a function or a variable. We can make this distinction only during the assignment, at the point of their declaration.

Doesn't seem feasible to skip the check based on the type of `bar`, we can only skip the whole check for functions. Technically, the error will be surfaced on the declaration entry point, let's say someone does `const Bar = 'something', and then passes it to the function somewhere, `foo( Bar )`, by skipping this check, this will not be flagged, but the file/line where `const Bar` is assigned will be flagged. And it will be changed to `const bar`, which means that variable also has to be changed anyway in the `foo( Bar )` call, even if forgot eslint will raise a different warning about undeclared variable. So it would be impossible to have that kind of acronym flying under the radar, but it will allow us to omit skipping the acronym rule in legit places like the one covered by the issue, where we pass component to the HOC.

What do you think?

**Comment by eugene-manuilov** [comment]
Fair point. I tend to agree with you. Let's go for it then. IB ✔️

**Comment by ankitrox** [comment]
PR has been approved ✅ 

Over to merge reviewer.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@ankitrox  confirmed that during CR this ticket was tested so I have moved this to approval.
