### ISSUE TITLE
Don't show the Audiences Widget Area when it's turned off in Settings

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9065]
## Feature Description

Ensure the Audiences Widget Area on the dashboard is hidden when the "Display visitor groups in dashboard" switch is toggled off in the Settings section.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the "Display visitor groups in dashboard" switch is toggled off in the Settings section, the Audiences Widget Area should not be present on the dashboard.

## Implementation Brief

- [x] During the widget area registration [here](https://github.com/google/site-kit-wp/blob/2dbb7103df5f467594ca399156b6764a873b8f26/assets/js/googlesitekit/widgets/register-defaults.js#L148-L162), pass the `filterActiveWidgets` function as the property `settings` property to `registerWidgetArea` function. It accepts two arguments `select` and  `areaWidgets`
  * In `filterActiveWidgets` function check if audience segmentation widget is hidden using 

  ```js
  select( CORE_USER ).isAudienceSegmentationWidgetHidden();
  ```
  * If it is hidden, return an empty array from function else `areaWidgets`.

### Test coverage

No additional test required.

## QA Brief

1. Enable the Audience Segmentation feature. Make sure audience tiles are visible in dashboard, if not enable it through CTA banner using `Enable Groups` CTA.
2. Go to `Site Kit > Settings`, turn off `Display visitor groups in dashboard` toggle.
3. Make sure that audiences widget area is not available so that following widgets won't be visible.

  * Audience tiles
  * No audience banner
  * Google analytics connect CTA
  * Info notice widget

4. Re-enable the toggle and widget area should show the relevant widgets mentioned above (as per their fulfilment conditions).

## Changelog entry

* Don't show the Audiences Widget Area on the dashboard when the "Display visitor groups in dashboard" switch is toggled off in the Settings section.

**Comment by eugene-manuilov** [comment]
IB :heavy

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

This is working well overall.
There is one observation here: ⚠️ 

- The Google connect CTA isn't currently governed by the toggle but by the Analytics.
- If analytics is disconnected, the **Display visitor groups in dashboard** toggle isn't present anymore.
  <Details>
  
   https://github.com/user-attachments/assets/f56fd871-5111-41a2-9ae1-edf3b327539f

  </Details>

I personally think we should update the logic such that even if analytics is disconnected, the **Display visitor groups in dashboard** toggle should still appear.

________________________________________________________
Apart from that, it's all working well:

- Info notice widget and audience tiles are hiding and showing correctly.  ✅
   <Details>
   
   https://github.com/user-attachments/assets/5249e126-52ff-4f52-afe6-97a93c50c39b


   </Details>

- No audience banner hides accordingly. ✅ 
   <Details>

   https://github.com/user-attachments/assets/c7a703ab-5ee5-446e-a2bd-e213214f642f

   </Details>

**Comment by techanvil** [comment]
Thanks @kelvinballoo, that's a good point. Initially, the audience settings were part of the Analytics module so we needed Analytics to be active in order to show the switch, but now we've moved the settings out to the user scope, we can show the switch even when Analytics is not active.

It's out of scope for this issue though, so please can you create a new one for it?

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @techanvil .
New issue raised under : https://github.com/google/site-kit-wp/issues/9264

As for this ticket, it's good to be moved to approval as it's working well.

- Info notice widget and audience tiles are hiding and showing correctly.  ✅
   <Details>
   
   https://github.com/user-attachments/assets/5249e126-52ff-4f52-afe6-97a93c50c39b


   </Details>

- No audience banner hides accordingly. ✅ 
   <Details>

   https://github.com/user-attachments/assets/c7a703ab-5ee5-446e-a2bd-e213214f642f

   </Details>
