### ISSUE TITLE
Update the Audience Selection Panel Error Notice to use the new callout buttons

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9068]
## Feature Description

The "Retry" and "Request access" links in the Audience Selection Panel Error Notice should be updated to use the new callout button styling.

Specifically, these links:
![image](https://github.com/user-attachments/assets/39c7d397-41e4-43eb-a339-b93a585d0e65)

![image](https://github.com/user-attachments/assets/45a4c819-5602-440a-b6a5-ab69dfb14220)

Should be updated to be error callout buttons:
![image](https://github.com/user-attachments/assets/03d4da14-7feb-4b1a-ab0f-9d901873bdea)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Retry" and "Request access" links in the Audience Selection Panel Error Notice should be updated to use the new callout button styling.
* See Figma:
  * [Callout button style]https://www.figma.com/design/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?node-id=3514-6155&t=UHJETR35G84eS1hv-0).
  * [Error Notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1705-15994&t=nXANVJ2VbFnPIi4r-0).

## Implementation Brief

In `assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-audience-selection-panel.scss`:

* [ ] Update the `.googlesitekit-audience-selection-panel__error-notice-actions.googlesitekit-cta-link` class to apply the new callout button styling as defined in the [Figma design](https://www.figma.com/design/ZL8qlbUyR9lmBaF95t0xpq/sitekit-system-gm2%2B?node-id=3514-6155&t=UHJETR35G84eS1hv-0).
* [ ] Adjust the following properties to match the callout button style:
     * [ ] **Spacing**: Ensure the link button have consistent margins and paddings to align with the Figma design.
     * [ ] **Padding**: Update the padding to match the design’s spacing requirements.
     * [ ] **Border-radius**: Apply the appropriate rounding to ensure the link button have the correct corner shape.
* [ ] Apply the hover, focus, and active states to the callout button.
* [ ] Use the `.googlesitekit-audience-selection-panel__success-notice-actions.googlesitekit-cta-link` class as a reference for implementing these states:
https://github.com/google/site-kit-wp/blob/face615c12ec6e0d91729d721f996f37c92e211c/assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-audience-selection-panel.scss#L234-L259

### Test Coverage

* No new tests are required for this change.
* Fix any failing VRT tests.

## QA Brief

* Open the `Insufficient permissions error` and `Audience sync error` stories in `Modules > Analytics4 > Components > AudienceSegmentation > Dashboard > AudienceSelectionPanel`.
* Verify that the "Request access" and "Retry" buttons are styled according to the ACs.

## Changelog entry

* Update the Audience Selection Panel Error Notice buttons to use the new callout button styling.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified `Insufficient permissions error` and `Audience sync error` stories in Modules > Analytics4 > Components > AudienceSegmentation > Dashboard > AudienceSelectionPanel.
- Verified that the "Request access" and "Retry" buttons are styled according to the ACs. and Figma design.

<details>


![image](https://github.com/user-attachments/assets/3bb63a61-0151-46f7-8f59-44948057070b)

![image](https://github.com/user-attachments/assets/5fa00e53-48b5-48ab-b713-f77bb3f8e8a8)

![image](https://github.com/user-attachments/assets/268af778-3b8f-463d-be53-6112dff83a40)

![image](https://github.com/user-attachments/assets/d3701303-4455-45d7-bc31-f4c95f7790b7)

![image](https://github.com/user-attachments/assets/b7d62013-82dc-4784-b356-3f8b9f35a90d)

![image](https://github.com/user-attachments/assets/759b8059-d38e-42ba-b91d-857291081cb9)

![image](https://github.com/user-attachments/assets/9381fc45-f4ff-4c1a-9013-d36c553097b1)

![image](https://github.com/user-attachments/assets/36fd5574-3d38-4021-8eba-001c11a3c08a)

![image](https://github.com/user-attachments/assets/d3546aae-e865-4100-809e-b9030d72173c)

</details>
