### ISSUE TITLE
Fix conditions for showing the publication approved overlay notification

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9089]
## Feature Description

When the onboarding state for the current publication is synced, the publication approved overlay notification should appear, but only when the onboarding state has changed from another non-empty state.

At present the notification will appear even if the publication was already in the onboarding state prior to the sync. See https://github.com/google/site-kit-wp/pull/9017/files#r1693880442.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* While viewing the dashboard, when the onboarding state for the current publication is synced, the publication approved overlay notification should appear, but only when the onboarding state has changed from another non-empty state.

## Implementation Brief

- [ ] In `assets/js/modules/reader-revenue-manager/datastore/publications.js`, update following condition

https://github.com/google/site-kit-wp/blob/e72c21681f8edca2875b3b2e285c06ecdb8b87ba/assets/js/modules/reader-revenue-manager/datastore/publications.js#L131-L134

add following check along with existing one

```js
onboardingState !== currentOnboardingState
```

### Test coverage

* Add the test coverage for status transition change.

## QA Brief

* Set up Site Kit with a Google account that has one or more publications in the publisher center.
* Using the tester plugin, enable the `rrmModule` feature flag, and change the "_
Force Reader Revenue Manager publication onboarding state_" setting to something other than `ONBOARDING_COMPLETE`.
* Set up the RRM module.
* Go to the Site Kit dashboard and verify that the [publication approved overlay notification](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=192-3738&t=FD9l1FaVeUHtygjE-4) is not shown.
* Go to the tester plugin and change the RRM setting to `ONBOARDING_COMPLETE`.
* Go back to the dashboard and in the browser console, run the following script:
```js
googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).syncPublicationOnboardingState()
```
* Verify that after a few seconds, the publication approved overlay notification is displayed.
* Refresh the page and run the above script again. Verify that the overlay notification is no longer displayed.
* Besides the above, also perform a smoke test using the QAB for #8796 and #8797, as this includes a few improvements regarding those areas.

## Changelog entry

* N/A

**Comment by nfmohit** [comment]
The IB looks good to me, @ankitrox. Would you agree that it would be wise to increase the estimate to a `7` at least, considering there's test coverage involved?

**Comment by ankitrox** [comment]
Hi @nfmohit 

Thanks for flagging this. I had been conservative, but this exceeds the estimated time considering the fact that we may have to adjust test cases and may encounter some unforeseen scenarios.

I have updated estimate to 7 as it sounds correct.

Thanks again.

**Comment by nfmohit** [comment]
Thank you @ankitrox !

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Onboarding state setting to something other than ONBOARDING_COMPLETE.
- The [publication approved overlay notification](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=192-3738&t=FD9l1FaVeUHtygjE-4) is not shown.

Onboarding state setting to ONBOARDING_COMPLETE.
- After a few seconds, the publication approved overlay notification is displayed.

Refreshing the page and running the above script again. 
- The overlay notification is no longer displayed.

Besides the above, I also performed a smoke test using the QAB for https://github.com/google/site-kit-wp/issues/8796 and https://github.com/google/site-kit-wp/issues/8797.  I will be creating a more thorough smoke test of the entire RRM functionality as approaching the completion of the bug bash instructions. 

![image](https://github.com/user-attachments/assets/0ff4ba04-c5c8-422f-8f7b-da993190f9c4)
