### ISSUE TITLE
Google Analytics Opt Out

### ISSUE THREAD

**Issue by valentinwinkelmann** [google/site-kit-wp#909]
Is there a way using a hook or any other method to prevent the google site kit from loading the analytics scripts? i would like to link the whole thing to my cookie approval function so that it complies with the GDPR

**Comment by michaelbourne** [comment]
Try https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L176

**Comment by valentinwinkelmann** [comment]
> Try https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L176

Thank you very much. Elegant and simple solution to avoid tracking. Works great. 🍪👍
`function sitekit_optout(){
  if(is_plugin_active('google-site-kit/google-site-kit.php') == true){
    if(GetCookie('allow_cookies') == 'true'){
      return false;
    } else {
      return true;
    }
    echo is_tracking_disabled();

  } else {
    return true;
  }
}
add_action('googlesitekit_analytics_tracking_disabled', 'sitekit_optout');
`

**Comment by michaelbourne** [comment]
That action won't fire if the plugin isn't active, so the check is likely not needed. Depending on your use case, it might even make more sense to abstract a custom function for the tracking permission, since the solution used for permission might change over the years and this way you only edit a single function and not multiple references.

```
/**
 * Helper function to determine if user has allowed tracking. 
 * Use this function anywhere a customization is needed for tracking pixel output.
 *
 * @return bool
 */
function prefix_is_tracking_allowed() {
  if ( isset( $_COOKIE['allow_cookies'] ) && 'true' == $_COOKIE['allow_cookies'] ) {
    return true;
  } else {
    return false;
  }
}

/**
 * Filters whether or not the Analytics tracking snippet is output for the current request.
 *
 * @param $disabled bool Whether to disable tracking or not (default value)
 *
 * @return $disabled bool Whether to disable tracking or not.
 */
function prefix_sitekit_optout( $disabled ) {
  // Return default $disabled if we're not explicitly blocking tracking.
  $disabled = ( ! prefix_is_tracking_allowed() ) ? true : $disabled; 
  return $disabled;
}
add_action('googlesitekit_analytics_tracking_disabled', 'prefix_sitekit_optout', 10, 1);
```

**Comment by valentinwinkelmann** [comment]
Thank you very much for your detailed help. it works even better.
