### ISSUE TITLE
React Dashboard error after update 1.132.0

### ISSUE THREAD

**Issue by Towerss** [google/site-kit-wp#9094]
## Bug Description

After updating to version 1.132.0 the dashboard is broken.

## Steps to reproduce

1. Go to WordPress Admin Dashboard
2. Do to Site Kit > Dashboard
3. The dashboard does not show. There is an error message instead.

Error:

`Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=KeyMetricsNewBadge for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in KeyMetricsNewBadge
    in h3
    in div
    in Cell
    in div
    in Row
    in div
    in Grid
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root`

## Screenshots

![image](https://github.com/user-attachments/assets/e7c182e5-1e76-4849-bd9a-34c76cb2a7ca)

## Additional Context

<details><summary>Site Info</summary>
### wp-core ###

version: 6.6.1
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-server ###

server_architecture: Linux 6.5.0-1016-aws x86_64
httpd_software: Apache/2.4.52 (Ubuntu)
php_version: 8.3.4 64bit

### google-site-kit ###

version: 1.132.0
php_version: 8.3.4
wp_version: 6.6.1
reference_url: https://mlashesbrisbane.com.au
amp_mode: no
site_status: connected-site
user_status: authenticated
verification_status: verified-non-site-kit
connected_user_count: 1
active_modules: site-verification, search-console, analytics-4, pagespeed-insights
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_update_plugins: ✅
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ✅
	googlesitekit_view_wp_dashboard_widget: ✅
	googlesitekit_view_admin_bar_menu: ✅
	googlesitekit_view_shared_dashboard: ⭕
	googlesitekit_read_shared_module_data::["search-console"]: ⭕
	googlesitekit_read_shared_module_data::["analytics-4"]: ⭕
	googlesitekit_read_shared_module_data::["pagespeed-insights"]: ⭕
	googlesitekit_manage_module_sharing_options::["search-console"]: ✅
	googlesitekit_manage_module_sharing_options::["analytics-4"]: ✅
	googlesitekit_manage_module_sharing_options::["pagespeed-insights"]: ✅
	googlesitekit_delegate_module_sharing_management::["search-console"]: ✅
	googlesitekit_delegate_module_sharing_management::["analytics-4"]: ✅
	googlesitekit_delegate_module_sharing_management::["pagespeed-insights"]: ⭕
enabled_features: 
	adsPax: ⭕
	audienceSegmentation: ⭕
	consentModeSwitzerland: ⭕
	conversionInfra: ✅
	gm3Components: ⭕
	privacySandboxModule: ⭕
	rrmModule: ⭕
active_conversion_event_providers: 
	contact-form-7: contact
consent_mode: disabled
consent_api: not-detected
search-console_shared_roles: none
search-console_management: owner
analytics-4_shared_roles: none
analytics-4_management: owner
pagespeed-insights_shared_roles: none
pagespeed-insights_management: all_admins
search_console_property: sc-domain:mlashesbrisbane.com.au
analytics_4_account_id: 2895•••••
analytics_4_property_id: 4117252••
analytics_4_web_data_stream_id: 6285••••••
analytics_4_measurement_id: G-LD••••••••
analytics_4_use_snippet: no
analytics_4_ads_conversion_id: none
analytics_4_available_custom_dimensions: none
analytics_4_ads_linked: false
analytics_4_ads_linked_last_synced_at: 1722286994
</details> 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The conditional rendering/return of the `KeyMetricsNewBadge` component should be guarded so as not return/render _nothing_ in any condition, which currently causes the Site Kit dashboard to crash in certain. 
    * The Site Kit dashboard should not error/crash as a result of any `KeyMetricsNewBadge` component-specific errors

## Implementation Brief

* [ ] Update `assets/js/components/KeyMetrics/KeyMetricsNewBadge.js` component so it does not return `undefined` when the value of `isKeyMetricsSetupNew` selector is `undefined`.
* [ ] This can be achieved by explicitly returning `null` from the component when `isNew` is not `true`, i.e

```
	if ( isNew ) {
		return (
			<Badge
				className="googlesitekit-new-badge"
				label={ __( 'New', 'google-site-kit' ) }
			/>
		);
	}

	return null;
```

### Test Coverage

* No new tests needed.

## QA Brief

* Visit the Site Kit dashboard with Key Metrics set up.
* Enable various Key Metrics widgets and ensure Site Kit dashboard does not error.

## Changelog entry

* Fix the react dashboard error caused by the New badge component for key metric widgets.

**Comment by tofumatt** [comment]
ACs 👍🏻 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev and main environment.
- Verified key metrics setup and functionality on dev environment.
- Set up key metrics on latest environment and switch to dev environment.
- Not found any console or fatal error.
- Key metrics functionality working as expected.

<details>

_Key metrics module set up on latest and updated to dev and main environment._


https://github.com/user-attachments/assets/ad9a10bf-187f-4d9b-b817-3841f45bf2d7

_Key metrics setup and functionality test on dev environment._

https://github.com/user-attachments/assets/02f48b66-318f-4f48-b3c7-e819ce1033e0

</details>
