### ISSUE TITLE
Add "temporarily hidden" badge to hidden audiences in the Selection Panel

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9096]
## Feature Description

When an Audience Tile has been temporarily hidden, we should show a badge to clarify its status in the Selection Panel.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When an Audience Tile has been temporarily hidden (see https://github.com/google/site-kit-wp/issues/8143):
  * The audience should display a "Temporarily hidden" badge in the Selection Panel.
    * The badge should follow the [Figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=5821-17430&t=zBDcj8GGE0FJ5Li3-0).
    * Clicking/hovering the badge's info icon should display a tooltip, which should follow the [Figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=5834-18083&t=zBDcj8GGE0FJ5Li3-0) with the following copy:
      * _Site Kit is collecting data for this group. Once data is available the group will be added to your dashboard._
  * An audience should only display one badge in the Selection Panel; if the audience is eligible to display a "New" badge (see https://github.com/google/site-kit-wp/issues/8170), the "Temporarily hidden" badge should take precedence and the "New" badge should not be displayed.

## Implementation Brief

- [x] Create a component `BadgeWithTooltip` in `assets/js/components`.
  * Accept `label` and `tooltipTitle` as props. Both should be of type `string`.
  * It should also use `className` props to add additional class names to the component wrapper. Use `googlesitekit-badge-with-tooltip` class as a generic one.
  * Return a span element from the component which should output `label` and for `tooltipTitle` use `InfoTooltip` component with title prop set to `tooltipTitle`. Refer `PartialDataBadge` [component](https://github.com/google/site-kit-wp/blob/5a8c46be665ea3be63a0564fe5f9ccca90e39f8c/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/PartialDataBadge.js#L34-L41) which does the same.
  * Update all instances of `PartialDataBadge` usage which should use `BadgeWithTooltip` component.
    * Pass `label` prop as `Partial data`.
    * `tooltipTitle` should already be there, so use same one.
    * Pass `className` as `googlesitekit-audience-segmentation-partial-data-badge` to retain the existing styles.
    * Remove `PartialDataBadge` component from codebase as it is no longer needed.
- [x] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceItem.js`
    * Use `isItemDismissed` selector, pass `audience-tile-${slug}` to the selector. Collect result in `temporarilyHidden`constant.
    * Pass `BadgeWithTooltip` component as a `badge` prop to `SelectionPanelItem` component (refer #8170) when `temporarilyHidden` is `true`.  
      * Pass `label` as "Temporarily hidden" to `BadgeWithTooltip`.
      * Pass `tooltipTitle` as  
      _Site Kit is collecting data for this group. Once data is available the group will be added to your dashboard._  
      * Pass `className` as `googlesitekit-audience-segmentation-temporary-hidden-badge`

### Test coverage

* Update tests which may get failed due to update in `PartialDataBadge` component.

* Add tests for temporarily hidden badge check by setting the audience tile to be dismissed and zero data.

## QA Brief

1. Enable audience segmentation feature and enable the visitor groups. Add the non Site Kit created audience to audience tile like "All visitors".

2. In the tester plugin, set `Analytics > 
Force Analytics report data` to `Zero`. Also, set `Analytics Partial Data > 
Force Analytics audience partial data state` to `last-28-days`. Save changes.

3. Go to Site Kit dashboard and to audience tile section. You will see the tile in collecting data status with the link to hide the tile temporarily ( "Temporarily hide" ).

4. Click on the "Temporarily hide" link for "All Visitors", that will hide the tile. 

5. Open the audience selection panel. There should be a "Temporarily Hidden" badge with a tooltip.

6. Ensure it matches the Figma Design and the text is according to AC.

## Changelog entry

* Add support for the "Temporary hidden" badge in the audience selection panel.

**Comment by eugene-manuilov** [comment]
> Create a new component `assets/js/modules/analytics-4/components/audience-segmentation/TemporaryHiddenBadge.js`.

@ankitrox why do we need it? Your IB says that we need to create it but nothing where we should use it. If we don't need to use it, then we shouldn't add it.

> In `assets/js/components/SelectionPanel/SelectionPanelItem.js` ... Render a `BadgeWithTooltip` component in the widget header if ... The audience is hidden.

The `SelectionPanelItem` component should know nothing about audiences.

PS: also not need to use the checkbox for each sub item in your IB, use it for top level groups of action items, for sub items that are part of those groups just use ordered/unordered list, for example:

* [ ] Foo
  * sub item 1
  * sub item 2
* [ ] Bar
  * [ ] Sub bar 1
    * sub item 1
    * sub item 2
  * [ ] Sub bar 1
    * sub item 1
    * sub item 2

**Comment by ankitrox** [comment]
Thank you for reviewing the IB @eugene-manuilov and highlighting the issues. I've updated the IB according to the mentioned points.

Also, I agree with your point that `SelectionPanelItem` should not be concerned about anything related to `audience` as it is a generic component, but as I took the reference of #8170 for this one, I found that this is also doing the same, which we can update IMO.

Maybe, @techanvil can comment about #8170. 
Thanks

**Comment by techanvil** [comment]
Thanks @eugene-manuilov and @ankitrox. That's a great point that `SelectionPanelItem` shouldn't know about audiences, and a detail I missed when reviewing the IB for #8170.

I have therefore tweaked the IB for #8170 to avoid this. As part of the amendment I've specified adding a `badge` prop to `SelectionPanelItem` which can be referenced in the IB for this issue.

**Comment by eugene-manuilov** [comment]
@ankitrox could you please fix the structure of your IB because right now it feels like changes in `AudienceItem` are a subtask of `PartialDataBadge`?

> Refer `PartialDataBadge` component. A common component can be extracted out of it as `BadgeWithTooltip` which should accept `label` and `tooltipTitle` as props.

We need to be concrete what exactly needs to be done, if this is something that not really necessary, then no need to include it in IB.

> A common component can be extracted out of it as `BadgeWithTooltip` which should accept `label` and `tooltipTitle` as props.

Why not to change the existing one to accept label and class name?

**Comment by nfmohit** [comment]
Hi @techanvil. Question about the tooltip copy in the ACs:

> Site Kit is collecting data for this group. once data is available the this group will be added to your dashboard.

I believe the text is grammatically incorrect. I think the correct version would be:

> Site Kit is collecting data for this group. Once data is available this group will be added to your dashboard.

Would you agree?

**Comment by techanvil** [comment]
Hi @nfmohit, thanks for spotting that! I didn't notice it when I copied the text from Figma. I've fixed the text in the AC, and also asked Sigal to fix it over in Figma.

**Comment by ankitrox** [comment]
Thank you @nfmohit and @techanvil 

I've updated the tooltip text and pushed the changes.

**Comment by nfmohit** [comment]
Hi @techanvil. The text still has a "the this", which I think is incorrect. Could you recheck?

**Comment by techanvil** [comment]
Apologies @nfmohit, I missed that part! I've amended accordingly. Thanks for the :eagle: :eyes:!

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

There is only one thing to flag related to the AC which states:
`Clicking/hovering the badge's info icon should display a tooltip, which should follow the [Figma design] etc...`
- Focusing on 'Clicking', currently when we click the badge's info icon, it does bring up the tool tip but also selects or deselects the corresponding checkbox. Is that expected? ⚠️ 
   <Details>

   https://github.com/user-attachments/assets/c6bbd601-9c62-4d60-8347-fbd57dbe523b

   </Details>

Other than that, it's working as expected: ✅ 
- When an Audience Tile has been temporarily hidden, the audience displays a "Temporarily hidden" badge in the Selection Panel and the badge follows figma.
   <Details>
   

   https://github.com/user-attachments/assets/b355b2b2-f34a-4cc5-a55a-dc740f81d7ff


   </Details>

- Clicking/hovering the badge's info icon should display a tooltip which follows Figma with the copy:
   "Site Kit is collecting data for this group. Once data is available the group will be added to your dashboard."
   <Details>
   
   <img width="1188" alt="Screenshot 2024-09-26 at 14 38 04" src="https://github.com/user-attachments/assets/455b9250-8f80-4c88-b5a4-ed055cb6195f">

   </Details>
   
- An audience only displays one badge in the Selection Panel; if the audience is eligible to display a "New" badge, the "Temporarily hidden" badge takes precedence and the "New" badge is not be displayed.
   <Details>
   
   https://github.com/user-attachments/assets/b2c3242e-a62c-463a-899f-e9b52282a011

   </Details>

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

New issue raised for the UX on clicking the badge here: https://github.com/google/site-kit-wp/issues/9421
Also added a mobile UX issue in the ticket.

Since the main use-case is working as expected for this ticket, we are moving this to approval ✅ 
- When an Audience Tile has been temporarily hidden, the audience displays a "Temporarily hidden" badge in the Selection Panel and the badge follows figma.
   <Details>
   

   https://github.com/user-attachments/assets/b355b2b2-f34a-4cc5-a55a-dc740f81d7ff


   </Details>

- Clicking/hovering the badge's info icon should display a tooltip which follows Figma with the copy:
   "Site Kit is collecting data for this group. Once data is available the group will be added to your dashboard."
   <Details>
   
   <img width="1188" alt="Screenshot 2024-09-26 at 14 38 04" src="https://github.com/user-attachments/assets/455b9250-8f80-4c88-b5a4-ed055cb6195f">

   </Details>
   
- An audience only displays one badge in the Selection Panel; if the audience is eligible to display a "New" badge, the "Temporarily hidden" badge takes precedence and the "New" badge is not be displayed.
   <Details>
   
   https://github.com/user-attachments/assets/b2c3242e-a62c-463a-899f-e9b52282a011

   </Details>
