### ISSUE TITLE
AdSense set-up for some existing AdSense users does not give code toggle

### ISSUE THREAD

**Issue by OisinOConnor** [google/site-kit-wp#91]
## Bug Description
When connecting Site Kit to an existing AdSense account, the plugin does not always ask users if they would like to code placed on their account. 

## Steps to reproduce
Set up AdSense on Site Kit with an existing account without any Adsense code on the site already.

## Expected behavior
A screen with a toggle that gives user the option to add AdSense code to the site.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by ivankristianto** [comment]
@OisinOConnor 
I cannot reproduce this issue on my end.
When I try to setup AdSense module with this criteria:
1. I have the active AdSense account
2. I did add the Sites on AdSense account
3. My AdSense account already show ads and has revenue.

During AdSense setup flow i see the option:
![Screen Shot 2019-07-08 at 09 38 10](https://user-images.githubusercontent.com/656006/60780164-85ccb680-a167-11e9-9da7-eeafca2a094c.png)

Can you please ensure you have reset site kit and have clean browser cache and try again, also we did release the version 1.0.0-beta.1.0.1 last week.
https://sitekit.withgoogle.com/service/download/google-site-kit.zip

If the issue still persist can you tell me from which AdSense internal test account should I try?

**Comment by bjackson27** [comment]
@ThierryA noting that we aren't able to reproduce this issue.

**Comment by ThierryA** [comment]
@OisinOConnor are you still getting this error with the latest version?

**Comment by OisinOConnor** [comment]
We can mark this as "could not reproduce" for now.
