### ISSUE TITLE
Hide additional groups after dismissing audience creation notice

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9109]
## Bug Description

This came up from https://github.com/google/site-kit-wp/issues/8164

When 'New visitors' and 'Returning visitors' are archived in Analytics, the audience creation notice would appear in the audience selection panel.
If I dismiss the audience creation notice, the 'All Visitors' audience is there and we will have the text 'Additional groups' below it but it's essentially blank. 

Since there are no audiences there, it's best to hide the text 'Additional groups'
  

## Steps to reproduce

1. Setup a site with GA, enable the feature flag and enable the Visitor Groups feature.
2. Go into the Audience settings in GA and archive the Site Kit created audiences, if these have been created automatically (New visitors and Returning Visitors).
3. Sync the available audiences by running the following command in the browser console:
   `googlesitekit.data.dispatch( 'modules/analytics-4' ).syncAvailableAudiences()`
4. Refresh the SK dashboard and open the Audience Selection panel.
5. You should now see the Audience Creation Notice.
6. Dismiss the notice without creating the audiences.
7. You will see the additional groups but nothing under it

## Screenshots

<Details>
<img width="548" alt="Screenshot 2024-08-01 at 15 20 36" src="https://github.com/user-attachments/assets/b6b9ad03-1536-47b8-9d7d-d44eaa14c2c3">
</Details>

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a Selection Panel is opened and it has a saved selection, but no "available items" (i.e. items that are not in the saved selection), the available items title should not be displayed.
* In concrete terms this is only applicable to the Audience Selection Panel at present, so when following the steps to reproduce, the "Additional groups" title should not be visible at the end.

## Implementation Brief

* [x] Conditionally render the title paragraph when `availableUnsavedItems` is not empty:
https://github.com/google/site-kit-wp/blob/6d3de25afd9b8c02dfabb777ed4f6783471756d3/assets/js/components/SelectionPanel/SelectionPanelItems.js#L62-L64

* [x] Apply the same condition to the render of the related subsection:
https://github.com/google/site-kit-wp/blob/6d3de25afd9b8c02dfabb777ed4f6783471756d3/assets/js/components/SelectionPanel/SelectionPanelItems.js#L68-L70

### Test Coverage

* Add a story and VRT to `assets/js/components/SelectionPanel/index.stories.js` for a Selection Panel with a saved selection but no available items.

## QA Brief

1. As per the `Steps to reproduce` section in issue description, follow the same steps, but you should not be able to see `Additional groups` title if there are no audiences to display beneath it.

2. Also, refer to `SelectionPanel > With zero unsaved items` story.

## Changelog entry

* Ensure that a Selection Panel without any available items doesn't display the available items title.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that "additional groups" after dismissing audience creation notice is not appear now.
- Note : I observe that notice to add another group to dashboard is continuos display even if only 1 group exist. I will create a separate ticket for this.

<details>

https://github.com/user-attachments/assets/7a5809b1-9346-4382-98ce-019f0d8351d6

https://github.com/user-attachments/assets/379a23a4-2e11-42a4-9d6b-22ff2cacd51f

</details>
