### ISSUE TITLE
Fix googlesitekit-active-modules option name to use underscores

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#911]
## Bug Description

The option name `googlesitekit-active-modules` does not follow our option naming standard of using underscores (including the `googlesitekit_` prefix). Let's fix that.

This change should ensure that the old option gets migrated and then deleted. It should also simplify the `uninstall.php` file so that it doesn't need to specifically consider that option any longer.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The option previously called `googlesitekit-active-modules` should be called `googlesitekit_active_modules`.
* Setups that have the old option set should continue to work with that change (i.e. the same modules should be recognized as active).

## Implementation Brief

* Update references to option name to use `googlesitekit_active_modules`
    - `Modules::get_active_modules_option`
    - `Modules::set_active_modules_option`
* In `Modules::get_active_modules_option`, if `googlesitekit_active_modules` is not an array - fallback to returning the value of the legacy `googlesitekit-active-modules` option
* Don't delete the old value on-the-fly
    - It can stay for BC should the user rollback to an older version
    - It will be ignored as soon as the new option is set
    - It will be removed with everything else on reset/uninstall
* No changes to `uninstall.php`
    - Keep the special case for old option for now, we can remove it later

## QA Brief

* Set up Site Kit using the current release (1.1.3)
* Activate any module (does not require set up), e.g. Analytics
* The option `googlesitekit_active_modules` should not exist
    - You can see all options on `wp-admin/option.php` (not linked anywhere in menus) but serialized values such as this one will not be visible. You can verify the option is not present here though.
* Check the option `googlesitekit-active-modules` contains the activated module
    - Via wp-cli: `wp option get googlesitekit-active-modules` or via DB in the options table
* Upgrade Site Kit to the latest build from develop _without uninstalling_
    - Use this plugin https://wordpress.org/plugins/easy-theme-and-plugin-upgrades/
    - Or `wp plugin install --force url/or/path/to/new/plugin.zip`
* The `googlesitekit-active-modules` option should still exist
* Activate a new module (e.g. Tag Manager)
* The `googlesitekit_active_modules` should exist and contain both activated modules now
* Update Site Kit to the old version again (1.1.3) using the plugin or wp-cli as mentioned above
* Active modules should be the same as before the upgrade (`googlesitekit-active-modules` was preserved without changes)

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv The uninstall prefix should remain `googlesitekit_`, it was intentionally set up like that. I'm okay not removing `googlesitekit-active-modules` on the fly, but then we should keep the uninstall extra case around for a bit longer. That is fine with me.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
Followed the QA steps and everything looks good and behaved as expected.

QA ✅
