### ISSUE TITLE
PHP warning `Undefined array key "name"`

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#9113]
## Bug Description

A user has [reported](https://wordpress.org/support/topic/php-warnings-for-undefined-array-key-in-google-site-kit/) in the support forum of experiencing the following PHP warning on their site:

`: Undefined array key "name" in /wp-content/plugins/google-site-kit/includes/Core/Util/Sort.php on line 37`

While it doesn't have any impact on the user experience or functionality within Site Kit, this could be enhanced to be safer. 

Site health from the report highlighted above: https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjxx-aj7atcYiFfi0lcShwp_lcKDRT0BMTZjodWaPpOf_2zaRWIQXKhypNOZ71n1vM

## Steps to reproduce

- Connect SK
- Go to Settings
- Edit Search Console settings
- See response for `matched-sites` (or look in logs)

## Screenshots

<img width="1839" alt="image" src="https://github.com/user-attachments/assets/27ec2d40-4f5e-4795-843f-19c4fb9908ae">

## Additional Context

 - PHP Version: 8.1.29 64bit
 - OS: N/A
 - Browser: N/A
 - Plugin Version: 1.132.0
 - Device: N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Audit the use of `Sort::case_insensitive_list_sort` to ensure no notices are being raised/logged

## Implementation Brief

* [ ] Update the key here to use `siteURL` instead of `name` as "name" does not exist on the mapped array value https://github.com/google/site-kit-wp/blob/f1f4f9e9980f58e1a1a0a0f43b0effeb41b8211c/includes/Modules/Search_Console.php#L304-L307
* [ ] Merge https://github.com/google/site-kit-wp/pull/9266

### Test Coverage

* Add a simple test to cover this endpoint

## QA Brief

* Follow steps to reproduce above. Look in error logs to see the warning like so 
<img width="729" alt="image" src="https://github.com/user-attachments/assets/853e668c-38cd-4f70-99d1-ac66035c0237">

## Changelog entry

* Fix the undefined array key "name" warning.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- I created the same environment using site heath info.
- On latest environment under debug log I'm getting the PHP warning :  Undefined array key "name"
- Verified on main environment PHP warning :  Undefined array key "name" is not showing.

<details>

On latest environment

![image](https://github.com/user-attachments/assets/7c27797c-cbc5-448c-b130-b503c54c4839)

</details>
