### ISSUE TITLE
Remove use of non-existent `WithRegistrySetup.features` prop

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9115]
## Feature Description

A number of stories have been implemented which pass the `features` prop to the `WithRegistrySetup` component. However, the component doesn't have this prop and it's ignored.

The stories are working as expected because the `features` prop is provided via `parameters`.

For example:

https://github.com/google/site-kit-wp/blob/e112780ccddc087e03acf9fe1452120cdf3a045f/assets/js/modules/ads/components/settings/SettingsEdit.stories.js#L99-L123

Note how `WithRegistrySetup` doesn't have the `features` prop:

https://github.com/google/site-kit-wp/blob/e112780ccddc087e03acf9fe1452120cdf3a045f/tests/js/WithRegistrySetup.js#L35

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Stories using `WithRegistrySetup` should not attempt to pass the `features` prop to it.

## Implementation Brief

* [x] Update the following stories, removing the `features` prop from the use of `WithRegistrySetup`:
   * https://github.com/google/site-kit-wp/blob/798b43c2ba8711caadfe049e328588a0008e00a1/assets/js/components/conversion-tracking/ConversionTrackingToggle.stories.js#L62
   * https://github.com/google/site-kit-wp/blob/798b43c2ba8711caadfe049e328588a0008e00a1/assets/js/components/conversion-tracking/ConversionTrackingToggle.stories.js#L96
   * https://github.com/google/site-kit-wp/blob/798b43c2ba8711caadfe049e328588a0008e00a1/assets/js/modules/ads/components/settings/SettingsEdit.stories.js#L117
   * https://github.com/google/site-kit-wp/blob/798b43c2ba8711caadfe049e328588a0008e00a1/assets/js/modules/ads/components/settings/SettingsEdit.stories.js#L147
   * https://github.com/google/site-kit-wp/blob/798b43c2ba8711caadfe049e328588a0008e00a1/assets/js/modules/ads/components/settings/SettingsEdit.stories.js#L177
   * https://github.com/google/site-kit-wp/blob/798b43c2ba8711caadfe049e328588a0008e00a1/assets/js/modules/analytics-4/components/settings/SettingsForm.stories.js#L240
 * [x] Remove any unused imports caused by these changes.

### Test Coverage

* Confirm VRTs still pass and components which require feature flags still render in storybook. Feature flags should be passed on the main story definition.

## QA Brief

Refer the [storybook](https://google.github.io/site-kit-wp/storybook/develop) and ensure that following stories are rendering properly and as expected.

- [Analytics-4 SettingsEdit](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-settings-settingsedit--default)
- [Ads SettingsEdit](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-ads-settings-settingsedit--default)
- [ConversionTrackingToggle](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-conversion-tracking-conversiontrackingtoggle--enabled)

## Changelog entry

* Remove the use of the non-existent `features` prop in stories using the `WithRegistrySetup` component.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by ankitrox** [comment]
Thanks @hussain-t 

I have added links to those stories.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested below Stories -
- [Analytics-4 SettingsEdit](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-settings-settingsedit--default)
- [Ads SettingsEdit](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-ads-settings-settingsedit--default)
- [ConversionTrackingToggle](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-conversion-tracking-conversiontrackingtoggle--enabled)

 

- Verified that above stories are rendering properly and as expected.
