### ISSUE TITLE
`no-yield-dispatch` ESLint rule not working as expected

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9119]
## Bug Description

The `no-yield-dispatch` ESLint rule is allowing registry-dispatched actions to be returned from generator action functions.

It's only failing if a call to `registry.dispatch()` is returned directly; returning `registry.dispatch().someAction()` is not failing, as illustrated below in VSCode.

## Steps to reproduce

1. Return a registry-dispatched action from a generator.
2. See no lint failure.
3. Directly return the call to `registry.dispatch()`.
4. See the lint failure.

## Screenshots

_This is fine:_
![image](https://github.com/user-attachments/assets/7c9ca118-439b-4a85-8a6e-c4f54c4d98f1)

_This fails:_
![image](https://github.com/user-attachments/assets/6618acdb-3f62-40e9-ac14-d04fa2435a18)

![image](https://github.com/user-attachments/assets/3f22d55c-5ea9-4012-b5bd-5fe70d5d60ac)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `no-yield-dispatch` ESLint rule should throw an error when attempting to return the result of dispatching an action via the registry from a generator action.

## Implementation Brief

* [x] Update `packages/eslint-plugin/rules/no-yield-dispatch.js`
  * In this conditional check https://github.com/google/site-kit-wp/blob/9e6a6a480e24e25d9720edcab4caf82aba0fc413/packages/eslint-plugin/rules/no-yield-dispatch.js#L33 add OR `callee?.object?.callee?.name === 'dispatch'` 

### Test Coverage

* Update `packages/eslint-plugin/rules/no-yield-dispatch.test.js` in the `invalid` array include a function that yields dispatched action, for example `yield dispatch( CORE_MODULES ).activateModule( slug )`

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️
