### ISSUE TITLE
E2E failing to start environment

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9123]
## Bug Description

E2E workflows have started failing while attempting to start the environment.

## Screenshots

<img width="874" alt="image" src="https://github.com/user-attachments/assets/0c25e96c-d771-4440-b46d-250bbc9b0efe">
https://github.com/google/site-kit-wp/actions/runs/10187379394/job/28181278087

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* E2E GHA workflow runs should be restored to working order

## Implementation Brief

* The failure seems to be due to runner images no longer including `docker-compose` but instead using `docker compose` (V2). Follow https://docs.docker.com/compose/migrate/ to update our usage.
* Finish and merge #9122 

### Test Coverage

* No changes

## QA Brief

* No QA needed as this can be fully verified during CR

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
Thanks @aaemnnosttv ! This is now merged and the reported error in setting up the environment is fixed. No additional QA is needed here so moving this to Approval. 

Note that there's been a few E2E tests failing in `nightly` version of WordPress, I will keep an eye out for it and file any follow up issues if needed. This failure is unrelated to this ticket. 

:tada:
