### ISSUE TITLE
Make tracking opt-in user-specific

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#913]
## Feature Description

> Help us improve the Site Kit plugin by allowing tracking of anonymous usage stats. All data are treated in accordance with Google Privacy Policy.

Currently the opt-in for tracking anonymous usage stats is saved as an option which affects all users. This is likely undesirable for a few reasons:

1. It isn't clear that this is not a user-specific preference - any change by another user will silently apply to all other users, which can seem like the plugin isn't respecting their previous choice
1. Desire to volunteer this information will likely vary from user to user and there likely isn't a technical requirement why this needs to be the same for all users so we're more likely to have better participation with a per-user scope

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Every admin setting up the plugin should be able to choose whether they want to opt-in to anonymous tracking or not. 
* Preferences for each user should be stored separately and if they change their preference, that change should not affect other users' settings. 

## Implementation Brief

* Update the `Tracking` class to accept an optional `User_Options` instance.
* Update `Tracking::is_active` to use the `User_Options` instance instead of `get_option` directly
* Update `Tracking::register_settings` to use `register_meta` 
* Update the `<Optin>` component to handle the toggle to use the appropriate endpoint
    - See if we can use `/wp/v2/users/me` with the meta field to set
    - If core endpoint is not an option, create a dedicated `/google-site-kit/v1/core/user/data/tracking` REST route
* If necessary, update the endpoint in the `Activation` notice toggle  
_This should be unnecessary after #991_

### Migrate current option to user option

* Create a `Migration_n_e_x_t` class to run after the previous migration
* If tracking is currently **opted-out**, do nothing and finish migration
* If tracking is currently **opted-IN**
    * Query Users who have access tokens, limit 2
        - If only one, migrate the current setting (enable tracking)
* Delete `googlesitekit_tracking_optin` option in both cases

## Changelog entry

* Make opting in to tracking specific per user instead of per site.

**Comment by Tobias-Conrad** [comment]
I like it too.
I track customers and guests, some are logged in and some are not. 
Filter and deactivate tracking by user role would be great .

**Comment by aaemnnosttv** [comment]
@Tobias-Conrad I think you're referring to Analytics tracking connected to your own account. This issue is specific to the anonymous usage data sharing you're prompted for when setting up Site Kit 😄 

As for your comment, v1.1 changed the default behavior to no longer include logged in users in Analytics tracking (although this can be toggled via the module's settings if you wish). If you want more fine-grained control we offer a `googlesitekit_analytics_tracking_disabled` filter to customize the tracking behavior to your needs

**Comment by tofumatt** [comment]
What's the thinking here for migrations? We don't want to opt users in without them explicitly giving consent, but as mentioned we can't tell if a previous opt-in was meant for all users or just one.

Do we keep track of how many users have authorised Site Kit thus far on a site? I'd say that the AC here needs expanding and that we should migrate the opt-in from the "site-wide" setting to the "user" setting, but **only if there is only one authorised Site Kit user**. If there is more than one and we detect consent, I think it's only fair to opt all users out so no one is opted-in without consent.

**Comment by aaemnnosttv** [comment]
That's a good question @tofumatt. Unfortunately, this setting can currently be toggled by any admin at any time, whether Site Kit has been set up or not (since it is shown on the splash screen and after activation), so it isn't possible to reliably infer which user had granted it; even if there is only one authorized user. For this reason, I think the only safe thing to do here is to not migrate the setting to user preferences.

**Comment by tofumatt** [comment]
Yeah, sorry, that's what I meant—but if there's only one Site Kit user we could migrate the setting to that user's preference. It would save all the single-user sites who have opted-in from having to do so again.

**Comment by aaemnnosttv** [comment]
Yeah, I think at best we could migrate the preference only for single-admin installs.

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**
Confirmed multiple admins were able to adjust their anonymous tracking independently without affecting each other's settings.

![Site Kit by Google Settings ‹ googlekitlocal 10uplabs com — WordPress](https://user-images.githubusercontent.com/57115907/72874379-b9f06a80-3ca6-11ea-932e-c2f6c3f5b1ac.gif)

Passed QA ✅
