### ISSUE TITLE
Update Analytics_4 Module Inline Data to Include ACR Events Data

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9131]
## Feature Description

Issue #9130 relating to scheduled event data checks resulted in a new settings key being added to the exsiting GA4 settings entry within the options table. The value of this new setting entry needs to be exposed within the Google Analytics module inline data (as a new key) in order for various GA4 datastore components to digest and make use of this data. 

A suitable key name should be used to reference this data in the inline module data, i.e `recentEvents` or similar.

Inline module data is currently handled within the `register` method of the `Analytics_4` main module class, via the `googlesitekit_inline_modules_data` filter. Additional filters should be added as required to surface said new data as inline module data.

See the [relevant area of the design document](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.1roe9kf401qv) for more information.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics module class is updated to include `recentEvents` setting key value in the existing module inline data
  * It should be included under `analytics-4` key in the inline module data, and nested as `recentEvents` key.

## Implementation Brief

* [ ] Update `includes/Modules/Analytics_4.php`
  * In `register` method hook into the `googlesitekit_inline_modules_data` filter after `inline_tag_id_mismatch`, use priority `20`
  * Add callback method `inline_conversion_reporting_data`
    * Retrieve the `recentEvents` setting  and pass the value to the `$modules_data['analytics-4']['recentEvents']`

### Test Coverage

* Update `tests/phpunit/integration/Modules/Analytics_4Test.php` to include tests for the new method. You can check `test_inline_tag_id_mismatch` for an example

## QA Brief

* Setup Site Kit with Analytics 4 module (contact Aleksej for access to the GA4 property that has ACR data) and `conversionReporting` feature flag enabled
* Enter `_googlesitekitModulesData['analytics-4'].recentEvent` into the JS console. It should be an array that includes the values `'purchase'` and `'submit_lead_form'`, eg: `['purchase', 'submit_lead_form']`

## Changelog entry

* Include Analytics Conversion Report event data in preloaded JS data.

**Comment by 10upsimon** [comment]
✅ **AC** LGTM, thanks @zutigrm moving to IB

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
@tofumatt @zutigrm @10upsimon is this necessary? See https://github.com/google/site-kit-wp/issues/9132#issuecomment-2313436638
