### ISSUE TITLE
Creation of a New GA4 Datastore Partial for Detected ACR Events

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9132]
## Feature Description

As part of the ongoing Analytics Conversion Report work, notably issues #9130 and #9131, there is a need to surface said new ACR events data via a new Google Analytics 4 datastore partial. This new datastore will be responsible for resolving the new inline module data added to the GA4 module in #9131, and it will function similarly to how we handle retrieval of custom dimensions within the GA4 module, etc.

This datastore should contain the necessary resolver, action and and selectors in order to retrieve the detected ACR events within the users GA4 report data.

See the [relevant section of the design document](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.7e6inft5e4wy) for more detailed information.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* ~~The inline Analytics 4 data from `_googlesitekitModulesData` holding the available event names under `recentEvents` key is retrieved and stored in the `MODULES_ANALYTICS_4` datastore.~~
* New datastore partial should be created, with following:
  * ~~Selector for returning the `detectedEvents` value~~
  * ~~Resolver for retrieving the data if unavailable and updating the state through action~~
  * ~~Action which receives the data and passes it to the reducer~~
  * Selector which will check if the stored `detectedEvents` value has any of the event names passed as the parameter

See https://github.com/google/site-kit-wp/issues/9132#issuecomment-2313436638 regarding edits

## Implementation Brief

* [ ] Add `assets/js/modules/analytics-4/datastore/conversion-reporting.js`
  * [ ] include `recentEvents` to the initial state object
  *  [ ] Add `getConversionReportingEvents` resolver
     * Return early if analytics module is not connected or `_googlesitekitModulesData` is not set
     * Retrieve events from `_googlesitekitModulesData['analytics-4']['recentEvents']` and pass them to the `receiveConversionReportingEvents` action
  * [ ] Add  `getConversionReportingEvents` selector to return the `recentEvents` from the state
  * [ ] Add `receiveConversionReportingEvents` action
    * It should accept `events` prop and yield it to the reducer
  * [ ] Add `hasConversionReportingEvents`  selector
    * It should accept `events` prop
    * Retrieve stored events with `getConversionReportingEvents` selector and check for the presence of `events` within the returned array if not empty
    * It should return boolean value to represent if passed `events` are present or not

### Test Coverage

* Add test coverage for new datastore partial

## QA Brief

* No QA needed here as there are no new features/changes.

## Changelog entry

* Add support for Analytics Conversion Report Events in data store.

**Comment by eugene-manuilov** [comment]
> * Relevant selector/resolver should be created to obtain the stored values in new datastore partial

@zutigrm, let's define which selectors and actions should be created to make it clear. No need to put selector and action names there, but just explain what they should do. For example:

* A new selector to return Foo from the state.
* A new action that accepts Bar and update Baz in the stat
* ...

**Comment by zutigrm** [comment]
@eugene-manuilov thanks, AC updated

**Comment by eugene-manuilov** [comment]
Awesome! Thanks, @zutigrm. Slightly updated AC to have two top level points. AC is ✔️ now.

**Comment by 10upsimon** [comment]
@zutigrm IB LGTM, moving to EB

**Comment by aaemnnosttv** [comment]
@zutigrm @10upsimon it seems to me some of the work here isn't necessary unless I'm misunderstanding? [See my comment on the doc](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ&disco=AAABUg79E9I).

**Comment by zutigrm** [comment]
@aaemnnosttv Actually you are correct, since we switched to storing events in the settings, we will only need `hasConversionReportingEvents` selector, as helper that will be used with widgets

**Comment by tofumatt** [comment]
Moving directly to Approval as there's nothing to QA here 🙂
