### ISSUE TITLE
Exclude from Analytics: Logged-in users wont applied

### ISSUE THREAD

**Issue by valentinwinkelmann** [google/site-kit-wp#914]
If I switch off and save the logged-in users under SiteKit > Settings > Analytics > Edit 🖊 > Exclude from Analytics: Logged-in users, this will not be applied and saved.

**Comment by jamesozzie** [comment]
@valentinwinkelmann Thanks for reporting. Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. We would be happy to assist from there.
