### ISSUE TITLE
Reduce frequency of AdsLinks checks

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9141]
## Feature Description

Synchronization of the presence of AdsLinks for a GA4 property was added in #8382 for the purpose of better informing when Consent Mode should be recommended. It currently queries the state once per day, however, due to the only other condition being GA4 connected it has become the most requested endpoint of the Admin API. Since this state is not highly time-sensitive, or likely to change often, we should greatly reduce the frequency in which it is called.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The polling frequency for synchronizing the AdsLinks state via cron should be reduced to once/week
	* The check should only be scheduled when loading the SK dashboard
	* If Ads is connected, the check can be skipped

## Implementation Brief

* [x] Update `includes/Modules/Analytics_4/Synchronize_AdsLinked.php`
  * Include `Context` instance to the list of arguments in the constructor and assign it to the `$context` class property 
  * In `maybe_schedule_synchronize_ads_linked` method 
    * Check if in admin interface and on dashboard page to return early (`is_admin() && 'googlesitekit-dashboard' === $this->context->input()->filter( INPUT_GET, 'page' )`)
    * Replace current timestamp to use `WEEK_IN_SECONDS` instead of a day
  * In `synchronize_ads_linked_data` method:
    * Check if `Ads` module is connected to return early. You can use `googlesitekit_is_module_connected` filter for the check
* [x] Update `includes/Modules/Analytics_4.php`
  * Pass `$context` class property to the `Synchronize_AdsLinked` instance in `register` method 

### Test Coverage

* No updates needed

## QA Brief

1. Install `Advanced Cron Manager` plugin.

2. Make sure `Ads` module is deactivated and `Analytics 4` module is connected.

3. Go to `Tools > Cron Manager`, search for `googlesitekit_cron_synchronize_ads_linked_data`. If it is present, delete it.

4. Go to Site Kit dashboard, let it load completely.

5. Go to `Tools > Cron Manager` again and search for `googlesitekit_cron_synchronize_ads_linked_data`. It should be available with the next execution set to 7 days (a week).

## Changelog entry

* Reduce frequency of AdsLinks checks.

**Comment by neehhaa06** [comment]
Hello @aaemnnosttv 

fix: 9141

### optimizing AdsLinks checks for GA4 properties in Site Kit to ### improve efficiency and reduce API load.

**Comment by eugene-manuilov** [comment]
> * Replace current timestamp to use `WEEK_IN_SECONDS` instead of a day

@zutigrm, this will be applied only to the new SK installations, everyone else who has already had that cron job active won't switch to the weekly schedule. We need to unregister the existing schedule and re-register it again if the existing schedule is daily.

> * Check if `Ads` module is connected to return early. You can use `googlesitekit_is_module_connected` filter for the check

This should happen in the cron job hook itself.

**Comment by zutigrm** [comment]
@eugene-manuilov 
> Replace current timestamp to use WEEK_IN_SECONDS instead of a day
@zutigrm, this will be applied only to the new SK installations, everyone else who has already had that cron job active won't switch to the weekly schedule. We need to unregister the existing schedule and re-register it again if the existing schedule is daily.

It won't be necessary, because we only schedule this as a single non-repeating event each time. So if they have something scheduled for that day, as soon as that last event is executed, starting from next one, they will all be scheduled on a weekly basis.

> Check if Ads module is connected to return early. You can use googlesitekit_is_module_connected filter for the check
This should happen in the cron job hook itself.

Thanks, IB updated

**Comment by eugene-manuilov** [comment]
> > Replace current timestamp to use WEEK_IN_SECONDS instead of a day
> > @zutigrm, this will be applied only to the new SK installations, everyone else who has already had that cron job active won't switch to the weekly schedule. We need to unregister the existing schedule and re-register it again if the existing schedule is daily.
> 
> It won't be necessary, because we only schedule this as a single non-repeating event each time. So if they have something scheduled for that day, as soon as that last event is executed, starting from next one, they will all be scheduled on a weekly basis.

Ah... Yes, you are correct. 👍 

IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Followed the steps in the QAB: 
- When I search for `googlesitekit_cron_synchronize_ads_linked_data`. it appears after refreshing the dashboard fully with the next execution set to `7 days` 

![image](https://github.com/user-attachments/assets/e2d9e18d-2a28-41c6-8b25-0c14f5011c53)
