### ISSUE TITLE
Fix "See full details" link for the RRM module

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9144]
## Bug Description

When I click on the '[See full details in Reader Revenue Manager]' link on RRM module in the view mode, I get routed to a page hitting 400 error.
The error page is attached.

## Steps to reproduce

1. Activate RRM
2. Go to the RRM module under view mode

## Screenshots
Click on [See full details in Reader Revenue Manager]' link 
<img width="1290" alt="Screenshot 2024-08-06 at 11 36 50" src="https://github.com/user-attachments/assets/43b774de-414d-4efb-8e10-7d60a083c9b7">

400 error appears:
<img width="1065" alt="Screenshot 2024-08-06 at 11 36 55" src="https://github.com/user-attachments/assets/c2362f81-a68d-4ab6-8836-1c17f34550f3">

## Additional Context

 - PHP Version: 8.0
 - OS: Mac OS Sonoma
 - Browser: Chrome
 - Plugin Version: 1.133.0
 - Device: Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "See full details in Reader Revenue Manager" link on the RRM module page should open the following URL in a new tab:
  * `https://publishercenter.google.com`

## Implementation Brief

* [x] Update the `homepage` value for the RRM module to be `https://publishercenter.google.com`.

https://github.com/google/site-kit-wp/blob/1763e549ca4900900db17b8afa536dd7c5a615e9/includes/Modules/Reader_Revenue_Manager.php#L243

### Test Coverage

* Update any failing tests.

## QA Brief

1. Activate RRM
2. Go to the RRM module under view mode.
3. Click on "See full details in Reader Revenue Manager" link. It should direct to https://publishercenter.google.com/ in a new tab. Note that there might be an extra parameter `pli` which is fine.

## Changelog entry

* Update the "See full details" link in Reader Revenue Manager.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

@ankitrox @nfmohit , I have a suggestion for the link.
I am thinking if we should append the publication ID as well, based on what is selected in RRM module so that when we click the [See full details in Reader Revenue Manager]' link, we are directed to the correct Publication.

The reason why is because if a user has multiple publications, the publication they might see might not be the correct one.

Refer to the video below.

<Details>

https://github.com/user-attachments/assets/5a41afef-3e06-4ea3-8077-0f9a97128b41

</Details>

**Comment by techanvil** [comment]
Hi @kelvinballoo, thanks for the suggestion. I had considered this too while drafting the AC. However, we have a standard pattern of linking to the statically defined homepage for the service in these "See full details" links.

For example, in the Analytics settings view, the "See full details in Analytics" link points to https://analytics.google.com; we provide the "Edit in Analytics" link to take the user directly to the connected property.

![image](https://github.com/user-attachments/assets/78687caf-2663-4100-b0c7-d98e5e225781)

A similar pattern can be seen in Tag Manager, AdSense etc.:
![image](https://github.com/user-attachments/assets/4220548d-4c5d-4022-95e5-977623114629)

![image](https://github.com/user-attachments/assets/122c6cb6-d507-47fd-b7c8-c03016b29165)

So, the consistent thing to do here is to maintain the current target of https://publishercenter.google.com for the "See full details" link, but we should consider adding an "Edit in Reader Revenue Manager" link or suchlike to take the user directly to the publication...

@nfmohit, has this already come up for consideration for the RRM module?

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @techanvil . Agreed on that.
With that, this ticket is QA pass. We are no longer hitting 400 error page.

<Details>

https://github.com/user-attachments/assets/d61fb1c6-4a5a-4e82-9015-33b742805327

</Details>

@nfmohit , this is a QA pass and can be moved to approval but since there is a follow up question for you [here](https://github.com/google/site-kit-wp/issues/9144#issuecomment-2286104864), I am assigning this ticket to you first.

**Comment by nfmohit** [comment]
> @nfmohit, has this already come up for consideration for the RRM module?

Unfortunately, no, it looks like we missed this during the design doc/UX design stage. Thank you for pointing it out. I have just created a new issue #9192 that adds this.

> @nfmohit , this is a QA pass and can be moved to approval but since there is a follow up question for you [here](https://github.com/google/site-kit-wp/issues/9144#issuecomment-2286104864), I am assigning this ticket to you first.

I've opened a follow-up issue. As this is a QA pass, I'm moving it to Approval, thanks @kelvinballoo !
