### ISSUE TITLE
Add `conversionReporting` Feature Flag

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9152]
## Feature Description

A new feature flag, `conversionReporting`, is required in order to gate work related to the Analytics Conversion Reporting epic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

*  A new `conversionReporting` feature flag is present in the code base
*  Said new `conversionReporting` feature flag is selectable via the Site Kit Tester plugin

## Implementation Brief

* [ ] Update `feature-flags.json`, add `conversionReporting` to the list

### Test Coverage

* No updates needed

## QA Brief

* Verify that `conversionReporting` feature flag is present using tester plugin

## Changelog entry

* Add `conversionReporting` feature flag to plugin.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `conversionReporting` feature flag is present using tester plugin. 
- I was able to enable the feature flag with no errors. 
- Refreshed tester plugin settings and the feature flag stayed enabled

![image](https://github.com/user-attachments/assets/80efb13f-4697-46b4-9d2b-2265b490d177)
