### ISSUE TITLE
Creation of `Top traffic source driving leads` ACR KMW

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9155]
## Feature Description

One of the identified metric tiles for the ACR epic is `Top traffic source driving leads`. Details of this metric tile are as follows:

- **Description**: Total number of lead form submissions for top traffic source. We will extract only the top performing one and show it in the existing numeric tile template (like what we have for the existing “Top traffic source” KM tile). Tile should combine counts from both contact and submit_lead_form events, if present, otherwise, it will use the data for events that are present.
- **Events**: `submit_lead_form`
- **Metrics**: `generate_lead`, `submit_lead_form`, and `contact` events count
- **Dimension**: `sessionDefaultChannelGroup`
- **Order**: Descending
- **Purpose**: Inform users of the most performing traffic source so they can take action in that direction, or adjust their content strategy/marketing efforts or get confirmation that their current strategy is growing and they should keep doing it.
- **Type**: Numerical

Figma design: [TBA](#)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by zutigrm** [comment]
This one is a duplicate, I have created same one and move it to ACR, didn't spot this one at the time. CLosing it as duplicate

cc: @10upsimon
