### ISSUE TITLE
Creation of `Top traffic source driving add to cart` ACR KMW

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9158]
## Feature Description

One of the identified metric tiles for the ACR epic is `Top traffic source driving add to cart`. Details of this metric tile are as follows:

- **Description**: Total number of add to cart events for top traffic source. We will extract only the top performing one and show it in existing numeric tile template (similar to the existing “Top traffic source” KMW tile)
- **Events**: `add_to_cart`
- **Metrics**: `addToCarts`
- **Dimension**: `sessionDefaultChannelGroup`
- **Order**: Descending
- **Purpose**: Inform users of the most performing traffic source so they can take action in that direction, or adjust their content strategy/marketing efforts or get confirmation that their current strategy is growing and they should keep doing it.
- **Type**: Numerical

Figma design: [TBA](#)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Top traffic source driving add to cart` ACR widget is introduced to the existing list of widgets available within KMW
  * Said widget presents visually as per the Figma design: [Top traffic source driving add to cart](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&t=StMacPaWHh4k5rtt-0) within ACR metrics section of design
  * Widget displays the percentage of `addToCarts` metric count for the `sessionDefaultChannelGroup` dimension (using the 1st/top channel from the results)
  * `Traffic source that generates the most add to cart events` should be used for description and the tooltip
  * Widget will not be displayed, or shown in the selection panel list if `add_to_cart` event is not present, or `conversionReporting` feature flag is not enabled

## Implementation Brief

* [ ] Update `assets/js/googlesitekit/datastore/user/constants.js`
  * Include new constant, say `KM_ANALYTICS_TOP_TRAFFIC_SOURCE_DRIVING_ADD_TO_CART`, holding a string `kmAnalyticsTopTrafficSourceDrivingAddToCart` 
* [ ] Update `assets/js/components/KeyMetrics/key-metrics-widgets.js`
  *  Register new widget for `KM_ANALYTICS_TOP_TRAFFIC_SOURCE_DRIVING_ADD_TO_CART`
    * Use "Top traffic source driving add to cart" for `title`
    * Use "Traffic source that generates the most add to cart events" for `description` and `tooltip`
    * Include new property `requiredConversionEventName`, and assign it an array value containing `add_to_cart` event name
    * In `displayInList` pass the helper function `shouldDisplayWidgetWithConversionEvent`
* [ ] Add `assets/js/modules/analytics-4/components/widgets/TopTrafficSourceDrivingAddToCart.js`
  * You can use `assets/js/modules/analytics-4/components/widgets/TopTrafficSourceWidget.js` as a starting point 
  * Include `showWidget` const which should hold value of `isKeyMetricActive` or if no event is present in the inline data (the condition used in `shouldDisplayWidgetWithConversionEvent` helper function), so this const can be used to return `WidgetNull` and prevent report requests if conditions are not met. You can see example usage of this const in `assets/js/modules/analytics-4/components/widgets/PopularProductsWidget.js`
  * In `totalAddToCartReportOptions`:
    * Use `addToCarts` metric
  * In `trafficSourceReportOptions`:
    * Use `sessionDefaultChannelGroup` for dimensions
    * Use `addToCarts` metric
* [ ] Update `assets/js/modules/analytics-4/index.js` to include new widget registration

### Test Coverage

* Add stories for the new widget

## QA Brief

* Setup Site Kit with Analytics module
  * Contact Aleksej for access to the website with ACR data, if you do not have it already
* Verify that in key metrics selection panel `Top traffic source driving add to cart` widget is not available
* Enable `conversionReporting` feature flag
* Go to key metrics selection panel and choose `Top traffic source driving add to cart` tile
* Verify it widget is showing data, and matching the figma design
* Go to analytics settings - switch to different account/property, and verify that `Top traffic source driving add to cart` widget is showing zero data (since widget will only have data on property that has ACR data)

## Changelog entry

* Add the `Top traffic source driving add to cart` widget.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment using test ACR test site.
- Verified that  `Top traffic source driving add to cart` widget is not available under KMW panel if conversionReporting feature flag is not enabled.
- Verified the `Top traffic source driving add to cart `widget is showing zero data if data is not available for selected property or selected date range.
- Verified `Traffic source that generates the most add to cart events` used for description and the tooltip
- Verified that the widget is showing correct data as per analytics, and matching the [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&node-type=frame&t=FQy0jev5nwa4EDKq-0)

<details>

![image](https://github.com/user-attachments/assets/bf17250f-0cc1-4f9d-9168-a15ed47cfdcd)

![image](https://github.com/user-attachments/assets/5c750ba6-8e3b-4913-a8b6-7a708a78d524)

![image](https://github.com/user-attachments/assets/0901ad31-f1b6-4dd4-b018-7ea04850b139)

![image](https://github.com/user-attachments/assets/a2e2526c-cb0e-428a-8d15-3f7cfc6bd590)

![image](https://github.com/user-attachments/assets/adec8c43-13f8-4065-aedd-ca351de9b92f)

28 days -

![image](https://github.com/user-attachments/assets/6bf36c07-34ca-41bd-9495-56cc046e6443)

7 Days -

![image](https://github.com/user-attachments/assets/cb54ba68-1972-4235-96da-3327866cd08a)

90 Days -

![image](https://github.com/user-attachments/assets/27dbe4f2-377a-4173-a674-0595e0f57eb7)

</details>
