### ISSUE TITLE
Creation of `Top cities driving purchases` ACR KMW

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9160]
## Feature Description

One of the identified metric tiles for the ACR epic is `Top cities driving purchases`. Details of this metric tile are as follows:

- **Description**: Cities from which users are making the most purchases.
- **Events**: `purchase`
- **Metrics**: `ecommercePurchases`
- **Dimension**: `city`
- **Order**: Descending
- **Purpose**: Inform users of the most active countries making the purchases on the website so they can make informed decisions on increasing the effort (translating/keywords/marketing campaigns, etc) to serve their content/products to these countries.
- **Type**: Tabular

Figma design: [TBA](#)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Top cities driving purchases` ACR widget is introduced to the existing list of widgets available within KMW
  * Said widget presents visually as per the Figma design: [Top traffic source driving leads](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&t=StMacPaWHh4k5rtt-0) within ACR metrics section of design
  * Widget displays the list of top cities for `ecommercePurchases` metric based on `city` dimension (returning top 3 results)
  * `Cities driving the most purchases` should be used for description and the tooltip
  * Widget will not be displayed, or shown in the selection panel list if `purchase` event is not present, or `conversionReporting` feature flag is not enabled

## Implementation Brief

* [ ] Update `assets/js/googlesitekit/datastore/user/constants.js`
  * Include new constant, say `KM_ANALYTICS_TOP_CITIES_DRIVING_PURCHASES`, holding a string `kmAnalyticsTopCitiesDrivingPurchases` 
* [ ] Update `assets/js/components/KeyMetrics/key-metrics-widgets.js`
  *  Register new widget for `KM_ANALYTICS_TOP_CITIES_DRIVING_PURCHASES`
    * Use "Top cities driving purchases" for `title`
    * Use "Cities driving the most purchases" for `description` and `tooltip`
    * Include new property `requiredConversionEventName`, and assign it an array value containing `purchase` event name
    * In `displayInList` pass the helper function `shouldDisplayWidgetWithConversionEvent`
* [ ] Add `assets/js/modules/analytics-4/components/widgets/TopCitiesDrivingPurchasesWidget.js`
  * You can use `assets/js/modules/analytics-4/components/widgets/TopCitiesWidget.js` for example, as a starting point 
  * In `reportOptions`:
    * Use `city` for dimensions
    * Use `ecommercePurchases` metric
    * Filter out the `not set` dimension value for the city. You can see an example in `TopCitiesDrivingLeadsWidget`
* [ ] Update `assets/js/modules/analytics-4/index.js` to include new widget registration

### Test Coverage

* Add stories for the new widget

## QA Brief

* Setup Site Kit with the Analytics module enabled 
* Contact @zutigrm for access to the test website containing ACR data
* Verify that in key metrics selection panel the `Top cities driving purchases` widget is not available
* Enable the `conversionReporting` feature flag
* Navigate to the key metrics selection panel and select the `Top cities driving purchases` tile
* Verify that the widget is showing data, and matching the [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&node-type=frame&t=FQy0jev5nwa4EDKq-0)
* Go to Analytics settings - switch to a different account/property, and verify that the `Top cities driving purchases` widget is showing zero data (since the widget will only be having data on properties that have required ACR events and data associated with them)

## Changelog entry

* Added the `Top cities driving purchases` widget.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by eugene-manuilov** [comment]
@zutigrm, looks like you missed my [comment](https://github.com/google/site-kit-wp/pull/9370/files#r1768838093) in your PR or forgot to push your changes. Could you please check it?

**Comment by zutigrm** [comment]
@eugene-manuilov Thanks, sorry about that, didn't send my reply somehow. Left you a comment

**Comment by eugene-manuilov** [comment]
@zutigrm could you please add QAB?

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm 

_Question >I noticed that after enabling the conversionReporting feature flag, the ACR widgets do not appear immediately after the page loads under the KMW selection panel. We need to reset the plugin and then reconnect with the feature flag enabled for the ACR widgets to appear. Should I create a separate ticket for this as it applies to all ACR widgets or you will fix this under follow up of this ticket?_

<details>


https://github.com/user-attachments/assets/35bc7c5a-c9fd-4eae-bda9-6bfcc84e1015

</details>
 

- Tested on dev environment.
- Verified that `Top cities driving purchases` widget is not available under KMW panel if `conversionReporting `feature flag is not enabled.
- Verified the `Top cities driving purchases` widget is showing zero data if data is not available for selected property or selected date range.
- Verified that the widget is showing data, and matching the [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&node-type=frame&t=FQy0jev5nwa4EDKq-0)

<details>

![image](https://github.com/user-attachments/assets/e01392dd-0b57-406c-9412-88ccda68429b)

![image](https://github.com/user-attachments/assets/d45c11c1-d7de-4391-83ac-73889c523ddc)

![image](https://github.com/user-attachments/assets/78f78973-3f8c-438e-b167-d897d5f65971)

</details>

**Comment by zutigrm** [comment]
Hi @mohitwp this is not connected to the feature flag, the ACR metrics (including this one) will be shown in the selection panel after events have been detected. Detection of events happens in two ways:
* Over CRON that checks this every 24h
* Upon analytics setup or property change

What you are seeing is normal, as event detection won't happen until feature flag is enabled, and if you had analytics setup before that, events will be synced on 24h schedule after flag is enabled. So you can either setup analytics under feature flag with the property that has ACR data, or change the property,  or you can manually trigger sync earlier, you can see the steps in QAB for this issue #9130

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @zutigrm !

- Tested on dev environment.
- Verified that `Top cities driving purchases` widget is not available under KMW panel if `conversionReporting `feature flag is not enabled.
- Verified the `Top cities driving purchases` widget is showing zero data if data is not available for selected property or selected date range.
- Verified that the widget is showing data, and matching the [Figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&node-type=frame&t=FQy0jev5nwa4EDKq-0)

<details>

![image](https://github.com/user-attachments/assets/e01392dd-0b57-406c-9412-88ccda68429b)

![image](https://github.com/user-attachments/assets/d45c11c1-d7de-4391-83ac-73889c523ddc)

![image](https://github.com/user-attachments/assets/78f78973-3f8c-438e-b167-d897d5f65971)

![image](https://github.com/user-attachments/assets/fd1100ce-cf8b-4305-b224-c3f0e38037dc)

</details>
