### ISSUE TITLE
Creation of `Top traffic source driving purchases` ACR KMW

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9164]
## Feature Description

One of the identified metric tiles for the ACR epic is `Top traffic source driving purchases`. Details of this metric tile are as follows:

- **Description**: Total number of purchases for top traffic source. We will extract only the top performing one and show it in existing numeric tile template (similar to the existing “Top traffic source” KM tile)
- **Events**: `purchase`
- **Metrics**: `ecommercePurchases`
- **Dimension**: `sessionDefaultChannelGroup`
- **Order**: Descending
- **Purpose**: Inform users of the most performing traffic source so they can take action in that direction, or adjust their content strategy/marketing efforts or get confirmation that their current strategy is growing and they should keep doing it.
- **Type**: Numerical

Figma design: [TBA](#)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Top traffic source driving purchases` ACR widget is introduced to the existing list of widgets available within KMW
  * Said widget presents visually as per the Figma design: [Top traffic source driving leads](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&t=StMacPaWHh4k5rtt-0) within ACR metrics section of design
  * Widget displays the percentage of `ecommercePurchases` metric count for the `sessionDefaultChannelGroup` dimension (using the 1st/top channel from the results)
  * `Traffic source that generates the most purchases` should be used for description and the tooltip
  * Widget will not be displayed, or shown in the selection panel list if `purchase` event is not present, or `conversionReporting` feature flag is not enabled

## Implementation Brief

* [ ] Update `assets/js/googlesitekit/datastore/user/constants.js`
  * Include new constant, say `KM_ANALYTICS_TOP_TRAFFIC_SOURCE_DRIVING_PURCHASES`, holding a string `kmAnalyticsTopTrafficSourceDrivingPurchases` 
* [ ] Update `assets/js/components/KeyMetrics/key-metrics-widgets.js`
  *  Register new widget for `KM_ANALYTICS_TOP_TRAFFIC_SOURCE_DRIVING_PURCHASES`
    * Use "Top traffic source driving purchases" for `title`
    * Use "Traffic source that generates the most purchases" for `description` and `tooltip`
    * Include new property `requiredConversionEventName`, and assign it an array value containing `purchase` event name
    * In `displayInList` pass the helper function `shouldDisplayWidgetWithConversionEvent`
* [ ] Add `assets/js/modules/analytics-4/components/widgets/TopTrafficSourceDrivingPurchases.js`
  * You can use `assets/js/modules/analytics-4/components/widgets/TopTrafficSourceWidget.js` as a starting point 
  * Include `showWidget` const which should hold value of `isKeyMetricActive` or if no event is present in the inline data (the condition used in `shouldDisplayWidgetWithConversionEvent` helper function), so this const can be used to return `WidgetNull` and prevent report requests if conditions are not met. You can see example usage of this const in `assets/js/modules/analytics-4/components/widgets/PopularProductsWidget.js`
  * In `totalPurchasesReportOptions`:
    * Use `ecommercePurchases` metric
  * In `trafficSourceReportOptions`:
    * Use `sessionDefaultChannelGroup` for dimensions
    * Use `ecommercePurchases` metric
* Update `assets/js/modules/analytics-4/index.js` to include new widget registration

### Test Coverage

* Add stories for the new widget

## QA Brief

* Setup Site Kit with Analytics module
  * Contact Aleksej for access to the website with ACR data, if you do not have it already
* Verify that in key metrics selection panel `Top traffic source driving purchases` widget is not available
* Enable `conversionReporting` feature flag
* Go to key metrics selection panel and choose `Top traffic source driving purchases` tile
* Verify it widget is showing data, and matching the figma design
* Go to analytics settings - switch to different account/property, and verify that `Top traffic source driving purchases` widget is showing zero data (since widget will only have data on property that has ACR data)

## Changelog entry

* Add the `Top traffic source driving purchases` widget.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that `Top traffic source driving purchases`  widget is not available under KMW panel if `conversionReporting` feature flag is not enabled.
- Verified that `Traffic source that generates the most purchases`  used for description and the tooltip.
- Verified that widget is showing correct data, and matching the figma design.
- Verified that widget changes the color of percentage as per negative and positive trends in data.
- Verified the `Top traffic source driving purchases`  widget is showing zero data if data is not available for selected property or selected date range.


<details>

![image](https://github.com/user-attachments/assets/55b0aa8e-3098-4f93-b934-4dbfc14ef7f9)

![image](https://github.com/user-attachments/assets/b7b3453d-1855-4ae6-8196-907a34fd8309)

![image](https://github.com/user-attachments/assets/bb76e308-94ea-4cfd-8b3b-3b3ce7a12125)

![image](https://github.com/user-attachments/assets/53a282dc-1959-4467-b3bb-579c20c53bbf)

</details>
