### ISSUE TITLE
Impossible to stop tagmanager code placement

### ISSUE THREAD

**Issue by robwent** [google/site-kit-wp#9169]
## Bug Description

When I change the setting for Tagmanager to stop sitekit placing the code on the site, the save button becomes disabled with the text 'confirm changes'.
After removing the disabled attribute in dev tools, it's still not possible to save the setting and reloading the page shows that sitekit is still adding the code to the site.
The only way to stop it is to disconnect tagmanager completely.
(I want to add tagmanager with complianz for Google consent).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi there @robwent thanks for raising this. Unfortunately, we don't provide support via GitHub but we'd be happy to help you with this and see what's happening if you could [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) in the Site Kit forum. 

Thanks!
