### ISSUE TITLE
Agency with hundreds of client Google Analytics accounts unable to assign correct profiles

### ISSUE THREAD

**Issue by uogecko** [google/site-kit-wp#9170]
As a web development agency, we build WordPress websites for hundreds of clients, each of which have Google Analytics accounts. It's my understanding that Google's API limits the number of Analytics accounts per query to 100 or so. That's causing a huge issue for us because we're unable to assign the correct Analytics account when we configure the plugin.

**Comment by aaemnnosttv** [comment]
Hi there, and thanks for raising this. There is a limit of [100 Analytics accounts](https://support.google.com/analytics/answer/9303323?hl=en&utm_id=ad#zippy=%2Cin-this-article:~:text=up%20to%20a%20maximum%20of%20100) per Google account, so I'm guessing you have many accounts that are shared with your agency's account to exceed that limit?

When setting up Analytics we currently request the maximum number of accounts possible in a single request which is 200 – so your Google account would need to have access to more than 200 to experience this issue.

The simplest workaround for this limitation is to set up the Analytics module using a different Google account that has access to fewer total accounts as to not exceed the 200 account limit above. That may not be ideal, but would work today to unblock the setup flow.

I hope that helps. If others are similarly impacted by this issue, please let us know below.

**Comment by uogecko** [comment]
I appreciate the reply! Google Analytics allows users to request an increase to the maximum number of accounts allowed. Our agency has done that a few times and we have well over 200 now. It would be a huge help if the plugin could list all of the accounts so that we can assign the correct profile!

**Comment by jamesozzie** [comment]
@uogecko Just to keep you updated on this, we're still investigating options. Should we have any update on this we'll let you know here. Thank you.

**Comment by uogecko** [comment]
Thanks for keeping me posted, @jamesozzie !

**Comment by aaemnnosttv** [comment]
I've opened #9348 to address this. We have quite a bit going on right now so I can't say when it will land, but feel free to check in if it's been a while. We'll also follow-up here when completed 👍  Cheers!

**Comment by uogecko** [comment]
Thanks - appreciate it!

I'm also happy to help test when you're ready!

G

[image: Gecko Designs] <https://www.geckodesigns.com/>

*Gabriel Silverman* • He/Him/His
+1 (406) 662-1123 x703 <14066621123>
***@***.***

Gecko Designs
523 N Higgins Ave
Missoula, MT 59802

geckodesigns.com <https://www.geckodesigns.com/>

**Comment by aaemnnosttv** [comment]
Hey @uogecko 👋 Just dropping in to let you know that this issue should be resolved in the upcoming release (1.138.0) scheduled for Oct 21st. Let us know if you're still having any issues once you have a chance to upgrade and give it another try.

**Comment by uogecko** [comment]
@aaemnnosttv thanks for the update - I really appreciate it! This will be a big help for us - thank you!
