### ISSUE TITLE
Remove `conversionInfra` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9173]
## Feature Description

Once available to all sites, the `conversionInfra` feature flag should be removed, replacing the conditional functionality it controlled with the guarded code unconditionally.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `conversionInfra` feature flag should be removed such that conditions that use it should keep the code path where the flag is `true`
* Any other references to the flag should be removed, except the changelog

## Implementation Brief

* [ ] Remove the `conversionInfra` feature flag from `feature-flags.json`.
* [ ] Remove the feature flag blocking from the flowing files:
   * [ ] assets/js/components/conversion-tracking/ConversionTrackingToggle.js
   * [ ] assets/js/components/conversion-tracking/ConversionTrackingToggle.stories.js
   * [ ] assets/js/modules/ads/components/settings/SettingsEdit.stories.js
   * [ ] assets/js/modules/ads/components/settings/SettingsForm.js
   * [ ] assets/js/modules/ads/components/settings/SettingsView.js
   * [ ] assets/js/modules/ads/components/settings/SettingsView.stories.js
   * [ ] assets/js/modules/analytics-4/components/settings/OptionalSettingsView.js
   * [ ] assets/js/modules/analytics-4/components/settings/SettingsForm.js
   * [ ] assets/js/modules/analytics-4/components/settings/SettingsForm.stories.js
   * [ ] assets/js/modules/analytics-4/components/settings/SettingsView.stories.js
   * [ ] includes/Plugin.php - 
   * [ ] includes/Core/Site_Health/Debug_Data.php
   * [ ] tests/phpunit/integration/Core/Site_Health/Debug_DataTest.php

### Test Coverage

* Update any newly failing tests. There should be no changes to VRTs.

## QA Brief

* Create a new site and install the plugin
* Ensure that you don't have the `conversionInfra` feature flag forced by the tester plugin
* Ensure that there is no `conversionInfra` feature flag set for your site.
* Go to Analytics and Ads modules and ensure that there is the conversion tracking toggle available and you can enable/disable it.

## Changelog entry

* Remove `conversionInfra` feature flag.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
@benbowler FWIW we don't really need to list out all of the instances where the flag is being used in the IB since that list will likely be out of date by the time this is worked on. This is one of those issues where an IB is almost unnecessary, but we could instead describe/list how to find instances and maybe which (if any) to keep/ignore.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `conversionInfra` feature flag does not appear in the tester plugin. 
- There is no `conversionInfra` feature flag set for my site in Site Health.
- The conversion tracking toggle is available in the Ads and/or Analytics settings and I can enable/disable it.
- I testted this to ensure that the toggle functioned with each module connected and disconnected. 
- I tested the tracking on one of the supported plugins, Ninja Forms and could see that the correct event is getting tracked with the `submit_lead_form` and the source of `site-kit` is appearing. 

<details>
 <summary>Screenshots</summary>
![image](https://github.com/user-attachments/assets/9878ccfd-5915-4963-9761-dc6aeb8ef5e3)
![image](https://github.com/user-attachments/assets/88fa35ad-e51d-4f70-9655-944322909ce7)
![image](https://github.com/user-attachments/assets/137c4efb-0a79-46e9-b1d7-8fca06490d21)
![image](https://github.com/user-attachments/assets/bc9e21cd-afe7-43f8-b5a0-adab31f123b5)
![image](https://github.com/user-attachments/assets/5c5984e0-9a0f-4da4-b4a7-b84c6cd3661c)
![image](https://github.com/user-attachments/assets/da2b4d6c-4ab7-4207-b927-a382c72ccd42)
![image](https://github.com/user-attachments/assets/dcdc9128-bf22-412d-8614-0bb1cf42bb35)
![image](https://github.com/user-attachments/assets/2e4bcb69-8bdd-40dc-96aa-b1ecd0d29a4d)
</details>
