### ISSUE TITLE
AdSense set up ignores existing tag if user has an account

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#918]
## Bug Description

Currently the existing tag detection only affects the set up flow if the user has no account, nor has access to an AdSense account.

## Steps to reproduce

These steps are specific to an existing tag that belongs to an AdSense account that your user does not have access to.

1. Manually place an AdSense tag on your site  
    ```html
    <script data-ad-client="ca-pub-1234567890" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    ```
1. Set up Site Kit using a Google account with no AdSense accounts
1. Connect AdSense module
1. See notice about existing code

![image](https://user-images.githubusercontent.com/1621608/69702331-9de1aa00-10f7-11ea-8e3b-1b2c624bccbd.png)

**Bug**
1. Manually place an AdSense tag on your site  
    ```html
    <script data-ad-client="ca-pub-1234567890" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    ```
1. Set up Site Kit using a Google account with 1 or more AdSense accounts
1. Connect AdSense module
1. See no notice about existing code is shown  
_Set up appears as if no existing tag was detected_

Mentioned in https://github.com/google/site-kit-wp/issues/803#issuecomment-558210795 

## Additional Context

 - Plugin Version 1.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by OisinOConnor** [comment]
We can de-prioritise this, as we're going to remove the "existing code on page" check as part of the flow simplification.

**Comment by marrrmarrr** [comment]
Moving this to "revisit later" and assigning to Felix, since he is reworking the entire module and can double-check that this will function as expected once the changes are in place.

**Comment by felixarntz** [comment]
This is no longer relevant as it has already been addressed by the refactoring in early 2020
