### ISSUE TITLE
Enhance compatibility with Docker locally for E2E

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9183]
## Feature Description

Newer versions of Docker Desktop don't expose the default socket (`/var/run/docker.socket`) by default

![image](https://github.com/user-attachments/assets/12a00f4d-9e95-4556-92a7-2e9eed1e5edc)

If disabled, this will cause E2E test runs to fail without an obvious reason as it is expected to exist since E2E requires Docker.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Local E2E runs should run consistently (not specifically pass), regardless of the "Allow default Docker socket to be used" setting
* If Docker cannot be communicated with, exit the process with an error message
```
Failed to connect to Docker with the following error: { message }
```

## Implementation Brief

* [ ] Upgrade `dockerode` to the latest version (currently [`4.0.2`](https://github.com/apocas/dockerode/releases)), as it will properly find the socket by default including better support cross-platform
* [ ] Remove the hardcoded socket path currently provided https://github.com/google/site-kit-wp/blob/64b8643c162ffff4fc877a51f2fb43c0ba4f45c8/tests/e2e/config/wordpress-debug-log/index.js#L35
* [ ] If Docker is unable to be communicated with, exit the process with a more informative error message as per AC

### Test Coverage

* No changes – test infra

## QA Brief

This can be tested a few ways

1. Edit `tests/e2e/bin/test-docker-connectivity` and give `Docker` a non-existent socket path, then run E2E as usual `npm run test:e2e`
```diff
- const docker = new Docker();
+ const docker = new Docker( { socketPath: '/non/existent' } );
```
2. Stop Docker entirely (engine) and run `tests/e2e/bin/test-docker-connectivity`. You should see the error message and a non-successful error code.

## Changelog entry

* N/A

**Comment by 10upsimon** [comment]
### QA:ENG PASS
- ✅ Altered `tests/e2e/bin/test-docker-connectivity` and set non existent socket, `const docker = new Docker( { socketPath: '/non/existent' } );`
- ✅ Stopped Docker engine
- ✅ Executed `tests/e2e/bin/test-docker-connectivity`
- ✅Noted error message: `Failed to connect to Docker from Node with message: "connect ENOENT /non/existent"`
