### ISSUE TITLE
Tag Manager and AMP pages issue

### ISSUE THREAD

**Issue by dariocalamai** [google/site-kit-wp#919]
Hi!
thanks for your work!

I got a problem searching the correct way to configure Site Kit for Tag manager.
1 try:
In Site Kit settings I connected Analytics and Tag Manager services (I activated all services).
Both AMP and non-AMP pages have Analytics and Tag Manager scripts.
On analytics I have those problems
* ONLY on AMP pages:
  - Avg. time on page dropped from around 5minutes to 30 seconds
  - Pages/session doubled 
* On all page types:
  - Bounce rate near 0%

2 try:
from first scenario I removed Analytics Code Snippet from Site Kit, so all the pages was GTM script only.
All Analytics data are back to normal except for AMP pages. AMP pages were not recognized from Analytics. I think because my GTM container is not an AMP container (https://support.google.com/tagmanager/answer/9205783?hl=en). 
But, as is, I can't tell to Site Kit a "use this different containers for AMP pages", right?

I'm using last version of Site Kit.

thanks,
  Dario

**Comment by ernee** [comment]
@dariocalamai sorry for the delay. We now provide support for Site Kit in the [WordPress Support Forums.](https://wordpress.org/support/plugin/google-site-kit/). Could you post a new topic there and reference your site URL so we can see what could be occurring? Thank you!
