### ISSUE TITLE
Add "Edit in Reader Revenue Manager" link for the RRM module

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9192]
## Feature Description

As pointed out kindly by @techanvil [here](https://github.com/google/site-kit-wp/issues/9144#issuecomment-2286104864), similar to other modules, an "_Edit in Reader Revenue Manager_" link should be added to the RRM module's settings view screen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* An "_Edit in Reader Revenue Manager_" external link should be added to the settings view screen of the Reader Revenue Manager module.
	* The link text should technically be "_Edit publication in Reader Revenue Manager_", but "_publication_" should be visually hidden, only accessible to screen readers.
* This should be added just to the right-side of the publication ID, and look similar to how the "_Edit in Analytics_" external icon exists for the same screen of the Analytics module.
* The link should open the publication details page in the Publisher Center in a new tab.

## Implementation Brief

* [ ] Update `assets/js/modules/reader-revenue-manager/components/settings/SettingsView.js`:
	* [ ] Adjacent to the existing `div.googlesitekit-settings-module__meta-item` element, add the external link as mentioned in the ACs in a new `div.googlesitekit-settings-module__meta-item.googlesitekit-settings-module__meta-item--data-only` element, similar to how the "_Edit in Analytics_" link is added in `assets/js/modules/analytics-4/components/settings/SettingsView.js`.
	* [ ] The `VisuallyHidden` component should be used to prevent the "publication" text from being visible according to the ACs.

### Test Coverage

* No tests need to be added/updated.
* Update VRT references if required.

## QA Brief

* Connect RRM module. 
* The link, as defined it ACs should appear in Settings View of RRM module. Clicking the link should open the publication details in Reader Revenue Manager. 

## Changelog entry

* Add an "Edit in Reader Revenue Manager" link to the RRM module's settings view screen.

**Comment by kuasha420** [comment]
IB :heavy_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This was verified good. Moving ticket to approval.

- An "Edit in Reader Revenue Manager" external link was added to the settings view screen of the Reader Revenue Manager module.
   - This appeared just to the right-side of the publication ID, and looks similar to how the "Edit in Analytics" external icon exists for the same screen of the Analytics module.
   - The link opens the publication details page in the Publisher Center in a new tab.
   <Details>
   
   https://github.com/user-attachments/assets/b237c881-81d8-4994-8f93-c6d6d87bf6fc

   </Details>

- The link text is technically "Edit publication in Reader Revenue Manager", but "publication" is visually hidden and is only accessible to screen readers.
   <Details>
   
   https://github.com/user-attachments/assets/fdbb025f-caa3-48a9-b812-e818a9599598

   </Details>
