### ISSUE TITLE
Sort Storybook menu items

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9194]
## Feature Description

At present the Storybook menu items are not consistently sorted.

For example, the Components section is an unsorted list:

![image](https://github.com/user-attachments/assets/da51b550-5da7-44da-ae5a-95e0ab6a8c53)

Furthermore, the top level items are not sorted:

![image](https://github.com/user-attachments/assets/c6e32b8e-dd5c-4f36-8aa9-9c0dcb5fe72f)

It would be good to alphabetically sort these lists for ease of navigation.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Storybook menu should be sorted alphabetically.
* Folders should be grouped together in a sorted list at the top of a section.

## Implementation Brief

* [x] Update `.storybook/preview.js`, adding the following block to the [exported parameters const](https://github.com/google/site-kit-wp/blob/798b43c2ba8711caadfe049e328588a0008e00a1/.storybook/preview.js#L111):
```
	options: {
		storySort: {
			method: 'alphabetical',
		},
	},
```

### Test Coverage

* No test coverage required.

## QA Brief

* View the storybook generated at this branch, confirm the top level folders and all sub level stories are sorted alphabetically.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️  but I'll change the estimate to `3`.

**Comment by benbowler** [comment]
@techanvil @eugene-manuilov while working on this ticket I suggest a couple of other cleanups to the stories, I could do this here or create a follow up ticket:

1. Move these top level stories to the components folder:

<img width="219" alt="Screenshot 2024-09-23 at 12 23 34" src="https://github.com/user-attachments/assets/b7b13a2b-6e4b-4425-9bc6-04e596b447a5">

2. Move these top level module folders to within the existing modules folder:

<img width="207" alt="Screenshot 2024-09-23 at 12 23 39" src="https://github.com/user-attachments/assets/170d870f-3bab-4dda-baa6-19a37b63e6a7">
<img width="226" alt="Screenshot 2024-09-23 at 12 23 45" src="https://github.com/user-attachments/assets/d69af117-6302-4b2c-b4ab-ea5a71116756">
<img width="170" alt="Screenshot 2024-09-23 at 12 23 49" src="https://github.com/user-attachments/assets/b09e9417-36ae-4e29-8810-c5e833fde421">

**Comment by techanvil** [comment]
Thanks @benbowler! These would be good to apply. I'd suggest creating a new issue where we can spec them out fully, and potentially consider some additional improvements, rather than including them here.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Reviewed this and here are a couple of observations based on the tested URL : https://google.github.io/site-kit-wp/storybook/develop/?path=/story/accountchooser--account-chooser

**ITEM 1:**
The AC states `Folders should be grouped together in a sorted list at the top of a section.`
However, I did not see this implemented.
E.g. Under 'Adsense Module', there is a folder 'Component' but it's not at the top of the section. Refer to image attached.
Also added another example under 'Components'
<Details>

<img width="367" alt="Screenshot 2024-09-24 at 23 30 46" src="https://github.com/user-attachments/assets/dfecf8d5-5802-49d3-87eb-228685570209">

<img width="735" alt="Screenshot 2024-09-24 at 23 32 55" src="https://github.com/user-attachments/assets/f88cf6ad-4d4d-4b48-94e6-d4e42463b718">


</Details>

________________________________________________________________

**ITEM 2:**
Another question under 'Adsense Module' section, should the 'Setting' and 'Setup' be above the 'Use Snippet Switch' item?
<Details>
<img width="385" alt="Screenshot 2024-09-24 at 23 34 27" src="https://github.com/user-attachments/assets/caa38337-8c22-4b8d-a2aa-d6a5e56356c8">
</Details>

________________________________________________________________

**ITEM 3:**
Noticed a couple of instances where the lists are not alphabetically sorted.
Examples attached below. 
This is not an exhaustive but let me know if you require me to list all the different ones.

<Details>
<img width="389" alt="Screenshot 2024-09-24 at 23 38 30" src="https://github.com/user-attachments/assets/85e43a4f-3340-4be6-aa4c-e74137acc2d1">

<img width="399" alt="Screenshot 2024-09-24 at 23 40 25" src="https://github.com/user-attachments/assets/b4814246-cffb-42a4-adce-c1da1d1e0dd1">


</Details>

**Comment by benbowler** [comment]
Hey @kelvinballoo, I've taken a look into the issues here and they are related to the fact that we have some legacy stories stored in the `/stories/` folder. Updating these is out of the scope of this ticket so I've created a follow up here #9408.

**Comment by benbowler** [comment]
@kelvinballoo I missed the "folders at the top" point in the IB and execution. I spoke to @techanvil about this as he wrote the AC. Sorting with folders at the top needs a completely different implementation than this ticket so I've moved this to a follow up here: #9436

**Comment by mohitwp** [comment]
@benbowler Can I move this to approval ?

**Comment by benbowler** [comment]
@mohitwp yes you can. Everything mentioned above has now been captured in follow up tickets. Thanks.

**Comment by mohitwp** [comment]
### QA Update ✅ 

Feedback from @kelvinballoo will get address under #9436.
