### ISSUE TITLE
Use global instead of window in JS code

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#920]
Now that we're using Jest, we are running our plugin code in both Node and Browser environments. This hasn't actually created any issues yet, but I think it'd be nice to rely on Webpack's `global` variable instead of using `window` in plugin code and `global` in our Jest code—[as we currently do](https://github.com/google/site-kit-wp/pull/915#discussion_r351078788).

This is a somewhat aesthetic choice right now, though I think `global` more clearly expresses our usual intended use of `window`, and also makes the code a bit more flexible/idiomatic.

This would be a pretty easy search+replace of `window` in our code that is processed by Webpack.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Use `global` over `window` in JS code that will be bundled by Webpack.

## Implementation Brief

* Add a `no-restricted-globals` rule to our `eslintrc` encouraging usage of `global` over `window`:
```js
"no-restricted-globals": [
      "error",
      {
        "name": "window",
        "message": "Use 'global' instead."
      }
    ],
```
* Convert all existing instances of `window` to `global`.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@tofumatt Webpack turns this into `window` when bundling right?

**Comment by tofumatt** [comment]
Yup! Everything client-side will continue to work as-normal, but it means our code is a bit more portable for `jest`, etc. Plus it's just a bit more "standard" use of ES6. 🤷‍♂

**Comment by aaemnnosttv** [comment]
@tofumatt can we enforce this with an ESLint rule? I took a look at the core set but I don't see one for this. Is there maybe a third-party package that you know of that we could leverage?

**Comment by tofumatt** [comment]
An easy way might just be to disable usage of `window` as a global. But I'll have a quick look for anything a bit more codified/pre-made 😄

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
Regression tests on my local and Jurassic Ninja passed.

**Tested**

- Setup all services (between Jurassic Ninja and my Local)
![image](https://user-images.githubusercontent.com/57115907/73242529-17c6fb80-415a-11ea-9743-201ccbca9d8a.png)
![image](https://user-images.githubusercontent.com/57115907/73242652-6d9ba380-415a-11ea-8445-8a39d12a4201.png)

- Deactivated services, disconnected SK. No issues to note.


Passed QA ✅
