### ISSUE TITLE
Revert the Fix For VRT failures

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9200]
## Feature Description

Recently we implemented #7965 which was attempt to fix the failures in VRT, but since implementation, VRT is still consistent in failures, so we can consider reverting the edits done in linked issue, since it is not bringing expected improvements

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Closing in favor of #7965
