### ISSUE TITLE
Fix issue where VRT test fails in CI when launching Chromium

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9211]
## Bug Description

Unfortunately the experimental fix for our VRT workflow flakiness applied via https://github.com/google/site-kit-wp/issues/7965 doesn't seem to have improved its reliability and the workflow is still failing at a high rate during peak US/EU working hours.

VRT runs in CI are still intermittently failing before all the screenshots are captured, with the following error:

```sh
      COMMAND | Command "test" ended with an error after [542.215s]
      COMMAND | Error: Failed to launch the browser process!
```

## Steps to reproduce

- Watch for failing VRT test runs in CI.
- They will intermittently fail with the above error, particularly so during peak US/EU hours.
- See this example test run: https://github.com/google/site-kit-wp/actions/runs/10452867954/job/28942188022
## Screenshots

This error has been seen with a couple of permutations:

![image](https://github.com/user-attachments/assets/7e20cae7-3b15-4e8c-9613-3e42f3b312a8)

![image](https://github.com/user-attachments/assets/5b07e8a3-0cbb-402e-8afd-04c4bd09a56e)

![image](https://github.com/user-attachments/assets/efb7137c-7174-4dc2-b1be-45b2e193fb1a)

See this [Slack thread](https://fueled10up.slack.com/archives/CBKKQEBR9/p1724077599010909) for related discussion on the topic, including some suggested avenues for investigation:

- Ensure the installed version of Chromium matches the [preferred revision](https://github.com/puppeteer/puppeteer/blob/a654607c747dac0f0adc95d94a3ff585a5321d58/src/node/BrowserRunner.ts#L324) for the installed version of Puppeteer.
- Use a debugging pipe (`--remote-debugging-pipe`) instead of a port (`--remote-debugging-port`) so the [WebSocket setup code where the error is raised doesn't run](https://github.com/puppeteer/puppeteer/blob/a654607c747dac0f0adc95d94a3ff585a5321d58/src/node/BrowserRunner.ts#L258-L266).
- Upgrade our versions of Puppeteer/Backstop/Alpine etc.
- Try running on a [larger](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners) or a [self-hosted](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) runner.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* VRT test runs should not fail with an error before all the screenshots are captured and the test has run to completion.

Note, additional issues should be raised if needed to follow up on separate avenues of investigation.

## Implementation Brief

After substantial investigation, it seems this may be due to resource limitations when running the Docker container. See https://github.com/garris/BackstopJS/issues/537#issuecomment-339710797

* [ ] Merge https://github.com/google/site-kit-wp/pull/9213

### Test Coverage

* No changes; this addresses the ability of VRT to run until completion rather than the result

## QA Brief

* None needed; this can be reviewed during CR and iterated on if other issues persist. No plugin code is changed.

## Changelog entry

* Enhance stability of visual regression test runs.

**Comment by tofumatt** [comment]
Moving directly to Approval given no QA is required here.
