### ISSUE TITLE
Ensure the "Top content" CTA for creating the custom dimension appears when the corresponding report error shows the custom dimension is missing

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9218]
## Feature Description

The Audience Tile's "Top content" metric area has a CTA for creating the `googlesitekit_post_type` custom dimension if it doesn't exist.

However, it doesn't have logic in place to determine if the custom dimension doesn't exist when requesting the report for the metric. At present it's reliant on the list of available custom dimensions being synced _somewhere_, which only happens during Audience Segmentation setup, or in the Key Metrics feature.

We should ensure that, if the report for the "Top content" metric returns an error because the custom dimension doesn't exist, the list of custom dimensions is resynced so the tile will immediately know that the dimension is missing and show the CTA to create it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the reports for the Audience Tile's "Top content" metric return an error because the custom dimension doesn't exist:
  * For an authenticated user:
    * The list of available custom dimensions should be resynced.
    * The Audience Tiles should remain in the loading state while the resync is happening.
    * Once the resync has finished the populated tiles should show with the CTA for creating the `googlesitekit_post_type` present in the "Top content" metric area (already implemented via https://github.com/google/site-kit-wp/issues/8153).
  * For a view-only user, the "Top content" metric area should not be displayed.
    * This is because a view-only user doesn't have permission to sync custom dimensions, and we are not going to show the "Top content" metric to them if the custom dimension doesn't exist (see https://github.com/google/site-kit-wp/issues/8175), so the logical thing to do here is not to display the metric area if the custom dimension state can't be determined.

## Implementation Brief

**Add Missing Custom Dimension to Top Content Report**
 - [ ] Add the `googlesitekit_post_type` dimension filter to the top content report options: 
```
 dimensionFilters: { 
 	'customEvent:googlesitekit_post_type': { 
 		filterType: 'stringFilter', 
 		matchType: 'EXACT', 
 		value: 'post', 
 	}, 
 }, 
```
https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/modules/analytics-4/hooks/useAudienceTilesReports.js#L322-L329
https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/modules/analytics-4/hooks/useAudienceTilesReports.js#L346-L353

**Authenticated User Context**
* [ ] Update `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTiles.js` (note the new `useAudienceTilesReports` custom hook merged in #8144):
   * [ ] Add a `useEffect` with `topContentReportErrors` as a dependency.
      * [ ] Check if the `topContentReportErrors` contains any invalid custom dimension errors using the `.find` prototype, and use the [`isInvalidCustomDimensionError` util](https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/assets/js/modules/analytics-4/utils/custom-dimensions.js#L51-L64) to identify this error type.
      * [ ] If an invalid custom dimension error exists, dispatch the action `fetchSyncAvailableCustomDimensions`.
   * [ ] Create a new boolean constant `isSyncingAvailableCustomDimensions ` containing the value of the `isFetchingSyncAvailableCustomDimensions` selector:
   https://github.com/google/site-kit-wp/blob/56feb1f6ca227cc9fc6da3511a96fb2f4bf9d3b0/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js#L94-L96
      * [ ] Update the loading statement to include `isSyncingAvailableCustomDimensions `:
      https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTiles.js#L419-L427
 * [ ] Filter out invalid custom dimension errors from `topContentReportErrors` and `topContentPageTitlesReportErrors` here, using the [`isInvalidCustomDimensionError` util](https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/assets/js/modules/analytics-4/utils/custom-dimensions.js#L51-L64), so that the Top Cities Audience Tile will be rendered if there is only an invalid custom dimension error:
 https://github.com/google/site-kit-wp/blob/b2d47c854a1c23eaba82690c88812972ba730bed/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTiles.js#L321-L322

**View-Only Context**

 - [ ] Update `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.js`, use the `getErrorForSelector` selector to get any errors for the [top content report](https://github.com/google/site-kit-wp/blob/b2d47c854a1c23eaba82690c88812972ba730bed/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTiles.js#L217-L224) for the [audienceResourceName of the current tile](https://github.com/google/site-kit-wp/blob/b2d47c854a1c23eaba82690c88812972ba730bed/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTiles.js#L253).
    - [ ] Update this conditional block to *not* render the Top Cities metric if the user is in the view-only context and the there is a invalid custom dimension error for the Top Cities report:
    https://github.com/google/site-kit-wp/blob/b2d47c854a1c23eaba82690c88812972ba730bed/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.js#L261

### Test Coverage

* Update the tests that fail due to the addition of the custom dimension filter for the Top Content queries.
* Create a VRT when the tile is in the view-only context with an invalid custom dimension error for the Top Content report.

### Authenticated user

- Set up Site Kit with the `audienceSegmentation` feature flag enabled and Analytics connected to a property which is out of the "gathering data" state.
- Click on **Enable groups** to set up Audience Segmentation.
- Archive the `googlesitekit_post_type` custom dimension in Analytics.
- Return to Site Kit and clear session storage: `sessionStorage.clear()` in the JS console.
- Refresh the dashboard.
- Error messages including the phrase "Field customEvent:googlesitekit_post_type is not a valid dimension." will appear in the JS console, this is to be expected.
- A POST request to the `sync-custom-dimensions` endpoint should appear in the network devtools.
- The **Update** CTA should appear in the "Top content" metric area in the Audience Tiles.

### View-only user

- Having run through the steps above, share Analytics and login as a view-only user with access to the module.
- The "Top content" metric area should not appear in the Audience Tiles.

## Changelog entry

* Ensure the "Top content" CTA for creating the `googlesitekit_post_type` custom dimension appears in the main dashboard when the corresponding report error indicates the missing custom dimension.

**Comment by techanvil** [comment]
Hi @benbowler, thanks for drafting this IB. A couple of points:

- Thinking about https://github.com/google/site-kit-wp/issues/8175, I've realised there's an edge case for view-only users that we should handle in this issue, although it wasn't explicitly captured in the AC. I hope you don't mind, but I've amended the AC to include this.

> ... selectors to monitor `syncAvailableCustomDimensions` selector/resolver like so:

- As we're dispatching the `fetchSyncAvailableCustomDimensions()` _action_, this doesn't seem right. We'll probably want to use `isFetchingSyncAvailableCustomDimensions()`, e.g.:

https://github.com/google/site-kit-wp/blob/56feb1f6ca227cc9fc6da3511a96fb2f4bf9d3b0/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js#L94-L96

**Comment by techanvil** [comment]
Hi @benbowler, thanks for updating the IB. A few more points:

For the view-only context:
- We shouldn't need to check `isSyncingAvailableCustomDimensions` in the `AudienceTile`, component because the `AudienceTileLoading` component [will be rendered instead](https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTiles.js#L493-L504) due to including this value in the loading condition.
- We need to filter out invalid custom dimension errors from the list that determines the `individualTileErrors` value, in order to avoid showing the whole tile in the error state, but still need to flag that there was an invalid custom dimension error to the `AudienceTile` so it can avoid rendering the "Top content" metric area.

More fundamentally, though - I've noticed the `googlesitekit_post_type` custom dimension is actually missing from the "Top content" report options:

https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/modules/analytics-4/hooks/useAudienceTilesReports.js#L322-L329

https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/modules/analytics-4/hooks/useAudienceTilesReports.js#L346-L353

It needs to be added as a dimension filter, like we do here, but with `value: 'post'`:

https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/modules/analytics-4/components/widgets/PopularProductsWidget.js#L79-L85

This will be needed for this issue to be complete and testable, so we should include the fix here too. There's likely to be a number of tests that need updating as a result which we should factor into the estimate.

**Comment by benbowler** [comment]
I chose to use the `getErrorForSelector` selector within the `AudienceTile` component instead of adding another new prop to this component, we could instead create a new prop such as `hasTopContentCustomDimensionError` instead if prefered.

I've increased the estimate a couple of bands because the scope has expanded slightly as we've discussed required fixes/additions to be able to work on this ticket.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Hi @techanvil , I followed the steps but it doesn't seem like it's working as expected. 

- I've archived googlesitekit_post_type custom dimension in Analytics.
- I used the tester plugin with the following settings
   <Details>
   <img width="778" alt="Screenshot 2024-09-26 at 01 04 24" src="https://github.com/user-attachments/assets/bb55825b-3bc1-4f3d-ab16-f9099c078114">
   </Details>
- However, after running the clear session storage line and refreshing, nothing really changes.
- Video is attached for reference:
   <Details>

   https://github.com/user-attachments/assets/214b2e11-ce8a-48e2-9cfd-cd8dfa384ac3

   </Details>

Let me know in case I missed any steps.

**Comment by techanvil** [comment]
Hey @kelvinballoo, maybe I should have mentioned this in the QAB, but you won't be able to test this issue with the Tester plugin configured to provide mock report data. This is because the underlying code relies on the error response returned by the real request for the "Top content" data once the custom dimension has been archived.

You should be able to test this with any property which is legitimately out of the gathering data state. Please give it another try and let me know if you run into any further problems.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Hi @techanvil , thanks.
I managed to test it with a site, despite having 0 data, it was out of the gathering state.
I was able to get the 'Update' button and in dashboard sharing view mode, the "Top content" metric area did not appear in the tiles. ✅ 

Clicking on 'Update' on the admin dashboard: ✅ 
- recreated the googlesitekit_post_type custom dimension in Analytics
- Update button no longer appears in admin dashboard
- Top content metric area re-appears on dashboard sharing

This is working as expected.
Moving ticket to approval.

<Details>

https://github.com/user-attachments/assets/208a0c6b-9a9b-47ef-8416-bb1306822c93

https://github.com/user-attachments/assets/c9530fea-08bc-4fa3-9d2b-f1946b518605



</Details>
