### ISSUE TITLE
Allow WordPress Subdirectory Setup with WordPress Address (URL) and Site Address (URL) with different values

### ISSUE THREAD

**Issue by nroccogit** [google/site-kit-wp#922]
Hi,
from here:
https://sitekit.withgoogle.com/documentation/fix-common-issues/
I can read:
"Verify that your **WordPress Address (URL) and Site Address (URL) values match**. If you have an HTTPS website, make sure that both URLs have an HTTPS prefix. "

So I think the plugin doesn't works with WordPress running on a subdirectory install:
https://wordpress.org/support/article/giving-wordpress-its-own-directory/

I suggest to make it work in a setup like this:
- SITE ADDRESS => www.mydomain.com
- WORDPRESS ADDRESS => www.mydomain.com/wordpress
where
- public homepage is on www.mydomain.com
- website admin access is on www.mydomain.com/wordpress/wp-admin

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@nroccogit Have you actually tried this? Site Kit and its authentication service have been built to support a WordPress URL that points to a subfolder, so it should work. Let me know if you're running into issues despite it.

It's a good point that the documentation there maybe is a bit too much. The important things are actually:
* Make sure that WordPress address and site address start with `https://` if your domain is on HTTPS.
* Make sure that WordPress address and site address are using the same domain. It is okay for the WordPress address to be somewhere else as long as it is relative to the site address.

**Comment by Saeglopur** [comment]
> * Make sure that WordPress address and site address are using the same domain. It is okay for the WordPress address to be somewhere else as long as it is relative to the site address.

It's still the same, I have that issue too. Site Kit is using Wordpress URL and after whole process it ends in URL of that subdirectory so it throws 403 error. In my case Site Kit was installed before I've changed Site URL to cardroid.pl, will roll back to that and will see. I don't want to reinstall because one person was already logged in with it.

![Annotation 2020-01-14 003910](https://user-images.githubusercontent.com/7388636/72301195-6064bc00-3666-11ea-966b-be0725f79c6a.jpg)

**Comment by felixarntz** [comment]
This issue shouldn't be relevant anymore; using Site Kit with WordPress in a subdirectory of the home URL has been possible for more than a year now.
