### ISSUE TITLE
Gathering data notification - Loader not appearing on 'See other services' CTA click

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#9225]
## Bug Description

When clicking 'See more services,' the loader does not appear, and the user is taken to the Settings > Services tab after a few seconds. In the latest environment, the loader does appear. We have increased the speed, but the loader should be displayed as it is in the latest environment.

## Steps to reproduce

1. Set up site kit.
2. Click on 'See more services' CTA of gathering data notification on main dashboard.

## Screenshots

https://github.com/user-attachments/assets/bf94978c-1406-4a13-bd3f-5e50c800a837

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a CTA is clicked for any refactored banner notification that dismisses the notification and takes the user to a different page, then: 
  * the notification should not be immediately dismissed and removed from the page until the navigation to the new page is complete
  * the CTA button should be in a loading state (spinner icon) during this time
* This currently only applies to the `GatheringDataNotification` component - however, functionality should be introduced to cover similar behaviour for any other notification that will be refactored using the new infrastructure.

## Implementation Brief

Note: Since the Notifications API is implemented, the dismissal will also remove notification from `getQueuedNotifications` selector which removes notification immediately. Before this was handled in `BannerNotification` component, which would determine if notification should be hidden using class property, which would account for `isNavigatingToCTALink`. With new API, this happens before `isNavigatingToCTALink` is signalled opposite to this being checked during the render.

* [ ] Update `dismissNotification` action https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/googlesitekit/notifications/datastore/notifications.js#L145 
  * It should include additional property in `options` object - `skipHidingFromQueue` for example.
  * Then wrap the internal dismissal from queue https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/googlesitekit/notifications/datastore/notifications.js#L149-L153 in conditional check, so it is not invoked if  `options.skipHidingFromQueue` is present.
* [ ] Update `assets/js/googlesitekit/notifications/components/common/CTALink.js`
  *  Update https://github.com/google/site-kit-wp/blob/119747b9e3be9bb8310faec37b7ea41c6b4ea89f/assets/js/googlesitekit/notifications/components/common/CTALink.js#L73 to include `skipHidingFromQueue` option
  * `CTALink` component is used only for notification that have CTA leading to another page/website so this will resolve issue for other notifications with same behaviour in the future when they are refactored

### Test Coverage

* Update `assets/js/googlesitekit/notifications/datastore/notifications.test.js`, by adding test case to verify that `dismissNotification` does not remove notification from queue when `skipHidingFromQueue` option is passed

## QA Brief

* Follow steps to reproduce
* Verify that banner is not disappearing immediately, but showing a loading state on the button when redirecting
* Verify this behaviour does not affect other type of banners, that should disappear immediately

## Changelog entry

* Add ability to remove a notification on next page load.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified when only SC is in gathering data state.
- Verified when only Analytics is in gathering data  state.
- Verified when both SC and analytics are in gathering data state.
- Verified that banner is not disappearing immediately, but showing a loading state on the button when redirecting.
- Verified this behaviour does not affect other type of banners, they disappear immediately.

<details>


https://github.com/user-attachments/assets/2f2d0d58-d87c-46e4-b1de-3c270d0a0735

</details>
