### ISSUE TITLE
`a.getTime is not a function` error on WP dashboard

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9226]
## Bug Description

On a site in a zero data state for Search Console and Analytics, the Site Kit widget on the WordPress dashboard is showing an error:  **a.getTime is not a function** 

A support ticket on this was also reported :
https://wordpress.org/support/topic/problem-a-gettime-is-not-a-function/

## Steps to reproduce
This was tested on 1.133.0 (latest release), using tester plugin 1.13.1 Beta to enforce zero data states

- After setting up Site Kit, the error appears on the dashboard
- Same observations if I test under 1.13.0 tester plugin and also if I test under develop branch.

## Screenshots

<img width="735" alt="Screenshot 2024-08-21 at 19 23 23" src="https://github.com/user-attachments/assets/ea2caca9-9ac7-44b4-b3f5-488705c42d0d">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Unique Visitors chart within the Site Kit Summary dashboard widget should not error in a zero data scenario

## Implementation Brief

* Update the condition in the chart when the report is zero data to provide a `Date` instance rather than the string reference date. This changed in 1.130.0 with changes to the reference date selector but was missed because the string was being handled automatically in other places where needed 
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/6750cefd-be26-4c5a-a61f-b11bda65ed13">
* Merge https://github.com/google/site-kit-wp/pull/9353

### Test Coverage

* No changes

## QA Brief

* To reproduce, connect GA with a property in zero data state and view the SK widget on the WP dashboard
* This issue is specific to the zero data state – it isn't observable in a gathering state

## Changelog entry

* Fix unexpected error in Site Kit WordPress dashboard widget for sites in zero data states.

**Comment by wpdarren** [comment]
### QA Update: 

**Verified:**

- Recreated the issue reported on the latest release.  Then switched to the develop branch and I can see the WP Dashboard widget for Site Kit now functions as expected.  Checked the UX/UI and all looks fine. 
- An additional test, I also checked the admin toolbar to ensure that the Site Kit menu option works as expected there too.

![image](https://github.com/user-attachments/assets/deca756a-c2f5-4daf-8fbe-a93721bcf54d)
