### ISSUE TITLE
Zero Data Notification Not Appearing consistently - on First Load in New Tab/Window

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#9227]
## Bug Description

If the zero data notification is not dismissed and the user opens the dashboard in a new tab or window, the zero data state notification does not appear on the first load. The user must refresh the page for the notification to appear. This behavior is observed on both the main and entity dashboards. However, this issue does not occur with the gathering data state notification.

### Steps to reproduce

1. Set up Site Kit with Analytics.
2. Make sure both Analytics and Search Console are in zero data state.
3. Open main dashboard in new tab.
4. Notification will not appear.
5. Now refresh the page.
6. Notification will appear after refresh.

### Screenshots

https://github.com/user-attachments/assets/64238b26-4ac3-453a-8e06-d1f7509a93f8

### Steps to reproduce

1. Set up site kit without Analytics connected.
2. Ensure Search Console is in Zero Data state.
3. Load the main dashboard.
4. ZeroDataNotification does not appear consistently (appears sometimes).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Zero Data Notification should appear in all scenarios that it appeared in, at or before Release 1.133.0, eg:
  * When Search Console is in Zero-data state and GA4 is disconnected.
  * When both, Search Console and GA4 are in Zero-data state.
* The above should be true:
  * When the dashboard is loaded the first time (no page reload should be necessary)
  * When the dashboard is loaded in a new tab

## Implementation Brief

* [ ] Update `assets/js/googlesitekit/notifications/register-defaults.js`
  * `hasZeroData` selector is calling another resolver `getReport`, which is not resolved in most of the cases when `checkRequirements` is run, hence banner is not shown in most cases, except for the initial load when report is resolved in the state, but after reload banner will disappear - which shouldn't be the case. So replace https://github.com/google/site-kit-wp/blob/8117ca79f8026064d8fd60d30f860617f597130b/assets/js/googlesitekit/notifications/register-defaults.js#L276 and https://github.com/google/site-kit-wp/blob/8117ca79f8026064d8fd60d30f860617f597130b/assets/js/googlesitekit/notifications/register-defaults.js#L270 with the usage of `isZeroReport` directly, and use `resolveSelect` to make a report request directly and wait for it to be resolved.
    * Use directly https://github.com/google/site-kit-wp/blob/8117ca79f8026064d8fd60d30f860617f597130b/assets/js/modules/search-console/datastore/report.js#L215-L219 for both Search Console and Analytics, and replace the pointed selector with direct usage of `isZeroReport` from the modules.

### Test Coverage

* No update needed

## QA Brief

* Follow steps to reproduce and ensure that the zero data notification banner works correctly now.

## Changelog entry

* Ensure Zero Data notification always appears in new banner notifications.

**Comment by jimmymadon** [comment]
@mohitwp I have added another Scenario 2 as well with the latest main branch here.

**Comment by mohitwp** [comment]
@jimmymadon Regarding issue number 2, I’ve observed that the "zero data" notification appears upon reload if both Analytics and SC are connected. However, if only SC is connected and is in a zero data state, the notification appears only once. It does not reappear upon reload or if we log in from another browser or open the dashboard in a new tab.
I will add this scenario under #9227. Same issue exist on latest environment also.

<details>


https://github.com/user-attachments/assets/64222246-a799-44e6-8d98-943f5003f4e8

</details>

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested when SC is in zero data state.
- Tested when both SC and analytics are in zero data state.
- Verified that zero data notification appear when dashboard loaded for the first time.
- Verified that zero data notification appear when we open dashboard in a new tab.
- Verified that zero data notification appear on 'view only ' and 'entity dashboard'. 
- Verified clicking 'Remind me later' CTA dismiss the notification.


<details>

![image](https://github.com/user-attachments/assets/fda1f4dc-8763-40cb-aee1-9c7c5fc9a022)


https://github.com/user-attachments/assets/eba10187-40f2-412e-8dda-11b38bd01597

</details>
