### ISSUE TITLE
E2E jobs sometimes fail and succeed after restart

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#923]
## Bug Description

The E2E tests often fail in Travis referencing issues with a page navigation/lack of page context, or other seemingly timeout-related issues. Even testing on severely CPU-throttled instances I've not been able to recreate this on my Mac, and have seen similar intermittently failing tests on Gutenberg (which uses the same E2E tools and a similar setup) on Travis.

I'm suspicious that this could be something specifically related to the Travis platform, and would be curious about transitioning (at least) the E2E tests away from Travis. To debug this, the best option is to run the E2E tests both on Travis and another platform—GitHub Actions seems the obvious choice here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Given the same source code and dependencies, an E2E test job should consistently pass or fail
* E2E test jobs should be resilient to inconsistencies between runs which are beyond our control (e.g. current date)

## Implementation Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
Disappointingly, these seem to have failed on GitHub Actions in a similar manner: https://github.com/google/site-kit-wp/pull/926/checks?check_run_id=323496282

The GitHub Actions for that run appeared to start earlier and run a bit faster, which is promising in an unrelated point, but it seems this is down to the actual testing setup and not the CI we're using…

**Comment by tofumatt** [comment]
Interestingly, Travis failed on the same job: https://travis-ci.com/google/site-kit-wp/jobs/261088031

**Comment by aaemnnosttv** [comment]
As discussed on the call today, there are a few packages that we may be able to leverage to deal with false positives due to random failures:

* https://www.npmjs.com/package/jest-retry  
This one looks the most promising at first glance
* https://www.npmjs.com/package/jest-retries  
Looks like it could work as well, but seems to require wrapping each test with a new `retry` function

**Comment by felixarntz** [comment]
@aaemnnosttv Is this still relevant after the recent fixes you've added?

**Comment by aaemnnosttv** [comment]
Stability is much better now indeed, but I have seen a few failures. It might be worth keeping this issue around for tracking but as for the retry stuff, I don't think that will be necessary.

**Comment by aaemnnosttv** [comment]
I'm going to take ownership of this one. E2E tests are more/less stable now (much more than before) but I've seen a few failures from time to time, usually around the date selector or post search. I would say the builds pass 49/50 times right now (at least on Travis). Let's keep this open a little longer and see if these last instabilities can be identified and fixed.

**Comment by aaemnnosttv** [comment]
Updating this one to be specific to remaining random failures as they no longer _often_ fail, but do 1/3 fail sometimes when they shouldn't and pass on after running again.

**Comment by aaemnnosttv** [comment]
Closing this as things are currently quite stable as decided during planning today. Will reopen a new issue if necessary.
