### ISSUE TITLE
Fix glitches in the Audience Segmentation Setup CTA Banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9231]
## Bug Description

There are a couple of glitches relating to the Audience Segmentation Setup CTA Banner.

1. The "Don't show again" dismissal CTA flashes in place of the "Maybe later" CTA.
2. The Setup CTA Banner shows again when the No Audiences Banner is visible.

These should be small fixes and can be addressed in this single issue.

### The "Don't show again" dismissal CTA flashes in place of the "Maybe later" CTA.

1. Set up Site Kit with the `audienceSegmentation` feature flag enabled and Analytics connected.
2. Refresh the dashboard to show the Setup CTA Banner.
3. The dismissal CTA will briefly show the "Don't show again" text in place of "Maybe later".
4. Run through the setup process and the same glitch will occur while the "Enabling groups" CTA is showing.

### The Setup CTA Banner shows again when the No Audiences Banner is visible.

1. Set up Site Kit with the `audienceSegmentation` feature flag enabled and Analytics connected.
2. Set up the Audience Segmentation feature with the "new visitors" and "returning visitors" audiences selected.
3. Archive the audiences in Analytics (or hide them using the Tester plugin).
4. Refresh the dashboard and open the Selection Panel to trigger an audience resync.
5. See the Setup CTA Banner unexpectedly return, while the No Audiences Banner is displayed as expected.

### The "Don't show again" dismissal CTA flashes in place of the "Maybe later" CTA.

https://github.com/user-attachments/assets/1a79dabc-9986-4341-86a0-82e3db1bba76

### The Setup CTA Banner shows again when the No Audiences Banner is visible.

![enable_groups_with_no_audiences](https://github.com/user-attachments/assets/a9a2f9a0-0fab-4043-9638-876dfb7ad6ea)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: pre-release 1.134.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Don't show again" dismissal should not flash in place of the when the "Maybe later" CTA as described in the steps to reproduce.
* The Setup CTA Banner should not appear when the No Audiences Banner is visible.

## Implementation Brief

- [x] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js`
  * Add an additional check `dismissCount === undefined` [here](https://github.com/google/site-kit-wp/blob/59a424e013ece675920856b83b7fccbecae694c9/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L184-L191), so that if `dismissCount` is `undefined`, the component returns `null`. This will make sure that dismissed prompts data is loaded before the banner is displayed.

  * For the `useEnableAudienceGroup` hook, pass the `onSuccess` callback such that it should call `dismissPrompt` and pass slug as `AUDIENCE_SEGMENTATION_SETUP_CTA_NOTIFICATION` and `expiresInSeconds` as zero (permanent dismissal). Make the `onSuccess` callback `async`.

### Test coverage

* Add tests for `dismissCount` and `onSuccess` behaviour in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js`

## QA Brief

* Issue should no longer be visible using `Steps to reproduce` steps.

## Changelog entry

* Fix glitches relating to the Audience Segmentation Setup CTA Banner.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This was verified good. Moving ticket to Approval.

- There was no glitch observed in the 'Maybe Later' button upon the first reload and also after clicking the 'Enable Groups' and go through the oAuth flow.
- The setup CTA banner did not reappear after the audience sync when opening the audience selection panel.

<Details>

https://github.com/user-attachments/assets/4a507f51-0fa8-46af-8aa7-560770382c24

</Details>
