### ISSUE TITLE
PAX application not loading correctly on the Ads setup screen.

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9237]
## Bug Description

An issue has occurred where the PAX app is not appearing within the iframe, and is now appearing underneath the WordPress footer.   This means that users will not be able to create the ad campaign unless they scroll down the page.  

![pax](https://github.com/user-attachments/assets/77dfc53a-7d24-4d8e-8afb-f98d30e869d0)

## Steps to reproduce

1. Set up.a site with the PAX pilot plugin (you can use the template in InstaWP) 
2. Go to Settings > `Connect More Services` and select the `Ads` module. 
3. Within the setup screen, click on the `Create an account` CTA
4. Wait for 20-25 seconds, the app won't load in the iframe but scroll down and you wil see it displayed. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When using the PAX Pilot Plugin, or with the appropriate `adsPax` feature flag enabled, the PAX application should successfully render within the Ads Module setup container, not outside of it.

## Implementation Brief

* [ ] Update the versions of both the PAX integrator script and PAX SDK npm package to the latest versions, 1.0.12 at the time of writing:
    * [ ] Within `includes/Modules/Ads.php`:
        * [ ] Locate the pax integrator script URL, `https://www.gstatic.com/pax/1.0.9/pax_integrator.js`, and update it to be the latest 1.0.12 version: `https://www.gstatic.com/pax/1.0.12/pax_integrator.js` 
    * [ ] Within `package.json`:
        * [ ]  Locate the `google-pax-sdk` dependency entry, update it to match the integrator version, `1.0.12`

### Test Coverage

* No tests needed for this fix.

## QA Brief

* Using either the PAX Pilot plugin or by enabling the `adsPax` feature flag:
    * Validate that PAX application loads within the Ads set up area 
    * Validate that the PAX application and setup process works as intended from account creation to account ID storage within Site Kit
        * This can be validated by setting up Ads using PAX, and making sure the Ads conversion ID and account ID are stored within the Ads Settings area after completion  

## Changelog entry

* Update the PAX library version.

**Comment by tofumatt** [comment]
ACs are good and IB ✅ as well. Moving this right to CR. 👍🏻

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified issue is resolved and now PAX application loads within the Ads set up area.
- Verified PAX application set up flow is working fine.

<details>


https://github.com/user-attachments/assets/1e016432-4cb2-46fb-a2b3-d9d660f9f595


</details>
