### ISSUE TITLE
Lint commit messages in CI

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#925]
## Feature Description

@felixarntz mentioned that we should have commit messages that adhere to the following guidelines:

* Commit messages should start with an infinitive verb (present tense) and an uppercase letter (e.g. "Fix something." instead of "fix something." or "fixed something.").
* Commit messages should end in a dot (e.g. "Fix something." instead of "Fix something").

It would be good to codify this into a pre-commit hook using Husky and also a CI check that informs users of bad commit messages. This will ensure we're consistent going forward, as it's easy to forget these sorts of things (especially if you're an outside contributor or English is not your first language).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a pre-commit hook that checks commit messages for the following:
    * Message starts with a capital letter.
    * Message ends in a dot.
    * First word of the message does not end in "ed" or "es". See explanation below.

This is certainly not reliable but should work well for us. While English language verbs are too irregular to reliably lint for a regular present tense form, this gives us a good chance to catch wrong forms. It wouldn't cater for irregular past tense forms like "thought" or the very common "just-append-an-s" form (e.g. "commits"), but that is okay. The only real problem here would be present tense forms that actually end in "ed" or "es" and would be flagged as false positives. But there are only few words that that applies to and we're probably never going to use them here ("Shed a tear about how messy this code was before." is not really a commit message 😄). The false positives problem is also why we can't check for words ending in an "s" - while there are tons of cases like that we would catch, there are also too many regular verbs that end in "s", so this would probably end up more a pain than a help.

If this particular rule becomes a problem with false positives we didn't anticipate, we can always re-assess.

## Implementation Brief

* Create `check-commit-msg` file in the `/bin` folder and add the following to the script:
   * Add php shebang and change file permissions to make the file executable.
   * Take a command line argument with index `1` and check if such file exists. If the file doesn't exist, display an error and exit with a non-zero code. Otherwise read the file content into a variable - it will contain the current commit message.
   * Remove all lines which start with `#` from the commit message, concatenate lines and trim all whitespaces and technical characters from the beginning and the end of the resulting message.
   * Verify that resulting string ends with a dot. If not, display an appropriate error message and exit with a non-zero code.
   * Verify that resulting string starts with a capital letter. If not, display an appropriate error message and exit with a non-zero code.
   * Verify that the first word of the resulting string does not end in "ed" or "es". If not, display an appropriate error message and exit with a non-zero code.
   * At the end do not output anything and exit with a zero code.
* Add `commit-msg` hook with `./bin/check-commit-msg $HUSKY_GIT_PARAMS` command to the husky hooks list located in the `package.json` file: https://github.com/google/site-kit-wp/blob/c776b09354e40612462c88fa6128e6878c24f172/package.json#L58-L60

See this comment as an example: https://github.com/google/site-kit-wp/issues/925#issuecomment-640544853

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
Here is a husky hook that checks whether a commit message ends with a dot:

```
"husky": {
  "hooks": {
    "commit-msg": "test \"$(cat $HUSKY_GIT_PARAMS | sed '/^#/d' | tr '\r\n' ' ' | sed 's/ *$//g' | sed 's/.*\\(.\\)$/\\1/g')\" = \".\" || (echo '\\033[31mThe commit message must end with a full stop.\\033[0m' && exit 1)"
  }
}
```

**Comment by felixarntz** [comment]
@eugene-manuilov Nice, I like the approach of Husky hooks with a file like this - would be great if you could expand to an implementation brief with the overall approach.

cc @aaemnnosttv

**Comment by eugene-manuilov** [comment]
@felixarntz IB has been added. Does it look good to you or want me to change something there?

**Comment by aaemnnosttv** [comment]
Can we put the file in `/bin`? I don't think it really belongs in the root unless there is a reason why it must be there.

**Comment by eugene-manuilov** [comment]
> I don't think it really belongs in the root unless there is a reason why it must be there.

We have `scoper.inc.php` in the root folder. It is a helper script that we use to update php dependency namespaces, right? I followed the same logic for `check-commit-msg.php` file.

> Can we put the file in /bin? I don't think it really belongs in the root...

It doesn't belong to executable files either... We can probably create another folder for this kind of scripts and call it something like `helpers` or `utils`... What do you think @aaemnnosttv and @felixarntz ?

**Comment by aaemnnosttv** [comment]
> We have `scoper.inc.php` in the root folder. It is a helper script that we use to update php dependency namespaces, right? I followed the same logic for `check-commit-msg.php` file.

That's little bit different as it's not so much of a helper script as it is a configuration file for php-scoper. Config files are okay to be in the root, but this one is possible to relocate so it perhaps shouldn't be in the root either 🙂 

> It doesn't belong to executable files either... 

I think perhaps this directory is being used in a non-standard way as it is as I don't think the WP CLI command classes or `local-env` really belong there, whereas `check-commit-msg` would be a better fit IMO as it is essentially an executable, implemented as a PHP script.

It could be an executable file with a shebang that points to php could it not?
```
#!/usr/bin/env php
<?php // ...
```

I'm open to other ideas here. My main concern is that things have a clear location that they belong to and that we should avoid adding extra files or directories to the root that aren't needed. Perhaps reorganizing existing files is beyond the scope of this issue here, but I think there is room for improvement here.

Thoughts @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv @eugene-manuilov I just opened #1677 to move the WP CLI commands out of the `bin` directory, it's ready for IB review. I think with this, we can then put the new commit lint script into `bin`.

**Comment by eugene-manuilov** [comment]
Thanks @felixarntz! IB is updated to use /bin folder for the script.

**Comment by aaemnnosttv** [comment]
IB looks good to me. The only thing I think we should change there is that if `check-commit-msg` is an executable script with a php shebang, it doesn't need to have a `php` file extension. It can simply be an executable file with no extension, such as [`composer`](https://github.com/composer/composer/blob/master/bin/composer) or [`phpunit`](https://github.com/sebastianbergmann/phpunit/blob/master/phpunit). The fact that it uses PHP internally is an implementation detail 🙂 

I'll update this one thing in the IB, and this is good to go 👍 

IB ✅

**Comment by tofumatt** [comment]
This works as expected, very cool! QA ✅
<img width="465" alt="Screenshot 2020-06-23 at 18 39 19" src="https://user-images.githubusercontent.com/90871/85436367-dc055600-b580-11ea-8d0c-f191b61cdf6e.png">
<img width="707" alt="Screenshot 2020-06-23 at 18 38 13" src="https://user-images.githubusercontent.com/90871/85436288-b5dfb600-b580-11ea-8347-852719ec2412.png">

I noticed we don't set a limit on commits, but fair enough. Moving to approval.

**Comment by ryanwelcher** [comment]
@felixarntz I ran into an issue with this when merging changes from `develop` into my local. The commit message that is auto-generated by git does not contain a `.` at the end and so the merge is not completed:
<img width="541" alt="ryanwelcher_Ryans-MBP____wp-local-docker-sites_googlekitlocal-10uplabs-com_wordpress_wp-content_plugins_google-site-kit" src="https://user-images.githubusercontent.com/1259027/86016261-91f0fa00-b9f0-11ea-8c75-715528cef6e5.png">

We can use the `--no-verify` flag to bypass this but it would be better if we added an exception to the linter.

Did you want to move this ticket back into Execution or create a new follow-up issue for this?

**Comment by felixarntz** [comment]
Let's open a PR against this issue to address it, no need for a separate issue. 👍

**Comment by aaemnnosttv** [comment]
Assigning this one back to @eugene-manuilov for the follow-up.

@eugene-manuilov we want to allow for merge commits as these don't adhere to our general rules for commit messages, but that's okay for this case.

**Comment by tofumatt** [comment]
Augmenting the commit messages is a clever solution, but originally I worried this would fail when GitHub merges were used. But I suppose since we only lint during pre-commit hooks it's fine. This solution results in inconsistent merge commit messages between GitHub's web UI (where we do a lot of merging) and local machines.

That said: it doesn't error so it works. QA ✅
