### ISSUE TITLE
Change font colours to be consistent on RRM setup screens

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9256]
## Bug Description

When setting up Reader Revenue Manager,  we have two font colors on the setup screen when there are no publications. Discussing this with Sigal in Asana, we've decided to make the font colours the same on the setup screens like we did on [this step](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=171-3296&node-type=FRAME&t=Gn6UyjoETX5SnhRL-0) of the workflow.   Sigal has updated the figma designs to reflect this. 

Discussion in Asana can be [found here](https://app.asana.com/0/1207894970935603/1208146362275128/f). 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The descriptive text on the ["no publications" variant of the RRM setup screen](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-setup-setupmain--no-publications) should all be the same color, `surfaces/on-surface` (`#161b18`).
* When updated, the screen should look like this:
![image](https://github.com/user-attachments/assets/8b77bbe2-f42b-4850-9767-1c34de2aa453)

## Implementation Brief

- In `_googlesitekit-rrm-setup-module.scss`, remove the `$c-surfaces-on-background-variant` from the `googlesitekit-setup-module__description` class:
https://github.com/google/site-kit-wp/blob/8629939d3775e26ea5e28a2c11d611005d010486/assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-module.scss#L52-L53

### Test Coverage

* Update the relevant VRT images.

## QA Brief

* Reset and setup RRM, confirm the font colors match the image above when reaching the setup screen.

## Changelog entry

* Update text colour in Reader Revenue Manager publication creation screen.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This is verified good.
The descriptive text is now (#161b18) on both lines at the 'No Publications' variant step 1. 
Also reviewed step 2 to ensure it's still the same.

Moving ticket to Approval.

<Details>
STEP 1:

<img width="1078" alt="Screenshot 2024-09-09 at 21 14 00" src="https://github.com/user-attachments/assets/5d3ca507-73db-47e8-ac3c-5ecc2365d4ad">
<img width="1244" alt="Screenshot 2024-09-09 at 21 14 07" src="https://github.com/user-attachments/assets/82c49f94-551b-483a-98b3-c2556b1fdf78">

STEP 2:
<img width="1243" alt="Screenshot 2024-09-09 at 21 17 20" src="https://github.com/user-attachments/assets/7089976c-ae4a-48d6-9c59-4505fb0e3a69">


</Details>
