### ISSUE TITLE
Setup CTA Banner doesn't follow the multiple dismissal/settings tooltip pattern

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9257]
## Bug Description

The Setup CTA banner has a "Maybe later" dismissal CTA. Pressing this dismisses the banner permanently without further information as to where the feature can be set up later. It would be good for the banner to follow the pattern we've introduced whereby:  The banner is reshown after a delay (e.g. two weeks), either two or three times, with the dismissal CTA changing to "Don't show again" on the final showing. Upon pressing the dismissal CTA, a tooltip is shown pointing to the Settings menu item advising the user they can set up the feature later in Settings.

Asana ticket can be [found here](https://app.asana.com/0/1207894970935603/1208157651039716/f) 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the RRM Setup CTA Banner's "Maybe later" dismissal CTA is clicked:
  * The banner should be dismissed for two weeks.
  * A tooltip should appear pointing to the Settings menu item with the following copy:
    * _You can always set up Reader Revenue Manager from Settings later_
  * The tooltip should have the same look and feel as other similar tooltips, for example the corresponding Consent Mode tooltip:
![image](https://github.com/user-attachments/assets/226314a5-5177-4cf9-9542-81f92f308ebe)
* After two weeks has elapsed, the banner should be shown again, this time with "Don’t show again" for the dismissal CTA text. Upon clicking the CTA:
  * The banner should be dismissed permanently.
  * The tooltip pointing to the Settings menu item should appear again, as described above.

## Implementation Brief

- [x] In `assets/js/modules/reader-revenue-manager/components/dashboard/ReaderRevenueManagerSetupCTABanner.js`.<br />
  - [x] Use of prompts infrastructure.
    * Use `dismissPrompt` and remove use of `dismissItem` as the banner needs to be shown again after two weeks.
    * Use `getPromptDismissCount` selector to get the dismiss count.
    * Use `hasFinishedResolution( 'getDismissedPrompts', [] )` to check if dismissed prompts have been loaded or not. This is necessary in order to avoid glitches in banner when it shows `Maybe later` at first, but immediately change it to `Don't show again` text once the dismissed prompts data is available.
    * In `onDismiss` function, inside `finally` block, if `dismissCount` is less than `1`, dismiss the banner using `dismissPrompt` by passing slug as `READER_REVENUE_MANAGER_SETUP_BANNER_DISMISSED_KEY` and expiration as two week in seconds. A similar implementation can be seen [here](https://github.com/google/site-kit-wp/blob/0e32045bb530d8bd22b5dde634da1510beeefa36/assets/js/components/consent-mode/ConsentModeSetupCTAWidget.js#L213-L221).<br />
  - [x] Tooltip after dismissal.
    * Import `AdminMenuTooltip`, `useShowTooltip` and `useTooltipState` from `AdminMenuTooltip` component.
    * Check if tooltip should be visible using `useTooltipState` hook and pass `READER_REVENUE_MANAGER_SETUP_BANNER_DISMISSED_KEY` to it. This will return `isTooltipVisible`, a boolean.
    * Use `useShowTooltip` hook which will return a function that would be used to display the tooltip. Receive it in a constant `showTooltip`.
    * In `onDismiss` function before dismissing the banner in `finally` block, call `showTooltip()`. This will set `isTooltipVisible` to true.
    * Inside the component, check if `isTooltipVisible` is `true`, if it is, return `AdminTooltip` component.
      * Title should be empty.
      * Content would be: `You can always enable reader revenue manager from Settings later`
      * dismiss label as `Got it`
      * `tooltipStateKey` set to `READER_REVENUE_MANAGER_SETUP_BANNER_DISMISSED_KEY`.

### Test coverage

* In `assets/js/modules/reader-revenue-manager/components/dashboard/ReaderRevenueManagerSetupCTABanner.test.js`
  * Fix any failing tests.
  * Add tests for prompt behaviour.
  * Add test for tooltip behaviour.

## QA Brief

1. Enable RRM feature in the tester plugin and make sure to disable RRM module in Site Kit settings.

2. Go to dashboard, it should display the setup CTA banner.

3. Click on `Maybe later`, it will dismiss the banner and will display the tooltip with the text as mentioned in IB.

4. Install [Time Travel extension](https://chromewebstore.google.com/detail/time-travel/jfdbpgcmmenmelcghpbbkldkcfiejcjg?hl=en&pli=1) in chrome and set the date to 15 days or 1 month later. Reload the page.

5. The banner should be visible again. Dismiss the banner again using `Maybe later` CTA, it would again display the tooltip.

6. Change the date in extension further to 1 month and reload the page, the banner should not be visible anymore.

## Changelog entry

* Show the Reader Revenue Manager module's setup banner again two weeks after being dismissed, and show a tooltip to let the user know it can be set up later in Settings.

**Comment by nfmohit** [comment]
AC ✅

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When I clicked on `Maybe later`, it dismissed the banner and the tooltip with the text as mentioned in AC is displayed.
- When I set the date to 1 month later, the banner is visible again. 
- When I dismiss the banner again using `Maybe later` CTA, it displays the tooltip.
- When I set the date to 1 month later and reload the page, the banner is not visible anymore.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/b82488ac-dec1-455c-a5f4-aa668fc94c45)
![image](https://github.com/user-attachments/assets/5b7a05fb-71ff-44c7-b834-a248c628437c)

</details>
