### ISSUE TITLE
Include 'Learn more' link on RRM set up screen

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9259]
## Feature Description

On the Reader Revenue Manager setup screens it would be nice to include a `Learn more` link so the user can find out more about the feature before setting it up.  

![Image](https://github.com/user-attachments/assets/b29be050-4fc9-4f8d-b17c-8d497b164796)

Asana ticket can be [found here](https://app.asana.com/0/1207894970935603/1208146362275136/f) 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [RRM setup screen with the **Create publication** CTA](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-setup-setupmain--no-publications) should include a "Learn more" link.
* The "Learn more" link should be appended to the second descriptive line of the copy:
  * _Once you have created your publication, it is submitted for review. [Learn more]()_
* It should link to the "Get started with Reader Revenue Manager" support article: https://support.google.com/news/publisher-center/answer/11449914

## Implementation Brief

* [ ] Update `assets/js/modules/reader-revenue-manager/components/common/PublicationCreate.js`, use `createInterpolateElement` to add a Learn More link, linking to the support article in the AC.
   * https://github.com/google/site-kit-wp/blob/c7620667ac71e8323359c461b93e6b6a6a8d04ab/assets/js/modules/reader-revenue-manager/components/common/PublicationCreate.js#L80-L85

### Test Coverage

* No additional tests required. Check no new failures occur.

## QA Brief

1. Enable RRM feature in tester plugin.
2. Setup the feature and make sure that you don't have any publications setup already.
3. In the setup screen, you must see the `Learn More` link pointing to https://support.google.com/news/publisher-center/answer/11449914

## Changelog entry

* Include a "Learn more" link on the Reader Revenue Manager setup screen shown when the user doesn't have an existing publication.

**Comment by techanvil** [comment]
I've raised a question about this issue on its [Asana task](https://app.asana.com/0/1207894970935603/1208146362275136/f), and will hold off adding AC while we consider it further.

**Comment by techanvil** [comment]
Hi @wpdarren @aaemnnosttv, I'm assigning this to you for visibility, please can you take a look at the linked Asana task when you have a moment?

**Comment by aaemnnosttv** [comment]
@techanvil I've replied on that, thanks for raising it.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv! I've added AC for this issue, including a more contextually relevant link as per your suggestion on Asana.

**Comment by nfmohit** [comment]
AC ✅

**Comment by techanvil** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This was verified good. Moving ticket to approval.

- The RRM setup screen with the Create publication CTA includes a "Learn more" link.
   The "Learn more" link is appended to the second descriptive line of the copy:
   `Once you have created your publication, it is submitted for review. Learn more`

   <Details>

   ![Image](https://github.com/user-attachments/assets/096cf2f9-b288-4d40-8791-0265da0294ee)

   </Details>

- 'Learn more' links to the "Get started with Reader Revenue Manager" support article: 
   https://support.google.com/news/publisher-center/answer/11449914
   <Details>

   ![Image](https://github.com/user-attachments/assets/c50ff087-d058-4374-ad09-690343be180f)

   </Details>

- On accounts with existing publications, there was no 'Learn More' CTA.
   <Details>

   ![Image](https://github.com/user-attachments/assets/d99266e5-b1d1-4547-bbf0-0a5890c1e3c9)

   </Details>
