### ISSUE TITLE
RRM Setup CTA Banner flickers when actioning the CTA

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9260]
## Bug Description

The Setup CTA Banner briefly flickers when the CTA is actioned before the page navigates to the OAuth flow.

https://github.com/user-attachments/assets/f1017540-6b79-4550-935b-88004e9d2338

The Asana ticket can be [found here](https://app.asana.com/0/1207894970935603/1208157651039736/f). 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Reader Revenue Manager setup CTA banner should not flicker (disappear and reappear) at any point in its lifecycle.

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Closing, as this is no longer reproducible.
