### ISSUE TITLE
Improve UX when going back from OAuth and behaviour when redoing process

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9261]
## Bug Description

Related to setting up the RRM module. When navigating back from the initial OAuth screen, the `redo setup` CTA is shown. Clicking on this CTA proceeds through the OAuth flow again, but when returning to SK, the RRM setup flow is not continued. 

Evan mentioned:
>  My hunch here is that the redo setup that you're clicking is just a generic link in response to the unsatisfied scopes. It wouldn't be expected to go to the module setup afterwards in this scenario.

Tom responded:
> I think you are right about the generic aspect, but it's still something that could be improved in terms of the UX.

Asana ticket can be [found here](https://app.asana.com/0/1207894970935603/1208157651039742/f) 

https://github.com/user-attachments/assets/7426edcf-18ff-4c49-8030-9ca22beb69b5

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Any time a module set up is actioned, and the user enters the OAuth set up flow but then uses the back button to return to Site Kit and the "Site Kit can’t access necessary data" unsatisfied scopes notification is displayed, clicking on **Redo setup** and proceeding through the OAuth flow should result in the module setup being automatically continued when returning to Site Kit.
- By way of example, this includes but is not limited to the following scenarios:
  - Clicking **Connect now** on the [AdSense Connect CTA](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-widgets-adsenseconnectcta--ready) on the dashboard.
  - Clicking **Set up Google Analytics** on the [Activate Analytics CTA in the Search Traffic widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidgetga4--ready-with-activate-analytics-cta) on the dashboard.
  - Clicking **Connect Analytics** on the [Key Metrics Connect Analytics widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-connectga4ctatilewidget--default) on the dashboard.
  - Clicking **Connect Google Analytics** on the [Audience Segmentation Connect Analytics widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-connectanalyticsctawidget--default) on the dashboard.
  - Clicking **Set up Reader Revenue Manager** on the [Reader Revenue Setup CTA](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-dashboard-readerrevenuemanagersetupctabanner--default) on the dashboard.
  - Clicking any of the **Set up {service name}** CTAs on the [**Connect More Services** tab](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/settings--connect-more-services) on the Settings screen.
  
![Image](https://github.com/user-attachments/assets/806728a9-d989-4c5b-a6e1-2f72fd4d939f)

## Implementation Brief

* [ ] Update `assets/js/hooks/useActivateModuleCallback.js`, before `navigateTo` is called:
   * Store the setup module slug in the session storage using, expiring in 5 minutes `setItem( 'module_setup', moduleSlug, { ttl: 300 } )`.

* [ ] Update `assets/js/components/notifications/UnsatisfiedScopesAlert.js`:
   * Create new component state, eg. `inProgressModuleSetup`, with `false` default value.
   * In a `useMount`, use `getItem` to check if there is a value in session storage, and set the module slug into component state.
   * Create a new callback function `redoModuleSetup` using useCallback, replicating the standard module activation:
      https://github.com/google/site-kit-wp/blob/0ec1298d1ad840c11037ca73fff9405712569b46/assets/js/components/settings/SetupModule.js#L57-L82
   * If `inProgressModuleSetup` is truthy:
      * Update the actions to render a `CTALink` without a `ctaLink` prop, with a `ctaLabel` "Redo {Module Name} setup" and `onCTAClick` callback calling the `redoModuleSetup` callback created above. Get the module name using the `getModule` selector on the `CORE_MODULES` store.
        https://github.com/google/site-kit-wp/blob/0ec1298d1ad840c11037ca73fff9405712569b46/assets/js/components/notifications/UnsatisfiedScopesAlert.js#L204-L213

 * [ ] Update `assets/js/components/setup/ModuleSetup.js`, within the `finishSetup` definition, call `deleteItem( 'module_setup' )`:
      https://github.com/google/site-kit-wp/blob/0ec1298d1ad840c11037ca73fff9405712569b46/assets/js/components/setup/ModuleSetup.js#L62-L87

### Test Coverage

* Update `assets/js/hooks/useActivateModuleCallback.test.js` to test for new session storage value is being stored.
* Create new tests for `assets/js/components/notifications/UnsatisfiedScopesAlert.js` confirming the correct CTA and actions render based on session storage and existing conditions.

## QA Brief

* Enable the `rrmModule` feature flag using the tester plugin.
* Set up Site Kit.
* When you're in the SK dashboard, you should be able to see the CTA banner to set up RRM. Click on the CTA. You should be redirected to the OAuth screen.
* When you're in the OAuth screen, simply go back to the SK dashboard clicking on the "Back" button in the browser.
* When you're back in the SK dashboard, you should be able to see the "Site Kit can’t access necessary data" notification.
* Verify that clicking on the CTA retries the Reader Revenue Manager module setup.
* Verify setup for other modules as outlined in the AC and ensure that they're also retried from this notification.

## Changelog entry

* Ensure that the setup flow for a module is automatically continued when clicking the "Redo setup" CTA on the "Site Kit can’t access necessary data" unsatisfied scopes notification.

**Comment by nfmohit** [comment]
Just to add: This issue isn't specific to the RRM module, but any other SIte Kit module in general. We can address it as part of the RRM epic, but it can also be a non-epic general enhancement issue. CC: @ivonac4 @techanvil @wpdarren @aaemnnosttv

**Comment by nfmohit** [comment]
After [an internal discussion](https://fueled10up.slack.com/archives/C077DB69US2/p1725501267453779), we've decided to decouple this from the RRM epic.

**Comment by nfmohit** [comment]
AC ✅

**Comment by benbowler** [comment]
Added additional time for tests and detailed QA.

**Comment by nfmohit** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@nfmohit I am unable to verify that the CTA says "Redo Reader Revenue Manager setup".  I see the usual`Redo settup` CTA.   Tested this initially with RRM and Analytics, and clicked back on the browser as per the QAB.   I have cleared cache and used a few different sites including a new one.  I am on the develop branch.   Please could you look in this for me?

**Comment by nfmohit** [comment]
> ### QA Update: ❌
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/20284937?s=64&amp;u=63c3839dcc0b61268b55750651fd0c0a972909b2&amp;v=4">@nfmohit](https://github.com/nfmohit) I am unable to verify that the CTA says "Redo Reader Revenue Manager setup". I see the usual`Redo setup` CTA. Tested this initially with RRM and Analytics, and clicked back on the browser as per the QAB. I have cleared cache and used a few different sites including a new one. I am on the develop branch. Please could you look in this for me?

Hi @wpdarren, thank you for sharing your observations. This is a mistake from my end as that statement in the QAB is no longer valid. We decided to use the original CTA the notice uses, see discussion [here](https://github.com/google/site-kit-wp/pull/9728#discussion_r1867631464). I've updated the QAB. Back to you, thank you!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When a module set up is actioned, and the user enters the OAuth set up flow but then uses the back button to return to Site Kit and the "Site Kit can’t access necessary data" unsatisfied scopes notification is displayed, clicking on Redo setup and proceeding through the OAuth flow results in the module setup being automatically continued when returning to Site Kit.

I checked the following scenarios:

- Clicking Connect now on the [AdSense Connect CTA](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-widgets-adsenseconnectcta--ready) on the dashboard.
- Clicking Set up Google Analytics on the [Activate Analytics CTA in the Search Traffic widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidgetga4--ready-with-activate-analytics-cta) on the dashboard.
- Clicking Connect Analytics on the [Key Metrics Connect Analytics widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/key-metrics-connectga4ctatilewidget--default) on the dashboard.
- Clicking Connect Google Analytics on the [Audience Segmentation Connect Analytics widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-connectanalyticsctawidget--default) on the dashboard.
- Clicking Set up Reader Revenue Manager on the [Reader Revenue Setup CTA](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-dashboard-readerrevenuemanagersetupctabanner--default) on the dashboard.
- Clicking any of the Set up {service name} CTAs on the [Connect More Services tab](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/settings--connect-more-services) on the Settings screen.

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/af124957-05fe-409c-be51-a9f03a584dc4)
![Image](https://github.com/user-attachments/assets/a9213a61-841f-4e13-8843-2790ff6534b0)
![Image](https://github.com/user-attachments/assets/21ff24f7-8814-488b-ab63-12e8bd01df74)
![Image](https://github.com/user-attachments/assets/3bad28a5-50a8-4565-8751-e25967b5021a)

</details>
