### ISSUE TITLE
Remove RRM onboarding state notice when state changes

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#9262]
## Feature Description

Raised in RRM bug bash [here](https://app.asana.com/0/1207894970935603/1208146362275150/f).

Currently, when an RRM publication has onboarding states of either `ONBOARDING_ACTION_REQUIRED` or `PENDING_VERIFICATION`, we display an onboarding state notice in the RRM settings screens.

The problem in question is more prevalent in the case of `ONBOARDING_ACTION_REQUIRED`, where we display the following notice:

![image](https://github.com/user-attachments/assets/943ef53c-d563-4d12-abbb-1a8af08061ee)

Once the user navigates to the Publisher Center upon clicking on the CTA, actions their remaining steps, and returns to Site Kit, they still see the same notice. This has the potential to confuse the user as in reality, the publication no longer requires any further setup.

This happens because Site Kit stores the publication's onboarding state in the WordPress database and syncs it every 24 hours, i.e. if the user in the above example returns to Site Kit after the next sync, they'd see that the notice no longer exists. However, we should look into improving this so that the UX is further refined.

As part of triage, we've identified two potential approaches here:

1. Upon clicking the CTA in the notice, we simply remove the notice until at least the next sync.
2. Upon clicking the CTA, we wait for the user to come back to the Site Kit tab from Publisher Center. Once they do, immediately sync the onboarding state in the background and remove the notice if applicable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Upon clicking on the CTA to visit the Publisher Center from one of the notifications that indicate the publication's onboarding state, the publication's onboarding state stored in Site Kit should be synced if the user comes back to the originating (Site Kit) browser tab after at least 15 seconds.
	* Currently, these notifications are:
		* Publication onboarding state notice: [google.github.io/site-kit-wp/storybook/develop?path=/story/modules-readerrevenuemanager-common-publicationonboardingstatenotice](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-common-publicationonboardingstatenotice)
		* RRM module setup success notification: [google.github.io/site-kit-wp/storybook/develop?path=/story/modules-readerrevenuemanager-components-dashboard-rrmsetupsuccesssubtlenotification](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-dashboard-rrmsetupsuccesssubtlenotification)
	* The sync should happen once for every click on the CTA, i.e. if the user navigates away (without clicking on the CTA) and comes back, the sync should not happen.

## Implementation Brief

* [x] Update `assets/js/modules/reader-revenue-manager/components/common/PublicationOnboardingStateNotice.js` and `assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.js`:
   * [x] [Use the `useRefocus` hook](https://github.com/google/site-kit-wp/blob/b6c7c59c9bece36c8b0138d2e3d4f05a2f09479a/assets/js/hooks/useRefocus.js#L32), passing the timeout value of 15 seconds (as 15000 milliseconds), to dispatch the `syncPublicationOnboardingState` action when triggered.

 * [x] Update the `syncPublicationOnboardingState` action so that it can sync publications regardless of if the settings have been saved:
   * [x] Move the check for RRM being connected from `syncPublicationOnboardingState` to `maybeSyncPublicationOnboardingState()`:
https://github.com/google/site-kit-wp/blob/36b8bcd74d85fd8fa3f560c6b8eaf6ca5031c84a/assets/js/modules/reader-revenue-manager/datastore/publications.js#L71-L80
    * [x] Move the following check from `syncPublicationOnboardingState` to `maybeSyncPublicationOnboardingState` so that we can sync the state regardless of it there is already a saved publication ID but retain this check for the action triggered on dashboard load:
    https://github.com/google/site-kit-wp/blob/36b8bcd74d85fd8fa3f560c6b8eaf6ca5031c84a/assets/js/modules/reader-revenue-manager/datastore/publications.js#L89-L97
   * [x] Only set `publicationOnboardingStateLastSyncedAtMs` and save the settings when we're syncing the currently saved publication. (ie. when `hasSettingChanged('publicationID')` return `false`):
https://github.com/google/site-kit-wp/blob/36b8bcd74d85fd8fa3f560c6b8eaf6ca5031c84a/assets/js/modules/reader-revenue-manager/datastore/publications.js#L132-L135

### Test Coverage

* Update the tests for both the `PublicationOnboardingStateNotice` and `RRMSetupSuccessSubtleNotification` component to ensure the `syncPublicationOnboardingState` action is *not* dispatched on initial load or if the user refocusses within 15 seconds, and *is* dispatched if the user refocusses after 15 seconds.

### RRM setup

1. Turn on the `rrmModule` feature flag on the tester plugin.
2. Set up Site Kit.
3. Keep the tester plugin settings open in a new tab.
4. In the tester plugin, force Reader Revenue Manager publication status to either action required or pending verification.
5. Start setting up the Reader Revenue Manager module.
6. Once a publication is selected, verify that you see the publication onboarding state notice. Click on its CTA. You should be navigated to the Publisher Center.
7. Go to the tester plugin tab opened in step 3. Force the status to onboarding complete.
8. Go back to the RRM setup tab (ensure it has been at least 15 seconds).
9. Verify that the setup screen shows a loading progress and once it is complete, the notice no longer appears.

### RRM setup success notification

10. Right after step 9, perform step 4 and reload the page. Complete RRM setup. You should land back in the Site Kit dashboard with a success notification.
11. Click on the CTA. You should be navigated to the Publisher Center.
12. Go to the tester plugin tab opened in step 3. Force the status to onboarding complete.
13. Go back to the SK dashboard tab (ensure it has been at least 15 seconds).
14. Verify that the success notification changes to the publication-approved scenario (it may take a few seconds).

### RRM settings view

15. Disconnect the RRM module.
16. Perform steps 4, 5, and 6. Go back to the RRM setup tab and complete the module setup.
17. Go to Site Kit Settings -> Reader Revenue Manager. Verify that you see the publication onboarding state notice. Click on its CTA. You should be navigated to the Publisher Center.
18. Go to the tester plugin tab opened in step 3. Force the status to onboarding complete.
19. Go back to the RRM settings tab (ensure it has been at least 15 seconds).
20. Verify that the notice no longer appears (it may take a few seconds).

### RRM settings edit

21. Perform steps 15 and 16.
22. Go to Site Kit Settings -> Reader Revenue Manager -> Edit. Verify that you see the publication onboarding state notice. Click on its CTA. You should be navigated to the Publisher Center.
23. Go to the tester plugin tab opened in step 3. Force the status to onboarding complete.
24. Go back to the RRM settings tab (ensure it has been at least 15 seconds).
25. Verify that the notice no longer appears (it may take a few seconds).

### Other testing

26. Re-do the QAB for #8797 and verify that it still passes.

## Changelog entry

* When a user clicks the CTA to visit the Publisher Center from one of the onboarding state notifications, resync the onboarding state upon returning to the Site Kit browser tab and update/hide the notification if the state has changed.

**Comment by techanvil** [comment]
Hey @nfmohit, it looks like `PublicationOnboardingStateNotification` is a typo in the AC and should be `PublicationOnboardingStateNotice`.

That aside, it's worth noting that these component names are more of an implementation detail and are not so useful in the AC when considering them for a non-developer perspective, e.g. QA, PMs etc.

As a quick way to improve it I'd suggest linking to the relevant stories for each component:
- `PublicationOnboardingStateNotification`: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-common-publicationonboardingstatenotice
- `RRMSetupSuccessSubtleNotification`: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-readerrevenuemanager-components-dashboard-rrmsetupsuccesssubtlenotification

**Comment by nfmohit** [comment]
AC updated, thank you @techanvil!

**Comment by techanvil** [comment]
That's great, thanks @nfmohit!

AC :white_check_mark:

**Comment by benbowler** [comment]
Bumped the estimate a little bit for the test requirements.

**Comment by techanvil** [comment]
Thanks @benbowler.

- It looks like we're going to keep `syncPublicationOnboardingState()` based on the conversation on [Slack](https://fueled10up.slack.com/archives/C077DB69US2/p1725538088207679?thread_ts=1725528698.262269&cid=C077DB69US2). I'd suggest waiting until that's fully agreed and then updating this IB to remove the ambiguity.
- We already have a [`useRefocus()` hook](https://github.com/google/site-kit-wp/blob/b6c7c59c9bece36c8b0138d2e3d4f05a2f09479a/assets/js/hooks/useRefocus.js#L32) that can be reused :)

**Comment by nfmohit** [comment]
@benbowler I'm not the IB reviewer here but I've made some updates to the relationship between this issue (#9262) and #9149. In summary:

- I've set this issue ([#9262](https://github.com/google/site-kit-wp/issues/9262)) to be a blocker for [#9149](https://github.com/google/site-kit-wp/issues/9149), as this is a P0 launch blocker and we expect this to be implemented/released before [#9149](https://github.com/google/site-kit-wp/issues/9149).
	- That way, even if [#9149](https://github.com/google/site-kit-wp/issues/9149) removes the `syncPublicationOnboardingState()` later, it should also take care of updating the implementation introduced here for synchronizing the onboarding state.
	- The intention here is not to block this higher-priority issue.

@techanvil Does this sound good to you?

CC: @ankitrox

**Comment by nfmohit** [comment]
@benbowler An additional note: One of the consumers for the `PublicationOnboardingStateNotice` is the RRM setup flow, i.e. `assets/js/modules/reader-revenue-manager/components/setup/SetupForm.js`. In this location, I believe the `syncPublicationOnboardingState` will not work because it only works when the module is already connected. We might have to work around that somehow.

It's also worth noting that we're in the discussions of removing the `PublicationOnboardingStateNotice` (or at least its CTA) from the RRM setup flow as [this was reported to be confusing for users in the bug bash](https://app.asana.com/0/1207894970935603/1208035131189745/f). However, that has been triaged to be a post-launch initiative. Sigal has kindly proposed to remove the CTA from this notification in the setup flow and update the copy. If that is agreed upon, we can prioritise that issue as well so that we can stick to the approach defined in this issue.

CC: @techanvil

**Comment by techanvil** [comment]
Incidentally if we're extracting the action as per my above comment, that should work in both the setup and settings flow, so we shouldn't need to wait for the decision on whether to remove the CTA from the setup flow as per https://app.asana.com/0/1207894970935603/1208035131189745.

**Comment by nfmohit** [comment]
> Thanks @nfmohit, that's a good point. Looking into it a bit more, it looks like we need to remove the check for the publication _not_ having been changed in settings, as on the setup screen we won't have saved it yet anyway (although this is moot if we remove it from setup), and on the settings screen the user could have selected a property from the dropdown, clicked the CTA and completed the steps and returned to SK without saving the setting.
> 
> https://github.com/google/site-kit-wp/blob/36b8bcd74d85fd8fa3f560c6b8eaf6ca5031c84a/assets/js/modules/reader-revenue-manager/datastore/publications.js#L89-L97
> 
> So, effectively it's looking like we need to lift this block of code to a new action and use that, with a few tweaks (it needs to retrieve the current settings at the top, and at the end, it should only save the settings if the property is the currently saved one).
> 
> https://github.com/google/site-kit-wp/blob/36b8bcd74d85fd8fa3f560c6b8eaf6ca5031c84a/assets/js/modules/reader-revenue-manager/datastore/publications.js#L99-L135

@techanvil what you suggested sounds good to me, thank you!

**Comment by techanvil** [comment]
> Hey @techanvil, I updated the IB with an implementation that doesn't require a new action to be created. Let me know if I've missed something here that requires a new action for this case.

Thanks @benbowler. I think we can take the approach you've suggested and not extract an additional action, however a couple more changes are needed to `syncPublicationOnboardingState()`:

- We also need to lift the check for RRM being connected out to `maybeSyncPublicationOnboardingState()`:
https://github.com/google/site-kit-wp/blob/36b8bcd74d85fd8fa3f560c6b8eaf6ca5031c84a/assets/js/modules/reader-revenue-manager/datastore/publications.js#L71-L80
- We should only set `publicationOnboardingStateLastSyncedAtMs` and save the settings when we're syncing the currently saved publication. In other words, when `hasSettingChanged('publicationID')` return `false`.
https://github.com/google/site-kit-wp/blob/36b8bcd74d85fd8fa3f560c6b8eaf6ca5031c84a/assets/js/modules/reader-revenue-manager/datastore/publications.js#L132-L135

A couple more points

- There's no need to keep track of `Date.now()`, just pass 15,000 milliseconds as the second argument to `useRefocus()`.
- The note re marking as blocked by #9149 at the top of the IB is stale, and can be removed.

**Comment by techanvil** [comment]
Thanks for the update @benbowler!

IB :white_check_mark:

**Comment by techanvil** [comment]
Hey @nfmohit, thanks for spotting this.

Showing the loading state is not necessarily a bad thing, IMO, because it does let the user know we are indeed reloading the list of publications. Indeed, if the list of publications were to completely change due to the update, it would be better to have given the user a visual heads up via the loading state rather than simply update the list in situ.

So, I think calling `resetPublications()` could be the way to go here, at least in the short term. An alternative could be to dispatch 		`fetchGetPublications()` prior to the call to `getPublications()`, this would avoid the loading state, but as mentioned I don't think we need to do that here.

Either way, though, there's another minor issue which is the **Save** button briefly changes to **Confirm changes** before reverting to **Save** again when calling `syncPublicationOnboardingState()`, this is due to the settings being in a changed state while waiting for the save:

https://github.com/google/site-kit-wp/blob/caafd41a315055ad1142b8f6b35957060fc80e34/assets/js/modules/reader-revenue-manager/datastore/publications.js#L127-L135

This suggests that a more correct solution could be to add a `POST sync-publication-onboarding-state` endpoint so we handle the sync on the backend, and then call `fetchGetSettings()` after this to update the saved settings state and avoid the brief moment when the settings are changed on the client side (or something along those lines).

I guess it depends how much of an issue we consider this brief flash of the CTA text to be. I'd say it's not critical for launch, and we can tackle it post launch once https://github.com/google/site-kit-wp/issues/9149 has been implemented.

WDYT?
