### ISSUE TITLE
Show 'Display visitor groups in dashboard' toggle even if GA is disconnected

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9264]
## Bug Description
This is related to Audience Segmentation
- Currently, when Google Analytics is disconnected, we can't see the  **Display visitor groups in dashboard** toggle at the SK Admin settings
- The toggle should appear regardless of whether GA module is connected or not
- The Google connect CTA isn't currently governed by the toggle but by the Analytics.

Refer to video further down.

## Steps to reproduce

1. Activate the `audienceSegmentation` feature flag
2. Disconnect Google Analytics module
3. Go to SK settings > Admin settings
4. *Display visitor groups in dashboard** toggle is not present.

## Screenshots

  <Details>
  
   https://github.com/user-attachments/assets/f56fd871-5111-41a2-9ae1-edf3b327539f

  </Details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The **Settings > Admin Settings > Visitor groups** section should always be shown, with the  **Display visitor groups in dashboard** toggle present, when the current user has set up the Audience Segmentation feature.

## Implementation Brief

* [x] Within `SettingsAdmin`:
  * [x] Retrieve the list of `configuredAudiences` for the current user via the `getConfiguredAudiences()` selector.
  * [x] Update the condition for rendering the `SettingsCardVisitorGroups` to be `audienceSegmentationEnabled && ( isAnalyticsConnected || !!configuredAudiences )`

https://github.com/google/site-kit-wp/blob/107a1d0924164ff4e8d5d76c6716f07eea5d0a4c/assets/js/components/settings/SettingsAdmin.js#L149-L153

### Test Coverage

* No new tests needed.

## QA Brief

1. Enable the `audienceSegmentation` feature flag
2. Set up the Analytics module and enable the Audience Segmentation.
3. Disconnect Google Analytics module
4. Go to SK settings > Admin settings
5. *Display visitor groups in dashboard** toggle should be present.

### Regression

1. Disable the `audienceSegmentation` in tster plugin.

2. Go to `Site Kit > Settings > Admin Settings`, there shouldn't be any console error related to `audience-settings` datapoint.

## Changelog entry

* Show the "Display visitor groups in dashboard" toggle in the Site Kit Admin settings even when Google Analytics is disconnected.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

 @ankitrox , I just want to clarify one scenario:  ⚠️ 
If the user hasn't enabled any groups yet and we disconnect Analytics, the 'Visitor groups' setting will not be available at the settings page. I assume this is expected in that case?

____________________________________________

Testing based on the AC is as expected: 
- The AC point was tested good. As long as user has enabled groups one time, the 'Visitor groups' setting and toggle are there even if Analytics is disconnected. ✅ 
  <Details>

   https://github.com/user-attachments/assets/249dd184-3838-4b6c-abc4-de0c8447cf13

  </Details>

-

**Comment by ankitrox** [comment]
@kelvinballoo If the analytics is disconnected, the toggle won't show. This is a correct behaviour according to the [current implementation](https://github.com/google/site-kit-wp/blob/40f5363b0a49a3c24126d76b44e20cd1c22e919f/assets/js/components/settings/SettingsAdmin.js#L153-L158)

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Clarified with Ankit that with Analytics disconnected, the toggle won't show only when the audience segmentation isn't set up.
If the audience segmentation is set up and we disconnect analytics, the toggle should be there. This behaviour is as expected.

Moving ticket to Approval.

Test is successful based on the AC: 
- As long as user has enabled groups one time, the 'Visitor groups' setting and toggle are there even if Analytics is disconnected. ✅ 
  <Details>

   https://github.com/user-attachments/assets/249dd184-3838-4b6c-abc4-de0c8447cf13

  </Details>

**Comment by techanvil** [comment]
Assigning back to you @ankitrox to address the regression this has introduced, as detailed here: https://github.com/google/site-kit-wp/pull/9349/files#r1766931201

**Comment by techanvil** [comment]
Back to you @kelvinballoo to verify the regression has been fixed.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

I updated my test site to the latest main branch, and when I go to the settings screens, no error appears.  The issue [reported here](https://github.com/google/site-kit-wp/issues/9318#issuecomment-2361033926) appears to be fixed so moving this back to approval.
