### ISSUE TITLE
RRM Setup CTA Banner graphic can overflow the rounded corner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9271]
## Bug Description

The bottom right-hand corner of the graphic in the RRM Setup CTA Banner can overflow the rounded corner of the banner at some viewports.

## Steps to reproduce

1. View the RRM Setup CTA Banner on the dashboard at a viewport between ~1200-1280px wide.
2. See the graphic overflow the rounded bottom right-hand corner.

## Screenshots

![image](https://github.com/user-attachments/assets/9f5712cb-fc14-4063-b506-ed5ae2593a7b)

![image](https://github.com/user-attachments/assets/56c92757-eade-42c5-9342-70f9bf7a5756)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.134.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The bottom right-hand corner of the graphic in the RRM Setup CTA Banner should not overflow the rounded corner of the banner in any viewport.

## Implementation Brief

* [ ] Update `assets/sass/widgets/_widgets.scss` adding `overflow: hidden` to the block for `.googlesitekit-plugin .googlesitekit-widget`

### Test Coverage

* As this is a broad change, confirm this does not impact other widgets in the app, and confirm VRTs are not effected on any other component.

## QA Brief

* Load the RRM setup CTA banner either on the dashboard, or in storybook.
* Resize the window through from small mobile, through to desktop width and confirm that the SVG graphic never escapes the banner rounded corners.

## Changelog entry

* Improve Reader Revenue Manager setup CTA banner so that its graphic does not overflow the container.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kelvinballoo** [comment]
### QA update ⚠️ 

I tested good for the main issue. As I resize the Chrome desktop window, the green graphic is always contained in within the container.
<Details>

https://github.com/user-attachments/assets/2430f8f6-e1d9-4587-baab-003a5cafae32

</Details>

That said, while testing I noticed that on Safari, there are some breakpoints that will not show the image at all. ❌ 

- Refer to the video below for the desktop safari ❌ 
   <Details>
   
   https://github.com/user-attachments/assets/3d7cdd6a-ee78-404b-aca4-dc18fa04c85d

   </Details>

- I went on to test this on smaller breakpoint on an iPhone 15 Pro max (real) on Safari and Chrome browser. I could not see the graphic  ❌ 
   <Details>
   Safari
   
   ![IMG_9792](https://github.com/user-attachments/assets/7b37203e-f44b-45c0-b4d9-87658776cbc6)
   
   Chrome
   ![IMG_9793](https://github.com/user-attachments/assets/3ec9db0b-7719-4132-8e7a-5b028db588e4)


   </Details>


My gut feel is that it's not a regression and maybe it's best to tackle this under another ticket.
Do let me know.

**Comment by benbowler** [comment]
Hey @kelvinballoo, yes, this ticket was such a simple change it couldn't have caused the image not to show at these breakpoints.

As you mentioned, let's go ahead and create a new ticket to address these breakpoints to make sure they match the designs.

**Comment by kelvinballoo** [comment]
### QA update ✅ 

Thanks for confirming @benbowler 
New issue raised here: https://github.com/google/site-kit-wp/issues/9329

The issue in this ticket is resolved. As I resize the Chrome desktop window, the green graphic is always contained in within the container.
Moving ticket to approval.

<Details>

https://github.com/user-attachments/assets/2430f8f6-e1d9-4587-baab-003a5cafae32

</Details>
