### ISSUE TITLE
Test logic within notification registration

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#9273]
## Feature Description

In #8978 and #8979, the `ErrorNotifications.test.js` require "mock" registration of notifications using the new Notifications datastore register function. 

https://github.com/google/site-kit-wp/blob/dc0f77f42b41fa93326ebaa56c473eb2b729726f/assets/js/components/notifications/ErrorNotifications.test.js#L46-L73

This would require us to "copy-paste" code that registers notifications within our tests. In addition to copy-pasting, the main drawback here is that our tests do not actually cover the real production registration code within `register-defaults.js`. So we need a way to cover the logic within this code. We could perhaps create a utility function that wraps production registration code and adds it to a test registry.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Reintroduce test coverage removed as part of #8978, #8979 and #9280.
* Cover any other logic of rendering any notification that happens as part of the registration process. 

## Implementation Brief

* [ ] Update `tests/js/utils.js`
  * Add `provideNotificationsRegistration` util function
    * It should accept `registry` and `extraData` arguments
    * Use `createNotifications` with provided `registry` argument to include notifications into the test registry. You can check its usage in `assets/js/googlesitekit-notifications.js`
    * If `extraData` is passed, it should be object consisting of `{id, settings}` data, which can be forwarded to the `registerNotification` action of `CORE_NOTIFICATIONS` datastore, to include extra notification registration if needed . 
* [ ] Return referenced tests in AC,  `provideNotificationsRegistration` util will include the notifications in the test registry so notifications can be rendered

### Test Coverage

* No changes needed, issue is about tests

## QA Brief

* Only the Unsatisfied Scopes Alert logic has changed in a very minor sense - so the [QAB for this component should be followed](https://github.com/google/site-kit-wp/issues/8978#issue-2394412603) (point 2 only).
* All other changes are purely within the tests (non-user facing). So this won't require QA as long as the CI tests pass.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs here make sense, moving to IB 🙂

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by jimmymadon** [comment]
I have bumped up the estimate here as this issue will have to fix tests from another newly refactored notification - #9280. Have updated the AC. The IB won't change here - but more work will have to be done in Execution.
